### ISSUE TITLE
httpd failed to build on macOS 12.3.1

### ISSUE THREAD

**Issue by JLP04** [Homebrew/homebrew-core#100189]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/95e2d844e3321988b6a7ee5be48a4f1e
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was running `brew upgrade` because I wanted to upgrade my homebrew packages and at the end, it decided it had to reinstall a few packages with broken linkage from source, one of which was httpd. When it tried to do so, it failed, so I decided to try running `brew reinstall -s httpd`. This also failed with the same error. 

### What happened (include all command output)?

`brew install -s httpd
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from ee4ef876c to 1baa34015.
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
Updated 4 casks.

Warning: httpd 2.4.53_1 is already installed and up-to-date.
To reinstall 2.4.53_1, run:
  brew reinstall httpd
Jasons-MacBook-Pro:~ jasonpeskin$ brew reinstall -s httpd
==> Downloading https://dlcdn.apache.org/httpd/httpd-2.4.53.tar.bz2
Already downloaded: /Users/jasonpeskin/Library/Caches/Homebrew/downloads/711148bf383a97814c2bff7616a4cdff4abd24a82566d06f88b1b17d71018403--httpd-2.4.53.tar.bz2
==> Reinstalling httpd 
==> ./configure --enable-layout=Slackware-FHS --prefix=/usr/local/Cellar/httpd/2
==> make
==> make install
Last 15 lines from /Users/jasonpeskin/Library/Logs/Homebrew/httpd/03.make:
make[4]: Nothing to be done for `local-shared-build'.
Building shared: mod_heartbeat.la mod_heartmonitor.la
make[4]: Nothing to be done for `local-shared-build'.
Building shared: mod_dav.la
make[4]: Nothing to be done for `local-shared-build'.
Building shared: mod_status.la mod_autoindex.la mod_asis.la mod_info.la mod_suexec.la mod_cgid.la mod_cgi.la
make[4]: Nothing to be done for `local-shared-build'.
Building shared: mod_dav_fs.la
make[4]: Nothing to be done for `local-shared-build'.
Building shared: mod_dav_lock.la
make[4]: Nothing to be done for `local-shared-build'.
Building shared: mod_vhost_alias.la mod_negotiation.la mod_dir.la mod_actions.la mod_speling.la mod_userdir.la mod_alias.la mod_rewrite.la
make[4]: Nothing to be done for `local-shared-build'.

make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

`

### What did you expect to happen?

I expected it to reinstall httpd from source without error. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew reinstall -s httpd`. `brew install -s httpd` may also work.
```

**Comment by leonardoapolinario** [comment]
In my case the solution is grant access to httpd folder

sudo chown -R $(whoami) /usr/local/Cellar/httpd/

**Comment by JLP04** [comment]
It's still not working for me.

**Comment by Bo98** [comment]
This does seem like some permission problem:

```
chmod: Unable to change file mode on /usr/local/Cellar/httpd/2.4.53_1/bin/suexec: Operation not permitted
```

I'm also however interested in why there's broken linkage to begin with. What does `brew linkage httpd` output?

**Comment by JLP04** [comment]
`brew linkage httpd` outputs the following: 

```
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libexpat.1.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/apr/lib/libapr-1.0.dylib (apr)
  /usr/local/opt/brotli/lib/libbrotlicommon.1.dylib (brotli)
  /usr/local/opt/brotli/lib/libbrotlienc.1.dylib (brotli)
  /usr/local/opt/libnghttp2/lib/libnghttp2.14.dylib (libnghttp2)
  /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (openssl@1.1)
  /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (openssl@1.1)
  /usr/local/opt/pcre2/lib/libpcre2-8.0.dylib (pcre2)
Broken dependencies:
  /usr/local/opt/apr-util/lib/libaprutil-1.0.dylib (apr-util)

```

**Comment by Bo98** [comment]
Ah apologies, try `brew reinstall apr-util` (not from source) and it should work. I'm going to revision bump `apr-util` soon which should fix it properly.

**Comment by JLP04** [comment]
That seems to have fixed it according to `brew linkage`. Thanks.
