### ISSUE TITLE
formula for `mermaid-cli` is not pointing to latest stable. 

### ISSUE THREAD

**Issue by yogurtearl** [Homebrew/homebrew-core#100192]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.4.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: c2eaeed0b5978ef3e455cc29dda7e9e0b7a0670f
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 23a754deb53e4df9b02b581c0075227a34764de6
Core tap last commit: 53 minutes ago
Core tap branch: master
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install latest version of `mermaid-cli` (9.0.3)

Tagged here: 
https://github.com/mermaid-js/mermaid-cli/releases/tag/9.0.3

### What happened (include all command output)?

Formula points to 8.11.0 instead of 9.0.3 (or newer) 

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mermaid-cli.rb#L6

### What did you expect to happen?

Use latest stable version. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install mermaid-cli`
```

**Comment by nandahkrishna** [comment]
Multiple previous attempts to bump this formula have failed. See discussion in https://github.com/Homebrew/homebrew-core/pull/93625 and https://github.com/Homebrew/homebrew-core/pull/83338.

**Comment by Bo98** [comment]
As it stands `mermaid-cli` violates our build-from-source policy. It shows that AUR is the only other package manager (they ship closed source stuff) that ships mermaid-cli.

I think the way forward (unless there's a way to make it fit into Homebrew/core's policies) is to deprecate this and allow a third-party tap with less ties to open source to deal with it.

**Comment by cho-m** [comment]
Another puppeteer-based formula currently under review is #98549 which is trying to defer browser installation user (Firefox in their case).

The tedious way that AUR uses is building `chromium` from source (https://repology.org/project/chromium/versions).

**Comment by carlocab** [comment]
Building `chromium` from source would be a huge pain. Not to mention that they tag new builds as often as multiple times a day.

**Comment by MikeMcQuaid** [comment]
> As it stands `mermaid-cli` violates our build-from-source policy.
> 
> I think the way forward (unless there's a way to make it fit into Homebrew/core's policies) is to deprecate this and allow a third-party tap with less ties to open source to deal with it going forward.

👍🏻

**Comment by cho-m** [comment]
Will proceed with deprecation in #100478.

Since original question was on updating to latest version, also labelled as `wontfix`.

**Comment by cho-m** [comment]
Closing based on decision from Homebrew side.

The way forward for `mermaid-cli` formula would be an external Tap, perhaps maintained by upstream or  someone else. If one is created, it can be considered for documentation at https://docs.brew.sh/Interesting-Taps-and-Forks
