### ISSUE TITLE
emacs 28.1 bottle does not contain `dir` file

### ISSUE THREAD

**Issue by timvisher** [Homebrew/homebrew-core#100190]
[`brew gist-logs`](https://gist.github.com/timvisher/66cf2c43eccda4529eb2e41990e5e842)

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use emacs packaged info manuals.

### What happened (include all command output)?

The manuals included with emacs are not shown when opening info from inside emacs. The initially presenting problem is that there is no `dir` file initialized in the linked directory inside `"$(brew --prefix)"/share/info`:

```
$ ls -lA "$(brew --prefix)"/Cellar/emacs/28.1/share/info/dir
ls: cannot access '/opt/homebrew/Cellar/emacs/28.1/share/info/dir': No such file or directory
```

Running `M-x info RET` inside `emacs -Q` at that point yields a buffer that doesn't contain, for instance, `Htmlfontify`:

```
File Edit Options Buffers Tools Info Help
No next, prev or up links  --  This is the top of the INFO tree
(dir)Top

  This (the Directory node) gives a menu of major topics.
  Typing "q" exits, "?" lists all Info commands, "d" returns here,
  "h" gives a primer for first-timers,
  "mEmacs<Return>" visits the Emacs manual, etc.

  In Emacs, you can click mouse button 2 on a menu item or cross reference
  to select it.

* Menu:

Libraries
* autosprintf           Support for printf format strings in C++.
…

Emacs
* Ada mode              The GNU Emacs mode for editing Ada.
<No Htmlfontify>
```

Once I run the following fixup script

```
(
  cd "$(dirname "$(readlink -f "$(type -p emacs)")")"/../share/info/emacs &&
    for f in *.info.*
    do
      install-info "$f" dir
    done
)
```

I get an entry for Htmlfontify

```
File Edit Options Buffers Tools Info Help
No next, prev or up links  --  This is the top of the INFO tree
(dir)Top

  This (the Directory node) gives a menu of major topics.
  Typing "q" exits, "?" lists all Info commands, "d" returns here,
  "h" gives a primer for first-timers,
  "mEmacs<Return>" visits the Emacs manual, etc.

  In Emacs, you can click mouse button 2 on a menu item or cross reference
  to select it.

* Menu:
…

Emacs
* Autotype              Convenient features for text that you enter
                          frequently in Emacs.
…
* Htmlfontify           Convert source code to html.
```

Note that entries that have files inside `#{info}/emacs` do properly use them when visiting. It's just that all of the files available inside there aren't in the menu until running the `install-info` fixup.

It's worth nothing that a local installation _does_ generate a dir file:

```
$ pwd; grep Htmlfontify info/dir
/Users/tim.visher/git/emacs
* Htmlfontify: (htmlfontify).   Convert source code to html.
```

while the bottle does not (though it _does_ contain `htmlfontify.info.gz`)

```
$ tar -tzf ~/Library/Caches/Homebrew/downloads/4d23ccbd955636f080b9112261babb7655741242ecc1a81b4dc5af679fbe0f76--emacs--28.1.arm64_monterey.bottle.tar.gz -- emacs/28.1/share/info/emacs/{htmlfontify.info.gz,dir}
emacs/28.1/share/info/emacs/htmlfontify.info.gz
tar: emacs/28.1/share/info/emacs/dir: Not found in archive
tar: Error exit delayed from previous errors.
```

My only guess is that the bottle code is zipping up `*.info` rather than `*.info dir` here since the build process should be producing one.

That said, I did attempt to install `brew install emacs --HEAD` and it _also_ failed to produce or at least copy in the generated dir file.

```
$ ls -lA /opt/homebrew/Cellar/emacs/HEAD-516ff42/share/info/emacs/{htmlfontify.info.gz,dir}
ls: cannot access '/opt/homebrew/Cellar/emacs/HEAD-516ff42/share/info/emacs/dir': No such file or directory
-rw-r--r-- 1 tim.visher 22K Apr 26 16:30 /opt/homebrew/Cellar/emacs/HEAD-516ff42/share/info/emacs/htmlfontify.info.gz
```

I see no evidence that the `info` directory was even produced although it's possible `make clean` or similar is run by the the `install --HEAD` process:

```
$ ls -lAd ~/Library/Caches/Homebrew/emacs--git/info
ls: cannot access '/Users/tim.visher/Library/Caches/Homebrew/emacs--git/info': No such file or directory
```

### What did you expect to happen?

Be able to utilize all the manuals packaged with emacs.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
#!/usr/bin/env bash

brew uninstall emacs

ls -lA "$(brew --prefix)"/Cellar/emacs/28.1/share/info/emacs/dir

ls -lAd "$(brew --prefix)"/share/info/emacs

brew install emacs

ls -lA "$(brew --prefix)"/Cellar/emacs/28.1/share/info/emacs/dir

ls -lAd "$(brew --prefix)"/share/info/emacs

"$(brew --prefix)"/bin/emacs -Q --batch --eval '
  (progn
    (info)
    (message "%S" Info-directory-list)
    (occur "Htmlfontify")
    ;; Commented out because when `occur` does not find a match it does
    ;; not generate a buffer

    ;; (with-current-buffer "*Occur*"
    ;;  (message "%s" (buffer-substring (point-min)
    ;;                                    (point-max))))
  )'

(
  cd "$(brew --prefix)"/share/info/emacs &&
    for f in *.info.gz
    do
      install-info "$f" dir
    done
)

"$(brew --prefix)"/bin/emacs -Q --batch --eval '
  (progn
    (info)
    (message "%S" Info-directory-list)
    (occur "Htmlfontify")
    (with-current-buffer "*Occur*"
     (message "%s" (buffer-substring (point-min)
                                       (point-max))))
  )'
```

See my own logs of the above [here](https://gist.github.com/timvisher/ff91530774c5bc8d7ea69f04edf22304).

**Comment by SMillerDev** [comment]
What happens if you compile emacs outside of brew?

**Comment by timvisher** [comment]
> What happens if you compile emacs outside of brew?

A dir file gets created in the info directory:

> It's worth nothing that a local installation _does_ generate a dir file:
> 
> ```
> $ pwd; grep Htmlfontify info/dir
> /Users/tim.visher/git/emacs
> * Htmlfontify: (htmlfontify).   Convert source code to html.
> ```

**Comment by carlocab** [comment]
I think there is special handling of info pages in `brew`, but I'm a bit hazy on the details. The difference might lie there.

CC @Homebrew/brew in case this rings a bell for someone.

**Comment by cho-m** [comment]
Maybe https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cleaner.rb#L31-L35
```rb
    # Get rid of any info 'dir' files, so they don't conflict at the link stage
    Dir.glob(@f.info/"**/dir").each do |f|
      info_dir_file = Pathname(f)
      observe_file_removal info_dir_file if info_dir_file.file? && !@f.skip_clean?(info_dir_file)
    end
```

The problem being the symlink conflict at `HOMEBREW_PREFIX/share/info/dir`

**Comment by timvisher** [comment]
@cho-m That seems like a likely culprit. In this instance the `dir` file _shouldn't_ conflict because it's buried in a subdirectory, `#{info}/emacs/dir`. This appears to be at least somewhat uncommon just examining my local install.

**Comment by Bo98** [comment]
Excluding `#{info}/#{name}/dir` from deletion is probably a reasonable adjustment to make.
