### ISSUE TITLE
Cannot install multipass (whitespace or plus causes this issue )

### ISSUE THREAD

**Issue by chinafzy** [Homebrew/homebrew-core#100331]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
ignore it
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install multipass

### What happened (include all command output)?

==> Downloading https://github.com/canonical/multipass/releases/download/v1.8.1/multipass-1.8.1+mac-Darwin.pkg
curl: (28) Failed to connect to github.com port 443 after 79211 ms: Operation timed out
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
######################################################################## 100.0%##O#-
==> Installing Cask multipass
==> Running installer for multipass; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
==> Purging files for version 1.8.1 of Cask multipass
Error: Could not find PKG source file 'multipass-1.8.1+mac-Darwin.pkg', found 'multipass-1.8.1 mac-Darwin.pkg' instead.

### What did you expect to happen?

install the software.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew install multipass
```

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
