### ISSUE TITLE
Can't uninstall keybase after automagic change from formula to cask

### ISSUE THREAD

**Issue by lvh-zapier** [Homebrew/homebrew-core#10039]
# Please follow the general troubleshooting steps first:

- [x] ~~Ran `brew update` and retried your prior step?~~
- [x] ~~Ran `brew doctor`, fixed as many issues as possible and retried your prior step?~~
- [x] ~~Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new~~ (maybe? not sure :))

### Bug reports:

`brew update` this morning:

```
==> keybase has been moved to Homebrew-Cask.
==> brew uninstall --force keybase
Error: No available formula with the name "dunn/emacs/cl-lib"
Please tap it and then try again: brew tap dunn/emacs
==> brew prune
Pruned 0 symbolic links and 9 directories from /usr/local
==> brew cask install keybase
==> Downloading https://prerelease.keybase.io/darwin/Keybase-1.0.18-20170209165653%2B17b641d.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask keybase
==> Moving App 'Keybase.app' to '/Applications/Keybase.app'
==> 02.16.2017 09:55:30.699 Installer:42[DEBG] Version: 1.1.46
==> 02.16.2017 09:55:30.723 KBInstaller:27[DEBG] Installables: (
==>     "Privileged Helper",
==>     Updater,
==>     Service,
==>     Fuse,
==>     "Mount directory",
==>     KBFS,
==>     CLI
==> )
==> 02.16.2017 09:55:30.723 KBInstaller:32[DEBG] Install: Privileged Helper
==> 02.16.2017 09:55:44.377 KBInstaller:45[INFO] Install complete
==> 02.16.2017 09:55:44.377 KBInstaller:49[INFO] Privileged Helper: Install Error: Error copying rights: -60006
==> Not Installed, Bundle Version: 1.0.29
==> 02.16.2017 09:55:46.743 Installer:82[INFO] Exit(1)
==> Removing App: '/Applications/Keybase.app'
Error: Command failed to execute!
```

That ran in the background, as it usually does... Suddenly I get a popup with keybase asking for elevated permissions to install a helper. I do not want to give it those permissions, which is why I had the Formula installed, not the cask. (I am not interested in keybasefs or the chat functionality or whatever. I don't want to give it root access, and I sure as heck don't want to load its kernel module.)

Following part of the transcript is predictable:

```
==> Failed command:
/Applications/Keybase.App/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod --timeout=10

==> Standard Output of failed command:


==> Standard Error of failed command:
02.16.2017 09:55:30.699 Installer:42[DEBG] Version: 1.1.46
02.16.2017 09:55:30.723 KBInstaller:27[DEBG] Installables: (
    "Privileged Helper",
    Updater,
    Service,
    Fuse,
    "Mount directory",
    KBFS,
    CLI
)
02.16.2017 09:55:30.723 KBInstaller:32[DEBG] Install: Privileged Helper
02.16.2017 09:55:44.377 KBInstaller:45[INFO] Install complete
02.16.2017 09:55:44.377 KBInstaller:49[INFO] Privileged Helper: Install Error: Error copying rights: -60006
Not Installed, Bundle Version: 1.0.29
02.16.2017 09:55:46.743 Installer:82[INFO] Exit(1)


==> Exit status of failed command:
#<Process::Status: pid 43807 exit 1>
Error: nothing to install
```

Did new brew update. cask still listed as uninstalled; formula still listed as installed. For reasons unknown, in order to uninstall the poured keybase, I now need to tap `dunn/emacs` and install `cl-lib`?!

```
lvh@plotka ~> brew info keybase
keybase: stable 1.0.18, HEAD
Command-line interface to Keybase.io
https://keybase.io/
/usr/local/Cellar/keybase/1.0.18 (5 files, 36.5M) *
  Poured from bottle on 2016-11-23 at 09:24:49
From: /usr/local/opt/keybase/.brew/keybase.rb
==> Dependencies
Build: go ✔
lvh@plotka ~> brew uninstall keybase
Error: No available formula with the name "dunn/emacs/cl-lib"
Please tap it and then try again: brew tap dunn/emacs
```

No idea why. I'm happy with keybase being off of my system. I don't think it makes sense I should be tapping random emacs libs. This might be unrelated, but it shows up when trying `brew doctor`:

```
lvh@plotka ~ [130]> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/lvh/.pyenv/shims/python-config
  /Users/lvh/.pyenv/shims/python2-config
  /Users/lvh/.pyenv/shims/python2.7-config
  /Users/lvh/.pyenv/shims/python3-config
  /Users/lvh/.pyenv/shims/python3.6-config
  /Users/lvh/.pyenv/shims/python3.6m-config

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
Error: No available formula with the name "dunn/emacs/cl-lib"
Please tap it and then try again: brew tap dunn/emacs
```

`brew config`:

```
lvh@plotka ~> brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fa072755825b2983f27623b701b6de3eb6ab90f0
Core tap last commit: 51 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/lvh/.pyenv/shims/python => /Users/lvh/.pyenv/versions/pypy-5.4.1/bin/pypy
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.4-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

I think an issue has already been filed on brew about whether or not it's a good idea to automatically go for the cask when it's available as opposed to the formula. I submit this as evidence towards that idea (maybe it's good in general, but please consider requiring user interaction). Another example: I don't use the OpenSC upstream installer pkg (instead I use the homebrew version) because the Homebrew version just gives me the PKCS11 lib I want, and the upstream installer pkg installs a bunch of other crud that interacts poorly with other pieces of software.

**Comment by ilovezfs** [comment]
@gabriel @joshka any advice for @lvh-zapier ?

**Comment by lvh-zapier** [comment]
The cl-lib issue is an (apparently unrelated) https://github.com/dunn/homebrew-emacs problem. `brew untap homebrew/emacs` fixed that; once I did that, I was able to uninstall the keybase formulae (and it doesn't seem to feel installing the keybase cask is a good idea anymore).

**Comment by lvh-zapier** [comment]
Since the issue appears to be an unrelated homebrew-emacs problem, I'm closing this as invalid.

**Comment by joshka** [comment]
@lvh-zapper Responding to the"don't want to install various bits that require root", that's a question for upstream that I'd suggest you take to the keybase project. I can see why you'd want this. I can also see how it would be difficult for the devs to come up with a split that pleases everyone.

**Comment by gabriel** [comment]
@lvh-zapier We don't fully support a minimal keybase install anymore (we want to in the future, but currently "all or nothing" is easier to support).

But, you can sort of only get the minimal keybase install by doing:

```
# After copying Keybase.app to /Applications
ln -s /Applications/Keybase.app/Contents/SharedSupport/bin/keybase /usr/local/bin/keybase
# Only install service
keybase install --components=service
```

And then you can use basic functionality without any of the other services loading.
