### ISSUE TITLE
Wrong SHA256 for ladspa-sdk

### ISSUE THREAD

**Issue by DE0CH** [Homebrew/homebrew-core#100346]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs ladspa-sdk
Error: No logs.

brew config
HOMEBREW_VERSION: 3.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: d0a0bbef8db45cca303c607037338d02d8eaa8ca
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b785a45919c2915aa2de3e53390c7a3c4d383a11
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.4.0-97-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.4 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A

brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install ocrmypdf from source, which failed and led me to discorver this bug. 

### What happened (include all command output)?

The SHA256 mismatched
```
Running `brew update --preinstall`...
==> Downloading https://www.ladspa.org/download/ladspa_sdk_1.17.tgz
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/e2a9b0e9a94fe31f6c8a8343d9272ad9b1e55ab25740b4010af39166c4cbb35a--ladspa_sdk_1.17.tgz
Error: ladspa-sdk: SHA256 mismatch
Expected: d9d596171d93f9c226fcdb7e27c6f917422ac487efe2c05e0a18094df4268061
  Actual: 27d24f279e4b81bd17ecbdcc38e4c42991bb388826c0b200067ce0eb59d3da5b
    File: /home/vagrant/.cache/Homebrew/downloads/e2a9b0e9a94fe31f6c8a8343d9272ad9b1e55ab25740b4010af39166c4cbb35a--ladspa_sdk_1.17.tgz
To retry an incomplete download, remove the file above.
```

### What did you expect to happen?

I expected the SHA check to pass

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --build-from-source ladspa-sdk
```

**Comment by DE0CH** [comment]
I don't think it's a problem with my network because I've tried this in two difference places and the result is reproducable.

**Comment by natoopotato** [comment]
I've got the same issue with the exact same 'Actual' hash.

This isn't a proper fix but
```$ brew edit ladspa-sdk```
then change line 5 to
```27d24f279e4b81bd17ecbdcc38e4c42991bb388826c0b200067ce0eb59d3da5b```
It works in the sense that it will make it the problem go away and it will install.

**Comment by SMillerDev** [comment]
You'll have to find a way to contact the developers to see if that changed hash is intentional

**Comment by DE0CH** [comment]
I just sent the dev an email (richard at ladspa dot org). Hopefully that's the right guy and hopefully he replies.

**Comment by DE0CH** [comment]
Great. Thanks. Just opened a PR to fix this.
