### ISSUE TITLE
hub HEAD: 'bundle: command not found'

### ISSUE THREAD

**Issue by parkr** [Homebrew/homebrew-core#10052]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug report:

In #9521, @ilovezfs modified the `install` method of the `hub.rb` formula to build the 

Here is my gist from `brew gist-logs hub`: https://gist.github.com/parkr/e80b51cc18112ac372f880f882588799

You can see in the file `02.make`, the following lines:

```
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
script/bootstrap: line 28: bundle: command not found
script/bootstrap: line 30: bundle: command not found
You need Ruby 1.9 or higher and Bundler to run hub tests
make: *** [bin/ronn] Error 1
```

It appears to me like the `gem install bundle` command which is run (also present in the gist logs there) doesn't actually provide the `bundle` command. Running `sudo gem install bundler` to install with the `system` Ruby does not work:

```text
~$ sudo gem install bundler
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/bundle
```

/cc @MikeMcQuaid who approved #9521 and might be able to quickly spot where things have gone wrong.

**Comment by ilovezfs** [comment]
Note that brew test-bot builds both the stable and devel specs of the formula, so this is an issue particular to your system, otherwise the devel spec would not have passed test-bot.

**Comment by ilovezfs** [comment]
>Ruby: /Users/parkr/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby

is my initial guess

**Comment by parkr** [comment]
I have rbenv installed but it is set to my System `ruby` installation as I mentioned.

I logged in as `root` on my machine and ran `gem install bundler` and saw the same error. It is not rbenv.

**Comment by ilovezfs** [comment]
Do you mean `gem install bundle`? https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb#L36

**Comment by ilovezfs** [comment]
BTW here's what I see locally in case it helps: https://gist.github.com/ilovezfs/2b18abdbf4f6fa610978a4054c36f065

**Comment by ilovezfs** [comment]
And on Sierra: https://gist.github.com/ilovezfs/85541422e0b3c6dcec88a09e7e588cc3

**Comment by parkr** [comment]
@ilovezfs `gem install bundle` is basically a no-op if you already have `bundler` installed. See: https://rubygems.org/gems/bundle It's not a real package. What you really want is `gem install bundler`.

I see that my `PATH` doesn't include `/usr/local/bin` – why is this?

```console
mymac:~ root# gem install bundler
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/bundle
mymac:~ root# which bundle
/usr/local/bin/bundle
```

`gem install bundler` is trying to install into `/usr/bin`, but bundler's already in `/usr/local/bin`.

**Comment by ilovezfs** [comment]
Does it fix the issue if you edit the formula to use `gem install bundler`?

**Comment by ilovezfs** [comment]
OK formula uses `bundler` now: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb#L36

**Comment by parkr** [comment]
@ilovezfs That works for me, thank you. Could I suggest that if `bundle` exists and is executable in `PATH`, that you *not* do an unnecessary `gem install bundler`? It would certainly save time.

**Comment by MikeMcQuaid** [comment]
@parkr 👋 We'd probably rather avoid the code complexity and have something more reliable but good idea anyway.

**Comment by parkr** [comment]
@MikeMcQuaid Hey!! 

Something as simple as `which bundler || gem install bundler` would be too complext?

**Comment by MikeMcQuaid** [comment]
Yeh, people have stupid/broken stuff in their PATHS with alarming regularity and we generally don't want to rely or assume things are installed which are not.

**Comment by parkr** [comment]
Ok! A bit of a bummer but I'll deal. Cheers!

**Comment by ilovezfs** [comment]
@parkr thanks for reporting this and sorry about getting the `bundle` `bundler` thing bungled to begin with.

**Comment by parkr** [comment]
@ilovezfs It's no problem at all! Your time to resolution is very impressive, and I'm very grateful for your help!
