### ISSUE TITLE
Installing gst-plugins-bad does not find corevideomemory.h

### ISSUE THREAD

**Issue by Bitbored** [Homebrew/homebrew-core#1006]
When installing [gst-plugins-bad](../tree/master/Formula/gst-plugins-bad.rb) with the `with-applemedia` flag, building fails (but installation completes) with the following error:
```
plugin.m:25:10: fatal error: 'corevideomemory.h' file not found
```

This seems to be caused by [gst-plugins-bad-1.8.1.tar.xz](https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.8.1.tar.xz) not containing said `corevideomemory.h` file. The file is however present in [the gst-plugins-bad git repo](https://github.com/GStreamer/gst-plugins-bad/blob/1.8.1/sys/applemedia/corevideomemory.h).

I know this is an issue with the package, not with Homebrew, but having this issue should at least create some visibility for people encountering the same error.

Reported in Gnome's Bugzilla as [Bug 766163](https://bugzilla.gnome.org/show_bug.cgi?id=766163)

**Comment by mikemcquaid** [comment]
Nice detective work. In the short-term we could make `resource` containing a reference to this file in the Git repository and install that? Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
@mikemcquaid @Bitbored I opened a pull request fixing this here: https://github.com/Homebrew/homebrew-core/pull/1069

**Comment by ilovezfs** [comment]
@Bitbored this is now fixed if you brew update. Also, the option has been removed and the feature set to be always enabled (except on Mavericks). That means you don't need to build from source because the binary bottles now have the feature.

**Comment by Bitbored** [comment]
Great, thanks!

**Comment by ilovezfs** [comment]
@Bitbored You're welcome. Thanks for reporting this!
