### ISSUE TITLE
qt5 build fails

### ISSUE THREAD

**Issue by nextstopsun** [Homebrew/homebrew-core#10066]
QT5 build fails on building USB module with error:
```
modules.USB.o
fatal error: error in backend: IO failure on output stream.
```
Gist-logs here:
https://gist.github.com/67a3c5d500172fe03f2d0a34cab3092d

**Comment by ilovezfs** [comment]
Did the build perhaps fill your drive to 100%?

**Comment by ilovezfs** [comment]
Closing due to lack of response, but please let us know if this is still a problem.
