### ISSUE TITLE
Go v1.8.0 Fails to Build From Source on OS X/macOS 'El Capitan' v10.11.6

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#10093]
### Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

Running `brew upgrade -vd --build-from-source go` to upgrade said package specifier's associated software package from v1.7.5 to v1.8.0 fails near the end when trying to download `gotools`.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Go/v1.8.0/First%20Attempt) are my logs.  I don't know whether this is a problem with my local copy of the Git repository backing this resource or the relevant `resource` clause/block in `go.rb` is out of sync with upstream.  If it turns out to be the former situation, then I presume that the steps which I would need to perform in order to rectify this would be similar to those recommended to resolve corruption within `"$(brew --repository)"`?

**Comment by ilovezfs** [comment]
brew uninstall git

then try again

**Comment by ilovezfs** [comment]
Actually scratch that. Try changing
```
      url "https://go.googlesource.com/tools.git",
          :revision => "5682db0e919ed9cfc6f52ac32e170511a106eb3b"
```
to
```
      url "https://go.googlesource.com/tools.git",
          :revision => "5682db0e919ed9cfc6f52ac32e170511a106eb3b",
          :shallow => false
```

**Comment by ilovezfs** [comment]
Will be fixed by #10097

**Comment by ilovezfs** [comment]
@RandomDSdevel should be fixed now if you `brew update`

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Wonderful!  Sorry I was AFK and couldn't help.  If I hadn't been, I probably would have.
