### ISSUE TITLE
freenect-glview Number of Devices Found: 0

### ISSUE THREAD

**Issue by GBColumn** [Homebrew/homebrew-core#10105]
Trying to run an xbox360 Kinect on:
iMac OS X  Sierra 10.12.3
Intel Core i5 2.7Ghz
Intel Iris Pro 1536mb

Followed link from:
https://openkinect.org/wiki/Getting_Started#OS_X
to:
https://brew.sh
and followed instructions to install. No issues with installation but when I run freenect-glview it gives me:
Kinect Camera Test
Number of Devices Found: 0

I have the Kinect connected to the appropriate USB adapter and a green indicator light blinks when it is plugged in to a USB port. I've tried plugging the Kinect into different USB ports to no avail. When I run a systems report it shows an Xbox NUI Motor under Hardware>USB>hub. 

Any guidance would be appreciated. Thanks.

**Comment by MikeMcQuaid** [comment]
This doesn't seem to be an issue related to Homebrew in any way, sorry.
