### ISSUE TITLE
Upgrading Caddy Leaves Zombie Process

### ISSUE THREAD

**Issue by mohammed90** [Homebrew/homebrew-core#101031]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
2022-05-07 19:45:58  ~ $ brew gist-logs caddy
Error: No logs.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run Caddy with my own config

### What happened (include all command output)?

```shell
2022-05-06 20:55:14  ~$ caddy run --config shell.json
2022/05/07 16:45:40.883 INFO    using provided configuration    {"config_file": "shell.json", "config_adapter": ""}
run: loading initial config: loading new config: starting caddy administration endpoint: listen tcp 127.0.0.1:2019: bind: address already in use
exit status 1
```

### What did you expect to happen?

My own execution caddy runs successfully because I know for sure I don't have any caddy instances running.

### Step-by-step reproduction instructions (by running `brew` commands)

Start by having an older version of caddy and ensure it is not running, then run `brew upgrade caddy`. You will find a zombie Caddy instance. This is because the test block forks a caddy process to run with the test config. I was surprised to know I have a caddy instance running without my knowledge.

https://github.com/Homebrew/homebrew-core/blob/409c0774359e82416f18581b3d798508e774435a/Formula/caddy.rb#L40-L64

The alternative is to merely validate the version and perhaps validate the config (i.e. run `caddy validate --config <path to config>`, as is done with nginx.

**Comment by SMillerDev** [comment]
`brew upgrade` does not run the tests, only `brew test caddy` would do I don't think this issue was caused by brew.

**Comment by cho-m** [comment]
And the chance that `brew test` uses the same port 2019 is very low as it picks random free port.

A process should only be started if you started one either directly via command or indirectly via something like `brew services`. Both of these are user-controlled operations.

Unless there is any additional information, it doesn't sound like a bug.

**Comment by mohammed90** [comment]
Hmm. I'm not sure then. As far as original description goes, the issue is closed. That said, the test script does leave a zombie process, no?

**Comment by carlocab** [comment]
> That said, the test script does leave a zombie process, no?

It may. Then again, it might not. `brew` cleans up processes spawned during the test, but it doesn't always catch all of them.
