### ISSUE TITLE
Help with formula: bash >4.4 is required!

### ISSUE THREAD

**Issue by aronadaal** [Homebrew/homebrew-core#10104]
Hey there,
I'm trying to write my first formula and run into a problem that I couldn't solve by myself. I also didn't find any information about this on the net.

My program needs bash at least in version 4 to be installed on the system. I put a "depends_on" into my script and started the interactive mode. But during the "./configure" run I get the error:

> checking for bash version... configure: error: DAPS requires at least version 4.0 of bash.

bash v4.4 is installed and is called when I open a new terminal but the interactive mode of brew always starts bash v3.2. I also doesn't help if I call bash, before running './configure'.

Any help is appreciated!

**Comment by vladshablinsky** [comment]
I think you're still using your system bash. Try this:

https://github.com/Homebrew/homebrew-core/blob/0e332425b12e652c78becc91d0a0da66f19aac01/Formula/bashdb.rb
