### ISSUE TITLE
Valgrind should not be limited for Linux

### ISSUE THREAD

**Issue by IsraelBuitronD** [Homebrew/homebrew-core#101178]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs valgrind                                                                                                                      [14:06:57]
Error: No logs.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I tried to install `valgrind` into MacOS `10.15.7`, and 

### What happened (include all command output)?

After tried, Homebrew threw me:

```
brew install valgrind
Running `brew update --preinstall`...
==> Auto-updated Homebrew!
Updated Homebrew from 987e6888b to 5d61e69cf.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
libxcvt                                                                         tradcpp
==> Updated Formulae
Updated 5 formulae.
==> Updated Casks
Updated 2 casks.

valgrind: Linux is required for this software.
Error: valgrind: An unsatisfied requirement failed this build.
```

Then I check into its [formula](https://github.com/Homebrew/homebrew-core/blob/dcaa196d799a88100364464e37dcf27dbc80eb55/Formula/valgrind.rb#L25), and it is restricted to Linux (line 25).

Reading [Valgrind's homepage](https://valgrind.org/), I found:
>  It runs on the following platforms: [...] and AMD64/Darwin (Mac OS X 10.12).

So, it should be installable into MacOS.

### What did you expect to happen?

I expected to install `Valgrind` as any other formula does.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just `brew install valgrind`.
```

**Comment by SMillerDev** [comment]
macos 10.12 is pretty much the only supported macOS version for valgrind and that's not a version homebrew supports so practically there is no valgrind in homebrew on macOS.

**Comment by Bo98** [comment]
You can see upstream that 10.13 or later is not supported: https://bugs.kde.org/show_bug.cgi?id=383811
