### ISSUE TITLE
brew install numpy --with-python3 failed

### ISSUE THREAD

**Issue by andyli** [Homebrew/homebrew-core#10124]
```
$ brew upgrade numpy
Updating Homebrew...
==> Upgrading 1 outdated package, with result:
numpy 1.12.0
==> Upgrading numpy --with-python3
==> Using the sandbox
Error: No available formula with the name "gfortran"
```

If I try to install gfortan:
```
$ brew install gfortran
Updating Homebrew...
Error: No available formula with the name "gfortran" 
GNU Fortran is now provided as part of GCC, and can be installed with:
  brew install gcc
```

I guess the build dependency of numpy should be updated to depend on gcc instead.

**Comment by ilovezfs** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ilovezfs** [comment]
Closing due to lack of response but please let us know if this is still a problem for you.
