### ISSUE TITLE
brew update && brew upgrade doesn't seem to update properly.

### ISSUE THREAD

**Issue by brianjking** [Homebrew/homebrew-core#1012]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

* Output of `brew config` & `brew doctor` - https://gist.github.com/brianjking/935be186b0b7f12baea2bea02e6f355d

When I execute `brew update && brew upgrade` I expect that it should update all of the installed brews that show when executing `brew outdated`. However, when I run `brew outdated` even immediately following `brew update` and `brew upgrade` I find the following output:

`brianjking@bk-mbp13  ~  brew outdated
docker-compose (1.3.3, 1.4.0 < 1.7.0)
homebrew/php/php70 (7.0.4 < 7.0.6)
homebrew/php/phpbrew (1.20.1 < 1.21.1)
pngcrush (1.8.0 < 1.8.1)
pygobject3 (3.18.2 < 3.20.1)
sqlite (3.11.0, 3.11.0_1 < 3.12.2)
sshrc (0.6 < 0.6.1)
vim (7.4.1401, 7.4.1468, 7.4.1525, 7.4.1589, 7.4.1655 < 7.4.1817)
x264 (r2601 < r2668)
youtube-dl (2016.02.22, 2016.02.27, 2016.03.01, 2016.03.06, 2016.03.14, 2016.03.18, 2016.03.27, 2016.04.24 < 2016.05.01)`

**Comment by mikemcquaid** [comment]
Are you sure `brew update` was successful and returned a `0` exit code?

**Comment by brianjking** [comment]
@mikemcquaid How can I be sure? 

`brianjking@bk-mbp13  ~  brew update -v
remote: Counting objects: 13, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 13 (delta 8), reused 12 (delta 7), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/Homebrew/brew
   57bf333..5a90e71  master     -> origin/master
remote: Counting objects: 12, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 12 (delta 9), reused 10 (delta 7), pack-reused 0
Unpacking objects: 100% (12/12), done.
From https://github.com/Homebrew/homebrew-core
   17273c1..0b1a514  master     -> origin/master
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (6/6), done.
From https://github.com/Homebrew/homebrew-versions
   1a7a250..49968a5  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to origin/master.
Current branch master is up to date.
Current branch master is up to date.
First, rewinding head to replay your work on top of it...
Fast-forwarded master to origin/master.
Current branch master is up to date.
Current branch master is up to date.
First, rewinding head to replay your work on top of it...
Fast-forwarded master to origin/master.
Current branch master is up to date.
Current branch master is up to date.
Current branch master is up to date.
Current branch master is up to date.
Current branch master is up to date.
Updated Homebrew from 57bf333 to 5a90e71.
Updated 2 taps (homebrew/core, homebrew/versions).
==> Updated Formulae
docker-compose ✔                                           homebrew/versions/gcc6                                     node-build
`

**Comment by mikemcquaid** [comment]
Next time you run `brew update && brew upgrade` and it doesn't upgrade: paste all your logs here.

**Comment by brianjking** [comment]
@mikemcquaid I had just ran it right before I posted the initial issue. Which logs would you like me to obtain and I'll post them up now.

Thanks!

**Comment by mikemcquaid** [comment]
@brianjking Sorry; I mean the next time it fails to upgrade things and `brew outdated` shows values. There's nothing you can do now, though, if you don't have that data 😭

**Comment by brianjking** [comment]
@mikemcquaid 

brianjking@bk-mbp13  ~  brew update && brew upgrade
Already up-to-date.
==> Upgrading 10 outdated packages, with result:
docker-compose 1.7.1, homebrew/php/php70 7.0.6, homebrew/php/phpbrew 1.21.1, pngcrush 1.8.1, pygobject3 3.20.1, sqlite 3.12.2, sshrc 0.6.1, vim 7.4.1817, x264 r2668, youtube-dl 2016.05.01
Error: You must `brew link docker-machine` before docker-compose can be installed
==> Upgrading homebrew/php/php70
Error: Cannot install homebrew/php/php70 because conflicting formulae are installed.

  php56: because different php versions install the same binaries.

Please `brew unlink php56` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

brianjking@bk-mbp13  ~  brew outdated
docker-compose (1.3.3, 1.4.0 < 1.7.1)
homebrew/php/php70 (7.0.4 < 7.0.6)
homebrew/php/phpbrew (1.20.1 < 1.21.1)
pngcrush (1.8.0 < 1.8.1)
pygobject3 (3.18.2 < 3.20.1)
sqlite (3.11.0, 3.11.0_1 < 3.12.2)
sshrc (0.6 < 0.6.1)
vim (7.4.1401, 7.4.1468, 7.4.1525, 7.4.1589, 7.4.1655 < 7.4.1817)
x264 (r2601 < r2668)
youtube-dl (2016.02.22, 2016.02.27, 2016.03.01, 2016.03.06, 2016.03.14, 2016.03.18, 2016.03.27, 2016.04.24 < 2016.05.01)

**Comment by mikemcquaid** [comment]
Ok, that's the issue then; it can't upgrade and provides some instructions of what you need to to do for `brew upgrade` to work.

**Comment by brianjking** [comment]
@mikemcquaid What can't update? I understand the issues with php70 and docker/docker-machine, however, youtube-dl for instance has nothing to do with either of these.

**Comment by mikemcquaid** [comment]
Those issues need to be fixed for `brew upgrade` to upgrade your other packages. You can upgrade `youtube-dl` with `brew upgrade youtube-dl`.
