### ISSUE TITLE
please restore "--with-libdvdnav" and "--with-libdvdread" options for "brew install mplayer"

### ISSUE THREAD

**Issue by mark-zajac** [Homebrew/homebrew-core#101312]
@badvision I have now added options for libdvdread and libdvdnav

_Originally posted by @ilovezfs in https://github.com/Homebrew/homebrew-core/issues/15227#issuecomment-315108863_

Running "brew install --with-libdvdnav --with-libdvdread mplayer" now gives "Error: invalid option: --with-libdvdnav" as the result.

The problem seems limited to "brew install mplayer" only.  I ran "brew update" and "brew doctor" to no avail.  

The output from "brew gist-logs" was "Error: `brew gist-logs` requires HOMEBREW_GITHUB_API_TOKEN to be set!", even after "brew config" was run.

**Comment by SMillerDev** [comment]
We will not be restoring options

**Comment by mark-zajac** [comment]
> We will not be restoring options

Just curious, why not?

**Comment by SMillerDev** [comment]
For the same reason we removed them for: Options cause the formulae to build locally where the user can have made any number of modifications to the build environment, causing builds to fail and those users to request support from Homebrew maintainers. With the small group of people who maintain Homebrew that amount of support is not feasible so we will not allow options in Homebrew repositories anymore.

**Comment by mark-zajac** [comment]
> Options cause the formulae to build locally where the user can have made any number of modifications to the build environment, causing builds to fail and those users to request support from Homebrew maintainers.

Fair enough.  Thank you for providing and maintaining the existing formula.
