### ISSUE TITLE
Stunnel will not connect to endpoints on arm64 apple silicon

### ISSUE THREAD

**Issue by Coolbeans007** [Homebrew/homebrew-core#101431]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to connect to a stunnel server which I know works on windows and linux. I used the same config and stunnel will not connect to the endpoint.

### What happened (include all command output)?

stunnel runs with correct output in foreground but will fail to connect to the endpoint.

### What did you expect to happen?

connected to endpoint with no issues.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install stunnel
stunnel
(assuming you edit the config, cert, key files)
```

**Comment by SMillerDev** [comment]
Have you tried reporting this to the developers?
