### ISSUE TITLE
linking flyctl conflicts with concourse-ci cli tool fly

### ISSUE THREAD

**Issue by zbrox** [Homebrew/homebrew-core#101674]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: da3f335da379226cdc2470f622ea2fd3d9289b34
Core tap last commit: 36 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTO_UPDATE_SECS: 3600
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.3.1
Rosetta 2: false
```

```
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  flyctl
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install `flyctl` while having `fly` installed. 

### What happened (include all command output)?

`flyctl` cannot be linked because it tries to link to `$(brew --prefix)/bin/fly` which exists because that is the default name for the Concourse CI CLI tool.

```
==> Pouring flyctl--0.0.325.arm64_monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/fly
Target /opt/homebrew/bin/fly
already exists. You may want to remove it:
  rm '/opt/homebrew/bin/fly'

To force the link and overwrite all conflicting files:
  brew link --overwrite flyctl

To list all files that would be deleted:
  brew link --overwrite --dry-run flyctl

Possible conflicting files are:
/opt/homebrew/bin/fly -> /opt/homebrew/Caskroom/fly/7.7.1/fly
==> Caveats
fish completions have been installed to:
  /opt/homebrew/share/fish/vendor_completions.d
==> Summary
🍺  /opt/homebrew/Cellar/flyctl/0.0.325: 9 files, 30.9MB
==> Running `brew cleanup flyctl`...
```

### What did you expect to happen?

I expected that `flyctl` would link only to `$(brew --prefix)/bin/flyctl` and not make a shorter alias. The Fly.io documentation uses `flyctl` as the name of the CLI tool. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install fly
brew install flyctl
```

**Comment by cho-m** [comment]
`flyctl` specifically mentions adding symlink and documents how they plan to rename to `fly` in future.

See https://github.com/superfly/flyctl#flyctl
> Note: Most installations of `flyctl` also alias `flyctl` to `fly` as a command name and this will become the default name in the future. During the transition, note that where you see `flyctl` as a command it can be replaced with `fly`.

So, the conflict is expected unless upstream changes their mind.
