### ISSUE TITLE
gdb formula does not install GDB's info documentation

### ISSUE THREAD

**Issue by jmarshall** [Homebrew/homebrew-core#10179]
Since ffeb018e2099808d32798668d2fb9875c4aa278e, _gdb.rb_'s install step blows away the entire info directory (marked with `<--`):

    # Remove conflicting items with binutils
    rm_rf include
    rm_rf lib
    rm_rf share/"locale"
    rm_rf share/"info"        # <--

This is intended to remove _bfd.info_ (which is indeed is provided by binutils) and likely _standards.info_ (which is likely provided by some other package).  However it also removes _gdb.info_, which is provided only by GDB and constitutes the bulk of GDB's documentation.

This needs to remove conflicting info files but leave _gdb.info_ and any other GDB-specific info files installed.  Possibly something like

    rm_f share/"info"/[^g]*

(with appropriate ruby-ification of the file glob pattern) would suffice.

**Comment by ilovezfs** [comment]
@jmarshall Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by jmarshall** [comment]
As you know, not all of your users are themselves Ruby programmers.  So “please send a PR” is not always appropriate, and “needs response” doubly so.  Nonetheless: PR #10407.

**Comment by ilovezfs** [comment]
@jmarshall "needs response" is perhaps poorly named. The idea is that it lets us know when an issue has been commented on again because it gets removed automatically by BrewTestBot when a contributor subsequently comments as you can see above.

As for not all users being Ruby programmers, the brew DSL is significantly more accessible than run-of-the-mill ruby, or at least we hope it is.

**Comment by MikeMcQuaid** [comment]
Thanks for the PR ❤️ 

> As for not all users being Ruby programmers, the brew DSL is significantly more accessible than run-of-the-mill ruby, or at least we hope it is.

Relatedly, we are a community run project and if you're the person who cares about an issue being fixed you're the best person to try and fix it. The alternative is we just close a bunch of these issues with WONTFIX. 

> and “needs response” doubly so

This is our way of keeping track of stale issues. You were asked a question so needing a response is not unreasonable.
