### ISSUE TITLE
[GDAL formula] Switch to CMake and enable apache-arrow dependency

### ISSUE THREAD

**Issue by rouault** [Homebrew/homebrew-core#101771]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
(not sure if this is the right place where to report suggestions on a formula)

gdal.rb formula uses autoconf to build GDAL. Since GDAL 3.5.0, the autoconf build system is deprecated (cf https://github.com/OSGeo/gdal/blob/v3.5.0/NEWS.md) per a CMake build system. autoconf support will be removed in GDAL 3.6.0

GDAL 3.5.0 also adds 2 new drivers, arrow and parquet, which require the apache-arrow dependency, and using CMake builds
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

-

### What happened (include all command output)?

-

### What did you expect to happen?

-

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
-
```

**Comment by SMillerDev** [comment]
Suggestions should be submitted as pull requests.
