### ISSUE TITLE
postgresql: enabling boot-time service fails cryptically

### ISSUE THREAD

**Issue by megahall** [Homebrew/homebrew-core#10178]
# Please follow the general troubleshooting steps first:

- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ X ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

**NOTE**: Some of this issue might affect `brew services` in general but it seems like `postgresql` has some corner cases that trigger unexpected results.

Configuring the `postgresql` service to start at boot time fails with this error internally:

```shell
$ sudo /usr/local/opt/postgresql/bin/postgres -D /usr/local/var/postgres
"root" execution of the PostgreSQL server is not permitted.
The server must be started under an unprivileged user ID to prevent
possible system security compromise.  See the documentation for
more information on how to properly start the server.
```

The service also appears to fail if it is configured to start at login time. In this case I get a very cryptic `launchd` error and no output to the `postgres.log` configured for `stderr`:

```
Feb 21 01:04:08 mhall-osx-home com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql[58446]) <Error>: Service could not initialize: 15G1217: xpcproxy + 12684 [1462][F7717708-ACF7-307D-B04E-998DFC36598F]: 0xd
```

There are several usability issues which make this problem difficult to debug:

1. the `brew services` command and build output for `postgresql` never point out this won't work
2. the `brew services` command does not offer a way to view the logs or show where the logs would be located
3. the `brew services list` claims the service is `started` but it's actually broken and doesn't appear in any `ps` output(s)

Relevant Log:
<https://gist.github.com/megahall/7ac711e3039b8f18cab23d0185de31cf#file-post_install-01-initdb>

*NOTE*: `brew doctor` is irrelevant for this issue.

`brew config`:
```shell
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 672a41a272ec5f51a2b7eb4617f9feb5321e04d9
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112, 1.8.0_102, 1.8.0_72, 1.8.0_66
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.8 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
> the brew services command and build output for postgresql never point out this won't work
> the brew services command does not offer a way to view the logs or show where the logs would be located
> the brew services list claims the service is started but it's actually broken and doesn't appear in any ps output(s)

`brew services` is a thin wrapper around `launchctl`. We'll accept pull requests to fix it but most of this is a feature request rather than a bug report, sorry. I'm sure PostgreSQL has specific issues e.g. not being able to run as root but this isn't something we were aware of or can really do anything about.

**Comment by MikeMcQuaid** [comment]
`sudo rm -rf /usr/local/var/postgres; sudo brew services stop postgres; brew reinstall postgres; brew services restart postgres` may get you further along.
