### ISSUE TITLE
Libx11 compiled with --enable-loadable-i18n leading to non-functional non-ASCII characters

### ISSUE THREAD

**Issue by awetzel** [Homebrew/homebrew-core#101833]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/0bb0c5b04663fc497eea7f6ae2d22179
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to get a terminal emulator working with non-ascii input characters.

```
brew install xterm
brew install rxvt-unicode
```

Set locale `fr_FR.UTF-8` then open `xterm` and try do put a "euro" character.

### What happened (include all command output)?

No character output when typing "euro" character.

### What did you expect to happen?

"euro" € character should output correctly.

The bug is in libx11, looks like exactly the one described here : https://bugs.freedesktop.org/show_bug.cgi?id=7982
but the bug was corrected and here the problem is maybe a path or object link problem with xlibi18n.so .  

Unicode loader fails with current homebrew build of libx11 so the `--enable-loadable-i18n` option leads to non-functional non-ASCII characters.

To fix it on my computer : I have removed `--enable-loadable-i18n` from the `libx11.rb` formula of homebrew-core and rebuild libx11.

Maybe the problem does not come from homebrew packaging, but removing the loadable-i18n fix it and the problem is quite important as it make all X softwares installed with homebrew unusable for non english user with current homebrew packages.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install xterm
xterm
type €
```

**Comment by carlocab** [comment]
The `--enable-loadable-i18n` flag seems to have been inherited from when @maxim-belkin added it to the linuxbrew/xorg formula in https://github.com/maxim-belkin/homebrew-xorg/pull/416.

It seems to have been broken for a while now, though: https://lists.freedesktop.org/archives/xorg/2006-July/016715.html (but perhaps it's been fixed and then broken again since this message was posted)

I'm not opposed to removing the flag, but it would be good to have a fuller understanding of the consequences of doing so first.

**Comment by awetzel** [comment]
I think that loadable-i18n is to dynamically load i18n C function from ".so" external object file, and add no feature.
So as @maxim-belkin stated : Added configure flags (for reproducible builds), so the flag has been set in order to make sure compile options does not change when compile default change in new x11 version.
But from my knowledge,  loadable-i18n is not the default, see this email talking about a similar non-corrected bug https://lists.freedesktop.org/archives/xorg/2006-July/016715.html  

```
Probably nobody found this problem, since the i18n module support is not the default.
```
