### ISSUE TITLE
`PS /home/BEEDELLROKEJULIANLOCKHART> brew install --cask vlc-nightly Error: Cask 'vlc-nightly' is unavailable: No Cask with this name exists.`

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [Homebrew/homebrew-core#101906]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
PS /home/BEEDELLROKEJULIANLOCKHART> brew gist-logs nextcloud
Error: No available formula with the name "nextcloud".
PS /home/BEEDELLROKEJULIANLOCKHART> brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 45a6b78653799f2c0058b92f0931dfecbf929949
Core tap last commit: 20 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit zen
Clang: N/A
Git: 2.36.1 => /bin/git
Curl: 7.83.1 => /bin/curl
Kernel: Linux 5.18.0-0.rc6.20220513gitf3f19f939c11925.51.fc37.x86_64 x86_64 GNU/Linux
OS: Fedora release 37 (Rawhide)
Host glibc: 2.35
/usr/bin/gcc: 12.1.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
PS /home/BEEDELLROKEJULIANLOCKHART> brew doctor
Your system is ready to brew.
PS /home/BEEDELLROKEJULIANLOCKHART>
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I intended to execute `brew install --cask nextcloud` to install VLC.

### What happened (include all command output)?

`PS /home/BEEDELLROKEJULIANLOCKHART> brew install --cask vlc-nightly Error: Cask 'vlc-nightly' is unavailable: No Cask with this name exists.`

### What did you expect to happen?

`brew install --cask vlc-nightly` should execute successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`PS /home/BEEDELLROKEJULIANLOCKHART> brew install --cask vlc-nightly Error: Cask 'vlc-nightly' is unavailable: No Cask with this name exists.`
```

**Comment by SMillerDev** [comment]
Casks don't work on Linux

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Is this explained anywhere, and why?

**Comment by SMillerDev** [comment]
> [Homebrew](https://brew.sh/) Cask extends Homebrew and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications such as Atom and Google Chrome.

https://github.com/Homebrew/homebrew-cask/

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@SMillerDev, `http://github.com/Homebrew/homebrew-cask` does not appear to explain anything. Contradictorily, its primary taglines are `“To install, drag this icon…” no more!` and `To start using [Homebrew](https://brew.sh/) Cask, you just need Homebrew installed.`.

**Comment by SMillerDev** [comment]
I mean.. `“To install, drag this icon…”` is not really something you do on Linux and the rest of the first block of the README mentions macOS quite a few times:

> Homebrew Cask extends [Homebrew](https://brew.sh/) and brings its elegance, simplicity, and speed to the installation and management of GUI macOS applications such as Atom and Google Chrome.
> We do this by providing a friendly CLI workflow for the administration of macOS applications distributed as binaries.

If you have a suggestion how to further clarify this: pull requests are welcome.
