### ISSUE TITLE
Different MySQL versions have the same datadir

### ISSUE THREAD

**Issue by gwerbin** [Homebrew/homebrew-core#10244]
As the title says. This makes it impossible to actually have two usable MySQL versions installed at the same time.

It seems the quick fix is to add versioned datadirs, or at least the option to add versioned datadirs. I demonstrate a crude version of that fix here: https://github.com/gwerbin/homebrew-core/commit/374ad55a4c7bb616b59cba0818dfa4554374b186

This works for me because I use `brew services` to run MySQL. However for other uses, this would require the user to specify `--datadir=...` to just get the thing to run, which is intrusive. Therefore I suggest the following:

1. *Always* version the `datadir` (`var/opt/mysql@5.6`)
2. Symlink the versioned `datadir` to the non-versioned `datdir` (`var/opt/mysql`) by default
3. Add an option like `--with-versioned-datadir` that _disables_ the above-mentioned symlink. 

This would then allow me to do
```shell
brew install mysql
brew install mysql@5.6 --with-versioned-datadir
```

(We should probably do something similar for Postgres, too.)

That said, a more robust system à la `alternatives` in Linux would be nice here as well. But that's obviously more complicated and I'm sure it's been discussed elsewhere.

**Comment by ilovezfs** [comment]
I suppose we might consider a PR for this, but the availability of the versioned formulae in itself doesn't imply that we intend to support simultaneous installations of software like mysql.

**Comment by MikeMcQuaid** [comment]
> I suppose we might consider a PR for this, but the availability of the versioned formulae in itself doesn't imply that we intend to support simultaneous installations of software like mysql.

Agreed. We'll review a PR.
