### ISSUE TITLE
mitmproxy failed to build on 10.12.3

### ISSUE THREAD

**Issue by hakamadare** [Homebrew/homebrew-core#10278]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

After the release of mitmproxy 2.0.0, `brew upgrade mitmproxy` fails to build with an error message saying that my PYTHONPATH is configured for Python 2, but mitmproxy requires Python 3:

https://gist.github.com/hakamadare/d77b4cda542f8f9f0f5b9e892e0dc324

I confirmed that I don't set PYTHONPATH explicitly in my shell configuration, which suggests to me that it's being set either by Homebrew, Boxen, or pyenv.  Ideally I'd like the formula to be able to work around this setting (I do have Homebrew's python3 package installed), perhaps by using Homebrew's `pip3` instead of the default `pip` to install?

**Comment by ilovezfs** [comment]
you can try adding `ENV.delete("PYTHONPATH")` at the beginning of the install method, but this is really an issue for boxen.
