### ISSUE TITLE
tmux: default TERM is wrong

### ISSUE THREAD

**Issue by judge-red** [Homebrew/homebrew-core#102748]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30e3d8883cde265cbc16ff94b49a3ac14137590e
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 92f86779c4fd4aa967e1d18a3b2a7cc5eb869bf0
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.3nKVG4Da50/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.36.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  jupyterlab
  six
  telnet

(COMMENT: doctor output has nothing to do with the issue)
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

use tmux 3.3

### What happened (include all command output)?

tmux doesn't render color because TERM is set to tmux-256color instead of screen-256color. Only the latter is available on macos. Apparently upstream changed something and now this needs to be set in `configure`.

### What did you expect to happen?

tmux 3.3 works/looks like tmux 3.2

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
tmux
echo $TERM
```

**Comment by judge-red** [comment]
Valid workaround:
Add the following line to `~/.tmux.conf`:
```
set-option -g default-terminal screen-256color
```

**Comment by carlocab** [comment]
Yes, the default terminal was changed in this version. See https://github.com/tmux/tmux/issues/3203.

**Comment by judge-red** [comment]
> > Apparently upstream changed something and now this needs to be set in configure.
> 
> This isn't a brew bug then

It's unusable out of the box on macos, because upstream doesn't tailor it for macos. You'd think homebrew would be interested in tailoring it for macos, but I guess not. Sorry for trying to make your user's experience better.

**Comment by Bo98** [comment]
> now this needs to be set in `configure`.

There's something more going on here that just that because upstream configure already checks if a term exits - and it is detecting `tmux-256color` as existing.

I compiled it locally and got `screen-256color`.

**Comment by carlocab** [comment]
> I compiled it locally and got `screen-256color`.

Did you compile it outside of `brew`? It probably won't find the keg-only `ncurses` (which does provide `tmux-256color`) if you do.

**Comment by carlocab** [comment]
We could pass arguments to `configure` that retains `screen-256color` as the default on macOS, but I'm not certain it's worth it.

Upstream look to be moving away from supporting a `TERM` of `screen-256color`, so this likely just delays the inevitable. I've also had `tmux-256color` as my `TERM` for quite some time now, and have not had any problems. I've even been able to get rid of pretty much all the hacks I've had in place to get it to work by now.

**Comment by xandris** [comment]
I'm using MacOS's zsh with tmux. tmux sees `tmux-256color` from ncurses-6.3 I guess? tmux works but zsh doesn't even understand backspace. reset is `/usr/bin/reset` and it doesn't understand TERM either. What's the correct setup? Should I be manually setting TERMINFO to `/usr/local/Cellar/ncurses/6.3/share/terminfo`?

**Comment by nicm** [comment]
It looks like you should be able to easily do this with:
~~~~
$ /usr/local/Cellar/ncurses/6.3/bin/infocmp -x tmux-256color >tmux-256color.src
$ /usr/bin/tic -x tmux-256color.src
~~~~

**Comment by xandris** [comment]
I guess my question is what the out-of-the-box user experience with Homebrew is supposed to be. When you 'brew install tmux` there aren't any caveats about this, so it makes it seem like I've misconfigured my system. Is the "supported" configuration intended to be:

1. Use only binaries that link against Homebrew ncurses; don't use Mac native vim, zsh, reset, ...
2. tmux is configured with MacOS compatible TERM
3. A hand-modified /usr/share/terminfo

Or is all this moot because tmux wants to use `screen-256color` in the future anyway? (Scenario 2 above.)

**Comment by carlocab** [comment]
> 1) install `tmux-256color` with the system `tic` (don't forget `-x`);

[Here's](https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/) a nice guide for doing the above.

**Comment by utkonos** [comment]
I think I'm hitting a problem related to this issue. After the update to tmux 3.3, backspace causes spaces, shift and a letter add extra `/`, and delete is `~`.

Is there a simple solution for this?

Reading the above and that guide, it looks like some of the options can interfere with commands linked to the system ncurses. I encountered the following error when using `man`: `WARNING: terminal is not fully functional`.

Also, the steps in that guide appear fairly complex. Is that something that will need to be maintained? Is there a way to have the homebrew formula make this change during install?

**Comment by carlocab** [comment]
> Is there a simple solution for this?

You can either follow the [guide](https://gpanders.com/blog/the-definitive-guide-to-using-tmux-256color-on-macos/) I linked to above or continue to use `screen-256color` as your `TERM` by adding

```tmux
set -g default-terminal screen-256color
```

to your `~/.tmux.conf`.

> Also, the steps in that guide appear fairly complex. Is that something that will need to be maintained?

In principle, yes. In practice, this is something I did once long ago and completely forgot about it until recently, so you probably don't really need to maintain it.

> Is there a way to have the homebrew formula make this change during install?

Not for the steps in the guide. There are other possible changes we could consider making (e.g. change the compile-time `TERM`, install a `tmux.conf` into `etc` that configures the default terminal, add some `caveats` about steps you might need to take, etc), but it's not clear to me right now which, if any, are appropriate.

**Comment by utkonos** [comment]
@carlocab Thanks for the quick reply!

A line in `caveats` about adding

```
set -g default-terminal screen-256color
```

to `~/.tmux.conf` seems like the best band-aid from the perspective of the principle of least astonishment.

**Comment by nicm** [comment]
If you don't have a way for a package to install system terminfo entries then if I were you I would configure tmux with `--with-TERM=screen-256color`. The `configure` option is there to allow packagers and users to customise the default for their system if the detected one is not suitable.

Any mitigation I put into tmux for this would end up with the same thing (use `screen-256color` on macOS).

**Comment by majksner** [comment]
None of the suggested workarounds really worked for me.

Here is what I did to revert to the previous version of tmux.

```shell
brew edit tmux <- past contents of https://raw.githubusercontent.com/Homebrew/homebrew-core/e44425df5a8b3c8c24073486fa7e355f3ac19657/Formula/tmux.rb
brew reinstall tmux
brew pin tmux # stop further updates until is fixed.
```

It should install previous version

**Comment by utkonos** [comment]
@nicm That sounds like a nice solution.

These lines in the Formula:
https://github.com/Homebrew/homebrew-core/blob/b42836f6e911354dca02e48a67143692f0e38deb/Formula/tmux.rb#L49-L53

would then become:
```
    args = %W[
      --disable-dependency-tracking
      --prefix=#{prefix}
      --sysconfdir=#{etc}
      --with-TERM=screen-256color
    ]
```

It's been a long time since I've done a PR, so I will review the process from the Homebrew docs.

**Comment by nobrowser** [comment]
> > now this needs to be set in `configure`.
> 
> There's something more going on here that just that because upstream configure already checks if a term exits - and it is detecting `tmux-256color` as existing.
> 
> I compiled it locally and got `screen-256color`.

It checks that it exists *at build time*. Which doesn't work for bottles, and arguably is the wrong check altogether.

**Comment by nobrowser** [comment]
> We could pass arguments to `configure` that retains `screen-256color` as the default on macOS, but I'm not certain it's worth it.
> 
> Upstream look to be moving away from supporting a `TERM` of `screen-256color`, so this likely just delays the inevitable. I've also had `tmux-256color` as my `TERM` for quite some time now, and have not had any problems. I've even been able to get rid of pretty much all the hacks I've had in place to get it to work by now.

So, how do you deal with programs that link with the system ncurses, where that terminal type is missing? Note this includes most cursed Homebrew programs, at least ATM. (Why?)

**Comment by utkonos** [comment]
Can someone reopen this issue? I argue that despite this being due to an upstream change, the effect is that a newly installed tmux via homebrew doesn't work the way it's expected and having backspace not work at all is very unexpected and difficult to work around without coming here to this thread to find the workaround.

**Comment by thegcat** [comment]
For reference:

> To avoid this you can do one of:
> 
> 1. install `tmux-256color` with the system `tic` (don't forget `-x`);
> 2. build tmux with `--with-TERM=screen-256color`;
> 3. link tmux against the system ncurses instead of a newer version (it will then detect `screen-256color` unless you have installed `tmux-256color` manually);
> 4. manually change the option in `.tmux.conf` or `/etc/tmux.conf` with `set -g default-terminal screen-256color`.

I tried 1, 2 and 4 with the effect that `env` in fish did correctly show `TERM` as being `screen-256color` for 2 and 4, but somehow fish and vim started from fish would not pick up on it. Reverting to screen 3.2a solved this issue for me for the time being.

**Comment by nobrowser** [comment]
While I understand the reluctance of Homebrew maintainers to mess with upstream configuration, I do believe this situation merits at least a caveat.

All of the work-arounds suggested imply at least one of:

- compiling tmux from source, ignoring the provided bottle (even if you normally use bottles)
- making a local configuration change that will be hard to share with other systems (even if you normally share most of your configuration)

So, this does look like a regression to me.

Again, this would be a considerably smaller problem if all Homebrew packages linked to the Homebrew ncurses.

**Comment by utkonos** [comment]
@nobrowser Done.

**Comment by nobrowser** [comment]
@utkonos Thanks :-P

**Comment by carlocab** [comment]
> Again, this would be a considerably smaller problem if all Homebrew packages linked to the Homebrew ncurses.

Which packages are you having issues with that still link to system `ncurses`? Most widely used formulae already link to Homebrew `ncurses`: `tmux`, `zsh`, `vim`, `ncdu`, `less`, etc.

**Comment by nobrowser** [comment]
```
 61+0:~ $ for p in /usr/local/bin/* ; do if otool -L "$p" | fgrep ncurses.5 >/dev/null 2>&1 ; then echo "$p" ; fi ; done
/usr/local/bin/aspell
/usr/local/bin/bash
/usr/local/bin/ccmake
/usr/local/bin/clang-format
/usr/local/bin/ecasignalview
/usr/local/bin/ecasound
/usr/local/bin/lame
/usr/local/bin/lynx
/usr/local/bin/msgattrib
/usr/local/bin/msgcat
/usr/local/bin/msgcmp
/usr/local/bin/msgcomm
/usr/local/bin/msgconv
/usr/local/bin/msgen
/usr/local/bin/msgexec
/usr/local/bin/msgfilter
/usr/local/bin/msgfmt
/usr/local/bin/msggrep
/usr/local/bin/msginit
/usr/local/bin/msgmerge
/usr/local/bin/msgunfmt
/usr/local/bin/msguniq
/usr/local/bin/mzscheme
/usr/local/bin/racket
/usr/local/bin/rc
/usr/local/bin/rlwrap
/usr/local/bin/tig
/usr/local/bin/xgettext
 62+0:~ $ for p in /usr/local/bin/* ; do if otool -L "$p" | fgrep ncursesw.6 >/dev/null 2>&1 ; then echo "$p" ; fi ; done
/usr/local/bin/less
/usr/local/bin/pspg
/usr/local/bin/tmux
```

Ok, not a fair comparison because of the whole bunch of gettext programs, and the racket ones come from a cask. But still, if  you remove all those, that group is still bigger.

**Comment by carlocab** [comment]
I'm not sure that answers my question. Of the formulae you have installed that link with system `ncurses`, which ones are you having issues with that would be fixed by linking with Homebrew `ncurses`?

**Comment by nobrowser** [comment]
tig, I'll try to find a reproducible case. But I really don't understand why it's not done by default, or why there isn't a mass patch of all the remaining cases to migrate them.

**Comment by SMillerDev** [comment]
You can make a radr or submit feedback.

**Comment by utkonos** [comment]
Thanks! All done. Just for anyone else who needs to know how, there is an app named `Feedback Assistant` which is accessable via Spotlight. You then login with Apple ID and can then submit feedback.

Instructions were here:

https://developer.apple.com/bug-reporting/

**Comment by milosivanovic** [comment]
> It looks like you should be able to easily do this with:
> 
> ```
> $ /usr/local/Cellar/ncurses/6.3/bin/infocmp -x tmux-256color >tmux-256color.src
> $ sudo /usr/bin/tic -x tmux-256color.src
> ```

Reminder for those on Apple Silicon (M1/M2) Homebrew installations that the default Homebrew install path is `/opt/homebrew` instead of `/usr/local`, so for them it would be:

```
$ /opt/homebrew/Cellar/ncurses/6.3/bin/infocmp -x tmux-256color >tmux-256color.src
$ sudo /usr/bin/tic -x tmux-256color.src
```
