### ISSUE TITLE
Log files not being created when installing tinyproxy

### ISSUE THREAD

**Issue by wputnam** [Homebrew/homebrew-core#10284]
# Please follow the general troubleshooting steps first:

- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ X ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

See first comment at link: https://github.com/tinyproxy/tinyproxy/issues/80#issue-209698490

`Nagashimac-2:~ williamputnam$ brew doctor
Your system is ready to brew.`

`Nagashimac-2:~ williamputnam$ brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 658f06c1ab01686889b277d5db5a99a5f93d0f93
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_75
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A`

`Nagashimac-2:~ williamputnam$ brew gist-logs tinyproxy
Error: No logs.`

**Comment by ilovezfs** [comment]
The log is at /usr/local/var/log/tinyproxy/tinyproxy.log
