### ISSUE TITLE
qhelpgenerator not found  with last update 6.3

### ISSUE THREAD

**Issue by Nelson-numerical-software** [Homebrew/homebrew-core#102962]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew install qt
Warning: qt 6.3.0 is already installed and up-to-date.
To reinstall 6.3.0, run:
  brew reinstall qt
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to use qhelpgenerator to generate qt help files
Previously with qt6.2 and older qt version it was in `/usr/local/opt/qt6/bin/`

Currently 
ls /usr/local/opt/qt6/bin/

qhelpgenerator not found

### What happened (include all command output)?

```
% qml --version             
Qml Runtime 6.3.0
% qhelpgenerator
zsh: command not found: qhelpgenerator
```

### What did you expect to happen?

Where is qhelpgenerator with qt6.3 ?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install qt
```

**Comment by SMillerDev** [comment]
Did you report this to the qt project?

**Comment by Nelson-numerical-software** [comment]
> Did you report this to the qt project?

qhelpgenerator is available in official qt6 online binary package 
![image](https://user-images.githubusercontent.com/23081266/172021941-debf90c4-cd37-4197-9071-1370931fbc8f.png)
`./6.3.0/macos/libexec/qhelpgenerator`

And for brew path seems to have changed to:

`./Cellar/qt/6.3.0/share/qt/libexec/qhelpgenerator`
