### ISSUE TITLE
assimp 5.2.4 failure install on macOS

### ISSUE THREAD

**Issue by xlla** [Homebrew/homebrew-core#102992]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.4.11-173-gbdc32c2-dirty
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: bdc32c24cc6dfbd9a3f3f2a4a20bf5dce64874fc
Last commit: 4 days ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 8936c8cb6f96ec34fcc35b7fa77cbc229aa9dcec
Core tap last commit: 23 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SOuP8LrHd0/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 10.0.1 build 1001
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.2.1
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am try to upgrade assimp from 5.1.2 to 5.2.4, because dartsim depend on it.

### What happened (include all command output)?

==> Upgrading dartsim
  6.12.1_1 -> 6.12.1_3 

==> Installing dependencies for dartsim: assimp, octomap, libaec, hdf5, flann, openjdk, openblas, ipopt, jpeg-turbo, open-scene-graph and console_bridge
==> Installing dartsim dependency: assimp
==> cmake -GNinja -DASSIMP_BUILD_TESTS=OFF -DCMAKE_INSTALL_RPATH=@loader_path/../lib ..
==> ninja install
Last 15 lines from /Users/xlla/Library/Logs/Homebrew/assimp/02.ninja:
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DASSIMP_BUILD_NO_M3D_EXPORTER -DASSIMP_BUILD_NO_M3D_IMPORTER -DASSIMP_BUILD_NO_OWN_ZLIB -DMINIZ_USE_UNALIGNED_LOADS_AND_STORES=0 -DOPENDDLPARSER_BUILD -DRAPIDJSON_HAS_STDSTRING=1 -DRAPIDJSON_NOMEMBERITERATORCLASS -Dassimp_EXPORTS -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/build/include -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/build -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/include -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/. -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/../contrib/pugixml/src -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/../contrib/rapidjson/include -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/../contrib -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/../contrib/openddlparser/include -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/../include -I/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/build/code/../include -I/usr/local/Cellar/minizip/1.2.11/include/minizip -fvisibility=hidden -fno-strict-aliasing -Wall -Wno-long-long  -O3 -DNDEBUG -fPIC -Wall -Werror -std=gnu++11 -MD -MT code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o -MF code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o.d -o code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o -c /tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp
/tmp/assimp-20220605-36833-mxpdsz/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:57:14: fatal error: 'unzip.h' file not found
#    include <unzip.h>
             ^~~~~~~~~
1 error generated.
[9/234] Building CXX object code/CMakeFiles/assimp.dir/Common/SGSpatialSort.cpp.o
[10/234] Building CXX object code/CMakeFiles/assimp.dir/Common/VertexTriangleAdjacency.cpp.o
[11/234] Building CXX object code/CMakeFiles/assimp.dir/Common/SpatialSort.cpp.o
[12/234] Building CXX object code/CMakeFiles/assimp.dir/Common/ScenePreprocessor.cpp.o
[13/234] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseImporter.cpp.o
[14/234] Building CXX object code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.o
[15/234] Building CXX object code/CMakeFiles/assimp.dir/Common/SceneCombiner.cpp.o
[16/234] Building CXX object code/CMakeFiles/assimp.dir/Common/Importer.cpp.o
[17/234] Building CXX object code/CMakeFiles/assimp.dir/Common/Assimp.cpp.o
ninja: build stopped: subcommand failed.

Do not report this issue to Homebrew/brew or Homebrew/core!

### What did you expect to happen?

successful installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I found my system missing unzip.h , after add flag ASSIMP_BUILD_ZLIB , it raise another exception, 

<pre>
/tmp/assimp-20220605-76560-hgjp5f/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:199:50: error: expected ';' after expression
    mapping.zopendisk_file = (opendisk_file_func)opendisk;
                                                 ^
                                                 ;
/tmp/assimp-20220605-76560-hgjp5f/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:199:13: error: no member named 'zopendisk_file' in 'zlib_filefunc_def_s'
    mapping.zopendisk_file = (opendisk_file_func)opendisk;
    ~~~~~~~ ^
/tmp/assimp-20220605-76560-hgjp5f/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:199:31: error: use of undeclared identifier 'opendisk_file_func'
    mapping.zopendisk_file = (opendisk_file_func)opendisk;
                              ^
/tmp/assimp-20220605-76560-hgjp5f/assimp-5.2.4/code/Common/ZipArchiveIOSystem.cpp:199:50: error: expression result unused [-Werror,-Wunused-value]
    mapping.zopendisk_file = (opendisk_file_func)opendisk;
                                                 ^~~~~~~~
4 errors generated.
bash-3.2$ ninja install
</pre>

it seems need this [patch](https://raw.githubusercontent.com/conan-io/conan-center-index/master/recipes/assimp/5.x/patches/0005-fix-unzip.patch) .
```

**Comment by carlocab** [comment]
Sorry, but we don't provide support for source build failures, or for versions of macOS older than 10.15. You see this from the output of `brew doctor`.

**Comment by xlla** [comment]
@carlocab , I have read the output warning from brew and known the lack support for source build,  I have solved this issue already,  I just want to post some hint to help others who encounter similar problem.

**Comment by carlocab** [comment]
That's kind of you, but our issue tracker isn't the right place to post this.
