### ISSUE TITLE
Some formulae have `:all` and tag-specific bottles

### ISSUE THREAD

**Issue by danielnachun** [Homebrew/homebrew-core#103052]
Due to a bug in the rollout of `:all` bottles, a small number of formulae mistakenly ended up with both tag-specific and `:all` bottles.  Although the bug is now fixed, these formulae need to be cleaned up so that they either have only an `:all` or tag-specific bottles.  

From what I could see, most of these seem like they should be `:all`, as they do not seem to be calling anything that looks like it would compile native code.  I am not aware of any breakage caused by this as tag-specific bottles are always preferred over `:all` bottles, but this is still confusing for both users and maintainers so it would be good for us to clean this up.

- [x] align
- [x] chruby
- [x] cvsutils
- [x] docx2txt
- [x] dupseek
- [x] easy-rsa
- [x] foreman
- [x] fpp
- [x] g2
- [x] generate-json-schema
- [x] ghi
- [x] gist
- [x] git-cal
- [x] git-integration
- [x] git-multipush
- [x] git-now
- [x] git-number
- [x] git-octopus
- [x] git-secrets
- [x] git-standup
- [x] git-tracker
- [ ] gnome-common
- [x] gpm
- [x] gvp
- [x] icon-naming-utils
- [x] jsonlint
- [x] kaitai-struct-compiler
- [x] logcheck
- [x] lolcat
- [x] markdown
- [x] mecab-jumandic
- [x] mecab-unidic
- [x] mkvdts2ac3
- [x] ndiff
- [ ] onetime
- [x] pass-otp
- [x] pex
- [x] pipes-sh
- [x] pkgdiff
- [x] quicktype
- [x] react-native-cli
- [x] roundup
- [x] rubyfmt
- [x] ry
- [x] sjk
- [x] sloc
- [x] st
- [x] terraform_landscape
- [x] tesseract-lang
- [x] translate-shell
- [x] um
- [x] umple
- [x] urdfdom_headers
- [x] vert.x
- [x] vip
- [x] wemux
- [x] xbitmaps
- [x] zshdb

**Comment by cho-m** [comment]
Removed `all` bottles from non-deprecated formulae in #123249.

Left them for deprecated, non-disabled formulae (`gnome-common`, `mergepbx`, `onetime`).
