### ISSUE TITLE
bash 4.3.42 and readline library not found

### ISSUE THREAD

**Issue by onlynone** [Homebrew/homebrew-core#10315]
I had the same problem described in issue #5799 . The problem was that trying to run bash lead to the error:

```
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
Trace/BPT trap: 5
```

And bash wouldn't run. The solution was to upgrade bash (of course this isn't trivial when your main shell is `/usr/local/bin/bash`).

I'd just like to know why his would happen, and how to avoid problems like these in the future? Was there a bug in the formula for bash or readline? Is this expected behavior? Should upgrades of libraries fail if another package has dependencies on a specific version?

**Comment by Numbermaniac** [comment]
For future reference, you probably could use the system's `/bin/bash` next time as a backup. You can specify your launch shell in Terminal's settings, if that's what you use.

Did `brew list` tell you readline was installed?

**Comment by ilovezfs** [comment]
The current version of bash is 4.4.12, so it sounds like your repository is outdated, in which case, sure, something could be out of sync. But no, in general upgrades shouldn't break reverse dependencies, except when you've built with options, in which case yes, it is expected that you will have to run `brew reinstall` manually when there are ABI breaking upgrades to your non-default dependencies.
