### ISSUE TITLE
brew install freetds --with-unixodbc fails

### ISSUE THREAD

**Issue by kyungguyeo** [Homebrew/homebrew-core#10314]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug report:

When trying to run `brew install freetds --with-unixodbc` the command hangs for a very long time then errors with this output:

```
$ brew install freetds --with-unixodbc
==> Using the sandbox
==> Downloading ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.00.26.tar.bz2

curl: (56) response reading failed
Trying a mirror...
==> Downloading https://fossies.org/linux/privat/freetds-1.00.26.tar.bz2

curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "freetds"
Download failed: https://fossies.org/linux/privat/freetds-1.00.26.tar.bz2
```

Here's my brew config output:

```
$ brew config
HOMEBREW_VERSION: 1.1.10-217-g7077717a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7077717af9cc9b40c8bb61cf3cb15e3b5fe5d209
Last commit: 56 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 50e01ee4628d5ddef74ea359dea90a24efb68a67
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_111, 1.6.0_65-b14-468
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

here's my brew doctor output:

```
$ brew doctor
Your system is ready to brew.
```

It appears freetds has no gist-logs:

```
$ brew gist-logs freetds
Error: No logs.
```

**Comment by ilovezfs** [comment]
Are you behind a proxy or firewall?

**Comment by kyungguyeo** [comment]
Oh, i might be - I am using my work network. Could that be the issue? If so, is there a work around where I can still do it through my work network?

**Comment by ilovezfs** [comment]
you can try this link https://distfiles.macports.org/freetds/freetds-1.00.26.tar.bz2 and place the file in  ~/Library/Caches/Homebrew

**Comment by kyungguyeo** [comment]
then run the command?

**Comment by ilovezfs** [comment]
yes

**Comment by kyungguyeo** [comment]
wow, looks like this worked...! Thanks!

**Comment by JCount** [comment]
That's great! I am closing this as resolved.
