### ISSUE TITLE
`hardlink` in util-linux defaults to the sha256 comparison method, which never works on Mac

### ISSUE THREAD

**Issue by DrHyde** [Homebrew/homebrew-core#103304]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ $ brew config
HOMEBREW_VERSION: 3.5.1-26-g39f30d7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 39f30d75d45ee4a770f649076f03446df0a2b48d
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f99f0d0ded31140e0e16466395d2d6fd9fdfd0af
Core tap last commit: 23 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.5-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
~ $ brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use the `hardlink` utility from `util-linux`.

### What happened (include all command output)?

By default `hardlink` uses the `sha256` method for comparing file contents. On Linux this uses an in-kernel implementation, on Mac OS it spits out a warning to STDERR and then falls back to the `memcmp` comparison method:

```
~ $ hardlink -nq foo bar
hardlink: cannot initialize sha256 method, use 'memcmp' fallback
```

### What did you expect to happen?

No warning on STDERR

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install util-linux
mkdir foo bar
hardlink -nq foo bar
```

to make it go away:

```
hardlink -nq -y memcmp foo bar
```

so an easy fix would be to change the default in hardlink.c if running on a Mac.

**Comment by carlocab** [comment]
Fixed in https://github.com/util-linux/util-linux/pull/1713. We can either wait for a new release or backport the patch. Feel free to open a PR for either as and when appropriate.

**Comment by DrHyde** [comment]
There's an easy work-around so I don't think it's worth backporting. I'll keep an eye out for a new release.
