### ISSUE TITLE
brew prints zsh completion hint 2 times when it installs git.

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#10338]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general
Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

I see zsh completion hint 2 times when I do install git.

```
$ brew reinstall git
==> Reinstalling git 
==> Downloading https://homebrew.bintray.com/bottles/git-2.12.0.sierra.bottle.ta
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/git-2.12.0.sierra.bottle.tar.gz
==> Pouring git-2.12.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions

zsh functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
/usr/local/Cellar/git/2.12.0: 1,452 files, 33.0M
```

**Comment by dunn** [comment]
Does this happen with any other formulae that have zsh completions?

**Comment by yurikoles** [comment]
@dunn could you give an example of such formulae?

**Comment by dunn** [comment]
[`youtube-dl.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/youtube-dl.rb), but grepping for `zsh_completion` will turn up lots.

**Comment by yurikoles** [comment]
I had tried youtube-dl and mercurial, both of them print zsh completion message only once. So it seems like problem with git formulae.

**Comment by dunn** [comment]
Good to know, thanks!

**Comment by dunn** [comment]
I'm seeing the same thing with the git formula, so that's not just you.

**Comment by dunn** [comment]
It took me digging into `caveats.rb` to see what's going on.  The first is about zsh _completions_, the second is zsh _functions_.

We should probably combine the two, or make them easier to differentiate.

**Comment by MikeMcQuaid** [comment]
> It took me digging into caveats.rb to see what's going on. The first is about zsh completions, the second is zsh functions.

Closing as this isn't actually a bug.

**Comment by yurikoles** [comment]
Sorry for boring you, guys.
