### ISSUE TITLE
many autotools do not install foo-ver in addition to foo

### ISSUE THREAD

**Issue by sam-s** [Homebrew/homebrew-core#10354]
users of autotools expect `foo-version` in addition to `foo`
e.g.,  `/usr/local/bin/aclocal` is a hard link to `/usr/local/bin/aclocal-1.15`.
however, 
```
$ ls -l /usr/local/bin/auto*
8 lrwxrwxr-x  1 sds  admin  36 Aug 16  2016 /usr/local/bin/autoconf@ -> ../Cellar/autoconf/2.69/bin/autoconf
8 lrwxrwxr-x  1 sds  admin  38 Aug 16  2016 /usr/local/bin/autoheader@ -> ../Cellar/autoconf/2.69/bin/autoheader
8 lrwxrwxr-x  1 sds  admin  36 Aug 16  2016 /usr/local/bin/autom4te@ -> ../Cellar/autoconf/2.69/bin/autom4te
8 lrwxrwxr-x  1 sds  admin  36 Aug 16  2016 /usr/local/bin/automake@ -> ../Cellar/automake/1.15/bin/automake
8 lrwxrwxr-x  1 sds  admin  41 Aug 16  2016 /usr/local/bin/automake-1.15@ -> ../Cellar/automake/1.15/bin/automake-1.15
8 lrwxrwxr-x  1 sds  admin  38 Aug 16  2016 /usr/local/bin/autoreconf@ -> ../Cellar/autoconf/2.69/bin/autoreconf
8 lrwxrwxr-x  1 sds  admin  36 Aug 16  2016 /usr/local/bin/autoscan@ -> ../Cellar/autoconf/2.69/bin/autoscan
8 lrwxrwxr-x  1 sds  admin  38 Aug 16  2016 /usr/local/bin/autoupdate@ -> ../Cellar/autoconf/2.69/bin/autoupdate
```
IOW, the following links are missing:
`autoconf-2.69`
`autoheader-2.69`
&c

**Comment by MikeMcQuaid** [comment]
As this isn't causing any issues for Homebrew itself we'd consider accepting a PR for this but the upstream build system should probably be the one creating these symlinks.

**Comment by sam-s** [comment]
linux installations of autotools always contain those symlinks.
this problem is unique to homebrew.

**Comment by MikeMcQuaid** [comment]
We don't remove any symlinks but upstream isn't creating any. We try to match their configuration as closely as possible. Linux package managers differ from Homebrew in many ways; our goal isn't to emulate them unconditionally.
