### ISSUE TITLE
Bundletool with Zulu OpenJDK

### ISSUE THREAD

**Issue by yvbeek** [Homebrew/homebrew-core#103636]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 49132f7004a77370960db8ae9c38e90a88473630
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.36.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-x86_64
CLT: 12.5.0.22.9
Xcode: 13.4.1
```

The other two commands throw an error: "Command Line Tools are too outdated". Think that might be a separate Homebrew issue. I have 13.4.1, which is newer than 13.4.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

[React-Native recommends to use the Zulu OpenJDK cask](https://reactnative.dev/docs/environment-setup) instead of the OpenJDK formula. However there are some formulas that have the (regular) OpenJDK formula as a dependency. This will probably affect quite a number of users, because the Zulu cask seems to have better M1 support.

One of those formulas is bundletool. I've now installed bundletool using the following command: `brew install --ignore-dependencies bundletool`, but HomeBrew is yelling at me that this is an unsupported developer flag.

What would be the correct way for the bundletool formula to recognize that OpenJDK is already available?

### What happened (include all command output)?

When you run `brew install bundletool` it installs both `bundletool` and `openjdk`

When you run `brew install --ignore-dependencies bundletool`, it only installs `bundletool`, but based on the error message this will likely break in the near future.

### What did you expect to happen?

For the bundletool (and other formulas that require OpenJDK) to recognize the Zulu OpenJDK cask and therefor Homebrew doesn't install the regular OpenJDK

Or for the `--ignore-dependencies` option to not throw any errors. Although it might be better if you would be able to tell Homebrew to ignore one specific dependency (like OpenJDK in this example).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap homebrew/cask-versions
brew install --cask zulu11
brew install bundletool

or

brew tap homebrew/cask-versions
brew install --cask zulu11
brew install --ignore-dependencies bundletool
```

**Comment by gromgit** [comment]
Someone else will have to comment on your main issue, but...

> The other two commands throw an error: "Command Line Tools are too outdated". Think that might be a separate Homebrew issue. I have 13.4.1, which is newer than 13.4.

Nope.
>```
>CLT: 12.5.0.22.9
>Xcode: 13.4.1
>```

Your **Command Line Tools** (CLT) package is still at 12.5. Running `softwareupdate -l` should confirm that an update is available.

**Comment by SMillerDev** [comment]
> What would be the correct way for the bundletool formula to recognize that OpenJDK is already available?

It should check the `JAVA_HOME` variable.

> For the bundletool (and other formulas that require OpenJDK) to recognize the Zulu OpenJDK cask and therefor Homebrew doesn't install the regular OpenJDK

This won't happen, Homebrew installs all dependencies it requires for the software to function. You can only override the Java version it uses with `JAVA_HOME`

**Comment by carlocab** [comment]
> ### What did you expect to happen?
> For the bundletool (and other formulas that require OpenJDK) to recognize the Zulu OpenJDK cask and therefor Homebrew doesn't install the regular OpenJDK
> 
> Or for the `--ignore-dependencies` option to not throw any errors. Although it might be better if you would be able to tell Homebrew to ignore one specific dependency (like OpenJDK in this example).

We used to support replacing Homebrew-provided dependencies with software that users already have installed. It led to many complaints about things not working, because it leads to users running configurations we don't test in CI. So, we no longer support this, but instead provide a way to use the `JAVA_HOME` environment variable to use your preferred JDK. Otherwise, we don't support replacing dependencies in formulae.
