### ISSUE TITLE
reattach-to-user-namespace wrapper breaks pbcopy 

### ISSUE THREAD

**Issue by fatmcgav** [Homebrew/homebrew-core#10377]
It would appear that the [`with-wrap-pbcopy-and-pbpaste`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/reattach-to-user-namespace.rb#L17) option causes the `pbcopy -help` command to hang, which in turn causes some commands to hang, such as the Openstack python client.

Reported against `reattached-to-user-namespace` project [here](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/60), and the author has advised me that this is an issue with the homebrew [pbcopy shim](https://github.com/Homebrew/homebrew-core/blob/master/Formula/reattach-to-user-namespace.rb#L30). 

`brew info reattach-to-user-namespace`:
>╰─ brew info reattach-to-user-namespace
reattach-to-user-namespace: stable 2.5 (bottled), HEAD
Reattach process (e.g., tmux) to background
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
/usr/local/Cellar/reattach-to-user-namespace/2.5 (6 files, 34.2K) *
  Poured from bottle on 2017-02-24 at 15:01:03
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/reattach-to-user-namespace.rb
==> Options
--with-wrap-launchctl
        Include wrapper for launchctl with this fix
--with-wrap-pbcopy-and-pbpaste
        Include wrappers for pbcopy/pbpaste that shim in this fix
--HEAD
        Install HEAD version

`brew config` output:
>╰─ brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 50e01ee4628d5ddef74ea359dea90a24efb68a67
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A

**Comment by bfontaine** [comment]
Do you want to try and make a pull-request to fix these wrappers?

**Comment by MikeMcQuaid** [comment]
This is almost certainly not a Homebrew-specific bug so closing this.

**Comment by fatmcgav** [comment]
@MikeMcQuaid I'm not sure I follow your reasoning... 

The issue _only_ occurs when using the `--with-wrap-pbcopy-and-paste` option, which is _only_ provided as part of the Homebrew formula... So how is it _NOT_ and issue with the Homebrew formula?

**Comment by MikeMcQuaid** [comment]
My apologies, misread.

**Comment by fatmcgav** [comment]
@MikeMcQuaid Cheers :) 

@bfontaine I can give it a go, but if I'm honest I'm probably not familiar enough with what the wrapper script is trying to achieve...

**Comment by bfontaine** [comment]
At first glance it seems the wrapper should just pass its arguments to `reattach-to-user-namespace`. The `pbcopy` would look like this:

```sh
reattach-to-user-namespace /usr/bin/pbcopy $*
```

And the `pbpaste` one:

```sh
reattach-to-user-namespace /usr/bin/pbpaste $*
```

I haven’t tested, though.

**Comment by fxcoudert** [comment]
Why are we providing wrappers if upstream doesn't consider them worthy of being included?

**Comment by MikeMcQuaid** [comment]
> Why are we providing wrappers if upstream doesn't consider them worthy of being included?

@fxcoudert A good question. I'd be OK with removing them.

**Comment by fxcoudert** [comment]
PR opened for that, closing here: #10668
