### ISSUE TITLE
Not able to install vscodium on Ubuntu

### ISSUE THREAD

**Issue by aphive** [Homebrew/homebrew-core#104017]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
brew gist-logs vscodium
Error: No available formula with the name "vscodium".
```

```
brew config
HOMEBREW_VERSION: 3.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fba051f98f609634ae4392d0053ddfc627f8cdb3
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b2f0485ab0d35be6577232021a524f4df8831bb4
Core tap last commit: 6 days ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit unknown_0x6_0x8d
Clang: N/A
Git: 2.36.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-37-generic x86_64 GNU/Linux
OS: Ubuntu 22.04 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

```
brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Not sure if this is the correct place to submit this but there wasn't really another option other than start a community discussion, please let me know if there is an alternative path to submit this or if it should actually be a discussion or other and I will redo.

Trying to install vscodium to replace vscode on my machine. Can we expand this to also be able to install on Ubuntu or other *nix Os?

### What happened (include all command output)?

```
brew install vscodium
Warning: No available formula with the name "vscodium".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

```
brew install --cask vscodium
Error: Cask 'vscodium' is unavailable: No Cask with this name exists.
```

### What did you expect to happen?

Be able to install vscodium using brew on my Ubuntu laptop.

### Step-by-step reproduction instructions (by running `brew` commands)

I included all the commands I tried in the *What happened (include all command output)?* section, nothing else could be done. I did ensure I had all the latest brew related things by running 

```shell
brew update; brew upgrade; brew cleanup; brew doctor
```

**Comment by SMillerDev** [comment]
Casks do not work on Linux so this is expected behavior.
