### ISSUE TITLE
Update link to https in Github description

### ISSUE THREAD

**Issue by leonklingele** [Homebrew/homebrew-core#10409]
The description of this repo uses a http:// URL. Please switch to https://, as the domain brew.sh is not in the HTTPS Preload List.

**Comment by MikeMcQuaid** [comment]
Done.

**Comment by leonklingele** [comment]
Thanks @MikeMcQuaid
It looks like all other repos and the [Homebrew group](https://github.com/Homebrew) are using that http:// URL as well..

**Comment by MikeMcQuaid** [comment]
I'll do them later.

**Comment by leonklingele** [comment]
Can this issue please be reopened until it's fully resolved?

**Comment by MikeMcQuaid** [comment]
It's on my list of things to do.

**Comment by MikeMcQuaid** [comment]
Done.

**Comment by leonklingele** [comment]
👍 The [group overview](https://github.com/Homebrew) still uses http://

**Comment by MikeMcQuaid** [comment]
Done too.
