### ISSUE TITLE
Request to add Audacity to Homebrew

### ISSUE THREAD

**Issue by setek** [Homebrew/homebrew-core#10423]
Hi,

I tried to add Audacity to Homebrew, but I couldn’t get it to work properly.

You go to page: [Audacity download link](https://www.fosshub.com/Audacity.html/audacity-macosx-ub-2.1.2.dmg), which then fetches:
```
https://download.fosshub.com/Protected/expiretime=1488263191;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/ea4cbebcffb671e5c84149c1f46c1999ade56f6938c2a442dadacc611ba94be6/Audacity/audacity-macosx-ub-2.1.2.dmg
```

… where it seems like the `expiretime`, `badurl` etc. change on an individual basis. So I couldn’t get my `audacity.rb` to work:

```
cask 'audacity' do
  version '2.1.2'
  sha256 '2e4b7d608ecc0d2f79bf16663f085d383075e488f7d50bf7d74c0b69173defe7'

  url 'https://download.fosshub.com/Protected/expiretime=1488263191;badurl=aHR0cDovL3d3dy5mb3NzaHViLmNvbS9BdWRhY2l0eS5odG1s/ea4cbebcffb671e5c84149c1f46c1999ade56f6938c2a442dadacc611ba94be6/Audacity/audacity-macosx-ub-2.1.2.dmg'
  name 'Audacity'
  homepage 'http://www.audacityteam.org/'

  app 'Audacity/Audacity.app'
end
```

Anybody have any insights? How can I fix this?

Thanks!

**Comment by miccal** [comment]
> Anybody have any insights? How can I fix this?

You can't as Fosshub's terms of service do not allow automated downloads - see [this thread](https://github.com/caskroom/homebrew-cask/pull/27517) for more information.

**Comment by luizcavalcanti** [comment]
What about now that audacity is on github? https://github.com/audacity/audacity
