### ISSUE TITLE
imagemagick 6.9.4-0 is not available anymore

### ISSUE THREAD

**Issue by Tafkas** [Homebrew/homebrew-core#1042]
Trying to upgrade imagemagick gives

> ==> Upgrading imagemagick
> ==> Downloading https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.4-0.tar.x
> 
> curl: (22) The requested URL returned error: 404 Not Found
> Trying a mirror...
> ==> Downloading https://www.imagemagick.org/download/ImageMagick-6.9.4-0.tar.xz
> 
> curl: (22) The requested URL returned error: 404 Not Found
> Error: Failed to download resource "imagemagick"
> Download failed: https://www.imagemagick.org/download/ImageMagick-6.9.4-0.tar.xz

The resource is not available. It has been replaced with version 6.9.4-0 -> https://www.imagemagick.org/download/ImageMagick-6.9.4-1.tar.xz

**Comment by Tafkas** [comment]
I submitted a PR at #1043

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/1043, Thanks!
