### ISSUE TITLE
brew do not provide support for  macOS 13.

### ISSUE THREAD

**Issue by xinmans** [Homebrew/homebrew-core#104329]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
xinmans@LincM1 ~ %   brew install terraform
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install

Error: 'git' must be installed and in your PATH!
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install

xinmans@LincM1 ~ %
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

 brew install terraform

### What happened (include all command output)?

Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

### What did you expect to happen?

Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.
```

**Comment by SMillerDev** [comment]
The message says it all
