### ISSUE TITLE
Emacs formula actually requires imagemagick@6 to support --with-imagemagick

### ISSUE THREAD

**Issue by tchajed** [Homebrew/homebrew-core#10453]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

Emacs depends on imagemagick 6 rather than 7 to integrate imagemagick support. Installing with `--with-imagemagick` appears to work, except that `./configure` reports imagemagick was not found and the final build doesn't have imagemagick support (this can be checked by looking at the output of `M-x report-emacs-bug`: the list of configured features should include "IMAGEMAGICK").

I can easily get the formula to build with `brew switch imagemagick 6.9.7-3`, but it should be possible to depend on `imagemagick@6` and use it instead. Unfortunately I couldn't figure out how to do this - setting `PKG_CONFIG_PATH` works for me when I build Emacs manually (at least the `./configure` output is right), but not when I tried to modify the formula.

With some pointers on how to depend on an old version of a package including `pkg-config` (or even just the right way to debug this) I'd be happy to submit a pull request to fix this issue.

`brew config`:

```
HOMEBREW_VERSION: 1.1.10-425-gfa34aa2a2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa34aa2a21473a4e4d360e9561f8ca89f2415ded
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f58aa629a583e8e4c15cff2661c0d2a9f80c3078
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

`brew doctor`:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.5m/greenlet/greenlet.h
  /usr/local/include/python3.6m/greenlet/greenlet.h

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Users/tchajed/code/sw/coq/bin/
```

**Comment by MikeMcQuaid** [comment]
Can you try adding `depends_on "imagemagick@6" => :optional` and using that option? Thanks!

**Comment by ilovezfs** [comment]
doesn't work.

**Comment by ilovezfs** [comment]
looks like that does work if I also pass --with-cocoa

**Comment by tchajed** [comment]
Sweet, thanks for the help! I can confirm that works for me as well.

Here's a simpler way to test than reading `report-emacs-bug`, by the way:
`emacs --batch --eval='(princ (format "configured with: %s\nfeatures: %s\n" system-configuration-options system-configuration-features))'`

With emacs installed using `brew install --with-cocoa --with-gnutls --with-imagemagick@6 --with-librsvg emacs`, this prints the following for me now:
```
configured with: --disable-dependency-tracking --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/25.1/share/info/emacs --prefix=/usr/local/Cellar/emacs/25.1 --without-x --with-xml2 --without-dbus --with-gnutls --with-rsvg --with-ns --disable-ns-self-contained
features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS
```
