### ISSUE TITLE
reinstallation of openssl fails because libcrypto is missing - indeed it is removed during the reinstall process

### ISSUE THREAD

**Issue by dalloliogm** [Homebrew/homebrew-core#10476]
When I try to install a new version of openssl, I get errors saying that libcrypto.so.1.0 is missing:

> $: brew reinstall openssl
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> /GWD/bioinfo/projects/RD-TSci-Software/CB/linuxbrew/bin/git: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
> 

What happens is that libcrypto.so.1.0 is indeed installed and I can see it in the $HOMEBREW/lib folder. The problem is, when openssl is reinstalled, this libcrypto file is removed / unlinked, so it is no longer there. Since there is no libcrypto.so.1.0 file anywhere else in the system, the installation fails.

**Comment by MikeMcQuaid** [comment]
> linuxbrew

This is Homebrew so please don't report Linux stuff here, thanks.

You also didn't fill out the issue template which we need to debug any issue.
