### ISSUE TITLE
minizip 1.2.11 bottle can't be found (404)

### ISSUE THREAD

**Issue by vszakats** [Homebrew/homebrew-core#10480]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

---

Bottle can't be found since the `minizip` formula got updated yesterday:
```
==> Upgrading 1 outdated package, with result:
minizip 1.2.11
==> Upgrading minizip 
==> Downloading https://homebrew.bintray.com/bottles/minizip-1.2.11.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "minizip"
Download failed: https://homebrew.bintray.com/bottles/minizip-1.2.11.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
[...]
```

The bottle is missing:
```
$ curl -LI https://homebrew.bintray.com/bottles/minizip-1.2.11.sierra.bottle.tar.gz
HTTP/1.1 404 Not Found
Server: nginx
Date: Wed, 01 Mar 2017 14:47:16 GMT
Content-Type: application/octet-stream
Content-Length: 0
Connection: keep-alive
```

**Comment by JCount** [comment]
Thanks for reporting this. It looks like new bottles were never generated, or at the very least the bottle block was not updated with the rest of the formula. I am making new ones now, and will upload them as soon as I can. 🍁

**Comment by JCount** [comment]
Should be fixed with homwbrew-core@b455761

**Comment by vszakats** [comment]
I can confirm, it's working fine now. Thank you @JCount!

**Comment by alkopop79** [comment]
How do I fix this?

**Comment by ilovezfs** [comment]
@alkopop79 please open an issue and fill out the issue template completely.
