### ISSUE TITLE
`brew install dscanner` fails

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#10494]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

https://gist.github.com/a9655055d27428fd5579bee3fc6f7aca

```
==> Using the sandbox
==> Cloning https://github.com/Hackerpilot/Dscanner.git
Updating /Users/timothee/Library/Caches/Homebrew/dscanner--git
==> Checking out tag v0.3.0
Synchronizing submodule url for 'experimental_allocator'
Synchronizing submodule url for 'experimental_allocator'
==> make dmdbuild
Last 15 lines from /Users/timothee/Library/Logs/Homebrew/dscanner/01.make:
containers/experimental_allocator/src/std/experimental/allocator/package.d(1278): Error: function std.experimental.allocator.CAllocatorImpl!(Mallocator, cast(Flag)false).CAllocatorImpl.alignedAllocate does not override any function

```

**Comment by JCount** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/10496.
