### ISSUE TITLE
g++ doesn't emit code for calling constructor of thread_local static member

### ISSUE THREAD

**Issue by namniav** [Homebrew/homebrew-core#105022]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs gcc
Error: No logs.
```

```
❯ brew config
HOMEBREW_VERSION: 3.5.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b01354f2f8cdbf1315dce4f063b54cdecf95663
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4c070b73d08d205c28060bafe63f4638a3d09940
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

```
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/homebrew-x86_64/bin/pkg-config
  /opt/homebrew-x86_64/bin/python3.9-config
  /opt/homebrew-x86_64/bin/python3-config
  /opt/homebrew-x86_64/bin/em-config

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Compile and run this C++ program:

> foo.hpp:

```c++
#pragma once

struct Foo {
  Foo();
  void func();
};

struct Bar {
  thread_local static Foo foo;
};
```
 > foo.cpp

```c++
#include "foo.hpp"

#include <iostream>

Foo::Foo() {
  std::cout << "Foo::Foo(this=" << this << ")\n";
}

void Foo::func() {
  std::cout << "Foo::func(this=" << this << ")\n";
}

thread_local Foo Bar::foo;
```

> main.cpp

```c++
#include "foo.hpp"

int main() {
  Bar::foo.func();
}
```

### What happened (include all command output)?

```
❯ which g++
/opt/homebrew/bin/g++
❯ g++ --version
g++ (Homebrew GCC 11.3.0_2) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
❯ g++ -Wall -Wextra -Wpedantic -std=c++17 foo.cpp main.cpp
❯ ./a.out
Foo::func(this=0x600001a90038)
```

### What did you expect to happen?

Foo's constructor should be called and the prints `Foo::Foo(this=0x600001a90038)`.

Other info:
1. Clang (either from Apple or Homebrew) doesn't have this issue.
2. The issue would disappear if I combile source files into a single translation unit.
3. GCC-11 on my other devices(WSL and Ubuntu on Intel x86 PC, Termux on Arm-ed Android-10 mobile phone, etc) doesn't have this issue. So I report here until someone tell me that I should report to GCC team.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Create files `foo.hpp`, `foo.cpp` and `main.cpp` with content included above. Then compile and run.

❯ brew install gcc
❯ g++ -Wall -Wextra -Wpedantic -std=c++17 foo.cpp main.cpp
❯ ./a.out
```
```

**Comment by Bo98** [comment]
Do you reckon this bug report covers your issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87199?

**Comment by namniav** [comment]
> Do you reckon this bug report covers your issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87199?

No, that example prints "constest" on my machine, which is expected. I think it may be related. Didn't find it due to subtle difference of searched keywords, thanks.

**Comment by carlocab** [comment]
@fxcoudert, thoughts?

**Comment by fxcoudert** [comment]
I can confirm I see it, no obvious cause in our configure options, so I think it's an upstream bug. I've reported it at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106435 and CC'ed the relevant maintainer.

Thanks @namniav for your clear and reproducible report!

**Comment by carlocab** [comment]
Seems to be ARM-specific, btw:
```
❯ g++-11 -Wall -Wextra -Wpedantic -std=c++17 foo.cpp main.cpp
❯ ./a.out
Foo::func(this=0x600001d44008)
```

**Comment by fxcoudert** [comment]
It's a bug with GCC on all non-ELF platforms (so macOS and Windows), according to the analysis performed in the upstream tracker.

**Comment by fxcoudert** [comment]
Closing this. The proposed bug fix (https://github.com/iains/gcc-12-branch/commit/e5b0693cae732f3027c1cbe5814a3304ba06e743) will be present in the 12.2.0 version which is undergoing testing right now: https://github.com/Homebrew/homebrew-core/pull/108516
