### ISSUE TITLE
Unable to install skopeo on Mac 

### ISSUE THREAD

**Issue by AD1913** [Homebrew/homebrew-core#105055]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config output:

HOMEBREW_VERSION: 3.5.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b01354f2f8cdbf1315dce4f063b54cdecf95663
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7d799a3c20a009f6aa95aa377fef397cba94998d
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew/Homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
all_proxy: http://localhost:3128
http_proxy: http://localhost:3128
https_proxy: http://localhost:3128
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

brew doctor output:
brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install skopeo for Mac using brew install as it is a pre-requisite for one of the products we use for Redhat Openshift but unable to do so in the current version.

Mac OS: Monterey (12.4)

### What happened (include all command output)?

Have tried to install few times but it fails everytime. On the first attempt it gives an error that a curl connect is closed and on the second attempt, it gives an error "curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume."

brew install skopeo
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/manifests/0.21
Already downloaded: /Users/akulad/Library/Caches/Homebrew/downloads/66569d4eb02ec67195446d3dcba7d7806a35f88f629a55b43ba53fb1febb1f56--gettext-0.21.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:6e2c829031949c0cbd758d0701ed62c191387736e76a98a046c0619907632225
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:6e2c829031949c0cbd758d0701ed62c191387736e76a98a046c0619907632225?se=2022-07-04T05%3A30
##############################################################            86.3%curl: (18) transfer closed with 576508 bytes remaining to read

Error: skopeo: Failed to download resource "gettext"
Download failed: https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:6e2c829031949c0cbd758d0701ed62c191387736e76a98a046c0619907632225

 brew install skopeo
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/manifests/0.21
Already downloaded: /Users/akulad/Library/Caches/Homebrew/downloads/66569d4eb02ec67195446d3dcba7d7806a35f88f629a55b43ba53fb1febb1f56--gettext-0.21.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:6e2c829031949c0cbd758d0701ed62c191387736e76a98a046c0619907632225
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:6e2c829031949c0cbd758d0701ed62c191387736e76a98a046c0619907632225?se=2022-07-04T05%3A30
######################################################################## 100.0%curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

Error: skopeo: Failed to download resource "gettext"
Download failed: https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:6e2c829031949c0cbd758d0701ed62c191387736e76a98a046c0619907632225

### What did you expect to happen?

skopeo to be installed successfully and should be able to access skopeo from the terminal

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install skopeo
```

**Comment by SMillerDev** [comment]
Thus is a network issue between you and github, there is nothing brew can do about that.

**Comment by AD1913** [comment]
Just fyi, this looks to be happening both with home network and work network. May I know if it would still be a network issue?

"curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume."

**Comment by carlocab** [comment]
Try running it without your proxy:
```
all_proxy: http://localhost:3128
http_proxy: http://localhost:3128
https_proxy: http://localhost:3128
```

> Just fyi, this looks to be happening both with home network and work network. May I know if it would still be a network issue?

It doesn't seem to be reproducible by other users, so it's likely either a network issue on your end (with both your home and work networks) or a configuration issue (probably your proxy settings).
