### ISSUE TITLE
Maven 3.5 formula

### ISSUE THREAD

**Issue by mattnelson** [Homebrew/homebrew-core#10524]
### Formula Requests:

Create a new versioned formula for the alpha release of maven 3.5.

Requested formula: maven@3.5

http://blog.soebes.de/blog/2017/03/01/apache-maven-version-3-dot-5-0-alpha-1-released/

**Comment by fxcoudert** [comment]
We do not create versioned formulas for development versions. However, the alpha release was added to the main formula as devel (#10525), so you can install it with `brew install --devel maven`.

**Comment by paskos** [comment]
Maven 3.5 is alpha anymore, any plan for a 3.5 formula ?

**Comment by ilovezfs** [comment]
The current version in Homebrew is 3.5.0: https://github.com/Homebrew/homebrew-core/pull/12228.
