### ISSUE TITLE
gsettings-desktop-schemas does not install

### ISSUE THREAD

**Issue by programmingkidx** [Homebrew/homebrew-core#1054]
### Bug reports:

When installing gsettings-desktop-schemas, the installation will stop at 'make install'. The command will not do anything as if it froze.

**Comment by UniqMartin** [comment]
Sorry, but you have not followed the requested steps in our [Troubleshooting Guide](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting). Please follow (all of) these steps and post the information here so we can help you with your problem. Thanks!

**Comment by ilovezfs** [comment]
Running `brew test-bot gsettings-desktop-schemas` locally passes fine.

**Comment by DomT4** [comment]
Closing as dead, but please shout if we can offer any assistance here still. Thanks!
