### ISSUE TITLE
Add installationMethod to package.json for yarn formula

### ISSUE THREAD

**Issue by OmgImAlexis** [Homebrew/homebrew-core#10540]
To allow yarn to know it's been installed via brew the `installationMethod` needs to be set to "brew" in the `package.json` file.

I'm not all that familiar with ruby or Homebrew's formulas so I was hoping someone could point me in the right direction.

Ref: https://github.com/yarnpkg/yarn/issues/2517

**Comment by MikeMcQuaid** [comment]
> I'm not all that familiar with ruby or Homebrew's formulas so I was hoping someone could point me in the right direction.

I'm not familiar enough with what Yarn is wanting here to help either I'm afraid. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by OmgImAlexis** [comment]
In the `package.json` they just need the field `installationMethod` set to brew.

For example when I install version 0.21.3 of Yarn I'd need to add it to the file listed below.
`/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/package.json`
