### ISSUE TITLE
Ruby errors when running brew commands.

### ISSUE THREAD

**Issue by whyisjake** [Homebrew/homebrew-core#1055]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Brew is throwing Ruby errors.

```
➜  ~ brew
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

This is likely something on my end, just throwing this out to see if there is a fix.

**Comment by ilovezfs** [comment]
What OS is this?

**Comment by ilovezfs** [comment]
The fix is likely `sudo /usr/bin/gem uninstall core_ext` but I'm wondering if this is pre-release 10.11.5 since if I try to `sudo /usr/bin/gem install core_ext` I get
```
iMac-TMP:~ joe$ sudo /usr/bin/gem install core_ext
Password:
ERROR:  Error installing core_ext:
	core_ext requires Ruby version >= 2.2.2.
```

**Comment by whyisjake** [comment]
Currently at 10.11.4 (15E65) @ilovezfs.

**Comment by whyisjake** [comment]
```
➜  wired-wp git:(develop) ✗ sudo /usr/bin/gem uninstall core_ext
Password:
➜  wired-wp git:(develop) ✗ brew
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
➜  wired-wp git:(develop) ✗ brew
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
➜  wired-wp git:(develop) ✗ 
```

**Comment by ilovezfs** [comment]
I guess some other ruby besides /usr/bin/ruby installed that, then. Can you try just moving it out of the way?
```
sudo mv /Library/Ruby/Site/2.0.0/rubygems/core_ext ~/Desktop
```

**Comment by ilovezfs** [comment]
@whyisjake Is this now fixed?

**Comment by whyisjake** [comment]
Negative. This is response now:

```
➜  wired-wp git:(wired-video-updates) brew
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

**Comment by whyisjake** [comment]
Dunno if this is related:

```
➜  wired-wp git:(wired-video-updates) ruby
You didn't really think you could install Ruby through npm, did you?
```

**Comment by ilovezfs** [comment]
Can you try this:
```
export HOMEBREW_DEVELOPER=1
export HOMEBREW_RUBY_PATH=/usr/bin/ruby
```

**Comment by whyisjake** [comment]
Same response... :(

**Comment by ilovezfs** [comment]
Can you come one IRC?
https://www.irccloud.com/#!/ircs://irc.freenode.net:6697/%23machomebrew
i.e., freenode #machomebrew

**Comment by whyisjake** [comment]
After some fantastic chat support over IRC, we found that I was pointing to the older repo:

https://gist.github.com/whyisjake/6938b0766e8fc035561fadc86aa93d9a
https://gist.github.com/whyisjake/3c9ef711f77ab5a2738b390afd636eb1

After some debugging, we have got everything updates, and cleaned up. Thanks again for your help @ilovezfs.

**Comment by ilovezfs** [comment]
@whyisjake you're welcome! :fireworks:

**Comment by p-somers** [comment]
I'm having this issue... how do you go about switching to the correct repo?

**Comment by MikeMcQuaid** [comment]
@p-somers Can you try to run `brew update` twice and then paste your `brew config` and `brew doctor` output here? Thanks!

**Comment by p-somers** [comment]
This is what happens when I run `brew update`:
`/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:16:in `<main>'`

`brew config` and `brew doctor` both get the same result

**Comment by MikeMcQuaid** [comment]
@p-somers `cd /usr/local; git fetch; git reset --hard origin/master; brew update`

**Comment by p-somers** [comment]
That worked. Thanks!

**Comment by theDanielJLewis** [comment]
I had this same problem, but I had to add `sudo` to the `git reset …` and `brew update` parts. Then it worked.

**Comment by jakemcallister** [comment]
That worked. Cheers!
