### ISSUE TITLE
macOS Ventura Doesn't Include `groff`

### ISSUE THREAD

**Issue by fishcharlie** [Homebrew/homebrew-core#105682]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 25d9903b7a2033d625f360b173f66b511097e1d5
Core tap last commit: 31 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.32.1 => /Applications/Xcode_14.0-beta.app/Contents/Developer/usr/bin/git
Curl: 7.83.1 => /usr/bin/curl
macOS: 13.0-arm64
CLT: N/A
Xcode: 14.0 => /Applications/Xcode_14.0-beta.app/Contents/Developer
Rosetta 2: false

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  szip

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sdl
  sdl_image

Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.


Warning: Ruby version 2.6.10 is unsupported on macOS 13. Homebrew
is developed and tested on Ruby 2.6.9, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `aws lambda help` from https://formulae.brew.sh/formula/awscli#default.

According to:

https://github.com/Homebrew/homebrew-core/blob/25d9903b7a2033d625f360b173f66b511097e1d5/Formula/awscli.rb#L25

This should be included in macOS. But on macOS Ventura, `groff` isn't included in the OS.

### What happened (include all command output)?

aws lambda help

Could not find executable named "groff"

### What did you expect to happen?

It to succeed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Ensure you are on macOS Ventura
2. `brew install awscli`
3. `aws lambda help`
```

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports to Homebrew. See this message in the bug report template:

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.

**Comment by fishcharlie** [comment]
@carlocab Done.

**Comment by carlocab** [comment]
By `gruff`, do you mean `groff`?

**Comment by polluks** [comment]
By the way how does macOS format its manuals?

**Comment by SMillerDev** [comment]
Checking the code in the `/usr/bin/man` script, it formats it with `groff` if that is available.

**Comment by polluks** [comment]
Indeed, groff is replaced by mandoc right now.

**Comment by fishcharlie** [comment]
Not sure this is stale. Still seems like an active issue.

**Comment by carlocab** [comment]
For us, issues are stale when it seems unlikely that anyone is doing anything about them. The issue describing an existing problem is not sufficient to avoid it becoming stale.

Given the lack of related activity (e.g. PRs), this issue is almost certainly stale, so I'm closing it for now. It also pertains to an unreleased version of macOS.

We can revisit it when Ventura is released.
