### ISSUE TITLE
btop theme directory: path error

### ISSUE THREAD

**Issue by jjsanderson** [Homebrew/homebrew-core#105708]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3ab3f78f55d0e2acaf149334d86cc4438c380b25
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/mate -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false

---

Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

btop is a system monitor similar to htop, bpytop, etc. It installs correctly via `brew install btop`, with a configuration file created in `~/.config/btop/`.

Attempting to alter the btop theme by editing that configuration file has no effect. btop themes are installed in `/opt/homebrew/share/btop/themes`, but this is not found by the binary.

See [this btop bug](https://github.com/aristocratos/btop/issues/344) for discussion; symlinking `/opt/homebrew/share/btop/themes` into `~/.config/btop/` may be an appropriate solution.

### What happened (include all command output)?

btop ignores theme specification in configuration file.

### What did you expect to happen?

btop would find the preinstalled themes.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install btop

[edit ~/.config/btop.conf, alter `color_theme = "..."`]

    btop
```

**Comment by carlocab** [comment]
> If I'm reading [the formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/btop.rb) right (and that's a big if, my Ruby is … poor), it does create `~/.config/btop/` and populate it with a themes directory. I raised the issue because it seemed a bit odd to go that far but not to make it actually, you know, work. :-)

That's not correct.

The directories you are referring to are created in an ephemeral directory for the purposes of testing `btop`. That code is never run unless you actually do `brew test btop`, and even then you won't see those directories unless you also pass `--keep-tmp` to `brew test`.

I tried this out on an Intel Mac and it seems `btop` can find the themes just fine there. Presumably, this is because it knows to check `/usr/local/share/btop/themes`. If `btop` checked `../share/btop/themes` too (relative to the `btop` binary), it would be able to find the themes in an `/opt/homebrew` installation of Homebrew too.

**Comment by carlocab** [comment]
As an alternative workaround, you can also do
```
color_theme = "/opt/homebrew/share/btop/themes/nord.theme"
```
in your `btop.conf`.

**Comment by carlocab** [comment]
Should be fixed now. Do
```
brew update && brew upgrade btop
```

**Comment by jjsanderson** [comment]
That's working for me on 12.4 / M1. Awesome, thanks all.
