### ISSUE TITLE
[rpl] minor logic bug in its -t option (patch provided)

### ISSUE THREAD

**Issue by brevilo** [Homebrew/homebrew-core#105824]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs rpl
Error: No logs.

% brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `rpl` with the `-t` option.

Reason (doesn't matter in this case): such that it doesn't modify the source directory (with temp files) when *no* matches are found.

### What happened (include all command output)?

`rpl` complained: `Unable to read environment var $TMPDIR ...` despite everything worked as expected.

### What did you expect to happen?

No error message.

### Step-by-step reproduction instructions (by running `brew` commands)

Using macOS:
```shell
# Verify $TMPDIR exists and is writable
echo "$TMPDIR"
touch "$TMPDIR/test"

# Create empty file and run `rpl -t` on it
touch x
rpl -t "foo" "bar" x
```

Here's the patch which moves the error message into the correct code branch
```
diff --git a/src/replace.c b/src/replace.c
--- a/src/replace.c
+++ b/src/replace.c
@@ -524,13 +524,12 @@ int main(int argc, char** argv)
 			if(getenv("TMPDIR") != NULL )
 			{
 				strcpy(absPathOut,getenv("TMPDIR"));
-				fprintf(stderr, "\n" PACKAGE ": Unable to read environment var $TMPDIR with -t option active.\n" PACKAGE ": Using source file directory instead.\n" );
-
 			}
 			else
 			{
 				/* No-Go. So use the file's directory for the temp file */
 				strcpy(absPathOut,absPathIn);
+				fprintf(stderr, "\n" PACKAGE ": Unable to read environment var $TMPDIR with -t option active.\n" PACKAGE ": Using source file directory instead.\n" );
 			}
 				
 		}

```
```

**Comment by brevilo** [comment]
I provided the patch here as rpl seems to be unmaintained upstream and the original author (see file header) can't be reached via email anymore.

**Comment by carlocab** [comment]
Sorry, but we have a policy of not carrying patches indefinitely, which is what seems likely to happen if we use this one.

We also don't use patches to source code if they haven't been reviewed by the upstream devs.
