### ISSUE TITLE
after node@18.4.0 - cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/homebrew-core#105968]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config && brew doctor

HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5629a0cef31ec9605f2b4efce9e3ac47e1a0b477
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_COLOR: set
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_FAIL_LOG_LINES: 100
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 4.4.0-20348-Microsoft x86_64 GNU/Linux
OS: Ubuntu 20.04.3 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /home/linuxbrew/.linuxbrew/share/man/man7/package-spec.7
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm running homebrew under Ubuntu 20.04 under WSL (on Github Actions to be specific).

Just trying to get the latest node version up and running with `$ brew install node` and doing a smoke test `$ node -- version ` .

Version 18.3.0 works (I downloaded the old `node.rb` formula and installed it from the local file), but as soon as I go over I get the same error message.

Searching throw the issues, I see that this has happened before, but there's no resolution except "it was magically solved, just update brew and download a newer bottle".

This behaviour is not observed if I run Ubuntu 20.04 under docker e.g. `brew config` says
```
HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4cd544aa50e284c4966e7c127901ad61fc606cc0
Core tap last commit: 11 days ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit unknown_0x0_0x0
Clang: N/A
Git: 2.37.0 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.10.104-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

`file ../node` reports the same for both 18.3.0 and newer: `ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /home/linuxbrew/.linuxbrew/lib/ld.so, for GNU/Linux 2.6.32, not stripped`

### What happened (include all command output)?

`-bash: /home/linuxbrew/.linuxbrew/bin/node: cannot execute binary file: Exec format error`

### What did you expect to happen?

Print node version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install node
node --version
```

**Comment by carlocab** [comment]
Are you running WSL1 or WSL2? Does compiling Node yourself work? (When you compiled Node yourself, did you do it with `brew install --build-from-source` or did you not use `brew` at all?)

**Comment by Bo98** [comment]
WSL1 is buggy and known to randomly fail for any binary (not just node). No one has ever figured out why.

WSL2 will however work reliably.

**Comment by andreineculau** [comment]
@carlocab it is running WSL1 under Windows Server 2019 and 2022. It is not possible to run WSL2 on github actions' runners.

I currently don't have access to a physical Windows machine to run `brew install node --build-from-source node`. On Github Actions, it just takes too long.

@Bo98 randomly and randomly. Something changed from node v18.3.0 (2022-06-03) to v18.4.0 (2022-06-17) and the behaviour is consistent.

Looks like it's affecting other things recently: gzip, adb, etc on ubuntu, arch, etc. Closing as it is not brew-specific, based on online findings. It looks like a workaround exists, but I haven't confirmed it.

---

Relevant threads:
* https://github.com/microsoft/WSL/issues/8151
* https://github.com/microsoft/WSL/issues/8219#issuecomment-1092382219 # problem
* https://github.com/microsoft/WSL/issues/8219#issuecomment-1110508016 # monkey-patch
* https://github.com/microsoft/WSL/issues/8219#issuecomment-1133936081 # generic monkey-patch and more info
* https://gist.github.com/the-moog/179753aacc52b262d1068878d520e9c9 # as a gist
