### ISSUE TITLE
feh ERROR: Can't open X display. It *is* running, yeah?

### ISSUE THREAD

**Issue by punowo** [Homebrew/homebrew-core#105963]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.5.4-95-gf041a59
ORIGIN: https://github.com/Homebrew/brew
HEAD: f041a59af9daddc7c7afe8537e3858103f8f9ab9
Last commit: 17 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0c0f8687381fb9f9cde653cd7bbb12ceb17dcce1
Core tap last commit: 83 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sxiv

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
  ?? Formula/nsxiv.rb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

feh --verbose ~/Pictures/1656860888128.jpeg
feh ERROR: Can't open X display. It *is* running, yeah?

Open an image file.

### What happened (include all command output)?

feh --verbose ~/Pictures/1656860888128.jpeg
feh ERROR: Can't open X display. It *is* running, yeah?

### What did you expect to happen?

See an instance of `feh` open, displaying that image;

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install feh
cd ~/folder_with_image
feh some_image.jpeg
```

**Comment by punowo** [comment]
I've also encountered a similar behavior with sxiv, but that is deprecated.

**Comment by SMillerDev** [comment]
Do you have an x server installed?

**Comment by punowo** [comment]
> Do you have an x server installed?

Ohh I'm sorry I thought macOS had some sort of outdated X Server, but still there, now the `xquartz` I saw in other issues makes sense.
