### ISSUE TITLE
Universal python3 installation converted into non-universal without an error

### ISSUE THREAD

**Issue by sashkab** [Homebrew/homebrew-core#10624]
First of all, 508889d is offender here.

I tried to follow trail on WHY homebrew decided to drop universal support for Python and related packages. 

What is wrong with this -- it was done silently without warning me that this will happen. Suddenly, working system broke. 

This shouldn't be like this. If you decided to brake -- explain why this happened and what is a way to keep universal packages available.

```
==> Upgrading python3
==> Downloading https://homebrew.bintray.com/bottles/python3-3.6.0_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring python3-3.6.0_1.sierra.bottle.tar.gz
==> /usr/local/Cellar/python3/3.6.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.0_1/bin --install-lib=/usr/
==> /usr/local/Cellar/python3/3.6.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.0_1/bin --install-lib=/usr/
==> /usr/local/Cellar/python3/3.6.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.0_1/bin --install-lib=/usr/
==> Caveats
Pip, setuptools, and wheel have been installed. To update them
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: http://docs.brew.sh/Homebrew-and-Python.html
==> Summary
🍺  /usr/local/Cellar/python3/3.6.0_1: 3,602 files, 55.8MB
```

**Comment by ilovezfs** [comment]
@sashkab we've removed universal options from all formulae. If you still want to build with universal, you'll need to create a tap, and pluck the older versions of the formulae, before universal was removed, out of the git history, and copy them into the tap.

See https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap

**Comment by sashkab** [comment]
@ilovezfs -- I didn't find the reason *why* you deleted them. Is there insight into that? I certainly will add required packages to my tap.

**Comment by tdsmith** [comment]
The conversation at https://github.com/Homebrew/homebrew-core/pull/9641#issuecomment-280746019 describes the decision.

**Comment by sashkab** [comment]
@tdsmith thank you for pointing me into the right direction -- that answered most of my questions.
