### ISSUE TITLE
Missing <gmp.h> when building GCC plugin on M1 but not on x86_64

### ISSUE THREAD

**Issue by boris-kolpackov** [Homebrew/homebrew-core#106393]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config

HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 10d8aa664b63f589816de0ebc0edea1c0691da4e
Core tap last commit: 8 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

```
% brew info gcc

gcc: stable 11.3.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/opt/homebrew/Cellar/gcc/11.3.0_2 (1,403 files, 246.7MB) *
  Poured from bottle on 2022-07-22 at 11:47:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0-or-later with GCC-exception-3.1
==> Dependencies
Required: gmp ✔, isl ✔, libmpc ✔, mpfr ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am attempting to build a GCC plugin (it is part of the ODB compiler project). The same steps work without any errors on x86_64.

### What happened (include all command output)?

When I try to compile the ODB project I get errors like this:

```
opt/homebrew/Cellar/gcc/11.3.0_2/lib/gcc/11/gcc/aarch64-apple-darwin21/11/plugin/include/system.h:698:10: fatal error: gmp.h: No such file or directory
  698 | #include <gmp.h>
```

The same code using the same GCC version builds without errors on x86_64.

I also looked around and saw that `gmp.h` is located in `/opt/homebrew/Cellar/gmp/6.2.1_1/include/`:

```
% find /opt/homebrew/Cellar -name gmp.h
/opt/homebrew/Cellar/gmp/6.2.1_1/include/gmp.h
```

If I add `-I/opt/homebrew/Cellar/gmp/6.2.1_1/include` to ODB compilation command lines, then the build succeeds and plugin works.

### What did you expect to happen?

I expected the build to work out of the box, like it does on x86_64.  

I did a bit of investigating and I see that on x86_64, the `gmp.h` header is also installed into `/usr/local/include` which I guess how GCC finds it. Not sure what is the solution for M1. Maybe copy this (and any other gmp headers that it needs) into the GCC plugin directory?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# The only brew command involved was installing GCC 11.3:

brew install gcc
```

**Comment by carlocab** [comment]
You can also just do
```
-I/opt/homebrew/include
```
or
```
-I/opt/homebrew/opt/gmp/include
```
so you don't have paths that change whenever GMP's version changes.

More generally, it's probably a good idea to treat `Cellar` paths as an implementation detail that does not exist. You should use `/opt/homebrew/{bin,lib,include,share,etc}` or `/opt/homebrew/opt/*` instead.

**Comment by boris-kolpackov** [comment]
Hm, yes, I can see there is the `/opt/homebrew/include/gmp.h` symlink.

Am I correct in my understanding that for ARM Homebrew switched from `/usr/local/` to `/opt/homebrew/` and that what used to be `/usr/local/include/` is now `/opt/homebrew/include/`? Excuse my ignorance if this is documented somewhere...

**Comment by boris-kolpackov** [comment]
Ok, I think I understand the issue which can basically be summed up as: "On M1 Homebrew changed the header/library location from `/usr/local/{include,lib}` to `/opt/homebrew/{include,lib}` and it is now the user's responsibility to manually arrange for the compiler (either Clang from CLT or GCC from Homebrew) to use them as header/library search paths".
