### ISSUE TITLE
SDL2 --head inreplace step fails because of an SDL2 code change

### ISSUE THREAD

**Issue by DominusExult** [Homebrew/homebrew-core#106354]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs sdl2       
Error: `brew gist-logs` requires HOMEBREW_GITHUB_API_TOKEN to be set!

brew config
HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6183f8d007af2c39df875fe119ce9aac1539febb
Core tap last commit: 18 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 20-core 64-bit skylake
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10-config
  /Library/Frameworks/Python.framework/Versions/3.10/bin/python3-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libCAPSImage.dylib
  /usr/local/lib/libdvdcss.2.dylib
  /usr/local/lib/libglide2x.dylib
  /usr/local/lib/libz.1.2.12.dylib

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libexult.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libexult.a
  /usr/local/lib/libz.a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install the head of SDL2 because I needed current SDL2 code

### What happened (include all command output)?

brew install sdl2 --head
==> Downloading https://ghcr.io/v2/homebrew/core/m4/manifests/1.4.19
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/m4/blobs/sha256:8a17c921e5135206c382fc67ae53ba8835684dac5bfe7eb2bcdfa79df4d2731d
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:8a17c921e5135206c382fc67ae53ba8835684dac5bfe7eb2bcdfa79df4d2731d?se=2022-07-21T20%3A30%3A00Z&sig=F92%2B98m
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/manifests/2.71
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf/blobs/sha256:de8f4aa4123d307ad8bb11b1c685538224dc39939085fd00af928c5099c4202d
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:de8f4aa4123d307ad8bb11b1c685538224dc39939085fd00af928c5099c4202d?se=2022-07-21T20%3A30%3A00Z&sig=zQIoe%2Bf
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/automake/manifests/1.16.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/automake/blobs/sha256:ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:ae77a247a13ea860236a29b02769f5327395f712413f694d8a8d20cb6c21332d?se=2022-07-21T20%3A30%3A00Z&sig=7t18xgK0e
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtool/manifests/2.4.7
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libtool/blobs/sha256:33bf8379256791a8e8752541bf4e182090dcef5f73aa8faa5f6521d16414a6ca
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:33bf8379256791a8e8752541bf4e182090dcef5f73aa8faa5f6521d16414a6ca?se=2022-07-21T20%3A30%3A00Z&sig=Vyk9KHCl8
######################################################################## 100.0%
==> Cloning https://github.com/libsdl-org/SDL.git
Cloning into '/Users/Dominus/Library/Caches/Homebrew/sdl2--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
==> Installing dependencies for sdl2: m4, autoconf, automake and libtool
==> Installing sdl2 dependency: m4
==> Pouring m4--1.4.19.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/m4/1.4.19: 13 files, 740.8KB
==> Installing sdl2 dependency: autoconf
==> Pouring autoconf--2.71.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/autoconf/2.71: 71 files, 3.2MB
==> Installing sdl2 dependency: automake
==> Pouring automake--1.16.5.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.16.5: 131 files, 3.5MB
==> Installing sdl2 dependency: libtool
==> Pouring libtool--2.4.7.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/libtool/2.4.7: 75 files, 3.8MB
==> Installing sdl2 --HEAD
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
sdl2-config.in:
  expected replacement of "@prefix@" with #<Pathname:/usr/local>

### What did you expect to happen?

that brew installs the head of SDL2.

the problem is that SDL2 git removed the @prefix@ to replace in sdl2-config.in - see https://github.com/libsdl-org/SDL/commit/799d39a3022415f698cb92f44b872c8513d83249

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install sdl2 --head
```

**Comment by SMillerDev** [comment]
We don't provide support for head builds.

**Comment by DominusExult** [comment]
Then why not remove this from the formula altogether?
You have it in there and it's not working.

**Comment by gromgit** [comment]
> Then why not remove this from the formula altogether?

`head` blocks generally exist only because a _user_ added it, not a maintainer. Removing that `head` block tends to upset every user who relies on HEAD...like you.

Users are expected to fix HEAD builds themselves as and when they break, because HEAD is _unstable_ by definition. Continuously testing HEAD builds on all formulae that have a `head` block is an absurd waste of resources, especially with thousands of _stable_ builds that need building and babysitting.

So if you need a HEAD build _right now_, the onus is on you (or someone else who also needs the HEAD build _right now_) to figure out what changed, and fix the build accordingly...for _right now_.

Because tomorrow, there may be another upstream change that breaks your fix today. That's the downside of relying on HEAD.

**Comment by ylluminate** [comment]
Please see suggestion: https://github.com/Homebrew/homebrew-core/issues/106810#issuecomment-1198923030
