### ISSUE TITLE
`brew install clang` fails to find clang formulae inside of doozer builds.

### ISSUE THREAD

**Issue by AraHaan** [Homebrew/homebrew-core#10657]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step? (does not apply to doozer as I cannot use brew without the homebrew part of ``.doozer.json``)
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? (does not apply to doozer as I cannot use brew without the homebrew part of ``.doozer.json``)
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor` or if reporting a formula issue include the link from:
`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build). Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

Because Doozer does not allow me to use brew directly nor does it let me install it for use directly I cannot do those commands. I have no idea why it cannot find clang nor does it let me tell it to tap from here if it is not tapping from here already. All I know is something is wrong here. it works with gcc 6.3 however when I try to invoke gcc with g++6 it does not work well at all for me on the compile of my c++ 14 project. However when I try to use clang in the CI it does this. I am absolutely clueless as to why this is.

**Comment by DomT4** [comment]
There is no `clang` formula, or alias. You're looking for `brew install llvm`.

```
ls /usr/local/opt/llvm/bin | grep clang

clang
clang++
clang-3.9
clang-apply-replacements
clang-check
clang-cl
clang-format
clang-include-fixer
clang-query
clang-rename
clang-tblgen
clang-tidy
git-clang-format
```

**Comment by AraHaan** [comment]
oh

**Comment by AraHaan** [comment]
what about clang++-3.9?

**Comment by MikeMcQuaid** [comment]
There's no enough information here to help you.

**Comment by AraHaan** [comment]
Well then, What do I do with the missing header then? Can I somehow homebrew that in too for gcc and clang?

**Comment by MikeMcQuaid** [comment]
I still have no idea what you're asking.

To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)
