### ISSUE TITLE
Brew GCC compile on 10.11.4

### ISSUE THREAD

**Issue by JDeanThomas** [Homebrew/homebrew-core#1068]
Recently switched to 10.11.4 from 10.9.5

GCC installed fine from binary before (never compiled), installs fine after on 10.11.4, after clearing cache, but not from source.

Cleared Cache, turned off SIP, reinstalled everything, still throws an error.

(Installing the pours works fine. Same error after brew uninstall. compile with clang or built in GCC. Nothing works)

```
Jasons-MBP:~ jasonthomas$ brew reinstall GCC --all-languages --cc=clang
==> Reinstalling gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc-5.3.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
patching file gcc/jit/jit-playback.c
Hunk #1 succeeded at 2470 with fuzz 2 (offset 54 lines).
==> ../configure --build=x86_64-apple-darwin15.4.0 --prefix=/usr/local/Cellar/gcc/5.3.0 
==> make bootstrap
Last 15 lines from /Users/jasonthomas/Library/Logs/Homebrew/gcc/02.make:
checking for a BSD-compatible install... /usr/bin/install -c
checking for gawk... awk
checking for x86_64-apple-darwin15.4.0-ar... ar
checking for x86_64-apple-darwin15.4.0-lipo... lipo
checking for x86_64-apple-darwin15.4.0-nm... /private/tmp/gcc-20160511-95198-oz60w3/gcc-5.3.0/build/./gcc/nm
checking for x86_64-apple-darwin15.4.0-ranlib... ranlib
checking for x86_64-apple-darwin15.4.0-strip... strip
checking whether ln -s works... yes
checking for x86_64-apple-darwin15.4.0-gcc... /private/tmp/gcc-20160511-95198-oz60w3/gcc-5.3.0/build/./gcc/xgcc -B/private/tmp/gcc-20160511-95198-oz60w3/gcc-5.3.0/build/./gcc/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/bin/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/lib/ -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/include -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/sys-include   
checking for suffix of object files... configure: error: in `/private/tmp/gcc-20160511-95198-oz60w3/gcc-5.3.0/build/x86_64-apple-darwin15.4.0/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [configure-stage1-target-libgcc] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2
```

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ilovezfs** [comment]
>turned off SIP

please don't do that as a troubleshooting step

**Comment by ilovezfs** [comment]
@JDeanThomas Did you get this resolved? I was not able to reproduce the issue. If I had to guess, your Xcode or command line tools are outdated. The output requested by mikemcquaid above would be helpful.

Also, but not the cause: `--cc=clang` is unnecessary and the option is `--with-all-languages` not `--all-languages`

**Comment by JDeanThomas** [comment]
Sorry, was late at night.

I had followed all of the procedures in the troubleshooting guide. I updated Homebrew (and just repeated all steps, which I was trying to avoid as now the R formula has been updated from 3.2.5 to 3.3.0 now and I need a specific compile of R for OpenMx), folder permissions for /usr/local are correct  and CLT are up to date.

Here is the output

https://gist.github.com/anonymous/2dedbb6268442de2c32580766424ec82

Jason

**Comment by ilovezfs** [comment]
@JDeanThomas Please try installing Xcode.app from MAS and see if it changes the outcome.

**Comment by JDeanThomas** [comment]
@ilovezfs tried that right after reposting. Downloaded the .DMG for CLT 7.3.1 from Apple Developer and tried to recompile. Same error.

My suspicion is that this is a bug in 7.3.1.

**Comment by JDeanThomas** [comment]
@ilovezfs I removed CLT 7.3.1

$ sudo rm -rf /Library/Developer/CommandLineTools

and reinstalled 7.3 using .DMG from Apple Developer. Same error.

https://gist.github.com/f45d2b9658c244ae3021dd4ca4ad64fa

Jason

**Comment by ilovezfs** [comment]
I don't think it's 7.3.1 causing this.
```
🍺  /usr/local/Cellar/gcc/5.3.0: 1,390 files, 254.5M, built in 22 minutes 34 seconds
iMac-TMP:install joe$ brew config |grep 'CLT\|Xcode'
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
```

**Comment by UniqMartin** [comment]
@JDeanThomas From your build logs:

```
dyld: Library not loaded: /usr/local/lib/libmpc.3.dylib
  Referenced from: /private/tmp/gcc-20160511-26652-aqb5ge/gcc-5.3.0/build/./gcc/cc1
  Reason: image not found
```

Can you try removing and then reinstalling `libmpc`? This seems to be similar to the issue in #234.

> reinstalled everything

What do you mean by that? Did you really start off with an empty Homebrew installation?

**Comment by JDeanThomas** [comment]
@UniqMartin Good. Catch. I have no idea how that got removed from /usr/local/lib unless it occurred during upgrade from 10.9 to 10.11, but that could have been problematic elsewhere to say the least.

$ brew search libmpc
homebrew/versions/libmpc08 ✔             libmpc ✔                               
$ which libmpc
$ brew reinstall libmpc
==> Reinstalling libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3.el_capitan.bott
######################################################################## 100.0%
==> Pouring libmpc-1.0.3.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3: 11 files, 350.1K
$ 

That fixed the issue.

Thanks for the help!
