### ISSUE TITLE
offlineimap fails to import PySocks

### ISSUE THREAD

**Issue by adam8157** [Homebrew/homebrew-core#107023]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs offlineimap
Error: No logs.

$ brew config
HOMEBREW_VERSION: 3.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0b030b74e2ac518bd0bc4158f96c449198f9957f
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 03fbf3a604dd766c96e56ae80d15399acbd2b489
Core tap last commit: 78 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run offlineimap with proxy settings, which depends on `PySocks` module.

### What happened (include all command output)?

$ offlineimap -o
PySocks not installed, ignoring proxy option.

$ pip3 install pysocks
Requirement already satisfied: pysocks in /opt/homebrew/lib/python3.9/site-packages (1.7.1)

$ pip
pip     pip3    pip3.9

### What did you expect to happen?

offlineimap with proxy settings run successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The RCA is clear, `offlineimap` depends on `python@3.10`, but homebrew's default `python` is `python3.9`, so it installs `python@3.10` in offlineimap's own directory and for itself only.

I need to do `/opt/homebrew/Cellar/offlineimap/8.0.0_1/libexec/bin/pip3.10 install pysocks` to fix it.

This is a user experience problem, I'm not sure what is a good solution.

Submit an issue for others with the same issue to search.
```

**Comment by adam8157** [comment]
`/opt/homebrew/Cellar/offlineimap/8.0.0_1/libexec/bin/pip3.10 install pysocks` to fix it.

**Comment by carlocab** [comment]
Does doing
```
/opt/homebrew/opt/python@3.10/bin/pip3 install pysocks
```
help? You'll need to uninstall the PySocks you installed inside `offlineimap` to check this properly.

**Comment by adam8157** [comment]
> /opt/homebrew/opt/python@3.10/bin/pip3 install pysocks

It works too.

However `/opt/homebrew/opt/python@3.10/bin/pip3` or `/opt/homebrew/opt/python@3.10/bin/pip3.10` are not exposed explicitly.

**Comment by carlocab** [comment]
> However `/opt/homebrew/opt/python@3.10/bin/pip3` or `/opt/homebrew/opt/python@3.10/bin/pip3.10` are not exposed explicitly.

It is now. You can do
```
pip3 install pysocks
```
If that doesn't work:
```
brew update && brew upgrade
```
We'll review a pull request that adds `pysocks` to the `offlineimap` formula so that this doesn't need to be done manually.
