### ISSUE TITLE
sdl2_image: Fail to configure CMake projects.

### ISSUE THREAD

**Issue by FtZPetruska** [Homebrew/homebrew-core#107491]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

`brew config` output:

```
HOMEBREW_VERSION: 3.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: ff9c2500195cc357d4a06f99d462f8d8a5d37892
Last commit: 35 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3e46ad9edd0fd3f2bc4ea428e52c70bd67c82967
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.vu6teljo4Y/org.xquartz:0
HOMEBREW_EDITOR: /Users/ganyu/.zsh/code-wait
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

`brew doctor` output: `Your system is ready to brew.`

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to compile a small CMake project using SDL2 and SDL2_image.

Both libraries were freshly installed from homebrew:
- SDL2 version 2.0.22
- SDL2_image version 2.6.0_1

### What happened (include all command output)?

The configuration step of CMake fails due to invalid include directory.

Command output:
```
% cmake -S. -Bbuild
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "SDL2_image::SDL2_image" includes non-existent path

    "//include/SDL2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in CMakeLists.txt:
  Imported target "SDL2_image::SDL2_image" includes non-existent path

    "//include/SDL2"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### What did you expect to happen?

The configure step should succeed.

I could confirm that the issue is most likely related to homebrew's packaging as compiling SDL2_image 2.6.0 from source using the same configuration option as the formula results in a correct installation.

### Step-by-step reproduction instructions (by running `brew` commands)

- Install the build dependencies: `brew install sdl2 sdl2_image cmake`

- Create a sample project

Example CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.15)
project(example VERSION 0.1.0 LANGUAGES C)

add_executable(program main.c)

find_package(SDL2 CONFIG REQUIRED)
find_package(SDL2_image CONFIG REQUIRED)

target_link_libraries(program PRIVATE SDL2::SDL2main SDL2::SDL2 SDL2_image::SDL2_image)
```

Example main.c:

```c
int main() {}
```

- Run the configure step: `cmake -S. -Bbuild`

**Comment by cho-m** [comment]
Current generated `sdl2_image-config.cmake` looks like:
```cmake
get_filename_component(prefix "${CMAKE_CURRENT_LIST_DIR}../../../../../../../../.." ABSOLUTE)
...
set(includedir "${prefix}/include")
...
set(_sdl2image_incdir   "${includedir}/SDL2")
```

Probably need to look into generation of first line

**Comment by FtZPetruska** [comment]
Thank you for your feedback!

After testing, I was able to confirm that using the `--HEAD` commit fixes the issue. I also noticed on a project using SDL2_ttf that this issue also affects the `sdl2_ttf` formula, but also gets resolved using the `--HEAD` option during install.

Lastly, `sdl2_mixer` seems unaffected.

**Comment by carlocab** [comment]
It seems this is an upstream issue then. My guess is that if you build the same version from source without using `brew`, you would encounter the same problem.

**Comment by cho-m** [comment]
Following PR links ends up at upstream sdl2_ttf issue https://github.com/libsdl-org/SDL_ttf/issues/237

The best we can do is backport commits until upstream does new release

**Comment by FtZPetruska** [comment]
The patches have been added into a release! Here are the related PRs:
- #108466 
- #108467
