### ISSUE TITLE
odin is missing vendor directory

### ISSUE THREAD

**Issue by msal4** [Homebrew/homebrew-core#107602]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Syntax Error: Path does not exist:
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

odin build .

### What happened (include all command output)?

Syntax Error: Path does not exist:

### What did you expect to happen?

build successfull

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The fix is very simple we just need to add "vendor" to https://github.com/Homebrew/homebrew-core/blob/43fd4443dda4f1bc23ff7c3c0e41fa1c2b7b5991/Formula/odin.rb#L32
```

**Comment by SMillerDev** [comment]
If you know what to change please create a pull request

**Comment by carlocab** [comment]
Just to warn you: the `vendor` directory contains pre-built binaries that we are unlikely to be willing to ship unless they are built from source in the formula.

**Comment by mhmdanas** [comment]
@carlocab where are these binaries? I couldn't find them.
