### ISSUE TITLE
OpenShift CLI installed via "brew install openshift-cli" is stuck on version 4.2, latest version is 4.11

### ISSUE THREAD

**Issue by jmdelros** [Homebrew/homebrew-core#107682]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: (none)
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
http_proxy: **********
https_proxy: *********
no_proxy: ************
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: N/A
Git: N/A
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-x86_64
CLT: N/A
Xcode: N/A

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: You have the following deprecated, cask taps tapped:
  caskroom/fonts
  caskroom/versions
Untap them with `brew untap`.

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your user.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: Git could not be found in your PATH.
Homebrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git

Warning: No developer tools installed.
Install the Command Line Tools:
  xcode-select --install


Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/docker/cli-plugins
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install openshift-cli

### What happened (include all command output)?

After brew install openshift-cli.. running the command "oc version" showed below

Client Version: v4.2.0-alpha.0-1420-gf1f09a3

### What did you expect to happen?

"oc version" command needs to show

Client Version: v4.11.0

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openshift-cli

oc version
```

**Comment by gromgit** [comment]
>```
>HOMEBREW_VERSION: >=2.5.0 (shallow or no git repository)
>ORIGIN: (none)
>HEAD: (none)
>Last commit: never
>Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
>Core tap HEAD: (none)
>Core tap last commit: never
>Core tap branch: (none)
>```

Your Homebrew installation is unbelievably old, considering that `brew doctor` didn't complain about an improper core tap.

Run `brew update-reset`, then `brew config` again. If `brew config` gives you essentially the same results as above, you should probably re-run the Homebrew installer from scratch: https://brew.sh

**Comment by jmdelros** [comment]
I was able to update to the latest version of homebrew and re-installed openshift-cli, still getting the same error for "oc version"

HOMEBREW_VERSION: 3.5.8-35-g9382160
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9382160be6fe69206981f93a2da9055575d3cded
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9fa0b0f845f80b8910fb5341244edd206bce9737
Core tap last commit: 41 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12

**Comment by SMillerDev** [comment]
What does `brew info openshift-cli` say now?

**Comment by jmdelros** [comment]
Here's what I get..

╰─ brew info openshift-cli
openshift-cli: stable 4.11.0-202204020828 (bottled), HEAD
OpenShift command-line interface tools
https://www.openshift.com/
/usr/local/Cellar/openshift-cli/4.11.0-202204020828 (7 files, 104.1MB) *
  Poured from bottle on 2022-08-10 at 11:43:37
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openshift-cli.rb
License: Apache-2.0
==> Dependencies
Build: coreutils ✘, go@1.17 ✘
Required: socat ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 2,399 (30 days), 8,034 (90 days), 24,770 (365 days)
install-on-request: 2,397 (30 days), 8,022 (90 days), 24,694 (365 days)
build-error: 0 (30 days)

**Comment by gromgit** [comment]
This looks like an upstream issue, nothing that Homebrew can do about it: https://github.com/openshift/oc/issues/1210
