### ISSUE TITLE
runing `brew services start  docker` errors

### ISSUE THREAD

**Issue by ConanEdogawa1** [Homebrew/homebrew-core#107774]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Error: Formula `docker` has not implemented #plist, #service or installed a locatable service file 

ls -al /usr/local/opt/docker
lrwxr-xr-x  1 conan  admin  25  8 11 10:48 /usr/local/opt/docker -> ../Cellar/docker/20.10.17
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Start docker on boot

### What happened (include all command output)?

Error: Formula `docker` has not implemented #plist, #service or installed a locatable service file

### What did you expect to happen?

docker starts normally

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install docker 

brew services start docker 
output:Error: Formula `docker` has not implemented #plist, #service or installed a locatable service file
```

**Comment by carlocab** [comment]
The output of `brew config` and `brew doctor` is required from all bug reports to Homebrew.

**Comment by ConanEdogawa1** [comment]
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.


Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.8/greenlet/greenlet.h

**Comment by ConanEdogawa1** [comment]
HOMEBREW_VERSION: 3.5.9
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b90a54785f98ed4da3a566eefcb9e57ecd2806de
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.7-x86_64
CLT: 12.5.0.22.9
Xcode: N/A

**Comment by gromgit** [comment]
OK, the error message is literally correct:
```
Error: Formula `docker` has not implemented #plist, #service or installed a locatable service file
```
The `docker` formula has none of the above, since it's not a service to be managed, just like (say) the `go` compiler:
```
$ brew services start go
Error: Formula `go` has not implemented #plist, #service or installed a locatable service file
```
