### ISSUE TITLE
`man_db.conf` should be patched to use the formula's `#var` instead of `/var`

### ISSUE THREAD

**Issue by d125q** [Homebrew/homebrew-core#107805]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

No logs, formula installs successfully.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `gmandb` to update the man database.

### What happened (include all command output)?

```console
% gmandb
gmandb: warning: $MANPATH set, appending /usr/local/etc/man_db.conf
Processing manual pages under /usr/share/man...
gmandb: can't update index cache /var/cache/man/6836: No such file or directory
gmandb: warning: cannot create catdir /var/cache/man
gmandb: can't create index cache /var/cache/man/6836: No such file or directory
exit 2
```

### What did you expect to happen?

I expected the man database to be updated.

Looking at the default `man_db.conf`, there are the following entries for cat paths:

```text
#               *MANPATH*     ->        *CATPATH*
#
MANDB_MAP       /usr/man                /var/cache/man/fsstnd
MANDB_MAP       /usr/share/man          /var/cache/man
MANDB_MAP       /usr/local/man          /var/cache/man/oldlocal
MANDB_MAP       /usr/local/share/man    /var/cache/man/local
MANDB_MAP       /usr/X11R6/man          /var/cache/man/X11R6
MANDB_MAP       /opt/man                /var/cache/man/opt
MANDB_MAP       /snap/man               /var/cache/man/snap
```

Replacing `/var` by `$HOMEBREW_PREFIX/var` makes everything work correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew install man-db
% gmandb
```

**Comment by carlocab** [comment]
`man_db.conf` lives in `etc`, so you're free to make any change that you please, and `brew` will not overwrite it.

Any new `man_db.conf` will be installed as `man_db.conf.default` to avoid overwriting your existing `man_db.conf`.

This also means that if we change the `man_db.conf` that we install to use `$HOMEBREW_PREFIX/var`, that will still be installed for you as `man_db.conf.default` (unless you delete your existing `man_db.conf` before reinstalling `man-db`).

**Comment by carlocab** [comment]
I've opened #107806 to change this, but you'll need to do
```
brew update && brew reinstall man-db
mv "$(brew --prefix)/etc/man_db.conf.default" "$(brew --prefix)/etc/man_db.conf"
```
once that PR is merged. (Or you can skip doing any of that, since you've already amended your `man_db.conf` to what you need it to be.)
