### ISSUE TITLE
brew test fails with NoMethodError

### ISSUE THREAD

**Issue by Oleksii-Svintsitskyi** [Homebrew/homebrew-core#108095]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/dbc9ea17aa4a4e7957d8dbb9442910fb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew test <formula>

### What happened (include all command output)?

company@Alekseis-MBP ~ % brew test pyobjc
==> Testing oleksii-svintsitskyi/tap/pyobjc
Error: oleksii-svintsitskyi/tap/pyobjc: failed
An exception occurred within a child process:
  NoMethodError: undefined method `captures' for nil:NilClass
Did you mean?  capture_stderr
/usr/local/Homebrew/Library/Taps/oleksii-svintsitskyi/homebrew-tap/Formula/pyobjc.rb:13:in `python'
/usr/local/Homebrew/Library/Taps/oleksii-svintsitskyi/homebrew-tap/Formula/pyobjc.rb:57:in `block in <class:Pyobjc>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2256:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2255:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:935:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2254:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2531:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2248:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:48:in `<main>'

### What did you expect to happen?

company@Alekseis-MBP ~ % brew test pyobjc
==> Testing pyobjc
==> /usr/local/opt/python@3.10/libexec/bin/python -c import objc; print(objc.__version__)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap Oleksii-Svintsitskyi/homebrew-tap
brew install pyobjc
brew test pyobjc
```

**Comment by carlocab** [comment]
This is an issue with the `pyobjc` formula in https://github.com/Oleksii-Svintsitskyi/homebrew-tap.

Please don't file issues here about formulae that are not in this repository.
