### ISSUE TITLE
minimal-racket 8.6's raco has outdated catalog URL

### ISSUE THREAD

**Issue by lintwaddle** [Homebrew/homebrew-core#108284]
### `brew config` output

```shell
HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 108d7e02caa7564cd8995d0d69721c181fefba3e
Core tap last commit: 35 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 14.0.0.0.1.1659797938
Xcode: 14.0 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false
```

### `brew doctor` output

```shell
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

After installing `minimal-racket`, I was trying to install `drracket` through `raco`. It reported a version mismatch, trying to install packages for 8.5, rather than 8.6. Looking at `raco`'s config, it has the old catalog version:

```
[~]$ raco pkg config
name:
  8.6
catalogs:
  https://download.racket-lang.org/releases/8.5/catalog/
  https://pkgs.racket-lang.org
  https://planet-compats.racket-lang.org
default-scope:
  installation
download-cache-dir:
  /Users/blaketregre/Library/Caches/Racket/download-cache
download-cache-max-files:
  1024
download-cache-max-bytes:
  134217728
git-checkout-credentials:
trash-max-packages:
  512
trash-max-seconds:
  172800
network-retries:
  5
  ```

The correct catalog version is available through the cask `homebrew/cask/racket`. Thank you for taking a look.

### What happened (include all command output)?

[raco-install-output.txt](https://github.com/Homebrew/brew/files/9364409/raco-install-output.txt)

### What did you expect to happen?

Cleanly install `drracket`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install minimal-racket
raco pkg install --auto drracket
```
```

**Comment by carlocab** [comment]
That's strange since the `raco-install-output.txt` references the Cellar path to `8.5`:
```
raco setup: pkgs paths:
raco setup:   /opt/homebrew/Cellar/minimal-racket/8.5/share/racket/pkgs
```

What's the output of `ls -la /opt/homebrew/Cellar/minimal-racket`?

**Comment by lintwaddle** [comment]
```
[~]$ ls -la /opt/homebrew/Cellar/minimal-racket
total 0
drwxr-xr-x    3 user  admin    96 Aug 17 09:11 .
drwxrwxr-x  170 user  admin  5440 Aug 17 09:10 ..
drwxr-xr-x   10 user  admin   320 Aug 17 09:11 8.6
```

but after trying to install `drracket`
```
total 0
drwxr-xr-x    4 user  admin   128 Aug 17 09:21 .
drwxrwxr-x  170 user  admin  5440 Aug 17 09:10 ..
drwxr-xr-x    4 user  admin   128 Aug 17 09:22 8.5
drwxr-xr-x   10 user  admin   320 Aug 17 09:11 8.6
```

**Comment by lintwaddle** [comment]
Originally, I upgraded from 8.5 to 8.6. I did not have `drracket` installed. I only installed it after upgrading. Is it possible there is some old config file in a dusty corner of my disk messing things up?

**Comment by carlocab** [comment]
> Is it possible there is some old config file in a dusty corner of my disk messing things up?

Yes, that seems the likeliest explanation to me.

**Comment by lintwaddle** [comment]
> Yes, that seems the likeliest explanation to me.
Any ideas on where to look?

**Comment by lintwaddle** [comment]
Ok, I tried installing `minimal-racket` on a machine that didn't have 8.5. It gets the correct catalog path, so there is an error upgrading `minimal-racket`.

**Comment by carlocab** [comment]
> Any ideas on where to look?

Nope, sorry. I don't use `minimal-racket` so I have no idea. I think @gromgit might.

**Comment by cho-m** [comment]
Can you check for `etc` files that Homebrew won't replace on updates?
```
ls /opt/homebrew/etc/racket
cat /opt/homebrew/etc/racket/*
```

**Comment by carlocab** [comment]
> Can you check for `etc` files that Homebrew won't replace on updates?
> 
> ```
> ls /opt/homebrew/etc/racket
> cat /opt/homebrew/etc/racket/*
> ```

That looks like it.

**Comment by lintwaddle** [comment]
Yep, that's it. `config.rktd` has the old version in it.

**Comment by lintwaddle** [comment]
Thanks, y'all.

**Comment by carlocab** [comment]
You can run
```
brew update && brew postinstall minimal-racket
```
to avoid having a `config.rktd` that references old versions of `minimal-racket`.
