### ISSUE TITLE
CMocka *.cmake files not exposed in current brew installation

### ISSUE THREAD

**Issue by heckj** [Homebrew/homebrew-core#108287]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew gist-logs cmocka`:

Error: No logs.
```

`brew config`:
```
HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 108d7e02caa7564cd8995d0d69721c181fefba3e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.1BHHtSWkCW/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 14.0 => /Applications/Xcode-beta5.app/Contents/Developer
Rosetta 2: false
```

`brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/heckj/miniforge3/bin/krb5-config
  /Users/heckj/miniforge3/bin/python3.9-config
  /Users/heckj/miniforge3/bin/python3-config
  /Users/heckj/miniforge3/bin/curl-config
  /Users/heckj/miniforge3/bin/ncursesw6-config
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was installing CMocka to use within a CMake project (Automerge) for unit testing C APIs. After debugging with the Automerge team, they identified that the *.cmake files from CMocka weren't getting picked up by Homebrew's CMake.

We worked around it by adding environment variables which do a bit of redirection:
```
export CMAKE_PREFIX_PATH=/opt/homebrew
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```

The cmocka-config.cmake file may need to have the following two lines inserted into it: `include_directories("/opt/homebrew/include")` and `link_directories("/opt/homebrew/lib")`

I wasn't entirely sure if that was something for Homebrew to support, or if this should be routed upstream to CMocka itself. 

### What happened (include all command output)?

Without the additions, the Automerge build failed to find the cmocka.h headers (needed to run unit tests):
```
   Compiling uuid v0.8.2
   Compiling automerge v0.1.0 (/Users/heckj/src/automerge/automerge-rs/automerge)
   Compiling automerge-c v0.1.0 (/Users/heckj/src/automerge/automerge-rs/automerge-c)
    Finished release [optimized + debuginfo] target(s) in 22.13s
[ 16%] Built target automerge_artifacts
[ 33%] Building C object test/CMakeFiles/test_automerge.dir/group_state.c.o
[ 50%] Building C object test/CMakeFiles/test_automerge.dir/amlistset_tests.c.o
/Users/heckj/src/automerge/automerge-rs/automerge-c/test/amlistset_tests.c:10:10: fatal error: 'cmocka.h' file not found
#include <cmocka.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [test/CMakeFiles/test_automerge.dir/amlistset_tests.c.o] Error 1
make[1]: *** [test/CMakeFiles/test_automerge.dir/all] Error 2
make: *** [all] Error 2
```

### What did you expect to happen?

The build to complete, with the CMocka headers found appropriately, and used in the unit tests

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install cmake
brew install cmocka
git clone https://github.com/automerge/automerge-rs.git
cd automerge-rs
cd automerge-c
mkdir -p build
cd build
cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
## building and testing
$ cmake --build . --target test_automerge
```

**Comment by carlocab** [comment]
Does it work if you set `CMAKE_PREFIX_PATH=/opt/homebrew` without setting `CPATH` and `LIBRARY_PATH`?

If not, then this may be due to an extra `../` in `lib/cmake/cmocka-config.cmake`:

```cmake
# cmocka-config.cmake

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)

[snip]

if (EXISTS "${CMOCKA_CMAKE_DIR}/CMakeCache.txt")
    # In build tree
    include(${CMOCKA_CMAKE_DIR}/cmocka-build-tree-settings.cmake)
else()
    set(CMOCKA_INCLUDE_DIR ${PACKAGE_PREFIX_DIR}/include)
endif()

set(CMOCKA_LIBRARY ${PACKAGE_PREFIX_DIR}/lib/libcmocka.dylib)
set(CMOCKA_LIBRARIES ${PACKAGE_PREFIX_DIR}/lib/libcmocka.dylib)
```

It seems to be traversing one directory upwards too far.

**Comment by heckj** [comment]
I just gave that flow a work-through, and received the `cmocka.h` not found error:

```bash
export CMAKE_PREFIX_PATH=/opt/homebrew
git clone https://github.com/automerge/automerge-rs.git
cd automerge-rs/automerge-c
rm -rf build
mkdir -p build
cd build
cmake -S .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
  cmake --build . --target test_automerge
```

Final result:
```
[  7%] Built target automerge_artifacts
[ 14%] Building C object test/CMakeFiles/test_automerge.dir/actor_id_tests.c.o
/Users/heckj/src/automergeC/automerge-rs/automerge-c/test/actor_id_tests.c:10:10: fatal error: 'cmocka.h' file not found
#include <cmocka.h>
         ^~~~~~~~~~
1 error generated.
make[3]: *** [test/CMakeFiles/test_automerge.dir/actor_id_tests.c.o] Error 1
make[2]: *** [test/CMakeFiles/test_automerge.dir/all] Error 2
make[1]: *** [test/CMakeFiles/test_automerge.dir/rule] Error 2
make: *** [test_automerge] Error 2
```

I went ahead and checked to see if that would make the difference by manually tweaking the `cmocka-config.cmake` file to remove one of those `../`, but even with that in place (and the `CMAKE_PREFIX_PATH=/opt/homebrew`), it's not finding the cmocka.h header.

**Comment by cho-m** [comment]
Right now, `automerge-rs` doesn't try to use detected paths, so it fails if they are not part of default system search directories or passed in via input/env variables.

One option is to update [`automerge-c/test/CMakeLists.txt`](https://github.com/automerge/automerge-rs/blob/main/automerge-c/test/CMakeLists.txt) so that it uses detected `CMOCKA_INCLUDE_DIR` and `CMOCKA_LIBRARY`. Just passing these values to `target_include_directories` and `target_link_libraries` should fix issue.

I don't think there is anything wrong with `cmocka`. Issue seen is just how `automerge-rs` build scripts are written, so behavior is expected when using non-`/usr/local` prefix (e.g. `/opt/homebrew`).
