### ISSUE TITLE
Some packages install python@3.10 if they depend on it, others don't

### ISSUE THREAD

**Issue by Oleksii-Svintsitskyi** [Homebrew/homebrew-core#108264]

**Comment by Oleksii-Svintsitskyi** [comment]
@bayandin actually found something that I do not completely understand in this context.
Why then when I'm creating my own formula with without any additional resources and use
```
depends_on "python@3.10" => [:build, :test] 
depends_on "python@3.8" => [:build, :test]
depends_on "python@3.9" => [:build, :test]

def pythons
  deps.map(&:to_formula).sort_by(&:version)
end
  
def install
  pythons.each do |python|
    python_exe = python.opt_libexec/"bin/python"
    system python_exe, *Language::Python.setup_install_args(prefix, python)
end
```
just like in `six` package, by Formula install all the python versions that is depends on?
Maybe this situation might have another explanation?

**Comment by carlocab** [comment]
You are building your formula from source, so you need the `:build` dependencies to install it. Formulae in homebrew-core have bottles (pre-compiled artefacts), so there is no need to install the `:build` dependencies to install them.

**Comment by Oleksii-Svintsitskyi** [comment]
@carlocab thank you al ot!
