### ISSUE TITLE
MacVim and Vim use different versions of Ruby

### ISSUE THREAD

**Issue by shadowhand** [Homebrew/homebrew-core#10824]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug

MacVim is linking itself to system version of Ruby. Vim links itself to Homebrew Ruby. This causes any Vim plugin (such as [Command-T](https://github.com/wincent/Command-T)) to be usable in either MacVim *or* Vim, but not both.

**Comment by MikeMcQuaid** [comment]
We don't consider this a bug, sorry.

**Comment by shadowhand** [comment]
@MikeMcQuaid can you explain why?

**Comment by MikeMcQuaid** [comment]
`vim` uses `depends_on :ruby` and MacVim does not. By default both will link against the system Ruby. `vim` provides an option to not do so or will not do so if building from source and MacVim does not. This is expected behaviour and I'd sooner remove the option from `vim` than add it to MacVim.

**Comment by MikeMcQuaid** [comment]
Also on https://github.com/macvim-dev/macvim/issues/468 pretty sure it's not an upstream bug as if you use the `--enable-rubyinterp` I suspect it'll work. As you're building from source anyway you could maintain a custom formula fork with this change.

**Comment by shadowhand** [comment]
@MikeMcQuaid 

> By default both will link against the system Ruby. 

I don't believe this is an accurate statement, as [vim formula](https://github.com/Homebrew/homebrew-core/blob/5d2d43ce5b534f4b209e1b35fa63b1db71326090/Formula/vim.rb#L26) clearly [states it will default to Homebrew Ruby](https://github.com/Homebrew/homebrew-core/blob/5d2d43ce5b534f4b209e1b35fa63b1db71326090/Formula/vim.rb#L98-L99).

Why have different defaults for two similar packages?

**Comment by MikeMcQuaid** [comment]
> I don't believe this is an accurate statement, as vim formula clearly states it will default to Homebrew Ruby.

By "default" means "you're using /usr/local and the binary package".

> Why have different defaults for two similar packages?

Regardless of the past reasons: I've stated my reasons for why it's not considered a bug.

**Comment by shadowhand** [comment]
@MikeMcQuaid 

> if you use the `--enable-rubyinterp` I suspect it'll work.

The MacVim formula [already uses this option](https://github.com/Homebrew/homebrew-core/blob/5d2d43ce5b534f4b209e1b35fa63b1db71326090/Formula/macvim.rb#L47).

**Comment by MikeMcQuaid** [comment]
> The MacVim formula already uses this option and is linked to system Ruby.

That's because we filter your PATH. Have you tried building it from source outside of Homebrew? I'd suggest doing that to confirm that https://github.com/macvim-dev/macvim/issues/468 is valid.

**Comment by shadowhand** [comment]
No, I have no built outside of Homebrew. I did try a build from source, and it still linked against system Ruby, despite Homebrew Ruby being installed.

This is an extremely frustrating situation, because I switch between MacVim and Vim regularly. Any plugin that depends on Ruby will simply not work in one or the other, forcing me to recompile the plugin before I can continue to work.

It seems like either:

1. `vim` formula should **not** default to using Homebrew Ruby unless `--with-homebrew-ruby` is used (an option that does not exist right now)
2. `macvim` formula should be modified to ensure that it defaults to Homebrew Ruby, in order to be consistent with `vim` formula

Package builds are not my area of expertise, so I am at a loss as to how to solve this myself. 😕

**Comment by MikeMcQuaid** [comment]
> No, I have no built outside of Homebrew.

Upstream will ask you to do that.

> Package builds are not my area of expertise, so I am at a loss as to how to solve this myself.

We'll need a few more people to chime in here before we make a change, I'm afraid.

I'd suggest using the default Homebrew installation location on a supported version of macOS may be a solution for this problem for you.

**Comment by ilovezfs** [comment]
If you
```
brew install vim --with-custom-ruby
```
won't it use the system ruby and just stick with it when upgrading?

**Comment by CarterLi** [comment]
After some investigations, I found that I must add ruby dependency explicitly or `./configure` can't find brewed ruby
Same as brewed perl

```ruby
depends_on :ruby => "1.8"
```
works, copied from `vim.rb`

**Comment by sethfowler** [comment]
Looking forward to seeing this fixed. I have a similar issue with using both Neovim and MacVim on the same machine.

**Comment by shadowhand** [comment]
I believe the issue has been fixed upstream but is waiting on a release.

**Comment by thefonso** [comment]
@CarterLi you are trying to solve the problem i have been plagued with for years ( brew ruby working in vim but not macvim) . Has this been released yet?
