### ISSUE TITLE
brew complains about `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by xsteadfastx** [Homebrew/homebrew-core#108342]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew doctor
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/bin/clang)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/../lib/libLLVM-14.so)
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libquvi
  quvi

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/marv/.asdf/shims/freetype-config
  /home/marv/.asdf/shims/xml2-config
  /home/marv/.asdf/shims/python3.9-config
  /home/marv/.asdf/shims/python-config
  /home/marv/.asdf/shims/python3-config
  /home/marv/.asdf/shims/xslt-config
  /home/marv/.asdf/shims/curl-config
  /home/marv/.asdf/shims/icu-config
  /home/marv/.asdf/shims/krb5-config
  /home/marv/.asdf/shims/pcre-config
  /home/marv/.asdf/shims/libpng-config
  /home/marv/.asdf/shims/ncursesw6-config
  /home/marv/.asdf/shims/libpng16-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  elfutils
  speedtest

Warning: Some installed formulae are not readable:
  salamander: wrong number of arguments (given 1, expected 0)

  fortlit: wrong number of arguments (given 1, expected 0)

```
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

i get errors on all brew commands about `GLIBCXX_3.4.29' not found. 



### What happened (include all command output)?

```
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/bin/clang)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/.
./lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/.
./lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/.
./lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/..
/lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/..
/lib/libclang-cpp.so.14)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/.
./lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/.
./lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/.
./lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/..
/lib/libLLVM-14.so)
/home/linuxbrew/.linuxbrew/bin/clang: /home/linuxbrew/.linuxbrew/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/linuxbrew/.linuxbrew/Cellar/llvm/14.0.6_1/bin/..
/lib/libLLVM-14.so)
```

### What did you expect to happen?

that the errors are not there.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
running any brew command
```

**Comment by carlocab** [comment]
Try `brew reinstall llvm`.

**Comment by xsteadfastx** [comment]
that helped but i cant understand it. often my box wants to llvm compile itselt and then this error occurs. now it just used a bottle one and the errors are gone.

**Comment by carlocab** [comment]
Yes, this was broken by a recent GCC update. That was our fault, and we haven't quite worked out the best way to make the required fix (`brew reinstall llvm`) as seamless as possible.

Sorry for the inconvenience!
