### ISSUE TITLE
audit --online failures

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#10839]
- [x] libtextcat: 
  * Stable: The URL http://software.wise-guys.nl/download/libtextcat-2.2.tar.gz is not reachable (HTTP status code 500)
- [x] man2html:
  * Stable: The URL http://dcssrv1.oit.uci.edu/indiv/ehood/tar/man2html3.0.1.tar.gz is not reachable
- [x] pce:
  * Devel: The URL http://www.hampa.ch/pub/pce/pre/pce-20160308-72f1e10.tar.gz is not reachable (HTTP status code 404)
- [x] pianod: (https://github.com/Homebrew/homebrew-core/pull/11634)
  * Devel: The URL http://deviousfish.com/Downloads/pianod2/Devel/pianod2-189.tar.gz is not reachable (HTTP status code 404)
- [x] polipo:
  * HEAD: The URL git://git.wifi.pps.jussieu.fr/polipo is not a valid git URL
- [ ] qt@5.5:
  * xcodebuild should be passed an explicit "SYMROOT"
- [x] riak:
  * Commented-out dep "openssl"
- [x] schroedinger:
  * Stable: The URL http://diracvideo.org/download/schroedinger/schroedinger-1.0.11.tar.gz is not reachable
- [x] spidermonkey:
  * HEAD: The URL https://hg.mozilla.org/tracemonkey/archive/tip.tar.gz is not reachable (HTTP status code 404)
- [x] webarchiver:
  * xcodebuild should be passed an explicit "SYMROOT"
- [ ] xctool:
  * xcodebuild should be passed an explicit "SYMROOT"
---
- [x] bigdata: (https://github.com/Homebrew/homebrew-core/pull/10929)
  * Stable: The URL https://downloads.sourceforge.net/project/bigdata/bigdata/1.5.3/bigdata-bundled.jar is not reachable (HTTP status code 404)
- [x] boom-completion: (https://github.com/Homebrew/homebrew-core/pull/10938)
  * The URL http://zachholman.com/boom could use HTTPS rather than HTTP
- [x] boost@1.59: (https://github.com/Homebrew/homebrew-core/pull/10939)
  * The URL http://www.boost.org could use HTTPS rather than HTTP
- [x] cabocha: (https://github.com/Homebrew/homebrew-core/pull/10942)
  * Stable: The URL https://googledrive.com/host/0B4y35FiV1wh7cGRCUUJHVTNJRnM/cabocha-0.69.tar.bz2 is not reachable (HTTP status code 404)
- [x] chordii: (https://github.com/Homebrew/homebrew-core/pull/10944)
  * The URL http://www.vromans.org/johan/projects/Chordii/ could use HTTPS rather than HTTP
- [x] clang-format: (https://github.com/Homebrew/homebrew-core/pull/10945)
  * The URL http://clang.llvm.org/docs/ClangFormat.html could use HTTPS rather than HTTP
- [x] clhep: (https://github.com/Homebrew/homebrew-core/pull/10946)
  * HEAD: The URL http://git.cern.ch/pub/CLHEP is not a valid git URL
- [x] clockywock: (https://github.com/Homebrew/homebrew-core/pull/10948)
  * Stable: The URL http://soomka.com/clockywock-0.3.1a.tar.gz could use HTTPS rather than HTTP
  * The URL http://soomka.com/ could use HTTPS rather than HTTP
- [x] compface: (https://github.com/Homebrew/homebrew-core/pull/10949)
  * Stable: The URL http://ftp.xemacs.org/pub/xemacs/aux/compface-1.5.2.tar.gz is not reachable (HTTP status code 404)
- [x] csv-fix: (https://github.com/Homebrew/homebrew-core/pull/10950)
  * The URL http://neilb.bitbucket.org/csvfix/ could use HTTPS rather than HTTP
- [x] dcmtk: (https://github.com/Homebrew/homebrew-core/pull/10803)
  * Stable: The URL http://dicom.offis.de/download/dcmtk/snapshot/dcmtk-3.6.1_20161102.tar.gz is not reachable (HTTP status code 404)
- [x] debianutils: (https://github.com/Homebrew/homebrew-core/pull/10932)
  * Stable: The URL https://mirrors.ocf.berkeley.edu/debian/pool/main/d/debianutils/debianutils_4.8.tar.xz is not reachable (HTTP status code 404)
- [x] ecasound: (https://github.com/Homebrew/homebrew-core/pull/10954)
  * Stable: The URL http://ecasound.seul.org/download/ecasound-2.9.1.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.eca.cx/ecasound/ could use HTTPS rather than HTTP
- [x] enchant: (https://github.com/Homebrew/homebrew-core/pull/10955)
  * Stable: The URL http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.abisource.com/projects/enchant/ could use HTTPS rather than HTTP
- [x] etl: (https://github.com/Homebrew/homebrew-core/pull/10956)
  * The URL http://synfig.org could use HTTPS rather than HTTP
- [x] fabric-completion: (https://github.com/Homebrew/homebrew-core/pull/10958)
  * HEAD: The URL https://raw.githubusercontent.com/kbakulin/fabric-completion.git is not a valid git URL
- [x] fbida: (https://github.com/Homebrew/homebrew-core/pull/10959)
  * Stable: The URL http://dl.bytesex.org/releases/fbida/fbida-2.10.tar.gz could use HTTPS rather than HTTP
  * The URL http://linux.bytesex.org/fbida/ could use HTTPS rather than HTTP
- [x] fcgi: (https://github.com/Homebrew/homebrew-core/pull/10960)
  * Stable: The URL https://ftp.ucsb.edu/pub/mirrors/linux/gentoo/distfiles/fcgi-2.4.0.tar.gz is not reachable (HTTP status code 404)
- [x] flawfinder: (https://github.com/Homebrew/homebrew-core/pull/10825)
  * Stable: The URL http://www.dwheeler.com/flawfinder/flawfinder-1.31.tar.gz could use HTTPS rather than HTTP
  * Stable resource "flaws": The URL http://www.dwheeler.com/flawfinder/test.c could use HTTPS rather than HTTP
  * HEAD resource "flaws": The URL http://www.dwheeler.com/flawfinder/test.c could use HTTPS rather than HTTP
  * The URL http://www.dwheeler.com/flawfinder/ could use HTTPS rather than HTTP
- [x] flvstreamer: (https://github.com/Homebrew/homebrew-core/pull/10961)
  * Stable: The URL https://download.savannah.gnu.org/releases-noredirect/flvstreamer/source/flvstreamer-2.1c1.tar.gz is not reachable (HTTP status code 404)
- [x] freealut: (https://github.com/Homebrew/homebrew-core/pull/10987)
  * Stable: The URL http://connect.creativelabs.com/openal/Downloads/ALUT/freealut-1.1.0.tar.gz is not reachable
- [x] fs-uae: (https://github.com/Homebrew/homebrew-core/pull/10990)
  * The URL http://fs-uae.net/ could use HTTPS rather than HTTP
- [x] fsevents-tools: (https://github.com/Homebrew/homebrew-core/pull/10991)
  * Stable: The URL http://geoff.greer.fm/fsevents/releases/fsevents-tools-1.0.0.tar.gz could use HTTPS rather than HTTP
  * The URL http://geoff.greer.fm/fsevents/ could use HTTPS rather than HTTP
- [x] gauge: (https://github.com/Homebrew/homebrew-core/pull/10966)
  * The URL http://getgauge.io could use HTTPS rather than HTTP
- [x] gmp@4: (https://github.com/Homebrew/homebrew-core/pull/10992)
  * The URL http://gmplib.org/ could use HTTPS rather than HTTP
- [x] grunt-completion: (https://github.com/Homebrew/homebrew-core/pull/10993)
  * The URL http://gruntjs.com/ could use HTTPS rather than HTTP
- [x] gtk+: (https://github.com/Homebrew/homebrew-core/pull/10994)
  * The URL http://gtk.org/ could use HTTPS rather than HTTP
- [x] gtk-doc: (https://github.com/Homebrew/homebrew-core/pull/10995)
  * The URL http://www.gtk.org/gtk-doc/ could use HTTPS rather than HTTP
- [x] gwenhywfar: (https://github.com/Homebrew/homebrew-core/pull/10996)
  * HEAD: The URL http://git.aqbanking.de/git/gwenhywfar.git is not a valid git URL
- [x] hardlink: (https://github.com/Homebrew/homebrew-core/pull/10999)
  * Stable: The URL http://jak-linux.org/projects/hardlink/hardlink_0.3.0.tar.xz could use HTTPS rather than HTTP
  * The URL http://jak-linux.org/projects/hardlink/ could use HTTPS rather than HTTP
- [x] imake: (https://github.com/Homebrew/homebrew-core/pull/11001)
  * The URL http://xorg.freedesktop.org could use HTTPS rather than HTTP
- [x] imapsync: (https://github.com/Homebrew/homebrew-core/pull/11002)
  * HEAD: The URL https://git.fedorahosted.org/git/imapsync.git is not a valid git URL
- [x] iphotoexport: (https://github.com/Homebrew/homebrew-core/pull/10853)
  * Stable: The URL https://iphotoexport.googlecode.com/files/iphotoexport-1.6.4.zip is not reachable (HTTP status code 404)
- [x] jailkit: (https://github.com/Homebrew/homebrew-core/pull/11004)
  * Stable: The URL http://olivier.sessink.nl/jailkit/jailkit-2.19.tar.bz2 could use HTTPS rather than HTTP
  * The URL http://olivier.sessink.nl/jailkit/ could use HTTPS rather than HTTP
- [x] jbig2dec: (https://github.com/Homebrew/homebrew-core/pull/11005)
  * The URL http://ghostscript.com/jbig2dec.html could use HTTPS rather than HTTP
- [x] jpcsp: (https://github.com/Homebrew/homebrew-core/pull/11006)
  * The URL http://jpcsp.org/ could use HTTPS rather than HTTP
- [x] lasi: (https://github.com/Homebrew/homebrew-core/pull/11007)
  * The URL http://www.unifont.org/lasi/ could use HTTPS rather than HTTP
- [x] legit: (https://github.com/Homebrew/homebrew-core/pull/11008)
  * The URL http://www.git-legit.org/ could use HTTPS rather than HTTP
- [x] libarchive: (https://github.com/Homebrew/homebrew-core/pull/10888)
  * Stable: The URL http://www.libarchive.org/downloads/libarchive-3.3.0.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.libarchive.org could use HTTPS rather than HTTP
- [x] libcdr: (https://github.com/Homebrew/homebrew-core/pull/11012)
  * Stable: The URL http://dev-www.libreoffice.org/src/libcdr/libcdr-0.1.3.tar.xz could use HTTPS rather than HTTP
- [x] libetonyek: (https://github.com/Homebrew/homebrew-core/pull/11013)
  * Stable: The URL http://dev-www.libreoffice.org/src/libetonyek/libetonyek-0.1.6.tar.xz could use HTTPS rather than HTTP
- [x] libforensic1394: (https://github.com/Homebrew/homebrew-core/pull/11014)
  * HEAD: The URL git://git.freddie.witherden.org/forensic1394.git is not a valid git URL
- [x] libfreehand: (https://github.com/Homebrew/homebrew-core/pull/11016)
  * Stable: The URL http://dev-www.libreoffice.org/src/libfreehand/libfreehand-0.1.1.tar.xz could use HTTPS rather than HTTP
- [x] libident: (https://github.com/Homebrew/homebrew-core/pull/11127)
  * Stable: The URL http://www.remlab.net/files/libident/libident-0.32.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.remlab.net/libident/ could use HTTPS rather than HTTP
- [x] liblas: (https://github.com/Homebrew/homebrew-core/pull/11126)
  * The URL http://liblas.org could use HTTPS rather than HTTP
- [x] liblwgeom: (https://github.com/Homebrew/homebrew-core/pull/11172)
  * The URL http://postgis.net could use HTTPS rather than HTTP
- [x] libmspub: (https://github.com/Homebrew/homebrew-core/pull/11125)
  * Stable: The URL http://dev-www.libreoffice.org/src/libmspub/libmspub-0.1.2.tar.xz could use HTTPS rather than HTTP
- [x] libodfgen: (https://github.com/Homebrew/homebrew-core/pull/11124)
  * Stable: The URL http://dev-www.libreoffice.org/src/libodfgen-0.1.6.tar.bz2 could use HTTPS rather than HTTP
- [x] libpagemaker: (https://github.com/Homebrew/homebrew-core/pull/11123)
  * Stable: The URL http://dev-www.libreoffice.org/src/libpagemaker/libpagemaker-0.0.3.tar.xz could use HTTPS rather than HTTP
- [x] librevenge: (https://github.com/Homebrew/homebrew-core/pull/11122)
  * Stable: The URL http://dev-www.libreoffice.org/src/librevenge-0.0.4.tar.bz2 could use HTTPS rather than HTTP
- [x] libvisio: (https://github.com/Homebrew/homebrew-core/pull/11121)
  * Stable: The URL http://dev-www.libreoffice.org/src/libvisio/libvisio-0.1.5.tar.xz could use HTTPS rather than HTTP
- [x] libwpd: (https://github.com/Homebrew/homebrew-core/pull/11120)
  * Stable: The URL http://dev-www.libreoffice.org/src/libwpd-0.10.1.tar.bz2 could use HTTPS rather than HTTP
- [x] libwpg: (https://github.com/Homebrew/homebrew-core/pull/11128)
  * Stable: The URL http://dev-www.libreoffice.org/src/libwpg-0.3.1.tar.bz2 could use HTTPS rather than HTTP
- [x] libwps: (https://github.com/Homebrew/homebrew-core/pull/11129)
  * Stable: The URL http://dev-www.libreoffice.org/src/libwps-0.4.2.tar.bz2 could use HTTPS rather than HTTP
- [x] mac-robber: (https://github.com/Homebrew/homebrew-core/pull/11171)
  * The URL http://www.sleuthkit.org/mac-robber/ could use HTTPS rather than HTTP
- [x] mailutils: (https://github.com/Homebrew/homebrew-core/pull/10901)
  * The URL http://mailutils.org/ could use HTTPS rather than HTTP
- [x] mapcrafter: (https://github.com/Homebrew/homebrew-core/pull/11170)
  * The URL http://mapcrafter.org could use HTTPS rather than HTTP
- [x] mesalib-glw: (https://github.com/Homebrew/homebrew-core/pull/11169)
  * The URL http://www.mesa3d.org could use HTTPS rather than HTTP
- [x] mysql-sandbox: (https://github.com/Homebrew/homebrew-core/pull/11168)
  * The URL http://mysqlsandbox.net could use HTTPS rather than HTTP
- [x] mysql@5.5: (https://github.com/Homebrew/homebrew-core/pull/11101)
  * The URL http://dev.mysql.com/doc/refman/5.5/en/ could use HTTPS rather than HTTP
- [x] nim: (https://github.com/Homebrew/homebrew-core/pull/11167)
  * Stable: The URL http://nim-lang.org/download/nim-0.16.0.tar.xz could use HTTPS rather than HTTP
  * The URL http://nim-lang.org/ could use HTTPS rather than HTTP
- [x] open-tyrian: (https://github.com/Homebrew/homebrew-core/pull/11166)
  * Stable resource "data": The URL http://camanis.net/tyrian/tyrian21.zip could use HTTPS rather than HTTP
  * HEAD resource "data": The URL http://camanis.net/tyrian/tyrian21.zip could use HTTPS rather than HTTP
- [x] openmsx: (https://github.com/Homebrew/homebrew-core/pull/11165)
  * The URL http://openmsx.org/ could use HTTPS rather than HTTP
- [x] openrtsp: (#10971)
  * Stable: The URL http://www.live555.com/liveMedia/public/live.2016.11.28.tar.gz is not reachable (HTTP status code 404)
- [x] openttd: (https://github.com/Homebrew/homebrew-core/pull/10963)
  * Stable: The URL http://binaries.openttd.org/releases/1.6.1/openttd-1.6.1-source.tar.xz could use HTTPS rather than HTTP
- [x] pdal: (https://github.com/Homebrew/homebrew-core/pull/11164)
  * The URL http://www.pdal.io/ could use HTTPS rather than HTTP
- [x] pgpdump: (https://github.com/Homebrew/homebrew-core/pull/11163)
  * The URL http://www.mew.org/~kazu/proj/pgpdump/en/ could use HTTPS rather than HTTP
- [x] phoronix-test-suite: (https://github.com/Homebrew/homebrew-core/pull/11162)
  * Stable: The URL http://www.phoronix-test-suite.com/download.php?file=phoronix-test-suite-5.2.1 could use HTTPS rather than HTTP
  * The URL http://www.phoronix-test-suite.com/ could use HTTPS rather than HTTP
- [x] postgis: (https://github.com/Homebrew/homebrew-core/pull/11161)
  * The URL http://postgis.net could use HTTPS rather than HTTP
- [x] ppsspp: (https://github.com/Homebrew/homebrew-core/pull/11160)
  * The URL http://ppsspp.org/ could use HTTPS rather than HTTP
- [x] pypy: (https://github.com/Homebrew/homebrew-core/pull/10933)
  * The URL http://pypy.org/ could use HTTPS rather than HTTP
- [x] pypy3: (https://github.com/Homebrew/homebrew-core/pull/10933)
  * The URL http://pypy.org/ could use HTTPS rather than HTTP
- [x] pytouhou: (https://github.com/Homebrew/homebrew-core/pull/11159)
  * The URL http://pytouhou.linkmauve.fr/ could use HTTPS rather than HTTP
- [x] qcachegrind: (https://github.com/Homebrew/homebrew-core/pull/11158)
  * Stable: The URL http://download.kde.org/stable/applications/16.12.0/src/kcachegrind-16.12.0.tar.xz could use HTTPS rather than HTTP
- [x] quex: (https://github.com/Homebrew/homebrew-core/pull/10886)
  * Stable: The URL https://downloads.sourceforge.net/project/quex/DOWNLOAD/quex-0.65.11.zip is not reachable (HTTP status code 404)
- [x] radare2: (https://github.com/Homebrew/homebrew-core/pull/11157)
  * The URL http://radare.org could use HTTPS rather than HTTP
- [x] raine: (https://github.com/Homebrew/homebrew-core/pull/10973)
  * The URL http://raine.1emulation.com/ could use HTTPS rather than HTTP
- [x] redis: (https://github.com/Homebrew/homebrew-core/pull/10559)
  * The URL http://redis.io/ could use HTTPS rather than HTTP
- [x] s-lang: (https://github.com/Homebrew/homebrew-core/pull/11201)
  * Stable: The URL http://www.jedsoft.org/releases/slang/slang-2.3.0.tar.bz2 is not reachable (HTTP status code 404)
- [x] sfml: (https://github.com/Homebrew/homebrew-core/pull/11156)
  * Stable: The URL http://www.sfml-dev.org/files/SFML-2.4.2-sources.zip could use HTTPS rather than HTTP
  * The URL http://www.sfml-dev.org/ could use HTTPS rather than HTTP
- [x] sleuthkit: (https://github.com/Homebrew/homebrew-core/pull/11155)
  * The URL http://www.sleuthkit.org/ could use HTTPS rather than HTTP
- [x] sloccount: (https://github.com/Homebrew/homebrew-core/pull/11154)
  * Stable: The URL http://www.dwheeler.com/sloccount/sloccount-2.26.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.dwheeler.com/sloccount/ could use HTTPS rather than HTTP
- [x] slrn: (https://github.com/Homebrew/homebrew-core/pull/11242)
  * Stable: The URL http://jedsoft.org/releases/slrn/slrn-1.0.2.tar.bz2 is not reachable (HTTP status code 404)
- [x] spandsp: (https://github.com/Homebrew/homebrew-core/pull/11173)
  * Stable: The URL http://www.soft-switch.org/downloads/spandsp/spandsp-0.0.6.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.soft-switch.org/ could use HTTPS rather than HTTP
- [x] speex: (https://github.com/Homebrew/homebrew-core/pull/11174)
  * The URL http://speex.org could use HTTPS rather than HTTP
- [x] synfig: (https://github.com/Homebrew/homebrew-core/pull/10843)
  * The URL http://synfig.org could use HTTPS rather than HTTP
- [x] t-completion: (#10974)
  * The URL http://sferik.github.com/t could use HTTPS rather than HTTP
- [x] taisei: (#10975)
  * The URL http://taisei-project.org/ could use HTTPS rather than HTTP
- [x] tal: (https://github.com/Homebrew/homebrew-core/pull/11015)
  * Stable: The URL http://thomasjensen.com/software/tal/tal-1.9.tar.gz could use HTTPS rather than HTTP
  * The URL http://thomasjensen.com/software/tal/ could use HTTPS rather than HTTP
- [x] temporal_tables:  (https://github.com/Homebrew/homebrew-core/pull/11003)
  * The URL http://pgxn.org/dist/temporal_tables/ could use HTTPS rather than HTTP
- [x] terminator:  (https://github.com/Homebrew/homebrew-core/pull/11003)
  * The URL http://gnometerminator.blogspot.com/p/introduction.html could use HTTPS rather than HTTP
- [x] tofrodos: (https://github.com/Homebrew/homebrew-core/pull/11003)
  * The URL http://www.thefreecountry.com/tofrodos/ could use HTTPS rather than HTTP
- [x] twoping: (https://github.com/Homebrew/homebrew-core/pull/11017)
  * Stable: The URL http://www.finnie.org/software/2ping/2ping-3.2.1.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.finnie.org/software/2ping/ could use HTTPS rather than HTTP
- [x] uni2ascii: (https://github.com/Homebrew/homebrew-core/pull/11011)
  * The URL http://billposer.org/Software/uni2ascii.html could use HTTPS rather than HTTP
- [x] vmdktool: (https://github.com/Homebrew/homebrew-core/pull/11130)
  * The URL http://manned.org/vmdktool could use HTTPS rather than HTTP
- [x] webfs: (https://github.com/Homebrew/homebrew-core/pull/11010)
  * The URL http://linux.bytesex.org/misc/webfs.html could use HTTPS rather than HTTP
- [x] wesnoth: (https://github.com/Homebrew/homebrew-core/pull/11009)
  * The URL http://www.wesnoth.org/ could use HTTPS rather than HTTP
- [x] wv: (https://github.com/Homebrew/homebrew-core/pull/11000)
  * Stable: The URL http://abisource.com/downloads/wv/1.2.9/wv-1.2.9.tar.gz could use HTTPS rather than HTTP
- [x] xpa: (https://github.com/Homebrew/homebrew-core/pull/10997)
  * The URL http://hea-www.harvard.edu/RD/xpa/ could use HTTPS rather than HTTP

**Comment by Numbermaniac** [comment]
Looking at the very first one, latest version of `bigdata` appears to be [2.1.4](https://sourceforge.net/projects/bigdata/files/bigdata/2.1.4/), but none of them match the filename "bigdata-bundled.jar".

**Comment by ilovezfs** [comment]
Half-way there!

**Comment by neutric** [comment]
🔥

**Comment by miguelarauj1o** [comment]
@ilovezfs, _mailutils_ already use HTTPS at homepage.

**Comment by neutric** [comment]
Entered all up to and including qcachegrind into the list.

**Comment by Numbermaniac** [comment]
slrn fixed in #11242

**Comment by ilovezfs** [comment]
@Numbermaniac thanks for the heads up!

**Comment by ilovezfs** [comment]
I've updated the list, and floated the remaining 11 to the top. Thank you very much to everyone who has helped so far.

**Comment by fxcoudert** [comment]
Re. `libtextcat`: I've emailed the maintainers to warn them about the website issue.

**Comment by fxcoudert** [comment]
`qt@5.5` and `xctool` are false positives from the audit: https://github.com/Homebrew/brew/pull/2199#issuecomment-287768076

**Comment by ilovezfs** [comment]
Maybe just edit the comment in some way to shut it up?

**Comment by ilovezfs** [comment]
For libtextcat we can use a mirror

https://ftp.heanet.ie/mirrors/OpenBSD/distfiles/libtextcat-2.2.tar.gz
https://www.jabawok.net/gentoo/distfiles/128cfc86ed5953e57fe0f5ae98b62c2e-libtextcat-2.2.tar.gz
http://pkgs.fedoraproject.org/repo/pkgs/libtextcat/libtextcat-2.2.tar.gz/md5/128cfc86ed5953e57fe0f5ae98b62c2e/libtextcat-2.2.tar.gz

**Comment by ilovezfs** [comment]
Thanks to everyone who helped here! Onward to https://github.com/Homebrew/homebrew-core/issues/11865.

**Comment by ilovezfs** [comment]
Also https://github.com/Homebrew/homebrew-core/issues/11869.
