### ISSUE TITLE
gdb installation does not work on Mac M1 machines.

### ISSUE THREAD

**Issue by aditya-solana** [Homebrew/homebrew-core#108309]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output
```
$ brew config
HOMEBREW_VERSION: 3.5.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3748bed378401ed75abdf32bcb3d2674d854a6f9
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 108d7e02caa7564cd8995d0d69721c181fefba3e
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

$ brew doctor
Your system is ready to brew.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installing gdb on M1

### What happened (include all command output)?

$ brew install gdb
gdb: The x86_64 architecture is required for this software.
Error: gdb: An unsatisfied requirement failed this build.

### What did you expect to happen?

gdb should get installed on my machine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install gdb
gdb: The x86_64 architecture is required for this software.
Error: gdb: An unsatisfied requirement failed this build.
```

**Comment by aditya-solana** [comment]
someone claimed to have made it work (https://gist.github.com/mike-myers-tob/9a6013124bad7ff074d3297db2c98247) so i created an issue here.

**Comment by carlocab** [comment]
Nope, I don't think anyone claims to have made it work on M1 macOS there. If anything, I've seen several comments saying it _doesn't_ work.

**Comment by gromgit** [comment]
> someone claimed to have made it work (https://gist.github.com/mike-myers-tob/9a6013124bad7ff074d3297db2c98247) so i created an issue here.

You misread. The entire thread was basically about getting GDB to work on _Intel_ macOS, which was broken since at least Mojave (so predating M1).
