### ISSUE TITLE
opencascade current build, bottle or from source causes a crash within freecad

### ISSUE THREAD

**Issue by ipatch** [Homebrew/homebrew-core#108395]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

there is a cmake option for opencascade that is required to prevent freecad from crashing basically any and all versions of freecad will crash unless opencascade is compiled with the below cmake flag,

```
-D BUILD_RELEASE_DISABLE_EXCEPTIONS=OFF
```

any chance y'all would be open to adding that flag in the cmake configure options for opencascade.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

use freecad surface workbench, but unfortunately opencascade causes it to crash.

### What happened (include all command output)?

na

### What did you expect to happen?

not experience a crash.

### Step-by-step reproduction instructions (by running `brew` commands)

install freecad via 

```
brew install --cask freecad/freecad/freecad
```

this issue appears to not effect the below install of freecad from the homebrew-cask tap because that version is built using conda and with this definition file for building opencascade,

https://github.com/conda-forge/occt-feedstock/blob/429f53c9bcc1fc8c1ef00d31875d284b6b6b692f/recipe/build.sh#L9

```
brew install --cask freecad
```

---

below is a link to the upstream freecad issue,

https://github.com/FreeCAD/FreeCAD/issues/6200

and a separate issue with a video demoing the steps to reproduce the crash.

https://github.com/FreeCAD/homebrew-freecad/issues/318

**Comment by SMillerDev** [comment]
This should be a discussion between freecad and opencascade to change the opencascade defaults. Homebrew only distributes opencascade.

**Comment by carlocab** [comment]
We probably shouldn't be distributing broken software either, especially if it can be fixed with a simple config toggle. (But probably not if it requires heavy 3rd-party patching.)

**Comment by SMillerDev** [comment]
If it's broken that's all the more reason for upstream to change the default.

**Comment by carlocab** [comment]
I imagine they can be persuaded to do so. @ipatch, has this been reported to opencascade?

**Comment by ipatch** [comment]
https://github.com/FreeCAD/FreeCAD/issues/6200#issuecomment-1221012643
