### ISSUE TITLE
`brew install zoxide` does not install manpages

### ISSUE THREAD

**Issue by ajeetdsouza** [Homebrew/homebrew-core#108485]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```text
HOMEBREW_VERSION: 3.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88a5fac96752f17280e64f60926f58dff45990e0
Last commit: 7 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abcdf885805f8240313a103ee8391d0fc9ac8e0f
Core tap last commit: 6 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.0 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

---

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/ajeetdsouza/.cargo/bin/cargo-install-update-config
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

zoxide bundles some manpages (`man/man1/*.1`) into its releases, but Homebrew doesn't seem to be installing them.

### What happened (include all command output)?

Not applicable

### What did you expect to happen?

Not applicable

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install zoxide
man zoxide # not found
man zoxide-init # not found
```

**Comment by carlocab** [comment]
We require the output of `brew config` and `brew doctor` for all bug reports to this repository, applicable or not.

We can reopen this once you've provided the requested information. Alternatively, feel free to open a pull request that resolves this.

**Comment by ajeetdsouza** [comment]
@carlocab I've added the missing information, could you reopen?

**Comment by carlocab** [comment]
Is this issue about completions (as in the issue title) or manpages (as in the issue body)? Or both?

**Comment by ajeetdsouza** [comment]
Sorry, I meant manpages. I fixed the issue title.

**Comment by carlocab** [comment]
I've opened #108501. When that's merged, users who are looking for manpages can do `brew update && brew reinstall zoxide`.
