### ISSUE TITLE
Macvim wont install via brew on Sierra 

### ISSUE THREAD

**Issue by lisakpuglisi** [Homebrew/homebrew-core#10869]
Hello,

Hitting a brick wall here cannot get macvim to install - I am very new to coding - just starting out with tutorials - however I can't even get the software installed! - feeling a bit silly here!!!

Lisas-Mac-mini:~ lisapuglisi$ brew install macvim
Updating Homebrew...
==> Installing dependencies for macvim: readline, sqlite, gdbm, openssl, python, cscope
==> Installing macvim dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-7.0.3.sierra.bottl

curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "readline"
Download failed: https://homebrew.bintray.com/bottles/readline-7.0.3.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://ftpmirror.gnu.org/readline/readline-7.0.tar.gz

curl: (28) Resolving timed out after 5563 milliseconds
Trying a mirror...
==> Downloading https://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz

curl: (6) Could not resolve host: ftp.gnu.org
Error: Failed to download resource "readline"
Download failed: https://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz

Also have had this error:

Lisas-Mac-mini:~ lisapuglisi$ brew install vim
Updating Homebrew...
==> Installing dependencies for vim: perl, readline, libyaml, openssl, ruby, sqlite, gdbm, python
==> Installing vim dependency: perl
==> Downloading https://homebrew.bintray.com/bottles/perl-5.24.1.sierra.bottle.t

curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "perl"
Download failed: https://homebrew.bintray.com/bottles/perl-5.24.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading http://www.cpan.org/src/5.0/perl-5.24.1.tar.xz

curl: (6) Could not resolve host: www.cpan.org
Error: Failed to download resource "perl"
Download failed: http://www.cpan.org/src/5.0/perl-5.24.1.tar.xz
Lisas-Mac-mini:~ lisapuglisi$ brew install perl
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/perl-5.24.1.sierra.bottle.t

curl: (6) Could not resolve host: homebrew.bintray.com
Error: Failed to download resource "perl"
Download failed: https://homebrew.bintray.com/bottles/perl-5.24.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading http://www.cpan.org/src/5.0/perl-5.24.1.tar.xz

curl: (6) Could not resolve host: www.cpan.org
Error: Failed to download resource "perl"
Download failed: http://www.cpan.org/src/5.0/perl-5.24.1.tar.xz

**Comment by JCount** [comment]
Have you checked your DNS configuration and flushed your DNS resolver cache? Also, are behind a proxy of some kind? What you are running into doesn't seem to be an issue directly related to brew per se, but more that you are unable to resolve the remote hosts that you need to. What it seems you need to do is determine if something is misconfigured in your network stack. You could also try switching to different DNS severs, such as Google's Public DNS at 8.8.8.8 and 8.8.4.4, as well.

**Comment by lisakpuglisi** [comment]
I'll check both of those thank you!!! Will let you know how I go!

**Comment by fxcoudert** [comment]
This looks like a network issue, which I hope you were able to fix. I am closing the issue for now, please reopen if the issue persists and you have additional information.
