### ISSUE TITLE
zsh-completion's instructions differ from Homebrew documentation

### ISSUE THREAD

**Issue by fterrag** [Homebrew/homebrew-core#108716]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
frank@MacBook-Pro ~ % brew config
HOMEBREW_VERSION: 3.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5731faf8be1ddc1eeae4b162b88bd76318fc279
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6355eba2f31ddc89e7932e70f39bdcf26312630e
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

frank@MacBook-Pro ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Enable autocompletion the `brew` command.

### What happened (include all command output)?

Running `brew install zsh-completions` outputs:

```
To activate these completions, add the following to your .zshrc:

  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi
```

Adding the above code to `.zshrc` (and following all of the post-install instructions) does not enable autocomplete for the `brew`.

### What did you expect to happen?

`brew [tab]` autocompletes with a list of brew's commands.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install zsh-completions
```

Add the following to `.zshrc` per the output:

```
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi
```

Notice autocomplete for the `brew` command does not work.

Visit https://docs.brew.sh/Shell-Completion and use the path from the Zsh instructions: `$(brew --prefix)/share/zsh/site-functions` and autocomplete for `brew` will become available.

Should both `$(brew --prefix)/share/zsh-completions` and `$(brew --prefix)/share/zsh/site-functions` appear in FPATH?

**Comment by fterrag** [comment]
Should both `$(brew --prefix)/share/zsh-completions` and `$(brew --prefix)/share/zsh/site-functions` appear in FPATH?

**Comment by SMillerDev** [comment]
The zsh completions formula and the homebrew completions are 2 separate things AFAIK so the documentation and the formula are both right.

**Comment by fterrag** [comment]
@SMillerDev ah, that would make sense! Thanks
