### ISSUE TITLE
I have managed to compile rtorrent.

### ISSUE THREAD

**Issue by rweichler** [Homebrew/homebrew-core#10882]
And it uses clang! :D

I have no idea how homebrew formulas work, nor do I know ruby, but I thought it would be worth posting this here for anyone that might want to make this into a formula. Maybe that will be future me.

**THIS IS KIND OF A HACK**. I am writing this for my own documentation. It is very late at night and I want to go to bed, so I'm writing this down before I forget it. I will amend it with better build instructions later.

So... what I did:

First, **I had a previous installation of libtorrent 0.13.6**, so when pkg-config asked for it, it thought it was installed. Just used to trick pkg-config, not used for the build.

Then, I installed these dependencies off of brew: curl, lzlib, libsigc++. There might be more that I already had installed.

Then, I ran this:

```
git clone git@github.com:rakshasa/rtorrent.git
git clone git@github.com:rakshasa/libtorrent.git

cd libtorrent
./autogen.sh
CC=clang CXX=clang++ CXXFLAGS="-Wno-deprecated-declarations -O3 -std=c++11 -stdlib=libc++" ./configure
make

cd ../rtorrent
./autogen.sh
CC=clang CXX=clang++ CXXFLAGS="-Wno-deprecated-declarations -O3 -std=c++11 -stdlib=libc++" ./configure
# shitty hack, force it to look for headers/libs in our freshly baked libtorrent.
# i probably wouldnt have to do this if i ran make install on libtorrent
find . -name Makefile -type f -print0 | xargs -0 sed -i '' 's~-I/usr/local/Cellar/libtorrent/0.13.6/include~-I'"$(pwd)"'/../libtorrent/src~g'
find . -name Makefile -type f -print0 | xargs -0 sed -i '' 's~-L/usr/local/Cellar/libtorrent/0.13.6/lib~-L'"$(pwd)"'/../libtorrent/src/.libs~g'
make

cd ..

rm -f /usr/local/lib/libtorrent.19.dylib /usr/local/lib/libtorrent.dylib
ln -s $(pwd)/libtorrent/src/.libs/libtorrent.dylib /usr/local/lib
ln -s $(pwd)/libtorrent/src/.libs/libtorrent.19.dylib /usr/local/lib

rm -f /usr/local/bin/rtorrent
ln -s $(pwd)/rtorrent/src/.libs/rtorrent /usr/local/bin
```

And.... yeah. That's pretty much it.

_______

For future reference, as of this writing, [this is rtorrent/master](https://github.com/rakshasa/rtorrent/tree/226e670decf92e7adaa845a6982aca4f164ea740) and [this is libtorrent/master](https://github.com/rakshasa/libtorrent/tree/c167c5a9e0bcf0df23ae5efd91396aae0e37eb87)

#157 #338 #369 Homebrew/homebrew-boneyard#109

**Comment by MikeMcQuaid** [comment]
Glad you got working. We'd accept a PR to add it back if and when it works without hacks.

**Comment by rweichler** [comment]
I dunno if it's a good idea to close this? Cuz then nobody would see this. The entire build process is pretty much laid out with no ambiguity.  The "hacks" are only there because I was trying to avoid installing it. I'm sure if you just did "make install" after each make, it would work without a hitch.

**Comment by rweichler** [comment]
For someone that understands how ruby/homebrew works, making this into a forumla would only take about 30 min id imagine

**Comment by MikeMcQuaid** [comment]
Anyone who would create this formula saw this issue.

**Comment by doctorpangloss** [comment]
For those of you finding this on Google, I posted complete command line commands from scratch that will get you `rtorrent` running on your Mac:

https://gist.github.com/doctorpangloss/ecfbe70c61de9332698d4d4445848f81

**Comment by rweichler** [comment]
^ That's a lot nicer than what I had haha. Now, if only I knew Ruby...

**Comment by pyed** [comment]
why no one is making a formulae for libtorrent and rtorrent, I'm no expert but @doctorpangloss gist looks clean and I managed to build libtorrent+rtorrent on a fresh install of High Sierra just fine and it works as expected, I had to edit the gist a bit though : https://gist.github.com/pyed/197f6a9348212e92c211ad3d3cff710a

what do you think @MikeMcQuaid ?

**Comment by MikeMcQuaid** [comment]
> why no one is making a formulae for libtorrent and rtorrent

Anyone who wishes to should do so. I do not.
