### ISSUE TITLE
glib formula now installs .gitignore file in bash completions directory

### ISSUE THREAD

**Issue by paxswill** [Homebrew/homebrew-core#108936]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 3.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5731faf8be1ddc1eeae4b162b88bd76318fc279
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c78aa5d8dd8c6b045c2e6677cbe2749a293006be
Core tap last commit: 76 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 21600
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: mvim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.37.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.8-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Open a bash shell

### What happened (include all command output)?

There's an error message at shell startup:
```
-bash: !gio: command not found
```

### What did you expect to happen?

For there to not be an error.

### Step-by-step reproduction instructions (by running `brew` commands)
1. `brew install bash-completion@2 bash glib`
1. Follow installation instructions in `bash-completion@2` caveats
1. Open new bash shell

**Comment by paxswill** [comment]
The issue is because of the .gitignore file from glib. Turning on logging in bash (with `set -x` in .bashrc) shows this (trimmed to the relevant part):
```
++++ [[ -f /usr/local/etc/bash_completion.d/.gitignore ]]
++++ [[ -r /usr/local/etc/bash_completion.d/.gitignore ]]
++++ . /usr/local/etc/bash_completion.d/.gitignore
+++++ '!gio'
-bash: !gio: command not found
```
And showing that file from glib:
```
$ ls -ahl /usr/local/etc/bash_completion.d/.gitignore
lrwxr-xr-x  1 paxswill  admin    59B Aug 24 09:25 /usr/local/etc/bash_completion.d/.gitignore@ -> ../../Cellar/glib/2.72.3_1/etc/bash_completion.d/.gitignore
$ cat /usr/local/etc/bash_completion.d/.gitignore
!gio
```

It looks like the bug was introduced in #108307, specifically [here](https://github.com/Homebrew/homebrew-core/commit/2d4a6277aa2a94bf24245870f7e441f95e68626d#diff-a3891eed6b342d3d58fff76d5dc09f5a0963e42e4635921c096c8b60942d4fc4L104-R92) where a wildcard expansion was replaced with `.children`.

**Comment by carlocab** [comment]
Thanks for the report. Will be fixed in https://github.com/Homebrew/homebrew-core/pull/108937.

You can `brew update && brew reinstall glib` when that's merged, or just `rm` the `.gitignore` now.
