### ISSUE TITLE
helmfile version is 0.145.4, Please check

### ISSUE THREAD

**Issue by yxxhero** [Homebrew/homebrew-core#108947]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://github.com/helmfile/helmfile/releases/tag/v0.145.4
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

None

### What happened (include all command output)?

None

### What did you expect to happen?

None

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
None
```

**Comment by yxxhero** [comment]
@branchvincent

**Comment by branchvincent** [comment]
Thanks for the heads up @yxxhero, #108948 should fix it

**Comment by SMillerDev** [comment]
Please see https://docs.brew.sh/Updating-Software-in-Homebrew next time instead of making an issue and tagging maintainers.

**Comment by yxxhero** [comment]
ok
