### ISSUE TITLE
reenable makepkg now that fakeroot works

### ISSUE THREAD

**Issue by RyanHir** [Homebrew/homebrew-core#109000]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
not applicable
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install `makepkg` which was disabled on [2022/03/28](https://github.com/Homebrew/homebrew-core/blob/d5ea602d327021c0d2ec47e44ada1a39698bb5ec/Formula/makepkg.rb#L17) because `fakeroot` would not build. However, it appears that `fakeroot` is building and there are packages for the current versions of macOS.

I need `makepkg` as I want to use `PKGBUILD` files to manage toolchain components in my project here https://github.com/wpilibsuite/opensdk.

It appears `makepkg` was going to be enabled here https://github.com/Homebrew/homebrew-core/issues/77488, but the page got locked by the bot.

### What happened (include all command output)?

Formula disabled!

### What did you expect to happen?

Installable `makepkg`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install makepkg
```

**Comment by SMillerDev** [comment]
If you want to change a formula you should file a pull request.
