### ISSUE TITLE
Time for a `git gc --aggressive`?

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#10904]
Today I cloned afresh the `homebrew-core` repo, and the `.git` dir was a whopping 111 MB and took a long time to download.

Can an aggressive garbage-collection be done on the server side?  Or maybe that won't even help.  (I don't know very much about git.)

**Comment by chdiza** [comment]
(I know I can shallowly clone, but the purpose of the clone was to make a PR, and making PRs based off a shallow clone has often been a big problem for me in the past.)

**Comment by MikeMcQuaid** [comment]
This couldn't be done by us, wouldn't be done by GitHub and wouldn't make a fetch any quicker. It's just a big repo with many changes over a long time, unfortunately.
