### ISSUE TITLE
macOS-arm64 slice in Homebrew binary

### ISSUE THREAD

**Issue by jacobcxdev** [Homebrew/homebrew-core#109109]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.5.10-57-g27093ad
ORIGIN: https://github.com/Homebrew/brew
HEAD: 27093adb09464563de1cab90f3ac0ae6f1900d1e
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d5ea602d327021c0d2ec47e44ada1a39698bb5ec
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit westmere
Clang: 14.0.0 build 1400
Git: 2.37.2 => /usr/local/bin/git
Curl: 7.83.1 => /usr/bin/curl
macOS: 13.0-x86_64
CLT: N/A
Xcode: 14.0 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: true
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

The latest available binary on Homebrew currently lacks a macOS-arm64 slice. This has been causing issues when linking against libunicorn.dylib and building for macOS-arm64 (e.g. any Apple Silicon Mac).

### What happened (include all command output)?

Below is an excerpt from my build log.
```
Ignoring file /usr/local/Cellar/unicorn/2.0.0/lib/libunicorn.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

### What did you expect to happen?

`/usr/local/Cellar/unicorn/2.0.0/lib/libunicorn.dylib` to contain a macOS-arm64 slice.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install unicorn
```

(See unicorn-engine/unicorn/issues/1696.)

**Comment by Bo98** [comment]
You have the x86_64 version of Homebrew installed.

arm64 Homebrew installs to `/opt/homebrew`.

**Comment by jacobcxdev** [comment]
> You have the x86_64 version of Homebrew installed.
> 
> 
> 
> arm64 Homebrew installs to `/opt/homebrew`.

Thanks for letting me know — I've realised there's a much wider issue with my system where arch, uname, etc. are returning x86_64 and i386 instead of arm64… I have no idea why 😐.

**Comment by Bo98** [comment]
Your terminal is perhaps running under Rosetta.

**Comment by jacobcxdev** [comment]
> Your terminal is perhaps running under Rosetta.

Activity monitor displays both Terminal.app and iTerm 2 running using Apple (ARM) slices, and the checkbox to run under Rosetta 2 is unchecked.

**Comment by carlocab** [comment]
Are you running `screen` or `tmux` installed with `brew` in `/usr/local`?

**Comment by jacobcxdev** [comment]
I am not currently.

**Comment by jacobcxdev** [comment]
I've found the issue: my ZSH installation was x86_64, not arm64… *cough* https://github.com/ProcursusTeam/Procursus *cough*.
