### ISSUE TITLE
Incorrect library pathing for postgresql@14 

### ISSUE THREAD

**Issue by dhendry** [Homebrew/homebrew-core#109164]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config

HOMEBREW_VERSION: 3.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5731faf8be1ddc1eeae4b162b88bd76318fc279
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f554ff6487482fb9673848ba038f7e89eb70ec92
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false
```

```
brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  go@1.16

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/dhendry/.pyenv/shims/python3.6m-config
  /Users/dhendry/.pyenv/shims/python3.7-config
  /Users/dhendry/.pyenv/shims/python3.10-config
  /Users/dhendry/.pyenv/shims/python3.7m-config
  /Users/dhendry/.pyenv/shims/python3.9-config
  /Users/dhendry/.pyenv/shims/python-config
  /Users/dhendry/.pyenv/shims/python3-config
  /Users/dhendry/.pyenv/shims/python3.6-config
  /Users/dhendry/.pyenv/shims/python3.8-config
```

Please note that I am unable to fix the above brew doctor warnings due to other system configuration constraints but I would not expect any should be related to this issue.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

* Investigate an issue with the python package `psycopg2-binary==2.8.6`
* `psycopg2-binary==2.8.6` has been failing to initialize correctly due to the following error

```
ImproperlyConfigured: Error loading psycopg2 module: dlopen(/Users/dhendry/code/ad_analysis/.venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so, 0x0002): Library not loaded: '/opt/homebrew/opt/postgresql/lib/libpq.5.dylib'
  Referenced from: '/Users/dhendry/code/ad_analysis/.venv/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so'
  Reason: tried: '/opt/homebrew/opt/postgresql/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file), '/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
```

Note the component of the path which is `'/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/libpq.5.dylib' (no such file)`

### What happened (include all command output)?

```
ls -Alh  /opt/homebrew/Cellar/postgresql@14/14.5_1/lib/
```

I see the following directory list

```
drwxr-xr-x  106 dhendry  admin   3.3K 29 Aug 08:01 postgresql@14
```

### What did you expect to happen?

I expected to find all library files under `/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/`

Instead, all of the files are nested under an additional `postgresql@14` directory

```
➜  ~ ls -Alh  /opt/homebrew/Cellar/postgresql@14/14.5_1/lib/postgresql@14 
total 16768
-r--r--r--  1 dhendry  admin    63K  8 Aug 14:59 _int.so
-r--r--r--  1 dhendry  admin    38K  8 Aug 14:59 adminpack.so
-r--r--r--  1 dhendry  admin    75K  8 Aug 14:59 amcheck.so
-r--r--r--  1 dhendry  admin    33K  8 Aug 14:59 auth_delay.so
-r--r--r--  1 dhendry  admin    52K  8 Aug 14:59 auto_explain.so
-r--r--r--  1 dhendry  admin    34K  8 Aug 14:59 autoinc.so
...
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql@14

ls -Alh  /opt/homebrew/Cellar/postgresql@14/14.5_1/lib/
```

# Links

If this is a bug I suspect it is related to the following cc: @MikeMcQuaid:
* https://github.com/Homebrew/homebrew-core/commit/8060df9169055ee1fb9d1d69fd149c3922e864ba
* Which appears to come form https://github.com/Homebrew/homebrew-core/pull/107726

**Comment by dhendry** [comment]
Following from discussion https://github.com/orgs/Homebrew/discussions/3579

**Comment by carlocab** [comment]
Based on Homebrew/discussions#3579, this is expected behaviour. You need to use `pg_config` to get the right library directory.

**Comment by dhendry** [comment]
@carlocab as per my comments on that discussion:

The key point to me is the postgres version is already encoded higher up the path in multiple places so I would not think the additional `postgresql@14` is necessary:

`/opt/homebrew/Cellar/**postgresql@14**/**14.5_1**/lib/` -> I would never expect `postgresql@15` to be a valid subdirectory here


Also, there is not the additional level of version redirection in the `bin` directory:

```
➜  ~ ls -Alh /opt/homebrew/Cellar/postgresql@14/14.5_1/lib
total 0
drwxr-xr-x  106 dhendry  admin   3.3K 29 Aug 08:01 postgresql@14

➜  ~ ls -Alh /opt/homebrew/Cellar/postgresql@14/14.5_1/bin
total 25768
-r-xr-xr-x  1 dhendry  admin   113K 29 Aug 08:01 clusterdb
-r-xr-xr-x  1 dhendry  admin   113K 29 Aug 08:01 createdb
-r-xr-xr-x  1 dhendry  admin   113K 29 Aug 08:01 createuser
-r-xr-xr-x  1 dhendry  admin   112K 29 Aug 08:01 dropdb
-r-xr-xr-x  1 dhendry  admin   112K 29 Aug 08:01 dropuser
-r-xr-xr-x  1 dhendry  admin   873K  8 Aug 14:59 ecpg
-r-xr-xr-x  1 dhendry  admin   167K 29 Aug 08:01 initdb
...
```

Finally, if I look at any other versioned package, there is not the same level of indirection. Consider openssl:

```
➜  ~ ls -Alh /opt/homebrew/Cellar/openssl@3/3.0.5/lib 
total 21824
drwxr-xr-x  11 dhendry  admin   352B  6 Jul 05:04 .
drwxr-xr-x  14 dhendry  admin   448B  6 Jul 05:04 ..
drwxr-xr-x   5 dhendry  admin   160B  6 Jul 05:04 engines-3
-rw-r--r--   1 dhendry  admin   3.2M  6 Jul 05:04 libcrypto.3.dylib
-r--r--r--   1 dhendry  admin   6.1M  5 Jul 02:57 libcrypto.a
lrwxr-xr-x   1 dhendry  admin    17B  5 Jul 02:57 libcrypto.dylib -> libcrypto.3.dylib
-r--r--r--   1 dhendry  admin   553K  6 Jul 05:04 libssl.3.dylib
-r--r--r--   1 dhendry  admin   861K  5 Jul 02:57 libssl.a
lrwxr-xr-x   1 dhendry  admin    14B  5 Jul 02:57 libssl.dylib -> libssl.3.dylib
drwxr-xr-x   3 dhendry  admin    96B  6 Jul 05:04 ossl-modules
drwxr-xr-x   5 dhendry  admin   160B  6 Jul 05:04 pkgconfig
```

The path is NOT `/opt/homebrew/Cellar/openssl@3/3.0.5/lib/openssl@3`

**Comment by dhendry** [comment]
Duplicating comment from [discussion thread](https://github.com/orgs/Homebrew/discussions/3579#discussioncomment-3510647) here: 

@carlocab @bayandin @MikeMcQuaid One last attempt to explain why I think there is a bug here:

1. I believe the reason psycopg2 is searching the `/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/` path to begin with is that:
   1. It looks at the symlinked resolved path for the postgres executable
   2. It then uses the `lib` directory which is a sibling of the `bin` directory. 
   * This does not seem unreasonable to me based on my understanding of how unix directories should be laid out.

Here is a hacky bash equivalent of what I _believe_ the resolution logic is doing:

```bash
# Where is postgres:
➜  which postgres
/opt/homebrew/bin/postgres

# Whats the symlink its pointing at:
➜  ls -l  /opt/homebrew/bin/postgres
lrwxr-xr-x  1 dhendry  admin  43 29 Aug 08:01 /opt/homebrew/bin/postgres -> ../Cellar/postgresql@14/14.5_1/bin/postgres

# Resolve symlink: 
➜  realpath $(which postgres)
/opt/homebrew/Cellar/postgresql@14/14.5_1/bin/postgres

# lib directory path which is a sibling of the bin directory which seems reasonable:
➜  echo "$(realpath $(which postgres) | xargs dirname)/../lib/"
/opt/homebrew/Cellar/postgresql@14/14.5_1/bin/../lib/

# Contents of this lib directory (sibling of bin): 
# I would expect proper library contents to belong here but instead they are buried a directory deeper 
# (which seems unnecessary and incorrect, or at the very least very unexpected and non-standard)
➜  ls -l  /opt/homebrew/Cellar/postgresql@14/14.5_1/bin/../lib/
total 0
drwxr-xr-x  106 dhendry  admin  3392 29 Aug 08:01 postgresql@14
```

2. The logic I described above works for **every** versioned brew package I have checked so far including:
* `openssl@1.1`/`openssl@3`
* `llvm@11`
* `mysql`/`mysql@5.7`
* `mariadb`/`mariadb@10.7`

I have not seen a single case where any other package adds an additional level of version redirection under the already versioned cellar path

You can check for yourself with the following: `ls -ld "$(realpath $(which mysql) | xargs dirname)/../lib/"*`

For example:

```bash
# Check for mysql
➜  ls -ld "$(realpath $(which mysql) | xargs dirname)/../lib/"* | head   
-rw-r--r--    1 dhendry  admin  6822224 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlclient.21.dylib
-r--r--r--    1 dhendry  admin  7377720  6 Jul 16:01 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlclient.a
lrwxr-xr-x    1 dhendry  admin       23  6 Jul 16:01 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlclient.dylib -> libmysqlclient.21.dylib
-r--r--r--    1 dhendry  admin   861808 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlharness.1.dylib
-r--r--r--    1 dhendry  admin    57488 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlharness_stdx.1.dylib
-r--r--r--    1 dhendry  admin   101280 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlharness_tls.1.dylib
-r--r--r--    1 dhendry  admin  7896464 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlrouter.1.dylib
-r--r--r--    1 dhendry  admin   110992 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlrouter_connection_pool.1.dylib
-r--r--r--    1 dhendry  admin   129872 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlrouter_http.1.dylib
-r--r--r--    1 dhendry  admin   134032 28 Jul 06:33 /opt/homebrew/Cellar/mysql/8.0.30/bin/../lib/libmysqlrouter_http_auth_backend.1.dylib

# Same logic does NOT work for postgres (but it DOES for *every* other brew binary I have tried which has a lib companion):
➜  ls -ld "$(realpath $(which postgres) | xargs dirname)/../lib/"* | head
drwxr-xr-x  106 dhendry  admin  3392 29 Aug 08:01 /opt/homebrew/Cellar/postgresql@14/14.5_1/bin/../lib/postgresql@14
```

Sorry to keep bringing this up but this issue is a huge pain for me as we do not control the psycopg2 library and need to use an older version for legacy reasons (which we are trying to migrate away from as a separate initiative). I have resorted to asking my team to do really crazy things like `sudo ln -s /opt/homebrew/opt/postgresql@14/lib/postgresql@14/libpq.5.dylib /usr/local/lib`. 

Irrespective of my specific issue, this still just feels like a bug in the postgres homebrew formula. It seems entirely reasonable to me that the `lib` sibling of the `bin` directory has the same structure.

Thanks for the help and thanks for all your effort on the homebrew project!

**Comment by jaklan** [comment]
Bump this one, I have just updated the `postgresql` formula and `dbt`, which uses `psycopg2` under the hood, started to fail for the same reason:
```
  Reason: tried: '/opt/homebrew/opt/postgresql/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file), '/opt/homebrew/Cellar/postgresql@14/14.5_1/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
```

https://github.com/Homebrew/homebrew-core/pull/107726 was introduced to avoid breaking changes, but it is a breaking change itself...

**Comment by SMillerDev** [comment]
No, it was made to avoid it breaking. Which is a different thing.

**Comment by jaklan** [comment]
@SMillerDev yeah, that's what I meant, mental shortcut. 

Anyway, I was able to fix the following issue by explicitly installing `psycopg2` into `dbt` environment:
`pipx inject dbt-core psycopg2`
based on [that suggestion](https://github.com/psycopg/psycopg2/issues/1490#issue-1353228885). Btw, reinstalling `dbt` packages was not enough.

**Comment by SMillerDev** [comment]
I can't find a formula for `dbt`, how did you install it?

**Comment by jaklan** [comment]
@SMillerDev nah, `dbt-core`, together with `dbt-postgres` and `dbt-redshift`, is installed via `pipx`, and `pipx` is installed via `brew`. `dbt` depends on `psycopg2`, and `psycopg2` was looking for the the needed libs in the paths specified above, but after reinstalling - it seems it also discovered the new one.

**Comment by jaklan** [comment]
I found a reason why reinstalling `dbt` wasn't enough:
https://github.com/dbt-labs/dbt-core/blob/1df713fee986741289568f553befdd4e38a51122/plugins/postgres/setup.py#L32-L40
`dbt` by default uses `psycopg2-binary`, not `psycopg2`. And it seems reinstalling `psycopg2-binary` doesn't solve the issue, but additionally installing pure `psycopg2` - does.
