### ISSUE TITLE
option to skip fontconfig cache regeneration

### ISSUE THREAD

**Issue by vszakats** [Homebrew/homebrew-core#10920]
First of all thanks for the new self-contained `wine` formula, I'm migrating from the wine-devel cask as we speak.

One concern with it, which I noticed on the first install: The infamous fontconfig cache regeneration is taking place as a post-install task and this may be a problem when installing the formula on CI machines. These are headless and certainly not GUI, so fonts should not matter. The regeneration process however takes several minutes (~2-5), which reduces the useful time to run the actual build and adds an uncomfortable wait to each CI session.

I had committed a patch to address this problem to the MSYS2 project here: Alexpux/MINGW-packages@fdea2f9
It solved the problem properly.

Do you think it would be feasible to implement a similar setting to the wine formula? I'm unsure about the best way, but maybe an --without-fc-cache or similar option would do. Or an envvar, like in MSYS2.

Any opinions?

**Comment by vszakats** [comment]
Closing in favour of PR #10947.

**Comment by vszakats** [comment]
Reopening this, as it is also an issue with `fontconfig` itself, even when it is being installed as a dependency.

The issue is that installing any of those packages that have `fontconfig` as a dependency, a several minutes long delay is required. This is fine on local machines, but quite a waste when using `homebrew` on a CI machine for automated builds (f.e. with Travis CI.)

The suggested `brew install --force-bottle --build-bottle wine` hack does work fine for `wine` but it's almost impossible to discover by a normal user and won't cover the cases when `fontconfig` is a normal dependency.

The previously proposed envvar-based solution is rather simple and painless.

**Comment by vszakats** [comment]
Proposed patch: https://github.com/Homebrew/homebrew-core/compare/master...vszakats:fc

**Comment by ilovezfs** [comment]
If it's a dependency, you can use the same arguments to install `fontconfig` before installing whatever is using it.

**Comment by vszakats** [comment]
@ilovezfs That's true and thanks for the tip (which didn't occur me last night.)

I'd argue it's still not very ideal given that now it's required to know about the hack, to discover which packages may depend on `fontconfig` and manually install a dependency, if any of them do (in my case these are `cairo` and `gd`.)

I'm guessing there is quite a bit of CI cycles wasted on `fc-cache`.

**Comment by mpsuzuki** [comment]
recently I'm working with poppler + travis-ci, and I agree with your point; un-avoidable execution of fc-cache in each "brew install" is not good idea. however, yet I'm unfamiliar with brew and cannot propose a patch, I don't want to blame anybody. just I wanted to thank you because I found my request is not so irregular.
