### ISSUE TITLE
Gstreamer not working on M1 Max Macbook

### ISSUE THREAD

**Issue by scalers-ai** [Homebrew/homebrew-core#109283]
### `brew config` output

```shell
1) MacBook Pro (14-inch, 2021) - Chip M1 Max
2) Installed gstreamer with this command: brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-rtsp-server gst-editing-services gst-devtools

3) Upon launching any gstreamer pipeline (already tried reinstalling, rebooting etc. etc.)
e.g.
gst-launch-1.0 videotestsrc ! fakesink

I get this error.

(gst-plugin-scanner:1245): GLib-GObject-WARNING **: 06:45:13.387: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.388: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.388: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:1245): GLib-GObject-WARNING **: 06:45:13.404: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.404: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.404: g_type_set_qdata: assertion 'node != NULL' failed
```

### `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.9/greenlet/greenlet.h
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to Run gstreamer on Mac M1 Max

gst-launch-1.0 videotestsrc ! fakesink

### What happened (include all command output)?

Application does NOT work

(gst-plugin-scanner:1245): GLib-GObject-WARNING **: 06:45:13.387: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.388: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.388: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:1245): GLib-GObject-WARNING **: 06:45:13.404: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.404: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:1245): GLib-GObject-CRITICAL **: 06:45:13.404: g_type_set_qdata: assertion 'node != NULL' failed

### What did you expect to happen?

Expected it to work

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-rtsp-server gst-editing-services gst-devtools
```

**Comment by SMillerDev** [comment]
What made you think Homebrew's code has an issue rather than the gstreamer project itself?

**Comment by scalers-ai** [comment]
1) The gstreamer standalone (non-Homebrew) does work
2) The gstreamer Homebrew build does not work

https://gstreamer.freedesktop.org/documentation/installing/on-mac-osx.html?gi-language=c

**Comment by SMillerDev** [comment]
Judging by the macOS versions referenced on that page that pkg is for a x86 version of gstreamer and it works only in Rosetta.

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1358 indicates that gstreamer doesn't work on M1 macs

**Comment by scalers-ai** [comment]
Thanks for your prompt response!

The gstreamer build from the gstreamer site work. The "kind" shows up as "Apple" and not "Rosetta" indicating that it is in fact the M1 version.

Appreciate any pointers. Perhaps there may be some weird issue in an upstream dependency in the Homebrew builds (I don't know the internals)?


![image](https://user-images.githubusercontent.com/91742529/187676169-dd7c98d0-b9c8-4589-bb86-89b190d9ee0b.png)

![image](https://user-images.githubusercontent.com/91742529/187676543-a8fbcf56-0026-4f5b-acea-93568c52b900.png)

**Comment by alebcay** [comment]
The non-Homebrew version distributed by upstream (both [runtime](https://gstreamer.freedesktop.org/data/pkg/osx/1.20.3/gstreamer-1.0-1.20.3-universal.pkg) and [development](https://gstreamer.freedesktop.org/data/pkg/osx/1.20.3/gstreamer-1.0-devel-1.20.3-universal.pkg)) seem to contain all fat libraries with both `x86_64` and `arm64` slices. I guess the GitLab issue linked above is outdated.

**Comment by alebcay** [comment]
FYI, this looks M1-specific; works fine on my Intel machine:
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/3536482/187993759-34ca87d4-382a-4468-a30b-1c46e147d745.png">

**Comment by cho-m** [comment]
When I tried commands on M1, after the `GLib-GObject-WARNING`/etc messages, the commands worked (below with `fakesink` and also tried `autovideosink` with no issue).

```console
❯ gst-launch-1.0 videotestsrc ! fakesink

(gst-plugin-scanner:23613): GLib-GObject-WARNING **: 14:53:06.125: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:23613): GLib-GObject-CRITICAL **: 14:53:06.126: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:23613): GLib-GObject-CRITICAL **: 14:53:06.126: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:23613): GLib-GObject-WARNING **: 14:53:06.142: type name '-a-png-encoder-pred' contains invalid characters

(gst-plugin-scanner:23613): GLib-GObject-CRITICAL **: 14:53:06.142: g_type_set_qdata: assertion 'node != NULL' failed

(gst-plugin-scanner:23613): GLib-GObject-CRITICAL **: 14:53:06.142: g_type_set_qdata: assertion 'node != NULL' failed
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
Redistribute latency...
New clock: GstSystemClock
0:28:21.9 / 99:99:99.
```

As far as I can tell, the logged warnings didn't impact particular functionality.

Anyway, it could be an upstream issue in `gst-libav` with FFmpeg 5 https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1055
