### ISSUE TITLE
On M1 Mac : Hive has a dependancy on openjdk@8 (which is no longer available)

### ISSUE THREAD

**Issue by davidradl** [Homebrew/homebrew-core#109379]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew install hive will fail with an error saying that dependancy openjdk@8

On my new mac which has an M1 processor, I get the above error.

I cannot install openjdk@8 using brew. In the past on an non-M1 mac I used to be able to do this. 

Looking into this , openjdk is now deprecated . See https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

I appear to have fixed hive by symlinking the openJDK@8 to my tempurin@8 folder.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install hive. - to use hive

### What happened (include all command output)?

brew install hive 

....
Error: openjdk@8: no bottle available!

### What did you expect to happen?

successfull hive install. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install hive 

this may only fail on an M1 mac. I am not sure if the openjdk@8 is only not available on the M1 mac
```

**Comment by davidradl** [comment]
I think the fix is to change the dependancy from openjdk@8 to temurin@8

**Comment by Bo98** [comment]
OpenJDK 8 has not been ported to Apple Silicon. OpenJDK 11 and later have.

Even Temurin (which we don't have in Homebrew/core anyway) does not have a build for Apple Silicon of OpenJDK 8.

There's an upstream issue tracking the port to OpenJDK 11: https://issues.apache.org/jira/browse/HIVE-22415.

The workaround here is to install an x86_64 version of Homebrew via Rosetta.

**Comment by planetf1** [comment]
On my m1 I was able to install the following *casks* (not formula)

- zulu8 https://github.com/Homebrew/homebrew-cask-versions/blob/HEAD/Casks/zulu8.rb

➜  ~ /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java -version
openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Zulu 8.64.0.19-CA-macos-aarch64) (build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Zulu 8.64.0.19-CA-macos-aarch64) (build 25.345-b01, mixed mode)

- temurin8 https://github.com/Homebrew/homebrew-cask-versions/blob/HEAD/Casks/temurin8.rb

➜  ~ /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java -version

openjdk version "1.8.0_345"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_345-b01)
OpenJDK 64-Bit Server VM (Temurin)(build 25.345-b01, mixed mode)

Would either of these be suitable?

I presume the difficulty is that they are casks and not in Homebrew/core ?

**Comment by Bo98** [comment]
That'll be right. Though not in the temurin case, I think it's actually installing an x86_64 version that runs through Rosetta: check with `file /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java`. Casks don't install into a single place so you don't need separate x86_64 and arm64 installs of Homebrew for casks like you would for formulae.

Zulu is native arm64 but it's a custom patch made by Zulu that's not exactly open source. You have to email them to even get the source code. Unlike casks, formulae must be completely open source.

**Comment by planetf1** [comment]
That makes sense re: open source, and native - good to know
```
 ➜  master git:(master) file /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java                                                                                <<<
/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java: Mach-O 64-bit executable arm64
➜  master git:(master) file /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java
/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java: Mach-O 64-bit executable x86_64
➜  master git:(master) file /Library/Java/JavaVirtualMachines/temurin-18.jdk/Contents/Home/bin/java
/Library/Java/JavaVirtualMachines/temurin-18.jdk/Contents/Home/bin/java: Mach-O 64-bit executable arm64
```
Agreed the root cause is the old hive code/java 11 support as 8 is way outdated now. The rosetta workaround is useful idea -thanks

**Comment by davidradl** [comment]
thanks for your help @Bo98 @planetf1 seems to have worked using Rosetta
