### ISSUE TITLE
jsonschema is correctly given ,but validate fail in code

### ISSUE THREAD

**Issue by rushant001** [Homebrew/homebrew-core#109483]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
none.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

validate jsonschema

### What happened (include all command output)?

input json body:
{"error_code": 0, "error_msg": "OK", "result": {"data": [{"action": "to", "mod": "cleaner", "property": "area", "property_unit": null, "property_value": ["1013", "2014"], "reply": "", "skill_id": "1104379", "time_duration": null, "time_start": "2022-09-03|22:00:00"}], "err_code": 0, "err_msg": "ok", "response_list": [{"schema": {"slots": [], "intent_confidence": 100, "intent": "", "domain_confidence": 100}, "origin": "1104379", "action_list": [{"custom_reply": "{\"reply\":[]}"}]}]}}
 
input jsonschema:
{"required": ["error_code", "error_msg", "result"], "type": "object", "properties": {"error_code": {"type": "integer"}, "error_msg": {"type": "string"}, "result": {"required": ["data", "err_code", "err_msg", "response_list"], "type": "object", "properties": {"err_msg": {"type": "string"}, "data": {"items": [{"required": ["action", "mod", "property", "property_unit", "property_value", "reply", "skill_id", "time_duration", "time_start"], "type": "object", "properties": {"property_unit": {"type": "null"}, "time_duration": {"type": "null"}, "property_value": {"items": {}, "type": "array"}, "action": {"type": "string"}, "reply": {"type": "string"}, "property": {"type": "string"}, "time_start": {"type": "string"}, "skill_id": {"type": "string"}, "mod": {"type": "string"}}}], "type": "array"}, "response_list": {"items": [{"required": ["schema", "origin", "action_list"], "type": "object", "properties": {"origin": {"type": "string"}, "action_list": {"items": [{"required": ["custom_reply"], "type": "object", "properties": {"custom_reply": {"type": "string"}}}], "type": "array"}, "schema": {"required": ["slots", "intent_confidence", "intent", "domain_confidence"], "type": "object", "properties": {"intent": {"type": "string"}, "slots": {"items": {}, "type": "array"}, "intent_confidence": {"type": "integer"}, "domain_confidence": {"type": "integer"}}}}}], "type": "array"}, "err_code": {"type": "integer"}}}}}

### What did you expect to happen?

jsonschema validate pass

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
from jsonschema import validate
ret = validate(instance=response, schema=validate_schema)
```

**Comment by carlocab** [comment]
This problem does not have anything to do with Homebrew. Please consult the documentation for `jsonschema`.
