### ISSUE TITLE
libharu shared lib install

### ISSUE THREAD

**Issue by redtempura** [Homebrew/homebrew-core#109676]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
formula file: libharu.rb
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install libharu to system and compile independent project with libharu dependency and dynamic linking

### What happened (include all command output)?

shared lib not installed

### What did you expect to happen?

libharu.dylib to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libharu
//link to shared library --> linker error: libharu not found
//fix: 'lib.install "build-static/src/libharu.dylib"' to libharu.rb
```

**Comment by carlocab** [comment]
The output of `brew config` and `brew doctor` is required information for all bug reports to this repository. This is indicated in the PR template. We can reopen this when you provide the requested information.

**Comment by chenrui333** [comment]
> ```shell
> brew install libharu
> //link to shared library --> linker error: libharu not found
> //fix: 'lib.install "build-static/src/libharu.dylib"' to libharu.rb
> ```

Can you upload the build logs? What artifact are you trying to build against?
