### ISSUE TITLE
Node package seems to be broken since icu4c update

### ISSUE THREAD

**Issue by jdecool** [Homebrew/homebrew-core#109968]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config

HOMEBREW_VERSION: 3.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 93ea8cb2c40e1ef25f1489b0267526bd47bc8030
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6b19db40b4b6ae05c2a4bc2fa33965bd3d703cc1
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.37.3 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.4.1
Rosetta 2: false


$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@12
  php@7.3

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  flux
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Since the icu4c package has been updated, `node` (the main) package doesn't run anymore.

This issue has been reproduce on many other formulae depend on `icu4c`
* https://github.com/shivammathur/homebrew-php/issues/1068 & https://github.com/shivammathur/homebrew-php/issues/1089

### What happened (include all command output)?

```text
$ node -v
dyld[16993]: Library not loaded: '/opt/homebrew/opt/icu4c/lib/libicui18n.70.dylib'
  Referenced from: '/opt/homebrew/Cellar/node/18.8.0_1/bin/node'
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicui18n.70.dylib' (no such file), '/usr/local/lib/libicui18n.70.dylib' (no such file), '/usr/lib/libicui18n.70.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/71.1/lib/libicui18n.70.dylib' (no such file), '/usr/local/lib/libicui18n.70.dylib' (no such file), '/usr/lib/libicui18n.70.dylib' (no such file)
[1]    16993 abort      node -v
```

### What did you expect to happen?

Should run properly without error and display the program version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Before the upgrade icu4c was installed in 70.1.

Update icu4c to the latest version (eg. 71.1).

`node` doesn't work anymore.
```

**Comment by carlocab** [comment]
What is the output of
```
brew info node
brew outdated
```
?

**Comment by jdecool** [comment]
Strange, I just try to reinstall node and there's no error anymore.

So sorry for my mistake...

**Comment by carlocab** [comment]
We rebuilt Node when we updated `icu4c`, so `brew upgrade icu4c` should have also installed the rebuilt version of Node.

That is, unless you:
1. did `brew pin node`.
2. set `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK`.
3. did another thing that prevented `node` from being upgraded.

If none of the above apply, then that's a bug that needs to be fixed.
