### ISSUE TITLE
BIND 9.10.4 is deprecated; requires manual reinstall

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-core#1099]
BIND 9.10.4 may have a fatal crash defect, and has been deprecated by upstream.

https://lists.isc.org/pipermail/bind-users/2016-May/096851.html

We've rolled back the Homebrew formula to 9.10.3-P4. See discussion [here](https://github.com/Homebrew/homebrew-core/pull/796#issuecomment-218734283).

I'm posting this as a separate bug here so that users following our Issue activity will see it. While we've already done the rollback, please leave this Issue open for a little while to give people a chance to see it.

Users: if you have `bind` 9.10.4 installed (or aren't sure which version you have), do a `brew update; brew reinstall bind` to pick up the correct version. (`brew upgrade` will not catch it, because `brew` doesn't have a mechanism for indicating that `upgrade` should go backwards in versions.)

**Comment by mikemcquaid** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/issues/796
