### ISSUE TITLE
not able to install ruby version 2.4 on macos ventura (13.0) beta 

### ISSUE THREAD

**Issue by vikramcse** [Homebrew/homebrew-core#110112]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 93ea8cb2c40e1ef25f1489b0267526bd47bc8030
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f7f87675fd46469df5c9383e858db062fb77ec9
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-x86_64
CLT: 11.0.0.33.12
Xcode: 12.2
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to install ruby version 2.4 on macos ventura.

why: want to check my code run's on macos ventura beta

### What happened (include all command output)?

brew reinstall ruby@2.4
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: ruby@2.4 has been disabled because it is not supported upstream!

### What did you expect to happen?

it should install ruby version 2.4

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall ruby@2.4
```

**Comment by bayandin** [comment]
> it should install ruby version 2.4

Nope, the formula is disabled, so you can't install it despite of macOS version.


And this:
> You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.
