### ISSUE TITLE
ffmpeg <-> chromaprint cyclic depedency

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-core#11058]
chomaprint depends on ffmpeg and ffmpeg has a --with-chromaprint option. Someone on IRC noticed that having ffmpeg installed --with-chromaprint means that neither ffmpeg or chromaprint could be upgraded because they depend on each other.

--with-chromaprint was added to ffmpeg in #7713. I think we should probably remove the option. @dericed, you sent that PR; do you see any alternatives?

**Comment by ilovezfs** [comment]
@tdsmith this has been known for a while. See

https://github.com/Homebrew/brew/issues/1933
https://github.com/Homebrew/brew/pull/2093
https://github.com/Homebrew/homebrew-core/pull/10207

I think this is no longer an issue in https://github.com/Homebrew/homebrew-core/pull/8595 which should be shipped now that it is no longer blocked, as pointed out by Dom https://github.com/Homebrew/homebrew-core/pull/8595#issuecomment-285031798.

**Comment by tdsmith** [comment]
:+1:; thanks!
