### ISSUE TITLE
GCC 12.2.0 breaks TLS (thread_local) at least on x86_64

### ISSUE THREAD

**Issue by boris-kolpackov** [Homebrew/homebrew-core#110673]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config

HOMEBREW_VERSION: 3.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6e2b162c4786e075323f038d46bfb566d91889e7
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b327cd385a61f4583890a3d12b90789d2a09864d
Core tap last commit: 73 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit penryn
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5-x86_64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A

% brew info gcc@12

==> gcc: stable 12.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org/
/usr/local/Cellar/gcc/12.2.0 (1,582 files, 405.2MB) *
  Poured from bottle on 2022-09-13 at 10:02:41
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb
License: GPL-3.0-or-later with GCC-exception-3.1
==> Dependencies
Required: gmp, isl, libmpc, mpfr, zstd
==> Options
--HEAD
	Install HEAD version
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I upgraded from GCC 12.1.0 to GCC 12.2.0. @fxcoudert 

### What happened (include all command output)?

This upgrade appears to have broken TLS support, specifically, C++ `thread_local` mechanism, at least on x86_64 (I haven't tested M1).

### What did you expect to happen?

I expected the TLS support to continue working correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
// file: tl.hxx
#pragma once

extern thread_local void* tl;

inline void* gt_tl () {return tl;}
```

```
// file: tl.cxx
#include "tl.hxx"

thread_local void* tl = nullptr;
```

```
// file: main.cxx
#include "tl.hxx"

int main ()
{
  return gt_tl () == nullptr ? 0 : 1;
}
```

```
$ g++-12 tl.cxx main.cxx
Undefined symbols for architecture x86_64:
  "__ZTH2tl", referenced from:
      __ZTW2tl in cc4nuRRN.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

Interestingly, if we combine the two files into a single translation unit, then the error goes away (which perhaps suggests it's a symbol visibility issue):

```
$ cat tl.cxx main.cxx >tl-main.cxx
$ g++-12 -o tl tl-main.cxx
```
```

**Comment by iains** [comment]
is this "fixed" - I see it's closed?  if not, please file a bug on the compiler with the reproducer.
Note that GCC12.2 does have a fix for the (previously broken) cross-TU initialization of thread-local vars .. clearly, this could be related.

**Comment by boris-kolpackov** [comment]
@iains 

> is this "fixed" - I see it's closed?

No, this issue is still open (perhaps you've confused it with the mentioned issue 106394, which is closed).

> if not, please file a bug on the compiler with the reproducer.

The reproducer is provided in this issue. Are you suggesting that I file a bug report in the GCC's bugzilla? If that's helpful, I can definitely do that.

**Comment by iains** [comment]
> @iains

> > if not, please file a bug on the compiler with the reproducer.

the reproducer needs to work outside of the home-brew structure .. otherwise it's almost impossible to debug.

> The reproducer is provided in this issue. Are you suggesting that I file a bug report in the GCC's bugzilla? If that's helpful, I can definitely do that.

no .. please file one against the Darwin 12.2. branch here, which is what is current for Darwin:
https://github.com/iains/gcc-12-branch/issues

In general, if it's determined to be a compiler bug - please file it there - otherwise I will probably never see it (except by luck,  like this time).

**Comment by boris-kolpackov** [comment]
> please file one against the Darwin 12.2. branch

Done: https://github.com/iains/gcc-12-branch/issues/9

**Comment by fxcoudert** [comment]
@iains I'm monitoring things here and encourage people to report to you (or do it myself) after I filter out some non-compiler issues.

**Comment by yhu266** [comment]
More examples related to this issue
- https://github.com/spack/spack/issues/32640
- https://github.com/open-source-parsers/jsoncpp/issues/1434

And a (maybe) relevant post in Apple Developer Forums: https://developer.apple.com/forums/thread/714565

**Comment by Bo98** [comment]
> 

That's a different issue caused by an Xcode 14 `ld` bug rather than a GCC one.

**Comment by boris-kolpackov** [comment]
@fxcoudert There is an upstream fix for this (see https://github.com/iains/gcc-12-branch/issues/9). I wonder if/when it will get propagated to Homebrew?

**Comment by carlocab** [comment]
It might take a bit, because we are unable to rebuild `gcc` due to https://github.com/iains/gcc-12-branch/issues/6

**Comment by boris-kolpackov** [comment]
@carlocab The https://github.com/iains/gcc-12-branch/issues/6#issuecomment-1260282797 comment in that issue reports things have been fixed in the latest beta of CLT, so maybe things are unblocking now?

**Comment by carlocab** [comment]
We need to upgrade Xcode first. But we'll need the beta I think.

I'm open to doing this to unblock us, but CC @Homebrew/brew to be sure.

On the other hand, the actual release is likely imminent, so it may be better to just wait.

**Comment by iains** [comment]
Will try to make the actual 12.2Dr1 release over the weekend, so you are not pulling from a pre-release.

**Comment by MikeMcQuaid** [comment]
> We need to upgrade Xcode first. But we'll need the beta I think.
> 
> I'm open to doing this to unblock us, but CC @Homebrew/brew to be sure.

@carlocab Can you elaborate on the ask here, not totally sure I understand it ❤️

**Comment by carlocab** [comment]
Oh, was just wondering about whether we should upgrade our Xcode install to the latest beta to pull in some fixes, since we're currently unable to rebuild some formulae without them. Apologies for the lack of clarity!

**Comment by MikeMcQuaid** [comment]
@carlocab Thanks for clarifying! I'd lean against upgrading to the beta and considering downgrading GCC just because of the potential for it to break other formulae but I don't have strong opinions either way.

**Comment by iains** [comment]
the problem is not actually with GCC .. so "downgrading" would not necessarily make any difference

**Comment by fxcoudert** [comment]
- Re. Xcode: I'm against building bottles with a beta version, and in this case the release will come soon. Let's wait and updated to the official 14.1 when it is released.
- Re. GCC: the patch that breaks TLS in some circumstances fixes another bug, and none is a vital breakage or impacts other formulas. So we'll just wait until the Xcode update and then bump to Iain's latest.
