### ISSUE TITLE
Homebrew not upgrading to most recent version of semgrep

### ISSUE THREAD

**Issue by AJAlmeida23** [Homebrew/homebrew-core#110672]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs semgrep
Error: No logs.

brew config
HOMEBREW_VERSION: 3.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6e2b162c4786e075323f038d46bfb566d91889e7
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f461e689821f463be722ffad671a0b459dff86ce
Core tap last commit: 20 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.32.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false

brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have to use semgrep on work and I had the version 0.111.1 installed via homebrew (brew install semgrep). When I ran it today it warned me that a new version existed, so I ran upgrade to version 0.111.1_1 (brew upgrade semgrep), still, for some reason, it keeps using version 0.111.1, even when I erase all files and try to reinstall it again.
Nonetheless, while reading semgrep documentation, I realised that there is actually a "newer" version (0.112.1), but in your source code (file semgrep.rb), the version you use is `tag:      "v0.111.1`.

I need to have semgrep as up to date as I can, so am I doing something wrong or can you fix your source code?

### What happened (include all command output)?

`brew install semgrep`
Warning: semgrep 0.111.1_1 is already installed and up-to-date.
To reinstall 0.111.1_1, run:
  `brew reinstall semgrep`
  
`semgrep --version`
0.111.1

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

### What did you expect to happen?

I expected semgrep to be updated to the most recent version (0.112.1).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install semgrep

brew upgrade semgrep
```

**Comment by SMillerDev** [comment]
Yes, that version is broken: https://github.com/Homebrew/homebrew-core/pull/109943

**Comment by AJAlmeida23** [comment]
Ok, thank you, will just have to wait for a patch then.
