### ISSUE TITLE
postgresql@9.5 is keg-only, but postgresql is not

### ISSUE THREAD

**Issue by haraldme** [Homebrew/homebrew-core#11072]
The recent import of postgresql@9.5 (and @9.4) formulae from homebrew-versions converted these to be "keg_only :versioned_formula".  This means that after upgrading, I'm suddenly left with no "psql" command (etc.) on PATH.

I think earlier versions of OSX had their own version of PostgreSQL, but that's apparently no longer the case on my machine (which is now on Sierra/10.12.3).  Additionally, the plain "postgresql" formula is NOT keg-only; I'd have thought that either none or all of the postgresql formulae ought to be keg-only.

So, why did the move of the 9.5 (and 9.4) formulae from homebrew-versions to homebrew-core convert them to be keg-only?  Is there any chance of reverting that change?  If not, how do I best go about putting a properly versioned PostgreSQL commands on my PATH -- "brew link --force"?

**Comment by fxcoudert** [comment]
Versioned formulas typically are keg-only, so that they can coexist with the non-versioned formula (which is, for example, installed as dependency by many other formulas).

`export PATH="/usr/local/Cellar/postgresql@9.5/9.5.6/bin:$PATH"` is your solution

**Comment by MikeMcQuaid** [comment]
> If not, how do I best go about putting a properly versioned PostgreSQL commands on my PATH -- "brew link --force"?

Yup or ideally: `export PATH="/usr/local/opt/postgresql@9.5/bin:$PATH` (@fxcoudert: note the `opt` paths are generally work recommending).

We're open to ideas on how to make it easier to add such things to your PATH or notify people more visibly that they are required.

**Comment by faucct** [comment]
> We're open to ideas on how to make it easier to add such things to your PATH or notify people more visibly that they are required.
That would be great.

**Comment by aviddiviner** [comment]
I ran `brew link --force postgresql@9.5`
