### ISSUE TITLE
broken utf-8 in mutt, neomutt, ncdu, weechat... (ncurses depended)

### ISSUE THREAD

**Issue by xsteadfastx** [Homebrew/homebrew-core#110812]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
OMEBREW_VERSION: 3.6.1-58-g7a14ae6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7a14ae61874770d9ceaee716f90e19c3b5674caa
Last commit: 60 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a511bc93c2c277337aa77b9e918fc3df9eeae516
Core tap last commit: 33 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BAT_THEME: Dracula
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 14.0.6
Git: 2.37.3 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-124-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.4 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: 2.35
gcc@11: 11.3.0
xorg: N/A
```
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  gcc@5
  isl@0.18
  libquvi
  quvi
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

i discovered that umlauts and other utf-8 characters doesnt show no more in, i think, ncurse based software. for me in neomutt, mutt and ncdu for example.

### What happened (include all command output)?

system ncdu:
![grafik](https://user-images.githubusercontent.com/168397/190468249-ce0ad2b6-0519-4d89-b2df-6ba6b46632eb.png)

brew ncdu:
![grafik](https://user-images.githubusercontent.com/168397/190468309-e3097c90-dc4d-4734-a534-8d79b8b8f1df.png)

i tested this without tmux, in tmux with alacritty and gnome-terminal. no problem with umlauts for like go based software like gopass.

### What did you expect to happen?

that this characters are shown.

### Step-by-step reproduction instructions (by running `brew` commands)

running mutt, neomutt or ncdu.

**Comment by carlocab** [comment]
Seem Linux-specific. Works for me on macOS.

<img width="1172" alt="Screenshot 2022-09-16 at 01 29 48" src="https://user-images.githubusercontent.com/30379873/190471480-bc9ecfa0-e3eb-46d5-840c-307bf01519ad.png">

**Comment by xsteadfastx** [comment]
another discovery... when reinstalling with `brew reinstall --build-from-source ncdu` the umlauts are back. 

![image](https://user-images.githubusercontent.com/168397/190478834-c216fa20-db4c-46d5-84bb-4dabcf02e62d.png)

```
ldd (which ncdu)
        linux-vdso.so.1 (0x00007ffc78521000)
        libncursesw.so.6 => /home/linuxbrew/.linuxbrew/Cellar/ncurses/6.3/lib/libncursesw.so.6 (0x00007f82ccc00000)
        libpthread.so.0 => /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/lib/libpthread.so.0 (0x00007f82ccf5e000)
        libc.so.6 => /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/lib/libc.so.6 (0x00007f82cc9ef000)
        /lib64/ld-linux-x86-64.so.2 => /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/lib64/ld-linux-x86-64.so.2 (0x00007f82ccf65000)
```

before and again broken when reinstalling without building from source

```
ldd (which ncdu)
        linux-vdso.so.1 (0x00007ffd07bbf000)
        libncursesw.so.6 => /home/linuxbrew/.linuxbrew/Cellar/ncurses/6.3/lib/libncursesw.so.6 (0x00007fbdd7400000)
        libpthread.so.0 => /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (0x00007fbdd7802000)
        libc.so.6 => /home/linuxbrew/.linuxbrew/lib/libc.so.6 (0x00007fbdd71ef000)
        /home/linuxbrew/.linuxbrew/lib/ld.so => /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/lib64/ld-linux-x86-64.so.2 (0x00007fbdd7809000
```

**Comment by xsteadfastx** [comment]
reinstalling neomutt from source doesnt fix anything.

**Comment by cho-m** [comment]
To confirm, was this working previously?

If so, I would guess it is related to recent Homebrew Linux migration. Perhaps using newer `glibc` 2.35 with `ncdu` bottle built with previous `glibc` 2.23.

Though `glibc` is supposed to be backwards compatible. Need someone more familiar with details to comment.

**Comment by danielnachun** [comment]
If it were a `glibc` ABI compatibility issue, the binaries would crash before even getting to this point.  All three of these affected packages depend on `ncurses`.  Can you try rebuilding that from source and see if that fixes the problems?  It's possible it needs a rebuild.

**Comment by cho-m** [comment]
I did a quick test on fresh Homebrew Ubuntu 20.04 container with only `brew install ncdu`. In the case that locale data exists, then I don't see any issue.

However, I am not sure if `glibc` correctly installs user's `LANG` due to Homebrew's environment:
https://github.com/Homebrew/homebrew-core/blob/da08bcf37f4a03216fe6ecd286c1b237de0b44cb/Formula/glibc.rb#L164-L167

Based on tests, I wasn't able to get `brew postinstall glibc` to pick up a non-US language like `LANG=de_DE.UTF-8`.

On side note, `LANG=en_US.UTF-8 ncdu` worked as it is always installed

**Comment by xsteadfastx** [comment]
Yes it worked. I had weechat and neomutt Opend for weeks. Worked fine. I upgrade brew a few times a day. After reopening neomutt this problem accures. As soon as iam on my computer i will check all your ideas. 

Am 16. September 2022 00:23:55 MESZ schrieb Michael Cho ***@***.***>:

**Comment by carlocab** [comment]
Probably needs this patch for `brew`
```diff
diff --git a/bin/brew b/bin/brew
index bfb14ca09..79754c843 100755
--- a/bin/brew
+++ b/bin/brew
@@ -84,7 +84,7 @@ HOMEBREW_LIBRARY="${HOMEBREW_REPOSITORY}/Library"
 
 # Copy and export all HOMEBREW_* variables previously mentioned in
 # manpage or used elsewhere by Homebrew.
-for VAR in BAT_THEME BROWSER DISPLAY EDITOR NO_COLOR TMUX DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR
+for VAR in BAT_THEME BROWSER DISPLAY EDITOR NO_COLOR TMUX DBUS_SESSION_BUS_ADDRESS XDG_RUNTIME_DIR LANG "${!LC_@}"
 do
   # Skip if variable value is empty.
   [[ -z "${!VAR}" ]] && continue
```
and this patch for `glibc.rb`
```diff
diff --git a/Formula/glibc.rb b/Formula/glibc.rb
index 7586de2c591..01690518aff 100644
--- a/Formula/glibc.rb
+++ b/Formula/glibc.rb
@@ -163,7 +163,7 @@ class Glibc < Formula
 
     # Get all extra installed locales from the system, except C locales
     locales = ENV.map do |k, v|
-      v if k[/^LANG$|^LC_/] && v != "C" && !v.start_with?("C.")
+      v if k[/^HOMEBREW_LANG$|^HOMEBREW_LC_/] && v != "C" && !v.start_with?("C.")
     end.compact
 
     # en_US.UTF-8 is required by gawk make check
```
After applying both patches, try `brew postinstall glibc` and see if that helps.

You may need to revert/restore the state of your Git repos to avoid issues with `brew update` in the future.

**Comment by xsteadfastx** [comment]
manually `export LC_ALL="en_US.UTF-8"` fixes it. it looks like the brew version of locale cant even set it.

could it be that its a locale mismatch? i mean i didnt updated my ubuntu for months now (yes i know...). the only thing i update is my brew stuff. if i run `locale` it uses the brew version and i get this error:

```
~ on  main [!] took 3s
❯ locale
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

~ on  main [!]
❯ locale -a
C
en_US.utf8
POSIX
```
```
~ on  main [!]
❯ /usr/bin/locale -a
C
C.UTF-8
de_DE.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX

~ on  main [!]
❯ /usr/bin/locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

```
no error message.

**Comment by carlocab** [comment]
Did you try the fix suggested [here](https://github.com/Homebrew/homebrew-core/issues/110812#issuecomment-1248936100)?

**Comment by xsteadfastx** [comment]
applied the patch but got errors

```
brew postinstall glibc
==> Postinstalling glibc
==> Installing locale data for de_DE.UTF-8 en_US.UTF-8 en_US.utf-8
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/bin/localedef -i de_DE -f UTF-8 de_DE.UTF-8
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
==> /home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/bin/localedef -i en_US -f utf-8 en_US.utf-8
Last 15 lines from /home/marv/.cache/Homebrew/Logs/glibc/post_install.03.localedef:
2022-09-16 08:54:25 +0200

/home/linuxbrew/.linuxbrew/Cellar/glibc/2.35/bin/localedef
-i
en_US
-f
utf-8
en_US.utf-8

failed to set locale!
[error] character map file `utf-8' not found: No such file or directory
failed to set locale!
[error] no output file produced because errors were issued
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall glibc
```

**Comment by xsteadfastx** [comment]
but it fixed it. brew version of `locale` doesnt threw errors no more:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```

**Comment by xsteadfastx** [comment]
but what went wrong? that it just didnt worked for me no more? is this a change that has to be permanent?

**Comment by xsteadfastx** [comment]
any news on this? this really looks like a bug to me.

**Comment by sisrfeng** [comment]
May be relevant : https://github.com/orgs/Homebrew/discussions/3682#discussioncomment-3829952
