### ISSUE TITLE
dbt 0.7.1 sierra bottle SHA is incorrect

### ISSUE THREAD

**Issue by cmcarthur** [Homebrew/homebrew-core#11113]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

When attempting to install dbt:

```
10:36 $ brew install dbt
==> Downloading https://homebrew.bintray.com/bottles/dbt-0.7.1.sierra.bottle.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ccb780cec3c5d0153ad6b549e28fb9d7fc6c26b4e100e330ff78c56e4dfa8915
Actual: 8c2bb62b47e9719c1190fe29ae189baf051fe3108af286f963ea4bb9182e3164
Archive: /Users/connor/Library/Caches/Homebrew/dbt-0.7.1.sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
```

`brew gist-logs dbt`:

https://gist.github.com/anonymous/d4e189ce7906b50e5aa8eaa27864d499

**Comment by fxcoudert** [comment]
I can confirm the actual sum :(

**Comment by dunn** [comment]
I'm getting the right SHA too.  Is this reproducible for you?  Are you behind a proxy?

**Comment by cmcarthur** [comment]
AHH this is totally my fault. I had a branch of homebrew/core checked out, and the brew bot had rebuilt dbt 0.7.1. Sorry to waste your time, I appreciate you looking into this.
