### ISSUE TITLE
Invalid INSTALL_NAME in protobuf executable

### ISSUE THREAD

**Issue by jeroen** [Homebrew/homebrew-core#11114]
The `protoc` utility from the `protobuf` package has an invalid `INSTALL_NAME`. Therefore it cannot find the shared libraries if these are not on the library path. This was not the case a few weeks ago.

![screen shot 2017-03-15 at 8 31 57 am](https://cloud.githubusercontent.com/assets/216319/23956575/39beaeb2-095a-11e7-96d8-ca11db6c0733.png)

It looks as if somehow the dir for `libprotobuf.12.dylib` is appended twice to the path.

The problem can be worked around by setting `DYLD_LIBRARY_PATH` to point to where the shared libs are located, however this should not be needed.

**Comment by raza15** [comment]
@jeroen can i have a look at this issue? I'm new to this project.

**Comment by ilovezfs** [comment]
It's not supported to install the HOMEBREW_PREFIX inside HOMEBREW_TEMP, which is /tmp by default.

**Comment by jeroen** [comment]
@ilovezfs can you elaborate please? Will installing in side another directory fix the problem? The default `/usr/local` is not an option in my case unfortunatly

**Comment by ilovezfs** [comment]
Yes. You can't use /tmp though unless you explicitly set HOMEBREW_TEMP to somewhere else. But you wouldn't want to anyway. macOS removes everything in /tmp during each boot.

**Comment by raza15** [comment]
@jeroen @ilovezfs can you guys please recommend me a issue that i can solve which could serve as my 1st PR to this project. I think this project is really awesome but i could not find any issues or new features that i can implement to get started with contributing to this project. Please help. Thanks!
