### ISSUE TITLE
gcc@12 overrides basic commands

### ISSUE THREAD

**Issue by mikhailkoliada** [Homebrew/homebrew-core#111236]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dual-core 64-bit haswell
Clang: 11.0.0
Git: 2.37.3 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.15.0-1019-azure x86_64 GNU/Linux
OS: Ubuntu 20.04.5 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: 2.35_1
gcc@11: N/A
gcc@12: 12.2.0
xorg: N/A


brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Our customer runs a code which invokes `gfortran`. It looks like brew-provided gfortran is not versioned, and as a result brew's provided command is used rather than the system-supplied one. More info can be found here: https://github.com/actions/runner-images/issues/6274

### What happened (include all command output)?

which -a gfortran

shows you brew gfortran

### What did you expect to happen?

system gfortran is used, not the brew's one

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gcc@12

which -a gfortran
```

**Comment by SMillerDev** [comment]
That is the designed behavior, Homebrew on Linux shadows system binaries by design.

**Comment by dawidd6** [comment]
Shouldn't versioned formulae be keg-only though? Here we have a case about `gcc@12`, so one could assume this is a versioned formula and should be keg-only, not shadowing anything.

**Comment by carlocab** [comment]
`gcc@12` is an alias for `gcc`.

You can just delete `"$(brew --prefix)/bin/gfortran"`. This is already what you do on macOS. See https://github.com/actions/runner-images/blob/ab475d3ed707b236b0042140faab1a326c7dbe54/images/macos/provision/core/gcc.sh#L10-L14.

**Comment by mikhailkoliada** [comment]
@carlocab oh!

Indeed, `brew ls -v gcc@12 | grep "/bin/"`

Shows that there is `gfortran` (symlink) and `gfortran-12`, could you please give me any hint why the symlink is needed here?

**Comment by SMillerDev** [comment]
Because `gcc == gcc@12`, so you should be able to call the unversioned gfortran too.

**Comment by carlocab** [comment]
> @carlocab oh!
> 
> Indeed, `brew ls -v gcc@12 | grep "/bin/"`
> 
> Shows that there is `gfortran` (symlink) and `gfortran-12`, could you please give me any hint why the symlink is needed here?

Because many of our builds look for Fortran as `gfortran`. Removing the symlink would break them.

**Comment by mikhailkoliada** [comment]
@carlocab thanks for the hint and sorry for the noise!

We have removed the gfortran's symlink from the images by now.
