### ISSUE TITLE
Latest Bottle for qt 6.3.1_4 failed to build for OS linux/5.15.0-1016-gcp/amd64

### ISSUE THREAD

**Issue by gzagatti** [Homebrew/homebrew-core#111317]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.2-10-ga6aab4b
ORIGIN: https://github.com/Homebrew/brew
HEAD: a6aab4b349a45f98cd2f2a80d9870e37bdbe3100
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 206b0381b058735431b0f65dba768fa4849db334
Core tap last commit: 49 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /home/linuxbrew/.linuxbrew/bin/nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0
Git: 2.37.3 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-47-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.1 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.2.0
/usr/bin/ruby: 3.0.2
glibc: 2.35_1
gcc@11: 11.3.0
gcc@12: 12.2.0
xorg: N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

To install formula `qt` when upgrading all Homebrew.

### What happened (include all command output)?

It was not possible to install `qt` from the bottle as the bottle for  `linux/5.15.0-1016-gcp/amd64` is not available, see [here](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fqt/42208153?tag=6.3.1_4). 

I tried to build `qt` from source which failed. It is likely that `qt` also failed to build in the CI.

### What did you expect to happen?

That `qt` installed from the bottle. `qt` takes a long time to build, so it's impractical to build it in the local machine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install qt
```

**Comment by SMillerDev** [comment]
I'm not sure what actionable issue there is here. Yes QT builds are slow, no it does not have a bottle.

**Comment by carlocab** [comment]
It does build, but the resulting build appears to be very broken and fails `brew test qt`.

We could use some help diagnosing and fixing the failure. See https://github.com/Homebrew/homebrew-core/pull/111031.

**Comment by gzagatti** [comment]
`brew` will throw an error if no bottle is available and on top of that it prints a message discouraging the user from installing from source as this modality "is unsupported". As such, I assumed that it was a bug and opened this pull request.

```
Error: qt: no bottle available!
You can try to install from source with:
  brew install --build-from-source qt
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

I have also noticed that `qt` version 6.3.1_3 has a bottle for `linux/5.15.0-1016-gcp/amd64` which you can see [here](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fqt/40512715?tag=6.3.1_3) which suggests that the lack of a bottle for version 6.3.1_4 is a bug of the build process.

Perhaps, I would suggest that when upgrading `brew` it should refrain from upgrading un-bottled Formulas to avoid disruption and then warn the user about that. This is not the first time that I have faced this type of issue. It can be quite disruptive when updating `brew` on your daily routine and especially for Formulas that need a lot of compilation and which are low-level dependencies for other Formulas.

In the particular case of this issue we need to solve #11031. I am afraid I don't know anything about `qt` to be of much help.

**Comment by carlocab** [comment]
This seems to be a `brew` bug. See Homebrew/brew#13922.

**Comment by iMichka** [comment]
We have built a bottle now. Is this working for you now?

**Comment by gzagatti** [comment]
I can confirm that `qt` version 6.4.0 now installs from bottle in my machine (Ubuntu 22.04) without any issues.
