### ISSUE TITLE
Fontforge formula missing woff2 dependency

### ISSUE THREAD

**Issue by ahankinson** [Homebrew/homebrew-core#111516]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (13.3.1) is outdated.
Please update to Xcode 13.4 (or delete it).
Xcode can be updated from the App Store.

❯ brew config
HOMEBREW_VERSION: 3.6.2-26-g4441452
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4441452f4e7a7efdd5ae8cc98466d8cf6fa410ab
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3393539591ba18d575b7cdf4cf65df9c59dae10a
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.5.1-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 13.3.1
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install fontforge with WOFF2 support, so that I can generate WOFF2 font files. I did this with `brew install fontforge`. 

By altering the formula to include `depends_on "woff2"` I was able to get the correct behaviour.

### What happened (include all command output)?

Installing the current version of fontforge (CLI-only), running the following does not work:

```
$ fontforge -lang=ff -
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-03-08 10:16 UTC-D.
> Open("/path/to/font/MyFont.otf")
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
> Generate("/path/to/font/MyFont.woff2")
```

### What did you expect to happen?

I expected this to generate a WOFF2 font. Instead, it generates a PostScript Type 1 font. I believe this is because the bottled version does not include a dependency on the `woff2` library (also available in Homebrew). 

### Step-by-step reproduction instructions (by running `brew` commands)

If I run `brew edit fontforge` and edit the formula in "homebrew-core" to include the line:

`depends_on "woff2"`

Then re-run:

`$ brew install fontforge -s`

Fontforge re-builds from source and correctly detects WOFF2 support. The above script now behaves as expected.

Could a dependency on `woff2` please be added to the fontforge formula for Homebrew Core?

**Comment by SMillerDev** [comment]
This is not a bug but a feature request and, as such, should be a pull request.
