### ISSUE TITLE
apt-cacher-ng broken

### ISSUE THREAD

**Issue by scotto** [Homebrew/homebrew-core#1120]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Formula Requests:

It looks like the version of apt-cacher-ng requested in the formula (0.8.8) doesn't currently exist on the specified servers.  There are older and new versions, but not this one.  I don't know enough about apt-cacher-ng to understand if this is as simple as updating the version, or if more is required.

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by scotto** [comment]
Sorry, sent that before finishing it, sorry!  Have edited above.

**Comment by DomT4** [comment]
This is a known issue [FWIW](https://github.com/Homebrew/legacy-homebrew/pull/49987). If you know anyone willing to fix it we'd love a PR.

**Comment by scotto** [comment]
OK, will work on it.  Thanks!

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
