### ISSUE TITLE
ffmbc - H.264 input files result in "Segmentation fault: 11"

### ISSUE THREAD

**Issue by ejolley** [Homebrew/homebrew-core#11218]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? 

ffmpeg installed with brew transcodes files fine.  This is specific to ffmbc.

### Bug reports:

After doing a fresh install of Homebrew and then "brew install ffmbc", I tried to use ffmbc to transcode a source file (the source file is H.264 codec).  This is the result:

> ffmbc -i /Users/eric/Desktop/test.mp4 /Users/eric/Desktop/output.mov
> FFmbc version 0.7.2
> Copyright (c) 2008-2014 Baptiste Coudurier and the FFmpeg developers
> Segmentation fault: 11

A second test with a source file (MPEG2 codec) succeeded in transcoding.  As did another source file which was encoded in the ProRes codec.  Encoding to H.264 is also not a problem.

However, any source file containing H.264 (.mov or mp4) always results in "Segmentation fault: 11"  This did not occur on earlier versions of ffmbc installed by Homebrew.

[Here](https://drive.google.com/open?id=0BwPGmvJ_ZaVQRGZqVlZfSU9PQkE) is an input file to reproduce the error.

------------------------------

> brew config
> HOMEBREW_VERSION: 1.1.11
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
> Last commit: 11 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 14c622931e08d41855d17f95f73df3ae98993a8c
> Core tap last commit: 56 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: 12-core 64-bit ivybridge
> Homebrew Ruby: 2.0.0-p648
> Clang: 8.0 build 800
> Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Perl: /usr/bin/perl
> Python: /usr/bin/python
> Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
> Java: 1.6.0_65-b14-468
> macOS: 10.11.6-x86_64
> Xcode: 8.2.1
> CLT: 8.2.0.0.1.1480973914
> X11: 2.7.9 => /opt/X11

------------------------------

> brew doctor
> Your system is ready to brew.

------------------------------

> brew gist-logs ffmbc
> Error: No logs.

**Comment by zmwangx** [comment]
I can reproduce the issue. The project seems to be in serious trouble though: hosted on Google Code, downloading from Google Drive... Wow...

Code appears to be hosted at https://github.com/bcoudurier/FFmbc now. README says stable version is 0.7.3, Changelog.FFmbc disagrees and says 0.7.5. Nevertheless, I can find neither a 0.7.3 tag (other than the old FFmpeg 0.7.3 tag) nor a download link anywhere. Is there a home page somewhere? No idea. Maybe commits updating the changelog should be treated as tags? Again, no idea.

You can try to compile from the master branch of https://github.com/bcoudurier/FFmbc. Seriously though, I'd recommend using FFmpeg instead if you can.

**Comment by ejolley** [comment]
I do use FFmpeg.  Unfortunately there's a few things FFmbc still does better than FFmpeg, especially if you're in television production.  Thanks for the verification.

**Comment by JCount** [comment]
The x264 library is only used in the encoding process, decoding is performed by an internal codec. To make certain that it is the x264 library at fault, could you attempt to transcode a H.264 file to a format such as MPEG-2 Part 2 or MPEG-4 Part 2. Thanks.

Sorry in advance if you have already done this.

**Comment by ejolley** [comment]
Ah, I didn't know it only did the encoding.  Perhaps that's not the issue then.  I can do those tests tomorrow.  Thanks.

**Comment by ejolley** [comment]
Actually, I already know the answer.  Any H.264 input file file results in a segmentation fault.  I can attempt the reverse, try to transcode an MPEG2 input file into H.264...
