### ISSUE TITLE
brew upgrade pulumi throws an Error: invalid attribute for formula 'pulumi/tap/pulumi': version ("")

### ISSUE THREAD

**Issue by basictheprogram** [Homebrew/homebrew-core#112439]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs pulumi
Error: invalid attribute for formula 'pulumi/tap/pulumi': version ("")
/opt/homebrew/Library/Homebrew/formula.rb:294:in `validate_attributes!'
/opt/homebrew/Library/Homebrew/formula.rb:219:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:307:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:307:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:468:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:560:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:608:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:581:in `from_rack'
/opt/homebrew/Library/Homebrew/formulary.rb:243:in `resolve'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:180:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:100:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:186:in `to_resolved_formulae'
/opt/homebrew/Library/Homebrew/cmd/gist-logs.rb:120:in `gist_logs'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrade pulumi it gave me a warning to upgrade.
```
warning: A new version of Pulumi is available. To upgrade from version '3.40.2' to '3.40.3', run 
   $ brew upgrade pulumi
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### What happened (include all command output)?

```
$ brew update
Already up-to-date.
$ brew upgrade pulumi
Error: invalid attribute for formula 'pulumi/tap/pulumi': version ("")
/opt/homebrew/Library/Homebrew/formula.rb:294:in `validate_attributes!'
/opt/homebrew/Library/Homebrew/formula.rb:219:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:307:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:307:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:468:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:560:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:608:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:581:in `from_rack'
/opt/homebrew/Library/Homebrew/formulary.rb:243:in `resolve'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:180:in `resolve_formula'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:100:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:57:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:56:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:77:in `to_formulae_to_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:191:in `to_resolved_formulae_to_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:107:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:95:in `<main>'
$ 
```

### What did you expect to happen?

Pulumi would be upgraded to 3.40.3

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew update
$ brew upgrade pulumi
```
```

**Comment by gromgit** [comment]
> Error: invalid attribute for formula 'pulumi/tap/pulumi': version ("")

That's a third-party tap, not Homebrew core. You'll have to report an issue there instead.
