### ISSUE TITLE
Cannot install PowerShell

### ISSUE THREAD

**Issue by DanielEIlie** [Homebrew/homebrew-core#112539]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew gist-logs openssl`
Error: openssl: /opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: syntax error, unexpected ..
../Formula/openssl@3.rb
^~
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: unknown regexp options - pl
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: `@3' is not allowed as an instance variable name

`brew config`
HOMEBREW_VERSION: 3.6.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 99682c5af3b48e7b37bf9c565781800153ee88fb
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 20a991bff175a2e7e89faf9fd9f4456163bce42f
Core tap last commit: 61 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

`brew doctor`
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I wanted to install PowerShell by executing:
`brew install --cask powershell`
The error occurs in the openssl formula.

### What happened (include all command output)?

==> Caveats
To use Homebrew in PowerShell, set:
  Add-Content -Path $PROFILE.CurrentUserAllHosts -Value '$(/opt/homebrew/bin/brew shellenv) | Invoke-Expression'

==> Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-7.2.6-osx-arm64.pkg
Already downloaded: /Users/n1614056/Library/Caches/Homebrew/downloads/c7abdb14cc0f4891bb6f3df9f8f2e8a39183df9add399b08688f1823a91262bc--powershell-7.2.6-osx-arm64.pkg
Error: openssl: /opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: syntax error, unexpected ..
../Formula/openssl@3.rb
^~
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: unknown regexp options - pl
/opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: `@3' is not allowed as an instance variable name

### What did you expect to happen?

Powershell to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew doctor
brew install --cask powershell
```

**Comment by gromgit** [comment]
```
Error: openssl: /opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: syntax error, unexpected ..
../Formula/openssl@3.rb
^~
```
That looks like a b0rked symbolic link. What's the output of `ls -l /opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases"?

**Comment by DanielEIlie** [comment]
> ls -l /opt/homebrew/Library/Taps/homebrew/homebrew-core/Aliases

Please see attached
[aliases.txt](https://github.com/Homebrew/homebrew-core/files/9733525/aliases.txt)

**Comment by DanielEIlie** [comment]
Thank you. That was the fix.

**Comment by carlocab** [comment]
We should probably make sure `core.symlinks` is not set for Homebrew repositories.
