### ISSUE TITLE
libwhy-test.pc from highway formulae breaks pkg-config

### ISSUE THREAD

**Issue by mikhailkoliada** [Homebrew/homebrew-core#112785]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d5b6b068c15a8df60f0f5e34a4ca80dcf82c48e3
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a1b61b0fec33a77423af06e132d396ba28296be0
Core tap last commit: 11 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 3-core 64-bit ivybridge
Clang: 14.0.0 build 1400
Git: 2.37.3 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.0.1 => /Applications/Xcode_14.0.1.app/Contents/Developer
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

The original ticket was reported to the GitHub Actions team (https://github.com/actions/runner-images/issues/6364)

Simple test revealed that `/usr/local/lib/pkgconfig/libhwy-test.pc` removal fixes the problem. This pkg-config file comes from the highway formulae, which, in turn, is a dependency of imagemagick (we are installing imagemagick to macOS runners).
I also noticed that compiling highway from scratch also bring the problem back, so formally it myst go directly to upstream, but in the formulae I see these files are being [overwritten](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/highway.rb#L21) by the `jpeg-xl` formula so I di nit know who is the real culprit.

NB: I see this problem exists only on the Big Sur and Monterey runners, Catalina seems to be unaffected.

### What happened (include all command output)?

/Users/runner/work/_temp/51c71d4c-af30-4e69-826a-37bc32455a38.sh: line 8: 23019 Segmentation fault: 11  pkg-config --list-all

### What did you expect to happen?

no segfault, list all available modules

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install imagemagick
pkg-config --list-all

OR

brew install highway
pkg-config --list-all
```

**Comment by SMillerDev** [comment]
If it also happens when compiled from source it should probably be reported upstream instead.

**Comment by mikhailkoliada** [comment]
@SMillerDev true that but:

1. at which upstream exactly? (jpeg-xl, highway, both?)
2. do not want brew to fix it locally in a formulae/formula? (though I do not know if it is a case to be fixed)

**Comment by SMillerDev** [comment]
1. The link overwrite just means that if you still have those files brew can assign them to highway so that's the upstream those files now come from
2. Brew only ships fixes that have been submitted and accepted upstream.

**Comment by mikhailkoliada** [comment]
@SMillerDev ah ok, now I see, lets report it upstream then, I will CC you if you are not minding as I think brew might be interested in getting a fix too.

**Comment by Bo98** [comment]
Looks like it's already fixed upstream: https://github.com/google/highway/commit/357e21beabb1af037f20130b4195fa5d0e6bbbfb

We can apply this patch to the formula.
