### ISSUE TITLE
MYSQL not supported

### ISSUE THREAD

**Issue by Brettk80** [Homebrew/homebrew-core#112796]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: fb52a12144e80118c112ea744ab65ab6ca997d67
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5fb25bb5e8674bb53fa8837fde24acad40d90503
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.JBjR5rM24j/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installed gal, couldnt add --with-mysql like older versions.
Doesnt install mysql driver

### What happened (include all command output)?

Normal installation

### What did you expect to happen?

Normal installation with MYSQL driver

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gdal --with-mysql   Error: invalid option: --with-mysql
brew install gdal     results in no mysql driver installation
```

**Comment by SMillerDev** [comment]
That option was removed 4 years ago. If you want to modify your installation options you'll have to `brew extract` and maintain the formulas in a personal tap.
