### ISSUE TITLE
Some "@" formulas don't have un-@-ed names

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#11279]
Some formulas with "@" in their name don't have a corresponding formula with no "@".  This means that if you see e.g., `play@1.4` and wonder "huh, I wonder what `play` is" and do `brew desc play` or `brew edit play` you will get:
```
Error: No available formula with the name "play"
```
The same is true of two others:
```
Error: No available formula with the name "gst-ffmpeg"
Error: No available formula with the name "hdf"
```
I think this is subpar UX.  There shouldn't be an `x@n.m` unless there is a plain `x`, even if that plain `x` is an alias or a dummy formula or some such construction.

Also, for some reason `brew info play` will return some information, but `brew info [hdf | gst-ffmpeg]` just gives the "No available formula" error.

**Comment by MikeMcQuaid** [comment]
> I think this is subpar UX. There shouldn't be an x@n.m unless there is a plain x, even if that plain x is an alias or a dummy formula or some such construction.

I agree. These should all be deleted and this is my fault for not checking them before creating import PRs.

**Comment by ilovezfs** [comment]
"gst-ffmpeg" was renamed `gst-libav` so it could be an @ of that I guess ...
