### ISSUE TITLE
Python3 failed to build on 10.11

### ISSUE THREAD

**Issue by omni-vi** [Homebrew/homebrew-core#11275]
python3 fails to build on 10.11 due to problems with quicktest:

### short output:
FAILED (failures=1, skipped=1)
2 tests failed again:
    test_platform test_popen

Total duration: 1 min 52 sec
Tests result: FAILURE
make: *** [quicktest] Error 1

### complete output:
https://gist.github.com/0eb524a367bda3a2d05d78c6e88cc231

I did:
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] Confirmed this is a problem with specific formulae and not Homebrew/brew?

**Comment by ilovezfs** [comment]
I'd suggest not passing `--with-quicktest` then.

**Comment by omni-vi** [comment]
Isn't quicktest supposed to work?

**Comment by ilovezfs** [comment]
Probably. You'd have to take that up with upstream.

**Comment by omni-vi** [comment]
Ok, thanks.

**Comment by ilovezfs** [comment]
You're welcome.
