### ISSUE TITLE
Unable to install pkg-config with a fresh linuxbrew, "C compiler cannot create executables"

### ISSUE THREAD

**Issue by quasus** [Homebrew/homebrew-core#11289]
I install Linuxbrew using the command

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"

copied from the home page and I update environmental variables.  I install GCC, so far so good.  Then I try to install pkg-config and the installation fails with

    configure: error: C compiler cannot create executables

Logs: https://gist.github.com/anonymous/4fa2ab670632fe467f8e92ba9b8f9f08

**Comment by JCount** [comment]
This issue needs to be filed over at Linuxbrew, they are the ones who will best be able to help you. https://github.com/Linuxbrew/homebrew-core/issues should be the place.
