### ISSUE TITLE
HB Homebrew JK Jekyll RE: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by rwebaz** [Homebrew/homebrew-core#11290]
Hello: 

RE: Confirmed this is a problem with specific formulae and not Homebrew/brew?

RE: If it's a general Homebrew/brew problem please file this issue at:

https://github.com/Homebrew/brew/issues/new

Response: I think I will file this issue here and at the link provided above.

Why? Because the issue may be with a Ruby install, a Jekyll install via Ruby Gem, or a tool.

And, when I can't get my Jekyll server to run locally on my development machine, how am I to submit code to the GitHub server that has not been run locally and confirmed?

C=> https://gist.github.com/rwebaz/64330b2f5a37f857a27a59075d55dac7

Robert

P.S. The above link is to a 'private' GIST ... unless, of course you would prefer a public gist that is followed by the search engines;

**Comment by MikeMcQuaid** [comment]
Please don't file the same issue in multiple places.

**Comment by rwebaz** [comment]
Ok, Mike ... Thx for your rapid response ( and, closure ). Robert.
