### ISSUE TITLE
Problem with "speedcrunch"

### ISSUE THREAD

**Issue by ticktockhouse** [Homebrew/homebrew-core#11304]
I get the following when attempting to install speedcrunch via Homebrew:

==> brew cask install Caskroom/cask/speedcrunch
==> Downloading https://bitbucket.org/heldercorreia/speedcrunch/downloads/SpeedCrunch-0.12.dmg
Already downloaded: /Users/jsteele/Library/Caches/Homebrew/Cask/speedcrunch--0.12.dmg
==> Verifying checksum for Cask speedcrunch
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 1c513acd0db375e079f47055f5903b538361fdd2ebf62d09bd3e876cb7513a94
Actual: 09a881ef4e5d8ee37f90b5291544fcabeb28c63bc57e6e5eabbd748e09c975be
File: /Users/jsteele/Library/Caches/Homebrew/Cask/speedcrunch--0.12.dmg
To retry an incomplete download, remove the file above.

Seems like a simple case of the incorrect checksum being entered somewhere, but not sure how to solve it.

Apologies if this is not the correct place to report this..

Thanks in advance

**Comment by fxcoudert** [comment]
Can you please report this at [Homebrew Cask](https://github.com/caskroom/homebrew-cask/issues)? Thanks
