### ISSUE TITLE
New libomp 15.0.2 doesn't work

### ISSUE THREAD

**Issue by BrushXue** [Homebrew/homebrew-core#113176]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.5-42-g34979a3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 34979a33d32f4074b34cab9113e4bd04ccdbe299
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8f02c71a7f17c21a849cc143ccf7d22702443941
Core tap last commit: 15 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to compile something with `libomp`. The code has been working normally for many years but the recent `libomp` update is broken.

### What happened (include all command output)?

When using 15.0.2:
```
wmake kahipDecomp
    link: /Users/gux215/OpenFOAM/OpenFOAM-v2206/platforms/darwin64ClangDPInt32Opt/lib/libkahipDecomp.dylib
ld: library not found for -lomp
```

### What did you expect to happen?

If I install 14.0.6 manually:
```
wmake kahipDecomp
(passed)
```
I never had any issue before v15.

### Step-by-step reproduction instructions (by running `brew` commands)

It's hard to reproduce unless you want to compile the whole OpenFOAM.
I suggest rollback to v14 until v15 has been fully tested.

**Comment by BrushXue** [comment]
Sorry didn't realize you made it keg-only recently. https://github.com/Homebrew/homebrew-core/issues/112107

**Comment by BrushXue** [comment]
This is definitely not a right approach because many working code is not working anymore...

**Comment by carlocab** [comment]
Do `brew link --force libomp`.
