### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by kdheepak89** [Homebrew/homebrew-core#1131]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew update` twice.
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

I get the following error when trying to install graphviz.

    brew reinstall graphviz --with-gts
    ==> Reinstalling graphviz with --with-gts
    ==> Downloading http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz
    Already downloaded: /Library/Caches/Homebrew/graphviz-2.38.0.tar.gz
    ==> Downloading https://raw.githubusercontent.com/Homebrew/patches/ec8d133/graphviz/patch-project.pbxproj.diff
    Already downloaded: /Library/Caches/Homebrew/graphviz--patch-7c8d5c2fd475f07de4ca3a4340d722f472362615a369dd3f8524021306605684.diff
    ==> Patching
    ==> Applying patch-project.pbxproj.diff
    patching file macosx/graphviz.xcodeproj/project.pbxproj
    ==> ./configure --prefix=/usr/local/Cellar/graphviz/2.38.0 --without-qt --with-quartz --with-gts --disable-swig --without-pangocairo --without-freetype2 --without-x --without-rsvg
    ==> make install
    Last 15 lines from /Users/$USER/Library/Logs/Homebrew/graphviz/02.make:
          _gvwrite in gvdevice.o
      "_deflate", referenced from:
          _gvwrite in gvdevice.o
          _gvdevice_finalize in gvdevice.o
      "_deflateEnd", referenced from:
          _gvdevice_finalize in gvdevice.o
      "_deflateInit2_", referenced from:
          _gvdevice_initialize in gvdevice.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[3]: *** [libgvc.la] Error 1
    make[3]: *** Waiting for unfinished jobs....
    make[2]: *** [install-recursive] Error 1
    make[1]: *** [install-recursive] Error 1
    make: *** [install] Error 2

    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/brew):
      https://github.com/Homebrew/homebrew-core/issues

Any thoughts on how to proceed with debugging this? The full gist-logs for the command `brew gist-logs graphviz --with-gts` are [here](https://gist.github.com/kdheepak89/7a60e6c3dd6e420b74fddecd953ac215).

**Comment by DomT4** [comment]
I'd be tempted to put money on:

> Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
MacVim, due to bundling many duplicates of system and Homebrew-available
tools.

> If you encounter a build failure please temporarily remove Anaconda
from your $PATH and attempt the build again prior to reporting the
failure to us. Thanks!

**Comment by kdheepak89** [comment]
Hi @DomT4, I tried moving Anaconda to a different location and still received the same error.

**Comment by ilovezfs** [comment]
The problem is the libz in the doctor errors.
```
    /usr/local/lib/libz.1.2.5.dylib
    /usr/local/lib/libz.1.dylib
    /usr/local/lib/libz.dylib
```

**Comment by kdheepak89** [comment]
I deleted those files and I think that worked. I'm getting a different error now, which seems to be a error caused by permissions. I'll close this now. Thanks!

**Comment by ilovezfs** [comment]
You're welcome.

**Comment by DomT4** [comment]
Thanks @ilovezfs, you cycled back round to this issue faster than I managed to 😄.

**Comment by ilovezfs** [comment]
You're welcome. It gave me an excuse to use nm:
```
Josephs-MacBook-Pro:~ joe$ nm /usr/lib/libz.dylib|grep defl
0000000000001dcc T _deflate
0000000000002c95 T _deflateBound
0000000000002df3 T _deflateCopy
00000000000018bb T _deflateEnd
00000000000015ff T _deflateInit2_
00000000000015d1 T _deflateInit_
0000000000001cd9 T _deflateParams
0000000000001c97 T _deflatePrime
00000000000019b4 T _deflateReset
0000000000001b27 T _deflateSetDictionary
0000000000001c68 T _deflateSetHeader
0000000000002c5c T _deflateTune
```
