### ISSUE TITLE
Include a man page in Formula?

### ISSUE THREAD

**Issue by chrisfinazzo** [Homebrew/homebrew-core#1133]
### Formula Request: Chext

I would like to add [this][] utility to Homebrew but am unsure how to proceed. I have communicated with the original author who indicated that in addition to the main executable, a  man page should be included. Do instructions exist within `brew create` which describe how this should be integrated?

[this]: https://github.com/joe-antognini/chext

**Comment by ilovezfs** [comment]
This won't pass audit due to
```
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
```

Typically it would be integrated using `make install` but if one isn't available `man1.install ...`

**Comment by chrisfinazzo** [comment]
Fair enough. As it's something that he still would like to do, I'll keep this local for now.
