### ISSUE TITLE
ghostscript could not symlink (conflict with MacTeX)

### ISSUE THREAD

**Issue by earthflat** [Homebrew/homebrew-core#11368]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

Installing/updating ghostscript builds but gives an error that it could not symlink into /usr/local. 'brew gist-logs ghostscript' gives an error: 'No logs.'. 'brew config', 'brew doctor' and the 'brew reinstall ghostscript' error message are provided below.
I strongly assume a conflict with the MacTeX distribution which is installed via Homebrew Cask. MacTeX apparently installed its own /usr/local/bin/dvipdf which now conflicts with brew's linking of the same.
A related issue was already discussed, but it is closed and no solution has been presented:
https://github.com/Homebrew/homebrew-core/issues/4732 

**brew reinstall ghostscript:**

`mac:~ user$ brew reinstall ghostscript
==> Reinstalling ghostscript 
==> Downloading https://homebrew.bintray.com/bottles/ghostscript-9.21.sierra.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/ghostscript-9.21.sierra.bottle.tar.gz
==> Pouring ghostscript-9.21.sierra.bottle.tar.gz

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/dvipdf
Target /usr/local/bin/dvipdf
already exists. You may want to remove it:
  rm '/usr/local/bin/dvipdf'

To force the link and overwrite all conflicting files:
  brew link --overwrite ghostscript

To list all files that would be deleted:
  brew link --overwrite --dry-run ghostscript

Possible conflicting files are:
/usr/local/bin/dvipdf
/usr/local/bin/eps2eps
/usr/local/bin/font2c
/usr/local/bin/gs -> /usr/local/bin/gs-X11
/usr/local/bin/gsbj
/usr/local/bin/gsdj
/usr/local/bin/gsdj500
/usr/local/bin/gslj
/usr/local/bin/gslp
/usr/local/bin/gsnd
/usr/local/bin/lprsetup.sh
/usr/local/bin/pdf2dsc
/usr/local/bin/pdf2ps
/usr/local/bin/pf2afm
/usr/local/bin/pfbtopfa
/usr/local/bin/pphs
/usr/local/bin/printafm
/usr/local/bin/ps2ascii
/usr/local/bin/ps2epsi
/usr/local/bin/ps2pdf
/usr/local/bin/ps2pdf12
/usr/local/bin/ps2pdf13
/usr/local/bin/ps2pdf14
/usr/local/bin/ps2pdfwr
/usr/local/bin/ps2ps
/usr/local/bin/ps2ps2
/usr/local/bin/unix-lpr.sh
/usr/local/bin/wftopfa
/usr/local/share/man/man1/dvipdf.1
/usr/local/share/man/man1/eps2eps.1 -> /usr/local/share/man/man1/ps2ps.1
/usr/local/share/man/man1/font2c.1
/usr/local/share/man/man1/gs.1
/usr/local/share/man/man1/gsbj.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gsdj.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gsdj500.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gslj.1 -> /usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gslp.1
/usr/local/share/man/man1/gsnd.1
/usr/local/share/man/man1/pdf2dsc.1
/usr/local/share/man/man1/pdf2ps.1
/usr/local/share/man/man1/pf2afm.1
/usr/local/share/man/man1/pfbtopfa.1
/usr/local/share/man/man1/printafm.1
/usr/local/share/man/man1/ps2ascii.1
/usr/local/share/man/man1/ps2epsi.1
/usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdf12.1 -> /usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdf13.1 -> /usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdf14.1 -> /usr/local/share/man/man1/ps2pdf.1
/usr/local/share/man/man1/ps2pdfwr.1
/usr/local/share/man/man1/ps2ps.1
/usr/local/share/man/man1/wftopfa.1
==> Summary
🍺  /usr/local/Cellar/ghostscript/9.21: 717 files, 64.2MB`

**brew config:**

`mac:~ user$ brew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 75c87b33f7454181bd37f427156b8a57e00b4507
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111, 1.8.0_101
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
`

**brew doctor:**

`mac:~ user$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/user/Software/pdal/pdal_1-4-0/py35/bin/pdal-config
  /Users/user/anaconda/bin/curl-config
  /Users/user/anaconda/bin/freetype-config
  /Users/user/anaconda/bin/glue-config
  /Users/user/anaconda/bin/icu-config
  /Users/user/anaconda/bin/libdynd-config
  /Users/user/anaconda/bin/libpng-config
  /Users/user/anaconda/bin/libpng16-config
  /Users/user/anaconda/bin/python3-config
  /Users/user/anaconda/bin/python3.5-config
  /Users/user/anaconda/bin/python3.5m-config
  /Users/user/anaconda/bin/xml2-config
  /Users/user/anaconda/bin/xslt-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
`

**Comment by fxcoudert** [comment]
Homebrew does indeed conflict with ghostscript as installed by MacTex. There is not much we can do here, apart from what we already do: tell the user that this is the case, do the next best thing (i.e. install but not link into `/usr/local`, provide an option to overwrite existing files (`brew link --overwrite ghostscript`).

You could also reinstall MacTex without ghostscript (it works well, as their documentation explicitly state), and the run `brew reinstall ghostscript`).

**Comment by chdiza** [comment]
If one is already using Homebrew, MacTeX is pointless.  Just use a straight TeXLive install and `brew install` anything else you need, like `ghostscript`.
