### ISSUE TITLE
MacOS error: -67062 (security exception)

### ISSUE THREAD

**Issue by fabianishere** [Homebrew/homebrew-core#11378]
Multiple packages installed by Homebrew (like `coreutils`, `python`, `tmux-mem-cpu-load`, `vim`) cause the Console to be filled with the error "MacOS error: -67062" from processes like `taskgated`, `lsd` and `socketfilterfw` when binaries from the package are executed.

- [X] Ran `brew update` and retried your prior step?
```
$ brew update
Already up-to-date.
```

- [X] Ran `brew doctor`.
```sh
$ brew doctor
Your system is ready to brew.
```

- [X]  Ran `brew config`.
```sh
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b0a8468bfeab9b147ec5e8a311557a17d1e4722e
Core tap last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

Reproducing:
1. `brew install tmux-mem-cpu-load`
2. `tmux-mem-cpu-load`
3. In Console, the error "MacOS error: -67062" from `taskgated` is logged.

This happens on a clean install of Sierra.

**Comment by fabianishere** [comment]
Signing the binaries fixes the problem, but this requires you to sign every binary you install:
```sh 
$ codesign -dvvv $(which vim)
/usr/local/bin/vim: code object is not signed at all

$ vim # (error is logged to Console)
$ codesign -f -s - $(which vim)
$ vim # (no error is logged to Console)
$ codesign -dvvv $(which vim)

Executable=/usr/local/Cellar/vim/8.0.0495/bin/vim
Identifier=vim-55554944f42c16a0ac473581a57e9f311d78b69c
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=17565 flags=0x2(adhoc) hashes=544+2 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=fc9110288f07b4dddfb250eeffe041c347c33b4f
Hash choices=sha256
CDHash=fc9110288f07b4dddfb250eeffe041c347c33b4f
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12
```

Should all binaries installed by Homebrew have to be signed?

**Comment by DomT4** [comment]
> Should all binaries installed by Homebrew have to be signed?

No. This error seems to be a fairly common [one](https://discussions.apple.com/thread/7705551?start=0&tstart=0). Are you running any anti-virus software?

**Comment by fabianishere** [comment]
@DomT4 I can reproduce this on a clean Sierra install. Is it possible this is hardware related?

**Comment by DomT4** [comment]
Interesting. I know people have had issues with that error code, but I've never seen those issues limited exclusively to Homebrew, and I can't remember anyone walking through a fix either 😓.

> I can reproduce this on a clean Sierra install.

Is this on a different machine or the same machine?

**Comment by fabianishere** [comment]
> Is this on a different machine or the same machine?
The same machine. Also, I tried it on a clean Parallels VM and then I got the followimg error:

**Comment by JCount** [comment]
What is the message type in the console?

**Comment by fabianishere** [comment]
> What is the message type in the console?

It shows no type in the console. That column is empty.

**Comment by fabianishere** [comment]
I suspect this may be hardware related, as calling `ifconfig` also results in multiple errors from `socketfilterfw`:

```
socketfilterfw - MacOS error: -67065
socketfilterfw - UNIX error exception: 3
```

**Comment by MikeMcQuaid** [comment]
Given this, closing but thanks anyway.

**Comment by CamJN** [comment]
I'm seeing this as well, 100% original hardware and no hw faults that I'm aware of. I get approx. 150 messages per second every few minutes because of this.

I'm more than happy to help investigate if people want.

**Comment by fabianishere** [comment]
I think this is a bug in Sierra. I get these errors on all my Sierra devices (even on devices of my friends). Running '''sh
$ ifconfig
''' in the terminal is enough to trigger an error/exception in Console.

**Comment by gordol** [comment]
Are any of y'all having hard-locks also? I'm seeing these errors too, and trying to figure out if these are related to the freezes and constant beachballs...

**Comment by fabianishere** [comment]
Nope, my main issue was the console getting spammed.
