### ISSUE TITLE
`gnu-smalltalk`: no bottle available!

### ISSUE THREAD

**Issue by callumfrance** [Homebrew/homebrew-core#113868]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 3.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 978a452ea7ccdff1ed7377f88add3ff0513ba2b7
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1282a13f2286bb22ea70c2d08f82de635905bb5e
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false
➜  ~
➜  ~ brew doctor
Your system is ready to brew.
➜  ~
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install `gnu-smalltalk` so I can write [smalltalk programs](https://www.gnu.org/software/smalltalk/).

### What happened (include all command output)?

➜  ~ brew install gnu-smalltalk
Error: gnu-smalltalk: no bottle available!
You can try to install from source with:
  brew install --build-from-source gnu-smalltalk
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
➜  ~

### What did you expect to happen?

A successful install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
➜  ~ brew install gnu-smalltalk
```

**Comment by dawidd6** [comment]
There is no bottle for any ARM macOS versions, dispatched build: https://github.com/Homebrew/homebrew-core/actions/runs/3311282213. Let's see what the build failures are.

**Comment by dawidd6** [comment]
```
  ld: the target architecture doesn't support executable stacks
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by carlocab** [comment]
`gnu-smalltalk` does not work on ARM.
