### ISSUE TITLE
macOS 13 (Ventura) and gcc-12

### ISSUE THREAD

**Issue by paulmadejong** [Homebrew/homebrew-core#113968]
###  `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.6.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a7eac25e167a1eb2d49e13c8cc530a3188af995
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a1aad54d0a8f1b2ae23636612035637abca76740
Core tap last commit: 58 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Y31wpy2j1d/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.3 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.0.1
Rosetta 2: false

brew doctor:
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.1.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  szip


Warning: Your Command Line Tools (CLT) does not support macOS 13.
It is either outdated or was modified.
Please update your Command Line Tools (CLT) or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.1.


Warning: Your Xcode (14.0.1) is too outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (14.0.1) is outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to build a Cython module in macOS 13 and gcc-12 (12.2.0). However, the headers are not found since gcc assumes that macOS 13 SDK is available (found through `gcc -v`, see below). This SDK is still in beta afaik so how can I resolve this?

Also note that 'brew doctor' warns to upgrade Xcode to 14.1 and the CLT however, these are both still in beta. So what should be done when one is not an Apple Developer and hence, how to resolve the brew doctor warning?

### What happened (include all command output)?

```
gcc-12 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Volumes/projects/git/mode-s.oper/src/decodeADSB -I/Volumes/projects/git/mode-s.oper/include -I/Volumes/projects/git/mode-s.oper/buildDebug -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /Volumes/projects/git/mode-s.oper/src/decodeADSB/pydecodeADSB.c -o build/temp.macosx-13-arm64-cpython-39/Volumes/projects/git/mode-s.oper/src/decodeADSB/pydecodeADSB.o
      In file included from /opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin22/12/include-fixed/syslimits.h:7,
                       from /opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin22/12/include-fixed/limits.h:34,
                       from /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/Python.h:11,
                       from /Volumes/projects/git/mode-s.oper/src/decodeADSB/pydecodeADSB.c:36:
      /opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin22/12/include-fixed/limits.h:203:75: error: no include path in which to search for limits.h
        203 | #include_next <limits.h>                /* recurse down to the real one */
            |                                                                           ^
      In file included from /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9/Python.h:25:
      /opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin22/12/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
         78 | #include <_stdio.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/opt/homebrew/bin/gcc-12' failed with exit code 1
```

### What did you expect to happen?

Successful compilation

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
gcc-12 -v output:
Using built-in specs.
COLLECT_GCC=gcc-12
COLLECT_LTO_WRAPPER=/opt/homebrew/Cellar/gcc/12.2.0/bin/../libexec/gcc/aarch64-apple-darwin22/12/lto-wrapper
Target: aarch64-apple-darwin22
Configured with: ../configure --prefix=/opt/homebrew/opt/gcc --libdir=/opt/homebrew/opt/gcc/lib/gcc/current --disable-nls --enable-checking=release --with-gcc-major-version-only --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-12 --with-gmp=/opt/homebrew/opt/gmp --with-mpfr=/opt/homebrew/opt/mpfr --with-mpc=/opt/homebrew/opt/libmpc --with-isl=/opt/homebrew/opt/isl --with-zstd=/opt/homebrew/opt/zstd --with-pkgversion='Homebrew GCC 12.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --with-system-zlib --build=aarch64-apple-darwin22 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Homebrew GCC 12.2.0)
```
Note the ` --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk` in gcc-12 output which is not available on my machine nor is it fully released AFAIK?

**Comment by Bo98** [comment]
> Note the --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk in gcc-12 output which is not available on my machine nor is it fully released AFAIK?

The SDK was supposed to be released at the same time but a last minute issue caused RC 2 to be released instead. This surprised us as well, as that has never happened before.

We don't support development tools without a matching SDK so you'll need to install Command Line Tools for Xcode RC 2 from developer.apple.com or wait for it to be released, which is hopefully very soon.

**Comment by paulmadejong** [comment]
Thanks for the answer. For those running into these issues, instead of using Xcode 14.1 RC 2, you can also just download the SDK here: https://developer.apple.com/download/all/

**Comment by vandit2209** [comment]
> Thanks for the answer. For those running into these issues, instead of using Xcode 14.1 RC 2, you can also just download the SDK here: https://developer.apple.com/download/all/

what version to download instead?

```
Configured with: ../configure --prefix=/opt/homebrew/opt/gcc --libdir=/opt/homebrew/opt/gcc/lib/gcc/current --disable-nls --enable-checking=release --with-gcc-major-version-only --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-12 --with-gmp=/opt/homebrew/opt/gmp --with-mpfr=/opt/homebrew/opt/mpfr --with-mpc=/opt/homebrew/opt/libmpc --with-isl=/opt/homebrew/opt/isl --with-zstd=/opt/homebrew/opt/zstd --with-pkgversion='Homebrew GCC 12.2.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --with-system-zlib --build=aarch64-apple-darwin21 --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
```
Mine `--with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk`

**Comment by Bo98** [comment]
14.1 RC 2 should still contain the macOS 12 SDK if you need that.

**Comment by kenju** [comment]
For those who encounter the similar issue, let me share few more tips to solve this.

As @paulmadejong suggets, you'll have to download Command Line Tools for XCode 14.1 Release Candidate 2 from https://developer.apple.com/download/all/

<img width="731" alt="Screenshot 2022-10-31 at 15 16 30" src="https://user-images.githubusercontent.com/4186381/199043011-6bd33df9-847d-487f-9bb9-37244d6c1336.png">

Once you download and installed the tools, you'll find that command line tools are installed at `/Library/Developer/CommandLineTools/usr/bin` directory.

```
 ls -l /Library/Developer/CommandLineTools/usr/bin/ | wc -l
     114
```

Especially, you'll find `clang` there.

```
$ /Library/Developer/CommandLineTools/usr/bin/clang -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

That might be linked to `/usr/bin/clang` now, if set the path manually.

```
$ /usr/bin/clang -v
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Bo98** [comment]
You might have Xcode 14.1, but you definitely don't have "Command Line Tools for Xcode 14.1".

**Comment by zerobytes** [comment]
You're right. 
Just downloaded the command line individually and installed. Now it seems to be running.
Thank you @Bo98

**Comment by shish** [comment]
> you'll need to install Command Line Tools for Xcode RC 2 from developer.apple.com (free - doesn't require to be in the paid program) or wait for it to be released, which is hopefully very soon.

Looks like a week later it's still not released, and https://developer.apple.com/download/all/ redirects me to https://developer.apple.com/account/ with a "Join the Apple Developer Program" prompt :(

Has anyone managed to download the command line tools without joining the program, if so is there some other link to it that I'm just not seeing?

**Comment by carlocab** [comment]
You'll need to register to download it, unfortunately. Registration is free, however.

**Comment by shish** [comment]
Aha, it appears to be a browser-based issue??

- I am registered and signed in with my (free) Apple ID, but not registered for the (paid) Apple Developer Program.
- When I open the page, logged in with my Apple ID, in Chrome - it redirects me to sign up for the paid program.
- When I open the page, logged in with my Apple ID, in Safari - it lets me download the command line tools.

Sorry for the noise in this discussion thread, but maybe the hint of "try downloading using Safari" will be helpful for somebody :)

**Comment by eo1989** [comment]
The gcc-12 issue also shows up on linuxbrew, is there a way to fix it on linux?

**Comment by Bo98** [comment]
> The gcc-12 issue also shows up on linuxbrew, is there a way to fix it on linux?

If you're having this issue on Linux, you will have a different issue. Open a separate discussion about that.

macOS SDKs aren't involved with GCC on Linux.
