### ISSUE TITLE
Zig panics on Ventura

### ISSUE THREAD

**Issue by anatol** [Homebrew/homebrew-core#113978]
:x: @fxcoudert bottle request for zig [failed](https://github.com/Homebrew/homebrew-core/actions/runs/3314759137).

`thread 18115 panic: Darwin is handled separately via std.zig.system.darwin module`

_Originally posted by @BrewTestBot in https://github.com/Homebrew/homebrew-core/issues/113717#issuecomment-1289381614_

Here is an upstream issue to track Zig+Ventura development https://github.com/ziglang/zig/issues/10478

**Comment by Bo98** [comment]
Interesting, I'm guessing Zig not using the SDK is intentional?

**Comment by anatol** [comment]
cc @jedisct1 to help with this question

**Comment by Bo98** [comment]
Or maybe it's not and it was was fixed by https://github.com/ziglang/zig/commit/aec0e595f2a679f10e927ea4531b8f58ced7080a. Haven't updated to macOS 13 myself yet.

**Comment by natecraddock** [comment]
There is a PR to update Zig for Ventura https://github.com/ziglang/zig/pull/13299

**Comment by carlocab** [comment]
Lots of formulae don't build yet on Ventura. We don't need a separate open issue to track individual ones.

**Comment by anatol** [comment]
fyi the original issue #113717 does not allow me to comment there. The only action available for comment is to "Reference in a new issue".

**Comment by carlocab** [comment]
That's intentional. I edited https://github.com/Homebrew/homebrew-core/issues/113717#issuecomment-1289381614 to include the link to the upstream issue.
