### ISSUE TITLE
`fnt` formula missing dependency for `xz`

### ISSUE THREAD

**Issue by jarrettone** [Homebrew/homebrew-core#114122]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
# brew config; brew doctor
HOMEBREW_VERSION: 3.6.7-32-g31758ea
ORIGIN: https://github.com/Homebrew/brew
HEAD: 31758eaa0272a7860816cf584ed91a72a95a1f7f
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1c7871ab9e6acbf5d270d36f9cce9fbe7881e3e4
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libctxfuse.2.dylib
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use `fnt`, after installing it with `brew install fnt`, to search for and install SourceCodePro font.

### What happened (include all command output)?

Ran the following commands:
```
brew update
brew install fnt
fnt update
fnt search sourcecodepro
```

The output printed after the `fnt search sourcecodepro` is as follows:
```
/opt/homebrew/bin/fnt: line 175: unxz: command not found
google-sourcecodepro
```

In addition to pasting the output above, I have attached the output from `brew install fnt` to show what was installed as a dependency for `fnt` on my system, but I have excluded other output as it was uninteresting. 

[brew-install-fnt.macos.txt](https://github.com/Homebrew/homebrew-core/files/9882761/brew-install-fnt.macos.txt)

### What did you expect to happen?

I expected `fnt search sourcecodepro` to find a font without any errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install fnt
fnt update
fnt search sourcecodepro
```

**Comment by cloudbow** [comment]
Getting the same issue on an was linux instance.

**Comment by carlocab** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/114132. If you installed `fnt` before that PR was merged, just `brew install xz`.

**Comment by cloudbow** [comment]
❯ brew install xz                                                                                                                                                                   ⇣0 B/s ⇡0 B/s 10.101.42.9   50.16.116.156  ─╯
Warning: Building xz from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/ec2-user/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/ec2-user/.linuxbrew)
==> Downloading https://downloads.sourceforge.net/project/lzmautils/xz-5.2.7.tar.gz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/4eb076b0160c00e99dd67d38cddbbee3519920ef67831e22ed6efba152448265--xz-5.2.7.tar.gz
==> ./configure --prefix=/home/ec2-user/.linuxbrew/Cellar/xz/5.2.7
Last 15 lines from /home/ec2-user/.cache/Homebrew/Logs/xz/01.configure:

Initializing Automake:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/xz-20221029-1391-1fy8rgu/xz-5.2.7':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by cloudbow** [comment]
❯ brew config                                                                                                                                                                ⇣2.12 KiB/s ⇡919 B/s ─╯
HOMEBREW_VERSION: 3.6.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a7eac25e167a1eb2d49e13c8cc530a3188af995
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 86754e6d11ccdd0dff1dc514c76d29f97bbb5a23
Core tap last commit: 15 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/ec2-user/.linuxbrew
HOMEBREW_REPOSITORY: /home/ec2-user/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/ec2-user/.linuxbrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.8 => /home/ec2-user/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.32.0 => /bin/git
Curl: 7.79.1 => /bin/curl
Kernel: Linux 4.14.225-169.362.amzn2.x86_64 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.26
/usr/bin/gcc: 7.3.1
/usr/bin/ruby: N/A
glibc: 2.35_1
gcc@11: N/A
gcc: N/A
xorg: N/A
