### ISSUE TITLE
helmfile - autocompletion broke

### ISSUE THREAD

**Issue by aeimer** [Homebrew/homebrew-core#114158]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.6.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a7eac25e167a1eb2d49e13c8cc530a3188af995
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 388ff7561473380333de18e98eb3bbf1c7fdb69f
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A

---

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/alexeimer/.pyenv/shims/python-config
  /Users/alexeimer/.pyenv/shims/python3-config
  /Users/alexeimer/.pyenv/shims/python3.8-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.9/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  azure-functions-core-tools@3
  python-typing-extensions
  six

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I brew update ; brew upgrade 'ed and then the helmfile autocompletion stopped working.

brew uninstall helmfile ; brew install helmfile did not help.

### What happened (include all command output)?

helmfile <TAB> will bring up this error `helmfile unknown flag: --generate-bash-completion`:
![grafik](https://user-images.githubusercontent.com/25035182/198543071-125ee5fb-d0ba-47a1-9dbb-175aaaf9d08f.png)

### What did you expect to happen?

The autocompletion should be installed automatically.

It seems like the formula install file is (almost?!) ok, it calls `helmfile completion` instead of `helmfile completion zsh`:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/helmfile.rb#L33

This will result in:
![grafik](https://user-images.githubusercontent.com/25035182/198543724-afa54fc3-1785-4764-8c9e-3c9b2435e70a.png)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install helmfile
helmfile <TAB>
or
helmfile --kube-c<TAB>
```

**Comment by issyl0** [comment]
> It seems like the formula install file is (almost?!) ok, it calls `helmfile completion` instead of `helmfile completion zsh`:

This is intentional, because the [`generate_completions_from_executable` method](https://github.com/Homebrew/brew/blob/31758eaa0272a7860816cf584ed91a72a95a1f7f/Library/Homebrew/formula.rb#L1686) should auto-append the `zsh` portion (and other shells like `fish` and `bash`).

I'll look into why this isn't working specifically here. 🤔

**Comment by issyl0** [comment]
Autocompletions installed by this formula seem to work on my machine.

```shell
issyl0 at cetus in /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core on master
❯ helmfile completion <TAB>
bash        -- Generate the autocompletion script for bash
fish        -- Generate the autocompletion script for fish
powershell  -- Generate the autocompletion script for powershell
zsh         -- Generate the autocompletion script for zsh
```

Did you follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh to set up Homebrew's completions? Maybe some of your zsh config got lost?

**Comment by aeimer** [comment]
@issyl0

I tried adding
```bash
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi
before the `source $ZSH/oh-my-zsh.sh` in `.zshrc`.

Open new tab, same behaviour.
`rm -f ~/.zcompdump; compinit` also does not help (tried with new tab in iTerm2 => new shell.

Any further ideas?

**Comment by remidebette** [comment]
Hi, this does not work for me either, on macos or linuxbrew.
I have had the above `if` in my .zshrc for a while (I do not use oh-my-zsh) and I do not have any problem with other commands autocompletions as installed by brew.

I cannot remember it pyenv autocompletion's ever worked though

**Comment by cho-m** [comment]
> before the `source $ZSH/oh-my-zsh.sh` in `.zshrc`.

OMZ may have its own completions cache file. Try to go through OMZ and find out what is getting configured and when it gets rebuilt.

You can also try starting without existing shell config (OMZ/etc) and just enable the basic zsh completions config to see if it works.

---

Since this cannot be reproduced (I also just tried and it worked fine for me) and there doesn't seem to be any issue with the installed `_helmfile`, this is most likely something in your personal setup that is causing the issue.
