### ISSUE TITLE
ansible-lint: Missing dependency on Pygments prevents ansible-lint from running

### ISSUE THREAD

**Issue by nossralf** [Homebrew/homebrew-core#114524]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.8-10-g73d535a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 73d535a206d86c06e6ebc266351a53e28692dace
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: adbdbb252e385daa0359c65dfed3f45d3f020612
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs -nw
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
---
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  maven@3.5
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Simply running `ansible-lint --help` fails with an exception complaining that no module named `pygments` can be found.

By explicitly installing Pygments into the virtualenv created for ansible-lint (using `/usr/local/Cellar/ansible-lint/6.8.6/libexec/bin/pip install pygments`), the error goes away. There was a change in ansible-lint [back on September 22nd](https://github.com/ansible/ansible-lint/commit/55068d7752e18ab3e0cbf35fb651d86b40948d03) which added the line in `color.py` which is part of the exception backtrace, and that was released in ansible-lint version 6.7.0, so I suspect this has been broken since then (I don't recall when I started seeing this issue in the Homebrew install of ansible-lint, I feel like it didn't start with 6.7.0 but I don't know if I just did the manual Pygments hack back then too, and then forgot about it).

### What happened (include all command output)?

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 5, in <module>
    from ansiblelint.__main__ import _run_cli_entrypoint
  File "/usr/local/Cellar/ansible-lint/6.8.6/libexec/lib/python3.10/site-packages/ansiblelint/__main__.py", line 42, in <module>
    from ansiblelint.app import get_app
  File "/usr/local/Cellar/ansible-lint/6.8.6/libexec/lib/python3.10/site-packages/ansiblelint/app.py", line 15, in <module>
    from ansiblelint.color import console, console_stderr, render_yaml
  File "/usr/local/Cellar/ansible-lint/6.8.6/libexec/lib/python3.10/site-packages/ansiblelint/color.py", line 7, in <module>
    import rich.markdown
  File "/usr/local/Cellar/ansible-lint/6.8.6/libexec/lib/python3.10/site-packages/rich/markdown.py", line 15, in <module>
    from .syntax import Syntax
  File "/usr/local/Cellar/ansible-lint/6.8.6/libexec/lib/python3.10/site-packages/rich/syntax.py", line 21, in <module>
    from pygments.lexer import Lexer
ModuleNotFoundError: No module named 'pygments
```

### What did you expect to happen?

I expected ansible-lint to work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ansible-lint
/usr/local/bin/ansible-lint --help
```

**Comment by dawidd6** [comment]
I have `ansible-lint 6.8.6` on Linux and can't reproduce this.

**Comment by dawidd6** [comment]
Possibly related PR: https://github.com/Homebrew/homebrew-core/pull/113286.

**Comment by nossralf** [comment]
Interesting, a reference to pygments was created in the ansible-lint site-packages directory, in a `homebrew_deps.pth` file. But the path for Pygments was given as `/usr/local/opt/pygments/lib/python3.10/site-packages` whereas on my machine there were no `bin`, `etc` or `lib` directories inside `/usr/local/opt/pygments`, only a `libexec`.

After reinstalling pygments using `brew reinstall pygments`, it has now created `/usr/local/opt/pygments/lib/python3.10/site-packages` as well, and ansible-lint works again.

I have no Homebrew formulas installed that depend on pygments other than ansible-lint. So this is weird, but I guess we can probably chalk it up to some weird state on my machine.

Thanks @dawidd6 for finding that PR, as I had missed that there was a formula dependency on Pygments.
