### ISSUE TITLE
ddclient 3.10: unresolved shebang on MacOS 12.6.1

### ISSUE THREAD

**Issue by favincen** [Homebrew/homebrew-core#114637]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
fabrice@MBA-2021-des-Vincent ~ % brew gist-logs ddclient
Error: No logs.

fabrice@MBA-2021-des-Vincent ~ % brew config            
HOMEBREW_VERSION: 3.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa2649dde786208da7d151a89bcafdd23a453f4d
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f0a57e9d6af030b3c8daee72b91ca541e1683543
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A
Rosetta 2: false

fabrice@MBA-2021-des-Vincent ~ % brew doctor 
Your system is ready to brew.

fabrice@MBA-2021-des-Vincent ~ %
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

launch ddclient (after brew upgrade), to use it for dynamic dns entry update

### What happened (include all command output)?

fabrice@MBA-2021-des-Vincent ~ % /opt/homebrew/opt/ddclient/bin/ddclient -file /opt/homebrew/etc/ddclient.conf
zsh: /opt/homebrew/opt/ddclient/bin/ddclient: bad interpreter: /opt/homebrew/opt/perl/bin/perl: no such file or directory
fabrice@MBA-2021-des-Vincent ~ %

### What did you expect to happen?

Have ddclient update my dynamic DNS entry

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ddclient
/opt/homebrew/opt/ddclient/bin/ddclient -file /opt/homebrew/etc/ddclient.conf

Additional information: perl formula was not installed manualy and not requested by a ddclient dependency
Additional bug: If perl is installed manualy, ddclient fails if "ssl=yes" is set in ddclient.conf
```

**Comment by Bo98** [comment]
Hmm this seems to be because we now have one bottle for both Linux and macOS and it seems the Linux tab is being used for that and thus its dependency list.

I'm surprised we haven't hit this before to be honest.

**Comment by favincen** [comment]
The second issue I encountered once I manually installed homebrew perl is also reported as an issue in ddclient's main repository: https://github.com/ddclient/ddclient/issues/468
I haven't open a second issue because I don't know if homebrew installed ddclient on MacOS should be using homebrew's perl or MacOS's perl. My tests seam to show that apparently neither seam to work if `ssl=yes` is mentioned in ddclient.conf.

**Comment by Bo98** [comment]
The intention was to have ddclient use macOS's Perl. A bug on our side means it's using Homebrew's Perl instead.

macOS Perl should have `IO::Socket::SSL` and `IO::Socket::INET6` by default. Homebrew Perl doesn't by default (we should update the ddclient formula to bundle those).

**Comment by carlocab** [comment]
Upstream ship a `configure.ac` script that seems to check for the required Perl modules though. If that's the case then it looks like that needs to be fixed upstream?

**Comment by favincen** [comment]
Hi. Github bot says this issue is stale. Am I the only one experiencing this issue ?
I there anything I/any non-developper can do to help ?
Or is there any work around ?
Thanks

**Comment by voska** [comment]
Having the same issue. Following.

**Comment by dsuresh-ap** [comment]
Having the same issue as above on an M1 Mac mini. Is there any workaround?

**Comment by multizone-uk** [comment]
Same issue. M1 Mac Mini, macOS Ventura. Installed Homebre's Perl but that doesnt seem to help. (It gets rid of the 'bad interpreter' message but still doesnt work). HTH if I can.

**Comment by multizone-uk** [comment]
I was able to workaround this by installing homebrew perl, and then using CPAN to install the missing modules from homebrew Perl. 
`perl -MCPAN -e shell` and then `install IO::Socket::SSL` followed by `IO::Socket::INET6`. All working now!

**Comment by favincen** [comment]
> I was able to workaround this by installing homebrew perl, and then using CPAN to install the missing modules from homebrew Perl.
> `perl -MCPAN -e shell` and then `install IO::Socket::SSL` followed by `IO::Socket::INET6`. All working now!

Thanks for sharing a workaround !
That’s 2 months at least that ddclient formula 3.10 is brocken on homebrew. 
homebrew having no rollback feature and no version selection feature, my worckaround was to restore previous ddclient from backup and then pin it to prevent accidental update…

**Comment by favincen** [comment]
> The intention was to have ddclient use macOS's Perl. A bug on our side means it's using Homebrew's Perl instead.
> 
> macOS Perl should have `IO::Socket::SSL` and `IO::Socket::INET6` by default. Homebrew Perl doesn't by default (we should update the ddclient formula to bundle those).

Any plan to change the formula in order to have ddclient use macOS’s perl on macs, as initialy planned ?
Or alternatively, add dependencies for homebrew’s perl and its required modules ?
