### ISSUE TITLE
Flann: add hdf5-mpi as an alternative dependency

### ISSUE THREAD

**Issue by renatobusatto** [Homebrew/homebrew-core#114624]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config         
HOMEBREW_VERSION: 3.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa2649dde786208da7d151a89bcafdd23a453f4d
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2dce6235c0e1493edaaaf214999bbcd4f64f33b7
Core tap last commit: 62 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/mate -w
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install hdf5
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install Flann with the hdf5-mpi alternative dependency to hdf5.

### What happened (include all command output)?

brew reinstall flann
==> Downloading https://ghcr.io/v2/homebrew/core/hdf5/manifests/1.12.2_2
Already downloaded: /Users/renato/Library/Caches/Homebrew/downloads/226c4d9d4f35ced4aadbd6937ef03414e9b5f64a927046898b1e6eefc05c48a5--hdf5-1.12.2_2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/hdf5/blobs/sha256:06113cd41180b8047be4a086f8a06ad9912a44520e95915a9aab75dc13e57c9d
Already downloaded: /Users/renato/Library/Caches/Homebrew/downloads/fd35c685cca3e16131ae01c0af7d0aa618bc50f4a6881e7b44532940cf31078c--hdf5--1.12.2_2.arm64_ventura.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/flann/manifests/1.9.1_13
Already downloaded: /Users/renato/Library/Caches/Homebrew/downloads/e5a9112afe6e4a26a2b36622c404ccda839ef101419a34f0227cf2efebedcba9--flann-1.9.1_13.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/flann/blobs/sha256:c9820e001f854b3d5abe3b95b5e63c2b787bd4a7f85c4ba43c5a97300372a802
Already downloaded: /Users/renato/Library/Caches/Homebrew/downloads/9693c2c7205b4706d758178c19647edf19d96e770eacda762c6d1f5a50aa14cb--flann--1.9.1_13.arm64_ventura.bottle.tar.gz
==> Reinstalling flann 
==> Installing dependencies for flann: hdf5
==> Installing flann dependency: hdf5
Error: Cannot install hdf5 because conflicting formulae are installed.
  hdf5-mpi: because hdf5-mpi is a variant of hdf5, one can only use one or the other

Please `brew unlink hdf5-mpi` before continuing.

Unlinking removes a formula's symlinks from /opt/homebrew. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side effects in the
resulting software.

### What did you expect to happen?

The formula should recognise that hdf5-mpi is installed and NOT try to install hdf5.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install hdf5-mpi
brew install flann
```

**Comment by SMillerDev** [comment]
Homebrew does not have a concept of alternative dependencies. You'll need to either install the dependencies, resolving conflicts, or tell Homebrew to ignore dependencies.
