### ISSUE TITLE
webkitgtk assertion error

### ISSUE THREAD

**Issue by shanna** [Homebrew/homebrew-core#11461]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

`webkitgtk` has a failing assertion on a minimal example causing applications that use it to segfault. The version used in the formula is behind by a few minor revisions. The patch doesn't apply cleanly to the next minor revision or the latest patch level for the current minor revision so the formula needs work I think.

#### Minimal example of failure:
https://gist.github.com/shanna/64f3f6475654f35c8ea82e528dd5f50a

**Comment by ilovezfs** [comment]
It was boneyarded: https://github.com/Homebrew/homebrew-core/pull/11243
