### ISSUE TITLE
Samba SMBD can't write new files when running in non-root mode

### ISSUE THREAD

**Issue by 0Rick0** [Homebrew/homebrew-core#114600]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/540d2d54ddcd0b95d51eae7591818e8b
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Writing a file to an SMBD instance running using a non-root user.

The original use case was running a Qemu VM with a smb share, e.g.
```bash
qemu-system-x86_64 \
     .... \
     -netdev user,id=net0,smb=path/to/share
```

### What happened (include all command output)?

NT_STATUS_ACCESS_DENIED when trying to put a file

### What did you expect to happen?

The file to be written correctly

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I've documented some reproduction steps in this Samba ticket https://bugzilla.samba.org/show_bug.cgi?id=15215

Download and extract the test script documented in the Samba BugZilla.
Modify the test script to test a specific version.
Run the test script.

Or:
- Write a simple SMB configuration (the test configuration in the recipe will do).
- run samba-dot-org-smbd with the configuration as non-root.
- use smbclient to put a file
```

**Comment by 0Rick0** [comment]
I'm not sure if Samba will fix it on their side, so maybe HomeBrew should apply the patch before building Samba.

**Comment by SMillerDev** [comment]
Unless upstream accepts the patch Homebrew will not be applying patches. That's what some other package managers sometimes do, and it has massively backfired in the past: https://www.debian.org/security/2008/dsa-1571

**Comment by kjliew** [comment]
I hope this can be reviewed as special exception for macOS. Upstream rejected the patch because smbd should always be run as root user. This is NOT the case for macOS when using Samba smbd for QEMU use cases. Personally, I prefer having smbd as non-root user for sharing host storage to QEMU virtual machines on macOS.

**Comment by MikeMcQuaid** [comment]
> I hope this can be reviewed as special exception for macOS.

No, sorry.

**Comment by kjliew** [comment]
Alright, thanks for the answer.
