### ISSUE TITLE
brew install clang-format@14 fails

### ISSUE THREAD

**Issue by paulb777** [Homebrew/homebrew-core#114628]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew install clang-format@14
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
hotbuild                 libdivide                muon                     pferd                    pomsky
huggingface-cli          markdownlint-cli2        node@18                  pluto                    proxsuite
==> New Casks
binocs                                    dbeaverultimate                           paper
dbeaverlite                               openlens                                  workspace-one-intelligent-hub

You have 15 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: No available formula with the name "clang-format@14". Did you mean clang-format, clang-format@11 or clang-format@8?
==> Searching for similarly named formulae...
These similarly named formulae were found:
clang-format ✔                            clang-format@11                           clang-format@8
To install one of them, run (for example):
  brew install clang-format ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

We would like our CI to continue to succeed when a new version of clang-format publishes.

More context at https://github.com/llvm/llvm-project/issues/49340#issuecomment-1302481419

### What happened (include all command output)?

$ brew install clang-format@14
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
hotbuild                 libdivide                muon                     pferd                    pomsky
huggingface-cli          markdownlint-cli2        node@18                  pluto                    proxsuite
==> New Casks
binocs                                    dbeaverultimate                           paper
dbeaverlite                               openlens                                  workspace-one-intelligent-hub

You have 15 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

Warning: No available formula with the name "clang-format@14". Did you mean clang-format, clang-format@11 or clang-format@8?
==> Searching for similarly named formulae...
These similarly named formulae were found:
clang-format ✔                            clang-format@11                           clang-format@8
To install one of them, run (for example):
  brew install clang-format ✔
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

### What did you expect to happen?

Successful installation of clang-format 14

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install clang-format@14
```

**Comment by SMillerDev** [comment]
This is a feature request, not a bug.

**Comment by paulb777** [comment]
Is there another supported way to install a particular version of clang-format?

**Comment by carlocab** [comment]
You can use `brew extract` to create a version of the formula that you need in your own tap. See `man brew` for details. `brew tap-new` may also be helpful here.

Alternatively, you can try using the `llvm@14` formula.
