### ISSUE TITLE
git: cannot run gitk

### ISSUE THREAD

**Issue by cybertk** [Homebrew/homebrew-core#115]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

After install **git** with `brew install git`, **gitk** is failed to run with following error

```
$ gitk
Error in startup script: unknown color name "lime"
    (processing "-fore" option)
    invoked from within
"$ctext tag conf m2 -fore [lindex $mergecolors 2]"
    (procedure "makewindow" line 347)
    invoked from within
"makewindow"
    (file "/usr/local/bin/gitk" line 12434)
```

**Comment by mikemcquaid** [comment]
I can reproduce this. Can you see if you get the same result building `git` outside Homebrew? If so, please report this upstream and let us know. Thanks!

**Comment by tdsmith** [comment]
What's `which wish`? I don't see this with Homebrew gitk + the system Tcl.

**Comment by mikemcquaid** [comment]
`/usr/bin/wish` for me. Do you have X11 installed? (I don't)

**Comment by DomT4** [comment]
I can reproduce the failure locally as well.

**Comment by tdsmith** [comment]
I have Xquartz.

**Comment by mikemcquaid** [comment]
@DomT4 Do you? If not my guess is that's the failure and we should probably just remove `gitk` (Apple doesn't install it in their `git`).

**Comment by DomT4** [comment]
Yup, and if I punt `/opt/X11/bin` out of the `$PATH` it magically works again.

**Comment by apjanke** [comment]
I can also reproduce on OS X 10.9.5 with latest XQuartz (2.7.8) installed, system Tcl/Tk.

[StackOverflow is on it](http://stackoverflow.com/questions/34637896/gitk-will-not-start-on-mac-unknown-color-name-lime). Seems like `lime` is new in something between Tcl 8.5.9 and 8.6.4.

The patch is trivial: https://github.com/Homebrew/homebrew-core/pull/236. With this, `gitk` works again for me on 10.9.5. Want to do this?

**Comment by apjanke** [comment]
And when I say "the patch is trivial", I also mean "simplistic": it does a simple string replace, so if future versions include any word with "lime" as a substring, this'll edit them and things'll probably break. (I checked the current version; it's safe to use.) This should be reported upstream as well; hopefully they care about running against older Tcl/Tks.

**Comment by DomT4** [comment]
This has been patched (by Andrew) in our `git` formula & there's tracking links to the upstream submission there, so let's close this issue out. Thanks everyone ❤️.
