### ISSUE TITLE
g++-12 doesn't issue warning on unitialized variables even though "-ansi -Wall -pedantic" options are used

### ISSUE THREAD

**Issue by anta40** [Homebrew/homebrew-core#115157]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92e3ea0ecc219510d850c639c035bf0cdc6903f3
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7da925b66f74d75327dc89c55b5a7f035f09afd0
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Consider this C++ code

```
#include <iostream>

using namespace std;

int main(void){
    int sum;
    int N;
    int data;

    cout << "How many numbers? ";
    cin >> N;

    for (int x = 1; x <= N; x++){
        cout << "Enter number: ";
        cin >> data;
        sum += data;
    }

    cout << "Sum: " << sum << endl;
    return 0;
}

```

If I run it, and provides N=3, then provides these data: 10, 20, 30, then the sum printed maybe 60, maybe 61, maybe 817264, or something else, depends on the compiler. This happens because `data` is unitialized, and then points to random value. The purpose of this code is to explain to C/C++ beginners how unitialized variables may cause bugs, so always read the compiler warnings.

### What happened (include all command output)?

```
$ g++-12 sumdemo.cpp -o sumdemo -Wall -ansi -pedantic
$ ./sumdemo
How many numbers? 3
Enter number: 10
Enter number: 20
Enter number: 30
Sum: 61

```
The compiler doesn't print anything, simply builds the executable.

### What did you expect to happen?

It should print something like this:
```
sumdemo.cpp:16:9: warning: variable 'sum' is uninitialized when used here [-Wuninitialized]
        sum += data;
        ^~~
sumdemo.cpp:6:12: note: initialize the variable 'sum' to silence this warning
    int sum;
           ^
            = 0
1 warning generated.
```

On the other side, g++ provided by Apple's Command Line Tools (clang-1400.0.29.202) and clang 15 (installed via Homebrew) do that.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install gcc@12
$ g++-12 sumdemo.cpp -o sumdemo -Wall -ansi -pedantic
$ ./sumdemo
```

g++-12 is silent, no warning at all

**Comment by carlocab** [comment]
This sounds like an upstream issue, as I don't think this is peculiar to the way we build/package GCC. Does this reproduce on a non-Homebrew build (e.g. MacPorts, or something you built from source yourself) of GCC 12?

CC @fxcoudert

**Comment by fxcoudert** [comment]
Confirmed with other versions, including g++-10 on Debian linux. This may be a GCC limitation, but not a bug specific to Homebrew. You can report it upstream: https://gcc.gnu.org/bugzilla/

**Comment by anta40** [comment]
OK, guess I didn't read the manuals.

> GCC can only detect uninitialized variables when **optimization is enabled**, because the logic for tracking the values of variables is part of the optimization machinery.
> https://stackoverflow.com/questions/47307538/why-gcc-does-not-report-uninitialized-variable/47308887#47308887

Let's enable optimization, e.g `-O1`:
```
$ g++-12 sumdemo.cpp -o sumdemo -Wall -ansi -pedantic -O1
sumdemo.cpp: In function ‘int main()’:
sumdemo.cpp:18:28: warning: ‘sum’ may be used uninitialized [-Wmaybe-uninitialized]
   18 |         cout << "Sum: " << sum << endl;
      |                            ^~~
sumdemo.cpp:6:13: note: ‘sum’ was declared here
    6 |         int sum;
      |             ^~~

```

Problem solved.
