### ISSUE TITLE
Error building open-mpi with gcc-5 or gcc-6

### ISSUE THREAD

**Issue by ilciavo** [Homebrew/homebrew-core#11520]
I'm trying to build `open-mpi` with `gcc-5` or `gcc-6`. 

Generally, I export the environment variables and aliases

```
#For GCC 6
export CC=gcc-6
export CXX=g++-6
export CPP=cpp-6
export LD=gcc-6
export FC=gfortran-6

alias c++=c++-6
alias g++=g++-6
alias gcc=gcc-6
alias cpp=cpp-6
alias ld=gcc-6
alias cc=gcc-6
alias gfortran=gfortran-6

export HOMEBREW_CC=gcc-6
export HOMEBREW_CXX=g++-6
export HOMEBREW_CPP=cpp-6
export HOMEBREW_LD=gcc-6
export HOMEBREW_FC=gfortran-6
```
Then build `open-mpi` as 

>$brew install open-mpi --build-from-source

which returns the following error 

> Last 15 lines from /Users/leo/Library/Logs/Homebrew/open-mpi/03.make:
> # PASS:  9
> # SKIP:  0
> # XFAIL: 0
> # FAIL:  1
> # XPASS: 0
> # ERROR: 0
> ============================================================================
> See test/class/test-suite.log
> Please report to http://www.open-mpi.org/community/help/
> ============================================================================
> make[4]: *** [test-suite.log] Error 1
> make[3]: *** [check-TESTS] Error 2
> make[2]: *** [check-am] Error 2
> make[1]: *** [check-recursive] Error 1
> make: *** [check-recursive] Error 1

The complete error log can be found [here](https://gist.github.com/anonymous/6eb6659f7f0e1b1b71f49ebc049ced5c)

**Comment by MikeMcQuaid** [comment]
We don't support building every package with every compiler, sorry. We'll accept pull requests to address this but won't be fixing it ourselves.
