### ISSUE TITLE
Failure to build python formula no setuptools found

### ISSUE THREAD

**Issue by battlemidget** [Homebrew/homebrew-core#11528]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Attempting to locally build a python formula is failing with setuptools import error, https://github.com/battlemidget/homebrew-core/blob/add-conjure-up/Formula/conjure-up.rb

```
HOMEBREW_VERSION: 1.1.11-151-g54abadb2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 54abadb202fcb1f0cd7df057809e841e1930d94c
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0fb94327ca30b492dde2e0e3b63fbe1bce356b3f
Core tap last commit: 62 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: N/A
```
```
Your system is ready to brew.
```

brew gist-logs: https://gist.github.com/anonymous/ea17e48e2ab977d1a3908e2c6c88d6cb

I did attempt to clear out  my cache and rebuild but same error. I did notice that python3 was recently updated as well.

**Comment by battlemidget** [comment]
After completely removing python3 and reinstalling I saw:

```
Sarahs-Mac-mini:Formula ninja$ brew install conjure-up --HEAD
==> Installing dependencies for conjure-up: python3, juju-wait
==> Installing conjure-up dependency: python3
==> Downloading https://homebrew.bintray.com/bottles/python3-3.6.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring python3-3.6.1.sierra.bottle.tar.gz
==> Using the sandbox
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python3`
```

And re-running `brew postinstall python3` manually fixed this issue. I'm curious if the postinstall problem is known already?

**Comment by tdsmith** [comment]
This seems like an echo of #10771. I'm not aware of a reason that postinstall should fail and then succeed without anything changing in between.

**Comment by battlemidget** [comment]
Thanks, I'll re-open if I come across this again.

**Comment by tdsmith** [comment]
Thanks. After your report I'm more confident there's a real problem here but I don't know how to figure out what it is. :(
