### ISSUE TITLE
Forced Python Install with gobject-introspection

### ISSUE THREAD

**Issue by blogabe** [Homebrew/homebrew-core#11536]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

May I ask why the change in commit https://github.com/Homebrew/homebrew-core/commit/1ab01953810fa04d65d0f961dc34898077f0ec7f#diff-626b321c06d31d0bffed408d358c97cf to force homebrew's python over system python?

I'd prefer to use system python and am unsure why specifically v1.52 requires a more modern python.

**Comment by neutric** [comment]
Does [this comment](https://github.com/Homebrew/homebrew-core/pull/11464#discussion_r107407934) by @tschoonj answer your question?

**Comment by blogabe** [comment]
It does, thank you.  Went looking for the gobject-introspection pull request by name and couldn't find it.  Didn't realize it was part of a broader change related to glib.

I agree with the question, it does seem a bit heavy-handed to require, and I now understand the reason (although I don't personally like it).

**Comment by blogabe** [comment]
Reason I created this issue in the first place is because homebrew can't link python upon installation:
```
>~$ brew upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Upgrading 1 outdated package, with result:
gobject-introspection 1.52.0
Error: You must `brew link python` before gobject-introspection can be installed
>:~$ brew link python
Linking /usr/local/Cellar/python/2.7.13... Error: Permission denied - /usr/local/Frameworks
```

**Comment by tschoonj** [comment]
I have just opened #11538, which hardcodes Homebrew's python full path to the executable in `gobject-introspection`'s executables' shebangs.

So even if you don't like the brewed python, you can still unlink it, and it will still get used by `gobject-introspection`.

Why the linking doesn't work on your system I cannot say though: looks like you cannot write to /usr/local...

**Comment by ilovezfs** [comment]
@tschoonj I'm wondering if we can intervene with a shim to prevent the universal-whatever rather than resorting to full replacement. This doesn't seem like a particularly surgical approach.

**Comment by fxcoudert** [comment]
There are other formulas that work around the universal python issue, IIRC

**Comment by tschoonj** [comment]
I agree that it would be better to come up with a solution that does not require a brewed python. Is there a way for the superenv to strip `-arch x86_64 -arch i386` from the compiler invocations?

**Comment by ilovezfs** [comment]
Maybe having shims for python*-config?

**Comment by tschoonj** [comment]
I doubt that will be sufficient as software can also get this from the python interpreter directly:

````python
>>> import sysconfig
>>> a = sysconfig.get_config_vars('CFLAGS')
>>> print(a)
['-fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE']
````

What is Homebrew's policy on universal builds nowadays? Are they still supported?

**Comment by ilovezfs** [comment]
Yes they're still supported if all dependencies are vendored and there's a good reason (e.g., wine).

So I guess we could check if `ENV.universal_binary` is set, and if not, filter out the `-arch x86_64 -arch i386` junk.

**Comment by blogabe** [comment]
While this is being worked out, can anyone provide any suggestions to get over this error message when i try to link homebrew python:
```
$ brew link python
Linking /usr/local/Cellar/python/2.7.13... Error: Permission denied - /usr/local/Frameworks
```

Is it a permissions thing?

**Comment by tschoonj** [comment]
Looks like it, works fine here

**Comment by MikeMcQuaid** [comment]
@blogabe `chown -R $USER /usr/local/Frameworks`

**Comment by blogabe** [comment]
Thank you @MikeMcQuaid but still getting an error:
```
$ chown -R $USER /usr/local/Frameworks
chown: /usr/local/Frameworks: No such file or directory
```

Assume installing homebrew python would have created this directory.  I can manually create the directory, but wondering who should own it, root or my?

**Comment by MikeMcQuaid** [comment]
@blogabe Create it yourself and own it with your user. The installer creates it but Homebrew Python won't.

**Comment by blogabe** [comment]
Great.  Thank you.  Looks like everything is functioning properly again.  Close this or keep it open due to the conversation around potentially going around the universal python issue?

**Comment by MikeMcQuaid** [comment]
Will defer to @ilovezfs on that.

**Comment by blogabe** [comment]
One other question.  If the installer should have created the directory, and it hadn't been created on my system, I can only assume that's because I've had homebrew installed for many years.  Is it in the plans to upgrade the installer so updates like this are forced for existing homebrew users?

**Comment by MikeMcQuaid** [comment]
This should have been done for you by `update-report` when it migrated you to `/usr/local/Homebrew`.

**Comment by blogabe** [comment]
I can confirm the "Frameworks" directory was not created on two separate homebrew installations during the migration.  On one computer, I have it installed to /usr/local.  On the other, it's at ~/local.  Just reporting.  No sweat one way or another.

**Comment by MikeMcQuaid** [comment]
I'm afraid I have no idea why that would be given: 
- https://github.com/Homebrew/brew/blob/1ba401039eeafec6dca464e9be18a5257a3d89bc/Library/Homebrew/cmd/update-report.rb#L267-L269
- https://github.com/Homebrew/install/blob/d97fb9edbe2ea308400a894f7d1df7967717a937/install#L206

If you've installed not using the installer or not updated such that `update-report` is hit that would explain it.

**Comment by ilovezfs** [comment]
Let's leave this open. We've already had people on IRC complaining on IRC as well about requiring brew python just due to `gobject-introspection`.

**Comment by ilovezfs** [comment]
adding `in progress` to protect this from probot-stale

**Comment by ilovezfs** [comment]
Closing this in favor of #12226
