### ISSUE TITLE
SECURITY - 7zip should be upgraded to version 16.00

### ISSUE THREAD

**Issue by skarfacegc** [Homebrew/homebrew-core#1155]
There's a nasty security problem with prior versions

http://blog.talosintel.com/2016/05/multiple-7-zip-vulnerabilities.html

I'm fairly new to homebrew or I'd muck with it.

**Comment by ilovezfs** [comment]
https://sourceforge.net/projects/p7zip/files/p7zip/

Doesn't seem to be a 16* version out yet

**Comment by ilovezfs** [comment]
@mikemcquaid not sure if this merits boneyarding but doesn't sound good

**Comment by mikemcquaid** [comment]
It's unclear to me whether this is affected/vulnerable.

**Comment by ilovezfs** [comment]
Yup https://packages.qa.debian.org/p/p7zip/news/20160515T102412Z.html

**Comment by mikemcquaid** [comment]
Ok, definitely worth patching 👍

**Comment by ilovezfs** [comment]
@skarfacegc This should take care of it until upstream releases a new version: #1184

**Comment by skarfacegc** [comment]
@ilovezfs thanks for the quick turnaround.

**Comment by ilovezfs** [comment]
@skarfacegc You're welcome!

**Comment by ilovezfs** [comment]
@skarfacegc FYI: https://github.com/Homebrew/homebrew-core/pull/3003
