### ISSUE TITLE
mariadb: delete default datadir from homebrew.mxcl.mariadb.plist

### ISSUE THREAD

**Issue by procodix** [Homebrew/homebrew-core#115847]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
irrelevant
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install MariaDB and use *my* custom datadir

### What happened (include all command output)?

The package installs fine, but the file from the issue title includes the config directive
<string>--datadir= [...] </string>

Every update resets my config to the stupid default and overrides any datadir I have set int /etc/my.cnf

### What did you expect to happen?

That the service file does not include any datadir, this should be read from the MariaDB config file. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) brew install mariadb

2) check /opt/homebrew/Cellar/mariadb/10.9.4/homebrew.mxcl.mariadb.plist

3) find line 20, saying: <string>--datadir= [...] </string>
```

**Comment by SMillerDev** [comment]
You can always use your own plist or run MySQL manually. This data directory is a good default for new users. If you're more experienced you can use alternatives.

**Comment by procodix** [comment]
No, I use the plist provided and that makes sense, but it gets overwritten with every update, so I don't change anything inside it. 

The "normal" way to set a datadir is by configuring it in one of those 100 locations, mariadb will look for it, but not in the service definition.
