### ISSUE TITLE
gcc head URL doesn't work

### ISSUE THREAD

**Issue by petere** [Homebrew/homebrew-core#11581]
If I run

    brew upgrade gcc --HEAD

it fails after a short while with

    ==> Upgrading 1 outdated package, with result:
    gcc HEAD_1
    ==> Upgrading gcc
    ==> Using the sandbox
    ==> Cloning https://gcc.gnu.org/svn/gcc/trunk
    svn: E120108: Error running context: The server unexpectedly closed the connection.
    Error: Failed to download resource "gcc"
    Failure while executing: svn checkout -q https://gcc.gnu.org/svn/gcc/trunk /Users/peter/Library/Caches/Homebrew/gcc--svn-HEAD

The svn URL was recently (761b514ccfd7d1563b08e8ecf5949bc0f871159e) changed from `svn:` to `https:`. If I change it back, it works fine. I don't find the `https:` URL documented on the GCC web site (https://gcc.gnu.org/svn.html), so maybe it's not expected to work?

Can someone else reproduce this? Is it just a momentary problem?

Perhaps switching to the Git mirror (https://gcc.gnu.org/wiki/GitMirror) would be easiest?

**Comment by ilovezfs** [comment]
if you `brew install svn` does the problem go away

**Comment by d25fe0be** [comment]
The same to me, either with the pre-installed `subversion` or the brew one.

`svn:` works.

ps: `http(s):` is noticeably slower than `svn:` for large repos like gcc (suppose the checkout succeeds
).

**Comment by vszakats** [comment]
Works here fine (with Sierra):
```
$ which svn
/usr/bin/svn
$ svn co https://gcc.gnu.org/svn/gcc/trunk
A    trunk/libitm
A    trunk/libitm/testsuite
A    trunk/libitm/testsuite/libitm.c
A    trunk/libitm/alloc_cpp.cc
A    trunk/libitm/libitm.h
A    trunk/libitm/alloc.cc
A    trunk/libitm/configure.tgt
A    trunk/config-ml.in
A    trunk/libitm/alloc_c.cc
A    trunk/libitm/eh_cpp.cc
A    trunk/libitm/testsuite/libitm.c/clone-1.c
A    trunk/libitm/testsuite/libitm.c/dropref.c
A    trunk/libitm/local_atomic
A    trunk/libitm/testsuite/libitm.c/priv-1.c
A    trunk/libitm/testsuite/libitm.c/reentrant.c
[...]
```

**Comment by vszakats** [comment]
Can this be the known SVN issue under El Capitan/Yosemite?

If so, this method should work here as well:
```
  if MacOS.version >= :sierra
    head "https://gcc.gnu.org/svn/gcc/trunk", :using => :svn
  else
    head "svn://gcc.gnu.org/svn/gcc/trunk"
  end
```

**Comment by vszakats** [comment]
Update: The El Capitan/Yosemite issue is present (where it asks to manually accept cert), but I could reproduce this issue as well, it looks like the checkout stops after a while with this error:
```
svn: E120108: Error running context: The server unexpectedly closed the connection.
```

**Comment by d25fe0be** [comment]
I got some similar error on a CentOS 7 when checking out GCC using `https:` previously. 
I suspect it's an issue with the protocol or GCC's http server.

**Comment by vszakats** [comment]
HTTPS protocol in itself should work (as it does with other SVN servers), so it's likely a gcc server specific issue, or configuration not yet completed.
