### ISSUE TITLE
Node ships with wrong Openssl Version

### ISSUE THREAD

**Issue by ScriptType** [Homebrew/homebrew-core#115964]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7391069d48805c786b1e9fe88edf795960321dc
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 22f30b5c5ab393db4aaa1cd9b3376d5bac16b0b0
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Node behaves different if used with the prebuilt node executable or the Homebrew made one.
Apps that rely on the behavior of OpenSSL 1.1.1 will crash in the official prebuilt of Node 19.1 with the error ERR_OSSL_EVP_UNSUPPORTED which is since Node 17 the correct behavior as it ships with OpenSSL 3.0.

The Node Homebrew variant is still shipping with OpenSSL 1.1.1 which is at least not the “intended” behavior.
https://nodejs.org/es/blog/release/v17.0.0/

Homebrew Node should follow the official release of node because it gets problematic when it shifts
My Workmate and I had both the same Node Version 19.1.0 I could run the app, but it crashed for my workmate with
ERR_OSSL_EVP_UNSUPPORTED 
which costed us some debug time to find the difference he installed node with NVM which is using the prebuilt I am using the Homebrew build and I think there shouldn't be a difference.

### What happened (include all command output)?

Apps relying on specifict featureset of OpenSSL 1.1.1 run without a problem.
For example apps relying on OpenSSL1.1.1 and running 
" node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);"
  will crash on the prebuilt of Node as it only ships with OpenSSL 3.0

### What did you expect to happen?

That an App that relies on specific OpenSSL 1.1.1 features crash with the error (according to https://nodejs.org/es/blog/release/v17.0.0/)
ERR_OSSL_EVP_UNSUPPORTED

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install node
```

**Comment by Bo98** [comment]
At the time of Node 17's release, OpenSSL 3 was not compatible with older versions of macOS so was not an option at the time. This changed with OpenSSL 3.0.6, and we're working on migrating all of homebrew-core to it - and this ideally means changing Node's dependencies to use OpenSSL 3 as well.

**Comment by chrmoritz** [comment]
Also note that Node.js ships with [quictls/openssl](https://github.com/quictls/openssl), which is still different from upstream openssl 3.0.x (namely lacking QUIC support).

**Comment by cho-m** [comment]
Related #114641. The problem is the size of OpenSSL dependency tree.

Issue #104784 is being used as tracking OpenSSL migration work. That also provides info for anyone who wants to help migrate OpenSSL formulae.

---

> Also note that Node.js ships with [quictls/openssl](https://github.com/quictls/openssl), which is still different from upstream openssl 3.0.x (namely lacking QUIC support).

Most 3rd party distributions of Node.js will use system copy of OpenSSL, e.g. Alpine, Arch, Debian, Fedora, Gentoo. Homebrew shares the ideology of Linux distros against bundled dependencies, particularly in regards to something with high security risk like OpenSSL.

I only saw MacPorts default to using bundled copy.

I don't expect Homebrew using bundled copy, so if you want QUIC support then you may want to consider a personal tap, using another NodeJS installer, or the MacPorts copy.
