### ISSUE TITLE
Ansible 6.6.0 ships with incompatible openstacksdk version 

### ISSUE THREAD

**Issue by albgus** [Homebrew/homebrew-core#115922]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7391069d48805c786b1e9fe88edf795960321dc
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4a82a72e2aad3b1aefb59b961b7be9a3640f7c6f
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.38.1 => /usr/local/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-x86_64
CLT: 12.5.0.22.9
Xcode: 12.2
```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Your Xcode (12.2) is too outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (12.2) is outdated.
Please update to Xcode 14.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm using `openstack.cloud.openstack` to provide dynamic inventories from an OpenStack cloud.

### What happened (include all command output)?

```
$ ansible-playbook playbooks/nginx.yml
[WARNING]:  * Failed to parse /Users/[REDACTED]/Code/ansible//inventory/openstack.yml with auto plugin: Incompatible openstacksdk library found: Version MUST be >=0.36 and <=0.98.999, but 0.102.0 is larger than maximum version 0.98.999.
[WARNING]:  * Failed to parse /Users/[REDACTED]/Code/ansible/inventory/openstack.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /Users/[REDACTED]/Code/ansible/inventory/openstack.yml with ini plugin: Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
[WARNING]: Unable to parse /Users/[REDACTED]/Code/ansible/inventory/openstack.yml as an inventory source
[WARNING]: Unable to parse /Users/[REDACTED]/Code/ansible/inventory as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead. This feature will be removed in version 2.16. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Could not match supplied host pattern, ignoring: nginx

PLAY [nginx] **************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP **************************************************************************************************************************
```

### What did you expect to happen?

The `openstack.cloud.openstack` module should be able to load.

### Step-by-step reproduction instructions (by running `brew` commands)

1. brew install ansible
2. Create inventory file openstack.yml:
```
---
plugin: openstack.cloud.openstack
expand_hostvars: false
use_hostnames: true
fail_on_errors: true
all_projects: false
compose:
  ansible_ssh_host: openstack.private_v4
```
4. Run: `ansible -i openstack.yml -m ping all`

(No Openstack environment should be needed as it crashes at loading the module)

**Comment by Bo98** [comment]
Hmm given this isn't included in Ansible anymore, we probably shouldn't be bundling any `openstacksdk` and let just let the user install the version they need for the plugin versions they use

**Comment by cho-m** [comment]
> Hmm given this isn't included in Ansible anymore, we probably shouldn't be bundling any `openstacksdk` and let just let the user install the version they need for the plugin versions they use

This will probably be easiest for Homebrew as Ansible doesn't use standardized `extras_require` so we can't automatically pick up version restrictions. Can consider a `caveat` to include particular `pipX.Y` command needed as we can migrate Python aliases at any time.

Having to track the version ourselves will be too much of a maintainer burden.

---

Note that Homebrew isn't the only one with this problem. Linux distros are probably in trickier situation due to having global packages.

Just taking a look, Arch Linux has `python-openstacksdk 0.102.0` and Debian has `python3-openstacksdk 0.101.0`.

Only one that might have correct versions is Fedora/RedHat since they own Ansible. Fedora 37 has `ansible 6.4.0 + python3-openstacksdk 0.61.0` while Fedora Rawhide has `ansible 7.0.0~b1 + python3-openstacksdk 0.101.0`
