### ISSUE TITLE
Wine 2.4 (devel) fails to build

### ISSUE THREAD

**Issue by spaghetti2514** [Homebrew/homebrew-core#11592]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

When building wine with --devel, the install fails after printing a bunch of errors about unknown mpg123 symbols for i386. I think the problem is just the 32bit wine binary is trying to be built against a 64bit mpg123, and for some reason the --without-mpg123 build flag was removed from the configuration of 32bit wine in the formula. After manually adding --without-mpg123 to the configure args in the formula, the formula built successfully, but I don't know if this is the correct approach to be taking.

**Comment by fxcoudert** [comment]
Thanks for reporting, I am trying to fix it by building universal mpg123 inside wine. Let's move the discussion to the PR :)
