### ISSUE TITLE
onefetch miss shell completions

### ISSUE THREAD

**Issue by Freed-Wu** [Homebrew/homebrew-core#116000]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
/
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

See <https://github.com/o2sh/onefetch/issues/864>

### What happened (include all command output)?

/

### What did you expect to happen?

/

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
/
```

**Comment by SMillerDev** [comment]
It says you can run the command to generate them, what is broken about the command when installed through Homebrew?

**Comment by Freed-Wu** [comment]
It should have an out-of-box setting, like <https://github.com/Homebrew/homebrew-core/blob/master/Formula/gh.rb#L37>.

**Comment by Freed-Wu** [comment]
The same bug also happens in other package managers like <https://github.com/NixOS/nixpkgs/issues/201603#event-7835404821> and <https://github.com/termux/termux-packages/issues/13150>, which has been fixed there.

**Comment by mhmdanas** [comment]
See https://github.com/Homebrew/homebrew-core/pull/116041.

**Comment by Freed-Wu** [comment]
And trash-cli <https://github.com/Homebrew/homebrew-core/blob/master/Formula/trash-cli.rb> also miss shell completions. Same bug happens in nix <https://github.com/NixOS/nixpkgs/issues/202165>, but not in archlinux <https://github.com/archlinux/svntogit-community/blob/packages/trash-cli/trunk/PKGBUILD#L31-L34>.
