### ISSUE TITLE
python3 formula tries to pull Python-3.6.0.tar.xz from python.org -- it's empty

### ISSUE THREAD

**Issue by ssteinerx** [Homebrew/homebrew-core#11646]
I did the manual update, the formula refers to an out-of-date Python version (latest is 3.6.1) and the pull of the previous archive comes back empty:

```
jenkins@9b35c129d1e9:/$ cd $(brew --repo)
jenkins@9b35c129d1e9:~/.linuxbrew$ git fetch
jenkins@9b35c129d1e9:~/.linuxbrew$ git reset --hard origin/master
HEAD is now at 92bb61c cpu.rb: add skylake to Linuxbrew
jenkins@9b35c129d1e9:~/.linuxbrew$ brew update
Already up-to-date.
jenkins@9b35c129d1e9:~/.linuxbrew$ brew install python3
==> Downloading https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
Already downloaded: /var/jenkins_home/.cache/Homebrew/python3-3.6.0.tar.xz
Error: Empty archive
```

**Comment by ssteinerx** [comment]
This is on Debian Jessie:

    Linux 9b35c129d1e9 4.9.13-moby #1 SMP Tue Mar 21 21:21:05 UTC 2017 x86_64 GNU/Linux

fully upgraded via `apt-get update && apt-get upgrade`

Updated the formula locally and fixed up the SHA256, xz-utils is installed, the archive is this:

    -rw-r--r-- 1 jenkins jenkins 16872064 Mar 21 07:47 /var/jenkins_home/.cache/Homebrew/python3-3.6.1.tar.xz

but brew is still saying:

```
jenkins@9b35c129d1e9:~/.linuxbrew$ brew install python3
==> Downloading https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz
Already downloaded: /var/jenkins_home/.cache/Homebrew/python3-3.6.1.tar.xz
Error: Empty archive
```

**Comment by ilovezfs** [comment]
>linuxbrew

This is Homebrew so please don't report Linux stuff here, thanks.

**Comment by ilovezfs** [comment]
No worries. It's no big deal, but, no, there's no mechanism to transfer issues between repositories.

**Comment by ssteinerx** [comment]
Crap.  Thanks, I'll move it by hand.
