### ISSUE TITLE
Nicotine Plus doesn't add a folder to /Applications

### ISSUE THREAD

**Issue by james-tindal** [Homebrew/homebrew-core#116653]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
_
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the standard application from the website.

### What happened (include all command output)?

It installs a version which is called in the terminal and requires the terminal session to be left open to continue to run.

### What did you expect to happen?

I expect an application to be added to the /Applications folder.
This is available here: [Download Nicotine+ macOS Installer](https://github.com/nicotine-plus/nicotine-plus/releases/latest/download/macos-installer.zip)
Why would anyone want a special version that runs a GUI from the command line?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
_
```

**Comment by SMillerDev** [comment]
Since there are no brew commands in your issue I don't think there's anything actionable here.

**Comment by james-tindal** [comment]
I'm suggesting the formula should simply install the normal version of the application instead of a GUI launched from the command line. The suggested action would be for someone to make that happen.

**Comment by SMillerDev** [comment]
That's not what formula do. Those are always terminal based. Sounds like you want a cask.

**Comment by james-tindal** [comment]
That makes sense. This really isn't a terminal app though. On execution, it
spits out some text and opens the GUI. The terminal doesn't read any text
input or print anything else. It just sits there, taking up an iTerm tab
while interaction happens solely in the GUI.

**Comment by carlocab** [comment]
> It just sits there, taking up an iTerm tab
> while interaction happens solely in the GUI.

You can call a program with `&` (e.g. `sleep 100 &`) to run it in the background. You'll need to use `disown` or `nohup` if you want to close the terminal session that you started the backgrounded process from, though.
