### ISSUE TITLE
Feature request: 'brew update postgresql' should try to update database files automatically

### ISSUE THREAD

**Issue by unikitty37** [Homebrew/homebrew-core#11678]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

After running `brew upgrade postgresql`, `brew services start postgresql`, and `postgres`, I receive the following message:

```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.2.
```

While a link to manual upgrade instructions is provided on running the upgrade, shouldn't Homebrew do this automatically if possible, rather than leaving an install that won't start? It presumably knows which version it's upgrading from — and the point of Homebrew is to make installing and upgrading developer tools easy, after all :)

`brew config`:
```
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 58b574b4b69282c8a12201b51098d0bcfab03e06
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit nehalem
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/slacker/.rbenv/shims/ruby => /Users/slacker/.rbenv/versions/2.4.0/bin/ruby
Java: 1.7.0_79
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

`brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  qt@5.5
```

`brew gist-logs postgresql`:
```
https://gist.github.com/349204a0a9739d3db42df32262e134ad
```

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by unikitty37** [comment]
Thanks, but I doubt I'd have the time to look at this for several months, as setting aside the project I'm working on to tinker with Homebrew isn't really an option :)

Would it possible to leave the issue open so that somebody else can pick it up if they can get to it before I can?

**Comment by MikeMcQuaid** [comment]
@unikitty37 Sorry, we don't leave open feature requests that aren't being actively worked on by a maintainer.

**Comment by DomT4** [comment]
See previous: https://github.com/Homebrew/legacy-homebrew/pull/35577. Feel free to build on that as much as you want to.

**Comment by MikeMcQuaid** [comment]
Cheers @DomT4.
