### ISSUE TITLE
wine fails to upgrade on OS X 10.11.6

### ISSUE THREAD

**Issue by Marqin** [Homebrew/homebrew-core#11729]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I'm trying to upgrade wine and it fails with:

```
 $ brew upgrade wine
==> Upgrading 1 outdated package, with result:
wine 2.0
==> Upgrading wine
==> Downloading https://homebrew.bintray.com/bottles/wine-2.0.el_capitan.bottle.1.tar.gz
######################################################################## 100,0%
==> Pouring wine-2.0.el_capitan.bottle.1.tar.gz
Error: Failed changing install name in /usr/local/Cellar/wine/2.0/libexec/bin/agentxtrap
  from @@HOMEBREW_CELLAR@@/wine/2.0/libexec/lib/libnetsnmpmibs.30.dylib
    to /usr/local/Cellar/wine/2.0/libexec/lib/libnetsnmpmibs.30.dylib
Error: While modifying Mach-O slice 0: No such dylib name: @@HOMEBREW_CELLAR@@/wine/2.0/libexec/lib/libnetsnmpmibs.30.dylib
```

Brew doctor returns only `Your system is ready to brew.`.

**I've upgraded many other brews today and all of them were OK.**

**Comment by ilovezfs** [comment]
What does `brew config` report?

**Comment by Marqin** [comment]
```
$ brew config
HOMEBREW_VERSION: 1.1.10
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69d1cedd12d37d6a9535fbba17d2129b165c08f8
Last commit: 6 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 215b8d5816f1bd079bf8c5873b3d2970a53b9a84
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /Users/marqin/perl5/perlbrew/perls/perl-5.10.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/marqin/.rvm/rubies/ruby-2.2.3/bin/ruby
Java: 1.8.0
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by ilovezfs** [comment]
OK, your brew is quite outdated (it should be at version 1.1.11 not 1.1.10). Did you run `brew update`?

**Comment by Marqin** [comment]
Yes, I did. I also did run `brew upgrade` and it upgraded many packages, apart from that one - `wine`.

Now I run again `brew update` and `brew config` still shows `1.1.10`.

**Comment by ilovezfs** [comment]
what does
```
git -C `brew --repo` status
```
say?

**Comment by Marqin** [comment]
```
$ git -C `brew --repo` status
On branch stable
nothing to commit, working tree clean
```

**Comment by ilovezfs** [comment]
```
git -C `brew --repo` tag -l
```

**Comment by Marqin** [comment]
```
$ git -C `brew --repo` tag -l
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.7.1
0.8
0.8.1
0.9
0.9.1
0.9.2
0.9.3
0.9.4
0.9.5
0.9.8
0.9.9
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.1.1
1.1.10
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.1.9
```

**Comment by ilovezfs** [comment]
@Marqin fixed?

**Comment by ilovezfs** [comment]
I'm assuming this is fixed now. Please let us know if it's still a problem.

**Comment by Marqin** [comment]
@ilovezfs I just noticed that my brew is on branch `stable` and there is no such branch on Github - https://github.com/Homebrew/brew - might this be a issue?

**Comment by ilovezfs** [comment]
That is normal. Did you follow the steps above?

**Comment by Marqin** [comment]
Yes, I just used those commands and seems wine is installing correctly.
But why did my homebrew clogged?

**Comment by ilovezfs** [comment]
If for whatever reason a brew update does not get the new tag (I don't know why it missed 1.1.11 in your specific case), then you'll be stuck on the prior tag until we push out a new one. Since we haven't pushed out 1.1.12 yet, you were stuck on 1.1.10 until then.
