### ISSUE TITLE
gem broken after updating to ruby 2.4.1_1

### ISSUE THREAD

**Issue by tinhkyaw** [Homebrew/homebrew-core#11728]
I am seeing the following error whenever I try to run gem after updating to the latest ruby 2.4.1_1:

> gem
> /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/yaml.rb:5:in `<top (required)>':
> It seems your ruby installation is missing psych (for YAML output).
> To eliminate this warning, please install libyaml and reinstall your ruby.
> /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib (LoadError)
>   Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.bundle
>   Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.bundle
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/lib/ruby/gems/2.4.0/gems/psych-2.2.4/lib/psych.rb:8:in `<top (required)>'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/yaml.rb:6:in `<top (required)>'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems.rb:700:in `load_yaml'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/config_file.rb:340:in `load_file'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/config_file.rb:202:in `initialize'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/gem_runner.rb:75:in `new'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/gem_runner.rb:75:in `do_configuration'
> 	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/gem_runner.rb:40:in `run'
> 	from /usr/local/bin/gem:21:in `<main>'

I tried uninstalling libyaml and ruby many times but the problem still persists.

Here is the output of `brew doctor`:

>  brew doctor
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
> 
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>   /Users/tinhkyaw/anaconda3/bin/curl-config
>   /Users/tinhkyaw/anaconda3/bin/freetype-config
>   /Users/tinhkyaw/anaconda3/bin/icu-config
>   /Users/tinhkyaw/anaconda3/bin/libpng-config
>   /Users/tinhkyaw/anaconda3/bin/libpng16-config
>   /Users/tinhkyaw/anaconda3/bin/python3-config
>   /Users/tinhkyaw/anaconda3/bin/python3.6-config
>   /Users/tinhkyaw/anaconda3/bin/python3.6m-config
>   /Users/tinhkyaw/anaconda3/bin/xml2-config
>   /Users/tinhkyaw/anaconda3/bin/xslt-config
> 
> Warning: Unbrewed dylibs were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected dylibs:
>   /usr/local/lib/libaspell.15.dylib
>   /usr/local/lib/libpspell.15.dylib
> 
> Warning: Unbrewed header files were found in /usr/local/include.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected header files:
>   /usr/local/include/aspell.h
>   /usr/local/include/pspell/pspell.h
>   /usr/local/include/python2.7/greenlet/greenlet.h
> 
> Warning: Unbrewed .la files were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected .la files:
>   /usr/local/lib/libaspell.la
>   /usr/local/lib/libpspell.la

and `brew config`:

> brew config
> HOMEBREW_VERSION: 1.1.11
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 394f9fa0aaa5854aa52bc589708a079665dcf462
> Last commit: 3 weeks ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: bfe7eefdf2c591c56742b6d07aa09fe2bf53746f
> Core tap last commit: 5 hours ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: quad-core 64-bit broadwell
> Homebrew Ruby: 2.0.0-p648
> Clang: 8.1 build 802
> Git: 2.12.2 => /usr/local/bin/git
> Perl: /usr/bin/perl
> Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
> Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
> Java: 1.8.0_121, 1.7.0_80
> macOS: 10.12.4-x86_64
> Xcode: 8.3
> CLT: N/A
> X11: 2.7.11 => /opt/X11

Please let me know if you need any additional information.  Thanks in advance!

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/11636.

**Comment by tinhkyaw** [comment]
I see.  Thanks!
