### ISSUE TITLE
mongodb fails to build

### ISSUE THREAD

**Issue by teslamint** [Homebrew/homebrew-core#11739]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

https://gist.github.com/teslamint/6829373c89478bb6f1f789989b0c0057

**Comment by yurikoles** [comment]
Another one is affected here.

https://gist.github.com/yurikoles/fa80e430514f5e4b7ddfca04ad1b8651

**Comment by ojab** [comment]
There is an issue with`mongoreplay`, actually:
```
ojab-notebook:mongodb--github.com-mongodb-mongo-tools--git ojab$ ./bin/mongoreplay
Killed: 9
ojab-notebook:mongodb--github.com-mongodb-mongo-tools--git ojab$ sudo dtruss ./bin/mongoreplay
dtrace: failed to execute ./bin/mongoreplay: unknown error
ojab-notebook:mongodb--github.com-mongodb-mongo-tools--git ojab$ lldb ./bin/mongoreplay
(lldb) target create "./bin/mongoreplay"
Current executable set to './bin/mongoreplay' (x86_64).
(lldb) run
error: error: ::posix_spawnp ( pid => 9571, path = './bin/mongoreplay', file_actions = 0x7fff5b7a5f08, attr = 0x7fff5b7a5f18, argv = 0x7ff62e6246b0, envp = 0x7ff62fb45200 ) err = Cannot allocate memory (0x0000000c)
(lldb)
```
so it's really a `go` issue. `brew upgrade go --HEAD` fixes mongodb build.

**Comment by teslamint** [comment]
@ojab hmm, that's weird. BrewTestBot builds mongodb without problem. https://bot.brew.sh/job/Homebrew%20Core/19503/version=sierra/testReport/brew-test-bot/sierra/install_mongodb/

**Comment by teslamint** [comment]
Looks like CLT for Xcode 8.3 breaks it: https://github.com/golang/go/issues/19734
