### ISSUE TITLE
Byobu fails to find interpreter since newt bumped to python@3.11

### ISSUE THREAD

**Issue by vemek** [Homebrew/homebrew-core#117482]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.6.14-37-g7ecc079
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7ecc079cc21d320d7ad8b2433840363499cbb7a5
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 64dbb36bcaf850924b361de143030d2d6f0ce055
Core tap last commit: 61 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 13.3.1
Rosetta 2: false

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.4
Warning: Use glib instead of deprecated glib-utils
```

Please note that I did not resolve the PHP deprecation (as it is unrelated and I rely on it) and cannot remove glib-utils due to dependencies from many other packages.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run the `byobu` program, which has been working on my system previously.

### What happened (include all command output)?

`byobu` is looking for the `python3` interpreter in the python 3.11 bindir, which does not have that symlink:
```
❯ byobu
/opt/homebrew/Cellar/byobu/5.133_2/libexec/byobu-select-session: line 24: /opt/homebrew/opt/python@3.11/bin/python3: No such file or directory
```

### What did you expect to happen?

`byobu` should not exit with an error.

The issue is caused by [`newt`'s upgrade to python 3.11](https://github.com/Homebrew/homebrew-core/pull/115548). [Byobu selects a python interpreter by looking at `newt`'s deps](https://github.com/Homebrew/homebrew-core/blob/64dbb36bcaf850924b361de143030d2d6f0ce055/Formula/byobu.rb#L38-L41) and adding `python3` to the bin path:
```ruby
    byobu_python = Formula["newt"].deps
                                  .find { |d| d.name.match?(/^python@\d\.\d+$/) }
                                  .to_formula
                                  .opt_bin/"python3"
```
This worked previously for python versions that shipped a `python3` symlink, however 3.11 does not. I can fix this issue by explicitly choosing an interpreter or by pointing the symlink at `.opt_bin/"python3.11"`, but neither seem like an acceptable solution. Happy to take suggestions for a more robust fix and open a PR if you'd like.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install byobu
byobu
```

**Comment by branchvincent** [comment]
Thanks for the report! Fixed by #118283, so you can just upgrade as usual: `brew update && brew upgrade byobu`
