### ISSUE TITLE
jxrlib: include JXRMeta.h error

### ISSUE THREAD

**Issue by iewchen** [Homebrew/homebrew-core#117415]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Brew itself is OK. The jxrlib package has a bug need fix.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Build an application that requires jxrlib.

### What happened (include all command output)?

Build error due to a bug in JXRMeta.h.

### What did you expect to happen?

Line 37 of JXRMeta.h is:

```code
#endif UNREFERENCED_PARAMETER
```

Need remove or comment out "UNREFERENCED_PARAMETER". Upstream debian jxrlib 1.1-6 fixed this probelm (debian/patches/typos.patch), among other things. Could homebrew sync to a newer version of jxrlib? Thanks!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Running brew won't show error. It only happen when actually build application with jxrlib, i.e. include the header file JXRMeta.h.
```

**Comment by SMillerDev** [comment]
Needs to be reported upstream if it's not a brew bug

**Comment by iewchen** [comment]
Brew as a package manager is OK. The jxrlib packaged by brew has a bug, which had been fixed in upstream.

**Comment by SMillerDev** [comment]
Has that fix been released in a stable version by upstream?

**Comment by iewchen** [comment]
Yes.
https://formulae.brew.sh/formula/jxrlib shows its upstream is https://tracker.debian.org/pkg/jxrlib . 1.1-6 is the stable version in Debian since 2017.

**Comment by SMillerDev** [comment]
And Homebrew is using 1.1 from debian so that should already be fixed.
