### ISSUE TITLE
node: node binary is not signed (compiled instead of official build download)

### ISSUE THREAD

**Issue by bgalek** [Homebrew/homebrew-core#117452]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew info node
==> node: stable 19.2.0 (bottled), HEAD
Platform built on V8 to build network applications
https://nodejs.org/
/usr/local/Cellar/node/19.1.0 (1,963 files, 52.4MB) *
  Poured from bottle on 2022-11-21 at 10:36:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/node.rb
License: MIT
==> Dependencies
Build: pkg-config ✔, python@3.10 ✔
Required: brotli ✔, c-ares ✔, icu4c ✔, libnghttp2 ✔, libuv ✔, openssl@1.1 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 484,849 (30 days), 1,470,723 (90 days), 5,320,924 (365 days)
install-on-request: 427,750 (30 days), 1,305,632 (90 days), 4,685,367 (365 days)
build-error: 59 (30 days)
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to exclude `node` process out of my antivirus (CORTEX XDR) - for my builds to be faster.

### What happened (include all command output)?

After `brew install node`, node binary is not signed

```
codesign -dv --verbose=4 /usr/local/bin/node
/usr/local/bin/node: code object is not signed at all
```

### What did you expect to happen?

The binary is downloaded from official nodejs.org site and signed so that it can be whitelisted in my AV solutions.

`codesign -dv --verbose=4 /usr/local/bin/node`

```
Executable=/Users/xxx/node-v18.12.1-darwin-x64/bin/node
Identifier=node
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=687728 flags=0x10000(runtime) hashes=21483+5 location=embedded
VersionPlatform=1
VersionMin=659200
VersionSDK=659206
Hash type=sha256 size=32
CandidateCDHash sha256=ac56500407be106277ee3ace316afb900f92afd6
CandidateCDHashFull sha256=ac56500407be106277ee3ace316afb900f92afd6443de2e0aee5e6db5ee44896
Hash choices=sha256
CMSDigest=ac56500407be106277ee3ace316afb900f92afd6443de2e0aee5e6db5ee44896
CMSDigestType=2
Page size=4096
Launch Constraints:
	None
CDHash=ac56500407be106277ee3ace316afb900f92afd6
Signature size=8985
Authority=Developer ID Application: Node.js Foundation (HX7739G8FX)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=4 Nov 2022 at 18:51:31
Info.plist=not bound
TeamIdentifier=HX7739G8FX
Runtime Version=10.15.6
Sealed Resources=none
Internal requirements count=1 size=164
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install node`
`codesign -dv --verbose=4 /usr/local/bin/node`
```

**Comment by SMillerDev** [comment]
Homebrew doesn't sign the binaries it builds.

**Comment by bgalek** [comment]
@SMillerDev yes, i understand, but why does it build instead of download binary in the first place?

**Comment by MikeMcQuaid** [comment]
> yes, I understand, but why does node formula build binaries from sources instead of download official binaries in the first place?

@bgalek That's how most package managers work.

> i.e. java cask downloads official binaries, so "java" is signed properly!

And `openjdk` does not and is not.

---

Casks are generally signed, formulae are not.

**Comment by Kentzo** [comment]
> Casks are generally signed, formulae are not.

Hmm, but the bottles of CLI tools that homebrew downloads do have an adhoc signature.
