### ISSUE TITLE
purescript 0.11.1 bottle is incomplete

### ISSUE THREAD

**Issue by FranklinChen** [Homebrew/homebrew-core#11778]
purescript 0.11.1 bottle only includes `purs` in `bin` but not

- psc
- psc-bundle
- psc-docs
- psc-hierarchy
- psc-ide-client
- psc-ide-server
- psc-publish
- psci

**Comment by ilovezfs** [comment]
Yeah those were all combined into one binary. So psc is
```
purs compile "$@"
```

psc-bundle is
```
purs bundle "$@"
```
etc.

I'll look at packaging the new wrappers too.

**Comment by ilovezfs** [comment]
OK, they're here: https://github.com/purescript/purescript/tree/master/scripts

I'll add them to the bottle.

**Comment by ilovezfs** [comment]
@FranklinChen https://github.com/Homebrew/homebrew-core/issues/11778

**Comment by ilovezfs** [comment]
@FranklinChen https://github.com/Homebrew/homebrew-core/issues/11779.

**Comment by ilovezfs** [comment]
@FranklinChen `brew update` and `brew upgrade purescript` and it should be fixed.

**Comment by ilovezfs** [comment]
@FranklinChen Do you use those scripts directly or only via tooling? I'm asking due to https://github.com/purescript/purescript/pull/2952#issuecomment-314403036

**Comment by FranklinChen** [comment]
@ilovezfs I don't use them directly, only through Pulp currently.
