### ISSUE TITLE
Formula Request: woof2 font converter

### ISSUE THREAD

**Issue by FinalDes** [Homebrew/homebrew-core#11771]
add woff2_compress and woff2_decompress into brew recipe
https://github.com/google/woff2

**Comment by FinalDes** [comment]
duplicate issue

**Comment by FinalDes** [comment]
have bug when install using homebrew/boneyard/woff2

**Comment by bfontaine** [comment]
Also, we don’t do formula requests. You can make a pull-request if you want a formula in Homebrew.

**Comment by fxcoudert** [comment]
That software does not have any released version. It is Homebrew's policy to only integrate software with a well-defined release process and released versions, considered as stable by their maintainers.
