### ISSUE TITLE
libarchive 3.6.2 has bugs

### ISSUE THREAD

**Issue by leleliu008** [Homebrew/homebrew-core#117869]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

a cmake project using libarchive:

```
cmake
 pkg_check_modules(PKG_CONFIG_LIBARCHIVE libarchive)
```

### What happened (include all command output)?

```
prefix=/usr/local/Cellar/libarchive/3.6.2
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libarchive
Description: library that can create and read several streaming archive formats
Version: 3.6.2
Cflags: -I${includedir}
Cflags.private: -DLIBARCHIVE_STATIC
Libs: -L${libdir} -larchive
Libs.private: -lexpat -llzma -lzstd -llz4 -lb2 -lbz2 -lz
Requires.private: iconv
```
Starting with 3.6.2 iconv is now in Requires.private, which breaks pkgconf because iconv doesn't install a .pc file.

```
-- Checking for module 'libarchive'
-- Package 'iconv', required by 'libarchive', not found
```
Reference:https://github.com/libarchive/libarchive/issues/1766

### What did you expect to happen?

cmake can successfully invoke pkg_check_modules(PKG_CONFIG_LIBARCHIVE libarchive)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libarchive
```

**Comment by cho-m** [comment]
Looks like there are at least 4 different PRs upstream for this:
- https://github.com/libarchive/libarchive/pull/1812 **(closed)**
- https://github.com/libarchive/libarchive/pull/1813 **(open)**
- https://github.com/libarchive/libarchive/pull/1817 **(open)**
- https://github.com/libarchive/libarchive/pull/1825 **(merged)**

---

Sadly, the one that got merged (last PR) may not help on macOS where `-liconv` is used. It may help on Linux where it is available in glibc.

**Comment by leleliu008** [comment]
Two weeks have passed, I can't believe there is no one maintainer want to resolve this simple problem. They are just wating for the next release rather than making a patch to let it works.

**Comment by SMillerDev** [comment]
We don't do patches that aren't accepted upstream. Debian did and it made their security worthless: 
https://www.debian.org/security/2008/dsa-1571 if you want a fix, work with the libarchive developers.

**Comment by Kagami** [comment]
Just remove `iconv` from `Requires.private` at `/opt/homebrew/opt/libarchive/lib/pkgconfig/libarchive.pc` if you need to make it work now.

**Comment by MikeMcQuaid** [comment]
> I can't believe there is no one maintainer want to resolve this simple problem.

@leleliu008 not going to keep your issues open when you speak to us like this. If it's so simple: you do it (complying with our documented patch policies).

**Comment by antony-jr** [comment]
For those who need a fix for their CI/CD,

```
 brew install gnu-sed
 gsed -i '/Requires.private: iconv/d' /usr/local/opt/libarchive/lib/pkgconfig/libarchive.pc
```
