### ISSUE TITLE
Cant run qemu after installing it with brew

### ISSUE THREAD

**Issue by njmulsqb** [Homebrew/homebrew-core#118043]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11cdffb4fef84828a7e02860212b30ce4fac85f5
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9fd0813ca63e1e926e1f760737c64881b9e8c6f8
Core tap last commit: 20 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
Rosetta 2: false

Your system is ready to brew
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install and run qemu

### What happened (include all command output)?

I installed qemu using `brew install qemu` and when trying to run it gives the following error  `zsh: command not found: qemu` whereas I have other tools installed using brew like `brew install amass` are working fine.

### What did you expect to happen?

The qemu icon should appear in the applications launchpad and it should launch via `qemu` command in terminal as well.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install qemu`
2. `qemu`
```

**Comment by SMillerDev** [comment]
There is no such executable `brew ls qemu | grep /bin` will tell you which ones do exist.

> The qemu icon should appear in the applications launchpad 

Formulae don't install GUI applications.
