### ISSUE TITLE
Homebrew Does Not Ignore .curlrc

### ISSUE THREAD

**Issue by dolvany** [Homebrew/homebrew-core#11806]
### Bug reports:

If I do something like the following, things get quite interesting when I try to install a package. Perhaps a curl -q is more appropriate.

echo '--url https://www.google.com/' > ~/.curlrc

**Comment by ilovezfs** [comment]
This is intentional. See https://github.com/Homebrew/brew/blob/b757c927afe7abb5d284cf28dc7d5e3321dba14c/Library/Homebrew/diagnostic.rb#L502-L515
