### ISSUE TITLE
Formula request: bloaty

### ISSUE THREAD

**Issue by AlekSi** [Homebrew/homebrew-core#11803]
https://github.com/google/bloaty

**Comment by Stellarspace** [comment]
It's a simple build.
```bash
$ brew install git
$ git clone https://github.com/google/bloaty.git
$ cd bloaty
$ make
```

**Comment by FinalDes** [comment]
@Stellarspace I think @AlekSi how to make recipe form that app?

**Comment by fxcoudert** [comment]
That software does not have any released version: https://github.com/google/bloaty/releases . It is Homebrew's policy to only integrate software with a well-defined release process and released versions, considered as stable by their maintainers.

**Comment by bfontaine** [comment]
Also, we don’t do formula requests. You can make a pull-request if you want a formula in Homebrew.
