### ISSUE TITLE
golangci-lint requires diffutils

### ISSUE THREAD

**Issue by jzelinskie** [Homebrew/homebrew-core#118149]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
$ brew config && brew doctor
HOMEBREW_VERSION: 3.6.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11cdffb4fef84828a7e02860212b30ce4fac85f5
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5101cf7ea662f37e1b5d6288b4d079709744b535
Core tap last commit: 12 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.38.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.1
Rosetta 2: false
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to lint one of my Go projects.

golangci-lint has a runtime requirement for diffutils on macOS or else some of its linters cease to function.

See https://github.com/golangci/golangci-lint/issues/3087

It looks like the next release might not require this.

### What happened (include all command output)?

The linter failed because the native macOS diff functions differently from the diff in other platforms.

From the upstream issue I cited:

```
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649. 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goimports: can't extract issues from gofmt diff output "--- /Users/jacek.leszczynski/RiderProjects/reporting-tools/go/rot/client/reporting.go.orig\t2022-08-10 12:30:31\n+++ /Users/jacek.leszczynski/RiderProjects/reporting-tools/go/rot/client/reporting.go\t2022-08-10 12:30:31\n@@ -4,8 +4,9 @@\n \t\"context\"\n \t\"encoding/json\"\n \t\"fmt\"\n-\t\"github.com/Fonoa-Tech/reporting-api/generated/contracts\"\n \t\"net/url\"\n+\n+\t\"github.com/Fonoa-Tech/reporting-api/generated/contracts\"\n )\n \n type ReportingClient struct {\n": can't parse patch: parsing time "2022-08-10 12:30:31" as "2006-01-02 15:04:05 -0700": cannot parse "" as "-0700"
```

### What did you expect to happen?

The lint to execute without crashing.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install golangci-lint
golangci-lint run
```
```

**Comment by carlocab** [comment]
The output of `brew config` and `brew doctor` is required for all bug reports in this repository. We can reopen this when you provide the requested information.

**Comment by jzelinskie** [comment]
Updated to have the brew output

**Comment by dawidd6** [comment]
Instead of depending on diffutils, we can just add this patch https://github.com/golangci/golangci-lint/commit/58ebedda6341e2f67d4338eb1d8f75b4a54590d1 and remove it on new release.

**Comment by chenrui333** [comment]
@jzelinskie I have included the go-diff patch, can you give that a try with `brew upgrade golangci-lint`? Thanks!

**Comment by cho-m** [comment]
Closing as should be fixed now. Let us know if there are still issues.
