### ISSUE TITLE
brew install node@16 fails on MacOS Mojave (10.14.6)

### ISSUE THREAD

**Issue by MalayTripathi** [Homebrew/homebrew-core#118175]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Brew Config

HOMEBREW_VERSION: 3.6.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 11cdffb4fef84828a7e02860212b30ce4fac85f5
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1fdce20960fedc5cd7dbcde09c27e029a7dcac22
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 10.0.1 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A

Brew Doctor

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.

Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install node@16 on MacOS Mojave (10.14.6). It's specifically needed to install MongoDB community edition version 6.0.1 which supports MacOS 10.14 and above. The installation of node@16 which in turn install node v16.19.0 fails with the error mentioned below. I have gcc 12.2.0.

### What happened (include all command output)?

$ brew install node@16
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching node@16
==> Downloading https://nodejs.org/dist/v16.19.0/node-v16.19.0.tar.xz
Already downloaded: /Users/malay/Library/Caches/Homebrew/downloads/02a127506ed614b2245c3f8d0ca3b97bc8ee1a167e83511bbc0393a854281263--node-v16.19.0.tar.xz
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.

==> python3.11 configure.py --prefix=/usr/local/Cellar/node@16/16.19.0 --with-intl=system-icu --shared-libuv --shared-nghttp2 --shared-openssl --shared-zlib --shared-brotli --shared-cares --shared-libuv-i
==> make install
Last 15 lines from /Users/malay/Library/Logs/Homebrew/node@16/02.make:
  gcc-12 -o /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/codec_choose.o ../deps/base64/base64/lib/codec_choose.c '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_CERT_STORE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DBASE64_STATIC_DEFINE' '-DHAVE_SSSE3=1' '-DHAVE_SSE41=1' '-DHAVE_SSE42=1' '-DHAVE_AVX=1' '-DHAVE_AVX2=1' -I/usr/local/opt/libuv/include -I/usr/local/opt/brotli/include -I/usr/local/opt/c-ares/include -I/usr/local/opt/libnghttp2/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/Cellar/icu4c/71.1/include -I../deps/base64/base64/include -I../deps/base64/base64/lib  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/.deps//private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/codec_choose.o.d.raw   -c
  gcc-12 -o /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/lib.o ../deps/base64/base64/lib/lib.c '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_CERT_STORE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DBASE64_STATIC_DEFINE' '-DHAVE_SSSE3=1' '-DHAVE_SSE41=1' '-DHAVE_SSE42=1' '-DHAVE_AVX=1' '-DHAVE_AVX2=1' -I/usr/local/opt/libuv/include -I/usr/local/opt/brotli/include -I/usr/local/opt/c-ares/include -I/usr/local/opt/libnghttp2/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/Cellar/icu4c/71.1/include -I../deps/base64/base64/include -I../deps/base64/base64/lib  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/.deps//private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/lib.o.d.raw   -c
  gcc-12 -o /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/arch/neon32/codec.o ../deps/base64/base64/lib/arch/neon32/codec.c '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_CERT_STORE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DBASE64_STATIC_DEFINE' '-DHAVE_SSSE3=1' '-DHAVE_SSE41=1' '-DHAVE_SSE42=1' '-DHAVE_AVX=1' '-DHAVE_AVX2=1' -I/usr/local/opt/libuv/include -I/usr/local/opt/brotli/include -I/usr/local/opt/c-ares/include -I/usr/local/opt/libnghttp2/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/Cellar/icu4c/71.1/include -I../deps/base64/base64/include -I../deps/base64/base64/lib  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/.deps//private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/arch/neon32/codec.o.d.raw   -c
  gcc-12 -o /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/arch/neon64/codec.o ../deps/base64/base64/lib/arch/neon64/codec.c '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_CERT_STORE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DBASE64_STATIC_DEFINE' '-DHAVE_SSSE3=1' '-DHAVE_SSE41=1' '-DHAVE_SSE42=1' '-DHAVE_AVX=1' '-DHAVE_AVX2=1' -I/usr/local/opt/libuv/include -I/usr/local/opt/brotli/include -I/usr/local/opt/c-ares/include -I/usr/local/opt/libnghttp2/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/Cellar/icu4c/71.1/include -I../deps/base64/base64/include -I../deps/base64/base64/lib  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/.deps//private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/base64/deps/base64/base64/lib/arch/neon64/codec.o.d.raw   -c
  g++-12 -o /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/gtest/deps/googletest/src/gtest-death-test.o ../deps/googletest/src/gtest-death-test.cc '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-DNODE_OPENSSL_CONF_NAME=nodejs_conf' '-DNODE_OPENSSL_CERT_STORE' '-D_DARWIN_USE_64_BIT_INODE=1' '-DGTEST_HAS_POSIX_RE=0' '-DGTEST_LANG_CXX11=1' -I/usr/local/opt/libuv/include -I/usr/local/opt/brotli/include -I/usr/local/opt/c-ares/include -I/usr/local/opt/libnghttp2/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/Cellar/icu4c/71.1/include -I../deps/googletest -I../deps/googletest/include  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++14 -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF /private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/.deps//private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/gtest/deps/googletest/src/gtest-death-test.o.d.raw   -c
In file included from ../deps/googletest/include/gtest/internal/gtest-death-test-internal.h:39,
                 from ../deps/googletest/include/gtest/gtest-death-test.h:41,
                 from ../deps/googletest/src/gtest-death-test.cc:33:
../deps/googletest/include/gtest/gtest-matchers.h:38:10: fatal error: atomic: No such file or directory
   38 | #include <atomic>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [/private/tmp/nodeA16-20221215-9728-1c8l874/node-v16.19.0/out/Release/obj.target/gtest/deps/googletest/src/gtest-death-test.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [node] Error 2

### What did you expect to happen?

Successful installation of node@16 -> v16.19.0

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install node@16
```

**Comment by cho-m** [comment]
```
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
```
