### ISSUE TITLE
`docutils`: symlink to "invalid interpreter" in Linux bottle

### ISSUE THREAD

**Issue by ticky** [Homebrew/homebrew-core#118458]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.15-33-g884c4be
ORIGIN: https://github.com/Homebrew/brew
HEAD: 884c4bec14073314ac6e8e9a6a64bc3b26161ab6
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d5b16cd642606cef70f717aa2ed6197332af4904
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit zen
/home/linuxbrew/.linuxbrew/bin/clang: error while loading shared libraries: libz3.so.4.11: cannot open shared object file: No such file or directory
Clang: N/A
Git: 2.35.0 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.13.0-valve21.3-1-neptune x86_64 GNU/Linux
OS: SteamOS Holo (Holo)
Host glibc: 2.33
/usr/bin/gcc: 11.1.0
/usr/bin/ruby: N/A
glibc: 2.35_1
gcc@11: N/A
gcc: 12.2.0
xorg: N/A
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo ticky/steamos) checkout

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /home/linuxbrew/.linuxbrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Preparing a formula which depends on `docutils`' `rst2man` utility on Linux.

In doing so, I made my forumla `depends_on "docutils"`.

### What happened (include all command output)?

Linuxbrew installed `docutils` as expected, and the build proceeded, but at the critical point where `rst2man` was called upon, I got an "invalid interpreter" error, citing an absolute path to a `python@3.11` binary, which does not exist.

It appears that while `docutils` will likely be able to use the system Python on macOS, on Linux it is dependent on a Homebrew version, and in this case, it is not marked as a runtime dependency.

### What did you expect to happen?

`docutils` should have had a _runtime_ dependency on _some version_ of `python`, and therefore run as expected.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install docutils
head -n 1 $(which rst2man)
rst2man
```

**Comment by cho-m** [comment]
Should be fixed now as refactored formula in #118471 to use single python (`python@3.11`) everywhere.
