### ISSUE TITLE
MySQL Disabling "secure-file-priv"

### ISSUE THREAD

**Issue by tomrossi7** [Homebrew/homebrew-core#11853]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with specific formulae and not Homebrew/brew?

### Bug reports:

$ brew gist-logs mysql@5.6
https://gist.github.com/22977f0d4d31c397f734e338e4af9599

I had to reinstall MySQL 5.6 (mysql@5.6 formula) and this is the first time I've seen this issue. Basically, the new install appears to be enabling the --secure-file-priv option and I can't find where to disable it.

**"The MySQL server is running with the --secure-file-priv option so it cannot execute this statement"**

Where does Brew set this option?

**Comment by MikeMcQuaid** [comment]
> This isn't something we configure specifically so I'm afraid we can't help here.
https://github.com/Homebrew/homebrew-versions/issues/1552

Don't just reopen the same issue with the same text.

**Comment by tomrossi7** [comment]
@MikeMcQuaid I am trying to get help and doing exactly what the readme said.
