### ISSUE TITLE
audit --strict --online failures

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#11869]
Excludes audit failures due to missing test-do blocks.

- [x] ats2-postiats: (https://github.com/Homebrew/homebrew-core/pull/11886)
  * Description is too long. "name: desc" should be less than 80 characters.
    Length is calculated as ats2-postiats + desc. (currently 105)
- [x] dxpy:
  * Can't find conflicting formula "android-sdk".
- [x] mecab-ipadic: (https://github.com/Homebrew/homebrew-core/pull/11901)
  * Options should begin with with/without. Migrate '--charset=' with `deprecated_option`.
- [x] mecab-jumandic: (https://github.com/Homebrew/homebrew-core/pull/11902)
  * Options should begin with with/without. Migrate '--charset=' with `deprecated_option`.
- [x] clipsafe:
  * Stable resource "DateTime": The URL http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/DateTime-1.03.tar.gz is not reachable (HTTP status code 404)
- [x] couchdb:
  * HEAD: The URL https://git-wip-us.apache.org/repos/asf/couchdb.git is not a valid git URL
- [x] net-snmp: (https://sourceforge.net/p/net-snmp/bugs/2769/)
  * The URL http://www.net-snmp.org/ is not reachable
- [x] nikto: (https://github.com/sullo/nikto/issues/466)
  * Stable: The URL https://cirt.net/nikto/nikto-2.1.5.tar.bz2 is not reachable
  * The URL https://cirt.net/nikto2 is not reachable
- [x] pcre++:
  * Stable: The URL http://www.daemon.de/idisk/Apps/pcre++/pcre++-0.9.5.tar.gz could use HTTPS rather than HTTP
  * The URL http://www.daemon.de/PCRE could use HTTPS rather than HTTP

**Comment by fxcoudert** [comment]
`nikto` issue is expired certificate, which I reported to them: https://github.com/sullo/nikto/issues/466

**Comment by ilovezfs** [comment]
Indeed, thank you for doing that.

**Comment by ilovezfs** [comment]
@fxcoudert looks like the download link can be degraded to http but the homepage cannot. So we could use GitHub for the homepage. There's also a mirror for the download here

http://pkgs.fedoraproject.org/repo/pkgs/nikto/nikto-2.1.5.tar.bz2/35ac9f11ab4aa0d5b8449748338bd159/nikto-2.1.5.tar.bz2

**Comment by fxcoudert** [comment]
They seem pretty active and it's a recent issue, so maybe we can just wait a few days before doing that?

**Comment by ilovezfs** [comment]
Yep sure. Another option is the debian _orig tarballs: https://mirrors.ocf.berkeley.edu/debian/pool/non-free/n/nikto/nikto_2.1.5.orig.tar.gz

**Comment by fxcoudert** [comment]
`net-snmp` website down, reported https://sourceforge.net/p/net-snmp/bugs/2769/
