### ISSUE TITLE
ipmitool 1.8.19 bottles are broken

### ISSUE THREAD

**Issue by stek29** [Homebrew/homebrew-core#118705]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I don't think these are relevant in this case, since all bottles are broken.
See next comment for example.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed bottled `ipmitool` on Ventura and wanted to use it

However, it fails because `enterprise-numbers` file is incorrect -- it contains some HTML file instead of actual `enterprise-numbers`

Doing `curl https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers -o "$(brew --cellar ipmitool)/ipmitool/1.8.19/share/misc/enterprise-numbers"` fixes `ipmitool`

### What happened (include all command output)?

```
$ ipmitool -V
ipmitool version 1.8.19

$ ipmitool
Failed to initialize the OEM info dictionary

$ curl https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers -o "$(brew --cellar ipmitool)/ipmitool/1.8.19/share/misc/enterprise-numbers"

$ ipmitool
No hostname specified!
```

### What did you expect to happen?

I expected ipmitool installed from bottle to be functional

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall ipmitool || brew install ipmitool
ipmitool
```

**Comment by stek29** [comment]
```
❯ grep sha256 $(brew --repo homebrew/core)/Formula/ipmitool.rb | awk '/: /{print$2" "$3}' | tr -d '"' | while read -r name sha; do echo -n $name; curl --location -qs -H 'Authorization: Bearer QQ==' https://ghcr.io/v2/homebrew/core/ipmitool/blobs/sha256:$sha | tar -zxOf - ipmitool/1.8.19/share/misc/enterprise-numbers | file -; done
arm64_ventura:/dev/stdin: HTML document text, ASCII text
arm64_monterey:/dev/stdin: HTML document text, ASCII text
arm64_big_sur:/dev/stdin: HTML document text, ASCII text
ventura:/dev/stdin: HTML document text, ASCII text
monterey:/dev/stdin: HTML document text, ASCII text
big_sur:/dev/stdin: HTML document text, ASCII text
x86_64_linux:/dev/stdin: HTML document text, ASCII text
```

bottles for *all* platforms are broken, this is why my config is irrelevant

**Comment by MikeMcQuaid** [comment]
> ```shell
> I don't think these are relevant in this case, since all bottles are broken.
> ```

Can you please just supply your `brew config` at least anyway?

**Comment by Bo98** [comment]
Looks like we need to apply https://github.com/ipmitool/ipmitool/commit/1edb0e27e44196d1ebe449aba0b9be22d376bcb6

**Comment by stek29** [comment]
@MikeMcQuaid how is `brew config` relevant? I’ve demonstrated with curl that all bottles are broken, no matter OS/arch or brew configuration.
I’m sorry, I just don’t get it — the issue is reproducible no matter what brew config would display, or am I missing something?

**Comment by carlocab** [comment]
> I’m sorry, I just don’t get it — the issue is reproducible no matter what brew config would display, or am I missing something?

This information is required, regardless of perceived relevance. See the issue template:

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

We can reopen this once the required information is provided.

**Comment by MikeMcQuaid** [comment]
> I’m sorry, I just don’t get it

Specifically: it helps us to verify e.g. what revision of homebrew-core you are on, if you have anything that could be causing corrupted bottle downloads (e.g. a 3rd-party mirror) etc.

More generally: because we ask for it and it's a waste of everyone's time when you decide you know better than to provide the information we've asked for.

**Comment by stek29** [comment]
@MikeMcQuaid I agree that not doing what expected might waste maintainers’ time, sorry on that. Thank you for putting your time into responding.

However, this time looking into my brew configuration might’ve actually wasted just as much maintainers’ time — as I’ve demonstrated, bottles stay broken no matter what, just downloading them with curl|tar shows that they’re broken.

Sorry for doing something that started this discussion and did waste everyone’s time.

I understand that people might be wrong when deciding that those steps don’t matter — so closing every issue no matter what might be a more sustainable way to keep issue report quality higher, even if it means applying the policy where it doesn’t make sense.

The issue has been fixed anyway, and formula tests have been improved — thank you @chenrui333 :)

**Comment by MikeMcQuaid** [comment]
> I understand that people might be wrong when deciding that those steps don’t matter — so closing every issue no matter what might be a more sustainable way to keep issue report quality higher, even if it means applying the policy where it doesn’t make sense.

This, yup.
