### ISSUE TITLE
brew install gcc, errors in RHEL6 with centos6 repository

### ISSUE THREAD

**Issue by kaji331** [Homebrew/homebrew-core#1188]
➜   brew install gcc                   
==> Installing dependencies for gcc: gmp, mpfr, libmpc, isl
==> Installing gcc dependency: gmp
==> Downloading https://linuxbrew.bintray.com/bottles/gmp-6.1.0.x86_64_linux.bot
Already downloaded: /home/cancer/.cache/Homebrew/gmp-6.1.0.x86_64_linux.bottle.tar.gz
==> Pouring gmp-6.1.0.x86_64_linux.bottle.tar.gz
/home/cancer/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
Error: Failure while executing: /home/cancer/.linuxbrew/Cellar/patchelf/0.9/bin/patchelf --set-rpath /home/cancer/.linuxbrew/lib 
Warning: Bottle installation failed: building from source.
==> Downloading https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
Already downloaded: /home/cancer/.cache/Homebrew/gmp-6.1.0.tar.xz
==> ./configure --prefix=/home/cancer/.linuxbrew/Cellar/gmp/6.1.0 --enable-cxx
Last 15 lines from /home/cancer/.cache/Homebrew/Logs/gmp/01.configure:
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking compiler /usr/bin/gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include... no, program does not run
checking ABI=x32
checking compiler /usr/bin/gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include... no, program does not run
checking ABI=32
checking compiler /usr/bin/gcc -Os -w -pipe -march=native -isystem/home/cancer/.linuxbrew/include... no, program does not run
configure: error: could not find a working compiler, see config.log for details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues

These open issues may also help:
Update missing gmp 6.1.0 file https://github.com/Homebrew/homebrew-core/issues/1053

============
I tried many times~I installed libstdc++ in this RHEL6.

**Comment by chdiza** [comment]
> If reporting this issue please do so at (not Homebrew/brew):
> https://github.com/Linuxbrew/homebrew-core/issues

**Comment by kaji331** [comment]
thx @chdiza

**Comment by ilovezfs** [comment]
Closed in favor of https://github.com/Linuxbrew/homebrew-core/issues/306
