### ISSUE TITLE
Formulae without a `test do` test block

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#11898]
Please help add `test do` test blocks to the formulae missing them. If you see something on the list that now _does_ have a test block, just comment below, and one of the maintainers will check the box.

- [x] aces_container
- [x] ahcpd
- [x] aldo
- [x] alure
- [ ] anttweakbar
- [ ] aoeui
- [x] apachetop
- [x] apollo
- [ ] app-engine-python
- [x] arabica
- [x] argtable
- [x] argus-clients
- [x] argus
- [x] arm
- [x] arp-sk
- [x] arpoison
- [x] arss
- [ ] at-spi2-atk
- [x] at-spi2-core
- [x] atf
- [x] atomicparsley
- [x] autoenv
- [ ] autopsy
- [x] aview
- [x] avro-c
- [x] avro-cpp
- [x] avro-tools
- [x] backupninja
- [x] balance
- [ ] ballerburg
- [x] bash-git-prompt
- [ ] bastet
- [x] batik
- [x] bbe
- [x] bdw-gc
- [x] beanstalkd
- [x] blahtexml
- [x] blitz
- [ ] blitzwave
- [x] bogofilter
- [x] bokken
- [x] bonnie++
- [x] boost-build
- [ ] bpm-tools
- [x] brew-pip
- [x] briss
- [ ] bsdsfv
- [ ] bsponmpi
- [x] cadaver
- [ ] camellia
- [ ] cataclysm
- [x] cclive
- [ ] cctools-headers
- [x] cdargs
- [x] cdparanoia
- [x] cdpr
- [ ] cdrdao
- [x] cgdb
- [x] cherokee
- [x] chgems
- [ ] chmlib
- [x] chocolate-doom
- [ ] chromaprint
- [x] chruby
- [x] cityhash
- [ ] classads
- [ ] clens
- [ ] clucene
- [ ] cmigemo
- [ ] cmockery
- [ ] cmu-pocketsphinx
- [ ] cmu-sphinxbase
- [ ] cmuclmtk
- [ ] cntlm
- [x] coccinelle
- [ ] cocot
- [ ] collada-dom
- [x] contacts
- [ ] convertlit
- [x] corsixth
- [ ] cpansearch
- [ ] crash
- [ ] crm114
- [ ] cronolog
- [x] crunch
- [ ] cssembed
- [ ] ctemplate
- [ ] curlftpfs
- [ ] cvsps
- [ ] davmail
- [x] dbacl
- [x] dcfldd
- [x] dcled
- [ ] ddar
- [x] devtodo
- [ ] dhcping
- [ ] dict
- [ ] dirac
- [ ] djview4
- [x] dnstop
- [ ] docbook
- [x] docbook2x
- [x] doublecpp
- [x] doubledown
- [ ] drip
- [ ] dsh
- [ ] dsocks
- [ ] dvd+rw-tools
- [x] dvdauthor
- [x] dvdbackup
- [ ] dvdrtools
- [ ] dvorak7min
- [ ] dxflib
- [ ] dyld-headers
- [ ] ecasound
- [ ] echoprint-codegen
- [x] ecj
- [ ] ecm
- [ ] einstein
- [ ] ekhtml
- [ ] emacs-clang-complete-async
- [ ] enet
- [ ] engine_pkcs11
- [x] epsilon
- [ ] epubcheck
- [ ] esniper
- [ ] eventlog
- [ ] ex-vi
- [ ] exempi
- [x] exodriver
- [ ] ext2fuse
- [ ] ext4fuse
- [x] faad2
- [x] fail2ban
- [x] fatsort
- [x] fcgi
- [ ] fcgiwrap
- [ ] fdclone
- [x] flake
- [x] foremost
- [ ] fragroute
- [ ] freealut
- [x] freediameter
- [ ] freeglut
- [x] freexl
- [ ] frei0r
- [ ] frotz
- [ ] ftgl
- [x] fuego
- [ ] g2
- [ ] gaul
- [x] gcab
- [ ] gconf
- [ ] gearboy
- [ ] gearsystem
- [ ] genders
- [x] gflags
- [x] gforth
- [ ] gibbslda
- [x] gibo
- [x] git-number
- [x] git-open
- [x] gitslave
- [ ] glassfish
- [x] glog
- [ ] glui
- [x] gmime
- [ ] gmtl
- [ ] gnome-common
- [x] gnome-doc-utils
- [ ] gnuski
- [ ] goocanvas
- [ ] google-sparsehash
- [ ] gplcver
- [x] gpp
- [x] gpsd
- [x] gpsim
- [ ] gptsync
- [x] grepcidr
- [x] griffon
- [x] gtmess
- [ ] gts
- [ ] gupnp-av
- [ ] gzrt
- [x] h2
- [ ] h264bitstream
- [ ] homeworlds
- [ ] hornetq
- [ ] hping
- [x] htmldoc
- [x] httperf
- [x] iat
- [ ] ical-buddy
- [ ] icbirc
- [ ] icecast
- [ ] icon-naming-utils
- [ ] id3lib
- [x] id3v2
- [ ] ievms
- [x] ifstat
- [x] iftop
- [ ] ii
- [x] imake
- [ ] imap-uw
- [ ] iniparser
- [x] iperf
- [x] iphotoexport
- [ ] isc-dhcp
- [ ] itpp
- [ ] ivy
- [x] jags
- [ ] jailkit
- [ ] jbig2enc
- [x] jboss-as
- [x] jboss-as@5
- [ ] jerm
- [x] jetty-runner
- [x] jetty@8
- [x] jhiccup
- [ ] jnethack
- [ ] john
- [ ] jpcsp
- [x] json-c
- [ ] json_spirit
- [ ] jsvc
- [ ] jvmtop
- [x] jython
- [x] keychain
- [ ] kimwitu++
- [x] kite
- [ ] kyoto-cabinet
- [ ] kyoto-tycoon
- [x] kytea
- [ ] kyua
- [ ] lasi
- [ ] lastfmfpclient
- [ ] latex2rtf
- [x] launch4j
- [x] lcdf-typetools
- [ ] lci
- [x] lcov
- [ ] lcs
- [ ] ld64
- [ ] lesstif
- [x] libaacs
- [ ] libagg
- [ ] libart
- [ ] libatomic_ops
- [ ] libbind
- [ ] libbinio
- [x] libbluray
- [ ] libbs2b
- [x] libcddb
- [ ] libcmph
- [ ] libcoap
- [x] libcsv
- [ ] libcuefile
- [ ] libdaemon
- [ ] libdc1394
- [ ] libdca
- [ ] libdiscid
- [ ] libdmtx
- [x] libdnet
- [ ] libdshconfig
- [ ] libdv
- [ ] libdvbpsi
- [ ] libdvdcss
- [ ] libdvdnav
- [ ] libdvdread
- [ ] libebml
- [x] libelf
- [x] libev
- [ ] libexosip
- [x] libfaketime
- [ ] libfishsound
- [ ] libfixbuf
- [ ] libflowmanager
- [ ] libfreefare
- [x] libftdi0
- [ ] libgadu
- [ ] libgaiagraphics
- [ ] libgda
- [x] libgeotiff
- [ ] libgsm
- [x] libhid
- [x] libical
- [ ] libid3tag
- [ ] libident
- [ ] libidl
- [ ] libiptcdata
- [ ] libkml
- [ ] liblacewing
- [ ] liblo
- [ ] liblqr
- [ ] liblunar
- [x] liblwgeom
- [ ] libmaa
- [x] libmagic
- [ ] libmatroska
- [x] libmemcached
- [ ] libmetalink
- [ ] libmms
- [ ] libmonome
- [ ] libmp3splt
- [ ] libmpd
- [ ] libmpdclient
- [ ] libmpeg2
- [ ] libmrss
- [ ] libmusicbrainz
- [ ] libnatpmp
- [ ] libnet
- [ ] libnids
- [ ] libnotify
- [ ] libntlm
- [ ] libnxml
- [ ] liboauth
- [x] libogg
- [ ] libopennet
- [x] liboping
- [ ] libopkele
- [ ] libosip
- [ ] libotr
- [ ] libowfat
- [ ] libp11
- [ ] libpano
- [ ] libpcl
- [ ] libpgm
- [x] libplist
- [ ] libpoker-eval
- [x] libpqxx
- [ ] libpqxx@3
- [x] libquicktime
- [ ] libquvi
- [ ] librasterlite
- [ ] libreplaygain
- [ ] libresample
- [x] librtlsdr
- [ ] libsamplerate
- [x] libscrypt
- [ ] libshout
- [ ] libsmf
- [x] libsndfile
- [ ] libsoxr
- [ ] libstxxl
- [ ] libsvg-cairo
- [ ] libsvg
- [ ] libtcod
- [ ] libtermkey
- [ ] libtrace
- [x] libunistring
- [ ] libunwind-headers
- [ ] libupnp
- [ ] libutf
- [ ] libuvc
- [ ] libvidstab
- [x] libvorbis
- [ ] libwbxml
- [ ] libwmf
- [ ] libxdiff
- [ ] libxmi
- [x] libxmlsec1
- [ ] libxspf
- [ ] libyubikey
- [ ] libzdb
- [ ] lifelines
- [ ] lilv
- [ ] lldpd
- [x] lnav
- [x] lockrun
- [ ] log4cplus
- [ ] log4cpp
- [ ] logtalk
- [ ] lpc21isp
- [x] lsdvd
- [ ] ltl2ba
- [ ] luciddb
- [ ] lutok
- [ ] lv
- [ ] lv2
- [ ] lxsplit
- [x] lzlib
- [x] lzo
- [ ] mac-robber
- [ ] mad
- [x] madplay
- [ ] mailcheck
- [x] mairix
- [x] makeicns
- [x] makepp
- [ ] malbolge
- [ ] matlab2tikz
- [ ] maven-shell
- [ ] mcpp
- [ ] mda-lv2
- [ ] mdbtools
- [ ] memcache-top
- [ ] memcacheq
- [ ] mesalib-glw
- [ ] midgard2
- [ ] minetest
- [ ] minidjvu
- [x] miniupnpc
- [ ] minizip
- [ ] minuit2
- [ ] mjpegtools
- [x] mkclean
- [x] mktorrent
- [x] mkvdts2ac3
- [ ] mm-common
- [x] mogenerator
- [ ] monetdb
- [ ] morse
- [x] movgrab
- [ ] mozilla-addon-sdk
- [x] mp3gain
- [ ] mpack
- [x] mpc
- [x] mpdas
- [x] mpdscribble
- [ ] mpdviz
- [x] mpg321
- [ ] mpgtx
- [ ] mscgen
- [ ] msdl
- [x] msmtp
- [x] mussh
- [ ] nacl
- [ ] narwhal
- [x] naturaldocs
- [x] ncmpc
- [ ] neon
- [ ] nesc
- [ ] nethack
- [ ] nethacked
- [ ] nfcutils
- [x] ngrep
- [x] nikto
- [x] nkf
- [x] nload
- [ ] noweb
- [ ] npush
- [x] nspr
- [ ] nuvie
- [x] nvi
- [ ] nxengine
- [x] ocp
- [x] ode
- [ ] ogmtools
- [ ] omega-rpg
- [ ] ondir
- [ ] open-ocd
- [x] open-sp
- [x] opencolorio
- [ ] opencore-amr
- [ ] opendetex
- [ ] openjazz
- [ ] opensaml
- [ ] opensc
- [ ] openslp
- [x] opus-tools
- [x] opus
- [ ] oscats
- [ ] osm-pbf
- [x] ossp-uuid
- [ ] pacman4console
- [ ] pacvim
- [ ] pakchois
- [ ] partio
- [ ] pax-runner
- [x] pbrt
- [x] pbzip2
- [ ] pc6001vx
- [ ] pcre++
- [x] pdfcrack
- [ ] pdflib-lite
- [ ] pdftohtml
- [x] peg
- [ ] perceptualdiff
- [x] percona-server
- [x] percona-server@5.5
- [x] perl-build
- [ ] pgdbf
- [x] pgplot
- [x] phoon
- [x] phoronix-test-suite
- [ ] pianobar
- [x] pidof
- [x] pinentry-mac
- [ ] pkcs11-helper
- [x] pktanon
- [x] plenv
- [ ] plowshare
- [ ] plustache
- [ ] png++
- [ ] pngnq
- [ ] polyml
- [ ] popt
- [ ] portmidi
- [ ] pow
- [ ] ppsspp
- [ ] predictionio
- [x] privoxy
- [ ] proctools
- [x] protobuf-c
- [x] proxytunnel
- [ ] ptex
- [ ] puf
- [ ] putmail-queue
- [ ] putmail
- [ ] qcachegrind
- [x] qstat
- [ ] raptor
- [ ] rarian
- [ ] rasqal
- [x] rdiff-backup
- [ ] reaver
- [x] recoverjpeg
- [ ] redland
- [x] redo
- [x] redsocks
- [ ] redstore
- [ ] ripmime
- [ ] rlog
- [ ] rlvm
- [x] rlwrap
- [ ] rmcast
- [ ] rnv
- [ ] rofs-filtered
- [ ] rp
- [ ] rpm2cpio
- [x] rsnapshot
- [ ] rsyslog
- [x] runcocoa
- [ ] runit
- [x] s3cmd
- [ ] saxon-b
- [ ] scale2x
- [ ] scamper
- [ ] schroedinger
- [ ] scrollkeeper
- [x] sdl2_gfx
- [x] sdl2_image
- [x] sdl2_mixer
- [x] sdl2_net
- [x] sdl2_ttf
- [ ] sdl_gfx
- [ ] sdl_image
- [ ] sdl_mixer
- [ ] sdl_net
- [ ] sdl_rtf
- [ ] sdl_sound
- [ ] sdl_ttf
- [ ] sdlpop
- [ ] serd
- [ ] shakespeare
- [x] shapelib
- [ ] shivavg
- [x] shocco
- [ ] sic
- [x] simgrid
- [ ] sisc-scheme
- [x] sispmctl
- [ ] skipfish
- [ ] skktools
- [x] sl
- [ ] slashem
- [ ] sleepwatcher
- [x] sloccount
- [x] smartmontools
- [ ] snobol4
- [ ] snownews
- [x] sntop
- [ ] soci
- [ ] solid
- [ ] somagic-tools
- [ ] somagic
- [ ] sord
- [x] sox
- [ ] spatialite-gui
- [x] speex
- [ ] speexdsp
- [x] spiped
- [ ] spring-roo
- [x] sqlcipher
- [ ] sratom
- [ ] srecord
- [ ] ssss
- [x] star
- [ ] startup-notification
- [x] stk
- [x] stone
- [x] streamripper
- [ ] svdlibc
- [ ] swfmill
- [ ] syck
- [ ] t1lib
- [x] taisei
- [x] task-spooler
- [ ] tclap
- [ ] tcpflow
- [x] tcpsplit
- [x] tcptraceroute
- [ ] teapot
- [ ] term
- [x] theora
- [x] thrift
- [ ] thrulay
- [x] tidyp
- [ ] tiger-vnc
- [x] timedog
- [x] tintin
- [ ] tiny-fugue
- [ ] tivodecode
- [ ] tn5250
- [x] tnef
- [ ] tofrodos
- [ ] tokyo-cabinet
- [ ] tomcat-native
- [ ] topgit
- [ ] torrentcheck
- [ ] tpl
- [x] tracebox
- [x] tractorgen
- [x] trafshow
- [ ] tta
- [ ] ttf2pt1
- [ ] two-lame
- [ ] typespeed
- [ ] uade
- [ ] udns
- [ ] udpxy
- [x] unittest
- [ ] unnethack
- [ ] unoconv
- [ ] urlview
- [x] utimer
- [ ] vde
- [x] vgmstream
- [ ] vip
- [ ] virtualhost.sh
- [ ] visionmedia-watch
- [ ] vit
- [ ] vncsnapshot
- [x] vorbisgain
- [ ] vrpn
- [x] wakeonlan
- [x] webkit2png
- [x] whohas
- [x] wiggle
- [x] winexe
- [x] wordplay
- [ ] writerperfect
- [ ] wrk-trello
- [x] wry
- [ ] wslay
- [ ] wv
- [ ] wv2
- [x] wwwoffle
- [x] wy60
- [ ] xbee-comm
- [x] xcproj
- [ ] xlslib
- [ ] xml-tooling-c
- [x] xmlcatmgr
- [ ] xmlformat
- [x] xmlstarlet
- [x] xmlto
- [ ] xmltoman
- [ ] xmp
- [ ] xpa
- [x] xpdf
- [ ] xshogi
- [ ] xspin
- [ ] yamdi
- [ ] yazpp
- [ ] yconalyzer
- [ ] yydecode
- [x] z
- [x] zsh-history-substring-search
- [ ] zssh

**Comment by rwhogg** [comment]
`xmlto` has a test; it was added in https://github.com/Homebrew/homebrew-core/pull/12261

**Comment by ilovezfs** [comment]
@rwhogg thanks! updated.

**Comment by subkrish** [comment]
`imake` has a test. It was added in https://github.com/Homebrew/homebrew-core/commit/7e84e2ef03649957e13afa0d520f715461e7c2f8

**Comment by ilovezfs** [comment]
Thanks @subkrish! Updated.

**Comment by subkrish** [comment]
- bdw-gc has a test. It was added in https://github.com/Homebrew/homebrew-core/commit/5c488dc5fb00147da75fa1d0e4b13167f2fb2dba

- brew-pip has a test. It was added in https://github.com/Homebrew/homebrew-core/pull/12204

- corsixth has a test. It was added in https://github.com/Homebrew/homebrew-core/commit/439f9dc9b074cd9c3c2915c2d687ec58381924c8

- gnome-doc-utils has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnome-doc-utils.rb#L36

- h2 has a test. It was added in https://github.com/Homebrew/homebrew-core/commit/5dd9a34ecf8068853f5ccd8272a61551e67b8483

- jetty-runner has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/jetty-runner.rb#L19

- libaacs has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/libaacs.rb#L32

- libgeotiff has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/libgeotiff.rb#L35

- libplist has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/libplist.rb#L44

- libquicktime has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/libquicktime.rb#L50

- lsdvd has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/lsdvd.rb#L25

- miniupnpc has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/miniupnpc.rb#L18

- ode has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/ode.rb#L46

- percona-server has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/percona-server.rb#L166

- percona-server@5.5 has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/percona-server@5.5.rb#L161

- perl-build has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/perl-build.rb#L193

- phoronix-test-suite has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/phoronix-test-suite.rb#L19

- spiped has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/spiped.rb#L22

- zsh-history-substring-search has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/zsh-history-substring-search.rb#L25

**Comment by ilovezfs** [comment]
@subkrish thanks! Updated.

**Comment by subkrish** [comment]
- `autotrace` needs to be removed from the list. It does not exist in `Formula`.

- `curlftpfs` needs to be added to the list.

- `ext2fuse` needs to be added to the list.

- `ext4fuse` needs to be added to the list.

- `libpqxx@3` needs to be added to the list.

- ` rofs-filtered` needs to be added to the list.

**Comment by ilovezfs** [comment]
@subkrish thanks! done.

**Comment by hjmallon** [comment]
rpm2cpio would need an rpm file adding to the test files. Is that a sensible thing to do (I don't think there is a sensible way to make an rpm on macOS) or should I add a get-version type test?

**Comment by fxcoudert** [comment]
Here are the formulas missing tests, that are among the 1000 most-installed Homebrew formulas:

- chromaprint
- chruby
- docbook
- ext4fuse
- freexl
- frei0r
- gflags
- imap-uw
- libdnet
- libdvdcss
- libebml
- libftdi0
- libmatroska
- libmpdclient
- libnet
- libsamplerate
- libsoxr
- libtermkey
- libvidstab
- libxmlsec1
- lnav
- mad
- mogenerator
- nkf
- nspr
- opencore-amr
- ossp-uuid
- popt
- portmidi
- rlwrap
- sdl_image
- sdl_mixer
- sdl_ttf
- sl
- smartmontools
- speex
- thrift
- tokyo-cabinet
- wakeonlan
- xmlstarlet

We may want to deal with those first

**Comment by barthel** [comment]
* ```arm.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/arm.rb#L25
* ```arss.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/arss.rb#L26
* ```atomicparsley.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/atomicparsley.rb#L39
* ```aview.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/aview.rb#L28
* ```batik.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/batik.rb#L16
* ```bbe.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/bbe.rb#L24
* ```beanstalkd.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/beanstalkd.rb#L50
* ```bogofilter.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/bogofilter.rb#L23
* ```cdargs.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/cdargs.rb#L37
* ```cdparanoia.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/cdparanoia.rb#L35
* ```cdpr.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/cdpr.rb#L26
* ```cgdb.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/cgdb.rb#L32
* ```chgems.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/chgems.rb#L21
* ```crunch.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/crunch.rb#L25
* ```dcfldd.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/dcfldd.rb#L23
* ```dcled.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/dcled.rb#L27
* ```dnstop.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/dnstop.rb#L24
* ```doublecpp.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/doublecpp.rb#L22
* ```doubledown.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/doubledown.rb#L15
* ```dvdbackup.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/dvdbackup.rb#L24
* ```epsilon.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/epsilon.rb#L24
* ```faad2.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/faad2.rb#L21
* ```fatsort.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/fatsort.rb#L24
* ```flake.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/flake.rb#L23
* ```foremost.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/foremost.rb#L28
* ```freediameter.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/freediameter.rb#L85
* ```fuego.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/fuego.rb#L33
* ```gcab.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcab.rb#L31
* ```gforth.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gforth.rb#L30
* ```git-number.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-number.rb#L19
* ```git-open.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-open.rb#L13
* ```gmime.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmime.rb#L34
* ```gpp.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gpp.rb#L23
* ```gpsim.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gpsim.rb#L31
* ```griffon.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/griffon.rb#L21
* ```gtmess.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtmess.rb#L35
* ```htmldoc.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/htmldoc.rb#L26
* ```httperf.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/httperf.rb#L45
* ```iat.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/iat.rb#L22
* ```id3v2.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/id3v2.rb#L27
* ```iphotoexport.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/iphotoexport.rb#L20
* ```jhiccup.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/jhiccup.rb#L28
* ```keychain.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/keychain.rb#L15
* ```kytea.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/kytea.rb#L30
* ```launch4j.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/launch4j.rb#L15
* ```lcov.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/lcov.rb#L22
* ```liblwgeom.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/liblwgeom.rb#L64
* ```liboping.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/liboping.rb#L25
* ```lockrun.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/lockrun.rb#L23
* ```lzlib.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/lzlib.rb#L23
* ```madplay.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/madplay.rb#L37
* ```mairix.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/mairix.rb#L23
* ```makepp.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/makepp.rb#L21
* ```mkvdts2ac3.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/mkvdts2ac3.rb#L32
* ```mogenerator.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/mogenerator.rb#L25
* ```movgrab.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/movgrab.rb#L28
* ```mussh.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/mussh.rb#L14
* ```naturaldocs.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/naturaldocs.rb#L18
* ```nkf.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/nkf.rb#L25
* ```nload.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/nload.rb#L37
* ```ocp.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/ocp.rb#L39
* ```pbrt.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/pbrt.rb#L24
* ```pbzip2.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/pbzip2.rb#L23
* ```pdfcrack.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdfcrack.rb#L19
* ```pktanon.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/pktanon.rb#L30
* ```plenv.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/plenv.rb#L27
* ```proxytunnel.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/proxytunnel.rb#L28
* ```qstat.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/qstat.rb#L22
* ```rdiff-backup.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/rdiff-backup.rb#L46
* ```redo.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/redo.rb#L27
* ```redsocks.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/redsocks.rb#L23
* ```rlwrap.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/rlwrap.rb#L28
* ```rsnapshot.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/rsnapshot.rb#L23
* ```sdl2_ttf.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl2_ttf.rb#L28
* ```shocco.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/shocco.rb#L46
* ```sloccount.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/sloccount.rb#L27
* ```sntop.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/sntop.rb#L34
* ```star.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/star.rb#L36
* ```stk.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/stk.rb#L60
* ```stone.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/stone.rb#L30
* ```streamripper.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/streamripper.rb#L32
* ```tcpsplit.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/tcpsplit.rb#L21
* ```thrift.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/thrift.rb#L85
* ```tidyp.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/tidyp.rb#L35
* ```tnef.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/tnef.rb#L24
* ```vorbisgain.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/vorbisgain.rb#L24
* ```wakeonlan.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wakeonlan.rb#L23
* ```webkit2png.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/webkit2png.rb#L13
* ```wiggle.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wiggle.rb#L20
* ```winexe.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/winexe.rb#L51
* ```wry.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wry.rb#L27
* ```wwwoffle.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wwwoffle.rb#L19
* ```wy60.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/wy60.rb#L20
* ```xcproj.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/xcproj.rb#L42
* ```xmlcatmgr.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/xmlcatmgr.rb#L23
* ```xmlformat.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/xmlformat.rb#L13
* ```xmlstarlet.rb``` has a test. https://github.com/Homebrew/homebrew-core/blob/master/Formula/xmlstarlet.rb#L25

**Comment by barthel** [comment]
* ```jboss-as``` and ```jboss-as@5``` removed with #19698

**Comment by barthel** [comment]
@fxcoudert You kidding me... ```sl``` is one of the 1000 most-installed Homebrew formulas?

**Comment by barthel** [comment]
Could one of the maintainers please update the original list of @ilovezfs ?

**Comment by ilovezfs** [comment]
@barthel the list has been updated.

**Comment by vinyldarkscratch** [comment]
Some of my findings when attempting to write tests for some of the formulas in @fxcoudert's [top-1K list](https://github.com/Homebrew/homebrew-core/issues/11898#issuecomment-375880917), for anyone else planning to work on these:

`chromaprint` has testing modules, however they depend on the Google Test framework to do so.

I couldn't get `portmidi` to compile, so I gave up.  It looks like there are modifications that the Formula is doing to ensure compatibility with newer operating systems.

**Comment by MikeMcQuaid** [comment]
`brew audit` will complain about this so closing as @ilovezfs isn't around to maintain the list any more.
