### ISSUE TITLE
Unable to perform install --HEAD

### ISSUE THREAD

**Issue by bohdaq** [Homebrew/homebrew-core#119273]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/1491b302681a97a3f3c4d73d08eb0197
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Build executable from the latest sources

### What happened (include all command output)?

➜  homebrew-rust-tls-server git:(main) ✗ brew install bohdaq/rust-tls-server/rts --HEAD
==> Fetching bohdaq/rust-tls-server/rts
==> Cloning https://github.com/bohdaq/rust-tls-server.git
Cloning into '/Users/bogdantsap/Library/Caches/Homebrew/rts--git'...
fatal: Remote branch master not found in upstream origin
Error: rts: Failed to download resource "rts"
Failure while executing; `git clone --branch master -c advice.detachedHead=false https://github.com/bohdaq/rust-tls-server.git /Users/bogdantsap/Library/Caches/Homebrew/rts--git` exited with 128. Here's the output:
Cloning into '/Users/bogdantsap/Library/Caches/Homebrew/rts--git'...
fatal: Remote branch master not found in upstream origin

### What did you expect to happen?

Successful build.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
> brew uninstall rts
> 
> brew untap bohdaq/rust-tls-server
> 
> brew update
> 
> brew tap bohdaq/rust-tls-server
> 
> brew install bohdaq/rust-tls-server/rts --HEAD
>
> rts
```

**Comment by bohdaq** [comment]
<img width="1990" alt="Screenshot 2022-12-28 at 20 32 45" src="https://user-images.githubusercontent.com/1307140/209857218-31997508-6859-4cdb-9c7c-a34561a7b5ac.png">
brew doctor shows no warnings

**Comment by cho-m** [comment]
You need to add the corresponding branch as default is `master`.

Also, this issue page is for `homebrew-core` formulae. Please use discussions page if you want support.

**Comment by bohdaq** [comment]
@cho-m 
after setting default branch to master issue is still reproducible.

created [discussion](https://github.com/Homebrew/discussions/discussions/4071).
