### ISSUE TITLE
freerdp: SmartScaling requested but compiled without libcairo support

### ISSUE THREAD

**Issue by steclb** [Homebrew/homebrew-core#119213]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.16-8-g895d322
ORIGIN: https://github.com/Homebrew/brew
HEAD: 895d3221215dff340baa3fc58b114ce5c52c52d1
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 025fe79713b67cf1ab858c3d8e94bd9457809b19
Core tap last commit: 34 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.u2YV5whQsP/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

$ brew doctor
Your system is ready to brew.

$ brew info freerdp 
==> freerdp: stable 2.9.0 (bottled), HEAD
X11 implementation of the Remote Desktop Protocol (RDP)
https://www.freerdp.com/
/usr/local/Cellar/freerdp/2.9.0 (255 files, 5.2MB) *
  Poured from bottle on 2022-12-26 at 12:18:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/freerdp.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: jpeg-turbo ✔, libusb ✔, libx11 ✔, libxcursor ✔, libxext ✔, libxfixes ✔, libxi ✔, libxinerama ✔, libxrandr ✔, libxrender ✔, libxv ✔, openssl@3 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 2,723 (30 days), 7,925 (90 days), 26,053 (365 days)
install-on-request: 2,721 (30 days), 7,928 (90 days), 26,059 (365 days)
build-error: 51 (30 days)
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run freerdp with the option /smart-sizing in order to be able to adjust the xfreerdp window size, i.e. something such as:
$ xfreerdp /u:\<user\> /p:\<password\> /v:\<server\> /cert-ignore /smart-sizing

### What happened (include all command output)?

xfreerdp closes the connection with:

[WARN][com.freerdp.color] - SmartScaling requested but compiled without libcairo support!
[ERROR][com.freerdp.core] - freerdp_abort_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_CANCELLED

If xfreerdp is started without the /smart-sizing option then it works as expected but the xfreerdp window size cannot be adjusted

### What did you expect to happen?

When started with the /smart-sizing option xfreerdp should allow the client window to be resized (either smaller or larger) and maximized, all without changing the remote server resolution

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1- check the remote server connects without the /smart-sizing option:
$ xfreerdp /u:<user> /p:<password> /v:<server> /cert-ignore

2- repeat with /smart-sizing enabled:
$ xfreerdp /u:<user> /p:<password> /v:<server> /cert-ignore /smart-sizing
```

**Comment by SMillerDev** [comment]
This seems more like a feature request than a bug. Everything is working as configured.

**Comment by steclb** [comment]
Well, it could be seen as a bug in the build configuration too :-)
Anyway, it is a feature already supported upsteam and widely deployed, ubuntu LTS ships with this enabled and the specific feature is working fine as well.
I am not aware if there is some background that pushes against having the binary built with this option.
All I can say is that spawning a fixed size client window that cannot be scaled down client size breaks basic functionalities  (e.g. the capabilty to effectively connect from a macbook screen to a full HD server) and UI assumptions (common desktop windows can be resized).
If it is just a matter of adding cairo as dependency and enabling it in the build then, in my opinion, it would be worth.

**Comment by SMillerDev** [comment]
> If it is just a matter of adding cairo as dependency and enabling it in the build then, in my opinion, it would be worth.

We welcome pull requests to add features.
