### ISSUE TITLE
installing `gawk` creates an undesirable symlink overriding `awk`

### ISSUE THREAD

**Issue by buckyster** [Homebrew/homebrew-core#119311]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.6.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 740f9ddcc620d4812770a0f12854ddd79c643874
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bcde3f1b57c7186126271b2782ad44894ab16c8f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-x86_64
CLT: 14.1.0.0.1.1666437224
Xcode: N/A
```
```
$ brew doctor
Your system is ready to brew.
```

---

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

---

### What were you trying to do (and why)?

I installed `gawk` since it has some features that `awk` doesn't.

`brew install gawk`

---

### What happened (include all command output)?

`gawk` was installed, but it also silently created a symlink `/usr/local/bin/awk` that pointed `awk` to `gawk`. 

This is undesirable because it breaks programs that expect the original version of `awk` that shipped with macOS.

This behavior is also inconsistent with the brew installation of other GNU utilities such as ggrep (grep.rb), gsed (gnu-sed.rb), coreutils.rb. Those all leave the original grep, sed, etc alone.

**Before install:**
```
$ which awk
/usr/bin/awk
```

**After install:**
```
$ which awk
/usr/local/bin/awk

$ which gawk
/usr/local/bin/gawk

$ ls -l /usr/local/bin/awk
/usr/local/bin/awk -> ../Cellar/gawk/5.2.1/bin/awk*

$ ls -l /usr/local/bin/gawk
/usr/local/bin/gawk -> ../Cellar/gawk/5.2.1/bin/gawk*
```

**Installation output:**

```
$ brew install gawk
==> Fetching dependencies for gawk: mpfr
==> Fetching mpfr
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/manifests/4.1.0-p13
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/mpfr/blobs/sha256:1007b284b2bc9
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Fetching gawk
==> Downloading https://ghcr.io/v2/homebrew/core/gawk/manifests/5.2.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/gawk/blobs/sha256:4c4b1b9becee9
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
######################################################################## 100.0%
==> Installing dependencies for gawk: mpfr
==> Installing gawk dependency: mpfr
==> Pouring mpfr--4.1.0-p13.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/4.1.0-p13: 30 files, 5.2MB
==> Installing gawk
==> Pouring gawk--5.2.1.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/gawk/5.2.1: 98 files, 5.8MB
==> Running `brew cleanup gawk`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

---

### What did you expect to happen?

The symlink `/usr/local/bin/awk` should not have been created. That points `awk` to `gawk`, which breaks programs that expect the original version of `awk` that shipped with macOS.

**Expected to happen after install:**

```
$ which awk
/usr/bin/awk

$ which gawk
/usr/local/bin/gawk
```

This would be consistent with the behavior of the other GNU utilities installed by brew, such as ggrep (grep.rb), gsed (gnu-sed.rb), coreutils.rb. Those all leave the original grep, sed, etc alone.

---

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
which awk

brew install gawk

which awk
which gawk
ls -l /usr/local/bin/awk
ls -l /usr/local/bin/gawk
```

**Comment by ryenus** [comment]
Can you share what's broken with awk linked to gawk? Asking since you're reporting this as a bug.

**Comment by MikeMcQuaid** [comment]
> This would be consistent with the behavior of the other GNU utilities installed by brew, such as ggrep (grep.rb), gsed (gnu-sed.rb), coreutils.rb. Those all leave the original grep, sed, etc alone.

I agree, it would make sense to change this.
