### ISSUE TITLE
LilyPond formula must package font files

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [Homebrew/homebrew-core#119476]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs lilypond
Error: No logs.

$ brew config
HOMEBREW_VERSION: 3.6.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 740f9ddcc620d4812770a0f12854ddd79c643874
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1284c51e2dd7e75c9af9adea194c06ddbfe12099
Core tap last commit: 42 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 15.0.6
Git: 2.38.1 => /bin/git
Curl: 7.85.0 => /bin/curl
Kernel: Linux 6.0.15-300.fc37.x86_64 x86_64 GNU/Linux
OS: Fedora release 37 (Thirty Seven) (ThirtySeven)
Host glibc: 2.36
/usr/bin/gcc: 12.2.1
/usr/bin/ruby: 3.1.3
glibc: N/A
gcc@11: N/A
gcc: 12.2.0
xorg: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Compiling any LilyPond file with text (like: `\markup "abcd"`).

### What happened (include all command output)?

The fonts in the output PDF file come from the system. For example, after uninstalling URW-35 fonts from my Fedora system, the font is

```
$ pdffonts test.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
LRNWAE+TeXGyreSchola-Regular         Type 1C           Custom           yes yes no       8  0
```

### What did you expect to happen?

LilyPond's default fonts are documented [here](https://lilypond.org/doc/v2.24/Documentation/notation/fonts#font-families) and the default is C059. While LilyPond does search the system for fonts, system fonts should only be looked up if requested by the user (e.g., by overriding the `font-name` property). It is essential to get the fonts expected by the developers for an experience matching LilyPond's defaults and its behavior on other systems.

I believe that this problem is related to the upgrade to LilyPond 2.24.0 in https://github.com/Homebrew/homebrew-core/pull/118260. As documented in our Changelog, our build system does not search and install text fonts anymore, for various reasons, including build complexity and licensing reasons. Please see this commit in the LilyPond repository: https://gitlab.com/lilypond/lilypond/-/commit/5689c2721530c6ded22b6291ebb06d10adb5bc28

As a result, the LilyPond package in Homebrew is utterly broken right now. It only works if the user also happens to have the fonts installed by chance (like with TeX-related packages), but not in the vanilla setup where the user just installs Homebrew plus LilyPond from Homebrew. While having a TeX install around is probably the case for a significant proportion of LilyPond users, I definitely don't think it is the case of a majority.

See https://lists.gnu.org/archive/html/lilypond-user/2022-12/msg00349.html for the kind of problems this causes.

Given that this significantly regresses the functionality of the LilyPond package and makes for problems that are very difficult to understand for users of the Joe User, I would like to request that the upgrade to LilyPond 2.24.0 be reverted for the time being if this takes time to figure out.

Precise information on which fonts are required can be found on https://lilypond.org/doc/v2.24/Documentation/contributor/requirements-for-running-lilypond.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install lilypond
echo '\markup "abc"` > test.ly
lilypond test.ly
```

Running `pdffonts` or equivalent on the resulting `test.pdf` tells which fonts have been used. Without customizations, such as in this example, this must be C059-Roman.

The following snippet allows to check where LilyPond is taking its fonts (to be put in `test.ly`, outputs info on stderr when compiled):

```
\version "2.24.0"

#(define-markup-command (debug layout props arg) (markup?)
   (let ((stil (interpret-markup layout props arg)))
     (pretty-print (ly:stencil-expr stil)
                   (current-error-port))
     (flush-all-ports)
     stil))

\markup \debug "abc"
```
```

**Comment by SMillerDev** [comment]
Sounds like an upstream bug caused by stopping the install of fonts. We should wait for a patch for that.

**Comment by lemzwerg** [comment]
No, no, this is not an upstream bug.  We from LilyPond intentionally decided to no longer distribute the fonts – they are available elsewhere, as documented [in our build instructions](https://lilypond.org/doc/v2.25/Documentation/contributor-big-page.html).

**Comment by chenrui333** [comment]
sounds like we can add a patch to search the system font and add a caveat for it?

**Comment by alebcay** [comment]
Another option is to add the font as a `resource` (find wherever it comes from online) and install it in the Cellar where it is expected. Looking at the distributed binaries for macOS from `lilypond.org`, I see this includes the fonts and shows where the fonts are expected to be placed:
```
❯ fd C059
share/lilypond/2.24.0/fonts/otf/C059-BdIta.otf
share/lilypond/2.24.0/fonts/otf/C059-Bold.otf
share/lilypond/2.24.0/fonts/otf/C059-Italic.otf
share/lilypond/2.24.0/fonts/otf/C059-Roman.otf
```

We can just install the needed font in-tree rather than as a system font. This is assuming, of course, that we have the rights to distribute the font.

I don't know what the precedent is on distributing embedded fonts like this via formulae is (maybe some formulae like `texlive` are already doing something similar?).

---

> sounds like we can add a patch to search the system font and add a caveat for it?

This is also an option. There would still be a discrepancy if users choose not to install the C059 font cask afterwards.

---

One final option is to stop building LilyPond from source and just ship the LilyPond binaries (https://gitlab.com/lilypond/lilypond/-/releases/v2.24.0/downloads/lilypond-2.24.0-darwin-x86_64.tar.gz) as provided from upstream as a cask rather than a formula.

**Comment by alebcay** [comment]
There's an ongoing effort in #119481 to implement option 1 that I laid out above. @Jean-Abou-Samra, I'd like to check:
- Do we need to (or should we) include all of the OTF font files from the URW-35 repository? I only see that the C059, Nimbus Mono, and Nimbus Sans families are included in the macOS binaries tarball from the LilyPond site. However, the packaging script at https://gitlab.com/lilypond/lilypond/-/blob/master/release/binaries/lib/fonts.py seems to suggest that all the OTF font files would be copied in and included.
- Do we need to include the TeX Gyre family as well? From https://github.com/Homebrew/homebrew-core/pull/119481#issuecomment-1368285789 it seems like this is a fallback if the URW-35 fonts are absent, so if we are including the URW-35 fonts, then we shouldn't need TeX Gyre. Just wanted to confirm that this understanding is accurate.

**Comment by alebcay** [comment]
This should be fixed by https://github.com/Homebrew/homebrew-core/pull/119481 which has shipped, so closing this. In summary:

- The `lilypond` formula now ships the URW-35 and TeX Gyre fonts installed into the Cellar (not as system fonts)
- The `license` for `lilypond` has been updated to reflect the addition of new licenses incurred by including the above fonts
- The `test` for `lilypond` has been updated to confirm that the preferred fonts are used when creating a PDF

We can re-open this issue or create a new one if any new issues relating to `lilypond` out-of-the-box default behaviors are found.
