### ISSUE TITLE
[FR]wine-staging

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#11965]
Please help me implement wine-staging. Should we use current wine package by adding flag `--with-staging`?

**Comment by fxcoudert** [comment]
Right now, we provide three "versions" of wine: stable (2.0), devel (2.5) and HEAD (top of git master branch). What is wine-staging and what does it provide in addition to those?

**Comment by yurikoles** [comment]
@fxcoudert it's staging area for experimental patches to wine.
https://www.wine-staging.com/

**Comment by fxcoudert** [comment]
What is its release process / versioning system?

**Comment by yurikoles** [comment]
It's bases on wine-devel, so it releases after one or two days after corresponding wine-devel release.

**Comment by ilovezfs** [comment]
It looks like they provide a pkg. Maybe this could go in Cask?

**Comment by yurikoles** [comment]
@ilovezfs it's already in caskroom.

**Comment by fxcoudert** [comment]
Then I suggest we keep the current situation.

**Comment by alexchandel** [comment]
There is a case to reopen this.

Wine's own wine-staging doesn't include an [important graphics patch](https://bugs.winehq.org/attachment.cgi?id=57353) ([bug](https://bugs.winehq.org/show_bug.cgi?id=34166)) that a Wine developer believes is a bug in macOS, and thus is useless for many fullscreen Windows programs.

**Comment by ilovezfs** [comment]
@alexchandel not sure what that has to do with wine staging. That patch is in the formula, and the supposed "bug" has been reported to Apple.

**Comment by alexchandel** [comment]
@ilovezfs That patch isn't in wine-staging. It's only in the homebrew-core formula, which doesn't provide any of the wine-staging patches. Hence this issue.

**Comment by ilovezfs** [comment]
@alexchandel you can use the cask.

**Comment by alexchandel** [comment]
@ilovezfs No, I can't. The cask doesn't have [patch 57353](https://bugs.winehq.org/attachment.cgi?id=57353), which is mandatory for macOS.

**Comment by ilovezfs** [comment]
@alexchandel then you'll need to convince upstream to include the patch. That's not going to happen unless users tell upstream they need it.

**Comment by alexchandel** [comment]
@ilovezfs The maintainer is 100% adamant that [the bug](https://bugs.winehq.org/show_bug.cgi?id=34166) not be fixed, and has chosen this hill to die on. However, your implication is also false, since the Homebrew formula for wine explicitly includes this patch. I don't see why `wine-staging` shouldn't be included as a flag on the `wine` formula, since it's just a collection of patches on top of wine.

**Comment by ilovezfs** [comment]
I think ultimately we may just need to remove the patch and leave this between users and wine.

**Comment by ilovezfs** [comment]
@alexchandel also note that Apple provided guidance on how to fix it properly, and as far as I can tell the wine devs haven't mentioned trying it or not trying it: https://bugs.winehq.org/show_bug.cgi?id=34166#c89

**Comment by virus-found** [comment]
For me it would be really lovely to be able to build my own wine-staging whenever I want.
Any clues how to do this via `brew edit` ?
