### ISSUE TITLE
Fix patch URL in dirmngr formula

### ISSUE THREAD

**Issue by alyssais** [Homebrew/homebrew-core#12001]
Trying to install `dirmngr` from source fails because of a broken patch URL: https://bugs.gnupg.org/gnupg/file419/dirmngr-pth-fix.patch. It just redirects to https://dev.gnupg.org.

This is what needs to be done to fix this:

- Track down the patch. There's some detail in the formula about what the patch fixes that should help you find it. If it's been deleted, it'll need to be recovered somehow and added to [our own patch repo](https://github.com/Homebrew/formula-patches).
- Fix the URL in the formula. You can run <kbd>brew edit dirmngr</kbd> from the command line or just open up the Library/Taps/homebrew/homebrew-core/Formula/dirmngr.rb file in your Homebrew installation (/usr/local/Homebrew by default).
- Install dirmngr from source with <kbd>brew install -s dirmngr</kbd> and check it works with <kbd>brew test dirmngr</kbd>
- Commit your changes and create a pull request. Here's our [documentation](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#contribute-a-fix-to-the-foo-formula) explaining how to do that in more detail.

This would probably be a good first issue for somebody who hasn't contributed to Homebrew before — the hard part will be looking through the GNU bug tracker to figure out what happened to the patch. If you need any help with the Homebrew side, you can comment in this issue, or get in touch privately with me — I'm [@qyliss](https://twitter.com/qyliss) on Twitter and my email address is in my profile. Good luck! :D

***

<details>
<summary>Issue template stuff</summary>

- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? <ins><q><code>Error: No logs</code></q></ins>
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
<summary><kbd>brew config</kbd></summary>
<blockquote><pre>
HOMEBREW_VERSION: 1.1.12-2-g5ab904ed9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5ab904ed93eafdb7e87e509fa928854880653db1
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2b96f26d9123bc112f5b8f2e6d6f102c3c7424cc
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/alyssa/.rubies/ruby-2.4.0/bin/ruby
Java: 1.8.0_112
macOS: 10.12.4-x86_64
Xcode: 8.3
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11
</pre></blockquote>
</details>

<details>
<summary><kbd>brew doctor</kbd></summary>
<blockquote><pre>
</pre></blockquote>
</details>

</details>

**Comment by fstoerkle** [comment]
The GnuPG issue with the linked patch can be found here: https://dev.gnupg.org/T1590, the patch is still linked there, with a new URL: https://dev.gnupg.org/D186

However, I did not find a stable URL that enables us to download the raw patch – there is only a one-time download URL. Therefore, I guess we need to add the patch to [Homebrew/formula-patches](https://github.com/Homebrew/formula-patches)

**Comment by fstoerkle** [comment]
I'd like to take care of this, will give an update later

**Comment by fstoerkle** [comment]
Here are two PRs that fix the problem:
- New patch added for dirmngr: https://github.com/Homebrew/formula-patches/pull/127
- Updated patch URL in formula: https://github.com/Homebrew/homebrew-core/pull/12005

**Comment by alyssais** [comment]
That's amazing @fstoerkle! I'll have a look over them.

**Comment by alyssais** [comment]
Fixed by #12005. Thanks for your contribution to Homebrew, @fstoerkle! You're awesome! 😃
