### ISSUE TITLE
Warnings caused by zlib transition from dupes to core

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-core#12007]
Was getting a number of these warnings:

```Warning: Use zlib instead of deprecated homebrew/dupes/zlib```

Appears due to php71 and httpd24 being built with dupes/zlib and now causing warnings to use the core zlib. There was no clear solution indicated by the warning.

Attempted the following which caused the same warnings, probably because ```reinstall``` was still trying to use dupes/zlib:
```$ brew reinstall http24; brew reinstall php71```

The way I finally fixed it:
```
$ brew uninstall zlib
$ brew uninstall php71
$ brew uninstall httpd24
$ brew untap homebrew/dupes
$ brew install httpd24
$ brew install <with various options> php71
```

Suggestion:
* Homebrew formula transitions should either be handled in a seamless way for the user (reinstalling items properly as necessary, etc), or warning/docs should indicate recommended approach for dealing with the formula transition(s). The current warnings do not indicate any clear course of action and leave the user a bit stranded.

**Comment by edrozenberg** [comment]
Still getting the warnings after doing the steps above, guess the problem is ultimately caused by the httpd22.rb and httpd24.rb formulas needing to be edited to change the ```depends_on "homebrew/dupes/zlib``` line.

**Comment by fxcoudert** [comment]
Thanks for reporting this, we are currently updating all these. The warnings will soon be gone

**Comment by fxcoudert** [comment]
This will be fixed by https://github.com/Homebrew/homebrew-apache/pull/160
