### ISSUE TITLE
rustup-init does not install shell completions

### ISSUE THREAD

**Issue by adinklotz** [Homebrew/homebrew-core#120964]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.6.19-12-g260ee0e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 260ee0ee6af21d31e8c57f6855d661ff6b325fb9
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ef02c6ac3053503e90207091c239443835c5bf70
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

rustup provides shell completions for itself and cargo through a `rustup completions` subcommand, as described [here](https://rust-lang.github.io/rustup/installation/index.html#enable-tab-completion-for-bash-fish-zsh-or-powershell). Brew does not currently seem to install these.

### What happened (include all command output)?

N/A

### What did you expect to happen?

The outputs of `rustup completions {zsh/bash/fish} {cargo/rustup}` should be installed to the respective completion script directories

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install rustup-init
rustup <tab> # expect a list of subcommands, get generic directory listing
```

**Comment by SMillerDev** [comment]
If it's a command the user can run it doesn't seem up to the packager to run it. https://rust-lang.github.io/rustup/installation/index.html?highlight=Comple#enable-tab-completion-for-bash-fish-zsh-or-powershell has documentation.

**Comment by adinklotz** [comment]
Ok but there's precedent for packages saving generated completion scripts as part of install, see e.g. [gh](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gh.rb).

Actually, I hadn't read through that source before and didn't realize there's even a `generate_completions_from_executable` helper function. If it's that easy I'll just write the PR unless you think it wouldn't be wanted

**Comment by SMillerDev** [comment]
You can make the pull request and it might be useful for people. But having to follow upstream documentation on shell completion is not a bug in brew.
