### ISSUE TITLE
Formula changes made when bumping libpsl from 0.21.1 to 0.21.2 introduced breaking changes

### ISSUE THREAD

**Issue by ckerr** [Homebrew/homebrew-core#121081]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
## brew config

HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d8f0c070cca0dfad47089f75fabc54353a6c09ac
Core tap last commit: 54 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2

## brew doctor

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm a developer on [Transmission](https://github.com/transmission/transmission), which on macOS can be built with a system-installed copy of libpsl, such as the one provided by Homebrew.

Homebrew [recently updated from 0.21.1 to 0.21.2](https://github.com/Homebrew/homebrew-core/pull/119028) of libpsl. This bump [changed the build steps](https://github.com/Homebrew/homebrew-core/pull/119028/files#diff-502b5196af391aa272fa0593caa52d756d18474053f8361c013a8a8bf26577a0R26) to disable the compile-time suffix list, so there effectively is no more default list. (@kazuho [also reported this](https://github.com/Homebrew/homebrew-core/pull/119028#issuecomment-1372088438)).

Bumping from 0.21.1 to 0.21.2 is a semver-patch bump, but this formula change introduced a non-bugfix change in runtime behavior. Calls to `psl_builtin()` before https://github.com/Homebrew/homebrew-core/commit/6bf29651214d70569823e6d6fa1344b7bccce16e would return a PSl context that was built at compile time; it now returns `NULL`. 

### What happened (include all command output)?

Transmission's unit tests and runtime fail when built on a system with Homebrew libpsl 0.21.2 installed, but not with Homebrew 0.21.1 installed.

### What did you expect to happen?

I would expect that a semver-patch bugfix bump would not introduce breaking changes due to a formula change.

libpsl should be built with a default psl context.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
IDK if this helpful to you since it's basically "brew install libpsl" -> clone & build Transmission :smile:

However if you'd like to see a sample output, [this GitHub Action CI run](https://github.com/transmission/transmission/actions/runs/3960513272/jobs/6790416506) which lists the full steps and command output leading up to the test failures after using [brew install libpsl](https://github.com/transmission/transmission/actions/runs/3960513272/jobs/6790416506#step:3:1).
```

**Comment by SMillerDev** [comment]
The way it was built before stopped working. If you find a way to restore the old behaviour a pull request would be welcome.

**Comment by carlocab** [comment]
Please test #121083 to see if it helps. This might work, if you have `gh` installed (`brew install gh`):

```
cd "$(brew --repository homebrew/core)"
gh pr checkout 121083
brew reinstall --build-from-source libpsl
git checkout master
```

and then try to see if the rebuilt `libpsl` fixes your problem.

**Comment by ckerr** [comment]
It does!

**Comment by carlocab** [comment]
This should be fixed now. If you find that it's not, try doing
```
brew update && brew reinstall libpsl
```
Thanks for the report!
