### ISSUE TITLE
How to get back Homebrew to previous state?

### ISSUE THREAD

**Issue by GRV22** [Homebrew/homebrew-core#12102]
I deleted some of .rb files(cassandra.rb, cassandra@2.1.rb and cassandra@2.2.rb) from folder /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ from mac system.I want back those .rb files.
I thought brew upgrade will give me back those deleted .rb files back.But they are still missing. Those .rb files are important for me to install packages.
brew install cassandra gives

Updating Homebrew...
Error: No available formula with the name "cassandra" 
==> Searching for a previously deleted formula...
cassandra was deleted from homebrew/core in commit d20fe73:
  cassandra: update 3.10_1 bottle.

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show d20fe73^:Formula/cassandra.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html

I tried also this command
brew install https://github.com/Homebrew/homebrew-core/blob/master/Formula/cassandra@2.2.rb
it gives 

######################################################################## 100.0%
Error: cassandra@2.2: /Users/sajjan.kumar/Library/Caches/Homebrew/Formula/cassandra@2.2.rb:7: syntax error, unexpected '<'
...
...
...
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Please I need solution "how to get back these .rb files?" or "any other alternative way to install cassandra".

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
