### ISSUE TITLE
nano 2.8.0 formula issue with nanorc files

### ISSUE THREAD

**Issue by kapitainsky** [Homebrew/homebrew-core#12136]
after updating nano to version 2.8.0 syntax highlights don't work anymore. 

Starting nano every included nanorc generates error e.g.:

Error in /usr/local/share/nano/autoconf.nanorc on line 29: Bad regex "[[:<:]]dnl.*": Invalid character class name

After some investigation I found that nanorc files in 2.8.0 are not compatible with Mac OS regex parser. Replacing all   \< and \> by \b character in nanorc files fix the issue. Not sure though if it is formula or latest nano issue.

**Comment by ilovezfs** [comment]
Yeah we need the patch from https://savannah.gnu.org/bugs/?50705

**Comment by ilovezfs** [comment]
@kapitainsky https://github.com/Homebrew/homebrew-core/pull/12143 should take care of it once merged, if you'd like to test it.

**Comment by kapitainsky** [comment]
Tested. Works as expected no. Thx

**Comment by ilovezfs** [comment]
Thanks for testing. Shipped!
