### ISSUE TITLE
Upstream tagging/versioning error in git-town

### ISSUE THREAD

**Issue by g-a-c** [Homebrew/homebrew-core#121365]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew config`:

HOMEBREW_VERSION: 3.6.20-49-g462c69d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 462c69d3d59fc2c660da23687bdb7b32b4d647fd
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2e5889864fbf5ca5cf8d4fd4e8b17a53c0d5cf61
Core tap last commit: 54 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

--
`brew doctor`:

Your system is ready to brew
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install a current version of `git-town` to match the current documentation on the website

### What happened (include all command output)?

Due to upstream tagging/versioning issues, I got a version tagged `v7.9.0` which is NOT actually the latest code, tagged `7.9.0` (no `v`-prefix). This means that the documentation on the Git Town website is not accurate for what you get via Homebrew

https://github.com/git-town/git-town/compare/v7.9.0...7.9.0 shows the changes between `v7.9.0` (which is what Homebrew currently installs) and `7.9.0` (which is what the documentation is for, and is the "current" latest release).

I don't know the best way to address this in Homebrew; it feels like a version bump in `brew` to make this `7.9.0_1` and then update the URL to use the `7.9.0` code without the `v`-prefix is a good thing to do, but underscore versioning is specifically for formula changes without code changes, which this is not.

### What did you expect to happen?

The documentation matches the installed binary

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install git-town
- git town version (see `v7.9.0 (2022/12/28)`)
- run `git town install aliases true`
  - according to current docs (https://www.git-town.com/installation-commands.html) this is a valid command, and with the `7.9.0` tag, it should be
  - with the `v7.9.0` tag that Homebrew builds, this is an invalid command because the `install` subcommand is not implemented
```

**Comment by carlocab** [comment]
This tag was yanked. https://github.com/Homebrew/homebrew-core/issues/122686
