### ISSUE TITLE
Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections in the context of brew install brewsci/bio/nullarbor

### ISSUE THREAD

**Issue by NathAmack** [Homebrew/homebrew-core#121311]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
(base) user@ubuntu:~$ brew config
HOMEBREW_VERSION: 3.6.20-14-g31ed690
ORIGIN: https://github.com/Homebrew/brew
HEAD: 31ed6906f927ec7c63b72c6f5c7d72ea6baa2fb4
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0af9a9f2914fd755a6b1bcf60d32bb760691639e
Core tap last commit: 37 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: 16-core 64-bit unknown_0x6_0xa7
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-58-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.1 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: 3.0.2
glibc: N/A
gcc@11: 12.2.0
gcc: 12.2.0
xorg: N/A

(base) user@ubuntu:~$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install the pipeline nullarbor to perform the associated data analysis 

### What happened (include all command output)?

I am getting an ERROR message
Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
(see also below)

(base) user@ubuntu:~$ brew install brewsci/bio/nullarbor
==> Fetching dependencies for brewsci/bio/nullarbor: tabixpp, vcflib, vt, gzip, snippy and snp-dists
==> Fetching brewsci/bio/tabixpp
==> Downloading https://ghcr.io/v2/brewsci/bio/tabixpp/manifests/1.1.1
Already downloaded: /home/user/.cache/Homebrew/downloads/e6bfe99c0d419183f176575fb7493e00f0b6c9a405e2c08a7e6bb87f35d38b6d--tabixpp-1.1.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/tabixpp/blobs/sha256:fef2b7232b66f4851fba14c0c24ff5f4e579077ddf7b516af9b1d694f5264318
Already downloaded: /home/user/.cache/Homebrew/downloads/a83c1f324e8c53d48f157fbf7d54c1395688c72737e0e144337f4fd5eb6c9126--tabixpp--1.1.1.x86_64_linux.bottle.tar.gz
==> Fetching brewsci/bio/vcflib
==> Downloading https://ghcr.io/v2/brewsci/bio/vcflib/manifests/1.0.3
Already downloaded: /home/user/.cache/Homebrew/downloads/1560fd99a7d717da2b61e0976c9e2bdbf11a4cdc59f8e9db984efb03d8aa5e0a--vcflib-1.0.3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/vcflib/blobs/sha256:47f04c252cb344b3debdfdf8b65e0db0a086d18f4f3437514078579b48251000
Already downloaded: /home/user/.cache/Homebrew/downloads/9bfc781d43500716d13b9313bb7c52e8eb59cc4a807acf27f64f63d2678b8adb--vcflib--1.0.3.x86_64_linux.bottle.tar.gz
==> Fetching brewsci/bio/vt
==> Downloading https://ghcr.io/v2/brewsci/bio/vt/manifests/0.5772_2
Already downloaded: /home/user/.cache/Homebrew/downloads/df61450271138486dd9dda2f28fcf66c52ca82bfc14d9bf375673e7210477a89--vt-0.5772_2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/vt/blobs/sha256:a2f0c3b7e3078719d39b7d257d964f19d327e3a3638c9e1397d804588da811f6
Already downloaded: /home/user/.cache/Homebrew/downloads/842610080a9aa6e594bd28ca3e68fc211a9d90c85767991bad71f0a8a717bcad--vt--0.5772_2.x86_64_linux.bottle.tar.gz
==> Fetching gzip
==> Downloading https://ghcr.io/v2/homebrew/core/gzip/manifests/1.12
Already downloaded: /home/user/.cache/Homebrew/downloads/bc24420562f3d33063f5d82330623d4b794e2d5050cdecd043f9f87ef2bdd758--gzip-1.12.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gzip/blobs/sha256:0112fa3e595f2f5e7b95c939aba21ddaeca8e710138e9c7d1258442c8ad758aa
Already downloaded: /home/user/.cache/Homebrew/downloads/bccffd7add4dfb76b9238470b7877060ccf5ff4ab8934cc82fed451a64166c37--gzip--1.12.x86_64_linux.bottle.tar.gz
==> Fetching brewsci/bio/snippy
==> Downloading https://ghcr.io/v2/brewsci/bio/snippy/manifests/4.6.0
Already downloaded: /home/user/.cache/Homebrew/downloads/1e34751b4618ef3fcda56b2ecc90def8f1fd8583d3ab96419291665a90c2e37d--snippy-4.6.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/snippy/blobs/sha256:c7a253e55f63fa2969d95ff81908f7fc61a6b1b09cc46b9d796511071396251b
Already downloaded: /home/user/.cache/Homebrew/downloads/009d8ae802e47e6628ba1e0a372f9dd9be5f535bfe8a68212eb59ee86a9872bf--snippy--4.6.0.x86_64_linux.bottle.tar.gz
==> Fetching brewsci/bio/snp-dists
==> Downloading https://ghcr.io/v2/brewsci/bio/snp-dists/manifests/0.7.0
Already downloaded: /home/user/.cache/Homebrew/downloads/3d1412338f8fa27adfa6df21f41fa70c5128f61bc7948dad769ec272f2247cc6--snp-dists-0.7.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/brewsci/bio/snp-dists/blobs/sha256:1e6bd8de0a2fc72365256c8b7ce8fcb2d3f53a108ecc719f57d417796ea45e5c
Already downloaded: /home/user/.cache/Homebrew/downloads/8d4870f83ecfebdb196bbd5e1fd0b171134f78c9daddbab8d5dc8451b257b6fa--snp-dists--0.7.0.x86_64_linux.bottle.tar.gz
==> Fetching brewsci/bio/nullarbor
==> Downloading https://github.com/tseemann/nullarbor/archive/v2.0.20191013.tar.gz
Already downloaded: /home/user/.cache/Homebrew/downloads/ecef42c05ce94e10c1e7c4b7a9e2cc2014cdc0369528f233e5a89d09e64c1025--nullarbor-2.0.20191013.tar.gz
==> Installing nullarbor from brewsci/bio
==> Installing dependencies for brewsci/bio/nullarbor: tabixpp, vcflib, vt, gzip, snippy and snp-dists
==> Installing brewsci/bio/nullarbor dependency: tabixpp
==> Pouring tabixpp--1.1.1.x86_64_linux.bottle.tar.gz
Error: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:682:in `normalize_note_segment'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:659:in `block in normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:955:in `block in phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `each_with_index'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:952:in `phdrs_by_type'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:653:in `normalize_note_segments'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:638:in `rewrite_sections_library'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:475:in `rewrite_sections'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/alt_saver.rb:88:in `save!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib/patchelf/patcher.rb:191:in `save'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:167:in `save_using_patchelf_rb'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:112:in `patch!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:53:in `change_rpath'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:15:in `block (2 levels) in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:341:in `ensure_writable'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:14:in `block in relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:13:in `relocate_dynamic_linkage'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/keg_relocate.rb:132:in `replace_placeholders_with_locations'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1236:in `pour'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:426:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:737:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:657:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:657:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:657:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:403:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/upgrade.rb:203:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:350:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:340:in `block in install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/install.rb:339:in `install_formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:98:in `<main>'

### What did you expect to happen?

I expected to get the pipeline and the associated packages installed
(PS: first post here, I read the different documents, but let me know in case I forgot /missed something; thanks and best wishes :-) )

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install brewsci/bio/nullarbor
```

**Comment by SMillerDev** [comment]
This should be reported to https://github.com/brewsci/homebrew-bio since that's the tap that's reporting the issue.
