### ISSUE TITLE
Tab completion error for pass

### ISSUE THREAD

**Issue by Synesso** [Homebrew/homebrew-core#12160]
Tab completion for `pass` prints an error after recent brew update / upgrade. 

On pressing tab `-bash: compopt: command not found` is printed.

The completion does work. It is only the error message that is broken.

e.g.

```
pass foo/[tab]-bash: compopt: command not found

bar     baz
```

Diagnostics:
```
jem@Jems-MacBook-Pro:~つ brew config
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aacb5ab5d072a090804810df660ebc5f5c1e5344
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_40, 1.7.0_75
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11
```

```
jem@Jems-MacBook-Pro:~つ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  android-sdk
  docker
  docker-compose
  docker-machine
```

**Comment by bfontaine** [comment]
What makes you think this issue comes from Homebrew rather than Pass itself?

**Comment by Synesso** [comment]
Apologies. I don't know how this ended up on homebrew-core.

**Comment by HakimCassimallyBBC** [comment]
@Synesso did you ever find a fix for this?  We've all upgraded to OSX Sierra and had to reinstall everything inc homebrew and pass.  Is it the pass recipe that is missing a relevant dependency?

(I couldn't find 'compopt' in system bash, nor in the version 4.x installed by `brew install bash`.  Doing the latter also broke all existing bash completions, even with bash-completion2, so I've reverted.)

**Comment by Synesso** [comment]
No, sorry. I was unable to make any progress & have been putting up with it. Please report back if you find anything.

**Comment by santuari** [comment]
I face the same issue. 
Is there any solution?

**Comment by Synesso** [comment]
I revisited this today. I had a file `~/.profile` which contained:

```
export PATH="$HOME/.cargo/bin:$PATH"
export PS1="\[\e[38;5;202m\]\[\e[38;5;245m\]\u\[\e[00m\]@\[\e[38;5;2m\]\h\[\e[00m\]:\[\e[38;5;5m\]\w\[\e[00m\]つ "
alias ll='ls -aslH'
```

These settings are not used by my bash sessions. I removed the file and now completion works for pass.

I attempted this because of [this stackoverflow comment](https://apple.stackexchange.com/questions/211671/bash-1-command-not-found-immediately-on-loading-terminal#comment255512_211671). I can't tell you why it worked for me.

**Comment by jimdoescode** [comment]
Since pass isn't currently hosted on github and I was running into this same issue. The original problem was because the bash completion script for pass (located in `/usr/local/Cellar/pass/<version_number>/etc/bash_completion.d/pass` uses the compopt command which is available in later versions of bash but not the version of bash used in OSX. 

Updating the version of Bash used in OSX should fix the problem. Alternatively you could modify the completion script to not use compopt if you want to stick with stock bash.

**Comment by eak12913** [comment]
I was able to get around the issue using the "Alternatively" suggestion of @jimdoescode and then using the script from here: https://github.com/stuartsierra/password-store/blob/master/src/completion/pass.bash-completion
