### ISSUE TITLE
CIVL 1.7 fails to build on 10.11.3

### ISSUE THREAD

**Issue by AlshammariA** [Homebrew/homebrew-core#1217]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by AlshammariA** [comment]
Here is the error:

Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/civl.rb:1: syntax error, unexpected <<
<<<<<<< bf0893476780082ff025b519e78916d9c2e9ecf1
  ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/formulary.rb:220:in `from_rack'
/usr/local/Library/Homebrew/extend/ARGV.rb:37:in `block in resolved_formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:27:in `resolved_formulae'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:175:in `gist_logs'
/usr/local/Library/brew.rb:87:in `<main>'

**Comment by mikemcquaid** [comment]
Running `brew update` or `cd /usr/local/Library/Taps/homebrew/homebrew-core; git reset --hard origin/master` should fix this for you.

**Comment by AlshammariA** [comment]
thank you @mikemcquaid for your help. It works now

**Comment by dunn** [comment]
Great!
