### ISSUE TITLE
zsh-completion chmod caneat needs further improvement

### ISSUE THREAD

**Issue by 75033us** [Homebrew/homebrew-core#121742]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs zsh-completion
Error: No logs.
```

```
% brew config
HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 73fed2110506e6ef510e2ff251ea3c645a97fc26
Core tap last commit: 15 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

```
% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

After install `brew install zsh-completion`, it suggest to fix the `.zshrc` to enable the completion:

```
% brew info zsh-completion

==> zsh-completions: stable 0.34.0 (bottled), HEAD
Additional completion definitions for zsh
https://github.com/zsh-users/zsh-completions
/opt/homebrew/Cellar/zsh-completions/0.34.0 (151 files, 1.2MB) *
  Poured from bottle on 2023-01-24 at 09:11:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/zsh-completions.rb
License: MIT-Modern-Variant
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate these completions, add the following to your .zshrc:

  if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
  fi

You may also need to force rebuild `zcompdump`:

  rm -f ~/.zcompdump; compinit

Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
to load these completions, you may need to run this:

  chmod -R go-w '/opt/homebrew/share/zsh'
```

### What happened (include all command output)?

I fixed the permission according to the instruction:

```
%  chmod -R go-w '/opt/homebrew/share/zsh'
```

And I open a new terminal, I saw

```
Last login: Fri Jan 27 19:05:05 on console
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]?
```

### What did you expect to happen?

My expectation would be no longer to see the warning message.

### Step-by-step reproduction instructions (by running `brew` commands)

In the last line, `chmod -R go-w '/opt/homebrew/share/zsh'` is not good enough to fix the warning `zsh compinit: insecure directories`.

When I run `compaudit` and found the following:

```
~ % compaudit
There are insecure directories:
/opt/homebrew/share
```

I checked the history of the formula, we used to do that before https://github.com/Homebrew/homebrew-core/pull/67250.

I would suggest we should do both in the instruction:

```
  chmod go-w '/opt/homebrew/share'
  chmod -R go-w '/opt/homebrew/share/zsh'
```

Thank you very much.

**Comment by fxcoudert** [comment]
@75033us could you open a pull request to fix the issue?
