### ISSUE TITLE
OpenCV 4.7.0 SHA Missmatch

### ISSUE THREAD

**Issue by blackandcold** [Homebrew/homebrew-core#121929]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config           
                                                                                       
HOMEBREW_VERSION: 3.6.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 344d32bf7f40183359592ef81ca6486e0587981b
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 928dc4dfcc24ab78e830a50fb260b7db318cff0e
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/XXX/homebrew
HOMEBREW_REPOSITORY: /Users/XXX/homebrew
HOMEBREW_CELLAR: /Users/XXX/homebrew/Cellar
HOMEBREW_CASK_OPTS: ["--appdir=~/programs"]
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

brew doctor   
                                                                                                 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /opt/homebrew.

Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
Consider uninstalling Homebrew and reinstalling into the default prefix.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

When installing siril with "brew install siril" the dependency opencv has a SHA missmatch.
I can confirm that the expected SHA is present in the main branch opencv.rb file.

That I use my home as brew directory has nothing to do with the problem.
(Company device, keeping it clean!)

### What happened (include all command output)?

==> Fetching opencv
Warning: Building opencv from source as the bottle needs:
- HOMEBREW_CELLAR: /opt/homebrew/Cellar (yours is /Users/IP3RGFY/homebrew/Cellar)
- HOMEBREW_PREFIX: /opt/homebrew (yours is /Users/IP3RGFY/homebrew)
==> Downloading https://github.com/opencv/opencv_contrib/archive/refs/tags/4.7.0.tar.gz
Already downloaded: /Users/XXX/Library/Caches/Homebrew/downloads/1df1f49749d668e4c597f72b86170c2c1f3300745829256579ded740d1536c9d--opencv_contrib-4.7.0.tar.gz
Error: siril: SHA256 mismatch
Expected: 42df840cf9055e59d0e22c249cfb19f04743e1bdad113d31b1573d3934d62584
  Actual: 53ce5287b2004c26e339854327b6adad1f6105d4a6c89975adb218cbf98315f5
    File: /Users/XXX/Library/Caches/Homebrew/downloads/1df1f49749d668e4c597f72b86170c2c1f3300745829256579ded740d1536c9d--opencv_contrib-4.7.0.tar.gz
To retry an incomplete download, remove the file above.

### What did you expect to happen?

Siril to install obviously :)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Try and install opencv 4.7.0
```

**Comment by blackandcold** [comment]
Link is missing to the SHA
https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb#L50

**Comment by carlocab** [comment]
Delete this file then try again.
```
/Users/XXX/Library/Caches/Homebrew/downloads/1df1f49749d668e4c597f72b86170c2c1f3300745829256579ded740d1536c9d--opencv_contrib-4.7.0.tar.gz
```

**Comment by blackandcold** [comment]
can confirm that the file online really has the stated SHA256

Will prune and report back, thanks!
