### ISSUE TITLE
Gitbucket 3.14 is required for upgrade to Gitbucket 4.0

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#1222]
For existing Gitbucket users version 3.13 or older, they will need to upgrade to 3.14 before upgrading to Gitbucket 4.0. Otherwise, it will result in this error

2016-05-17 15:59:15.948:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@106cc338{/,file:///Users/hanxue/.gitbucket/tmp/webapp/,STARTING}{file:/usr/local/Cellar/gitbucket/4.0/libexec/gitbucket.war}
java.lang.Exception: GitBucket can't migrate from this version. Please update to 3.14 at first.

See the [GitBucket 4.0 release note](https://github.com/gitbucket/gitbucket/blob/master/README.md). 

Looking at the `gitbucket.rb` history, there are updated formulas for `3.13` and `4.0`, but no `3.14`. 
```
4bbc3f0 gitbucket 4.0 (#763)
23e945c gitbucket 3.13
021ed0c Update gitbucket.rb
92829a7 gitbucket 3.12
```

Is there a way to add Gitbucket 3.13 formula into the history? E.g. downgrade the formula to *3.14*, then update it back to *4.0*

**Comment by mikemcquaid** [comment]
We don't support that unfortunately. We'll need to work out another way of doing this.

**Comment by dunn** [comment]
We could vendor 3.13 in the formula, like how we've vendored earlier versions of GHC for bootstrapping: [`ghc.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghc.rb)

**Comment by ilovezfs** [comment]
https://github.com/gitbucket/gitbucket/compare/3.13...3.14

I'm wondering if the magic is
```
ALTER TABLE WEB_HOOK ADD COLUMN CTYPE VARCHAR(10);

UPDATE WEB_HOOK SET CTYPE = 'form';
```

**Comment by ilovezfs** [comment]
It's been a month since this was released and so far no one else has mentioned this. @hanxue did you find a workaround?

**Comment by hanxue** [comment]
My workaround is to check out version `3.14` of the Gitbucket formula, uppgrade to `3.14`, and then upgrade to Gitbucket `4.0`

**Comment by ilovezfs** [comment]
Where does gitbucket put its data?

@DomT4 I wonder if a gitbucket314 formula in versions would do the trick. Something like

```
brew install homebrew/versions/gitbucket314
/usr/local/Cellar/gitbucket314/3.14/bin/gitbucket
brew upgrade gitbucket
brew uninstall gitbucket314
gitbucket
```

**Comment by ilovezfs** [comment]
Closing for now.
