### ISSUE TITLE
awscli: No module named 'docutils'

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#122238]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew config`


HOMEBREW_VERSION: 3.6.20-90-g824fdd6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 824fdd6b190e37f4c6b2e5804d775b096fc49c61
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: (none)
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BROWSER: open -a Firefox.app
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.yxV05lWEYp/org.xquartz:0
HOMEBREW_EDITOR: mate_wait
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_FROM_API: set
HOMEBREW_MAKE_JOBS: 10
SUDO_ASKPASS: /usr/local/bin/ssh-askpass
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.1 => /opt/homebrew/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
```

`brew doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  subliminal

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/BandedSmithWaterman.h
  /usr/local/include/BedReader.h
  /usr/local/include/Fasta.h
  /usr/local/include/IndelAllele.h
  /usr/local/include/IntervalTree.h
  /usr/local/include/LargeFileSupport.h
  /usr/local/include/LeftAlign.h
  /usr/local/include/Mosaik.h
  /usr/local/include/Region.h
  /usr/local/include/Repeats.h
  /usr/local/include/SmithWatermanGotoh.h
  /usr/local/include/Variant.h
  /usr/local/include/disorder.h
  /usr/local/include/filevercmp.h
  /usr/local/include/join.h
  /usr/local/include/makeUnique.h
  /usr/local/include/mt19937ar.h
  /usr/local/include/multichoose.h
  /usr/local/include/multipermute.h
  /usr/local/include/vec128int.h
  /usr/local/include/veclib_types.h
```

NB, I've checked the following boxes re `brew doctor`, even though it doesn't quite pass, since it seems that the above warnings are not pertinent to this case.
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run the `aws` program from the `awscli` formula.

### What happened (include all command output)?

```shell
$ aws
Traceback (most recent call last):
  File "/opt/homebrew/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/opt/homebrew/Cellar/awscli/2.9.20/libexec/lib/python3.11/site-packages/awscli/clidriver.py", line 43, in <module>
    from awscli.help import ProviderHelpCommand
  File "/opt/homebrew/Cellar/awscli/2.9.20/libexec/lib/python3.11/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
ModuleNotFoundError: No module named 'docutils'
```

### What did you expect to happen?

The program should run with producing a `ModuleNotFoundError` error.	

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew reinstall -f awscli
$ aws
```

**Comment by cho-m** [comment]
Check when you installed `docutils` (`brew info docutils`).

Particularly, if it is before https://github.com/Homebrew/homebrew-core/commit/4f5ab4156870311c56412af135ca0ec483b308b6, then you will need to `brew reinstall docutils`, otherwise it will have the Python 3.10 library rather than Python 3.11.

I don't think `docutils` was version/revision bumped recently so won't automatically update if you installed before 2022-11-21

**Comment by alexreg** [comment]
@cho-m I just reinstalled it a few hours ago after doing `brew update`.

**Comment by alexreg** [comment]
Well, I solved this with `pip3.11 install docutils` (since Python 3.10 is the version that gets linked still). But this should surely be done by the formula itself?

**Comment by cho-m** [comment]
> @cho-m I just reinstalled it a few hours ago after doing `brew update`. v2.9.20

`docutils` is v0.19. Needs to be rebuild 1 or 2.

**Comment by alexreg** [comment]
@cho-m Ah right, got it. I should have looked closer at the dependencies. (I had assumed docutils would just be installed in some sandbox site-packages by awscli, silly me...) Thanks for clearing this up.

**Comment by mvilain** [comment]
I've been installing docutils into each version of awscli when it's updated with the pip3.11 that comes with the package. aws works after that. I only see this problem on M1 installs. The intel install works fine.

/opt/homebrew/Cellar/awscli/2.9.21/libexec/bin/pip3.11 install docutils

**Comment by cho-m** [comment]
> @cho-m Ah right, got it. I should have looked closer at the dependencies. (I had assumed docutils would just be installed in some sandbox site-packages by awscli, silly me...) Thanks for clearing this up.

`docutils` used to be part of venv until https://github.com/Homebrew/homebrew-core/commit/c2b4aa1563bda53bf25daae56e62237c456bd3c1. Anyways, I'm revision bumping `docutils` in #122590 to distribute the correct `python@3.11` supported bottle to users.
