### ISSUE TITLE
SMake is moved to 

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-core#122336]
https://codeberg.org/schilytools/schilytools

Since @clausecker dropped by the FOSDEM stand to notify us of this I'm making an issue to remind me

**Comment by iMichka** [comment]
Looks like we shipped this. Thanks @alebcay !

@SMillerDev I think our new friend at FOSDEM will be happy about that next year :)

**Comment by clausecker** [comment]
Thank you for this update.  Much appreciated!
