### ISSUE TITLE
LLVM build problem

### ISSUE THREAD

**Issue by adah1972** [Homebrew/homebrew-core#12248]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? *This should be irrelevant, as I am reporting a problem of a bottled brew.*

To help us debug your issue please explain:
- I was installing doxygen with `brew install doxygen --with-graphviz --with-llvm`.
- Installation was successful, but running `doxygen` gives me:
```
dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/bin/doxygen
  Reason: image not found
Abort trap: 6
```
- Of course I expect it to work.
- Just my `brew install ...` command followed by running `doxygen` should reproduce the problem.

I am not familiar with the build of LLVM, so I am not proposing a solution here. I did find a workaround according to my understanding of the macOS dylib mechanism.

- I went into the */usr/local/opt/llvm/lib* directory.
- ``DYLIBS=`find . -name '*.dylib' -a -type f` ``
- `for DYLIB in $DYLIBS; do install_name_tool -id $PWD/$DYLIB $DYLIB; done`
- To my surprise, it failed, because the files were not writeable (mode 555 instead of the expected 755). I guess it *might* be related to the problem I encountered, as the builder might have failed to apply `install_name_tool` successfully.
- I did `find . -name '*.dylib' -exec chmod u+w {} \;`.
- Then `for DYLIB in $DYLIBS; do install_name_tool -id $PWD/$DYLIB $DYLIB; done` again.

After that, I reinstalled doxygen, and it was able to build and run successfully.

**Comment by ilovezfs** [comment]
What does `brew config` output?

**Comment by adah1972** [comment]
```
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0b4688c8666a14d774c3ae5f77b6f8d63c7ffb90
Core tap last commit: 81 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.3.0.0.1.1490382677
X11: N/A
```

**Comment by ilovezfs** [comment]
Great, thank you. I think this should work correctly once LLVM is rebuilt from source using brew master (as opposed to the 1.1.12 tag) due to https://github.com/Homebrew/brew/pull/2450.

**Comment by adah1972** [comment]
Got it. So it is a known issue. Thank you.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/12525.
