### ISSUE TITLE
git-town cannot build from source

### ISSUE THREAD

**Issue by benmoss** [Homebrew/homebrew-core#122686]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/608a9a75e57699a081a9f60395b5c1a5
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install `git-town` from source, to reproduce a test failure we're seeing in #122082

### What happened (include all command output)?

The download fails:
```
$ brew install --build-from-source git-town
==> Fetching git-town
######################################################################## 100.0%
==> Downloading https://github.com/git-town/git-town/archive/refs/tags/7.9.0.tar.gz
==> Downloading from https://codeload.github.com/git-town/git-town/tar.gz/refs/tags/7.9.0
curl: (22) The requested URL returned error: 404

Error: git-town: Failed to download resource "git-town"
Download failed: https://github.com/git-town/git-town/archive/refs/tags/7.9.0.tar.gz
```

### What did you expect to happen?

It should work and install from source

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Included above, but:


brew install --build-from-source git-town
```
```

**Comment by fxcoudert** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/122687
