### ISSUE TITLE
GraphicsMagick: configure with `--with-perl=yes` option

### ISSUE THREAD

**Issue by tenzap** [Homebrew/homebrew-core#122753]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

+ brew config
```shell
HOMEBREW_VERSION: 3.6.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 932d2cf3b77c9439a57b6a43577fc8d3b6399a62
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 81570d0a2f993c8c1a9a77701bb68935bcbb2724
Core tap last commit: 41 minutes ago
Core tap branch: master
Core tap JSON: 06 Feb 00:36 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 3-core 64-bit ivybridge
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.3-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2 => /Applications/Xcode_14.2.app/Contents/Developer
```
+ brew doctor
```
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm installing graphicsmagick on github runner because I need to use findimagedupes.

findimagedupes depends on the perl module  'Graphics::Magick' which is built by graphicsmagick provided it was build with `--with-perl=yes` option

Would it be possible to have this?

Currently, I have to proceed this way :
```
          # Graphics::Magick is provided by graphicsmagick
          brew install graphicsmagick

          # Install PerlMagick from GraphicsMagick to have Graphics::Magick
          wget https://netcologne.dl.sourceforge.net/project/graphicsmagick/graphicsmagick/1.3.40/GraphicsMagick-1.3.40.tar.xz
          tar -xf GraphicsMagick-1.3.40.tar.xz
          cd GraphicsMagick-1.3.40

          # Configure with the same configure arguments as homebrew, but with "--with-perl=yes"
          ./configure \
            --prefix=/usr/local \
            --disable-dependency-tracking \
            --disable-openmp \
            --disable-static \
            --enable-shared \
            --with-modules \
            --with-quantum-depth=16 \
            --without-lzma \
            --without-x \
            --without-gslib \
            --with-gs-font-dir=/usr/local/share/ghostscript/fonts \
            --without-wmf \
            --with-jxl \
            --with-perl=yes
          cd PerlMagick
          perl Makefile.PL
          make
          sudo make install

```

### What happened (include all command output)?

See above

### What did you expect to happen?

See above

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above
```

**Comment by carlocab** [comment]
We'll review a PR that does this. Please add a test for the added functionality. We can consider scoping it to macOS so that we don't need to add an extra dependency to the formula.

**Comment by tenzap** [comment]
Great! Hopefully someone will do (I don't run macos)

**Comment by tenzap** [comment]
Ping

**Comment by SMillerDev** [comment]
Clearly nobody else is interested and stalebot is there to keep issues open if they are actively progressing towards a fix.
