### ISSUE TITLE
Formula Not Relinking After Update

### ISSUE THREAD

**Issue by chryton** [Homebrew/homebrew-core#12287]
# Please always follow these steps:
- [X] Confirmed this is a problem with only one, specific formula and not Homebrew/brew
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew gist-logs node@6` (returned `Error: No logs.`)
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Brew Config
```
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: afe9867b31dc82e4317e7b5e268dc509acde2dd7
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_79
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: N/A
X11: N/A
```
### Brew Doctor Output
```
You may wish to `brew unlink` these brews:
  node@6
```

### Issue Explanations:
- What you were trying to do (and why)
-- Update `node@6` or `node6-lts` to the current version
- What happened (include command output)
-- Node updated but was no longer accessible view the path
- What you expected to happen
-- Node to still be accessible from the path

### Steps to Reproduce
1. Have `node@6` or `node6-lts` installed
1. Run `brew update` and `brew upgrade` after the formula is updated
1. Run an arbitrary `node` command such as `which node` or `gulp`
1. See `env: node: No such file or directory` returned

## Additional Notes
I believe that this is most possibly intended behavior but there is not clear messaging as what the user should do. The console output of `This formula is keg-only, which means it was not symlinked into /usr/local.` does not give enough information that this formula has to be relinked _every_ time it is updated or that you must use the `--force` command to do it each time.

**Comment by ilovezfs** [comment]
You should set your PATH instead of force linking, as described by the caveats:
```
iMac-TMP:~ joe$ brew install node@6
==> Downloading https://homebrew.bintray.com/bottles/node@6-6.10.2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring node@6-6.10.2.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Caveats
Please note by default only English locale support is provided. If you need
full locale support you should either rebuild with full icu:
  `brew reinstall node --with-full-icu`
or add full icu data at runtime following:
  https://github.com/nodejs/node/wiki/Intl#using-and-customizing-the-small-icu-build

This formula is keg-only, which means it was not symlinked into /usr/local.

This is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/node@6/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/node@6/lib
    CPPFLAGS: -I/usr/local/opt/node@6/include


Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node@6/6.10.2: 3,073 files, 41.5MB
```

Specifically, do this bit:
```
If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/node@6/bin:$PATH"' >> ~/.bash_profile
```
