### ISSUE TITLE
panic default data-dir

### ISSUE THREAD

**Issue by mskblackbelt** [Homebrew/homebrew-core#12296]
This isn't a build-failure issue, but rather a setting issue that I can't seem to figure out what to modify. When installing pandoc via `brew install pandoc` (no additional settings used) then trying something like:
```shell
pandoc --template=my-custom-template.latex ./letter.md -o ./letter.pdf
```
I get an output like this:

    pandoc: Could not find data file /usr/local/Cellar/pandoc/1.19.2.1/share/x86_64-osx-ghc-8.0.2/pandoc-1.19.2.1/data/templates/template-letter.latex

suggesting that the data-dir variable is not correctly set for pandoc. However, `pandoc --version` outputs the following:

    pandoc 1.19.2.1
    Compiled with pandoc-types 1.17.0.5, texmath 0.9, skylighting 0.1.1.4
    Default user data directory: /Users/mskblackbelt/.pandoc
    Copyright (C) 2006-2016 John MacFarlane
    Web:  http://pandoc.org
    This is free software; see the source for copying conditions.
    There is no warranty, not even for merchantability or fitness
    for a particular purpose.

I've tried placing my template files in `~/.pandoc`, as suggested in the pandoc manual. What am I missing here? As far as I can tell, pandoc is correctly configured out of the bottle, yet I can't run it the way I expect… If I define the full path to the template when I call pandoc, everything runs without incident.

**Comment by bfontaine** [comment]
According to [this StackOverflow thread](http://stackoverflow.com/q/40390667/735926) it might be an issue with how you wrote your template.
