### ISSUE TITLE
Pango won't compile

### ISSUE THREAD

**Issue by alexstaj** [Homebrew/homebrew-core#12298]
tha@bioinfo:~$ brew upgrade
Error: Another active Homebrew update process is already in progress.
Please wait for it to finish or terminate it to continue.
==> Upgrading 2 outdated packages, with result:
cmake 3.7.2_1, pango 1.40.5
==> Upgrading cmake 
==> Downloading https://linuxbrew.bintray.com/bottles/cmake-3.7.2_1.x86_64_linux
######################################################################## 100.0%
==> Pouring cmake-3.7.2_1.x86_64_linux.bottle.tar.gz
==> Caveats

Emacs Lisp files have been installed to:
  /home/tha/.linuxbrew/share/emacs/site-lisp/cmake
==> Summary
🍺  /home/tha/.linuxbrew/Cellar/cmake/3.7.2_1: 2,142 files, 60.3MB
==> Upgrading pango 
==> Installing dependencies for pango: berkeley-db@4
==> Installing pango dependency: berkeley-db@4
==> Downloading https://linuxbrew.bintray.com/bottles/berkeley-db@4-4.8.30.x86_6
######################################################################## 100.0%
==> Pouring berkeley-db@4-4.8.30.x86_64_linux.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /home/tha/.linuxbrew.

This is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/home/tha/.linuxbrew/opt/berkeley-db@4/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/home/tha/.linuxbrew/opt/berkeley-db@4/lib
    CPPFLAGS: -I/home/tha/.linuxbrew/opt/berkeley-db@4/include

==> Summary
🍺  /home/tha/.linuxbrew/Cellar/berkeley-db@4/4.8.30: 4,596 files, 82.2MB
==> Installing pango 
==> Downloading https://download.gnome.org/sources/pango/1.40/pango-1.40.5.tar.x
==> Downloading from https://muug.ca/mirror/gnome/sources/pango/1.40/pango-1.40.
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/home/tha/.linuxbrew/Cellar/pang
==> make
Last 15 lines from /home/tha/.cache/Homebrew/Logs/pango/02.make:
distutils.errors.CompileError: command 'gcc-5' failed with exit status 1
/home/tha/.linuxbrew/Cellar/gobject-introspection/1.52.0_1/share/gobject-introspection-1.0/Makefile.introspection:159: recipe for target 'Pango-1.0.gir' failed
make[4]: *** [Pango-1.0.gir] Error 1
make[4]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5/pango'
Makefile:1299: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5/pango'
Makefile:1042: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5/pango'
Makefile:580: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/pango-20170410-14108-3wp634/pango-1.40.5'
Makefile:469: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

**Comment by jorgenarntzen** [comment]
Last 15 lines from /Users/jorgenarntzen/Library/Logs/Homebrew/pango/02.make:
        XGenericEventCookie *in,
        ^
/opt/X11/include/X11/Xlibint.h:1429:9: error: unknown type name 'XGenericEventCookie'
        XGenericEventCookie *out);
        ^
18 errors generated.
make[4]: *** [pangoxft-fontmap.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/usr/local/Cellar/pango/1.40.5/etc\" -DLIBDIR=\"/usr/local/Cellar/pango/1.40.5/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -D_REENTRANT -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.29/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/graphite2/1.3.9/include -I/usr/local/Cellar/harfbuzz/1.4.5/include/harfbuzz -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -fvisibility=hidden -g -O2 -Wall -c pangoxft-render.c -o pangoxft-render.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/usr/local/Cellar/pango/1.40.5/etc\" -DLIBDIR=\"/usr/local/Cellar/pango/1.40.5/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -D_REENTRANT -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.29/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/graphite2/1.3.9/include -I/usr/local/Cellar/harfbuzz/1.4.5/include/harfbuzz -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -fvisibility=hidden -g -O2 -Wall -c pangocairo-context.c  -fno-common -DPIC -o .libs/pangocairo-context.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -DG_LOG_DOMAIN=\"Pango\" -DPANGO_ENABLE_BACKEND -DPANGO_ENABLE_ENGINE -DSYSCONFDIR=\"/usr/local/Cellar/pango/1.40.5/etc\" -DLIBDIR=\"/usr/local/Cellar/pango/1.40.5/lib\" -I.. -I.. -DG_DISABLE_CAST_CHECKS -D_REENTRANT -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/libpng/1.6.29/include/libpng16 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/pixman/0.34.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.14.8/include/cairo -I/opt/X11/include -I/usr/local/Cellar/pcre/8.40/include -I/usr/local/Cellar/glib/2.52.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.52.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/graphite2/1.3.9/include -I/usr/local/Cellar/harfbuzz/1.4.5/include/harfbuzz -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.12.1_2/include -I/usr/local/opt/freetype/include/freetype2 -fvisibility=hidden -g -O2 -Wall -c pangocairo-context.c -o pangocairo-context.o >/dev/null 2>&1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html

**Comment by ilovezfs** [comment]
@alexstaj please report Linuxbrew issues to https://github.com/Linuxbrew/homebrew-core/
