### ISSUE TITLE
Incorrect config in`neo4j` formula

### ISSUE THREAD

**Issue by jackwaudby** [Homebrew/homebrew-core#122909]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to `brew install neo4j` but when I navigate to the package installation and attempt to start `neo4j` using `./bin/neo4j start` it fails due to  unrecognisable config parameters. Namely wrapper.java.additional and its friend wrapper.java.additional.4. 

Removing these parameters from the `neo4j.rb` file would solve this issue and allow it to start 

### What happened (include all command output)?

Failed to read config /usr/local/Cellar/neo4j/5.4.0/libexec/conf/neo4j.conf: Unrecognized setting. No declared setting with name: wrapper.java.additional.4. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.

### What did you expect to happen?

neo4j should start 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install neo4j`
`cd /usr/local/Cellar/neo4j/5.4.0`
`./bin/neo4j start`
```

**Comment by carlocab** [comment]
That comes from here:

https://github.com/Homebrew/homebrew-core/blob/88be0f6d48a9c7d913a739a1a7f3dd3d6227b2ae/Formula/neo4j.rb#L44-L45

No idea what they're supposed to be doing, though. Maybe we can just remove them? Ideally we should figure out what they're meant to be for and fix them appropriately.

**Comment by brettgus** [comment]
I am having this same issue as well.

**Comment by cho-m** [comment]
Previous issue: https://github.com/Homebrew/homebrew-core/issues/114553.

The fastest way to get a fix is for someone knowledgable about `neo4j` to submit a PR for updating config. I don't think any maintainer is using `neo4j` so will have a slower turnaround (as seen by previous issue going stale).

---

As note, the configs appear to have been renamed twice:
- `wrapper.java.additional` (v2) --> `dbms.jvm.additional` (v3), ref: https://neo4j.com/developer/kb/manually-migrating-configuration-settings-from-neo4j-2x-to-neo4j-3x/
- `dbms.jvm.additional` (v4) -->  `server.jvm.additional` (v5), ref: https://neo4j.com/docs/upgrade-migration-guide/current/version-5/changelogs/configuration-settings/

I'm guessing 1st migration deprecated original config and 2nd migration removed it as a valid config.

**Comment by cham423** [comment]
I am not a `neo4j` expert by any means, but the following options in the `Other Neo4j system properties` section of `neo4j.conf` are working for me and do not produce any warnings in the logs on startup:
```
server.jvm.additional=-Djava.awt.headless=true
server.directories.data=/usr/local/var/neo4j/data
server.directories.logs=/usr/local/var/log/neo4j
```

The main issue appears to be the option ending in `.4` -- I am inferring that this was used to denote the v4 style options while those were supported in transition, and were eventually phased out in some recent update.

I also replaced the "dbms" prefix with "server" on the data and logs options based on the refs from @cho-m.

**Comment by nomasprime** [comment]
Just ran into this issue 🤷‍♂️

**Comment by rqi7** [comment]
Besides, neo4j@5.6 require java version=17. The dependent will automatically download dependent openjdk@19 which will raise a warning.
