### ISSUE TITLE
Tmux should use reattach-user-namespace by default

### ISSUE THREAD

**Issue by timothybasanov** [Homebrew/homebrew-core#12302]
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

On macOS 10.12 tmux is known to require a workaround to make pbcopy, pbpaste, ssh key agent and other things to work, see details here
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard (https://github.com/Homebrew/homebrew-core/blob/master/Formula/reattach-to-user-namespace.rb)

There are no plans to include this patch into tmux itself. To unbreak end-users by default we may want to make `tmux` package dependent on `reattach-to-user-namespace` package.

Proposed change:
 - make `tmux` package depend on `reattach-to-user-namespace` package
 - add `set-option -g default-command "reattach-to-user-namespace -l ${SHELL}"` to default tmux config file

Additional considerations:
 - there should be a separate cmd-line option `--without-reattach-to-user-namespace`
 - `byobu` package should be able to take advantage of this change

**Comment by tdsmith** [comment]
Thanks for the issue; this sounds like an annoying problem.

> There are no plans to include this patch into tmux itself.

Has anyone asked?

> default tmux config file

Is there a system tmux config file?

**Comment by timothybasanov** [comment]
> Has anyone asked?

I'm not an owner for any of the two, here is my summary: Reattach uses undocumented macOS API, which has already changed before. And some users may want increased security where tmux does not have access to a clipboard.
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard#patch-tmux

> Default tmux config file

I'm not completely sure, there is always a workaround when notes are printed after the script it done.
I know that tmux does load `~/.tmux.config`.
Byobu with tmux backend sources `~/.byobu/.tmux.config` (using `/usr/local/bin/byobu` and `/usr/local/share/byobu/profiles/tmuxrc`)

If you would guide me, I'll be happy to craft a pull request. I'm not sure how homebrew treats configuration files.

**Comment by timothybasanov** [comment]
A relevant tmux issue: https://github.com/tmux/tmux/issues/543

**Comment by ilovezfs** [comment]
This is not something we'll add to tmux ourselves because Homebrew's packaging guidelines do not permit feature patching. You'll have to negotiate this with upstream.
