### ISSUE TITLE
Problem with Installing OpenCV 3 with Python 3 bindings via HomebrewError: undefined local variable or method `buildpath' for #<Class:0x007fe1ac83ed58>

### ISSUE THREAD

**Issue by jhuh3226** [Homebrew/homebrew-core#12303]
- [ ] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

 I'm having problem with Installing OpenCV 3 with Python 3 bindings via Homebrew 
(referring link " http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/"). 
On commanding $ brew install opencv3 --with-contrib --with-python3 --HEAD, 
there always occurs this issue

> Error: undefined local variable or method `buildpath' for #<Class:0x007fd82601abe8>

Will there be any ways to solve the problem?

**Comment by ilovezfs** [comment]
`opencv3` is a homebrew/science formula, so you'll need to raise this there: https://github.com/Homebrew/homebrew-science/
