### ISSUE TITLE
[macos] [mojave-bottle] Can't install freetype formula, fall-through problem

### ISSUE THREAD

**Issue by palikao** [Homebrew/homebrew-core#123278]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Config:
'''
HOMEBREW_VERSION: 3.6.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: 932d2cf3b77c9439a57b6a43577fc8d3b6399a62
Last commit: 8 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a1924589b16a826fcb0d21cbe3eb2db946c9e7b0
Core tap last commit: 16 hours ago
Core tap branch: master
Core tap JSON: 14 Feb 18:25 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.TzJWvizaRI/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 11.0.0 build 1100
Git: 2.21.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1
'''

Doctor:
'''
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
'''
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install freetype formula or other formulas (es. fox, sumo-gui, gdal) that call freetype in its latests version

### What happened (include all command output)?

Hi,
I'm experiencing a problem in installing freetype (2.13) formula in homebrew.
I'm on macOS 10.14 (mojave), amd my homebrew version is updated.
Starting from brew '''install freetype''', this is the log..

'''
==> ./configure --prefix=/usr/local/Cellar/freetype/2.13.0 --enable-freetype-con
==> make
Last 15 lines from /Users/stefano/Library/Logs/Homebrew/freetype/02.make:
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/bdf -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/bdf/bdf.c  -fno-common -DPIC -o /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs/.libs/bdf.o
./builds/unix/libtool --mode=compile clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/sfnt -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/include  -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON   -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread -DFT_CONFIG_CONFIG_H="<ftconfig.h>" -DFT_CONFIG_MODULES_H="<ftmodule.h>" -DFT_CONFIG_OPTIONS_H="<ftoption.h>" -DFT2_BUILD_LIBRARY -o /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs/sfnt.lo /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/sfnt/sfnt.c
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/pcf -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/pcf/pcf.c -o /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs/pcf.o >/dev/null 2>&1
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/sfnt -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/sfnt/sfnt.c  -fno-common -DPIC -o /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs/.libs/sfnt.o
In file included from /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/sfnt/sfnt.c:21:
/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/sfnt/pngshim.c:411:7: error: expected expression
      FALL_THROUGH;
      ^
/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/include/freetype/internal/compiler-macros.h:46:27: note: expanded from macro 'FALL_THROUGH'
#    define FALL_THROUGH  __attribute__(( __fallthrough__ ))
                          ^
1 error generated.
make: *** [/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs/sfnt.lo] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile:  clang -pedantic -std=c99 -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/bdf -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs -I./builds/unix -I/private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/include -c -Wall -g -O2 -fvisibility=hidden -DDARWIN_NO_CARBON -I/usr/local/Cellar/libpng/1.6.39/include/libpng16 -pthread "-DFT_CONFIG_CONFIG_H=<ftconfig.h>" "-DFT_CONFIG_MODULES_H=<ftmodule.h>" "-DFT_CONFIG_OPTIONS_H=<ftoption.h>" -DFT2_BUILD_LIBRARY /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/src/bdf/bdf.c -o /private/tmp/freetype-20230213-27568-qv3qku/freetype-2.13.0/objs/bdf.o >/dev/null 2>&1
'''

I posted the same issue on freetype github, but they consider all ok, and asked to post the same here..

NB: I'm not a developer, I'm a simple user 

### What did you expect to happen?

Freetype installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Simply: brew install freetype (or any other formula with that dependency)
```

**Comment by carlocab** [comment]
Sorry, we don't provide support for versions of macOS older than Big Sur. See the output of `brew doctor` on your Mojave machine.
