### ISSUE TITLE
rpm2cpio doesn't work for new(ish) .rpms on macOS

### ISSUE THREAD

**Issue by cpick** [Homebrew/homebrew-core#123563]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs rpm2cpio
Error: No logs.
```

```
$ brew config
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 33 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1b00051c38850ea16a36abe51c8778174873171a
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 17 Feb 21:53 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

```
$ brew doctor
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/skhd.rb:26

Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the koekeishiya/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/koekeishiya/homebrew-formulae/yabai.rb:42

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to use `rpm2cpio` to extract a newer .rpm file [which are compressed with zstd](https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression) (as opposed to xz).  The extraction failed because it couldn't find the `zstd` binary (see "what happened" below).  This seems to be because the script [sets its $PATH](https://svnweb.freebsd.org/ports/head/archivers/rpm2cpio/files/rpm2cpio?view=markup#l5) to: `PATH=/bin:/usr/bin` which does not include "/usr/local/bin" for `zstd`:
```
$ which zstd
/usr/local/bin/zstd
```

When I modify `rpm2cpio` to include "`brew --prefix`/bin" in the $PATH it begins to work (see "what did you expect to happen" below).

*Additionally*, I believe the "rpm2cpio" formula needs a dependency on the "zstd" formula.  I already happened to have it installed as a dependency of "qemu".

### What happened (include all command output)?

The brew-installed version of `rpm2cpio` fails to extract a modern .rpm file:
```
$ curl -sSf https://dl.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/Packages/e/edk2-ovmf-20221117gitfff6d81270b5-13.fc37.noarch.rpm | rpm2cpio >/dev/null; echo $?
tar: Can't initialize filter; unable to run program "zstd -d -qq"
tar: Error exit delayed from previous errors.
1
```

### What did you expect to happen?

After copying and patching a local version of `rpm2cpio`:
```
$ diff /usr/local/bin/rpm2cpio ./rpm2cpio 
5c5
< PATH=/bin:/usr/bin
---
> PATH=/bin:/usr/bin:"$(brew --prefix)/bin"
```

That local version works:
```
$ curl -sSf https://dl.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/Packages/e/edk2-ovmf-20221117gitfff6d81270b5-13.fc37.noarch.rpm | ./rpm2cpio >/dev/null; echo $?
0
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install rpm2cpio zstd
$ curl -sSf https://dl.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/Packages/e/edk2-ovmf-20221117gitfff6d81270b5-13.fc37.noarch.rpm | rpm2cpio >/dev/null; echo $?
```
```

**Comment by fxcoudert** [comment]
Bug exists since 2015-12-17. The scripts has not been updated since then. Current head is on git: https://cgit.freebsd.org/ports/log/archivers/rpm2cpio/files/rpm2cpio

**Comment by iMichka** [comment]
Funny that this issue was opened today, I just opened this pull request to get the build / test fixed this morning: #123583

**Comment by iMichka** [comment]
Please reinstall the formula and try again

**Comment by iMichka** [comment]
Ping @cpick

**Comment by cpick** [comment]
Works great, thanks!
