### ISSUE TITLE
Nuget formula doesn't update ~.nuget/Nuget/Nuget.config

### ISSUE THREAD

**Issue by ThatNerdUKnow** [Homebrew/homebrew-core#123564]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17c872fb5275d87922a56416587cb439a5064354
Last commit: 33 hours ago
Core tap JSON: 17 Feb 22:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
❯ brew doctor
Your system is ready to brew.
❯ brew update
Already up-to-date.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to connect to a private Nuget package registry, but it seems that the Nuget.config in the default location ~.nuget/Nuget/Nuget.config isn't updated when I use `Nuget sources add`

### What happened (include all command output)?

Visual studio is unable to see my private package source

The Nuget.Config file in the default location doesn't seem to have changed after I aded the package source from the command line

Weirdly enough, If I try adding the package source again I get the following error:
```
❯ nuget sources Add -Name Artifactory -Source Redacted -username Redacted -password Redacted
The name specified has already been added to the list of available package sources. Provide a unique name.
❯ cd ~/.nuget/NuGet
❯ cat NuGet.Config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    </packageSources>
  <activePackageSource>
  </activePackageSource>
</configuration>
```

### What did you expect to happen?

I expected that Nuget would properly modify my global Nuget.Config file

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install nuget
nuget sources Add ...
```

**Comment by SMillerDev** [comment]
Did you try reporting this upstream? It doesn't seem related to anything brew could do here

**Comment by ThatNerdUKnow** [comment]
> Did you try reporting this upstream? It doesn't seem related to anything brew could do here

I'm not sure where to report to, The formula points to the Microsoft documentation for NuGet, but I don't believe that this formula was created by Microsoft as they make no mention of distributing the NuGet CLI via homebrew in their documentation, so I wasn't really sure where to open an issue, I apologize if this is the wrong place

**Comment by SMillerDev** [comment]
NuGet is just an open source project, anyone can package it.
