### ISSUE TITLE
Please provide a maven@3.8 formula version

### ISSUE THREAD

**Issue by DominiqueComte** [Homebrew/homebrew-core#123610]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
the Maven 3.9.0 release introduced breaking changes in plugins, by removing the previously provided plexus-utils.

from the release notes:
Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer. See MNG-6965.

But the formula only provides the latest version or unmaintained versions.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I just develop on Java using Maven builds.

My projects CI started showing build failures on Dependabot branches proposing the Maven 3.9.0 update.

Same issue locally or in CI servers.

### What happened (include all command output)?

just run "mvn compile" on a project using a plugin broken on v3.9.0

The failing output, for example with the editorconfig plugin (that plugin will get its own issue and PR):

[ERROR] Failed to execute goal org.ec4j.maven:editorconfig-maven-plugin:0.1.1:format (editorconfig-format) on project ******: Execution editorconfig-format of goal org.ec4j.maven:editorconfig-maven-plugin:0.1.1:format failed: A required class was missing while executing org.ec4j.maven:editorconfig-maven-plugin:0.1.1:format: org/codehaus/plexus/util/DirectoryScanner
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.ec4j.maven:editorconfig-maven-plugin:0.1.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/******/.m2/repository/org/ec4j/maven/editorconfig-maven-plugin/0.1.1/editorconfig-maven-plugin-0.1.1.jar
[ERROR] urls[1] = file:/******/.m2/repository/org/ec4j/linters/editorconfig-lint-api/0.2.1/editorconfig-lint-api-0.2.1.jar
[ERROR] urls[2] = file:/******/.m2/repository/org/ec4j/core/ec4j-core/0.2.1/ec4j-core-0.2.1.jar
[ERROR] urls[3] = file:/******/.m2/repository/org/ec4j/linters/editorconfig-linters/0.2.1/editorconfig-linters-0.2.1.jar
[ERROR] urls[4] = file:/******/.m2/repository/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.codehaus.plexus.util.DirectoryScanner

### What did you expect to happen?

a working Maven build.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
it is not directly related to brew, just too big a gap in the formula versions, the 3.8 version is not available, only latest or 3.5, and 3.5 cannot be installed.

% brew install maven@3.5
Error: maven@3.5 has been disabled because it is not maintained upstream!
% brew install maven    
Warning: maven 3.9.0 is already installed and up-to-date.
To reinstall 3.9.0, run:
  brew reinstall maven
```

**Comment by DominiqueComte** [comment]
I know the brew extract command, but it is much less practical than just having an alternate version available.

**Comment by carlocab** [comment]
Sorry, but this isn't something we're willing to do. See related discussion about a proposed `maven@3.6` at #86192, #79917, #74641, and others.

Please host this formula in your own tap instead.
