### ISSUE TITLE
Is anyone working on a formula update for pypy3 v5.7.1?

### ISSUE THREAD

**Issue by rw** [Homebrew/homebrew-core#12369]
https://morepypy.blogspot.fr/2017/04/pypy-571-bugfix-released.html

(Homebrew's version is currently v.5.5.0-alpha0, which is very out of date.)

**Comment by ilovezfs** [comment]
The last attempt to update it was here: https://github.com/Homebrew/homebrew-core/pull/11420

**Comment by ilovezfs** [comment]
Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by cclauss** [comment]
This is not brew problem, instead the problem is that [PyPy3.5 supports Linux 64bit only for now](http://doc.pypy.org/en/latest/release-v5.7.0.html).
