### ISSUE TITLE
Python 3.11 removal of gnu readline.

### ISSUE THREAD

**Issue by keeely** [Homebrew/homebrew-core#123842]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
It seems the developers have removed gnu readline from Homebrew python.  I can understand the desire to avoid gnu software in general, but this shouldn't be done where it breaks people.  You surely need feature parity before making this switch?
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Execute python3 readline.read_history_file()

### What happened (include all command output)?

    readline.read_history_file("history_file")
       OSError: [Errno 22] Invalid argument

### What did you expect to happen?

My program to work normally, reading the history file.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python3 (install latest version)
brew link python3
```

**Comment by Bo98** [comment]
Cannot reproduce:

```
readline.read_history_file(Path.home() / ".python_history")
```

I'm guessing the file you are trying is corrupt or something. There is insufficient information here.

You failed to even provide a `brew config` so I don't even know which macOS you are using.

**Comment by keeely** [comment]
Ah, for some reason I missed that:
$ brew config
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 20 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4e34bc1667e076b8dfea00c5974e104947abacc5
Core tap last commit: 71 minutes ago
Core tap branch: master
Core tap JSON: 21 Feb 13:16 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.6NtF82E6Xe/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2

**Comment by keeely** [comment]
I believe you must create the history file with gnu readline using write_history_file() , and try to read it with read_history_file() in the new readline.

**Comment by keeely** [comment]
I think effectively the change is forced on people, because most will just upgrade their version of Python as a matter of routine and think nothing of the bump from 3.10 -> 3.11.  I certainly do.

My answer to the Apple/Homebrew compatibility issues was to simply check the readline type, and on finding libedit give a warning to my users that they should use Homebrew instead of Apple's Python, and refuse to run otherwise.  Since most users have some Homebrew stuff on their Macs, this wasn't too big a deal, and insulated them from MacOs updates to some extent.

The easiest solution for me going forward is to pull gnureadline into my project, unless I want to work through the compatibility issues on upgrade (which I don't fancy).

**Comment by keeely** [comment]
Oh dear.  Using gnureadline does not appear to be a drop-in replacement for the readline previously found in Homebrew python 3.10.  Tab completion in cmd doesn't appear to work properly. 
https://docs.python.org/3/library/cmd.html

**Comment by keeely** [comment]
I raised a Python bug here:
https://github.com/python/cpython/issues/102130
I think this is perhaps a failing of the cmd.py module, however I don't know if the Python devs will see it that way.
