### ISSUE TITLE
New Go build flags not working with the brew distributed version

### ISSUE THREAD

**Issue by sideninja** [Homebrew/homebrew-core#123885]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
We've added a new build flag in order to build a new version of our Flow CLI https://github.com/onflow/flow-cli but it seems that the version distributed through homebrew doesn't include those flags. Not sure why, but we could normally run binaries downloaded directly from Github release. I would appreciate any help.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install latest version.

### What happened (include all command output)?

////

### What did you expect to happen?

////

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
///
```

**Comment by Bo98** [comment]
You've provided little to no information here to work with. If something's wrong with the build, it's probably upstream's Makefile given we just run that.

**Comment by sideninja** [comment]
You are right! my bad

**Comment by sideninja** [comment]
@Bo98 just one last thing, is it anyway possible to use the Github secrets we use for building the binaries in CD somehow with homebrew and makefile?
