### ISSUE TITLE
VICE 3.x should move to SDL2 (Cocoa GUI is broken & deprecated by upstream)

### ISSUE THREAD

**Issue by daniel-jozsef** [Homebrew/homebrew-core#12426]
I see VICE is still being built using the Cocoa UI. Maintainers have made it clear that the Cocoa GUI has not been maintained since the 2.4 release.

from http://vice-emu.sourceforge.net/macosx.html
> 64bit Binary for Intel Mac OS X >= 10.12: vice-macosx-cocoa-x86_64-10.12-3.1.dmg
> please be aware that the Cocoa UI is lagging behind compared to the SDL version, it is recommended to use the SDL download.

from the lemon64.com forums:
> Compyx wrote:
> We don't have an OSX maintainer, and since Apple seems to break its API with every release I'm surprised we even have an OSX binary. The Cocoa port is broken. 
> So the Cocoa port is a dead end. SDL2 should work on OSX though, might not look fancy, but it's complete (ie all options are accessible through the UI, unllike Cocoa) and works

So to make VICE 3.x actually usable, we need to change the formula to build the SDL2 gui instead of the Cocoa one.

**Comment by DomT4** [comment]
FWIW, taking a brief look locally I couldn't get the latest release to compile against `sdl2`. It just blew up consistently on one of the last `make` stages.
