### ISSUE TITLE
PostgreSQL Locale issue

### ISSUE THREAD

**Issue by cheleb** [Homebrew/homebrew-core#124215]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> $ brew config
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aa410805836c56bfebd2d856eab60a1ef9f0c886
Core tap last commit: 9 days ago
Core tap branch: master
Core tap JSON: 25 Feb 13:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.1
Rosetta 2: false

> $ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Start postgreql

### What happened (include all command output)?

Server failed to start:

2023-02-25 14:24:47.763 CET [42262] LOG:  starting PostgreSQL 15.2 (Homebrew) on aarch64-apple-darwin22.3.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit
2023-02-25 14:24:47.764 CET [42262] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-02-25 14:24:47.764 CET [42262] LOG:  listening on IPv6 address "::1", port 5432
2023-02-25 14:24:47.765 CET [42262] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-02-25 14:24:47.766 CET [42262] FATAL:  postmaster became multithreaded during startup
2023-02-25 14:24:47.766 CET [42262] **HINT:  Set the LC_ALL environment variable to a valid locale.**
2023-02-25 14:24:47.766 CET [42262] LOG:  database system is shut down

### What did you expect to happen?

Service to start :-/ 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew services start postgresql@15
tail -f /opt/homebrew/var/log/postgresql@15.log

BTW, just adding as explained is the output log the locale solved the issue:

        <key>EnvironmentVariables</key>
         <dict>
          <key>LC_ALL</key>
           <string>en_US.UTF-8</string>
         </dict>

In 
/opt/homebrew/Cellar/postgresql@15/15.2_1/homebrew.mxcl.postgresql@15.plist

I liked to provide a patch, but no idea what is the locale to choose !
```

**Comment by SMillerDev** [comment]
Could be that https://github.com/Homebrew/homebrew-core/pull/124135 caused this

**Comment by walro** [comment]
> Could be that #124135 caused this

Yeah, most likely the ` --enable-nls` part. From [PostgreSQL locale docs](https://www.postgresql.org/docs/15/locale.html)

> To enable messages to be translated to the user's preferred language, NLS must have been selected at build time (configure --enable-nls). 

I suppose that adds a requirement to `LC_*` to be set. FWIW it seems to work (instead of tampering with the formula) to run `launchctl setenv LC_ALL en_US.UTF-8` but that's not really a solution either.

**Comment by lehni** [comment]
Instructions to downgrade back to postgresql@15.2.0 for the time being. Sadly there's no elegant way to do so, but this did the job:

```sh
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/1ab4aae8080ae30a8fb18907f6604ff4178214a2/Formula/postgresql%4015.rb
brew reinstall postgresql@15.rb
rm postgresql@15.rb
brew services restart postgresql@15
```

https://github.com/PostgresApp/PostgresApp/issues/656#issuecomment-1445057492
