### ISSUE TITLE
Unable to produce a static library for libsndfile

### ISSUE THREAD

**Issue by jlgiavitto** [Homebrew/homebrew-core#124310]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
-----------------
brew config
-----------------

HOMEBREW_VERSION: 4.0.3-158-g06cf85f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 06cf85ffd4769fd961d8e70f4798ea4cde57325c
Last commit: 14 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 369d38a2dd04607af4199bd3cc87ef5db86fb881
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 27 Feb 11:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4LSuIhezqs/org.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-arm64
CLT: 14.1.0.0.1.1666437224
Xcode: 14.2
Rosetta 2: false

-----------------
brew doctor 
-----------------

Your system is ready to brew.


-----------------
the local version of the formula libsndfile, as viewed with 'brew edit libsndfile'
----------------

class Libsndfile < Formula
  desc "C library for files containing sampled sound"
  homepage "https://libsndfile.github.io/libsndfile/"
  url "https://github.com/libsndfile/libsndfile/releases/download/1.2.0/libsndfile-1.2.0.tar.xz"
  sha256 "0e30e7072f83dc84863e2e55f299175c7e04a5902ae79cfb99d4249ee8f6d60a"
  license "LGPL-2.1-or-later"

  livecheck do
    url :stable
    strategy :github_latest
  end

  bottle do
    sha256 cellar: :any,                 arm64_ventura:  "613bc9b6aa39f97f5b96f8fde4eb326d86b84eefe834bb4390525a27394920ee"
    sha256 cellar: :any,                 arm64_monterey: "3a684c2f61724acd97267aa7663871debf68cfa90e5c16205add3e4a3ecbdbc2"
    sha256 cellar: :any,                 arm64_big_sur:  "b1d790d532e030e237f8a2cc107d7f89bb9770777dcb3b539f2d25dbe8ca375d"
    sha256 cellar: :any,                 ventura:        "006bfec19f53d52e3fc5124368e28047e4dc93d4eeadd5c279214cbe0bb8f45f"
    sha256 cellar: :any,                 monterey:       "1f7d0cd31198a65141994868ff9fb38a9b6461e9ab0de5101df721ebb39e8b6e"
    sha256 cellar: :any,                 big_sur:        "df6c7be8e1ed21ba93dbd54a5ebcafe52240427cc3db497755d45222341128b3"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "999459d04493b8d24126025e3b954d0172bd89b38cbb92072a4ce993ce320d68"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "libtool" => :build
  depends_on "pkg-config" => :build
  depends_on "flac"
  depends_on "lame"
  depends_on "libogg"
  depends_on "libvorbis"
  depends_on "mpg123"
  depends_on "opus"

  uses_from_macos "python" => :build

  def install
    system "autoreconf", "-fvi"
    system "./configure", "-enable-static", "--enable-static-build", *std_configure_args
    system "make", "install"
  end

  test do
    output = shell_output("#{bin}/sndfile-info #{test_fixtures("test.wav")}")
    assert_match "Duration    : 00:00:00.064", output
  end
end
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to generate the static version of libsndfile on Apple Silicon. 

The static version was implicitly generated in the past. 
At some point it was not. 
So I added the flag "--enable-static" to the formula and used "brew reinstall libsndfile --build-from-source". 
It worked for some months. 
[libsndfile.rb.zip](https://github.com/Homebrew/homebrew-core/files/10839447/libsndfile.rb.zip)

Now, it does not work anymore. 
I suspect that there was a change in the build procedure, going from ./configure + make to cmake (the source of libsndfile support the two).

Note that I am able to produce the static lib from the source, by hands, using the configure+cmake approach.

### What happened (include all command output)?

The command work fine and the dynamic libs are installed. But not the static lib. 

### What did you expect to happen?

I expect the installation of static lib. If for some reason this is not anymore the default intended, I expact that 'brew reinstall libsndfile --build-from-source' will install the static lib provided that "--enable-static" is configured in teh formula (see the altered formula given in the first field after the output of 'brew doctor'

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew edit libsndfile

# add the '--enable static' flag to the line 'system "./configure", *std_configure_args'
# so we have 'system "./configure", "-enable-static", *std_configure_args'

brew reinstall libsndfile --build-from-source
```

**Comment by SMillerDev** [comment]
Not being able to edit a formula is not a bug in brew.

**Comment by jlgiavitto** [comment]
Hello Sean Molenaar. 
I am able to edit the formula. The problem is that the formula is not able to produce a static library as it did. I don't know if this is considered as a bug. 
Best,
Jl.

**Comment by gromgit** [comment]
Try `HOMEBREW_NO_INSTALL_FROM_API=1 brew reinstall libsndfile --build-from-source`

**Comment by jlgiavitto** [comment]
It works. Thank you very much.
