### ISSUE TITLE
OpenJDK crashes on macOS 13.3 Beta (22E5219e)

### ISSUE THREAD

**Issue by henryhchchc** [Homebrew/homebrew-core#124306]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba6d87eed9ce31f42fa2b33a4e6067d9cf17f13f
Last commit: 7 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: acb965a9e5df1c6782cb4b6ccecc0b28873b5ba6
Core tap last commit: 9 minutes ago
Core tap branch: master
Core tap JSON: 27 Feb 09:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `java` installed with `brew install openjdk`

### What happened (include all command output)?

It crashes. The output was

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0xa) at pc=0x000000010167ef38, pid=88544, tid=8707
#
# JRE version:  (19.0.2) (build )
# Java VM: OpenJDK 64-Bit Server VM (19.0.2, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# V  [libjvm.dylib+0x3baf38]  CodeHeap::allocate(unsigned long)+0x1c0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/henry/hs_err_pid88544.log
#
#
zsh: abort      java
```

### What did you expect to happen?

It runs without crashes.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
On macOS 13.3 Beta (22E5219e)

brew install openjdk
java
```

**Comment by henryhchchc** [comment]
FIY that Zulu JDK does no crash on the above mentioned OS version.

**Comment by carlocab** [comment]
Thanks for the report. Can you try getting a backtrace from `lldb`?

**Comment by cho-m** [comment]
Also there should be more info in `/Users/henry/hs_err_pid88544.log` as mentioned in output. I think that should have a stack trace, environment info, etc. used for debugging crash.

There isn't enough info to figure out what is going wrong.

**Comment by henryhchchc** [comment]
> Also there should be more info in `/Users/henry/hs_err_pid88544.log` as mentioned in output. I think that should have a stack trace, environment info, etc. used for debugging crash.
> 
> There isn't enough info to figure out what is going wrong.

The log file is available at https://gist.github.com/henryhchchc/cd22be7509eb6e4f2750b0f20d330950

**Comment by henryhchchc** [comment]
> Thanks for the report. Can you try getting a backtrace from `lldb`?

```
$ lldb /Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/bin/java
(lldb) target create "/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/bin/java"
Current executable set to '/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/bin/java' (arm64).
(lldb) run
Process 2555 launched: '/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/bin/java' (arm64)
Process 2555 stopped
* thread #3, stop reason = signal SIGBUS
    frame #0: 0x00000001032daf38 libjvm.dylib`CodeHeap::allocate(unsigned long) + 448
libjvm.dylib`CodeHeap::allocate:
->  0x1032daf38 <+448>: str    x20, [x21]
    0x1032daf3c <+452>: mov    w8, #0x1
    0x1032daf40 <+456>: strb   w8, [x21, #0x8]
    0x1032daf44 <+460>: ldr    x8, [x19, #0x108]
Target 0: (java) stopped.
(lldb) 
```

**Comment by dkocher** [comment]
For what it's worth, we have observed this very same crash in our applications that load the runtime using [JLI_Launch](https://github.com/openjdk/jdk17u/blob/9b054a1fafe546495dd209fa927b56ecb3bbc1ca/src/java.base/share/native/libjli/java.c#L227). In our case this affects the Eclipse Temurin build [17.0.6+10](https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.6%2B10) 

The only specific we have found so fare is that it can only reproduced when the launcher binary has been compiled with the Xcode 14.2 toolchain whereas the same build works just fine when built with the Xcode 13.4.1 toolchain.

**Comment by henryhchchc** [comment]
Seems like it is no longer crashing on macOS 13.3 Beta 3 (22E5236f)

**Comment by dkocher** [comment]
A user that could reproduce the crash also reports this to be resolved with build 22E5236f.

**Comment by iMichka** [comment]
So all good then? Can we close this issue if it is solved with a newer macOS build?

**Comment by henryhchchc** [comment]
Sure

**Comment by iMichka** [comment]
I'm not sure we have enough bandwidth to debug issues on macOS beta versions. Also, this sounds like a moving target right now.

**Comment by Bo98** [comment]
> 22E7752300g

This is older than 22E5236f so please update your macOS.

**Comment by rfhickey** [comment]
@henryhchchc I am still getting this exact error with Ventura 13.3 (22E252) and an M1 chip. Tried a bunch of ARM64 JDKs.

Was there anything else done to solve this?

**Comment by henryhchchc** [comment]
> @henryhchchc I am still getting this exact error with Ventura 13.3 (22E252) and an M1 chip. Tried a bunch of ARM64 JDKs.
> 
> 
> 
> Was there anything else done to solve this?

I didn't. I upgraded macOS and everything worked.
