### ISSUE TITLE
Gnuplot wrong SHA256 checksum for source download

### ISSUE THREAD

**Issue by messju** [Homebrew/homebrew-core#124442]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4d0154fa7926e8a7b06e9b074dd45957e820407c
Last commit: 30 hours ago
Core tap JSON: 28 Feb 18:40 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to build Gnuplot from source.

### What happened (include all command output)?

```
Error: gnuplot: SHA256 mismatch
Expected: bef7b9618079c724f19d3b0e1d7830b5b407a56b303f2b9e3690a4ce8ce0a89c
  Actual: 02fc27918200ed64d8f0c3b84fe81b95b59cd47ad99f270939ae497c19f27419
    File: /Users/automan/Library/Caches/Homebrew/downloads/2428e4213af5ffc515c48c06e61a514cd4a084a23e5ca48249953fbb5419f7bf--gnuplot-5.4.6.tar.gz
To retry an incomplete download, remove the file above.
```

### What did you expect to happen?

I expect that the download finishes and gets verified successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run `brew install --build-from-source gnuplot` to get the above error.
```

**Comment by SMillerDev** [comment]
Yeah, seems like upstream changed the source so someone will have to ask them if it was intentional or if their systems have been compromised

**Comment by johnsonjh** [comment]
@SMillerDev Has the upstream been contacted?

**Comment by carlocab** [comment]
It doesn't look like it.

**Comment by SMillerDev** [comment]
Not by me

**Comment by johnsonjh** [comment]
I've just sent a message to the maintainer.

**Comment by johnsonjh** [comment]
Also, I opened a bug report at https://sourceforge.net/p/gnuplot/bugs/2602

**Comment by carlocab** [comment]
Thanks, @johnsonjh.

**Comment by johnsonjh** [comment]
I see you beat me to it, thanks @ZhongRuoyu

**Comment by ZhongRuoyu** [comment]
No problem. Thanks for your upstream report, @johnsonjh.
