### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by REPTILEHAUS** [Homebrew/homebrew-core#12450]
I know that this keeps coming up but I still cant seem to find a fix for this. Im not a Python master by any sense but anytime I try to run scripts which have to use ssl protocol I come across this on my macbook (which has openssl and python installed from brew) which means I tend to not write as much python as probably should be as its my primary dev machine.

Would be eternally grateful for a fix for this or telling me how to solve it.

```
brew info python
python: stable 2.7.13 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org
/usr/local/Cellar/python/2.7.13 (6,336 files, 86.7MB) *
  Built from source on 2017-04-15 at 04:53:15
```

```
python -c 'import ssl; print ssl.OPENSSL_VERSION'
OpenSSL 1.0.2d 9 Jul 2015
```

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by MikeMcQuaid** [comment]
Also, even without the issue template: I have no idea what the issue is you're facing so have to assume it's unrelated to Homebrew.

**Comment by REPTILEHAUS** [comment]
Sure, but I spent most of the night reading various issues about it and apparently it is related to homebrew and the fact that homebrew openssl doesn't use apples native keychain or homebrew openssl is not trusted by apples keychain process or something to that effect.. 

I worked around it anyway by prepending the script execution with:

```
SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem  python whatever-the-args-are
```
