### ISSUE TITLE
Some workflows are taking longer to complete

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/homebrew-core#124619]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I've checked all of our workflows and their run time after introduction of HOMEBREW_INSTALL_FROM_API to the wide public and the following workflows:

- https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/autopublish.yml
- https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/publish-commit-bottles.yml
- https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/remove-disabled-formulae.yml
- https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/scheduled.yml

are spending too much time at the step of "Setting Up Homebrew", which could be tracked down to the fact that recent GitHub Actions' runner Ubuntu images are no longer containing a full clone of homebrew-core.

### What happened (include all command output)?

We waste ~4 minutes on every workflow run just to make a full clone of homebrew-core.

### What did you expect to happen?

Workflow runs to be quicker.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Look at `Actions` tab in this repo, navigate to (listed above) workflows, see the run times.
```

**Comment by dawidd6** [comment]
I've created this issue to gather some thoughts on the subject and work on the best solution on how to reduce the run time of our affected workflows.

My take on this: run those workflows in container where we are guaranteed to always how most up-to-date core tap available in place. Disadvantage: no `skopeo` in container image :disappointed:. Would need to somehow work this around.

**Comment by carlocab** [comment]
I've noticed this issue too.

> My take on this: run those workflows in container where we are guaranteed to always have most up-to-date core tap available in place. 

This was my thought as well, but I wasn't sure if it would make things faster.

> Disadvantage: no `skopeo` in container image :disappointed:. Would need to somehow work this around.

We should add `skopeo` to our container. Or install it where needed.

**Comment by SMillerDev** [comment]
Would a shallow clone work now that there's less traffic?

**Comment by carlocab** [comment]
> Cloning the core tap takes ~4 minutes. Pulling the image takes ~30 seconds. I think it would make things faster a bit 😄.

Cool, we can try that then. Maybe we can do something like this for our bottle upload jobs? #112134

> Would a shallow clone work now that there's less traffic?

`git push` is probably still pretty expensive from a shallow clone. Not sure though.

**Comment by Bo98** [comment]
Note that this issue does not affect the macOS images.

GitHub have opted to keep Homebrew/core tapped on macOS. Thus will not happen on Ubuntu as they consider Homebrew on Linux deprecated after 3.6.0.

**Comment by dawidd6** [comment]
Alright, so looks like we are done with the bottle publishing workflow. It takes ~2 minutes now to complete. 3 other workflows to go.

**Comment by dawidd6** [comment]
The dispatch workflow for bottle building+uploading is also affected I think, specifically the upload job at the end.

**Comment by dawidd6** [comment]
![image](https://user-images.githubusercontent.com/9713907/222745270-5eab96f3-5f58-4ff4-9dad-d57e9d667768.png)

:tada:

**Comment by carlocab** [comment]
The `tap syntax` job in Homebrew/brew could probably use this treatment as well.

**Comment by ZhongRuoyu** [comment]
Since https://github.com/Homebrew/homebrew-core/pull/124626 was merged there have been a notable number of ["Publish and commit bottles"](https://github.com/Homebrew/homebrew-core/actions/workflows/publish-commit-bottles.yml) failures with the following error message:

`time="2023-03-02T15:09:45Z" level=fatal msg="writing blob: Patch \"[https://ghcr.io/v2/homebrew/core/miller/blobs/upload/9f26cc9e-e5ea-47ca-9c50-1eabbf3200c1\](https://ghcr.io/v2/homebrew/core/miller/blobs/upload/9f26cc9e-e5ea-47ca-9c50-1eabbf3200c1/)": read tcp 172.18.0.2:58072->140.82.112.33:443: read: connection reset by peer"`

Any idea what's going on here?

**Comment by dawidd6** [comment]
Looks like some unrelated network issues for me.
