### ISSUE TITLE
Help with pull requests management in homebrew-php

### ISSUE THREAD

**Issue by javian** [Homebrew/homebrew-core#1247]
The individual that usually manages the pull requests in the homebrew-php repo has been away for a little while and I wanted to start merging some of the pull requests in the repo. There's no documentation (that I can find) on how to work with the pull requests to get the merged together with the bottles for the formulas. Can you share the workflow for how to manage this ? I'm assuming it is the same for core.

**Comment by javian** [comment]
I was given some more information in the php tap https://github.com/Homebrew/homebrew-php/issues/3081 but the only answer I'm lacking is if some kind of permission is required to post the bottles to bintray or not.

**Comment by javian** [comment]
The api requires authentication `Security: When publishing a version, authenticated user with 'publish' permission, or version read/write entitlement.` - so the question then would be who can grant that to homebrew-php on bintray ?

**Comment by DomT4** [comment]
Cross-post so I don't forget I actually replied to this in the other thread: https://github.com/Homebrew/homebrew-php/issues/3081#issuecomment-219872672

**Comment by mikemcquaid** [comment]
You have permissions now. These docs are probably also worth reading/linking for homebrew-php maintainers: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Maintainer-Guidelines.md https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Maintainers-Avoiding-Burnout.md https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/New-Maintainer-Checklist.md

**Comment by javian** [comment]
Thanks @mikemcquaid ! I'll go through the documentation as soon as I can.
