### ISSUE TITLE
id3v2 man page packaging issue

### ISSUE THREAD

**Issue by monochromec** [Homebrew/homebrew-core#124845]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
man page of this formula contains escape sequences instead of groff markup.

Please find the correct file contents at https://github.com/myers/id3v2/blob/main/id3v2.1.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

man id3v2

### What happened (include all command output)?

```

ID3V2(1)                         User Command                         ID3V2(1)



?[1mNAME?[0m
       id3v2  -   Adds/Modifies/Removes/Views id3v2 tags, converts/lists id3v1
       tags

?[1mSYNOPSIS?[0m
       ?[1mid3v2 ?[22m[ ?[4mOPTION?[24m ] [ ?[4mFILE?[24m ]

?[1mOPTIONS?[0m
       ?[1m-h, --help?[0m
              Display help and exit

       ?[1m-f, --list-frames?[0m
              Display all possible frames for id3v2

       ?[1m-L, --list-genres?[0m
              Lists all id3v1 genres

       ?[1m-v, --version?[0m
              Display version information and exit

       ?[1m-l, --list?[0m
              Lists the tag(s) on the file(s)

       ?[1m-R, --list-rfc822?[0m
              Lists using an rfc822-style format for output

       ?[1m-d, --delete-v2?[0m
              Deletes id3v2 tags

       ?[1m-s, --delete-v1?[0m
              Deletes id3v1 tags

       ?[1m-D, --delete-all?[0m
               Deletes both id3v1 and id3v2 tags

       ?[1m-C, --convert?[0m
               Converts id3v1 tag to id3v2
```

### What did you expect to happen?

Correctly formatted man page.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) brew install id3v2
2) man id3v2
```

**Comment by fxcoudert** [comment]
We simply run `make install`. The man page is built from upstream makefile with:

```
install: all
	install -c -s id3v2 ${PREFIX}/bin/id3v2
	nroff -man id3v2.1 > ${PREFIX}/share/man/man1/id3v2.1
```

So this is an upstream issue.

**Comment by monochromec** [comment]
Upstream man page checks out, cf. link. I just ran the raw blob file as linked above against an nroff installed on a Bullseye instance => works. Also did the same with a groff I just installed on a Ventura M1 running homebrew => works as well.

Glitch when packaging the formula?

**Comment by fxcoudert** [comment]
If you reinstall within Homebrew from source, with `brew reinstall -s id3v2` does the manpage work?

**Comment by monochromec** [comment]
No, still same issue.

**Comment by fxcoudert** [comment]
The `id3v2.1` file originally in the source is a valid man page:

```
$ head id3v2.1 
.TH ID3V2 1 "May 2000" "" "User Command"
.SH NAME
id3v2 \-  Adds/Modifies/Removes/Views id3v2 tags, converts/lists id3v1 tags
.SH SYNOPSIS
.B id3v2
.RB [
.I OPTION
.RB ]
...
.RB [
```

I don't know why, but the makefile then runs
```nroff -man id3v2.1 > /opt/homebrew/Cellar/id3v2/0.1.12/share/man/man1/id3v2.1```
which produces an ASCII file with escape sequences for color and bold. This is not a man page. Upstream should simply install their man page.

**Comment by fxcoudert** [comment]
Last upstream activity is from 2010-03-26 so clearly abandoned project.
