### ISSUE TITLE
openssh fails to establish a connection: profile not found

### ISSUE THREAD

**Issue by irundaia** [Homebrew/homebrew-core#12488]
I've recently upgraded openssh, and now I can no longer connect to my server. I think this issue is similar/identical to [this issue](https://github.com/Homebrew/homebrew-dupes/issues/641). 

I'd like to help but unfortunately, I don't have enough knowledge of the homebrew to fix this issue myself.

Below I've included a log in which I attempted to connect to my server exactly once. I hope this helps!

> sudo /usr/local/sbin/sshd -D -d
debug1: sshd version OpenSSH_7.5, OpenSSL 1.0.2k  26 Jan 2017
debug1: private host key #0: ssh-rsa <omitted>
debug1: private host key #1: ssh-dss <omitted>
debug1: private host key #2: ecdsa-sha2-nistp256 <omitted>
debug1: private host key #3: ssh-ed25519 <omitted>
debug1: rexec_argv[0]='/usr/local/sbin/sshd'
debug1: rexec_argv[1]='-D'
debug1: rexec_argv[2]='-d'
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: fd 6 clearing O_NONBLOCK
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 6 out 6 newsock 6 pipe -1 sock 9
debug1: inetd sockets after dupping: 5, 5
Connection from 89.99.198.124 port 53128 on 192.168.0.10 port 22
debug1: Client protocol version 2.0; client software version OpenSSH_7.5
debug1: match: OpenSSH_7.5 pat OpenSSH* compat 0x04000000
debug1: Local version string SSH-2.0-OpenSSH_7.5
debug1: Enabling compatibility mode for protocol 2.0
ssh_sandbox_child: sandbox_init: @PREFIX@/share/openssh/org.openssh.sshd.sb: profile not found [preauth]
debug1: do_cleanup [preauth]
debug1: monitor_read_log: child log fd closed
debug1: do_cleanup
debug1: Killing privsep child 79361

**Comment by dunn** [comment]
A workaround until that issue is resolved would be to build OpenSSH from source: `brew reinstall -s openssh`

**Comment by irundaia** [comment]
Thanks guys, it works again!
