### ISSUE TITLE
Python 2 builds with UCS2, add UCS4 option

### ISSUE THREAD

**Issue by tony** [Homebrew/homebrew-core#12510]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)

  The project [cihai](https://cihai.git-pull.com) I'm developing on a local machine, macOS Sierra with python 2 brew, will fail because the distribution builds with UCS2.
- What happened (include command output)

   ``unichr`` commands will unicode characters will encounter out of range errors:

```python
self = <test_datasets.BootstrapUnicode testMethod=test_generate_unicode>

    def test_generate_unicode(self):
        from cihai import conversion

        totalCharacters = 0
        for block_name, urange in cjk_ranges.items():
            for c in urange:
>               char = unichr(int(c))
E               ValueError: unichr() arg not in range(0x10000) (narrow Python build)

tests/test_datasets.py:59: ValueError
```
- What you expected to happen

   Python 2.7 should have the option to build with UCS4 (just as travis-ci's 2.7 does).

   It is a standard flag in python 2.7's build system.
- Step-by-step reproduction instructions (by running `brew install` commands)

  Install python 2 via homebrew: `$ brew install python`

```python
$ /usr/local/bin/python

>>> import sys
>>> sys.maxunicode > 0xffff
False
```

```sh
❯ brew --version
Homebrew 1.1.12
Homebrew/homebrew-core (git revision c2146; last commit 2017-04-16)
```

The flag on python 2.7 will be ``--enable-unicode[=ucs[24]]``, so adding the flag `` --enable-unicode=ucs4`` will enable UCS4 range characters. The current default (if nothing specified) will be ``ucs2``.

Despite the default build of cpython being UCS2, it is standard practice for Linux distributions which package Python 2.7 to *have unicode UCS4 turned on*.

This *does not* apply to python 3.3+, as the character range and distinction no longer exists.

I think the default python 2 package should have a flag added to enable a build with UCS4.

**Comment by tony** [comment]
I looked closer at the [formula for python](https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb):

>  # Please don't add a wide/ucs4 option as it won't be accepted.
>  # More details in: https://github.com/Homebrew/homebrew/pull/32368

It's difficult to `git-blame` it due to a bot and the history being so big, but I've reread the issue.

https://github.com/Homebrew/legacy-homebrew/pull/32368

It's been about 3 years since this issue was made.

As of 2017, even macOS Sierra's python ships narrow (UCS2).

> You might consider maintaining this yourself outside of Homebrew core, though; with the tap mechanism, you just stick a formula (say, wide-python.rb) in a Github repository, name it e.g. bukzor/homebrew-wide-python, and then "brew tap bukzor/wide-python; brew install wide-pytho

This flag is in default cpython though.

> The UCS-4 build breaks binary everything. Happily, it breaks things obviously; things just won't import, failing on ImportError exceptions, complaining about a lack of UCS2 symbols. The wxpython bottle and binary wheels from PyPI (I tested numpy, Pillow, and shapely) break identically.
>
> I think I'm 👎 here. It's good that things are obviously broken but things are still broken. "pip install Pillow" happily installs a version of Pillow that won't import, without any hints that you need "--no-use-wheel". For Homebrew bottles, we would need to add code to detect Python width and refuse to pour.

from https://github.com/Homebrew/legacy-homebrew/pull/32368#issuecomment-56260783

I haven't confirmed if that's true in 2017, but if other bottles would require logic, rather than it just being a flag to add. 

And since homebrew targets macOS, and the default python 2.7 is narrow (built with the default UCS2), I'm learning toward not wanting to touch out of the effort.

That said, it has been about 3 years since then, is there anything maintainers who are familiar with the core know that'd be different from the thread at https://github.com/Homebrew/legacy-homebrew/pull/32368#issuecomment-56260783?

**Comment by sanscore** [comment]
I've had issues with building between UCS2 and UCS4. I don't understand why one would prefer UCS2 over UCS4 other than history which is grasping at straws. PEP 261 was in 2001, part of Python 2.2, so one would expect people to be up to speed by now..., however, this is the Python community we are talking about. So... 

The biggest problem with switching over will be getting every user to wipe out their `pip` cache. Although, it wouldn't be the worst idea to remove the wheel cache  (`rm -rf ~/Library/Caches/pip/wheel/`) each time one rebuilds python.

**Comment by tony** [comment]
> The biggest problem with switching over will be getting every user to wipe out their pip cache. Although, it wouldn't be the worst idea to remove the wheel cache (rm -rf ~/Library/Caches/pip/wheel/) each time one rebuilds python.

Aside from that, what about bottle / formula complexities that could be introduced by adding support for UCS4? Is there any tooling in brew that makes the labor/effort required different than it was 4 years ago?

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for thoughts here.

**Comment by MikeMcQuaid** [comment]
> And since homebrew targets macOS, and the default python 2.7 is narrow (built with the default UCS2), I'm learning toward not wanting to touch out of the effort.

This sounds like a good idea.

**Comment by tdsmith** [comment]
Nothing has changed; narrow builds are still what the ecosystem expects for 2.7 on OS X and Windows and that will almost certainly be true until EOL. You should use Python 3 if you don't want to worry about this. :)
