### ISSUE TITLE
libosinfo, logrotate, tmpwatch, xmlto: url change

### ISSUE THREAD

**Issue by kyungminlee** [Homebrew/homebrew-core#12513]
`fedorahosted.org` has retired, and the Formulae `libosinfo`, `logrotate`, `tmpwatch`, and `xmlto` need to be updated to new urls

https://libosinfo.org
https://gitlab.com/libosinfo/libosinfo/repository/archive.tar.gz?ref=v1.0.0

https://github.com/logrotate/logrotate
https://github.com/logrotate/logrotate/archive/r3-9-1.tar.gz

https://pagure.io/tmpwatch
https://releases.pagure.org/tmpwatch/tmpwatch-2.11.tar.bz2

https://pagure.io/xmlto
https://releases.pagure.org/xmlto/xmlto-0.0.28.tar.bz2

**Comment by bfontaine** [comment]
Could you please make a pull-request for each one? Thanks! 😃

**Comment by tschoonj** [comment]
I took care of `libosinfo` in #13346

**Comment by kyungminlee** [comment]
https://github.com/Homebrew/homebrew-core/commit/f0ad81b6e3c05f89466f3cfbee32653156873fe4 fixes `tmpwatch`

**Comment by kyungminlee** [comment]
fda2a3df07109cf842bb9dba5fd7142a3feb91c4 fixes `xmlto`
