### ISSUE TITLE
NetPGP formula request/discussion

### ISSUE THREAD

**Issue by RSully** [Homebrew/homebrew-core#1252]
There was originally a pull-request at Homebrew/legacy-homebrew#26538 for NetPGP. It was closed for lack of a versioned URL. Per the [pkgsrc](http://pkgsrc.se/security/netpgp) page it appears versioned URLs are now available (e.g. [here](http://ftp.fr.netbsd.org/pub/pkgsrc/distfiles/LOCAL_PORTS/netpgp-20140220.tar.gz) or [here](http://www.netpgp.com/src/netpgp-20140220.tar.gz)). 

/cc @rnelson

**Comment by mikemcquaid** [comment]
We don't really accept formulae requests but will accept a versioned PR.
