### ISSUE TITLE
gubbins failed to build on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by Nicolas-Radomski** [Homebrew/homebrew-core#12589]
#PEASE HELP ME TO INSTALL GUBBINS FORMULA WITH BREW

#BREW UPDATE
$ brew update
Updated 1 tap (homebrew/core).
No changes to formulae.

#BREW DOCTOR
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/nradomski/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile

#BREW GIST-LOGS GUBBINS
$ brew gist-logs gubbins
Error: No logs.

#BREW CONFIG
$ brew config
HOMEBREW_VERSION: 1.1.11
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 59c9ddbc1d9b9dfdeb0514768e0efd0112c63b25
Last commit: il y a 10 jours
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 87754413ca4a2e98c8faeea292ad914bbdd9b5ba
Core tap last commit: il y a 17 heures
HOMEBREW_PREFIX: /home/nradomski/.linuxbrew
HOMEBREW_REPOSITORY: /home/nradomski/.linuxbrew
HOMEBREW_CELLAR: /home/nradomski/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648 => /home/nradomski/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 1.9.1 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: 1.8.0_121
Kernel: Linux 4.4.0-59-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS
Codename: trusty
OS glibc: 2.19
OS gcc: 4.8.4
Linuxbrew glibc: N/A
Linuxbrew gcc: 5.3.0
Linuxbrew xorg: N/A

#ERROR BREW INSTALL GUBBINS
$ brew install gubbins
==> Installing gubbins from homebrew/science
==> Installing dependencies for homebrew/science/gubbins: gawk, check, numpy, libpng, freetype, jpeg, libtiff, little-cms2, webp, pillow, raxml, fasttree
==> Installing homebrew/science/gubbins dependency: gawk
==> Downloading https://ftpmirror.gnu.org/gawk/gawk-4.1.4.tar.xz
Already downloaded: /home/nradomski/.cache/Homebrew/gawk-4.1.4.tar.xz
==> ./configure --prefix=/home/nradomski/.linuxbrew/Cellar/gawk/4.1.4_1 --withou
==> make
==> make check
Last 15 lines from /home/nradomski/.cache/Homebrew/Logs/gawk/03.make:
  2007
! gawk: mbstr2.awk:1: (FILENAME=- FNR=2) warning: Invalid multibyte data detected. There may be a mismatch between your data and your locale.
  2007
  2007
  2007
--- 1,5 ----
  2007
! gawk: mbstr2.awk:1: (FILENAME=- FNR=2) avertissement : Données multioctets non valables détectées. Possible incohérence entre données et paramètres régionaux (locale).
  2007
  2007
  2007
make[2]: quittant le répertoire « /tmp/gawk-20170418-30142-78f71x/gawk-4.1.4/test »
make[1]: *** [check] Erreur 1
make[1]: quittant le répertoire « /tmp/gawk-20170418-30142-78f71x/gawk-4.1.4/test »
make: *** [check-recursive] Erreur 1
READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

**Comment by MikeMcQuaid** [comment]
> https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

**Comment by MikeMcQuaid** [comment]
Report this to Linuxbrew.

**Comment by MikeMcQuaid** [comment]
Or homebrew-science.
