### ISSUE TITLE
Checksum-related commands in `uutils-coreutils` were not found.

### ISSUE THREAD

**Issue by ivaquero** [Homebrew/homebrew-core#125810]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.6-126-g1a72b86
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a72b861c36701e386e5acb2604b36398c8b382f
Last commit: 10 hours ago
Core tap JSON: 16 Mar 08:02 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed `uutils-coreutils` using `homebrew`, most commands work well except checksum-related commands like `sha*sum` and `md5sum` not found.

### What happened (include all command output)?

Checksum-related commands in `uutils-coreutils` like `sha*sum` and `md5sum` not found.

```console
zsh: command not found: md5sum
```

### What did you expect to happen?

`sha*sum` and `md5sum` can be found

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install uutils-coreutils

md5sum README.md
```

**Comment by SMillerDev** [comment]
See the caveat when you run `brew install uutils-coreutils`.
