### ISSUE TITLE
p7zip.rb formula SHA256 mismatch

### ISSUE THREAD

**Issue by kapitainsky** [Homebrew/homebrew-core#125841]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 4.0.6-126-g1a72b86
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a72b861c36701e386e5acb2604b36398c8b382f
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 364c2c6dade3098b929538f1081ef88653d20267
Core tap last commit: 5 weeks ago
Core tap branch: master
Core tap JSON: 16 Mar 14:10 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/nano
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A


brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python@2



```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install p7zip from source

### What happened (include all command output)?

```
==> Fetching p7zip
==> Downloading https://github.com/p7zip-project/p7zip/archive/v17.05.tar.gz
==> Downloading from https://codeload.github.com/p7zip-project/p7zip/tar.gz/refs/tags/v17.05
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 9473e324de6a87d89cb7ff65b0fec4ae3f147f03ffc138189c336a4650d74804
  Actual: d2788f892571058c08d27095c22154579dfefb807ebe357d145ab2ddddefb1a6
    File: /Users/db/Library/Caches/Homebrew/downloads/551a3458140ac9653922e87808998945b2244e4bac817715cf681db6a9836e18--p7zip-17.05.tar.gz
```

### What did you expect to happen?

source code to be downloaded and compiled

### Step-by-step reproduction instructions (by running `brew` commands)

there is error in p7zip formula:

https://github.com/Homebrew/homebrew-core/blob/f82a0bd5cdb8947d9a1d54bd5c6300da0e02cfe3/Formula/p7zip.rb#L4-L5
```
  url "https://github.com/p7zip-project/p7zip/archive/v17.05.tar.gz"
  sha256 "9473e324de6a87d89cb7ff65b0fec4ae3f147f03ffc138189c336a4650d74804"
```

I have verified it by manually downloading:

`wget https://github.com/p7zip-project/p7zip/archive/v17.05.tar.gz`

and checking its SHA256

shasum -a 256 v17.05.tar.gz
d2788f892571058c08d27095c22154579dfefb807ebe357d145ab2ddddefb1a6  v17.05.tar.gz
```
```

**Comment by carlocab** [comment]
The output of `brew config` and `brew doctor` is required for issues in this repository. We can reopen this once you've provided the required information.

**Comment by kapitainsky** [comment]
updated

**Comment by carlocab** [comment]
Why are you installing `p7zip` from source?

**Comment by kapitainsky** [comment]
> Why are you installing `p7zip` from source?

It was actually not planned and did it by accident  but when I saw error and obvious reason I thought it is good to report it.

Either way there is mistake/error in formula

**Comment by kapitainsky** [comment]
Thank you for looking into it!

**Comment by kapitainsky** [comment]
but they have already clarified why it was changed.

https://github.com/p7zip-project/p7zip/issues/218

With brew mismatch it means for example that people on older macOS versions (I know that not officially supported) will have issue updating as in such case everything is built from sources.

**Comment by kapitainsky** [comment]
p7zip does releases very rarely so it wont be "fixed" on brew site on its own soon.

Brew bottles contain buggy p7zip version - reported version is maybe not critical problem but can sooner or later cause problem e.g. if somebody's script rely on p7zip version explicitly. 

Given all above please reopen this report.

**Comment by carlocab** [comment]
This is already handled by #124758, which should be merged soon.
