### ISSUE TITLE
LLNode looks for Xcode version even when there is none

### ISSUE THREAD

**Issue by MCJack123** [Homebrew/homebrew-core#12609]
I was trying to install Homebrew, and during the installation, I got this error:
    
    Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llnode.rb
    undefined method `>=' for nil:NilClass
    Error: Cannot tap homebrew/core: invalid syntax in tap!
    Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
I realized that I did not have Xcode installed, but I did have the command line tools installed. I am using this on a VM with low hard drive space, and I wanted to save space by not installing Xcode. I checked the formula, and this line was the problem:
    
    if MacOS::Xcode.version >= "8.0"
This assumes that Xcode is installed. The formula should check if Xcode is installed before installing, or it should check the command line utility version. I get this error every time I try to run an `install` or `tap` command, so I cannot use homebrew because of this. `brew doctor` says that the command line utilities are not installed, but I did install them.

**Comment by ilovezfs** [comment]
What's the output of `brew config`? (Filling out the PR template would help)
