### ISSUE TITLE
brew uninstall script will delete OSX distribution binaries

### ISSUE THREAD

**Issue by supersophie** [Homebrew/homebrew-core#12601]
I wanted to completly uninstall brew

In here is the uninstall script called "uninstall" 
https://github.com/Homebrew/install

Running the uninstall **will remove /usr/sbin/sudo**  This does not see bright to me...

``# ./uninstall --dry-run
Warning: This script would remove:
/Library/Caches/Homebrew/
/usr/local/.git/
/usr/local/.github/
/usr/local/.gitignore
/usr/local/.travis.yml
/usr/local/.yardopts
/usr/local/CODEOFCONDUCT.md
/usr/local/Cellar/
/usr/local/LICENSE.txt
/usr/local/Library/
/usr/local/README.md
/usr/local/bin/brew
/usr/local/etc/bash_completion.d/brew
/usr/local/share/doc/homebrew/
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
==> Removing Homebrew installation...
Would delete:
/usr/local/share/info/dir
/usr/local/share/info/wget.info
Would delete:
/usr/local/bin/ccmake
/usr/local/bin/cmake
/usr/local/bin/cmakexbuild
/usr/local/bin/cpack
/usr/local/bin/cpulimit
/usr/local/bin/ctest
/usr/local/bin/dlite
/usr/local/bin/go
/usr/local/bin/godoc
/usr/local/bin/gofmt
/usr/local/bin/htop
/usr/local/bin/ncat
/usr/local/bin/ndiff
/usr/local/bin/nmap
/usr/local/bin/nping
/usr/local/bin/uninstall_ndiff
/usr/local/bin/watch
/usr/local/bin/wdel
/usr/local/bin/wget
/usr/local/bin/wput
/usr/local/etc/bash_completion.d/docker
/usr/local/include/libusb-1.0
/usr/local/lib/libusb-1.0.0.dylib
/usr/local/lib/libusb-1.0.a
/usr/local/lib/libusb-1.0.dylib
/usr/local/lib/pkgconfig/libusb-1.0.pc
/usr/local/lib/python2.7/site-packages/ndiff.py
/usr/local/opt/cmake
/usr/local/opt/cpulimit
/usr/local/opt/dlite
/usr/local/opt/docker
/usr/local/opt/go
/usr/local/opt/htop
/usr/local/opt/libusb
/usr/local/opt/nmap
/usr/local/opt/openssl
/usr/local/opt/qt5
/usr/local/opt/watch
/usr/local/opt/wget
/usr/local/opt/wput
/usr/local/share/aclocal/cmake.m4
/usr/local/share/applications/htop.desktop
/usr/local/share/cmake
/usr/local/share/doc/cmake
/usr/local/share/emacs
/usr/local/share/fish/vendor_completions.d/docker.fish
/usr/local/share/info/wget.info
/usr/local/share/man/de/man1/nmap.1
/usr/local/share/man/es/man1/nmap.1
/usr/local/share/man/fr/man1/nmap.1
/usr/local/share/man/hr/man1/nmap.1
/usr/local/share/man/hu/man1/nmap.1
/usr/local/share/man/it/man1/nmap.1
/usr/local/share/man/ja/man1/nmap.1
/usr/local/share/man/man1/ccmake.1
/usr/local/share/man/man1/cmake.1
/usr/local/share/man/man1/cpack.1
/usr/local/share/man/man1/ctest.1
/usr/local/share/man/man1/htop.1
/usr/local/share/man/man1/ncat.1
/usr/local/share/man/man1/ndiff.1
/usr/local/share/man/man1/nmap.1
/usr/local/share/man/man1/nping.1
/usr/local/share/man/man1/watch.1
/usr/local/share/man/man1/wdel.1.gz
/usr/local/share/man/man1/wget.1
/usr/local/share/man/man1/wput.1.gz
/usr/local/share/man/man7/cmake-buildsystem.7
/usr/local/share/man/man7/cmake-commands.7
/usr/local/share/man/man7/cmake-compile-features.7
/usr/local/share/man/man7/cmake-developer.7
/usr/local/share/man/man7/cmake-generator-expressions.7
/usr/local/share/man/man7/cmake-generators.7
/usr/local/share/man/man7/cmake-language.7
/usr/local/share/man/man7/cmake-modules.7
/usr/local/share/man/man7/cmake-packages.7
/usr/local/share/man/man7/cmake-policies.7
/usr/local/share/man/man7/cmake-properties.7
/usr/local/share/man/man7/cmake-qt.7
/usr/local/share/man/man7/cmake-toolchains.7
/usr/local/share/man/man7/cmake-variables.7
/usr/local/share/man/pl/man1/nmap.1
/usr/local/share/man/pt_BR/man1/nmap.1
/usr/local/share/man/pt_PT/man1/nmap.1
/usr/local/share/man/ro/man1/nmap.1
/usr/local/share/man/ru/man1/nmap.1
/usr/local/share/man/sk/man1/nmap.1
/usr/local/share/man/zh/man1/nmap.1
/usr/local/share/ncat
/usr/local/share/nmap
/usr/local/share/pixmaps/htop.png
/usr/local/share/zsh/site-functions/_docker
Would delete /Library/Caches/Homebrew
Would delete /usr/local/.git
Would delete /usr/local/.github
Would delete /usr/local/.gitignore
Would delete /usr/local/.travis.yml
Would delete /usr/local/.yardopts
Would delete /usr/local/CODEOFCONDUCT.md
Would delete /usr/local/Cellar
Would delete /usr/local/LICENSE.txt
Would delete /usr/local/Library
Would delete /usr/local/README.md
Would delete /usr/local/bin/brew
Would delete /usr/local/etc/bash_completion.d/brew
Would delete /usr/local/share/doc/homebrew
Would delete /usr/local/share/man/man1/brew.1
Would delete /usr/local/share/zsh/site-functions/_brew
==> Removing empty directories...
Would delete:
==> /usr/bin/sudo /usr/bin/find /usr/local/Cellar /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share -name .DS_Store -print
Would remove directories:
==> /usr/bin/sudo /usr/bin/find /usr/local/Cellar /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/opt /usr/local/sbin /usr/local/share -depth -type d -empty -print
/usr/local/Cellar/go/1.6/libexec/pkg/darwin_amd64/internal/syscall/windows
/usr/local/etc/openssl/certs
/usr/local/etc/openssl/private

``# ls -l /usr/bin/sudo
-r-s--x--x  1 root  wheel  369648 Mar 23 00:56 /usr/bin/sudo``

**Comment by ilovezfs** [comment]
It's not saying it would delete that. That's part of the command.

**Comment by supersophie** [comment]
oh. it's calling find via sudo.  thanks
