### ISSUE TITLE
haskell-stack -> stack

### ISSUE THREAD

**Issue by xeoneux** [Homebrew/homebrew-core#12614]
Why isn't haskell-stack simply named stack? It's easier to search and install that way.

**Comment by ilovezfs** [comment]
Because "stack" was considered too generic when the formula was named.

**Comment by xeoneux** [comment]
Should it be renamed now as there are no other formulas named stack?

**Comment by ilovezfs** [comment]
Does it change your opinion at all given their domain is haskellstack.org ?

**Comment by xeoneux** [comment]
Nope! stack.org is taken, probably that's why. They call it The Haskell Tool Stack.

**Comment by ilovezfs** [comment]
Let's see what other people think as well.

**Comment by ilovezfs** [comment]
CC @Homebrew/maintainers for thoughts.

**Comment by MikeMcQuaid** [comment]
Debian calls it Haskell Stack, their website is haskellstack and it's not in the first page of Google results for either "Stack" or "Stack Software" for me. 👎 from me.

**Comment by ilovezfs** [comment]
To make the counter-argument: I cannot tell him many times I've typed `brew install stack`, the basename of the repository on GitHub is `stack`, all of the documentation refers to it as "Stack" and it is colloquially referred to as such.

**Comment by ilovezfs** [comment]
>it's not in the first page of Google results for either "Stack" or "Stack Software" for me

For me, in a private browsing session, both hakellstack.org and https://github.com/commercialhaskell/stack are on the first page for a search for "stack."

**Comment by xeoneux** [comment]
I believe that the formula name should be the same as main executable that brew installs, to prevent confusion. 😸

**Comment by alyssais** [comment]
I like haskell-stack.

- stack on its own feels way to generic for me. As someone who was new to Haskell a couple of years ago, it was pretty confusing to see this thing just referred to everywhere as "stack", and it wasn't that easy for me to Google for and figure out what it was — it's not on the first page for me.
- haskell-stack means it'll show up in search results for `brew search haskell`, which I think is very valuable. If you're new to Haskell and trying to install the stack, it's very possible that you'll search for Haskell and not find anything, or that you'll see a formula just called "stack" and not be immediately sure if that's what you want. "haskell-stack" is completely unambiguous, and it's much less trouble for someone who knows they want Stack to try running "brew install stack", have it not work, do a quick search for stack and see the "Haskell-stack" formula than it is the other way around.

**Comment by alyssais** [comment]
@xeoneux side note: for a nice easy way to look up formulae by the names of their executables, check out [homebrew-command-not-found](https://github.com/Homebrew/homebrew-command-not-found)

**Comment by ilovezfs** [comment]
I'd be fine with an alias.

**Comment by xeoneux** [comment]
@alyssais `brew search haskell` could show similar output like `brew search clojure` does.

Which shows:
If you meant "clojure" specifically:
Clojure isn't really a program but a library managed as part of a
project and Leiningen is the user interface to that library.

To install Clojure you should install Leiningen:
  brew install leiningen
and then follow the tutorial:
  https://github.com/technomancy/leiningen/blob/stable/doc/TUTORIAL.md

**Comment by ilovezfs** [comment]
@alyssais regarding search: that's why we have `--desc`.

**Comment by alyssais** [comment]
@ilovezfs TIL xD

**Comment by alyssais** [comment]
An alias would be okay, I think.

**Comment by ilovezfs** [comment]
@alyssais RTFM or go home!

**Comment by ilovezfs** [comment]
Seems everyone is OK with an alias. @xeoneux is that sufficient for you to be :smiley:

**Comment by xeoneux** [comment]
Yup! @ilovezfs that would be great. 😸

**Comment by ilovezfs** [comment]
@xeoneux Done: https://github.com/Homebrew/homebrew-core/pull/12639.

**Comment by xeoneux** [comment]
Thanks @ilovezfs

**Comment by ilovezfs** [comment]
you're welcome
