### ISSUE TITLE
gnuradio formula is missing libsndfile dependency, Wav File Source & Sink blocks

### ISSUE THREAD

**Issue by argilo** [Homebrew/homebrew-core#126118]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.0.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c1031f2fd71016f0f5df699caaed384487bfb16
Last commit: 10 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bd7f8870ec2442c19bdeb295ad50742ee41be41f
Core tap last commit: 33 minutes ago
Core tap branch: master
Core tap JSON: 20 Mar 01:59 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-x86_64
CLT: 14.0.0.0.1.1661618636
Xcode: N/A

% brew doctor
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=#                                                                         
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use the "Wav File Source" and "Wav File Sink" blocks in GNU Radio.

### What happened (include all command output)?

The "Wav File Source" and "Wav File Sink" blocks are not present in GNU Radio Companion or elsewhere. `find /usr/local/Cellar/gnuradio -name 'wavfile_*.h'` returns nothing.

These blocks are only built if libsndfile is present at build time:

https://github.com/gnuradio/gnuradio/blob/c36e3b59ea0002f1cb9d178b411c9b1d3d8a5ade/gr-blocks/CMakeLists.txt#L13-L21

The current gnuradio formula does not specify libsndfile as a dependency, so the blocks are not built.

### What did you expect to happen?

I expected the "Wav File Source" and "Wav File Sink" blocks to be present after installing GNU Radio.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gnuradio
```

**Comment by jj1bdx** [comment]
When building gqrx:

```shell
/Users/kenji/src/gqrx/src/applications/gqrx/receiver.h:34:10: fatal error: 'gnuradio/blocks/wavfile_sink.h' file not found
```

**Comment by argilo** [comment]
> When building gqrx

Indeed. I noticed this problem because CI builds of Gqrx began failing with `'gnuradio/blocks/wavfile_sink.h' file not found` a couple days ago.

I suspect that earlier gnuradio builds may have been picking up libsndfile by accident as a transitive dependency, which could explain why the problem only manifested now.
