### ISSUE TITLE
`fakeroot` does not correctly working under SIP disabled environment

### ISSUE THREAD

**Issue by Torrekie** [Homebrew/homebrew-core#126334]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.6.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3e257890da96b4cc44f5933e3a54aee2b47549de
Last commit: 10 weeks ago
Branch: stable
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 28b9d1f537d5e0970c55d4dfc20ef63fbfa6d758
Core tap last commit: 9 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.39.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5.1
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

run `fakeroot` normally

### What happened (include all command output)?

`fakeroot` seems broken when SIP is disabled, this may also affects `libfaketime` but untested.

```
TorrekiedeMacBook-Pro:~ torrekie$ fakeroot 
dyld: dyld std::__terminate()

/opt/homebrew/bin/fakeroot: line 178: 46379 Abort trap: 6           FAKEROOTKEY=$FAKEROOTKEY DYLD_INSERT_LIBRARIES="$FAKEROOT_LIB" ${SHELL:-/bin/sh}
```

### What did you expect to happen?

it should then enter fake rooted shell normally

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# under recoveryOS
csrutil disable


```bash
# under macOS
brew install fakeroot
fakeroot bash
```
```

**Comment by gromgit** [comment]
Also:
> ```shell
> HOMEBREW_VERSION: 3.6.19
> Last commit: 10 weeks ago
> Core tap last commit: 9 weeks ago
> ```

Your Homebrew setup is pretty old, and there's been at least one version bump to `fakeroot` since then. Try `brew update` then `brew upgrade`, and see if that makes things work again.
