### ISSUE TITLE
Problem upgrading wine, running 10.11.6 osx

### ISSUE THREAD

**Issue by dnmurphy** [Homebrew/homebrew-core#12637]
Installing wine dependency: gd
==> Downloading https://github.com/libgd/libgd/releases/download/gd-2.2.3/libgd-2.2.3.tar.xz
==> Downloading from https://github-cloud.s3.amazonaws.com/releases/29669711/611ef3ba-4ffe-11e6-9382-af2d86b4324e.xz?X-Amz-Algorithm=AWS4-HMAC-SHA256&
######################################################################## 100.0%
Error: Empty archive

I then tried a separate upgrade of gd

brew upgrade gd
Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Upgrading 1 outdated package, with result:
gd 2.2.3
==> Upgrading gd
==> Downloading https://github.com/libgd/libgd/releases/download/gd-2.2.3/libgd-2.2.3.tar.xz
Already downloaded: /Users/user/Library/Caches/Homebrew/gd-2.2.3.tar.xz
Error: Empty archive

I then tried to install xz
brew install xz
Warning: xz-5.2.2 already installed
Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

I then tried to upgrade xz
brew upgrade xz
Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
Error: xz 5.2.2 already installed

Pretty sure this is a package problem as I have successfully used brew already for other packages 
Have done the brew update and the brew doctor
nothing from brew gist-logs, and when ran against xz https://gist.github.com/658749f4d8bd8c38d1d7c0f682e143fc

I was trying to upgrade wine, so ran brew upgrade wine (my current version is 1.6.2 and I wanted the latest version; then tried with updating individual dependencies

**Comment by dnmurphy** [comment]
Just as a small update i reran the upgrade for wine and got the following

brew upgrade wine
Warning: You are using a pre-release version of Xcode.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Upgrading 1 outdated package, with result:
wine 1.8.3
==> Upgrading wine
==> Installing dependencies for wine: gd, libgphoto2, little-cms2, sane-backends, libtasn1
==> Installing wine dependency: gd
==> Downloading https://github.com/libgd/libgd/releases/download/gd-2.2.3/libgd-2.2.3.tar.xz
Already downloaded: /Users/user/Library/Caches/Homebrew/gd-2.2.3.tar.xz
Error: Empty archive
Users-MacBook-Pro-3:ballots user$ wine --version
wine-1.6.2
Note, the xcode is not a pre-release version

**Comment by DomT4** [comment]
Your Homebrew is _way_ out of date. Like _waaaaaaaaaaaaaaaaaaay_ out of date. Try this:

```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```
And then:
```bash
brew upgrade wine
```

**Comment by dnmurphy** [comment]
worked a treat thanks

**Comment by DomT4** [comment]
@ilovezfs Safe to close here.
