### ISSUE TITLE
Missing mpv.app bundle for Apple Silicon

### ISSUE THREAD

**Issue by rgaufman** [Homebrew/homebrew-core#126368]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
NA
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed the package but there's no /Applications/mpv.app bundle like in previous versions from years ago.

### What happened (include all command output)?

mpv.app is missing

### What did you expect to happen?

mpv.app to be available in /Applications

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mpv
OR brew install mpv --HEAD
OR brew install --cask mkv # this does install mpv.app but an Intel binary, not one for Apple Silicon
```

**Comment by ZhongRuoyu** [comment]
The `mpv` cask should be what you're looking for. Do:

```
brew uninstall mpv
brew install --cask mpv
```

**Comment by rgaufman** [comment]
I tried that but this installed the Intel version, not an Apple Silicon one.

**Comment by ZhongRuoyu** [comment]
To answer why it's an Intel version, I'm quoting the app provider's [FAQ](https://laboratory.stolendata.net/~djinn/mpv_osx/) (note that Homebrew/cask is not building the app from source):

> faq: "Could you provide a native build for M1/M2 Macs?" - i'll look into it once i get access to an M1/M2 Mac

Note that this issue relates to a cask, and is therefore actually not a Homebrew/core issue.

**Comment by ZhongRuoyu** [comment]
On a side note, as for why Homebrew/cask is not providing an official build: because there isn't one. Some discussion related to `mpv`'s status in Homebrew/core and in Homebrew/cask can be found at at https://github.com/Homebrew/homebrew-cask/issues/86226.

**Comment by rgaufman** [comment]
Understood, thank you - as a solution I found this: https://github.com/deus0ww/homebrew-tap - hopefully this will be useful to somebody if they find this issue.
