### ISSUE TITLE
Fails to install emacs --HEAD

### ISSUE THREAD

**Issue by d12frosted** [Homebrew/homebrew-core#12667]
Hello, I just tried to `brew install emacs --HEAD` and it failed with following output.

```
$ brew install emacs --HEAD
==> Using the sandbox
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Users/d12frosted/Library/Caches/Homebrew/emacs--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/HEAD-4364a76/share/info/emacs
==> make
Last 15 lines from /Users/d12frosted/Library/Logs/Homebrew/emacs/03.make:
make[2]: *** [../lisp/leim/ja-dic/ja-dic.el] Error 255
make[1]: *** [../lisp/leim/leim-list.el] Error 2
make[1]: *** Waiting for unfinished jobs....
Directories for loaddefs: . ./calc ./calendar ./cedet ./cedet/ede ./cedet/semantic ./cedet/semantic/analyze ./cedet/semantic/bovine ./cedet/semantic/decorate ./cedet/semantic/symref ./cedet/semantic/wisent ./cedet/srecode ./emacs-lisp ./emulation ./erc ./eshell ./gnus ./image ./international ./language ./leim ./leim/ja-dic ./leim/quail ./mail ./mh-e ./net ./nxml ./org ./play ./progmodes ./textmodes ./url ./vc
EMACSLOADPATH= '../src/bootstrap-emacs' -batch --no-site-file --no-site-lisp -l autoload \
	    --eval '(setq autoload-ensure-writable t)' \
	    --eval '(setq autoload-builtin-package-versions t)' \
	    --eval '(setq generated-autoload-file (expand-file-name (unmsys--file-name "./loaddefs.tmp")))' \
	    -f batch-update-autoloads . ./calc ./calendar ./cedet ./cedet/ede ./cedet/semantic ./cedet/semantic/analyze ./cedet/semantic/bovine ./cedet/semantic/decorate ./cedet/semantic/symref ./cedet/semantic/wisent ./cedet/srecode ./emacs-lisp ./emulation ./erc ./eshell ./gnus ./image ./international ./language ./leim ./leim/ja-dic ./leim/quail ./mail ./mh-e ./net ./nxml ./org ./play ./progmodes ./textmodes ./url ./vc
Not registering prefix "lo" from completion.  Affects: ("locate-completion-entry" "locate-completion-entry-retry" "locate-completion-db-error" "load-completions-from-file")
Not registering prefix "*" from ielm.  Affects: ("*" "**" "***" "*1" "*2" "*3")
Not registering prefix "is" from ind-util.  Affects: ("is13194-default-repertory" "is13194-repertory-to-ucs-script" "is13194-to-ucs-devanagari-hashtbl" "is13194-to-ucs-devanagari-regexp" "is13194-to-ucs-bengali-hashtbl" "is13194-to-ucs-bengali-regexp" "is13194-to-ucs-assamese-hashtbl" "is13194-to-ucs-assamese-regexp" "is13194-to-ucs-gurmukhi-hashtbl" "is13194-to-ucs-gurmukhi-regexp" "is13194-to-ucs-gujarati-hashtbl" "is13194-to-ucs-gujarati-regexp" "is13194-to-ucs-oriya-hashtbl" "is13194-to-ucs-oriya-regexp" "is13194-to-ucs-tamil-hashtbl" "is13194-to-ucs-tamil-regexp" "is13194-to-ucs-telugu-hashtbl" "is13194-to-ucs-telugu-regexp" "is13194-to-ucs-malayalam-hashtbl" "is13194-to-ucs-malayalam-regexp" "is13194-to-ucs-kannada-hashtbl" "is13194-to-ucs-kannada-regexp" "iscii-to-ucs-region")
Not registering prefix "se" from page-ext.  Affects: ("search-pages" "set-page-delimiter")
../build-aux/move-if-change ./loaddefs.tmp loaddefs.el
make: *** [src] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html


Error: Your Xcode (8.3.1) is outdated.
Please update to Xcode 8.3.2 (or delete it).
Xcode can be updated from the App Store.
```

Expected behaviour: `emacs` should be installed without any errors.

Several possibly useful outputs.

```
$ brew gist-logs emacs
https://gist.github.com/3bb00556d7d064f525c99a509d3fab65

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode (8.3.1) is outdated.
Please update to Xcode 8.3.2 (or delete it).
Xcode can be updated from the App Store.
```

*Note that I can't update Xcode for now. Will try with updated Xcode on weekends.*

Let me know if you need any other info.

**Comment by MikeMcQuaid** [comment]
> Let me know if you need any other info.

Out issue template told you what information we need. Please add it to this issue and it may be reopened.

**Comment by d12frosted** [comment]
@MikeMcQuaid, I've followed template. But let me check out everything it asked:

----

# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? -- and even included output
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? -- not applicable

To help us debug your issue please explain:
- [x] What you were trying to do (and why)
- [x] What happened (include command output)
- [x] What you expected to happen
- [x] Step-by-step reproduction instructions (by running `brew install` commands)
```

Am I missing anything?

**Comment by MikeMcQuaid** [comment]
As you didn't follow the template it was hard to see what was and wasn't included. I couldn't find your `gist-logs` output first time I looked.

> Ran brew doctor, fixed as many issues as possible and retried your prior step?

You didn't update Xcode and there's various other issues there that you should try to resolve.

**Comment by d12frosted** [comment]
> As you didn't follow the template it was hard to see what was and wasn't included. I couldn't find your gist-logs output first time I looked.

Ah sorry. Thought that I can remove that template once I check everything. 

> You didn't update Xcode

Yes, I haven't updated it, but unfortunately, I can't update it right now. Is it critical for building emacs from sources? I will update only on weekends. And will let you know if it fixes the issue.

> there's various other issues there that you should try to resolve.

Which other issues? Running `brew doctor` only gives me a warning about Xcode.

**Comment by MikeMcQuaid** [comment]
@d12frosted There's a bunch of other warnings here: https://gist.github.com/anonymous/3bb00556d7d064f525c99a509d3fab65#file-00-doctor-out

It may not be critical or it may, I can't tell I'm afraid.

**Comment by d12frosted** [comment]
Wow. First of all I am impressed in a bad way that it's uploaded automatically without asking me. But whatever. Secondly, I've went through these warnings, fixed them and then tried again to install. And only then I've filled out the issue. 😸 

<img width="958" alt="screenshot 2017-04-20 17 16 40" src="https://cloud.githubusercontent.com/assets/6507913/25235217/30dcfee8-25ed-11e7-838e-5efb023d20ef.png">

As per Xcode version, I know some people had similar issue on the same version of Xcode before the latest was released. But I'll try out updating and will let you know.

**Comment by ilovezfs** [comment]
Stupid question: does it work if you build stable from source? (i.e., if you pass `--build-from-source` instead of `--HEAD`)

**Comment by DomT4** [comment]
Fails locally when building from `--HEAD` despite a clean `doctor` FWIW. The `--HEAD` build here has been notoriously unreliable for a long time though.

**Comment by ilovezfs** [comment]
HEAD built fine for me on 10.11 so this sounds like Xcode 8.3.? issue

**Comment by DomT4** [comment]
Aye, very possibly:
```
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.0.0.1.1490382677
```
I wonder if it builds cleanly with CLT-only on 10.12.

**Comment by ilovezfs** [comment]
@dunn @zmwangx any ideas from the Church of Emacs?

**Comment by d12frosted** [comment]
@ilovezfs it succeeds when I `--build-from-source`. 

Ok, apparently I just have to update Xcode. Will leave a comment.

Thanks everyone!

**Comment by ilovezfs** [comment]
@d12frosted if that were the case, I don't think @DomT4 would see his build fail since has 8.3.2

**Comment by dunn** [comment]
HEAD builds successfully for me:
```
HOMEBREW_VERSION: 1.1.13-33-g67a0a89b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 67a0a89b100b36adec735601e90082eeef3456a1
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8858f5a90c87d6b0744e3f322d0b1f4d6e980fb6
Core tap last commit: 84 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/alex/.rbenv/shims/ruby => /Users/alex/.rbenv/versions/2.3.1/bin/ruby
Java: 1.8.0_121
macOS: 10.12.4-x86_64
Xcode: 8.3.1
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11

**Comment by dunn** [comment]
This looks like a parallelization problem: https://gist.github.com/anonymous/3bb00556d7d064f525c99a509d3fab65#file-03-make-L2264

**Comment by ilovezfs** [comment]
@d12frosted you can try
```
HOMEBREW_MAKE_JOBS=1 brew install emacs --HEAD
```

**Comment by DomT4** [comment]
It makes for an incredibly slow build but:
```diff
diff --git a/Formula/emacs.rb b/Formula/emacs.rb
index 7ac3d05647..1b5341c10b 100644
--- a/Formula/emacs.rb
+++ b/Formula/emacs.rb
@@ -97,6 +97,7 @@ class Emacs < Formula
     end
 
     system "./configure", *args
+    ENV.deparallelize
     system "make"
     system "make", "install"
 
```

```
==> Summary
🍺  /usr/local/Cellar/emacs/HEAD-4364a76: 3,919 files, 100.2MB, built in 14 minutes 54 seconds
```

**Comment by ilovezfs** [comment]
@dunn gets the :trophy:

**Comment by d12frosted** [comment]
@ilovezfs your suggestion worked:

```
==> Summary
🍺  /usr/local/Cellar/emacs/HEAD-4364a76: 3,919 files, 100.1MB, built in 14 minutes 29 seconds
```

**Comment by d12frosted** [comment]
@DomT4 yeah, it takes a lot. But at least builds 😸 

@ilovezfs 🏆 thanks :)

**Comment by ilovezfs** [comment]
So who wants to report this turkey to upstream?

**Comment by ilovezfs** [comment]
Assuming this will take care of itself as we don't really support HEAD builds.
