### ISSUE TITLE
Coq requires ocaml-findlib at runtime (since version 8.16)

### ISSUE THREAD

**Issue by MSoegtropIMC** [Homebrew/homebrew-core#126774]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

I am not using homebrew myself so I can't answer some of the below questions but I belong to the maintainer team of Coq and report this as follow up to this issue report on stackoverflow:

https://stackoverflow.com/questions/75843422/coqc-does-not-find-findlib-conf

Looking at what I think is homebrew's definition of the Coq package:

https://formulae.brew.sh/api/formula/coq.json

I would say that "ocaml-findlib" should be moved from "build_dependencies" to "dependencies". In version 8.16 Coq changed its way to find shared libraries at run time and now requires ocaml-findlib also at run time. Up to 8.15 it required this only at build time.

The solution given in the above stackoverflow to do a "brew install ocaml-findlib" support this.

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

See https://stackoverflow.com/questions/75843422/coqc-does-not-find-findlib-conf

### What happened (include all command output)?

See https://stackoverflow.com/questions/75843422/coqc-does-not-find-findlib-conf

### What did you expect to happen?

See https://stackoverflow.com/questions/75843422/coqc-does-not-find-findlib-conf

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See https://stackoverflow.com/questions/75843422/coqc-does-not-find-findlib-conf
```

**Comment by carlocab** [comment]
Thanks for the report. I opened #126775 to fix this.

**Comment by MSoegtropIMC** [comment]
Thanks - I appreciate it!
