### ISSUE TITLE
Mujs 1.3.3 seems broken on Apple Silicon machines

### ISSUE THREAD

**Issue by kiracus** [Homebrew/homebrew-core#126846]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config 

HOMEBREW_VERSION: 4.0.10-11-gdb7c74d
ORIGIN: https://github.com/Homebrew/brew
HEAD: db7c74d0988c087c3405864480bc08ef7368a962
Last commit: 5 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bdf52e4896818e57839a8110779b8dad97fe505c
Core tap last commit: 89 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1678558616
Xcode: N/A
Rosetta 2: false```
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

use `mujs`

### What happened (include all command output)?

fatal error: 'mujs.h' file not found

### What did you expect to happen?

mujs works

### Step-by-step reproduction instructions (by running `brew` commands)

I am trying to build the osxbundle of mpv and I notice the error during build as

fatal error: 'mujs.h' file not found

In order to triage the issue, I take a look at  `/opt/homebrew/Cellar/mujs/1.3.3/lib/pkgconfig/mujs.pc`
. The contains is

```shell
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.3
Cflags: -I/usr/local/include
Libs: -L/usr/local/lib -lmujs
Libs.private: -lm
```

then I compare the content from previous version, which does not have the issue

``` 
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.2
Cflags: -I/opt/homebrew/Cellar/mujs/1.3.2/include
Libs: -L/opt/homebrew/Cellar/mujs/1.3.2/lib -lmujs
Libs.private: -lm
```

I feel the 1.3.3 version contains the incorrect Cflags and Libs values obviously. it should always point to the homebrew folder, right?

So I did an experiment by modifying the mujs.pc into
```
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.3
Cflags: -I/opt/homebrew/Cellar/mujs/1.3.3/include
Libs: -L/opt/homebrew/Cellar/mujs/1.3.3/lib -lmujs
Libs.private: -lm
```
and then I no longer saw the 'mujs.h' file not found error.

I notice that, inside the PR when homebrew bumps the `mujs` version https://github.com/Homebrew/homebrew-core/pull/126240. A patch was removed. I am not sure whether it is related or not, I can not find the upstream link of the path. maybe we still need the patch?

Thanks

**Comment by carlocab** [comment]
No, it's not because of the patch. Upstream tweaked their `Makefile`, we need to pass `"prefix=#{prefix}"` in the first call to `make` as well, since that's when the `.pc` is generated.
