### ISSUE TITLE
Latest git-annex Formula Loses s3 remote

### ISSUE THREAD

**Issue by xanderdunn** [Homebrew/homebrew-core#1268]
### Bug reports:

`brew install git-annex` installs 6.2.20160418.  Attempt to create an [S3 remote](http://git-annex.branchable.com/special_remotes/S3/) and you'll get the error `git-annex: Unknown remote type S3`.  

It appears the latest bottle has been compiled without S3 remote type support?

I reverted to 6.20160126, the version I was using before my latest `brew update`, and S3 remote types work again:
```
brew uninstall git-annex
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/714f0346476022d2b874fbeb3784bc5db4e7cd98/Formula/git-annex.rb
```

**Comment by dunn** [comment]
The only recent change to the formula other than version bumps was around the flags; `Webapp` was removed in https://github.com/Homebrew/homebrew-core/commit/4d9833c7aab984d429607ceab3e4ecff5ed8ddd3 and `webapp` introduced in https://github.com/Homebrew/homebrew-core/commit/0831f365f5e09291e4f71f7d6a2e41fb7e1d1e28.

Can you try upper-casing that flag again and see if that fixes it?

**Comment by ilovezfs** [comment]
All flags are lower case: https://hackage.haskell.org/package/git-annex

The issue is cabal's behavior: https://www.haskell.org/cabal/users-guide/developing-packages.html#resolution-of-conditions-and-flags

I'm trying a build now with all the flags set to their default value explicitly to see if it fails. Most likely this is all moot since there are two newer versions out anyway.

**Comment by ilovezfs** [comment]
Strangely, specifying all the flags caused no issue, so it's not a backtracking bug after all. More likely a run-of-the-mill upstream bug. I'm building the new version now, so we'll see if that's affected, too.

Of course it's also possible upstream changed the syntax and we're doing it wrong.

**Comment by ilovezfs** [comment]
@dunn Actually, the documentation says the flags are case insensitive. Thanks for bringing that up, as it had previously bugged me that the capitalization had changed without comment.

**Comment by ilovezfs** [comment]
@xanderdunn @dunn #1307 fixes this.

**Comment by xanderdunn** [comment]
@ilovezfs Cool, thanks!

**Comment by ilovezfs** [comment]
You're welcome. Thanks for reporting it!

If you want to try the fix locally:
```
brew pull 1307
brew install --verbose --build-from-source git-annex
```
