### ISSUE TITLE
Newer versions of the emacs formula (current is 25.1) do not support x11 builds

### ISSUE THREAD

**Issue by drzowie** [Homebrew/homebrew-core#12690]
It appears to be no longer possible to build an X11 emacs with the included package.  This is because the --with-x11 option is no longer supported.

It would be fabulous if it did, because many folks (like me) prefer the x11 interface to the separate Quartz app.  The options "--with-cocoa" and "--with-x11" should both exist (and be mutually exclusive, as per the GNU-provided "configure" script with emacs 25.1).  The --with-x11 option just needs to add "--with-x --without-ns" to the ./configure command line.

# Please always follow these steps:
- [ X ] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ NA ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ NA ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

_install emacs with x11 support_

- What happened (include command output)

_The --with-x11 option is no longer part of the default formula._

- What you expected to happen

_ An emacs that supported x11 would be built and installed.  Instead, --with-x11 is no longer a valid option._

- Step-by-step reproduction instructions (by running `brew install` commands)

_brew install --with-x11 emacs_

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

**Comment by DomT4** [comment]
See the discussion at https://github.com/Homebrew/homebrew-core/pull/3531, and possibly the related discussion at https://github.com/Homebrew/homebrew-x11/issues/285.

Chasing the option is a dead-end, for better or worse.

**Comment by ilovezfs** [comment]
@drzowie you may want to consider using https://github.com/d12frosted/homebrew-emacs-plus which still has the option.
