### ISSUE TITLE
texlive: documentation removed

### ISSUE THREAD

**Issue by kenohassler** [Homebrew/homebrew-core#126958]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a3e0fb3fe4a28d59c4f0fc68198e3aab24a12be8
Core tap last commit: 6 weeks ago
Core tap branch: master
Core tap JSON: 29 Mar 13:35 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
Rosetta 2: false
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I tried to open documentation for an installed latex package. Example: `texdoc listings`.

### What happened (include all command output)?

Error message:
```
Sorry, no documentation found for "listings".
If you are unsure about the name, try full-text searching on CTAN.
Search form: <https://www.ctan.org/search/>
```

### What did you expect to happen?

The documentation PDF should be opened.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install texlive
texdoc listings
```
I found in the formula that the `texmf-dist/doc` folder is deleted after installation, which I believe should contain the latex documentation. Is there a specific reason for this?
https://github.com/Homebrew/homebrew-core/blob/c18a35db1a25be4c080c81cde6cdf6617392da1f/Formula/texlive.rb#L380

**Comment by SMillerDev** [comment]
We don't generally ship documentation since it is almost always available online as well, and in this case Texlive just uses so much disk space that we had to free some up to get it through CI.

**Comment by kenohassler** [comment]
Alright, makes sense. Thanks for your answer! I'll switch to online resources then 😃
