### ISSUE TITLE
ranger doesn't work anymore after upgrade

### ISSUE THREAD

**Issue by cyberdynesoftware** [Homebrew/homebrew-core#127084]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.10-82-ga969ac9
ORIGIN: https://github.com/Homebrew/brew
HEAD: a969ac9a948eac1b97e3b597a93163dfb65b7c72
Last commit: 85 minutes ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61239c4c7192787f360874ea7d7d8aa3361ae2c1
Core tap last commit: 7 weeks ago
Core tap branch: master
Core tap JSON: 30 Mar 13:54 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.7.4-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run ranger (because I like managing my files with ranger).

### What happened (include all command output)?

zsh: /usr/local/bin/ranger: bad interpreter: /usr/local/opt/python@3.10/bin/python3: no such file or directory

### What did you expect to happen?

For ranger to run normally, as before the upgrade.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install ranger
$ ranger

No space for additional information? I'll just provide them here:
Python has been upgraded to version 3.11.2 and it seems somebody forgot to tell ranger about it. Maybe it would be easier to simply point to /usr/local/bin/python3 instead.
```

**Comment by cyberdynesoftware** [comment]
Thanks, reinstalling actually fixed the problem. How did this happen?

I've searched ~/.config/ranger/ before to see if there was some bad configuration on my part, but found nothing.

**Comment by carlocab** [comment]
Not sure, TBH. Closing this as your issue is fixed, and I'm not sure what more we can do here.
