### ISSUE TITLE
Ansible 2.3.0 with Jinja 2.9.6 breaks templating.

### ISSUE THREAD

**Issue by danielgriggs** [Homebrew/homebrew-core#12703]
To help us debug your issue please explain:
Installing Ansible 2.3.0 bundles Jinja 2.9.6 with it.
But there is a problem with Jinja > 2.9.0 and multiple imports into templates don't work anymore.
Please downgrade the included Jinja library to below 2.9.

Debugging details and examples can be found at on the Ansible Issue tracker here.
https://github.com/ansible/ansible/issues/23779

**Comment by ilovezfs** [comment]
@danielgriggs has this been reported to Jinja upstream?
