### ISSUE TITLE
Replace ipcalc package with ipv6-capable version

### ISSUE THREAD

**Issue by justdave** [Homebrew/homebrew-core#12715]
# Please always follow these steps:
- [√] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [√] Ran `brew update` and retried your prior step?
- [n/a] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [n/a] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

=====

The ipcalc package is ipcalc from http://jodies.de/ipcalc
That ipcalc branch hasn't been updated since 2006 and isn't IPv6-aware.

There's a newer fork at https://github.com/nmav/ipcalc which is IPv6-aware.

Sorry, I don't know how to build a package, so I can't do a pull request with a replacement package, just offering the suggestion in case someone else can.

**Comment by dunn** [comment]
Is the fork widely accepted as the replacement (ideally, endorsed by the original developers)?

**Comment by justdave** [comment]
I don't know and not sure how to find out.

**Comment by MikeMcQuaid** [comment]
We'd need there to be a reference on the webpage pointing to the new fork and the new fork doesn't seem particularly notable currently. You're best to contact the author. Sorry!

**Comment by justdave** [comment]
How about putting the other one in with an alternate package name and marking it as conflicting with the first one?  The idea is to get a modern tool for the job into homebrew, not necessarily to replace the old one.

**Comment by justdave** [comment]
OK, I just heard back from the author, he is intending to add IPv6 support to his version, so I guess we just wait for it. :-)
