### ISSUE TITLE
Latest MariaDB Fails To Start

### ISSUE THREAD

**Issue by taylorotwell** [Homebrew/homebrew-core#1272]
### Bug reports:

Fresh install of Homebrew. Install `mariadb`. Run `brew services start mariadb`. Unable to connect to MariaDB. `brew doctor` does not report any problems. `LaunchAgent` appears correctly installed.

**Comment by taylorotwell** [comment]
Noticed that "group" is `admin` for the `mysqld_safe` binary in /usr/local/opt/mariadb/bin.

**Comment by taylorotwell** [comment]
Added error output to LaunchAgent plist file and this is in file:

/usr/local/opt/mariadb/bin/mysqld_safe: line 144: /usr/local/var/mysql/Taylors-MacBook.attlocal.net.err: Permission denied

**Comment by adamwathan** [comment]
Same problem for me, linking MariaDB then unlinking and relinking MySQL also caused MySQL to stop working. Had to recursively change permissions on `/usr/local` to get things working again but not confident that was necessarily the proper fix.

**Comment by taylorotwell** [comment]
Yeah, I also had to run `sudo chown -R Taylor/staff /usr/local` to things to work out of the box.

This was on a fresh laptop so not sure this is expected Homebrew / Maria behavior to have to run this command to get things working.

**Comment by adamwathan** [comment]
Linking MariaDB:
![image](https://cloud.githubusercontent.com/assets/4323180/15394026/6aafd30a-1d9e-11e6-9cd9-e643538aa662.png)

Changing permissions gets it to run:
![image](https://cloud.githubusercontent.com/assets/4323180/15394039/797f99c4-1d9e-11e6-8355-ae122deb554b.png)

**Comment by adamwathan** [comment]
Unlinking MariaDB then relinking it causes same issues until I fix the permissions:
![image](https://cloud.githubusercontent.com/assets/4323180/15394083/b31aaae8-1d9e-11e6-9331-6aafbdb45fdc.png)

**Comment by adamwathan** [comment]
Now even changing the permissions won't allow MariaDB to work properly.

**Comment by lucasmichot** [comment]
@adamwathan 
- Is the mysql daemon stopped ?
- Does `/tmp/mysql.sock` file really exist ?
- If so, what are the owner/group of `/tmp/mysql.sock` ?

**Comment by adamwathan** [comment]
Hey thanks @lucasmichot ! Still getting the error after unlinking MySQL, reinstalling MariaDB and restarting:

![image](https://cloud.githubusercontent.com/assets/4323180/15413778/b5d520f2-1e01-11e6-8762-2c8daa18c252.png)

MariaDB appears to be "running" according to `brew services`:

![image](https://cloud.githubusercontent.com/assets/4323180/15413785/ca7ca8ae-1e01-11e6-9ad4-80775f89492f.png)

`/tmp/mysql.sock` does not actually exist while MariaDB is running:

![image](https://cloud.githubusercontent.com/assets/4323180/15413803/f2883282-1e01-11e6-9d4a-f5e293c29ca0.png)


When I unlink MariaDB and relink and restart MySQL, that file does exist:

![image](https://cloud.githubusercontent.com/assets/4323180/15413813/ff104472-1e01-11e6-994c-a8f140623239.png)

**Comment by MikeMcQuaid** [comment]
> Same problem for me, linking MariaDB then unlinking and relinking MySQL also caused MySQL to stop working. Had to recursively change permissions on /usr/local to get things working again but not confident that was necessarily the proper fix.



> Yeah, I also had to run sudo chown -R Taylor/staff /usr/local to things to work out of the box.
> 
> This was on a fresh laptop so not sure this is expected Homebrew / Maria behavior to have to run this command to get things working.

That's expected behaviour, our installer does that for you.

Don't rely on `brew services` to see if it is running or not: use `ps aux | grep mysql` (or the `mariadb` equivalent). Try to use `mysql.server start` or `mysqld` rather than `brew services` to start it and check the failure output.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by adamwathan** [comment]
FWIW in case anyone finds this down the road (future me included 😊),  the thing that seems to reliably work for me when trying to switch between MariaDB and MySQL is to delete/rename/backup `/usr/local/var/mysql` before switching to the other database.

It seems like the installer notices those files and tries to preserve them, but something in there is not compatible between the two databases.

I can reliably switch whenever I want as long as `/usr/local/var/mysql` doesn't exist when installing the other DB.

For example, this works every time:

```
brew services stop mysql
brew uninstall mysql
mv /usr/local/var/mysql /usr/local/var/mysql_bu
brew install mariadb
brew services start mariadb
```

**Comment by timleland** [comment]
@adamwathan these steps worked. Thanks!

**Comment by xtrasmal** [comment]
For those who get  the ```mysql.sock not found``` error. See if ```mysqld``` is running.
After updating Valet, all went on a roadtrip to hell. The above made the dev-il go away.

**Comment by gobijan** [comment]
I did a clean remove via this guide and then reinstalled: 
https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks
