### ISSUE TITLE
Please install git-lfs man pages with the git-lfs formula

### ISSUE THREAD

**Issue by pwagland** [Homebrew/homebrew-core#12727]
It would be very useful if the git-lfs man pages were installed with the formula.  Currently you get no help for git bfs:

> 15:41 $ git lfs --help
> No manual entry for git-lfs

**Comment by ilovezfs** [comment]
Closed via #12728.

**Comment by ilovezfs** [comment]
@pwagland if you `brew update` and `brew upgrade git-lfs` you should have the man pages.

**Comment by pwagland** [comment]
Fantastic work @ilovezfs ! Indeed the man pages are there as predicted. Thanks for the super quick turn-around time!

**Comment by ilovezfs** [comment]
You're very welcome!
