### ISSUE TITLE
brew services Error: uninitialized constant Homebrew::Service::System

### ISSUE THREAD

**Issue by gregch** [Homebrew/homebrew-core#127329]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.10-119-g931327d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8a4facc6236b60732808b14d18ce42c3d8a5ea0d
Core tap last commit: 4 days ago
Core tap branch: master
Core tap JSON: 02 Apr 10:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.cloud.tencent.com/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.tZDuV4f6po/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  sxiv
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to list services.

### What happened (include all command output)?

Error: uninitialized constant Homebrew::Service::System
/opt/homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:61:in `services'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### What did you expect to happen?

List all services

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew services list
```

**Comment by ThinkerT** [comment]
I also encountered the same problem

**Comment by SMillerDev** [comment]
What does `git -C $(brew --repo homebrew/services) remote get-url origin` say?

**Comment by gregch** [comment]
> What does `git -C $(brew --repo homebrew/services) remote get-url origin` and `git -C $(brew --repo homebrew/services) show HEAD` say?


`git -C $(brew --repo homebrew/services) remote get-url origin` results:
```
$ git -C $(brew --repo homebrew/services) remote get-url origin
https://gitee.com/cunkai/homebrew-services.git
```

`git -C $(brew --repo homebrew/services) show HEAD` results

```
commit 36c2e20cbd592e36c4749aac5f7d4345e8cbbb27 (HEAD -> master, origin/master, origin/HEAD)
Merge: 8f4bb61 f17c89c
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Wed Jun 29 16:08:08 2022 +0100

    Merge pull request #484 from MikeMcQuaid/brew_style_fix
    
    Manual brew style fixes

(END)
```

**Comment by ZhongRuoyu** [comment]
That seems to be an unmaintained mirror. Please try

```
git -C "$(brew --repo homebrew/services)" remote set-url origin https://github.com/Homebrew/homebrew-services.git
brew update
```

**Comment by gregch** [comment]
> git -C "$(brew --repo homebrew/services)" remote set-url origin https://github.com/Homebrew/homebrew-services.git
> brew update

Thanks for the reply. Definitely solved the problem.

**Comment by ningninga** [comment]
> git -C "$(brew --repo homebrew/services)" remote set-url origin https://github.com/Homebrew/homebrew-services.git
> brew update

it works! thx!
