### ISSUE TITLE
terraform formula installs incorrect version of binary

### ISSUE THREAD

**Issue by amancevice** [Homebrew/homebrew-core#127453]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
-----------
HOMEBREW_VERSION: 4.0.11-20-ga883970
ORIGIN: https://github.com/Homebrew/brew
HEAD: a88397096daffccede3f6daab8ed519b8230a714
Last commit: 9 hours ago
Core tap JSON: 03 Apr 19:52 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.40.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-x86_64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3

brew doctor
-----------
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install terraform v1.4.4 to do some serious infrastructure crimes

### What happened (include all command output)?

After installing the latest version of the `terraform` formula (1.4.4) the output of `terraform -version` is:

```bash
Terraform v1.4.3-dev
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### What did you expect to happen?

The output of `terraform -version` ought to be:

```bash
Terraform v1.4.4
on darwin_amd64
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install terraform
# or
brew reinstall terraform
```

**Comment by cho-m** [comment]
Probably need to replicate upstream's build scripts for setting `ldflags`/etc.

Homebrew's build was done using the version number in corresponding Git tag which upstream didn't update https://github.com/hashicorp/terraform/blob/v1.4.4/version/version.go#L13-L14

However, upstream's build does pass in some `ldflags` like https://github.com/hashicorp/terraform/actions/runs/4568417937/jobs/8063451319#step:5:11
```
go build -ldflags "-w -s -X 'github.com/hashicorp/terraform/version.Version=1.4.4' -X 'github.com/hashicorp/terraform/version.Prerelease='" -o dist/ .
```

Corresponding version info in flags may be from script: https://github.com/hashicorp/terraform/blob/v1.4.4/.github/scripts/get_product_version.sh

**Comment by p-linnane** [comment]
This is an issue with upstream's tarball. Building it outside `brew` returns `1.4.3-dev` as well. See https://github.com/Homebrew/homebrew-core/pull/127125#issuecomment-1494563102.

**Comment by amancevice** [comment]
thanks for the investigation — I'll close this as an issue on their end. As a closing thought: does it make sense to build & bottle this formula with brew, or would it be better to link to hashicorp's own pre-built tarballs? Downloading the official release [here](https://developer.hashicorp.com/terraform/downloads) does not exhibit the same issue.

**Comment by SMillerDev** [comment]
> does it make sense to build & bottle this formula with brew, or would it be better to link to hashicorp's own pre-built tarballs? 

Brew only builds its own software. In the end it might be a better fix if hashicorp distributed its own open source tarballs so it doesn't break like this anymore.

**Comment by amancevice** [comment]
@SMillerDev forgive me if this is ignorant, but what's not open source about the official releases linked above?

The download URLs ought to be parseable by Homebrew:
```plaintext
https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_darwin_amd64.zip
https://releases.hashicorp.com/terraform/1.4.4/terraform_1.4.4_darwin_arm64.zip
```

**Comment by SMillerDev** [comment]
Well, the resulting binaries are different between brew and upstream so clearly they're not using the instructions brew is following.

As for using pre compiled binaries, that's what casks are for. Homebrew core compiles all binaries for specific platforms.

**Comment by crw** [comment]
> In the end it might be a better fix if hashicorp distributed its own open source tarballs so it doesn't break like this anymore.

Just FYI: `brew install hashicorp/tap/terraform` is the officially-supported tap.

> the resulting binaries are different between brew and upstream so clearly they're not using the instructions brew is following.

As there were no previous explicit build instructions, this is correct insofar as `go build` was the default through 1.4.3. Terraform is in the process of changing build systems. There will likely be new build instructions for 1.4.5 and beyond. We are working out the details now. See: https://github.com/hashicorp/terraform/issues/32963#issuecomment-1494772804
