### ISSUE TITLE
luajit --devel compiled with options that break correctness

### ISSUE THREAD

**Issue by joshuafcole** [Homebrew/homebrew-core#1274]
# Please follow the general troubleshooting steps first:
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

The issue is tracked and explained in depth on this issue that I filed against luaJIT.
https://github.com/LuaJIT/LuaJIT/issues/180

Some aspect of the formula's build process causes the compiled artifact to use AVX instead of integer operations which clobber a register than LuaJIT expects to be available. This problem cannot be reproduced without changing the `CCOPT_x64` make flag to `-march=native` when building from source.

This leads to wildly incorrect behavior on trivial examples.

**Comment by bigbes** [comment]
It also affects Tarantool, since it's using LuaJIT. I've reproduced this behavior.

**Comment by ilovezfs** [comment]
Please try adding
```
ENV["HOMEBREW_OPTFLAGS"] = "-march=#{Hardware.oldest_cpu}" unless build.bottle?
```
at the beginning of `def install`. Does the problem go away?

**Comment by tdsmith** [comment]
From that discussion it looks like this commit resolves the issue: https://github.com/LuaJIT/LuaJIT/commit/5837c2a2fb1ba66510c9100a296966020f1610a3

**Comment by ilovezfs** [comment]
Someone should probably nag them to tag a new version.

**Comment by DomT4** [comment]
If someone who can reproduce the original errors reported upstream wants to test https://github.com/Homebrew/homebrew-core/pull/1346 that'd be appreciated.
