### ISSUE TITLE
Terraform 1.4.4 formula report 1.4.3-dev version in CLI

### ISSUE THREAD

**Issue by nikaro** [Homebrew/homebrew-core#127407]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew gist-logs terraform
Error: No logs.
> brew doctor
Your system is ready to brew.
> brew config
HOMEBREW_VERSION: 4.0.10-119-g931327d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 3 days ago
Core tap JSON: 03 Apr 05:41 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTOREMOVE: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to use the Terraform CLI installed by brew in version 1.4.4, with Terraform Cloud with a constraint on the 1.4.4 version. Doing my job.

### What happened (include all command output)?

Terraform Cloud refuses to take the task because of the CLI version mismatch:
```
> terraform state rm google_compute_instance.tbox_memory
╷
│ Error: Incompatible Terraform version
│
│ The local Terraform version (1.4.3-dev) does not meet the version
│ requirements for remote workspace work/work-dev (~> 1.4.0).
│
│ If you're sure you want to upgrade the state, you can force Terraform to
│ continue using the -ignore-remote-version flag. This may result in an
│ unusable workspace.
╵

Error loading the state: Error checking remote Terraform version

Please ensure that your Terraform state exists and that you've
configured it properly. You can use the "-state" flag to point
Terraform at another state file.

> terraform version
Terraform v1.4.3-dev
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.4.4. You can update by downloading from https://www.terraform.io/downloads.html
```
Indeed with the `-ignore-remote-version` it works.

Tested on two differents MacBook Pro, both M1.

### What did you expect to happen?

I expected to not get an error. And `terraform version` to report `1.4.4` instead of `1.4.3-dev`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install terraform
terraform <whatever-using-terraform-cloud>
```

**Comment by ZhongRuoyu** [comment]
Sorry, but this is not a Homebrew/core issue. Someone has already reported this to Terraform at https://github.com/hashicorp/terraform/issues/32963, and according to https://github.com/hashicorp/terraform/issues/32963#issuecomment-1492577372, this will be fixed in the next release.
