### ISSUE TITLE
brew build binary from source without asking when download updates failed

### ISSUE THREAD

**Issue by gonejack** [Homebrew/homebrew-core#12742]
brew automatically build from source without a confirm, and I would prefer brew to retry download 10 times instead of compiling from source code once, which cost me 17 minutes waiting for my little poor mac mini to finish, this is not cool.

![screenshot 2017-04-22 03 33 29](https://cloud.githubusercontent.com/assets/2720676/25293495/c092aee0-270d-11e7-90ad-f41a51e982e0.png)

**Comment by woodruffw** [comment]
A cursory google suggests that this particular error is a (known) problem with Apple's Secure Transport. 

Unfortunately, there isn't much Homebrew can do about this sort of failure, although `brew install --with-openssl curl` might help.

**Comment by gonejack** [comment]
It would be better if brew ask me to press any key before starting a fallback building, thanks for your suggestion any way.

**Comment by woodruffw** [comment]
> It would be better if brew ask me to press any key before starting a fallback building

This is an design choice, for better or worse - we've intentionally minimized/eliminated interactivity in places where the invocation itself makes intent clear. 

That being said, I think it would be nice to add a flag to `brew install` that does what you want. `--force-bottle` already exists and does something different, so `--no-source-fallback` perhaps? I'll put it on my todo list :smile:

**Comment by JCount** [comment]
This is not really a solution, but you could always simply abort a source build and try again to install from the bottle. An alternative would also be to use `brew fetch` if you are having issues downloading a bottle as part of the install process.

**Comment by gonejack** [comment]
Yes, but since the command executing is make & install, there are possibility of resulting binaries partial installed, which cause more troubles.

**Comment by ilovezfs** [comment]
`brew` deletes everything if the build fails.

**Comment by MikeMcQuaid** [comment]
Passing on this but thanks for the report.
