### ISSUE TITLE
`elan-init` formula for homebrew must also be offered for arm64 architecture

### ISSUE THREAD

**Issue by rami3l** [Homebrew/homebrew-core#127583]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config
HOMEBREW_VERSION: 4.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 4 days ago
Core tap JSON: 05 Apr 02:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: 1337
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
all_proxy: socks5://127.0.0.1:1087
http_proxy: http://127.0.0.1:1087
https_proxy: http://127.0.0.1:1087
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false

> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install `elan-init` on an ARM Mac.

This should be supported for `elan` 1.4.1+ (see https://github.com/leanprover/elan/releases).

### What happened (include all command output)?

```
> brew install elan-init
elan-init: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.
```

### What did you expect to happen?

`elan-init` gets installed normally.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
> brew install elan-init
```

**Comment by SMillerDev** [comment]
Homebrew has no such obligations. https://docs.brew.sh/Updating-Software-in-Homebrew

**Comment by rami3l** [comment]
@SMillerDev Thanks for your timely response! In that case, I'll be glad to propose a PR to remove this restriction.
