### ISSUE TITLE
wg-quick CONFIG_SEARCH_PATHS corrupted by path replacement

### ISSUE THREAD

**Issue by ashokdelphia** [Homebrew/homebrew-core#127520]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config 
HOMEBREW_VERSION: 4.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 4 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5571b522849fff12e41919e6e4b4818c3ff45692
Core tap last commit: 37 minutes ago
Core tap branch: master
Core tap JSON: 04 Apr 14:36 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.4-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install wireguard-tools and use wg-quick.

A colleague ran into a problem where wg-quick failed to find their wireguard config file in `/etc/wireguard`, and after some investigation I believe the problem is with how homebrew replaces strings in the file since the change in #121390.

### What happened (include all command output)?

Using the version in `1.0.20210914_1`:

```
$ sudo wg-quick up wg0
wg-quick: `/usr/local/etc/wireguard/wg0.conf' does not exist
```

```
$ fgrep -n CONFIG_SEARCH_PATHS= $(which wg-quick)
44:CONFIG_SEARCH_PATHS=( /usr/local/etc/wireguard /usr/local/etc/wireguard )
```

Comparing to the previous version (having copied the wg-quick file from each version):

```
$ diff wg-quick-previous-version wg-quick-current-version
44c44
< CONFIG_SEARCH_PATHS=( /etc/wireguard /usr/local/etc/wireguard )
---
> CONFIG_SEARCH_PATHS=( /usr/local/etc/wireguard /usr/local/etc/wireguard )
```

Which is why I believe it is failing to find interface config files in /etc/wireguard.

### What did you expect to happen?

For wg-quick to use a list of search paths, and look in `/etc/wireguard` first, and then in `/usr/local/etc/wireguard`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I had an existing (working) version (1.0.20210914), and I upgraded to 1.0.20210914_1 using 'brew upgrade wireguard-tools'.

The previous version worked, but the new one did not. See the diff above in 'what happened'.
```

**Comment by SMillerDev** [comment]
`/etc` is a protected directory so Homebrew formulae can't install anything there. `/usr/local/etc/wireguard` seems like the correct location to search.

**Comment by ashokdelphia** [comment]
> `/etc` is a protected directory so Homebrew formulae can't install anything there. `/usr/local/etc/wireguard` seems like the correct location to search.

I don't expect the formula to install anything in `/etc/wireguard` but I do expect to be able to use the tool after it's installed (with sudo when needed), and I have existing processes that do expect the config files to be in there.

It looks like the change in #121390 (presumably inadvertently) corrupted that list of search paths, so now it's looking in the same place twice, and not looking in /etc/wireguard at all.

**Comment by carlocab** [comment]
> It looks like the change in #121390 (presumably inadvertently) corrupted that list of search paths, so now it's looking in the same place twice, and not looking in /etc/wireguard at all.

#121390 was very much intentional. But it doesn't hurt to check `/etc/wireguard` first and then Homebrew's `etc` directory (which isn't always `/usr/local/etc`). See #127521.
