### ISSUE TITLE
fcitx-remote-for-osx failed to build on 10.11.5

### ISSUE THREAD

**Issue by ladrift** [Homebrew/homebrew-core#1275]
Build error occurred when I update fcitx-remote-for-osx from 0.2.0 0.1.0
`brew gist-log` output: https://gist.github.com/ladrift/a4a76f447371405907e9970dd8528167

**Comment by ilovezfs** [comment]
I cannot reproduce this issue. What's the output of
```
cd /usr/local
git status
```
and
```
cd /usr/local/Library/Taps/homebrew/homebrew-core
git status
```

**Comment by ladrift** [comment]
After execute `brew update`, both outputs are:
```bash
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```
With the newest build crash log: https://gist.github.com/ladrift/9f415a41f522b0a75c7aaa4d392de419

**Comment by ilovezfs** [comment]
What's the output of `xcode-select -p`?

**Comment by ladrift** [comment]
The error causes seems that wrong usage on `build.py` script without `[im]` command-line argument.
```bash
$ brew upgrade fcitx-remote-for-osx
==> Upgrading 1 outdated package, with result:
fcitx-remote-for-osx 0.1.0
==> Upgrading fcitx-remote-for-osx
==> Downloading https://github.com/CodeFalling/fcitx-remote-for-osx/archive/0.1.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/fcitx-remote-for-osx-0.1.0.tar.gz
==> ./build.py build
Last 15 lines from /Users/ladrift/Library/Logs/Homebrew/fcitx-remote-for-osx/01.build.py:
2016-05-20 17:51:30 +0800

./build.py
build


Traceback (most recent call last):
  File "./build.py", line 59, in <module>
    build(sys.argv[2])
  File "./build.py", line 26, in build
    use_opts = OPTS % (InputMethod[imname], use_path)
KeyError: ''
```

The command execute by `brew` is `./build.py build`, which should be append with `[im]` to specifying an  input method.
According to the file `build.py`: https://github.com/CodeFalling/fcitx-remote-for-osx/blob/master/build.py#L41

**Comment by ladrift** [comment]
```bash
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

**Comment by ilovezfs** [comment]
Please try this:

```
mkdir ~/Documents/homebrew-20160520
sudo mv /usr/local ~/Documents/homebrew-20160520
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install -dvs fcitx-remote-for-osx
```

**Comment by ladrift** [comment]
Thank you so much. I install it without error. But, how can I safely restore my original `/usr/local` back? There are not only `brew`ed things.

**Comment by ilovezfs** [comment]
OK, good. Thank you for trying that. Let's first just reverse it:

```
mkdir ~/Documents/homebrew-empty-fresh-20160520
sudo mv /usr/local ~/Documents/homebrew-empty-fresh-20160520
sudo mv  ~/Documents/homebrew-20160520/local /usr/local
```
Let me know when that's done.

**Comment by ladrift** [comment]
It seems my original homebrew'd things back. And I run `brew install fcitx-remote-for-osx` and succeed!!
Thanks a lot.
Do you need any other informations? I'm glad to cooperate with you. Thanks a lot for your efforts.

**Comment by ilovezfs** [comment]
You're welcome.

That's interesting. I'd have expected it to fail again. `brew list` shows all of your packages now?

**Comment by ladrift** [comment]
Yes, it do show all my familiar packages, but not that sure. But original software like `vim` form `homebrew` is back.

**Comment by ilovezfs** [comment]
```
brew uninstall fcitx-remote-for-osx
brew install --build-from-source --verbose fcitx-remote-for-osx
```

**Comment by ladrift** [comment]
I have built from source and installed it. All come successfully.

**Comment by ilovezfs** [comment]
I cannot argue with success! Let us know if this "comes back" and gives you trouble again.
