### ISSUE TITLE
Brew upgrade hatch failure on OSX ventura 13.34

### ISSUE THREAD

**Issue by DAMisener** [Homebrew/homebrew-core#127511]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
None
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Just performing my daily brew upgrade

### What happened (include all command output)?

➜  trunk git:(master) ✗ brew outdated
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the dimentium/autoraise tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/dimentium/homebrew-autoraise/autoraise.rb:29

hatch (1.6.3_1) < 1.7.0
➜  trunk git:(master) ✗ brew upgrade hatch
==> Upgrading 1 outdated package:
hatch 1.6.3_1 -> 1.7.0
==> Fetching hatch
==> Downloading https://ghcr.io/v2/homebrew/core/hatch/manifests/1.7.0
Already downloaded: /Users/DM/Library/Caches/Homebrew/downloads/a28c3dd0079cf76805c7b8f548cc78c2241b611cb834fd31884bf88f35c97015--hatch-1.7.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/hatch/manifests/1.7.0
######################################################################## 100.0%
Error: Couldn't find manifest matching bottle checksum.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:447:in `github_packages_manifest_resource_tab'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:400:in `fetch_tab'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2633:in `fetch_bottle_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1194:in `fetch'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:73:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:54:in `map'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:54:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:206:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:128:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

### What did you expect to happen?

Not to encounter: Couldn't find manifest matching bottle checksum

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade hatch
```

**Comment by carlocab** [comment]
What is the output of `brew config` and `brew doctor`?

**Comment by carlocab** [comment]
Looks like a problem #127414.

**Comment by carlocab** [comment]
Thanks for the report. This should be fixed by #127555.

**Comment by carlocab** [comment]
We've merged the fix. Try `brew update && brew upgrade hatch` in ~20 minutes (the API is slightly behind the core repo).

**Comment by DAMisener** [comment]
Thanks for such prompt service.  Kudos!!
