### ISSUE TITLE
wxmaxima formula

### ISSUE THREAD

**Issue by iwelch** [Homebrew/homebrew-core#127682]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 35f8763a90eab4203deb3a6ee2503cf0ddfd8c84
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 05 Apr 23:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: ansi
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.VByQHx7SJV/org.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: N/A
Xcode: 14.3
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

run wxmaxima.

[1] the brew installation message is probably outdated.  in the settings, there is no such location to enter.

[2] there are many error messages on startup:

```
17:54:23: Font file "/opt/homebrew/Cellar/wxmaxima/23.03.0/share/wxMaxima/fonts/LibertinusKeyboard-Regular.otf" cannot be used as it is not inside the font directory "/opt/homebrew/Cellar/wxmaxima/23.03.0/wxmaxima.app/Contents/Resources/Fonts".
17:54:23: Font file "share/wxMaxima/fonts/LibertinusKeyboard-Regular.otf" cannot be used as it is not inside the font directory "/opt/homebrew/Cellar/wxmaxima/23.03.0/wxmaxima.app/Contents/Resources/Fonts".
17:54:23: Font file "/opt/homebrew/Cellar/wxmaxima/23.03.0/share/wxMaxima/fonts/LibertinusMath-Regular.otf" cannot be used as it is not inside the font directory "/opt/homebrew/Cellar/wxmaxima/23.03.0/wxmaxima.app/Contents/Resources/Fonts".
```

[3] there is something wrong with "Settings".  There should be a pane on the left that shows all sorts of other setting options.

[4] would it make sense to link wxmaxima and maxima into the brew path?

I have tried this on three different m1 macs.  all the same symptoms.  (I also removed the .maxima directory and restarted.)

### What happened (include all command output)?

errors, missing features

### What did you expect to happen?

no errors.  full settings.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install wxmaxima
/opt/homebrew/Cellar/wxmaxima/*/wxmaxima.app
```

**Comment by iwelch** [comment]
from the wxmaxima site itself:

```
  * wxMaxima has a graphical user interface of Maxima with wxWidgets.
    If you would like to use wxMaxima, you have to install jsMath TeX fonts (TeX-fonts-10.zip).
      <https://www.math.union.edu/~dpvc/jsMath/download/jsMath-fonts.html>
    How to launch wxMaxima.app: use Launchpad or Finder.

    Website: <https://wxmaxima-developers.github.io/wxmaxima/>
```

this needs to be a prereq.  incidentally, they are 23.04.0.  23.03.0 is outdated and buggy on other fronts.  maybe 23.04.0 fixes some of them.

**Comment by chenrui333** [comment]
I created a PR to bump the formula to the latest.
