### ISSUE TITLE
problem with latest dnstwist 20230402

### ISSUE THREAD

**Issue by luckman212** [Homebrew/homebrew-core#127730]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew update && brew upgrade
Already up-to-date.
==> Upgrading 1 outdated package:
dnstwist 20221213 -> 20230402
==> Fetching dnstwist
==> Downloading https://ghcr.io/v2/homebrew/core/dnstwist/manifests/20230402
curl: (22) The requested URL returned error: 404

Error: dnstwist: Failed to download resource "dnstwist_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/dnstwist/manifests/20230402
```

```
$ brew config
HOMEBREW_VERSION: 4.0.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 931327df1f30a3a5b1aa07657c0d1070e61988f9
Last commit: 6 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e07fb8e77b1f5c047369a423a7ddc38d10bd883d
Core tap last commit: 24 hours ago
Core tap branch: master
Core tap JSON: 06 Apr 14:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_AUTO_UPDATE_SECS: 600
HOMEBREW_AUTO_UPDATE_SECS: 14400
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: editor_subl
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_TOKEN: set
HOMEBREW_GITHUB_PACKAGES_USER: luckman212
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_TEMP: /private/tmp/brew
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Update to latest ver of `dnstwist`

### What happened (include all command output)?

see above -- `Error: dnstwist: Failed to download resource "dnstwist_bottle_manifest"`

### What did you expect to happen?

Install `dnstwist 20230402`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew reinstall --force dnstwist
==> Fetching dnstwist
==> Downloading https://ghcr.io/v2/homebrew/core/dnstwist/manifests/20230402
curl: (22) The requested URL returned error: 404

Error: Failed to download resource "dnstwist_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/dnstwist/manifests/20230402
```

**Comment by ZhongRuoyu** [comment]
Thanks for reporting the issue. This is because #127342 was accidentally merged without bottles published. I have dispatched a workflow to rebuild the bottles and publish them.

**Comment by luckman212** [comment]
I think there's a problem with this test:

```sh
dnstwist -rw --lsh ssdeep brew.sh 2>&1
```

The `--lsh` long flag does not appear valid to me, from reading the helptext.

**Comment by ZhongRuoyu** [comment]
> The `--lsh` long flag does not appear valid to me, from reading the helptext.

Could you elaborate on that? It seems okay to me:


```python
	parser.add_argument('--lsh', type=str, metavar='LSH', nargs='?', const='ssdeep',
		help='Evaluate web page similarity with LSH algorithm: ssdeep, tlsh (default: ssdeep)')
```

https://github.com/elceef/dnstwist/blob/f1f7744f06b7ce9892e52b80e8ac26a171fb85c7/dnstwist.py#L970-L971

**Comment by ZhongRuoyu** [comment]
I'm guessing it was network flakiness, because all the jobs in #127734 passed. Let me try rerunning the workflow just once more.

**Comment by luckman212** [comment]
@ZhongRuoyu Thank you. I didn't actually look at the Python code, just ran `dnstwist -h` and didn't see an `--lsh` flag. But yes, seems it's a shortcut.

**Comment by ZhongRuoyu** [comment]
The bottles should be published now. Please give it about half an hour and try installing `dnstwist` again.

Or (since I noticed that you have recently updated your `homebrew/core` tap), the following should work too:

```
export HOMEBREW_NO_INSTALL_FROM_API=1
brew update
brew upgrade dnstwist
```

**Comment by luckman212** [comment]
Everything is good now! 👍
