### ISSUE TITLE
feh ERROR: Can't open X display. It *is* running, yeah?

### ISSUE THREAD

**Issue by WatermelonDriveway** [Homebrew/homebrew-core#12786]
Not entirely sure what this means.  I have a script that opens album art using feh on song change, but after doing a system restore and reinstalling xquartz and feh, I'm now getting this error.

This occurs when I just try to simply run 'feh /path/to/image'.  If I run this in xquartz it will work, but in iTerm I get "feh ERROR: Can't open X display. It *is* running, yeah?".

I've noticed that I no longer have to tap into x11, I don't think that was the case when I installed feh the last few times.

Sorry if this is the wrong place to post this issue.  If it is, could you redirect me somewhere better?

Thanks

**Comment by ilovezfs** [comment]
Does it work in Terminal.app?

**Comment by WatermelonDriveway** [comment]
I could have sworn I posted in here last night that I was able to fix it by doing 'echo $DISPLAY' in xquartz, and setting 'export $DISPLAY='whatever/xquartz/spit/out' in iTerm.

It works in Terminal.app now, but it didn't before I used the command above.
