### ISSUE TITLE
freerdp install fails to communicate an external prerequisite (xserver)

### ISSUE THREAD

**Issue by systemresearch** [Homebrew/homebrew-core#128321]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 4.0.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b60fcf7ac3f82fa589a64091376d0663262f8c6
Last commit: 27 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8dff624502c3d11da81c21bf7e53ca3d1e5d4205
Core tap last commit: 8 weeks ago
Core tap branch: master
Core tap JSON: 13 Apr 21:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.l0owncHHxF/org.xquartz:0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false

brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install and use `freerdp` (`xfreerdp`) on a fresh installation.

### What happened (include all command output)?

This was my experience:

``` sh
brew install freerdp
# ==> Fetching freerdp
# ==> Downloading …
# ==> Pouring freerdp--2.10.0.arm64_ventura.bottle.tar.gz
# 🍺  /opt/homebrew/Cellar/freerdp/2.10.0: 258 files, 5.2MB
# ==> Running `brew cleanup freerdp`...
# Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
# Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

### simple install check
which -a xfreerdp 
# /opt/homebrew/bin/xfreerdp

### simple version check
xfreerdp --version
# [15:19:10:365] [8587:faee9b40] [ERROR][com.freerdp.client.x11] 
#     - failed to open display: 
# - Please check that the $DISPLAY environment variable is properly set.
```

I am not alone. Several others have had this same _"What am I missing??"_ experience due to lack of communication of external prequisites.

* <https://github.com/FreeRDP/FreeRDP/issues/8764>
* <https://github.com/FreeRDP/FreeRDP/issues/7420>
* <https://github.com/FreeRDP/FreeRDP/issues/7354>
* <https://github.com/FreeRDP/FreeRDP/issues/7129>

### What did you expect to happen?

I expected the install formula [freerdp.rb](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/freerdp.rb) to provide a caveat of the external requirement for an `XServer` to be installed:

``` rb
  def caveats
    # on_linux also applies Windows Subsystem for Linux (WSL) 
    on_linux do
      <<~EOS
        xfreerdp is an X11 application that requires an XServer be installed 
        and running. Lack of a running XServer will cause a "$DISPLAY" error.
      EOS
    end
    on_macos do
      <<~EOS
        xfreerdp is an X11 application that requires an XServer be installed 
        and running. Lack of a running XServer will cause a "$DISPLAY" error.

        XQuartz provides an XServer for macOS. The XQuartz can be installed 
        as a package from www.xquartz.org or as a Homebrew cask:
          brew install --cask xquartz
      EOS
    end
  end
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run any one of `brew info freerdp`, `brew install freerdp`, `brew reinstall freerdp`.

The resulting output in each case will *not* advise of the external prerequisite requirement for an installed and running Xserver to be able to use the xfreerdp X11 application.
```

**Comment by SMillerDev** [comment]
Could you make a pull request to add the changes you're suggesting here?

**Comment by systemresearch** [comment]
@SMillerDev [Pull Request "freerdp: add external requirement caveat #128457"](https://github.com/Homebrew/homebrew-core/pull/128457) has been added.

**Comment by systemresearch** [comment]
PR was merged.
