### ISSUE TITLE
Rebuild proof-general bottle against emacs-25.2

### ISSUE THREAD

**Issue by glguy** [Homebrew/homebrew-core#12834]
Emacs was recently updated to 25.2 in homebrew. The existing proof-general bottle is built against emacs-25.1. This generates a warning message when starting proof-general. I was able to resolve this warning by installing the proof-general formula from source using homebrew.

It would be good to rebuild the proof-general bottle against the new version of emacs.

**Comment by dunn** [comment]
If you could open a PR, that'd be great!  All that would be needed is a `revision 1` below the `sha256` line.
