### ISSUE TITLE
docker-completion v17.04.0-ce SHA256 Mismatch

### ISSUE THREAD

**Issue by Cinal** [Homebrew/homebrew-core#12833]
I have no idea why checksum for docker-completion v17.04.0-ce is different than from official. For me this hash in homebrew was wrong at the beginning.

Get error during instal last version:

⇒  brew --version
Homebrew 1.1.13-110-g581e3b79
Homebrew/homebrew-core (git revision 5e6869; last commit 2017-04-24)

⇒  brew install docker-completion
==> Using the sandbox
==> Downloading https://github.com/docker/docker/archive/v17.04.0-ce.tar.gz
Already downloaded: /Users/qwerty/Library/Caches/Homebrew/docker-completion-17.04.0.tar.gz
Error: SHA256 mismatch
Expected: b6ee0aa93ecea44e956d3627907e10557b3ec37d13ddfb40e436656e5037c640
Actual: 76e84fbb7b5f1077f424ff40ddd14c98247f5aa3f49ad6412eede5a8cb11a29e
Archive: /Users/qwerty/Library/Caches/Homebrew/docker-completion-17.04.0.tar.gz
To retry an incomplete download, remove the file above.

Thanks

**Comment by MikeMcQuaid** [comment]
Please file this to docker-completion rather than Homebrew, thanks!

**Comment by ilovezfs** [comment]
Actually, as @neutric pointed out to me on Slack, this is cased by the upstream organization and repository both just being renamed "moby."
