### ISSUE TITLE
zig formula needs to be updated (0.10.1 to 0.11.0)

### ISSUE THREAD

**Issue by ksylvan** [Homebrew/homebrew-core#128545]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://github.com/Homebrew/homebrew-core/blob/master/Formula/zig.rb is installing 0.10.1 and the latest version here is 0.11.0:

https://ziglang.org/download/
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use Zig in VSCode

### What happened (include all command output)?

VSCode installed the zig language server, which was based on 0.11.0 and that popped up a warning (which is why I saw that zig was a version back)

### What did you expect to happen?

zig and VSCode zls should be on the same version. :-)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install zig
zig version
0.10.1
```

**Comment by carlocab** [comment]
We'll review a pull request for this.
