### ISSUE TITLE
mtr build: setcap: command not found

### ISSUE THREAD

**Issue by april4** [Homebrew/homebrew-core#12860]
Homebrew 1.1.13
brew install -v --build-from-source mtr

setcap cap_net_raw+ep /usr/local/Cellar/mtr/0.87/sbin/mtr
/bin/sh: setcap: command not found

The setcap command doesn't exist in OSX

**Comment by bfontaine** [comment]
> To help us debug your issue please explain:
> - What you were trying to do (and why)
> - What happened (include command output)
> - What you expected to happen
> - Step-by-step reproduction instructions (by running `brew install` commands)
>
> **Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**
