### ISSUE TITLE
"ERR_INVALID_THIS" on "pnpm install" in Node 20

### ISSUE THREAD

**Issue by CamilleHbp** [Homebrew/homebrew-core#128755]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

The `pnpm` brew package is unusable with Node 20. The bug is referenced in this [issue](https://github.com/pnpm/pnpm/issues/6424), and already merged.

Could we update the formulae in Homebrew? Thank you! :)

Use pnpm to install packages after update.

### What happened (include all command output)?

The command did not work : `GET https://nodejs.org/download/release/index.json error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.`

### What did you expect to happen?

I expected `pnpm` to use the updated Node to install my packages.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew update && brew upgrade && brew cleanup`

Node should be updated to version 20.

`pnpm install`

The command should fail with the previous output.
```

**Comment by CamilleHbp** [comment]
Hello @SMillerDev 👋 :)

 I don't know what you mean by open. The issue is closed and `pnpm` was updated to `8.3.1` to resolve this issue. Brew is still using `8.3.0`. How could I ask for an update if not in the brew tool?

**Comment by carlocab** [comment]
Should be fixed by #128758.

**Comment by SMillerDev** [comment]
When you opened this issue, the issue you referenced was still open.
<img width="382" alt="Screenshot 2023-04-19 at 15 45 54" src="https://user-images.githubusercontent.com/1484494/233094901-62790a54-0024-443c-96f8-82365e3ffd52.png">

**Comment by ZhongRuoyu** [comment]
#128758 is merged now. Please try:

```
brew update
brew upgrade pnpm
```

**Comment by CamilleHbp** [comment]
> When you opened this issue, the issue you referenced was still open. <img alt="Screenshot 2023-04-19 at 15 45 54" width="382" src="https://user-images.githubusercontent.com/1484494/233094901-62790a54-0024-443c-96f8-82365e3ffd52.png">

Oh sorry, I thought is was closed since the fix was already merged. My bad! Thank you very much for your response! :)

> #128758 is merged now. Please try:
> 
> ```
> brew update
> brew upgrade pnpm
> ```

I will do, thank you very much! 🙏
