### ISSUE TITLE
vim fails to build on 10.11.4

### ISSUE THREAD

**Issue by Numbermaniac** [Homebrew/homebrew-core#1288]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

`brew install vim` returns an error when building about a missing architecture or something. I'm not sure if it is related to https://github.com/Homebrew/homebrew-core/issues/1165 by any chance.

https://gist.github.com/anonymous/c38757d16077d1083f115ab7073cbf72

**Comment by DomT4** [comment]
```
ld: warning: ignoring file /Library/Frameworks/Python.framework/Python, missing required architecture x86_64 in file /Library/Frameworks/Python.framework/Python (2 slices)
Undefined symbols for architecture x86_64:
```

That's an unusual error. As far as I remember Python upstream offer two `.pkg`s for OS X, one of which is built for the old PPC & i386 arches, and one built for x86_64 & i386. Any chance you accidentally installed the one wrong or something?

**Comment by DomT4** [comment]
You should be able to check by running:

```
file /Library/Frameworks/Python.framework/Python
```

**Comment by Numbermaniac** [comment]
```
/Library/Frameworks/Python.framework/Python: Mach-O universal binary with 2 architectures
/Library/Frameworks/Python.framework/Python (for architecture ppc7400):	Mach-O dynamically linked shared library ppc
/Library/Frameworks/Python.framework/Python (for architecture i386):	Mach-O dynamically linked shared library i386
```

Wow you're right, looks like I have. Installed the other one now, so it says i386 and x86_64. That would explain why another of my Python programs wasn't working either. Thank you!!

**Comment by DomT4** [comment]
No worries at all. Glad things are working as-expected again 😃
