### ISSUE TITLE
Installing poppler doesn't include the python bindings

### ISSUE THREAD

**Issue by AlexanderWillner** [Homebrew/homebrew-core#12895]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) ```installing poppler python bindings```
- What happened (include command output) 
```
$ brew install poppler && python -c 'import poppler'
Warning: poppler-0.54.0 already installed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named poppler
```
- What you expected to happen ```no python error```
- Step-by-step reproduction instructions (by running `brew install` commands) ```see above```

**Comment by MikeMcQuaid** [comment]
We'd review a pull request to add a `with-python` option for these. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
