### ISSUE TITLE
Error while installing Home brew

### ISSUE THREAD

**Issue by Utkarshagupta** [Homebrew/homebrew-core#1290]
I am working on OS x V 10.11.3 and Xcode 7.0 and trying to run command to install homebrew. 

I am getting the below error while installing:

sudo: no tty present and no askpass program specified
Failed during: /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew

Any help will be appreciated.

![screen shot 2016-05-19 at 6 48 56 pm](https://cloud.githubusercontent.com/assets/10269638/15394760/642ea958-1df2-11e6-9e1c-9135e822a0a0.png)

**Comment by mikemcquaid** [comment]
Please report this to Cakebrew.
