### ISSUE TITLE
g++-11: The build tool has reset ENV; --env=std required.

### ISSUE THREAD

**Issue by ilya-lavrenov** [Homebrew/homebrew-core#129340]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
linuxbrew@9c468196dcf2:/tmp/openvino-20230425-59105-16kykzy/openvino-5533de5dd87b0630daf40be89aa93a6f1db0754e/openvino_build$ brew config
HOMEBREW_VERSION: 4.0.15-49-g3b92bb9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3b92bb9da59e5b214d1682e3bafec27e73ced716
Last commit: 8 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 50309df44d42de570fb2be02e3d4d1294ed63e9c
Core tap last commit: 8 hours ago
Core tap branch: master
Core tap JSON: 25 Apr 22:51 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 72
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 72-core 64-bit haswell
Clang: N/A
Git: 2.40.0 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.0-69-generic x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Building `openvino` formula from sources using `brew install -s openvino` to check latest changes in OpenVINO product

### What happened (include all command output)?

[ 30%] Linking CXX shared library /tmp/openvino-20230425-59105-16kykzy/openvino-5533de5dd87b0630daf40be89aa93a6f1db0754e/bin/intel64/Release/libopenvino_onnx_frontend.so
g++-11: The build tool has reset ENV; --env=std required.
make[2]: *** [src/frontends/onnx/frontend/CMakeFiles/openvino_onnx_frontend.dir/build.make:2585: /tmp/openvino-20230425-59105-16kykzy/openvino-5533de5dd87b0630daf40be89aa93a6f1db0754e/bin/intel64/Release/libopenvino_onnx_frontend.so.2023.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:2252: src/frontends/onnx/frontend/CMakeFiles/openvino_onnx_frontend.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

### What did you expect to happen?

I expect the build / linkage works without any issues like `g++-11: The build tool has reset ENV; --env=std required.`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
docker pull ghcr.io/homebrew/ubuntu22.04:master
brew tap ilya-lavrenov/core
brew install -s ilya-lavrenov/core/openvino
```

**Comment by ilya-lavrenov** [comment]
Related issue (brew is also mentioned there):
- https://github.com/souffle-lang/souffle/issues/2325
- https://github.com/ska-sa/homebrew-tap/issues/20
- https://github.com/Homebrew/legacy-homebrew/issues/49001

But no clear answer what happened there

**Comment by carlocab** [comment]
This means you need to specify
```ruby
env :std
```
in your formula for your build to work.

Note that using `env :std` is not allowed in Homebrew/core, so you'll need to host your formula in an external tap. If you prefer not to do that, you need to work out how/why the build resets the environment before calling the compiler.

**Comment by ilya-lavrenov** [comment]
>  the build resets the environment before calling the compiler.

Do we have more details what is part of _environment_?

**Comment by carlocab** [comment]
The environment means environment variables.

**Comment by ilya-lavrenov** [comment]
In understand, but which variables are supposed here?

**Comment by carlocab** [comment]
There are many. Any environment variable that starts with `HOMEBREW_`. I don't have an exhaustive list -- any `HOMEBREW_` variable references in Homebrew/brew is a candidate, but that might not be all of them given the behaviour of `Homebrew::EnvConfig`.

**Comment by ilya-lavrenov** [comment]
Just past solution to my problem: when the brew formula build has failed locally from sources, I came to build folder and tried to reproduce the build error and all env vars are not available in this case. The proper way is to build with `--debug` option, which in case of error will suggest to open shell with all env vars available.
