### ISSUE TITLE
GIT

### ISSUE THREAD

**Issue by ullolina** [Homebrew/homebrew-core#129302]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I NEED THE APP, ONLY FOR ONE TP
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

CODE

### What happened (include all command output)?

NOTHING

### What did you expect to happen?

WORK

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I DONT KNOW
```

**Comment by ZhongRuoyu** [comment]
Please provide a meaningful description to the issue and provide all the necessary inputs.

**Comment by ullolina** [comment]
I have a Macbookpro and it won't let me install Git.  , I did 10 thousand
juggling and none worked

**Comment by ZhongRuoyu** [comment]
To install Git (via Command Line Tools), please open a terminal, and run:

```
xcode-select --install
```

To install Homebrew, please follow the instructions on https://brew.sh/. Run this in your terminal and follow the instructions on screen:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by ullolina** [comment]
I have tried to do it , but I can not identify the step that is wrong , and it is very likely that _brew_[](url)
@ZhongRuoyu  Thank you very much for helping me,,, infinite gratitude... I'm new to this... and I feel a little disoriented... I also opened this link,,, but it didn't work. https://www.youtube.com/watch?v=Jj8y6sNITqI&feature=youtu.be

**Comment by ullolina** [comment]
<img width="630" alt="Captura de pantalla 2023-04-26 a la(s) 04 35 19" src="https://user-images.githubusercontent.com/128336737/234537350-d9dd7cb7-9d70-4a54-b72f-4f06243a0c77.png">

### THE MESSAGE SAYS THE INSTALLATION COMPLETED SUCCESSFULLY.......BUT GIT NEVER SHOWS UP...I'M STUNNED

**Comment by SMillerDev** [comment]
How is this installer related to brew?

**Comment by ullolina** [comment]
> I have a Macbookpro and it won't let me install Git. , I did 10 thousand juggling and none worked

### **the same thing happened to me...**

> What do you type in the terminal when it fails?

what I do is press click and control at the same time and open the app anyway... but it appears blind

**Comment by ullolina** [comment]
@SMillerDev  What do you think I should do from the beginning? to start from [scratch?[])

**Comment by ullolina** [comment]
![THIS](https://user-images.githubusercontent.com/128336737/234548770-4e33b7d7-af98-4354-be47-25d6bd13bff6.jpeg)

**Comment by ullolina** [comment]
> How is this installer related to brew?

THAT REALLY CAME OUT WHEN I CLICKED ON THE GIT FOLDER
<img width="218" alt="Captura de pantalla 2023-04-26 a la(s) 07 35 20" src="https://user-images.githubusercontent.com/128336737/234550166-5436c352-e4f7-4e76-87a6-0ce0921b0404.png">
