### ISSUE TITLE
`mujs` has incorrect prefix in pkg-config file on ARM Mac

### ISSUE THREAD

**Issue by uiryuu** [Homebrew/homebrew-core#129575]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.15-95-g7386d4e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7386d4e407de293e75f41b627a2e41a268099d8f
Last commit: 7 hours ago
Core tap JSON: 28 Apr 00:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false


Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to compile mpv from source. I'm expecting I've installed all required dependencies from homebrew since I've installed mpv via homebrew before.

### What happened (include all command output)?

When I ran `meson compile -C build`, it reported `mujs.h not found`.

```
../player/javascript.c:28:10: fatal error: 'mujs.h' file not found
#include <mujs.h>
         ^~~~~~~~
1 error generated.
```

I then checked `/opt/homebrew/Cellar/mujs/1.3.3/lib/pkgconfig/mujs.pc`, the content is:

```
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.3
Cflags: -I/usr/local/include
Libs: -L/usr/local/lib -lmujs
Libs.private: -lm
```
It seems that the prefix is wrong.

### What did you expect to happen?

The compiler should be able to find the header of mujs.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mpv
cd /source/of/mpv
meson setup build
meson compile -C build

Or try to compile anything that depends on mujs on an ARM Mac should reproduce the issue
```

**Comment by carlocab** [comment]
This was fixed in 5a5d152daffb25e32a715d3b4fc7d6a221cf93bd. Do
```
brew update && brew reinstall mujs
```
