### ISSUE TITLE
F3D is not correctly installed

### ISSUE THREAD

**Issue by mwestphal** [Homebrew/homebrew-core#129767]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I'm not a brew user, I'm a developper of the F3D application
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm looking at the update of the F3D package to 2.0.0 and it looks like you do not install it correctly

### What happened (include all command output)?

You are only installing using `make install` but missed to install optional component, especially the `configuration` component, which means that F3D is very barebone without any installed configuration.

The `sdk` component could also be installed in order to provide the libf3d.

### What did you expect to happen?

Correct configuration and sdk installed

More information here: https://github.com/f3d-app/f3d/releases/tag/v2.0.0

And here: https://f3d.app/doc/dev/BUILD.html#installing

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
not a brew user, but I suppose something like that:


brew install f3d
f3d /path/to/stl
```

resulting f3d windows contains only the stl instead of the whole UI of F3D with the grid and axis.
```

**Comment by mwestphal** [comment]
I've left a comment on the PR updating F3D but no answers: https://github.com/Homebrew/homebrew-core/pull/128873

**Comment by mwestphal** [comment]
@SMillerDev @p-linnane

**Comment by fxcoudert** [comment]
We run cmake with:

```
      -DF3D_MACOS_BUNDLE:BOOL=OFF
      -DBUILD_SHARED_LIBS:BOOL=ON
      -DBUILD_TESTING:BOOL=OFF
      -DF3D_INSTALL_DEFAULT_CONFIGURATION_FILE:BOOL=ON
      -DF3D_MODULE_ALEMBIC:BOOL=ON
      -DF3D_MODULE_ASSIMP:BOOL=ON
      -DF3D_MODULE_OCCT:BOOL=ON
      -DCMAKE_INSTALL_RPATH:STRING=#{rpath}
```

then `cmake --build` and `cmake --install`. Does `F3D_INSTALL_DEFAULT_CONFIGURATION_FILE` not actually install the configuration file?

The general feeling in Homebrew is that we cannot be experts of the 5000 formulas we distribute. We try to follow, as much as possible, upstream default choices, given that upstream developers know best. In that case, if the optional packages are optional, there probably is a good reason? It seems weird to call “optional” a package without which the software does not actually work.

**Comment by fxcoudert** [comment]
From https://f3d.app/doc/dev/BUILD.html:

> Optional components can be installed by specifying the component name:
> cmake --install ${your_build_dir} --component ${component_name}
>
> Here is the list of the optional components you can install:
>
> - mimetypes: Install plugins mimetype XML files for integration with Freedesktop (Linux only).
> - configuration: Install default configuration files , config and thumbnail.
> - sdk: Install the [libf3d](https://f3d.app/doc/libf3d/README_LIBF3D.html) SDK.

But we didn't install those optional parts before, and had no user request for them.

**Comment by mwestphal** [comment]
Hi @fxcoudert 

`F3D_INSTALL_DEFAULT_CONFIGURATION_FILE` does not exist anymore and waws replaced by the optional `configuration` component.

As per the release notes:

> Removed most of F3D_INSTALL_ options with the switch to a component-based approach, see the doc

`mimetypes` is not needed on your side, it is related to the mime database. https://linux.die.net/man/1/update-mime-database

`sdk` is indeed optional but let user compile against the libf3d, which was only added in F3D 1.3: https://f3d.app/doc/libf3d/README_LIBF3D.html

> We try to follow, as much as possible, upstream default choices, given that upstream developers know best.

Well, I'm one of the upstream developer, you can take a look at my profile :)

> In that case, if the optional packages are optional, there probably is a good reason? It seems weird to call “optional” a package without which the software does not actually work.

Well, F3D **can** be used without configuration files and we do not want to force them on anyone, as some people may want to distribute their own configuration files. However, without any config file, the F3D experience is very barebone and require standard user to create their own config file to be able to use F3D through brew is a bit much.

Thanks for packaging F3D btw !

**Comment by SMillerDev** [comment]
> Well, I'm one of the upstream developer, you can take a look at my profile

So you could change the defaults to be more convenient 

> Well, F3D can be used without configuration files and we do not want to force them on anyone, as some people may want to distribute their own configuration files. However, without any config file, the F3D experience is very barebone and require standard user to create their own config file to be able to use F3D through brew is a bit much.

Sounds like this is better suited as an opt-out from upstream so brew automatically does the right thing and people with strong opinions about config files have a means to enforce those.

**Comment by mwestphal** [comment]
You are welcome to open an issue on F3D if you think that an optional cmake component is not the right way to handle this: https://github.com/f3d-app/f3d/issues

BTW it was optional before, it was just handled differently using a CMake option.

In any case, current package (2.0.0) do not behave as previous package (1.3) because you are using an outdate cmake option instead of installing an optional cmake component.

**Comment by mwestphal** [comment]
BTW I just realized that the cmake options for the plugins are not correct either, but this is the case

`F3D_MODULE_` is not `F3D_PLUGIN_BUILD_`
