### ISSUE TITLE
brew upgrade flow - Does not update to 0.45.0 (Keeps old version 0.44.1)

### ISSUE THREAD

**Issue by petersuwara** [Homebrew/homebrew-core#12975]
# Please always follow these steps:
- [X] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Installing latest version of flow 0.45.0

- What happened (include command output)
DevMachine:testscreens piotrsuwara$ brew upgrade flow
Error: flow 0.44.1 already installed

- What you expected to happen
Expected to have latest version of flow, 0.45.0 installed.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew upgrade flow

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

`Error: No logs.
DevMachine:testscreens piotrsuwara$ brew config
HOMEBREW_VERSION: 1.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f6dc4c93b96abd528c3a0a808a5ca5a795c7f3
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 55498e05d32954a8f737b16a17236d0cd17f8dd4
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.3.2
CLT: N/A
X11: N/A`

**Comment by MikeMcQuaid** [comment]
This is the latest version if Homebrew and someone will need to update it. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
