### ISSUE TITLE
All services have the issue: Formula `any name` has not implemented #plist, #service or installed a locatable service file

### ISSUE THREAD

**Issue by ConstantinCezarBegu** [Homebrew/homebrew-core#129997]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
COMMAND: brew config
HOMEBREW_VERSION: 4.0.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01e0c20d01c6aab28d844280d130f0e745e2ddd9
Last commit: 2 days ago
Core tap JSON: 02 May 20:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false

COMMAND: brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to run: brew services start yabai 
OR
brew services start skhd 

### What happened (include all command output)?

Error: Formula `yabai` has not implemented #plist, #service or installed a locatable service file
Error: Formula `skhd` has not implemented #plist, #service or installed a locatable service file

### What did you expect to happen?

The services should run.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Install brew.
install yabai.
Create config for yabai.
Start yabai.

Error as mentioned above.
```

**Comment by SMillerDev** [comment]
Neither of those exist in Homebrew/core so we can't help you there

**Comment by ConstantinCezarBegu** [comment]
got them using brew install koekeishiya/formulae/yabai
 
 Is there anything I can do to get this to work? 
 I just got a fresh install of macOS hoping that this will work.
 
 same issue happens. What can I do to get the service to start, who can I contact ?

**Comment by carlocab** [comment]
Try https://github.com/koekeishiya/homebrew-formulae.

**Comment by gromgit** [comment]
> What can I do to get the service to start, who can I contact ?

Assuming you didn't specify a custom URL for the tap, `koekeishiya/formulae` maps to the GitHub project at `https://github.com/koekeishiya/homebrew-formulae`. You might want to raise an issue there.

**Comment by ShahriarDhruvo** [comment]
@ConstantinCezarBegu some other people including me is facing this issue now too. Maybe you should check this link for more update: https://github.com/koekeishiya/homebrew-formulae/issues/36
