### ISSUE TITLE
aescrypt form conflict?

### ISSUE THREAD

**Issue by featdd** [Homebrew/homebrew-core#1300]
hi,

I use [this aescrypt](https://www.aescrypt.com/) instead of the given by homebrew.
Which is the "correct" or would there be a conflict adding the linked aescrypt?

**Comment by DomT4** [comment]
That version of `aescrypt` is already available in Homebrew, via the `aescrypt-packetizer` [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aescrypt-packetizer.rb) 😃

**Comment by featdd** [comment]
Ah thx, sry for the unnecessary issue
