### ISSUE TITLE
Zig HEAD installation on Ventura not working

### ISSUE THREAD

**Issue by sbbddz** [Homebrew/homebrew-core#130154]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`$ brew config`

HOMEBREW_VERSION: 4.0.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01e0c20d01c6aab28d844280d130f0e745e2ddd9
Last commit: 4 days ago
Core tap JSON: 04 May 16:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/nvim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

`brew doctor`

Your system is ready to brew
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Installing zig from HEAD

### What happened (include all command output)?

When installing dependencies, mpdecimal seems to break the installation

### What did you expect to happen?

Zig to be installed with HEAD

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install zig --HEAD

On macos Ventura.

Seems in the past existed issues with bottling and Ventura, but for me that doesn't seem related.
Sorry if I was missing something, checked issue search and didn't found something related.
```

**Comment by fxcoudert** [comment]
This should be reported upstream to the zig project. Because development is on-going, HEAD builds can be broken at any time, and we have no control.

**Comment by sbbddz** [comment]
Ok, sorry for that, anyways, this section of the install bothers me:

`Error: No such file or directory @ rb_sysopen - /Users/samuel/Library/Caches/Homebrew/downloads/6bf6539627b31c17765f4bcfbe8be8996f3505d3342804531f114c13e64a5a9e--mpdecimal--2.5.1.arm64_ventura.bottle.tar.gz`

as this doesn't seem related to zig itself, that was what brought me here.

**Comment by fxcoudert** [comment]
Ah, that is weird, for sure. What happens if you run `brew fetch mpdecimal`? Then `brew install mpdecimal`?

**Comment by sbbddz** [comment]
`
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
Already downloaded: /Users/samuel/Library/Caches/Homebrew/downloads/f367c2ee08c56b88be0662703a8e4275f8657608a268c8c44e845154b0cea543--mpdecimal-2.5.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:5b1c62c08b42feb6e48c461a9de4751803f3ccc768
Already downloaded: /Users/samuel/Library/Caches/Homebrew/downloads/6bf6539627b31c17765f4bcfbe8be8996f3505d3342804531f114c13e64a5a9e--mpdecimal--2.5.1.arm64_ventura.bottle.tar.gz
SHA256: 5b1c62c08b42feb6e48c461a9de4751803f3ccc76830213a517f0905178dbbef
Warning: mpdecimal 2.5.1 is already installed and up-to-date.
To reinstall 2.5.1, run:
  brew reinstall mpdecimal
`

After that still doesn't work. Seems weird.

_Also, out of the topic of this issue, but maybe related, when doing --HEAD should fetch llvm@16 but is still fetching llvm@15, thing that should be fixed with #128078_

**Comment by sbbddz** [comment]
Any news on this issue

**Comment by gromgit** [comment]
From your previous run:
>```
> To reinstall 2.5.1, run: brew reinstall mpdecimal
>```
Did you try this?

**Comment by sbbddz** [comment]
Yes of course!

Also in the edit I mention another package was failing after trying that. Seems weird.

**Comment by gromgit** [comment]
What's the output of:
```
HOMEBREW_NO_INSTALL_FROM_API=1 brew install zig --HEAD
```
?

**Comment by sbbddz** [comment]
Hi, sorry for the delay in answering

Apparently seems fixed using that var.
Right now there exists problems but with the compilation of Zig itself:

```
error: the following build command failed with exit code 1:
/private/tmp/zig-20230508-83362-v675ib/zig-cache/o/74442718537d668ba714f0deceba69d6/build /private/tmp/zig-20230508-83362-v675ib/build/zig2 /private/tmp/zig-20230508-83362-v675ib /private/tmp/zig-20230508-83362-v675ib/zig-cache /private/tmp/zig-20230508-83362-v675ib/.brew_home/.cache/zig --prefix /tmp/zig-20230508-83362-v675ib/build/stage3 --zig-lib-dir /tmp/zig-20230508-83362-v675ib/lib -Dconfig_h=/tmp/zig-20230508-83362-v675ib/build/config.h -Denable-llvm -Doptimize=ReleaseFast -Dstrip -Dtarget=native -Dcpu=native -Dversion-string=0.11.0-dev.3009+b18b4db70
make[2]: *** [stage3/bin/zig] Error 1
make[2]: *** Deleting file `stage3/bin/zig'
make[1]: *** [CMakeFiles/stage3.dir/all] Error 2
make: *** [all] Error 2
```

But I bet this is out of scope of Brew, as this seems to be a problem with Zig itself.

Could you explain to me why this env var fixed the dependency problems?
As I read in the docs, this is for cloning the entire homebrew-core repo, any idea why installing from API didn't work in my case?
Does maybe this has to do with some bug in homebrew itself?

Thanks for your time!

**Comment by gromgit** [comment]
Homebrew's API install facility involves new code paths across much of Homebrew, and this is likely a corner case that wasn't covered in testing. Setting `HOMEBREW_NO_INSTALL_FROM_API` tells Homebrew to abandon all the advantages of API installs, and rely on the old "local install" code paths.

cc @Homebrew/brew

**Comment by Bo98** [comment]
Ok turns out the dependency tree produced in the API is occasionally incorrect. It's not the most simple fix as there's backward compatiblity concerns (so will likely require a new JSON field) but I'll figure something out.

**Comment by sbbddz** [comment]
Its nice to at least have found the problem!

Let me know when you figure out something.

Thanks!
