### ISSUE TITLE
Offer Botan 2 with Botan 3

### ISSUE THREAD

**Issue by varjolintu** [Homebrew/homebrew-core#130139]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.15-120-g0c478b3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0c478b36dff61b47925531ae6950219ad487ac1e
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bf083aa8b8462d77d67ac88e776f5e65044ee294
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 29 Apr 15:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UJvOAx6OvV/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 13.2
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install Botan 2 instead of Botan 3. Support for Botan 2 seems to be removed from Homebrew. Only way to install Botan 2 back is to manually download the old `botan.rb` file and install Botan using it.
Botan 3 breaks depedencies with many projects, e.g. when trying to build KeePassXC.

### What happened (include all command output)?

Only Botan 3 is offered.

### What did you expect to happen?

`brew install botan@2` or `brew install botan@2.19.3` should be allowed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install botan@2`
```

**Comment by SMillerDev** [comment]
Please indicate how this would fill our criteria for versioned formulas (https://docs.brew.sh/Versions).

**Comment by carlocab** [comment]
If Botan2 is still supported upstream, then we can add a versioned formula for it. We'll review a pull request for that, but please check with upstream first whether they will continue to ship updates for Botan2. I checked their repository and the support status of Botan2 is not explicit there.

If you decide to open a pull request, please check the [contributing guide](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-add-a-new-formula-for-foo-version-234-from-url). You might also wish to have a look at [recent PRs](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aclosed+label%3A%22new+formula%22) that add new formulae.

If upstream don't have a specific commitment to provide continued support for Botan2, then it won't satisfy our [requirements](https://docs.brew.sh/Versions#acceptable-versioned-formulae) for versioned formulae. You can host a `botan@2` formula in your own tap instead in that case.

**Comment by varjolintu** [comment]
Botan [mentions](https://botan.randombit.net/) both release lines, so version 2 is still definitely supported. One reason for this is because Botan 3 [has switched](https://botan.randombit.net/news.html#release-notes) to C++20 codebase.

**Comment by varjolintu** [comment]
@carlocab Their [manual](https://botan.randombit.net/handbook/botan.pdf) has the following info:
<img width="837" alt="Screenshot 2023-05-04 at 12 22 56" src="https://user-images.githubusercontent.com/24570482/236163949-564b2f79-23de-40d0-8c6d-084cae632ebf.png">

"At the conclusion of the active development phase, only bugfixes are applied.", with the EOL in "2024-12-31 or later" means Botan 2 still receives fixes if needed.

**Comment by carlocab** [comment]
Works for me then. Feel free to open a PR.
