### ISSUE TITLE
flacenc not included with gst-plugins-good

### ISSUE THREAD

**Issue by theosib** [Homebrew/homebrew-core#13015]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

According to "http://brewformulas.org/GstPluginsGood", flac should be included with this package, but it seems to be only partially included.  I don't know how the problem could be due to anything other than this package.

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I ran those.  There isn't any malfunction with brew.  It's that a plugin 

- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

[EDIT] Here you go:
https://gist.github.com/83d969fdb730aa881153769d21bb9f8b

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I don't think these are relevant, and the output I get says nothing about this package.

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

In general and on other systems, the gst-plugins-good package includes full FLAC support.  So when I install this package, gstreamer features like "flacenc" should work.  

For instance, after I have installed gstreamer base and streamer plugin packages on any Linux system, this command works as intended:

gst-launch-1.0 -q autoaudiosrc ! flacenc ! filesink location=test2.flac

But with gst-plugins-good from homebrew, this gives me an error:
WARNING: erroneous pipeline: no element "flacenc"

Note that if I substitute "wavenc", it works fine.  So this package is just missing a key component.

**Comment by theosib** [comment]
So, if I understand this correctly, /usr/local/lib/gstreamer-1.0 should contain libgstflac.so or similar, but it doesn't.

**Comment by theosib** [comment]
I built from source and added the log to the description.  As you can see, it says this in the log:

configure: *** checking feature: FLAC lossless audio ***
configure: *** for plug-ins: flac ***
checking for FLAC... no
configure: No package 'flac' found
configure: *** These plugins will not be built: flac

There are two problems with this:  (1) flac is supposed to be an automatic dep of this, and (2) I manually installed flac using brew and reinstalled gst-plugins-good, and it still didn't detect flac.

**Comment by theosib** [comment]
Ok, I finally figured it out.  For some bizarre reason, unlike every other gstreamer installation I've ever encountered, flac is made optional with brew, requiring the use of the --with-flac option.  The problem is that the documentation on this module fails to mention this key piece of information.  

Where do I file bugs on documentation?

**Comment by ibrokemypie** [comment]
well, to start you would just do `brew info gst-plugins-good` which lists all of the options...
however i think the real issue is that flac should be enabled by default, much more likely that users want flac, so make it recommended rather than optional.

**Comment by dunn** [comment]
> The problem is that the documentation on this module fails to mention this key piece of information.

Which documentation do you mean?

We'd happily review a pull request making that option on by default; take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md if you're interested and let us know if you have questions!

**Comment by ilovezfs** [comment]
@theosib I'm glad you found your way to the --with-flac option. Thanks for taking the time to report this.
