### ISSUE TITLE
plantuml - 404 not found

### ISSUE THREAD

**Issue by mkon** [Homebrew/homebrew-core#13022]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

I was trying to run `brew install plantuml`

This happens:
```
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/plantuml/plantuml.8059.jar

curl: (22) The requested URL returned error: 404 Not Found
```

I ran brew update multiple times but the URL stays the same.

I suppose the formula URL is no longer correct. But I am not sure which of the JARs offered at sourceforge are correct.

**Comment by neutric** [comment]
Resolved in #13013.
