### ISSUE TITLE
brew upgrade failing postinstall on python@3.10 and python@3.11

### ISSUE THREAD

**Issue by kwloafman** [Homebrew/homebrew-core#130394]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Brew gist-logs:
3.10 - https://gist.github.com/kwloafman/4a475e01b895ce78a12de68a46f934c4
3.11 - https://gist.github.com/kwloafman/f28ff14ad920128d1853fcfc8e19e382
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew upgrade - to upgrade obviously.

### What happened (include all command output)?

brew upgrade failed when trying to update python@3.10 and python@3.11.  

Both said to run postinstall again and both had identical results:
```
$ brew postinstall python@3.10
==> Postinstalling python@3.10
==> /usr/local/Cellar/python@3.10/3.10.11/bin/python3.10 -m ensurepip
==> /usr/local/Cellar/python@3.10/3.10.11/bin/python3.10 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/us
Last 15 lines from /Users/ken/Library/Logs/Homebrew/python@3.10/post_install.02.python3.10:
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 566, in run
    self._handle_target_dir(
  File "/usr/local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 621, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 681, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'RECORD'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.10
```
The line `PermissionError: [Errno 13] Permission denied: 'RECORD'` is **totally useless**.  I have over 1,100 files named RECORD, all owned by me and all with permissions granting me read/write access.  I even checked the permissions for the enclosing directory and all of them have the correct permissions. 

### What did you expect to happen?

system to upgrade all packages.

lacking that, a better error message to isolate the problem.  

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade

will reproduce the problem.

I tried:
- brew postinstall ...
- brew uninstall and reinstall ...
- cleared the cache and tried install again
- checked owner/perms on RECORD files
- checked owner/perms on enclosing directories

No luck on anything so far.
```

**Comment by fxcoudert** [comment]
Your gist has:

`WARNING: The directory '/Users/ken/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory.`

It may be related?

Other than that, it is not clear why there is a `RECORD` file in the temporary directory that `pip` is trying to remove.

**Comment by fxcoudert** [comment]
Just to be clear: `PermissionError: [Errno 13] Permission denied: 'RECORD'` is not output by brew itself. `brew postinstall` is running `pip install`, and this error message is from `pip install`

Also: brew is not running things as another user.

**Comment by kwloafman** [comment]
OK, this is strange.  Looks like brew needs to check the version of pip.  I did the following and cleared up all the problems.
```
$ python3.10 -m pip install -U pip
$ brew postinstall python@3.10
$ python3.11 -m pip install -U pip
$ brew postinstall python@3.11
```
I must have had borked pip packages in those two pythons.  Both were pip 23.0.1.

Thanks for the help.  Looks like pip error reporting needs serious help.  I'll get an issue into them soon.
