### ISSUE TITLE
osgqt is missing from openscenegraph 3.5.5

### ISSUE THREAD

**Issue by leolchat** [Homebrew/homebrew-core#13048]
Since version 3.5.5 of openscenegraph, the qt plugin osgqt is not shipped with the main software anymore. => the --with-qt option of openscenegraph doesn't do anything.

To actually get the plugin one has to build and use osgqt from https://github.com/openscenegraph/osgQt

The main struggle is that the osgqt version needs to match osg, the one provided by brew is 3.5.5 but osgqt 3.5.5 requires qt4. To get qt5, osgqt 3.5.6 needs to be used but osg 3.5.6 is not released it is master right now.

I would be happy to write an osgqt formula but I am new to it and handling of version dependencies seems tricky, especially here. Moreover, it seems that it should not be a separate formula but it should be compiled by --with-qt of openscenegraph formula, no ?

**Comment by MikeMcQuaid** [comment]
This should be a separate formula as it's a separate upstream project/GitHub repository. We'll happily accept a pull request (which I see you've made before: thanks!)

**Comment by davenquinn** [comment]
Any update on this? Has any progress been made on a separate formula? The `--with-qt` option on `open-scene-graph` fails silently.

**Comment by MikeMcQuaid** [comment]
> Any update on this? Has any progress been made on a separate formula? The --with-qt option on open-scene-graph fails silently.

There has not. We'll accept PRs for this.
