### ISSUE TITLE
brew install springboot

### ISSUE THREAD

**Issue by rajang** [Homebrew/homebrew-core#13040]
brew install springboot
Error: No available formula with the name "springboot" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Tried with brew update and it logging Already uo-to-date.
Homebrew 1.1.13-144-gb067700
Homebrew/homebrew-core (git revision acb5; last commit 2017-04-29)

Running command on MAC OS 10.12.3

**Comment by neutric** [comment]
Did you `brew tap pivotal/tap` beforehand, as per the [Spring Boot installation instructions](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-homebrew-cli-installation)? This should fix your problem.
