### ISSUE TITLE
NCMPCPP dyld: Symbol not found: __ZNK5boost16re_detail_10630031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_

### ISSUE THREAD

**Issue by ibrokemypie** [Homebrew/homebrew-core#13055]
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/97cc5a26b7326b0e2e5d2d945e2b6d35

To help us debug your issue please explain:
- What you were trying to do (and why)
Install and then run ncmpcpp
- What happened (include command output)
``
$ ncmpcpp
dyld: Symbol not found: __ZNK5boost16re_detail_10630031cpp_regex_traits_implementationIcE17transform_primaryEPKcS4_
  Referenced from: /usr/local/bin/ncmpcpp
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib
 in /usr/local/bin/ncmpcpp
zsh: abort      ncmpcpp
``
- What you expected to happen
ncmpcc to work
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install ncmpcc  
ncmpcc
```

**Comment by ilovezfs** [comment]
It's not clear to me how to reproduce this.
```
iMac-TMP:homebrew-core joe$ brew instal ncmpcpp
==> Downloading https://homebrew.bintray.com/bottles/ncmpcpp-0.7.7_2.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/ncmpcpp-0.7.7_2.el_capitan.bottle.tar.gz
==> Pouring ncmpcpp-0.7.7_2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/ncmpcpp/0.7.7_2: 12 files, 3.1MB
iMac-TMP:homebrew-core joe$ brew test ncmpcpp
Testing ncmpcpp
==> Using the sandbox
==> /usr/local/Cellar/ncmpcpp/0.7.7_2/bin/ncmpcpp --version
iMac-TMP:homebrew-core joe$  /usr/local/Cellar/ncmpcpp/0.7.7_2/bin/ncmpcpp --version
ncmpcpp 0.7.7

optional screens compiled-in:
 - tag editor
 - tiny tag editor
 - artist info

encoding detection: enabled
built with support for: curl ncurses taglib unicode
iMac-TMP:homebrew-core joe$ 
```

**Comment by ibrokemypie** [comment]
stable installed fine for me, but would not run, error above, head would not install for me, it simply stated empty installation, which I have fixed in my PR. not sure if the stable version is effected

**Comment by ilovezfs** [comment]
For stable try this please:
```
brew deps ncmpcpp | xargs -tn1 brew uninstall --ignore-dependencies
brew uninstall ncmpcpp
brew install ncmpcpp
```
and then check if it works.

**Comment by ibrokemypie** [comment]
That seemed to fix it for me

**Comment by ilovezfs** [comment]
Cool. Thanks for testing.
