### ISSUE TITLE
lua@5.4.5 is not found 

### ISSUE THREAD

**Issue by gxvv** [Homebrew/homebrew-core#130524]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
unnecessary
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install neovim

### What happened (include all command output)?

<img width="587" alt="image" src="https://user-images.githubusercontent.com/8492441/237060899-92936894-cdf5-481c-bbe7-818f51ba1e94.png">
<img width="901" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/8492441/5ab68f65-0915-40e6-a2d0-e796649bc60f">

### What did you expect to happen?

install successfully 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install neovim
```

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports at Homebrew.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.

**Comment by carlocab** [comment]
```
Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

Please use the discussions page instead if you need help.

**Comment by gxvv** [comment]
This commit updates a unexisted Lua download link and failed to pass the test. It's not a software bug but a source bug. Other imformation is unnecessary.

https://github.com/Homebrew/homebrew-core/commit/454a17cbbaf8ac5c0f81d9d79ce34ae8e595f2a0

<img width="772" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/8492441/b418872e-a9c2-4113-96b9-28c1cec307e2">

**Comment by gromgit** [comment]
Lua 5.4.5 has been pulled by upstream, 5.4.6 is in progress: http://lua-users.org/lists/lua-l/2023-05/msg00014.html

**Comment by carlocab** [comment]
> This commit updates a unexisted Lua download link and failed to pass the test. It's not a software bug but a source bug. Other imformation is unnecessary.
> 
> 454a17c

That is the wrong commit. You should be looking at 01e04f8564386cd7e702c8844d1cf4e6fe29d0ac.

**Comment by gxvv** [comment]
I have checked the lasted lua.rb. It's using the lua@5.4.5 download link.

[  url "https://www.lua.org/ftp/lua-5.4.5.tar.gz"](https://github.com/Homebrew/homebrew-core/blob/2a6feef4d241c0293ce0e27267032a2124781d61/Formula/lua.rb#L4)

**Comment by carlocab** [comment]
This should be fixed now.
