### ISSUE TITLE
systemd: fail to build from source if p11-kit library is installed in homebrew

### ISSUE THREAD

**Issue by gahishi** [Homebrew/homebrew-core#131067]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0dc84b117f54f6b18e0528b95477c54e409ebdd
Last commit: 3 days ago
Core tap JSON: 16 May 05:52 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.19.0-41-generic x86_64 GNU/Linux
OS: Unknown (I use Docker Ubuntu)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I tried to install systemd from source, but it failed to compile. I did some digging. 

### What happened (include all command output)?

The error log points to

```log
FAILED: src/shared/libsystemd-shared-253.a.p/pkcs11-util.c.o
gcc-11 -Isrc/shared/libsystemd-shared-253.a.p -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -Isrc/fundamental -I../src/fundamental -Isrc/systemd -I../src/systemd -I. -I.. -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-journal -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.38.1/include/blkid -I/home/linuxbrew/.linuxbrew/Cellar/libcap/2.69/include -I/home/linuxbrew/.linuxbrew/Cellar/lz4/1.9.4/include -I/home/linuxbrew/.linuxbrew/Cellar/util-linux/2.38.1/include/libmount -I/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1t/include -I/home/linuxbrew/.linuxbrew/Cellar/p11-kit/0.24.1_1/include/p11-kit-1 -I/home/linuxbrew/.linuxbrew/Cellar/xz/5.4.3/include -I/home/linuxbrew/.linuxbrew/Cellar/zstd/1.5.5/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O3 -Wno-missing-field-initializers -Wno-unused-parameter -Warray-bounds -Warray-bounds=2 -Wdate-time -Wendif-labels -Werror=format=2 -Werror=format-signedness -Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wzero-length-bounds -Wno-maybe-uninitialized -Wno-unused-result -Werror=missing-declarations -Werror=missing-prototypes -fdiagnostics-show-option -fno-common -fno-strict-aliasing -fstack-protector -fstack-protector-strong -fvisibility=hidden --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -fno-omit-frame-pointer -Werror=shadow -include config.h -fPIC -pthread -fvisibility=default -MD -MQ src/shared/libsystemd-shared-253.a.p/pkcs11-util.c.o -MF src/shared/libsystemd-shared-253.a.p/pkcs11-util.c.o.d -o src/shared/libsystemd-shared-253.a.p/pkcs11-util.c.o -c ../src/shared/pkcs11-util.c
In file included from ../src/shared/pkcs11-util.c:16:
../src/shared/pkcs11-util.h:7:12: fatal error: p11-kit/p11-kit.h: No such file or directory
    7 | #  include <p11-kit/p11-kit.h>
      |            ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Notably, `<p11-kit/p11-kit.h>` is specified at the option `-I/home/linuxbrew/.linuxbrew/Cellar/p11-kit/0.24.1_1/include/p11-kit-1`, but the compiler failed to find it. 

If `p11-kit` is not installed in homebrew, but installed in the system it can compile sucessfully. (In my usage, `p11-kit` is introduced by other formula.)

### What did you expect to happen?

Expect systemd successfully compiled and installed. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install p11-kit
brew install systemd -s
```

**Comment by gahishi** [comment]
There is another issue: if `systemd` is installed, install `p11-kit` from source will also fail to compile.

**Comment by carlocab** [comment]
Why are you installing `systemd` from source?

**Comment by gahishi** [comment]
I just tried to build everything from source and found this bug. It does not prevent me from using homebrew normally. I reported it because I thought it was worth to report even if no fix.

**Comment by carlocab** [comment]
I see. Well, not sure what we can do to fix this. Problems like this are a big part of why we don't provide support for source builds. But I'll tag @Homebrew/linux here for ideas.

**Comment by cho-m** [comment]
Probably related to autodetected features. In some formulae, this would have caused opportunistic linkage.

For workaround, it should be possible to do `brew unlink p11-kit` before compilation and `brew link p11-kit` afterward.

For handling, one option would be to explicitly disable feature (may need to be done with other features too https://github.com/systemd/systemd/blob/v253/meson_options.txt), e.g.
```diff
@@ -54,6 +54,7 @@ class Systemd < Formula
       -Dhwdb=false
       -Dlz4=true
       -Dgcrypt=false
+      -Dp11kit=false
     ]

     system "meson", "setup", *args, "build"
```

**Comment by iMichka** [comment]
Agreed that we can either 1) disable the feature as above, or 2) add the dependency. How important is p11kit?

**Comment by SMillerDev** [comment]
Looking at their docs, it's only one small part of systemd that uses it. I'd say disabling is fine.
