### ISSUE TITLE
Anaconda and Miniconda

### ISSUE THREAD

**Issue by Atcold** [Homebrew/homebrew-core#13115]
# Please always follow these steps:
- [x ] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>

```
HOMEBREW_VERSION: 1.1.13-150-g0c9047a2b8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0c9047a2b81eaa58ccffa286a08df214a05f88ef
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 221c380107382807e9a6eba5973826e0d787d23d
Core tap last commit: 76 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.4-x86_64
Xcode: 8.2.1
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

</details>

To help us debug your issue please explain:
- What you were trying to do (and why)
Install *Anaconda* / *Miniconda*.
- What happened (include command output)
*Miniconda* gets installed properly in `$HOME`. *Anaconda* seems to be installed in `/usr/local/anaconda3/` but there is no `bin` folder within. Only `LICENSE.txt` and `pkgs`.
- What you expected to happen
Find the `bin` folder.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew cask install anaconda`

**Comment by MikeMcQuaid** [comment]
Please report this to Homebrew Cask instead, thanks: https://github.com/caskroom/homebrew-cask/issues/new
