### ISSUE TITLE
Formulae with dependencies that require options

### ISSUE THREAD

**Issue by jonchang** [Homebrew/homebrew-core#13133]
https://github.com/Homebrew/brew/pull/2482 has been merged and `brew audit` will reject formulae with any dependencies that require options, including optional dependencies.

---

- [x] cmu-sphinxbase: libsamplerate => ["with-libsndfile"]
- [x] gst-plugins-good: flac => [:optional, "with-libogg"]
- [x] gst-python: pygobject3 => ["with-python@2"]
- [x] gv: ghostscript => ["with-x11"]
- [x] libpeas: pygobject3 => ["with-python@2"]
- [x] mat: pygobject3 => ["with-python@2"]
- [x] shibboleth-sp: curl => ["with-openssl"]
- [x] xml-tooling-c: curl => ["with-openssl"]

---

- [x] angband: sdl_mixer => ["with-smpeg"]
- [x] angolmois: sdl_mixer => ["with-smpeg"], sdl2_mixer => ["with-smpeg2"]
- [x] anjuta: libxml2 => ["with-python"]
- [x] baobab: libxml2 => ["with-python", :build]
- [x] ccache: asciidoc => ["with-docbook-xsl"]
- [x] dosbox-x: sdl_sound => ["--with-libogg", "--with-libvorbis"]
- [x] dosbox: sdl_sound => ["--with-libogg", "--with-libvorbis"]
- [x] dspdfviewer: poppler => ["with-qt"]
- [x] easyrpg-player: sdl2_mixer => ["with-libvorbis"]
- [x] enigma: sdl_mixer => ["with-libmikmod"]
- [x] evince: libxml2 => ["with-python"]
- [x] file-roller: libxml2 => ["with-python", :build]
- [x] freeling: boost => ["with-icu4c"]
- [x] gammaray: homebrew/science/vtk => [:optional, "with-qt5"]
- [x] ghex: libxml2 => [:build, "with-python"]
- [x] git-ftp: curl => ["with-libssh2"]
- [x] gnome-doc-utils: libxml2 => ["with-python"]
- [x] gst-python: pygobject3 => ["with-python3"]
- [x] gtk-doc: libxml2 => ["with-python"]
- [x] huexpress: sdl2_mixer => ["with-libvorbis"]
- [x] i3: cairo => ["with-x11"]
- [x] itstool: libxml2 => ["with-python"]
- [x] latexila: libxml2 => ["with-python"]
- [x] lincity-ng: sdl_mixer => ["with-libvorbis"]
- [x] lnav: curl => ["with-libssh2", :optional]
- [x] makepkg: asciidoc => ["with-docbook-xsl", :build]
- [x] negfix8: imagemagick => ["with-quantum-depth-16"]
- [x] openvpn: pkcs11-helper => [:optional, "without-threading", "without-slotevent"]
- [x] onscripter: sdl_mixer => ["with-libvorbis"]
- [x] plowshare: imagemagick => ["with-x11"]
- [x] ponscripter-sekai: sdl2_mixer => ["with-smpeg2"]
- [x] pyqt: sip => ["with-python3"]
- [x] pytouhou: pygobject3 => ["with-python3"]
- [x] qscintilla2: sip => ["with-python3"]
- [x] supertux: sdl2_mixer => ["with-libvorbis"]
- [x] ufoai: sdl2_mixer => ["with-libvorbis"]
- [x] viewvc: subversion => ["with-python"]
- [x] wesnoth: sdl_mixer => ["with-libvorbis"]
- [x] xplanetfx: pygtk => ["with-libglade"]

**Comment by ilovezfs** [comment]
Thank you for creating this @jonchang

**Comment by MikeMcQuaid** [comment]
Thanks @jonchang! The solution to some of these will be resource bblocks and some of them may be having slightly more heavy defaults (i.e. `sdl_mixer --with-libvorbis` looks like it has potential). The main thing I want to avoid is things like X11 being on by default and, to a lesser extent, very fat dependencies like Qt being added.

**Comment by Ghabry** [comment]
At least for "easyrpg-player" you can simply drop the "--with-libvorbis" from SDL mixer because EasyRPG will use it's own libvorbis OGG decoder instead of the one provided by SDL mixer. (Source: I'm one of the devs)

**Comment by ilovezfs** [comment]
I've sorted the outstanding ones to the top of the list. Excellent work here so far everyone, especially @JCount and @DomT4.

**Comment by sl1pkn07** [comment]
kf5-kfilemetadata and okular (from https://github.com/KDE-mac/homebrew-kde) needs poppler with qt support

If i understad correctly this bug (and https://github.com/Homebrew/brew/pull/2482), now poppler needs build with qt by default instead of use --with-qt.

or i need create a separate poppler formulae in KDE-mac with qt by default

greetings

**Comment by MikeMcQuaid** [comment]
> or i need create a separate poppler formulae in KDE-mac with qt by default

Yes, this is the best bet.

**Comment by sl1pkn07** [comment]
with the same name? (adding conflicts with poppler) or a custom name (also with poppler as conflict)

**Comment by MikeMcQuaid** [comment]
I'd recommend a custom name and making it `keg_only` so it doesn't need to conflict.

**Comment by vinyldarkscratch** [comment]
I'm now going through and modifying the last of the formulas so they pass `brew audit --strict` on the most recent version of Homebrew.  :wink:

**Comment by fxcoudert** [comment]
dspdfviewer fixed by vendoring poppler in #28120

**Comment by fxcoudert** [comment]
Thanks to everyone who helped, and thanks to @MikeMcQuaid for pushing it over the finish line!
