### ISSUE TITLE
Formula/graphicsmagick.rb builds without FreeType

### ISSUE THREAD

**Issue by leaderit** [Homebrew/homebrew-core#131442]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.0.18-102-gc265d3d
ORIGIN: https://github.com/Homebrew/brew
HEAD: c265d3d330adb2707502e61cc93864fb9353a7bc
Last commit: 6 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f7d8c48dff7a70f5102176c727287ae0154d7b5e
Core tap last commit: 2 hours ago
Core tap branch: master
Core tap JSON: 19 May 22:47 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.40.1 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.5-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libusb-1.0.0.dylib
  /usr/local/lib/libusb-1.0.dylib

libusb* from other equipment's driver - no conflicts with the library
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

% brew install graphicsmagick
% gm version

i would like to use the graphicsnagick library in my project but it builded without freetype.
i tried rebuild it from sources

%brew reinstall --build-from-source  --verbose --formula ./graphicsmagick.rb graphicsmagick

...

GraphicsMagick is configured as follows. Please verify that this
configuration matches your expectations.
...
FreeType 2.0      --with-ttf=yes          	no (failed tests)
...

### What happened (include all command output)?

GraphicsMagick 1.3.40 2023-01-14 Q8 http://www.GraphicsMagick.org/
Copyright (C) 2002-2023 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe         yes
  Large Files (> 32 bit)     yes
  Large Memory (> 32 bit)    yes
  BZIP                       yes
  DPS                        no
  FlashPix                   no
  FreeType                   no
  Ghostscript (Library)      no
  HEIF/HVEC ("HEIC")         yes
  JBIG                       no
  JPEG-2000                  yes
  JPEG                       yes
  JPEG XL                    yes
  Little CMS                 yes
  Loadable Modules           no
  Solaris mtmalloc           no
  Google perftools tcmalloc  no
  OpenMP                     no
  PNG                        yes
  TIFF                       yes
  TRIO                       no
  Solaris umem               no
  WebP                       yes
  WMF                        no
  X11                        yes
  XML                        yes
  ZLIB                       yes

Host type: x86_64-apple-darwin21.6.0

Configured using the command:
  ./configure  '--disable-debug' '--disable-dependency-tracking' '--prefix=/usr/local/Cellar/graphicsmagick-freetype/1.3.40' '--libdir=/usr/local/Cellar/graphicsmagick-freetype/1.3.40/lib' '--disable-silent-rules' 'CC=clang' 'CXX=clang++' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/12'

Final Build Parameters:
  CC       = clang
  CFLAGS   = -g -O2 -Wall -D_THREAD_SAFE
  CPPFLAGS = 
  CXX      = clang++
  CXXFLAGS = -D_THREAD_SAFE
  LDFLAGS  = 
  LIBS     = -lwebp -lwebpmux -lsharpyuv -lheif -lde265 -llcms2 -ltiff -ljasper -ljpeg -ljxl -ljxl_threads -lhwy -lbrotlidec -lbrotlienc -lstdc++ -lpng16 -lXext -lX11 -llzma -lbz2 -lxml2 -lz -lzstd -lm -lpthread

### What did you expect to happen?

Feature Support:
...
  FreeType                   yes

and working, so

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew install graphicsmagick
% gm version
```

**Comment by SMillerDev** [comment]
This is not a bug but a feature request and should therefore be filed as a pull request

**Comment by leaderit** [comment]
> This is not a bug but a feature request and should therefore be filed as a pull request

May be. But it worked before i did  brew upgrade. I used the library in my project and freetype functions in graphicsmagick worked great. But after upgrades my project doesn't work. 

I tried find out why i got error "FreeType library is not available" and founded graphicsmagick without freetype now.

**Comment by leaderit** [comment]
I solved my problem by uninstall brews graphicsmagick

brew uninstall graphicsmagick

and than build graphicsmagick from sources, using my script:

==================

# !/bin/sh
NAME=GraphicsMagick
VER="1.3.40"
HOMEBREW_PREFIX=/usr/local
wget -N https://downloads.sourceforge.net/project/graphicsmagick/graphicsmagick/${VER}/GraphicsMagick-${VER}.tar.gz
tar xf GraphicsMagick-${VER}.tar.gz
cd $NAME-$VER

./configure \
      --disable-dependency-tracking \
      --disable-openmp \
      --enable-static \
      --enable-shared \
      --with-modules \
      --with-quantum-depth=16 \
      --with-magick-plus-plus=yes \
      --without-lzma \
      --without-x \
      --without-gslib \
      --with-gs-font-dir=${HOMEBREW_PREFIX}/share/ghostscript/fonts \
      --without-wmf \
      --with-jxl

make && sudo make uninstall && sudo make install

==================
after that my programm compile and work fine. gm version now

gm versiom
gm: Unrecognized command 'versiom'. Use -help for a usage summary or see manual..
vg@MacBook-Pro16-vg graphicsmagick % gm version
GraphicsMagick 1.3.40 2023-01-14 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2023 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe         yes
  Large Files (> 32 bit)     yes
  Large Memory (> 32 bit)    yes
  BZIP                       yes
  DPS                        no
  FlashPix                   no
  FreeType                   yes
  Ghostscript (Library)      no
  HEIF/HVEC ("HEIC")         yes
  JBIG                       no
  JPEG-2000                  yes
  JPEG                       yes
  JPEG XL                    yes
  Little CMS                 yes
  Loadable Modules           yes
  Solaris mtmalloc           no
  Google perftools tcmalloc  no
  OpenMP                     no
  PNG                        yes
  TIFF                       yes
  TRIO                       no
  Solaris umem               no
  WebP                       yes
  WMF                        no
  X11                        no
  XML                        yes
  ZLIB                       yes

Host type: x86_64-apple-darwin21.6.0

Configured using the command:
  ./configure  '--disable-dependency-tracking' '--disable-openmp' '--enable-static' '--enable-shared' '--with-modules' '--with-quantum-depth=16' '--with-magick-plus-plus=yes' '--without-lzma' '--without-x' '--without-gslib' '--with-gs-font-dir=/usr/local/share/ghostscript/fonts' '--without-wmf' '--with-jxl' 'LDFLAGS=-L/usr/local/opt/node@18/lib -L/usr/local/lib' 'CPPFLAGS=-I/usr/local/opt/node@18/include'

Final Build Parameters:
  CC       = gcc
  CFLAGS   = -g -O2 -Wall -D_THREAD_SAFE
  CPPFLAGS = -I/usr/local/opt/node@18/include -I/usr/local/opt/freetype/include/freetype2
  CXX      = g++
  CXXFLAGS = -D_THREAD_SAFE
  LDFLAGS  = -L/usr/local/opt/node@18/lib -L/usr/local/lib -L/usr/local/opt/freetype/lib
  LIBS     = -llcms2 -lfreetype -lbz2 -lz -lltdl -lm -lpthread
