### ISSUE TITLE
go fails to build

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#13152]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 

[logs](https://gist.github.com/yurikoles/22da893acfc18ba9b6356c7730071740
)

**Comment by ilovezfs** [comment]
```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: adfdb43410251ccfe20bbe022e7110d2c03fd598
Core tap last commit: 1 year, 5 months ago
```
I think you may not be on the master branch in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/`
