### ISSUE TITLE
hugo failed to build on 10.11

### ISSUE THREAD

**Issue by nazavode** [Homebrew/homebrew-core#13161]
This issue was initially reported [here](https://github.com/Linuxbrew/homebrew-core/issues/2587) as it was affecting Linuxbrew@Ubuntu16.04 and identified as introduced upstream by Homebrew/homebrew-core@6717334

- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

`brew gist-logs hugo` replied with: `Error: No logs.`

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew doctor` gives no errors/warnings. Attached 
[brewconfig.txt](https://github.com/Homebrew/homebrew-core/files/970668/brewconfig.txt)

To help us debug your issue please explain:
- What you were trying to do (and why)

Install `hugo` formula

- What happened (include command output)

```
$ brew install hugo                           
==> Downloading https://github.com/spf13/hugo/archive/v0.20.6.tar.gz
==> Downloading from https://codeload.github.com/spf13/hugo/tar.gz/v0.20.6
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 857655b69fb3e7f174011fd6774501194f1241bbb833256fd63b585b6d7a3cc0
Actual: 692e08b009430d27064821d498f1454152cbfd5f26d019c29002e6fbff8fc387
Archive: /home/montag/.cache/Homebrew/hugo-0.20.6.tar.gz
To retry an incomplete download, remove the file above.
```

- What you expected to happen

To have the `hugo` formula installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew fetch -s hugo`

**Comment by woodruffw** [comment]
Have you deleted `/home/montag/.cache/Homebrew/hugo-0.20.6.tar.gz` and retried?

**Comment by woodruffw** [comment]
Opened an inquiry at https://github.com/spf13/hugo/issues/3428, and https://github.com/Homebrew/homebrew-core/pull/13186 is pending if it is indeed a re-tag.
