### ISSUE TITLE
New upstream for rpl

### ISSUE THREAD

**Issue by rrthomas** [Homebrew/homebrew-core#131862]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a

I'm not reporting a brew problem!
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

(This seems to be the right place, since the `rpl.rb` formula is in this repo. Apologies if I did it wrong!)

I notice that your formula for `rpl` uses an abandoned upstream. I took over developing Debian's replacement free version of `rpl` some years ago, and my actively-maintained upstream is at:

https://github.com/rrthomas/rpl

The current version includes new functionality such as auto-detection of input encoding, glob-matching of filenames, and user-friendly long options, while remaining backwards-compatible with Joe Laffey's original.

### What happened (include all command output)?

n/a

### What did you expect to happen?

n/a

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
n/a
```

**Comment by chenrui333** [comment]
Make sense, I just filed a PR to build on your fork.
