### ISSUE TITLE
openjdk failures: trino and walkmod

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#131903]
### Description

Multiple CI runs show openjdk-related failures in the tests for `trino` and `walkmod`. See for example: https://github.com/Homebrew/homebrew-core/actions/runs/5061875769/jobs/9090142889?pr=131789

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

**Comment by cho-m** [comment]
`walkmod` was deprecated in #131914.

`trino` sounds like a timing issue although we already wait 30s.

**Comment by cho-m** [comment]
Closing this as complete after #153348.
