### ISSUE TITLE
"brew install ffmpeg --HEAD" fails with "Error: No such file or directory - config.mak"

### ISSUE THREAD

**Issue by tamc** [Homebrew/homebrew-core#13228]
"brew install ffmpeg --HEAD" fails with "Error: No such file or directory - config.mak"

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
libressl

==> Using the sandbox
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/thomascounsell/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-92f4a4b --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp
Error: No such file or directory - config.mak
```

The cause is this line, looking for config.mak which does not exist:
https://github.com/Homebrew/homebrew-core/blob/1b718ab8c0ec34a14d1332a5eda8660fa9b9bb45/Formula/ffmpeg.rb#L183

It looks to me like that section is no longer required: https://github.com/FFmpeg/FFmpeg/commit/dff68563d846274cee0a2cd2430d6f1a2cb51eaa

It seems to compile fine without it for me. I will create a pull request.

**Comment by dunn** [comment]
Assuming fixed, thanks for the PR!
