### ISSUE TITLE
`brew bundle --all --cleanup` uninstalls VSCodium extensions

### ISSUE THREAD

**Issue by vraravam** [Homebrew/homebrew-core#132381]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config output:

HOMEBREW_VERSION: 4.0.19
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4446fe603cc19316036fd07e5df1124c4d15ead2
Last commit: 9 days ago
Core tap JSON: 31 May 01:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3
HOMEBREW_EDITOR: codium --goto
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_VERBOSE_USING_DOTS: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false

---------------------
brew doctor output:

Your system is ready to brew.

```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to run `brew bundle --all --cleanup` with this [Brewfile](https://gist.github.com/vraravam/8c9eae91a3750bed86b81e3a4711f842)

Please note the aliases on the comments at the top of the file - which is what I use and it triggered the issue

### What happened (include all command output)?

<img width="1327" alt="Screenshot 2023-05-31 at 7 04 21 AM" src="https://github.com/Homebrew/homebrew-core/assets/69629/c0d6e276-e710-492b-a976-b425b3d038d8">

I have changed the alias to remove the `--cleanup` option - and thus the information about "would uninstall vscode extensions". When I run with that switch, the extensions get removed.

### What did you expect to happen?

Till approx 24 hrs ago, the `--cleanup` would clean all other brew-installed software but not touch the vscode extensions. I expected that same behavior to continue

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Keep the Brewfile in the ~/Brewfile location
2. Run `brew bundle --all --cleanup`
```

**Comment by carlocab** [comment]
This should have been fixed in https://github.com/Homebrew/homebrew-bundle/pull/1210. If you're still having problems with this after a `brew update`, please file an issue there.
