### ISSUE TITLE
homebrew does not handle pbr versioning properly

### ISSUE THREAD

**Issue by austin987** [Homebrew/homebrew-core#132394]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
austin@Austins-MacBook-Air homebrew % brew config
HOMEBREW_VERSION: 4.0.20-2-ga380aed
ORIGIN: https://github.com/Homebrew/brew
HEAD: a380aed887f40cbe29953269798d510502bf177d
Last commit: 12 hours ago
Core tap JSON: 31 May 03:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: N/A
Rosetta 2: false
austin@Austins-MacBook-Air homebrew % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Note: This was originally discussed at https://github.com/Homebrew/homebrew-core/pull/128027

I was asked to report an upstream issue, however I don't see any reason that this would be an upstream issue. In my opinion, it's a homebrew issue.

====

I'm trying to submit a formula for bashate. bashate uses pbr as a dependency and to handle its versioning. However, that doesn't seem to work with homebrew.

### What happened (include all command output)?

Error: Failed to load cask: Formula/bashate.rb
Cask 'bashate' is unreadable: wrong constant name #<Class:0x00000001569ab238>
Warning: Treating Formula/bashate.rb as a formula.
==> Fetching bashate
==> Downloading https://files.pythonhosted.org/packages/02/d8/acee75603f31e27c51134a858e0dea28d321770c5eedb9d1d673eb7d3817/pbr-5.11.1.tar.gz
Already downloaded: /Users/austin/Library/Caches/Homebrew/downloads/cfc298423834d40380f82b47103f79269a4bf74e5c58e52c68bea2fd6f06c9f4--pbr-5.11.1.tar.gz
==> Downloading https://github.com/openstack-dev/bashate/archive/2.1.1.tar.gz
Already downloaded: /Users/austin/Library/Caches/Homebrew/downloads/43d51a08d376143b87074a228fd66a2b5307fe66262eb884cc423ec145f57019--bashate-2.1.1.tar.gz
==> python3.11 -m venv --system-site-packages /opt/homebrew/Cellar/bashate/2.1.1/libexec
==> /opt/homebrew/Cellar/bashate/2.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --use-feature=no-binary-enable-wheel-cache --ignore-installed /private/tmp/bashate--pbr-20230531-19549-rid5b2/
==> /opt/homebrew/Cellar/bashate/2.1.1/libexec/bin/pip install -v --no-deps --no-binary :all: --use-feature=no-binary-enable-wheel-cache --ignore-installed /private/tmp/bashate-20230531-19549-ygp59u/basha
Last 15 lines from /Users/austin/Library/Logs/Homebrew/bashate/03.pip:
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/bashate-20230531-19549-ygp59u/bashate-2.1.1/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /private/tmp/pip-pip-egg-info-u599ads4
  cwd: /private/tmp/bashate-20230531-19549-ygp59u/bashate-2.1.1/
  Preparing metadata (setup.py): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

### What did you expect to happen?

bashate to install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ curl -O https://raw.githubusercontent.com/austin987/homebrew-core/c62d1156d2581f76337a2c03bfb5dfd7e18de0f9/Formula/bashate.rb
$ brew install --build-from-source ./bashate.rb
```

**Comment by carlocab** [comment]
> I'm trying to submit a formula for bashate. bashate uses pbr as a dependency and to handle its versioning. However, that doesn't seem to work with homebrew.

I'm not sure I follow here. What is Homebrew doing that breaks either or both of 1) bashate using pbr as a dependency, and 2) handling its versioning?[^1]

[^1]: Incidentally, for (2), I'm not clear on which is handling the other's versioning. is pbr handling bashate's versioning, or vice-versa? What does "handle its versioning" mean, exactly?

Also:

> ```shell
> $ curl -O https://raw.githubusercontent.com/austin987/homebrew-core/c62d1156d2581f76337a2c03bfb5dfd7e18de0f9/Formula/bashate.rb
> $ brew install --build-from-source ./bashate.rb
> ```

Don't pass paths to Ruby files (e.g. `./bashate.rb`) to `brew install`; that never works properly. You should only ever pass formula names (e.g. `brew install bashate`).

**Comment by austin987** [comment]
> > I'm trying to submit a formula for bashate. bashate uses pbr as a dependency and to handle its versioning. However, that doesn't seem to work with homebrew.
> 
> I'm not sure I follow here. What is Homebrew doing that breaks either or both of 1) bashate using pbr as a dependency, and 2) handling its versioning?[1](#user-content-fn-1-7ffccb67e6dda513e91ec101f55d2117)

I don't know what Homebrew is doing to break it, but:

Bashate uses pbr as a dependency to output its version info. That works in pip:
```
#!/bin/sh
tmp="$(mktemp -d)"
cd "$tmp"
python3 -m venv env
. env/bin/activate
cd $HOME/src/bashate
pip install -r requirements.txt
python setup.py install
cd "$tmp"/env
./bin/bashate --version
```

will output:
```
bashate: 2.1.2.dev1
````

> Also:
> 
> > ```shell
> > $ curl -O https://raw.githubusercontent.com/austin987/homebrew-core/c62d1156d2581f76337a2c03bfb5dfd7e18de0f9/Formula/bashate.rb
> > $ brew install --build-from-source ./bashate.rb
> > ```
> 
> Don't pass paths to Ruby files (e.g. `./bashate.rb`) to `brew install`; that never works properly. You should only ever pass formula names (e.g. `brew install bashate`).

Okay.

> ## Footnotes
> 
>     1. Incidentally, for (2), I'm not clear on which is handling the other's versioning. is pbr handling bashate's versioning, or vice-versa? What does "handle its versioning" mean, exactly? [↩](#user-content-fnref-1-7ffccb67e6dda513e91ec101f55d2117)

See: https://github.com/openstack/bashate/blob/master/bashate/__init__.py#L17

**Comment by carlocab** [comment]
> > > I'm trying to submit a formula for bashate. bashate uses pbr as a dependency and to handle its versioning. However, that doesn't seem to work with homebrew.
> > 
> > 
> > I'm not sure I follow here. What is Homebrew doing that breaks either or both of 1) bashate using pbr as a dependency, and 2) handling its versioning?
> 
> I don't know what Homebrew is doing to break **_it_**

Ok, but what is the word "**_it_**" referring to?  (See matching bold italic text above -- emphasis mine.) Is it only (1), only (2), or both (1) and (2)?
 
> Bashate uses pbr as a dependency to output its version info. That works in pip:
> 
> ```
> #!/bin/sh
> tmp="$(mktemp -d)"
> cd "$tmp"
> python3 -m venv env
> . env/bin/activate
> cd $HOME/src/bashate
> pip install -r requirements.txt
> python setup.py install
> cd "$tmp"/env
> ./bin/bashate --version
> ```
> 
> will output:
> 
> ```
> bashate: 2.1.2.dev1
> ```

Ok, I can see that using `pip` directly outside of `brew` does not produce `error: metadata-generation-failed` as in your original post. How is the output `bashate: 2.1.2.dev1` related to the metadata generation error?

Or, if it is not related to the error, why is the version output of bashate important to highlight here? Does `bashate` produce different version output if installed using `brew`? If yes, what is that output, and how did you produce it given the install failure?

> See: https://github.com/openstack/bashate/blob/master/bashate/__init__.py#L17

Ok, does this mean that `bashate` uses `pbr` to work out its (`bashate`'s) version?
