### ISSUE TITLE
Unable to install an older version of cocoapods

### ISSUE THREAD

**Issue by SandraNPR** [Homebrew/homebrew-core#132350]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8917acac9560f8e2846eedc4181470f0345f6db8
Last commit: 11 hours ago
Core tap JSON: 30 May 18:11 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6.1-arm64
CLT: 14.0.0.0.1.1661618636
Xcode: 14.2 => /Users/Squel/Downloads/Xcode.app/Contents/Developer
Rosetta 2: false

brew doctor: 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 14.2.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

install the 1.11.3 version of cocoapods. Our project is not yet using the latest version of cocoapods.

### What happened (include all command output)?

brew install cocoapods
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
apko                                     mods
ast-grep                                 nexttrace
boolector                                openfga
clive                                    pocketbase
convco                                   procps@3
debugbreak                               quantum++
dzr                                      roblox-ts
jet                                      rojo
libabigail                               rye
libclc                                   shodan
libfastjson                              ssocr
libint                                   staq
libmediainfo                             svlint
libomemo-c                               svls
libpaho-mqtt                             tailwindcss-language-server
libzen                                   virtualfish
lpeg                                     wally
melange                                  yamlfmt
==> New Casks
1kc-razer
asix-ax88179
bose-updater
caldigit-docking-utility
caldigit-thunderbolt-charging
chatbox
concept2-utility
copilot
craft
dadroit-json-viewer
dintch
engine-dj
eobcanka
eu
eusamanager
filemonitor
firefly-shimmer
focusrite-control
fractal-bot
genesys-cloud
hdhomerun
hp-easy-start
huiontablet
insta360-studio
jabra-direct
kiibohd-configurator
konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver
lasso
lg-onscreen-control
linn-konfig
llamachat
lo-rain
music-miniplayer
music-remote
music-widget
nordic-nrf-command-line-tools
pallotron-yubiswitch
philips-hue-sync
processmonitor
qflipper
saleae-logic
shureplus-motiv
skiff
smooze-pro
synology-cloud-station-backup
synology-photo-station-uploader
synology-surveillance-station-client
synologyassistant
tea
tiptoi-manager
uhk-agent
wacom-tablet
yealink-meeting
zsa-wally

You have 1 outdated formula installed.

Warning: Treating cocoapods as a formula. For the cask, use homebrew/cask/cocoapods
Warning: cocoapods 1.12.1 is already installed and up-to-date.
To reinstall 1.12.1, run:
  brew reinstall cocoapods

### What did you expect to happen?

I would expect there to be a home brew command for specifying the version of cocoapods to install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run brew install cocoapods

It automatically installs cocoapods 1.12.1
```

**Comment by SMillerDev** [comment]
That is not a supported usage for Homebrew

**Comment by SandraNPR** [comment]
Will it ever be supported?

**Comment by SMillerDev** [comment]
Will you make a pull request to add support for it?

**Comment by SandraNPR** [comment]
@SMillerDev I'm new to this repo. How do I do that if I don't have a fix for it?

**Comment by SMillerDev** [comment]
In that case I don't think it'll ever be supported since Homebrew relies on volunteers contributing code to add new features.

**Comment by SandraNPR** [comment]
ok
