### ISSUE TITLE
Unable to run osc, getting import error for M2Crypto

### ISSUE THREAD

**Issue by MindTooth** [Homebrew/homebrew-core#13230]
# Please always follow these steps:
- [x] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/78345c2f2ffe85db0a839f9fbb21c793

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to run `osc`
- What happened (include command output)
```
cannot import name m2
M2Crypto is needed to access https://api.opensuse.org in a secure way.
Please install python-m2crypto.
```
- What you expected to happen
Success
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install -s osc
osc ls
```

Also happens when I use the bottle.  *(Tried from source just because.)*

My PATH:
`PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/MindTooth/.config/yarn/global/node_modules/.bin`

**Comment by ilovezfs** [comment]
I cannot reproduce this issue. Please try again in a dummy user account to rule out something in your profile.

**Comment by MindTooth** [comment]
Just created a new account, and still no go.

If I run Python and `help ('modules'), I can see M2Crypto.

But does the osc use the system Python perhaps?

**Comment by ilovezfs** [comment]
In that case, you'll need to try it in an empty brew installation.

```
sudo mv /usr/local ~/homebrew-20170507
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install osc
```

**Comment by MindTooth** [comment]
Did not solve anything.  Used Terminal, and made sure I used `bash` as I don't have a a .bashrc that loads stuff.

Tried to install m2crypto in system Python, but no go.

```
mactooth:~ MindTooth$ pip install m2crypto  --user python
Collecting m2crypto
Requirement already satisfied: python in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
Collecting typing (from m2crypto)
Installing collected packages: typing, m2crypto
Successfully installed m2crypto-0.26.0 typing-3.6.1
mactooth:~ MindTooth$ osc ls
cannot import name m2
M2Crypto is needed to access https://api.opensuse.org in a secure way.
Please install python-m2crypto.
```

When do in fact run `help ('modules')`, I can't see m2, just M2Crypto.

**Comment by ilovezfs** [comment]
@tdsmith any ideas?

**Comment by tdsmith** [comment]
The way this is intended to work, osc runs in its own virtualenv, into which m2crypto is installed, that is independent of the user and system environments, so making changes to the global package environment will not affect osc.

The failure is actually `from M2Crypto import m2`; the name m2 isn't supposed to be importable on its own.

The problem is:
```
>>> from M2Crypto import m2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/osc/0.157.2_1/libexec/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/usr/local/Cellar/osc/0.157.2_1/libexec/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/usr/local/Cellar/osc/0.157.2_1/libexec/lib/python2.7/site-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, util
  File "/usr/local/Cellar/osc/0.157.2_1/libexec/lib/python2.7/site-packages/M2Crypto/util.py", line 20, in <module>
    from typing import AnyStr, Tuple, Union  # noqa
ImportError: No module named typing
```

M2Crypto grew a dependency on the `typing` module that we couldn't account for because we don't have a useful test for this formula because all of the endpoints require authentication.

The fix is to add a resource for `typing` to the formula.

**Comment by ilovezfs** [comment]
@tdsmith Does the issue actually occur for you when running `osc ls`?

**Comment by tdsmith** [comment]
I haven't tried; I don't intend to register.

**Comment by ilovezfs** [comment]
Ah, I see. So it may only occur after you go through that authentication nonsense.
