### ISSUE TITLE
Mkvtoolnix Error Qt

### ISSUE THREAD

**Issue by AzX0z** [Homebrew/homebrew-core#132822]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

used mkvtoolnix 73.0.0. normally, I went to update and now I can't install it in my seedbox anymore.
Qt instaled.

brew install mkvtoolnix --force

==> Fetching mkvtoolnix
Warning: Building mkvtoolnix from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/user/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/user/.linuxbrew)
==> Downloading https://mkvtoolnix.download/sources/mkvtoolnix-76.0.tar.xz
Already downloaded: /home/user/.cache/Homebrew/downloads/b1e234a4e77976d661ed323cd6483c97d28f60ff7a3e055f9fb911d91665d528--mkvtoolnix-76.0.tar.xz
==> Fetching mkvtoolnix
Warning: Building mkvtoolnix from source as the bottle needs:
- HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar (yours is /home/user/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /home/user/.linuxbrew)==> Patching
==> ./configure --prefix=/home/user/.linuxbrew/Cellar/mkvtoolnix/76.0_1 --with-boost=/home/user/.linuxbrew/opt/boost --with-docbook-xsl-root=/home/user/.linuxbrew/opt/docbook-xsl/docbLast 15 lines from /home/user/.cache/Homebrew/Logs/mkvtoolnix/01.configure:
for more information.
checking for Qt 6... no: qmake6 couldn't be run for a dummy project
checking for qmake-qt5... no
checking for qmake... /home/user/.linuxbrew/opt/qt/bin/qmake
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, but has failed to switch to one.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
checking for qmake's version... 6.5.1
checking for lconvert... /home/user/.linuxbrew/opt/qt/bin/lconvert
checking for moc... no
checking for rcc... no
checking for uic... no
checking for Qt 5... no: could not find the moc executable
configure: error: The Qt library is required for building MKVToolNix.

READ THIS: https://docs.brew.sh/Troubleshooting

### What happened (include all command output)?

.

### What did you expect to happen?

.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
.
```

**Comment by carlocab** [comment]
> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.
