### ISSUE TITLE
`exiv2` v0.27.6 is deprecated. update to v0.28.0

### ISSUE THREAD

**Issue by sjsone** [Homebrew/homebrew-core#132800]
### `brew config`

```shell
HOMEBREW_VERSION: 4.0.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8917acac9560f8e2846eedc4181470f0345f6db8
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 43dcb21d4b46a63fd3032c6cf71c62707d94532f
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 04 Jun 09:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.2
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to install the NPM Package `raw-preview` which builds a local nodejs extension using `exiv2`. 

### What happened (include all command output)?

Node GYP threw errors (`error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'? `) while trying to compile: 

```
... 
In file included from ../src/binding.cpp:1:
In file included from ../src/binding.h:2:
In file included from /opt/homebrew/Cellar/exiv2/0.27.6/include/exiv2/exiv2.hpp:28:
In file included from /opt/homebrew/Cellar/exiv2/0.27.6/include/exiv2/bmffimage.hpp:27:
In file included from /opt/homebrew/Cellar/exiv2/0.27.6/include/exiv2/image.hpp:28:
In file included from /opt/homebrew/Cellar/exiv2/0.27.6/include/exiv2/exif.hpp:35:
/opt/homebrew/Cellar/exiv2/0.27.6/include/exiv2/tags.hpp:143:17: error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'?
        typedef std::auto_ptr<ExifKey> AutoPtr;
                ^~~~~~~~~~~~~
                auto_ptr
/opt/homebrew/Cellar/exiv2/0.27.6/include/exiv2/config.h:105:3: note: 'auto_ptr' declared here
  using auto_ptr = std::unique_ptr<T>;
  ^
...
```

Trying to search this error lead me to this issue with a clear answere:

> Hi @yangpenglove . You already found out that there is a difference between the 0.27.5 release and the version we keep in the `main` branch. We keep releasing 0.27.X versions from time to time to fix bugs, but that branch is not anymore under active development. The code there is using the C++ 03 standard and not using any feature from modern C++. 
>
> The active development is happening in the `main` branch where we started to migrate some code modern C++. You can download nightly releases of the newest branch from this page:
https://github.com/Exiv2/exiv2/releases
> 
> I am closing this ticket since it was a question (and not a bug).

_Originally posted by @piponazo in https://github.com/Exiv2/exiv2/issues/2359#issuecomment-1250093334_
            

### What did you expect to happen?

The package should build normally. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
mkdir exiv2-test
cd exiv2-test
brew install exiv2
yarn init
yarn add raw-preview
```

**Comment by carlocab** [comment]
In progress at https://github.com/Homebrew/homebrew-core/pull/130959.
