### ISSUE TITLE
The subversion formula (serf download URL) is outdated 

### ISSUE THREAD

**Issue by PlugNPush** [Homebrew/homebrew-core#133035]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
(brew gist-logs subversion below) I am running macOS 14 and Homebrew in Rosetta 2 so I understand that you are not providing support for it, but to my knowledge, this issue IS NOT software related so I am submitting it as an issue anyway. I strongly believe this issue can be replicated on any macOS version, though I haven't tested it, as the error I am facing is a 404 HTTP (curl) error (which can be confirmed through the browser by opening https://dlcdn.apache.org/serf/serf-1.3.9.tar.bz2).

In the subversion formula, line 73 and 74 are : 

url "https://www.apache.org/dyn/closer.lua?path=serf/serf-1.3.9.tar.bz2"
mirror "https://archive.apache.org/dist/serf/serf-1.3.9.tar.bz2"

By opening https://dlcdn.apache.org/serf/ (the URL Homebrew is apparently using to download serf) in your browser, you can see that version 1.3.9 does not appear, but version 1.3.10 does. The mirror URL provided in the config does work, but apparently is not used by the formula during download. Curl throws a 404 not found and stops all execution of Homebrew.


For compliance, brew gist-logs subversion returns the following:

Error: You are using macOS 14.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install subversion

Because another package that I wanted to install needed subversion as a dependency and encountered the same issue, so I went on trying to manually install it. No success due to the issue described above and below).

### What happened (include all command output)?

==> Fetching subversion
Warning: Building subversion from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /usr/local/homebrew/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /usr/local/homebrew)
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/03cf8088210822aa2c1ab544ed58ea04c897d9c4/libtool/configure-big_sur.diff
Already downloaded: /Users/plugn/Library/Caches/Homebrew/downloads/195208ba31cadc265ea97bb8aad4e78caab1200daf4d855e6c839b5f987f92db--configure-big_sur.diff
==> Downloading https://github.com/encukou/py3c/archive/v1.1.tar.gz
Already downloaded: /Users/plugn/Library/Caches/Homebrew/downloads/341faafd274c164961d080ffbaab85a010d9385563dc574212244e60297de7b8--py3c-1.1.tar.gz
Error: subversion: Failed to download resource "subversion--serf"
Failure while executing; `/usr/bin/env /usr/local/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.21-4-ge37650d\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 14.0\)\ curl/8.0.1 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dlcdn.apache.org/serf/serf-1.3.9.tar.bz2` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/2 404 
server: Apache
content-type: text/html; charset=iso-8859-1
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
date: Wed, 07 Jun 2023 08:13:09 GMT
age: 7029
x-served-by: cache-hel1410020-HEL, cache-par-lfpg1960079-PAR
x-cache: HIT, HIT
x-cache-hits: 9, 1
x-timer: S1686125590.833360,VS0,VE1
content-length: 196

### What did you expect to happen?

Succeed to download the resource "subversion--serf" with whatever version is needed and complete the installation.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install subversion
```

**Comment by carlocab** [comment]
Please open a pull request. There are too many formulae in this repository for it to be reasonable to track outdated ones as issues. Thanks!

**Comment by Bo98** [comment]
> Warning: Building subversion from source as the bottle needs:
> * HOMEBREW_CELLAR: /usr/local/Cellar (yours is /usr/local/homebrew/Cellar)
> * HOMEBREW_PREFIX: /usr/local (yours is /usr/local/homebrew)

Out of interest, how did you install Homebrew? I've seen a few people install to this (non-default) location so am wondering whether that's intentionally done or not.

**Comment by PlugNPush** [comment]
It is intentional, I'm trying to play around with Apple's Game Porting Tooklit and it needs to be run in Rosetta 2 mode. To avoid merging ARM and X64 tools, I created a new /usr/local/homebrew directory to install my X64 Homebrew, used only when necessary via arch -x86_64 /usr/local/homebrew/bin/brew install <formula>

**Comment by Bo98** [comment]
That's fine, was just checking. :+1:

The default for x64 is `/usr/local` (without the homebrew) but if you already have other stuff in /usr/local that makes sense. The consequence will be not being able to use pre-built bottles so you may come across issues like the one you had.

**Comment by PlugNPush** [comment]
@Bo98 I tried to move it back to /usr/local, but the issue I faced is related to permissions: 

<img width="524" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/31410359/02f95300-4de9-4c86-b9c0-b914ad7cf918">

 
<img width="292" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/31410359/8131ca05-6d8a-4092-82b8-9feee21579bd">

If you know the magic trick to make it work I'll take it

**Comment by Bo98** [comment]
The way it works in `/usr/local` is a bit special. Everything in the [brew](https://github.com/Homebrew/brew) repository is stored in `/usr/local/Homebrew` (uppercase H) with [a symlink](https://github.com/Homebrew/install/blob/716a1d024f32890ef75ea82c18a769abc24e9475/install.sh#L924) in `/usr/local/bin/brew`. Stuff like the `Cellar` live at `/usr/local/Cellar`, along with everything else e.g. `/usr/local/bin`, `/usr/local/include`, `/usr/local/lib`. The installer handles all this automatically.

**Comment by PlugNPush** [comment]
Thanks, I reinstalled it fully and it seems to work now 👍
