### ISSUE TITLE
libusb on Mac OS X (Sierra) - where are the binaries?

### ISSUE THREAD

**Issue by b0mbel** [Homebrew/homebrew-core#13339]
Hej,

I do need libusb on my OS X to understand where my dongle is mounting to passthrough it to a QEMU session.

I`ve already installed brew and other tools, which work great.

But I do have an issue with libusb, and I do not understand why ;(

_MAC:lib user$ brew install libusb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
Warning: libusb-1.0.21 already installed
MAC:lib user$ libusb
-bash: libusb: command not found_

Anyone who could help me with that?
Or give me a hint how to fix it?

Cheers,
-b0mbel

**Comment by pvtmert** [comment]
libusb as name states, is a library.

you can see files via: `brew list libusb` (generic) `brew list --verbose libusb` (recursively)
