### ISSUE TITLE
Wireshark-ChmodBPF Reinstall Fail

### ISSUE THREAD

**Issue by bgausden** [Homebrew/homebrew-core#13358]
# Please always follow these steps:
- [X ] Confirmed this is a problem with only one, specific formula and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
- [ X] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Upgraded wireshark, attempted to re-install ChmodBPF to capture any possible changes there.

- What happened (include command output)
Reinstall fails with warning that username and password (not prompted for) are required:
[command output](https://gist.github.com/bgausden/e0f6586dde3ed19a2649443ce1982bb0)

- What you expected to happen
Successful reinstallation of ChmodBPF cask
- Step-by-step reproduction instructions (by running `brew install` commands)
brew cask reinstall wireshark-chmodbpf

- brew config output
[brew config](https://gist.github.com/bgausden/568e82d3d46284585f5cbb2df9b32a92)

-brew doctor output
```
barryg@barrys-mbp ~> brew doctor
Your system is ready to brew.
```

**Comment by ilovezfs** [comment]
Please report this to https://github.com/Caskroom/homebrew-cask.
