### ISSUE TITLE
groff: man float

### ISSUE THREAD

**Issue by polluks** [Homebrew/homebrew-core#133561]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.0.22-6-gf71294d
ORIGIN: https://github.com/Homebrew/brew
HEAD: f71294d483e1ce9920fd10d8169b1419c0ba41fb
Last commit: 2 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a246363012eb92ffe3fc4c3a0f5f4ab0969cde3f
Core tap last commit: 5 months ago
Core tap branch: master
Core tap JSON: 13 Jun 17:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.h7rfNcT7bN/org.xquartz:0
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I want one manual page of float and its table.

### What happened (include all command output)?

man -d float
...
-- Command: cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man && /usr/bin/zcat -f "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man3/float.3" | tbl | groff -S -P-h -Wall -mtty-char -man -Tascii -P-c | /usr/local/bin/less
-- Command: cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man && /usr/bin/zcat -f "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man/man3/float.3" | mandoc  | /usr/local/bin/less

### What did you expect to happen?

One man, one less.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install groff
man float
q
q
```

**Comment by cho-m** [comment]
Why do you think this is a Homebrew issue? `groff` is only a command being run by Apple's `man` and the behavior you see is most likely from `man`.

I think this is an Apple issue and should be reported to them.

You can see how their `man` command looks at https://github.com/apple-oss-distributions/man/blob/main/man/man.sh#L380-L401 where the `return` was commented out:
```sh
                if which -s groff; then
#ifdef __APPLE__
                        man_display_page_groff $path
#else
#                       man_display_page_groff
#endif
                else
#ifdef __APPLE__
                        echo "This manpage is not compatible with mandoc(1) and might display incorrectly." >&2


                        # Leave sufficient time to note the above warning.
                        sleep 1
#else
#                       echo "This manpage needs groff(1) to be rendered" >&2
#                       echo "First install groff(1): " >&2
#                       echo "pkg install groff " >&2
#                       ret=1
#endif
                fi
#ifndef __APPLE__
#               return
#endif
```

If they add a `return` after `man_display_page_groff` then it would avoid re-opening the manpage later on via `mandoc`

**Comment by polluks** [comment]
I opened a ticket at Apple support.
