### ISSUE TITLE
GDAL is missing WEBP support

### ISSUE THREAD

**Issue by gtnbssn** [Homebrew/homebrew-core#133603]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew gist-logs gdal
Error: No logs.
> brew config
HOMEBREW_VERSION: 4.0.22-6-gf71294d
ORIGIN: https://github.com/Homebrew/brew
HEAD: f71294d483e1ce9920fd10d8169b1419c0ba41fb
Last commit: 12 hours ago
Core tap JSON: 14 Jun 02:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am trying to create Cloud Optimized Geotiffs using WEBP in order to save space.

This is supposed to be supported by GDAL: https://gdal.org/drivers/raster/cog.html#general-creation-options

### What happened (include all command output)?

```shell
> gdal_translate input.tif output.cog.tif -of COG -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=WEBP
Input file size is 25948, 17270
Warning 6: 'WEBP' is an unexpected value for COMPRESS creation option of type string-select.
0...10...20...30...40...50Warning 6: 'WEBP' is an unexpected value for COMPRESS creation option of type string-select.
ERROR 1: Cannot create TIFF file due to missing codec for WEBP.
```

### What did you expect to happen?

I was expecting the geotiff to be created without error.

Things I have tried:

Reinstalling required packages:
```brew reinstall webp libtiff gdal```

Adding webp support to libtiff, the formula for libtiff disables it:
https://github.com/Homebrew/homebrew-core/blob/89ce019dcc38a3721b6da661dd2e1063e9319398/Formula/libtiff.rb#LL35C21-L35C21

```brew edit libtiff```
(change the line to `--enable-webp` as seen [here](https://github.com/Homebrew/homebrew-core/issues/106450#issuecomment-1244250399) for zstd)
```brew reinstall libtiff```

Issue wasn't solved.

The GDAL code seems to indicate that, in order for webp to work, GDAL needs to use its internal libtiff library:
https://github.com/OSGeo/gdal/blob/b1c9c12ad373e40b955162b45d704070d4ebf7b0/gdal/frmts/gtiff/geotiff.cpp#L99

So I tried editing the gdal formula and adding this option instead: https://gdal.org/development/building_from_source.html#cmdoption-arg-GDAL_USE_TIFF_INTERNAL
```brew edit gdal```
add a line with `-GDAL_USE_TIFF_INTERNAL=ON` in the args.
```brew reinstall gdal```

Still seeing the same issue when trying to build a COG with WEBP.

### Step-by-step reproduction instructions (by running `brew` commands)

Install GDAL:
```shell
brew install gdal
```

Create a COG with WEBP:
```shell
gdal_translate input.tif output.cog.tif -of COG -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=WEBP```
```

**Comment by carlocab** [comment]
This requires enabling `webp` support in `libtiff`, but that requires resolving the circular dependency it creates. See #119767.

**Comment by gtnbssn** [comment]
Thanks! Sorry i hadn't found this 🙏.

Is there something I can do to help with this? The linked PR was closed by its author.

**Comment by carlocab** [comment]
Well, to resolve the circular dependency I think the only solution is to remove the `libtiff` dependency from `webp` and then make `webp` a dependency of `libtiff`.

However, before we decide to do that, we should have a good understanding of what the consequences of doing it will be. In particular, we need to assess the tradeoffs of doing so, so it would be good for you to help us work that out.

**Comment by carlocab** [comment]
Also CC @Firefishy since you might be interested in this discussion.

**Comment by Firefishy** [comment]
The way debian and others break the circular dependence (libtiff -> webp -> libtiff) is they have split the webp package into webp (cli tools with libtiff support) and libwebp (not linked to libtiff).

**Comment by carlocab** [comment]
I'm open to trying that, but it might be a bit difficult to make this work for Homebrew without supporting upstream changes. Care to give it a go?

**Comment by gtnbssn** [comment]
> I'm open to trying that, but it might be a bit difficult to make this work for Homebrew without supporting upstream changes. Care to give it a go?

Sorry I am probably being a bit naive here but just seeing I could help, to the modest extent of my abilities...

What would be the upstream changes to support?

**Comment by Firefishy** [comment]
> I'm open to trying that, but it might be a bit difficult to make this work for Homebrew without supporting upstream changes. Care to give it a go?

No upstream changes are required.

Debian simply packages as follows:
webp -> /usr/bin/* (built from libwebp source)
libwebp -> /usr/lib/* (built from libwebp source)

libwebp package has no external dependencies
webp package has dependencies on libwebp, libjpeg62-turbo, libtiff (and others)
