### ISSUE TITLE
dnscontrol version does not return the current version

### ISSUE THREAD

**Issue by truthdoug** [Homebrew/homebrew-core#133862]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.0.22-10-gab20a6e
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab20a6e0f598d9fdc7858020ce83b5ce58a85f18
Last commit: 17 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c1408e72eaa44545ead62fff22a0866a42033ae
Core tap last commit: 5 months ago
Core tap branch: master
Core tap JSON: 15 Jun 17:10 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.6-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to run `dnscontrol version` to see which version of dnscontrol I have installed. 

I believe I have a fix which I'll cite in a comment.

### What happened (include all command output)?

Running `dnscontrol version` always returned `-dev` and not the current version:

```
$ dnscontrol version
dnscontrol -dev
```

### What did you expect to happen?

I expected to see the current version. Currently I rely on `brew info dnscontrol` since `dnscontrol version` doesn't work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install dnscontrol
2. dnscontrol version
```

**Comment by carlocab** [comment]
This patch should probably work:
```diff
diff --git a/Formula/dnscontrol.rb b/Formula/dnscontrol.rb
index e77798db02a..ad20e799a11 100644
--- a/Formula/dnscontrol.rb
+++ b/Formula/dnscontrol.rb
@@ -27,10 +27,11 @@ class Dnscontrol < Formula
   depends_on "go" => :build
 
   def install
-    system "go", "build", *std_go_args(ldflags: "-s -w")
+    system "go", "build", *std_go_args(ldflags: "-s -w -X main.SHA=#{version}")
   end
 
   test do
+    assert_match version.to_s, shell_output("#{bin}/dnscontrol version")
     (testpath/"dnsconfig.js").write <<~EOS
       var namecom = NewRegistrar("name.com", "NAMEDOTCOM");
       var r53 = NewDnsProvider("r53", "ROUTE53")
```
Please feel free to open a pull request, preferably after testing it out.

**Comment by truthdoug** [comment]
PR submitted: https://github.com/Homebrew/homebrew-core/pull/133864

**Comment by j-f1** [comment]
Hm, the result doesn’t seem to exactly match the released version (https://github.com/StackExchange/dnscontrol/releases/tag/v4.1.1):

```shellsession
$ /opt/homebrew/bin/dnscontrol version
dnscontrol  (4.1.1)
$ ~/Downloads/dnscontrol_4.1.1_darwin_all/dnscontrol version
dnscontrol "4.1.1" ("9c9ff4d45a970cb851d9fda013dc9da631e54ce5") built 06 Jun 23 11:11 EDT
```

**Comment by carlocab** [comment]
Yes, we tweaked the version output a little in #133933, so that's why the version output has now changed slightly.
