### ISSUE TITLE
Failed to download resource "kim-api"

### ISSUE THREAD

**Issue by cprivetom** [Homebrew/homebrew-core#133936]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Hi. I'm trying to install lammps package on my MAC, but see following things:
==> Fetching kim-api
Error: lammps: Failed to download resource "kim-api"
Download failed: Homebrew-installed `curl` is not installed for: https://s3.openkim.org/kim-api/kim-api-2.3.0.txz
How I can install lammps?
Thank you!
Julia
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

to install lammps with comand

brew install lammps

### What happened (include all command output)?

==> Fetching kim-api
Error: lammps: Failed to download resource "kim-api"
Download failed: Homebrew-installed `curl` is not installed for: https://s3.openkim.org/kim-api/kim-api-2.3.0.txz

### What did you expect to happen?

installation finished without error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. I install homebrew using site homebrew

2. I used command: brew install lammps
```

**Comment by SMillerDev** [comment]
What happens if you run `brew install curl` first?
