### ISSUE TITLE
mp4v2 missing man page

### ISSUE THREAD

**Issue by jprokos** [Homebrew/homebrew-core#13413]
I installed mp4v2 using
`homebrew install mp4v2`

When trying to read the man page from terminal it's not found.
`No manual entry for mp4v2`

I expect the man page to be installed for all binaries installed with homebrew.

The homebrew page for the formula clearly shows that the manual is included in the install

`class Mp4v2 < Formula
  desc "Read, create, and modify MP4 files"
  homepage "https://code.google.com/archive/p/mp4v2/"
  url "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/mp4v2/mp4v2-2.0.0.tar.bz2"
  sha256 "0319b9a60b667cf10ee0ec7505eb7bdc0a2e21ca7a93db96ec5bd758e3428338"

  bottle do
    cellar :any
    rebuild 1
    sha256 "6cab2b32c845f6d54cdb8d64c558126cec39c27fb77a92f204bb8abda1c0ccfa" => :sierra
    sha256 "52d299e61126db288d73a3e6e8b40c3eff25af1c7498c4a74787dce2dda02e9a" => :el_capitan
    sha256 "14ca4b71690959d461d41b4338be70005de4553566996677f973094c1a56c3fb" => :yosemite
    sha256 "bb51275338ca5b157b303fb9d024922c9b73ddcac69973ba2fe9d880ad6dc914" => :mavericks
    sha256 "ec42cf726369e5f6c3a4956cffbf44ab8d4b74f5bec35892a0c041641c2f4d4c" => :mountain_lion
  end

  def install
    system "./configure", "--disable-debug", "--prefix=#{prefix}"
    system "make"
    system "make", "install"
    **system "make", "install-man"**
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mp4art --version")
  end
end`

https://github.com/Homebrew/homebrew-core/blob/master/Formula/mp4v2.rb
http://brewformulas.org/Mp4v2

**Comment by jprokos** [comment]
If there is no immediate solution can someone explain the best way to download the original binary and remove the man page from that package and get it into the right spot with symlinks, etc. so Terminal can read it?

**Comment by DomT4** [comment]
Manpages are there...

```
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4art
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4chaps
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4extract
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4file
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4info
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4subtitle
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4tags
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4track
/usr/local/Cellar/mp4v2/2.0.0/bin/mp4trackdump
/usr/local/Cellar/mp4v2/2.0.0/COPYING
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/chapter.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/file.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/file_prop.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/general.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/isma.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/itmf_generic.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/itmf_tags.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/mp4v2.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/platform.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/project.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/sample.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/streaming.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/track.h
/usr/local/Cellar/mp4v2/2.0.0/include/mp4v2/track_prop.h
/usr/local/Cellar/mp4v2/2.0.0/INSTALL_RECEIPT.json
/usr/local/Cellar/mp4v2/2.0.0/lib/libmp4v2.2.dylib
/usr/local/Cellar/mp4v2/2.0.0/lib/libmp4v2.a
/usr/local/Cellar/mp4v2/2.0.0/lib/libmp4v2.dylib
/usr/local/Cellar/mp4v2/2.0.0/README
/usr/local/Cellar/mp4v2/2.0.0/share/man/man1/mp4art.1
/usr/local/Cellar/mp4v2/2.0.0/share/man/man1/mp4file.1
/usr/local/Cellar/mp4v2/2.0.0/share/man/man1/mp4subtitle.1
/usr/local/Cellar/mp4v2/2.0.0/share/man/man1/mp4track.1
```

**Comment by jprokos** [comment]
Yes.... my directories look the same. However, Terminal does not find them. Months before installing this binary I had added the following line in .bashrc
`export MANPATH=$HOMEBREWDIR/share/man:$MANPATH`

Still no manual opens when executing  `man mp4v2` in terminal.

Last night I did some searching and tried the following which also made no difference.
`sudo -s` 
`echo "/usr/local/homebrew/bin" > /etc/paths.d/homebrew`
`echo "/usr/local/homebrew/share/man" > /etc/manpaths.d/homebrew`

**Comment by DomT4** [comment]
Yeah, what I'm saying is that there's no manpage called `mp4v2`. I can't find any indication that that would be incorrect on the Homebrew side of things. The four manpages are `mp4art`, `mp4file`, `mp4subtitle` & `mp4track`. Have you tried running `man mp4art`?

**Comment by jprokos** [comment]
I see.
