### ISSUE TITLE
ld: library not found for -lopencv_ts

### ISSUE THREAD

**Issue by fivetech** [Homebrew/homebrew-core#1341]
After upgrading opencv3 via homebrew, when I try to build the project, Xcode says: 

```
 ld: library not found for -lopencv_ts
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, it works when I remove -lopencv_ts from "Other Linker Flags" section. 

By the way, I run "brew doctor" and get this result:

```
Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.
```

However, I have up-to-date version of Xcode. There is no 7.3.1. version of Xcode.

**Comment by DomT4** [comment]
> After upgrading opencv3 via homebrew

You'll need to report problems with this formula to the [science tap](https://github.com/Homebrew/homebrew-science) I'm afraid. That's where the formula originates and they'll be able to help you better consequently.

> However, I have up-to-date version of Xcode. There is no 7.3.1. version of Xcode.

<img width="690" alt="screen shot 2016-05-22 at 15 55 03" src="https://cloud.githubusercontent.com/assets/6998367/15454605/d053cd30-2035-11e6-856a-1cf1327f07df.png">

?
