### ISSUE TITLE
protobuf: Static library missing from v23 bottle

### ISSUE THREAD

**Issue by jbeyerstedt** [Homebrew/homebrew-core#134170]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.0.24
ORIGIN: https://github.com/Homebrew/brew
HEAD: 54c8876dc39047c04de15e7d212979ae8d98cf1c
Last commit: 3 hours ago
Core tap JSON: 19 Jun 15:43 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.z8J4bbzsgE/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libndi.4.dylib
  /usr/local/lib/libtbb.12.2.dylib
  /usr/local/lib/libtbb.12.dylib
  /usr/local/lib/libtbb.dylib
  /usr/local/lib/libtbbmalloc.2.2.dylib
  /usr/local/lib/libtbbmalloc.2.dylib
  /usr/local/lib/libtbbmalloc.dylib
  /usr/local/lib/libtbbmalloc_proxy.2.2.dylib
  /usr/local/lib/libtbbmalloc_proxy.2.dylib
  /usr/local/lib/libtbbmalloc_proxy.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I tried to compile C++ code against the libprotobuf static library, which worked before updating to the latest "protobuf" version.

### What happened (include all command output)?

I ran `brew upgrade` and there was no `libprotobuf.a` any more, just the shared/ dynamic libraries of libprotobuf.

### What did you expect to happen?

Still having a recent version of the static libprotobuf library.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install protobuf
ls -l /usr/local/lib/libprotobuf*
find /usr/local/Cellar/ -name "libprotobuf.a"
```

**Comment by jbeyerstedt** [comment]
Sorry, that I didn't solve all checkboxes, but the `bottle.2.tar.gz` doesn't contain the static libraries, so the issue is not related to the doctor issues.

**Comment by carlocab** [comment]
This change was intended. See https://github.com/Homebrew/homebrew-core/commit/5c6d1bc12fafdae166757e2efd6afb6142ff610a.

We'll review PRs to improve this (but we may not merge them).
