### ISSUE TITLE
please stop offering --HEAD installations of zig, you are causing trouble upstream

### ISSUE THREAD

**Issue by andrewrk** [Homebrew/homebrew-core#134298]
Hello, [upstream](https://ziglang.org/) here.

I am not happy with the way you are sending users to us:
 * https://github.com/ziglang/zig/issues/16102
 * https://github.com/ziglang/zig/issues/15979
 * https://github.com/ziglang/zig/issues/15956
 * https://github.com/ziglang/zig/issues/15121

It is not appropriate for users to install a development commit of Zig with homebrew. Please stop offering this to them.

Furthermore, you have this text:

> Do not report this issue to Homebrew/brew or Homebrew/core!
> Please create pull requests instead of asking for help on Homebrew's GitHub, Twitter or any other official channels.

This is extremely rude, because you are effectively using our upstream issue tracker for your bugs.

Please, desist.

**Comment by SMillerDev** [comment]
`--HEAD` mode is compiling from source, which is not a supported case by Homebrew. It only exists for developers to test releases so users aren't supposed to report this upstream either, they are supposed to fix it.

I can make a pull request to remove the head definition though, but it might take a while for me to have time for it. It might be faster to do it yourself.

**Comment by SMillerDev** [comment]
Just as an FYI, it was added roughly 5 years ago https://github.com/Homebrew/homebrew-core/pull/31864.

**Comment by SMillerDev** [comment]
> It is not appropriate for users to install a development commit of Zig with homebrew. Please stop offering this to them.

Could you edit your documentation to stop recommending it then? https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager

> This is extremely rude, because you are effectively using our upstream issue tracker for your bugs.

I'm not sure how that line suggests to go to the upstream bugtracker though, all it suggests is to make a pull request to fix the issues.

**Comment by andrewrk** [comment]
> Could you edit your documentation to stop recommending it then? https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager

Thank you for pointing this out. It's fixed now.

I'm sorry for my visible frustration when filing this issue. At first, I suggested that we work with homebrew to get the issue fixed, since the error message makes it look very much like homebrew's problem rather than upstream's. But then I saw that message "don't file a bug report on homebrew", and it made me upset that y'all don't want to work together to solve the problem. Instead, users are coming to our bug tracker, expecting us to solve your homebrew bugs.

I am wiling to have a tracking issue upstream for homebrew, even though it's technically out of scope of upstream, but you need to be willing to have an issue open as well.

As for --HEAD, my preference speaking for upstream is for homebrew to not offer it, unless homebrew is willing to support it directly. And clearly you are not willing, based on that messaging. Upstream provide development binaries, as well as having correct, working, build-from-source instructions. Homebrew is the buggy party here, and is also the party unwilling to accept bug reports.

Even this issue, I had to pretend that it was a bug report, and then edit it later. It unnecessarily creates a hostile relationship, when what I really want to do is to work together in good faith.

**Comment by carlocab** [comment]
We're happy to work with you to solve these issues: the error message you quote even suggests using our [discussions page](https://github.com/orgs/Homebrew/discussions) for it (except this part appears to be omitted).

Our issue tracker is for higher-priority, actionable items (but we also spend a lot of time trying to resolve discussion posts too), and the template is focused on handling 95% of bug reports that we get (which yours doesn't quite fall under).

**Comment by SMillerDev** [comment]
> But then I saw that message "don't file a bug report on homebrew", and it made me upset that y'all don't want to work together to solve the problem. Instead, users are coming to our bug tracker, expecting us to solve your homebrew bugs.

It seems to be an unfortunate collision of circumstances where Zig was recommending an install method Homebrew does not want to support (but offers anyway for people who know what they are doing). Redirecting users to the upstream bugtracker is never the intention and is not part of the message for that exact reason.

> Upstream provides development binaries, as well as having correct, working, build-from-source instructions. 

Sounds like a good alternative for users.

> Even this issue, I had to pretend that it was a bug report, and then edit it later, because of you aggressive issue templates. It unnecessarily creates a hostile relationship, when what I really want to do is to work together in good faith.

It is unfortunate you feel that way, however as carlocab pointed out we are optimising for the majority of our bug reports that does not really cover your usecase. But you got your message out there and all is good in the world for Zig users in Homebrew again.

**Comment by seanfarley** [comment]
I found this thread since zig's [website itself instructed me](https://ziglang.org/learn/getting-started/#macos) to use `brew install zig --HEAD`. It's disappointing (and frustrating) to walk into such a hostile thread. I am sad and discouraged from even using zig because of so many zig libraries *requiring* a pre-release. Oh well.
