### ISSUE TITLE
Failed to download resource "qcachegrind"

### ISSUE THREAD

**Issue by joetroyer** [Homebrew/homebrew-core#13438]
qcachegrind formula is getting this error:

Error: Failed to download resource "qcachegrind"
Download failed: https://download.kde.org/stable/applications/16.12.0/src/kcachegrind-16.12.0.tar.xz

[homebrew-core/blob/master/Formula/qcachegrind.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qcachegrind.rb#L4)

**Comment by alexreinking** [comment]
The new url appears to be

    https://download.kde.org/stable/applications/17.04.0/src/kcachegrind-17.04.0.tar.xz

It should just be a matter of updating the SHA keys and dropping this one in.

**Comment by dunn** [comment]
If the newer version works then go for it; surprising that KDE is removing old versions from the download server though.
