### ISSUE TITLE
tcl-tk missing after untapping Dupes

### ISSUE THREAD

**Issue by remy-actual** [Homebrew/homebrew-core#13444]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

# The problem

How do I get brew to find  [tcl-tk in its new home](https://github.com/Homebrew/homebrew-core/blob/ea84b8893cafe2c60a746cf5c5ad9116d14ed7fc/Formula/tcl-tk.rb)?

Seems to be the same problem as #12322 but with a different formula.  

Had previously installed Formula `tcl-tk` from the Dupes tap, before it was migrated to Core.  

Attempting to re-install from core after removing tcl-tk  and untapping dupes: 

```
$ brew install tcl-tk
Error: No available formula with the name "tcl-tk"
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

$ brew search tcl
tclap vtclock # no tcl-tk

$ brew gist-logs tcl-tk
Error: No available formula with the name "tcl-tk"

$ brew config
HOMEBREW_VERSION: 1.2.0-64-gfa1e23823
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa1e23823c623adc235eb0de44eb84539ac5a17d
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae1c33fbf824ab4b6a609a222e9cc012c47eadda
Core tap last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/remy/.rbenv/shims/ruby => /Users/remy/.rbenv/versions/2.3.3/bin/ruby
Java: 1.8.0_92
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

$ brew doctor
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mariadb
```

**Comment by DomT4** [comment]
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae1c33fbf824ab4b6a609a222e9cc012c47eadda
Core tap last commit: 4 months ago

That'll be your problem 😉. What does:
```bash
cd $(brew --repo)/Library/Taps/homebrew/homebrew-core && git status
```
return?

**Comment by remy-actual** [comment]
Aha! Thank you... I edited a formula for a PR some time back and forgot to git checkout master afterwards.  
Derp :see_no_evil:

**Comment by DomT4** [comment]
This comes up at least once a week, so, if any consolation you aren't the first person by a long way to end up forgetting to check `master` back out 😉

**Comment by remy-actual** [comment]
Fresh breadcrumbs for the Google trail ...:bread:
