### ISSUE TITLE
Failed during: git config remote.origin.url https://github.com/Homebrew/brew

### ISSUE THREAD

**Issue by aunapat** [Homebrew/homebrew-core#13458]
Error Failed during: git config remote.origin.url https://github.com/Homebrew/brew

I don't know how to fix it.

help me pls. 

Thank you.

**Comment by aunapat** [comment]
Next step 

Can you Resolve this

Error: invalid byte sequence in UTF-8
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:341:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:334:in `+'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:346:in `resolved_path'
/usr/local/Homebrew/Library/Homebrew/keg.rb:237:in `optlinked?'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:274:in `each'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:274:in `detect'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:274:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1051:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1048:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:1048:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:90:in `<main>'


because I don't know how to do?

**Comment by MikeMcQuaid** [comment]
Try to uninstall and reinstall Homebrew. Please always fill out the issue template in future.
