### ISSUE TITLE
Could homebrew reinstall packages if dependent package changed?

### ISSUE THREAD

**Issue by Aqualon** [Homebrew/homebrew-core#134625]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.0.24
ORIGIN: https://github.com/Homebrew/brew
HEAD: 54c8876dc39047c04de15e7d212979ae8d98cf1c
Last commit: 3 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eec9e20774f5398bd3513952bfca0ba4d73f29bf
Core tap last commit: 4 months ago
Core tap branch: master
Core tap JSON: 20 Jun 19:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.40.1 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

```shell
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Hi, I just had a failure in starting mysql 8 (`/opt/homebrew/Cellar/mysql/8.0.33_2`), which complained about
`Library not loaded: /opt/homebrew/opt/icu4c/lib/libicuuc.72.dylib`

The actual files I have after running `brew upgrade` yesterday are
```
/opt/homebrew/opt/icu4c/lib/libicuuc.73.2.dylib
/opt/homebrew/opt/icu4c/lib/libicuuc.73.dylib
/opt/homebrew/opt/icu4c/lib/libicuuc.a
/opt/homebrew/opt/icu4c/lib/libicuuc.dylib
```

After a `brew reinstall mysql`, mysql runs again as expected. I also had this similar issue in the past, when readline was updated and then I had to reinstall ruby.

Since brew seems to know, what depends on icu4c according to the uninstall output
```
❯ brew uninstall icu4c
Error: Refusing to uninstall /opt/homebrew/Cellar/icu4c/73.2
because it is required by cassandra, ffmpeg, harfbuzz, libass, librsvg, mysql, node, openjdk@11, pango, prettier and tesseract, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies icu4c
```
would it make sense to reinstall all formulas, that have this dependency to be sure, they use the right version? Or is this an issue with mysql, that it's not using the `/opt/homebrew/opt/icu4c/lib/libicuuc.dylib` symlink, but a distinct version (I have not very much knowledge about C/C++ libraries and how they are handled).

**Comment by SMillerDev** [comment]
The MySQL version bum from `8.0.33_1` to `8.0.33_2` did exactly that. Did you have a MySQL instance running before that might have been using the old binary?

**Comment by Aqualon** [comment]
Ok, probably it was the older version then. Just noticed that brew upgrade didn't finish completely due to conflict between gdu and coreutils formulas, maybe this causes icu4c to be updated but not mysql yesterday. So an issue on my side.
