### ISSUE TITLE
gspell 1.4.0 fails to build

### ISSUE THREAD

**Issue by muellermartin** [Homebrew/homebrew-core#13509]
gspell 1.4.0 fails during build in the configure phase with following error:

    configure.ac:130: error: macro GTK_DOC_CHECK is not defined; is a m4 file missing?

Full log (generated with `brew gist-logs gspell`): https://gist.github.com/muellermartin/92b1a1fb6393614816a3405781dfb0d6#file-01-autoreconf

**Comment by ilovezfs** [comment]
I cannot reproduce this issue with the version in core, which is 1.4.1, revision 1. Also, your brew is quite outdated.

**Comment by muellermartin** [comment]
Sorry for the confusion - I don't know how I ran the update for 1.4.0... I tried it again after upgrading brew and it tried to compile gspell 1.4.1 like you pointed out, but it fails with the same error.

Here are the logs for the current run: https://gist.github.com/e2b729146bff552688d075de38f86588

**Comment by muellermartin** [comment]
Note: I'm still having this issue but simply adding the line `depends_on "gtk-doc" => :build` to the Formula as build dependency resolves this for me.
