### ISSUE TITLE
psql causing segfaults

### ISSUE THREAD

**Issue by matthughes** [Homebrew/homebrew-core#135170]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config && brew doctor
HOMEBREW_VERSION: 4.0.26
ORIGIN: https://github.com/Homebrew/brew
HEAD: eff45ef570f265e226f14ce91da72d7a6e7d516a
Last commit: 5 hours ago
Core tap JSON: 27 Jun 19:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
Your system is ready to brew.```
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run `psql` to connect to a local postgres database (or remote).

### What happened (include all command output)?

Get segfault.

```
> psql -Uonyx -donyx -hlocalhost -p5436
[1]    57520 segmentation fault  psql -Uonyx -donyx -hlocalhost -p5436

>~ otool -L /opt/homebrew/bin/psql
/opt/homebrew/bin/psql:
	/opt/homebrew/lib/postgresql@14/libpq.5.dylib (compatibility version 5.0.0, current version 5.14.0)
	/opt/homebrew/opt/readline/lib/libreadline.8.dylib (compatibility version 8.2.0, current version 8.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
➜  ~ lldb -- psql -Uonyx -donyx -hlocalhost -p5436
(lldb) target create "psql"
Current executable set to '/opt/homebrew/bin/psql' (arm64).
(lldb) settings set -- target.run-args  "-Uonyx" "-donyx" "-hlocalhost" "-p5436"
(lldb) run
Process 57469 launched: '/opt/homebrew/bin/psql' (arm64)
Process 57469 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xce2d3793ac6f0025)
    frame #0: 0x00000001003d2c18 libkrb5.3.3.dylib`krb5_free_principal + 20
libkrb5.3.3.dylib`krb5_free_principal:
->  0x1003d2c18 <+20>: ldr    x0, [x1, #0x18]
    0x1003d2c1c <+24>: cbz    x0, 0x1003d2c6c           ; <+104>
    0x1003d2c20 <+28>: ldr    w20, [x19, #0x20]
    0x1003d2c24 <+32>: cmp    w20, #0x1
```

### What did you expect to happen?

To be able to connect to the console.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install postgresql@14
- attempt to connect to postgres database
```

**Comment by limingxinleo** [comment]
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/a83c6484fcc2fc2addabbca089ed31bd7ac7b5ae/Formula/postgresql%4014.rb

brew uninstall postgresql@14
brew install postgresql@14.rb

**Comment by matthughes** [comment]
What is the difference?  Why does one work and not the other?  Note that
the segfault doesn’t occur 100% reliably but it is more often than not.

**Comment by Bo98** [comment]
I've been unable to reproduce so far, though I am running x86_64 and am only trying the most basic of setups (default configuration with `brew services run postgresql@14`):

```
$ psql -dpostgres
psql (14.8 (Homebrew))
Type "help" for help.

postgres=# 
```

**Comment by cho-m** [comment]
Do we need GSSAPI authentication to reproduce? Looks like failure is happening interacting with `krb5` (`krb5_free_principal`).

**Comment by catks** [comment]
Seems related to  https://github.com/ged/ruby-pg/issues/538 and https://github.com/ged/ruby-pg/issues/311#issuecomment-1609970533
