### ISSUE TITLE
openssh 9.3p1_1 spawns zombie process

### ISSUE THREAD

**Issue by robertc99** [Homebrew/homebrew-core#135197]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
rhc900@Roberts-MacBook-Pro ne4-puppet % brew config
HOMEBREW_VERSION: 4.0.26-2-gc5cbe64
ORIGIN: https://github.com/Homebrew/brew
HEAD: c5cbe6406b8b9d040c5d1850b5f041af4ddef83c
Last commit: 15 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fbf693010429a62c6d6a807750262508000736a
Core tap last commit: 5 months ago
Core tap branch: master
Core tap JSON: 28 Jun 07:47 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.lLN6KWSVZm/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1

rhc900@Roberts-MacBook-Pro ne4-puppet % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

This has occured with the latest openssh (9.3p1_1).
It didnt happen with 9.3p1

I wanted to log into a remote machine via a jumpbox using ssh.

### What happened (include all command output)?

after logging out of the remote machine, a "rogue" ssh process is left consuming all CPU.

rhc900@Roberts-MacBook-Pro ~ % ssh -J 130.56.243.154 10.0.0.8
Last login: Wed Jun 28 18:01:46 2023 from 10.0.3.140
[rhc900@rhc900-test8 ~]$ logout

rhc900@Roberts-MacBook-Pro ~ % ps auxww | grep ssh
rhc900           23925  99.3  0.0 34155268   4620 s002  R     6:03pm   0:04.97 ssh -W [10.0.0.8]:22 130.56.243.154

### What did you expect to happen?

that the ssh session would exit cleanly without leaving a  rogue process

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openssh
log into remote machine via jumpbox
```

**Comment by limingxinleo** [comment]
There seems to be some problems with OpenSSL 3

**Comment by hasso** [comment]
I can confirm that downgrading to the version using openssl@1.1 fixes the problem with zombie processes and segfaults with PKCS11 driver.

**Comment by silverwind** [comment]
There is another likely related issue when `ControlMaster` is enabled with a `.ssh/config` like below, it will get stuck on connecting and the process gets unresponsive consuming 100% CPU, and only `SIGTERM` can kill it.

````
ControlMaster=auto
ControlPath=~/.ssh/control-%r@%h:%p
````

**Comment by mitchblank** [comment]
Another thing that triggers 100% CPU for me is any window resize.  Just do an interactive ssh to any host, and immediately try resizing the window.

As far as I can tell it then spins forever trying to handle the `SIGWINCH` -- `/usr/bin/sample` shows it always in `_sigtramp()`

**Comment by limingxinleo** [comment]
> Another thing that triggers 100% CPU for me is any window resize.  Just do an interactive ssh to any host, and immediately try resizing the window.
> 
> 
> 
> As far as I can tell it then spins forever trying to handle the `SIGWINCH` -- `/usr/bin/sample` shows it always in `_sigtramp()`

I have the same problem, You can rollback the openssh at the preview command.

**Comment by hasso** [comment]
Probably related – https://bugzilla.mindrot.org/show_bug.cgi?id=3584

**Comment by mitchblank** [comment]
> Probably related – https://bugzilla.mindrot.org/show_bug.cgi?id=3584

Yes, seems so.

Question: is there anybody having trouble with the 9.3p1_1 on ARM (Apple Silicon), or is it only showing regression on intel macs?

I just tried to repro my window-resize problem on an M1 Macbook and couldn't.

So my current guess is that this is a regression in the xcode x86_64 compiler backend and `openssl@3` is innocent.

**Comment by carlocab** [comment]
Try installing the Monterey bottle by doing this:
```
export HOMEBREW_NO_INSTALL_FROM_API=1
brew update
```
Then, apply this patch at `"$(brew --repository homebrew/core)/Formula/openssh.rb"`
```diff
diff --git a/Formula/openssh.rb b/Formula/openssh.rb
index cc54588e6c2..39b84d5d323 100644
--- a/Formula/openssh.rb
+++ b/Formula/openssh.rb
@@ -17,7 +17,6 @@ class Openssh < Formula
     sha256 arm64_ventura:  "25275db5e437a463381adc4fb510ccf38ee1884f3aeef25bd11f243b70a190e9"
     sha256 arm64_monterey: "a33d7a73c9bae2b71277a3f4b71a926214f28b945e1deb31018eee171eaf18b8"
     sha256 arm64_big_sur:  "5be316b90b1cb3bca34b04880823521fbc2550e5fad13b2393053621f6778c52"
-    sha256 ventura:        "74631071090c319cc973394af9ea2f92e23b6cda54912e0548d83a165894fe66"
     sha256 monterey:       "b190854db1a47f11be8670e7175050577bd58cbcde7db92d76b5198930d184cf"
     sha256 big_sur:        "025ba8bcdfd679fe0ce5ae67db8969f804aa1fcfe953aed3f825fd5b33c11228"
     sha256 x86_64_linux:   "6cfa57236e4b0702e51906179fb96b71548820ced3fd50c85558bcc4d9e64be1"
```
and then do
```
brew reinstall openssh
```

**Comment by robertc99** [comment]
I rebuilt openssh using gcc-13 and the problem went away. So its definitely a clang problem.

**Comment by cho-m** [comment]
I'm testing out a workaround the other OpenSSH issue (#135200) in #135373. If anyone has chance to see if `-fzero-call-used-regs=all` is potential cause for this issue, try building from source with inreplace hack.

**Comment by robertc99** [comment]
yeah the inreplace hack seems to work ok.
