### ISSUE TITLE
tbb fails to compile with gcc

### ISSUE THREAD

**Issue by nash169** [Homebrew/homebrew-core#13515]
Hi there,
I'm trying to compile tbb using gcc. I changed homebrew env variables CC and CXX in order to set gcc-7 (or 6) as the default compiler but every time I get this error message:

Undefined symbols for architecture x86_64:
"std::range_error::range_error(char const*)", referenced from:
tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
"std::length_error::length_error(char const*)", referenced from:
tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
tbb::internal::concurrent_vector_base::internal_reserve(unsigned long, unsigned long, unsigned long) in concurrent_vector_v2.o
"std::out_of_range::out_of_range(char const*)", referenced from:
tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
"std::runtime_error::runtime_error(char const*)", referenced from:
tbb::internal::handle_perror(int, char const*) in tbb_misc.o
tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
"std::__exception_ptr::exception_ptr::exception_ptr(void*)", referenced from:
tbb::internal::tbb_exception_ptr::allocate(tbb::captured_exception&) in task_group_context.o
"std::__exception_ptr::exception_ptr::exception_ptr(std::__exception_ptr::exception_ptr const&)", referenced from:
tbb::internal::tbb_exception_ptr* tbb::internal::AllocateExceptionContainerstd::__exception_ptr::exception_ptr(std::__exception_ptr::exception_ptr const&) in task_group_context.o
tbb::internal::tbb_exception_ptr::throw_self() in arena.o
tbb::internal::tbb_exception_ptr::throw_self() in scheduler.o
"std::__exception_ptr::exception_ptr::~exception_ptr()", referenced from:
tbb::internal::tbb_exception_ptr::destroy() in task_group_context.o
tbb::internal::tbb_exception_ptr::allocate() in task_group_context.o
tbb::internal::tbb_exception_ptr::allocate(tbb::tbb_exception const&) in task_group_context.o
tbb::internal::tbb_exception_ptr::throw_self() in arena.o
tbb::internal::tbb_exception_ptr::throw_self() in scheduler.o
"std::invalid_argument::invalid_argument(char const*)", referenced from:
tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
"std::current_exception()", referenced from:
tbb::internal::tbb_exception_ptr::allocate() in task_group_context.o
tbb::internal::tbb_exception_ptr::allocate(tbb::tbb_exception const&) in task_group_context.o
"std::rethrow_exception(std::__exception_ptr::exception_ptr)", referenced from:
tbb::internal::tbb_exception_ptr::throw_self() in arena.o
tbb::internal::tbb_exception_ptr::throw_self() in scheduler.o
"___cxa_init_primary_exception", referenced from:
tbb::internal::tbb_exception_ptr::allocate(tbb::captured_exception&) in task_group_context.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [libtbb_debug.dylib] Error 1
make: *** [tbb] Error 2

My brew --env output is:
HOMEBREW_CC: gcc-7
HOMEBREW_CXX: g++-7
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/swig/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gcc/bin

It looks like it is using the wrong stdlib. Is there a way to solve it?

**Comment by nash169** [comment]
Hi there,
I'm trying to compile tbb using gcc. I changed homebrew env variables CC and CXX in order to set gcc-7 (or 6) as the default compiler but every time I get this error message:

Undefined symbols for architecture x86_64:
  "std::range_error::range_error(char const*)", referenced from:
      tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
  "std::length_error::length_error(char const*)", referenced from:
      tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
      tbb::internal::concurrent_vector_base::internal_reserve(unsigned long, unsigned long, unsigned long) in concurrent_vector_v2.o
  "std::out_of_range::out_of_range(char const*)", referenced from:
      tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
  "std::runtime_error::runtime_error(char const*)", referenced from:
      tbb::internal::handle_perror(int, char const*) in tbb_misc.o
      tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
  "std::__exception_ptr::exception_ptr::exception_ptr(void*)", referenced from:
      tbb::internal::tbb_exception_ptr::allocate(tbb::captured_exception&)    in task_group_context.o
  "std::__exception_ptr::exception_ptr::exception_ptr(std::__exception_ptr::exception_ptr const&)", referenced from:
      tbb::internal::tbb_exception_ptr* tbb::internal::AllocateExceptionContainer<std::__exception_ptr::exception_ptr>(std::__exception_ptr::exception_ptr const&) in task_group_context.o
      tbb::internal::tbb_exception_ptr::throw_self()     in arena.o
      tbb::internal::tbb_exception_ptr::throw_self()     in scheduler.o
  "std::__exception_ptr::exception_ptr::~exception_ptr()", referenced from:
      tbb::internal::tbb_exception_ptr::destroy()    in task_group_context.o
      tbb::internal::tbb_exception_ptr::allocate()    in task_group_context.o
      tbb::internal::tbb_exception_ptr::allocate(tbb::tbb_exception const&) in task_group_context.o
      tbb::internal::tbb_exception_ptr::throw_self()     in arena.o
      tbb::internal::tbb_exception_ptr::throw_self()     in scheduler.o
  "std::invalid_argument::invalid_argument(char const*)", referenced from:
      tbb::internal::throw_exception_v4(tbb::internal::exception_id) in tbb_misc.o
  "std::current_exception()", referenced from:
      tbb::internal::tbb_exception_ptr::allocate()    in task_group_context.o
      tbb::internal::tbb_exception_ptr::allocate(tbb::tbb_exception const&) in task_group_context.o
  "std::rethrow_exception(std::__exception_ptr::exception_ptr)", referenced from:
      tbb::internal::tbb_exception_ptr::throw_self()     in arena.o
      tbb::internal::tbb_exception_ptr::throw_self()     in scheduler.o
  "___cxa_init_primary_exception", referenced from:
      tbb::internal::tbb_exception_ptr::allocate(tbb::captured_exception&)    in task_group_context.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [libtbb_debug.dylib] Error 1
make: *** [tbb] Error 2

My brew --env output is:
HOMEBREW_CC: gcc-7
HOMEBREW_CXX: g++-7
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/swig/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gcc/bin

It looks like it is using the wrong stdlib. Is there a way to solve it?

**Comment by dunn** [comment]
Please include `brew gist logs tbb` and `brew config` and `brew doctor`.

**Comment by nash169** [comment]
Hi,
here is my "brew gist-logs tbb":
https://gist.github.com/a9a79bda8e1b06f2a538fcd1abb57e1e

You should find "brew config" and "brew doctor" there as well.  There are some warnings about freetype headers because I just moved them outside the default folder freetype2. Instead, node headers belong to an external installation.

Thanks

**Comment by dunn** [comment]
Hmm, when I run 
```
HOMEBREW_CC=gcc-7 HOMEBREW_CXX=g++-7 brew install -s tbb
```
it fails too, but later, during the Python section: https://gist.github.com/dunn/9dcbb8bf9c5ce26a4975cb8c0f64a06a#file-02-python-L26

**Comment by nash169** [comment]
That's weird.. did you install dependencies with gcc or with clang? Anyway I'm actually experiencing these kind of issues with many packages (for instance vtk or trillinos). I basically needs gcc for the openmp support but if you compile with gcc some package that has dependencies installed via clang you usually get the classical:
ld: symbol(s) not found for architecture x86_64

I know that the problem is likely connected to the use of different standard libraries but I didn't find a good solution so far... (hopefully apple clang will support openmp soon or later).

I tried to install tbb from source but if I set the gcc compiler with command:
make compiler=gcc-7
I get this error:
Created ./build/macos_intel64_gcc-7_cc8.1.0_os10.12.4_release and ..._debug directories
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C "./build/macos_intel64_gcc-7_cc8.1.0_os10.12.4_debug"  -r -f ../../build/Makefile.tbb cfg=debug
../../build/common.inc:110: *** "gcc-7" is not supported on macos. Add build/macos.gcc-7.inc file with compiler-specific settings. .  Stop.
make: *** [tbb] Error 2

**Comment by dunn** [comment]
> did you install dependencies with gcc or with clang

Clang.

**Comment by nash169** [comment]
My problem is probably caused by linking to (line 201 of 01.make.cc):
-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/system -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/

This is the only difference between your make log and mine.

How come your "brew --env" does not show any SDKROOT?

**Comment by nash169** [comment]
Ok... I added to tbb formula
 
ENV.delete("SDKROOT")

and now I get your same error...

**Comment by nash169** [comment]
To avoid those headers during the compilation of python it is necessary to disable the toolboxglue thought the command:
'--disable-toolbox-glue'

I would add a conditional to the brew formula in the event of gcc compiler is used. In this way it is possible to avoid the compilation of Python/mactoolboxglue.c which probably has references to the "buggy" apple headers. Otherwise it is necessary to manually fix those headers I guess... didn't try it yet.

**Comment by dunn** [comment]
That sounds like something that should be fixed upstream.

**Comment by nash169** [comment]
However there is another problem. Disabling the toolbox glue the make phase runs without any problem but during the make install phase I get an error regarding the _Res module import:

Traceback (most recent call last):
  File "./scripts/cachersrc.py", line 7, in <module>
    import macresource
  File "/private/tmp/python-20170517-26442-qubnnu/Python-2.7.13/Lib/plat-mac/macresource.py", line 6, in <module>
    from Carbon import Res
  File "/private/tmp/python-20170517-26442-qubnnu/Python-2.7.13/Lib/plat-mac/Carbon/Res.py", line 4, in <module>
    from _Res import *
ImportError: No module named _Res
make[1]: *** [installmacsubtree] Error 1
make: *** [frameworkinstallmaclib] Error 2

Here the gist-logs:
https://gist.github.com/22dfdd23f69c3830b9a18e0da08e167e

Do you get the same error?

**Comment by nash169** [comment]
Alex I'm going to open an issue about compiling python 2/3 with gcc. Perhaps someone else experienced the same problems and can help.
