### ISSUE TITLE
brew install v8@3.15 is failing besides having python2

### ISSUE THREAD

**Issue by prakashfw** [Homebrew/homebrew-core#135150]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
`brew install v8@3.15`
```
gives this error

Error: v8@3.15 has been disabled because it depends on Python 2 to build!

Could it be because of this commit: https://github.com/Homebrew/homebrew-core/commit/0d6f6d693534d04585d24083d3263f4a1b37d85e

any workaround for this?

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

`brew install v8@3.15`

### What happened (include all command output)?

Error: v8@3.15 has been disabled because it depends on Python 2 to build!

### What did you expect to happen?

After installing python 2 it should install v8 library..

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install v8@3.15`
```

**Comment by carlocab** [comment]
Not really. You can try creating your own tap (with `brew tap-new`) and using `brew extract` to create your own `v8@3.15` formula. We can't really help you with getting it to build, however.

Also:

Please read the issue template carefully. We require the output of `brew config` and `brew doctor` from all bug reports at Homebrew.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.
