### ISSUE TITLE
cloning repo is broken

### ISSUE THREAD

**Issue by ilia-shipitsin** [Homebrew/homebrew-core#135315]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
# git clone https://github.com/Homebrew/homebrew-core
Cloning into 'homebrew-core'...
remote: Enumerating objects: 1532699, done.
remote: Counting objects: 100% (34185/34185), done.
remote: fatal: object 0acc93f8ce85f8561492a6b56256ed7f0035af76 cannot be read
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
#

```

it would be nice to fix, because we use `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` and it clones repo, thus fails :(
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to install brew using `https://raw.githubusercontent.com/Homebrew/install/master/install.sh`

### What happened (include all command output)?

```
# git clone https://github.com/Homebrew/homebrew-core
Cloning into 'homebrew-core'...
remote: Enumerating objects: 1532699, done.
remote: Counting objects: 100% (34185/34185), done.
remote: fatal: object 0acc93f8ce85f8561492a6b56256ed7f0035af76 cannot be read
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
#

```

### What did you expect to happen?

not to fail

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
HOMEBREW_INSTALL_URL="https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
/bin/bash -c "$(curl -fsSL ${HOMEBREW_INSTALL_URL})"
```

**Comment by Bo98** [comment]
This is a GitHub issue we have no control over. I am told it they have fixed the issue so give it another try.

**Comment by ilia-shipitsin** [comment]
it's not a github issue.

anyway, it is possible `in theory` to clone using `depth 1`

```
~# git clone --depth 1 https://github.com/Homebrew/homebrew-core
Cloning into 'homebrew-core'...
remote: Enumerating objects: 7052, done.
remote: Counting objects: 100% (7052/7052), done.
remote: Compressing objects: 100% (6719/6719), done.
remote: Total 7052 (delta 106), reused 1569 (delta 64), pack-reused 0
Receiving objects: 100% (7052/7052), 7.78 MiB | 7.38 MiB/s, done.
Resolving deltas: 100% (106/106), done.
~#
```

but I cannot pass "depth 1" to brew install script

**Comment by ilia-shipitsin** [comment]
please consider adjusting https://raw.githubusercontent.com/Homebrew/install/master/install.sh to clone with depth 1, it will prevent from such errors

**Comment by Bo98** [comment]
It is a GitHub issue. We are talking to them directly about it and some replicas on their end are missing parts of the repo, causing the errors you have reported.

**Comment by Bo98** [comment]
> please consider adjusting https://raw.githubusercontent.com/Homebrew/install/master/install.sh to clone with depth 1, it will prevent from such errors

We don't do this because it causes severe performance issues that lead to GitHub asking us to stop using that flag. https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/update.sh#L474

**Comment by ilia-shipitsin** [comment]
I do not suggest to change default behaviour.

I'm ok with default clone, people may expect it.

however, if I need just the latest commit, I'm fine to say "depth 1" and I do not care of broken git indices.

**Comment by rfay** [comment]
This is breaking routinely using the standard GH Actions homebrew action, https://github.com/ddev/ddev-platformsh/blob/ea9eb17449728c6dcb57dd95b75939a37da49da9/.github/workflows/tests.yml#L47-L49

It's breaking every repo (there are MANY) that uses it.  I do note that it's using `HOMEBREW_NO_INSTALL_FROM_API: 1` in order to use `brew install --HEAD`

Examples: https://github.com/ddev/ddev-platformsh/actions/runs/5415041350

**Comment by SMillerDev** [comment]
`brew install --HEAD` is unsupported so that's not a concern.

**Comment by SMillerDev** [comment]
> maybe it makes sense to keep unshallow by default

GitHub has asked us explicitly not to do this.

**Comment by ilia-shipitsin** [comment]
thank you very much for closing this issue. you are very helpful

however, I still cannot clone repo

```
~# git clone https://github.com/Homebrew/homebrew-core
Cloning into 'homebrew-core'...
remote: Enumerating objects: 11082, done.
remote: Counting objects: 100% (7756/7756), done.
remote: fatal: object 0d7d72f3d46957a85ebbf915a1d2c78f001e486c cannot be read
remote: aborting due to possible repository corruption on the remote side.
fatal: protocol error: bad pack header
~#
```

**Comment by Bo98** [comment]
If you want an indication of recovery, check https://github.com/Homebrew/formulae.brew.sh/actions/workflows/scheduled.yml which is a job that runs every 15 minutes and fetchs Homebrew/core twice. If either of those fail then the whole job fails.

**Comment by SMillerDev** [comment]
> however, I still cannot clone repo

And that's still not something for us to fix. Do you also complain to your car dealer about road closures?

**Comment by ilia-shipitsin** [comment]
sorry, I did not realize that `https://raw.githubusercontent.com/Homebrew/install/master/install.sh` is not supposed to work.
is there a proper way ?

**Comment by Bo98** [comment]
I realise you're upset at us for this issue occurring but to follow up for the benefit for anyone else following along:

GitHub has identified and fixed the root cause, and has finished the repair operation on homebrew-core. This issue should now be resolved, and our own monitoring has confirmed this. Big thanks to the git systems team there who worked most of the day on resolving this issue.
