### ISSUE TITLE
weechat should use an existing CA bundle file

### ISSUE THREAD

**Issue by KellerFuchs** [Homebrew/homebrew-core#13553]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Use the weechat IRC client

- What happened (include command output)
Weechat was installed, and refused to connect to any TLS-enabled IRC server due to certificate validation issues.

The core issue seems to be that `weechat.network.gnutls_ca_file` is set to `/etc/ssl/certs/ca-certificates.crt` by default, which doesn't exist.
Setting it to `/usr/local/etc/openssl/cert.pem` works, and should be the default (assuming it is installed by a recipe `weechat` depends on).

- What you expected to happen
Weechat should work out of the box.

- Step-by-step reproduction instructions (by running `brew install` commands)
  - `brew install weechat`
  - Start `weechat`
  - Run `/connect irc.hashbang.sh/6697 -ssl`

This is a bug that @phoebeje encountered :)

**Comment by KellerFuchs** [comment]
Thanks a bunch, @DomT4

**Comment by DomT4** [comment]
No worries at all! Thanks for spotting this.
