### ISSUE TITLE
python3 failed to build on macOS 10.12.4

### ISSUE THREAD

**Issue by Merlynfry** [Homebrew/homebrew-core#13561]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
   I was trying to install python3 using quicktest.
- What happened (include command output)
   quicktest failed.
   
```
$ brew install python3 --with-quicktest
==> Using the sandbox
==> Downloading https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tar.xz
Already downloaded: /Users/Merlynfry/Library/Caches/Homebrew/python3-3.6.1.tar.xz
==> ./configure --prefix=/usr/local/Cellar/python3/3.6.1 --enable-ipv6 --dataroo
==> make
==> make quicktest TESTPYTHONOPTS=-s TESTOPTS=-j8 -w
Last 15 lines from /Users/Merlynfry/Library/Logs/Homebrew/python3/03.make:
    self._sslobj.do_handshake()
  File "/private/tmp/python3-20170514-27132-1bn9xi6/Python-3.6.1/Lib/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:749)

----------------------------------------------------------------------
Ran 95 tests in 8.262s

FAILED (errors=2)
3 tests failed again:
    test_imaplib test_platform test_popen

Total duration: 2 min 13 sec
Tests result: FAILURE
make: *** [quicktest] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
uwsgi fix --with-python3 to build plugin using python3 https://github.com/Homebrew/homebrew-core/pull/12100
SIGABRT with python3 --with-tcl-tk https://github.com/Homebrew/homebrew-core/issues/12808
```

- What you expected to happen
   I not sure what to put here except that I expected the quicktest to pass and the install to complete.
- Step-by-step reproduction instructions (by running `brew install` commands)
   I'm not sure if this is going to occur for anyone else, but for me the issue is reproducible by executing any of these commands:
`$ brew install python3 --with-quicktest --with-sphinx-doc --with-tcl-tk`
[gist-logs](https://gist.github.com/anonymous/f121219f91b6231c63adee818e9151fc)
`$ brew install python3 --with-quicktest --with-sphinx-doc`
[gist-logs](https://gist.github.com/anonymous/39a5f2b1a8d42a370d594358c9c1398d)
`$ brew install python3 --with-quicktest --with-tcl-tk`
[gist-logs](https://gist.github.com/anonymous/3c20f0dfe6320bf26d7621af26e64a2f)
`$ brew install python3 --with-quicktest`
[gist-logs](https://gist.github.com/anonymous/7e24a39d3af4d01a67d0ff8e0be6fef3)

**Comment by pewulfman** [comment]
Hi, i have been using homebrew python3 with no problem for a while. Due to a new installation i also try to download python3 with quicktest option enable. I looked into the verbose mode. It seems that the popen tst ry to open a file that it not there (bug int the test ?) and the platform try to import some window specific code. I am not sure why the imaplib fail though. 

In the end, i think you could install python3 without this options and used it without any problem. But I agree this test should be corrected.

Hope this help

**Comment by tdsmith** [comment]
quicktest is broken upstream; sorry!
