### ISSUE TITLE
Building ruby 2.4.1 fails

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#13583]
This is the output of brew config

```shell
$ brew config
HOMEBREW_VERSION: 1.2.0-90-gea8be174f6
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2aa3a8f1f2fc2d4e402c96e1e8d0d1faf099f7d1
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
GCC-4.2: build 5666
Clang: 6.1 build 602
Git: 2.12.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.2.1/bin/ruby
Java: 1.8.0_131, 1.8.0_72, 1.7.0_40, 1.6.0_65-b14-466.1, 1.6.0_51-b11-457
macOS: 10.10.5-x86_64
Xcode: 6.4
CLT: 7.2.0.0.1.1447826929
X11: 2.7.9 => /opt/X11
```

Logs have [been uploaded here](https://gist.github.com/hanxue/a9908fe7ab83cda52b2cf3d5f67e164d). 

FWIW, pouring from bottle and then running ruby scripts works fine. I need ruby to be compiled with libffi though.

**Comment by JCount** [comment]
The issue could well be that your Xcode it outdated, especially when compared to your CLT version. I would suggest updating your Xcode the most recent supported version for your platform, `7.2.1`, and then trying to compile from source again.

**Comment by hanxue** [comment]
I couldn't upgrade because of my OSX version. Can anyone else confirm this error happens on XCode 6.x and Yosemite? Then the build from source requirements ought to have XCode 7



Hanxue

________________________________

**Comment by ilovezfs** [comment]
Given I can build it with Xcode 5.1.1 on 10.8, an Xcode 7 requirement would not appropriate.

**Comment by ilovezfs** [comment]
I agree with JCount that the likely cause here is the mismatch between your Xcode version and your CLT version. You can try

```
sudo mv /Library/Developer/CommandLineTools ~/.Trash
```
and then see if it builds.
