### ISSUE TITLE
Typo in openldap.rb Formula

### ISSUE THREAD

**Issue by mlueck88** [Homebrew/homebrew-core#13584]
The formula changed the --with-berkeley-db4 option to --with-berkeley-db@4.

However, in line 45, it still checks "if build.without? "berkeley-db4".
Hence it is impossible to compile with bdb support.

This issue is similar, but not a duplicate, of https://github.com/Homebrew/homebrew-dupes/pull/535 which was fixed by https://github.com/Homebrew/homebrew-dupes/commit/ac92c606e090eeb62f678f02c2b2b9858ad1486d

**Comment by bfontaine** [comment]
Please make a pull-request instead.
