### ISSUE TITLE
groff bottle has outdated font paths

### ISSUE THREAD

**Issue by remorse** [Homebrew/homebrew-core#135878]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
pukku@macosmachine ~ % brew config
HOMEBREW_VERSION: 4.0.27
ORIGIN: https://github.com/Homebrew/brew
HEAD: 32ff40f688a49e02428eb3f20232aac69ffeeea0
Last commit: 20 hours ago
Core tap JSON: 05 Jul 20:42 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.24vla6hzEs/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.7-arm64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
Rosetta 2: false
pukku@macosmachine ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install groff, so that I could create a PDF written in roff. 

### What happened (include all command output)?

I installed groff, which installed Ghostscript. I then ran the groff command for my document:

```
pukku@macosmachine ringing_halfsheets % groff -Mm -mbell -Tpdf -Kutf8 -P-pa5 groff/1643386.groff > pdf/1643386.pdf
groff/1643386.groff: Failed to open '/opt/homebrew/Cellar/ghostscript/9.55.0/share/ghostscript/9.55.0/Resource/Font/C059-Roman'
```

As you can see, it complains that it can't find the font file. The file does exist, but in the path for Ghostscript 10.01.2, not 9.55.0.

### What did you expect to happen?

I expected groff to be able to find the font file and use it to create a PDF.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install groff
echo ".fam N\nThis is a test." | groff -Tpdf > test.pdf
```

**Comment by remorse** [comment]
I couldn't find a place to put this information in the template above. The issue is that the groff bottle was created on a machine that had the older version of Ghostscript installed, so the `/opt/homebrew/Cellar/groff/1.22.4_1/share/groff/1.22.4/font/devpdf/download` file has paths pointing to the wrong location. If I go in and change the paths there (by replacing `9.55.0` with `10.01.2`), it does work properly.

**Comment by cho-m** [comment]
Probably should first fix `ghostscript` so that it removes extra versioning (`--without-versioned-path`) and also outputs Homebrew's opt path rather than Cellar path. This will help avoid breakage on new `ghostscript` releases.

Then need to rebuild `groff` so it burns in the unversioned paths.
