### ISSUE TITLE
ffmpeg formula missing --with-fontconfig and with-freetype

### ISSUE THREAD

**Issue by stiller-leser** [Homebrew/homebrew-core#13611]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [https://gist.github.com/fcf12f787b76c5823cfdcd5b9f465868](url)

I am trying to run the following command: 
```
ffmpeg -i testclip.mp4 -vf \
"format=yuv444p, \
 drawbox=y=ih/PHI:color=black@0.4:width=iw:height=48:t=max, \
 drawtext=fontfile=OpenSans-Regular.ttf:text="Title of this Video":fontcolor=white:fontsize=24:x=(w-tw)/2:y=(h/PHI)+th, \
 format=yuv420p" \
-c:v libx264 -c:a copy -movflags +faststart 123.mp4

```

This requires the ffmpeg-configure-options `--enable-libfreetype` as well as `--enable-fontconfig` during compilation. Those are included in the formula source code under the args-section and the build-with-queries, but not included as option. I prepared a pull request but wanted to ask before if there is a reason that those options are not included? Once included ffmpeg installs just fine and runs the above command without issues.

**Comment by fxcoudert** [comment]
`brew info ffmpeg` will tell you there are present:

```
--with-fontconfig
	Build with fontconfig support
--with-freetype
	Build with freetype support
```
