### ISSUE TITLE
Postgresql formula uses `kill -9`, against Postgres documentation guidance, abrupt shutdown causes data loss

### ISSUE THREAD

**Issue by mmisiewicz** [Homebrew/homebrew-core#136107]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  brew config
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 2 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 79cd87a873fee7c9014963e1f94699866179dce5
Core tap last commit: 4 months ago
Core tap branch: master
Core tap JSON: 08 Jul 01:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_THEME: Solarized (dark)
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.YcK2BmIW9Y/org.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/mate -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 20-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false

➜  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pycparser
  docutils
  cffi
  awscli
  protobuf
  wireshark
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Update packages on my system by running `brew upgrade`

### What happened (include all command output)?

The homebrew formula for Postgres@15 kills the postmaster using a kill -9. Here's the long entries from my postgres log showing this (note I use csvlog on my system):

``` 782   │ 2023-07-07 21:55:43.223 EDT,,,2288,,64a7595a.8f0,8,,2023-07-06 20:16:26 EDT,,0,LOG,00000,"server process (PID 44150) was terminated by signal 9: Killed: 9",,,,,,,,,"","postmaster",,0```

Subsequently, due to the ungraceful shutdown, some of postgres data files have been fouled, resulting in the following bad errors:

```
 785   │ 2023-07-07 21:55:44.094 EDT,,,2288,,64a7595a.8f0,11,,2023-07-06 20:16:26 EDT,,0,LOG,42501,"could not open directory ""pg_tblspc/306937192/PG_15_202209061"": Operation not permitted",,,,,,,,,"","postmaster",,0
 786   │ 2023-07-07 21:55:44.095 EDT,,,2288,,64a7595a.8f0,12,,2023-07-06 20:16:26 EDT,,0,LOG,58P01,"could not open directory ""pg_tblspc/306879445/PG_15_202209061"": No such file or directory",,,,,,,,,"","postmaster",,0
 787   │ 2023-07-07 21:55:44.100 EDT,,,2288,,64a7595a.8f0,13,,2023-07-06 20:16:26 EDT,,0,LOG,42501,"could not open directory ""pg_tblspc/375146718/PG_15_202209061"": Operation not permitted",,,,,,,,,"","postmaster",,0
```

And after subsequent attempts to restart, the same issue has been repeated. Now I have to figure out how to repair my database. 

Per the [postgres manual](https://www.postgresql.org/docs/current/server-shutdown.html):

>Important
>
>It is best not to use SIGKILL to shut down the server. Doing so will prevent the server from releasing shared memory and semaphores. Furthermore, SIGKILL kills the postgres process without letting it relay the signal to its subprocesses, so it might be necessary to kill the individual subprocesses by hand as well.

I don't see where in `Formula/postgresql@15.rb` this might be coming from, maybe it's inherited from the Formula class?

### What did you expect to happen?

Do not use SIGKILL. Use SIGINT, SIGTERM or SIGQUIT to stop the postmaster process. If this fails, prompt the user to run pg_ctl

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
install postgresql@15
pg_ctl start -D /opt/homebrew/var/postgresql@15
brew upgrade postgresql@15 # for example when a new patch release is available
```

**Comment by carlocab** [comment]
The formula does not use `kill -9`. It's certainly not inherited from the `Formula` class. Your postgres server is being killed by the OS after the automatic `brew cleanup` that is done along with `brew upgrade`.

We could/should probably skip doing this automatically for formulae like `postgresql`. CC @Homebrew/core for thoughts.

As a workaround for now, do:
```
export HOMEBREW_NO_CLEANUP_FORMULAE=postgresql@15
```
to avoid `brew` cleaning up old `postgresql` installs after `brew upgrade`. You will need to do
```
HOMEBREW_NO_CLEANUP_FORMULAE= brew cleanup postgresql@15
```
when you're ready for `brew` to clean up old installations from your system.

**Comment by MikeMcQuaid** [comment]
> Your postgres server is being killed by the OS after the automatic `brew cleanup` that is done along with `brew upgrade`.

Not sure we can really do anything about this.

> We could/should probably skip doing this automatically for formulae like `postgresql`. CC @Homebrew/core for thoughts.

Would want to see (m)any more users complain about this before we change this default.

**Comment by mmisiewicz** [comment]
HOMEBREW_NO_CLEANUP_FORMULAE looks like it will solve my problem as a workaround for now. 

An idea: in other package managers (e.g. apt in ubuntu) in the post-install stage the user is prompted to press a key before restarting servers which may be in use. This behavior is triggered when upgrading certain packages like libc that many applications depend on. If macos itself is issuing the kill -9 command perhaps giving the user a bit of warning first would be a solution to the problem.

**Comment by mmisiewicz** [comment]
I'm going to go ahead and close this one out because the recent Postgresql 15.3_2 -> 15.4 upgrade in homebrew succeeded without anything being `kill -9`'d while using HOMEBREW_NO_CLEANUP_FORMULAE=postgresql@15. 

I'd still advocate for an `apt`-like warning in the future to gracefully restart processes.
