### ISSUE TITLE
`bump-formula-pr` fails with `Error: wrong argument type nil (expected Regexp)`

### ISSUE THREAD

**Issue by tuulos** [Homebrew/homebrew-core#13624]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I am trying to update the version of the `traildb` formula to correspond to the 0.6 tag in the upstream repo.

I get the following error:

```
$brew bump-formula-pr --strict --tag=0.6 --revision=df7c4dd236bd3a87caba31afc73c7608f6a0a00f traildb
Already up-to-date.
==> replace nil with "0.6"
Error: wrong argument type nil (expected Regexp)
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/extend/string.rb:52:in `gsub!'
/usr/local/Homebrew/Library/Homebrew/extend/string.rb:52:in `gsub!'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:63:in `block (2 levels) in inreplace_pairs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:59:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:59:in `block in inreplace_pairs'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:26:in `block in inreplace'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:22:in `each'
/usr/local/Homebrew/Library/Homebrew/utils/inreplace.rb:22:in `inreplace'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:58:in `inreplace_pairs'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:240:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

I have update the formula by hand in this commit https://github.com/tuulos/homebrew-core/commit/4ae94284c3a4481d988ad8d60139c84d1eaff03c

I can create a PR based on this commit if there isn't an easy workaround for the `bump-formula-pr` error. 

Thanks!

**Comment by ilovezfs** [comment]
From the man page:
```
              Note that this command cannot be used to  transition  a  formula
              from  a  URL-and-sha256 style specification into a tag-and-revi-
              sion style specification, nor vice versa. It must use  whichever
              style specification the preexisting formula already uses.
```

**Comment by tuulos** [comment]
Right, thanks. It works with `--url` and `--sha256`.
