### ISSUE TITLE
gcc-12: internal compiler error: Segmentation fault

### ISSUE THREAD

**Issue by jcp9071** [Homebrew/homebrew-core#136341]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Hi all,

I'm using Matlab and with Dynare (an economics software that works within Matlab) and I am finding the following problem:

Starting Dynare (version 5.4).
Calling Dynare with arguments: none
Starting preprocessing of the model file ...
Substitution of endo leads >= 2: added 1365 auxiliary variables and equations.
Substitution of endo lags >= 2: added 200 auxiliary variables and equations.
Found 1584 equation(s).
Evaluating expressions...done
Computing static model derivatives (order 1).
Computing dynamic model derivatives (order 2).
Processing outputs ...
Compiling static MEX...
"/Applications/Dynare/5.4/matlab/../preprocessor/../.brew/bin/gcc-12" -O3 -g0 --param ira-max-conflict-table-size=1 -fno-forward-propagate -fno-gcse -fno-dce -fno-dse -fno-tree-fre -fno-tree-pre -fno-tree-cselim -fno-tree-dse -fno-tree-dce -fno-tree-pta -fno-gcse-after-reload -I "/Applications/MATLAB_R2022a.app/extern/include" -L "/Applications/MATLAB_R2022a.app/bin/maci64" -fexceptions -DNDEBUG -fno-common -Wl,-twolevel_namespace -undefined error -bundle "nkpc_v1/model/src/static.c" -o "+nkpc_v1/static.mexmaci64" -lmex -lmx -lm
Compiling dynamic MEX...
"/Applications/Dynare/5.4/matlab/../preprocessor/../.brew/bin/gcc-12" -O3 -g0 --param ira-max-conflict-table-size=1 -fno-forward-propagate -fno-gcse -fno-dce -fno-dse -fno-tree-fre -fno-tree-pre -fno-tree-cselim -fno-tree-dse -fno-tree-dce -fno-tree-pta -fno-gcse-after-reload -I "/Applications/MATLAB_R2022a.app/extern/include" -L "/Applications/MATLAB_R2022a.app/bin/maci64" -fexceptions -DNDEBUG -fno-common -Wl,-twolevel_namespace -undefined error -bundle "nkpc_v1/model/src/dynamic.c" -o "+nkpc_v1/dynamic.mexmaci64" -lmex -lmx -lm
gcc-12: internal compiler error: Segmentation fault: 11 signal terminated program cc1
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
Compilation failed

I contacted the Dynare support and they told me that my code runs perfectly for them and that this is probably an internal error of gcc and I should make sure to update my version.

I made sure that everything is updated and I have the last versions of everything. When typing mex -setup in Matlab I get

MEX configured to use 'Xcode with Clang' for C language compilation.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN

I tried selecting another compiler to see if it does the trick. When I select C++ (it seems that the fortran one is not supported) I get:

MEX configured to use 'Xcode Clang++' for C++ language compilation.

But it does not seem that Matlab changed anything as when I type mex -setup again I again get 

 MEX configured to use 'Xcode with Clang' for C language compilation.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN

Thank you!
Jose
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run Dynare on Matlab

### What happened (include all command output)?

Hi all,

I'm using Matlab and with Dynare (an economics software that works within Matlab) and I am finding the following problem:

Starting Dynare (version 5.4).
Calling Dynare with arguments: none
Starting preprocessing of the model file ...
Substitution of endo leads >= 2: added 1365 auxiliary variables and equations.
Substitution of endo lags >= 2: added 200 auxiliary variables and equations.
Found 1584 equation(s).
Evaluating expressions...done
Computing static model derivatives (order 1).
Computing dynamic model derivatives (order 2).
Processing outputs ...
Compiling static MEX...
"/Applications/Dynare/5.4/matlab/../preprocessor/../.brew/bin/gcc-12" -O3 -g0 --param ira-max-conflict-table-size=1 -fno-forward-propagate -fno-gcse -fno-dce -fno-dse -fno-tree-fre -fno-tree-pre -fno-tree-cselim -fno-tree-dse -fno-tree-dce -fno-tree-pta -fno-gcse-after-reload -I "/Applications/MATLAB_R2022a.app/extern/include" -L "/Applications/MATLAB_R2022a.app/bin/maci64" -fexceptions -DNDEBUG -fno-common -Wl,-twolevel_namespace -undefined error -bundle "nkpc_v1/model/src/static.c" -o "+nkpc_v1/static.mexmaci64" -lmex -lmx -lm
Compiling dynamic MEX...
"/Applications/Dynare/5.4/matlab/../preprocessor/../.brew/bin/gcc-12" -O3 -g0 --param ira-max-conflict-table-size=1 -fno-forward-propagate -fno-gcse -fno-dce -fno-dse -fno-tree-fre -fno-tree-pre -fno-tree-cselim -fno-tree-dse -fno-tree-dce -fno-tree-pta -fno-gcse-after-reload -I "/Applications/MATLAB_R2022a.app/extern/include" -L "/Applications/MATLAB_R2022a.app/bin/maci64" -fexceptions -DNDEBUG -fno-common -Wl,-twolevel_namespace -undefined error -bundle "nkpc_v1/model/src/dynamic.c" -o "+nkpc_v1/dynamic.mexmaci64" -lmex -lmx -lm
gcc-12: internal compiler error: Segmentation fault: 11 signal terminated program cc1
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
Compilation failed

I contacted the Dynare support and they told me that my code runs perfectly for them and that this is probably an internal error of gcc and I should make sure to update my version.

I made sure that everything is updated and I have the last versions of everything. When typing mex -setup in Matlab I get

MEX configured to use 'Xcode with Clang' for C language compilation.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN

I tried selecting another compiler to see if it does the trick. When I select C++ (it seems that the fortran one is not supported) I get:

MEX configured to use 'Xcode Clang++' for C++ language compilation.

But it does not seem that Matlab changed anything as when I type mex -setup again I again get 

 MEX configured to use 'Xcode with Clang' for C language compilation.

To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN

Thank you!
Jose

### What did you expect to happen?

That it would perfectly run

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
a
```

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports at Homebrew.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.

**Comment by carlocab** [comment]
Ok, so you are not actually using `brew` directly yourself then.

You'll need to report this problem to the Dynare project again, because the error comes from a use-case we don't support (but appears to come from design decisions of Dynare). You can tell them what you've reported here. If they send you back to us, please ask for assistance on how to produce a reproduction using only Homebrew `gcc-12`, without using Dynare or MATLAB at all, because that's what we'll need here in order to debug this problem.
