### ISSUE TITLE
Warnings while installing android-sdk

### ISSUE THREAD

**Issue by xeoneux** [Homebrew/homebrew-core#1363]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

After installing `android-sdk`, I receive the following warnings:

```
Warning: Could not fix /tmp/android-build-build-temp-74102/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.4.1_1/tools/qemu/darwin-x86_64/qemu-system-aarch64
Warning: Could not fix /tmp/android-build-build-temp-74102/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.4.1_1/tools/qemu/darwin-x86_64/qemu-system-mips64el
Warning: Could not fix /tmp/android-build-build-temp-74102/install-darwin-x86_64/lib/libz.1.dylib in /usr/local/Cellar/android-sdk/24.4.1_1/tools/qemu/darwin-x86_64/qemu-system-x86_64
```

**Comment by DomT4** [comment]
See https://github.com/Homebrew/legacy-homebrew/issues/41110 & https://github.com/Homebrew/legacy-homebrew/pull/40630#issuecomment-111899028. It's harmless, but yeah, the warnings are annoying.
