### ISSUE TITLE
brew reinstall -s libfuse -- hash mismatch

### ISSUE THREAD

**Issue by 13steinj** [Homebrew/homebrew-core#136487]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew gist-logs libfuse || brew config && brew doctor
Error: No logs.
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 7 days ago
Core tap JSON: 13 Jul 04:00 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
ftp_proxy: [redacted, confirmed without]
http_proxy: [redacted, confirmed without]
https_proxy: [redacted, confirmed without]
no_proxy: [redacted, confirmed without]
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.41.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.19.0-43-generic x86_64 GNU/Linux
OS: Ubuntu 22.04.2 LTS (jammy)
Host glibc: 2.35
/usr/bin/gcc: 11.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
Your system is ready to brew.

```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Before I get shunned to the land of "no support" due to this being on linux, please hear me out in full--

* I installed libfuse and sshfs with homebrew, realized sshfs was out of date, switched to using rclone that I had separately
* Failed with an error with the posting pwd / getpwuid api failing, look into this, debugged this with strace, etc, narrowing down to fusermount3 binary
* Confirmed that the one from apt _works_
* Next step was to _try_ to build libfuse in homebrew from source (yes I know no support given with any issues of source-built packages, but I wanted to see if it was a build-time dynlib issue since the problem in question happens when nss libs can't be found)
* brew fails as described.

I know the underlying issue is "libfuse is busted" in some way; but I wanted to be a good open source contributor, figure out _what_ the difference was, before reporting the issue.
I know building from source is unsupported, but I imagine that's referring to "recipe is wrong? too bad" and not "brew hash-mismatches on a download"

### What happened (include all command output)?

```
➜  ~ brew reinstall -s libfuse
Warning: building from source is not supported!
You're on your own. Failures are expected so don't create any issues, please!
==> Fetching dependencies for libfuse: ninja, krb5, libxcrypt and meson
==> Fetching ninja
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/manifests/1.11.1
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/blobs/sha256:f0124cfd2fc9
######################################################################### 100.0%
==> Fetching krb5
==> Downloading https://ghcr.io/v2/homebrew/core/krb5/manifests/1.21.1
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:eb9b6638eeac1
######################################################################### 100.0%
==> Fetching libxcrypt
==> Downloading https://ghcr.io/v2/homebrew/core/libxcrypt/manifests/4.4.36
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/libxcrypt/blobs/sha256:ad1c4b57
######################################################################### 100.0%
==> Fetching meson
==> Downloading https://ghcr.io/v2/homebrew/core/meson/manifests/1.1.1
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/meson/blobs/sha256:75c008baf121
######################################################################### 100.0%
==> Fetching libfuse
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/c2e5f26
######################################################################### 100.0%
==> Downloading https://github.com/libfuse/libfuse/releases/download/fuse-3.15.1
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
Error: SHA256 mismatch
Expected: d236874dab83f2618901627cff4aff0fda69346e17f856da1ddcfdd8db2f3a41
  Actual: 13ef77cda531a21c2131f9576042970e98035c0a5f019abf661506efd2d38a4e
    File: /home/[redacted]/.cache/Homebrew/downloads/5410217e5d2b0ad771dcf1df3734308991265cd8ee7773450c5c8c663d69a8fd--fuse-3.15.1.tar.gz
To retry an incomplete download, remove the file above.
```

It's clear that this above output is partial, because the urls cut off. Rerunning; 

```
➜  ~ brew reinstall -s libfuse
Warning: building from source is not supported!
You're on your own. Failures are expected so don't create any issues, please!
==> Fetching dependencies for libfuse: ninja, krb5, libxcrypt and meson
==> Fetching ninja
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/manifests/1.11.1
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/cd63e02146a3b8a3cfbd138d15ecbc3593633d848f5e9d3ab329fff1953fa541--ninja-1.11.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/ninja/blobs/sha256:f0124cfd2fc96edec66111ffd30f51fa02be75e01a4b930bab17c8e980b28d14
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/747f1493566d5baf0e0356b628b0e6b4f2ed00350c8d982c2b3826b6920b7930--ninja--1.11.1.x86_64_linux.bottle.tar.gz
==> Fetching krb5
==> Downloading https://ghcr.io/v2/homebrew/core/krb5/manifests/1.21.1
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/ddfb679168b2fb5c81b5070273ae6ef48ac5b15e85212dfe4386e089c46b81b1--krb5-1.21.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/krb5/blobs/sha256:eb9b6638eeac1834e233fffef4e1ac145c5d38ae2f00c7844fe06afad26195ba
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/f9bbeee9a8a87a9c4fe0599e79f1843cb6762342376bb8293033eec81cc36b28--krb5--1.21.1.x86_64_linux.bottle.tar.gz
==> Fetching libxcrypt
==> Downloading https://ghcr.io/v2/homebrew/core/libxcrypt/manifests/4.4.36
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/950e230307625f9e57d74f0076caab42b6c67a325c70b83efa2c9cc84be1f839--libxcrypt-4.4.36.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libxcrypt/blobs/sha256:ad1c4b570d7a66046038c13345b54337d858a2db78dcfb7e90a2b21adc1d6802
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/8a89cd46e87dade4849639585d2fd436fa581e9d21471f24e76e590d177c095f--libxcrypt--4.4.36.x86_64_linux.bottle.tar.gz
==> Fetching meson
==> Downloading https://ghcr.io/v2/homebrew/core/meson/manifests/1.1.1
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/5e209a4cdada988b22a7483f62a70ac898cb4ca9f195f9c2b54913f6c0d764c7--meson-1.1.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/meson/blobs/sha256:75c008baf121ada9182e84db582a9d826efef83d6daa6bb4ddbcec47f2f5feb0
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/077a793b57f226ba4d513e12bcdf767ef97e3e737868b24a4f95fdfa06ab5b36--meson--1.1.1.all.bottle.tar.gz
==> Fetching libfuse
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/c2e5f263f775688ef4a35f091384b4798d58badd/Formula/libfuse.rb
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/5499d8c5ab08fa5e88996adb8489fa201daaa8f40417da6d81bbe1887f58a014--libfuse.rb
==> Downloading https://github.com/libfuse/libfuse/releases/download/fuse-3.15.1/fuse-3.15.1.tar.gz
Already downloaded: /home/[redacted]/.cache/Homebrew/downloads/5410217e5d2b0ad771dcf1df3734308991265cd8ee7773450c5c8c663d69a8fd--fuse-3.15.1.tar.gz
Error: SHA256 mismatch
Expected: d236874dab83f2618901627cff4aff0fda69346e17f856da1ddcfdd8db2f3a41
  Actual: 13ef77cda531a21c2131f9576042970e98035c0a5f019abf661506efd2d38a4e
    File: /home/jonathan/.cache/Homebrew/downloads/5410217e5d2b0ad771dcf1df3734308991265cd8ee7773450c5c8c663d69a8fd--fuse-3.15.1.tar.gz
To retry an incomplete download, remove the file above.
```

### What did you expect to happen?

A hash mismatch not to happen, and for it to at least attempt to build.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libfuse
# realize the bug you're having is related to the libfuse in homebrew, attempt to reinstall from source
brew reinstall -s libfuse
# boom
# n.b. might be able to just brew install -s libfuse
```

**Comment by 13steinj** [comment]
oh, in case it's not clear; yes I tried removing that file (and even a full `brew cleanup`). I also tested this from an ubuntu 20 machine.

Proxies are redacted because they are fairly self-doxxing / don't tell anyone anything, but I've confirmed this on a personal network by tunneling a socks proxy out to a personal mobile's tethered network; unless I'm crazy it does not appear to be the proxy blocking / modifying _that specific download (and no other).

If a maintainer comes back unable to reproduce the hash issue I'll triple check (it's just not easy to do so for the next several weeks), and apologize for wasting time if it does end up being on my end. I've also confirmed that the cached tarball does have a bunch of files with ye olde `tar ztvf /path/to/5410217e5d2b0ad771dcf1df3734308991265cd8ee7773450c5c8c663d69a8fd--fuse-3.15.1.tar.gz`

**Comment by 13steinj** [comment]
Okay, I've downloaded the source fuse 3.15 tarball from the ruby file and sha256sum'd it, it is definitely the actual in the following, not the expected
```
Expected: d236874dab83f2618901627cff4aff0fda69346e17f856da1ddcfdd8db2f3a41
  Actual: 13ef77cda531a21c2131f9576042970e98035c0a5f019abf661506efd2d38a4e
```

I don't know the details on if the shas can magically change or not (I guess technically libfuse 3.15.1 could have been untagged / unreleased then rereleased?) #135851 but I would have thought CI would have / should be able to catch a sha mismatch like this.

**Comment by ZhongRuoyu** [comment]
> it is definitely the actual in the following, not the expected

Right, the release asset on the [release page](https://github.com/libfuse/libfuse/releases/tag/fuse-3.15.1) was (re-)uploaded after #135851 was merged.

> I guess technically libfuse 3.15.1 could have been untagged / unreleased then rereleased?

Not necessarily retagged, since release assets can be edited after a release is made.

**Comment by ZhongRuoyu** [comment]
#136489 should fix it. (Thanks for reporting!)

**Comment by 13steinj** [comment]
> Not necessarily retagged, since release assets can be edited after a release is made.

Interesting; I wonder what's the difference between that and github's autogenerated source code. I know some fsf projects don't check in configure scripts, but provide them in source releases, but libfuse uses meson.

**Comment by ZhongRuoyu** [comment]
> I wonder what's the difference between that and github's autogenerated source code.

Release assets are managed by project maintainers and are not limited to source code archives. They can also be prebuilt binaries, signatures, etc. See [LLVM releases](https://github.com/llvm/llvm-project/releases) for example.

The autogenerated archives only provide a snapshot of the Git repository. The contents are identical to `git` checkouts. Also, [their checksum may change](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/).

In general, we use release assets whenever they are available.

**Comment by ZhongRuoyu** [comment]
Please try again now -- this should be fixed.

**Comment by 13steinj** [comment]
yes it is! now to figure out what's wrong with the prebuilt version...
