### ISSUE TITLE
clipboard package has broken formatting

### ISSUE THREAD

**Issue by Slackadays** [Homebrew/homebrew-core#136551]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 7 days ago
Core tap JSON: 13 Jul 22:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.86.0 => /usr/bin/curl
macOS: 13.2.1-arm64
CLT: N/A
Xcode: 14.3.1
Rosetta 2: false

brew doctor:
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run the `clipboard` package (`cb` command) and see nice colors.

### What happened (include all command output)?

Color formatting codes are not converted into terminal escape sequences as intended:

```
[progress]⬤ Checking status... ?%, 0s elapsed ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒    [bla[info]┏━━[inverse] [info][bold]All of your clipboards with content[nobold] [noinverse]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓[blank]
┃ [bold]0[nobold]│ [blank][help]hello[blank]                                                ┃
[info]┗━━▌[help]Text, Files, Directories,  Data [info]▐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛[blank]
```

### What did you expect to happen?

```
┏━━ All of your clipboards with content ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ 0│ hello                                                                                  ┃
┗━━▌Text, Files, Directories, Data▐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install clipboard
cb copy hello
cb
```

**Comment by carlocab** [comment]
Can't reproduce, but I'm on Intel Monterey:
```
❯ cb copy hello
 ✔  Copied text "hello"
❯ cb
┏━━ All of your clipboards with content ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ 0│ hello                                                                                                                                           ┃
┗━━▌Text, Files, Directories,  Data ▐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by carlocab** [comment]
I can reproduce this by building from source outside of Homebrew:
```
git clone https://github.com/Slackadays/Clipboard.git
cmake -S Clipboard -B build -DCMAKE_BUILD_TYPE=MinSizeRel
cmake --build build
```
Then:
```
❯ build/cb copy hello
[success][inverse] ✔ [noinverse] Copied text "[bold]hello[blank][success]"[blank]
❯ build/cb
[info]┏━━[inverse] [info][bold]All of your clipboards with content[nobold] [noinverse]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓[blank]
┃ [bold]0[nobold]│ [blank][help]hello[blank]                                                                                                         ┃
[info]┗━━▌[help]Text, Files, Directories,  Data [info]▐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛[blank]
```

**Comment by carlocab** [comment]
I have a workaround at #136572, but it would be good for builds with `-Os` to be fixed upstream too.

**Comment by Slackadays** [comment]
I just went through some of my compile logs, and it turns out that there was a warning from Clang that said something about a deleted memory location once some string construction is done.

What this meant was, the reason this issue happened in the first place is because there is a Clang optimization that only happens with Os on ARM, where the memory of the found replacement result became nothing, so no colors ever got replaced. The reason I couldn't catch this is because CB switched to CMake's Release mode (O3) for all official builds, so it never happened in testing on my Mac Mini.

Last night, I made an optimization to this function that just so happened to fix the underlying issue once and for all by properly utilizing memory. And today, I made the whole thing 2x faster by making a manual comparison function.

This means that the specific O2 workaround can be removed without breaking anything. Unfortunately, in my testing, it turns out that with this new manual comparison function, Os (the default) is SLOWER than even O1 because of tons of function calls that aren't inlined. A similar thing is also present, at a much larger scale, elsewhere in the project. Therefore, the new O2 option is needed to keep performance high.

**Comment by carlocab** [comment]
Thanks! Do you have a performance comparison for O2 vs O3?

**Comment by Slackadays** [comment]
Here's some results for a benchmark I made that just runs this function 100000 times for a string with tons of colors:

O3:
```
Benchmark 1: ./test
  Time (mean ± σ):     360.7 ms ±   0.5 ms    [User: 359.7 ms, System: 0.8 ms]
  Range (min … max):   359.6 ms … 361.3 ms    10 runs
```

O2:
```
Benchmark 1: ./test
  Time (mean ± σ):     373.3 ms ±   1.0 ms    [User: 372.7 ms, System: 0.3 ms]
  Range (min … max):   372.0 ms … 375.8 ms    10 runs
```

Os:
```
Benchmark 1: ./test
  Time (mean ± σ):     493.4 ms ±   1.8 ms    [User: 492.1 ms, System: 1.0 ms]
  Range (min … max):   491.4 ms … 497.3 ms    10 runs
```

O1:
```
Benchmark 1: ./test
  Time (mean ± σ):     412.6 ms ±   1.5 ms    [User: 411.4 ms, System: 0.9 ms]
  Range (min … max):   410.9 ms … 414.8 ms    10 runs
```

O0:
```
Benchmark 1: ./test
  Time (mean ± σ):      3.167 s ±  0.003 s    [User: 3.161 s, System: 0.005 s]
  Range (min … max):    3.162 s …  3.172 s    10 runs
```

Note that running this function 100000 times is a realistic benchmark, because if you have that many entries in your clipboard history, that's how many times it'll be called along with a separate function that has about 600 comparison calls each.

**Comment by Slackadays** [comment]
For an even-more-optimized version:

O3:
```
Benchmark 1: ./test
  Time (mean ± σ):     221.7 ms ±   0.8 ms    [User: 220.9 ms, System: 0.6 ms]
  Range (min … max):   219.9 ms … 223.1 ms    15 runs
```

O2:
```
Benchmark 1: ./test
  Time (mean ± σ):     237.9 ms ±   1.2 ms    [User: 237.1 ms, System: 0.6 ms]
  Range (min … max):   236.1 ms … 239.9 ms    15 runs
```

Os:
```
Benchmark 1: ./test
  Time (mean ± σ):     244.2 ms ±   1.1 ms    [User: 243.3 ms, System: 0.6 ms]
  Range (min … max):   241.5 ms … 245.9 ms    15 runs
```

O1:
```
Benchmark 1: ./test
  Time (mean ± σ):     261.5 ms ±   1.3 ms    [User: 260.6 ms, System: 0.6 ms]
  Range (min … max):   258.7 ms … 263.7 ms    15 runs
```

O0:
```
Benchmark 1: ./test
  Time (mean ± σ):      1.341 s ±  0.006 s    [User: 1.338 s, System: 0.002 s]
  Range (min … max):    1.330 s …  1.352 s    15 runs
```

Looks like the difference between Os and O2 is a lot smaller here, but the difference between O2 and O3 is bigger.

**Comment by fxcoudert** [comment]
Original issue seems fixed, but we will have to remove the workarounds at next opportunity.

Regarding optimization, I don't think we want to tinker with defaults, unless there is a very compelling real-life user case.

**Comment by Slackadays** [comment]
I think CB in fact deserves an O3 optimization level, as I just ran a new benchmark comparing CMake's MinSizeRel (Os) against Release (O3) when displaying the history of a clipboard with 100K text entries:

Release
```
Benchmark 1: CLIPBOARD_FORCETTY=1 cb hs2
  Time (mean ± σ):     364.9 ms ±   5.3 ms    [User: 256.6 ms, System: 295.8 ms]
  Range (min … max):   357.0 ms … 374.3 ms    10 runs
```

MinSizeRel
```
Benchmark 1: CLIPBOARD_FORCETTY=1 cb hs2
  Time (mean ± σ):     526.7 ms ±   6.5 ms    [User: 435.5 ms, System: 291.0 ms]
  Range (min … max):   521.6 ms … 543.5 ms    10 runs
```

Going from Release to MinSizeRel is a whopping 45% slowdown!

**Comment by Slackadays** [comment]
@carlocab you can now make clipboard `O3` optimized thanks to the PR merge

**Comment by carlocab** [comment]
Thanks for the ping; I opened #138171.
