### ISSUE TITLE
kitchen-sync bottle with mariadb - Library not loaded

### ISSUE THREAD

**Issue by kuahyeow** [Homebrew/homebrew-core#13680]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

1. Install mariadb with `brew install mariadb`
2. Install `kitchen-sync` with `brew install kitchen-sync`
3. Run `ks --from=mysql://127.0.0.1:3306/a --to=mysql://127.0.0.1:3306/b`. Errors out.

```
kuah-air:homebrew-core kuahyeow$ brew install mariadb
==> Downloading https://homebrew.bintray.com/bottles/mariadb-10.1.23.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mariadb-10.1.23.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

MySQL is configured to only allow connections from localhost by default

To connect:
    mysql -uroot

To have launchd start mariadb now and restart at login:
  brew services start mariadb
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
🍺  /usr/local/Cellar/mariadb/10.1.23: 598 files, 156.1MB
```

```
kuah-air:homebrew-core kuahyeow$ brew info kitchen-sync
kitchen-sync: stable 0.58 (bottled), HEAD
Fast efficiently sync database without dumping & reloading
https://github.com/willbryant/kitchen_sync
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kitchen-sync.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: boost ✔, yaml-cpp ✔
==> Requirements
Recommended: mysql ✔
Optional: postgresql ✔
==> Options
--with-postgresql
	Build with postgresql support
--without-mysql
	Build without mysql support
--HEAD
	Install HEAD version
kuah-air:homebrew-core kuahyeow$ brew install kitchen-sync
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
homebank                            infer                               libcouchbase                        ode                                 wireguard-tools

==> Downloading https://homebrew.bintray.com/bottles/kitchen-sync-0.58.el_capitan.bottle.tar.gz
Already downloaded: /Users/kuahyeow/Library/Caches/Homebrew/kitchen-sync-0.58.el_capitan.bottle.tar.gz
==> Pouring kitchen-sync-0.58.el_capitan.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/kitchen-sync/0.58: 6 files, 429.7KB
```

```
kuah-air:homebrew-core kuahyeow$ ks --from=mysql://127.0.0.1:3306/a --to=mysql://127.0.0.1:3306/b
Kitchen Sync
dyld: Library not loaded: /usr/local/opt/mysql/lib/libmysqlclient.20.dylib
  Referenced from: /usr/local/bin/ks_mysql
  Reason: image not found
dyld: Library not loaded: /usr/local/opt/mysql/lib/libmysqlclient.20.dylib
  Referenced from: /usr/local/bin/ks_mysql
  Reason: image not found
Kitchen Syncing failed.
```

I would expect `ks --from=mysql://127.0.0.1:3306/a --to=mysql://127.0.0.1:3306/b` to run  error. If I `brew install --HEAD kitchen-sync`, I should see a normal `ks` run (albeit with permission errors) 

```
kuah-air:homebrew-core kuahyeow$ ks --from=mysql://127.0.0.1:3306/a --to=mysql://127.0.0.1:3306/b
Kitchen Sync
Access denied for user ''@'localhost' to database 'b'
Access denied for user ''@'localhost' to database 'a'
Kitchen Syncing failed.
```

gist-logs https://gist.github.com/3563c60cc26f28acb41a1f886bc82cad

**Comment by makigumo** [comment]
You need to install *mysql* to get the required libs. This requirement probably won't change until *kitchen-sync* supports compilation with *mariadb*.

**Comment by kuahyeow** [comment]
@makigumo I'm not sure how you mean by kitchen-sync not supporting compilation with mariadb. As you can see above, I did successfully compile kitchen sync with mariadb libs (when I use `brew install --HEAD kitchen-sync`).

**Comment by makigumo** [comment]
Ok, didn't know it would compile with *mariadb* (Just tested with *mariadb 10.2.6* and *kitchen-sync --HEAD* and it did not compile.). Anyway the brew *kitchen-sync* is built using *mysql* so you probably have to either install *mysql* or build *kitchen-sync* from source yourself.

**Comment by MikeMcQuaid** [comment]
> brew install kitchen-sync

If you run this it installs using the bottle and installs MySQL. Are you sure you did not manually remove `mysql` after that?

**Comment by kuahyeow** [comment]
No, I did not install mysql nor manually removed it. I installed mariadb first, followed by kitchen-sync.

> depends_on :mysql

That does not automatically install the mysql formula as the symbol :mysql translates to `MysqlRequirement`, something I learnt recently via ilovezfs. Instead MysqlRequirement detects I have a `mysql_config` installed courtesy of the mariadb formula.

**Comment by kuahyeow** [comment]
Oh, mariadb has been bumped from 10.1 to 10.2 ! Ouch, that probably changes things.

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid If I recall, we'd determined this is actually a brew bug where it's no longer enforcing the use of the default formula for bottles.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Yeh, this is still on my list to get around to, sorry for the delay.
