### ISSUE TITLE
eatmydata error: unable to find 'eatmydata' in PATH

### ISSUE THREAD

**Issue by ojwb** [Homebrew/homebrew-core#136873]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

# brew config

```shell
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 12 days ago
Core tap JSON: 18 Jul 05:56 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 3-core 64-bit ivybridge
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Applications/Xcode_14.2.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 12.6.7-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2 => /Applications/Xcode_14.2.app/Contents/Developer
```

# brew doctor
```
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to install the libeatmydata package in a GHA CI job in the hope of speeding up a testsuite run by eliminating time spent committing changes to disk.

### What happened (include all command output)?

I get an error when I try to run seemingly any command under eatmydata - e.g. `eatmydata ls /` gives:

```
eatmydata error: unable to find 'eatmydata' in PATH
```

### What did you expect to happen?

I'd expect it to successfully run `ls /` - that's what happens on platforms with a working eatmydata (for example, I tested on a Debian Linux machine using the Debian `eatmydata` package).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libeatmydata
eatmydata ls /
```

I created a repo to test this via GHA since I don't own a mac.  The workflow file I used is:

https://github.com/ojwb/homebrew-eatmydata-test/actions/runs/5583835375/workflow

Result of a run is:

https://github.com/ojwb/homebrew-eatmydata-test/actions/runs/5583835375/jobs/10204559309
```

**Comment by carlocab** [comment]
This is likely a limitation due to Apple's [SIP](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection). The short story here is that `eatmydata` will not work on binaries that live in `/[s]bin` or `/usr/[s]bin`.

Can you try doing
```
eatmydata gls /
```
?

If that works, and you prefer to call `gls` as `ls`, see the caveats of the `coreutils` formula:
```
==> Caveats
Commands also provided by macOS and the commands dir, dircolors, vdir have been installed with the prefix "g".
If you need to use these commands with their normal names, you can add a "gnubin" directory to your PATH with:
  PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
```

**Comment by carlocab** [comment]
I tried this out and it looks like my guess was incorrect. However, the following does work:
```
export PATH="$(brew --prefix libeatmydata)/bin:$PATH"
eatmydata ls /
```
It looks like `eatmydata` doesn't like the way `brew` installs `eatmydata` into it's own prefix and then symlinks it into `HOMEBREW_PREFIX`.

This seems like an upstream bug to me.

**Comment by ojwb** [comment]
Thanks for the `export PATH="$(brew --prefix libeatmydata)/bin:$PATH"` trick - I do at least have a workaround now.

I'm actually hitting this with a C++ test program built by the CI job so SIP shouldn't kick in AIUI.  My `ls` example was just an attempt to provide a minimal reproducer, that isn't what I'm actually trying to do as such.

I believe I now understand what's happening - eatmydata supports a "symlink mode":

> In  order  to  use  symlink  mode,  create  a  symlink  to
       /usr/bin/eatmydata  with  the filename (a.k.a basename) of another pro‐
       gram in the PATH and execute eatmydata via that symlink. Then eatmydata
       will find that program in the PATH and run it in the libeatmydata envi‐
       ronment repassing all command line options.

It looks like homebrew's symlink makes the eatmydata wrapper think it's being run in symlink mode and so it tries to find the "real" eatmydata further down PATH to run (and fails to find it so reports the error).  Probably checking if symlink basename is eatmydata and not treating that as "symlink mode" would solve this.

I'll try reporting upstream though upstream doesn't look all that active.

**Comment by cho-m** [comment]
Would be best if upstream fixes it.

A workaround would be to install `eatmydata` script under libexec and create an exec script instead which should allow script to be run via realpath and avoid this symlink mode.

**Comment by ojwb** [comment]
I don't have a mac, but this patch seems to solve my recreation of the symlink situation on Linux:

```
diff --git a/eatmydata.in b/eatmydata.in
index e37f07c1..428d520a 100644
--- a/eatmydata.in
+++ b/eatmydata.in
@@ -31,9 +31,19 @@ usage()
 
 # Detect operation mode. If this script is run via symlink, look for basename
 # in the PATH and execute it.
+cmd=
 if [ -L "$0" ]; then
     # Symlink mode. Get command to execute from the basename of $0.
     cmd="`basename "$0"`"
+    if [ "$cmd" = "eatmydata" ] ; then
+	# Don't engage symlink mode for a symlink from "eatmydata" though as
+	# that breaks with how homebrew installs each package in its own
+	# prefix and symlinks the binaries into a common "bin" directory.
+	cmd=
+    fi
+fi
+
+if [ -n "$cmd" ] ; then
     set -- "$cmd" "$@"
 else
     # Normal mode
```

I'll open a PR upstream, but if someone wants to confirm this patch works in homebrew that'd be useful.

**Comment by ojwb** [comment]
It occurred to me I could test by applying the patch to the installed eatmydata wrapper in CI, so I did that:

https://github.com/ojwb/homebrew-eatmydata-test/actions/runs/5650308016/job/15306429062

Without patch `eatmydata ls / || true` gives:

```
eatmydata error: unable to find 'eatmydata' in PATH
```

With patch: `eatmydata ls /` gives:

```
Applications
Library
System
Users
Volumes
bin
cores
dev
etc
home
opt
private
sbin
tmp
usr
var
```

So the patch does solve the problem.

**Comment by ojwb** [comment]
https://github.com/stewartsmith/libeatmydata/pull/33

**Comment by ojwb** [comment]
Upstream has merged my fix.

**Comment by ojwb** [comment]
Just to confirm that my original problem (with trying to use the homebrew libeatmydata package in a CI job) is fixed with current homebrew.  Thanks everyone.

**Comment by carlocab** [comment]
Does it actually do what you needed it to?

`eatmydata` relies on `DYLD_FORCE_FLAT_NAMESPACE` and `DYLD_INSERT_LIBRARIES`, which, in my experience, no longer works on newer versions of macOS.

**Comment by ojwb** [comment]
Hmm, thanks for asking.

It now "works" in as much as `eatmydata foo` runs `foo`, but from what you say it might not be intercepting `fsync`, etc which is what I'm actually wanting.  GHA CI jobs still seem to run rather slowly on macos compared to Ubuntu, but that seems to be a general issue with the github macos runners (at least I've found other people complaining about it, but github don't seem able to/interested in addressing it).

I'll investigate and open a new issue here or upstream if I can show it isn't actually making fsync, etc a no-op like it should.
