### ISSUE TITLE
Question around generic names.

### ISSUE THREAD

**Issue by kennycason** [Homebrew/homebrew-core#1370]
Hi, I created a program called "run" which is essentially an "easy-to-use alias" program. https://github.com/kennycason/run

I created the brew formula, got it working on my machine, etc. Then I discovered `brew audit` and found that I picked one of the 4 names that are too generic.

Is `run` a reserved word somewhere that i'm not aware of? Or is there another reason it's flagged as too generic? 

I'm open to new names (call?) but was curious of this restriction. Thanks! :)

**Comment by UniqMartin** [comment]
The original commit that introduced the check is Homebrew/brew@81bf8a168ada914ec47ca5b37a9fe44f8d797fea and two more items were added to the list in Homebrew/brew@bba2b7616735fe5503923c908cc36c9222b40393. This was added way before my time with Homebrew and both don't provide too much context as there's no linked PR. Maybe one of the more seasoned maintainers remembers whether there has been any discussion and can comment.

To my knowledge, `run` isn't a reserved word anywhere, so I'm not sure this audit check has any merit beyond preventing overly generic names. (But then this list seems a bit arbitrary, at least to me.)

**Comment by MikeMcQuaid** [comment]
What you name your project and programs is totally up to you, to be clear. They just may need renamed if added to Homebrew core to something like `kenny-run` to avoid conflicts.
