### ISSUE TITLE
Git completions installed by Homebrew

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew-core#13700]
This might be more of a support issue.

- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? --> not applicable, problem with the formula itself or I am the problem?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.2.1-12-g0977b4a17d
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0977b4a17d92853a952bcba643cfd3dac21db944
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b39cdd5b5f0acda2aa9ca2a27af4e1772b9d4611
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/werner/.rbenv/shims/ruby => /Users/werner/.rbenv/versions/2.3.0/bin/ruby
Java: 1.6.0_65-b14-466.1
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.8 => /opt/X11
```
**What you were trying to do (and why)**

Per default, Zsh offers extensive Git autocompletion:

![image](https://cloud.githubusercontent.com/assets/582444/26218291/c273267e-3c0a-11e7-9ebd-d0237bcb06ec.png)

For example, here I can preview individual commits.

**What happened (include command output)**

Once I install Git with `brew install git`, these autocompletion options are gone, and back to a minimum:

![image](https://cloud.githubusercontent.com/assets/582444/26218360/faf9172e-3c0a-11e7-81f3-dafffd24a9f4.png)

This is because Homebrew creates the respective autocompletion files in `/usr/local/share/zsh/site-functions/git-completion.bash` and `/usr/local/share/zsh/site-functions/_git`, which, apparently, reduce functionality?

**What you expected to happen**

I expected the completions to actually offer me the same functionality, not less, than what Zsh already gave me.

Is this intended behavior, and am I supposed to install Git without completions then? (I see that the formula provides an option for that.) Or is this a bug with the completion files that the Git formula is installing? (If so, I guess I'd ask there instead.)

Thanks for any pointers!

**Comment by MikeMcQuaid** [comment]
These are unmodified upstream files provided by Git itself so I'd suggest asking them rather than us. If ZSH's completions are deemed to be consistently better we may consider a PR removing ZSH completions by default.
