### ISSUE TITLE
rollback request: downgrade Go formula 1.20.6 to 1.20.5

### ISSUE THREAD

**Issue by nicks** [Homebrew/homebrew-core#137413]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Upgrading from Go 1.20.5 to Go 1.20.6 accidentally included a major breaking change that breaks a lot of CLIs in the Go ecosystem. 

We're working with the Go team on addressing the problem. More discussion here: https://github.com/golang/go/issues/61431

This is causing major downstream problems for us because Homebrew-core auto-upgrades everyone to Go 1.20.6. Any new releases of code written in Go will appear to compile correctly, but may contain this bug, and may not work.

What are the pros/cons of rolling the Go formula in Homebrew-core back to Go 1.20.5 while Go-team fixes the issue? would it be enough to rollback https://github.com/Homebrew/homebrew-core/commit/3659ac0f72456981dd47c88f329ac73f2d4dd924 ?

Alternatively, is there a way to mark formulas "only works with Go 1.20.5, refuse to compile with Go 1.20.6"?

Thanks!

### What happened (include all command output)?

see above

### What did you expect to happen?

see above

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see above
```

**Comment by alebcay** [comment]
If upstream does roll it back (e.g. there's a pull request for it), I think it would be preferable to take the rollback/revert/fix commit on as a patch to be applied on top of 1.20.6 rather than to roll back to 1.20.5.

While we do have `version_scheme` DSL available that can facilitate a rollback downstream here, it's not really designed for this purpose. Just my two cents.

**Comment by MikeMcQuaid** [comment]
Yes: please don't use version_scheme for this.

**Comment by fxcoudert** [comment]
Upstream has decided to patch all active branches, but not roll back the release (probably not considered critical). Closing here. We'll ship the next version, and it will have the fix in it.
