### ISSUE TITLE
Compiling python 2/3 with gcc

### ISSUE THREAD

**Issue by nash169** [Homebrew/homebrew-core#13759]
Hi there,
I'm trying to compile python with home-brew installed gcc but I'm experiencing different issues.

**Python 2**
The compilation of python2 fails due to the incompatibility between some gcc and apple headers:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h
or
/System/Library/Frameworks/Security.framework/Headers/Authorization.h
Briefly the problem is caused by the definition of certain const variables. Clang fails to diagnose the error, so the compilation works out, while gcc not.
The modification of the "buggy" headers is not difficult. However if one does not want to modify system files it is possible to avoid references to those headers by disabling toolboxglue through the command:
'--disable-toolbox-glue'

Although, in this way, I can complete the "make" phase, I get an error during the "make install" phase:
Traceback (most recent call last):
File "./scripts/cachersrc.py", line 7, in 
import macresource
File "/private/tmp/python-20170517-26442-qubnnu/Python-2.7.13/Lib/plat-mac/macresource.py", line 6, in 
from Carbon import Res
File "/private/tmp/python-20170517-26442-qubnnu/Python-2.7.13/Lib/plat-mac/Carbon/Res.py", line 4, in 
from _Res import *
ImportError: No module named _Res
make[1]: *** [installmacsubtree] Error 1
make: *** [frameworkinstallmaclib] Error 2

Here the gist-logs:
https://gist.github.com/22dfdd23f69c3830b9a18e0da08e167e

**Python 3**
For python 3 the "make" phase runs fine without any modification, but the "make install" returns multiple errors:
value = [dict objectForKey: @"scriptargs"];
     ^~~~~
./FileSettings.m:238:5: warning: 'NSDictionary' may not respond to '-objectForKey:'
     value = [dict objectForKey: @"with_terminal"];
     ^~~~~
./FileSettings.m: In function '-[FileSettings _replaceSingleQuotes:]':
./FileSettings.m:247:5: warning: initialization from distinct Objective-C type
     NSArray* components = [string componentsSeparatedByString:@"'"];
     ^~~~~~~
./FileSettings.m:249:5: warning: 'NSArray' may not respond to '-componentsJoinedByString:'
     return [components componentsJoinedByString:@"'\"'\"'"];
     ^~~~~~
make[2]: *** [FileSettings.o] Error 1
make[1]: *** [install_PythonLauncher] Error 2
make: *** [frameworkinstallapps] Error 2

The gist-logs:
https://gist.github.com/c64261138f7dc66bc0cf8a928148e9f6

The errors here are probably related to issues arising from obj-c files compilation with gcc.

Did anyone experience the same problems?

**Comment by MikeMcQuaid** [comment]
Sorry, we don't support failures when using non-default compilers to install software.
