### ISSUE TITLE
How does one install non-inline plists in formulas?

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#13768]
I see several formulas that use `def plist` to define a plist inline, and this seems to be supported out-of-the-box. Is it however possible to include plists that are files within the source, just modifying some simple `inreplace`s? Or rather, is there a convenience feature for this, like there is for inline plist definitions?

**Comment by MikeMcQuaid** [comment]
Please always fill in the issue template, as requested.

> Is it however possible to include plists that are files within the source, just modifying some simple inreplaces?

Yes, see `Formula/vdirsyncer.rb` for an example. As a general note, `grep -r plist $(brew --repo homebrew/core) | grep inreplace` will allow you to answer these questions quickly yourself.

**Comment by alexreg** [comment]
Even for questions? Okay then...

Thanks for the suggestion, in any case.

**Comment by MikeMcQuaid** [comment]
This is not the best place for questions. https://discourse.brew.sh or IRC is a better fit.

**Comment by alexreg** [comment]
Thank you. I was unaware of that! IRC is kind of dead, but I'll definitely try out discourse.brew.sh.

**Comment by ilovezfs** [comment]
>IRC is kind of dead

Tell that to the 216 people in the channel.

**Comment by alexreg** [comment]
> IRC is kind of dead
> Tell that to the 216 people in the channel.

Of which almost all are idlers, if you're actually on there! 😛
