### ISSUE TITLE
I want to add msbuild into mono package

### ISSUE THREAD

**Issue by mfilippov** [Homebrew/homebrew-core#13788]
I want to add "msbuild" into "mono" formula. But build script download zip with tools from bootstrap from the internet and use NuGet in build time for restore packages. It is a common way for building .NET project but in Homebrew cookbook I read that is isn't a good way. Is it ok? Without msbuild mono formula is not completed.
FYI msbuild download the certain version of bootstrap fixed in sources.
** Downloading MSBUILD from https://github.com/Microsoft/msbuild/releases/download/mono-hosted-msbuild-v0.03/mono_msbuild_d25dd923839404bd64cc63f420e75acf96fc75c4.zip

**Comment by dunn** [comment]
If you can get it to work without build scripts making network calls, we'd be happy to look at a PR! You would want to use `resource` blocks for the tools that are downloaded at build-time.  The easiest way to get an idea of how they're used is probably just looking at existing formulae; but let us know if you have questions!
