### ISSUE TITLE
Problem installing pulseview - Error: marshal data too short

### ISSUE THREAD

**Issue by xog00** [Homebrew/homebrew-core#13787]
# Please always follow these steps:
- [ y] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ y] Ran `brew update` and retried your prior step?
- [y ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ y] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?   https://gist.github.com/6ea7efd602f701d1ea80e297e28877f4

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

SW-MacBook-Lab:macosx swilliams$ brew install --HEAD pulseview
==> Installing pulseview from rene-dev/sigrok
==> Cloning git://sigrok.org/pulseview
Updating /Users/swilliams/Library/Caches/Homebrew/pulseview--git
==> Checking out branch master
==> cmake . -DENABLE_DECODE=y -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_IN
Last 15 lines from /Users/swilliams/Library/Logs/Homebrew/pulseview/01.cmake:
Call Stack (most recent call first):
  CMakeLists.txt:87 (find_package)

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Atomics provided by the C-library - yes
-- Performing Test HAVE_UNALIGNED_LITTLE_ENDIAN_ACCESS
-- Performing Test HAVE_UNALIGNED_LITTLE_ENDIAN_ACCESS - Success
-- PulseView version: 0.4.0-git-d008cab
-- Configuring incomplete, errors occurred!
See also "/tmp/pulseview-20170521-91333-3262me/CMakeFiles/CMakeOutput.log".
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `dump': can't dump anonymous class #<Class:0x007fe8b0ac97c0> (TypeError)
	from /usr/local/Homebrew/Library/Homebrew/build.rb:191:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:180:in `<main>'
Error: marshal data too short
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:389:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:658:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:312:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:207:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'

**Comment by JCount** [comment]
I am sorry, but you really need to file this issue with whomever maintains the tap hosting the formula you cannot build.

The real error messages here are at the beginning of this post and in your gist, and they point toward an issue(s) with the HEAD spec of the formula you are trying to build.

The Homebrew debug output at the end of your post that most likely led you to report here is merely a trace of the build stack because it threw an error trying to create a dump as part of handling the build exception.
