### ISSUE TITLE
Curl zsh completions aren't installed into the standard path

### ISSUE THREAD

**Issue by Logicer16** [Homebrew/homebrew-core#137882]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.1.2-11-g4c612ab
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4c612ab324677e75ccbf6fd44fdd885f2c6a4156
Last commit: 23 hours ago
Core tap JSON: 27 Jul 13:29 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 300
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/env nvim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 14.0.0 build 1400
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.8-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use `curl` zsh completions by adding `$(brew --prefix)/share/zsh/site-functions` to my `$FPATH`.

### What happened (include all command output)?

Instead, as stated by the caveats:

```
zsh completions have been installed to:
  /usr/local/opt/curl/share/zsh/site-functions
```

It is a minor inconvenience to have to add an extra path to `$FPATH`, but it defies expectations when the caveats message is ignored due to assuming the zsh completions will be installed into the same directory as most other formulae.

### What did you expect to happen?

Like other formulae, install zsh completions into `$(brew --prefix)/share/zsh/site-functions`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install curl
```

**Comment by gromgit** [comment]
The very first caveat tells you why the `curl` completions aren't linked into the main hierarchy:
```
==> Caveats
==> curl
curl is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.
```
> it defies expectations when the caveats message is ignored due to assuming the zsh completions will be installed into the same directory as most other formulae.

I'm not sure what you mean here.

**Comment by Logicer16** [comment]
Ah, my misunderstanding.

Got a bit confused with git installing completions to the standard path, but it seems for whatever reason git is not key-only even though macOS provides git.
