### ISSUE TITLE
[starship] latest version 1.16.0 always warns about AppleRawMaxCapacity

### ISSUE THREAD

**Issue by superbonaci** [Homebrew/homebrew-core#138065]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3db1acf3e38e270af4e1c3f214622bbfb18f830e
Last commit: 4 days ago
Core tap JSON: 30 Jul 19:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_MAKE_JOBS: 8
```
```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  brew-pip
[WARN] - (starship::modules::battery): Unable to access battery information:
AppleRawMaxCapacity
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
[WARN] - (starship::modules::battery): Unable to access battery information:
AppleRawMaxCapacity
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run bash inside zsh.

### What happened (include all command output)?

After latest `starship` update, it always launches a warning when launching bash, with starship profile in it:
```
% /opt/homebrew/bin/bash
[WARN] - (starship::modules::battery): Unable to access battery information:
AppleRawMaxCapacity
```
starship version:
```
$ brew list starship
/opt/homebrew/Cellar/starship/1.16.0/.crates.toml
/opt/homebrew/Cellar/starship/1.16.0/.crates2.json
/opt/homebrew/Cellar/starship/1.16.0/bin/starship
/opt/homebrew/Cellar/starship/1.16.0/etc/bash_completion.d/starship
/opt/homebrew/Cellar/starship/1.16.0/share/fish/vendor_completions.d/starship.fish
/opt/homebrew/Cellar/starship/1.16.0/share/zsh/site-functions/_starship
[WARN] - (starship::modules::battery): Unable to access battery information:
AppleRawMaxCapacity
```

### What did you expect to happen?

Handle different.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Already explained.
```

**Comment by SMillerDev** [comment]
What does brew have to do with this?

**Comment by gromgit** [comment]
@superbonaci Always check with upstream first to see if it's a general issue rather than Homebrew-specific. Simply going to [`starship`'s issues page](https://github.com/starship/starship/issues) immediately surfaces this: https://github.com/starship/starship/issues/5350
