### ISSUE TITLE
Python versions installed with pyenv are not kept when updating pyenv

### ISSUE THREAD

**Issue by davidparsson** [Homebrew/homebrew-core#13814]
When installing a new Python version with `pyenv` (installed via brew), the new Python version is installed to `/usr/local/opt/pyenv/versions/<python-version>`, which of course symlinks to `/usr/local/Cellar/pyenv/<pyenv-version>/versions/<python-version>`.

If `pyenv` is updated after that, `/usr/local/opt/pyenv/versions` then points to `/usr/local/Cellar/pyenv/<new-pyenv-version>/versions`, which is empty, requiring the user to re-install all wanted Python versions.

Is this by design or unintended?

**Comment by ilovezfs** [comment]
CC @tdsmith

**Comment by zmwangx** [comment]
This shouldn't be the case. Unless you set `PYENV_ROOT`, it defaults to `$HOME/.pyenv`. See https://github.com/pyenv/pyenv/blob/e93ae00/libexec/pyenv#L53-L58. Pythons are installed to this `PYENV_ROOT`. Are you doing anything weird like setting `PYENV_ROOT` to `/usr/local/opt/pyenv`?

**Comment by davidparsson** [comment]
Sorry. This is an issue with oh-my-zsh's pyenv plugin, not with homebrew. Sorry to waste your time and thanks for your help!

**Comment by zmwangx** [comment]
@davidafsilva  No worries. Plug: I highly recommend [Prezto](https://github.com/sorin-ionescu/prezto) to replace OMZ. More performant, cleaner module architecture, considerably better code quality compared to the hodgepodge that is OMZ.

**Comment by zmwangx** [comment]
(Apologies to apjanke in case you see this.)
