### ISSUE TITLE
Brotli: Extra Libs flag `-R` in libbrotlidec.pc

### ISSUE THREAD

**Issue by rootkea** [Homebrew/homebrew-core#138181]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 128df14e0afd0525564051a7665708c2973a3cab
Last commit: 17 hours ago
Core tap JSON: 01 Aug 06:26 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
% brew doctor
Your system is ready to brew.
%
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Hello!

I'm trying to build wget2 (https://gitlab.com/gnuwget/wget2) which uses brotli as a dependency. So I installed `brotli` using homebrew but then I found out that the wget2 build was failing.

### What happened (include all command output)?

The build was failing because `libbrotlidec.pc` has extra `Libs` flag `-R` compared to upstream.
```
% cat /opt/homebrew/lib/pkgconfig/libbrotlidec.pc
prefix=/opt/homebrew/Cellar/brotli/1.0.9
exec_prefix=/opt/homebrew/Cellar/brotli/1.0.9
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libbrotlidec
URL: https://github.com/google/brotli
Description: Brotli decoder library
Version: 1.0.9
Libs: -L${libdir} -R${libdir} -lbrotlidec
Requires.private: libbrotlicommon >= 1.0.2
Cflags: -I${includedir}
% curl https://raw.githubusercontent.com/google/brotli/master/scripts/libbrotlidec.pc.in
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@

Name: libbrotlidec
URL: https://github.com/google/brotli
Description: Brotli decoder library
Version: @PACKAGE_VERSION@
Libs: -L${libdir} -lbrotlidec
Requires.private: libbrotlicommon >= 1.0.2
Cflags: -I${includedir}
% 
```

While `clang` treats `-R` as a diagnostic flag (remark flag), `gcc` doesn't recognise it which fails the program checking brotli dependency.

The same issue is with the other 2 `.pc` files: `libbrotlienc.pc` and `libbrotlicommon.pc` 

### What did you expect to happen?

I expected `.pc` files to be same as that of upstream. Is there a reason to include `-R` flag in `Libs` section of `.pc` files?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. % brew install brotli
2. % cat /opt/homebrew/lib/pkgconfig/libbrotlidec.pc
```

**Comment by SMillerDev** [comment]
As you can see in https://github.com/Homebrew/homebrew-core/blob/1defd029b944852809b60ef696cde4fe7383bc53/Formula/brotli.rb, Homebrew does not modify that file. It's all generated by upstream like this.

**Comment by rootkea** [comment]
I did look at the formula to figure out the change but didn't see any.

BTW, on Debian I don't see any extra flag in `Libs` section of `libbrotlidec.pc`.
```
$ cat /usr/lib/aarch64-linux-gnu/pkgconfig/libbrotlidec.pc
prefix=/usr
exec_prefix=/usr
libdir=${prefix}/lib/aarch64-linux-gnu
includedir=${prefix}/include

Name: libbrotlidec
URL: https://github.com/google/brotli
Description: Brotli decoder library
Version: 1.0.9
Libs: -L${libdir} -lbrotlidec
Requires.private: libbrotlicommon >= 1.0.2
Cflags: -I${includedir}
$ 
```

**Comment by rootkea** [comment]
I just git cloned and built `brotli` on macOS and there's no extra `-R` in `Libs` section of `libbrotlidec.pc`. So clearly Homebrew is doing something different.
```
% cat installed/lib/pkgconfig/libbrotlidec.pc
prefix=/Users/avinashsonawane/Downloads/hacking/brotli/out/installed
exec_prefix=/Users/avinashsonawane/Downloads/hacking/brotli/out/installed
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libbrotlidec
URL: https://github.com/google/brotli
Description: Brotli decoder library
Version: 1.0.9
Libs: -L${libdir} -lbrotlidec
Requires.private: libbrotlicommon >= 1.0.2
Cflags: -I${includedir}
% 
```

**Comment by carlocab** [comment]
> I just git cloned and built `brotli` on macOS and there's no extra `-R` in `Libs` section of `libbrotlidec.pc`. So clearly Homebrew is doing something different to the upstream source. Or am I missing something?

You didn't build the same version. Try using the tarball at https://github.com/google/brotli/archive/v1.0.9.tar.gz, or checkout the `v1.0.9` tag in your clone.

**Comment by rootkea** [comment]
@carlocab Ah, of course! It seems the issue was fixed upstream 3 years back just after the v1.0.9 release. https://github.com/google/brotli/pull/838/commits/092446fafb4bfb81738853b7c7f76b293cd92a80

What are the options here? Wait for an upstream release or is there a way in Homebrew to add and maintain patches to packages?

**Comment by carlocab** [comment]
Probably better to see if we can nudge upstream to cut a new release tag. You're the second person in about as many years to notify us about this problem (see #87153), so I'm not (yet) convinced it's worth patching here.

**Comment by rootkea** [comment]
Okay, cool! Closing this one as not a bug but the upstream issue.

**Comment by rootkea** [comment]
I have 2 related questions (this is from someone who's completely new to Homebrew and macOS):

```
% find /opt/homebrew -name libbrotlidec.pc
/opt/homebrew/lib/pkgconfig/libbrotlidec.pc
/opt/homebrew/Cellar/brotli/1.0.9/lib/pkgconfig/libbrotlidec.pc
% find /opt/homebrew -name icu-uc.pc
/opt/homebrew/Cellar/icu4c/73.2/lib/pkgconfig/icu-uc.pc
%
```

1. Why is `icu-uc.pc` is at one place only unlike `libbrotlidec.pc`?
This is causing issue while building `wget2`. Its dependency `libpsl` has `Requires.private: icu-uc` in `libpsl.pc` but `icu-uc.pc` is missing from `/opt/homebrew/lib/pkgconfig` which makes `pkg-config` unable to detect `icu-uc`. So why is `icu-uc.pc` is not at `/opt/homebrew/lib/pkgconfig` but `libbrotlidec.pc` is?

2. How is `brew install -s --verbose wget2` able to detect `libpsl` without any issue? I mean, this above issue of `pkg-config` not being able to find `icu-uc`, how come it's not happening in this case? Do we modify pkg-config path while building from source?

Thanks!

**Comment by rootkea** [comment]
@onlynone Hey Steven, I see you added the `wget2` formula (thanks for that!). Could you please help me out here? I'm trying to build `wget2` and I'm stuck at `libpsl` not getting detected. (Please see above comment)

From `config.log`:
```
configure:65033: checking for libpsl
configure:65040: $PKG_CONFIG --exists --print-errors "libpsl"
Package icu-uc was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-uc.pc'
to the PKG_CONFIG_PATH environment variable
Package 'icu-uc', required by 'libpsl', not found
```

But I don't see this error in `config.log` generated by `brew install -s --verbose wget2`. How's that possible?

**Comment by SMillerDev** [comment]
> Why is icu-uc.pc is at one place only unlike libbrotlidec.pc?

Because the formula is keg-only so that it doesn't override macOS versions of it.

> Do we modify pkg-config path while building from source?

Yes, declared dependencies are added to the path AFAIK

**Comment by rootkea** [comment]
Ah, okay. So should I copy-paste `icu-uc.pc` from `/opt/homebrew/Cellar/icu4c/73.2/lib/pkgconfig/icu-uc.pc` to `/opt/homebrew/lib/pkgconfig/` so that `pkg-config` finds it or should I add `/opt/homebrew/Cellar/icu4c/73.2/lib/pkgconfig` to `pkg-config` path?

**Comment by SMillerDev** [comment]
No, just depend on `icu4c`

**Comment by onlynone** [comment]
> I'm trying to build `wget2` and I'm stuck at `libpsl` not getting detected. (Please see above comment)
> 
> From `config.log`:
> 
> ```
> configure:65033: checking for libpsl
> configure:65040: $PKG_CONFIG --exists --print-errors "libpsl"
> Package icu-uc was not found in the pkg-config search path.
> Perhaps you should add the directory containing `icu-uc.pc'
> to the PKG_CONFIG_PATH environment variable
> Package 'icu-uc', required by 'libpsl', not found
> ```
> 
> But I don't see this error in `config.log` generated by `brew install -s --verbose wget2`. How's that possible?

So, it sounds like `libpsl` depends on `icu-uc` and `icu-uc` can't be found? Are transitive dependencies usually handled automatically? Anyway, I it looks like `icu-uc.pc` is provided by the `icu4c` package as you found. I have the following in the formula for `wget2`:

```
  uses_from_macos "icu4c"
```

I believe that directive tells homebrew to use the include and library paths for the system version `icu4c` when compiling `wget2` which is how it finds it.

Honestly I was doing a lot of trial and error trying to get it to compile, figuring out library dependencies, figuring out which packages included those libraries, then which ones should be installed via homebrew and which ones could be used via the system, and figuring out which extra flags I *still* needed during compile because for whatever reason they weren't being added automatically. Once I got it working, all that info went out of my head.

If you're having trouble compiling `wget2` manually, can't you just run the install from source with homebrew in verbose mode to find out exactly what it's using to compile it?
