### ISSUE TITLE
Add synergy formula

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-core#1383]
### Formula Requests:

    **Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

    We will consider your request but it may be closed if it's something we're not actively planning to work on.

Well, since I can't find a pull request in progress, this probably is not in the works already.

I propose to add Synergy http://synergy-project.org/synergy/ as a build from source thing to home-brew. It is open source, and the sources are available, so it would be a great boon to brew to have it included.

**Comment by UniqMartin** [comment]
That's not a new discussion, see e.g. Homebrew/legacy-homebrew#34265. Somebody gave this a try in Homebrew/legacy-homebrew#38200 but ultimately failed. As we don't have a formula yet, this probably means one of:

- This is not a trivial task and nobody was able to resolve all outstanding issues.
- There is not enough interest from maintainers/contributors.

If you're passionate about this, consider putting together a PR (the [Formula Cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md) should get you started and the above mentioned issues/PRs might help, too), but be prepared to encounter difficulties in getting it to build.

Closing as this is not something we plan to work on currently.
