### ISSUE TITLE
Post-install step of `glibc` formula doesn't set the local time zone correctly

### ISSUE THREAD

**Issue by giuseppedandrea** [Homebrew/homebrew-core#138532]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config
HOMEBREW_VERSION: 4.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 128df14e0afd0525564051a7665708c2973a3cab
Last commit: 4 days ago
Core tap JSON: 04 Aug 10:48 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 20.04.6 LTS (focal)
WSL: 2 (Microsoft Store)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

```shell
> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

While working on an [unrelated issue](https://github.com/jrnl-org/jrnl/issues/1607#issuecomment-1662524297) in another repository, I discovered that the `glibc` formula, which provides the C standard library, doesn't correctly set the local time zone during the post-install step. The UTC time is always used by the library, and not the local time zone.

### What happened (include all command output)?

The function `tzset()` of the C standard library is automatically called by other time conversion functions that depend on the timezone. In particular:

- The `tzset()` function initializes the `tzname` variable from the `TZ` environment variable
- If the `TZ` variable does not appear in the environment, the system timezone is used
- The system timezone is configured by copying, or linking, a file in the [tzfile format](https://man7.org/linux/man-pages/man5/tzfile.5.html) to */etc/localtime*
- If the default tzfile is not found (or it is in the wrong format), the UTC time is used
- 
The `glibc` formula installed with Homebrew looks for the tzfile located at *<HomebrewPrefix>/etc/localtime*, but this file doesn't exist. As a result, the UTC time is used.
The post-install step of the `glibc` formula should create this file with a symbolic link to the system tzfile (located at */etc/localtime*) but I think there is a bug in the condition:
https://github.com/Homebrew/homebrew-core/blob/d83b5e63469db4df6289b0f79cc1341daf3b7945/Formula/glibc.rb#L228-L231
As you can see, the symbolic link is created only if `brew_localtime` exists. But this is quite strange, it should be the opposite, as in the similar condition some lines below related to zoneinfo file. So the condition should be `sys_localtime.exist? && !brew_localtime.exist?` instead of `sys_localtime.exist? && brew_localtime.exist?`.
Also [this comment](https://github.com/orgs/Homebrew/discussions/3617#discussioncomment-3648992) in a discussion on git that ignores the local timezone leads to the same conclusion.

### What did you expect to happen?

I expect the `glibc` formula's post-install step to create the symbolic link to the system tzfile (`/etc/localtime`) if it doesn't exist in the Homebrew directory. This would correctly set the local time zone and avoid issues with other formulae that depend on the timezone.

### Step-by-step reproduction instructions (by running `brew` commands)

Install `glibc` formula with Homebrew:

- `> brew install glibc`

Verify if the symbolic link for the localtime file exists:

- `> ls -l /home/linuxbrew/.linuxbrew/etc/localtime`

**Comment by ZhongRuoyu** [comment]
Indeed this seems like a typo. The review at https://github.com/Homebrew/homebrew-core/pull/70994#discussion_r589374025 also suggests that the condition was `sys_localtime.exist? && !brew_localtime.exist?` initially.
