### ISSUE TITLE
nginx cannot be installed --with-passenger due to openssl version conflict

### ISSUE THREAD

**Issue by nloveladyallen** [Homebrew/homebrew-core#13861]
`nginx` depends on `openssl@1.1`, and `passenger` depends on `openssl`, so `nginx` cannot be installed `--with-passenger`.

**Comment by DomT4** [comment]
The formula has [code to handle](https://github.com/Homebrew/homebrew-core/blob/ecba06dacbae457aca21ac3dce83d27cd7e8c343/Formula/nginx.rb#L32-L38) this situation. I'm not sure how you'd be running into the linkage issue unless your `core` tap was significantly behind the `brew` tap.

What output are you getting from `brew install nginx --with-passenger` and what's your `brew config`?

**Comment by nloveladyallen** [comment]
After uninstalling `nginx`, reinstalling without the `--with-passenger` flag, then uninstalling again, I am able to successfully install with it.

**Comment by MikeMcQuaid** [comment]
Please always fill out the issue template in future. Not filling it out shows a lack of respect to the people who are working on this software and have asked you to do so.
