### ISSUE TITLE
make a package with @{{version}} as the default one

### ISSUE THREAD

**Issue by SuperMarioBean** [Homebrew/homebrew-core#13875]
hi there, I would like make node@6 as the node in my package management to prevent the situation I have to install node(most recently version) when I install or upgrade yarn or babel again and again. is there any method like 'alias' to set node@6 as node to let the brew known this node@6 is node

**Comment by ilovezfs** [comment]
No, that's not something we support. `depends_on "node"` means the latest version of the main `node` formula.
