### ISSUE TITLE
Caddy 0.8.3

### ISSUE THREAD

**Issue by nesl247** [Homebrew/homebrew-core#1387]
Caddy has been upgraded to 0.8.3. 

I attempted to follow the PR steps but ran into an issue when building it.

```
go
build
-o
/usr/local/Cellar/caddy/0.8.3/bin/caddy

# github.com/mholt/caddy/caddy/https
src/github.com/mholt/caddy/caddy/https/client.go:37: cannot use &leUser (type *User) as type acme.User in argument to acme.NewClient:
	*User does not implement acme.User (wrong type for GetPrivateKey method)
		have GetPrivateKey() crypto.PrivateKey
		want GetPrivateKey() *rsa.PrivateKey
src/github.com/mholt/caddy/caddy/https/https.go:407: undefined: acme.RSA2048
src/github.com/mholt/caddy/caddy/https/setup.go:279: undefined: acme.KeyType
```

Hoping it may just be my system though, and whoever normally maintains caddy has this issue solved.

**Comment by rakkesh** [comment]
Looking at the backtrace - `acme` is imported as `github.com/xenolf/lego/acme`, so probably, you need to update the `commit` for `go_resource "github.com/xenolf/lego"` to point at the latest release tagged commit [96a24777ffb3c6a25f6bb0b3a7997969c1fcde4b](https://github.com/xenolf/lego/releases/tag/v0.3.1). 

You might also want to check other `go_resources` and update them as necessary.

**Comment by MikeMcQuaid** [comment]
> whoever normally maintains caddy has this issue solved.

All formulae are maintained by the community so we'll rely on the person who updates this formula to fix this issue. Thanks!

**Comment by vsivsi** [comment]
I just submitted a PR that resolves this issue.
