### ISSUE TITLE
Can't install ncdu with Homebrew on a fresh machine

### ISSUE THREAD

**Issue by revolter** [Homebrew/homebrew-core#13880]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/9a6c80868b46c0314635ac75fd2c0e39
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to install `ncdu` using linuxbrew.

- What happened (include command output)

It crashed with the error `configure: error: required header file not found`.

- What you expected to happen

Install required dependencies then complete the `ncdu` installation successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew install ncdu` on a fresh machine.

I noticed that if I install `neovim` beforehand, `ncdu` installs correctly, so I thought that the spec doesn't list its required dependencies. A related issue can be found [here](https://dev.yorhel.nl/ncdu/bug/97).

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by JCount** [comment]
@revolter As this is pertains to a `Linuxbrew` installation, please file your issue at [Linuxbrew/homebrew-core/issues](https://github.com/Linuxbrew/homebrew-core/issues) as they will best be able to assist you.

**Comment by revolter** [comment]
Aren't the spec files shared between the 2 projects?

**Comment by MikeMcQuaid** [comment]
We don't support Linux here.

**Comment by revolter** [comment]
But the Formula [is here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ncdu.rb)!

**Comment by MikeMcQuaid** [comment]
@revolter Yes but because you use Linuxbrew it's using this: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/ncdu.rb. This is Homebrew, we don't support Linux for Homebrew and Linuxbrew is a completely separate problem run by different people.

**Comment by revolter** [comment]
They are identical, because Linuxbrew's homebrew-core is a fork. Also, I don't think the issue is only on Linux, it just happened for me to discover it o a Linux machine. Having installed a lot of packages in my main macOS system, I can't test this.

**Comment by MikeMcQuaid** [comment]
> They are identical, because Linuxbrew's homebrew-core is a fork.

That's irrelevant to this discussion because we don't support Linux or Linuxbrew here. Additionally, the actual `brew` logic differs on Homebrew and Linuxbrew so the formula being identical still doesn't mean these issues are reproducible on macOS.

> Also, I don't think the issue is only on Linux, it just happened for me to discover it o a Linux machine. Having installed a lot of packages in my main macOS system, I can't test this.

We are only interested in issues you have having on macOS. If you have a macOS system and can reproduce this issue and submit a `brew gist-logs` from there we will look at fixing it. We will not look at fixing issues on Linux because we do not support Linux, do not run Homebrew on Linux and never plan to do so.
