### ISSUE TITLE
when homebrew/core is untapped, brew bump-formula-pr no longer works

### ISSUE THREAD

**Issue by jmhodges** [Homebrew/homebrew-core#139027]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

If a user followed the instructions from brew to speed up their local work, and ran `brew untap homebrew/core`, any otherwise successful `brew bump-formula-pr` will error with:

```
$  brew bump-formula-pr --strict --version=1.21.0 go
Error: This formula is not in a tap!
```

This is fixed by running `brew tap homebrew/core`.

This isn't mentioned in the [CONTRIBUTING](https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md) docs (nor [the troubleshooting docs](https://docs.brew.sh/Troubleshooting) linked from it) and probably should.

### What happened (include all command output)?

$  brew bump-formula-pr --strict --version=1.21.0 go
Error: This formula is not in a tap!

### What did you expect to happen?

Create a formula PR.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew untap homebrew/core
brew bump-formula-pr --strict --version=1.21.0 go
```

**Comment by iMichka** [comment]
Thanks for the report. I think this is not something we will fix with code / changes to brew. Maybe a small comment in https://github.com/Homebrew/homebrew-core/blob/HEAD/CONTRIBUTING.md should do it. Would you be willing to open a pull request for it?
