### ISSUE TITLE
gpgme - GgpmeConfig.cmake needs a patch

### ISSUE THREAD

**Issue by winterz** [Homebrew/homebrew-core#13925]
# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
I'm trying to build kwallet from the KDE frameworks

- What happened (include command output)
kwallet cmake step works fine but when I try to build I run into this error:
make[2]: *** No rule to make target `/usr/local/Cellar/gpgme/1.9.0_1/lib/libgpgme.so', needed by `src/runtime/kwalletd/backend/libkwalletbackend5.5.34.0.dylib'.  Stop.

- What you expected to happen
builds ok

Clearly this is really a bug in gpgme, but we could patch with the following to make it work:

```
$ diff GpgmeppConfig.cmake GpgmeppConfig.cmake.orig
66c66
<   INTERFACE_LINK_LIBRARIES "pthread;/usr/local/Cellar/gpgme/1.9.0_1/lib/libgpgme.dylib;-L/usr/local/opt/libassuan/lib -lassuan -L/usr/local/opt/libgpg-error/lib -lgpg-error"
---
>   INTERFACE_LINK_LIBRARIES "pthread;/usr/local/Cellar/gpgme/1.9.0_1/lib/libgpgme.so;-L/usr/local/opt/libassuan/lib -lassuan -L/usr/local/opt/libgpg-error/lib -lgpg-error"

```

**Comment by ilovezfs** [comment]
@winterz mind testing https://github.com/Homebrew/homebrew-core/pull/13926?

**Comment by ilovezfs** [comment]
Reported https://dev.gnupg.org/T3181

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/13926.

@winterz latest bottle now has the fix.
