### ISSUE TITLE
webp-pixbuf-loader post install broken

### ISSUE THREAD

**Issue by KenjiTakahashi** [Homebrew/homebrew-core#139497]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.4-40-g2cfea60
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2cfea600d4bded2e59c4cb97dcb3b5805f3bc5e2
Last commit: 34 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72286a09e6644cff2b342b43d1e2c3c3e7bbe603
Core tap last commit: 16 hours ago
Core tap branch: master
Core tap JSON: 13 Aug 21:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pygments

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo kenjitakahashi/tap) checkout
```

### What were you trying to do (and why)?

`brew install czkawka` (which depends on `webp-pixbuf-loader`)

### What happened (include all command output)?

Output of `brew postinstall --debug webp-pixbuf-loader` probably makes more sense:

```
/opt/homebrew/Library/Homebrew/brew.rb (Formulary::FormulaAPILoader): loading webp-pixbuf-loader from API
==> Postinstalling webp-pixbuf-loader
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall webp-pixbuf-loader
==> An exception occurred within a child process:
  NoMethodError: undefined method `gdk_so_ver' for #<Formulary::FormulaNamespaceAPIb50585d218335b247caa7d85d72e9df1::GdkPixbuf:0x0000000114e6fb80>

/opt/homebrew/opt/webp-pixbuf-loader/.brew/webp-pixbuf-loader.rb:18:in `gdk_so_ver'
/opt/homebrew/opt/webp-pixbuf-loader/.brew/webp-pixbuf-loader.rb:27:in `module_subdir'
/opt/homebrew/opt/webp-pixbuf-loader/.brew/webp-pixbuf-loader.rb:38:in `post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1254:in `block (2 levels) in run_post_install'
/opt/homebrew/Library/Homebrew/formula.rb:1054:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:1253:in `block in run_post_install'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:499:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:1249:in `run_post_install'
/opt/homebrew/Library/Homebrew/postinstall.rb:24:in `<main>'
```

### What did you expect to happen?

No warnings and working post install.

[BTW: That GH "template" thing is broken, produces garbage formatting. Attempted to somewhat clean it manually.]

**Comment by cho-m** [comment]
Looks like issue with API where only a known subset of info is loaded from formula file, which results in `gdk_so_ver` not being available from:
https://github.com/Homebrew/homebrew-core/blob/3db418f0bcf038a9a47f7b2b45d740012a05038b/Formula/g/gdk-pixbuf.rb#L38-L40

Assuming we want this behavior to be retained, this may need to be handled in `brew`'s API loader.

On formula side, one alternative could be to extract information from `gdk-pixbuf` installation directories.

Main workaround for now would be to rely on non-API install until fixed.

**Comment by Bo98** [comment]
> Looks like issue with API where only a known subset of info is saved/loaded from formula file, which results in gdk_so_ver not being available from:

This code structure is explicitly unsupported. Even outside of API, it is problematic as formulae in Homebrew/core should only use public API and if we start treating arbitrary methods in arbitrary formulae as public API then we'll need to introduce brew's deprecation flow on minor releases to here.

**Comment by cho-m** [comment]
> `gdk_module_ver` can be obtained from querying pkg-config for `gdk_pixbuf_binary_version` (or go direct and change `module_subdir` to use the pkg-config `gdk_pixbuf_moduledir` with `--define-variable=libdir=lib`). Using pkg-config should also catch a theoretical `2.0` bump as the pkg-config file's name also has it, and invoking pkg-config will fail if it were renamed.

One minor impact of using `pkg-config` is that it adds a runtime dependency given the method usage in post_install.

`pkg-config` is lightweight enough to add so not too important. Though, we did kind of reduce runtime usage of `pkg-config` after removing usage of `libpthread-stubs` from `libxcb`.

**Comment by Bo98** [comment]
> > `gdk_module_ver` can be obtained from querying pkg-config for `gdk_pixbuf_binary_version` (or go direct and change `module_subdir` to use the pkg-config `gdk_pixbuf_moduledir` with `--define-variable=libdir=lib`). Using pkg-config should also catch a theoretical `2.0` bump as the pkg-config file's name also has it, and invoking pkg-config will fail if it were renamed.
> 
> One minor impact of using `pkg-config` is that it adds a runtime dependency given the method usage in post_install.
> 
> `pkg-config` is lightweight enough to add so not too important. Though, we did kind of reduce runtime usage of `pkg-config` after removing usage of `libpthread-stubs` from `libxcb`.

We could make a script that is generated in `install` that gets executed in `post_install` potentially.

**Comment by KenjiTakahashi** [comment]
Still broken, mr. bot.

**Comment by JonathanDoughty** [comment]
also happens with `brew install geeqie` which fails with "Postinstalling webp-pixbuf-loader" - one wonders with the webp vulnerability resulting in a storm of people trying to upgrade if this will become a frequently submitted bug.

**Comment by KenjiTakahashi** [comment]
Still no change.

**Comment by KenjiTakahashi** [comment]
.

**Comment by SMillerDev** [comment]
Clearly nobody has time or motivation to fix this, no need to keep it open if nobody will work on it.

**Comment by KenjiTakahashi** [comment]
Well, that's an interesting take. Didn't know issues disappeared when there's no one to work on them 🤷.

**Comment by SMillerDev** [comment]
They don't, they get closed.
