### ISSUE TITLE
`brew uninstall node` leaves npm symlink in `$(brew --prefix)/bin/npm`

### ISSUE THREAD

**Issue by gibfahn** [Homebrew/homebrew-core#139495]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```console
❯ brew gist-logs node
Error: No logs.

❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pycparser
  cffi
  bazelisk

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm still seeing https://github.com/Homebrew/homebrew-core/issues/7929 , but I believe it to actually be a bug.

That issue says:

>This is normal because
>
>```
>/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
>```
>
>and we don't cleanup node_modules on uninstall. If you brew install node subsequently, npm-cli.js is updated.

But it isn't the cleanup of `node_modules` that is the issue, it's the manually-added symlinks at https://github.com/Homebrew/homebrew-core/blob/41cc85b36f9d205e6a45a0cb0776bbdd763711f3/Formula/node.rb#L125-L131

I assume as they are custom symlinks, they need a custom uninstall to remove them.

### What happened (include all command output)?

npm and npx symlinks are left behind when you `brew uninstall node`

### What did you expect to happen?

I expected the `npm` symlink to be removed from `$(brew --prefix)/bin`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
❯ brew install node
❯ brew uninstall node
❯ which node
node not found

❯ which npm
/opt/homebrew/bin/npm
```

**Comment by Bo98** [comment]
We have a fix for this. It will however only fully take effect after the next update of Node (and you upgrade to that version), which probably will only be days away.
