### ISSUE TITLE
Can someone please tell how to install android-platform-tools?

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-core#13982]
Hello. I only need the platform tools. not the full SDK.

I tried installing it but I keep getting an error. Thanks

---------------------------

15:06:02 Sat May 27
mine@mines-Mac-Pro : ~
=> brew install android-platform-tools
Error: No available formula with the name "android-platform-tools" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
16:34:53 Sat May 27
mine@mines-Mac-Pro : ~
=> brew tap caskroom/cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3722, done.
remote: Compressing objects: 100% (3698/3698), done.
Receiving objects:   1% (38/3722), 108.00 KiB | 196.00 KiB/sReceiving objects:   2% (75/3722), 108.00 KiB | 196.00 KiB/sReceiving objects:   3% (112/3722), 108.00 KiB | 196.00 KiB/Receiving objects:   4% (149/3722), 108.00 KiB | 196.00 KiB/Receiving objects:   5% (187/3722), 108.00 KiB | 196.00 KiB/Receiving objects:   6% (224/3722), 108.00 KiB | 196.00 KiB/Receiving objects:   7% (261/3722), 108.00 KiB | 196.00 KiB/Receiving objects:   8% (298/3722), 108.00 KiB | 196.00 KiB/Receiving objects:   9% (335/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  10% (373/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  11% (410/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  12% (447/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  13% (484/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  14% (522/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  15% (559/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  16% (596/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  17% (633/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  18% (670/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  19% (708/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  20% (745/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  21% (782/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  22% (819/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  23% (857/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  24% (894/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  25% (931/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  26% (968/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  26% (980/3722), 108.00 KiB | 196.00 KiB/Receiving objects:  27% (1005/3722), 108.00 KiB | 196.00 KiBReceiving objects:  28% (1043/3722), 412.00 KiB | 391.00 KiBReceiving objects:  29% (1080/3722), 412.00 KiB | 391.00 KiBReceiving objects:  30% (1117/3722), 412.00 KiB | 391.00 KiBReceiving objects:  31% (1154/3722), 412.00 KiB | 391.00 KiBReceiving objects:  32% (1192/3722), 412.00 KiB | 391.00 KiBReceiving objects:  33% (1229/3722), 412.00 KiB | 391.00 KiBReceiving objects:  34% (1266/3722), 412.00 KiB | 391.00 KiBReceiving objects:  35% (1303/3722), 412.00 KiB | 391.00 KiBReceiving objects:  36% (1340/3722), 412.00 KiB | 391.00 KiBReceiving objects:  37% (1378/3722), 412.00 KiB | 391.00 KiBReceiving objects:  38% (1415/3722), 412.00 KiB | 391.00 KiBReceiving objects:  39% (1452/3722), 412.00 KiB | 391.00 KiBReceiving objects:  40% (1489/3722), 412.00 KiB | 391.00 KiBReceiving objects:  41% (1527/3722), 412.00 KiB | 391.00 KiBReceiving objects:  42% (1564/3722), 412.00 KiB | 391.00 KiBReceiving objects:  43% (1601/3722), 412.00 KiB | 391.00 KiBReceiving objects:  44% (1638/3722), 412.00 KiB | 391.00 KiBReceiving objects:  45% (1675/3722), 412.00 KiB | 391.00 KiBReceiving objects:  46% (1713/3722), 628.00 KiB | 402.00 KiBReceiving objects:  47% (1750/3722), 628.00 KiB | 402.00 KiBReceiving objects:  48% (1787/3722), 628.00 KiB | 402.00 KiBReceiving objects:  49% (1824/3722), 628.00 KiB | 402.00 KiBReceiving objects:  50% (1861/3722), 628.00 KiB | 402.00 KiBReceiving objects:  51% (1899/3722), 628.00 KiB | 402.00 KiBReceiving objects:  52% (1936/3722), 628.00 KiB | 402.00 KiBReceiving objects:  53% (1973/3722), 628.00 KiB | 402.00 KiBReceiving objects:  54% (2010/3722), 628.00 KiB | 402.00 KiBReceiving objects:  55% (2048/3722), 628.00 KiB | 402.00 KiBReceiving objects:  56% (2085/3722), 628.00 KiB | 402.00 KiBReceiving objects:  57% (2122/3722), 628.00 KiB | 402.00 KiBReceiving objects:  58% (2159/3722), 628.00 KiB | 402.00 KiBReceiving objects:  59% (2196/3722), 628.00 KiB | 402.00 KiBReceiving objects:  60% (2234/3722), 628.00 KiB | 402.00 KiBReceiving objects:  61% (2271/3722), 628.00 KiB | 402.00 KiBReceiving objects:  62% (2308/3722), 628.00 KiB | 402.00 KiBReceiving objects:  63% (2345/3722), 628.00 KiB | 402.00 KiBReceiving objects:  64% (2383/3722), 628.00 KiB | 402.00 KiBReceiving objects:  64% (2412/3722), 628.00 KiB | 402.00 KiBReceiving objects:  65% (2420/3722), 628.00 KiB | 402.00 KiBReceiving objects:  66% (2457/3722), 628.00 KiB | 402.00 KiBReceiving objects:  67% (2494/3722), 860.00 KiB | 417.00 KiBReceiving objects:  68% (2531/3722), 860.00 KiB | 417.00 KiBReceiving objects:  69% (2569/3722), 860.00 KiB | 417.00 KiBReceiving objects:  70% (2606/3722), 860.00 KiB | 417.00 KiBReceiving objects:  71% (2643/3722), 860.00 KiB | 417.00 KiBReceiving objects:  72% (2680/3722), 860.00 KiB | 417.00 KiBReceiving objects:  73% (2718/3722), 860.00 KiB | 417.00 KiBReceiving objects:  74% (2755/3722), 860.00 KiB | 417.00 KiBReceiving objects:  75% (2792/3722), 860.00 KiB | 417.00 KiBReceiving objects:  76% (2829/3722), 860.00 KiB | 417.00 KiBReceiving objects:  77% (2866/3722), 860.00 KiB | 417.00 KiBReceiving objects:  78% (2904/3722), 860.00 KiB | 417.00 KiBReceiving objects:  79% (2941/3722), 860.00 KiB | 417.00 KiBReceiving objects:  80% (2978/3722), 860.00 KiB | 417.00 KiBReceiving objects:  81% (3015/3722), 860.00 KiB | 417.00 KiBReceiving objects:  82% (3053/3722), 860.00 KiB | 417.00 KiBReceiving objects:  83% (3090/3722), 860.00 KiB | 417.00 KiBReceiving objects:  84% (3127/3722), 860.00 KiB | 417.00 KiBReceiving objects:  85% (3164/3722), 860.00 KiB | 417.00 KiBReceiving objects:  86% (3201/3722), 860.00 KiB | 417.00 KiBReceiving objects:  87% (3239/3722), 860.00 KiB | 417.00 KiBReceiving objects:  88% (3276/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  89% (3313/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  90% (3350/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  91% (3388/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  92% (3425/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  93% (3462/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  94% (3499/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  95% (3536/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  96% (3574/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  97% (3611/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  98% (3648/3722), 1.07 MiB | 425.00 KiB/sReceiving objects:  99% (3685/3722), 1.07 MiB | 425.00 KiB/sremote: Total 3722 (delta 39), reused 609 (delta 20), pack-reused 0
Receiving objects: 100% (3722/3722), 1.07 MiB | 425.00 KiB/sReceiving objects: 100% (3722/3722), 1.26 MiB | 425.00 KiB/s, done.
Resolving deltas: 100% (39/39), done.
Checking out files: 100% (3707/3707), done.
Tapped 0 formulae (3,731 files, 3.9MB)
16:35:23 Sat May 27
mine@mines-Mac-Pro : ~
=> brew install android-platform-tools
Error: No available formula with the name "android-platform-tools" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
16:35:35 Sat May 27
mine@mines-Mac-Pro : ~
=> brew tap caskroom/cask
16:35:53 Sat May 27
mine@mines-Mac-Pro : ~
=> brew install android-platform-tools
Error: No available formula with the name "android-platform-tools" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
16:36:05 Sat May 27
mine@mines-Mac-Pro : ~
=>

**Comment by ilovezfs** [comment]
```
brew cask install android-platform-tools
```
