### ISSUE TITLE
Error installing virtualbox vagrant

### ISSUE THREAD

**Issue by RalphWanders** [Homebrew/homebrew-core#140163]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
ralph.wanders@NLCT-RalphWanders ~ % brew config
HOMEBREW_VERSION: 4.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 4 days ago
Core tap JSON: 22 Aug 14:02 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
ralph.wanders@NLCT-RalphWanders ~ % 


ralph.wanders@NLCT-RalphWanders ~ % brew doctor
Your system is ready to brew.
ralph.wanders@NLCT-RalphWanders ~ %
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install virtualbox vagrant on my Mac, I ran the command 'brew install virtualbox vagrant'.

I need this to create a virtual environment on my Mac for test purpose

Attached is a screenshot of the error message from my console/ terminal app on Mac.

<img width="902" alt="Screenshot 2023-08-22 at 4 21 49 PM" src="https://github.com/Homebrew/homebrew-core/assets/142911360/2353f8f6-953c-491e-8646-2261864d1102">

### What happened (include all command output)?

Installation was cut of. See message in screenshot previously attached

### What did you expect to happen?

Succesful installation of the vagrant virtualbox on my Mac

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install virtualbox vagrant
```

**Comment by gromgit** [comment]
Please copy-and-paste text output _as text_, not screenshots. Screenshots don't offer any advantage for pure text output, and in fact have a number of disadvantages, including:
* being a pain to read on mobile devices
* impossible to copy text from

As for the "formulae require at least a URL" error, that's almost certainly caused by one of your local taps, not Homebrew core. What's the output of `brew readall --eval-all`?

**Comment by RalphWanders** [comment]
Hi, I solved the issue by using the following commands: brew tap homebrew-cask-versions, brew install virtualbox-beta and brew install --cask vagrant instead of the single command brew install virtualbox vagrant.

**Comment by gromgit** [comment]
OK, but I think it's important for everyone reading this thread to understand _why_ it worked:
> brew tap homebrew-cask-versions, brew install virtualbox-beta

This allows you to install a Virtualbox v7.0 _beta_ binary that supports M1 Macs (previous versions are Intel-only).

Also note that the tap command should be `brew tap homebrew/cask-versions`, not what you typed.

> brew install --cask vagrant

This installs upstream's Vagrant _cask_ rather than Homebrew's formula, and since you haven't actually addressed the underlying issue, you'll likely see the same error on the next formula you install.

**Comment by RalphWanders** [comment]
See my comments inline:

OK, but I think it's important for everyone reading this thread to understand why it worked:

brew tap homebrew-cask-versions, brew install virtualbox-beta

This allows you to install a Virtualbox v7.0 beta binary that supports M1 Macs (previous versions are Intel-only). [RW] Correct

Also note that the tap command should be brew tap homebrew/cask-versions, not what you typed. [RW] Correct, made a fault copying the wrong command.

brew install --cask vagrant

This installs upstream's Vagrant cask rather than Homebrew's formula, and since you haven't actually addressed the underlying issue, you'll likely see the same error on the next formula you install. [RW] Makes sense, but as I am on a tight time schedule it fixed my problem for now

In order for you to be able to solve the underlying issue, hereby the initial error message in txt format:

ralph.wanders@NLCT-RalphWanders ~ % brew install virtualbox vagrant
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################### 100.0%
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:306:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:237:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:484:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:484:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:761:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:649:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:645:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:645:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:318:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:167:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
ralph.wanders@NLCT-RalphWanders ~ % 

Hope this helps to solve the underlying error. 

Thanks for your support

**Comment by gromgit** [comment]
You missed the last part of my first response:

> What's the output of `brew readall --eval-all`?
