### ISSUE TITLE
Error executing ./script_name in CLI

### ISSUE THREAD

**Issue by st-fresh** [Homebrew/homebrew-core#14022]
**macbook Pro macOS 10.x**

`brew doctor` prints the following blob for maintainers at this time . . . 

```
Warning: "config" scripts exist outside your system or Homebrew directories. './configure' scripts often look for *-config scripts to determine if software packages are installed, and what additional flags to use when compiling and linking.

Having additional scripts in your path can confuse software installed via Homebrew if the config script overrides a system or Homebrew provided script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a brewed Python. In particular, Pythons installed to /Library can interfere with other software installs.
```

**// What I'm trying to do . . .**
Execute python module/script/program file in CLI using `./script_name`
The content of File script_name is currently . . .
`#! /Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
`print('The Bright Side ' + 'of Life...')`

**// CLI output when executing** `./script_name` **is . . .**
`-bash: ./script_name: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3^M: bad interpreter: No such file or directory`

**// Expected . . .**
`The Bright Side of Life...`

**// Other things happening . . .**
`which env` output is `/usr/bin/env`
`which python` output is `/usr/bin/python`
`which python3` output is `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
`/usr/bin/env python3` starts `>>>` python prompt
changing File to `#! /usr/bin/env python3` and executing `./script_name` in CLI output is `env: python3\r: No such file or directory`

**I am unsure how to configure my machine and `!# /path/` so that I can execute `./script_name` in CLI**

**Comment by dunn** [comment]
How did you install Python 3?

**Comment by st-fresh** [comment]
[ How did you install Python 3? ]
**// Installed python3 in CLI by executing`brew install python3`**

**// Notes output to CLI after successful install . . .**
`=> Pouring python3-3.6.1.sierra.bottle.1.tar.gz`
`==> /usr/local/Cellar/python3/3.6.1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scrip`
`==> /usr/local/Cellar/python3/3.6.1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scrip`
`==> /usr/local/Cellar/python3/3.6.1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scrip`
`==> Caveats`
`Pip, setuptools, and wheel have been installed. To update them`
`  pip3 install --upgrade pip setuptools wheel`

`You can install Python packages with`
`  pip3 install <package>`

`They will install into the site-package directory`
`  /usr/local/lib/python3.6/site-packages`

`See: http://docs.brew.sh/Homebrew-and-Python.html`
`==> Summary`
`🍺  /usr/local/Cellar/python3/3.6.1: 3,600 files, 55.8MB`

`Using Python 2.x or 3.x for dev: https://wiki.python.org/moin/Python2orPython3`

**Comment by dunn** [comment]
Well it looks like you've got a separate installation at `/Library/Frameworks/Python.framework/Versions/3.6` that is causing problems, so you probably want to remove it if you don't need it.

What does `brew config` say?

**Comment by st-fresh** [comment]
I found `Library/Frameworks/Python.framework/Versions/3.6` in my .bash_profile . . . 
`PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"`
`export PATH`
. . . I removed it

`which python3` output is now `/usr/local/bin/python3`

`brew config` output is a long list including . . .
`Python: /usr/bin/python`

**Comment by dunn** [comment]
Now that you've got the correct python3 in your PATH, does the test script work?

**Comment by ilovezfs** [comment]
@st-fresh ping on this.
