### ISSUE TITLE
proctools's pgrep -P option ignored

### ISSUE THREAD

**Issue by lifepillar** [Homebrew/homebrew-core#14020]
When `pgrep -P $pid` is run, the output is the list of *all* process IDs (the expected output would be `$pid`'s children's IDs: compare with `/usr/bin/pgrep -P $pid`).

The reason I'm reporting here and not upstream is that Homebrew applies some patches and I have not been able to build proctools without them. Feel free to close this if you believe that the patches are not the cause of `pgrep`'s bug.

- [X] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by ilovezfs** [comment]
I don't think I see anything in the patches that would be causing this. If you need to build your own pgrep for some reason, you could try https://opensource.apple.com/tarballs/adv_cmds/adv_cmds-168.tar.gz instead.
