### ISSUE TITLE
Yarn should include an option `--without-node` to skip installing NodeJS

### ISSUE THREAD

**Issue by ntwb** [Homebrew/homebrew-core#14026]
Ref: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb

Currently there is no option `--without-node` when installing Yarn.

The reason I'm requesting this as per the discussion in https://github.com/yarnpkg/yarn/issues/3255 in that when using [nvm](https://github.com/creationix/nvm) you want to use the nvm installed version of NodeJS, not a system-wide version installed by Homebrew.

To update the Yarn docs for the recommendations when using nvm, first Yarn when installed with Homebrew will need this `--without-node` option.

_p.s. I read the issue template and as this issue is a feature request for an existing package that currently works as expected I removed the template info_

**Comment by dunn** [comment]
Since Yarn requires that a Node installation exists, we would need a special `:node` dependency that wouldn't mandate a Homebrew installation of Node.  There's been some work on that in the past, but it's never been completed: https://github.com/Homebrew/brew/pull/1408

**Comment by ilovezfs** [comment]
You can use `--ignore-dependencies`
