### ISSUE TITLE
build script for GNU plotutils-2.6 is not including X11 support

### ISSUE THREAD

**Issue by unixwizard107** [Homebrew/homebrew-core#140305]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs  plotutils
Error: No logs.

% echo $PATH
/opt/homebrew/opt/lsof/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/gnu-getopt/bin:/Users/ctcole/.local/bin:/Users/ctcole/src/simh/BIN:/usr/local/sbin:/usr/local/bin:/opt/local/bin:/opt/homebrew/opt/lsof/bin:/opt/homebrew/opt/coreutils/libexec/gnubin:/opt/homebrew/opt/gnu-getopt/bin:/Users/ctcole/.local/bin:/Users/ctcole/src/simh/BIN:/usr/local/sbin:/usr/local/bin:/opt/local/bin:/Volumes/usrcs/clemc/perl5/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/opt/fzf/bin:/usr/texbin:/Volumes/usrcs/clemc/bin:/Volumes/usrcs/clemc/go/bin:/opt/homebrew/opt/go/bin:/usr/texbin:/Volumes/usrcs/clemc/bin:/Volumes/usrcs/clemc/go/bin:/opt/homebrew/opt/go/bin

% which gcc-13

 % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libpas2jslib.dylib
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I would like libplot to not return this error - as I believe it has not been properly configured when it was built: 

> libplot: ignoring request to create plotter of unknown type
> plot: error: the plot device could not be created

Reproduce with: **plot -T X** 
The issue is for some reason the **plotutils.rb** is set to be -**-without-x**
which I suspect was originally done because macOS does not natively supply X11.  But of course XQuartz is available and Brew used it for the support.

The rb script for the linux port does not have that switch set.

I believe that if you use: **CC=${HOMEBREW_PREFIX}/bin/gcc-13 CPPFLAGS=-I${HOMEBREW_PREFIX}/include LIBS=-L${HOMEBREW_PREFIX}/lib ./configure --disable-debug --disable-dependency-tracking --disable-silent-rules   --enable-libplotter**

The **configure** script can drop **-without-x** and will correctly find the X11 support and thus properly build the support into the subsystem.

### What happened (include all command output)?

% plot -T X 
libplot: ignoring request to create plotter of unknown type
plot: error: the plot device could not be created

### What did you expect to happen?

plot should have openned an X11 window and then started ploting.opened

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% plot -T X
```

**Comment by SMillerDev** [comment]
Please submit a pull request instead of an issue when requesting features.

**Comment by unixwizard107** [comment]
Sean,

I'm not the maintainer (and for that matter, nor have a complete Gnu
setup on my Mac).  *But I also know this is an old bug.*   I personally ran
into it 11 years ago on MacPorts which had this same issue - which is why I
recognized it.  Today, I was moving an old piece of code graphics code to
demonstrate to a student [from a much older machine] to my new ARM based
Mac when I recompiled it.  My code (which uses Gnu's libplot) uses the X11
support in it. I have brew's X11 support installed as well as some of
Brew's Gnu support.

From my experience, I know that that bug can be fixed if Gnu's plotlib
subsystem is properly configured (MacPorts was then fixed and has had it
working properly long before Brew existed, and I was running it on the old
Mac that I pulled this code from) ... plus ... given/if I am to believe
the Ruby script from Brew (and I'm not 100% well versed in same so I could
be in error there), the Linux Brew version seems to be correctly configured
as it has a dependency on libxaw and does not turn on the --without-x when
its build (again I believe the original sin was because the default support
for X11 is a part of the core OS for Linux most *BSD's - but Apple has X11
as an external option via XQuartz).

So, I am reporting the issue and asking the maintainer to change his/her
configuration for the Mac and find the proper one so it works as
documented.  Simple the problem is on a Mac, the macOS Brew supplied
version of GNU plotlib-2.6 subsystem is returning an error when it's man
pages, and all of its docs that Brew has installed say that -T X or -T
Xdrawable will work (i.e. the first parameter to libplot's pl_newpl_r routine
where type='X" or type="Xdrawable, will return the error I reported).  As
my report shows in my repeater example, I have demonstrated that the gnu
libplot routine (which is doing all the work under the covers) is currently
returning an error (again - I believe the error is because the entire
subsystem when it was built was not configured correctly).

That said, I have >>suggested<< a solution that I >>think<< should fix the
problem to save the maintainer time.  But they will need to verify.  If I'm
right, it should be changed in the build scripts, the fixed pushed out, and
everyone should be happy.

So I don't think it is far-fetched for the bug as it currently exists to be
reported and ask the maintainer to correct the issue.

Thank you for your consideration,
ᐧ
ᐧ

**Comment by SMillerDev** [comment]
> Sean, I'm not the maintainer

You are part of the community and the community is the maintainer of all Homebrew formulae. No specific responsibilities exist.

> (and for that matter, nor have a complete Gnu setup on my Mac).

These days all you need for a pull request is a GitHub account and there edit button in the web ui.

>  *But I also know this is an old bug.* 

It's not a bug when a feature you want isn't enabled.

> the Linux Brew version seems to be correctly configured as it has a dependency on libxaw and does not turn on the --without-x when its build

Could very well be
> but Apple has X11 as an external option via XQuartz

Homebrew core formula only ever depend on other Homebrew core formula. But we have some X11 formula nowadays.

> is returning an error when it's man pages, and all of its docs that Brew has installed say that -T X or -T Xdrawable will work

Sounds like the manpages are incorrectly assuming everyone will always do a full build. You should report that upstream since clearly that's incorrect.

> That said, I have >>suggested<< a solution that I >>think<< should fix the problem to save the maintainer time.

If you suggest it as a pull request, CI will run on it and we'll see if it even builds.
