### ISSUE TITLE
MPD formulae build binary without Wavpack decoder limiting player support of Wavpack files.

### ISSUE THREAD

**Issue by t0maz** [Homebrew/homebrew-core#140343]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.6-16-g3c8b494
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3c8b4949baefb1f8166749ff1a3f0665afadedda
Last commit: 24 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 082895ddc90efe5df50d23d4ae96528da6e5e4b3
Core tap last commit: 4 days ago
Core tap branch: master
Core tap JSON: 23 Aug 22:39 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.TSE7AsGBPP/org.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm observing the issue of MPD not able to play DSD content packed in Wavpack files as DSD on the DSD-capable DACs.
It's because MPD binary uses FFmpeg instead of fully featured Wavpack to decode Wavpack content (wv files).

### What happened (include all command output)?

MPD was built without linking libwavpack hence the MPD "Wavpack" decoder plugin was not built.
This limits MPD abilities when playing Wavpack files.
More details can be found in the MPD ticket:
https://github.com/MusicPlayerDaemon/MPD/issues/1860

### What did you expect to happen?

MPD build with "Wavpack" enabled, which means that it should be dependent on "wavpack" formulae and should link libwavpack to enable all Wavpack-related features, eg.: playing DSD content in Wavpack files as DSD without conversion to PCM. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mpd
/usr/local/Cellar/mpd-<VERSION>/bin/mpd --version

the output doesn't include "[wavpack] wv" in the "Decoders plugins:" list.
```

**Comment by SMillerDev** [comment]
How is "not adding a dependency" a bug?

**Comment by t0maz** [comment]
Thank you for your reply. I'll try to put it in other words in an attempt to clarify what's the issue.

The bug is that MPD is not able to play DSD Wavpack to DSD capable DAC without unnecessary conversion (loss of audio quality) because brew formulae MPD binary can't handle it and there is no way to fix it other than resigning from using MPD from the brew repo and building it from sources with "Wavpack" feature enabled.

Wavpack is a very popular encoder/decoder and I see no reason why its support is disabled in brew formulae.
I hope the "Wavpack" feature can be enabled for MPD formulae to enable all Wavpack features.
I'd very much prefer to use the brew package instead of building it myself and currently can do this due to a missing feature.

**Comment by SMillerDev** [comment]
That's not a bug though, that's a feature request and Homebrew requires feature requests to be filed as pull requests.

> Wavpack is a very popular encoder/decoder and I see no reason why its support is disabled in brew formulae.

Because nobody put in the work enable it, but you can help: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
