### ISSUE TITLE
brew install Azure/kubelogin/kubelogin fails with "kubelogin: SHA256 mismatch" error

### ISSUE THREAD

**Issue by sjagannathan22** [Homebrew/homebrew-core#140312]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell

% brew gist-logs azure/kubelogin/kubelogin
Error: No logs.

% brew config
brew config
HOMEBREW_VERSION: 4.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 6 days ago
Core tap JSON: 23 Aug 23:15 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1


% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am trying to install azure/kubelogin/kubelogin plugin using homebrew to to connect to AAD enabled cluster.

### What happened (include all command output)?

% brew install Azure/kubelogin/kubelogin
==> Fetching azure/kubelogin/kubelogin
==> Downloading https://github.com/Azure/kubelogin/releases/download/v0.0.30/kubelogin-darwin-amd64.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/250050091/ab72cbb9-dce7-471b-ad9e-2290df257f8
                            -=O=-                                                    #          #         #        #                          
Error: kubelogin: SHA256 mismatch
Expected: f986909e6216610614e50396a8ff26635bd513d6d8929db00af86681e1a0a454
  Actual: 3a806f4b640620bffc3c6189dd443b4ca233c176d036f63f40a0063bcb34ef72
    File: /Users/saritha.jagannathan/Library/Caches/Homebrew/downloads/5d0be18bb56600fcbfabad22dcb2c0f5e94803e5a792245f7ff46169f2dab105--kubelogin-darwin-amd64.zip
To retry an incomplete download, remove the file above.

### What did you expect to happen?

I expect the installation to be successful without any errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew update
2. brew install azure/kubelogin/kubelogin
```

**Comment by ZhongRuoyu** [comment]
This issue should be reported to https://github.com/Azure/homebrew-kubelogin.
