### ISSUE TITLE
Formula soci lacks an option to specify which ODBC lib to use

### ISSUE THREAD

**Issue by dcatteeu** [Homebrew/homebrew-core#14048]
The [soci library](http://soci.sourceforge.net/) allows you to specify which ODBC library to link against: unixODBC or iODBC. Homebrew doesn't allow you to do that, so you're always stuck with iODBC.

Proposed solution:
* add options: --with-unixodbc and --with-iodbc
* pass extra arguments to cmake call referring to homebrew installed ODBC lib depending on the option: 
     - with-unixodbc: -DODBC_INCLUDE_DIR="/usr/local/opt/unixodbc/include" -DODBC_LIBRARY:PATH="/usr/local/opt/unixodbc/lib/libodbc.dylib"
     - with-iodbc: -DODBC_INCLUDE_DIR="/usr/local/opt/iodbc/include" -DODBC_LIBRARY:PATH="/usr/local/opt/iodbc/lib/libodbc.dylib"
     - with-odbc: none, so that it works as before, this means soci decides and links against the system installed iODBC.
* install unixodbc or iODBC dependency as required

For more information: http://soci.sourceforge.net/doc/3.2/installation.html

**Comment by ilovezfs** [comment]
Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

**Comment by dcatteeu** [comment]
Ok, thank you for the pointer. I'll make an attempt.

Below is what I have up to now. 

How to figure out where Homebrew installed a given dependency, unixodbc or iodbc in this case? 

I know there is `brew info <formula>`, but I guess there must be a better way than calling `brew info` and parsing its output.

Any hints or pointers are more than welcome. Thank you.

````
class Soci < Formula
  desc "Database access library for C++"
  homepage "https://soci.sourceforge.io/"
  url "https://download.sourceforge.net/project/soci/soci/soci-3.2.3/soci-3.2.3.zip"
  sha256 "ab0f82873b0c5620e0e8eb2ff89abad6517571fd63bae4bdcac64dd767ac9a05"

  bottle do
    sha256 "61ac3ada591371a743198251fa35d70a18cc6018d23e4a36e3ec45aa6ec99db2" => :sierra
    sha256 "4b8d8acc29c2ed8e826be84c9dc777d947033396336885440fb823530460b470" => :el_capitan
    sha256 "b802ee253ceb25ebfd2b5a90ef4dc8b229a90c7b1cae1a33533c9bd2ff9e7d50" => :yosemite
  end

  option "with-oracle", "Enable Oracle support."
  option "with-boost", "Enable boost support."
  option "with-mysql", "Enable MySQL support."
  option "with-odbc", "Enable ODBC support."
  option "with-unixodbc", "Enable ODBC support using Homebrew's unixODBC."
  option "with-iodbc", "Enable ODBC support using Homebrew's iODBC."
  option "with-pg", "Enable PostgreSQL support."

  ## TODO: Test that only one of with-*odbc is given. Warn user if he
  ## provided multiple
  
  depends_on "cmake" => :build
  depends_on "boost" => [:build, :optional]
  depends_on "sqlite" if MacOS.version <= :snow_leopard
  depends_on "unixodbc" if build.with?("unixodbc")
  depends_on "iodbc" if build.with?("iodbc")

  def translate(a)
    a == "pg" ? "postgresql" : a
  end

  fails_with :clang do
    build 421
    cause "Template oddities"
  end

  def install
    args = std_cmake_args + %w[.. -DWITH_SQLITE3:BOOL=ON]

    %w[boost mysql oracle odbc pg].each do |a|
      bool = build.with?(a) ? "ON" : "OFF"
      args << "-DWITH_#{translate(a).upcase}:BOOL=#{bool}"
    end

    odbc_dependency = build.with?("unixodbc") ? "unixodbc"
                      : build.with?("iodbc") ? "iodbc"
                      : ""

    if odbc_dependency != ""
      ## TODO: Ask Brew where the given library is in the Cellar. Or
      ## should I refer to the installation directory (like
      ## /usr/local/opt/...)
      dir = ""
      incl_dir = "-DODBC_INCLUDE_DIR=\"" + dir + "/include/\""
      odbc_lib = "-DODBC_LIBRARY:PATH=\"" + dir + "/lib/libodbc.a\""
      args << incl_dir
      args << odbc_lib
      puts args
    end

    mkdir "build" do
      system "cmake", *args
      system "make", "install"
    end

  end
end
````
