### ISSUE TITLE
perl locale problem

### ISSUE THREAD

**Issue by gamaralf** [Homebrew/homebrew-core#140500]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 4.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3cd72905ce3d36a84994cc6c6b9ebbdafff4e922
Last commit: 7 days ago
Core tap JSON: 25 Aug 18:41 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_BROWSER: firefox
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: jmacs
HOMEBREW_MAKE_JOBS: 6
http_proxy: http://127.0.0.1:3128
https_proxy: http://127.0.0.1:3128
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /bin/curl
Kernel: Linux 5.15.0-78-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.6 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was running a perl program.

### What happened (include all command output)?

Everytime I run perl, I receive the follow warning:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "pt_BR:pt:en",
	LC_ALL = (unset),
	LANG = "pt_BR.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

I have observed this in 2 different computers running different Ubuntu versions (19.04 and 20.04).

### What did you expect to happen?

I expected no annoying verbose warning every time I run a Perl program.

There is a "fix" to the problem: set the variable LC_ALL to "C" before running a perl, for example:
`LC_ALL=C perl --version`

The perl package that comes with Ubuntu runs fine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Install Perl:
brew install perl

Run any Perl program, or even run:
perl --version

And the warning about the locale problem will be shown.
```

**Comment by gromgit** [comment]
What's the output of `locale -a | grep pt_BR` on your system?

**Comment by gamaralf** [comment]
> What's the output of `locale -a | grep pt_BR` on your system?
```
$ locale -a | grep pt_BR
pt_BR.utf8

```

**Comment by cho-m** [comment]
Can you show `brew info perl` to check installation method? And maybe also `brew info glibc` to see if it is using brewed `glibc`?

Homebrew should automatically install its own `glibc` in your case as bottle was built on Ubuntu 22.04 (glibc 2.35) while your system is:
```
OS: Ubuntu 20.04.6 LTS (focal)
Host glibc: 2.31
```

---

Assuming you are using poured bottle with Homebrew's `glibc`, then you would probably hit issue mentioned in #110812 where postinstall doesn't work correctly.

Homebrew cleans `LANGUAGE`/`LC_*` environment variables before they can be used to generate locale data.

---

You can also retry previous command using brew's `locale` (e.g. `$(brew --prefix glibc)/bin/locale`) rather than Ubuntu's system `locale` (e.g. `/usr/bin/locale`)

**Comment by gamaralf** [comment]
```
$ $(brew --prefix glibc)/bin/locale | grep pt_BR
/home/linuxbrew/.linuxbrew/opt/glibc/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/home/linuxbrew/.linuxbrew/opt/glibc/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/home/linuxbrew/.linuxbrew/opt/glibc/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC="pt_BR.UTF-8"
LC_TIME="pt_BR.UTF-8"
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY="pt_BR.UTF-8"
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER="pt_BR.UTF-8"
LC_NAME="pt_BR.UTF-8"
LC_ADDRESS="pt_BR.UTF-8"
LC_TELEPHONE="pt_BR.UTF-8"
LC_MEASUREMENT="pt_BR.UTF-8"
LC_IDENTIFICATION="pt_BR.UTF-8"
```
----
```
$ brew info perl
==> perl: stable 5.36.1 (bottled), HEAD
Highly capable, feature-rich programming language
https://www.perl.org/
/home/linuxbrew/.linuxbrew/Cellar/perl/5.36.1 (2,495 files, 74.8MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-08-26 at 17:01:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/perl.rb
License: Artistic-1.0-Perl or GPL-1.0-or-later
==> Dependencies
Required: berkeley-db ✔, gdbm ✔, expat ✔, libxcrypt ✔, gcc ✔, glibc ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
And add the following to your shell profile e.g. ~/.profile or ~/.zshrc
  eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
==> Analytics
install: 14,437 (30 days), 50,015 (90 days), 105,520 (365 days)
install-on-request: 5,434 (30 days), 21,295 (90 days), 33,166 (365 days)
build-error: 35 (30 days)

```

**Comment by cho-m** [comment]
You need to use `-a` arg to get locales installed on your system.

Anyway, the fact that `perl` is poured from bottle means you are using Homebrew's `glibc` and hitting #110812.

The easiest workaround is to manually run the postinstall command for language you want, e.g. https://github.com/orgs/Homebrew/discussions/3682#discussioncomment-3829952 but making sure to use Homebrew's copy of commands (i.e. not system `/usr/bin/{localedef,locale}`).

**Comment by gamaralf** [comment]
Now including the `-a` option

```
$ $(brew --prefix glibc)/bin/locale -a | grep pt_BR
/home/linuxbrew/.linuxbrew/opt/glibc/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/home/linuxbrew/.linuxbrew/opt/glibc/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/home/linuxbrew/.linuxbrew/opt/glibc/bin/locale: Cannot set LC_COLLATE to default locale: No such file or directory
```

**Comment by gamaralf** [comment]
> The easiest workaround is to manually run the postinstall command for language you want, e.g. https://github.com/orgs/Homebrew/discussions/3682#discussioncomment-3829952 but making sure to use Homebrew's copy of commands (i.e. not system `/usr/bin/{localedef,locale}`).

After checking the link above, I found out that locale is present in another directory,  `/home/linuxbrew/.linuxbrew/bin/` .

And that version's output is different:
```
$ /home/linuxbrew/.linuxbrew/bin/locale -a
/home/linuxbrew/.linuxbrew/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/home/linuxbrew/.linuxbrew/bin/locale: Cannot set LC_MESSAGES to default locale: No such file or directory
/home/linuxbrew/.linuxbrew/bin/locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX
en_US.utf8
```

Note that, apart from the STDERR messages starting with "Cannot set ...", it reports 3 available locales "C", "POSIX" and "en_US.utf8".

**Comment by gamaralf** [comment]
@cho-m , following the discussion link you mentioned, I was able to fix the problem.

I ran:
```
$ /home/linuxbrew/.linuxbrew/bin/localedef -v -i pt_BR -f UTF-8 pt_BR.UTF-8
# (...)
# some long output with warnings and messages with failure (sic)
# (...)
```

Now, I do not receive the error messages anymore when I run perl. And locale says the Brazilian Portuguese locale (pt_BR) is installed:
```
$ which perl
/home/linuxbrew/.linuxbrew/bin/perl

$ perl -v

This is perl 5, version 36, subversion 1 (v5.36.1) built for x86_64-linux-thread-multi

Copyright 1987-2023, Larry Wall
# (...)

$ /home/linuxbrew/.linuxbrew/bin/locale -a
C
en_US.utf8
POSIX
pt_BR.utf8
```

Thanks!
