### ISSUE TITLE
curl: (56) SSLRead() return error -36 Error: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by battegoal** [Homebrew/homebrew-core#14066]
==> Upgrading 1 outdated package, with result:
gradle 3.5
==> Upgrading gradle 
==> Using the sandbox
==> Downloading https://services.gradle.org/distributions/gradle-3.5-all.zip
==> Downloading from https://downloads.gradle.org/distributions/gradle-3.5-all.zip
#####################################                                     52.5%

curl: (56) SSLRead() return error -36
Error: parent directory is world writable but not sticky
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `ensure in mktmpdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:94:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:658:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:312:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:137:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `block in upgrade'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:90:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:90:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.
