### ISSUE TITLE
libgphoto2 error 

### ISSUE THREAD

**Issue by mgracer48** [Homebrew/homebrew-core#1406]
```
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.1
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5
==> make install
Last 15 lines from /Users/mgracer48/Library/Logs/Homebrew/libgphoto2/02.make:
  "_ax206_compress_jpeg", referenced from:
      _ax203_write_file in ax203_la-ax203.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ax203.la] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: ( cd ".libs" && rm -f "barbie.la" && ln -s "../barbie.la" "barbie.la" )
libtool: link: sed -e 's|^|_|' < ../camlibs/camlib.sym > .libs/canon-symbols.expsym
libtool: link: clang  -o .libs/canon.so -bundle  canon/.libs/canon_la-canon.o canon/.libs/canon_la-library.o canon/.libs/canon_la-serial.o canon/.libs/canon_la-usb.o canon/.libs/canon_la-crc.o canon/.libs/canon_la-util.o   ../libgphoto2/.libs/libgphoto2.dylib /private/tmp/libgphoto2-20160525-34563-c8cbe7/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lm ../libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lltdl -lpthread  -g -O2 -Wl,-dylib_file -Wl,/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port.12.dylib:/private/tmp/libgphoto2-20160525-34563-c8cbe7/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib   -Wl,-exported_symbols_list,.libs/canon-symbols.expsym
libtool: link: sed -e 's|^|_|' < ../camlibs/camlib.sym > .libs/casio_qv-symbols.expsym
libtool: link: clang  -o .libs/casio_qv.so -bundle  casio/.libs/casio-qv.o casio/.libs/casio-qv-commands.o casio/.libs/camtojpeg.o casio/.libs/ycctoppm.o   ../libgphoto2/.libs/libgphoto2.dylib /private/tmp/libgphoto2-20160525-34563-c8cbe7/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lm ../libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lltdl -lpthread  -g -O2 -Wl,-dylib_file -Wl,/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port.12.dylib:/private/tmp/libgphoto2-20160525-34563-c8cbe7/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib   -Wl,-exported_symbols_list,.libs/casio_qv-symbols.expsym
libtool: link: ( cd ".libs" && rm -f "canon.la" && ln -s "../canon.la" "canon.la" )
libtool: link: ( cd ".libs" && rm -f "casio_qv.la" && ln -s "../casio_qv.la" "casio_qv.la" )
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by mgracer48** [comment]
brew doctor : 
MacBook-Pro:~ mgracer48$  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

Warning: gettext files detected at a system prefix.
These files can cause compilation and link failures, especially if they
are compiled with improper architectures. Consider removing these files:
    /usr/local/lib/libintl.dylib
    /usr/local/lib/libintl.dylib

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libatk-1.0.0.2209.1.dylib
    /usr/local/lib/libgdk-x11-2.0.0.1200.0.dylib
    /usr/local/lib/libgdk_pixbuf-2.0.0.1200.0.dylib
    /usr/local/lib/libgdk_pixbuf_xlib-2.0.0.1200.0.dylib
    /usr/local/lib/libgio-2.0.0.0.0.dylib
    /usr/local/lib/libGLEW.1.5.4.dylib
    /usr/local/lib/libglib-2.0.0.1600.0.dylib
    /usr/local/lib/libgmodule-2.0.0.1600.0.dylib
    /usr/local/lib/libgobject-2.0.0.1600.0.dylib
    /usr/local/lib/libgthread-2.0.0.1600.0.dylib
    /usr/local/lib/libgtk-x11-2.0.0.1200.0.dylib
    /usr/local/lib/libintl.8.0.2.dylib
    /usr/local/lib/libirecovery.2.dylib
    /usr/local/lib/libjpeg.62.dylib
    /usr/local/lib/libpango-1.0.0.2100.0.dylib
    /usr/local/lib/libpangocairo-1.0.0.2100.0.dylib
    /usr/local/lib/libpangoft2-1.0.0.2100.0.dylib
    /usr/local/lib/libpangox-1.0.0.2100.0.dylib
    /usr/local/lib/libpangoxft-1.0.0.2100.0.dylib
    /usr/local/lib/libportaudio.2.0.0.dylib
    /usr/local/lib/libSDL-1.2.0.dylib
    /usr/local/lib/libsoci_core.3.2.0.dylib
    /usr/local/lib/libsoci_empty.3.2.0.dylib
    /usr/local/lib/libsoci_mysql.3.2.0.dylib
    /usr/local/lib/libsoci_odbc.3.2.0.dylib
    /usr/local/lib/libsoci_postgresql.3.2.0.dylib
    /usr/local/lib/libsoci_sqlite3.3.2.0.dylib
    /usr/local/lib/libz.1.2.5.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/libirecovery.h
    /usr/local/include/soci/backend-loader.h
    /usr/local/include/soci/blob-exchange.h
    /usr/local/include/soci/blob.h
    /usr/local/include/soci/boost-fusion.h
    /usr/local/include/soci/boost-gregorian-date.h
    /usr/local/include/soci/boost-optional.h
    /usr/local/include/soci/boost-tuple.h
    /usr/local/include/soci/connection-parameters.h
    /usr/local/include/soci/connection-pool.h
    /usr/local/include/soci/empty/soci-empty.h
    /usr/local/include/soci/error.h
    /usr/local/include/soci/exchange-traits.h
    /usr/local/include/soci/into-type.h
    /usr/local/include/soci/into.h
    /usr/local/include/soci/mysql/common.h
    /usr/local/include/soci/mysql/soci-mysql.h
    /usr/local/include/soci/odbc/soci-odbc.h
    /usr/local/include/soci/odbc/utility.h
    /usr/local/include/soci/once-temp-type.h
    /usr/local/include/soci/postgresql/common.h
    /usr/local/include/soci/postgresql/soci-postgresql.h
    /usr/local/include/soci/prepare-temp-type.h
    /usr/local/include/soci/procedure.h
    /usr/local/include/soci/query_transformation.h
    /usr/local/include/soci/ref-counted-prepare-info.h
    /usr/local/include/soci/ref-counted-statement.h
    /usr/local/include/soci/row-exchange.h
    /usr/local/include/soci/row.h
    /usr/local/include/soci/rowid-exchange.h
    /usr/local/include/soci/rowid.h
    /usr/local/include/soci/rowset.h
    /usr/local/include/soci/session.h
    /usr/local/include/soci/soci-backend.h
    /usr/local/include/soci/soci-config.h
    /usr/local/include/soci/soci-platform.h
    /usr/local/include/soci/soci-simple.h
    /usr/local/include/soci/soci.h
    /usr/local/include/soci/sqlite3/common.h
    /usr/local/include/soci/sqlite3/soci-sqlite3.h
    /usr/local/include/soci/statement.h
    /usr/local/include/soci/transaction.h
    /usr/local/include/soci/type-conversion-traits.h
    /usr/local/include/soci/type-conversion.h
    /usr/local/include/soci/type-holder.h
    /usr/local/include/soci/type-ptr.h
    /usr/local/include/soci/unsigned-types.h
    /usr/local/include/soci/use-type.h
    /usr/local/include/soci/use.h
    /usr/local/include/soci/values-exchange.h
    /usr/local/include/soci/values.h
    /usr/local/include/soci/version.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libatk-1.0.la
    /usr/local/lib/libfreetype.la
    /usr/local/lib/libgdk-x11-2.0.la
    /usr/local/lib/libgdk_pixbuf-2.0.la
    /usr/local/lib/libgdk_pixbuf_xlib-2.0.la
    /usr/local/lib/libgio-2.0.la
    /usr/local/lib/libglib-2.0.la
    /usr/local/lib/libgmodule-2.0.la
    /usr/local/lib/libgobject-2.0.la
    /usr/local/lib/libgthread-2.0.la
    /usr/local/lib/libgtk-x11-2.0.la
    /usr/local/lib/libintl.la
    /usr/local/lib/libirecovery.la
    /usr/local/lib/libjpeg.la
    /usr/local/lib/libpango-1.0.la
    /usr/local/lib/libpangocairo-1.0.la
    /usr/local/lib/libpangoft2-1.0.la
    /usr/local/lib/libpangox-1.0.la
    /usr/local/lib/libpangoxft-1.0.la
    /usr/local/lib/libportaudio.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/libirecovery.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libGLEW.a
    /usr/local/lib/libintl.a
    /usr/local/lib/libirecovery.a
    /usr/local/lib/libjpeg.a
    /usr/local/lib/libportaudio.a
    /usr/local/lib/libsoci_core.a
    /usr/local/lib/libsoci_empty.a
    /usr/local/lib/libsoci_mysql.a
    /usr/local/lib/libsoci_odbc.a
    /usr/local/lib/libsoci_postgresql.a
    /usr/local/lib/libsoci_sqlite3.a
    /usr/local/lib/libz.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    docker
    gcc
    php54

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install dbus

**Comment by MikeMcQuaid** [comment]
It's like due to those `brew doctor` warnings. Please try to fix them (e.g. update the CLT, remove those files) and try again.

**Comment by voxynn** [comment]
I'm having a similar problem:

```
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/libgphoto2-2.5.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.10
Last 15 lines from /Users/Richard/Library/Logs/Homebrew/libgphoto2/01.configure:
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no
configure: error: 
libgphoto2 requires the ltdl library, included with lib tool

Please make sure that the proper development package is installed
(libltdl-dev, libtool-ltdl-devel, etc.)


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
libgphoto2 error  https://github.com/Homebrew/homebrew-core/issues/1406

Richards-MacBook-Air:~ Richard$ brew doctor
Your system is ready to brew.
```

Any advice?

**Comment by UniqMartin** [comment]
> Any advice?

As far as I can tell, this doesn't seem to be related to the issue discussed here. Can you please open a new issue? Please also run `brew gist-logs libgphoto2` and provide its output there.

**Comment by UniqMartin** [comment]
@mgracer48 Any update on your situation? Have you been able to follow Mike's advice?

**Comment by mgracer48** [comment]
the thing is that i have so much files that need deleting according to brew doctor i don't want to delete them because they might be important :/

**Comment by mgracer48** [comment]
found another bug  with gd:

MacBook-Pro:~ mgracer48$ brew upgrade wine --universal
==> Upgrading 1 outdated package, with result:
wine 1.8.2
==> Upgrading wine
==> Installing dependencies for wine: gd, libgphoto2, libtasn1, gnutls
==> Installing wine dependency: gd
==> Downloading https://github.com/libgd/libgd/releases/download/gd-2.2.1/libgd-
Already downloaded: /Library/Caches/Homebrew/gd-2.2.1.tar.xz
==> Downloading https://github.com/libgd/libgd/commit/502e4cd8.patch
Already downloaded: /Library/Caches/Homebrew/gd--patch-34fecd59b7f9646492647503375aaa34896bcc5a6eca1408c59a4b17e84896da.patch
==> Patching
==> Applying 502e4cd8.patch
patching file configure.ac
==> ./bootstrap.sh
==> ./configure --prefix=/usr/local/Cellar/gd/2.2.1 --without-x --with-png=/usr/
==> make install
Last 15 lines from /Users/mgracer48/Library/Logs/Homebrew/gd/03.make:
clang -DHAVE_CONFIG_H -I.   -I/usr/local/opt/libpng/include -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/opt/freetype/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1_2/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/jpeg/include  -I/usr/local/opt/libtiff/include -I/usr/local/Cellar/libtiff/4.0.6_1/include  -Werror -g -O2 -fvisibility=hidden -c -o annotate.o annotate.c
clang -DHAVE_CONFIG_H -I.   -I/usr/local/opt/libpng/include -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/opt/freetype/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1_2/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/jpeg/include  -I/usr/local/opt/libtiff/include -I/usr/local/Cellar/libtiff/4.0.6_1/include  -Werror -g -O2 -fvisibility=hidden -c -o gd2copypal.o gd2copypal.c
clang -DHAVE_CONFIG_H -I.   -I/usr/local/opt/libpng/include -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/opt/freetype/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1_2/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/jpeg/include  -I/usr/local/opt/libtiff/include -I/usr/local/Cellar/libtiff/4.0.6_1/include  -Werror -g -O2 -fvisibility=hidden -c -o gd2togif.o gd2togif.c
clang -DHAVE_CONFIG_H -I.   -I/usr/local/opt/libpng/include -I/usr/local/Cellar/libpng/1.6.21/include/libpng16 -I/usr/local/opt/freetype/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/fontconfig/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/Cellar/fontconfig/2.11.1_2/include -I/usr/local/Cellar/freetype/2.6.3/include/freetype2 -I/usr/local/opt/jpeg/include  -I/usr/local/opt/libtiff/include -I/usr/local/Cellar/libtiff/4.0.6_1/include  -Werror -g -O2 -fvisibility=hidden -c -o giftogd2.o giftogd2.c
/bin/sh ../libtool  --tag=CC   --mode=link clang  -Werror -g -O2 -fvisibility=hidden -version-info 3:1:0 -no-undefined  -o libgd.la -rpath /usr/local/Cellar/gd/2.2.1/lib gd.lo gd_bmp.lo gd_color.lo gd_color_map.lo gd_color_match.lo gd_crop.lo gd_filename.lo gd_filter.lo gd_gd.lo gd_gd2.lo gd_gif_in.lo gd_gif_out.lo gd_interpolation.lo gd_io.lo gd_io_dp.lo gd_io_file.lo gd_io_ss.lo gd_jpeg.lo gd_matrix.lo gd_nnquant.lo gd_png.lo gd_rotate.lo gd_security.lo gd_ss.lo gd_tga.lo gd_tiff.lo gd_topal.lo gd_transform.lo gd_version.lo gd_wbmp.lo gd_webp.lo gd_xbm.lo gdcache.lo gdfontg.lo gdfontl.lo gdfontmb.lo gdfonts.lo gdfontt.lo gdft.lo gdfx.lo gdhelpers.lo gdkanji.lo gdtables.lo gdxpm.lo wbmp.lo -liconv -lz -L/usr/local/opt/libpng/lib -L/usr/local/Cellar/libpng/1.6.21/lib -lpng16 -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/freetype/2.6.3/lib -lfreetype -L/usr/local/opt/fontconfig/lib -L/usr/local/Cellar/freetype/2.6.3/lib -L/usr/local/Cellar/fontconfig/2.11.1_2/lib -lfontconfig -lfreetype -L/usr/local/opt/jpeg/lib  -ljpeg -L/usr/local/opt/libtiff/lib -L/usr/local/Cellar/libtiff/4.0.6_1/lib -ltiff
libtool: link: clang -dynamiclib  -o .libs/libgd.3.dylib  .libs/gd.o .libs/gd_bmp.o .libs/gd_color.o .libs/gd_color_map.o .libs/gd_color_match.o .libs/gd_crop.o .libs/gd_filename.o .libs/gd_filter.o .libs/gd_gd.o .libs/gd_gd2.o .libs/gd_gif_in.o .libs/gd_gif_out.o .libs/gd_interpolation.o .libs/gd_io.o .libs/gd_io_dp.o .libs/gd_io_file.o .libs/gd_io_ss.o .libs/gd_jpeg.o .libs/gd_matrix.o .libs/gd_nnquant.o .libs/gd_png.o .libs/gd_rotate.o .libs/gd_security.o .libs/gd_ss.o .libs/gd_tga.o .libs/gd_tiff.o .libs/gd_topal.o .libs/gd_transform.o .libs/gd_version.o .libs/gd_wbmp.o .libs/gd_webp.o .libs/gd_xbm.o .libs/gdcache.o .libs/gdfontg.o .libs/gdfontl.o .libs/gdfontmb.o .libs/gdfonts.o .libs/gdfontt.o .libs/gdft.o .libs/gdfx.o .libs/gdhelpers.o .libs/gdkanji.o .libs/gdtables.o .libs/gdxpm.o .libs/wbmp.o   -liconv -lz -L/usr/local/opt/libpng/lib -L/usr/local/Cellar/libpng/1.6.21/lib -lpng16 -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/freetype/2.6.3/lib -L/usr/local/opt/fontconfig/lib -L/usr/local/Cellar/fontconfig/2.11.1_2/lib -lfontconfig -lfreetype -L/usr/local/opt/jpeg/lib -ljpeg -L/usr/local/opt/libtiff/lib -L/usr/local/Cellar/libtiff/4.0.6_1/lib -ltiff  -g -O2   -install_name  /usr/local/Cellar/gd/2.2.1/lib/libgd.3.dylib -compatibility_version 4 -current_version 4.1 -Wl,-single_module
Undefined symbols for architecture x86_64:
  "_compress", referenced from:
      __gdImageGd2 in gd_gd2.o
  "_uncompress", referenced from:
      __gd2ReadChunk in gd_gd2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libgd.la] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
gd build fails with command i expects \ followed by text https://github.com/Homebrew/homebrew-core/issues/1613
gd: remove gnu-sed dependency via upstream patch https://github.com/Homebrew/homebrew-core/pull/1622

**Comment by mgracer48** [comment]
got any advice for specific files i should remove and ones i can keep?

**Comment by mgracer48** [comment]
or should i remove them all?

**Comment by mgracer48** [comment]
i got so much soci stuff (because can't be installed by brew) this process takes forever

**Comment by mgracer48** [comment]
You know what be cool? A script that makes this easier deletes all the stuff that is unbrewed and asks if u want to delete or not
and if it finds anything matching in brew it will suggest it

**Comment by mgracer48** [comment]
no longer getting this kinda error issue is resolved
