### ISSUE TITLE
Wanting To Contribute 

### ISSUE THREAD

**Issue by hasahmed** [Homebrew/homebrew-core#14065]
Hey, I love homebrew, I think its the coolest thing and I'm wanting to contribute. I'm writing now to ask for some direction. I have no idea where to get started. I once stumbled upon a list of issues that needed to be worked on, but I can't seem to find it. Can someone point me in the right direction? Perhaps something small to get started? Sorry if this is the wrong place to ask questions. Thank you for your time.

**Comment by MikeMcQuaid** [comment]
Hey @hasahmed! Check out https://github.com/Homebrew/brew#contributing.
