### ISSUE TITLE
postgresql crashes with locale failure after upgrading to 9.6.3

### ISSUE THREAD

**Issue by cayblood** [Homebrew/homebrew-core#14084]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to do a `brew upgrade` and after it was complete, postgresql refused to start. The postgresql logs say
```
FATAL:  postmaster became multithreaded during startup
HINT:  Set the LC_ALL environment variable to a valid locale.
LOG:  database system is shut down
```
repeatedly. `brew services list` says that postgresql is started.

I tried to set LC_ALL in my `/etc/profile` file, hoping it would be applied to the postgresql user. That didn't help. Couldn't find how to set the environment for the `_postgres` user itself. I also tried uninstalling postgresql altogether and deleting the old db files, then installing from scratch. That didn't seem to help. The same errors are appearing in the logs.

**Comment by cayblood** [comment]
For what it's worth, I also got the same error after installing the downloadable postgresql mac app.

**Comment by JCount** [comment]
@cayblood Please fill out the rest of the issue template. It is a necessary element for trying to assist you.

**Comment by cayblood** [comment]
@JCount what portion of the issue template did I not fill out?

**Comment by JCount** [comment]
@cayblood Perhaps https://github.com/PostgresApp/PostgresApp/issues/317 may be helpful.

-----
(As an answer to your question):
- [ ] **If brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?**

(This meant that I had no substantive information to use to try and effectively help you with your issue.)
