### ISSUE TITLE
`deno` 1.36.3 fails when invoking `localStorage.setItem(...)`

### ISSUE THREAD

**Issue by davepeck** [Homebrew/homebrew-core#140808]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config
HOMEBREW_VERSION: 4.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: d4444b563e24ac7c05a93121c464c02dfa04d44f
Last commit: 2 days ago
Core tap JSON: 29 Aug 18:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: code --wait
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

```shell
> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

A simple call to `localStorage.setItem(...)` fails when using the latest `deno` as installed by `homebrew`.

### What happened (include all command output)?

```shell
> brew install deno
...
> which deno
/opt/homebrew/bin/deno
> deno --version
deno 1.36.3 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
> deno repl --allow-all
Deno 1.36.3
exit using ctrl+d, ctrl+c, or close()
> localStorage.setItem("hello", 42)
Uncaught Error: no such table: dbstat: Error code 1: SQL error or missing database
    at Proxy.setItem (ext:deno_webstorage/01_webstorage.js:51:9)
    at <anonymous>:2:14
```

### What did you expect to happen?

I expect this to work.

```shell
> deno-binary-not-from-homebrew repl --allow-all
Deno 1.36.3
exit using ctrl+d, ctrl+c, or close()
> localStorage.setItem("hello", 42)
undefined
```

### Step-by-step reproduction instructions (by running `brew` commands)

See above.

At first I assumed this was a `deno` issue. However, running `deno 1.36.3` both from `docker` _and_ directly built from source on my machine, I am unable to reproduce this behavior.

I paved a new M2 Mac Mini to make sure there wasn't something oddball about my M2 laptop where I originally ran into this problem. I was able to reproduce this behavior on the Mini, so I _think_ this is a valid bug. Would still like a separate repro from someone who isn't me. :-)

**Comment by Bo98** [comment]
Looks like deno assumes `SQLITE_ENABLE_DBSTAT_VTAB` is enabled. We can look into enabling that for our builds - shouldn't be a problem.

Not sure if there's anything more it needs though, I've not found any documentation on it.

**Comment by cho-m** [comment]
Partly a side effect of Homebrew's formula patching build to use our `sqlite` rather than static/bundled copy:
https://github.com/Homebrew/homebrew-core/blob/d1bcaa9aa1da613c097e8913e712b9af00db2d30/Formula/d/deno.rb#L97-L99

Worst case would be to enable everything from `rusqlite` (https://github.com/rusqlite/rusqlite/blob/v0.29.0/libsqlite3-sys/build.rs#L109-L128) if we assume it is fair game since `deno` expects bundled copy. Narrowing it down would be nice to avoid feature bloat.

**Comment by Bo98** [comment]
For comparison, Apple's SQLite have these we don't have (+ various other differences like `DEFAULT_CKPTFULLFSYNC`):

```
ENABLE_API_ARMOR
ENABLE_BYTECODE_VTAB
ENABLE_DBSTAT_VTAB
ENABLE_FTS3_TOKENIZER
ENABLE_NORMALIZE
ENABLE_SNAPSHOT
ENABLE_SQLLOG
ENABLE_STMT_SCANSTATUS
ENABLE_UNKNOWN_SQL_FUNCTION
ENABLE_UPDATE_DELETE_LIMIT
```

Though note that: `ENABLE_SQLLOG` requires extra patching, `ENABLE_UNKNOWN_SQL_FUNCTION` seems like a backwards compat option, `ENABLE_STMT_SCANSTATUS` has a performance penalty, and `ENABLE_FTS3_TOKENIZER` has security concern.

`rusqlite`'s `ENABLE_*` options seem ok except `SQLITE_ENABLE_JSON1`, `SQLITE_ENABLE_LOAD_EXTENSION` and `SQLITE_ENABLE_STAT2` are obsolete.

**Comment by ZhongRuoyu** [comment]
This issue should be fixed:

```console
$ deno
Deno 1.36.3
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> localStorage.setItem("hello", 42)
undefined
```

Please do `brew upgrade`.

**Comment by davepeck** [comment]
@ZhongRuoyu 🎉 I've confirmed that all is working. Thanks for the quick fix!
