### ISSUE TITLE
grc doesn't work after some recent updates

### ISSUE THREAD

**Issue by xeron** [Homebrew/homebrew-core#14082]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to use `grc diff` to colorize `diff -u` output.

- What happened (include command output)

It doesn't colorize it.

- What you expected to happen

It colorizes it. This was working before some recent updates to `grc` formula.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install grc
echo 1 > file1
echo 2 > file2
grc diff -u file1 file2 # no colors
grc -c conf.diff diff -u file1 file2 # error config file [conf.diff] not found
grc -c /opt/brew/share/grc/conf.diff diff -u file1 file2 # works, has colors
```

Same happens with other commands, for example `df` and `ping`:
```
grc df # no colors
grc -c /opt/brew/share/grc/conf.df df # has colors
grc ping 127.0.0.1 # no colors
grc -c /opt/brew/share/grc/conf.ping ping 127.0.0.1 # has colors
```

I understand that it could be related to the fact that my brew installation is under `/opt/brew` but the fact is that `grc` was working before.

### brew config
```
HOMEBREW_VERSION: 1.2.1-128-g344c49229
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 344c49229936736c902e08d965b4ed2262aa2c0c
Last commit: 38 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0fa7e12dd48002047dbc208ed8fdbfc3ef858a68
Core tap last commit: 43 minutes ago
HOMEBREW_PREFIX: /opt/brew
HOMEBREW_REPOSITORY: /opt/brew
HOMEBREW_CELLAR: /opt/brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.13.0 => /opt/brew/bin/git
Perl: /opt/brew/bin/perl => /opt/brew/Cellar/perl/5.24.1/bin/perl
Python: /opt/brew/bin/python => /opt/brew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/ilarionov/.rvm/rubies/ruby-2.4.1/bin/ruby
Java: 1.8.0_131, 1.7.0_80
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

### brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  libxml2
  libxslt
  openssl@1.1
```

**Comment by JCount** [comment]
Did you source the correct `grc` file in your relevant shell profile?

**Comment by xeron** [comment]
I don't source any `grc` shell files because I don't want automatic coloring of my commands. What I want to do is to use command `grc diff -u file1 file2`. This was working before, not sure when it broke, may be after some recent updates to 1.11: https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+grc+is%3Aclosed

**Comment by xeron** [comment]
BTW sourcing `grc.bashrc` doesn't help anyway:

![screen shot 2017-05-30 at 3 12 45 pm](https://cloud.githubusercontent.com/assets/110569/26607269/8bbaea38-454a-11e7-9a7d-fd113c67ab04.png)

**Comment by xeron** [comment]
May be it has something to do with these `install` changes: https://github.com/Homebrew/homebrew-core/commit/6eecadbebe8378551dfe66b0018ac0b633041ebf#diff-7d7cab99192dbb52c33f601c3f95c7f5L15

**Comment by JCount** [comment]
@xeron #14089 should fix this once it is merged.

**Comment by xeron** [comment]
You didn't bump the revision so I had to reinstall it but now it works as expected. Thanks!
