### ISSUE TITLE
Node 8 doesn't come with npm@5

### ISSUE THREAD

**Issue by ismay** [Homebrew/homebrew-core#14108]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Install node 8, which should come with npm 5.

- What happened (include command output)

After `brew upgrade node`, node 8 was installed with npm@4.2.0 (see here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/node.rb#L38).

- What you expected to happen

I expected it to install npm 5, as that's the version that should come with node 8, and it's the latest major version.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install node` or `brew upgrade node`

Is there a reason that npm wasn't updated? Because I'd expect it to install npm 5. If there's no reason it'd be nice to update npm to version 5.

**Comment by ilovezfs** [comment]
We know https://github.com/Homebrew/homebrew-core/pull/14085. But thanks for reporting!

**Comment by ilovezfs** [comment]
Note you can
```
npm install -g npm@latest
```
to get 5.0.0 immediately.

**Comment by ismay** [comment]
@ilovezfs Ah ok sorry, I missed that. Thanks for the quick reply!

**Comment by ilovezfs** [comment]
No problem at all. We genuinely appreciate the report!

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/14085.
