### ISSUE TITLE
qt failed to build on 10.12.5

### ISSUE THREAD

**Issue by TarSzator** [Homebrew/homebrew-core#14106]
I have a problem running "brew upgrade" due to an error in the build process of "qt --with-qtwebkit". I tried to do a general upgrade because upgrades make sense :-)

I got the error(?) "make[2]: Nothing to be done for `first'." followed by a message to read the trouble shooting guide. There was a large command in front of the error I will post it here when requested since it was very long.
The output of "brw gist-logs qt" can be found here https://gist.github.com/befccb43f3036c00dd5766c5a8c908b4

I expected the upgrade to work without problems ;-)

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by ilovezfs** [comment]
5.9.0 has shipped. Please let us know if this is still a problem with 5.9.0.
