### ISSUE TITLE
Please provide a node 7 version

### ISSUE THREAD

**Issue by thewoolleyman** [Homebrew/homebrew-core#14118]
node v 8.0.0 is a major upgrade, and likely to break many things, e.g. https://github.com/sass/node-sass/issues/1985

Please provide a Node 7 [version](http://docs.brew.sh/Versions.html) to easily downgrade while the 8.0 downstream dust settles.

Thanks,
-- Chad

**Comment by ilovezfs** [comment]
There is no upstream LTS for 7.x (https://github.com/nodejs/LTS#lts-schedule1) so I would suggest you try moving to 8.x ASAP. The issue you linked indicates, "Support was added in 4.5.3 but the binaries still need to be built."

**Comment by thewoolleyman** [comment]
OK, then how about Node 6, which is LTS until April 2019?

The node-sass issue I linked was just an example issue of something that broke under 8.  There will likely be others.

If key third-party libraries that people need don't yet support 8, then "move to 8.x ASAP" isn't very helpful advice, because they aren't in control of how fast the maintainers upgrade.  And if there's no easy downgrade path to an older node version, they are stuck having to install it outside of brew or some other manual way.

**Comment by ilovezfs** [comment]
node@6 is already available.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@6.rb

**Comment by thewoolleyman** [comment]
@ilovezfs Ah, I didn't realize node@6 was already available.  That one works for now, thanks!

**Comment by lvieirajr** [comment]
What about people who have stuff relying on Node7, but that can't update atm to Node8?
Are we just going to leave these people behind just because there is no LTS?
I don't know how things are done here, but not allowing people to install something because there is no LTS for it doesn't seem like a good path to follow.

E.g: If I'm on a project that required Node 7 (for whatever reasons) and my computer stops working and I have to get a new one, now I can't install node 7 to get the project to work, so I am stuck forever.

**Comment by ilovezfs** [comment]
@lvieirajr You can see the criteria for versioned formulae here: https://github.com/Homebrew/brew/blob/master/docs/Versions.md

Specifically, versioned formulae need to be "still supported by their upstream projects" which is not the case for a non-LTS node release.

**Comment by lvieirajr** [comment]
Thank you for the quick and thorough response.
Although I do not agree with this policy it is the one that is stated and which I by using brew "accepted".
I guess I'll just have to figure out another way to download it or create my own tap.

**Comment by ilovezfs** [comment]
@lvieirajr you're welcome. Here's what you'll want to do:
```
bash-3.2$ git log -n10 --format="%h %s" -- Formula/node.rb 
b1189a0a77 node: update 8.1.0 bottle.
a9422dde73 node 8.1.0
cd4e7e0c5f node: copy rather than symlink manpages
20bfd4facb node: update 8.0.0_1 bottle.
ecb2d1e855 node: update npm to 5.0.1
3eab657601 node: update 8.0.0 bottle.
5b37dc0000 node 8.0.0
b40b8b4697 node: fix rubocop warnings.
d378f637cd node: update 7.10.0 bottle.
4662200e45 node 7.10.0
bash-3.2$ git show 5b37dc0000^:Formula/node.rb
```

**Comment by nicksnyder** [comment]
```
$ brew uninstall node
$ cd $(brew --repo homebrew/core)
$ git reset --HARD 5b37dc0000^
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install node
```
