### ISSUE TITLE
node 8.0.0 should contain npm 5.0.0 but contains 4.2.0

### ISSUE THREAD

**Issue by ravshansbox** [Homebrew/homebrew-core#14128]

**Comment by sholladay** [comment]
They are trying: https://github.com/Homebrew/homebrew-core/pull/14085

It is hard apparently. @iarna @zkat

**Comment by ravshansbox** [comment]
thanks.

**Comment by ilovezfs** [comment]
You can safely `npm install -g npm@latest` if you need 5.0.0 immediately.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/14085.
