### ISSUE TITLE
lablgtk bottle out of date wrt ocaml dependency

### ISSUE THREAD

**Issue by btj** [Homebrew/homebrew-core#14126]
The current `lablgtk` bottle (dated Dec 1, 2016) is incompatible with the current `ocaml` bottle (dated April 15, 2017). OCaml libraries compiled with a given version of the OCaml compiler are not compatible with newer OCaml compilers.

Please rebuild the bottle.

**Comment by ilovezfs** [comment]
This should be fixed now if you brew update and brew upgrade. Thank you for reporting it @btj

**Comment by ilovezfs** [comment]
@btj any idea if we need to revision bump lablgtk for OCaml 4.06.1, which I just shipped?
