### ISSUE TITLE
sudo: unable to stat /etc/sudoers.d/10-installer: Permission denied when permissions seem to be fine.

### ISSUE THREAD

**Issue by BigNoseSec** [Homebrew/homebrew-core#1413]
# Please follow the general troubleshooting steps first:

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Having trouble installing cmake and qt. perl installed fine.

Using Archlinux, and other information needed can be provided. Anyone have any insight?

I tried sudo chown -R $(whoami) $(brew --prefix) and i just got the cowardly error. (as expected, so i reversed it back to root ownership.)

`sudo brew install cmake            
==> Installing dependencies for cmake: openssl, bzip2, python, curl, libidn
==> Installing cmake dependency: openssl
sudo: unable to stat /etc/sudoers.d/10-installer: Permission denied
sudo: unable to stat /etc/sudoers.d/g_wheel: Permission denied
==> Downloading https://www.openssl.org/source/openssl-1.0.2h.tar.gz
Already downloaded: /root/.cache/Homebrew/openssl-1.0.2h.tar.gz
==> perl ./Configure --prefix=/opt/linuxbrew/Cellar/openssl/1.0.2h --openssldir=/usr/local/etc/openssl no
Last 15 lines from /root/.cache/Homebrew/Logs/openssl/01.perl:
2016-05-25 14:52:55 -0400

perl
./Configure
--prefix=/opt/linuxbrew/Cellar/openssl/1.0.2h
--openssldir=/usr/local/etc/openssl
no-ssl2
zlib-dynamic
shared
enable-cms
 -Os -w -pipe -march=native -Wl,--dynamic-linker=/usr/local/lib/ld.so -Wl,-rpath,/usr/local/lib
linux-x86_64

target already defined -  -Os -w -pipe -march=native -Wl,--dynamic-linker=/usr/local/lib/ld.so -Wl,-rpath,/usr/local/lib (offending arg: linux-x86_64)

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues

`

**Comment by DomT4** [comment]
> If reporting this issue please do so at (not Homebrew/brew):
https://github.com/Linuxbrew/homebrew-core/issues

You will need to do that I'm afraid. Linuxbrew handle the Linux support.

**Comment by BigNoseSec** [comment]
My mistake!

Thanks!
