### ISSUE TITLE
riscv64-elf-gcc does not work

### ISSUE THREAD

**Issue by ilya-lavrenov** [Homebrew/homebrew-core#141578]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  riscv64-elf-binutils
  riscv64-elf-gcc
  riscv64-elf-gdb
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

To build product via cmake and riscv64 toolchain

### What happened (include all command output)?

-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /opt/homebrew/bin/riscv64-elf-gcc
-- Check for working C compiler: /opt/homebrew/bin/riscv64-elf-gcc - broken
CMake Error at /opt/homebrew/lib/python3.11/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeTestCCompiler.cmake:70 (message):
  The C compiler

    "/opt/homebrew/bin/riscv64-elf-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/sandye51/Documents/Programming/builds/openvino-risc/CMakeFiles/CMakeScratch/TryCompile-0DYUAM
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_9cf7e/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_9cf7e.dir/build.make CMakeFiles/cmTC_9cf7e.dir/build
    Building C object CMakeFiles/cmTC_9cf7e.dir/testCCompiler.c.o
    /opt/homebrew/bin/riscv64-elf-gcc    -o CMakeFiles/cmTC_9cf7e.dir/testCCompiler.c.o -c /Users/sandye51/Documents/Programming/builds/openvino-risc/CMakeFiles/CMakeScratch/TryCompile-0DYUAM/testCCompiler.c
    Linking C executable cmTC_9cf7e
    /opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9cf7e.dir/link.txt --verbose=1
    /opt/homebrew/bin/riscv64-elf-gcc CMakeFiles/cmTC_9cf7e.dir/testCCompiler.c.o -o cmTC_9cf7e 
    /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ld: cannot find crt0.o: No such file or directory
    /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ld: cannot find -lc: No such file or directory
    /opt/homebrew/opt/riscv64-elf-binutils/bin/riscv64-elf-ld: cannot find -lgloss: No such file or directory
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTC_9cf7e] Error 1
    make: *** [cmTC_9cf7e/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:25 (project)

-- Configuring incomplete, errors occurred!

### What did you expect to happen?

cmake configure step to pass

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
git clone https://github.com/oneapi-src/oneTBB.git
CXX=riscv64-elf-g++ CC=riscv64-elf-gcc cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=riscv64 oneTBB
```

**Comment by ilya-lavrenov** [comment]
CC @mkroening

**Comment by fxcoudert** [comment]
If I am correct, the missing files should come from your riscv64-elf system library. Do you have a libc for riscv64-elf installed? (glibc or musl)

**Comment by ilya-lavrenov** [comment]
I've additionally installed https://github.com/riscv-software-src/homebrew-riscv:
```sh
brew tap riscv-software-src/riscv
brew install riscv-tools
```
And now it fails with:
```bash
sandye51@Ilyas-Air openvino-risc % cmake -DCMAKE_CXX_COMPILER=/opt/homebrew/bin/riscv64-elf-g++ -DCMAKE_C_COMPILER=/opt/homebrew/bin/riscv64-elf-gcc -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=riscv64 ../../git_repo/oneTBB
-- The CXX compiler identification is GNU 13.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /opt/homebrew/bin/riscv64-elf-g++
-- Check for working CXX compiler: /opt/homebrew/bin/riscv64-elf-g++ - broken
CMake Error at /opt/homebrew/lib/python3.11/site-packages/cmake/data/share/cmake-3.25/Modules/CMakeTestCXXCompiler.cmake:63 (message):
  The C++ compiler

    "/opt/homebrew/bin/riscv64-elf-g++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/sandye51/Documents/Programming/builds/openvino-risc/CMakeFiles/CMakeScratch/TryCompile-ezHP4l
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_41ada/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_41ada.dir/build.make CMakeFiles/cmTC_41ada.dir/build
    Building CXX object CMakeFiles/cmTC_41ada.dir/testCXXCompiler.cxx.o
    /opt/homebrew/bin/riscv64-elf-g++    -o CMakeFiles/cmTC_41ada.dir/testCXXCompiler.cxx.o -c /Users/sandye51/Documents/Programming/builds/openvino-risc/CMakeFiles/CMakeScratch/TryCompile-ezHP4l/testCXXCompiler.cxx
    Linking CXX executable cmTC_41ada
    /opt/homebrew/lib/python3.11/site-packages/cmake/data/bin/cmake -E cmake_link_script CMakeFiles/cmTC_41ada.dir/link.txt --verbose=1
    /opt/homebrew/bin/riscv64-elf-g++ -rdynamic CMakeFiles/cmTC_41ada.dir/testCXXCompiler.cxx.o -o cmTC_41ada 
    riscv64-elf-g++: error: unrecognized command-line option '-rdynamic'
    make[1]: *** [cmTC_41ada] Error 1
    make: *** [cmTC_41ada/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:57 (project)

```

**Comment by fxcoudert** [comment]
So that's building https://github.com/oneapi-src/oneTBB is that correct? Is it a supported configuration? Why is it passing `-rdynamic`? Is that flag really supported on riscv64-elf?
