### ISSUE TITLE
python installation partiallyl fails 

### ISSUE THREAD

**Issue by michalsarna** [Homebrew/homebrew-core#1415]
### Bug reports:

```
brew install python
==> Downloading https://homebrew.bintray.com/bottles/python-2.7.11.el_capitan.bottle.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/python-2.7.11.el_capitan.bottle.2.tar.gz
==> Pouring python-2.7.11.el_capitan.bottle.2.tar.gz
==> /usr/local/Cellar/python/2.7.11/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/micsar/Library/Logs/Homebrew/python/01.python:
  File "/usr/local/Cellar/python/2.7.11/libexec/setuptools/pkg_resources/__init__.py", line 2510, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/Cellar/python/2.7.11/libexec/setuptools/pkg_resources/__init__.py", line 2827, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/Cellar/python/2.7.11/libexec/setuptools/pkg_resources/__init__.py", line 2475, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/Cellar/python/2.7.11/libexec/setuptools/pkg_resources/__init__.py", line 2643, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/Cellar/python/2.7.11/libexec/setuptools/pkg_resources/__init__.py", line 2011, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/Cellar/python/2.7.11/libexec/setuptools/pkg_resources/__init__.py", line 2006, in get_metadata
    metadata = f.read()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb6 in position 147: invalid start byte
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/python/2.7.11: 4,521 files, 61M
```

https://gist.github.com/00337f2a937f66a23aecf73d847229c3

**Comment by MikeMcQuaid** [comment]
No idea what's going on here. @tdsmith, any ideas?

**Comment by tdsmith** [comment]
I don't understand either. If you `brew reinstall python` does this error persist?

**Comment by michalsarna** [comment]
@tdsmith yep. nothing helped. I've tried `brew install python` and `brew reinstall python`. Funny thing is that python2.7 appears and it's working. but there is no easy_install nor pip. 
Brew suggested to run `brew postinstall python` and that failed with same error so it looks like problem with setuptools.
I need to test python 2.7 from official pkg from: https://www.python.org/ftp/python/2.7.11/python-2.7.11-macosx10.6.pkg

**Comment by michalsarna** [comment]
And now I can confirm that pkg version is working. :(

**Comment by tdsmith** [comment]
Taking a closer look, it seems like one of your installed packages might be malformed, which is unfortunately keeping setuptools from installing. If you `rm -rf /usr/local/lib/python2.7/site-packages` I bet `brew postinstall python` will succeed.

**Comment by tdsmith** [comment]
(Arguably, pkg_resources should be robust to this scenario)

**Comment by michalsarna** [comment]
@tdsmith You are a great human being. Removing site-packages worked like a charm.

**Comment by MikeMcQuaid** [comment]
Nice work @tdsmith 👏

**Comment by diegocavalletti** [comment]
I'm having similar issue aswell, my installation completed successfully but if i go with `python -v` i get this:

`[~/Downloads/moist-master]$ python -v                                                                                                        rbenv:2.3.0 
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py
import site # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py
import os # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/stat.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/stat.py
import stat # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/stat.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.py
import warnings # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/linecache.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/linecache.py
import linecache # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/linecache.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/types.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/types.py
import types # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/types.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py
import abc # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/_weakrefset.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy_reg.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy_reg.pyc
# /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.pyc matches /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py
import traceback # precompiled from /usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py
import re # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_parse.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_constants.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_constants.pyc
dlopen("/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so", 2);
import _locale # dynamically loaded from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_sysconfigdata.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_sysconfigdata.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_osx_support.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_osx_support.py
import _osx_support # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_osx_support.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sitecustomize.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sitecustomize.py
import sitecustomize # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sitecustomize.pyc
import encodings # directory /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/__init__.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/__init__.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py
import codecs # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/aliases.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/aliases.pyc
# /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.pyc matches /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.pyc
Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
dlopen("/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so", 2);
import readline # dynamically loaded from /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/readline.so`
