### ISSUE TITLE
brew install/upgrade on neovim HEAD fails

### ISSUE THREAD

**Issue by nathanjcollins** [Homebrew/homebrew-core#141545]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew doctor`
Your system is ready to brew.

`brew config`
HOMEBREW_VERSION: 4.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0985dabec8517ab5afda7cfee7d59f1da4ed6ce
Last commit: 13 hours ago
Core tap JSON: 06 Sep 05:51 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to upgrade my neovim to the latest HEAD. It has been working for the last few weeks, and it had just stopped working yesterday.

### What happened (include all command output)?

==> Fetching neovim
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/191729e3986e7ac409404048c06f64c422fd3b57/Formula/n/neovim.rb
Already downloaded: /Users/nathancollins/Library/Caches/Homebrew/downloads/4b7bf7043f59686c818d2c94c32f6cf4d6178fbc556774d8f338194a0eeccb4c--neovim.rb
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/nathancollins/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 2ef7b6a43 Merge pull request #25030 from zeertzjq/vim-9.0.1874
==> cmake -S . -B build -DLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib -DLIBUV_LIBRARY=/opt/homebrew/opt/libuv/lib/libuv.dylib
Last 15 lines from /Users/nathancollins/Library/Logs/Homebrew/neovim/01.cmake:
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Libuv: /opt/homebrew/opt/libuv/lib/libuv.dylib (Required is at least version "1.28.0")
-- Found Luv: /opt/homebrew/opt/luv/lib/libluv.dylib (Required is at least version "1.43.0")
-- Found Iconv: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include
CMake Error at /opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Lpeg (missing: LPEG_LIBRARY)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.27.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLpeg.cmake:3 (find_package_handle_standard_args)
  src/nvim/CMakeLists.txt:29 (find_package)

-- Configuring incomplete, errors occurred!

READ THIS: https://docs.brew.sh/Troubleshooting

neovim's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

### What did you expect to happen?

I expected the build to succeed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install neovim --HEAD`

OR

`brew upgrade neovim --fetch-HEAD`
```

**Comment by feekApp** [comment]
I experience exactly the same also same error output.

**Comment by SMillerDev** [comment]
`HEAD` builds are not supported, they take an untagged commit and can therefore break at any time.
