### ISSUE TITLE
Unbound 1.18.0 Is Broken

### ISSUE THREAD

**Issue by elfurbe** [Homebrew/homebrew-core#141643]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
amichel@spectre:~ $ brew config && brew doctor
HOMEBREW_VERSION: 4.1.8-46-gd5d7478
ORIGIN: https://github.com/Homebrew/brew
HEAD: d5d74788b2eb2b3bdfdd5a632dfb1c8290f33b42
Last commit: 9 hours ago
Core tap JSON: 06 Sep 23:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ZK9wqtR17V/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  fwknop
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am trying to use unbound but version 1.18.0 is broken on mac, apparently (https://github.com/NLnetLabs/unbound/issues/928).

NOTE: I WAS REQUIRED to lie and check a box above, my brew doctor produces a warning about a Formula you're very mad about due to lack of updates that I will not uninstall because I use it. I cannot make it say "Your system is ready to brew", but my system brews just fine.

### What happened (include all command output)?

I updated unbound as part of a bulk brew update, and now it doesn't work, not much to it.

### What did you expect to happen?

Either unbound should work or I should be able to put back the old version, honestly both I think, but either one would be fine. Currently you're at 0/2.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install unbound`
2. `brew services start unbound` or run it from the command line by hand, it doesn't really matter, it's broken either way
3. Try to do a DNS query against it and be sad when it crashes.

4. Optionally: try to roll back to 1.17.1 if you already cleaned it up after the upgrade. I couldn't figure it out. It was easier to download the unbound source manually and compile it by hand and install it into /opt/homebrew/Cellar/unbound/1.17.1 and copy some files over from 1.18.0 which apparently trick homebrew into believing it's installed so I could then manually move 1.18.0 out of there and pin my hand-rolled 1.17.1 and thus have a working version. Why was that easier than `brew install unbound@1.17.1`, honestly could not tell you, but it was, cause that command does not work. You seem to have broken formula history by re-organizing the formula directory? Couldn't say for sure, I'm not a homebrew scholar, but something ain't right.
```

**Comment by alebcay** [comment]
Reproduced the issue building 1.18.0 outside of Homebrew. Performed some further investigation and left a comment on the upstream issue.

**Comment by elfurbe** [comment]
Version 1.18.0_1 installed, works as expected. Cheers!
