### ISSUE TITLE
unexpected behavior of `brew install` in shell script piped into `bash -s`

### ISSUE THREAD

**Issue by LukeWinikates** [Homebrew/homebrew-core#141712]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
>  brew config
HOMEBREW_VERSION: 4.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 12c8778af976269344f3c0b914243e178fc4ffbd
Last commit: 16 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 27320f133bde93c35a6e9e776157b478c46ed782
Core tap last commit: 79 minutes ago
Core tap branch: master
Core tap JSON: 07 Sep 18:31 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-x86_64
CLT: N/A
Xcode: 14.3.1

> brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am investigating a bug in a script that tries to automate some homebrew package installs. It was mysteriously printing a few lines of bash, rather than evaluating them. I reduced the reproduction steps down to a 2-line script.

### What happened (include all command output)?

rather than handing control back to the parent `bash` process, `brew install` prints the remaining contents of the bash file and exits.

### What did you expect to happen?

I expected the brew install to succeed and `ls .` to run afterward.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
create a script with these contents:


#!/bin/bash

brew install zookeeper
ls .
```

invoke it like this:

`cat ./test.sh | bash -s --`

The output I get is:

```
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

==> Downloading https://ghcr.io/v2/homebrew/core/zookeeper/manifests/3.9.0
Already downloaded: /Users/winikatesl/Library/Caches/Homebrew/downloads/6f4373dab7ba9ea36095aa9230272528a43b181b32b4e242ae6ef77580dfa754--zookeeper-3.9.0.bottle_manifest.json
==> Fetching zookeeper
==> Downloading https://ghcr.io/v2/homebrew/core/zookeeper/blobs/sha256:dd31876c
Already downloaded: /Users/winikatesl/Library/Caches/Homebrew/downloads/34efe9be8972bc8d0515becc6c933e4adf2777930562f7fb8f520609a0b75e61--zookeeper--3.9.0.ventura.bottle.tar.gz
==> Pouring zookeeper--3.9.0.ventura.bottle.tar.gz
ls .==> Caveats
To start zookeeper now and restart at login:
  brew services start zookeeper
Or, if you don't want/need a background service you can just run:
  SERVER_JVMFLAGS="-Dapple.awt.UIElement=true" /usr/local/opt/zookeeper/bin/zkServer start-foreground
==> Summary
🍺  /usr/local/Cellar/zookeeper/3.9.0: 1,111 files, 61.8MB
==> Running `brew cleanup zookeeper`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

For some reason, it prints `ls .` partway through the install, rather than executing `ls .` after the install has succeeded. If the contents of the file are larger, it'll print the whole remaining file.

I think that perhaps something inside homebrew is trying to read from `stdin`, but I'm not sure what it could be.

I originally found this with this formula: https://github.com/wavefrontHQ/homebrew-wavefront/blob/master/Formula/wfproxy.rb

I was able to reproduce it with `zookeeper`. But it doesn't happen with `kustomize`, `jq`, or `apache-geode`. I couldn't find any obvious unifying feature of the failing formulae.
```

**Comment by Bo98** [comment]
You're likely seeing it on formulae with post-installs. In those we open a subprocess in a new pseudo-terminal as a sandbox, and pipe stdin into that (since while `brew` generally doesn't need stdin, some features can such as `--debug`). This process is intentionally a separate pseudo-terminal to detach itself from potentially impacting the parent terminal state. I guess this bridge somewhere doesn't really hande the case where stdin is passed but not actually read in the spawned pseudo-terminal.

Might be worth testing this on Linux (e.g. in Docker). I think macOS pseudo-terminals have a different behaviour, such as enabling the `PENDIN` flag. Unfortunately it's tricky to control this behaviour within Ruby.

**Comment by LukeWinikates** [comment]
Thanks @Bo98 - I tried a few different changes to my brew formula - basically trying to make it look more like the `kustomize` one, to try to understand what would make them different enough. Nothing I added or commented out changed anything. My formula has a `service` block but no `post_install`.

But if I change the calling script from:

```
brew install zookeeper
ls .
```

to 

```
echo "" | brew install zookeeper
ls .
```

then sure enough, `brew install` takes that STDIN and then the rest of the script file proceeds normally.

What I'm seeing doesn't seem consistent with `post_install` being the culprit. Is there anything that happens prior to install that might be trying to read stdin? If I do a `puts` in my `install` method, I see the stdin getting printed out right before my "got here":

```ruby
def install
      puts "got here"
end
```

```bash
% cat ./sh/test.sh| bash -s --

==> Fetching wfproxy
==> Downloading https://wavefront-cdn.s3.us-west-2.amazonaws.com/brew/wavefront-
Already downloaded: /Users/winikatesl/Library/Caches/Homebrew/downloads/3b24f519c584e937bd7d057fbc835e747953e564f557326235710ba1045480cb--wavefront-proxy-13.2.0.zip
ls .
#
#echo "" | brew install zookeeper
#ls .got here
```

One thing I notice about my formula is that it doesn't use `bottle`. `zookeeper` uses bottles, but it has a `post_install`, so maybe with the `zookeeper` formula, it's `post_install` but in my formula's case it's something about installing a non-bottled formula.
