### ISSUE TITLE
Update core now PHP wont work libavif.15.dylib not found 

### ISSUE THREAD

**Issue by philipbradbury1** [Homebrew/homebrew-core#141766]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 12c8778af976269344f3c0b914243e178fc4ffbd
Last commit: 33 hours ago
Core tap JSON: 08 Sep 10:36 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /opt/homebrew/bin/git
Curl: 7.88.1 => /usr/bin/curl
macOS: 13.4.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false


Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

After an update of brew coere I now get the issue with php. 

### What happened (include all command output)?

php -v 

dyld[16337]: Library not loaded: /opt/homebrew/opt/libavif/lib/libavif.15.dylib
  Referenced from: <87C1A268-34E4-396F-8BBC-D5591064E333> /opt/homebrew/Cellar/gd/2.3.3_5/lib/libgd.3.dylib
  Reason: tried: '/opt/homebrew/opt/libavif/lib/libavif.15.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libavif/lib/libavif.15.dylib' (no such file), '/opt/homebrew/opt/libavif/lib/libavif.15.dylib' (no such file), '/usr/local/lib/libavif.15.dylib' (no such file), '/usr/lib/libavif.15.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/libavif/1.0.1/lib/libavif.15.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libavif/1.0.1/lib/libavif.15.dylib' (no such file), '/opt/homebrew/Cellar/libavif/1.0.1/lib/libavif.15.dylib' (no such file), '/usr/local/lib/libavif.15.dylib' (no such file), '/usr/lib/libavif.15.dylib' (no such file, not in dyld cache)

### What did you expect to happen?

For php to show me the version and work as expected

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
php -v
```

**Comment by philipbradbury1** [comment]
brew reinstall php

```
dyld[18140]: Library not loaded: /opt/homebrew/opt/libavif/lib/libavif.15.dylib
  Referenced from: <87C1A268-34E4-396F-8BBC-D5591064E333> /opt/homebrew/Cellar/gd/2.3.3_5/lib/libgd.3.dylib
  Reason: tried: '/opt/homebrew/opt/libavif/lib/libavif.15.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libavif/lib/libavif.15.dylib' (no such file), '/opt/homebrew/opt/libavif/lib/libavif.15.dylib' (no such file), '/usr/local/lib/libavif.15.dylib' (no such file), '/usr/lib/libavif.15.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/libavif/1.0.1/lib/libavif.15.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libavif/1.0.1/lib/libavif.15.dylib' (no such file), '/opt/homebrew/Cellar/libavif/1.0.1/lib/libavif.15.dylib' (no such file), '/usr/local/lib/libavif.15.dylib' (no such file), '/usr/lib/libavif.15.dylib' (no such file, not in dyld cache)
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall php
```

**Comment by SMillerDev** [comment]
What does `brew outdated` say?

**Comment by philipbradbury1** [comment]
abseil (20230125.3) < 20230802.0
gcc (13.1.0) < 13.2.0
gd (2.3.3_5) < 2.3.3_6
git (2.39.2) < 2.42.0
glib (2.76.4) < 2.76.5
heroku/brew/heroku (7.68.2) < 8.4.2
imagemagick (7.1.1-15) < 7.1.1-15_1
jpeg-xl (0.8.2) < 0.8.2_1
libnghttp2 (1.55.1) < 1.56.0
nginx (1.23.3, 1.25.1_1) < 1.25.2
node (20.5.0) < 20.6.0
php@8.1 (8.1.21) < 8.1.23
protobuf (23.4) < 24.2_1
redis (7.0.12) < 7.2.1
rtmpdump (2.4+20151223_2) < 2.4-20151223_3

**Comment by SMillerDev** [comment]
Yeah, you've updated only part of your system. Updating GD too should fix it

**Comment by akabucko** [comment]
> Yeah, you've updated only part of your system. Updating GD too should fix it

This worked for me `brew upgrade gd`
