### ISSUE TITLE
CIVL 1.7 failed to build on 10.11

### ISSUE THREAD

**Issue by AlshammariA** [Homebrew/homebrew-core#1418]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by AlshammariA** [comment]
I have noticed that the sha256 was updated two days ago, 
https://github.com/Homebrew/homebrew-core/blob/master/Formula/civl.rb

Is this updated related to this error? 

Abdulrahmans-MacBook-Pro:homebrew-core Abdulrahman$ brew install civl
==> Installing dependencies for civl: z3
==> Installing civl dependency: z3
==> Downloading https://homebrew.bintray.com/bottles/z3-4.4.1.el_capitan.bottle.
Already downloaded: /Library/Caches/Homebrew/z3-4.4.1.el_capitan.bottle.2.tar.gz
==> Pouring z3-4.4.1.el_capitan.bottle.2.tar.gz
==> Caveats
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/Abdulrahman/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/Abdulrahman/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/z3/4.4.1: 76 files, 72M
==> Installing civl
==> Downloading http://vsl.cis.udel.edu/lib/sw/civl/1.7/r3157/release/CIVL-1.7_3
Already downloaded: /Library/Caches/Homebrew/civl-1.7-3157.tgz
Error: SHA256 mismatch
Expected: 49ed0467ea281bf5a436b2caf4f87862d3f613fa9e6e746ce52cfd409c3f4403
Actual: 33fa5b4877fbf494b0a4b426c15d6a165fa3db48a9f97cbf391818d965d2dfb9
Archive: /Library/Caches/Homebrew/civl-1.7-3157.tgz
To retry an incomplete download, remove the file above.

**Comment by UniqMartin** [comment]
Yes, it is. Apparently upstream updated the archive without creating a new release (not good, but happens sometimes). You can fix the problem by moving the mentioned file in the Homebrew cache somewhere else (or just delete it) or by running `brew fetch --retry civl`.
