### ISSUE TITLE
libfaketime doesn't install due to compile failure

### ISSUE THREAD

**Issue by nikhilbhardwaj** [Homebrew/homebrew-core#14191]
# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ *] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/anonymous/cdd5e4d712b91230be845916570c1522

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install libfaketime
- What happened (include command output)
brew install failed
- What you expected to happen
brew install should succeed
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install libfaketime

**Comment by ilovezfs** [comment]
Thanks for reporting this. It actually turns out to already be a known issue as this is one of the formulae still without a Sierra bottle, which are listed here along with the reasons: https://github.com/Homebrew/homebrew-core/issues/6408

**Comment by ilovezfs** [comment]
The good news is that it looks like there's been progress on the problem upstream and the fix should be in the next release: https://github.com/wolfcw/libfaketime/commits/master

**Comment by ilovezfs** [comment]
@nikhilbhardwaj I've added a head spec in https://github.com/Homebrew/homebrew-core/pull/14205 so you can do
```
brew install --HEAD libfaketime
```
until the new release is out.

**Comment by nikhilbhardwaj** [comment]
Thanks @ilovezfs for fixing this so quickly.
Appreciate it!
