### ISSUE TITLE
Redis cannot start because of broken log directory

### ISSUE THREAD

**Issue by hyperknot** [Homebrew/homebrew-core#14192]
Because of this issue: https://github.com/Homebrew/homebrew-services/issues/121 Redis cannot start in service mode. It can start with `redis-server /usr/local/etc/redis.conf`. Test was done with `redis-cli ping`

To help us debug your issue please explain:
- What you were trying to do (and why): 
Install redis on a clean homebrew reinstall (after `rm -rf /usr/local`)
- What happened (include command output): 
`redis-cli ping` didn't work, as redis couldn't start because of the log dir issue 
- What you expected to happen
`redis-cli ping` should have replied: `PONG`, like it does in `redis-server /usr/local/etc/redis.conf` mode
- Step-by-step reproduction instructions (by running `brew install` commands):
1. Reinstall homebrew, deleting `/usr/local`
2. Install redis

Config output:
```
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6339c5b85a6d354ae2f3d63c8ea4549420c5711d
Core tap last commit: 82 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by MikeMcQuaid** [comment]
> redis-cli ping didn't work, as redis couldn't start because of the log dir issue

Please remove your existing log directory and run `brew reinstall redis` which should address this.

**Comment by hyperknot** [comment]
OK, I don't know how did I end up with a root owned log folder on a clean install.

I did try reinstall many times and it did nothing. Also, more importantly it also didn't say any warning.

Reproduce:
1. Stop redis
2. Remove log folder
3. Start redis and stop redis
4. Now log is root owned
5. `brew reinstall redis` will not say anything at all about having a non-functioning system.

I recommend that the install command at least displays a warning, or even better, offer to chown to correct values, but that'd require a sudo prompt.

**Comment by MikeMcQuaid** [comment]
> I recommend that the install command at least displays a warning

It can't because it doesn't know there's a problem at install time.

> I did try brew reinstall many times and it did nothing.

You will need to be more specific about exactly what commands you ran, what permissions your `/usr/local`, `/usr/local/var`, `/usr/local/var/log` have and what version everything was at when you run `brew reinstall`.

**Comment by hyperknot** [comment]
OK, here are the permissions right now, on a working system:

`/usr/local`: `drwxr-xr-x   13 root  wheel`
`/usr/local/var`: `drwxrwxr-x   8 user  admin`
`/usr/local/var/log`: `drwxr-xr-x  4 user  admin`

Let's reproduce the broken log folder with the steps I've written in my previous post:

```
brew services stop redis
rm -rf /usr/local/var/log
brew services start redis
brew services stop redis
```

`/usr/local`: `drwxr-xr-x   13 root  wheel`
`/usr/local/var`: `drwxrwxr-x   8 user  admin`
`/usr/local/var/log`: `drwxr--r--  2 root  admin`

Reinstall log:

```
brew reinstall redis
==> Reinstalling redis
==> Downloading https://homebrew.bintray.com/bottles/redis-3.2.9.el_capitan.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/redis-3.2.9.el_capitan.bottle.tar.gz
==> Pouring redis-3.2.9.el_capitan.bottle.tar.gz
==> Using the sandbox
==> Caveats
To have launchd start redis now and restart at login:
  brew services start redis
Or, if you don't want/need a background service you can just run:
  redis-server /usr/local/etc/redis.conf
==> Summary
🍺  /usr/local/Cellar/redis/3.2.9: 13 files, 1.7MB
```

```
brew services start redis
==> Successfully started `redis` (label: homebrew.mxcl.redis)

redis-cli ping
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

**Comment by MikeMcQuaid** [comment]
You need to stop the services, remove the directory, reinstall redis, confirm that `/usr/local/var/log` exists and is owned by the correct user and start the service.

**Comment by hyperknot** [comment]
@MikeMcQuaid yes, sure, that's how I'm fixing it. What I'm trying to say is that the install script should check it and display a warning that it cannot start with root owned directory.

**Comment by MikeMcQuaid** [comment]
@hyperknot I mean: the `brew reinstall` should create that directory owned by the correct user if the service is stopped. Can you confirm that is the case?

> What I'm trying to say is that the install script should check it and display a warning that it cannot start with root owned directory.

It cannot check a directory that is used only in the plist. As said above: this should be fixed by `brew reinstall` with the service stopped and directory removed. If it is not: that's a bug. If it is: we consider this bug fixed.

**Comment by hyperknot** [comment]
If the directory does not exists, reinstall creates it.
If the directory does exists, with wrong permissions, reinstall just silently skips is. This results in the broken service.

Why can it not check permissions if it knows how to create it?

**Comment by MikeMcQuaid** [comment]
> Why can it not check permissions if it knows how to create it?

Because some people want to use custom permissions and this change would break it for them. The real bug here was that `var/log` didn't used to be created which caused this problem. It's annoying but I'm glad you've resolved this.

**Comment by hyperknot** [comment]
OK, at least this thread is here so if anyone runs into an issue they can Google it.
