### ISSUE TITLE
ansible 2.3.1 ImportError: No module named __future__

### ISSUE THREAD

**Issue by danielgriggs** [Homebrew/homebrew-core#14216]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
```bash
brew upgrade ansible 2.3.0.0_2 -> 2.3.1.0
```

- What happened (include command output)
```bash
ansible --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible", line 21, in <module>
    from __future__ import (absolute_import, division, print_function)
ImportError: No module named __future__
```
- What you expected to happen
```bash
Ansible to continue working.
```

- Step-by-step reproduction instructions (by running `brew install` commands)
```bash
brew install ansible
this causes Ansible to not work.

brew switch ansible 2.3.0.0_2
returns Ansible to normal service.
```

**Comment by tdsmith** [comment]
Can you share this, please?

> If brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

Is there a chance you're running a stale version of brew—maybe you have an old feature branch checked out? We shipped a fix for a similar problem recently. Also, what are the contents of /usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/orig-prefix.txt?

**Comment by danielgriggs** [comment]
The contents of is /usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/orig-prefix.txt
```
@@HOMEBREW_PREFIX@@/opt/python/Frameworks/Python.framework/Versions/2.7
```
I believe I am running the correct version of Homebrew
```
$ pwd
/usr/local/Homebrew
$ git status
On branch stable
nothing to commit, working tree clean
```

**Comment by tdsmith** [comment]
I guess we haven't cut a release yet that includes Homebrew/brew#2598, which I ought to have realized we needed to do. test-bot runs master and knows this file needs to be relocated but `brew` doesn't. cc @MikeMcQuaid

**Comment by ilovezfs** [comment]
That's not what I am seeing:
```
iMac-TMP:Homebrew joe$ git status
HEAD detached at 1.2.1
nothing to commit, working tree clean
iMac-TMP:Homebrew joe$ brew install ansible
==> Downloading https://homebrew.bintray.com/bottles/ansible-2.3.1.0.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/ansible-2.3.1.0.el_capitan.bottle.tar.gz
==> Pouring ansible-2.3.1.0.el_capitan.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/ansible/2.3.1.0: 11,346 files, 124.4MB
iMac-TMP:Homebrew joe$ cat /usr/local/opt/ansible//libexec/lib/python2.7/orig-prefix.txt
/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7iMac-TMP:Homebrew joe$ 
iMac-TMP:Homebrew joe$ cat /usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/orig-prefix.txt
/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7iMac-TMP:Homebrew joe$ 
iMac-TMP:Homebrew joe$ 
```

**Comment by ilovezfs** [comment]
@danielgriggs please follow all of the issue template and run the gist-logs, config, and doctor steps, and post output. Thanks!

**Comment by danielgriggs** [comment]
Output of the commands in the following pastebin

https://pastebin.com/RkSEsCYG

**Comment by ilovezfs** [comment]
Yes, this is why we ask for the issue template to be completed:
```
HOMEBREW_VERSION: 1.0.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 817bc2746e594761911edd78f743a640f089494f
Last commit: 8 months ago
```

That is going to be a bit of a problem.

Please try
```
brew update --force
```
and then post output of `brew config` again. Thanks!

**Comment by danielgriggs** [comment]
Sorry, same thing.

SailorTheParrot:Homebrew daniel$ brew update --force
Already up-to-date.
SailorTheParrot:Homebrew daniel$ brew config
HOMEBREW_VERSION: 1.0.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 817bc2746e594761911edd78f743a640f089494f
Last commit: 8 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d60315504bc17e994bd97464725aaadb59387e4
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
SailorTheParrot:Homebrew daniel$ cd /usr/local/Homebrew/
SailorTheParrot:Homebrew daniel$ git status
On branch stable
nothing to commit, working tree clean
SailorTheParrot:Homebrew daniel$

**Comment by ilovezfs** [comment]
Yup. OK, time to try
```
brew update-reset
```
and then `brew config` again.

**Comment by danielgriggs** [comment]
Sorry I checked the FAQ and did the following.

git fetch origin
SailorTheParrot:Homebrew daniel$ git reset --hard FETCH_HEAD
HEAD is now at a4aacbc15e Merge pull request #2699 from mistydemeo/fix_boolean_types
SailorTheParrot:Homebrew daniel$ cd ..
SailorTheParrot:local daniel$ brew update
Already up-to-date.
SailorTheParrot:local daniel$ brew config
HOMEBREW_VERSION: 1.2.1-179-ga4aacbc15e
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a4aacbc15eecb9bb2fc67ab2a70f0e3d35020ba3
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d60315504bc17e994bd97464725aaadb59387e4
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
SailorTheParrot:local daniel$ brew uninstall ansible
Uninstalling /usr/local/Cellar/ansible/2.3.1.0... (11,360 files, 124.5MB)
SailorTheParrot:local daniel$ brew install ansible
==> Downloading https://homebrew.bintray.com/bottles/ansible-2.3.1.0.sierra.bottle.tar.gz
Already downloaded: /Users/daniel/Library/Caches/Homebrew/ansible-2.3.1.0.sierra.bottle.tar.gz
==> Pouring ansible-2.3.1.0.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/ansible/2.3.1.0: 11,346 files, 124.3MB
SailorTheParrot:local daniel$ ansible --version
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
SailorTheParrot:local daniel$

Which seems to have fixed the problem.
Sorry for the noise and thanks for the help.
I'm not sure how it's getting out of sync like that, I do updates && upgrades fairly regularly.

**Comment by ilovezfs** [comment]
Yeah, your not on stable now, though :(

```
git -C $(brew --repo) reset --hard HEAD^
export HOMEBREW_UPDATE_TO_TAG="1"
brew update
```
and then post `brew config`

**Comment by danielgriggs** [comment]
SailorTheParrot:local daniel$ brew config
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0d60315504bc17e994bd97464725aaadb59387e4
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
SailorTheParrot:local daniel$

**Comment by ilovezfs** [comment]
Much better!

Now please make sure that `brew uninstall ansible; brew install ansible` still results in a correct installation.

**Comment by danielgriggs** [comment]
SailorTheParrot:local daniel$ brew uninstall ansible; brew install ansible
Uninstalling /usr/local/Cellar/ansible/2.3.1.0... (11,522 files, 126.4MB)
==> Downloading https://homebrew.bintray.com/bottles/ansible-2.3.1.0.sierra.bottle.tar.gz
Already downloaded: /Users/daniel/Library/Caches/Homebrew/ansible-2.3.1.0.sierra.bottle.tar.gz
==> Pouring ansible-2.3.1.0.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/ansible/2.3.1.0: 11,346 files, 124.3MB
SailorTheParrot:local daniel$ ansible --version
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
SailorTheParrot:local daniel$

Yep still seems to be working.

**Comment by ilovezfs** [comment]
Cool. I think we can close this out :)
