### ISSUE TITLE
Tracking issue for Sonoma bottling

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#142161]
🔗 Automated tracker: https://mass-bottling-manager.nw.r.appspot.com

This will serve as tracking issue to gather Sonoma bottling info. This first post can be edited, with a summary of the high-profile failures and issues. The bottling job results will be posted as comments below.

----

Remaining non-deprecated/disabled (skipping some that may be missing Ventura bottles):

## Remaining:
- [ ] `libchaos` - #182806
- [ ] `sextractor` - #181246
- [ ] `hashcat` - OpenCL on ARM VM - #181921

## Blocked. Moved to tracking in #139929
- `sn0int` - Blocked due to Rust bump
- `tremor-runtime` - Blocked due to Rust bump
- `ipmiutil` - SHA256 mismatch
- `khiva` - not compatible with newer `arrayfire`

**Comment by Moisan** [comment]
> ❌ @fxcoudert bottle request for nmap [failed](https://github.com/Homebrew/homebrew-core/actions/runs/6182181209).
> 
> ```
>   In file included from charpool.cc:70:
>   In file included from ./charpool.h:66:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/vector:3359:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/algorithm:1913:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/chrono:746:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__chrono/convert_to_tm.h:19:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__chrono/statically_widen.h:17:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__format/concepts.h:17:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__format/format_parse_context.h:15:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/string_view:1027:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/functional:515:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__functional/boyer_moore_searcher.h:24:
>   In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/array:124:
>   ./libpcap/version:1:1: error: expected unqualified-id
>   1.10.4
>   ^
> ```

This is similar to [this nmap issue](https://github.com/nmap/nmap/issues/1586) although I'm not sure if the fix should be in our formula or coming from  the toolchain.

**Comment by SMillerDev** [comment]
It really shouldn't build it's own libpcap though since brew has one, and there is one in macOS.

**Comment by ZhongRuoyu** [comment]
:x: @ZhongRuoyu bottle request for clutter [failed](https://github.com/Homebrew/homebrew-core/actions/runs/6257889763).

(Sorry, I forgot to add `--issue` to `brew dispatch-build-bottle`. 😅)

**Comment by ZhongRuoyu** [comment]
:x: @ZhongRuoyu bottle request for gtkglext [failed](https://github.com/Homebrew/homebrew-core/actions/runs/6257891200).

```
  gdkglpixmap-quartz.c:146:2: error: call to undeclared function 'gdk_drawable_get_size'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          gdk_drawable_get_size (GDK_DRAWABLE (pixmap), &width, &height);
          ^
  gdkglpixmap-quartz.c:247:2: error: call to undeclared function 'gdk_draw_pixbuf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          gdk_draw_pixbuf(pixmap,
          ^
```

**Comment by yurikoles** [comment]
Will formula automatically upgrade if there is no other changes except appearance of Sonoma bottle?

**Comment by cho-m** [comment]
I added some that need upstream work to #139929 and others have open PRs. Going to close this as complete as bottling effort moves to Sequoia.

Everything else seems to be `deprecated!` / `disabled!` / `maximum_macos` / `:linux` / also fails on Ventura.
