### ISSUE TITLE
bazel.rb is for 0.4.5 and not 0.5.0

### ISSUE THREAD

**Issue by Gadgeteering** [Homebrew/homebrew-core#14220]
Installation instructions for Bazel for 0.5.0 below:
[https://bazel.build/versions/master/docs/install-os-x.html#install-on-mac-os-x-homebrew(url)

tell you to use brew install bazel to install version 0.5.0 but this file details version 0.4.5

**Comment by ilovezfs** [comment]
Yes, upstream requested a revert of 0.5.0. They'll post an 0.5.1 soon and then it'll be upgraded in Homebrew again.

**Comment by paladox** [comment]
@ilovezfs hi, bazel 0.5.1 was released with the regression fix. Can homebrew be updated to 0.5.1 please?

https://groups.google.com/forum/m/#!topic/bazel-discuss/p9rMMblGDsg

**Comment by ilovezfs** [comment]
@paladox sure: https://github.com/Homebrew/homebrew-core/pull/14299

**Comment by paladox** [comment]
Thanks.
