### ISSUE TITLE
Build v8@3.15 with libc++ instead of libstdc++6

### ISSUE THREAD

**Issue by jeroen** [Homebrew/homebrew-core#14230]
My application builds with xcode on osx 10.11 and links against `v8@3.15`. Everything builds however there are some runtime problems with c++ exceptions because `v8@3.15` is built against `libstdc++6` but my application uses `libc++`.

```
> otool -L /usr/local/opt/v8@3.15/lib/libv8.dylib
/usr/local/opt/v8@3.15/lib/libv8.dylib:
	/usr/local/opt/v8@3.15/lib/libv8.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 489.0.0)

> otool -L /usr/local/opt/v8/lib/libv8.dylib
/usr/local/opt/v8/lib/libv8.dylib:
	/usr/local/opt/v8/lib/libv8.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

Would there be a way to build `v8@3.15` with `libc++` instead? The `v8` formula already uses `libc++` but unfortunately it has a completely different API then `v8@3.15` so upgrading is not an option.

**Comment by jeroen** [comment]
Same problem as https://github.com/nodejs/node-gyp/issues/469. Looks like old versions of gyp default to building a lib that is compatible with `OSX < 10.7` which is when clang was still using `libstdc++`.

They say that the problem can be fixed by passing `-mmacosx-version-min` or setting:

               'xcode_settings': {
                  'MACOSX_DEPLOYMENT_TARGET':'10.9'
                }

But I am not sure how to do this in homebrew.

**Comment by ilovezfs** [comment]
@jeroen do you mind testing if the lines @DomT4 linked to work as well?
