### ISSUE TITLE
error: parent file not sticky

### ISSUE THREAD

**Issue by nrj53** [Homebrew/homebrew-core#14241]
Just installed homebrew on macbook pro 10.12.5.  Then tried to install get_iplayer and this script came up in Terminal, telling me to report the bug.  As a result get i_player does not install.  I did not see this as an issue, but I'm sorry if it is already known.

==> Installing get_iplayer from dinkypumpkin/get_iplayer
==> Downloading https://github.com/get-iplayer/get_iplayer/archive/v3.01.tar.gz
Already downloaded: /Users/Ross/Library/Caches/Homebrew/get_iplayer-3.01.2.tar.gz
==> Downloading https://cpan.metacpan.org/authors/id/P/PE/PEVANS/IO-Socket-IP-0.
Already downloaded: /Users/Ross/Library/Caches/Homebrew/get_iplayer--IO::Socket::IP-0.39.tar.gz
==> perl Makefile.PL INSTALL_BASE=/usr/local/Cellar/get_iplayer/3.01.2/libexec
==> make install
==> Downloading https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.31.t
Already downloaded: /Users/Ross/Library/Caches/Homebrew/get_iplayer--Mojolicious-7.31.tar.gz
==> perl Makefile.PL INSTALL_BASE=/usr/local/Cellar/get_iplayer/3.01.2/libexec
==> make install
Error: parent directory is world writable but not sticky
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:658:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:312:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:207:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:205:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'

**Comment by ilovezfs** [comment]
What does `brew doctor` say?

**Comment by MikeMcQuaid** [comment]
And `brew config`.

**Comment by nrj53** [comment]
Ran brew doctor ( I did not know about it) and this was the result:

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libFLAC.8.dylib
  /usr/local/lib/libiconv.2.dylib
  /usr/local/lib/libogg.0.dylib

Warning: /tmp is world-writable but does not have the sticky bit set.
Please execute `sudo chmod +t /tmp` in your Terminal.
 
So I ran the command suggested in the last line and that warning disappeared when I re-ran brew doctor.  The dylib warnings still came up,  but get_iplayer installed anyway.

Thanks for the help.

**Comment by ilovezfs** [comment]
You're welcome! Glad you got it sorted.
