### ISSUE TITLE
`fortune` missing "off" file

### ISSUE THREAD

**Issue by shawnyeager** [Homebrew/homebrew-core#142442]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs fortune                                                                      
Error: No logs.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run `fortune -a` to see all fortunes, including those categorized as "offensive."

### What happened (include all command output)?

```
❯ fortune -a                                                                                 
/opt/homebrew/Cellar/fortune/9708/share/games/fortunes/off: No such file or directory
```

### What did you expect to happen?

To see a fortune

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install fortune
fortune -a
```

**Comment by nandahkrishna** [comment]
This is not a bug, the offensive quotes were intentionally removed in #61706 (see https://github.com/Homebrew/brew/issues/8811) as their content violates Homebrew's Code of Conduct. You can refer to the advice in https://github.com/Homebrew/homebrew-core/pull/61706#issuecomment-751291566 if you still want this functionality -- host a version of the formula in a custom tap with this feature enabled.
