### ISSUE TITLE
coreutils manpage not recognized by touchbar

### ISSUE THREAD

**Issue by monouser7dig** [Homebrew/homebrew-core#14262]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

```
$ brew config
HOMEBREW_VERSION: 1.2.2-2-gb9cfd2cb
ORIGIN: https://github.com/Homebrew/brew
HEAD: b9cfd2cb58a2f360dadf691dc3eeaf22b694e960
Last commit: 85 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d4d47e537962f1f41c39ab82b55ae84d1d41183d
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_131
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

To help us debug your issue please explain:
- tried to get the man page of a formula
- the BSD page was shown when using the touchbar
- the GNU man page, like when running `man ls`, `ls --version` also shows that the GNU version is used correctly, just the touchbar manpage does not connect to the new man page installed by brew
- all coreutils exhibit this behavior 

please let me know if I can make any other additions to make debugging easier

thank you very much

**Comment by dunn** [comment]
Does this happen for only coreutils, or for all Homebrew-installed manpages?

**Comment by monouser7dig** [comment]
e.g. wget/ stop behave just fine

gg-7/ youtube-dl behave interestingly 
```
No manual entry for gcc
```

bash 4.4 does not work, just shows the 3.2 man page using the touchbar
