### ISSUE TITLE
node@v4 installs npm v5.0.1 when it should be npm v2.15.11

### ISSUE THREAD

**Issue by richardhills** [Homebrew/homebrew-core#14269]
Here's the change a few days ago:

https://github.com/Homebrew/homebrew-core/commit/dc6b5f7fa52893f3d908a738f22f0521410edc3f

Here's the list of npm versions for each version of node:

https://nodejs.org/en/download/releases/

**Comment by ilovezfs** [comment]
This is intentional so that it does not overwrite the npm installed by the primary node formula with a different version.

See
https://github.com/Homebrew/brew/issues/2240
https://github.com/Homebrew/homebrew-core/pull/10601
https://github.com/Homebrew/homebrew-core/pull/10600
