### ISSUE TITLE
CANU installation from Homebrew Science

### ISSUE THREAD

**Issue by LordGenome** [Homebrew/homebrew-core#14274]
iMac:barcode01 gtaylor$ poretools fastq --min-length 4975 --max-length 5025 batch_1491401999766/ >>bc01.fastq
iMac:barcode01 gtaylor$ canu -p bc01 -d bc01 -nanopore-raw bc01.fastq genomeSize=5k  minReadLength=4500
--   Reason: image not found
-- Detected Java(TM) Runtime Environment '1.8.0_101' (from 'java').
-- Detected gnuplot version '5.0 patchlevel 6' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 32 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
-- Run   2 jobs concurrently using    8 GB and   4 CPUs for stage 'meryl'.
-- Run   1 job  concurrently using    6 GB and   8 CPUs for stage 'mhap (cor)'.
-- Run   1 job  concurrently using    8 GB and   8 CPUs for stage 'overlapper (obt)'.
-- Run   1 job  concurrently using    8 GB and   8 CPUs for stage 'overlapper (utg)'.
-- Run   4 jobs concurrently using    8 GB and   2 CPUs for stage 'falcon_sense'.
-- Run   8 jobs concurrently using    4 GB and   1 CPU  for stage 'ovStore bucketizer'.
-- Run   8 jobs concurrently using    8 GB and   1 CPU  for stage 'ovStore sorting'.
-- Run   2 jobs concurrently using    2 GB and   4 CPUs for stage 'read error detection'.
-- Run   8 jobs concurrently using    1 GB and   1 CPU  for stage 'overlap error adjustment'.
-- Run   2 jobs concurrently using   16 GB and   4 CPUs for stage 'bogart'.
-- Run   8 jobs concurrently using    4 GB and   1 CPU  for stage 'GFA alignment and processing'.
-- Run   2 jobs concurrently using   16 GB and   4 CPUs for stage 'consensus'.
--
-- Generating assembly 'bc01' in '/Users/gtaylor/Desktop/run1_barcodes/barcode01/bc01'
--
-- Parameters:
--
--  genomeSize        5000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1440 ( 14.40%)
--
--
-- BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Mon Jun  5 18:48:43 2017 with 1283.963 GB free disk space

    cd correction
    /usr/local/Cellar/canu/1.5/Darwin-amd64/bin/gatekeeperCreate \
      -minlength 4500 \
      -o ./bc01.gkpStore.BUILDING \
      ./bc01.gkpStore.gkp \
    > ./bc01.gkpStore.BUILDING.err 2>&1
sh: line 4: 69363 Trace/BPT trap: 5       /usr/local/Cellar/canu/1.5/Darwin-amd64/bin/gatekeeperCreate -minlength 4500 -o ./bc01.gkpStore.BUILDING ./bc01.gkpStore.gkp > ./bc01.gkpStore.BUILDING.err 2>&1

-- Finished on Mon Jun  5 18:48:43 2017 (lickety-split) with 1283.963 GB free disk space
----------------------------------------
ERROR:
ERROR:  Failed with exit code 133.  (rc=34048)
ERROR:
================================================================================
Don't panic, but a mostly harmless error occurred and Canu stopped.

  Reason: image not found failed with:
  gatekeeper store exists, but contains no reads

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by LordGenome** [comment]
Sorry, will revise with template tomorrow.

Graham
