### ISSUE TITLE
coreutils formula: incorrect $MANPAGES instructions

### ISSUE THREAD

**Issue by aristidesfl** [Homebrew/homebrew-core#14273]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0828f4ffd611b6461838d877ab5e1bf8904ffad4
Core tap last commit: 24 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/user/.rbenv/shims/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```
To help us debug your issue please explain:
- What you were trying to do (and why)
Getting man to show manpages for the coreutils package.

- What happened (include command output)
man only finds pages from `/usr/local/opt/coreutils/libexec/gnuman`, and not for other commands
```bash
$ man git
No manual entry for git
```

- What you expected to happen
man should show documentation for all commands and for the coreutils packages

- Step-by-step reproduction instructions (by running `brew install` commands)
1. `brew install coreutils`
2. Set `$PATH` to `/usr/local/opt/coreutils/libexec/gnubin:$PATH`
3. Set `$MANPATH` to `/usr/local/opt/coreutils/libexec/gnuman:$MANPATH`

## Comments

Has `$MANPATH` been deprecated? It is empty by default, and adding a path to it, prevents man from finding other man pages. It seems that the instructions in https://github.com/Homebrew/homebrew-core/blob/d1c2a2726ddfcaaa6a849e06307302aa2d3c9c55/Formula/coreutils.rb#L104-L115 might need to be updated to use another method of configuring man pages.

One possible way to configure them could be adding the following to `/etc/man.conf`:
```
MANPATH_MAP /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/coreutils/libexec/gnuman
```

The formula could probably add this line automatically, since it works concurrently with system default coreutils even if `/usr/local/opt/coreutils/libexec/gnubin` isn't added to `$PATH`.

Related: https://github.com/Homebrew/homebrew-core/issues/14262
@adamv @netj

**Comment by monouser7dig** [comment]
```
echo $MANPATH
/usr/local/opt/findutils/libexec/gnuman:/usr/local/opt/coreutils/libexec/gnuman:
```
```
echo $MANPATH_MAP
```
is empty

adding
```
MANPATH_MAP /usr/local/opt/coreutils/libexec/gnubin /usr/local/opt/coreutils/libexec/gnuman
```
does not seem to solve the issue yet

**Comment by aristidesfl** [comment]
@monouser7dig both `echo $MANPATH` and `echo $MANPATH_MAP` should print nothing.

**Comment by monouser7dig** [comment]
```
Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
```
thus MANPATH should not print nothing otherwise `man ls` would not work either

**Comment by aristidesfl** [comment]
@monouser7dig man has other mechanisms for finding pages. setting `$MANPATH` overrides them and prevents man from working correctly.

**Comment by monouser7dig** [comment]
so then the install instructions are somewhat confusing

**Comment by aristidesfl** [comment]
@monouser7dig have you read the this issue?

**Comment by JCount** [comment]
> The formula could probably add this line automatically, since it works concurrently with system default coreutils ...

This is not possible, as I see it. The largest issue is the fact that the default ownership and default permissions of /etc/man.conf are root:wheel 644, meaning it would take elevated permissions to modify the file.

**Comment by netj** [comment]
@JCount @aristidesfl There is `/etc/manpaths.d/` which is probably easier to work with, except it may be difficult to insert before the ones in `/etc/manpaths`.

I haven't fully digested what this error is about since it's been working fine for me since I introduced the trick to the formula. (Has a new thing been introduced in macOS that clears `MANPATH`?  I still have them set in my shell, maybe because my dotfiles always run `/usr/libexec/path_helper -s`...)  Anyway, I'll see if I can guess what's going on in others' Macs without my dotfiles and look for a nice fix when I find some time later this week.

**Comment by MikeMcQuaid** [comment]
We're not ever going to modify anything outside of the Homebrew prefix automatically and would like to avoid ever recommend making changes to `/etc` which is a system rather than Homebrew or user directory.
