### ISSUE TITLE
pgbouncer fails to listen to specified port on 10.12.5 when using brew services

### ISSUE THREAD

**Issue by nogurenn** [Homebrew/homebrew-core#14295]
I am trying to connect my django project to pgbouncer for connection pooling. So django connects to pgbouncer, and pgbouncer connects to postgre db. This is the accepted way of placing pgbouncer as the connection pooler between django and postgre.

I am running `brew services start/restart pgbouncer`, of which I'm getting the following confirmation.

```bash
Stopping `pgbouncer`... (might take a while)
==> Successfully stopped `pgbouncer` (label: homebrew.mxcl.pgbouncer)
==> Successfully started `pgbouncer` (label: homebrew.mxcl.pgbouncer)
```
I then run `lsof -i -P | grep "6432"` to find it but there's nothing. If I `grep "5432"` instead, my actual database shows up, so I know that the db itself is listening. The same behavior occurs even after `sudo`ing brew services.

`pgbouncer` only listens if I use its command like `pgbouncer /usr/local/etc/pgbouncer.ini`

```bash
~$ pgbouncer /usr/local/etc/pgbouncer.ini
2017-06-06 15:48:31.692 38998 LOG File descriptor limit: 4864 (H:-1), max_client_conn: 100, max fds possible: 190
2017-06-06 15:48:31.694 38998 LOG listening on 127.0.0.1:6432
2017-06-06 15:48:31.695 38998 LOG listening on unix:/tmp/.s.PGSQL.6432
2017-06-06 15:48:31.695 38998 LOG process up: pgbouncer 1.7.2, libevent 2.1.8-stable (kqueue), adns: evdns2, tls: OpenSSL 1.0.2l  25 May 2017
```

**Gists**
The troubleshooting steps and `brew gist-logs pgbouncer` didn't work. Here's the gist for `brew doctor` and `brew config`.
[brew doctor + brew config](https://gist.github.com/nogurenn/685206cec381c8ff9c7c4c5b4f919ce0)

`pgbouncer` config file
[pgbouncer.ini](https://gist.github.com/nogurenn/caeacb1d59f3c766c85590a14efe72e9)

**Comment by contra** [comment]
Yeah, this is an issue I'm having as well. I think it has something to do with the pgbouncer brew not setting up the right paths on install, so when you launch it there is an instant failure (no logs).
