### ISSUE TITLE
sdl2_image: proper linkage?

### ISSUE THREAD

**Issue by clobber** [Homebrew/homebrew-core#14293]
Question:

Should formulas that have 'recommended' dependencies and have pre-built (bottled) releases also be linking against their recommended dependencies?

The problem:

[sdl2_image](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl2_image.rb) has recommended dependencies of jpeg, libpng, libtiff, webp

But when I run `otool -L sdl2_image.dylib` or `brew linkage sdl2_image`, I find that it is only linked against sdl2 and not the other recommended dependencies. This is contrary to the older [sdl_image](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl_image.rb) from sdl 1.2.x which *is* linked against all its dependencies.

So, is the linkage for sdl2_image wrong or does sdl2_image instead try to use them at runtime? Can anyone that knows more about sdl2_image comment?

Without being linked against its recommended dependencies, it is difficult to use `otool` and `install_name_tool` to make redistributable app bundles using this library.

**Comment by MikeMcQuaid** [comment]
> Should formulas that have 'recommended' dependencies and have pre-built (bottled) releases also be linking against their recommended dependencies?

If they link against them when built from source they should do so when installed from the bottle, yes.

**Comment by ilovezfs** [comment]
@clobber this should take care of it: https://github.com/Homebrew/homebrew-core/pull/14315

**Comment by clobber** [comment]
@ilovezfs Thank you! I had just looked at the makefile and noticed they are dynamically loaded by default, but for Homebrew purposes they should probably be linked or at least have the option. Looks like you handled that. Does the 'revision' for that formula also need to be bumped after that change?

**Comment by ilovezfs** [comment]
You're welcome. Since the current bottles are not technically broken, I think just pulling the new bottles is enough.
