### ISSUE TITLE
brew install v8@3.15 is failing besides having python2 

### ISSUE THREAD

**Issue by prakashfw** [Homebrew/homebrew-core#142925]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

HOMEBREW_VERSION: 4.1.11-36-g184efd9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 184efd9eabcb116ffa244a9ccaeeff39eee1ece2
Last commit: 9 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7ea36b10e579baee5c7f9331205a5c6e3065cb1f
Core tap last commit: 3 months ago
Core tap branch: master
Core tap JSON: 15 Sep 16:42 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.3 build 1403
Git: 2.39.0 => /usr/local/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3.1-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A

brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  openssl@3

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install python@3.11

Run `brew missing` for more details.

cegprakash@FWS-CHE-LT-5010 my_project % brew install v8@3.15
Error: v8@3.15 has been disabled because it depends on Python 2 to build!
cegprakash@FWS-CHE-LT-5010 my_project % python --version
Python 2.7.18rc1
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

cegprakash@FWS-CHE-LT-5010 my_project % brew --version
Homebrew 4.1.11-36-g184efd9

cegprakash@FWS-CHE-LT-5010 my_project % python --version
Python 2.7.18rc1

cegprakash@FWS-CHE-LT-5010 my_project % openssl version
OpenSSL 1.1.1u  30 May 2023

I'm trying this command 
`brew install v8@3.15`

Already reported few days back here: https://github.com/Homebrew/homebrew-core/issues/135150 but I missed to provide the brew config and brew doctor results.

### What happened (include all command output)?

Error: v8@3.15 has been disabled because it depends on Python 2 to build!

### What did you expect to happen?

v8 to be installed.. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
cegprakash@FWS-CHE-LT-5010 my_project % brew install v8@3.15
```

**Comment by Bo98** [comment]
We won't be supporting v8@3.15 anymore - the disabled message is an indication of the end of support. It is over 10 years old and we can't support everything forever. If you still need it, it would be best suited for you to copy the formula and maintain it in your own tap. It will likely need tweaking to pick up Pythons installed in arbitrary places outside of Homebrew, or potentially make it depend on a Python 2 formula that some tap somewhere probably offers.
