### ISSUE TITLE
nginx --with-passenger failed to build on 10.11

### ISSUE THREAD

**Issue by cjlarose** [Homebrew/homebrew-core#143]
brew gist-logs nginx

https://gist.github.com/cjlarose/0f9c13005ea03376b51e04381a9078a8

I can `brew install nginx` just fine, but `brew install nginx --with-passenger` seems to hang indefinitely on `make install`.

**Comment by DomT4** [comment]
Try again after a `brew update`. We suspect this was solved via https://github.com/Homebrew/brew/commit/d7aa0c0335dd67e4151503f3a29d7089c57059c3.

**Comment by cjlarose** [comment]
It works! Thanks!
