### ISSUE TITLE
Sshfs

### ISSUE THREAD

**Issue by rbf22** [Homebrew/homebrew-core#14320]
# Please always follow these steps:
- [ Y] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ Y] Ran `brew update` and retried your prior step?
- [ Y] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why) brew install sshfs
- What happened (include command output) nothing - just errors
dyld: Library not loaded: /usr/local/lib/libosxfuse.2.dylib
  Referenced from: /usr/local/bin/sshfs
  Reason: Incompatible library version: sshfs requires version 12.0.0 or later, but libosxfuse.2.dylib provides version 10.0.0
Abort trap: 6

- What you expected to happen
something without errors
- Step-by-step reproduction instructions (by running `brew install` commands)

brew install sshfs
sshfs

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by ilovezfs** [comment]
It sounds like you do not have osxfuse installed.

```
brew cask install osxfuse
```

**Comment by nawa** [comment]
Try to upgrade `osxfuse` from your MacOS Preferences
