### ISSUE TITLE
node@6 uses too new npm to be usable as LTS

### ISSUE THREAD

**Issue by atamanroman** [Homebrew/homebrew-core#14361]
I'm very surprised that `node@6` just upgraded to npm 5. This breaks a lot of builds. I expected `node@6` to behave similarly to the node 6 LTS schedule.

The [node@6](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@6.rb) formula uses npm 5 (just jumped from 4), while the original node 6 LTS package still uses npm 3. The LTS versions don't allow major version jumps in their included npm.

This may be a misunderstanding on my side. Could anybody please clarify how `node@6` should behave an whether there is any formula which is roughly equivalent to `node-6-lts`?

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/14269.

You can npm install whichever version you'd like after brew installing node@6. The reason for the behavior is that we do not want to downgrade anyone who does `brew install node` first and then `brew install node@6` from npm 5 to something else.
