### ISSUE TITLE
Sitecopy formula missing (existed in legacy-homebrew)

### ISSUE THREAD

**Issue by stefanhaller** [Homebrew/homebrew-core#14460]
In legacy-homebrew there was a `sitecopy` formula; it was added in 2010, see https://github.com/Homebrew/legacy-homebrew/issues/581. The relevant commits are https://github.com/Homebrew/legacy-homebrew/commit/2234784bdf7085f3d4dbb678296a47dddd0d6d19 and https://github.com/Homebrew/legacy-homebrew/commit/6a002ea17bfb09387f4a92ce9fb6c37737157571.

It is missing in homebrew-core though, so I'm wondering if it somehow got lost in the transition.

Would you like me to create a PR with the latest state of the formula from legacy-homebrew?

**Comment by ilovezfs** [comment]
This was removed from Homebrew in 2015 in https://github.com/Homebrew/legacy-homebrew/pull/36389 where the reasons are listed.
```
iMac-TMP:~ joe$ brew install sitecopy
Error: No available formula with the name "sitecopy" 
==> Searching for a previously deleted formula...
sitecopy was deleted from homebrew/core in commit 36e1ffe:
  sitecopy: boneyarding
  Sitecopy currently compiles against the insecure system OpenSSL, and
  won’t compile against our OpenSSL because it wants SSLv2 at runtime
  (Ouch) and it won’t compile against GnuTLS because GnuTLS have
  considerably changed the structure of their build since the last update
  of sitecopy (2008).
  Closes Homebrew/homebrew#36389.
  Signed-off-by: Jack Nagel <jacknagel@gmail.com>

To show the formula before removal run:
  git -C "$(brew --repo homebrew/core)" show 36e1ffe^:Formula/sitecopy.rb

If you still use this formula consider creating your own tap:
  http://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
```
