### ISSUE TITLE
Dmd

### ISSUE THREAD

**Issue by ChrisG0x20** [Homebrew/homebrew-core#14464]
Description: Brew installs the wrong version of DMD.

Reproduction steps:
1. In the terminal: brew install dmd
Note the output:
==> Pouring dmd-**2.074.1**.sierra.bottle.tar.gz
==> Using the sandbox
/usr/local/Cellar/dmd/**2.074.1**: 587 files, 67MB

2. In the terminal: dmd --version

Result:
DMD64 D Compiler **v2.074.0**

Expected:
DMD64 D Compiler v2.074.1

**Comment by ilovezfs** [comment]
This is an upstream issue: https://github.com/dlang/dmd/blob/v2.074.1/VERSION

Please report it to them here if it concerns you: https://issues.dlang.org
