### ISSUE TITLE
psql fails connecting to Amazon Redshift

### ISSUE THREAD

**Issue by Cornellio** [Homebrew/homebrew-core#144671]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew info libpq
==> libpq: stable 16.0 (bottled) [keg-only]
Postgres C API library
https://www.postgresql.org/docs/current/libpq.html
/opt/homebrew/Cellar/libpq/16.0 (2,379 files, 29.5MB)
  Poured from bottle using the formulae.brew.sh API on 2023-09-21 at 15:59:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libpq.rb
License: PostgreSQL
==> Dependencies
Build: pkg-config ✔
Required: icu4c ✔, krb5 ✔, openssl@3 ✔


brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  exa

brew config
zsh: correct 'config' to '.config' [nyae]? n
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 5 days ago
Core tap JSON: 21 Sep 22:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.41.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.1-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am using the Postgres cli, psql to connect to an Amazon Redshift database. I installed psql using `brew install libpq`.

We have ruled out networking and Redshift cluster configuration as issues, as another engineer in our company can connect fine to the same Redshift cluster while another user who recently installed libpq via homebrew can reproduce the issue, as he gets the same error that I do.

I noticed in the commit history there was a recent switch to ssl@3. Perhaps this caused the problem. Our user who can connect to Redshift probably installed his package before this change.

### What happened (include all command output)?

It fails with the following error:

psql: error: connection to server at "npe-dw-redshift-mls1-20.xxxxxxxxx6622.us-west-2.redshift-serverless.amazonaws.com" (10.163.x.x), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

### What did you expect to happen?

I should connect to a database shell on the Redshift cluster.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libpq

which psql
/opt/homebrew/opt/libpq/bin/psql

psql -h endpoint.redshift-serverless.amazonaws.com -p 5432 -d dbname -U pcornell
```

**Comment by SMillerDev** [comment]
This really should be filed to the postgres project since we only package libpq and by the looks of it just build using standard configuration (since OpenSSL only has one supported version at this time)

**Comment by Cornellio** [comment]
The problem does not exist when using the current version of psql from the Postgres Mac installer package, as well as the one provided by EDB. Perhaps there is something else that changed in the Homebrew build that is breaking it? My comment about OpenSSL is just a guess.

**Comment by SMillerDev** [comment]
The people behind the Postgres project would probably have a very good idea about what it could be and can help you debug the issue. I for one have only used Postgres once in my life and don't have more reference than: it compiles and passes all tests and you're the first to complain.
