### ISSUE TITLE
Are constant high download rates (mainly from APPLE-WWNET) for "xz" tarball "normal"?

### ISSUE THREAD

**Issue by jschleus** [Homebrew/homebrew-core#14486]
**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

Ok, that is may risk but my problem is an "external" one: 

I am the maintainer of a server (fossies.org) offering FOSS software and especially some according add-on services. That server isn't an official  mirror server but nevertheless it's used by Homebrew for the "xz"-package, see:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/xz.rb

Today and yesterday I observed a little bit the traffic on that server and I found that roughly 3000 times a day the tarball "xz-5.2.3.tar.gz" was downloaded (roughly 3 GB/day) by clients with the User-Agent

```Homebrew/1.X.Y (Macintosh; Intel Mac OS X 10.13) curl/7.51.0```

In the Januar I found a similar traffic so there seem 1 million downloads per year to be expected (using 1 TB bandwidth anyhow).

Now my issue: 90-95% of the accesses came currently from IP addresses 17.111.x.x (a whois query says APPLE-WWNET Apple Inc.) all without DNS hostnames. Is the described behaviour normal, expected and explainable?

**Comment by MikeMcQuaid** [comment]
We have no idea whether this is normal or not, sorry. If you would like us to stop using fossies as a mirror let us know and we will do so, thanks!

**Comment by jschleus** [comment]
Hmm, stupid question or grumpy issuer? Nevertheless, I think Homebrew doesn't need fossies.org as a mirror so please stop using it if possible. Thanks.

**Comment by ilovezfs** [comment]
@jschleus we currently use fossies for quite a few
```
bind.rb
5:  mirror "https://fossies.org/linux/misc/dns/bind9/9.11.1/bind-9.11.1.tar.gz"

cdrtools.rb
8:    mirror "https://fossies.org/linux/misc/cdrtools-3.01.tar.bz2"
27:    mirror "https://fossies.org/linux/misc/cdrtools-3.02a07.tar.bz2"

chkrootkit.rb
5:  mirror "https://fossies.org/linux/misc/chkrootkit-0.51.tar.gz"

cronolog.rb
4:  url "https://fossies.org/linux/www/old/cronolog-1.6.2.tar.gz"

dialog.rb
5:  mirror "https://fossies.org/linux/misc/dialog-1.3-20170131.tgz"

dos2unix.rb
5:  mirror "https://fossies.org/linux/misc/dos2unix-7.3.4.tar.gz"

dovecot.rb
5:  mirror "https://fossies.org/linux/misc/dovecot-2.2.29.1.tar.gz"

e2fsprogs.rb
5:  mirror "https://fossies.org/linux/misc/e2fsprogs-1.43.4.tar.gz"

erlang.rb
35:    mirror "https://fossies.org/linux/misc/otp_doc_man_19.3.tar.gz"
41:    mirror "https://fossies.org/linux/misc/otp_doc_html_19.3.tar.gz"

expat.rb
5:  mirror "https://fossies.org/linux/www/expat-2.2.0.tar.bz2"

fcgi.rb
5:  url "https://fossies.org/linux/www/old/fcgi-2.4.0.tar.gz"

file-formula.rb
6:  mirror "https://fossies.org/linux/misc/file-5.31.tar.gz"

fltk.rb
4:  url "https://fossies.org/linux/misc/fltk-1.3.4-source.tar.gz"

freetds.rb
5:  mirror "https://fossies.org/linux/privat/freetds-1.00.43.tar.bz2"

go.rb
7:    mirror "https://fossies.org/linux/misc/go1.8.3.src.tar.gz"

go@1.7.rb
5:  mirror "https://fossies.org/linux/misc/go1.7.6.src.tar.gz"

icu4c.rb
5:  mirror "https://fossies.org/linux/misc/icu4c-58_2-src.tgz"

keychain.rb
5:  mirror "https://fossies.org/linux/privat/keychain-2.8.3.tar.bz2"

libcaca.rb
4:  url "https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz"

libmagic.rb
5:  mirror "https://fossies.org/linux/misc/file-5.31.tar.gz"

libraw.rb
5:  mirror "https://fossies.org/linux/privat/LibRaw-0.17.2.tar.gz"

libtiff.rb
5:  mirror "https://fossies.org/linux/misc/tiff-4.0.8.tar.gz"

midnight-commander.rb
5:  mirror "https://fossies.org/linux/misc/mc-4.8.19.tar.xz"

monit.rb
5:  mirror "https://fossies.org/linux/privat/monit-5.22.0.tar.gz"

mpich.rb
5:  mirror "https://fossies.org/linux/misc/mpich-3.2.tar.gz"

node@4.rb
35:    mirror "https://fossies.org/linux/misc/icu4c-58_2-src.tgz"

node@6.rb
42:    mirror "https://fossies.org/linux/misc/icu4c-58_2-src.tgz"

oath-toolkit.rb
5:  mirror "https://fossies.org/linux/privat/oath-toolkit-2.6.2.tar.gz"

pkg-config.rb
5:  mirror "https://fossies.org/linux/misc/pkg-config-0.29.2.tar.gz"

pstree.rb
8:  mirror "https://fossies.org/linux/misc/pstree-2.39.tar.gz"

pure-ftpd.rb
5:  mirror "https://fossies.org/linux/misc/pure-ftpd-1.0.46.tar.gz"

sane-backends.rb
6:  mirror "https://fossies.org/linux/misc/sane-backends-1.0.27.tar.gz"

sgrep.rb
7:  mirror "https://fossies.org/linux/misc/old/sgrep-1.94a.tar.gz"

source-highlight.rb
6:  mirror "https://fossies.org/linux/www/source-highlight-3.1.8.tar.gz"

tree.rb
5:  mirror "https://fossies.org/linux/misc/tree-1.7.0.tgz"

vsftpd.rb
5:  mirror "https://fossies.org/linux/misc/vsftpd-3.0.3.tar.gz"

wine.rb
97:    mirror "https://fossies.org/linux/misc/tiff-4.0.8.tar.gz"
143:    mirror "https://fossies.org/linux/www/libgd-2.2.4.tar.xz"
149:    mirror "https://fossies.org/linux/privat/libgphoto2-2.5.14.tar.bz2"
161:    mirror "https://fossies.org/linux/misc/sane-backends-1.0.27.tar.gz"

xvid.rb
4:  url "https://fossies.org/linux/misc/xvidcore-1.3.4.tar.gz"

xz.rb
6:  url "https://fossies.org/linux/misc/xz-5.2.3.tar.gz"

zabbix.rb
5:  mirror "https://fossies.org/linux/misc/zabbix-3.2.6.tar.gz"
Josephs-MacBook-Pro:Formula joe$ ag fossies.org
bind.rb
5:  mirror "https://fossies.org/linux/misc/dns/bind9/9.11.1/bind-9.11.1.tar.gz"

cdrtools.rb
8:    mirror "https://fossies.org/linux/misc/cdrtools-3.01.tar.bz2"
27:    mirror "https://fossies.org/linux/misc/cdrtools-3.02a07.tar.bz2"

chkrootkit.rb
5:  mirror "https://fossies.org/linux/misc/chkrootkit-0.51.tar.gz"

cronolog.rb
4:  url "https://fossies.org/linux/www/old/cronolog-1.6.2.tar.gz"

dialog.rb
5:  mirror "https://fossies.org/linux/misc/dialog-1.3-20170131.tgz"

dos2unix.rb
5:  mirror "https://fossies.org/linux/misc/dos2unix-7.3.4.tar.gz"

dovecot.rb
5:  mirror "https://fossies.org/linux/misc/dovecot-2.2.29.1.tar.gz"

e2fsprogs.rb
5:  mirror "https://fossies.org/linux/misc/e2fsprogs-1.43.4.tar.gz"

erlang.rb
35:    mirror "https://fossies.org/linux/misc/otp_doc_man_19.3.tar.gz"
41:    mirror "https://fossies.org/linux/misc/otp_doc_html_19.3.tar.gz"

expat.rb
5:  mirror "https://fossies.org/linux/www/expat-2.2.0.tar.bz2"

fcgi.rb
5:  url "https://fossies.org/linux/www/old/fcgi-2.4.0.tar.gz"

file-formula.rb
6:  mirror "https://fossies.org/linux/misc/file-5.31.tar.gz"

fltk.rb
4:  url "https://fossies.org/linux/misc/fltk-1.3.4-source.tar.gz"

freetds.rb
5:  mirror "https://fossies.org/linux/privat/freetds-1.00.43.tar.bz2"

go.rb
7:    mirror "https://fossies.org/linux/misc/go1.8.3.src.tar.gz"

go@1.7.rb
5:  mirror "https://fossies.org/linux/misc/go1.7.6.src.tar.gz"

icu4c.rb
5:  mirror "https://fossies.org/linux/misc/icu4c-58_2-src.tgz"

keychain.rb
5:  mirror "https://fossies.org/linux/privat/keychain-2.8.3.tar.bz2"

libcaca.rb
4:  url "https://fossies.org/linux/privat/libcaca-0.99.beta19.tar.gz"

libmagic.rb
5:  mirror "https://fossies.org/linux/misc/file-5.31.tar.gz"

libraw.rb
5:  mirror "https://fossies.org/linux/privat/LibRaw-0.17.2.tar.gz"

libtiff.rb
5:  mirror "https://fossies.org/linux/misc/tiff-4.0.8.tar.gz"

midnight-commander.rb
5:  mirror "https://fossies.org/linux/misc/mc-4.8.19.tar.xz"

monit.rb
5:  mirror "https://fossies.org/linux/privat/monit-5.22.0.tar.gz"

mpich.rb
5:  mirror "https://fossies.org/linux/misc/mpich-3.2.tar.gz"

node@4.rb
35:    mirror "https://fossies.org/linux/misc/icu4c-58_2-src.tgz"

node@6.rb
42:    mirror "https://fossies.org/linux/misc/icu4c-58_2-src.tgz"

oath-toolkit.rb
5:  mirror "https://fossies.org/linux/privat/oath-toolkit-2.6.2.tar.gz"

pkg-config.rb
5:  mirror "https://fossies.org/linux/misc/pkg-config-0.29.2.tar.gz"

pstree.rb
8:  mirror "https://fossies.org/linux/misc/pstree-2.39.tar.gz"

pure-ftpd.rb
5:  mirror "https://fossies.org/linux/misc/pure-ftpd-1.0.46.tar.gz"

sane-backends.rb
6:  mirror "https://fossies.org/linux/misc/sane-backends-1.0.27.tar.gz"

sgrep.rb
7:  mirror "https://fossies.org/linux/misc/old/sgrep-1.94a.tar.gz"

source-highlight.rb
6:  mirror "https://fossies.org/linux/www/source-highlight-3.1.8.tar.gz"

tree.rb
5:  mirror "https://fossies.org/linux/misc/tree-1.7.0.tgz"

vsftpd.rb
5:  mirror "https://fossies.org/linux/misc/vsftpd-3.0.3.tar.gz"

wine.rb
97:    mirror "https://fossies.org/linux/misc/tiff-4.0.8.tar.gz"
143:    mirror "https://fossies.org/linux/www/libgd-2.2.4.tar.xz"
149:    mirror "https://fossies.org/linux/privat/libgphoto2-2.5.14.tar.bz2"
161:    mirror "https://fossies.org/linux/misc/sane-backends-1.0.27.tar.gz"

xvid.rb
4:  url "https://fossies.org/linux/misc/xvidcore-1.3.4.tar.gz"

xz.rb
6:  url "https://fossies.org/linux/misc/xz-5.2.3.tar.gz"

zabbix.rb
5:  mirror "https://fossies.org/linux/misc/zabbix-3.2.6.tar.gz"
```

Is your request specific to xz or should we remove all of them?

**Comment by jschleus** [comment]
Thanks for that information. I had no knowledge of that long list. But only xz produces the high traffic probably since it's configured as a main url and not only as a mirror (derived from the Fossies traffic Homebrew seems to have 3000 or more new clients a day?) the other formulae using fossies.org produce only  some sporadic accesses (besides of pkg-config today with 300) and are so currently not a problem (xz also not dramatically but ...).

By the way some of the Fossies URLs in use are only still working since Fossies moves most packages in a legacy folder after a new package was released and let be the old (no longer visible) URL as a service still operable for some weeks (normally roughly 3 months; if frequently used also longer). 

Here a list of such Homebrew used URLs (two with a dead link):
```
old (2016-10-29): /linux/misc/chkrootkit-0.51.tar.gz
new (2017-03-16): /linux/misc/chkrootkit-0.52.tar.gz

old (2017-02-01): /linux/misc/dialog-1.3-20170131.tgz
new (2017-05-10): /linux/misc/dialog-1.3-20170509.tgz

old (2017-04-12): /linux/misc/dovecot-2.2.29.1.tar.gz
new (2017-06-06): /linux/misc/dovecot-2.2.30.2.tar.gz

old (2017-05-23; NOT available on Fossies): /linux/misc/go1.7.6.src.tar.gz
new (2017-05-24): /linux/misc/go1.8.3.src.tar.gz

old (2016-12-09): /linux/misc/icu4c-58_2-src.tgz
new (2017-04-14): /linux/misc/icu4c-59_1-src.tgz

old (2017-06-09): /linux/privat/freetds-1.00.43.tar.bz2
new (2017-06-11):  /linux/privat/freetds-1.00.44.tar.bz2

old (2016-05-14; NOT available on Fossies): /linux/privat/LibRaw-0.17.2.tar.gz
new (2017-03-08): /linux/privat/LibRaw-0.18.2.tar.gz

old (2017-04-19): /linux/privat/monit-5.22.0.tar.gz
new (2017-06-07): /linux/privat/monit-5.23.0.tar.gz
```

**Comment by ilovezfs** [comment]
> probably since it's configured as a main url

Yes, that would be why, although it's still a bit strange there's so much traffic for xz source builds since we have binaries for it which are installed by default.

>pkg-config today with 300

I'll look for another mirror for that.

Thanks for the heads up about the new versions.

I had just opened one for freetds (https://github.com/Homebrew/homebrew-core/pull/14510) and icu4c has been pending for a while (https://github.com/Homebrew/homebrew-core/pull/12461).

go is for the go@1.7 formula, so that's intentionally outdated. I'll see if I can find an additional mirror for that.

I'll open PRs to update chkrootkit, dialog, dovecot, libraw, and monit.

**Comment by ilovezfs** [comment]
@jschleus amazingly fossies has been used as the main url for xz ever since 2013 (https://github.com/Homebrew/legacy-homebrew/pull/21419) and was made the main url because

>upstream is being hammered by Homebrew users. Would like to have less traffic.

**Comment by jschleus** [comment]
> > probably since it's configured as a main url

>Yes, that would be why, although it's still a bit strange there's so much traffic for xz source builds since we have binaries for it which are installed by default.

That was the main point of my original issue (with the question if that is expected ("normal") or may be a hint that there goes something wrong?). But there seems not a simple answer existing. And as already said for fossies.org is stopping just the xz accesses enough. Thank you for your quick reaction.

**Comment by ilovezfs** [comment]
>That was the main point of my original issue (with the question if that is expected ("normal") or may be a hint that there goes something wrong?). But there seems not a simple answer existing.

I would suspect someone using it for some kind of CI.

>And as already said for fossies.org is stopping just the xz accesses enough. Thank you for your quick reaction.

You're welcome!

- xz https://github.com/Homebrew/homebrew-core/pull/14511
- pkg-config https://github.com/Homebrew/homebrew-core/pull/14512
- go@1.7 https://github.com/Homebrew/homebrew-core/pull/14513
- chkroot https://github.com/Homebrew/homebrew-core/pull/14514
- dialog https://github.com/Homebrew/homebrew-core/pull/14516
- dovecot https://github.com/Homebrew/homebrew-core/pull/14516
- libraw https://github.com/Homebrew/homebrew-core/pull/14518
- monit https://github.com/Homebrew/homebrew-core/pull/14519

**Comment by MikeMcQuaid** [comment]
> Hmm, stupid question or grumpy issuer? Nevertheless, I think Homebrew doesn't need fossies.org as a mirror so please stop using it if possible. Thanks.

Neither @jschleus, sorry if closing made it feel like that. We just tend to close stuff out immediately if they are asking a question when we've answered the question. I will add a check in the next wee while that tells Homebrew authors to never use fossies as a `mirror` or `url`. Thanks ❤️

**Comment by ilovezfs** [comment]
@MikeMcQuaid I don't think @jschleus said using it for mirrors is a problem. xz was the one causing issues because it was the primary.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Ok, cool, will make it just for primary `url`.

**Comment by ilovezfs** [comment]
:+1:
