### ISSUE TITLE
gnupg and gettext installation fails with 403 

### ISSUE THREAD

**Issue by ehsank777** [Homebrew/homebrew-core#145090]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config                                                                                           
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 6 days ago
Core tap JSON: 23 Sep 08:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit westmere
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: N/A
Rosetta 2: true


$ arch -arm64 brew doctor                                                                            
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I wanted to install gnupg and it fails with error 403 when downloading  `gettext` formula. I tried to install it sepratly but still got the same error.
$ arch -arm64 brew install gnupg
$arch -arm64 brew install gettext

### What happened (include all command output)?

$ arch -arm64 brew install gettext                                                     
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/manifests/0.22.2
Already downloaded: /Users/<my user>/Library/Caches/Homebrew/downloads/1d7107d862bee9bc06cd0edaeedde698981c5061b6de64c869aff2628e5e6953--gettext-0.22.2.bottle_manifest.json
==> Fetching gettext
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:7dc306a073a88a53e457afd750139cf73785c299dd112cbeae051e114
######################################################################################################################## 100.0%curl: (22) The requested URL returned error: 403

Error: gettext: Failed to download resource "gettext"
Download failed: https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:7dc306a073a88a53e457afd750139cf73785c299dd112cbeae051e114249ba38

### What did you expect to happen?

To install it without issue

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install gnupg
```

**Comment by SimardeepSingh-zsh** [comment]
Greetings of the day, 

I would be glad to contribute to this issue. Please assign me to this specific issue.

Regards,
Simardeep Singh

**Comment by SMillerDev** [comment]
You don't need to be assigned to something to help people.

**Comment by snehas13** [comment]
Facing same issue. Please help resolve the issue @ehsank777 

==> Fetching gettext
==> Downloading https://ghcr.io/v2/homebrew/core/gettext/blobs/sha256:9bf5b0ea5f
curl: (22) The requested URL returned error: 403                     #  #  # #

**Comment by iMichka** [comment]
This could be: a firewall issue / a network issue on your side, or on GitHub's side.
The file is hosted on GitHub, so we don't have much control over the performance of the web server.

Not sure if there is anything we can do to help.

Is this always happening? Did you try to download things from another location or on another network?

**Comment by iMichka** [comment]
Closing given the above comment from myself, and no answer since 2 weeks now
