### ISSUE TITLE
Does the rmlint GUI work for anyone installing from the cask?

### ISSUE THREAD

**Issue by SainteCelery** [Homebrew/homebrew-core#14536]
> robot:~ person$ rmlint --gui
> python3: posix_spawn: /usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0

**Comment by JCount** [comment]
**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**
