### ISSUE TITLE
Can you please update latest nifi version 1.3.0 in nifi.rb. Still it is pulling version 1.2.0

### ISSUE THREAD

**Issue by retkrish** [Homebrew/homebrew-core#14555]
==> Summary
/home/osadmin/.linuxbrew/Cellar/jdk/1.8.0-112: 1,628 files, 355.2M
==> Installing nifi
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/nifi/1.2.0/nifi-1.2.
==> Best Mirror http://mirrors.koehn.com/apache/nifi/1.2.0/nifi-1.2.0-bin.tar.gz

**Comment by ilovezfs** [comment]
Done https://github.com/Homebrew/homebrew-core/pull/14556.
