### ISSUE TITLE
hdf5 --with fortran fails to install

### ISSUE THREAD

**Issue by oliviermarti** [Homebrew/homebrew-core#14551]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
_Still have a problem with python, but I doubt this is linked._
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
See https://gist.github.com/anonymous/f105a25e7fd0fca73e22eeffa979a48f
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Installing  `hdf5 --with-fortran`. Because installing `netcdf --with-fortran` fails, and I wanted to reinstall some deps properly.
Note that hdf5 without fortran installs nicely.

- What happened (include command output)
```
==> autoreconf -fiv
==> ./configure --prefix=/usr/local/Cellar/hdf5/1.10.1 --enable-build-mode=production --with-zlib=/usr --with-szlib=/usr/local/opt/szip --enable-static=yes --enable-shared=yes --ena
==> make
Last 15 lines from /Users/marti/Library/Logs/Homebrew/hdf5/03.make:
Error: Function 'buf' at (1) has no IMPLICIT type
H5_gen.F90:422:18:

     f_ptr = C_LOC(buf(1))
                  1
Warning: Procedure 'buf' called with an implicit interface at (1) [-Wimplicit-interface]
H5_gen.F90:422:18:

     f_ptr = C_LOC(buf(1))
                  1
Error: Function 'buf' at (1) has no IMPLICIT type
make[3]: *** [H5_gen.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

- What you expected to happen

- Step-by-step reproduction instructions (by running `brew install` commands)
 `brew install hdf5 --with-fortran`

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by ilovezfs** [comment]
This issue should be opened in https://github.com/Homebrew/homebrew-science/issues since that tap has hdf5.
