### ISSUE TITLE
brogue fails to install due to bad patch

### ISSUE THREAD

**Issue by ericscharff** [Homebrew/homebrew-core#14589]
brew install for package brogue has been broken for some time (I remember this being an issue for several months, and can reproduce on a fresh install of homebrew

Console log:

```
$ brew install brogue
==> Using the sandbox
==> Downloading https://sites.google.com/site/broguegame/brogue-1.7.4-linux-amd6
Already downloaded: /Users/escharff/Library/Caches/Homebrew/brogue-1.7.4.tbz2
==> Patching
patching file src/platform/platformdependent.c
Hunk #1 FAILED at 75.
Hunk #2 FAILED at 128.
Hunk #3 FAILED at 197.
3 out of 3 hunks FAILED -- saving rejects to file src/platform/platformdependent.c.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1

```

**Comment by dunn** [comment]
Do you know why that patch no longer applies? If it's no longer needed, we can remove it.

**Comment by ericscharff** [comment]
Reading the patch, it looks like it is used to set paths for installed files, relative to HOMEBREW_PREFIX, e.g.

```
-	scoresFile = fopen("BrogueHighScores.txt", "w");
+	scoresFile = fopen("HOMEBREW_PREFIX/var/brogue/BrogueHighScores.txt", "w");
```

Looking at the upstream source, it looks like the patch is still needed. It also looks as if it ought to patch cleanly (perhaps the offsets have changed), but I'm not an expert in debugging brew patching, so I'm not sure how to fix.

**Comment by dunn** [comment]
If you could try updating the patch and adding it to https://github.com/Homebrew/formula-patches, that'd be better than keeping it inline.

**Comment by ilovezfs** [comment]
I've taken care of it: https://github.com/Homebrew/homebrew-core/pull/14641.

**Comment by ilovezfs** [comment]
Thanks for reporting this @ericscharff and sorry for the trouble.

**Comment by ericscharff** [comment]
Thanks for the fix! I verified that with the fix, it installs and runs correctly.
