### ISSUE TITLE
Afsctool

### ISSUE THREAD

**Issue by vfx01j** [Homebrew/homebrew-core#14616]
Brew formula afsctool v1.6.4 does not work on Mac OS 10.12 and the warning message "Unable to compress" is returned for every occasion.

Suggestion to change is available:

Merge pull request:
https://github.com/jrk/afsctool/commit/1146c90c572074f3d5ff608b4d7b14bcbbb50452

Please have a look, many thanks!

**Comment by dunn** [comment]
We'd be happy to review a pull request!  Have a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md and let us know if you have questions!

**Comment by fxcoudert** [comment]
A pull request has been opened, so closing.
