### ISSUE TITLE
Change log location for dovecot?

### ISSUE THREAD

**Issue by Jmuccigr** [Homebrew/homebrew-core#14629]
The formula sets the log file for dovecot to `/usr/local/var/log/dovecot/dovecot.log` which, on my El Cap system at least, is not readable by Console.app. Any reason not to put that instead in the user's Logs dir?

**Comment by ilovezfs** [comment]
>Any reason not to put that instead in the user's Logs dir?

We need to set the location at compile time. I suggest opening a bug report with Apple regarding Console.app
