### ISSUE TITLE
autobench: bench2graph needs patches and dependencies

### ISSUE THREAD

**Issue by kgadek** [Homebrew/homebrew-core#1463]
### Bug reports:

`bench2graph`, a part of `autobench`, is not working out-of-the-box. To fix:
- add `gawk` and `gnuplot` as a dependencies for `bench2graph` (clearly used in the script),
- apply the patch below:

```patch
--- bench2graph	2016-05-27 00:58:44.000000000 +0200
+++ /usr/local/bin/bench2graph	2004-05-27 19:01:16.000000000 +0200
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # BenchToGraph : Graph modeler for Autobench results files
 # written by Samuel Dupas <samuel.dupas@synaptique.co.uk>
@@ -74,7 +74,7 @@
 echo set key box >> gnuplot.cmd
 echo set grid >> gnuplot.cmd
 echo set output \"${output}\" >> gnuplot.cmd
-echo set style data linespoints >> gnuplot.cmd
+echo set data style linespoints >> gnuplot.cmd
 echo set title \"$title\" >> gnuplot.cmd
 echo -n plot >> gnuplot.cmd
 j=0
```

```
❯ brew info autobench
autobench: stable 2.1.2 (bottled)
Automatic webserver benchmark tool
http://www.xenoclast.org/autobench/
/usr/local/Cellar/autobench/2.1.2 (17 files, 105.3K) *
  Poured from bottle on 2016-05-27 at 00:13:43
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/autobench.rb
==> Dependencies
Required: httperf ✔
```

**Comment by MikeMcQuaid** [comment]
@kgadek Does this affect `bench2graph` outside of Homebrew? If so, please submit this patch upstream. Regardless, could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by kgadek** [comment]
For the record: the fix for the `set data style` I found on [freebsd-ports-bugs list (July 2011)](https://lists.freebsd.org/pipermail/freebsd-ports-bugs/2011-July/214381.html). The change to `bash` was a quickfix for strange behaviour:
```
-n Enter the title :
My Sweet Title

-n plot
^
"gnuplot.cmd", line 8: invalid command
```

Upstream seems to be abandoned, I see lingering PRs: https://github.com/menavaur/Autobench/pulls

As far as I can see, to fix this in brew:
1. add patch file to https://github.com/Homebrew/formula-patches,
1. add `patch` section to formula, like here: https://github.com/Homebrew/homebrew-core/blob/7f5799fd2178001b715827e3a84e021923d357c2/Formula/id3lib.rb#L36

Is that right? Seems like two PRs.

**Comment by MikeMcQuaid** [comment]
If upstream is abandoned we probably want to remove/boneyard this formula instead of patching it.

**Comment by kgadek** [comment]
Ok, so I think it's better to close. I'm not perl-savvy, so couldn't become maintainer.

**Comment by MikeMcQuaid** [comment]
@DomT4 Shall we 💀 this?

**Comment by DomT4** [comment]
@MikeMcQuaid Looks like it's potentially a one/two line `inreplace` but if there's no chance it'll ever be fixed upstream and nobody wants to fork it to restart development it's probably fair to say over time it's likely to gain more problems.
