### ISSUE TITLE
gcc (7.1.0) does not automatically link libatomic with C11 code

### ISSUE THREAD

**Issue by jeffhammond** [Homebrew/homebrew-core#14633]
I am reporting this here because the package explicitly says to do so here (`--with-bugurl=https://github.com/Homebrew/homebrew-core/issues`).  If this is the wrong place to report this bug, then please fix the bug in the `gcc` package.
```
$ gcc-7 -v
Using built-in specs.
COLLECT_GCC=gcc-7
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/7.1.0/libexec/gcc/x86_64-apple-darwin16.6.0/7.1.0/lto-wrapper
Target: x86_64-apple-darwin16.6.0
Configured with: ../configure --build=x86_64-apple-darwin16.6.0 --prefix=/usr/local/Cellar/gcc/7.1.0 --libdir=/usr/local/Cellar/gcc/7.1.0/lib/gcc/7 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-7 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-checking=release --with-pkgversion='Homebrew GCC 7.1.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls --with-native-system-header-dir=/usr/include --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
Thread model: posix
gcc version 7.1.0 (Homebrew GCC 7.1.0) 
```

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```sh
$ brew gist-logs gcc
Error: No logs.
```
[brew-config.txt](https://github.com/Homebrew/homebrew-core/files/1079098/brew-config.txt)
[brew-doctor.txt](https://github.com/Homebrew/homebrew-core/files/1079101/brew-doctor.txt)

_All `brew doctor` issues are innocuous and have nothing to do with this issue._

To help us debug your issue please explain:
- What you were trying to do (and why)

_Compile C11 code that uses C11 atomics._

- What happened (include command output)

```sh
$ gcc-7 -std=c11 c11-insane.c  -latomic || echo "FAIL"
$ gcc-7 -std=c11 c11-insane.c || echo "FAIL"
Undefined symbols for architecture x86_64:
  "___atomic_feraiseexcept", referenced from:
      _main in ccCJLVjC.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
FAIL
$ cat c11-insane.c 
#include <stdio.h>
#include <complex.h>
#include <stdatomic.h>

int main(void)
{
    _Atomic long double _Complex x = 0.0 + 0.0*I;
    for (int i=0; i<1000; i++) {
        x += 1.0;
    }
    printf("(%Lf,%Lf)\n",creall(x), cimagl(x));
    printf("%zu\n",sizeof(x));
    return 0;
}
```

- What you expected to happen

_The error-free output should not require me to link `libatomic` explicitly._

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install gcc
<create c11-insane.c from source above>
gcc-7 -std=c11 c11-insane.c
```

**Comment by jeffhammond** [comment]
Closing issues because developers ignore them is a very stupid support model.

**Comment by fxcoudert** [comment]
Upstream issue, now reported at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81358
Thanks for your bug report!

**Comment by MikeMcQuaid** [comment]
@jeffhammond Your comment was not considerate or respectful. Please read our [Code of Conduct](https://github.com/Homebrew/homebrew-core/blob/master/CODEOFCONDUCT.md).

**Comment by jeffhammond** [comment]
@fxcoudert Thank you for filing the upstream bug.  I'm sorry you had to do that.  It was stupid of me to not try to reproduce this on Linux before reporting it here.
