### ISSUE TITLE
It seems that `cleanup` removes `/usr/local/etc/my.cnf.d`

### ISSUE THREAD

**Issue by kud** [Homebrew/homebrew-core#14662]
This is what I've got when I start mariadb after a `cleanup`:

```
./usr/local/Cellar/mariadb@10.1/10.1.24/bin/my_print_defaults: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
```

Is it normal?

**Comment by kud** [comment]
I just have to do `mkdir /usr/local/etc/my.cnf.d` to solve it but why `cleanup` interferes there.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by aegrey** [comment]
Error: mysql: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Issue: Brew Cleanup removes '/usr/local/etc/my.cnf.d' for MariaDB 

`mkdir /usr/local/etc/my.cnf.d` does solve the issue, but I'm still experiencing it on Homebrew 1.5.10 on OSX 10.11.6

Commenting here vs. making another ticket to put info in the most findable reference to the error if there's anyone else also experiencing this.
