### ISSUE TITLE
Glfw v 3.3 formula ??

### ISSUE THREAD

**Issue by joeblew99** [Homebrew/homebrew-core#14666]
http://brewformulas.org/glfw

i need glfw 3.3 so i can bring up this project:
https://github.com/vulkan-go/demos#how-to-run-on-desktops

If there a brew formula for 3.3 ??

**Comment by bfontaine** [comment]
Glfw hasn’t been released yet so even if we wanted we couldn’t update the formula for it.
https://github.com/glfw/glfw/releases

**Comment by joeblew99** [comment]
@bfontaine 
Is there a way to use brew to instal the head of git ? I am not sure of the bash command.. Maybe you know ?

**Comment by bfontaine** [comment]
`brew install --HEAD git` will do the trick.
