### ISSUE TITLE
64-bit Mono is not fully supported

### ISSUE THREAD

**Issue by ticky** [Homebrew/homebrew-core#14684]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

NOTE: This mandatory section is very likely _not_ helpful in starting this discussion. As it’s requested, I’m filling it in, but you’ve been warned. 😜

To help us debug your issue please explain:
- **What you were trying to do (and why)**:  
  Build a .NET application using Mono’s `xbuild` utility, then run it.
- **What happened (include command output)**  
  The build succeeded, but runtime warnings are emitted that `WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all`, and the application crashed with an error in `System.Windows.Forms`
- **What you expected to happen**  
  The application should run successfully
- **Step-by-step reproduction instructions (by running `brew install` commands)**
  - Clone <https://github.com/Almamu/CrashEdit/tree/newgui>
  - Download <https://sourceforge.net/projects/opentk/files/opentk/opentk-1.0/rc-1/> and extract `OpenTK.dll` and `OpenTK.GLControl.dll` into `CrashEdit/obj/Debug`
  - Edit `CrashEdit/CrashEdit.csproj`, updating the reference `Version=1.0.0.0` to `Version=1.0.0.201` for both OpenTK entries.
  - Run `xbuild` from the root directory
  - Copy `Crash/obj/Debug/Crash.dll` to `CrashEdit/obj/Debug` (I believe this project is misconfigured)
  - Run `mono CrashEdit/obj/Debug/CrashEdit.exe`

---
**Explanation:**

The Mono Project [considers 64-bit support on macOS to be incomplete](http://www.mono-project.com/docs/about-mono/supported-platforms/osx/#32-and-64-bit-support) and they themselves do not ship a 64-bit version of the VM in their binary packages _at all_ due to these limitations.

>The 64 bit support has a few limitations today which is why we have not entirely switched to it:
>
>* Our Windows.Forms implementation uses Carbon, and as such, it would not work with a 64-bit Mono.
>* MonoDevelop uses Carbon for its menu integration so it would not run on a 64-bit VM.
>* MonoMac bindings have not been ported to 64 bits.

`Windows.Forms` in particular is pretty important, as it’s the GUI building block of most Win32 type applications!

For this reason, I think it would be best for Homebrew to instead ship a 32-bit build of Mono (either as the default or as an option), as its compatibility and usefulness would be significantly increased.

Related: #4332

**Comment by ticky** [comment]
I’m currently testing building a 32-bit version of mono via Homebrew’s infrastructure. I’ll put up a PR if I succeed!

**Comment by ticky** [comment]
Looks like _Mono itself_ is fine with this, but of course the problem then becomes that other external dependencies (such as `mono-libgdiplus` need to be built for 32-bit, which means all their dependencies need to be built for 32-bit, which means… etc etc)

**Comment by ilovezfs** [comment]
@ticky can we ship both?

**Comment by ticky** [comment]
Hypothetically - Mono do [discuss the possibility](http://www.mono-project.com/docs/about-mono/supported-platforms/osx/#32-and-64-bit-support) of a `mono` / `mono64` naming convention

> In the future we will ship both mono and mono64 binaries for our users.

However, it looks like they haven’t enacted such a thing yet as `mono64` would still not be very useful.

**Comment by ticky** [comment]
Just discovered `brew uses`, so here’s the list of things in homebrew-core which may require switching to 32-bit if Mono itself goes 32-bit.

- [~`archi-steam-farm`~](https://github.com/Homebrew/homebrew-core/blob/master/Formula/archi-steam-farm.rb) (.Net executable fetched and binstubbed)
- [`autorest`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/autorest.rb)
- [~`ckan`~](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ckan.rb) (.Net executable fetched and binstubbed)
- [`mercury`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mercury.rb)
- [~`nuget`~](https://github.com/Homebrew/homebrew-core/blob/master/Formula/nuget.rb) (.Net executable fetched and binstubbed)
- [`scriptcs`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/scriptcs.rb)
- [`uwsgi`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/uwsgi.rb)

**Comment by bendiken** [comment]
👍 I've been running into [`System.BadImageFormatException`](https://stackoverflow.com/q/11370344/320911) problems trying to use Npgsql with the Mono installed by Homebrew. Building a 32-bit Mono binary would indeed be preferable.

**Comment by ilovezfs** [comment]
@ticky experimenting with distributing 32-bit only sounds fine to me. Would you be willing to open a PR?

**Comment by ticky** [comment]
@ilovezfs I threw this patch together when I was first discussing it, I should’ve published it then, haha. It’s up as #15263!

**Comment by ilovezfs** [comment]
Closing this since we can now track it on https://github.com/Homebrew/homebrew-core/pull/15263.

Thanks for the report @ticky!
