### ISSUE TITLE
`brew clean` after updating rbenv results in all installed rubies to be deleted

### ISSUE THREAD

**Issue by aried3r** [Homebrew/homebrew-core#14702]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

Updating `rbenv` and running `brew clean` afterwards uninstalled all my previously installed rubies, just as described in https://github.com/Homebrew/homebrew-core/pull/7237#issuecomment-263156369

```
$ brew --version
Homebrew 1.2.3
Homebrew/homebrew-core (git revision c6806; last commit 2017-06-18)
```

Upgrade from rbenv 1.1.0 to 1.1.1.

I'm using
```
$ brew update && brew outdated && brew upgrade && brew cleanup
```
where `brew clean` results in 
```
Removing: /usr/local/Cellar/rbenv/1.1.0... (167,300 files, 1.2GB)
```

**Comment by MikeMcQuaid** [comment]
> ran brew config and brew doctor and included their output with your issue?

Do this, please. Also, please paste the output of `env | grep -i rbenv`

**Comment by aried3r** [comment]
Sorry, I forgot!

```
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c680634dae71484bce0a4fe9972b54521682cddd
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/opt/rbenv/shims/ruby => /usr/local/Cellar/rbenv/1.1.1/versions/2.4.1/bin/ruby
Java: 1.8.0_121, 1.8.0_25
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config
```
See https://github.com/PostgresApp/PostgresApp/issues/352


```
$ env | grep -i rbenv
PATH=/Users/aried3r/.opam/4.02.3/bin:/usr/local/opt/rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/local/opt/rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/texbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/aried3r/Development/android-sdk/platform-tools:/Users/aried3r/Development/android-sdk/tools:/usr/local/Cellar/node/8.0.0_1/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/texbin
RBENV_ROOT=/usr/local/opt/rbenv
RBENV_SHELL=zsh
```

**Comment by MikeMcQuaid** [comment]
> RBENV_ROOT=/usr/local/opt/rbenv

Unset this and your problems will go away.

**Comment by aried3r** [comment]
Thank you, I was looking at the wrong place, it was https://github.com/robbyrussell/oh-my-zsh/blob/3705d47bb3f3229234cba992320eadc97a221caf/plugins/rbenv/rbenv.plugin.zsh causing `RBENV_ROOT` to be set this way.
