### ISSUE TITLE
mysql 5.7.12 fails to build on OS X 10.6 (Unsupported compiler)

### ISSUE THREAD

**Issue by vanderhoorn** [Homebrew/homebrew-core#1475]
When trying to install mysql 5.7.12 on OS X 10.6, I get the following error:
```
$ brew install mysql
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-boost-5.7.12.tar.gz
Already downloaded: /Library/Caches/Homebrew/mysql-5.7.12.tar.gz
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/mysql/5.7.12 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -DMYSQL_DATADIR=/usr/local/var/mysql 
Last 15 lines from /Users/vanderhoorn/Library/Logs/Homebrew/mysql/01.cmake:
-- Checking whether CXX compiler supports OSX deployment target flag - no
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/g++-4.2
-- Check for working CXX compiler: /usr/local/Library/ENV/4.3/g++-4.2 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/os/Darwin.cmake:33 (MESSAGE):
  Unsupported compiler!
Call Stack (most recent call first):
  CMakeLists.txt:162 (INCLUDE)
```

The brew gist can be found here: https://gist.github.com/anonymous/4c980f2ba7077b51eec20af2cffa3010

```brew doctor``` only warns about OS X 10.6 being old.

```
$ brew list
autoconf	curl		libgpg-error	libyaml		pidof		python		sqlite
automake	gdbm		libksba		makedepend	pkg-config	readline	xz
cmake		git		libtool		openssl		postgresql	sphinx-doc
```

Any clue? Thanks in advance for your help.

**Comment by DomT4** [comment]
```
# This file includes OSX specific options and quirks, related to system checks

INCLUDE(CheckCSourceRuns)

# We require at least Clang 3.3 (XCode 5).
IF(NOT FORCE_UNSUPPORTED_COMPILER)
  IF(CMAKE_C_COMPILER_ID MATCHES "Clang")
    CHECK_C_SOURCE_RUNS("
      int main()
      {
        return (__clang_major__ < 3) ||
               (__clang_major__ == 3 && __clang_minor__ < 3);
      }" HAVE_SUPPORTED_CLANG_VERSION)
    IF(NOT HAVE_SUPPORTED_CLANG_VERSION)
      MESSAGE(FATAL_ERROR "Clang 3.3 or newer is required!")
    ENDIF()
  ELSE()
    MESSAGE(FATAL_ERROR "Unsupported compiler!")
  ENDIF()
ENDIF()
```

That's why, at least.

Can you try `brew install mysql --cc=gcc-5`?

**Comment by vanderhoorn** [comment]
It says:
```
$ brew install mysql --cc=gcc-5
Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Error: The requested Homebrew GCC was not installed. You must:
  brew install gcc
```

I presume I should try to install gcc?

**Comment by MikeMcQuaid** [comment]
Yep `brew install gcc`.

**Comment by vanderhoorn** [comment]
Same problem after installing gcc.

gist: https://gist.github.com/anonymous/9ac8e1f278edc7826c96f8c2c3bb3a81

The piece of source code quoted checks for Clang 3.3, while the gist reports only Clang 3.0. Xcode 4.2 is the highest version for OS X 10.6.

**Comment by DomT4** [comment]
Yeah, I feared that wouldn't work sadly.

We may have to clamp off support for building MySQL from source for 10.7 & less; you _can force_ MySQL to build regardless of the unsupported compiler but that seems like an absolute world of pain to invite.

**Comment by vanderhoorn** [comment]
> The piece of source code quoted checks for Clang 3.3, while the gist reports only Clang 3.0. Xcode 4.2 is the highest version for OS X 10.6.

This might not be true. The check fails earlier. ```CMAKE_C_COMPILER_ID``` does not return "Clang". Not sure if that changes things.

If not, do you happen to know which versions of MySQL I can still install? I can live with an older version.

**Comment by DomT4** [comment]
I presume you're stuck on 10.6 & have no way to upgrade at all? It's not looking particularly pretty for the older OS X versions based on the upstream announcement a couple months back:

<img width="1144" alt="screen shot 2016-05-28 at 17 48 19" src="https://cloud.githubusercontent.com/assets/6998367/15628591/8ff3724c-24fc-11e6-9f29-0d5357ee0a12.png">

> If not, do you happen to know which versions of MySQL I can still install? I can live with an older version.

I believe 5.6 may still have support for the older OS X releases so you may have luck with `brew install homebrew/versions/mysql56`

**Comment by vanderhoorn** [comment]
> I presume you're stuck on 10.6 & have no way to upgrade at all?
I think it can go to Lion (it's a black MacBook2,1), but I'm on this laptop for next week only (hard disk connector broke on my regular one). But I'm not planning on upgrading for now, as it'll take too much time getting everything running again. It was already a pain to upgrade from Tiger to Snow Leopard.

mysql56 works! Good enough for now. Thanks a lot for your help!

**Comment by vanderhoorn** [comment]
Not sure, but maybe the ```Unsupported compiler!``` can be improved a little.

**Comment by UniqMartin** [comment]
> mysql56 works! Good enough for now. Thanks a lot for your help!

If that's good enough for you, glad to hear you're happy!

> Additionally, maybe the `Unsupported compiler!` can be improved a little.

Probably, but that's not a thing we can do as this is a message coming from the MySQL build system.
