### ISSUE TITLE
Cannot get Homebrew to instal on Sierra.

### ISSUE THREAD

**Issue by cmarshy** [Homebrew/homebrew-core#14755]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by cmarshy** [comment]
Hi all.
I'm new to all this, so please excuse my ignorance.
I am trying to instal Homebrew on my iMac, running sierra 10.12.5, but am having problems, and I don't know enough so that I can fix it.
I want to use Handbrake, but I read that I have to instal a file it needs, via Homebrew.
I am in my Admin account, and this is the result I get:

![failed homebrew instal 2017-06-20 at 12 24 49 pm](https://user-images.githubusercontent.com/29515549/27316075-be5b4d12-55c0-11e7-8f16-2e065d9c868f.png)

I hope someone can point me in the right direction.
Thanks, in advance.

**Comment by MikeMcQuaid** [comment]
You need to run the Homebrew uninstall script first then try to run install again. Shout here if you have any more problems.

**Comment by cmarshy** [comment]
This is the script, and results.


![uninstal homebrew - edited 2017-06-20 at 7 32 42 pm copy](https://user-images.githubusercontent.com/29515549/27327118-dad80900-55f0-11e7-9641-f2ff6bfb9ab5.png)

I am obviously doing something wrong.
I did not try to reinstall  Homebrew, as it could not be found to uninstall it.

**Comment by ilovezfs** [comment]
You may just need to `sudo chown -R $(whoami) /usr/local` and the try running the install script.

**Comment by cmarshy** [comment]
Thank you for that.

I followed you instructions, and now have the following installation:

![hidden folders with homebrew installed 2017-06-21 at 4 26 04 pm](https://user-images.githubusercontent.com/29515549/27370524-4b180db4-56a0-11e7-9239-ed89d45bce03.png)

I have also installed libdvdcss, which Handbrake needs, so I assume I have installed Homebrew correctly.

**Comment by ilovezfs** [comment]
Great, so now you should be able to do `brew install handbrake`

Also, you can run

```
sudo chown root:wheel /usr/local
```

now that Homebrew has been installed successfully.

**Comment by cmarshy** [comment]
I will have to check all this out tomorrow, but I already have installed Handbrake from their website.
As it didn't work, I searched for reasons why not, and  thats how I found out about Homebrew.

Is there a difference between installing from their site, as compared to installing via Homebrew?

As I am new to Homebrew, let alone Terminal, I will have to read up on it.

I  understand some of the commands you wrote, but not other parts of it.
I'm getting a 'Take Control of Terminal', book to help me understand it a lot more.

Thanks for taking the time to reply.
Your post solved my problem.

**Comment by ilovezfs** [comment]
>Is there a difference between installing from their site, as compared to installing via Homebrew?

Yes. Installing from Homebrew will only install the Terminal program `HandBrakeCLI`. The download from their website will install the graphical `/Applications/HandBrake.app`.

Instead of `brew install handbrake` you can run `brew cask install handbrake`, which will install `/Applications/HandBrake.app`, the same thing you get from their website.

>I'm getting a 'Take Control of Terminal', book to help me understand it a lot more.

Have fun learning!

>Thanks for taking the time to reply. Your post solved my problem.

You're welcome.
