### ISSUE TITLE
Possible fix for broken irssi build in homebrew

### ISSUE THREAD

**Issue by vague666** [Homebrew/homebrew-core#147655]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
foobar
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

This is related to #138415
The following PR in irssi would probably allow perl to be built
https://github.com/irssi/irssi/pull/1492

### What happened (include all command output)?

foobar

### What did you expect to happen?

foobar

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
foobar
```

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by vague666** [comment]
I'm sorry but how lazy can you get? I don't have proprietary hardware so I have no way of doing what you want. This is related to an issue where I can't comment anymore because you close comments almost instantaneously. You have the PR you need to apply to the sources you build to get the perl module to build.

**Comment by SMillerDev** [comment]
Homebrew runs on Linux, even in docker, too so you can test things easily. If you want something changed you could make a pull request.

The requirements for issues are pretty easy, you give information and people generally try to help fix your issue, but the effort works two ways.
