### ISSUE TITLE
Can't build Vim 8.0.0647 in upgrade mode

### ISSUE THREAD

**Issue by masongup-mdsol** [Homebrew/homebrew-core#14774]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

[gist-logs link](https://gist.github.com/69cb0734e6c065ee5ff2b751c1468f5a)

I currently have Vim 8.0.0086 installed through Homebrew, and am trying to use the `brew upgrade vim` command to upgrade to 8.0.0647. It seems to have a problem with linking to Python - the build errors are shown in the linked gist-logs entry. It could be related to my `pyenv` setup, and I honestly don't care if my Vim install can use Python, as I have never used that. However, I can't try disabling python support easily or pointing to a different directory, as none of the build options seem to be recognized in the `upgrade` command. I commented on [this issue](https://github.com/Homebrew/brew/issues/1699), which seemed related, and was asked to post the issue here.

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade the installed Vim to the latest version
- What happened (include command output)
The build of Vim failed, output is included in the linked gist
- What you expected to happen
The build to succeed
- Step-by-step reproduction instructions (by running `brew install` commands)
Run `brew upgrade vim` with a previous version of `vim` installed and `pyenv` set up.

**Comment by ilovezfs** [comment]
Does this work?
```
HOMEBREW_ENV_FILTERING=1 brew upgrade vim
```

**Comment by masongup-mdsol** [comment]
Just tried that, the result is the same. Homebrew updated to `44c85c4` on the way, but the error didn't change.

**Comment by ilovezfs** [comment]
OK, in that case, please try.
```
brew uninstall vim
brew install --without-python --with-override-system-vi vim
```

**Comment by masongup-mdsol** [comment]
The `install` step failed at first, but it worked when I ran it as:

```
brew install --without-python --with-override-system-vi --without-ruby vim
```

I was getting a similar-looking error that appeared to be related to the Ruby integration, and I also don't use the Ruby integration with Vim, so this seems to work for now.

**Comment by ilovezfs** [comment]
I'm glad you got it working. Unfortunately, fulfilling the requirements with non-brew dependencies is touch and go, but we'd be happy to look at a PR if someone who uses pyenev and/or rubyenv knows how to make the vim formula's handling of non-standard configurations more robust.
