### ISSUE TITLE
Formula `lsdvd` out-of-date

### ISSUE THREAD

**Issue by decorate** [Homebrew/homebrew-core#14816]
Sadly I am not very technical on the command line, and was unable to parse the contribution guidelines beyond the following to attempt to upgrade the `lsdvd` formula.

`brew bump-formula-pr --strict lsdvd --url=https://downloads.sourceforge.net/project/lsdvd/lsdvd/lsdvd-0.17.tar.gz -sha256=aa44b8c33c66df2a131e469988ced2b11ebf9aab`

My command line output terminated with:

```
lsdvd:
  * A `test do` test block should be added
Error: 1 problem in 1 formula
Error: brew audit failed!
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `odie'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:275:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

Wish I could be of more help.

**Comment by ilovezfs** [comment]
omit --strict

**Comment by decorate** [comment]
Thank you that got me to the commit stage. Unfortunately I got a permission error.

```
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Error: Failure while executing: git push --set-upstream decorate lsdvd-0.17:lsdvd-0.17
```

Rerunning the command now suggests a manual bump (which I do not know how to do) :(

```
Error: You probably need to bump this formula manually since the new version
and old version are both 0.17.
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:55:in `odie'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:252:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by ilovezfs** [comment]
OK, no worries.

```
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
git reset --hard
git checkout master
brew update
```
And I will take a look at doing the update.

**Comment by ilovezfs** [comment]
@decorate https://github.com/Homebrew/homebrew-core/pull/14818/files

**Comment by ilovezfs** [comment]
@decorate I have now shipped 0.17 if you want to `brew update` and `brew upgrade lsdvd`

**Comment by decorate** [comment]
Thank you very much, confirmed working.

**Comment by ilovezfs** [comment]
Excellent.
