### ISSUE TITLE
Typo in mingw-w64 formula.

### ISSUE THREAD

**Issue by bradleysepos** [Homebrew/homebrew-core#14850]
See https://github.com/Homebrew/homebrew-core/blob/master/Formula/mingw-w64.rb#L102

Looks like this should be `LD=#{target}-ld`.

**Comment by dunn** [comment]
We'd love a PR to fix it!  Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md and let us know if you have questions.

**Comment by ilovezfs** [comment]
This should be fixed now if you brew update.
