### ISSUE TITLE
idris does not build under GHC 8

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#1486]
I've reported the problem upstream, but putting this here so it's not forgotten: https://github.com/idris-lang/Idris-dev/issues/3193

**Comment by MikeMcQuaid** [comment]
We should boneyard this if it's known to fail.

**Comment by ilovezfs** [comment]
Yeah, I think that's where this probably belongs at least for the short term. I poked my HEAD into #idris on IRC freenode yesterday. No one seems to know what's wrong yet. I was directed to follow a particular guide to do a from scratch GHC 8 HEAD build to rule out any anomalies with the Homebrew formula, which I did, and ended up hitting the same error.

**Comment by ilovezfs** [comment]
Since upstream acknowledges this is a serious bug and approves of the workaround we're using for the time being, I'm closing this for now in favor of the confirmed upstream report. With any luck, the next major release will have GHC 8 support.
