### ISSUE TITLE
Elixir install throws an error

### ISSUE THREAD

**Issue by bantl23** [Homebrew/homebrew-core#14883]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

# Outputs

* Step A: `brew doctor`
`Your system is ready to brew.`
* Step B: `brew install elixir`
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
knot-resolver                                                                         libphonenumber

Error: undefined method `exitstatus' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/elixir.rb:9:in `block in <class:Erlang18Requirement>'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:198:in `block in yielder'
/usr/local/Homebrew/Library/Homebrew/extend/ENV.rb:25:in `with_build_environment'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:198:in `yielder'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:412:in `install_requirement_formula?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:432:in `block in expand_requirements'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:230:in `block in prune?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:228:in `catch'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:228:in `prune?'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:219:in `block (2 levels) in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:68:in `each'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:218:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:217:in `each'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:217:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1534:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:425:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:367:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:134:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:127:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:337:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:223:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:221:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:221:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
* Step C: `brew doctor`
`Your system is ready to brew.`

* Step D: `brew gist-logs elixir`
`Error: No logs.`

* Step E: `brew config`
```
HOMEBREW_VERSION: 1.2.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 54e01d76db34a3a649c79b189873bfd0a52dbc9f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 918902fd25a44b71bcbfce4baef48028e0261e17
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.13.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_60, 1.8.0_45, 1.8.0_31, 1.7.0_67, 1.7.0_17
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```
* Step F: `brew doctor`
`Your system is ready to brew.`

**Comment by JCount** [comment]
I believe this is because your `HOMEBREW_VERSION` is out of date. You have `1.2.2` while the most recent version is `1.2.3`.

Can you try running `brew update --force --verbose`, and if that doesn't update you to the next tag (1.2.3) can you provide the output that you got?

**Comment by bantl23** [comment]
That fixed it, thanks! However, I thought brew automatically updated itself with `brew update`.

**Comment by JCount** [comment]
@bantl23 It should, but occasionally individuals have sporadic issues when upgrading to new tags. I am glad this is fixed for you.
