### ISSUE TITLE
gcc6 pours gcc7

### ISSUE THREAD

**Issue by RichieSams** [Homebrew/homebrew-core#14888]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
Error: No logs.
```
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 918902fd25a44b71bcbfce4baef48028e0261e17
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A
```

When trying to install gcc6 using the command `brew install gcc6`, brew will install gcc7 instead:

```
Adrians-iMac:~ adrian$ brew install gcc6
==> Downloading https://homebrew.bintray.com/bottles/gcc-7.1.0.el_capitan.bottle
Already downloaded: /Users/adrian/Library/Caches/Homebrew/gcc-7.1.0.el_capitan.bottle.tar.gz
==> Pouring gcc-7.1.0.el_capitan.bottle.tar.gz
```

**Comment by RichieSams** [comment]
Using the command `brew install gcc@6` correctly installs gcc-6

```
Adrians-iMac:~ adrian$ brew install gcc@6
==> Downloading https://homebrew.bintray.com/bottles/gcc@6-6.3.0.el_capitan.bott
Already downloaded: /Users/adrian/Library/Caches/Homebrew/gcc@6-6.3.0.el_capitan.bottle.tar.gz
==> Pouring gcc@6-6.3.0.el_capitan.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/gcc@6/6.3.0: 1,435 files, 280.5MB
```

**Comment by jeevatatva** [comment]
To be exact, `brew install gcc6` installs `gcc`. Homebrew uses `@` to identify versions of a formula. This is an issue which needs a fix in `Homebrew/brew` repository.

**Comment by MikeMcQuaid** [comment]
> This is an issue which needs a fix in Homebrew/brew repository.

In this case it wasn't, it was in `formula_renames.json`. Note, you should use `brew install gcc@6` in future.

**Comment by RichieSams** [comment]
Thanks for the fix! I changed all my scripts to use gcc@<version>
