### ISSUE TITLE
llvm is compiled with no optimization when installing the head version

### ISSUE THREAD

**Issue by d25fe0be** [Homebrew/homebrew-core#14889]
As `DCMAKE_C_FLAGS_RELEASE` and `DCMAKE_CXX_FLAGS_RELEASE` are specified as `-DNDEBUG` in [Homebrew/formula.rb:1336/1337](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula.rb#L1336), we effectively removes `-O3` from the compilation flags in the default settings. (CMake defaults them to `-DNDEBUG -O3`, and specifying them explicitly overrides the default ones.)

And the optimization flags are not added back in [Formula/llvm.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb).

The two definitions in `Homebrew/formula.rb` were introduced / modified by https://github.com/Homebrew/brew/commit/d09698f19f3a57ce00baddc6142aa484d7d908f6. But that commit does not seem to be problematic but was rather intended, as the comment explicitly states that before the commit, both of the macros were defined as empty string so that packages can specify their own optimization flags, and the commit only tried to add `-NDEBUG` if the packages use the default one.

I know few about the history, so there must be reasons I'm not aware of why `formula.rb` defaults the optimization flags to nothing (besides `-NDEBUG`).

I still think we might remove the macro definitions in `formula.rb` if possible, and use the default settings of CMake. Though I believe there were some strong reasons not to do so.

If changing `formula.rb` is not feasible, I think the easy fix would be overriding the two macros by defining them as `-NDEBUG -O3` at [Formula/llvm.rb:209](https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb#L209), or simply removing them from `std_cmake_args` and using the defaults.

I'm also curious if some other packages also suffer from this. 

Also, if bottled version is `cmake`'d the same way (presumably using the same `llvm.rb`), the bottled version might suffer from this as well.

ps: Just for my own curiosity, if possible, could anyone kindly explain why we chose the default (`std_cmake_args` in `formula.rb`) to be disabling optimization?

**Comment by ilovezfs** [comment]
superenv builds everything with `-Os` automatically. See the logs in `~/Library/Logs/Homebrew/llvm`

**Comment by d25fe0be** [comment]
Oops, I'll take a look at `superenv`.

Thank you for your quick response and sorry for the noise.

Closing the issue.

**Comment by ilovezfs** [comment]
>Thank you for your quick response and sorry for the noise.

You're welcome! No worries.
