### ISSUE TITLE
glib docs missing!

### ISSUE THREAD

**Issue by easior** [Homebrew/homebrew-core#14895]
I have installed GTK+ on Mac OS X by Homebrew. Everything except glib is fine. Documentations for GTK+, ATK, Cairo etc, are all locating at proper places but glib documetation is missing. Let's see what happened.
```sh
$ cd `brew --prefix`
$ cd ./share/gtk-doc/html
$ find -L . -iname "*.devhelp2"
./atk/atk.devhelp2
./cairo/cairo.devhelp2
./gdk-pixbuf/gdk-pixbuf.devhelp2
./gdk2/gdk2.devhelp2
./gtk2/gtk2.devhelp2
./harfbuzz/harfbuzz.devhelp2
$ cd ../../doc
$ find -L . -iname "*.devhelp2"
./pango/pango.devhelp2
```
I don't know how to fix it. Please help me.

**Comment by ilovezfs** [comment]
CC @tschoonj

**Comment by tschoonj** [comment]
Apparently we delete the docs in the last line of the install method:

````ruby
(share+"gtk-doc").rmtree
````

I have no idea why this was introduced...

Feel free to open a PR to remove this line.

**Comment by easior** [comment]
@tschoonj Thank you for your comment. Let me test it. If it works well, I would be send a PR.

**Comment by easior** [comment]
I found that it has been fixed by upstream.
