### ISSUE TITLE
nginx start erro again. 

### ISSUE THREAD

**Issue by hel1o-wor1d** [Homebrew/homebrew-core#149229]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
In debian 12, I installed Linuxbrew, and found the same error:

[emerg] 15225#0: unexpected end of parameter, expecting ";" in command line

After testing, I found that  -g 'daemon off'; can used in both linux and mac.

But the error comes from the file homebrew.nginx.service, this file should modified in bottle file.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install nginx
brew services start nginx

### What happened (include all command output)?

[emerg] 15225#0: unexpected end of parameter, expecting ";" in command line

### What did you expect to happen?

no error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install nginx
brew services start nginx
```

**Comment by MikeMcQuaid** [comment]
> ### What happened (include all command output)?
> [emerg] 15225#0: unexpected end of parameter, expecting ";" in command line

Can you include more output please @hel1o-wor1d such as the command you're running and the full output of that command, your `brew config` output and generally anything else you're running that seems useful.

**Comment by hel1o-wor1d** [comment]
> > ### What happened (include all command output)?
> > [emerg] 15225#0: unexpected end of parameter, expecting ";" in command line
> 
> Can you include more output please @hel1o-wor1d such as the command you're running and the full output of that command, your `brew config` output and generally anything else you're running that seems useful.

not need detials.

just modify  
`-g daemon off;`
to 
`-g 'daemon off;'`
in everywhere/anywhere in nginx cask files.

**Comment by SMillerDev** [comment]
Nor providing the information maintainers need means we can't help you
