### ISSUE TITLE
lynx doesn't work right after installation

### ISSUE THREAD

**Issue by echosa** [Homebrew/homebrew-core#14968]
This is an issue with using a program after installation, not a problem with installation itself. I'm not sure if this is the right place to report it, but it's the first place I thought of.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew gist-logs lynx
Error: No logs.

$ brew config
HOMEBREW_VERSION: 1.2.3-71-g13576111e0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 13576111e0d8c335ef9fb5d6c37c4afbe083224a
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 377530b4ed684c4baba94a4fe6e3b198948204b4
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/echosa/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_65
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
```

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to use `lynx` after installing it.

- What happened (include command output)

There are a couple of issues, at least. First, by default `lynx` is trying to go to a non-existed URL:

```
$ lynx

Looking up lynx.isc.org
Unable to locate remote host lynx.isc.org.
Alert!: Unable to connect to remote host.

lynx: Can't access startfile http://lynx.isc.org/
```

It works if you pass in a valid URL, e.g.:

```
$ lynx https://ddg.gg
```

Once `lynx` is open, the help doesn't work. Pressing `?` results in:

```
Alert!: Unable to connect to remote host.
```

- What you expected to happen

I'd expect lynx to not have a bad URL set as it's default URL, and I'd expect the built-in help to work.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install lynx
$ brew lynx # will error out
$ brew lynx https://ddg.gg # once lynx loads, press ? to try to load the help page, which errors out
```

**Comment by chdiza** [comment]
> First, by default lynx is trying to go to a non-existed URL

That's a bug in lynx, and should be reported.  They are very slow to make releases, so in the meantime you can create a `lynx.cfg` and in it do:
```
STARTFILE:file://localhost/~/
```
(or whatever url you want).

> Once lynx is open, the help doesn't work.

I am not having this problem.

**Comment by echosa** [comment]
@chdiza  I have a `lynx.cfg` already for other settings, so I'll add a `STARTFILE` to it. Thanks for that tip. Regarding the help issue, what file or URL loads when you press `?` to bring up help? it's supposed to be a local file, right? Maybe I'm missing it for some reason?

**Comment by echosa** [comment]
@chdiza Ah, I believe I found the "help" issue in my `.lynx.cfg`:

```
HELPFILE:http://lynx.isc.org/release/breakout/lynx_help/lynx_help_main.html
```

Obviously that's broken. However, I don't have a local version of that file:

```
/usr/local $ find . -name lynx_help_main.html

/usr/local $
```

Should the brew formula have installed local copies of the help files? If not, what is the correct source?

**Comment by chdiza** [comment]
It's not a local file, at least not on my machine.  Mine goes to (apparently): `http://lynx.invisible-island.net/lynx_help/`.

**Comment by echosa** [comment]
Ah. I've used lynx on systems where it was local. Still, I use that URL. Thanks.

**Comment by chdiza** [comment]
> Should the brew formula have installed local copies of the help files?

No.  I have installed my own and use a shellvar to make sure that lynx uses it.

**Comment by chdiza** [comment]
I am using a "dev" edition, with some patches applied.  One of them (I guess) has already patched the system `lynx.cfg` (in `etc`) to have the correct `STARTFILE`: "http://lynx.invisible-island.net/".

So no need to report this to them.  You just have to wait until they cut a release.

**Comment by chdiza** [comment]
> I have installed my own and use a shellvar to make sure that lynx uses it.

Rather, I made my own, but inside it it sources the system version of the file at the beginning.  My local settings then override any global ones, when they conflict.

**Comment by chdiza** [comment]
Might be worth making a PR to `inreplace` the relevant spots (`STARTFILE` and `HELPFILE`)  in `etc/lynx.cfg`, until a new release comes out.

**Comment by echosa** [comment]
Alternatively, it might be nice to have a flag for the formula that installs the latest dev version? Right now, the lynx formula will only install the latest stable, which is 2.8.8rel.2 from a couple of years ago. The latest is 2.8.9dev.14 from from last month.

**Comment by ilovezfs** [comment]
@echosa I'd be happy to remove a PR adding a `devel do` block to the `lynx` formula!
