### ISSUE TITLE
Pylucene listed as "Active" but not found

### ISSUE THREAD

**Issue by BlueKeleher** [Homebrew/homebrew-core#14969]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs pylucene
Error: No available formula with the name "pylucene"
```

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.2.3
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ed9942fbd1ec4243f0a92ab8f9b2411c8b1fb091
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 377530b4ed684c4baba94a4fe6e3b198948204b4
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131, 1.8.0_31
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.8 => /opt/X11

$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your XQuartz (2.7.8) is outdated.
Please install XQuartz 2.7.9 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz
```

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
**- What you were trying to do (and why)**
I was trying to install PyLucene (python wrapper to Java Lucene). The formula recently went from "Inactive" to "Active", which I took to mean that I would be able to use it.

**- What happened (include command output)**
'PyLucene' is still not being found by Homebrew.

```
$ brew install pylucene
Error: No available formula with the name "pylucene" 
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**- What you expected to happen**
I was hoping PyLucene would be installed/built.

**- Step-by-step reproduction instructions (by running `brew install` commands)**
`brew install pylucene`

**Comment by JCount** [comment]
@BlueKeleher I do not know what listing you are referring to, but Homebrew currently does not have a formula for Pylucene in an official tap. Additionally, for a variety of reasons, we would be unlikely to accept a new formula for it.

**Comment by BlueKeleher** [comment]
Thanks for the feedback, sorry for the inconvenience. For about a day the old PyLucene formula page was listed as "Active," but I see it has changed.
