### ISSUE TITLE
[python-certifi] Error: The brew link step did not complete successfully

### ISSUE THREAD

**Issue by superbonaci** [Homebrew/homebrew-core#150306]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e57a87cfe9c15f192cd4fc6695a2b3b7acf0ddf7
Last commit: 5 hours ago
Core tap JSON: 09 Oct 16:38 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```
```shell
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  brew-pip
  exa

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-certifi
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

issue started here:
https://github.com/pypa/pipx/issues/1080

### What happened (include all command output)?

Upgrade brew.sh:
```
$ brew update && brew upgrade
==> Upgrading 2 outdated packages:
python-certifi 2023.7.22 -> 2023.7.22_1
python-mutagen 1.47.0 -> 1.47.0_1
==> Pouring python-certifi--2023.7.22_1.arm64_sonoma.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink lib/python3.10/site-packages/certifi/__init__.py
Target /opt/homebrew/lib/python3.10/site-packages/certifi/__init__.py
already exists. You may want to remove it:
  rm '/opt/homebrew/lib/python3.10/site-packages/certifi/__init__.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite python-certifi

To list all files that would be deleted:
  brew link --overwrite --dry-run python-certifi

Possible conflicting files are:
/opt/homebrew/lib/python3.10/site-packages/certifi/__init__.py
/opt/homebrew/lib/python3.10/site-packages/certifi/__main__.py
/opt/homebrew/lib/python3.10/site-packages/certifi/cacert.pem
/opt/homebrew/lib/python3.10/site-packages/certifi/core.py
/opt/homebrew/lib/python3.10/site-packages/certifi/py.typed
==> Summary
🍺  /opt/homebrew/Cellar/python-certifi/2023.7.22_1: 43 files, 34.0KB
==> Running `brew cleanup python-certifi`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /opt/homebrew/Cellar/python-certifi/2023.7.22... (34 files, 27.7KB)
==> Pouring python-mutagen--1.47.0_1.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/python-mutagen/1.47.0_1: 218 files, 1.8MB
==> Running `brew cleanup python-mutagen`...
Removing: /opt/homebrew/Cellar/python-mutagen/1.47.0... (218 files, 1.8MB)
```

### What did you expect to happen?

work

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run the commands
```

**Comment by cho-m** [comment]
Did you ever `pip install certifi` or some other Python package that uses `certifi`? If so, you'll need to handle this using one of commands recommended in error message.

Homebrew doesn't delete files created by user so using `pip install` (or indirect tools like `brew-pip` listed in your snippet) can lead to these type of issues.

Maybe check metadata for `/opt/homebrew/lib/python3.10/site-packages/certifi` directory to see when it was created.

**Comment by superbonaci** [comment]
> Maybe check metadata for `/opt/homebrew/lib/python3.10/site-packages/certifi` directory to see when it was created.

That dir was created `October 28, 2022`

**Comment by superbonaci** [comment]
Reported to https://github.com/pypa/pipx/issues/1080

**Comment by cho-m** [comment]
As Homebrew adds more Python libraries/formulae, this will sadly be hit more often (e.g. https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+label%3Apython+label%3A%22new+formula%22+python+in%3Atitle+).

Similar to issue mentioned in abstract for PEP 668 https://peps.python.org/pep-0668/#abstract but Homebrew does not provide enough packages to be "externally managed". Homebrew could enable this anyways and only allow users to install via virtualenvs or user directories; however, it doesn't help with already installed Python packages and will limit prior functionality.
