### ISSUE TITLE
Winedevice occasionally crashes

### ISSUE THREAD

**Issue by vlovich** [Homebrew/homebrew-core#15093]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
N/A
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
N/A

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
I run an old GNU make version built for Windows under wine.
- What happened (include command output)
winedevice.exe(72228,0xb0004000) malloc: *** error for object 0x401c5808: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
- What you expected to happen
I expect wine to not crash.  I do not see these kinds of crashes with Wine on Linux, although it could just be silent/glibc's malloc isn't catching the issue.
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install wine
? unclear.

The problem does seem to be rarer than in previous builds.

**Comment by ilovezfs** [comment]
I suggest trying `brew install --devel wine` and seeing if it happens with wine 2.11. If it does, you'll need to report this to upstream.
