### ISSUE TITLE
Update for cmatrix

### ISSUE THREAD

**Issue by abishekvashok** [Homebrew/homebrew-core#15102]
Chris handled the development key of cmatrix on to me and is now hosted at: https://github.com/abishekvashok/cmatrix

Pls update homebrew/cmatrix to point to the newest release: https://github.com/abishekvashok/cmatrix/archive/1.2.tar.gz

**Comment by ilovezfs** [comment]
@abishekvashok thank you for the heads up! Do you mind creating a new release named 1.2.0.1 or 1.2.1? Unfortunately in our version parsing

```
irb(main):002:0> Version.new("1.2") < Version.new("1.2a")
=> true
```
So no one will get upgraded if we push out a 1.2.

**Comment by abishekvashok** [comment]
I will let you know for 1.3. i will push it out by next weekend.

**Comment by ilovezfs** [comment]
@abishekvashok perfect, thanks!
