### ISSUE TITLE
scriptcs dependency on mono should be recommended

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#15109]
This is per the convention that system Mono should be allowed as an alternative.

**Comment by MikeMcQuaid** [comment]
This is not a formal convention and there is no such thing as a `system Mono` as it's not provided by macOS.

**Comment by alexreg** [comment]
But it is an informal convention... so why not adopt it? Would you accept a PR?

**Comment by MikeMcQuaid** [comment]
Honestly I'd rather accept PRs doing the opposite. I'm pretty unhappy about Homebrew using random libraries that may happen to be installed on the system.

**Comment by alexreg** [comment]
What do you intend to do about the fundamental conflict between people installing Hombrew Mono and Xamarin Mono then? The latter is needed for Visual Studio for Mac among other things, as far as I know.

**Comment by MikeMcQuaid** [comment]
What do you mean by the "fundamental conflict"? Do they both install into `/usr/local`?

**Comment by alexreg** [comment]
I just mean that some people will always have excellent reasons to go for one or the other. Hence, excluding Xamarin Mono users from using Homebrew packages that depend on Mono seems unhelpful. (Yes, they can install both, but that's an enormous and needless waste if space.)

**Comment by MikeMcQuaid** [comment]
> Yes, they can install both, but that's an enormous and needless waste if space.

I've said before that this really isn't a concern of ours and it doesn't seem to be the primary concern of any non-trivial number of people, either.

**Comment by alexreg** [comment]
Okay, we'll just have to beg to differ then... I do think a survey should be effected though!
