### ISSUE TITLE
Upgrading pyinvoke to 2.2.0_1 fails to link

### ISSUE THREAD

**Issue by rouge8** [Homebrew/homebrew-core#151232]
#### `brew gist-logs pyinvoke`

```
Error: No logs.
```

#### `brew config`

```
HOMEBREW_VERSION: 4.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0c8a4dd4dd19ec16deb429abd50cdf82ea33b27
Last commit: 2 days ago
Core tap JSON: 16 Oct 15:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

#### `brew doctor`

```
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Ran `brew upgrade` to bring everything up to date.

### What happened (include all command output)?

Unfortunately I didn't notice the error until later, so I don't have the full output from the upgrade. But I have output from after:

```console
❯ brew install pyinvoke
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################### 100.0%
Warning: pyinvoke 2.2.0_1 is already installed, it's just not linked.
To link this version, run:
  brew link pyinvoke
❯ brew link pyinvoke
Linking /opt/homebrew/Cellar/pyinvoke/2.2.0_1... 
Error: Could not symlink lib/python3.10/site-packages/invoke/__init__.py
Target /opt/homebrew/lib/python3.10/site-packages/invoke/__init__.py
already exists. You may want to remove it:
  rm '/opt/homebrew/lib/python3.10/site-packages/invoke/__init__.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite pyinvoke

To list all files that would be deleted:
  brew link --overwrite --dry-run pyinvoke
❯ brew link --overwrite pyinvoke
Linking /opt/homebrew/Cellar/pyinvoke/2.2.0_1... 185 symlinks created.
```

### What did you expect to happen?

pyinvoke to upgrade and remain linked.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade pyinvoke
```

**Comment by rouge8** [comment]
I don't think so. These are the packages I have installed with pipx and I don't think any of them depend on invoke:

```console
❯ pipx list
venvs are in /Users/andyfreeland/.local/pipx/venvs
apps are exposed on your $PATH at /Users/andyfreeland/.local/bin
   package black 23.10.0, installed using Python 3.11.6
    - black
    - blackd
   package blacken-docs 1.16.0, installed using Python 3.11.6
    - blacken-docs
   package build 1.0.3, installed using Python 3.11.6
    - pyproject-build
   package ipython 8.16.1, installed using Python 3.11.6
    - ipython
    - ipython3
   package twine 4.0.2, installed using Python 3.11.6
    - twine
```

I also have `PIP_REQUIRE_VIRTUALENV=true` so it shouldn't have been possible to pip install anything into the Homebrew Python...

**Comment by cho-m** [comment]
Based on `brew`'s output, the existing files are not owned by Homebrew:
```
Target /opt/homebrew/lib/python3.10/site-packages/invoke/__init__.py
already exists. You may want to remove it:
  rm '/opt/homebrew/lib/python3.10/site-packages/invoke/__init__.py'

To force the link and overwrite all conflicting files:
  brew link --overwrite pyinvoke
```

You may want to look at when those files were created.

Homebrew only added `pyinvoke` Python 3.10 libraries in #151057. These were never available by Homebrew before then as they were originally installed in an unlinked virtualenv.

**Comment by rouge8** [comment]
Hmm. Unfortunately I already ran `brew link --overwrite pyinvoke` so I can't see when the previous file was created.

**Comment by cho-m** [comment]
I am working on removing the extra Python 3.10 lib in #152286 so that should help avoid this happening for other users and resolve issue.

Python 3.12 was made externally-managed so it should no longer be possible to create these conflicts moving forward.
