### ISSUE TITLE
openssl@1.1 postinstall hook fails

### ISSUE THREAD

**Issue by rofreytag** [Homebrew/homebrew-core#15126]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/21f778ee36cacc5322d3817bc2f35e7b
- What you were trying to do (and why)
 I updated brew after updating my mac to sierra, I ran `brew update`, `brew upgrade`

- What happened (include command output)
 the post install hook of openssl 1.1 did not finish, it prompted me to re-run
`brew postinstall openssl@1.1`

I can reproduce the error running `brew -v postinstall openssl@1.1` which results in
```
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20170629-91056-6jrmlw.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb -v
Error: undefined method `success?' for nil:NilClass
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:86:in `block in post_install'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:80:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb:80:in `post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:966:in `block in run_post_install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:832:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:965:in `run_post_install'
/usr/local/Homebrew/Library/Homebrew/postinstall.rb:16:in `<main>'
```

**Comment by DomT4** [comment]
```
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cafe1497808ef1ddb002061665ad606aa2340d10
Last commit: 9 months ago
```

That's ya problem. You probably need to do [this](https://github.com/Homebrew/brew#update-bug), although if there really is no git repository in `HOMEBREW_PREFIX` your fix is going to be a little more involved.

**Comment by rofreytag** [comment]
Wow, what are the chances... very subtle! Updating the repo and rerunning the posthook fixes the issue. Thanks for your help!
