### ISSUE TITLE
Problem with elixir-ls package

### ISSUE THREAD

**Issue by thiagomajesk** [Homebrew/homebrew-core#151387]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

**Output of `brew gist-logs elixir-ls:`**

Error: No logs.

**Output of `brew config`:**

```
HOMEBREW_VERSION: 4.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0c8a4dd4dd19ec16deb429abd50cdf82ea33b27
Last commit: 3 days ago
Core tap JSON: 17 Oct 13:30 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: 16-core 64-bit unknown_0x6_0x97
Clang: N/A
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Running the `elixir-ls` command from the package

### What happened (include all command output)?

Running the elixir-ls cli on Linux I get:

```
running /home/linuxbrew/.linuxbrew/Cellar/elixir-ls/0.17.1/libexec/launch.sh
Preferred shell fish is not supported, continuing in POSIX shell
Looking for ASDF install
ASDF install found in /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh, sourcing
/home/linuxbrew/.linuxbrew/Cellar/elixir-ls/0.17.1/libexec/launch.sh: 99: Syntax error: redirection unexpected
```

### What did you expect to happen?

The command should do something other than error I guess

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Install the package `brew install elixir-ls`
2. Try to run `elixir-ls`
```

**Comment by lukaszsamson** [comment]
Hi, elixir-ls maintainer here. It looks like you build the package using a deprecated release way https://github.com/elixir-lsp/elixir-ls#deprecated-ez-archives-release. Instead you should be using https://github.com/elixir-lsp/elixir-ls#mixinstall-based-release

**Comment by SMillerDev** [comment]
Hi @lukaszsamson do you have any reference for the mix command that is used in those docs? Because as far as I can tell Homebrew doesn't ship that tool, so someone would need to package that first

**Comment by lukaszsamson** [comment]
Mix is standard part of elixir install.
