### ISSUE TITLE
IPython formula doesn't get linked to Python site-packages

### ISSUE THREAD

**Issue by gwerbin** [Homebrew/homebrew-core#15159]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
_No output_
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 
_https://gist.github.com/gwerbin/9eb48db6e44067db0a91b6d46e24c576_

IPython is not being linked or installed into the Homebrew-installed Python's `site-packages` directory, meaning the Homebrew-installed Python can't find it.

Setup:
```shell
brew install python3
brew install ipython
pip3 install jupyter
```

Examples of expected behavior:
1. `pip3` should be able to identify that `ipython` is installed, via `pip3 show ipython`.
2. `jupyter console` should run seamlessly

Actual behavior:
1. `pip3 show ipython` returns nothing, indicating that PIP is not aware of the IPython installation
2. `jupyter console` fails with `ModuleNotFoundError: No module named 'IPython'`

By contrast, `numpy`, `scipy`, and `matplotlib` are correctly linked:

```shell
brew install numpy
/usr/local/bin/python3 -c 'import numpy as np; print(np.sum(np.array([1,2,3])))'
pip3 show numpy
```

**Comment by ilovezfs** [comment]
@gwerbin see the discussion on https://github.com/Homebrew/homebrew-core/pull/14916.

CC @cglong

**Comment by gwerbin** [comment]
Thanks. I've just identified a similar issue with `mypy`:

```shell
brew install mypy
pip3 show mypy
```

FWIW and somewhat OT, it would be nice if Python packages at least had a `python-` prefix like in most Linux distros.

**Comment by ilovezfs** [comment]
This should be fixed now.
