### ISSUE TITLE
CMake fails to link various homebrew libraries

### ISSUE THREAD

**Issue by Roboron3042** [Homebrew/homebrew-core#152007]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa2a77b1f1ac1539e69e186bad1d569100448987
Last commit: 5 weeks ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2812fdba6289848e40007b675e1e4a81c67462b
Core tap last commit: 4 weeks ago
Core tap branch: master
Core tap JSON: 22 Sep 01:16 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 3-core 64-bit ivybridge
Clang: 14.0.0 build 1400
Git: 2.42.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.7-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2 => /Applications/Xcode_14.2.app/Contents/Developer

Your system is ready to brew
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

We are using Github Actions to build a project on MacOS with homebrew and CMake. Since the updated to MacOS 12.6.8, some libraries can't be linked (it was previously working fine on MacOS 12.6.7 images).

### What happened (include all command output)?

CMake is unable to find the homebrew installed libraries at fixup_bundle, throwing always:
```
warning: embedded item does not exist '/usr/opt/libogg/lib/libogg.0.dylib'
warning: cannot resolve item '@loader_path/../../../../opt/libogg/lib/libogg.0.dylib'
```

This happens concretely with fluidsynth dependencies: libogg, libvorbisenc, libFLAC, libopus, libmpg123, libmp3lame, libvorbis. 

### What did you expect to happen?

For the homebrew libraries to be linked by CMake, as they were previously.

I apologize if this is a CMake issue and not a homebrew issue. I am not sure who is responsible.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
A failed run for reference: https://github.com/Roboron3042/simutrans-android/actions/runs/6598788140/job/17927105317
```

**Comment by Roboron3042** [comment]
The installed libsndfile version is 1.2.2.

If I explicitly re-install libsndfile, then version 1.2.2-1 is installed. And that seems to solve the issue!

**Comment by chenrui333** [comment]
ok gonna close the issue now. Thanks!
