### ISSUE TITLE
Rust 1.73.0 failed to build on Monterey arm

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#152108]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Building stage0 library artifacts (aarch64-apple-darwin)
      Finished release [optimized] target(s) in 0.24s
  thread 'main' panicked at 'could not read dir "/private/tmp/rust-20231019-5370-1ajvakf/rustc-1.73.0-src/build/aarch64-apple-darwin/stage0/lib/rustlib/aarch64-apple-darwin/codegen-backends": Os { code: 2, kind: NotFound, message: "No such file or directory" }', lib.rs:1714:25
```

relates to https://github.com/Homebrew/homebrew-core/pull/149754

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

rust 1.73.0 formula upgrade

### What happened (include all command output)?

failed to build

### What did you expect to happen?

build should pass

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- run `brew install -s rust` on Monterey arm
```

**Comment by SMillerDev** [comment]
Shouldn't this be reported to the Rust devs? Or handled in the PR

**Comment by chenrui333** [comment]
yeah, I will x-post this as well.

**Comment by chenrui333** [comment]
it is fixed now in https://github.com/Homebrew/homebrew-core/pull/154526 via https://github.com/rust-lang/rust/pull/117875
