### ISSUE TITLE
pkg-config include path of vulkan-loader points to an non-exist directory

### ISSUE THREAD

**Issue by CarterLi** [Homebrew/homebrew-core#152107]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.16-15-gee9766a
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: ee9766aa7c72c04b33f309cced3922ad7d9637d1
Last commit: 3 days ago
Core tap origin: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: 8e40ab2571435ec7149d148756894a9d95ee2439
Core tap last commit: 5 days ago
Core tap branch: master
Core tap JSON: 23 Oct 00:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
HOMEBREW_BREW_GIT_REMOTE: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
HOMEBREW_EDITOR: nvim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```
```


### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue. **Irrelevant**
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem. **Irrelevant**
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

```bash
$ brew install vulkan-loader vulkan-headers
$ pkg-config vulkan --cflags
```

### What happened (include all command output)?

```
$ brew install vulkan-loader vulkan-headers
$ pkg-config vulkan --cflags
-I/opt/homebrew/Cellar/vulkan-loader/1.3.268/include
$ command ls /opt/homebrew/Cellar/vulkan-loader/1.3.268/include
ls: cannot access '/opt/homebrew/Cellar/vulkan-loader/1.3.268/include': No such file or directory
```

### What did you expect to happen?

`pkg-config vulkan --cflags` should print `-I/opt/homebrew/Cellar/vulkan-headers/1.3.268/include` or `-I/opt/homebrew/opt/vulkan-headers/include` or `-I/opt/homebrew/opt/include`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install vulkan-loader vulkan-headers
$ pkg-config vulkan --cflags
```

**Comment by CarterLi** [comment]
Ref: https://github.com/KhronosGroup/Vulkan-Loader/commit/520eaa5a525adce0cdbdc7b8c7f7d8f0375340a6

`vulkan-loader` and `vulkan-headers` are expected to be installed in the same prefix, but it's not the case for homebrew

**Comment by cho-m** [comment]
Homebrew's symlink directory structure doesn't always work well with build scripts, which may expect something like common Linux distros.

One option would be to upstream a way of using `VULKAN_HEADERS_INSTALL_DIR` since this is already a CMake variable so the build should know where to find it.
https://github.com/Homebrew/homebrew-core/blob/b506307accadbfafcaa133dca262f226038f8c6e/Formula/v/vulkan-loader.rb#L38

---

On Homebrew side, main workarounds are to manually modify generated `.pc` file or to collapse some `vulkan-*` formulae that need a specific directory. Neither is ideal but can discuss these as options.

**Comment by juan-lunarg** [comment]
@jbeich do you have any advice for the homebrew devs here?

**Comment by jbeich** [comment]
Likely regressed by 498d5de38c74 via `inreplace` removal. v1.3.268 restored v1.3.266 behavior but `inreplace` got forgotten.

Does Homebrew not test build of consumers before updating packages? Sometimes API may break while ABI stays compatible and vice versa.

**Comment by CarterLi** [comment]
Shouldnt the `Cflag:` line be in vulkan-headers?

**Comment by jbeich** [comment]
Already suggested in https://github.com/KhronosGroup/Vulkan-Loader/issues/1319 Upstream chose to restore the old behavior instead.

**Comment by CarterLi** [comment]
> Likely regressed by [498d5de](https://github.com/Homebrew/homebrew-core/commit/498d5de38c74b34a24b484abc75e38a26149d38f) via `inreplace` removal. v1.3.268 restored v1.3.266 behavior but `inreplace` got forgotten.

@chenrui333 Should we revert the `inreplace` removal? Currently this issue [breaks building of fastfetch](https://github.com/fastfetch-cli/fastfetch/actions/runs/6637761087/job/18032723546#step:6:73)

**Comment by chenrui333** [comment]
waiting for the green build 👍
