### ISSUE TITLE
Mplayer has no compile support for libdvdread

### ISSUE THREAD

**Issue by badvision** [Homebrew/homebrew-core#15227]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by badvision** [comment]
I am unable to use mplayer for very specific DVD backup scenarios (namely -dumpstream for a particular track), and there's no option to install a version compiled with libdvdread support.  Thanks for providing the formula for it, all the same.

**Comment by ilovezfs** [comment]
@badvision does the `dvdbackup` formula do what you want?

**Comment by badvision** [comment]
It does not compile mplayer with libdvdread support and there is no way to
do what I need to do because of that.

**Comment by ilovezfs** [comment]
I'm not sure this would really be a widely used option but this should work:
```
diff --git a/Formula/mplayer.rb b/Formula/mplayer.rb
index ddf414c..7a8de54 100644
--- a/Formula/mplayer.rb
+++ b/Formula/mplayer.rb
@@ -21,6 +21,9 @@ class Mplayer < Formula
 
   depends_on "yasm" => :build
   depends_on "libcaca" => :optional
+  depends_on "libdvdread" => :optional
+  depends_on "libdvdnav" => :optional
+  depends_on "pkg-config" => :build if build.with? "libdvdnav"
 
   unless MacOS.prefer_64_bit?
     fails_with :clang do
@@ -43,6 +46,12 @@ class Mplayer < Formula
     ]
 
     args << "--enable-caca" if build.with? "libcaca"
+    args << "--enable-dvdnav" if build.with? "libdvdnav"
+
+    if build.with? "libdvdread"
+      ENV["LDFLAGS"] = "-L#{Formula["libdvdread"].opt_lib} -ldvdread"
+      args << "--enable-dvdread"
+    end
 
     system "./configure", *args
     system "make"
bash-3.2$
```

**Comment by ilovezfs** [comment]
@badvision I have now added options for libdvdread and libdvdnav
