### ISSUE TITLE
invalid attribute for formula : version (nil)

### ISSUE THREAD

**Issue by Wentzell** [Homebrew/homebrew-core#15229]
I am currently writing a new formula.

https://github.com/Wentzell/brew_triqs_test/blob/master/triqs.rb

I can install the formula without any problem. 
However when I use the '--devel' option I get the error

```
Error: invalid attribute for formula 'triqs': version (nil)
```

(see also https://travis-ci.org/Wentzell/brew_triqs_test/builds/249419223)

I have set up my devel option with

```ruby
  devel do
    url "https://github.com/TRIQS/triqs.git", :using => :git, :branch => "unstable"
  end
```

Is it not possible to pick the tip of any branch for the '--devel' install?

**Comment by ilovezfs** [comment]
@Wentzell you'll need to use `head do` for that.
