### ISSUE TITLE
CMake is compiled with non-POSIX time functions

### ISSUE THREAD

**Issue by colemancda** [Homebrew/homebrew-core#15232]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The CMake binary compiled by homebrew (`brew install cmake`),  seems to be using non-POSIX C time function [`utimensat()`](https://www.gnu.org/s/gnulib/manual/html_node/utimensat.html), but at runtime `dylib` can't lazily load this missing symbol and will crash when compiling certain projects. [Linphone for iOS](https://github.com/BelledonneCommunications/linphone-iphone/) can be successfully compiled with the official CMake binary provided at [cmake.org](https://cmake.org), but not the binary provided by HomeBrew. For more details and crash log see https://github.com/BelledonneCommunications/linphone-iphone/issues/259.

**Comment by MikeMcQuaid** [comment]
> If brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

You didn't do this, we'll reopen when you did.

**Comment by colemancda** [comment]
```
Last login: Sat Jul  1 23:04:39 on ttys002
Colemans-MacBook-Pro-Retina:~ coleman$ brew config
HOMEBREW_VERSION: 1.2.3-4076-g0a505214
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0a5052141d59ece4adb3c9dbd62096c7a2ed7282
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 824af16c2d75a767dabacac4159cc57c14271ac2
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131
macOS: 10.12.5-x86_64
Xcode: 8.3.3 => /applications/Xcode.app/Contents/Developer
CLT: N/A
X11: N/A
Colemans-MacBook-Pro-Retina:~ coleman$ brew doctor
Your system is ready to brew.
Colemans-MacBook-Pro-Retina:~ coleman$ 
```

**Comment by ilovezfs** [comment]
I'm not able to reproduce this: https://gist.github.com/ilovezfs/12f2063d2c0a1660b7ddad7d53185d46

**Comment by ilovezfs** [comment]
@colemancda what is the output of
```
 nm /usr/local/Cellar/cmake/3.8.2/bin/cmake | grep utimensat
```

**Comment by colemancda** [comment]
```
Last login: Mon Jul  3 07:14:52 on ttys002
Colemans-MacBook-Pro-Retina:~ coleman$ nm /usr/local/Cellar/cmake/3.8.2/bin/cmake | grep utimensat
Colemans-MacBook-Pro-Retina:~ coleman$ nm /usr/local/Cellar/cmake/3.8.2/bin/cmake | grep utimensat
Colemans-MacBook-Pro-Retina:~ coleman$ 
```

**Comment by ilovezfs** [comment]
OK so that symbol isn't in there. Not sure what to make of your log, but as you can see in my log it built fine. Are you sure you can still reproduce this?

**Comment by colemancda** [comment]
I'll try again, very puzzling.

**Comment by hjmallon** [comment]
I have just made this happen. I am using Xcode 9 beta. 
`$ nm /usr/local/Cellar/cmake/3.9.0/bin/cmake | grep utim
                 U _futimens
                 U _futimes
                 U _lutimes
                 U _utime
                 U _utimensat
00000001003ce366 T _uv_fs_futime
00000001003cf695 T _uv_fs_utime
`

**Comment by ilovezfs** [comment]
@hjmallon still don't see `utimensat` there.

**Comment by hjmallon** [comment]
futimens and utimensat are available in the 10.13 SDK. They are not available on 10.12. So brew (when using the beta Xcode) makes cmake (and probably other binaries) that do not run. We can to use "MACOSX_DEPLOYMENT_TARGET=#{MacOS.version}" to avoid this problem I think, I'm just testing now.

**Comment by hjmallon** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/17101

**Comment by ilovezfs** [comment]
We already set the deployment target.

**Comment by JCount** [comment]
This is may essentially be https://github.com/Homebrew/homebrew-core/issues/4902 all over again, except now the lazy symbol binding failures are on Sierra with the Xcode 9 SDK.

**Comment by hjmallon** [comment]
Fix for this in MacPorts here
https://github.com/macports/macports-ports/commit/14ca1ce6b3014ab09bf948bf5152e611a95d8696

**Comment by ilovezfs** [comment]
:-1: to patching this in individual formulae until the superenv fixes are in first.

**Comment by hjmallon** [comment]
That's fair enough. It is in staging upstream too. I am just tracking the issue for anyone that lands here from google or something. I imagine a few people mights as Xcode 9 is released and cmake just updated.

**Comment by ilovezfs** [comment]
@hjmallon https://github.com/Homebrew/homebrew-core/pull/18371

**Comment by ilovezfs** [comment]
A patch has been merged upstream if someone want to open a PR applying it.

**Comment by ilovezfs** [comment]
This is now patched in the formula.
