### ISSUE TITLE
Brew upgrade tmux, Error: Interrupted system call @ dir_s_rmdir - /usr/local/etc

### ISSUE THREAD

**Issue by huyhoang8398** [Homebrew/homebrew-core#152518]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 5 days ago
Core tap JSON: 26 Oct 22:43 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```
```


### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

upgrade tmux

### What happened (include all command output)?

Brew upgrade threw this:
```
Error: Interrupted system call @ dir_s_rmdir - /usr/local/etc
```

Then try to open tmux

```
❯ tmux
dyld[4997]: Library not loaded: /usr/local/opt/utf8proc/lib/libutf8proc.2.dylib
  Referenced from: <BC49705A-B8BB-3BDC-9292-DD829211BBEE> /usr/local/Cellar/tmux/3.3a_2/bin/tmux
  Reason: tried: '/usr/local/opt/utf8proc/lib/libutf8proc.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/utf8proc/lib/libutf8proc.2.dylib' (no such file), '/usr/local/opt/utf8proc/lib/libutf8proc.2.dylib' (no such file), '/usr/local/Cellar/utf8proc/2.9.0/lib/libutf8proc.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/utf8proc/2.9.0/lib/libutf8proc.2.dylib' (no such file), '/usr/local/Cellar/utf8proc/2.9.0/lib/libutf8proc.2.dylib' (no such file)
[1]    4997 abort      tmux
```

### What did you expect to happen?

can open tmux

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew upgrade tmux
2. run `tmux`
```

**Comment by SMillerDev** [comment]
What does `brew outdated` say?

**Comment by huyhoang8398** [comment]
strange for me, since `brew oudated` doesnt say anything,
the issue fixed after i reinstall tmux

**Comment by chenrui333** [comment]
👍 Gonna close the issue for now then

**Comment by llimllib** [comment]
I think this is related to #150336
