### ISSUE TITLE
update output in a mess

### ISSUE THREAD

**Issue by novNorthSea** [Homebrew/homebrew-core#152639]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 4.1.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35746e0a6ba6c3c5cfe56d99f79d9ec9f52ee15f
Last commit: 6 days ago
Core tap JSON: 28 Oct 01:52 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.evDPAOumyW/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.0-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false

➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

update installed software

### What happened (include all command output)?

I don't how to describe this. The output is in a mess.

<img width="1920" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/7507628/04d68019-79b6-42b4-8753-c1dfe523e26d">

### What did you expect to happen?

The "-=O=-  #" should not print or in a good manner.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
bubu (brew update && brew outdated && brew upgrade && brew cleanup)
```

**Comment by SMillerDev** [comment]
Bugs with the brew tool should be filed in Homebrew/brew. This is normal behaviour for the download bar of curl under some circumstances though, so I do not think it's a bug at all
