### ISSUE TITLE
Missing symlink to libsnappy.1.dylib as of snappy 1.1.5

### ISSUE THREAD

**Issue by esamson** [Homebrew/homebrew-core#15274]
Some local code I'm building (Hadoop, actually) depends on snappy. Just the usual `brew install snappy` worked as expected but, as of the update to snappy 1.1.5, there is no longer a `/usr/local/lib/libsnappy.1.dylib` symlink and my build fails with not being able to load libsnappy.

If I create the symlink myself (`ln -s /usr/local/lib/libsnappy.dylib /usr/local/lib/libsnappy.1.dylib`) then I'm back in business. It would be nice if this was done automatically so we retain the previous behavior with no manual intervention.

I'm not familiar with snappy itself or how it's built so I can't comment on what the cleanest approach would be. Maybe @ilovezfs would be so kind.

#### Not sure if this is relevant...
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by ilovezfs** [comment]
@esamson This is due to the upstream switch to CMake. It now installs
```
iMac-TMP:homebrew-core joe$ ls -l /usr/local/opt/snappy/lib/
total 80
drwxr-xr-x  3 joe  admin    170 Jul 11 07:26 cmake
-r--r--r--  1 joe  admin  34236 Jul 11 07:26 libsnappy.1.1.5.dylib
lrwxr-xr-x  1 joe  admin     21 Jul 11 07:26 libsnappy.dylib -> libsnappy.1.1.5.dylib
iMac-TMP:homebrew-core joe$ 
```

**Comment by ilovezfs** [comment]
@esamson this is a bug: https://github.com/google/snappy/pull/45

I will apply the fix there as a patch. Thanks for reporting this.

**Comment by ilovezfs** [comment]
Going to hold off for now because it will require all reverse dependencies to be bumped, and the Autotools build and CMake build are producing different library versions currently so I'd like to see upstream clarify what exactly they "intend" to be correct at this point.

**Comment by ilovezfs** [comment]
@esamson upstream has a new branch with a release candidate for 1.1.6 if you want to try it:

https://github.com/pwnall/snappy/tree/rc

```
diff --git a/Formula/snappy.rb b/Formula/snappy.rb
index dc08822b53..c139664f4c 100644
--- a/Formula/snappy.rb
+++ b/Formula/snappy.rb
@@ -1,8 +1,10 @@
 class Snappy < Formula
   desc "Compression/decompression library aiming for high speed"
   homepage "https://google.github.io/snappy/"
-  url "https://github.com/google/snappy/archive/1.1.5.tar.gz"
-  sha256 "c67d8d23387b1902ceff134af26e401d5412c510adeeabe6bb6b47c106b08e45"
+  url "https://github.com/pwnall/snappy.git",
+      :revision => "1b62ea916f21202b4e56e89bd60b7d4211adf8d3",
+      :shallow => false
+  version "1.1.6-rc1"
   head "https://github.com/google/snappy.git"
 
   bottle do
```

**Comment by pwnall** [comment]
@ilovezfs I tagged a 1.1.6 release that hopefully fixes some of the SONAME / SOVERSION woes. As we discussed in the snappy repo, this will require re-building all the packages that depend on snappy. Does Homebrew have a way to do that?

**Comment by ilovezfs** [comment]
@pwnall voilà. I'll add the revision bumps next.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/15583

**Comment by ilovezfs** [comment]
Closing this since we can now track it on https://github.com/Homebrew/homebrew-core/pull/15583 if needed.

Thanks for the report @esamson!

**Comment by ilovezfs** [comment]
@esamson https://github.com/Homebrew/homebrew-core/pull/15583 has shipped! So this should now be fixed.

**Comment by esamson** [comment]
Thanks for taking care of this @ilovezfs ! :)
