### ISSUE TITLE
mkvtoolnix/9.3.1_1 fails to install

### ISSUE THREAD

**Issue by PacoH** [Homebrew/homebrew-core#15305]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
	https://gist.github.com/1c5820dd19c142a1c172159bf6307733
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
	$ brew config
	HOMEBREW_VERSION: 0.9.9
	ORIGIN: https://github.com/Homebrew/brew.git
	HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
	Last commit: 11 months ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: bcb5cf680ae83de77e0ab35657f6d7fd014b28a0
	Core tap last commit: 11 months ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_REPOSITORY: /usr/local
	HOMEBREW_CELLAR: /usr/local/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: 16-core 64-bit arrandale
	Homebrew Ruby: 1.8.7-p358
	Clang: 5.1 build 503
	Git: 2.8.4 => /usr/local/bin/git
	Perl: /usr/bin/perl
	Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
	Java: 1.6.0_65-b14-462
	OS X: 10.8.5-x86_64
	Xcode: N/A
	CLT: 5.1.0.0.1.1396320587
	X11: 2.7.8 => /opt/X11

	$ brew upgrade mkvtoolnix
	Warning: You are using OS X 10.8.
	We (and Apple) do not provide support for this old version.
	You may encounter build failures or other breakages.
	Please create pull-requests instead of filing issues.
	==> Upgrading 1 outdated package, with result:
	mkvtoolnix 9.3.1_1
	==> Upgrading mkvtoolnix
	==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-9.3.1.tar.xz
	Already downloaded: /Users/user/Library/Caches/Homebrew/mkvtoolnix-9.3.1.tar.xz
	==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/9.3.1_1 --without-curl --with-boost=/usr/local/opt/boost --with-extra-incl
	==> ./drake -j16
	Last 15 lines from /Users/user/Library/Logs/Homebrew/mkvtoolnix/02.drake:
		:allow_failure => true
						 ^
	/private/tmp/mkvtoolnix-20170705-51878-v0az2d/mkvtoolnix-9.3.1/Rakefile:252: syntax error, unexpected tIDENTIFIER, expecting tAMPER
		PCH.runq(*args[0..2], args[3].merge(pchi.pretty_flags))
								  ^
	/private/tmp/mkvtoolnix-20170705-51878-v0az2d/mkvtoolnix-9.3.1/Rakefile:252: syntax error, unexpected ')', expecting kEND
	/private/tmp/mkvtoolnix-20170705-51878-v0az2d/mkvtoolnix-9.3.1/Rakefile:334: syntax error, unexpected ':', expecting ')'
		IO.write(t.name, output, encoding: "UTF-8", mode: "w")
										  ^
	/private/tmp/mkvtoolnix-20170705-51878-v0az2d/mkvtoolnix-9.3.1/Rakefile:334: syntax error, unexpected ',', expecting kEND
		IO.write(t.name, output, encoding: "UTF-8", mode: "w")
												   ^
	/private/tmp/mkvtoolnix-20170705-51878-v0az2d/mkvtoolnix-9.3.1/Rakefile:334: syntax error, unexpected ')', expecting kEND

**Comment by DomT4** [comment]
```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347
Last commit: 11 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bcb5cf6
Core tap last commit: 11 months ago
```

Your Homebrew is pretty ancient. Try running this first:
```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```
and then try:
```bash
brew install mkvtoolnix
```

**Comment by PacoH** [comment]
I tried that and tried to upgrade `mkvtoolnix`. It just quit at:

	==> Installing mkvtoolnix dependency: ruby
	==> Downloading https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2
	######################################################################## 100.0%
	==> ./configure --prefix=/usr/local/Cellar/ruby/2.4.1_1 --enable-shared --disable-silent-rules --with-sitedir=/usr/local/lib/rub
	==> make
	Last 15 lines from /Users/user/Library/Logs/Homebrew/ruby/02.make:
	compiling dmyext.c
	compiling miniprelude.c
	compiling bignum.c
	compiling class.c
	compiling compar.c
	compiling compile.c
	compiling complex.c
	compiling cont.c
	compiling debug.c
	compiling dir.c
	compiling dln_find.c
	compiling encoding.c
	dtrace: failed to compile script probes.d: line 1: empty D program translation unit
	make: *** [probes.h] Error 1
	make: *** Waiting for unfinished jobs....

	Do not report this issue to Homebrew/brew or Homebrew/core!


	Error: You are using macOS 10.8.
	We (and Apple) do not provide support for this old version.
	You may encounter build failures or other breakages.
	Please create pull-requests instead of filing issues.

	Error: You are using macOS 10.8.
	We (and Apple) do not provide support for this old version.
	You may encounter build failures or other breakages.
	Please create pull-requests instead of filing issues.

	local $ brew info mkvtoolnix
	mkvtoolnix: stable 13.0.0, HEAD
	Matroska media files manipulation tools
	https://www.bunkus.org/videotools/mkvtoolnix/
	/usr/local/Cellar/mkvtoolnix/7.3.0 (35 files, 14.4MB)
	  Built from source on 2015-02-23 at 10:00:15 with: --with-wxmac
	/usr/local/Cellar/mkvtoolnix/8.8.0_1 (42 files, 14.2MB) *
	  Built from source on 2016-03-01 at 08:41:09
	From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mkvtoolnix.rb
	==> Dependencies
	Build: xz ✘, docbook-xsl ✘, pkg-config ✔, pugixml ✘
	Required: boost ✘, libebml ✔, libmatroska ✘, libogg ✔, libvorbis ✘
	Recommended: flac ✘, libmagic ✘
	Optional: qt ✘, gettext ✔
	==> Requirements
	Build: ruby >= 1.9 ✔
	==> Options
	--with-gettext
		Build with gettext support
	--with-qt
		Build with Qt GUI
	--without-flac
		Build without flac support
	--without-libmagic
		Build without libmagic support
	--HEAD
		Install HEAD version

Now I can't use bash at all. I get:

	dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
	  Referenced from: /usr/local/bin/bash
	  Reason: image not found

	[Process completed]

when I open a terminal. How do I get back to where I was?

**Comment by DomT4** [comment]
Start with brew reinstall bash. That'll fix that problem.

**Comment by PacoH** [comment]
What? How can I do that if I can't use the terminal?

**Comment by DomT4** [comment]
> when I open a terminal.

You can change the shell which opens with the Terminal, temporarily.

If you're using the macOS Terminal it's in `Terminal => Preferences => General => Shells open with => Command => /bin/bash`.

If you're using something like iTerm2 it's in `iTerm2 => Preferences => Profiles => Default => Command => Command => /bin/bash`.

**Comment by PacoH** [comment]
I found out a quick way to get a new window in `Terminal`.  `Shell=>New Command…` (or Shift-CMD-N) and enter `/bin/sh `. Then I could install bash and it's working now. But now I think things are still messed up with `Brew`.

**Comment by DomT4** [comment]
Oh, it just throws you back onto the default shell if it can't find your login one or that's broken? It's been so long since I've had this problem I've forgotten if there's a fallback mechanism there 😄.

Anyway. `ruby` is the problem now, will need a `brew gist-logs ruby`. It is worth noting 10.8 is unsupported by Homebrew at this point, but maybe there's something obvious either I or someone else can see.

**Comment by PacoH** [comment]
I'll try that. I have problems with Ruby and Python.

**Comment by ilovezfs** [comment]
Nothing to do with 10.8. ruby builds fine for me and I'm on 10.8.

**Comment by ilovezfs** [comment]
@PacoH what is the output of `brew config` now?

**Comment by PacoH** [comment]
~ $ brew config
	HOMEBREW_VERSION: 1.2.4-4-gae33f5c
	ORIGIN: https://github.com/Homebrew/brew.git
	HEAD: ae33f5c79c8d21b3e45862945d8414fc6b95e6e9
	Last commit: 4 days ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: ff3cf9dfb84d229e1f5fa02728d518f6622ce74e
	Core tap last commit: 4 days ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_REPOSITORY: /usr/local/Homebrew
	HOMEBREW_CELLAR: /usr/local/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: 16-core 64-bit arrandale
	Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
	Clang: 5.1 build 503
	Git: 2.8.4 => /usr/local/bin/git
	Perl: /usr/bin/perl
	Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
	Java: 1.6.0_65-b14-462
	macOS: 10.8.5-x86_64
	Xcode: N/A
	CLT: 5.1.0.0.1.1396320587
	X11: 2.7.9 => /opt/X11

**Comment by ilovezfs** [comment]
>Xcode: N/A

I suspect that may be the problem. I'll test locally to confirm.

**Comment by ilovezfs** [comment]
Yeah without Xcode,
```
dtrace: failed to compile script probes.d: line 1: empty D program translation unit
```

**Comment by ilovezfs** [comment]
This change will get ruby building without Xcode (though you should just in stall Xcode):
```
diff --git a/Formula/ruby.rb b/Formula/ruby.rb
index aa363dd4ee..9d4c35e677 100644
--- a/Formula/ruby.rb
+++ b/Formula/ruby.rb
@@ -43,7 +43,7 @@ class Ruby < Formula
 
     args << "--program-suffix=#{program_suffix}" if build.with? "suffix"
     args << "--disable-install-doc" if build.without? "doc"
-    args << "--disable-dtrace" unless MacOS::CLT.installed?
+    args << "--disable-dtrace" # unless MacOS::CLT.installed?
     args << "--without-gmp" if build.without? "gmp"
 
     paths = [
```

**Comment by ilovezfs** [comment]
There is reason to be optimistic:
```
==> Summary
🍺  /usr/local/Cellar/mkvtoolnix/13.0.0: 15 files, 14.7MB, built in 5 minutes 55 seconds
Josephs-MacBook-Pro:~ joe$ brew test mkvtoolnix
Testing mkvtoolnix
==> Using the sandbox
==> /usr/local/Cellar/mkvtoolnix/13.0.0/bin/mkvmerge -o /tmp/mkvtoolnix-test-20170710-42117-rv7s86/Gr
==> /usr/local/Cellar/mkvtoolnix/13.0.0/bin/mkvinfo /tmp/mkvtoolnix-test-20170710-42117-rv7s86/Great.
==> /usr/local/Cellar/mkvtoolnix/13.0.0/bin/mkvextract tracks /tmp/mkvtoolnix-test-20170710-42117-rv7
```

**Comment by retokromer** [comment]
13.0.0 is the current version.

**Comment by ilovezfs** [comment]
@retokromer indeed :)

**Comment by ilovezfs** [comment]
@PacoH here's what you'll need to do:
```
brew uninstall -f --ignore-dependencies $(brew deps mkvtoolnix)
brew install flac
brew install --cc=gcc-7 --c++11 boost libebml libmatroska libogg libvorbis libmagic mkvtoolnix
```

**Comment by ilovezfs** [comment]
@PacoH Closing as this only affects you but will keep talking here.

**Comment by PacoH** [comment]
OK, I've spent some time re-installing Xcode tools. I had them installed from the downloaded installer pkg in `command_line_tools_for_osx_mountain_lion_april_2014.dmg`. The problem was, `xcode-select` wasn't working. Somehow `xcrun` got corrupted at some point and never worked. I noticed there was a backup `/usr/bin/xcrun-orig` so I moved it to `xcrun` and now `xcode-select` works fine. I still can't find where `command_line_tools_for_osx_mountain_lion_april_2014.dmg=>Command Line Tools (Mountain Lion).mpkg` installed the tools or how to uninstall them. Meanwhile I simply copied the `xcode_5.1.1` app to `/Applications` and executed `xcode-select -switch /Applications/Xcode.app`. Now `brew doctor` doesn't report it missing and `brew config` now reports it as well:

	~ $ brew config
	HOMEBREW_VERSION: 1.2.4-4-gae33f5c
	ORIGIN: https://github.com/Homebrew/brew.git
	HEAD: ae33f5c79c8d21b3e45862945d8414fc6b95e6e9
	Last commit: 5 days ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: 9c019a0357daa5678a74bad1e6eaea0a56df707d
	Core tap last commit: 14 hours ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_REPOSITORY: /usr/local/Homebrew
	HOMEBREW_CELLAR: /usr/local/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: 16-core 64-bit arrandale
	Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
	Clang: 5.1 build 503
	Git: 2.8.4 => /usr/local/bin/git
	Perl: /usr/bin/perl
	Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
	Java: 1.6.0_65-b14-462
	macOS: 10.8.5-x86_64
	Xcode: 5.1.1
	CLT: 5.1.0.0.1.1396320587
	X11: 2.7.9 => /opt/X11

I will continue tomorrow using the suggestions offered by you all and will report back.

**Comment by PacoH** [comment]
OK, I tried upgrading `mkvtoolnix` and all the dependencies were installed, including `ruby`. But there were compiler errors for `mkvtoolnix`.

	==> Installing mkvtoolnix
	==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-13.0.0.tar.xz
	==> Downloading from https://mkvtoolnix.download/sources/mkvtoolnix-13.0.0.tar.xz
	######################################################################## 100.0%
	==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/13.0.0 --with-boost=/usr/local/opt/boost --with-docbook-xsl-root=/usr/loca
	Last 15 lines from /Users/user/Library/Logs/Homebrew/mkvtoolnix/01.configure:
	checking for support for C++11 feature "nullptr"... yes
	checking for support for C++11 feature "tuples"... yes
	checking for support for C++11 feature "alias declarations"... yes
	checking for support for C++14 feature "std::make_unique"... no
	checking for support for C++14 feature "digit separators"... no
	checking for support for C++14 feature "binary literals"... no
	checking for support for C++14 feature "generic lambdas"... no
	The following features of the C++11/C++14 standards are not supported by clang++:
	  * std::make_unique function (C++14)
	  * digit separators (C++14)
	  * binary literals (C++14)
	  * generic lambdas (C++14)
	`If you are using the GNU C compiler collection (gcc) then you need
	at least **v4.9.x**.`
	configure: error: support for required C++11/C++14 features incomplete

I checked the `gcc` version and it was only 4.2.1, so I installed `gcc@5`. It took **84 minutes 12 seconds**!

I moved `export PATH=/usr/local/bin:$PATH` to the last export in `.bash_profile` so it is at the head of `$PATH`.

Still same errors.

I then did:

	~ $ brew upgrade --cc=gcc-5 mkvtoolnix 

and got these errors:

	Updating Homebrew...
	==> Upgrading 1 outdated package, with result:
	mkvtoolnix 13.0.0
	==> Upgrading mkvtoolnix 
	==> Using the sandbox
	==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-13.0.0.tar.xz
	Already downloaded: /Users/user/Library/Caches/Homebrew/mkvtoolnix-13.0.0.tar.xz
	==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/13.0.0 --with-boost=/usr/local/opt/boost --with-docbook-xsl-root=/usr/loca
	==> rake -j16
	Last 15 lines from /Users/user/Library/Logs/Homebrew/mkvtoolnix/02.rake:
		  kax_reader_c::read_headers_tracks(mm_io_c*, libebml::EbmlElement*, long long) in libmtxinput.a(r_matroska.o)
		  ...
	  "libebml::EbmlString::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&[abi:cxx11]() const", referenced from:
		  mtx::xml::ebml_chapters_converter_c::fix_display(libmatroska::KaxChapterDisplay&) const   in libmtxcommon.a(ebml_chapters_converter.o)
	  "libebml::EbmlUnicodeString::GetValueUTF8[abi:cxx11]() const", referenced from:
		  parse_arg_segmentinfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in mkvmerge.o
		  get_chapter_name[abi:cxx11](libmatroska::KaxChapterAtom&)    in libmtxcommon.a(chapters.o)
		  ebml_dumper_c::to_string[abi:cxx11](libebml::EbmlElement const*) const in libmtxcommon.a(debugging.o)
		  mtx::tags::get_simple_name[abi:cxx11](libmatroska::KaxTagSimple const&) in libmtxcommon.a(tags.o)
		  mtx::tags::get_simple_value[abi:cxx11](libmatroska::KaxTagSimple const&) in libmtxcommon.a(tags.o)
		  mtx::tags::remove_track_statistics(libmatroska::KaxTags*, boost::optional<unsigned long long>) in libmtxcommon.a(tags.o)
		  mtx::tags::convert_old(libmatroska::KaxTags&)       in libmtxcommon.a(tags.o)
		  ...
	ld: symbol(s) not found for architecture x86_64
	collect2: error: ld returned 1 exit status

**Comment by ilovezfs** [comment]
You need to build everything with `--c++11` that has the option.

**Comment by PacoH** [comment]
~ $ brew upgrade --c++11 mkvtoolnix
	==> Upgrading 1 outdated package, with result:
	mkvtoolnix 14.0.0
	==> Upgrading mkvtoolnix 
	==> Using the sandbox
	==> Downloading https://www.bunkus.org/videotools/mkvtoolnix/sources/mkvtoolnix-14.0.0.tar.xz
	==> Downloading from https://mkvtoolnix.download/sources/mkvtoolnix-14.0.0.tar.xz
	######################################################################## 100.0%
	==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/14.0.0 --with-boost=/usr/local/opt/boost --with-docbook-xsl-root=/usr/loca
	Last 15 lines from /Users/user/Library/Logs/Homebrew/mkvtoolnix/01.configure:
	checking for support for C++11 feature "nullptr"... yes
	checking for support for C++11 feature "tuples"... yes
	checking for support for C++11 feature "alias declarations"... yes
	checking for support for C++14 feature "std::make_unique"... no
	checking for support for C++14 feature "digit separators"... no
	checking for support for C++14 feature "binary literals"... no
	checking for support for C++14 feature "generic lambdas"... no
	The following features of the C++11/C++14 standards are not supported by clang++:
	  * std::make_unique function (C++14)
	  * digit separators (C++14)
	  * binary literals (C++14)
	  * generic lambdas (C++14)
	If you are using the GNU C compiler collection (gcc) then you need
	at least v4.9.x.
	configure: error: support for required C++11/C++14 features incomplete

**Comment by ilovezfs** [comment]
@PacoH right. You need to use gcc 7 :)
