### ISSUE TITLE
ffmpeg fails with dylib error

### ISSUE THREAD

**Issue by llimllib** [Homebrew/homebrew-core#153177]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/llimllib/2cd4aab015fd4d31fff5adce1587ae6e
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

run ffmpeg

### What happened (include all command output)?

I tried to run ffmpeg:

```
$ ffmpeg --version
dyld[29385]: Library not loaded: /opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib
  Referenced from: <8C2E2CF9-054E-300F-BDE7-3DE52F848638> /opt/homebrew/Cellar/librist/0.2.7_3/lib/librist.4.dylib
  Reason: tried: '/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.14.dylib' (no such file), '/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache)
zsh: abort      ffmpeg --version
```

I search for `libmbedcrypto.14.dylib` and it's no longer available - I guess homebrew cleaned it up? I'm a frequent user of `ffmpeg` and it definitely worked recently, so this couldn't have happened long ago.

```
$ fd -u libmbedcrypto.14.dylib /opt/homebrew

$ fd -u libmbedcrypto.15.dylib /opt/homebrew
/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.15.dylib
/opt/homebrew/lib/libmbedcrypto.15.dylib
```

OK, looks like there's an updated version of `libmbedcrypto`, so the first issue is: homebrew shouldn't have removed the version that ffmpeg was depending on.

Nevertheless, let's try to reinstall ffmpeg. No joy:

```
$ brew reinstall ffmpeg
==> Downloading https://ghcr.io/v2/homebrew/core/ffmpeg/manifests/6.0_1-2
################################################################################################################################################################################################################ 100.0%
==> Fetching ffmpeg
==> Downloading https://ghcr.io/v2/homebrew/core/ffmpeg/blobs/sha256:42d52253402650e0213379f160c55d84b65dd00f6399f164df05f114c74ebcc4
################################################################################################################################################################################################################ 100.0%
==> Reinstalling ffmpeg 
==> Pouring ffmpeg--6.0_1.arm64_sonoma.bottle.2.tar.gz
🍺  /opt/homebrew/Cellar/ffmpeg/6.0_1: 284 files, 48.7MB
==> Running `brew cleanup ffmpeg`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ ffmpeg --help        
dyld[34884]: Library not loaded: /opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib
  Referenced from: <8C2E2CF9-054E-300F-BDE7-3DE52F848638> /opt/homebrew/Cellar/librist/0.2.7_3/lib/librist.4.dylib
  Reason: tried: '/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/opt/homebrew/opt/mbedtls/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.14.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.14.dylib' (no such file), '/opt/homebrew/Cellar/mbedtls/3.5.0/lib/libmbedcrypto.14.dylib' (no such file), '/usr/local/lib/libmbedcrypto.14.dylib' (no such file), '/usr/lib/libmbedcrypto.14.dylib' (no such file, not in dyld cache)
zsh: abort      ffmpeg --help
```

It's still trying to dynamically link `libmbedcrypto.14.dylib`, so there's nothing I can think of to do.

So that's the second issue: the current bottle of `ffmpeg` appears to depend on a dynamic library that's not available in homebrew?

- It's very unclear to me if this is related to #150336 or not
- I tried upgrading `ffmpeg`, but it's already at the current version (`Warning: ffmpeg 6.0_1 already installed`)
- I uninstalled and reinstalled, no difference

### What did you expect to happen?

ffmpeg worked

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install ffmpeg`
2. `ffmpeg --help`
```

**Comment by llimllib** [comment]
Update: `brew reinstall librist` fixed the problem!

However, I think there's still a bug here as homebrew should not have gotten itself into this situation?

**Comment by llimllib** [comment]
Is the issue maybe with `brew cleanup` being to liberal in removing packages? Like in this instance it should not have felt itself clear to remove `mbedtls` 3.4.1 because `librist` was clearly depending on it, but it did it anyway?

**Comment by SMillerDev** [comment]
@Homebrew/brew any ideas?

**Comment by cho-m** [comment]
Probably related to https://github.com/Homebrew/brew/pull/16152

**Comment by Bo98** [comment]
Yes it is, sorry for the disruption. I'm still trying to think a solution.

**Comment by llimllib** [comment]
Appreciate the clarity! I see you already know how disruptive this feels for users, this is the first time homebrew has felt broken for me and I've been using it for a long time.

Good luck fixing it, looking forward to the fix.

**Comment by cho-m** [comment]
https://github.com/Homebrew/brew/pull/16152 is merged and in `brew` release. Any broken installs will need manual intervention but future upgrades/installs should be okay.

Going to close this. Let us know if issue is hit in future install/upgrade.

**Comment by llimllib** [comment]
Thank you very much @cho-m! Appreciate your work
