### ISSUE TITLE
mariadb pkg-config bug

### ISSUE THREAD

**Issue by jeroen** [Homebrew/homebrew-core#15333]
Installed `mariadb-10.2.6` but I get a linking error because of a bug in the pkgconfig:

```sh
$ mariadb_config --libs
-L/usr/local/Cellar/mariadb/10.2.6/lib/ -lmariadb -lpthread -ldl -lm -l/usr/lib/libiconv.dylib -l/usr/local/opt/openssl/lib/libssl.dylib -l/usr/local/opt/openssl/lib/libcrypto.dylib /usr/lib/libiconv.dylib
```

This results in linking error:

```
ld: library not found for -l/usr/lib/libiconv.dylib
```

I think it should use `-liconv` instead of `-l/usr/lib/libiconv.dylib` ? 

For some reason `mysql_config` which is also included with `mariadb-10.2.6` gives the correct output:

```
$ mysql_config --libs
-L/usr/local/Cellar/mariadb/10.2.6/lib  -lmariadb
```

**Comment by ilovezfs** [comment]
Yes this is the same issue as https://github.com/Homebrew/homebrew-core/issues/14278#issuecomment-306393981

There is a bug in mariadb's build system.

**Comment by jeroen** [comment]
OK I have reported this upstream: https://lists.launchpad.net/maria-developers/msg10792.html

**Comment by ilovezfs** [comment]
@jeroen This should be fixed now if you `brew update && brew upgrade`

**Comment by jeroen** [comment]
Ah you backported the fix, thanks! Will test right now.

**Comment by jeroen** [comment]
@ilovezfs can you reapply this fix? Somehow it got broken again in upstream.
