### ISSUE TITLE
Imagemagick: morphologic operations require HDRI enabled in IM compile

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/homebrew-core#153747]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.19-25-gae64469
ORIGIN: https://github.com/Homebrew/brew
HEAD: ae64469d5a3d509312c16e3275fad42c37a4bbea
Last commit: 17 hours ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4e48cfeb107becf14bfcbb0d563f637b4bdea069
Core tap last commit: 16 hours ago
Core tap branch: master
Core tap JSON: 08 Nov 18:11 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.LxuHCqEKDq/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.42.1 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.5.2-x86_64
CLT: N/A
Xcode: 15.0.1
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to use the _cameradeblur_ scripts by Fred Weinhaus.

### What happened (include all command output)?

I consistently got this error:

```
/usr/local/imagemagick/cameradeblur: line 237: [: ,0   7010121: integer expression expected

--- REQUIRES HDRI ENABLED IN IM COMPILE ---
```
I see that imagemagick libraries include the HDRI libraries:
```
$ ls /usr/local/lib/*HDRI*
/usr/local/lib/libMagick++-7.Q16HDRI.5.dylib    /usr/local/lib/libMagickCore-7.Q16HDRI.dylib
/usr/local/lib/libMagick++-7.Q16HDRI.a          /usr/local/lib/libMagickCore-7.Q16HDRI.la
/usr/local/lib/libMagick++-7.Q16HDRI.dylib      /usr/local/lib/libMagickWand-7.Q16HDRI.10.dylib
/usr/local/lib/libMagick++-7.Q16HDRI.la         /usr/local/lib/libMagickWand-7.Q16HDRI.a
/usr/local/lib/libMagickCore-7.Q16HDRI.10.dylib /usr/local/lib/libMagickWand-7.Q16HDRI.dylib
/usr/local/lib/libMagickCore-7.Q16HDRI.a        /usr/local/lib/libMagickWand-7.Q16HDRI.la
```

### What did you expect to happen?

To run the scripts as usual, they are widely used I did not get errors in the past.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew reinstall imagemagick
```

But nothing changed
```

**Comment by SMillerDev** [comment]
I'm not sure what brew can do about someone else's script failing to recognise features that you saw were enabled

**Comment by cbertelli** [comment]
I understand, but the bash script does not use libraries, only (old)
commands, so it should not be Fred's fault.
I see that on jpg files convert gives another error.

convert: delegate library support not built-in `./cameradeblur_I_95706.mpc'
(FFTW) @ warning/fourier.c/ForwardFourierTransformImage/922.

convert: invalid image index `./cameradeblur_I_95706.mpc' @
error/list.c/CloneImages/296.

convert: no such image `-clone' @ error/convert.c/ConvertImageCommand/1040.

Maybe this helps in understanding the issues with imagemagick.
I see the script use _convert_ instead of _magick convert_ but I think
there should not be any difference.

Thank you for your fast response

**Comment by cbertelli** [comment]
I see the formula says 
```
   --without-wmf
```
but this is another issue…

**Comment by SMillerDev** [comment]
Since none of these are brew commands I can't really tell if there is an issue with the brew package. It seems very much that it's a problem with your preferred usage of the package, which is not something we track in our issue tracker.

Please raise this with the imagick or script developers. If they can point out some way the brew install is broken I'm happy to reopen this.

**Comment by cbertelli** [comment]
Thank you.
But I found that the formula shows
```
      "--without-fftw",
```
So the issue may be in the formula...

**Comment by cbertelli** [comment]
anyway even installing from source after removing "--without-fftw" in the formula does not solve the issue.
