### ISSUE TITLE
Please adapt openfortivpn 1.21.0 formula: add `--enable-legacy-pppd`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Homebrew/homebrew-core#154319]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [ ] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [ ] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Reporting a packaging issue in the openfortivpn formula. I am maintaining openfortivpn.

### What happened (include all command output)?

See https://github.com/adrienverge/openfortivpn/issues/1165.

### What did you expect to happen?

See https://github.com/adrienverge/openfortivpn/issues/1165.

### Step-by-step reproduction instructions (by running `brew` commands)

See https://github.com/adrienverge/openfortivpn/issues/1165.

**Comment by SMillerDev** [comment]
@DimitriPapadopoulos the formulae does not depend on `pppd`, where is this dependency provided defined? And wouldn't it be better for the build system to detect what version of software it can use?

**Comment by DimitriPapadopoulos** [comment]
I don't maintain the formula. I maintain openfortivpn, and I know it depends on pppd at run-time.

In the short term, I won't have time to adapt the build system to detect the version of pppd at build-time, hence this request. Besides, it would be best to detect the version of pppd at run-time.

**Comment by SMillerDev** [comment]
> I don't maintain the formula. I maintain openfortivpn, and I know it depends on pppd at run-time.

Formula don't have dedicated maintainers.

I found my answer now, macOS ships with pppd and possibly so does Linux so that means we've been using system dependencies unknowingly. I'll see when I'll have time and motivation to make a PR to change the openfortivpn formula. Feel free to make a PR to change it before I do.

**Comment by DimitriPapadopoulos** [comment]
I can try to change the formula. By the way, does a formula result in a package per macOS release, or a single package for all macOS releases? The latter case might be an issue if mac0S switches to pppd ≥ 2.5.0.

**Comment by SMillerDev** [comment]
It's a package per macOS version/architecture combination.

**Comment by DimitriPapadopoulos** [comment]
Trying to implement that in https://github.com/Homebrew/homebrew-core/pull/154460. I don't know how to add `pppd` as a system dependency:
```
==> Running TapSyntax#run!
==> brew style homebrew/core
==> FAILED
▼ Full style homebrew/core output
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/o/openfortivpn.rb:23:3: C: FormulaAudit/UsesFromMacos: uses_from_macos should only be used for macOS dependencies, not pppd.
    uses_from_macos "pppd"
    ^^^^^^^^^^^^^^^^^^^^^^
  
  6902 files inspected, 1 offense detected
==> brew readall --aliases --os=all --arch=all homebrew/core
==> brew audit --except=installed --tap=homebrew/core
==> FAILED
▼ Full audit --except=installed --tap=homebrew/core output
  openfortivpn
    * Can't find dependency '"pppd"'.
  Error: 1 problem in 1 formula detected.
Error: 2 failed steps!
brew style homebrew/core
brew audit --except=installed --tap=homebrew/core
Error: Process completed with exit code 1.
```
