### ISSUE TITLE
dnsmasq needs a directory created for DHCP to work

### ISSUE THREAD

**Issue by keithjjones** [Homebrew/homebrew-core#15431]
The following command needs to occur for dnsmasq to allow the DHCP portion to work because it creates a leases file there:

```
sudo mkdir /var/lib/misc
```

**Comment by JCount** [comment]
You will either need to create that directory yourself, or make a copy of the example config as described in the `caveats` section, and then edit the relevant section:

```
# The DHCP server needs somewhere on disk to keep its lease database.
# This defaults to a sane location, but if you want to change it, use
# the line below.
#dhcp-leasefile=/var/lib/misc/dnsmasq.leases
```

**Comment by keithjjones** [comment]
@JCount correct.  Unfortunately it took me an hour to find out why it was halting.  There weren't any obvious logs or anything to tell you that.  I had to run the binary by hand, outside brew, to finally figure that out.

**Comment by JCount** [comment]
@keithjjones That's a good and fair point. I'll see if I can modify the formula so that at the very least a **_usable_** default configuration is set up when the formula is installed.

**Comment by JCount** [comment]
@keithjjones I have updated the formula, which you can get with `brew update` followed by a `brew upgrade dnsmasq`.  

Hopefully the changes I made to the default configuration solve the issues you described here, but please test them and report back the results. If things are fixed, then we can close this issue, but if problems persist please let me know so I can try again. 🙂

**Comment by ilovezfs** [comment]
@keithjjones I'm assuming this is now fixed for you! Please holler if it's not.
