### ISSUE TITLE
Can't find homebrew.mxcl.***.plist in files

### ISSUE THREAD

**Issue by ouyangliqi** [Homebrew/homebrew-core#15488]
Hey, everyone. I am new in here. And I got a problem by installing new services. I try to install tomcat by "brew install tomcat" , and I succeeded. But I can't find any file like homebrew.mxcl.tomcat.plist in /usr/local/opt/tomcat/. And the same issue happened when I installed hadoop. It seem that I can't find homebrew.mxcl.***.plist in the services file I recently installed.Can anyone help me?
P.S. I can't find the path by "brew info tomcat" or "brew info hadoop"

**Comment by ilovezfs** [comment]
Neither of those formulae have plists.

For example,
```
bash-3.2$ brew cat tomcat | grep plist
bash-3.2$ brew services start tomcat
Error: Formula `tomcat` has not implemented #plist or installed a locatable .plist file
```

**Comment by ouyangliqi** [comment]
Oh, I see. Thank you very much.
