### ISSUE TITLE
ansible-test fails to launch due to wrong python version

### ISSUE THREAD

**Issue by sandra-thieme** [Homebrew/homebrew-core#154912]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
» brew gist-logs ansible
Error: No logs.

» brew config                                                                                                                           1 ↵
HOMEBREW_VERSION: 4.1.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad1bb178d4a478840c4524063ac5cd52d8667d25
Last commit: 22 hours ago
Core tap JSON: 20 Nov 13:25 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false

» brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to invoke `ansible-test` fails because it does not support python 3.12 which is installed by brew when installing ansible. 

### What happened (include all command output)?

```shell
» ansible-test -h
This version of ansible-test cannot be executed with Python version 3.12.0. Supported Python versions are: 3.9, 3.10, 3.11
```

Short research showed that this is due to some version checks in the referenced ansible package in version 2.15.6: https://github.com/ansible/ansible/blob/v2.15.6/test/lib/ansible_test/_util/target/common/constants.py
It supports only python up to 3.11.

### What did you expect to happen?

Being able to invoke ansible-test without errors. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
» brew install ansible
» ansible-test -h
```

**Comment by cho-m** [comment]
Looks like this is updated in `ansible-core >= 2.16.0` which will be included with `ansible 9.0.0`. The new release should happen maybe tomorrow (11/21) at earliest or next week - https://docs.ansible.com/ansible/devel//roadmap/COLLECTIONS_9.html#release-schedule.
