### ISSUE TITLE
awscurl package requires botocore python module

### ISSUE THREAD

**Issue by if-jeremy** [Homebrew/homebrew-core#155202]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 4.1.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad1bb178d4a478840c4524063ac5cd52d8667d25
Last commit: 3 days ago
Core tap JSON: 22 Nov 20:52 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.10_1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
```

```
brew doctor:
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use awscurl in conjunction with aws-vault and it's --ecs-server option to make signed calls to AWS APIs.

### What happened (include all command output)?

```
awscurl -v --service s3 https://awscurl-sample-bucket.s3.amazonaws.com
{'access_key': None,
 'data': '',
 'data_binary': False,
 'header': None,
 'include': False,
 'insecure': False,
 'location': False,
 'profile': 'default',
 'region': 'us-east-1',
 'request': 'GET',
 'secret_key': None,
 'security_token': None,
 'service': 's3',
 'session_token': None,
 'uri': 'https://awscurl-sample-bucket.s3.amazonaws.com',
 'verbose': True}
"Credentials file '/Users/jutley/.aws/credentials' exists 'False'"
'loading botocore package'
'botocore package could not be loaded'
Traceback (most recent call last):
  File "/usr/local/bin/awscurl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/awscurl/0.32/libexec/lib/python3.12/site-packages/awscurl/awscurl.py", line 544, in main
    inner_main(sys.argv[1:])
  File "/usr/local/Cellar/awscurl/0.32/libexec/lib/python3.12/site-packages/awscurl/awscurl.py", line 512, in inner_main
    raise ValueError('No access key is available')
ValueError: No access key is available
```

### What did you expect to happen?

Call completes successfully, returning an Access Denied message from the AWS API, instead of a Python traceback.  I was able to narrow this down to the homebrew formula not installing the botocore python package, despite it being listed an a requirement ( see: https://github.com/okigan/awscurl/blob/master/requirements.txt )

Even manually doing `pip3 install botocore` does not allow the command to complete successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install aws-vault
brew install aws-curl
aws-vault exec --ecs-server {aws-profile-name}
awscurl -v --service s3 https://awscurl-sample-bucket.s3.amazonaws.com
```

**Comment by Amar1729** [comment]
Interesting. The `awscurl`'s `setup.py` only requires `botocore` as an extras dependency, specifically `awslibs` https://github.com/okigan/awscurl/blob/2b9f16317369277a626c1f4d15f7fbeb1cf3975a/setup.py#L36 . Presumably that's why it's not in the resource stanzas.

I don't think `homebrew-pypi-poet` or `brew create --python` support extras ...

----

FYI: `pip3 install botocore` will install `botocore` for you, but homebrew python formulae use dedicated virtual envs. You could make this work temporarily by installing it into the `awscurl` venv:

```
$ $(brew --prefix awscurl)/libexec/bin/python -m pip install botocore
```
