### ISSUE TITLE
Vifm preview garbled when vifm is built against system ncurses

### ISSUE THREAD

**Issue by bazuchan** [Homebrew/homebrew-core#155252]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs vifm
Error: No logs.
```

```
% brew config
HOMEBREW_VERSION: 4.1.20-15-g75e8376-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 75e837681670d79111c530b959b017f6ed5f52b6
Last commit: 9 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d62f532fcbb7b3f99b6515560504a2b437267c43
Core tap last commit: 9 months ago
Core tap branch: master
Core tap JSON: 14 Nov 15:27 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A
Rosetta 2: false
```

```
% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use image preview in vifm with viu (in terminal)

### What happened (include all command output)?

Image preview is garbled

### What did you expect to happen?

Image preview is fine

### Step-by-step reproduction instructions (by running `brew` commands)

Vifm from brew is built against system ncurses and have not enough curses color pairs (`tput pairs`). 
When I build vifm from source agains ncurses from brew it works fine. Please change vifm formula to build agains non-system ncurses.

Upstream bug https://github.com/vifm/vifm/issues/959

**Comment by ZhongRuoyu** [comment]
This should be fixed now; please `brew reinstall vifm`, and try again.

**Comment by bazuchan** [comment]
Confirming, thanks
