### ISSUE TITLE
geoip package doesn't work without config changes

### ISSUE THREAD

**Issue by quinncomendant** [Homebrew/homebrew-core#15539]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The [geoip](https://github.com/Homebrew/homebrew-core/blob/master/Formula/geoip.rb) formula installs without the required data files for `geoiplookup` to work correctly. The data files will not be downloaded by the accompanying `geoipupdate` program without some modifification to the `/usr/local/Cellar/geoipupdate/{VERSION}/etc/GeoIP.conf` file, as [documented here](https://apple.stackexchange.com/questions/269787/homebrew-installed-geoiplookup-shows-no-output-howto-install-geoip-data). The conf file needs these two lines before `geoipupdate` will work correctly:

    UserId 999999
    ProductIds GeoLite2-City GeoLite2-Country GeoLite-Legacy-IPv6-City GeoLite-Legacy-IPv6-Country 506 517 533

`brew config && brew doctor`:

    [q@x/0 ~] brew config
    HOMEBREW_VERSION: 1.2.4-27-gf1fa475c4
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: f1fa475c4fc6f82312368114bdd604d5752e743b
    Last commit: 4 days ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: e1f1ba00224ec173fa0334b1613182ed5ec2d6f0
    Core tap last commit: 3 days ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit broadwell
    Homebrew Ruby: 2.0.0-p648
    Clang: 8.1 build 802
    Git: 2.13.2 => /usr/local/bin/git
    Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
    Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
    Java: N/A
    macOS: 10.12.5-x86_64
    Xcode: N/A
    CLT: 8.3.2.0.1.1492020469
    X11: N/A
    [q@x/0 ~] brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: You have a curlrc file
    If you have trouble downloading packages with Homebrew, then maybe this
    is the problem? If the following command doesn't work, then try removing
    your curlrc:
      curl https://github.com

**Comment by ilovezfs** [comment]
@quinncomendant Thank you for reporting this! It's now fixed via https://github.com/Homebrew/homebrew-core/pull/15559. Note the config file location has changed to `/usr/local/etc/GeoIP.conf`
