### ISSUE TITLE
cmake 3.8.2 failed to build on 10.12.5

### ISSUE THREAD

**Issue by Pottiman** [Homebrew/homebrew-core#15547]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? NOTE: All relevant issues, i need stb for projects and have not written a formula yet.
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I was trying to upgrade a few fomulae, one of which had `cmake` as its dependency.
The upgrade from cmake 3.8.1 to 3.8.2 failed, with [this](https://gist.github.com/anonymous/c1532c62b5205c07580cba050ef36a44#file-01-bootstrap-L215) output ( [full gist output](https://gist.github.com/anonymous/c1532c62b5205c07580cba050ef36a44) ).

Manually downloading the source and compiling worked, but used `g++` instead of `clang++`.

**Comment by ilovezfs** [comment]
What's output of
```
ls /Applications/ | grep -i x
```
and
```
xcode-select -p
```

**Comment by Pottiman** [comment]
```
> ls /Applications/ | grep -i x
TextEdit.app
Xcode.app
```

```
> xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

**Comment by ilovezfs** [comment]
Can you try disabling rbenv?

**Comment by Pottiman** [comment]
Unlinked `rbenv`, restarted shell session, same result during upgrade.

**Comment by ilovezfs** [comment]
OK, I am seeing this too.

You can fix it by doing this:
```
cd /usr/local/Homebrew
git reset --hard HEAD^
export HOMEBREW_UPDATE_TO_TAG=1
brew update
```

**Comment by Pottiman** [comment]
Setting homebrew to stay on stable fixed the issue.

**Comment by ilovezfs** [comment]
The breaking commit is https://github.com/Homebrew/brew/commit/2aefd7eed65fd05ce44d46404d3f05dafb2b2cf2.
