### ISSUE TITLE
postgresql@15 is not installing pg_dump

### ISSUE THREAD

**Issue by prashanth-fbt** [Homebrew/homebrew-core#155631]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.21
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad1bb178d4a478840c4524063ac5cd52d8667d25
Last commit: 8 days ago
Core tap JSON: 27 Nov 08:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 14.3.1
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

am trying to install postgresql@15 to use pg_dump in my local mac

### What happened (include all command output)?

==> Downloading https://ghcr.io/v2/homebrew/core/postgresql/15/manifests/15.5
Already downloaded: /Users/prashanthhl/Library/Caches/Homebrew/downloads/4d1f93c62abc7db6cfe438b26d272d2b6f018ce439357cba27224d6e704e9f60--postgresql@15-15.5.bottle_manifest.json
==> Fetching postgresql@15
==> Downloading https://ghcr.io/v2/homebrew/core/postgresql/15/blobs/sha256:09e30c08099375ba9d3eb5d60ff158f734afe131aea85fa7eaf2c1b8daa8ad3a
Already downloaded: /Users/prashanthhl/Library/Caches/Homebrew/downloads/3127e3c2075c9ba27cbce1336ec99ba054f1ef8aa6fb822592f402207c4c8e9b--postgresql@15--15.5.arm64_sonoma.bottle.tar.gz
==> Pouring postgresql@15--15.5.arm64_sonoma.bottle.tar.gz
==> Caveats
This formula has created a default database cluster with:
  initdb --locale=C -E UTF-8 /opt/homebrew/var/postgresql@15
For more details, read:
  https://www.postgresql.org/docs/15/app-initdb.html

postgresql@15 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have postgresql@15 first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"' >> /Users/prashanthhl/.bash_profile

For compilers to find postgresql@15 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/postgresql@15/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/postgresql@15/include"

For pkg-config to find postgresql@15 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/postgresql@15/lib/pkgconfig"

To restart postgresql@15 after an upgrade:
  brew services restart postgresql@15
Or, if you don't want/need a background service you can just run:
  LC_ALL="C" /opt/homebrew/opt/postgresql@15/bin/postgres -D /opt/homebrew/var/postgresql@15
==> Summary
🍺  /opt/homebrew/Cellar/postgresql@15/15.5: 3,700 files, 63.0MB
==> Running `brew cleanup postgresql@15`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

### What did you expect to happen?

pg_dump should be installed because when I do brew install postgresql then it installs everything

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just run: 
brew install postgresql@15

and check:
pg_dump --version
```

**Comment by ZhongRuoyu** [comment]
It should be found at `/opt/homebrew/opt/postgresql@15/bin/pg_dump`. See your `brew install` output for instructions to have it available in your `PATH`:

> ```
> postgresql@15 is keg-only, which means it was not symlinked into /opt/homebrew,
> because this is an alternate version of another formula.
> 
> If you need to have postgresql@15 first in your PATH, run:
> echo 'export PATH="/opt/homebrew/opt/postgresql@15/bin:$PATH"' >> > /Users/prashanthhl/.bash_profile
> ```
