### ISSUE TITLE
Remove multiple speedtest aliases

### ISSUE THREAD

**Issue by daylightbrightledlight** [Homebrew/homebrew-core#15561]
After installing the formula `brew install speedtest_cli`, there are multiple aliases to the same `speedtest` command (`speedtest`, `speedtest-cli`, `speedtest_cli`). See [`speedtest_cli.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/speedtest_cli.rb).

I think it would be simpler to do the following:

- [ ] Rename formula from `speedtest_cli` to `speedtest-cli`
- [ ] Prevent assigning the following aliases during installation:
  - [ ] `speedtest`
  - [ ] `speedtest_cli`

By keeping a single `speedtest-cli` command, it would be easy to see that it corresponds to the `speedtest-cli` formula (after it is renamed), and would also match the [author's original command usage](https://github.com/sivel/speedtest-cli#usage).

**Comment by ilovezfs** [comment]
If installed with pip, you get
```
iMac-TMP:~ joe$ ls -l /usr/local/Cellar/speedtest_cli/1.0.6/bin/
total 16
lrwxr-xr-x  1 joe  admin  24 Jul 13 04:04 speedtest -> ../libexec/bin/speedtest
lrwxr-xr-x  1 joe  admin  28 Jul 13 04:04 speedtest-cli -> ../libexec/bin/speedtest-cli
```

So we should keep both of those for sure. `speedtest-cli` is currently an alias for the formula (so `brew install speedtest-cli` already works) but a complete formula rename to `speedtest-cli`, and not installing a `speedtest_cli` link,  is probably warranted at this point, given the upstream repository is now named `https://github.com/sivel/speedtest-cli` and its name on PyPI is also `speedtest-cli` (https://pypi.python.org/pypi/speedtest-cli/)

**Comment by ilovezfs** [comment]
@daylightbrightledlight https://github.com/Homebrew/homebrew-core/pull/15580

**Comment by ilovezfs** [comment]
@daylightbrightledlight I've shipped https://github.com/Homebrew/homebrew-core/pull/15580 so the formula is now named `speedtest-cli` and the `speedtest_cli` symlink is gone. I did keep the `speedtest` symlink, though.

Thanks for filing this issue!
