### ISSUE TITLE
git 2.13.3 and up: missing diff-highlight

### ISSUE THREAD

**Issue by ghostbar** [Homebrew/homebrew-core#15588]
After updating `git` `diff-highlight` is no longer available.

`git 2.13.2`:
```
$ ls /usr/local/opt/git/share/git-core/contrib/diff-highlight/
t  Makefile  README  diff-highlight
```

`git 2.13.3` and `git HEAD`:
```
$ ls /usr/local/opt/git/share/git-core/contrib/diff-highlight/
t  DiffHighlight.pm  Makefile  README  diff-highlight.perl
```

**Comment by ilovezfs** [comment]
```
 make -C $(brew --prefix git)/share/git-core/contrib/diff-highlight
```

**Comment by ghostbar** [comment]
Maybe this should be added to the formula, right? You can't expect people to run this every single time `git` is updated.

**Comment by ilovezfs** [comment]
@ghostbar it's only in `contrib` so I'm not sure it makes sense to add that step to the formula permanently.

**Comment by ghostbar** [comment]
I saw this because I depend on it, and searching on google for "diff-highlight homebrew" it seems lot of people would be expecting it to be there already compiled.

**Comment by ilovezfs** [comment]
Couldn't the same be said for just about everything in contrib?
