### ISSUE TITLE
Cmake cannot find the qt installed with homebrew

### ISSUE THREAD

**Issue by njuyuanrui** [Homebrew/homebrew-core#156]
Hi
I tried to install qt on my MacOS 10.10 this morning and chose homebrew to do that.
`#brew install qt `
And qt was been installed to /usr/local successfully。
But it seems that Cmake cannot find it because there is not Qtconfig.cmake or findQt.cmake。
So，how can I fix this?

**Comment by mikemcquaid** [comment]
You need to have `qmake` in your `$PATH` I believe. Anything more than that you'll need to ask the CMake developers.
