### ISSUE TITLE
Expat 2.2.2 has been released

### ISSUE THREAD

**Issue by hartwork** [Homebrew/homebrew-core#15600]
Dear Expat maintainers,

Expat 2.2.2 has been released.  It fixes a few rough egdes that you reported with 2.2.1 and should help reduce the number of downstream patches.  The change log is up at https://github.com/libexpat/libexpat/blob/master/expat/Changes.  Please report bugs for anything new that you run into.

Best

&nbsp;
Sebastian

PS: I would love to send this via e-mail. If you have a mail contact to write to for this, please let me know.

**Comment by ilovezfs** [comment]
@hartwork Thanks! https://github.com/Homebrew/homebrew-core/pull/15625.

>PS: I would love to send this via e-mail. If you have a mail contact to write to for this, please let me know.

ilovezfs  `AT` icloud
`dot` com

**Comment by hartwork** [comment]
Excellent, thank you!
