### ISSUE TITLE
Build libtiff with liblerc dependency for GDAL

### ISSUE THREAD

**Issue by JesseRMeyer** [Homebrew/homebrew-core#156045]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.22
ORIGIN: https://github.com/Homebrew/brew
HEAD: 251a098fbf1c02ca95f53b4806e5b6da8d5e4a80
Last commit: 6 days ago
Core tap JSON: 30 Nov 19:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.avKt6NDYIr/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 13.6.2-arm64
CLT: 15.0.0.0.1.1694021235
Xcode: 15.0.1
Rosetta 2: false
```

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
```

`gdal` already includes liblerc as a dependency, which provides LERC based compression.  However, currently libtiff is not built with liblerc, so the functionality is unavailable for raster workloads.  Otherwise I'm not sure what value including liblerc is.  I think this is problematic, but was unsure exactly how to report it.

https://github.com/Homebrew/homebrew-core/blob/b4698a581c0d752241353682fecd627d85ca6dd6/Formula/lib/libtiff.rb#L25-L30

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to use LERC with a task involving gdal.  gdal comes pre-packaged with zstd, and I am able to use zstd in gdal workloads, so when I saw liblerc was also provided in the formulae, I assumed lerc would be available to.  But it actually isn't, even though it is provided as a dependency.

### What happened (include all command output)?

Ultimately GDAL issued an error that was traceable down to the fact that the libtiff provided is not built against the provided liblerc.

### What did you expect to happen?

For libtiff to have been built with liblerc.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gdal
```

**Comment by fxcoudert** [comment]
Hum, libtiff is much more widely used than liblerc and I'm not sure if it's useful for most users to enable liblerc support there, it will expand the dependency tree.

**Comment by JesseRMeyer** [comment]
Removing liblerc entirely from the gdal tree would at least resolve the confusion (currently it seems as total dead weight), but I'd prefer to see its functionality made available somehow.

**Comment by cho-m** [comment]
> Removing liblerc entirely from the gdal tree would at least resolve the confusion (currently it seems as total dead weight)

The reason it exists is to avoid the internal copy from being built:
```
-- The following RECOMMENDED packages have not been found:

 * LERC
   Enable LERC (external)

-- Internal libraries enabled:

 * OPENCAD internal library enabled
 * LERC internal library enabled
```

Ref: https://github.com/Homebrew/homebrew-core/commit/0affc9893b22985c79aaf29035dfff98f1df907d

---

We probably will not enable `liblerc` in `libtiff` without significant requests from community given how deep `libtiff` is inside the dependency tree across multiple formulae.

If you are confident that `liblerc` has no important use in `gdal` outside of `libtiff`, then we can try using `GDAL_USE_LERC_INTERNAL=OFF` and remove `liblerc` dependency.

**Comment by JesseRMeyer** [comment]
Searching the GDAL website only lists the GTiff driver as a user of LERC.  I do not know if this is representative or holistic though, but is consistent with my understanding. @rouault would be an authority on the matter, if there's interest from the GDAL project to chime in.

https://gdal.org/search.html?q=LERC&check_keywords=yes&area=default

**Comment by rouault** [comment]
> Searching the GDAL website only lists the GTiff driver as a user of LERC

the MRF driver may also uses LERC, but I doubt that anybody outside Esri uses MRF.

**Comment by rouault** [comment]
Reopening. It would be nice to have libtiff built against liblerc. LERC compression in TIFF is more and more used. It shines particularly for digital elevation models (DEM)
