### ISSUE TITLE
Rename `zsh-completions` to `zsh-completion`

### ISSUE THREAD

**Issue by tjrana** [Homebrew/homebrew-core#15604]
Currently, the formula name `zsh-completions` is not consistent with other completion-related formulas. Use `brew search completion`.

I suggest renaming `zsh-completions` to `zsh-completion` to keep it consistent with the others. Let me know if this suggestion sounds good.

**Comment by ilovezfs** [comment]
Upstream is
```
  homepage "https://github.com/zsh-users/zsh-completions"
```
so it's probably best to leave it as-is.

**Comment by ilovezfs** [comment]
@apjanke @zmwangx any thoughts here?

**Comment by zmwangx** [comment]
`zsh-completions` provides completion**s** for multiple commands and command groups. It should not be consistent with formulae that provide completion for a single command or command group.

**Comment by zmwangx** [comment]
(Of course there's `bash-completion`. One could argue that's not a good name.)

**Comment by ilovezfs** [comment]
That seems to because it's the upstream name.
```
  homepage "https://bash-completion.alioth.debian.org/"
```

**Comment by zmwangx** [comment]
Yeah I know. I would respect the upstream name, even if the upstream name is `bash-conpletiom`.

**Comment by ilovezfs** [comment]
>bash-conpletiom

I like it.

**Comment by apjanke** [comment]
I agree with @ilovezfs and @zmwangx. We're a packager, and the project name is the project name. Let's keep as is to be consistent with upstream.

**Comment by ilovezfs** [comment]
Any objections to an alias?

**Comment by apjanke** [comment]
Nope.

**Comment by ilovezfs** [comment]
@tjrana I've added an alias so that `brew install zsh-completion` will work.
