### ISSUE TITLE
super model for apple silicon M2Pro Mac Mini (cropped image)

### ISSUE THREAD

**Issue by bonna79** [Homebrew/homebrew-core#156229]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I recently installed supermodel via Homebrew, the installation was successful but when I run a game, Sega Rally 2, both in window and full screen, I only see a portion of the game screen, namely the word insert coin. The audio sounds very good and there is no audio slowdown.
What settings should you add to the command line inside the Shell?
Or do I need to configure something I haven't configured?
Thank you

PS: I attach photos to better understand the problem.

___________________________________________________________________________________

Recentemente ho installato tramite Homebrew, supermodel , l'installazione è andata a buon fine ma quando eseguo un gioco , Sega Rally 2 , sia in finestra che a pieno schermo , visualizzo solo una porzione dello schermo di gioco , ovvero la scritta insert coin. L'audio si semnte molto bene e non ci sono rallentamenti audio. 
Che impostazioni bisogna aggiungere alla riga di comando dentro la Shell?
Oppure devo configurare qualcosa che non ho configurato? 
Grazie

PS: Allego foto per far capire meglio il problema.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

![Screenshot 2023-12-03 alle 11 10 32](https://github.com/Homebrew/homebrew-core/assets/70318818/cd822c76-6549-4272-95a9-4f2bcfad751a)
![photo_2023-12-03_11-22-04](https://github.com/Homebrew/homebrew-core/assets/70318818/01af1051-3792-4a4c-96d2-cabfe24fd613)
![photo_2023-12-03_11-22-36](https://github.com/Homebrew/homebrew-core/assets/70318818/75e1e891-e9f3-410c-ac91-6da9797be9a2)

### What happened (include all command output)?

admin-mini@Minidiadminmini ~ % supermodel /Users/admin-mini/Downloads/sega\ model\ 3\ ROMs/Roms\ Games/srally2.zip -fullscreen

### What did you expect to happen?

That I could see the whole screen

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I installed by running this command on terminal, no errors found and then to install super model I entered this command via terminal: brew install supermodel
and then added this command: brew install sdl12-compat
No error, super model starts but you only see a portion of the screen
```

**Comment by SMillerDev** [comment]
This should be reported to the developers. Homebrew has no influence on the way emulators render.

**Comment by SMillerDev** [comment]
I see you made https://github.com/Homebrew/formulae.brew.sh/issues/980, that's not correct either. Please contact the actual developers

**Comment by Motommy** [comment]
supermodel [rompath/rom] -fullscreen -res=1920,1080
this will solve the problem.
