### ISSUE TITLE
brew python loading "wrong" modules first

### ISSUE THREAD

**Issue by climbfuji** [Homebrew/homebrew-core#1566]
Hi, I have an issue with brew's python 2.7.11 on Mac OS X El Capitan 10.11.5. Basically, it loads the modules in 

> which python
/usr/local/bin/python
> # ok
> python
>>> import numpy
>>> numpy.__path__
['/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy']

Similar for other packages that are installed by default in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python. In particular, this kills matplotlib-basemap, because the system mpl_toolkits directory doesn't contain basemap, and the one in /usr/local/lib/python-2.7/site-packages never gets loaded (although being in the PYTHONPATH, which I can check by loading modules that are only in /usr/local/lib/python-2.7/site-packages but not in /System/Library/...)

I thought brew's python ignores those system python paths and only uses $PYTHONPATH? Is there a way to enforce this without having to disable SIP and delete contents in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python ?

Here the obligatories:
- ran brew update twice
- ran brew doctor and fixed fix-able stuff
- no problem running "sudo chown -R $(whoami) $(brew --prefix)"
- brew gist-logs python
https://gist.github.com/504d81af7438271621e32c3a708ed410

Thanks very much in advance for your help.

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for the usual 🐍 👊

**Comment by tdsmith** [comment]
I think you probably have some local configuration that's causing this. Inside the Python interpreter, can you run:
```python
import sys
from pprint import pprint
pprint(sys.path)
print sys.executable
```
and give the output?

At the shell, can you run:
```bash
echo $PYTHONPATH
find ~/Library/Python -name '*site*' -or -name '*.pth' 
```
and give the output, and additionally paste the content of any .pth files it finds?

**Comment by climbfuji** [comment]
Hi Tim et al.,

apologies for the slow response. Here is the output, I highlighted the offending entry in bold and further down, thanks to your instructions, the culprit.

>>> import sys
>>> from pprint import pprint
>>> pprint(sys.path)
['',
 '/usr/local/lib/python2.7/site-packages/paramiko-2.0.0-py2.7.egg',
 '/usr/local/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg',
 '/usr/local/lib/python2.7/site-packages/ipaddress-1.0.16-py2.7.egg',
 '/usr/local/lib/python2.7/site-packages/enum34-1.1.5-py2.7.egg',
 '/usr/local/lib/python2.7/site-packages/idna-2.1-py2.7.egg',
 '/usr/local/lib/python2.7/site-packages/pycparser-2.14-py2.7.egg',
 '/usr/local/lib/python2.7/site-packages/pycurl-7.43.0-py2.7-macosx-10.11-intel.egg',
 '/usr/local/lib/python2.7/site-packages/netCDF4-1.2.4-py2.7-macosx-10.11-intel.egg',
 '/usr/local/lib/python2.7/site-packages/cycler-0.10.0-py2.7.egg',
 '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python',
 '/usr/local/lib/python2.7/site-packages/cryptography-1.3.2-py2.7-macosx-10.11-intel.egg',
 '/usr/local/lib/python2.7/site-packages/cffi-1.6.0-py2.7-macosx-10.11-intel.egg',
 '/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg',
 '/usr/local/lib/python2.7/site-packages',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old',
 '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages/PyNGL',
 '/usr/local/lib/python2.7/site-packages/PyNIO',
 '/usr/local/lib/python2.7/site-packages/geos',
 '/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages',
 '/usr/local/Cellar/numpy/1.11.0/libexec/nose/lib/python2.7/site-packages',
 '/usr/local/Cellar/pillow/3.2.0/libexec/lib/python2.7/site-packages',
 '/Library/Python/2.7/site-packages’]
>>> print sys.executable
/usr/local/opt/python/bin/python2.7


$ echo $PYTHONPATH
/usr/local/lib/python2.7/site-packages
$ find ~/Library/Python -name '*site*' -or -name '*.pth'
find: /Users/heinzeller-d/Library/Python: No such file or directory
$ find /usr/local/lib/python2.7/site-packages -name '*site*' -or -name '*.pth'
/usr/local/lib/python2.7/site-packages
/usr/local/lib/python2.7/site-packages/easy-install.pth
/usr/local/lib/python2.7/site-packages/geos.pth
/usr/local/lib/python2.7/site-packages/homebrew-matplotlib-bundle.pth
/usr/local/lib/python2.7/site-packages/homebrew-numpy-nose.pth
/usr/local/lib/python2.7/site-packages/homebrew-pillow-nose.pth
/usr/local/lib/python2.7/site-packages/matplotlib/tests/baseline_images/test_image/image_composite_alpha.pdf
/usr/local/lib/python2.7/site-packages/matplotlib/tests/baseline_images/test_image/image_composite_alpha.png
/usr/local/lib/python2.7/site-packages/matplotlib/tests/baseline_images/test_image/image_composite_alpha.svg
/usr/local/lib/python2.7/site-packages/matplotlib/tests/baseline_images/test_image/image_composite_background.pdf
/usr/local/lib/python2.7/site-packages/matplotlib/tests/baseline_images/test_image/image_composite_background.png
/usr/local/lib/python2.7/site-packages/matplotlib/tests/baseline_images/test_image/image_composite_background.svg
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/matplotlib/tests/baseline_images/test_image/image_composite_alpha.pdf
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/matplotlib/tests/baseline_images/test_image/image_composite_alpha.png
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/matplotlib/tests/baseline_images/test_image/image_composite_alpha.svg
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/matplotlib/tests/baseline_images/test_image/image_composite_background.pdf
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/matplotlib/tests/baseline_images/test_image/image_composite_background.png
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/matplotlib/tests/baseline_images/test_image/image_composite_background.svg
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/mpl_toolkits/axes_grid/parasite_axes.py
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/mpl_toolkits/axes_grid/parasite_axes.pyc
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/mpl_toolkits/axes_grid1/parasite_axes.py
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg/mpl_toolkits/axes_grid1/parasite_axes.pyc
/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-nspkg.pth
/usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid/parasite_axes.py
/usr/local/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py
/usr/local/lib/python2.7/site-packages/Ngl.pth
/usr/local/lib/python2.7/site-packages/Nio.pth
/usr/local/lib/python2.7/site-packages/setuptools/site-patch.py
/usr/local/lib/python2.7/site-packages/setuptools/site-patch.pyc
/usr/local/lib/python2.7/site-packages/site.py
/usr/local/lib/python2.7/site-packages/site.pyc
/usr/local/lib/python2.7/site-packages/sitecustomize.py
/usr/local/lib/python2.7/site-packages/sitecustomize.pyc



imk-ifu-l257b1:~ heinzeller-d$ for file in `find /usr/local/lib/python2.7/site-packages -name '*.pth'`; do echo $file; cat $file; echo ""; done

/usr/local/lib/python2.7/site-packages/easy-install.pth
import sys; sys.__plen = len(sys.path)
./paramiko-2.0.0-py2.7.egg
./pyasn1-0.1.9-py2.7.egg
./cryptography-1.3.2-py2.7-macosx-10.11-intel.egg
./cffi-1.6.0-py2.7-macosx-10.11-intel.egg
./ipaddress-1.0.16-py2.7.egg
./enum34-1.1.5-py2.7.egg
./setuptools-21.0.0-py2.7.egg
./idna-2.1-py2.7.egg
./pycparser-2.14-py2.7.egg
./pycurl-7.43.0-py2.7-macosx-10.11-intel.egg
./netCDF4-1.2.4-py2.7-macosx-10.11-intel.egg
./matplotlib-1.5.1-py2.7-macosx-10.11-intel.egg
./cycler-0.10.0-py2.7.egg
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
import sys; new = sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p = getattr(sys, '__egginsert', 0); sys.path[p:p] = new; sys.__egginsert = p + len(new)

/usr/local/lib/python2.7/site-packages/geos.pth
# .pth file for the geos extensions
geos
/usr/local/lib/python2.7/site-packages/homebrew-matplotlib-bundle.pth
/usr/local/Cellar/matplotlib/1.5.1/libexec/lib/python2.7/site-packages

/usr/local/lib/python2.7/site-packages/homebrew-numpy-nose.pth
/usr/local/Cellar/numpy/1.11.0/libexec/nose/lib/python2.7/site-packages

/usr/local/lib/python2.7/site-packages/homebrew-pillow-nose.pth
/usr/local/Cellar/pillow/3.2.0/libexec/lib/python2.7/site-packages

/usr/local/lib/python2.7/site-packages/matplotlib-1.5.1-py2.7-nspkg.pth
import sys, types, os;p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('mpl_toolkits',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and sys.modules.setdefault('mpl_toolkits', types.ModuleType('mpl_toolkits'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)

/usr/local/lib/python2.7/site-packages/Ngl.pth
PyNGL

/usr/local/lib/python2.7/site-packages/Nio.pth
PyNIO


Commenting out the offending line /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python in /usr/local/lib/python2.7/site-packages/easy-install.pth solves all the problems. Don’t know how it got in there, though, but at least it works. Thanks, and if I can help to figure out why that happened please let me know.

Cheers

Dom

**Comment by tdsmith** [comment]
> Commenting out the offending line /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python in /usr/local/lib/python2.7/site-packages/easy-install.pth solves all the problems. Don’t know how it got in there, though, but at least it works. Thanks, and if I can help to figure out why that happened please let me know.

:+1:, that's definitely the right thing to do. No idea how it could have got there. Thanks for figuring it out!
