### ISSUE TITLE
`clamav` formulae has incorrect LaunchDaemon definition for MacOS

### ISSUE THREAD

**Issue by kkovaletp** [Homebrew/homebrew-core#156684]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.1.24
ORIGIN: https://github.com/Homebrew/brew
HEAD: ab6a7ed5a122b6d4f9d441ef76c86032398ced5f
Last commit: 2 days ago
Core tap JSON: 07 Dec 08:11 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BAT_THEME: GitHub
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 30
HOMEBREW_DISPLAY: :0.0
HOMEBREW_EDITOR: /usr/local/bin/micro
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.5.0 => /usr/local/opt/curl/bin/curl
macOS: 14.1.1-x86_64
CLT: 15.0.0.0.1.1694021235
Xcode: N/A

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  powerlevel10k

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  exa
  openssl@1.1

Warning: Found Ruby file outside goodwithtech/r tap formula directory.
(/usr/local/Homebrew/Library/Taps/goodwithtech/homebrew-r/Formula):
  /usr/local/Homebrew/Library/Taps/goodwithtech/homebrew-r/dockle.rb

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  handbrake
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I've installed the `clamav` formulae on my mac from `brew` and found that the service definition (LaunchDaemon) is incorrect: the one for `freshclam` is missing and the one for `clamd` contains incorrect or not optimal configuration, as it runs the `clamd` not in its daemon mode, but as a foreground process, which disables the switch user functionality and some other features.

### What happened (include all command output)?

N/A, as this is configuration issue, but I'll use this field to copy here the initial `clamd` plist file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.clamav</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/opt/clamav/sbin/clamd</string>
		<string>--foreground</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

### What did you expect to happen?

Here is my own plists for `freshclam` and `clamav` LaunchDaemons. I'm unfamiliar with the way they have to be aligned with the formulae and integrated with the `brew`, so I don't know how to create a PR (even after checking the help page from the previous step of submit issue form here). That is why I submit this issue with all the details, so formulae's maintainers will be able to pick it up and implement.

correct plist for `freshclam`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>net.clamav.freshclamd</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/opt/clamav/bin/freshclam</string>
        <string>-d</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>Nice</key>
    <integer>15</integer>
    <key>UserName</key>
    <string>clamav</string>
    <key>GroupName</key>
    <string>clamav</string>
    <key>LaunchOnlyOnce</key>
    <true/>
</dict>
</plist>
```

correct plist for `clamd`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>net.clamav.clamd</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/opt/clamav/sbin/clamd</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>Nice</key>
    <integer>15</integer>
    <key>UserName</key>
    <string>clamav</string>
    <key>GroupName</key>
    <string>clamav</string>
    <key>LaunchOnlyOnce</key>
    <true/>
</dict>
</plist>
```

In case a LaunchDaemon is going to be started on-demand manually and shouldn't start automatically on system boot, the next (both) settings need to be set to `false`:
```xml
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
```
in my case it is useful, as I run the `clamd` only during the scan process, all other time it is not running. `fleshclam` on other side, wakes up only to send single call to server to check for updates, and then sleeps till the next time, so it has no impact on the system performance or battery life and could be defined with the regular LaunchDaemon definition.

I don't know what exactly was the idea behind the:
```xml
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
```
so I didn't include it into my configuration. If you know for sure what exactly it does and why is it needed here, you might add it as well.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install clamav
ls -lah $(brew --prefix)/opt/clamav/
cat $(brew --prefix)/opt/clamav/*.plist
```

**Comment by kkovaletp** [comment]
Really? It hasn't even been reviewed by anyone from the project so far. `github-actions` shouldn't close incoming issues (as far as there should be a review process for incoming issues in the team), otherwise it looks like the team doesn't care about reported issues.

**Comment by SMillerDev** [comment]
If it's stale nobody has any interest in working on it. We'll happily review pull requests, but for issues if nobody is interested stalebot will close it.

**Comment by arpieb** [comment]
Just installed the `clamav` package and running into the same problem + error.  I can manually start `clamd` using old instructions found [here](https://gist.github.com/mendozao/3ea393b91f23a813650baab9964425b9) so the package install appears to be OK otherwise.  

Looks like @remino added this in #139384, maybe he could assist with the update?  I would, but I know squat re macOS services.

**Comment by Jerry1144** [comment]
I do not use `clamav` but wanted to help anyways. Feel free to incorporate these into a PR, for these are only hypothetical solutions^[1]. I've only tested these blocks by adding them into other formulae (faster to compile), and checked the resulting .plist files.

Formula edits^[2]:
---
Change service blocks:
```
  service do
    name macos: "net.clamav.clamd"  # Specifies the plist name; if coming with run, specifies the generated plist name.
    run macos: [opt_sbin/"clamd"]   # No idea if this path applies to Linux installs as well
    run_at_load false               # Defaults to true otherwise
    keep_alive false
    launch_only_once true
    require_root true               # prints a Warning if `brew services start` without sudo
    sockets "/tmp/clamd.socket"     # Is this what LocalSockets setting make?
  end
```
```
  service do
    name macos: "net.clamav.freshclamd"
    run macos: [opt_sbin/"freshclam", "-d"]
    keep_alive true
    launch_only_once true
    require_root true
    process_type :background        # My interpretion of Nice-15
  end
```

Then somehow patch the generated plist files after `make install` (I don't know how to write a `inreplace "net.clamav.clamd.plist" do` for this, but the idea should be matching before the final `\t<key>RunAtLoad</key>` lines):
```
diff --git a/net.clamav.clamd.plist b/net.clamav.clamd.plist
index 7f58bb5..fa74ff2 100644
--- a/net.clamav.clamd.plist
+++ b/net.clamav.clamd.plist
@@ -18,6 +18,10 @@
 	<array>
 		<string>/usr/local/opt/x264/sbin/clamd</string>
 	</array>
+	<key>UserName</key>
+	<string>clamav</string>
+	<key>GroupName</key>
+	<string>clamav</string>
 	<key>RunAtLoad</key>
 	<false/>
 </dict>
```
```
diff --git a/net.clamav.freshclamd.plist b/net.clamav.freshclamd.plist
index 556f618..07812a1 100644
--- a/net.clamav.freshclamd.plist
+++ b/net.clamav.freshclamd.plist
@@ -23,6 +23,10 @@
 		<string>/usr/local/opt/x264/sbin/freshclam</string>
 		<string>-d</string>
 	</array>
+	<key>UserName</key>
+	<string>clamav</string>
+	<key>GroupName</key>
+	<string>clamav</string>
 	<key>RunAtLoad</key>
 	<true/>
 </dict>
```
Note that plists use tabs! The diff files as gists: https://gist.github.com/Jerry1144/a596818c4b17804514a92e9022e6aa55

Then the Caveat block. __Users of clamav please note if it's accurate__:
```
  def caveats
    <<~EOS
      To finish installation & run clamav you will need to edit the example conf
      files at #{etc}/clamav/, and run freshclam to download the database.
      Then register clamd as LaunchDaemon: `sudo brew services start clamav`
      To register freshclam as LaunchDaemon, put #{prefix}/net.clamav.freshclam.plist
      into /Library/LaunchDaemons/
      then `sudo chown` the database file to be owned by user `clamav:clamav`
    EOS
  end

```
Whose output would be: ^[3]
```
==> Caveats
To finish installation & run clamav you will need to edit the example conf
files at /usr/local/etc/clamav/, and run freshclam to download the database.
Then register clamd as LaunchDaemon: `sudo brew services start clamav`
To register freshclam as LaunchDaemon, put /usr/local/opt/clamav/net.clamav.freshclam.plist
into /Library/LaunchDaemons/
then `sudo chown` the database file to be owned by user `clamav:clamav`

To start clamav now and restart at login:
  brew services start clamav
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/x264/sbin/clamd
```
Notes
---
[1]: Brew does not currently provide facilities to install _two_ services at once - a later service block in the formula simply overrides a former one. Nor does it have corresponding keys for UserName and GroupName. 
- Is it possible to call [`to_plist`](https://rubydoc.brew.sh/Homebrew/Service.html#to_plist-instance_method) in the first `service do` block to generate a plist artifact? Preferably the updater service `freshclam`, later being shadowed by the scan service `clamd`.

[2]: The `require_root true` line only causes `brew service start` to output a warning,
```
Warning: [] must be run as root to start at system startup!
```
instead of making it _downright refuse_ to put the .plist file into `~/LaunchAgents/`.

[3]: The `service do` block automatically generates a Caveat:
```
To start [] now and restart at login:
  brew services start []
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/[]/sbin/freshclam -d
```
These words don't go well with our supplied Caveats…

**Comment by kkovaletp** [comment]
@Jerry1144, thanks a lot for your efforts to create so detailed post with instructions and your investigation results!
However, I'm not familiar with the brew formulae creation process, and from your description, it looks to me like a complex task (with many corner cases to be taken into account).
So, I'm not skilled enough to make a PR. Instead, I'll try to help as far as I can to anyone, who can do a PR and implement all the reported things.

**Comment by remino** [comment]
Haven't logged in for a while and I just saw this now. I'll see if I can help tonight. Thanks for bringing this us.
