### ISSUE TITLE
SHA256 Mismatch

### ISSUE THREAD

**Issue by photoemulator** [Homebrew/homebrew-core#156904]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Verifying checksum for 'a4872869029d02f83aefe6eefd985a3528e2440e25bdbe9d45fb31e4401efbf9--schilytools-2023-09-28.tar.gz'
Error: SHA256 mismatch
Expected: 564ea2365876a53eba02f184c565016399aee188c26d862589906cf3f92198e6
Actual: c813cc19a320f8d3b5d82f5b1ca6a93ab1bb5f4c50f86fdac58101fe472d2143
File: /Users/PhotoPro/Library/Caches/Homebrew/downloads/a4872869029d02f83aefe6eefd985a3528e2440e25bdbe9d45fb31e4401efbf9--schilytools-2023-09-28.tar.gz
To retry an incomplete download, remove the file above.

Can't get past this when running
brew update && brew upgrade && brew cleanup

I can remove the file, but when I go to run the above commands again, I get stopped here.

Can someone tell me if the checksum has been updated?
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Just run 
brew update -v && brew upgrade -v && brew cleanup

### What happened (include all command output)?

OUTPUT:
Verifying checksum for 'a4872869029d02f83aefe6eefd985a3528e2440e25bdbe9d45fb31e4401efbf9--schilytools-2023-09-28.tar.gz'
Error: SHA256 mismatch
Expected: 564ea2365876a53eba02f184c565016399aee188c26d862589906cf3f92198e6
Actual: c813cc19a320f8d3b5d82f5b1ca6a93ab1bb5f4c50f86fdac58101fe472d2143
File: /Users/PhotoPro/Library/Caches/Homebrew/downloads/a4872869029d02f83aefe6eefd985a3528e2440e25bdbe9d45fb31e4401efbf9--schilytools-2023-09-28.tar.gz
To retry an incomplete download, remove the file above.

But with what recommendations I've found, there is no joy.  No fix.  And I can't get past this error.

### What did you expect to happen?

I've removed the file and run:
brew cleanup && brew update

but the response returns me to the same issue

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update -v && brew upgrade -v && brew cleanup
```

**Comment by SMillerDev** [comment]
Please add the `brew doctor` and `brew config` output. This can be reopened when we have the required information.
