### ISSUE TITLE
AttributeError: module 'numpy' has no attribute '__version__'

### ISSUE THREAD

**Issue by shongololo** [Homebrew/homebrew-core#15698]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>`: [link to gist](https://gist.github.com/b84713cd39cddf8e061f4fae401a325d)

To help us debug your issue please explain:
- What you were trying to do (and why)
When installing a package with the `--with-python3` flag if that package has a dependency on numpy.
- What happened (include command output)
```
  File "setup.py", line 184, in <module>
    result = package.check()
  File "/private/tmp/matplotlib-20170717-87843-1j63d2q/matplotlib-2.0.2/setupext.py", line 894, in check
    if not is_min_version(numpy.__version__, min_version):
AttributeError: module 'numpy' has no attribute '__version__'
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [2.0.2]
                python: yes [3.6.1 (default, Apr  4 2017, 09:40:21)  [GCC
                        4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]]
              platform: yes [darwin]
```
- What you expected to happen
For the package to install without raising a numpy error.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install matplotlib --with-python3`

**Comment by shongololo** [comment]
`brew link --overwrite numpy` seems to have fixed the issue

**Comment by ilovezfs** [comment]
>brew link --overwrite numpy seems to have fixed the issue

Glad you were able to sort this out!
