### ISSUE TITLE
HDF5 incomplete without building with CMake

### ISSUE THREAD

**Issue by jpfeuffer** [Homebrew/homebrew-core#157078]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs hdf5
Error: No logs.

# but should be irrelevant since the installation is successful but incomplete (please read further)
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

In CMake: 
`find_package(HDF5 CONFIG ... )`

To find HDF5 in my tool/lib.

### What happened (include all command output)?

Fail.

```
[cmake] CMake Error at cmake/cmake_findExternalLibs.cmake:172 (find_package):
[cmake]   Could not find a package configuration file provided by "HDF5" with any of
[cmake]   the following names:
[cmake] 
[cmake]     HDF5Config.cmake
[cmake]     hdf5-config.cmake
```

### What did you expect to happen?

Find HDF5 successfully.

Requirement would be the config files that hdf5 comes with if you built it with CMake.

https://forum.hdfgroup.org/t/can-we-retire-the-autotools/10362
Looks like many people are in favour of retiring autotools.

Also ".pc" files were requested before, which are only available with CMake:
https://github.com/Homebrew/homebrew-core/issues/61490
And one can IMHO not say anymore that autotools is "the recommended" way (rather the other way round).
(Especially since the then-opened issue was one of the first ever and has not been addressed in their autotools build in almost 4 years https://github.com/HDFGroup/hdf5/issues/8 )

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# Something like this (but the problem should obvious by just inspecting what you are installing during the hdf5 build which uses autotools).

brew install hdf5

echo "find_package(HDF5 CONFIG)" >> script.cmake

cmake -P script.cmake
```

**Comment by SMillerDev** [comment]
@jpfeuffer how do we stop it from compiling in hardcoded paths for everything though?

**Comment by jpfeuffer** [comment]
Cool! Thanks for starting this.
Can you give me an example?
I can try with my general cmake knowledge but I could also contact the HDF5 people.

**Comment by jpfeuffer** [comment]
Do you mean paths to shared libraries? In that case I would need to know what the policies for homebrew are.
I assume you are using rpaths or something like that?

**Comment by SMillerDev** [comment]
No, shared libraries seem fine. What I'm looking for is things like:
```console
$ strings /opt/homebrew/bin/h5diff | grep /opt
Installation point: /opt/homebrew/Cellar/hdf5/1.14.3
C Compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang 15.0.0.15000100
```

**Comment by jpfeuffer** [comment]
I totally agree.. unfortunately there seem to be A LOT of hardcoded paths in the different binaries. I asked on the HDF5 for now.
Do we know if this was different with autoconf?
And more importantly, is this the only problem? Looks like h5cc is not executing correctly, right?

One thing I saw is that you are currently not enabling C++ and Fortran (but I think they should not be necessary for h5cc).

**Comment by jpfeuffer** [comment]
Hi! I just wanted to revive this discussion. Meanwhile I received an [answer](https://forum.hdfgroup.org/t/switching-homebrew-to-cmake-build-harcoded-paths-in-binaries/11905/7) from the HDF5 staff that confirms that the hardcoded build information is not used by the programs and is therefore no issue for the functionality of the binaries.

The build information seemingly comes from [this](https://github.com/HDFGroup/hdf5/blob/772276ea1f6f8b150a22eff3a908eff24ccc50a7/src/H5build_settings.cmake.c.in#L22) file, that is only included in the binaries with the CMake build. It seems merely informative for debugging.

I think the strings to the source files come from the `__FILE__` macro and they might be different (in CMake) from what autotools creates based on how the source files are passed to the compiler. The developers say they are also seeing information from the source files in errors so I guess it can be considered "normal".

Is this a hard rule for homebrew or can we ignore/acknowledge this problem and continue if it does not affect functionality?
If so, I think we should enable C++ and Fortran to see if the tests go further.

**Comment by SMillerDev** [comment]
> The developers say they are also seeing information from the source files in errors so I guess it can be considered "normal".

The way Homebrew builds and in doing so intercepts compiler calls, this information will be pretty useless to most people. For autotools we could still override it, but for CMake it'll likely just make it much harder to use HDF5.

**Comment by jpfeuffer** [comment]
Sorry, but can you elaborate?
I don't think you have to change or intercept anything. The binaries should work as is, they just contain unnecessary but non-harmful information.
And I would say that 99% of the users will not run "strings" on their binaries. Regarding error messages: It should not matter much if users see `Exception in line 9 of /opt/homebrew/hdf5/src/foo.c` or `Exception in line 9 of hdf5/src/foo.c` since none of those files will be present. It will just be used for reporting.
But that is just my opinion since I think the CMake config and pkgconfig are bigger upsides than this downside.

If it is a strict rule however, we should file a bug report at HDF5 GitHub and ask the developers if they are willing to change that. They probably need to reimplement the `__FILE__` macro then and add a switch to not include the "Build information" header in every binary.

**Comment by jpfeuffer** [comment]
You can also just add `-DCMAKE_CXX_FLAGS="-fmacro-prefix-map=/opt/homebrew/=." -DCMAKE_C_FLAGS="-fmacro-prefix-map=/opt/homebrew=."` to replace your build folder with a dot in the built-in macros like "__FILE__".

And the config.in file that I mentioned in my previous comment can be easily grepped to remove the information that you think is harmful.

**Comment by SMillerDev** [comment]
> Regarding error messages: It should not matter much if users see Exception in line 9 of /opt/homebrew/hdf5/src/foo.c or Exception in line 9 of hdf5/src/foo.c since none of those files will be present. It will just be used for reporting.

It'll say something like `/tmp/fsdhkfhsdk/brewfkjshfkdsj/build/hdf5-1.2.3/hdf5/src/foo.c` though. Being compiled by `/opt/homebrew/Library/Homebrew/something/something/shims/clang`, which could be either pointing to gcc or clang.

**Comment by jpfeuffer** [comment]
Regarding error messages from macros: My suggestion still stands. You can use `$pwd` or `$BUILD_FOLDER` (you probably have such a variable) in the compiler flag.

Regarding shims, you are replacing the shims for autotools as well, so why don't you replace them for Cmake? You just need to choose another file.

```
    # Avoid shims in settings file
    inreplace_files = %w[
      src/H5build_settings.c
      src/libhdf5.settings
      src/Makefile
    ]
```

becomes

```
    # Avoid shims in settings file
    inreplace_files = %w[
      src/H5build_settings.cmake.c.in   <--- note this
      src/libhdf5.settings
    ]
```

And of course you have to run this *before* the build.

**Comment by jpfeuffer** [comment]
My bad, see my comment in the PR. You apparently want to do it after cmake configuration, when the actual paths are already in the file. In this case your path `build/src/H5build_settings.c` was correct since the file is renamed during configuration.
I think the only mistake was then the order of replacing and building.

**Comment by eli-schwartz** [comment]
I'm not aware offhand of a single linux distro that uses anything but the autotools files to build hdf5. Usually with notes that the cmake build is badly broken.



> Also ".pc" files were requested before, which are only available with CMake:
> #61490
> And one can IMHO not say anymore that autotools is "the recommended" way (rather the other way round).
> (Especially since the then-opened issue was one of the first ever and has not been addressed in their autotools build in almost 4 years [HDFGroup/hdf5#8](https://github.com/HDFGroup/hdf5/issues/8) )

Linux distros are so convinced that the cmake build of hdf5 is irreparably broken that they will even configure with cmake just to generate the pkg-config files, install the pkg-config files on their own using `cp`, and build and install with autotools.
