### ISSUE TITLE
Snappy - missing libsnappy.a after upgrade to v1.1.6

### ISSUE THREAD

**Issue by narekgharibyan** [Homebrew/homebrew-core#15722]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
   **I have upgraded from snappy 1.1.3 to 1.1.6**
- What happened (include command output)
  **v1.1.3 was containing static lib `libsnappy.a` along with dynamic libs.**
   **However v1.1.6 install only dynamic libraries**
```
 ➜  snappy git:(master) ✗ ls /usr/local/Cellar/snappy/1.1.6/lib 
    cmake  libsnappy.1.1.6.dylib  libsnappy.1.dylib  libsnappy.dylib
```
- What you expected to happen
**I expect static library `libsnappy.a` to be present after install/upgrade v1.1.6**
- Step-by-step reproduction instructions (by running `brew install` commands)
```
➜  snappy git:(master) ✗ brew install snappy --force 
==> Downloading https://homebrew.bintray.com/bottles/snappy-1.1.6.sierra.bottle.tar.gz
Already downloaded: /Users/narek/Library/Caches/Homebrew/snappy-1.1.6.sierra.bottle.tar.gz
==> Pouring snappy-1.1.6.sierra.bottle.tar.gz
==> Using the sandbox
  /usr/local/Cellar/snappy/1.1.6: 18 files, 214.1KB
```
# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by mbanyar033** [comment]
@narekgharibyan 

_Sent from my Samsung SM-N900 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ilovezfs** [comment]
This is an upstream issue. Please feel free to :+1: https://github.com/google/snappy/pull/38.

**Comment by pwnall** [comment]
@ilovezfs I put together https://github.com/pwnall/snappy/tree/shared_build, which uses the same approach as other Google projects. Can you please try and see if you can get things working with this branch?

You'd have to build snappy twice. One build uses the default options and gives you the static library, the other build specifies `-DBUILD_SHARED_LIBS=1` and gives you the shared library.

**Comment by ilovezfs** [comment]
@pwnall sure!

**Comment by ilovezfs** [comment]
@pwnall 
```
iMac-TMP:~ joe$ find /usr/local/Cellar/snappy/HEAD-4541ad1
/usr/local/Cellar/snappy/HEAD-4541ad1
/usr/local/Cellar/snappy/HEAD-4541ad1/.brew
/usr/local/Cellar/snappy/HEAD-4541ad1/.brew/snappy.rb
/usr/local/Cellar/snappy/HEAD-4541ad1/AUTHORS
/usr/local/Cellar/snappy/HEAD-4541ad1/COPYING
/usr/local/Cellar/snappy/HEAD-4541ad1/INSTALL_RECEIPT.json
/usr/local/Cellar/snappy/HEAD-4541ad1/NEWS
/usr/local/Cellar/snappy/HEAD-4541ad1/README.md
/usr/local/Cellar/snappy/HEAD-4541ad1/include
/usr/local/Cellar/snappy/HEAD-4541ad1/include/snappy-c.h
/usr/local/Cellar/snappy/HEAD-4541ad1/include/snappy-sinksource.h
/usr/local/Cellar/snappy/HEAD-4541ad1/include/snappy-stubs-public.h
/usr/local/Cellar/snappy/HEAD-4541ad1/include/snappy.h
/usr/local/Cellar/snappy/HEAD-4541ad1/lib
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/cmake
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/cmake/Snappy
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/cmake/Snappy/SnappyTargets-release.cmake
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/cmake/Snappy/SnappyTargets.cmake
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/cmake/SnappyConfig.cmake
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/cmake/SnappyConfigVersion.cmake
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.1.1.6.dylib
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.1.dylib
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.a
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.dylib
```

```
diff --git a/Formula/snappy.rb b/Formula/snappy.rb
index c1870d2..44fdb23 100644
--- a/Formula/snappy.rb
+++ b/Formula/snappy.rb
@@ -3,7 +3,7 @@ class Snappy < Formula
   homepage "https://google.github.io/snappy/"
   url "https://github.com/google/snappy/archive/1.1.6.tar.gz"
   sha256 "6fa92cde5b2caefd0d9a60336991ba42e5a7ddc3bdc36c5610451373751d0495"
-  head "https://github.com/google/snappy.git"
+  head "https://github.com/pwnall/snappy.git", :branch => "shared_build"
 
   bottle do
     cellar :any
@@ -18,6 +18,9 @@ class Snappy < Formula
   def install
     system "cmake", ".", *std_cmake_args
     system "make", "install"
+    system "make", "clean"
+    system "cmake", ".", "-DBUILD_SHARED_LIBS=1", *std_cmake_args
+    system "make", "install"
   end
 
   test do
```

**Comment by pwnall** [comment]
@ilovezfs Thank you very much for your testing! Is it correct to assume that the formula diff above results in both a static and a shared library and (combined with my Snappy branch) is a fix for this issue?

**Comment by ilovezfs** [comment]
@pwnall you're welcome!

>Is it correct to assume that the formula diff above results in both a static and a shared library

Yes.

>and (combined with my Snappy branch) is a fix for this issue?

Yes.

**Comment by ilovezfs** [comment]
See the
```
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.1.1.6.dylib
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.1.dylib
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.a
/usr/local/Cellar/snappy/HEAD-4541ad1/lib/libsnappy.dylib
```
above :)

**Comment by ilovezfs** [comment]
@narekgharibyan this is now fixed if you `brew update` and `brew upgrade` to snappy 1.1.7.

**Comment by narekgharibyan** [comment]
@ilovezfs thanks!
