### ISSUE TITLE
R tries to use wrong /usr/bin/install after xcode update ("INSTALL: illegal option -- l")

### ISSUE THREAD

**Issue by adamaltmejd** [Homebrew/homebrew-core#15724]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

After what I think must have been updating Xcode to 8.3.3. R started behaving wierdly with any attempt to installing and loading packages failing. Stating that:

```
INSTALL: illegal option -- l
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```

Seems like R calls /usr/bin/install which is an old version that doesn't have the -l flag. Furthermore, when trying to start RStudio I get the following message.

```
Unable to find libR.dylib in expected locationswithin R Home directory /usr/local/Cellar/r/3.4.1/lib/R; Unable to find libR.dylib in expected locationswithin R Home directory /Library/Frameworks/R.framework/Resources
```

Installing R as a framework with the installer instead resolves the issues, so it seems like it has something to do with Homebrew. I have tried to install R from source (with and without openblas) and also rebuilt GCC before installing. What else could be wrong?

Gist log: https://gist.github.com/anonymous/c85e6426bce8b0fe5bc6799b07f74197

**Comment by MikeMcQuaid** [comment]
@luisspuerto Can you try:

```
brew pull 15723
brew uninstall --force r
brew install --build-from-source r
```

that's a different approach we're trying that hopefully should fix your issue.

**Comment by MikeMcQuaid** [comment]
> with any attempt to installing and loading packages failing

What command did/do you run to do that?

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/15723.

**Comment by adamaltmejd** [comment]
Thanks a bunch! Works now
