### ISSUE TITLE
Linux install stuck

### ISSUE THREAD

**Issue by alfonsocv12** [Homebrew/homebrew-core#157288]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I'm trying to install homebrew not currently installed
```

### Verification

- [x] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I run these commands as advice on the homebrew website

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

### What happened (include all command output)?

```
==> Checking for `sudo` access (which may request your password)...
```

### What did you expect to happen?

Install Homebrew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I'm using Debian Trixie, kernel 6.5, gets stuck in
```

**Comment by SMillerDev** [comment]
This should be filed in https://github.com/Homebrew/install/issues

**Comment by alfonsocv12** [comment]
Thanks I'll do
