### ISSUE TITLE
fontforge 20161012_2 fails to build: Prerequisite 'automake' not found.

### ISSUE THREAD

**Issue by Alhadis** [Homebrew/homebrew-core#15734]
~~~
bootstrap:   error: Prerequisite 'automake' not found. Please install it, or
bootstrap:          'export AUTOMAKE=/path/to/automake'.
bootstrap:   error: Program    Min_version Homepage                            
bootstrap:          -----------------------------------------------------------
bootstrap:          git        1.5.5       http://git-scm.com                  
bootstrap:          perl       5.5         http://perl.com                     
bootstrap:          tar        -           http://www.gnu.org/s/tar            
bootstrap:          autoconf   2.68        http://www.gnu.org/s/autoconf       
bootstrap:          automake   -           http://www.gnu.org/s/automake       
bootstrap:          -----------------------------------------------------------
~~~

- { 𝒳 } **Yep, I've** *confirmed this is a problem with* `brew install`*ing one, specific formula (not cask) and not every time you run `brew`?*
- { 𝒳 } **Yep, I** *ran `brew update` and retried my prior step* **about 4-5 times.**
- { 𝒳 } *Ran `brew doctor`, fixed all issues and retried your prior step?* **Yeah; the doctor whined about a [`.curlrc` file](https://github.com/Alhadis/.files/blob/769385754e0e89f1b578f98d7e846f1d014781d0/.curlrc) in my dotfiles directory, but I doubt it means anything.**
- { 𝒳 } *Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?* **[Merry Christmas](https://gist.github.com/d581fda0450be2a41e41230b9acb0131).**
- { 𝒳 } *If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?* **It did work, but I ran it anyway. Doctor complained about my curlrc and said my heart-rate was worrying.**

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

<img src="https://user-images.githubusercontent.com/2346707/28330081-905e1374-6c2f-11e7-9e0b-e1111c0742ee.jpg" width="256" alt="" />

## ***... WHOOOOAAAA THERE***.

------------------

I'm at a loss to explain why this is happening, because I haven't touched `automake`, or `auto-` anything. The only thing I can think of is an update I was prompted to install by Xcode when I opened it to install [`digitalmoksha/QLCommonMark`](https://github.com/digitalmoksha/QLCommonMark). Would compiling `QLCommonMark.qlgenerator` (and dropping it into a newly-created `~/Library/QuickLook/`) have had any impact...?

**Comment by ilovezfs** [comment]
```
ls -al /usr/local/opt/automake/bin
```

**Comment by Alhadis** [comment]
~~~
total 1152
drwxr-xr-x   6 johngardner  admin     204 21 Jun 16:03 .
drwxr-xr-x  11 johngardner  admin     374 21 Jun 16:03 ..
-r-xr-xr-x   2 johngardner  admin   36879 21 Jun 16:03 aclocal
-r-xr-xr-x   2 johngardner  admin   36879 21 Jun 16:03 aclocal-1.15
-r-xr-xr-x   2 johngardner  admin  253346 21 Jun 16:03 automake
-r-xr-xr-x   2 johngardner  admin  253346 21 Jun 16:03 automake-1.15
~~~

**Comment by ilovezfs** [comment]
brew uninstall automake

then try again.

**Comment by Alhadis** [comment]
~~~console
λ Desktop: brew uninstall automake
Warning: Use hdf5 instead of deprecated homebrew/science/hdf5
Warning: Use hdf5 instead of deprecated homebrew/science/hdf5
Warning: Use hdf5 instead of deprecated homebrew/science/hdf5
Uninstalling /usr/local/Cellar/automake/1.15.1... (131 files, 3.0MB)
λ Desktop: brew install automake
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
pgcli

==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring automake-1.15.1.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/automake/1.15.1: 131 files, 3.0MB
λ Desktop: brew upgrade
==> Upgrading 1 outdated package, with result:
fontforge 20161012_2
==> Upgrading fontforge --with-extra-tools --with-libspiro
==> Using the sandbox
==> Downloading https://github.com/fontforge/fontforge/archive/20161012.tar.gz
Already downloaded: /Users/johngardner/Library/Caches/Homebrew/fontforge-20161012.tar.gz
==> Cloning https://git.savannah.gnu.org/git/gnulib.git
Updating /Users/johngardner/Library/Caches/Homebrew/fontforge--gnulib--git
==> Checking out revision 29ea6d6fe2a699a32edbe29f44fe72e0c253fcee
==> ./bootstrap --gnulib-srcdir=/Users/johngardner/Library/Caches/Homebrew/fontforge--gnulib--git --skip-git
Last 15 lines from /Users/johngardner/Library/Logs/Homebrew/fontforge/01.bootstrap:

./bootstrap
--gnulib-srcdir=/Users/johngardner/Library/Caches/Homebrew/fontforge--gnulib--git
--skip-git

bootstrap:   error: Prerequisite 'automake' not found. Please install it, or
bootstrap:          'export AUTOMAKE=/path/to/automake'.
bootstrap:   error: Program    Min_version Homepage                            
bootstrap:          -----------------------------------------------------------
bootstrap:          git        1.5.5       http://git-scm.com                  
bootstrap:          perl       5.5         http://perl.com                     
bootstrap:          tar        -           http://www.gnu.org/s/tar            
bootstrap:          autoconf   2.68        http://www.gnu.org/s/autoconf       
bootstrap:          automake   -           http://www.gnu.org/s/automake       
bootstrap:          -----------------------------------------------------------

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
fontforge 20161012_2 fails to build: Prerequisite 'automake' not found. https://github.com/Homebrew/homebrew-core/issues/15734

λ Desktop: WHEEE, I\'M FAMOUS
-bash: WHEEE,: command not found
λ Desktop: 
~~~

**Comment by ilovezfs** [comment]
```
mkdir ~/homebrew-20170719
sudo mv /usr/local ~/homebrew-20170719
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install --with-extra-tools --with-libspiro fontforge
```

**Comment by Alhadis** [comment]
JFC, moving the *entire* `/usr/local` directory and reinstalling? This must be serious.

[Terminal output is up on PasteBin](https://pastebin.com/raw/vNXfXNdY).

Any particular steps I need to take to revert this, orrr... can I just rimraf the shit out of my new `/usr/local` directory and move `~/homebrew-20170719/local` back to where it was?

**Comment by ilovezfs** [comment]
>can I just rimraf the shit out of my new /usr/local directory and move ~/homebrew-20170719/local back to where it was?

Yes, but first try again in a new user account, with the throw away installation.

make new account
log in to new account
sudo chown -R $(whomai) /usr/local
try the install again

**Comment by Alhadis** [comment]
[Yeah, it worked](https://pastebin.com/raw/BfwmT1ah). So... what now?

**Comment by Alhadis** [comment]
I'm undoing this crap because everything is broken and I can't resume work on what I was doing.

One other thing that might be relevant: I [recently added](https://github.com/Alhadis/.files/commit/5bbb42fbfd67754b6e458b8cd7e544dec762162f) `rvm_project_rvmrc=0` to my environment variables, since I don't like the thought of a shell built-in being overridden by crap code I don't need or use (and I've wanted to nuke RVM into orbit for a long time, but it's probably required by something somewhere... ugh).

Sooo if disabling RVM's builtin overrides is causing this issue, I'd say we have an entirely new problem, then...

**Comment by ilovezfs** [comment]
Since it worked in another user account, it's likely something in your profile. Maybe it's what you're describing with rvm, or maybe it's something else. You can try moving your shell profile file out of the may and see if that makes any difference.

**Comment by Alhadis** [comment]
Commenting out `export rvm_project_rvmrc=0` does nothing, I'm afraid. Having said that, I'm out of theories.

[Here's the output](https://github.com/Alhadis/.files/blob/4633b624ba7c807432c6beec2e7c6e5d741ea39b/etc/install/Brewfile) of `brew bundle dump` in case it offers anything enlightening...

**Comment by ilovezfs** [comment]
did you try moving your .bash_profile out of the way?

**Comment by Alhadis** [comment]
Hey, that worked. Trouble is, I have no idea *why*...

I also noticed earlier before that `brew info python` and `brew info gobject-introspection` lists *two* installation paths per formula:

~~~console
λ Desktop: brew info gobject-introspection
gobject-introspection: stable 1.52.1 (bottled)
Generate introspection data for GObject libraries
https://live.gnome.org/GObjectIntrospection
/usr/local/Cellar/gobject-introspection/1.52.1 (172 files, 9.7MB)
  Poured from bottle on 2017-05-15 at 22:36:43
/usr/local/Cellar/gobject-introspection/1.52.1_1 (172 files, 9.7MB) *
  Poured from bottle on 2017-07-19 at 01:44:25
~~~

~~~console
phoenix:~ johngardner$ brew info python
python: stable 2.7.13 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org
/usr/local/Cellar/python/2.7.13 (3,619 files, 49.7MB)
  Poured from bottle on 2016-12-19 at 20:36:02
/usr/local/Cellar/python/2.7.13_1 (3,581 files, 48.9MB) *
  Poured from bottle on 2017-07-19 at 01:44:15
~~~

Is this normal?

I also don't think I've seen this message before in FontForge's `Caveats` block:

> Python modules have been installed and Homebrew's site-packages is not in your Python sys.path, so you will not be able to import the modules this formula installed. If you plan to develop with these modules, please run: `mkdir -p /Users/johngardner/Library/Python/2.7/lib/python/site-packages`

**Comment by ilovezfs** [comment]
>Is this normal?

Yes. You have to run `brew cleanup` to get rid of older version. `_1` means revision 1.

>I also don't think I've seen this message before in FontForge's Caveats block:

This is probably due to https://github.com/Homebrew/homebrew-core/pull/14408.

**Comment by Alhadis** [comment]
> This is probably due to #14408.

Ah. Yep, might be connected, since `fontforge` was one of the formulae affected by the `python` renaming...

I don't see how that could've lead to `automake` though...

**Comment by ilovezfs** [comment]
>I don't see how that could've lead to automake though...

yeah just the caveat.

**Comment by Alhadis** [comment]
Alrighty, well, guess I'll be closing this then... Thanks for your help. =)
