### ISSUE TITLE
Can't install HDF5's C++ Headers

### ISSUE THREAD

**Issue by LogicalKnight** [Homebrew/homebrew-core#15740]
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [N/A] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N/A] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Install HDF5 after migration from homebrew/science, but including the C++ headers.

- What happened (include command output)

Installed successfully, but without the C++ headers.

- What you expected to happen

I expected there to be an option to install the C++ headers (which is done in HDF5 via the --enable-cxx option) as was available previously. However, the formula's --enable-cxx is deprecated, and the warning message states:

```
Warning: hdf5: --enable-cxx was deprecated; using --with-cxx instead!
```

which is then followed by 

```
Warning: hdf5: this formula has no --with-cxx option so it will be ignored!
```

- Step-by-step reproduction instructions (by running `brew install` commands)

```
> brew install hdf5 --enable-cxx
Warning: hdf5: --enable-cxx was deprecated; using --with-cxx instead!
Warning: hdf5: this formula has no --with-cxx option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/hdf5-1.10.1.sierra.bottle.tar.gz
Already downloaded: /Users/xxx/Library/Caches/Homebrew/hdf5-1.10.1.sierra.bottle.tar.gz
==> Pouring hdf5-1.10.1.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/hdf5/1.10.1: 143 files, 11.7MB
```
And then no C++ headers!

Note that the `--c++11` doesn't add the C++ headers either.

**Comment by LogicalKnight** [comment]
Oh, and of course the C++ library (hdf5_cpp)

**Comment by ilovezfs** [comment]
We've reduced the option set as part of the migration. If you still need that particular option, please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

**Comment by LogicalKnight** [comment]
Okay thanks. Too bad, as this affects several others I work with who have been using Homebrew to install dependencies for a code I'm developing. It'll be more overhead, but my own tap would work.

**Comment by ilovezfs** [comment]
@LogicalKnight actually it was a formula bug! https://github.com/Homebrew/homebrew-core/pull/15771

**Comment by ilovezfs** [comment]
@LogicalKnight should be fixed now if you brew update and brew upgrade.

**Comment by LogicalKnight** [comment]
@ilovezfs Awesome! Thank you very much.

**Comment by ilovezfs** [comment]
You're welcome!
