### ISSUE TITLE
Please make Redis 3.2 available

### ISSUE THREAD

**Issue by bits01** [Homebrew/homebrew-core#15742]
After a recent brew upgrade, Redis 4.0.0 was installed and there doesn't seem to be a way to go back to Redis 3.2.x
The symlink `/usr/local/opt/redis@3.2` points to `../Cellar/redis/4.0.0/` which is not right.

**Comment by MikeMcQuaid** [comment]
As the issue template said: please submit a pull request if you need it, thanks.

**Comment by bits01** [comment]
You do have the template already as it was the default a few days ago. Please make it available. Currently having a link 3.2 that points to 4.0.0 seems like a bug, I doubt that was the intended behavior. Thank you.

**Comment by ilovezfs** [comment]
```
bash-3.2$ ls -l /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/redis*
lrwxr-xr-x  1 joe  admin  19 Jul 15 02:15 /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/redis@4.0 -> ../Formula/redis.rb
```

**Comment by MikeMcQuaid** [comment]
@bits01 Please submit a pull request, as requested by the issue template and by me.
