### ISSUE TITLE
brew-installed neovim 0.9.4 exits non-zero if `VimLeave * call system('true')` configured

### ISSUE THREAD

**Issue by mikepqr** [Homebrew/homebrew-core#157652]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/mikepqr/c44d42e1356418c53cc76d3e29f4c30f
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use the stable release of `neovim` with a `VimLeave * call system(...)` autocommand configured

### What happened (include all command output)?

```
$ nvim --clean  # i.e. ignore local configuration
```
then in neovim:
```
:autocmd VimLeave * call system("true")
:q
```
then back in the shell
```
$ echo $?
134
```

### What did you expect to happen?

The autocommand configured above means that neovim runs the shell executable `true` on exit, which should succeed and therefore ensure neovim's own exit code is 0, i.e.

```
$ echo $?
0
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install neovim
```
then follow the steps above.
```

**Comment by mikepqr** [comment]
Note that the following builds of vim/neovim do not reproduce this error, i.e. they exit with exit code 0 as expected:

- `brew install neovim --HEAD`
- a brew-installed version of neovim 0.8.1 that I have on another machine
- any official macOS build of neovim installed from https://github.com/neovim/neovim/releases, including neovim 0.9.4
- regular vim 9.0 installed with `brew install vim`

And neovim installed via `brew install neovim` (i.e. the version affected by this issue) exits with exit code 0:
- without an `autocommand VimLeave` configured
- with an `autocommand VimLeave` that does not call `system` configured, e.g. `:autocommand VimLeave * call echo hello` works fine

**Comment by SMillerDev** [comment]
Since the instructions don't actually reproduce the issue, you should file it with the developers of the tool.

**Comment by mikepqr** [comment]
As stated in the comment, this issue does not repro upstream. I only see it with the brew-installed version.

What does "the instructions don't actually reproduce the issue" mean? Does that mean you followed the repro instructions and did not see the same result? Or that you were not able to follow the repro instructions for some other reason?

**Comment by SMillerDev** [comment]
> Does that mean you followed the repro instructions and did not see the same result? 

Yes `brew install neovim` does not crash for me.

**Comment by mikepqr** [comment]
> Note that the following builds of vim/neovim do not reproduce this error, i.e. they exit with exit code 0 as expected:
>  -  a brew-installed version of neovim 0.8.1 that I have on another machine

Just ran `brew upgrade neovim` on this system and immediately reproduced the issue.
