### ISSUE TITLE
--with-default-names makes packages take considerably longer to install

### ISSUE THREAD

**Issue by caleb531** [Homebrew/homebrew-core#15786]
Hi,

I have recently noticed that when I install normally-prefixed packages with `--with-default-names`, they take a considerably longer to install. For example, `brew install grep` takes about 2-3 seconds to install, but `brew install grep --with-default-names` takes over a minute. The same applies to other packages that support `--with-default-names` (`gnu-sed`, `gnu-tar`, and `findutils`), each taking about 1 to 2 minutes longer to install when `--with-default-names` is passed.

I can't be certain if this is a bug with Homebrew itself or with the packages themselves, but considering that multiple packages are consistently displaying this behavior, I figure I'd start here. It seems that the package binaries are being completely recompiled (via `./configure` and `make`) for a simple prefix change I could make myself with `ln -s`. Even if this isn't a bug with Homebrew per se, I'd really like to understand *why* this is happening, and if there's anything that can be done to resolve the inefficiency (because it doesn't seem right).

## How to Reproduce

1. Run `brew uninstall --force grep` to make sure you're starting fresh
2. Run `brew install grep`; it should take a few seconds to install
3. Run `brew uninstall grep` to prepare for reinstalling below
4. Run `brew install grep --with-default-names`; it should take 1-2 minutes to install

Same steps  `gnu-sed`, `gnu-tar`, and `findutils`.

## Gist Logs  
https://gist.github.com/caleb531/016ab52cbf99ce0f8e6be397b517f130

## Checklist

- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
  - Trying to run `brew install grep --with-default-names`
- What happened (include command output)
  - Took a relatively long time to install
- What you expected to happen
  - I expect it to be even remotely close to the installation time for `brew install grep`
- Step-by-step reproduction instructions (by running `brew install` commands)
  - See above

### grep

```sh
~  ❯ time brew install grep
==> Downloading https://homebrew.bintray.com/bottles/grep-3.1.sierra.bottle.tar.g
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/grep-3.1.sierra.bottle.tar.gz
==> Pouring grep-3.1.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
...
==> Summary
🍺  /usr/local/Cellar/grep/3.1: 15 files, 860KB

real	0m2.400s
user	0m1.612s
sys	0m0.655s 
~  ❯ brew uninstall grep
Uninstalling /usr/local/Cellar/grep/3.1... (15 files, 860KB)
~  ❯ time brew install grep --with-default-names
==> Using the sandbox
==> Downloading https://ftp.gnu.org/gnu/grep/grep-3.1.tar.xz
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/grep-3.1.tar.xz
==> ./configure --disable-nls --prefix=/usr/local/Cellar/grep/3.1 --infodir=/usr/
==> make
==> make install
🍺  /usr/local/Cellar/grep/3.1: 15 files, 860KB, built in 1 minute 19 seconds

real	1m20.486s
user	1m1.260s
sys	0m16.742s
```

### gnu-sed

```sh
~  ❯ time brew install gnu-sed
==> Downloading https://homebrew.bintray.com/bottles/gnu-sed-4.4.sierra.bottle.ta
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/gnu-sed-4.4.sierra.bottle.tar.gz
==> Pouring gnu-sed-4.4.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
...
==> Summary
🍺  /usr/local/Cellar/gnu-sed/4.4: 12 files, 491KB

real	0m2.050s
user	0m1.507s
sys	0m0.579s
~  ❯ brew uninstall gnu-sed 
Uninstalling /usr/local/Cellar/gnu-sed/4.4... (12 files, 491KB)
~  ❯ time brew install gnu-sed --with-default-names
==> Using the sandbox
==> Downloading https://ftp.gnu.org/gnu/sed/sed-4.4.tar.xz
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/gnu-sed-4.4.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gnu-sed/4.4
==> make install
🍺  /usr/local/Cellar/gnu-sed/4.4: 10 files, 486.8KB, built in 1 minute 14 seconds

real	1m16.769s
user	0m52.639s
sys	0m16.584s
```

### gnu-tar

```sh
~  ❯ time brew install gnu-tar
==> Downloading https://homebrew.bintray.com/bottles/gnu-tar-1.29_1.sierra.bottle
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/gnu-tar-1.29_1.sierra.bottle.tar.gz
==> Pouring gnu-tar-1.29_1.sierra.bottle.tar.gz
==> Using the sandbox
==> Caveats
...
==> Summary
🍺  /usr/local/Cellar/gnu-tar/1.29_1: 15 files, 1.7MB

real	0m2.393s
user	0m1.628s
sys	0m0.638s
~  ❯ brew uninstall gnu-tar 
Uninstalling /usr/local/Cellar/gnu-tar/1.29_1... (15 files, 1.7MB)
~  ❯ time brew install gnu-tar --with-default-names
==> Using the sandbox
==> Downloading https://ftp.gnu.org/gnu/tar/tar-1.29.tar.gz
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/gnu-tar-1.29.tar.gz
==> Downloading https://sources.debian.net/data/main/t/tar/1.29b-1.1/debian/patch
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/gnu-tar--patch-6b1371b9abd391e1654f7d730aae9c4dee703a867276b1e8a9ef97a2a906b7cf.patch
==> Patching
==> Applying When-extracting-skip-.-members.patch
patching file src/extract.c
==> ./configure --prefix=/usr/local/Cellar/gnu-tar/1.29_1 --mandir=/usr/local/Cel
==> make install
🍺  /usr/local/Cellar/gnu-tar/1.29_1: 13 files, 1.7MB, built in 1 minute 52 seconds

real	1m54.291s
user	1m29.296s
sys	0m27.001s
```

### findutils

```sh
~  ❯ time brew install findutils
==> Downloading https://homebrew.bintray.com/bottles/findutils-4.6.0.sierra.bottl
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/findutils-4.6.0.sierra.bottle.1.tar.gz
==> Pouring findutils-4.6.0.sierra.bottle.1.tar.gz
==> Using the sandbox
==> Caveats
...
==> Summary
🍺  /usr/local/Cellar/findutils/4.6.0: 33 files, 1.6MB

real	0m2.554s
user	0m1.746s
sys	0m0.669s
~  ❯ brew uninstall findutils 
Uninstalling /usr/local/Cellar/findutils/4.6.0... (33 files, 1.6MB)
~  ❯ time brew install findutils --with-default-names
==> Using the sandbox
==> Downloading https://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz
Already downloaded: /Users/Caleb/Library/Caches/Homebrew/findutils-4.6.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/findutils/4.6.0 --localstatedir=/usr/l
==> make install
🍺  /usr/local/Cellar/findutils/4.6.0: 25 files, 1.6MB, built in 2 minutes 20 seconds

real	2m21.498s
user	1m44.572s
sys	0m28.992s
```

**Comment by ilovezfs** [comment]
These are formula options, so they trigger source builds. There are no formula options that do not trigger source builds.

If you want to use the default names, and avoid a source build, you can instead prepend the `gnubin` directories to your PATH, as noted in the caveats.

```
==> Caveats
All commands have been installed with the prefix 'g'.

If you really need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:

    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
```
