### ISSUE TITLE
Node / npm package broken

### ISSUE THREAD

**Issue by jtsom** [Homebrew/homebrew-core#15804]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
brew gist-logs node
Error: No logs.
```
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
brew config
HOMEBREW_VERSION: 1.2.4-89-g997260d
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 997260da541cf4d1be8769e8c7960372bd6a92f0
Last commit: 27 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1bf6366af6ded2fbb6fb7627ec1b844848293c08
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/John/.rbenv/shims/ruby => /Users/John/.rbenv/versions/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

After doing a `brew update` and `brew upgrade`, the latest version of node was installed - v8.2.0. With it came npm V5.3.0.

After this update, npm commands are failing. Doing a `npm -g outdated` gives:

```
~ npm -g outdated
Unhandled rejection Error: ENOENT: no such file or directory, stat '/Users/brew/Library/Caches/Homebrew/node--npm-5.3.0.tgz'

npm ERR! cb() never called!
```

Note that it is looking in `/Users/brew/Library/Caches` .. for files.. obviously there's no such user

**Comment by ilovezfs** [comment]
CC @chrmoritz any ideas?

**Comment by jtsom** [comment]
FWIW, here is the error log referenced...


[2017-07-20T11_50_15_378Z-debug.txt](https://github.com/Homebrew/homebrew-core/files/1162206/2017-07-20T11_50_15_378Z-debug.txt)

**Comment by chrmoritz** [comment]
Can reproduce this error locally: Running `npm -g outdated npm` on an homebrew provided npm will fail because of missing integrity hashes.

```
149 silly cache add args [ 'npm',
149 silly cache add   'file:../../../Users/brew/Library/Caches/Homebrew/node--npm-5.3.0.tgz' ]
150 verbose cache add spec npm@file:../../../Users/brew/Library/Caches/Homebrew/node--npm-5.3.0.tgz
151 silly cache add parsed spec npm@file:../../../Users/brew/Library/Caches/Homebrew/node--npm-5.3.0.tgz
152 silly prefetch no integrity hash provided for npm@file:../brew/Library/Caches/Homebrew/node--npm-5.3.0.tgz - fetching by manifest
```

Simple workaround: Run `npm i -g npm` before running `npm outdated` the first time on a homebrew provided npm.

**Comment by jtsom** [comment]
Yeah, that seems to work around it. Thanks. (though on my home system, I seem to recall trying to do the `npm i -g npm` but just got the same `cb() never called` error. I'll try again.

**Comment by chrmoritz** [comment]
Are you sure you tried `npm install -g npm` and not the more unsafe `npm update -g npm`?

I can confirm that both `npm install -g npm` and `npm update -g npm` are failing with the homebrew provided npm (before running `npm i -g npm` at least once) because of missing integrity hashes. But every other command (including local and global installs like `npm i -g- npm`) is working fine for me.

Im working on a potential fix for it now.

**Comment by jtsom** [comment]
I know I didn't do `npm update`, and I'm pretty sure I did an `npm i -g npm`, but I will try again later. (an aside, you said "I can confirm that both `npm install -g npm` .. are failing ... before running `npm i -g npm` at least once" .. I'm guessing you meant `npm outdated -g` ?)

**Comment by chrmoritz** [comment]
@jtsom You are right, that was a typo and I meant `outdated`.

@ilovezfs Looks like we can't install npm from our `resource("npm").cached_download` anymore because of missing integrity hashes required by `npm@5`. I'm currently trying to get our formula working with the recently fixed npm Makefile (which does the npm pack workaround), which should hopefully provide correct integrity hashes.

**Comment by ilovezfs** [comment]
@chrmoritz they sure don't make this easy.

**Comment by chrmoritz** [comment]
@ilovezfs Yeah, I'm currently getting a build failure with npm's `make install` because it can't find rimraf. Looking into this I've found out that this is caused by registry tarball (which we download for npm sources) not containg the magic [`node_modules/.bin`](https://github.com/npm/npm/tree/latest/node_modules/.bin) folder breaking the discovery of these tools inside npm's own scrips...

**Comment by ilovezfs** [comment]
@chrmoritz I think I got it working building directly from the npm tag instead of the registry tarball.

**Comment by chrmoritz** [comment]
I got it working by restoring the symlink, but it's still complaing about missing integrity hashes. Is `npm -g outdated npm` working in your version?

**Comment by ilovezfs** [comment]
>Is npm -g outdated npm working in your version?

Yes, I think so :)

**Comment by ilovezfs** [comment]
@chrmoritz https://gist.githubusercontent.com/ilovezfs/570fd91dc47604a6a589e9866656b2dc/raw/50aaf714b9d2046cd94ed389f26f2eafa06eea9f/gistfile1.txt

**Comment by chrmoritz** [comment]
I think that copying the old vanilla `package.json` over like [we used too](https://github.com/Homebrew/homebrew-core/commit/ecb2d1e8551d80b5c5de2ac0d00dc071987eac01#diff-d3ef2414308e30df24a517ca9a1324eeL73) fixes the issue.

@ilovezfs Can I see your formula version?

**Comment by ilovezfs** [comment]
https://gist.githubusercontent.com/ilovezfs/5d00ddef196567b3f5eae8ca961a302c/raw/a66e6c335f5e769c50384c59dc0b0744ccacba1e/gistfile1.txt

yes that's in there too

**Comment by chrmoritz** [comment]
Submitted a one-line fix by just copying the old `package.json` over without any other install logic modifications over at #15807

**Comment by ilovezfs** [comment]
Thanks @chrmoritz!

**Comment by jtsom** [comment]
Just FYI... everything seems ok now after a brew update/upgrade.  Thanks!
