### ISSUE TITLE
Spark

### ISSUE THREAD

**Issue by devasood** [Homebrew/homebrew-core#15821]
brew install spark doesn't take care of running the `spark-shell` command, which comes when you extract the tar, set SPARK_HOME and add the sbin to the path.

Here is the gist-log: https://gist.github.com/devasood/bd07d35314ef88479ee92be68acc9813

- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**Comment by JCount** [comment]
> **Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

This issue is impossible to address since it is not defined. You need to use the issue template and and state your issue as clearly as possible.

**Comment by devasood** [comment]
Wait, let me try doing that again

**Comment by devasood** [comment]
Done, i've updated my original description

**Comment by fxcoudert** [comment]
There is no `spark-shell` command in the [`spark` package](https://github.com/holman/spark). I think you want Apache Spark, which is installed with `brew install apache-spark`. If this fails or I guessed wrong, please reopen this issue with more details on what you are trying to do.

**Comment by devasood** [comment]
Thanks!
