### ISSUE TITLE
mpfr: deprecated call used

### ISSUE THREAD

**Issue by tilda** [Homebrew/homebrew-core#15824]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new (yes - this is related to a specific formula)
- [x] Ran `brew update` and retried your prior step? (was up to date)
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? (only produced untapped libs that I installed on purpose)
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (this is irrelevant to the issue at hand)
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (irrelevant)

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

-----------------

- Was trying to compile GCC

```
==> Installing gcc dependency: mpfr
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/m/mpfr4/mpfr4_3.1.5.orig.tar.xz
######################################################################## 100.0%
Warning: Calling build.build_32_bit? is deprecated!
There is no replacement.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb:30:in `install'
Please report this to the homebrew/core tap!
```

- mpfr should go through with no warnings present

- `brew install gcc`, wait until it gets to mpfr dependency, right after downloading and configuring it emits a warning

**Comment by tilda** [comment]
Closing for the moment as it may be related to Linuxbrew's own formulae

**Comment by MikeMcQuaid** [comment]
@tilda Please don't report anything here you haven't reproduced on macOS, thanks.

**Comment by tilda** [comment]
@MikeMcQuaid Okay, thanks!

**Comment by tilda** [comment]
This issue has been moved to Linuxbrew/homebrew-core#3334
