### ISSUE TITLE
nano: shortcut bar lists `Go To Line`'s shortcut as `^/`, when it is actually bound to `^-`

### ISSUE THREAD

**Issue by unbeatable-101** [Homebrew/homebrew-core#158305]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

Brew config:
```shell
HOMEBREW_VERSION: 4.2.1-14-g719c892
ORIGIN: https://github.com/Homebrew/brew
HEAD: 719c892f64726702ca3bb6fc1e31f64a927ee3ee
Last commit: 3 hours ago
Core tap HEAD: 1f400d967445775bc446cc1f438848b665ed2098
Core tap last commit: 88 minutes ago
Core tap JSON: 12 Dec 14:36 UTC
Core cask tap HEAD: 51c68c3dd0d2e7de3562a77fe0431fc69ea40bd9
Core cask tap last commit: 2 hours ago
Core cask tap JSON: 12 Dec 14:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

Brew Doctor:
```
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm using nano to edit files, and tried to go to a line using `^/`

### What happened (include all command output)?

Nothing

### What did you expect to happen?

The shortcut should be listed as `^-` or `^_`

### Step-by-step reproduction instructions (by running `brew` commands)

`brew install nano`
`nano test`
type a 6 lines
`^/ 5`

**Comment by alebcay** [comment]
For me, all of `^/`, `^-`, and `^_` pull up the `Enter line number, column number` prompt. Is your terminal emulator intercepting the `^/` combination?

**Comment by unbeatable-101** [comment]
I'm just using Terminal.app, when I press it, a beep is played, but nothing else

**Comment by alebcay** [comment]
I am able to reproduce the issue you mention in the default Terminal app, but not in iTerm or in Visual Studio Code's terminal.

I would suggest that you can inquire further at the nano bug tracker (https://savannah.gnu.org/bugs/?group=nano) or open a ticket in Apple's Feedback Assistant against the Terminal app (https://feedbackassistant.apple.com/, see also https://openradar.appspot.com).

From a Homebrew perspective, I don't think there's anything to be done to address this issue.

**Comment by unbeatable-101** [comment]
Bug I filled for future reference: https://savannah.gnu.org/bugs/index.php?65087
