### ISSUE TITLE
toilet source link returning 503

### ISSUE THREAD

**Issue by meldonization** [Homebrew/homebrew-core#1583]
The src link is dead somehow.

**Comment by tdsmith** [comment]
`curl: (22) The requested URL returned error: 503 Service Not Available`

Let's wait and see if it comes back.

**Comment by ilovezfs** [comment]
@samhocevar any idea what's up?

**Comment by DomT4** [comment]
Chucked some mirrors into the formula in https://github.com/Homebrew/homebrew-core/commit/01d2746304d1f25d6518262a162fbc2fabc56767.

**Comment by ilovezfs** [comment]
It's back.
