### ISSUE TITLE
qemu accidentally builds against libsnappy without dependency?

### ISSUE THREAD

**Issue by sgielen** [Homebrew/homebrew-core#15831]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`?
  - Yes, it's a problem in the qemu package
- [X] Ran `brew update` and retried your prior step?
  - Still exists
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
  - There are issues in `brew doctor` but they are most likely irrelevant
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  - https://gist.github.com/sgielen/847925ae01d5925461244e13f3e53269
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  - it did work

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

------

libsnappy was just updated from 1.1.5 to 1.1.6 and since then, qemu is giving the following error when starting:

```
dyld: Library not loaded: /usr/local/opt/snappy/lib/libsnappy.1.1.5.dylib
  Referenced from: /usr/local/bin/qemu-system-i386
  Reason: image not found
```

Apparently, when building the package from source (I used `--with-vde` so it couldn't take the bottled version) it linked against snappy, this can be confirmed from the build log: 01.configure contains "snappy support yes" and the final linking of qemu happens with -lsnappy.

I'm not sure how you usually address this kind of issue, but I believe that usually qemu should link against the version of libsnappy in /usr/local/Cellar, which still exists: `/usr/local/Cellar/snappy/1.1.5/lib/libsnappy.1.1.5.dylib`.

I haven't checked this, but this can probably be reproduced by installing libsnappy, building qemu from source, then uninstalling libsnappy.

**Comment by ilovezfs** [comment]
Adding `--disable-snappy` to the configure args should prevent this from happening if you'd like to open a pull request.
