### ISSUE TITLE
x3270 formula does not install x3270 executable

### ISSUE THREAD

**Issue by marcoxa** [Homebrew/homebrew-core#158445]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew doctor tells me that everything is fine.


brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libregina.dylib
  /usr/local/lib/libregutil.dylib
  /usr/local/lib/librxtest1.dylib
  /usr/local/lib/librxtest2.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/cppgc/allocation.h
  /usr/local/include/node/cppgc/common.h
  /usr/local/include/node/cppgc/cross-thread-persistent.h
  /usr/local/include/node/cppgc/custom-space.h
  /usr/local/include/node/cppgc/default-platform.h
  /usr/local/include/node/cppgc/ephemeron-pair.h

  ... many more because I installed 'nodejs'

   /usr/local/include/node/v8-weak-callback-info.h
  /usr/local/include/node/v8.h
  /usr/local/include/node/v8config.h
  /usr/local/include/node/zconf.h
  /usr/local/include/node/zlib.h
  /usr/local/include/rexxsaa.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libregina.a
```

Bottom line: the x3270 formula should also install the x3270 executable.
It looks like it just adding a line to the `args` definition should fix the issue, but I have not enough expertise to propose a pull request.

args = %w[
      --enable-c3270
      --enable-pr3287
      --enable-s3270
      --enable-tcl3270
      --enable-x3270
    ]
```
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to run x3270.

### What happened (include all command output)?

The formula does not install the expected program (x3270).

### What did you expect to happen?

To have x3270 installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The x3270 formula should also install the x3270 executable.
It looks like it just adding a line to the `args` definition should fix the issue, but I have not enough expertise to propose a pull request.


args = %w[
      --enable-c3270
      --enable-pr3287
      --enable-s3270
      --enable-tcl3270
      --enable-x3270
    ]
```

**Comment by SMillerDev** [comment]
It is stale though, clearly nobody is working on it.

**Comment by marcoxa** [comment]
Weeeellll.  Does "staleness" mean that it is not a bug?

**Comment by SMillerDev** [comment]
In this case it's not a bug either, it's a feature you want enabled. Homebrew uses pull requests for this.

If it were a bug, it going stale simply means that nobody will work on this. We can keep the issue open forever, but that won't help anyone. Least of all the maintainers
