### ISSUE TITLE
openjdk: Cannot open macOS framework library

### ISSUE THREAD

**Issue by manuelbl** [Homebrew/homebrew-core#158901]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.2.2-12-g0555270
ORIGIN: https://github.com/Homebrew/brew
HEAD: 055527086789d315ac20253966bc4afce373499c
Last commit: 8 hours ago
Core tap HEAD: 36a1df7f913423c58d6390f9920a36b2e3cc2407
Core tap last commit: 12 minutes ago
Core tap JSON: 03 Jan 16:24 UTC
Core cask tap JSON: 03 Jan 16:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_INSTALL_FROM_API: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.1
Rosetta 2: false

% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm the main author of the Java project [Java Does USB](https://github.com/manuelbl/JavaDoesUSB). Users have reported a problem with the library when running one of the examples. The issue is unique to the OpenJDK 21 installed with *brew* (`brew install openjdk`). It does occur with the OpenJDK 21 downloaded directly from [OpenJDK web site](https://openjdk.org/projects/jdk/21/). It doesn't either occur with Zulu or Temurin builds, neither when installed with *brew* nor by downloading it directly.

### What happened (include all command output)?

*Java Does USB* uses the new Java Foreign Function & Memory interface to access native APIs directly. To that end, it needs to load macOS framework libraries using [`SymbolLookup.libraryLookup`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/foreign/SymbolLookup.html#libraryLookup(java.lang.String,java.lang.foreign.Arena)). This call fails when running a sample application:

## Install OpenJDK and Maven

```
$ brew install openjdk maven
```

## Ensure the correct Java version is used

```
$ export JAVA_HOME=/opt/homebrew/Cellar/openjdk/21.0.1/libexec/openjdk.jdk/Contents/Home
$ java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)
```
Note that it says "Homebrew" on the last two lines.

## Clone and run the sample application

```
$ git clone https://github.com/manuelbl/JavaDoesUSB.git
$ cd JavaDoesUSB/examples/monitor
$ mvn compile exec:exec
...
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< net.codecrete.usb.examples:monitor >-----------------
[INFO] Building monitor 0.7.0
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec:3.1.0:exec (default-cli) @ monitor ---
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.codecrete.usb.macos.gen.corefoundation.CoreFoundation.<clinit>(CoreFoundation.java:20)
	at net.codecrete.usb.macos.CoreFoundationHelper.createCFStringRef(CoreFoundationHelper.java:61)
	at net.codecrete.usb.macos.MacosUsbDeviceRegistry.<clinit>(MacosUsbDeviceRegistry.java:50)
	at net.codecrete.usb.Usb.createInstance(Usb.java:35)
	at net.codecrete.usb.Usb.instance(Usb.java:52)
	at net.codecrete.usb.Usb.setOnDeviceConnected(Usb.java:113)
	at net.codecrete.usb.examples.Monitor.main(Monitor.java:22)
Caused by: java.lang.IllegalArgumentException: Cannot open library: CoreFoundation.framework/CoreFoundation
	at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:277)
	at java.base/java.lang.foreign.SymbolLookup.libraryLookup(SymbolLookup.java:238)
	at net.codecrete.usb.macos.gen.corefoundation.RuntimeHelper.<clinit>(RuntimeHelper.java:26)
	... 7 more
```

### What did you expect to happen?

The sample application should run without throwing an exception and thus behave the same as it does for all other JDK 21 builds.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install maven openjdk
git clone https://github.com/manuelbl/JavaDoesUSB.git
cd JavaDoesUSB/examples/monitor
java -version
mvn compile exec:exec
```

**Comment by Bo98** [comment]
`SymbolLookup.libraryLookup` is effectively a wrapper around `dlopen` and you will see the same behaviour there:

```c

#include <dlfcn.h>
#include <stdio.h>

void test(const char *name) {
  void *ptr = dlopen(name, RTLD_LAZY);
  if (ptr == NULL)
    printf("%s\n\n", dlerror());
  else
    printf("Success for %s!\n\n", name);
}

int main() {
  test("libz.dylib");
  test("CoreFoundation.framework/CoreFoundation");
}
```

```console
Success for libz.dylib!

dlopen(CoreFoundation.framework/CoreFoundation, 0x0001): tried: 'CoreFoundation.framework/CoreFoundation' (no such file), '/System/Volumes/Preboot/Cryptexes/OSCoreFoundation.framework/CoreFoundation' (no such file), '/usr/lib/CoreFoundation.framework/CoreFoundation' (no such file, not in dyld cache), 'CoreFoundation.framework/CoreFoundation' (no such file)
```

Basically what happened here is Apple have changed how framework lookups work and the method you describe is now deprecated (see `man dlopen`):

> When path looks like a framework path (e.g. /stuff/foo.framework/foo), if
> $DYLD_FRAMEWORK_PATH was set at launch, dyld will first look in that
> directory for the framework partial path (e.g. foo.framework/foo). Next,
> dyld will try the supplied path as-is (using current working directory
> for relative paths).  Lastly, **for old binaries**, dyld will try some
> fallbacks.  If $DYLD_FALLBACK_FRAMEWORK_PATH was set at launch, dyld will
> search those directories.  Otherwise, it will search /Library/Frameworks
> (on macOS if process is unrestricted), then /System/Library/Frameworks.

(emphasis on old binaries)

Old binaries in this case means anything built using an SDK older than macOS 14. You can see what SDK is used by running `otool -l /opt/homebrew/opt/openjdk/bin/java | grep 'sdk '`. Some third party OpenJDK builds likely use much older machines than we do.

With that said, this change will eventually make its way to other OpenJDKs when they update their build machines.

My recommendation for both backwards and forwards compatibility is to use `SymbolLookup.libraryLookup("/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation")` instead - you can trust the framework is there and is potentially more secure from people placing things in `/usr/local/lib`.

**Comment by manuelbl** [comment]
Thank you for responding quickly, and with good hints. 

About 18 months ago, I already dug into this topic and had come up with a relative framework path as the most compatible solution. I will need to test it again (including compatibility with Intel Macs).

**Comment by SMillerDev** [comment]
There is no difference in file paths here between Intel and MacOS, but there might be a difference between older and newer macOS versions.

**Comment by manuelbl** [comment]
The absolute path for the framework is working on all tested setup (different Macs, different macOS versions, different JDK builds). I will change my library accordingly.

I can't quite remember what the problem was the absolute path was at the time. It might have been related to an issue in the preview implementation of the Foreign Function and Memory API in JDK 19.

Thanks for the quick and profound support. I appreciate it.
