### ISSUE TITLE
Postgis formula fail to create postgresql extensions

### ISSUE THREAD

**Issue by clouddie** [Homebrew/homebrew-core#15892]
# Please always follow these steps:
- [X ] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 

https://gist.github.com/anonymous/d5b78c0c13f27ac7944b27c299ddc8c4

- [ X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Install latest postgis version without gdal (to avoid conflict with gdal1 as I have gdal2 installed)

- What happened (include command output)

```
romain$ brew install postgis --without-gdal
==> Using the sandbox
==> Downloading http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
Already downloaded: /Users/romain/Library/Caches/Homebrew/postgis-2.3.2.tar.gz
==> ./configure --with-projdir=/usr/local/opt/proj --with-jsondir=/usr/local/opt
==> make
==> make install DESTDIR=/private/tmp/postgis-20170722-30731-1ianhnj/postgis-2.3
Warning: tried to install empty array to /usr/local/Cellar/postgis/2.3.2/share/doc/postgis/postgresql/extension
Warning: tried to install empty array to /usr/local/Cellar/postgis/2.3.2/share/postgresql/extension
Warning: tried to install empty array to /usr/local/Cellar/postgis/2.3.2/share/postgis_topology
==> Caveats
To create a spatially-enabled database, see the documentation:
  https://postgis.net/docs/manual-2.2/postgis_installation.html#create_new_db_extensions
If you are currently using PostGIS 2.0+, you can go the soft upgrade path:
  ALTER EXTENSION postgis UPDATE TO "2.3.2";
Users of 1.5 and below will need to go the hard-upgrade path, see here:
  https://postgis.net/docs/manual-2.2/postgis_installation.html#upgrading

PostGIS SQL scripts installed to:
  /usr/local/opt/postgis/share/postgis
PostGIS plugin libraries installed to:
  /usr/local/lib
PostGIS extension modules installed to:
  /usr/local/share/postgresql/extension
==> Summary
🍺  /usr/local/Cellar/postgis/2.3.2: 49 files, 10.5MB, built in 1 minute 8 seconds
````

and then, when trying CREATE EXTENSION POSTGIS, I get 

```
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/postgis.control": No such file or directory
```
Extensions might have been created, but not copied into /usr/local/share/postgresql/extension (and no sign of postgre whatsoever

- What you expected to happen

psql -c 'CREATE EXTENSION postgis' should have resulted in installation of the postgis extension in postgresql

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install postgis --without-gdal
psql -c 'CREATE EXTENSION postgis' 
```

**Comment by leepa** [comment]
This is an upstream issue that the Postgis community marked as won't fix:

https://trac.osgeo.org/postgis/ticket/1713

**Comment by clouddie** [comment]
Hi, ok, sorry for this !!
