### ISSUE TITLE
cromwell - SHA256 changed - argh, updated with same release number :-(

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-core#15917]
```
==> Installing cromwell
==> Downloading https://github.com/broadinstitute/cromwell/releases/download/28/cromwell-28.jar
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/34136406/a369990a-6b0a-11e7-8913-d7ce4d7a2ce3
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 25c6c30fe062fb4a8384ef82aa5313ad5a5ee05eae62a2c831219d7c6c756347
Actual: c9ce762df236588ded042ceaf099848c0c1685d34788442ee251615ff13b5190
Archive: /home/linuxbrew/.cache/Homebrew/cromwell-28.jar
To retry an incomplete download, remove the file above.
```

If you read  https://github.com/broadinstitute/cromwell/

```
WARNING! If you downloaded the Cromwell 28 JAR prior to 7/17/2017 please redownload as we discovered and patched a critical bug.
```

ARGH....

The correct sha is `c9ce762df236588ded042ceaf099848c0c1685d34788442ee251615ff13b5190`

**Comment by tseemann** [comment]
Looks like i've clashed with #15710

**Comment by ilovezfs** [comment]
@tseemann your brew is outdated as the current version is 28.1 which has this resolved.

**Comment by ilovezfs** [comment]
@tseemann that update hasn't made its way over to Linuxbrew (https://github.com/Linuxbrew/homebrew-core/blob/acd2c71e0eef5967c7b5e09a8df949bf8d9c2060/Formula/cromwell.rb), which is one of the reason Linuxbrew issues should be reported to Linuxbrew not Homebrew. Please only report issues to Homebrew that you have actually personally reproduced with Homebrew on macOS.
