### ISSUE TITLE
swftools fails to build from source

### ISSUE THREAD

**Issue by r0mai** [Homebrew/homebrew-core#15910]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install the package swftools from source `brew install --build-from-source swftools`. I wanted to modify the formula with an extra patch for my own use, so I tried to install the formula from source first, to make sure compilation won't cause issues with my patched version.
- What happened (include command output)
```
$ brew install --build-from-source swftools
==> Using the sandbox
==> Downloading http://www.swftools.org/swftools-0.9.2.tar.gz
Already downloaded: /Users/r0mai/Library/Caches/Homebrew/swftools-0.9.2.tar.gz
==> Patching
patching file configure
==> ./configure --prefix=/usr/local/Cellar/swftools/0.9.2_1
==> make
Last 15 lines from /Users/r0mai/Library/Logs/Homebrew/swftools/02.make:
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swfaction.c -o modules/swfaction.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swfbits.c -o modules/swfbits.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swfbutton.c -o modules/swfbutton.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swfcgi.c -o modules/swfcgi.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swfdraw.c -o modules/swfdraw.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swfdump.c -o modules/swfdump.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swffilter.c -o modules/swffilter.o
clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swffont.c -o modules/swffont.o
modules/swffont.c:42:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^
1 error generated.
make[1]: *** [modules/swffont.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html
```
Note: I have ft2build.h installed in the correct location on my system: `/usr/local/Cellar/freetype/2.8/include/freetype2/ft2build.h` which is the same as `/usr/local/opt/freetype/include/freetype2/ft2build.h`

- What you expected to happen
It successfully compiles and installs the package.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install --build-from-source swftools
```

## Additional information:

Gist logs:
https://gist.github.com/r0mai/1a7c3b78b69ab22efdad7aadbbf254a4

I could reproduce the issue on another computer as well.

Running the last clang command that failed manually from the debug console succeeds(!):

```
$ brew install --debug --build-from-source swftools
[...same error...]
BuildError: Failed executing: make
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
bash-3.2$ cd lib/
bash-3.2$ clang -c -DHAVE_CONFIG_H   -I/usr/local/Cellar/swftools/0.9.2_1/include -I/usr/local/opt/freetype/include/freetype2 -I /usr/local/include/lame -fPIC -Wimplicit -Wreturn-type -Wno-write-strings -Wformat -O -fomit-frame-pointer  modules/swffont.c -o modules/swffont.o
modules/swffont.c:196:16: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
            if(gindex >= 0 && gindex<face->num_glyphs) {
               ~~~~~~ ^  ~
1 warning generated.
```

I tried to compare the environment variables while executing inside the Makefile with the env vars in the brew shell. Nothing suspicious was different.

I also found that by replacing
```
-I/usr/local/opt/freetype/include/freetype2
```
with
```
-isystem /usr/local/Cellar/freetype/2.8/include/freetype2
```
in the Makefile fixes the compilation error (no clue why, `<>` bracket includes should be searched for in the `-I` paths as well.

Using this trick I managed to do a hacky workaround by adding this to the formula:

```
    ENV["CFLAGS"] = "-isystem /usr/local/Cellar/freetype/2.8/include/freetype2"
    ENV["CPPFLAGS"] = "-isystem /usr/local/Cellar/freetype/2.8/include/freetype2"
```

So the strangeness of the issue is that make can't execute the same command I'm executing by hand in the same environment. Hopefully you can reproduce the issue too.

**Comment by ilovezfs** [comment]
This is due to opportunistic use of freetype if it happens to be installed while building. Out of interest, why aren't you using the bottle?

**Comment by ilovezfs** [comment]
>I wanted to modify the formula with an extra patch for my own use, so I tried to install the formula from source first, to make sure compilation won't cause issues with my patched version.

Ah I missed this bit. OK.

You can `brew unlink freetype` during the build to avoid the issue.

**Comment by r0mai** [comment]
Thank you, indeed it works after unlink. So I assume `--build-from-source` is only supposed to work on a clean machine with nothing installed.

Is there any way to enforce unlink/relink of freetype in a formula file?

**Comment by ilovezfs** [comment]
>So I assume --build-from-source is only supposed to work on a clean machine with nothing installed.

Right. In this case superenv is deliberately breaking the build because the formula doesn't declare a direct or indirect/recursive dependency on freetype.

>Is there any way to enforce unlink/relink of freetype in a formula file?

You can just add `depends_on "freetype"` to the formula. Note that this formula has the same problem with `giflib`. We could just add both those deps to the formula but that's a bit heavy handed when they're not really needed.

Ideally upstream would provide `--without-freetype` and `--without-giflib` options so that we could pass those.

**Comment by r0mai** [comment]
`depends_on "freetype"` works beautifully. Thank you for the insights!

**Comment by ilovezfs** [comment]
You're welcome!
