### ISSUE TITLE
go: vet build steps are outdated

### ISSUE THREAD

**Issue by AlekSi** [Homebrew/homebrew-core#1591]
I was tracking down a problem when `go vet` on my OS X was producing results different from Linux CI (somewhat similar to https://github.com/golang/go/issues/12636). It turned out it's a problem in Homebrew go formula. `vet` now present in the release tarball, `golang.org/x/tools/cmd/vet` no longer exists. I assume that old version was cached on the host you use to produce bottles.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
@AlekSi I think you've misdiagnosed the problem.

vet is contained within the gotools resource, not the go tarball:
```
 resource "gotools" do
    url "https://go.googlesource.com/tools.git",
    :branch => "release-branch.go#{go_version}",
    :revision => "c887be1b2ebd11663d4bf2fbca508c449172339e"
  end
```

This gets fetched and put in place during the `install` method:
```
(buildpath/"src/golang.org/x/tools").install resource("gotools")
```
That will effectively
```
mkdir -p src/golang.org/x/tools
```
And then copy the gotools into that directory.

Subtracting "src/golang.org/x/tools" from "src/golang.org/x/tools/cmd/vet/" you get "cmd/vet", which indeed does still exist: https://go.googlesource.com/tools.git/+/release-branch.go1.6/cmd/vet/

**Comment by AlekSi** [comment]
Yes, that's what this formula is doing now. And that way of install `vet` is outdated since `vet` is present in release tarball (I guess since release 1.6). Versions in the tarball and tools repository are different. Result: `vet` installed with Homebrew can't detect some errors, `vet` installed from the tarball in our CI can.

**Comment by ilovezfs** [comment]
I see. However, the tools are version stamped 1.6 just like the release, so that seems like a bizarre situation. Do you have a link that explains this change?

**Comment by AlekSi** [comment]
No, and I don't have a small enough example to show a problem yet. I will try again.

**Comment by AlekSi** [comment]
Ok, I have an example:
```go
package main

import (
	"errors"
	"log"
)

func main() {
	err := errors.New("1")
	if err != nil {
		err := errors.New("2")
		log.Print(err)
	}
	log.Print(err)
}
```
`go tool vet -shadow test.go` from Homebrew shows no problem. Running this command with Go installed from OS X package or from release tarball gives me `test.go:11: declaration of err shadows declaration at test.go:9:`. Yes, I know that `-shadow` is experimental, but this test shows that versions are different.

**Comment by ilovezfs** [comment]
Yeah, the source does definitely differ. What change are you proposing we make exactly?

**Comment by AlekSi** [comment]
Do we want to keep `head`? Personally, I always install released Go version from Homebrew and HEAD from the git repository by my own. If we remove `head`, then formula can be significantly simplified: gotools can be removed, vet will be installed from the release tarball. Otherwise, I'm not sure what we can to do.

**Comment by ilovezfs** [comment]
Yes, we should keep head for go. Why is head a problem specifically? It has vet: https://github.com/golang/go/tree/master/src/cmd/vet

**Comment by AlekSi** [comment]
Ok, vet moved to the main repository for release 1.5. `tools` can be dropped completely. I will try to make a pull request in few days.

**Comment by ilovezfs** [comment]
I think they're still needed for `godoc`.

**Comment by ilovezfs** [comment]
Here's where the change was made, by the way:
https://groups.google.com/forum/#!topic/golang-announce/qu_rAphYdxY
https://github.com/golang/tools/commit/adaaa074861b0d254acf51dec74daf7c2ba20e90

**Comment by ilovezfs** [comment]
@AlekSi any update on this?
