### ISSUE TITLE
No x11 or cairo with R in Sierra 10.12.6  

### ISSUE THREAD

**Issue by TomHarrop** [Homebrew/homebrew-core#15925]
On a fresh install of Sierra (10.12.6), bottled `r` does not have x11 or cairo.

```
brew reinstall r
==> Reinstalling r 
==> Downloading https://homebrew.bintray.com/bottles/r-3.4.1_1.sierra.bottle.tar.gz
Already downloaded: /Users/tom/Library/Caches/Homebrew/r-3.4.1_1.sierra.bottle.tar.gz
==> Pouring r-3.4.1_1.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/r/3.4.1_1: 2,113 files, 55.2MB
```
In R:

```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE        TRUE       FALSE        TRUE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 
```
I tried `--build-from-source` but it didn't help. The gist log says I installed using `--with-java`, but I didn't.

Any suggestions?  

Cheers!

Gist log: https://gist.github.com/TomHarrop/bc160cc7297729c15c942004e8893da0

Issue checklist: 
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by ilovezfs** [comment]
We've reduced the option set as part of the migration of r from homebrew/science. See https://github.com/Homebrew/homebrew-core/pull/14416.

If you still need those particular options, please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).
