### ISSUE TITLE
`postgis` and `pgrouting` GHA build failures: Failed system call was shmget

### ISSUE THREAD

**Issue by jpfeuffer** [Homebrew/homebrew-core#159391]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
running bootstrap script ... 2024-01-08 09:28:10.805 PST [24189] FATAL:  could not create shared memory segment: No space left on device
2024-01-08 09:28:10.805 PST [24189] DETAIL:  Failed system call was shmget(key=1406819897, size=56, 03600).
2024-01-08 09:28:10.805 PST [24189] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
	The PostgreSQL documentation contains more information about shared memory configuration.
child process exited with exit code 1
initdb: removing data directory "/private/tmp/postgis-test-20240108-24126-j7nqvu/test"
pg_ctl: database system initialization failed
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

fix an existing formula ([hdf5](https://github.com/Homebrew/homebrew-core/pull/159165#issuecomment-1881539996)) that has those as a dependency

### What happened (include all command output)?

see https://github.com/Homebrew/homebrew-core/actions/runs/7450537616

### What did you expect to happen?

Build the formula successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run the GH Actions https://github.com/Homebrew/homebrew-core/actions/runs/7450537616.
```

**Comment by ZhongRuoyu** [comment]
Please don't open issues for CI failures; allow some time for maintainers to respond if you are not sure how to proceed with a PR.

**Comment by jpfeuffer** [comment]
I understand, sorry! I just thought it would reach maintainers more familiar with the other packages more easily.
And it felt like something that would benefit from tracking in the sense that other new contributors can find this.
As you can see, there was not an issue for it and I think people are less drawn to search inside existing PRs that also fail because of this.
