### ISSUE TITLE
Postresql 15 is broken after update

### ISSUE THREAD

**Issue by dandee** [Homebrew/homebrew-core#159696]
Yesterday's update to the postgresql@15 formula has broken my development environment. There are no longer 'dropdb', 'psql', etc. commands available on my machine. I want them back.

https://github.com/Homebrew/homebrew-core/commit/f2cf0a302f30b1014ef1a9e2cf496af7748d4932

https://github.com/Homebrew/homebrew-core/commit/f2cf0a302f30b1014ef1a9e2cf496af7748d4932#commitcomment-136841129

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use 'dropdb' and 'psql' CLI tools

### What happened (include all command output)?

```
dropdb testdb -f
zsh: command not found: dropdb
```

### What did you expect to happen?

`dropdb` to be available.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql@15

psql
^^^ fails

brew link postgresql@15

psql
^^^ still fails
```

**Comment by SMillerDev** [comment]
They are now suffixed with the version

**Comment by swrobel** [comment]
I don't understand why they would be suffixed if using `brew link`, though...

**Comment by joelburton** [comment]
Having this change for existing users of these formulas was a very, very poor decision.

**Comment by MikeMcQuaid** [comment]
I'm reverting this in https://github.com/Homebrew/homebrew-core/pull/159758. Apologies for the pain here @dandee @swrobel @joelburton

**Comment by MikeMcQuaid** [comment]
@dandee @swrobel @joelburton Until https://github.com/Homebrew/homebrew-core/pull/159760 is merged: this will require a `brew reinstall postgresql@15` or `brew reinstall postgresql@16` to fix. After that, a `brew upgrade` will work as expected.

**Comment by dandee** [comment]
> I'm reverting this in #159758. Apologies for the pain here @dandee @swrobel @joelburton

Thanks Mike! I really appreciate the effort!
