### ISSUE TITLE
Podman machine start, waits indefinately with 'Wating for VM...' with latest qemu (8.2.0) on OSX (M1)

### ISSUE THREAD

**Issue by venekamp** [Homebrew/homebrew-core#159971]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 8 days ago
Core tap JSON: 15 Jan 13:00 UTC
Core cask tap JSON: 15 Jan 13:00 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```
```
% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Start a podman machine on MacOS (M1). I have few podman containers for testing code.

### What happened (include all command output)?

```
% ./test/start-podman.sh
Extracting compressed file: podman-machine-default_fedora-coreos-39.20240104.2.0-qemu.aarch64.qcow2: done
Image resized.
Machine init complete
To start your machine run:

	podman machine start

Starting machine "podman-machine-default"
Waiting for VM ...
```

```
% cat ./test/start-podman.sh
#!/usr/bin/env bash

podman machine init --volume /Users/xxx:/Users/xxx
podman machine start
```

### What did you expect to happen?

That the podman machine would start.

### Step-by-step reproduction instructions (by running `brew` commands)

Brewing is fine. No issues there. However, the result does not work as expected. Tried downgrading qemu to something <8.2.0 and pinning it, but the podman formula seems to want the latest only. Tried to downgrade podman to an earlier version, but qemu 8.2.0 still seems the only acceptable version. People have reported elsewhere that qemu 8.2.0 seems to cause of the endless: Waiting for VM...

**Comment by venekamp** [comment]
I got it in a workable state for me by doing:

```shell
brew uninstall podman-desktop podman qemu

wget https://raw.githubusercontent.com/Homebrew/homebrew-core/d0c1a25835de4aeac60a4fadbf46ebf14a7d1934/Formula/p/podman.rb -O podman.rb
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/676c6922d79d24cc0794dd22250e3ea1167f2cd9/Formula/q/qemu.rb -O qemu.rb

brew install podman.rb
brew unlink qemu
brew install qemu.rb
```
 
Then I was able to start a podman machine:
```
% ./test/start-podman.sh
Extracting compressed file: podman-machine-default_fedora-coreos-39.20240104.2.0-qemu.aarch64.qcow2: done
Image resized.
Machine init complete
To start your machine run:

	podman machine start

Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users/xxx:/Users/xxx

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: /Users/xxx/.local/share/containers/podman/machine/qemu/podman.sock

The system helper service is not installed; the default Docker API socket
address can't be used by podman. If you would like to install it run the\nfollowing commands:

        sudo /opt/homebrew/Cellar/podman/4.7.2/bin/podman-mac-helper install
        podman machine stop/opt/homebrew/Cellar/podman/4.7.2/bin/podman-mac-helper; podman machine start/opt/homebrew/Cellar/podman/4.7.2/bin/podman-mac-helper

                You can still connect Docker API clients by setting DOCKER_HOST using the
following command in your terminal session:

        export DOCKER_HOST='unix:///Users/xxx/.local/share/containers/podman/machine/qemu/podman.sock'

Machine "podman-machine-default" started successfully
```

See also the following issue: https://github.com/containers/podman/issues/20776

**Comment by cho-m** [comment]
The `podman` issue refers to `qemu` issue: https://gitlab.com/qemu-project/qemu/-/issues/1990 so sounds like some upstream issues. It looks like there are some recent commits that are related to fixing issue by updating edk2 firmware though no idea if they are stable enough for a release.

**Comment by cfergeau** [comment]
The fixes are now in master, and will be in qemu 8.2.1, they should be good enough to be backported. lima also has a patched qemu (or rather edk2/shim) build to avoid these problems.

**Comment by cfergeau** [comment]
qemu 8.2.1 is now available in brew, hopefully this fixes this issue, and it can be closed.

**Comment by TimPchelintsev** [comment]
> qemu 8.2.1 is now available in brew, hopefully this fixes this issue, and it can be closed.

I had this issue and can confirm that after upgrading qemu to 8.2.1 issue was resolved.

**Comment by cho-m** [comment]
> I had this issue and can confirm that after upgrading qemu to 8.2.1 issue was resolved.

Thanks for confirming. Closing issue as fixed with 8.2.1.

**Comment by venekamp** [comment]
Tested, and the latest qemu fixes the starting issue.

**Comment by josepheiba** [comment]
> Tested, and the latest qemu fixes the starting issue.

do you know why it's not working on qemu 8.2.1 on macports, but working on brew?

**Comment by venekamp** [comment]
> > Tested, and the latest qemu fixes the starting issue.
> 
> do you know why it's not working on qemu 8.2.1 on macports, but working on brew?

No, I'm sorry.
