### ISSUE TITLE
`brew install yarn` always installed node v8.2.1 even I've installed node@6 with HomeBrew on MacOS

### ISSUE THREAD

**Issue by imzhengfei** [Homebrew/homebrew-core#16019]
**MacOS**: v10.12.5
**HomeBrew**: v1.2.4
**Yarn**: v0.27.5

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
* `brew install yarn` always installed node v8.2.1 even I've installed node@6 with HomeBrew on MacOS
* That command also installed `icu4c`, what's and why `icu4c`?

**If the current behavior is a bug, please provide the steps to reproduce.**
**Steps:**
* Open iTerm2
* Run `brew ls` to make sure I've installed `node@6`
* Run ` node -v` to make sure my node version is `v6.10.2`
* Run `brew install yarn` to install `yarn`
* When completed, run `brew ls` and I saw `node node@6 yarn icu4c ...`

**What is the expected behavior?**
* No installing `node v8.2.1`
* No installing `icu4c`

**Please mention your node.js, yarn and operating system version.**

**Comment by ilovezfs** [comment]
This is intentional. The `yarn` formula

```
depends_on "node"
```

There is no `:node` requirement that can be fulfilled with any arbitrary node.

**Comment by ilovezfs** [comment]
@imzhengfei See https://github.com/Homebrew/homebrew-core/pull/16021

**Comment by ilovezfs** [comment]
@imzhengfei you can now do

```
brew install --without-node yarn
```

**Comment by imzhengfei** [comment]
OK, I used `brew install yarn --ignore-dependencies` to solve this.

**Comment by ilovezfs** [comment]
That will not be persistent, which is why I provided `--without-node`, which will be persistent.

**Comment by imzhengfei** [comment]
OK, I've tried and succeed. Thx. 👍

**Comment by ilovezfs** [comment]
You're welcome!
