### ISSUE TITLE
trailing whitespace in brew install command causes failure

### ISSUE THREAD

**Issue by tcox2harken** [Homebrew/homebrew-core#1601]
When performing `brew install <formula> ` with a trailing whitespace, the command fails with the
`no available formulae` error.

To reproduce, try:
`brew install ruby-install​ `
Note the trailing whitespace in the command.

It took me a while to realize the error message was telling me exactly what was wrong:
```
 brew install ruby-install​
Error: No available formula with the name "ruby-install​ " 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

This is not really a defect of course - but it would be nice if brew trimmed the leading and trailing whitespaces automagically.

**Comment by UniqMartin** [comment]
> This is not really a defect of course - but it would be nice if brew trimmed the leading and trailing whitespaces automagically.

I'm sorry, but I disagree. This will just include more magic and will make it harder for anyone to understand what is going on, despite the fact that we'll probably don't expect formulae to have whitespace in their names for a bunch of other reasons.

How did you even manage to include the whitespace in the first place? Just having a trailing space in a normal invocation in a shell won't have this effect. You'd need to have either escaped or quoted the space, but any of the following invocations make it pretty clear where the space is coming from.

```sh
brew install ruby-install\  # <- Notice the escaped space.
brew install "ruby-install "
brew install 'ruby-install '
```

**Comment by UniqMartin** [comment]
Did you copy the invocation from some website or something similar? I suspect that might mean the space wasn't a regular space but, e.g. a non-breaking space, and this would explain why that space wasn't ignored by your shell. (This would also mean stripping it from the formula argument will be a bit more complicated and I'd rather we don't go down that path, considering the error message is spot on.)

**Comment by tcox2harken** [comment]
I copied the command line string from a README.md file in RubyMine. I'll close this out. I thought it might be a quick hit to just trim trailing whitespace characters. Thanks for responding and I apologize for the noise.
