### ISSUE TITLE
R/openblas migration broke RStudio

### ISSUE THREAD

**Issue by ck37** [Homebrew/homebrew-core#16024]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I ran a normal brew update && brew upgrade. RStudio could no longer open - it gives an empty window with just "ok" and then closes.

I noticed that r and openblas were both reporting a warning "should be using normal versions rather than homebrew/science versions" or something to that effect, and was able to fix the issue by force uninstalling `r` and `openblas`formulas and then re-installing.

Gist info: https://gist.github.com/76cf88687da4e951993cbf7b6417bd81

**Comment by JCount** [comment]
So what is your current issue? From the logs you provided it seems as if it installed fine.

**Comment by ck37** [comment]
I'm reporting that the current upgrade process broke RStudio 1) under the hopes that it would be seen as suboptimal and worth fixing, 2) so others can see the solution without having to figure it out themselves.

**Comment by JCount** [comment]
Are you using the `rstudio-server` formula from `homebrew/science`?

**Comment by ck37** [comment]
I had it installed and did re-install it, but I don't currently use it.

**Comment by JCount** [comment]
So you were using a non-homebrew installation that depend upon Homebrew's R formula, that stopped working?

**Comment by ck37** [comment]
Right, RStudio the macOS app is what I'm referring to, not rstudio-server which I did not check.

**Comment by JCount** [comment]
Did you manually configure RStudio to depend upon the Homebrew-built R installation? If so, I am sorry that changes within Homebrew broke outside software that was configured to depend upon it. 

However, Homebrew does not, and simply cannot, support configurations that are entirely beyond the scope of what we can manage. We try to do things delicately, but at the same time in order for us to be able to function as a package manager and develop our own project as well, we will unavoidably break such configurations with some frequency.

**Comment by ck37** [comment]
No, RStudio detects the installed R automatically. Homebrew's migration of R from homebrew-science to core is what caused the error, which is within Homebrew's control. Most R users will be using the Rstudio app.

Tired of the hostility to this honest issue, I won't be responding further.

**Comment by JCount** [comment]
@ck37 I was not trying or intending to be hostile. I was just trying to determine what your situation was. However, this is a bug you may want to report upstream to RStudio, because changes to R installations that are not directly part of it, but instead automatically picked up as you described, probably should not cause RStudio itself to malfunction that way.

**Comment by MikeMcQuaid** [comment]
I've tested `r-studio` and it works fine for me with the new formula. There's no hostility here; just questions about your situation so we can understand and statements on what we can and can't control. If you can provide a set of reproducible commands that illustrate your issue we can look at fixing it.
