### ISSUE TITLE
libgphoto2 error when installing wine

### ISSUE THREAD

**Issue by voxynn** [Homebrew/homebrew-core#1604]
I'm having trouble installing wine, as an error related to libgphoto2 appears. Code it below. gist logs available at https://gist.github.com/anonymous/70ca6d15d69c0668af6af778b34c7958.

```
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/libgphoto2-2.5.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.10
Last 15 lines from /Users/Richard/Library/Logs/Homebrew/libgphoto2/01.configure:
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no
configure: error: 
libgphoto2 requires the ltdl library, included with lib tool

Please make sure that the proper development package is installed
(libltdl-dev, libtool-ltdl-devel, etc.)


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
libgphoto2 error  https://github.com/Homebrew/homebrew-core/issues/1406

Richards-MacBook-Air:~ Richard$ brew doctor
Your system is ready to brew.
```

**Comment by vlegchilkin** [comment]
I have the same issue. My gist logs here: https://gist.github.com/6800c098b894bfc8315473e8dc628bf3

**Comment by vlegchilkin** [comment]
Also I have such log from libtool installation(see Caveats). I suppose it is linked.

```
Vitals-MacBook-Pro:~ Alik$ brew install wine
==> Installing dependencies for wine: libtool, libgphoto2, little-cms2, jas
==> Installing wine dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.el_capitan.bott
Already downloaded: /Library/Caches/Homebrew/libtool-2.4.6.el_capitan.bottle.tar.gz
==> Pouring libtool-2.4.6.el_capitan.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 70 files, 3.7M
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.1
Last 15 lines from /Users/Alik/Library/Logs/Homebrew/libgphoto2/01.configure:
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no
configure: error: 
libgphoto2 requires the ltdl library, included with libtool
```

**Comment by ilovezfs** [comment]
```
brew uninstall libtool
```
then try again please

**Comment by shimika** [comment]
Same here

==> Installing dependencies for wine: libtool, libgphoto2, little-cms2, jasper, libicns, makedepend, openssl, sane-backends, libtasn1, gmp, nettle, gnutls
==> Installing wine dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libtool-2.4.6.el_capitan.bottle.tar.gz
==> Pouring libtool-2.4.6.el_capitan.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 70 files, 3.7M
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/libgphoto2-2.5.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.10
Last 15 lines from /Users/mika/Library/Logs/Homebrew/libgphoto2/01.configure:
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no
configure: error:
libgphoto2 requires the ltdl library, included with libtool

Please make sure that the proper development package is installed
(libltdl-dev, libtool-ltdl-devel, etc.)


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
libgphoto2 error  https://github.com/Homebrew/homebrew-core/issues/1406
libgphoto2 error when installing wine https://github.com/Homebrew/homebrew-core/issues/1604

**Comment by vlegchilkin** [comment]
> ilovezfs commented an hour ago
brew uninstall libtool
then try again please

 Nothing changed. Still reproduces.

**Comment by ilovezfs** [comment]
Quite strange. Mine triggers a source build of libtool as required.
```
iMac-TMP:~ joe$ brew uninstall -f libtool libgphoto2 little-cms2 jasper libicns makedepend openssl sane-backends libtasn1 gmp nettle gnutls
Uninstalling libtool... (70 files, 3.7M)
Uninstalling libgphoto2... (168 files, 7.3M)
iMac-TMP:~ joe$ brew install wine
==> Installing dependencies for wine: libtool, libgphoto2, little-cms2, j
==> Installing wine dependency: libtool
==> Downloading http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.xz
Already downloaded: /Users/joe/Library/Caches/Homebrew/libtool-2.4.6.tar.xz
==> ./configure --prefix=/usr/local/Cellar/libtool/2.4.6 --program-prefix=g --en
==> make install
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 70 files, 3.7M, built in 12 seconds
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.1
Already downloaded: /Users/joe/Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5
==> make install
🍺  /usr/local/Cellar/libgphoto2/2.5.10: 168 files, 7.3M, built in 50 seconds
==> Installing wine dependency: little-cms2
==> Downloading https://downloads.sourceforge.net/project/lcms/lcms/2.7/lcms2-2.
Already downloaded: /Users/joe/Library/Caches/Homebrew/little-cms2-2.7.tar.gz
tar: copyfile unpack (lcms2-2.7/Projects/mac/LittleCMS/.DS_Store) failed: File exists
```

**Comment by ilovezfs** [comment]
A workaround is probably to do
```
brew uninstall -f libtool
brew install --universal --build-from-source libtool
brew install wine
```

but I wonder if you could try this with a new dummy user and see if the problem still occurs.

**Comment by ilovezfs** [comment]
Ah after brew updating, I get the error. So this is a very recent regression. I'll investigate further.

**Comment by ilovezfs** [comment]
The regression was introduced by c47c9a6991db2134ede339fbe681a32d51156d38

So a temporary workaround is to

```
cd /usr/local/Library/Taps/homebrew/homebrew-core
git revert c47c9a6991db2134ede339fbe681a32d51156d38
```
until we fix it for real.

**Comment by vlegchilkin** [comment]
> The regression was introduced by c47c9a6
So a temporary workaround is to
git revert c47c9a6991db2134ede339fbe681a32d51156d38
until we fix it for real.

I have tried to do this but gd-2.1.1 library is not on mirrors. (404 error)

Vitals-MacBook-Pro:homebrew-core Alik$ brew install wine
==> Installing dependencies for wine: gd, libgphoto2, little-cms2, jasper, libicns, makedepend, openssl, sane-backends, l
==> Installing wine dependency: gd
==> Downloading https://github.com/libgd/libgd/releases/download/gd-2.1.1/libgd-2.1.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/gd-2.1.1.tar.xz
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/libg/libgd2/libgd2_2.1.1-4.1.debian.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/libg/libgd2/libgd2_2.1.1-4.1.debian.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "gd--patch"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/libg/libgd2/libgd2_2.1.1-4.1.debian.tar.xz

**Comment by ilovezfs** [comment]
Ah ok. You can do this instead:
```
cd /usr/local/Library/Taps/homebrew/homebrew-core
git reset --hard origin/master
perl -p -i -e 's/"libtool" => :build/"libtool" => :run/' Formula/gd.rb
```

**Comment by vlegchilkin** [comment]
thank you, it is working now.

**Comment by ilovezfs** [comment]
You're welcome. I've found the "real" bug, but that workaround is "good enough" for now :)

**Comment by willin** [comment]
```
brew uninstall libtool
Uninstalling /usr/local/Cellar/libtool/2.4.6... (70 files, 3.7M)
 ~  brew install wine
==> Installing dependencies for wine: libtool, libgphoto2, little-cms2, jasper, libicns, ma
==> Installing wine dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.el_capitan.bottle.tar.gz
Already downloaded: /Users/willin/Library/Caches/Homebrew/libtool-2.4.6.el_capitan.bottle.tar.gz
==> Pouring libtool-2.4.6.el_capitan.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 70 files, 3.7M
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/libgphoto2-2.5.1
Already downloaded: /Users/willin/Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.10
Last 15 lines from /Users/willin/Library/Logs/Homebrew/libgphoto2/01.configure:
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking ltdl.h usability... yes
checking ltdl.h presence... yes
checking for ltdl.h... yes
checking for lt_dlinit in -lltdl... no
configure: error:
libgphoto2 requires the ltdl library, included with libtool

Please make sure that the proper development package is installed
(libltdl-dev, libtool-ltdl-devel, etc.)


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
libgphoto2 error when installing wine https://github.com/Homebrew/homebrew-core/issues/1604
```

**Comment by ilovezfs** [comment]
@willin you should probably read the prior posts in this issue

**Comment by s8i** [comment]
```
brew uninstall -f libtool
brew install --universal --build-from-source libtool
brew install wine
```

worked for me... big thanks!

**Comment by ilovezfs** [comment]
This is now fixed properly if you `brew update`. See https://github.com/Homebrew/brew/pull/308.

**Comment by anandsubbu** [comment]
I tried to install wine today and hit into the same issue as mentioned in this thread.

Here's my version of Homebrew:

`asubramanian:homebrew-core asubramanian$ git log`
`commit fc05135bffd6419d550d6d9f83afbb15832c7bf5`
`Author: Elliot Saba <staticfloat@gmail.com>`
`Date:   Thu Jul 28 10:16:49 2016 -0700`
`<snip>`


The following steps worked fine for me... 

`cd /usr/local/Library/Taps/homebrew/homebrew-core`
`perl -p -i -e 's/"libtool" => :build/"libtool" => :run/' Formula/gd.rb`
`brew install wine`

Note that if I did `git reset --hard origin/master`, as per the one of the comment [above](https://github.com/Homebrew/homebrew-core/issues/1604#issuecomment-223140129), then I still hit the same error.

**Comment by Saklad5** [comment]
I am encountering this error still.

**Comment by MikeMcQuaid** [comment]
Anyone still encountering this should open a new issue.
