### ISSUE TITLE
Unable to install neovim --HEAD

### ISSUE THREAD

**Issue by LeviticusNelson** [Homebrew/homebrew-core#160519]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/LeviticusNelson/da23e0216a7f6825e5eb6679fe093661
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to update my neovim to the latest commit and it won't update after possibly this [change](https://github.com/neovim/neovim/commit/f936a962d04f9937946018cc1386f20bda6fc1de)

### What happened (include all command output)?

brew install --HEAD neovim
==> Fetching neovim
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/157fec6543b2905eee0779572d0506bf455a3938/Formula/n/neovim.rb
#################################################################################################################################################################### 100.0%
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/levi/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at fa9a85ae4 fix(lsp): clean up duplicate and unused meta type annotations
==> cmake -S . -B build -DLUV_LIBRARY=/opt/homebrew/opt/luv/lib/libluv.dylib -DLIBUV_LIBRARY=/opt/homebrew/opt/libuv/lib/libuv.dylib -DLPEG_LIBRARY=/opt/homebrew/opt/lpeg/
==> cmake --build build
==> cmake --install build
Last 15 lines from /Users/levi/Library/Logs/Homebrew/neovim/03.cmake:
2024-01-21 00:48:31 +0000

cmake
--install
build

-- Install configuration: "Release"
CMake Error at build/src/nvim/cmake_install.cmake:87 (file):
  file INSTALL cannot find
  "/tmp/neovim-20240120-59875-kq4sm0/build/lib/nvim": No such file or
  directory.
Call Stack (most recent call first):
  build/cmake_install.cmake:82 (include)

### What did you expect to happen?

I expected to install the most up-to-date neovim

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --HEAD neovim
```

**Comment by SMillerDev** [comment]
`--HEAD` builds aren't officially supported since you're not building a stable target but just "whatever upstream has as a latest commit"

**Comment by dundargoc** [comment]
@LeviticusNelson yah I broke it. Working on it

**Comment by georgeguimaraes** [comment]
it's fixed now on upstream
