### ISSUE TITLE
qt build fails with '--universal' argument

### ISSUE THREAD

**Issue by wfaulk** [Homebrew/homebrew-core#1605]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Installing qt with the '--universal' argument causes brew to attempt to build qt, and it fails with this error:

    clang: error: invalid Xarch argument: '-Xarch_i386 -framework', options requiring arguments are unsupported

gist-logs: https://gist.github.com/3aafd33ab9cbad5127338896d848eb1b

This is under MacOS X 10.10.5, `clang++` version "Apple LLVM version 7.0.2 (clang-700.1.81)".

**Comment by ilovezfs** [comment]
Yup same error on 10.11.5 with Xcode 7.3.1:
```
clang: error: invalid Xarch argument: '-Xarch_i386 -framework', options requiring arguments are unsupported
clang: error: invalid Xarch argument: '-Xarch_i386 -framework', options requiring arguments are unsupported
make[4]: *** [../../../../plugins/phonon_backend/libphonon_qt7.dylib] Error 1
make[3]: *** [release] Error 2
make[2]: *** [sub-qt7-make_default] Error 2
make[1]: *** [sub-phonon-make_default] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by ilovezfs** [comment]
This has been going on a long time. See
https://github.com/Homebrew/legacy-homebrew/issues/21770#issuecomment-22378591
https://llvm.org/bugs/show_bug.cgi?id=16805
https://bugreports.qt.io/browse/QTBUG-32832
https://forum.qt.io/topic/35044/build-failure-4-8-5-on-mac-with-phonon/13

It seems the workaround is to build x86 with gcc not clang, but since gcc doesn't do universal builds, I'm not sure where that leaves us in terms of what to do with the formula.

**Comment by MikeMcQuaid** [comment]
@ilovezfs We should just remove the `--universal` option I think.

**Comment by ilovezfs** [comment]
@MikeMcQuaid Yeah, that seems like the most straightforward answer, but I wasn't sure if that was going to make anyone howl :wolf:

**Comment by wfaulk** [comment]
Uh, yeah; it's going to make me howl.

I specifically need an x86 QT to support a commercial app.

**Comment by MikeMcQuaid** [comment]
@wfaulk We're sorry but this is Qt's responsibility, not ours.

**Comment by wfaulk** [comment]
Yeah, I see that now.  Sorry.

**Comment by MikeMcQuaid** [comment]
That's OK, I realise it's annoying regardless.

**Comment by DomT4** [comment]
At this point Qt4 is security fixes only, so whilst this is worth reporting to them I'd be surprised if they fixed it sadly. Agree with the option removal here.

**Comment by UniqMartin** [comment]
> At this point Qt4 is security fixes only, so whilst this is worth reporting to them I'd be surprised if they fixed it sadly.

At this point it's EOL (since December 2015) and doesn't even receive security fixes. Upstream certainly doesn't care or support anymore. (Maybe things are different if you are a paying customer.)

**Comment by DomT4** [comment]
Missed that announcement, or forgot about it. We really need to find some time to start kicking things over to Qt5 where supported 😓.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew uses qt
automoc4                                 soccerwindow2                          
avidemux                                 sqlitebrowser                          
codequery                                sqliteman                              
coin                                     valkyrie                               
cuty_capt                                visualnetkit                           
djview4                                  homebrew/boneyard/comparepdf           
ezlupdate                                homebrew/boneyard/ipe                  
gammaray                                 homebrew/boneyard/kde-phonon           
gnuradio                                 homebrew/boneyard/kdelibs              
gpsbabel                                 homebrew/boneyard/libqxt               
kdiff3                                   homebrew/boneyard/qimageblitz          
libdbusmenu-qt                           homebrew/boneyard/soprano              
libechonest                              homebrew/boneyard/texmacs              
liblastfm                                homebrew/boneyard/wkhtmltopdf          
libqglviewer                             homebrew/games/color-code              
orfeo                                    homebrew/games/hedgewars               
pyqt                                     homebrew/games/hugor                   
pyqwt                                    homebrew/games/qtads                   
pyside                                   homebrew/science/alglib                
qca                                      homebrew/science/biopp                 
qjackctl                                 homebrew/science/cube                  
qjson                                    homebrew/science/octave                
quassel                                  homebrew/science/opencascade           
quazip                                   homebrew/science/osgearth              
qwt                                      homebrew/science/paraview              
qwtpolar                                 homebrew/science/pcl                   
qxmpp                                    homebrew/science/populations           
rcssserver                               homebrew/science/pulseview             
shiboken                                 homebrew/x11/scantailor                
shrewsoft-vpn-client                   
```
:see_no_evil:

**Comment by ilovezfs** [comment]
@DomT4 Well now it's as good as done: https://github.com/Homebrew/homebrew-core/issues/1705
