### ISSUE TITLE
Ansible AttributeError: module 'bcrypt' has no attribute '__about__'

### ISSUE THREAD

**Issue by fmunteanu** [Homebrew/homebrew-core#160525]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.4-76-g9b4427d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b4427d9d81ae3d7bcfe82882f475a1f8fff2aa9
Last commit: 9 hours ago
Core tap HEAD: 86eb2ffefe6bc27ad9dcdd423c948ac541965f81
Core tap last commit: 2 hours ago
Core tap JSON: 21 Jan 04:42 UTC
Core cask tap HEAD: 48836a5452ffd4dcf81cb1e50a6e15264f0fcefd
Core cask tap last commit: 28 minutes ago
Core cask tap JSON: 21 Jan 04:42 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 24
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 24-core 64-bit westmere
Clang: 14.0.0 build 1400
Git: 2.43.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.7.2-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

There is an issue with ansible `bcrypt.py` handler, running this simple playbook to generate a bcrypt password:
```
- name: Test
  hosts: apollo
  become: true
  gather_facts: true
  vars:
    foo: bar
  tasks:
    - name: Debug hashed foo
      ansible.builtin.debug:
        var: foo | password_hash('bcrypt')
```

### What happened (include all command output)?

Produces this warning:
```
TASK [Gathering Facts] *********
ok: [apollo]
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/9.1.0/libexec/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

### What did you expect to happen?

No warning should be generated, however, the password is successfully generated:
```
TASK [Debug hashed foo] *********
ok: [apollo] =>
  foo | password_hash('bcrypt'): $2b$12$mnIC9P5s9j.O7PX1DfjOtOpNuysrj1aC.V3tnTHxaxKJgJmWStFgG
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ansible
```

**Comment by fmunteanu** [comment]
See https://github.com/pyca/bcrypt/issues/684, upgrading to bcrypt 4.1.2 seems to address the issue.

**Comment by fmunteanu** [comment]
@cho-m should I report this issue to Ansible developers?

**Comment by fmunteanu** [comment]
Any update on this issue?

**Comment by ZhongRuoyu** [comment]
`ansible` 9.2.0 should have `bcrypt` 4.1.2 already:

https://github.com/Homebrew/homebrew-core/blob/b49e1bda48e07ed10148dcd44ffdf0d38561b178/Formula/a/ansible.rb#L70-L73

Can you do `brew upgrade` and try again?

**Comment by fmunteanu** [comment]
The warning still shows with 9.2.0:

```
Friday 23 February 2024  16:21:52 -0500 (0:00:02.833)       0:14:55.827 *******
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/9.2.0/libexec/lib/python3.12/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
```

**Comment by Bo98** [comment]
The warning is from `passlib` but `passlib` hasn't received an update in over 3 years and is currently seen to be abandonware, leading to some fork attempts: https://pypi.org/project/passlib-fork.

There's been some discussions upstream about it: https://github.com/ansible/ansible/issues/81949.

We probably won't downgrade `bcrypt`, as using an old version of a security-focussed library is worse than silencing a warning.

**Comment by fmunteanu** [comment]
Sure, on my side, I don’t really care about that warning, as it does not break any functionality for me. I simply wanted to inform you about the issue.

**Comment by Bo98** [comment]
> Is there an alternative or fix?

There's been some effort to reach out to the original developer: https://foss.heptapod.net/python-libs/passlib/-/issues/187

It's got enough attention I'm not too concerned: the situation will improve in some form as there's plenty of people showing interest to sort things out, but it's currently unknown exactly how yet.

**Comment by cho-m** [comment]
May just close this issue as "not planned" as there isn't really an ideal actionable task for Homebrew right now.

The best we can do is just drop `passlib` support totally by removing it from getting added to venv:
https://github.com/Homebrew/homebrew-core/blob/0b6d956373568532389ffb924fc62e6aaf7df8f1/pypi_formula_mappings.json#L19

But the end result is the same as current situation as the feature will remain unusable.

Corresponding upstream projects will need to take the step forward before anything can be done in Homebrew. 

For example, if Ansible adds support for alternatives to `passlib`, e.g. some partial changes in https://github.com/ansible/ansible/pull/82665 but haven't check what extent it replaces reliance on `passlib`.

**Comment by cho-m** [comment]
Closing for now. Can revisit if any upstream activity that allows us to switch libs or backport commits.
