### ISSUE TITLE
New octave formula get rid of its GUI

### ISSUE THREAD

**Issue by gluque** [Homebrew/homebrew-core#16069]
# octave.rb in homebrew-core get rid of the GUI
I have installed Octave 4.2.1 a couple of days ago and I can only run it through the terminal because according to the formulae it was configured with the option: **--with-x=no**. I mean, I could try to enable the GUI again but I wonder whether was there any reason to do that?

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/15986.
