### ISSUE TITLE
libcue is outdated. 

### ISSUE THREAD

**Issue by Wang-Yue** [Homebrew/homebrew-core#1606]
please upgrade to v2.1.0.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by Wang-Yue** [comment]
Sorry I'm not interested in contributing back for the moment. But v2.1.0 fixed many bugs in previous versions and the homebrew team should definitely consider updating it.

**Comment by Wang-Yue** [comment]
Also this issue should not be closed. it shall be closed once a PR is in.

**Comment by MikeMcQuaid** [comment]
@Wang-Yue We rely on the community to provide updates for us. If you'd like it updated, you should try to do so.

**Comment by Wang-Yue** [comment]
@MikeMcQuaid filing a bug report/feature request is also a contribution. anyone with time/experience  and interested in getting it updated can contribute once they see this bug report / feature request. Closing this issue is doing no good to this community.

**Comment by MikeMcQuaid** [comment]
@Wang-Yue We have thousands of packages and it does not scale to have issues sitting open waiting for someone to pick it up. Someone may update it based on this issue, it's just closed because it's not something the current maintainers are going to be focused on.

**Comment by Wang-Yue** [comment]
@MikeMcQuaid  OK I agree what you said. But there should be a scalable way to track all package's status. Maybe you can have a repo/file/masterbug that track all packages' status so someone may pick them up. This is rather important since many package updates solved severe bugs/security issues. 

If there's no way to do that for now, you should open a feature request to make this happen.

**Comment by MikeMcQuaid** [comment]
@Wang-Yue thanks for the suggestions, we'll consider them in future.
