### ISSUE TITLE
mongoreplay missing from mongodb package

### ISSUE THREAD

**Issue by karlpokus** [Homebrew/homebrew-core#16068]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Installing mongodb via homebrew.

- What happened (include command output)

the module `mongoreplay` is missing. See issue [here](https://github.com/mongodb/mongo-tools/issues/92)

- What you expected to happen

mongoreplay to be included.

- Step-by-step reproduction instructions (by running `brew install` commands)

```bash
$ brew install mongodb
...
$ brew update
Updated 1 tap (homebrew/core).
$ brew doctor
Your system is ready to brew.
$ brew gist-logs mongodb
Error: No logs.
$ brew upgrade mongodb
Error: mongodb 3.4.6 already installed
$ ls -lah /usr/local/Cellar/mongodb/3.4.6/bin/
total 546680
drwxr-xr-x  15 pokus  admin   510B Jul  5 20:23 .
drwxr-xr-x   8 pokus  admin   272B Jul 10 13:19 ..
-r-xr-xr-x   1 pokus  admin    11M Jul 10 13:19 bsondump
-r-xr-xr-x   1 pokus  admin    28M Jul 10 13:19 mongo
-r-xr-xr-x   1 pokus  admin    51M Jul 10 13:19 mongod
-r-xr-xr-x   1 pokus  admin    14M Jul 10 13:19 mongodump
-r-xr-xr-x   1 pokus  admin    12M Jul 10 13:19 mongoexport
-r-xr-xr-x   1 pokus  admin    12M Jul 10 13:19 mongofiles
-r-xr-xr-x   1 pokus  admin    12M Jul 10 13:19 mongoimport
-r-xr-xr-x   1 pokus  admin    11M Jul 10 13:19 mongooplog
-r-xr-xr-x   1 pokus  admin    51M Jul 10 13:19 mongoperf
-r-xr-xr-x   1 pokus  admin    15M Jul 10 13:19 mongorestore
-r-xr-xr-x   1 pokus  admin    27M Jul 10 13:19 mongos
-r-xr-xr-x   1 pokus  admin    12M Jul 10 13:19 mongostat
-r-xr-xr-x   1 pokus  admin    12M Jul 10 13:19 mongotop
```

**Comment by dunn** [comment]
We'd love a PR fixing this, if you're willing to try!  Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md and let us know if you have questions.

**Comment by karlpokus** [comment]
@dunn I'd love to help but I don't know ruby. Maybe we can start by confirming if indeed the problem is as stated below.

> when looking at ruby script that is used to generate the package, libpcap is not listed as a dependency and is therefore missing when they build the binaries. The libpcap headers are required to properly build mongoreplay so it is probably skipped and not distributed.

From [this issue](https://github.com/mongodb/mongo-tools/issues/92)

**Comment by dunn** [comment]
What version of libpcap is required?  macOS comes with libpcap, so it's missing from the formula since I guess we assumed we could use the system version.

**Comment by karlpokus** [comment]
@dunn So is the build failing?

**Comment by dunn** [comment]
No, but I'm not sure if it's skipping mongoreplay because the system libpcap is too old, or it just isn't finding it.

**Comment by DomT4** [comment]
Neither, apparently. https://github.com/Homebrew/homebrew-core/pull/16794
