### ISSUE TITLE
tarsnap broken since upgrade to build against openssl@3

### ISSUE THREAD

**Issue by mrtazz** [Homebrew/homebrew-core#160754]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

% brew doctor
Your system is ready to brew.

% brew config 
HOMEBREW_VERSION: 4.2.5-37-g044d06d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 044d06d105a4efe0b801f73b666b44ce540cac35
Last commit: 2 hours ago
Core tap JSON: 23 Jan 18:54 UTC
Core cask tap JSON: 23 Jan 18:54 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT_CONFIG_PATH: /Users/mrtazz/.batrc
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.QbS9X4AArq/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.2-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false

### Verification

- [x] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [x] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [x] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

using tarsnap with the newest version `1.0.40_1`

### What happened (include all command output)?

When running the binary, an exception occurs and the binary doesn't work:

```
% tarsnap --keyfile ${machine}.key --list-archives
Please enter passphrase for keyfile ${machine}.key:
tarsnap: Generic scrypt code is broken - please report bug!
zsh: abort      tarsnap --keyfile ${machine}.key --list-archives
```

Debugging this it seems this is broken since [switching the formula to openssl@3](https://github.com/Homebrew/homebrew-core/commit/881aaec13c9577a3edfb69593a52f544e4a9ae6c). Using the previous formula (i.e. [from here](https://raw.githubusercontent.com/Homebrew/homebrew-core/18790e9751cb9b6e323cee09787bb4defc8f6ae8/Formula/tarsnap.rb)) results in a working tarsnap install.

This is true for installing from source as well as bottle.

### What did you expect to happen?

the binary should work

### Step-by-step reproduction instructions (by running `brew` commands)

```
brew install tarsnap
<run tarsnap>
```

**Comment by mrtazz** [comment]
I filed this here since on first look it seems more like a packaging problem rather than a software problem. But pinging @cperciva and @gperciva just in case and to maybe give some more input.

**Comment by Bo98** [comment]
This sounds similar to https://github.com/technion/libscrypt/issues/60. I imagine it's fixed on the tarsnap side with https://github.com/Tarsnap/tarsnap/commit/4af6d8350ab53d0f1f3104ce3d9072c2d5f9ef7a, though there hasn't been a release in 2 years so will have to manually apply that to see if it works.

**Comment by gperciva** [comment]
Yes, this is a problem with our stable releases, now fixed in git.  (This bug is not related to openssl.)

I believe that one workaround is to add:
```
ENV.append_to_cflags "-fno-strict-aliasing"
```
to the top of the "def install" section, but I haven't had confirmation from anybody with an Intel mac.  (As far as I know, this does not effect M1 or M2 machines.

Regarding a PR: I know that the fix works on the command-line, but it's just possible that this is the wrong way to add compiler flags to brew, so I hesitated to submit a PR that I hadn't checked myself.

**Comment by gperciva** [comment]
Sorry, I just looked at the brew log supplied by @mrtazz in more detail.  You encountered this on an arm64 machine?!

I'm surprised, and I'll investigate on an M2 that I have access to.  I thought that it only affected Intel SSE2 machines!  (I knew that in theory it could affect other CPUs, but I hadn't heard of this happening in practice.)

**Comment by mrtazz** [comment]
> Sorry, I just looked at the brew log supplied by @mrtazz in more detail. You encountered this on an arm64 machine?!

hey @gperciva, thanks for looking into this. Yea this is on an arm64 machine. I don't currently have an intel based one to try and recreate the issue there. Happy to test out patches though if that would help
