### ISSUE TITLE
tfenv loses installed versions of terraform on update

### ISSUE THREAD

**Issue by kevwil** [Homebrew/homebrew-core#16077]
# Please always follow these steps:
- [ X ] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ X ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (broken)
- [ X ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

output of brew config:
```
$ brew config
HOMEBREW_VERSION: 1.2.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: f0ca3108f779f7248c4ea38426a4c43ed0e9793f
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c1099004aee3be34949aad3ec61c9311f3c9db6c
Core tap last commit: 40 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/myusername/.rbenv/shims/ruby => /Users/myusername/.rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_141, 1.8.0_131, 1.8.0_121, 1.8.0_112, 1.8.0_102
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```
output of brew doctor:
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker-machine
```

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

run `terraform` after `brew upgrade && brew cleanup` has upgraded the installed version of tfenv

- What happened (include command output)

```
tfenv: tfenv-version-name: [ERROR] No versions of terraform installed. Please install one with: tfenv install
/usr/local/Cellar/tfenv/0.5.2/libexec/tfenv-exec: line 22: /usr/local/Cellar/tfenv/0.5.2/versions//terraform: No such file or directory
```

- What you expected to happen

Previously installed versions of Terraform should still be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

* cd $( brew --prefix )
* git checkout 6310cc2a41340104f26e3c302432326b7cd05978 Library/Formula/tfenv.rb
* brew install tfenv (should be 0.5.0)
* tfenv install 0.9.8
* (note path to terraform executable is /usr/local/Cellar/tfenv/0.5.0/versions/0.9.8/terraform)
* terraform --version
* git checkout -- Library/Formula/tfenv.rb
* brew upgrade
* brew cleanup
* brew info tfenv (should be 0.5.2 as of today)
* terraform --version (should get error message as above)

## Further details:

It seems that tfenv installs versions of Terraform under the versioned Cellar path of tfenv itself; thus all installed versions of Terraform are deleted when tfenv is upgraded and old tfenv versions are deleted.

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by dunn** [comment]
Looks like it's hardcoded to use the installation root for the versions directory: https://github.com/kamatama41/tfenv/blob/master/libexec/tfenv-install#L34

I'd file an issue upstream asking for it to be configurable.

**Comment by DomT4** [comment]
Leave it be bot. There's an open upstream report.

**Comment by DomT4** [comment]
Go away.

**Comment by kevwil** [comment]
JEeezuzz how annoying. Go away!

**Comment by ilovezfs** [comment]
Happy to review a PR fixing this.
