### ISSUE TITLE
Why not add another formula for selective system python shadowing?

### ISSUE THREAD

**Issue by grischa** [Homebrew/homebrew-core#16087]
Unfortunately, the discussion of issue #15746 did not result in a solution. Closing it for discussion doesn't make this problem go away. PEP394 is real, there should not be two python installations available on python and python2. Simply suggesting edits to /etc/paths or bash_profile is not a good solution.

I understand some people have other priorities (prefer outdated python versions?), and asked for this change to be made and the brew maintainers went through some effort to make it happen. Now they aren't getting praised but criticised for their hard work. Doesn't seem fair, I know.

How about creating a formula for other packages that depend on python that installs the non-shadowing version, e.g. `python-base` and another one that installs full python, PEP394 conforming called `python`? Then everyone can have what they need, no?

https://gist.github.com/295473df7d94ec850a34f7dbd16d4b83

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by ilovezfs** [comment]
Please do not reopen duplicates of already closed issues.

**Comment by MikeMcQuaid** [comment]
> PEP394 is real, there should not be two python installations available on python and python2.

We do not control one of the two python installations so there's nothing we can do about the macOS system one. We control our one, read PEP394 and are following the best compromise we can at the time. Note that we are not bound by PEP394 or anything except the desire to provide the best experience for our users.
