### ISSUE TITLE
Fixing yarn's global installation prefix

### ISSUE THREAD

**Issue by chrmoritz** [Homebrew/homebrew-core#16083]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **=> not a installation error, but a runtime issue**
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
<details><summary> brew doctor & brew config</summary>

```
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.2.5-14-g88b762f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 88b762f78447842a6187e0fda49c9493f029cbef
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 88f1a8ffdbad54b4fab8bddf3cdfb9b690c9eaa0
Core tap last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_45
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```
</details>

-------

###  2 issues with yarn and how to reproduce them

Installing something globally with a homebrew provided `yarn` is completely broken atm, which has 2 unfortunate side affects noticeable for homebrew users:
1.  Packages installed globally will not end up in the users $PATH:
    * run `yarn global add coffeescript`
    * try to run `coffee` or `which coffee` and you will see that no symlink is created to `/usr/local/bin`(similar to what npm would do when installing modules globally)
    * debugging it further you will find out the the symlinks are created inside node's cellar inside the `bin` folder (next to the `node` executable) instead (e.g. `HOMEBREW_PREFIX/Cellar/node/<version>/bin/coffee`)
    * in the end `yarn` will write something to another formulas cellar when installing modules globally, which should be avoided imho
2. Formulas with a build time dependency on yarn will fail installling native addons
    * this is caused by yarn not being able to globally install a copy of `node-gyp`which will end up in the users $PATH
    * fortunately this has only affected the installation of the optional `fsevents` addon in core formulae so far (see messages about skipping the optional dependency `fsevents` in formulae depending on yarn)

### The cause of these issues

This issue is caused by `yarn` [auto-detecting it's global prefix](https://github.com/yarnpkg/yarn/blob/050815d5c2552d1ab8a74aa16790150c7f881a2b/src/registries/npm-registry.js#L33-L34) as the same folder containing the `node` executable (following symlinks). In the case of homebrew the `node` executable (after resolving the symlink from `/usr/local/bin`) is located inside `HOMEBREW_PREFIX/Cellar/node/<version>/bin` and yarn unfortunately sets this as it's global prefix (or more precise to `HOMEBREW_PREFIX/Cellar/node/<version>` and global modules get installed to `yarn_global_prefix/bin`). You can check the global module installation prefix by running `yarn global bin`.

### Possible fixes:
We have to set the global installation prefix of `yarn` to `HOMEBREW_PREFIX` (so that global coffeescript module get symlinked to `/usr/local/bin/coffee` instead), which is the same prefix we set for `npm` in the node formula. This can be done by:

1. Calling `yarn config set prefix HOMEBREW_PREFIX` or appending `prefix "/usr/local"` to `~/.yarnrc` directly
    * This can't be done in yarn's `post_install` because homebrew sandbox will block writes to the users home folder.
    * This also wouldn't solve the 2nd issue, because brew manipulates the HOME variable during forumula installation
2. Creating a (undocumented) system wide `.yarnrc` file, which would take precedence of the user's `.yarnrc` file
    * Unfortunately this file has to be located inside what `yarn` considers to be the global prefix (`HOMEBREW_PREFIX/Cellar/node/<version>/.yarnrc`) so we would end up fixing it by putting something in another formulas Cellar which would not persist `node` updates (unless we would create this file inside the node formula)
    * This also can't be done in yarn's `post_install` because of the sandbox, but it would need to end up in the `node` formula anyway (see above)
3. Patch [yarn's getGlobalPrefix method](https://github.com/yarnpkg/yarn/blob/050815d5c2552d1ab8a74aa16790150c7f881a2b/src/registries/npm-registry.js#L26-L43) to always point to `HOMEBREW_PREFIX`
    * this would require maintaining a patch for the yarn formula
    * https://gist.github.com/chrmoritz/80f90f86796c57d0e0519717df19e04f/74ba59533bbe76e80cb9b81e8acc6b3cd1051b27
4. Change the yarn formula to install yarn wrapped inside a `write_env_script` to set the PREFIX environment variable to `HOMEBREW_PREFIX`
    * The works because of [this getGlobalPrefix logic](https://github.com/yarnpkg/yarn/blob/050815d5c2552d1ab8a74aa16790150c7f881a2b/src/registries/npm-registry.js#L27-L28)
    * https://gist.github.com/chrmoritz/80f90f86796c57d0e0519717df19e04f/73ff3704848d1a8e1a6aa6243552dee074a3f593

BTW: `brew install yarn --HEAD` is also not working.

**Comment by chrmoritz** [comment]
Look also at the similar yarn issue https://github.com/yarnpkg/yarn/issues/1194 which was fixed in https://github.com/yarnpkg/yarn/pull/3458 (by hardcoding the prefix to `/usr/local` on OS X) and got immediately reverted in https://github.com/yarnpkg/yarn/pull/3458 (because of permissions errors and not supporting custom HOMEBREW_PREFIX's).

@ilovezfs @MikeMcQuaid @DomT4 : Any opinions on how this should be fixed?

**Comment by ilovezfs** [comment]
I think we either need an upstream fix or an env script wrapper. The other options sound like non-starters.

**Comment by ilovezfs** [comment]
>BTW: brew install yarn --HEAD is also not working.

Head should be removed for yarn.

**Comment by chrmoritz** [comment]
I agree, that 1 and 2 (`.yarnrc`) are not an option (while something like 2 works very well for npm in homebrew, it is completely broken for yarn and homebrew, see 2 above).

Personally I would prefer 3 (patching `getGlobalPrefix`) over 4 (env script wrapper), because it is a more cleaner fix imho and I'm not yet completely certain that the env script wrapper will work in every case (needs more testing to confirm, that yarn does not call the yarn executable directly instead of our wrapper in some edge cases).

The disadvantage of submitting the patch upstream over applying it during formula installation is that only homebrew knows the location of `HOMEBREW_PREFIX` during compile/installation time, which enables us to use a simple one line patch (or inreplace [like used in my gist](https://gist.github.com/chrmoritz/80f90f86796c57d0e0519717df19e04f/74ba59533bbe76e80cb9b81e8acc6b3cd1051b27#file-yarn-rb-L13-L14) which could be rewritten in a 1 line changing patch). Submitting a patch upstream would require determining the `HOMEBREW_PREFIX` at runtime by for e.g. spawning a sync child process to execute (`brew --prefix`) in `getGlobalPrefix` and use the result as the prefix, which would add a big performance overhead to this method and it would have to be executed every time a global yarn command is invoked vs. only once during formula installation.

> Head should be removed for yarn.

Do you have a strong opinions against fixing and for removing HEAD?

**Comment by ilovezfs** [comment]
@chrmoritz we're not going to carry a patch indefinitely, so if it cannot be upstreamed then I don't think it should go in the formula.

>Do you have a strong opinions against fixing and for removing HEAD?

Analytics show no one is using it.

**Comment by MikeMcQuaid** [comment]
> Submitting a patch upstream would require determining the HOMEBREW_PREFIX at runtime by for example spawning a sync child process to execute (brew --prefix) in getGlobalPrefix and use the result as the prefix, which would add a big performance overhead to this method and it would have to be executed every time a global yarn command is invoked vs. only once during formula installation.

Or: have some sort of `configure` or other upstream buildsystem script to set this value correctly.

**Comment by chrmoritz** [comment]
> @chrmoritz we're not going to carry a patch indefinitely, so if it cannot be upstreamed then I don't think it should go in the formula.

But we're already carrying [another inreplace](https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb#L16) to change the `installationMethod` property to `homebrew` indefinitely and carrying another inreplace to change the globalPrefix to something suitable for homebrew shouldn't be to much different from that.

> Or: have some sort of configure or other upstream buildsystem script to set this value correctly.

`configure` scripts are not very common for JavaScript libraries/cmd line tools, expecially if you expect them to be able to change runtime behavior of the js sources.

**Comment by MikeMcQuaid** [comment]
> But we're already carrying another inreplace to change the installationMethod property to homebrew indefinitely

It would be good not carry that indefinitely.

> configure scripts are not very common for JavaScript libraries/cmd line tools, expecially if you expect them to be able to change runtime behavior of the js sources.

They are not but that's not an argument against them if upstream wants Homebrew to package this properly.

**Comment by chrmoritz** [comment]
Would you be happy if I'd try to submit a patch, which would add another property (similar to `installationMethod`) to package.json for storing the `HOMEBREW_PREFIX`? Yarn could read this property to determine the globalPrefix on OS X for a homebrew based installation and we would have to inreplace `HOMEBREW_PREFIX` in there in addition to the `installationMethod` during formula installation.

Otherwise I think we should go for the env wrapper scripts after some more testing.

**Comment by MikeMcQuaid** [comment]
> Would you be happy if I'd try to submit a patch, which would add another property (similar to installationMethod) to package.json for storing the HOMEBREW_PREFIX? Yarn could read this property to determine the globalPrefix on homebrew OS X and we would have to inreplace HOMEBREW_PREFIX in there in addition to the installationMethod during formula installation.

That seems fine. It does seem weird that we're having to `inreplace` this stuff, though. I do think it would be good to at least attempt having some sort of upstream script that we can call that will set all these values correctly. That means they provide a static interface and the onus is on them to keep it working for us (and it's easy to add to unit tests). If not, yes, env wrapper scripts seems good.

**Comment by chrmoritz** [comment]
> I do think it would be good to at least attempt having some sort of upstream script that we can call that will set all these values correctly.

But this would (at least indirectly) contradict @ilovezfs's request to remove HEAD builds. We are atm using a already prepared/prepublished single-file-production-build of yarn. What you are requesting is to use a github source tarball instead and run the build step on our end, which is exactly what a HEAD build would have to do.

**Comment by MikeMcQuaid** [comment]
> What you are requesting is to use a github source tarball instead and run the build step on our end, which is exactly what a HEAD build would have to do.

I don't think I am requesting that as the tarball could/should include these files.

**Comment by ilovezfs** [comment]
>We are atm using a already prepared/prepublished single-file-production-build of yarn.

And we should continue doing that.

**Comment by chrmoritz** [comment]
I think your are now completely contradicting each other.

> I don't think I am requesting that as the tarball could/should include these files.

Why should a release tarball containing only the already prebuild production build contain the build script which was used the create said production build? And even if it would be included, we couldn't run it with a custom `HOMEBREW_PREFIX` option, because the release tarball does not include the sources on which the build script is run on.

**Comment by ilovezfs** [comment]
@chrmoritz presumably in the next release, if your PR were to be accepted upstream, the new property would make it into the already prepared/prepublished single-file-production-build of yarn that we use, no?

**Comment by ilovezfs** [comment]
We really do need an upstream install script that takes a `--prefix=` option and whatever we're inreplacing or planning to inreplace.

**Comment by MikeMcQuaid** [comment]
> Why should a release tarball containing only the already prebuild production build contain the build script which was used the create said production build?

Every autotools application does this, I don't see why it's impossible here.

> And even if it would be included, we couldn't run it with a custom HOMEBREW_PREFIX option, because the release tarball does not include the sources on which the build script is run on.

An `./install.sh` or whatever that's included in the release build and uses `sed` should and could be in the release tarball.

**Comment by chrmoritz** [comment]
> @chrmoritz presumably in the next release, if your PR were to be accepted upstream, the new property would make it into the already prepared/prepublished single-file-production-build of yarn that we use, no?

In the `package.json` next to `installationMethod`. Yes this was the plan.

> Every autotools application does this, I don't see why it's impossible here.

Yeah, but autotools is run on the sources and not on a minified release build. To be fair you can't compare languages like C (which are compiled during the build step) to languages like JavaScript (which are at most transpiled during the build step and gets interpreted at runtime or partly JIT compiled at runtime nowadays)

> We really do need an upstream install script that takes a --prefix= option and whatever we're inreplacing or planning to inreplace.

> An ./install.sh or whatever that's included in the release build and uses sed should and could be in the release tarball.

It just the point, that I think it is rather unlikely that such a script (put inside the release tarball as suggested by @MikeMcQuaid) would be every accepted upstream and if a spend my time on developing a non trivial upstream patch than it should have at least a small possibility to be accepted. The only place where such an `--prefix=` option would be thinkable would be the Gulpfile (building the github sources like a HEAD build). Unfortunately after looking into restoring the HEAD build I found out that building yarn from source requires another (older) version of `yarn` so this seems infeasible for homebrew too.

**Comment by MikeMcQuaid** [comment]
> Yeah, but autotools is run on the sources and not on a minified release build. To be fair you can't compare languages like C (which are compiled during the build step) to languages like JavaScript (which are at most transpiled during the build step and gets interpreted at runtime or partly JIT compiled at runtime nowadays)

The language they are written in is pretty irrelevant when in both cases you're expecting a downstream packager to modify files for your application to work.

> It just the point, that I think it is rather unlikely that such a script (put inside the release tarball as suggested by @MikeMcQuaid) would be every accepted upstream and if a spend my time on developing a non trivial upstream patch than it should have at least a small possibility to be accepted.

I think it's probably worth asking upstream and pointing them to this thread.

**Comment by chrmoritz** [comment]
> The language they are written in is pretty irrelevant when in both cases you're expecting a downstream packager to modify files for your application to work.

What you are requesting is comparable to asking a C(++) developer to put a script next to the prebuilt binary in their release tarball and expecting the script to rewrite something in the compiled binary.

> I think it's probably worth asking upstream and pointing them to this thread.

I could mentioned this as an alternative, but we should target the to be inreplaced property in `package.json` for the reasons mentioned above.

**Comment by MikeMcQuaid** [comment]
@chrmoritz No, I'm requesting if a project tarball requires modification to be able to be used that they provide a supported API and script for that rather than just having us hack it until it works. I'd be happy with that script writing to some new file that it checks at runtime rather than modifying the JavaScript. In short, I don't care how it works just that it has a static command for us to run.

**Comment by chrmoritz** [comment]
A first draft of the yarn fix can be found here: https://github.com/chrmoritz/yarn/commit/ea7d733ba1a98da9c8a004a09d5d597bf799d8c7

A yarn formula installing a version of this commit from a release build on my fork can be found here:  https://gist.github.com/chrmoritz/4047907cdcf43ca7a8153289fe81c3b7/74815659ac8e7ee5bc4ae9050b132f7ec0f51954
(The upcoming yarn v0.28 release will unfortunately break most yarn based formulas because of strict engine checks by default. Running a different node version than specified in the engine field of package.json is now a error and not a warning anymore).

I'm working on a backport of my commit to the latest stable v0.27.5 for easier testing with homebrew now.

**Comment by chrmoritz** [comment]
I've opened https://github.com/Homebrew/brew/pull/2962 to add a `setup_yarn_environment` helper method to `language/node` which will be needed to fix said strict top level engine checks in yarn depending formulas with the upcoming yarn 0.28.

**Comment by chrmoritz** [comment]
I've updated my yarn test build with a added support for yarn detecting `node-gyp` from the homebrew managed npm (see https://github.com/Homebrew/brew/pull/2962#issuecomment-318746057):
```
brew install https://gist.githubusercontent.com/chrmoritz/4047907cdcf43ca7a8153289fe81c3b7/raw/6b506d89338a9866d6106cb39660e3bce1597483/yarn.rb
```

**Comment by chrmoritz** [comment]
I have a questions about non-default homebrew setups (and which of them are considered supported) to determine, which possible fix I propose upstream:

What we need is a path to our global `npmrc` file in `$(brew --prefix)/lib/node_modules/npm` relative to the resolved node binary location in `$(brew --cellar node)/$version/bin/node`:

* First I assumed that `brew --cellar` will equal `$(brew --prefix)/Cellar` (realpath, not a symlink to the real cellar location) and created https://github.com/chrmoritz/yarn/commit/54e161a2c3bade12d90adfc3ff9917bf4c9de25a
* After reading the sources of [`brew.sh`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L7-L14) and realizing that a cellar located in `HOMEBREW_REPOSITORY` is supported too (`brew --cellar` will equal  `$(brew --prefix)/Homebrew/Cellar`) I've added a second path (which goes one more folder up) in https://github.com/yarnpkg/yarn/commit/33fdf62e7cf8cce5cc0d11a1f02f8d7dc4223534
* Is this enough or do we need to do something more complicated like spawning `brew --prefix` like in https://github.com/chrmoritz/yarn/commit/00ea835421758b66047ffd2a380a531ef61f1b70 (which has a higher performance impact than the simple fix from above)? There are 2 cases, which aren't supported by the simple fix from above:
   * Cellar is just a symlink to the real cellar: There is a [brew doctor check which warns about it](https://github.com/Homebrew/brew/blob/837ea74f448092d822a42ff137642c0aaf076650/Library/Homebrew/diagnostic.rb#L638-L655), so this doesn't look supported to me
   * The Cellar is at a completely different location (e.g not in `HOMEPREW_PREFIX`): I'm unsure if this is a supported setup?

Please let me know what kind of homebrew setups we want to support for `yarn` (and yarn depending formulae) to select the right version of the fix to submit upstream.

cc @ilovezfs

**Comment by MikeMcQuaid** [comment]
> Is this enough or do we need to do something more complicated like spawning brew --prefix like in chrmoritz/yarn@00ea835

I think calling `brew --prefix`, `brew --repo` or `brew --cellar` is the best option rather than making any assumptions about any of them. None of them take more than `0.02s` on my machine.

**Comment by chrmoritz** [comment]
> I think calling brew --prefix, brew --repo or brew --cellar is the best option rather than making any assumptions about any of them. None of them take more than 0.02s on my machine.

I agree, this seems to be the only way to support all edge cases in homebrew setup layouts. Unfortunately it's the one solutions with the highest overhead. Even with the [fast direct return from the shell script](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L17) it's still an async operation compared to the sync path operations (=string manipulations). Lucky the corresponding function was rewritten to an async function during the major yarn 1.0 rewrite, making such async calls possible.
