### ISSUE TITLE
pgxnclient Needs LIBEXEC set

### ISSUE THREAD

**Issue by theory** [Homebrew/homebrew-core#160937]
``` sh
❯ which pgxnclient
/opt/homebrew/bin/pgxnclient

❯ pgxn help --libexec
/usr/local/libexec/pgxnclient
```

Should that be something like `/opt/homebrew/opt/pgxnclient/libexec`?

Looks like the formula should [update `pgxnclient/__init__.py`](/pgxn/pgxnclient/blob/master/pgxnclient/libexec/README):

> Note that setuptools doesn't do a perfect job and replaces the links with the
> script content, dropping the executable flag. If you are packaging pgxnclient
> for a distribution, you may use soft/hard links instead. The location of this
> directory may also be changed if your distribution policies prefer a better
> location (e.g.  ``/usr/lib/pgxnclient/libexec``...): in this case change the
> `LIBEXECDIR` constant in ``pgxnclient/__init__.py`` with the absolute path of
> the scripts directory.

### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

``` console
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ruby@2.7
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install a program in the PGXN client libexec directory, but got an error.

### What happened (include all command output)?

```
mkdir /usr/local/libexec: Permission denied at PGXN-Meta-Validator-v0.16.0/_build/lib/My/Builder.pm line 11.
```

### What did you expect to happen?

The installer I'm using reads the directory to install into from `pgxn help --libexec`. It should point to a homebrew libexec directory that I have permission to install into. Similar to how one can install stuff into the Git libexec directory.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pgxn cpanminus
cpanm PGXN::Meta::Validator -v
```

**Comment by carlocab** [comment]
Yes, we should probably adjust the `LIBEXECDIR` constant. But, `/opt/homebrew/opt/pgxnclient/libexec` is probably not a good choice, because that directory will get wiped when `pgxnclient` is updated.

Though I imagine we also need to manage the fact that `pgxn` expects to find extensions inside `libexec`?

**Comment by theory** [comment]
Yes, that's correct.

**Comment by carlocab** [comment]
Maybe we can point `LIBEXECDIR` to `$HOMEBREW_PREFIX/libexec/pgxnclient` and then symlink the contents of that directory into `$HOMEBREW_PREFIX/opt/pgxnclient/libexec/pgxnclient`?

CC @Homebrew/core for thoughts.

**Comment by MikeMcQuaid** [comment]
> Maybe we can point `LIBEXECDIR` to `$HOMEBREW_PREFIX/libexec/pgxnclient` and then symlink the contents of that directory into `$HOMEBREW_PREFIX/opt/pgxnclient/libexec/pgxnclient`?

This makes sense to me 👍🏻

**Comment by theory** [comment]
*breathes life into the issue…*

**Comment by MikeMcQuaid** [comment]
Passing on this for now. We'll review a PR but to keep this open need to have more people who care about this, sorry.
