### ISSUE TITLE
protobuf 3.0.0-beta-3 (devel) failed to build on Mac OS X 10.11.5

### ISSUE THREAD

**Issue by makelifebetter** [Homebrew/homebrew-core#1609]
### Bug reports:

hi guys:

I need help.
There is a issues in autogen.sh file while i run brew install --devel protobuf.

detail is:[gist-logs](https://gist.github.com/anonymous/82c276c4ce4b0f08e693d387637130f6)

thank you

**Comment by ilovezfs** [comment]
Seems to be a network issue. Can you try again? No drama here:
```
x protobuf-3.0.0-beta-3/util/
x protobuf-3.0.0-beta-3/util/python/
x protobuf-3.0.0-beta-3/util/python/BUILD
==> ./autogen.sh
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2116k  100 2116k    0     0  1593k      0  0:00:01  0:00:01 --:--:-- 1594k
+ autoreconf -f -i -Wall,no-obsolete
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.

```

**Comment by makelifebetter** [comment]
@ilovezfs thanks. I think you are right.
so i download the file by copying the URL(https://googlemock.googlecode.com/files/gmock-1.7.0.zip) into the address bar, and then put the downloaded file into the"/Users/XXX/Library/Caches/Homebrew" folder.
After this i run "brew install --devel protobuf" again and get log here:
=============
sudo brew install --devel protobuf
Password:
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-beta-3.tar.gz
Already downloaded: /Users/XXX/Library/Caches/Homebrew/protobuf-3.0.0-beta-3.tar.gz
==> Downloading https://googlemock.googlecode.com/files/gmock-1.7.0.zip
^@
curl: (7) Failed to connect to googlemock.googlecode.com port 443: Operation timed out
Error: Failed to download resource "protobuf--gmock"
Download failed: https://googlemock.googlecode.com/files/gmock-1.7.0.zip

**Comment by DomT4** [comment]
Are you behind a proxy, located in China or have certain Google domains in your `hosts` file by any chance?

**Comment by ilovezfs** [comment]
@makelifebetter also, a side note: you shouldn't be using "sudo" with brew.

**Comment by makelifebetter** [comment]
@DomT4 thank you.
Located in China, I use the proxy service of Shadowsocks.

**Comment by makelifebetter** [comment]
@ilovezfs thank you for your response.
I have changed the owner of "/usr/local".
I use "brew install --devel protobuf" whithout "sudo",but still get the same log below:
===
brew install --devel protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-beta-3.tar.gz
Already downloaded: /Users/XXX/Library/Caches/Homebrew/protobuf-3.0.0-beta-3.tar.gz
==> Downloading https://googlemock.googlecode.com/files/gmock-1.7.0.zip
^@^@
curl: (7) Failed to connect to googlemock.googlecode.com port 443: Operation timed out
Error: Failed to download resource "protobuf--gmock"
Download failed: https://googlemock.googlecode.com/files/gmock-1.7.0.zip
===
i think it is a pure network issue

**Comment by ilovezfs** [comment]
Are you able to download that file directly?

**Comment by DomT4** [comment]
@makelifebetter Can you try again? I added a Bintray mirror, which typically has less problems surviving China's filtering.

**Comment by makelifebetter** [comment]
@ilovezfs thanks.
1. I can download the file by copying the URL(https://googlemock.googlecode.com/files/gmock-1.7.0.zip) into the address bar.
2. I get failed log below when i use "curl" in terminal (Iterm2).
===
curl -O https://googlemock.googlecode.com/files/gmock-1.7.0.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:16 --:--:--     0curl: (7) Failed to connect to googlemock.googlecode.com port 443: Operation timed out

**Comment by makelifebetter** [comment]
@DomT4 thank you !
After using the command of "brew update",i run "brew install —devel protobuf" again.The result make me happy,it seems that everything is ok.
===
brew install --devel protobuf
==> Downloading https://github.com/google/protobuf/archive/v3.0.0-beta-3.tar.gz
Already downloaded: /Users/XXX/Library/Caches/Homebrew/protobuf-3.0.0-beta-3.tar.gz
==> Downloading https://googlemock.googlecode.com/files/gmock-1.7.0.zip
^@
curl: (28) Connection timed out after 5002 milliseconds
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/gmock-1.7.0.zip
######################################################################## 100.0%^@
==> ./autogen.sh
^@==> ./configure --prefix=/usr/local/Cellar/protobuf/3.0.0-beta-3 --with-zlib
==> make
^@==> make install
==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-20.9.0.tar.gz
######################################################################## 100.0%^@
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/protobuf-20160607-80033-bgrvvt/protobuf-3.0.0-beta-3/homebrew --single-versio
==> Downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/protobuf-20160607-80033-bgrvvt/protobuf-3.0.0-beta-3/homebrew --single-versio
==> Downloading https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-2.5.2.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/protobuf-20160607-80033-bgrvvt/protobuf-3.0.0-beta-3/homebrew --single-versio
==> Downloading https://pypi.python.org/packages/source/p/pytz/pytz-2016.3.tar.bz2
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/protobuf-20160607-80033-bgrvvt/protobuf-3.0.0-beta-3/homebrew --single-versio
==> Downloading https://pypi.python.org/packages/source/p/python-gflags/python-gflags-2.0.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/protobuf-20160607-80033-bgrvvt/protobuf-3.0.0-beta-3/homebrew --single-versio
==> Downloading https://pypi.python.org/packages/source/g/google-apputils/google-apputils-0.4.2.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/protobuf-20160607-80033-bgrvvt/protobuf-3.0.0-beta-3/homebrew --single-versio
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/protobuf/3.0.0-beta-3/libexec --single-version-externally-managed --reco
==> Caveats
Editor support and examples have been installed to:
  /usr/local/Cellar/protobuf/3.0.0-beta-3/share/doc/protobuf

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/XXX/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/XXX/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/protobuf/3.0.0-beta-3: 331 files, 16.7M, built in 6 minutes 3 seconds

**Comment by DomT4** [comment]
Thanks for the confirmation, glad all is working again. Please shout if we can help with anything else 😃.
