### ISSUE TITLE
Certificate issue with https://brew.sh

### ISSUE THREAD

**Issue by shoulda-linuxed** [Homebrew/homebrew-core#16108]
Not sure if this is the proper place to place this issue; and will gladly move/take it down with proper instruction; however, as of 5:01 AM Pacific TIme, 07/27/17; google chrome is reporting a certificate error for https://brew.sh.

I've uploaded a screenshot of the error, available below: 

http://imagebucket.net/qo7lkd3d7mgo/Screen_Shot_2017-07-27_at_4.53.10_AM.png

Not sure if this is intentional (as the 'Advanced' option reveals that Github.com is hosting the site, so it could be a false positive on Chrome's party, but thought it'd be good to bring it to light.

**Comment by fxcoudert** [comment]
Confirmed with all browsers:

```
$ curl https://brew.sh/ 
curl: (51) SSL: no alternative certificate subject name matches target host name 'brew.sh'
```

The list of authorised hostnames for the certificate does not include `brew.sh`:

<img width="793" alt="capture d ecran 2017-07-27 a 15 10 51" src="https://user-images.githubusercontent.com/1980544/28671726-01150866-72de-11e7-83ba-361ae54b0667.png">

**Comment by MikeMcQuaid** [comment]
Thanks for the report, should be fixed now.
