### ISSUE TITLE
`brew` getting stuck on `make` while installing `gcc`

### ISSUE THREAD

**Issue by jolespin** [Homebrew/homebrew-core#16102]
I'm trying to install this but it keeps getting stuck at this step.  Is there anything I can do? I'm running Sierra with the newest home brew installed on July 27 2017.  I'm not sure how to check the home brew version. 
```
$ brew install gcc --without-multilib
==> Using the sandbox
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-7.1.0/gcc-7.1.0.tar.bz2
Already downloaded: /Users/mu/Library/Caches/Homebrew/gcc-7.1.0.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e9e0e
Already downloaded: /Users/mu/Library/Caches/Homebrew/gcc--patch-863957f90a934ee8f89707980473769cff47ca0663c3906992da6afb242fb220.patch
==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> ../configure --build=x86_64-apple-darwin16.7.0 --prefix=/usr/local/Cellar/gc
==> make
```

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

**Comment by MikeMcQuaid** [comment]
Wait 24h: it will take a long time to build. Alternatively, omit `--without-multilib` to get a binary package that doesn't require compilation.
