### ISSUE TITLE
gstreamer formula: Include file gst/gl/gstglconfig.h is missing in the bottle

### ISSUE THREAD

**Issue by kblaschke** [Homebrew/homebrew-core#161084]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9c8374d3b78c4f531c5c2c0d272d1fb1f1b60d70
Last commit: 6 days ago
Core tap JSON: 27 Jan 18:10 UTC
Core cask tap JSON: 27 Jan 18:10 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.42.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.1
Rosetta 2: false


% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Using the gstreamer formula to build a custom GStreamer plug-in.

### What happened (include all command output)?

The "gstglconfig.h" header was not found:
```
In file included from /Users/kai.blaschke/CLionProjects/gst-plugin-projectm/src/plugin.c:6:
In file included from /opt/homebrew/Cellar/gstreamer/1.22.8_2/include/gstreamer-1.0/gst/gl/gl.h:24:
In file included from /opt/homebrew/Cellar/gstreamer/1.22.8_2/include/gstreamer-1.0/gst/gl/gstgl_fwd.h:26:
/opt/homebrew/Cellar/gstreamer/1.22.8_2/include/gstreamer-1.0/gst/gl/gstglapi.h:24:10: fatal error: 'gst/gl/gstglconfig.h' file not found
#include <gst/gl/gstglconfig.h>
         ^~~~~~~~~~~~~~~~~~~~~~
```

### What did you expect to happen?

The "gstglconfig.h" header is in the proper include dir and can be found. Checked the whole brew install dir for the file, it cannot be found. Since this file is generated during the GStreamer build process, it looks like it got lost somewhere in the process, not ending up in the final bottle.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install gstreamer

Then build a simple C test file that includes `gst/gl/gl.h`. This will lead to the error output above:


#include <gst/gl/gl.h>

int main() { return 0; }
```

**Comment by cho-m** [comment]
It is installed into the path that upstream has picked, i.e. `lib/gstreamer-1.0/include/gst/gl/gstglconfig.h`.

See: https://github.com/GStreamer/gstreamer/blob/1.22.8/subprojects/gst-plugins-base/gst-libs/gst/gl/meson.build#L1034-L1036
```meson
  configure_file(input : 'gstglconfig.h.meson',
    output : 'gstglconfig.h',
    install_dir : get_option('libdir') + '/gstreamer-1.0/include/gst/gl',
```

---

Are you using the correct flags during compilation?

For example, 
```
gcc test.c $(pkg-config gstreamer-gl-1.0 --cflags --libs)
```

**Comment by kblaschke** [comment]
To add to this: This looks like it's a GStreamer build system issue. Since GStreamer isn't very popular on macOS, it probably went unnoticed, as GStreamer itself builds and works just fine.

**Comment by cho-m** [comment]
Closing as this is an intentional upstream decision as described in https://gitlab.freedesktop.org/gstreamer/gstreamer/-/commit/90022c451cabbae9a1ae71f82c14c5153c57a3c7

If you disagree with upstream, then you can open an issue over at GStreamer https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues.

**Comment by kblaschke** [comment]
I'm not disagreing with such a decision. The thing is, this file is not installed at all, not even in the mentioned directory - thus there's absolutely no way of building GStreamer plug-ins with GL support anymore. Plus, the include directives in GStreamer's headers still point to `<gst/gl/gstglconfig.h>`, so there's not even a way to add another include dir so the compiler finds the moved file.
