### ISSUE TITLE
`brew upgrade python-setuptools` doesn't upgrade python3.11's setuptools to the latest 69.0.3

### ISSUE THREAD

**Issue by kkdd** [Homebrew/homebrew-core#161014]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew upgrade python-setuptools
Warning: python-setuptools 69.0.3 already installed
$ 
$ brew gist-logs python-setuptools
Error: No logs.
$ 
$ brew config
HOMEBREW_VERSION: 4.2.5-84-g9caedc1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9caedc1ed0813e0fc284a8dc00f61df2465d8f31
Last commit: 73 minutes ago
Core tap JSON: 26 Jan 15:22 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 24
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 24-core 64-bit unknown_0x6_0xb7
Clang: 17.0.6
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 5.15.133.1-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 22.04.3 LTS (jammy)
WSL: 2 (Microsoft Store)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 13.2.0
xorg: N/A
$
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

$ python3.11 -c "import setuptools; print(setuptools.__version__)"
69.0.2
$ python3.12 -c "import setuptools; print(setuptools.__version__)"
69.0.3
$ python3.11 -V
Python 3.11.7

### What happened (include all command output)?

$ python3.11 -c "import setuptools; print(setuptools.__version__)"
69.0.2
$

### What did you expect to happen?

$ python3.11 -c "import setuptools; print(setuptools.__version__)"
69.0.3
$

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew upgrade python-setuptools
Warning: python-setuptools 69.0.3 already installed
$ python3.11 -c "import setuptools; print(setuptools.__version__)"
69.0.2
$
```

**Comment by Bo98** [comment]
`python-setuptools` is for Python 3.12 only, at least at the moment. For 3.11 and earlier we're bundling it with the `python@3.11` install.

**Comment by kkdd** [comment]
Thank you for your comment.
Does it means that `brew upgrade python@3.11` upgrades  setuptools to the latest 69.0.3?

It doesn't upgrade to 69.0.3 on my environment, however:
```
$ brew upgrade python@3.11
Warning: python@3.11 3.11.7_1 already installed
$ python3.11 -c "import setuptools; print(setuptools.__version__)"
69.0.2
$ 
```

**Comment by Bo98** [comment]
They're completely separate and no one has updated the formula to 69.0.3 yet: https://github.com/Homebrew/homebrew-core/blob/5c68c9170efa6269a4ebbd339de4272f5b6df8b4/Formula/p/python@3.11.rb#L81

While we can't always guarantee they'll be in sync, if you are needing 69.0.3 then we can update 3.11 to have that.

**Comment by kkdd** [comment]
Thank you for your explanation.
I understand the exact situation by it.

**Comment by cho-m** [comment]
Closing as updated in #162002
