### ISSUE TITLE
pdal 2.6.2.  Trace/BPT trap: 5 error

### ISSUE THREAD

**Issue by rdzur** [Homebrew/homebrew-core#161342]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

After installing pdal 2.6.2 on a machine (Mac Studio 2022) with Sonoma 14.3, attempting to run the command: pdal --version errors out and returns the following:  Trace/BPT trap: 5.  This behavior has been verified on another machine (MacBook Pro 2021) where pdal was upgraded to 2.6.2. and this same error occurs.   In both machine instances any pdal command returns the same error.  On a third machine (MacBook Pro 2023) also running Sonoma 14.3 and pdal (2.5.5.) which has not been upgraded still has a  functioning pdal installation.  Any assistance with this issue is appreciate.   

### Command that failed

pdal --version

### Output of command with `--verbose --debug`

```shell
Trace/BPT trap: 5
```

### Output of `brew doctor` and `brew config`

```shell
`brew doctor`
Your system is ready to brew.

`brew config`
HOMEBREW_VERSION: 4.2.6-5-g2cb8efc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2cb8efc51d1bf30adb71004d6921ca8beaae9994
Last commit: 24 hours ago
Core tap JSON: 30 Jan 15:34 UTC
Core cask tap JSON: 30 Jan 15:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 20-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Output of `brew tap`

```shell
running the command `brew tap` results in no output
```

**Comment by SMillerDev** [comment]
Can you post `brew config` and `brew doctor` from both the working and non-working device?

**Comment by rdzur** [comment]
non-working:

`brew config`
HOMEBREW_VERSION: 4.2.6-5-g2cb8efc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2cb8efc51d1bf30adb71004d6921ca8beaae9994
Last commit: 3 days ago
Core tap JSON: 30 Jan 15:34 UTC
Core cask tap JSON: 30 Jan 15:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 20
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 20-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false

`brew doctor`
Your system is ready to brew.

working:

`brew config`
HOMEBREW_VERSION: 4.0.28
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b4cfb033757b63ab0b128d01c58db76480956f9
Last commit: 7 months ago
Core tap JSON: 13 Jul 14:53 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false

`brew doctor`
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1

Warning: You are using macOS 14.
We do not provide support for this pre-release version.
It is expected behaviour that some formulae will fail to build in this pre-release version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

**Comment by SMillerDev** [comment]
Since the difference is mostly the PDAL version (and an ancient Homebrew install) I'd recommend submitting an issue to the pdal developers. They can likely debug the issue much better.

**Comment by matekelemen** [comment]
I'm also getting trace traps on an M1 from a large project. The problem only occurs if I try using the HDF5 lib, which is also part of your list of dependencies. Hope this helps.

**Comment by hobu** [comment]
> They can likely debug the issue much better.

Not without a stack trace 😄

**Comment by cho-m** [comment]
I am able to repro `pdal --version` error locally. Homebrew's test does `pdal info` which works.

```
Process 50378 launched: '/opt/homebrew/bin/pdal' (arm64)
Process 50378 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x192457a6c)
    frame #0: 0x0000000192457a6c libunwind.dylib`_Unwind_GetIP + 244
libunwind.dylib`:
->  0x192457a6c <+244>: brk    #0xc471
    0x192457a70 <+248>: mov    x0, x16
    0x192457a74 <+252>: ldp    x29, x30, [sp, #0x10]
    0x192457a78 <+256>: ldp    x20, x19, [sp], #0x20
Target 0: (pdal) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=1, subcode=0x192457a6c)
  * frame #0: 0x0000000192457a6c libunwind.dylib`_Unwind_GetIP + 244
    frame #1: 0x0000000185b97c7c libc++abi.dylib`__gxx_personality_v0 + 588
    frame #2: 0x00000001005a8770 libunwind.1.dylib`unwind_phase2 + 388
    frame #3: 0x00000001005a89a8 libunwind.1.dylib`_Unwind_Resume + 100
    frame #4: 0x00000001000113ac pdal`pdal::TArg<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::assignPositional(this=0x00006000035008f0, vals=0x000000016fdfc1f0) at ProgramArgs.hpp:470:13
    frame #5: 0x000000010000a604 pdal`pdal::ProgramArgs::parseSimple(this=0x000000016fdfc3c8, s=size=1) at ProgramArgs.hpp:1229:22
    frame #6: 0x0000000100009d34 pdal`App::execute(this=0x000000016fdfc4c0, cmdArgs=size=1, log=std::__1::shared_ptr<pdal::Log>::element_type @ 0x000000015a60a820 strong=1 weak=1) at pdal.cpp:326:14
    frame #7: 0x0000000100009bd4 pdal`main(argc=2, argv=0x000000016fdfc7a0) at pdal.cpp:315:17
    frame #8: 0x000000018585d0e0 dyld`start + 2360
```

---

`libunwind` appears to be linked from `llvm` rather than the copy in CLT
```console
❯ brew linkage pdal | rg libunwind
  /opt/homebrew/opt/llvm/lib/libunwind.1.dylib (llvm)
```

`llvm` is indirectly pulled in via `apache-arrow`, which has the workaround
https://github.com/Homebrew/homebrew-core/blob/63744832c44598300a0183adeecff4e88f4fa325/Formula/a/apache-arrow.rb#L44-L46

We can give that a try to see if using CLT libs fixes issue.
