### ISSUE TITLE
gd build fails with command i expects \ followed by text

### ISSUE THREAD

**Issue by apertureless** [Homebrew/homebrew-core#1613]
# Bug Report

gd update is failing: [gist] (https://gist.github.com/anonymous/89bd765d2d073c671898afb5b5250640)

```
2016-06-01 11:23:21 +0200

./bootstrap.sh

docs/naturaldocs/run_docs.sh --nonfatal
skipping doc generation -- please install naturaldoc!
Having trouble on OS X? Try: brew install autoconf libtool automake gettext apple-gcc42 pkg-config cmake
autoreconf -f -i
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
glibtoolize: copying file 'config/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: copying file 'm4/libtool.m4'
glibtoolize: copying file 'm4/ltoptions.m4'
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:64: installing 'config/compile'
configure.ac:61: installing 'config/missing'
src/Makefile.am: installing 'config/depcomp'
sed: 1: "2i/* Generated from con ...": command i expects \ followed by text
```

**Comment by mattsday** [comment]
I found replacing the /usr/bin/sed with gnu sed fixed this - looks like the bootstrap doesn't like BSD sed much

**Comment by ilovezfs** [comment]
The formula depends on gnu-sed, so that doesn't explain why you needed to intervene to install it.

**Comment by henderea** [comment]
I was getting this issue too.  After looking into things, I saw that my install of `gnu-sed` was done with the `--with-default-names` flag.  Uninstalling `gnu-sed` and installing it again without the flag fixed the issue.

It would still be nice to get the formula fixed to support `gnu-sed` installed with that flag.

**Comment by ilovezfs** [comment]
Ah, I see. That's interesting corner case.

I'm patching the formula right now to remove the gnu-sed dependency.

**Comment by ilovezfs** [comment]
@henderea @apertureless https://github.com/Homebrew/homebrew-core/pull/1622

**Comment by DomT4** [comment]
Is everyone impacted here deliberately choosing to build from source or running < OS X 10.9 or something? Bit curious how you're avoiding the `cellar :any` bottle.

**Comment by henderea** [comment]
I'm running 10.11.5, and I'm installing however the default is.

**Comment by DomT4** [comment]
@henderea Hmm, odd. What does `brew info gd` output for you?

**Comment by henderea** [comment]
```
gd: stable 2.2.1 (bottled), HEAD
Graphics library to dynamically manipulate images
https://libgd.github.io/
/usr/local/Cellar/gd/2.2.1 (35 files, 2M) *
  Built from source on 2016-06-01 at 08:47:43 with: --universal
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gd.rb
==> Dependencies
Build: xz, autoconf, automake, libtool, gnu-sed, pkg-config, gettext
Recommended: fontconfig, freetype, jpeg, libpng, libtiff
Optional: webp
==> Options
--universal
	Build a universal binary
--with-webp
	Build with webp support
--without-fontconfig
	Build without fontconfig support
--without-freetype
	Build without freetype support
--without-jpeg
	Build without jpeg support
--without-libpng
	Build without libpng support
--without-libtiff
	Build without libtiff support
--HEAD
	Install HEAD version
```

**Comment by henderea** [comment]
Oh, must be the `--universal` option

**Comment by DomT4** [comment]
> Built from source on 2016-06-01 at 08:47:43 with: --universal

That'll be it. Thanks 👍. I wondered if you'd uncovered a deeper issue with our cellar relocation detection.

**Comment by ilovezfs** [comment]
@DomT4 @henderea I'm actually still confused about the gnu-sed issue. Even if it was installed with default names, wouldn't the /usr/local/bin/sed one have been earlier in the PATH anyway due to superenv?

**Comment by henderea** [comment]
Honestly, I don't know why it matters either, but it was one thing that I could find that was not a default setup, so I figured i would try changing it, and it worked.  BTW, you can then run `brew reinstall gnu-sed --with-default-names` after you install the `gd` update, and it will go back to using the name `sed` instead of `gsed`.  I haven't actually tried anything that uses GD (TBH, I'm not quite sure why I have it installed), but I think `gd` was only using `gnu-sed` for the install process.

**Comment by ilovezfs** [comment]
@henderea Yup, you're right.

@DomT4 @MikeMcQuaid this looks like a :bug to me.
```
sed: 1: "2i/* Generated from con ...": command i expects \ followed by text
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./bootstrap.sh 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
bash-3.2$ which sed
/usr/local/Library/ENV/4.3/sed
bash-3.2$ ls -l /usr/local/bin/sed
lrwxr-xr-x  1 joe  admin  31 Jun  1 07:33 /usr/local/bin/sed -> ../Cellar/gnu-sed/4.2.2/bin/sed
bash-3.2$ /usr/local/Library/ENV/4.3/sed
^Z
[1]+  Stopped                 /usr/local/Library/ENV/4.3/sed
bash-3.2$ ps aux |grep sed
joe             21918   0.0  0.0  2434856    696 s007  TN    7:34AM   0:00.00 /usr/bin/sed
joe             21920   0.0  0.0  2434840    788 s007  SN+   7:34AM   0:00.00 grep sed
bash-3.2$
```
The formula explicitly `depends_on gnu-sed` and yet the superenv wrapper goes with `/usr/bin/sed` anyway.

**Comment by ilovezfs** [comment]
which means all formulae that use `depends_on gnu-sed => :build` + `ENV.prepend_path "PATH", Formula["gnu-sed"].opt_libexec/"gnubin"` are broken for users who have done `brew install --with-default-names gnu-sed`.
