### ISSUE TITLE
undefined method `plist_options' for Formulary

### ISSUE THREAD

**Issue by BainDragneel** [Homebrew/homebrew-core#161534]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
☁  ~  brew install v2ray-core
Error: v2ray-core: undefined method `plist_options' for Formulary::FormulaNamespace6983004a15018f0c4cf2d75c64a421f2f950930d03c5f8aa1b3bcfde39c44ff7::V2rayCore:Class


And my mac is M2
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install v2ray
brew install v2ray-core

### What happened (include all command output)?

Error: v2ray-core: undefined method `plist_options' for Formulary::FormulaNamespace6983004a15018f0c4cf2d75c64a421f2f950930d03c5f8aa1b3bcfde39c44ff7::V2rayCore:Class

### What did you expect to happen?

success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install v2ray
brew install v2ray-core
```

**Comment by Bo98** [comment]
`v2ray-core` is from the tap https://github.com/v2ray/homebrew-v2ray which upstream no longer supports. You should be able to `brew untap v2ray/v2ray` and stick with just `brew install v2ray` that we offer directly.
