### ISSUE TITLE
wxmac fails to install on 10.13

### ISSUE THREAD

**Issue by imrefazekas** [Homebrew/homebrew-core#16167]
I'm using High Sierra (10.13) public beta and can not install wxmac required by erlang used by rabbitmq.

Installation logs:
https://gist.github.com/081a8a3a70b9ca346a66cda428b45639

**Comment by DomT4** [comment]
Known issue. Is fixed in `--HEAD` which builds fine. Someone probably needs to work out what changed in `HEAD` that resolved the problem and then backport those changes to stable/devel if practical, or simply steal the upstream fix as a patch if they've already done so.

**Comment by DomT4** [comment]
Gift: https://github.com/Homebrew/homebrew-core/pull/16178

**Comment by imrefazekas** [comment]
thanks!
