### ISSUE TITLE
Not able to install java7 using brew cask

### ISSUE THREAD

**Issue by rastogiaman** [Homebrew/homebrew-core#16164]
# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by rastogiaman** [comment]
Here are the logs:

ind-1765-mac:~ arastogi$ brew cask install java7
Error: Cask 'java7' is unavailable: No Cask with this name exists.
Error: Install incomplete.
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ brew update
Already up-to-date.
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ brew upgrade brew-cask
Error: No available formula with the name "brew-cask" 
ind-1765-mac:~ arastogi$ brew install caskroom/cask/brew-cask
==> brew cask install caskroom/cask/brew-cask 
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
Error: Install incomplete.
ind-1765-mac:~ arastogi$ brew cleanup && brew cask cleanup
==> Removing cached downloads
/Users/arastogi/Library/Caches/Homebrew/Cask/java--1.8.0_144-b01,090f390dda5b47b9b721c7dfaa008135.dmg
/Users/arastogi/Library/Caches/Homebrew/Cask/java6--1.6.0_65.dmg.incomplete
==> This operation has freed approximately 231.5MB of disk space.
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ 
ind-1765-mac:~ arastogi$ brew install caskroom/cask/brew-cask
==> brew cask install caskroom/cask/brew-cask 
Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.
Error: Install incomplete.
ind-1765-mac:~ arastogi$ brew cask
brew-cask provides a friendly homebrew-style CLI workflow for the
administration of macOS applications distributed as binaries.

Commands:

    --version              displays the Homebrew-Cask version
    audit                  verifies installability of Casks
    cat                    dump raw source of the given Cask to the standard output
    cleanup                cleans up cached downloads and tracker symlinks
    create                 creates the given Cask and opens it in an editor
    doctor                 checks for configuration issues
    edit                   edits the given Cask
    fetch                  downloads remote application files to local cache
    home                   opens the homepage of the given Cask
    info                   displays information about the given Cask
    install                installs the given Cask
    list                   with no args, lists installed Casks; given installed Casks, lists staged files
    outdated               list the outdated installed Casks
    reinstall              reinstalls the given Cask
    search                 searches all known Casks
    style                  checks Cask style using RuboCop
    uninstall              uninstalls the given Cask
    zap                    zaps all files associated with the given Cask

See also "man brew-cask"
Error: Unknown command: 
ind-1765-mac:~ arastogi$ brew cask search java
==> Exact Match
java ✔
==> Partial Matches
charles-applejava                        java-beta                                java6                                    netbeans-java-ee                         yourkit-java-profiler
eclipse-java                             java-jdk-javadoc                         java9-beta                               netbeans-java-se
ind-1765-mac:~ arastogi$ ls -al

**Comment by tschoonj** [comment]
This means that there is no java7 package available. Just install `java`, which is java 8, currently the only supported JDK.
