### ISSUE TITLE
emacs always links against brew fontconfig

### ISSUE THREAD

**Issue by drizt** [Homebrew/homebrew-core#1616]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

I have installed XQuartz-2.7.9. When I installing emacs `--with-x11` I want/wait that emacs will be linked with XQuartz fontconfig but it links with brew fontconfig. Furthemore it force install brew fontconfig if no installed brew fontconfig. brew fontconfig breaks fonts in emacs. See Homebrew/legacy-homebrew#37803 for details. Before I allready opened such issue. But than emacs can be compiled without brew fontconfig. So I could just remove brew fontconfig to get good fonts in emacs.

[Build log](https://gist.github.com/anonymous/2546a5a6017b6233b81bca5dd4382eda)

**Comment by drizt** [comment]
This patch works for me. I use this commit https://github.com/Homebrew/legacy-homebrew/pull/37829/commits/b0fc65c1e7d034dc66a25b49970c61bada194514
[ensure-x11.patch.txt](https://github.com/Homebrew/homebrew-core/files/293229/ensure-x11.patch.txt)

**Comment by DomT4** [comment]
Coming from the author, https://github.com/Homebrew/legacy-homebrew/pull/37829/commits/b0fc65c1e7d034dc66a25b49970c61bada194514 was a bad idea 😉. It's too broadly scoped and has the potential to cause surprising results elsewhere.

The status of the current situation remains as discussed in https://github.com/Homebrew/legacy-homebrew/issues/37803, but I'll leave this open and close the original issue.

**Comment by MikeMcQuaid** [comment]
As of https://github.com/Homebrew/homebrew-core/pull/3531 being merged we no longer provide/support `--with-x11`, I'm afraid.

**Comment by ellio167** [comment]
What's the reasoning for dropping x11 support?  This seems like a big problem for me!

**Comment by DomT4** [comment]
It wasn't being used enough to justify keeping it supported, essentially, and since we don't CI test non-default options having a low number of people using that option is a recipe for breakage to creep through.

**Comment by ellio167** [comment]
On Thu, 1 Sep 2016, Dominyk Tiller wrote:

> It wasn't being used enough to justify keeping it supported, essentially, and since we don't CI test non-default options having a low number of people using that option is a recipe for breakage to creep through.

I see...  Thanks for your reply, it is appreciated.
