### ISSUE TITLE
OpenCV installation with python3 and java

### ISSUE THREAD

**Issue by Amritasha** [Homebrew/homebrew-core#16181]
**Want to install opencv3 with python3 and java** 

Installed opencv3 with - 

> brew install opencv3 --with-contrib --with-python3 --without-python

Installed perfectly.

However, when installing with java using - 

> brew install opencv3 --HEAD --with-contrib --with-java

Error - 

> Error: homebrew/science/opencv3 3.2.0 is already installed

no folder named java in -

> /usr/local/opt/opencv3/share/OpenCV/

**Comment by JCount** [comment]
You need to run `brew uninstall opencv3` and then `brew install opencv3 --HEAD --with-contrib --with-java`.

In the future, please use the issue template.
