### ISSUE TITLE
Feature request: termpdf

### ISSUE THREAD

**Issue by adius** [Homebrew/homebrew-core#162]
https://github.com/dsanson/termpdf

**Comment by ilovezfs** [comment]
Would you like to give it a shot? We don't really take requests but the [formula cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md) and [how to open a PR and get it merged](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-%28and-get-it-merged%29.md) guides should help.

**Comment by DomT4** [comment]
We'd need a stable, tagged upstream release so a good first step would be asking upstream for one of those :).
