### ISSUE TITLE
brew install sbt SHA256 mismatch

### ISSUE THREAD

**Issue by glennleekg** [Homebrew/homebrew-core#16204]
$ brew install sbt
==> Using the sandbox
==> Downloading https://cocl.us/sbt01316tgz
==> Downloading from http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c
Actual: 367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397
Archive: /Users/inventor/Library/Caches/Homebrew/sbt-0.13.16
To retry an incomplete download, remove the file above.

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ curl -sL https://cocl.us/sbt01316tgz | shasum -a256 
22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c  -
```

**Comment by ilovezfs** [comment]
I suggest you
```
brew fetch --force sbt
```

**Comment by glennleekg** [comment]
still the same problem

**Comment by ilovezfs** [comment]
can you download https://cocl.us/sbt01316tgz directly?

**Comment by glennleekg** [comment]
I not sure what should I do

**Comment by glennleekg** [comment]
brew fetch --force sbt
==> Downloading https://cocl.us/sbt01316tgz
==> Downloading from http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0
######################################################################## 100.0%
Downloaded to: /Users/inventor/Library/Caches/Homebrew/sbt-0.13.16
SHA256: 367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397
Warning: Formula reports different SHA256: 22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c

What should I do after this ?

**Comment by glennleekg** [comment]
curl -sL https://cocl.us/sbt01316tgz | shasum -a256
367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397  -

**Comment by ilovezfs** [comment]
Save this file to your cache: https://dl.bintray.com/homebrew/mirror/sbt-0.13.16

**Comment by ilovezfs** [comment]
@glennleekg if you could upload the bad file somewhere that might be helpful so we can compare them.

**Comment by glennleekg** [comment]
I think the file is downloaded from this mirror site http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0

**Comment by ilovezfs** [comment]
@glennblock yeah that is what the URL expands to, but the file has the right checksum, at least for me:
```
Josephs-MacBook-Pro:~ joe$ curl -IL https://cocl.us/sbt01316tgz
HTTP/1.1 301 Moved Permanently
Server: nginx/1.13.1
Content-Type: text/html; charset=UTF-8
X-Powered-By: PHP/7.1.6
Cache-Control: no-cache
Date: Sun, 30 Jul 2017 06:17:08 GMT
Location: http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz
Set-Cookie: XSRF-TOKEN=eyJpdiI6IkRvOGdJdEZsN0ZjdUswV2hGdHV0cFE9PSIsInZhbHVlIjoiNTdDM0FOYmEwczV0V2ZORk1aZzZGSEtJNVwvR2h2M0lhTHYreFk5TTlTazMwZldaXC9GTktZaXdTVk5kUXV5S1dTNHh4Y2J2UGtZNlNRTElUeWtVY0ZIdz09IiwibWFjIjoiOGExODIxYWQ4M2I3MWM5MDhiZjExNzZmMWEzY2UzMTA5NmViYTFjNzdkMTZiOTZkMWQ0MTdhODlmMzMxZjI2MCJ9; expires=Sun, 30-Jul-2017 08:17:08 GMT; Max-Age=7200; path=/
Set-Cookie: laravel_session=eyJpdiI6InYrWGxNMzNkUkFpc3FzNFArUmRGY0E9PSIsInZhbHVlIjoiSnZCakxVbGhJeEhrVTF4YXhSclpQSzhHSExaejRTbTM5dTdielwvM1FqZlBnRVEwYStiSkxremJFZE5lMTI2MFgxS296cnA3NnRiM3RYT3F5MHhreUd3PT0iLCJtYWMiOiIzNDhkMjZjNGI5MzI5YWUxYzI1OWQ5OWI3NmYxMzgyZDQxOThlN2I3MDcyMDIwNmUyYmRmMGVjZGJiY2Y0OTA4In0%3D; expires=Sun, 30-Jul-2017 08:17:08 GMT; Max-Age=7200; path=/; HttpOnly

HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: application/x-tar
Date: Sun, 30 Jul 2017 06:17:08 GMT
Etag: 15ae8db94676d00c95750ba6a348d3bd
Last-Modified: Thu, 27 Jul 2017 15:05:53 GMT
Server: ECAcc (sjc/16F8)
X-Cache: HIT
X-Object-Meta-Mtime: 1501105256.000000
X-Timestamp: 1501167952.00555
X-Trans-Id: txe57cba15c759450faf34c-00597a684a
Content-Length: 60378816

Josephs-MacBook-Pro:~ joe$ curl -sL http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz | shasum -a256
22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c  -
Josephs-MacBook-Pro:~ joe$ 
```

**Comment by glennleekg** [comment]
That's really weird ... I tried at different places with internet, and always get the mismatch

curl -sL http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz | shasum -a256
367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397  -
