### ISSUE TITLE
Gnu-smalltalk error downloading- <string.h> not included

### ISSUE THREAD

**Issue by lmbutman** [Homebrew/homebrew-core#162195]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/lmbutman/b5b8553157da275d572b404f1c485ca8
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to install gnu-smalltalk so i can do some programming in smalltalk. On mac M1 ARM.

### What happened (include all command output)?

I get an error that <string.h> isn't included in the getopt.c file. 

Last 15 lines from /Users/imbutman/Library/Logs/Homebrew/gnu-smalltalk/03.make:
                == (unsigned int) strlen (p->name))
                                  ^
getopt.c:655:21: note: include the header <string.h> or explicitly provide a declaration for 'strlen'
2 errors generated.
make[2]: *** [getopt.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c getopt1.c -o getopt1.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c lock.c -o lock.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c avltrees.c -o avltrees.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c strspell.c -o strspell.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c rbtrees.c -o rbtrees.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c md5.c -o md5.o >/dev/null 2>&1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I/opt/homebrew/opt/readline/lib/../include -g -O2 -Wall -c regex.c -o regex.o >/dev/null 2>&1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

### What did you expect to happen?

Gnu-smalltalk to be downloaded

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gnu-smalltalk
```

**Comment by Bo98** [comment]
Not entirely sure why it's building from source for you. Did anything print out from `brew install` that indicated why it wasn't using bottles?

With that said, I will look into the build error itself anyway.

**Comment by Bo98** [comment]
Yes, we've not managed to successfully build `gnu-smalltalk` on ARM yet. Not sure what the status upstream is.

**Comment by lmbutman** [comment]
That's probably why it won't work... Then I guess I'll work in squeak instead. Thanks!
