### ISSUE TITLE
"cppformat" renamed to "fmt"

### ISSUE THREAD

**Issue by tcbrindle** [Homebrew/homebrew-core#1621]
The "cppformat" project has [renamed to "fmt" and released a new 3.0.0 version](https://github.com/fmtlib/fmt/releases). Homebrew currently has a recipe under the name "cppformat" for the 2.1.1 version.

I'd like to update the recipe for the new version, but I'm not sure of the best way to proceed given the change of name, as the contributor guide doesn't cover this. Could anybody give me any guidance?

**Comment by MikeMcQuaid** [comment]
Given it's only a formatter for C++ and that name is pretty generic we're probably not wanting to rename it. If we were renaming this would be the guide: https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Rename-A-Formula.md

**Comment by tcbrindle** [comment]
Thanks for the link, very helpful!

I submitted a pull request with a name change, as the cppformat name already seems to have disappeared from the internet in all but the release announcement for "fmt" so it will probably be quite hard to find in future. If you're dead-set against changing the name then let me know on the PR and I'll resubmit with just the version update.
