### ISSUE TITLE
Upgrade LiquidPrompt formula to 1.10

### ISSUE THREAD

**Issue by dolmen** [Homebrew/homebrew-core#1623]
[Liquid Prompt 1.10](/nojhan/liquidprompt/releases/tag/v_1.10) has been released and is the only supported version.

Please upgrade [the formula](../blob/master/Formula/liquidprompt.rb) to that release for benefit to Homebrew users and to reduce the pain of invalid bug reports sent to the Liquid Prompt maintainer.

The `caveats` block must also be updated because its install instructions are invalid: liquidprompt must not be called from .bash_profile.

Note that I am the upstream maintainer of Liquid Prompt, but not a Mac user, so don't expect a pull request from me.

Cc: @augmentedfourth @adzenith @xu-cheng @wprl @Cottser @lxndrp @mayersj1

**Comment by MikeMcQuaid** [comment]
@dolmen Despite not having a Mac, could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else. It should be as simple as changing two lines (https://github.com/Homebrew/homebrew-core/blob/7db7d4a930d53eb4108f9435025116f642348818/Formula/liquidprompt.rb#L4-L5) which you can do through the GitHub web editor and our CI will check for you. Thanks!

Thanks!
