### ISSUE TITLE
brew's hcloud for x86_64_linux shows 'v1.42.0-dev' although it should provide stable 1.42.0

### ISSUE THREAD

**Issue by yan-huang-ipf** [Homebrew/homebrew-core#162520]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: eb7338abba43112e16e178d4329d5483d6d8fd6f
Last commit: 22 hours ago
Core tap JSON: 13 Feb 11:46 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.1.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 16-core 64-bit zen3
Clang: N/A
Git: 2.40.1 => /bin/git
Curl: 8.2.1 => /bin/curl
Kernel: Linux 6.5.0-17-generic x86_64 GNU/Linux
OS: Ubuntu 23.10 (mantic)
Host glibc: 2.38
/usr/bin/gcc: 13.2.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

As of 13 February 2024 13:36 UTC, on Linux x86_64, `hcloud` provided by `brew` shows the version string `v1.42.0-dev` - even after `brew reinstall hcloud`.

### What happened (include all command output)?

```shell
$ hcloud version
hcloud v1.42.0-dev
```

### What did you expect to happen?

But https://formulae.brew.sh/formula/hcloud states that `brew` should provide the stable version `1.42.0` of `hcloud` for Intel 64-Bit Linux.

And `hcloud-linux-amd64.tar.gz` downloaded from the upstream https://github.com/hetznercloud/cli/releases/tag/v1.42.0 shows `1.42.0`, not `v1.42.0-dev`:

```shell
$ wget https://github.com/hetznercloud/cli/releases/download/v1.42.0/hcloud-linux-amd64.tar.gz
[...]

$ tar -xvf hcloud-linux-amd64.tar.gz
LICENSE
README.md
hcloud

$ chmod +x hcloud

$ ./hcloud version
hcloud 1.42.0
```

Please ensure that `brew`'s `hcloud` for Linux x86_64 is on the stable version `1.42.0` instead of a development version. Thanks.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew update ; brew upgrade ; brew cleanup
Already up-to-date.

$ which brew
/home/linuxbrew/.linuxbrew/bin/brew

$ brew reinstall hcloud
==> Downloading https://ghcr.io/v2/homebrew/core/hcloud/manifests/1.42.0
Already downloaded: /home/yanhuang/.cache/Homebrew/downloads/23f4744aaf8d580913217bd9d88a120e9c2366b631f1e2b8ad680a21cdd24e1c--hcloud-1.42.0.bottle_manifest.json
==> Fetching hcloud
==> Downloading https://ghcr.io/v2/homebrew/core/hcloud/blobs/sha256:53e87efffabca074c7d894e66bd70ad5ae05af24f8d5
Already downloaded: /home/yanhuang/.cache/Homebrew/downloads/090227249f238e7ede1496cc617b8788671ce044b2d509a2e46f0aedb04ddc84--hcloud--1.42.0.x86_64_linux.bottle.tar.gz
==> Reinstalling hcloud 
==> Pouring hcloud--1.42.0.x86_64_linux.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/hcloud/1.42.0: 9 files, 12MB
==> Running `brew cleanup hcloud`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ which hcloud
/home/linuxbrew/.linuxbrew/bin/hcloud

$ hcloud version
hcloud v1.42.0-dev
```

**Comment by SMillerDev** [comment]
As you can see here: https://github.com/Homebrew/homebrew-core/blob/abf863b81e6a918213fb0ec4bbc4f7b45a773961/Formula/h/hcloud.rb it downloads from the stable tag.

**Comment by yan-huang-ipf** [comment]
Thanks a lot for the quick fix.

It works now:
```
$ hcloud version
hcloud v1.42.0
```
