### ISSUE TITLE
aws-sam-cli installed incorrect version of urllib3

### ISSUE THREAD

**Issue by hawflau** [Homebrew/homebrew-core#162626]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  aws-sam-cli-nightly
  aws-sam-cli-beta-cdk

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  dep
  jsonschema
  node@12
  openssl@1.1
  python@3.7

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMidwayClientSuiteLibraryMac.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-jmespath
  docker-credential-helper-ecr
  virtualenv
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Hi, we've received reports that users are seeing errors from urllib3 when they run `sam package` with SAM CLI installed via homebrew.

We found out that, when homebrew installed SAM CLI, it installed `urllib3 2.2.0` which is the latest version of `urllib3`. However, `botocore` (a dependency of SAM CLI) requires `urllib3 < 2.1.0` as specified in its setup.py. There is some breaking changes as mentioned in an [open issue in botocore](https://github.com/boto/botocore/issues/2926). Homebrew didn't seem to be aware of the requirement of `urllib3` version in `botocore`.

See https://github.com/aws/aws-sam-cli/issues/6667 for more info.

### What happened (include all command output)?

```
2024-02-12 05:41:36,703 | Unable to find Click Context for getting session_id.
2024-02-12 05:41:36,708 | Sending Telemetry: {'metrics': [{'events': {'requestId': 'c0b31d56-0433-4541-860a-0326beff394e', 'installationId': '49ea70ab-17f8-43ca-9d1f-d8e3e43ebebc', 'sessionId': 'bc4e0b0c-3b8b-450d-814c-ad225b8ed7e3', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.12.1', 
'samcliVersion': '1.109.0', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'events': [{'event_name': 'SamConfigFileExtension', 'event_value': '.toml', 'thread_id': '9318a650db3645218272fb6cea48c08e', 'time_stamp': '2024-02-11 16:41:32.574', 'exception_name': None}, {'event_name': 
'SamConfigFileExtension', 'event_value': '.toml', 'thread_id': 'add60d4132f746c1a92a29a3221b511a', 'time_stamp': '2024-02-11 16:41:32.681', 'exception_name': None}]}}}]}
2024-02-12 05:41:37,323 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: An HTTP Client raised an unhandled exception: sequence item 0: expected str instance, bytes found
2024-02-12 05:41:37,330 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### What did you expect to happen?

When install `aws-sam-cli` through homebrew, it should install the right version of dependencies

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install aws-sam-cli
sam init --no-interactive --name my-app --runtime python3.10 --dependency-manager pip --app-template hello-world
sam build
sam package
```

**Comment by p-linnane** [comment]
Thanks for the report. We are working through a project to fix issues like this. I've opened https://github.com/Homebrew/homebrew-core/pull/162634 to resolve this.
