### ISSUE TITLE
Need Support for brew installation for opencv 4.8.1

### ISSUE THREAD

**Issue by PRAN20** [Homebrew/homebrew-core#162701]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.8-48-g24c8c0e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 24c8c0e745017507d6bd34a9ccc9e703f437eb3c
Last commit: 9 hours ago
Core tap JSON: 14 Feb 16:49 UTC
Core cask tap JSON: 14 Feb 16:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

was trying to install 4.8.1 with brew but it always install 4.9.0. i tried installation with .rb but it does not install all the packages

### What happened (include all command output)?

% brew install opencv@4.8.1                                                   
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################################### 100.0%
Warning: No available formula with the name "opencv@4.8.1". Did you mean opencv?
==> Searching for similarly named formulae and casks...
==> Formulae
opencv

To install opencv, run:
  brew install opencv

### What did you expect to happen?

installation of opencv 4.8.1

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install opencv@4.8.1
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Manpage#extract---version---force-formula-tap can help you with this.
