### ISSUE TITLE
Set a symbolic link from vi to vim

### ISSUE THREAD

**Issue by VonUniGE** [Homebrew/homebrew-core#16317]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [ x Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config:
```
HOMEBREW_VERSION: 1.3.0-15-g2ad03b8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ad03b8eb30ca69bf4b45c1cfc1ca619e49b9a04
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 06df396f45e210034597154cfdb165bc7b13511c
Core tap last commit: 5 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_144, 1.8.0_111, 1.8.0_91
macOS: 10.12.5-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

brew doctor:
```
Your system is ready to brew.
```
After installing vim, `vi` runs the vim from macOS (`usr/bin/vi` is a symbolic link to `/usr/bin/vim`) and `vim` runs the vim from Homebrew. I'm used to run vim through vi and I would like to add a symbolic link `/usr/local/bin/vi` to `/usr/local/bin/vim`. I think this is a decent default and could benefit to all users.

**Comment by ilovezfs** [comment]
This is what the option `brew install --with-override-system-vi vim` does.

**Comment by VonUniGE** [comment]
Ok, thank you. This should maybe set as default?
