### ISSUE TITLE
Ettercap

### ISSUE THREAD

**Issue by sayan-sibyl** [Homebrew/homebrew-core#16319]
I have checked everything brew doctor update and what not but every time I type in brew install ettercap --with-gtk+ brew installs the 2015 version of ettercap it does not installs the latest version of ettercap what to do?

**Comment by ProfessorCoal** [comment]
"Ettercap #16319
@sayan-sibyl
sayan-sibyl opened this issue 
1 minute ago 
I have checked everything brew doctor update and what not but every time I type in brew install ettercap --with-gtk+ brew installs the 2015 version of ettercap it does not installs the latest version of ettercap what to do?"

**Comment by fxcoudert** [comment]
Homebrew packages the version 0.8.2 of Ettercap, which I believe is the latest version released (on March 14, 2015), as is clear on their webpage: https://ettercap.github.io/ettercap/downloads.html

What version were you expecting to see?

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by ilovezfs** [comment]
@sayan-sibyl `brew install --HEAD ettercap` will install the latest version.
