### ISSUE TITLE
sbt SHA256 mismatch error on Mac 10.12.6

### ISSUE THREAD

**Issue by jnarhan** [Homebrew/homebrew-core#16342]
# Please always follow these steps:
- [ x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
**- What you were trying to do (and why)**
I'm attempting to use Homebrew to install sbt (a build tool for Scala).

**- What happened (include command output)**
Homebrew reports an error with SHA256 checksum being mismatched.

Error: SHA256 mismatch
Expected: 22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c
Actual: 367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397

**- What you expected to happen**
Expected to have the package unpacked without failing on the checksum.

**- Step-by-step reproduction instructions (by running `brew install` commands)**
Please see for full output: https://gist.github.com/jnarhan/2d79adf9e7b21cfd98d86c65b85f544a

* Ran `brew install sbt` 
* Received the error 
* Removed the the file and retried.
* Ran `brew cleanup && brew update` and retried `brew install sbt` .. 

** brew config **
HOMEBREW_VERSION: 1.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 05e9086355607e9103030b1f0e3f186e674ce063
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 289eb7ec60d62311f0727a99820b12a64b6d17b0
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: N/A

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by fxcoudert** [comment]
Hi @jnarhan and thanks for the very complete report. Unfortunately, I cannot reproduce from here: download of https://cocl.us/sbt01316tgz both from within Homebrew and outside lead to the correct SHA-256 sum of `22729…`. Can you retry? I suggest this is a temporary network issue, either on your end or theirs.

**Comment by ilovezfs** [comment]
There is a real issue here. This is the second time it's reported. https://github.com/Homebrew/homebrew-core/issues/16204

**Comment by ilovezfs** [comment]
@eed3si9n any idea what's going on here?

**Comment by fxcoudert** [comment]
@jnarhan could you tell us what the file `/Users/jnarhan/Library/Caches/Homebrew/sbt-0.13.16` contains when the download is incomplete? Is it a valid `.tar.gz` file? Or a HTML error page?

**Comment by jnarhan** [comment]
Thanks for the responses. @fxcoudert the file is *not* recognized as a valid `.tar.gz` file. See attached screenshot:
![screen shot 2017-08-03 at 5 56 21 pm](https://user-images.githubusercontent.com/6789153/28916651-85e2b9d4-7875-11e7-93c2-af94bcb0cd71.png)

**Comment by bhargavg** [comment]
I'm having the same issue too:

![screen shot 2017-08-03 at 5 08 26 pm](https://user-images.githubusercontent.com/5916302/28917035-708ed7ea-786e-11e7-8fea-fc468ba146bc.png)

**Comment by bhargavg** [comment]
The SHA's are indeed different:

```bash
$ brew install sbt
Updating Homebrew...
==> Using the sandbox
==> Downloading https://cocl.us/sbt01316tgz
==> Downloading from http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c
Actual: 367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397
Archive: /Users/bgurlanka/Library/Caches/Homebrew/sbt-0.13.16
To retry an incomplete download, remove the file above.

$ file /Users/bgurlanka/Library/Caches/Homebrew/sbt-0.13.16
/Users/bgurlanka/Library/Caches/Homebrew/sbt-0.13.16: gzip compressed data, was "sbt.tar", last modified: Wed Jul 26 21:15:31 2017, max compression, from Unix

$ openssl dgst -sha256 /Users/bgurlanka/Library/Caches/Homebrew/sbt-0.13.16
SHA256(/Users/bgurlanka/Library/Caches/Homebrew/sbt-0.13.16)= 367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397
```

**Comment by ilovezfs** [comment]
Can someone please upload the bad file?

**Comment by eed3si9n** [comment]
I just downloaded to check but the SHA matches for me:

```
$ curl -L https://cocl.us/sbt01316tgz > sbt-0.13.16.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   520    0   520    0     0    980      0 --:--:-- --:--:-- --:--:--   982
100 57.5M  100 57.5M    0     0  13.8M      0  0:00:04  0:00:04 --:--:-- 17.5M
$ ls
sbt-0.13.16.tgz
$ shasum -a 256 ~/Downloads/homebrewcheck/sbt-0.13.16.tgz
22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c  
$ openssl dgst -sha256 ~/Downloads/homebrewcheck/sbt-0.13.16.tgz
SHA256(/Users/eed3si9n/Downloads/homebrewcheck/sbt-0.13.16.tgz)= 22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c

## original file
$ shasum -a 256 ~/Downloads/sbt-0.13.16.tgz
22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c  /Users/eed3si9n/Downloads/sbt-0.13.16.tgz
```

**Comment by ilovezfs** [comment]
@eed3si9n right, as it does for me and @fxcoudert. The problem is we have three users reporting the same bad checksum.

**Comment by eed3si9n** [comment]
I am going to ping the file hosting ppl, and ask them what's up.

**Comment by ilovezfs** [comment]
@eed3si9n thanks!

**Comment by nquoctuan** [comment]
Same here, it looks like that someone uploaded a bad file, and did not test properly

**Comment by eed3si9n** [comment]
@nquoctuan Could you help us debug this issue? What do you see when you run:

```
$ curl -L -v https://cocl.us/sbt01316tgz > sbt-0.13.16.tgz
```

If there actually is a bad upload somewhere, I am hoping that would reveal it.

**Comment by nquoctuan** [comment]
Hi @eed3si9n ,

Below is the output. Hopefully it can help you. I am struggling to install sbt. 

`jimmy@jimmy-mac ~                                                                                                                          [11:59:00]
> $ curl -L -v https://cocl.us/sbt01316tgz > sbt-0.13.16.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 169.55.145.209...
* Connected to cocl.us (169.55.145.209) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: cocl.us
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0> GET /sbt01316tgz HTTP/1.1
> Host: cocl.us
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.13.1
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< X-Powered-By: PHP/7.1.6
< Cache-Control: no-cache
< Date: Mon, 07 Aug 2017 03:59:45 GMT
< Location: http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz
< Set-Cookie: XSRF-TOKEN=eyJpdiI6ImljVWlyd0RLNE93WnBuZmxqREdYc2c9PSIsInZhbHVlIjoiSnd1OW5OVVY0YTRaYXhGMU9HVjZnQXUraWsyUlRLcjNGNUFPa0R2OU1LUm01TnF1QndYWTdOYXBEcXQ5bDEzbzNpcGVsdCthWjE5M1ZPQVdTR3RtcHc9PSIsIm1hYyI6IjFhMDM4MWE4MTJhZDc4ZDc0NTkyZTkyODViOGRmOTE3YWFlMmQ1ZTVhN2YyMzc2MDc0MWI5YTdiY2Q1NGE3NDkifQ%3D%3D; expires=Mon, 07-Aug-2017 05:59:45 GMT; Max-Age=7200; path=/
< Set-Cookie: laravel_session=eyJpdiI6InJSYlluOFZEdmxaQnh6dkV3cFhyNkE9PSIsInZhbHVlIjoiVGtHbXV0ZHpsNUx4ZHUxbW1HQjZqRGxUbXZmQUZjS1RsTnpGaFJDa2E2YXVhQ2ZcLzFcL0N4ZHhXeFhrc0U1TXN1MVpsNXladFlrTzlqOHNIM05pM0dXZz09IiwibWFjIjoiNDU0M2E4YjBjNGI5ZGU1ZjRlMjc5MzdiZGE5MWU3YjU1NTE1MDY2NDEzMGFmOThmNGI2OTQzNDU2MmNhYWEyMCJ9; expires=Mon, 07-Aug-2017 05:59:45 GMT; Max-Age=7200; path=/; HttpOnly
<
* Ignoring the response-body
{ [527 bytes data]
100   520    0   520    0     0    289      0 --:--:--  0:00:01 --:--:--   288
* Connection #0 to host cocl.us left intact
* Issue another request to this URL: 'http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz'
*   Trying 68.232.45.253...
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0* Connected to 11A36.http.tor01.cdn.softlayer.net (68.232.45.253) port 80 (#1)
> GET /sbt/0.13.16/sbt-0.13.16.tgz HTTP/1.1
> Host: 11A36.http.tor01.cdn.softlayer.net
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Type: application/x-tar
< Date: Mon, 07 Aug 2017 03:59:46 GMT
< Etag: 15ae8db94676d00c95750ba6a348d3bd
< Last-Modified: Thu, 27 Jul 2017 15:05:53 GMT
< Server: ECAcc (sin/BF5B)
< X-Cache: HIT
< X-Object-Meta-Mtime: 1501105256.000000
< X-Timestamp: 1501167952.00555
< X-Trans-Id: txa110ef6f53e64d09ad741-005983f65a
< Content-Length: 22408048
<
{ [2538 bytes data]
100 21.3M  100 21.3M    0     0  1565k      0  0:00:13  0:00:13 --:--:-- 1819k
* Connection #1 to host 11A36.http.tor01.cdn.softlayer.net left intact
`

**Comment by bhargavg** [comment]
@eed3si9n 

```sh
 $ curl -L -v https://cocl.us/sbt01316tgz > sbt-0.13.16.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 169.55.145.209...
* TCP_NODELAY set
* Connected to cocl.us (169.55.145.209) port 443 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: cocl.us
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /sbt01316tgz HTTP/1.1
> Host: cocl.us
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: nginx/1.13.1
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< X-Powered-By: PHP/7.1.6
< Cache-Control: no-cache
< Date: Mon, 07 Aug 2017 04:00:17 GMT
< Location: http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz
< Set-Cookie: XSRF-TOKEN=eyJpdiI6ImE5dzlSd0ZYZHprNjFvXC9ZTXVEd213PT0iLCJ2YWx1ZSI6InBudVpSVWF5RUJuQnVvT3JCU1h0Uk0xUTZBditZMDBEc0lKUUVyOXZBVFppTDJNaEFyNjhoallBQndyTDdHb01jMERCSmtOaXFsVWs3MGgrY1NPRXJnPT0iLCJtYWMiOiJkZmI3OGNkZTIzNDZkNDdjNDYwMzY0YjU3M2NlZGI5ZTgxNWFiNDA4NDUwYTliMGUwZTI2ODFiNDM2MDQ1NWZlIn0%3D; expires=Mon, 07-Aug-2017 06:00:17 GMT; Max-Age=7200; path=/
< Set-Cookie: laravel_session=eyJpdiI6Im1uZkhlekt0N1wvN1BTOWgwcHhTVnRnPT0iLCJ2YWx1ZSI6InNkTHdyUzlwR21rRVBKZmJ5SE1rc2hrNU1WWERwME1MVFwvMUdBVXdqS0tGcWpuOTdQQ3Q3eXlyTHAxek5jZ0kwZ24yUlEyZ2RCRVFZV2FGS01xQzNkQT09IiwibWFjIjoiNjE4NTkyOTJmZWFlYmM1YzgxNzJhOTRmNmY5ZTdmMjkxZTFhN2Q5NTliZGU5ZTVkYTE2NzhhNmMxNDI3ZjMyZCJ9; expires=Mon, 07-Aug-2017 06:00:17 GMT; Max-Age=7200; path=/; HttpOnly
<
* Ignoring the response-body
{ [527 bytes data]
* Curl_http_done: called premature == 0
100   520    0   520    0     0    399      0 --:--:--  0:00:01 --:--:--   399
* Connection #0 to host cocl.us left intact
* Issue another request to this URL: 'http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz'
*   Trying 68.232.45.253...
* TCP_NODELAY set
* Connected to 11A36.http.tor01.cdn.softlayer.net (68.232.45.253) port 80 (#1)
> GET /sbt/0.13.16/sbt-0.13.16.tgz HTTP/1.1
> Host: 11A36.http.tor01.cdn.softlayer.net
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Type: application/x-tar
< Date: Mon, 07 Aug 2017 04:00:17 GMT
< Etag: 15ae8db94676d00c95750ba6a348d3bd
< Last-Modified: Thu, 27 Jul 2017 15:05:53 GMT
< Server: ECAcc (sin/BF5B)
< X-Cache: HIT
< X-Object-Meta-Mtime: 1501105256.000000
< X-Timestamp: 1501167952.00555
< X-Trans-Id: txa110ef6f53e64d09ad741-005983f65a
< Content-Length: 22408048
<
{ [2538 bytes data]
 98 21.3M   98 21.1M    0     0  2086k      0  0:00:10  0:00:10 --:--:-- 1986k* Curl_http_done: called premature == 0
100 21.3M  100 21.3M    0     0  2083k      0  0:00:10  0:00:10 --:--:-- 1859k
* Connection #1 to host 11A36.http.tor01.cdn.softlayer.net left intact
$
$ gzip -t sbt-0.13.16.tgz
gzip: sbt-0.13.16.tgz: unexpected end of file
gzip: sbt-0.13.16.tgz: uncompress failed
$
$ file sbt-0.13.16.tgz
sbt-0.13.16.tgz: gzip compressed data, was "sbt.tar", last modified: Wed Jul 26 21:15:31 2017, max compression, from Unix
```

**Comment by nquoctuan** [comment]
Hi @eed3si9n ,
This is the output of installation,

jimmy@jimmy-mac ~                                                                                                                          [11:59:57]
```
> $ brew install sbt
==> Using the sandbox
==> Downloading https://cocl.us/sbt01316tgz
Already downloaded: /Users/jimmy/Library/Caches/Homebrew/sbt-0.13.16
Error: SHA256 mismatch
Expected: 22729580a581e966259267eda4d937a2aecad86848f8a82fcc716dcae8dc760c
Actual: 367982d8448d26b1ba26026f481b983ea3d4ebacf892ed6a41c4d1ee0d1ec397
Archive: /Users/jimmy/Library/Caches/Homebrew/sbt-0.13.16
To retry an incomplete download, remove the file above.
```

**Comment by ilovezfs** [comment]
@nquoctuan please upload the bad file somewhere so we can see what's in it.

**Comment by nquoctuan** [comment]
@ilovezfs 

https://files.fm/u/a74kbeff

The funny thing is the file have not tgz extension, like @bhargavg mentioned, only sbt-0.13.16

`Already downloaded: /Users/jimmy/Library/Caches/Homebrew/sbt-0.13.16`

**Comment by eed3si9n** [comment]
Thanks! Since you guys are both getting the bad file with the same size, the bad upload (or sync failure?) seems more plausible. 

When I run curl the file is served from a different IP address:

```
* Issue another request to this URL: 'http://11A36.http.tor01.cdn.softlayer.net/sbt/0.13.16/sbt-0.13.16.tgz'
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0*   Trying 72.21.81.253...
```

**Comment by ilovezfs** [comment]
I will add https://dl.bintray.com/homebrew/mirror/sbt-0.13.16 to the formula as a mirror until this is sorted out.

**Comment by ilovezfs** [comment]
You should be able to install it now by doing this:

```
brew update
brew fetch --force sbt
brew install sbt
```

**Comment by eed3si9n** [comment]
Thanks @ilovezfs

**Comment by ilovezfs** [comment]
@eed3si9n no problem

**Comment by bhargavg** [comment]
It works now, Thanks @ilovezfs

**Comment by jnarhan** [comment]
@ilovezfs .. confirming that this has resolved my issue as well - many thanks.

**Comment by nquoctuan** [comment]
thanks @ilovezfs
