### ISSUE TITLE
percona-server (5.6, 5.7) 'mysql_config' has incorrect values due to conflicting path data

### ISSUE THREAD

**Issue by cringdahl** [Homebrew/homebrew-core#16373]
First seen in closed issue [12092](https://github.com/Homebrew/homebrew-core/issues/12092), the `mysql_config` script (used by Ruby and other languages to pull compilation information) spits out an incorrect library location for shared libs; specifically:

    --libs           [-L/usr/local/opt/percona-server@5.6/lib/mysql -lperconaserverclient -lz -lssl -lcrypto]
    --libs_r         [-L/usr/local/opt/percona-server@5.6/lib/mysql -lperconaserverclient -lz -lssl -lcrypto]
    ...
    --libmysqld-libs [-L/usr/local/opt/percona-server@5.6/lib/mysql -lmysqld -lz -lssl -lcrypto]

The libs are located in `/usr/local/opt/percona-server@5.6/lib`, not that + mysql.

This is because, as @VGerris pointed out, the `pkglibdir` variable is being populated with the `/usr/local/Cellar` path location of the lib directory, not the `/usr/local/opt` symlink location the mysql_config script is being called from.

This is relevant verbose output from the script with the current `pkglibdir` value:
```
+ pkglibdir=/usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib
++ echo /usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib
++ sed -e 's;^/usr/local/opt/percona-server@5.6/;;'
+ pkglibdir_rel=/usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib
+ fix_path pkglibdir /usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib lib/mysql lib
+ var=pkglibdir
+ shift
+ for filename in "$@"
+ path=/usr/local/opt/percona-server@5.6//usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib
+ '[' -d /usr/local/opt/percona-server@5.6//usr/local/Cellar/percona-server@5.6/5.6.35-81.0/lib ']'
+ for filename in "$@"
+ path=/usr/local/opt/percona-server@5.6/lib/mysql
+ '[' -d /usr/local/opt/percona-server@5.6/lib/mysql ']'
+ eval pkglibdir=/usr/local/opt/percona-server@5.6/lib/mysql
++ pkglibdir=/usr/local/opt/percona-server@5.6/lib/mysql
+ return
```
This is relevant verbose output from the script with `pkglibdir` changed to the symlinked value:
```
+ pkglibdir=/usr/local/opt/percona-server@5.6/lib
++ echo /usr/local/opt/percona-server@5.6/lib
++ sed -e 's;^/usr/local/opt/percona-server@5.6/;;'
+ pkglibdir_rel=lib
+ fix_path pkglibdir lib lib/mysql lib
+ var=pkglibdir
+ shift
+ for filename in "$@"
+ path=/usr/local/opt/percona-server@5.6/lib
+ '[' -d /usr/local/opt/percona-server@5.6/lib ']'
+ eval pkglibdir=/usr/local/opt/percona-server@5.6/lib
++ pkglibdir=/usr/local/opt/percona-server@5.6/lib
+ return
```

As you can see, the symlink value is properly parsed in the modified script. This is due to `pkglibdir` being contained inside variable `basedir`, which is ultimately derived from `$0`, which will usually be the `/usr/local/opt` symlink.

This is seen in both 5.6 and 5.7.

**Comment by ilovezfs** [comment]
@cringdahl This seems like an upstream issue to me. Have you reported it to them?

**Comment by cringdahl** [comment]
@ilovezfs I don't see it as an upstream issue. The mysql_config is pulled from source and populated with a value during compile, and that's all on the Homebrew side. Besides, this isn't an issue with either MySQL or Percona in native Linux environments.

**Comment by ilovezfs** [comment]
OK. I'll be happy to look at a PR fixing it, but I suggest you report it upstream.
