### ISSUE TITLE
implement a scalable way to track package status

### ISSUE THREAD

**Issue by Wang-Yue** [Homebrew/homebrew-core#1640]
as discussed in https://github.com/Homebrew/homebrew-core/issues/1606, there should be a scalable way to track all package's status (current version, upstream version). For instance, there could be an upstream version value in each formula. when it's outdated user would know it, so someone may pick them up. This is rather important since many package updates solved severe bugs/security issues.

**Comment by MikeMcQuaid** [comment]
Please submit feature requests to https://github.com/Homebrew/brew-evolution, thanks!

**Comment by Wang-Yue** [comment]
You guys are not serious about getting feedback. I gave up. Sorry.

**Comment by MikeMcQuaid** [comment]
@Wang-Yue We're serious about it but it's far harder to work on a generic issue than it is to on a well-thought proposal. We do know that this is something we'd ideally handle but it's not something that is easy or we'd have done it already.

**Comment by Wang-Yue** [comment]
@MikeMcQuaid simply closing important issues is not a good attitude developing any projects. If you can close your issue at your own discretion, you can reject people's hard-working PR as well. 

If you don't have time working on maintaining something, please quit. No one demands your impatient help.

I've been working on various oss/proprietary project before, and I know you are not serious maintaining bug list at all. I don't want to waste my time on this further. If you are serious, file a feature request yourself. This is the last time I'll ever post anything to your project. Good luck.

**Comment by MikeMcQuaid** [comment]
@Wang-Yue I've been helping maintain this project for 7 years and have been working full-time as a software engineer for longer. We're written documentation to ease issues, pull-requests and features being created and it's been clear from each of your issues you have not read them. Have a good day.
