### ISSUE TITLE
sha256 failure for bazel 0.5.3

### ISSUE THREAD

**Issue by toffaletti** [Homebrew/homebrew-core#16427]
# Please always follow these steps:
- [X ] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X ] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

> brew install bazel

- What happened (include command output)

> ==> Downloading https://github.com/bazelbuild/bazel/releases/download/0.5.3/bazel-0.5.3-dist.zip
Already downloaded: /Users/jason/Library/Caches/Homebrew/bazel-0.5.3.zip
Error: SHA256 mismatch
Expected: d6d27e87bb3ccc6f70f885d51b70c4a9924f0b198dec8ccb82baceb912075212
Actual: 76b5c5880a0b15f5b91f7d626c5bc3b76ce7e5d21456963c117ab711bf1c5333
Archive: /Users/jason/Library/Caches/Homebrew/bazel-0.5.3.zip
To retry an incomplete download, remove the file above.

- What you expected to happen

I expect the sha256 to match the one from https://github.com/bazelbuild/bazel/releases
Which it does:
>cat Downloads/bazel-0.5.3-dist.zip.sha256 
>76b5c5880a0b15f5b91f7d626c5bc3b76ce7e5d21456963c117ab711bf1c5333  bazel-0.5.3-dist.zip
>shasum -a 256 /Users/jason/Library/Caches/Homebrew/bazel-0.5.3.zip
76b5c5880a0b15f5b91f7d626c5bc3b76ce7e5d21456963c117ab711bf1c5333  /Users/jason/Library/Caches/Homebrew/bazel-0.5.3.zip

However, the formula contains a different value as of this commit https://github.com/Homebrew/homebrew-core/commit/f383072ef89b95e8f61c6dfa9517399801895008
```
+  url "https://github.com/bazelbuild/bazel/releases/download/0.5.3/bazel-0.5.3-dist.zip"
+  sha256 "d6d27e87bb3ccc6f70f885d51b70c4a9924f0b198dec8ccb82baceb912075212"
```

- Step-by-step reproduction instructions (by running `brew install` commands)

> brew install bazel

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by ilovezfs** [comment]
@toffaletti reported https://github.com/bazelbuild/bazel/issues/3509

**Comment by ilovezfs** [comment]
@toffaletti this should now be fixed if you `brew update` and `brew upgrade`.
