### ISSUE TITLE
ethereum installation fails.

### ISSUE THREAD

**Issue by bezzangi** [Homebrew/homebrew-core#16425]
What can I do?
On Mac OSX El Capitan (10.11.3)

$ brew install ethereum
==> Installing ethereum from ethereum/ethereum
Error: undefined method `head?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:229:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:186:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1510:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1516:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:386:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:300:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

$ brew reinstall ethereum
Error: undefined method `head?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:229:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:186:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1510:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1516:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:386:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:41:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:18:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:13:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by ilovezfs** [comment]
`brew update -f`

**Comment by bezzangi** [comment]
Same result

$ brew update -f
Already up-to-date.
$ brew install ethereum
==> Installing ethereum from ethereum/ethereum
Error: undefined method `head?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:229:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:186:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1510:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1516:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:386:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:300:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by ilovezfs** [comment]
```
brew config
```

**Comment by ilovezfs** [comment]
@bezzangi ?

**Comment by bezzangi** [comment]
Not working

iMac:~ bezzangi$ brew config
HOMEBREW_VERSION: 1.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cce3414fbd39d146d97911dbb3bf07fffaa1080
Last commit: 7 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 196b202be87c873af710afa3e3a46da1992733e5
Core tap last commit: 81 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /anaconda/bin/python => /anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.8 => /opt/X11
iMac:~ bezzangi$ 
iMac:~ bezzangi$ 
iMac:~ bezzangi$ brew install ethereum
==> Installing ethereum from ethereum/ethereum
Error: undefined method `head?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:229:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:186:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1510:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1516:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:386:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:300:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
iMac:~ bezzangi$ brew update
Already up-to-date.
iMac:~ bezzangi$ brew update -f
Already up-to-date.
iMac:~ bezzangi$ brew install ethereum
==> Installing ethereum from ethereum/ethereum
Error: undefined method `head?' for nil:NilClass
Please report this bug:
  http://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:55:in `block in owner='
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `each_value'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:53:in `owner='
/usr/local/Homebrew/Library/Homebrew/formula.rb:229:in `spec_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:186:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:97:in `block in expand'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:84:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1510:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/requirement.rb:200:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1516:in `recursive_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:386:in `expand_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:300:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:194:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
iMac:~ bezzangi$

**Comment by ilovezfs** [comment]
>HOMEBREW_VERSION: 1.1.7

The current version of Homebrew is 1.3.0: https://github.com/Homebrew/brew/releases/tag/1.3.0

What's the output of
```
cd /usr/local/Homebrew
git status
git tag -l
brew update-reset
brew config
```

**Comment by bezzangi** [comment]
iMac:cpp-ethereum--git bezzangi$ cd /usr/local/Homebrew/
iMac:Homebrew bezzangi$ git status
On branch stable
nothing to commit, working tree clean
iMac:Homebrew bezzangi$ git tag -l
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.7.1
0.8
0.8.1
0.9
0.9.1
0.9.2
0.9.3
0.9.4
0.9.5
0.9.8
0.9.9
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
iMac:Homebrew bezzangi$ brew update-reset
==> Fetching /usr/local/Homebrew...
remote: Counting objects: 29542, done.
remote: Compressing objects: 100% (7652/7652), done.
remote: Total 29542 (delta 22203), reused 28428 (delta 21255), pack-reused 0
Receiving objects: 100% (29542/29542), 10.71 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (22203/22203), completed with 771 local objects.
From https://github.com/Homebrew/brew
   7c27bfd3..441bd37f  master     -> origin/master
 * [new tag]           1.1.10     -> 1.1.10
 * [new tag]           1.1.11     -> 1.1.11
 * [new tag]           1.1.12     -> 1.1.12
 * [new tag]           1.1.13     -> 1.1.13
 * [new tag]           1.1.8      -> 1.1.8
 * [new tag]           1.1.9      -> 1.1.9
 * [new tag]           1.2.0      -> 1.2.0
 * [new tag]           1.2.1      -> 1.2.1
 * [new tag]           1.2.2      -> 1.2.2
 * [new tag]           1.2.3      -> 1.2.3
 * [new tag]           1.2.4      -> 1.2.4
 * [new tag]           1.2.5      -> 1.2.5
 * [new tag]           1.2.6      -> 1.2.6
 * [new tag]           1.3.0      -> 1.3.0

==> Resetting /usr/local/Homebrew...
Branch master set up to track remote branch master from origin.
Switched to and reset branch 'master'

==> Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
remote: Counting objects: 176756, done.
remote: Compressing objects: 100% (56465/56465), done.
remote: Total 176756 (delta 121173), reused 175485 (delta 119903), pack-reused 0
Receiving objects: 100% (176756/176756), 49.44 MiB | 5.00 MiB/s, done.
Resolving deltas: 100% (121173/121173), completed with 1048 local objects.
From https://github.com/caskroom/homebrew-cask
   24cbf9e68..8029b97d1  master     -> origin/master
 * [new tag]             v0.1.0     -> v0.1.0
 * [new tag]             v0.10.0    -> v0.10.0
 * [new tag]             v0.10.1    -> v0.10.1
 * [new tag]             v0.11.0    -> v0.11.0
 * [new tag]             v0.12.0    -> v0.12.0
 * [new tag]             v0.12.1    -> v0.12.1
 * [new tag]             v0.12.2    -> v0.12.2
 * [new tag]             v0.13.0    -> v0.13.0
 * [new tag]             v0.14.0    -> v0.14.0
 * [new tag]             v0.14.1    -> v0.14.1
 * [new tag]             v0.15.0    -> v0.15.0
 * [new tag]             v0.16.0    -> v0.16.0
 * [new tag]             v0.16.1    -> v0.16.1
 * [new tag]             v0.16.2    -> v0.16.2
 * [new tag]             v0.17.0    -> v0.17.0
 * [new tag]             v0.17.1    -> v0.17.1
 * [new tag]             v0.17.2    -> v0.17.2
 * [new tag]             v0.17.3    -> v0.17.3
 * [new tag]             v0.18.0    -> v0.18.0
 * [new tag]             v0.18.1    -> v0.18.1
 * [new tag]             v0.18.2    -> v0.18.2
 * [new tag]             v0.18.3    -> v0.18.3
 * [new tag]             v0.19.0    -> v0.19.0
 * [new tag]             v0.19.1    -> v0.19.1
 * [new tag]             v0.19.2    -> v0.19.2
 * [new tag]             v0.19.3    -> v0.19.3
 * [new tag]             v0.19.4    -> v0.19.4
 * [new tag]             v0.2.0     -> v0.2.0
 * [new tag]             v0.20.0    -> v0.20.0
 * [new tag]             v0.20.1    -> v0.20.1
 * [new tag]             v0.21.0    -> v0.21.0
 * [new tag]             v0.21.1    -> v0.21.1
 * [new tag]             v0.22.0    -> v0.22.0
 * [new tag]             v0.23.0    -> v0.23.0
 * [new tag]             v0.24.0    -> v0.24.0
 * [new tag]             v0.25.0    -> v0.25.0
 * [new tag]             v0.26.0    -> v0.26.0
 * [new tag]             v0.26.1    -> v0.26.1
 * [new tag]             v0.27.0    -> v0.27.0
 * [new tag]             v0.27.1    -> v0.27.1
 * [new tag]             v0.28.0    -> v0.28.0
 * [new tag]             v0.29.0    -> v0.29.0
 * [new tag]             v0.29.1    -> v0.29.1
 * [new tag]             v0.29.2    -> v0.29.2
 * [new tag]             v0.3.0     -> v0.3.0
 * [new tag]             v0.3.1     -> v0.3.1
 * [new tag]             v0.3.2     -> v0.3.2
 * [new tag]             v0.3.3     -> v0.3.3
 * [new tag]             v0.3.4     -> v0.3.4
 * [new tag]             v0.3.5     -> v0.3.5
 * [new tag]             v0.3.6     -> v0.3.6
 * [new tag]             v0.3.7     -> v0.3.7
 * [new tag]             v0.30.0    -> v0.30.0
 * [new tag]             v0.30.1    -> v0.30.1
 * [new tag]             v0.31.0    -> v0.31.0
 * [new tag]             v0.31.1    -> v0.31.1
 * [new tag]             v0.32.0    -> v0.32.0
 * [new tag]             v0.33.0    -> v0.33.0
 * [new tag]             v0.33.1    -> v0.33.1
 * [new tag]             v0.34.0    -> v0.34.0
 * [new tag]             v0.35.0    -> v0.35.0
 * [new tag]             v0.36.0    -> v0.36.0
 * [new tag]             v0.36.1    -> v0.36.1
 * [new tag]             v0.36.2    -> v0.36.2
 * [new tag]             v0.37.0    -> v0.37.0
 * [new tag]             v0.37.1    -> v0.37.1
 * [new tag]             v0.38.0    -> v0.38.0
 * [new tag]             v0.38.1    -> v0.38.1
 * [new tag]             v0.39.0    -> v0.39.0
 * [new tag]             v0.39.1    -> v0.39.1
 * [new tag]             v0.39.2    -> v0.39.2
 * [new tag]             v0.39.3    -> v0.39.3
 * [new tag]             v0.4.0     -> v0.4.0
 * [new tag]             v0.40.0    -> v0.40.0
 * [new tag]             v0.41.0    -> v0.41.0
 * [new tag]             v0.41.1    -> v0.41.1
 * [new tag]             v0.42.0    -> v0.42.0
 * [new tag]             v0.43.0    -> v0.43.0
 * [new tag]             v0.43.1    -> v0.43.1
 * [new tag]             v0.44.0    -> v0.44.0
 * [new tag]             v0.45.0    -> v0.45.0
 * [new tag]             v0.46.0    -> v0.46.0
 * [new tag]             v0.47.0    -> v0.47.0
 * [new tag]             v0.48.0    -> v0.48.0
 * [new tag]             v0.49.0    -> v0.49.0
 * [new tag]             v0.5.0     -> v0.5.0
 * [new tag]             v0.5.1     -> v0.5.1
 * [new tag]             v0.5.2     -> v0.5.2
 * [new tag]             v0.5.3     -> v0.5.3
 * [new tag]             v0.5.4     -> v0.5.4
 * [new tag]             v0.50.0    -> v0.50.0
 * [new tag]             v0.51.0    -> v0.51.0
 * [new tag]             v0.51.1    -> v0.51.1
 * [new tag]             v0.52.0    -> v0.52.0
 * [new tag]             v0.52.1    -> v0.52.1
 * [new tag]             v0.53.0    -> v0.53.0
 * [new tag]             v0.53.1    -> v0.53.1
 * [new tag]             v0.53.2    -> v0.53.2
 * [new tag]             v0.53.3    -> v0.53.3
 * [new tag]             v0.54.0    -> v0.54.0
 * [new tag]             v0.54.1    -> v0.54.1
 * [new tag]             v0.55.0    -> v0.55.0
 * [new tag]             v0.56.0    -> v0.56.0
 * [new tag]             v0.57.0    -> v0.57.0
 * [new tag]             v0.58.0    -> v0.58.0
 * [new tag]             v0.59.0    -> v0.59.0
 * [new tag]             v0.6.0     -> v0.6.0
 * [new tag]             v0.60.0    -> v0.60.0
 * [new tag]             v0.60.1    -> v0.60.1
 * [new tag]             v0.7.0     -> v0.7.0
 * [new tag]             v0.8.0     -> v0.8.0
 * [new tag]             v0.9.0     -> v0.9.0
 * [new tag]             v0.9.1     -> v0.9.1
 * [new tag]             v0.9.2     -> v0.9.2

==> Resetting /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum...

==> Resetting /usr/local/Homebrew/Library/Taps/ethereum/homebrew-ethereum...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/Homebrew/homebrew-core
   e6d5d03b..8a27cc46  master     -> origin/master

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch master set up to track remote branch master from origin.
Reset branch 'master'
Your branch is up-to-date with 'origin/master'.

iMac:Homebrew bezzangi$ brew config
HOMEBREW_VERSION: 1.3.0-31-g441bd37
ORIGIN: https://github.com/Homebrew/brew
HEAD: 441bd37fd03d3300c655eea1d206644a2718dce2
Last commit: 61 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8a27cc46ba590d2db3771924b6e4dd0e1f4e23f8
Core tap last commit: 4 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /anaconda/bin/python => /anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_121
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.8 => /opt/X11

**Comment by ilovezfs** [comment]
@bezzangi good. It should be fixed now.

**Comment by bezzangi** [comment]
It looks working. Thank you.

**Comment by ilovezfs** [comment]
You're welcome!

**Comment by bezzangi** [comment]
Well, There is another error.

$ brew install cpp-ethereum --with-gpu-mining --devel --build-from-source
==> Installing cpp-ethereum from ethereum/ethereum
Warning: ethereum/ethereum/cpp-ethereum: this formula has no --with-gpu-mining option so it will be ignored!
==> Using the sandbox
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Updating /Users/bezzangi/Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/l
Last 15 lines from /Users/bezzangi/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
2017-08-06 03:33:14 +0900

cmake
-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DCMAKE_BUILD_TYPE=Release
-DEVMJIT=1

CMake Error: The current CMakeCache.txt directory /tmp/cpp-ethereum-20170806-19020-ed02qf/CMakeCache.txt is different than the directory /Users/bezzangi/Library/Caches/Homebrew/cpp-ethereum--git where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/tmp/cpp-ethereum-20170806-19020-ed02qf/CMakeLists.txt" does not match the source "/Users/bezzangi/Library/Caches/Homebrew/cpp-ethereum--git/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

**Comment by ilovezfs** [comment]
@bezzangi that you will need to report to the 3rd party tap: https://github.com/ethereum/cpp-ethereum/issues
