### ISSUE TITLE
[WARNING]: kubernetes<24.2.0 is not supported or tested. Some features may not work.

### ISSUE THREAD

**Issue by fmunteanu** [Homebrew/homebrew-core#164335]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.9-52-g28ad3f7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28ad3f7fecca6783641596dccbcf7c177b37330d
Last commit: 7 days ago
Core tap HEAD: 91cf92579cd5fda0680a25a2377431b703fe35c7
Core tap last commit: 6 days ago
Core tap JSON: 20 Feb 20:43 UTC
Core cask tap HEAD: e7e0469c71ba576301bffe8be0a2d0a53f9a8c5d
Core cask tap last commit: 6 days ago
Core cask tap JSON: 20 Feb 20:43 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 24
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 24-core 64-bit westmere
Clang: 14.0.0 build 1400
Git: 2.43.2 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.3-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

By default, installing ansible will have kubernetes.core 2.4.0 installed:

```
$ ansible-galaxy collection list kubernetes.core
/usr/local/Cellar/ansible/9.2.0/libexec/lib/python3.12/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0
```

I need to use kubernetes.core 3.0.0 for additional features, so I ran the upgrade:

```
$ ansible-galaxy collection install -U kubernetes.core
$ ansible-galaxy collection list kubernetes.core

/Users/floren/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 3.0.0

/usr/local/Cellar/ansible/9.2.0/libexec/lib/python3.12/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.4.0
```

The problem I encounter is related to this warning, while executing an Ansible playbook:
```
[WARNING]: kubernetes<24.2.0 is not supported or tested. Some features may not work.
```

Looking at these lines:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/a/ansible.rb#L182-L185

I see kubernetes-29 package is listed, which should not produce the warning. How can can I correctly update the Python kubernetes package to version 29?

Files present locally:
```
$ ls -lah /usr/local/Cellar/ansible/9.2.0/libexec/lib/python3.12/site-packages/kubernetes-29.0.0.dist-info
total 208
drwxr-xr-x   10 floren  admin   320B 30 Jan 10:43 .
drwxr-xr-x  197 floren  admin   6.2K 20 Feb 16:07 ..
-rw-r--r--    1 floren  admin     4B 30 Jan 10:43 INSTALLER
-rw-r--r--    1 floren  admin    11K 30 Jan 10:43 LICENSE
-rw-r--r--    1 floren  admin   1.5K 30 Jan 10:43 METADATA
-rw-r--r--    1 floren  admin    71K 30 Jan 10:43 RECORD
-rw-r--r--    1 floren  admin     0B 30 Jan 10:43 REQUESTED
-rw-r--r--    1 floren  admin    92B 30 Jan 10:43 WHEEL
-rw-r--r--    1 floren  admin   106B 30 Jan 10:43 direct_url.json
-rw-r--r--    1 floren  admin    11B 30 Jan 10:43 top_level.txt
```

**Comment by SMillerDev** [comment]
> I see kubernetes-29 package is listed, which should not produce the warning. How can can I correctly update the Python kubernetes package to version 29?

The version defined there is what is installed unless `brew outdated` shows ansible as outdated.

**Comment by SMillerDev** [comment]
If ansible has a command to show what components it uses you can run that, but I know absolutely nothing about ansible or kubernetes in relation to it so I suspect you'll need to find that command on your own.

**Comment by freeyoung** [comment]
@fmunteanu Just in case you or anyone else is still stuck at this - the error message was a bit vague that might lead to the confusion that your local `kubernetes` python library is outdated. However, it was complaining about the `kubernetes` version on the destination machine where you were running ansible against.

Once you upgrade the `kubernetes` or `openshift` version with `pip`, this warning will be gone.

**Comment by freeyoung** [comment]
> @freeyoung I see, I’m running Ubuntu 22.04 LTS with this package installed:
> 
> ```
> # apt search python3-kubernetes
> Sorting... Done
> Full Text Search... Done
> python3-kubernetes/jammy 12.0.1-1ubuntu1 all
>   Kubernetes Python client - Python 3.x
>   ˋ`ˋ
> ```

That explains. So if you would like to get rid of that warning (although it probably won't hurt), you might want to uninstall that package with apt and install the latest one with pip instead.
