### ISSUE TITLE
Permission Error when installing formulae in osgeo/osgeo4mac repo.

### ISSUE THREAD

**Issue by spolloni** [Homebrew/homebrew-core#16443]
- [x]  This is a problem with `brew install`ing one (or more) specific formula.
- [x]  I Ran `brew update` and retried my prior step.
- [x]  I Ran `brew doctor`, fixed all issues and retried my prior step.
- [X] I Ran `brew gist-logs` and included the output [link](https://gist.github.com/1037303a0e3bef6fe2c1d2a04e09cb6c).
------
I'm experiencing weird permissions errors when trying to install some (though not all) formulas from osgeo/osgeo4mac. A quick example would be with `brew install -verbose  osgeo/osgeo4mac/sip-qt4`. I believe the error occurs during the `make clean` step:

> ==> Sandbox log
> Aug  5 17:03:30 sandboxd[93092]: ruby(96271) deny file-write-create /usr/local/share/sip
> Aug  5 17:03:30 sandboxd[93092]: ruby(96271) deny file-write-create /usr/local/share/sip
> Error: Operation not permitted - /usr/local/share/sip

This seems to be a permission issue when the script tries to create the /usr/local/share/sip directory. All my attempts have failed to remedy the situation. Some of these are borderline irresponsible: 

1.  Giving permission with `sudo chown -R $(whoami) /usr/local`.
2.  Disabling the OS's _System Integrity Protection_ with `csrutil disable`.
3.  Messing with homebrew's executables (brew.sh) to allow for `sudo brew install `.
4. Doing a fresh install of homebrew in $HOME and trying to install the formulas from there. 

I am able to `mkdir /usr/local/share/sip` right after the error, but trying to install again will prompt the same error, as the script tries to create yet another (different) directory. Here is the output when using `cd /usr/local/share && ls -l`:
> total 0
> drwxr-xr-x  3 stefanopolloni  admin  102  5 Aug 16:49 doc
> drwxr-xr-x  3 stefanopolloni  admin  102  5 Aug 16:49 man
> drwxr-xr-x  3 stefanopolloni  admin  102  5 Aug 16:48 zsh

Any Clue? Thanks!

**Comment by ilovezfs** [comment]
Yes please see
https://brew.sh/2017/07/31/homebrew-1.3.0/
https://github.com/Homebrew/brew/issues/2986
https://github.com/Homebrew/brew/issues/2994

**Comment by spolloni** [comment]
@ilovezfs  Thanks for this. Would you be able to provide me with a temporary quick fix ? I need these formulas for a research project with a tight deadline.

**Comment by ilovezfs** [comment]
@spolloni `--no-sandbox`

**Comment by spolloni** [comment]
@ilovezfs great, thank you!

**Comment by ilovezfs** [comment]
you're welcome!
