### ISSUE TITLE
 Error: gcc@8 has been disabled because it is deprecated upstream! next #164472 [not solved]

### ISSUE THREAD

**Issue by andykimpe** [Homebrew/homebrew-core#164481]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://github.com/Homebrew/homebrew-core/issues/164472

please stop your bullshit gcc support only stops when there is no longer any unix distribution that uses the version concerned

excluding gcc 8 is part of rhel 9 so support valid until May 31, 2032

which means that you must provide it until this date

currently you must provide all versions of gcc from 4.9

so support ends with rhel 7 on May 31, 2024

has version 13 which is the latest

even Linux distributions take care of this

Please do not close this ticket until the problem is resolved.

this will only be considered resolved when gcc 8 has been reactivated and not before this must remain available until the end of support for all unix distributions which distribute it and not before
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

https://github.com/Homebrew/homebrew-core/issues/164472

please stop your bullshit gcc support only stops when there is no longer any unix distribution that uses the version concerned

excluding gcc 8 is part of rhel 9 so support valid until May 31, 2032

which means that you must provide it until this date

currently you must provide all versions of gcc from 4.9

so support ends with rhel 7 on May 31, 2024

has version 13 which is the latest

even Linux distributions take care of this

Please do not close this ticket until the problem is resolved.

this will only be considered resolved when gcc 8 has been reactivated and not before this must remain available until the end of support for all unix distributions which distribute it and not before

### What happened (include all command output)?

https://github.com/Homebrew/homebrew-core/issues/164472

please stop your bullshit gcc support only stops when there is no longer any unix distribution that uses the version concerned

excluding gcc 8 is part of rhel 9 so support valid until May 31, 2032

which means that you must provide it until this date

currently you must provide all versions of gcc from 4.9

so support ends with rhel 7 on May 31, 2024

has version 13 which is the latest

even Linux distributions take care of this

Please do not close this ticket until the problem is resolved.

this will only be considered resolved when gcc 8 has been reactivated and not before this must remain available until the end of support for all unix distributions which distribute it and not before

### What did you expect to happen?

https://github.com/Homebrew/homebrew-core/issues/164472

please stop your bullshit gcc support only stops when there is no longer any unix distribution that uses the version concerned

excluding gcc 8 is part of rhel 9 so support valid until May 31, 2032

which means that you must provide it until this date

currently you must provide all versions of gcc from 4.9

so support ends with rhel 7 on May 31, 2024

has version 13 which is the latest

even Linux distributions take care of this

Please do not close this ticket until the problem is resolved.

this will only be considered resolved when gcc 8 has been reactivated and not before this must remain available until the end of support for all unix distributions which distribute it and not before

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
https://github.com/Homebrew/homebrew-core/issues/164472

please stop your bullshit gcc support only stops when there is no longer any unix distribution that uses the version concerned

excluding gcc 8 is part of rhel 9 so support valid until May 31, 2032

which means that you must provide it until this date

currently you must provide all versions of gcc from 4.9

so support ends with rhel 7 on May 31, 2024

has version 13 which is the latest

even Linux distributions take care of this

Please do not close this ticket until the problem is resolved.

this will only be considered resolved when gcc 8 has been reactivated and not before this must remain available until the end of support for all unix distributions which distribute it and not before
```

**Comment by SMillerDev** [comment]
> please stop your bullshit gcc support only stops when there is no longer any unix distribution that uses the version concerned

That is wrong and creates a logic loop, support ends when upstream says so: https://gcc.gnu.org/releases.html

Please stop creating new issues or we will be forced to block you from doing so.
