### ISSUE TITLE
Static libraries

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#16441]
There are about 34 formulas that specifically build static libraries (`aalib flac fontconfig freeswitch gdk-pixbuf glib gpgme harfbuzz icu4c imagemagick imagemagick@6 lesstif libao libassuan libetonyek libfreehand libgcrypt libgpg-error libiconv libkate libmagic libmspub libodfgen libpagemaker librevenge libvisio media-info mediaconch pango unixodbc vice x264`) when it's not upstream's default (i.e. that configure with `--enable-static`).

Is that really something we want? For `fontconfig`, for example, it comes from this [2015 PR](https://github.com/Homebrew/legacy-homebrew/pull/45610) but it's not clear to me why we would want to ship static libraries in this case (and not for all other libs).

**Comment by ilovezfs** [comment]
yes.

**Comment by fxcoudert** [comment]
So do we want to provide static libraries for all formulas? If not, what's the criterion?

**Comment by ilovezfs** [comment]
If someone requests them, or it's trivial to build both, we usually do.

**Comment by fxcoudert** [comment]
Thanks
