### ISSUE TITLE
php: ext-imap causes 5 second delay when running cli commands

### ISSUE THREAD

**Issue by Zakini** [Homebrew/homebrew-core#164605]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/Zakini/a401ae448af2d000dae88c7a6fc136dc
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run any `php` cli commands

### What happened (include all command output)?

Running `php` in any way always take 5 seconds before any output appears

```
time php -v
PHP 8.3.3 (cli) (built: Feb 13 2024 15:41:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies
php -v  0.02s user 0.01s system 0% cpu 5.041 total
```

### What did you expect to happen?

Simple commands like `php -v` should run in under a second

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php
time php -v
```

**Comment by SMillerDev** [comment]
Can't reproduce this, do you have any config for imap enabled?
```
bash-5.2$ time php -v
PHP 8.3.3 (cli) (built: Feb 13 2024 15:41:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Xdebug v3.3.1, Copyright (c) 2002-2023, by Derick Rethans
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies

real    0m0.157s
user    0m0.069s
sys     0m0.029s
```

**Comment by Zakini** [comment]
That was quick 😅, I was part way through adding this:

It's worth noting that I don't see the same issue with shivammathur/php/php. I swapped versions by running:
```
brew uninstall --zap php
rm -rf /opt/homebrew/etc/php/
brew install shivammathur/php/php
```

then testing with:
```
time php -v
PHP 8.3.3 (cli) (built: Feb 13 2024 15:41:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies
php -v  0.02s user 0.01s system 22% cpu 0.170 total
```

As far as I can tell, the only difference between these is that `php` has `imap` enabled, but `shivammathur/php/php` doesn't. I'm using the default config files that come with each of these formulae. This is probably related to #151795, since I only noticed this recently, and that PR added `imap`

@SMillerDev have you got `imap` disabled? If so, I reckon `imap` should be disabled in the default config for this formula

**Comment by SMillerDev** [comment]
> have you got imap disabled? If so, I reckon imap should be disabled in the default config for this formula

`php -i` reports nothing for imap. So I guess not explicitly.

**Comment by Zakini** [comment]
That's gotta be the issue then. I'm not totally sure how to disable `imap` though. There's an `extension=imap` line in `php.ini`, but that's already commented out. I guess it's being loaded by default and needs to be explictly disabled? Either that or there's another config file I haven't looked at. I've checked every file in the output of `php --ini` though, so I'm not sure what other files to check

**Comment by Zakini** [comment]
I've been digging some more. There's actually a separate tap that was created to allow users to install PHP extension that aren't included in homebrew core: https://github.com/kabel/homebrew-php-ext

> These extensions are not a part of Homebrew/core because they are either not popular enough or have known stability problems.
>
> This tap includes one of the sources for the popular imap extension that isn't included in the core homebrew php formulae because of default system performance issues.

Apologies if this is bad Github etiquette, but could @kabel weigh in on this? I imagine you know more about why `imap` wasn't part of homebrew core in the first place

**Comment by kabel** [comment]
> could @kabel weigh in on this? I imagine you know more about why `imap` wasn't part of homebrew core in the first place

This is just a little history playing out again. See https://github.com/Homebrew/homebrew-core/pull/25579. Additional context is that the extension is doing some domain name resolution at start-up and many developers don't have their environments configured to timely resolve their machine's hostname via DNS.

Not much has changed for this php extension since the time it was removed from homebrew in the PR above. In fact, the core php team has approved removing the imap extension from the main distribution in the next version (PHP 8.4). See https://wiki.php.net/rfc/unbundle_imap_pspell_oci8. The general consensus seems that development of the `c-client` (imap client in C; part of the `imap-uw` package) is dead and thus so should the php extension wrapper. The RFC makes mention of a few user-land (PHP) packages that are good candidates for migrating development.

I'd suggest reverting https://github.com/Homebrew/homebrew-core/pull/151795 and letting the extension continue to fade into obscurity.
