### ISSUE TITLE
Some PRs seems to fire the autobump.yml job which can result in the job running twice concurrently

### ISSUE THREAD

**Issue by Porkepix** [Homebrew/homebrew-core#164661]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A (CI issue)
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I saw it at least twice these last two days, especially I was curious that a job having a name such as "Merge pull request #164639 from Homebrew/limit-pull-requests-once" (https://github.com/Homebrew/homebrew-core/actions/runs/8100655678) was actually an autobump.yml workflow.

It turns out the scheduled one fired not long after: https://github.com/Homebrew/homebrew-core/actions/runs/8100783939 (those two are still running as of now).

This is probably caused by https://github.com/Homebrew/homebrew-core/blob/master/.github/workflows/autobump.yml#L4-L8 ; does it make sense to have it trigger on push and not only on schedule? If yes, maybe the name can be improved for runs on push, and something put in place so that this can't run concurrently with the scheduled one (or worse, if I'm reading it correctly, several pushes there could mean the workflow could run 5 or 10 times concurrently I think).

This also risks to trigger more throttling from GitHub livechecks and so on.

### What happened (include all command output)?

N/A (CI issue)

### What did you expect to happen?

N/A (CI issue)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A (CI issue)
```

**Comment by Bo98** [comment]
Yeah push job was for https://github.com/Homebrew/homebrew-core/commit/fb462bd8d0d7caa7065dc0de4595891251cac6e3 but we don't push the fork anymore so doesn't actually have that effect anymore.
