### ISSUE TITLE
Consider enabling little-cms2 by default in ImageMagick, Poppler

### ISSUE THREAD

**Issue by adunning** [Homebrew/homebrew-core#16475]
The colour management support in ImageMagick and Poppler is useful, and only requires little-cms2 to be enabled, but right now they are only enabled with options (hence a local build). This dependency only takes up 1 MB, and many people will have it anyway through Ghostscript; could you consider enabling it by default?

I realize that there may be some reason I am missing for keeping this optional, but I haven't been able to find anything in searching the repository.

**Comment by MikeMcQuaid** [comment]
In the last 30 days <0.3% of users requested `little-cms` support in ImageMagick so we'd rather not force everyone to install an extra dependency for a small proportion of users. Sorry and thanks!

**Comment by adunning** [comment]
Thanks for the response!
