### ISSUE TITLE
libjpeg update breaking php

### ISSUE THREAD

**Issue by apertureless** [Homebrew/homebrew-core#16477]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

1. Ran `brew update && brew upgrade`
2. Ran `brew cleanup -s`
3. php71 is not working anymore

```
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
[1]    30759 abort      php -v
```

<details>
  <summary>Output of /usr/local/opt/jpeg/lib </summary>

```
/usr/local/opt/jpeg/lib
❯ ll
total 480K
-r--r--r-- 1 jjuszczak 203K Aug  7 11:17 libjpeg.9.dylib
-r--r--r-- 1 jjuszczak 270K Jan 17  2016 libjpeg.a
lrwxr-xr-x 1 jjuszczak   15 Jan 17  2016 libjpeg.dylib -> libjpeg.9.dylib

```

</details>

## Try to fix:

Tried to `brew reinstall php71` however it seems it fetched the latest libjpeg but still trying to grab libjpeg.8.dylib

**Comment by ilovezfs** [comment]
```
brew reinstall --build-from-source
```

**Comment by apertureless** [comment]
Thanks. That worked.

**Comment by MikeMcQuaid** [comment]
Thanks @apertureless for the issue. I've opened a PR in https://github.com/Homebrew/brew/pull/3017 to improve the user experience so that `brew reinstall` would have directed you to `brew reinstall --build-from-source`.

**Comment by carlosafonso** [comment]
Can confirm. @ilovezfs ' solution does indeed work.
