### ISSUE TITLE
Latest jpeg.rb broke my PHP installation

### ISSUE THREAD

**Issue by faustbrian** [Homebrew/homebrew-core#16487]
I just ran `brew update` which updated `libjpeg` (https://github.com/Homebrew/homebrew-core/blob/master/Formula/jpeg.rb) and now whenever I want to do anything with PHP I get the following error.

```shell
→ php -v
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
[1]    20749 abort      php -v
```

`brew config`
```php
HOMEBREW_VERSION: 1.3.0
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 05e9086355607e9103030b1f0e3f186e674ce063
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 79c81253162fa0b7d2800dece60e19a078423903
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
bGit: 2.14.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
rRuby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_102, 1.7.0_79
macOS: 10.12.6-x86_64
eXcode: 8.3.1
CLT: 8.3.2.0.1.1492020469
wX11: 2.7.9 => /opt/X11
```

**Comment by dmitry-ivanov** [comment]
+1

**Comment by ilovezfs** [comment]
You'll need to use
```
brew reinstall --build-from-source
```
for the relevant formulae until the php tap has a chance to catch up.

**Comment by dmitry-ivanov** [comment]
Already tried, but there was an error while doing:
> brew reinstall --build-from-source php71

So, I'm just waiting for new php71 tap.

**Comment by masonconkright** [comment]
This solved the issue for me...

`brew reinstall -s php71`
`brew reinstall -s imagemagick`

**Comment by ilovezfs** [comment]
> brew reinstall -s imagemagick

You should be able to just run
```
brew upgrade
```
for that since imagemagick is in core and already got its revision bump.

**Comment by faustbrian** [comment]
That fixed it for me for now `brew reinstall -s imagemagick`

**Comment by ilovezfs** [comment]
```
brew upgrade imagemagick
```
should be sufficient for the `imagemagick` part.

**Comment by smartlara** [comment]
+1

In addition, fixed by `brew reinstall -s php71`

**Comment by ilovezfs** [comment]
The php tap has shipped a new php71 so this should now be fixed if you
```
brew update
brew upgrade
```

Thanks for reporting this @faustbrian!

**Comment by rogeriopradoj** [comment]
For me, here the commands that solved my problem:
```
brew update
brew upgrade php71
```
