### ISSUE TITLE
scipy: _flapack.error in when using eigh

### ISSUE THREAD

**Issue by fahasch** [Homebrew/homebrew-core#164827]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.10-106-g4e65af0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e65af03911d03aabe242978ffa9472d933e29fa
Last commit: 7 hours ago
Core tap HEAD: 5aacf8df4ff2465cded3b61e2be9b2369fc57e98
Core tap last commit: 5 hours ago
Core tap JSON: 02 Mar 12:21 UTC
Core cask tap JSON: 02 Mar 12:21 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false

Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I tried to diagonalize a small matrix using scipy.
So I ran the command

`python3.12 -c "from scipy import linalg;linalg.eigh([[1]])"`

### What happened (include all command output)?

It outputs
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/lib/python3.12/site-packages/scipy/_lib/deprecation.py", line 213, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/scipy/linalg/_decomp.py", line 560, in eigh
    w, v, *other_args, info = drv(a=a1, **drv_args, **lwork_args)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_flapack.error: (liwork>=max(1,10*n)||liwork==-1) failed for 10th keyword liwork: dsyevr:liwork=1
david@lxta444 fabian % python3.12 -c "from scipy import linalg;linalg.eigh([[1]])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/lib/python3.12/site-packages/scipy/_lib/deprecation.py", line 213, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/scipy/linalg/_decomp.py", line 560, in eigh
    w, v, *other_args, info = drv(a=a1, **drv_args, **lwork_args)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_flapack.error: (liwork>=max(1,10*n)||liwork==-1) failed for 10th keyword liwork: dsyevr:liwork=1
```

### What did you expect to happen?

When I install scipy with pip I do get an error.

When running `python3.12 -c "from scipy import linalg;print(linalg.eigh([[1]]))"` I get 
`(array([1.]), array([[1.]]))`
as expected.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install scipy
python3.12 -c "from scipy import linalg;linalg.eigh([[1]])"
```

**Comment by cho-m** [comment]
Looks like an upstream issue: https://github.com/scipy/scipy/issues/19831

v1.13.0 was just released upstream (not yet in brew) which may provide a fix https://github.com/scipy/scipy/releases/tag/v1.13.0 / https://github.com/Homebrew/homebrew-core/pull/167846
