### ISSUE TITLE
pipx.rb does not link register-python-argcomplete to $PATH (needed for pipx shell completions)

### ISSUE THREAD

**Issue by ngie-eign** [Homebrew/homebrew-core#164891]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
% brew config
HOMEBREW_VERSION: 4.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: c6d959218f143cd17b1fc3e0f10f143cbd273528
Last commit: 6 days ago
Core tap JSON: 03 Mar 03:07 UTC
Core cask tap JSON: 03 Mar 03:07 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
```

### Verification

- [ ] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to install the pipx completions for zsh using the upstream/package provided directions.

### What happened (include all command output)?

According to `pipx completions`, I should do the following to enable ZSH completions for pipx:
```
zsh:
    To activate completions for zsh you need to have
    bashcompinit enabled in zsh:

    autoload -U bashcompinit
    bashcompinit

    Afterwards you can enable completion for pipx:

    eval "$(register-python-argcomplete pipx)"
```

When I try and do this in my .zshrc, however, `register-python-argcomplete` can not be found. Example:
```
% eval "$(register-python-argcomplete pipx)"
zsh: command not found: register-python-argcomplete
```
This is happening because `register-python-argcomplete` is not linked to `$PATH`.

### What did you expect to happen?

The completions should be installed in my shell.

### Step-by-step reproduction instructions (by running `brew` commands)

```
- Run `brew install pipx`.
- Follow directions provided by `pipx completions`.
- Run `pipx ensurepath`.
- Open a new shell in Terminal, etc.
- Try using pipx completions. For example, `pipx<TAB>` should complete to the full list of top-level available commands and options.
```

### Workaround

I'm currently working around the issue using the following zsh snippet:
```
if autoload -U bashcompinit; then
        bashcompinit
        old_PATH="$PATH"
        # Completions don't work because `register-python-argcomplete` is not in $PATH.
        PATH="$PATH:$(dirname "$(readlink -f "$(which pipx)")")"
        eval "$(register-python-argcomplete pipx)"
        PATH="$old_PATH"
fi
```

**Comment by cho-m** [comment]
Homebrew doesn't support that way of setting up completions since `pipx` does not own `register-python-argcomplete`. That is from argcomplete, but we will be dropping our corresponding formula `python-argcomplete` as we no longer support distributing it as a formula.

Instead, Homebrew pre-generates the completions and they should automatically be installed in our [default paths for bash, zsh, and fish](https://docs.brew.sh/Shell-Completion),
https://github.com/Homebrew/homebrew-core/blob/a71301ed309e5e0e88a5089cb321f6a37ef31e2d/Formula/p/pipx.rb#L62-L63

**Comment by ngie-eign** [comment]
> Homebrew-core doesn't support that way of setting up completions since `pipx` does not own `register-python-argcomplete`. That is from argcomplete, but we will be dropping our corresponding formula `python-argcomplete` as we no longer support distributing it as a formula.
> 
> Instead, `pipx` formula pre-generates the completions and they should automatically be installed in our [default paths for bash, zsh, and fish](https://docs.brew.sh/Shell-Completion),
> 
> https://github.com/Homebrew/homebrew-core/blob/a71301ed309e5e0e88a5089cb321f6a37ef31e2d/Formula/p/pipx.rb#L62-L63

The homebrew provided completions don’t work. The vanilla ones from upstream do.

**Comment by cho-m** [comment]
Looks like only the Zsh completions don't work as they don't have `#compdef` for autoloading.

Upstream has added it in https://github.com/kislyuk/argcomplete/commit/dd79ddf2e0df4be899ec60cfb96b6c2271f8f10f so it may be possible when `argcomplete` decides to do a release and resource can be updated.

**Comment by cho-m** [comment]
Opened #165571 to rebuild bottles with new `argcomplete`.

After that goes in, you will need to `brew reinstall pipx` and maybe clear any Zsh completion cache.

Works for me locally.
