### ISSUE TITLE
brew services start mysql is error, undefined method `plist_startup' for #<Formula mysql (stable) /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mysql.rb>

### ISSUE THREAD

**Issue by Goodvincent** [Homebrew/homebrew-core#164966]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew services start mysql is error, undefined method `plist_startup' for #<Formula mysql (stable) /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mysql.rb>
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew services start mysql

### What happened (include all command output)?

undefined method `plist_startup' for #<Formula mysql (stable) /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mysql.rb>

### What did you expect to happen?

undefined method `plist_startup' for #<Formula mysql (stable) /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mysql.rb>

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
undefined method `plist_startup' for #<Formula mysql (stable) /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/m/mysql.rb>
```

**Comment by SMillerDev** [comment]
You have a very old MySQL install if this is the case. Upgrading it will make this issue go away.
