### ISSUE TITLE
pass: does not activate zsh-completions

### ISSUE THREAD

**Issue by kousu** [Homebrew/homebrew-core#165245]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
kousu@macbook ~ % brew config
HOMEBREW_VERSION: 4.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7d4c8266210c024b93a450a7d357cec0b46a1bb
Last commit: 2 days ago
Core tap JSON: 06 Mar 02:44 UTC
Core cask tap JSON: 06 Mar 02:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: false
```

```
kousu@macbook ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I wanted to use the `pass` password manager with tab completiton.

### What happened (include all command output)?

I installed `pass` and `zsh-completions`. I followed the instructions from zsh-completions, creating and add this to `~/.zshrc`:

```
kousu@macbook ~ % head .zshrc

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi
```

and starting a new window.

then tried to use `pass [tab]` and got nothing

```
kousu@macbook ~ % pass g
```

Completions are working for other apps; for example:

```
kousu@macbook ~ % adb [tab]
No (started) device specified, completions do not yet work
backup             disable-verity     exec-out           get-state          jdwp               ppp                reboot-bootloader  root               status-window      unroot             
bugreport          disconnect         forward            help               keygen             pull               remount            shell              sync               usb                
connect            emu                get-devpath        install            kill-server        push               restore            sideload           tcpip              version            
devices            enable-verity      get-serialno       install-multiple   logcat             reboot             reverse            start-server       uninstall          wait-for-device    
```

### What did you expect to happen?

pass should show me completions like `init`, `git`, and the list of my passwords. It should look like this:

```
Last login: Wed Mar  6 10:14:49 on ttys004
kousu@macbook ~ % pass g[tab]
generate  -- Generate a new password using pwgen
git       -- Call git on the password store
grep      -- Search inside decrypted password files for matching pattern
google.com   greatwestlifeco.com
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install zsh-completions pass
echo > ~/.zshrc <<EOF
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi
EOF

chmod go-w '$/opt/homebrew/share'
chmod -R go-w '/opt/homebrew/share/zsh'
```

Make a new terminal window or log out/back in

```
# verify completions are loaded
echo $FPATH
adb [tab]
```

**Comment by kousu** [comment]
The completions are installed, they are in

```
% brew ls pass | grep zsh
/opt/homebrew/Cellar/pass/1.7.4/share/zsh/site-functions/_pass
```

but they're not in `$FPATH`.

This fixes the issue for me:

```
sudo ln -s  /opt/homebrew/Cellar/pass/1.7.4/share/zsh/site-functions/_pass /opt/homebrew/share/zsh-completions/ 
```

**Comment by kousu** [comment]
Thanks for the clue! So is my problem in `zsh-completions`? Is this line out of date?

https://github.com/Homebrew/homebrew-core/blob/fd602f0a4288b46db0dfc81e29e59fd148bfa2a6/Formula/z/zsh-completions.rb#L28

Or am I supposed to have this?

```
if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

    autoload -Uz compinit
    compinit
fi


if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

    autoload -Uz compinit
    compinit
fi
```

I guess this was a problem of not reading the docs. :sheep:

**Comment by Bo98** [comment]
`share/zsh/site-functions` is the primary destination while `share/zsh-completions` is specific to the `zsh-completions` formula. The reason I think `zsh-completions` doesn't also install to `share/zsh/site-functions` is because `zsh-completions` contains its own completions that clash with what some upstreams provide so we leave it user choice which should be prioritised: upstream completions or those from `zsh-completions`. Some people (including me) don't use `zsh-competions` at all.

**Comment by kousu** [comment]
Thank you for taking the time to explain. I was misled by the `caveat` in `zsh-completions`. I thought I *had* to install `zsh-completions` to make it work -- the last time I set up completions it was with bash and I had to `brew install bash-completions` to make them work, so I made the same assumption with zsh.
