### ISSUE TITLE
grpc package is missing mock_stream.h header

### ISSUE THREAD

**Issue by misha-codethink** [Homebrew/homebrew-core#165487]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7d4c8266210c024b93a450a7d357cec0b46a1bb
Last commit: 4 days ago
Core tap JSON: 08 Mar 12:29 UTC
Core cask tap JSON: 08 Mar 12:29 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.FdKlpBtQUE/org.xquartz:0
HOMEBREW_EDITOR: e
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

```
% brew doctor               
Your system is ready to brew.
%
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to compile a piece of code that links to `grpc` library, and in particular uses `mock_stream.h` header from that package.

### What happened (include all command output)?

The compilation failed due to the missing header.

### What did you expect to happen?

The compilation succeeded.

This header used to be private for `grpc`, but [in 2019](https://github.com/grpc/grpc/issues/20208) it was promoted to be public. However it still needs configuration option `-DgRPC_BUILD_TESTS` to be installed.

I have checked several Linux distributions: Debian, Ubuntu, Fedora and Alpine all install this header in their packages. OpenSUSE does not, probably due to the same oversight.

The fix should be pretty easy: add `-DgRPC_BUILD_TESTS` to `grpc` formula.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install grpc
echo '#include <grpcpp/test/mock_stream.h>' > a.cpp
g++ -o a a.cpp
```

**Comment by SMillerDev** [comment]
Generally Homebrew builds the upstream default. Why isn't this part of the default configuration?

**Comment by misha-codethink** [comment]
From the issue linked above looks like upstream is not very concerned about builds outside of Bazel ecosystem: they have declared the header public 5 years ago, but didn't do anything to make it easer for the rest of the world to consume it.

**Comment by iMichka** [comment]
Going to close this as this is definitely an upstream issue that we can not solve. I'll comment on the upstream issue though.

**Comment by iMichka** [comment]
Note: if upstream is in favour of shipping the file and a fix is written: we will accept a patch until a new release is cut by upstream.
