### ISSUE TITLE
I really hate that homebrew as the most popular package managing software download your .jws.json every time I install something even the last package installation is 1 minute ago!

### ISSUE THREAD

**Issue by AntiMoron** [Homebrew/homebrew-core#165478]
### What were you trying to do (and why)?

I really hate that homebrew as the most popular package managing software download your .jws.json every time I install something even the last package installation is 1 minute ago!

I mean, why cannot we have the jws.json cached at least 3 days, and provide users with an flag option to force update jws.json.

```bash
brew install xxxx
# downloading your jws.json for the first time, cache it three days

brew install xxx
# within 3days, no download at all.

brew install xxxx 
# after 3 days, we can update the json
```

It's so slay that even `brew doctor` runs `Downloading https://formulae.brew.sh/api/formula.jws.json`, what does the docter have to do with tapping any package...

### What happened (include all command output)?

brew docter -> runs `Downloading https://formulae.brew.sh/api/formula.jws.json`
brew install xxxx -> `Downloading https://formulae.brew.sh/api/formula.jws.json` each call, please dont

I know you have ENV variables to turn off this, I've read this: https://github.com/orgs/Homebrew/discussions/4314 
why we cannot make a better updating strategy.

### What did you expect to happen?

we have the jws.json cached at least 3 days, and provide users with an flag option to force update jws.json.

### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 4.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: d7d4c8266210c024b93a450a7d357cec0b46a1bb
Last commit: 4 days ago
Core tap JSON: 08 Mar 09:03 UTC
Core cask tap JSON: 08 Mar 08:34 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.84.0 => /usr/bin/curl
macOS: 13.0-arm64
CLT: 14.3.1.0.1.1683849156
Xcode: 14.3.1
Rosetta 2: false
```

```
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Settings.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 15.1.

==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################# 100.0%

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  node@16
  openssl@1.1
  youtube-dl

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-cask-drivers
Untap them with `brew untap`.

Warning: Your Xcode (14.3.1) is outdated.
Please update to Xcode 15.1 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
-
-
-
```

**Comment by SMillerDev** [comment]
> I really hate that homebrew as the most popular package managing software download your .jws.json every time I install something even the last package installation is 1 minute ago!

https://docs.brew.sh/Manpage#environment says that the default for `HOMEBREW_API_AUTO_UPDATE_SECS` is ~7 minutes. You might have adjusted that to be under a minute.

> It's so slay that even brew doctor runs Downloading https://formulae.brew.sh/api/formula.jws.json, what does the docter have to do with tapping any package...

`brew doctor` is there to report issues. For that it needs to know the latests state of packages.

> why we cannot make a better updating strategy.

This is the best update strategy people came up with so far, but you're very welcome to make a pull request to improve it.

---

Since none of this has anything to do with brew packages, nor is it a bug I'm closing this.
