### ISSUE TITLE
openssl --universal failed to build on 10.11.2

### ISSUE THREAD

**Issue by guidupuy** [Homebrew/homebrew-core#1656]
Build fails with the following output:
https://gist.github.com/guidupuy/3d32db8f2e1ffb91c31eceafac442979

**Comment by guidupuy** [comment]
Getting the exact same error when installing `v1.0.1t` from `homebrew/versions` (`brew install homebrew/versions/openssl101 --universal`)

**Comment by guidupuy** [comment]
Oh, and I should mention that `brew doctor` yields nothing (`Your system is ready to brew`), and that I've already updated brew (`brew update`) twice.

**Comment by guidupuy** [comment]
Running `brew upgrade` didn't help. Neither did upgrading the XCode CLT with `xcode-select --install`.

**Comment by ilovezfs** [comment]
I cannot reproduce this:
```
🍺  /usr/local/Cellar/openssl/1.0.2h_1: 1,692 files, 17.2M, built in 6 minutes 1 second
iMac-TMP:local joe$ cat /usr/local/Cellar/openssl/1.0.2h_1/
CHANGES               NEWS                  include/              
INSTALL_RECEIPT.json  README                lib/                  
LICENSE               bin/                  share/                
iMac-TMP:local joe$ cat /usr/local/Cellar/openssl/1.0.2h_1/INSTALL_RECEIPT.json 
{"used_options":["--universal"],"unused_options":["--without-test"],"built_as_bottle":false,"poured_from_bottle":false,"time":1464852767,"source_modified_time":1462283203,"HEAD":"ee42f8c3553b815034d85663c3e03f222c15bcc5","stdlib":null,"compiler":"clang","source":{"path":"/usr/local/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb","tap":"homebrew/core","spec":"stable"}}iMac-TMP:local joe$ 
iMac-TMP:local joe$ file `which openssl`
/usr/bin/openssl: Mach-O universal binary with 2 architectures
/usr/bin/openssl (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/bin/openssl (for architecture i386):	Mach-O executable i386
```

```
iMac-TMP:local joe$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee42f8c3553b815034d85663c3e03f222c15bcc5
Last commit: 31 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 63aabbc12e197c27372aa58727ac5826200c5e1f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit skylake
Clang: 7.3 build 703
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92, 1.8.0_77, 1.7.0_80, 1.6.0_65-b14-468
System Ruby: 2.0.0-p648
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.8 => /opt/X11
```

**Comment by guidupuy** [comment]
Hum. Strange. Here's my `brew config` - anything seems fishy to you?
```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4a8fcae3cc29600cb3736e44eae7834d5b6c6feb
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 76532121a0966c01cdca5e1179decd7cde48bc8f
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Clang: 7.3 build 703
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_31
System Ruby: 2.0.0-p645
OS X: 10.11.2-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

**Comment by ilovezfs** [comment]
Yes, that your system is at 10.11.2 but you're saying brew doctor reported `Your system is ready to brew`, which should not be the case since doctor is supposed to complain when you're not on the latest point release of your OS X version. So that needs to be diagnosed, and you should also probably upgrade to 10.11.5.
```
brew gist-logs openssl
brew doctor
cd /usr/local/Library/Taps/homebrew/homebrew/homebrew-core
git status
cd /usr/local
git status
```

**Comment by guidupuy** [comment]
Upgrading OSX right now. Will let you know how it goes. Thanks for helping!

**Comment by guidupuy** [comment]
That did the trick (still compiling, but it did go further than `make` this time, where is was tripping up before)

**Comment by ilovezfs** [comment]
@guidupuy Interesting, so the `openssl` formula is indeed "broken" for 10.11.2 and possibly other point releases, which may be acceptable since we really only "support" the latest point releases, but is worth noting.

Also, was doctor really not saying anything about 10.11.2 being outdated?

**Comment by guidupuy** [comment]
Pretty sure it said nothing about that, no.

**Comment by guidupuy** [comment]
Still waiting for binaries to compile. Will close the issue as soon as I can confirm that everything's building smoothly.

**Comment by guidupuy** [comment]
`/usr/local/Cellar/openssl/1.0.2h_1: 1,691 files, 17.2M, built in 11 minutes 25 seconds`

**Comment by UniqMartin** [comment]
> Also, was doctor really not saying anything about 10.11.2 being outdated?

`brew doctor` has no knowledge of OS X point releases, so there's really nothing it could have complained about. The only thing it knows to complain about is if an unsupported OS X release is used, currently anything that doesn't fall into the 10.9.x..10.11.x range. I don't know the exact reason for why we do not track this, but probably a mix of that OS X usually does a good job of bullying users into the security/bugfix updates and that this rarely creates issues when building stuff. Xcode is a completely different beast, so with it and a few other components we're a bit more diligent.

**Comment by MikeMcQuaid** [comment]
> that this rarely creates issues when building stuff.

Yeh, this is probably why. I think it'd be a good candidate for a `brew doctor` check as there's various other things (e.g. XQuartz) there that give gentle nudges for security reasons.

**Comment by DomT4** [comment]
>  I don't know the exact reason for why we do not track this, but probably a mix of that OS X usually does a good job of bullying users into the security/bugfix updates and that this rarely creates issues when building stuff. 

I've proposed a Doctor check to nudge people to update OS X versions a few times and been glared at for doing so 😄. I don't know how much more effective it would be than OS X's built-in persistent nagging, to be honest, but I'm still not opposed to it.

@guidupuy It may be worth filing an Issue with the snippet of breakage there to the [OpenSSL](https://github.com/openssl/openssl) team to see if they're aware. If it impacts certain OS X versions only that smells like a valid bug.

**Comment by ilovezfs** [comment]
>I've proposed a Doctor check to nudge people to update OS X versions a few times and been glared at for doing so

I just assumed it must exist since it seems like something we would "naturally" nag about in doctor, given that getting people on the latest point releases ensures CI for each OS matches what we expect users to be running.
