### ISSUE TITLE
pg_dump gives different output for postgresql@15 when compared to postgresql@14 and postgresql@16

### ISSUE THREAD

**Issue by woutersmeenk** [Homebrew/homebrew-core#165726]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
postgres@16: https://gist.github.com/woutersmeenk/dee752bffeb1ec01725db6ba600c8035
@14 and @15 did not give logs

brew doctor: 'Your system is ready to brew.'
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

We use `pg_dump` to dump the structure of the database. When using `pg_dump` the output differs per version. On other systems (of colleges) where Postgres 15 is not installed with homebrew no extra comment is dumped.

### What happened (include all command output)?

When running the script below (in the step-by-step instructions) I get this output:
```
Warning: Service `postgresql@14` is not started.
Warning: Service `postgresql@15` is not started.
Warning: Service `postgresql@16` is not started.
==> Successfully started `postgresql@14` (label: homebrew.mxcl.postgresql@14)
pg_dump (PostgreSQL) 14.11 (Homebrew)
Stopping `postgresql@14`... (might take a while)
==> Successfully stopped `postgresql@14` (label: homebrew.mxcl.postgresql@14)
==> Successfully started `postgresql@15` (label: homebrew.mxcl.postgresql@15)
pg_dump (PostgreSQL) 15.6 (Homebrew)
Stopping `postgresql@15`... (might take a while)
==> Successfully stopped `postgresql@15` (label: homebrew.mxcl.postgresql@15)
==> Successfully started `postgresql@16` (label: homebrew.mxcl.postgresql@16)
pg_dump (PostgreSQL) 16.2 (Homebrew)
Stopping `postgresql@16`... (might take a while)
==> Successfully stopped `postgresql@16` (label: homebrew.mxcl.postgresql@16)
--- tmp14.sql   2024-03-11 08:10:40
+++ tmp15.sql   2024-03-11 08:10:44
@@ -2,8 +2,8 @@
 -- PostgreSQL database dump
 --
 
--- Dumped from database version 14.11 (Homebrew)
--- Dumped by pg_dump version 14.11 (Homebrew)
+-- Dumped from database version 15.6 (Homebrew)
+-- Dumped by pg_dump version 15.6 (Homebrew)
 
 SET statement_timeout = 0;
 SET lock_timeout = 0;
@@ -17,6 +17,13 @@
 SET row_security = off;
 
 --
+-- Name: public; Type: SCHEMA; Schema: -; Owner: -
+--
+
+-- *not* creating schema, since initdb creates it
+
+
+--
 -- PostgreSQL database dump complete
 --
 
--- tmp14.sql   2024-03-11 08:10:40
+++ tmp16.sql   2024-03-11 08:10:48
@@ -2,8 +2,8 @@
 -- PostgreSQL database dump
 --
 
--- Dumped from database version 14.11 (Homebrew)
--- Dumped by pg_dump version 14.11 (Homebrew)
+-- Dumped from database version 16.2 (Homebrew)
+-- Dumped by pg_dump version 16.2 (Homebrew)
 
 SET statement_timeout = 0;
 SET lock_timeout = 0;
```

### What did you expect to happen?

I expect the diff between the 15 and 14/16 dump files to only be the version numbers instead of all the extra schema info.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql@14 postgresql@15 postgresql@16

brew services stop postgresql@14
brew services stop postgresql@15
brew services stop postgresql@16

brew services start postgresql@14
sleep 1
/opt/homebrew/Cellar/postgresql@14/14.11_1/bin/pg_dump --version
/opt/homebrew/Cellar/postgresql@14/14.11_1/bin/pg_dump -d postgres -f tmp14.sql
brew services stop postgresql@14

brew services start postgresql@15
sleep 1
/opt/homebrew/Cellar/postgresql@15/15.6_1/bin/pg_dump --version
/opt/homebrew/Cellar/postgresql@15/15.6_1/bin/pg_dump -d postgres -f tmp15.sql
brew services stop postgresql@15

brew services start postgresql@16
sleep 1
/opt/homebrew/Cellar/postgresql@16/16.2_1/bin/pg_dump --version
/opt/homebrew/Cellar/postgresql@16/16.2_1/bin/pg_dump -d postgres -f tmp16.sql
brew services stop postgresql@16

diff -u tmp14.sql tmp15.sql
diff -u tmp14.sql tmp16.sql
```

**Comment by cho-m** [comment]
`postgresql@16` and `postgresql@15` have identical build steps on macOS in Homebrew.

Comparing to another PostgreSQL 15 may not be accurate as Homebrew also runs an `initdb` step to allow `brew services` to work, which probably doesn't occur on those installations.

I think this is probably a difference upstream. The message was added in PostgreSQL 15 (https://github.com/postgres/postgres/commit/a7a7be1f2fa6b9f0f48e69f12256d8f588af729b) which is why you don't see it in PostgreSQL 14. I am guessing there was a change in PostgreSQL 16 that may have hid the message, but haven't had time to check.

**Comment by iMichka** [comment]
Is there something actionable on our side to do here?
Looks like we have an explanation.

The only thing is why it's hidden on PostgreSQL 16: either the print got removed, or `initdb` failed?

**Comment by woutersmeenk** [comment]
> Is there something actionable on our side to do here? Looks like we have an explanation.
> 
> The only thing is why it's hidden on PostgreSQL 16: either the print got removed, or `initdb` failed?

The print is still there in PG 16: https://github.com/postgres/postgres/blob/REL_16_STABLE/src/bin/pg_dump/pg_dump.c#L10317

Also I tried pg_dump 16.2 on the 15.6 database and it seems this also give this same comment. But when using the database from 16 it does not.

**Comment by iMichka** [comment]
Does the database created with postresql 16 have a schema that is already there and was created by initdb?

**Comment by cho-m** [comment]
There doesn't seem to be anything actionable from Homebrew side. Perhaps you can get someone from PostgreSQL side to debug further on reason but for now will close.
