### ISSUE TITLE
Error installing meson-python (MacOSX 10.15.7)

### ISSUE THREAD

**Issue by rogeriod** [Homebrew/homebrew-core#165727]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Last login: Mon Mar 11 07:28:18 on ttys000
rogerio@Rogerios-iMac ~ % brew config
HOMEBREW_VERSION: 4.2.11-103-gcd1f040
ORIGIN: https://github.com/Homebrew/brew
HEAD: cd1f0409493c77e7964cf03a0fb1e93d03a83772
Last commit: 3 days ago
Core tap JSON: 10 Mar 19:33 UTC
Core cask tap JSON: 10 Mar 19:33 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
rogerio@Rogerios-iMac ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

rogerio@Rogerios-iMac ~ %
```

### Verification

- [X] My "`brew doctor` output" says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install meson-python.

### What happened (include all command output)?

Installation fails due "Error: An exception occurred within a child process" (see below). 

### What did you expect to happen?

Package meson-python to install. It is a dependency for openvino/ffmpeg. I had it running on this machine before, but I decided to reinstall the machine from scratch to clean out some old stuff and now I am having difficult reinstalling some components that were installed before.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Last login: Mon Mar 11 07:38:01 on ttys000
rogerio@Rogerios-iMac ~ % python --version
Python 3.12.2
rogerio@Rogerios-iMac ~ % python3 --version
Python 3.12.2
rogerio@Rogerios-iMac ~ % meson --version
1.3.2
rogerio@Rogerios-iMac ~ % brew install meson-python
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from cd1f04094 to ae0ceee74.
Updated 1 tap (homebrew/cask).
==> New Casks
arturia-software-center

You have 1 outdated formula installed.

Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching meson-python
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/90c02007778049214b6c76120bb74ef702eec449/Formula/m
#################################################################################################################### 100.0%
==> Downloading https://files.pythonhosted.org/packages/38/af/b0e6a9eba989870fd26e10889446d1bec2e6d5be0a1bae2dc4dcda9ce199/
Already downloaded: /Users/rogerio/Library/Caches/Homebrew/downloads/02a5747f866df5e01b26c1ac33117077b407fa30a2163ad46620e3f3a26f7833--pyproject-metadata-0.7.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c0/3f/d7af728f075fb08564c5949a9c95e44352e23dee646869fa104a3b2060a3/
Already downloaded: /Users/rogerio/Library/Caches/Homebrew/downloads/c18681289175fb45367956fde79823bf2d98bab623266b25e1d8f5b8b5845bfe--tomli-2.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/a2/3b/276b596824a0820987fdcc7721618453b4f9a8305fe20b611a00ac3f948e/
Already downloaded: /Users/rogerio/Library/Caches/Homebrew/downloads/1709bf19f58d282ce75b45d2bc4b0bf5f64d22c6387f1d2e5ba4686a063085c4--meson_python-0.15.0.tar.gz
Error: An exception occurred within a child process:
  TypeError: Parameter 'python': Expected type T.any(Pathname, String), got type Formulary::FormulaNamespaceAPIe850a65aec9bf3c6062278a00519b2d0dbe0aacf00851741dc120e93d0b3a4be::PythonAT311 with value #<Formula python@3.11 (stab...core/Formula/p/python@3.11.rb>
Caller: /Users/rogerio/Library/Caches/Homebrew/api-source/Homebrew/homebrew-core/90c02007778049214b6c76120bb74ef702eec449/Formula/meson-python.rb:42
Definition: /usr/local/Homebrew/Library/Homebrew/language/python.rb:23
rogerio@Rogerios-iMac ~ %
```

**Comment by SMillerDev** [comment]
> Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.

**Comment by rogeriod** [comment]
Thank you for your kind message. It's reassuring to know that there is a support community around Homebrew.

**Comment by Undefined-User** [comment]
While they hate and reject bug reports from older systems, I think this is a problem caused by an under-tested type check merge, and they will soon find this report again on supported systems and have to fix it .

According to the message in the error, you can run the `git revert 383d774` command in the `/usr/local/Homebrew` path. After resolving the conflict and submitting the commit, you will no longer receive the error message by running `HOMEBREW_NO_INSTALL_FROM_API=1 brew install meson-python`.

**Comment by rogeriod** [comment]
@Undefined-User Thanks for the tip and follow up. After the ticket was closed off the bat, I went for the nuclear option - formatted the drive and reinstalled the OS. After installing brew, the first package I installed was meson-python - it took forever but it installed correctly. That goes to show that this issue was somehow related to brew. Openvino installed correctly (it required by meson-python) and am now installing the remaining packages required for ffmpeg - so far, so good!

**Comment by Undefined-User** [comment]
> @Undefined-User Thanks for the tip and follow up. After the ticket was closed off the bat, I went for the nuclear option - formatted the drive and reinstalled the OS. After installing brew, the first package I installed was meson-python - it took forever but it installed correctly. That goes to show that this issue was somehow related to brew. Openvino installed correctly (it requires meson-python) and am now installing the remaining packages required for ffmpeg - so far, so good!

Thanks for you hard test! I want to know homebrew project is welcome to PRs for fixing bugs on unsupported systems without affecting supported systems? If so, I will try to analyze the cause of the error and submit the fix code.

**Comment by Bo98** [comment]
> I want to know homebrew project is welcome to PRs for fixing bugs on unsupported systems without affecting supported systems?

Yes, unless the fix is ridiculous to maintain (e.g. a massive multi-file patch). In this case, it looks like a bug in the `meson-python` formula itself (`site_packages` should be passed an executable name, e.g. `python` or `python3.11` - not an entire formula object). The change in brew just happened to catch this bug and made it an error and we can't test thousands of formulae for every change as that would take months.
