### ISSUE TITLE
`gnu-getopt` cannot be used as dependency

### ISSUE THREAD

**Issue by LecrisUT** [Homebrew/homebrew-core#165752]
See new formula attempt: https://github.com/Homebrew/homebrew-core/pull/164352

### What were you trying to do (and why)?

Add a `gnu-getopt` dependency for MacOS since it seems that it still does not have an enhanced version

### What happened (include all command output)?

I have tried with:
```ruby
  on_macos do
    depends_on "gnu-getopt"
  end
```
but that results in:
```
* Dependency 'gnu-getopt' is provided by macOS; please replace 'depends_on' with 'uses_from_macos'.
```

Trying the suggested approach was not successful either because:
```ruby
uses_from_macos "gnu-getopt", since: :sonoma
```
uses the MacOS version of getopt when on `sonoma` which still is not compatible.

### What did you expect to happen?

Have a way to include `gnu-getopt` dependency

### Other references
- https://github.com/Homebrew/homebrew-core/pull/109215#issuecomment-1262290563

**Comment by SMillerDev** [comment]
It is something that maintainers should be warned about, so that's why the audit is failing.

**Comment by LecrisUT** [comment]
Sure, that would be good for the review, but then how can we add new formulas that need this dependency since it fails the CI? You've mentioned there could be a whitelist for that, but the only reference I could find is in [`uses_from_macos`](https://github.com/Homebrew/brew/blob/a30f6c48f22ca5f27c16ab6acbf9afcef32f1cab/Library/Homebrew/rubocops/uses_from_macos.rb#L25). All other implementations seem to be before `uses_from_macos` check got implemented

**Comment by Bo98** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/audit_exceptions/provided_by_macos_depends_on_allowlist.json

**Comment by LecrisUT** [comment]
Thanks for the tip, I've tried to add it there. Worth noting that this seems to only affect `brew audit --online --new`? I was looking at `vcs` for equivalent and it's not on the list, but the CI did not seem to be affected by it.

**Comment by Bo98** [comment]
It's a new formula only audit yeah. The allowlist is sort of useless after the initial merge - we should probably replace it with a PR label or something.

**Comment by Bo98** [comment]
Ah right, sorry I misunderstood what that whitelist was for. It's the dependency itself that goes there.

In this case, we can override new formula audits - they're intentionally new formula only audits because we know they're not 100% accurate in all cases. You can revert that change and leave a note on the PR and we can merge it anyway if we see that audit is the only bit failing.

**Comment by LecrisUT** [comment]
Hmm, if that's the case, wouldn't it be worth it to cherry-pick and keep that exception until MacOS provides an extended `getopt` version? 275ad8aca62aaec1b768d416f6ef957cffc703e0 in the #164352 PR

**Comment by Bo98** [comment]
> until MacOS provides an extended `getopt` version

macOS is a BSD-like operating system so it's unlikely it will ever ship GNU-only features. There's a lot of things in the command-line world that are BSD-only or GNU-only and some software only support one or the other.

**Comment by LecrisUT** [comment]
Welp, even more relevant than to keep the audit exception for `gnu-getopt` long-term than
