### ISSUE TITLE
pkg-config --cflags --libs tree-sitter reporting wrong location

### ISSUE THREAD

**Issue by jangid** [Homebrew/homebrew-core#165854]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs tree-sitter                                                 
Error: No logs.
```

```
% brew config                                                                
HOMEBREW_VERSION: 4.2.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 780fbbc65e90fbe09629aba180a1839e9e7dbaf2
Last commit: 17 hours ago
Core tap JSON: 12 Mar 04:50 UTC
Core cask tap JSON: 12 Mar 04:50 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Applications/Emacs.app/Contents/MacOS/bin/emacsclient -qt -a "/Applications/Emacs.app/Contents/MacOS/Emacs -Q -nw"
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

```
% brew doctor                                                                
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to build a package that depends on tree-sitter. It failed to build and then I found that `pkg-config` is reporting wrong location of the library and its headers. Note that `tree-sitter` was updated today when I ran `brew upgrade`. It was working fine before that. I mean the dependent package was building fine; so I assume that the `pkg-config` was giving correct location earlier.

`pkg-config --cflags --libs tree-sitter `

### What happened (include all command output)?

`-I/usr/local/include -L/usr/local/lib -ltree-sitter`

### What did you expect to happen?

`-I/opt/homebrew/Cellar/tree-sitter/0.22.1/include -L/opt/homebrew/Cellar/tree-sitter/0.22.1/lib -ltree-sitter`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`pkg-config --cflags --libs tree-sitter`
```

**Comment by cho-m** [comment]
Looks like upstream Makefile refactor ended up moving `tree-sitter.pc` generation from `make install` to `make [all]`. Since we only provide `PREFIX=` in latter, the `.pc` file is getting default value:

`make install` should run `make all` so can try a single command instead.

**Comment by dr-scsi** [comment]
@cho-m - Thanks for fixing this.  Is it possible to trigger a new release or will it happen automatically?  TIA.

**Comment by cho-m** [comment]
`brew reinstall tree-sitter` should install the fixed bottle.

**Comment by dr-scsi** [comment]
@cho-m - Thanks, did that, and now `pkg-config --libs tree-sitter` returns the correct value 👍
