### ISSUE TITLE
Hercules formula is years, if not decades, out of date

### ISSUE THREAD

**Issue by Rhialto** [Homebrew/homebrew-core#165987]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://github.com/Homebrew/homebrew-core/blob/master/Formula/h/hercules.rb is supplying version 3.13 which has not been in development in a long, long time.

SDL Hercules is in active development, and version 4.7 has just been released: https://github.com/SDL-Hercules-390/hyperion/releases/tag/Release_4.7

General website about SDL Hercules Hyperion (the one in the formula is likewise outdated):
https://sdl-hercules-390.github.io/html/
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

https://github.com/Homebrew/homebrew-core/blob/master/Formula/h/hercules.rb is supplying version 3.13 which has not been in development in a long, long time.

SDL Hercules is in active development, and version 4.7 has just been released: https://github.com/SDL-Hercules-390/hyperion/releases/tag/Release_4.7

General website about SDL Hercules Hyperion (the one in the formula is likewise outdated):
https://sdl-hercules-390.github.io/html/

### What happened (include all command output)?

I got the extremely old and outdated version 3.13

### What did you expect to happen?

I expect the currently developed version of Hercules to be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install hercules
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew

**Comment by Rhialto** [comment]
I think closing a bug report with just an URL and no constructive comment is rather rude. 

I reported this deficiency in homebrew on behalf of a another reader of a Hercules mailing list. I don't think they are in a position to do whatever you seem to want them to do. Similarly, I use a Mac only for work and are not really in a position to maintain stuff here. I already maintain Hercules in pkgsrc: https://github.com/NetBSD/pkgsrc/tree/trunk/emulators/hercules4sdl . You can use that as inspiration for homebrew.

**Comment by SMillerDev** [comment]
> I think closing a bug report with just an URL and no constructive comment is rather rude.

It's not a bug though, it's an update request and Homebrew only allows those as feature requests.

**Comment by Rhialto** [comment]
Where on https://github.com/Homebrew/homebrew-core/issues/new/choose do you see feature requests? Where do I report a feature request to add feature requests?

**Comment by SMillerDev** [comment]
> Where on https://github.com/Homebrew/homebrew-core/issues/new/choose do you see feature requests? 

Exactly, Homebrew only accepts feature request ads pull request. Not as issues.

We also close any issue that nobody is actively working on to prevent them piling up.

**Comment by Rhialto** [comment]
Well, I only tried to do this other user a favour, and to do you a favour, by pointing out that you're packaging the wrong version of Hercules. It doesn't matter to me personally since I use pkgsrc for that. But any inclination I might have had in the past to try to update the packaging myself anyway, or to do any other contribution, has evaporated in the face of the counterproductive policies homebrew apparently follows. If nobody knows that there is interest in an update, since update requests are routinely closed immediately, you will not get updates. And certainly not from me.

\*plonk\*

**Comment by carlocab** [comment]
Thanks for the info, I've opened #166069 to try to update the formula.
