### ISSUE TITLE
Hashcat

### ISSUE THREAD

**Issue by raphaels17** [Homebrew/homebrew-core#16618]
Hi

Ist there a brew for Hashcat utils ? Could never get it to work from the stand alone github project.

I always end up with cap2hccapx 
-bash: cap2hccapx: command not found

Can anyone help ?

All the best

Raph

**Comment by walchko** [comment]
There appears to be something

``` bash
$ brew search hashcat
hashcat
```

**Comment by dunn** [comment]
Not yet, but if you want to add a formula for https://github.com/hashcat/hashcat-utils, that'd be great! Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md and let us know if you have questions.
