### ISSUE TITLE
MPICH not satisfying `depends_on :mpi` for OpenCoarrays

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew-core#16632]
CC: @fxcoudert @jeffhammond

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new  
This may be an issue for homebrew/brew, but under @fxcoudert's direction (https://github.com/Homebrew/homebrew-core/pull/16627#issuecomment-321614604) I'm filing it here.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/e78743a886c98bda2166d4837d952519
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install OpenCoarrays with MPICH on my system, but no OpenMPI

- What happened (include command output)

```
$ brew rm openmpi
Uninstalling /usr/local/Cellar/open-mpi/2.1.1... (694 files, 8.4MB)
$ brew rm opencoarrays mpich
Uninstalling /usr/local/Cellar/opencoarrays/1.9.0... (16 files, 119.9KB)
Uninstalling /usr/local/Cellar/mpich/3.2_3... (885 files, 15MB)
$ brew update
Already up-to-date.
$ brew install mpich
==> Downloading https://homebrew.bintray.com/bottles/mpich-3.2_3.sierra.bottle.tar.gz
Already downloaded: /Users/ibeekman/Library/Caches/Homebrew/mpich-3.2_3.sierra.bottle.tar.gz
==> Pouring mpich-3.2_3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/mpich/3.2_3: 885 files, 14.2MB
$ brew install opencoarrays
==> Installing dependencies for opencoarrays: open-mpi
==> Installing opencoarrays dependency: open-mpi
Error: Cannot install open-mpi because conflicting formulae are installed.
  mpich: because both install mpi__ compiler wrappers

Please `brew unlink mpich` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
$ brew info opencoarrays
opencoarrays: stable 1.9.1 (bottled), HEAD
Open-source coarray Fortran ABI, API, and compiler wrapper
http://opencoarrays.org
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencoarrays.rb
==> Dependencies
Build: cmake ✔
Required: gcc ✔
==> Requirements
Required: fortran ✔, mpi ✔
==> Options
--without-test
	Skip build time tests (not recommended)
--HEAD
	Install HEAD version
```

- What you expected to happen

Install OpenCoarrays (somehow) preferably using MPICH rather than OpenMPI. It could fall back to building from source.

- Step-by-step reproduction instructions (by running `brew install` commands)

See "What happened (include command output)" section.

A user (@jeffhammond) first reported this to us: https://gitter.im/sourceryinstitute/opencoarrays?at=595093f0c101bc4e3a1f3773

**Comment by fxcoudert** [comment]
I understand now what's happening. Homebrew accepts to build OpenCoarrays with MPICH, as you can check by build from source (`brew install -s opencoarrays`).

However, the default `brew install opencoarrays` wants to install prebuilt binaries (a Homebrew _bottle_), and those are built on our servers with the _default_ MPI implementation, which is set system-wide for Homebrew as Open MPI.

I don't think there is an easy way around this, apart from changing our default choice of MPI (and this would not be done lightly).

**Comment by zbeekman** [comment]
Yes exactly...

Do you think I can at least provide users some guidance about this? My
thoughts are either:

   1. At least add some caveat text to help them deal with this situation
   when they encounter it
   2. Add an optional default dependency on MPICH to try to get
   OpenCoarrays bottled against MPICH. Users could then pass `--without-mpich`
   to build linked against OpenMPI. This approach is probably dubious and I
   would guess @MikeMcQaid and others would object to this one.

**Comment by fxcoudert** [comment]
1. We could try help give a clear error message to users, yes.
2. We want to keep all bottles against Open MPI, so people can install multiple bottles without conflict.
3. Another option would be to maintain an MPICH-specific formula in a tap maintained by OpenCoarrays (or your personally). You could even have bottles.

**Comment by zbeekman** [comment]
If I opened a PR for opencoarrays.rb adding a caveats block explaining that
users may need to build from source if they wish to use MPICH, would such a
PR be accepted?

I have thought about maintaining a tap with bottles for OpenCoarrays built
against MPICH and also with MPICH and OpenCoarrays built with GCC, not
clang. It's on my someday list.

**Comment by MikeMcQuaid** [comment]
> I have thought about maintaining a tap with bottles for OpenCoarrays built
> against MPICH and also with MPICH and OpenCoarrays built with GCC, not
> clang. It's on my someday list.

This seems like a better medium-term approach. I'd probably rather avoid caveats in this case because it's how all bottles function.

**Comment by zbeekman** [comment]
true, but this [has prevented users from installing the package](https://gitter.im/sourceryinstitute/opencoarrays?at=595093f0c101bc4e3a1f3773) in the past.

**Comment by ilovezfs** [comment]
Using a requirement's default formula with bottles is standard behavior in Homebrew because we want the bottles to be built – and tested – during CI in the _same_ configuration that users will get them. If you don't want to use the default formula for a requirement, then you need to build locally so that the build products match the configuration you're locally using to satisfy the requirement. We don't offer the same level of support for such a configuration, but the point of a requirement is to make that at least possible.

This isn't specific to the `:mpi` requirement, so I'm closing this, but thanks for reporting @zbeekman.
