### ISSUE TITLE
Bottled vit fails to work on OSX 10.10.5

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#16630]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Installing bottled vit using `brew installed vit` is OK, but when I started running `vit`, it hangs and does not respond with the ncurses interface. 

Only after uninstalling and rebuilding from source does it work:

```
$ brew install vit -s
```

Output from `brew config`:

```
HOMEBREW_VERSION: 1.3.1-24-g67b20d9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 67b20d97d80d8bf550e62a92af4aba025dd806a7
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 37af55a8dcd9bc158d679d97f0d0fb1effb79ab2
Core tap last commit: 32 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
GCC-4.2: build 5666
Clang: 6.1 build 602
Git: 2.14.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.2.1/bin/ruby
Java: 1.8.0_131, 1.8.0_72, 1.7.0_40, 1.6.0_65-b14-466.1, 1.6.0_51-b11-457
macOS: 10.10.5-x86_64
Xcode: 6.4
CLT: 7.2.0.0.1.1447826929
X11: 2.7.9 => /opt/X11
```

**Comment by dunn** [comment]
Is there anything in the system log that might point at the problem?

**Comment by hanxue** [comment]
I have reinstalled vit from bottle, and it is now working fine. 

```
$ brew install vit
Updating Homebrew...
^C==> Downloading https://homebrew.bintray.com/bottles/vit-1.2_1.yosemite.bottle.t
Already downloaded: /Users/hanxue/Library/Caches/Homebrew/vit-1.2_1.yosemite.bottle.tar.gz
==> Pouring vit-1.2_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/vit/1.2_1: 17 files, 329.9KB
$ vit
```

No idea what is causing the difference. Let's close for now.
