### ISSUE TITLE
Sandboxing prevents formulae from calling git/ssh

### ISSUE THREAD

**Issue by buttafoo** [Homebrew/homebrew-core#16643]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  Error: No logs.

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
% brew config
HOMEBREW_VERSION: 1.3.1-dirty
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 272c13ea141ce6940183a4d64d85ba47dcac76e7
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_91
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: N/A
X11: N/A

% brew doctor
Warning: Some installed formula are missing dependencies.

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
  My formula does a: git ls-remote --tags git@git.mycompany:myorg/myrepo.git
  Thanks to the new sandboxing (sandbox-exec), this fails shortly after it makes the ssh connection to our internal github. I can't seem to work around it other than to run: brew install FORMULA --no-sandbox. 

- What happened (include command output)
I boiled it down by printing the sandbox profile and calling sandbox-exec with it:

% env GIT_SSH_COMMAND="ssh -vvv" sandbox-exec -f ./sandbox.sb git ls-remote --tags git@github.mycompany.com:myorg/myrepo.git
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/me/.ssh/config
debug1: /Users/me/.ssh/config line 209: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 20: Applying options for *
debug1: /etc/ssh/ssh_config line 22: Deprecated option "useroaming"
debug1: /etc/ssh/ssh_config line 102: Applying options for *
debug1: /etc/ssh/ssh_config line 105: Applying options for *
debug1: /etc/ssh/ssh_config line 108: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/tmp/ssh-git@github.mycompany.com:22" does not exist
debug2: resolving "github.mycompany.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to github.mycompany.com [IP] port 22.
debug1: Connection established.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

% cat sandbox.sb
(version 1)
(debug deny) ; log all denied operations to /var/log/system.log
(debug allow)
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/private/var/tmp"))
(allow file-write* (regex #"^/private/var/folders/[^/]+/[^/]+/[C,T]/"))
(allow file-write* (subpath "/private/tmp"))
(allow file-write* (subpath "/Users/me/Library/Caches/Homebrew"))
(allow file-write* (subpath "/Users/me/Library/Logs/Homebrew/sprox"))
(allow file-write* (subpath "/Users/me/Library/Developer"))
(allow file-write* (subpath "/usr/local/Cellar/sprox"))
(allow file-write* (subpath "/usr/local/etc"))
(allow file-write* (subpath "/usr/local/var"))
(allow file-write*
    (literal "/dev/ptmx")
    (literal "/dev/dtracehelper")
    (literal "/dev/null")
    (literal "/dev/random")
    (literal "/dev/zero")
    (regex #"^/dev/fd/[0-9]+$")
    (regex #"^/dev/ttys?[0-9]*$")
    )
(deny file-write*) ; deny non-whitelist file write operations
(allow process-exec
    (literal "/bin/ps")
    (with no-sandbox)
    ) ; allow certain processes running without sandbox
(allow default) ; allow everything else

- What you expected to happen
I expected it to make the connection and list my tags. I've been trying to figure out what exactly is being denied, but I can't seem to do so. The syslogging is not working. Adding /usr/bin/ssh to the process-exec list works

- Step-by-step reproduction instructions (by running `brew install` commands)
Run sandbox-exec above

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by MikeMcQuaid** [comment]
> Step-by-step reproduction instructions (by running brew install commands)
> Run sandbox-exec above

Can you provide an example formula that produces this issue by doing an `ls-remote` on github.com?

**Comment by fivetonsflax** [comment]
This is still a live issue.

**Comment by MikeMcQuaid** [comment]
> fakey.txt

This works on my machine.
