### ISSUE TITLE
'brew install cairo --with-x11' doesn't play nicely with pkg-config

### ISSUE THREAD

**Issue by kevinushey** [Homebrew/homebrew-core#16646]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

---

On my machine, Installing cairo with `--with-x11` seems to produce a Cairo installation that doesn't play well with `pkg-config`:

```
brew uninstall --ignore-dependencies cairo
brew install cairo --with-x11
pkg-config cairo --cflags
```

This prints, for me:

```
$ pkg-config cairo --cflags
Package xcb-shm was not found in the pkg-config search path.
Perhaps you should add the directory containing `xcb-shm.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xcb-shm', required by 'cairo', not found
```

Also confirming this is Homebrew's `pkg-config` binary:

```
$ which pkg-config | xargs greadlink -f
/usr/local/Cellar/pkg-config/0.29.2/bin/pkg-config
```

Note that plain bottle installs, as well as `brew install cairo --HEAD`, work fine for me here. See details below for `brew config` output.

https://gist.github.com/kevinushey/c57b06de5c6234325acd1c549bfdba72

<details>
$ brew config
HOMEBREW_VERSION: 1.3.1-24-g67b20d9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 67b20d97d80d8bf550e62a92af4aba025dd806a7
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d1555ecb8abe99a19ffbff9ca447b0ccc01ede92
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.14.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.1_1/bin/ruby
Java: 1.8.0_121, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
</details>

**Comment by kevinushey** [comment]
The following does work so perhaps this is some kind of local configuration issue?

```
$ PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig pkg-config cairo --cflags
-I/opt/X11/include/cairo -I/opt/X11/include/pixman-1 -I/opt/X11/include -I/opt/X11/include/freetype2 -I/opt/X11/include/libpng16 -I/opt/X11/include
```

**Comment by fxcoudert** [comment]
I think it is expected that, if you install software relying on X11, you will need to set your `PKG_CONFIG_PATH` variable to account for that. Homebrew will do it itself for all formulas where you specify an X11 option, but I do not think we should tamper with the user's environment for builds outside of Homebrew.

**Comment by kevinushey** [comment]
Got it, sounds reasonable to me. Thanks for the clarification!
