### ISSUE TITLE
octave --gui no longer opens the octave gui

### ISSUE THREAD

**Issue by kencu** [Homebrew/homebrew-core#166543]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`
% brew config
HOMEBREW_VERSION: 4.2.13-32-g8e67ee2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8e67ee26d7736ab86165c92e728eddb260422802
Last commit: 8 hours ago
Core tap HEAD: dabd78df5d3292ac65507594f7199a4e4da36294
Core tap last commit: 8 weeks ago
Core tap JSON: 19 Mar 00:24 UTC
Core cask tap JSON: 19 Mar 00:24 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
`

`
% brew doctor
Your system is ready to brew.
`
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

run octave with the gui

### What happened (include all command output)?

% octave --gui
octave: GUI features missing or disabled in this build

### What did you expect to happen?

octave gui would open	

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% octave --gui
octave: GUI features missing or disabled in this build
```

**Comment by carlocab** [comment]
I think this is fixed now; if that's not the case we can reopen this.
