### ISSUE TITLE
Issue with running mpdscribble on 10.12: "dyld: Library not loaded"

### ISSUE THREAD

**Issue by 676339784** [Homebrew/homebrew-core#16651]
`brew config`: https://gist.github.com/676339784/cf5c598f20d09dfcfa3422d9d35b5ee6
`brew doctor`: https://gist.github.com/676339784/ab75908b861545485e1e9b55f05fd406

No `brew gist-logs` available.

I was trying to run `mpdscribble` but I get this output: https://gist.github.com/676339784/9a9a4d8ff08903235942fc0a0b25590c

Typically it'd just run without issue. I've tried reinstalling mpd, libmpdnotify, and mpdscribble but I get the same error nevertheless.

**Comment by JCount** [comment]
@676339784 This should have been fixed by #16652.

Running `brew update && brew upgrade mpdscribble` should fix your issue now.
