### ISSUE TITLE
Unable to install graphviz dependency for root formulae

### ISSUE THREAD

**Issue by Kavish1294** [Homebrew/homebrew-core#166635]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
make[8]: Nothing to be done for `install-exec-am'.
make[8]: Nothing to be done for `install-data-am'.
make[8]: Nothing to be done for `install-exec-am'.
make[8]: Nothing to be done for `install-data-am'.
make[7]: Nothing to be done for `install-exec-am'.
 mkdir -p '/private/tmp/graphviz-20240319-62707-33md2n/macosx/build/Destdir/Users/imam2/local/Cellar/graphviz/10.0.1/share/doc/graphviz'
 mkdir -p '/private/tmp/graphviz-20240319-62707-33md2n/macosx/build/Destdir/Users/imam2/local/Cellar/graphviz/10.0.1/share/man/man7'
 mkdir -p '/private/tmp/graphviz-20240319-62707-33md2n/macosx/build/Destdir/Users/imam2/local/Cellar/graphviz/10.0.1/include/graphviz'
 /usr/bin/install -c -m 644 AUTHORS COPYING CHANGELOG.md NEWS cpl1.0.txt '/private/tmp/graphviz-20240319-62707-33md2n/macosx/build/Destdir/Users/imam2/local/Cellar/graphviz/10.0.1/share/doc/graphviz'
 /usr/bin/install -c -m 644 ./graphviz_version.h '/private/tmp/graphviz-20240319-62707-33md2n/macosx/build/Destdir/Users/imam2/local/Cellar/graphviz/10.0.1/include/graphviz'
 /usr/bin/install -c -m 644 graphviz.7 '/private/tmp/graphviz-20240319-62707-33md2n/macosx/build/Destdir/Users/imam2/local/Cellar/graphviz/10.0.1/share/man/man7'
find ../.. -name "*.la" -delete
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to install the formulae called `root`. As part of installation, it requires installation of `graphviz` dependency but it gives the error output when brew runs the make install.

### What happened (include all command output)?

I used `brew install root`, when it reached to install the `graphviz` dependency, it gave the error. I tried `brew upgrade graphviz` separately, but it also gave the same error. 

### What did you expect to happen?

I'm not sure but I expect that it cannot find the `*.la` file and delete it? 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I used `brew install root`, when it reached to install the `graphviz` dependency, it gave the error. I tried `brew upgrade graphviz` separately, but it also gave the same error.
```

**Comment by iMichka** [comment]
Hi. It looks like you are compiling from source? We do not really give support for this case.

Can you give us your `brew config` output just in case we have a quick idea what is going on?

**Comment by Kavish1294** [comment]
As I understand, homebrew provides the binary executable of `root`, which is the formulae I'm trying to install.

Here is my brew config output: 

```
HOMEBREW_VERSION: 4.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: bb753a6c48575ae018d7ad925d7762d59647fff7
Last commit: 3 days ago
Core tap JSON: 19 Mar 22:09 UTC
Core cask tap JSON: 19 Mar 22:09 UTC
HOMEBREW_PREFIX: /Users/imam2/local
HOMEBREW_REPOSITORY: /Users/imam2/local/homebrew
HOMEBREW_CELLAR: /Users/imam2/local/Cellar
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.zieCrBkDYF/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.1.4 => /Users/imam2/local/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 13.6.4-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: false
```

**Comment by cho-m** [comment]
```
HOMEBREW_PREFIX: /Users/imam2/local
```
Homebrew only will guarantee bottles (binaries) and support when you use the default prefix. Building from source is not supported by us and will be up to you to figure out reason.

There should have been a message telling you this 
* https://github.com/Homebrew/brew/blob/master/Library/Homebrew/diagnostic.rb#L825-L829
* https://github.com/Homebrew/brew/blob/master/Library/Homebrew/diagnostic.rb#L118-L126

> Your Homebrew's prefix is not /opt/homebrew.
>
> Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
> Consider uninstalling Homebrew and reinstalling into the default prefix.
> It is expected behaviour that some formulae will fail to build in this unsupported configuration.
> It is expected behaviour that Homebrew will be buggy and slow.
> **Do not create any issues about this on Homebrew's GitHub repositories.**
> **Do not create any issues even if you think this message is unrelated.**
> **Any opened issues will be immediately closed without response.**
> Do not ask for help from Homebrew or its maintainers on social media.
> You may ask for help in Homebrew's discussions but are unlikely to receive a response.
> Try to figure out the problem yourself and submit a fix as a pull request.
> We will review it but may or may not accept it.


As detailed in message, this is not a valid issue for homebrew/core.

**Comment by Kavish1294** [comment]
After reinstalling brew correctly, it seems to have resolved the issue. My apologies for any inconvenience.
