### ISSUE TITLE
azure-cli

### ISSUE THREAD

**Issue by lfaoro** [Homebrew/homebrew-core#16678]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb 

is super outdated, do we really want to dissuade users that they have a not well working azure-cli or shall we remove the formula?

**Comment by ahmetb** [comment]
I think Azure's official installation method is to use `npm`. Maybe this package belongs to [Casks](https://github.com/caskroom/homebrew-cask) and not homebrew-core.

**Comment by ilovezfs** [comment]
Feel free to open a PR updating it to 0.10.15
