### ISSUE TITLE
ffmpeg fails to build on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by maki-chan** [Homebrew/homebrew-core#16686]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

To help us debug your issue please explain:
I was trying to run `brew reinstall ffmpeg` which seems to be needed every time a library like x264 is updated due to my custom install flags for ffmpeg via brew. Every time I run this command, the following output happens:

```
==> Reinstalling ffmpeg --with-chromaprint --with-fdk-aac --with-libass --with-libsoxr --with-libssh --with-tesseract --
==> Downloading https://ffmpeg.org/releases/ffmpeg-3.3.3.tar.bz2
Already downloaded: /Users/armbrust/Library/Caches/Homebrew/ffmpeg-3.3.3.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/3.3.3 --enable-shared --enable-pthreads --enable-gpl --enable-version3
Last 15 lines from /Users/armbrust/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-openssl
--enable-lzma
--enable-libopenjpeg
--disable-decoder=jpeg2000
--extra-cflags=-I/usr/local/Cellar/openjpeg/2.2.0/include/openjpeg-2.2
--enable-nonfree
--enable-vda

ERROR: libopenjpeg not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

Link to output of `brew gist-logs ffmpeg`: https://gist.github.com/maki-chan/fd5e39d1d622e0da9d2cc315b2251d71

Instead of the error, I expected the `ffmpeg` formula to recompile without errors as it did on 2017-08-04, exactly one week ago.

The exact install command for a new installation would be `brew install ffmpeg --with-chromaprint --with-fdk-aac --with-libass --with-libsoxr --with-libssh --with-tesseract --with-libvidstab --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-rtmpdump --with-rubberband --with-schroedinger --with-sdl2 --with-snappy --with-tools --with-webp --with-x265 --with-xz --with-zeromq --with-zimg --with-fontconfig --with-freetype --with-frei0r --with-game-music-emu --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-libvorbis --with-libvpx --with-opus --with-speex --with-theora --with-two-lame --with-wavpack`

**Comment by maki-chan** [comment]
It does work without the `--with-openjpeg` flag as was expected according to the error message. Could this be a problem because of the recent update of the openjpeg formula to 2.2.0?

**Comment by ilovezfs** [comment]
@maki-chan yes. Unfortunately https://github.com/FFmpeg/FFmpeg/commit/078322f33ced4b2db6ac3e5002f98233d6fbf643 hasn't made its way into the released version of ffmpeg yet.

**Comment by ilovezfs** [comment]
@maki-chan this should be fixed now if you `brew update` and try again.
