### ISSUE TITLE
depends_on specific version

### ISSUE THREAD

**Issue by InTheCloudDan** [Homebrew/homebrew-core#16681]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I'm working on a formula but the current version of it requires bazel 0.4.5. As a hacky workaround I pulled the specific commit of bazel to get it installed but thought there has to be a better way to do it before opening a PR:
https://github.com/InTheCloudDan/homebrew-core/blob/istio-new/Formula/istio.rb#L8

I looked through the documentation but didn't find anything covering this type of specific issue.

**Comment by MikeMcQuaid** [comment]
> I looked through the documentation but didn't find anything covering this type of specific issue.

This should cover it: https://docs.brew.sh/Versions.html.

We won't support a new formula here that requires an old version of Bazel. We may consider accepting a `bazel@0.4` formula if it has explained use-cases (e.g. broken backwards compatibility in newer versions) and is still supported by the upstream project. If you need an old version please consider [creating your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) instead. Thanks!
