### ISSUE TITLE
openssl is listening for network connections while being installed

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/homebrew-core#16696]
Right now I am doing a clean install of all my brew/cask packages in a custom brew installation directory (~/homebrew), so I ran `brew bundle --global`. While it's running I got this window (instead of python, it was saying openssl):

![image](https://user-images.githubusercontent.com/159209/29234154-eb67e902-7ea9-11e7-96a8-5039ed4dc60e.png)

My `ps` output shows this:

```
$ ps aux | grep openssl
ahmetb           34481   1.9  0.1  2461896  11104 s000  SN+   3:27PM   0:00.47 perl ./util/process_docs.pl --destdir=/Users/ahmetb/homebrew/Cellar/openssl@1.1/1.1.0f/share/doc/openssl/html --type=html
ahmetb           34715   0.0  0.0  2442020    776 s001  U+    3:28PM   0:00.00 grep --color openssl
ahmetb           32279   0.0  0.0  2460580   3692 s000  SN+   3:27PM   0:00.10 /Library/Developer/CommandLineTools/usr/bin/make install MANDIR=/Users/ahmetb/homebrew/Cellar/openssl@1.1/1.1.0f/share/man MANSUFFIX=ssl
ahmetb           13920   0.0  0.1  2475604  24492 s000  SN+   3:22PM   0:00.56 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /Users/ahmetb/homebrew/Library/Homebrew -- /Users/ahmetb/homebrew/Library/Homebrew/build.rb /Users/ahmetb/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl@1.1.rb
```

What could be the reason `openssl` is listening on a port which would trigger this pop-up?

**Comment by DomT4** [comment]
`openssl@1.1`'s bottle isn't `cellar :any` so given your custom prefix I suspect you'll be building it from source, and Homebrew for obvious enough reasons runs `make test` by default, and the tests use various ports for various tests.

**Comment by ilovezfs** [comment]
`--without-test` if it bothers you but I'd not recommend doing that

**Comment by ahmetb** [comment]
Hmm I can't seem to find that argument on openssl:

    $ brew install openssl --without-tests
    ...
    Warning: openssl: this formula has no --without-tests option so it will be ignored!

**Comment by DomT4** [comment]
`without-test`, not `without-tests`.
