### ISSUE TITLE
Cannot install php71 on Mac OS 10.13

### ISSUE THREAD

**Issue by sbahr001** [Homebrew/homebrew-core#16700]
➜  ~ brew install php71
==> Installing php71 from homebrew/php
==> Downloading https://php.net/get/php-7.1.8.tar.bz2/from/this/mirror
Already downloaded: /Users/sean/Library/Caches/Homebrew/php71-7.1.8
==> ./configure --prefix=/usr/local/Cellar/php71/7.1.8_20 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --wit
^[[C==> make
Last 15 lines from /Users/sean/Library/Logs/Homebrew/php71/02.make:
      _php_mail in mail.o
      _php_mail_log_to_syslog in mail.o
      _zif_syslog in syslog.o
      _php_log_err_with_severity in main.o
      _vzlog in zlog.o
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
make: *** Waiting for unfinished jobs....
make: *** [sapi/cli/php] Error 1
make: *** [sapi/fpm/php-fpm] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Add php71-zmq formula https://github.com/Homebrew/homebrew-php/pull/4345
php71-protobuf (new formula) https://github.com/Homebrew/homebrew-php/pull/4339
Cannot install php71-redis https://github.com/Homebrew/homebrew-php/issues/4061
php71-stemmer https://github.com/Homebrew/homebrew-php/pull/3630
php71 does not work with httpd https://github.com/Homebrew/homebrew-php/issues/3960
php71-libsodium fails to install on macOS Sierra https://github.com/Homebrew/homebrew-php/issues/4166
PHP 7.1 installation  brew install php71 --with-httpd24 fails https://github.com/Homebrew/homebrew-php/issues/4192

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by BrianGilbert** [comment]
this problem is gone with the latest beta of xcode..

**Comment by Chienle** [comment]
Hi @BrianGilbert , do you have any link about this issue?
