### ISSUE TITLE
Issue updating NPM

### ISSUE THREAD

**Issue by lewiswolf** [Homebrew/homebrew-core#167223]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92a4311868322188478d7a90511ec0e8e6b0d7df
Last commit: 2 days ago
Core tap JSON: 26 Mar 15:39 UTC
Core cask tap JSON: 26 Mar 15:39 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Wr1GiOh925/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 15.0.0 build 1500
Git: 2.44.0 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-platformdirs
  python-distlib
  python-filelock

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/liblo.7.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python-distlib
  python-filelock

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/node_modules/bin/npm
  /usr/local/lib/node_modules/bin/npx

$ brew cleanup
Error: Permission denied @ apply2files - /usr/local/lib/node_modules/bin/npm
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am having trouble with updating npm to 10.5.0, as mine is stuck at 10.3.0

I originally reported the issue here => https://github.com/npm/cli/issues/7278

I am also having trouble with `npm link` - this showed up in my `brew doctor`, and I was unable to fix the issue with `brew cleanup` so I deleted the symlink manually.

### What happened (include all command output)?

```
$ brew reinstall node
$ npm -v  
10.3.0
$ sudo npm i -g npm@latest
$ npm -v  
10.3.0 
```

### What did you expect to happen?

```
$ brew reinstall node
$ npm -v  
10.3.0
$ sudo npm i -g npm@latest
$ npm -v  
10.5.0 
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
see above
```

**Comment by ZhongRuoyu** [comment]
What's the output of `which -a npm` and `brew info node`?

**Comment by lewiswolf** [comment]
```bash
$ which -a npm
/usr/local/bin/npm

$ brew info node
==> node: stable 21.7.1 (bottled), HEAD
Platform built on V8 to build network applications
https://nodejs.org/
/usr/local/Cellar/node/21.7.1 (2,131 files, 65.8MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-03-26 at 15:48:09
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/node.rb
License: MIT
==> Dependencies
Build: pkg-config ✘, python@3.12 ✔
Required: brotli ✔, c-ares ✔, icu4c ✔, libnghttp2 ✔, libuv ✔, openssl@3 ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 226,726 (30 days), 622,985 (90 days), 2,487,841 (365 days)
install-on-request: 199,380 (30 days), 545,617 (90 days), 2,180,714 (365 days)
build-error: 437 (30 days)
```

**Comment by ZhongRuoyu** [comment]
That's weird, because the latest `node` is already on NPM 10.5.0:

```console
$ brew info node
==> node: stable 21.7.1 (bottled), HEAD
Platform built on V8 to build network applications
https://nodejs.org/
/usr/local/Cellar/node/21.7.1 (2,133 files, 65.8MB) *
  Poured from bottle on 2024-03-10 at 09:56:12
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/n/node.rb
License: MIT
==> Dependencies
Build: pkg-config ✔, python@3.12 ✔
Required: brotli ✔, c-ares ✔, icu4c ✔, libnghttp2 ✔, libuv ✔, openssl@3 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 224,762 (30 days), 622,806 (90 days), 2,487,977 (365 days)
install-on-request: 197,686 (30 days), 545,482 (90 days), 2,180,795 (365 days)
build-error: 440 (30 days)
$ /usr/local/bin/npm --version
10.5.0
```

https://github.com/Homebrew/homebrew-core/blob/6a4688b2094893bd3c96d72a64fee82a46eb89e1/Formula/n/node.rb#L51-L54

However, your `brew doctor` output looks suspicious:

```
Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/node_modules/bin/npm
  /usr/local/lib/node_modules/bin/npx
```

Can you try `sudo rm` the broken symlinks and then `brew reinstall node`? I suspect it's because your `sudo node` invocation has somehow messed up the node modules; I believe you should not need to use `sudo` with `node` (even for global installation with `-g`).

**Comment by lewiswolf** [comment]
Doing `sudo rm` did fix the message in `brew doctor`, but `brew reinstall node` did not solve the issue. I am still on 10.3.0 for some reason.

```
$realpath /usr/local/bin/npm
/usr/local/lib/node_modules/npm/bin/npm-cli.js
```

**Comment by cho-m** [comment]
This definitely looks like a user-specific issue due to running
```
$ sudo npm i -g npm@latest
```

You've probably overwritten `node` formula's files with `root`-owned files making them unable to be modified by `brew`. This is not only the `npm` command, but the underlying JavaScript files.

You'll need to manually clean up whatever files you've modified either by deleting them or by doing a `chown` to fix up permissions.

**Comment by lewiswolf** [comment]
I just basically did `rm -rf /usr/local/lib/node_modules` and then `brew reinstall node` and it fixed it. Will no longer do `npm i -g npm@latest` either. :)

Thanks!
