### ISSUE TITLE
Issue installing dependencies

### ISSUE THREAD

**Issue by natonamco** [Homebrew/homebrew-core#16726]
brew install autoconf automake libtool boost miniupnpc openssl pkg-config protobuf qt

Warning: autoconf-2.69 already installed
Warning: automake-1.15 already installed
Warning: libtool-2.4.6 already installed
Warning: boost-1.60.0_2 already installed
Warning: miniupnpc-1.9.20151008 already installed
Warning: openssl-1.0.2h already installed
Warning: pkg-config-0.29.1 already installed
Warning: protobuf-2.6.1 already installed
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Downloading https://download.qt.io/official_releases/qt/4.8/4.8.7/qt-everywh
Already downloaded: /Library/Caches/Homebrew/qt-4.8.7.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/480b7142c4e2a
Already downloaded: /Library/Caches/Homebrew/qt--patch-c8a0fa819c8012a7cb70e902abb7133fc05235881ce230235d93719c47650c4e.patch
==> Patching
==> Applying el-capitan.patch
patching file src/gui/painting/qpaintengine_mac.cpp
==> ./configure -prefix /usr/local/Cellar/qt/4.8.7_2 -release -opensource -confi
==> make
Last 15 lines from /Users/Baredes/Library/Logs/Homebrew/qt/02.make:
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_abstractviewinspector.o .moc/release-shared/moc_abstractviewinspector.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_qdeclarativeinspectorplugin.o .moc/release-shared/moc_qdeclarativeinspectorplugin.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_qdeclarativeinspectorprotocol.o .moc/release-shared/moc_qdeclarativeinspectorprotocol.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_qdeclarativeviewinspector.o .moc/release-shared/moc_qdeclarativeviewinspector.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_qdeclarativeviewinspector_p.o .moc/release-shared/moc_qdeclarativeviewinspector_p.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_abstractliveedittool.o .moc/release-shared/moc_abstractliveedittool.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_liveselectiontool.o .moc/release-shared/moc_liveselectiontool.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_boundingrecthighlighter.o .moc/release-shared/moc_boundingrecthighlighter.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_zoomtool.o .moc/release-shared/moc_zoomtool.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_colorpickertool.o .moc/release-shared/moc_colorpickertool.cpp
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -I/usr/local/opt/openssl/include -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_SHARED -I../../../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../../../lib/QtCore.framework/Versions/4/Headers -I../../../../include/QtCore -I../../../../lib/QtGui.framework/Versions/4/Headers -I../../../../include/QtGui -I../../../../lib/QtDeclarative.framework/Versions/4/Headers -I../../../../include/QtDeclarative -I../../../../include -I.moc/release-shared -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/moc_abstracttool.o .moc/release-shared/moc_abstracttool.cpp
rm -f libqmldbg_inspector.dylib
clang++ -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64 -single_module -dynamiclib -o libqmldbg_inspector.dylib .obj/release-shared/abstractviewinspector.o .obj/release-shared/qdeclarativeinspectorplugin.o .obj/release-shared/qdeclarativeviewinspector.o .obj/release-shared/abstractliveedittool.o .obj/release-shared/liveselectiontool.o .obj/release-shared/livelayeritem.o .obj/release-shared/livesingleselectionmanipulator.o .obj/release-shared/liverubberbandselectionmanipulator.o .obj/release-shared/liveselectionrectangle.o .obj/release-shared/liveselectionindicator.o .obj/release-shared/boundingrecthighlighter.o .obj/release-shared/subcomponentmasklayeritem.o .obj/release-shared/zoomtool.o .obj/release-shared/colorpickertool.o .obj/release-shared/abstracttool.o .obj/release-shared/moc_abstractviewinspector.o .obj/release-shared/moc_qdeclarativeinspectorplugin.o .obj/release-shared/moc_qdeclarativeinspectorprotocol.o .obj/release-shared/moc_qdeclarativeviewinspector.o .obj/release-shared/moc_qdeclarativeviewinspector_p.o .obj/release-shared/moc_abstractliveedittool.o .obj/release-shared/moc_liveselectiontool.o .obj/release-shared/moc_boundingrecthighlighter.o .obj/release-shared/moc_zoomtool.o .obj/release-shared/moc_colorpickertool.o .obj/release-shared/moc_abstracttool.o  -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -L/usr/local/opt/openssl/lib -L/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -framework QtDeclarative -L/usr/local/opt/openssl/lib -L/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -F/private/tmp/qt-20170812-29936-omg173/qt-everywhere-opensource-src-4.8.7/lib -framework QtScript -framework QtCore -framework QtSvg -framework QtGui -framework QtSql -framework QtXmlPatterns -framework QtNetwork  
mv -f libqmldbg_inspector.dylib ../../../../plugins/qmltooling/
make: *** [sub-plugins-make_default-ordered] Error 2

**Comment by DomT4** [comment]
Your Homebrew is ancient. Start with:
```bash
cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update
```

**Comment by MikeMcQuaid** [comment]
@natonamco We tell you to fill in the formula template so always do so, please.

**Comment by natonamco** [comment]
@MikeMcQuaid sorry for that. Thank you! @DomT4
