### ISSUE TITLE
7zz offered in sevenzip echoes entered passwords

### ISSUE THREAD

**Issue by dennisschulz2** [Homebrew/homebrew-core#167291]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config 
HOMEBREW_VERSION: 4.2.15-22-ge698c29
ORIGIN: https://github.com/Homebrew/brew
HEAD: e698c291062f513059e0ad1442bd415394a1add8
Last commit: 46 minutes ago
Core tap HEAD: c24187829054961b2f35a3219b817c12300392ca
Core tap last commit: 4 weeks ago
Core tap JSON: 27 Mar 09:25 UTC
Core cask tap HEAD: d20e202ab44605100017a2fadd7527ced0fe92b0
Core cask tap last commit: 4 weeks ago
Core cask tap JSON: 27 Mar 09:25 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.3TfI4jReiG/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit westmere
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.2.1-x86_64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2
Rosetta 2: true

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /opt/homebrew.

Many of Homebrew's bottles (binary packages) can only be used with the default prefix.
Consider uninstalling Homebrew and reinstalling into the default prefix.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

When testing an 7z encrypted archive using `7zz t archive.7z` the tool asks for the password to decrypt the archive. While entering that password it echoes the entered password which makes it readable in cleartext. I think this should be prevented.

I've created an encrypted archive using Keka on my Mac. I've installed 7zz (from the forumula sevenzip) via Homebrew on my Mac. 
Installed version of `7zz` is: `7-Zip (z) 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20 64-bit`.

Running `7zz t your_encrypted_archive.7z` will ask you for the password. Enter it and you'll see your entered password in cleartext.

### Impact
Anybody reading logs of a script output using 7zz in this scenario would find the password in cleartext in the log file.

### What happened (include all command output)?

```
$ 7zz t encrypted_archive.7z

7-Zip (z) 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=UTF-8 Threads:10 OPEN_MAX:256

Scanning the drive for archives:
1 file, 158 bytes (1 KiB)

Testing archive: encrypted_archive.7z

Enter password:secret1234

--
Path = encrypted_archive.7z
Type = 7z
Physical Size = 158
Headers Size = 158
Solid = -
Blocks = 0

Everything is Ok

Size:       0
Compressed: 158
```

### What did you expect to happen?

It should have not echoed my entered password. Not even stars because that would tell me something about the entered password's length.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Create an encrypted 7z archive. I've used Keka on MacOS.

`$ 7zz t your_encrypted_archive.7z`
```

**Comment by SMillerDev** [comment]
I'm not sure how this is related to Homebrew

**Comment by dennisschulz2** [comment]
I will post this at https://sourceforge.net/p/sevenzip/bugs/ as well.
