### ISSUE TITLE
Referencing $USER variable fails

### ISSUE THREAD

**Issue by alexanderharm** [Homebrew/homebrew-core#16732]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/e15e308fc26204c943b9b5349a6bfa8c

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

I try to create a new formula which eventually should find its way into brew.

- What happened (include command output)

The following commands run perfectly fine in `brew install --interactive s-nail`:

```
make VAL_PREFIX=/usr/local/Cellar/s-nail/14.9.3 VAL_PRIVSEP_USER=$USER C_INCLUDE_PATH=/usr/local/opt/openssl/include CFLAGS=-L/usr/local/opt/openssl/lib LDFLAGS=-L/usr/local/opt/openssl/lib CONFIG=MAXIMAL config
make build
make install
make[1]: Nothing to be done for `all'.
```

However, the formula will fail when run with `brew install -v s-nail`:

```
==> make VAL_PREFIX=/usr/local/Cellar/s-nail/14.9.3 VAL_PRIVSEP_USER=$USER C_INCLUDE_PATH=/usr/local/opt/openssl/include CFLAGS=-L/usr/local/opt/openssl/lib LDFLAGS=-L/usr/local/opt/openssl/lib CONFIG=MAXIMAL config
==> make build
==> make install
make[1]: Nothing to be done for `all'.
chown: SER: illegal user name
```

- What you expected to happen

I expected the variable `$USER` to be correctly resolved to the user running brew.

- Step-by-step reproduction instructions (by running `brew install` commands)

See above. `$USER` is resolved correctly within `brew install --interactive` and not with `brew install -v`

**Comment by DomT4** [comment]
You want `ENV["USER"]` rather than `$USER`.

**Comment by alexanderharm** [comment]
Thanks. For newbies like me to use inside a double quoted string use `#{ENV["USER"]}`.

**Comment by DomT4** [comment]
Aye, something like `puts "Your name is #{ENV["USER"]}"` if folks are hunting examples in that context.
