### ISSUE TITLE
Cannot find OpenSSL with new formula

### ISSUE THREAD

**Issue by alexanderharm** [Homebrew/homebrew-core#16741]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/817f99e2e48948c73d20e45305f7c325

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

Create a new formula for s-nail

- What happened (include command output)

My configure always fails ***within*** brew (`brew install --interactive s-nail`) and cannot find OpenSSL

```
make OPT_AUTOCC=no CC=clang VAL_PREFIX="/usr/local/Cellar/s-nail/14.9.3" VAL_PRIVSEP_USER=admin C_INCLUDE_PATH=/usr/local/opt/openssl/include CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib CONFIG=NETSEND config
```

```
 . TLS/SSL (LibreSSL) ... no
 . TLS/SSL (OpenSSL >= v1.1.0) ... no
 . TLS/SSL (OpenSSL) ... yes
 . TLS/SSL (new style *_client_method(3ssl)) ... no
 . TLS/SSL (old style *_client_method(3ssl)) ... no
ERROR: feature OPT_SSL is required but not available
```

- What you expected to happen

The same command works 100% fine ***outside*** brew.

- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by equal-l2** [comment]
Would you show us the content of the formula you are making?
If anything is wrong with brew itself, all of us can reproduce the problem with it.

**Comment by DomT4** [comment]
Probably a stupid question, but I presume you have added `depends_on "openssl"` to your formula?

At the moment you're getting quietly nullified by Homebrew's environment:
```
clang called with: -I/usr/local/opt/openssl/include -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -o ./___tmp211797 ./___tmp111797.c
superenv removed:  -I/usr/local/opt/openssl/include -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

**Comment by alexanderharm** [comment]
I believe I did:

```
  # Define options
  option "with-maximal", "Anything on, including experimental features."
  option "with-netsend", "Sending messages directly to the mail provider via the SMTP protocol, instead of requiring a local mail-transfer-agent (MTA) who does."
  option "with-medium", "Possibly what people want who need nothing but a MIME-capable mailx(1)."
  option "with-minimal", "This is the most plain mailx(1)-alike mode, but with MIME support."
  option "with-nulli", "Anything that can be turned off is off but iconv(3)."
  option "with-null", "Anything that can be turned off is off."

  #depends_on "libidn"
  depends_on "openssl" => :optional

  def install

    args = %W[
      OPT_AUTOCC=no
      CC=clang
      VAL_PREFIX="#{prefix}"
      VAL_PRIVSEP_USER=#{ENV["USER"]}
    ]

    # Build with SSL?
    with_ssl = true
    if build.with? "maximal" or build.with? "netsend"
      with_ssl = true
    elsif build.with? "medium" or build.with? "minimal" or build.with? "nulli" or build.with? "null"
      with_ssl = false
    else
      with_ssl = true
    end

    if with_ssl
      args << "C_INCLUDE_PATH=#{Formula["openssl"].opt_include}"
      args << "CFLAGS=-I#{Formula["openssl"].opt_include}"
      args << "LDFLAGS=-L#{Formula["openssl"].opt_lib}"
    end
```

I'm probably missing something here...

**Comment by equal-l2** [comment]
Probably you are missing `pkg-config` as a dependency.
With `pkg-config`, you shouldn't need to specify `CFLAGS`, `LDFLAGS`, `C_INCLUDE_PATH`, if `s-nail` supports pkgconfig.

By the way, would you provide the *whole* content of your formula?

**Comment by DomT4** [comment]
In terms of Homebrew dependency resolution, you're not actually binding `with_ssl` to the `openssl` dependency anywhere. There's nothing in a default install there telling Homebrew it's okay to use the `openssl` dependency, so Homebrew rejects it.

Some broader advice: You don't need the quotes around `prefix` in the `args` array, and if you're going to string multiple conditionals together they should be wrapped in parens to avoid issues, such as `if build.with?("ducks") || build.with?("horses")`.

**Comment by ilovezfs** [comment]
```
  depends_on "openssl" => :optional
```
is not the same as
```
  depends_on "openssl"
```

You probably just need to pass `--with-openssl`.

**Comment by alexanderharm** [comment]
Thank you all for your input. I reworked my Formula but still face some issues:

- brew now complains about `s-nail.rb:90: syntax error, unexpected end-of-input, expecting keyword_end` which I don't really understand because to me the code looks fine.

- s-nail is compiled with different configuration presets which are mutually exclusive. What is the best approach to solving this? I now give the "higher" preset precedence over "lower" ones and default to the "highest".

```ruby
# Documentation: https://docs.brew.sh/Formula-Cookbook.html
#                http://www.rubydoc.info/github/Homebrew/brew/master/Formula
# PLEASE REMOVE ALL GENERATED COMMENTS BEFORE SUBMITTING YOUR PULL REQUEST!

class SNail < Formula
  desc "bla"
  homepage "https://www.sdaoden.eu/code.html"
  url "https://www.sdaoden.eu/downloads/s-nail-14.9.3.tar.gz"
  sha256 "9048abe94c8b732ddefcd70b9f6052da16977de76b07598790e4c763e97f911d"

  # Define options
  option "with-maximal", "Anything on, including experimental features."
  option "with-netsend", "Sending messages directly to the mail provider via the SMTP protocol, instead of requiring a local mail-transfer-agent (MTA) who does."
  option "with-medium", "Possibly what people want who need nothing but a MIME-capable mailx(1)."
  option "with-minimal", "This is the most plain mailx(1)-alike mode, but with MIME support."
  option "with-nulli", "Anything that can be turned off is off but iconv(3)."
  option "with-null", "Anything that can be turned off is off."

  # Determine configuration preset (higher preset takes precendence)
  config = 5 # MAXIMAL is default

  if build.with?("maximal")
  elsif build.with?("netsend")
    config = 4
  elsif build.with?("medium")
    config = 3
  elsif build.with?("minimal")
    config = 2
  elsif build.with?("nulli")
    config = 1
  elsif build.with?("null")
    config = 0
  end  

  #depends_on "libidn"
  depends_on "openssl" => if config > 3 

  def install

    args = %W[
      VAL_PREFIX=#{prefix}
      VAL_PRIVSEP_USER=#{ENV["USER"]}
    ]
   
    # Make does not find the correct paths to OpenSSL itself 
    args << "C_INCLUDE_PATH=#{Formula["openssl"].opt_include}" if config > 3 
    args << "EXTRA_LDFLAGS=-L#{Formula["openssl"].opt_lib}" if config > 3 

    # Determine config
    if config == 5
      args << "CONFIG=MAXIMAL"
    elsif config == 4
      args << "CONFIG=NETSEND"
    elsif config == 3
      args << "CONFIG=MEDIUM"
    elsif config == 2
      args << "CONFIG=MINIMAL"
    elsif config == 1
      args << "CONFIG=NULLI"
    elsif config == 0
      args << "CONFIG=NULL"
    end

    # Configure using above defined args
    system "make", *args, "config"
    # Build
    system "make", "build"
    # Somehow make doesn't like a file called INSTALL being present.
    # File is included in the .PHONY variable in the makefile but nonetheless.
    # Install will fail if not renamed/deleted.
    system "mv", "INSTALL", "INSTALL.txt"
    # Install
    system "make", "install" 

  end

  test do
    # `test do` will create, run in and delete a temporary directory.
    #
    # This test will fail and we won't accept that! For Homebrew/homebrew-core
    # this will need to be a test that verifies the functionality of the
    # software. Run the test with `brew test s-nail`. Options passed
    # to `brew install` such as `--HEAD` also need to be provided to `brew test`.
    #
    # The installed folder is not in the path, so use the entire path to any
    # executables being tested: `system "#{bin}/program", "do", "something"`.
    system "false"
  end
end
```

**Comment by ilovezfs** [comment]
```
  depends_on "openssl" => if config > 3 
```
shouldn't have the hash rocket. You can try
```
  depends_on "openssl" if config > 3 
```

**Comment by alexanderharm** [comment]
Great, thanks a lot. Also had to change the variable `config` to `@@config` (beginner's mistake).

One last question: a helper program of `s-nail` needs access to `/var/mail` which is by default owned by `root:mail`. How can I elevate the privileges of this helper program? Or do I just mention it in the caveats?
