### ISSUE TITLE
glib: metadata for GObject Introspection isn't used

### ISSUE THREAD

**Issue by tatethurston** [Homebrew/homebrew-core#167524]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs glib
Error: No logs.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run the example project for https://github.com/ruby-gnome/ruby-gnome.

### What happened (include all command output)?

`$(brew --prefix)/share/gir-1.0/Gio-2.0.gir` has the following content. introspectable="0" is the important part. It seems that metadata for GObject Introspection isn't used. It should be extracted from https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gcontenttype.c?ref_type=heads#L936-945 .

```
    <function name="content_types_get_registered"
              c:identifier="g_content_types_get_registered"
              introspectable="0">
      <source-position filename="gio/gcontenttype.h" line="72"/>
      <return-value>
        <type name="GLib.List" c:type="GList*">
          <type name="gpointer" c:type="gpointer"/>
        </type>
      </return-value>
    </function>
 ```

### What did you expect to happen?

See above. Cross posting from https://github.com/ruby-gnome/ruby-gnome/issues/1610#issuecomment-2026882248.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`$(brew --prefix)/share/gir-1.0/Gio-2.0.gir`
```

**Comment by tatethurston** [comment]
Still spinning up on the details here, opened an issue to kick off a conversation per https://github.com/ruby-gnome/ruby-gnome/issues/1610. cc @kou

**Comment by Bo98** [comment]
That's probably because `gcontentype.c` is not used on macOS - `gosxcontentype.m` is used instead.

**Comment by tatethurston** [comment]
Ah -- yes reverting to `gobject-introspection` v1.78 "resolves" the linked issue.

**Comment by kou** [comment]
Wow. Thanks for investing this.

@tatethurston Could you report this to upstream? https://gitlab.gnome.org/GNOME/glib/
`g_content_types_get_registered()`'s metadata for GObject Introspection is missing because `gosxcontentype.m` doesn't have a comment for GObject Introspection.

This may work:

```diff
diff --git a/gio/gcontenttype-win32.c b/gio/gcontenttype-win32.c
index 11ea203ab..5e454785b 100644
--- a/gio/gcontenttype-win32.c
+++ b/gio/gcontenttype-win32.c
@@ -400,6 +400,16 @@ g_content_type_guess (const gchar  *filename,
   return g_strdup ("*");
 }
 
+/**
+ * g_content_types_get_registered:
+ *
+ * Gets a list of strings containing all the registered content types
+ * known to the system. The list and its data should be freed using
+ * `g_list_free_full (list, g_free)`.
+ *
+ * Returns: (element-type utf8) (transfer full): list of the registered
+ *     content types
+ */
 GList *
 g_content_types_get_registered (void)
 {
diff --git a/gio/gosxcontenttype.m b/gio/gosxcontenttype.m
index 4d7a650c7..9bbca9aba 100644
--- a/gio/gosxcontenttype.m
+++ b/gio/gosxcontenttype.m
@@ -594,6 +594,16 @@ g_content_type_guess (const gchar  *filename,
   return create_cstr_from_cfstring (uti);
 }
 
+/**
+ * g_content_types_get_registered:
+ *
+ * Gets a list of strings containing all the registered content types
+ * known to the system. The list and its data should be freed using
+ * `g_list_free_full (list, g_free)`.
+ *
+ * Returns: (element-type utf8) (transfer full): list of the registered
+ *     content types
+ */
 GList *
 g_content_types_get_registered (void)
 {
diff --git a/gio/meson.build b/gio/meson.build
index 59c2b0fc0..7f4cda2ac 100644
--- a/gio/meson.build
+++ b/gio/meson.build
@@ -605,6 +605,7 @@ gio_base_sources = files(
   'glistmodel.c',
   'gliststore.c',
 )
+gio_base_sources += contenttype_sources
 
 gio_sources = gio_base_sources
 
@@ -612,7 +613,6 @@ if glib_build_shared
   gio_sources += files ('../glib/gtrace.c')
 endif
 
-gio_sources += contenttype_sources
 gio_sources += gdbus_daemon_sources
 gio_sources += unix_sources
 gio_sources += win32_sources
```

**Comment by tatethurston** [comment]
> Wow. Thanks for investing this.
> 
> @tatethurston Could you report this to upstream? https://gitlab.gnome.org/GNOME/glib/ `g_content_types_get_registered()`'s metadata for GObject Introspection is missing because `gosxcontentype.m` doesn't have a comment for GObject Introspection.
> 
> This may work:
> 
> ```diff
> diff --git a/gio/gcontenttype-win32.c b/gio/gcontenttype-win32.c
> index 11ea203ab..5e454785b 100644
> --- a/gio/gcontenttype-win32.c
> +++ b/gio/gcontenttype-win32.c
> @@ -400,6 +400,16 @@ g_content_type_guess (const gchar  *filename,
>    return g_strdup ("*");
>  }
>  
> +/**
> + * g_content_types_get_registered:
> + *
> + * Gets a list of strings containing all the registered content types
> + * known to the system. The list and its data should be freed using
> + * `g_list_free_full (list, g_free)`.
> + *
> + * Returns: (element-type utf8) (transfer full): list of the registered
> + *     content types
> + */
>  GList *
>  g_content_types_get_registered (void)
>  {
> diff --git a/gio/gosxcontenttype.m b/gio/gosxcontenttype.m
> index 4d7a650c7..9bbca9aba 100644
> --- a/gio/gosxcontenttype.m
> +++ b/gio/gosxcontenttype.m
> @@ -594,6 +594,16 @@ g_content_type_guess (const gchar  *filename,
>    return create_cstr_from_cfstring (uti);
>  }
>  
> +/**
> + * g_content_types_get_registered:
> + *
> + * Gets a list of strings containing all the registered content types
> + * known to the system. The list and its data should be freed using
> + * `g_list_free_full (list, g_free)`.
> + *
> + * Returns: (element-type utf8) (transfer full): list of the registered
> + *     content types
> + */
>  GList *
>  g_content_types_get_registered (void)
>  {
> diff --git a/gio/meson.build b/gio/meson.build
> index 59c2b0fc0..7f4cda2ac 100644
> --- a/gio/meson.build
> +++ b/gio/meson.build
> @@ -605,6 +605,7 @@ gio_base_sources = files(
>    'glistmodel.c',
>    'gliststore.c',
>  )
> +gio_base_sources += contenttype_sources
>  
>  gio_sources = gio_base_sources
>  
> @@ -612,7 +613,6 @@ if glib_build_shared
>    gio_sources += files ('../glib/gtrace.c')
>  endif
>  
> -gio_sources += contenttype_sources
>  gio_sources += gdbus_daemon_sources
>  gio_sources += unix_sources
>  gio_sources += win32_sources
> ```

https://gitlab.gnome.org/GNOME/glib/-/issues/3322

**Comment by kou** [comment]
Thanks.
I think that we can close this as an upstream issue.
