### ISSUE TITLE
picoc bottle seems broken

### ISSUE THREAD

**Issue by rien333** [Homebrew/homebrew-core#16758]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

If I install `picoc`  the binary fails every time I enter a line of code:
```
 $ brew install picoc
==> Downloading https://homebrew.bintray.com/bottles/picoc-2.1.sierra.bottle.tar.gz
Already downloaded: /Users/rw/Library/Caches/Homebrew/picoc-2.1.sierra.bottle.tar.gz
==> Pouring picoc-2.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/picoc/2.1: 3 files, 118.4KB
$ picoc -i
starting picoc v2.1
picoc> int test=5;
Abort trap: 6
$ 
```

`brew install --build-from-source picoc` shows the same issue. [The github picoc repository](https://github.com/zsaleeba/picoc) has a newer version (2.2) available however, that when I build it from source does actually work. 

[`brew gist-logs` output](https://gist.github.com/efabf2201d33d6ea865732b2e59380f5)

**Comment by ilovezfs** [comment]
@rien333 thanks for reporting this. If you `brew update && brew upgrade` this should now be fixed.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/16768.
