### ISSUE TITLE
`brew install postgresql` should install @16

### ISSUE THREAD

**Issue by willfaught** [Homebrew/homebrew-core#167593]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92a4311868322188478d7a90511ec0e8e6b0d7df
Last commit: 6 days ago
Core tap JSON: 30 Mar 22:23 UTC
Core cask tap JSON: 30 Mar 22:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.3
Rosetta 2: false
```

```
❯ brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install the latest postgresql (postgresql@16).

### What happened (include all command output)?

```
❯ brew install postgresql
Warning: Formula postgresql was renamed to postgresql@14.
==> Downloading https://ghcr.io/v2/homebrew/core/postgresql/14/manifests/14.11_1
Already downloaded: /Users/will/Library/Caches/Homebrew/downloads/cc5ce32be3ad755d6853a306c7d20db8221cceaa63708acb1937567a4ab65fda--postgresql@14-14.11_1.bottle_manifest.json
==> Fetching postgresql@14
==> Downloading https://ghcr.io/v2/homebrew/core/postgresql/14/blobs/sha256:d49e8b487d6b7e696e74ebf7d0bddbb9b8c343d7861d7
Already downloaded: /Users/will/Library/Caches/Homebrew/downloads/695bc5763b3ab3f65140681669c474e2b18ff40d6ff809534e5436f2105b6d90--postgresql@14--14.11_1.arm64_sonoma.bottle.tar.gz
==> Pouring postgresql@14--14.11_1.arm64_sonoma.bottle.tar.gz
==> Caveats
This formula has created a default database cluster with:
  initdb --locale=C -E UTF-8 /opt/homebrew/var/postgresql@14
For more details, read:
  https://www.postgresql.org/docs/14/app-initdb.html

To start postgresql@14 now and restart at login:
  brew services start postgresql@14
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/postgresql@14/bin/postgres -D /opt/homebrew/var/postgresql@14
==> Summary
🍺  /opt/homebrew/Cellar/postgresql@14/14.11_1: 3,319 files, 46MB
==> Running `brew cleanup postgresql@14`...
```

### What did you expect to happen?

Install @16.

See https://github.com/orgs/Homebrew/discussions/5244.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql
```

**Comment by cho-m** [comment]
This is expected as we want to remove the unversioned `postgresql` name - https://github.com/Homebrew/homebrew-core/pull/107726

Previously, users who installed unversioned name would often get broken DBs upon `brew upgrade` since PostgreSQL DBs are version-specific.

The `postgresql` name is still around since it was renamed to `postgresql@14` and will remain around until `postgresql@14` is removed. Afterward, the `postgresql` name will no longer be used in Homebrew/core.

Users are expected to install the specific version they need/want. For upgrade, users have to install `n+1` version and follow official migration steps.
