### ISSUE TITLE
`brew install postgresql@16` does not link psql into /opt/homebrew/bin

### ISSUE THREAD

**Issue by willfaught** [Homebrew/homebrew-core#167594]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92a4311868322188478d7a90511ec0e8e6b0d7df
Last commit: 6 days ago
Core tap JSON: 30 Mar 22:23 UTC
Core cask tap JSON: 30 Mar 22:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.3
Rosetta 2: false
```

```
❯ brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install the latest postgresql version (16.x), and have the binaries linked into my PATH.

### What happened (include all command output)?

```
❯ brew install postgresql@16
==> Downloading https://ghcr.io/v2/homebrew/core/postgresql/16/manifests/16.2_1
Already downloaded: /Users/will/Library/Caches/Homebrew/downloads/4951a84303f0ec8880205aaa4a088f759033fe5025cd14e815ee1d24c4721e24--postgresql@16-16.2_1.bottle_manifest.json
==> Fetching postgresql@16
==> Downloading https://ghcr.io/v2/homebrew/core/postgresql/16/blobs/sha256:40d2efe6bbcf70078f6fbe80ca8e72eafc16d6003d390
Already downloaded: /Users/will/Library/Caches/Homebrew/downloads/2e44a19ae11fdc6842af26b976c8936bc406e18f2a22d5bdfc8d3141da671a6c--postgresql@16--16.2_1.arm64_sonoma.bottle.tar.gz
==> Pouring postgresql@16--16.2_1.arm64_sonoma.bottle.tar.gz
==> Caveats
This formula has created a default database cluster with:
  initdb --locale=C -E UTF-8 /opt/homebrew/var/postgresql@16
For more details, read:
  https://www.postgresql.org/docs/16/app-initdb.html

postgresql@16 is keg-only, which means it was not symlinked into /opt/homebrew,
because this is an alternate version of another formula.

If you need to have postgresql@16 first in your PATH, run:
  fish_add_path /opt/homebrew/opt/postgresql@16/bin

For compilers to find postgresql@16 you may need to set:
  set -gx LDFLAGS "-L/opt/homebrew/opt/postgresql@16/lib"
  set -gx CPPFLAGS "-I/opt/homebrew/opt/postgresql@16/include"

To start postgresql@16 now and restart at login:
  brew services start postgresql@16
Or, if you don't want/need a background service you can just run:
  LC_ALL="C" /opt/homebrew/opt/postgresql@16/bin/postgres -D /opt/homebrew/var/postgresql@16
==> Summary
🍺  /opt/homebrew/Cellar/postgresql@16/16.2_1: 3,798 files, 68.6MB
==> Running `brew cleanup postgresql@16`...

❯ which psql
❯ echo $status
1
```

### What did you expect to happen?

Link psql into /opt/homebrew/bin.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install postgresql@16
```

**Comment by cho-m** [comment]
This is expected behavior because we can only link a single PostgreSQL formula as all of them conflict with each other.

The version of PostgreSQL linked has to be the copy that "owns" the extension formulae (e.g. `postgis`, `citus`, etc.) due to how PostgreSQL detects extensions.

At some point, the version for PostgreSQL that gets linked by default may change, but that depends on whenever someone creates a PR to do so (migrating all necessary formulae).

**Comment by willfaught** [comment]
@cho-m It seems to me that the result of this issue and https://github.com/Homebrew/homebrew-core/issues/167593 is that it isn’t possible to “brew install” Postgres and have it working on your path out of the box. This isn’t a good user experience. I have to manually add the @16 bin to my path to get anything working. Wouldn’t following this pattern for all names that have multiple major versions/incompatible versions result in nothing being linked into PATH by default? That’s not very useful out of the box.

It seems better in my opinion to have a plain “postgresql” formula always install the latest major version, and let users install older versions if they want to use older DBs.

**Comment by ollietreend** [comment]
@willfaught @cho-m Annoyingly I'm experiencing a similar issue, also related to #167593.

I want to use PostgreSQL 16 with the PostGIS extension.

But there's only one [postgis](https://formulae.brew.sh/formula/postgis) formula and it's hardcoded to `postgresql@14` 🤦🏻

https://github.com/Homebrew/homebrew-core/blob/d091ded4d075fe52c57c2eef38bf09eb0874c15d/Formula/p/postgis.rb#L38

So it seems that there's no way to use it with Postgres 16 (or any other version) using Homebrew 😢

**Comment by slifty** [comment]
I also find it strange that I can't have a single `postgres` installation that tracks with the major versions, and instead always need to specify a version. The broken out-of-the-box experience makes it all the more confusing.

**Comment by SMillerDev** [comment]
> I also find it strange that I can't have a single postgres installation that tracks with the major versions, and instead always need to specify a version.

This is how Postgres devs intend it to work since you can't migrate from one major version to another without manual intervention
