### ISSUE TITLE
ghostscript package config

### ISSUE THREAD

**Issue by exekutive** [Homebrew/homebrew-core#167677]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.15-127-g26200a9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 26200a9e9bda4c9f9d8f2ea48a273f7671d7e3ff
Last commit: 2 hours ago
Core tap JSON: 01 Apr 10:35 UTC
Core cask tap JSON: 01 Apr 10:35 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.bF9Ym8s6Vy/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

compile imagemagick with ghostscript support

### What happened (include all command output)?

- installed ghostscript using homebrew
- compilers cannot find ghostscript 

### What did you expect to happen?

I expected homebrew to generate a pc file for ghostscript so that package config can generate to appropriate cflags for compilers to find the headers and files

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ghostscript

pkg-config --cflags ghostscript
Package ghostscript was not found in the pkg-config search path.
Perhaps you should add the directory containing `ghostscript.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ghostscript' found
```
```

**Comment by carlocab** [comment]
There is no pc file because upstream don't provide one. If you need ghostscript to provide `.pc` files, please file an issue upstream (or send them a patch).

**Comment by exekutive** [comment]
how are they supposed to know where homebrew is going to install the files?

**Comment by SMillerDev** [comment]
> how are they supposed to know where homebrew is going to install the files?

That's what gets configured in the build. Every single other tool with pkgconfig files has the paths generated during the build, so can Ghostscript
