### ISSUE TITLE
trafshow formula shoud be updated for sierra

### ISSUE THREAD

**Issue by scamp** [Homebrew/homebrew-core#16766]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

gist-logs: https://gist.github.com/anonymous/08d873ab64ef199700cab783be33ba80

To help us debug your issue please explain:
- What you were trying to do (and why)
Run trafshow utility, installed either from bottle or source on mac OS Sierra 10.12.6.
Starting from Sierra, systems libpcap in /usr/lib/libpcap.A.dylib does not have pcap_version symbol.
- What happened (include command output)
sudo trafshow
dyld: Symbol not found: _pcap_version
  Referenced from: /usr/local/bin/trafshow
  Expected in: /usr/lib/libpcap.A.dylib
 in /usr/local/bin/trafshow
Abort trap: 6
- What you expected to happen
Trafshow is running
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install trafshow
sudo trafshow

**Comment by ilovezfs** [comment]
@scamp This should be fixed now if you `brew update` and `brew upgrade`.

**Comment by scamp** [comment]
Thanks @ilovezfs
