### ISSUE TITLE
gpgme needs a rebuild

### ISSUE THREAD

**Issue by tsdgeos** [Homebrew/homebrew-core#167631]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~$ brew config
HOMEBREW_VERSION: 4.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92a4311868322188478d7a90511ec0e8e6b0d7df
Last commit: 7 days ago
Core tap JSON: 31 Mar 17:01 UTC
Core cask tap JSON: 31 Mar 17:08 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false


~$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use gpgme-config --libs

### What happened (include all command output)?

It points to a wrong and non existing assuan path

### What did you expect to happen?

It should point to the correct libassuan path

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gpgme
gpgme-config --libs

Check it says 2.5.7 (the current version) instead of 2.5.6
```

**Comment by bschaatsbergen** [comment]
Running `brew install gpgme`, followed by `gpgme-config --libs` results a 2.5.6 libassuan version for:

```
$brew install gpgme
...
$ gpgme-config --libs
-L/home/linuxbrew/.linuxbrew/opt/gpgme/lib -lgpgme -L/home/linuxbrew/.linuxbrew/Cellar/libassuan/2.5.6/lib -lassuan -L/home/linuxbrew/.linuxbrew/opt/libgpg-error/lib -lgpg-error
```

**Comment by tsdgeos** [comment]
Exactly which is wrong because that path doesn't exist

Aah i see i may have written the "Step-by-step reproduction instructions" in reverse.

What i mean is see how the path that exists is /home/linuxbrew/.linuxbrew/Cellar/libassuan/2.5.7/lib while the tool is saying to use /home/linuxbrew/.linuxbrew/Cellar/libassuan/2.5.6/lib (which doesn't exist)
