### ISSUE TITLE
Change resource url of `predictionio` and add its mirrors

### ISSUE THREAD

**Issue by sahilshekhawat** [Homebrew/homebrew-core#16777]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<img width="522" alt="screen shot 2017-08-14 at 12 21 24 pm" src="https://user-images.githubusercontent.com/5890452/29261046-1e7c57ea-80eb-11e7-9ff2-9377897bac59.png">

URL is correct since it is mentioned in [predictionio's documentation](https://predictionio.incubator.apache.org/install/install-linux/) but it is not working anymore. 

I think we can add its mirrors as [mentioned on their website](http://predictionio.incubator.apache.org/install/install-sourcecode/). Link to its [Apache Mirrors](https://www.apache.org/dyn/closer.cgi/incubator/predictionio/0.11.0-incubating/apache-predictionio-0.11.0-incubating.tar.gz)

``brew gist-logs predictionio``
<img width="215" alt="screen shot 2017-08-14 at 12 29 28 pm" src="https://user-images.githubusercontent.com/5890452/29261261-3f866876-80ec-11e7-8b52-739ff618685f.png">

**Comment by ilovezfs** [comment]
It looks like it may be due for an upgrade because the homepage only seems to reference 0.11.0 now, but until that happens, they've posted the release tarball to GitHub: https://github.com/apache/incubator-predictionio/releases/download/v0.9.6/PredictionIO-0.9.6.tar.gz

**Comment by ilovezfs** [comment]
@sahilshekhawat this should be fixed now if you `brew update`.

**Comment by sahilshekhawat** [comment]
Thanks @ilovezfs
