### ISSUE TITLE
Installing 'delve' fails in 10.12.6.

### ISSUE THREAD

**Issue by brunomcustodio** [Homebrew/homebrew-core#16780]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] ~~If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~~

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)

> I was trying to install `delve` using Homebrew.

- What happened (include command output)

```
$ brew install delve
==> Installing delve from go-delve/delve

==> Downloading https://github.com/derekparker/delve/archive/v1.0.0-rc.1.tar.gz
Already downloaded: /Users/brunomcustodio/Library/Caches/Homebrew/delve-1.0.0-rc.1.tar.gz
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
==> Generating dlv-cert
==> openssl req -new -newkey rsa:2048 -x509 -days 3650 -nodes -config dlv-cert.cfg -extensions codesign_reqext -batch -out dlv-cert.cer -keyout dlv-cert.key
==> [SUDO] Installing dlv-cert as root
==> sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain dlv-cert.cer
Last 15 lines from /Users/brunomcustodio/Library/Logs/Homebrew/delve/02.sudo:
2017-08-14 09:09:25 +0100

sudo
security
add-trusted-cert
-d
-r
trustRoot
-k
/Library/Keychains/System.keychain
dlv-cert.cer


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/go-delve/homebrew-delve/issues
```

- What you expected to happen

> I expected the installation to succeed.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install delve
```

# ~~New Formulae~~
~~To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).~~

**Comment by ilovezfs** [comment]
>If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
>https://github.com/go-delve/homebrew-delve/issues

**Comment by brunomcustodio** [comment]
@ilovezfs I'm terribly sorry, I totally overlooked that.

**Comment by ilovezfs** [comment]
No problem :)
