### ISSUE TITLE
brew search takes 30+ seconds

### ISSUE THREAD

**Issue by forthrin** [Homebrew/homebrew-core#16783]
Why does a `brew search`, a text search against a database of some thousand entries, take 30+ seconds rather than a split second? Same goes for `brew update`. Is something wrong with my system?

```
$ time brew search urlwatch
No formula found for "urlwatch".

real	0m37.175s
user	0m35.039s
sys	0m0.718s

$ brew doctor
Your system is ready to brew.

$ brew tap
homebrew/core
homebrew/nginx
homebrew/php
homebrew/science

$ brew --version
Homebrew 1.3.1

```

**Comment by MikeMcQuaid** [comment]
> a text search against a database of some thousand entries

There is no database. It's also using the GitHub API to check online.

> Is something wrong with my system?

It sounds like you may have a slow connection to GitHub.

**Comment by MikeMcQuaid** [comment]
Also: 

> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by forthrin** [comment]
Please delete this issue. Posted a new one with more details in the correct repository.

**Comment by MikeMcQuaid** [comment]
@forthrin You can't delete issues. Don't just create the same issue again with more information. This is not something we're able to support. If you're able to reproduce what your problem is could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by forthrin** [comment]
I'm a bit confused about your response, and the nature of the issue I reported initially.

1. Your response: "This is not something we're able to support." Should I interpret this as "you're not able to support searches faster than about 30 seconds per search"...?

2. Your suggestion to "open a pull request": Aren't regular end users allowed to make bug reports for Homebrew? Is the issue tracker only open for developers who make code contributions?

**Comment by MikeMcQuaid** [comment]
> Your response: "This is not something we're able to support." Should I interpret this as "you're not able to support searches faster than about 30 seconds per search"...?

This search takes a comparable amount of time for me. This is not a bug.

> Your suggestion to "open a pull request": Aren't regular end users allowed to make bug reports for Homebrew? 

As above: this is not a bug. You would like `brew search` to behave faster in this case. For that, we would need a pull request.

> Is the issue tracker only open for developers who make code contributions?

If you file an issue, fill out the issue template and it becomes clear it's a bug in Homebrew's behaviour that affects more than just you: the issue will be left open and we may work on a fix. If not, it will be closed.

**Comment by forthrin** [comment]
I'm not familiar with how to create pull requests, and was unaware that this was required to report an issue. I thought I'd supplied the necessary details. Evidently you're experiencing the same issue, and I assume you too would have appreciated a search that was on par with a regular Web search (<1s).

You haven't said anything about why the search is taking so long. Is it because Homebrew has to make a roundtrip to thousands of repositories to retrieve information?

Shouldn't this be cached in a central place, even possibly locally, since Homebrew is updated on a daily basis, and a database table representing relevant search data couldn't take up much space.

But as a regular user I don't know all the details under the hood, or the culture around how you do development. As an evident expert in the area, you are probably more likely to have the answers and what's possible to achieve.
