### ISSUE TITLE
FR: qt5 offer --with-webkit option?

### ISSUE THREAD

**Issue by bagong** [Homebrew/homebrew-core#168]
Our project has the problem that it can't quickly/easily switch to webengine. It is mainly a resources problem, but also as, it is cross-platform, linux distributions will take time to reach qt5.6. Qt5.6 official does not provide webkit binaries any more. Would it be possible to offer a "build with webkit" option for projects that have difficulties making the switch for now?
I asked a similar question on msys2 (kind of a Windows homebrew), and they plan to keep providing webkit binaries "until it is too much of a burden", which sounds like a fair offer to me. They expect webkit to be supportable with not too much hassle during Qt5.6...

**Comment by mikemcquaid** [comment]
I'm afraid this is something we don't have the resources to do. While I feel your pain I think this is something you should take up with Qt rather than us. Sorry!

**Comment by bagong** [comment]
I understand your point, and I respect it, of course! But maybe leave the issue open for a while, just to see how many projects come up with a similar problem? Btw., it's not only linux, projects using MinGW for their Windows port are completely locked out, because webengine is not provided in MinGW builds at all. Apparently Qt is going to switch to llvm for the "free"-compiler alternative because of problems between Webengine and gcc, and there is another transitional lag time to be expected here.

**Comment by mikemcquaid** [comment]
Sorry, we close out things we don't plan on actively working on. https://github.com/Homebrew/homebrew-versions/blob/master/qt55.rb is the best bet for you, probably: `brew install homebrew/versions/qt55`.

**Comment by UniqMartin** [comment]
@bagong: You might also be interested in reading up on the discussion following the update to Qt 5.6.0 in Homebrew/legacy-homebrew#50234. (There might also be people you want to join forces with.)
