### ISSUE TITLE
libevent: using the wrong release package

### ISSUE THREAD

**Issue by carenas** [Homebrew/homebrew-core#16807]
brew audit --strict suggested this ticket be open

the release for 2.1.8 is available from :

  https://github.com/libevent/libevent/releases/tag/release-2.1.8-stable

the one used by the current Formula is most likely an autogenerated archive and differ slightly (plus it doesn't include any of the autotools artifacts)

additionally the current Formula could be improved to : 

* make openssl optional, so other packages that depend on this but don't need it (like tmux) can be built without it
* allow for packaging the HEAD for cases where unreleased bugs (like libevent/libevent#512) that had fixes that haven't been released can be fixed

**Comment by ilovezfs** [comment]
Closing since there's a pull request.
