### ISSUE TITLE
python3 and rapidjson don't seem to be working

### ISSUE THREAD

**Issue by anujgoyal** [Homebrew/homebrew-core#168180]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd1155be8f50998429a795c15a69c8fe75250510
Last commit: 4 days ago
Core tap JSON: 06 Apr 02:46 UTC
Core cask tap JSON: 06 Apr 02:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to import rapidjson into python3

### What happened (include all command output)?

$ brew reinstall rapidjson
==> Downloading https://ghcr.io/v2/homebrew/core/rapidjson/manifests/1.1.0-1
Already downloaded: /Users/goanuj/Library/Caches/Homebrew/downloads/e7100bb1fda499a8d283fda7f6cfbc765ee2f44c56d29e5587ff2e46836a5b73--rapidjson-1.1.0-1.bottle_manifest.json
==> Fetching rapidjson
==> Downloading https://ghcr.io/v2/homebrew/core/rapidjson/blobs/sha256:97a2dc11fc6d7359450d3bee8c9b06b4ad1f141ea23b2b1b57eae9f9c9bcb0cf
Already downloaded: /Users/goanuj/Library/Caches/Homebrew/downloads/e7aa740d55a8c85036ebdaf944854b560211c4f9026df780a9298b51464536d5--rapidjson--1.1.0.all.bottle.1.tar.gz
==> Reinstalling rapidjson 
==> Pouring rapidjson--1.1.0.all.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/rapidjson/1.1.0: 60 files, 661.1KB
==> Running `brew cleanup rapidjson`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

$ /opt/homebrew/bin/python3
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import rapidjson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rapidjson'
>>> 

### What did you expect to happen?

python3 should have allowed the import of rapidjson

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall python3
brew reinstall rapidjson

/opt/homebrew/bin/python3
>>> import rapidjson
```

**Comment by ZhongRuoyu** [comment]
`rapidjson` is a C++ project which does not provide any Python bindings.
