### ISSUE TITLE
.NET 8 Runtime Bad Signature for formula "dotnet"

### ISSUE THREAD

**Issue by hanc2006** [Homebrew/homebrew-core#168205]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew doctor`
Your system is ready to brew

`brew config`
HOMEBREW_VERSION: 4.2.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: bd1155be8f50998429a795c15a69c8fe75250510
Last commit: 5 days ago
Core tap JSON: 06 Apr 14:47 UTC
Core cask tap JSON: 06 Apr 14:47 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Looks like the dotnet binaries from Homebrew are ad-hoc signed, not signed by Microsoft. This causes problems when they need to be loaded by third-party applications (like VSCode extensions). I found a discussion from the runtime .NET team guys where they explain the problem.

```
codesign -dv /opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib
Executable=/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib
Identifier=libhostfxr-55554944e079e2218f4232fcbc25de741b71ed09
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=3020 flags=0x2(adhoc) hashes=88+2 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12
```

Link in github: https://github.com/dotnet/runtime/issues/100413#issuecomment-2035037476

### What happened (include all command output)?

VScode extension C# Dev kit Fails to load on Mac OS

```
Starting Check for .NET Version for Blazor Projects...
Starting command: "dotnet" --version...
Completed command: "dotnet" --version (68ms)
Starting command: "dotnet" --list-sdks...
Completed command: "dotnet" --list-sdks (4ms)
Completed Check for .NET Version for Blazor Projects (72ms)
Starting Query for all projects...
Starting ExecuteQuery with project query execution service...
Starting Spawn .NET server...
Using preinstalled .NET runtime at "/opt/homebrew/Cellar/dotnet/8.0.3/libexec/dotnet"
.NET server STDERR: Failed to load /opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib, error: dlopen(/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib' (code signature in <E079E221-8F42-32FC-BC25-DE741B71ED09> '/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib' (no such file), '/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib' (code signature in <E079E221-8F42-32FC-BC25-DE741B71ED09> '/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
The library libhostfxr.dylib was found, but loading it from /opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

.NET server exited with 130
```

### What did you expect to happen?

No errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install dotnet
brew cask install visual-studio-code
code --install-extension ms-dotnettools.csdevkit
```

Open VSCode -> Terminal -> Output -> select C# Dev Toolkit from the dropdown to view the issue.
```

**Comment by Bo98** [comment]
> Looks like the dotnet binaries from Homebrew are ad-hoc signed, not signed by Microsoft

Only Microsoft have access to their private keys. You will see this with any open-source redistribution.

If you need Microsoft-signed binaries, you are likely looking for closed-source .NET from Microsoft.

As such, this cannot be fixed on our side. If Microsoft want to allow .NET builds from other vendors, they could disable library validation (`com.apple.security.cs.disable-library-validation`).

**Comment by cho-m** [comment]
Closing as expected behavior and nothing actionable on Homebrew side.

Install one of the available Casks (e.g. https://formulae.brew.sh/cask/dotnet, https://formulae.brew.sh/cask/dotnet-sdk) if you need Microsoft-built-and-signed binaries.
