### ISSUE TITLE
ncmpcpp fails to launch

### ISSUE THREAD

**Issue by maletor** [Homebrew/homebrew-core#16834]
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.58.2.dylib
  Referenced from: /usr/local/opt/boost/lib/libboost_locale-mt.dylib
  Reason: image not found
fish: 'ncmpcpp' terminated by signal SIGABRT (Abort)

It needs to be compiled against boost.

**Comment by ilovezfs** [comment]
Your boost with built with the `--with-icu4c` option, and `icu4c` was just upgraded, so you will need to `brew reinstall boost` so that it is linked against the new version of `icu4c`.

**Comment by maletor** [comment]
I did that and it's working. Seems like boost needs to be upgraded to a `-2` release or something.

**Comment by ilovezfs** [comment]
@maletor we would do that if icu4c were a required or recommended dependency, but you're on your own in terms of rebuilding for optional dependencies. Less than 1% of users are building boost with icu4c so we're not going to force upgrades on the other 99%.

**Comment by maletor** [comment]
I never installed boost with icu4c nor optional dependencies for boost.

**Comment by ilovezfs** [comment]
@maletor did you install freeling at some point?

**Comment by maletor** [comment]
No. Maybe. I don't know. Shouldn't matter.

**Comment by ilovezfs** [comment]
@maletor it does matter in that boost would have been built with icu4c prior to https://github.com/Homebrew/homebrew-core/pull/16737.

**Comment by maletor** [comment]
Do you think you should have released a new "rel" number on boost when you changed something about it?

**Comment by ilovezfs** [comment]
@maletor nothing with boost changed.

**Comment by maletor** [comment]
Interesting. Well I didn't have freeling installed but maybe something else had it installed with boost.

**Comment by ilovezfs** [comment]
@maletor what's the output of
```
cat /usr/local/opt/boost/INSTALL_RECEIPT.json
```

**Comment by maletor** [comment]
```json
{
   "homebrew_version":"1.3.1-49-gdaa0ea4",
   "used_options":[
      "--with-icu4c"
   ],
   "unused_options":[
      "--without-single",
      "--without-static",
      "--c++11"
   ],
   "built_as_bottle":false,
   "poured_from_bottle":false,
   "installed_as_dependency":false,
   "installed_on_request":true,
   "changed_files":null,
   "time":1502820258,
   "source_modified_time":1492397336,
   "HEAD":"daa0ea4b8a53b3d2965b84ff673c58310a6937ed",
   "stdlib":"libcxx",
   "compiler":"clang",
   "aliases":[
      "boost@1.64"
   ],
   "runtime_dependencies":[
      {
         "full_name":"icu4c",
         "version":"59.1"
      }
   ],
   "source":{
      "path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb",
      "tap":"homebrew/core",
      "spec":"stable",
      "versions":{
         "stable":"1.64.0",
         "devel":null,
         "head":"HEAD",
         "version_scheme":0
      }
   }
}
```

**Comment by ilovezfs** [comment]
>I guess I'm busted.

Hehe. Yeah the `--with-icu4c` came from _somewhere_.

**Comment by maletor** [comment]
How do I tell homebrew to stop installing that each time I reinstall boost? I want boost without icu4c.

**Comment by ilovezfs** [comment]
```
brew uninstall boost
brew install boost
```
and it should be gone :)
