### ISSUE TITLE
gd failed to build on 10.11.4

### ISSUE THREAD

**Issue by bartgrantham** [Homebrew/homebrew-core#1683]
Trying to install gphoto2, but the install is failing on gd.  [here's the gist](https://gist.github.com/3679a611e70030db703140e39d741fd0).

**Comment by ilovezfs** [comment]
Please try
```
brew uninstall -f fontconfig freetype gd jpeg libpng libtiff libtool libusb libusb-compat webp
brew install libgphoto2
```

**Comment by ilovezfs** [comment]
@bartgrantham did you get a chance to try the above?

**Comment by bartgrantham** [comment]
Yes!  And it failed again, I'll post the error when I get back in front of my laptop.

On Jun 4, 2016, at 13:58, ilovezfs <notifications@github.com<mailto:notifications@github.com>> wrote:


@bartgrantham<https://github.com/bartgrantham> did you get a chance to try the above?

�

**Comment by ilovezfs** [comment]
@bartgrantham Great, thank you.

**Comment by bartgrantham** [comment]
I spoke too soon.  I tried to `brew install gphoto2` and had missed brew's recommendation to `brew unlink libgphoto2`.  So I did get gphoto2 installed properly via:

```
brew unlink libgphoto2
brew install libgphoto2
brew install gphoto2
```

And now I have gphoto2, apparently.  Still have to test, but I'm going to close this issue.

**Comment by ilovezfs** [comment]
Glad you got it working :)
