### ISSUE TITLE
rxvt-unicode formula unnecessarily disabling perl?

### ISSUE THREAD

**Issue by spaghetti2514** [Homebrew/homebrew-core#16846]
The formula for rxvt-unicode contains the line
```ruby
args << "--disable-perl" if ENV.compiler == :clang
```
but if I comment this line out, the build still succeeds and urxvt seems to function fine (and now has perl support).

Was this added to work around a clang bug that was fixed at some point? Can anyone else try building without --disable-perl and see if it also builds successfully?

If there's no longer a reason to use --disable-perl, I'd like to request it be taken out or have a formula option to toggle it, since I prefer using some perl scripts with urxvt

(brew repo is updated, macOS version is 10.12.6, clang version is 802.0.42)

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/legacy-homebrew/issues/27955
https://github.com/Homebrew/homebrew-x11/issues/163
https://github.com/Homebrew/legacy-homebrew/issues/32375

It's possible the bug has been fixed. CC @mistydemeo

**Comment by mistydemeo** [comment]
While the Perl header is the same, it's possible something else has changed to fix this. I guess we can safely restore perl support?

**Comment by ilovezfs** [comment]
@spaghetti2514 Perl support should be there now if you brew update and brew upgrade.
