### ISSUE TITLE
aws-cdk depends on node, but isn't compatible with current node 21

### ISSUE THREAD

**Issue by peterhalicky** [Homebrew/homebrew-core#168511]
### `brew config` output

```shell
HOMEBREW_VERSION: 4.2.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0476c2e5e4f02b409084553896340b2f4ab3352e
Last commit: 3 days ago
Core tap JSON: 10 Apr 08:49 UTC
Core cask tap JSON: 10 Apr 08:49 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.RBvm3oOtLi/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install and use aws-cdk.

### What happened (include all command output)?

I have installed aws-cdk (long time ago), then did a brew update/brew upgrade recently, everything looks ok. But when I try to run `cdk`, I get this error:
`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                                                      !!
!!  This software has not been tested with node v21.7.2.                                                                !!
!!  Should you encounter odd runtime issues, please try using one of the supported release before filing a bug report.  !!
!!                                                                                                                      !!
!!  This software is currently running on node v21.7.2.                                                                 !!
!!  As of the current release of this software, supported node releases are:                                            !!
!!  - ^20.0.0 (Planned end-of-life: 2026-04-30)                                                                         !!
!!  - ^18.0.0 (Planned end-of-life: 2025-04-30)                                                                         !!
!!                                                                                                                      !!
!!  This warning can be silenced by setting the JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION environment variable.        !!
!!                                                                                                                      !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

### What did you expect to happen?

I expect that the formula will depend on a compatible nodejs, i.e. as of now node@20 -- and should also use it.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install aws-cdk
cdk
(observe top of printout)
```

**Comment by chenrui333** [comment]
that is not really a bug, you can silence it with `JSII_SILENCE_WARNING_UNTESTED_NODE_VERSION`

**Comment by chenrui333** [comment]
see some discussion in here, https://github.com/hashicorp/terraform-cdk/issues/1316

either way, the cdk would work as it is. Gonna close it for now.
