### ISSUE TITLE
Varnish version does not correct.

### ISSUE THREAD

**Issue by amrokhudair** [Homebrew/homebrew-core#16857]
Hi
I use brew install varnish , to install varnish in mac
When I type : brew install varnish in terminal , there is an waning message says **(Warning: varnish 5.1.3 is already installed**)
But when I type : varnishd -V , the consloe echo 👍
**varnishd (varnish-3.0.4 revision 9f83e8f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2011 Varnish Software AS**
I want the version 5.1.3 to be activated.
HowI can solve this problem??

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

**Comment by amrokhudair** [comment]
What is the **issue checklist and provide ALL the requested information** yo want?

**Comment by chdiza** [comment]
It's the stuff you deleted from the issue submission text box before you submitted the issue.
