### ISSUE TITLE
Move gh to boneyard

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#16871]
On the front page for the `gh` project, the author mentioned that the project is no longer actively updated, and superseded by `github/hub`. That is back in 2014, and all the features in `gh` has been merged to `hub` https://github.com/github/hub/issues/475

Since `hub` is already in `hombrew-core`, why not move `gh` to the boneyard?

**Comment by ilovezfs** [comment]
The boneyard is deprecated but it makes sense to delete the formula.
