### ISSUE TITLE
mpv: no audio playing .mkv files when ffmpeg upgraded to 7.0

### ISSUE THREAD

**Issue by cattyhouse** [Homebrew/homebrew-core#168892]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.17-99-g17d5ab3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17d5ab381bb8da90f94964e475fb73b87993108a
Last commit: 14 hours ago
Core tap HEAD: c6b3cbe78038d1f7a0b3c4672fce6b4a37758207
Core tap last commit: 35 minutes ago
Core cask tap HEAD: 1b9a5024fead350c5d3a7d612b68963b9713e72c
Core cask tap last commit: 3 hours ago
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_AUTOREMOVE: set
HOMEBREW_BAT: set
HOMEBREW_BAT_THEME: TwoDark
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 10
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 10
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false


Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

mpv file.mkv

### What happened (include all command output)?

- no audio, the issue is fixed by mpv upstream, but the patch is not included in mpv formula

```
[ffmpeg] SWR: Input channel layout "" is invalid or unsupported.
[swresample] Cannot open Libavresample context.
[swresample] libswresample failed to initialize.
Cannot convert decoder/filter output to any format supported by the output.
Audio: no audio
```

- `brew info mpv`

```
==> mpv: stable 0.37.0 (bottled), HEAD
Media player based on MPlayer and mplayer2
https://mpv.io
Installed
/opt/homebrew/Cellar/mpv/0.37.0_2 (33 files, 9.3MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-04-13 at 09:57:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/m/mpv.rb
License: Cannot Represent
==> Dependencies
Build: docutils, meson, pkg-config
Required: ffmpeg, jpeg-turbo, libarchive, libass, libplacebo, little-cms2, luajit, mujs, uchardet, vapoursynth, yt-dlp
==> Requirements
Build: Xcode (on macOS)
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
```

### What did you expect to happen?

with audio

### Step-by-step reproduction instructions (by running `brew` commands)

[mpv developer suggests](https://github.com/mpv-player/mpv/pull/13665#issuecomment-2053014913) including this patch in mpv formula: 

https://github.com/mpv-player/mpv/pull/13665/commits

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`. This is required information for all bug reports to this repository. We can reopen this once you've done that.

**Comment by ZhongRuoyu** [comment]
The fix is in. You can run `brew update && brew upgrade mpv` to install the updated version.
