### ISSUE TITLE
brew services start sing-box couldn't start, the cmd in services plist lack of '--directory string' which used for  set working directory

### ISSUE THREAD

**Issue by Litchi2049** [Homebrew/homebrew-core#168942]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs sing-box
Error: No logs.

brew config
HOMEBREW_VERSION: 4.2.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0476c2e5e4f02b409084553896340b2f4ab3352e
Last commit: 7 days ago
Core tap JSON: 13 Apr 11:45 UTC
Core cask tap JSON: 13 Apr 11:45 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.4-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A

brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

After `brew install sing-box`, I want to use `brew services` to manage sing-box autostart/running in background.

 I find sing-box's plist in 

`/usr/local/Cellar/sing-box/1.8.11/homebrew.mxcl.sing-box.plist`

which inidicates `config.json` location

```plist
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/opt/sing-box/bin/sing-box</string>
		<string>run</string>
		<string>--config</string>
		<string>/usr/local/etc/sing-box/config.json</string>
	</array>
```

I create `/usr/local/etc/sing-box/config.json`

Test by direct run `sudo /usr/local/opt/sing-box/bin/sing-box run --config /usr/local/etc/sing-box/config.json` in directory `/usr/local/opt/sing-box/bin/`, success starts. Using sudo because of sing-box runs in tun mode

but when I use `sudo brew service start sing-box`, it wouldn't start sing-box.

### What happened (include all command output)?

The sing-box don't start in background, 
Run `sudo brew services` or `sudo brew info sing-box` will show error but without msg.

(below screenshot I add `-d` to show what happens)

![截屏2024-04-13 23 07 43](https://github.com/Homebrew/homebrew-core/assets/82750770/db2d08f3-0485-4b5f-9e7d-ab203e7e0d85)

### What did you expect to happen?

The sing-box start in background, and managed by brew services

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install sing-box

sudo brew services start sing-box
```

**Comment by Litchi2049** [comment]
I find `sing-box -h` output says: the flag `--directory` set working directory.

```bash
% sing-box -h
Usage:
  sing-box [command]

Available Commands:
  check       Check configuration
  completion  Generate the autocompletion script for the specified shell
  format      Format configuration
  generate    Generate things
  geoip       GeoIP tools
  geosite     Geosite tools
  help        Help about any command
  merge       Merge configurations
  rule-set    Manage rule sets
  run         Run service
  tools       Experimental tools
  version     Print current version of sing-box

Flags:
  -c, --config stringArray             set configuration file path
  -C, --config-directory stringArray   set configuration directory path
  -D, --directory string               set working directory
      --disable-color                  disable color output
  -h, --help                           help for sing-box

Use "sing-box [command] --help" for more information about a command.
```

Without this flag, sing-box will use current dir as working directory if using cmd start, however, when use plist, it causes sing-box couldn't find or create working dir

I add the flag to the plist:

![IMAGE 2024-04-13 21:28:03](https://github.com/Homebrew/homebrew-core/assets/82750770/427c1b7a-ff1d-46d4-acc0-bcef9a377744)

Then `sudo brew service restart sing-box` works as expect, success starts sing-box

And `sudo brew services` show sing-box started

**Comment by Litchi2049** [comment]
I don't know why I can't pass commit styles check... Someone can help?

**Comment by Litchi2049** [comment]
> I don't know why I can't pass commit styles check... Someone can help?

I found out: 1st the title is too long, 2nd after reopen PR, commits aren't squashed to one

**Comment by Jerry1144** [comment]
I think there's a relevant key for this, and macOS actually [recommends using it](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-104489).

From [service block methods](https://docs.brew.sh/Formula-Cookbook#service-block-methods) there is a `working_dir` method, which translates into `<key>WorkingDirectory</key><string>path/to/working/directory</string>`. Can you try using this and see if it works as intended?
```
<key>ProgramArguments</key>
<array>
  <string>/usr/local/opt/sing-box/bin/sing-box</string>
  <string>run</string>
  <string>--config</string>
  <string>/usr/local/etc/sing-box/config.ison</string>
</array>
<key>WorkingDirectory</key>
<string>/usr/local/etc/sing-box</string>
```

If it works, then an easier fix would be:
```
service do
  [...]
  working_dir etc/"sing-box"
end
```

**Comment by Litchi2049** [comment]
It works

```bash
litchi@LitchideMacBookAir 1.8.11 % launchctl list homebrew.mxcl.sing-box
{
	"LimitLoadToSessionType" = "Aqua";
	"Label" = "homebrew.mxcl.sing-box";
	"OnDemand" = false;
	"LastExitStatus" = 256;
	"Program" = "/usr/local/opt/sing-box/bin/sing-box";
	"ProgramArguments" = (
		"/usr/local/opt/sing-box/bin/sing-box";
		"run";
		"--config";
		"/usr/local/etc/sing-box/config.json";
	);
};
litchi@LitchideMacBookAir 1.8.11 % sudo brew services
Name     Status User File
sing-box none   root
litchi@LitchideMacBookAir 1.8.11 % cat homebrew.mxcl.sing-box.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.sing-box</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/opt/sing-box/bin/sing-box</string>
		<string>run</string>
		<string>--config</string>
		<string>/usr/local/etc/sing-box/config.json</string>
	</array>
        <key>WorkingDirectory</key>
        <string>/usr/local/etc/sing-box</string>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
litchi@LitchideMacBookAir 1.8.11 % sudo brew services restart sing-box
Warning: Taking root:admin ownership of some sing-box paths:
  /usr/local/Cellar/sing-box/1.8.11/bin
  /usr/local/Cellar/sing-box/1.8.11/bin/sing-box
  /usr/local/opt/sing-box
  /usr/local/opt/sing-box/bin
  /usr/local/var/homebrew/linked/sing-box
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Warning: sing-box must be run as non-root to start at user login!
==> Successfully started `sing-box` (label: homebrew.mxcl.sing-box)
litchi@LitchideMacBookAir 1.8.11 % launchctl list homebrew.mxcl.sing-box
{
	"LimitLoadToSessionType" = "Aqua";
	"Label" = "homebrew.mxcl.sing-box";
	"OnDemand" = false;
	"LastExitStatus" = 256;
	"PID" = 20795;
	"Program" = "/usr/local/opt/sing-box/bin/sing-box";
	"ProgramArguments" = (
		"/usr/local/opt/sing-box/bin/sing-box";
		"run";
		"--config";
		"/usr/local/etc/sing-box/config.json";
	);
};
litchi@LitchideMacBookAir 1.8.11 % sudo brew services
Name     Status  User File
sing-box started root /Library/LaunchDaemons/homebrew.mxcl.sing-box.plist
litchi@LitchideMacBookAir 1.8.11 %
```

**Comment by Litchi2049** [comment]
So, which one is better😂

**Comment by Jerry1144** [comment]
Well it has been merged so, if it ain't broke…
