### ISSUE TITLE
Node bottle download fails with 404 error

### ISSUE THREAD

**Issue by FdezRomero** [Homebrew/homebrew-core#16915]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/5a7b6c7acd74478ac5161cc55b855d59
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Install Node.js 8.4.0 (`node`) over Node.js 6 (`node@6`) with `brew install node`
- What happened (include command output)
Downloading the bottle file (https://homebrew.bintray.com/bottles/node-8.4.0.sierra.bottle.tar.gz) fails with error 404:
```
$ brew install node
==> Downloading https://homebrew.bintray.com/bottles/node-8.4.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "node"
Download failed: https://homebrew.bintray.com/bottles/node-8.4.0.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
^C
```
- What you expected to happen
Install the binaries from the bottle and not having to build from source.
- Step-by-step reproduction instructions (by running `brew install` commands)
1. `brew install node`

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by fulopm** [comment]
Also affects me.

**Comment by FdezRomero** [comment]
Retried now and the bottle file downloaded correctly. Closing.
