### ISSUE TITLE
pixz has wrong instructions for tar

### ISSUE THREAD

**Issue by MikeRich88** [Homebrew/homebrew-core#16944]
# Please always follow these steps:
- [Not applicable. This instruction is confusing. I don't know where to open this issue.] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [Not applicable] Ran `brew update` and retried your prior step?
- [Not applicable] Ran `brew doctor`, fixed all issues and retried your prior step?
- [Not applicable] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Not applicable] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

pixz 1.0.6 has wrong instructions for using tar. The given instructions are for GNU tar, and not for BSD tar.

    tar -Ipixz -cf output.tpxz dir  # Make tar use pixz automatically

I don't know what the policy is for stuff like this. Do you leave that alone? Or, do you change the instructions so they work for BSD tar? Or do you change the instructions so they work for GNU tar, taking into account that GNU tar would be installed as "gtar"?

If it's one of the latter two, then I would like to submit a pull request for that change, since it would seem like a good way to get my feet wet with submitting other pull requests in the future. Thanks!

**Comment by ilovezfs** [comment]
If it's an issue with the upstream documentation, please report it to them here: https://github.com/vasi/pixz/issues. It would be great to see this fixed so that the instructions work for BSD tar but that's not the sort of change we'd make in the formula with a patch.
