### ISSUE TITLE
library not found for -lzstd

### ISSUE THREAD

**Issue by edg-l** [Homebrew/homebrew-core#169512]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew gist-logs zstd    
Error: No logs.

❯ brew config              
HOMEBREW_VERSION: 4.2.18-71-g47c2c6d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 47c2c6deed929152720fd8a1acbe3decc317a6a1
Last commit: 3 hours ago
Core tap HEAD: 7df03e15df4467fd8744da2135f11284a6bf98ae
Core tap last commit: 2 weeks ago
Core tap JSON: 19 Apr 09:58 UTC
Core cask tap HEAD: 100ba3f51c14a5de914dc7a0d47c5090a55cf2a8
Core cask tap last commit: 2 weeks ago
Core cask tap JSON: 19 Apr 09:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false


❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to use the zstd library, (actually from llvm which uses it, but alone it doesnt work either)

### What happened (include all command output)?

```
❯ LDFLAGS="-L$(brew --prefix zstd)/lib" ld -lzstd --verbose 
ld: library not found for -lzstd
```

Apparently its there though:
```
❯ ls $(brew --prefix zstd)/lib
cmake                   libzstd.1.5.6.dylib     libzstd.1.dylib         libzstd.a               libzstd.dylib           pkgconfig
```

### What did you expect to happen?

Find the zstd library.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install zstd
LDFLAGS="-L$(brew --prefix zstd)/lib" ld -lzstd --verbose
# ld: library not found for -lzstd
```

**Comment by juanbono** [comment]
I just got the same error after running `brew upgrade`.
Do you have a workaround for this?

**Comment by carlocab** [comment]
`ld` does not use the `LDFLAGS` variable. You need to do
```
ld -L$(brew --prefix zstd)/lib -lzstd --verbose
```

**Comment by Anton-4** [comment]
Out of curiosity, why was `-L$(brew --prefix zstd)/lib` not required with the previous version?

**Comment by carlocab** [comment]
It's likely always been required, unless you've been using Homebrew on an Intel Mac (compilers usually check `/usr/local` by default without any prodding).
