### ISSUE TITLE
Python: setuptools-scm creates failed vendor build

### ISSUE THREAD

**Issue by LecrisUT** [Homebrew/homebrew-core#169501]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

PR is more relevant: https://github.com/Homebrew/homebrew-core/pull/164367

### Verification

(Build failure reproducible in the CI)

### What were you trying to do (and why)?

Package `tmt` as a testing framework.

### What happened (include all command output)?

When building `pint` as a dependency of `tmt`, it is trying to get `setuptools-scm` as a build dependency. The download succeeds, but for some reason, instead of detecting that setuptools-scm is `8.0.4` (version downloaded) it is reporting `1.31.0` (version of `tmt`) which breaks the build further on.

```
    Collecting setuptools_scm>=3.4.3 (from setuptools_scm[toml]>=3.4.3)
      Downloading setuptools-scm-8.0.4.tar.gz (74 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.3/74.3 kB 3.5 MB/s eta 0:00:00
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Installing backend dependencies: started
      Installing backend dependencies: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'done'
      WARNING: Requested setuptools_scm>=3.4.3 from https://files.pythonhosted.org/packages/eb/b1/0248705f10f6de5eefe7ff93e399f7192257b23df4d431d2f5680bb2778f/setuptools-scm-8.0.4.tar.gz (from setuptools_scm[toml]>=3.4.3), but installing version 1.31.0
    Discarding https://files.pythonhosted.org/packages/eb/b1/0248705f10f6de5eefe7ff93e399f7192257b23df4d431d2f5680bb2778f/setuptools-scm-8.0.4.tar.gz (from https://pypi.org/simple/setuptools-scm/) (requires-python:>=3.8): Requested setuptools_scm>=3.4.3 from https://files.pythonhosted.org/packages/eb/b1/0248705f10f6de5eefe7ff93e399f7192257b23df4d431d2f5680bb2778f/setuptools-scm-8.0.4.tar.gz (from setuptools_scm>=3.4.3) has inconsistent version: expected '8.0.4', but metadata has '1.31.0'
      Downloading setuptools-scm-8.0.3.tar.gz (72 kB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.8/72.8 kB 10.8 MB/s eta 0:00:00
      Installing build dependencies: started
      Installing build dependencies: finished with status 'error'
      error: subprocess-exited-with-error
```

### Step-by-step reproduction instructions (by running `brew` commands)

See formula in: https://github.com/Homebrew/homebrew-core/pull/164367

**Comment by carlocab** [comment]
Please see the section on dealing with CI failures here: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md

**Comment by LecrisUT** [comment]
@carlocab I have been trying to bring to attention for 1-2 months now. But I am opening a dedicated issue, because I expect this to happen to a bunch more packages in the process of dealing with #167905 and it would be good to bring together ideas instead of having discussions on each individual package.

**Comment by LecrisUT** [comment]
Resolved, I was setting an environment variable for all `SETUPTOOLS_SCM_PRETEND_VERSION` instead of `SETUPTOOLS_SCM_PRETEND_VERSION_FOR_TMT`
