### ISSUE TITLE
R tries to use GCC 7.1.0 even though its installed dependency is 7.2.0

### ISSUE THREAD

**Issue by forthrin** [Homebrew/homebrew-core#16952]
# Please always follow these steps:
- [V] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`?
- [V] Ran `brew update` and retried your prior step?
- [V] Ran `brew doctor`, fixed all issues and retried your prior step?
- [V] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/forthrin/40968b564ed2d256138acff32a404174

To help us debug your issue please explain:
- What you were trying to do (and why)

Install the "gss" package in R

- What happened (include command output)

```
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/gcc/x86_64-apple-darwin16.5.0/7.1.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/7.1.0/lib/gcc/7'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/gcc/x86_64-apple-darwin16.5.0/7.1.0'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/7.1.0/lib/gcc/7'
ld: library not found for -lgfortran
```

- What you expected to happen

I expected the package to compile without errors. The GCC version installed as a dependency of R is 7.2.0, but still R tries to use 7.1.0 for compiling, which fails. If 7.1.0 is a leftover specified in a configuration file, I couldn't find it in any of my R configuration files or my ENV.

```
~$ gfortran --version
GNU Fortran (Homebrew GCC 7.2.0) 7.2.0
```

- Step-by-step reproduction instructions (by running `brew install` commands)

Bash:

    brew install r
    r

Once inside R:

    install.packages("gss")

**Comment by ilovezfs** [comment]
@forthrin this should be fixed now if you brew update and brew upgrade. Thanks for reporting it!
