### ISSUE TITLE
You are using OS X 10.12. We do not provide support for this pre-release version.

### ISSUE THREAD

**Issue by jesse881025** [Homebrew/homebrew-core#16951]
OS X 10.12  上 执行 brew install go-delve/delve/delve
提示：
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
如何解决

**Comment by ilovezfs** [comment]
You need to update.

```
brew update-reset
```

**Comment by Young-Je** [comment]
brew update-reset is undoable.

**Comment by ilovezfs** [comment]
@Young-Je you need to open [a new issue](https://github.com/Homebrew/brew/issues/new) and fill out the entire template.
