### ISSUE TITLE
Mac OS Yosemite && Php71-phalcon === Failure.

### ISSUE THREAD

**Issue by HendrikEduard** [Homebrew/homebrew-core#16966]
**I did brew install php71 it claimed to be successful** - It was NOT.

I installed Php7.1 via curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1

**I did brew install php71-phalcon and the following text was produced:**

==> Pouring php71-phalcon-3.2.0.yosemite.bottle.tar.gz
==> Caveats
To finish installing phalcon for PHP 7.1:
  * /usr/local/etc/php/7.1/conf.d/ext-phalcon.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the phalcon module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run `php -i "(command-line 'phpinfo()')"`
  * - Look for the info on the phalcon module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php71-phalcon/3.2.0: 7 files, 3.7MB

Phpinfo() says there is no php71-phalcon installed.

**_This was an issue 3/4 years ago with PHP55-phalcon, I tried that (user) fix - still no  php71-phalcon installed.

Is there a solution yet??_**

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by HendrikEduard** [comment]
@MikeMcQuaid  Seriously??  Great way to avoid the issue!!

**Comment by MikeMcQuaid** [comment]
@HendrikEduard If you can't be bothered to read our instructions then I'm not sure why you expect us to help you.
