### ISSUE TITLE
incorrect jar reference in tika-server jar script

### ISSUE THREAD

**Issue by andreasnef** [Homebrew/homebrew-core#169663]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.18
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9edabf02ce29e54d0b717baa757cff38ad0c0e25
Last commit: 7 days ago
Core tap JSON: 21 Apr 11:29 UTC
Core cask tap JSON: 21 Apr 11:29 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to start the tika server

### What happened (include all command output)?

```
$ /opt/homebrew/bin/tika-rest-server 
Error: Unable to access jarfile /opt/homebrew/Cellar/tika/2.9.2/libexec/tika-server-2.9.2.jar
$
```

### What did you expect to happen?

Expecting the server to correctly start up with default settings.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install tika
$ $HOMEBREW_PREFIX/bin/tika-rest-server
```
```

**Comment by SMillerDev** [comment]
Is `/opt/homebrew/Cellar/tika/2.9.2/libexec/tika-server-2.9.2.jar` installed?

**Comment by andreasnef** [comment]
Hi @SMillerDev 
See my PR, there is a mismatch between the name of the jar file and the name used in the jar script.
