### ISSUE TITLE
Mac OS Yosemite && Php71-phalcon === Failure.

### ISSUE THREAD

**Issue by HendrikEduard** [Homebrew/homebrew-core#16967]
# Please always follow these steps:
- [X ] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X ] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**

> administrator$ brew gist-logs php71-phalcon
> Error: No logs.

**

- [X ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**administrator$ brew config**
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6eee85ea6724594fc29268aa8564cb0061e471b0
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 7.0 build 700
Git: 2.13.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /private/etc
Java: N/A
macOS: 10.10.5-x86_64
Xcode: N/A
CLT: 7.2.0.0.1.1447826929
X11: N/A

**administrator$ brew doctor**
Your system is ready to brew.

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why) _I was trying to install Phalcon - for development_
- What happened (include command output) please see above
- What you expected to happen I expecting to install php71-phalcon
- Step-by-step reproduction instructions (by running `brew install` commands)
brew update
brew doctor
brew install php71  <= it failed too I had to install it via curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1
brew install php71-phalcon
which resulted in:
==> Pouring php71-phalcon-3.2.0.yosemite.bottle.tar.gz ==> Caveats To finish installing phalcon for PHP 7.1:
	•	/usr/local/etc/php/7.1/conf.d/ext-phalcon.ini was created, do not forget to remove it upon extension removal.
	•	Validate installation via one of the following methods:
	•	
	•	Using PHP from a webserver:
	◦	Restart your webserver.
	◦	Write a PHP page that calls "phpinfo();"
	◦	Load it in a browser and look for the info on the phalcon module.
	◦	If you see it, you have been successful!
	•	
	•	Using PHP from the command line:
	◦	Run php -i "(command-line 'phpinfo()')"
	◦	Look for the info on the phalcon module.
	◦	If you see it, you have been successful! ==> Summary 🍺 /usr/local/Cellar/php71-phalcon/3.2.0: 7 files, 3.7MB

Phpinfo() says there is no php71-phalcon installed.

# New Formulae
To get a new formula into Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).

**Comment by HendrikEduard** [comment]
@MikeMcQuaid  Is this better??

**Comment by MikeMcQuaid** [comment]
@HendrikEduard Please report this to the Homebrew/php tap as the error output will have told you to, sorry.
