### ISSUE TITLE
Warning: Some installed kegs have no formulae! This means they were either deleted or installed manually. You should find replacements for the following formulae: python-flit-core

### ISSUE THREAD

**Issue by Danrancan** [Homebrew/homebrew-core#169769]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
When using brew upgrade command I get the following warning:

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-flit-core

brew gist-logs python-flit-core
Error: No logs.

brew config
HOMEBREW_VERSION: 4.2.19-4-gb0c4202
ORIGIN: https://github.com/Homebrew/brew
HEAD: b0c42029542b2ca63953841ee1f5c0c9349d2f97
Last commit: 3 hours ago
Core tap HEAD: 1ebef261e5b820b6d00f219c90a7e7c2362aa8a1
Core tap last commit: 2 hours ago
Core tap JSON: 22 Apr 15:38 UTC
Core cask tap HEAD: 575381df764d25c53115232bdc4b58631f7bc934
Core cask tap last commit: 16 minutes ago
Core cask tap JSON: 22 Apr 15:38 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.oFwOiSu5BB/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.44.0 => /usr/local/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  authy
  diskmaker-x
  meld
  nsregextester
  product-hunt

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-flit-core

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libgit2@1.6
  openssl@1.1
  python-typing-extensions

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfuse-t-1.0.36.dylib

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/fuse-t.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libfuse-t-1.0.36.a

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install llvm@17

Run `brew missing` for more details.


What does this mean and how can I fix it?
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew update

### What happened (include all command output)?

brew upgrade
==> Updating Homebrew...
Already up-to-date.
==> Upgrading 1 outdated package:
cloudflare-warp 2024.2.68.0,20240214.9 -> 2024.3.407.0,20240329.17
==> Upgrading cloudflare-warp
==> Downloading https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP.zip
Already downloaded: /Users/boo/Library/Caches/Homebrew/downloads/56519345fed42b501f885c5691d43053d4be85d4acb55d65e5ad16db2990147c--Cloudflare_WARP.zip
Warning: No checksum defined for cask 'cloudflare-warp', skipping verification.
==> Removing launchctl service com.cloudflare.1dot1dot1dot1.macos.loginlauncherapp
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)':
==> Running uninstall script /Applications/Cloudflare WARP.app/Contents/Resources/uninstall.sh
Proceeding with uninstallation.
Stopping 'Cloudflare WARP' GUI process.
Cloudflare WARP GUI process not running.
Deleting registration
sudo: warp-cli: command not found
Stopping and unloading CloudflareWARP daemon.
Stopped and unloaded 'CloudflareWARP' daemon process.
Removed daemon plist file.
Removing 'Cloudflare WARP' app folder.
Forgot package 'com.cloudflare.1dot1dot1dot1.macos' on '/'.
Removing settings and log files folder.
2024-04-22 10:37:53.555 defaults[13477:85173]
Domain (com.cloudflare.1dot1dot1dot1.macos) not found.
Defaults have not been changed.
Finished uninstallation!
==> Running installer for cloudflare-warp with sudo; the password may be necessary.
==> Purging files for version 2024.3.407.0,20240329.17 of Cask cloudflare-warp
==> Purging files for version 2024.3.407.0,20240329.17 of Cask cloudflare-warp
Warning: Reverting upgrade for Cask cloudflare-warp
==> Running installer for cloudflare-warp with sudo; the password may be necessary.
installer: Package name is Cloudflare WARP
installer: Installing at base path /
installer: The install was successful.
Error: cloudflare-warp: Could not find PKG source file 'Cloudflare_WARP_2024.3.407.0.pkg', found 'Cloudflare_WARP.pkg' instead.
==> Updating Homebrew...
Already up-to-date.
==> Upgrading 1 outdated package:
cloudflare-warp 2024.2.68.0,20240214.9 -> 2024.3.407.0,20240329.17
==> Upgrading cloudflare-warp
==> Downloading https://1111-releases.cloudflareclient.com/mac/Cloudflare_WARP.zip
Already downloaded: /Users/boo/Library/Caches/Homebrew/downloads/56519345fed42b501f885c5691d43053d4be85d4acb55d65e5ad16db2990147c--Cloudflare_WARP.zip
Warning: No checksum defined for cask 'cloudflare-warp', skipping verification.
==> Removing launchctl service com.cloudflare.1dot1dot1dot1.macos.loginlauncherapp
==> Running uninstall script /Applications/Cloudflare WARP.app/Contents/Resources/uninstall.sh
Proceeding with uninstallation.
Stopping 'Cloudflare WARP' GUI process.
'Cloudflare WARP' GUI process running with pid: 13515.
Killed 'Cloudflare WARP' GUI process.
Deleting registration
sudo: warp-cli: command not found
Stopping and unloading CloudflareWARP daemon.
Stopped and unloaded 'CloudflareWARP' daemon process.
Removed daemon plist file.
Removing 'Cloudflare WARP' app folder.
Forgot package 'com.cloudflare.1dot1dot1dot1.macos' on '/'.
Removing settings and log files folder.
2024-04-22 10:38:15.788 defaults[14712:88155]
Domain (com.cloudflare.1dot1dot1dot1.macos) not found.
Defaults have not been changed.
Finished uninstallation!
==> Running installer for cloudflare-warp with sudo; the password may be necessary.
==> Purging files for version 2024.3.407.0,20240329.17 of Cask cloudflare-warp
==> Purging files for version 2024.3.407.0,20240329.17 of Cask cloudflare-warp
Warning: Reverting upgrade for Cask cloudflare-warp
==> Running installer for cloudflare-warp with sudo; the password may be necessary.
installer: Package name is Cloudflare WARP
installer: Installing at base path /
installer: The install was successful.
Error: cloudflare-warp: Could not find PKG source file 'Cloudflare_WARP_2024.3.407.0.pkg', found 'Cloudflare_WARP.pkg' instead.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  authy
  diskmaker-x
  meld
  nsregextester
  product-hunt

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  python-flit-core

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  libgit2@1.6
  openssl@1.1
  python-typing-extensions

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libfuse-t-1.0.36.dylib

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/fuse-t.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libfuse-t-1.0.36.a

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install llvm@17

Run `brew missing` for more details.

### What did you expect to happen?

No errors or warnings

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by SMillerDev** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
