### ISSUE TITLE
Gitg failed to build on 10.11.5

### ISSUE THREAD

**Issue by moggers87** [Homebrew/homebrew-core#1701]
When I try to install Gitg, the install process complains about libgit2 not being thread-safe. A cursory examination of libgit2 shows that it _should_ already be thread-safe.

Console output:
> ==> Downloading https://download.gnome.org/sources/gitg/3.18/gitg-3.18.0.tar.xz
Already downloaded: /Users/mmolyneaux/Library/Caches/Homebrew/gitg-3.18.0.tar.xz
==> ./configure --disable-silent-rules --prefix=/Users/mmolyneaux/homebrew/Cellar/gitg/3.18.0 --disable-schemas-compile
Last 15 lines from /Users/mmolyneaux/Library/Logs/Homebrew/gitg/01.configure:
checking for CFPreferencesCopyAppValue... yes
checking for CFLocaleCopyCurrent... yes
checking for GNU gettext in libc... no
checking for iconv... yes
checking for working iconv... yes
checking how to link with libiconv... -liconv
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl -Wl,-framework -Wl,CoreFoundation
checking for sinf in -lm... yes
checking for pkg-config... /Users/mmolyneaux/homebrew/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBGITG... yes
checking for libgit2-glib threading support... configure: error: no, please recompile a threadsafe version of libgit2 (-DTHREADSAFE:BOOL=ON)

> READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by moggers87** [comment]
No need to be sorry :)

`brew doctor` warns me about the following things:

* brew is not installed to `/usr/local` (I'd rather not try as this is a client machine - not my own)
* A keg-only formular has been linked into the Cellar: `gettext` (unlinking it doesn't help)

gist-log output here: https://gist.github.com/anonymous/f0caf7e30e11eb3d28562093fbe6d0cd

**Comment by ilovezfs** [comment]
Yup, seeing the same error here. Simply rebuilding libgit2 and libgit2-glib doesn't seem to be sufficient either, even passing `-DTHREADSAFE:BOOL=ON` or `-DTHREADSAFE=ON` directly.

**Comment by ilovezfs** [comment]
Well this turns out to have a very peculiar cause, which I do not fully understand yet, but which is quite reproducible. If you rebuild `harfbuzz` with `icu4c 56.1`, then the build of `gitg` will succeed.

```
brew uninstall harfbuzz
brew uninstall icu4c
cd /usr/local/Library/Taps/homebrew/homebrew-core
git fetch --unshallow
git checkout 13c08a8c43c057812d23b755c4c8d5857c385893 -- Formula/icu4c.rb
brew install -s harfbuzz
brew install -s gitg
```
@UniqMartin I suspect this is somehow related to the issues you were addressing in https://github.com/Homebrew/homebrew-core/pull/221

**Comment by UniqMartin** [comment]
Yes, this seems to be related. Though the `webkitgtk` formula has no direct dependency on `icu4c` its `libwebkit2gtk-4.0.37.dylib` ends up linking to `libicui18n.56.dylib` (searching for `dyld` in the uploaded Gist shows this). We'll need to revision bump the `webkitgtk` formula (see #1790).

**Comment by ilovezfs** [comment]
I also observed a webitgtk build failure, so I think you're on to something there ;)

**Comment by UniqMartin** [comment]
Should hopefully be resolved after a `brew update` followed by a `brew upgrade`. Please let us know whether that's the case or if you're still experiencing problems. Thanks!

**Comment by ilovezfs** [comment]
Yep, fixed. Thanks for turning this around so quickly @UniqMartin. Is there anything that can be done other than "institutional memory" to make sure all affected revdeps and indirect revdeps of icu4c get revision bumps next time? I cannot tell if this a deficiency in `brew linkage`, missing explicit dependency declarations, or something else that might help.

@moggers87 In case you did follow the workaround above, you can reverse it, as follows:

```
cd /usr/local/Library/Taps/homebrew/homebrew-core
git reset --hard origin/master
brew update
brew uninstall -f icu4c harfbuzz gitg
brew install gitg
brew upgrade
```

**Comment by UniqMartin** [comment]
@ilovezfs My pleasure! I'm afraid we currently don't have a satisfying solution beyond “institutional memory”. The answer lies probably somewhere between making `brew uses --recursive` feasible again (and thus testing also indirect reverse dependencies for breakage) and a more Mach-O specific solution that keeps a database of all formulae/bottles and what the binaries in those bottles link to, such that once the set of binaries provided by a formula (like `icu4c`) changes it's easy to find out which formulae/bottles still reference a file that has been removed by a version bump.

Another workaround might be to instead declare all indirect dependencies explicitly with `depends_on`, but I don't think this will scale very well. The `webkitgtk` formula itself is a nice showcase for this discrepancy: Compare [these lines from `test do`](https://github.com/Homebrew/homebrew-core/blob/fe68b9a7833ad63dc473626d5fe908004e504b72/Formula/webkitgtk.rb#L61-L74) with [the formula's `depends_on` lines](https://github.com/Homebrew/homebrew-core/blob/fe68b9a7833ad63dc473626d5fe908004e504b72/Formula/webkitgtk.rb#L14-L18). 😜
