### ISSUE TITLE
llvm versioned formula does not build and install lldb

### ISSUE THREAD

**Issue by mizvekov** [Homebrew/homebrew-core#170122]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.19-94-gf381b2c
ORIGIN: https://github.com/Homebrew/brew
HEAD: f381b2cdf732abf28d72bcfdaf94b7fb9bc4bc32
Last commit: 11 hours ago
Core tap HEAD: 1efea3be1f662aa77ad0fc42371c695839a8eed1
Core tap last commit: 2 hours ago
Core tap JSON: 26 Apr 01:06 UTC
Core cask tap JSON: 26 Apr 01:06 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: dodeca-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.44.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.3
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I installed llvm@17 because vscode lldb plugin doesn't work with lldb 18.

### What happened (include all command output)?

llvm@17 installation misses lldb binary and libraries.

### What did you expect to happen?

llvm@17 should contain lldb.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install llvm@17
ls /opt/homebrew/Cellar/llvm@17/17.0.6/lib/
```

**Comment by kuznetsss** [comment]
`llvm-vscode` was renamed to `llvm-dap` in LLVM.
PR: https://github.com/llvm/llvm-project/pull/69264

**Comment by carlocab** [comment]
The VSCode LLDB plugin should work with LLVM 18 if you configure it to use `lldb-dap` instead of `lldb-vscode`.

If that doesn't work, please report this issue to the VSCode LLDB plugin maintainers first.

**Comment by mizvekov** [comment]
The fact lldb-18 didn't work with vscode is a bit of a background information / motivation on my part.

It's still strange this part of the formula is not built when versioned, when it did build for previous versions.

As an llvm developer and compiler engineer, it sure is interesting to be able to test and try lldb-17, just as much as we can with clang-17 and other llvm tools, in order to properly identify regressions and such.

**Comment by carlocab** [comment]
Might've been better to lead with that.

We didn't build LLDB for `llvm@17` to reduce the burden on our (limited, self-hosted) build infrastructure. And most users don't have as much need for older versions of LLDB.

But I'm happy to review a PR that returns LLDB to `llvm@17`'s `LLVM_ENABLE_PROJECTS` configuration.
