### ISSUE TITLE
Argyll CMS crashes with "dyld: Symbol not found: _clock_gettime" on Mac OS 10.11

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Homebrew/homebrew-core#17034]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Gist log: https://gist.github.com/DarwinAwardWinner/5e0e16abe1e20dfa8aa1d00fe8601c03

Argyll CMS installs just fine, but any program I attempt to run crashes with an error like this:

```
» dispcal
Calibrate a Display, Version 1.9.2
Author: Graeme W. Gill, licensed under the AGPL Version 3
Diagnostic: Too few arguments
usage: dispcal [options] outfile
 -v [n]               Verbose mode
 -d n                 Choose the display from the following list (default 1)
    1 = 'Color LCD, at 0, 0, width 1280, height 800 (Primary Display)'
 -dweb[:port]         Display via a web server at port (default 8080)
 -dcc[:n]             Display via n'th ChromeCast (default 1, ? for list)
 -c listno            Set communication port from the following list (default 1)
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/dispcal
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/dispcal
  Expected in: /usr/lib/libSystem.B.dylib

[1]    31383 trace trap  dispcal
```

From searching around, this seems to be related to some idiotic Apple policy of having the latest XCode only compile things for Mac OS 10.12, while I'm on 10.11. Apparently this can be worked around by setting some compiler flags, but Argyll uses an esoteric build system, so I have no idea how to do that.

**Comment by DarwinAwardWinner** [comment]
Note: `brew doctor` has some complaints, but they're not things I can easily fix, and I don't think they're related to this issue. Also, I get the same error when installing bottled or when compiling locally (I have XCode 8.2 installed).

**Comment by ilovezfs** [comment]
@DarwinAwardWinner this should now be fixed if you `brew update` and `brew upgrade`.

**Comment by DarwinAwardWinner** [comment]
I got the update, and it seems to be fixed. Thanks!
