### ISSUE TITLE
Non-checksummed download of ffmpeg formula file from an arbitrary URL is unsupported! `brew extract` or `brew cr

### ISSUE THREAD

**Issue by first567** [Homebrew/homebrew-core#170305]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Downloads % brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8af82980c55172cfc694d4058f442deac960103c/Formula/f/ffmpeg.rb
Error: Non-checksummed download of ffmpeg formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

download ffmpeg@6.1.1 

### What happened (include all command output)?

Non-checksummed download of ffmpeg formula file from an arbitrary URL is unsupported! `brew extract` or `brew create` and `brew tap-new` to create a formula file in a tap on GitHub instead.

### What did you expect to happen?

download successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8af82980c55172cfc694d4058f442deac960103c/Formula/f/ffmpeg.rb
```

**Comment by ZhongRuoyu** [comment]
The error message has told you exactly what to do.

If you simply need FFmpeg 6.1.1, run `brew install ffmpeg@6`.
