### ISSUE TITLE
PCSC-Lite configuration issue

### ISSUE THREAD

**Issue by rdluffy** [Homebrew/homebrew-core#170328]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.2.20
ORIGIN: https://github.com/Homebrew/brew
HEAD: c2ed3327c605c3e738359c9807b8f4cd6fec09eb
Last commit: 9 hours ago
Core tap JSON: 29 Apr 11:54 UTC
Core cask tap JSON: 29 Apr 11:55 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.0
Rosetta 2: false


Doctor : 
brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to use pcsc-lite daemon via a golang program.
I want to install pcsc-lite and launch pcscd -fd

### What happened (include all command output)?

brew install pcsc-lite
/opt/homebrew/opt/pcsc-lite/sbin/pcscd -fd

### What did you expect to happen?

00000000 [0x1d9511c40] debuglog.c:394:DebugLogSetLevel() debug level=debug
00000166 [0x1d9511c40] pcscdaemon.c:632:main() cannot create /run/pcscd: No such file or directory

According to (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247719) it is suggested to add the ipc path argument at configuration time.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pcsc-lite
/opt/homebrew/opt/pcsc-lite/sbin/pcscd -fd

Also if you launch : 
/opt/homebrew/opt/pcsc-lite/sbin/pcscd --version
You can see it : 
pcsc-lite version 2.1.0.
Copyright (C) 1999-2002 by David Corcoran <corcoran@musclecard.com>.
Copyright (C) 2001-2022 by Ludovic Rousseau <ludovic.rousseau@free.fr>.
Copyright (C) 2003-2004 by Damien Sauveron <sauveron@labri.fr>.
Report bugs to <pcsclite-muscle@lists.infradead.org>.
Enabled features: MacOS aarch64-apple-darwin23.4.0 serial usb usbdropdir=/opt/homebrew/Cellar/pcsc-lite/2.1.0/lib/pcsc/drivers 

[[[[[ipcdir=/run/pcscd]]]<---- wrong path

 filter configdir=/opt/homebrew/etc/reader.conf.d
MAX_READERNAME: 128, PCSCLITE_MAX_READERS_CONTEXTS: 16

also in the changelog
it appeas to be change from 2020
1.9.0: Ludovic Rousseau
14 June 2020
- SCardEndTransaction(): greatly improve performances (x300)
- tokenparser: accept any Unicode character in a reader name
- Use /run instead of /var/run by default
```

**Comment by carlocab** [comment]
This should have been fixed in 4962e18eb25306d2310c2426c14aea0add2ef180
