### ISSUE TITLE
OpenCV Version 2 Formula Unexpectedly Eliminated

### ISSUE THREAD

**Issue by jriesen** [Homebrew/homebrew-core#17038]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

(Logs seem unnecessary since the formula did not, strictly speaking, fail in any way.)

- What you were trying to do (and why)

Perform a regular update of Homebrew, because I like to keep my packages up to date.  Among other things, OpenCV 2.4.13.3 came out earlier this month.

- What happened (include command output)

It looks like the opencv formula (OpenCV version 2.4) and the opencv3 formulas were under homebrew/science.  opencv3 now redirects to homebrew/core (which is fine, you can migrate opencv into core, I don't care)... and the opencv formula is now aliased to opencv3.  This means that, as far as I can tell, there is no longer a OpenCV 2 package in Homebrew.

On the homebrew/science end, commit https://github.com/Homebrew/homebrew-science/commit/6c38af15f22ff24e2b398970bc4eb102bfa2b7d2 has eliminated opencv and opencv3, but in core https://github.com/Homebrew/homebrew-core/commit/f8ccef5cfea7db79efcedc05fe7fef14c8cc9572 only implements a OpenCV 3.3 formula under the name 'opencv'.

```
jriesen$ brew update

Updated 3 taps (caskroom/cask, homebrew/core, homebrew/science).
==> New Formulae
ampl-mp         clinfo          hypre           libmatio        opencv@2
clblas          datamash        igraph          libxlsxwriter   pcb
clfft           gmt             libbitcoin      nco             xtensor
==> Updated Formulae
acmetool                                 gspell
afl-fuzz                                 homebrew/science/sratoolkit
allure                                   imagemagick ✔
alot                                     imagemagick@6
angular-cli                              jfrog-cli-go
apache-arrow                             kotlin
audacious                                latexila
bash-snippets                            mariadb
convox                                   p11-kit ✔
expat ✔                                  pc6001vx
gdk-pixbuf ✔                             qcli
git-annex                                sccache
goad                                     squid
goofys                                   watchman
gopass                                   yle-dl
==> Renamed Formulae
gmt4 -> gmt@4                            opencv3 -> opencv ✔
==> Deleted Formulae
homebrew/science/opencv ✔
```

- What you expected to happen

To not be forcibly upgraded to OpenCV 3.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install opencv
```

...which installs OpenCV 3 instead of OpenCV 2 as it did previously.

**Comment by JCount** [comment]
The output you posted shows `opencv@2`, which is the new name for `homebrew/science`'s old `opencv`. `opencv3` did not match `homebrew/core`'s version naming scheme, so it was renamed to `opencv` and the formula for `OpenCV 2` was migrated to `opencv@2`.

**Comment by jriesen** [comment]
Ah!  Thank you.  I'm not used to the new @ version functionality yet, my mistake.  I was able to ```brew install opencv@2``` just fine and get OpenCV 2.4.13.2_2 again on my system.
