### ISSUE TITLE
Could not install openblas

### ISSUE THREAD

**Issue by Code-Hex** [Homebrew/homebrew-core#17077]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I tried to `brew install openblas` after twice `brew update`, but result is below.
```
Error: No available formula with the name "openblas"
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

Why can't i install the `openblas`?
Thank you.

**Comment by ilovezfs** [comment]
Where's your `brew config` output?

Also, what does `git -C $(brew --repo homebrew/core) status` say?

**Comment by Code-Hex** [comment]
@ilovezfs Oh...
I could check that my branch was not `master` by `git -C $(brew --repo homebrew/core) status`.

So, I fixed this problem by changed my branch.
Many Thanks!!
