### ISSUE TITLE
Missing write permissions for R files ("cannot update HTML package index")

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew-core#17098]
- [x] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? → *Sort of, it's already installed.*
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? → *Output is empty*
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? → *Formula didn't fail to install, no logs*
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### What was I trying to do

I updated some R packages via RStudio's interface (*Tools » Check for Package Updates*). It called this command, as shown in the RStudio console:

```
> install.packages("tibble")
Installing package into ‘/usr/local/lib/R/3.4/site-library’
...
> install.packages(c("boot", "Matrix", "mgcv"), lib="/usr/local/Cellar/r/3.4.1_2/lib/R/library")
...
```

### What happened

The packages installed fine, however, at the end of the installation log, it says:

```
Warning in install.packages :
  cannot create file '/usr/local/Cellar/r/3.4.1_2/lib/R/doc/html/packages.html', reason 'Permission denied'
Warning in install.packages :
  cannot update HTML package index
```

### What you expected to happen

I expected the files in this folder (and its subfolders) to be writable, and R being able to create the respective manual pages. However, they are not, as all the files are missing write permissions for my user:

```
$ ls -l /usr/local/Cellar/r/3.4.1_2/lib/R/doc
total 4648
-r--r--r--   1 werner  admin     957 Jun 30 09:04 AUTHORS
-r--r--r--   1 werner  admin    3283 Jun 30 09:04 BioC_mirrors.csv
-r--r--r--   1 werner  admin   18011 Jun 30 09:04 COPYING
-r--r--r--   1 werner  admin   23203 Jun 30 09:04 COPYRIGHTS
-r--r--r--   1 werner  admin   23199 Jun 30 09:04 CRAN_mirrors.csv
-r--r--r--   1 werner  admin  125806 Aug 22 11:24 FAQ
-r--r--r--   1 werner  admin    2530 Jun 30 09:04 KEYWORDS
-r--r--r--   1 werner  admin    3047 Jun 30 09:04 KEYWORDS.db
-r--r--r--   1 werner  admin  239862 Aug 22 11:24 NEWS
-r--r--r--   1 werner  admin   93568 Jun 30 09:04 NEWS.0
-r--r--r--   1 werner  admin  294277 Aug 22 11:24 NEWS.1
-r--r--r--   1 werner  admin  641818 Aug 22 11:24 NEWS.2
-r--r--r--   1 werner  admin  489588 Jun 30 09:04 NEWS.pdf
-r--r--r--   1 werner  admin  392496 Jun 30 09:04 NEWS.rds
-r--r--r--   1 werner  admin    1253 Jun 30 09:04 RESOURCES
-r--r--r--   1 werner  admin    3498 Jun 30 09:04 THANKS
drwxr-xr-x  19 werner  admin     646 Jun 30 09:04 html
drwxr-xr-x   3 werner  admin     102 Jun 30 09:04 manual
```

The same goes for files in the `html` directory.

I don't want to go ahead and `chmod u+w` everything – any ideas what the proper solution would be?

My `brew config` output:

```
HOMEBREW_VERSION: 1.3.1-71-g85fd43d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 85fd43d4fe595f73b9168360b4c15a43e1a9debf
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01b40c6161d835b1610d4324650e7d773cef8fab
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit dunno
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/werner/.rbenv/shims/ruby => /Users/werner/.rbenv/versions/2.4.1/bin/ruby
Java: 1.8.0_144, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 8.3.2.0.1.1492020469
X11: N/A
```

**Comment by fxcoudert** [comment]
I can reproduce that on a clean install of R. It is apparently due to the `lib="/usr/local/Cellar/r/3.4.1_2/lib/R/library"` argument passed on the second `install.packages`. If you don't force it to that directory, everything installs fine.

**Comment by slhck** [comment]
Thanks for checking. I didn't force it though (I guess that's what you meant, right?); R is doing that automatically for some reason when installing dependent packages.

So really, it should try to put everything in `/usr/local/lib` and let the symlinks there do the magic?

**Comment by fxcoudert** [comment]
Isn't it a problem in RStudio passing wrong arguments to R?

**Comment by slhck** [comment]
Hm, I guess so, but I don't understand why it chooses the correct directory the first time and then forces the other on that dependent install. I thought it was related to the way Homebrew creates those symlinks in `/usr/local` (which I assume would not be there when using the default R macOS installer … but I may be wrong).

If you want, we can close this and I'll post this in the RStudio community forum.

**Comment by kmiddleton** [comment]
I'm getting the same error with a fresh install of homebrew and R. 

`cannot create file '/usr/local/Cellar/r/3.4.1_2/lib/R/doc/html/packages.html', reason 'Permission denied'`

This is not RStudio-specific. Running R from the command line gives the same error.

**Comment by pooranis** [comment]
> Isn't it a problem in RStudio passing wrong arguments to R?

No, those packages that were updated are core packages in R.  They aren't installed to the site-library, but rather to the library folder.  RStudio is updating/installing the newer versions of those packages in their original folder (I think it's just running update.packages?  So this is consistent with using R outside of RStudio).

**Comment by apjanke** [comment]
I see the same permissions configuration in a fresh installation of R on my machine using Homebrew. (The regular files under `$PREFIX/lib/R/doc` are read-only, mode `-r--r--r--`.) That's probably in conflict with the assumptions of R's own package installer.

A vanilla, non-Homebrew installation of R from their distribution results in these files being user-writable instead of read-only. So this sounds like a Homebrew-specific issue, not RStudio, and this issue can be left open here.

I suspect it's because these docs are under `lib/` instead of `share/`, and `brew` locks down files installed under `lib/`, which R does not expect.

Sounds to me like `brew install R` should carve out an exception for the files under `lib/` that R expects to manage with its package installer, and make them user-writable.

**Comment by slhck** [comment]
This is still an issue – @fxcoudert, any idea if or how this could be solved? I think @apjanke's comment describes the actual issue.

**Comment by lazarillo** [comment]
Yes, this is still an issue, I think.  I came across the exact same problem, trying to install ggplot2 (and a few other non-core libraries) on a fresh install.

**Comment by kmiddleton** [comment]
Yes, this is still an issue.

**Comment by apjanke** [comment]
Yes, stale-bot, go away. This is a significant issue, and it's next on my to-do list, as soon as Real Work gives me enough time to address it.

**Comment by dlwatts** [comment]
Same, following the instructions found [here](https://stackoverflow.com/questions/8255663/how-to-apply-a-function-across-columns-of-data-frame) and getting errors for each section with Updating HTML index of packages in 'Library'
Errors are in the form of
`Updating HTML index of packages in '.Library'
Warning messages:
1:  In file.create(f.tg) :
    cannot create file '/usr/local/Cellar/r/3.4.2/lib/R/doc/hrml/packages.html', reason 'Permission denied'
2:  In make.packages.html(.Library) : cannot update HTML package index
`

**Comment by kfox** [comment]
Still a problem, but this terminal command was enough to fix it for me:
```bash
chmod -R u+w /usr/local/Cellar/r
```

**Comment by ilovezfs** [comment]
Happy to review a PR fixing this.

**Comment by slhck** [comment]
Why close this issue if it's not fixed yet?

I'm happy to write a PR to propose a fix, but I have no idea how to go about doing it without violating some Homebrew-specific assumptions – or in other words, just `chmod`ding everything.

As @apjanke said before:

> I suspect it's because these docs are under lib/ instead of share/, and brew locks down files installed under lib/, which R does not expect. Sounds to me like brew install R should carve out an exception for the files under lib/ that R expects to manage with its package installer, and make them user-writable.

Would this be a viable solution?

**Comment by ilovezfs** [comment]
>Why close this issue if it's not fixed yet?

We don't leave issues open that no one is actively working on.

>Would this be a viable solution?

Not really. But relocating stuff to `var` (which is actually `/usr/local/var` not `/usr/local/Cellar/r/3.4.2/var`) may work.

**Comment by ilovezfs** [comment]
Also, we may be able to use a reverse-symlink as in shared-mime-info:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/shared-mime-info.rb#L43-L48

**Comment by acgetchell** [comment]
Still an issue.

**Comment by ilovezfs** [comment]
PRs welcome.

**Comment by slhck** [comment]
I tried to figure out what would be needed but couldn't quite get there. Any reason this wouldn't work? (Just like the package library is symlinked, basically.)

```python
doc_library = HOMEBREW_PREFIX/"lib/R/#{short_version}/doc"
doc_library.mkpath
ln_s doc_library, lib/"R/doc"
```

**Comment by ilovezfs** [comment]
It might. We do that sort of thing in `pypy`

**Comment by adamaltmejd** [comment]
This is still a problem for me (using R 3.5.0).

**Comment by briankung** [comment]
Not an R user, but this is a problem for me, as well. I'm writing a formula for [flutter] and something is setting the permissions after install. My `#install` method is pretty simple:

```rb
  def install
    cp_r '.', prefix
    puts "After copy:"
    system('ls', '-al', prefix/'bin/cache')

    chmod_R '+w', prefix/'bin/cache'
    puts "After chmod_R:"
    system('ls', '-al', prefix/'bin/cache')
  end
```

The `ls` output after the initial `cp_r`:

```
==> ls -al /usr/local/Cellar/flutter/0.3.1-beta/bin/cache
total 11688
drwxr-xr-x  14 briankung  admin      448 May  2 10:54 .
drwxr-xr-x   6 briankung  admin      192 May  2 10:54 ..
-rw-r--r--   1 briankung  admin        0 May  2 10:54 .dartignore
drwxr-xr-x   5 briankung  admin      160 May  2 10:54 artifacts
drwxr-xr-x  10 briankung  admin      320 May  2 10:54 dart-sdk
drwxr-xr-x   2 briankung  admin       64 May  2 10:54 downloads
-rw-r--r--   1 briankung  admin       41 May  2 10:54 engine-dart-sdk.stamp
-rw-r--r--   1 briankung  admin       40 May  2 10:54 engine.stamp
-rw-r--r--   1 briankung  admin  5962618 May  2 10:54 flutter_tools.snapshot
-rw-r--r--   1 briankung  admin       41 May  2 10:54 flutter_tools.stamp
-rw-r--r--   1 briankung  admin       88 May  2 10:54 gradle_wrapper.stamp
-rw-r--r--   1 briankung  admin        0 May  2 10:54 lockfile
-rw-r--r--   1 briankung  admin       78 May  2 10:54 material_fonts.stamp
drwxr-xr-x   3 briankung  admin       96 May  2 10:54 pkg
```

Then after `chmod_R` (which just proves that I can change the permissions during the install phase - it turns out the permissions were fine to begin with):

```
==> ls -al /usr/local/Cellar/flutter/0.3.1-beta/bin/cache
total 11688
drwxrwxrwx  14 briankung  admin      448 May  2 10:54 .
drwxr-xr-x   6 briankung  admin      192 May  2 10:54 ..
-rw-rw-rw-   1 briankung  admin        0 May  2 10:54 .dartignore
drwxrwxrwx   5 briankung  admin      160 May  2 10:54 artifacts
drwxrwxrwx  10 briankung  admin      320 May  2 10:54 dart-sdk
drwxrwxrwx   2 briankung  admin       64 May  2 10:54 downloads
-rw-rw-rw-   1 briankung  admin       41 May  2 10:54 engine-dart-sdk.stamp
-rw-rw-rw-   1 briankung  admin       40 May  2 10:54 engine.stamp
-rw-rw-rw-   1 briankung  admin  5962618 May  2 10:54 flutter_tools.snapshot
-rw-rw-rw-   1 briankung  admin       41 May  2 10:54 flutter_tools.stamp
-rw-rw-rw-   1 briankung  admin       88 May  2 10:54 gradle_wrapper.stamp
-rw-rw-rw-   1 briankung  admin        0 May  2 10:54 lockfile
-rw-rw-rw-   1 briankung  admin       78 May  2 10:54 material_fonts.stamp
drwxrwxrwx   3 briankung  admin       96 May  2 10:54 pkg
```

...but after the installation, the permissions change once again:

```
total 11688
drwxrwxrwx  13 briankung  admin      416 May  2 10:55 .
drwxr-xr-x   6 briankung  admin      192 May  2 10:54 ..
-r--r--r--   1 briankung  admin        0 May  2 10:54 .dartignore
drwxrwxrwx   5 briankung  admin      160 May  2 10:54 artifacts
drwxrwxrwx  10 briankung  admin      320 May  2 10:54 dart-sdk
-r--r--r--   1 briankung  admin       41 May  2 10:54 engine-dart-sdk.stamp
-r--r--r--   1 briankung  admin       40 May  2 10:54 engine.stamp
-r--r--r--   1 briankung  admin  5962618 May  2 10:54 flutter_tools.snapshot
-r--r--r--   1 briankung  admin       41 May  2 10:54 flutter_tools.stamp
-r--r--r--   1 briankung  admin       88 May  2 10:54 gradle_wrapper.stamp
-r--r--r--   1 briankung  admin        0 May  2 10:54 lockfile
-r--r--r--   1 briankung  admin       78 May  2 10:54 material_fonts.stamp
drwxrwxrwx   3 briankung  admin       96 May  2 10:54 pkg
```

The permissions being set to read only are extremely annoying and it doesn't look like I can change the permissions during the installation.

[flutter]: https://flutter.io/
