### ISSUE TITLE
OpenCV option to build --with-java was removed

### ISSUE THREAD

**Issue by wbridewell** [Homebrew/homebrew-core#17106]
- [X] Confirmed this is a problem with `brew install`ing one, specific formula (not cask) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [Not Necessary] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Not Necessary] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The migration of OpenCV 3 formula from science to core removed almost all the build options associated with the library.

Given that OpenCV is commonly used with the JVM, it would be useful either to add the option or to build the bindings  by default. I would recommend having them built by default.

**Comment by fxcoudert** [comment]
Our analytics indicates that java bindings were used by ~3% of users, which is why they were removed:

```
install events in the last 100 days for homebrew/science/opencv3
=======================================================================================================================
   1 | homebrew/science/opencv3                                                                      | 10,563 |  18.81%
   2 | homebrew/science/opencv3 --HEAD --with-contrib --with-python3                                 |  5,729 |  10.20%
   3 | homebrew/science/opencv3 --with-contrib --without-python --with-python3                       |  4,791 |   8.53%
   4 | homebrew/science/opencv3 --with-contrib --with-python3                                        |  4,393 |   7.82%
   5 | homebrew/science/opencv3 --with-contrib                                                       |  4,235 |   7.54%
   6 | homebrew/science/opencv3 --with-python3                                                       |  3,043 |   5.42%
   7 | homebrew/science/opencv3 --HEAD --with-contrib                                                |  1,890 |   3.37%
   8 | homebrew/science/opencv3 --HEAD --with-contrib --with-java                                    |  1,348 |   2.40%
   9 | homebrew/science/opencv3 --without-python --with-python3                                      |  1,049 |   1.87%
  10 | homebrew/science/opencv3 --HEAD                                                               |  1,047 |   1.86%
  11 | homebrew/science/opencv3 --HEAD --with-contrib --without-python --with-python3                |    947 |   1.69%
  12 | homebrew/science/opencv3 --with-contrib --c++11 --with-python3                                |    631 |   1.12%
  13 | homebrew/science/opencv3 --HEAD --with-python3                                                |    485 |   0.86%
  14 | homebrew/science/opencv3 --with-contrib --with-examples --with-nonfree --with-qt --with-tbb - |    481 |   0.86%
  15 | homebrew/science/opencv3 --with-contrib --with-ffmpeg                                         |    379 |   0.67%
  16 | homebrew/science/opencv3 --with-contrib --with-qt --with-tbb --with-ffmpeg                    |    363 |   0.65%
  17 | homebrew/science/opencv3 --with-contrib --with-java                                           |    351 |   0.63%
  18 | homebrew/science/opencv3 --with-contrib --with-examples --with-nonfree --with-qt --with-tbb - |    335 |   0.60%
  19 | homebrew/science/opencv3 --with-ffmpeg                                                        |    325 |   0.58%
  20 | homebrew/science/opencv3 --with-tbb --with-ffmpeg --with-python3                              |    313 |   0.56%
```

Would building require Java to be installed, or can they build when Java is not present on the system? Does the resulting opencv run on a java-less system (except for the Java bindings)?

**Comment by JCount** [comment]
Building the Java wrapper(s) requires both Java and `ant` to be installed.

**Comment by wbridewell** [comment]
The resulting OpenCV does run on a Java-less system as long as you're not using the Java bindings.

**Comment by bertjan** [comment]
Ran into this today too; most tutorials for opencv on mac refer to the --with-java flag. At first, I didn't notice the warning that --with-java is an unknown flag, and couldn't figure out why the Java bindings weren't present in the opencv dir. Then, I saw the warning and landed on this issue. Edited the formula to set -DBUILD_opencv_java=ON and build from source with `brew install --build-from-source opencv` - that worked.

**Comment by wmarshall484** [comment]
Ran into this today since most online tutorials still indicate `--with-java` is valid.

Still haven't gotten it working. I did the following:
```
# opencv3 had been previously installed with the failed "--with-java" command
brew uninstall opencv3

# Change -DBUILD_opencv_java to ON
brew edit opencv3

# install opencv again
brew install opencv3
```
Should this be expected to generate the opencv jar files?

**Comment by bertjan** [comment]
I don't think that `brew install opencv3` builds from source.
I had to do a source build via `brew install --build-from-source opencv` to make brew honor the edited formula.

**Comment by jwr** [comment]
FWIW, this bit me today, and so far I have been unable to get the formula to build with java support. Still fighting. I wish this option hadn't been removed.

**Comment by ilovezfs** [comment]
Actually I think we should just require Java as a `=> :build` dependency and always build the jars if someone want to open a PR.

**Comment by yosuah** [comment]
I also into a problem related to the removed build options, though not the `--with-java` one (shall I make a separate issue for this?)

In OpenCV 3.2 if a GUI window was resized to a smaller size then the contents of that window were also automatically resized. In OpenCV 3.3 this is no longer the case on my computer, the contents were simply cropped and other advanced features also stopped working (e.g. zooming). After some digging I realised this is because the GUI framework used in 3.2 was Qt [1], but 3.3 is installed without Qt, and the previously available `--with-qt` option is not available anymore.

I could get back a working version of OpenCV by combining the suggestions above and editing the formula and installing using the `--build-from-source` option. 

```
brew uninstall opencv3
# Change -DBUILD_QT to ON. Additionally I had to set DBUILD_opencv_python2=OFF
# as I only have Python 3 on my system
brew edit opencv3
brew install --build-from-source opencv3
```

This means that the behaviour of the previous version (which was really useful!) silently broke after the upgrade, without a notification or an easy way to fix it. I appreciate the detailed usage analysis conducted by the Homebrew team, but I believe some of these options were actually useful and are referenced all around the web in tutorials, so I would suggest re-introducing them.

[1] I am not entirely sure if using Qt was the default behaviour or if I manually set that option when I installed the previous version.

**Comment by ilovezfs** [comment]
Well, one option would be to require Qt for everyone.

**Comment by sonvirgo** [comment]
@ilovezfs Manually build from source and a work-around [add missing header](https://stackoverflow.com/questions/39590741/fatal-error-qtkit-qtkit-h-file-not-found-when-i-build-opencv-on-mac), work for me. But lots of "camera droped frames"
Trying to install from brew but no java too

**Comment by ilovezfs** [comment]
@sonvirgo QTKit has been gone since Xcode 8.0

**Comment by sonvirgo** [comment]
@ilovezfs so the brew will install a AVFoundation version? Let's see if the code works without any modification :D

**Comment by ckampfe** [comment]
I was not able to get this working by flipping `-DBUILD_opencv_java` to `ON` and running `brew install --build-from-source opencv`

However, after adding `depends_on "ant"` above the other dependencies, it magically worked (again with `brew install --build-from-source opencv`).

**Comment by sonvirgo** [comment]
I use cmake-gui to test the config and it found ANT so it build ok

**Comment by ilovezfs** [comment]
I've removed all comments related to manually editing the formula.
