### ISSUE TITLE
`rust` should not bundle huge HTML documentation

### ISSUE THREAD

**Issue by kidonng** [Homebrew/homebrew-core#172042]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8378cc825d83acffd125fb0fec041793df378a57
Last commit: 4 days ago
Core tap JSON: 18 May 05:43 UTC
Core cask tap JSON: 18 May 05:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Understanding why `rust` weighs ~1 GB on my system. (Pardon for not being a real *bug*, but other issue templates are far more irrelevant)

### What happened (include all command output)?

```
$ du -sh /opt/homebrew/Cellar/rust
989M	/opt/homebrew/Cellar/rust
$ du -sh /opt/homebrew/Cellar/rust/1.78.0/share/doc/docs/html/
697M	/opt/homebrew/Cellar/rust/1.78.0/share/doc/docs/html/
```

### What did you expect to happen?

Does anybody actually prefer the bundled HTML docs instead of the online one? If it's a few megabytes it's fine to ship them as-is, but at this size `rust` should be an exception. I assume most of the time it just slows down installation and takes up precious disk space for every user who needs Rust.

For references, Debian has HTML docs available in [`rust-doc`](https://packages.debian.org/sid/rust-doc) as a separate package (as expected), Arch's [`rust`](https://archlinux.org/packages/extra/x86_64/rust/) package doesn't bundle the HTML docs (git log shows there used to be a separate `rust-docs` package, which is now gone probably for the same reasons above 🤷)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Run `brew install rust`
2. Notice how `rust` unexpectedly takes up huge space
```

**Comment by carlocab** [comment]
Thanks for opening an issue, but the output of `brew config` and `brew doctor` is mandatory for all issues opened here, whether this output is applicable or not.

We can reopen this once you've provided the required information.

**Comment by kidonng** [comment]
@carlocab I apologize for arrogantly thinking that these wouldn't matter for this specific issue (they pretty much would if I actually installed `rust` from somewhere else than the official formulae!)

I have provided the required info as requested.

**Comment by carlocab** [comment]
While I agree with you that it likely does not for your issue:

1. As a policy, we require it anyway, because many users don't have good judgement about what is and isn't relevant, unfortunately.
2. Using issues as historical references are more useful when they include as much information as possible about context.

**Comment by ZhongRuoyu** [comment]
`brew reinstall rust` will install the updated bottle without docs for you.
