### ISSUE TITLE
mpv formula is missing molten-vk as a dependency

### ISSUE THREAD

**Issue by rgaufman** [Homebrew/homebrew-core#172104]
Without molten-vk as a dependency, the vulkan-loader and vulkan-headers dependencies are useless and mpv cannot work in an optimal way and shows "VK_ERROR_INCOMPATIBLE_DRIVER" on start.

More details here: https://github.com/mpv-player/mpv/issues/14173

Simple solution is to add molten-vk as a dependency.

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install mpv
mpv filename

### What happened (include all command output)?

It installed but because of the missing dependency it was slow and glitchy

### What did you expect to happen?

For molten-vk to be installed automatically as a dependency

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install mpv
2. Playback a file with mpv -v filename and notice the VK_ERROR_INCOMPATIBLE_DRIVER errors and slow performance
```

**Comment by carlocab** [comment]
So, to be sure: this doesn't apply to installs of the stable version? Does this mean `molten-vk` will be required in a future release of MPV?

**Comment by rgaufman** [comment]
It applies to any natively running mpv, the "stable" cask version unfortunately isn't running natively but through rosetta.

**Comment by carlocab** [comment]
To be clear, I wasn't referring to the cask. So this is needed when you do
```
brew install --formula mpv
```
too? (Note: without `--HEAD`)

Is it only required on Apple Silicon? Or is it needed on Intel macOS too?

**Comment by rgaufman** [comment]
Ah, sorry, yes with mpv -v filename it throws the same errors: VK_ERROR_INCOMPATIBLE_DRIVER because molten-vk is missing.

**Comment by carlocab** [comment]
Ok, thanks. You mentioned the problem not appearing when running in Rosetta. Does that mean this dependency is not required on Intel macOS?

**Comment by rgaufman** [comment]
I checked with an mpv developer and he said molten-vk is recommended for any mpv user with a modern MacOS.
