### ISSUE TITLE
ncurses build depends on TERMINFO variable

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-core#172103]
Fails:

_(Running under Kitty terminal)_

```
❯ brew upgrade -s ncurses
[snip]
==> Upgrading 1 outdated package:
ncurses 6.4 -> 6.5
==> Fetching ncurses
[snip]
==> ./configure --enable-pc-files --with-pkg-config-libdir=/usr/local/Cellar/ncurses/6.5/lib/pkgconfig --enable-sigwinch --enable-symlinks --enable-widec --with-shared --with-cxx-s
 ==> make install
Last 15 lines from /Users/glen/Library/Logs/Homebrew/ncurses/02.make:

	You may see messages regarding extended capabilities, e.g., AX.
	These are extended terminal capabilities which are compiled
	using
		tic -x
	If you have ncurses 4.2 applications, you should read the INSTALL
	document, and install the terminfo without the -x option.

** creating ncurses++w.pc
touch pc-files
ncurses 6.5.20240427
"terminfo.tmp", line 24325, terminal 'v3220': /Applications/kitty.app/Contents/Resources/kitty/terminfo: permission denied (errno 1)
? tic could not build /Applications/kitty.app/Contents/Resources/kitty/terminfo
make[1]: *** [install.data] Error 1
make: *** [install] Error 2
```

Succeeds:

```
❯ env -u TERMINFO brew upgrade ncurses
[snip]
==> Upgrading ncurses
  6.4 -> 6.5 
==> ./configure --enable-pc-files --with-pkg-config-libdir=/usr/local/Cellar/ncurses/6.5/lib/pkgconfig --enable-sigwinch --enable-symlinks --enable-widec --with-shared --with-cxx-s

```

### Verification

- [ ] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [ ] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

upgrade ncurses

### What happened (include all command output)?

build failure

### What did you expect to happen?

build success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
env TERMINFO=/unwritable/path brew reinstall -s ncurses
```

**Comment by carlocab** [comment]
We don't provide support for source builds. If you'd like to see source build failures fixed, please either use the [Discussions page](https://github.com/orgs/Homebrew/discussions), or open a pull request. Please stop ignoring the warnings that `brew` shows you about not filing issues in Homebrew-owned repositories.

This is not specific to Homebrew. This would also happen if you tried to build `ncurses` from source outside Homebrew. Well, either that or it would write its terminfo database to the location specified by your `TERMINFO` variable, which is probably not what you want either. You can try reporting this upstream, but I suspect you are likely to get a WONTFIX in response.
