### ISSUE TITLE
bottled emacs exit with SIGSEGV when use built-in rust-ts-mode

### ISSUE THREAD

**Issue by Moroshima** [Homebrew/homebrew-core#172249]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config         
HOMEBREW_VERSION: 4.3.1
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: e0bc557e7b991cb23583679e1cf1c8a92b793aeb
Last commit: 21 hours ago
Core tap JSON: 21 May 04:16 UTC
Core cask tap JSON: 21 May 04:16 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_API_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles/api
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_BREW_GIT_REMOTE: https://mirrors.ustc.edu.cn/brew.git
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.ustc.edu.cn/homebrew-core.git
HOMEBREW_MAKE_JOBS: 8
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.1 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I tried to use emacs write rust code with emacs built-in treesit rust-ts-mode.

### What happened (include all command output)?

Emacs crashed with `Fatal error 11: Segmentation fault`.

### What did you expect to happen?

Emacs works well.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install emacs
emacs
```

and then input `M-x rus` to enable rust-ts-mode, it will crash.

**Comment by Moroshima** [comment]
But use `brew install --build-from-source emacs` will not trigger the segmentation fault, maybe the new version of **tree-sitter** package broke the treesit support of emacs built with an older version of **tree-sitter**?

**Comment by Lucartas** [comment]
Yep,
https://github.com/tree-sitter/tree-sitter/issues/3296

**Comment by carlocab** [comment]
If there's a command-line/scriptable way to trigger the crash, we can add it to the emacs `test` block to avoid breakage like this in the future.

I'm not an emacs user, so suggestions welcome.

In the meantime, the rebuild I triggered in #172484 will fix this.

**Comment by Moroshima** [comment]
It may be a bit difficult to reproduce the crash through a command-line or scriptable method. Tree-sitter can be used by many emacs major modes, but there is no generic way to test tree-sitter support.

The script below is just an example:

```ansi
echo "(add-hook 'emacs-startup-hook 'rust-ts-mode)" >> ~/.emacs.d/init.el
emacs
```

I do not think this is a reliable way to trigger the crash.

**Comment by Moroshima** [comment]
Sorry, I forgot to mention a crucial point: we need to first install the corresponding language grammar in Emacs, which appears to require an interactive process.

**Comment by carlocab** [comment]
I think this should be fixed now by
```
brew update && brew upgrade emacs
```
