### ISSUE TITLE
Remove "helm-docs" broken formula

### ISSUE THREAD

**Issue by ebuildy** [Homebrew/homebrew-core#172339]
**You are distributing a broken formula https://formulae.brew.sh/formula/helm-docs**

The build script is missing "main.version" to define the version in the go build, the build is green but the software is not working correctly / different than official releases.

Please remove this formula so people use the official formula from https://github.com/norwoodj/homebrew-tap/blob/master/Formula/helm-docs.rb .

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install helm-docs 

### What happened (include all command output)?

helm-docs binary from Homebrew is missing "version".

### What did you expect to happen?

The helm-docs binary from Homebrew should work like other binaries (Linux etc...)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install helm-docs

helm-docs --version
--> error
```
```

**Comment by p-linnane** [comment]
This will be fixed by https://github.com/Homebrew/homebrew-core/pull/172402. We do not remove formulae simply because they are also distributed elsewhere.

**Comment by SMillerDev** [comment]
See https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by ebuildy** [comment]
> This will be fixed by #172402. We do not remove formulae simply because they are also distributed elsewhere.

When they are distributed by the application creator, yes you should :-)

**Comment by SMillerDev** [comment]
> When they are distributed by the application creator, yes you should :-)

No, it looks like we're fine: https://github.com/norwoodj/helm-docs/blob/master/LICENSE

**Comment by p-linnane** [comment]
> When they are distributed by the application creator, yes you should :-)

What a grotesque notion. That's not how any of this works. I suggest you actually read the full text of GPLv3 instead of attempting to tell us how to run our project, which is doing just fine.

**Comment by p-linnane** [comment]
>Sure thanks you. I am just saying if software author is providing a tap that work whereas Homebrew version not, well, we should use the TAP.

We disagree. This fragments the Homebrew userbase and prevents users from using `brew search` and `brew install` without having to seek out separate taps on their own. Something in the main Homebrew/core repository can be immediately installed with `brew install`.

> Also about license, from [docs.brew.sh/Acceptable-Formulae](https://docs.brew.sh/Acceptable-Formulae) I can read
> 
> "Our policy is that formulae in the core tap ([homebrew/core](https://github.com/Homebrew/homebrew-core)) must be open-source with a [Debian Free Software Guidelines license](https://wiki.debian.org/DFSGLicenses)"
> 
> GPL license is fine isnit?

What I'm saying is that everything in Homebrew/core is licensed under a OSI-approved license. Meaning that we (and anyone else) are free to build and redistribute those projects. We [outright reject](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#upstream-taps) the notion of upstream "maintaining control" as antithetical to the values of open source.
