### ISSUE TITLE
tgenv should point to new github instead of old one

### ISSUE THREAD

**Issue by aramatev** [Homebrew/homebrew-core#172504]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

Currently brew install tgenv is using an old repo thats unmaintained and has issues with install.
There are a bunch of issues but this one specifically prevents installation of slightly older versions, https://github.com/cunymatthieu/tgenv/issues/21.  

We should use a new repo thats being maintained - https://github.com/tgenv/tgenv.
They have solved the issues that arent solved in the old repo.

This formula is using old and unmaintained repo ! https://github.com/Homebrew/homebrew-core/blob/master/Formula/t/tgenv.rb

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

they have bugs that are solved

### What happened (include all command output)?

no comment

### What did you expect to happen?

i expect new and maintained tgenv to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
no comment
```

**Comment by SMillerDev** [comment]
Search works for closed and open issues, and since there is nothing actionable for Homebrew here the issue can be closed.
