### ISSUE TITLE
sip formulae doesn't appear in pip3 list on sonoma

### ISSUE THREAD

**Issue by k61n** [Homebrew/homebrew-core#172701]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 4.3.1-52-gea5023a
ORIGIN: https://github.com/Homebrew/brew
HEAD: ea5023a4ad22a8cd2046e7f126fa2a39f83add05
Last commit: 27 minutes ago
Core tap HEAD: 6fd6f60a799501e7c093b695cc830a8708bd1c14
Core tap last commit: 3 weeks ago
Core tap JSON: 24 May 07:54 UTC
Core cask tap HEAD: 3e464f6aef0cdb7f0c48b3dca358a190339768d5
Core cask tap last commit: 3 weeks ago
Core cask tap JSON: 24 May 07:54 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.6aPQXb8LAU/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

% brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

sip is a python module
After upgrade to sonoma sip doesn't appear in pip3 list.
Reinstallation doesn't help.
As a result python3 doesn't see the module and I get `ModuleNotFoundError: No module named 'sipbuild'`

### What happened (include all command output)?
```shell
% brew install sip

% brew list
==> Formulae
ca-certificates	mpdecimal	openssl@3	python@3.12	readline	sip		sqlite		xz

 % pip3 --version
pip 24.0 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)

% pip3 list
Package Version
------- -------
pip     24.0
wheel   0.43.0

% python3
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sipbuild
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sipbuild'
```
### What did you expect to happen?

Expected sip to appear in pip3 list

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install sip
brew list
pip3 list
python3
import sipbuild
```

**Comment by branchvincent** [comment]
This is expected, it's installed in a venv and only the binaries are exposed to avoid polluting your global site packages and causing version conflicts.

If you need an importable version, we recommend using pip. Sorry!
