### ISSUE TITLE
opensearch-dashboards not being updated

### ISSUE THREAD

**Issue by najdanovicivan** [Homebrew/homebrew-core#172876]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bc557e7b991cb23583679e1cf1c8a92b793aeb
Last commit: 6 days ago
Core tap JSON: 26 May 13:23 UTC
Core cask tap JSON: 26 May 13:23 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to install latest version of opensearch-dashboards

### What happened (include all command output)?

Latest available version is 2.11.1 

### What did you expect to happen?

Latest available version should be 2.14.0

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
For some reason PR #172675 was not merged
```

**Comment by SMillerDev** [comment]
Please follow https://docs.brew.sh/Updating-Software-in-Homebrew
