### ISSUE TITLE
Make "Merge when ready" button always "work"

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-core#172999]
### What were you trying to do (and why)?

It would be nice if the Homebrew/homebrew-core "Merge when ready" button always "just worked" i.e. it would intelligently know to push bottle commits to the PR if necessary and then attempt another merge later.

### What happened (include all command output)?

People click the "merge when ready" button and it does the wrong thing e.g. not merge, not include bottles, etc.

### What did you expect to happen?

The "merge when ready" button always merges when ready.

### Step-by-step reproduction instructions (by running `brew` commands)

- Press "merge when ready"
- Sometimes: it does not do what you want/expect

**Comment by Bo98** [comment]
Alternative thought: given merging requires approval, and approving itself triggers an automerge, we could make a status check that only passes once the bottle commit is added (or otherwise doesn't require a bottle commit).

**Comment by carlocab** [comment]
> Alternative thought: given merging requires approval, and approving itself triggers an automerge, we could make a status check that only passes once the bottle commit is added (or otherwise doesn't require a bottle commit) so that adding to the merge queue doesn't happen until that point.

Yes, @MikeMcQuaid had suggested this previously.

It's not my preferred solution since it makes status indicators on the PR list less informative. i.e. We don't know if a PR has an ❌ because it's failing or because it just has no bottles yet.

**Comment by Bo98** [comment]
> > Alternative thought: given merging requires approval, and approving itself triggers an automerge, we could make a status check that only passes once the bottle commit is added (or otherwise doesn't require a bottle commit) so that adding to the merge queue doesn't happen until that point.
> 
> Yes, @MikeMcQuaid had suggested this previously.
> 
> It's not my preferred solution since it makes status indicators on the PR list less informative. i.e. We don't know if a PR has an ❌ because it's failing or because it just has no bottles yet.

I would probably make it 🟡 rather than ❌ but yeah point noted.

**Comment by carlocab** [comment]
Yea, 🟡 is a lot more reasonable, and I would no longer opposed to it if we used 🟡. It would take some getting used to, though (but I can live with it if that's what others wanted to do).

**Comment by MikeMcQuaid** [comment]
I think having "this PR is ready to be added to the merge queue" indicated with 🟢 rather than 🟡 or 🔴 is a much nicer experience.

**Comment by carlocab** [comment]
> I think having "this PR is ready to be added to the merge queue" indicated with 🟢 rather than 🟡 or 🔴 is a much nicer experience.

This is ready to go at https://github.com/Homebrew/homebrew-core/pull/173010. Just needs another review since I had to rework the approach.
