### ISSUE TITLE
docker-py not working with docker 7.0.0 in ansible formula

### ISSUE THREAD

**Issue by Silvio-Br** [Homebrew/homebrew-core#173012]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.2-16-g92adf6a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92adf6a0b71e59d3348c982d11e2560dc9317687
Last commit: 18 hours ago
Core tap JSON: 28 May 11:42 UTC
Core cask tap JSON: 28 May 11:42 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.1 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4.1-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I use a ansible playbook in order to launch docker containers.
The current requests 2.32.0 release (python) has introduced a breaking change for the Docker SDK for Python (https://github.com/docker/docker-py/pull/3257).
The Docker SDK for Python team has addressed this issue in their version 7.1.0 release (https://github.com/docker/docker-py/releases/tag/7.1.0).

Maybe if we upgrade the Docker SDK for Python to version 7.1.0 in the resource of the formula ansible instead of 7.0.0 the problem could be solved ?

### What happened (include all command output)?

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"}

### What did you expect to happen?

The container should have been started.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ansible
ansible-playbook <playbook>
```

**Comment by branchvincent** [comment]
Once #173099 is merged (and wait ~15min for the API to update), you can reinstall to pull in the fix: `brew reinstall ansible`
