### ISSUE TITLE
brew install --cask metasploit fail 404 on macOS

### ISSUE THREAD

**Issue by cchopin** [Homebrew/homebrew-core#173298]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew doctor
Your system is ready to brew.

brew config
HOMEBREW_VERSION: 4.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fdb0d53990d3e62e25325a6f89dbb769e84a530
Last commit: 4 days ago
Core tap JSON: 31 May 06:04 UTC
Core cask tap JSON: 31 May 06:04 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install --cask metasploit

### What happened (include all command output)?

==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/services and homebrew/core).
==> New Formulae
span-lite

You have 2 outdated formulae and 1 outdated cask installed.

==> Downloading https://osx.metasploit.com/metasploit-framework-6.4.8%2B20240504103023-1rapid7-1.x86_64.pkg
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-6.4.8%2B20240504103023-1rapid7-1.x86_64.pkg

### What did you expect to happen?

The URL used is not the correct one.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --cask metasploit
```

**Comment by carlocab** [comment]
You're probably looking for the [homebrew-cask](https://github.com/Homebrew/homebrew-cask) repository.

You can open a pull request there to update the cask: https://docs.brew.sh/Updating-Software-in-Homebrew
