### ISSUE TITLE
Missing R.framework in Brew installed  R 3.4.1_2 

### ISSUE THREAD

**Issue by akhst7** [Homebrew/homebrew-core#17340]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

No issues here. 

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Updating R from 3.1.4_1 to 3.1.4_2

- What happened (include command output)
Updating went without any issues. 

- What you expected to happen
As in precious R installation,  R.framework should be installed in /usr/local/Cellar/r/3.4.1_2/ but it is not there. 

`3.4.1_2 total 72

drwxr-xr-x  11 akihoji  admin   374B Aug 27 22:15 .
drwxr-xr-x   3 akihoji  admin   102B Aug 27 22:15 ..
drwxr-xr-x   3 akihoji  admin   102B Jun 30 03:04 .brew
-rw-r--r--   1 akihoji  admin    18K Jun 30 03:04 COPYING
-rw-r--r--   1 akihoji  admin   210B Jun 30 03:04 ChangeLog
-rw-r--r--   1 akihoji  admin   1.1K Aug 27 22:15 INSTALL_RECEIPT.json
-rw-r--r--   1 akihoji  admin   4.0K Jun 30 03:04 README
drwxr-xr-x   4 akihoji  admin   136B Aug 27 22:15 bin
drwxr-xr-x  12 akihoji  admin   408B Jun 30 03:04 include
drwxr-xr-x   7 akihoji  admin   238B Jun 30 03:04 lib
drwxr-xr-x   3 akihoji  admin   102B Jun 30 03:04 share`

- Step-by-step reproduction instructions (by running `brew install` commands)
I did brew reinstall gcc and r but I still don't see the R.framework.  

My gcc is `gcc (Homebrew GCC 7.2.0) 7.2.0`
My Brew config is

`HOMEBREW_VERSION: 1.3.1

ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6c570a16b646e4c9e2aea50c2d706f7e5f85052e
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.9 => /opt/X11`

My Mac config is
`ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29`

Any way to restore R.famework ?  

Thanks in advance. 

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by MikeMcQuaid** [comment]
> Any way to restore R.famework ?

No, sorry, we do not install the R.framework now.
