### ISSUE TITLE
mtr doesn't gives any report output if --port option is used with tcp/ udp. 

### ISSUE THREAD

**Issue by keshvic** [Homebrew/homebrew-core#173552]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
admin@test ~ % brew gist-logs mtr
Error: No logs.

admin@test ~ % brew config
HOMEBREW_VERSION: 4.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fdb0d53990d3e62e25325a6f89dbb769e84a530
Last commit: 7 days ago
Core tap JSON: 03 Jun 06:30 UTC
Core cask tap JSON: 03 Jun 06:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.1 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

admin@test ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

What?
I was trying to run mtr and see the output for tcp port 22. 
Why?
There seems to be network issue at my office vpn

### What happened (include all command output)?

I saw that when I run default tcp (port 80) or icmp or udp (port 33xxx) then it works fine but when I run with option for port with tcp or udp then, there is no output shown after command finishes running. 

<img width="408" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/40782126/89fc8a8d-6d37-42cd-a9f6-14fcfff6391a">

I also ran wireshark and I can see that packets were sent out by my mac but cli showed no report output.

![image](https://github.com/Homebrew/homebrew-core/assets/40782126/c5c863f3-4d66-467d-bc91-6b008936607b)

### What did you expect to happen?

I expect to see regular report output which shows the hops taken with loss and other network characteristics. See example below for working scenario with default port (80).

<img width="1208" alt="image" src="https://github.com/Homebrew/homebrew-core/assets/40782126/0d5458b1-8515-47f9-b10f-b72581840f74">

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew update
2. brew upgrade
3. brew install mtr
4. sudo mtr --tcp --port 22 -w -o "LSRD BAW MXI" 194.108.117.16
```

**Comment by SMillerDev** [comment]
Does it work if you compile that version from scratch?
