### ISSUE TITLE
Squid

### ISSUE THREAD

**Issue by costa** [Homebrew/homebrew-core#17369]
1. installed "successfully"
2. no `squid` (just `squidclient`)
3. what gives?

Thanks.

**Comment by DomT4** [comment]
> what gives?

You haven't checked `sbin`...

**Comment by JCount** [comment]
From the issue template:

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.

If you add the necessary information this issue may be reopened.
