### ISSUE TITLE
R 3.4.1_2 can not find out R_HOME 3.4/site-library

### ISSUE THREAD

**Issue by tkosaka1976** [Homebrew/homebrew-core#17372]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I upgrade r to 3.4.1_1 (from usual update)
- What happened (include command output)
probably R can not find "R_HOME" and warning came when install packages as 
error: error: cannot change directly ‘/usr/local/lib/R/WARNING: ignoring environment value of R_HOME 3.4/site-library’
- What you expected to happen
I'm not sure, but library should see from R console.
I set R_HOME as R_HOME=/usr/local/opt/r/lib/R

3.4.1_1 works well.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

If you add the necessary information this issue may be reopened.

**Comment by tkosaka1976** [comment]
I updated the comment.
R 3.4.1_2 still have problem in library.
I hope to know the solution.

**Comment by tkosaka1976** [comment]
if I install a package, it cannot be loaded.

~~~
> library("edgeR")
 要求されたパッケージ limma をロード中です
 エラー: package or namespace load failed for ‘edgeR’ in dyn.load(file, DLLpath = DLLpath, ...):
  共有ライブラリ '/usr/local/lib/R/3.4/site-library/edgeR/libs/edgeR.so' を読み込めません:
  dlopen(/usr/local/lib/R/3.4/site-library/edgeR/libs/edgeR.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/edgeR/libs/edgeR.so
  Reason: image not found
~~~

**Comment by ilovezfs** [comment]
The current version is /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib not /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib so that extension may just need to be reinstalled.

**Comment by tkosaka1976** [comment]
Thanks, @ilovezfs!
I noticed that the problem was not come from update but from requirement of update of Bioconductor.
I updated them, the problem was partly resolved.
Remaining things probably come from different portion.
I'll follow there https://github.com/Homebrew/homebrew-core/issues/17098

**Comment by tkosaka1976** [comment]
I have problem for installing "flowCore" and "mgcv" packages in R 3.4.2
This problem have continued from 3.4.1_1.
I believe that this problem come from libgfortran.
I already tested reinstall from source several times but it did not resolve the problem.

I'm using gcc installed via Homebrew 1.3.4-61-gec0d8fa.
