### ISSUE TITLE
package ccze not picked up by install command 

### ISSUE THREAD

**Issue by shehanster** [Homebrew/homebrew-core#174341]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜ brew install ccze
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################################################### 100.0%
Warning: No available formula with the name "ccze". Did you mean cctz?
==> Searching for similarly named formulae and casks...
==> Formulae
cctz

To install cctz, run:
  brew install cctz
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install package ccze
package is available - https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fccze

### What happened (include all command output)?

says its not available

### What did you expect to happen?

install ccze 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ccze
```

**Comment by bevanjkay** [comment]
`ccze` was removed from `homebrew-core` almost a year ago, as the repo had been archived upstream.
https://github.com/Homebrew/homebrew-core/pull/138155
