### ISSUE TITLE
rmlint.rb: Components for optional GUI are missing

### ISSUE THREAD

**Issue by workflowsguy** [Homebrew/homebrew-core#17434]
The `rmlint` utility should show a visual interface if called with `rmlint --gui`.

However, in the brew formula [https://github.com/Homebrew/homebrew-core/blob/master/Formula/rmlint.rb](url) the components for the GUI are missing.
Running the above command gives the error message:

`Failed to load shredder: No module named 'shredder' This might be due to a corrupted install; try reinstalling.`

I checked with the developers of the utility ([https://github.com/sahib/rmlint/issues/253](url)), but this is not a problem of the utility itself, but with the brew formula.

`brew gist-logs rmlint` gives no output.

`rmlint` is most recent version 2.6.1, `brew` is 1.3.1, OS X is 10.11.6

I hope I have provided all required information.

Thanks!

**Comment by ilovezfs** [comment]
We'd consider a pull request adding a `--with-gui` option, but any software that can build as CLI only without a GUI must do so by default. See https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#stuff-that-builds-a-gui-by-default-but-doesnt-have-to.

So we don't actually consider this a bug.

**Comment by workflowsguy** [comment]
I think there is a misunderstanding.
`rmlint` builds/runs as CLI by default. But it also has a GUI option. However, this option doesn't work.

This is the same as e.g. `TIKA`. This also runs as CLI by default, but can show a GUI when called with `--gui`.

Anyway, formula author @tomhoover and `rmlint` co-creator @sahib will look into this issue again.
