### ISSUE TITLE
Missing msbuild in dotnet@8.0.4 breaks SonarQube scanning in our build pipeline

### ISSUE THREAD

**Issue by SciPlayD** [Homebrew/homebrew-core#174429]
The `msbuild` binary, removed in the upgrade from dotnet < 8.0.4 to dotnet 8.0.4, breaks our local use of SonarQube's `dotnet-scanner`. Please restore`msbuild`.

**Comment by SMillerDev** [comment]
If you can get it to build we would love to review a pull request that restores it.
