### ISSUE TITLE
Linking with brewed apr and apr-util produces a ton of warnings

### ISSUE THREAD

**Issue by brainy** [Homebrew/homebrew-core#17445]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **NOT APPLICABLE**
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? **NOT APPLICABLE**

To help us debug your issue please explain:
- What you were trying to do (and why)

Building Subversion from source, using brewed `apr` and `apr-util` libraries.

- What happened (include command output)

Got an immense amount of warnings of the following kind:
```
libtool: warning: '/usr/local/opt/apr-util/libexec/lib/libaprutil-1.la' seems to be moved
libtool: warning: '/usr/local/opt/apr/libexec/lib/libapr-1.la' seems to be moved
```

- What you expected to happen

Did not expect these warnings. :)

- Step-by-step reproduction instructions (by running `brew install` commands)

Oof. Really? I don't think this is necessary, because:

# Discussion

The libtool library description file `/usr/local/opt/apr/libexec/lib/libapr-1.la`, which is a symlink to `/usr/local/Cellar/apr/1.6.2/libexec/lib/libapr-1.la`, contains the following property:
```
# Directory that this library needs to be installed in:
libdir='/usr/local/Cellar/apr/1.6.2/libexec/lib'
```

The `apr.rb` formula has the following string replacement:

```
    # No need for this to point to the versioned path.
    inreplace libexec/"bin/apr-1-config", libexec, opt_libexec
```

I *suspect* that the latter is wrong and we should either keep the versioned path in the `apr-1-config` file, or edit the `.la` file to contain the unversioned path, too. I'm not sure which is better/more correct, other than for APR-1.x and APR-Util-1.x, upgrades to newer versions are always backward ABI-compatible.

(The above analysis holds for `apr-util.rb` & co. as well.)

If someone points me towards the correct solution, I'll be happy to produce a pull request with a fix.

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/17535.

**Comment by RandomDSdevel** [comment]
@brainy:  Thanks for reporting this!  I noticed it, too, and should have reported it myself, but wasn't entirely sure whether the warning was worth getting distracted by (I don't often use Subversion, as I've really only ever used it via `git svn`, and then only sparsely and not frequently as of late, so I didn't feel it was worth getting bothered by at the time…  :sweat_smile:)
