### ISSUE TITLE
Running formulae `asitop` breaks `python@3.12` permissions

### ISSUE THREAD

**Issue by z4pf1sh** [Homebrew/homebrew-core#174620]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3f08c75e7b950d4340dab462f3e7f77e8093fa2b
Last commit: 4 days ago
Core tap JSON: 15 Jun 08:56 UTC
Core cask tap JSON: 15 Jun 08:56 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 3.3.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false

Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

In my recent brew update (with `brew update && brew upgrade`), `python@3.12` was among those updated.

Background info: I installed `asitop` days before and run it with `sudo` (as required), `python@3.12` was installed as a dependency.

### What happened (include all command output)?

During the cleanup process, I got this error:

> Error: Could not cleanup old kegs! Fix your permissions on: /opt/homebrew/Cellar/python@3.12/3.12.3

### What did you expect to happen?

The update and cleanup run just fine.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Use a Mac with Apple Silicon, and make sure Homebrew is up-to-date
2. Install `asitop`: `brew install asitop`
3. Run `asitop` with `sudo asitop`
4. Leave `asitop` with Ctrl-C
5. Run `find /opt/homebrew -exec stat -f "%Su %N" {} + | grep ^root`
6. You can find a lot of files with owner `root`, all of which are Python cache files generated when running `asitop` as root, like:

root /opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/curses/__pycache__
root /opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/curses/__pycache__/__init__.cpython-312.pyc
root /opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/curses/__pycache__/has_key.cpython-312.pyc
root /opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/__pycache__/tty.cpython-312.pyc
root /opt/homebrew/Cellar/asitop/0.0.24/libexec/lib/python3.12/site-packages/wcwidth/__pycache__
root /opt/homebrew/Cellar/asitop/0.0.24/libexec/lib/python3.12/site-packages/wcwidth/__pycache__/wcwidth.cpython-312.pyc
root /opt/homebrew/Cellar/asitop/0.0.24/libexec/lib/python3.12/site-packages/wcwidth/__pycache__/table_zero.cpython-312.pyc
root /opt/homebrew/Cellar/asitop/0.0.24/libexec/lib/python3.12/site-packages/wcwidth/__pycache__/table_vs16.cpython-312.pyc

Those files cannot be deleted during normal homebrew update and uninstall process. Therefore errors are generated while attempting to remove the old python@3.12 installation.

This could be an upstream bug that should not be fixed by Homebrew team, but just so you guys know, maybe could be helpful for other users affected.
```

**Comment by z4pf1sh** [comment]
Just a quick TL;DR for other guys encountering `Error: Could not cleanup old kegs! Fix your permissions on: /opt/homebrew/Cellar/python@3.12/3.12.3` while performing `brew upgrade`:

If you have previously run `asitop` with `sudo`, you could have run into this exact issue. Run `find /opt/homebrew -exec stat -f "%Su %N" {} + | grep ^root` shown above to make sure that all files with incorrect permissions are Python caches, then run this command to change their owners to you:

```sh
sudo chown -R $(whoami) $(brew --prefix)/Cellar/python@3.12
sudo chown -R $(whoami) $(brew --prefix)/Cellar/asitop
```

You should now be able to proceed with your previously failed command just fine.

**Comment by cho-m** [comment]
Could consider disabling .pyc generation given `sudo` is mandatory, e.g. env script using [`PYTHONDONTWRITEBYTECODE`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE) or appending `-B` to shebang.

**Comment by z4pf1sh** [comment]
> Could consider disabling .pyc generation given `sudo` is mandatory, e.g. env script using [`PYTHONDONTWRITEBYTECODE`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE) or appending `-B` to shebang.

Good idea, I've thought about this fix. It works well and prevents further issues.

However I do think that there could be a number of users out there already affected by the same issue and some of them could be confused about the error in updates. I think some interventions on Homebrew's side should help the confused users.

At least, we can write some caveats about the `asitop` formulae, something like:

```
Running `asitop` as root generates `.pyc` caches in your Python installation. Consider (adding environment variable or other fixes) to avoid this issue. If you are having troubles updating your Python formulae, try (permission fixes) to fix it.
```

Homebrew can also consider patching the original `asitop` formulae's script with a `-B` to the shbang as a temporary fix, sounds dirty to me, but a worthy tradeoff for avoiding the confusion of many users.
