### ISSUE TITLE
Homebrew curl HTTP/3 support

### ISSUE THREAD

**Issue by segevfiner** [Homebrew/homebrew-core#174686]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 4.3.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3f08c75e7b950d4340dab462f3e7f77e8093fa2b
Last commit: 5 days ago
Core tap JSON: 16 Jun 09:46 UTC
Core cask tap JSON: 16 Jun 09:46 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.2 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.2/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

```
❯ brew doctor
Your system is ready to brew.
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use Homebrew curl with http3.

### What happened (include all command output)?

```
❯ /opt/homebrew/opt/curl/bin/curl --http3
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information
```

### What did you expect to happen?

For this to work, as libnghttp2 is listed as a dependency in the formula. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install curl`
2. `/opt/homebrew/opt/curl/bin/curl --http3`
```

**Comment by carlocab** [comment]
`libnghttp2` is an HTTP/2 library.
```
❯ brew desc libnghttp2
libnghttp2: HTTP/2 C Library
```
Perhaps you were thinking of `libnghttp3`?
```
❯ brew desc libnghttp3
libnghttp3: HTTP/3 library written in C
```

**Comment by Bo98** [comment]
The missing bit is a QUIC library.

`ngtcp2` became stable recently but does not work with OpenSSL so would require using multiple SSL libraires (or switching the entire stack).
`openssl` itself does have QUIC support - but it's still considered experimental by curl. This may change in OpenSSL 3.4 in October if the API & performance improves.

**Comment by segevfiner** [comment]
Oh. Whooops. Confused nghttp2 and nghttp3. Yeah so we don't have an http/3 quic library... So you can close this if you don't want to have a ticket for tracking adding this support.

ngtcp2/nghttp3 are the only stable ones in cURL ATM. Using OpenSSL with it currently requires a fork of OpenSSL (quictls) with a different SONAME due to what I can only assume are politics leading to OpenSSL not wanting to support those low level APIs... Not sure if there is an option of using that fork only for ngtcp2, sounds risky having two versions loaded if not explicitly supported by the library...

The OpenSSL QUIC implementation will probably take a while until it is stable, and also stable in cURL...

**Comment by carlocab** [comment]
Closing this out for now because there isn't anything actionable for us in the near future. We can reopen this if/when there is something that can be done here.

**Comment by segevfiner** [comment]
@carlocab BTW Homebrew seems to have [quictls](https://formulae.brew.sh/formula/quictls) in the tap, it might be possible to simply build and depend cURL on that instead to get HTTP/2 support in.

**Comment by carlocab** [comment]
Switching `curl` away from `openssl` is not an option here -- that just risks breaking too many things.

**Comment by Bo98** [comment]
OpenSSL is getting pretty close to being able to offer HTTP/3 support here so is very likely the way forward here. We could maybe even enable it now, though performance will be much better come (potentially) OpenSSL 3.5.

**Comment by segevfiner** [comment]
Better be sure the builtin QUIC of OpenSSL is stable when used by cURL, hopefully sooner or later. 🤷‍♂️

**Comment by vszakats** [comment]
With OpenSSL 3.5 released with QUIC API support, and curl supporting it, the QUIC issue is resolved.

The remining missing bit is a libngtcp2 package in Homebrew.

**Comment by carlocab** [comment]
Nice! I'll have a look at packaging `libngtcp2`...

**Comment by carlocab** [comment]
Draft PR at #230515. The `test` block is WIP. Suggestions on the simplest function that can be tested quickly in a small C/C++ file would be appreciated.

**Comment by carlocab** [comment]
Should be added to curl in #230591, but needs some preliminary work.
