### ISSUE TITLE
mupdf-tools: Create symlink from mudraw to mutool

### ISSUE THREAD

**Issue by jbcpollak** [Homebrew/homebrew-core#1747]
I installed mupdf-tools looking for the mudraw command. `mutool` is installed, and you can access mudraw via `mutool draw`, but this is problematic for third party tools that expect `mudraw`.

This can be solved by creating a symlink from `mutool` to `mudraw`, which works great.

Can that be made a part of the official package?

**Comment by UniqMartin** [comment]
Thank you for this suggestion! The symlink should become available once the update #1753 is merged.
