### ISSUE TITLE
autopsy is not the latest version

### ISSUE THREAD

**Issue by merces** [Homebrew/homebrew-core#175053]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs autopsy
Error: No logs.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm trying to install autopsy [v4.21.0](https://www.autopsy.com/download/).

### What happened (include all command output)?

`brew install autopsy` runs fine, but it installs an old 2.24 version from SourceForge so, not the latest one.

### What did you expect to happen?

To install autopsy 4.21.0, not 2.24.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew info autopsy
```

**Comment by Bo98** [comment]
The formula needs completely rewritten in order for that to happen.

In [the previous attempt](https://github.com/Homebrew/homebrew-core/pull/156402), we noticed that:
* It's very difficult to make it build from source without it installing prebuilt binaries. This is a hard requirement for homebrew-core formulae and anybody updating the formula would need to address that
* Unlike the old version, the new version doesn't seem to work on Apple Silicon. A patch was sent upstream a while back but did not receive a response

Debian/Ubuntu also stopped updating at 2.24.

Unless someone finds a solution, it's perhaps unfortunately time to deprecate the formula.
