### ISSUE TITLE
xpdf download url changed and version was updated

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-core#17515]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

###

When trying to build xpdf formula the download of the source fails.

When connecting to the old old ftp address they left a readme file that says

> Xpdf downloads have moved to:
> http://www.xpdfreader.com/download.html

Thanks for updating to the correct url. 
This seems like the correct url to me
[http://www.xpdfreader.com/dl/xpdf-4.00.tar.gz](http://www.xpdfreader.com/dl/xpdf-4.00.tar.gz
)

The version and therefore the respective prebuilt bottles also seems outdated.

Thanks in advance.

**Comment by ilovezfs** [comment]
@tiiiecherle This should now be fixed via #17529. Thanks for reporting!
