### ISSUE TITLE
Mplayer shows movie on a quarter screen only on macOS

### ISSUE THREAD

**Issue by aihua** [Homebrew/homebrew-core#175476]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.7
HEAD: 43eaeca50fe3b6c755f3fc9bc6f43669e0db1039
Last commit: 29 hours ago
Core tap JSON: 25 Jun 11:52 UTC
Core cask tap JSON: 25 Jun 11:52 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Watching video with mplayer on macOS  at  display’s resolution to `1920*1080` with 4K (`3840*2160`) monitor.

### What happened (include all command output)?

```shell
MPlayer 1.5-15.0.0 (C) 2000-2022 MPlayer Team
Can't init Apple Remote.

libavformat version 59.17.102 (internal)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1012e4410]Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang und
VIDEO:  [H264]  1280x720  24bpp  30.000 fps   81.4 kbps ( 9.9 kbyte/s)
[gl] using extended formats. Use -vo gl:nomanyfmts if playback fails.
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 59.21.100 (internal)
Selected video codec: [ffh264] vfm: ffmpeg (FFmpeg H.264)
==========================================================================
Clip info:
 major_brand: isom
 minor_version: 512
 compatible_brands: isomiso2avc1mp41
 comment: vid:v0200fg10000ce2rq9bc77ucgufpqo7g
 encoder: Lavf58.76.100
Load subtitles in ./
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
[aac @ 0x101326a20]Multiple frames in a packet.
AUDIO: 44100 Hz, 2 ch, floatle, 128.0 kbit/4.54% (ratio: 16000->352800)
Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))
==========================================================================
AO: [coreaudio] 44100Hz 2ch floatle (4 bytes per sample)
Starting playback...
[aac @ 0x101326a20]channel element 0.0 is not allocated
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [gl_nosw] 1280x720 => 1280x720 Planar YV12 
A:  18.9 V:  18.9 A-V:  0.009 ct: -0.044   0/  0  5%  2%  0.3% 4 0                                                                  

Exiting... (Quit)
```

### What did you expect to happen?

Mplayer shows movie on a full window/screen at  display’s resolution to `1920*1080` with 4K (`3840*2160`) monitor.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1) mplayer example.avi
2) Mplayer shows movie on a quarter screen only as: 
https://apple.stackexchange.com/questions/438169/mplayer-shows-movie-on-a-quarter-screen-only
3) while ffplay example.avi , the movie is shown on full screen.
```
 [https://apple.stackexchange.com/questions/438169/mplayer-shows-movie-on-a-quarter-screen-only](https://apple.stackexchange.com/questions/438169/mplayer-shows-movie-on-a-quarter-screen-only)

**Comment by SMillerDev** [comment]
Does this also happen when you build it outside of brew?

**Comment by aihua** [comment]
> Does this also happen when you build it outside of brew?

I have not build it outside of brew.
BTW, when Change my Mac display’s resolution to `3840*2160`, then `mplayer example.avi`, it shows the movie on a full screen. When change the Mac  display’s resolution to `1920*1080`,  then `mplayer example.avi`, it shows the movie on a quarter screen.

Screenshot at display’s resolution to 3840*2160, it is full screen: 
![Screenshot at display’s resolution to 3840*2160, it is full screen](https://github.com/Homebrew/homebrew-core/assets/919831/98747642-0fa0-4874-b608-f8db38f8be5e)

Screenshot at display’s resolution to 1920*1080, it is quarter screen:
![Screenshot at display’s resolution to 1920*1080, it is quarter screen](https://github.com/Homebrew/homebrew-core/assets/919831/d3fc99ad-9f83-4968-bca8-de0865a682fb)

**Comment by SMillerDev** [comment]
Really seems like something you should report to the developers so they can have a look.

**Comment by cho-m** [comment]
I'm guessing it is related to upstream https://trac.mplayerhq.hu/ticket/2383. If someone wants, they can try backporting fix, test that it works on Intel machine, and submit PR. Otherwise, will need to wait until upstream does a 1.6 release or try building formula's HEAD.

**Comment by cho-m** [comment]
I applied a fix current release that worked for me (reproduced and tested via Rosetta). 

Run `brew reinstall mplayer` to get the new bottle.
