### ISSUE TITLE
curl install issue 10.7.5 one or more libs available at link-time are not used at link-time

### ISSUE THREAD

**Issue by bearachute** [Homebrew/homebrew-core#17567]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Trying to install more recent version of curl on OSX 10.7.5, fails with the command listed in the subject. 

brew doctor:
Admins-MacBook-5:curl-7.55.1 admin$ brew config
HOMEBREW_VERSION: 1.3.1-4457-g3bb9871
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3bb98714afd42dc0d62da2e09e07c79e168054d9
Last commit: 28 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e45386e283911db18e69aeefbc69d6608343e555
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 4.2 build 425
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65-b14-462
macOS: 10.7.5-i386
Xcode: 4.6.3
CLT: 4.6.0.0.1.1365549073
X11: 2.6.3 => /usr/X11

brew doctor:
Admins-MacBook-5:curl-7.55.1 admin$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The system curl on 10.8 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.

We recommend you:
  brew install curl

and no brew gist logs

I don't understand the problem with this, there aren't any config options to make it actually install, at least that I've noticed and short of editing the brew file I don't know else to do. 

This is actually kind of sad, because I really need this mac to work, for project reasons and I can't even get curl to work probably, or install or update.

I'm sorry I don't have 2000+ bucks to shell out to get a new mac, Mine is an early 2008 model, it works great otherwise but I'd like to update Ruby, most of everything I've installed otherwise has worked like a charm, but curl is the bane of my existence.

It's also kind of irresponsible, to tell people who are newer or new to macs, or even homebrew that they are SOL and need to just "pony up for a new Mac". Are you buying? I could barely afford this one, and it's 10 years old.

It would just be really nice if this would somehow work, if anyone has any info or has gotten this to work on 10.7.5 please help. It isn't a total dealbreaker but can't do much of anything if the computer refuses to install things.

Thanks

**Comment by ilovezfs** [comment]
@bearachute Can you see if you can get it to install using https://github.com/mistydemeo/tigerbrew ?

**Comment by bearachute** [comment]
no, tigerbrew isn't any different, accept curl just refuses to even install anything throwing up a curl (35) error, when i try to update curl itself. 

==> Installing curl
==> Downloading https://curl.haxx.se/download/curl-7.50.3.tar.bz2

curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failed to download resource "curl"
Download failed: https://curl.haxx.se/download/curl-7.50.3.tar.bz2

**Comment by ilovezfs** [comment]
@bearachute ah, that's because the http mirror from the Homebrew formula hasn't been merged into Tigerbrew yet. You just need to edit the curl formula and add [this line](https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl.rb#L5) to it.

**Comment by bearachute** [comment]
I added the line, however now i'm getting a sha mismatch whenever I download curl

Error: SHA256 mismatch
Expected: 8c153f282bbe482495214654cdcd4182
Actual: e5b1a92ed3b0c11f149886458fa063419500819f1610c020d62f25b8e4b16cfb
Archive: /Users/admin/Library/Caches/Homebrew/curl-7.50.3.tar.bz2
To retry an incomplete download, remove the file above.

**Comment by ilovezfs** [comment]
@bearachute. Right, you need to match the same version, or change the sha256. :)

**Comment by bearachute** [comment]
haha i'm kind of new at this so i don't know exactly what i'm doing, i've tried changing the sha, and it still reports mismatch, do i change the sha in the curl.rb? it seems like when i change it it doesn't reflect what i'm changing

**Comment by ilovezfs** [comment]
Just replace the whole section at the top with
```
  url "https://curl.haxx.se/download/curl-7.55.1.tar.bz2"
  mirror "http://curl.askapache.com/download/curl-7.55.1.tar.bz2"
  sha256 "e5b1a92ed3b0c11f149886458fa063419500819f1610c020d62f25b8e4b16cfb"
```

**Comment by bearachute** [comment]
i just did that, ran into the problems with link time libs not available that i had with homebrew, my system must be borked or something?

configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lldap -lz

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting

These open issues may also help:
brew install curl fails https://github.com/mistydemeo/tigerbrew/issues/506
curl-ca-bundle upgrade issue (PPC 10.5.8) https://github.com/mistydemeo/tigerbrew/issues/511

**Comment by ilovezfs** [comment]
OK, if you replace the top block with
```
  url "https://curl.haxx.se/download/curl-7.50.3.tar.bz2"
  mirror "http://curl.askapache.com/download/curl-7.50.3.tar.bz2"
  sha256 "7b7347d976661d02c84a1f4d6daf40dee377efdc45b9e2c77dedb8acf140d8ec"
```
does it fail the same way?

**Comment by bearachute** [comment]
ok that time it worked, however it's still showing the old executable and i have the path the right way, if i closed by terminal would it change that?

**Comment by ilovezfs** [comment]
>ok that time it worked

Hmm... that is interesting.

>it's still showing the old executable and i have the path the right way, if i closed by terminal would it change that

You'll need to add `export PATH=/usr/local/opt/curl/bin:$PATH` to your profile.

**Comment by ilovezfs** [comment]
OK, can you try switching back to Homebrew now?

And try this diff:
```
diff --git a/Formula/curl.rb b/Formula/curl.rb
index 3942c12d1d..91f69d1e33 100644
--- a/Formula/curl.rb
+++ b/Formula/curl.rb
@@ -47,6 +47,8 @@ class Curl < Formula
       --disable-dependency-tracking
       --disable-silent-rules
       --prefix=#{prefix}
+      --disable-ldap
+      --disable-ldaps
     ]
 
     # cURL has a new firm desire to find ssl with PKG_CONFIG_PATH instead of using
```

**Comment by bearachute** [comment]
i got curl running nicely, now i have another issue but i'll search before i post

thanks a lot for your help

**Comment by ilovezfs** [comment]
>i got curl running nicely, now i have another issue but i'll search before i post

Under Homebrew or Tigerbrew? And which version of curl?

>thanks a lot for your help

You're welcome.

**Comment by bearachute** [comment]
tigerbrew and i believe it's 7.50.3 curl

**Comment by ilovezfs** [comment]
OK cool. Let me know if you want help getting 7.55.1 working under Homebrew at some point.
