### ISSUE TITLE
OpenJDK `release` file is modified by Homebrew

### ISSUE THREAD

**Issue by yopox** [Homebrew/homebrew-core#175878]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
╰─➤  brew config
HOMEBREW_VERSION: 4.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 43eaeca50fe3b6c755f3fc9bc6f43669e0db1039
Last commit: 4 days ago
Core tap JSON: 28 Jun 10:01 UTC
Core cask tap JSON: 28 Jun 10:01 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

```
╰─➤  brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Hi, I am a developer for IntelliJ IDEA and I am working on the detection of JDKs installed with Homebrew.

We are using the `Contents/Home/release` file to parse JDK vendor information. Homebrew installation removes this specific information and replace it with "Homebrew".

Is there any reason why the `release` file has to be modified? If `IMPLEMENTOR` must be set to "Homebrew", is it possible to add a property that would point to the origin of the JDK? For instance GraalVM has `GRAALVM_VERSION` as an additional property.

### What happened (include all command output)?

Here is the `release` file from the distribution installed with Homebrew (`openjdk@17`).
`/opt/homebrew/Cellar/openjdk@17/17.0.11/libexec/openjdk.jdk/Contents/Home/release`:

```
IMPLEMENTOR="Homebrew"
IMPLEMENTOR_VERSION="Homebrew"
JAVA_RUNTIME_VERSION="17.0.11+0"
JAVA_VERSION="17.0.11"
[...]
```

### What did you expect to happen?

`release` file from OpenJDK downloaded from Oracle website:

```
IMPLEMENTOR="Oracle Corporation"
JAVA_VERSION="17.0.2"
JAVA_VERSION_DATE="2022-01-18"
[...]
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openjdk@17
cat /opt/homebrew/Cellar/openjdk@17/17.0.11/libexec/openjdk.jdk/Contents/Home/release
```

**Comment by SMillerDev** [comment]
> Is there any reason why the release file has to be modified? If IMPLEMENTOR must be set to "Homebrew", is it possible to add a property that would point to the origin of the JDK?

The origin _is_ Homebrew, all formulae are build from source. It's a build of OpenJDK, but it is my understanding all JDKs are.

**Comment by yopox** [comment]
Is it then correct to refer to this JDK as "Homebrew OpenJDK"? This would close the issue.
