### ISSUE TITLE
Change all node formulas to use Homebrew-installed node rather than the first node on the path

### ISSUE THREAD

**Issue by ctaintor** [Homebrew/homebrew-core#176257]
This is in response to the [discussion](https://github.com/Homebrew/brew/pull/17539) on updating the documentation for Node for Formula Authors. @MikeMcQuaid suggested opening a discussion here.

To summarize - _most_ node formulas in `homebrew-core` add a binary by symlinking, likely because this is how the [current documentation](https://docs.brew.sh/Node-for-Formula-Authors) suggests it be done. However, using a symlink will mean that the first `node` binary on your `PATH` will be used and this may not be the one which was installed by the formula via `depends_on "node"`. This is problematic if the binary installed by the formula requires newer versions of node or if the architecture of the Homebrew-node differs from that which is installed on the PATH (e.g. arm64 vs x86, which is what made me realize this problem).

To fix this, it is suggested that all formulas which include `require "language/node"` and have a `depends_on "node"` be changed, removing something like `bin.install_symlink Dir["#{libexec}/bin/*"]` and instead doing something like:

```ruby
env = { PATH: "#{HOMEBREW_PREFIX/"bin"}:$PATH" }
(bin/"foo").write_env_script "#{libexec}/bin/foo", env
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Consistently run a CLI which was installed by a homebrew node formula.

### What happened (include all command output)?

In my case, a user was getting an error which was related to npm not having installed an x86 version of a dependency. The reason they were getting this error is because they had an x86 version of node on their PATH while the Homebrew formula had installed and used an arm64 version of node, thus meaning that npm had only installed the arm64 version of a dependency.

### What did you expect to happen?

I expected that the formula would use the Homebrew-installed node and not fail due to something the user had installed elsewhere.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
* install any of the homebrew node formulas
* add a binary named `node` to be in your PATH before Homebrew's path
* note that when you call the homebrew formula's CLI, it will try to execute the binary you added, not homebrew's node
```

**Comment by MikeMcQuaid** [comment]
@Homebrew/core thoughts here? Seems fairly sensible to me but I may be missing something.

**Comment by Rylan12** [comment]
```ruby
env = { PATH: "#{HOMEBREW_PREFIX/"bin"}:$PATH" }
(bin/"foo").write_env_script "#{libexec}/bin/foo", env
```

If this pattern is used enough, it feels like we should have a simpler way to specify it (I don't think this pattern is necessarily unique to node formulae...). Maybe have a function that returns the env hash?:

```ruby
(bin/"foo").write_env_script "#{libexec}/bin/foo", homebrew_bin_env
```

(not a fan of `homebrew_bin_env` as the name)

**Comment by cho-m** [comment]
> If this pattern is used enough, it feels like we should have a simpler way to specify it (I don't think this pattern is necessarily unique to node formulae...).

I don't think that pattern is commonly used. Couldn't find any usage for `node` formulae.

More common are prepending `opt_bin`, e.g.

https://github.com/Homebrew/homebrew-core/blob/0fdd17adb3f24de316e3585028ff273804ce2002/Formula/b/bcoin.rb#L36

https://github.com/Homebrew/homebrew-core/blob/0fdd17adb3f24de316e3585028ff273804ce2002/Formula/m/mongosh.rb#L24

Or shebang modification

https://github.com/Homebrew/homebrew-core/blob/0fdd17adb3f24de316e3585028ff273804ce2002/Formula/a/apify-cli.rb#L32

https://github.com/Homebrew/homebrew-core/blob/741721d29ab8e5fed5931ae94982e8e9c83d9a1d/Formula/c/cloudflare-wrangler2.rb#L28

https://github.com/Homebrew/homebrew-core/blob/0fdd17adb3f24de316e3585028ff273804ce2002/Formula/l/lando-cli.rb#L31-L32

---

I guess the original approach didn't require manually checking executable names as everything in `libexec/bin` would be linked. If new executables are added in a future release, then they would automatically be available.

Though, something similar to Java formulae logic could be used instead that generates env scripts for everything in `libexec/bin/`.
```rb
    bin.install Dir["#{libexec}/bin/*"]
    bin.env_script_all_files libexec/"bin", Language::Java.overridable_java_home_env
```

**Comment by MikeMcQuaid** [comment]
> Or shebang modification

We automatically rewrite shebangs for some stuff (Python, Perl, ?), right? Doing this for NodeJS (and perhaps Ruby, etc.) too would make more sense to me than requiring DSL changes in hundreds of formulae.

> * Perl - `brew` does shebang rewrites during keg cleaning

Yeh, this.

> * Python - default shebang of virtualenvs will resolve to dependency
> * Ruby - default shebang of gem install uses path to dependency

Ok, yeh, so it's handled by upstream in these cases. Feels like if `npm` doesn't do this for us: we should do it (and the Perl approach makes most sense to me).

**Comment by SenseiMarv** [comment]
Hi @MikeMcQuaid, unfortunately this change broke setups that relied on https://github.com/nvm-sh/nvm. I installed pnpm through Brew, which has a dependency on node, so that was also installed through Brew. Different projects in my company rely on different versions of node, all of which are defined by `.nvmrc` files. This way, nvm automatically ensures that the correct node version is used for each project. This no longer works after this change, as the nvm version, which is also the one set in the PATH, is now overridden by Brew's version.
The overriding behaviour was also confusing to me, as it's not obvious why pnpm would use a different node version than what the shell reports:
<img width="757" alt="image" src="https://github.com/user-attachments/assets/03d35ed3-81be-4a10-88b5-27a5b83edb54">

Is there a way to disable this so that I'm not forced to stop using Brew to manage my pnpm installation or have to use `--build-from-source`?

There are also others who have been confused by this behaviou and thought it was pnpm's fault. See: https://github.com/pnpm/pnpm/issues/8384

**Comment by jstcki** [comment]
I second the comment by @SenseiMarv. Suddenly pnpm is broken on systems where node versions are managed with [fnm](https://github.com/Schniz/fnm) too.

**Comment by ctaintor** [comment]
I'd suggest opening a bug on this.

I think the fix should be that the shebang rewrite only happens if node is a **required** dependency. For the examples above (and also for yarn formula), node is not required - but is necessary to build and/or test.

**Comment by carlocab** [comment]
> Or have a way for the formula to opt out of the rewrite - but I'd expect that to only be the case in situations where node is not a required dependency

This seems reasonable to me, and can already be handled in specific formulae. See [`pnpm.rb`](https://github.com/Homebrew/homebrew-core/blob/753cb488e0c6ad28b1f123a8c2a3b9c0337193bd/Formula/p/pnpm.rb#L27) for an example. (If that isn't working for some reason, that may be a `brew` bug.)

**Comment by jstcki** [comment]
I @ctaintor I don't understand the intricacies of what is rewritten and when. I only can say that this change broke every setup where node versions are managed through nvm/fnm or similar, so I believe it should be reverted asap. yarn, pnpm, you name it.

**Comment by MikeMcQuaid** [comment]
> I think the fix should be that the shebang rewrite only happens if node is a **required** dependency. For the examples above (and also for yarn formula), node is not required - but is necessary to build and/or test.

I agree: this is the correct fix here.

> This seems reasonable to me, and can already be handled in specific formulae. See [`pnpm.rb`](https://github.com/Homebrew/homebrew-core/blob/753cb488e0c6ad28b1f123a8c2a3b9c0337193bd/Formula/p/pnpm.rb#L27) for an example. (If that isn't working for some reason, that may be a `brew` bug.)

@carlocab I'm a bit 😢 that that `skip_clean` is present without a comment. I'd love to see that removed unless needed.

> so I believe it should be reverted asap

We're going to fix forward instead of reverting.

**Comment by Bo98** [comment]
> @carlocab I'm a bit 😢 that that skip_clean is present without a comment. I'd love to see that removed unless needed

Yeah this isn't good. Cleaner is not supposed to have false positives so if we're going to start adding skip_clean everywhere then I don't think the cleaner is the correct place for this logic to be. My approval on the PR was conditional on that.

**Comment by MikeMcQuaid** [comment]
> We're going to fix forward instead of reverting.

Have opened https://github.com/Homebrew/brew/pull/17993 for this.

**Comment by carlocab** [comment]
> @carlocab I'm a bit 😢 that that `skip_clean` is present without a comment.

Same here.

> I'd love to see that removed unless needed.

https://github.com/Homebrew/homebrew-core/pull/180632
