### ISSUE TITLE
[youtube-dl] Update package to nightly versions

### ISSUE THREAD

**Issue by superbonaci** [Homebrew/homebrew-core#176570]
### `brew doctor` output

```shell
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  youtube-dl
```

### Verification

- [X] My "`brew doctor` output" above says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` twice and am still able to reproduce my issue.
- [X] This issue's title and/or description do not reference a single formula e.g. `brew install wget`. If they do, open an issue at https://github.com/Homebrew/homebrew-core/issues/new/choose instead.

### `brew config` output

```shell
brew config
HOMEBREW_VERSION: 4.3.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e5f776b3e23cae8f1b6c3d1194b8329bf701965f
Last commit: 6 days ago
Core tap JSON: 06 Jul 19:43 UTC
Core cask tap JSON: 06 Jul 19:43 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
Rosetta 2: false
```

### What were you trying to do (and why)?

Install a newer version of `youtube-dl`. Since a few years, only nightlies are offered for legal reasons, so there won't be any stable release soon.

### What happened (include all command output)?

not available.

### What did you expect to happen?

`youtube-dl` is offering nightlies, which are far superior to latest version offered by brew:
https://github.com/ytdl-org/ytdl-nightly/releases

They can't be used as is, since they are hard coded to work with `python`, not python3 (the only one supported on macOS 14), so they require to be re-compiled with that in mind.

A feature request has been already sent but brew.sh could do that instead:
https://github.com/ytdl-org/youtube-dl/issues/30129#issuecomment-2201994087

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
not available.
```

**Comment by iMichka** [comment]
Transferred issue to https://github.com/Homebrew/homebrew-core

**Comment by superbonaci** [comment]
Thanks for moving, didn't know where to put it.

**Comment by iMichka** [comment]
I think we could accept a new `youtube-dl-nightly` formula. It's not a big deal that it is a nightly build, as long as it gets a tag. We might need to throttle the updates though because we might not be interested to run a daily rebuild on our side.

Looks like AUR already did this:
https://repology.org/project/youtube-dl-nightly/versions
https://repology.org/project/youtube-dl/versions

Regarding python; I did not read everything in detail but we can probably work around this with some shebang rewrite. We do that in other formulae.

And if there are some legal risks regarding shipping this package for homebrew: the @Homebrew/tsc might need to have a look at this

**Comment by superbonaci** [comment]
At least the website don't allow to download the latest stable:
https://ytdl-org.github.io/youtube-dl/download.html

```
$ curl -L https://yt-dl.org/downloads/latest/youtube-dl -o -
<h1>Access denied</h1>

<p>
  Due to a <a href="https://openjur.de/u/2466945.html" target="_blank">ruling</a> of the Hamburg Regional Court, access to this website is blocked.
</p>

<hr />

<h1>Zugriff gesperrt</h1>

<p>
  Aufgrund eines <a href="https://openjur.de/u/2466945.html" target="_blank">Urteils</a> des Landgerichts Hamburg ist der Zugriff auf diese Website gesperrt.
</p>
```

**Comment by superbonaci** [comment]
The shebang will have to be adapte for each macOS version, but at least latest macOS has python3 only, not python1 or python2, and I don't think should be a good idea have any as dependency, just use:

```
/opt/homebrew/bin/python3
/usr/local/bin/python3
/usr/bin/python3
```

**Comment by MikeMcQuaid** [comment]
Do we have any other formulae we've published nightly versions for?

It instead sounds to me like `youtube-dl` itself should probably be either updated to a random nightly version or just removed entirely if they are no longer tagging releases.

**Comment by superbonaci** [comment]
There's no difference in "quality" between nightlies and tagged releases, so just pick any nightly as your stable.
There are at least 5 nightlies already in brew.sh:

1. https://formulae.brew.sh/cask/1password@nightly
2. https://formulae.brew.sh/cask/adguard-vpn@nightly
3. https://formulae.brew.sh/cask/adguard@nightly
4. https://formulae.brew.sh/cask/arduino-ide@nightly
5. https://formulae.brew.sh/cask/brave-browser@nightly

**Comment by SMillerDev** [comment]
Those are casks (precompiled binaries) while youtube-dl is a formula (source build). There is only one formula that is sort of a nightly, it's luajit.

**Comment by MikeMcQuaid** [comment]
> There's no difference in "quality" between nightlies and tagged releases, so just pick any nightly as your stable.

@superbonaci I'd like to see an upstream citation before we rely on that, sorry.

> There is only one formula that is sort of a nightly, it's luajit.

Given `--HEAD` exists: I am even less inclined to introduce a `youtube-dl-nightly` now.

**Comment by Bo98** [comment]
Something recent Debian/Ubuntu/etc has done instead is just replace phase out `youtube-dl` entirely in favour of `yt-dlp`.

We've already deprecated `youtube-dl` ourselves, though we don't currently point `yt-dlp` in that deprecation message.

**Comment by MikeMcQuaid** [comment]
> We've already deprecated `youtube-dl` ourselves, though we don't currently point `yt-dlp` in that deprecation message.

If it's deprecated: let's not make any more changes.
