### ISSUE TITLE
[pngquant] Missing man page

### ISSUE THREAD

**Issue by omarieclaire** [Homebrew/homebrew-core#176910]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config output:

HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 3 days ago
Core tap JSON: 10 Jul 14:09 UTC
Core cask tap JSON: 10 Jul 14:09 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 14.0.0 build 1400
Git: 2.45.2 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.6-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: 14.0
Rosetta 2: false
```

brew doctor output:
https://gist.github.com/omarieclaire/0908e5065e65213a88a724c4daaa47b1

### Verification

- [] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I tried to run man pngquant

### What happened (include all command output)?

It says
```
No manual entry for pngquant.
```
I also tried:

* setting my `MAN_PATH` to include homebrew's man pages
* running `find / -name pngquant.1.gz` to search everywhere on my computer for the man page. It returned nothing
* Looking at the original formula ([link](https://github.com/Homebrew/homebrew-core/blob/42d96a6ec38c02412863c3820badb4c0c73096f5/Formula/p/pngquant.rb)) which doesn't appear to install the man page

Note: Brew doctor lists a bunch of problems but I don't believe any of them are related to pngquant

### What did you expect to happen?

I expected to see the man page, which does exist: https://github.com/kornelski/pngquant/blob/main/pngquant.1

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install pngquant
man pngquant
```
```

**Comment by chenrui333** [comment]
yeah, it is because the `pngquant.1` is missing in the crate. thanks for catching this.
