### ISSUE TITLE
A plea for the restoration of the “--enable-unsupported” option in hdf5.rb

### ISSUE THREAD

**Issue by fish2000** [Homebrew/homebrew-core#17717]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

… it’s a problem – or an issue, at any rate – with the [HDF5 formula](https://github.com/Homebrew/homebrew-core/tree/master/Formula/hdf5.rb), recently migrated back to homebrew-core from homebrew-science.

- [X] Ran `brew update` and retried your prior step?

… I have indeed.

- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

… This has been done on my end as well (except for linking `numpy` – I actively use the `pip` version but keep homebrew’s installation around to satisfy dependencies; this is orthogonal to the HDF5 issue).

- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/fish2000/5908215769b131e9c363957183b32343

- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

… this is not applicable (see above).

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

<hr/>

… This is a half issue report, half feature request, I suppose. I have read the latest [issue reports](https://github.com/Homebrew/homebrew-core/issues/15740) and [pull](https://github.com/Homebrew/homebrew-core/pull/16430) [requests](https://github.com/Homebrew/homebrew-core/pull/15771) on the HDF5 formula, and specifically concerning the frustrating combinatorial logic that governs which `./configure` flags may be used, and the use of which flags preclude the use of which other flags.

The problem [that others have had](https://github.com/Homebrew/homebrew-core/issues/15740) is, in brief: you can’t compile HDF5 with both `--enable-parallel` and `--enable-cxx`. The [current formula deals with this](https://github.com/Homebrew/homebrew-core/blob/d8de81a91f1d646f968aef6e9953bec974dc19ea/Formula/hdf5.rb#L44-L48)  by only really exposing the parallelism flag as a (depreciated) formula option; the C++ parts of HDF5 are compiled if parallelism happens to be disabled, and silently skipped otherwise.

Now, if you are building HDF5 independently of Homebrew, you can (when confronted with the error about this from `./configure`) either choose one of the two flags, _or_ add the `--enable-unsupported` flag, which allows compilation to proceed with the two options enabled. This flag sounds treacherous, but in my own practical use I have not encountered any problems or bugs when using it. 

At one point, the official Homebrew formula did offer the three-flag-compromise as a valid thing to do – this was before `hdf5.rb` had migrated to `homebrew-science` and back, if memory serves. Since I am personally developing against both the HDF5 C and C++ modules, I am doing an awful hack thing where I maintain [a chopped version of `hdf5.rb`](https://github.com/fish2000/homebrew-praxa/blob/d123abac002dc474cb393011c92ad1bf30ef5a9d/hdf5.rb#L35-L50), which I download and then use to “re-install” HDF5 every time there’s an update to the official formula.

Anyway. **tl;dr:** can we restore the capacity to specify C++ and parallelism through the `--enable-unsupported` flag to `./configure` in the HDF5 formula?

**Comment by fxcoudert** [comment]
What is upstream's position on the matter? Why is it called `unsupported`, and what does that entail?

**Comment by ilovezfs** [comment]
@tschoonj do you have any thoughts here?

**Comment by tschoonj** [comment]
No opinion really, I never use that option :smile

**Comment by ilovezfs** [comment]
@fish2000 can you open a PR for this?

**Comment by fish2000** [comment]
@fxcoudert I get the impression that the development of the core HDF5 distribution is actually more like several somewhat siloed parallel-track projects, in terms of their internal process – they likely don’t have a way to QA patches that span e.g. the C++ and the MPI silos in a non-trivial fashion (and I say that with full respect for the people who provide the HDF5 codebase; _c’est la guerre_ as it were).

@ilovezfs absolutely I can – I will pursue that this weekend. Thanks!
