### ISSUE TITLE
Install curl with openssl@1.1 ?

### ISSUE THREAD

**Issue by remoe** [Homebrew/homebrew-core#17724]
I installed openssl 1.1 with

`brew install openssl@1.1`

and also openssl 1.0.2l with

`brew install openssl`

after install of curl with `brew install curl` it uses openssl 1.0.2l

How can one install curl with openssl@1.1 ?

**Comment by ilovezfs** [comment]
Until we decide to use openssl@1.1 for curl, you can `brew install DomT4/crypto/curl-max`
