### ISSUE TITLE
OpenSSL seems to fail to build on 10.13db9 `17A360a`

### ISSUE THREAD

**Issue by SConaway** [Homebrew/homebrew-core#17732]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I already installed it from bottle.
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.
```
Stevens-MacBook-Pro:~ steven$ brew install python python3
==> Installing dependencies for python: openssl
==> Installing python dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2l.tar.gz
Already downloaded: /Users/steven/Library/Caches/Homebrew/openssl-1.0.2l.tar.gz
^C
Stevens-MacBook-Pro:~ steven$ brew install openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2l.tar.gz
Already downloaded: /Users/steven/Library/Caches/Homebrew/openssl-1.0.2l.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2l --openssldir=/usr
==> make depend
==> make
Last 15 lines from /Users/steven/Library/Logs/Homebrew/openssl/03.make:
2017-09-04 17:34:32 -0700

make

making all in crypto...
/usr/bin/perl ../util/mkbuildinf.pl "clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM" "darwin64-x86_64-cc" >buildinf.h
make[1]: *** No rule to make target `6.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/Availability.h', needed by `cryptlib.o'.  Stop.
make: *** [build_crypto] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
Upgrade to mono 5.2.0.215, fsharp 4.1.25 and add msbuild d15.3 https://github.com/Homebrew/homebrew-core/pull/17435
faust. v2.1.0 and v0.9.90 (new formula) https://github.com/Homebrew/homebrew-core/pull/16724
First issues with macOS 10.13 High Sierra https://github.com/Homebrew/homebrew-core/issues/14418
xerces-c 3.2.0 https://github.com/Homebrew/homebrew-core/pull/17371
Formulae affected by Homebrew/brew#2482 https://github.com/Homebrew/homebrew-core/issues/13133
php: 7.1 (new formula) https://github.com/Homebrew/homebrew-core/pull/16067
hadoop 2.8.1 failed to install on 10.12.6 https://github.com/Homebrew/homebrew-core/issues/17065

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```

**Comment by SConaway** [comment]
Didn't notice 
```
Warning: Xcode is installed to a directory with a space in the name.
This will cause some formulae to fail to build.
``` in `brew doctor`

**Comment by fxcoudert** [comment]
Yeah, my guess was right :)

**Comment by SConaway** [comment]
Is there a way to fix this? Patch the `makefile`?
