### ISSUE TITLE
onnxruntime: consider building with coreml support

### ISSUE THREAD

**Issue by redthing1** [Homebrew/homebrew-core#177367]
[onnxruntime formula in brew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/o/onnxruntime.rb)

[documentation](https://onnxruntime.ai/docs/build/eps.html#coreml) on compiling onnxruntime with coreml support

i will make a PR myself at some point, but if someone else wants to do it, please go ahead.

**Comment by SMillerDev** [comment]
This is not a bug and should not be filed as such.

**Comment by redthing1** [comment]
> This is not a bug and should not be filed as such.

Would you be open to it if I submitted a patch?

**Comment by SMillerDev** [comment]
Sure, pull requests are welcome. We just don't keep issues for feature requests.
