### ISSUE TITLE
stow: perl compilation failed, can't locate File/Copy.pm in @INC

### ISSUE THREAD

**Issue by liondandelion** [Homebrew/homebrew-core#177695]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 10 days ago
Core tap JSON: 18 Jul 07:47 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: /usr/bin/nano
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.3 => /var/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: dodeca-core 64-bit zen
Clang: N/A
Git: 2.45.2 => /bin/git
Curl: 8.6.0 => /bin/curl
Kernel: Linux 6.9.8-200.fc40.x86_64 x86_64 GNU/Linux
OS: Fedora release 40 (Forty)
Host glibc: 2.39
/usr/bin/gcc: 14.1.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 14.1.0_2
xorg: N/A

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to install and run stow to manage my dotfiles.

### What happened (include all command output)?

While running stow with any arguments i get the following output:
```
$ stow -h
Can't locate File/Copy.pm in @INC (you may need to install the File::Copy module) (@INC entries checked: /home/linuxbrew/.linuxbrew/Cellar/stow/2.4.0/share/perl/5.34.0 /usr/local/lib64/perl5/5.38 /usr/local/share/perl5/5.38 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /home/linuxbrew/.linuxbrew/Cellar/stow/2.4.0/share/perl/5.34.0/Stow.pm line 54.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/stow/2.4.0/share/perl/5.34.0/Stow.pm line 54.
Compilation failed in require at /home/linuxbrew/.linuxbrew/bin/stow line 465.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/bin/stow line 465.
```

### What did you expect to happen?

I expected stow to work normally without failures.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. $ brew install stow
2. $ stow -h
```

**Comment by cho-m** [comment]
This doesn't look like right search path for brew `perl` (5.34). It seems to be using system `perl` (5.38) instead:
```
(@INC entries checked:
/home/linuxbrew/.linuxbrew/Cellar/stow/2.4.0/share/perl/5.34.0
/usr/local/lib64/perl5/5.38
/usr/local/share/perl5/5.38
/usr/lib64/perl5/vendor_perl
/usr/share/perl5/vendor_perl
/usr/lib64/perl5
/usr/share/perl5)
```

Can you check what the shebang is? e.g. `head -1 /home/linuxbrew/.linuxbrew/bin/stow`

**Comment by cho-m** [comment]
May be due to not uploading bottle from #176700 so existing bottles are still using system `/usr/bin/perl` and only work if that Perl matches version on Ubuntu 22.04

**Comment by liondandelion** [comment]
> Can you check what the shebang is?
It is indeed `#!/usr/bin/perl`

**Comment by branchvincent** [comment]
Bottle was rebuilt in #177803, should be fixed after a `brew reinstall stow`

**Comment by liondandelion** [comment]
Yes, it is fixed now. Thanks!
