### ISSUE TITLE
Error: private method `system' called for module Homebrew

### ISSUE THREAD

**Issue by P4sca1** [Homebrew/homebrew-core#177714]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.9-307-g4aae003
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4aae003a1a9caa4a5b22c3c9c23afd6b1ef58a0f
Last commit: 10 hours ago
Core tap JSON: 18 Jul 13:00 UTC
Core cask tap JSON: 18 Jul 13:00 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 15.0.0 build 1500
Git: 2.45.2 => /usr/local/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-x86_64
CLT: 15.3.0.0.1.1708646388
Xcode: 15.4
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Installing multiple packages using `brew bundle`
```
brew bundle --no-lock --file=/dev/stdin <<EOF
brew "helix"
brew "fzf"
brew "fd"
brew "n"
brew "gh"
brew "jq"
brew "go"
brew "hcloud"
brew "kubectl"
brew "helm"
EOF
```

### What happened (include all command output)?

```
Error: private method `system' called for module Homebrew
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:267:in `safe_system'
/usr/local/Homebrew/Library/Homebrew/brew.rb:139:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:530:in `with_env'
/usr/local/Homebrew/Library/Homebrew/brew.rb:128:in `<main>'
```

### What did you expect to happen?

The install should succeed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The issue also occurs when running `brew bundle` without any arguments.
```

**Comment by SMillerDev** [comment]
This doesn't include any `brew doctor` output and should have been filed in https://github.com/homebrew/homebrew-bundle either way.

**Comment by P4sca1** [comment]
My `brew doctor` output just includes `Your system is ready to brew.`, which I confirmed via the checkbox.
I did not know about the separate repo for `homebrew-bundle`, so I will check there. Thank you for the link.

**Comment by P4sca1** [comment]
https://github.com/Homebrew/homebrew-bundle/issues/1413
