### ISSUE TITLE
Running cypher shell from neo4j installed via formula yields warning about unsupported Java version

### ISSUE THREAD

**Issue by SpecialThing44** [Homebrew/homebrew-core#177744]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c98a33a376e5b35ebc801d0f7d6ba7b9eb118ac
Last commit: 11 days ago
Core tap JSON: 18 Jul 16:13 UTC
Core cask tap JSON: 18 Jul 16:13 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.3 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.3/bin/ruby
CPU: 16-core 64-bit arm_palma
Clang: 15.0.0 build 1500
Git: 2.45.0 => /opt/homebrew/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.4-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

To run cypher-shell after installing neo4j using `brew install neo4j`

### What happened (include all command output)?

```sh
$ cypher-shell
You are using an unsupported version of the Java runtime. Please use Java(TM) 17 or Java(TM) 21.
```

### What did you expect to happen?

I expected that brew would require/provide the correct Java versions when installing. I have a Java 21 version available on my system, which is the default when running java --version

See https://github.com/Homebrew/homebrew-core/issues/61713#issuecomment-699771299

https://github.com/Homebrew/homebrew-core/blob/8237ed435b8a64220666c7a575ecbf102d0bfc7f/Formula/n/neo4j.rb#L30

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install neo4j
cypher-shell
```

**Comment by gromgit** [comment]
A couple of things are happening here:
* The formula depends on the latest OpenJDK release instead of LTS (v17 and v21, both of which are still supported by Homebrew at this point). This should be easily fixed.
* The test runs a command that's expected to fail, hence it doesn't surface the "unsupported runtime" issue. @SpecialThing44, can you suggest a test that normally passes and is runnable in a CI context? (I don't think this is a block to addressing the runtime issue, but it would be nice to not have to revisit this down the line.)

**Comment by gromgit** [comment]
Sorry, just noticed that you're talking about the `neo4j` version of `cypher-shell` (there's also a `cypher-shell` formula that conflicts). That raises the question as to whether `neo4j` should also be fixed to only use LTS.
