### ISSUE TITLE
brew install maven should not have ` depends_on "openjdk"`

### ISSUE THREAD

**Issue by muescha** [Homebrew/homebrew-core#177940]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs maven
Error: No logs.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I would like to install Maven. I already have a version of Java installed and do not need any additional Java installations. I have installed Java using `asdf`.

There are many tools available for installing Java on a machine, including:
- SDKMAN
- ASDF
- MiSE
- Java installed by an IDE (e.g., IntelliJ)
- and brew

Therefore, it is unnecessary to install an additional Java version that might not be needed. It's also not always the best solution, given the numerous Java runtimes and versions available.

[Link to the Maven formula on Homebrew](https://github.com/Homebrew/homebrew-core/blob/25742ddeaf3aea5c3934f04d8b8fe8f9a22be807/Formula/m/maven.rb#L24C1-L25C1)

### What happened (include all command output)?

When I install Maven, why does it fetch so many dependencies for such a "small" tool?

I don't need all this stuff:
```
==> Fetching dependencies for maven: giflib, libpng, freetype, fontconfig, xorgproto, libxau, libxdmcp, libxcb, libx11, libxext, libxrender, lzo, pixman, cairo, graphite2, harfbuzz, jpeg-turbo, lz4, zstd, libtiff, little-cms2, and openjdk
```

### What did you expect to happen?

only install maven

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install maven
```

**Comment by SMillerDev** [comment]
Does maven depend on Java? Then it should have a dependency. 

Homebrew formulae can't really depend on users doing something outside of Homebrew since beginning users might not know about that.

**Comment by carlocab** [comment]
We're not able to test using Maven with alternative installations of Java, so we don't support what you're looking for. Sorry!
