### ISSUE TITLE
binutils does not include `gld` (GNU `ld`) utility

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#17794]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [ x Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I believe this package should include the `gld` (GNU `ld`) program, but it does not. I have verified it does not exist in the cellar.

**Comment by fxcoudert** [comment]
GNU binutils's `ld` does not support Darwin (macOS), and is thus not built.

**Comment by alexreg** [comment]
Okay, thanks for the info.

**Comment by JustAPerson** [comment]
Does it not build at all on darwin, or does it not target darwin?
In my use case I would like to just generate a normal ELF just as if I were on linux.

**Comment by fxcoudert** [comment]
You can build binutils as cross-tools, hosted on macOS and targeting ELF/Linux. But this is not what this formula does (and we do not include a Linux cross-binutils in Homebrew currently).
