### ISSUE TITLE
brew insall node.js with opensll always forces no NPM

### ISSUE THREAD

**Issue by BenjaminHCCarr** [Homebrew/homebrew-core#1781]
### Bug reports:

When node.js is called with the --openssl flag it builds without npm support

> tyr:~ benc$ brew update && brew install --with-openssl --with-npm nodejs
> Updated Homebrew from 2cd81e5 to af42dec.
> Updated 1 tap (caskroom/cask).
> No changes to formulae.
> ==> Downloading https://nodejs.org/dist/v6.2.1/node-v6.2.1.tar.xz
> Already downloaded: /Users/benc/Library/Caches/Homebrew/node-6.2.1.tar.xz
> ==> ./configure --prefix=/usr/local/Cellar/node/6.2.1 --without-npm --shared-openssl
> ==> make install

python is far from my main language, but the install ruby looks like NPM is disabled with any flag on the install script: https://github.com/Homebrew/homebrew-core/blob/01ae8fcc5c3c1a7d1a6515c83f53bae8fb9f2239/Formula/node.rb

Lines [50-51]:

>  def install
>    args = %W[--prefix=#{prefix} --without-npm]

With SSL/TLS becoming so important, I am unsure (and again python isn't my *thing*) why building with encryption support should disable NPM. Even a comment in the build file would be useful explaining the neccessity, as while node.js over http isn't a problem at the moment, that doesn't mean you won't go into SEO bucket list without it next week.

**Comment by dunn** [comment]
npm is installed manually after node: https://github.com/Homebrew/homebrew-core/blob/01ae8fcc5c3c1a7d1a6515c83f53bae8fb9f2239/Formula/node.rb#L64-L91

**Comment by DomT4** [comment]
Ah, there's a misunderstanding of the formula here.

`depends_on "openssl" => :optional` in the Node formula, when invoked, just means _"Build against Homebrew's OpenSSL rather than the version bundled with Node"_ rather than _"Disable all SSL/TLS please"_.

`--without-npm` pretty much means the same thing, _"Please don't build the bundled npm"_, which we immediately rectify by installing `npm` from the tarball as @dunn just highlighted unless `brew install node --without-npm` is passed. Doing it that way allows us greater control over how `npm` builds, which equals less pain all around.

**Comment by BenjaminHCCarr** [comment]
AHHHHHHHH!!!!!!!! yes, that was the confusion, I need SSL support, what it's built against less an issue.

How is this going to work though:
https://github.com/Homebrew/homebrew-core/blob/01ae8fcc5c3c1a7d1a6515c83f53bae8fb9f2239/Formula/node.rb#L64 

if you are making with:
https://github.com/Homebrew/homebrew-core/blob/01ae8fcc5c3c1a7d1a6515c83f53bae8fb9f2239/Formula/node.rb#L15

it seems to be like L64 conditional would never be met?

**Comment by DomT4** [comment]
There's a difference between the Homebrew option flag `--without-npm` and the `npm` configuration flag `--without-npm`. The latter doesn't have an impact on the former. The `if build.with? "npm"` on L64 is met by the default `brew install node`.

The only time it isn't met is if you `brew install node --without-npm`. The arguments passed to Node's `./configure` have no impact on the later `if build.with?` qualifications.

`brew install node --without-npm` is a valid Homebrew option choice. We permit people to install `npm` themselves if they wish to, some people prefer to avoid package managers packaging other package managers, which we're sympathetic towards but most people just want formulae that work straight "out of the box".

**Comment by BenjaminHCCarr** [comment]
Thanks for the answers, that all makes sense, and I appreciate the --without-npm flag now that I understand it. Macports/perl/CPAN/python was ummmm, yeah, we'll leave packaging inside packaging/inside packaging alone.
