### ISSUE TITLE
bonnie++ not built with Large File Support

### ISSUE THREAD

**Issue by jrwren** [Homebrew/homebrew-core#17822]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Use bonnie++
- What happened (include command output)
```
 $ /usr/local/Cellar/bonnie++/1.97.3/sbin/bonnie++
Large File Support not present, can't do 32768M.
```
- What you expected to happen

bonnie++ to run.

- Step-by-step reproduction instructions (by running `brew install` commands)
* brew install bonnie++ # on any machine with more than 1GB of ram
* /usr/local/Cellar/bonnie++/1.97.3/sbin/bonnie++

Bonnie defaults to a -s size of twice RAM. LFS support is required to create files > 2GB. Bonnie will fail on any system with > 1GB RAM. (This feels so 10yrs ago.)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I was going to see which options need to be passed to `configure` to enable LFS, but the source tarball is not available.
```
$ brew install -d --debug --build-from-source bonnie++
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bonnie++.rb
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bonnie++.rb
==> Downloading https://www.coker.com.au/bonnie++/experimental/bonnie++-1.97.3.tgz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "bonnie++"
Download failed: https://www.coker.com.au/bonnie++/experimental/bonnie++-1.97.3.tgz
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:341:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:335:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:115:in `fetch'
/usr/local/Homebrew/Library/Homebrew/resource.rb:84:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1887:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:114:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:188:in `<main>'
```

**Comment by ilovezfs** [comment]
@jrwren Thanks for reporting this. It should now be fixed via https://github.com/Homebrew/homebrew-core/pull/17824.
