### ISSUE TITLE
ledger: "ledger entry" command fails with error message "Invalid date" on OS X 10.12.6

### ISSUE THREAD

**Issue by he-sk** [Homebrew/homebrew-core#17825]
After a recent update of ledger, I cannot use the entry command anymore.

For example:

````
$ ledger entry 2017/08/26 lebensmittel 6,5
Error: Invalid date: 
$ ledger --version
Ledger 3.1.1-20160111, the command-line accounting tool
`````

The command works if I switch to an older ledger and boost installation.

````
$ brew switch ledger 3.1.1_5         # was: 3.1.1_7
$ brew switch boost 1.64.0_1         # was: 1.65.1
$ ledger entry 2017/08/26 lebensmittel 6,5
2017/08/26 Lebensmittel
    Ausgaben:Essen                            6,50 €
    Aktiva:Bargeld
$ ledger --version
Ledger 3.1.1-20160111, the command-line accounting tool
````

As you can see, it's the same upstream version but linked against a different version of boost. So I assume that the problem is not really with ledger but somewhere with how boost parses the date.

brew config output:

````
HOMEBREW_VERSION: 1.3.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 751334a257d81851e68da7ab390982d4e9fdf909
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0498af3057b41340ca905fb82f3bbc70783791b8
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: N/A
X11: 2.7.11 => /opt/X11
````

brew doctor output:

````
Your system is ready to brew.
````

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
Please report this upstream.

**Comment by ilovezfs** [comment]
@he-sk upstream issue tracker is here: http://bugs.ledger-cli.org/

**Comment by he-sk** [comment]
Upstream bug report: http://bugs.ledger-cli.org/show_bug.cgi?id=1229
