### ISSUE TITLE
gnu-sed fails with linkage error to shared library libacl.so.1:

### ISSUE THREAD

**Issue by briangerholdc3** [Homebrew/homebrew-core#178258]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
To reproduce:

brew install gnu-sed
brew test gnu-sed

test output:
(base) ➜  ~ brew test gnu-sed                           
==> Testing gnu-sed
==> /home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed -i s/world/World/g test.txt
Last 15 lines from /home/c3/.cache/Homebrew/Logs/gnu-sed/test.01.sed:
2024-07-24 00:31:34 +0000

/home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed
-i
s/world/World/g
test.txt

/home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory
Error: gnu-sed: failed


Appears to be connected to this recent commit:
https://github.com/Homebrew/homebrew-core/commit/f337a2e3157cab24a86e02036a3f676ce3fd09a3
From this PR:
https://github.com/Homebrew/homebrew-core/pull/176589
And was cited as erroring during review:
https://github.com/Homebrew/homebrew-core/pull/176589#issuecomment-2218176993
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Trying to install (latest) gnu-sed on linux

### What happened (include all command output)?

Install succeeded without issue:

 > brew install gnu-sed
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:44a5a8e4c5e4f74a346e50232c13b2ec54a72d8cb5d8ebc6965a197eefc9b03f
######################################################################## 100.0%
==> Pouring portable-ruby-3.3.4.x86_64_linux.bottle.tar.gz
==> Auto-updated Homebrew!
==> Updated Homebrew from 9538f424b5 to 4.3.10 (8e8ce4a2f7).
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
clang-uml                                                    iowow                                                        libgit2@1.7                                                  terrahash                                                    terramaid
==> New Casks
avbeam                                      dockdoor                                    geoda                                       ivacy                                       longplay                                    roblox                                      treeviewer
boosteroid                                  duplicateaudiofinder                        gitkraken-on-premise-serverless             kando                                       monarch                                     teamspeak-client@beta                       twingate

You have 6 outdated formulae installed.

The 4.3.0 release notes are available on the Homebrew Blog:
  https://brew.sh/blog/4.3.0
The 4.3.10 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/4.3.10
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-sed/manifests/4.9-1
######################################################################################################################################################################################################################################################### 100.0%
==> Fetching dependencies for gnu-sed: linux-headers@5.15 and xz
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/5.15/manifests/5.15.163
######################################################################################################################################################################################################################################################### 100.0%
==> Fetching linux-headers@5.15
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/5.15/blobs/sha256:1b29b2cb5f096d49878f7adfa6304fb7b2301ce0d4e93c84a92d09e48837c43d
######################################################################################################################################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.6.2
######################################################################################################################################################################################################################################################### 100.0%
==> Fetching xz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:ab97999c22de61b2efa61c2a3f62d28085ce3f15601035955e41b8d783b89725
######################################################################################################################################################################################################################################################### 100.0%
==> Fetching gnu-sed
==> Downloading https://ghcr.io/v2/homebrew/core/gnu-sed/blobs/sha256:3989ab1717786e2d9ac9d1035f794cd741372131c1f830e2a76722f085872cfb
######################################################################################################################################################################################################################################################### 100.0%
==> Installing dependencies for gnu-sed: linux-headers@5.15 and xz
==> Installing gnu-sed dependency: linux-headers@5.15
==> Downloading https://ghcr.io/v2/homebrew/core/linux-headers/5.15/manifests/5.15.163
Already downloaded: /home/c3/.cache/Homebrew/downloads/6f735d8b29b36871e089c41487fddaf18d5e895800f1e75a206b48e1014ecea6--linux-headers@5.15-5.15.163.bottle_manifest.json
==> Pouring linux-headers@5.15--5.15.163.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/linux-headers@5.15/5.15.163: 961 files, 5.7MB
==> Installing gnu-sed dependency: xz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.6.2
Already downloaded: /home/c3/.cache/Homebrew/downloads/0f02a3a463ce4e72f92871751d9ba7b872ca8090348074d46ffb523fd67e1c7b--xz-5.6.2.bottle_manifest.json
==> Pouring xz--5.6.2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/xz/5.6.2: 97 files, 2.0MB
==> Installing gnu-sed
==> Pouring gnu-sed--4.9.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9: 52 files, 1.5MB
==> Running `brew cleanup gnu-sed`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /home/c3/.cache/Homebrew/gnu-sed_bottle_manifest--4.9... (9.6KB)
==> Upgrading 4 dependents of upgraded formulae:
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
libtirpc 1.3.3 -> 1.3.4, nuclei 3.2.9 -> 3.3.0, pcre2 10.43 -> 10.44, util-linux 2.40.1 -> 2.40.2
==> Downloading https://ghcr.io/v2/homebrew/core/libtirpc/manifests/1.3.4
######################################################################################################################################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/nuclei/manifests/3.3.0
######################################################################################################################################################################################################################################################### 100.0%
==> Fetching nuclei
==> Downloading https://ghcr.io/v2/homebrew/core/nuclei/blobs/sha256:fc8ae5159fb461c64c344dedad8512850f9ebdc5c06601f3bd2e75ad39142853
######################################################################################################################################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/manifests/10.44
Already downloaded: /home/c3/.cache/Homebrew/downloads/22ed791461c5bf400adde8c3b432c1230866aa1db3c5cb81e06a6ff21cac96ee--pcre2-10.44.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/util-linux/manifests/2.40.2-1
Already downloaded: /home/c3/.cache/Homebrew/downloads/635c3a4838ab534b3fed900de735d2527a71bca53917fcc61cc683223c724e8a--util-linux-2.40.2-1.bottle_manifest.json
==> Upgrading nuclei
  3.2.9 -> 3.3.0 
==> Pouring nuclei--3.3.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/nuclei/3.3.0: 6 files, 74MB
==> Running `brew cleanup nuclei`...
Removing: /home/linuxbrew/.linuxbrew/Cellar/nuclei/3.2.9... (6 files, 74.7MB)
Removing: /home/c3/.cache/Homebrew/nuclei_bottle_manifest--3.2.9... (7.3KB)
Removing: /home/c3/.cache/Homebrew/nuclei--3.2.9... (25.3MB)
==> Checking for dependents of upgraded formulae...
==> No broken dependents found!

Sed is updated to linux brew

> which sed
/home/linuxbrew/.linuxbrew/bin/sed

Running sed throws shared lib error

> /home/linuxbrew/.linuxbrew/bin/sed
/home/linuxbrew/.linuxbrew/bin/sed: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory

Brew test fails that formula:

> brew test gnu-sed                           
==> Testing gnu-sed
==> /home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed -i s/world/World/g test.txt
Last 15 lines from /home/c3/.cache/Homebrew/Logs/gnu-sed/test.01.sed:
2024-07-24 00:31:34 +0000

/home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed
-i
s/world/World/g
test.txt

/home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory
Error: gnu-sed: failed
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
An exception occurred within a child process:
  BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/gnu-sed/4.9/bin/sed -i s/world/World/g test.txt
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:3048:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2984:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2984:in `system'
/home/linuxbrew/.linuxbrew/opt/gnu-sed/.brew/gnu-sed.rb:53:in `block in <class:GnuSed>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2790:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:530:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2789:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1193:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2788:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:75:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:3099:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2782:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:47:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/timeout.rb:41:in `handle_timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/lib/ruby/3.3.0/timeout.rb:195:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:51:in `<main>'

### What did you expect to happen?

sed functions as normal

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall gnu-sed
brew test gnu-sed
```

**Comment by ZhongRuoyu** [comment]
This is now fixed. Please do `brew update`, then `brew reinstall gnu-sed`.
