### ISSUE TITLE
gtk+ 3.22.20 update broke libgdk

### ISSUE THREAD

**Issue by philn** [Homebrew/homebrew-core#17861]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

My python app stopped working after the last gtk+ update:

```
** (CocoricoFM:20848): WARNING **: Failed to load shared library '/usr/local/Cellar/gtk+3/3.22.20/lib/libgdk-3.0.dylib' referenced by the typelib: dlopen(/usr/local/Cellar/gtk+3/3.22.20/lib/libgdk-3.0.dylib, 9): Library not loaded: @@HOMEBREW_PREFIX@@/opt/gettext/lib/libintl.8.dylib
  Referenced from: /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
  Reason: image not found
```

**Comment by philn** [comment]
Looks like something changed in my setup, I tried to rollback to 3.22.18 and the error is the same, I'll investigate :/

**Comment by philn** [comment]
Hah!
```
==> Upgrading harfbuzz 
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.5.1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/65/65b2821a8af21d348fc4fd3ffd6b94b934b8fafe05e51820addec0d80f8fe9b1?__gda__=exp=1504898790~hmac=5ae6125b1cd40a4752643871dd95d6d6749354f071011
######################################################################## 100.0%
==> Pouring harfbuzz-1.5.1.sierra.bottle.tar.gz
Error: Failed to fix install linkage
The formula built, but you may encounter issues using it or linking other
formula against it.
```

**Comment by ilovezfs** [comment]
There was an issue which is now fixed by https://github.com/Homebrew/brew/pull/3138.

You can fix it by uninstalling and reinstalling the affected packages.

**Comment by philn** [comment]
Yes that's what I did :) BTW why is this error non-fatal? Luckily I had my terminal scrollback to find the packages to reinstall.

**Comment by ilovezfs** [comment]
>BTW why is this error non-fatal?

It probably could be made fatal. It's never supposed to happen, so I'm not sure it makes much difference one way or the other.
