### ISSUE TITLE
Error: Failure while executing: unzip -qq -q while creating ktlint 0.9.2 (new formula)

### ISSUE THREAD

**Issue by pgreze** [Homebrew/homebrew-core#17895]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
➜  ~ brew update
Already up-to-date.
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Your Xcode (8.2.1) is outdated.
Please update to Xcode 8.3.3 (or delete it).
Xcode can be updated from the App Store.
➜  ~ brew gist-logs ktlint
Error: No logs.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
I'm trying to create a new formula for [ktlint](ktlint.github.io).
- What happened (include command output)
After used following commands without errors to create the formula:
```
brew create https://github.com/shyiko/ktlint/releases/download/0.9.2/ktlint
brew audit --new-formula ktlint
brew audit --strict ktlint
```
I have successfully created [this formula](https://github.com/pgreze/homebrew-core/commit/71e2fd4c6e6e8bcf9c98beec31db4c8d64b12ee1).
But when I'm trying to install it, an error is occurring:
```
➜  ~ brew install ktlint
==> Downloading https://github.com/shyiko/ktlint/releases/download/0.9.2/ktlint
Already downloaded: /Users/pgreze/Library/Caches/Homebrew/ktlint-0.9.2
warning [/Users/pgreze/Library/Caches/Homebrew/ktlint-0.9.2]:  46 extra bytes at beginning or within zipfile
  (attempting to process anyway)
Error: Failure while executing: unzip -qq -q /Users/pgreze/Library/Caches/Homebrew/ktlint-0.9.2
```
- What you expected to happen
ktlint executable should be installed.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install ktlint
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

----

**Comment by fxcoudert** [comment]
The formula downloads a binary wrapped in a shell script, which confuses Homebrew. You need to download the [release source tarball](https://github.com/shyiko/ktlint/archive/0.9.2.tar.gz) instead

**Comment by shyiko** [comment]
@pgreze see https://github.com/shyiko/ktlint/blob/master/.deploy-to-homebrew#L20
