### ISSUE TITLE
Settings schema 'io.github.lxi-tools.lxi-gui' is not installed

### ISSUE THREAD

**Issue by manotam** [Homebrew/homebrew-core#179217]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

HOMEBREW_VERSION: 4.3.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 874d2da45344d3b27aa740e555b0210d8c474220
Last commit: 2 days ago
Core tap JSON: 31 Jul 14:56 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 3.3.4 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4/bin/ruby
CPU: 16-core 64-bit unknown_0x6_0x9a
Clang: 18.1.8
Git: 2.34.1 => /bin/git
Curl: 7.81.0 => /bin/curl
Kernel: Linux 6.5.0-1025-oem x86_64 GNU/Linux
OS: Linux Mint 21.1 (vera)
Host glibc: 2.35
/usr/bin/gcc: 11.4.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: 14.1.0_2
xorg: N/A


brew doctor:

Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Installed [lxi-tools](https://github.com/lxi-tools/lxi-tools) and ran

`lxi-gui`

I reached out to the creators of the tool ([here the issue and workaround](https://github.com/lxi-tools/lxi-tools/issues/89)) and suggested to list that issue here. However, I am not sure how to reach out to the creator of the brew instructions for this distro. In case this is misplaced please reach out to me how I can contact the creator. Thanks!

### What happened (include all command output)?

output:
`(lxi-gui:2864): GLib-GIO-ERROR **: 17:08:47.333: Settings schema 'io.github.lxi-tools.lxi-gui' is not installed Trace/breakpoint trap (core dumped)`

### What did you expect to happen?

gui launching

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
run:

$ brew install lxi-tools
$ lxi-gui
```

**Comment by cho-m** [comment]
It seems you had `XDG_DATA_DIRS` set prior to running command?

Homebrew's `glib` automatically looks up correct directory, but only if `XDG_DATA_DIRS` isn't set as that overrides the defaults:

* https://github.com/Homebrew/formula-patches/blob/master/glib/hardcoded-paths.diff
* https://github.com/Homebrew/homebrew-core/blob/40c45b887b68d12c4528853fe6008f5243f5cc23/Formula/g/glib.rb#L67
* https://gitlab.gnome.org/GNOME/glib/-/blob/2.80.4/glib/gutils.c#L2691-2698
  ```c
    gchar *data_dirs = (gchar *) g_getenv ("XDG_DATA_DIRS");
  
    /* These checks are the same as the ones that g_win32_get_system_data_dirs_for_module()
     * does. Please keep them in sync.
     */
  #ifndef G_OS_WIN32
    if (!data_dirs || !data_dirs[0])
      data_dirs = "/usr/local/share/:/usr/share/";
  ```

---

If you set `XDG_DATA_DIRS`, then you will need to make sure to add correct path as Homebrew cannot install into system's `/usr/share`.

**Comment by lundmar** [comment]
> It seems you had `XDG_DATA_DIRS` set prior to running command?

FYI - on most distributions this variable will be set. This will conflict with brew installed applications as is the case here. There must be a more sensible solution than homebrew users having to manually set or unset XDG_DATA_DIRS.

**Comment by gromgit** [comment]
> FYI - on most distributions this variable will be set.

I can confirm this to be true even on GUI-less Ubuntu and Debian server installations. The "culprit" is `snapd`, a cross-distro containerised packaging platform that installs `/etc/profile.d/apps-bin-path.sh`, in which is the following:
```bash
# Ensure base distro defaults xdg path are set if nothing filed up some
# defaults yet.
if [ -z "$XDG_DATA_DIRS" ]; then
    export XDG_DATA_DIRS="/usr/local/share:/usr/share"
fi
```
that makes Homebrew's `glib` adjustment null and void.

Since `snapd` is [widely installed by default](https://repology.org/project/snapd/versions), I think `brew shellenv` needs to add Homebrew's `share` dir to `XDG_DATA_DIRS` if it exists, otherwise we'll likely be running into the same issue with other `glib`-enabled formulae down the line.

**Comment by lundmar** [comment]
> I can confirm this to be true even on GUI-less Ubuntu and Debian server installations with no X11 or Wayland apps installed. The "culprit" is `snapd`, a cross-distro containerised packaging platform that installs `/etc/profile.d/apps-bin-path.sh`, in which is the following:

FYI - Flatpak is equally a "culprit" in this case as it does something similar in `/etc/profile.d/flatpak.sh`.

For example, on my Ubuntu system, my XDG_DATA_DIR looks like this:
```
$ echo $XDG_DATA_DIRS 
/usr/share/ubuntu-wayland:/usr/share/gnome:/home/lundmar/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```

**Comment by MikeMcQuaid** [comment]
> * My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.

This is confusing to me given https://github.com/Homebrew/brew/blob/635a776fce1b63b1be554ca39b0cdc5911b4bd95/Library/Homebrew/extend/os/linux/diagnostic.rb#L62-L73

I'm not sure why this `brew doctor` warning was not displayed for this user.

**Comment by cho-m** [comment]
> This is confusing to me given https://github.com/Homebrew/brew/blob/635a776fce1b63b1be554ca39b0cdc5911b4bd95/Library/Homebrew/extend/os/linux/diagnostic.rb#L62-L73
> 
> I'm not sure why this `brew doctor` warning was not displayed for this user.

Wouldn't the environment variable get filtered out by `brew`?

**Comment by MikeMcQuaid** [comment]
@cho-m 🤦🏻 yes, of course. Might be worth passing this through as a `HOMEBREW_XDG_DATA_DIRS` so we can check it here?

**Comment by gromgit** [comment]
Also, `check_xdg_data_dirs` is currently scoped to Linux, but `glib` is used In various cross-platform formulae, so I think it makes sense for the check to be cross-platform as well.
