### ISSUE TITLE
boost: some compilation problems with latest  update

### ISSUE THREAD

**Issue by jcelerier** [Homebrew/homebrew-core#18001]
Would it be possible to apply the following patch ? 

https://github.com/mapnik/mapnik/issues/3744

**Comment by ilovezfs** [comment]
@jcelerier I cannot actually reproduce that build failure. Can you?

**Comment by jcelerier** [comment]
well, I originally stumbled on the mapnik post because I encountered the same build error in my software (and applying the fix locally did fix it)

**Comment by ilovezfs** [comment]
@jcelerier can you please complete the issue template?
