### ISSUE TITLE
gnupg should depend on pinentry-mac

### ISSUE THREAD

**Issue by wenzowski** [Homebrew/homebrew-core#18011]
Since the gnupg formula [already depends](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnupg.rb#L29) on a `pinentry` program, why not depend on the [pinentry-mac](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pinentry-mac.rb) formula instead, seeing as this is an excellent pinentry tool which works by default?

By currently depending on the [pinentry](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pinentry.rb) formula which installs the [gnu pinentry program](https://gnupg.org/software/pinentry/index.html) instead of the one from [GPGTools](https://github.com/GPGTools/pinentry-mac), the existing default has already caused developer confusion, as evidenced in #14737, and results in the absolutely *horrendous* `gpg: signing failed: Inappropriate ioctl for device` error, which anyone not intimately familiar with the gnupg codebase is going to have extreme difficulty debugging.

While that cryptic error criticism is indeed one of gnupg itself, I feel strongly that the homebrew formula for gnupg 2.2.0 should protect the community from this rabbit-hole by default, and default to a pinentry program that properly integrates with the OS, especially since the formula is already available.

If the community disagrees, I would ask that all dependency on a pinentry program be dropped, so the error is one of a missing pinentry program and the user is forced to read the gnu docs and choose an appropriate pinentry for their needs.

**Comment by wenzowski** [comment]
I am, ahem, opening a PR which shall ref this issue

**Comment by ilovezfs** [comment]
Thanks for the suggestion but our position on this was already explained here https://github.com/Homebrew/homebrew-core/issues/14737#issuecomment-319797811
