### ISSUE TITLE
Branches for autobump PR's should be deleted if the PR is closed

### ISSUE THREAD

**Issue by p-linnane** [Homebrew/homebrew-core#180127]
When autobump PR's are merged, the branch is automatically deleted. However, if a PR is closed, rather than being merged, the branch sticks around until one of us manually deletes it. It'd be nice to automate this so we can keep the repo cleaner and do less digital janitor work.

**Comment by ZhongRuoyu** [comment]
Turns out #177334 didn't work for PRs closed by @github-actions (like #179279) because [`GITHUB_TOKEN` events don't trigger workflow runs](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow).
