### ISSUE TITLE
RFC: Cython formula

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-core#1803]
Cython is a tool that makes it easy to write C extensions for Python and Python bindings for C libraries. It's used by a handful of formulas (see below), which install it temporarily to buildpath, since it is not needed at runtime. Building Cython is relatively slow. It would be nice to have a formula we can bottle and use as a :build dependency. Does that sound reasonable?

```
tim@rocketman:homebrew (master)$ grep -ilR --exclude-dir .git cython . | cut -d/ -f2 | sort | uniq -c
   8 homebrew-core
   1 homebrew-games
   3 homebrew-science
```

**Comment by MikeMcQuaid** [comment]
Seems like a good call to me 👍

**Comment by DomT4** [comment]
Should possibly be `keg_only` like `sphinx-doc` if the primary usage is designed to be internal (?) but otherwise 👍.

**Comment by tdsmith** [comment]
Thanks!

**Comment by physicalist** [comment]
Is there a reason this issue was closed without being resolved? The number of formulae using Cython has since increased, if anything. And it still seems like a good idea to me :)

**Comment by DomT4** [comment]
Likely that nobody either found the time or willpower to do the work. Can't remember the idea being rejected after this discussion.

**Comment by tdsmith** [comment]
Yeah, I regarded the question as settled, so I closed the ticket (and proceeded to drop the ball).
