### ISSUE TITLE
Golang 1.22.6 has been released, but I can only update to version 1.22.5 using brew

### ISSUE THREAD

**Issue by bing127** [Homebrew/homebrew-core#180329]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Golang 1.22.6 has been released, but I can only update to version 1.22.5 using brew
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Golang 1.22.6 has been released, but I can only update to version 1.22.5 using brew

### What happened (include all command output)?

Golang 1.22.6 has been released, but I can only update to version 1.22.5 using brew

### What did you expect to happen?

Golang 1.22.6 has been released, but I can only update to version 1.22.5 using brew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Golang 1.22.6 has been released, but I can only update to version 1.22.5 using brew
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
