### ISSUE TITLE
Problems with brew up

### ISSUE THREAD

**Issue by ramlev** [Homebrew/homebrew-core#18043]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
`brew up`

- What happened (include command output)

`❯ brew up
Failed to set filetime 1505074478 on outfile: errno 1
Failed to set fileFtaiilmeed  t1o5 0s5e2t9 8f4i7l1e toni moeu t1f5i0l5e3:1 1e9r7r4n oo n1
outfile: errno 1
Failed to set filetime 1505266878 on outfile: errno 1
FailedF atiol esde tt of isleett ifmiel e1t5i0m5e3 2115206543 1o7n2 4o9u tofni loeu:t feirlren:o  e1r
rno 1
Failed to set filetime 1491314592 on outfile: errno 1
Failed to set filetime 1500719840 on outfile: errno 1
Failed to set filetime 1504638112 on outfile: errno 1
Failed to set filetime 1504553860 on outfile: errno 1
Failed to set filetime 1498518953 on outfile: errno 1
Failed to set filetime 1493025614 on outfile: errno 1
Updated 2 taps (caskroom/cask, homebrew/core).

- What you expected to happen
Not to output alle the Failed.... statemenst
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by ilovezfs** [comment]
This is the same issue as https://github.com/Homebrew/brew/issues/2921 which turned out to be `remote-time` in curlrc https://github.com/Homebrew/brew/issues/2921#issuecomment-317174254
