### ISSUE TITLE
opencv source tar.gz checksum is wrong

### ISSUE THREAD

**Issue by ngutman** [Homebrew/homebrew-core#18041]
When trying to install opencv 3.3.0 the installation fails because of sha256 checksum failure:

![image](https://user-images.githubusercontent.com/1540134/30386854-964b992c-98b3-11e7-9bb9-20d6561bc1e0.png)

https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb#L5 is expecting `95029eb5578af3b20b8c7f8f6f59db1b827c2d5aaaa74b6becb1de647cbdda5a` when it's really `8bb312b9d9fd17336dc1f8b3ac82f021ca50e2034afc866098866176d985adc6`

(I'm running MacOS High Sierra but afaik it should affect anything)

**Comment by sjackman** [comment]
Thanks for the bug report. The checksums of all .tar.gz files generated by GitHub have recently changed. We're working on sorting it out. See https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745

**Comment by ilovezfs** [comment]
This was resolved in https://github.com/Homebrew/homebrew-core/pull/18048. Thanks for reporting it.
