### ISSUE TITLE
Can you please add boost 1.58 and  boost-python 1.58 to homebrew

### ISSUE THREAD

**Issue by GoingMyWay** [Homebrew/homebrew-core#18050]
Hi, this is not a bug. I found that the stable boost is 1.61.1 https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb 

however when I `brew search boost`,  I can' t install boost 1.58 and boost-python 1.58.

Can you please add boost 1.58 and boost-python 1.58 to homebrew since install boost and boost-python from source is not very easy on macos for newbies.

**Comment by GoingMyWay** [comment]
I'll close this issue since I can instlal boost 1.58 and boost-python 1.58 by editing formula via `brew edit boost` and `brew edit boost-python`.

**Comment by SanjoDeundiak** [comment]
@GoingMyWay can you explain how to do that?

**Comment by GoingMyWay** [comment]
@SanjoDeundiak  see [this issue](https://github.com/mwydmuch/ViZDoom/issues/243) and its workaround
