### ISSUE TITLE
Unable to install mongodb

### ISSUE THREAD

**Issue by manshoor** [Homebrew/homebrew-core#18071]
`brew install mongodb`

./build.sh
ssl

Building bsondump...
# command-line-arguments
/usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: /usr/local/opt/go/libexec/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: abort trap
error: invalid abbreviation code [110] for DIE at 0x000ea1c8 in '/tmp/go-link-990776186/go.o'
Assertion failed: (ref_addr_die != NULL), function AppendDependants, file /SourceCache/dwarf_utilities/dwarf_utilities-121/source/DWARFDebugInfoEntry.cpp, line 375.

## here is the full log gist

https://gist.github.com/manshoor/71dda70fb793b9daf277459c3238d901

**Comment by DomT4** [comment]
What does `go version` return? That looks suspiciously like an old error.

**Comment by DomT4** [comment]
Also if you're building stuff from source routinely ignoring [this doctor warning](https://gist.github.com/manshoor/71dda70fb793b9daf277459c3238d901#file-00-doctor-out-L9-L12) is probably unwise.

**Comment by manshoor** [comment]
Hey @DomT4 

`go version go1.9 darwin/amd64`

well, I'm currently using "os x yosemite" soon I'll update os x so xcode will be updated in that process.

**Comment by DomT4** [comment]
That's interesting. Can you provide your `brew info go`? Curious as to whether you poured it from bottle or built it from source.

**Comment by ilovezfs** [comment]
At this point we no longer support Yosemite, but if you can reproduce it on >= El Capitan, please let us know.

**Comment by manshoor** [comment]
Here is the info that you [asked for.](https://gist.github.com/manshoor/bf04f36b053380b195d7c84cf2d07a77)

Thanks @DomT4 I'll try again when os is updated

**Comment by DomT4** [comment]
`go` having been poured from bottle pretty much rules out any suspicion I had about `go` here, so yeah, let us know after you've updated macOS/Xcode.

**Comment by manshoor** [comment]
Hey, 
I installed Sierra (10.12.6) and MongoDB is installed smoothly.

**Comment by ilovezfs** [comment]
@manshoor cool! Congratulations on the upgrade and glad to hear it's working :)

We're happy to take PRs fixing this from anyone who does have to use it on <= 10.10.

**Comment by semeano** [comment]
@ilovezfs i got the same error with 10.9 (Mavericks).

```
Building bsondump...
# command-line-arguments
/usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64/link: /usr/local/Cellar/go/1.10/libexec/pkg/tool/darwin_amd64/link: running dsymutil failed: signal: abort trap
Assertion failed: (ref_addr_die != NULL), function AppendDependants, file /SourceCache/dwarf_utilities/dwarf_utilities-119/source/DWARFDebugInfoEntry.cpp, line 355.
```

**Comment by david-pureal** [comment]
@semeano Hey dude, I suffer exactly the same problem for a whole day. Finally i fixed it by updating my max OS and re-installing Xcode IDE

**Comment by semeano** [comment]
yeah i ended up upgrading macOS... it was something that i wanted to avoid but it seemed the only solution. tks!
