### ISSUE TITLE
source-highlight: cannot find input file anywhere outlang.map

### ISSUE THREAD

**Issue by kenahoo** [Homebrew/homebrew-core#18087]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
% brew config
HOMEBREW_VERSION: 1.3.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 751334a257d81851e68da7ab390982d4e9fdf909
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c010d3fdd3b111462e0c34f3efe4a9ec3e583af7
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112, 1.8.0_60, 1.7.0_75
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

```
% brew doctor                  
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5-config
  /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libtensorflow
```

`brew doctor` does have some output, but I don't think it has anything to do with the issue here.  Let me know if I'm mistaken.

I have `source-highlight` configured as shown:

```
[KenMacBook-2:~] % echo $LESS
-eiMqR
[KenMacBook-2:~] % echo $LESSOPEN
| src-hilite-lesspipe.sh %s
[KenMacBook-2:~] % which src-hilite-lesspipe.sh 
/usr/local/bin/src-hilite-lesspipe.sh
```

When I try to view a file using `less`, I always get the error `"source-highlight: cannot find input file anywhere outlang.map"`.  Even if I invoke `source-highlight` without any arguments, it seems to have this trouble:

```
[KenMacBook-2:~] % less tiles.R 
source-highlight: cannot find input file anywhere outlang.map
[KenMacBook-2:~] % source-highlight --failsafe --infer-lang -f esc --style-file=esc.style -i tiles.R  
source-highlight: cannot find input file anywhere outlang.map
[KenMacBook-2:~] % source-highlight                                                                 
source-highlight: cannot find input file anywhere outlang.map
```

If I manually add a `--data-dir` parameter to the `source-highlight` call, it doesn't complain anymore (and the output is colorized):

```
[KenMacBook-2:~] % source-highlight --failsafe --infer-lang -f esc --style-file=esc.style -i tiles.R --data-dir=/usr/local/share/source-highlight     
hexagon <- function(x, y, side, ...) {
  polygon(x=x+side/2*c(0, 1, 3, 4, 3, 1),
          y=y+side*sqrt(3)/2*c(0, -1, -1, 0, 1, 1),
          ...)
}

plot(3,3, type='n')
hexagon(2,3,1)
```

Has my configuration gotten messed up?  I'm inclined to think this is an issue with the brew recipe (or my configuration) rather than the underlying software.

**Comment by dunn** [comment]
`outlang.map` exists in the `src` directory of the tarball, but I guess `make install` doesn't copy it to the correct location.  Could you report that as a bug upstream?

**Comment by kenahoo** [comment]
I tried for a few days to open an account at savannah.gnu.org so I could report this, but their registration process seems hosed and I can't get through it.  I could try to report *that* bug, but...

**Comment by kenahoo** [comment]
This is still broken in source-highlight version 3.1.8_8.  I seem to have successfully submitted this as a bug upstream, looks like they don't require login for submitters anymore.
