### ISSUE TITLE
scipy failed to build on X.11.5

### ISSUE THREAD

**Issue by puiseux** [Homebrew/homebrew-core#1808]
here is the output of `brew config` and `brew doctor` : [https://gist.github.com/puiseux/595a2d070e400ad3cb4f9ebcc63787c7](url)

and here is the error message when i import scipy.linalg in Python :
  

> File "/usr/local/lib/python2.7/site-packages/scipy/linalg/blas.py", line 155, in <module>
>     from scipy.linalg import _fblas
> ImportError: dlopen(/usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so, 2): Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
>   Referenced from: /usr/local/lib/python2.7/site-packages/scipy/linalg/_fblas.so
>   Reason: image not found

**Comment by puiseux** [comment]
Problem solved by reinstalling last release of gcc `brew uninstall gcc numpy scipy --force` then `brew install gcc` and `brew install --build-from-source numpy scipy`

**Comment by DomT4** [comment]
Problems with formulae from taps should be reported to the tap in question rather than the core. Someone filed an issue over at the `python` tap where this lives so it's probably worth tracking that: https://github.com/Homebrew/homebrew-python/issues/303. Thanks!
