### ISSUE TITLE
homebrew-core version stuck at "git revision 34583; last commit 2017-06-22"

### ISSUE THREAD

**Issue by amio** [Homebrew/homebrew-core#18099]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/a6ede2cef96c447028462de96bbde096

To help us debug your issue please explain:
I update brew almost daily, but cannot install newest version of `youtube-dl` other than "2017.06.18". And after every time I did `brew update`, then `brew -v` I got this:
![image](https://user-images.githubusercontent.com/215282/30470930-5a338bf2-99bc-11e7-95d0-16cc0e2e8168.png)

**Comment by ilovezfs** [comment]
```
git -C $(brew --repo homebrew/core) status
```

**Comment by amio** [comment]
Oops, my bad, I was on a local development branch, not the master branch.
```
bash-3.2$ git -C $(brew --repo homebrew/core) status
On branch formula-now
Your branch and 'amio/formula-now' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
```

After switching back to master branch, everything goes fine. Thanks!
```bash
git -C $(brew --repo homebrew/core) checkout master
```
