### ISSUE TITLE
Ghc -- downloads from homebrew.bintray.com terribly slow

### ISSUE THREAD

**Issue by schroederd** [Homebrew/homebrew-core#18090]
I was attempting to install the ghc formula and it was installing terribly slow.  Testing the download URL with `wget` gave me a download rate of 7.21 KB/s.  My installation through `brew` seems to be stalled at 0.4%.

The full URL being used by homebrew is 'https://homebrew.bintray.com/bottles/ghc-8.2.1.sierra.bottle.tar.gz'

My internet connection is Comcast in Washington state.  Speedtest.net reports my connection as being from 73.254.68.*, with a download rate of around 120Mbps and upload of 12Mbps.

`brew config`: https://gist.github.com/schroederd/a6aedef1467d0900655550098843f5a6
`brew doctor`: https://gist.github.com/schroederd/887d7e83db7ab12b55e51db48e13bf5b

**Comment by ilovezfs** [comment]
Hopefully this will resolve itself but it's not something we have any control over.
