### ISSUE TITLE
Golang 1.23.0 has been released, but I can only update to version 1.22.6 using brew

### ISSUE THREAD

**Issue by bing127** [Homebrew/homebrew-core#181135]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Golang 1.23.0 has been released, but I can only update to version 1.22.6 using brew
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Golang 1.23.0 has been released, but I can only update to version 1.22.6 using brew

### What happened (include all command output)?

Golang 1.23.0 has been released, but I can only update to version 1.22.6 using brew

### What did you expect to happen?

Golang 1.23.0 has been released, but I can only update to version 1.22.6 using brew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Golang 1.23.0 has been released, but I can only update to version 1.22.6 using brew
```

**Comment by bing127** [comment]
What is the reason for the closure

**Comment by gromgit** [comment]
Perhaps because the Homebrew maintainers:
1. have been preparing for this release since rc1: #175310
2. are hampered by breaking changes in 1.23.0 (see above PR)
3. see no reason to keep "new version" issues open when the upgrade PRs are already active (see above PR)
