### ISSUE TITLE
netcdf-fortran make failure

### ISSUE THREAD

**Issue by jessequinn** [Homebrew/homebrew-core#18113]
I am trying to install netcdf and the following is the command used:

brew (re)install netcdf --build-from-source ## I use install or reinstall depending on instance 

on the make of netcdf-fortran-4.4.4 it crashes. The brew gist-logs netcdf can be found here: https://gist.github.com/367fc6a54d5b951126a60cdac156bac0

brew doctor shows a couple of warnings but nothing that should impact the make of netcdf-fortran:

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  macvim
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
Warning: Use tcl-tk instead of deprecated homebrew/dupes/tcl-tk
comp1:~ admin$ brew gist-logs netcdf

The error during the make:

gcc-4.9: error: unrecognized command line option '-fmacro-backtrace-limit=0'
make[2]: *** [fortran/CMakeFiles/netcdff.dir/nf_lib.c.o] Error 1
make[1]: *** [fortran/CMakeFiles/netcdff.dir/all] Error 2
make: *** [all] Error 2

Any ideas?

I am using for hdf5:
 CC=mpicc CXX=mpic++ FC=mpif90 brew reinstall hdf5 --enable-fortran --with-mpi --build-from-source

**Comment by ilovezfs** [comment]
>gcc-4.9

Is this reproducible with gcc-7?

**Comment by jessequinn** [comment]
I get this msg with mpicc compiled with gcc-4.9 or with gcc-4.9. I will let you know with gcc-7 makes. a difference.

**Comment by jessequinn** [comment]
OK. the problem appears to be with the hdf5:

CC=mpicc CPPFLAGS=-I/usr/local/Cellar/hdf5/1.10.1_2/include LDFLAGS=-L/usr/local/Cellar/hdf5/1.10.1_2/lib brew reinstall netcdf --build-from-source --default-fortran-flags

however, if both hdf5 and netcdf packages are compiled with gcc-4.9 it all works. Any ideas why mpicc with gcc-4.9 is causing a problem?

**Comment by jessequinn** [comment]
my guess is that --enable-parallel option is missing from the netcdf.rb

**Comment by jessequinn** [comment]
using gcc-7 has the same issues.

**Comment by fxcoudert** [comment]
`-fmacro-backtrace-limit=0` is a clang option, and GCC does not recognise it. Probably netcdf tries to use the same compilation flags as hdf5 for consistency, so if you switch compilers in-between it goes wrong.
