### ISSUE TITLE
Cannot run `brew services start mongodb`

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#18126]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

As recommended in the notes for *mongodb*, I ran `brew services start mongodb`. However, I get the following error.

```sh
$ brew services start -vvv mongodb
==> Generated plist for mongodb:
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
   <dict>
     <key>Label</key>
     <string>homebrew.mxcl.mongodb</string>
     <key>ProgramArguments</key>
     <array>
       <string>/usr/local/opt/mongodb/bin/mongod</string>
       <string>--config</string>
       <string>/usr/local/etc/mongod.conf</string>
     </array>
     <key>RunAtLoad</key>
     <true/>
     <key>KeepAlive</key>
     <false/>
     <key>WorkingDirectory</key>
     <string>/usr/local</string>
     <key>StandardErrorPath</key>
     <string>/usr/local/var/log/mongodb/output.log</string>
     <key>StandardOutPath</key>
     <string>/usr/local/var/log/mongodb/output.log</string>
     <key>HardResourceLimits</key>
     <dict>
       <key>NumberOfFiles</key>
       <integer>4096</integer>
     </dict>
     <key>SoftResourceLimits</key>
     <dict>
       <key>NumberOfFiles</key>
       <integer>4096</integer>
     </dict>
   </dict>
   </plist>
   

/bin/launchctl enable gui/499/homebrew.mxcl.mongodb
Usage: launchctl enable <service-target>
Error: Failure while executing: /bin/launchctl enable gui/499/homebrew.mxcl.mongodb
```

What's going on here?

**Comment by ilovezfs** [comment]
`brew config`? `brew doctor`?

**Comment by alexreg** [comment]
[`brew config`](https://gist.github.com/6ae612bb758d6d196af4dbc2643e5b6f)
[`brew doctor`](https://gist.github.com/2e1dae87ba38d1dca7194a4e2eb50faa)

**Comment by dunn** [comment]
What happens if you run the command specified by the plist manually?

**Comment by alexreg** [comment]
I figured out the issue: it was due to the _hombrew user owning the data/log dirs (under `/usr/local/var`), but the mongod service of course being run by root. The solution was to grant group write priveleges to the appropriate dirs under `var`.

**Comment by ilovezfs** [comment]
:tada:

**Comment by ellis** [comment]
@alexreg Can you say which command you used?  I have the same problem with postgres, but after trying to set write priveleges, I'm still getting the same error.  I ran: `chmod -R g+rwx /usr/local/var/postgres`
The group on the directories is `admin`.  Thanks if you can help!

**Comment by alexreg** [comment]
@ellis Hmm, well I'm using [brewdo](https://github.com/zigg/brewdo), so things might be working slightly differently for me. If I launch the service using `sudo brew services mongodb`, then it works. Sorry I can't help more. Do post back here if you find a solution that works for you!
