### ISSUE TITLE
SHA256 mismatch when trying to install 'wireguard-go'

### ISSUE THREAD

**Issue by phantasm** [Homebrew/homebrew-core#181317]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
=== brew config ===
HOMEBREW_VERSION: 4.3.15-106-gfbbdc1e
ORIGIN: https://github.com/Homebrew/brew
HEAD: fbbdc1e1fa443371dd0bfd1b4dff7caa5b69b106
Last commit: 2 hours ago
Core tap JSON: 15 Aug 18:45 UTC
Core cask tap JSON: 15 Aug 18:45 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.MR4VnFeMNe/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit sandybridge
Clang: 10.0.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

=== brew doctor ===
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
...
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew install wireguard-go

### What happened (include all command output)?

==> Fetching wireguard-go
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/1590d93512764bf7a821047c2f86e4995160960e/Formula/w/wireguard-go.rb
###################################################################################################################################################################### 100.0%
==> Downloading https://git.zx2c4.com/wireguard-go/snapshot/wireguard-go-0.0.20230223.tar.xz
###################################################################################################################################################################### 100.0%
Error: wireguard-go: SHA256 mismatch
Expected: ed3694e808d96720e79e17ae396f89f7c2024da07f3449ff0af8fbc6dbfa7f6a
  Actual: 50029ca43196cc3d925c0f0b98a9fcfd7f6c28465122da90ebe5262398f3b31c
    File: /Users/phantasm/Library/Caches/Homebrew/downloads/f1c31ba406a7d0c14cac90f9a2b7da36e41378900fc9b2ba1f48ee9f29b5ad0e--wireguard-go-0.0.20230223.tar.xz
To retry an incomplete download, remove the file above.

### What did you expect to happen?

I was expecting wireguard-go installation (or local build from source)
I've manually downloaded and checked tar.xz file and it definitely has different SHA256 checksum, maybe maintainer specified wrong sha256 on their end.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install wireguard-go
```

**Comment by SMillerDev** [comment]
You cut of the part where it told you not to file issues but it still applies

**Comment by phantasm** [comment]
> You cut of the part where it told you not to file issues but it still applies
I was sure it's not related to my outdated macbook, but to wrong sha256 checksum in the repo. Anyway I filed this issue to the maintainer, hope it will fix it. Maybe... Thanks for the reply.
