### ISSUE TITLE
sourceforge url audit failures

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#181398]
## Problem

from time to time, sourceforge formulae stable url checks would report 404 errors while the artifacts are accessible (the most recent one is https://github.com/Homebrew/homebrew-core/pull/179961)

**Comment by Bo98** [comment]
That error is legitimate - the URL is wrong:

```console
$ curl --head  https://downloads.sourceforge.net/project/synfig/development/1.5.2/synfig-1.5.2.tar.gz
HTTP/1.1 404 Not Found

$ curl --head  https://downloads.sourceforge.net/project/synfig/development/1.5.2/source/synfig-1.5.2.tar.gz
HTTP/1.1 302 Found
```

**Comment by cho-m** [comment]
> That error is legitimate - the URL in the formula is wrong:

Yeah, went ahead and fixed it while working on #180185.

---

Though I think we did have some formulae that consistently failed either audit or livecheck even though they worked during build.

**Comment by Bo98** [comment]
If you find any precise, reproducible examples then let me know.

**Comment by chenrui333** [comment]
the mirrors were introduced in https://github.com/Homebrew/homebrew-core/pull/65023 (I am gonna remove them in https://github.com/Homebrew/homebrew-core/pull/182122)
