### ISSUE TITLE
Boost lexical_cast library not build

### ISSUE THREAD

**Issue by melhindi** [Homebrew/homebrew-core#18150]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? 
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I want to use boost lexical_cast library
- What happened (include command output)
CMake tells me "Could not find the following Boost libraries:
          boost_lexical_cast"
AND in fact there are multiple boost-libaries, but no boost:lexical:cast in /usr/local/lib

- What you expected to happen
there should be libboost_lexical_cast.* file in /usr/local/lib
CMake should be able to find the library
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by ilovezfs** [comment]
lexical_cast is a header-only library. Just include boost/lexical_cast.hpp and you should be good to go.
