### ISSUE TITLE
Jruby 404 bin not found

### ISSUE THREAD

**Issue by GuillermoBlasco** [Homebrew/homebrew-core#18156]
When installing `jruby` a 404 error is displayed:

![image](https://user-images.githubusercontent.com/1889971/30516594-c62b2774-9b43-11e7-8f65-ff904d14cef4.png)

`brew update`  and `brew doctor` executed before as well.

**Comment by ilovezfs** [comment]
Closed via #18164.

**Comment by ilovezfs** [comment]
This should be fixed now if you `brew update`. Thanks for reporting it!

**Comment by GuillermoBlasco** [comment]
Yes, Fixed. Thanks
