### ISSUE TITLE
Unable to submit a version bump for mariadb

### ISSUE THREAD

**Issue by omame** [Homebrew/homebrew-core#181571]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.16-19-g277c425
ORIGIN: https://github.com/Homebrew/brew
HEAD: 277c4259fb5326fa13dc8d132b986be21c333b97
Last commit: 7 hours ago
Core tap HEAD: 617f90e58ea669bc46140b3a1f380f19b3c31e0e
Core tap last commit: 46 minutes ago
Core tap JSON: 18 Aug 11:02 UTC
Core cask tap JSON: 18 Aug 11:02 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_ibiza
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.6.1-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Mariadb has [published a new set of patch releases](https://mariadb.org/mariadb-11-6-1-11-5-2-11-4-3-11-2-5-11-1-6-10-11-9-10-6-19-and-10-5-26-now-available/). These should fix [an issue with innodb corruption that users are experiencing](https://www.reddit.com/r/mariadb/comments/1ekz4zh/constant_innodb_errors_missing_file_checkpoint).

I tried to use `bump-formula-pr` to bump from 11.4.2 to 11.4.3 but I received an error message stating that mariadb is managed by autobump. Thing is, I couldn't see any PRs for mariadb 11.4.3, even though [I can see others being handled just fine](https://github.com/search?q=repo%3AHomebrew%2Fhomebrew-core+mariadb&type=pullrequests&s=created&o=desc).

Maybe something is broken in autobump for mariadb?

### What happened (include all command output)?

```
$ brew bump-formula-pr -n mariadb --version 11.4.3
==> Auto-updating Homebrew...
Error: Whoops, the mariadb formula has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
  https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt
```

### What did you expect to happen?

To be able to bump the mariadb version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-formula-pr -n mariadb --version 11.4.3
```
```

**Comment by iMichka** [comment]
`mariadb`, like a lot of other packages, will get automatically updated by our bot as soon as there is a new version.
Looking at the autobump logs, the bot does not want to open another pull request as someone is already working on `mariadb` right now: https://github.com/Homebrew/homebrew-core/pull/174249

This prevents duplicate work or conflicts. In an ideal world a pull request like the above should not stay open forever and not block updates to be done.

`brew livecheck mariadb` tells me that the latest version is `11.5.2`, not `11.4.3`. So we should update to that version.

I think at this point you can open a new pull request manually to do the update if that's ok for you.

**Comment by cho-m** [comment]
> `brew livecheck mariadb` tells me that the latest version is `11.5.2`, not `11.4.3`. So we should update to that version.

Specifically `mariadb` should track rolling release (thus 11.5.2) but there should also be a new `mariadb@11.4` since it is an LTS maintained until May 2029.

**Comment by omame** [comment]
> Looking at the autobump logs, the bot does not want to open another pull request as someone is already working on mariadb right now: https://github.com/Homebrew/homebrew-core/pull/174249

Ah, I missed that. Thanks for the pointer.

> In an ideal world a pull request like the above should not stay open forever and not block updates to be done.

Agreed. It's a tricky one to solve though.

> I think at this point you can open a new pull request manually to do the update if that's ok for you.

I may, but I need to test that nothing will break in my instance during the upgrade. It'll require a little more time than a simple patch version bump.

> Specifically `mariadb` should track rolling release (thus 11.5.2) but there should also be a new `mariadb@11.4` since it is an LTS maintained until May 2029.

Indeed, I was also surprised by that. Perhaps it's worth pursuing this option rather then the above? It should be just a copy of the current formula into `mariadb@11.4` with some adjustments, right?

**Comment by pich** [comment]
@omame Are there any updates on this matter? I’m eagerly awaiting this update because there’s currently a bug that causes irreversible damage to the cluster every time MariaDB is restarted.​

**Comment by cho-m** [comment]
#181935 is essentially what I mentioned for latest in LTS and rolling releases.

In theory, there should be a brew feature where users who installed via `mariadb@11.4` should remain on that version (but may need to `brew link mariadb@11.4` afterward? maybe uninstalling/unlinking `mariadb`? haven't tested feature myself).

**Comment by pich** [comment]
As for me, I’m happy to migrate to the 11.5 rolling release  :)
