### ISSUE TITLE
git: new credential helper default causes annoying dialogs

### ISSUE THREAD

**Issue by nlfiedler** [Homebrew/homebrew-core#1815]
The change in the 2.8.4 version of the Git package seems to have introduced a default setting for credential.helper. This is problematic as it cannot be overridden with something else. Running Git LFS commands continually presents a dialog box about a failure to store credentials in the OS X keychain. Defining my own setting in ~/.gitconfig (or in the repo config) does not help. My only choice is to remove the setting in /usr/local/etc/gitconfig, which seems heavy-handed. It would seem this change should be given more consideration.

**Comment by MikeMcQuaid** [comment]
> The change in the 2.8.4 version of the Git package seems to have introduced a default setting for credential.helper.

This is the same as the `credential.helper` set by the Git Apple installs in the CLT.

> This is problematic as it cannot be overridden with something else.

This is not correct. From `git config --help`:
```
If not set explicitly with --file, there are four files where git
config will search for configuration options:
$(prefix)/etc/gitconfig
    System-wide configuration file.
$XDG_CONFIG_HOME/git/config
    Second user-specific configuration file. If $XDG_CONFIG_HOME is not
    set or empty, $HOME/.config/git/config will be used. Any
    single-valued variable set in this file will be overwritten by
    whatever is in ~/.gitconfig. It is a good idea not to create this
    file if you sometimes use older versions of Git, as support for
    this file was added fairly recently.
~/.gitconfig
    User-specific configuration file. Also called "global"
    configuration file.
$GIT_DIR/config
    Repository specific configuration file.

...

The files are read in the order given above, with last value found
taking precedence over values read earlier.
```

> Running Git LFS commands continually presents a dialog box about a failure to store credentials in the OS X keychain.

This sounds like a bug (but not one in Homebrew).

> My only choice is to remove the setting in /usr/local/etc/gitconfig, which seems heavy-handed.

That's fine to do and, as it's a configuration file, we support that. As mentioned above, though, it's quite easy to override elsewhere, is the default on the Git provided outside of Homebrew and is something that should work so may require other changes on your side.

**Comment by nlfiedler** [comment]
Hmm, strange that I am unable to override the setting. Despite what I put in my own ~/.gitconfig (which, by the way, was the first thing I tried since that is quite obvious), it still attempts to use osxkeychain and I continue to get the annoying dialog. I expect this won't be the end of this issue.

**Comment by MikeMcQuaid** [comment]
@nlfiedler What if you use `/usr/bin/git`?

**Comment by nlfiedler** [comment]
Yep, behaves identically. At least the problem does not lie strictly in Homebrew. Of course, it did work just fine before, and now I have to dig into why I can't make this override take hold. Works perfectly with settings like user.email, but apparently not with credential.helper.

**Comment by UniqMartin** [comment]
> Of course, it did work just fine before, and now I have to dig into why I can't make this override take hold. Works perfectly with settings like user.email, but apparently not with credential.helper.

This variable is cumulative so there's currently no way to reset it. Quoting from `gitcredentials(7)`:

> If there are multiple instances of the credential.helper configuration variable, each helper will be        tried in turn, and may provide a username, password, or nothing. Once Git has acquired both a        username and a password, no more helpers will be tried.

It will be possible to reset it once Git 2.9 becomes a thing, cf. https://github.com/git/git/commit/24321375cda79f141be72d1a842e930df6f41725 for details.
