### ISSUE TITLE
(Perl) echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.config/fish/config.fish causes and error

### ISSUE THREAD

**Issue by pahakalle** [Homebrew/homebrew-core#18157]
<img width="751" alt="screen shot 40" src="https://user-images.githubusercontent.com/1533244/30516671-226ed238-9b4e-11e7-82fe-992966cdb786.png">

https://github.com/Homebrew/homebrew-core/blob/aee70b9c2ee2882d03a8f45eded9d9b13d00caf5/Formula/perl.rb#L72

**Comment by pahakalle** [comment]
After installing Perl with brew, you get the info message  

>By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

> You can set that up like this:
`PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib`
`echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> #{shell_profile}`

If your shell is [Fish shell](https://fishshell.com/) this causes an error [First image].

**Comment by dunn** [comment]
I guess we should guard that caveat with a check of the user's shell, or just remove it entirely and point them to the upstream docs.

**Comment by DomT4** [comment]
> or just remove it entirely and point them to the upstream docs.

I'd be keen to avoid this, personally. There's going to be a lot of people that simply won't bother & then nonetheless get mardy that every time `perl` gets upgraded by `brew upgrade` all their installed modules get smashed.

We always get this with `fish` stuff to an extent, due it the lack of Bourne-compatibility :sob:.
