### ISSUE TITLE
odin: vendor libraries are not available on Linux

### ISSUE THREAD

**Issue by tamasd** [Homebrew/homebrew-core#182068]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config && brew doctor
HOMEBREW_VERSION: 4.3.17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3426911432b93dc46d20d910c2f4fd33cdac62a2
Last commit: 4 days ago
Core tap JSON: 22 Aug 19:53 UTC
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
SUDO_ASKPASS: /usr/libexec/openssh/gnome-ssh-askpass
Homebrew Ruby: 3.3.4 => /var/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 18.1.8
Git: 2.46.0 => /bin/git
Curl: 8.6.0 => /bin/curl
Kernel: Linux 6.10.4-201.fsync.fc40.x86_64 x86_64 GNU/Linux
OS: Fedora Linux 40.20240627.0 (Silverblue)
Host glibc: 2.39
/usr/bin/gcc: 14.2.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@11: N/A
gcc: N/A
xorg: N/A
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Compile a simple odin project with raylib

### What happened (include all command output)?

```
$ odin run .
/usr/bin/ld: cannot find -l:/var/home/linuxbrew/.linuxbrew/Cellar/odin/2024-08/libexec/vendor/raylib//linux/libraylib.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

In #164071, the prebuilt vendored libraries were removed on all platforms, but they are linked back only on macos.

**Comment by xakep8** [comment]
hey @tamasd I wish to work on this issue could you help me by giving an overview of it?

**Comment by SMillerDev** [comment]
> In https://github.com/Homebrew/homebrew-core/pull/164071, the prebuilt vendored libraries were removed on all platforms, but they are linked back only on macos.

This line at the end of the issue is a pretty clear description of the issue.
