### ISSUE TITLE
certbot is missing standard plugins in the current distribution

### ISSUE THREAD

**Issue by spelletier** [Homebrew/homebrew-core#18227]
certbot is missing standard plugins in the current distribution

I tried to edit the formula by adding the missing plugin source directories in this array at the edit of the formula:

>     # Shipped with certbot, not external resources.
>     %w[acme certbot-apache certbot-nginx].each do |r|

with this array: 

>     # Shipped with certbot, not external resources.
>     %w[acme certbot-apache certbot-nginx certbot-dns-cloudflare certbot-dns-cloudxns certbot-dns-digitalocean certbot-dns-dnsimple certbot-dns-dnsmadeeasy certbot-dns-google certbot-dns-luadns certbot-dns-nsone certbot-dns-rfc2136 certbot-dns-route53].each do |r|

I compiled and installed the bottle successfully:

> brew -v install --build-bottle certbot
> brew postinstall certbot

Now certbot is not longer working, it fail with error like this:

> An unexpected error occurred:
> DistributionNotFound: The 'boto3' distribution was not found and is required by the application

The missing distribution name change when I add or remove plugin directories. Seems like some dependency problems but I have no idea how to resolve them.

**Comment by ilovezfs** [comment]
@spelletier see https://github.com/Homebrew/homebrew-core/pull/18228.

**Comment by ilovezfs** [comment]
@spelletier you can use the formula from #18228 but until we see more demand for the extra plugins, I'm not willing to have us maintain them in the formula, and their assortment of extra resources at this time.

**Comment by spelletier** [comment]
OK, thank you, it worked fine and now I know how to edit the formula to add the plugin I need.

**Comment by JasonLunn** [comment]
@ilovezfs 👍 More demand for the extra plugins
