### ISSUE TITLE
is there a package for https://github.com/scdl-org/scdl? 

### ISSUE THREAD

**Issue by frranck** [Homebrew/homebrew-core#182334]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1e560120a65be3b3c7b8a42083d54f795e1d0ec4
Last commit: 3 weeks ago
Core tap JSON: 05 Aug 16:57 UTC
Core cask tap JSON: 05 Aug 16:57 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_blizzard_avalanche
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A


Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  meld
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Hello is there a package for this https://github.com/scdl-org/scdl ? 
I have a scdl program installed by brew but it's a different (and outdated) one.

### What happened (include all command output)?

scdl not the one expected

### What did you expect to happen?

I would like to know how to install the updated maybe different project with brew

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
n/a
```

**Comment by carlocab** [comment]
It doesn't look like it.

You can browse the existing packages at https://formulae.brew.sh.

In future, please ask questions like this at https://github.com/orgs/Homebrew/discussions.

**Comment by idleberg** [comment]
Added in https://github.com/Homebrew/homebrew-core/pull/230322 

See https://formulae.brew.sh/formula/scdl

**Comment by frranck** [comment]
Thank you!
