### ISSUE TITLE
kibana fails to build on macOS 10.13

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#18259]
Error occurs during `npm install -ddd --build-from-source`:

```
npm verb If you need help, you may report this error at:
npm verb     <https://github.com/npm/npm/issues>
npm verb stack Error: version not found: jquery@2.0.3
npm verb stack     at setData (/usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/lib/cache/add-named.js:138:12)
npm verb stack     at RES (/usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
npm verb stack     at f (/usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/node_modules/once/once.js:25:25)
npm verb stack     at fixName (/usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/lib/cache/add-named.js:30:5)
npm verb stack     at /usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
npm verb stack     at saved (/usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
npm verb stack     at /usr/local/Cellar/kibana/5.6.1/libexec/node/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
npm verb stack     at FSReqWrap.oncomplete (fs.js:123:15)
npm verb statusCode 404
npm verb cwd /private/tmp/kibana-20170919-31273-n2rkzh
npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/Cellar/kibana/5.6.1/libexec/node/bin/node" "/usr/local/Cellar/kibana/5.6.1/libexec/node/bin/npm" "install" "-ddd" "--build-from-source" "--cache=/Users/fx/Library/Caches/Homebrew/npm_cache"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! version not found: jquery@2.0.3
```

Full logs available here: https://gist.github.com/c61b846ed1904bc5ca87060c75e59a77

Poke @jasontedor

**Comment by chrmoritz** [comment]
I can't reproduce this locally on 10.13 GM (kibana@5.6.1 builds fine for me from source). The error doesn't look like something which should be macOS version dependent too.

Is there a way to get the complete npm output? (there is missing output in the middle replaced by a `[...snip...]`).

**Comment by ilovezfs** [comment]
@DomT4 can you reproduce this?

**Comment by DomT4** [comment]
Still building. Should know one way or another soon hopefully :sweat_smile:.

**Comment by DomT4** [comment]
I forgot `kibana` triggers about 100 Little Snitch connection alerts, hence the delay as the build waited for me to approve them. But eventually:

```
==> Summary
🍺  /usr/local/Cellar/kibana/5.6.1: 34,456 files, 189.0MB, built in 50 minutes 1 second
```

**Comment by DomT4** [comment]
It's not relevant to this issue, but `kibana` seems to have a soft Xcode dependency. I currently don't have Xcode installed because I'm switching over the MAS version of 9.0 to make updates easier in future, and running `brew test kibana` throws out:

```
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/'
==> /usr/local/Cellar/kibana/5.6.1/bin/kibana -V
```

**Comment by chrmoritz** [comment]
The connection alerts are caused by [running the node test suite](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kibana.rb#L24) in the kibana formula.

**Comment by DomT4** [comment]
Also all the fetching around `npm` stuff, since we don't vendor resources for `npm`, for entirely sensible reasons. There's connections to GitHub there over `https://`, `git://` and obviously to the `npm` registry itself.

**Comment by fxcoudert** [comment]
Temporary issue, built on the third try!
