### ISSUE TITLE
What's with the Ruby Versions?

### ISSUE THREAD

**Issue by takuhii** [Homebrew/homebrew-core#18274]
When I run `brew doctor` I get this;

Warning: Ruby version 2.3.3 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.0, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.

But I am running Ruby 2.4.1...

**Comment by ilovezfs** [comment]
The ruby you have installed via Homebrew isn't related to that message. This will soon be resolved by https://github.com/Homebrew/brew/pull/3164.

**Comment by takuhii** [comment]
I don't use Homebrew to manage Ruby though... I use RBenv and configure it depending on my need manually...

**Comment by ilovezfs** [comment]
Homebrew itself uses ruby on the backend. This has nothing to do with packages you install or how you manage ruby.

**Comment by takuhii** [comment]
Ah ok, thought it might be, just wanted calrification. Thank you very much for your help :)

**Comment by ilovezfs** [comment]
You're welcome :)
