### ISSUE TITLE
Version is stale for two days

### ISSUE THREAD

**Issue by n0tf0und** [Homebrew/homebrew-core#182895]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
ESPHome is at 2024.8.1
Homebrew is at 2024.7.2
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

update ESPHome using Homebrew

### What happened (include all command output)?

Homebrew shows 2024.7.2 using Info

### What did you expect to happen?

update to 2024.8.1

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew should help resolve this.

**Comment by shaunplee** [comment]
It seems like autobump was taking care of version updates:
https://github.com/Homebrew/homebrew-core/commits/master/Formula/e/esphome.rb

When I try `brew bump esphome` I get:
```
❯ brew bump esphome
==> esphome
Formula is autobumped so will have bump PRs opened by BrewTestBot every ~3 hours.
```

According to https://esphome.io/changelog/2024.8.0.html, esphome 2024.8.0 was released on August 21 and 2024.8.1 was released on August 28, but BrewTestBot last generated a [PR to bump esp home to 2024.7.3](https://github.com/Homebrew/homebrew-core/pull/179169).

Is there something wrong with the current formula that's keeping it from being auto bumped by BrewTestBot?

**Comment by carlocab** [comment]
Looks like @BrewTestBot doesn't want to open a new PR because there's an existing open one for esphome at #180587. See https://github.com/Homebrew/homebrew-core/actions/runs/10625689274/job/29456044912#step:7:32.

Feel free to open a PR manually that updates it.

**Comment by n0tf0und** [comment]
Homebrew on my mac now delivers the current version.

**Comment by carlocab** [comment]
Version bump due to @shaunplee. Thanks Shaun!
