### ISSUE TITLE
Handbrake formula outdated

### ISSUE THREAD

**Issue by theDanielJLewis** [Homebrew/homebrew-core#182987]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I'm just a user trying to get Homebrew to offer Handbrake 1.8.2 instead of the version currently in Homebrew (1.7.3).

I tried using `bump-formula-pr` but kept getting the error "This formula is not in a tap!"

I want only trying to help by submitting a version bump, but I give up.

### What happened (include all command output)?

Error: This formula is not in a tap!

### What did you expect to happen?

I really don't know, but something that would let me bump up the version for the Handbrake formula to the current version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-formula-pr -d handbrake
```

**Comment by daeho-ro** [comment]
The correct command is
```
brew bump --open-pr --formula handbrake
```
and here is the PR
- https://github.com/Homebrew/homebrew-core/pull/183026

Btw, it was failed to build and have to be fixed correctly.
- https://github.com/Homebrew/homebrew-core/pulls?q=is:pr+handbrake+is:closed

**Comment by theDanielJLewis** [comment]
That is not at all what the documentation says to do.

Actually, the documentation was rather unhelpful. Thus why I gave up and I'm hoping someone else can bump the version up.

**Comment by theDanielJLewis** [comment]
```
$ brew bump --open-pr --formula handbrake
…
Error: These formulae are not in any locally installed taps!

  handbrake

You may need to run `brew tap` to install additional taps.
```

**Comment by daeho-ro** [comment]
What is the output of `brew doctor` and `brew tap --list`?

**Comment by ZhongRuoyu** [comment]
You need to do `brew tap --force homebrew/core` beforehand. I agree that the documentation may not have been clear about that, but you can make it more helpful by improving it.

**Comment by daeho-ro** [comment]
@theDanielJLewis The formula is failed to build and so cannot update the version. You can try to install the cask version of handbrake,
