### ISSUE TITLE
Formula cannot find certain libraries

### ISSUE THREAD

**Issue by xionglingfeng** [Homebrew/homebrew-core#1833]
**I am not talking about `libfreenect2`. It is just an example.**

The behaviour of `cmake` is different between running it directly in terminal and running it with `homebrew` formula.

For example, I wrote a formula to install `libfreenect2`. The formula complain about it cannot find `CUDA` and `libusb` when I install it with `brew install libfreenect2.rb --HEAD -v`. But if I copy the `cmake` command line from `brew install` and run it directly in terminal, it works.

Install with `brew`:

	$ brew install --HEAD -v libfreenect2.rb 
	==> Cloning https://github.com/OpenKinect/libfreenect2.git
	Updating /Users/xxxx/Library/Caches/Homebrew/libfreenect2--git
	git config remote.origin.url https://github.com/OpenKinect/libfreenect2.git
	git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
	git fetch origin
	==> Checking out branch master
	git checkout -f master --
	Already on 'master'
	Your branch is up-to-date with 'origin/master'.
	git reset --hard origin/master
	HEAD is now at 83f88b4 Update author list for 0.2 release
	==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/Volumes/Application/homebrew/Cellar/libfreenect2/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DLibUSB_INCLUDE_DIRS=/Volumes/Application/homebrew/Cellar/libusb/1.0.20/include/libusb-1.0
	-- The C compiler identification is AppleClang 7.0.2.7000181
	-- The CXX compiler identification is AppleClang 7.0.2.7000181
	-- Check for working C compiler: /Volumes/Application/homebrew/Library/ENV/4.3/clang
	-- Check for working C compiler: /Volumes/Application/homebrew/Library/ENV/4.3/clang -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /Volumes/Application/homebrew/Library/ENV/4.3/clang++
	-- Check for working CXX compiler: /Volumes/Application/homebrew/Library/ENV/4.3/clang++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- using tinythread as threading library
	-- Found PkgConfig: /Volumes/Application/homebrew/bin/pkg-config (found version "0.29.1") 
	-- Checking for module 'libusb-1.0'
	--   No package 'libusb-1.0' found
	CMake Error at /Volumes/Application/homebrew/Cellar/cmake/3.5.2/share/cmake/Modules/FindPkgConfig.cmake:363 (message):
	  A required package was not found
	Call Stack (most recent call first):
	  /Volumes/Application/homebrew/Cellar/cmake/3.5.2/share/cmake/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
	  cmake_modules/FindLibUSB.cmake:21 (PKG_CHECK_MODULES)
	  CMakeLists.txt:93 (FIND_PACKAGE)

	-- Configuring incomplete, errors occurred!
	See also "/tmp/libfreenect2-20160608-67252-1nuysow/build/CMakeFiles/CMakeOutput.log".
	==> Formula
	Path: /Volumes/Workspace/libfreenect2.rb
	==> Configuration
	HOMEBREW_VERSION: 0.9.9
	ORIGIN: https://github.com/Homebrew/brew.git
	HEAD: fe894678322261a285ec51a27c1fb766061dee67
	Last commit: 5 hours ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: 7ac0c366a11d76deaea5961b875de67660146929
	Core tap last commit: 4 hours ago
	HOMEBREW_PREFIX: /Volumes/Application/homebrew
	HOMEBREW_REPOSITORY: /Volumes/Application/homebrew
	HOMEBREW_CELLAR: /Volumes/Application/homebrew/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: quad-core 64-bit haswell
	Clang: 7.0 build 700
	Perl: /usr/bin/perl
	Python: /Volumes/Application/homebrew/bin/python => /Volumes/Application/homebrew/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	Java: N/A
	System Ruby: 2.0.0-p648
	OS X: 10.11.5-x86_64
	Xcode: 7.2.1 => /Applications/Xcode7.2.app/Contents/Developer
	CLT: N/A
	X11: 2.7.8 => /opt/X11
	==> ENV
	HOMEBREW_CC: clang
	HOMEBREW_CXX: clang++
	SDKROOT: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
	MAKEFLAGS: -j4
	CMAKE_PREFIX_PATH: /Volumes/Application/homebrew/opt/jpeg-turbo:/Volumes/Application/homebrew
	CMAKE_INCLUDE_PATH: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2:/Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/apache2:/Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
	CMAKE_LIBRARY_PATH: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
	CMAKE_FRAMEWORK_PATH: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks
	MACOSX_DEPLOYMENT_TARGET: 10.11
	PKG_CONFIG_PATH: /Volumes/Application/homebrew/opt/libusb/lib/pkgconfig:/Volumes/Application/homebrew/opt/glfw3/lib/pkgconfig
	PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/Volumes/Application/homebrew/Library/ENV/pkgconfig/10.11
	HOMEBREW_SDKROOT: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
	ACLOCAL_PATH: /Volumes/Application/homebrew/share/aclocal
	PATH: /Volumes/Application/homebrew/Library/ENV/4.3:/Volumes/Application/homebrew/opt/cmake/bin:/Volumes/Application/homebrew/opt/pkg-config/bin:/Volumes/Application/homebrew/opt/jpeg-turbo/bin:/usr/bin:/bin:/usr/sbin:/sbin

	Error: libfreenect2 HEAD did not build

Install directly with `cmake`:

	$ cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/Volumes/Application/homebrew/Cellar/libfreenect2/HEAD -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DLibUSB_INCLUDE_DIRS=/Volumes/Application/homebrew/Cellar/libusb/1.0.20/include/libusb-1.0
	-- The C compiler identification is AppleClang 7.0.2.7000181
	-- The CXX compiler identification is AppleClang 7.0.2.7000181
	-- Check for working C compiler: /Applications/Xcode7.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
	-- Check for working C compiler: /Applications/Xcode7.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /Applications/Xcode7.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
	-- Check for working CXX compiler: /Applications/Xcode7.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- using tinythread as threading library
	-- Found PkgConfig: /Volumes/Application/homebrew/bin/pkg-config (found version "0.29.1") 
	-- Checking for module 'libusb-1.0'
	--   Found libusb-1.0, version 1.0.20
	-- Checking for modules 'libva;libva-drm'
	--   No package 'libva' found
	--   No package 'libva-drm' found
	-- Found JPEG: /Volumes/Application/homebrew/lib/libjpeg.dylib  
	-- Could NOT find TegraJPEG (missing:  TegraJPEG_LIBRARIES TegraJPEG_INCLUDE_DIRS TegraJPEG_L4T_OK TegraJPEG_DRIVER_OK TegraJPEG_WORKS) 
	-- Could NOT find TurboJPEG (missing:  TurboJPEG_LIBRARIES TurboJPEG_INCLUDE_DIRS TURBOJPEG_WORKS) 
	-- Checking for module 'glfw3'
	--   Found glfw3, version 3.1.2
	-- Found OpenGL: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework  
	-- Looking for CL_VERSION_2_0
	-- Looking for CL_VERSION_2_0 - not found
	-- Looking for CL_VERSION_1_2
	-- Looking for CL_VERSION_1_2 - not found
	-- Looking for CL_VERSION_1_1
	-- Looking for CL_VERSION_1_1 - not found
	-- Looking for CL_VERSION_1_0
	-- Looking for CL_VERSION_1_0 - not found
	-- Found OpenCL: /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework  
	-- Looking for pthread.h
	-- Looking for pthread.h - found
	-- Looking for pthread_create
	-- Looking for pthread_create - found
	-- Found Threads: TRUE  
	-- Found CUDA: /usr/local/cuda (found version "7.5") 
	-- RPATH set to /Volumes/Application/homebrew/Cellar/libusb/1.0.20/lib
	-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
	-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
	-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
	-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
	-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
	-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
	-- Linking with these libraries: 
	 /Volumes/Application/homebrew/Cellar/libusb/1.0.20/lib/libusb-1.0.dylib
	 pthread
	 /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/VideoToolbox.framework
	 /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreFoundation.framework
	 /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreMedia.framework
	 /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreVideo.framework
	 /Volumes/Application/homebrew/Cellar/glfw3/3.1.2/lib/libglfw3.dylib
	 /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework
	 /Applications/Xcode7.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework
	 /usr/local/cuda/lib/libcudart_static.a
	 -Wl,-rpath,/Volumes/Application/homebrew/cuda/lib
	-- Found Doxygen: /Volumes/Application/homebrew/bin/doxygen (found version "1.8.11") 
	-- Configurating examples
	-- Using in-tree freenect2 target
	-- Checking for module 'libopenni2'
	--   No package 'libopenni2' found
	-- Could NOT find OpenNI2 (missing:  OpenNI2_LIBRARY_DIR OpenNI2_INCLUDE_DIRS) 
	-- Feature list:
	--   CUDA    yes
	--   CXX11    disabled
	--   Examples    yes
	--   FLAG_SEARCH_PATHS_FIRST    1
	--   OpenCL    yes
	--   OpenGL    yes
	--   OpenNI2    no
	--   TegraJPEG    no
	--   Threading    tinythread
	--   TurboJPEG    no
	--   VAAPI    no
	--   VideoToolbox    yes
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /Volumes/Workspace/libfreenect2-git/build

libfreenect2.rb:

    class Libfreenect2 < Formula
      desc "Drivers and libraries for the Xbox Kinect device version 2"
      homepage "http://openkinect.org"
      head "https://github.com/OpenKinect/libfreenect2.git"
      url "https://github.com/OpenKinect/libfreenect2/archive/v0.1-rc1.tar.gz"
      sha256 "ae337fc301b506f87a9bfb4baad891600e464c81abae3c646e201ed7720a3305"

      option :universal

      depends_on "cmake" => :build
      depends_on "pkg-config" => :build
      depends_on "libusb"
      depends_on "jpeg-turbo"
      depends_on "homebrew/versions/glfw3"

      def install
        args = std_cmake_args

        if build.universal?
          ENV.universal_binary
          args << "-DCMAKE_OSX_ARCHITECTURES=#{Hardware::CPU.universal_archs.as_cmake_arch_flags}"
        end

        mkdir "build" do
          args << "-DLibUSB_INCLUDE_DIRS=#{Formula["libusb"].include}/libusb-1.0"
          system "cmake", "..", *args
          system "make", "install"
        end
      end
    end

**Comment by rakkesh** [comment]
Check out the previous attempt of introducing `libfreenect2` formula into Homebrew core - https://github.com/Homebrew/legacy-homebrew/pull/48614.

```rb
class Libfreenect2 < Formula
  desc "Drivers and libraries for the Xbox One Kinect 2 device"
  homepage "https://github.com/OpenKinect/libfreenect2"
  url "https://github.com/OpenKinect/libfreenect2/archive/v0.2.0.tar.gz"
  sha256 "344019f4360d3858f4c5843e215b0b9d0c0d396a2ebe5cb1953c262df4d9ff54"

  head "https://github.com/OpenKinect/libfreenect2.git"

  option :universal

  depends_on "cmake" => :build
  depends_on "pkg-config" => :build
  depends_on "libusb"
  depends_on "jpeg-turbo"
  depends_on "homebrew/versions/glfw3" # => :optional

  def install
    args = std_cmake_args

    inreplace "CMakeLists.txt", /FIND_PACKAGE\(LibUSB REQUIRED\)/, ""
    inreplace "CMakeLists.txt", /FIND_PACKAGE\(GLFW3\)/, "SET(GLFW3_FOUND 1)"

    if build.universal?
      ENV.universal_binary
      args << "-DCMAKE_OSX_ARCHITECTURES=#{Hardware::CPU.universal_archs.as_cmake_arch_flags}"
    end

    mkdir "build" do
      args << "-DLibUSB_INCLUDE_DIRS=#{Formula["libusb"].include}/libusb-1.0"
      args << "-DLibUSB_LIBRARIES=usb-1.0"
      args << "-DGLFW3_INCLUDE_DIRS=#{Formula["glfw3"].include}/GLFW"
      args << "-DGLFW3_LIBRARIES=glfw3"
      system "cmake", "..", *args
      system "make", "install"
      bin.install Dir["bin/*"]
    end
  end

  test do
    system "#{bin}/Protonect", "--version"
  end
end
```

**Comment by xionglingfeng** [comment]
@rakkesh Thanks for your reply, but I am talking about the wired behaviour of `cmake` in `homebrew`. The script you posted monkey patched `CMakeLists.txt`, which neither solved or explained the wired behaviour of `cmake`......
I can successfully install `libfreenect2` with an older attempt (https://github.com/Homebrew/homebrew-head-only/pull/153), it worked perfectly for the current version. I just want to find a more elegant solution, at least an explanation, for the previous issue.

**Comment by ilovezfs** [comment]
Have you tried this with brew in the default /usr/local prefix?

**Comment by rakkesh** [comment]
Yes, here is the failure at `cmake` step, https://gist.github.com/326f9685dfa1eb761470a3e379fdde7f.

p.s. - `cmake` finds `libusb` when not using a `Hombrew` formula.

**Comment by xionglingfeng** [comment]
@ilovezfs no I didn't. Is this related?

**Comment by ilovezfs** [comment]
@xionglingfeng I'm not sure yet, but the non-standard prefix and separate volume stood out as possible issues. @rakkesh seems to be indicating those are not related. I haven't investigated further myself.

**Comment by xionglingfeng** [comment]
@ilovezfs idk if it is related, but it seems the formula is a quite standard one (mine in `homebrew-head`, or his)... compare to the one `OpenCV` used, it seems they use same way for declaring requirement of `CUDA`.

**Comment by apjanke** [comment]
> I am not talking about libfreenect2. It is just an example.

Because of how `cmake` works, it can be hard or impossible to separate the behavior of `cmake` from the specific package you're using it to install. CMake is largely a collection of "modules" which contain basically arbitrary code for looking up various things. And CMake allows packages to supply their own CMake modules to be used along with or instead of the standard ones, so its behavior can depend on what package you're running it against. This is the case here. You can see it in the second line of the call stack.

```
-- Checking for module 'libusb-1.0'
--   No package 'libusb-1.0' found
CMake Error at /Volumes/Application/homebrew/Cellar/cmake/3.5.2/share/cmake/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /Volumes/Application/homebrew/Cellar/cmake/3.5.2/share/cmake/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  cmake_modules/FindLibUSB.cmake:21 (PKG_CHECK_MODULES)
  CMakeLists.txt:93 (FIND_PACKAGE)
```

That `FindLibUSB.cmake` module is supplied by `libfreenect2`, not standard CMake. Inside `libfreenect2`'s `FindLibUSB.cmake`, it's fiddling with the `PKG_CONFIG_PATH` environment variable before calling `PKG_CHECK_MODULES`.

```
IF(PKG_CONFIG_FOUND)
  IF(DEPENDS_DIR) #Otherwise use System pkg-config path
    SET(ENV{PKG_CONFIG_PATH} "${DEPENDS_DIR}/libusb/lib/pkgconfig")
  ENDIF()
...

  PKG_CHECK_MODULES(LibUSB ${LibUSB_REQUIRED} ${MODULE})
```

This may be a problem under `brew` because Homebrew itself uses `$PKG_CONFIG_PATH` to set up a path with just the formula's dependencies when running under superenv. When `libfreenect2` clobbers it, libusb and other dependencies are no longer visible to `pkg-config`.

It may be working outside of `brew` because outside superenv, `pkg-config` may see everything under `/usr/local/lib/pkgconfig` by default, instead of just the system libraries.

The fix might be to have `libfreenect2`'s `FindLibUSB.cmake` prepend to `$PKG_CONFIG_PATH` instead of clobbering it entirely. Its `FindGLFW3.cmake` is doing similar.

```
[~/local/opp/libfreenect2 on ⇄ master]
$ grep -r PKG_CONFIG_PATH *
cmake_modules/FindGLFW3.cmake:    SET(ENV{PKG_CONFIG_PATH} "/usr/local/opt/glfw3/lib/pkgconfig:/opt/local/lib/pkgconfig")
cmake_modules/FindGLFW3.cmake:  SET(ENV{PKG_CONFIG_PATH} "${DEPENDS_DIR}/glfw/lib/pkgconfig:$ENV{PKG_CONFIG_PATH}")
cmake_modules/FindLibUSB.cmake:    SET(ENV{PKG_CONFIG_PATH} "${DEPENDS_DIR}/libusb/lib/pkgconfig")
```

Rakkesh's formula file looks like it works because it removes the calls to `libfreenect`'s custom `FindLibUSB` and `FindGLFW3` and supplies the needed flags directly. Same with xionglingfeng's linked "older attempt".

I would probably submit this as an upstream bug to `libfreenect2`.

**Comment by xionglingfeng** [comment]
@apjanke Thanks for your detail answer. I'm looking forward to see your patch in `libfreenect2` :-)

**Comment by DomT4** [comment]
Closing as Andrew's answer seemed to cover the bases here, and it's not (yet) a problem with a Homebrew formula. If you can get things fixed, we'll happily review a PR for that though.
