### ISSUE TITLE
gnuplot: PDF terminal does not get build with --with-pdflib-lite

### ISSUE THREAD

**Issue by omni-vi** [Homebrew/homebrew-core#18333]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[https://gist.github.com/86a596cb28e8ee6fb7868919fd038d65](https://gist.github.com/86a596cb28e8ee6fb7868919fd038d65)
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install and use gnuplot to create pdf files

- What happened (include command output)
The pdf terminal did not get build

- What you expected to happen
I expected the terminal to get build. [Terminals which were actually build](https://gist.github.com/omni-vi/2c80aca4d6249ae1acc53b2a3901392e)

- Step-by-step reproduction instructions (by running `brew install` commands)
1. install gnuplot
`~$ brew install gnuplot --with-qt --without-lua --with-pdflib-lite`
2. open gnuplot
3. check available terminals
`set term`
4. you should see the pdf terminal

**Comment by ilovezfs** [comment]
The `pdfcairo` terminal (`--with-cairo`) may do what you want. I think the `pdflib-lite` term is no longer a thing.

**Comment by ilovezfs** [comment]
I've removed the option in https://github.com/Homebrew/homebrew-core/issues/18333. Thanks for reporting this @omni-vi!
