### ISSUE TITLE
shared-mime-info: uninstall complains that it's used but brew doesn't think so

### ISSUE THREAD

**Issue by iamitava** [Homebrew/homebrew-core#18353]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Note**: `brew config` and other output at https://gist.github.com/iamitava/97d2e225889c78270f0610c5f18905fc

To help us debug your issue please explain:

- What you were trying to do (and why)

  Tried to uninstall `shared-mime-info` since `brew uses --installed` reports no users.

  ```
  $ brew uses --installed shared-mime-info
  <no output>
  ```

- What happened (include command output)

  `brew uninstall` gave an error that it's being used by `librsvg`.

  ```
  $ brew uninstall shared-mime-info
  Error: Refusing to uninstall /usr/local/Cellar/shared-mime-info/1.9
  because it is required by librsvg 2.40.18, which is currently installed.
  ```

  However, `brew info librsvg` / `brew deps librsvg` don't show `shared-mime-info` as a dependency.

- What you expected to happen

  Expected `shared-mime-info` to be uninstalled.

- Step-by-step reproduction instructions (by running `brew install` commands)

  Not sure what installed this.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
@tschoonj 

In #5582 I added `shared-mime-info` as a dependency of `gdk-pixbuf` to fix #5482.

In #16999 you removed it. Do you know if #5482 is no longer an issue?

**Comment by tschoonj** [comment]
Have a look at https://github.com/GNOME/gdk-pixbuf/blob/master/configure.ac#L673-L677

You will see that for Darwin they set `gio_can_sniff` to `no`, which means that `shared-mime-info` is not a dependency.

This change was introduced in https://github.com/GNOME/gdk-pixbuf/commit/4c63e6fea6ceda96af72c9931d49c7c002c6607b#diff-67e997bcfdac55191033d57a16d1408a

**Comment by ilovezfs** [comment]
@tschoonj cool. So we can just rebuild librsvg and this will go away.

**Comment by ilovezfs** [comment]
@iamitava this is now fixed if you
```
brew update
brew reinstall librsvg
brew uninstall shared-mime-info
```
