### ISSUE TITLE
Can't use Homebrew for external scripts because of env vars?

### ISSUE THREAD

**Issue by zenspider** [Homebrew/homebrew-core#1838]
```ruby
prefix = `brew --prefix`.chomp
$:.unshift "#{prefix}/Library/Homebrew"
require "global"
```

results in:

```
# .../Homebrew/os/mac.rb:27:in `full_version': undefined method `chomp' for nil:NilClass (NoMethodError)
#       from .../Homebrew/os.rb:17:in `<module:OS>'
#       from .../Homebrew/os.rb:1:in `<top (required)>'
#       from .../Homebrew/global.rb:7:in `<top (required)>'
#       from brew.rb:5:in `<main>'
```

because I am not running `brew` which sources `brew.sh` which sets a bunch of environment variables before exec'ing to `brew.rb`. I would recommend trying to push what you can down to `global.rb` or at least making those methods fall back a bit more gracefully. Suggestions on how to write such a script?

**Comment by DomT4** [comment]
Please re-file this over at https://github.com/Homebrew/brew. The `homebrew-core` tap only handles formulae.
