### ISSUE TITLE
root compilation fails after update to Xcode and Command Line Tools Version 9.0

### ISSUE THREAD

**Issue by matthewkenzie** [Homebrew/homebrew-core#18388]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

--------------------------------------------------------------------------------------

- Trying to install HEAD version of root (from homebrew-core) on MacOS 10.12.6 after (perhaps foolishly) updating Xcode and Command Line Tools to Version 9.0
- Build fails but not sure why
- I expected it to build ok
- I was running brew install -vd root --HEAD

- General brew commands work fine
- I ran brew update twice 
- I ran brew doctor (no issue - i.e. got "Your system is ready to brew.")
- the output of brew gist-logs root can be found here: https://gist.github.com/matthewkenzie/62e1869316d36d1da235daa445c4875d

**Comment by soleti** [comment]
Applying these two patches

- https://github.com/root-project/root/commit/e16c3fd309e375e8aa781a6495a74a3f89b0cb25
- https://github.com/root-project/root/commit/263508429dec26449513914e71f0f71c9ce9485f

should fix your problem. However, I get several errors like this
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:314:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^```
Complete gist available here: https://gist.github.com/soleti/fb9f29b969fdc047c9ef7e026ccae276

**Comment by ilovezfs** [comment]
Please report this upstream.

**Comment by ilovezfs** [comment]
@soleti did you apply https://github.com/root-project/root/commit/9339de9e644b06d5f77607f83aea118969cab7b6 yet

**Comment by soleti** [comment]
Yes, sorry, forgot to mention it. My issue seems related to some problems with <cmath>. Apparently it does not put ::signbit in the standard namespace

**Comment by ilovezfs** [comment]
Definitely report it upstream since they're probably thinking about cutting a release soon.

**Comment by ilovezfs** [comment]
Closing this out as it's an upstream issue.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by davidchall** [comment]
@ilovezfs We might be experiencing a related problem in https://github.com/Homebrew/homebrew-science/pull/6382. Could you please explain what was changed in Homebrew (referenced in your most recent comment), which fixed this issue?

**Comment by abhih1** [comment]
@soleti even I'm getting an error related to cmath. I tried brew update and brew upgrade, but to no avail. 
I'm using Xcode 9.1 and root 6.09/01 on macos high sierra.
Any help please?!

**Comment by lozelin** [comment]
@abhih1 I am also having an error related to cmath. 

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
138 using ::signbit
And so on...

Was there any solution to this issue?

**Comment by abhih1** [comment]
@lozelin I fixed mine by reinstalling root, to be compatible with the new Xcode update.
Good luck!
