### ISSUE TITLE
fontforge fails to install. Can't find "mem.h"

### ISSUE THREAD

**Issue by tabair-addepar** [Homebrew/homebrew-core#18398]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) **Install fontforge to edit fonts**
- What happened (include command output) **Install failed during make** because "mem.h" couldn't be found.  See below for command output.
- What you expected to happen **Install to succeed :p**
- Step-by-step reproduction instructions (by running `brew install` commands) **See output below**

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

# Why Is The `brew doctor` Item Not Checked?
I ran `brew doctor` but I haven't gotten rid of all the errors.  The warnings about deprecated stuff that have to do with "boxen" are caused by a poorly maintained tool installed by my employer.  They should be ignorable.

The last warning about keg-only formula that is linked is for openssl, and it seems like unlinking it does nothing.  Below is the output of a dry run of the unlink command.
```
~/workspace$ brew unlink --dry-run openssl
Would remove:
```

Finally, the first warning: "Putting non-prefixed coreutils in your path can cause gmp builds to fail." is not likely to be the culprit.  I've run the command without coreutils in my path and gotten the same results before.

# Gist Logs
https://gist.github.com/5e77ad1866f633a06c387e680685e38a

# Command Output and Reproduction
```
~/workspace$ brew install fontforge --with-extra-tools --with-giflib --with-libspiro --with-libuninameslist
==> Downloading https://github.com/fontforge/fontforge/releases/download/20170731/fontforge-dist-20170731.tar.xz
Already downloaded: /Users/tyler.abair/Library/Caches/Homebrew/fontforge-20170731.tar.xz
==> ./configure --prefix=/usr/local/Cellar/fontforge/20170731_2 --disable-silent-rules --without-x
==> make install
==> make
Last 15 lines from /Users/tyler.abair/Library/Logs/Homebrew/fontforge/03.make:
         ^~~~~~~
findtable.c:5:10: fatal error: 'mem.h' file not found
#include "mem.h"
         ^~~~~~~
1 error generated.
make: *** [findtable.o] Error 1
1 error generated.
make: *** [pcl2ttf.o] Error 1
dewoff.c:7:10: fatal error: 'mem.h' file not found
#include "mem.h"
         ^~~~~~~
1 error generated.
make: *** [dewoff.o] Error 1
1 error generated.
make: *** [showttf.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html

```

**Comment by ilovezfs** [comment]
@tabair-addepar The build failure will go away if you remove the option ` --with-extra-tools`

**Comment by ilovezfs** [comment]
@tabair-addepar I have opened an issue about this here: https://github.com/fontforge/fontforge/issues/3155

CC @jtanx

**Comment by ilovezfs** [comment]
@tabair-addepar this now fixed via https://github.com/Homebrew/homebrew-core/pull/18530 if you `brew update`.

**Comment by tabair-addepar** [comment]
Works great, thank you!
