### ISSUE TITLE
Python IDLE crash on start when using Open With

### ISSUE THREAD

**Issue by James2516** [Homebrew/homebrew-core#18406]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [y] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [y ] Ran `brew update` and retried your prior step?
- [y ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [y ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [y] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

I can run `idle3` from terminal and open a file from it perfectly.

However, if i try to open a .py file directly with it (via "Open with), it crashes immediately with the following log: https://pastebin.com/raw/c2jrNxh9

Python was installed with `brew install python3 --with-tcl-tk` and I have tried reinstalling it and restarting OS with no results. 
Any idea what could be wrong with it?

**Comment by dunn** [comment]
Sorry for the delay getting back to you.

Any way you could check if this happens when IDLE is installed outside of Homebrew?

**Comment by James2516** [comment]
Just checked, works fine with the installation downloaded from python.org.
Using macOS Sierra 10.12.6.

**Comment by dunn** [comment]
Does it look like the same problem as https://github.com/Homebrew/homebrew-core/issues/12068 ?

**Comment by James2516** [comment]
Nope, i think the "Open with" was not done right for the installation.

**Comment by dunn** [comment]
Just to double-check, could you try reinstalling `python3`, without the `--with-tcl-tk` flag?

**Comment by James2516** [comment]
I did, didn't solve the problem.

**Comment by dunn** [comment]
Thanks for trying!  Unfortunately my Python knowledge is pretty limited, so I'm not sure how much more I can help.  Another maintainer will chime in if they have any further ideas.

**Comment by James2516** [comment]
This is still not fixed. Anyone able to replicate it on a Mac?
