### ISSUE TITLE
autobump GitHub Actions worfklow is broken?

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [Homebrew/homebrew-core#184014]
We have a package that is in autobump, we pushed a release and it did not get picked up

Bump GitHub Actions logs show an error
https://github.com/Homebrew/homebrew-core/actions/workflows/autobump.yml
https://github.com/Homebrew/homebrew-core/actions/runs/10778997128/job/29891535761#step:7:30

```
Error: No available formula with the name "rpcgen".
Error: Process completed with exit code 1.
```

**Comment by carlocab** [comment]
Fixed now. Please don't file issues without filling up the issue template.

If you don't want to fill up the template, use the [discussions page](https://github.com/orgs/Homebrew/discussions).

Thanks!
