### ISSUE TITLE
More Xcode 9 fun: msmtp

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#18438]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`msmtp` built on Sierra with Xcode 9 encounters runtime failures whenever I try to send an email.  The nature of the error message suggests that this is more Xcode 9 garbage:
```
dyld: lazy symbol binding failed: Symbol not found: _fmemopen
  Referenced from: /usr/local/bin/msmtp
  Expected in: /usr/lib/libSystem.B.dylib
```
Moreover, if I `xcode-select` myself to use Xcode 8.3.3, the problem vanishes.

**Comment by chdiza** [comment]
For the first time, `xcode-select`ing to point at the CLT associated with Xcode 9 did not make the problem go away.

**Comment by chdiza** [comment]
Crap, forgot the info!  I'm "ready to brew", and:
```
HOMEBREW_VERSION: 1.3.3-6-gc4b6dbf
ORIGIN: https://github.com/Homebrew/brew
HEAD: c4b6dbf6533dcf98e388620bd96081d1a557aa73
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 06f78018d3896bb6ad3444f938b481ad5eb353bb
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/hb
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.3.3 => /usr/local/hb/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
```

**Comment by chdiza** [comment]
I am unqualified to say whether adding yet another `ac_cv_func` tweak to superenv is the right thing to do, so I did not try that locally.

**Comment by ilovezfs** [comment]
Until we had it to superenv, https://github.com/Homebrew/homebrew-core/pull/18439.

**Comment by ilovezfs** [comment]
>Does this mean it will eventually wind up in superenv?

probably yeah
