### ISSUE TITLE
cimg Formula Fails to Install Because of Invalid Hash

### ISSUE THREAD

**Issue by Frizlab** [Homebrew/homebrew-core#18459]
# Problem

The file at http://cimg.eu/files/CImg_2.0.4.zip has SHA-Sum 256 hash of `50cdc91f0434364c55211f3578829514fe7ee30824e45094d15b24c5057766d3` but formula expects `5abe230585e784b85607bbca3e3d61e872309654f8c0dd59b677227d66120a27`. I have no access to the original download, so I cannot compare both versions.

# My Config

I don't think it's that relevant here because the error is straightforward. Anyway, there they are (I know I have an unusual config; this is why not all brew doctors errors are fixed):
```
HOMEBREW_VERSION: 1.3.3-13-g804d688
ORIGIN: https://github.com/Homebrew/brew
HEAD: 804d6880ddf95099c2200827c3c31bf287ae7b53
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 17ccdf1df7d59c3adfe86718aa4cdc354f388c96
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /Users/frizlab/usr/homebrew
HOMEBREW_REPOSITORY: /Users/frizlab/usr/homebrew
HOMEBREW_CELLAR: /Users/frizlab/usr/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
```

```
Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: /usr/bin occurs before /Users/frizlab/usr/homebrew/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  rsync

Consider setting your PATH so that /Users/frizlab/usr/homebrew/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/Users/frizlab/usr/homebrew/bin:$PATH"' >> ~/.bash_profile
```

`brew gist-logs` has no logs for `cimg`.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by acdha** [comment]
Just ran into this as well - the remote archive appears to be valid and has been served with that SHA-256 hash for at least a couple days

**Comment by DomT4** [comment]
Someone's going to need to kick the hash change upstream & ask them to verify what changed to ensure the change isn't malicious.

**Comment by DomT4** [comment]
Might be another case of [this sort of thing](https://github.com/dtschump/CImg/issues/136).

**Comment by ilovezfs** [comment]
Reported https://github.com/dtschump/CImg/issues/155

**Comment by ilovezfs** [comment]
@Frizlab @acdha if you `brew update`, this is fixed.
