### ISSUE TITLE
invalid multibyte char (Windows-31J) (SyntaxError)

### ISSUE THREAD

**Issue by shinsahara** [Homebrew/homebrew-core#18458]
[utils.rb.zip](https://github.com/Homebrew/homebrew-core/files/1326312/utils.rb.zip)

# Please always follow these steps:
- [y] Confirmed this is the problem in homebrew installing.

To help us debug your issue please explain:
- What you were trying to do (and why)
I've tried to install Homebrew for macOS Sierra 10.12.6.
I executed following:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

- What happened (include command output)
I met the following SyntaxError.
`
HEAD is now at 804d688 Merge pull request #3196 from ilovezfs/ac_cv_xcode9-2
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/local/Homebrew/Library/Homebrew/utils.rb:119: invalid multibyte char (Windows-31J) (SyntaxError)
/usr/local/Homebrew/Library/Homebrew/utils.rb:120: syntax error, unexpected keyword_else, expecting ')'
...
Failed during: /usr/local/bin/brew update --force`

- What you expected to happen
Success of installing.

- Step-by-step reproduction instructions (by running `brew install` commands)

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Homebrew

==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions

==> /usr/bin/sudo /usr/sbin/chown sahara /usr/local/Homebrew

==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Homebrew

==> Downloading and installing Homebrew...

and the result is following:

remote: Counting objects: 7192, done.
remote: Compressing objects: 100% (4232/4232), done.
remote: Total 7192 (delta 4343), reused 4757 (delta 2736), pack-reused 0
Receiving objects: 100% (7192/7192), 3.72 MiB | 202.00 KiB/s, done.
Resolving deltas: 100% (4343/4343), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3

 omitted a few lines.

 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
Checking out files: 100% (1063/1063), done.

HEAD is now at 804d688 Merge pull request #3196 from ilovezfs/ac_cv_xcode9-2
`/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': `/usr/local/Homebrew/Library/Homebrew/utils.rb:119: invalid multibyte char (Windows-31J) (SyntaxError)`
/usr/local/Homebrew/Library/Homebrew/utils.rb:120: syntax error, unexpected keyword_else, expecting ')'

/usr/local/Homebrew/Library/Homebrew/utils.rb:122: syntax error, unexpected keyword_end, expecting tSTRING_DEND
/usr/local/Homebrew/Library/Homebrew/utils.rb:129: invalid multibyte char (Windows-31J)
/usr/local/Homebrew/Library/Homebrew/utils.rb:130: syntax error, unexpected keyword_else, expecting ')'
/usr/local/Homebrew/Library/Homebrew/utils.rb:132: syntax error, unexpected keyword_end, expecting tSTRING_DEND
/usr/local/Homebrew/Library/Homebrew/utils.rb:167: module definition in method body

/usr/local/Homebrew/Library/Homebrew/utils.rb:574: syntax error, unexpected end-of-input, expecting tSTRING_DEND

	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:4:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:5:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:17:in `<main>'

Failed during: /usr/local/bin/brew update --force

# Formula additions or changes
I think that the following line should be in the first line of utils.rb

# -*- encoding: UTF-8 -*-

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
>Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

This issue is not related to `brew install`ing a single package so it should be filed to https://github.com/Homebrew/brew/issues/new. Please read the issue template in full. Thanks!
