### ISSUE TITLE
Formulae missing High Sierra bottles

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#18493]
### Remaining

- [x] ddd (https://savannah.gnu.org/bugs/index.php?52175)
- [x] djbdns (depends on `ucspi-tcp`)
- [x] fastbit
- [x] frobtads (https://github.com/realnc/frobtads/pull/2)
- [x] ht (https://github.com/sebastianbiallas/ht/pull/18)
- [x] moe (http://lists.gnu.org/archive/html/bug-moe/2017-09/msg00000.html)
- [x] nazghul
- [x] ntp
- [x] picolisp (https://github.com/Homebrew/homebrew-core/pull/19055)
- [x] rlvm (https://github.com/Homebrew/homebrew-core/pull/18306)
- [x] squirrel (https://github.com/albertodemichelis/squirrel/issues/98)
- [x] supermodel
- [x] supertux (https://github.com/SuperTux/supertux/issues/762)
- [x] tcc
- [x] tpp (#25214)
- [x] ucg (https://github.com/gvansickle/ucg/issues/118)
- [x] ufoai
- [x] voltdb

### Top formulas (> 200 installs a month)

_(sorted by usage)_

- [x] htop (https://github.com/hishamhm/htop/issues/682) (will be fixed once macOS 10.13.4 is out)
- [x] root (https://github.com/Homebrew/homebrew-core/pull/18768)
- [x] gpsbabel (https://github.com/Homebrew/homebrew-core/pull/18739)
- [x] passenger (https://github.com/Homebrew/homebrew-core/pull/19509)
- [x] handbrake (https://github.com/HandBrake/HandBrake/issues/872)
- [x] bullet (https://github.com/Homebrew/homebrew-core/pull/18755)
- [x] elm (https://github.com/Homebrew/homebrew-core/pull/18927)
- [x] gearman (https://github.com/Homebrew/homebrew-core/pull/18841)
- [x] smlnj (#18833)
- [x] imapsync (https://github.com/Homebrew/homebrew-core/pull/18279)
- [x] emscripten (new version 1.37.21 available)
- [x] imagesnap (https://github.com/Homebrew/homebrew-core/pull/18837)
- [x] hh (https://github.com/Homebrew/homebrew-core/pull/18770)
- [x] rswift (https://github.com/Homebrew/homebrew-core/pull/18829)
- [x] gst-python (https://github.com/Homebrew/homebrew-core/pull/19186)
- [x] mapnik
- [x] masscan (https://github.com/robertdavidgraham/masscan/issues/294)
- [x] redis@3.2
- [x] iozone (#18115)
- [x] ucspi-tcp
- [x] daq (https://github.com/Homebrew/homebrew-core/pull/19207)
- [x] tinyproxy (https://github.com/tinyproxy/tinyproxy/issues/111)
- [x] snort (https://github.com/Homebrew/homebrew-core/pull/19207)

### Done, 13 March 2018

- [x] echoprint-codegen (https://github.com/spotify/echoprint-codegen/issues/97)
- [x] exodriver (https://github.com/labjack/exodriver/issues/24)
- [x] exult
- [x] libbladerf (redefinition of `clockid_t`)
- [x] mal4s (https://github.com/secure411dotorg/mal4s/issues/44)
- [x] mimetic (https://sourceforge.net/p/mimetic/bugs/2/)
- [x] mobiledevice
- [x] nethacked
- [x] percona-xtrabackup
- [x] talk-filters

### Other formulas

- [x] aqbanking
- [x] aurora-cli (https://github.com/pantsbuild/pants/issues/4943)
- [x] darkstat (https://github.com/Homebrew/homebrew-core/pull/19168)
- [x] elixirscript (https://github.com/Homebrew/homebrew-core/pull/18977)
- [x] glslang (https://github.com/KhronosGroup/glslang/issues/1083)
- [x] gmic (https://github.com/Homebrew/homebrew-core/pull/19259)
- [x] go@1.5
- [x] go@1.6
- [x] go@1.7
- [x] gom (https://github.com/Homebrew/homebrew-core/pull/20107)
- [x] gstreamermm (https://bugzilla.gnome.org/show_bug.cgi?id=788359)
- [x] hopenpgp-tools (https://github.com/Homebrew/homebrew-core/pull/19120)
- [x] infer (https://github.com/Homebrew/homebrew-core/pull/19646)
- [x] libfaketime
- [x] macosvpn (https://github.com/halo/macosvpn/issues/35)
- [x] mariadb@10.0 (https://github.com/Homebrew/homebrew-core/pull/18556)
- [x] mighttpd2 (https://github.com/Homebrew/homebrew-core/pull/19117)
- [x] mongodb@2.6 (https://github.com/Homebrew/homebrew-core/pull/22097)
- [x] natalie (https://github.com/Homebrew/homebrew-core/pull/19545)
- [x] pdns
- [x] qtads
- [x] raine (https://github.com/zelurker/raine/pull/13)
- [x] rexster-console (https://github.com/Homebrew/homebrew-core/pull/19083)
- [x] root@5
- [x] sfk (new versions available)
- [x] shmux
- [x] sqlite-analyzer
- [x] swfmill (https://github.com/djcsdy/swfmill/pull/42)
- [x] swift
- [x] sword
- [x] tcpurify
- [x] thc-pptp-bruter
- [x] thrift@0.90
- [x] yydecode (https://sourceforge.net/p/yydecode/bugs/5/)

### Done

- amap
- anjuta
- ansible@1.9
- anttweakbar (https://github.com/Homebrew/homebrew-core/pull/18943)
- apache-arrow (https://github.com/Homebrew/homebrew-core/pull/18302)
- baresip (depends on `librem`)
- bastet (https://github.com/fph/bastet/issues/6)
- bdsup2sub (https://github.com/Homebrew/homebrew-core/pull/18716)
- bluepill
- bulk_extractor (https://github.com/Homebrew/homebrew-core/pull/18722)
- c2048
- caf (https://github.com/actor-framework/actor-framework/issues/600)
- charm-tools (https://github.com/Homebrew/homebrew-core/pull/18767)
- cryptol (https://github.com/Homebrew/homebrew-core/pull/18848)
- dc3dd (https://sourceforge.net/p/dc3dd/bugs/17/)
- docker2aci
- dosbox-(https://github.com/joncampbell123/dosbox-x/pull/308)
- dshb (https://github.com/Homebrew/homebrew-core/pull/19006)
- dspdfviewer
- efl
- ejdb
- fceu(https://github.com/Homebrew/homebrew-core/pull/18291)
- fragroute
- git-cola
- git-number (https://github.com/holygeek/git-number/issues/32)
- globus-toolkit
- gnu-apl
- gxml (https://bugzilla.gnome.org/show_bug.cgi?id=788360)
- kpcli
- launch
- libgda ([Debian bug report and patch](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870741))
- liblas (https://github.com/libLAS/libLAS/pull/128)
- libpoker-eval
- librem
- libtensorflow
- libtorrent-rasterbar (https://github.com/arvidn/libtorrent/issues/2130)
- lsyncd (https://github.com/Homebrew/homebrew-core/pull/18809)
- makepp
- mariadb@10.1
- midgard2
- modules
- molecule (https://github.com/Homebrew/homebrew-core/pull/18767)
- mpage
- mupen64plus (https://github.com/mupen64plus/mupen64plus-video-glide64mk2/commit/5ac11270)
- mysql++
- ndpi
- nedit
- netperf
- nordugrid-arc (depends on `globus-toolkit`)
- nylon
- oauth2_proxy
- openms(https://github.com/openMSX/openMSX/issues/1082)
- openttd (depends on `openmsx`)
- ophcrack (sha256 mismatch)
- osc (https://github.com/Homebrew/homebrew-core/pull/18563)
- pmdmini (https://github.com/mistydemeo/pmdmini/pull/1)
- quex
- reop
- rinetd
- robot-framework
- rom-tools
- shibboleth-sp (https://github.com/Homebrew/homebrew-core/pull/18759)
- simutrans
- snap7 (sha256 mismatch; https://sourceforge.net/p/snap7/tickets/12/)
- solarus (https://github.com/solarus-games/solarus/issues/1084)
- swiftgen
- uberftp (depends on `globus-toolkit`)
- ucommon
- udptunnel
- varnish@4
- vgmstream (https://github.com/Homebrew/homebrew-core/pull/18966)
- viewvc
- virtualpg
- voltdb (newer versions available)
- vrpn (https://github.com/vrpn/vrpn/issues/187)
- wiggle
- wirouter_keyrec
- wordnet
- ykclient
- zelda-roth-se (depends on `solarus`)
- zile
- zsd(depends on `solarus`)
- zshdb
- zsxd (depends on `solarus`)

**Comment by zmwangx** [comment]
Ha, didn't realize they removed 2to3. While Python 2.7 is 2.5 years from final death and the even the most entrenched are moving to Python 3, Apple is backing away.

(Feel free to delete this lament.)

**Comment by ilovezfs** [comment]
There is now `2to3-` and `2to3-2.7`

**Comment by zmwangx** [comment]
Oh yeah, I missed those. What the heck is 2to3-...

**Comment by ilovezfs** [comment]
@zmwangx no idea. I could come up with theories but the only one that seems plausible is that someone hit the wrong key on their keyboard.

**Comment by zmwangx** [comment]
They do something funny with 2to3: https://opensource.apple.com/source/python/python-97.50.7/Makefile.auto.html

**Comment by ilovezfs** [comment]
I guess `2to3-` isn't actually new though

**Comment by zmwangx** [comment]
No it's not. At least it's present on 10.12.

**Comment by zmwangx** [comment]
```console
$ ls /usr/bin/2to3*
/usr/bin/2to3  /usr/bin/2to3-  /usr/bin/2to3-2.7  /usr/bin/2to32.6
```

**Comment by ilovezfs** [comment]
Going to mass replace 2to3 to 2to3- until I get around to converting those to patches https://github.com/Homebrew/homebrew-core/pull/18501 so that we can haz bottles.

**Comment by SMillerDev** [comment]
Gearman doesn't seem to compile on high Sierra, as mentioned here: https://github.com/Homebrew/homebrew-php/pull/4447 so that can either be checked or crossed of.

**Comment by scpeters** [comment]
I've tested `bullet` on high sierra, and it builds from source fine. This issue says `help wanted`, but I'm not sure how you build bottles for the new OS release. I haven't seen pull requests; I just see commits from @brewtestbot that are merged by a maintainer. Not sure if there's anything I can do.

**Comment by fxcoudert** [comment]
@scpeters `bullet` fails to build on our CI machines. This is due to `b3GjkPairDetector.cpp` failing to compile with Xcode9's `clang` when `-target-cpu core2` (or `-march=core2`) is passed.

**Comment by ilovezfs** [comment]
@SMillerDev this list represents things that do not have bottles on High Sierra. So none of them built. If the box is checked that means there's no longer an issue, and the formula has a bottle now or the formula has been deleted. So `gearman` being on the list without a check mark already conveys the fact that it doesn't build on 10.13.

**Comment by SMillerDev** [comment]
Right, I thought it was just things that didn't happen to have one yet. My bad.

**Comment by ilovezfs** [comment]
@SMillerDev ah, I see. No worries. Just didn't want you to think we were ignoring you :)

**Comment by lugray** [comment]
I found a hacky way to build libgda on High Sierra for anyone else who comes looking.  It should also provide some insight into how to fix it properly:

1) Apply patch to `/usr/local/opt/glib/bin/glib-mkenums` to deal with latin-1 encoded libgda files:
```diff
410a411,415
>     if curfilename.startswith("gda-") or curfilename.startswith("libgda-"):
>         encoding = "latin-1"
>     else:
>         encoding = "utf-8"
>
412c417
<         curfile = io.open(curfilename, encoding="utf-8")
---
>         curfile = io.open(curfilename, encoding=encoding)
```
2) In shell, make mysql libraries findable when libgda goes looking for them in the wrong places (replace `5.7.10` below with whichever mysql client version you have):

```sh
brew install mysql
cd /usr/local/include/
for f in ../Cellar/mysql-client/5.7.10/include/mysql/*.h; do ln -s "$f"; done
cd mysql
ln -s mysql/psi
for f in mysql/*.h; do ln -s "$f"; done
brew install libgda
```

**Comment by scpeters** [comment]
@fxcoudert thanks for the info about bullet. It compiled fine with `-march=native`, but I was able to reproduce the problem with `-march=core2`. I tinkered with flags and it seems to be fine with `-O1` and lower, but clang just takes forever with `-O2` and higher. I've reported it upstream to bullet https://github.com/bulletphysics/bullet3/issues/1347

**Comment by erwincoumans** [comment]
How are you building Bullet exactly? I'm using cmake or premake usually, and both work out-of-the-box fine with Bullet on High Sierra, but there isn't a flag -march=core2 in neither of those build systems.

**Comment by scpeters** [comment]
@erwincoumans The bullet homebrew formula [uses cmake](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bullet.rb#L48) and the `-march=` compiler flags are [supplied by brew](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/hardware.rb#L11-L14) to ensure support for a wide range of supported CPU architectures. We can continue discussion in https://github.com/bulletphysics/bullet3/issues/1347 unless you have specific questions for the homebrew maintainers.

**Comment by CamJN** [comment]
fix for bdsup2sub https://github.com/Homebrew/homebrew-core/pull/18716 and a fix for passenger is coming but we're trying to squeeze in some other things to the release too.

**Comment by ilovezfs** [comment]
@CamJN is there a passenger patch we can backport in the meantime?

**Comment by CamJN** [comment]
@ilovezfs Not really, it's spread over a few commits and they aren't tested without the intermediary commits. The most important commit is this one: https://github.com/phusion/passenger/commit/416894542e3c689f4d609e6ce7f6c9a298ca3992 but I'm not sure if it can stand alone.

**Comment by CamJN** [comment]
Note today's Passenger releases do not fix the High Sierra issue, they are due to a forced Enterprise release.

**Comment by CamJN** [comment]
Apparently `rake apache2` in the formula becomes `/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/rake apache2` now? Even though `/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/rake` doesn't exist? Can someone explain why you guys broke rake? We need rake to build Passenger.

**Comment by fxcoudert** [comment]
@CamJN please file an issue. On my 10.13 system it is correctly calling `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/rake apache2`, which then fails: 

```
clang -o buildout/apache2/mod_passenger.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -fPIC -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -g -DHAS_ALLOCA_H -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -c src/apache2_module/mod_passenger.c
src/apache2_module/mod_passenger.c:26:10: fatal error: 'httpd.h' file not found
#include <httpd.h>
         ^~~~~~~~~
1 error generated.
rake aborted!
```

**Comment by CamJN** [comment]
I'm referring to a system that uses the new portable-ruby not the system ruby like one would expect. I know that passenger <= 5.1.10 won't compile on High Sierra but I was trying to test on el cap and found that portable-ruby is broken/crippled.

**Comment by fxcoudert** [comment]
@CamJN if this is not on High Sierra, I am unclear why this is here. Please file an issue describing in detail your issue.

**Comment by CamJN** [comment]
It's mentioned here because it has become one more yak to shave.

**Comment by fxcoudert** [comment]
Worry no more, that animal has been depilated. https://github.com/Homebrew/homebrew-core/pull/19376

**Comment by CamJN** [comment]
It won't work, I said so in https://github.com/Homebrew/homebrew-core/issues/18493#issuecomment-336224014, But now I have to fight with the homebrew maintainers to fix their new bugs before I can work on getting the release that will fix High-Sierra out.

**Comment by CamJN** [comment]
and this is how they behave: https://github.com/Homebrew/brew/issues/3310

**Comment by fxcoudert** [comment]
@CamJN I am a Homebrew maintainer, and I did fix the `rake` issue in that commit, less than an hour after you reported it above.

I guess now you can return to _“work on getting the release that will fix High-Sierra out”_, since High Sierra has been released for weeks (and months if we count betas)

**Comment by CamJN** [comment]
Huh, so `system "rake"` is allowed? That's the exact kind of thing that gets my PRs rejected all the time by you guys.

**Comment by fxcoudert** [comment]
> That's the exact kind of thing that gets my PRs rejected all the time by you guys.

??? Not in [this universe](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+author%3AcamJN+is%3Aclosed)

**Comment by CamJN** [comment]
More like in this universe:
https://github.com/Homebrew/legacy-homebrew/pull/49567#issuecomment-189703317
https://github.com/Homebrew/legacy-homebrew/pull/48377#issuecomment-174352599

**Comment by ilovezfs** [comment]
@CamJN Please read, or re-read, our [Code of Conduct](https://github.com/Homebrew/homebrew-core/blob/master/CODE_OF_CONDUCT.md#code-of-conduct) and adjust your future communication accordingly.

**Comment by CamJN** [comment]
I've read it, and I'm sorry I got angry. Homebrew is by far the most infuriating project I've ever interacted with, and because of the official and often enforced policy of not caring about the users I tend to read replies as having an air of condescension and dismissal that may not always be present.

I realize the policy isn't going to change, and that I have to live with it if I want to interact with the project at all, but being treated badly sucks; as you well know given you tell me not to do it to you.

**Comment by JCount** [comment]
@CamJN Please stop being deliberately inflammatory, it is not constructive and helps no one.

The comment
> because of the official and often enforced policy of not caring about the users

is entirely unnecessary, and furthermore is not factually accurate. It may be a personally held belief or opinion, but by including it in what is framed as a conciliatory statement perverts the apologetic tone into one that could be received in a number of quite negative ways.

Please, try to temper your tone and overall manner.

**Comment by SConaway** [comment]
` tinyproxy` seems to build fine now

**Comment by offlinenow** [comment]
For `passenger`, just add dependence `httpd` and `apr` when building with apache2 module

**Comment by xwkuang5** [comment]
Hi! I'm on High Sierra (version 10.13.1) and when I try to install `opencv3` with the `--with-contrib` option, I got the warning from homebrew saying that `Warning: opencv: this formula has no --with-contrib option so it will be ignored!`. I try doing `brew options opencv3` and nothing shows up. Is this because `opencv3` was only released several weeks ago and no updates have been made to homebrew?

Thanks!

**Comment by ilovezfs** [comment]
it's always built with contrib now

**Comment by Mirocow** [comment]
work it
$ brew install --ignore-dependencies htop

**Comment by vinyldarkscratch** [comment]
Just created a PR that fixes `ucspi-tcp`, meaning that there's just one more popular formula to go!  (At least, if #22681 is accepted and merged.  😛)

**Comment by HazCod** [comment]
What about `htop`? (https://github.com/Homebrew/homebrew-core/issues/22622)

**Comment by ilovezfs** [comment]
@HazCod that is not the purpose of this issue.

**Comment by SEAPUNK** [comment]
@ilovezfs Then why close #22622?

**Comment by apjanke** [comment]
Some updates:

* djbdns  - works for me now that ucspi-tcp is fixed. Just pull another bottle?
* echoprint-codegen - works for me under Xcode 9.1 and 9.2
* nethacked - development looks moribund
* squirrel - looks reported and fixed upstream in HEAD: https://github.com/albertodemichelis/squirrel/issues/98. No release since March 2016, though. I commented asking for one.
* supertux - vendors squirrel; same error. Reported: https://github.com/SuperTux/supertux/issues/762

Are we still doing `depends_on MaximumMacOSRequirement`? Might be time to slap that on nethacked; the formula's already kind of a mess of hacks.

**Comment by ilovezfs** [comment]
>Are we still doing depends_on MaximumMacOSRequirement?

Only in cases where it's not feasible to backport a fix, but a fix is nonetheless expected or already merged, and at the same time an `or_later` bottle won't work. For example: valgrind.

**Comment by HesselM** [comment]
Patched ddd with PR #25233

**Comment by fxcoudert** [comment]
Thanks to everyone who helped on this enormous task! We've got them all working… well, except a few we removed :)

**Comment by ilovezfs** [comment]
A special thanks to @fxcoudert for his tireless and skillful work getting everything patched and bottled for High Sierra.
