### ISSUE TITLE
DVTM formula no longer works with 10.11

### ISSUE THREAD

**Issue by gridsystem** [Homebrew/homebrew-core#185]
Explained in more depth [in that repo](https://github.com/martanne/dvtm/issues/19). I'm logging here too as the developer does not actively support OS X.

I've also put a small bounty on the issue. It's not much, less of an incentive and more of a thank you for anyone who can help.

**Comment by mikemcquaid** [comment]
Looks like we should just flag this as depending on OS X <10.11 for now and consider whether it'll be removed/fixed in future.
