### ISSUE TITLE
Fontconfig 2.12.5 dependencies not met during upgrade

### ISSUE THREAD

**Issue by rhwood** [Homebrew/homebrew-core#18525]
Upgrading fontconfig from 2.12.4 to 2.12.5 led to a post install failure to link against libpng.

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade existing packages on my mac, including fontconfig.
- What happened (include command output)
```
==> Upgrading fontconfig 
==> Installing dependencies for fontconfig: freetype
==> Installing fontconfig dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.8.1.sierra.bottl
######################################################################## 100.0%
==> Pouring freetype-2.8.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.8.1: 63 files, 2.6MB
==> Installing fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.12.5.sierra.bo
######################################################################## 100.0%
==> Pouring fontconfig-2.12.5.sierra.bottle.tar.gz
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.12.5/bin/fc-cache -frv
Last 15 lines from /Users/rhwood/Library/Logs/Homebrew/fontconfig/post_install.01.fc-cache:
2017-09-25 05:53:01 -0400

/usr/local/Cellar/fontconfig/2.12.5/bin/fc-cache
-frv

dyld: Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
  Referenced from: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Reason: Incompatible library version: libfreetype.6.dylib requires version 49.0.0 or later, but libpng16.16.dylib provides version 48.0.0
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall fontconfig`
==> Summary
🍺  /usr/local/Cellar/fontconfig/2.12.5: 495 files, 3.2MB
```
- What you expected to happen
Fontconfig to install without error
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew uninstall --ignore-dependencies fontconfig
brew install fontconfig
```

[gist-log output](https://gist.github.com/d7a6abe0ec828e2f832fed9ace56cb94)

**Comment by ilovezfs** [comment]
```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a0dd5196ac84427ad394be4c3c81c5f49c569bc
Core tap last commit: 6 weeks ago
```

```
git -C $(brew --repo homebrew/core) status
```

**Comment by rhwood** [comment]
Thanks for that clue. I had made a PR for a formula a couple of months ago and that branch remained the working copy. No idea why brew would only partly update it though.

Removed branch and everything works now.
