### ISSUE TITLE
rclone: install --HEAD No such file or directory - bash_completion

### ISSUE THREAD

**Issue by vancleve** [Homebrew/homebrew-core#18535]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I tried to install HEAD version of `rclone` with `brew install --HEAD rclone` and got the following error: 

`Error: No such file or directory - bash_completion`

gist-log: <https://gist.github.com/vancleve/643d19868fa36ed54216f1b6c8e70f5b>

**Comment by ilovezfs** [comment]
`HEAD` installs will frequently break and we don't offer support for them. Please open a PR if you'd like to see this fixed. Thanks!
