### ISSUE TITLE
rcs on High Sierra crashes with illegal instruction when calling "rcs diff"

### ISSUE THREAD

**Issue by jj1bdx** [Homebrew/homebrew-core#18566]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step? -> YES
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? -> YES
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? -> YES see https://gist.github.com/anonymous/d2c1c38e16694f47327bdf0bb64561d1
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? -> `brew gist-logs` worked so not applicable

To help us debug your issue please explain:

- What you were trying to do (and why)

    - Running GNU RCS 5.9.4 provided as `brew install rcs`

- What happened (include command output)

```shell
sh-3.2$ brew install rcs
==> Downloading https://homebrew.bintray.com/bottles/rcs-5.9.4.high_sierra.bottl
Already downloaded: /Users/kenji/Library/Caches/Homebrew/rcs-5.9.4.high_sierra.bottle.1.tar.gz
==> Pouring rcs-5.9.4.high_sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/rcs/5.9.4: 27 files, 732.2KB
sh-3.2$ rcs diff
Illegal instruction: 4
```

- What you expected to happen

    - An error message with command usage

- Step-by-step reproduction instructions (by running `brew install` commands)

    * See https://gist.github.com/anonymous/d2c1c38e16694f47327bdf0bb64561d1 for the installation detail output of `brew gist-logs`
    * See above (`brew install rcs` for High Sierra)

**Comment by DomT4** [comment]
Can reproduce this from source as well, FWIW:

```
==> Summary
🍺  /usr/local/Cellar/rcs/5.9.4: 27 files, 732.2KB, built in 1 minute 29 seconds

~> rcs diff
[1]    35009 illegal hardware instruction  rcs diff
```

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`
