### ISSUE TITLE
zbar doesn't include QR support

### ISSUE THREAD

**Issue by mattdeckard** [Homebrew/homebrew-core#18565]
If you use `brew install zbar` the version that gets installed does not include QR support
Using `brew install zbar --HEAD` includes QR support.

**Comment by mattdeckard** [comment]
Correction: the default version of `zbar` includes QR support but its manpage does not list it as a supported symbology.

**Comment by fxcoudert** [comment]
We (Homebrew) do not do anything specific concerning the QR support or the man page. Please report this issue to the zbar project itself.
