### ISSUE TITLE
CMake is missing bottle for yosemite

### ISSUE THREAD

**Issue by andyli** [Homebrew/homebrew-core#18568]
I'm using brew to install dependencies in TravisCI, and I noticed that installing cmake takes a long time to compile since there is no yosemite bottle.

Is yosemite bottle still supported in general?

**Comment by ilovezfs** [comment]
Nope. 10.13, 10.12, 10.11 now

**Comment by andyli** [comment]
I see. I guess it is time to bump our min OSX version support.
Thanks for the quick reply!

**Comment by ilovezfs** [comment]
you're welcome!
