### ISSUE TITLE
libmodplug 0.8.9.0: SHA256 mismatch

### ISSUE THREAD

**Issue by herrbischoff** [Homebrew/homebrew-core#18588]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Please see the log below:

```
==> Upgrading libmodplug
==> Downloading https://downloads.sourceforge.net/modplug-xmms/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz
==> Downloading from https://downloads.sourceforge.net/#!/modplug-xmms/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 457ca5a6c179656d66c01505c0d95fafaead4329b9dbaa0f997d00a3508ad9de
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/mbischoff/Library/Caches/Homebrew/libmodplug-0.8.9.0.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by easyaspi314** [comment]
I got this exact same SHA256 when trying to install `swig`. 

I opened swig-3.0.12.tar.gz in TextEdit and found this: 

```html
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

So I guess we just need to wait for Sourceforge to fix itself.

**Comment by herrbischoff** [comment]
@easyaspi314: Nice find. That should explain it.

> the Sourceforge site is currently in Disaster Recovery mode

SF should really be ditched by any and all projects in favor of self-hosting or GitHub. It really is just a mess nowadays.

**Comment by herrbischoff** [comment]
Closing the issue as it's something on the end of SourceForge which the Homebrew team can do nothing about.

**Comment by straxus** [comment]
According to their Twitter account they believe that they have resolved the issue, and when I follow the link above from a browser (https://downloads.sourceforge.net/modplug-xmms/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz) the full download comes down as expected, however brew still retrieves the static HTML page instead of the gz - this implies to me that this may be a permanent change to SF.net, and there seem to be a nontrivial number of projects still on sf.net - I ran into this issue (with the same hash) when running a brew upgrade:

```
$ brew upgrade
==> Upgrading 2 outdated packages, with result:
fontconfig 2.12.6, freetype 2.8.1
==> Upgrading fontconfig 
==> Installing dependencies for fontconfig: freetype
==> Installing fontconfig dependency: freetype
==> Downloading https://downloads.sourceforge.net/project/freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2
==> Downloading from https://downloads.sourceforge.net/#!/project/freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: e5435f02e02d2b87bb8e4efdcaa14b1f78c9cf3ab1ed80f94b6382fb6acc7d78
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/[...]/Library/Caches/Homebrew/freetype-2.8.1.tar.bz2
To retry an incomplete download, remove the file above.
$ 

```

If this is the new normal, perhaps there will need to be a short-term hack to brew to work around this :(

**Comment by ilovezfs** [comment]
it's a SourceForge bug https://twitter.com/sfnet_ops/status/913097676916367360
