### ISSUE TITLE
Plantuml SHA256 Mismatch

### ISSUE THREAD

**Issue by connorlay** [Homebrew/homebrew-core#18629]
I tried installing [plantuml](http://brewformulas.org/Plantuml) today and encountered this error:
~~~
$ brew install plantuml
==> Downloading https://downloads.sourceforge.net/project/plantuml/1.2017.16/plantuml.1.2017.16.jar
==> Downloading from https://downloads.sourceforge.net/#!/project/plantuml/1.2017.16/plantuml.1.2017.16.jar
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a3d319ed54ed78ce3cf7bfcfe76ffc5aa6ed28a72b5aa575fe9125e0c6bd985c
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/connorlay/Library/Caches/Homebrew/plantuml-1.2017.16.jar
To retry an incomplete download, remove the file above.
~~~

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by connorlay** [comment]
This is probably related to: https://github.com/Homebrew/homebrew-core/issues/18630

**Comment by connorlay** [comment]
See https://github.com/Homebrew/homebrew-core/issues/18630

**Comment by ilovezfs** [comment]
Yup.
