### ISSUE TITLE
Sourceforge.net artifacts failing to download correctly during brew install/upgrade

### ISSUE THREAD

**Issue by straxus** [Homebrew/homebrew-core#18630]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Problem observed with multiple artifacts hosted on sourceforge - see:

https://github.com/Homebrew/brew/issues/3226#issuecomment-332548673
https://github.com/Homebrew/homebrew-core/issues/18588#issuecomment-332571733

I have personally observed this with a `brew upgrade` (fails on fontconfig):

```
$ brew upgrade
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
ndpi

==> Upgrading 2 outdated packages, with result:
fontconfig 2.12.6, freetype 2.8.1
==> Upgrading fontconfig 
==> Installing dependencies for fontconfig: freetype
==> Installing fontconfig dependency: freetype
==> Downloading https://downloads.sourceforge.net/project/freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2
==> Downloading from https://downloads.sourceforge.net/#!/project/freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: e5435f02e02d2b87bb8e4efdcaa14b1f78c9cf3ab1ed80f94b6382fb6acc7d78
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/[...]/Library/Caches/Homebrew/freetype-2.8.1.tar.bz2
To retry an incomplete download, remove the file above.
$
```

And with an attempted install of a new package:

```
$ brew install libav --with-fdk-aac --with-ffplay --with-freetype --with-libass --with-libquvi --with-libvorbis --with-libvpx --with-opus --with-x265
==> Installing dependencies for libav: faac, fdk-aac, freetype, lame, libogg, libvorbis, libvpx, opus, x264, xvid
==> Installing libav dependency: faac
==> Downloading https://downloads.sourceforge.net/project/faac/faac-src/faac-1.29/faac-1.29.7.6.tar.gz
==> Downloading from https://downloads.sourceforge.net/#!/project/faac/faac-src/faac-1.29/faac-1.29.7.6.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 36298549deab66b4b9bb274ecbe74514bb7c83f309265f8f649cf49a44b9bd9f
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/[...]/Library/Caches/Homebrew/faac-1.29.7.6.tar.gz
To retry an incomplete download, remove the file above.
$
```

Note that the hashes are the same for both artifacts - that's because these are static HTML files being returned which use Javascript to redirect to the actual artifact (see https://github.com/Homebrew/homebrew-core/issues/18588 for full details). The specified download URL works from a browser and retrieves the artifact, but only retrieves the static HTML from `brew install/upgrade`

- [X] Ran `brew update` and retried your prior step?

No change

- [X] Ran `brew doctor`, fixed all issues and retried your prior step?

all issues reported were irrelevant to the issue observed (Assorted unexpected headers/dylibs/la/pc files/static libs)

- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

$ brew gist-logs fontconfig
Error: No logs.
$

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I can add this if desired, but it seems irrelevant to this issue - this is not my local config based on the other issues filed around this problem (linked above) in the last 24 hours

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by docwhat** [comment]
It looks like Sourceforge is having issues. From the downloaded Plantuml "jar":

> We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.

**Comment by straxus** [comment]
@docwhat I did see that in the HTML, however I'm not sure how honest it is now - their Twitter account seemed to claim that everything was fine for a while and I was able to download an artifact as expected via the browser (since it's doing a JS redirect to the real artifact location), so this makes me wonder (a) whether this is actually the new normal despite what the <noscript> tag says in that HTML page, and (b) if they are indeed planning to fix it, how long brew users will be dead in the water until they do

**Comment by docwhat** [comment]
According to the News Article, they had it up this morning and it went down again (California Time).

The [sfnet_ops twitter account](https://twitter.com/sfnet_ops) says they still have problems.

In addition, their [support page](sourceforge.net/support/) shows:

> The sourceforge.net website is temporarily in static offline mode.
>
> Only a very limited set of project pages are available until the main website returns to service.

**Comment by straxus** [comment]
Sounds like it boils down to option (b) above then - we basically wait and hope that they fix things in a timely manner, and a (likely nontrivial) number of brew users are dead in the water until then.

This SF.net failure mode seems like something that is likely to recur in the future (if they had this ready-to-go static-redirect-based workaround) - I wonder if it's worthwhile to build in a workaround which does the same thing that their static code does, since SF.net appears to be a common source of brew artifacts? This appears to be the pertinent bit:

```
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
```

It appears to grab the original URL and ship it to a mirror - e.g. this:

https://downloads.sourceforge.net/project/freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2

Becomes:

https://pilotfiber.dl.sourceforge.net/project/freetype/freetype2/2.8.1/freetype-2.8.1.tar.bz2

The upside is that brew would be more resilient in the face of SF.net outages, the downside is that we're building what is basically a hack into the artifact download process.

**Comment by herrbischoff** [comment]
Given this situation, I would welcome if the Homebrew project would cache the source downloads in a way they offer bottles for download. This would strengthen the infrastructure against such outages and resolve the SF situation once and for all.

**Comment by ilovezfs** [comment]
You'll need to use bottles until it's fixed. We're not planning on caching source downloads as we're primarily a binary package manager and the vast majority of our users use bottles.

SourceForge should have this fixed soon. See https://twitter.com/sfnet_ops/status/913097676916367360.
