### ISSUE TITLE
testssl missing files after install

### ISSUE THREAD

**Issue by rajiv** [Homebrew/homebrew-core#18634]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

---

trying to install and run testssl:

```
 ~ $ brew install testssl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, caskroom/versions).
No changes to formulae.

==> Downloading https://github.com/drwetter/testssl.sh/archive/v2.9.5-1.tar.gz
Already downloaded: /Users/rmanglan/Library/Caches/Homebrew/testssl-2.9.5-1.tar.gz
🍺  /Users/rmanglan/homebrew/Cellar/testssl/2.9.5-1: 6 files, 677.9KB, built in 2 seconds
 ~ $ which testssl.sh 
/Users/rmanglan/homebrew/bin/testssl.sh
 ~ $ testssl.sh 184.x.x.x

ATTENTION: No cipher mapping file found!
Please note from 2.9dev on testssl.sh needs files in "$TESTSSL_INSTALL_DIR/etc/" to function correctly.

Type "yes" to ignore this warning and proceed at your own risk --> ^C
```

testssl.sh should run after install. 

looks like certain files are missing or not installed by brew? the previous version of this formula (2.8) did not have these issues.

logs:
https://gist.github.com/rajiv/7aff70c79ba78eb7a4322fa0114eea5b

**Comment by ilovezfs** [comment]
@rajiv this is now fixed if you `brew update` and `brew upgrade`
