### ISSUE TITLE
awscli: should not install aws.cmd 

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/homebrew-core#18640]
When I installed `awscli` via brew, the command `aws.cmd` was also installed to `homebrew/bin/` (which is a windows things)

Can you modify the formula?

**Comment by CaledoniaProject** [comment]
It also installed a few completer script, 

```
aws_bash_completer    aws_completer         aws_zsh_completer
```

**Comment by ilovezfs** [comment]
This is now fixed if `brew update` and `brew reinstall awscli`
