### ISSUE TITLE
Packages with node dependency (e.g. heroku) install node even though it's already installed with nvm

### ISSUE THREAD

**Issue by dorongutman** [Homebrew/homebrew-core#18659]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew gist-logs` returned no results.

`brew config` output:
```
HOMEBREW_VERSION: 1.3.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ac8b58537fe3dd71098a43afcc6a1785dcde1d39
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: de2aa0b451c2628ed8ddb7f176b575e6b18023c9
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/doron/.rvm/rubies/ruby-2.3.1/bin/ruby
Java: 1.8.0_66
macOS: 10.13-x86_64
Xcode: 9.0
CLT: N/A
X11: 2.7.11 => /opt/X11
```

`brew doctor` output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/sentinel-1842166869449.dylib

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
```

To help us debug your issue please explain:
- What you were trying to do (and why) - install heroku cli tool
- What happened (include command output) - homebrew installed node even though I already have node installed using nvm (nvm installed externally from homebrew, like the docs of nvm say)
- What you expected to happen - heroku being installed without installing node, as it's already installed
- Step-by-step reproduction instructions (by running `brew install` commands) - brew install heroku

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
We don't have a `:node` requirement and so the `node` formula is required to build and run `heroku`. `nvm` has no relationship to the situation.

**Comment by OliverJAsh** [comment]
`install yarn --without-node` works but `install heroku --without-node` doesn't. How come?

**Comment by OliverJAsh** [comment]
I created https://github.com/Homebrew/homebrew-core/pull/19230 to fix this.

**Comment by OliverJAsh** [comment]
In hindsight, installing without Node generates issues:

```
❯ heroku
zsh: /usr/local/bin/heroku: bad interpreter: /usr/local/opt/node/bin/node: no such file or directory
```

Not sure why this is.

**Comment by ilovezfs** [comment]
We only support building and running heroku with Homebrew's node.
