### ISSUE TITLE
Conflicting files: jbigkit and netpbm

### ISSUE THREAD

**Issue by s172262** [Homebrew/homebrew-core#18651]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

---
>$ brew install -s netpbm
==> Cloning https://svn.code.sf.net/p/netpbm/code/stable
==> Checking out 3044
==> make
==> make package pkgdir=/private/tmp/netpbm-20170928-36640-nfh763/stage
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/man/man5/pbm.5
Target /usr/local/share/man/man5/pbm.5
is a symlink belonging to jbigkit. You can unlink it:
  brew unlink jbigkit
>
>To force the link and overwrite all conflicting files:
  brew link --overwrite netpbm
>
>To list all files that would be deleted:
  brew link --overwrite --dry-run netpbm
>
>Possible conflicting files are:
/usr/local/share/man/man5/pbm.5 -> /usr/local/Cellar/jbigkit/2.1/share/man/man5/pbm.5
/usr/local/share/man/man5/pgm.5 -> /usr/local/Cellar/jbigkit/2.1/share/man/man5/pgm.5
==> Summary
🍺  /usr/local/Cellar/netpbm/10.73.14: 741 files, 6.5MB, built in 4 minutes 33 seconds

>$ brew link --overwrite --dry-run netpbm
Would remove:
/usr/local/share/man/man5/pbm.5 -> /usr/local/Cellar/jbigkit/2.1/share/man/man5/pbm.5
/usr/local/share/man/man5/pgm.5 -> /usr/local/Cellar/jbigkit/2.1/share/man/man5/pgm.5

**Comment by ilovezfs** [comment]
@s172262 can you please open a PR adding `conflicts_with` for these? Thanks!
