### ISSUE TITLE
can't install root6 on macOS High Sierra[want help]

### ISSUE THREAD

**Issue by xiaoniuniu** [Homebrew/homebrew-core#18661]
After updating to macOS High Sierra, I can't install root successfully.
I have already done the "brew update" and "brew doctor" steps. Hope somebody could give me some help.

Here is my gist-logs for this installation:

[https://gist.github.com/anonymous/dd747b4cd6d691aa6150a07bd9d29f73](url)

I have also attach the files here:
[dd747b4cd6d691aa6150a07bd9d29f73-42dec5664f855250a936628c91232eee839ddcd7.zip](https://github.com/Homebrew/homebrew-core/files/1340291/dd747b4cd6d691aa6150a07bd9d29f73-42dec5664f855250a936628c91232eee839ddcd7.zip)

**Comment by ilovezfs** [comment]
Please report this upstream. Thanks!

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by xiaoniuniu** [comment]
Thank you very much for this.
