### ISSUE TITLE
weechat should depend on Cmake ≥ v2.4, not just the latest Cmake

### ISSUE THREAD

**Issue by nicexe** [Homebrew/homebrew-core#18665]
I have pinned cmake at v3.9.2 and weechat refuses to built without upgrading cmake to the latest version

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from every submitting issues to Homebrew again.**

**Comment by MikeMcQuaid** [comment]
Also, we do not support building against random older versions, sorry.

**Comment by nicexe** [comment]
Latest cmake does not have a bottled version for Yosemite and it cannot be built from source

**Comment by ilovezfs** [comment]
@nicexe I suggest you upgrade to High Sierra then.

**Comment by MikeMcQuaid** [comment]
Yosemite is no longer a supported version of macOS for Homebrew.

**Comment by nicexe** [comment]
@ilovezfs High Sierra isn't available for my machine (MacBook Pro 17 Early 2009)

**Comment by ilovezfs** [comment]
@nicexe then El Capitan.
