### ISSUE TITLE
libconfig requires texinfo to build

### ISSUE THREAD

**Issue by ratijas** [Homebrew/homebrew-core#1866]
# Please follow the general troubleshooting steps first:

- [+] Ran `brew update` and retried your prior step?
- [+] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [-] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

`brew upgrade libconfig` was failing due to "makeinfo: command not found" error.  i was able to fix the build with following commands:
```sh
brew info texinfo
brew link --force texinfo
brew upgrade --env=std libconfig
```
it looks like `texlib` must be specified as a dependency for `libconfig`.  however, for now, the former won't be linked without '`--force`' flag and located without '`--env=std`' flag.

here's failing build log:
https://gist.github.com/ratijas/666e6ca1f85fb3cc3c14e213767ae8aa

**Comment by DomT4** [comment]
It's kind of hard to tell because you've only shared a snippet of the logs rather than whole deal but I'm not sure how `makeinfo` is missing on your system. It exists for me out-of-the-box on a 10.8 VM:

```
which makeinfo
/usr/bin/makeinfo

makeinfo --version
makeinfo (GNU texinfo) 4.8

Copyright (C) 2004 Free Software Foundation, Inc.
There is NO warranty.  You may redistribute this software
under the terms of the GNU General Public License.
For more information about these matters, see the files named COPYING.
```

Can you share your `brew doctor` and `brew config`?

**Comment by ilovezfs** [comment]
Closing for now since texinfo is provided with OS X. Please let us know if you still need help.
