### ISSUE TITLE
MacVim Fails To Build after High Sierra Update

### ISSUE THREAD

**Issue by Prajjwal** [Homebrew/homebrew-core#18663]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
**What you were trying to do (and why)**

Upgrade `macvim`.

- What happened (include command output)

The build repeatedly failed as follows:

```
λ Prajjwals-MacBook-Air ~ → brew reinstall macvim
==> Reinstalling macvim --with-override-system-vim --with-lua --with-python3
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-137.tar.gz
Already downloaded: /Users/prajjwal/Library/Caches/Homebrew/macvim-8.0-137.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tclinterp --enable-terminal --with-tlib=ncurses --
==> make
Last 15 lines from /Users/prajjwal/Library/Logs/Homebrew/macvim/02.make:
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20170928-52975-kuc3ik/macvim-snapshot-137/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20170928-52975-kuc3ik/macvim-snapshot-137/src/MacVim/English.lproj/FindAndReplace.nib

CopyPlistFile build/Release/MacVim.app/Contents/Resources/KeyBinding.plist KeyBinding.plist
    cd /tmp/macvim-20170928-52975-kuc3ik/macvim-snapshot-137/src/MacVim
    builtin-copyPlist --outdir /tmp/macvim-20170928-52975-kuc3ik/macvim-snapshot-137/src/MacVim/build/Release/MacVim.app/Contents/Resources -- KeyBinding.plist

** BUILD FAILED **


The following build commands failed:
	StripNIB English.lproj/Preferences.nib
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

Output of `brew gist-logs macvim` - https://gist.github.com/anonymous/1743303fbb8ac8f0250de10b836fddbf.

**Step-by-step reproduction instructions (by running `brew install` commands)**

- Upgrade to MacOS High Sierra and XCode 9.0.
- Run `brew install macvim`.

**Comment by ilovezfs** [comment]
You need to open Xcode and accept the license etc.

**Comment by knutsvk** [comment]
I have the same problem, but it was not solved by accepting the Xcode license.

**Comment by ilovezfs** [comment]
@knutsvk then it's probably not the same problem. Please open your own issue and fill out the issue template completely.
