### ISSUE TITLE
mpv 0.27.0 not building with --with-libcdio flag

### ISSUE THREAD

**Issue by maki-chan** [Homebrew/homebrew-core#18672]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

gist-log output: https://gist.github.com/5c06e924070f94a99b95334bf137b520

To help us debug your issue please explain:
I tried to install mpv including all possible `--with-*` flags for the most complete mpv possible. So I ran the following:

    brew install mpv --with-bundle --with-jack --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libcdio --with-libdvdnav --with-libdvdread --with-pulseaudio --with-rubberband --with-uchardet --with-vapoursynth --with-x11

I expected it to build successfully. Instead, it told me, the `libcdio_paranoia` library was not found, although `libcdio` was installed as dependency. Omitting the `--with-libcdio` flag works perfectly without any errors.

The same issue without this much information was already mentioned: https://github.com/Homebrew/homebrew-core/issues/17144#issuecomment-331963269

**Comment by ilovezfs** [comment]
@gtm87x the libcdio option was added in https://github.com/Homebrew/homebrew-core/pull/16549. Do you have any idea why this isn't working? The above issue seems to be reproducible.

**Comment by zmwangx** [comment]
Um, did this ever build? The `libcdio_paranoia` code has been there for >4 years [1][2], and `libcdio` never had those headers — they are in a separate repo.[3]

[1] https://github.com/mpv-player/mpv/blame/master/stream/stream_cdda.c#L30-L33
[2] https://github.com/mpv-player/mpv/blame/master/wscript#L385
[3] https://github.com/rocky/libcdio-paranoia

**Comment by ilovezfs** [comment]
@zmwangx I would hope so but :(

**Comment by zmwangx** [comment]
@ilovezfs Any insight from `brew formula-analytics mpv | grep libcdio`?

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics mpv | grep libcdio
 52 | mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-uchardet --with-libcdio --with-x11                      |     4 |   0.04%
 58 | mpv --HEAD --with-bundle --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-libcdio                                                                        |     3 |   0.03%
 63 | mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-rubberband --with-uchardet --with-libcdio               |     3 |   0.03%
 64 | mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-uchardet --with-libcdio                                 |     3 |   0.03%
147 | mpv --HEAD --with-bundle --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-rubberband --with-vapoursynth --with-libcdio                                      |     1 |   0.01%
149 | mpv --HEAD --with-bundle --with-libcaca --with-libdvdnav --with-libdvdread --with-rubberband --with-vapoursynth --with-libcdio                                                       |     1 |   0.01%
155 | mpv --HEAD --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-rubberband --with-vapoursynth --with-libcdio                                                    |     1 |   0.01%
156 | mpv --HEAD --with-libbluray --with-libdvdnav --with-libdvdread --with-rubberband --with-vapoursynth --with-libcdio                                                                   |     1 |   0.01%
160 | mpv --with-bundle --with-jack --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-pulseaudio --with-libcdio --with-x11        |     1 |   0.01%
163 | mpv --with-bundle --with-jack --with-libaacs --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-rubberband --with-libcdio                   |     1 |   0.01%
186 | mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-rubberband --with-uchardet --with-vapoursynth --with-libcdio           |     1 |   0.01%
188 | mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-uchardet --with-libcdio                                                |     1 |   0.01%
262 | mpv --with-libbluray --with-libdvdnav --with-libdvdread --with-rubberband --with-vapoursynth --with-libcdio                                                                          |     1 |   0.01%
```

**Comment by zmwangx** [comment]
The percentage of completionists here is lower than I would have thought.

**Comment by ilovezfs** [comment]
>completionists

Hmmm … is calling someone a completionist a violation of the code of conduct, a compliment, both, or neither?

**Comment by zmwangx** [comment]
Let me reveal a dirty secret: I used to be a completionist, at least for FFmpeg.

**Comment by ilovezfs** [comment]
@zmwangx :scream_cat:

**Comment by fxcoudert** [comment]
Option removed: https://github.com/Homebrew/homebrew-core/commit/8c3af6a9b0a2336bb2f0f26a29dccd1eba43e2ae
