### ISSUE TITLE
solid does not install required headers

### ISSUE THREAD

**Issue by GlenHenshaw** [Homebrew/homebrew-core#18677]
# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] Ran `brew update` and retried your prior step?

    glenhenshaw$ brew update
    Already up-to-date.

- [x ] Ran `brew doctor`, fixed all issues and retried your prior step?

    glenhenshaw$ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
      /usr/local/lib/libgnuplot_i.dylib

- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

    glenhenshaw$ brew gist-logs solid
    Error: No logs.

- [ x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

    glenhenshaw$ brew config
    HOMEBREW_VERSION: 1.3.4-18-gcb139ca
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: cb139ca381cb7f00a4dfdc21482515f103aed417
    Last commit: 34 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 7f4e4ca73af3fbea82d80fd5426d6302e74f6684
    Core tap last commit: 5 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit broadwell
    Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
    Clang: 9.0 build 900
    Git: 2.14.2 => /usr/local/bin/git
    Perl: /usr/bin/perl
    Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
    Java: N/A
    macOS: 10.13-x86_64
    Xcode: 9.0
    CLT: N/A
    X11: 2.7.11 => /opt/X11

To help us debug your issue please explain:
- What you were trying to do (and why)

    - Linking to the SOLID library, so I could use it in a development environment

- What happened (include command output)

    - Libraries MT_Vector3.h, MT_Quaternion.h, MT_Transpose.h, and other MT libraries are not installed in /usr/local/Cellar/solid, or anywhere else. Note that these headers are included in the SOLID source and are expected to be installed in a header include path.

- What you expected to happen

    - I expected the necessary headers to be installed in either /usr/local/include/SOLID

- Step-by-step reproduction instructions (by running `brew install` commands)

    brew install solid

    then attempt to compile, e.g., the example code found on the SOLID github wepage.

**Comment by fxcoudert** [comment]
What example are you referring to exactly? https://github.com/dtecta/solid3

```
$ ls /usr/local/opt/solid/include/SOLID 
SOLID.h       SOLID_broad.h SOLID_types.h
```

**Comment by GlenHenshaw** [comment]
For instance,

https://github.com/dtecta/solid3/blob/master/examples/sample.cpp

and

https://github.com/dtecta/solid3/blob/master/examples/gldemo.cpp

and

https://github.com/dtecta/solid3/blob/master/examples/physics.cpp

**Comment by GlenHenshaw** [comment]
What I expect to see in /usr/local/include/solid is *all* of the headers in the original source package, eg:

https://github.com/dtecta/solid3/tree/master/include

which includes SOLID.h etc but also includes MT_Scalar.h, MT_Vector3.h, MT_Quaternion.h, and so on. Am I missing something here? It looks like these are all prerequisites to use Solid.

**Comment by fxcoudert** [comment]
@GlenHenshaw I don't use SOLID myself, but from their code, `solid3/include/Makefile.am` (https://github.com/dtecta/solid3/blob/master/include/Makefile.am) makes it clear that it's on purpose:

```
# Which header files to install
libsolidinclude_HEADERS = \
	SOLID.h \
	SOLID_broad.h \
	SOLID_types.h

noinst_HEADERS = \
	GEN_MinMax.h \
	GEN_random.h \
```

All headers listed as `noinst` will not be installed. If you think that it is a mistake, I suggest you file a bug report with the SOLID project.
