### ISSUE TITLE
When tab completing with pass(1), compopt: command not found

### ISSUE THREAD

**Issue by jfhbrook** [Homebrew/homebrew-core#18679]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step? (entirely up2d8)
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? (nothing in the output is relevant)
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (formula installs; no logs)
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (formula installs; no logs)

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to tab complete a password path with pass(1)

- What happened (include command output)

Tab complete freaks out:

```sh
pass -c W-bash: compopt: command not found
```

- What you expected to happen

I expected to have that tab-complete to `Work/`

- Step-by-step reproduction instructions (by running `brew install` commands)

As far as I know, you should be able to `brew install pass` and have pass installed, hopefully w/ the same problem I'm having. I checked for any other complete I coulda been sourcing on accident, didn't see one.

The code for loading this in my bash_profile is:

```sh
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I *hope* a bugfix(?) doesn't constitute a change?

Thanks.

**Comment by jfhbrook** [comment]
I'm using sierra (work machine), probably part of the reason--google suggests my bash is older than that feature

**Comment by jfhbrook** [comment]
Related issue: https://github.com/Homebrew/homebrew-core/issues/12160

I've tracked down the line that this shows up in, it's in `bash_completion.d/pass` and looks like

```sh
  # The only time we want to add a space to the end is if there is only
  # one match, and it is not a directory
  if [[ $i -gt 1 || ( $i -eq 1 && -d $firstitem ) ]]; then
    compopt -o nospace
  fi
```

which seems pretty critical. I don't have this error on another machine also running sierra--I'll check its completion.d and see what it does instead or if my other computer's bash (also stock) somehow has compopt.

**Comment by jfhbrook** [comment]
My home computer, which works, has that version of pass's tab complete available. However,

```sh
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
josh@koffing:~/dev/apache/incubator-openwhisk$ which bash
/bin/bash
```

My work machine has bash 4 iirc (need to check this), and iirc may not resolve to /bin/bash 🤔

**Comment by jfhbrook** [comment]
Removing /usr/local/bin/bash makes my bash the correct version, `3.2.57(1)-release`, but the problem still persists

**Comment by jfhbrook** [comment]
Making /usr/local/bin/bash my shell's bashed fixed this. Kinda sidestepping the problem so not closing this, and I have no idea where this version of bash came from, but hey

**Comment by dunn** [comment]
That's probably Hombrew bash, right?

We could add a dependency if the system version of bash is too old.

**Comment by jfhbrook** [comment]
Maybe? I separately brew installed bash, and then brew uninstalled it. Maybe state got weird? But seriously, no idea where it came from.

That really bizarre thing is my other laptop has the same version of bash and, afaik, doesn't have brew bash installed or set in /etc/shells.

From a usability standpoint, I'd suggest that making pass depend on changing your default shell is a usability problem, but I don't have any brighter ideas.

**Comment by fruityten** [comment]
I also had the same issue on my work mac running Sierra.

For now I've changed shell to brews version of bash and all working. Will test on my home machine later.

bash -version
GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin15.6.0)
Copyright (C) 2016 Free Software Foundation, Inc.

**Comment by jfhbrook** [comment]
I accidentally reproduced this on my home laptop, presumably with an errant brew update. Installing brew bash fixed it, so while I don't find that satisfying at all it does seem like a path forward.

**Comment by dminkovsky** [comment]
I got this working by upgrading bash with brew. Then I symlinked `/usr/local/bin/bash` to `/bin/bash`, which was the previous binary. I saved the previous binary as `/bin/bash3` just in case.

**Comment by ilovezfs** [comment]
@dminkovsky that will violate System Integrity Protection so it's not something that should be suggested here.

**Comment by dminkovsky** [comment]
@ilovezfs thanks that a good point!

**Comment by luisra51** [comment]
I solved it with:
~$ `chsh -s /usr/local/bin/bash`

**Comment by arjuhe** [comment]
On OS X 10.11.6 I solved this by changing 

`/usr/local/etc/bash_completion.d/pass` 

to this 

[https://github.com/stuartsierra/password-store/blob/master/src/completion/pass.bash-completion](https://github.com/stuartsierra/password-store/blob/master/src/completion/pass.bash-completion
)

**Comment by Ruberoid** [comment]
Neither of theese helps for brew pass OS X 10.13.3

**Comment by noahdesu** [comment]
same issue here

**Comment by pbx** [comment]
I'm experiencing this as well. 
* macOS 10.13.4 (17E202)
* pass v1.7.1
* `which bash` is `/bin/bash`
* `/usr/local/etc/bash_completion.d/pass -> ../../Cellar/pass/1.7.1_1/etc/bash_completion.d/pass`
