### ISSUE TITLE
termius: depends on bash-completion and refuses to install with bash-completion@2

### ISSUE THREAD

**Issue by achikin** [Homebrew/homebrew-core#18710]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install `termius` formula
- What happened (include command output)
```
→ brew install termius
Updating Homebrew...
==> Installing dependencies for termius: bash-completion, zsh-completions
==> Installing termius dependency: bash-completion
Error: Cannot install bash-completion because conflicting formulae are installed.
  bash-completion@2: because Differing version of same formula

Please `brew unlink bash-completion@2` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```
- What you expected to happen
`termius` formula is installed without errors and did'nt complain about `bash-completion@2`
- Step-by-step reproduction instructions (by running `brew install` commands)
run `brew install termius`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

```
→ brew config
HOMEBREW_VERSION: 1.3.4-24-g22e329f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 22e329fb02329f9d270a1a0b82fb6227dcd91d26
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ba4ea377a01bd762ba2240fd395c62f9ff3c22a9
Core tap last commit: 61 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.0/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 1.8.0_20, 1.7.0_60
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
```
```
→ brew doctor
Your system is ready to brew.
```

**Comment by dunn** [comment]
The formula could instead specify one as `:optional` and the other as `:recommended`, if it's possible to use both.  We'd be happy to review a PR!  Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md and let us know if you have questions.
