### ISSUE TITLE
FFmpeg will depend on xz/liblzma if installed

### ISSUE THREAD

**Issue by mrpippy** [Homebrew/homebrew-core#1873]
If `xz` is installed, FFmpeg will use and link against it, but it's not listed as an optional dependency in the formula.

After installing `ffmpeg` with `xz` installed, I can do the following:
```
$ brew unlink xz
Unlinking /usr/local/Cellar/xz/5.2.2... 53 symlinks removed
$ ffmpeg
dyld: Library not loaded: /usr/local/lib/liblzma.5.dylib
  Referenced from: /usr/local/bin/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Trace/BPT trap: 5
```

From the FFmpeg configure script, `--disable-lzma           disable lzma [autodetect]` is the option to enable/disable it.

**Comment by UniqMartin** [comment]
I believe the best solution would be to just add `xz` to the required dependencies of `ffmpeg`. `xz` should be part of almost any Homebrew installation, thus it makes sense to always link to it. (We can also make it optional and pass `--disable-lzma` by default, but this seems less desirable.)

In any case, can you please [create a pull request](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md) with these changes to the `ffmpeg` formula? I'll be happy to guide you through the rest of the process. Thanks!

**Comment by ilovezfs** [comment]
@UniqMartin You've reminded me of this one: https://github.com/Homebrew/homebrew-core/pull/1211

**Comment by UniqMartin** [comment]
@ilovezfs Nice discussion. Thanks for the reference! I guess making the `xz` dependency optional or always passing `--disable-lzma` (as `ffmpeg` hasn't previously depended on `xz`) is the way to go then.
