### ISSUE TITLE
brew install platypus | incomplete

### ISSUE THREAD

**Issue by uglygus** [Homebrew/homebrew-core#18734]
`platypus` formula does not full install platypus in a runnable form from the command line.

The folder `/usr/local/share/platypus` should be created and populated. Instead the folder is not created at all. Only the executable is installed. Without this folder the `platypus` command will run but it will not build. It will exit with 
`Error: Executable not found at path '/usr/local/share/platypus/ScriptExec'`

`/usr/local/share/platypus` should contain...
`$ls /usr/local/share/platypus
MainMenu.nib         PlatypusDefault.icns ScriptExec`

**Comment by chdiza** [comment]
It works fine for me.  On my machine `/usr/local/share/platypus` is a symlink to ../Cellar/platypus/5.2/share/platypus, as it is supposed to be.

**Comment by uglygus** [comment]
SOLVED. Definitely related to me, not homebrew or platypus. I'm running as an unprivileged user and of course can't write to /usr/local which is owned by root.

**Comment by ilovezfs** [comment]
@uglygus glad to hear you figured it out :)
