### ISSUE TITLE
asdf: Upgrade to 0.4.0 lost all of my plugins and installs

### ISSUE THREAD

**Issue by randycoulman** [Homebrew/homebrew-core#18785]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [n/a] Ran `brew update` and retried your prior step?
- [n/a] Ran `brew doctor`, fixed all issues and retried your prior step?
- [n/a] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I had asdf v0.3.0 installed and had used it to install a number of its language plugins and installations for those languages.

Recently, v0.4.0 came out and I upgraded with `brew upgrade asdf`.

- What happened (include command output)

The upgrade completed successfully, but afterwards, asdf was no longer able to find any of the plugins or language installations that I had previously installed.  I was forced to reinstall everything from scratch again.

- What you expected to happen

I expected that asdf would remember what I had installed before and keep it accessible after upgrading.

- Step-by-step reproduction instructions (by running `brew install` commands)

  - Somehow install asdf 0.3.0; it doesn't appear that this is easy to do with homebrew; after some searching, I couldn't find a good, easy-to-reproduce way to do it.  Several sources suggested `brew install asdf@0.3.0`, but that didn't work for me (`No available formula with the name "asdf@0.3.0"`)
  - `asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git` # Install a plugin
  - `asdf plugin-list` # Note that nodejs is listed
  - `brew upgrade asdf`
  - `asdf --version` # Ensure that you're running 0.4.0
  - `asdf plugin-list` # Notice that there are now no plugins installed

The root cause of the problem is that all of the asdf 0.3.0 plugins and language installs are stored in `/usr/local/Cellar/asdf/0.3.0`, but the symlink from `/usr/local/opt/asdf` now points at `/usr/local/Cellar/asdf/0.4.0`.

I'm not sure of the best fix, but I can think of a couple of options:
- The upgrade process should copy plugins, installs, shims, etc., from the previous directory to the new; or
- The asdf formula should be set up so that installed plugins, languages, and shims are stored in a version-independent location so that they are shared by all installed versions of asdf.

I really love having a Homebrew formula for asdf, because it makes it easier to keep it up to date.  I really hope there's a way to fix this upgrade issue.  When installing and upgrade asdf manually, upgrades happen in place; I'm hoping there's a good way to make that happen using Homebrew as well.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
>The asdf formula should be set up so that installed plugins, languages, and shims are stored in a version-independent location so that they are shared by all installed versions of asdf.

This is what we should do. It will probably require a string replacement since the install method doesn't have a `configure` or anything like that.

**Comment by dunn** [comment]
And if it's not possible to configure this, it should be fixed upstream.  We'd love it if you opened a ticket with the developers!

**Comment by randycoulman** [comment]
I don't believe this is an upstream issue.  To use asdf outside of Homebrew, you clone the repo into whatever directory you want and it manages everything from there.  Upgrades are done by pulling the latest version from GitHub.

Storing things under `/usr/local/Cellar` is handled by this plugin and not by the upstream project, so I don't think there is an upstream issue that needs to be filed.
