### ISSUE TITLE
gcal won't install - disabled because not maintained upstream/not a bug. 

### ISSUE THREAD

**Issue by aspauldingcode** [Homebrew/homebrew-core#188196]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
What do we do about it.

: gcal has been disabled because it is not maintained upstream! It was disabled on 2024-08-03.

kinda sucks because gcal doesn't need to be maintained much for it to work, its like 20 years old or something. cmon!

You broke my sketchybar calendar I made for macOS. How can I install this?

and, Why should I trust homebrew package manager for longevity if you're just going to keep disabling packages when they're no longer maintained.


I want the default behavior to be a warning, not a full-on disablement of the package. 

There are decades old software people enjoy but cannot install with a package manager like brew because of this decision. It should be optional somewhere...
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

read above

### What happened (include all command output)?

read above

### What did you expect to happen?

read above

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
read above - brew install gcal
```

**Comment by SMillerDev** [comment]
> kinda sucks because gcal doesn't need to be maintained much for it to work, its like 20 years old or something. cmon!

But it does need to be maintained for it to be in Homebrew/core.

> and, Why should I trust homebrew package manager for longevity if you're just going to keep disabling packages when they're no longer maintained.

You don't have to, our goal is nog longevity. It's usability.

> I want the default behavior to be a warning, not a full-on disablement of the package. 

It was, for a year. Until it was disabled in https://github.com/Homebrew/homebrew-core/commit/cd1f21a9dccaf3c7c7b7f2e0954d019076977a3f, because it was deprecated for a year.

> There are decades old software people enjoy but cannot install with a package manager like brew because of this decision. It should be optional somewhere...

There is always the option to host it in a tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.

**Comment by Bo98** [comment]
> kinda sucks because gcal doesn't need to be maintained much for it to work, its like 20 years old or something. cmon!
> 
> Why should I trust homebrew package manager for longevity if you're just going to keep disabling packages when they're no longer maintained.

To be clear here: it wasn't just because it wasn't updated. It was not updated _and_ also broken. You can't compile it on macOS 13 or later and we're dropping macOS 12 CI tomorrow.

So it was broken.
