### ISSUE TITLE
Cvs commit illegal instruction

### ISSUE THREAD

**Issue by liyistc** [Homebrew/homebrew-core#18853]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`https://gist.github.com/c22a40e6966fd348ac55abf25b9a3943`
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Run `cvs commit` to commit changes to remote cvs server via :extssh. It always work before upgrading to OS X 10.13. Other commands (such as `cvs up`, `cvs diff`, `cvs checkout`) work.
- What happened (include command output)
```
$ cvs commit
Illegal instruction: 4
```
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew update  
brew upgrade  
brew install cvs  
cvs -d :ext:<SOME_REMOTE_CVS_SERVER> commit
```
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by JCount** [comment]
@liyistc This should now be fixed If you run:
```
brew update
brew upgrade cvs
```

**Comment by javalovercn** [comment]
if above fail, try
```
brew uninstall --force cvs
brew install cvs
```
it works fine for me to fix the problem
