### ISSUE TITLE
failing to upgrade subversion (to 1.9.7_1) on macOS 10.12.6

### ISSUE THREAD

**Issue by swiety** [Homebrew/homebrew-core#18872]
# Please always follow these steps:
- [v] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [v] Ran `brew update` and retried your prior step?
- [v] Ran `brew doctor`, fixed all issues and retried your prior step?
- [v] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Tried running brew upgrade, all packages were upgraded but attempt to upgrade subversion (1.9.7_1) failed.  See 
brew upgrade command output (including stderr): https://gist.github.com/swiety/38bc80800f19154f18ad4f8dd43fee16
and
gist-logs: https://gist.github.com/swiety/3b82e78386d3dba6f06cbb76383d4bd6

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
@swiety I think this will be fixed if you install the CLT (i.e. the Xcode Command Line Tools).

```
xcode-select --install
```

**Comment by swiety** [comment]
@ilovezfs , thanks a lot, 
`xcode-select --install ` 
helped indeed, I was under impression I got it installed already, should've checked before.

I'm guessing this issue can be closed now, unless anybody is planning to add some dependency/warning to ensure xcode-select is installed prior to the upgrade.

**Comment by ilovezfs** [comment]
You're welcome!

(Note `xcode-select` is just a switcher. It's the CLT that you've now installed.)

>unless anybody is planning to add some dependency/warning

Hopefully it doesn't come to that but we'll see.
