### ISSUE TITLE
Security vuln: Invalid code signature on awscli's bundled python

### ISSUE THREAD

**Issue by fromonesrc** [Homebrew/homebrew-core#18870]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

I am monitoring my network connections with [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) and when I run any awscli command that interacts with AWS remotely (like `aws lambda list-functions`) I see a warning about an invalid signature on the version of `python` shipping with the awscli formula:

<img width="1328" alt="" src="https://user-images.githubusercontent.com/550256/31097968-1c7bdd56-a78f-11e7-882c-ee5811e6eba6.png">

Checking the code signature of the `awscli` version of `python` I see this:

```
~ $ codesign -dv --verbose=4 /usr/local/Cellar/awscli/1.11.160/libexec/bin/python
Executable=/usr/local/Cellar/awscli/1.11.160/libexec/bin/python
Identifier=org.python.python
Format=Mach-O universal (i386 x86_64)
CodeDirectory v=20100 size=290 flags=0x0(none) hashes=4+3 location=embedded
Platform identifier=2
Hash type=sha256 size=32
CandidateCDHash sha256=8322c46d11792a8f5d84bf186c4397be5c637b16
Hash choices=sha256
Page size=4096
CDHash=8322c46d11792a8f5d84bf186c4397be5c637b16
Signature size=4105
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=68
```

I don't yet know how this invalidly signed version of `python` made its way into `awscli` but I am opening this issue in case there is a larger security issue at hand here.

**Comment by fromonesrc** [comment]
This does not appear to be limited to `awscli` as I've verified the same behavior in `awslogs`:

![](http://drops.articulate.com/xWiZk0/5ei6Hc1R+)

**Comment by DomT4** [comment]
Pretty sure this is a completely known thing with the way `virtualenv` works. You can reproduce it yourself outside of Homebrew by doing something like:

```
~> mkdir /tmp/venv
~> cd /tmp/venv
~> curl -LvO https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
~> gtar -zxvf virtualenv-15.1.0.tar.gz
== Swap out /usr/bin/env python to /usr/bin/python in virtualenv.py if Homebrew's Python is installed ==
~> PYTHONPATH="/tmp/testing" virtualenv-15.1.0/virtualenv.py /tmp/testing
~> codesign -vvvv bin/python
bin/python: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
```

**Comment by ilovezfs** [comment]
It may be a bug but it's not Homebrew's bug. Thanks for reporting this, though, @fromonesrc

**Comment by gerrymiller** [comment]
Interesting, I actually came across this the same way with Little Snitch.

**Comment by gerrymiller** [comment]
The Little Snitch tech support folks provided the following input:

> Hello Gerry,
> 
> Good to hear you found the culprit! But it’s hard to say why the Info.plist of that executable is invalid. Since python is just a plain executable file, not an app bundle, the Info.plist can’t be a file on disk, but would have to be embedded in the binary itself. I installed awscli and checked using this command:
> 
> `otool -X -s __TEXT __info_plist /usr/local/Cellar/awscli/1.11.170/libexec/bin/python | xxd -r`
> 
> But the thing is: This doesn’t output anything because that executable does not have an embedded Info.plist. This also matches the output of the first command you sent us (codesign --display) shows a line “Info.plist=not bound”, meaning that there is no Info.plist (neither a file, nor an embedded one). If there was an embedded Info.plist, it would show something like “Info.plist entries=15” (like it does for /usr/bin/atos, for example).
> 
> This leaves us with quite a riddle: Verifying the code signature complains about an invalid Info.plist, but there is no Info.plist. I haven’t seen such a case but since I can reproduce it on a fresh install of awscli, I would say that this problem is in the awscli package itself.
> 
> Taking a closer look at the output of codesign --display as in your first message, I realized that the python executable is signed with Apple’s own certificate. This is very strange. It looks like the awscli package contains an executable that was  signed by Apple, shipped with macOS, copied to awscli, but modified in some way to break the signature while still allowing the executable to be run. I’m no expert on licensing, but it seems fishy to me from a licensing standpoint that Amazon/Homebrew redistributes a python executable that contains a code signature by Apple.
> 
> 
> Anyways, there are two things you can do right now:
> 
> First, if you trust this package, you can create a rule in Little Snitch that simply ignores the code signature for connections by “Terminal via python” (this specific python executable). You can create such a rule from the connection alert that probably tipped you off in the first place. You can also create such a rule in Little Snitch Configuration by copying and pasting the following text, then modifying the resulting rule to only allow the servers/protocols/ports you want:
> 
> action: allow
> process: /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal
> via: /usr/local/Cellar/awscli/1.11.150/libexec/bin/python
> code-signature: ignore
> destination: any
> 
> Second, I would suggest you contact the package maintainer for awscli because something is just not right here. They need to fix this. AFAIK the stuff Homebrew installs is never code signed, so the options are to either remove the code signature of the python executable or better yet: Just compile python or take a prebuilt binary and put that in the package. Just don’t take a binary from a macOS installation and ship that.
> Should you choose to do that, you can CC me or forward any questions about details to me directly at [redacted], if you want. This is a really interesting issue. I would like to know what comes out of this.
> 
> Please let me know if there’s anything else I can help you with.

So it looks like potentially the bug may actually be with Homebrew, @ilovezfs?

**Comment by DomT4** [comment]
I'm a huge fan of LS, but I'm not sure they're understanding what `virtualenv` does here. They can reproduce this themselves, outside of everything Homebrew, by doing this:

```
~> mkdir /tmp/venv
~> cd /tmp/venv
~> curl -LvO https://files.pythonhosted.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz
~> tar -zxvf virtualenv-15.1.0.tar.gz
== Swap out /usr/bin/env python to /usr/bin/python in virtualenv-15.1.0/virtualenv.py if a non-system Python is installed ==
~> virtualenv-15.1.0/virtualenv.py .
~> bin/pip install --no-binary :all: --ignore-installed awscli
~> bin/aws configure
== If you don't have valid variables just dump the ones from https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html here ==
~> bin/aws lambda list-functions
```
<img width="557" alt="screen shot 2017-10-19 at 02 27 11" src="https://user-images.githubusercontent.com/6998367/31749993-29c855a0-b475-11e7-86d3-4a76ab984c07.png">

**Comment by ilovezfs** [comment]
@gerrymiller as I already said, this isn't a Homwbrew issue. You'll need to convince Apple, virtual env or LittleSnitch to change something. @DomT4 has virtualenv marked this won't fix?

**Comment by DomT4** [comment]
@ilovezfs I'm not sure anyone has punted it to them, to be honest, but I'm not sure how much they can do. They could theoretically strip all codesigning on MacOS by default using `codesign --remove-signature`, but that's an undocumented flag that could vanish any time Apple wants it to.

**Comment by ilovezfs** [comment]
We could back out all uses of virtualenv, which is likely what we'll end up doing soon anyway.

**Comment by DomT4** [comment]
An alternative is to rely on Homebrew's `python` for applications that touch the internet, which is something that was thrown around a while back. Since Homebrew's `python` is never codesigned at all, you get a more "normal" warning with these situations in LS.

**Comment by ilovezfs** [comment]
Yuck.

**Comment by DomT4** [comment]
Heh. I think we've discovered over the years there's pretty much zero answer here that doesn't involve infringing on Homebrew's principles around system usage as much as possible & yet also doesn't infringe on providing the user as close to ideal as possible UX. Whichever way this goes I think "yuck" is quite likely 🙈.

**Comment by ilovezfs** [comment]
Anyway, I'm not eager to get into the system-Python-sucks conversation yet again.

**Comment by DomT4** [comment]
Aye, appreciated.

**Comment by marcomasser** [comment]
I’m one of the developers of Little Snitch and I’m also the one who worked on @gerrymiller’s question in tech support and who wrote the passage he quoted above. To be honest, I’m absolutely no expert on Homebrew, Python, AWS, or virtualenv so all your input is very much appreciated.

Regarding @ilovezfs’s comment about us maybe changing something in Little Snitch to handle this: I’m afraid there’s not much we can do. The validity of a process’ dynamic code signature is determined in kernel space by the OS itself and it comes to the conclusion that this python process has an invalid code signature. We don’t really have any influence on that and Little Snitch’s kernel extension just uses the info that’s there. Apart from that, we wouldn’t want to pretend the signature to be valid when it’s clearly not, of course.

From what I understand, this does sound like an issue that virtualenv would need to solve. I don’t have any experience with that whatsoever, but if anyone wants to take this issue to them, feel free to reference and/or contact me.

By the way, just as well as you can reproduce this issue without Homebrew, you can reproduce it without Little Snitch by using this command:

```
$ codesign --verify --verbose=4 /usr/local/Cellar/awscli/1.11.170/libexec/bin/python
/usr/local/Cellar/awscli/1.11.170/libexec/bin/python: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
```

@fromonesrc: Please note that the command you used (`codesign -dv …`) does not actually verify the code signature. Unfortunately, when you pass codesign the parameters “-dv”, it only respects the “d” (same as --display) but ignores the “v” (same as --verify). Therefore, the output you posted only *shows information* about the code signature, but does *not actually check* anything.
