### ISSUE TITLE
R package cannot install in R 3.4.2

### ISSUE THREAD

**Issue by tkosaka1976** [Homebrew/homebrew-core#18952]
# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
https://gist.github.com/cf24cef68ed64fcf0f090aa5747a854e
To help us debug your issue please explain:
- What you were trying to do (and why)
I installed R package "flowCore" via biocLite() of Bioconductore installer.
- What happened (include command output)
~~~
installing to /usr/local/lib/R/3.4/site-library/flowCore/libs
** R
** data
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
   共有ライブラリ '/usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so' を読み込めません:
  dlopen(/usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib
  Referenced from: /usr/local/lib/R/3.4/site-library/mvtnorm/libs/mvtnorm.so
  Reason: image not found
ERROR: lazy loading failed for package ‘flowCore’
* removing ‘/usr/local/lib/R/3.4/site-library/flowCore’
~~~

Probably, this came from gfortran library.

**Comment by fxcoudert** [comment]
The latest `gcc` version is 7, which provides a `libgfortran.4.dylib`. If you have upgraded your GCC compiler after having installed previous Fortran libraries (such as `mvtnorm.so`), you will need to rebuild them from source. If `mvtnorm.so` is a prebuilt binary provided by an external source, they will need to provide a version linked against GCC 7.

I am closing this for now, as I do not think it is a Homebrew bug specifically.

**Comment by tkosaka1976** [comment]
I see. Now I understand.
These already installed packages have already compiled by different version of Fortran.
I solved this problem by re-install these packages from source by this command.
`install.packages(pkg, type="source")`

@fxcoudert, Thank you for your help.
