### ISSUE TITLE
R fails to install, citing missing X11 headers

### ISSUE THREAD

**Issue by rolfmblindgren** [Homebrew/homebrew-core#18972]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed all issues and retried your prior step?

Since /usr/local is not _only_ used by brew, that's not really possible, but I've fixed what could be fixed, which was not much

- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/10bab9bef9b56a39d43407440fdebcc6

- [ N/A ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

install r

- What happened (include command output)

```
clang -I../../../../include -DNDEBUG -I../../../include -I../../../../src/include -DHAVE_CONFIG_H -I/usr/local/include -I/usr/local/include -I/usr/X11/include  -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include   -fPIC  -I/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/include/darwin  -c tcltk_unix.c -o tcltk_unix.o
In file included from tcltk.c:668:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found
#       include <X11/Xlib.h>
                ^~~~~~~~~~~~
1 error generated.
make[4]: *** [tcltk.o] Error 1
make[3]: *** [all] Error 1
make[2]: *** [R] Error 1
make[1]: *** [R] Error 1
make: *** [R] Error 1
```

- What you expected to happen

For R to be compiled and installed … 

- Step-by-step reproduction instructions (by running `brew install` commands)

as per instructions,

brew install r --with-openblas --with-java 

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
You have many non-Homebrew files in `/usr/local`, and including Tcl-related ones which appear to be causing the trouble you are seeing:

```
checking for tclConfig.sh... no
checking for tclConfig.sh in library (sub)directories... /usr/local/lib/tclConfig.sh
checking for tkConfig.sh... no
checking for tkConfig.sh in library (sub)directories... /usr/local/lib/tkConfig.sh
```

**Comment by rolfmblindgren** [comment]
Thanks. It works now.
