### ISSUE TITLE
Yap

### ISSUE THREAD

**Issue by ZiggerZZ** [Homebrew/homebrew-core#18999]
Hello,

I have MacOS High Sierra 10.13 and want to install yap - Yet Another Prolog.
> brew install yap
says that there's 'No formulae found' anywhere.
In other qithub-brew-yap questions I saw that people had some problems with the installation but at least brew knew the formulae.

What can I do to install yap?

**Comment by fxcoudert** [comment]
We do no package this software, so you will need to get it from its website (https://www.dcc.fc.up.pt/~vsc/Yap/) and build it from source.
