### ISSUE TITLE
Valgrind fails to compile Sierra 10.12.6

### ISSUE THREAD

**Issue by hasahmed** [Homebrew/homebrew-core#18998]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
       **Trying to install valgrind to inspect c++ memory usage/leaks**
- What happened (include command output)
       **The command failed. Here is the output**
`
Updating Homebrew...
valgrind: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.`
- What you expected to happen
   **Expected valgrind to install and be usable**

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install valgrind`

- brew gist-logs did not work. Here is the output to `brew config`

`HOMEBREW_VERSION: 1.3.4-71-g57035b3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 57035b3ba4b8361c0e764575348607cc18b64ae7
Last commit: 4 hours ago 
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9586b57eb1b2d9bed127d2259e649e16f8f0ae5a
Core tap last commit: 7 months ago 
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900 
Git: 2.8.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/hasankatie/.rvm/rubies/ruby-2.3.1/bin/ruby
Java: 1.8.0_91, 1.7.0_79
macOS: 10.12.6-x86_64
Xcode: 9.0 
CLT: N/A 
X11: 2.7.112 => /opt/X11`

- Here is the output to `brew doctor`

`Your system is ready to brew.`

**Comment by JCount** [comment]
What is the output of:
```
git -C $(brew --repo homebrew/core) status
```

**Comment by fxcoudert** [comment]
The error message given was accurate:

> valgrind: This formula either does not compile or function as expected on macOS versions newer than El Capitan due to an upstream incompatibility.

valgrind does not yet support High Sierra: https://bugs.kde.org/show_bug.cgi?id=383811

**Comment by fxcoudert** [comment]
Closing for now, please add information requested. It appears that your Homebrew repo is at an old version. Try to `brew update`, possibly reinstall.

**Comment by hasahmed** [comment]
here is the output of `git -C $(brew --repo homebrew/core) status`

```
On branch snake
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    Formula/snake.rb

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by fxcoudert** [comment]
@hasahmed you are on a branch, not on homebrew-core's latest version.

Please run: `cd $(brew --repo homebrew/core) && git checkout master`
Then `brew update`. This should fix your problem.

**Comment by hasahmed** [comment]
@fxcoudert It did indeed. Thank you.

**Comment by alejoamiras** [comment]
Are we too far from having it on macOS high sierra ? This sucks 😢.

**Comment by hasahmed** [comment]
Any updates on having valgrind on High Sierra?

**Comment by ilovezfs** [comment]
Feel free to test `brew install --HEAD valgrind` and let us know how it goes.

**Comment by hasahmed** [comment]
Yeah I tried it. No luck

**Comment by ilovezfs** [comment]
Then you'll want to let upstream know about that. There's nothing we can do.

**Comment by alebcay** [comment]
Valgrind head builds for me on High Sierra now. See build output [here](https://pastebin.com/UQ6uLrEp) and environment details are below.

```
~
• brew --env
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/bin:/bin:/usr/sbin:/sbin
```
</p></details>

**Comment by AlexanderYogurt** [comment]
Valgrind head also builds for me on High Sierra. Thank you!

**Comment by hasahmed** [comment]
still no luck for me. it won't even clone.

**Comment by hasahmed** [comment]
Scratch that. All good with --HEAD

**Comment by rodrigorandel** [comment]
I am not able to build it using --HEAD on macOS 10.13.4 and Clang 9.1 build 902. It fails on the _make_. Here is the log file. 
[03.make.log](https://github.com/Homebrew/homebrew-core/files/1896748/03.make.log)

**Comment by GasimGasimzada** [comment]
I know this is not a Homebrew solution but if you go to include/vki/vki_darwin.h and add the following:

https://gist.github.com/renesugar/cf87a9107ad73b40b8487c7c226f5084

`make` will work. I manually installed it using http://www.valgrind.org/docs/manual/dist.readme.html

**Comment by rodrigorandel** [comment]
Great! Thank you @GasimGasimzada, it worked!

**Comment by xiaohk** [comment]
I can build valgrind with HEAD, but it gives this error:

    valgrind: tool 'memcheck' not installed (/usr/local/lib/valgrind/memcheck-amd64-darwin) (No such file or directory)

Anyone having the same issue?
