### ISSUE TITLE
python3: Upgrading to 3.6.3 breaks MacVim

### ISSUE THREAD

**Issue by alecshaw** [Homebrew/homebrew-core#19001]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade `python3` and then open MacVim.
- What happened (include command output)
MacVim launched with `mvim` produces the following:
```
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fffacc99340 (most recent call first):
Vim: Caught deadly signal ABRT
Vim: Finished.
```
When launching MacVim from the Applications folder, no window is drawn. Attempting to open a new window creates no window.
- What you expected to happen
I expected to upgrade `python3` and then work in MacVim.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install python3`
`mvim`
- `brew gist-logs python3` output: https://gist.github.com/alecshaw/cec6438c311271b464042ce9887b1cac

I was able to install the development version of `python3` with `brew upgrade python3 --devel` and then MacVim worked as expected. 

There is also an open issue at https://github.com/macvim-dev/macvim/issues/554 where another user is experiencing the same issue, although it isn't clear if this is related to upgrading `python3`.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
I cannot reproduce this issue. Please try

```
brew reinstall macvim
```

**Comment by alecshaw** [comment]
I tested this yesterday, and neither installing the Homebrew version or reinstalling the cask solved the issue.

However, when installing either today, everything is fine with both versions (8.0.137_2/8.0.138). There has been a version bump to 138 (https://github.com/macvim-dev/macvim/commit/06f8b8e6670490d6df2a1916bcda26cadad1cbe5).
