### ISSUE TITLE
Upgrade to Python 3.6.2  output error, pip3 no longer works

### ISSUE THREAD

**Issue by diek** [Homebrew/homebrew-core#19047]
- [**yes** ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [**yes** ] Ran `brew update` and retried your prior step?
- [**No issues reported** ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [**yes**] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
=> https://gist.github.com/anonymous/11289136eb6c5e0e12bc0bf0bc24f60b
- [**gist-logs worked, but I am including the output of config** ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
**config output**
HOMEBREW_VERSION: 1.3.4-75-g1d82197
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d821975465f7426dab12395aa553cfc5e26fcea
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 716d5336655edc92f41911a8b12e65910b99e2ca
Core tap last commit: 39 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2/bin/ruby
Java: 9
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade Python 3
**- What happened (include command output)**
**First** 
`brew upgrade python3`
**Output**
error: could not delete '/usr/local/lib/python3.6/site-packages/pip/__init__.py': Permission denied
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python3`
**Second**
`brew postinstall python3`
**Output**
running install
running build
running build_py
running install_lib
copying build/lib/pip/__init__.py -> /usr/local/lib/python3.6/site-packages/pip
error: could not delete '/usr/local/lib/python3.6/site-packages/pip/__init__.py': Permission denied

**Running pip3 results in:**
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip import main
ImportError: cannot import name 'main'
**- What you expected to happen**
A clean install, and pip3 to work
**- Step-by-step reproduction instructions (by running `brew install` commands)**
`brew upgrade python3`
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by JCount** [comment]
@diek What is the output of:
`ls -ld /usr/local/lib/python3.6/site-packages/pip`
and 
`ls -ld /usr/local/lib/python3.6/site-packages/pip/__init__.py` ?

**Comment by diek** [comment]
Thanks @JCount, here it is:
**output 1**
drwxr-xr-x  23 root  staff  782  5 Oct 11:57 /usr/local/lib/python3.6/site-packages/pip
**output 2**
-rw-r--r--  1 root  staff  0  5 Oct 11:57 /usr/local/lib/python3.6/site-packages/pip/__init__.py

**Comment by diek** [comment]
I updated the permissions, and reinstalled python3, it is resolved. 
Not sure why it happened, in the first place. thanks @JCount  for getting me back on track

**Comment by JCount** [comment]
@diek Glad I could help! 😄
