### ISSUE TITLE
Apache fails after auto update (just wanted to install php 7.1)

### ISSUE THREAD

**Issue by Samnan** [Homebrew/homebrew-core#19043]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  https://gist.github.com/abdc8870baa3841d356c7ad712128a7c
- [] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   Already had php 5.3 and 7.0 installed with apache 2.4 and working, so I tried to Install php 7.1 version
- What happened (include command output)
   Ran the command:
   brew install php71 --with-httpd24
   It started with updating homebrew.. downloaded newer version of apache and installed
    php 7.1 installation completed without errors
   Apache fails to run afterwards
    Checked and found that the auto update created another httpd config folder, previously it was /usr/local/etc/apache2/2.4/, now there is another one called /usr/local/etc/httpd
   Due to above, all my configuration is lost, apache still does not run
   tried to remove httpd folder from etc and make a link to the original 2.4 folder, still apache does not run, complains about invalid configuration of MPM module
- What you expected to happen
   Should have been able to browse localhost as usual (simple html index file)
- Step-by-step reproduction instructions (by running `brew install` commands)
   brew install php71 --with-httpd24

**Please please please can the auto update of brew on every package install be disabled by default also. Many people have asked for this, it's a complete nuisance to do this one every package install. Now I am stuck for a couple of hours on fixing apache just because brew auto updated. Still looking to fix it**

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by kabel** [comment]
As you noted, the new httpd package has new configuration locations that are not entirely compatible with the community supported version it replaced. The core team decided not to retain compatibility. 

Your new configuration will need to be updated to make use of the new httpd server root `/usr/local/opt/httpd` and module location at `lib/httpd/modules`. You'll also need to add the new MPM configuration to determine which mpm you'd like to use by default (likely prefork if you're wanting to use the php apache module): `LoadModule mpm_prefork_module lib/httpd/modules/mod_mpm_prefork.so`.

**Comment by Samnan** [comment]
Ok understood. What about the brew default auto update set to on. At least
when installing brew for the first time there could a question asked from
user whether they want auto updates or want to do it manually. That should
avoid the frustration when something screws itself up all by itself.


-----------------------------
Samnan ur Rehman
Consultant / Senior Software Developer
about.me/samnan

**Comment by kabel** [comment]
Sorry, I can't speak as to what the core homebrew maintainers think about freezing auto updates. I imagine the reasoning behind forcing it is to reduce the support necessary for users that forget to update and run into issues that are no longer valid on the latest versions. In this case, the screw up was a known, acknowledged backwards compatibility break when the community supported formula `httpd24` was imported into the homebrew core as `httpd`.

**Comment by JCount** [comment]
@Samnan When you say `auto update of brew on every package install be disabled by default`, what behavior are you referencing precisely?

**Comment by Samnan** [comment]
Now I am speechless :P


-----------------------------
Samnan ur Rehman
Consultant / Senior Software Developer
about.me/samnan

**Comment by ilovezfs** [comment]
Migrations are handled by update. But upgrades are not. As we're deprecating all the Homebrew organization  taps except homebrew/core, this isn't a behavior you need to worry about for much longer.

In general autoupdate does not autoupgrade. So only the formula definitions get updated, but you still have to manually `brew upgrade`.
