### ISSUE TITLE
brew install links is installing a broken version on macOS 10.13

### ISSUE THREAD

**Issue by ldepandis** [Homebrew/homebrew-core#19058]
Hi,
I installed the links bottle, but the binary seems to be linked against a newer version of one of its own dependency than the one packaged with it, and therefore it crashes at launch time.

`
==> Downloading https://homebrew.bintray.com/bottles/links-2.14.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/82/82e39d92b7653ba187d2de6b5a9c760319e8ba8d4c9898a12f96dc6f7ae5f256?__gda__=exp=1507191180~hmac=a29df75e0ceca16d80f12ab1fe505b8ce1b1d2d8572379d25
######################################################################## 100,0%
==> Pouring links-2.14.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/links/2.14: 19 files, 1.5MB
                                                                                                                                                                                                 
$ links
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /usr/local/bin/links
  Reason: Incompatible library version: links requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
[1]    9471 abort      links

$ otool -L $(which links)                                                                                                                                                                      
/usr/local/bin/links:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	/usr/local/opt/xz/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.3.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
`
As a workaround, I built it from source code and it is working properly.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by ldepandis** [comment]
Thank you!

**Comment by ilovezfs** [comment]
@ldepandis you're welcome :)
