### ISSUE TITLE
universal-ctags: errors while upgrading

### ISSUE THREAD

**Issue by bxsx** [Homebrew/homebrew-core#190818]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

https://gist.github.com/bxsx/f0ecd6faf156bad62d77179eabdddc22

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

`brew upgrade`

### What happened (include all command output)?

It's already in the generated gist (should this field be optional?).

### What did you expect to happen?

Enjoying a new version of `universal-ctags`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
```
```

**Comment by carlocab** [comment]
Why are you building `universal-ctags` from source?

**Comment by carlocab** [comment]
But the formula has bottles, so you shouldn't need to:

https://github.com/Homebrew/homebrew-core/blob/59438884732fc99e4e5c3eb9cb119e24ba221264/Formula/u/universal-ctags.rb#L15-L22

**Comment by bxsx** [comment]
I don't think these bottles have ever been downloaded (in my case). I always see a rebuild of `universal-ctags`, and I just ran `brew install`, and then `brew upgrade`...

The build source config may come from the old tap `univeral-ctags`. I think like a year ago this formula was moved over to `homebrew-core`..


```
$ brew info universal-ctags
==> universal-ctags: stable p6.1.20240915.0 (bottled), HEAD
Maintained ctags implementation
https://github.com/universal-ctags/ctags
Conflicts with:
  ctags (because this formula installs the same executable as the ctags formula)
Installed
/opt/homebrew/Cellar/universal-ctags/HEAD-5039ab9 (46 files, 3.8MB) *
  Built from source on 2024-09-10 at 13:09:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/u/universal-ctags.rb
License: GPL-2.0-only
==> Dependencies
Build: autoconf ✔, automake ✔, docutils ✔, pkg-config ✔, python@3.12 ✔
Required: jansson ✔, libyaml ✔, pcre2 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 3,561 (30 days), 9,930 (90 days), 39,215 (365 days)
install-on-request: 2,943 (30 days), 8,090 (90 days), 31,220 (365 days)
build-error: 25 (30 days)
```

```
$ brew tap
bxsx/pyenv-virtualenv-migrate
datawire/blackbird
fluxcd/tap
garden-io/garden
git-chglog/git-chglog
homebrew/core
homeport/tap
kreuzwerker/taps
txn2/tap
```

**Comment by bxsx** [comment]
Uninstalling and reinstalling `universal-ctags` has fixed this issue. Now, it's using a bottled version.
I guess, the issue was with the change of the tap mentioned above.
