### ISSUE TITLE
ffmpeg failed to build on 10.11.6 due to missing libopenjpeg

### ISSUE THREAD

**Issue by kieranjol** [Homebrew/homebrew-core#19094]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ YES] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ YES] Ran `brew update` and retried your prior step?
- [Almost ] Ran `brew doctor`, fixed all issues and retried your prior step?
I fixed as much as I could, but was nervous about the python one. Here's the current output:

```
$brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
```

- [YES ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/a41cb2eefa7df0cc5a1d8add52f17680

- [N/A ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to upgrade `ffmpeg` from `3.3.3` to `3.3.4`.

- What happened (include command output)

This failed as `libopenjpeg` was not found. 

```
brew upgrade ffmpeg
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Upgrading 1 outdated package, with result:
ffmpeg 3.3.4
==> Upgrading ffmpeg --with-libass --with-tesseract --with-openjpeg --with-sdl2 --with-freetype
==> Downloading https://ffmpeg.org/releases/ffmpeg-3.3.4.tar.bz2
Already downloaded: /Users/admin/Library/Caches/Homebrew/ffmpeg-3.3.4.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/dfe0fd6/ffmpeg/openjpeg-2.2.patch
Already downloaded: /Users/admin/Library/Caches/Homebrew/ffmpeg--patch-77fbc0f61f2e5742f33116e0da3d246882717affeee2f25112a8a8a69dc17815.patch
==> Patching
==> Applying openjpeg-2.2.patch
patching file configure
patching file libavcodec/libopenjpegdec.c
patching file libavcodec/libopenjpegenc.c
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/3.3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-ffplay --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libtessera
Last 15 lines from /Users/admin/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-opencl
--enable-videotoolbox
--disable-lzma
--enable-libopenjpeg
--disable-decoder=jpeg2000
--extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3
--enable-vda

ERROR: libopenjpeg not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Use a multilib build of x265 so you can have both 8 and 10 bit https://github.com/Homebrew/homebrew-core/pull/18791
OpenCV option to build --with-java was removed https://github.com/Homebrew/homebrew-core/issues/17106
mpv 0.27.0 not building with --with-libcdio flag https://github.com/Homebrew/homebrew-core/issues/18672
```
- What you expected to happen

I expected ffmpeg to build correctly. Seeing as libopenjpeg 2.3.0 is installed via homebrew, I would have expected everything to run OK.

```
brew install openjpeg
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (caskroom/cask, caskroom/versions, homebrew/core).
No changes to formulae.

Warning: openjpeg 2.3.0 is already installed
```

I also see in the ffmpeg configure line:
`--extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3` 

and here is the output of that directory:
```
ls /usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3
openjpeg.h	opj_config.h	opj_stdint.h
```

- Step-by-step reproduction instructions (by running `brew install` commands)

I just ran `brew upgrade ffmpeg`

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew reinstall ffmpeg`

**Comment by kieranjol** [comment]
Ye are wonderful! I ended up running `brew upgrade ffmpeg` out of habit but all was well. Should I reinstall just to be safe?

**Comment by ilovezfs** [comment]
@kieranjol Thanks for the kinds words. They're really appreciated :)

Yes you should use `reinstall`. Since I didn't revision bump it, `brew upgrade` will have no effect.

**Comment by ilovezfs** [comment]
@kieranjol But I guess if the install simply failed and you haven't worked around it already, `brew upgrade` will work too.

**Comment by kieranjol** [comment]
It seemed to work fine, but I did a reinstall jut to be safe. Thanks again!
