### ISSUE TITLE
Missing headers for libffi

### ISSUE THREAD

**Issue by samvv** [Homebrew/homebrew-core#191]
Using `libffi: stable 3.0.13 (bottled), HEAD [keg-only]`, there is no `include/`-directory bottled with **libffi**. It would be nice if a `--with-sources`-option would include the source files.

**Comment by DomT4** [comment]
Don't ask me why upstream install like this, but there are headers in:
```
/usr/local/Cellar/libffi/3.0.13/lib/libffi-3.0.13/include
```

**Comment by tdsmith** [comment]
Its configure script doesn't respect --includedir, either. Please use the pkg-config file to determine the right include paths, like:

`PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig pkg-config libffi --cflags`

You can extract the source tarball to a folder in the current directory with `brew unpack libffi`.

Let us know if we can help with anything.
