### ISSUE TITLE
Your own issue instructions for filing an issue contains a 404

### ISSUE THREAD

**Issue by tommyjcarpenter** [Homebrew/homebrew-core#19105]
# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/caskroom/homebrew-cask/new. If 

THE ABOVE LINK IS A 404
https://github.com/Homebrew/caskroom/homebrew-cask/new does not exist.

**Comment by ilovezfs** [comment]
Fixed!
