### ISSUE TITLE
Graphviz install --with-bindings fails. Can't find Python.h

### ISSUE THREAD

**Issue by coordt** [Homebrew/homebrew-core#19110]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/anonymous/b76189381c9df7dcd1622ad69359d4ac
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   **Install graphviz with Python bindings**

- What happened (include command output)

```
gv_python.cpp:173:11: fatal error: 'Python.h' file not found
# include <Python.h>
          ^~~~~~~~~~
1 error generated.
make[4]: *** [libgv_python_la-gv_python.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```
- What you expected to happen
    **Graphviz to install with python bindings**

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install graphviz --with-bindings --with-freetype --with-librsvg --with-pango`

This is baffling to me because the output of the `configure` command contains:

```
checking for python... python
checking Python.h usability... yes
checking Python.h presence... yes
checking for Python.h... yes
```

I wonder if it has to do with the `CMAKE_INCLUDE_PATH` which in the report says:

```
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by s172262** [comment]
Is there `Python.h` in `/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/` ?

It seems that `graphviz` attempted using Homebrew's `python` instead of system's one.
If `PATH` contains "/usr/local/opt/python/libexec/bin", `graphviz` would use  Homebrew's `python`.

22285-22286 lines in Configure:
```
PYTHON_PREFIX=`$PYTHON -c "import sys; print sys.prefix"`
PYTHON_INCLUDES=-I$PYTHON_PREFIX/include/python$PYTHON_VERSION_SHORT
```

I think that adding the following line in install block makes to force use  system's Python.
```
ENV["PYTHON"]=/usr/bin/python
```

**Comment by coordt** [comment]
Yes, there is a `Python.h` there:

```
coordt ~  $ ls /usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h
/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h
```

**Comment by fxcoudert** [comment]
I can't even reproduce your Python error here, because I get an earlier error with:

```
gv_php.cpp:754:3: error: These bindings need PHP5 - to generate PHP7 bindings use: swig -php7
# error These bindings need PHP5 - to generate PHP7 bindings use: swig -php7
  ^
```

**Comment by s172262** [comment]
@fxcoudert
Php's error has removed  in https://github.com/Homebrew/homebrew-core/pull/19128 .
Please review it.

**Comment by Sky10086** [comment]
I have the same problem,when I run the brew intsall vim --with-lua ,it get a error and say "Can't find Python.h"
then I use 
brew upgrade python
then edit the ~/.zshrc make the system to find the python version that I just update
after that ,I rerun the brew intsall vim --with-lua ,it is done

**Comment by TorvaldsDB** [comment]
@Sky10086 please tell the detail. I need your help.

**Comment by jkulesza** [comment]
@TorvaldsDB I had the same problem with just `brew install vim`.  What do you see when you do `which python`?  If `which python` doesn't give `/usr/bin/python`, you may need to edit your path to use the system.  For example, I had Anaconda Python installed and that was causing a problem.

**Comment by Sky10086** [comment]
@TorvaldsDB
You can use 
brew list Python 
Then you can see the path which brew install the python in it.
After that you should add the path to you  zshrc  use export 
By the way.the zshrc is read from the last line to the first line. So you should add your path after the last line.
Ps:i guess you want to install the auto-complete tools in your vim. If this,I recommend you to install you-complete-me , is faster.

**Comment by pixelhandler** [comment]
@jkulesza, Sky10086 - same for me, I ran into this issue with `brew intsall vim --with-lua`

Thanks everyone for the workarounds :)

This worked for me:

    brew upgrade python
    brew install vim --with-lua
