### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by shilshar** [Homebrew/homebrew-core#19119]
I installed mysql using brew. That installed 5.7 successfully. I started it (using launchctl), everything works. I then uninstalled mysql using brew and then installed using brew mysql@5.6. I did force link to create the symlinks. Now on mysql.server start, it errors. I then noticed that /usr/local/var/mysql still has older files, so I removed this directory. Then uninstalled and installed mysql@5.6 again. Now it starts without any issues. So, should cleanup of the /usr/local/var/mysql be part of the uninstall?

**Comment by ilovezfs** [comment]
Nope, we don't touch things in /usr/local/etc or /usr/local/var on uninstall.

In the future, please fill out the issue template completely even if you think it's irrelevant.
