### ISSUE TITLE
Error: The bottle for wakeonlan has an invalid build provenance attestation.

### ISSUE THREAD

**Issue by 101Dude** [Homebrew/homebrew-core#191180]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
22:58:04.990 iMac191 ~ 2.2s 
➜ brew config && brew doctor
HOMEBREW_VERSION: 4.3.21-18-g1f306b4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f306b4d150cf1c72791786d6180a6ab83aea03d
Last commit: 5 days ago
Core tap HEAD: 657ae4c4701a0f2fd6a4fa5a881530994102181a
Core tap last commit: 5 days ago
Core tap JSON: 15 Sep 05:28 UTC
Core cask tap HEAD: 3ce2f0bc4313e1234175bb9e194cac929d47d403
Core cask tap last commit: 5 days ago
Core cask tap JSON: 15 Sep 05:28 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--greedy", "--require-sha", "--no-quarantine", "--appdir=/Applications", "--fontdir=/Library/Fonts", "--qlplugindir=/Library/QuickLook", "--internet_plugindir=/Library/Internet Plug-Ins", "--prefpanedir=/Library/PreferencePanes/", "--servicedir=/Library/Services"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UFphrnHJjt/org.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.46.0 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0-x86_64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0
Your system is ready to brew.
```
```
23:08:18.257 iMac191 ~ 12.6s 
➜ which -a perl
/usr/local/bin/perl
/usr/bin/perl

23:09:30.628 iMac191 ~ 
➜ /usr/local/bin/perl -v

This is perl 5, version 38, subversion 2 (v5.38.2) built for darwin-thread-multi-2level

23:09:24.638 iMac191 ~ 
➜ /usr/bin/perl -v

This is perl 5, version 34, subversion 1 (v5.34.1) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

23:09:50.375 iMac191 ~ 
➜ perl -v

This is perl 5, version 34, subversion 1 (v5.34.1) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)
```

```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

run `wakeonlan`

### What happened (include all command output)?

```
22:49:00.597 iMac191 ~ 3.8s 
➜ wakeonlan -i 192.168.10.233                      
zsh: /usr/local/bin/wakeonlan: bad interpreter: /usr/bin/perl5.30: no such file or directory
```

I then reinstalled perl
```
22:55:33.642 iMac191 ~ 
➜ brew reinstall perl  
==> Downloading https://ghcr.io/v2/homebrew/core/perl/manifests/5.38.2_1
######################################################################################################## 100.0%
==> Fetching dependencies for perl: berkeley-db@5
==> Downloading https://ghcr.io/v2/homebrew/core/berkeley-db/5/manifests/5.3.28_1
######################################################################################################## 100.0%
==> Fetching berkeley-db@5
==> Downloading https://ghcr.io/v2/homebrew/core/berkeley-db/5/blobs/sha256:db128eb3926e9941b0db4aaf52df8848c74
######################################################################################################## 100.0%
==> Fetching perl
==> Downloading https://ghcr.io/v2/homebrew/core/perl/blobs/sha256:4da05eef811a965977571311b16877bfd281c01494e3
######################################################################################################## 100.0%
==> Reinstalling perl 
==> Installing dependencies for perl: berkeley-db@5
==> Installing perl dependency: berkeley-db@5
==> Downloading https://ghcr.io/v2/homebrew/core/berkeley-db/5/manifests/5.3.28_1
Already downloaded: /Users/john/Library/Caches/Homebrew/downloads/17e4e0def00184b561c8a490b5c0813a7c4f5e1365eb2e927570786eb4e05e09--berkeley-db@5-5.3.28_1.bottle_manifest.json
==> Verifying attestation for berkeley-db@5
==> Pouring berkeley-db@5--5.3.28_1.sonoma.bottle.tar.gz
🍺  /usr/local/Cellar/berkeley-db@5/5.3.28_1: 5,272 files, 86.2MB
==> Installing perl
==> Verifying attestation for perl
==> Pouring perl--5.38.2_1.sonoma.bottle.tar.gz
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
And add the following to your shell profile e.g. ~/.profile or ~/.zshrc
  eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"
```

I then tried to reinstall `wakeonlan`
```
22:57:08.213 iMac191 ~ 
➜ brew reinstall wakeonlan
==> Downloading https://ghcr.io/v2/homebrew/core/wakeonlan/manifests/0.42
######################################################################################################## 100.0%
==> Fetching wakeonlan
==> Downloading https://ghcr.io/v2/homebrew/core/wakeonlan/blobs/sha256:fd7879b6d846df1d5a5186b6c05cde2207467aa
######################################################################################################## 100.0%
==> Reinstalling wakeonlan 
==> Verifying attestation for wakeonlan
Error: The bottle for wakeonlan has an invalid build provenance attestation.

This may indicate that the bottle was not produced by the expected
tap, or was maliciously inserted into the expected tap's bottle
storage.

Additional context:

no attestation matches subject: 6b8182ee6bef05029feecded36446c18b44004c1d7a0bf3160c0898945ed9a4f--wakeonlan--0.42.sonoma.bottle.tar.gz
```

### What did you expect to happen?

I expected `wakeonlan` to install without issue

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
show above in "What happened (include all command output)?"
```

**Comment by carlocab** [comment]
Duplicate of #177384

**Comment by 101Dude** [comment]
It's a duplicate?

I did find an old token and removed that from my environment. 
then I ran through the recommended actions
still unable to clear that error

```
brew config
HOMEBREW_VERSION: 4.4.0-119-g587949b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 587949bd8417c486795be04194f9e9baeaa9f5a7
Last commit: 15 minutes ago
Core tap HEAD: 1e2a03d80d050b4458daa3d0064dec70d6b38750
Core tap last commit: 4 days ago
Core tap JSON: 10 Oct 18:20 UTC
Core cask tap HEAD: c8ae1b30a9caac1344a857dfb4a8e46358c47a4a
Core cask tap last commit: 4 days ago
Core cask tap JSON: 10 Oct 18:20 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--greedy", "--require-sha", "--no-quarantine", "--appdir=/Applications", "--fontdir=/Library/Fonts", "--qlplugindir=/Library/QuickLook", "--internet_plugindir=/Library/Internet Plug-Ins", "--prefpanedir=/Library/PreferencePanes/", "--servicedir=/Library/Services"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Me38PdP2OJ/org.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.5 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.46.2 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-x86_64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.0

gh auth status
github.com
  ✓ Logged in to github.com account 101Dude (keyring)
  - Active account: true
  - Git operations protocol: https
  - Token: gho_************************************
  - Token scopes: 'gist', 'read:org', 'repo', 'workflow'
```

**Comment by carlocab** [comment]
Do
```
brew untap homebrew/core
brew update
```
then try `brew install wakeonlan` again.
