### ISSUE TITLE
SWI-Prolog development installation fails

### ISSUE THREAD

**Issue by zephyrfalcon** [Homebrew/homebrew-core#19140]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? --> https://gist.github.com/zephyrfalcon/969a9f4c43c1572276d0050a56115019
- [n/a] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I am trying to install the development version of SWI-Prolog (package `swi-prolog`). This used to work in the past, but since a month or two (not exactly sure) it fails. The stable version does install properly. Previously installed development versions also still work. I saw that a new version (7.7.1) was available, and decided to try it, but the same problem still occurs.

- What happened (include command output)

This is my current situation:

```
hans@vulpix ~/temp % brew info swi-prolog
swi-prolog: stable 7.4.2 (bottled), devel 7.7.1, HEAD
ISO/Edinburgh-style Prolog interpreter
http://www.swi-prolog.org/
/usr/local/Cellar/swi-prolog/7.4.2 (791 files, 18.9MB)
  Poured from bottle on 2017-09-30 at 08:01:28
/usr/local/Cellar/swi-prolog/7.5.6 (1,795 files, 29.5MB)
  Built from source on 2017-06-18 at 11:30:11 with: --with-libarchive --with-xpce --with-jpl
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/swi-prolog.rb
==> Dependencies
Build: pkg-config ✔
Required: readline ✔, gmp ✔, openssl ✔
Optional: libarchive ✔
[...]
```

Then, when upgrading, this happens:

```
hans@vulpix ~/temp % brew upgrade swi-prolog --devel --with-libarchive --with-xpce
==> Upgrading 1 outdated package, with result:
swi-prolog 7.7.1
==> Upgrading swi-prolog --with-jpl --with-xpce --with-libarchive
==> Downloading http://www.swi-prolog.org/download/devel/src/swipl-7.7.1.tar.gz
Already downloaded: /Users/hans/Library/Caches/Homebrew/swi-prolog-7.7.1.tar.gz
Error: No such file or directory @ rb_sysopen - packages/archive/configure.in
```

(I looked at the source of SWI-Prolog 7.7.1, and the file `packages/archive/configure.in` does exist. I don't see any glaring differences here with previous versions either.)

- What you expected to happen

I expected version 7.7.1 to be installed. :)

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install swi-prolog --devel --with-xpce --with-libarchive
# or, if already installed:
brew upgrade swi-prolog --devel --with-xpce --with-libarchive
```

(For the record, I am reluctant to completely delete all the existing Prolog versions and do a fresh install, in case none of the installs work. I am working on a few projects that use Prolog and need to have at least the stable version around...)

**Comment by ilovezfs** [comment]
Do you have to build with `--with-libarchive`? If you leave that option out the problem should go away.

**Comment by zephyrfalcon** [comment]
I will try it, but I think the libarchive bindings are necessary to be able to install Prolog packs.

**Comment by zephyrfalcon** [comment]
It does install if I omit that option, but then it will no longer install packs (Prolog's equivalent of Ruby gems, Python eggs, etc). :(

**Comment by zephyrfalcon** [comment]
I see `packages/archives/configure.in` no longer exists (in the unpacked SWI-Prolog source), that probably has to do with it?

**Comment by ilovezfs** [comment]
@zephyrfalcon this fixes it: https://github.com/Homebrew/homebrew-core/pull/19151

**Comment by ilovezfs** [comment]
@zephyrfalcon thanks for reporting this! It's now fixed if you `brew update`

**Comment by zephyrfalcon** [comment]
Works like a charm! Thank you! ^__^

**Comment by ilovezfs** [comment]
@zephyrfalcon you're welcome!
