### ISSUE TITLE
gocryptfs depends on Linux because macfuse is closed source, but I can install macfuse?

### ISSUE THREAD

**Issue by OJFord** [Homebrew/homebrew-core#191546]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install gocryptfs on a Mac to use it

### What happened (include all command output)?

```
gocryptfs: Linux is required for this software.
libfuse: Linux is required for this software.
Error: gocryptfs: Unsatisfied requirements failed this build.
```

### What did you expect to happen?

that it would install, because having `brew install macfuse`d, macfuse is installed

the formula has:
https://github.com/Homebrew/homebrew-core/blob/ced14f2621a69cbaac160433eb08fab043485e32/Formula/g/gocryptfs.rb#L14-L15

but I don't see why that should make it refuse to install, `gocryptfs` _itself_ is open source, and anyway macfuse is installed through `brew`! If it being closed source is the problem, why is _that_ allowed, just not anything which actually wants to use it?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install gocryptfs`
```

**Comment by SMillerDev** [comment]
Anything in Homebrew/core must be open source to be included and can only depend on formula in Homebrew/core. Macfuse is a cask, so it is installable, just nothing in Homebrew/core can depend on it.

Just like no formula depend on Google Chrome etc

**Comment by OJFord** [comment]
Ok... but then 'requires closed-source macFUSE' is not the correct reason right, it's 'requires a cask'?

And that's surely not a reason to disallow its install, it's just an installation note? Hey btw you need macfuse which happens to be closed source but you can install it as it's a cask?

Or are you saying `gocryptfs` should be itself a cask on macOS so that it can depend on the cask macfuse?

**Comment by SMillerDev** [comment]
> Ok... but then 'requires closed-source macFUSE' is not the correct reason right, it's 'requires a cask'?

No, it requires something that is not allowed in Homebrew/core because it's not open source. That's why it was disabled in Homebrew/core.

> And that's surely not a reason to disallow its install, it's just an installation note? Hey btw you need macfuse which happens to be closed source but you can install it as it's a cask?
> Or are you saying gocryptfs should be itself a cask on macOS so that it can depend on the cask macfuse?

It can't be build on macOS because it requires components that are disallowed in Homebrew/core. Installing a cask won't make it work, it might make it compilable, but it still won't work from Homebrew/core because its CI does not have casks.

**Comment by OJFord** [comment]
Can you appreciate that from an end-user perspective it's pretty confusing that I can:
- `brew install gocryptfs` on Linux
- `brew install macfuse` on macOS

But I cannot:
- `brew install gocryptfs` on macOS, because it depends on `macfuse`
 
?

**Comment by ZhongRuoyu** [comment]
[It's a Homebrew policy](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae) that non-free software cannot be included in Homebrew's core tap, or depended on by other formulae; everything in `homebrew/core` needs to be open-source.

If installing `gocryptfs` is all you want, consider installing it from a tap from the community, e.g. [`gromgit/fuse`](https://github.com/gromgit/homebrew-fuse). TL;DR: `brew install gromgit/fuse/gocryptfs-mac`.

**Comment by OJFord** [comment]
Sure. I just think the UX is pretty poor, and it's exacerbated by this policy differing between cask & core.

(And that in many ways you no longer need to care if something's a cask or not - i.e. the bare `brew install`s as above.)

Why can't `gocryptfs` be a cask on macOS?

**Comment by SMillerDev** [comment]
> Why can't gocryptfs be a cask on macOS?

Because the gocryptfs project does not provide macOS binaries that could be shipped as a cask.
