### ISSUE TITLE
Can't find python on brew.sh

### ISSUE THREAD

**Issue by moenodedev** [Homebrew/homebrew-core#191878]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

https://formulae.brew.sh/formula/python is 404 and searching for `python` doesn't return a python package

![brew](https://github.com/user-attachments/assets/decc640b-df3c-4be9-8fd1-33ffce669466)

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install python

### What happened (include all command output)?

Python not found

### What did you expect to happen?

Python found

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Searched for python at https://formulae.brew.sh/
```

**Comment by ZhongRuoyu** [comment]
Try https://formulae.brew.sh/formula/python@3.12, https://formulae.brew.sh/formula/python@3.11, or any other Python version that's still supported.

**Comment by moenodedev** [comment]
For anyone else searching for python it's not available in homebrew. Download from https://www.python.org/downloads/macos/

**Comment by moenodedev** [comment]
@ZhongRuoyu You can close the issue

**Comment by ZhongRuoyu** [comment]
> For anyone else searching for python it's not available in homebrew.

As pointed out in my earlier comment (https://github.com/Homebrew/homebrew-core/issues/191878#issuecomment-2374596643), this is not true.

`brew install python` gets you Python 3.12.

**Comment by moenodedev** [comment]
Why is python not returned in the search results?

**Comment by moenodedev** [comment]
Is that a website bug?

**Comment by moenodedev** [comment]
![image](https://github.com/user-attachments/assets/e57f1837-c010-4705-ab4f-2be2050316ed)

**Comment by moenodedev** [comment]
Where do I report the issue?

**Comment by ZhongRuoyu** [comment]
> Why is python not returned in the search results?

Because the number of search results is limited to 5, while `python` happens to be not among the first 5.

**Comment by moenodedev** [comment]
Can that be changed to help beginners?

**Comment by ZhongRuoyu** [comment]
I have raised this internally for discussion. Thanks for the report!

**Comment by moenodedev** [comment]
Thank you :)

**Comment by moenodedev** [comment]
ruby and rust and go work without a version
