### ISSUE TITLE
Protobuf: program not found

### ISSUE THREAD

**Issue by geoffreywiseman** [Homebrew/homebrew-core#192]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Installed protobuf, ran protoc, got the following error:
```
$ brew install protobuf
==> Downloading https://homebrew.bintray.com/bottles/protobuf-2.6.1.el_capitan.bottle.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/protobuf-2.6.1.el_capitan.bottle.4.tar.gz
==> Pouring protobuf-2.6.1.el_capitan.bottle.4.tar.gz
==> Caveats
Editor support and examples have been installed to:
  /usr/local/Cellar/protobuf/2.6.1/share/doc/protobuf
==> Summary
🍺  /usr/local/Cellar/protobuf/2.6.1: 121 files, 6.9M
$ protoc MyProto.proto --objc_out=.
protoc-gen-objc: program not found or is not executable
--objc_out: protoc-gen-objc: Plugin failed with status code 1.
```

Maybe I'm missing something / doing something wrong, but ... I dunno.

**Comment by tdsmith** [comment]
The Google protobuf package doesn't support Objective C. You need to obtain an Objective C plugin from e.g. http://protobuf.io/#objc. Please let us know if we can help with anything!

**Comment by geoffreywiseman** [comment]
Yeah, sorry, I just realized talking to a colleague this morning that the objc version is only in 3.x line, which I hadn't realized -- I was deliberately downgrading from 3.0-beta when I hit this. I was the one who was confused. ;)
