### ISSUE TITLE
glslang formulae is outdated

### ISSUE THREAD

**Issue by davll** [Homebrew/homebrew-core#19209]
Current version in Homebrew:
```
Glslang Version: 3.0.729 19-Aug-2015
ESSL Version: OpenGL ES GLSL 3.00 glslang LunarG Khronos.3.0.729 19-Aug-2015
GLSL Version: 4.20 glslang LunarG Khronos.3.0.729 19-Aug-2015
SPIR-V Version 99, Revision 31
GLSL.std.450 Version 99, Revision 2
```

Which Glslang Version is still in 2015 (**two years ago**!)

It's recommended to add `--HEAD` option to provide users up-to-date version.

**Comment by ilovezfs** [comment]
>To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.
