### ISSUE TITLE
asciinema2gif: missing dependencies

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/homebrew-core#19226]
When you `brew install asciinema2gif` and run `asciinema2gif`, you get error:

```
This script has unmet dependencies. You need to install these first:
  convert
  gifsicle
```

This is defeating the purpose of a package manager.

I don't know what `convert` is but `gifsicle` has a homebrew formula, therefore it should be listed as a dependency. At least there should be a Caveats message for this formula.

cc: @ilovezfs

**Comment by stephengroat** [comment]
@ahmetb `convert` comes from `imagemagick`

both `imagemagick` and `gifsicle` are [listed as depends in the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/asciinema2gif.rb#L16-L17)

**Comment by ahmetb** [comment]
@stephengroat interesting enough, it didn't work. I could see gifsicle was present but was unlinked, I guess there was an error during its installation through `brew bundle`. I will close this, if anyone else runs into it, we can reopen.
