### ISSUE TITLE
macOS 10.13, Brew 1.3.5 Error -> fatal: 'origin/' is not a commit and a branch '' cannot be created from it

### ISSUE THREAD

**Issue by d-ave-g** [Homebrew/homebrew-core#19227]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
$ brew gist-logs clojure
https://gist.github.com/e01987f38bbc1d13b8c0f558f5ae23f2

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I attempted to ensure that the Homebrew packages were up to date per https://docs.brew.sh/FAQ.html

- What happened (include command output)
$ brew update
fatal: 'origin/' is not a commit and a branch '' cannot be created from it
fatal: Needed a single revision
invalid upstream origin/
Already up-to-date.

NOTE: This three line error is thrown with both simple "brew update" or using brew to install a package.  The command executes or the package installs, but the "Fatal" error lines and "invalid upstream origin/" errors are always displayed.

- What you expected to happen
Brew to execute without throwing an error message.

- Step-by-step reproduction instructions (by running `brew install` commands)
1. Open a Terminal window on a macOS 10.13 system with Homebrew 1.3.5 installed
2. Type "brew update"<RETURN> or "brew install clojure"<RETURN> (or any other package)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by JCount** [comment]
What's the output of `brew update --verbose` ?

**Comment by d-ave-g** [comment]
Thanks, JCount!  Please find below the information you requested:

$ brew update --verbose
Checking if we need to fetch /usr/local/Homebrew...
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 16 (delta 12), reused 13 (delta 9), pack-reused 0
Unpacking objects: 100% (16/16), done.
From https://github.com/Homebrew/homebrew-core
   be58c3e..545417a  master     -> origin/master
Updating /usr/local/Homebrew...
Reset branch 'stable'
Current branch stable is up to date.

Updating /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
fatal: 'origin/' is not a commit and a branch '' cannot be created from it
fatal: Needed a single revision
invalid upstream origin/

Already up-to-date.


$ git -C $(brew --repo) remote show origin
* remote origin
  Fetch URL: https://github.com/Homebrew/brew
  Push  URL: https://github.com/Homebrew/brew
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (up to date)


$ git -C $(brew --repo homebrew/core) remote show origin
* remote origin
  Fetch URL: https://github.com/Homebrew/homebrew-core
  Push  URL: https://github.com/Homebrew/homebrew-core
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)

**Comment by ilovezfs** [comment]
You can just

```
rm -rf "$(brew --repo homebrew/core)"
brew tap homebrew/core
brew update
```
and it should be back to normal.

**Comment by d-ave-g** [comment]
Thanks for the suggestion, ilovezfs.  I tried it, but the problem remains.  Please see below.  

Is there anything else I should try, or any other system/install/diagnostic information that would be of use in trying to troubleshoot the issue?  Please let me know.

$ rm -rf "$(brew --repo homebrew/core)"

$ brew tap homebrew/core
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4600, done.
remote: Compressing objects: 100% (4383/4383), done.
remote: Total 4600 (delta 34), reused 339 (delta 10), pack-reused 0
Receiving objects: 100% (4600/4600), 3.83 MiB | 6.23 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Tapped 4378 formulae (4,647 files, 11.9MB)

$ brew update
fatal: 'origin/' is not a commit and a branch '' cannot be created from it
fatal: Needed a single revision
invalid upstream origin/
Already up-to-date.

**Comment by ilovezfs** [comment]
Ah so it's not homebrew/core that is messed up. What's the output of
```
brew update --debug --verbose
```

**Comment by ilovezfs** [comment]
@d-ave-g did you manager to fix it?

**Comment by d-ave-g** [comment]
Hi @ilovezfs,

My apologies, I thought I had pasted the output of "brew update --debug --verbose" per your request.

The short answer is no.  The error still appears:

$ brew update
fatal: 'origin/' is not a commit and a branch '' cannot be created from it
fatal: Needed a single revision
invalid upstream origin/
Already up-to-date.


The output that you originally asked for follows below.  Please let me know if there is any additional information that you need - I'd be more than happy to provide it.  Thanks!


$ brew update --debug --verbose
++ [[ -z '' ]]
++ [[ -z '' ]]
++ [[ -n '' ]]
++ [[ -n '' ]]
++ export HOMEBREW_UPDATE_TO_TAG=1
++ HOMEBREW_UPDATE_TO_TAG=1
++ [[ -z '' ]]
++ HOMEBREW_AUTO_UPDATE_SECS=60
++ [[ -e /usr/local/Cellar ]]
++ [[ ! -w /usr/local/Cellar ]]
++ [[ ! -w /usr/local/Homebrew ]]
++ git --version
++ export GIT_TERMINAL_PROMPT=0
++ GIT_TERMINAL_PROMPT=0
++ export 'GIT_SSH_COMMAND=ssh -oBatchMode=yes'
++ GIT_SSH_COMMAND='ssh -oBatchMode=yes'
++ [[ -z 1 ]]
++ QUIET_ARGS=()
++ unset GIT_CONFIG
++ lock update
++ local name=update
++ local lock_dir=/usr/local/var/homebrew/locks
++ local lock_file=/usr/local/var/homebrew/locks/update
++ [[ -d /usr/local/var/homebrew/locks ]]
++ [[ -w /usr/local/var/homebrew/locks ]]
++ exec
++ exec
++ _create_lock 200 update
++ local lock_fd=200
++ local name=update
++ local ruby=/usr/bin/ruby
++ local python=/usr/bin/python
++ [[ -x /usr/bin/ruby ]]
++ [[ -x /usr/bin/python ]]
++ [[ -x /usr/bin/ruby ]]
++ /usr/bin/ruby -e 'exit(RUBY_VERSION >= '\''1.8.7'\'')'
++ /usr/bin/ruby -e 'File.new(200).flock(File::LOCK_EX | File::LOCK_NB) || exit(1)'
++ git_init_if_necessary
++ [[ -n 1 ]]
++ BREW_OFFICIAL_REMOTE=https://github.com/Homebrew/brew
++ CORE_OFFICIAL_REMOTE=https://github.com/Homebrew/homebrew-core
++ safe_cd /usr/local/Homebrew
++ cd /usr/local/Homebrew
++ [[ ! -d .git ]]
++ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core ]]
++ safe_cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ [[ ! -d .git ]]
++ rename_taps_dir_if_necessary
++ local tap_dir
++ local tap_dir_basename
++ local tap_dir_hyphens
++ local user
++ local repo
++ for tap_dir in '"$HOMEBREW_LIBRARY"/Taps/*'
++ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/.git ]]
++ continue
++ safe_cd /usr/local/Homebrew
++ cd /usr/local/Homebrew
++ trap '{ /usr/bin/pkill -P $$; wait; exit 130; }' SIGINT
++ local update_failed_file=/usr/local/Homebrew/.git/UPDATE_FAILED
++ rm -f /usr/local/Homebrew/.git/UPDATE_FAILED
++ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
++ [[ -d /usr/local/Homebrew/.git ]]
++ cd /usr/local/Homebrew
++ [[ -n 1 ]]
++ echo 'Checking if we need to fetch /usr/local/Homebrew...'
Checking if we need to fetch /usr/local/Homebrew...
+++ repo_var /usr/local/Homebrew
+++ local repo_var
+++ repo_var=/usr/local/Homebrew
+++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+++ repo_var=
+++ echo ''
++ TAP_VAR=
+++ upstream_branch
+++ local upstream_branch
++++ git symbolic-ref refs/remotes/origin/HEAD
+++ upstream_branch=
+++ upstream_branch=
+++ [[ -z '' ]]
+++ upstream_branch=master
+++ echo master
++ UPSTREAM_BRANCH_DIR=master
++ declare UPSTREAM_BRANCH=master
++ [[ UPSTREAM_BRANCH=master == \-\f ]]
++ command declare UPSTREAM_BRANCH=master
++ declare UPSTREAM_BRANCH=master
+++ git rev-parse -q --verify refs/remotes/origin/master
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify refs/remotes/origin/master
++ declare PREFETCH_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ [[ PREFETCH_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f == \-\f ]]
++ command declare PREFETCH_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ declare PREFETCH_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+++ git tag --list
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git tag --list
++ [[ -z 0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.7.1
0.8
0.8.1
0.9
0.9.1
0.9.2
0.9.3
0.9.4
0.9.5
0.9.8
0.9.9
1.0.0
1.0.1
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9
1.1.0
1.1.1
1.1.10
1.1.11
1.1.12
1.1.13
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.1.7
1.1.8
1.1.9
1.2.0
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
1.3.0
1.3.1
1.3.2
1.3.3
1.3.4
1.3.5
1.3.6 ]]
++ [[ -z '' ]]
++ [[ -n '' ]]
++ [[ -n '' ]]
++ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
++ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git ]]
++ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ [[ -n 1 ]]
++ echo 'Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...'
Checking if we need to fetch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
++ [[ -n '' ]]
+++ repo_var /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+++ git config remote.origin.url
+++ local repo_var
+++ repo_var=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+++ [[ -z /usr/local/bin/git ]]
+++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+++ /usr/local/bin/git config remote.origin.url
+++ repo_var=/homebrew/homebrew-core
++++ echo -n /homebrew/homebrew-core
++++ tr -C A-Za-z0-9 _
++++ tr '[:lower:]' '[:upper:]'
++ UPSTREAM_REPOSITORY_URL=https://github.com/Homebrew/brew
++ [[ https://github.com/Homebrew/brew = \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/* ]]
++ UPSTREAM_REPOSITORY=Homebrew/brew
++ UPSTREAM_REPOSITORY=Homebrew/brew
++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ [[ -n 1 ]]
+++ repo_var=_HOMEBREW_HOMEBREW_CORE
+++ echo _HOMEBREW_HOMEBREW_CORE
++ TAP_VAR=_HOMEBREW_HOMEBREW_CORE
+++ sed -n 's/^ETag: "\([a-f0-9]\{32\}\)".*/\1/p' .git/GITHUB_HEADERS
+++ upstream_branch
+++ local upstream_branch
++++ git symbolic-ref refs/remotes/origin/HEAD
++ GITHUB_API_ETAG=ad75311e22fcf8990aaa897ca700645d
++ GITHUB_API_ACCEPT=application/vnd.github.v3+json
++ GITHUB_API_ENDPOINT=tags
+++ /usr/bin/curl --silent --max-time 3 --output /dev/null --write-out '%{http_code}' --dump-header /usr/local/Homebrew/.git/GITHUB_HEADERS --user-agent 'Homebrew/1.3.6 (Macintosh; Intel Mac OS X 10.13) curl/7.54.0' --header 'Accept: application/vnd.github.v3+json' --header 'If-None-Match: "ad75311e22fcf8990aaa897ca700645d"' https://api.github.com/repos/Homebrew/brew/tags
+++ upstream_branch=refs/remotes/origin/master
+++ upstream_branch=master
+++ [[ -z master ]]
+++ echo master
++ UPSTREAM_BRANCH_DIR=master
++ declare UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CORE=master
++ [[ UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CORE=master == \-\f ]]
++ command declare UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CORE=master
++ declare UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CORE=master
+++ git rev-parse -q --verify refs/remotes/origin/master
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify refs/remotes/origin/master
++ declare PREFETCH_REVISION_HOMEBREW_HOMEBREW_CORE=b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12
++ [[ PREFETCH_REVISION_HOMEBREW_HOMEBREW_CORE=b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12 == \-\f ]]
++ command declare PREFETCH_REVISION_HOMEBREW_HOMEBREW_CORE=b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12
++ declare PREFETCH_REVISION_HOMEBREW_HOMEBREW_CORE=b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12
++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ [[ -z '' ]]
++ [[ -n '' ]]
++ [[ -n '' ]]
++ wait
++ [[ -n '' ]]
+++ git config remote.origin.url
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git config remote.origin.url
++ UPSTREAM_REPOSITORY_URL=https://github.com/Homebrew/homebrew-core
++ [[ https://github.com/Homebrew/homebrew-core = \h\t\t\p\s\:\/\/\g\i\t\h\u\b\.\c\o\m\/* ]]
++ UPSTREAM_REPOSITORY=Homebrew/homebrew-core
++ UPSTREAM_REPOSITORY=Homebrew/homebrew-core
++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+++ git rev-parse refs/remotes/origin/master
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse refs/remotes/origin/master
++ GITHUB_API_ETAG=b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12
++ GITHUB_API_ACCEPT=application/vnd.github.v3.sha
++ GITHUB_API_ENDPOINT=commits/master
+++ /usr/bin/curl --silent --max-time 3 --output /dev/null --write-out '%{http_code}' --dump-header /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/GITHUB_HEADERS --user-agent 'Homebrew/1.3.6 (Macintosh; Intel Mac OS X 10.13) curl/7.54.0' --header 'Accept: application/vnd.github.v3.sha' --header 'If-None-Match: "b7d1e926e9f2e3e950866b7e82ad1fbe34f1fb12"' https://api.github.com/repos/Homebrew/homebrew-core/commits/master
++ UPSTREAM_SHA_HTTP_CODE=304
++ UPSTREAM_SHA_HTTP_CODE=304
++ [[ -f /usr/local/Homebrew/.git/FETCH_HEAD ]]
++ [[ -f /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/FETCH_HEAD ]]
++ touch /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/FETCH_HEAD
++ touch /usr/local/Homebrew/.git/FETCH_HEAD
++ [[ -z '' ]]
++ [[ -z '' ]]
++ [[ 304 = \3\0\4 ]]
++ [[ 304 = \3\0\4 ]]
++ exit
++ exit
++ trap - SIGINT
++ [[ -f /usr/local/Homebrew/.git/UPDATE_FAILED ]]
++ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
++ [[ -d /usr/local/Homebrew/.git ]]
++ cd /usr/local/Homebrew
+++ repo_var /usr/local/Homebrew
+++ local repo_var
+++ repo_var=/usr/local/Homebrew
+++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+++ repo_var=
+++ echo ''
++ TAP_VAR=
++ UPSTREAM_BRANCH_VAR=UPSTREAM_BRANCH
++ UPSTREAM_BRANCH=
+++ read_current_revision
+++ git rev-parse -q --verify HEAD
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify HEAD
++ CURRENT_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ PREFETCH_REVISION_VAR=PREFETCH_REVISION
++ PREFETCH_REVISION=
+++ git rev-parse -q --verify refs/remotes/origin/
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify refs/remotes/origin/
++ POSTFETCH_REVISION=
++ [[ -n '' ]]
++ [[ -z '' ]]
++ [[ '' = '' ]]
++ [[ 270b752f5d9d218bfbed6fe85b6974fa653fb25f = '' ]]
++ merge_or_rebase /usr/local/Homebrew '' ''
++ [[ -n 1 ]]
++ echo 'Updating /usr/local/Homebrew...'
Updating /usr/local/Homebrew...
++ local DIR
++ local TAP_VAR
++ local UPSTREAM_BRANCH
++ DIR=/usr/local/Homebrew
++ cd /usr/local/Homebrew
++ TAP_VAR=
++ UPSTREAM_BRANCH=
++ unset STASHED
++ trap reset_on_interrupt SIGINT
++ [[ /usr/local/Homebrew = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ [[ -n 1 ]]
+++ git tag --list
+++ [[ -z /usr/local/bin/git ]]
+++ sort --field-separator=. --key=1,1nr -k 2,2nr -k 3,3nr
+++ /usr/local/bin/git tag --list
+++ grep --max-count=1 '^[0-9]*\.[0-9]*\.[0-9]*$'
++ UPSTREAM_TAG=1.3.6
++ '[' -n 1.3.6 ']'
++ REMOTE_REF=refs/tags/1.3.6
++ UPSTREAM_BRANCH=stable
+++ git status --untracked-files=all --porcelain
++ [[ -n '' ]]
+++ git symbolic-ref --short HEAD
++ INITIAL_BRANCH=stable
++ [[ -n 1.3.6 ]]
++ [[ -z 1.3.6 ]]
++ git checkout --force -B stable refs/tags/1.3.6
++ [[ -z /usr/local/bin/git ]]
++ /usr/local/bin/git checkout --force -B stable refs/tags/1.3.6
Reset branch 'stable'
+++ read_current_revision
+++ git rev-parse -q --verify HEAD
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify HEAD
++ INITIAL_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ export HOMEBREW_UPDATE_BEFORE=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ HOMEBREW_UPDATE_BEFORE=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ git config core.autocrlf false
++ [[ -z /usr/local/bin/git ]]
++ /usr/local/bin/git config core.autocrlf false
++ [[ -z '' ]]
++ git rebase refs/tags/1.3.6
++ [[ -z /usr/local/bin/git ]]
++ /usr/local/bin/git rebase refs/tags/1.3.6
Current branch stable is up to date.
+++ read_current_revision
+++ git rev-parse -q --verify HEAD
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify HEAD
++ CURRENT_REVISION=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ export HOMEBREW_UPDATE_AFTER=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ HOMEBREW_UPDATE_AFTER=270b752f5d9d218bfbed6fe85b6974fa653fb25f
++ [[ 270b752f5d9d218bfbed6fe85b6974fa653fb25f != \2\7\0\b\7\5\2\f\5\d\9\d\2\1\8\b\f\b\e\d\6\f\e\8\5\b\6\9\7\4\f\a\6\5\3\f\b\2\5\f ]]
++ trap '' SIGINT
++ [[ -n '' ]]
++ pop_stash_message
++ [[ -z '' ]]
++ return
++ trap - SIGINT
++ [[ -n 1 ]]
++ echo

++ for DIR in '"$HOMEBREW_REPOSITORY"' '"$HOMEBREW_LIBRARY"/Taps/*/*'
++ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git ]]
++ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+++ repo_var /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+++ local repo_var
+++ repo_var=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
+++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
+++ repo_var=/homebrew/homebrew-core
++++ echo -n /homebrew/homebrew-core
++++ tr -C A-Za-z0-9 _
++++ tr '[:lower:]' '[:upper:]'
+++ repo_var=_HOMEBREW_HOMEBREW_CORE
+++ echo _HOMEBREW_HOMEBREW_CORE
++ TAP_VAR=_HOMEBREW_HOMEBREW_CORE
++ UPSTREAM_BRANCH_VAR=UPSTREAM_BRANCH_HOMEBREW_HOMEBREW_CORE
++ UPSTREAM_BRANCH=
+++ read_current_revision
+++ git rev-parse -q --verify HEAD
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify HEAD
++ CURRENT_REVISION=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ PREFETCH_REVISION_VAR=PREFETCH_REVISION_HOMEBREW_HOMEBREW_CORE
++ PREFETCH_REVISION=
+++ git rev-parse -q --verify refs/remotes/origin/
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify refs/remotes/origin/
++ POSTFETCH_REVISION=
++ [[ -n '' ]]
++ [[ -z '' ]]
++ [[ '' = '' ]]
++ [[ ab8b54a22e303c6d88a6e4da9318ac072f415f35 = '' ]]
++ merge_or_rebase /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core _HOMEBREW_HOMEBREW_CORE ''
++ [[ -n 1 ]]
++ echo 'Updating /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...'
Updating /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
++ local DIR
++ local TAP_VAR
++ local UPSTREAM_BRANCH
++ DIR=/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
++ TAP_VAR=_HOMEBREW_HOMEBREW_CORE
++ UPSTREAM_BRANCH=
++ unset STASHED
++ trap reset_on_interrupt SIGINT
++ [[ /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core = \/\u\s\r\/\l\o\c\a\l\/\H\o\m\e\b\r\e\w ]]
++ UPSTREAM_TAG=
++ '[' -n '' ']'
++ REMOTE_REF=origin/
+++ git status --untracked-files=all --porcelain
++ [[ -n '' ]]
+++ git symbolic-ref --short HEAD
++ INITIAL_BRANCH=master
++ [[ -n '' ]]
++ [[ master != '' ]]
++ [[ -n master ]]
++ [[ -z '' ]]
++ git merge-base --is-ancestor '' origin/
++ git checkout --force -B '' origin/
++ [[ -z /usr/local/bin/git ]]
++ /usr/local/bin/git checkout --force -B '' origin/
fatal: 'origin/' is not a commit and a branch '' cannot be created from it
+++ read_current_revision
+++ git rev-parse -q --verify HEAD
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify HEAD
++ INITIAL_REVISION=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ export HOMEBREW_UPDATE_BEFORE_HOMEBREW_HOMEBREW_CORE=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ HOMEBREW_UPDATE_BEFORE_HOMEBREW_HOMEBREW_CORE=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ git config core.autocrlf false
++ [[ -z /usr/local/bin/git ]]
++ /usr/local/bin/git config core.autocrlf false
++ [[ -z '' ]]
++ git rebase origin/
++ [[ -z /usr/local/bin/git ]]
++ /usr/local/bin/git rebase origin/
fatal: Needed a single revision
invalid upstream origin/
+++ read_current_revision
+++ git rev-parse -q --verify HEAD
+++ [[ -z /usr/local/bin/git ]]
+++ /usr/local/bin/git rev-parse -q --verify HEAD
++ CURRENT_REVISION=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ export HOMEBREW_UPDATE_AFTER_HOMEBREW_HOMEBREW_CORE=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ HOMEBREW_UPDATE_AFTER_HOMEBREW_HOMEBREW_CORE=ab8b54a22e303c6d88a6e4da9318ac072f415f35
++ [[ ab8b54a22e303c6d88a6e4da9318ac072f415f35 != \a\b\8\b\5\4\a\2\2\e\3\0\3\c\6\d\8\8\a\6\e\4\d\a\9\3\1\8\a\c\0\7\2\f\4\1\5\f\3\5 ]]
++ trap '' SIGINT
++ [[ -n '' ]]
++ pop_stash_message
++ [[ -z '' ]]
++ return
++ trap - SIGINT
++ [[ -n 1 ]]
++ echo

++ safe_cd /usr/local/Homebrew
++ cd /usr/local/Homebrew
++ [[ -n '' ]]
++ [[ -n '' ]]
++ [[ -n '' ]]
++ [[ -d /usr/local/Homebrew/Library/LinkedKegs ]]
++ [[ -n '' ]]
++ [[ -z '' ]]
++ echo 'Already up-to-date.'
Already up-to-date.
++ exit 0
