### ISSUE TITLE
Unable to install/uninstall Go

### ISSUE THREAD

**Issue by oli-laban** [Homebrew/homebrew-core#19236]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### What you were trying to do (and why)
Install `hugo`
### What happened (include command output)
Installing/uninstalling `go` or it seems any package that depends on go renders the error:
`Error: go: version missing for "gotools" resource!`
`brew gist-logs go` results in the same error.
### What you expected to happen
Successful installation.
### Step-by-step reproduction instructions (by running `brew install` commands)
`brew install go` or `brew install hugo`
### Brew config
```
HOMEBREW_VERSION: 1.3.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ac8b58537fe3dd71098a43afcc6a1785dcde1d39
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c7fb0c17f25e38c6762c88dfc7a512592c12c447
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/oli/.rvm/rubies/ruby-2.3.3/bin/ruby
Java: 1.8.0_121, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: N/A
```

**Comment by cafreeman** [comment]
Just ran into the same issue trying to install `kubectl`.

The error appears to originate from [this commit](https://github.com/Homebrew/homebrew-core/commit/3da9acff6e48a050fe30bd68bfd76494dcaa3f2f#diff-9846fb3e9988a7fc2566903da7d72a9a).

Without the `version` definition, the URL used to download `gotools` doesn't appear to be created properly.

**Comment by ochronus** [comment]
Having the same issue running almost any brew subcommand.

`➜  ~ brew info go
Error: go: version missing for "gotools" resource!`

`➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Users/csaba/GOPATH/bin/
Error: go: version missing for "gotools" resource!`

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/19221#issuecomment-335199633
