### ISSUE TITLE
graph-tool failed to build on macOS 10.13 and Xcode 9.0

### ISSUE THREAD

**Issue by moreka** [Homebrew/homebrew-core#19239]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

While installing graph-tool, it gives errors related to Xcode `<cmath>`. The complete errors can be found in the [gist](https://gist.github.com/b9b25cf156e6dabe60e8aa15ed4fc764). I think there is a problem with clang packed with homebrew.

To reproduce error, having installed Xcode 9.0 and commandline tools 9.0 on macOS 10.13, run the following:

`brew install graph-tool --without-matplotlib --without-numpy --without-scipy --verbose`

You'll get several errors like
```
In file included from ../../../../src/graph/graph_filtering.hh:21:
...
In file included from /usr/local/include/boost/config/no_tr1/cmath.hpp:21:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace

using ::signbit;
```

I'm using brew python2 and also installed numpy, matplotlib and scipy via pip. I also tried to use compilers other than brew's clang located in `/usr/local/Homebrew/Library/Homebrew/shims/`, but it didn't recognise CGAL and other libraries during configure.

By the way, I had no problems prior to this version of macOS. I made a clean install of OS and couldn't install graph-tool anymore. 

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
graph-tool is in homebrew/science.
