### ISSUE TITLE
brew install ht error

### ISSUE THREAD

**Issue by axmanwang** [Homebrew/homebrew-core#19261]
Downloading https://downloads.sourceforge.net/project/hte/ht-source/ht-2.1.0
Already downloaded: /Users/axman/Library/Caches/Homebrew/ht-2.1.0.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ht/2.1.0 --disable-x11-textmode
==> make install
Last 15 lines from /Users/axman/Library/Logs/Homebrew/ht/02.make:
                                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:693:1: note: candidate function
abs(float __lcpp_x) _NOEXCEPT {return ::fabsf(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:697:1: note: candidate function
abs(double __lcpp_x) _NOEXCEPT {return ::fabs(__lcpp_x);}
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/math.h:701:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {return ::fabsl(__lcpp_x);}
^
clang++ -DHAVE_CONFIG_H -I.   -I./analyser -I./asm -I./info -I./io/posix -I./io -I./output -I./eval -I.   -DNOMACROS  -O3 -fomit-frame-pointer -Wall -fsigned-char -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Woverloaded-virtual -Wnon-virtual-dtor  -c -o htdebug.o htdebug.cc
1 error generated.
make[1]: *** [htapp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

-------------------------------------
vi htapp.cc 
find abs 
modify "while (abs(a-b) > 1) { " to "while (abs((int)(a - b)) > 1) {"

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/18493 and https://github.com/sebastianbiallas/ht/pull/18.
