### ISSUE TITLE
Suggestion:add the rocketmq

### ISSUE THREAD

**Issue by rainplus** [Homebrew/homebrew-core#19295]
when the rocketmq became apache top level project,i want to install it by brew install rocketmq.but i can't find it.
-----------------------------------------------------
sorry,I just started using honwbrew,doesn't know the Formulae syntax

**Comment by fxcoudert** [comment]
We don't really consider requests for new software, so your best bet is probably to ask the upstream developers or the community to contribute a [pull request](https://github.com/Homebrew/homebrew-core/pulls) to include rocketmq into Homebrew.
