### ISSUE TITLE
wxmac does not install on High Sierra 

### ISSUE THREAD

**Issue by skyman** [Homebrew/homebrew-core#19290]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install wxmac.

- What happened (include command output)
Gist-log: https://gist.github.com/anonymous/b9a218adb158b26da8c6c0839cdaca8b
The installation fails when make is called. The reason seems to be that XCode changed some macros including this verify_noerr one. The change is explained in /usr/include/AssertMacros.h:

```
/*
 *	For time immemorial, Mac OS X has defined version of most of these macros without the __ prefix, which
 *	could collide with similarly named functions or macros in user code, including new functionality in
 *	Boost and the C++ standard library.
 *
 *  macOS High Sierra and iOS 11 will now require that clients move to the new macros as defined above.
```

The verify_noerr macro is included.

- What you expected to happen
The installation to complete normally like it did in Sierra.

- Step-by-step reproduction instructions (by running `brew install` commands)
Run `brew install wxmac`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by DomT4** [comment]
> Core tap last commit: 8 months ago

There's ya problem lol.
```bash
cd $(brew --repo homebrew/core) && git fetch && git reset --hard origin/master
```

**Comment by skyman** [comment]
It works, I wonder what the upgrade to High Sierra did that broke this... Thanks a lot!

**Comment by DomT4** [comment]
> I wonder what the upgrade to High Sierra did that broke this

Likely unrelated. There were a couple of old update bugs with Homebrew that were resolved pretty quickly but took _some_ existing users to notice something had gone awry & apply a manual fix.

It's possible/probable you got snagged as part of that _some_, unless you find future `brew update`s aren't matching `Core tap HEAD` to the latest [master branch commit](https://github.com/Homebrew/homebrew-core/commits/master).
