### ISSUE TITLE
Fetching unbound results in a 404

### ISSUE THREAD

**Issue by ryanolson-aumni** [Homebrew/homebrew-core#193139]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use codecov orb within CircleCI. It uses Homebrew to install curl and a few other packages. It is failing to install unbound (404).

### What happened (include all command output)?

```bash
==> Fetching unbound
curl: (22) The requested URL returned error: 404                              

Error: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.3\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.3\)\ curl/7.79.1 --header Accept-Language:\ en --fail --progress-bar --retry 3 --location --remote-time --output /Users/distiller/Library/Caches/Homebrew/Formula/unbound.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/6408033d2a6c15b8ccdab9e298ce273734a470c3/Formula/unbound.rb` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404 
```

### What did you expect to happen?

Successful install of unbound

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by Bo98** [comment]
> Homebrew/4.0.3

This is nearly two years old and likely doesn't work properly anymore. I checked and this was fixed in 4.0.12.

Alternatively, macOS 13 or later will work better as it doesn't need to build things from source like macOS 12.
