### ISSUE TITLE
x265 2.5_1 fails to build on Sierra 10.12.6 and Xcode 9.0 (9A235)

### ISSUE THREAD

**Issue by Ranutso** [Homebrew/homebrew-core#19343]
- [✓] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [✓] Ran `brew update` and retried your prior step? (Twice)
- [✓] Ran `brew doctor`, fixed all issues and retried your prior step? I am building from source. I hope I am helping you with these less popular formulas.
- [✓] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [✓] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Updating x265 to the new version 2.5_1 (after brew update).

- What happened (include command output)
```
$ brew upgrade x265
==> Upgrading 1 outdated package, with result:
x265 2.5_1
==> Upgrading x265 
==> Downloading https://bitbucket.org/multicoreware/x265/downloads/x265_2.5.tar.gz
Already downloaded: /Users/rash/Library/Caches/Homebrew/x265-2.5.tar.gz
==> cmake /private/tmp/x265-20171011-31060-7fpe7y/x265_2.5/source -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=
==> make
==> cmake /private/tmp/x265-20171011-31060-7fpe7y/x265_2.5/source -DMAIN12=ON -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INS
==> make
==> cmake /private/tmp/x265-20171011-31060-7fpe7y/x265_2.5/source -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=
==> make
Last 15 lines from /Users/rash/Library/Logs/Homebrew/x265/06.make:
/usr/bin/ranlib libx265.a
[ 87%] Built target x265-static
/usr/local/Cellar/cmake/3.9.4/bin/cmake -E cmake_symlink_library libx265.130.dylib libx265.130.dylib libx265.dylib
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.4/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.4/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

make[2]: *** [libx265.dylib] Abort trap: 6
make[2]: *** Deleting file `libx265.dylib'
make[1]: *** [CMakeFiles/x265-shared.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

- What you expected to happen
For x265 to build successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)
Run `brew update`
Run `brew upgrade x265`
or
Run `brew install x265`

This is the gist-logs output: https://gist.github.com/anonymous/1a82f868f7193a0f0fd9ebeef5ff1fed

**Comment by JCount** [comment]
@Ranutso Once #19388 is merged, running:
```
brew update
brew upgrade cmake
```
should fix this issue, and allow you to successfully upgrade `x265`.

**Comment by JCount** [comment]
@Ranutso This should now be fixed if you upgrade `cmake`, so I am going to close this. Feel free to post a comment if you still have issues.
