### ISSUE TITLE
exiftool incorrect file and version

### ISSUE THREAD

**Issue by jprokos** [Homebrew/homebrew-core#19378]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [y ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [y ] Ran `brew update` and retried your prior step?
- [y ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [y ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [y] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Brew Config
HOMEBREW_VERSION: 1.3.5-8-g30b84ac
ORIGIN: https://github.com/Homebrew/brew
HEAD: 30b84ac6f39d2f0cd3e3993959a11888a047afd5
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7d96c959dc43b46efb27ce2a030f91ff8a1157c1
Core tap last commit: 59 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.0
CLT: N/A
X11: N/A

### brew doctor
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mp4v2

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to access the exiftool man pages after installing it, but none have been installed.
- What happened (include command output)
Terminal reports no man page found for exiftool
- What you expected to happen
I expect the complete and lastest version of the software to be compiled and the man pages to be installed.
- Step-by-step reproduction instructions (by running `brew install` commands)
After running brew install exiftool and running man exiftool no man page is found and the installed version is not the latest version.

The issue appears to be that an incorrect file is linked for this formulae. There are two files, one is a smaller version of exiftool as an .dmg package (sans the man files). The other is the complete image including the man files. Downloading the latest exiftool.tar.gz file and building it shows the man files exist in that file. The smaller .dmg package does not contain the man files.

http://owl.phy.queensu.ca/~phil/exiftool/ExifTool-10.63.dmg
http://owl.phy.queensu.ca/~phil/exiftool/Image-ExifTool-10.63.tar.gz

I am not sure how to correct this or even if this is the correct place to report it. Is this an issue or a pull request?

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by DomT4** [comment]
> I am not sure how to correct this or even if this is the correct place to report it. Is this an issue or a pull request?

The latter, if there's an update available. Formula should be bumped using the source code, not the `.dmg`, FYI.

**Comment by ilovezfs** [comment]
@jprokos this should be fixed if you `brew update` and `brew reinstall exiftool`

**Comment by jprokos** [comment]
Hi, thank you but trying again today gets me an outdated version and no man files. The current version is 10.63. Installing today brew downloaded 10.55. The version is one issue, I think the formula doesn't contain the correct commands to add the man files. 


### ==> Downloading https://homebrew.bintray.com/bottles/exiftool-10.55.high_sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring exiftool-10.55.high_sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/exiftool/10.55: 363 files, 17.5MB

10:44:42>~
   iMac112: admin$ man exiftool
No manual entry for exiftool

**Comment by DomT4** [comment]
Check the formula notation:
```
  # Ensure release is tagged production before submitting.
  # https://www.sno.phy.queensu.ca/~phil/exiftool/history.html
```

The `10.63` release was marked not yet "production" so you'd need to install it with `--devel`.

**Comment by jprokos** [comment]
That's something I don't know how to check, thank you. Can you help us figure out why man pages never install?

**Comment by DomT4** [comment]
Upstream don't seem to provide them. There's HTML documentation in:
```
/usr/local/Cellar/exiftool/10.55/share/doc/
```
as of https://github.com/Homebrew/homebrew-core/commit/267d1f5a19c.

**Comment by jprokos** [comment]
Thanks DomT4. "Upstream"? In my previous comment it says they are provided if using the Unix install and not the OS X package. Does the formula link to the UNIX install or the package?

**Comment by ilovezfs** [comment]
@jprokos the man pages should now install if you brew update and brew upgrade, thanks to https://github.com/Homebrew/homebrew-core/pull/19516.
