### ISSUE TITLE
gmp requires `--disable-assembly` to static link

### ISSUE THREAD

**Issue by jeroen** [Homebrew/homebrew-core#19407]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Static linking to `libgmp.a` from the `gmp` package fails with:

```
illegal text-relocation to '___gmpn_mul_1' in /usr/local/lib/libgmp.a(mul_1.o) from '___gmpn_mul_1' in /usr/local/lib/libgmp.a(mul_1.o) for architecture x86_64
```
A similar warning (though no error) appears when static linking [test.c](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gmp.rb#L29-L45) from the formula.
```
cc test.c /usr/local/opt/gmp/lib/libgmp.a
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in ___gmpn_mul_1 from /usr/local/opt/gmp/lib/libgmp.a(mul_1.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
```

The solution from the gmp forums is to compile with `--disable-assembly` on MacOS. I confirmed this works and it does not seem to have any side effects. Can I file a PR to add an option for this?

**Comment by ilovezfs** [comment]
Please check if this works as expected:
```
iMac-TMP:homebrew-core joe$ git diff -- Formula/gmp.rb 
diff --git a/Formula/gmp.rb b/Formula/gmp.rb
index 55379c3..2652f6d 100644
--- a/Formula/gmp.rb
+++ b/Formula/gmp.rb
@@ -20,10 +20,14 @@ class Gmp < Formula
     ENV.cxx11 if build.cxx11?
     args = %W[--prefix=#{prefix} --enable-cxx]
     args << "--build=core2-apple-darwin#{`uname -r`.to_i}" if build.bottle?
-    system "./configure", *args
+    system "./configure", "--disable-static", *args
     system "make"
     system "make", "check"
     system "make", "install"
+    system "make", "clean"
+    system "./configure", "--disable-shared", "--disable-assembly", *args
+    system "make"
+    lib.install Dir[".libs/*.a"]
   end
 
   test do
```

**Comment by jeroen** [comment]
Yes this works, thanks!

**Comment by jeroen** [comment]
Should I prepare a PR with that patch?

**Comment by fxcoudert** [comment]
FWIW: `--with-pic` is a better solution to that problem, that does not disable the fast assembler code paths.
