### ISSUE TITLE
Cannot tap homebrew/core

### ISSUE THREAD

**Issue by kmnovak** [Homebrew/homebrew-core#19456]
I'm attempting to install Linuxbrew onto a new ec2 instance running Amazon Linux and it seems like its unable to successfully tap homebrew/core due to some invalid formulas.

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

`brew gist-logs core` fails:

> Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.6.rb
go@1.6: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
go: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/smlnj.rb
smlnj: version missing for "cm" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.7.rb
go@1.7: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/platypus.rb
invalid attribute for formula 'platypus': version (nil)
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.5.rb
go@1.5: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.8.rb
go@1.8: version missing for "gotools" resource!
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/ec2-user/.linuxbrew/bin/brew tap homebrew/core -q

- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config` output:
> HOMEBREW_VERSION: 1.3.2
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: b464f111f1bd4e8190e65eadf186935c99c0534c
Last commit: 4 days ago
Core tap: N/A
HOMEBREW_PREFIX: /home/ec2-user/.linuxbrew
HOMEBREW_REPOSITORY: /home/ec2-user/.linuxbrew
HOMEBREW_CELLAR: /home/ec2-user/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648 => /usr/bin/ruby2.0
Clang: N/A
Git: 2.13.6 => /usr/bin/git
Perl: /usr/bin/perl
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.6.rb
go@1.6: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
go: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/smlnj.rb
smlnj: version missing for "cm" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.7.rb
go@1.7: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/platypus.rb
invalid attribute for formula 'platypus': version (nil)
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.5.rb
go@1.5: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.8.rb
go@1.8: version missing for "gotools" resource!
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/ec2-user/.linuxbrew/bin/brew tap homebrew/core -q

`brew doctor` output:
> Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.6.rb
go@1.6: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go.rb
go: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/smlnj.rb
smlnj: version missing for "cm" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.7.rb
go@1.7: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/platypus.rb
invalid attribute for formula 'platypus': version (nil)
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.5.rb
go@1.5: version missing for "gotools" resource!
Error: Invalid formula: /home/ec2-user/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/go@1.8.rb
go@1.8: version missing for "gotools" resource!
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/ec2-user/.linuxbrew/bin/brew tap homebrew/core -q

To help us debug your issue please explain:
- What you were trying to do (and why)
I'm attempting to install a new version of Linuxbrew into a fresh ec2 instance running Amazon Linux.
- What happened (include command output)
Any time I attempt to do any `brew install` commands, homebrew fails to execute because it can't tap the core package.
- What you expected to happen
Successful installation.
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew.
