### ISSUE TITLE
phpmd prints Serializable interface deprecated message

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-core#194850]
phpmd when run, spews php deprecation messages

```
PHP Deprecated:  Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

The formula is using unmodified phar from upstream:
- https://github.com/Homebrew/homebrew-core/blob/376641e86202b509a04a2dab0a0bda7d695babd2/Formula/p/phpmd.rb#L4

```
❯ phpmd /etc/passwd xml unusedcode
PHP Deprecated:  Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in phar:///opt/homebrew/Cellar/phpmd/2.15.0/bin/phpmd/vendor/symfony/config/Resource/FileResource.php on line 21

Deprecated: Symfony\Component\Config\Resource\FileResource implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in phar:///opt/homebrew/Cellar/phpmd/2.15.0/bin/phpmd/vendor/symfony/config/Resource/FileResource.php on line 21
<?xml version="1.0" encoding="UTF-8" ?>
<pmd version="2.15.0snapshot202312110823" tool="phpmd" timestamp="2024-10-18T09:27:05+00:00">
</pmd>
```

The notices go away if using php 8.0:

```
❯ /opt/homebrew/opt/php@8.0/bin/php /opt/homebrew/bin/phpmd /etc/passwd xml unusedcode
<?xml version="1.0" encoding="UTF-8" ?>
<pmd version="2.15.0snapshot202312110823" tool="phpmd" timestamp="2024-10-18T09:28:21+00:00">
</pmd>
```

Upstream reports they are not going to fix this:
- https://github.com/phpmd/phpmd/issues/971

So I'm thinking since php@8.0 is still available, easy fix would be to use php@8.0.

I'm not sure what upstream mean by installing from composer would fix the problem, is the code modified during their phar build?

**Comment by glensc** [comment]
I read the error again: The notice comes from `Symfony\Component\Config` package. so likely when using composer it will pick newer `symfony/config` package. 

So this could be fixed if using composer rather than downloading the phar file.

**Comment by SMillerDev** [comment]
This is an upstream compatibility issue. If they don't want to support the Phar install we should deprecate the formula.

**Comment by glensc** [comment]
Building phar, or installing via composer (in Formula) is not an option?

**Comment by glensc** [comment]
Just to be sure that it's correctly understood, upstream does support phar, but they build it PHP 5.3 compatible way, which causes this issue:
- https://github.com/phpmd/phpmd/issues/971#issuecomment-1214924926

**Comment by SMillerDev** [comment]
> Building phar, or installing via composer

If upstream support building the phar file somehow you can try that. Installing through composer doesn't work as a homebrew package.

> Just to be sure that it's correctly understood, upstream does support phar, but they build it PHP 5.3 compatible way, which causes this issue:

They support a phar for versions Homebrew doesn't ship so as far as Homebrew is concerned it's unsupported.

**Comment by carlocab** [comment]
> > Just to be sure that it's correctly understood, upstream does support phar, but they build it PHP 5.3 compatible way, which causes this issue:
> 
> They support a phar for versions Homebrew doesn't ship so as far as Homebrew is concerned it's unsupported.

I don't think this is accurate. I think they support the phar for versions that Homebrew ships; it's just that they also support it for versions that Homebrew doesn't ship (which is what produces the warning).
