### ISSUE TITLE
Upgrading ode 0.15.2 fails due to SHA256 mismatch

### ISSUE THREAD

**Issue by jslee02** [Homebrew/homebrew-core#19487]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): upgrading ode
- What happened (include command output):
```
$ brew upgrade ode
==> Upgrading 1 outdated package, with result:
ode 0.15.2
==> Upgrading ode --with-double-precision --with-libccd
==> Downloading https://bitbucket.org/odedevs/ode/downloads/ode-0.15.2.tar.gz
Already downloaded: /Users/jeongseoklee/Library/Caches/Homebrew/ode-0.15.2.tar.gz
Error: SHA256 mismatch
Expected: 2eaebb9f8b7642815e46227956ca223806f666acd11e31708bd030028cf72bac
Actual: 02c43ac96ada3cd623061c79b71a6f66e31e003a3138343d2df0d0d6fef9b9a7
Archive: /Users/jeongseoklee/Library/Caches/Homebrew/ode-0.15.2.tar.gz
To retry an incomplete download, remove the file above.
```
- What you expected to happen: upgrading ode without any errors
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

```
$ brew config
HOMEBREW_VERSION: 1.3.5-14-ge1808bf
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1808bf0e35d522cda4ee4803f13746b604713f5
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 713fec875fc7b18b4eb9fccec587c11692bad8e6
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_101, 1.7.0_45
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.0.0.1.1504363082
X11: 2.7.11 => /opt/X11
```

**Comment by JCount** [comment]
@jslee02 I got the correct checksum fetching the source just now. Try removing the cached file with `rm /Users/jeongseoklee/Library/Caches/Homebrew/ode-0.15.2.tar.gz` and then running `brew upgrade ode` again. Your current artifact is likely a partial download or corrupt.

**Comment by jslee02** [comment]
@JCount It worked. I didn't know that it could happen. Good to know. Thanks for the help!
