### ISSUE TITLE
need to create symbolic link after trigger `brew install bottom`

### ISSUE THREAD

**Issue by hanleilei** [Homebrew/homebrew-core#194964]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
󰀵 ywu  …/homebrew/bin   stable   21:05 
 brew config
HOMEBREW_VERSION: 4.4.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 70672606c6ac07a5e8f75abeda7b8736e8285dbe
Last commit: 5 days ago
Core tap JSON: 19 Oct 13:05 UTC
Core cask tap JSON: 19 Oct 13:05 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
all_proxy: socks5://127.0.0.1:4781
http_proxy: http://127.0.0.1:4780
https_proxy: http://127.0.0.1:4780
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.0.1-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: N/A
Rosetta 2: false

󰀵 ywu  …/homebrew/bin   stable   21:07 
 brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

after install the bottom with `brew install bottom`

### What happened (include all command output)?

 I can not run bottom directly, 

### What did you expect to happen?

run the bottom application

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
after I create a symbolic link with this command: `ln -s /opt/homebrew/Cellar/bottom/0.10.2/btm /opt/homebrew/bin/bottom`.
```

**Comment by ZhongRuoyu** [comment]
Your `bottom` installation is not linked for some reason. You may be able to fix it with `brew link bottom` which should have been done automatically when you installed the formula.

> ```
>  brew doctor
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!
> ```

The `brew doctor` output you provided is incomplete. To make it possible to further diagnose this, you need to provide the *full* output of `brew doctor`, including all the warnings.

**Comment by hanleilei** [comment]
thanks, here is the docter:

```shell
󰀵 ywu  ~   v22.9.0   01:43 
 brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed casks are deprecated or disabled.
You should find replacements for the following casks:
  sourcetrail

󰀵 ywu  ~   v22.9.0   01:43 





```

**Comment by ZhongRuoyu** [comment]
Actually, from the command you posted earlier:

> ```shell
> ln -s /opt/homebrew/Cellar/bottom/0.10.2/btm /opt/homebrew/bin/bottom
> ```

You seem to expect to run bottom as `bottom`, but [the command to run it is `btm` instead](https://clementtsang.github.io/bottom/stable/#usage-and-configuration), so nothing is actually broken.
