### ISSUE TITLE
Problem with TGDMLParse in root6

### ISSUE THREAD

**Issue by will-fawcett** [Homebrew/homebrew-core#19505]
Hello, 

I am attempting to visualise a tracker with ROOTs visualisation software. I installed root6 formula with homebrew, and it seems that the libGdml.so is missing from root/lib . There may also be other shared objects missing. Unfortunately, I don't understand the problem much, so I can't offer any real insight. 

To recreate the problem
- install root6 with homebrew
`brew install root6`

- create a dummy file
`touch TestBox.gdml`

- run root
`root`

- Enter these commands in the root prompt. 
```
root [0] TGeoManager* gman = new TGeoManager();
root [1] gman->Import("TestBox.gdml");
```

The error is 
`error: 'TGDMLParse' is not a class, namespace, or enumeration`

EDIT: Here is the output from gist-logs:
```
brew gist-logs root6
Error: No logs.
```
and from brew doctor (I know what the unexpected dylibs are):
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcvmfs_fuse.2.4.1.dylib
  /usr/local/lib/libcvmfs_fuse_debug.2.4.1.dylib
```

#
- [ x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by ilovezfs** [comment]
>[ x] If brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

**Comment by ilovezfs** [comment]
Please post the `brew gist-logs`, `brew config`, and `brew doctor` output.

**Comment by will-fawcett** [comment]
Hi, here are the results:

Here is the result from gist logs
```
$ brew gist-logs root6
Error: No logs.

```

From brew config
```
$ brew config root6
HOMEBREW_VERSION: 1.3.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 91ab116ace7f4f97d3440190463c93be9ec6d675
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5142e6c30f7b98fc32f84f9ed19e9a7797776398
Core tap last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_101
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.10 => /opt/X11
```

and from brew doctor (I know wha tthe unexpected dylibs are)
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libcvmfs_fuse.2.4.1.dylib
  /usr/local/lib/libcvmfs_fuse_debug.2.4.1.dylib
```

**Comment by ilovezfs** [comment]
@will-fawcett I have now shipped #19753 so this should be fixed if you
```
brew update
brew reinstall root
```

**Comment by will-fawcett** [comment]
Thanks very much for the fix. I don't think there are any other packages
that are necessary. However, since there is the option it would be nice to
set
// Build using C++17 compatible mode, requires gcc >= 7.1.0 or clang
cxx17:BOOL=OFF
To ON
that would require an additional dependency on gcc version, but that is
also available via homebrew :)

**Comment by ilovezfs** [comment]
@will-fawcett that is an interesting idea, but if we can avoid a GCC dependency, we will at just about any cost ;)

**Comment by ilovezfs** [comment]
>Thanks very much for the fix.

You're welcome!
