### ISSUE TITLE
Recommend cask installs for GUI counterparts of CLI-only formulas?

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-core#1950]
Opening this issue in the name of consistency, and to see if this is somehow desirable.

[`fontforge`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/fontforge.rb), [`platypus`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/platypus.rb), and [`transmission`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/transmission.rb) are the formulas I found that made me think of this.

Both `platypus` and `transmission` have `caveats` that tell the user only the CLI was installed, and that to install the GUI they should **visit the website**.

`fontforge`, on the other hand, has a comment (not a `caveat`) telling that to get the GUI, they should **use homebrew-cask**.

`depends_on :java`, tells the user to **use homebrew-cask** or **visit the website**.

This is inconsistent, and there may be other formulas like this, but right now, these are what seem like the right changes<sup id="a1">[1](#f1)</sup>:

- [x] Add to `platypus` a note about installing the GUI via homebrew-cask (https://github.com/Homebrew/homebrew-core/pull/2080)
- [x] Add to `transmission` a note about installing the GUI via homebrew-cask (https://github.com/Homebrew/homebrew-core/pull/2081)
- [x] Add a `caveat` to `fontforge` (https://github.com/Homebrew/homebrew-core/pull/2083)
  - [x] Mention getting GUI via website
  - [x] Mention getting GUI via homebrew-cask

---

<sup id="f1">[1](#a1)</sup> I’m not necessarily pushing for homebrew-cask. Either way, consistency could be improved on these.

**Comment by MikeMcQuaid** [comment]
Having caveats for all these sounds good.

**Comment by DomT4** [comment]
Agreed.

**Comment by DomT4** [comment]
All three now have the discussed caveats, per @vitorgalvao's PRs. Closing as fixed.
