### ISSUE TITLE
R --with-cairo option

### ISSUE THREAD

**Issue by andremrsantos** [Homebrew/homebrew-core#19504]
Hi everyone,

I was working on R recently and found no support for cairo graphics environment in my macOS. Unfortunately, some graphics functions (like compress tiff) requires cairo support, and the current formula hardcoded the options `--without-cairo`.
May I suggest adding an optional dependency such as open-blas and java?

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/15925#issuecomment-317240808
