### ISSUE TITLE
jack may be broken

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew-core#19543]
I was alerted to this issue by the OP of https://discourse.brew.sh/t/moc-and-mplayer-not-working-properly/1152.

```console
$ brew kegs berkeley-db jack
/usr/local/Cellar/berkeley-db/6.2.32 (5,632 files, 115.2MB) *
  Poured from bottle on 2017-10-17 at 07:13:36
/usr/local/Cellar/jack/0.125.0_1 (64 files, 1.1MB) *
  Poured from bottle on 2017-10-17 at 07:13:38
```

The issue can be reproduced with either `moc` or `mpv --with-jack`.

With `moc`:

```console
$ jackd -d coreaudio  # This is a blocking call, so have it in a separate terminal session.
jackd 0.125.0
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

JACK compiled with POSIX SHM support.
loading driver ..
Error calling AudioUnitSetProperty - kAudioUnitProperty_StreamFormat kAudioUnitScope_Output
could not handle external client request
(null)
Cannot open metadata DB at /tmp/jack-501/default/metadata.db: Unknown error: 1752629350
[1]    42868 segmentation fault  jackd -d coreaudio

$ mocp
Running the server...
Trying JACK...

FATAL_ERROR: Server exited!
```

The segfault happens immediately after launching `mocp`.

With `mpv --with-jack`:

```console
$ jackd -d coreaudio
jackd 0.125.0
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

JACK compiled with POSIX SHM support.
loading driver ..
Error calling AudioUnitSetProperty - kAudioUnitProperty_StreamFormat kAudioUnitScope_Output
could not handle external client request
(null)
Cannot open metadata DB at /tmp/jack-501/default/metadata.db: Unknown error: 167510098
[1]    42912 segmentation fault  jackd -d coreaudio

$ mpv --ao=jack some-video-or-audio-file
...
```

Note that `mpv` plays audio normally; the segfault only happens when `mpv` quits (you can quit immediately with `q`).

Since there are two separate repros, the issue seems to be in `jack`, or maybe `berkeley-db`. I don't have time (or actually the incentive) to investigate, so not sure if it's an upstream issue.

(Tests done on 10.12.6.)

**Comment by ilovezfs** [comment]
Oh how gross.

**Comment by ilovezfs** [comment]
@zmwangx it seems to work if it's rebuilt from source. Can you still repro with a source build of jack?

**Comment by zmwangx** [comment]
@ilovezfs A source build seems to eliminate the segfault, but still

```
could not handle external client request
```

and `mocp` still does not work.

**Comment by ilovezfs** [comment]
OK so sounds like we should revision bump to escape the segfault at least.

**Comment by zmwangx** [comment]
Yeah.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/19548

**Comment by ilovezfs** [comment]
@zmwangx looks like `mocp` is fine if it's rebuilt too …

**Comment by zmwangx** [comment]
Sounds great...

**Comment by ilovezfs** [comment]
trying with `--build-bottle` now

**Comment by ilovezfs** [comment]
um now the moc bottle is working … this makes no sense

**Comment by ilovezfs** [comment]
hmm maybe it was due to an instance already running

**Comment by zmwangx** [comment]
The moc bottle now works for me too. Lovely.

**Comment by ilovezfs** [comment]
Seemed to stop working after killing the running instance which was left over from the source build I think.

**Comment by zmwangx** [comment]
Right...

**Comment by ilovezfs** [comment]
moc revision bump: https://github.com/Homebrew/homebrew-core/pull/19549

**Comment by ilovezfs** [comment]
(new jack bottles already pushed)

**Comment by ilovezfs** [comment]
I'm assuming this is now resolved since I've pushed new jack bottles and new moc bottles. @zmwangx can you confirm that mpv is :cool: now too?

**Comment by zmwangx** [comment]
Yeah, seems to work now.

**Comment by ilovezfs** [comment]
thanks for checking
