### ISSUE TITLE
No jpeg, png, x11 and cairo capabilities

### ISSUE THREAD

**Issue by brakkobain** [Homebrew/homebrew-core#19557]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by brakkobain** [comment]
The title says it all. I have lots of old code for figures relying on svg() and I'd like to keep using it.
Installing r using:
brew install r
and checking capabilities() in the r console gives jpeg, png, x11 and cairo as FALSE.
This is not the case when installing r from the CRAN package. In this case all capabilities are TRUE.

**Comment by brakkobain** [comment]
When installing R with 
brew install r
and checking capabilities() I get:
jpeg, png, x11 and cairo as FALSE
This is not the case when installing R with the CRAN package.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/15925#issuecomment-317240808

**Comment by slhck** [comment]
@ilovezfs Seeing that this has come up several times now, and in the other thread Mike was saying that:

> (X11) Seems to be used sometimes, but we probably do not want to have this as a default.

… why is X11 not available as `--with-x11` anymore?

I don't necessarily want to create my own tap just for adding a flag that was already there at some point. Would you accept a PR that adds a `--with-x11`?

**Comment by ilovezfs** [comment]
>Would you accept a PR that adds a --with-x11?

No, we have 10,898 installs in the last 30 days so I think the formula is proving sufficiently useful as-is without adding an X11 option, especially when we're trying to retire X11 options and deps wherever they still exist in formulae.

**Comment by slhck** [comment]
From the multiple issues related to missing Cairo / X11 capabilities raised in the last months (and I was just about to post another one), I would actually conclude that there is still a use case for it. (I'm not sure I understand how it is possible to judge the usefulness a formula from the number of installs, when it's about an option that is *not* there. Hard to prove in any case.)

So I think the argument is that you want to retire X11 support, but it's not a strict dependency, is it? Consider that the “normal” R version from CRAN does support X11 just fine.

**Comment by ilovezfs** [comment]
At this point, I'd be fine with non-optionally requiring Cairo, but I'm not interested in adding X11 support back to the formula even as just an option.

**Comment by randy3k** [comment]
It is pretty unfortunate that homebrew R doesn't support cairo and x11. Without them, R can no longer create `svg` images. R users may not discover it when they first install/upgrade their homebrew R. Then later they will find it out when they need to save svg images.

**Comment by randy3k** [comment]
I am now hosting a tap containing a formula `r-x11` with cairo and x11 supports.
https://github.com/randy3k/homebrew-r#installing-r-with-x11-support

**Comment by joe4dev** [comment]
X11 and Cairo is also required to embed fonts with ggplot using `device=cairo_pdf` (see https://stackoverflow.com/questions/27542302/ggplot-embedded-fonts-in-pdf)

The `r` formula should at least provide this option. We have to resort to the workaround from @randy3k in the meantime. Thanks for that 👏

**Comment by ilovezfs** [comment]
Does that really require both x11 and cairo or just cairo?

**Comment by randy3k** [comment]
> In principle these devices are independent of X11 (as is seen by their presence on Windows). But on a Unix-alike the cairo libraries may be distributed as part of the X11 system and hence that (on macOS, XQuartz) may need to be installed.

https://www.rdocumentation.org/packages/grDevices/versions/3.4.3/topics/cairo

**Comment by ilovezfs** [comment]
So the fact that /opt/X11/lib/libcairo.dylib exists if XQuartz is installed means upstream doesn't look for any other cairo?

**Comment by randy3k** [comment]
R in fact uses `pkg-config` to discover `libcairo`.

**Comment by ilovezfs** [comment]
@randy3k OK. Yet https://github.com/Homebrew/homebrew-core/pull/24094 needed to do string replacements to make it work without X11.
