### ISSUE TITLE
Install javaHL failed

### ISSUE THREAD

**Issue by futterwack** [Homebrew/homebrew-core#19584]
i try to install javaHL by homebrew, but failed

command  : brew install --universal --java subversion

output:

vandeMacBook-Pro-2:~ van$ brew install --universal --java subversion
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/van in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Users/van in PATH, mode 040777
Warning: subversion: --java was deprecated; using --with-java instead!
Warning: subversion: this formula has no --universal option so it will be ignored!
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.9.7.tar.bz2
Already downloaded: /Users/van/Library/Caches/Homebrew/subversion-1.9.7.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
Already downloaded: /Users/van/Library/Caches/Homebrew/subversion--serf-1.3.9.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.9.7_1/libexec/serf GSSAPI=/usr CC=/usr/bin/cla
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.9.7_1 --enable-optimize --with-zlib=/usr --with-sqlite=/usr/loc
==> make
==> make install
==> make tools
==> make install-tools
==> make swig-pl
==> make install-swig-pl
==> make javahl
==> make install-javahl
==> make swig-rb EXTRA_SWIG_LDFLAGS=-L/usr/lib
Last 15 lines from /Users/van/Library/Logs/Homebrew/subversion/12.make:
2017-10-18 11:12:21 +0800

make
swig-rb
EXTRA_SWIG_LDFLAGS=-L/usr/lib

/bin/sh "/private/tmp/subversion-20171018-66853-1svoqeb/subversion-1.9.7/libtool" --tag=CC --silent --mode=compile none  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/private/tmp/subversion-20171018-66853-1svoqeb/subversion-1.9.7/subversion/bindings/swig/ruby/libsvn_swig_ruby -prefer-pic -c -o subversion/bindings/swig/ruby/svn_client.lo subversion/bindings/swig/ruby/svn_client.c
/private/tmp/subversion-20171018-66853-1svoqeb/subversion-1.9.7/libtool: line 1760: none: command not found
make: *** [subversion/bindings/swig/ruby/svn_client.lo] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
Formulae affected by Homebrew/brew#2482 https://github.com/Homebrew/homebrew-core/issues/13133

**Comment by mjrit** [comment]
I'm seeing the same error when running `brew upgrade` when i'ts upgrading svn (previously installed using `--with-java`

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by virtualirfan** [comment]
Did anyone find a workaround?
