### ISSUE TITLE
upgrade homebrew/php/php71

### ISSUE THREAD

**Issue by tdelhaise** [Homebrew/homebrew-core#19591]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

On HighSierra 

Darwin yellow.smobee.com 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

Launched :

1 - brew update first
2 - brew upgrade => failed upgrade homebrew/php/php71 with 
         .............
          checking if the location of ZLIB install directory is defined... no
          configure: error: Cannot find libz
         ..............
3 - brew update => nothing new ... 
4 - brew update => nothing new ... 
5 - brew doctor => ask me to add /usr/local/sbin to path => so done this.
6 - brew update => nothing new
7 - brew upgrade => still 
         .............
          checking if the location of ZLIB install directory is defined... no
          configure: error: Cannot find libz
         ..............
8 - brew gist-logs homebrew/php/php71 =>
https://gist.github.com/720d4e014440119aa013e677e516ebf4

**Comment by ilovezfs** [comment]
Please raise this with the php tap https://github.com/Homebrew/homebrew-php/issues
