### ISSUE TITLE
Error installing Maven after installing Java 9

### ISSUE THREAD

**Issue by howieweiner** [Homebrew/homebrew-core#19593]
Hi

I am installing both Java JK and Maven on a fairly newly built Macbook with no prior installs of Java. I have installed Java using `brew cask install java`. This now installs Java 9.

Both `java` and `javac` work from the cmd line and confirm the version as 9.01.

Running `/usr/libexec/java_home -v 9` outputs `/Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home`

I have updated my .bash_profle to set $JAVA_HOME using
export JAVA_HOME=`/usr/libexec/java_home -v 9`.

Having re-sourced my profile file, I can echo $JAVA_HOME and see that it has been set.

`brew config` outputs `Java: 9.0.1`

Yet, when I run `brew install maven` I am informed that JavaRequirement unsatisfied!

I'm guessing the formula does not yet detect Java 9?

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/19593. We'll have a new tag shortly.

**Comment by ilovezfs** [comment]
Make that https://github.com/Homebrew/brew/pull/3333.

**Comment by ilovezfs** [comment]
@howieweiner this is now fixed if you `brew update` because https://github.com/Homebrew/brew/releases/tag/1.3.6 just shipped.

**Comment by howieweiner** [comment]
@ilovezfs Just tried, and confirm that the issue is now fixed.

3 hour turnaround. That is impressive!
