### ISSUE TITLE
MacOS Sequoia 15.1  use bind service occur reboot

### ISSUE THREAD

**Issue by zouchengli** [Homebrew/homebrew-core#196028]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew info bind
==> bind: stable 9.20.3 (bottled), HEAD
Implementation of the DNS protocols
https://www.isc.org/bind/
Installed
/opt/homebrew/Cellar/bind/9.20.3 (316 files, 8.4MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-10-29 at 16:45:12
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/b/bind.rb
License: MPL-2.0
==> Dependencies
Build: pkg-config ✔
Required: jemalloc ✔, json-c ✔, libidn2 ✔, libnghttp2 ✔, libuv ✔, openssl@3 ✔, readline ✔, userspace-rcu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To start bind now and restart at startup:
  sudo brew services start bind
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/bind/sbin/named -f -L /opt/homebrew/var/log/named/named.log
==> Analytics
install: 1,513 (30 days), 4,679 (90 days), 16,164 (365 days)
install-on-request: 1,420 (30 days), 4,377 (90 days), 14,784 (365 days)
build-error: 8 (30 days)
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I want use dns server test 
Because install bind service support my test

### What happened (include all command output)?

Execute domain resolve command:
ping github.com
Occur Immediately reboot
<img width="1020" alt="image" src="https://github.com/user-attachments/assets/99a27e07-e568-4ca0-a907-9b0ebd3bf6fc">

### What did you expect to happen?

<img width="718" alt="image" src="https://github.com/user-attachments/assets/a6fde9a5-4a8e-4126-9dec-f32e2dec89ce">

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install bind
sudo brew services start bind
sudo networksetup -setdnsservers Ethernet 127.0.0.1 
ping github.com
```
<img width="581" alt="image" src="https://github.com/user-attachments/assets/957a12bb-46d2-4abb-939f-69a7dce77ae9">

**Comment by carlocab** [comment]
What is the output of `brew config` and `brew doctor`?

**Comment by zouchengli** [comment]
> What is the output of `brew config` and `brew doctor`?

<img width="652" alt="image" src="https://github.com/user-attachments/assets/2e49404b-ce66-4f07-9242-e332c1aa2629">

**Comment by carlocab** [comment]
Please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). They also typically can't be parsed by screen readers. Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

**Comment by carlocab** [comment]
Does it behave the same way when you're not running in a VM?

**Comment by zouchengli** [comment]
> Does it behave the same way when you're not running in a VM?

same

**Comment by zouchengli** [comment]
> Please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). They also typically can't be parsed by screen readers. Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

`
chengli.zou@clz-vm-m1-max ~ % brew config
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 3 days ago
Core tap JSON: 30 Oct 01:44 UTC
Core cask tap JSON: 30 Oct 01:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: quad-core 64-bit dunno
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
chengli.zou@clz-vm-m1-max ~ % brew doctor
Your system is ready to brew.
chengli.zou@clz-vm-m1-max ~ % 
`

**Comment by zouchengli** [comment]
> > Please [don't use screenshots](https://meta.stackoverflow.com/a/285557) when sharing the output of commands in your terminal. They're often difficult to read and impossible to reuse (e.g. when looking up error messages). They also typically can't be parsed by screen readers. Instead, copy the text here and wrap them in three back-ticks (```) on the line before and on the line after to format them properly.

```
chengli.zou@clz-vm-m1-max ~ % brew config
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 3 days ago
Core tap JSON: 30 Oct 01:44 UTC
Core cask tap JSON: 30 Oct 01:44 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: quad-core 64-bit dunno
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
chengli.zou@clz-vm-m1-max ~ % brew doctor
Your system is ready to brew.
chengli.zou@clz-vm-m1-max ~ % 
```

**Comment by ZhongRuoyu** [comment]
This problem doesn't seem specific to macOS 15.1. There are other reports from macOS 14.7 and 15.0:

- https://lists.isc.org/pipermail/bind-users/2024-October/109096.html
- https://gitlab.isc.org/isc-projects/bind9/-/issues/4975

**Comment by zouchengli** [comment]
> This problem doesn't seem specific to macOS 15.1. There are other reports from macOS 14.7 and 15.0:
> 
> * https://lists.isc.org/pipermail/bind-users/2024-October/109096.html
> * https://gitlab.isc.org/isc-projects/bind9/-/issues/4975

It seems so, because I have been using this service for a long time, and it seems that this problem has appeared since the new system was launched this year. So has no one fixed this problem yet? I would like to ask whether this problem is a problem with the service itself or a problem with the system?

**Comment by ZhongRuoyu** [comment]
It should be a kernel problem because a user space process should not cause a kernel panic like this.

I encourage you to report this to Apple (via the "Problem Report for macOS" window in the screenshot you provided at the beginning), with the commands to reproduce this.

**Comment by zouchengli** [comment]
> It should be a kernel problem because a user space program should not cause a kernel panic like this.
> 
> I wasn't able to reproduce this on x86_64 macOS 15.1, so this may be specific to Apple Silicon. I encourage you to report this to Apple (via the "Problem Report for macOS" window in the screenshot you provided at the beginning), with the commands to reproduce this.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/fe1cc547-5967-4fea-b41e-04064be08a1c">
OK，I have given feedback to Apple, but they may not reply or accept it.

**Comment by tsborland** [comment]
I was experiencing the same issue today after doing some updating.

After some testing, it looks like reverting libuv from 1.49.2 to the previously working version 1.48.0 allows BIND to start for me at latest release (9.20.3)

```
~ % brew outdated
libuv (1.48.0) < 1.49.2 [pinned at 1.48.0]
```

I was able to do this by grabbing the libuv.rb formula file and installing manually:
```
~ % curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/aaf5fb716c35c00f77901cded781c746bf108ce2/Formula/lib/libuv.rb
~ % brew reinstall ~/libuv.rb
```

I then pinned it to avoid breaking things again.

I will likely do further testing Monday to see if 1.49.0 or 1.49.1 is stable as well.

**Comment by tsborland** [comment]
I was experiencing the same issue today after doing some updating.

After some testing, it looks like reverting libuv from 1.49.2 to the previously working version 1.48.0 allows BIND to start for me at latest release (9.20.3)

```
~ % brew outdated
libuv (1.48.0) < 1.49.2 [pinned at 1.48.0]
```

I was able to do this by grabbing the libuv.rb formula file and installing manually:
```
~ % curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/aaf5fb716c35c00f77901cded781c746bf108ce2/Formula/lib/libuv.rb
~ % brew reinstall ~/libuv.rb
```

I then pinned it to avoid breaking things again.

I will likely do further testing Monday to see if 1.49.0 or 1.49.1 is stable as well.

**Comment by zouchengli** [comment]
> ```shell
> ping github.com
> ```

Thanks very much，It's worked for me.

**Comment by zouchengli** [comment]
> I was experiencing the same issue today after doing some updating.
> 
> After some testing, it looks like reverting libuv from 1.49.2 to the previously working version 1.48.0 allows BIND to start for me at latest release (9.20.3)
> 
> ```
> ~ % brew outdated
> libuv (1.48.0) < 1.49.2 [pinned at 1.48.0]
> ```
> 
> I was able to do this by grabbing the libuv.rb formula file and installing manually:
> 
> ```
> ~ % curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/aaf5fb716c35c00f77901cded781c746bf108ce2/Formula/lib/libuv.rb
> ~ % brew reinstall ~/libuv.rb
> ```
> 
> I then pinned it to avoid breaking things again.
> 
> I will likely do further testing Monday to see if 1.49.0 or 1.49.1 is stable as well.

Thanks very much，It's worked for me.

**Comment by jameslbrown** [comment]
Thanks @tsborland - I've now got 1.48 of libuv, but bind refuses to install without updating it to 1.92:

```
brew pin libuv 
% brew outdated
libuv (1.48.0) < 1.49.2 [pinned at 1.48.0]
brew install bind
==> Downloading https://ghcr.io/v2/homebrew/core/bind/manifests/9.20.3
Already downloaded: /Users/jlbrown/Library/Caches/Homebrew/downloads/98737115e5f4c439396f16d43dfaaab58484fd043918638f23c1f15306ac0716--bind-9.20.3.bottle_manifest.json
Error: You must `brew unpin libuv` as installing bind requires the latest version of pinned dependencies
```

**Comment by jameslbrown** [comment]
```
sudo brew services stop bind
brew uninstall bind
brew install bind
curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/aaf5fb716c35c00f77901cded781c746bf108ce2/Formula/lib/libuv.rb
brew reinstall ~/libuv.rb
brew pin libuv
sudo brew services start bind
```
worked

**Comment by jameslbrown** [comment]
Update:
Computer no longer reboots!

Unfortunately after a while named crashes.

![PastedGraphic-1](https://github.com/user-attachments/assets/5d334553-62e1-4073-98b5-f4f24b6cb0b6)

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x001c000000200070 -> 0x0000000000200070 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x001c000000200070

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [55960]

VM Region Info: 0x200070 is not in any region.  Bytes before following region: 4375265168
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      104e94000-104eec000    [  352K] r-x/r-x SM=COW  /opt/homebrew/*/named

Application Specific Information:
crashed on child side of fork pre-exec
```

**Comment by carlocab** [comment]
> After some testing, it looks like reverting libuv from 1.49.2 to the previously working version 1.48.0 allows BIND to start for me at latest release (9.20.3)

Please report this to the bind and/or libuv projects so it can be fixed.

**Comment by jameslbrown** [comment]
> > After some testing, it looks like reverting libuv from 1.49.2 to the previously working version 1.48.0 allows BIND to start for me at latest release (9.20.3)
> 
> Please report this to the bind and/or libuv projects so it can be fixed.

ISC (developers of BIND) had been in contact with Apple.

You can also file FeedBack to them:

[https://www.apple.com/feedback/macos/](url)

or better:
[https://developer.apple.com/bug-reporting/](url)

**Comment by carlocab** [comment]
Thanks! Is the libuv project aware of this issue? It seems to affect them too.

**Comment by tsborland** [comment]
I opened https://github.com/libuv/libuv/issues/4594

**Comment by carlocab** [comment]
> I opened https://github.com/libuv/libuv/issues/4594
> 

Thanks!

**Comment by foonon** [comment]
This problem showed up for me on both Intel AND Apple Silicon systems running MacOS 15.2 when using the latest 'brewed bind. In both cases I'm using Ethernet for my network connection, not WiFi.

On my Apple Silicon system (2024 Mac Mini M4 Pro), I can start named and the host immediately panics as soon as I run a 'dig' against the server.

On my Intel system (2018 Mac Mini), the failure is not always as immediate. Usually, the network stack has a meltdown after named tries to service a query. Eventually the system MAY panic. Or not and the network is simply hosed. Either way, the only way to recover here is to reboot the system and hope that named is not restarted.

~f
