### ISSUE TITLE
Ruby 2.4.2 unavailable for Yosemite

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#19626]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Upgrading ruby 2.4.1 to 2.4.2 fails
```
$ brew upgrade ruby
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 56458f03fc to c4e8c7906d.

==> Upgrading 1 outdated package, with result:
ruby 2.4.2
==> Upgrading ruby 
==> Downloading https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.2.tar.xz
Already downloaded: /Users/hanxue/Library/Caches/Homebrew/ruby-2.4.2.tar.xz
==> ./configure --prefix=/usr/local/Cellar/ruby/2.4.2 --enable-shared --disable-
==> make
Last 15 lines from /Users/hanxue/Library/Logs/Homebrew/ruby/02.make:
Target: x86_64-apple-darwin14.5.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /tmp/regexec-878078.c
clang: note: diagnostic msg: /tmp/regexec-878078.sh
clang: note: diagnostic msg: 

********************
make: *** [regexec.o] Error 254
make: *** Waiting for unfinished jobs....
```

This is the gist output:  [https://gist.github.com/220e7ce4f5fc774bfe12758c6f4d6952](https://gist.github.com/220e7ce4f5fc774bfe12758c6f4d6952)

I notice that the error comes from clang. How can I compile ruby using the homebrew'ed version of llvm/clang?

In  `Formula/ruby.rb`, there is no bottle for Yosemite

```ruby
  bottle do
    sha256 "1d7e596bdd35aa4759945f82e8581fa9ec61325573b3203d3217ce13d2c574a8" => :high_sierra
    sha256 "77c0c862695e7d2bb028bb8c9129552088a2af055bf7161c6a44771747ad60b6" => :sierra
    sha256 "0f8cb64f36323fd90e53d54138b024296e09dc662e3969cd7e122a98e1eea3f3" => :el_capitan
  end
```

Are bottles no longer generated for Yosemite by default?

From what I can tell, Yosemite is still supported by homebrew [https://github.com/Homebrew/brew/blob/021729e1646212d47d3f52c0b29034e7da97693b/Library/Homebrew/os/mac.rb#L42](https://github.com/Homebrew/brew/blob/021729e1646212d47d3f52c0b29034e7da97693b/Library/Homebrew/os/mac.rb#L42). 

Compiling Ruby 2.4.2 using `ruby-build` or via manual compilation below still works

```bash
$ ./configure --prefix=/usr/local/Cellar/ruby/2.4.2 --enable-shared --disable-silent-rules --with-sitedir=/usr/local/lib/ruby/site_ruby --with-vendordir=/usr/local/lib/ruby/vendor_ruby --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/readline:/usr/local/opt/gmp:/usr/local/opt/libffi
```

**Comment by ilovezfs** [comment]
We only support and provide bottles for the most recent three versions. So 10.11, 10.12, and 10.13 currently.

```
Warning: Your Xcode (6.4) is outdated.
Please update to Xcode 7.2.1 (or delete it).
Xcode can be updated from the App Store.
```
This is likely the problem. But I suggest you upgrade to at least 10.11 if possible.

**Comment by hanxue** [comment]
@ilovezfs Thanks for the quick response. I am unable to upgrade to 10.11 at the moment, hence I am stuck with Xcode 6.4

How can I  build ruby 2.4.2 using homebrew'ed toolchain instead of the system toolchain?

**Comment by ilovezfs** [comment]
You can upgrade to Xcode 7.2.1 on Yosemite.
