### ISSUE TITLE
Upgrade formulae for Lulu wipes out all its preferences

### ISSUE THREAD

**Issue by jebediah2** [Homebrew/homebrew-core#196202]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Upgrading Lulu performs a full uninstall, which therefore deletes all its preferences (aka 'rules') while these are the whole point of installing it. Lulu's creator objective-see has pointed out that brew's formulae is not created by them, doesn't work, and will not preserve the rules, making it effectively garbage: https://github.com/objective-see/LuLu/issues/590#issuecomment-2016605470

==> Upgrading lulu
==> Downloading https://github.com/objective-see/LuLu/releases/download/v2.9.6/L
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Running uninstall script /Applications/LuLu.app/Contents/Resources/LuLu Unin
Password:
LULU: performing full 'uninstall' logic
LULU: waiting for 'kextcache' to complete
LULU: uninstall ok!
...reboot to complete
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew upgrade lulu

### What happened (include all command output)?

It performed a full uninstall of the previous version while upgrading.

==> Upgrading lulu
==> Downloading https://github.com/objective-see/LuLu/releases/download/v2.9.6/L
==> Downloading from https://objects.githubusercontent.com/github-production-rel
######################################################################### 100.0%
==> Running uninstall script /Applications/LuLu.app/Contents/Resources/LuLu Unin
Password:
LULU: performing full 'uninstall' logic
LULU: waiting for 'kextcache' to complete
LULU: uninstall ok!
...reboot to complete

### What did you expect to happen?

That lulu would be updated while preserving its preferences.
Lulu's creator objective-see has pointed out that brew's formulae is not created by them, doesn't work, and will not preserve the rules, making it effectively garbage: https://github.com/objective-see/LuLu/issues/590#issuecomment-2016605470

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade lulu
```

**Comment by daeho-ro** [comment]
It should be homebrew cask and it was discussed long ago,
- https://github.com/Homebrew/homebrew-cask/issues/166180

and indeed, uninstall of lulu for recent version will not trigger uninstaller. Before upgrade, what version did you use?

**Comment by jebediah2** [comment]
My bad, I had looked into all other repos and left cask out.

I was doing lulu 2.3.1 -> 2.9.6

I don't know enough about homebrew to suggest how to prevent this from happening to other people. I was unable to find anything at all online and in the homebrew repos, so I thought I should mention it here, but since it's right there is the cask repo, there is no need. I'll close this and let the discussion continue on the issue you pointed to, even though it hasn't been solved, at least for whoever is upgrading from older versions.
