### ISSUE TITLE
HomeBrew stopped working in Brazil - `brew update`

### ISSUE THREAD

**Issue by arnonrdp** [Homebrew/homebrew-core#196356]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 5 days ago
Core tap JSON: 01 Nov 11:56 UTC
Core cask tap JSON: 30 Oct 13:33 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: dodeca-core 64-bit arm_lobos
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false
➜  ~ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

brew update

### What happened (include all command output)?

==> Updating Homebrew...
Error: Failed to download https://formulae.brew.sh/api/formula.jws.json!
Failed to download https://formulae.brew.sh/api/cask.jws.json!
Failed to download https://formulae.brew.sh/api/formula_tap_migrations.jws.json!
Failed to download https://formulae.brew.sh/api/cask_tap_migrations.jws.json!

### What did you expect to happen?

I expected it works.
Also for `brew update` it doesn't work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I also tried to install a package:
`brew install docker` but I have a similar error like:


==> Downloading https://formulae.brew.sh/api/formula.jws.json
curl: (28) Failed to connect to formulae.brew.sh port 443 after 300003 ms: Couldn't connect to server

Warning: formula.jws.json: update failed, falling back to cached version.
==> Downloading https://formulae.brew.sh/api/formula_tap_migrations.jws.json
curl: (28) Failed to connect to formulae.brew.sh port 443 after 300016 ms: Couldn't connect to server

Warning: formula_tap_migrations.jws.json: update failed, falling back to cached version.
```

I said "in Brazil" because I talked to some partners from other places in the world and it works there.

I tried to running those commands in 2 different Mac I have at home and both have the same error.

**Comment by arnonrdp** [comment]
UPDATE:
- It works if I use a VPN.

**Comment by Bo98** [comment]
Looks like a wider outage in Brazil: https://github.com/orgs/community/discussions/143145. Someone from GitHub is in that thread asking for information to help debug.

**Comment by corrosive4354** [comment]
If you cannot directly access Homebrew's server in the Brazilian network environment, you can try to use a proxy or VPN to connect.

Seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easy to use than docker and homebrew on Mac.
