### ISSUE TITLE
wakeonlan installs but errors when run with bad interpreter: /usr/bin/perl5.30: no such file or directory

### ISSUE THREAD

**Issue by crhilton** [Homebrew/homebrew-core#196509]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
crhilton@mulan ~ % brew gist-logs wakeonlan
Error: No logs.
crhilton@mulan ~ % brew config
HOMEBREW_VERSION: 4.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 91f3671b16fe62121364c465c14e0dfd088d7ead
Last commit: 7 days ago
Core tap JSON: 03 Nov 12:30 UTC
Core cask tap JSON: 03 Nov 12:30 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.P2I8uHwWez/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.5 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
crhilton@mulan ~ % brew doctor
Your system is ready to brew.
crhilton@mulan ~ %
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Run the wakeonlan command with a mac address to wake up a specific PC on my network.

### What happened (include all command output)?

crhilton@mulan ~ % wakeonlan <redacted mac address>
zsh: /opt/homebrew/bin/wakeonlan: bad interpreter: /usr/bin/perl5.30: no such file or directory

### What did you expect to happen?

I expect it to send that packet out and exit quietly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install wakeonlan
wakeonlan


 -- I don't think you actually need to test that it works, the failure is with the first line of the script referencing a perl version that's no longer the current one (seems to be 5.34)
```

**Comment by carlocab** [comment]
Could you attach the contents of
```
"$(brew --prefix wakeonlan)/INSTALL_RECEIPT.json"
```
here?

**Comment by cho-m** [comment]
One common reason for this is if you upgraded your macOS.

If so, a workaround is to `brew reinstall wakeonlan` as the Perl version is written at install time.

**Comment by carlocab** [comment]
Yes, I was going to suggest that, but I wanted to double-check the `INSTALL_RECEIPT.json` first.

**Comment by crhilton** [comment]
I definitely did install this on a previous macos release.  And brew reinstall wakeonlan fixed it, thanks!  I'll try to remember brew reinstall in the future.

Here is the contents of that file before I ran brew reinstall:

crhilton@mulan ~ % cat $(brew --prefix wakeonlan)/INSTALL_RECEIPT.json
{
  "homebrew_version": "3.3.9-83-g0b14b6d",
  "used_options": [

  ],
  "unused_options": [

  ],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "installed_as_dependency": false,
  "installed_on_request": true,
  "changed_files": [
    "bin/wakeonlan"
  ],
  "time": 1658685237,
  "source_modified_time": 1637548107,
  "compiler": "clang",
  "aliases": [

  ],
  "runtime_dependencies": [

  ],
  "source": {
    "spec": "stable",
    "versions": {
      "stable": "0.42",
      "head": null,
      "version_scheme": 0
    },
    "path": "/opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/wakeonlan.rb",
    "tap_git_head": "b8ed9d4c8a57ad53906c6d18213b6c36652b3e66",
    "tap": "homebrew/core"
  },
  "arch": "arm64",
  "built_on": {
    "os": "Macintosh",
    "os_version": "macOS 12.0",
    "cpu_family": "arm_firestorm_icestorm",
    "xcode": "13.1",
    "clt": "13.1.0.0.1.1633545042",
    "preferred_perl": "5.30"
  }
}%
crhilton@mulan ~ %

**Comment by crhilton** [comment]
Fixed with brew reinstall wakeonlan

**Comment by paddor** [comment]
I had the same problem trying to install the Ruby gem `rbsecp256k1`. It kept failing: 

```
> gem install rbsecp256k1
Building native extensions. This could take a while...
ERROR:  Error installing rbsecp256k1:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.4.0/gems/rbsecp256k1-6.0.0/ext/rbsecp256k1
/usr/local/opt/ruby/bin/ruby extconf.rb
Downloading libsecp256k1.zip
Running 'chmod' for libsecp256k1 0.2.0... OK
Running 'autogen' for libsecp256k1 0.2.0... ERROR. Please review logs to see what happened:
----- contents of '/usr/local/lib/ruby/gems/3.4.0/gems/rbsecp256k1-6.0.0/ext/rbsecp256k1/tmp/x86_64-apple-darwin24.2.0/ports/libsecp256k1/0.2.0/autogen.log' -----
./autogen.sh: /usr/local/bin/autoreconf: /usr/bin/perl5.30: bad interpreter: No such file or directory
----- end of file -----
*** extconf.rb failed ***
```


Since it's `autoreconf` that's unable to find the perl interpreter, I did `brew reinstall autoconf`. After that I was able to install the gem.
