### ISSUE TITLE
Udunits - udunits-2.2.20.tar.gz isn't available

### ISSUE THREAD

**Issue by pedrotildes** [Homebrew/homebrew-core#19672]
The installation of NCO fails because of the installation of a dependency, in this case, UDUNITS.
The cause seems to be in the filename that don't exists: 
==> Installing nco from homebrew/science
==> Installing dependencies for homebrew/science/nco: udunits, homebrew/v
==> Installing homebrew/science/nco dependency: udunits
==> Downloading ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz

curl: (78) RETR response: 550
Error: Failed to download resource "udunits"
Download failed: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz

I went to checkout the FTP site and there isn't a udunits-2.2.20.tar.gz available.
What can I do.
Thanks
Pedro

**Comment by ilovezfs** [comment]
>Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

Please complete the issue template and maybe this will be reopened.

For what it's worth, your brew is very outdated. `nco` is now in homebrew/core not homebrew/science and udunits current version is 2.2.25 not 2.2.20.
