### ISSUE TITLE
Restic 0.4.0 fails to install - Error: Invalid argument @ rb_file_s_rename

### ISSUE THREAD

**Issue by tback** [Homebrew/homebrew-core#19685]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/5198a794ccfae3c72f3befb9b6e08d0d

I was trying to install restic. Then instead of a confirmation message I got this error:
```
brew install restic
==> Downloading https://github.com/restic/restic/archive/v0.4.0.tar.gz
Already downloaded: /Users/tback/Library/Caches/Homebrew/restic-0.4.0.tar.gz
Error: Invalid argument @ rb_file_s_rename - (/private/tmp/restic-20171021-67846-kpjvis/restic-0.4.0/src, /private/tmp/restic-20171021-67846-kpjvis/restic-0.4.0/src/github.com/restic/restic/src)
```

**Comment by ilovezfs** [comment]
`restic` isn't in https://github.com/Homebrew/homebrew-core.

It's in the tap https://github.com/restic/homebrew-restic

However, the current version is 0.7.3 not 0.4.0. So I suggest you

```
brew untap restic/restic
brew install restic/restic/restic
```

**Comment by tback** [comment]
thanks @ilovezfs - that worked.
the broken formula wasn't even an old tap. it was an old attempt of mine to write a formula and that I forget about. Sorry for that.

**Comment by ilovezfs** [comment]
@tback no worries. I'm glad it worked :)
