### ISSUE TITLE
`openssh` hardcodes subsystem path in `sshd_config`; breaks on upgrade

### ISSUE THREAD

**Issue by allenap** [Homebrew/homebrew-core#196817]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.4.4-32-g3ff3ad6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3ff3ad6f6f3ff31116f96f03c866c0e2e971f0e9
Last commit: 31 minutes ago
Core tap JSON: 06 Nov 09:37 UTC
Core cask tap JSON: 06 Nov 09:37 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: hx
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.0 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false

$ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I ran `/opt/homebrew/sbin/sshd -Dd` and used `sftp` to connect from another machine.

### What happened (include all command output)?

On the other machine: `Connection closed`.

On this machine (the one with Homebrew), unfortunately I've lost the logs, but `sshd` said it couldn't find `/opt/homebrew/Cellar/openssh/9.3p1/libexec/sftp-server` when trying to fork the server. Note that it said 9.3, but the current version is 9.9.

I tracked it down to the following line in `/opt/homebrew/etc/ssh/sshd_config`:

```
Subsystem   sftp    /opt/homebrew/Cellar/openssh/9.3p1/libexec/sftp-server
```

Copying over the `sshd_config.default` resolved the issue. This line (and an automatic VCS comment) were the only differences between `sshd_config.default` and `sshd_config`.

### What did you expect to happen?

I expected the `sftp-server` binary on this machine to be forked.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openssh
# Wait some time for `openssh` formula to be updated.
brew update && brew upgrade
/opt/homebrew/sbin/sshd -Dd &
# Connect with `sftp`.
```

**Comment by carlocab** [comment]
Should be fixed by #196818. The fix only applies to new installs, though. Homebrew doesn't overwrite files in `etc` (to avoid clobbering any customisation users have made).
