### ISSUE TITLE
llvm --HEAD should be @20

### ISSUE THREAD

**Issue by FabioFracassi** [Homebrew/homebrew-core#196905]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew doctor
Your system is ready to brew.

brew config
HOMEBREW_VERSION: 4.4.4-41-g451c3a8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 451c3a8735eb9b3050e40802a771eddf7c23e568
Last commit: 8 hours ago
Core tap HEAD: 18d1256005fe2919416cc21b14197e851b050835
Core tap last commit: 22 minutes ago
Core tap JSON: 06 Nov 22:28 UTC
Core cask tap HEAD: fc825e5702a5ee354e2c8b4f4ac36aac9f552419
Core cask tap last commit: 8 minutes ago
Core cask tap JSON: 06 Nov 22:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.6.0 => /usr/bin/curl
macOS: 14.5-arm64
CLT: 16.0.0.0.1.1724870825
Xcode: 16.1
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Install llvm@19 alongside llvm --HEAD (which resolves to llvm/clang --version 20.x.x)

I already have llvm --HEAD and llvm@18 installed

### What happened (include all command output)?

`brew install llvm@19`

```
==> Downloading https://formulae.brew.sh/api/formula.jws.json

==> Downloading https://formulae.brew.sh/api/cask.jws.json

Warning: llvm 19.1.3 is already installed and up-to-date.
To reinstall 19.1.3, run:
  brew reinstall llvm
```

### What did you expect to happen?

Not exactly expect, but I would wish that it installed in the same way llvm@18 did

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- `brew install llvm --HEAD`  (works, takes a while -> build from source as expected
                               llvm/bin/clang --version returns 20.x.x
                              )
- `brew install llvm@18`      (works, as expected llvm@18/bin/clang --version returns 18.x.x.)
- `brew install llvm@19`      (warning already installed)
- `brew reinstall llvm@19`    (works, as expected llvm@19/bin/clang --version returns 19.x.x.
                               but llvm/bin/clang --version returns 19.x.x now as well
                              )
```

**Comment by FabioFracassi** [comment]
By now it should be `llvm@21`  since llvm's main branch is on version 21. (i.e. after installing `brew install llvm --HEAD` running `clang++ --version` results in `Homebrew clang version 21.0.0git`)

**Comment by EricFromCanada** [comment]
This is happening because `llvm@18` is a separate [versioned formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/l/llvm%4018.rb), while `llvm@19` is [currently an alias](https://github.com/Homebrew/homebrew-core/blob/master/Aliases/llvm%4019) for the `llvm` formula, and you can't have both the release and HEAD versions of a formula installed and linked at the same time. Once LLVM v20 is the current release version, `llvm@19` will (probably) become its own separate formula.

**Comment by FabioFracassi** [comment]
> and you can't have both the release and HEAD versions of a formula installed and linked at the same time.

That is exactly the problem. It should be possible.  I do not know how hombrew should handle versioned formulas or aliases, but the outcome needs to be that I can install latest release and --HEAD side by side.
 
This would also match the llvm versioning scheme, since all installed tools have different version numbers depending how you install them, i.e.:

`brew install llvm && clang++ --version`                  =>  `Homebrew clang version 20.x.y`
`brew install llvm --HEAD && clang++ --version`    =>  `Homebrew clang version 21.0.0git`

**Comment by SMillerDev** [comment]
> That is exactly the problem. It should be possible. I do not know how hombrew should handle versioned formulas or aliases, but the outcome needs to be that I can install latest release and --HEAD side by side.

HEAD builds are unsupported in Homebrew and are only for upstream testing. If you want to package the unstable version of LLVM, you can do so in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by FabioFracassi** [comment]
Fair enough I suppose. 
I still think the behaviour I propose is more useful - for all users of homebrew. It would not make head any more supported, just easier to test and revert

**Comment by SMillerDev** [comment]
I think anything that makes an unsupported configuration easier and more likely to be used implicitly makes it more supported.

If you make a pull request to implement this, it might turn out I'm the only maintainer who feels this way. So if you want this I'd recommend making a pull request all the same.
