### ISSUE TITLE
For consideration: homebrew-android formulas

### ISSUE THREAD

**Issue by toonetown** [Homebrew/homebrew-core#1969]
I would like to submit for consideration the repository at https://github.com/toonetown/homebrew-android as a substitute for the formulas in the core homebrew.  These formulas are generated (and I keep them updated) based off of the official google `repo.xml` files - and allow for installing the additional android packages (such as the SDK, build-tools, m2repositories, NDK, etc).

I understand, however, if these are not of sufficient quality to replace the ones in homebred-core...I merely submit them here for discussion/consideration.

If desired, I am fine transferring the repository to the Homebrew github organization as well.  Or I am also OK with maintaining it as a separate project.

**Comment by toonetown** [comment]
As a note, I attempt to maintain these formulas so that they are updated regularly...and they should "work" with AndroidStudio and be seamless with the android SDK manager (i.e. you can still use the SDK manager to install packages - but any packages installed using the formulas will also show up as "installed" in SDK manager as well)

**Comment by ilovezfs** [comment]
What do you see as the benefit here given that moving formulae out of core reduces their overall exposure? Of course, I'm all for it as an iOS fanboi. :smirk:

**Comment by toonetown** [comment]
> @ilovezfs
> What do you see as the benefit here given that moving formulae out of core reduces their overall exposure?

Good point - maybe it doesn't make sense.  Maybe the current state is the best...sdk/ndk are in the main repository (though I'd argue that android-platform-tools should probably be installed via the SDK manager...rather than as a formula).  That way, the "core" android formulas would be those that are not otherwise installable via the SDK manager.  For people who want to manage their android SDK install via homebrew (which is probably just me), then another repository could be tapped and pinned.

I'll close this.
