### ISSUE TITLE
compcert fails to build because coq is too new

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-core#19710]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The `compcert` formula fails to build because the `coq` version is too new for it. Here is the error message at build time:
```
==> ./configure -prefix /usr/local/Cellar/compcert/3.1 ia32-macosx
Testing assembler support for CFI directives... yes
Testing Coq... version 8.7.0 -- UNSUPPORTED
Error: CompCert requires Coq version 8.6.
Testing OCaml... version 4.05.0 -- good!
Testing OCaml .opt compilers... yes
Testing Menhir... version 20171013 -- good!
Testing GNU make... version 3.81 (command 'make') -- good!
One or several required tools are missing or too old.  Aborting.
```

I am just opening this issue to synchronise our effort to get this fixed. There seem to be a fix, and I already contacted upstream here, to ask if they could make a new release: https://github.com/AbsInt/CompCert/commit/c96c50577569c6077c42e756bbf12d31d9c82717#comments

Once the release is done or once we have a bunch of patches, I'll open a pull request to get this fixed in homebrew-core.

Issue on Linuxbrew, for reference:
https://github.com/Linuxbrew/homebrew-core/pull/4764

**Comment by ilovezfs** [comment]
@iMichka https://github.com/Homebrew/homebrew-core/pull/19742
