### ISSUE TITLE
brew install openssl failed with syntax error

### ISSUE THREAD

**Issue by mioyingluffy** [Homebrew/homebrew-core#19744]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

> brew gist-logs has the same error output

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config:

> HOMEBREW_VERSION: 1.3.3
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 05bb3532fc3f0d723a8e8af1605c3f8080051e78
> Last commit: 5 weeks ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: e7c562d3d0d3bd4ef09445c5627bf8000b760525
> Core tap last commit: 46 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: octa-core 64-bit haswell
> Homebrew Ruby: 2.0.0-p648
> Clang: 9.0 build 900
> Git: 2.11.0 => /usr/local/bin/git
> Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
> Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
> Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
> Java: 1.8.0_112
> macOS: 10.12.6-x86_64
> Xcode: N/A
> CLT: 9.0.0.0.1.1504363082
> X11: N/A

brew doctor:

> Your system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why)
I try to brew upgrade, then it failed with error with openssl.  Then I try to install openssl. Get the same error message.

- What happened (include command output)]
brew install openssl, then it will have this problem

> Error: openssl: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:103: syntax error, unexpected <<
>   def caveats; <<~EOS
>                  ^
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:105: syntax error, unexpected keyword_in, expecting ')'
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:106: syntax error, unexpected ')', expecting keyword_end
>     the System keychain), place .pem files in
>                         ^
> /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:106: syntax error, unexpected keyword_in, expecting keyword_end

- What you expected to happen
pass the install openssl step.

- Step-by-step reproduction instructions (by running `brew install` commands)
just brew install openssl

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
What is the output of
```
brew update -f
brew config
```

**Comment by ilovezfs** [comment]
To be explicit: your Homebrew is terribly outdated. The current version is 1.3.6 (https://github.com/Homebrew/brew/releases/latest) not 1.3.3.

I'm closing this out as it's not actually a formula specific issue.
