### ISSUE TITLE
mongodb-atlas-cli 1.31.0 is not being published on homebrew

### ISSUE THREAD

**Issue by fmenezes** [Homebrew/homebrew-core#197725]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
# brew config
HOMEBREW_VERSION: 4.4.5-25-g2fb6bf0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fb6bf05fbf0984fe7a6ab1476537d657a9fab01
Last commit: 24 hours ago
Core tap HEAD: a4e6049197817cf75b9aa88e7a5da0d6af4d1dd9
Core tap last commit: 7 hours ago
Core tap JSON: 14 Nov 10:42 UTC
Core cask tap JSON: 14 Nov 10:42 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false

# brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was expecting `mongodb-atlas-cli` formula to auto-update as always.

Latest version was properly auto updated at https://github.com/Homebrew/homebrew-core/pull/194731

### What happened (include all command output)?

Unfortunately, the latest version did not update (mongodb-atlas-cli 1.31.0).

according to https://github.com/Homebrew/homebrew-core/actions/runs/11820321744/job/32932347742#step:6:11832 there is a duplicate PR (https://github.com/Homebrew/homebrew-core/pull/139259) from over a year ago (it was a buggy PR though).

### What did you expect to happen?

mongodb-atlas-cli to update to 1.31.0

### Step-by-step reproduction instructions (by running `brew` commands)

Command:

```shell
brew bump mongodb-atlas-cli
```

Output:
```
==> mongodb-atlas-cli
Formula is autobumped so will have bump PRs opened by BrewTestBot every ~3 hours.
```

Command:
```shell
brew bump-formula-pr mongodb-atlas-cli
```
Output:
```
Error: Whoops, the mongodb-atlas-cli formula has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that's not in the autobump list:
  https://github.com/Homebrew/homebrew-core/blob/master/.github/autobump.txt
```

**Comment by daeho-ro** [comment]
Manually opened a PR and now it is fixed.
