### ISSUE TITLE
brew link ruby -- dir_s_mkdir permission denied

### ISSUE THREAD

**Issue by dezza** [Homebrew/homebrew-core#19789]
- [x] Ran `brew update` and retried your prior step? Yes
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? Yes
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? No
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? # brew doctor is empty
```
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f5882150c3c5af3376a63daea5ca1d7883ce6aef
Core tap last commit: 21 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

To help us debug your issue please explain:
- What you were trying to do (and why)
My Vim ruby linking was suddenly broke then I attempted to reinstall vim and upgrade ruby meanwhile to relink the shared libraries. I got consistent permission errors on every subdir in:
/usr/local/lib/ruby/gems/2.4.0/doc/rubygems-2.6.14

- What happened (include command output)
Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.4.0/doc/rubygems-2.6.14/ri/Gem

- What you expected to happen
Find out what weird permissions macos could have set before or after an upgrade. I recently upgraded from Sierra to High Sierra that could be it.

- Step-by-step reproduction instructions (by running `brew install` commands)
Upgrade from sierra to high sierra and try reinstalling vim and brew link ruby

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
```
find /usr/local -not -uid $(id -u)
```

**Comment by dezza** [comment]
@ilovezfs 
> find /usr/local -not -uid $(id -u)
You mean change permission on all that does not correspond to your user under /usr/local ?

I can tell from poking the dir they are all more or less `root:admin`

I fixed it myself temporarily by "chmod g+w -R /usr/local/lib/ruby/gems/2.4.0/doc/rubygems-2.6.14/ri/Gem" and since I am in doubt as to whether this is intended I open this issue.

I guess "admin" is the normal MacOS administrator group so it should be OK? But what is your recommended permissions? What permissions does homebrew usually put files under? Asking because I just got a mac again and I would really value that information to get comfortable with homebrew quickly again.

**Comment by ilovezfs** [comment]
>they are all more or less root:admin

Do you know the full set of files that ended up owned by root?

>But what is your recommended permissions? What permissions does homebrew usually put files under?

$(whomai):admin ownership, 755 for most directories, 644 for most files. This is not something you typically need to manage manually in any way.

The working theory is that the macOS Installer switched some thing to root ownership on you, but I have no idea why it happened or what subset of files were affected.

**Comment by olimorris** [comment]
@dezza I had the same problem earlier trying to install vim with lua support. To get it to work I switched to Ruby 2.0 and ran my brew command and it worked perfectly.

If you have rbenv then it should be a breeze.

**Comment by ilovezfs** [comment]
Basically it's not possible for Homebrew to change their ownership to, or from, root, since that requires `sudo`.

**Comment by dezza** [comment]
This was stock ruby. No version manager.
