### ISSUE TITLE
Upgrading harfbuzz and atk Error

### ISSUE THREAD

**Issue by nasyxx** [Homebrew/homebrew-core#19799]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

---
I just tried this:

`brew upgrade`

Then, harfbuzz and atk upgrade failed.

The Error is "distutils.errors.CompileError: command 'clang' terminated by signal 11"

Here is the gist-logs 
harfbuzz https://gist.github.com/nasyxx/38edbbcf0d9c5319f49037e1e28e8814
atk https://gist.github.com/nasyxx/58c7eb337fe82fde4b60b864a2b3e2aa

**Comment by s172262** [comment]
Both stopped at `g-ir-scanner`. Did you build `gobject-introspection` yourself?

**Comment by nasyxx** [comment]
Nope, I install gobject-introspection from homebrew.
At the time of installation, python will terminate unexpectedly

**Comment by ilovezfs** [comment]
Please re-test now that harfbuzz 1.6.3 has shipped. brew update && brew upgrade

**Comment by nasyxx** [comment]
@ilovezfs I have tried it, but still failed

**Comment by ilovezfs** [comment]
>Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.

Can you unset `HOMEBREW_BUILD_FROM_SOURCE` please? Then
```
brew reinstall python $(brew deps --include-build harfbuzz)
```

**Comment by nasyxx** [comment]
Thank you @ilovezfs ,  success upgrade it

**Comment by ilovezfs** [comment]
@nasyxx you're welcome!
