### ISSUE TITLE
The Homebrew give an error for macOS Monterey 12.7.6 new version 

### ISSUE THREAD

**Issue by krisailu** [Homebrew/homebrew-core#197990]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Warning: You are using macOS 12.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

mongoDB is not installing properly on my mac 12.7.6 . it is new version of 12.6.0

### What happened (include all command output)?

MacOS Monterery 12 is not supported that is older version for brew mongodb community and brew formulas are not installed

### What did you expect to happen?

Mongodb should be installed properly and work it fine

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
yew
```

**Comment by SMillerDev** [comment]
In addition to the obvious message in `brew doctor` that's telling you not to make issues here, mongodb is also not open source so it is not in Homebrew/core.
