### ISSUE TITLE
Allow `openjdk@8` Installation on Apple Silicon Macs Using Rosetta 2

### ISSUE THREAD

**Issue by squigglyjuicebox** [Homebrew/homebrew-core#198087]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config                                                                        
HOMEBREW_VERSION: 4.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cc0b5d6d05d1f3af5b2f53e9fbb1e7bfa0c332ab
Last commit: 27 hours ago
Core tap JSON: 18 Nov 13:22 UTC
Core cask tap JSON: 18 Nov 13:22 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_blizzard_avalanche
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false
```

```
❯ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to install `openjdk@8` on an Apple Silicon Mac. While I understand that it is an x86_64-only formula, other x86_64-only formulae like `temurin@8` install successfully with a note about requiring Rosetta 2. I was hoping `openjdk@8` would behave similarly, as Rosetta 2 enables running x86_64 binaries on Apple Silicon.

### What happened (include all command output)?

The installation failed with the following error:

```
openjdk@8: The x86_64 architecture is required for this software.
Error: openjdk@8: An unsatisfied requirement failed this build.
```

In contrast, installing `temurin@8` produces a caveat about requiring Rosetta 2, but the installation succeeds:

```
==> Caveats
temurin@8 is built for Intel macOS and so requires Rosetta 2 to be installed.
You can install Rosetta 2 with:
  softwareupdate --install-rosetta --agree-to-license
Note that it is very difficult to remove Rosetta 2 once it is installed.
```

### What did you expect to happen?

I expected `openjdk@8` to install with a caveat similar to `temurin@8`, allowing it to work on Apple Silicon Macs via Rosetta 2.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openjdk@8 # on an Apple Silicon Mac
```

**Comment by SMillerDev** [comment]
It doesn't build on Apple Silicon, there is nothing Homebrew can do to resolve this.

**Comment by squigglyjuicebox** [comment]
Thank you for the response. I understand that openjdk@8 doesn’t build natively on Apple Silicon. However, my request is not about native support but about allowing the installation of the x86_64 version of openjdk@8 to run through Rosetta 2. As far as I understand, this wouldn’t require it to be *built* on Apple Silicon.

Apologies if I’m misunderstanding how Homebrew’s build system or formula requirements work in this case.

**Comment by SMillerDev** [comment]
You can install an x86 Homebrew using Rosetta, that will allow you to install any x86 formula. An ARM native install will not allow you to install x86 formula since it would not be compatible with the other native software.

**Comment by squigglyjuicebox** [comment]
Thank you for clarifying. I’ll install an x86 Homebrew through Rosetta as suggested. I now realize that temurin@8 is a cask, while openjdk@8 is a formula, which explains the difference in behavior.
