### ISSUE TITLE
failing brew install --with-toolchain llvm

### ISSUE THREAD

**Issue by zkurtz** [Homebrew/homebrew-core#19808]
I tried `brew install --with-toolchain llvm` as [suggested here](https://bitbucket.org/rpy2/rpy2/issues/403/cannot-pip-install-rpy2-with-latest-r-340) to possibly enable installation of `rpy2`.  This failed as

```
==> cmake -G Unix Makefiles /private/tmp/llvm-20171024-26404-1g1alft/llvm-5.0.0.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE
Last 15 lines from /Users/me/Library/Logs/Homebrew/llvm/01.cmake:
  command.


CMake Warning at tools/xcode-toolchain/CMakeLists.txt:60 (message):
  Failed to detect the version of an installed copy of Xcode, falling back to
  highest supported version.  Set XCODE_VERSION to override.


CMake Error at tools/xcode-toolchain/CMakeLists.txt:80 (message):
  Could not identify toolchain dir


-- Configuring incomplete, errors occurred!
See also "/tmp/llvm-20171024-26404-d4s3ul/CMakeFiles/CMakeOutput.log".
See also "/tmp/llvm-20171024-26404-d4s3ul/CMakeFiles/CMakeError.log".

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
faust. v2.1.0 (new formula) https://github.com/Homebrew/homebrew-core/pull/16724
gdb: Automatic code signing https://github.com/Homebrew/homebrew-core/pull/19421
cling 0.4 (new formula) https://github.com/Homebrew/homebrew-core/pull/18124
infer 0.13.0 https://github.com/Homebrew/homebrew-core/pull/19646
pypy crashes with dyld: lazy symbol binding failed: Symbol not found: _clock_gettime https://github.com/Homebrew/homebrew-core/issues/6949
```

gist-logs:  https://gist.github.com/anonymous/9b3639190902987fdc97ff0ede066859

**Comment by ilovezfs** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

You've not filled out the issue template, which includes

>Ran brew doctor, fixed all issues and retried your prior step?

You have a whole pile of doctor errors so I'm assuming this is caused by one of them.

**Comment by zkurtz** [comment]
Thanks for pointing me in the right direction.  I'm confused on how to interpret the doctor output, since it begins "Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue", and nothing is explicitly marked as "error".  I'll try cleaning up and resubmitting a warnings-free output.

**Comment by ilovezfs** [comment]
For what it's worth:
```
==> Summary
🍺  /usr/local/Cellar/llvm/5.0.0: 4,890 files, 2.3GB, built in 20 minutes 33 seconds
iMac-TMP:~ joe$ cat /usr/local/Cellar/llvm/5.0.0/INSTALL_RECEIPT.json 
{"homebrew_version":"1.3.6-117-g079689d","used_options":["--with-toolchain"],"unused_options":["--without-compiler-rt","--without-libcxx","--with-lldb","--with-python","--with-shared-libs","--without-libffi","--with-graphviz","--with-ocaml"],"built_as_bottle":false,"poured_from_bottle":false,"installed_as_dependency":false,"installed_on_request":true,"changed_files":null,"time":1509031115,"source_modified_time":1504283332,"HEAD":"079689d53c565f43a56956d557e20d64cc29a7c7","stdlib":"libcxx","compiler":"clang","aliases":["llvm@5"],"runtime_dependencies":[{"full_name":"libffi","version":"3.2.1"}],"source":{"path":"/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb","tap":"homebrew/core","spec":"stable","versions":{"stable":"5.0.0","devel":null,"head":"HEAD","version_scheme":0}}}iMac-TMP:~ joe$ 
```

**Comment by zkurtz** [comment]
I completely uninstalled and re-installed brew, but the error persisted.  Looking at the content of the message, "Failed to detect the version of an installed copy of Xcode", I noticed [here](https://github.com/Homebrew/homebrew-core/issues/4564) a suggestion to do `xcode-select -s /Applications/Xcode.app`. This evidently fixed the problem.  So did I do something wrong with my xcode installation, or should this brew formula be updated to handle my situation?

**Comment by ilovezfs** [comment]
Well at this point we have no idea what your xcode-select was previously pointing to so there's not much more to be learned here.
