### ISSUE TITLE
'brew install nifi' ignoring pre-downloaded (sha256-matching) tar.gz

### ISSUE THREAD

**Issue by jrittenh** [Homebrew/homebrew-core#19801]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

    Error: No logs.

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config:

    HOMEBREW_VERSION: 1.3.6-107-g8be34a9
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 8be34a98f8f88e0ea304429b10350ebb64d06652
    Last commit: 78 minutes ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 1d1f4b48e2b1b519f48e8217ddf32d838095735e
    Core tap last commit: 4 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local/Homebrew
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: octa-core 64-bit skylake
    Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
    Clang: 9.0 build 900
    Git: 2.14.3 => /usr/local/bin/git
    Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
    Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
    Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
    Java: 1.8.0_144, 1.8.0_121
    macOS: 10.12.6-x86_64
    Xcode: 8.3.2
    CLT: 9.0.1.0.1.1506734476
    X11: 2.7.11 => /opt/X11

brew doctor:

    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: The filesystem on / appears to be case-sensitive.
    The default macOS filesystem is case-insensitive. Please report any apparent problems.

    Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

    Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
      /usr/local/lib/libpainter.0.dylib
      /usr/local/lib/librfxencode.0.dylib

    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected header files:
      /usr/local/include/painter.h
      /usr/local/include/rfxcodec_common.h
      /usr/local/include/rfxcodec_decode.h
      /usr/local/include/rfxcodec_encode.h
      /usr/local/include/xrdp_client_info.h
      /usr/local/include/xrdp_constants.h
      /usr/local/include/xrdp_rail.h
      /usr/local/include/xrdp_sockets.h

    Warning: Unbrewed .la files were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected .la files:
      /usr/local/lib/libpainter.la
      /usr/local/lib/librfxencode.la

    Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected .pc files:
      /usr/local/lib/pkgconfig/libpainter.pc
      /usr/local/lib/pkgconfig/rfxcodec.pc
      /usr/local/lib/pkgconfig/xrdp.pc

    Warning: Unbrewed static libraries were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected static libraries:
      /usr/local/lib/libpainter.a
      /usr/local/lib/librfxencode.a

    Warning: Some directories in your path end in a slash.
    Directories in your path should not end in a slash. This can break other
    doctor checks. The following directories should be edited:
      /usr/local/Cellar/openssl@1.1/1.1.0f/include/openssl/

    Warning: Your Xcode (8.3.2) is outdated.
    Please update to Xcode 9.0.1 (or delete it).
    Xcode can be updated from the App Store.

    Warning: Some keg-only formula are linked into the Cellar.
    Linking a keg-only formula, such as gettext, into the cellar with
    `brew link <formula>` will cause other formulae to detect them during
    the `./configure` step. This may cause problems when compiling those
    other formulae.

    Binaries provided by keg-only formulae may override system binaries
    with other strange results.

    You may wish to `brew unlink` these brews:
      gettext

To help us debug your issue please explain:
- What you were trying to do (and why)

brew install nifi via a pre-downloaded tar.gz file, because the mirror selector was picking insanely slow mirrors.

notes:

brew edit nifi shows sha256 to be "d67c90deb50ed5fee44e7ebf61fbf870f2e97cf1c82ad0f598ff5c4ef905ce99"

    prompt $ sha256sum Library/Caches/Homebrew/nifi-1.4.0-bin.tar.gz
    d67c90deb50ed5fee44e7ebf61fbf870f2e97cf1c82ad0f598ff5c4ef905ce99  Library/Caches/Homebrew/nifi-1.4.0-bin.tar.gz

- What happened (include command output)

    prompt $ brew install -d nifi
    /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nifi.rb
    /usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/nifi.rb
    ==> Downloading https://www.apache.org/dyn/closer.cgi?path=/nifi/1.4.0/nifi-1.4.0-bin.tar.gz
    ==> Best Mirror http://mirror.cc.columbia.edu/pub/software/apache/nifi/1.4.0/nifi-1.4.0-bin.tar.gz
    #########                                                                 12.5%

- What you expected to happen

    prompt $ brew install nifi
    ==> Downloading https://www.apache.org/dyn/closer.cgi?path=/nifi/1.4.0/nifi-1.4.0-bin.tar.gz
    Already downloaded: /Users/<username>/Library/Caches/Homebrew/nifi-1.4.0-bin.tar.gz

- Step-by-step reproduction instructions (by running `brew install` commands)

    brew install nifi

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
The file name should be nifi-1.4.0.tar.gz.
