### ISSUE TITLE
nginx 1.12.2 Upgrading Possibly Causing 403 Forbidden errors

### ISSUE THREAD

**Issue by daBee** [Homebrew/homebrew-core#19810]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Upon upgrading/updating homebrew, on two machines, they tripped on something and nginx is now throwing localhost virtual hosts 403 Forbidden errors without any config file changes, locations, permissions, etc.  

- What happened (include command output)

nginx started serving 403 Forbidden errors on virtual hosts.  Updating nginx was something I wanted to do to make sure I wasn't expired in any way.  Upon upgrading/updating nginx, I tripped over ssl dependency issues, and I think this is causing the 403's.  

```
Firefly:~ rich$ brew upgrade
==> Upgrading 1 outdated package, with result:
nginx 1.12.2
==> Not upgrading 1 pinned package:
postgresql 10.0
Error: nginx contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree nginx`.
Firefly:~ rich$ brew update
Already up-to-date.
Firefly:~ rich$ brew doctor
Your system is ready to brew.
Firefly:~ rich$ brew install nginx
Updating Homebrew...
Error: nginx 1.12.0 is already installed
To upgrade to 1.12.2, run `brew upgrade nginx`
Firefly:~ rich$ brew upgrade nginx
==> Upgrading 1 outdated package, with result:
nginx 1.12.2
Error: nginx contains conflicting version recursive dependencies:
  openssl, openssl@1.1
View these with `brew deps --tree nginx`.
Firefly:~ rich$ brew doctor
Your system is ready to brew.
Firefly:~ rich$ brew gist-logs nginx
Error: No logs.
Firefly:~ rich$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3e1fd48c5b86e90fc758cda5908b284d955b1737
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.6.4 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/rich/.rbenv/shims/ruby => /Users/rich/.rbenv/versions/2.4.1/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: 9.0.1
CLT: N/A
X11: 2.7.9 => /opt/X11
Firefly:~ rich$ brew doctor
Your system is ready to brew.
Firefly:~ rich$
```

- What you expected to happen

I expected nginx to update properly.  It's currently showing the 403 Forbidden errors with 1.12.0, so nginx has not been upgraded.  I'm thinking this trip over the openssl versions is confusing nginx as it isn't seeing anything, replicable on two machines.  

- Step-by-step reproduction instructions (by running `brew install` commands)

As above:  

    Firefly:~ rich$ brew install nginx 
    Updating Homebrew... 
    Error: nginx 1.12.0 is already installed 
    To upgrade to 1.12.2, run `brew upgrade nginx` 
    Firefly:~ rich$ brew upgrade nginx 
    ==> Upgrading 1 outdated package, with result: 
    nginx 1.12.2 
    Error: nginx contains conflicting version recursive dependencies: 
      openssl, openssl@1.1 
    View these with `brew deps --tree nginx`. 
    Firefly:~ rich$ brew doctor 
    Your system is ready to brew. 

Upon further investigation, on chasing this: 

    Error: nginx contains conflicting version recursive dependencies:
    openssl, openssl@1.1

The latter has recursive dependencies:

    Firefly:~ rich$ brew deps --tree openssl@1.1
    openssl@1.1

**Comment by daBee** [comment]
Tried uninstalling `nginx` and reinstalling with `debug` and `passenger`.

    Firefly:~ rich$ brew install nginx --with-passenger --with-debug
    ==> Downloading https://nginx.org/download/nginx-1.12.2.tar.gz
    ######################################################################## 100.0%
    ==> ./configure --prefix=/usr/local/Cellar/nginx/1.12.2 --with-http_ssl_module --with-pcre --sbin-path=/usr/local/Cellar/nginx/1.12.2/bin/nginx --with-cc-opt=-I/usr/loca
    
    ==> make install
    ==> Caveats
    Docroot is: /usr/local/var/www
    
    The default port has been set in /usr/local/etc/nginx/nginx.conf to 8080 so that
    nginx can run without sudo.
    
    nginx will load all files in /usr/local/etc/nginx/servers/.
    
    To activate Phusion Passenger, add this to /usr/local/etc/nginx/nginx.conf, inside the 'http' context:
      passenger_root /usr/local/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
      passenger_ruby /usr/bin/ruby;
    
    To have launchd start nginx now and restart at login:
      brew services start nginx
    Or, if you don't want/need a background service you can just run:
      nginx
    ==> Summary
    🍺  /usr/local/Cellar/nginx/1.12.2: 8 files, 3.8MB, built in 1 minute 18 seconds
    Firefly:~ rich$ nginx -t
    nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
    nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
    Firefly:~ rich$ curl ltf.local:8080
    <html>
    <head><title>403 Forbidden</title></head>
    <body bgcolor="white">
    <center><h1>403 Forbidden</h1></center>
    <hr><center>nginx/1.12.0</center>
    </body>
    </html>
    Firefly:~ rich$ nginx -v
    nginx version: nginx/1.12.2

So it's reporting version `1.12.0` after installing `1.12.2`.  None of this is making sense.

**Comment by ilovezfs** [comment]
This should now be fixed.
