### ISSUE TITLE
brew install memcached throwing errors 

### ISSUE THREAD

**Issue by Colette-Pitamba** [Homebrew/homebrew-core#19851]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Decided to uninstall and reinstall memcached after noticing issues with my server due to memcached not running/missing. Ran `brew uninstall memcached` which uninstalled the program, then ran `brew install memcached` which outputs this error:

```
Error: memcached: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:35: syntax error, unexpected <<
  def plist; <<~EOS
               ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:36: syntax error, unexpected '<', expecting keyword_end
    <?xml version="1.0" encoding="UTF-8"?>
     ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:36: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    <?xml version="1.0" encoding="UTF-8"?>
                                ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:36: syntax error, unexpected '>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:38: syntax error, unexpected '<'
    <plist version="1.0">
     ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:39: syntax error, unexpected '<'
    <dict>
     ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:41: unknown regexp options - trg
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:42: syntax error, unexpected '<'
      <key>KeepAlive</key>
       ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:44: syntax error, unexpected '<'
      <key>ProgramArguments</key>
       ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:46: unknown regexp options - cachd
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:47: unknown regexp options - trg
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:48: syntax error, unexpected '<'
        <string>localhost</string>
         ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:49: unknown regexp options - array
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:50: syntax error, unexpected '<'
      <key>RunAtLoad</key>
       ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:52: syntax error, unexpected '<'
      <key>WorkingDirectory</key>
       ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:53: unknown regexp options - trg
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:54: syntax error, unexpected '<'
    </dict>
     ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/memcached.rb:55: unknown regexp options - plt
```
Not sure why these errors are present as my memcached.rb matches the latest rb file on master. Anyone has thoughts on this? I would expect `brew install memcached` to install memcached on my machine.

**Comment by ilovezfs** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Your Homebrew is outdated. `brew update`

**Comment by Colette-Pitamba** [comment]
Tried homebrew upgrade and update which didn't resolve the issue. I had to resolve by uninstalling and reinstalling homebrew.
