### ISSUE TITLE
corepack now needs to re-enable every time upgrades node formula

### ISSUE THREAD

**Issue by rinsuki** [Homebrew/homebrew-core#198728]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
~ $ brew config
HOMEBREW_VERSION: 4.4.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: cc0b5d6d05d1f3af5b2f53e9fbb1e7bfa0c332ab
Last commit: 6 days ago
Core tap JSON: 23 Nov 08:59 UTC
Core cask tap JSON: 23 Nov 08:59 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 16.1
Rosetta 2: false

~ $ brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

* Install `node`
* Run `corepack enable`
* (wait until next node update)
* `brew upgrade`

### What happened (include all command output)?

after upgrade, `/opt/homebrew/bin/pnpm` will not work, since symblic link is depending to specific node version.

```
$ /opt/homebrew/bin/pnpm
zsh: no such file or directory: /opt/homebrew/bin/pnpm

$ ls -l /opt/homebrew/bin/pnpm
lrwxr-xr-x@ 1 user  admin  62 11 23 18:16 /opt/homebrew/bin/pnpm -> ../Cellar/node/23.2.0_1/lib/node_modules/corepack/dist/pnpm.js
```

### What did you expect to happen?

binary created by `corepack enable` (e.g. `yarn`, `pnpm`, ...) should still work after upgrades node formula.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall pnpm; brew uninstall node
# Install node@23.2.0_1 for upgrade
curl -LO https://github.com/Homebrew/homebrew-core/raw/a6cd670526b0b1b7abe7e2610fb55536ea712280/Formula/n/node.rb
brew install ./node.rb
corepack enable
brew upgrade
# Current node version is 23.3.0
pnpm version
# ... not working
```

**Comment by SMillerDev** [comment]
What creates those symlinks?

**Comment by SMillerDev** [comment]
Then the corepack/node developers should probably fix that. All homebrew does is `--enable-corepack` when building node

**Comment by rinsuki** [comment]
But I think it is hard to tell corepack to use a permanent (symlink) path like /opt/homebrew/opt/node/... instead of real path `/opt/homebrew/Cellar/node/<version>/...`, without specific hack (in corepack) for Homebrew.

I think most good choice for corepack user is (re)split corepack formula from node and enables every binary in install phase.

(sorry for suddenly ping, but @ovflowd might be want to know this issue because of #193982 )

**Comment by ovflowd** [comment]
> Then the corepack/node developers should probably fix that. All homebrew does is `--enable-corepack` when building node

That only tells Node to bundle the corepack binary, but not enable corepack.

There isn't currently an environment variable to tell if corepack should be enabled, the corepack enable command must be executed.

Note that "corepack enable" is more about enabling corepack for X package managers (if no argument provided it does for all of them)

I do think it is a command you should run on every upgrade, as corepack also does certain checks regarding versioning of package managers.

**Comment by ovflowd** [comment]
And yes, I agree that this isn't a Homebrew bug. Please report an issue on nodejs/node, I believe what you want is permanent corepack enablement even if Node.js version switches (i.e by some sort of .dotfile on home/profile folders idk)

**Comment by tofrankie** [comment]
I've encountered this problem as well. Every time I upgrade Node, I have to manually `corepack enable`.

**Comment by carlocab** [comment]
@tofrankie this issue is two years old. If you're having an issue with node/corepack, please open a new issue.
