### ISSUE TITLE
ModuleNotFoundError: No module named 'Schedule"

### ISSUE THREAD

**Issue by Cerberus1810** [Homebrew/homebrew-core#198994]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
schedule missing from python3 pip
pip3 unable to install or upgrade using python3 -m pip install --upgrade pip
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

writing python script

### What happened (include all command output)?

module 'schedule' missing

### What did you expect to happen?

download missing module and compile code

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install schedule
brew reinstall python3
brew install pip3
brew install pipx
python3 -m pip install --upgrade pip
```

**Comment by branchvincent** [comment]
Let us know if you have any other questions
