### ISSUE TITLE
Kotlin error on version check

### ISSUE THREAD

**Issue by jrwiegand** [Homebrew/homebrew-core#19896]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/ce48ebaa4d58c2d709d92967c1ba3753
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
 Just checking on the Kotlin version.
- What happened (include command output)
```
$ kotlin -version
error: no build.txt was found at home=/usr/local/Cellar/kotlin/1.1.51/libexec
```
- What you expected to happen
It should show the version of kotlin installed by homebrew
- Step-by-step reproduction instructions (by running `brew install` commands)
```
# josh
$ brew install kotlin
==> Downloading https://github.com/JetBrains/kotlin/releases/download/v1.1.51/kotlin-compiler-1.1.51.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/3432266/c25af51a-a521-11e7-8361-ad437a489823?
######################################################################## 100.0%
🍺  /usr/local/Cellar/kotlin/1.1.51: 48 files, 36.1MB, built in 21 seconds

# josh
$ kotlin -version
error: no build.txt was found at home=/usr/local/Cellar/kotlin/1.1.51/libexec
```
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
Please report this upstream. `kotlin` is apparently incompatible with Java 9.

**Comment by ilovezfs** [comment]
@jrwiegand this should now be fixed if you `brew update` and `brew upgrade kotlin`
