### ISSUE TITLE
openblas-julia from staticfloat/julia no longer working

### ISSUE THREAD

**Issue by wjj2329** [Homebrew/homebrew-core#19940]
I had already install Jullia and this library before and had no issues a couple of weeks ago.  Then an update occurred for this library and every time I ran Brew Upgrade it would fail to update it and would give me this. 

Installing openblas-julia from staticfloat/julia
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
Already downloaded: /Users/williamjones/Library/Caches/Homebrew/openblas-julia-0.2.20.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/9c8a1
######################################################################## 100.0%
==> Patching
==> Applying openblas0.2.19.diff
patching file cpuid_x86.c
Hunk #1 succeeded at 1687 with fuzz 2 (offset 577 lines).
patching file driver/others/dynamic.c
Hunk #1 succeeded at 206 with fuzz 2 (offset -26 lines).
patching file kernel/x86_64/dgemm_kernel_4x8_sandy.S
Hunk #1 FAILED at 277.
Hunk #2 FAILED at 317.
Hunk #3 FAILED at 345.
Hunk #4 FAILED at 373.
Hunk #5 FAILED at 402.
Hunk #6 FAILED at 446.
Hunk #7 FAILED at 475.
Hunk #8 FAILED at 516.
Hunk #9 FAILED at 544.
Hunk #10 FAILED at 555.
Hunk #11 FAILED at 568.
Hunk #12 FAILED at 776.
Hunk #13 FAILED at 805.
Hunk #14 FAILED at 821.
Hunk #15 FAILED at 837.
Hunk #16 FAILED at 855.
Hunk #17 FAILED at 883.
Hunk #18 FAILED at 901.
Hunk #19 FAILED at 927.
Hunk #20 FAILED at 943.
Hunk #21 FAILED at 1076.
Hunk #22 FAILED at 1106.
Hunk #23 FAILED at 1123.
Hunk #24 FAILED at 1140.
Hunk #25 FAILED at 1159.
Hunk #26 FAILED at 1188.
Hunk #27 FAILED at 1208.
Hunk #28 FAILED at 1251.
Hunk #29 FAILED at 1345.
Hunk #30 FAILED at 1429.
Hunk #31 FAILED at 1497.
Hunk #32 FAILED at 1526.
Hunk #33 FAILED at 1563.
Hunk #34 FAILED at 1600.
Hunk #35 FAILED at 1637.
Hunk #36 FAILED at 1689.
Hunk #37 FAILED at 1726.
Hunk #38 FAILED at 1775.
Hunk #39 FAILED at 1815.
Hunk #40 FAILED at 1825.
Hunk #41 FAILED at 1838.
Hunk #42 FAILED at 1952.
Hunk #43 FAILED at 1977.
Hunk #44 FAILED at 1996.
Hunk #45 FAILED at 2015.
Hunk #46 FAILED at 2034.
Hunk #47 FAILED at 2067.
Hunk #48 FAILED at 2086.
Hunk #49 FAILED at 2116.
Hunk #50 FAILED at 2138.
Hunk #51 FAILED at 2220.
Hunk #52 FAILED at 2255.
Hunk #53 FAILED at 2264.
Hunk #54 FAILED at 2273.
Hunk #55 FAILED at 2282.
Hunk #56 FAILED at 2305.
Hunk #57 FAILED at 2314.
Hunk #58 FAILED at 2334.
Hunk #59 FAILED at 2345.
Hunk #60 FAILED at 2408.
Hunk #61 FAILED at 2534.
Hunk #62 FAILED at 2558.
Hunk #63 FAILED at 2580.
Hunk #64 FAILED at 2589.
Hunk #65 FAILED at 2598.
Hunk #66 FAILED at 2607.
Hunk #67 FAILED at 2630.
Hunk #68 FAILED at 2639.
Hunk #69 FAILED at 2660.
Hunk #70 FAILED at 2672.
Hunk #71 FAILED at 2762.
Hunk #72 FAILED at 2847.
Hunk #73 FAILED at 2878.
Hunk #74 FAILED at 2917.
Hunk #75 FAILED at 3000.
Hunk #76 FAILED at 3119.
76 out of 76 hunks FAILED -- saving rejects to file kernel/x86_64/dgemm_kernel_4x8_sandy.S.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/openblas-julia--patch-20171027-4663-9l9wju/openblas0.2.19.diff

So I ran brew uninstall to remove this library (Also so I could update other libraries) and tried running brew install openblas-julia to reinstall it and it gave me this same issue.  Brew doctor doesn't seem to give me any information about this error either apart from saying I'm missing this library that arpack-julia 3.3.0_4 is dependant on.   It also says there is no gist logs when I ran brew gist-logs openblas-julia.   Everything I have is up to date as well including my operating system which is running High Sierra.

**Comment by ilovezfs** [comment]
This should be reported to the relevant tap not homebrew/core. https://github.com/staticfloat/homebrew-julia/issues
