### ISSUE TITLE
MacOS get_iplayer problems - obsolete versions of IO::Socket::SSL causing problems for Mojolicious?

### ISSUE THREAD

**Issue by therealmarcuslynch** [Homebrew/homebrew-core#19956]
This is an issue discussed by several users on the get-iplayer forum, and is summarised as below. dinky.pumpkin replied to forum posts on this issue:-
"BBC schedule pages are now being redirected to HTTPS URLs. Systems with obsolete Perl modules, like macOS, could have problems with that. In particular, it looks like obsolete versions of IO::Socket::SSL cause problems for Mojolicious. 

More to the point, Homebrew has released 3.06 without addressing the issue discussed in this thread. I'm closing this thread. This is a Homebrew issue, so take it to their forum. As we make clear in the forum rules, Homebrew is not supported here."

As nobody else seems to have taken this to your forum, I am doing so. Apologies if I have not done so correctly, but I am still relatively new to using command line programs and forums.

ISSUE DESCRIPTION ON get-iplayer FORUM
<Trying to refresh my cache tonight and I'm getting this

get_iplayer --refresh
get_iplayer 3.05-homebrew, Copyright (C) 2008-2010 Phil Lewis
 This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
 This is free software, and you are welcome to redistribute it under certain
 conditions; use --conditions for details.

INFO: Indexing tv programmes (concurrent)
.....Mojo::Reactor:Tongueoll: I/O watcher failed: SSL_ca_file SCALAR(0x7f8a54001178) does not exist at /System/Library/Perl/Extras/5.18/IO/Socket/SSL.pm line 1642.
Mojo::Reactor:Tongueoll: I/O watcher failed: SSL_ca_file SCALAR(0x7f8a54001178) does not exist at /System/Library/Perl/Extras/5.18/IO/Socket/SSL.pm line 1642.
Mojo::Reactor:Tongueoll: I/O watcher failed: SSL_ca_file SCALAR(0x7f8a54001178) does not exist at /System/Library/Perl/Extras/5.18/IO/Socket/SSL.pm line 1642.
Mojo::Reactor:Tongueoll: I/O watcher failed: SSL_ca_file SCALAR(0x7f8a54001178) does not exist at /System/Library/Perl/Extras/5.18/IO/Socket/SSL.pm line 1642.
Mojo::Reactor:Tongueoll: I/O watcher failed: SSL_ca_file SCALAR(0x7f8a54001178) does not exist at /System/Library/Perl/Extras/5.18/IO/Socket/SSL.pm line 1642.>

- [ √] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ √] Ran `brew update` and retried your prior step?
- [ √] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ √] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 
***Did not work
- [ √] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? I had already run `brew doctor`and applied all relevant changes, none of which seem to have worke dwhen I ran it again.....

OUTPUT OF `brew config`
<Marcus-Air:~ marcus$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8571dd4d1d4e7dd1cd184661f10618ad6b9d6581
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.10.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25, 1.6.0_65-b14-468
macOS: 10.12.6-x86_64
Xcode: 9.0
CLT: 9.0.1.0.1.1506734476
X11: 2.7.9 => /opt/X11
MacPorts/Fink: /sw/bin/fink>

OUTPUT OF `brew doctor`
<Marcus-Air:~ marcus$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /sw/bin/fink

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/IKStealthPedalAPI.dylib
  /usr/local/lib/IKStompIO1API.dylib
  /usr/local/lib/libMonoPosixHelper.dylib
  /usr/local/lib/libSFFileMonitor.32.dylib
  /usr/local/lib/libSFIPC.32.dylib
  /usr/local/lib/libSFIPC.I.dylib
  /usr/local/lib/libSFsqlite3.7.4.dylib
  /usr/local/lib/libSFSyncEngine.I.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/jack/control.h
  /usr/local/include/jack/intclient.h
  /usr/local/include/jack/jack.h
  /usr/local/include/jack/jslist.h
  /usr/local/include/jack/midiport.h
  /usr/local/include/jack/ringbuffer.h
  /usr/local/include/jack/statistics.h
  /usr/local/include/jack/systemdeps.h
  /usr/local/include/jack/thread.h
  /usr/local/include/jack/transport.h
  /usr/local/include/jack/types.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/jack.pc

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'setenv PATH /usr/local/sbin:$PATH' >> ~/.tcshrc>

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
@therealmarcuslynch can you please test this version of the formula:
```
class GetIplayer < Formula
  desc "Utility for downloading TV and radio programmes from BBC iPlayer"
  homepage "https://github.com/get-iplayer/get_iplayer"
  url "https://github.com/get-iplayer/get_iplayer/archive/v3.06.tar.gz"
  sha256 "fba3f1abd01ca6f9aaed30f9650e1e520fd3b2147fe6aa48fe7c747725b205f7"
  head "https://github.com/get-iplayer/get_iplayer.git", :branch => "develop"

  bottle do
    cellar :any_skip_relocation
    sha256 "1ed429e5a0b2df706f9015c8ca40f5b485e7e0ae68dfee45c76f784eca32b553" => :high_sierra
    sha256 "1c9101656db2554d72b6f53d13fba9f84890f82119414675c5f62fb7e126373e" => :sierra
    sha256 "1c9101656db2554d72b6f53d13fba9f84890f82119414675c5f62fb7e126373e" => :el_capitan
  end

  depends_on "atomicparsley" => :recommended
  depends_on "ffmpeg" => :recommended

  depends_on :macos => :yosemite

  resource "IO::Socket::IP" do
    url "https://cpan.metacpan.org/authors/id/P/PE/PEVANS/IO-Socket-IP-0.39.tar.gz"
    sha256 "11950da7636cb786efd3bfb5891da4c820975276bce43175214391e5c32b7b96"
  end

  resource "IO::Socket::SSL" do
    url "https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.052.tar.gz"
    sha256 "e4897a9b17cb18a3c44aa683980d52cef534cdfcb8063d6877c879bfa2f26673"
  end

  resource "Mojolicious" do
    url "https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.48.tar.gz"
    sha256 "86d28e66a352e808ab1eae64ef93b90a9a92b3c1b07925bd2d3387a9e852388e"
  end

  def install
    ENV.prepend_create_path "PERL5LIB", libexec/"lib/perl5"
    ENV["NO_NETWORK_TESTING"] = "1"

    resources.each do |r|
      r.stage do
        system "perl", "Makefile.PL", "INSTALL_BASE=#{libexec}"
        system "make", "install"
      end
    end

    inreplace ["get_iplayer", "get_iplayer.cgi"] do |s|
      s.gsub!(/^(my \$version_text);/i, "\\1 = \"#{pkg_version}-homebrew\";")
      s.gsub! "#!/usr/bin/env perl", "#!/usr/bin/perl"
    end

    bin.install "get_iplayer", "get_iplayer.cgi"
    bin.env_script_all_files(libexec/"bin", :PERL5LIB => ENV["PERL5LIB"])
    man1.install "get_iplayer.1"
  end

  test do
    output = shell_output("\"#{bin}/get_iplayer\" --refresh --refresh-include=\"BBC None\" --quiet dontshowanymatches 2>&1")
    assert_match "get_iplayer #{pkg_version}-homebrew", output, "Unexpected version"
    assert_match "INFO: 0 matching programmes", output, "Unexpected output"
    assert_match "INFO: Indexing tv programmes (concurrent)", output,
                         "Mojolicious not found"
  end
end
```

**Comment by therealmarcuslynch** [comment]
Hi,

Thanks for quick reply. As I said, I'm relatively new to command line stuff (hence my use of homebrew rather than installing everything myself), so not quite sure what I should do with this code in Terminal.

Sorry to be so dim but I used to use GUI Get iPlayer Automator until it stopped working...

Can you guide me a bit?

Cheers, Marcus.

**Comment by ilovezfs** [comment]
@therealmarcuslynch No worries. I'm assuming that https://github.com/Homebrew/homebrew-core/pull/19987 is the correct fix and I've now shipped it. If you `brew update` and `brew upgrade`, you'll have the new version and can make sure it is in fact fixed now.

**Comment by therealmarcuslynch** [comment]
Hi,

Thanks for your understanding. I'll update and upgrade and let you know if it works OK now.

Cheers, Marcus.

**Comment by therealmarcuslynch** [comment]
Hi,

Just updated and upgraded and run it again - worked flawlessly! Many thanks for sorting it out so quickly. I'll post news of update on get-iPlayer forum.

Cheers, Marcus.

**Comment by ilovezfs** [comment]
@therealmarcuslynch thanks! That would be perfect.

**Comment by petef4** [comment]
I confirm that 3.06_01 fixes this same issue with IO::Socket::IP that I was seeing in El Capitan 10.11.6.
