### ISSUE TITLE
Can't upgrade infer of 0.13

### ISSUE THREAD

**Issue by veryitman** [Homebrew/homebrew-core#19963]
I have installed the infer of version0.12.1 by brew.

I want to upgrade it to 0.13 using cmd:

```
brew update
brew upgrade infer
```
It can't upgrade.

But i change a way:

```
brew uninstall infer
brew install infer
```

So, install completed, the version is always 0.12.1.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/19646

**Comment by veryitman** [comment]
@ilovezfs Sorry, I can't understand.

**Comment by ilovezfs** [comment]
@veryitman the pull request that would upgrade infer to 0.13 hasn't been merged yet, so you're still going to be on 0.12.1 until that happens.

**Comment by veryitman** [comment]
Thanks, I have understanted you.

0.12.1 can't be used in Xcode 9.
The check tells me no issue.

**Comment by ilovezfs** [comment]
@veryitman right. See https://github.com/facebook/infer/issues/756

**Comment by veryitman** [comment]
Ok, Thanks.

**Comment by Benny-iPhone** [comment]
un-install and re-install fixed it
