### ISSUE TITLE
wxmac fails to build on OSX 10.12

### ISSUE THREAD

**Issue by enilsen16** [Homebrew/homebrew-core#1996]
https://gist.github.com/anonymous/5d22977c76e44ffd920a99ba0ec061ec

**Comment by enilsen16** [comment]
Building from source seems to work.

**Comment by UniqMartin** [comment]
> Building from source seems to work.

You were already building from source, so not sure why something would have changed on the second run. There are no bottles yet for 10.12 (they will only appear once we get closer to a final release).

Please take to heart this output of `brew doctor`:

```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
```

macOS Sierra is *very* new and obviously hasn't seen much testing, not to mention that Homebrew hasn't been fully adopted to all changes just yet. The best thing you can do at this stage is to investigate build failures, report them to upstream (if applicable), and contribute back with pull requests. Thanks!

**Comment by enilsen16** [comment]
@UniqMartin Yeah sorry about that I meant `head`. 

Is it best to report MacOS issues to the issue created by @DomT4?

**Comment by UniqMartin** [comment]
> Yeah sorry about that I meant `head`.

That's valuable information. Maybe you can track down the commit where this was fixed and see if the latest stable release can be patched from that commit. That would be a way to actually fix the formula.

> Is it best to report MacOS issues to the issue created by @DomT4?

Yes, commenting in #1957 is preferable at this early stage, though debugging and contributing fixes in the form of pull requests is even more so. :wink:

**Comment by tdsmith** [comment]
Heh, this is the commit that fixes it: http://trac.wxwidgets.org/changeset/f6a2d1caef5c6d412c84aa900cb0d3990b350938/git-wxWidgets
