### ISSUE TITLE
How to help installing gstreamer recommended dependencies?

### ISSUE THREAD

**Issue by pornel** [Homebrew/homebrew-core#20014]
Most gstreamer-based tools also need `gst-plugins-base` and `gst-plugins-*` formulas, and don't work with the `gstreamer` formula alone. This is quite non-obvious: 

* Search for `gstreamer-video-1.0` (often required by tools) does not find the plugins formulas that contain this (pkginfo) package. 
* `brew info gstremer` does not hint existence of `gst-plugins-*`, 
* the plugin formulas don't come up in search results for "gstreamer".

I wanted to fix that, but:

* Description is limited to 80 characters, and in gstreamer's description there's no room left to add info about gst-plugins.
* I could not find any long description nor keyword-related fields in `Formula` class
* An optional `depends_on` for `gst-plugins-base` in `gstreamer` could be a nice hint that this is often needed, but `gst-plugins-base` formula depends on `gstreamer` itself. That would create a circular dependency, and I assume that's not allowed.

Do you have a suggestion how this can be improved? (so that person unfamiliar with gstreamer packaging can figure out how to install all of it)

**Comment by ilovezfs** [comment]
maybe a very brief `def caveats` would suffice
