### ISSUE TITLE
no attestation matches subject: simdjson--3.11.0.arm64_sequoia.bottle.tar.gz

### ISSUE THREAD

**Issue by ivaquero** [Homebrew/homebrew-core#200359]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config

HOMEBREW_VERSION: 4.3.23-53-g29c22e0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 29c22e0ab3fd9826cefd4b14c143266dea3bc391
Last commit: 3 months ago
Core tap JSON: 07 Dec 02:18 UTC
Core cask tap JSON: 07 Dec 02:18 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 3
HOMEBREW_EDITOR: code
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTOREMOVE: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_ENV_HINTS: set
HOMEBREW_SORBET_RUNTIME: set
all_proxy: socks5://127.0.0.1:7890
http_proxy: http://127.0.0.1:7890
https_proxy: http://127.0.0.1:7890
Homebrew Ruby: 3.3.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.4_1/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false

brew doctor

Your system is ready to brew.
```
```


### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

```console
brew install simdjson
```

### What happened (include all command output)?

```console
Error: The bottle for simdjson has an invalid build provenance attestation.

This may indicate that the bottle was not produced by the expected
tap, or was maliciously inserted into the expected tap's bottle
storage.

Additional context:

no attestation matches subject: simdjson--3.11.0.arm64_sequoia.bottle.tar.gz
```

### What did you expect to happen?

```console
Pouring simdjson--3.11.0.arm64_sequoia.bottle.tar.gz
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install simdjson
```

**Comment by cho-m** [comment]
Your `brew` is out-of-date:
```
HOMEBREW_VERSION: 4.3.23-53-g29c22e0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 29c22e0ab3fd9826cefd4b14c143266dea3bc391
Last commit: 3 months ago
```

Please try again after updating to recent version.

**Comment by ivaquero** [comment]
Maybe this is due to another bug, I tried `brew config` many times, but get the same result.

**Comment by gromgit** [comment]
`brew config` just tells you about your Homebrew setup. You want to run `brew update`, _then_ `brew config` to confirm that your setup is more recent than 3 months ago.

**Comment by ivaquero** [comment]
Although `export HOMEBREW_NO_VERIFY_ATTESTATIONS=1` is a work around, I still think this is a fixable bug.

**Comment by cho-m** [comment]
You need a version of `brew` at least 4.4.10 (https://github.com/Homebrew/brew/releases/tag/4.4.10) to install recent bottles due to multiple subject attestations.

---

If you are on latest `master` branch, output of `brew config` should look like:
```
HOMEBREW_VERSION: 4.4.10-20-g405ceda
ORIGIN: https://github.com/Homebrew/brew
HEAD: 405cedad235fa9d6960e19b78705d0f43094b140
Last commit: 12 hours ago
Branch: master
```

If you are on latest `stable` branch, output of `brew config` should look like:
```
HOMEBREW_VERSION: 4.4.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8c868ba70e526f1f00561470d58fcbaddb1b4e48
Last commit: 2 days ago
Branch: stable
```

Given lack of `Branch:` information in your output, it seems like you may not be on either.

---

May want to make sure `git -C "$(brew --prefix)" status` shows either `master`  or `stable`. Could manually run `git` commands to restore or try [`brew update-reset`](https://docs.brew.sh/Manpage#update-reset-repository-)

**Comment by ivaquero** [comment]
@cho-m Thank you, you are right, I am on a branch of my PR. `[brew update-reset](https://docs.brew.sh/Manpage#update-reset-repository-)` solve the problem.
