### ISSUE TITLE
why need dependency  python 3.11, 3.12 & 3.13 ? no install single python3 only exmaple just 3.12

### ISSUE THREAD

**Issue by alsyundawy** [Homebrew/homebrew-core#200354]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
when install bind9 parallel aria2 git gh why need dependency python 3.11, 3.12 & 3.13 too?
so i need req why no have  option to install pyhton 3.12 or 3.13 only



please use single pyhton3 dependency only exmaple just 3.12
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

when install bind9 parallel aria2 git gh why need dependency python 3.11, 3.12 & 3.13 too?
so i need req why no have  option to install pyhton 3.12 or 3.13 only

please use single pyhton3 dependency only exmaple just 3.12

### What happened (include all command output)?

when install bind9 parallel aria2 git gh why need dependency python 3.11, 3.12 & 3.13 too?
so i need req why no have  option to install pyhton 3.12 or 3.13 only

### What did you expect to happen?

when install bind9 parallel aria2 git gh why need dependency python 3.11, 3.12 & 3.13 too?
so i need req why no have  option to install pyhton 3.12 or 3.13 only

please use single pyhton3 dependency only exmaple just 3.12

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
when install bind9 parallel aria2 git gh why need dependency python 3.11, 3.12 & 3.13 too?
so i need req why no have  option to install pyhton 3.12 or 3.13 only


please use single pyhton3 dependency only exmaple just 3.12
```

**Comment by ZhongRuoyu** [comment]
Please fill out the issue template properly. A normal installation of these formulae would not require any Python dependency.
