### ISSUE TITLE
brew upgrade error in ruby 'dyld: lazy symbol binding failed: Symbol not found: _futimens'

### ISSUE THREAD

**Issue by parunach** [Homebrew/homebrew-core#20056]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I tried to install graphviz

`brew install graphviz`

and received

> ==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
> Already downloaded: /Users/test/Library/Caches/Homebrew/portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
> ==> Pouring portable-ruby-2.3.3.leopard_64.bottle.1.tar.gz
> dyld: lazy symbol binding failed: Symbol not found: _futimens
>   Referenced from: /usr/local/bin/tar
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> dyld: Symbol not found: _futimens
>   Referenced from: /usr/local/bin/tar
>   Expected in: /usr/lib/libSystem.B.dylib
> 
> /usr/local/Homebrew/Library/Homebrew/cmd/vendor-install.sh: line 115: 93634 Abort trap: 6           tar "$tar_args" "$CACHED_LOCATION"
> Error: Failed to install vendor ruby.
> Error: Failed to install vendor Ruby.

I tried

`brew doctor`
and
`brew upgrade`

and got the same error.

**Comment by JCount** [comment]
@parunach The issue you are having is that your default `tar`, (the first one in your `PATH`), appears to have been built with symbols that your version of macOS does not have.

To work around this, try running: `env PATH="/usr/bin/tar:$PATH" brew update`

Please report back about the results.

**Comment by DomT4** [comment]
We trust people to have a "sane" [tar](https://github.com/Homebrew/brew/blob/270b752f5d9d218bfbed6fe85b6974fa653fb25f/Library/Homebrew/cmd/vendor-install.sh#L144) installed, which perhaps is unwise 🙈.

**Comment by parunach** [comment]
You are right, if I use the /usr/bin it works. Thanks a lot!
