### ISSUE TITLE
I've been trying to install man and mysql using brew and it's been throwing the following error:

### ISSUE THREAD

**Issue by pptaj** [Homebrew/homebrew-core#20052]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [Yes ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ Yes] Ran `brew update` and retried your prior step?
- [Yes ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [Yes ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Yes ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) 
  I'm trying to install man and mysql
- What happened (include command output)
taj.palecanda:~ $ brew install mvn31
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4614, done.
remote: Compressing objects: 100% (4398/4398), done.
remote: Total 4614 (delta 34), reused 310 (delta 8), pack-reused 0
Receiving objects: 100% (4614/4614), 3.83 MiB | 2.96 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imagesnap.rb
undefined method `>=' for nil:NilClass
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llnode.rb
undefined method `>=' for nil:NilClass
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
taj.palecanda:~ $ 

- What you expected to happen
   install the software
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by DomT4** [comment]
Can you provide your `brew config`?

**Comment by pptaj** [comment]
@DomT4 
taj.palecanda:~ $ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 12 days ago
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4614, done.
remote: Compressing objects: 100% (4398/4398), done.
remote: Total 4614 (delta 34), reused 310 (delta 8), pack-reused 0
Receiving objects: 100% (4614/4614), 3.83 MiB | 1.65 MiB/s, done.
Resolving deltas: 100% (34/34), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/imagesnap.rb
undefined method `>=' for nil:NilClass
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/llnode.rb
undefined method `>=' for nil:NilClass
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
taj.palecanda:~ $

**Comment by DomT4** [comment]
Aha, okay. How about `xcodebuild -version` and `ls -1 /Library/Developer/CommandLineTools/usr`?

**Comment by pptaj** [comment]
@DomT4 
taj.palecanda:~ $ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
taj.palecanda:~ $ ls -1 /Library/Developer/CommandLineTools/usr
bin
include
lib
libexec
share
taj.palecanda:~ $

**Comment by DomT4** [comment]
Okay, I guess I'll just ask for the information I was trying to tease out of `xcodebuild`. Do you have Xcode installed? Also what does `clang --version` output? From the `Clang: N/A` I wondered if you had a partially-broken CLT installation or something, but doesn't look likely from the `ls` at least.

**Comment by pptaj** [comment]
@DomT4 Does this mean that I have to install Xcode? Should I upgrade brew now?

**Comment by DomT4** [comment]
> Does this mean that I have to install Xcode?

No, it's not mandatory. I'm working off a hunch on this because I don't currently have a clean VM to test against but I've opened three PRs which I think _should_ resolve your issue.

**Comment by pptaj** [comment]
@DomT4 perfect! Thank you, Dominyk.

**Comment by ilovezfs** [comment]
Should be fixed now.

**Comment by DomT4** [comment]
Presuming I haven't missed any more of these 😸.

**Comment by pptaj** [comment]
@DomT4 , the installation worked. Thank you so much for your help.

**Comment by pptaj** [comment]
Thank you, @ilovezfs .
