### ISSUE TITLE
Patch link in unzip.rb points to nowhere

### ISSUE THREAD

**Issue by blogabe** [Homebrew/homebrew-core#200768]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
[unzip](https://github.com/Homebrew/homebrew-core/blob/f9cd7140195ba602fecc83791d4a2a0cf61df813/Formula/u/unzip.rb) requires [patch](http://archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-27ubuntu1.debian.tar.xz) which does not exist:
Failed to download resource "unzip--patch
 Download failed: http://archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-27ubuntu1.debian.tar.xz
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

intall unzip

### What happened (include all command output)?

patch doesn't download

### What did you expect to happen?

successful install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install unzip
```

**Comment by ZhongRuoyu** [comment]
This has been fixed. Please run `brew update`, and then try again.
