### ISSUE TITLE
php@7 missing

### ISSUE THREAD

**Issue by aep-sunlife** [Homebrew/homebrew-core#200955]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs php@7
Error: No available formula with the name "php@7". Did you mean php?
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I have a need to target PHP prior to v8.

I see that the php formula supports some specific versions of PHP, just not other specific major versions like v6, v5, etc.

### What happened (include all command output)?

```console
$ brew install php@7
Warning: No available formula with the name "php@7". Did you mean php?
==> Searching for similarly named formulae and casks...
==> Formulae
php ✔

To install php ✔, run:
  brew install php ✔
```

### What did you expect to happen?

PHP 7 should install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install php@7
==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=#                                                                            
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=#                                                                            
Warning: No available formula with the name "php@7". Did you mean php?
==> Searching for similarly named formulae and casks...
==> Formulae
php ✔

To install php ✔, run:
  brew install php ✔
```

**Comment by carlocab** [comment]
PHP 7 is no longer supported: https://endoflife.date/php
