### ISSUE TITLE
brew's micromamba provides mamba as well as 

### ISSUE THREAD

**Issue by BastianZim** [Homebrew/homebrew-core#200954]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Error: No logs.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use micromamba to create anything

### What happened (include all command output)?

mamba is also installed and micromamba a link of mamba. 

Ref: https://formulae.brew.sh/formula/micromamba

I opened an issue for mamba here as well which has more info: https://github.com/mamba-org/mamba/issues/3687

The gist ist:

I only installed micromamba with `brew install micromamba` and got mamba as well:

```
bastianzimmermann@Bastians-MacBook ~ % which mamba
/opt/homebrew/bin/mamba
bastianzimmermann@Bastians-MacBook ~ % which micromamba 
micromamba () {
	__mamba_wrap "$@"
}
bastianzimmermann@Bastians-MacBook ~ % type mamba
mamba is /opt/homebrew/bin/mamba
```

This might also be related to https://github.com/spyder-ide/spyder/issues/23246 as I didn't get this before.

### What did you expect to happen?

Only get micromamba and no mamba

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install micromamba
```

**Comment by carlocab** [comment]
The `micromamba` executable is just a symlink to `mamba` to avoid breaking users who call it as `micromamba`:

https://github.com/Homebrew/homebrew-core/blob/13950f56ab9288166fd8661f1bc3e29fa591684c/Formula/m/micromamba.rb#L61-L63

Since v2 they're essentially the same thing. Is there a reason you want only an executable named `micromamba` and not one named `mamba` too?

**Comment by BastianZim** [comment]
Ahh I did not know that. No, I don't have a preference for micromamba vs mamba, but based on the docs, they are two different things, from my understanding? I generally liked micromamba as it is faster than mamba.

Also, the installation is "weird" in the sense that it creates a `mamba` file under my user and not a `.mamba` file as the docs state.

So I guess it's best to just use mamba?

**Comment by carlocab** [comment]
Historically they were different, but these days they're the same thing now (modulo some implementation details that you shouldn't really notice).

> Also, the installation is "weird" in the sense that it creates a `mamba` file under my user and not a `.mamba` file as the docs state.

That might be from the caveats:
```
==> Caveats
Please run the following to setup your shell:
  /opt/homebrew/opt/micromamba/bin/mamba shell init --shell <your-shell> --root-prefix ~/mamba
```

If you had done
```
/opt/homebrew/opt/micromamba/bin/mamba shell init --shell <your-shell> --root-prefix ~/.mamba
```
I suspect you'll get the `.mamba` that you were expecting.

> So I guess it's best to just use mamba?

You can use either; it doesn't really matter.
