### ISSUE TITLE
Filenames with non-valid UTF8 in 'is' and 'nb' dictionaries prevent aspell from being installed 

### ISSUE THREAD

**Issue by lucrocha** [Homebrew/homebrew-core#20108]
Hi,

I had aspell installed version 0.60.6.1. Doing a `brew update` today ended up in failure due to invalid UTF-8 characters in file names used by the 'is' and 'nb' dictionaries.

# Please always follow these steps:
- [ X ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [  ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ X ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to do a 'brew update' of everything. I do this every few weeks, to keep my system up to date.

- What happened (include command output)

The update failed on updating aspell, when doing the 'make install' for the 'is' dictionary. I commented that one out, and then it failed on the 'nb' dictionary too, for the same reason (different file name though). After also removing the 'nb' dictionary, then it finished correctly.

Gist with the build output and error:
   https://gist.github.com/lucrocha/198f61cb143f08724ee1b5f0aedc418c

Doing a `brew gist-logs aspell` failed for similar reason, invalid UTF-8 character in the output:
  https://gist.github.com/lucrocha/088ae16d265e0deba1a97f028ac532d9

Gist with the part of gist-logs for the 'is' install:
  https://gist.github.com/lucrocha/e436cff7a7cf5af1498e295bffdd952c

I've checked the contents of the 'is' package, https://ftp.gnu.org/gnu/aspell/dict/is/aspell-is-0.51.1-0.tar.bz2, as I expected the file to fail already when unpackaging it, but the file isn't named like that in the package:
-rw-r----- 1 lrocha wheel     72 Mar 11  2004 %EDslenska.alias

So the install does the conversion to an invalid character (it's the character `í` in latin1 encoding).

- What you expected to happen

That the install step of a package (or subpackage?) wouldn't try and fail to create invalid file names.

- Step-by-step reproduction instructions (by running `brew install` commands)

I have the option '--with-all-langs' enabled for aspell.
With a prior version installed with that option do: brew upgrade aspell

Without aspell installed, do: brew install aspell --with-all-langs

**Comment by lucrocha** [comment]
Forgot some details:
 - Darwin C02TN0JGG8WL 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
 - macOS Sierra 10.12.6 (16G1036)
 - Xcode Version 9.0.1 (9A1004)

**Comment by lucrocha** [comment]
And filesystem type:

$ df -h /usr/local/Cellar/
Filesystem      Size  Used Avail Use% Mounted on
/dev/disk1      465G  214G  252G  46% /
$ mount | grep disk1
/dev/disk1 on / (hfs, local, journaled)

**Comment by apjanke** [comment]
I can reproduce on my Sierra box. `brew install aspell --with-lang-nb` and `brew install aspell --with-lang-is` are 


```
$ brew install aspell --with-lang-nb
...
==> make install
Last 15 lines from /Users/janke/Library/Logs/Homebrew/aspell/12.make:
2017-11-03 15:26:33 -0400

make
install

/usr/local/Cellar/aspell/0.60.6.1_1/bin/word-list-compress d < nb.cwl | /usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell  --lang=nb create master ./nb.rws
mkdir -p /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp nb.rws bokmal.alias bokm�l.alias nb.multi no.alias norsk.alias /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp: /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/bokm�l.alias: Operation not permitted
make: *** [install] Error 1
...
$ brew install aspell --with-lang-is
...
==> make install
Last 15 lines from /Users/janke/Library/Logs/Homebrew/aspell/12.make:
2017-11-03 15:28:05 -0400

make
install

/usr/local/Cellar/aspell/0.60.6.1_1/bin/word-list-compress d < is.cwl | /usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell  --lang=is create master ./is.rws
mkdir -p /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp is.rws icelandic.alias is.multi �slenska.alias /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp: /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/�slenska.alias: Operation not permitted
make: *** [install] Error 1
```

I'll do a bit of research on this. I agree this looks like an encoding issue. On a quick glance, it looks like the `Makefile.pre` files in the aspell dictionary distributions are encoded in ISO-8859 instead of Unicode. But the build process/file system is operating in Unicode/UTF-8, so these are invalid strings. That is, I don't think it's the file names in the files themselves that are the problem; it's the file lists in this line of `Makefile.pre`.

```
multi_files = icelandic.alias is.multi íslenska.alias
```

Wonder why this wasn't reported earlier; the dictionary files haven't changed in years. Maybe nobody's using these languages?

**Comment by apjanke** [comment]
@lucrocha Question for you: do you actually need the IS and NB dictionaries? Or do you just want to install "everything"? The quick fix from Homebrew's perspective might just be disabling the IS and NB dictionaries and reporting the issue upstream.

**Comment by apjanke** [comment]
I think we could also fix this by just transcoding the `Makefile.in` from ISO-8859-1 to UTF-8 and patching up the file names that have those weird `%` escape sequences in them, but I'd like to get at the root of how the files got generated that way, and determine what the Right Way to run this from upstream's perspective is.

**Comment by apjanke** [comment]
Here's another strange thing. When I try to reproduce this by installing the dictionaries individually to `/tmp`, the installation succeeds.

```
[~/tmp/aspell/aspell-is-0.51.1-0]
$ DESTDIR=/tmp/test-aspell ./configure --vars ASPELL=/usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell PREZIP=/usr/local/Cellar/aspell/0.60.6.1_1/bin/prezip
Finding Dictionary file location ... /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60
Finding Data file location ... /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60
[~/tmp/aspell/aspell-is-0.51.1-0]
$ make install
mkdir -p /tmp/test-aspell/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp is.rws icelandic.alias is.multi �slenska.alias /tmp/test-aspell/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cd /tmp/test-aspell/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/ && chmod 644 is.rws icelandic.alias is.multi �slenska.alias
mkdir -p /tmp/test-aspell/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp is.dat is_phonet.dat /tmp/test-aspell/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cd /tmp/test-aspell/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/ && chmod 644 is.dat is_phonet.dat
[~/tmp/aspell/aspell-is-0.51.1-0]
$
```

Same if I install it into `/usr/local/Cellar/aspell` manually. Seems like something is different about the `brew install` environment that's affecting character encoding interpretation or filesystem strictness?

**Comment by ilovezfs** [comment]
Happy to review a PR fixing this.

**Comment by apjanke** [comment]
@ilovezfs What do you think about a PR just removing the `is` and `nb` dictionaries for the time being? Doing a real fix might be kinda involved, but that would at least get `--with-all-langs` working again.
