### ISSUE TITLE
Brew upgrade huggingchat failed SHA256 mismatch

### ISSUE THREAD

**Issue by Vercety87** [Homebrew/homebrew-core#201036]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 4.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad356d365837a691a52dfec32b3fb5f282f3aefc
Last commit: 4 days ago
Branch: stable
Core tap JSON: 13 Dec 08:14 UTC
Core cask tap JSON: 13 Dec 08:14 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.1.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: N/A
Rosetta 2: false

brew doctor
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Try to update huggingchat with `brew upgrade`

### What happened (include all command output)?

SHA256 mismatch, even after deleting the file
 `==> Casks with 'auto_updates true' or 'version :latest' will not be upgraded; pass `--greedy` to upgrade them.
==> Upgrading 1 outdated package:
huggingchat 0.6.0 -> 0.7.0
==> Upgrading huggingchat
==> Downloading https://github.com/huggingface/chat-macOS/releases/download/v0.7.0/HuggingChat.zip
Already downloaded: /Users/xx/Library/Caches/Homebrew/downloads/56d240e19d805142edbb7c71b9a07ae7f11b0dcde5d3c747bef9a80c912edb2a--HuggingChat.zip
==> Purging files for version 0.7.0 of Cask huggingchat
Error: huggingchat: SHA256 mismatch
Expected: 6a9601d793f25dc62fe6cec9314a7a99d51106937d283c90fabd45e29f1d83e4
  Actual: b421090d0e68230b7fc2dc086bb12b1e846acce0682af45edc26e66b4be15ce1
    File: /Users/xx/Library/Caches/Homebrew/downloads/56d240e19d805142edbb7c71b9a07ae7f11b0dcde5d3c747bef9a80c912edb2a--HuggingChat.zip
To retry an incomplete download, remove the file above.
`

### What did you expect to happen?

Huggingchat to be updated to 0.7.0

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update && brew upgrade
```

**Comment by SMillerDev** [comment]
This is not a formula, so this should be filed in https://github.com/Homebrew/homebrew-cask/issues
