### ISSUE TITLE
Racket: problems when upgrading to new release

### ISSUE THREAD

**Issue by HiPhish** [Homebrew/homebrew-core#20137]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
[brew-doctor.txt](https://github.com/Homebrew/homebrew-core/files/1433842/brew-doctor.txt)
[brew-config.txt](https://github.com/Homebrew/homebrew-core/files/1433832/brew-config.txt)

> What you were trying to do (and why)

Upgrade from one version of Minimal Racket to another one

> What happened (include command output)

Upgrade works fine, but there are leftovers from the old installation which interfere with the new one. Even first uninstalling the old one and installing the new one is not sufficient. In particular, all the packages end up split between the new and old Racket version, making everything unusable. The existence of old file prevents the installation of new files.

> What you expected to happen

Uninstalling should have removed all traces of the old version.

> Step-by-step reproduction instructions (by running `brew install` commands)

```sh
# regular upgrading
brew update
brew upgrade

# or attempting to remove the old version first
brew update
brew uninstall minimal-racket
brew install minimal-racket
```
__________

This is an issue that has been throwing me off every time a new version of Racket was released. Basically what happens is that some of Racket's files leak into the file system, such as binaries like DrRacket (the official IDE) in `/usr/local/bin`. This could be related to Racket's own package manager placing those files in there.

I ran `ack '[^bB]racket'` in `/usr/local/` and this is a list of files and directories that need to be removed:

I removed some of the false positives. This might not be a minimal list, but after removing those installing Racket works again.

- `bin/DrRacket.app/`
- `bin/drracket`
- `bin/gracket`
- `bin/gracket-text`
- `bin/mred`
- `bin/mred-text`
- `bin/plt-help`
- `bin/plt-r5rs`
- `bin/plt-r6rs`
- `bin/plt-web-server`
- `bin/Racket Documentation.app`
- `bin/scribble`
- `etc/racket/`

**Comment by JCount** [comment]
@HiPhish 
I believe this is indeed caused by running `raco pkg install --auto drracket` to install the IDE. The files that are created by `raco pkg install` are not, and realistically cannot be tracked by Homebrew's current formula code. This means when the formula is uninstalled or updated, those files get left behind as unwanted artifacts.

However, I believe that you should be able to uninstall `drracket` using `raco` **_prior_** to performing an upgrade (or uninstall), and prevent the remnants from being created.  I realize this is less than an ideal solution, but I think it _should_ work. I recommend testing it once or twice with an installation of `minimal-racket` you don't care too much about to see if, and how, it works.
**(Disclaimer: I have not actually tested this.)**

I would be great if you could post whether this actually works, and if it does, how well. If it does work, it may be something to add to the `caveats` section of the formula.

Good luck! 😄

**Comment by HiPhish** [comment]
I'll have to try when Racket 6.12 rolls around in a few months. But I'm wondering, would it be possible to set aside a set of directories for raco to place those files into and then somehow to add them to the `PATH`? Something like when Racket is installed created a directory `/usr/local/lib/racket6.11/` with directories like `bin/` and `etc/`, set up raco to use that instead of `/usr/local/bin/` and add them to the `PATH`. Then, when uninstalling Racket nuke `/usr/local/lib/racket6.11` and remove `/usr/local/lib/racket6.11/bin` from the `PATH` again. That way raco would not spill its results over.

Another question, is it possible to tell Homebrew not to automatically upgrade Racket when I run `brew upgrade`? Because if it happens automatically I don't get a chance to first uninstall all raco packages.

**Comment by JCount** [comment]
Looking at the formula, I can tell we already make some config changes to `raco`: [minimal-racket.rb#L34-L45](https://github.com/Homebrew/homebrew-core/blob/master/Formula/minimal-racket.rb#L34-L45). It is possible that these could be improved, to make the package install and uninstall process more streamlined. I’d be happy if to provide guidance/help if you would like to try and open a PR.

Also, have you tried using `raco pkg migrate` (if that would even apply in this situation)?

Regarding your final question, calling `brew upgrade` unconditionally will always attempt to upgrade of all your outdated formulae. The most reliable way to prevent an unintended upgrade is to slightly change the way you update Homebrew. I’ll list them as a series of steps for clarity.

1. Run `brew update`. This will update the Homebrew version if necessary as well as fetch the most recent formulae information.
2. Run `brew outdated`. This will display all of your outdated formulae, what would be upgraded if you ran `brew upgrade`.
  a. If `minimal-racket` is on the list do what you need to and then run `brew upgrade`.
  b. Simply run `brew upgrade` if there is nothing on the list that you want to handle specially.

**Aside:** Running `brew upgrade foo` will upgrade `foo` and it’s outdated dependencies (except for some edge cases with custom builds).

**Comment by HiPhish** [comment]
An update: upgrading Racket and then running `raco pkg migrate` did not work.
