### ISSUE TITLE
fakeroot doesn't work on arm64e: needs arm64e dylib slice

### ISSUE THREAD

**Issue by saurik** [Homebrew/homebrew-core#201419]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 4.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3001afe88112c13b5aafdd92e097680897060881
Last commit: 30 hours ago
Branch: stable
Core tap HEAD: 4d66a7cf5c69f36d57796f4ed2bf6f2f84527a09
Core tap last commit: 16 minutes ago
Core tap JSON: 16 Dec 21:28 UTC
Core cask tap HEAD: 87b51675dcc35335e44b3e84c398609095b63b34
Core cask tap last commit: 42 minutes ago
Core cask tap JSON: 16 Dec 21:28 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_COLOR: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 3-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 14.7.1-arm64
CLT: 16.1.0.0.1.1729049160
Xcode: 15.4 => /Applications/Xcode_15.4.app/Contents/Developer
Rosetta 2: false
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Use fakeroot for its intended purpose (I have script that needs to run as root).

### What happened (include all command output)?

bash-3.2$ fakeroot ls
dyld[37445]: terminating because inserted dylib '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' could not be loaded: tried: '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' (no such file), '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot-0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot-0.dylib' (no such file), '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot-0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))
dyld[37445]: tried: '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' (no such file), '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot-0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot-0.dylib' (no such file), '/opt/homebrew/Cellar/fakeroot/1.36/lib/libfakeroot-0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))
/opt/homebrew/bin/fakeroot: line 178: 37445 Abort trap: 6           FAKEROOTKEY=$FAKEROOTKEY DYLD_INSERT_LIBRARIES="$FAKEROOT_LIB" "$@"

### What did you expect to happen?

ls to execute (but as root)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install fakeroot
fakeroot ls
```

**Comment by SMillerDev** [comment]
> CPU: 3-core 64-bit dunno

What hardware are you running this on?

**Comment by carlocab** [comment]
Last I checked, it is not possible to build working arm64e executables outside of Apple. Running them requires disabling SIP.

Has that changed?

**Comment by Bo98** [comment]
> Has that changed?

It hasn't changed, no. arm64e ABI isn't stable and can change between macOS updates without notice.

`fakeroot` isn't really supported when using Apple system binaries due to SIP limitations. It requires disabling SIP to even take effect and when it does take effect it then needs arm64e which is requires changing OS boot arguments for the OS to even accept non-Apple libraries.

Using `coreutils` should work however.

**Comment by saurik** [comment]
> What hardware are you running this on?

FWIW, it is a GitHub Actions CI macos-latest runner instance, which is virtualized somehow (and thereby the reason why I'm not just using docker for this workload, due to the lack of nested virutalization).

$ uname -a
Darwin Mac-1734386730101.local 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:00 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_VMAPPLE arm64

$ sysctl machdep.cpu
machdep.cpu.cores_per_package: 3
machdep.cpu.core_count: 3
machdep.cpu.logical_per_package: 3
machdep.cpu.thread_count: 3
machdep.cpu.brand_string: Apple M1 (Virtual)

Regardless, I naively assumed this would be easy--as it always was dealing with these issues on 32-bit ARM back in the day (on jailbroken iOS devices)--but, after reading your explanations (and doing some testing of my own after trying to build a working version of fakeroot myself... I seemingly managed to get it injected, but had to make a bunch of silly hacks due to $INODE64 symbols that weren't being found, and then it still didn't work as it just locked up? it is reporting an AMFI issue, but I honestly think that's spurious. regardless: I gave up, as I don't care enough; it could be that the issue is as simple as that I'm using the configure script output for arm64 to build the arm64e libraries?), _of course_, Apple is being annoying :(.

Given that this is, in fact, difficult, and even then is likely more of a thing to negotiate with the upstream fakeroot, I'll close this issue here ;P. Thanks, regardless, for even discussing/considering the issue <3.
