### ISSUE TITLE
scipy.spatial.Delaunay segfaults

### ISSUE THREAD

**Issue by ghackebeil** [Homebrew/homebrew-core#20148]
Calling `scipy.spatial.Delaunay` from Python 2.7.14 or Python 3.6.3 (i.e., the most recent homebrew-installed versions) results in a segmentation fault for the homebrew-installed Scipy 1.0.0. This occurs after both `brew install scipy` and `brew install --build-from-source scipy`. E.g., running
```python
import numpy
import scipy.spatial
scipy.spatial.Delaunay(numpy.array([[0.0, 0.0, 0.0],
                                    [1.0, 0.0, 0.0],
                                    [0.0, 1.0, 0.0],
                                    [0.0, 0.0, 1.0]]))
```
results in output `Segmentation fault: 11`.

However, there is no issue with this function when Scipy 1.0.0 is directly installed with pip (e.g., `pip2 install scipy`, `pip3 install scipy`).

Build logs:
https://gist.github.com/9a6471c60bdab0ad4529c3240dacecdb

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by ilovezfs** [comment]
I cannot reproduce this issue.
