### ISSUE TITLE
x264 “ failed to load avisynth”; official binary runs without error

### ISSUE THREAD

**Issue by elmimmo** [Homebrew/homebrew-core#20172]
Running x264, installed via `brew install x264` (currently r2795; tried on macOS 10.11.6), as described in [Authoring a professional Blu-ray Disc with x264 (1080p content)](http://www.x264bluray.com/home/1080i-p), like so:

    x264 --bitrate 25000 --preset veryslow --tune animation --bluray-compat --vbv-maxrate 30000 --vbv-bufsize 30000 --level 4.1 --keyint 25 --open-gop --slices 4 --fake-interlaced --colorprim "bt709" --transfer "bt709" --colormatrix "bt709" --sar 1:1 --pass 1 -o out.264 in.mp4

returns the following errors:

````
avs [error]: failed to load avisynth
raw [error]: raw input requires a resolution.
x264 [error]: could not open input file `in.mp4' via any method!
````

Running the [latest x264 binary at videolan.org](http://download.videolan.org/pub/videolan/x264/binaries/macosx-x86-64/x264-r2851-ba24899) (r2851) with same arguments runs successfully without any error.

----

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? → `Error: No logs.`
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):

    Transcode an MP4 fle into Blu-ray compatible h264 video using x264 and following the instructions at [x264bluray.com](http://www.x264bluray.com)

- What happened (include command output)

    ````
    x264 --bitrate 25000 --preset veryslow --tune animation --bluray-compat --vbv-maxrate 30000 --vbv-bufsize 30000 --level 4.1 --keyint 25 --open-gop --slices 4 --fake-interlaced --colorprim "bt709" --transfer "bt709" --colormatrix "bt709" --sar 1:1 --pass 1 -o out.264 in.mp4
    ````

- What you expected to happen

    `in.mp4` should have been transcoded into a new output file with the name `out.264`

- Step-by-step reproduction instructions (by running `brew install` commands)

    ````
    brew install x264
    x264 --bitrate 25000 --preset veryslow --tune animation --bluray-compat --vbv-maxrate 30000 --vbv-bufsize 30000 --level 4.1 --keyint 25 --open-gop --slices 4 --fake-interlaced --colorprim "bt709" --transfer "bt709" --colormatrix "bt709" --sar 1:1 --pass 1 -o out.264 in.mp4
    ````

**Comment by s172262** [comment]
Where can I get avisynth for MacOS?

**Comment by s172262** [comment]
Homebrew's `x264` was build with "Avisynth support (yes)" . It is need to build with `--disable-avs`.
```
$ x264 --help
x264 core:148 r2795 aaa9aa8
Syntax: x264 [options] -o outfile infile

Infile can be raw (in which case resolution is required),
  or YUV4MPEG (*.y4m),
  or Avisynth if compiled with support (yes).
  or libav* formats if compiled with lavf support (no) or ffms support (no).
Outfile type is selected by filename:
 .264 -> Raw bytestream
 .mkv -> Matroska
 .flv -> Flash Video
 .mp4 -> MP4 if compiled with GPAC or L-SMASH support (lsmash)
Output bit depth: 10 (configured at compile time)
```

**Comment by s172262** [comment]
Please test with https://github.com/s172262/homebrew-core/blob/master/Formula/x264.rb script.

**Comment by elmimmo** [comment]
With your fix, except for a [typo](https://github.com/s172262/homebrew-core/pull/1), x264 now works as expected.

**Comment by zmwangx** [comment]
The difference is that the official binary build of x264 is compiled with lavf support, while ours isn't, for very good reason actually: lavf, i.e., libavformat, is part of FFmpeg, so making x264 depend on FFmpeg would introduce a circular dependency.

**Comment by ilovezfs** [comment]
Going to close this since we can't introduce circular dependencies. @elmimmo please try using the ffmpeg x264 bindings instead.

**Comment by zmwangx** [comment]
For the record, please refer to https://ffmpeg.org/ffmpeg-all.html#libx264_002c-libx264rgb for FFmpeg's libx264 options. You can always specify an `x264` option with `x264opts` in case there's no native FFmpeg binding available.

https://trac.ffmpeg.org/wiki/Encode/H.264 is a beginner-friendly tutorial and IMO it's sufficient for most people.
