### ISSUE TITLE
rvm install ruby-2.2.4 on Yosemite: Unsupported Dependency

### ISSUE THREAD

**Issue by jetsgit** [Homebrew/homebrew-core#2019]
Not sure what formula was called, but error was generated when using 

```
rvm install ruby-2.2.4
```

The error generated:   **Error: Unsupported special dependency :perl** 
The following file was located, which may have been source of errors:

```
https://rubies.travis-ci.org/osx/10.10/x86_64/ruby-2.2.4.tar.bz2
```

Just reporting this per request of error message,  ruby-2.2.4 compiled
OK on my Yosemite macbook so I  have no problem

**Comment by DomT4** [comment]
Does `env | grep HOMEBREW_DEVELOPER` turn up a result for you?

As part of the install process `rvm` runs a `brew update`, and developers see warnings normal users wouldn't _(that almost always can be disregarded unless persistent)_, which this warning has typically been one of.

**Comment by jetsgit** [comment]
No  ```HOMEBREW_DEVELOPER```  in ```env```,  but I did take the opportunity to run brew update. This gave me a list of 'Updated Formulae'.

Some members of this list were in bold with a green checkmark after them.

Would that be indicating formulas that were actually updated?

Also noticed that ruby was not in that list.

I believe this issue can be closed?

**Comment by DomT4** [comment]
That's strange, perhaps `rvm` sets it or something. Unsure.

> Would that be indicating formulas that were actually updated?

This shows what formulae you already have installed have version updates pending. They won't actually be upgraded until you run `brew upgrade`.

> I believe this issue can be closed?

Seems safe enough unless you see a recurring error, yeah. Thanks for the report here.
