### ISSUE TITLE
pipenv's python version has an invalid code signature

### ISSUE THREAD

**Issue by AlexanderOMara** [Homebrew/homebrew-core#20193]
In short, `pipenv` includes a `libexec/bin/python` binary with a broken code signature, which makes certain security software like Little Snitch 4 treat it as a suspicious binary.

----

Obligatory checklist, though it seems irrelevant because it installs fine:

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? Yes, it's a specific file in a specific formula.
- [x] Ran `brew update` and retried your prior step? Yes.
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? Yes
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? It installs fine, so it says `Error: No logs.`
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? Irrelevant, it installs fine

----

- **What you were trying to do (and why):** Install `pipenv` for normal use.
- **What happened (include command output):** It installs fine, but one file has a broken code signature.
- **What you expected to happen:** A file with a broken code signature was unexpected.
- **Step-by-step reproduction instructions (by running `brew install` commands):**

```bash
$ brew install pipenv
$ codesign -vv /usr/local/Cellar/pipenv/8.3.1/libexec/bin/python
/usr/local/Cellar/pipenv/8.3.1/libexec/bin/python: invalid Info.plist (plist or signature have been modified)
In architecture: x86_64
$ codesign -vd /usr/local/Cellar/pipenv/8.3.1/libexec/bin/python
Executable=/usr/local/Cellar/pipenv/8.3.1/libexec/bin/python
Identifier=org.python.python
Format=Mach-O universal (i386 x86_64)
CodeDirectory v=20100 size=290 flags=0x0(none) hashes=4+3 location=embedded
Platform identifier=2
Signature size=4105
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=68
```

You can also find this file in the current bottle: https://homebrew.bintray.com/bottles/pipenv-8.3.1.sierra.bottle.tar.gz

It looks like an official python binary is included from somewhere, but without the `Info.plist` the code signature expects.

**Comment by ilovezfs** [comment]
This is a bug in Little Snitch. Take it up with them please. See https://github.com/Homebrew/homebrew-core/issues/18870

**Comment by AlexanderOMara** [comment]
@ilovezfs  It's not a bug in Little Snitch, it does what it's supposed to do correctly (see `codesign -vv` which confirms it is correct).

The problem is software shouldn't ever have a broken code signature...

**Comment by ilovezfs** [comment]
Little Snitch is choosing to raise user facing, false positive notifications that Apple itself does not raise. That is between you and Little Snitch.

**Comment by AlexanderOMara** [comment]
Forget Little Snitch.

You're in favor of shipping binaries that have broken signatures? I find that utterly bizarre, and security software should warn about that, because why would anything non-malicious choose to do that?

**Comment by ilovezfs** [comment]
@AlexanderOMara Homebrew is not signing anything. So you can take the question of broken signatures up with people who are signing something, which isn't us.

**Comment by AlexanderOMara** [comment]
> Homebrew is not signing anything

But it is breaking the code signature of the official python binary it is using (although I have not yet identified where the formula is getting it from).
