### ISSUE TITLE
Excessive build time for LLVM dependency on Mac

### ISSUE THREAD

**Issue by iamfullstop** [Homebrew/homebrew-core#202033]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
command `brew install llvm --verbose --debug`
its result at --> 🍺  /usr/local/Cellar/llvm/19.1.6: 8,041 files, 1.8GB, built in 342 minutes 30 seconds

Homebrew --> 4.4.12

host --> MacBook Pro (Early 2015)
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

i was try to install neovim with the hlep of it
it took so long before, and i used some flags installing that dependency oneby one ,  and i am still try in my background, 
there are many dependencies which takes soo long.  like rust is alsoo one of them . 

### What happened (include all command output)?

`🍺  /usr/local/Cellar/llvm/19.1.6: 8,041 files, 1.8GB, built in 342 minutes 30 seconds`

### What did you expect to happen?

install quickly as much as possible , my internet also good. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install neovim 
brew install llvm --verbose --debug # one of nvim dependency which took so long
```

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports at Homebrew.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.
