### ISSUE TITLE
After running "brew install node@22" my brew setup and PATH is broken

### ISSUE THREAD

**Issue by matthiasguentert** [Homebrew/homebrew-core#202042]
Brew was working fine until I ran `brew install node@22`, which broke my setup. Now brew is not on the PATH anymore. 

I did ran `/opt/homebrew/brew update` without any change. I DIDN'T follow `brew doctor` advice on purpose and fiddle with my path since it would further mess up my setup. 

## `brew gist-logs node@22`
```zsh
$ /opt/homebrew/bin/brew gist-logs node@22
Error: No logs.
```

## `brew config`
```zsh
$ brew
zsh: command not found: brew

$ /opt/homebrew/bin/brew config
HOMEBREW_VERSION: 4.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3001afe88112c13b5aafdd92e097680897060881
Last commit: 6 days ago
Branch: stable
Core tap JSON: 21 Dec 13:31 UTC
Core cask tap JSON: 21 Dec 13:31 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 14
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 14-core 64-bit arm_brava
Clang: 16.0.0 build 1600
Git: 2.39.5 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
Rosetta 2: false
```

## `brew doctor`

```zsh
$ /opt/homebrew/bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: /usr/bin occurs before /opt/homebrew/bin in your PATH.
This means that system-provided programs will be used instead of those
provided by Homebrew. Consider setting your PATH so that
/opt/homebrew/bin occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc

The following tools exist at both paths:
  openssl

Warning: Homebrew's "bin" was not found in your PATH.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
```

## `brew shellenv`

To me, the PATH looks broken. How can this be adjusted? How could this have happened? 

```zsh
$ /opt/homebrew/bin/brew shellenv
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
fpath[1,0]="/opt/homebrew/share/zsh/site-functions";
PATH="/opt/homebrew/bin:/opt/homebrew/sbin:"/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/share/dotnet:~/.dotnet/tools";"; export PATH;
[ -z "${MANPATH-}" ] || export MANPATH=":${MANPATH#:}";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

Tried installing node.js 

### What happened (include all command output)?

Unfortunately, I have lost the output of the `brew install node@22` command. When I now start a terminal I receive 

```zsh
$ /opt/homebrew/bin/brew gist-logs node@22
Error: No logs.
```

### What did you expect to happen?

node.js gets installed and brew keeps on working as before... 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install node@22
```

**Comment by SMillerDev** [comment]
Brew invocations can not adjust your path since that would be a security issue. It's much more likely that you missed something in the install of brew.

What does `cat ~/.zprofile | grep shellenv` say?
