### ISSUE TITLE
haproxy is incompatible with brew services

### ISSUE THREAD

**Issue by XueyangXu** [Homebrew/homebrew-core#20219]
if I run manually "haproxy -f /usr/local/etc/haproxy.cfg", everything is ok. But if I "brew services start haproxy", processes, named"haproxy" will be added continuously.
![image](https://user-images.githubusercontent.com/19919729/32362698-50aebb2c-c0a6-11e7-828d-f780fbaa67b6.png)

**Comment by mirokk** [comment]
I have the same issue.. after a couple of hours i have somewhere between 50 and 100 haproxy processes running
