### ISSUE TITLE
autoconf-archive 2024.10.16 breaks important macro `AX_CHECK_GL` that was working with previous 2023.02.20

### ISSUE THREAD

**Issue by hartwork** [Homebrew/homebrew-core#202234]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

This is from inside GitHub Actions with macOS 13.7.2 22H313 ([image `macos-13` 20241216.479](https://github.com/actions/runner-images/blob/macos-13/20241216.479/images/macos/macos-13-Readme.md)):

```console
# brew config
HOMEBREW_VERSION: 4.4.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: ad356d365837a691a52dfec32b3fb5f282f3aefc
Last commit: 2 weeks ago
Branch: stable
Core tap HEAD: 2f380d0268d5441b0dabd6030947bbd3c276c160
Core tap last commit: 8 days ago
Core tap JSON: 16 Dec 12:59 UTC
Core cask tap HEAD: 504b728c2f3fd3de169a17eed1826e5184091b42
Core cask tap last commit: 8 days ago
Core cask tap JSON: 16 Dec 12:59 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 15.0.0 build 1500
Git: 2.47.1 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 13.7.2-x86_64
CLT: 14.3.1.0.1.1683849156
Xcode: 15.2 => /Applications/Xcode_15.2.app/Contents/Developer
```

```console
# brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  openssl@1.1
  ruby@3.0

Warning: You have an unnecessary local Cask tap.
This can cause problems installing up-to-date casks.
Please remove it by running:
  brew untap homebrew/cask

Warning: You have an unnecessary local Core tap!
This can cause problems installing up-to-date formulae.
Please remove it by running:
 brew untap homebrew/core

Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core && git stash -u && git clean -d -f

Uncommitted files:
   M Formula/o/openssl@1.1.rb

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/prlcopy
  /usr/local/bin/python3.13t
  /usr/local/bin/python3.13t-config
  /usr/local/bin/python3.13t-intel64
  /usr/local/bin/python3t
  /usr/local/bin/python3t-config
  /usr/local/bin/python3t-intel64
  /usr/local/etc/bash_completion.d/prlctl
  /usr/local/etc/bash_completion.d/prlsrvctl
  /usr/local/share/man/man8/prl_convert.8
  /usr/local/share/man/man8/prl_disk_tool.8
  /usr/local/share/man/man8/prlcopy.8
  /usr/local/share/man/man8/prlctl.8
  /usr/local/share/man/man8/prlexec.8
  /usr/local/share/man/man8/prlsrvctl.8
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

macOS CI for libvisual started failing at https://github.com/Libvisual/libvisual/actions/runs/12469071221/job/34801479116?pr=373 due to the update of autoconf-archive at 1bd552f4702b5e589a490f40f6ee626567eba9d4 in HomeBrew showing the  symptom below.

### What happened (include all command output)?

```console
# cd "$(mktemp -d)"
# git clone --depth 1 --branch 0.4.x https://github.com/Libvisual/libvisual
# cd libvisual/libvisual-plugins/
# NOCONFIGURE=please ./autogen.sh
[..]
configure.ac:201: error: _AX_CHECK_GL_MANUAL_LIBS_GENERIC: argument must not be empty
lib/m4sugar/m4sh.m4:690: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
/usr/local/share/aclocal/ax_check_gl.m4:187: _AX_CHECK_GL_MANUAL_LIBS_GENERIC is expanded from...
lib/m4sugar/m4sh.m4:595: AS_CASE is expanded from...
/usr/local/share/aclocal/ax_check_gl.m4:253: AX_CHECK_GL is expanded from...
lib/m4sugar/m4sh.m4:697: AS_IF is expanded from...
configure.ac:201: the top level
autom4te: error: /usr/local/opt/m4/bin/m4 failed with exit status: 1
aclocal: error: /usr/local/Cellar/autoconf/2.72/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
[..]
```

The issue also showed with vanilla 2024.10.16 in Gentoo which is why Gentoo has patched the issue downstream post-release via patch stack https://dev.gentoo.org/~sam/distfiles/dev-build/autoconf-archive/autoconf-archive-2024.10.16-patches.tar.xz . Seems to need ~more than just~ upstream patch https://github.com/autoconf-archive/autoconf-archive/commit/427e226a2fe3980388abffd6de25ed6b9591cce3 — which I tried on top of 2024.10.16 and nothing more ~but it still failed — but I'm not sure yet what more it needs~.

CC @eli-schwartz @thesamesam @chenrui333

### What did you expect to happen?

autoreconf to continue working flawlessly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Please see above.
```

**Comment by hartwork** [comment]
@eli-schwartz the error was the same after…

- `sudo patch -n /usr/share/aclocal/ax_check_gl.m4 ~/Desktop/427e226a2fe3980388abffd6de25ed6b9591cce3.patch` and
- `rm -f aclocal.m4 configure`

…but maybe I forgot deleting some other important file for re-running.

**Comment by eli-schwartz** [comment]
> …but maybe I forgot deleting some other important file for re-running.

Most emphatically so. Please do a full `git clean -idx` which will also delete the entirety of the m4/ directory. aclocal.m4 just contains lines such as this one:

```
m4_include([m4/ax_check_gl.m4])
```

**Comment by hartwork** [comment]
@eli-schwartz my call to `patch` was broken apparantly. After fixing that and re-trying with a clean environment I can now confirm that patch https://github.com/autoconf-archive/autoconf-archive/commit/427e226a2fe3980388abffd6de25ed6b9591cce3 and just that **fixes the `AX_CHECK_GL` issue**.

**Comment by carlocab** [comment]
> ### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output
>
> ```shell
> Likely not relevant
> 
> ```

Please provide the output of `brew config` and `brew doctor`. We require this information from all bug reports at Homebrew, regardless of perceived relevance.

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.

**Comment by hartwork** [comment]
> Please provide the output of `brew config` and `brew doctor`.

@carlocab done, added at https://github.com/Homebrew/homebrew-core/issues/202234#issue-2756343178 above.

**Comment by hartwork** [comment]
@carlocab thanks for the fix :+1:
