### ISSUE TITLE
aws-shell is broken with awscli

### ISSUE THREAD

**Issue by jpz** [Homebrew/homebrew-core#20245]
# Summary

aws-shell needs to ensure it sets the path to its vendor directory, so as to execute the aws within there, rather than using the aws instance included the path, which typically is installed with the awscli package.

The error arises due to aws in the path being Python 3, and aws-shell setting PYTHONPATH environment variable to point to a number of Python 2 libraries, which cause awscli execution to fail.

Has awscli recently migrated from Python 2 to Python 3?  If so, this would cause the error to emerge.

---
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  

`Error: no logs.`

- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
% brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 612db13a6392da5fe03af3a762574af9c16ef113
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: N/A

% brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

Installed aws-shell, tried to run it.  Already had awscli installed.  Did some test commands inside aws-shell "s3 ls" and get errors reported from awscli, due to PYTHONPATH set up in aws-shell being Python 2 libraries, and awscli being a Python 3 package.

```
% aws-shell
Creating doc index in the background. It will be a few minutes before all documentation is available.
aws> s3 ls
Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/Cellar/aws-shell/0.2.0/libexec/vendor/lib/python2.7/site-packages/awscli/clidriver.py", line 35, in <module>
    from awscli.help import ProviderHelpCommand
  File "/usr/local/Cellar/aws-shell/0.2.0/libexec/vendor/lib/python2.7/site-packages/awscli/help.py", line 20, in <module>
    from docutils.core import publish_string
  File "/usr/local/Cellar/aws-shell/0.2.0/libexec/vendor/lib/python2.7/site-packages/docutils/__init__.py", line 112, in <module>
    class ApplicationError(StandardError):
NameError: name 'StandardError' is not defined
aws>
```
I uninstalled both, installed aws-shell alone.  aws-shell cannot find aws, so "s3 ls" etc reports aws not found.

```
% brew uninstall awscli aws-shell
Uninstalling /usr/local/Cellar/awscli/1.11.180_1... (4,159 files, 36.3MB)
Uninstalling /usr/local/Cellar/aws-shell/0.2.0... (3,386 files, 39.4MB)
% brew install aws-shell
==> Downloading https://homebrew.bintray.com/bottles/aws-shell-0.2.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/jasonz/Library/Caches/Homebrew/aws-shell-0.2.0.high_sierra.bottle.tar.gz
==> Pouring aws-shell-0.2.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/aws-shell/0.2.0: 2,793 files, 33.7MB
% aws-shell
Creating doc index in the background. It will be a few minutes before all documentation is available.
aws> s3 ls
/bin/sh: aws: command not found
aws>
```

- Possible remedies:

Specifically, aws-shell includes a copy of "aws" in the subdirectory `/usr/local/Cellar/aws-shell/0.2.0/libexec/vendor/bin` - but this is not used, because the PATH is not set up. 

To resolve the issue, aws-shell should be set to refer to the aws instance inside its own vendor directory (by setting the PATH as well as the PYTHONPATH)

This was tested:
```
% export PATH=/usr/local/Cellar/aws-shell/0.2.0/libexec/vendor/bin:$PATH
% aws-shell
aws> s3 ls
## successful contents omitted ##
aws>
```

# Formula additions or changes

I'm not familiar enough with maintaining a brew package to submit a PR on this, but hopefully this would be fairly easy to maintainers.

**Comment by ilovezfs** [comment]
@jpz thanks for reporting this. I'm going with the minimal fix for now, but may switch it over to python3 too at some point: https://github.com/Homebrew/homebrew-core/pull/20246

**Comment by ilovezfs** [comment]
@jpz this is fixed now if you `brew update` and `brew upgrade`.
