### ISSUE TITLE
SFML not installing dynamic libraries. 

### ISSUE THREAD

**Issue by JLP04** [Homebrew/homebrew-core#202490]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/JLP04/18f33840d16aa294ab8fa8e601087eee
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I was trying to link against the SFML library (assuming the dynamic library). 

### What happened (include all command output)?

My compiler wasn't able to find the library, so I investigated and discovered that the formula for SFML 3 is only installing the static libraries (.a) and not the dynamic libraries (.dylib). 

### What did you expect to happen?

I expected the formula to also install the dynamic libraries like it has in the past. (It looks like if you pass `-DBUILD_SHARED_LIBS=ON` to cmake, it'll compile the dynamic libraries but not the static. However, this causes the install command to fail because it can't find the static libraries. I have a feeling this is a cmake flag issue). 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install sfml`
Then, try to compile anything against SFML where you're actually using the `-l` flag to link against the library (i.e. `-lsfml-audio`).
```

**Comment by carlocab** [comment]
> ### Step-by-step reproduction instructions (by running `brew` commands)
> ```shell
> `brew install sfml`
> Then, try to compile anything against SFML where you're actually using the `-l` flag to link against the library (i.e. `-lsfml-audio`).
> ```

I don't think the steps you describe reproduces the failure you're having. The second step of these instructions is what is done by `brew test sfml`, see:

https://github.com/Homebrew/homebrew-core/blob/61d4bec811ae95c429f83362d170213777c49a63/Formula/s/sfml.rb#L69-L71

**Comment by JLP04** [comment]
> > ### Step-by-step reproduction instructions (by running `brew` commands)
> > ```shell
> > `brew install sfml`
> > Then, try to compile anything against SFML where you're actually using the `-l` flag to link against the library (i.e. `-lsfml-audio`).
> > ```
> 
> I don't think the steps you describe reproduces the failure you're having. The second step of these instructions is what is done by `brew test sfml`, see:
> 
> https://github.com/Homebrew/homebrew-core/blob/61d4bec811ae95c429f83362d170213777c49a63/Formula/s/sfml.rb#L69-L71

The test is passing `-L` but not `-l`. To my understanding, what that does is tells the linker where to find the libraries but does not ask the linker to actually link against any libraries. Thus, the linker doesn't search for something such as `libsfml-audio.dylib` which doesn't exist.

**Comment by carlocab** [comment]
> The test is passing `-L` but not `-l`. To my understanding, what that does is tells the linker where to find the libraries but does not ask the linker to actually link against any libraries. Thus, the linker doesn't search for something such as `libsfml-audio.dylib` which doesn't exist.

Good point; I misread that. In any case, using `-l` does use static libraries. See the snippet from `man ld` that I quoted above.

**Comment by JLP04** [comment]
It's still not linking against it though, I think it's because `sfml` names it's static libraries ending in -s (for example, `libsfml-audio.dylib` seems to be synonymous with `libsfml-audio-s.a` not `libsfml-audio.a` so the same `-l` will not work with only static libraries.

**Comment by carlocab** [comment]
So, shouldn't you be using `-lsfml-audio-s` to link instead?

**Comment by JLP04** [comment]
Technically, yes. I was just thinking this should maybe be looked into as it'll likely break a lot of existing build processes that use `-lsfml-audio` to link against the dynamic version.

**Comment by carlocab** [comment]
We're not touching the `.pc` files, so that looks like an upstream bug to me.

**Comment by JLP04** [comment]
I figured it might be but I wasn't sure if it was just the flags being passed to cmake. I'll open a ticket there then.

**Comment by carlocab** [comment]
> I figured it might be but I wasn't sure if it was just the flags being passed to cmake. I'll open a ticket there then.

Thanks; that'll be good.

I've opened #202492 to switch to a shared library build here anyway (but upstream should still fix their static library build).
