### ISSUE TITLE
`cfitsio` lost reentrant in recent updates

### ISSUE THREAD

**Issue by HaoxuanGuo** [Homebrew/homebrew-core#202429]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

brew config

```
HOMEBREW_VERSION: 4.4.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6ea9df68df4868ce12ea7c51c85b57dce514f2e8
Last commit: 2 days ago
Branch: stable
Core tap JSON: 25 Dec 12:12 UTC
Core cask tap JSON: 25 Dec 12:12 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.oDNjyHiqIl/org.xquartz:0
HOMEBREW_MAKE_JOBS: 10
all_proxy: socks5://127.0.0.1:18889
http_proxy: http://127.0.0.1:18888
https_proxy: http://127.0.0.1:18888
Homebrew Ruby: 3.3.6 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 16.0.0 build 1600
Git: 2.47.1 => /opt/homebrew/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-arm64
CLT: 16.2.0.0.1.1733547573
Xcode: 16.2
Rosetta 2: false
```

brew doctor
```
Your system is ready to brew.
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I try to use cfitsio but found `reentrant` compile flag is closed.

In [recent update](https://github.com/Homebrew/homebrew-core/commit/21a85533241e60150f652aed4da4481dd65a0c7c#diff-32720d7ce549b8a1c2795039af6e0cacae3cb20a303381ed608867ef86b13c57L27) of cfitsio, legacy `configure` was upgraded to `cmake`. but `--enable-reentrant` was deleted and no corresponding flag for cmake options (which I guess is `USE_PTHREADS`).

### What happened (include all command output)?

`cfitsio` is not thread safe.

### What did you expect to happen?

An corresponding flag for `--enable-reentrant` should be added and the cfitsio library should be thread safe.

### Step-by-step reproduction instructions (by running `brew` commands)

Sorry to no instructions but [this link](https://github.com/Homebrew/homebrew-core/commit/21a85533241e60150f652aed4da4481dd65a0c7c#diff-32720d7ce549b8a1c2795039af6e0cacae3cb20a303381ed608867ef86b13c57L27) due to the special problem.

**Comment by HaoxuanGuo** [comment]
Sorry to bother @chenrui333 and @SMillerDev, but regarding the update from PR #200851, would it be possible to look into a fix? I really appreciate your help!

**Comment by SMillerDev** [comment]
I won't be looking into a fix because as far as I can tell it's working.

Additionally, please don't tag volunteers to demand their attention no matter how important you think your bug is.

**Comment by HaoxuanGuo** [comment]
@SMillerDev I apologize for any inconvenience my previous message may have caused. I appreciate the time and effort you and the other volunteers put into this project. I understand your perspective and will be more mindful in the future. Thank you for your feedback!

**Comment by HaoxuanGuo** [comment]
I personally tried to compile it, and it's not as simple as just toggling a few compilation options; it seems to be due to version differences in the software itself. Therefore, I have closed this issue.

**Comment by carlocab** [comment]
It may be worth filing an issue upstream for this.

**Comment by d3v-null** [comment]
Hello,
I'm hosting a reentrant cfitsio on my own tap and it works. I could help write a pr for a reentrant cfitsio in homebrew core.
The only difference is adding `-DUSE_PTHREADS=1 -D_REENTRANT=1` to the cmake args.

```
brew tap mwatelescope/tap
brew install mwatelescope/tap/cfitsio_reentrant
```

**Comment by gromgit** [comment]
> The only difference is adding `-DUSE_PTHREADS=1 -D_REENTRANT=1` to the cmake args.

As a disinterested third party:
1. Is this of general benefit to `cfitsio` users?
2. Are there any downsides to making this the default for all users?

If the answers are "yes" and "no" respectively, then perhaps a PR should be raised to incorporate this change into the Homebrew core formula.
