### ISSUE TITLE
Traefik dashboard missing?

### ISSUE THREAD

**Issue by jdelker** [Homebrew/homebrew-core#202777]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 4.4.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6ea9df68df4868ce12ea7c51c85b57dce514f2e8
Last commit: 8 days ago
Branch: stable
Core tap JSON: 30 Dec 14:21 UTC
Core cask tap JSON: 30 Dec 14:21 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.KRA9Uk9jMN/org.xquartz:0
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 3.3.6 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.3.6/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 16.0.0 build 1600
Git: 2.47.1 => /usr/local/bin/git
Curl: 8.7.1 => /usr/bin/curl
macOS: 15.2-x86_64
CLT: 16.2.0.0.1.1733547573
Xcode: N/A
```

### Verification

- [X] My `brew doctor` output says `Your system is ready to brew.` and am still able to reproduce my issue.
- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.
- [X] I searched for recent similar issues at https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue and found no duplicates.

### What were you trying to do (and why)?

I installed the `traefik` package to establish a reverse proxy for some services.
Installation and general setup are ok.

However, the brewed package is obviously missing the dashboard UI component.
(See also [this discussion](https://community.traefik.io/t/traefik-dashboard-shows-dont-edit-files-in-this-directory-md/21352) on the traefik forum)

### What happened (include all command output)?

I provided traefik with this minimal configuration in a `traefik.yml`
```yaml
api:
  dashboard: true
  insecure: true
```
and started traefik with `/usr/local/opt/traefik/bin/traefik --configfile=/usr/local/etc/traefik/traefik.yml`.
By default, this opens the default entrypoints on port 80, 443 and 8080, which I successfully verified.

Port 8080 should expose the traefik dashboard at http://localhost:8080/dashboard/, but a GET request only returns
`DONT-EDIT-FILES-IN-THIS-DIRECTORY.md`.

From my research I would conclude, that the build traefik package is incomplete (see referenced post above).
Without any deeper knowledge in GO or the brew build process, I compared the [Github-Build-Workflows from the traefik](https://github.com/traefik/traefik/blob/master/.github/workflows/build.yaml) project with the [brew formula](https://github.com/Homebrew/homebrew-core/blob/c84f4007b5e2465c70912cd843c41de2958d29bb/Formula/t/traefik.rb). 
The first is explicitly including a "webui" build, which I can't find in the formula.

### What did you expect to happen?

An HTTP request on ' http://localhost:8080/dashboard/` should show the traefik dashboard.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install traefik

cat <<EOF > /tmp/traefik.yml
api:
  dashboard: true
  insecure: true
EOF

/usr/local/opt/traefik/bin/traefik --configfile=/tmp/traefik.yml &

curl -v -k http://localhost:8080/dashboard/
```

**Comment by jdelker** [comment]
For reference, the full `curl`output:
```
curl -v -k http://localhost:8080/dashboard/
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /dashboard/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Security-Policy: frame-src 'self' https://traefik.io https://*.traefik.io;
< Content-Type: text/html; charset=utf-8
< Date: Mon, 30 Dec 2024 15:32:04 GMT
< Content-Length: 169
<
<!doctype html>
<meta name="viewport" content="width=device-width">
<pre>
<a href="DONT-EDIT-FILES-IN-THIS-DIRECTORY.md">DONT-EDIT-FILES-IN-THIS-DIRECTORY.md</a>
</pre>
```

**Comment by alebcay** [comment]
Thanks for the detailed report, this should be fixed now with https://github.com/Homebrew/homebrew-core/pull/202791. You should be able to pick up the rebuilt version with the dashboard working via `brew upgrade traefik`. Please advise if you are still seeing the issue and we can re-open this.

**Comment by jdelker** [comment]
The update to 3.2.3_1 has resolved the issue.
Thanks for the prompt fixing.
