### ISSUE TITLE
Error happens when installing libgcrypt on OS X 10.12

### ISSUE THREAD

**Issue by vinanny** [Homebrew/homebrew-core#2030]
### Bug reports:

Error happens when installing libgcrypt.

Log as below:
==> Installing libgcrypt
==> Downloading https://gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.7.1.tar.bz2
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgcrypt/1.7.
==> make
==> make install
==> make check
Last 15 lines from /Users/shaoyun/Library/Logs/Homebrew/libgcrypt/04.make:
HMAC_SHA3_384           10ms     0ms    10ms
HMAC_SHA3_512           10ms    20ms    10ms
/bin/sh: line 1: 29125 Segmentation fault: 11  GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: benchmark
/bin/sh: line 1: 29143 Segmentation fault: 11  GCRYPT_IN_REGRESSION_TEST=1 ${dir}$tst
FAIL: bench-slope
SKIP: hashtest-256g
======================================
4 of 25 tests failed
(1 test was not run)
Please report to http://bugs.gnupg.org
======================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

**Comment by vcarus** [comment]
I have the same issue here.

**Comment by jeromesavin** [comment]
Same issue too.

**Comment by MikeMcQuaid** [comment]
Sorry but none of you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting). As this is a "developer preview" also consider submitting a pull request to fix this.

**Comment by DomT4** [comment]
Please see (and check for 10.12 issues in future) https://github.com/Homebrew/homebrew-core/issues/1957. It's a known issue, that probably should be reported to Werner upstream.

If he says there's a fix or it's something we can ignore we can work with that, but I'd rather not blindly wipe `make check` out on 10.12 without some clarification that's a safe step, given the nature of what `libgcrypt` does.
