### ISSUE TITLE
wxWidgets fails (--devel) on High Sierra

### ISSUE THREAD

**Issue by dcoeurjo** [Homebrew/homebrew-core#20319]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- ~[ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to install  wxwidgets 3.1 using the --devel flag

- What happened (include command output)

Build issue related to missing <Appkit/Appkit.h> (see https://gist.github.com/anonymous/f5b2e74e5a9735ce296f1b508e94e19e)

- What you expected to happen

Expected to build.

- Step-by-step reproduction instructions (by running `brew install` commands)

        brew install wxwidgets --devel

got:

```
[...]
/private/tmp/wxmac-20171106-79418-d89h37/wxWidgets-3.1.0/bk-deps clang++ -mmacosx-version-min=10.13 -c -o coredll_artprov.o  -D__WXOSX_COCOA__      -DWXBUILDING      -I./src/regex  -DWXUSINGDLL -DWXMAKINGDLL_CORE -DwxUSE_BASE=0 -dynamic -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -Wno-deprecated-declarations -D_FILE_OFFSET_BITS=64 -I/private/tmp/wxmac-20171106-79418-d89h37/wxWidgets-3.1.0/lib/wx/include/osx_cocoa-unicode-3.1 -I./include -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=1 -O2 -fno-common -fvisibility=hidden -fvisibility-inlines-hidden ./src/common/artprov.cpp
./src/osx/cocoa/tooltip.mm:27:14: fatal error: 'Appkit/Appkit.h' file not found
    #include <Appkit/Appkit.h>
             ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [coredll_cocoa_tooltip.o] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by ilovezfs** [comment]
@DomT4 @fxcoudert I thought `devel` was fine?

**Comment by DomT4** [comment]
It was. As far as I recall, this is an issue we hadn't seen before. `AppKit` is still very much present on High Sierra so I'm not immediately sure what's going on there.

**Comment by ilovezfs** [comment]
Ah, OK.

**Comment by DomT4** [comment]
Will see if I can repro in a sec.

**Comment by DomT4** [comment]
Nope.
```
==> Summary
🍺  /usr/local/Cellar/wxmac/3.1.0_1: 812 files, 24.5MB, built in 6 minutes 53 seconds
```

This is my config:
```
HOMEBREW_VERSION: 1.3.6-204-gccf933f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ccf933f31c11adf1fd96df45f7056e3dc8a59824
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8ec727e557700163171e10c5d31f22040a59449a
Core tap last commit: 78 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /usr/local/var/homebrewcache
HOMEBREW_CASK_OPTS: --require-sha
HOMEBREW_DEVELOPER: 1
HOMEBREW_GIT: /usr/local/opt/git/bin/git
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /usr/local/var/homebrewcache/logs
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_SANDBOX: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/opt/git/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/var/rbenv/shims/ruby => /usr/local/var/rbenv/versions/2.4.2/bin/ruby
Java: 9.0.1
macOS: 10.13.2-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

Interesting but unrelated:
```
/usr/bin/sandbox-exec -f /tmp/homebrew20171107-83378-r8cy7q.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wxmac.rb -s -v --devel --devel
```
Apparently `--devel` is getting passed twice. Not immediately sure what's going on there either, heh.

**Comment by ilovezfs** [comment]
>Apparently --devel is getting passed twice.

It means it's extra unstable.

**Comment by DomT4** [comment]
Also can't reproduce this if I switch over `xcode-select` to point to the CLT instead of Xcode, so that rules that one out. OP has an unusually large amount of CPU cores which makes me wonder if it could be a parallelisation issue: `CPU: 12-core 64-bit ivybridge`.

**Comment by dcoeurjo** [comment]
well... ```--devel``` is fine on my laptop but not on my MacPro (same OS version).

**Comment by ilovezfs** [comment]
@dcoeurjo something is probably messed up with your Xcode.

What's the output of
```
xcode-select -p
```

**Comment by dcoeurjo** [comment]
Nothing special... 
```
/Applications/Xcode.app/Contents/Developer
```

**Comment by ilovezfs** [comment]
Have you launched it and accepted the latest license agreement?

**Comment by dcoeurjo** [comment]
sure. 

(I don't see why to could be a problem but my /Applications/Xcode.app is a symlink to and Xcode on another drive..)

**Comment by ilovezfs** [comment]
Yeah that could be it. Can you try putting Xcode.app on the main drive?

**Comment by DomT4** [comment]
Any chance that drive has spaces in the name? IIRC that’s been problematic in the past.

**Comment by dcoeurjo** [comment]
I'm using Xcode for daily code purposes and it's fine.

**Comment by dcoeurjo** [comment]
ok.. i'm trying

**Comment by dcoeurjo** [comment]
ok done. No more "Appkit" issue.. that's a bit weird (no spaces in my drive name) but the problem was there.

**Comment by ilovezfs** [comment]
I'm glad you were able to get it working.
