### ISSUE TITLE
Failed during: /usr/local/bin/brew update --force when install brew

### ISSUE THREAD

**Issue by panjizeith** [Homebrew/homebrew-core#20393]
I have problem with my brew because suddenly command brew not found in terminal. So I uninstall and try to reinstall again using  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)

It show error 
Failed during: /usr/local/bin/brew update --force

The log
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at ccf933f31 Merge pull request #3435 from MikeMcQuaid/auto-update-checked
/usr/local/Homebrew/Library/Homebrew/PATH.rb:71:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/Homebrew/Library/Homebrew/PATH.rb:71:in `block in parse'
	from /usr/local/Homebrew/Library/Homebrew/PATH.rb:71:in `each'
	from /usr/local/Homebrew/Library/Homebrew/PATH.rb:71:in `flat_map'
	from /usr/local/Homebrew/Library/Homebrew/PATH.rb:71:in `parse'
	from /usr/local/Homebrew/Library/Homebrew/PATH.rb:8:in `initialize'
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:325:in `new'
	from /usr/local/Homebrew/Library/Homebrew/utils.rb:325:in `which_all'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:5:in `find_gpg'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:15:in `gpg'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:22:in `<class:Gpg>'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:3:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/requirements/gpg2_requirement.rb:2:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/requirements.rb:3:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:5:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/software_spec.rb:6:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:10:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/readall.rb:1:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/tap.rb:3:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/compat/tap.rb:1:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/compat.rb:2:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:63:in `<top (required)>'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:21:in `<main>'
Failed during: /usr/local/bin/brew update --force

And here is my echo $PATH result
/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin:“/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:??:/usr/local/Caskroom/android-sdk/3859397,26.0.2//build-tools:/usr/local/Caskroom/android-sdk/3859397,26.0.2//platform-tools:/usr/local/Caskroom/android-sdk/3859397,26.0.2//tools

Please Help
Thank You

**Comment by ilovezfs** [comment]
Your PATH variable's value does not look valid. Can you please

```
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

and then try again?

**Comment by ilovezfs** [comment]
@panjizeith You're welcome. You'll need to figure out which of your profile files (probably ~/.bash_profile) has the "bad" PATH variable set to make this problem go away permanently.
