### ISSUE TITLE
pkg-config config for opencv is wrong and unusable.

### ISSUE THREAD

**Issue by staviq** [Homebrew/homebrew-core#20406]
File `/usr/local/lib/pkgconfig/opencv.pc` has all the linker flags wrong, and it makes pkg-config unusable for opencv.

example:

it is:
`-llibopencv_stitching.3.3.1.dylib`

it should be:
`-lopencv_stitching.3.3.1`

etc.

Fresh install High Sierra.

`$ brew config
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ade735b9e95352f1731445bad505d920c9521969
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.11 => /opt/X11`

**Comment by ilovezfs** [comment]
Please report this upstream: https://github.com/opencv/opencv/issues

**Comment by ilovezfs** [comment]
@staviq this is now fixed if you `brew update` and `brew reinstall opencv`
