### ISSUE TITLE
Failing to update libp11 'cannot create regular file'

### ISSUE THREAD

**Issue by Vad1mo** [Homebrew/homebrew-core#20419]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I want to submit a PR #20409 that updates libp11 0.2.8 to 0.4.7 however I have some problems running the installation in locally. 

```
brew pull https://github.com/Homebrew/homebrew-core/pull/20409
brew install --interactive libp11
```

make install complains about **cannot create regular file ... Operation not permitted** 
It seems that sudo rights are needed, but I am not sure if its the correct way to do so.

```
make install     
Making install in src
 /usr/local/bin/gmkdir -p '/usr/local/Cellar/openssl/1.0.2m/lib/engines'
 /usr/local/bin/gmkdir -p '/usr/local/lib'
 /usr/local/bin/gmkdir -p '/usr/local/include'
 /bin/sh ../libtool   --mode=install /usr/local/bin/ginstall -c   libp11.la '/usr/local/lib'
 /bin/sh ../libtool   --mode=install /usr/local/bin/ginstall -c   pkcs11.la '/usr/local/Cellar/openssl/1.0.2m/lib/engines'
 /usr/local/bin/gmkdir -p '/usr/local/lib/pkgconfig'
 /usr/local/bin/ginstall -c -m 644 libp11.h p11_err.h '/usr/local/include'
 /usr/local/bin/ginstall -c -m 644 libp11.pc '/usr/local/lib/pkgconfig'
ginstall: cannot create regular file '/usr/local/include/libp11.h': Operation not permitted
ginstall: cannot create regular file '/usr/local/include/p11_err.h': Operation not permitted
make[2]: *** [install-includeHEADERS] Error 1
make[2]: *** Waiting for unfinished jobs....
ginstall: cannot create regular file '/usr/local/lib/pkgconfig/libp11.pc': Operation not permitted
make[2]: *** [install-pkgconfigDATA] Error 1
libtool: install: /usr/local/bin/ginstall -c .libs/libp11.2.dylib /usr/local/lib/libp11.2.dylib
libtool: install: /usr/local/bin/ginstall -c .libs/pkcs11.dylib /usr/local/Cellar/openssl/1.0.2m/lib/engines/pkcs11.dylib
ginstall: cannot create regular file '/usr/local/lib/libp11.2.dylib': Operation not permitted
ginstall: cannot create regular file '/usr/local/Cellar/openssl/1.0.2m/lib/engines/pkcs11.dylib': Operation not permitted
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: *** [install-enginesexecLTLIBRARIES] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

```

**Comment by mtrojnar** [comment]
AFAIK you should have write permissions to /usr/local to use Homebrew.  It is your Homebrew installation that seems to be broken, and not the stunnel package.

**Comment by fxcoudert** [comment]
Please run `brew doctor` and fix all warnings there. Follow the issue template's instructions, and post the output of `brew config` and `brew doctor`.
