### ISSUE TITLE
Unable to install Homebrew -> Cannot type in password when requested

### ISSUE THREAD

**Issue by briglm** [Homebrew/homebrew-core#20454]
Hi

I am trying to install homebrew using the terminal. I can put in the command promt, click enter, but when it gets to the password I can't seem to type anything in, except Enter. After 3 times it fails (because I have a blank for a password). Is there any way around this, or another way to install?

**Comment by ilovezfs** [comment]
Set a password for your user account. Type the password when prompted. It will not show anything that you type in (so that someone looking over your shoulder can't read the password!). Press enter after you type in the password.
