### ISSUE TITLE
syncthing 0.13.7 binary not signed

### ISSUE THREAD

**Issue by metasieben** [Homebrew/homebrew-core#2048]
Seems like the syncthing binary in version 0.13.7 is unsigned: 

`$ codesign -vvv /usr/local/Cellar/syncthing/0.13.?/bin/syncthing`
`/usr/local/Cellar/syncthing/0.13.6/bin/syncthing: valid on disk`
`/usr/local/Cellar/syncthing/0.13.6/bin/syncthing: satisfies its Designated Requirement`
`/usr/local/Cellar/syncthing/0.13.7/bin/syncthing: invalid signature (code or signature have been modified)`

could you please sign the binary?
thx.

**Comment by DomT4** [comment]
We don't sign binaries. This is the case for everything Homebrew distributes, as far as I'm aware, aside perhaps `homebrew/binary` and `Caskroom/cask` where upstream pre-compiled versions are used instead of building from source.

I'm not sure how you're actually hitting this:

```
~> brew install syncthing
==> Summary
🍺  /usr/local/Cellar/syncthing/0.13.7: 6 files, 14.8M
~> codesign -vvv `which syncthing`
/usr/local/bin/syncthing: code object is not signed at all
In architecture: x86_64
```
How did you install this?

**Comment by metasieben** [comment]
I didn't do anything out of the ordinary.
`brew install syncthing`
and then
`brew upgrade syncthing`

**Comment by ilovezfs** [comment]
You can sign the binary yourself with a certificate from Apple or a self-signed certificate, but this outside of Homebrew's scope.

For more information see https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW2
