### ISSUE TITLE
tinyproxy fails to build on 10.13

### ISSUE THREAD

**Issue by hmage** [Homebrew/homebrew-core#20500]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 

https://gist.github.com/05909f5d47c7f7fb460e7bb5403a7d81

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Tried to install `tinyproxy` on fresh OSX 10.13
- What happened (include command output)
```hmage@whmd:~$ brew install tinyproxy
==> Downloading https://github.com/tinyproxy/tinyproxy/releases/download/1.8.4/tinyproxy-1.8.4.tar.xz
Already downloaded: /Users/hmage/Library/Caches/Homebrew/tinyproxy-1.8.4.tar.xz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/tinyproxy/1.8.4 --localstatedir=/usr/local/var --sysco
==> make install
Last 15 lines from /Users/hmage/Library/Logs/Homebrew/tinyproxy/02.make:
 /usr/bin/install -c -m 644 debug.html default.html stats.html '/usr/local/Cellar/tinyproxy/1.8.4/share/tinyproxy'
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in etc
sed -e 's|@bindir[@]|/usr/local/Cellar/tinyproxy/1.8.4/bin|g' -e 's|@datadir[@]|/usr/local/Cellar/tinyproxy/1.8.4/share|g' -e 's|@datarootdir[@]|/usr/local/Cellar/tinyproxy/1.8.4/share|g' -e 's|@sysconfdir[@]|/usr/local/etc|g' -e 's|@localstatedir[@]|/usr/local/var|g' -e 's|@pkgdatadir[@]|/usr/local/Cellar/tinyproxy/1.8.4/share/tinyproxy|g' -e 's|@prefix[@]|/usr/local/Cellar/tinyproxy/1.8.4|g' -e 's|@TINYPROXY_STATHOST[@]|tinyproxy.stats|g' ../etc/tinyproxy.conf.in > tinyproxy.conf.tmp
make[2]: Nothing to be done for `install-data-am'.
 .././install-sh -c -d '/usr/local/etc'
 /usr/bin/install -c -m 644 tinyproxy.conf '/usr/local/etc'
Making install in docs
Making install in man5
/usr/local/opt/asciidoc/bin/a2x -d manpage -f manpage -L tinyproxy.conf.txt
env: python2: No such file or directory
make[2]: *** [tinyproxy.conf.5] Error 127
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html
```
- What you expected to happen
Tinyproxy would build and install successfully.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install tinyproxy`

I even tried `brew install python2` but the same error persists, it somehow can't find `python2` in `PATH`.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
```
perl -p -i -e "s/python2/python/" /usr/local/Cellar/asciidoc/8.6.10/bin/a2x.py
```
will fix it.

**Comment by hmage** [comment]
Alright, that error message disappeared, build works.

Thanks!

**Comment by JCount** [comment]
Closing this as resolved. 👍
