### ISSUE TITLE
ffmpeg does not install on 10.13 when built with `--with-sdl2`

### ISSUE THREAD

**Issue by maelp** [Homebrew/homebrew-core#20506]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

installing ffmpeg with sdl2 to get ffplay

- What happened (include command output)

```
=> ./configure --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-p
Last 15 lines from /Users/primet/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-ffplay
--enable-libmp3lame
--enable-libx264
--enable-libxvid
--enable-opencl
--enable-videotoolbox
--disable-lzma

ERROR: libx264 not found
```

- What you expected to happen

the formula should build because I did `brew uninstall x264 && brew install x264` and it worked, but it seems to come from the compilation step of ffmpeg which has type errors with `uint8_t`

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install ffmpeg --with-sdl2`

I did a migration from my previous laptop to my new laptop, which kept the same OS but changed the processor, and some brew packages did not work anymore, so I did a `brew bundle dump; brew uninstall all ; brew bundle` to reinstall, and some packages do not work with errors about unknown type `uint8_t`

when I do `brew install -vd ffmpeg --with-sdl2` and I look at the `config.log` in the build I get this:

```
BEGIN /tmp/ffconf.L54Qc1ov/test.c
    1	#include <stdint.h>
    2	#include <x264.h>
    3	#include <stdint.h>
    4	long check_x264_encoder_encode(void) { return (long) x264_encoder_encode; }
    5	int main(void) { int ret = 0;
    6	 ret |= ((intptr_t)check_x264_encoder_encode) & 0xFFFF;
    7	return ret; }
END /tmp/ffconf.L54Qc1ov/test.c
clang -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I$(SRC_PATH)/compat/dispatch_semaphore -DPIC -std=c11 -fomit-frame-pointer -fPIC -c -o /tmp/ffconf.L54Qc1ov/test.o /tmp/ffconf.L54Qc1ov/test.c
In file included from /tmp/ffconf.L54Qc1ov/test.c:2:
/usr/local/include/x264.h:40:4: warning: You must include stdint.h or inttypes.h before x264.h [-W#warnings]
#  warning You must include stdint.h or inttypes.h before x264.h
   ^
/usr/local/include/x264.h:110:5: error: unknown type name 'uint8_t'
    uint8_t *p_payload;
    ^
/usr/local/include/x264.h:351:5: error: unknown type name 'uint8_t'
    uint8_t     cqm_4iy[16];        /* used only if i_cqm_preset == X264_CQM_CUSTOM */
    ^
/usr/local/include/x264.h:352:5: error: unknown type name 'uint8_t'
    uint8_t     cqm_4py[16];
    ^
/usr/local/include/x264.h:353:5: error: unknown type name 'uint8_t'
    uint8_t     cqm_4ic[16];
    ^
/usr/local/include/x264.h:354:5: error: unknown type name 'uint8_t'
```

so it seems that `x254.h` does not include some header

```
#  warning You must include stdint.h or inttypes.h before x264.h
```

I have a long output from `brew doctor` because I guess I uninstalled some binaries from brew but the headers were kept (not sure how to clean those)

```
 /usr/local/include/cloog.h
  /usr/local/include/atomic.h
  /usr/local/include/deprecated/ast_int.h
  /usr/local/include/deprecated/aff_int.h
  /usr/local/include/deprecated/polynomial_int.h
  /usr/local/include/deprecated/val_int.h
  /usr/local/include/deprecated/int.h
  /usr/local/include/deprecated/mat_int.h
  /usr/local/include/deprecated/vec_int.h
  /usr/local/include/deprecated/set_int.h
  /usr/local/include/deprecated/union_map_int.h
  /usr/local/include/deprecated/constraint_int.h
  /usr/local/include/deprecated/map_int.h
  /usr/local/include/deprecated/ilp_int.h
  /usr/local/include/deprecated/point_int.h
  /usr/local/include/gaiaexif.h
```

**Comment by maelp** [comment]
A few other brew seem to have the problem

```
==> Installing gnuplot --with-cairo --without-lua --with-wxmac --with-x11
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.1/gnuplot-5.2.1.tar.gz
==> Downloading from https://freefr.dl.sourceforge.net/project/gnuplot/gnuplot/5.2.1/gnuplot-5.2.1.tar.gz
==> Downloading http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.5.tgz
==> ./configure --prefix=/private/tmp/gnuplot-20171110-51049-1fh86qq/gnuplot-5.2.1/libcerf --enable-static --disable-shared
==> make install
Last 15 lines from /Users/primet/Library/Logs/Homebrew/gnuplot/02.make:
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/resource.h:216:2: error: unknown type name 'uint64_t'
        uint64_t ri_wired_size;
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/resource.h:217:2: error: unknown type name 'uint64_t'
        uint64_t ri_resident_size;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [err_fcts.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
mv -f .deps/w_of_z.Tpo .deps/w_of_z.Plo
mv -f .deps/erfcx.Tpo .deps/erfcx.Plo
mv -f .deps/im_w_of_x.Tpo .deps/im_w_of_x.Plo
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html

Installing gnuplot has failed!
```

**Comment by maelp** [comment]
I do have a `/usr/include/stdint.h` file with the types

```
/*
 * Copyright (c) 2000-2010 Apple Inc.
 * All rights reserved.
 */

#ifndef _STDINT_H_
#define _STDINT_H_

#if __LP64__
#define __WORDSIZE 64
#else
#define __WORDSIZE 32
#endif

/* from ISO/IEC 988:1999 spec */

/* 7.18.1.1 Exact-width integer types */
#include <sys/_types/_int8_t.h>
#include <sys/_types/_int16_t.h>
#include <sys/_types/_int32_t.h>
#include <sys/_types/_int64_t.h>

#include <_types/_uint8_t.h>
#include <_types/_uint16_t.h>
#include <_types/_uint32_t.h>
#include <_types/_uint64_t.h>

/* 7.18.1.2 Minimum-width integer types */
typedef int8_t           int_least8_t;
typedef int16_t         int_least16_t;
typedef int32_t         int_least32_t;
typedef int64_t         int_least64_t;
typedef uint8_t         uint_least8_t;
typedef uint16_t       uint_least16_t;
typedef uint32_t       uint_least32_t;
typedef uint64_t       uint_least64_t;


```

**Comment by ilovezfs** [comment]
you didn't post brew config, brew doctor, or gist-logs as directed in the issue template so it's hard to help you.

**Comment by maelp** [comment]
There is also a `/usr/local/include/stdint.h` which seems empty, could it be the issue?

```
#ifndef _ISL_INCLUDE_ISL_STDINT_H
#define _ISL_INCLUDE_ISL_STDINT_H 1
#ifndef _GENERATED_STDINT_H
#define _GENERATED_STDINT_H "isl 0.18"
/* generated using gnu compiler Apple LLVM version 8.0.0 (clang-800.0.42.1) */
#define _STDINT_HAVE_STDINT_H 1
#include <stdint.h>
#endif
#endif
```

**Comment by maelp** [comment]
@ilovezfs the `brew doctor` is long and is mostly weird headers which seem to have been kept from the previous installation, I added a few

`brew config`

```
HOMEBREW_VERSION: 1.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 270b752f5d9d218bfbed6fe85b6974fa653fb25f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8b185c7640ca3ebc05d81e9c0e0cec9205a58f3c
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/primet/.rvm/rubies/ruby-2.2.0/bin/ruby
Java: 1.8.0_131, 1.8.0_05
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: 9.0.1.0.1.1506734476
X11: 2.7.9 => /opt/X11

```

**Comment by maelp** [comment]
`brew gist-logs ffmpeg --with-sdl2`
<https://gist.github.com/790075b5c548945132732d2cb476d8d3>

**Comment by maelp** [comment]
Actually `brew doctor` shows `/usr/local/include/stdint.h` as an undesired header, not sure why it was there, I can remove it and see

**Comment by maelp** [comment]
After removing the file it goes farther but now shows:

```
ERROR: videotoolbox requested but not found
```

**Comment by ilovezfs** [comment]
You're probably best off clearing out /usr/local entirely and starting over with brew bundle.

```
mkdir ~/homebrew-old-20171110
sudo mv /usr/local/* ~/homebrew-old-20171110/
sudo mv /usr/local/.* ~/homebrew-old-20171110/
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
and then brew bundle.

**Comment by maelp** [comment]
Thanks, is it safe to remove everything from /usr/local? I thought that Python package installs and other could be there?

I did a clean reinstall of homebrew but it did not help, I'm removing all the files from `brew doctor` and reinstalling all packages to see

**Comment by ilovezfs** [comment]
It's safe in that everything in there should be replaceable one way or another. Also you're just moving the files not deleting them.

**Comment by ilovezfs** [comment]
>I'm removing all the files from brew doctor and reinstalling all packages to see

yes that should work though it's a bit labor intensive :)

**Comment by maelp** [comment]
I did a python script :)

**Comment by ilovezfs** [comment]
fancy

**Comment by maelp** [comment]
It is progressing, now I get this when building `ffmpeg` although I reinstalled `brew install libav`

```
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-p
==> make install
Last 15 lines from /Users/primet/Library/Logs/Homebrew/ffmpeg/02.make:
CC	libavdevice/alldevices.o
CC	libavdevice/avdevice.o
OBJCC	libavdevice/avfoundation.o
CC	libavdevice/lavfi.o
CC	libavdevice/reverse.o
CC	libavdevice/sdl2.o
CC	libavdevice/utils.o
CC	libavdevice/xcbgrab.o
libavdevice/xcbgrab.c:25:10: fatal error: 'xcb/xcb.h' file not found
#include <xcb/xcb.h>
         ^~~~~~~~~~~
CC	libavfilter/aeval.o
1 error generated.
make: *** [libavdevice/xcbgrab.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by maelp** [comment]
`brew gist-logs ffmpeg --with-sdl2`
https://gist.github.com/d291b9fe5d4030b19b55ec77d1726ca6

**Comment by ilovezfs** [comment]
probably need to reinstall xquartz or zap it

**Comment by maelp** [comment]
what do you mean by "zap it"? remove a previous version?

**Comment by ilovezfs** [comment]
`brew cask zap xquartz` should remove x11

**Comment by maelp** [comment]
Thanks:

- reinstalling XQuartz did not work
- removing XQuartz did work, then I reinstalled it

**Comment by ilovezfs** [comment]
I'm glad you were able to get it sorted out!
