### ISSUE TITLE
brew install postgresql@9.6 on latest version of homebrew compiles without SSL support

### ISSUE THREAD

**Issue by dnasseri** [Homebrew/homebrew-core#20516]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Installing postgres with SSL mode enabled
- What happened (include command output)
```
After installing postgres using the following command:
⋊> ~ brew install postgresql@9.6                                                                                                                             15:02:04
==> Downloading https://homebrew.bintray.com/bottles/postgresql@9.6-9.6.6.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring postgresql@9.6-9.6.6.high_sierra.bottle.tar.gz
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/legacy-homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.0) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/upgrading.html

To migrate existing data from a previous minor version (9.0-9.5) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/pgupgrade.html

  You will need your previous PostgreSQL installation from brew to perform `pg_upgrade`.
    Do not run `brew cleanup postgresql@9.6` until you have performed the migration.

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'set -g fish_user_paths "/usr/local/opt/postgresql@9.6/bin" $fish_user_paths' >> ~/.config/fish/config.fish

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/postgresql@9.6/lib
    CPPFLAGS: -I/usr/local/opt/postgresql@9.6/include


To have launchd start postgresql@9.6 now and restart at login:
  brew services start postgresql@9.6
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgresql@9.6 start
==> Summary
🍺  /usr/local/Cellar/postgresql@9.6/9.6.6: 3,273 files, 36.8MB
[I] ⋊> ~ brew services start postgresql@9.6                                                                                                                      15:03:04
==> Successfully started `postgresql@9.6` (label: homebrew.mxcl.postgresql@9.6)
```
I ran a local rails server with the DATABASE_URL pointing to a postgres database with ssl mode required. Unfortunately since the upgrade to postgres 9.6.5 (previously on version 9.4) attempting to connect a local rails server to the remote database using the following command `DATABASE_URL=<database-url> bundle exec rails c` yields an error. I have included the first couple lines of stack trace below just for context:

```
Called from /Users/dean.nasseri/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:238:in `block in load_dependency'
/Users/dean.nasseri/.rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize': sslmode value "require" invalid when SSL support is not compiled in (PG::ConnectionBad)
```
If I am reading this correctly, this is telling me that my local version of postgres was compiled without SSL enabled. I am running the rails server locally on the latest version of Mac OSX high sierra. Has this issue been reported to you folks, and do you know of any workarounds? It's weird because homebrew does install openssl in the postgres installation process, but it appears that the compiled postgres version doesn't know about it.

- What you expected to happen
Posgresql is installed and compiled with SSL support enabled.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install postgresql@9.6`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by DomT4** [comment]
Certainly looks like it should be there:

```
checking for CRYPTO_new_ex_data in -lcrypto... yes
checking for SSL_new in -lssl... yes
checking for SSL_get_current_compression... yes
checking for OPENSSL_init_ssl... no
checking for BIO_get_data... no
checking for BIO_meth_new... no
checking for ASN1_STRING_get0_data... no
checking for RAND_OpenSSL... no
checking for CRYPTO_lock... yes

checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes

configure: using CPPFLAGS=-I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libxml2
configure: using LDFLAGS=-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -Wl,-dead_strip_dylibs

~> /usr/local/Cellar/postgresql@9.6/9.6.6/bin/pg_config --libs
-lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm
```

**Comment by dnasseri** [comment]
@DomT4 thank you for getting back to me so quickly, and for providing that command. I was looking for a way to see what postgresql was compiled with. When issuing the same command, I do see the same thing: ```
[I] ⋊> ~ /usr/local/Cellar/postgresql@9.6/9.6.6/bin/pg_config --libs                                                                                             15:30:14
-lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm
``` 

So now I am doubly confused. I am confident that the remote database does have SSL enabled as well (it is being managed by Heroku, and they provision those dbs with SSL) so I'm doubly confused as to what is going on. I will keep digging on my end.

**Comment by dnasseri** [comment]
@DomT4 It looks like the problem was actually with the `pg` gem. After issuing `bundle exec gem pristine pg` followed by a `bundle install` which rebuilt the gem, the problem has gone away. Apologies for polluting the issue tracker, I'll go ahead and close this out.

**Comment by DomT4** [comment]
@dnasseri No worries! Never gonna find me complaining when the solution is relatively simple & not something that needs hours of chasing 😸. Thanks for following up.
