### ISSUE TITLE
Formula "nsnake" contains malware-link 

### ISSUE THREAD

**Issue by FynnZW** [Homebrew/homebrew-core#20523]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

So, I was wondering if there's a snake game on brew and found this:
```bash
❯ brew info nsnake
nsnake: stable 3.0.1 (bottled), HEAD
Classic snake game with textual interface
http://nsnake.alexdantas.net/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/nsnake.rb
````
The domain alexdantas.net is compromised. It varies from simple spam to malicious malware. I got an ad for "mackeeper".

**Comment by ilovezfs** [comment]
thanks. should be fixed now if you `brew update`
