### ISSUE TITLE
R - No X11 or Cairo

### ISSUE THREAD

**Issue by IsmailM** [Homebrew/homebrew-core#20540]
R was recently moved from homebrew-science to homebrew-core - see [here](https://github.com/Homebrew/homebrew-science/commit/9cfc5716887fb07c1bcdf887b5ecceb2d60a5f95#diff-69da07d8b273e78fd6b38ad22b836786).

However, the newer r formula does not have include cairo or x11  - see below

https://github.com/Homebrew/homebrew-core/blob/19f6cb330c81231f9b361ed5c644802ca7f88ba2/Formula/r.rb#L40-L49

(Note ` --without-cairo --without-x` in particular)

Here are the corresponding lines from the homebrew science formula:

```ruby
 args = [ 
   "--prefix=#{prefix}", 
   "--with-cairo", 
   "--with-libintl-prefix=#{Formula["gettext"].opt_prefix}", 
   "--enable-memory-profiling", 
 ] 
```

(from: [here](https://github.com/Homebrew/homebrew-science/blob/edf4c4c50dac32efd9aa829d495b9da46322df35/r.rb#L63-L68))

As such, when I run `capabilities()` with the homebrew-core R, I get the following 
```r
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
      FALSE       FALSE       FALSE       FALSE       FALSE        TRUE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE
```

I'm now unable to install certain dependencies (which depend on cairo) because of this change... 

For Comparison, here is the output for `capabilities()` after installing R from [CRAN](https://cran.r-project.org/bin/macosx/)
```R

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua    
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS     profmem       cairo         ICU long.double     libcurl
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
```

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/issues/19557
