### ISSUE TITLE
hdf5: curl: (22) The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by orlandini** [Homebrew/homebrew-core#20542]
I was trying to `brew install petsc` but I couldn't install one of its dependencies, `hdf5`.
When I run `brew install --build-from-source hdf5 --c++11 --with-mpi` I get:

    ==> Using Homebrew-provided fortran compiler.
    This may be changed by setting the FC environment variable.
    ==> Downloading https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.bz2
    ==> Downloading from https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.bz2
    
    curl: (22) The requested URL returned error: 403 Forbidden
    Error: Failed to download resource "hdf5"

I am not sure if this is the right place for it, but I can't access the URL even in my browser.
Required info:

- Running `brew doctor` gives me `Your system is ready to brew.`.
- Running `brew config` gives me:
`

     HOMEBREW_VERSION: 1.3.6-217-g441c212
     ORIGIN: https://github.com/Homebrew/brew
     HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
     Last commit: 28 hours ago
     Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
     Core tap HEAD: cf537fbfd8bae7b9f97ddfedd3fbd82a008580b9
     Core tap last commit: 3 hours ago
     HOMEBREW_PREFIX: /usr/local
     HOMEBREW_DEV_CMD_RUN: 1
     HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
     CPU: octa-core 64-bit ivybridge
     Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
     Clang: 9.0 build 900
     Git: 2.15.0 => /usr/local/bin/git
     Curl: 7.54.0 => /usr/bin/curl
     Perl: /usr/bin/perl
     Python: /usr/bin/python
     Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
     Java: N/A
     macOS: 10.13.1-x86_64
     Xcode: 9.1
     CLT: 9.0.1.0.1.1506734476
     X11: N/A
`
 - Running `brew gist-logs hdf5` gives me `Error: No logs.`.
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
@orlandini this is now fixed if you `brew update`
