### ISSUE TITLE
szip source unreachable. Alternative source

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/homebrew-core#20563]
Hello,
the szip source to build hdf5 seems unreachable.
I found I could download the source from hdfgroup's ftp. Here is the URL:
ftp://ftp.hdfgroup.org/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz
Maybe the http relay will be back soon, but by now this works.

**Comment by ilovezfs** [comment]
Thanks. This is fixed if you `brew update`
