### ISSUE TITLE
mysql_config from mysql-connector-c outputs invalid data

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [Homebrew/homebrew-core#20622]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to build a library that connects to MySQL. This failed when linking due to missing symbols. And in fact when running `mysql_config --libs` it produces `-L/usr/local/Cellar/mysql-connector-c/6.1.11/lib -l` which is clearly wrong. Doing the same with `mariadb_config --libs` yields a more reasonable `-L/usr/local/Cellar/mariadb-connector-c/2.2.2/lib/mariadb -lmariadb -lssl /usr/lib/libiconv.dylib -ldl -lm -lpthread`, though that does not seem to be entirely correct either.

- What happened (include command output)

It outputs the wrong `CFLAGS`.

- What you expected to happen

Output something like  `-L/usr/local/Cellar/mysql-connector-c/6.1.11/lib -lmysqlclient -lssl -ldl -lm -lpthread`

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install mysql-connector-c
mysql_config --libs
```

**Comment by ilovezfs** [comment]
This is an upstream issue not a Homebrew issue. Please report it to them https://dev.mysql.com/downloads/connector/c/
