### ISSUE TITLE
SHA256 mismatch on little-cms2

### ISSUE THREAD

**Issue by guyjones** [Homebrew/homebrew-core#20628]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**To help us debug your issue please explain:**
- What you were trying to do (and why)
I'm trying to use Homebrew to install ffmpeg

**- What happened (include command output)**
The install fails when trying to install a dependency of ffmpeg – 'little-cms2' – I get a SHA256 mismatch:
```
edit1:~ dpm$ brew install ffmpeg --with-ffplay --with-libvidstab --with-libvo-aacenc --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools --with-x265
==> Installing dependencies for ffmpeg: little-cms2, libpng, openjpeg, makedepend, openssl, opus, rtmpdump, sdl2, speex, x265
==> Installing ffmpeg dependency: little-cms2
==> Downloading https://downloads.sourceforge.net/project/lcms/lcms/2.9/lcms2-2.9.tar.gz
==> Downloading from https://netix.dl.sourceforge.net/project/lcms/lcms/2.9/lcms2-2.9.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 00756bed09ce059a68289f10de56b00267667647393ddc30400cb87c0d9037d5
Actual: 40bf6bedc2836c673bf2fd5a0f24a696f789b394b2fbed043128366c6d75a5b8
Archive: /Users/dpm/Library/Caches/Homebrew/little-cms2-2.9.tar.gz
To retry an incomplete download, remove the file above.

```
If I delete and try again, I get the same thing. I've also tried downloading the tar.gz direct with no success. I've also tried installing little-cms2 independently.

**- What you expected to happen**
For ffmpeg to install with all dependencies.

**- Step-by-step reproduction instructions (by running `brew install` commands)**
Ran brew install ffmpeg
Received the error
Removed the the file and retried.
Ran brew cleanup && brew update and retried brew install ffmpeg ..

**BREW CONFIG**
HOMEBREW_VERSION: 1.3.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 02e3d1f64090b98a79baef328a926b41862c8a35
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 7.0 build 700
Git: 2.6.0 => /usr/local/bin/git
Curl: 7.43.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: N/A

It does look like there was an update to little-cms2 yesterday: https://sourceforge.net/projects/lcms/files/lcms/

**Comment by ilovezfs** [comment]
@mm2 any idea what happened here?

**Comment by guyjones** [comment]
Thanks @ilovezfs. Any ideas in his absence?

**Comment by ilovezfs** [comment]
@guyjones I've reported here now https://github.com/mm2/Little-CMS/issues/140. Unfortunately the checksum has changed _again_, which is not an encouraging sign.

**Comment by ilovezfs** [comment]
@guyjones thanks for reporting this. It's now fixed if you `brew update` and `brew upgrade`

**Comment by guyjones** [comment]
Ah great. Thanks very much.

**Comment by theeternalsw0rd** [comment]
Appears to be broken again.

**Comment by mm2** [comment]
I wonder if this is a consequence of the recent release of lcms2-2.9,  you reported this issue when I uploaded release candidates to sourceforge.RegardsMartiOn Nov 30, 2017 19:42, Micah Bucy <notifications@github.com> wrote:Appears to be broken again.

**Comment by DomT4** [comment]
No problem here at least:
```
Downloaded to: /usr/local/var/homebrewcache/little-cms2-2.9.tar.gz
SHA256: 48c6fdf98396fa245ed86e622028caf49b96fa22f3e5734f853f806fbc8e7d20
==> Verifying little-cms2-2.9.tar.gz checksum
```

**Comment by theeternalsw0rd** [comment]
Leftover tarball from before this was fixed. Redownloading fixed the issue.
