### ISSUE TITLE
Run "the brew upgrade bazel" error

### ISSUE THREAD

**Issue by ddlxstudio** [Homebrew/homebrew-core#20672]
**An error is as follows：**
Error: bazel: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bazel.rb:43: syntax error, unexpected '\n', expecting :: or '[' or '.'

**My solution：**
Modified Formula/bazel. Rb file.The "~EOS" replace "-EOS.Undent".

The modified can work.

**Comment by ilovezfs** [comment]
```
git -C "$(brew --repo)" fetch --tags
brew update --force
```

**Comment by ilovezfs** [comment]
```
git -C "$(brew --repo)" rev-parse origin/master
```
