### ISSUE TITLE
Custom config path for elasticsearch 6.0 not working

### ISSUE THREAD

**Issue by khakulov** [Homebrew/homebrew-core#20717]
The command `ES_PATH_CONF=$PWD/elasticsearch_config elasticsearch` not working anymore.

My workaround for now is
```
ES_PATH_CONF=$PWD/elasticsearch_config /usr/local/Cellar/elasticsearch/6.0.0/libexec/bin/elasticsearch
```
But the path `/usr/local/Cellar/elasticsearch/6.0.0/` is very specific for my Mac OSX and eventually does not work on other systems.

I also copied `jvm.options` file to my config folder to fix java errors. This step was not necessary for ES 5.

related pull request https://github.com/elastic/elasticsearch/issues/21932

**Comment by ilovezfs** [comment]
@jasontedor any ideas here what we should do?

**Comment by jasontedor** [comment]
Thanks for the report @khakulov. Thanks for the point @ilovezfs. This is from elastic/elasticsearch#25815 (and the follow on elastic/elasticsearch#26197 that only renamed `CONF_DIR` to `ES_PATH_CONF`). I will open a PR here soon to address.

**Comment by jasontedor** [comment]
I opened #20735.
