### ISSUE TITLE
Why are installers stored in Cache?

### ISSUE THREAD

**Issue by bretonics** [Homebrew/homebrew-core#20720]
Why are installers/sources for installed formula stored in cache after being installed? 
More specifically, what is the purpose of keeping these install files? They just take up space on the drives.

I researched cleaning up cache `brew cleanup` but it does not remove files for current versions installed, but what is the purpose in that? If it installed properly, why keep these? I know we can remove them with rm -rf $(brew --cache), but I feel like `brew cleanup` should remove **all** of these files, or at least have a flag for it, which is why I want to understand a strong reason why these are kept.

**Comment by ilovezfs** [comment]
This is a question for https://discourse.brew.sh/
