### ISSUE TITLE
about curl:(77) error 

### ISSUE THREAD

**Issue by yzhzu** [Homebrew/homebrew-core#20761]
[rcmm@localhost ~]$ brew install git
Updating Homebrew...
==> Installing dependencies for git: glibc, xz, m4, gmp, mpfr, libmpc, isl, gcc, gpatch, openssl, pkg-config, curl, libbsd, expat
==> Installing git dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
hello, can someone help me deal with the error? I spent several days and failed. thank you very much.

curl: (77) Problem with the SSL CA cert (path? access rights?)
Error: Failed to download resource "glibc"
Download failed: https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by ilovezfs** [comment]
>Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
