### ISSUE TITLE
brew update fails

### ISSUE THREAD

**Issue by therealmarcuslynch** [Homebrew/homebrew-core#20792]
Hi,

Apologies if this is not the right place to file this issue, but I'm still a relative newbie at this stuff.

After some problems with get-iplayer (which running through the check routine for posting here sorted out), I had tried running <brew update>, which resulted in the following:-

"Marcus-Air:~ marcus$ brew update
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/dinkypumpkin/homebrew-get_iplayer failed!"

I checked and<usr/local/Homebrew/Library/Taps/dinkypumpkin/homebrew-get_iplayer> is there, so I'mnot sure why github terminal prompts are disabled.

Can you help?

Cheers,

Marcus.

**Comment by miguelarauj1o** [comment]
Hey @therealmarcuslynch, I believe this is not a problem related to **Homebrew**.
See this issue [#176](https://github.com/kemayo/sublime-text-git/issues/176), from **sublime-text-git**. Also, after a quick search on google, I got this: https://stackoverflow.com/questions/32232655/go-get-results-in-terminal-prompts-disabled-error-for-github-private-repo

**Comment by ilovezfs** [comment]
The repository https://github.com/dinkypumpkin/homebrew-get_iplayer has been deleted, so `brew untap dinkypumpkin/get_iplayer`

**Comment by ilovezfs** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Note you didn't follow these directions. Please do so in the future.

**Comment by therealmarcuslynch** [comment]
Many thanks for this - brew update and upgrade now work! Thanks also for your forebearance with my ineptitude.

Cheers,

Marcus.
