### ISSUE TITLE
brew upgrade llvm: Could not identify toolchain dir

### ISSUE THREAD

**Issue by lobachevzky** [Homebrew/homebrew-core#20791]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

I am able to use brew in general without issue. This issue is triggered by [this file](https://github.com/llvm-mirror/llvm/blob/master/tools/xcode-toolchain/CMakeLists.txt).

- [x] Ran `brew update` and retried your prior step?

```
❯ brew update
Already up-to-date.
```

- [x] Ran `brew doctor`, fixed all issues and retried your prior step?

```
❯ brew doctor
Your system is ready to brew.
```

- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/8ea28ddada35c63296bcc637b9df76c5

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I am trying to upgrade `llvm`.

- What happened (include command output)

```
❯ brew upgrade llvm
==> Upgrading 1 outdated package, with result:
llvm 5.0.0
==> Upgrading llvm --with-toolchain
==> Installing dependencies for llvm: cmake
==> Installing llvm dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.9.6.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake-3.9.6.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.9.6: 2,267 files, 31.7MB
==> Installing llvm --with-toolchain
==> Downloading https://releases.llvm.org/5.0.0/llvm-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/cfe-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/clang-tools-extra-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/openmp-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/libcxx-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/libunwind-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/lld-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/polly-5.0.0.src.tar.xz
######################################################################## 100.0%
==> Downloading https://releases.llvm.org/5.0.0/compiler-rt-5.0.0.src.tar.xz
######################################################################## 100.0%
==> cmake -G Unix Makefiles /private/tmp/llvm-20171118-14985-kg9ntx/llvm-5.0.0.src -DCMAKE_C_FLAG
Last 15 lines from /Users/ethan/Library/Logs/Homebrew/llvm/01.cmake:
  command.


CMake Warning at tools/xcode-toolchain/CMakeLists.txt:60 (message):
  Failed to detect the version of an installed copy of Xcode, falling back to
  highest supported version.  Set XCODE_VERSION to override.


CMake Error at tools/xcode-toolchain/CMakeLists.txt:80 (message):
  Could not identify toolchain dir


-- Configuring incomplete, errors occurred!
See also "/tmp/llvm-20171118-14985-nvxarp/CMakeFiles/CMakeOutput.log".
See also "/tmp/llvm-20171118-14985-nvxarp/CMakeFiles/CMakeError.log".

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

- What you expected to happen

I expected the upgrade to succeed.

- Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew upgrade llvm`.
System info:
```
❯ brew --version
Homebrew 1.3.7
Homebrew/homebrew-core (git revision 2326a; last commit 2017-11-18)

~
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.1
BuildVersion:	17B48

~
❯ clang --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

~
❯ xcrun -find otool
/Library/Developer/CommandLineTools/usr/bin/otool
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

The problem seems to be that `llvm/tools/xcode-toolchain/CMakeLists.txt` expects `clang` live under a directory called `Toolchains/`. More specifically, it uses `xcrun -find otool` to assign a variable called `clang_path` (not sure why this isn't `scrun -find clang`, but they happen to occupy the same directory so that isn't the problem). Now there is `/usr/local/Cellar/llvm/4.0.1/Toolchains/LLVM4.0.1.xctoolchain/usr/share/clang/`. Maybe these are the droids that CMakeLists.txt is looking for. 

I am also going to post a bug with llvm as soon as I am granted an account on bugzilla. If I get the issue resolved there, I will update this post.

Thanks for your help!

**Comment by ilovezfs** [comment]
Have you launched Xcode.app and accepted the license, etc.? I cannot reproduce the issue.

```
-- Looking for sys/resource.h
-- Looking for sys/resource.h - found
-- Clang version: 5.0.0
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG
-- Performing Test CXX_SUPPORTS_NO_NESTED_ANON_TYPES_FLAG - Success
-- LLD version: 5.0.0
-- Identified Xcode Version: 9.1
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/llvm-20171119-12176-e1m92n
==> make
```

**Comment by ilovezfs** [comment]
```
❯ xcrun -find otool
/Library/Developer/CommandLineTools/usr/bin/otool
```

That may be the problem.

For me,
```
xcrun -find otool
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool
```

So your
```
xcode-select -p
```
is probably pointing at `/Library/Developer/CommandLineTools`

Try
```
sudo xcode-select -r
```

and see if that gets it pointing at Xcode.

**Comment by lobachevzky** [comment]
That solved it:

1. launched Xcode.app and accepted the license
2. `sudo xcode-select -r`
3. brew upgrade llvm
