### ISSUE TITLE
brew update Failed

### ISSUE THREAD

**Issue by Mamta678** [Homebrew/homebrew-core#20866]
While trying to run brew update command in terminal, the following error is displayed:

fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Could not resolve host: github.com
fatal: unable to access 'https://github.com/Homebrew/brew/': Could not resolve host: github.com
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Homebrew failed!

Any idea on how it can be resolved?

**Comment by ilovezfs** [comment]
This sounds like a transient issue with your Internet connection or DNS. I'd try again later.

**Comment by ilovezfs** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Note you didn't follow these directions. Please do so in the future.
