### ISSUE TITLE
hydra security issues

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#2090]
See https://github.com/vanhauser-thc/thc-hydra/issues/134

Repeating what I said in the upstream issue above,

Firefox is saying,

>This web page at www.thc.org has been reported to contain unwanted software and has been blocked based on your security preferences.

>Unwanted software pages try to install software that can be deceptive and affect your system in unexpected ways.

And wget is saying

>ERROR: cannot verify www.thc.org's certificate, issued by ‘CN=RapidSSL SHA256 CA - G3,O=GeoTrust Inc.,C=US’:
  Unable to locally verify the issuer's authority.
To connect to www.thc.org insecurely, use `--no-check-certificate'.

I think we may need to boneyard this until the situation is understood.

**Comment by DomT4** [comment]
THC ends up on "Safe Browsing" lists all the time due to the nature of the software it provides. It's not uncommon for cracking or penetration testing software to end up being flagged. I wouldn't read too much into that, personally.

> And wget is saying

This is interesting, though. It reproduces against Homebrew's `curl` (built with OpenSSL) and `wget`, but doesn't reproduce with `/usr/bin/curl`.

**Comment by ilovezfs** [comment]
That's pretty ridiculous if it's what's going on. I guess the homepage could be set to the GitHub repo since it's kind of "not OK" to be sending people to sites where their browser will go all paranoid and turn red.

**Comment by tdsmith** [comment]
I think the cause of the certificate error is described here: http://stackoverflow.com/a/7644229/892260 -- if you `openssl s_client -connect www.thc.org:443 -servername www.thc.org -showcerts`, copy the intermediate certificate the server sends, and run `pbpaste | openssl x509 -text` you can convince yourself that thc.org is sending the wrong intermediate certificate, and that the web browsers are able to resolve the certificate chain only by doing magic with embedded certificate metadata. In particular, the server certificate is issued by `/C=US/O=GeoTrust Inc./CN=RapidSSL SHA256 CA - G3` and the provided intermediate certificate is `/C=US/O=GeoTrust, Inc./CN=RapidSSL CA`. That's probably reportable upstream. 

I don't care what we do with the homepage but I don't think there's an underlying issue besides browser vendors being nervous.

**Comment by ilovezfs** [comment]
@tdsmith here's what upstream said: https://github.com/vanhauser-thc/thc-hydra/issues/134#issuecomment-226947807

**Comment by tdsmith** [comment]
I saw; either they or I is failing to completely understand the issue and my natural hubris thinks it might not be me. :) I'll comment there.

**Comment by ilovezfs** [comment]
@tdsmith thanks. Hopefully they can at least get the SSL happy if they're also going to have to continue to contend with this ridiculous "math is malware" rubbish.

**Comment by DomT4** [comment]
This sort of thing with the homepage is generally why I think "Safe Browsing" lists cause as many problems as they solve. Content flagged as "dangerous" with seemingly minimal human review, and even less review in terms of how incorrectly flagged websites get off the list.

**Comment by MikeMcQuaid** [comment]
Closing out upstream issues.
