### ISSUE TITLE
BINDIR errors with rkhunter package

### ISSUE THREAD

**Issue by derhornspieler** [Homebrew/homebrew-core#20900]
sudo rkhunter -c
Invalid BINDIR configuration option: Invalid directory found: Fusion.app/Contents/Public

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by heywoodlh** [comment]
I know this is closed, however I'm throwing this on for my own personal record as well as anyone else who runs into this same issue. I fixed this by adding this to my `/etc/rkhunter.conf`:

`PATH=$PATH:~/bin`

You could also modify your root user's ~/.bash_profile to reflect the same line.

Not sure if this is recommended but it started working for me once I added this. Had to quit my current terminal session and then it started working. 

Apparently `rkhunter` looks at the "$PATH" variable and if you have VMWare Fusion installed, there is a line added to path which includes 'VMWare Fusion.app' and `rkhunter` doesn't seem to parse the space in 'VMWare Fusion.app' without an error.

Once you get this line removed from your "$PATH" variable it should fix it. There are multiple ways to do it.

**Comment by derhornspieler** [comment]
Thank you Spencer for being helpful instead of just closing a real issue with the program.

I will give this a try.

Sent from my iPhone

On Nov 30, 2017, at 17:21, Spencer Heywood <notifications@github.com<mailto:notifications@github.com>> wrote:


I know this is closed, however I'm throwing this on for my own personal record as well as anyone else who runs into this same issue. I fixed this by adding this to my /etc/rkhunter.conf:

PATH=$PATH:~/bin

You could also modify your root user's ~/.bash_profile to reflect the same line.

Not sure if this is recommended but it started working for me once I added this. Had to quit my current terminal session and then it started working.

Apparently rkhunter looks at the "$PATH" variable and if you have VMWare Fusion installed, there is a line added to path which includes 'VMWare Fusion.app' and rkhunter doesn't seem to parse the space in 'VMWare Fusion.app' without an error.

Once you get this line removed from your "$PATH" variable it should fix it. There are multiple ways to do it.

**Comment by heywoodlh** [comment]
You could also rename `/Applications/VMWare Fusion/` to `/Applications/VMWareFusion` without a space. Not sure if this is a bad idea but may work.

**Comment by durian808** [comment]
I was also getting this error.  I modified my /etc/rkhunter.conf to set a BINDIR that would eliminate the problem, since the default PATH contained the "./" directory, etc.  After this I was still getting the error so I looked at /bin/rkhunter and found that it was indeed using my new BINDIR; however, it was **ALSO** using the default PATH.  So I changed

`       for DIR in ${PREPEND_PATHS} ${RKHROOTPATH} ${BINPATHS}; do`

to

`        for DIR in ${PREPEND_PATHS}; do`

Things now appear to be working correctly.

**Comment by heywoodlh** [comment]
This is awesome. Thanks for the info.
