### ISSUE TITLE
Postgres formula not working on High Sierra

### ISSUE THREAD

**Issue by lxsndl** [Homebrew/homebrew-core#20907]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Installing and using postgresql on OSX

- What happened (include command output)

Installation went well and without issues but service does not start/can't connect to the database. Errors show up in the system.log (see below)

- What you expected to happen

Postgres formula to work

- Step-by-step reproduction instructions (by running `brew install` commands)

% brew install postgresql
% brew services start postgresql
% psql

> % brew gist-logs postgresql     
> Error: No logs.

> % brew config
> HOMEBREW_VERSION: 1.3.7
> ORIGIN: https://github.com/Homebrew/brew.git
> HEAD: 441c212f2dd70f053ee21eac8398c5fe5dfd0551
> Last commit: 11 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 73ccfcea98f6a33784af6c6589f5cbe90f7e5326
> Core tap last commit: 13 hours ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
> HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
> CPU: quad-core 64-bit haswell
> Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
> GCC-4.2: build 5666
> Clang: 9.0 build 900
> Git: 2.15.0 => /usr/local/bin/git
> Curl: 7.54.0 => /usr/bin/curl
> Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
> Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
> Ruby: /Users/name/.rbenv/shims/ruby => /Users/name/.rbenv/versions/2.4.1/bin/ruby
> Java: N/A
> macOS: 10.13.1-x86_64
> Xcode: 9.1
> CLT: N/A
> X11: N/A
> 

> % brew doctor
> Your system is ready to brew.

System.log:

> Nov 21 12:07:24 hostname com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
> Nov 21 12:07:34 hostname com.apple.xpc.launchd[1] (homebrew.mxcl.postgresql[1963]): Service exited with abnormal code: 1
> 

(these 2 lines are repeated every 10 seconds.)

Trying to connect to the postgres server yields:

> % psql       
> psql: could not connect to server: No such file or directory
> 	Is the server running locally and accepting
> 	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

> % brew services list
> Name       Status  User Plist
> postgresql started name /Users/name/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
>

**Comment by ilovezfs** [comment]
This is a local configuration issue. You may need to recreate your databases and configuration files.

**Comment by lxsndl** [comment]
@ilovezfs Huh, thanks for getting back to me quickly. I 'brew uninstall'-ed postgresql and thought that would take care of all potential config issues. Apparently even uninstalling kept all the data in /usr/local/var/postgres, specifically the config. So manually deleting the folder and re-installing the formula fixed it. Thanks for pointing me in the right direction.

Is there a brew command à la 'purge' to completely get rid of all traces of a formula?

Cheers.

**Comment by ilovezfs** [comment]
>Is there a brew command à la 'purge' to completely get rid of all traces of a formula?

Not for anything outside of the Cellar. But you can look at the post_install method https://github.com/Homebrew/homebrew-core/blob/fb827da5eadde60f9b483b3d93052d3abd9ab749/Formula/postgresql.rb#L93-L99
