### ISSUE TITLE
Nmap - Closed port inconsistency

### ISSUE THREAD

**Issue by ama21n** [Homebrew/homebrew-core#20951]
Brew Nmap version 7.60 (latest version)

Using the '--reason' parameter, -sT shows some ports as 'conn-refused', and incorrectly marks them as closed, when in reality, an upstream router has sent a 'Destination unreachable (Communication administratively filtered)' ICMP (type 3, code 13) packet.
Furthermore, the -sT option responds to this ICMP packet by sending an ACK and FIN packet, and as a result, misinterprets the results.

-sS on the other hand reports the port status correctly as 'admin-prohibited from <router_ip>'. No further packets are sent, and the port is correctly marked as filtered.

nmap (Nmap version 7.01) on kali linux works as expected, marking the port as filtered with reason 'host-unreach'

**Comment by fxcoudert** [comment]
Dear @ama21n, thanks for the report. However, this looks like a very specific bug, and likely to come from upstream (the nmap code base) rather than a problem specific to Homebrew's packaging. Your best chance to get it fixed is to report it to them: http://seclists.org/nmap-dev/
