### ISSUE TITLE
mac must install xcode?   xcode-select --install  not work

### ISSUE THREAD

**Issue by donghl** [Homebrew/homebrew-core#20986]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.
-----------------------------------
# At first my mac install xcode 8.x,but it's outdate,so I uninstall it . when I run "brew upgrade ", It tall me:

curl: (18) transfer closed with 80768435 bytes remaining to read
Error: Failed to download resource "erlang"
Download failed: https://homebrew.bintray.com/bottles/erlang-20.1.7.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: The following formula:
  erlang
cannot be installed as a binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

# so I run "xcode-select --install"  ,but not install xcode ,because xcode 9.x is vary  large . then it not work  :

xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:148:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:148:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:58:in `without_clt?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:19:in `homebrew_extra_paths'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:107:in `determine_path'
/usr/local/Homebrew/Library/Homebrew/extend/ENV/super.rb:42:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/extend/ENV/super.rb:91:in `setup_build_environment'
/usr/local/Homebrew/Library/Homebrew/build.rb:85:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'

**Comment by ilovezfs** [comment]
What the output of
```
brew config
```

```
brew doctor
```

```
xcode-select -p
```

```
ls /Applications/ | grep -i xc
```

**Comment by ilovezfs** [comment]
@donghl ping

**Comment by MikeMcQuaid** [comment]
Should be fixed by https://github.com/Homebrew/brew/pull/3509
