### ISSUE TITLE
Snort formula suggests setting 644 on /dev/bpf* while by default it's 660

### ISSUE THREAD

**Issue by techraf** [Homebrew/homebrew-core#2103]
There's a [suggestion to set permissions to `644` for `/dev/bpf*`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/snort.rb#L63) in the formula for Snort.

According to the explanation it is to enable non-root users to read the files. However following the advice removes the default write permission for `access_bpf` group.

Is it intentional? Doesn't it break anything?

By default these files have `660`:
```
crw-rw----  1 root  access_bpf   23,   0 Jun 18 01:04 /dev/bpf0
crw-rw----  1 root  access_bpf   23,   1 Jun 18 00:52 /dev/bpf1
crw-rw----  1 root  access_bpf   23,  10 Jun 18 01:00 /dev/bpf10
crw-rw----  1 root  access_bpf   23, 100 Jun 18 01:00 /dev/bpf100
crw-rw----  1 root  access_bpf   23, 101 Jun 18 01:00 /dev/bpf101
...
```

**Comment by tdsmith** [comment]
Thanks a lot for filing this issue! This is probably unintentional; nobody's complained that anything is broken yet. It's probably better advice to suggest adding users to the `access_bpf` group or to run `chmod o+r ...`. Would you like to write a patch for this? [This document](https://git.io/vo2xc) should give you a head start and we'd be more than happy to walk you through it if you have any questions.

**Comment by techraf** [comment]
Thank you for your warm welcome. Not without problems (`brew audit` complaining about `rubocop` not found in `GEM PATH`, even though it was previously installed) I managed to issue a [PR](https://github.com/Homebrew/homebrew-core/pull/2133). Learnt something new. 👍

**Comment by tdsmith** [comment]
:tada: Awesome; thanks for your help!

**Comment by techraf** [comment]
Just curious... On another machine I checked the contents of `/usr/local/Library/Taps/homebrew/homebrew-core/Formula/snort.rb`, then I executed `brew update` and checked `snort.rb` again. It got updated.

However it was not listed in `Updated Formulae` at the update.

Any idea why?

**Comment by UniqMartin** [comment]
Formulae are only listed in the `brew update` output if they are updated (their version number changes). If there are only minor fixes/tweaks without a version change, then these are filtered from the output.
