### ISSUE TITLE
autoconf is missing aclocal

### ISSUE THREAD

**Issue by gwoplock** [Homebrew/homebrew-core#21125]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
install autoconf
- What happened (include command output)
when running autoreconf -i and autoconf it failed due to missing aclocal
- What you expected to happen
it to run
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install autoconf
autoremake -i

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I attempted to change the autoconf formula but adding automake as a dependency causes a circular dependency. When I added the dependency I made it a run time dependency so it should be able to break the circular dependency.

**Comment by JCount** [comment]
`aclocal` is part of GNU's `automake` set of tools. You should be able to simply run `brew install automake` to add it to your path, and then run `autoreconf -i`.

**Comment by gwoplock** [comment]
I figured that out. I would assume that since autoreconf is part of the autoconf package that it would have everything it needed. 

To me, the solution would be to add a runtime dependency to the autoconf package but homebrew cant resolves circular dependencies as far as I can tell. since automake isn't required until autoconf is run it should be able to install autoconf then automake. Further, it could install the 2 in any order because both have the other as runtime dependencies.

**Comment by fxcoudert** [comment]
`automake` requires `autoconf`, while only a small part of `autoconf` (`autoreconf`) needs `automake`. It may be seen as unfortunate that GNU decided to split those into two packages, but that's what we have to deal with…
