### ISSUE TITLE
Broken linking for python

### ISSUE THREAD

**Issue by mciancia** [Homebrew/homebrew-core#21159]
I installed homebrew today on latest High Sierra, and tried installing python after that. Looks like python installed successfully, but after running python in terminal I still get version from apple.
I tried reinstalling, unlinking and linking but still does not work. Same goes for python 3 and for pip (which is not found). Tried brew update and brew doctor, no problems here

My path variable: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Gist: https://gist.github.com/2c3c9f4bfaa4ee422e951a6a439d1d28

I also installed wget and sbt, and look like there are no problems with those.
Running ls -l $(which python) shows me there is no symlink like there is for sbt and wget

**Comment by ilovezfs** [comment]
Please re-read the python caveats.
```
==> Caveats
This formula installs a python2 executable to /usr/local/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python.html
bash-3.2$ 
```
