### ISSUE TITLE
CMake formula builds in Debug mode?

### ISSUE THREAD

**Issue by kaihowl** [Homebrew/homebrew-core#21155]
# Please always follow these steps:
- [does not apply] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [does  not apply] Ran `brew update` and retried your prior step?
- [does not apply ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [does not apply] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [does not apply] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Using cmake from brew
- What happened (include command output)
It worked but cmake seems very slow compared to my Ubuntu install
- What you expected to happen
Faster cmake, built with optimizations turned on.
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install cmake

# Formula additions or changes
I am willing to contribute a pull request. Yet, I first wanted to confirm my suspicion:
Is the the cmake formula building cmake without optimizations turned on? I only see standard build system invocations for building cmake and no special flags or the CMAKE_BUILD_TYPE being set to Release. This usually yields a binary with optimizations turned off. Please confirm or refute my hypothesis.

**Comment by ilovezfs** [comment]
What you see is what you get.

```
  def install
    args = %W[
      --prefix=#{prefix}
      --no-system-libs
      --parallel=#{ENV.make_jobs}
      --datadir=/share/cmake
      --docdir=/share/doc/cmake
      --mandir=/share/man
      --system-zlib
      --system-bzip2
      --system-curl
    ]

    if build.with? "docs"
      # There is an existing issue around macOS & Python locale setting
      # See https://bugs.python.org/issue18378#msg215215 for explanation
      ENV["LC_ALL"] = "en_US.UTF-8"
      args << "--sphinx-man" << "--sphinx-build=#{Formula["sphinx-doc"].opt_bin}/sphinx-build"
    end

    system "./bootstrap", *args
    system "make"
    system "make", "install"

    if build.with? "completion"
      cd "Auxiliary/bash-completion/" do
        bash_completion.install "ctest", "cmake", "cpack"
      end
    end

    elisp.install "Auxiliary/cmake-mode.el"
  end
```
So your theory is probably correct.

**Comment by kaihowl** [comment]
Why did you just close it? Building this without optimization is completely useless. I am testing a pull request right now and would love to close this issue by that instead.

**Comment by ilovezfs** [comment]
There were 180,000 installations of this in the last 30 days. So I'm going with "not useless."

>would love to close this issue by that instead.

From the issue template: 
># Formula additions or changes
>To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
>We will close issues requesting formulae changes.
