### ISSUE TITLE
gcc installation fails on Travis-CI xcode 8.3

### ISSUE THREAD

**Issue by xoviat** [Homebrew/homebrew-core#21172]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I attempted to install gcc on Travis-CI with homebrew

- What happened (include command output)

```
==> Installing dependencies for gcc: libmpc, isl
==> Installing gcc dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3_1.sierra.bottle.tar.gz
==> Pouring libmpc-1.0.3_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3_1: 12 files, 345.0KB
==> Installing gcc dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.18.sierra.bottle.tar.gz
==> Pouring isl-0.18.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.18: 80 files, 3.8MB
==> Installing gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-7.2.0.sierra.bottle.tar.gz
==> Pouring gcc-7.2.0.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'
To force the link and overwrite all conflicting files:
  brew link --overwrite gcc
To list all files that would be deleted:
  brew link --overwrite --dry-run gcc
Possible conflicting files are:
/usr/local/include/c++ -> /usr/local/Caskroom/oclint/0.11,15.6.0/oclint-0.11/include/c++
```

- What you expected to happen

I expected gcc to be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

On Travis-CI, run `brew install gcc` on xcode 8.3.

I realize that this may not be homebrew's problem. But given that `gcc` is probably a common formula, and given that Xcode 8.3 is common (I guess?), I am curious about the implications of this directory and whether it's possible to install gcc on OSX with that Xcode version installed. So the questions are:

- Who's fault is it that the `c++` directory exists?
- What is to be done about it? Should the directory simply be removed on Xcode 8.3?

xref travis-ci/travis-ci#8826

**Comment by fxcoudert** [comment]
There is a preexisting `/usr/local/include/c++`, which according to https://github.com/travis-ci/travis-ci/issues/8826 comes from a prior installation of the `oclint` cask. Remove that and you will be good to go.

**Comment by xoviat** [comment]
This may be related, but are there plans for homebrew to automatically
uninstall conflicting packages or at least detect the conflict earlier
and/or print a more helpful error message (probably not)?
