### ISSUE TITLE
python3 has wrong LINKFORSHARED in module sysconfig

### ISSUE THREAD

**Issue by count0** [Homebrew/homebrew-core#21212]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

This is a regression of: https://github.com/Homebrew/legacy-homebrew/issues/37923

When using python3, and running:
```
import distutils.sysconfig
distutils.sysconfig.get_config_var('LINKFORSHARED')
```
it returns '-Wl,-stack_size,1000000 -framework CoreFoundation Python.framework/Versions/3.4/Python'

Like we observe in https://github.com/Homebrew/homebrew-science/issues/6461, automake builds like graph-tool calls this method. Then it looks for Python.framework/Versions/3.4/Python in /System/Library/Frameworks. This directory does not exist since it is in #{HOMEBREW_PREFIX}/Cellar/python3/3.4.3/Frameworks instead.

**Comment by tommyjiang** [comment]
I had the same issue. Can't resolve with `brew install python3` and `brew postinstall python3`.

**Comment by shongololo** [comment]
Not stale

**Comment by ilovezfs** [comment]
@zmwangx any idea what's going on here?

**Comment by zmwangx** [comment]
@ilovezfs Not sure. We appear to be setting the variable correctly, but Python's not picking it up:

```console
$ /usr/local/Cellar/python3/3.6.4/bin/python3 -c 'import distutils.sysconfig; print(distutils.sysconfig.get_makefile_filename()); print(distutils.sysconfig.get_config_var("LINKFORSHARED"))'
/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/Makefile
-Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.6/Python
$ grep -E '^(LINKFORSHARED|PYTHONFRAMEWORKINSTALLDIR)' /usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/Makefile
LINKFORSHARED=	-Wl,-stack_size,1000000  -framework CoreFoundation $(PYTHONFRAMEWORKINSTALLDIR)/Versions/$(VERSION)/$(PYTHONFRAMEWORK)
PYTHONFRAMEWORKINSTALLDIR= /usr/local/opt/python3/Frameworks/Python.framework
```

I'll test a non-Homebrew build later to see if this is brew-specific. So Tim's no longer available?

**Comment by ilovezfs** [comment]
@zmwangx formally, no. https://github.com/Homebrew/brew/commit/e504caa5a367ffa48321aa1f599aed951bde50bf#diff-04c6e90faac2675aa89e2176d2eec7d8

But we could always try pinging him if you think it's necessary :)

**Comment by zmwangx** [comment]
Yeah I know he formally stepped down, just wondering if his activities stopped completely.

**Comment by ilovezfs** [comment]
He's still participating on IRC but hasn't opened any PRs of late.

**Comment by zmwangx** [comment]
This should be fixed by #22103.

**Comment by ilovezfs** [comment]
@count0 @shongololo @tommyjiang This should be fixed now, thanks to @zmwangx, if you `brew update && brew reinstall python3`

**Comment by shongololo** [comment]
@count0 @ilovezfs @zmwangx I can confirm all is now working with graph-tool on python version 3
