### ISSUE TITLE
Why not generate `mupdf-gl` binary in formula `mupdf`?

### ISSUE THREAD

**Issue by specter119** [Homebrew/homebrew-core#21343]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# To help us debug your issue please explain:

I wondering why there is not a `mupdf-gl` binary, for I have already tried install `mupdf` or `mupdf-tools`?

**Comment by fxcoudert** [comment]
We do not build `mupdf-gl` because of a bug in mupdf, which I reported in May and was not fixed (or even acknowledged): https://bugs.ghostscript.com/show_bug.cgi?id=697842

**Comment by specter119** [comment]
@fxcoudert Thanks, I got it.
