### ISSUE TITLE
cgi script is displayed as plain text and not executed

### ISSUE THREAD

**Issue by adamwinn** [Homebrew/homebrew-core#21368]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
Adams-MacBook-Pro:htdocs awinn$ brew gist-logs httpd
Error: No logs.
```
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
Adams-MacBook-Pro:htdocs awinn$ brew config
HOMEBREW_VERSION: 1.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4f5e938a5dbe049e05dea19495b6547acc5c5b5b
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a775893d328b4719eb049bcd6809b35132adcf43
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.2_1/bin/ruby
Java: 1.8.0_51, 1.6.0_65-b14-468
macOS: 10.13.1-x86_64
Xcode: 9.1
CLT: 9.1.0.0.1.1508540944
X11: N/A
```
```
Adams-MBP:~ awinn$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Execute a cgi script from localhost in my browser
- What happened (include command output)
The cgi code was displayed as plain text and not executed
- What you expected to happen
The cgi script to be executed
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install httpd

I believe the issue is because the resulting httpd.conf file doesn't have `LoadModule cgi_module libexec/apache2/mod_cgi.so` so the cgi script is not executed.  I've searched my system and the only `mod_cgi.so` file that comes up is the Mac system one.  How can I get a valid `mod_cgi.so` file that's compatible with homebrew's apache?

**Comment by ilovezfs** [comment]
@kabel or @javian may have some advice for you.

**Comment by javian** [comment]
@adamwinn a good place to start would be to check https://httpd.apache.org/docs/2.4/howto/cgi.html . `mod_cgi` is not available but I can see that `mod_cgid` is listed in the bottle so I would start to look there..

**Comment by ikthorn** [comment]
@javian mod_cgi is part of apache 'base' and should be included by default.  I concur that it's not in the build here, is there a particular reason for it?
This was something I ended up chasing my tail over a little bit until I found this issue post.

**Comment by ilovezfs** [comment]
This should now be fixed, thanks to @kabel, if you `brew update && brew upgrade`
