### ISSUE TITLE
Ansible and jinja2 division

### ISSUE THREAD

**Issue by publicarray** [Homebrew/homebrew-core#21369]
- [x] Confirmed this is a problem with `brew install`
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The ansible formula uses [an older jinja2 version](https://github.com/ilovezfs/homebrew-core/blob/6a8e86c1fc974f39b68b9f6a4c9100ba65015f23/Formula/ansible.rb#L75) and there is a bug when dividing, this seams to have append rather recently I think when I updated to ansible 2.4.2.0
```bash
$ ansible --version
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/seb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
$ ansible localhost -m debug -a 'msg="{{4 * 5 // 7}}"'
localhost | SUCCESS => {
    "changed": false, 
    "msg": "0"
}
```

`pip2 install ansible` does not have the problem:
```bash
$ ansible --version
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/seb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
$ ansible localhost -m debug -a 'msg="{{4 * 5 // 7}}"'
localhost | SUCCESS => {
    "changed": false, 
    "msg": "2"
}
```

Initially reported here: https://github.com/ansible/ansible/issues/33506

**Comment by ilovezfs** [comment]
OK, it's pinned due to https://github.com/ansible/ansible/issues/23779 but it sounds like we may be able to remove the pin now.

**Comment by ilovezfs** [comment]
@publicarray this is now fixed if you brew update and brew upgrade

**Comment by publicarray** [comment]
Thanks for the speedy fix 👍
