### ISSUE TITLE
pre-commit: virtualenv failure due to relative symlinks

### ISSUE THREAD

**Issue by asottile** [Homebrew/homebrew-core#21386]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### description

Hi, I'm the maintainer of pre-commit and noticed some strangeness that can come about if `PATH` is limited (or pythonx.x isn't on the `PATH`).  I've traced the root cause to the execution of `virtualenv` from the virtualenv `brew` set up for `pre-commit`.  I'll include two sets of reproductions below -- one demonstrating the failure for `pre-commit` itself, the other the root cause.

### related issues

- https://github.com/pre-commit/pre-commit/issues/664
- https://github.com/pre-commit/pre-commit-hooks/issues/253

### failure using pre-commit

note that I intentionally constrain the path.  The "broken" condition is that `python3.6` is not on the `PATH` -- I've seen two ways this happens:
1. running from some application which doesn't correctly add the various FHS paths to `PATH`
2. `brew` partially installed `python3` but failed to symlink to `/usr/local/bin`

```bash
#!/usr/bin/env bash
set -ex
brew install pre-commit
rm -rf /tmp/pre-commit-demo
git init /tmp/pre-commit-demo
cd /tmp/pre-commit-demo
cat >.pre-commit-config.yaml <<EOF
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
EOF
pre-commit clean
pre-commit install
git add .pre-commit-config.yaml
PATH=/usr/bin:/bin $(which git) commit -m "test"
```

Output:

```console
$ bash test.sh
+ brew install pre-commit
Warning: pre-commit 1.4.1 is already installed
+ rm -rf /tmp/pre-commit-demo
+ git init /tmp/pre-commit-demo
Initialized empty Git repository in /private/tmp/pre-commit-demo/.git/
+ cd /tmp/pre-commit-demo
+ cat
+ pre-commit clean
Cleaned /Users/asottile/.cache/pre-commit.
+ pre-commit install
pre-commit installed at /private/tmp/pre-commit-demo/.git/hooks/pre-commit
+ git add .pre-commit-config.yaml
++ which git
+ PATH=/usr/bin:/bin
+ /usr/local/bin/git commit -m test
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python3.6', '-m', 'virtualenv', '/Users/asottile/.cache/pre-commit/repo5fx2k9wu/py_env-default', '-p', '/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python3.6')
Return code: 1
Expected return code: 0
Output: 
    Already using interpreter /usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python3.6
    Using real prefix '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6'
    
Errors: 
    Traceback (most recent call last):
      File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
        main()
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 1132, in install_python
        copy_required_modules(home_dir, symlink)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 1063, in copy_required_modules
        copyfile(filename, dst_filename, symlink)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 343, in copyfile
        os.makedirs(os.path.dirname(dest))
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/../lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/Users/asottile/.cache/pre-commit/repo5fx2k9wu/py_env-default/lib/python3.6/lib-dynload'
    

Check the log at /Users/asottile/.cache/pre-commit/pre-commit.log
```

### root cause failure

```bash
#!/usr/bin/env bash
set -ex
brew install pre-commit
rm -rf venv-pre-commit-test
/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/virtualenv \
    venv-pre-commit-test \
    -p /usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python
```

Output:
```console
$ bash test.sh
+ brew install pre-commit
Warning: pre-commit 1.4.1 is already installed
+ rm -rf venv-pre-commit-test
+ /usr/local/Cellar/pre-commit/1.4.1/libexec/bin/virtualenv venv-pre-commit-test -p /usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python
Running virtualenv with interpreter /usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python
Using real prefix '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6'
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 1132, in install_python
    copy_required_modules(home_dir, symlink)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 1063, in copy_required_modules
    copyfile(filename, dst_filename, symlink)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 343, in copyfile
    os.makedirs(os.path.dirname(dest))
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/../lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/private/tmp/foo/venv-pre-commit-test/lib/python3.6/lib-dynload'
```

### root cause analysis

`brew`'s virtualenv setup is _slightly_ different than a traditional virtual environment.  Consider the following (the virtual environment `venv` is set up through traditional means: `virtualenv venv` -- if you'd like a dependencyless way to get a virtual environment you could `curl https://asottile.github.io/get-virtualenv.py | python - venv`:

```console
$ ls -al venv/lib/python3.6/lib-dynload
lrwxr-xr-x 1 asottile wheel 98 Dec  6 09:43 venv/lib/python3.6/lib-dynload -> /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
$ ls -al /usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/lib-dynload
lrwxr-xr-x 1 asottile admin 96 Nov  9 08:36 /usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/lib-dynload -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
```

The above virtualenv, the symlink is an absolute symlink and so when it is recreated by the `virtualenv` machinery, it still points to the correct place -- however when a virtualenv is made from the `brew` virtualenv, the relative symlink may be pointing to the incorrect place.

I presume the reason `brew` adjusts all of the symlinks to relative symlinks is to make them relocatable (and not be tied to a specific `brew` prefix)?

I'm wondering if there's some sort of post-install hook to adjust these symlinks back to being absolute -- such that the virtualenv machinery can still function correctly.  Presumably other tools which are in a virtualenv and use virtualenv would be affected by the same things.

### for pre-commit users hitting the above stacktrace:

1. If you're running inside some sort of specialized `git` application, ensure that your `brew` bin is on the `PATH` (usually need to add `/usr/local/bin` to the `PATH`, either through the specific application's configuration or through the launcher configuration).
2. If you're running on the command line, ensure that `brew install python3` succeeds without error -- make sure that the `python3.6` executable can be found via `which python3.6`

**Comment by ilovezfs** [comment]
@asottile It seems to be the same problem as pseudo-solved here: https://github.com/Homebrew/homebrew-core/pull/20902#issuecomment-346264148

@zmwangx more virtualenv :boom:

**Comment by asottile** [comment]
boom! that looks like exactly that -- maybe we should make a helper (or the default?) to un-relativize the symlinks at post-install?

**Comment by ilovezfs** [comment]
@asottile that makes it so things have to be revision bumped every time you sneeze :(

**Comment by asottile** [comment]
Hmmm, I'm not seeing why that would require more version bumps than today -- doesn't post-install just run on the client?

Just to be clear, I'm not suggesting *copying* the files, just fixing up the symlinks to be non-relative after unpacking the bottle.

**Comment by ilovezfs** [comment]
@asottile can you test this please? https://github.com/Homebrew/homebrew-core/pull/21392

**Comment by asottile** [comment]
sure! what's the tl;dr for attempting to use that?

**Comment by ilovezfs** [comment]
`brew pull 21392`

**Comment by ilovezfs** [comment]
Then `brew upgrade -s pre-commit`

**Comment by asottile** [comment]
yeah doesn't work unfortunately :( `PYTHONPATH` causes more problems than this solves

**Comment by ilovezfs** [comment]
That's odd. It was using that way of installing up until September 2016 ... never heard any complaints from you about that. See https://github.com/Homebrew/homebrew-core/pull/4410

**Comment by ilovezfs** [comment]
Also we clearly need some kind of better test block #21392 passes just fine with the current one.

**Comment by asottile** [comment]
yeah I can look to improve the test situation from brew side.  Here's the issue that we had with `PYTHONPATH` (it got magically fixed when brew switched to virtualenv approach): https://github.com/pre-commit/pre-commit/issues/359

**Comment by ilovezfs** [comment]
:(

**Comment by asottile** [comment]
I'll hack at post-install and see what I can come up with.  This issue isn't terribly high priority for now but figured I'd document what I've figured out in case others run into similar things.

**Comment by ilovezfs** [comment]
@asottile how's this https://github.com/Homebrew/homebrew-core/pull/21404

**Comment by asottile** [comment]
:shipit: thanks a million

I'll follow up with some tests from our side (expect a PR \~\*\~\*eventually\*\~\*\~): https://github.com/pre-commit/pre-commit/issues/669

**Comment by ilovezfs** [comment]
@asottile no problem. Yes, a test for the relative path problem and the PYTHONPATH problem would be good. It would also be good if we could figure out how to get this working properly without resorting to virtualenv.
