### ISSUE TITLE
mpv not compiled with lua support

### ISSUE THREAD

**Issue by inflation** [Homebrew/homebrew-core#21388]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/66c0f584d3db08e184ce3090c189c265
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew upgrade`
- What happened (include command output)
Updated `mpv` and found that all functionalities related to `lua` are not available.
- What you expected to happen
The behavior should be the same.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install mpv`
Then try to provide options like `--ytdl` or `--osc`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by DomT4** [comment]
```
Checking for Lua                                                  : no ('luajit >= 2.0.0' not found)
```

```
    --lua=LUA_VER       select Lua package which should be autodetected. Choices: 51 51deb 51obsd 51fbsd 52 52deb 52arch
                        52fbsd luajit
```

```
[cplayer] List of enabled features: apple-remote asm atomics avutil-content-light-level avutil-icc-profile avutil-imgcpy-uc avutil-spherical bsd-fstatfs build-date cocoa coreaudio cplayer cplugins cuda-hwaccel debug-build encoding fchmod gl gl-cocoa glob glob-posix gnuc iconv is_ffmpeg jpeg lcms2 libass libass-osd libav libavcodec libavdevice libdl libm libmpv-shared macos-touchbar nanosleep optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn pthreads shm stdatomic termios videotoolbox-gl videotoolbox-hwaccel videotoolbox-hwaccel-new zlib zsh-comp
```

Yup. Fixed by https://github.com/Homebrew/homebrew-core/pull/21389.

**Comment by CounterPillow** [comment]
This is not an upstream issue.

**Comment by ilovezfs** [comment]
@CounterPillow the tag means an upstream issue report needs to be created.

**Comment by Argon-** [comment]
Does this suffice? https://github.com/mpv-player/mpv/pull/1914#issuecomment-98686501
All in all, mpv does not intend to support lua 5.3. Not now and not in the foreseeable future, as far as I know.

**Comment by ilovezfs** [comment]
That is a closed issue from over two years ago. There needs to be a current, open issue. If there's zero upstream intent to support the current lua version at some point soon, then we could just remove lua support from the formula, I suppose.

**Comment by Argon-** [comment]
That's what I tried to say, there is currently 0 effort going on to support lua 5.3. This doesn't mean that a good PR would be rejected (as you can see from the linked one, technical issues prevented merging it, not the fact it was lua 5.3). But so far I don't see one on the horizon and nobody interested in creating one.

While lua is technically an optional dependency of mpv, without it you actually loose so much functionality that I wouldn't consider a build without lua useful as mpv already ships with built-in lua scripts. No lua means no streaming, no youtube/other video websites, no on screen controller, no stats, no user scripts.

**Comment by JCount** [comment]
@Argon- What about switching to using what about switching to using `LuaJIT`? It is Lua 5.1 ABI compatible, and is still being actively "maintained".

**Comment by Argon-** [comment]
I would actually like that but there were problems: https://github.com/mpv-player/mpv/issues/1110#issuecomment-302879492
Back then, I didn't investigate as nobody was interested in having luajit support on OSX and normal lua was fast enough for me. Maybe these problems are magically resolved by now, who knows...

**Comment by ilovezfs** [comment]
Upstream issue here: https://github.com/mpv-player/mpv/issues/5205
