### ISSUE TITLE
Yajl symlink is not properly set.

### ISSUE THREAD

**Issue by xbeta** [Homebrew/homebrew-core#21446]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
brew gist-logs yajl
Error: No logs.
```

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Symlink for `yajl` is not linked.  (`/usr/local/lib/libyajl.dylib`)

- What happened (include command output)

```
$ brew install yajl
Warning: yajl 2.1.0 is already installed
```

```
$ pip install yajl-py==1.0.11
Collecting yajl-py==1.0.11
  Downloading https://pypi.uberinternal.com/packages/f0/95/5f3865e641c28ada51fffde53bc408b44580aa6d3a8b67a7b9f9ab46143c/yajl-py-1.0.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_7/012jt6r14771z1_zwpm4hxfh0000gn/T/pip-build-XJTZnZ/yajl-py/setup.py", line 4, in <module>
        from yajl import __version__ as version
      File "yajl/__init__.py", line 13, in <module>
        from yajl_common import *
      File "yajl/yajl_common.py", line 50, in <module>
        yajl = load_yajl()
      File "yajl/yajl_common.py", line 37, in load_yajl
        raise OSError('Yajl shared object cannot be found. '
    OSError: Yajl shared object cannot be found. Please install Yajl and confirm it is on your shared lib path.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_7/012jt6r14771z1_zwpm4hxfh0000gn/T/pip-build-XJTZnZ/yajl-py/
```

- What you expected to happen
After manually symlink it, it seems to be working now

```
$ sudo ln -s /usr/local/lib/libyajl.2.1.0.dylib /usr/local/lib/libyajl.dylib
$ pip install yajl-py==1.0.11
Collecting yajl-py==1.0.11
  Downloading https://pypi.uberinternal.com/packages/f0/95/5f3865e641c28ada51fffde53bc408b44580aa6d3a8b67a7b9f9ab46143c/yajl-py-1.0.11.tar.gz
Building wheels for collected packages: yajl-py
  Running setup.py bdist_wheel for yajl-py ... done
  Stored in directory: /Users/samxiao/Library/Caches/pip/wheels/f9/02/c3/2a526e692b0eb0043453e9a999b5c1c7e99056f939e1582195
Successfully built yajl-py
Installing collected packages: yajl-py
Successfully installed yajl-py-1.0.11
```

- Step-by-step reproduction instructions (by running `brew install` commands)
(See above)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
Symlinks are present here:

```
$ brew install yajl
==> Downloading https://homebrew.bintray.com/bottles/yajl-2.1.0.high_sierra.bottle.4.tar.gz
######################################################################## 100.0%
==> Pouring yajl-2.1.0.high_sierra.bottle.4.tar.gz
🍺  /usr/local/Cellar/yajl/2.1.0: 18 files, 173.6KB
$ ll /usr/local/lib/libyajl*     
lrwxr-xr-x  1 fx  staff    44B Dec 13 14:22 /usr/local/lib/libyajl.2.1.0.dylib -> ../Cellar/yajl/2.1.0/lib/libyajl.2.1.0.dylib
lrwxr-xr-x  1 fx  staff    40B Dec 13 14:22 /usr/local/lib/libyajl.2.dylib -> ../Cellar/yajl/2.1.0/lib/libyajl.2.dylib
lrwxr-xr-x  1 fx  staff    38B Dec 13 14:22 /usr/local/lib/libyajl.dylib -> ../Cellar/yajl/2.1.0/lib/libyajl.dylib
lrwxr-xr-x  1 fx  staff    36B Dec 13 14:22 /usr/local/lib/libyajl_s.a -> ../Cellar/yajl/2.1.0/lib/libyajl_s.a
```

Does the problem persist if you uninstall and reinstall `yawl`? What is the output of `brew config` and `brew doctor`?
