### ISSUE TITLE
cannot install macVim on mac high sierra

### ISSUE THREAD

**Issue by oohogwash** [Homebrew/homebrew-core#21468]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by oohogwash** [comment]
It appears not to be supported on the current macbook pro.
I have removed the file and various other items, no luck it appears this file is bad if you believe Brew.


gavans-MBP:ISA 95 gavan1$ sudo brew install macvim
Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-103.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapsh
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ad6cdee1178d4b8fddc126eb209481710803256f6826913c4bbc30224e290e0b
Actual: 5df21d0c16fd9b33fa291250bce2e8456261ccf6869070be8901002d655fb30a
Archive: /Library/Caches/Homebrew/macvim-7.4-103.tar.gz
To retry an incomplete download, remove the file above.

**Comment by chdiza** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by ilovezfs** [comment]
Your Homebrew installation is severely outdated. Please `brew update` and fill out the issue template completely if you still need help.

**Comment by oohogwash** [comment]
I have run that  already, I tried uninstalling brew.
Now it won’t reinstall. It does not have permission to make its updates on install.
The idea of not running under sudo is not working on this version of mac  os - high sierra

On 10 Dec 2017, at 1:51 am, ilovezfs <notifications@github.com> wrote:

Your Homebrew installation is severely outdated. Please brew update and fill out the issue template completely if you still need help.

**Comment by oohogwash** [comment]
I updated the check list as you required.
