### ISSUE TITLE
httpd not starting with mongodb 1.3.4 extension: Segmentation Fault 11

### ISSUE THREAD

**Issue by sibidharan** [Homebrew/homebrew-core#21475]
I did a `brew upgrade` today. After that I tried to start my apache using `sudo apachectl start` and it didn't work. Again I tried `sudo apachectl -k restart`, there was an error related to PHP MPM, I cleared it with a reinstall of php71. 

Now I tried to start apache, it didn't show any errors, and it didn't start.

I then tried turning it up manually using `sudo httpd -X -k restart`

Sadly the output was:

httpd not running, trying to start
Segmentation fault: 11

I have no clue what is wrong or I screwed it up. Then I tried the same on my another development mac. The same happened. 

Please fix it. All our development environments are unusable now.

**UPDATE**

During the upgrade, the mongodb (php71-mongodb 1.3.4) driver version 1.3.4 was installed, which I believe is causing the issue. Disabling it is can start the server.

**Comment by sibidharan** [comment]
This has nothing to do with httpd! It's mongodb driver issue https://github.com/mongodb/mongo-php-driver/issues/682

**Comment by sibidharan** [comment]
This has nothing to do with httpd! It's mongodb driver issue https://github.com/mongodb/mongo-php-driver/issues/682

**Comment by sibidharan** [comment]
https://github.com/Homebrew/homebrew-core/pull/16067 -  Already addressed

**Comment by sibidharan** [comment]
https://github.com/mongodb/mongo-php-driver/issues/682

**Comment by sibidharan** [comment]
As far as I understand, httpd is trying to access BoringSSL instead of OpenSSL that is causing the crash! mongodb/mongo-php-driver#682 https://github.com/Homebrew/homebrew-core/pull/16067

**Comment by sibidharan** [comment]
As I said in mongodb/mongo-php-driver#682

The issue is with Apache for sure.

I tried adding MongoDB Driver (mongodb.so 1.3.4) to conf.d and executed few php codes on CLI. They were all working perfectly.

The issue is there only when it's loaded via httpd, it crashes with Segmentation Fault 11.

So the suspect is Apache.

As said by @jmikola in https://github.com/mongodb/mongo-php-driver/issues/681,

> Based on your otool -L output you provided and the fact that Apache, PHP, and the driver have all been installed via Homebrew, I believe you're facing the same issue as @adamwinn in https://github.com/mongodb/mongo-php-driver/issues/682. Please read https://github.com/mongodb/mongo-php-driver/issues/682 (comment) onward (note that I incorrectly assumed he was using the macOS version of httpd in the first comment linked).
To reiterate here, the root cause of this is httpd loading BoringSSL at runtime, despite PHP and its extensions being compiled against OpenSSL. I don't understand why a version of Apache installed through Homebrew would not utilize Homebrew's OpenSSL library, but that's something I've asked @adamwinn to follow up on (with the Apache formula maintainers).

This has to be fixed with high priority as lot of people are affected by this issue.

**Comment by sibidharan** [comment]
I have created temporary workaround to keep the development going as suggested by @jmikola. Check if this might be useful for you @adamwinn 

## Summary

Instead of `php7_module`, let's proxy it using `php-fpm`. Because the `php7_module` and `mongodb.so` is what causing `httpd` to crash with `Segmentation Fault 11`. But if we run PHP in CLI, the extension fires up without any issues. So I thought of using `php-fpm` to proxy the handler, by keeing your existing `.htaccess` configuration intact (if you have it). If you have used `php_value` directives in `.htaccess`, just wrap it around `<IfModule php7_module />`, because we are going to disable this module till a permanent fix for this issue is out.

## Here is what I did

Edit Apache main conf file: `$(brew --prefix)/etc/httpd/httpd.conf`

    a. Uncomment: `LoadModule proxy_module  lib/httpd/modules/mod_proxy.so`
    b. Uncomment: `LoadModule proxy_fcgi_module  lib/httpd/modules/mod_proxy_fcgi.so`
    c. Uncomment: `LoadModule vhost_alias_module  lib/httpd/modules/mod_vhost_alias.so`
    d. Uncomment: `Include /usr/local/etc/httpd/extra/httpd-vhosts.conf` (If applicable)
    e. Comment Out: `LoadModule php7_module        /usr/local/../libphp7.so`

Inside your <VirtualHost> directive, commonly under file `$(brew --prefix)/etc/httpd/httpd/extra/httpd-vhosts.conf`,

```
<VirtualHost *:80>
    DocumentRoot "/path/to/webroot"
    ServerName webserver.dev
    ErrorLog "/usr/local/var/logs/webserver-error_log"
    CustomLog "/usr/local/var/logs/webserver-error_log" common
    <Directory "/path/to/webroot">
            Options Indexes FollowSymLinks ExecCGI Includes
            AllowOverride All
            Require all granted
            #JUST ADD EVERYTHING YOU WANT AS YOU NEED
    </Directory>
    <LocationMatch "^(.*\.php)$">
            ProxyPass fcgi://127.0.0.1:8000/path/to/webroot
    </LocationMatch>
</VirtualHost>
```

## Configuring PHP-FPM

PHP-FPM's configuration file is located at `$(brew --prefix)/etc/php/7.1/php-fpm.conf`. The default configuration is fine for most purposes, but you may want to edit it to suit your needs. For example, some parameters you may want to tune are `pm.start_servers` (number of child processes at startup), `pm.max_spare_servers` (maximum number of idle server processes), `pm.max_requests` (maximum number of requests each child process should execute before respawning), etc…

You must change `listen = 127.0.0.1:9000` to `listen = listen = 127.0.0.1:8000` in `php-fpm.conf` because of a bug that keeps default port of `fcgi` to 8000 (Reference https://bugzilla.redhat.com/show_bug.cgi?id=1224763)

_PS: Unix sock didn't work, I don't know why. I didn't try it as it worked with port 8000, I wanted to resolve it and keep my development going._

More importantly, you can change the pool configuration file `$(brew --prefix)/etc/php/7.1/php-fpm.d/www.conf` and replace the values for `user` and `group` to your user name and "staff" as group. This will avoid permission and ownership of files in your document root.

## Testing PHP-FPM with Apache

You may check that PHP-FPM is configured correctly by running the following:

```
php-fpm -y $(brew --prefix)/etc/php/7.1/php-fpm.conf -t
```

If it says ok/success, you are all set. 

Now finally execute, `brew services start httpd && brew services start php71` to start the services, or if required, restart them. If you want to restart `httpd` alone, use `sudo apachectl -k restart`. 

In some cases you might need to run php-fpm manually for debugging purposes, try `php-fpm --fpm-config $(brew --prefix)/etc/php/7.1/php-fpm.conf`

Expecting this issue to be resolved soon!!

**Comment by sibidharan** [comment]
**The following process fixed the issue with php-mongodb driver (temporary workaround)**

We are simply compiling the packages with system SSL instead of Homebrew OpenSSL. 

http://mongoc.org/libmongoc/current/installing.html#building-on-mac-os-x - install libmongoc, it must be the system library for building mongodb driver from source.

http://mongoc.org/libbson/current/installing.html - install libbson (must have been installed by libmongoc, but just in case)

```
$ brew remove httpd
$ brew reinstall --build-from-source php71 --with-httpd --with-homebrew-libressl

#compile mongodb driver 
$ git clone https://github.com/mongodb/mongo-php-driver.git
$ git checkout 048d6efa75852ab573ef5dc08267d3e3a3dfb114
$ cd mongo-php-driver
$ git submodule sync && git submodule update --init
$ sudo phpize
$ ./configure --with-libmongoc=yes --with-libbson=yes --with-openssl-dir=/usr
$ make clean
$ sudo make install
```

Now link the mongodb.so library to php. Restart apache. Enjoy!! :) :)

**Comment by LMCom** [comment]
@sibidharan Thx! This worked for MAMP PRO. I only compiled the mongodb driver.

**Comment by ilovezfs** [comment]
We'll be happy to review a PR fixing this, but it needs to be reported to httpd upstream.

**Comment by eboye** [comment]
@sibidharan thank you thank you thank you! :) Working on brew httpd+php72 on High Sierra

**Comment by formigone** [comment]
I'm following your @sibidharan 's instructions, but getting the following error at the end of `./configure --`

    ...
    checking whether to use system libbson... yes
    checking whether to use system libmongoc... yes
    checking for pkg-config... /usr/local/bin/pkg-config
    checking for libbson... version 1.9.0 found
    checking configuring libmongoc... ...
    checking for pkg-config... (cached) /usr/local/bin/pkg-config
    checking for libmongoc... configure: error: pkgconfig and mongoc must be installed

I already have `pkg-config` installed:

    $ brew install pkgconfig
    Warning: pkg-config 0.29.2 is already installed

Ideas?

**Comment by formigone** [comment]
Also, since I already have `pkg-config` and `mongoc` installed, I've tried

    $ ./configure --with-openssl-dir=/usr

But that errors out as follows:

    ...
    checking whether to enable developer build flags... no
    checking whether to enable code coverage... no
    checking whether to use system libbson... no
    checking whether to use system libmongoc... no
    checking configuring libmongoc... ...
    checking for pkg-config... /usr/local/bin/pkg-config
    configure: error: Cannot find OpenSSL's <evp.h>

**Comment by sibidharan** [comment]
Must be because of the system ssl libs. Try installing libressl manually using homebrew and set the openssl dir for its bin's parent folder. 

Must work.

**Comment by formigone** [comment]
Great. Thanks for your help. I had installed `mongo-c-driver` as listed, but had not realized that not all files had been linked because of permissions. Changing directory permissions and trying the `brew install` again did the trick. Thanks again.

**Comment by vazgen** [comment]
Make sure that **brew link** was successful

**Comment by navneetdixit07** [comment]
Same issue when using homebrew to install mongodb driver with MAMP 4.2.1 on High Sierra 10.13.1 on php7.1.8. 
Apache not start after including extension on php.ini file but mysql is running.

Same process running on another machine only the OS is diffrent OS X Yosemite.

**Comment by sibidharan** [comment]
Recompile MongoDB driver as instructed above. It will fix your problem.

**Comment by navneetdixit07** [comment]
Thanks @sibidharan , its working now.
