### ISSUE TITLE
mpv won't update after 0.27.0_1

### ISSUE THREAD

**Issue by Diskutant** [Homebrew/homebrew-core#21500]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [-] Ran `brew doctor`, fixed all issues and retried your prior step?
Couldn't fix everything, I think that would break stuff, here is the output:

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/var/pyenv/shims/python-config
  /usr/local/var/pyenv/shims/python2-config
  /usr/local/var/pyenv/shims/python2.7-config
  /usr/local/var/pyenv/shims/python3-config
  /usr/local/var/pyenv/shims/python3.4-config
  /usr/local/var/pyenv/shims/python3.4m-config
  /usr/local/var/pyenv/shims/python3.6-config
  /usr/local/var/pyenv/shims/python3.6m-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  advancemenu
  python
  python3
```

- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/Diskutant/b641e15126f06f10c346875ed4ac5eea

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
upgrading mpv from 0.27.0_1 to 0.27.0_3 (had the same issue with _2)

- What happened (include command output)

```
brew upgrade
==> Upgrading 1 outdated package, with result:
mpv 0.27.0_3
==> Upgrading mpv --with-bundle --with-vapoursynth
==> Downloading https://github.com/mpv-player/mpv/archive/v0.27.0.tar.gz
Already downloaded: /Users/snake/Library/Caches/Homebrew/mpv-0.27.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/25/7b5484aca5d46915493f1fd4ecb63c38c333bd32aa9ad6e19da8d08895
Already downloaded: /Users/snake/Library/Caches/Homebrew/mpv--docutils-0.13.1.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/mpv-20171209-25385-8w2lad/mpv-0.27.0/vend
==> ./bootstrap.py
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/0.27.0_3 --enable-zsh-comp --enable-libmpv-shared --enable-html
==> python3 waf install
Last 15 lines from /Users/snake/Library/Logs/Homebrew/mpv/04.python3:
+ install /usr/local/Cellar/mpv/0.27.0_3/share/mpv/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
Traceback (most recent call last):
  File "/private/tmp/mpv-20171209-25385-8w2lad/mpv-0.27.0/vendor/bin/rst2man.py", line 21, in <module>
    from docutils.core import publish_cmdline, default_description
ModuleNotFoundError: No module named 'docutils'

Traceback (most recent call last):
  File "/private/tmp/mpv-20171209-25385-8w2lad/mpv-0.27.0/vendor/bin/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
ModuleNotFoundError: No module named 'docutils'

Waf: Leaving directory `/private/tmp/mpv-20171209-25385-8w2lad/mpv-0.27.0/build'
Build failed
 -> task in 'rst2man' failed with exit status 1 (run with -v to display more information)
 -> task in 'rst2html' failed with exit status 1 (run with -v to display more information)

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

- What you expected to happen
get the latest mpv version

- Step-by-step reproduction instructions (by running `brew install` commands)
brew upgrade

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
I cannot reproduce this. It may be something non-standard about your python environment.

**Comment by ilovezfs** [comment]
@DomT4 are you able to reproduce this?

**Comment by Diskutant** [comment]
got it to work now.
When it didn't work I had pyenv set to 

```
pyenv version
3.6.2 (set by /usr/local/var/pyenv/version)
3.4.7 (set by /usr/local/var/pyenv/version)
2.7.14 (set by /usr/local/var/pyenv/version)
```

after I set `pyenv global 2.7.14` I was able to update mpv.

**Comment by ilovezfs** [comment]
Does the former configuration make `python` itself mean `python3`?

**Comment by Diskutant** [comment]
```
pyenv global 3.6.2 3.4.7 2.7.14

pyenv version
3.6.2 (set by /usr/local/var/pyenv/version)
3.4.7 (set by /usr/local/var/pyenv/version)
2.7.14 (set by /usr/local/var/pyenv/version)

python --version
Python 3.6.2

type python
python is /usr/local/var/pyenv/shims/python

python3 --version
Python 3.6.2

type python3
python3 is /usr/local/var/pyenv/shims/python3
```

does this help?

**Comment by ilovezfs** [comment]
OK so brew has trouble if the generic `python` binary is some version of python 3. I recall @zmwangx pointed that out a few months ago. I'm glad you were able to resolve the problem.

**Comment by sashkab** [comment]
That makes sense... but errors could be improved.

**Comment by zmwangx** [comment]
I did not look at the details of this issue, but my former, detailed analysis of the python3-as-default situation is https://github.com/Homebrew/brew/issues/2958. Never got around to working on a fix though. I've been sporting this patch the whole time:

```diff
diff --git a/Library/Homebrew/requirements/python_requirement.rb b/Library/Homebrew/requirements/python_requirement.rb
index c162b072c9..5223455a13 100644
--- a/Library/Homebrew/requirements/python_requirement.rb
+++ b/Library/Homebrew/requirements/python_requirement.rb
@@ -46,7 +46,7 @@ class PythonRequirement < Requirement
   end
 
   def python_binary
-    "python"
+    "python2.7"
   end
 
   # Deprecated
```

**Comment by zmwangx** [comment]
(Anyway, py27 EOL is, interestingly, only 27 months away, so if we just wait it out it will resolve itself in 27 months...)

**Comment by navidR** [comment]
This problem has not been solved.

**Comment by ilovezfs** [comment]
@navidR if you're having a problem, please file a new issue and fill out the issue template completely.
