### ISSUE TITLE
pass does not allow installation of extensions

### ISSUE THREAD

**Issue by arcnmx** [Homebrew/homebrew-core#21606]
[`pass`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pass.rb) looks for extensions in `$(LIBDIR)/password-store/extensions/*.bash`. This path is generated inside its `make install` rule and includes the full cellar prefix. This seems to prevent any other formula from installing extensions into the more general `HOMEBREW_PREFIX/lib/password-store/extensions`.

> To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

um, I would if I knew what the right approach here is... Using `DESTDIR=` and `PREFIX=` would solve this, but I'm not sure if that's the homebrew way of doing things since it would require the package to be `brew link`ed to work. Is that something to avoid? Alternatively some sort of post install step could `sed -i` the file and insert the right path?

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by arcnmx** [comment]
I've fixed this with a pretty hacky approach to the problem in my personal tap: https://github.com/arcnmx/homebrew-formulae/commit/d9fa7fae489ab05d1a91f7e9af4cdea7da83f75a

**Comment by ilovezfs** [comment]
You'll need to report this upstream to `pass` and request a way to set the extensions directory with an argument to `make`.

**Comment by alfiepates** [comment]
@arcnmx FWIW, I’d suggest looking into `gopass`; it’s `pass`-compatible, does TOTP (which is the extension you’re looking for, right? ;) ), and is a little more actively developer.

I’ve put a few patches/bug reports to the `pass` dev before, with no response - I don’t feel like this will get fixed upstream.
