### ISSUE TITLE
Pandoc bottle fails installation, triggers build from source

### ISSUE THREAD

**Issue by peterdimou** [Homebrew/homebrew-core#21648]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
    - gist: https://gist.github.com/anonymous/6d87c0593764e0e6bb433f383062d282

- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
    - Upgrade pandoc to new version via `brew upgrade`
- What happened (include command output)
    - pandoc failed installation and triggered a build from source
    - Output: 
```bash
==> Upgrading 1 outdated package, with result:
pandoc 2.0.5
==> Upgrading pandoc
==> Downloading https://homebrew.bintray.com/bottles/pandoc-2.0.5.high_sierra.bo
######################################################################## 100.0%
==> Pouring pandoc-2.0.5.high_sierra.bottle.tar.gz
Error: Invalid argument
Warning: Bottle installation failed: building from source.
```
- What you expected to happen
    - pandoc package to be upgraded via bottle
- Step-by-step reproduction instructions (by running `brew install` commands)
    - `brew update && brew install pandoc`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
What's the output of
```
brew doctor
```

**Comment by peterdimou** [comment]
```bash
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php56
  php71
  php55
```

Explanation: I link and unlink php versions to switch between them

**Comment by ilovezfs** [comment]
Can you try
```
brew rm pandoc
brew install -dv pandoc
```
and post output please

**Comment by peterdimou** [comment]
```bash
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cabal-install.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
==> Downloading https://homebrew.bintray.com/bottles/pandoc-2.0.5.high_sierra.bottle.tar.gz
Already downloaded: /Users/USER/Library/Caches/Homebrew/pandoc-2.0.5.high_sierra.bottle.tar.gz
==> Verifying pandoc-2.0.5.high_sierra.bottle.tar.gz checksum
==> Pouring pandoc-2.0.5.high_sierra.bottle.tar.gz
tar xzf /Users/padtwc/Library/Caches/Homebrew/pandoc-2.0.5.high_sierra.bottle.tar.gz
==> Finishing up
ln -s ../../Cellar/pandoc/2.0.5/etc/bash_completion.d/pandoc pandoc
ln -s ../Cellar/pandoc/2.0.5/bin/pandoc pandoc
ln -s ../../Cellar/pandoc/2.0.5/share/doc/x86_64-osx-ghc-8.2.2 x86_64-osx-ghc-8.2.2
ln -s ../../../Cellar/pandoc/2.0.5/share/man/man1/pandoc.1 pandoc.1
ln -s ../Cellar/pandoc/2.0.5/share/x86_64-osx-ghc-8.2.2 x86_64-osx-ghc-8.2.2
/usr/bin/sandbox-exec -f /tmp/homebrew20171214-94172-11ktodx.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc.rb -dv
/usr/local/Homebrew/Library/Homebrew/postinstall.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc.rb
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/pandoc/2.0.5: 166 files, 63.7MB
```

It appears to have been installed successfully

**Comment by ilovezfs** [comment]
Cool. So probably some weird transient issue. Please let us know if you see it happen again.
