### ISSUE TITLE
couchdb install does not create /usr/local/etc/couchdb config directory

### ISSUE THREAD

**Issue by feltech** [Homebrew/homebrew-core#21732]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew gist-logs couchdb
Error: No logs.
```
```
$ brew config
HOMEBREW_VERSION: 1.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: f42d8acde3907b90ea32cef01445744288984a4c
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ec65b1cea3e20327770b2657c3194606bd444712
Core tap last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_40
macOS: 10.13.2-x86_64
Xcode: 9.0.1
CLT: 9.0.1.0.1.1506734476
X11: N/A
```
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.


Warning: Your Xcode (9.0.1) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.

Warning: Calling BottleSpecification.revision is deprecated!
Use BottleSpecification.rebuild instead.
/usr/local/Homebrew/Library/Taps/scivisum/homebrew-tap/Formula/vncsnapshot-png.rb:14:in `block in <class:VncsnapshotPng>'
Please report this to the scivisum/tap tap!


Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install cairo fdk-aac fontconfig fribidi glib gobject-introspection graphite2 harfbuzz libass libffi libvidstab pixman

Run `brew missing` for more details.
```
(I don't think the warnings above are relevant to this issue)

I am trying to `brew install couchdb`. 

The install appears to work fine, but couchdb cannot start.  The install does not create the ` /usr/local/etc/couchdb` directory.  Looking at the formula, I can't see anywhere where this is created explicitly, though other directories are (i.e.  /usr/local/{var,lib,run}/couchdb).

This means couchdb does not start with 
```
$ /usr/local/opt/couchdb/bin/couchdb
{"init terminating in do_boot",{{badmatch,{error,{bad_return,{{couch_app,start,[normal,["/usr/local/etc/couchdb/default.ini","/usr/local/etc/couchdb/local.ini"]]},{'EXIT',{{badmatch,{error,{error,enoent}}},[{couch_server_sup,start_server,1,[{file,"couch_server_sup.erl"},{line,56}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}}},[{couch,start,0,[{file,"couch.erl"},{line,18}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()
```
The salient bit is `enoent`.  I copied the ` /usr/local/etc/couchdb` directory from an install with an older version on another machine (1.6.1_9) and modified the `default.ini` file to update the library path.  This allowed couchdb to start fine.

**Comment by ilovezfs** [comment]
Yes it needs to be rebottled.

**Comment by ilovezfs** [comment]
brew reinstall -s couchdb will fix it for you locally

**Comment by feltech** [comment]
Thanks, that did the trick.

**Comment by ilovezfs** [comment]
@feltech the bottle is rebuilt. Thanks for reporting this @feltech!
