### ISSUE TITLE
configure: error: ZLIB extension requires gzgets in zlib --with-httpd Mac OS X 10.13.2 High Sierra

### ISSUE THREAD

**Issue by ginko** [Homebrew/homebrew-core#21775]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] Ran `brew update` and retried your prior step?
- [x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I'm running into issues installing php56 with the --with-httpd option. The error is configure: error: ZLIB extension requires gzgets in zlib.

I'm running Mac OS X 10.13.2 High Sierra. I've tried php72 as well and the result is the same. My xCode command line tools are up to date. I tried all the options mentioned above in vain not sure what else to do. I really hope someone can help.

This is the logout put link
https://gist.github.com/ginko/ad953ab78931173abb44e9d6c2f8b212

**Comment by ilovezfs** [comment]
Please let the php tap know here: https://github.com/Homebrew/homebrew-php/issues/
