### ISSUE TITLE
caveat ERROR with clamav

### ISSUE THREAD

**Issue by echavanne-symantec** [Homebrew/homebrew-core#21778]
I am attempting to install clamav using brew. Here is my sample commands and the output. I have run brew update (twice) and brew doctor. No errors are shown. Thank you

```
M2673380YF5MW:~$ brew update
Already up-to-date.
M2673380YF5MW:~$ brew update
Already up-to-date.
M2673380YF5MW:~$ brew doctor
Your system is ready to brew.
M2673380YF5MW:~$ brew install clamav
Error: clamav: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clamav.rb:56: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clamav.rb:57: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    To finish installation & run clamav you will need to edit
                                       ^
M2673380YF5MW:~$ brew gist-logs clamav
Error: clamav: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clamav.rb:56: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clamav.rb:57: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    To finish installation & run clamav you will need to edit
                                       ^
```

**Comment by fxcoudert** [comment]
Can you show us the output of `brew config`?

**Comment by echavanne-symantec** [comment]
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 4 months ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d51c2a96571873866a110085d43e1a1eec4467da
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_144
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: N/A

**Comment by fxcoudert** [comment]
So, you're stuck with Homebrew 1.3.1 (while the latest is 1.4.0), and it's using system ruby 2.0 instead of homebrew-portable ruby 2.3. The later is why you're getting this syntax error.

Now, I'm not sure why this happened. A reinstall would definitely fix it. Maybe a cleverer maintainer can find a smaller hammer to hit that nail :)

**Comment by echavanne-symantec** [comment]
No problem, I can reinstall. Thanks

**Comment by echavanne-symantec** [comment]
... I missed the edit and went straight for the reinstall. Worked with the fresh install though.
