### ISSUE TITLE
graphviz snapshot URL is 404; they moved; can't find any versioned URLs

### ISSUE THREAD

**Issue by dreness** [Homebrew/homebrew-core#21777]
(I'm turning this template upside down for reasons that will be apparent very shortly)

The URL in the formula is 404. Witness:
```
$ curl --head https://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.1.tar.gz
HTTP/2 404 
date: Fri, 15 Dec 2017 21:15:34 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d67a7581d241781473d02a58f2071733a1513372534; expires=Sat, 15-Dec-18 21:15:34 GMT; path=/; domain=.graphviz.org; HttpOnly
vary: Origin
x-content-type-options: nosniff
server: cloudflare-nginx
cf-ray: 3cdc6b422e4a6e56-SJC
```
I couldn't find any versioned snapshot URLs for graphviz at their new location (gitlab.io). Instead, I see only:
```
$ curl --head https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz
HTTP/2 200 
accept-ranges: bytes
cache-control: max-age=600
content-type: application/x-gzip
expires: Fri, 15 Dec 2017 21:28:55 UTC
last-modified: Thu, 07 Dec 2017 20:47:09 GMT
vary: Origin
content-length: 25633455
date: Fri, 15 Dec 2017 21:18:55 GMT
```
Simply replacing the URL in the graphviz formula with the above isn't enough, however, because brew can't parse the version from the filename. I was also unable to use debug mode when installing to manually push things through, I guess because this problem is before the install phase.

I ended up manually downloading the archive from the new URL, placing it in the cache directory (brew --cache), and then renaming the file to graphviz-2.40.1.tar.gz. The checksum is the same as the one currently specified in the formula. At this point I was able to successfully install graphviz.

I have no idea what the right way is to solve this, but that's how I worked around it.

Here's the template:

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [-] Ran `brew doctor`, fixed all issues and retried your prior step?
- [-] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [-] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

(I'm confident this problem has nothing to do with my local state, and I understand why doctor is balking - not related to this.)

To help us debug your issue please explain:
- What you were trying to do (and why): install graphviz
- What happened (include command output): The snapshot URL in the formula is 404. I'm not including the actual brew failure logs because I already worked around this to install it, and don't want to do that again.
- What you expected to happen: normal installation
- Step-by-step reproduction instructions (by running `brew install` commands)
```brew install graphviz```

**Comment by DomT4** [comment]
Looks like the URL is now `https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz`, which presumably changes instantly every new release. Perfect 🙄.

**Comment by ilovezfs** [comment]
hopefully just a temporary situation since every package manager under the sun seems to be using the versioned urls

https://github.com/Homebrew/homebrew-core/pull/21793
