### ISSUE TITLE
"node: command not found" after completing "brew install node"

### ISSUE THREAD

**Issue by mrengy** [Homebrew/homebrew-core#218]
I just installed Homebrew today, and I ran 'brew update'. Here's version info:
```
Homebrew 0.9.9 (git revision 4a7c; last commit 2016-04-11)
Homebrew/homebrew-core (git revision 530b; last commit 2016-04-11)
```

I'm on Mac OS 10.6 (I know it's old, but not sure this computer can handle El Capitan) with [GCC](https://gcc.gnu.org/) installed. Her's [output from 'xcode-select --version' and 'gcc --version'](https://gist.github.com/mrengy/eefed84fe87f4279cfa3815c7e1f7312)

Here's [output from 'brew doctor'](https://gist.github.com/mrengy/09f6a827e3fee72125a7f84ea6efe8d2).

When I run 'node -v', I get '-bash: node: command not found'.

Uninstalling and reinstalling node doesn't seem to work. Here's the [full output of when I run 'brew uninstall node' and then 'brew install node'](https://gist.github.com/mrengy/22c776d6855dd34533f778d66bfb05e7) .

One thing that seems maybe useful is this line:
`make: *** [Python/mactoolboxglue.o] Error 1
`
I saw some suggestions for other operating systems to reinstall XCode when getting this error, but can I resolve this without installing XCode and relying on GCC? I'm trying to save some hard drive space.

**Comment by DomT4** [comment]
Oh, Python is failing to build, and you need a more recent Python to build Node on that OS X version than the system one, which is the problem. Maybe @tdsmith has some thoughts there.

Can't make promises though, 10.6 isn't officially supported by that much any more, including us and Apple.

**Comment by tdsmith** [comment]
I don't know why Python doesn't build on 10.6, sorry.

**Comment by mrengy** [comment]
All right. Well, thanks for helping me identify the problem.

**Comment by DomT4** [comment]
It seems the Python team upstream are providing a 10.6-compatible package on their website. Maybe it's worth filing your bug report with them or dropping an applicable mailing list an email to ask for some ideas; they may find a `brew gist-logs python` useful.

I make no promises that they'll be interested though, can't speak for them.

**Comment by mrengy** [comment]
Okay, I realize this is a closed issue and on a non-supported operating system, but wondering if anyone has insight into a new error. I installed python 2.7.6 from a .dmg , which seemed to work. Now when I run 'brew install node', I get a different error. Here's the [full output](https://gist.github.com/mrengy/63d4b842e568691584b064ecd8537078).

It's a lot of lines similar to:
`../deps/openssl/asm_obsolete/x64-macosx-gas/aes/aesni-x86_64.s:3508:missing or invalid immediate expression `0b00010000' taken as 0
../deps/openssl/asm_obsolete/x64-macosx-gas/aes/aesni-x86_64.s:3508:suffix or operands invalid for `shufps'`

and then 
`make[1]: *** [/private/tmp/node20160414-85630-dkku9n/node-v5.10.1/out/Release/obj.target/openssl/deps/openssl/asm_obsolete/x64-macosx-gas/aes/aesni-x86_64.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [node] Error 2`

**Comment by DomT4** [comment]
Looks like they may not have backported the build fixes for older OS X versions that OpenSSL applied post-release. That one is worth asking Node themselves about I'm afraid 😢.
