### ISSUE TITLE
Install GTK with X11 support

### ISSUE THREAD

**Issue by raxod502** [Homebrew/homebrew-core#21826]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step? **(not applicable)**
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **(not relevant, since I am not reporting an error)**
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? **(not applicable)**

## Question

Is there any way to install formula `gtk+` or `gtk+3` with `x11` support, specifically so that the header file `gdk/gdkx.h` will be installed to `/usr/local/include`? I could not find an option for this in either formula, nor any other formulae which looked relevant, nor any promising taps.

Thus I am wondering if this is a use case which is not officially supported by Homebrew, and if so what the recommended alternatives are.

**Comment by ilovezfs** [comment]
X11 support was removed from GTK stuff in Homebrew a while ago and it's all now Quartz only.

**Comment by ilovezfs** [comment]
>Thus I am wondering if this is a use case which is not officially supported by Homebrew, and if so what the recommended alternatives are.

I think MacPorts still has GTK X11 variants.
