### ISSUE TITLE
installing mongodb 3.6 on MacOS 10.11 El Capitan fails

### ISSUE THREAD

**Issue by obaratch** [Homebrew/homebrew-core#21889]
homebrew-core/Formula/mongodb.rb

On El Capitan, installation fails because the formula requires XCode 8.3.2, while 8.3.x is only available for MacOS Sierra (10.12) and above.  The [official MongoDB document](https://docs.mongodb.com/manual/tutorial/install-mongodb-on-os-x/) states, however, that the requirement is Lion (10.7).  I personally think Lion is a little too far back but El Capitan is too new to be unsupported.

FYI, I tried the change below but it faild.
```
depends_on :xcode => ["8.2.0", :build]
```

**Comment by ilovezfs** [comment]
It might work on Lion if built with a 10.7 deployment target outside of Homebrew. But in Homebrew, the bottles are intended for the platform they're built on, so if the build-time requirement is >= Xcode 8.2, then we'll only have bottles for >= 10.12.
