### ISSUE TITLE
Installing php56 via Homebrew not working with Apache 2.4

### ISSUE THREAD

**Issue by xingped** [Homebrew/homebrew-core#219]
# Please follow the general troubleshooting steps first:

- [ X ] Ran `brew update` and retried your prior step?
- [ X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ X ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Installing php56 via homebrew results in php 5.6.20 being installed, but when used with Apache 2.4.16 and included in the httpd.conf file with the line:
`LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so`
it results in the following error from `apachectl configtest`: 

`httpd: Syntax error on line 171 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _ldap_control_find\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP\n in /usr/local/opt/php56/libexec/apache2/libphp5.so`

The line referenced is the LoadModule line above. OS is: Mac OS X v10.10.4.

`brew gist-logs php56`:
"Error: No Logs"

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-php#3095
