### ISSUE TITLE
Error executing ttyrec on macOS 10.13

### ISSUE THREAD

**Issue by srguglielmo** [Homebrew/homebrew-core#21907]
Hello,

I installed the `ttyrec` formula using `brew install ttyrec`. The install completes successfully. However, when I execute the `ttyrec` command in my shell (zsh, also installed via Homebrew), I receive the error `Out of pty's` and `ttyrec` exits with code 143.

I tested this with a "vanilla" zsh shell by running `zsh -f` (bypassing my `~/.zshrc`), then `ttyrec`. The error still occurred. The same problem with `/bin/bash` as well.

Note, I ran `brew gist-logs ttyrec`, however, it reported that there were no logs. See https://gist.github.com/srguglielmo/4ee962ae205b8c291160027f9a9e74d3

Thanks

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by fxcoudert** [comment]
Issue is fixed, use `brew upgrade`

**Comment by srguglielmo** [comment]
Confirmed it's fixed. Thank you!
