### ISSUE TITLE
android-sdk formula has an implicit hardcoded dependency on android-build-tools 23.0.1

### ISSUE THREAD

**Issue by amitkot** [Homebrew/homebrew-core#2192]
When updating the android build tools using Android's SDK manager, this version of android-build-tools might no longer be available.

Furthermore, such updates made by Android's SDK manager will not reflect when using android tools from the terminal, as they have been replaced by wrappers (e.g. [zipalign](https://github.com/Homebrew/homebrew-core/blob/master/Formula/android-sdk.rb#L49)).

**Comment by amitkot** [comment]
In addition, the android-build-tools version currently being used (23.0.1) is no longer available for installing from the android SDK tool, meaning the installation command suggested:
```bash
android update sdk --no-ui --filter 'build-tools-23.0.1'
```
fails with:
```
Error: Ignoring unknown package filter 'build-tools-23.0.1'
```

**Comment by tdsmith** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? [This document](https://git.io/vo2xc) should give you a head start and we'd be more than happy to walk you through it if you have any questions.

**Comment by ilovezfs** [comment]
```
Do you accept the license 'android-sdk-license-c81a61d9' [y/n]: 
Installing Archives:
  Preparing to install archives
  Downloading Android SDK Platform-tools, revision 24.0.1
  Installing Android SDK Platform-tools, revision 24.0.1
  Stopping ADB server failed (code -1).
    Installed Android SDK Platform-tools, revision 24.0.199%)
  Downloading Android SDK Build-tools, revision 23.0.1
  Installing Android SDK Build-tools, revision 23.0.1
    Installed Android SDK Build-tools, revision 23.0.199%)
    Stopping ADB server succeeded.
    Starting ADB server succeeded.
  Done. 2 packages installed.
```
Looks like it's fine.

And the hard-coded part is intentional:
```
  def build_tools_version
    "23.0.1"
  end
```
@amitkot are you still seeing a problem, because this all looks like it's working as intended.

**Comment by amitkot** [comment]
Sorry, it's a month later I'm too out of context now to get into it again.
Thanks!
