### ISSUE TITLE
wine formula builds resources without parallelisation

### ISSUE THREAD

**Issue by barreyra** [Homebrew/homebrew-core#21924]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

As far as I can tell, when doing a `brew install wine --devel`, `brew` is not building wine's resources in parallel, causing a really long build.

While we are at it, I wanted to know why the dependencies are "inlined" for wine? This should at least be documented in the formula as a comment.

**Comment by ilovezfs** [comment]
We don't do any resource builds in parallel. They're all vendored in wine because everything must be built as universal binaries. I suggest you use the bottle.

**Comment by barreyra** [comment]
I don't mean building two resources in parallel. The issue is that I see is that each resource is being built without "make -j".

A bottle is not available for the non-X11 version.

**Comment by ilovezfs** [comment]
The `make -j` is implicit: https://github.com/Homebrew/brew/blob/b806a53d88938ab2d2aeb5e96651ed6d47efcdf9/Library/Homebrew/extend/ENV/super.rb#L41
