### ISSUE TITLE
Squashfs doesn't support LZMA

### ISSUE THREAD

**Issue by alexandernst** [Homebrew/homebrew-core#21957]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to extract a SquashFS file that was created with LZMA compression.

- What happened (include command output)

The file didn't extract because current squashfs package doesn't support LZMA.

```
→ unsquashfs unsquash/150000.squashfs
Filesystem uses lzma compression, this is unsupported by this version
Decompressors available:
	gzip
	lzo
	xz
```

- What you expected to happen

I expect `unsquash` to extract my file.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install squashs
unsquashfs some_squashfs_file_with_lzma_compression.squashfs
```

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/21958
