### ISSUE TITLE
llvm@3.9 does not support libcxxabi

### ISSUE THREAD

**Issue by yiakwy** [Homebrew/homebrew-core#21997]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

This formula has problems to support libcxxabi, because the ruby formula does not contain the libcxxabi sources. Could you show me the minimum codes to support that. Here is a example from homebrew legacy but I don't know how to generate the hashcode. Look forward to your reply.

**Comment by fxcoudert** [comment]
One caveat: llvm@3.9 is a legacy version we include for specific software dependencies.

What is it exactly that you're trying to do and is not working?

**Comment by yiakwy** [comment]
@fxcoudert I resolved libcxxabi problem without referring to the libcxxapi.dylib/so in Makefile and everything works well when I built boost and protobuf as local libraries. 

When I edit llvm@3.9.rb, I found there is no url about libcxxabi, a subproject from llvm. I think some people might suffer from it.
