### ISSUE TITLE
graphviz: library not found for -ltclstub8.6

### ISSUE THREAD

**Issue by jeffs** [Homebrew/homebrew-core#2204]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

`brew install graphviz --with-gts` fails because "library not found for -ltclstub8.6".

    ~ $ brew gist-logs graphviz
    https://gist.github.com/f75e7682e7d3413fe7f9238ce498c23f

I have libtclstub 8.5 in /usr/lib, and versions 8.4 and 8.5 apparently came with XCode and Tcl.framework, but I do not have version 8.6 anywhere.

**Comment by UniqMartin** [comment]
But you seem to have Tcl/Tk 8.6 installed and there is a binary named `/usr/local/bin/tclsh8.6` on your system. Where does that come from? In any case, there seems to be a problem with this Tcl/Tk installation (that is being picked up by the `graphviz` build process) as simply running `tclsh8.6` from the command line will also complain about a missing library. Any ideas about that?

**Comment by jeffs** [comment]
Thanks Martin, and sorry for the slow reply.

You're right.  I have no idea how /usr/local/bin/tclsh8.6 came to exist on
my machine, but it was broken. [1]  After removing it, I was able to
install graphviz with GTS.

[1]
$  /usr/local/bin/tclsh8.6
dyld: Library not loaded: /usr/local/lib/libtcl8.6.dylib
  Referenced from: /usr/local/bin/tclsh8.6
  Reason: image not found
Trace/BPT trap: 5

On Tue, Jun 21, 2016 at 12:03 AM, Martin Afanasjew <notifications@github.com
> wrote:

> But you seem to have Tcl/Tk 8.6 installed and there is a binary named
> /usr/local/bin/tclsh8.6 on your system. Where does that come from? In any
> case, there seems to be a problem with this Tcl/Tk installation (that is
> being picked up by the graphviz build process) as simply running tclsh8.6
> from the command line will also complain about a missing library. Any ideas
> about that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Homebrew/homebrew-core/issues/2204#issuecomment-227335223>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAEUmdSfOKp8SEr02hj1yz7G7WLRfIx-ks5qN2KpgaJpZM4I6B9Y>
> .
>



-- 

[image: Orchard Platform] <http://www.orchardplatform.com/>

Jeffrey Schwab / Senior Software Engineer
(617) 407-2542 / jeff@orchardplatform.com

Orchard Platform
101 5th Avenue, 4th Floor, New York, NY 10003
http://www.orchardplatform.com

[image: Twitter]  <https://twitter.com/orchardplatform>[image: Linkedin]
<https://www.linkedin.com/company/orchard-app>

Orchard Blog <http://www.orchardplatform.com/blog/> | Marketplace Lending
Meetup <http://www.meetup.com/Peer-to-Peer-Lending-P2P/>

-- 
*NOTICE TO RECIPIENTS*: This communication is confidential and intended for 
the use of the addressee only. If you are not an intended recipient of this 
communication, please delete it immediately and notify the sender by return 
email. Unauthorized reading, dissemination, distribution or copying of this 
communication is prohibited. This communication does not constitute an 
offer to sell or a solicitation of an indication of interest to purchase 
any loan, security or any other financial product or instrument, nor is it 
an offer to sell or a solicitation of an indication of interest to purchase 
any products or services to any persons who are prohibited from receiving 
such information under applicable law. The contents of this communication 
may not be accurate or complete and are subject to change without notice. 
As such, Orchard App, Inc. (including its subsidiaries and affiliates, 
"Orchard") makes no representation regarding the accuracy or completeness 
of the information contained herein. The intended recipient is advised to 
consult its own professional advisors, including those specializing in 
legal, tax and accounting matters. Orchard does not provide legal, tax or 
accounting advice.

**Comment by UniqMartin** [comment]
No worries; I'm glad we were able to resolve this!
