### ISSUE TITLE
brew update of major release

### ISSUE THREAD

**Issue by dpwildboar** [Homebrew/homebrew-core#22055]
brew update

I think much like brew link that there should be some form of --force when new major releases become the default, or require that you specifically state that you want to upgrade the major release. the latter being my preference.

an example of where this would be useful is postgres. brew has 10.1 now is the default.  however most production solutions will probably be stuck in version 9 for a while. at least for me I like keeping my development machine in a world parallel to what the production machines are at.

instead of doing the major release update that it instead would say something along the line of if you want to upgrade postgres either specifically state you want to do a postgres upgrade or provide --force as an option.

**Comment by ilovezfs** [comment]
Our approach to this is @ formulae.

`brew install postgresql@9.4` or
`brew install postgresql@9.5` or
`brew install postgresql@9.6`

if you need to stay on an older version than 10.1.

**Comment by dpwildboar** [comment]
yes, I know that now... after spending. a lot of time trying to undo what it did. but, tbh, I almost feel like being able to state just brew install postgresql with out the @x.x sets up someone for failure in the future.  that for some software that at minimum you have to state software@major or software@major.minor.  I can see how for some software you wouldn't want to be bothered by this detail...

**Comment by ilovezfs** [comment]
You may be interested in testing https://github.com/Homebrew/homebrew-core/pull/21244

**Comment by dpwildboar** [comment]
if I understand what that is saying by seebq, this could be some flavor of what I would want. the example is is pretty much the opposite of what I am asking for thou. development for a production system I would tend to want to stick in the major or major.minor that was on the production system.  I would only want to switch to the current major.minor when I wanted to test how things might break if I did the upgrade.

but, that said what seems to be discussed there is of interest.  anything that would better aid the brew user to flip between versions I think would be of merit.  as a consultant I tend to have to support several versions of postgres, running something in 9.3 (ubuntu 14 LTS installs that version) or 9.5 (for ubuntu 16) etc, etc, etc... means that taking something from 10.1 that works, doesn't always mean that it would work once I put it out on the server that has 9.5 on it.  it's one of the reasons that software like RVM is/was popular amongst rails developers and similar tools exist out there for other development environments.

**Comment by ilovezfs** [comment]
You may want to have multiple installations of Homebrew itself in different prefixes, and use `direnv`.

```
Josephs-MacBook-Pro:~ joe$ brew --prefix
/usr/local
Josephs-MacBook-Pro:~ joe$ cd ~/Developer/bfpr
direnv: loading .envrc
direnv: export +BROWSER ~HOMEBREW_RUBY_PATH ~PATH
Josephs-MacBook-Pro:bfpr joe$ brew --prefix
/Users/joe/Developer/bfpr/brew
Josephs-MacBook-Pro:bfpr joe$
```

**Comment by dpwildboar** [comment]
interesting. I think I will spend some time tying this out.  thanks. =)

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/brew/blob/master/docs/Installation.md#alternative-installs

**Comment by MikeMcQuaid** [comment]
https://github.com/Homebrew/homebrew-core/pull/21244 has been merged.
