### ISSUE TITLE
mtr tries to install to nonexistant directory

### ISSUE THREAD

**Issue by icco** [Homebrew/homebrew-core#22085]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

no output

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.4.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4d43e950fd45c24e48d6ebfd3013357abcd21a9
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7a4212fee1386f3d9f35c95c46e36fdccce56480
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_TOKEN: set
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/nat/.rvm/rubies/ruby-2.4.1/bin/ruby
Java: 1.8.0_121
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: N/A
X11: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mtr
```

To help us debug your issue please explain:
- What you were trying to do (and why)

brew install mtr

- What happened (include command output)

```
$ brew install mtr
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, caskroom/versions, caskroom/cask).
==> New Formulae
bcftools                                                             diamond                                                              travis
==> Updated Formulae
git ✔                  youtube-dl ✔           chamber                fish                   gitbucket              menhir                 pipenv                 spdlog                 vault
rclone ✔               ack                    chronograf             getdns                 haproxy                parallel               rebar@3                texmath

==> Downloading https://homebrew.bintray.com/bottles/mtr-0.92.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mtr-0.92.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink sbin/mtr
/usr/local/sbin is not writable.

You can try again using:
  brew link mtr
==> Caveats
mtr requires root privileges so you will need to run `sudo mtr`.
You should be certain that you trust any software you grant root privileges.
==> Summary
🍺  /usr/local/Cellar/mtr/0.92: 12 files, 181.8KB
```

It looks like mtr is trying to be installed into `/usr/local/sbin` which doesn't exist. 

```
$ ll /usr/local/
total 0
drwxrwxr-x   25 nat   admin   800B Nov  9 14:40 Caskroom
drwxrwxr-x   93 nat   admin   2.9K Dec 23 16:54 Cellar
drwxrwxr-x    3 nat   admin    96B Nov  9 14:38 Frameworks
drwxrwxr-x   17 nat   admin   544B Dec 18 21:58 Homebrew
drwxr-xr-x    6 root  wheel   192B Dec 20 10:53 MacGPG2
drwxrwxr-x  436 nat   admin    14K Dec 19 17:46 bin
drwxrwxr-x   18 nat   admin   576B Nov  9 14:40 etc
drwxrwxr-x  113 nat   staff   3.5K Dec 18 22:19 include
drwxrwxr-x  223 nat   staff   7.0K Dec 18 22:19 lib
drwxrwxr-x  115 nat   admin   3.6K Dec 23 16:54 opt
drwxr-xr-x    3 root  wheel    96B Nov  9 14:39 remotedesktop
drwxrwxr-x   40 nat   admin   1.3K Dec 18 22:19 share
drwxrwxr-x    6 nat   admin   192B Nov  9 14:38 var
```
- What you expected to happen

sbin to be created before attempting to be written to.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install mtr`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by JCount** [comment]
@icco I don't know what happened, but you should have a `/usr/local/sbin` directory that was created when you installed Homebrew. It must have been removed at some point somehow.

You can recreate it now using the following commands. :
```
sudo mkdir /usr/local/sbin && \
sudo chmod ug+rwx /usr/local/sbin && \
sudo chown $(id -un):admin /usr/local/sbin
```
You will want to add it the directory to your PATH, given it is necessary for `mtr` to function properly.
