### ISSUE TITLE
Nomad - missing built-in UI

### ISSUE THREAD

**Issue by aantono** [Homebrew/homebrew-core#22121]
after installing nomad using `brew install nomad` version 0.7.1 has been installed.  However, upon starting the app via `nomad agent -dev` and going to `http://127.0.0.1:4646/ui` no UI gets displayed.  The same url shows a Nomad built-in UI when using an official binary downloaded from https://releases.hashicorp.com/nomad/0.7.1/nomad_0.7.1_darwin_amd64.zip

**Comment by ilovezfs** [comment]
Right. The README https://github.com/hashicorp/nomad/blob/master/README.md says you need to run `make dev-ui` or `make release` for that, and it introduces dependencies on Node, Yarn, and Ember CLI. Feel free to open a PR.
