### ISSUE TITLE
Qt formula uses incorrect tarball filename in the mirror URL

### ISSUE THREAD

**Issue by nurupo** [Homebrew/homebrew-core#22145]
Just a heads-up that Qt changed the filename of their tarball in 5.10.0 version. The `mirror` in https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb links to a non-existent tarball, it should be `qt-everywhere-src-5.10.0.tar.xz` instead of `qt-everywhere-opensource-src-5.10.0.tar.xz`. The `url` variable is correct, I guess someone fixed the `url` but forgot to fix the `mirror`.

Not a mac nor homebrew user, just passing by after googling "qt-everywhere-opensource-src-5.10.0.tar.xz" since I had similar issue of not being able to find `qt-everywhere-opensource-src-5.10.0.tar.xz` on Qt servers.

**Comment by ilovezfs** [comment]
Fixed in 57d57d6bfa. Thanks for the heads up @nurupo!
