### ISSUE TITLE
SHA256 mismatch for libdap

### ISSUE THREAD

**Issue by hectorlee** [Homebrew/homebrew-core#22162]
There's a SHA256 mismatch for libdap. Encountered this while installing gdal on Mac OS 10.10.5. I'm unsure of the correct procedure for this. Should the SHA256 in the formula be updated?

```
brew install libdap
==> Downloading https://www.opendap.org/pub/source/libdap-3.19.1.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 5215434bacf385ba3f7445494ce400a5ade3995533d8d38bb97fcef1478ad33e
Actual: fb7014b6047cf3fa47d05c0faf258636f664c5fc232ff0886a78dfc5aae29f8f
```

**Comment by ilovezfs** [comment]
Please create an issue upstream to rule out malicious circumstances and to find out why the file changed.

**Comment by hectorlee** [comment]
Issue created. Waiting for a response.

[https://github.com/OPENDAP/libdap4/issues/37](https://github.com/OPENDAP/libdap4/issues/37)

**Comment by ilovezfs** [comment]
Checksum is back to normal:
```
iMac-TMP:~ joe$ brew fetch -fs libdap
==> Downloading https://www.opendap.org/pub/source/libdap-3.19.1.tar.gz
######################################################################## 100.0%
Downloaded to: /Users/joe/Library/Caches/Homebrew/libdap-3.19.1.tar.gz
SHA256: 5215434bacf385ba3f7445494ce400a5ade3995533d8d38bb97fcef1478ad33e
iMac-TMP:~ joe$
```
Explanation of what happened is here: https://github.com/OPENDAP/libdap4/issues/37#issuecomment-354315468
