### ISSUE TITLE
Alexa Skill AVS Installation Error

### ISSUE THREAD

**Issue by AndresMolina999** [Homebrew/homebrew-core#22249]
**# Hello!
I have followed the instructions of how to set up AVS SDK on MacOs from the following link:**
https://github.com/alexa/avs-device-sdk/wiki/macOS-Quick-Start-Guide

**But when I get to step 4 (try to run the SampleApp) it gives me the following error:**

Jairos-MBP:~ jairomolina$ alexac
dyld: Library not loaded: @rpath/libDefaultClient.dylib
  Referenced from: /Users/jairomolina/sdk-folder/sdk-build/SampleApp/src/SampleApp
  Reason: image not found
Abort trap: 6

**This is how my ./bash_profile looks like:**
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"

alias alexac="/Users/jairomolina/sdk-folder/sdk-build/SampleApp/src/SampleApp Users/jairomolina/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json"

alias alexacdebug="/Users/jairomolina/sdk-folder/sdk-build]/SampleApp/src/SampleApp /Users/jairomolina/sdk-folder/sdk-build/Integration/AlexaClientSDKConfig.json DEBUG9"

**Please help me, thank you!**

**Comment by ilovezfs** [comment]
You'll need to ask your question here: https://github.com/alexa/avs-device-sdk/issues
