### ISSUE TITLE
Error installing botan --with-debug 

### ISSUE THREAD

**Issue by labdlau** [Homebrew/homebrew-core#22262]
DrHalftone:~ dllau$ brew install botan --with-debug
==> Downloading https://botan.randombit.net/releases/Botan-2.3.0.tgz
######################################################################## 100.0%
==> ./configure.py --prefix=/usr/local/Cellar/botan/2.3.0 --docdir=share/doc --cpu=x86_64 --cc=clang --os=darwin --with-openssl --with-zlib --with-bzip2 --enable-debug
Last 15 lines from /Users/dllau/Library/Logs/Homebrew/botan/01.configure.py:

./configure.py
--prefix=/usr/local/Cellar/botan/2.3.0
--docdir=share/doc
--cpu=x86_64
--cc=clang
--os=darwin
--with-openssl
--with-zlib
--with-bzip2
--enable-debug

Usage: configure.py [options]

configure.py: error: no such option: --enable-debug

READ THIS: https://docs.brew.sh/Troubleshooting.html

**Comment by rakkesh** [comment]
Replace line 46 in formula file - 
```rb
args << "--with-debug" if build.with? "debug"
```

with

```rb
args << "--with-debug-info" << "--debug-mode" if build.with? "debug"
```

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
