### ISSUE TITLE
Ghostscript 9.22 is missing document file 'VectorDevices.htm' (among others)

### ISSUE THREAD

**Issue by jasidles** [Homebrew/homebrew-core#22272]
**BUG**   As of December 30, 2017, `brew install ghostscript`, version 9.22, apparently is  missing the following `*.htm` (documentation) files:
```
SavedPages.htm
VectorDevices.htm
sample_downscale_device.htm
subclass.htm
```
**SIGNIFICANCE** The missing file `VectorDevices.htm` is especially regretted, because it is the sole documentation for a considerable number of ghostscript idioms that emulate Adobe's `distiller`, in particular the (much-used) `gs` argument `-dPDFSETTINGS=<...>`.

**WORKAROUND** The missing documentationfiles  can be downloaded as a tarball from the web page "[Ghostscript 9.22 Source for all platforms](https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs922/ghostscript-9.22.tar.gz )", then unpacked to a folder named (for example) `~/Downloads/ghostscript-9.22`.  The above list of missing files was produced by:

```
DFROM='~/Downloads/ghostscript-9.22/doc'
DTO='/usr/local/share/ghostscript/9.22/doc'
FLIST="$(sudo diff -q "${DFROM}" "${DTO}" | grep Only | cut -d ' ' -f 4 | grep .htm)"
printf '%s\n' $FLIST
```
Moving the four missing files to `/usr/local/share/ghostscript/9.22/doc` solved the problem.

**Comment by ilovezfs** [comment]
@jasidles this is an upstream issue. See http://git.ghostscript.com/?p=ghostpdl.git;a=blob;f=base/unixinst.mak;h=fcc12224d1d3c520206c0b47195ff387f03b81bc;hb=HEAD#l148 which is missing the files you referenced from the list. Please report it to ghostscript here: https://bugs.ghostscript.com/describecomponents.cgi?product=Ghostscript
