### ISSUE TITLE
pdf2htmlex tests currently broken on Jenkins

### ISSUE THREAD

**Issue by lemzwerg** [Homebrew/homebrew-core#22331]
While trying to submit [an update to ttfautohint](https://github.com/Homebrew/homebrew-core/pull/22321), Jenkins fails with
```
failed: brew test --verbose pdf2htmlex
```
cf. https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/15720/

This problem is not related to ttfautohint in any way (except that pdf2htmlex depends on ttfautohint).  Looking into Jenkins's log files, it seems that pdf2htmlex has a problem with fontforge and readline...

Besides fixing this problem it would be great if the log messages of Jenkins could be improved with something like
```
testing packages that depend on ttfautohint
  pdf2htmlex: ...
```

**Comment by ilovezfs** [comment]
Yes see https://github.com/Homebrew/homebrew-core/pull/22321#issuecomment-354710604.

**Comment by ilovezfs** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/pull/22333.

**Comment by lemzwerg** [comment]
Thanks for the quick fix!
