### ISSUE TITLE
gdbm 1.13 is needed until 1.14 is supported by Python

### ISSUE THREAD

**Issue by sam-s** [Homebrew/homebrew-core#22369]
# Problem:

Python does not work with gdbm 1.14: https://bugs.python.org/issue32484

# Solution:

Either roll back to 1.13 (seems stupid) or provide 1.13 as an alternative version (dunno how).

**Comment by sam-s** [comment]
workaround:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6938c5e3ed0b91bd63de7035b5d5afb57b5942a4/Formula/gdbm.rb
```

**Comment by ilovezfs** [comment]
@sam-s this is now fixed if you `brew update` and `brew upgrade`.

**Comment by ilovezfs** [comment]
Thanks for reporting it!
