### ISSUE TITLE
--build-from-source insists on brew's python for magic-wormhole

### ISSUE THREAD

**Issue by resistor4u** [Homebrew/homebrew-core#22373]
brew config =
`HOMEBREW_VERSION: 1.4.2`
`ORIGIN: https://github.com/Homebrew/brew`
`HEAD: 4e08da95c34c27ba6d5ca5f80718fe2788337cdf`
`Last commit: 2 days ago`
`Core tap ORIGIN: https://github.com/Homebrew/homebrew-core`
`Core tap HEAD: 72d94f77652457a4dc6cd5eaf9b07b1e16147fc1`
`Core tap last commit: 10 hours ago`
`HOMEBREW_PREFIX: /usr/local`
`HOMEBREW_CASK_OPTS: --appdir=/Applications`
`HOMEBREW_DEV_CMD_RUN: 1`
`HOMEBREW_GITHUB_API_TOKEN: set`
`HOMEBREW_NO_AUTO_UPDATE: 1`
`CPU: quad-core 64-bit ivybridge`
`Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby`
`Clang: 8.0 build 800`
`Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git`
`Curl: 7.43.0 => /usr/bin/curl`
`Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl`
`Python: /usr/bin/python`
`Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby`
`Java: 1.8.0_66`
`macOS: 10.11.6-x86_64`
`Xcode: 8.2.1`
`CLT: 8.2.0.0.1.1480973914`
`X11: 2.7.11 => /opt/X11`

running `brew install --build-from-source magic-wormhole` insists on brewing python2 and doesn't seem to respect the system python. shouldn't `--build-from-source` force the formula to use the system python? i'm trying with `brew edit magic-wormhole` to comment-out `depends_on "python"`, but i'm not sure that's a good solution.

**Comment by DomT4** [comment]
Support for the system Python has been deprecated, or is being deprecated, I think.

**Comment by ilovezfs** [comment]
The `:python` requirement, which can cause a divergence between source builds and the bottles, has been deprecated as of

https://github.com/Homebrew/brew/pull/3612
https://github.com/Homebrew/homebrew-core/pull/22355

If you experience a problem with Homebrew's python other than not wanting to use it, please file an issue.
