### ISSUE TITLE
Latest python broke vim/macvim?

### ISSUE THREAD

**Issue by 9mm** [Homebrew/homebrew-core#22411]
**Gists**

- vim: no logs
- macvim: no logs
- python: https://gist.github.com/185814d1a41b0a16424a0428a408887b

**Problem**

After the latest Python installed, python isn't available to Vim and Macvim anymore.

When I run `:python print "hi"` it says `Sorry, this command is disabled, the Python's site module could not be loaded.' Also, lots of bundles that require python obviously dump all the errors to output.

I've tried the following to fix it:

  brew uninstall python python3 vim macvim
  brew cleanup
  brew update
  brew install python
  brew install python3
  brew install vim
  brew install macvim

And it still doesn't work. I've encountered python issues before with homebrew and vim, and reinstalling it always worked, but this time something is weird. 

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by 9mm** [comment]
Ooops... didn't mean to hit enter.. editing fast

**Comment by 9mm** [comment]
fixed

**Comment by ilovezfs** [comment]
brew reinstall -s macvim should fix it

**Comment by 9mm** [comment]
Oh snap... what is the `-s` option? It's not anywhere in `man brew` that I can see?

**Comment by ilovezfs** [comment]
it's shortcut for `--build-from-source`.

This is now fixed via https://github.com/Homebrew/homebrew-core/pull/22413 if you `brew update` and `brew upgrade`

**Comment by 9mm** [comment]
Nice! Thanks so much
