### ISSUE TITLE
freeradius-server use python2

### ISSUE THREAD

**Issue by palmerc** [Homebrew/homebrew-core#22417]
## freeradius-server rlm_python

In `src/modules/rlm_python` you have the option to configure the python binary used by freeradius's python module with the configure switch `--with-rlm-python-bin=`. There are also switches for `--with-rlm-python-lib-dir=` and `--with-rlm-python-include-dir=`.

In the world of brew we're calling python, `python2`,  so the main configure script never finds the python installation and you end up pointing at the system python binary which isn't desirable. This also results in a runtime error since freeradius is looking for `libpython2.7.so` instead of the associated `.dylib`.

> Python version: 2.7.10 (default, Jul 15 2017, 17:16:57)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
> Failed loading libpython2.7.so: dlopen(libpython2.7.so, 10): image not found
> Failed loading libpython symbols into global symbol table

I'm wondering if we should expose the ability to use the brew version of python and if the python module shouldn't be configured in `install` to use python2 before running the main configure in the formula. 

I edited the formula like this:

```
rlm_python_args = %W[
  --with-rlm-python-bin=#{Formula["python"].bin}/python2
]
    
pwd = Dir.pwd
Dir.chdir("src/modules/rlm_python")
system "./configure", *rlm_python_args
Dir.chdir(pwd)
```

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
