### ISSUE TITLE
Migrating formulas from homebrew/science 

### ISSUE THREAD

**Issue by nickjhathaway** [Homebrew/homebrew-core#22438]
Hi, 
I wanted to ask a couple of questions about migrating various formulas from homebrew/science. On the homebrew/science page, it says to create a pull request to migrate other widely used formulas, I haven't contributed before or created a formula before so I wanted to make sure I'm doing it correctly before attempting. There are about 20 formulas I wanted to migrate over, should I create a pull request for each one or do all of them in one request to migrate? I haven't created a formula before, is it ok to just copy over the .rb formula file from the commit in homebrew/science before they were deleted or do I need to modify them in any way? 

Any help would be appreciated and sorry for the naivety of my questions. 

Best,
Nick

**Comment by DomT4** [comment]
> formulas

formulae 😉 😸.

> There are about 20 formulas I wanted to migrate over, should I create a pull request for each one or do all of them in one request to migrate? 

One per PR. Commit message something like `<formula>: migrate from homebrew/science`.

> do I need to modify them in any way?

They'll likely need to pass `brew audit --new-formula`, if the handling of the others is representative.

**Comment by nickjhathaway** [comment]
Thanks will do. 

Also, either plural is fine (https://www.merriam-webster.com/dictionary/formulas)

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:Homebrew joe$ ag 'formulas '|wc -l
       1
Josephs-MacBook-Pro:Homebrew joe$ ag 'formulae '|wc -l
     184
```
not in brew world :)

**Comment by nickjhathaway** [comment]
thank you @ilovezfs, your comment has been extremely helpful

**Comment by ilovezfs** [comment]
happy to be of service
