### ISSUE TITLE
Cannot install "enchant --with-python", macOS 10.13.2

### ISSUE THREAD

**Issue by jimmy-biznessapps** [Homebrew/homebrew-core#22443]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Output link: https://gist.github.com/fc38965d78fd9b0225c351c028d39c81
(Note 03.python)**

To help us debug your issue please explain:
- What you were trying to do (and why)
**Install enchant with python support, to use the PyEnchant library.**
- What happened (include command output)
```$brew install enchant --with-python
==> Downloading https://github.com/AbiWord/enchant/releases/download/v2.2.1/enchant-2.2.1.tar.gz
Already downloaded: /Users/jrimmer/Library/Caches/Homebrew/enchant-2.2.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/enchant/2.2.1 --enable-relocatable
==> make install
==> Downloading https://files.pythonhosted.org/packages/source/p/pyenchant/pyenchant-1.6.5.tar.gz
Already downloaded: /Users/jrimmer/Library/Caches/Homebrew/enchant--pyenchant-1.6.5.tar.gz
==> python setup.py install --prefix=/usr/local/Cellar/enchant/2.2.1 --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/jrimmer/Library/Logs/Homebrew/enchant/03.python:
python
setup.py
install
--prefix=/usr/local/Cellar/enchant/2.2.1
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "setup.py", line 195, in <module>
    import enchant
  File "/private/tmp/enchant--pyenchant-20180104-48883-i7gtrj/pyenchant-1.6.5/enchant/__init__.py", line 90, in <module>
    from enchant import _enchant as _e
  File "/private/tmp/enchant--pyenchant-20180104-48883-i7gtrj/pyenchant-1.6.5/enchant/_enchant.py", line 133, in <module>
    raise ImportError("enchant C library not found")
ImportError: enchant C library not found

READ THIS: https://docs.brew.sh/Troubleshooting.html
```
- What you expected to happen
**Enchant + PyEnchant to be installed!**
- Step-by-step reproduction instructions (by running `brew install` commands)
**on latest macOS 10.13.2, open a command line, run "brew update," "brew upgrade," and "brew install enchant --with-python"**

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
should be fixed now if you `brew update`

**Comment by jimmy-biznessapps** [comment]
The good news is, it now installs.

The bad news is, I see the same error when attempting to run "import enchant" from within python:

```
jrimmer@Jimmys-MacBook-Pro.local:~
$which python
/usr/local/bin/python

jrimmer@Jimmys-MacBook-Pro.local:~
$python
Python 2.7.14 (default, Jan  3 2018, 12:57:16) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/enchant/__init__.py", line 92, in <module>
    from enchant import _enchant as _e
  File "/usr/local/lib/python2.7/site-packages/enchant/_enchant.py", line 145, in <module>
    raise ImportError(msg)
ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
>>> 
```

**Comment by ilovezfs** [comment]
right. you have to
```
export PYENCHANT_LIBRARY_PATH=/usr/local/Cellar/enchant/2.2.1/lib/libenchant-2.dylib
```

**Comment by jimmy-biznessapps** [comment]
Ah. That does the trick. Thanks!
