### ISSUE TITLE
Fails to install vim: if_python.c:67:10: fatal error: 'Python.h' file not found

### ISSUE THREAD

**Issue by ahmetb** [Homebrew/homebrew-core#22449]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step? (**see the note at the end**)
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  https://gist.github.com/d70e02e5aaf23b4544d62ad7bba0d3c7 

To help us debug your issue please explain:
- What you were trying to do (and why)

      brew install vim

because I uninstalled it after upgrading to High Sierra. Starting `vim` was failing with error:

```
dyld: Library not loaded: /usr/local/opt/ruby/lib/libruby.2.3.0.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
```

- What happened (include command output)

```
$ ~ brew install vim
==> Downloading https://github.com/vim/vim/archive/v8.0.1400.tar.gz
Already downloaded: /Users/ahmetb/Library/Caches/Homebrew/vim-8.0.1400.tar.gz
==> ./configure --prefix=/Users/ahmetb/.homebrew --mandir=/Users/ahmetb/.homebrew/Cellar/vim/8.0.1400_2/share/man --enable-multibyte --with-tlib=ncurses --enable-cs
==> make
Last 15 lines from /Users/ahmetb/Library/Logs/Homebrew/vim/02.make:
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/undo.o undo.c
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/userfunc.o userfunc.c
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/window.o window.c
clang -c -I. -g  -DPERL_DARWIN -fno-strict-aliasing -fstack-protector  -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE  -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_perl.o auto/if_perl.c
clang -c -I. -g  -DPERL_DARWIN -fno-strict-aliasing -fstack-protector  -I/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE  -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_perlsfio.o if_perlsfio.c
clang -c -I. -I/Users/ahmetb/.homebrew/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_HOME='"/Users/ahmetb/.homebrew/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7"' -fPIE  -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_python.o if_python.c
clang -c -I. -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0 -I/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin17 -DRUBY_VERSION=23 -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/if_ruby.o if_ruby.c
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/netbeans.o netbeans.c
if_python.c:67:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^~~~~~~~~~
1 error generated.
make[1]: *** [objects/if_python.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2
```

- What you expected to happen

no errors

- Step-by-step reproduction instructions (by running `brew install` commands)

      brew uninstall --force vim
      brew install vim

### One thing to add

My brew home directory is not `/usr/local/Cellar`; I host my brew and packages at `$HOME/.homebrew`. Therefore my `brew doctor` output is:

```
$ brew doctor
[...]

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
```

**Comment by japorized** [comment]
Just encountered the same problem. Tried reinstalling a moment ago and it works for me now.

**Comment by ahmetb** [comment]
I still see the same error after doing `brew update` as well. (In fact the error message is now saying this issue might be relevant, which is nice.)

**Comment by ilovezfs** [comment]
@ahmetb what does `brew outdated` say?

**Comment by ilovezfs** [comment]
Yes this is caused by outdated python. The current version is 2.7.14_1 (2.7.14 revision 1) and you have 2.7.14. `brew upgrade python` and the problem will go away.

**Comment by ahmetb** [comment]
Thanks, it looks like the order in which they're declared in the `Brewfile` matters. Once it upgraded `python` and I ran `brew bundle` again, it worked fine.

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid it looks like auto upgrade of formulae satisfying reqs is broken.
