### ISSUE TITLE
brew upgrade docker-completion: Error: v17.12.0-ce tag

### ISSUE THREAD

**Issue by r-chris** [Homebrew/homebrew-core#22452]
- What you were trying to do (and why)
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew upgrade docker-completion
```

- What happened (include command output)
```
Error: v17.12.0-ce tag should be 486a48d2701493bb65385788a291e36febb44ec1
but is actually c97c6d62c26c1da407e3086f0b5d3d866ed308bc
```

- What you expected to happen
Get latest version of the formula installed.
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`?
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs docker-completion`: `Error: No logs.`
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.4.2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4e08da95c34c27ba6d5ca5f80718fe2788337cdf
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4e3600a5d38576036d79406344c5c34e1f4afbd
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.15.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_31
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

**Comment by commitay** [comment]
https://github.com/Homebrew/homebrew-core/pull/22427

**Comment by r-chris** [comment]
Yes, thanks just saw that
