### ISSUE TITLE
crosstool-ng: gmake shim inserted during installation breaks execution

### ISSUE THREAD

**Issue by pspoerri** [Homebrew/homebrew-core#22469]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
```
$ brew doctor
Your system is ready to brew.
```
- [x] Ran `brew gist-logs <formula>` and included the output link? https://gist.github.com/anonymous/716bdd7fa7d9d3024667bc487e0bb527
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   I was trying to run `ct-ng`, the software installed by `crosstool-ng`
- What happened (include command output)
   I got an error:
```
$ ct-ng
/usr/local/bin/ct-ng: line 7: MAKEFLAGS: command not found
/usr/local/bin/ct-ng: line 10: .NOTPARALLEL:: command not found
/usr/local/bin/ct-ng: line 13: MAKEFILE_LIST: command not found
/usr/local/bin/ct-ng: line 13: lastword: command not found
/usr/local/bin/ct-ng: line 13: abspath: command not found
/usr/local/bin/ct-ng: line 13: export: `CT_NG:=': not a valid identifier
/usr/local/bin/ct-ng: line 15: shell: command not found
/usr/local/bin/ct-ng: line 15: export: `CT_TOP_DIR:=': not a valid identifier
/usr/local/bin/ct-ng: line 19: export: `CT_LIB_DIR:=/usr/local/Cellar/crosstool-ng/1.23.0/lib/crosstool-ng-1.23.0': not a valid identifier
/usr/local/bin/ct-ng: line 20: export: `CT_DOC_DIR:=/usr/local/Cellar/crosstool-ng/1.23.0/share/doc/crosstool-ng/crosstool-ng-1.23.0': not a valid identifier
/usr/local/bin/ct-ng: line 23: export: `CT_VERSION:=crosstool-ng-1.23.0': not a valid identifier
/usr/local/bin/ct-ng: line 26: CT_LIB_DIR: command not found
/usr/local/bin/ct-ng: line 26: include: command not found
```
   Tested bash versions: 4.4.12(1)-release (installed with homebrew) and 3.2.57(1)-release (osx)
- What you expected to happen
```
$ ct-ng
This is crosstool-NG version crosstool-ng-1.23.0

Copyright (C) 2008  Yann E. MORIN <yann.morin.1998@free.fr>
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
....
```
- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install crosstool-ng
$ ct-ng
```

# Formula additions or changes

I was able to resolve this issue by replacing the first line in 
```
#!/usr/local/Homebrew/Library/Homebrew/shims/super/gmake -rf
```
with 
```
#!/usr/bin/make -rf
```
or
```
#!/usr/local/bin/gmake -rf
```

For some reason `brew test crosstool-ng` runs it with `make -rf /usr/local/Cellar/crosstool-ng/1.23.0/bin/ct-ng` which avoids the shim: 
```
$ brew test crosstool-ng
Testing crosstool-ng
==> make -rf /usr/local/Cellar/crosstool-ng/1.23.0/bin/ct-ng version
```

This is not a simple change in the formulas because the configuration gets filled in the installation process of `crosstool-ng` probably by either `autoconf` or `automake`. See the [ct-ng.in](https://github.com/crosstool-ng/crosstool-ng/blob/master/ct-ng.in#L1). So either the gmake shim is broken, autoconf has to be adapted or crosstool-ng needs to be adapted with a patch. 

I also don't completely understand what the `gmake` shim is doing and how it could break execution. 
```
#!/bin/bash

if [[ -n "$HOMEBREW_MAKE" && "$HOMEBREW_MAKE" != "make" ]]
then
  export MAKE="$HOMEBREW_MAKE"
else
  MAKE="make"
fi
export HOMEBREW_CCCFG="O$HOMEBREW_CCCFG"
exec xcrun "$MAKE" "$@"
```

Maybe `xcrun` is generating the problem?

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by pspoerri** [comment]
Cool! Thanks!
