### ISSUE TITLE
tcc

### ISSUE THREAD

**Issue by shakna-israel** [Homebrew/homebrew-core#22549]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step? *No effect*
- [X] Ran `brew doctor`, fixed all issues and retried your prior step? *No issues found.*
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/e43d37655dc3b97c4297d0ce1125de63
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Use the TinyCCompiler. Because I like the kind of binaries it can build.

- What happened (include command output)

See below, in the step-by-step. But, the main error seems to be ```missing cr1.o``` and ```missing crti.o```. Something that I've encountered before in TCC broken builds.

- What you expected to happen

hello.c should have been compiled and linked to a.out as a mach binary.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install tcc
```

File: hello.c

```
#include <stdio.h>
int main() {
  printf("Hello, World!");
  return 0;
}
```

```
tcc hello.c
```

Produces:

```
tcc: error: file 'crt1.o' not found
tcc: error: file 'crti.o' not found
In file included from hello.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/stdio.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/cdefs.h:81: warning: #warning "Unsupported compiler detected"
tcc: error: file 'crtn.o' not found
tcc: error: undefined symbol 'printf'
```

---

This might be related to #18493, as I am on High Sierra, but it doesn't seem likely, as the only bug that should cause is a binary output that may not be compatible with High Sierra.

XCode does also seem to be interfering in the process, as it's stdio.h was chosen, rather than tcc's own. Probably some include hierarchy issues.

However, the first error seems the most concerning: crt1.o

So maybe connected with an older tcc issue, and nothing to do with Homebrew: [Debian 632089](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=632089)

And like with that issue, running tcc with the ```-run``` flag does succeed:

```
tcc -run hello.c
```

```
In file included from hello.c:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/stdio.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/cdefs.h:81: warning: #warning "Unsupported compiler detected"
Hello, World!
```

**Comment by fxcoudert** [comment]
tcc 0.9.27 builds fine on High Sierra, but it output a warning every time the compiler is run: `#warning "Unsupported compiler detected"`

**Comment by forthrin** [comment]
I can confirm that `tcc` still has the significant problem described above. Is anyone looking into this?

**Comment by ilovezfs** [comment]
@forthrin nope. Please feel free to do so.
