### ISSUE TITLE
ruby and perl are installing as dependencies of vim despite I specified --without-ruby and --without-perl

### ISSUE THREAD

**Issue by KiYugadgeter** [Homebrew/homebrew-core#22548]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Why perl and ruby are installing as dependencies of vim?
I specified --without-ruby and --without-perl options.

My vim installation command is below:
brew install vim --with-luajit --with-python3 --with-override-system-vi --without-perl --without-ruby --HEAD

https://gist.github.com/KiYugadgeter/46310aed25c303314338db4e9b19b06a

**Comment by ilovezfs** [comment]
Those aren't options in the formula. See `brew info vim`

**Comment by KiYugadgeter** [comment]
@ilovezfs 
Below is result of `brew info vim` on my environment.

There are these options
```
vim: stable 8.0.1400 (bottled), HEAD
Vi 'workalike' with many additional features
https://vim.sourceforge.io/
Conflicts with:
  ex-vi (because vim and ex-vi both install bin/ex and bin/view)
/usr/local/Cellar/vim/HEAD-200ea8f_4 (1,425 files, 22.8MB) *
  Built from source on 2018-01-08 at 21:01:11 with: --with-override-system-vi --with-python3 --without-perl --without-ruby --with-luajit
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb
==> Dependencies
Required: perl, ruby
Recommended: python
Optional: gettext, lua, luajit, python3
==> Options
--with-client-server
	Enable client/server mode
--with-gettext
	Build vim with National Language Support (translated messages, keymaps)
--with-lua
	Build vim with lua support
--with-luajit
	Build with luajit support
--with-override-system-vi
	Override system vi
--with-python3
	Build vim with python3 instead of python[2] support
--with-tcl
	Build vim with tcl support
--without-perl
	Build vim without perl support
--without-python
	Build vim without python support
--without-ruby
	Build vim without ruby support
--HEAD
	Install HEAD version
```

**Comment by ilovezfs** [comment]
Thanks. I see we're creating those options in a loop even though they do nothing.

**Comment by ilovezfs** [comment]
@KiYugadgeter this is now fixed.

**Comment by KiYugadgeter** [comment]
Why these options are deleted?

**Comment by ilovezfs** [comment]
They haven't actually been doing anything for a while.

**Comment by KiYugadgeter** [comment]
When I installed vim with homebrew some month ago, perl and ruby are not required, Why these packages have been required?

**Comment by KiYugadgeter** [comment]
@ilovezfs When I installed vim with homebrew some month ago, perl and ruby are not required, Why these packages have been required?

**Comment by ilovezfs** [comment]
Previously, if you were doing a source build, and didn't have Homebrew `perl` formula or Homebrew `ruby` installed, the system Perl and system Ruby would be used. The bottles were already using Homebrew `perl` and Homebrew `ruby`, though.

**Comment by smancill** [comment]
The options *were* doing something, they were effectively disabling the Ruby and Perl interpreters when doing a source build:

    $ vim --version | grep perl
    -clientserver      +job               -perl              +vertsplit

They were not ignored. And now I am being forced to compile with Perl/Ruby.

**Comment by robotvert** [comment]
Same here, had vim installed since forever with `--without-python` and now doing a simple brew upgrade pulls ruby, perl and their deps. This change is not acceptable because for many ruby hackers out there ruby versions are not managed using homebrew but other tools such as rbenv or rvm.
Also, I don't know the extent of the implications but if none of the plugins that I use actually require perl or ruby then homebrew shouldn't bloat my vim installation. Or in that case we should have some "vim-minimal" recipe like in some linux distributions.

Finally I'm wondering if it's common practice to open a PR and self-merge it on the homebrew project, had it been reviewed by extra pairs of eyes someone would probably have had raised the concern...

**Comment by ilovezfs** [comment]
>This change is not acceptable

You're welcome to maintain a different version in your own tap.
