### ISSUE TITLE
Formulae with URL problems

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#22563]
- [ ] tintin
```
==> Downloading https://downloads.sourceforge.net/project/tintin/TinTin%2B%2B%20Source%20Code/2.01.4/tintin-2.01.4.tar.gz
==> Downloading from https://iweb.dl.sourceforge.net/project/tintin/TinTin%2B%2B%20Source%20Code/2.01.4/tintin-2.01.4.tar.gz
######################################################################## 100.0%
Downloaded to: /Users/joe/Library/Caches/Homebrew/tintin-2.01.4.tar.gz
SHA256: dd22afbff45a93ec399065bae385489131af7e1b6ae8abb28f80d6a03b82ebbc
Warning: Formula reports different SHA256: 7f3eb8237252d1a23c6388e6f9ee2a8a2e79e143b5f5a809700775a45a6c6c55
```
- [x] amdatu-bootstrap #22609
- [x] cadaver #22617
- [x] cloudbees-sdk #22649
- [x] codec2 #22657
- [x] ctunnel #22658
- [x] daq #22612
- [x] dns2tcp #22619
- [x] entr #22611
- [x] fdclone #22615
- [x] i2p
- [x] jhiccup #23344
- [x] libggz #22620
- [x] litmus #22659
- [x] mariadb-connector-c #23160
- [x] mg3a #23348
- [x] mvptree #23349
- [x] neon #23351
- [x] netris #22623
- [x] ppl #23353
- [x] quex #22625
- [x] since
- [x] spigot #22610
- [x] splint #23352
- [x] supermodel #22673
- [x] systemc
- [x] talk-filters #23350
- [x] xshogi #22613

**Comment by commitay** [comment]
`i2p` is working again, I can add a mirror of you want?

**Comment by vinyldarkscratch** [comment]
@commitay Yes, please do!  If you submit a pull request, make sure to reference this issue as well, so everyone who wants to can see the history of this issue.  🙂 

I'm now working on `amdatu-bootstrap` -- it seems they changed usernames and possibly a bunch of other things (I found `amdatu-bootstrap-old` under the same user on BitBucket).  Will submit a PR to help with this soon!

**Comment by vinyldarkscratch** [comment]
Can't find mirrors for `cloudbees-sdk`, `mg3a`, and `mvptree`, and as you can see, `ctunnel` as well.  Will continue more next time.  🙂

**Comment by vinyldarkscratch** [comment]
The website for `supermodel` seems to be back up, but Chrome's giving me a big security warning.  Eek!  Looks like their SSL certificates aren't functioning.

**Comment by vinyldarkscratch** [comment]
`systemc` is now back up, and with no issues!  We can check that off the list.  👍

As for `tintin`, it looks like it's another one of the scenarios like `entr`.  With my time zone, the commit for `tintin` 2.01.4 states it was done on the 6th of January, but the release was published on the 7th.  (Of course, I'll be confirming this upstream!)

**Comment by yetisyny** [comment]
Are links from the Internet Archive, or MacPorts, or the Fedora Project, are those usable as mirrors? If all we want is those particular files and it doesn’t matter where they are from, that is simple, but if it matters where they are from, it would be good to know what exactly is required of a mirror.

**Comment by samsamh** [comment]
Hey can seem to find `dssp` anymore... 
It's telling me no formulae not in the tap, like it never even existed... Thx in advance and sorry too much of a noob to be able to check more closely and even less change something ^^"

**Comment by ilovezfs** [comment]
@samsamh that was removed from homebrew/science when the homebrew/science tap was deprecated. See https://github.com/Homebrew/homebrew-science/commit/224eed9111e6233a9ea55dee13118119c0043792.

**Comment by vinyldarkscratch** [comment]
`jhiccup` is being fixed by #23344.

`mg3a` (#23348) and `mvptree` (#23349) vanished completely.

WebDAV.org is down, which is the only place that `neon` and `litmus` seem to be hosted...aside from Fossies.  >~<

**Comment by vinyldarkscratch** [comment]
The site for `since` is back up.  👍

**Comment by vinyldarkscratch** [comment]
I tried to grab a copy of `talk-filters` from the URL, but the checksum doesn't match the one in the formula.  I found a mirror for it, but it's checksum doesn't match either the file I copied from the same URL, or the formula.  Might be best to just delete it?

**Comment by vinyldarkscratch** [comment]
Also, seems like `litmus` doesn't exist as a formula anymore as shown in #22659.

**Comment by vinyldarkscratch** [comment]
`supermodel` was fixed in #22673.  😉

**Comment by vinyldarkscratch** [comment]
@ilovezfs `ppl` and `tintin` are awaiting return contact, but I'm not sure what we should do for `neon` and `splint` -- should we just delete them?

**Comment by ilovezfs** [comment]
For neon I would use a mirror and contact @JimWhiteheadUCSC about the site being down.

**Comment by ilovezfs** [comment]
url "http://www.mirrorservice.org/sites/distfiles.macports.org/neon/neon-0.30.2.tar.gz"
mirror "https://fossies.org/linux/www/neon-0.30.2.tar.gz"

**Comment by vinyldarkscratch** [comment]
Sent an email to him, and added the mirrors!  #23351

**Comment by ilovezfs** [comment]
For splint, an issue should be filed at https://github.com/ravenexp/splint and

url "https://www.mirrorservice.org/sites/distfiles.macports.org/splint/splint-3.1.2.src.tgz"
mirror "http://pkgs.fedoraproject.org/repo/pkgs/splint/splint-3.1.2.src.tgz/25f47d70bd9c8bdddf6b03de5949c4fd/splint-3.1.2.src.tgz"

**Comment by ilovezfs** [comment]
For ppl we can use Debian mirrors while we wait for the return contact

url "https://mirrors.ocf.berkeley.edu/debian/pool/main/p/ppl/ppl_1.2.orig.tar.xz"
mirror "https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/p/ppl/ppl_1.2.orig.tar.xz"

**Comment by vinyldarkscratch** [comment]
Just looking at the repository for `splint`, it looks like a deprecated project, considering it's last commit was back in 2010 (and three issues have been made in 2016/2017 with no responses).  How many users are still installing it?

**Comment by ilovezfs** [comment]
52 in the last 30 days

**Comment by vinyldarkscratch** [comment]
That's...actually much more than I was expecting.  Well, mirror time it is!

**Comment by ilovezfs** [comment]
@vinyldarkscratch do you have the URL for the tintin issue? I'm closing this out since we're now to just the one.

**Comment by vinyldarkscratch** [comment]
@ilovezfs I wish I could provide one -- because their issue tracker is a form for the MUD that has a catchpa nobody can solve, I messaged the maintainer on SourceForge directly.  I can forward the messages if need be, however?

**Comment by ilovezfs** [comment]
@vinyldarkscratch maybe file an issue here too? https://github.com/tintinplusplus/tintin

**Comment by vinyldarkscratch** [comment]
@ilovezfs Done!
