### ISSUE TITLE
`brew install icecream` fails unless user creates /usr/local/sbin

### ISSUE THREAD

**Issue by thomcc** [Homebrew/homebrew-core#22576]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
    - I fixed all issues aside from this one. (I still get an "unlinked kegs" warning for icecream, if I didn't, I wouldn't file this issue)
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
    - It fails with `Error: No logs.`. 
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
    - Included in https://gist.github.com/thomcc/9b51a471843d220bdd8e91773cb1de9f 

To help us debug your issue please explain:

- What you were trying to do (and why)

    Run `brew install icecream`, because I'd like to install that package.

- What happened (include command output)

    It fails to link, since "/usr/local/sbin is not writable". See https://gist.github.com/thomcc/9b51a471843d220bdd8e91773cb1de9f for complete output, and further info (`brew doctor`/`brew config` output, etc.)

- What you expected to happen

    Brew should create the `/usr/local/sbin` directory when I try to install and/or link icecream, or at least tell me that I should, and what steps to take to do so.

- Step-by-step reproduction instructions (by running `brew install` commands)

    1. Ensure you have no `/usr/local/sbin`. 
    2. `brew install icecream`

Note: I'm aware that I can fix this with `sudo mkdir /usr/local/sbin; sudo chown $(whoami):admin /usr/local/sbin` (and then adding that directory to my PATH), but this should either be done for me, or suggested after the failure to install/link.

The following gist includes the log output of brew install, brew link, brew doctor, brew config, etc: https://gist.github.com/thomcc/9b51a471843d220bdd8e91773cb1de9f. This is also linked multiple times above.

**Comment by ilovezfs** [comment]
It is done by the installer https://github.com/Homebrew/install/blob/master/install#L206 so this shouldn't be an issue for people unless something has happened to their local configuration.

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink sbin/icecc-scheduler
/usr/local/sbin is not writable.
```
That existing error seems clear enough to me and indeed it sounds like you already know how to fix it.
