### ISSUE TITLE
Formulas of GUI apps that can be safely removed in favour of Casks.

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-core#2260]
This post is a continuation of https://github.com/Homebrew/brew-evolution/pull/3#issuecomment-225597589.

An effort of deduplication between Homebrew (HB) and Homebrew-Cask (HBC) is being discussed on https://github.com/caskroom/homebrew-cask/issues/15603. It’s been agreed between both projects this is desirable, but [the rules of what should remain/be dropped are a bit harder](https://github.com/caskroom/homebrew-cask/issues/15603#issuecomment-223563011). In addition, for https://github.com/Homebrew/brew-evolution/pull/3 to continue, having those rules defined is starting to become a necessity.

This post is mostly to first gather with help form the community which formulas can be safely removed in favour of the casks. Please keep in mind we’re all aware [a deduplicaton effort has some small inconveniences](https://github.com/caskroom/homebrew-cask/issues/15603#issuecomment-225932164). Maintaining a piece of software in both repos managed separately with few differences because a few users prefer to install one way rather than the other is undesirable.

Here’s the preliminary list of apps that produce app bundles (homebrew maintainers, please feel free to edit the post directly to add/remove):

+ [apcupsd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/apcupsd.rb)
+ [avidemux](https://github.com/Homebrew/homebrew-core/blob/master/Formula/avidemux.rb)
+ [cppcheck](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cppcheck.rb)
+ [djview4](https://github.com/Homebrew/homebrew-core/blob/master/Formula/djview4.rb)
+ [emacs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/emacs.rb)
+ [gammaray](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gammaray.rb)
+ [graphviz](https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphviz.rb)
+ [kdiff3](https://github.com/Homebrew/homebrew-core/blob/master/Formula/kdiff3.rb)
+ [macvim](https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb)
+ [mpv](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb)
+ [pinentry-mac](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pinentry-mac.rb)
+ [plan9port](https://github.com/Homebrew/homebrew-core/blob/master/Formula/plan9port.rb)
+ [puddletag](https://github.com/Homebrew/homebrew-core/blob/master/Formula/puddletag.rb)
+ [qcachegrind](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qcachegrind.rb)
+ [qjackctl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qjackctl.rb)
+ [qt](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb)
+ [qt5](https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt5.rb)
+ [valkyrie](https://github.com/Homebrew/homebrew-core/blob/master/Formula/valkyrie.rb)
+ [wireshark](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wireshark.rb)

Formulas should be moved to one of the other lists as they are resolved, and ~~crossed~~ from the first list.

---

Formulas that should not be removed:

(None yet)

---

Formulas than can safely be removed:

(None yet)

**Comment by DomT4** [comment]
* There's essentially no way we can get rid of `qt` or `qt5`. You can't use the upstream installations to build against sanely, we'd end up removing the majority of `qt5` and `qt` using formulae along with 'em. As tempting as that it, it's not reasonable. It also wouldn't seem to make much sense to stop providing only the `.app` bundles & make people install the formula from us for development & the cask to access the `.app`s.

* `emacs` as a formula offers a lot of flexibility & is used for build/run by other formulae.

* `graphviz` is too widely used as a formula, including as a dependency, to scrap.

* `pinentry-mac` - I wasn't aware upstream provided a pre-compiled `.app` here?

* `wireshark` offers a lot of flexibility over the upstream `.dmg`, and can function perfectly validly without the GUI, although before someone uses this sentence against me, I'm not saying we should scrap the GUI _option_.

Those are the only things I have strong opinions on.

**Comment by DomT4** [comment]
Possibly worth mentioning: We're currently pushing an effort to remove `qt4` dependencies from formulae, in favour of `qt5` if possible, so some of these formulae may "lose" their GUI-generating potential sooner rather than later.

**Comment by chdiza** [comment]
> pinentry-mac - I wasn't aware upstream provided a pre-compiled .app here?

They don't, as far as I can see.

**Comment by tdsmith** [comment]
FWIW I think only a few of these are really duplicates in the sense that a) all of the functionality is in the provided .app and b) there's no good reason a user would want to build these from source; Homebrew has been pretty good about rejecting apps that only exist in GUI-land.

**Comment by MikeMcQuaid** [comment]
> FWIW I think only a few of these are really duplicates in the sense that a) all of the functionality is in the provided .app and b) there's no good reason a user would want to build these from source; Homebrew has been pretty good about rejecting apps that only exist in GUI-land.

We can discuss them on a case-by-case basis when we open PRs.

**Comment by tomck** [comment]
`pinentry-mac` does not, and from what I can tell [they actually decided](https://gpgtools.tenderapp.com/discussions/problems/18217-pinentry) that it would be best to add a brew formula to resolve the issue for users installing via homebrew.

**Comment by MikeMcQuaid** [comment]
Think we've done this as much as we will for now. Thanks @AnastasiaSulyagina for the hard work here!
