### ISSUE TITLE
htop: This formula either does not compile or function as expected on macOS

### ISSUE THREAD

**Issue by Mirocow** [Homebrew/homebrew-core#22622]
$ sw_vers -productVersion
    10.13.2

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.2 (17C88)
      Kernel Version: Darwin 17.3.0
      Boot Volume: MAC HD
      Boot Mode: Normal
      Computer Name: iMac
      User Name: User (user)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 27 days 7 minutes

brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/htop.rb
######################################################################## 100.0%
htop: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

**Comment by Mirocow** [comment]
maybe bottle not found for $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

```
  bottle do
    sha256 "012058c2b3b3d4061b51ea4782ab4ecbe7063e0256ff4275d5f2f6514617faf4" => :sierra
    sha256 "fbb902d02cb45215128fe96a81132f6eb02afc91de38c8cc21e4ad28171c9119" => :el_capitan
  end```

**Comment by pascaldevink** [comment]
Should probably be listed in #18493

**Comment by donce** [comment]
This is not being addressed in https://github.com/Homebrew/homebrew-core/issues/18493, can we re-open this issue since it's still relevant?

**Comment by ilovezfs** [comment]
It's an upstream issue, so no.
