### ISSUE TITLE
doxygen install fails with the --with-llvm option

### ISSUE THREAD

**Issue by mellery451** [Homebrew/homebrew-core#22669]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [*] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] Ran `brew update` and retried your prior step?
- [*] Ran `brew doctor`, fixed all issues and retried your prior step?
- [*] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [*] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
 
----------

I've been trying to reinstall doxygen with llvm support:

```
 brew reinstall doxygen --with-graphviz --with-llvm --with-qt
```

which fails with:

```
==> cmake -G Unix Makefiles /private/tmp/llvm-20180109-48843-1q68jje/llvm-5.0.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS
Last 15 lines from /Users/ellery/Library/Logs/Homebrew/llvm/02.cmake:
  Unexpected failure executing llvm-build: Traceback (most recent call last):

    File "/tmp/llvm-20180109-48843-1q68jje/llvm-5.0.1.src/utils/llvm-build/llvm-build", line 3, in <module>
      import llvmbuild
    File "/private/tmp/llvm-20180109-48843-1q68jje/llvm-5.0.1.src/utils/llvm-build/llvmbuild/__init__.py", line 1, in <module>
      from llvmbuild.main import main
    File "/private/tmp/llvm-20180109-48843-1q68jje/llvm-5.0.1.src/utils/llvm-build/llvmbuild/main.py", line 1, in <module>
      from __future__ import absolute_import

  ImportError: No module named __future__


-- Configuring incomplete, errors occurred!

```

gist-logs:
https://gist.github.com/mellery451/7b9c57e1aa293baada07fbde4cfde62f

if I omit the `--with-llvm` option, it builds/installs fine.

Any advice about what to try to get the llvm enabled doxygen to build?

**Comment by vinyldarkscratch** [comment]
To add a little bit of additional information to this issue, when running `import __future__` on a few different versions of Python on my local machine, and all appear to be successful.  I tested using Python 2.7.10 (system included), 2.7.14 (via Brew formula), and 3.6.4 (also via Brew formula).

**Comment by mellery451** [comment]
thank you @vinyldarkscratch  -- I did the same and had no errors with system python, nor with python2 and python3 installed by homebrew. I'm not sure why the build gets confused, but it does appear - based on some cmake output - to be finding the homebrew /usr/local/bin/python2.7:

```
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Success
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Success
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Success
-- Found PythonInterp: /usr/local/bin/python2.7 (found version "2.7.14") 
-- Constructing LLVMBuild project information
CMake Error at CMakeLists.txt:660 (message):
  Unexpected failure executing llvm-build: Traceback (most recent call last):

    File "/tmp/llvm-20180109-53535-i2cp81/llvm-5.0.1.src/utils/llvm-build/llvm-build", line 3, in <module>
      import llvmbuild
    File "/private/tmp/llvm-20180109-53535-i2cp81/llvm-5.0.1.src/utils/llvm-build/llvmbuild/__init__.py", line 1, in <module>
      from llvmbuild.main import main
    File "/private/tmp/llvm-20180109-53535-i2cp81/llvm-5.0.1.src/utils/llvm-build/llvmbuild/main.py", line 1, in <module>
      from __future__ import absolute_import

  ImportError: No module named __future__


-- Configuring incomplete, errors occurred!
```

**Comment by vinyldarkscratch** [comment]
Mostly just out of curiosity, can you give the output for `tox llvm`?

**Comment by mellery451** [comment]
```
-bash: tox: command not found
```

...am I missing something obvious?

**Comment by vinyldarkscratch** [comment]
Oh whoops, that's my bad -- I have a few aliases for a few of the brew commands, and I'm so used to them now!  `tox = brew info` (i.e. a tox screen) for me.  😛

**Comment by mellery451** [comment]
got it - thx. Here is `brew info llvm`:

```
llvm: stable 5.0.1 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
https://llvm.org/
/usr/local/Cellar/llvm/5.0.0 (6,105 files, 2.5GB)
  Built from source on 2017-10-24 at 17:22:36 with: --with-toolchain --with-lldb --with-python --with-graphviz
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb
==> Dependencies
Build: cmake ✔
Recommended: libffi ✔
Optional: graphviz ✔, ocaml ✘, python ✔
==> Options
--with-graphviz
        Build with graphviz support
--with-lldb
        Build LLDB debugger
--with-ocaml
        Build with ocaml support
--with-python
        Build bindings against custom Python
--with-shared-libs
        Build shared instead of static libraries
--with-toolchain
        Build with Toolchain to facilitate overriding system compiler
--without-compiler-rt
        Do not build Clang runtime support libraries for code sanitizers, builtins, and profiling
--without-libcxx
        Do not build libc++ standard library
--without-libffi
        Do not use libffi to call external functions
--HEAD
        Install HEAD version
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.
```

now, I just tried a reinstall of llvm and it looks like it fails with the same python error, so I wonder if this is actually an issue with llvm 5.0.1 ? Happy to close/reopen if that's the case.

**Comment by vinyldarkscratch** [comment]
Thanks @mellery451 -- I'll attempt to build LLVM and Doxygen with those same options and see if I can reproduce the issue to figure out a solution!  (I'm leaving for a class soon, though, so it'll be a while -- cheers to anyone else who may take over.  🙂)

> I wonder if this is actually an issue with llvm 5.0.1

It's definitely a possibility.  I'm curious if there are any issues reported upstream?

One thing that caught my eye: the formula reports that it is version 5.0.1, however it's installed to `Cellar/llvm/5.0.0`.  I just installed llvm (without the options), and it installed to `Cellar/llvm/5.0.1`.  I'm just taking a guess that this may have something to do with the issue -- can you run `brew upgrade llvm` so we can eliminate that as an issue?

**Comment by mellery451** [comment]
yeah, `brew upgrade llvm` is failing (with the same python error), thus the disconnect between latest and installed version:

```
==> cmake -G Unix Makefiles /private/tmp/llvm-20180109-68283-1xdbzht/llvm-5.0.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS
Last 15 lines from /Users/ellery/Library/Logs/Homebrew/llvm/02.cmake:
  Unexpected failure executing llvm-build: Traceback (most recent call last):

    File "/tmp/llvm-20180109-68283-1xdbzht/llvm-5.0.1.src/utils/llvm-build/llvm-build", line 3, in <module>
      import llvmbuild
    File "/private/tmp/llvm-20180109-68283-1xdbzht/llvm-5.0.1.src/utils/llvm-build/llvmbuild/__init__.py", line 1, in <module>
      from llvmbuild.main import main
    File "/private/tmp/llvm-20180109-68283-1xdbzht/llvm-5.0.1.src/utils/llvm-build/llvmbuild/main.py", line 1, in <module>
      from __future__ import absolute_import

  ImportError: No module named __future__


-- Configuring incomplete, errors occurred!
See also "/tmp/llvm-20180109-68283-mnd3w5/CMakeFiles/CMakeOutput.log".
See also "/tmp/llvm-20180109-68283-mnd3w5/CMakeFiles/CMakeError.log".

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

**Comment by vinyldarkscratch** [comment]
I see, thanks for letting me know, @mellery451!  Hmm...  Let me get back to you after attempting to reproduce the issue on my own machine?

**Comment by vinyldarkscratch** [comment]
(I forgot how long LLVM takes to compile... XD)

Status update: I tried installing LLVM with the `--with-python` flag, and then manually import llvmbuild.  No luck.  I'm going to progressively add the other arguments, currently doing both `--with-python` and `--with-toolchain` together.  Part of me is hoping to be able to reproduce the issue and figure out what's going on!

**Comment by vinyldarkscratch** [comment]
@mellery451, you'll be happy to hear that I reproduced the issue.  I added `--with-lldb`, and just got the same problem that you did.  Now, we can dive further into the issue of why `--with-lldb` isn't working!

My question for you, however, is do you need LLDB as well?

**Comment by mellery451** [comment]
nice! - thanks for digging into this @vinyldarkscratch. I think I was experimenting with debugger integration in vim and thought I needed lldb built with python bindings (couldn't get stock apple/clang/lldb to work) That was a failed experiment, so I probably don't need it at this time.

**Comment by vinyldarkscratch** [comment]
Hey, of course, glad to help out!  It was definitely a fun little adventure finding out what exactly went wrong.  c:  As you can see, I created another issue in regards to this, so whoever would like to can try to figure out a fix for those two commands together.  (The last time I went digging through LLVM, I got a migraine just from how huge it is...)

So yeah, if you were to `brew uninstall llvm` (or `brew uninstall --ignore-dependencies llvm`) and then `brew install llvm --with-toolchain --with-python --with-graphviz`, that should get you what you're looking for!  :wink:

**Comment by fxcoudert** [comment]
Thanks @vinyldarkscratch for following down the rabbit hole… I guess we can close this now, and deal with the root bug at #22679
