### ISSUE TITLE
parmetis and petsc not found in taps

### ISSUE THREAD

**Issue by smaffei** [Homebrew/homebrew-core#22660]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Hi all,
I was trying to install some packages that I need to run a numerical code written by somebody else on my own laptop (for debugging purposes). I will need stuff like parmetis, slepc and petsc but I don't seem to be able to install them. If I try `brew install parmetis` I get:

````
Error: No available formula with the name "parmetis" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
````

I have been installing packages the whole evening (fftw, hdf5 and others) without problems. 

I tried to `brew tap homebrew/science` to no use. I check dependencies on [http://formulae.brew.sh/formula/parmetis](http://formulae.brew.sh/formula/parmetis) and only cmake (installed and up-to-date) is required. The output of `brew info parmetis` is the following:
````
Error: No available formula with the name "parmetis" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
````

The output of `brew config` is the following:
````
HOMEBREW_VERSION: 1.4.3-5-g5fe2ca2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5fe2ca2a833f94df2adea4947fb89662c17dd53f
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 63b7bf6ba611c9c6e398c52eb48f12774bf2a5c6
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/stefanomaffei/anaconda/bin/python => /Users/stefanomaffei/anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_20
macOS: 10.11.6-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
````

I am running on Mac OS X 10.11.6

**Comment by vinyldarkscratch** [comment]
For `parmetis`, there was a PR, #22361, but the author closed it as it wasn't ready for review.  Both of the formulas for these two need to be written.  (You can submit a PR if you'd like to write them of course.  🙂)

**Comment by fxcoudert** [comment]
parmetis cannot be incorporated into homebrew right now, it requires patches to be built. Given the last version was released 5 years ago, I am doubtful development is ongoing :(

petsc depends on parmetis
