### ISSUE TITLE
LLVM --with-python --with-lldb fails

### ISSUE THREAD

**Issue by vinyldarkscratch** [Homebrew/homebrew-core#22679]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

- What you were trying to do (and why)
While trying to help resolve #22669, we determined that the issue was in `brew install llvm --with-lldb`.  The build crashes whilst running a bit of Python.

- What happened (include command output)
```
Last 15 lines from /Users/vinyldarkscratch/Library/Logs/Homebrew/llvm/02.cmake:
  Unexpected failure executing llvm-build: Traceback (most recent call last):

    File "/tmp/llvm-20180109-98211-1v7p6iv/llvm-5.0.1.src/utils/llvm-build/llvm-build", line 3, in <module>
      import llvmbuild
    File "/private/tmp/llvm-20180109-98211-1v7p6iv/llvm-5.0.1.src/utils/llvm-build/llvmbuild/__init__.py", line 1, in <module>
      from llvmbuild.main import main
    File "/private/tmp/llvm-20180109-98211-1v7p6iv/llvm-5.0.1.src/utils/llvm-build/llvmbuild/main.py", line 1, in <module>
      from __future__ import absolute_import

  ImportError: No module named __future__
```

- What you expected to happen
Well...build and install, of course.  😛 

- Step-by-step reproduction instructions (by running `brew install` commands)
I ran a few different versions.
`brew install llvm --with-python --with-toolchain --with-lldb` > _Fail_ (logs are for this run)
`brew install llvm --with-python --with-lldb` > _Fail_
`brew install llvm --with-python` > **Pass**
`brew install llvm --with-lldb` > **Pass**
`brew install llvm --with-toolchain` > **Pass**

Logs: https://gist.github.com/eade71b537f9e1a5b19ccf8921313969

**Comment by fxcoudert** [comment]
The llvm formula has many options, and according to analytics others also frequently fail, like `--with-toolchain` (which fails in >25% of builds).

**Comment by vinyldarkscratch** [comment]
LLVM _is_ pretty big, that's for sure!  Actually that reminds me, I tested `--with-toolchain` and had a successful build.  Though of course, that's just my system.  😛

**Comment by ilovezfs** [comment]
Can you try adding `ENV.prepend_path "PATH", Formula["python"].opt_libexec/"bin"` to the install method please, and then see if the `--with-python --with-lldb` build still fails?

**Comment by ilovezfs** [comment]
@vinyldarkscratch any luck with that tweak?

**Comment by timotheecour** [comment]
@ilovezfs  @vinyldarkscratch  it seems to work, just wrote https://github.com/Homebrew/homebrew-core/pull/22837

**Comment by mellery451** [comment]
I think this just broke again, probably because the python formulae just went through some changes and "python" now installes python 3 instead of 2 (?). I think this formula might need to use `python@2` now.
