### ISSUE TITLE
Perl uses hardcoded filepaths while using local::lib

### ISSUE THREAD

**Issue by bartskowron** [Homebrew/homebrew-core#22745]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Error: No logs.

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 1.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 987805d3dcd4c8dbc70127399d4ea7aee8e98c21
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0b2a9b8090d52250dcd3d00512c423966144e13f
Core tap last commit: 36 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0/bin/ruby
Java: 9.0.1
macOS: 10.13.2-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

Doctor says my system is ready to brew.

```
perl: stable 5.26.1 (bottled), HEAD
Highly capable, feature-rich programming language
https://www.perl.org/
/usr/local/Cellar/perl/5.26.1 (2,395 files, 57MB) *
  Poured from bottle on 2018-01-10 at 00:22:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/perl.rb
==> Options
--with-dtrace
	Build with DTrace probes
--without-test
	Skip running the build test suite
--HEAD
	Install HEAD version
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bash_profile
```

Ok, so in the caveat there is a proposition to use local::lib with some default directory path such as $HOME/perl5. I wanted to use a different path so I run:
```
PERL_MM_OPT="INSTALL_BASE=$HOME/.perl5" cpan local::lib
echo 'eval "$(perl -I$HOME/.perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bash_profile
```
(see it's .perl5, not perl5 directory)

After that I checked $PATH and here is a result:
`/Users/user/perl5/bin:.....`

Somehow the perl5 got there. And indeed, I have not both perl5 and .perl5 directories!

```
perl5
├── bin
└── lib
    └── perl5
        ├── 5.26.1
        │   └── darwin-thread-multi-2level
        └── darwin-thread-multi-2level
.perl5
├── lib
│   └── perl5
│       ├── POD2
│       │   ├── DE
│       │   │   └── local
│       │   │       └── lib.pod
│       │   └── PT_BR
│       │       └── local
│       │           └── lib.pod
│       ├── darwin-thread-multi-2level
│       │   ├── auto
│       │   │   └── local
│       │   │       └── lib
│       │   └── perllocal.pod
│       ├── lib
│       │   └── core
│       │       └── only.pm
│       └── local
│           └── lib.pm
└── man
    └── man3
        ├── POD2::DE::local::lib.3
        ├── POD2::PT_BR::local::lib.3
        ├── lib::core::only.3
        └── local::lib.3

22 directories, 9 files
```

Looks like the $HOME/perl5 is hardcoded :(

**Comment by bartskowron** [comment]
The other interesting thing is the locale installed such as DE and PT_BR. I don't use these languages, I have never configured anything to use them. I have no idea for what reason I got them installed.
Shall I create a new issue for this?

**Comment by Habbie** [comment]
> I have no idea for what reason I got them installed.

Those appear to be the languages into which the `local::lib` documentation happens to have been translated.

**Comment by Habbie** [comment]
If this is a bug, I think it's a bug in `local::lib`, not in brew.

**Comment by Habbie** [comment]
Via http://search.cpan.org/~haarg/local-lib-2.000019/lib/local/lib.pm, the right syntax if you want to change the default is `perl -I$HOME/.perl5/lib/perl5 -Mlocal::lib=$HOME/.perl5`

**Comment by bartskowron** [comment]
Ok, going to test it. I'm hoping is just a wrong caveat description then.

Shall I simply run `brew uninstall perl` and then remove ~/.perl5 and ~/perl5 before rerunning the whole process or there is some additional steps that I should execute?

**Comment by Habbie** [comment]
Remove the two dirs and clean up your `.bash_profile`, then try again.

**Comment by bartskowron** [comment]
Seems like it's working now:

```
.perl5
├── bin
├── lib
│   └── perl5
│       ├── 5.26.1
│       │   └── darwin-thread-multi-2level
│       ├── POD2
│       │   ├── DE
│       │   │   └── local
│       │   │       └── lib.pod
│       │   └── PT_BR
│       │       └── local
│       │           └── lib.pod
│       ├── darwin-thread-multi-2level
│       │   ├── auto
│       │   │   └── local
│       │   │       └── lib
│       │   └── perllocal.pod
│       ├── lib
│       │   └── core
│       │       └── only.pm
│       └── local
│           └── lib.pm
└── man
    └── man3
        ├── POD2::DE::local::lib.3
        ├── POD2::PT_BR::local::lib.3
        ├── lib::core::only.3
        └── local::lib.3

19 directories, 9 files
```

First running of bash showed this: `Attempting to create directory /Users/user/.perl5` but then the message disappeared.

**Comment by ilovezfs** [comment]
It would be great if someone could open a PR to fix the caveat if we think it's wrong.

**Comment by DomT4** [comment]
AFAIK, the current syntax is fine? It adheres to the upstream default.

**Comment by bartskowron** [comment]
> AFAIK, the current syntax is fine? It adheres to the upstream default.

It's fine as long as you stick with the default values. The reason we can change a default value (the path in this case) is why we have this option. Otherwise, it would be hardcoded.

**Comment by DomT4** [comment]
Yeah, that's more or less what I was swinging at. I think encouraging the upstream default is the logical thing to do, given anyone who wants to wander can do so fairly easily by checking the upstream documentation.

**Comment by bartskowron** [comment]
I agree as long as the default recommendation doesn't provide misunderstanding for advanced configuration. This forces user to obligatory reinstallation due to suggestion.

The pull request is straight forward for default installation. It doesn't increase confusion for the default recommendation. It does decrease confusion for custom configuration.
