### ISSUE TITLE
Python2 is SUPER slow compared to the Apple version or Python3

### ISSUE THREAD

**Issue by bartskowron** [Homebrew/homebrew-core#22743]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/8837b3f3ccb0541589a8ecf3046cd3df

I have a test application that shows that Python2 from Homebrew is super slow.
The application code is here: 

```python
from threading import Thread
import time

def f(n):
    while n > 0:
        n -= 1

t1 = Thread(target=f, args=(100000000,))
t2 = Thread(target=f, args=(100000000,))

start = time.time()
t1.start()
t2.start()
t1.join()
t2.join()

stop = time.time()
print(stop-start)
```

Here are some time results:

- Apple py2 - 13.04s
- brew py2 - **42.5s** (!!)
- brew py3 - 14.1s

The running system: macOS High Sierra 10.13.2 (with recent updates).
Verified by other user on macOS Sierra with the same results.
I also verified it on a Ubuntu machine: py2 gets about 14s so similar to the Apple version which is correct.

Before installing highSierra I was using OSX Mavericks on my machine and py2 from homebrew (with compilation process) got similar 14s time.

The downgrade is over 3x times. It doesn't look as an OS issue as py3 from brew and bundled py2 work perfectly fine.

**Comment by Habbie** [comment]
> Verified by other user on macOS Sierra with the same results.

* apple py2 12.3s
* brew py2 44.5s
* brew py3 16.3s
* brew pypy 0.7s

**Comment by ilovezfs** [comment]
any difference with
```
diff --git a/Formula/python.rb b/Formula/python.rb
index 0202c4b5b7..890e2553aa 100644
--- a/Formula/python.rb
+++ b/Formula/python.rb
@@ -103,6 +103,7 @@ class Python < Formula
       --datadir=#{share}
       --enable-framework=#{frameworks}
       --without-ensurepip
+      --with-lto
     ]
 
     args << "--without-gcc" if ENV.compiler == :clang
```

**Comment by bartskowron** [comment]
Could you please provide instructions how to apply this change correctly?

**Comment by ilovezfs** [comment]
`lto` makes no difference in my local testing, and the difference I measure is much less:
```
iMac-TMP:~ joe$ python2 brewpythonsucks.py 
10.3280191422
iMac-TMP:~ joe$ python2 brewpythonsucks.py 
10.4606440067
iMac-TMP:~ joe$ python brewpythonsucks.py 
8.09146595001
iMac-TMP:~ joe$ python brewpythonsucks.py 
8.04578900337
```

**Comment by ilovezfs** [comment]
We'd be happy to look at a pull request improving the situation but there's not much more we can do here. Thanks for bringing it to our attention.

**Comment by bartskowron** [comment]
I am a bit confused by your results. What is your python2 and python?

And the most important IMHO it's not fair to close it as it's actually shows that python2 from brew is unusable.
Here is a similar test without threads that presents exactly similar results (35s for brew and 8.5s for Apple python):
```python
import time

def f(n):
    while n > 0:
        n -= 1

start = time.time()
f(100000000)
f(100000000)
stop = time.time()
print stop-start
```

**Comment by ilovezfs** [comment]
For me, `python` is system Python and `python2` is Homebrew's Python.

For your latest program,
```
iMac-TMP:~ joe$ python brewpythonsucks2.py 
5.21852111816
iMac-TMP:~ joe$ python2 brewpythonsucks2.py 
6.68095803261
iMac-TMP:~ joe$ 
```

>And the most important IMHO it's not fair to close it as it's actually shows that python2 from brew is unusable.

There have been 417,955 installs of Homebrew Python in the last 90 days, so it's at least somewhat usable ;)

As I said, we're happy to look at PR(s) improving Homebrew Python.

**Comment by bartskowron** [comment]
Somewhat for sure ;-)
I don't know the homebrew policy for managing issues but I would say it's enough important to not simple ignore and close it.

Anyway, I am going to investigate it even if the closed ticket.

@ilovezfs could you please run `brew gist-logs python` and paste the gist url? Your results are fine (I'm just blinking of this 2 secs downgrade compared to the system Python), so it would be a good start point. Same to @Habbie.
Thanks

**Comment by DomT4** [comment]
FWIW:

```
~> for pytest in {1..5}; do /usr/local/opt/python/libexec/bin/python test.py; done

38.4318349361
38.8159379959
38.4849860668
39.3036088943
40.1945571899
```

```
~> for pytest in {1..5}; do /usr/bin/python test.py; done

12.0464408398
12.1432790756
14.1699538231
13.6251618862
13.5484278202
```

```
~> for pytest in {1..5}; do python3 test.py; done

12.757915735244751
13.017276287078857
13.046283960342407
13.059051036834717
13.123716115951538
```

**Comment by DomT4** [comment]
Python 2.7.12 on Ubuntu averages under 8 seconds, for comparison.

**Comment by Habbie** [comment]
> could you please run brew gist-logs python

https://gist.github.com/Habbie/820ba10ba991d27c79661f1c97b4fc98

**Comment by bartskowron** [comment]
@ilovezfs just a reminder for the `brew gist-logs python`

**Comment by bartskowron** [comment]
It's hard to work on a correct version without help from @ilovezfs as his results look correctly. Any chance to get a feedback from you? or simple its better to use a native Python2 and not bother with Homebrew for this package?

**Comment by ilovezfs** [comment]
@tdsmith @zmwangx any ideas here? I'm assuming some kind of optimization is off that could be flipped on.

**Comment by ilovezfs** [comment]
OK this is interesting. I can reproduce the poor performance on 10.13. If I use the 10.11 bottle on 10.13, it is magically much faster.

**Comment by ilovezfs** [comment]
OK, so it looks like this is related to the Xcode version used. If I build with the llvm formula's clang it's actually faster than system Python.

**Comment by ilovezfs** [comment]
If you want to test that,
```
bash-3.2$ git diff -- Formula/python.rb 
diff --git a/Formula/python.rb b/Formula/python.rb
index 0202c4b5b7..3ea272c5a5 100644
--- a/Formula/python.rb
+++ b/Formula/python.rb
@@ -1,4 +1,7 @@
 class Python < Formula
+depends_on "llvm"
+fails_with :clang
+fails_with :gcc => "7"
   desc "Interpreted, interactive, object-oriented programming language"
   homepage "https://www.python.org/"
   url "https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz"
```
and `brew install -dvs python`

**Comment by DomT4** [comment]
> If I build with the llvm formula's clang it's actually faster than system Python.

Can repro.

```
~> for pytest in {1..5}; do /usr/local/opt/python/libexec/bin/python test.py; done

5.50056385994
5.58324694633
5.81261301041
5.62180399895
5.67253088951
```
That's pretty wild.

**Comment by zmwangx** [comment]
I simplified the test (drop inconsequential threads, and make it run faster), and ran benchmarks against pythons compiled with different versions of llvm (`llvm`, `llvm@4`, `llvm@3.9`):

```py
import time

def f(n):
    while n > 0:
        n -= 1

start = time.time()
f(50000000)
stop = time.time()
print(stop - start)
```

```console
$ ./bench
/usr/bin/python2.7
2.0681180954

/usr/local/bin/python2.7
7.83331799507

dist/python27-apple-clang-900.0.38/bin/python2.7
8.31766891479

dist/python27-clang-3.9.1/bin/python2.7
9.04964900017

dist/python27-clang-4.0.1/bin/python2.7
8.45596003532

dist/python27-clang-5.0.1/bin/python2.7
1.64623904228

/usr/local/bin/python3.6
3.268683910369873

dist/python-master-apple-clang-900.0.38/bin/python3
3.1528470516204834

dist/python-master-clang-3.9.1/bin/python3
3.045478105545044

dist/python-master-clang-4.0.1/bin/python3
2.9801700115203857

dist/python-master-clang-5.0.1/bin/python3
3.0513551235198975

```

Not sure what's the problem. I suggest creating a [bpo](https://bugs.python.org/) issue to solicit opinions from Python core developers.

Here is the complete script to set up my benchmarking environment and run the benchmarks:

```zsh
#!/usr/bin/env zsh
setopt xtrace errexit

ROOTDIR=/tmp/python-benchmark

brew install python2 python3 llvm llvm@4 llvm@3.9

mkdir -p $ROOTDIR
cd $ROOTDIR
[[ -d cpython ]] || git clone https://github.com/python/cpython.git

cd cpython

# build <CC> <prefix>
build () {
    [[ -d $2 ]] && return
    CC=$1 ./configure --prefix=$2
    make install -j8
    make distclean
}

git checkout 2.7
build /usr/bin/clang $ROOTDIR/dist/python27-apple-clang-900.0.38
build /usr/local/Cellar/llvm/5.0.1/bin/clang-5.0 $ROOTDIR/dist/python27-clang-5.0.1
build /usr/local/Cellar/llvm@4/4.0.1/bin/clang-4.0 $ROOTDIR/dist/python27-clang-4.0.1
build /usr/local/Cellar/llvm@3.9/3.9.1_1/bin/clang-3.9 $ROOTDIR/dist/python27-clang-3.9.1

git checkout master
build /usr/bin/clang $ROOTDIR/dist/python27-apple-clang-900.0.38
build /usr/local/Cellar/llvm/5.0.1/bin/clang-5.0 $ROOTDIR/dist/python-master-clang-5.0.1
build /usr/local/Cellar/llvm@4/4.0.1/bin/clang-4.0 $ROOTDIR/dist/python-master-clang-4.0.1
build /usr/local/Cellar/llvm@3.9/3.9.1_1/bin/clang-3.9 $ROOTDIR/dist/python-master-clang-3.9.1

cd ..

[[ -f test.py ]] || cat >test.py <<'EOF'
import time

def f(n):
    while n > 0:
        n -= 1

start = time.time()
f(50000000)
stop = time.time()
print(stop - start)
EOF

[[ -f bench ]] || cat >bench <<'EOF'
#!/usr/bin/env zsh

pythons=(
    /usr/bin/python2.7
    /usr/local/bin/python2.7
    dist/python27-apple-clang-900.0.38/bin/python2.7
    dist/python27-clang-3.9.1/bin/python2.7
    dist/python27-clang-4.0.1/bin/python2.7
    dist/python27-clang-5.0.1/bin/python2.7
    /usr/local/bin/python3.6
    dist/python-master-apple-clang-900.0.38/bin/python3
    dist/python-master-clang-3.9.1/bin/python3
    dist/python-master-clang-4.0.1/bin/python3
    dist/python-master-clang-5.0.1/bin/python3
)

for python in $pythons; do
    echo $python
    $python test.py
    echo
done
EOF
chmod +x bench

./bench
```

**Comment by ilovezfs** [comment]
Thanks, @zmwangx. It's somewhat encouraging that llvm 3.9 and 4.0 are just as bad as Xcode in your tests.

Mike pointed out that the fact that Python 3 seems to be OK with Xcode 9 suggests that this may be a Python 2 build system issue as opposed to a clang bug.

**Comment by ilovezfs** [comment]
I'm wondering if the same findings are reproducible on :penguin:

**Comment by zmwangx** [comment]
This is a py27+clang issue, not only on macOS. I'm composing my bpo bug report right now.

More comprehensive and refined benchmarks (using https://gist.github.com/zmwangx/f8151ba8907ba8159a07fdd1528fc2b5 ):

macOS 10.13.2:

```
2.082144	/usr/bin/python2.7
7.964049	/usr/local/bin/python2.7
8.750652	dist/python27-apple-clang-900/bin/python2.7
8.476405	dist/python27-clang-3.9/bin/python2.7
8.625660	dist/python27-clang-4.0/bin/python2.7
1.760096	dist/python27-clang-5.0/bin/python2.7
3.254814	/usr/local/bin/python3.6
2.864716	dist/python-master-apple-clang-900/bin/python3
3.071757	dist/python-master-clang-3.9/bin/python3
2.925192	dist/python-master-clang-4.0/bin/python3
2.908782	dist/python-master-clang-5.0/bin/python3
```

Ubuntu Artful in VirtualBox:

```
1.475095	/usr/bin/python2.7
8.576817	dist/python27-clang-3.9/bin/python2.7
8.165588	dist/python27-clang-4.0/bin/python2.7
1.779193	dist/python27-clang-5.0/bin/python2.7
1.728321	dist/python27-gcc-5/bin/python2.7
1.570040	dist/python27-gcc-6/bin/python2.7
1.604617	dist/python27-gcc-7/bin/python2.7
2.323037	/usr/bin/python3.6
2.964338	dist/python-master-clang-3.9/bin/python3
3.054277	dist/python-master-clang-4.0/bin/python3
2.734908	dist/python-master-clang-5.0/bin/python3
2.490278	dist/python-master-gcc-5/bin/python3
2.494691	dist/python-master-gcc-6/bin/python3
2.642277	dist/python-master-gcc-7/bin/python3
```

**Comment by zmwangx** [comment]
Hum, just realized my Xcode is outdated (9.0.1 instead of 9.2). WTF.

**Comment by ilovezfs** [comment]
CLT or Xcode.app?

**Comment by zmwangx** [comment]
CLT is 9.2, so I guess my benchmarks shouldn't be affected.

**Comment by ilovezfs** [comment]
If you can throw lldb 360.1 in as well, that might be interesting since I think that's what maps to Xcode 8.2.1 on El Capitan, where it seemed to be OK.

**Comment by zmwangx** [comment]
[bpo 32616](https://bugs.python.org/issue32616). The discussion should probably be continued there since I've demonstrated that this is not a Homebrew, or even macOS-specific problem. I'm too tired to do anything else today.

**Comment by ilovezfs** [comment]
Thanks @zmwangx :)

**Comment by zmwangx** [comment]
No problem.

**Comment by methane** [comment]
As I commented on b.p.o, `  --with-computed-gotos` configure option can mitigate this issue.

Long term solution is moving to LLVM 5, but I don't know Xcode roadmap.

**Comment by ilovezfs** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/23748

**Comment by bartskowron** [comment]
IMHO you made a typo @methane. On bpo you said `--without-computed-gotos`, here --with

**Comment by ilovezfs** [comment]
@bartskowron corrected in the PR.

**Comment by ilovezfs** [comment]
Fixes looks effective
```
bash-3.2$ python brewpythonsucks.py 
10.2647600174
bash-3.2$ python2 brewpythonsucks.py 
9.52381396294
bash-3.2$
```
So it now beats system Python.

**Comment by ilovezfs** [comment]
Any thoughts on whether we should restrict that argument to Xcode 9?
