### ISSUE TITLE
LLVM fails with --with-lldb --with-toolchain

### ISSUE THREAD

**Issue by gabyx** [Homebrew/homebrew-core#22764]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Installing llvm with `brew install llvm --with-toolchain --with-lldb`
Same as issue: #17839
- Error:

```
/tmp/llvm-20180111-5938-dbqid9/llvm-5.0.1.src/tools/lldb/include/lldb/API/SBTarget.h:225:41: error: no type named 'pid_t' in the global namespace; did you mean simply 'pid_t'?
                                        ::pid_t pid, // 32 bit int process ID
                                        ^~~~~~~
                                        pid_t
/tmp/llvm-20180111-5938-dbqid9/llvm-5.0.1.src/tools/lldb/include/lldb/lldb-types.h:87:18: note: 'pid_t' declared here
typedef uint64_t pid_t;
                 ^
```

https://gist.github.com/81a0568185f33c416ae1e182dd1cf4bb

**Comment by gabyx** [comment]
Can we somehow force brew?
I will try a `git revert 8f84c9238a9a5f8d85a08755c20eff9c8040a6b1` which deleted the patch
and report back

**Comment by gabyx** [comment]
Trying now: `HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm --with-toolchain --with-lldb`

**Comment by gabyx** [comment]
OK, with my patch it works: 
use the following patch:
https://gist.github.com/gabyx/611e1c97e324fb6f6e1fa6b7beab6de5
and apply it in the `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` repo.

Thats how I ve done it
```
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core
git checkout -b lldb-patch
git revert 8f84c9238a9a5f8d85a08755c20eff9c8040a6b1
git cherry-pick 8329f8fb419da3bffcb98b56fddb973e7862f04f
HOMEBREW_NO_AUTO_UPDATE=1 brew install llvm --with-toolchain --with-lldb
```

**Comment by timotheecour** [comment]
not sure if https://github.com/Homebrew/homebrew-core/issues/22679 is related

**Comment by gabyx** [comment]
I dont think so, since I did not use `--with-python` and the problem was due to a compiler error as in #17839

**Comment by ilovezfs** [comment]
@gabyx please do not suggest people run `git revert`/`git cherry-pick`/etc. in their local tree. This will cause support issues for the Homebrew maintainers when people then have broken `brew update`.

**Comment by gabyx** [comment]
true..., it was a workaround ;-)

**Comment by ilovezfs** [comment]
should be fixed now if you `brew update`
