### ISSUE TITLE
SHA256 checksum mismatch for qwt 6.1.3

### ISSUE THREAD

**Issue by muellermartin** [Homebrew/homebrew-core#2280]
I ran `brew update && brew upgrade` but it keeps failing on qwt due to a checksum mismatch. This is the relevant output:
```
==> Verifying qwt-6.1.3.tar.bz2 checksum
ln -s ../Cellar/qwt/6.1.2/lib/qwt.framework qwt.framework
Error: SHA256 mismatch
Expected: f996074eb50cafa06d45dc41cc1c18a087287d9f2079cc817eb8cfc96b710885
Actual: f3ecd34e72a9a2b08422fb6c8e909ca76f4ce5fa77acad7a2883b701f4309733
Archive: /Users/martin/Library/Caches/Homebrew/qwt-6.1.3.tar.bz2
To retry an incomplete download, remove the file above.
```
Steps I tried:

- deleted the file in case of an incomplete/corrupted download to redownload it as suggested but that does not seem to help
- manually downloaded that file from the URL given in the formula and checked its checksum and this way I also get `f3ecd34e72a9a2b08422fb6c8e909ca76f4ce5fa77acad7a2883b701f4309733` (which does not correspond to the checksum in the formula)

**Comment by DomT4** [comment]
Can reproduce the SHA mismatch. The update was merged ~9 days ago by @ilovezfs in https://github.com/Homebrew/homebrew-core/pull/1925. It would have passed CI at the time, so perhaps upstream retagged the release. It may be worth asking them if they did so.

**Comment by muellermartin** [comment]
The ["Last Modified" column on SourceForge](https://sourceforge.net/projects/qwt/files/qwt/6.1.3/) for the files shows that they were last modified on 2016-06-13 which is 9 days in the past so I doubt that upstream changed something meanwhile.

**Comment by DomT4** [comment]
I'm aware, but they could have retagged it _on the day_, given that we merged the update some time on the 13th.

**Comment by tdsmith** [comment]
Pinged upstream; should be visible at http://comments.gmane.org/gmane.comp.graphics.qwt.general/4486.

**Comment by muellermartin** [comment]
@DomT4 Seems you were right! @tdsmith got an answer on their mailing list:

This is the [reply from the mailing list](http://permalink.gmane.org/gmane.comp.graphics.qwt.general/4495):
>Hi,
>
>> Is it possible these tarballs were replaced since they were first
>> uploaded? Homebrew recorded a sha256 checksum of
>> f996074eb50cafa06d45dc41cc1c18a087287d9f2079cc817eb8cfc96b710885 for
>> qwt-6.1.3.tar.bz2 on June 13; now we're observing
>> f3ecd34e72a9a2b08422fb6c8e909ca76f4ce5fa77acad7a2883b701f4309733.
>>
>> Just wanted to confirm this was intentional.
>
>Yes the first tarball missed some files in the docs and had been 
>replaced  a couple of minutes later.
>
>Uwe

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-core/commit/4595fe627f3693a41301e716d685b158c284fc61.
