### ISSUE TITLE
dyld: Library not loaded: /usr/local/lib/libintl.8.dylib

### ISSUE THREAD

**Issue by metineren** [Homebrew/homebrew-core#22817]
gettext return library not load error.
gettext version 0.19.4

I am linking libintl.8.dylib to /usr/local/lib/libintl.8.dylib after works but brew doctor return to following message

![ekran resmi 2018-01-13 12 06 10](https://user-images.githubusercontent.com/1395204/34904611-3f935172-f85a-11e7-96bc-7980f5d8e0de.png)

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
You should not link `gettext`, which is `keg_only`. The `gettext` you're invoking isn't Homebrew's gettext. Howebrew's `gettext` is linked to `/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib` not `/usr/local/lib/libintl.8.dylib`.

```
iMac-TMP:homebrew-core joe$ otool -L /usr/local/opt/gettext/bin/gettext
/usr/local/opt/gettext/bin/gettext:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1258.1.0)
	/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
```
```
iMac-TMP:homebrew-core joe$ /usr/local/opt/gettext/bin/gettext --version
gettext (GNU gettext-runtime) 0.19.8.1
Copyright (C) 1995-1997, 2000-2007 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Ulrich Drepper.
```

I suggest you
```
rm /usr/local/bin/gettext
rm /usr/local/lib/libintl.8.dylib
brew unlink gettext
brew prune
```

and try
```
/usr/local/opt/gettext/bin/gettext --version
```
