### ISSUE TITLE
Apache Bench not migrated to brew-core

### ISSUE THREAD

**Issue by fcoury** [Homebrew/homebrew-core#22899]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install apache bench by running `brew install homebrew/apache/ab`

- What happened (include command output)

```
$ brew install homebrew/apache/ab
Error: No available formula with the name "homebrew/apache/ab"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/apache is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/apache)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
```

- What you expected to happen

Install apache bench or at least find a way to install it after it's been migrated to homebrew-core.

- Step-by-step reproduction instructions (by running `brew install` commands)

This is more of a question if the Apache Bench tool was migrated to homebrew-core along with the other ones reported here:

https://github.com/Homebrew/homebrew-apache

**Comment by ilovezfs** [comment]
macOS comes with ab. `man ab`

**Comment by fcoury** [comment]
No way @ilovezfs I am so sorry!

**Comment by ilovezfs** [comment]
hehe no worries

**Comment by johnwebbcole** [comment]
macOS comes with ab 2.3, it would be nice to get 2.4 via HomeBrew.
