### ISSUE TITLE
The LaTeXML formula needs some work

### ISSUE THREAD

**Issue by asmaier** [Homebrew/homebrew-core#22903]
The [formula for LaTeXML](https://github.com/Homebrew/homebrew-core/blob/master/Formula/latexml.rb) needs some work:

1. The scripts for `latexml`, `latexmlpost` etc. generated by the installation routine of brew in `/usr/local/bin/` overwrite the PERL5LIB environment variable, see e.g `/usr/local/bin/latexml`
```
#!/bin/bash
PERL5LIB="/usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5" exec "/usr/local/Cellar/latexml/0.8.2/libexec/bin/latexml" "$@"
```
This makes it impossible to set the PERL5LIB in the terminal for use with `latexml`, because all changes exported are overwritten and ignored. The line should better look like
```
#!/bin/bash
PERL5LIB="/usr/local/Cellar/latexml/0.8.2/libexec/lib/perl5":$PERL5LIB exec "/usr/local/Cellar/latexml/0.8.2/libexec/bin/latexml" "$@"
```
2. The perl scripts at `/usr/local/Cellar/latexml/0.8.2/libexec/bin/` for `latexml`, `latexmlpost` etc. use the shebang `#!/usr/bin/perl -w`. This successfully prevents the LaTeXML tools from using the perl installation managed by homebrew. Instead it will always use the Mac OS X system installation. Therefore the shebang should be changed to `#!/usr/bin/env perl` in all the scripts. 
3. The LaTeXML package is missing a dependency to the perl module "Image::Magick" or alternatively "Graphics::Magick". This is necessary, so LaTeXML can convert LaTeX files with images successfully (not a rare use case). But because of point 2 installing the Imagemagick formula manually with
```
brew install imagemagick --with-perl
```
will not help, because this will install the package for the perl version managed by homebrew (`/usr/local/bin/perl`) and not system perl used by LaTeXML.

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
...
># Formula additions or changes
>To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
>We will close issues requesting formulae changes.
