### ISSUE TITLE
Cracklib doesn't install correctly in custom prefixes

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-core#22926]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? > https://gist.github.com/24d03a280e2b018ac08698f046540d45
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I tried to install `cracklib` in my custom prefix (inside my home directory)

- What happened (include command output)

Postinstalation failed because it tried to write to `/usr/local/...`

- What you expected to happen

It should either write to my custom prefix, or know that it doesn't support custom prefixes and fall back to compile the package.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install cracklib
```

**Comment by fxcoudert** [comment]
From the post-install logs it's not clear how it failed. Could you please paste the error message you get?

**Comment by ilovezfs** [comment]
I have a fix locally. Not to worry.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by dwt** [comment]
Seems to work, but I'm not getting the bottle version (which is the one having the error for me) - or this is the actual fix that I'm not getting the bottled version. Not sure. :-)

**Comment by ilovezfs** [comment]
@dwt correct. That is by design. This software is not actually prefix independent.
