### ISSUE TITLE
"python2" is preferable rather than "python" in jupyter/kernels/python2/kernel.json (jupyter)

### ISSUE THREAD

**Issue by kkdd** [Homebrew/homebrew-core#22925]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

------------------------------

Hello,
I belive that "python2" is preferable rather than "python" in jupyter/kernels/python2/kernel.json.
I am sorry not to able to identify its defining description in "jupyter.rb".

```
$ diff -u jupyter/kernels/python2/kernel.json.orig jupyter/kernels/python2/kernel.json 
--- kernel.json.orig
+++ kernel.json
{
 "display_name": "Python 2", 
 "language": "python", 
 "argv": [
-  "python", 
+  "#{bin}/python2", 
```

**Comment by xyproto** [comment]
Why is Python 2 preferable over Python 3? Python 2 will reach its end of life in 2 years and 2 months, why not go for Python 3 now, to ease the burden when that time comes? Python 3 is the default version for many (most?) Linux distros right now.

**Comment by ilovezfs** [comment]
over "python" not "python3"

it already uses python 2

**Comment by kkdd** [comment]
Note that "python2" is intended to specify
- not /usr/bin/python (i.e., macOS-system's Python 2)
- but /usr/local/bin/python2 (i.e., homebrew's Python 2).

**Comment by ilovezfs** [comment]
@kkdd PR please?

**Comment by kkdd** [comment]
I regret to say that my PR https://github.com/Homebrew/homebrew-core/pull/23022 failed.

**Comment by ilovezfs** [comment]
@kkdd OK, I will look at why

**Comment by ilovezfs** [comment]
We'll track this on https://github.com/Homebrew/homebrew-core/pull/23022.
