### ISSUE TITLE
etc/ directory missing in unixodbc 2.3.5

### ISSUE THREAD

**Issue by v-makouz** [Homebrew/homebrew-core#22938]
I noticed that after installing unixodbc 2.3.5 the folder /usr/local/Cellar/unixodbc/2.3.5/etc/ is missing

When I manually extracted the following two packages:
https://homebrew.bintray.com/bottles/unixodbc-2.3.4.el_capitan.bottle.tar.gz
https://homebrew.bintray.com/bottles/unixodbc-2.3.5.el_capitan.bottle.tar.gz

I saw that indeed the 2.3.5 version didn't have the etc/ in it (but does have .brew/ which 2.3.4 doesn't have). I was also trying it on High Sierra VM and encountered the same issue, so it isn't just El Capitan

**Comment by ilovezfs** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/22939 which also relocate it to `/usr/local/etc`

**Comment by ilovezfs** [comment]
@v-makouz also note this is actually a Makefile bug. `Makefile.am` has
```
install-data-am:
        -touch $(DESTDIR)${sysconfdir}/odbcinst.ini
        -touch $(DESTDIR)${sysconfdir}/odbc.ini
        -mkdir -p $(DESTDIR)${sysconfdir}/ODBCDataSources
        cp unixodbc_conf.h $(DESTDIR)${includedir}/unixodbc_conf.h
```
which fails if `$(DESTDIR)${sysconfdir}` doesn't already exist.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`
