### ISSUE TITLE
Llvm not accepting --fopenmp option

### ISSUE THREAD

**Issue by kheyse-oqton** [Homebrew/homebrew-core#22970]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (No logs found)
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I have installed llvm using `brew install llvm` and was expecting this build of llvm to accept the `--fopenmp` option. However this is not the case.

```
$ /usr/local/opt/llvm/bin/clang --fopenmp
clang-5.0: error: unsupported option '--fopenmp'
clang-5.0: error: no input files
```

The brew formula contains an openmp test: https://github.com/ilovezfs/homebrew-core/blob/44360ede04e1e84d3c1d6de41ab240d096315398/Formula/llvm.rb#L320
But it is unclear to me what the status of this test is.

The last pull request on this formula did not include test results: https://github.com/Homebrew/homebrew-core/pull/22936

[brew config doctor output.txt](https://github.com/Homebrew/homebrew-core/files/1638784/brew.config.doctor.output.txt)

**Comment by kheyse-oqton** [comment]
Mentioning @ilovezfs

**Comment by ilovezfs** [comment]
`-fopenmp` not `--fopenmp`

**Comment by kheyse-oqton** [comment]
Thanks. Stupid mistake.
I was confused because the flag `-fopenmp` is not mentioned in the help, and the flag `--fopenmp` did not work, I thought something was wrong. Thanks for pointing out the typo.

**Comment by ilovezfs** [comment]
You're welcome!
