### ISSUE TITLE
Fail to upgrade macvim

### ISSUE THREAD

**Issue by knutsvk** [Homebrew/homebrew-core#22992]
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[https://gist.github.com/4a9b4d36c938b600bfaf719f8ef74cd1](https://gist.github.com/4a9b4d36c938b600bfaf719f8ef74cd1)

- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
(worked)

To help us debug your issue please explain:

- What you were trying to do (and why)
`brew reinstall macvim`
Tried to do this because general brew upgrade failed for macvim

- What happened (include command output)
```==> Reinstalling macvim --with-override-system-vim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-144.tar.gz
Already downloaded: /Users/ksk/Library/Caches/Homebrew/macvim-8.0-144.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-pe
==> make
Last 15 lines from /Users/ksk/Library/Logs/Homebrew/macvim/02.make:
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20180118-92100-3bevs0/macvim-snapshot-144/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20180118-92100-3bevs0/macvim-snapshot-144/src/MacVim/English.lproj/FindAndReplace.nib

CopyPlistFile build/Release/MacVim.app/Contents/Resources/KeyBinding.plist KeyBinding.plist
    cd /tmp/macvim-20180118-92100-3bevs0/macvim-snapshot-144/src/MacVim
    builtin-copyPlist --outdir /tmp/macvim-20180118-92100-3bevs0/macvim-snapshot-144/src/MacVim/build/Release/MacVim.app/Contents/Resources -- KeyBinding.plist

** BUILD FAILED **


The following build commands failed:
	StripNIB English.lproj/Preferences.nib
(1 failure)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting.html
```

- What you expected to happen
Upgrade to work 

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew reinstall macvim`
(macOS High Sierra Version 10.13.2)

**Comment by ilovezfs** [comment]
Have you launched Xcode.app and allowed it to install the additional components?

**Comment by ilovezfs** [comment]
See https://github.com/macvim-dev/macvim/issues/546.

**Comment by knutsvk** [comment]
I only have command line tools installed, would prefer not to install the full Xcode.app due to storage requirements. I find it surprising that this is a necessary requirement for MacVim, surely it should only require the CLT?

**Comment by ilovezfs** [comment]
The MacVim build requires Xcode.app.
```
  depends_on :xcode => :build
```

Your config shows Xcode.app is installed: https://gist.github.com/knutsvk/4a9b4d36c938b600bfaf719f8ef74cd1

```
Xcode: 9.2
```
