### ISSUE TITLE
Datomic installation failure

### ISSUE THREAD

**Issue by andriytyurnikov** [Homebrew/homebrew-core#23009]
To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install datomic`
- What happened (include command output)
```
Error: inreplace failed
/usr/local/etc/datomic/free-transactor.properties:
  expected replacement of "# data-dir=data" with "data-dir=/usr/local/var/lib/datomic/"
  expected replacement of "# log-dir=log" with "log-dir=/usr/local/var/lib/datomic/log"
```
- What you expected to happen
Successful install
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install datomic`

brew gist-logs datomic 
https://gist.github.com/c80cc0e4e6af00e5ff1cbfc0cc4a1bd8

@MerelyAPseudonym might be interested

**Comment by ilovezfs** [comment]
@andriytyurnikov thanks for reporting this. It should now be fixed if you `brew update`

**Comment by andriytyurnikov** [comment]
@ilovezfs  it is fixed!

**Comment by andriytyurnikov** [comment]
Thanks

**Comment by ilovezfs** [comment]
Yay! Thank you for testing and reporting back.
