### ISSUE TITLE
Polipo

### ISSUE THREAD

**Issue by Leowuqunqun** [Homebrew/homebrew-core#23023]
i installed polipo failed, 
brew version  1.3.0 , has already been updated
I got it errormesage 
![image](https://user-images.githubusercontent.com/11615263/35103078-d5ef3be2-fc9f-11e7-877d-6747565c7c07.png)

**Comment by ilovezfs** [comment]
Right. The current version of Homebrew is 1.4.3 https://github.com/Homebrew/brew/releases/latest

Please complete the issue template.
