### ISSUE TITLE
after today's update (git and some other package) I'm getting this when brew doctor:

### ISSUE THREAD

**Issue by dmarinescu** [Homebrew/homebrew-core#23036]
mbp:~ dmarinescu$ brew doctor
Warning: Calling 'depends_on :emacs' is deprecated!
Use 'depends_on "emacs"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/Formula/groovy-mode.rb:10:in `<class:GroovyMode>'
Please report this to the homebrew/emacs tap!

Warning: Calling 'depends_on :emacs' is deprecated!
Use 'depends_on "emacs"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-emacs/Formula/javaimp.rb:9:in `<class:Javaimp>'
Please report this to the homebrew/emacs tap!

Error: no implicit conversion of Symbol into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `extname'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:96:in `block in expand'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/delegate.rb:341:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1478:in `recursive_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1500:in `missing_dependencies'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:13:in `block in missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:12:in `missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:870:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
mbp:~ dmarinescu$

**Comment by ilovezfs** [comment]
As the message says, please report that to the emacs tap.
