### ISSUE TITLE
mysql 5.7.21 postinstall error thread_concurrency & mysql error 2002 

### ISSUE THREAD

**Issue by arpan03** [Homebrew/homebrew-core#23048]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 

https://gist.github.com/ebbc77e659d0c1c69c8cfaa496a6e77e

- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Was trying to install mysql

- What happened (include command output)

"brew install mysql" when I saw the warning that postinstall failed for mysql and it suggested I ran "brew postinstall mysql" which showed me this error:

brew postinstall mysql
==> Postinstalling mysql
==> /usr/local/Cellar/mysql/5.7.21/bin/mysqld --initialize-insecure --user=arpan --basedir=/usr/local/Cellar/mysql/5.7.21 --datadir=/usr/local/var/mysql --tmp
Last 15 lines from /Users/arpan/Library/Logs/Homebrew/mysql/post_install.01.mysqld:

/usr/local/Cellar/mysql/5.7.21/bin/mysqld
--initialize-insecure
--user=arpan
--basedir=/usr/local/Cellar/mysql/5.7.21
--datadir=/usr/local/var/mysql
--tmpdir=/tmp

2018-01-19T08:04:40.375476Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-01-19T08:04:40.389920Z 0 [Warning] Setting lower_case_table_names=2 because file system for /usr/local/var/mysql/ is case insensitive
2018-01-19T08:04:40.794374Z 0 [Warning] InnoDB: New log files created, LSN=45790
2018-01-19T08:04:40.845858Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2018-01-19T08:04:40.910708Z 0 [ERROR] unknown variable 'thread_concurrency=8'
2018-01-19T08:04:40.910802Z 0 [ERROR] Aborting

READ THIS: https://docs.brew.sh/Troubleshooting.html

brew services start mysql output: 

==> Successfully started `mysql` (label: homebrew.mxcl.mysql)

mysql command output: 

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

- What you expected to happen

To complete the installation of mysql.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install mysql

brew postinstall mysql

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is some kind of local configuration issue that you'll need to troubleshoot yourself.
