### ISSUE TITLE
cairo HEAD fails to build

### ISSUE THREAD

**Issue by theeternalsw0rd** [Homebrew/homebrew-core#23044]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
 https://gist.github.com/theeternalsw0rd/6b5938f2f72cdebae6e914ddfa936f43
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I like to try the bleeding edge to test stuff out. I am currently trying to install the HEAD version of cairo. I already had HEAD version installed successfully, so was performing a reinstall to get some updates.

`brew reinstall -svvv --HEAD cairo`

This caused a build issue. I've tracked it to a recent branch merge in cairo's master branch from a font-variations branch. This added a font-variations.c file to cairo's test folder. For some reason the compilation of this file during the make install process fails to include freetype properly when built using homebrew. If I build it outside of brew, everything works fine, so I don't believe it to be an issue with cairo's build system. So far I haven't been able to trace the reason for the failure.

Obviously this is currently a low priority issue. I'm reporting it anyways since it seems to be isolated to homebrew's build setup and will eventually become a higher priority issue when these changes are merged into cairo stable.

**Comment by ilovezfs** [comment]
Uninstall freetype and try the build again. If it still fails in the same way, freetype needs to be added as a dependency for head. If it succeeds, then we can pass some kind of --disable-freetype configure argument.

**Comment by theeternalsw0rd** [comment]
Uninstalled freetype and same result, however, freetype was pulled in as dependency already.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilovezfs** [comment]
We don't support --HEAD builds, and --HEAD builds fine for me locally so you'll need to troubleshoot this with upstream. It may be related to the fact that it's not finding your fontconfig.

**Comment by theeternalsw0rd** [comment]
Documenting for down the road and anyone doing Google searches. Turns out the head version of fontconfig, which I had installed, depends on ossp-uuid and cairo couldn't build without also depending on ossp-uuid.
