### ISSUE TITLE
Unable to install weechat using the `--with-python` option

### ISSUE THREAD

**Issue by jonathanhickford** [Homebrew/homebrew-core#23071]
I'm trying to install the weechat program, with the python plugin option.  I'm on OSX High Sierra, macOS 10.13.2.

Although I am able to install weechat using `brew install weechat`, I can't install it when using `brew install weechat --with-python`, it fails with an error during the build.

```
[ 70%] Linking C shared module irc.so
cd /tmp/weechat-20180119-10073-1yn00ed/build/src/plugins/irc && /usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/irc.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o irc.so CMakeFiles/irc.dir/irc.o CMakeFiles/irc.dir/irc-bar-item.o CMakeFiles/irc.dir/irc-buffer.o CMakeFiles/irc.dir/irc-channel.o CMakeFiles/irc.dir/irc-color.o CMakeFiles/irc.dir/irc-command.o CMakeFiles/irc.dir/irc-completion.o CMakeFiles/irc.dir/irc-config.o CMakeFiles/irc.dir/irc-ctcp.o CMakeFiles/irc.dir/irc-debug.o CMakeFiles/irc.dir/irc-ignore.o CMakeFiles/irc.dir/irc-info.o CMakeFiles/irc.dir/irc-input.o CMakeFiles/irc.dir/irc-message.o CMakeFiles/irc.dir/irc-mode.o CMakeFiles/irc.dir/irc-msgbuffer.o CMakeFiles/irc.dir/irc-nick.o CMakeFiles/irc.dir/irc-notify.o CMakeFiles/irc.dir/irc-protocol.o CMakeFiles/irc.dir/irc-raw.o CMakeFiles/irc.dir/irc-redirect.o CMakeFiles/irc.dir/irc-sasl.o CMakeFiles/irc.dir/irc-server.o CMakeFiles/irc.dir/irc-upgrade.o /usr/local/lib/libgnutls.dylib -L/usr/local/opt/libgcrypt/lib -lgcrypt -L/usr/local/opt/libgpg-error/lib -lgpg-error -lresolv 
[ 70%] Built target irc
make: *** [all] Error 2
```

I've run `brew update` and `brew doctor` says my system is ready to brew.

See output full from `brew gist-logs weechat --with-python`:
https://gist.github.com/anonymous/b02ba4aff5efe4e166ce686f9b1c0ef4

I've tried the other two options mentioned in the [WeeChat FAQ](https://weechat.org/files/doc/devel/weechat_faq.en.html)
 - `brew install weechat --with-aspell --with-curl --with-python --with-perl --with-ruby --with-lua --with-guile`
 - `brew install weechat --with-python --with-perl`

**Comment by ilovezfs** [comment]
Try adding
```
    if build.with? "python"
      ENV.prepend_path "PATH", Formula["python"].opt_libexec/"bin"
    end
```
at the beginning of the `def install` section

**Comment by seanleblanc** [comment]
I've tried adding that, now I get:


[ 61%] Built target irc
[ 62%] Linking C shared module tcl.so
cd /tmp/weechat-20180119-76523-1usiauk/weechat-2.0.1/build/src/plugins/tcl && /usr/local/Cellar/cmake/3.10.2/bin/cmake -E cmake_link_script CMakeFiles/tcl.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names   -o tcl.so CMakeFiles/tcl.dir/weechat-tcl.o CMakeFiles/tcl.dir/weechat-tcl-api.o /usr/lib/libtcl8.5.dylib ../libweechat_plugins_scripts.a
[ 62%] Built target tcl
make: *** [all] Error 2

**Comment by ilovezfs** [comment]
That doesn't show the error. Setting `export HOMEBREW_MAKE_JOBS=1` should improve the output.

**Comment by ilovezfs** [comment]
@jonathanhickford I cannot reproduce any issue here. For you, it is likely a parallelization problem. You can try setting `export HOMEBREW_MAKE_JOBS=1` and see if it still occurs.

@seanleblanc your problem is different and seems to be caused by its using /usr/local/lib/libz.dylib instead of the system /usr/lib/libz.dylib. You'd need to open your own issue and fill out the template completely. I suspect `brew doctor` will turn up some issues.
