### ISSUE TITLE
Gmsh upgrade failed

### ISSUE THREAD

**Issue by PierreMarchand20** [Homebrew/homebrew-core#23073]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x ] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? https://gist.github.com/51be368790ddf6b1698929c0f7baab5c

I tried to update homebrew and got the following error : 

> Error: Cannot install open-mpi because conflicting formulae are installed.
  mpich: because both install MPI compiler wrappers

> Please `brew unlink mpich` before continuing.

> Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.

I use `mpich` instead of `open-mpi`, I guess the dependency changed or something like that. But then I cannot upgrade `gmsh` anymore ? What do I have to do ?

**Comment by ilovezfs** [comment]
You need to use the `open-mpi` formula as we no longer support using alternative mpi implementations. So `brew unlink mpich && brew upgrade gmsh`. If you must use `mpich`, you'll need to host a separate version of the formula in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap). See https://brew.sh/2018/01/19/homebrew-1.5.0/ for additional details.
