### ISSUE TITLE
MCrypt Signal 11 on Mac OSX 10.13.2 High Sierrra

### ISSUE THREAD

**Issue by paper-skyline** [Homebrew/homebrew-core#23111]
Output of `brew config` and `brew doctor` at https://gist.github.com/anonymous/ed5e75d13a7c3d2862b75f6e5fe3e4ff

Anytime I try to encrypt a file with the command mcrypt from bash it will result in a signal 11 error and not actually encrypt the file. There was no output from brew -gist-logs mcrypt

```
$ mcrypt 5Mtest.txt 
Enter the passphrase (maximum of 512 characters)
Please use a combination of upper and lower case letters and numbers.
Enter passphrase: 

Enter passphrase: 


Signal 11 caught. Exiting.
```

If mcrypt was successful it should have resulted in a Signal 0, which indicates it successfully encrypted the specific file and produced in this case a 5Mtest.txt.nc file

```
$brew install mcrypt
$head -c 5242880 /dev/urandom > ./5Mtest.txt
$mcrypt 5Mtest.txt
```

**Comment by ilovezfs** [comment]
This seems to be a known and unresolved issue upstream: https://sourceforge.net/p/mcrypt/bugs/29/

**Comment by ilovezfs** [comment]
This patch from Debian seems to fix it http://http.debian.net/debian/pool/main/m/mcrypt/mcrypt_2.6.8-1.3.diff.gz

**Comment by paper-skyline** [comment]
Not sure how to apply that patch, but glad that it exists so that I can work on figuring out how to patch and make mcrypt work correctly again. Was trying to figure out how to install an older version through homebrew.

**Comment by ilovezfs** [comment]
```
iMac-TMP:homebrew-core joe$ git diff  --  Formula/mcrypt.rb 
diff --git a/Formula/mcrypt.rb b/Formula/mcrypt.rb
index daf66bb..84ac875 100644
--- a/Formula/mcrypt.rb
+++ b/Formula/mcrypt.rb
@@ -25,6 +25,11 @@ class Mcrypt < Formula
   # Upstream: https://sourceforge.net/p/mcrypt/patches/14/
   patch :DATA
 
+  patch do
+    url "http://http.debian.net/debian/pool/main/m/mcrypt/mcrypt_2.6.8-1.3.diff.gz"
+    sha256 "332268123ca1e7ea39402e400c4e6eaea3e97e0d6e73234ca8be325d9bdc7c76"
+  end
+
   def install
     resource("libmcrypt").stage do
       system "./configure", "--prefix=#{prefix}",
```
and brew reinstall -dvs mcrypt

**Comment by ilovezfs** [comment]
It looks like this is also fixing the same thing https://sourceforge.net/p/mcrypt/patches/13/

**Comment by paper-skyline** [comment]
Very cool, thank you for your help! 

Totally not a programer, just a user and fan of Homebrew. I just did a `brew edit mcrypt` and put in the patch portion followed by the the `brew reinstall -dvs mcrypt` and that did the trick!
