### ISSUE TITLE
"brew info gst-plugins-bad" is broken now that srtp@1.6 is deleted

### ISSUE THREAD

**Issue by yetisyny** [Homebrew/homebrew-core#23140]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

Hi this is the first issue I am posting to GitHub ever. Anyway, the command “`brew info gst-plugins-bad`” has been broken ever since the formula `srtp@1.6`, something that was an optional dependency of its, was deleted a few days ago.

The command “`brew info gst-plugins-bad`” yields the following output (with an error):
`gst-plugins-bad: stable 1.12.4 (bottled), HEAD`
`GStreamer plugins less supported, not fully tested`
`https://gstreamer.freedesktop.org/`
`Not installed`
`From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-plugins-bad.rb`
`==> Dependencies`
`Build: libtool ✔, pkg-config ✔`
`Required: gettext ✔, gst-plugins-base ✔, openssl ✔`
`Recommended: jpeg ✔, orc ✔`
`Error: No available formula with the name "srtp@1.6"`

This error does not affect the ability to install `gst-plugins-bad` as far as my testing of installing it goes, it seems all that is effected is the `brew info` command. But that command is needed to see what the options are.

Anyway there are three potential fixes:
1) Restore the deleted formula `srtp@1.6`. This would solve everything with no issues, as far as I can tell.
2) Remove the `srtp@1.6` optional dependency from `gst-plugins-bad`. This would get the `info` command for `gst-plugins-bad` working again, with the one minor issue that people who actually need to use srtp in gst-plugins-bad would not be able to have that option anymore. This is probably a small number of people, I mean I used to use that option myself but I did not actually need it, but still, it would be a loss of an option.
3) Change the dependency that `gst-plugins-bad` optionally uses from `srtp@1.6` to `srtp`, which is currently at version 2.1.0. Since this dependency is on an old version, there was definitely an incompatibility between `gst-plugins-bad` and `srtp` 2.x at the time `srtp` 2.x first came out, and given how `gst-plugins-bad` openly describes itself as being not that well maintained or tested, it would be kind of surprising if this third solution actually worked since that would imply the maintainers of `gst-plugins-bad` updated it to fix this. I looked at the commit history here: [https://github.com/GStreamer/gst-plugins-bad/search?o=desc&q=srtp&s=committer-date&type=Commits&utf8=%E2%9C%93](https://github.com/GStreamer/gst-plugins-bad/search?o=desc&q=srtp&s=committer-date&type=Commits&utf8=%E2%9C%93) and found no such update to make `gst-plugins-bad` compatible with newer `srtp` versions.

So solution #&#8288;3 is highly unlikely to work. Either solution #&#8288;1 or #&#8288;2 would solve the problem perfectly, my personal preference is with solution #&#8288;1, bringing back the deleted `srtp@1.6` formula, just in case anyone actually needs that functionality, but if the Homebrew maintainers prefer solution #&#8288;2, removing the line giving users the option of srtp support in `gst-plugins-bad`, out of a desire to not have too many outdated versions of formulae still around, I would not personally object, I am fine with any of the solutions as long as they work.

In defense of srtp 1.6 being brought back from deletion, I would point out that it actually was released more recently than srtp 2.1, both of them are listed as current releases on the official releases page for Cisco’s libsrtp: [https://github.com/cisco/libsrtp/releases](https://github.com/cisco/libsrtp/releases), and its release notes state “New 1.x.x release to stay compatible with 2.1.x.” Apparently the 1.x and 2.x APIs for it are incompatible, otherwise 2.x would work as a drop-in substitute for 1.x and that is clearly not the case. And srtp version 1.6 came out in August 2017 so it is not really that old, in fact its branch is being actively maintained.

So as far as I can tell, either bring back the deleted formula `srtp@1.6` or remove the optional dependency on it from `gst-plugins-bad`, in order to fix the “`brew info gst-plugins-bad`” command, those seem like the only 2 solutions that would actually work. Also, again, installations of `gst-plugins-bad` still work, the “`brew install gst-plugins-bad`” still works, whether from a bottle or with any of the options NOT relating to the missing `srtp@1.6`.

However, installation DOES fail if that option is enabled and the user does not have `srtp@1.6` installed. If I run “`brew install gst-plugins-bad --with-srtp@1.6`” I get the following output:
`Updating Homebrew...`
`==> Auto-updated Homebrew!`
`Updated Homebrew from df08bf2b0 to 97f0ef4c4.`
`Updated 1 tap (caskroom/cask).`
`No changes to formulae.`

`Error: No available formula with the name "srtp@1.6" (dependency of gst-plugins-bad)`
`==> Searching for a previously deleted formula (in the last month)...`
`Warning: homebrew/core is shallow clone. To get complete history run:`
`  git -C "$(brew --repo homebrew/core)" fetch --unshallow`

`srtp@1.6 was deleted from homebrew/core in commit c67396b:`
`  srtp@1.6: remove`

`To show the formula before removal run:`
`  git -C "$(brew --repo homebrew/core)" show c67396b^:Formula/srtp@1.6.rb`

`If you still use this formula consider creating your own tap:`
`  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html`

So actually the `brew install gst-plugins-bad` command can fail too if the `--with-srtp@1.6` option is enabled, currently, but the more irritating problem is that the `brew info gst-plugins-bad` command does not list the options in the first place.

Additionally, one last note: a number of other versioned formulae were deleted at the same time as `srtp@1.6` and it is possible some of them might be dependencies of formulae that still exist. It is certainly a problem when an existing formula claims a dependency on a formula that has been deleted and this might not be the only case of it. This is the only case that I know of, though, in homebrew-core. There are a bunch of formulae in homebrew-emacs that have similar bugs with “`brew info`” not working due to dependencies being specified wrong, but that bug is not one to be posted here in homebrew-core, I ought to report it to homebrew-emacs instead.

**Comment by ilovezfs** [comment]
This should be fixed now.

**Comment by yetisyny** [comment]
Yep, you deleted the optional dependency on the deleted formula, I just updated homebrew, it’s fixed. Thanks.

**Comment by WyseNynja** [comment]
Why was the versioned dependency deleted? A whole bunch of them were deleted on the 19th, but I can’t find any explanation as to why.

**Comment by ilovezfs** [comment]
Everything deleted was not in compliance with https://github.com/Homebrew/brew/pull/3697.
