### ISSUE TITLE
Provide python builds of specific versions

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-core#23193]
It seems there are now quite a few versioned packages in homebrew, so I am wondering if there could be python 2.6, 2.7, 3.4, 3.5, 3.6 packages in addition to python2-latest and python3-latest?

I know that it would greatly help me (I even installed macports in addition to homebrew just to get these for python package development.).

I know that there are other projects out there that also provide multiple python installation methods, but this would be so much easier if it could be done via homebrew. (Indeed I tried pretty much all of them, and they all kinda work, but do it so complicated that it's very brittle).

So I'm now left with pretty much just compiling my own versions of python and dumping them somewhere in the path - but I would much prefer to install these via homebrew.

So, is there anything stopping you guys from doing that?

**Comment by ilovezfs** [comment]
Please see the discussion on https://github.com/Homebrew/homebrew-core/pull/10239.
