### ISSUE TITLE
gpgme generate wrong cmake file

### ISSUE THREAD

**Issue by pasnox** [Homebrew/homebrew-core#23190]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [ X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Building kwalletd from KDE 5.42.0
- What happened (include command output)
Cmake find Gpgmepp correctly, but fails to build because the its cmake file only add the libgpg-error lib path, not the include path of libgpg-error.
- What you expected to happen
Gpgme.cmake contains entry for libgpg-error includes and build succeed
- Step-by-step reproduction instructions (by running `brew install` commands)
Create a c++ program that link gpgmepp
Include gpgme++.h -> gpg-error.h not found
# Formula additions or changes
The generated cmake file miss some entries for libgpg-error headers.

**Comment by ilovezfs** [comment]
This is an upstream issue, which you would need to report to https://dev.gnupg.org/
