### ISSUE TITLE
brew gnupg  2.2.4 breaks keyserver retrieval (install or upgrade)

### ISSUE THREAD

**Issue by erikjasiak** [Homebrew/homebrew-core#23208]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 
    _No logs_
- [X] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
    _Your system is ready to brew._

To help us debug your issue please explain:
- What you were trying to do (and why)
   On Sierra: install gpg keys before installing rvm - per their [instructions](https://rvm.io/rvm/install).
```
   > gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
```

- What happened (include command output)
   gpg commands _in 2.2.4, but not 2.2.3_ to connect/import keys fail, even after changing servers.

```
> gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: keyserver receive failed: No route to host
```

```
> gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
[if new install: "gpg: keyserver receive failed: No keyserver available"]
[if upgrade: hangs]
```

- What you expected to happen
   Key import
   After observing behavior, went to machine with 2.2.3 version of gnupg
     - ran the above keyserver command and it worked fine with 2.2.3
     - upgraded and re-ran with brew upgrade to 2.2.4, failed

[On box that had gnupg 2.2.3]
```
> brew list gpg2
/usr/local/Cellar/gnupg/2.2.3/bin/addgnupghome
/usr/local/Cellar/gnupg/2.2.3/bin/applygnupgdefaults
/usr/local/Cellar/gnupg/2.2.3/bin/dirmngr
/usr/local/Cellar/gnupg/2.2.3/bin/dirmngr-client
/usr/local/Cellar/gnupg/2.2.3/bin/gpg
/usr/local/Cellar/gnupg/2.2.3/bin/gpg-agent
/usr/local/Cellar/gnupg/2.2.3/bin/gpg-connect-agent
/usr/local/Cellar/gnupg/2.2.3/bin/gpgconf
/usr/local/Cellar/gnupg/2.2.3/bin/gpgparsemail
/usr/local/Cellar/gnupg/2.2.3/bin/gpgscm
/usr/local/Cellar/gnupg/2.2.3/bin/gpgsm
/usr/local/Cellar/gnupg/2.2.3/bin/gpgtar
/usr/local/Cellar/gnupg/2.2.3/bin/gpgv
/usr/local/Cellar/gnupg/2.2.3/bin/kbxutil
/usr/local/Cellar/gnupg/2.2.3/bin/symcryptrun
/usr/local/Cellar/gnupg/2.2.3/bin/watchgnupg
/usr/local/Cellar/gnupg/2.2.3/libexec/ (6 files)
/usr/local/Cellar/gnupg/2.2.3/share/doc/ (23 files)
/usr/local/Cellar/gnupg/2.2.3/share/gnupg/ (30 files)
/usr/local/Cellar/gnupg/2.2.3/share/info/ (3 files)
/usr/local/Cellar/gnupg/2.2.3/share/locale/ (28 files)
/usr/local/Cellar/gnupg/2.2.3/share/man/ (19 files)

> gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: 79 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 3 new signatures
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:              unchanged: 1
gpg:         new signatures: 3
```

[Upgraded box]
```
brew upgrade gnupg
==> Upgrading 1 outdated package, with result:
gnupg 2.2.4
==> Upgrading gnupg
==> Installing dependencies for gnupg: libtasn1, gnutls, libgcrypt
==> Installing gnupg dependency: libtasn1
==> Downloading https://homebrew.bintray.com/bottles/libtasn1-4.13.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtasn1-4.13.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libtasn1/4.13: 59 files, 435.2KB
==> Installing gnupg dependency: gnutls
==> Downloading https://homebrew.bintray.com/bottles/gnutls-3.5.17.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gnutls-3.5.17.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gnutls/3.5.17: 1,105 files, 7.6MB
==> Installing gnupg dependency: libgcrypt
==> Downloading https://homebrew.bintray.com/bottles/libgcrypt-1.8.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libgcrypt-1.8.2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libgcrypt/1.8.2: 19 files, 2.6MB
==> Installing gnupg
==> Downloading https://homebrew.bintray.com/bottles/gnupg-2.2.4.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gnupg-2.2.4.sierra.bottle.tar.gz
==> Caveats
Once you run this version of gpg you may find it difficult to return to using
a prior 1.4.x or 2.0.x. Most notably the prior versions will not automatically
know about new secret keys created or imported by this version. We recommend
creating a backup of your `~/.gnupg` prior to first use.

For full details on each change and how it could impact you please see
  https://www.gnupg.org/faq/whats-new-in-2.1.html
==> Summary
🍺  /usr/local/Cellar/gnupg/2.2.4: 133 files, 10.4MB
```

Ran upgraded version - note request to kill dirmngr to start using 2.2.4 version
(also note that running against gnupg 2.2.3 dirmngr is still working)
```
> gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: WARNING: server 'dirmngr' is older than us (2.2.3 < 2.2.4)
gpg: Note: Outdated servers may lack important security fixes.
gpg: Note: Use the command "gpgconf --kill all" to restart them.
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: 79 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 2
gpg:              unchanged: 2
```

kill 2.2.3 dirmngr, 2.2.4 gnupg breaks
```
> gpgconf --kill all

> gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: keyserver receive failed: No route to host
```

- Step-by-step reproduction instructions (by running `brew install` commands)
```
> brew install gnupg
> gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 
```
You can also get an alternative list of keyservers to try by running:
```
> gpg-connect-agent --dirmngr 'keyserver --hosttable'
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

```
> git log gnupg.rb
commit a2a92911413ff468a1b8da4b51745c97911bc124
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Wed Dec 20 20:01:41 2017 +0000

    gnupg: update 2.2.4 bottle.

commit 7b5a299d54433509dde023886df0970518ac2bba
Author: Dominyk Tiller <dominyktiller@gmail.com>
Date:   Wed Dec 20 18:58:43 2017 +0000

    gnupg 2.2.4

    Closes #21941.

    Signed-off-by: ilovezfs <ilovezfs@icloud.com>

commit 28164fdf63d8a7821bf000bf98b92bd0b013ac92
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Mon Nov 20 19:48:00 2017 +0000

    gnupg: update 2.2.3 bottle.

commit 9a30c3af9eec62b921cfdf36a3b89391959dbb45
Author: ilovezfs <ilovezfs@icloud.com>
Date:   Mon Nov 20 11:27:39 2017 -0800

    gnupg 2.2.3
```

**Comment by erikjasiak** [comment]
Also completely understand that this may be an issue with all gnupg 2.2.4 (nothing specific to brew) - only complication from brew's perspective is that on the new box there's no prior 2.2.3 formulae published to jump back to.

Will check with native non-brew 2.2.4 gnupg when i have a chance.

**Comment by ilovezfs** [comment]
This is something you'll need to discuss with upstream https://dev.gnupg.org/

**Comment by erikjasiak** [comment]
Okay, will do.

Did think it might be of add'l interest given the original [pull request to brew for 2.2.4 upgrade](https://github.com/Homebrew/homebrew-core/pull/21941) seems to note there's not much checking against if gpg if actually works.

If there's an example for adding/allowing 2.2.3 alongside 2.2.4 using formula@version, I'll try to put together a pull request, unless that's frowned upon.  (I like having a "last working rev" always available, but I'm sure keeping track of "working" is different for everyone,  and not something y'all want to be in the business of.)

For anyone else that finds this - brew switch back to the 2.2.3 version on the box that had it worked cleanly.

```
$ brew switch gnupg 2.2.3; gpgconf --kill all
Cleaning /usr/local/Cellar/gnupg/2.2.3
Cleaning /usr/local/Cellar/gnupg/2.2.4
68 links created for /usr/local/Cellar/gnupg/2.2.3

$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: key 3804BB82D39DC0E3: 79 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by ilovezfs** [comment]
Yeah, we don't allow versioned formulae for that purpose.

>Did think it might be of add'l interest given the original pull request to brew for 2.2.4 upgrade seems to note there's not much checking against if gpg actually works.

We run the full `make check` test suite so no idea what you mean.
