### ISSUE TITLE
Qt LTS @ing

### ISSUE THREAD

**Issue by xzcvczx** [Homebrew/homebrew-core#23234]
Qt has so far released 2 LTS versions of Qt with a gap of 14months, They seem to be offering support for these for 3 years, as there should only be a maximum of 3 of these supported at any one time would it not be worth @'ing these LTS versions of Qt so that other taps/repos may make use of stable versions in order to make it easier to use the qt frameworks from homebrew

Qt-5.6 is already @'d, currently it would only require @'ing Qt-5.9

**Comment by ilovezfs** [comment]
We will be removing qt@5.7 soon. Only qt@5.5 (for the sake of QtWebKit) and the main qt will remain at that point. There is no qt@5.6 is not available.

Our policy for versions are here: https://github.com/Homebrew/brew/blob/master/docs/Versions.md

Specifically,

>Versioned formulae submitted should be expected to be used by a large number of people. If this ceases to be the case: they will be removed. We will aim not to remove those in the top 1000 install_on_request formulae.

Given this is the first mention of any interest in an @5.9, and the motivation sounds theoretical, I don't think this would be a good use of our CI resources, as qt builds take several hours.

But thanks for the suggestion.
