### ISSUE TITLE
Sphinx will not build against MariaDB

### ISSUE THREAD

**Issue by nmagedman** [Homebrew/homebrew-core#23254]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install sphinx for use with mariadb.  MariaDB bills itself (per the formula description) as a "Drop-in replacement for MySQL".   Sphinx needs to be installed with the option `--with-mysql` in order to compile it with mysql support.   However, when the sphinx formula is installed with that option, it first attempts to install mysql.  This fails because mysql and mariadb conflict.

- What happened (include command output)
```
$ brew install mariadb
Warning: mariadb 10.2.12 is already installed

$ brew install sphinx --with-mysql
==> Installing dependencies for sphinx: mysql
==> Installing sphinx dependency: mysql
Error: Cannot install mysql because conflicting formulae are installed.
  mariadb: because mysql, mariadb, and percona install the same binaries.

Please `brew unlink mariadb` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side-effects in the
resulting software.
```

- What you expected to happen
I expected it to recognize that, even though mysql is not installed, an equivalent package (mariadb) _is_ installed, and to compile against that.

Although I could unlink mariadb (as instructed in the output), sphinx will end up building against mysql rather than mariadb.  And my mariadb installation will be broken.

Debian's APT supports a feature wherein a package "provides" a virtual package.   Other packages can then depend on that virtual package, without caring what physical package actually provides it.  Mariadb can then provide 'mysql', satisfying that dependency for any package that needs mysql (or a mysql drop-in replacement package).    Does Homebrew support anything like that?

- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install mariadb
$ brew install sphinx --with-mysql
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

[brew-sphinx-debug-output.txt](https://github.com/Homebrew/homebrew-core/files/1660745/brew-sphinx-debug-output.txt)

**Comment by ilovezfs** [comment]
You would need to create a separate version of the sphinx formula and maintain it in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).
