### ISSUE TITLE
packer fails to brew

### ISSUE THREAD

**Issue by martenson** [Homebrew/homebrew-core#2325]
### Bug reports:

I am brewing `brew install packer` and getting 404 on a code.google.com repo. The url itself redirects to https://code.google.com/archive/p/gosshold/ as Google has shut down the service. There is no repository to clone at either of those urls and I was unable to find the correct url.

(I am using linuxbrew but that is presumably not the problem here.)

```
==> Cloning https://github.com/mitchellh/multistep.git
Cloning into '/var/lib/jenkins/.cache/Homebrew/packer--github.com-mitchellh-multistep--git'...
remote: Counting objects: 116, done.
remote: Total 116 (delta 0), reused 0 (delta 0), pack-reused 116
Receiving objects: 100% (116/116), 22.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (64/64), done.
Checking connectivity... done.
==> Checking out revision 162146fc57112954184d90266f4733e900ed05a5
==> Cloning https://code.google.com/p/gosshold/
abort: HTTP Error 404: Not Found
Error: Failed to download resource "packer--code.google.com-p-gosshold"
```

**Comment by DomT4** [comment]
Should be fixed after a `brew update` via https://github.com/Homebrew/homebrew-core/commit/361ef46acc54d7bcd12ca577ed586bfb78996e7f. Thanks for letting us know! ❤️.

**Comment by martenson** [comment]
Splendid. Thanks for the fix! (nice! `+17 −311` )

**Comment by DomT4** [comment]
Yeah, they moved to the Go vendoring system upstream which is a lot more packager-friendly. We're hoping eventually the entire ecosystem moves across because it creates fewer breakage points for both us & end users.
