### ISSUE TITLE
helics.rb failed to build on 10.13.2

### ISSUE THREAD

**Issue by kdheepak** [Homebrew/homebrew-core#23357]
# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
I ran `brew update` twice as suggested by the [documentation](https://docs.brew.sh/Troubleshooting.html)
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
I ran `brew doctor` and fixed all issues that I thought could be related.
- [X] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/anonymous/68b56e299fcd63b631b1376dca2193d0

- What you were trying to do (and why)
I'm trying to create a formula for a CPP application. I'm able to build the application successfully from source on my Mac (10.13.2) using the install instructions. When I use the same instructions in `brew`, it throws the error shown in the [`gist`](https://gist.github.com/anonymous/68b56e299fcd63b631b1376dca2193d0)

<img width="1152" alt="screen shot 2018-01-27 at 5 27 04 am" src="https://user-images.githubusercontent.com/1813121/35472024-bba49ada-0324-11e8-8cf4-f9819513ef5c.png">

I've attached the gist that describes the formula [`helics.rb` here](https://gist.github.com/kdheepak/4cd1355fff3287f10b8425aa93b09600). I copied `helics.rb` to the formulas directory on my local machine. I tried `brew install --verbose --debug helics --HEAD` and got an error. I do not get this error if I build from source. I even opened the SHELL when the error occurred and typed `make` again and still got the same error.

If I clone the repository, and switch to the `develop` branch and run the install instructions, it works fine. I even tried the exact same `cmake` commands that `brew` generates and that also works successfully. My first reaction was that the `shim` for `clang` was causing an issue, but when I had an interactive SHELL I tested for the version of clang and that was identical to that in a normal SHELL.

Any suggestions on what might be going on here?

**Comment by kdheepak** [comment]
I tried the same thing on a different mac and got the same error. This is the gist-logs from the second computer (here](https://gist.github.com/anonymous/a3fb1bc876b83e4f9cff882a9cb82553).

**Comment by fxcoudert** [comment]
Hi, we do not have a `helics` formula as part of Homebrew core. I am not sure where you got that formula from, but it should probably be reported there instead.

**Comment by kdheepak** [comment]
It is a formula that I wrote. Any way I can debug this?

**Comment by ilovezfs** [comment]
Did you try `ENV.O0`

**Comment by kdheepak** [comment]
`ENV.O0` fixed this! I'm unable to find any mention of this in the documentation. Can you share why this works?

**Comment by ilovezfs** [comment]
The default optimization level in Homebrew is -Os. `ENV.O0` makes it -O0. The software you're building has a bug that causes the build to fail with -Os. It should be reported and fixed upstream.

**Comment by kdheepak** [comment]
Thanks for the comment! I'll take it up with the upstream developers.
