### ISSUE TITLE
Installing GCC --without-multilib fails on make bootstrap

### ISSUE THREAD

**Issue by CodingAnarchy** [Homebrew/homebrew-core#234]
### Bug reports:

Trying to run `brew install gcc --without-multilib` failed on `make bootstrap` with the following output:

```
checking for x86_64-apple-darwin15.4.0-gcc... /private/tmp/gcc20160411-2944-1d583db/gcc-5.3.0/build/./gcc/xgcc -B/private/tmp/gcc20160411-2944-1d583db/gcc-5.3.0/build/./gcc/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/bin/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/lib/ -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/include -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/sys-include   
checking for suffix of object files... configure: error: in `/private/tmp/gcc20160411-2944-1d583db/gcc-5.3.0/build/x86_64-apple-darwin15.4.0/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[2]: *** [configure-stage1-target-libgcc] Error 1
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2
```
The gist-logs are located here: https://gist.github.com/2511d63a9be0989e938d55fbac694cfb

Installing without the `--without-multilib` flag appears to work without issues.

**Comment by apjanke** [comment]
Hmm. Works for me on my 10.11.4 VM. [Logs here](https://gist.github.com/e257738138d467c6c00275a213561a44).

My relevant section:

```
checking whether ln -s works... yes
checking for x86_64-apple-darwin15.4.0-gcc... /private/tmp/gcc20160411-1629-1obwe7j/gcc-5.3.0/build/./gcc/xgcc -B/private/tmp/gcc20160411-1629-1obwe7j/gcc-5.3.0/build/./gcc/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/bin/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/lib/ -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/include -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/sys-include   
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /private/tmp/gcc20160411-1629-1obwe7j/gcc-5.3.0/build/./gcc/xgcc -B/private/tmp/gcc20160411-1629-1obwe7j/gcc-5.3.0/build/./gcc/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/bin/ -B/usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/lib/ -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/include -isystem /usr/local/Cellar/gcc/5.3.0/x86_64-apple-darwin15.4.0/sys-include    accepts -g... yes
```

Sorry this isn't helpful; just adding a data point.

Could you add the output of `brew ls` to that gist?

**Comment by CodingAnarchy** [comment]
I went ahead and added the output of `brew ls` to the gist as requested.

**Comment by apjanke** [comment]
Thanks. I don't see anything suspicious here. (Assuming the `gcc` in that list is from a later install with no `--without-multilib`.)

I'll try to reproduce against this set of installed packages.

**Comment by CodingAnarchy** [comment]
Your assumption is correct - the `gcc` in that list is from a later install with no `--without-multilib`.

**Comment by apjanke** [comment]
How about a `brew ls --full-name` and a `brew tap-info --installed`, too? There are some formulae there that aren't in the main taps. (Sorry I didn't include this first time around. Still learning the best approach to `brew` diagnostics here.)

**Comment by CodingAnarchy** [comment]
I've updated the gist to include that information.

**Comment by AndrazP** [comment]
Hi,
I get the same error output. What is the solution?

**Comment by UniqMartin** [comment]
@AndrazP Can you please post your logs of the failed build using `brew gist-logs gcc` so that we can inspect them and make sure it is indeed the same error? I'm afraid we can't provide a solution yet, as we weren't able to get to the root cause of the issue …

**Comment by AndrazP** [comment]
My log: https://gist.github.com/119f07327aa901dd32e9dc8e2b0b47fb
I honestly can't remember how I installed the previous version of gcc, with brew or directly. But gcc was in the `brew list`, `brew uninstall gcc` didn't help.

**Comment by UniqMartin** [comment]
@AndrazP Judging from the output in `00.doctor.out` in your Gist you've installed some earlier version of GCC without using Homebrew. Can you please try and resolve as many issues as possible that are reported by `brew doctor`? Particularly all those libraries from GCC and its dependencies (but other files listed there, too) have a pretty high chance of interfering with the build process. Ideally, you'll get to a stage where `brew doctor` no longer outputs any warnings …

Also, your build definitely fails for a different reason than the one of the original poster, so cleaning up your `/usr/local` (make backups if you're unsure about what is important to retain) should definitely help in your case. Removing and reinstalling GCC's dependencies (check out the output of `brew deps gcc`) could also help as there seem to be some files missing that should normally be there.

**Comment by UniqMartin** [comment]
@CodingAnarchy Can you try removing and then reinstalling `libmpc`? An error further up in your log indicates that there's an issue with that library. Maybe that's the reason why building GCC fails …

**Comment by CodingAnarchy** [comment]
Looks like that did the trick!  Thanks!
