### ISSUE TITLE
issue building metis4

### ISSUE THREAD

**Issue by jacob-roth** [Homebrew/homebrew-core#23405]
`brew config` output:
```
HOMEBREW_VERSION: 1.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 60a30e966b7cece5bd4823dae3fb981ab85106ea
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5313e2b5cd94da7667bc5b6ad0ade65205e2862f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/jakeroth/anaconda/bin/python => /Users/jakeroth/anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

`brew doctor` output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/jakeroth/anaconda/bin/curl-config
  /Users/jakeroth/anaconda/bin/freetype-config
  /Users/jakeroth/anaconda/bin/gsl-config
  /Users/jakeroth/anaconda/bin/icu-config
  /Users/jakeroth/anaconda/bin/libpng-config
  /Users/jakeroth/anaconda/bin/libpng16-config
  /Users/jakeroth/anaconda/bin/nc-config
  /Users/jakeroth/anaconda/bin/python-config
  /Users/jakeroth/anaconda/bin/python2-config
  /Users/jakeroth/anaconda/bin/python2.7-config
  /Users/jakeroth/anaconda/bin/xml2-config
  /Users/jakeroth/anaconda/bin/xslt-config
```

- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap. **I tried `brew install metis4` and `brew install homebrew/core/metis4` and neither worked; I then tired `brew install aamath` which worked**
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step? **All except for the Anaconda ones**
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **I get the following error: `Error: No available formula with the name "metis4"`**
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? **above**

Overview:
- I'm trying to download and build metis4 so that I can build some HSL libraries which require metis4. I know that it recently moved from science to core, but I've been unable to build it
- I'm getting the following error:
```
Error: No available formula with the name "metis4"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

```

I'm probably messing something silly up -- any help would be appreciated! Thanks!

**Comment by vinyldarkscratch** [comment]
@jacob-roth It looks like the formula name is `metis` (without the 4), and a quick `brew info` on it showed that it's now on version 5.1.0.  You'll want to run `brew install metis` instead.  😉

The question is, however: do you need metis 4.x.x specifically?

**Comment by fxcoudert** [comment]
The latest version of `metis` (i.e. 5.1.0) has been migrated to Homebrew core as part of the deprecation of homebrew-science. The legacy `metis4` formula can now be found in the `brewsci/science` external tap: https://github.com/brewsci/homebrew-science

**Comment by ilovezfs** [comment]
Please note, though, that https://github.com/brewsci/homebrew-science is the same tap with the same issues that led to https://github.com/Homebrew/homebrew-science deprecated/archived and is not endorsed in any way by the Homebrew project.

**Comment by jacob-roth** [comment]
Sorry, I need `metis 4.0.3` -- I should have included in my original post. Is the best (/only?) way to do this with the legacy formula?
