### ISSUE TITLE
How to migrate from homebrew to homebrew-core?

### ISSUE THREAD

**Issue by tschoonj** [Homebrew/homebrew-core#235]
Sorry if I missed it, but how do I migrate my open PR in legacy-homebrew to here?

Thanks!

**Comment by apjanke** [comment]
Is it an update to a formula, or something to the core `brew` package manager?

If it's a formula update, no need to migrate: maintainers can pull directly from PRs on the legacy repo to the new homebrew-core repo (thanks, @xu-cheng!), and we're still going through the backlog there. 

If it's a core `brew` code update, you can migrate it to a new PR over on `homebrew/brew` using GitHub's `.patch` mechanism and a new PR.

Any PRs in particular that need attention?

**Comment by tschoonj** [comment]
Ok, thanks for the info.

I have only one PR remaining in legacy: Homebrew/legacy-homebrew#50257

**Comment by apjanke** [comment]
Oh, that one's a biggie, and it's not ready to merge yet, right? Probably better to transfer it to a new PR on the new repo.

The `brew pull` command can help transfer this:
* In the new repo (with your new fork as a remote), create a new branch for this PR
* Check out that branch and `cd $(brew --repo homebrew/core)`
* Run `brew pull --legacy 50257`. That'll pull all the commits from that old PR down to the branch that you're currently in.
* `git push <tschoonj-or-whatever-your-remote-is>` to push it to a new branch in the new repo
* Make a new PR from that, and close the old PR

**Comment by tschoonj** [comment]
Thanks Andrew, will give it a try.

**Comment by DomT4** [comment]
Presume this is safe to close now as per https://github.com/Homebrew/homebrew-core/pull/267 being opened.
