### ISSUE TITLE
`brew install valgrind` fails but new version is available

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#23536]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
brew install valgrind
valgrind: This formula either does not compile or function as expected on macOS
versions newer than Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

brew gist-logs valgrind
Error: No logs.
```

NOTE: https://stackoverflow.com/questions/40650338/valgrind-on-macos-sierra#comment83098366_40713782 says:
> Now the latest version Valgrind works on Mac OS. – Musen Jan 2 at 14:36

```
brew config
HOMEBREW_VERSION: 1.5.0-25-g34aa15b
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 34aa15b69f49b17862c7d0ea6c22692672cfc607
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 099a7a00a4e189b5344d8a665694763858e8064b
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /Users/timothee/homebrew
HOMEBREW_REPOSITORY: /Users/timothee/homebrew
HOMEBREW_CELLAR: /Users/timothee/homebrew/Cellar
HOMEBREW_CELLAR: /Users/timothee/homebrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_PREFIX: /Users/timothee/homebrew
HOMEBREW_REPOSITORY: /Users/timothee/homebrew
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /Users/timothee/homebrew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/timothee/homebrew/opt/python/libexec/bin/python => /Users/timothee/homebrew/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9.0.1
macOS: 10.13.1-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  numpy
  opencv_dbg

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /Users/timothee/usr/local/bin/
```

**Comment by timotheecour** [comment]
workaround: `brew install --HEAD valgrind`
not sure why https://github.com/Homebrew/homebrew-core/issues/18998 was closed; why not keep it open until `brew install valgrind` works?

**Comment by ilovezfs** [comment]
We don't keep issues or PRs open as placeholders.

**Comment by bitboyz** [comment]
Get the following error 👎 
<img width="1263" alt="screen shot 2018-02-06 at 10 07 02 pm" src="https://user-images.githubusercontent.com/33888097/35901135-1fbc8830-0b8a-11e8-8729-7bbcb3618c1b.png">

**Comment by hasahmed** [comment]
@bitboyz I'm having the same issue

**Comment by ElliotVilhelm** [comment]
same issue

**Comment by ilovezfs** [comment]
http://valgrind.org/downloads/repository.html

> There is also an http mirror for the repository set up at repo.or.cz. You can use it if you are behind a firewall and cannot tunnel through with socat. To clone from this mirror, do this:
>
>  git clone http://repo.or.cz/valgrind.git

**Comment by seanwayland** [comment]
Same issue  here with brew install --HEAD valgrind 
error: Unable to find ec883e4975493e3ff724d99f728055cf57948c2b under https://sourceware.org/git/valgrind.git

**Comment by joshuakim314** [comment]
having same issue :(

**Comment by inumanag** [comment]
Workaround: do `brew edit valgrind`  and replace https://sourceware.org/git/valgrind.git with git://sourceware.org/git/valgrind.git in `head` section of the formula.
