### ISSUE TITLE
"illegal hardware instruction" running gstreamer from bottle

### ISSUE THREAD

**Issue by tmehlinger** [Homebrew/homebrew-core#23581]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### `brew gist-logs gstreamer`

```
Error: No logs.
```

### `brew config`

```
HOMEBREW_VERSION: 1.5.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 60a30e966b7cece5bd4823dae3fb981ab85106ea
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a6921e288881db8c33f2471c118b5c63b3b5caf5
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

### `brew doctor`

```
Your system is ready to brew.
```

-----------

I'm trying to run gstreamer to capture an RTP stream and getting `illegal hardware instruction`, at which point the OS kills the process:

```
$ gst-launch-1.0 -v udpsrc port=29002 caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)101" ! rtph264depay ! decodebin ! videoconvert ! autovideosink
Setting pipeline to PAUSED ...
[1]    42423 illegal hardware instruction  gst-launch-1.0 -v udpsrc port=29002 caps =  ! rtph264depay ! decodebin !  !
```

My first guess was that I had a dependency out of date that needed to be rebuilt (I had just done system updates before I installed gstreamer). However, installing with `--HEAD` and then running gstreamer works without error.

**Comment by tmehlinger** [comment]
Adding a bit more detail.

It's actually not clear to me whether this is a problem in gstreamer or one of the gst-plugins-* packages. Building everything with `--HEAD` works but installing from bottle does not.

**Comment by fxcoudert** [comment]
Can you try building the same exact version from source (`brew install -s gstreamer`) to see if it is a source vs. binary problem, or a stable vs. head issue? Thanks.

**Comment by ilovezfs** [comment]
@tmehlinger did you manage to resolve this? I notice you've not yet provided the information that @fxcoudert requested.
