### ISSUE TITLE
Cannot update `htop`

### ISSUE THREAD

**Issue by ablyeom** [Homebrew/homebrew-core#23628]
I couldn't update `htop` several months.

Htop is not listed at [`Formulae missing High Sierra bottles`](https://github.com/Homebrew/homebrew-core/issues/18493)

How can i fix it?

**Comment by 9mm** [comment]
https://github.com/Homebrew/homebrew-core/issues/22518

**Comment by ilovezfs** [comment]
Wait for macOS 10.13.4, which has the relevant bug fixed. Then we will lift the max OS requirement
