### ISSUE TITLE
Error Installing PyQT5 on python 2.7 with SIP 4.19

### ISSUE THREAD

**Issue by nikorose87** [Homebrew/homebrew-core#23713]
Hi 
I'm trying to install SIP 4.19.7 in order to install PyQT5 on python 2.7. SIP was installed succesfully. However, installing PyQT5, I got the following error: 
```
Error: /usr/include/python2.7/sip.h has version 4.17 but /usr/bin/sip has
version 4.19.7.
```
when I type SIP -V, it says that I've got 4.19 version, but when installed PyQT said the typed before.

thanks in advice.

**Comment by fxcoudert** [comment]
Please fill out our issue template, including request list of commands issued, and output of `brew doctor` and `brew gist-logs`.
