### ISSUE TITLE
GDAL fails to build.

### ISSUE THREAD

**Issue by oukjweather** [Homebrew/homebrew-core#2373]
### Bug reports:

Failing to build upgraded gdal after multiple attempts. Error is as follows:

$ brew upgrade gdal --HEAD
==> Upgrading 1 outdated package, with result:
gdal HEAD
==> Upgrading gdal
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Cloning https://svn.osgeo.org/gdal/trunk/gdal
Updating /Users/{user}/Library/Caches/Homebrew/gdal--svn-HEAD
...
Last 15 lines from /Users/{user}/Library/Logs/Homebrew/gdal/05.python:
copying osgeo/gdalconst.py -> build/lib.macosx-10.11-intel-2.7/osgeo
copying osgeo/gdalnumeric.py -> build/lib.macosx-10.11-intel-2.7/osgeo
copying osgeo/gnm.py -> build/lib.macosx-10.11-intel-2.7/osgeo
copying osgeo/ogr.py -> build/lib.macosx-10.11-intel-2.7/osgeo
copying osgeo/osr.py -> build/lib.macosx-10.11-intel-2.7/osgeo
running build_ext
building 'osgeo._gdal' extension
creating build/temp.macosx-10.11-intel-2.7
creating build/temp.macosx-10.11-intel-2.7/extensions
clang -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -I/usr/local/opt/sqlite/include -pipe -Wno-error=unused-command-line-argument-hard-error-in-future -I../../port -I../../gcore -I../../alg -I../../ogr/ -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/private/tmp/gdal-20160624-29288-56n72y/homebrew-numpy/lib/python2.7/site-packages/numpy/core/include -I/private/tmp/gdal-20160624-29288-56n72y/include -c extensions/gdal_wrap.cpp -o build/temp.macosx-10.11-intel-2.7/extensions/gdal_wrap.o
extensions/gdal_wrap.cpp:5929:10: fatal error: 'gdal_utils.h' file not found
#include "gdal_utils.h"
         ^
1 error generated.
error: command 'clang' failed with exit status 1

`brew gist-logs gdal`: https://gist.github.com/34364a85b2ba43bee622ac6d69b12d05

Thank you for taking a look at this.

**Comment by DomT4** [comment]
I'm afraid we don't really provide support for `head` installations because by their very nature they break often & in interesting ways. This is something you'll likely need to report upstream.
