### ISSUE TITLE
unable to install wimlib with --with-ntfs-3g option

### ISSUE THREAD

**Issue by jaywang0tw** [Homebrew/homebrew-core#23731]
I tried to install wimlib with --with-ntfs-3g option enabled. However, it kept looking for the dependency of ntfs-3g at homebrew/fuse/ntfs-3g.  Since the repo homebrew-fuse was deprecated and migrated into homebrew-core.  The formula of ntfs-3g is not there and is in homebrew-core now. Therefore, I cannot install it with ntfs-3g dependency.

```
Error: No available formula with the name "homebrew/fuse/ntfs-3g" (dependency of wimlib)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/fuse is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/fuse)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
```

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update`
