### ISSUE TITLE
Mono

### ISSUE THREAD

**Issue by sandeepthukral** [Homebrew/homebrew-core#23739]
OS X 10.12.6 Sierra

- What you were trying to do (and why)
Install project mono using homebrew
- What happened (include command output)
Mono installed, but when I ran it, it threw an error saying `libgdiplus.dylib` is not found
- What you expected to happen
I looked up on the internet and found that I had to install `mono-libgdiplus`
`brew install mono-libgdiplus`
- Step-by-step reproduction instructions (by running `brew install` commands)
No real steps

I do not know how homebrew works, but somehow, this needs to be a dependency. In the future, people should not have to go looking for this step they have to manually perform for mono to run properly.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
>Mono installed, but when I ran it, it threw an error saying libgdiplus.dylib is not found

I don't know what this means.

**Comment by sandeepthukral** [comment]
`$ mono Applications/fiddler-mac/Fiddler.exe
WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all exception inside UnhandledException handler: The type initializer for 'Fiddler.CONFIG' threw an exception.

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.WindowsFormsSynchronizationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeEngine' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.ThemeWin32Classic' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.KnownColors' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.dylib
`

The last statement says
`System.DllNotFoundException: libgdiplus.dylib`

**Comment by ilovezfs** [comment]
OK, so that dependency is specific to Fiddler. I don't think we need to require it for everyone who uses Homebrew's mono.

**Comment by sandeepthukral** [comment]
Thanks for the information.

**Comment by ilovezfs** [comment]
@sandeepthukral you're welcome. My suggestion would be to contact the upstream Fiddler project and ask them to note in their documentation that if you're using Homebrew's mono then Fiddler has additional dependencies beyond just the main formula.
