### ISSUE TITLE
gd Error: Empty archive

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#2375]
```
$ brew upgrade 
==> Upgrading 1 outdated package, with result:
gd 2.2.2
==> Upgrading gd
==> Downloading https://github.com/libgd/libgd/releases/download/gd-2.2.2/libgd-2.2.2.tar.xz
Already downloaded: /Users/yurikoles/Library/Caches/Homebrew/gd-2.2.2.tar.xz
Error: Empty archive
```
But I can see that gd-2.2.2.tar.xz is valid archive that I can extract.

**Comment by ilovezfs** [comment]
Maybe
`brew fetch --force --build-from-source gd`

**Comment by yurikoles** [comment]
@ilovezfs the file is correct, it passes sha256 check, but brew just don't wish to extract it.

It's not the case, but formula must depend on xz.

**Comment by ilovezfs** [comment]
no xz dependency is automatically handled due to the url. maybe you need to reinstall xz?

**Comment by yurikoles** [comment]
Seems like I had built xz on newer version of OSX. I made downgrade recently.

**Comment by ilovezfs** [comment]
Cool. Glad you got it worked out.

**Comment by yurikoles** [comment]
@ilovezfs thank you for your help.
