### ISSUE TITLE
Match the locale of the old cluster

### ISSUE THREAD

**Issue by brendon** [Homebrew/homebrew-core#23777]
https://github.com/Homebrew/homebrew-core/blob/83f665fe3cefb8adeb0c447343d813eb30eea579/cmd/brew-postgresql-upgrade-database.rb#L64

I ran into difficulty and had to migrate manually because my old cluster was en_NZ and the new one kept being created as en_US. I couldn't see a way around it other than manually making the new cluster as en_NZ and then migrating manually. Do you think there's a way to detect this while the cluster is offline (from the script), then initialise the new cluster with this locale?

**Comment by ilovezfs** [comment]
Please always fill out the issue template completely.

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
> Do you think there's a way to detect this while the cluster is offline (from the script), then initialise the new cluster with this locale?

We run `initdb` the same way in both the formula and that script so: no, unfortunately not. If it's different you'll need to upgrade it manually too. Sorry!

**Comment by brendon** [comment]
Thanks @MikeMcQuaid. @ilovezfs, sorry, I initiated the issue from the line of code in the file view so it didn't pre-populate the issue with the issue template. I would have filled it out had I seen it :)
