### ISSUE TITLE
Vim installs python(2) too when asking for python3 (`--with-python3`) -- is it expected?

### ISSUE THREAD

**Issue by iamitava** [Homebrew/homebrew-core#23771]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? => [vim on macOS 10.13.3 - Homebrew build logs · GitHub](https://gist.github.com/anonymous/33f8519f4c304d6655719d51ea47a748)
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
   Trying to upgrade vim (originally installed with: `--with-override-system-vi --with-python3`). I don't have Homebrew python2 installed, only python3 (and the system python).

- What happened (include command output)
   brew installs python2 too
   ```
   $ brew upgrade vim --ignore-dependencies
   Updating Homebrew...
   ==> Upgrading 1 outdated package, with result:
   vim 8.0.1450
   ==> Upgrading vim --with-override-system-vi --with-python3
   ==> Installing dependencies for vim: sqlite, python
   ...
   ==> Installing vim dependency: python
   ==> Downloading https://homebrew.bintray.com/bottles/python-2.7.14_2.high_sierra.bottle.tar.gz
   Already downloaded: /Users/abhattachar9/Library/Caches/Homebrew/python-2.7.14_2.high_sierra.bottle.tar.gz
   ==> Pouring python-2.7.14_2.high_sierra.bottle.tar.gz
   ...
   ```

- What you expected to happen
   I expected that vim would use python3 only. Are there other dependencies on python2?

- Step-by-step reproduction instructions (by running `brew install` commands)
   ```
   $ brew uninstall python
   $ brew install vim --with-python3
   ```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
It is. However, you can install with `--with-python3 --without-python` to achieve what you want!

**Comment by iamitava** [comment]
Thanks @fxcoudert -- that incantation works (but looks a bit strange) 👍
