### ISSUE TITLE
telnet failed to build on 10.13.3

### ISSUE THREAD

**Issue by Omniscimus** [Homebrew/homebrew-core#23838]
# Steps taken:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# Explanation:
- What you were trying to do (and why):
I was trying to install telnet by building it from source: `brew install --build-from-source telnet`.

- What happened (include command output):
Homebrew reported an error. See [the gist](https://gist.github.com/anonymous/776af5ab6240754bfcfaf3f1dee640aa).

- What you expected to happen:
I expected Homebrew to build telnet from source and install it.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install --build-from-source telnet`

Note: running just `brew install telnet` works.

**Comment by fxcoudert** [comment]
```
Error: Version value must be a string; got a NilClass ()
/usr/local/Homebrew/Library/Homebrew/version.rb:365:in `initialize'
/usr/local/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:25:in `new'
/usr/local/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:25:in `message'
```

Has to do with you not having Xcode installed, apparently… seems like a `brew` bug, rather than a specific problem with the `telnet` formula

**Comment by ilovezfs** [comment]
CC @MikeMcQuaid
