### ISSUE TITLE
Is there any possibility of having `conflicts_with` be finer-grained?

### ISSUE THREAD

**Issue by deinspanjer** [Homebrew/homebrew-core#23837]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [X] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade `parallel` package when `moreutils` package was installed with the `--without-parallel` option

- What happened (include command output)
`brew upgrade`
```==> Upgrading parallel
Error: Cannot install parallel because conflicting formulae are installed.
  moreutils: because both install a 'parallel' executable.

Please `brew unlink moreutils` before continuing.
```
- What you expected to happen
It would be nice if it could understand that `moreutils` was installed with the `--without-parallel` flag specifically to avoid this conflict.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install moreutils --without-parallel`
`brew install parallel`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by yetisyny** [comment]
For what it’s worth, using the `--force` option (or `-f` for short) with the `brew install` command allows you to install both formulae at the same time and is the workaround I have been using to have both `moreutils` installed with the `--without-parallel` option as well as having `parallel` installed.

I have encountered the same exact issue with the same exact 2 formulae and while I consider this an annoyance, I have gotten used to using `--force` to just make it work. I didn’t even think of filing a bug report. But yes, it would be nice if Homebrew could realize that the 2 formulae do not actually conflict if `moreutils` is installed with the `--without-parallel` option.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update`.
