### ISSUE TITLE
cannot install on Mac OSX 10.8.5 ==> Downloading and installing Homebrew... You must: brew install git You must: brew install git Error: Git is unavailable

### ISSUE THREAD

**Issue by Bazookato** [Homebrew/homebrew-core#2385]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by Bazookato** [comment]
macbookato:~ Katoo$     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...

You must: brew install git
You must: brew install git
Error: Git is unavailable
Failed during: /usr/local/bin/brew tap homebrew/core
macbookato:~ Katoo$ 
macbookato:~ Katoo$  brew install wget
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
macbookato:~ Katoo$ brew update
You must: brew install git
You must: brew install git
Error: Git must be installed and in your PATH!
macbookato:~ Katoo$ brew update
You must: brew install git
You must: brew install git
Error: Git must be installed and in your PATH!
macbookato:~ Katoo$ brew doctor
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
macbookato:~ Katoo$ brew edit $FORMULA
You must: brew install git
You must: brew install git
Error: Changes will be lost!
The first time you `brew update', all local changes will be lost, you should
thus `brew update' before you `brew edit'!
macbookato:~ Katoo$ rew gist-logs <formula>
-bash: syntax error near unexpected token `newline'
macbookato:~ Katoo$ brew install git
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
macbookato:~ Katoo$ brew doctor
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
macbookato:~ Katoo$

**Comment by bfontaine** [comment]
@Bazookato Can you give us more information on your environment? Which version of OS X do you use?

**Comment by Bazookato** [comment]
MacBookPro 2011 OS X 10.8.5

**Comment by Bazookato** [comment]
I tried "brew install git" but won't work

**Comment by blogabe** [comment]
Did you ```xcode-select --install```?

**Comment by ilovezfs** [comment]
10.8 is fine: https://gist.github.com/ilovezfs/a16ea718fc40101ae38b4056323bb8ea

I agree with @blogabe. This looks like neither Xcode nor CLT are installed.

**Comment by ilovezfs** [comment]
Yeah, if you have no git, and you run the install script, you get exactly what he's seeing above because core cannot be tapped: https://gist.github.com/ilovezfs/0009253f54da8ce8b86b9ae517518346

**Comment by MikeMcQuaid** [comment]
@ilovezfs We should probably detect that a little nicer, though and perhaps offer to `xcode-select --install`.

**Comment by Bazookato** [comment]
macbookato:~ Katoo$ xcode-select --install
xcode-select: Error: unknown command option '--install'.

xcode-select: Report or change the path to the active
              Xcode installation for this machine.

Usage: xcode-select --print-path
           Prints the path of the active Xcode folder
   or: xcode-select --switch <xcode_path>
           Sets the path for the active Xcode folder
   or: xcode-select --version
           Prints the version of xcode-select

macbookato:~ Katoo$

**Comment by Bazookato** [comment]
not working either...

**Comment by ilovezfs** [comment]
That's because `--install` does not exist on 10.8. You should just download Xcode.app (Version 5.1.1 (5B1008)) from Apple. The command line tools are only optional if you have Xcode.app, and they can be installed directly from Xcode 5.1.1 if you have happen to want them.

**Comment by ilovezfs** [comment]
@Bazookato for what it's worth the Mountain Lion Command Line Tools and Xcode.app direct download URLs are

[Command Line Tools (CLT) for Mountain Lion (April 2014)](http://adcdownload.apple.com/Developer_Tools/command_line_tools_os_x_mountain_lion_for_xcode__april_2014/command_line_tools_for_osx_mountain_lion_april_2014.dmg)
[Xcode.app 5.1.1](http://adcdownload.apple.com/Developer_Tools/xcode_5.1.1/xcode_5.1.1.dmg)

But you have to visit https://developer.apple.com/download/more/ and log in to your developer account (free or paid) to access the links anyway. To sign up if you haven't already: https://developer.apple.com/account/.

Note that the CLT can also be downloaded from within Xcode.app 5.1.1, but once you have Xcode.app, the CLT are optional for Homebrew anyway.

**Comment by Bazookato** [comment]
Guys, you are all very kind but I am lost as Alice in Wonderland. I actually landed here because Download Helper - Firefox Add-on - says I need to install a converter and linked me to your page:
http://www.downloadhelper.net/install-converter3.php

But I am a video editor and not a developer!!! *_*

**Comment by Bazookato** [comment]
And of course I can't manage to install that little converter...

**Comment by ilovezfs** [comment]
You don't need to be a developer to use brew, but you would need to install Xcode 5.1.1 from Apple.

**Comment by tomck** [comment]
@Bazookato Perhaps this video will help: https://www.youtube.com/watch?v=dR5UnYA5Sx8 ?

**Comment by jmmk** [comment]
I ran into this as well. I installed the CLI Tools and have git 1.8.5.2 (Apple Git-48) available on the system. Do I actually have to install the Xcode app? What's different than just installing the CLI Tools?

**Comment by MikeMcQuaid** [comment]
@jmmk That should be enough. Your bug is different if CLI Tools are installed. Can you open a  new issue?

**Comment by jmmk** [comment]
@MikeMcQuaid I ended up writing it off as a failed experiment and upgrading to El Capitan.

**Comment by MikeMcQuaid** [comment]
Resolved as much as we can for now in https://github.com/Homebrew/install/pull/54.
