### ISSUE TITLE
MacVim fails to install with extra flags.

### ISSUE THREAD

**Issue by mcourteaux** [Homebrew/homebrew-core#23921]
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install MacVim with Lua support (as described here: https://github.com/jeaye/color_coded#os-x).
- What happened (include command output)
```
Error: Version value must be a string; got a NilClass ()
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/version.rb:365:in `initialize'
/usr/local/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:25:in `new'
/usr/local/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:25:in `message'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:409:in `block (2 levels) in check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:407:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:407:in `block in check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:406:in `each_pair'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:406:in `check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:379:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:135:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:128:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:341:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
- What you expected to happen
Install it, duh.
- Step-by-step reproduction instructions (by running `brew install` commands)

      brew install macvim --with-lua --with-override-system-vim

Note that when omitting the *all* of the extra flags, it works. Adding one or both, causes this issue. I have everything updated (macOS, brew, everything).

## `brew config`
```
HOMEBREW_VERSION: 1.5.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: af8f8f11e32fe78677fc1d4cd62c07a29dc6d326
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc6e7485e89130b078a621caadde942c5610d25d
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_152
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A
```
`brew doctor` reports no issues: `Your system is ready to brew.`

**Comment by DomT4** [comment]
This is likely fixed by https://github.com/Homebrew/brew/commit/c32865011d1536eb6f7e626a3cb389d35beda48a. Probably just a case of waiting for @MikeMcQuaid to cut a new tag after that commit.

**Comment by ilovezfs** [comment]
For now, install Xcode as a workaround since it's required anyway, and once it's installed the issue goes away.

**Comment by mcourteaux** [comment]
Okay, thanks for the help. I just hate I have to install a freaking 5.5 GB application, for something I'm not gonna use. Is this really necessary? I have the command line tools installed? I'm compiling stuff without problem. Then why do I need Xcode??

**Comment by ilovezfs** [comment]
Because it uses
```
./src/Makefile:	xcodebuild -project MacVim/MacVim.xcodeproj $(XCODEFLAGS)
```
which is only available in Xcode.app

**Comment by mcourteaux** [comment]
Then wouldn't it make sense to add a bottle for the --with-lua flag? And make sure the --with-override-system-vim doesn't require xcode, as it's just some file symlinking?

**Comment by MikeMcQuaid** [comment]
@mcourteaux We cannot make bottles for options (this is why they generally suck). 

> Is this really necessary?

No hard feelings here at all but: Homebrew is designed so the answer to that question is always "yes". We don't like adding extra dependencies for users unless we have to either because they are required (in this case) or because they are required to provide a consistent, high-quality experience to all users that we're able to adequately support (in other cases). I hope that explains things a bit ❤️
