### ISSUE TITLE
Upgrade global error :SHA256 mismatch

### ISSUE THREAD

**Issue by Gilbert-Wong** [Homebrew/homebrew-core#23925]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap) and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] ~~Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   
   Upgrade global from 6.6.1 to 6.6.2

- What happened (include command output)
   ```bash
   Error: SHA256 mismatch
   Expected: ca1dc15e9f320983e4d53ccb947ce58729952728273fdf415ab309ea2c0cd7fa
   Actual: 43c64711301c2caf40dc56d7b91dd03d2b882a31fa31812bf20de0c8fb2e717f
   Archive: /Users/gilbertwong/Library/Caches/Homebrew/global-6.6.2.tar.gz
   To retry an incomplete download, remove the file above.
    ```

- What you expected to happen
   
    Upgrade global successfully.    

- Step-by-step reproduction instructions (by running `brew install` commands)
  
    ```brew update & brew upgrade ```

**Comment by ilovezfs** [comment]
@jschleus it looks like this bit fossies too :(

**Comment by jschleus** [comment]
Thanks for the information. There were two different tarballs under the same name distributed (the first contains a newest member timestamp of 2018-02-09 01:47, the second of 2018-02-09 21:32) and at least the member files INSTALL, reconf.sh, doc/stamp-vti, doc/texinfo.tex and doc/version.texi are changed. Now on Fossies the second (later, current) version is available.

**Comment by Gilbert-Wong** [comment]
Thanks for your reply . I removed global and reinstalled it again.Now  It works and upgrade to 6.6.2 successfully.
