### ISSUE TITLE
Can't install/link python: /usr/local/Frameworks missing

### ISSUE THREAD

**Issue by thepatrick** [Homebrew/homebrew-core#23932]
# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific Homebrew/homebrew-core formula (not cask or tap)
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` - https://gist.github.com/979aaa0aa7348d6ae67262d65d708dc9

To help us debug your issue please explain:
- What you were trying to do (and why): `brew install python` (or `brew link python`)
- What happened (include command output): it assumes /usr/local/Frameworks exists, which is clearly not a safe assumption.
- What you expected to happen: python to install!
- Step-by-step reproduction instructions (by running `brew install` commands): `brew install python`.

**Comment by thepatrick** [comment]
Yes, I'm aware I can `sudo mkdir /usr/local/Frameworks; sudo chown (whoami):wheel`, but either:

a) the formula should actually tell the user to do this
b) `brew doctor` should tell the user to do this

**Comment by ilovezfs** [comment]
This is something that affects some people upgrading to 10.13. The `install` script handles this properly already. I'm glad you figured out what to do.
