### ISSUE TITLE
Not opening sublime text 3 using rebase -i in Git

### ISSUE THREAD

**Issue by eno812** [Homebrew/homebrew-core#2396]
# Please follow the general troubleshooting steps first:

- [Y ] Ran `brew update` and retried your prior step?
- [Y ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [N/A ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

After running - git rebase -i master I get the following error:

/usr/local/Cellar/git/2.9.0/libexec/git-core/git-rebase--interactive: line 255: subl: command not found
Could not execute editor

This used to open Sublime but not now.

I do have the subl command setup and working.

**Comment by dunn** [comment]
What does `which subl` say?  Sounds like the command-line launcher is broken.

**Comment by eno812** [comment]
Thanks for getting back to me Alex, details below:

subl () {
"$_sublime_path" $*
}

**Comment by MikeMcQuaid** [comment]
Try an alias instead of a function (or add Sublime Text's directory to your PATH).

**Comment by eno812** [comment]
Hi Mike,

Thanks for getting back to me.

I’m fairly new to Git so not sure how to add Sublime’s directory to my path
or which path or why? It used to work but I haven’t rebased for a while and
now it won’t.

As far as the alias are you saying to use a Git alias instead of the
straight function?

Cheers,
Ian

**Comment by UniqMartin** [comment]
If you're using a shell function to invoke Sublime Text from the command line, then that shell function is invisible to the Git process that tries to execute an editor for editing the `git rebase` sheet. You either have to make it available as an executable in your search PATH (`which brew` returns a path), e.g. by placing a symlink to the `subl` executable in `/usr/local/bin` or by specifying the full path to the `subl` binary in your Git config, e.g.:

```
git config --global core.editor '"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" -w'
```

(Tested locally, though I'd personally prefer the first method, as the path with the space is a bit nasty.)

**Comment by eno812** [comment]
Thanks for your reply Martin,

I believe I had the first option setup when I first installed Sublime, but
that was ages ago.

I've checked the path of Sublime and this is what was returned:

/Applications/Sublime\ Text.app

 Is this a normal path as it does not seem to be a normal path. It is
Sublime Text 3 dev channel.

Cheers,
Ian

**Comment by UniqMartin** [comment]
> I've checked the path of Sublime and this is what was returned:
>
> /Applications/Sublime\ Text.app
>
> Is this a normal path as it does not seem to be a normal path. It is Sublime Text 3 dev channel.

I'm using the same version. This is the path of the application bundle that you select in your graphical user interface if you want to start Sublime Text. However, for invoking Sublime Text from the command line (or for opening tabs in an already running instance) you want to use the `subl` binary that is contained in this application bundle, that you can invoke without having it in your search path with either of the following two lines:

```
"/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl
```

(That's really just two different ways to tell the shell that the space is actually a part of the path.)

Closing as this is basically resolved and even if it wasn't, it's not actually a Homebrew issue. Thanks!

**Comment by eno812** [comment]
I'm sure you know a lot more about this than I do but what concerns me is
my subl command works on everything but Git. So it can't be a Sublime
problem can it?

**Comment by UniqMartin** [comment]
> but what concerns me is my subl command works on everything but Git.

What does “everything” mean? Can you be more specific and explain how you made every one of those pieces of software work with Sublime Text? What might also be helpful is if you provided the output of the following commands:

```
echo "[${_sublime_path}]"
which -a subl
```
