### ISSUE TITLE
GHC formula doesn't install man pages

### ISSUE THREAD

**Issue by habibalamin** [Homebrew/homebrew-core#2397]
I'm fairly sure that it used to, because I remember having the man page for GHC a while back. When I started using `stack`, I uninstalled my global GHC installation. After I tried to bring up the GHC man page and it failed, I thought to reinstall GHC from Homebrew, only to find that they aren't included (anymore).

**Comment by tdsmith** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? [This document](https://git.io/vo2xc) should give you a head start and we'd be more than happy to walk you through it if you have any questions. It looks like `make install` isn't enough to install them.

**Comment by habibalamin** [comment]
Yeah, I've already got a working formula which installs the man page, there's only one problem: It requires a build with Sphinx installed, which the bottle does not have. If you install with documentation, it requires a build from source, which can take a while. I think the Homebrew maintainers should rebuild the bottles with Sphinx installed (unless I can do that?).

**Comment by DomT4** [comment]
>  I think the Homebrew maintainers should rebuild the bottles with Sphinx installed (unless I can do that?).

Our CI will handle this if you file a PR. I'd recommend making the dependency:
```ruby
depends_on "sphinx-doc" => [:build, :recommended]
```

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/2fbabd37d82883901fe8a7e463310812b41c32fc.

**Comment by habibalamin** [comment]
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/2fbabd37d82883901fe8a7e463310812b41c32fc/Formula/ghc.rb` does not install the man page, but `brew install --build-from-source --debug --keep-tmp --verbose https://raw.githubusercontent.com/Homebrew/homebrew-core/2fbabd37d82883901fe8a7e463310812b41c32fc/Formula/ghc.rb` does.

**Comment by habibalamin** [comment]
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/2fbabd37d82883901fe8a7e463310812b41c32fc/Formula/ghc.rb` does not install the man page, but `brew install --build-from-source --debug --keep-tmp --verbose https://raw.githubusercontent.com/Homebrew/homebrew-core/2fbabd37d82883901fe8a7e463310812b41c32fc/Formula/ghc.rb` does. Does the right bottle only get installed once this is fully merged in (`brew update` doesn't update `gcc`)?

**Comment by DomT4** [comment]
Not sure why you're trying to do that dance? Simply `brew update && brew reinstall ghc`?

**Comment by habibalamin** [comment]
I did a `brew update` and searched for `ghc` in the output and didn't find it.

**Comment by DomT4** [comment]
Yeah, it won't have been listed because the version/formula revision wasn't updated. We don't flag every change in `brew update` any more, only substantial ones. It will have still been updated though.
