### ISSUE TITLE
How to install wget with debug support?

### ISSUE THREAD

**Issue by pengyu** [Homebrew/homebrew-core#23978]
By default, wget does not support -d. How to install wget with debug support? Thanks.

```
$ wget -d -o/tmp/log -qO- http://httpbin.org/get
Debugging support not compiled in. Ignoring --debug flag.
```

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by pengyu** [comment]
I don't know what you are referring to. Could you show me an example revised message which can satisfy your requirement?
