### ISSUE TITLE
GNU Global (from source) has SHA256 mismatch 

### ISSUE THREAD

**Issue by drdavis** [Homebrew/homebrew-core#23980]
When upgrading GNU Global to 6.6.2 I'm getting an SHA256 mismatch

Unfortunately I'm not security savvy enough to know if it's kosher to just update the formula to reflect the expected SHA256 word.

```
$ brew update
Already up-to-date.
$ brew upgrade global
==> Upgrading 1 outdated package, with result:
global 6.6.2
==> Upgrading global --with-ctags
==> Downloading https://ftp.gnu.org/gnu/global/global-6.6.2.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ca1dc15e9f320983e4d53ccb947ce58729952728273fdf415ab309ea2c0cd7fa
Actual: 43c64711301c2caf40dc56d7b91dd03d2b882a31fa31812bf20de0c8fb2e717f
Archive: /Users/ddavis/Library/Caches/Homebrew/global-6.6.2.tar.gz
To retry an incomplete download, remove the file above.
```

**Comment by J3RN** [comment]
What's extra bizarre is that if you leave off the `--with-ctags` option, it installs fine.

```
$ brew install global
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/global-6.6.2.high_sierra.bottle.tar.gz
Already downloaded: /Users/j3rn/Library/Caches/Homebrew/global-6.6.2.high_sierra.bottle.tar.gz
==> Pouring global-6.6.2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/global/6.6.2: 109 files, 1.9MB
```

**Comment by DomT4** [comment]
> Is the SHA sum only checked if you're installing with ctags?

No. The checksum is fine above because you're downloading a different thing.

Homebrew builds bottles _(binary packages)_ for the default build, which in this case is without `ctags`. When you ask Homebrew to build `--with-ctags` it doesn't have a binary package for that so you end up building from source, which necessitates fetching the upstream tarball with the checksum issue.

**Comment by vvv** [comment]
I “fixed” this issue by reinstalling `global`:
```
brew uninstall global
brew install global
```

**Comment by DomT4** [comment]
As long as your `HOMEBREW_PREFIX` is `/usr/local` you'll be fetching different things when you do `brew install global` Vs `brew install global --with-any-option-flag`.

```
~> brew fetch global -s

==> Downloading https://ftp.gnu.org/gnu/global/global-6.6.2.tar.gz
SHA256: 43c64711301c2caf40dc56d7b91dd03d2b882a31fa31812bf20de0c8fb2e717f
==> Verifying global-6.6.2.tar.gz checksum
Warning: Formula reports different SHA256: ca1dc15e9f320983e4d53ccb947ce58729952728273fdf415ab309ea2c0cd7fa
```

```
~> brew fetch global

==> Downloading https://homebrew.bintray.com/bottles/global-6.6.2.high_sierra.bottle.tar.gz
Downloaded to: /usr/local/var/homebrewcache/global-6.6.2.high_sierra.bottle.tar.gz
SHA256: c262bfe9dd7728df2d0ae22da2e646be5a12c666450507fabec6d0f70367b82c
==> Verifying global-6.6.2.high_sierra.bottle.tar.gz checksum
```

**Comment by DomT4** [comment]
@ilovezfs Looks like a retag 🙃. You opened https://github.com/Homebrew/homebrew-core/pull/23861 on the 9th Feb 05:44 UTC, upstream gets a [bug report](https://lists.gnu.org/archive/html/bug-global/2018-02/msg00001.html) about the `INSTALL` file being wrong and says they'll correct it. Upstream then [push this tweak](https://cvs.savannah.gnu.org/viewvc/global/global/reconf.sh?sortby=date&r1=1.47&r2=1.48&pathrev=VERSION-6_6_2) on Feb 9 20:24:51 UTC, and the archive date/time shifts to Feb 9 20:32:59 UTC after that point:

```
~> file /usr/local/var/homebrewcache/global-6.6.2.tar.gz
/usr/local/var/homebrewcache/global-6.6.2.tar.gz: gzip compressed data, last modified: Fri Feb  9 20:32:59 2018, max compression, from Unix
```

**Comment by ilovezfs** [comment]
I think this may be the first time I've seen this with a GNU tarball.

**Comment by ilovezfs** [comment]
This is now fixed.

**Comment by DomT4** [comment]
> I think this may be the first time I've seen this with a GNU tarball.

Aye, I can't recall many prior "silent" retags on the GNU side. Thanks for filing the PR; was planning to do so this morning but got sidetracked by life.
