### ISSUE TITLE
Nasm

### ISSUE THREAD

**Issue by aak2003** [Homebrew/homebrew-core#23997]
The page is not loading and hence I am unable to download this dependency

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by ilovezfs** [comment]
This should be fixed now. I mirrored the tarball to Bintray. Next time fill out the template please.
