### ISSUE TITLE
freerdp: Issues with builds built with --HEAD

### ISSUE THREAD

**Issue by ed-velez** [Homebrew/homebrew-core#24047]
Freerdp has implemented new features that are half baked right now for OS X. This currently causes issues with freerdp built from --HEAD to fail.

See the issue I submitted upstream: https://github.com/FreeRDP/FreeRDP/issues/4418

I am happy to submit a pull request with the following. Build's up to this commit should work properly: 

```
  head do
    url "https://github.com/FreeRDP/FreeRDP.git", :revision => "2a6c9e1b8742306097c9940ba3f7d3b18efbcfb7"
    depends_on :xcode => :build
  end
```

**Comment by apjanke** [comment]
I don't think we do revision pinning on `HEAD`. If `HEAD` is broken, it's broken, and that's on upstream. We'll leave it be broken, or remove `head` entirely.

If there's a viable under-development revision that's useful for testing, they could cut a prerelease and we could make that available under `devel`.

**Comment by ed-velez** [comment]
I figured as much. In any event there is some documentation of a workaround should someone run into this.

**Comment by dingus9** [comment]
--devel didn't compile and --head currently is still broken... the only workaround I found that was to swap out the head do section for one that checked out "2a6c9e1b8742306097c9940ba3f7d3b18efbcfb7" this works fine... however I can't ask my teamates to do this everytime.
