### ISSUE TITLE
Error: no implicit conversion of String into Array

### ISSUE THREAD

**Issue by fueno** [Homebrew/homebrew-core#24042]
$ brew install php71 --with-httpd24
==> Installing php71 from homebrew/php
Warning: homebrew/php/php71: --with-httpd24 was deprecated; using --with-httpd instead!
==> Downloading https://php.net/get/php-7.1.14.tar.bz2/from/this/mirror
Already downloaded: /Users/user_name/Library/Caches/Homebrew/php71-7.1.14
==> ./configure --prefix=/usr/local/Cellar/php71/7.1.14_25 --localstatedir=/usr/
==> make
==> make install
Error: no implicit conversion of String into Array
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:614:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:18:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:573:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:599:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:343:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
