### ISSUE TITLE
pulseaudio: failed to build --with-x11

### ISSUE THREAD

**Issue by tomyun** [Homebrew/homebrew-core#2408]
### Bug reports:

`pulseaudio` failed to build with x11 option enabled:
https://gist.github.com/tomyun/fa8fb2211c1ca2d0e06aa999c725934d

Not sure if it's related with the recent update (#2296).

**Comment by rwhogg** [comment]
From https://gist.github.com/tomyun/fa8fb2211c1ca2d0e06aa999c725934d#file-02-make-L6-L14

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-recursive
Making install in src
../build-aux/install-sh -c -d daemon modules
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
make[3]: *** No rule to make target `daemon/pulseaudio.desktop', needed by `all-am'.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2
```

I think this might be an upstream bug: https://bugs.freedesktop.org/show_bug.cgi?id=54658

I have the same problem on Linux.

**Comment by MikeMcQuaid** [comment]
Closing out upstream issues.
