### ISSUE TITLE
httpd: cannot load mod_proxy_fcgi.so

### ISSUE THREAD

**Issue by ideepblue** [Homebrew/homebrew-core#24114]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/aa73d332485a7e9422928f3ea839db07
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I faced a problem when I configure the httpd.conf.
I try to let php-fpm work with httpd. So I followed the instruction [Using FPM.md](https://github.com/Homebrew/homebrew-php/blob/master/Contributions/Using%20FPM.md).
After I installed the httpd, I uncommented the lines as shown in step 4 of `Quick summary`.
Then I tested the httpd configuration whether if it is fine by executing `apachectl configtest`, I got the error as follows:
```
httpd: Syntax error on line 133 of /usr/local/etc/httpd/httpd.conf: Cannot load lib/httpd/modules/mod_proxy_fcgi.so into server: dlopen(/usr/local/opt/httpd/lib/httpd/modules/mod_proxy_fcgi.so, 10): Symbol not found: _proxy_module\n
Referenced from: /usr/local/opt/httpd/lib/httpd/modules/mod_proxy_fcgi.so\n  Expected in: flat namespace\n
in /usr/local/opt/httpd/lib/httpd/modules/mod_proxy_fcgi.so`
```
I checked the path and confirmed the mod_proxy_fcig.so exists. Even I reinstall or reinstall from source, this issue presists. So I unlinked the httpd and back to use the macOS httpd again.

I also can confirm my Xcode is updated to the newest.

Is there something I did wrong? or this is a bug?

**Comment by fxcoudert** [comment]
- Make sure there is there a line to load proxy_module in httpd.conf: `LoadModule proxy_module modules/mod_proxy.so`
- The line should be above the `mod_proxy_fcgi.so`
- Make sure that that file exist and has reasonable permissions.

**Comment by ideepblue** [comment]
@fxcoudert Thank you very much. That's my mistake. I would like to close this issue.
