### ISSUE TITLE
Zabbix (From bottle) has SHA256 mismatch

### ISSUE THREAD

**Issue by pg07gordon** [Homebrew/homebrew-core#24140]
When Installing Zabbix 3.4.6 I’m getting an SHA256 mismatch

Unfortunately, I'm not security savvy enough to know if it's kosher to just install the formula to reflect the expected SHA256 hash.

Console output from brew update, brew doctor, brew gist-logs, brew config (because gist-logs didn’t work):

```
bash-3.2$ brew update
Already up-to-date.
bash-3.2$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
bash-3.2$ brew gist-logs zabbix
Error: No logs.
bash-3.2$ brew gist-logs --without-server-proxy zabbix
Error: No logs.
bash-3.2$ brew config
HOMEBREW_VERSION: 1.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 021fe22e3c982b08346422d1e7897e929a709380
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3253ad21a2823e2ec88df82eb72cea82ffd4e350
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Library/Caches/Homebrew
HOMEBREW_LOGS: /Library/Logs/Homebrew
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Library/Frameworks/Python.framework/Versions/2.7/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_162, 1.7.0_80
macOS: 10.12.6-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: N/A
```

- **What you were trying to do (and why):** I want to install Zabbix agent on OSX 12.6, so i can use zabbix agent
- **What happened (include command output):** It didn't install.

``bash-3.2$ brew install --without-server-proxy zabbix
==> Downloading https://downloads.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/3.4.6/zabbix-3.4.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/zabbix-3.4.6.tar.gz
Error: SHA256 mismatch
Expected: 2c261f967fece8f0f930bc07876e37debdf7a903f65a3a222aed5ba5fc724d6a
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Library/Caches/Homebrew/zabbix-3.4.6.tar.gz
To retry an incomplete download, remove the file above.``

- **What you expected to happen:** Zabbix agent to be installed

- **Step-by-step reproduction instructions (by running `brew install` commands):**

``brew` install --without-server-proxy zabbix
==> Downloading https://downloads.sourceforge.net/project/zabbix/ZABBIX%20Latest%20Stable/3.4.6/zabbix-3.4.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/zabbix-3.4.6.tar.gz
Error: SHA256 mismatch
Expected: 2c261f967fece8f0f930bc07876e37debdf7a903f65a3a222aed5ba5fc724d6a
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Library/Caches/Homebrew/zabbix-3.4.6.tar.gz
To retry an incomplete download, remove the file above.``

I really appreciate any help on this matter

**Comment by fxcoudert** [comment]
Could be a network issue. Have you tried brew's advice, which is to remove `/Library/Caches/Homebrew/zabbix-3.4.6.tar.gz` and try again?

**Comment by ilovezfs** [comment]
The current checksum in the formula seems to be correct, so I'm closing this issue, but please feel free to keep talking with us here until it's working for you.

**Comment by pg07gordon** [comment]
I did try deleting /Library/Caches/Homebrew/zabbix-3.4.6.tar.gz, with the same result, however using curl to manually download the file revealed that something on the network was cutting the download short.

Thank you for the support!
