### ISSUE TITLE
'pip2' does not work after 'brew install python' 

### ISSUE THREAD

**Issue by tomsem** [Homebrew/homebrew-core#24189]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x(*)] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/0b6d3572fd3c5d34eb7ac418b4b090b1

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

(*) did not delete .h/.a as they are part of my dev environment and doing so might futz something up. Could not link 'xz':
`brew link --overwrite xz          
Linking /usr/local/Cellar/xz/5.2.3... 
Error: Could not symlink include/lzma/base.h
/usr/local/include/lzma is not writable.`

To help us debug your issue please explain:
- What you were trying to do (and why)
Run pip2 after (apparently) successful install of python

- What happened (include command output)
`Traceback (most recent call last):
  File "/usr/local/bin/pip2", line 11, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip2')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2750, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'pip2') not found`

- What you expected to happen
pip CLI help displays

- Step-by-step reproduction instructions (by running `brew install` commands)
1. Installed brew for first time on this machine
2. 'brew install python'
3. try to run 'pip2' 
4. get above ImportError

There is at least one other person with this problem:
https://stackoverflow.com/questions/48811086/pip2-causes-importerror-entry-point-console-scripts-pip2-not-found/48819004#4881900 

'brew install python3' does not have this issue.

My workaround is to create virtualenv with PyCharm. When that's active, pip/pip2/pip2.7 works as expected.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
Hum… cannot reproduce this here, with a freshly installed python. Can you try with a clean install? It is probably some bad interaction with other installed software.

**Comment by chermen** [comment]
Same story here - pip2 stopped working. I don't know when exactly, probably after the last update of python 2.7. I also have python 3 installed on my machine and pip3 works just fine.

**Comment by fxcoudert** [comment]
Can either of you reproduce it on a clean Homebrew install?

**Comment by tomsem** [comment]
My brew install was clean. Python2 was first thing I installed with brew.

**Comment by fxcoudert** [comment]
> (*) did not delete .h/.a as they are part of my dev environment and doing so might futz something up. Could not link 'xz':
brew link --overwrite xz Linking /usr/local/Cellar/xz/5.2.3... Error: Could not symlink include/lzma/base.h /usr/local/include/lzma is not writable.

Not really a clean install, though :)
I can't reproduce it here, so I'm thinking it has to do with this issue.

**Comment by Kipsora** [comment]
It seems that currently homebrew has set the default value python3 for python. See [https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb](python.rb) for more details. Under this circumstance, `brew install python` will install python3 instead. 
But I don't know the reason for this.

**Comment by ilovezfs** [comment]
@Kipsora `brew install python@2` if you need that.
