### ISSUE TITLE
brew install Berkeley-db@5.3

### ISSUE THREAD

**Issue by agsstaff** [Homebrew/homebrew-core#24184]
brew install Berkeley-db@5.3 
Error: No available formula with the name "berkeley@5.3"

So manual install of berkeley-db@5.3 from bottle 
When I compile my app the @@HOMEBREW_PREFIX@@ is listed with otool -L 

 /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        @@HOMEBREW_PREFIX@@/opt/berkeley-db@5.3/lib/libdb_cxx-5.3.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/opt/boost@1.60/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)

How to set the /usr/local path instead of @@HOMEBREW_PREFIX@@ ?

**Comment by apjanke** [comment]
It doesn't look like there's currently a `berkeley-db@5.3` formula in homebrew-core. Where did you get that bottle from?

It looks like the path rewriting stage of building that bottle didn't work.

**Comment by agsstaff** [comment]
Thanks for the help Andrew
I'm new to Homebrew and more of a Linux dev using apt-get etc..

I found the bottle here
https://zeroc.com/download/homebrew/bottles/berkeley-db@5.3-5.3.28.NC.brew.high_sierra.bottle.tar.gz

I was able to install a formula and resolve this issue today.
Another Homebrew dev gave me access to his berkeley-db@53.rb that worked.

Thanks again
Please close the ticket

Doug
