### ISSUE TITLE
Building xapian with --with-python option fails if PYTHONDONTWRITEBYTECODE is set

### ISSUE THREAD

**Issue by martyanov** [Homebrew/homebrew-core#2422]
Build log:
```
brew install xapian --with-python
==> Downloading http://oligarchy.co.uk/xapian/1.2.23/xapian-core-1.2.23.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/xapian/1.2.23
==> make install
==> Downloading http://oligarchy.co.uk/xapian/1.2.23/xapian-bindings-1.2.23.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/xapian/1.2.23 XAPIAN_CONFIG=/usr/local/Cellar/xapian/1.2.23/bin/xapian-config --without-csharp --wi
==> make install
Last 15 lines from /Users/duke/Library/Logs/Homebrew/xapian/04.make:
 /usr/bin/install -c -m 644 docs/examples/simpleindex.py docs/examples/simpleexpand.py docs/examples/simplematchdecider.py docs/examples/simplesearch.py '/usr/local/Cellar/xapian/1.2.23/share/doc/xapian-bindings/python/examples'
 .././install-sh -c -d '/usr/local/Cellar/xapian/1.2.23/lib/python2.7/site-packages/xapian'
PYTHONPATH=".:$PYTHONPATH" /Users/duke/projects/sc-sso/.venv/bin/python -c "import xapian"
PYTHONPATH=".:$PYTHONPATH" /Users/duke/projects/sc-sso/.venv/bin/python -O -c "import xapian"
 /bin/sh ../libtool    --mode=install /usr/bin/install -c   _xapian.la '/usr/local/Cellar/xapian/1.2.23/lib/python2.7/site-packages/xapian'
libtool: install: /usr/bin/install -c .libs/_xapian.so /usr/local/Cellar/xapian/1.2.23/lib/python2.7/site-packages/xapian/_xapian.so
libtool: install: /usr/bin/install -c .libs/_xapian.lai /usr/local/Cellar/xapian/1.2.23/lib/python2.7/site-packages/xapian/_xapian.la
 .././install-sh -c -d '/usr/local/Cellar/xapian/1.2.23/lib/python2.7/site-packages/xapian'
 /usr/bin/install -c -m 644 xapian/__init__.py ./xapian/__init__.pyc ./xapian/__init__.pyo '/usr/local/Cellar/xapian/1.2.23/lib/python2.7/site-packages/xapian'
install: ./xapian/__init__.pyc: No such file or directory
make[3]: *** [install-pkgpylibDATA] Error 71
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install-am] Error 2
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1
```

I think that correct behavior is to check if `PYTHONDONTWRITEBYTECODE` is present, unset it and restore it's state after completion.

**Comment by DomT4** [comment]
Maybe `PYTHONDONTWRITEBYTECODE` is something we want to unset unconditionally in `superenv` for `brew install xyz`. This smells like a potential upstream bug though. @tdsmith is the guru.

**Comment by tdsmith** [comment]
I guess this is an unsupported configuration for Xapian. If you'd like to submit a pull request to call `ENV.delete "PYTHONDONTWRITEBYTECODE"` at the top of the `install` method in xapian.rb that seems fine to me. If this is more widespread we can do something more drastic; this doesn't affect setuptools stuff.

**Comment by martyanov** [comment]
@DomT4 It seems that unconditionally unsetting the variable is not a good solution, because it may affect users who explicitly set it, so it would be a surprising behavior. In general, manipulations with `PYTHONDONTWRITEBYTECODE` should not affect other Python packages. Unfortunately, I don't know anything about brew internals.

**Comment by DomT4** [comment]
@martyanov Anything unset by either Homebrew's `superenv` mechanism or in the formulae themselves is only `unset` for that operation rather than globally.

Things on the user side would go on as expected, unless they explicitly expected Homebrew to support random global environment variables that projects can pick up on _(Which we try not to, for consistency's sake)_.

**Comment by martyanov** [comment]
@DomT4 Thanks for the explanations. Didn't know about that.

**Comment by martyanov** [comment]
Oh, great thanks! 👍
