### ISSUE TITLE
HOMEBREW_PREFIX isn't set.

### ISSUE THREAD

**Issue by bumblebritches57** [Homebrew/homebrew-core#2430]
I cloned Homebrew to /usr/local/Packages/Homebrew, and now HOMEBREW_PREFIX is completely blank.

I've been googling to find how to set it, and even searching my filesystem for that string to manually update it, but nothing was found.

How do I fix this?

**Comment by ilovezfs** [comment]
What problem are you actually having? The prefix is determined automatically from the location of the bin/brew file …

**Comment by bumblebritches57** [comment]
When I run `brew install autoconf` (even with sudo) it says: Cannot write to  

which is a problem because it's not setting the HOMEBREW_PREFIX for whatever reason.

**Comment by ilovezfs** [comment]
First off, as a side note, brew isn't designed to work with sudo at all. You should never do `sudo brew ...`.

What's the output of `which -a brew`

**Comment by bumblebritches57** [comment]
/bin/brew, which I manually linked to /usr/local/Packages/Homebrew/brew/bin/brew

**Comment by tdsmith** [comment]
Oh! Don't do that. Homebrew tries to write to paths with respect to the location of the `brew` symlink (i.e. `/bin/../lib`, `/bin/../share`, .... You should add `/usr/local/Packages/Homebrew/bin` to PATH instead.

**Comment by bumblebritches57** [comment]
Awesome! thanks for the help dude.

**Comment by xu-cheng** [comment]
@UniqMartin this issue seem to indicate a bug in `bin/brew`, where if the brew file is `/bin/brew`, `HOMEBREW_PREFIX` will be set to an empty string. As result, https://github.com/Homebrew/brew/blob/master/Library/brew.sh#L56 fails to stop user run any brew command.

**Comment by UniqMartin** [comment]
Symlinking `bin/brew` to `/bin/brew` or installing Homebrew to `/` is a really silly idea and hopefully few people have tried this, which would explain why this issue remained unnoticed for many months. Fixed the bug in Homebrew/brew@3c5f007bfa1a469ef3e1a048ee163f3eaa73cb71 so the [error message in `brew.sh`](https://github.com/Homebrew/brew/blob/3c5f007bfa1a469ef3e1a048ee163f3eaa73cb71/Library/brew.sh#L56-L60) gets printed.
