### ISSUE TITLE
Unable to install geckodriver on Mac OS High Sierra 10.13.3

### ISSUE THREAD

**Issue by SalmonMode** [Homebrew/homebrew-core#24404]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/anonymous/a38e0f38417ec56b5f8fd1d7f501e103

- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
run `brew install geckodriver` so I could use it with selenium
- What happened (include command output)
I ran `brew install geckodriver`, and it failed to install.
- What you expected to happen
I expected geckodriver to be installed
- Step-by-step reproduction instructions (by running `brew install` commands)
run `brew install geckodriver` on Mac OS High Sierra 10.13.3 on a MacBook Pro (15-inch, 2017)

Here's my other installed formulae if it helps:

```
brew ls
cmake		gmp		libssh2		node		python		sqlite
gcc		icu4c		makedepend	openssl		python3		xz
gdbm		isl		mercurial	pkg-config	readline	zsh
git		libmpc		mpfr		postgresql@9.5	rust		zsh-completions
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
I can reproduce locally:

```
   Compiling slog v1.5.2
error[E0277]: the trait bound `*mut core::ops::Fn() + 'static: core::marker::Sync` is not satisfied in `core::fmt::Arguments<'static>`
   --> .brew_home/.cargo/registry/src/github.com-1ecc6299db9ec823/slog-1.5.2/src/ser.rs:228:6
    |
228 | impl SyncSerialize for fmt::Arguments<'static> {}
    |      ^^^^^^^^^^^^^ `*mut core::ops::Fn() + 'static` cannot be shared between threads safely
    |
    = help: within `core::fmt::Arguments<'static>`, the trait `core::marker::Sync` is not implemented for `*mut core::ops::Fn() + 'static`
    = note: required because it appears within the type `core::marker::PhantomData<*mut core::ops::Fn() + 'static>`
    = note: required because it appears within the type `core::fmt::Void`
    = note: required because it appears within the type `&'static core::fmt::Void`
    = note: required because it appears within the type `core::fmt::ArgumentV1<'static>`
    = note: required because it appears within the type `[core::fmt::ArgumentV1<'static>]`
    = note: required because it appears within the type `&'static [core::fmt::ArgumentV1<'static>]`
    = note: required because it appears within the type `core::fmt::Arguments<'static>`

error: aborting due to previous error

error: Could not compile `slog`.
```

**Comment by fxcoudert** [comment]
I reported it upstream: https://github.com/mozilla/geckodriver/issues/1185
Not sure what we can do, closing this for now.

**Comment by andreastt** [comment]
Author of geckodriver here. See https://bugzilla.mozilla.org/show_bug.cgi?id=1436105. This was fixed by removing the slog dependency in https://bugzilla.mozilla.org/show_bug.cgi?id=1436830, so you should find it compiles as expected with rustc 1.24 against mozilla-central now.
