### ISSUE TITLE
Latest update fails to install, likely reproducible elsewhere

### ISSUE THREAD

**Issue by sstillwell** [Homebrew/homebrew-core#24561]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  https://gist.github.com/3da63e0775ac0f0aaa9c2cee9992fa72
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Had noted that 'brew update' flagged an update to gnu-cobool, but 'brew upgrade' had not apparently installed it, so I tried the following to make sure I got a fresh copy.

brew update
brew uninstall gnu-cobol
brew cleanup
brew install gnu-cobol

*failure occurs*

Downloading the bottle failed with 404, so it brewed from source.  One thing that I noticed was the actual failure message referenced a missing automake-1.15, when automake has also recently been updated to 1.16 and is installed.

Hope that helps...

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
gnu-cobol updated to 2.2, issue is fixed.
