### ISSUE TITLE
Pwgen curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [Homebrew/homebrew-core#24577]
✗ brew install pwgen -k

==> Auto-updated Homebrew!
Updated 1 tap (caskroom/versions).
No changes to formulae.

==> Downloading https://downloads.sourceforge.net/project/pwgen/pwgen/2.08/pwgen-2.08.tar.gz
##O=-#    #                                                                                                                                                             
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Failed to download resource "pwgen"
Download failed: https://downloads.sourceforge.net/project/pwgen/pwgen/2.08/pwgen-2.08.tar.gz

**Comment by fxcoudert** [comment]
Please fill out our [issue template](https://github.com/Homebrew/homebrew-core/issues/new) completely when opening the issue.
