### ISSUE TITLE
Warning: Calling 'depends_on :postgresql' is deprecated!

### ISSUE THREAD

**Issue by webguide1** [Homebrew/homebrew-core#24599]
I dont know what to report (or what I am reporting), but I got this message when running brew doctor after trying to install homebrew

Warning: Calling 'depends_on :mysql' is deprecated!
Use 'depends_on "mysql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb:30:in `<class:Qt>'
Please report this to the homebrew/core tap!

Warning: Calling 'depends_on :postgresql' is deprecated!
Use 'depends_on "postgresql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb:31:in `<class:Qt>'
Please report this to the homebrew/core tap!

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by webguide1** [comment]
Hmm, did I fill in the above correct?

**Comment by ilovezfs** [comment]
What's the output of `brew config` and `brew doctor`? You may be on a branch.

**Comment by webguide1** [comment]
**This is from `brew config`**
HOMEBREW_VERSION: 1.5.4-88-g650d6db
ORIGIN: https://github.com/Homebrew/brew
HEAD: 650d6dbaac625a758881a215a35d8d4a248de5bf
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 840d615ad715c7c32b3872ee47a73f0bbee7f274
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/webguide/.rbenv/shims/ruby => /Users/webguide/.rbenv/versions/2.4.1/bin/ruby
Java: 1.6.0_65-b14-468
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A

**This is from `brew doctor`** 

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/android-ifaddrs.h
  /usr/local/include/ares.h
  /usr/local/include/ares_build.h
  /usr/local/include/ares_rules.h
  /usr/local/include/ares_version.h
  /usr/local/include/libplatform/libplatform.h
  /usr/local/include/libplatform/v8-tracing.h
  /usr/local/include/nameser.h
  /usr/local/include/node.h
  /usr/local/include/node_buffer.h
  /usr/local/include/node_object_wrap.h
  /usr/local/include/node_version.h
  /usr/local/include/openssl/aes.h
  /usr/local/include/openssl/archs/BSD-x86/opensslconf.h
  /usr/local/include/openssl/archs/BSD-x86_64/opensslconf.h
  /usr/local/include/openssl/archs/VC-WIN32/opensslconf.h
  /usr/local/include/openssl/archs/VC-WIN64A/opensslconf.h
  /usr/local/include/openssl/archs/aix-gcc/opensslconf.h
  /usr/local/include/openssl/archs/aix64-gcc/opensslconf.h
  /usr/local/include/openssl/archs/darwin-i386-cc/opensslconf.h
  /usr/local/include/openssl/archs/darwin64-x86_64-cc/opensslconf.h
  /usr/local/include/openssl/archs/linux-aarch64/opensslconf.h
  /usr/local/include/openssl/archs/linux-armv4/opensslconf.h
  /usr/local/include/openssl/archs/linux-elf/opensslconf.h
  /usr/local/include/openssl/archs/linux-ppc/opensslconf.h
  /usr/local/include/openssl/archs/linux-ppc64/opensslconf.h
  /usr/local/include/openssl/archs/linux-x32/opensslconf.h
  /usr/local/include/openssl/archs/linux-x86_64/opensslconf.h
  /usr/local/include/openssl/archs/linux32-s390x/opensslconf.h
  /usr/local/include/openssl/archs/linux64-s390x/opensslconf.h
  /usr/local/include/openssl/archs/solaris-x86-gcc/opensslconf.h
  /usr/local/include/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
  /usr/local/include/openssl/asn1.h
  /usr/local/include/openssl/asn1_mac.h
  /usr/local/include/openssl/asn1t.h
  /usr/local/include/openssl/bio.h
  /usr/local/include/openssl/blowfish.h
  /usr/local/include/openssl/bn.h
  /usr/local/include/openssl/buffer.h
  /usr/local/include/openssl/camellia.h
  /usr/local/include/openssl/cast.h
  /usr/local/include/openssl/cmac.h
  /usr/local/include/openssl/cms.h
  /usr/local/include/openssl/comp.h
  /usr/local/include/openssl/conf.h
  /usr/local/include/openssl/conf_api.h
  /usr/local/include/openssl/crypto.h
  /usr/local/include/openssl/des.h
  /usr/local/include/openssl/des_old.h
  /usr/local/include/openssl/dh.h
  /usr/local/include/openssl/dsa.h
  /usr/local/include/openssl/dso.h
  /usr/local/include/openssl/dtls1.h
  /usr/local/include/openssl/e_os2.h
  /usr/local/include/openssl/ebcdic.h
  /usr/local/include/openssl/ec.h
  /usr/local/include/openssl/ecdh.h
  /usr/local/include/openssl/ecdsa.h
  /usr/local/include/openssl/engine.h
  /usr/local/include/openssl/err.h
  /usr/local/include/openssl/evp.h
  /usr/local/include/openssl/hmac.h
  /usr/local/include/openssl/idea.h
  /usr/local/include/openssl/krb5_asn.h
  /usr/local/include/openssl/kssl.h
  /usr/local/include/openssl/lhash.h
  /usr/local/include/openssl/md4.h
  /usr/local/include/openssl/md5.h
  /usr/local/include/openssl/mdc2.h
  /usr/local/include/openssl/modes.h
  /usr/local/include/openssl/obj_mac.h
  /usr/local/include/openssl/objects.h
  /usr/local/include/openssl/ocsp.h
  /usr/local/include/openssl/opensslconf.h
  /usr/local/include/openssl/opensslv.h
  /usr/local/include/openssl/ossl_typ.h
  /usr/local/include/openssl/pem.h
  /usr/local/include/openssl/pem2.h
  /usr/local/include/openssl/pkcs12.h
  /usr/local/include/openssl/pkcs7.h
  /usr/local/include/openssl/pqueue.h
  /usr/local/include/openssl/rand.h
  /usr/local/include/openssl/rc2.h
  /usr/local/include/openssl/rc4.h
  /usr/local/include/openssl/ripemd.h
  /usr/local/include/openssl/rsa.h
  /usr/local/include/openssl/safestack.h
  /usr/local/include/openssl/seed.h
  /usr/local/include/openssl/sha.h
  /usr/local/include/openssl/srp.h
  /usr/local/include/openssl/srtp.h
  /usr/local/include/openssl/ssl.h
  /usr/local/include/openssl/ssl2.h
  /usr/local/include/openssl/ssl23.h
  /usr/local/include/openssl/ssl3.h
  /usr/local/include/openssl/stack.h
  /usr/local/include/openssl/symhacks.h
  /usr/local/include/openssl/tls1.h
  /usr/local/include/openssl/ts.h
  /usr/local/include/openssl/txt_db.h
  /usr/local/include/openssl/ui.h
  /usr/local/include/openssl/ui_compat.h
  /usr/local/include/openssl/whrlpool.h
  /usr/local/include/openssl/x509.h
  /usr/local/include/openssl/x509_vfy.h
  /usr/local/include/openssl/x509v3.h
  /usr/local/include/pthread-barrier.h
  /usr/local/include/stdint-msvc2008.h
  /usr/local/include/tree.h
  /usr/local/include/uv-aix.h
  /usr/local/include/uv-bsd.h
  /usr/local/include/uv-darwin.h
  /usr/local/include/uv-errno.h
  /usr/local/include/uv-linux.h
  /usr/local/include/uv-os390.h
  /usr/local/include/uv-sunos.h
  /usr/local/include/uv-threadpool.h
  /usr/local/include/uv-unix.h
  /usr/local/include/uv-version.h
  /usr/local/include/uv-win.h
  /usr/local/include/uv.h
  /usr/local/include/v8-debug.h
  /usr/local/include/v8-experimental.h
  /usr/local/include/v8-inspector-protocol.h
  /usr/local/include/v8-inspector.h
  /usr/local/include/v8-platform.h
  /usr/local/include/v8-profiler.h
  /usr/local/include/v8-testing.h
  /usr/local/include/v8-util.h
  /usr/local/include/v8-version.h
  /usr/local/include/v8.h
  /usr/local/include/v8config.h
  /usr/local/include/zconf.h
  /usr/local/include/zlib.h

**Comment by ilovezfs** [comment]
OK, so the problem looks solved? No message from doctor about `depends_on :mysql` this time.
