### ISSUE TITLE
subversion failed to build on 10.12.6

### ISSUE THREAD

**Issue by lbane** [Homebrew/homebrew-core#24608]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
I try to upgrade subversion to the latest version.

- What happened (include command output)
Building subversion 1.9.7_2 fails for me. 

Logs: https://gist.github.com/417130d1cff3ed643b6dfdc4dedb390d

Apparently the included serf 1.3.9 build uses python 2.7 syntax in a print statement, failing with python3 somehow used for the build.

There is a corresponding mail thread on the serf-dev mailing list: 
"SConstruct: calling print as a statement causes a SynatxError if SCons v. 3.0.0 is installed"

http://mail-archives.apache.org/mod_mbox/serf-dev/201710.mbox/%3cJIRA.13110349.1508343935000.28234.1508343960234@Atlassian.JIRA%3e

Output:
```
 brew upgrade
==> Upgrading 1 outdated package, with result:
subversion 1.9.7_2
==> Upgrading subversion --with-java --with-python
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.9.7.tar.bz2
Already downloaded: /Users/ralf/Library/Caches/Homebrew/subversion-1.9.7.tar.bz2
==> Patching
patching file configure
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
Already downloaded: /Users/ralf/Library/Caches/Homebrew/subversion--serf-1.3.9.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.9.7_2/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-Os 
Last 15 lines from /Users/ralf/Library/Logs/Homebrew/subversion/01.scons:
LINKFLAGS=-L/usr/local/opt/sqlite/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names
OPENSSL=/usr/local/opt/openssl
APR=/usr/local/opt/apr
APU=/usr/local/opt/apr-util

scons: Reading SConscript files ...
  File "/private/tmp/subversion--serf-20180227-38806-13rwo7z/serf-1.3.9/SConstruct", line 186

    print 'Warning: Used unknown variables:', ', '.join(unknown.keys())

                                           ^

SyntaxError: invalid syntax


READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen
A successful build.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew upgrade`
or
`brew install subversion --with-python --with-java`

**Comment by fxcoudert** [comment]
It seems likely that the Anaconda python scripts being in your PATH are screwing up the build. Remove anaconda from your PATH and try again.

**Comment by lbane** [comment]
Thank you, that helped completing the build.
