### ISSUE TITLE
Installing Opencv Issue: No available formula with the name "homebrew/core/libpng@1.2" (dependency of opencv)

### ISSUE THREAD

**Issue by 1Presidio** [Homebrew/homebrew-core#24613]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

``` brew config``` output
```
HOMEBREW_VERSION: 1.5.5-10-ge3be551
ORIGIN: https://github.com/Homebrew/brew
HEAD: e3be551244d53137752734a1ce2742810676f130
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: edaca39cfdeab153bef0ea60e2c18bda70ebcb6d
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

I am attempting to install opencv but keep getting the error 

```
Error: No available formula with the name "homebrew/core/libpng@1.2" (dependency of opencv)
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
```
The only command that I ran was ```brew install opencv``` I installed libpng earlier but no such package exists called ```libpng@1.2```

The output of ```brew doctor``` is 

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.
```

```brew gist-logs opencv``` has no output.s

**Comment by fxcoudert** [comment]
We will need this:

> if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue

The current version of the opencv formula, in Homebrew core, has no such dependency:

```
$ brew info opencv
opencv: stable 3.4.1 (bottled)
Open source computer vision library
https://opencv.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb
==> Dependencies
Build: cmake ✔, pkg-config ✔
Required: eigen ✔, ffmpeg ✘, jpeg ✔, libpng ✔, libtiff ✔, openexr ✘, python ✘, python3 ✘, numpy ✘, tbb ✘
```

**Comment by rakkesh** [comment]
@1Presidio to make sure you are on the `master` branch and there are no changes made to the formula locally, you can execute the following commands in order. (caveat: this would wipe out any other changes made on `master` branch)

```sh
git -C $(brew --repository homebrew/core) checkout master
git -C $(brew --repository homebrew/core) reset --hard HEAD
```

**Comment by 1Presidio** [comment]
@rakkesh Fixed thank you.
