### ISSUE TITLE
Brew link --force node@8 creates 4k+ symlinks

### ISSUE THREAD

**Issue by mourner** [Homebrew/homebrew-core#24610]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? 
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Running `brew link --force node@8` will create more than 4 thousand symlinks with irrelevant files such as various `*.js` files in `node_modules` folders. You can check this with `brew link --force --dry-run node@8`.

As opposed to `node@8` formula, both `node` and `node@6` will create only 7 symlinks, which is correct.

Not sure if it's a Brew problem or a formula problem.

`brew config`: <details>HOMEBREW_VERSION: 1.5.5-10-ge3be551
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e3be551244d53137752734a1ce2742810676f130
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: edaca39cfdeab153bef0ea60e2c18bda70ebcb6d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: N/A
X11: 2.7.9 => /opt/X11
~/projects/flatbush master* → </details>

`brew doctor` (note: there are still warnings but they're all unrelated): <details>Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/grib_api.h
  /usr/local/include/grib_api_f77.h
  /usr/local/include/grib_api_version.h
  /usr/local/include/grib_api_windef.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libgrib_api.la
  /usr/local/lib/libgrib_api_f77.la
  /usr/local/lib/libgrib_api_f90.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/grib_api.pc
  /usr/local/lib/pkgconfig/grib_api_f90.pc
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libgrib_api.a
  /usr/local/lib/libgrib_api_f77.a
  /usr/local/lib/libgrib_api_f90.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  ~/.config/yarn/global/node_modules/.bin/

Warning: Your XQuartz (2.7.9) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew-Cask by running
  brew cask reinstall xquartz

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gnutls libtasn1 nettle p11-kit

Run `brew missing` for more details.</details>

**Comment by ilovezfs** [comment]
This is intentional. Please see https://github.com/Homebrew/homebrew-core/issues/24610.

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/24349

**Comment by ilovezfs** [comment]
The bug is actually the reverse. `node@6` didn't get the relevant change as it still has an npm resource and should be changed to be like `node@8` as was the intent of #24349.

**Comment by MikeMcQuaid** [comment]
node@4, node@6 and node@8 now behave consistently. Yes, this will mean many symlinks are created if you `brew link --force` but this is not considered a bug.
