### ISSUE TITLE
Is Apache httpd really a dependency for PHP?

### ISSUE THREAD

**Issue by ihorvorotnov** [Homebrew/homebrew-core#24654]
So, PHP migrated to homebrew-core and now it `depends_on "httpd"`. Is that really necessary? 

Maybe I'm missing something, but there are several cases when one needs it without Apache web server. First, if you're developing on a VM and just need a local php cli and some tools (e.g. for PhpStorm). Second, if you prefer Nginx (H2O, Caddy etc). Also, I'm not sure how brew's httpd plays with the one built into macOS.

Is this dependency required? One can use `--ignore-dependencies` flag, but that's an advanced usage, not everyone knows how to handle other dependencies. Also, Apache web server isn't really required for PHP to function properly.

**Comment by MikeMcQuaid** [comment]
It's a popular PHP option that we're building in by default as we're trying to reduce the number of options provided by formulae (as they are error prone and not tested by CI). It's not technically required but we require it. You can create your own PHP formula in your own tap if you'd rather build it differently.

**Comment by neculaidaniel** [comment]
Are you serious @MikeMcQuaid? Do you want to start a war with the users?

**Comment by MikeMcQuaid** [comment]
@neculaidaniel Yes I'm serious. We owe the users exactly as much as they pay for Homebrew. You have a license which allows you to do what you want with the code and you have the ability to run your own taps. You don't have the ability to compel me or any other maintainer or contributor to do what you want just because you say so. 

People who unhelpfully pile on on this issue (including with negative reactions) are extremely likely to get blocked from submitting any issues to Homebrew ever again.

**Comment by ihorvorotnov** [comment]
@MikeMcQuaid Please don't take me wrong – I'm not being negative, just trying to understand the reasoning behind this and figure out how to live with it (or without it). The reason why I opened the issue in the first place is that I upgraded PHP and it force-installed the Apache httpd and an unnecessary httpd service. At the same time, I already had Nginx installed and configured on port 80. Now I have a mess and have to clean it up manually. Other people might run into the same issue, basically anyone who uses any other web server instead of httpd.

Interesting fact: Apache market share is steadily declining, while Nginx market share is steadily growing. Favoring one against other isn't logical. Also, as I said, Apache isn't required for PHP engine to function properly. To me it looks like you would install Chrome and it would silently force-install Slack. Because, why not? Chrome is good for browsing the Interwebs, and Slack is great for talking with people on the Interwebs. These two apps aren't required for each other, even if they often are installed side by side.

**Comment by MikeMcQuaid** [comment]
@neculaidaniel You've been blocked on the Homebrew org. You were warned.

> Now I have a mess and have to clean it up manually.

You don't have to do anything. No services are started or running. There is a new dependency that wasn't there before that you can ignore. That you use `nginx` doesn't affect anything: you can have both installed at the same time with no issues whatsoever.

Read https://github.com/Homebrew/homebrew-php/blob/9fa1f17ccd060720077daae681a34351d018209b/Abstract/abstract-php.rb#L73-L81

That was the old PHP 7.2 formula. Apache was an optional dependency because (unlike nginx) PHP needs to compile against Apache to build the module. Quoting myself from above (that your reply makes it sound like you didn't read)

> we're trying to reduce the number of options provided by formulae (as they are error prone and not tested by CI).

This was an option, it is now built by default and nothing changes for you except that there's now an extra formula on your system that you can ignore. This is done because we need to remove options to make the project work better for everyone and make it easier to maintain. 

> figure out how to live with it (or without it)

You have three options:

1. Ignore `httpd`, it's not doing anything on your machine except taking up a whole 26MB
2. Maintain your own tap with the formula however you want: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
3. Uninstall Homebrew and use MacPorts or similar

**Comment by MikeMcQuaid** [comment]
@franksitton @astlejimmie @troyroman @keithtownsend @waynejohnsonjr @edwardabram Thanks for your 👎s! They help to demotivate the project maintainers and make us want to not spend any of our evenings or weekends working on Homebrew!

> People who unhelpfully pile on on this issue (including with negative reactions) are extremely likely to get blocked from submitting any issues to Homebrew ever again.

As maybe I wasn't explicit enough here: please 👎 any of my comments on this issue (including this one!) to indicate that you'd like to be blocked from the Homebrew organisation on GitHub. If I mentioned you previously and you'd like to _not_ be blocked: it's simple: just undo your 👎 reaction. 

Thanks for playing Please Block Me!

**Comment by ihorvorotnov** [comment]
@MikeMcQuaid Thank you for the explanation. I might just ignore it. However, one more question I couldn't find an answer myself – how can I remove the `httpd` launch agent? The reason is I have 8 services (mariadb, php, memcached, redis, nginx, mailhog, blackfire-agent, dnsmasq), kind of a "web development combo", and I love to start/stop them all at once with `--all` flag. With that additional `httpd` agent, obviously, I can't enjoy it anymore. I'm totally fine to have Apache installed, as you mentioned, that 26MB sitting somewhere doesn't bother me. But that launch agent is redundant for my particular use case.

**Comment by MikeMcQuaid** [comment]
> But that launch agent is redundant for my particular use case.

That's a good question. If you can submit a feature request on https://github.com/homebrew/homebrew-services explaining that you'd like to disable services from being started with `--all` I'll take a look.

**Comment by ihorvorotnov** [comment]
@MikeMcQuaid I'd like to sleep on it until tomorrow to have a clear vision. Will submit a request with further details.

**Comment by mdeboer** [comment]
@ihorvorotnov now if httpd was the only issue. Why do we need the whole boost (435.2 MB) library as a dependency?

It is quite a shock to see all these dependencies all of a sudden coming from homebrew/homebrew-php php72.

You can debate forever what should be included by **default** but at least give **advanced** users the option to disable httpd, glib, boost and the like with a flag (e.g. `--without-httpd`). I don't care if that means I have to rebuild it from source. I just don't have 0.5 GB lying around to do nothing.

**Comment by ilovezfs** [comment]
```
bash-3.2$ brew deps --tree php
php
├── argon2
├── aspell
├── freetds
│   └── openssl
├── freetype
│   └── libpng
├── gettext
├── glib
│   ├── gettext
│   ├── libffi
│   └── pcre
├── gmp
├── httpd
│   ├── apr
│   ├── apr-util
│   │   ├── apr
│   │   └── openssl
│   ├── nghttp2
│   │   ├── c-ares
│   │   ├── libev
│   │   ├── openssl
│   │   ├── libevent
│   │   │   └── openssl
│   │   ├── jansson
│   │   ├── boost
│   │   └── jemalloc
│   ├── openssl
│   └── pcre
├── icu4c
├── imap-uw
│   └── openssl
├── jpeg
├── libpng
├── libpq
│   └── openssl
├── libsodium
├── libzip
├── openssl
├── pcre
├── unixodbc
│   └── libtool
└── webp
    ├── libpng
    └── jpeg

bash-3.2$ 
```

**Comment by MikeMcQuaid** [comment]
> You can debate forever what should be included by default but at least give advanced users the option to disable httpd, glib, boost and the like with a flag (e.g. --without-httpd). I don't care if that means I have to rebuild it from source. I just don't have 0.5 GB lying around to do nothing.

@mdeboer As I've said above: advanced users can create their own tap and do whatever they want there.

**Comment by ihorvorotnov** [comment]
> now if httpd was the only issue.

True.

> advanced users can create their own tap and do whatever they want there.

I don't write in Ruby (yet), so creating a tap and modifying the Formula might take a while if I do it on my own. However, that's what I'm probably going to do, especially if there's someone else ready to help/contribute and maintain it.

> That's a good question. If you can submit a feature request on https://github.com/homebrew/homebrew-services explaining that you'd like to disable services from being started with --all I'll take a look.

Will do it in next couple hours. However, for my current needs, I just wrote a simple shell app that controls the services in a way I need them. Also, rewrote the BitBar plugin to use it instead of `brew services`.

**Comment by MikeMcQuaid** [comment]
> I don't write in Ruby (yet), so creating a tap and modifying the Formula might take a while if I do it on my own. However, that's what I'm probably going to do, especially if there's someone else ready to help/contribute and maintain it.

@ihorvorotnov It's literally a matter of copy and pasting files from one GitHub repository into another. You didn't claim to be an advanced user but anyone who does claim to be one and isn't capable of doing this is not.

**Comment by ihorvorotnov** [comment]
@MikeMcQuaid Yes, I understand. However, in the Formula itself, there's some Apache-specific code (lines 44-64, configs, tests). This needs to be removed if I don't need it. Doing it requires some basic Ruby understanding and some trial and error. I might need to schedule a day or two to work on it, isolated from everything else. Currently, I'm actively learning Swift, refreshing Objective C knowledge, reading a book based on Java code and working daily with PHP, JavaScript, Shell and some Python. This creates a syntax mess in my head. I guess this may be qualified as "advanced". Adding Ruby on top of it should be fun...

Anyway, thanks for your patience and advice. And your work, even if doesn't always fit my expectations. I appreciate it.

**Comment by brandoncarr09** [comment]
How do I thumbs down

**Comment by MikeMcQuaid** [comment]
This will not be installed any more if you use the bottle: https://github.com/Homebrew/homebrew-core/pull/24907
