### ISSUE TITLE
SHA256 mismatch gnuplot-5.2.2.tar.gz

### ISSUE THREAD

**Issue by baarongit** [Homebrew/homebrew-core#24691]
The command I am running is from the torch directory:

./install-deps

which in turn is running:

brew install gnuplot --with-wxmac --with-cairo  --with-x11 --without-lua

The output is as follows: 

Warning: gnuplot: this formula has no --with-pdflib-lite option so it will be ignored!
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.2/gnuplot-5.2.2.tar.gz
==> Downloading from https://downloads.sourceforge.net/#!/project/gnuplot/gnuplot/5.2.2/gnuplot-5.2.2.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a416d22f02bdf3873ef82c5eb7f8e94146795811ef808e12b035ada88ef7b1a1
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/Library/Caches/Homebrew/gnuplot-5.2.2.tar.gz

Now, to test, I am running:

wget https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.2/gnuplot-5.2.2.tar.gz

dgst -sha256 gnuplot-5.2.2.tar.gz

SHA256(gnuplot-5.2.2.tar.gz)= 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf

The file downloaded does not match.  When I try to uncompress the file, I get an error:

tar: Unrecognized archive format

Perhaps someone uploaded a bad file.

Thanks,
Aaron

**Comment by DomT4** [comment]
`scons` failed earlier too, so I suspect SF is having issues. Looks like the redirection is failing. Usually gets resolved upstream in a few hours.

**Comment by baarongit** [comment]
@DomT4 I will try in a few hours and report an update.

**Comment by fxcoudert** [comment]
That's a temporary issue: manual download leads to this message

```
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
```

**Comment by StYaphet** [comment]
@baarongit I manually download gnuplot from [](https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.2/gnuplot-5.2.2.tar.gz) and problem solved.

**Comment by baarongit** [comment]
@fxcoudert The error is still occurring.

</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>

I don't think restoration should take this long.
