### ISSUE TITLE
 install gnuplot with --with-x11 option report  Error: SHA256 mismatch

### ISSUE THREAD

**Issue by StYaphet** [Homebrew/homebrew-core#24700]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

To help us debug your issue please explain:

I use `brew install gnuplot` without --with-x11 option, it installed success. But when I run `brew install gnuplot`, brew repoted error as follows:

```
==> Reinstalling gnuplot --with-x11
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.2/gnuplot-5.2.2.tar.gz
Already downloaded: /Users/shorewb/Library/Caches/Homebrew/gnuplot-5.2.2.tar.gz
Error: SHA256 mismatch
Expected: a416d22f02bdf3873ef82c5eb7f8e94146795811ef808e12b035ada88ef7b1a1
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/shorewb/Library/Caches/Homebrew/gnuplot-5.2.2.tar.gz
To retry an incomplete download, remove the file above.
```

I remove /Users/shorewb/Library/Caches/Homebrew/gnuplot-5.2.2.tar.gz and retry, brew still report this error.

**Comment by commitay** [comment]
This is a SourceForge issue, see https://github.com/Homebrew/homebrew-core/issues/24691#issuecomment-369733561

**Comment by StYaphet** [comment]
Thanks.
