### ISSUE TITLE
Sourceforge tarball SHA256 mismatch 

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#24738]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Installing formulas from Sourceforge tarballs often fail with SHA256 mismatch, for example:

```
==> Installing ffmpeg dependency: little-cms2
==> Downloading https://downloads.sourceforge.net/project/lcms/lcms/2.9/lcms2-2.
==> Downloading from https://downloads.sourceforge.net/#!/project/lcms/lcms/2.9/
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 48c6fdf98396fa245ed86e622028caf49b96fa22f3e5734f853f806fbc8e7d20
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/hanxue/Library/Caches/Homebrew/little-cms2-2.9.tar.gz

==> Installing ffmpeg dependency: lame
==> Downloading https://downloads.sourceforge.net/sourceforge/lame/lame-3.100.ta
yarn ==> Downloading from https://downloads.sourceforge.net/#!/sourceforge/lame/lame-
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: ddfe36cab873794038ae2c1210557ad34857a4b6bdc515785d1da9e175b1da1e
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
```

I notice recently there are a lot of issues regarding Sourceforge source tarball hash mismatch, for example https://github.com/Homebrew/homebrew-core/issues/18630 , https://github.com/Homebrew/homebrew-core/issues/9529 , https://github.com/Homebrew/homebrew-core/issues/20628 , https://github.com/Homebrew/homebrew-core/issues/24700 , https://github.com/Homebrew/homebrew-core/issues/24140

This issue has been occurring since at least 27 Jan 2018, and there has been similar issues in the past. Is using Github mirror as the primary download source a good approach to avoid this problem? For example, using https://github.com/mm2/Little-CMS/archive/lcms2.9.tar.gz as the source of `little-cms2`

**Comment by ilovezfs** [comment]
No, we need to be patient until SourceForge is out of recovery mode.
