### ISSUE TITLE
Support for subversion i18n

### ISSUE THREAD

**Issue by moonfruit** [Homebrew/homebrew-core#24740]
## Support for subversion i18n
I noticed that subversion compiled by homebrew do **NOT** support i18n. But subversion from CentOS or Ubuntu does. Even subversion complied by WANdisco also support i18n.
And homebrew does not add a parameter to Subversion for switching i18n on. It's just like `--with-gettext` for git.
Please support subversion i18n. A parameter is also acceptable. Thank you.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
@moonfruit You can now `brew reinstall --with-gettext subversion` thanks to @equal-l2

**Comment by moonfruit** [comment]
@ilovezfs On my macOS, compile subversion with --with-gettext stucks. It cannot be done. When it stucks, I found I can not create any process. I found that it forked a lot perl5.18 to do something, and no other resources for other process. Should I open another issue?

Here is the compile log.
[brew.txt](https://github.com/Homebrew/homebrew-core/files/1788547/brew.txt)

**Comment by ilovezfs** [comment]
@moonfruit I'll see if I can reproduce the problem. No need for another issue.

**Comment by ilovezfs** [comment]
@moonfruit hmm. I tried it on 10.11 and 10.13, and no problems. Have you tried just rebooting?
