### ISSUE TITLE
python3 creates links for python2

### ISSUE THREAD

**Issue by hyiltiz** [Homebrew/homebrew-core#24759]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Run `pip3 install pandas`. 

- What happened (include command output)
It wasn't in system path. 

- What you expected to happen
`pip3` gets called.

- Step-by-step reproduction instructions (by running `brew install` commands)
In a system where python2 and python3 was originally installed and kept up to date by constantly `brew update` and `brew upgrade`, install any package via `pip3`. All python3 bindings/links lost.

```BASH
/u/l/C/p/3/bin $ ls
2to3-3.6@          idle3.6@  pydoc3@    python3-config@    python3.6m@         pyvenv-3.6@
easy_install-3.6*  pip3*     pydoc3.6@  python3.6@         python3.6m-config@  wheel3*
idle3@             pip3.6*   python3@   python3.6-config@  pyvenv@
/u/l/C/p/3/bin $ brew link python3
Warning: Already linked: /usr/local/Cellar/python/2.7.14_3
To relink: brew unlink python && brew link python
/u/l/C/p/3/bin $
/u/l/C/p/3/bin $ ls
2to3-3.6@          idle3.6@  pydoc3@    python3-config@    python3.6m@         pyvenv-3.6@
easy_install-3.6*  pip3*     pydoc3.6@  python3.6@         python3.6m-config@  wheel3*
idle3@             pip3.6*   python3@   python3.6-config@  pyvenv@
/u/l/C/p/3/bin $ brew link python3
Warning: Already linked: /usr/local/Cellar/python/2.7.14_3
To relink: brew unlink python && brew link python
/u/l/C/p/3/bin $ brew link python
Warning: Already linked: /usr/local/Cellar/python/2.7.14_3
To relink: brew unlink python && brew link python
/u/l/C/p/3/bin $ python unlink python
python: can't open file 'unlink': [Errno 2] No such file or directory
/u/l/C/p/3/bin $ brew unlink python2
Error: No such keg: /usr/local/Cellar/python@2
/u/l/C/p/3/bin $ brew unlink python@2
Error: No such keg: /usr/local/Cellar/python@2
/u/l/C/p/3/bin $ brew unlink python3
Unlinking /usr/local/Cellar/python/2.7.14_3... 32 symlinks removed
/u/l/C/p/3/bin $ brew link python2
Error: No such keg: /usr/local/Cellar/python@2
/u/l/C/p/3/bin $ brew link python3
Linking /usr/local/Cellar/python/2.7.14_3... 32 symlinks created
/u/l/C/p/3/bin $ ls
2to3-3.6@          idle3.6@  pydoc3@    python3-config@    python3.6m@         pyvenv-3.6@
easy_install-3.6*  pip3*     pydoc3.6@  python3.6@         python3.6m-config@  wheel3*
idle3@             pip3.6*   python3@   python3.6-config@  pyvenv@
/u/l/C/p/3/bin $ ./pip3 install pandas
Collecting pandas
  Downloading pandas-0.22.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (14.9MB)
    100% |████████████████████████████████| 14.9MB 75kB/s
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil>=2->pandas)
Installing collected packages: pandas
Successfully installed pandas-0.22.0
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by sunilshah** [comment]
I also found this when I did 
>> brew update 
...
==> Deleted Formulae
python3 ✔
==> Migrating python3 to python
==> Unlinking python3
==> Unlinking python
==> Moving python3 children
==> Linking python

>> brew upgrade python3 
restored  the links, allowing pip3 install -U <packageName>.

**Comment by ilovezfs** [comment]
The migration output now recommends `brew upgrade`:
https://github.com/Homebrew/brew/releases/tag/1.5.8
