### ISSUE TITLE
Python 3 migration prevents access to system Python

### ISSUE THREAD

**Issue by scolby33** [Homebrew/homebrew-core#24757]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs python
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 1.5.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84d718cbef0b96ef621a2ec51171f7d66c20f87d
Last commit: 85 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 106634c3db0e1d1702519ac12d55fb896ce25b24
Core tap last commit: 72 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Run `brew update` and `brew upgrade`
- What happened (include command output)
Everything went fine
- What you expected to happen
`python` should call the system Python in `/usr/bin/python`
- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew unlink python
$ brew link python
$ which python
/usr/local/bin/python2
```

I really think the `python` Python 3 formula shouldn't override the system Python.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is intentional. Python 3 is the latest version of Python. `brew install python` puts the latest version of Python in your PATH as `python`.

**Comment by scolby33** [comment]
I disagree, not because I prefer Python 2, but because overriding the system Python is surprising to me having never installed the `python2` formula. In any case, I can work around this.

**Comment by ilovezfs** [comment]
> In any case, I can work around this.

👍

**Comment by mansweet** [comment]
@scolby33 

> I can work around this

How?  Please share.  I use python 2.x for everything.  I just want my existing virtual environments to work and everything to go back to the way it was.  I'm not gonna complain to the maintainers (@ilovezfs ) about this change, but would love some guidance on how to mitigate it, or just completely unwind it all.

For now, i've just uninstalled anything that depends on python3, and python3 itself, and copied everything from `/usr/local/opt/python@2` to `/usr/local/opt/python`.  I know this is a hammer approach, but I need to continue my day!

**Comment by scolby33** [comment]
My workaround was to install pyenv and stop using Homebrew Python for anything but as a dependency (I think for vim, mainly).

**Comment by Fauxsys** [comment]
```
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH=$PATH:/usr/local/sbin
```

1) Before the latest update, the above was required in `~/.bash_profile` for system python, brew python2, and brew python3 to all work nicely together. With the latest update of brew, those lines are no longer required in `~/.bash_profile` and `python` will refer to brew python2. System python will remain unreferenced.

2) I removed all installed system python packages by running `pip freeze | xargs pip uninstall -y` and all re-installed packages will now point to brew python2.
