### ISSUE TITLE
No python3 executables

### ISSUE THREAD

**Issue by externl** [Homebrew/homebrew-core#24758]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

After this long debate https://github.com/Homebrew/homebrew-core/issues/15773 I'm kind of disappointed to see that there is no `python3` symlink with the new python setup.

It would be nice to have `exe3` versions of all the python executables.

Now all of my scripts with `/usr/bin/env python3` no longer work.

**Comment by ilovezfs** [comment]
```
brew upgrade
```

**Comment by externl** [comment]
After debugging a little more. It seems that although python3 -> python. Brew seems very confused as to what version I have:

```
❯ brew info python
python: stable 3.6.4 (bottled), devel 3.7.0b1, HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/2.7.14_3 (3,574 files, 49.4MB) *
  Poured from bottle on 2018-02-07 at 10:07:00
/usr/local/Cellar/python/3.6.4_2 (3,742 files, 57.6MB)
  Poured from bottle on 2018-01-08 at 10:21:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: pkg-config ✔, sphinx-doc ✔
Required: openssl ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔, xz ✔
Optional: tcl-tk ✘, sphinx-doc ✔
==> Options
--with-quicktest
	Run `make quicktest` after the build
--with-sphinx-doc
	Build HTML documentation
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--without-gdbm
	Build without gdbm support
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--without-xz
	Build without xz support
--devel
	Install development version 3.7.0b1
--HEAD
	Install HEAD version
==> Caveats
Pip, setuptools, and wheel have been installed. To update them
  pip3 install --upgrade pip setuptools wheel

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

Unversioned symlinks python, python-config, pip etc. pointing to python3,
python3-config, pip3 etc., respectively, have been installed.

If you need Homebrew's Python 2, `brew install python@2`.

~
❯ brew link python
Warning: Already linked: /usr/local/Cellar/python/2.7.14_3
To relink: brew unlink python && brew link python

~
❯ brew unlink python
Unlinking /usr/local/Cellar/python/2.7.14_3... 32 symlinks removed

~
❯ brew link python
Linking /usr/local/Cellar/python/2.7.14_3... 32 symlinks created
```

**Comment by externl** [comment]
Derrr... sorry @ilovezfs :)

**Comment by ilovezfs** [comment]
@externl no worries!

**Comment by ilovezfs** [comment]
The migration output now recommends `brew upgrade`:
https://github.com/Homebrew/brew/releases/tag/1.5.8

**Comment by externl** [comment]
Cool thanks. What tripped me up was that I was installing an unrelated package and the auto `brew update` was showing renaming python3 -> python, etc. When I did `brew info python` it showed python 3.
