### ISSUE TITLE
Installing vim replaces default python

### ISSUE THREAD

**Issue by cmsj** [Homebrew/homebrew-core#24761]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was installing the vim8 brew, which pulls in python3 as a dependency

- What happened (include command output)
`/usr/local/bin/python` was created as a symlink to the python3 install, meaning that per the default `$PATH`, homebrew's python3 trumps the system python 2.

- What you expected to happen
I expected my default python interpreter to not change, and I guessed I'd have python3 installed with a `/usr/local/bin/python3` symlink, and a `python` symlink in another directory, per the behaviour change in https://github.com/Homebrew/homebrew-core/pull/14408

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install vim`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by cmsj** [comment]
I'm not an expert at Ruby or Homebrew, but I think https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L203 may be the problem, but I'm slightly concerned that there has been a policy shift since #14408 because 788b65e645bb342e82946b52173997cd00c322ac seems to explicitly remove the removal of system-python-shadowing symlinks in favour of explicitly adding them.

**Comment by ilovezfs** [comment]
This is intentional. The `vim` formula depends on the `python` formula and the `python` formula was upgraded to be Python 3 on March 1 as was announced in January: https://brew.sh/2018/01/19/homebrew-1.5.0/

**Comment by cmsj** [comment]
Ooi why did the stance on shadowing system python change?

I appreciate that this probably isn’t the right venue to debate that decision, but I think it’s a mistake to override by default python interpreter (with any version) because I installed a text editor.

**Comment by cmsj** [comment]
Also, I think this bug is valid, I just read the blog post:

```
(although this will be keg-only so neither python nor python2 will be added to the PATH by default without a manual brew link --force
```

That is not the behaviour I observed.

**Comment by ilovezfs** [comment]
That is referring to the new python@2 formula, not python.
