### ISSUE TITLE
Option for old behavior of python formula

### ISSUE THREAD

**Issue by stek29** [Homebrew/homebrew-core#24788]
I know that Python migration is intentional, and was announced in January (via post in blog which I doubt is read by many users)

However, one may want to have "python3" link and/or have system python not shadowed.

From what I saw in other closed issues, user is expected to workaround this, but  I can't come up with any workaround which doesn't require replacing links brew creates manually, and which won't break on upgrade.

In fact, I can't come up with any way to workaround this properly: if there's any non-kegonly formula depending on python, it can safely expect "python" to be python 3, and in fact it has to do that, because it can't use python3 anymore.

I also realize that "python is now same as other languages", but python2 and python3 is a thing that makes it different.

So, provided that workaround isn't easy, and may even be impossible in some cases, I think that it should be provided out of box.

And removing "python3" symlink is a bad choice too -- even on systems where "python" is python 3, python3 symlink still exists
because it's widely used.

And maybe it can be done in a way that anything depending on python may specify it absolutely needs "python" to be "python3", but I'm not that good in brew to think of this.

**Comment by ilovezfs** [comment]
> because it can't use python3 anymore.

I'm not sure what you mean by that.

```
bash-3.2$ tree 
.
├── 2to3 -> ../Frameworks/Python.framework/Versions/3.6/bin/2to3
├── 2to3-3.6 -> ../Frameworks/Python.framework/Versions/3.6/bin/2to3-3.6
├── easy_install
├── easy_install-3.6
├── idle -> ../Frameworks/Python.framework/Versions/3.6/bin/idle3.6
├── idle3 -> ../Frameworks/Python.framework/Versions/3.6/bin/idle3
├── idle3.6 -> ../Frameworks/Python.framework/Versions/3.6/bin/idle3.6
├── pip
├── pip3
├── pip3.6
├── pydoc -> ../Frameworks/Python.framework/Versions/3.6/bin/pydoc3.6
├── pydoc3 -> ../Frameworks/Python.framework/Versions/3.6/bin/pydoc3
├── pydoc3.6 -> ../Frameworks/Python.framework/Versions/3.6/bin/pydoc3.6
├── python -> ../Frameworks/Python.framework/Versions/3.6/bin/python3.6
├── python-config -> ../Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
├── python3 -> ../Frameworks/Python.framework/Versions/3.6/bin/python3
├── python3-config -> ../Frameworks/Python.framework/Versions/3.6/bin/python3-config
├── python3.6 -> ../Frameworks/Python.framework/Versions/3.6/bin/python3.6
├── python3.6-config -> ../Frameworks/Python.framework/Versions/3.6/bin/python3.6-config
├── python3.6m -> ../Frameworks/Python.framework/Versions/3.6/bin/python3.6m
├── python3.6m-config -> ../Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
├── pyvenv -> ../Frameworks/Python.framework/Versions/3.6/bin/pyvenv
├── pyvenv-3.6 -> ../Frameworks/Python.framework/Versions/3.6/bin/pyvenv-3.6
├── wheel
└── wheel3 -> wheel

```

**Comment by ilovezfs** [comment]
If you're not seeing the python3 symlink that's probably because you have not run `brew upgrade` yet.

**Comment by stek29** [comment]
@ilovezfs yup, but the issue isn't just about python3 symlink.
