### ISSUE TITLE
vim --with-python@2 still installs python 3

### ISSUE THREAD

**Issue by cmsj** [Homebrew/homebrew-core#24789]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
```brew install vim --with-python@2``` to install vim with python2 instead of python3

- What happened (include command output)
```
==> Installing dependencies for vim: python, python@2
==> Installing vim dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-3.6.4_3.high_sierra.bottle.tar.gz
```

It does install `python@2` and build against it, but `python` is also installed.

- What you expected to happen

`python` to not be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

```brew install vim --with-python@2```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
@cmsj https://github.com/Homebrew/homebrew-core/pull/24790

**Comment by ilovezfs** [comment]
@cmsj this should now be fixed if you `brew update`. (Previously you could `--with-python@2 --without-python` to avoid that but now only the `--with-python@2` will be needed.)

**Comment by cmsj** [comment]
Thanks!

**Comment by ilovezfs** [comment]
You're welcome :)
