### ISSUE TITLE
installing python3 symlinked incompatible "python" binary

### ISSUE THREAD

**Issue by ghazel** [Homebrew/homebrew-core#24792]
I installed python3 with homebrew. Homebrew then created a `python` symlink to python3, which broke scripts on my system that expect python2 (which macOS ships with).

Usually, homebrew is polite enough to refuse to symlink, or it installs the conflicting packages under a different name. 

Some examples:

```bash
$ brew install llvm
...
==> Caveats
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.
...
$ clang --version | grep version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
$ /usr/local/opt/llvm/bin/clang --version | grep version
clang version 5.0.1 (tags/RELEASE_501/final)
```

```bash
$ brew install make
...
==> Caveats
All commands have been installed with the prefix 'g'.
If you do not want the prefix, install using the "with-default-names" option.
...
$ make --version | grep Make
GNU Make 3.81
$ gmake --version | grep Make
GNU Make 4.2.1
```

Homebrew previously installed python3 under the name `python3`, and I would vastly prefer that behavior, since python3 is not compatible with python2. Or, python3 could be "keg-only".

**Comment by ilovezfs** [comment]
You'll need to start using e.g. `#!/usr/bin/env python2.7` or `#!/usr/bin/python` in scripts that aren't compatible with python3.

**Comment by ghazel** [comment]
That's the right answer if I cared to migrate all the python scripts on my system to python3, but I do not. (many came with macOS itself).

Homebrew should not force an incompatible upgrade of a system provided package.

**Comment by ilovezfs** [comment]
@ghazel Things from macOS itself use `#!/usr/bin/python`. Your own stuff should do the same, and use a full path, or use a versioned python program name.

**Comment by ghazel** [comment]
I am using `python`, which is intended to be the system python -- as `clang` in the above example is the system clang.

It fails even the most basic test: 

```
$ python -c 'print "hello world!"'
  File "<string>", line 1
    print "hello world!"
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("hello world!")?
```

Homebrew should not force an incompatible upgrade of a system provided package.

**Comment by ilovezfs** [comment]
If you need to be able to run `python` and have it be python 2, then

```
export PATH=/System/Library/Frameworks/Python.framework/Versions/Current/bin:$PATH
```

or `brew install python@2` and

```
export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
```

**Comment by ghazel** [comment]
I think you're imposing quite a burden on the user here.

Other homebrew packages that conflict are nice enough to not symlink by default. I would prefer this.
I did not ask to replace "python", in fact I installed a package which depended on "python3" and this happened to my system which I then had to debug and come here to report.

I appreciate your advice on supporting python3, but I did not intend to do that and homebrew should not force me to do so.

**Comment by ilovezfs** [comment]
>Other homebrew packages that conflict are nice enough to not symlink by default

That is not the case for all packages. The most notable exceptions are `perl`, `python`, `ruby`, `vim`, and `emacs`, and that's likely to continue to be the case for the foreseeable future.

**Comment by ghazel** [comment]
The case of python3 is different, since python3 is clearly not compatible with python2. Which is why homebrew broke my system and I came here to report a bug.

**Comment by ilovezfs** [comment]
`perl` and `ruby` are not API compatible either.

**Comment by ilovezfs** [comment]
@ghazel we could consider those bugs, but we don't. It's the application developers' responsibility to make sure they're using the desired interpreter. A Homebrew user who runs `brew install perl python ruby` should then be able to find the latest upstream versions of Perl, Python and Ruby installed in HOMEBREW_PREFIX/bin installed as `perl`, `python`, and `ruby`. That is now the case.

**Comment by ghazel** [comment]
But I didn't type anything like that. I typed `brew install foo` where foo depends on `python3`.

It is my responsibility to make sure my system has functional interpreters for languages I use, and `python3` is not one of them.

**Comment by ilovezfs** [comment]
@ghazel It's not feasible for us to have one behavior when something is installed as a dependency and another behavior when it's installed explicitly.

**Comment by ghazel** [comment]
I agree, that would be messy. So, the `foo` package should specify the interpreter it intends to use by version number, as you suggest, and the package should not attempt to symlink since it is not equivalent.

**Comment by ilovezfs** [comment]
Anything that is not keg_only is going to be symlinked even if it's installed as a dependency.

**Comment by ghazel** [comment]
Then it sounds like it should be keg_only.

**Comment by ilovezfs** [comment]
That would result in it not being symlinked into `#{HOMEBREW_PREFIX}/bin` when someone runs `brew install python`.

**Comment by ghazel** [comment]
Which is also true of `clang` and `make` in my examples above, both of which I needed from homebrew. I can work with that; it doesn't introduce sudden breaking changes.

**Comment by ilovezfs** [comment]
In the cases of `perl`, `python`, and `ruby`, we don't think that is an acceptable user experience for the majority of users.

**Comment by ghazel** [comment]
First, do no harm.

**Comment by ilovezfs** [comment]
Expecting people to set appropriate PATH environment variables in their shell profiles and shebang lines in their scripts is not doing harm.

**Comment by ghazel** [comment]
Shebang lines do not affect imported modules, obviously. And setting PATH environment variables as you describe here https://github.com/Homebrew/homebrew-core/issues/24792#issuecomment-370152799 is both unexpected and undiscoverable -- even as the damage is done.

So yes, harm. I wouldn't have come here to report a bug if there was not any.

**Comment by ilovezfs** [comment]
I apologize for the pain. This isn't something likely to change.

**Comment by ghazel** [comment]
Also note; it took a comment thread for me to discover Homebrew's policy about a few languages taking precedence to such a degree that keg_only would not be used.

**Comment by ilovezfs** [comment]
Feel free to comment on https://github.com/Homebrew/brew/pull/3863 if you have any suggestions for the corresponding docs changes.

**Comment by anthonybrown** [comment]
Thank you, this was messing with me

**Comment by akienm** [comment]
wrt 'Expecting people to set appropriate PATH environment variables in their shell profiles and shebang lines in their scripts is not doing harm.'

i didn't know about the language prefs either. putting that information to the console when it made the change from a 2.7 link to a 3.x link would have been immeasurably helpful.

i gotta say, you have taught me today why not to upgrade just because one is available. thanks to this 'no pain' tiny little change of yours, it's gonna take a month to fix all the ins and outs of this. thanks so much.
