### ISSUE TITLE
Python symlink violates guidance from Python dev team

### ISSUE THREAD

**Issue by richardcooper** [Homebrew/homebrew-core#24793]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Quoting from the official position of the core Python development team - [PEP 394 -- The "python" Command on Unix-Like Systems](https://www.python.org/dev/peps/pep-0394/)

> The more general `python`command should be installed whenever any version of Python 2 is installed and should invoke the same version of Python as the `python2` command.

The Python team have put literally years of thought and effort into making the migration from Python 2 to 3 go as smoothly as possible for users, system administrators, and distributions alike.

Homebrew should follow PEP 394 and not unilaterally decide that `python` now points to Python 3.

**Comment by richardcooper** [comment]
If it helps, I'm happy to submit a PR which either removes the `python` symlink or at least makes it optional.

**Comment by ilovezfs** [comment]
As noted in https://github.com/Homebrew/homebrew-core/pull/24604#issue-171653084 we're well aware of that PEP. Thanks for your concern.

**Comment by habnabit** [comment]
Chiming in to say that this was very irritating and disruptive. I have python code which I had no intention of updating and now I have to go find and replace shebangs as things break.

**Comment by ilovezfs** [comment]
@richardcooper PR making python and python@2 PEP 394 compliant:
https://github.com/Homebrew/homebrew-core/pull/25060
