### ISSUE TITLE
offlineimap not happy with default python3

### ISSUE THREAD

**Issue by boyanpenkov** [Homebrew/homebrew-core#24809]
Hello folks -- after the latest python update which links the default python to python3, offlineimap does not work (since it depends on imaplib2, which only supports python2).

What can we do about this?  Can we tell offlineimap the specific python to use?

As for the gist: 
→ Learning/C brew gist-logs python@2                                                                                   6:52:44
https://gist.github.com/5977ba3fc8cbe9c5b0f87c58eaa0cb39

If that one is not correct, please let me know.  First-time poster....

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by frodeaa** [comment]
quick fix is to create an alias for offlineimap where python2 is used

    alias offlineimap="python2.7 /usr/local/Cellar/offlineimap/7.1.5/libexec/offlineimap.py"

the ´/usr/local/bin/offlineimap` should be updated to use python2 and the formula will need to depend on python2

    PYTHONPATH="/usr/local/Cellar/offlineimap/7.1.5/libexec/vendor/lib/python2.7/site-packages" exec "/usr/local/Cellar/offlineimap/7.1.5/libexec/offlineimap.py" "$@"

    PYTHONPATH="/usr/local/Cellar/offlineimap/7.1.5/libexec/vendor/lib/python2.7/site-packages" exec "python2" "/usr/local/Cellar/offlineimap/7.1.5/libexec/offlineimap.py" "$@"

**Comment by boyanpenkov** [comment]
Can confirm that the first line does work, and yields a functioning offlineimap.  

What are the consequences of making it part of the formula? Can we do this?

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update` and `brew upgrade`

**Comment by boyanpenkov** [comment]
Yes indeedy -- does work after the update.
Thanks kindly to all involved!
