### ISSUE TITLE
[asio] checksum mismatch for --devel

### ISSUE THREAD

**Issue by gjasny** [Homebrew/homebrew-core#24804]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I wanted to install the latest development version of asio.

- What happened (include command output)

```
$ brew install asio --devel
==> Downloading https://downloads.sourceforge.net/project/asio/asio/1.11.0%20%28Development%29/asio-1.11.0.tar.bz2
Already downloaded: /Users/gjasny/Library/Caches/Homebrew/asio-1.11.0.tar.bz2
Error: SHA256 mismatch
Expected: 4f7e13260eea67412202638ec111cb5014f44bdebe96103279c60236874daa50
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
```

- What you expected to happen

Chechsums should match, asio should be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install asio --devel`

**Comment by commitay** [comment]
This was a SourceForge issue, it should be working now.
