### ISSUE TITLE
ASan issue on macOS 10.12 - Wine, running winbox.exe [EDIT: XQuartz 2.7.9-2.7.10_Beta2 ASan]

### ISSUE THREAD

**Issue by AlexanderNeilson** [Homebrew/homebrew-core#2481]
# Please follow the general troubleshooting steps first:

- [yes] Ran `brew update` and retried your prior step?
- [yes] Ran `brew doctor`, fixed as many issues as possible and retried your prior step? (Python installed to non standard location - for python development - not removed)

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

My particular builds of Wine --devel under macOS 10.12 appears to invoke / include address sanitizer in the build which causes failures to execute apps. Mistydemeo was unable to reproduce so separated from issue: 1597 [Earlier discussion](https://github.com/Homebrew/homebrew-core/issues/1957#issuecomment-229244163)

[Gist-Logs Output](https://gist.github.com/c86728fbbb553c23f3c966a6b832f860)

Looks to be a local issue if it can't be reproduced by others, AFAIK there is no relationship to python at any part of this installation so my location of python shouldn't have any effect.

To try resolve this I have blown away my whole xcode installation and followed all instructions for removal of Homebrew. Then reinstalled xcode-beta and homebrew as if a new install. New install was then attempted with wine --devel as the only install (plus obviously dependencies).

I am thinking my next step may need to have a full wipe and reinstall of the system from base to eliminate the effect and rebuild my system around whats there, if anyone can provide some insight however into what could be causing this to happen or that I could try investigate.

**Comment by mistydemeo** [comment]
Can you show me the output of the following commands?

```
otool -L /usr/local/opt/wine/lib/libwine.1.dylib
otool -L /usr/local/opt/wine/bin/wine.bin
```

**Comment by AlexanderNeilson** [comment]
```
Atlantis:Git alexander$ otool -L /usr/local/opt/wine/lib/libwine.1.dylib
/usr/local/opt/wine/lib/libwine.1.dylib:
	/usr/local/opt/wine/lib/libwine.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1333.20.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 763.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1237.0.0)
Atlantis:Git alexander$ 
```

```
Atlantis:Git alexander$ otool -L /usr/local/opt/wine/bin/wine.bin
/usr/local/opt/wine/bin/wine.bin:
	@rpath/libwine.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1237.0.0)
Atlantis:Git alexander$
```

**Comment by mistydemeo** [comment]
And just for completeness, can you include in this issue the full output you get when it fails?

**Comment by AlexanderNeilson** [comment]
[winefail.txt](https://github.com/Homebrew/homebrew-core/files/338776/winefail.txt)

![image](https://cloud.githubusercontent.com/assets/13706540/16444655/3a6c352a-3e33-11e6-88e7-12c4584189f9.png)

![image](https://cloud.githubusercontent.com/assets/13706540/16444707/7d2a6ad0-3e33-11e6-885c-929e9a022120.png)

Hopefully this can help with any guidance / testing?

Regards
Alexander

**Comment by AlexanderNeilson** [comment]
Hi Team

I went back and wiped the entire machine, fresh install from fresh download on macOS 10.12.

After the install I completed normal user setup, installed XQuartz 2.7.10 Beta 2, install homebrew (allowing it to install command line tools directly), then brew install wine --devel, brew install winetricks.

Then I downloaded a fresh copy of winbox.exe and wine ~/winbox.exe (downloaded into my home directory).

I am still seeing the same memory (address sanitiser) errors. I am starting to wonder if there could be either a hardware issue or a problem with the small amount of ram in the MacBook Air 13".

Is anyone else experiencing this as an issue with anything they try?

[New Gist-Logs](https://gist.github.com/35624b0430c94b5d67f745b341e1c910)
[Build Process - BuildWineClean.txt](https://github.com/Homebrew/homebrew-core/files/341421/BuildWineClean.txt)
[What happens when I run winbox.exe - RebuildFailWine.txt](https://github.com/Homebrew/homebrew-core/files/341422/RebuildFailWine.txt)

```
Alexanders-MacBook-Air:~ alexander$ otool -L /usr/local/opt/wine/lib/libwine.1.dylib
/usr/local/opt/wine/lib/libwine.1.dylib:
	/usr/local/opt/wine/lib/libwine.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1333.20.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 763.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1237.0.0)
Alexanders-MacBook-Air:~ alexander$ 
```

```
Alexanders-MacBook-Air:~ alexander$ otool -L /usr/local/opt/wine/bin/wine.bin
/usr/local/opt/wine/bin/wine.bin:
	@rpath/libwine.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1237.0.0)
Alexanders-MacBook-Air:~ alexander$ 
```

Any guidance to locating these faults or providing further helpful information that would be much appreciated.

Regards
Alexander

**Comment by mistydemeo** [comment]
Do you mind providing the output of `env`? Feel free to redact anything. I'm wondering if there might be environment variables influencing this.

**Comment by AlexanderNeilson** [comment]
I will go back to 10.12 as soon as I can again, I am currently rebuilding the machine as 10.11 fresh and untouched so I can confirm that its definitely related to something in my 10.12 and not something like a bug in the latest XQuartz (also this machine is my main road machine so I have been taking my MBP to the field with me).

I may also get my MBA back on track and try the same setup on the MBP and see what is different.

Thank you again for all the time you putting into helping something that you can't reproduce.

Regards
Alexander

**Comment by mheaton228** [comment]
I think I'm having the same issue. There's something with the ASan that keeps buggering up with installing any .exe I'm trying after a clean install of 10.12. I was able to get Wine and Winetricks installed but with any other program I am getting: 

==70931==Shadow memory range interleaves with an existing memory mapping. ASan cannot proceed correctly. ABORTING.
==70931==ASan shadow was supposed to be located in the [0x1ffff000-0x3fffffff] range.

It also referenced this thread. I can show you what's in my env if you'd like.

**Comment by AlexanderNeilson** [comment]
Hi mheaton228

That does look like the same thing, If you can provide your full output when you run the apps, the gist-logs, etc as above just to validate. Also if you can send in your env then that may help.

As I test last night I tried regedit in my wine and it threw the same error for me as my winbox so it seems wine wide.

Can you also confirm please what kind of machine you are running it on? how much ram? what model mac? and what version of XQuartz? just to try find a commonality.

Regards
Alexander

**Comment by mistydemeo** [comment]
I just noticed this in your `brew --config`:

> X11: 2.7.10_beta2 => /opt/X11

Whereas I installed the stable release:

> X11: 2.7.9 => /opt/X11

Can one of you downgrade to 2.7.9 and see if that resolves your issue?

**Comment by AlexanderNeilson** [comment]
@mheaton228 

Can you confirm if you are on 2.7.10_beta2?

I have been using that and I am currently in the build phase for my wine on 10.11 with 2.7.10_beta2. If this fails we may have our common factor and be able to zero in on a root cause.

If this dies then I will go back up to 10.12 and try with 2.7.9.

Regards
Alexander

**Comment by mistydemeo** [comment]
I'm seeing a report on the XQuartz tracker that suggests that 2.7.10 (and maybe some builds of 2.7.9) are built with ASan, leading to bugs like this one: https://bugs.freedesktop.org/show_bug.cgi?id=96666

**Comment by mheaton228** [comment]
I wasn't able to install Wine at all until I upgraded to the 2.7.10_beta2 and XCode 8 beta, but I did the XQuartz upgrade before I did the XCode upgrade. 

Here's the stuff requested:

- [When I try to install an .exe](https://gist.github.com/mheaton228/1f70478aa8c1e2f1e82cb79a4d4e1837)
- [My env output](https://gist.github.com/mheaton228/759de06f266c4b35876b9f7d506b5071)

**Comment by AlexanderNeilson** [comment]
I can confirm I see the same failure on 10.11 with 2.7.10_beta2

Tonight when I get home from work I will install 10.12 again and then install wine without XQuartz (as it should be only an optional not a requirement) then I can also try it with 2.7.8, 2.7.9, and see if I can come up with some clear advice for users. 

Regards
Alexander

**Comment by mistydemeo** [comment]
I just realized that, while I have XQuartz 2.7.9 installed, I've been running wine using the Mac driver. You appear to be using the X driver, yes? Does this occur using the Mac driver?

**Comment by AlexanderNeilson** [comment]
My system is building from scratch again now so hopefully results without XQuartz within an hour or so. 

I understood even with XQuartz installed that the system would build both available but still use Mac driver by default. But maybe not. So I will try it clean now and see how that goes.

Regards
Alexander

**Comment by sidneys** [comment]
I am having the a similar issue on El Capitan using the XCode 8 Beta: Cannot install Wine at all at the moment. Console message pointed me to this issue...

**Comment by AlexanderNeilson** [comment]
Hi team. 

It looks like this can be confirmed as a problem linked to XQuartz. 

I can build under 10.12 without XQuartz (note you need to add --without-x11 to your install command) and have my wine apps execute. 

I haven't tried it built against XQuartz 2.7.8 yet but I can try that but if people could remove it and then rebuild without linking to X11 then we may be able to advise people or look at varying install if these versions are detected. 

Regards
Alexander

**Comment by mistydemeo** [comment]
I can't seem to reproduce on 10.11 with XQuartz 2.7.9, but I'm pretty confident about what the issue is now.

**Comment by mistydemeo** [comment]
Can someone who has XQuartz 2.7.9 installed who *didn't* previously have 2.7.10 beta installed check if there's an `/opt/X11/lib/asan` directory? I do not have that, with 2.7.9 installed over 2.7.8.

This thread confirms that the beta releases of XQuartz use address sanitization for debug purposes: https://lists.macosforge.org/pipermail/xquartz-dev/2016-May/003957.html The implication is that the stable releases aren't intended to.

**Comment by mistydemeo** [comment]
@sidneys I don't think your issue is related; can you please open a new issue with the debug output specified in the [troublshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md)? Thanks!

**Comment by AlexanderNeilson** [comment]
I have just installed 2.7.9 onto my MBP (Still on 10.11.6).

Was previously running 2.7.8 and confirmed the folder was not in place at that point.

My install of 2.7.9 comes off a fresh download taken from the project homepage main link.

After the installation I am not seeing /opt/X11/lib/asan on my drive.

Regards
Alexander

**Comment by jeremyhu** [comment]
wine is not compatible with asan.  See https://llvm.org/bugs/show_bug.cgi?id=25466

**Comment by jeremyhu** [comment]
@mistydemeo ASan is only used for beta builds.  ASan was not used for 2.7.9_rc* and 2.7.9.

**Comment by mistydemeo** [comment]
@jeremyhu Perfect, thanks for the confirmation.

**Comment by mistydemeo** [comment]
Added a warning about beta XQuartz releases.
