### ISSUE TITLE
djvu2pdf: checksum mismatch

### ISSUE THREAD

**Issue by pmer** [Homebrew/homebrew-core#24810]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Issue

To help us debug your issue please explain:
- What you were trying to do (and why)

Install the djvu2pdf formula.

- What happened (include command output)

```
$ brew install djvu2pdf
==> Installing dependencies for djvu2pdf: djvulibre, little-cms2, ghostscript
==> Installing djvu2pdf dependency: djvulibre
==> Downloading https://downloads.sourceforge.net/project/djvu/DjVuLibre/3.5.27/
==> Downloading from https://downloads.sourceforge.net/#!/project/djvu/DjVuLibre
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: e69668252565603875fb88500cde02bf93d12d48a3884e472696c896e81f505f
Actual: 7a07d3f7cca5c0b38ca811984ef8da536da32932d68c1a6cce33ec2462b930bf
Archive: /Users/pdm/Library/Caches/Homebrew/djvulibre-3.5.27.tar.gz
To retry an incomplete download, remove the file above.
```

- What you expected to happen

Chechsums should match, djvu2pdf should be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install djvu2pdf`

## brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

## brew config

HOMEBREW_VERSION: 1.5.8-6-gbc3389b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: bc3389bdae5be31e5447802cb0eb8e1a967f5b4d
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2d0aaa0caf40d5f67a80d80214fa02735481d909
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /Users/pdm/Library/Homebrew
HOMEBREW_REPOSITORY: /Users/pdm/Library/Homebrew
HOMEBREW_CELLAR: /Users/pdm/Library/Homebrew/Cellar
HOMEBREW_CELLAR: /Users/pdm/Library/Homebrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_PREFIX: /Users/pdm/Library/Homebrew
HOMEBREW_REPOSITORY: /Users/pdm/Library/Homebrew
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /Users/pdm/Library/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /Users/pdm/Library/Homebrew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /Users/pdm/Library/Homebrew/opt/python/libexec/bin/python => /Users/pdm/Library/Homebrew/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_101
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: N/A
X11: 2.7.11 => /opt/X11

**Comment by commitay** [comment]
This is a SourceForge issue, see https://github.com/Homebrew/homebrew-core/issues/24691#issuecomment-369733561
