### ISSUE TITLE
"python" formula violates Python standard (PEP 394) by putting python3 on $PATH as "python"

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew-core#24812]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? - https://gist.github.com/anonymous/d4226e834bf246ad40dbd9b80474a855
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Just trying to use Python from Homebrew while using lots of software (much of it "legacy") written in Python.

- What happened (include command output)

`#!/usr/bin/env python` started invoking python 3 rather than python 2 in a fresh shell.

- What you expected to happen

As per [the PEP governing this behavior](https://www.python.org/dev/peps/pep-0394/), 

> - for the time being, all distributions should ensure that python refers to the same target as python2.

I expected `python` to refer to the same target as `python2`, as it both previously has been and is officially documented to be.

- Step-by-step reproduction instructions (by running `brew install` commands)

```console
$ brew install python
. . .
$ python --version
Python 3.6.4
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
please search for dupicates

**Comment by glyph** [comment]
This was a duplicate of https://github.com/Homebrew/homebrew-core/issues/24793 .

@ilovezfs I did search for duplicates, but since the bug is still present I assumed the duplicate would be open.

**Comment by ilovezfs** [comment]
@glyph PR making python and python@2 PEP 394 compliant:
https://github.com/Homebrew/homebrew-core/pull/25060

**Comment by glyph** [comment]
@ilovezfs - thanks for reconsidering, and thanks for the ping. I appreciate the heads up.
