### ISSUE TITLE
protobuf: python is not required, but `brew missing` complains if it's not installed

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-core#24815]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

If I install protobuf, and python is not installed, `brew missing` will complain that python is not installed (and by proxy `brew doctor` will complain).

~~~
$ brew list
$ brew install protobuf
==> Downloading https://homebrew.bintray.com/bottles/protobuf-3.5.1.el_capitan.b
Already downloaded: /Users/jenkins/Library/Caches/Homebrew/protobuf-3.5.1.el_capitan.bottle.tar.gz
==> Pouring protobuf-3.5.1.el_capitan.bottle.tar.gz
==> Caveats
Editor support and examples have been installed to:
  /usr/local/opt/protobuf/share/doc/protobuf
==> Summary
🍺  /usr/local/Cellar/protobuf/3.5.1: 267 files, 17.6MB
$ brew list
protobuf
$ brew missing
readline sqlite gdbm openssl xz python
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gdbm openssl python readline sqlite xz

Run `brew missing` for more details.
~~~

I think this happens because the protobuf `INSTALL_RECEIPT.json` has `--without-python` as an unused option.

~~~
$ brew config
HOMEBREW_VERSION: 1.5.8-6-gbc3389b
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc3389bdae5be31e5447802cb0eb8e1a967f5b4d
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4bca86494fd1fe2f469291613395efb5be9b88a5
Core tap last commit: 29 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.43.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_131, 1.8.0_77
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
~~~

**Comment by ilovezfs** [comment]
Did I mention how much I love install receipts?

**Comment by ilovezfs** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/24825.

**Comment by ilovezfs** [comment]
Thanks for reporting this @scpeters!
