### ISSUE TITLE
mercurial: bash: /usr/local/bin/hg: /usr/local/opt/python@2/bin/python2.7: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by RokerHRO** [Homebrew/homebrew-core#24839]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
   -> "no logs."

**Comment by RokerHRO** [comment]
` brew link --force python@2` seems to help. :-/

**Comment by ilovezfs** [comment]
You need to run`brew upgrade`.

**Comment by mrkhoa99** [comment]
We should try to upgrade Mercurial as well: `brew upgrade mercurial`

**Comment by ilovezfs** [comment]
@mrkhoa99 `brew upgrade` upgrades everything outdated ... including mercurial.

**Comment by mrkhoa99** [comment]
@ilovezfs yes, I agreed with that. Just one more question, after upgrading my Python version from 2 to 3, my mercurial didn't work. Seem that in this case, we need to run mercurial upgrade or brew upgrade? I tried with mercurial upgrade only. I worked fine.
