### ISSUE TITLE
python@2 contends with Python 3 (python package) over unversioned `python` symlinks

### ISSUE THREAD

**Issue by triplepoint** [Homebrew/homebrew-core#24830]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# Gist Logs
- `python@2` gist-log
https://gist.github.com/73b0c63624fb1eb324c3b29066e17da9
- `python` gist-log
https://gist.github.com/01b45a64d52f8ee1f3cf6e5fd7f492e7

# Report
The documentation at https://docs.brew.sh/Homebrew-and-Python states:
```
python and python3 point to Homebrew’s Python 3.x (if installed) otherwise the macOS system Python
python2 points to Homebrew’s Python 2.7.x (if installed)
pip and pip3 point to Homebrew’s Python 3.x’s pip (if installed)
pip2 points to Homebrew’s Python 2.7.x’s pip (if installed)
```

Installing both the `python` and `python@2` packages does not result in the above mapping. 
 Instead:
- `python`   -> `/usr/local/opt/python@2/libexec/bin/python`
- `python2` -> Does Not Exist
- `python3` -> `/usr/local/bin/python3`
- `pip` -> `/usr/local/opt/python@2/libexec/bin/pip`
- `pip2` -> Does Not Exist
- `pip3` -> `/usr/local/bin/pip3`

# Procedure
## Uninstall all Python packages
```
$ brew uninstall python python@2 python3
.......

$ brew list|grep python    $ returns no results

$ which python python2 python3 pip pip2 pip3
/usr/bin/python
python2 not found
python3 not found
pip not found
pip2 not found
pip3 not found

$ where python python2 python3 pip pip2 pip3
/usr/bin/python
```

## Install Python 3 (the `python` brew package)
```
$ brew install python
....

$ where python python2 python3 pip pip2 pip3
/usr/local/bin/python        # is python3
/usr/bin/python
/usr/local/bin/python3
/usr/local/bin/pip              # is pip3
/usr/local/bin/pip3

$ which python python2 python3 pip pip2 pip3
/usr/local/bin/python
python2 not found
/usr/local/bin/python3
/usr/local/bin/pip
pip2 not found
/usr/local/bin/pip3
```

## Install Python 2
```
$ brew install python@2
...

# Modify the shell path in `~/.zshrc` as stated in the package notes:
# export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
# open a new terminal to take effect (following continues in new terminal)

$ where python python2 python3 pip pip2 pip3
/usr/local/opt/python@2/libexec/bin/python
/usr/local/bin/python
/usr/bin/python
/usr/local/bin/python3
/usr/local/opt/python@2/libexec/bin/pip
/usr/local/bin/pip
/usr/local/bin/pip3

$ which python python2 python3 pip pip2 pip3
/usr/local/opt/python@2/libexec/bin/python
python2 not found
/usr/local/bin/python3
/usr/local/opt/python@2/libexec/bin/pip
pip2 not found
/usr/local/bin/pip3
```

The `python2` and `pip2` symlinks were expected to be present, and are not.  In addition, the `python` and `pip` symlinks are directed to the python 2 path, and not the expected python 3 path.

**Comment by commitay** [comment]
This puts `python@2` in your PATH as `python`, `pip` , etc.
```
If you wish to have this formula's python executable in your PATH then add
the following to ~/.zshrc:
  export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
```
```
$ which -a python pip
/usr/local/opt/python@2/libexec/bin/python
/usr/local/bin/python
/usr/bin/python
/usr/local/opt/python@2/libexec/bin/pip
/usr/local/bin/pip
```
____
 This will put `python@2` in your path as `python2`, `pip2`, etc.
```
If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.zshrc
```
```
$ which -a python pip
/usr/local/bin/python
/usr/bin/python
/usr/local/bin/pip

$ which -a python2 pip2
/usr/local/opt/python@2/bin/python2
/usr/local/opt/python@2/bin/pip2
```

**Comment by triplepoint** [comment]
If that's the case, then the package's documentation is not sufficient to explain distinction:

```
This formula installs a python2 executable to /usr/local/opt/python@2/bin
If you wish to have this formula's python executable in your PATH then add
the following to ~/.zshrc:
  export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@2/bin:$PATH"' >> ~/.zshrc
```

`If you wish to have this formula's python executable in your PATH then add
the following to ~/.zshrc` vs `If you need to have this software first in your PATH run:` sounds very much like the same thing, and does not at all make clear the relationship between the `python`, `python2`, and `python3` commands.

**Comment by rdonkin** [comment]
The docs at https://docs.brew.sh/Homebrew-and-Python seem out of date  compared to `brew info python` (installed 3.6.4).

The docs say that `/usr/local/bin/python` points to Python 2.7:

> `python` points to Homebrew’s Python 2.7.x (if installed) otherwise the macOS system Python. Check out `brew info python` if you wish to add Homebrew’s 3.x `python` to your PATH.

`brew info python` says that `python` points to `python3`, which is correct (see 2nd to last paragraph):

> ==> Caveats
> Pip, setuptools, and wheel have been installed. To update them
>     pip3 install --upgrade pip setuptools wheel
> 
> You can install Python packages with
>     pip3 install <package>
> 
> They will install into the site-package directory
  /usr/local/lib/python3.6/site-packages
> 
> See: https://docs.brew.sh/Homebrew-and-Python
> 
> Unversioned symlinks python, python-config, pip etc. pointing to python3,
python3-config, pip3 etc., respectively, have been installed.
> 
> If you need Homebrew's Python 2, `brew install python@2`.

Given discussion in this issue, I think the docs need to be fixed, particularly since the caveats link to them.

**Comment by ilovezfs** [comment]
`python` formula != `/usr/local/bin/python`. The docs are correct as is.

The `python` formula installs the latest version of Python, which is Python 3. Upstream wishes the binary for Python 3 to be named `python3`, which is installed as `/usr/local/bin/python3`.

The `python@2` formula installs something other than the latest version of Python (hence the `@`), which is Python 2.7. Upstream wish the binary for Python 2 to be named `python`, which is installed as `/usr/local/bin/python`. Upstream also wishes the binary for Python 2 to be available as `python2`. This is installed as `/usr/local/bin/python2`.

**Comment by rdonkin** [comment]
OK, I'm on 3.6.4 which has the caveats text quoted.

The 3.6.5 setup seems better to avoid breaking lots of existing Python 2 code with shebang lines such as `/usr/bin/env python`.
