### ISSUE TITLE
Installing bandcamp-dl installs wrong version

### ISSUE THREAD

**Issue by nrlquaker** [Homebrew/homebrew-core#24855]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Installing [bandcamp-dl](https://github.com/Homebrew/homebrew-core/blob/b7e81b52d0578332569ca40c71754710746ba6be/Formula/bandcamp-dl.rb)
```
brew install bandcamp-dl
```
 installs `0.0.8-09`, not `0.0.8-10` as specified in formula. Installing with --HEAD option
```
brew install bandcamp-dl --HEAD
```
installs proper version.

**Comment by SMillerDev** [comment]
This is an issue with the tag from bandcamp-dl. If you look at the tag commit https://github.com/iheanyi/bandcamp-dl/releases/tag/v0.0.8-10 you'll see that it points to a commit that changes the version to 0.0.8-09. And in the git repo this has been fixed with a force push, thus resulting in homebrew reporting the version correctly when using `--HEAD`.

If you can report this at https://github.com/iheanyi/bandcamp-dl/ homebrew can make a new release when the tag is fixed.

**Comment by nrlquaker** [comment]
@SMillerDev Good catch. I've opened an [issue](iheanyi/bandcamp-dl#141).

**Comment by SMillerDev** [comment]
Link is broken, this one is correct: https://github.com/iheanyi/bandcamp-dl/issues/141

**Comment by MikeMcQuaid** [comment]
Closing as an upstream issue.

**Comment by ilovezfs** [comment]
This will be fixed via https://github.com/Homebrew/homebrew-core/pull/24861.
