### ISSUE TITLE
Does the getmail formula need an update in light of python migration?

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew-core#24875]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Now that python3 is the default python interpreter for Homebrew, getmail has some issues. Since upgrading python to be python3 and having python2 moved to a keg-only formula, I'm seeing these warnings when I call getmail inside mutt:

    File "/usr/local/bin/getmail", line 64
         except ImportError, o:
                           ^
    SyntaxError: invalid syntax

These are only warnings—i.e., the getmail command still works—but I can't be sure how long that will last or how reliable it is.

Does the getmail formula need to be adjusted in some way to call the right python? I looked at the mercurial formula, but it's not quite clear to me what to do for a pull request here.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/24879

**Comment by CryoRenegade** [comment]
Reference: https://discourse.brew.sh/t/getmail-throws-warnings-since-python-2-3-changes-solved/1774/8
