### ISSUE TITLE
Consider adding python2 and pip2 automatically to PATH with python@2

### ISSUE THREAD

**Issue by mc10** [Homebrew/homebrew-core#24873]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (N/A)

Gist link: https://gist.github.com/16af2a4f4b0469ab5c65a6d17fb424f8

I know that `brew info python@2` gives recommendations for adding `python2`, `pip2`, etc. to the `PATH`, but it'd be nice if they were automatically added, as these aliases do not clash with the system Python install. Also, it's a bit confusing that `brew info` has the following messages:
```
Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>
```
when `pip2` cannot be used.

**Comment by blixt** [comment]
Furthermore, I followed the instructions in the caveat, which is to add `/usr/local/opt/python@2/libexec/bin` to PATH, however this causes different behaviors depending on order of PATH, because that directory does not contain `python2` symlinks, but `python` ones:

```
$ ls -la /usr/local/opt/python@2/libexec/bin
total 0
drwxr-xr-x  12 blixt  admin  384 Mar  6 15:21 .
drwxr-xr-x   6 blixt  admin  192 Mar  6 15:21 ..
lrwxr-xr-x   1 blixt  admin   16 Mar  6 15:21 2to3 -> ../../bin/2to3-2
lrwxr-xr-x   1 blixt  admin   26 Mar  6 15:21 easy_install -> ../../bin/easy_install-2.7
lrwxr-xr-x   1 blixt  admin   15 Mar  6 15:21 idle -> ../../bin/idle2
lrwxr-xr-x   1 blixt  admin   14 Mar  6 15:21 pip -> ../../bin/pip2
lrwxr-xr-x   1 blixt  admin   16 Mar  6 15:21 pydoc -> ../../bin/pydoc2
lrwxr-xr-x   1 blixt  admin   17 Mar  6 15:21 python -> ../../bin/python2
lrwxr-xr-x   1 blixt  admin   24 Mar  6 15:21 python-config -> ../../bin/python2-config
lrwxr-xr-x   1 blixt  admin   18 Mar  6 15:21 pythonw -> ../../bin/pythonw2
lrwxr-xr-x   1 blixt  admin   19 Mar  6 15:21 smtpd.py -> ../../bin/smtpd2.py
lrwxr-xr-x   1 blixt  admin   16 Mar  6 15:21 wheel -> ../../bin/wheel2
```

**Comment by acecilia** [comment]
As @blixt said, if you follow the instructions in the caveat, in MacOS you will get:
- `python3`, pointing to python3
- `python` pointing to homebrew python (this also depends on the order of your `PATH`, it may be a different behavior)
- `python2`: command not found

The caveat says: 

    This formula installs a python2 executable to /usr/local/opt/python@2/bin
    If you wish to have this formula's python executable in your PATH then add
    the following to ~/.bash_profile:
    export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"

But what you really need to add to your ~/.bash_profile file in order to have `python2` working is:

    export PATH="/usr/local/opt/python@2/bin:$PATH"

Furthermore, in my personal case I was using Xcode as my IDE, which was previously looking for python2 (and finding it) under `/usr/local/bin/python3`. After I updated python this morning, due to the change of path installation, Xcode is failing to build my project because `python2` is not found anymore under `/usr/local/bin/python2`. I guess others are in similar situation, and I do not see the point of this change in the formulae.
