### ISSUE TITLE
Russians started Bullying Campaign Against You!

### ISSUE THREAD

**Issue by saniv** [Homebrew/homebrew-core#24882]
They use boards, like 4chan, to coordinate assault:
https://dis.tinychan.org/read/prog/1520261535

I'm sorry for my compatriots, Mike. They misread "github" as "gulag".

**Comment by stychos** [comment]
I think you misread "github" as "asulym". Go take some fresh air.

**Comment by MikeMcQuaid** [comment]
@saniv I'd rather not know.
