### ISSUE TITLE
Brew removed /usr/local/bin/python3

### ISSUE THREAD

**Issue by onlynone** [Homebrew/homebrew-core#24880]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

gist-logs:
 * [python](https://gist.github.com/2c56b168938ec9e688edeca4c0091381)
 * [python2](https://gist.github.com/237ceb2f1cf628e291439a336c473c79)
 * [python3](https://gist.github.com/55e1e29c9235826cbc5553ee36df42c9) (This appears to be the same as the python gist-log, I couldn't figure out a way to get it for python3)

To help us debug your issue please explain:
- What you were trying to do (and why)

   Run a script with `#!/usr/bin/env python3`.

- What happened (include command output)

   `env: python3: No such file or directory`

- What you expected to happen

   env to have found python3 and exec'd it

- Step-by-step reproduction instructions (by running `brew install` commands)

   I believe I installed another formula recently which I guess triggered a brew update/upgrade and that removed python3.

## Notes:

I no longer have a plain `/usr/local/bin/python` nor a `/usr/local/bin/python3`. I still have `/usr/local/bin/python2` and `python2.7`. I do still have several `3.x` directories under `/usr/local/Cellar/python`

It seems like I previously had `python` and `python3` formulas installed, and now I only have `python@2` installed. It seems to me that if the `python` formula is now the 3.x version, then users who had installed `python3` in the past should have automatically had `python` installed after the switch.

**Comment by MikeMcQuaid** [comment]
Try to run `brew upgrade` and let us know if you can reproduce this. If you can please paste the output of `brew list --versions | grep python` and `echo $PATH`. Thanks!

**Comment by onlynone** [comment]
Yeah, the upgrade worked. It just seems like if the user explicitly had `python3` installed prior to installing an unrelated package, it would be desirable to make sure the latest `python` is installed `@3`. Though I could see how that would cause problems when `/usr/local/bin/python` goes from py2 to py3 without the user explicitly asking for it. But it's either that unexpected behavior *or* the unexpected behavior of `/usr/local/bin/python3` suddenly going missing.

Or (as I would have preferred), have the `python@2` formula create `/usr/local/bin/python` and `python2*`. And have the `python` formula create `/usr/local/bin/python3*` only. But you're already fighting that battle elsewhere, so I won't push that here. Though I did see you say you were aware of the PEP covering the naming situation, but not your reasoning for ignoring it. It might be nice to read that rationale.

**Comment by MikeMcQuaid** [comment]
> It might be nice to read that rationale.

`brew install python` should install a `python` binary for the end-user.
