### ISSUE TITLE
autoconf: autoreconf doesn't work with brewed perl

### ISSUE THREAD

**Issue by larseggert** [Homebrew/homebrew-core#24909]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

gist-logs:
* `Error: No logs.`

brew config:
```
HOMEBREW_VERSION: 1.5.8-26-g6c203f9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6c203f9372787393fc0ad2f2b8ddb72a500ce410
Last commit: 15 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: afa9f3edb36523561fe918daec9cdb5d72ece461
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: 1.8.0_144, 1.8.0_141, 1.8.0_131
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

brew doctor:
* `Your system is ready to brew.`

To help us debug your issue please explain:
- What you were trying to do (and why)

Tried to run `autoreconf -i`.

- What happened (include command output)
```
# autoreconf -i
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /usr/local/perl/lib/perl5/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /usr/local/perl/lib/perl5/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: flat namespace
```

- What you expected to happen

Expected `autoreconf` to execute.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
# brew install autoconf perl
# autoreconf -i
```

This issue also affects other `automake` scripts, due to hardcoded perl paths of `/usr/bin/perl`.

**Comment by resistor4u** [comment]
I see the pull request is still open, but do you have suggestions for a fix in the meantime? it's tempting to change `#! /usr/bin/perl -w` to `#! /usr/local/bin/perl -w`, but I imagine that's not ideal.
