### ISSUE TITLE
thefuck is missing dependencies and will soon drop Python 3 support 

### ISSUE THREAD

**Issue by thedrow** [Homebrew/homebrew-core#24910]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/anonymous/bc90f4ed4642608e65be38a9b3815f7c
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Upgrade to a new version of thefuck
- What happened (include command output): Installation was successful but when opening a new shell I get the following:
```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/thefuck", line 8, in <module>
    from thefuck.entrypoints.main import main
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/entrypoints/main.py", line 2, in <module>
    from ..system import init_output
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/system/__init__.py", line 7, in <module>
    from .unix import *  # noqa: F401,F403
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/system/unix.py", line 49, in <module>
    from pathlib2 import Path
ImportError: No module named pathlib2
```
After installing pathlib2 on my Homebrew installed Python I get the following traceback:
```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/thefuck", line 8, in <module>
    from thefuck.entrypoints.main import main
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/entrypoints/main.py", line 12, in <module>
    from .fix_command import fix_command  # noqa: E402
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/entrypoints/fix_command.py", line 5, in <module>
    from .. import logs, types, const
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/types.py", line 10, in <module>
    from .output_readers import get_output
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/output_readers/__init__.py", line 2, in <module>
    from . import read_log, rerun
  File "/home/linuxbrew/.linuxbrew/Cellar/thefuck/3.25_2/libexec/lib/python2.7/site-packages/thefuck/output_readers/read_log.py", line 6, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named backports.shutil_get_terminal_size
```
This indicates that both the pathlib2 and the backports.shutil_get_terminal_size packages are missing from the dependencies of the newest thefuck version.

After installing both of them, I get the following warning:
```
[WARN] The Fuck will drop Python 2 support soon, more details https://github.com/nvbn/thefuck/issues/685
```
- What you expected to happen: Installation should install both packages and use Python 3 instead of Python 2.
- Step-by-step reproduction instructions (by running `brew install` commands):
```
brew install thefuck
eval $(thefuck --alias)
```
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew.

**Comment by thedrow** [comment]
@ilovezfs The problem is the same problem though. The formula in this repository is wrong and they update their formulas from your repository.
I'm sure this is also a bug with Homebrew. Can you please reopen this issue?

**Comment by ilovezfs** [comment]
In Homebrew/homebrew-core the virtualenv is using python 3. Some Homebrew/brew fixes have probably not been backported to Linuxbrew.

**Comment by thedrow** [comment]
So python is now python3? https://github.com/Homebrew/homebrew-core/blob/master/Formula/thefuck.rb#L18
In which case I'm guessing the missing dependencies won't be needed.

**Comment by ilovezfs** [comment]
Correct :)

**Comment by thedrow** [comment]
Right, I'll report this on Linuxbrew. Thank you for the information.
