### ISSUE TITLE
brew migrate python fails because of python 2.7.14_3

### ISSUE THREAD

**Issue by saagarjha** [Homebrew/homebrew-core#24926]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### brew config
```
HOMEBREW_VERSION: 1.5.8-26-g6c203f9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6c203f9372787393fc0ad2f2b8ddb72a500ce410
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4ab1fef0739f7ba2b407284605c49a6101f1c3c
Core tap last commit: 60 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
GCC-4.2: build 5666
Clang: 9.1 build 902
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.0_2/bin/ruby
Java: 9.0.4, 1.8.0_162
macOS: 10.13.4-x86_64
Xcode: 9.3 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

(There's a bunch of python issues open right now, so this might be a duplicate of one of them. I couldn't find anything with a quick search, however.)
I'm was having an issue during `brew update` where it was trying to perform a rename of python3 and failing. A quick investigation showed that the failing set was `brew migrate python`:

```shell
$ brew migrate python
==> Processing python3 formula rename to python
==> Unlinking python3
==> Moving python3 versions to /usr/local/Cellar/python
==> Relinking python
Error: An unexpected error occurred during linking
Cannot link python
Another version is already linked: /usr/local/Cellar/python/2.7.14_3
Error: Error occurred while migrating.
Cannot link python
Another version is already linked: /usr/local/Cellar/python/2.7.14_3
Backing up...
```

Apparently, I have python 2.7.14_3 installed (from 6a70b7dc8ed40c86c9dc976ff35b7829bc408fdd?), but the latest python now is 2.7.14_1 (from 034dab6e4b18ffd88cc70be1378a7a9d83d666cb I believe). This makes this step hard because I don't think homebrew understands that I have 2.7.14_3 installed:

```
$ brew info python@2
python@2: stable 2.7.14 (bottled), HEAD [keg-only]
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@2/2.7.14_1 (3,527 files, 48.6MB)
  Poured from bottle on 2018-03-06 at 12:10:35
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@2.rb
==> Dependencies
Build: sphinx-doc ✔, pkg-config ✔
Required: openssl ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: sphinx-doc ✔, tcl-tk ✘, berkeley-db@4 ✘
…
```

**Comment by quantumproducer** [comment]
`brew install python3` failed for me, and it referenced this issue. Here's my log:

```
# Sphinx version: 1.7.1
# Python version: 2.7.10 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/lib/python2.7/site-packages/sphinx/application.py", line 187, in __init__
    self.setup_extension(extension)
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/lib/python2.7/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/lib/python2.7/site-packages/sphinx/builders/linkcheck.py", line 20, in <module>
    from requests.exceptions import HTTPError
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/vendor/lib/python2.7/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/Cellar/sphinx-doc/1.7.1/libexec/vendor/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 124, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

**Comment by fxcoudert** [comment]
@quantumproducer please open a separate issue for your problem, and fill out the entire template so we can help

**Comment by acecilia** [comment]
@saagarjha Update brew and try again. During the last 10 days there were several bugs + issues with `python2` and `python3` formulaes. A fix to the formulaes was introduced 2 days ago [here](https://github.com/Homebrew/homebrew-core/pull/25060), and the docs were also updated [here](https://github.com/Homebrew/brew/pull/3902). You can read them at https://docs.brew.sh/Homebrew-and-Python, where the actual setup with `python2` and `python3` is explained.

**Comment by saagarjha** [comment]
Hmm, I've updated and the original issue is gone. However, it looks like this change breaks things that depend on the system Python, so I think I'll file a separate issue for that.
