### ISSUE TITLE
Unsupported special dependency: perl

### ISSUE THREAD

**Issue by maharlikans** [Homebrew/homebrew-core#2494]
I got this error about a special dependency with perl that seemed to fail. Not getting any errors except for this one from 'brew doctor'.

Error: Unsupported special dependency :perl
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
/usr/local/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:61:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:155:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1859:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1859:in `each'
/usr/local/Library/Homebrew/formula.rb:1859:in `depends_on'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:42:in `<class:Vim>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/vim.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:167:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:226:in `from_rack'
/usr/local/Library/Homebrew/diagnostic.rb:1268:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Library/Homebrew/diagnostic.rb:1265:in `reject'
/usr/local/Library/Homebrew/diagnostic.rb:1265:in `check_for_unlinked_but_not_keg_only'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:84:in `<main>'

**Comment by DomT4** [comment]
Does this reproduce or is it a one-off error?

**Comment by ilovezfs** [comment]
presumably this means it's been a while since brew update was run, since :perl is pretty new

**Comment by DomT4** [comment]
Yeah, that's typically the issue. If it doesn't reproduce more than once it's not an issue _per se_, just an annoying quirk.

**Comment by maharlikans** [comment]
It reproduces, but it just happens when I run 'brew doctor' each time. I don't see it elsewhere.

**Comment by DomT4** [comment]
Can you provide your `brew config`? Thanks.

**Comment by maharlikans** [comment]
Here we go: 

HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: da06e813c2b8925499484ff8be7772f6aa6ae9e3
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: db601d6f4ae41501982f2f7cfe48082ab73c1e64
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Clang: 7.3 build 703
Git: 2.9.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: N/A
System Ruby: 2.0.0-p648
OS X: 10.11.5-x86_64
Xcode: 7.3
CLT: N/A
X11: 2.7.9 => /opt/X11

**Comment by maharlikans** [comment]
Hmm... actually it looks okay now. Yesterday running brew doctor, it was reproducing, but now it seems okay. Maybe we can close this?

**Comment by DomT4** [comment]
I'm not sure how long it had been since you'd previously updated, but there's a known issue around very old Homebrew's updating that can require a couple of `brew update`s to shake off. Not sure if that was the cause here, but if you're no longer seeing the problem I guess we can close, yeah.

**Comment by nepalez** [comment]
```
Error: Unsupported special dependency :perl
Please report this bug:
    https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:123:in `parse_symbol_spec'
~/.linuxbrew/Library/Homebrew/compat/dependency_collector.rb:17:in `parse_symbol_spec'
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:61:in `build'
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:48:in `fetch'
~/.linuxbrew/Library/Homebrew/dependency_collector.rb:38:in `add'
~/.linuxbrew/Library/Homebrew/software_spec.rb:155:in `depends_on'
~/.linuxbrew/Library/Homebrew/formula.rb:1862:in `block in depends_on'
~/.linuxbrew/Library/Homebrew/formula.rb:1862:in `each'
~/.linuxbrew/Library/Homebrew/formula.rb:1862:in `depends_on'
~/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:34:in `<class:Openssl>'
~/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb:1:in `load_formula'
~/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
~/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
~/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
~/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
~/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
~/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
~/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
~/.linuxbrew/Library/Homebrew/dependency.rb:32:in `to_formula'
~/.linuxbrew/Library/Homebrew/dependency.rb:93:in `block in expand'
~/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
~/.linuxbrew/Library/Homebrew/dependencies.rb:9:in `each'
~/.linuxbrew/Library/Homebrew/dependency.rb:80:in `expand'
~/.linuxbrew/Library/Homebrew/formula.rb:1223:in `recursive_dependencies'
~/.linuxbrew/Library/Homebrew/requirement.rb:196:in `expand'
~/.linuxbrew/Library/Homebrew/formula.rb:1229:in `recursive_requirements'
~/.linuxbrew/Library/Homebrew/formula_installer.rb:313:in `expand_requirements'
~/.linuxbrew/Library/Homebrew/formula_installer.rb:263:in `compute_dependencies'
~/.linuxbrew/Library/Homebrew/formula_installer.rb:130:in `verify_deps_exist'
~/.linuxbrew/Library/Homebrew/formula_installer.rb:123:in `prelude'
~/.linuxbrew/Library/Homebrew/cmd/install.rb:231:in `install_formula'
~/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `block in install'
~/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `each'
~/.linuxbrew/Library/Homebrew/cmd/install.rb:93:in `install'
~/.linuxbrew/Library/brew.rb:84:in `<main>'
```

And brew config:

```
HOMEBREW_VERSION: 0.9.8
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: eec5059563a483a674ecabe01a3cec43811fa0d7
Last commit: 3 месяца назад
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 45f9b2181833778b63bf1e480341d8c23445a731
Core tap last commit: 3 дня назад
HOMEBREW_PREFIX: ~/.linuxbrew
HOMEBREW_REPOSITORY: ~/.linuxbrew
HOMEBREW_CELLAR: ~/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 8-core 64-bit broadwell
Kernel: Linux 3.19.0-32-generic x86_64 GNU/Linux
OS: Linux Mint 17.3 Rosa
Codename: rosa
OS glibc: 2.19
OS gcc: 4.8.4
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Clang: 3.4 build 0
X11: 2.7.8 => /usr
System Ruby: 2.3.1 => ~/.rvm/rubies/ruby-2.3.1/bin/ruby
Perl: /usr/bin/perl
Python: ~/Программы/anaconda3/bin/python => ~/Программы/anaconda3/bin/python3.5
Ruby: ~/.rvm/rubies/ruby-2.3.1/bin/ruby
Java: 1.8.0_101
```

**Comment by DomT4** [comment]
Linuxbrew stuff should be reported to Linuxbrew, but again, unless you see it more than once I wouldn't worry about it.

**Comment by vinodakumar** [comment]
Hi Update your brew and install nodejs  then it will works 
$ brew update

**Comment by voicenter** [comment]
the $ brew update work for me to ,
thanks
