### ISSUE TITLE
Yara, pcre lib missing

### ISSUE THREAD

**Issue by nyx0** [Homebrew/homebrew-core#2499]
I saw that in a recent patch #2078 the dependency `pcre` was removed. 
But when I install yara and I launch it, I get this error:
```
$  yara --help
dyld: Library not loaded: /usr/local/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/yara
  Reason: image not found
Trace/BPT trap: 5

$ otool -Lv "$(which yara)"
/usr/local/bin/yara:
	/usr/local/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.5.0)
	time stamp 2 Thu Jan  1 00:00:02 1970
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
	time stamp 2 Thu Jan  1 00:00:02 1970
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	time stamp 2 Thu Jan  1 00:00:02 1970
```
I fixed the bug with `brew install pcre`
So my question is do I need to put the `pcre` dependency again in the formula or I'm missing something?
cc @plusvic

**Comment by plusvic** [comment]
How did you install yara? Did you use brew to install it? It's a fresh installation?

**Comment by nyx0** [comment]
Yes fresh install with `brew install yara`

**Comment by rakkesh** [comment]
Looks to me that a Homebrew bottle was not generated on merging https://github.com/Homebrew/homebrew-core/pull/2078. 

You can reinstall the formula with,
`$ brew reinstall --build-from-source yara`

**Comment by DomT4** [comment]
Good spot @rakkesh, appreciate you noticing that. I've left a gentle nag in the cross-channel chat about our over-eagerness to use the merge button, this has happened a few times lately 🙈.

Pulled a new bottle in https://github.com/Homebrew/homebrew-core/commit/b96ca76661eb3f71cd841aaa52927852f2b1f242. `brew update && brew reinstall yara` should fix it now. Apologies that this happened.
