### ISSUE TITLE
PHP 7.2.3_1 /_2 - libphp7.so missing

### ISSUE THREAD

**Issue by black-snow** [Homebrew/homebrew-core#25018]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question.
- [-] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? 
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? `https://gist.github.com/black-snow/e779400d4f133f34a67c73f6ae7efdb3`
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**What you were trying to do (and why)**
Just update `php72` without any other changes.

**What happened (include command output)**
`php72` was updated - libexec is missing.

**What you expected to happen**
I expected my existing `libphp7.so` not to vanish. `brew reinstall php72 --with-httpd` resulted in:
> Warning: php: this formula has no --with-httpd option so it will be ignored!

`brew options php72` is empty

**Step-by-step reproduction instructions (by running `brew install` commands)**

Have an existing `php72` install `--with-httpd` - i. e. before 7.2.3_1
`brew update && brew upgrade` to 7.2.3_1 or 7.2.3_2
See that apache won't start anymore. `apachectl` reveals that the libphp7.so is gone.

**Comment by ilovezfs** [comment]
The httpd bits and most other options are now included by default. The --with-foo brew options for php no longer exist because they're not needed for you to get that functionality.

**Comment by black-snow** [comment]
@ilovezfs Thanks for the quick reply.
I then wonder why the `libphp7.so` is not created.

**Comment by black-snow** [comment]
@ilovezfs please reopen the issue - it's not solved for me
`libephp7.so` is not created

**Comment by black-snow** [comment]
Found the `lbphp7.so` under `/usr/local/Cellar/php/7.2.3_2/lib/httpd/modules/libphp7.so`.
Would've been nice to know such changes before they were made.

**Comment by black-snow** [comment]
Found the `lbphp7.so` under `/usr/local/Cellar/php/7.2.3_2/lib/httpd/modules/libphp7.so`.
Would've been nice to know such changes before they were made.

Changed the config to: `LoadModule php7_module /usr/local/opt/php72/lib/httpd/modules/libphp7.so`

Wonder if `brew-php-switcher` works with the new path.

**Comment by jimblue** [comment]
Have the same issue! Why changing the path with notice user...
