### ISSUE TITLE
libwebsockets 2.4.2 was released yesterday, but has been re-tagged this morning. Brew is serving the old version.

### ISSUE THREAD

**Issue by srgb** [Homebrew/homebrew-core#25017]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):
A libwebsockets release (2.4.2) was released yesterday that got picked up here: https://github.com/Homebrew/homebrew-core/pull/24999/commits/9fdbcfcf151cf977d57b5bd7d6ea960d7a7e97d9
However, there was a bug in that release and libwebsockets has since re-tagged the same version this morning. The current built brew version has the bug in that, meaning clients cannot connect to websockets.

- What happened (include command output)
brew functions correctly
- What you expected to happen
brew functions correctly, but an incorrect version is installed
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install libwebsockets

Based on https://github.com/Homebrew/homebrew-core/pull/24999/commits/9fdbcfcf151cf977d57b5bd7d6ea960d7a7e97d9
I think the sha256 needs updating to `73012d7fcf428dedccc816e83a63a01462e27819d5537b8e0d0c7264bfacfad6`

I'm happy to update the libwebsockets.rb formula and submit a pull request, but I'm not sure if there is an automated process that would do this already, sorry for my ignorance.

**Comment by fxcoudert** [comment]
We will need confirmation from upstream that the retag is intentional.

(Releasing different content under the same version number really defeats the purpose of having a version system at all…)

**Comment by srgb** [comment]
Completely understand - this issue comment shows what has happened if that helps... https://github.com/warmcat/libwebsockets/pull/1201#issuecomment-371448049

**Comment by joelittlejohn** [comment]
@lws-team could you confirm the retag?

**Comment by lws-team** [comment]
Yes it's intentional.

> We will need confirmation from upstream that the retag is intentional.

> (Releasing different content under the same version number really defeats the purpose of having a version system at all…)

The original tag was never announced and lasted a few hours before @joelittlejohn saw his push had a problem.  Although it's called the "insane" way :-) this is a documented way to do things, see "On Re-tagging":

https://git-scm.com/docs/git-tag

**Comment by joelittlejohn** [comment]
@fxcoudert I've pushed #25059 to address this.

**Comment by fxcoudert** [comment]
> Although it's called the "insane" way :-) this is a documented way to do things

Well, yes, it's documented. Deleting your whole repo is also documented :)
Doesn't mean it's good practice.
