### ISSUE TITLE
mailhog is not truly building 0.2.0 version

### ISSUE THREAD

**Issue by swrobel** [Homebrew/homebrew-core#2501]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

The [mailhog formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mailhog.rb) downloads the correct 0.2.0 version of the archive from github, but then downloading outdated versions of the deps, such as [Mailhog](https://github.com/mailhog/MailHog/commit/91a9d8afe119dc96a6c9acfa94c997765c824908), [Mailhog-UI](https://github.com/mailhog/MailHog-UI/commit/ebdfa0f91fac40169ca376953d7c13f9d83cd01a) and [Mailhog-Server](https://github.com/mailhog/MailHog-Server/commit/1dfb973b724a309c18474fe032b1458c0d8654fc).

I would submit a PR to update these, but:

1. I'm not very familiar with the Go build process
2. I'm not sure what @maijs's rationale was for locking to these specific versions, especially when it comes to external deps (it seems obvious to me that the Mailhog ones should be locked to their respective version tags)

**Comment by dunn** [comment]
Usually we use the latest revision of a dependency since Go often just pulls `HEAD`; but it looks like the dependency revisions weren't updated with the 2.0 release.  So a PR to bump the revisions to either their latest or to a corresponding 0.2.0 tag would be great!

**Comment by DomT4** [comment]
I looked into this the other night & fell down a deep, deep rabbithole. It turns out we've added some dependencies as `go_resource`s, but not all, but if you add them all it doesn't compile. It'd be _really_ nice if upstream moved over to the vendor system here really.

**Comment by maijs** [comment]
@swrobel The specific revisions were locked because with the most recent versions of external dependencies MailHog would not build, at least at the time the formula was created.

**Comment by swrobel** [comment]
@maijs I was afraid of that. I've filed a [related issue](https://github.com/mailhog/MailHog/issues/100) with Mailhog about the complicated build process

In the interim, how does everyone feel about using the [prebuilt binaries](https://github.com/mailhog/MailHog/releases) that mailhog offers?

**Comment by maijs** [comment]
@swrobel I haven't used prebuilt binaries on a Mac, but they do work out-of-box on Ubuntu.

**Comment by swrobel** [comment]
amd64 build is working great for me on 2 separate macs

**Comment by MikeMcQuaid** [comment]
We don't use prebuilt binaries in Homebrew. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by DomT4** [comment]
Given the problematic upstream build process I'd lean towards either removing from Homebrew completely, accepting the status quo with outdated resources or removing from `core` and moving to `binary`.
