### ISSUE TITLE
minetest 0.4.x no longer getting added to /Applications with brew install minetest

### ISSUE THREAD

**Issue by Megaf** [Homebrew/homebrew-core#25019]
Related https://github.com/minetest/minetest.github.io/pull/119

Issue as described in topic.
brew linkapps will actually add the .app to /Applications though this should be included in the formula, or something like that.

@ilovezfs

**Comment by DomT4** [comment]
`brew linkapps` is deprecated, so, that's not advice that should be passed on upstream, FWIW.

**Comment by Megaf** [comment]
@DomT4 We do know that. That's why I am here, we need to fix the formulas so a deprecated command is not necessary.

Unfortunately I don't eve know where to start to fix the formula.

Thanks for coming round.

**Comment by Megaf** [comment]
@DomT4 We do know that, however that is the only way of making it work for now.
That's why I'm here, we need to update and improve the formulas so a deprecated command is no longer necessary.

I do not know how to do that however and I'd like someone here to improve the formula, if possible.

Thank you.

**Comment by fxcoudert** [comment]
Homebrew formulas won't install things in `/Applications`, but store them in `/usr/local`. This is the desired behaviour. Quoting from the (deprecated) `brew linkapps` usage information:

> Unfortunately brew linkapps cannot behave nicely with e.g. Spotlight using
> either aliases or symlinks and Homebrew formulae do not build "proper" .app
> bundles that can be relocated. **Instead, please consider using brew cask and
> migrate formulae using .apps to casks.**

**Comment by Megaf** [comment]
@fxcoudert Why did you close the issue? Issue still pretty much present.
If we have to move Minetest to a cask to be it. I can't do it, I am reporting the issue.

We already now that brew won't install things to /Applications, that's what this issue is about. 
So @fxcoudert, can you please actually provide some useful help instead of just closing the issue?

**Comment by fxcoudert** [comment]
The `minetest` formula in Homebrew core is doing exactly what it should do, as per Homebrew core policies: it installs the `minetest.app` under `/usr/local/opt/minetest`. The app is working. There is no issue in Homebrew core, which is why I closed the issue (but I could have explained better).

If you want it incorporated into [Homebrew Cask](https://caskroom.github.io), you are free to do it, or to request that they add it. But it is a separate project from Homebrew core, so I can't really help you much there.

**Comment by Megaf** [comment]
> The minetest formula in Homebrew core is doing exactly what it should do, as per Homebrew core policies: it installs the minetest.app under /usr/local/opt/minetest. The app is working. There is no issue in Homebrew core, which is why I closed the issue (but I could have explained better).

My apologies @fxcoudert I now understand.
I will be looking into Homebrew Cask.
Thank you.
