### ISSUE TITLE
vim: Try to use Python 2.7.11 framework while 2.7.12 is installed

### ISSUE THREAD

**Issue by yous** [Homebrew/homebrew-core#2506]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

With Python 2.7.12 installed, `brew install vim` adds compile option `-F/usr/local/Cellar/python/2.7.11/Frameworks -framework Python`. But there is no `/usr/local/Cellar/python/2.7.11` while there is `/usr/local/Cellar/python/2.7.12`.

The following is the result of `vim --version` after compilation:
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 23 2016 14:32:39)
MacOS X (unix) version
Included patches: 1-1952
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +termguicolors
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+channel         -gettext         -mzscheme        +textobjects
+cindent         -hangul_input    +netbeans_intg   +timers
-clientserver    +iconv           +packages        +title
+clipboard       +insert_expand   +path_extra      -toolbar
+cmdline_compl   +job             +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.11 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/Cellar/python/2.7.11/Frameworks -framework Python   -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1/lib
```

Open Vim with `vim -u NONE` and execute `:python print(1)`, then it prints:
```
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
```

**Comment by ahawkins** [comment]
I "fixed" this issue by temporarily linking:

```
ln -s /usr/local/Cellar/python/2.7.11 /usr/local/Cellar/python/2.7.12
```

Vim error messages go away but uncertain how much still works.

**Comment by rakkesh** [comment]
Your `vim` installation links to `/usr/local/Cellar/python/2.7.11` because the Homebrew bottle for `vim` was built with `Python 2.7.11`. I should have bumped the revisions of all the `Python` dependent formulae. I'll create a PR for this change. /cc @tdsmith @DomT4 should I also revise `homebrew/python` and `homebrew/science`?

**Comment by williamboman** [comment]
```sh
$ brew install vim --with-custom-python
```

Seems to fix it as well.

**Comment by rakkesh** [comment]
If you build it again, it would work; the issue is with the current Homebrew bottle for `vim`.

**Comment by williamboman** [comment]
> If you build it again, it would work; the issue is with the current Homebrew bottle for vim.

Not sure if I'm installing vim with wront options, but: https://asciinema.org/a/6rzowxtci98tg6udbp89ya5st

**Comment by rakkesh** [comment]
`--with-python` is a default option for `vim` formula, so, Homebrew bottle was extracted when you had installed `vim`.

try,
`$ brew install vim --build-from-source`

**Comment by rakkesh** [comment]
Seems like when you use `--with-custom-python`, it has the same effect of using `--build-from-source`.

**Comment by yous** [comment]
@rakkesh `--build-from-source` seems to fix this for now. Thanks.

**Comment by DomT4** [comment]
Vim problem should be solved after `brew update && brew upgrade vim` after https://github.com/Homebrew/homebrew-core/commit/82161c69dcf16b2614a262f4ebe5e03bca721613.
