### ISSUE TITLE
nim-0.18.0 SHA256 mismatch

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-core#25070]
```
% brew install -s nim
==> Reinstalling nim
==> Downloading https://nim-lang.org/download/nim-0.18.0.tar.xz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 2ebe164eb4638a7a65aa02da7bdc4d7559026105655fdf3f620b9525406a46c1
Actual: 45c74adb35f08dfa9add1112ae17330e5d902ebb4a36e7046caee8b79e6f3bd0
Archive: /Users/torsten/Library/Caches/Homebrew/nim-0.18.0.tar.xz
To retry an incomplete download, remove the file above.
```
[X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
[X] ran brew update and can still reproduce the problem?
[X] ran brew doctor, fixed all issues and can still reproduce the problem?
[ ] ran brew gist-logs <formula> (where <formula> is the name of the formula that failed) and included the output link?
[ ] if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

**Comment by fxcoudert** [comment]
Please file an issue with the nim project,  so that they confirm whether it is intentional.

**Comment by dom96** [comment]
Yep, intentional. We had a small build issue with the first tarball and had to rebuild it.
