### ISSUE TITLE
`brew install ldc` after `brew upgrade llvm` => ld: library not found for -lLLVMBPFAsmParser

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#25098]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew install ldc` after `brew upgrade llvm` errors with:
`ld: library not found for -lLLVMBPFAsmParser`
it worked before the upgrade of llvm to 6.0
(even though brew install ldc tries to install llvm to 5.0 anyway)

also, I had previously installed llvm 5 with:
`brew install llvm --with-python --with-lldb --with-graphviz --with-toolchain`
but after `brew upgrade llvm` (which installed 6.0), `brew install ldc` reinstalled llvm 5 (without my options) instead of using llvm 5 with my options.

gist-logs:
https://gist.github.com/timotheecour/b01eeb42efc6e6957c7b16735f6ee8e0
`brew doctor` warnings seem irrelevant.

/cc @alex @ilovezfs

**Comment by timotheecour** [comment]
~/temp/brew/bin/brew install --keep-tmp --verbose ldc
shows -DLLVM_ROOT_DIR=/Users/timothee/temp/brew/opt/llvm

which is suspicious since /Users/timothee/temp/brew/opt/llvm points to ../Cellar/llvm/6.0.0/
and:
exists: /Users/timothee/temp/brew/Cellar/llvm/6.0.0/lib/libLLVMBPFAsmParser.a
not exists: /Users/timothee/temp/brew/Cellar/llvm@5/5.0.1/lib/libLLVMBPFAsmParser.a

**Comment by timotheecour** [comment]
EDIT: fix in progress in https://github.com/Homebrew/homebrew-core/pull/25099

**Comment by commitay** [comment]
Closed via #25099

**Comment by commitay** [comment]
Thanks for reporting this @timotheecour!
