### ISSUE TITLE
llvm: missing lldb header files

### ISSUE THREAD

**Issue by eidheim** [Homebrew/homebrew-core#25147]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# Outputs
brew gist-logs llvm:
```sh
https://gist.github.com/444961c491cda7823b3dde93882eeaba
```

# Problem
After installing newest llvm using `brew install --with-lldb llvm`, the following folder and files were missing from `/usr/local/Cellar/llvm/6.0.0/include/lldb`:
API/
lldb-defines.h
lldb-enumerations.h
lldb-forward.h
lldb-private-defines.h
lldb-private-enumerations.h
lldb-private-forward.h
lldb-private-interfaces.h
lldb-private-types.h
lldb-private.h
lldb-public.h
lldb-types.h
lldb-versioning.h

These files are included in https://releases.llvm.org/6.0.0/lldb-6.0.0.src.tar.xz, so my solution was to copy the missing folder and files to `/usr/local/Cellar/llvm/6.0.0/include/lldb`. Previous homebrew versions of llvm did not have this issue.

**Comment by mrexodia** [comment]
Found the same issue here. I'm using a case-sensitive file system if that matters.
