### ISSUE TITLE
Question: Correct way to add ArangoDB 3.0?

### ISSUE THREAD

**Issue by fceller** [Homebrew/homebrew-core#2517]
The new major version of ArangoDB 3.0 is not (datafile) compatible with ArangoDB 2.8. The correct way to upgrade is, to dump the data using ArangoDB 2.8 and then import the data into 3.0. It also requires some changes to the install Foxx apps.

How should the new ArangoDB formula look like? 

(a) create a new "arangodb3" formula and keep the old "arangodb"
(b) rename the "arangodb" formula to "arangodb2" and create a "arangodb" for ArangoDB 3.0
(c) something else

Thanks for any hints

**Comment by ilovezfs** [comment]
@fceller I'm happy to defer to you on this and will close the PR, but this is how I started: https://github.com/Homebrew/homebrew-core/pull/2515

There does seem to be a Mavericks build failure.

**Comment by ilovezfs** [comment]
@fceller Here's the full log for 10.9: https://gist.githubusercontent.com/ilovezfs/4a63c98e41eb54364295a162f4322f44/raw/97b2af849e0fb198ff8624d4cbb56c4fbbab353f/gistfile1.txt

**Comment by dothebart** [comment]
hm, ```
n file included from /tmp/arangodb-20160630-46463-37lwyp/ArangoDB-3.0.0/3rdParty/rocksdb/rocksdb/db/compaction_job.cc:46:0:
/tmp/arangodb-20160630-46463-37lwyp/ArangoDB-3.0.0/3rdParty/rocksdb/rocksdb/table/block.h:14:20: fatal error: malloc.h: No such file or directory
 #include <malloc.h>
                    ^
compilation terminated.
```
Strange, that doesn't happen during regular compiles on macs over here...

**Comment by ilovezfs** [comment]
It's specifically OS X 10.9

**Comment by dothebart** [comment]
whats it supposed to do? is an include path missing? or is the filename wrong?

**Comment by fceller** [comment]
Anyone any thoughts on the original question? If not, I will try to 

- fix the issue @ilovezfs has encountered
- try to push the old formula to homebrew-versions

Is this sensible? @DomT4?

**Comment by ilovezfs** [comment]
The biggest problem I was seeing was the mismatch between the formula name and the directories. So for example, pkgshare is /usr/local/share/arangodb but it wants to use /usr/local/share/arangodb3. So if it's important that the directories have the 3, then the formula should probably be renamed. If it's not, then the software should be configured to use the standard pkgshare /usr/local/share/arangodb, not /usr/local/share/arangodb3.

**Comment by fceller** [comment]
@ilovezfs I'll try to change it to /usr/local/share/arangodb

**Comment by ilovezfs** [comment]
Issue seems to affect etc and var/log as well if I recall. There may be others.

**Comment by fceller** [comment]
@ilovezfs the filenames are part of the upstream cmake file. So 

a) I either create a patch in order to change the upstream CMakeFile.txt
b) rename the formula

What is the preferred solution?

**Comment by ilovezfs** [comment]
Whichever requires less patching, which in this case I believe is a formula rename.

**Comment by fceller** [comment]
thanks, will rename the formula

**Comment by fceller** [comment]
I've create a ArangoDB 2.x version formula: https://github.com/Homebrew/homebrew-versions/pull/1304

**Comment by ilovezfs** [comment]
Closing in favor of #2576 and https://github.com/Homebrew/homebrew-versions/pull/1304

**Comment by pekeler** [comment]
Once Homebrew/homebrew-versions#1304 has been merged, what's the correct way to migrate from 2.8.9 to 2.8.10 using homebrew? Simply `brew install arangodb2`?

Also, what's the holdup, why doesn't homebrew merge the PR?

**Comment by DomT4** [comment]
> Also, what's the holdup, why doesn't homebrew merge the PR?

If only there was some way to discover this information... such as the PR reference @ilovezfs posted in the last post before your's 😉 - https://github.com/Homebrew/homebrew-core/pull/2576.

> Simply brew install arangodb2?

```bash
brew rm arangodb && brew install homebrew/versions/arangodb2
```

**Comment by pekeler** [comment]
@DomT4 I meant what's the holdup with Homebrew/homebrew-versions#1304. I need 2.8.10.

`brew rm arangodb` won't remove my data?
