### ISSUE TITLE
gcc failed to build on 10.11.5

### ISSUE THREAD

**Issue by skleinbo** [Homebrew/homebrew-core#2519]
Upgrading from `gcc-5.3.0` to `6.1.0` fails at bootstrapping. 

https://gist.github.com/59ccf0768ef6ff3d795fa360003cd8bd

I do not have root privileges on the machine, hence `brew` is in a private directory, not in `/usr/local`. Worked fine for `gcc-5`.

**Comment by dunn** [comment]
Your `brew doctor` is flagging a lot of errors.  I'd first try uninstalling or moving MacPorts.

**Comment by DomT4** [comment]
Closing as dead, but please shout if we can offer any assistance here still. Thanks!
