### ISSUE TITLE
Question: How do it set dynamodb-local to use -sharedDb flag?

### ISSUE THREAD

**Issue by edelpero** [Homebrew/homebrew-core#2521]
I'm having some issues to run dynamodb-local with the `-sharedDb` flag.

I've tried to update the Formula (`/usr/local/Library/Formula/dynamodb-local.rb`) as it follows but it didn't worked:

```ruby
class DynamodbLocal < Formula
  ...

  def bin_wrapper; <<-EOS.undent
    #!/bin/sh
    cd #{data_path} && exec java -Djava.library.path=#{libexec}/DynamodbLocal_lib -jar #{libexec}/DynamoDBLocal.jar -sharedDb "$@"
    EOS
  end

  ...
end
```

Can anyone help me out with this please? Thanks in advance.

**Comment by tdsmith** [comment]
The bin wrapper passes its arguments through. What happens when you pass -sharedDb on the command line and what do you expect to happen?

**Comment by edelpero** [comment]
@tdsmith thank you very much, it was an issue with dynamodb, I was not able to see the tables I created previously because they were created without using the -sharedDb flag. Thanks for your help.
