### ISSUE TITLE
gdb with --with-python@2 option builds against wrong python dir

### ISSUE THREAD

**Issue by skrap** [Homebrew/homebrew-core#25230]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/508a4eb4389efc8b789a33b8de431358
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew `gdb` using the homebrew-provided python, using the `--with-python@2` option
- What happened (include command output)
brew failed!  It looks like the failure is caused by the wrong path being passed to gdb's ./configure script: `--with-python=/usr/local/opt/python/libexec/bin`.  Homebrew's python is installed in` /usr/local/opt/python2`

Output:
```
11:24 $ brew upgrade gdb --with-python@2
==> Upgrading 1 outdated package, with result:
gdb 8.1
==> Upgrading gdb --with-all-targets --with-python@2
==> Downloading https://ftp.gnu.org/gnu/gdb/gdb-8.1.tar.xz
Already downloaded: /Users/skrap/Library/Caches/Homebrew/gdb-8.1.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gdb/8.1 --enable-targets=all --with-python=/usr/local/opt/python/libexec/bin
==> make
Last 15 lines from /Users/skrap/Library/Logs/Homebrew/gdb/02.make:
checking size of unsigned long long... 8
checking size of unsigned long... 8
checking size of unsigned __int128... 16
checking for library containing dlopen... (cached) none required
checking whether to use expat... auto
checking for libexpat... yes
checking how to link with libexpat... -lexpat
checking for XML_StopParser... yes
checking whether to use MPFR... auto
checking for libmpfr... no
configure: WARNING: MPFR is missing or unusable; some features may be unavailable.
checking whether to use python... /usr/local/opt/python/libexec/bin
configure: error: invalid value for --with-python
make[1]: *** [configure-gdb] Error 1
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Switch --with-python option for GDB formula to Python 3. https://github.com/Homebrew/homebrew-core/pull/24524
gdb 8.1 breakpoint trap in High Sierra 10.13.3 https://github.com/Homebrew/homebrew-core/issues/25172

```
- What you expected to happen
brew success!
- Step-by-step reproduction instructions (by running `brew install` commands)
1. prerequisite: uninstall homebrew python, python3, python@2, whatever python you might have, by whatever name...
2. `brew install gdb --with-python@2`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes

**Comment by skrap** [comment]
Looks like this might be a regression caused by either ba42c7a540ec32c58012374dfe1beccc03efb28e or maybe 1749991697e23373e00ca34724f651a49d1c5a0d?

**Comment by thmoa** [comment]
Try changing line 53 in `gdb.rb` to `args << "--with-python=#{Formula["python@2"].bin}"`.
