### ISSUE TITLE
postgresql failed to build with python3

### ISSUE THREAD

**Issue by yatagan** [Homebrew/homebrew-core#2525]
$ PYTHON=/usr/local/Cellar/python3/3.5.2/bin/python3 brew reinstall postgres --with-python
fails with:
checking for python... /usr/local/Cellar/python3/3.5.2/bin/python3
checking for Python distutils module... no
configure: error: distutils module not found

but, it builds successfully the same sources without brew:
PYTHON=/usr/local/Cellar/python3/3.5.2/bin/python3 ./configure --with-python --prefix=/Users/yatagan/SRC/pibox/epibox/postgresql_plpython3u
...
checking for python... /usr/local/Cellar/python3/3.5.2/bin/python3
checking for Python distutils module... yes
checking Python configuration directory... /usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/config-3.5m
checking Python include directories... -I/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/include/python3.5m
...

my environment here:
https://gist.github.com/yatagan/926dae6b93b278f4cef02bf43b10f19b

where did I go wrong?

**Comment by tdsmith** [comment]
Homebrew assumes `--with-python` is always Python 2.

**Comment by JamesHaskell** [comment]
Are there any plans to support Python 3?  Do you have any advice for those of us wishing to move forward with Python 3?

Get Outlook for iOS




On Thu, Jun 30, 2016 at 7:27 PM -0700, "Tim D. Smith" <notifications@github.com> wrote:












Homebrew assumes --with-python is always Python 2.

**Comment by tdsmith** [comment]
#2540 just landed and now you can `brew uninstall postgresql && brew install postgresql --with-python3`.
