### ISSUE TITLE
R bottle fetch 404 error

### ISSUE THREAD

**Issue by pooranis** [Homebrew/homebrew-core#25283]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? *could not include link as no log was produced - see below*
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install R.
- What happened (include command output)

```bash
$ brew fetch R
==> Downloading https://homebrew.bintray.com/bottles/R-3.4.3_1.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "R"
Download failed: https://homebrew.bintray.com/bottles/R-3.4.3_1.sierra.bottle.tar.gz
Warning: Bottle fetch failed: fetching the source.
```
- What you expected to happen
I expected homebrew to download the bottle, but it gave a 404 error.  Also, trying the download link, https://homebrew.bintray.com/bottles/R-3.4.3_1.sierra.bottle.tar.gz, by itself in the browser gives "The requested path was not found."  The other versions are also missing:
https://homebrew.bintray.com/bottles/R-3.4.3_1.el_capitan.bottle.tar.gz
https://homebrew.bintray.com/bottles/R-3.4.3_1.high_sierra.bottle.tar.gz

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install R` or `brew fetch R`

- Config
```
HOMEBREW_VERSION: 1.5.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 04efbadb9ef155c5921a03bf5f5d9052cd378c21
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e712b4ab726bda9c337ad886a6abf8bf53335e4b
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.6-x86_64
Xcode: N/A
CLT: 9.2.0.0.1.1510905681
X11: N/A
```
- brew doctor
`Your system is ready to brew.`
- brew gist-logs R
```Error: No logs.```

**Comment by fxcoudert** [comment]
The bottles are called `https://homebrew.bintray.com/bottles/r-3.4.3_1.high_sierra.bottle.tar.gz` (lowercase `r`) and exist. On my system, they get installed whether I call `brew install R` or `brew install `r`.

Do you, by any chance, have a case-sensitive filesystem?

**Comment by fxcoudert** [comment]
I'm closing this issue for now. A new version of R has been released, and bottles were updated.
