### ISSUE TITLE
gcc failed to compile on macOS 10.13.3

### ISSUE THREAD

**Issue by ncvv** [Homebrew/homebrew-core#25293]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- ~~[X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~~

To help us debug your issue please explain:
- What you were trying to do (and why)
I updated and upgraded Homebrew (this also led to an upgrade of python3, in case this is helpful).

- What happened (include command output)
I tried to compile a c++ program with gcc (`g++ main.cc -o main`)
The output was as follows:
```
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.15.dylib
  Referenced from: /usr/local/Cellar/gcc/7.3.0/libexec/gcc/x86_64-apple-darwin17.3.0/7.3.0/cc1plus
  Reason: image not found
g++: internal compiler error: Abort trap: 6 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
```

- Step-by-step reproduction instructions (by running `brew install` commands)
I can't particularly provide a step-by-step reproduction since homebrew was already installed and suddenly after the upgrade it did not work anymore. After the homebrew upgrade I also updated my macOS. I have also reinstalled the Xcode command line tools and I ran `brew reinstall gcc --build-from-source` and recreated my symlinks. `which gcc` shows `/usr/local/Cellar/gcc/7.3.0/bin/gcc`.
The output of `brew doctor` is `Your system is ready to brew.`

Output of `brew config`:
```
HOMEBREW_VERSION: 1.5.10
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 04efbadb9ef155c5921a03bf5f5d9052cd378c21
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f9aec7aa50704c258cb412e2022c752625d1a416
Core tap last commit: 75 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_RUBY_WARNINGS: -W0
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_40
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

Gist: https://gist.github.com/ncvv/de1f744296512b9f39847e105b5926d6

Thank you!

**Comment by ilovezfs** [comment]
```
brew upgrade gcc
```

**Comment by ncvv** [comment]
Hi, output for `brew upgrade gcc` is `gcc 7.3.0_1 already installed`.

**Comment by tobiasboyd** [comment]
I assume it's related, `brew update gcc` is failing for me on 10.13.3, make loops over and over until I kill it.

**Comment by commitay** [comment]
>  and recreated my symlinks

What do you mean by this?

**Comment by fxcoudert** [comment]
> gcc 7.3.0_1 already installed

You need to removed your outdated `gcc 7.3.0`, and then `brew link` the most-recent 7.3.0_1.

**Comment by ncvv** [comment]
> What do you mean by this?

Once I installed gcc with homebrew and tried to compile cpp applications, my laptop still used another older compiler version but not the one I installed via homebrew. I had to manually remove `/usr/bin/g++` and symlink `/usr/local/Cellar/gcc/7.3.0/bin/gcc-7` to it (with `ln -s /usr/bin/g++ /usr/local/Cellar/gcc/7.3.0/bin/gcc-7`

> You need to removed your outdated `gcc 7.3.0`, and then `brew link` the most-recent 7.3.0_1.

Thanks, that did the trick! I actually just did `brew cleanup` and `gcc --version` now says `gcc (Homebrew GCC 7.3.0_1) 7.3.0 [...]`
