### ISSUE TITLE
Restrictive umask inheritance

### ISSUE THREAD

**Issue by rbcrwd** [Homebrew/homebrew-core#25296]
A little esoteric for the checklist, but here goes...

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Installing the docker-machine-driver-xhyve formula in order to use native docker machines.

- What happened (include command output)
I followed the owner and setuid instructions in the formula, but kept running into permissions issues launching machines:
```
Error starting plugin binary: fork/exec /usr/local/bin/docker-machine-driver-xhyve: permission denied
```
Looking at the permissions of the installed file, we see something like this:
```
-r-s------  1 root  wheel  11026100 Jun 28  2017 /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve*
```
As I have a restrictive umask (077) and am accustomed to debugging issues with it, this immediately stood out to me - setting my umask to 022 and removing/reinstalling the formula resulted in the expected permissions:
```
-r-sr-xr-x  1 root  wheel  11026100 Jun 28  2017 /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve*
```

- What you expected to happen
Depends - if this is deemed broken behavior (inheriting a restrictive umask), the file should be installed with appropriate permissions, regardless of the parent shell's umask.

- Step-by-step reproduction instructions (by running `brew install` commands)
```BASH
umask 077
brew install docker-machine docker-machine-driver-xhyve
docker-machine create default --driver xhyve
```

Of course, feel free to close this WONTFIX if it's operating as designed.  I didn't see any other bug mentioning umask, so figured it may have been a yet-uncovered subject.

**Comment by fxcoudert** [comment]
Thanks @rbcrwd for the detailed report, it is an interesting question to which I did not know the answer myself. It will surely serve as documentation in case someone in the future has a similar issue.

After research, I confirm that we make the choice of respecting the user's umask: https://github.com/Homebrew/legacy-homebrew/pull/45837
