### ISSUE TITLE
Naming enchant binary (enchant vs enchant-2)

### ISSUE THREAD

**Issue by rnkn** [Homebrew/homebrew-core#25348]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
~~~
Error: No logs.
~~~
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
🤨

To help us debug your issue please explain:
- What you were trying to do (and why)

Get Enchant it to work with Emacs, in order to use AppleSpell with the Emacs spellchecker Ispell.

- What happened (include command output)

When setting the Enchant binary `enchant-2`, Emacs looks for a binary `enchant-2-lsmod` (i.e. `BINARY-lsmod`, however the associated binary is called `enchant-lsmod-2`. This prevents Enchant from working with Emacs.

- What you expected to happen

That the Enchant binary be linked to either `enchant` or both `enchant` and `enchant-2`.

- Step-by-step reproduction instructions (by running `brew install` commands)
~~~
$ brew install enchant
$ emacs
M-x customize-option RET ispell-program-name RET
    /usr/local/bin/enchant-2
~~~

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I understand this is clearly an Emacs issue, but considering that a versioned Enchant formula [was rejected](https://github.com/Homebrew/homebrew-core/pull/21634) it seems that the most obvious solution is to link to `enchant`.

I would edit the formula myself, but Homebrew formulae being written in Ruby is a barrier for me.

**Comment by ilovezfs** [comment]
This is an upstream issue. Please report it to them.

**Comment by rnkn** [comment]
To Emacs? So they can get teh name of the binary changed? I don't understand...

**Comment by ilovezfs** [comment]
no, enchant

**Comment by rnkn** [comment]
Ah, thanks.
