### ISSUE TITLE
About adding formulas

### ISSUE THREAD

**Issue by norman784** [Homebrew/homebrew-core#25369]
I'm curious on how formulas are added, just via pull request or I can ask also to be added? If is only the first one, can I get help on how to create a formula?

Regards

**Comment by SMillerDev** [comment]
I think the documentation on pull requests on the homebrew website would be a good starting point. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by norman784** [comment]
thanks, will check it out!
