### ISSUE TITLE
Building PHP with tidy-html5 not working, using a --with-tidy option or so

### ISSUE THREAD

**Issue by efoken** [Homebrew/homebrew-core#25371]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to build PHP 7.2 with `tidy-html5`, so I ran `brew install php --with-tidy=/usr/local/opt/tidy-html5`

- What happened (include command output)

There is no configuration option to do that. I remember there was in older PHP versions, or there were even formulae like `php70-tidy`. I have no idea, but `phpinfo()` says my tidy version is the one from Apple released in 2006.

- What you expected to happen

To have a PHP version build with `tidy-html5`

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install php --with-tidy=/usr/local/opt/tidy-html5`

**Comment by gramtech** [comment]
Not sure of this is what you are looking for but if you run 
`brew tap homebrew/php`
and then 
`brew search tidy`

Few option are available:

```
MacBook-Pro:~ graham$ brew search tidy
==> Searching local taps...
homebrew/php/php53-tidy        homebrew/php/php55-tidy        homebrew/php/php70-tidy        tidy-html5
homebrew/php/php54-tidy        homebrew/php/php56-tidy        homebrew/php/php71-tidy        tidyp
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...
```

Using php71 as an example, the below should set up the way you need, no?

`brew install php71-tidy`

hope this helps?

**Comment by efoken** [comment]
Yes for PHP 7.1 that's the solution, but I'm talking about the new PHP 7.2 in homebrew-core, there is no chance to get it working with `tidy-html5`. And yes, there is no option like `--with-tidy`, that's the problem.

I see the `--with-tidy` option hardcoded in the `./configure` command in the `php` formula.

**Comment by SMillerDev** [comment]
For the new formula all major extensions are included in the php build. If you want a different version of tidy to be build with php I'm afraid you're going to have to maintain your own tap that does this, or submit a pull request.
