### ISSUE TITLE
Filebeat doesn't include modules.d and kibana folder

### ISSUE THREAD

**Issue by jbelmont** [Homebrew/homebrew-core#25416]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install dashboard for kibana using command:
`filebeat setup --dashboards`
- What happened (include command output)
```bash
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /usr/local/Cellar/filebeat/6.2.2/kibana: No directory /usr/local/Cellar/filebeat/6.2.2/kibana/6 
```
- What you expected to happen
I expected to see the output `Loaded dashboards`
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install filebeat
brew services start filebeat
filebeat setup --dashboards
```
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by jbelmont** [comment]
I solved my issue by downloading the source for kibana and copying 2 directories:

`cp -r ~/Downloads/filebeat-6.2.2-darwin-x86_64/kibana /usr/local/Cellar/filebeat/6.2.2`

and then copying:

`cp -r ~/Downloads/filebeat-6.2.2-darwin-x86_64/modules.d /usr/local/Cellar/filebeat/6.2.2`

**Comment by commitay** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/25530

`brew update && brew upgrade filebeat`

Please provide all of the information requested in the template next time.
