### ISSUE TITLE
VTE formula installs a version that doesn't work

### ISSUE THREAD

**Issue by joaquinlpereyra** [Homebrew/homebrew-core#255]
The VTE formula tries to install vte version 0.42. This version will crash with Mac as soon as try to use Vte.Terminal().spawn_sync. In fact if you open VTE the output will be a blank window, 'cause it won't be able to execute bin/sh.

This could be fixed by downgrading vte to 0.40 or to updating to 0.44.

**Comment by dunn** [comment]
We'd love a pull request bringing it up to 0.44!  Take a look at https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by apjanke** [comment]
https://github.com/Homebrew/homebrew-core/pull/277 - bump to 0.44.1

**Comment by apjanke** [comment]
(Note that this is the `vte3` formula for gtk+3. The `vte` formula is way back on 0.28, though it also seems to be broken in a similar manner.)

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/c0d97e6475df7cf5bbf98e17b614135f5639e19b I presume?

**Comment by apjanke** [comment]
Yup.
