### ISSUE TITLE
Formulae using GHC older than 8.4

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#25568]
These should be switched to depend on the main ghc formula (currently 8.4.1) instead of ghc@8.2 as soon as possible.
 
- [x] [agda](https://github.com/Homebrew/homebrew-core/blob/master/Formula/agda.rb) https://github.com/Homebrew/homebrew-core/pull/28612
- [x] [arx](https://github.com/Homebrew/homebrew-core/blob/master/Formula/arx.rb) 
https://gist.github.com/ilovezfs/6d17f35e3a5d6609cc13ff70dc955e8a https://github.com/solidsnack/arx/issues/7
- [x] [cabal-install](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cabal-install.rb) https://gist.github.com/commitay/7904011d7cf7feb67f808ade1dabe0ae https://github.com/Homebrew/homebrew-core/pull/25889
- [x] [cryptol](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cryptol.rb) https://gist.github.com/commitay/9cead7f86fa56921333a3e458b72d5d8 https://github.com/GaloisInc/cryptol/issues/501 https://github.com/Homebrew/homebrew-core/pull/30693
- [x] [darcs](https://github.com/Homebrew/homebrew-core/blob/master/Formula/darcs.rb) https://gist.github.com/commitay/ff3bf40fb56d3c4fef604f08bc549253 https://github.com/Homebrew/homebrew-core/pull/28500
- [x] [dhall-json](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dhall-json.rb) https://gist.github.com/commitay/e19c54c269c1a5ef6338d2dea1774d21 https://github.com/Homebrew/homebrew-core/pull/25586
- [x] [elm-format](https://github.com/Homebrew/homebrew-core/blob/master/Formula/elm-format.rb) https://gist.github.com/commitay/66a7534a4888001d38c2872d3aff0b6f https://github.com/Homebrew/homebrew-core/pull/25587 https://github.com/avh4/elm-format/issues/464
- [x] [elm](https://github.com/Homebrew/homebrew-core/blob/master/Formula/elm.rb) (using 8.2) https://gist.github.com/ilovezfs/df2f56795643ef5ec27b34dc387ba8bc https://github.com/elm-lang/elm-compiler/issues/1695
https://github.com/Homebrew/homebrew-core/pull/31318
- [x] [futhark](https://github.com/Homebrew/homebrew-core/blob/master/Formula/futhark.rb) https://gist.github.com/commitay/a0cf40e71fff810260ed364d0db9f808
- [ ] [git-annex](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-annex.rb) https://gist.github.com/commitay/0c4e5067ed507d4b9797520fd79dcb76
- [x] [hadolint](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hadolint.rb) https://github.com/Homebrew/homebrew-core/pull/28546
- [x] [haskell-stack](https://github.com/Homebrew/homebrew-core/blob/master/Formula/haskell-stack.rb) https://gist.github.com/commitay/121006a5bef72fa39f038fcae26acff8 https://github.com/Homebrew/homebrew-core/pull/27201
- [x] [hledger](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hledger.rb) https://gist.github.com/commitay/2fa898a54c85cc2cb66c9e34623a5c1a https://github.com/Homebrew/homebrew-core/pull/25676
- [x] [hopenpgp-tools](https://github.com/Homebrew/homebrew-core/blob/master/Formula/hopenpgp-tools.rb) https://github.com/Homebrew/homebrew-core/pull/28501
- [x] [idris](https://github.com/Homebrew/homebrew-core/blob/master/Formula/idris.rb) https://gist.github.com/commitay/a2361550d946110cc76225af4e08ab97 https://github.com/Homebrew/homebrew-core/pull/28325
- [x] [pinboard-notes-backup](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pinboard-notes-backup.rb) https://github.com/Homebrew/homebrew-core/pull/28548
- [ ] [postgrest](https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgrest.rb) https://gist.github.com/commitay/9a619f1f7afef756ae6a7c95b7232ca0
https://github.com/PostgREST/postgrest/issues/1109
- [x] [purescript](https://github.com/Homebrew/homebrew-core/blob/master/Formula/purescript.rb)
https://gist.github.com/ilovezfs/c532faf88ead5dd7440e660d04178ce0 https://github.com/purescript/purescript/issues/3284 https://github.com/purescript/purescript/pull/3372
https://github.com/Homebrew/homebrew-core/pull/34440
- [x] [shellcheck](https://github.com/Homebrew/homebrew-core/blob/master/Formula/shellcheck.rb) https://github.com/Homebrew/homebrew-core/pull/28544 https://github.com/koalaman/shellcheck/issues/1157

**Comment by fxcoudert** [comment]
@ilovezfs is not following this list anymore, and we have only two formulas awaiting migration. Keeping a meta-issue open seems like overkill at this point, so I'm closing.
