### ISSUE TITLE
luarocks-5.1 requires /usr/local writable, but this is not possible

### ISSUE THREAD

**Issue by mcclure** [Homebrew/homebrew-core#25597]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ X ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ NO ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X ] ran `brew update` and can still reproduce the problem?
- [ X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ FORMULA INSTALLS ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ N/A ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Summary**

Lua is available as a `lua` package and a `lua-5.1` package. Although `lua-5.1` is an older version it is possible more people are using it. The `luarocks` package manager (installed by the lua formula) behaves properly with regards to package install but `luarocks-5.1` does not. 5.1 requires /usr/local to be writable which is essentially unachievable on Mac OS High Sierra.

**Example**

Lua (expected behavior) If you `brew install lua`, then run the `luarocks` package manager, 

```
$ luarocks install luacs
Installing https://luarocks.org/luacs-1.0.0-0.src.rock
luacs 1.0.0-0 is now installed in /usr/local (license: MIT)

$ luarocks remove luacs
Checking stability of dependencies in the absence of
luacs 1.0.0-0...

Removing luacs 1.0.0-0...
Removal successful.
```

However if you run `brew install lua-5.1`, then run the same command:

```
$ luarocks-5.1 install luacs

Error: Your user does not have write permissions in /usr/local 
-- you may want to run as a privileged user or use your local tree with --local.
```

**Expected behavior:** Luarocks-5.1 should do whatever Luarocks does. The basic `luarocks-5.1` is returning an error out of the box on its most basic operation and should not.

Opinion: Although there is an easy workaround (using --local), dealing with the /usr/local writability should be considered part of Homebrew's OS compatibility work. Also, if Homebrew supplies two versions of lua, the two should be consistent wrt compatibility.

**Comment by mistydemeo** [comment]
It looks like `lua@5.1` installs luarocks 2.3.0, while `lua` installs luarocks 2.4.3. I do see there's an upstream fix for the `/usr/local` issue: https://github.com/luarocks/luarocks/commit/927b11f650e7b60fa92f37dd6d6ba663250f7bd9 That fix  seems to be in 2.4.3 and 2.4.4. We can fix this by updating the bundled luarocks shipped with `lua@5.1`.

**Comment by mistydemeo** [comment]
Looks like there's a WIP pull request for this: https://github.com/Homebrew/homebrew-core/pull/21282 Which currently doesn't work, which is why this has lagged.

**Comment by DomT4** [comment]
Yeah, this is a known one, and a fun one.

I think the last time I took a major run at this I ended up rewriting a not insignificant chunk of the `configure` file for `luarocks`, which highlighted that it was finding the versioned executable okay but rejecting the version string in the `lua.h` header, and that sent me down a rabbit hole I didn't manage to dig myself out of.

I can get it to build in `postinstall` using the versioned links, but not during `install`, and that mix of behaviour is peculiar. ILZ rejected using `postinstall` for reasons I understand so it is effectively stalled on working out which of the build issues isn't a giant red-herring.

**Comment by DomT4** [comment]
Some of the fun:

With the rename moved below the `luarocks` build/install step:
```
./configure --prefix=/usr/local/Cellar/lua@5.1/5.1.5_6/libexec --rocks-tree=/usr/local --sysconfdir=/usr/local/etc/luarocks51 --with-lua=/usr/local/Cellar/lua@5.1/5.1.5_6 --versioned-rocks-dir
Lua version detected:
Lua interpreter found: /usr/local/Cellar/lua@5.1/5.1.5_6/bin/lua...
Checking Lua includes...
lua.h not found (looked in /usr/local/Cellar/lua@5.1/5.1.5_6/include, /usr/local/Cellar/lua@5.1/5.1.5_6/include/lua/, /usr/local/Cellar/lua@5.1/5.1.5_6/include/lua)
You may want to use the flag --with-lua or --with-lua-include. See --help.

configure failed.
```

```
./configure --prefix=/usr/local/Cellar/lua@5.1/5.1.5_6/libexec --rocks-tree=/usr/local --sysconfdir=/usr/local/etc/luarocks51 --with-lua=/usr/local/Cellar/lua@5.1/5.1.5_6 --with-lua-include=/usr/local/Cellar/lua@5.1/5.1.5_6/include/lua-5.1 --versioned-rocks-dir
Lua version detected:
Lua interpreter found: /usr/local/Cellar/lua@5.1/5.1.5_6/bin/lua...
Checking Lua includes...
lua.h found in /usr/local/Cellar/lua@5.1/5.1.5_6/include/lua-5.1/lua.h
Checking if Lua header version matches that of the interpreter...
no
lua.h version mismatch (interpreter: ; lua.h: 5.1).
You may want to use the flag --with-lua or --with-lua-include. See --help.

configure failed.
```

With the formula as-is:
```
./configure --prefix=/usr/local/Cellar/lua@5.1/5.1.5_6/libexec --rocks-tree=/usr/local --sysconfdir=/usr/local/etc/luarocks51 --with-lua=/usr/local/Cellar/lua@5.1/5.1.5_6 --with-lua-include=/usr/local/Cellar/lua@5.1/5.1.5_6/include/lua-5.1 --lua-version=5.1 --versioned-rocks-dir
Lua 5.1 interpreter not found in /usr/local/Cellar/lua@5.1/5.1.5_6/bin
You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help.

configure failed.
```

**Comment by DomT4** [comment]
Oh, fixed it. Will update the PR.

**Comment by ilovezfs** [comment]
This should now be fixed if you `brew upgrade`
