### ISSUE TITLE
proj 5.0.0 leaks memory when used with gdal 

### ISSUE THREAD

**Issue by rundel** [Homebrew/homebrew-core#25594]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Recently the version of proj available from homebrew moved from 4.9.3 to 5.0.0, the new version changes details of the proj api which are not currently reflected in gdal or gdal2 (from homebrew-osgeo4mac). This results in a memory leak and related issues when attempting to use gdal to reproject.

I've included an example of valgrind output here: https://gist.github.com/rundel/c7d31b0dc8bd63193058af3a82719cbb.
 
It appears that these issues are being worked on and fixes are available in gdal trunk (https://lists.osgeo.org/pipermail/gdal-dev/2018-March/048278.html) but they also depend on changes in proj which will not be available until 5.0.1 is released.

@ilovezfs

**Comment by ilovezfs** [comment]
Hopefully 5.0.1 is imminent based on https://github.com/OSGeo/proj.4/commit/be3587d8de04ab35baf04c86d67bdb0b9e269be8

**Comment by rundel** [comment]
What is the thinking with regard to updating gdal (1.11.5 is from July 2016)? I'm not sure that 5.0.1 will fix the memory leak issue based on the news (it requires the gdal update).

**Comment by ilovezfs** [comment]
@rundel just waiting for someone to open a ✅ pull request doing the upgrade.

**Comment by rundel** [comment]
It looks like there is a now a pull request for 2.2.4 in #25647 -  this doesn't resolve the leak issue. Until gdal 2.2.5 and proj 5.0.1 are available is it possible roll back proj or at the very least support a proj@4 version?

**Comment by ilovezfs** [comment]
No, that's not warranted at this point.

**Comment by fxcoudert** [comment]
proj was updated to 5.0.1: #26030
