### ISSUE TITLE
provide Qemu 2.12RC's as -devel option?

### ISSUE THREAD

**Issue by oscarbg** [Homebrew/homebrew-core#25678]
Hi,
I see some formulas/packages have a -devel optional argument which fetches current master branch of the project or some current beta/RC i.e. not the stable version..
since Qemu now is on 2.12RC phase would love to be able to get it using "brew install qemu -devel" and getting either prebuilt or that script builds on user machine..
thanks..

**Comment by fxcoudert** [comment]
It's a good suggestion. We'd welcome a [pull request](https://github.com/Homebrew/homebrew-core/pulls) adding this, but don't have enough maintainer power to act ourselves on feature requests, especially for nonstable versions.
