### ISSUE TITLE
jbig2enc compiles but the compiled binary does not work

### ISSUE THREAD

**Issue by lzlarryli** [Homebrew/homebrew-core#25714]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install and use `jbig2enc`.

- What happened (include command output)

The compilation and installation went through without error. But the compiled binary does not work. In particular, instead of processing a file, it is trapped in an infinite loop.

```
$ jbig2 -s -v -p tosr-011.tiff 
Processing "tosr-011.tiff"...
source image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 1
thresholded image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 2
source image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 1
thresholded image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 2
source image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 1
thresholded image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 2
...
```
The last two lines just repeat themselves forever.

- What you expected to happen

I compiled the package from source myself. The output is correct:
```
$ jbig2enc/src/jbig2 -s -v -p tosr-011.tiff 
Processing "tosr-011.tiff"...
source image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 1
thresholded image: 3188 x 5180 (1 bits) 300dpi x 300dpi, refcount = 2
JBIG2 compression complete. pages:1 symbols:6 log2:3
```

- Step-by-step reproduction instructions (by running `brew install` commands)

1. Run `brew install jbig2enc`
2. Run `jbig2 -s -v -p tosr-011.tiff` where the input file can be found in
[tosr-011.tiff.zip](https://github.com/Homebrew/homebrew-core/files/1844812/tosr-011.tiff.zip).

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
I confirm the bug, and I confirm it is fixed with the current git source. Use `brew install jbig2enc --HEAD` in order to install that in Homebrew.

**Comment by lzlarryli** [comment]
@fxcoudert Thank you. I confirm that using the current git source works.
