### ISSUE TITLE
Automatic linking of youtube-dl

### ISSUE THREAD

**Issue by tdegeus** [Homebrew/homebrew-core#25774]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# Formula

```bash
$ brew gist-logs youtube-dl
https://gist.github.com/543e61022e7425124379073ce5c0e0e6
```

# Description

It would be great if the Homebrew installation of `youtube-dl` would automatically link the latest version. 

This done for almost all, if not all, other apps. For example, for Python3:

```bash
$ ls -l `which python3`
lrwxr-xr-x  1 tdegeus  admin  36 Mar 12 09:09 /usr/local/bin/python3 -> ../Cellar/python/3.6.4_4/bin/python3
```

I.e. a link is created in the usual location (`/usr/local/bin`) that points to the latest version in the `Cellar`. 

For `youtube-dl` the desired behavior would be

```bash
$ ls -l `which youtube-dl`
lrwxr-xr-x  ... /usr/local/bin/youtube-dl -> ../Cellar/youtube-dl/2018.03.20/bin/youtube-dl
```

which updates with every update.

# What I have done

I have tried to look into the formula and other formulas to see if I would be able to do this myself. But currently, I cannot say that I understand exactly what I would need for this.

**Comment by ilovezfs** [comment]
This is already the case.
```
iMac-TMP:~ joe$ ls -l /usr/local/bin/youtube-dl 
lrwxr-xr-x  1 joe  staff  46 Mar 26 02:45 /usr/local/bin/youtube-dl -> ../Cellar/youtube-dl/2018.03.20/bin/youtube-dl
```

**Comment by tdegeus** [comment]
That was kind of naive of me... It was not done before, and somehow I never rechecked. Thanks in any case!
