### ISSUE TITLE
Lftp: installed features and man page differ from expected source?

### ISSUE THREAD

**Issue by kevzettler** [Homebrew/homebrew-core#25803]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)
Install LFTP and utlize features from https://lftp.yar.ru/lftp-man.html sepcifically the `--dry-run` option

- What happened (include command output)
LFTP installs without error. However if I view the man page with `man lftp` it is differnt from the posted man page at https://lftp.yar.ru/lftp-man.html which should be applicale to the installed brew version. 

It is missing the `--dry-run` option form the man pages and fails when I execute the command and pass the option

- What you expected to happen
I expected the brew installed package to match the features of the source package. The version numbers are the same

```
Kevs-MacBook-Pro:lftp-4.8.3 kev$ lftp --version
LFTP | Version 4.8.3 | Copyright (c) 1996-2017 Alexander V. Lukyanov

LFTP is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with LFTP.  If not, see <http://www.gnu.org/licenses/>.

Send bug reports and questions to the mailing list <lftp@uniyar.ac.ru>.

Libraries used: Expat 2.1.0, libiconv 1.11, OpenSSL 1.0.2n  7 Dec 2017, Readline 7.0, zlib 1.2.8
```

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install lftp
man lftp
```
search for `--dry-run` option

**Comment by rakkesh** [comment]
This isn't an issue with `homebrew`; you may have to report upstream about the `man` document formatting - 

```sh
➜ ~ man lftp
/usr/bin/tbl:<standard input>:171: unrecognised format `<'
/usr/bin/tbl:<standard input>:171: giving up on this table
/usr/bin/tbl:<standard input>:190: `p' modifier must be followed by number
/usr/bin/tbl:<standard input>:190: unrecognised format `h'
/usr/bin/tbl:<standard input>:190: giving up on this table
/usr/bin/tbl:<standard input>:220: unrecognised format `h'
/usr/bin/tbl:<standard input>:220: giving up on this table
/usr/bin/tbl:<standard input>:243: unrecognised format `\'
/usr/bin/tbl:<standard input>:243: giving up on this table
/usr/bin/tbl:<standard input>:303: unrecognised format `\'
/usr/bin/tbl:<standard input>:303: giving up on this table
```
The option `--dry-run` is present in the file `lftp.1`, just doesn't show up in `man lftp` due to format error -
```sh
$ grep dry-run /usr/local/opt/lftp 
/usr/local/opt/lftp/share/man/man1/lftp.1
704:	\-\-just-print, \-\-dry-run	T{
```
