### ISSUE TITLE
LUA: Error: inreplace failed

### ISSUE THREAD

**Issue by horta** [Homebrew/homebrew-core#25836]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config:
```
HOMEBREW_VERSION: 1.5.12
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: ea3ed5c7e458644cb5d45115a04c3e30f4489e36
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 6de250122ea8d0c14042509cacdf8f9f3942b89c
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /nfs/software/stegle/system/linuxbrew2
HOMEBREW_REPOSITORY: /nfs/software/stegle/system/linuxbrew2
HOMEBREW_CELLAR: /nfs/software/stegle/system/linuxbrew2/Cellar
HOMEBREW_CACHE: /homes/horta/.cache/Homebrew
HOMEBREW_CELLAR: /nfs/software/stegle/system/linuxbrew2/Cellar
HOMEBREW_PREFIX: /nfs/software/stegle/system/linuxbrew2
HOMEBREW_REPOSITORY: /nfs/software/stegle/system/linuxbrew2
HOMEBREW_RUBY_WARNINGS: -W0
CPU: 40-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /nfs/software/stegle/system/linuxbrew2/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.16.3 => /nfs/software/stegle/system/linuxbrew2/bin/git
Curl: 7.29.0 => /usr/bin/curl
Perl: /nfs/software/stegle/system/linuxbrew2/bin/perl => /nfs/software/stegle/system/linuxbrew2/Cellar/perl/5.26.1_1/bin/perl
Python: /nfs/software/stegle/system/linuxbrew2/opt/python/libexec/bin/python => /nfs/software/stegle/system/linuxbrew2/Cellar/python/3.6.4_5/bin/python3.6
Ruby: /nfs/software/stegle/system/linuxbrew2/bin/ruby => /nfs/software/stegle/system/linuxbrew2/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
Kernel: Linux 3.10.0-327.10.1.el7.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 7.3 (Maipo) (Maipo)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_3
xorg: 20170115_1
```

brew doctor
```
Your system is ready to brew.
```

Steps to reproduce the error:

```
brew install lua@5.1
```

which produced 

```
==> Downloading https://www.lua.org/ftp/lua-5.1.5.tar.gz
Already downloaded: /homes/horta/.cache/Homebrew/lua@5.1-5.1.5.tar.gz
Error: inreplace failed
src/Makefile:
  expected replacement of "@LUA_PREFIX@" with #<Pathname:/nfs/software/stegle/system/linuxbrew2/Cellar/lua@5.1/5.1.5_7>
```

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew.
