### ISSUE TITLE
IPython not symlinked into site-packages

### ISSUE THREAD

**Issue by adunning** [Homebrew/homebrew-core#25847]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? <https://gist.github.com/224928200b267341c9656184a46acfc6>

To help us debug your issue please explain:
- What you were trying to do (and why)

Install IPython and use it with Jupyter from Pip (because the Homebrew Jupyter formula uses Python@2 for some reason).

- What happened (include command output)

IPython is accessible from the command line and tests properly, but is not symlinked into `/usr/local/lib/python3.6/site-packages` and hence not detected by Pip. Looking at <https://github.com/Homebrew/homebrew-core/blob/master/Formula/ipython.rb>, this should be happening, and I am not clear on why it isn't. (Compare the technique used by the numpy formula, which works on my system.)

- What you expected to happen

IPython listed when running `pip3 list`.

- Step-by-step reproduction instructions (by running `brew install` commands)

```shell
$ brew install ipython
$ pip list
```

**Comment by rakkesh** [comment]
>Install IPython and use it with Jupyter from Pip (because the Homebrew Jupyter formula uses Python@2 for some reason).

You may try and update the formula to use `python` (python3) and `ipython` instead.

>IPython is accessible from the command line and tests properly, but is not symlinked into /usr/local/lib/python3.6/site-packages and hence not detected by Pip.

The package would have been "symlinked" into `/usr/local/lib/python3.6/site-packages` if it was installed into the formula's `lib` directory and not under `libexec`.

To workaround this issue, you need to add the `ipython` `site-packages` directory path to `python3`'s `site-packages` directory list.
```sh
$ echo "import site; site.addsitedir('/usr/local/opt/ipython/libexec/lib/python3.6/site-packages')" > /Users/ravi/Library/Python/3.6/lib/python/site-packages/ipython.pth
```
and then, verify -
```sh
$ pip3 list
Package        Version
-------------- -------
ipython        6.2.1  
pip            9.0.1  
setuptools     38.5.2 
six            1.11.0 
wheel          0.30.0 
```

**Comment by adunning** [comment]
Thanks for the explanation! Is that not considered a bug in the formula, then?

**Comment by rakkesh** [comment]
>Is that not considered a bug in the formula, then?

No, it by design. To avoid installed `python` software packages (formulas) to be overwritten by `pip` install or other methods.
