### ISSUE TITLE
libjpeg shasum problem

### ISSUE THREAD

**Issue by hjmallon** [Homebrew/homebrew-core#25845]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The jpeg-9c tar.gz package at "http://www.ijg.org/files/jpegsrc.v9c.tar.gz" seems to have a different shasum then that defined in the formula:
* `1f3a3f610f57e88ff3f1f9db530c605f3949ee6e78002552e324d493cf086ad4` in formula 
* `650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122` now
    * Using `shasum -a 256 jpegsrc.v9c.tar.gz`.

I think it must have changed as I have jpeg-9c on other machines (or maybe they came from a cask).

Here is my brew version info:

```
HOMEBREW_VERSION: 1.5.12-57-g0851f96
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0851f96710ef147624c4164bae219872ca224f26
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6f5800df4d43b29db702516167df539a89df38ce
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: 12-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.3 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_60
macOS: 10.13.3-x86_64
Xcode: 9.2
CLT: 9.2.0.0.1.1510905681
X11: 2.7.11 => /opt/X11
```

**Comment by ilovezfs** [comment]
@jschleus fossies seems to be impacted too

**Comment by jschleus** [comment]
Yes, today the old tarball seems replaced by a newer one with same name and identical contents but with one exception: The dot file `jpeg-9c/.directory` (28 bytes) is now removed. Timestamp of the tarball subdirectory `jpeg` is now `2018-03-27 15:26` (was `2018-01-26 13:49`) but timestamp of the "new" tarball jpegsrc.v9c.tar.gz in the directory listing `http://www.ijg.org/files/` is `Sun Jan 14 11:48 2018` (maybe artificially touched) although the HTTP header gives `Last-Modified: Tue, 27 Mar 2018 14:37:34 GMT`.

Fossies.org offers now the new one.

**Comment by commitay** [comment]
Reported to the email address in the readme.

http://www.ijg.org/files/README

**Comment by jackyzonewen** [comment]
how to resolve it, the same to me~

**Comment by ilovezfs** [comment]
Use the bottle.

**Comment by jackyzonewen** [comment]
@ilovezfs what's your mean?

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update`
