### ISSUE TITLE
Enhancement: Separate Emacs plugin for cmake from the main cmake formula

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#25925]
The Homebrew cmake formula is mostly pretty great, though I wonder if the Emacs plugin currently bundled with cmake would be better packaged as a formula distinct from cmake. This saves a bit of storage space for non-Emacs users, speeds up installation, and streamlines buildbots, which don't want the bloat of editor-specific resources installed. In any case, cmake-mode is available via MELPA and other sources.

http://melpa.milkbox.net/#/cmake-mode

**Comment by ilovezfs** [comment]
For the majority of users this is just a question of a small amount of space, so it's not worth maintaining an entirely separate formula for over the long-term, but thanks for the idea!
