### ISSUE TITLE
brew doctor

### ISSUE THREAD

**Issue by gdupret** [Homebrew/homebrew-core#25939]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

 brew upgrade
xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:40:in `below_minimum_version?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:110:in `check_xcode_minimum_version'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:314:in `block in check_development_tools'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `check_development_tools'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:333:in `perform_preinstall_checks'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:30:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
blado:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Missing Homebrew/brew git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the Homebrew remote:
  git -C "/usr/local/Homebrew" remote add origin https://github.com/Homebrew/brew.git
xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
Error: NaN
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `to_i'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:152:in `detect_version_from_clang_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:144:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:114:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:283:in `detect_version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:273:in `version'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:202:in `installed?'
/usr/local/Homebrew/Library/Homebrew/os/mac/xcode.rb:245:in `below_minimum_version?'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/diagnostic.rb:120:in `check_clt_minimum_version'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:47:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:39:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:39:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
blado:~$

**Comment by ilovezfs** [comment]
You need to reinstall Homebrew.

**Comment by gdupret** [comment]
blado:~$ which brew
/usr/local/bin/brew
blado:~$ ll /usr/local/bin/brew 
lrwxr-xr-x  1 gdupret  admin  28 Oct 20 14:47 /usr/local/bin/brew -> /usr/local/Homebrew/bin/brew
blado:~$ sudo mv /usr/local/Homebrew/ /tmp
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/share/man/man8
==> The following existing directories will have their owner set to gdupret:
/usr/local/share/man/man8
==> The following existing directories will have their group set to admin:
/usr/local/share/man/man8
==> The following new directories will be created:
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/share/man/man8
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/share/man/man8
==> /usr/bin/sudo /usr/sbin/chown gdupret /usr/local/share/man/man8
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/share/man/man8
==> /usr/bin/sudo /bin/mkdir -p /usr/local/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/Homebrew
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown gdupret /usr/local/Homebrew
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/Homebrew
==> /usr/bin/sudo /bin/mkdir -p /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown gdupret /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 99242, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 99242 (delta 12), reused 16 (delta 8), pack-reused 99210
Receiving objects: 100% (99242/99242), 22.68 MiB | 6.61 MiB/s, done.
Resolving deltas: 100% (72197/72197), done.
From https://github.com/Homebrew/brew
 * [new branch]          master     -> origin/master
 * [new tag]             0.1        -> 0.1
 * [new tag]             0.2        -> 0.2
etc.

HEAD is now at 07997d41e Merge pull request #4004 from MikeMcQuaid/usability
==> Tapping homebrew/core
xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --depth=1
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core
Failed during: /usr/local/bin/brew update --force

Best, and thank you brew,
ged
