### ISSUE TITLE
php72-xdebug is not found

### ISSUE THREAD

**Issue by andreybolonin** [Homebrew/homebrew-core#26007]
<img width="487" alt="screen shot 2018-03-31 at 8 22 14 pm" src="https://user-images.githubusercontent.com/2576509/38165762-466679a8-3521-11e8-882e-c753394efa5d.png">

**Comment by SMillerDev** [comment]
With the migration to Homebrew-core the php formula has stopped taking over the role of PECL. Installing xdebug can (and should) be done through PECL (https://pecl.php.net/package/xdebug).

**Comment by r-nicol** [comment]
Can we please add this kinda of information to the docs or at least in the old [homebrew-php README](https://github.com/Homebrew/homebrew-php/blob/master/README.md). As "or deleted" is not very helpful or clear. I won't be alone in wasting time to find this one comment that should be on the README.

**Comment by Pushplaybang** [comment]
🖕 🖕 :rage4:

**Comment by mikeschinkel** [comment]
Thanks to this change, I just wasted about 6+ hours.  :-(
And moved to using a well designed tool (Homebrew) that just seems to work, to a poorly designed tool (pecl), that only seems to work correctly when the planets are correctly aligned.

<sigh>
