### ISSUE TITLE
[Formula/open-mpi] Open MPI Fails to Build and Install Under OS X v10.11.6 'El Capitan'

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#26009]
**Please note we will close your issue without comment if you delete, do not read, or do not fill out the issue checklist below and provide ALL the requested information.  If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please always confirm that you:  
- [x] are reporting a bug others will be able to reproduce and not asking a question.  If you're not sure or want to ask a question, do so on our Discourse:  https://discourse.brew.sh.  
- [x] have a problem with `brew install`ing (or `upgrade`ing or `reinstall`ing) a single, official formula (not a cask?)  If it's a general `brew` problem, please file this issue at Homebrew/brew:  https://github.com/Homebrew/brew/issues/new.  If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new.  If it's a tap&thinsp;—&thinsp;e.g. Homebrew/homebrew-php&thinsp;—&thinsp;problem, please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?  (Caveat:  I suspended running `brew update`s while producing debugging logs for this issue to ensure that Homebrew Core would stay on the same revision between both log-collection runs I made, so me checking this box only applies with respect to the status of my system prior to my preparing to submit this issue.  This should _not_, however, prove to be any sort of problem, as no commits to Homebrew Core since I started going down this rabbit hole appear to have touched any files that would be relevant here.)  
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?  
- [ ] ~~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~  (N/A; see the next bullet point.)  
- [x] if `brew gist-logs` didn't work (or, in this case, was not preferred:)  ran `brew config` and `brew doctor` and included their output with your issue?  

To help us debug your issue please explain:  
- What you were trying to do (and why:)  

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upgrade my local, built-from-source copy of Open MPI from v3.0.0, Homebrew formula `revision 2`, to v3.0.1 in the course of going through my normal routine of keeping all of my software tools up to date.  

- What happened (include command output:)  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Homebrew failed to successfully build Open MPI from v3.0.0, Homebrew formula `revision 2`, to v3.0.1.  My logs are:  

   - [here](https://gitlab.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Open%20MPI/3.0.1/Recorded%20Attempts/First%20Recorded%20Attempt/With%20%60HOMEBREW_BUILD_FROM_SOURCE=1%60) (from when I _did_ set `HOMEBREW_BUILD_FROM_SOURCE=1`.)  
   - [here](https://gitlab.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Open%20MPI/3.0.1/Recorded%20Attempts/First%20Recorded%20Attempt/With%20%60HOMEBREW_BUILD_FROM_SOURCE%60%20Undefined) (from when I _didn't._)  

   In both cases, the exact point of failure manifested itself as follows:  

   ```
   ⋮
   Making all in mpi/java
   Making all in java
     JAVAC    MPI.class
   Picked up _JAVA_OPTIONS:  -Duser.home=/Users/zadmin/Library/Caches/Homebrew/java_cache
     JAVAH    mpi_MPI.h
     JAVAH    mpi_CartParms.h
   Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home/bin/javah" (-1)
   Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home/bin/javah" (-1)
   make[3]: *** [mpi_CartParms.h] Error 2
   make[3]: *** Waiting for unfinished jobs....
   make[3]: *** [mpi_MPI.h] Error 2
   make[2]: *** [all-recursive] Error 1
   make[1]: *** [all-recursive] Error 1
   make: *** [all-recursive] Error 1
   /usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb
   /usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
   BuildError: Failed executing: make all
   1. raise
   2. ignore
   3. backtrace
   4. irb
   5. shell
   Choose an action: 1
   ⋮
   ```

   The issue I describe in this report is thus due to Homebrew's `open-mpi` formula's `--with-java` option and the fact that `javah` was deprecated in Java 9.x and removed in Java 10.  

- What you expected to happen:  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For Homebrew to successfully build the new version of Open MPI from source and install it in the old version's place.  

- Step-by-step reproduction instructions (by running `brew` commands:)  
   - _With_ `HOMEBREW_BUILD_FROM_SOURCE=1` (not supported with issue resolution:)  

      ```
      HOMEBREW_BUILD_FROM_SOURCE=1 brew upgrade -vd --build-from-source open-mpi --with-java --with-mpi-thread-multiple
      ```

      Note that setting that environment variable as shown above _probably_ doesn't make _any_ difference in this case, as upgrading Open MPI doesn't depend on upgrading any of its dependencies given the states my Homebrew installation and the packages it manages are currently in, but I usually set it _any_ time I run `brew upgrade`, just to be consistent.  

   - _Without_ `HOMEBREW_BUILD_FROM_SOURCE=1` (given to show that this issue _also_ occurs under a _supported_ configuration:)  

      ```
      brew upgrade -vd --build-from-source open-mpi --with-java --with-mpi-thread-multiple
      ```

**Comment by scpeters** [comment]
I see `open-mli` in the last two commands; I'm guessing that's a typo and it should be `open-mpi`?

**Comment by RandomDSdevel** [comment]
@scpeters:  Oof, should have looked for more of those; I saw one, but didn't catch the ones you saw before submitting this issue.  I'm fixing them now…

**Comment by RandomDSdevel** [comment]
@scpeters:  Reported upstream as open-mpi/ompi#5000.

**Comment by RandomDSdevel** [comment]
You know, I'm surprised Open MPI's `configure.ac` script didn't detect this and bail because of it…

**Comment by RandomDSdevel** [comment]
Looking through my logs, it appears said script fell back to using some programs it found in `/ur/bin`, which…doesn't make sense, as the JDK installs into `/Library/Java/JavaVirtualMachines`, and I don't _think_ I'd have detritus from any of the old Apple-vended Java installations left lying around (as far as I can remember, this OS X installation hails from after Apple handed releasing Java for Macs back over to Oracle.)  I wonder where _those_ executables came from…?

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Never mind; I don't see any old Apple Java run-time libraries left over on my machine in `/System/Library/Java` (there's no `JavaVirtualMachines` folder in there.)  What I'm dealing with here must therefore all be from within `/System/Library/Frameworks/JavaVM.framework`, which is apparently some infrastructure that's still needed even with the Oracle JREs and JDKs.  (Per [an old message which I found on one of the OpenJDK mailing lists](http://mail.openjdk.java.net/pipermail/macosx-port-dev/2014-February/006388.html) via [this Ask Different answer](https://apple.stackexchange.com/a/192200/70614) when I was looking around to see what information I could jump off from to troubleshoot and make sure I was as free of old Apple Java installations as I _thought_ I was:  

> ⋮
>
> Do NOT remove any content in the JavaVM.framework. Those items are required by Java 7, 8, 9+ as well as Java SE 6. No modern version of OS X has a Java JDK inside there anyway.
>
> ⋮

So, in any case, I'm _not_ crazy and _did_ end up cleaning up after any old Apple Java VMs I might ever have had, if _any._)  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Anyway, if I poke at `/usr/bin/javah` (or `/System/Library/Frameworks/JavaVM.frameworks/Versions/Current/Commands/javah`, the former's symbolic-linking target which behaves identically)&thinsp;—&thinsp;say, by invoking it with its `--version` or `--help` flag&thinsp;—, then here's what I get back:  

```
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home/bin/javah" (-1)
```

If I ask my shell what `$?` is after that, then it prints '`2`,' an error code.  This, of course, is all to be expected, given the circumstances.

**Comment by RandomDSdevel** [comment]
@scpeters:  It's getting a bit late, so I'll probably sign off for the night soon, but I have a pretty good idea of what would need to be patched upstream to get this to work, so I'll work on that tomorrow.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I've now brought this issue's [upstream counterpart](https://github.com/open-mpi/ompi/issues/5000) to the attention of the Open MPI developers' mailing list [here](https://www.mail-archive.com/devel@lists.open-mpi.org//msg20549.html) and have already received [a response](https://www.mail-archive.com/devel@lists.open-mpi.org//msg20550.html) to the thread that my former message started there.  This reply was to the effect that one of Open MPI's developers felt this issue to be important enough to solve at least part of it himself.  I'll still be working on the other part of it, so that's till coming.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This issue will be addressed upstream once open-mpi/ompi#5001 and open-mpi/ompi#5015 get merged.  I'll submit a formula patch to pull them in once they are (I doubt those two changes alone would be enough for upstream to tag a new release…)

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#5001 has now been merged upstream to `master` as [commit `5e12e0f`](https://github.com/open-mpi/ompi/commit/5e12e0f2e517dfdad7bae8bc6f08c7eafa32d163) and is currently in the process of being backported to Open MPI v3.0.x in open-mpi/ompi#5029 pending upstream CI network hiccups.  open-mpi/ompi#5015 should follow shortly.

**Comment by fxcoudert** [comment]
Thanks @RandomDSdevel for chasing the bug and reporting it. Given that it affects a non-default option, I think we'll wait for the fix in the next version.

**Comment by RandomDSdevel** [comment]
@fxcoudert:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I was going to submit the relevant patch in-formula to fix this once said commit landed upstream since I'm the one who's working on that anyway, but OK.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Not that this is nearly as relevant before since @fxcoudert has indicated that Homebrew Core is just going to wait for the Open MPI v3.0.2 to get this fix and the previous one relevant here and has not indicated interest in reopening this issue for me to submit a formula patch to incorporate both of them, but open-mpi/ompi#5015 has now been merged upstream.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'm going to go ahead and follow up on this issue by submitting a PR to fix it even though it was never reopened for this to happen.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OK, I think I've got everything sorted out now.  Just a second and I'll have a new version of this PR ready for CI, which I'll also test locally…
