### ISSUE TITLE
OSError: [Errno 1] Operation not permitted: '/usr/local/Cellar/node/9.10.1/bin/node'

### ISSUE THREAD

**Issue by nasyxx** [Homebrew/homebrew-core#26020]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

gist logs here: https://gist.github.com/nasyxx/e54c33cbd236c46bb81a284018d0fe89

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I was trying to install node with openssl using `brew install node --with-openssl`. But it failed.

```
if [ ! -r node -o ! -L node ]; then ln -fs out/Release/node node; fi
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python tools/install.py install '' '/usr/local/Cellar/node/9.10.1'
installing /usr/local/Cellar/node/9.10.1/bin/node
Traceback (most recent call last):
  File "tools/install.py", line 227, in <module>
    run(sys.argv[:])
  File "tools/install.py", line 221, in run
    if cmd == 'install': return files(install)
  File "tools/install.py", line 138, in files
    action([output_prefix + output_file], 'bin/' + output_file)
  File "tools/install.py", line 76, in install
    def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
  File "tools/install.py", line 76, in <lambda>
    def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
  File "tools/install.py", line 68, in try_copy
    return shutil.copy2(source_path, target_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/usr/local/Cellar/node/9.10.1/bin/node'
make: *** [install] Error 1
```

I have tried to execute `chown -R $USER:$(id -gn $USER) /usr/local/Cellar`, however it’s still not enough permissions.

What should I do to solve this problem?

**Comment by ilovezfs** [comment]
Sorry, I cannot reproduce this. You may need to reinstall Homebrew.
