### ISSUE TITLE
Notmuch manpages are not linked/built

### ISSUE THREAD

**Issue by ahmedelgabri** [Homebrew/homebrew-core#26067]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`
```
HOMEBREW_VERSION: 1.5.13-22-g46f583c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 46f583c4f72c45eaf30a30171494ca81b0f59208
Last commit: 27 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 84bfc71884899f1f6513888bcd4ce66125f45ee1
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_GITHUB_TOKEN: set
HOMEBREW_GITHUB_USER: ahmedelgabri
HOMEBREW_ROOT: /usr/local
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.1 build 902
Git: 2.16.3 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.26.1/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.5.1/bin/ruby
Java: 1.8.0_152, 1.8.0_144
macOS: 10.13.4-x86_64
Xcode: 9.3
CLT: 9.3.0.0.1.1521514116
X11: 2.7.11 => /opt/X11
```

`brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com
```

To help us debug your issue please explain:
- What you were trying to do (and why) 
Checking the man page of `notmuch`, simply running `man notmuch-config`

- What happened (include command output) 
I get an error `No manual entry for notmuch-config`

- What you expected to happen that 
To open the manpage

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
$ brew install notmuch
$ man notmuch-config
No manual entry for notmuch-config
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
Not installing man pages isn't itself a bug (unless you see docs-specific build-time deps) but we'd review a PR adding them. Thanks for the report @ahmedelgabri

**Comment by ahmedelgabri** [comment]
@ilovezfs I don't mind opening a PR, as far as I can tell it might be something like

```ruby
system "make", "<TASK>"
```

But I need some help understanding the `Makefile` structure in `notmuch` codebase too many nested `Makefile`s and the `build-man` task is inside one of those nested ones https://github.com/notmuch/notmuch/blob/master/doc/Makefile.local#L85-L99. 

Also how to deal with the `ifeq ($(HAVE_SPHINX),0)` check inside the formula?

**Comment by ilovezfs** [comment]
https://github.com/notmuch/notmuch/blob/040c3236afcf95bead0324a48c2e0b9cd7934993/configure#L632-L641

So `depends_on "sphinx-doc" => :build` should automatically cause that to get set.

**Comment by ahmedelgabri** [comment]
@ilovezfs PR is here but I'm stuck with one thing, can you have a look and let me know how I can fix it? https://github.com/Homebrew/homebrew-core/pull/26072
