### ISSUE TITLE
how install php@7.1 with intl

### ISSUE THREAD

**Issue by 550502-kudravets** [Homebrew/homebrew-core#26079]
Hello, how after merge php-homebrew to homebrew-core i can install. php@7.1 with intl ?

**Comment by Adsada2205** [comment]
ในวันที่ อ. 3 เม.ย. 2018 01:40 Ilya <notifications@github.com> เขียนว่า:

**Comment by jpirkey** [comment]
The default install has it enabled already, so simply doing `brew install php@7.1` ... if you `php -i | grep intl|` you'll see it is installed.

**Comment by Romain** [comment]
@jpirkey Thanks, `intl` is indeed installed by default.
How would you do for `mcrypt` or `redis` for instance?

**Comment by jpirkey** [comment]
i believe they added mcrypt recently to the base install as well even though it was deprecated in 7.1 by php.

i believe all other extensions are expected to be installed by pecl based on the readme here: https://github.com/kabel/homebrew-php-ext

**Comment by kabel** [comment]
Use `/usr/local/opt/php@7.1/bin/php -m` to see what all is included by default. Redis can be installed via `/usr/local/opt/php@7.1/bin/pecl install redis`. If you migrated from Homebrew/php, be sure to check your config `/usr/local/etc/php/7.1/php.ini` to make sure it's compatible with the new homebrew default `/usr/local/etc/php/7.1/php.ini.default` (if exists)

**Comment by gamort** [comment]
Hmm, however PECL is no installed with PHP 7.1, making it useless

**Comment by kabel** [comment]
It absolutely is. If it's not there, you got a bad build.

**Comment by gamort** [comment]
I just install PHP@7.1 and it's not in there.   Should I reinstall?

**Comment by kabel** [comment]
If you built from source, yes. Before you do back up `/usr/local/etc/php/7.1/` and remove it.

**Comment by gamort** [comment]
Thanks, seems to have worked..   Now to reinstall everything I need for simple dev using php 7.1 CLI

**Comment by patrickomeara** [comment]
How do we specify a particular version we want installed `brew install php@7.2.3` returns 

```
Updating Homebrew...
Error: No available formula with the name "php@7.2.3"
```

`brew install php` currently installs 7.2.4

**Comment by ilovezfs** [comment]
We don't provide formulae for specific patch-level releases. 7.2 in Homebrew will always be the latest patch level of the 7.2.x series. You'd need to maintain 7.2.3 in [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap).

```
git -C $(brew --repo homebrew/core) show 7ca74edbd9e7c204dc31dfc8b474bff8db5ed468:Formula/php.rb
```

**Comment by Romain** [comment]
Thanks a lot @kabel.
I also confirm @gamort comment. I had to reinstall php@7.1 to have PECL activated.

**Comment by patrickomeara** [comment]
Perfect, thanks so much @ilovezfs
