### ISSUE TITLE
Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so'?

### ISSUE THREAD

**Issue by JesseLeite** [Homebrew/homebrew-core#26074]
I used to have `php71` and `php71-intl` installed with brew.  Now that everything PHP is being moved into homebrew-core, brew update screwed up a bunch of things with my PHP installation.

![help](https://user-images.githubusercontent.com/5187394/38201473-70e8200a-3666-11e8-88fc-f6671d2d4a37.jpg)

I've tried uninstalling everything PHP related, then I ran:

```
brew install php@7.1
brew link --overwrite --force php@7.1
```

[Here's my brew gist-log for php@7.1](https://gist.github.com/JesseLeite/efd9bb94dafdaa83a1012e80baf07560)

While it seems to link fine (see above screenshot), I can't get rid of that php71-intl.so warning, and now I can't run [Valet](https://github.com/laravel/valet) to serve up sites anymore.

![screen shot 2018-04-02 at 11 15 41 am](https://user-images.githubusercontent.com/5187394/38201741-44ae5d3c-3667-11e8-895c-7ccda7c7c41a.png)

Anyone else having this issue?  Kinda stuck here without a fully working version of PHP 😢

**Comment by riverway-developer** [comment]
same problem(

**Comment by jasongroulx** [comment]
I've been fighting the same issue all morning.

**Comment by ilovezfs** [comment]
Remove the config files.

**Comment by Neodork** [comment]
The fix is actually quite easy. Since the library is now in the core of PHP and should be managed using pecl. One should delete the include in the conf.d directory of the PHP version you're running. E.G: For PHP 7.1 I would remove the following:

```
/usr/local/etc/php/7.1/conf.d/ext-intl.ini
```

**Comment by JesseLeite** [comment]
Nice, that fixed the intl error, thank you!  Now I'm getting this, though maybe it's unrelated.

![screen shot 2018-04-02 at 12 06 35 pm](https://user-images.githubusercontent.com/5187394/38203764-4de96250-366e-11e8-881b-18d736281272.png)

**Comment by Neodork** [comment]
That is actually a valet+ which does not belong to the homebrew repository. I will soon open a new issue within the valet-plus. Valet-plus is currently still using the old tap and needs to be rebuild for the new kind of PHP management provided by homebrew/core.

**Comment by JesseLeite** [comment]
100%, thank you sirs.

**Comment by mistre83** [comment]
I'm having the same error. From when moved repo from homebrew/php to homebrew/core my dev enviroment no longer works! Two days of search to fix all the issues and no solution right now!!!

**Comment by Neodork** [comment]
@mistre83 You could fix your PHP installation by following the instructions in https://github.com/weprovide/valet-plus/issues/127#issuecomment-378914908.

**Comment by aginanjar** [comment]
@Neodork you saved my day..
