### ISSUE TITLE
I can't install php70-intl

### ISSUE THREAD

**Issue by AleksLi** [Homebrew/homebrew-core#26080]
Already downloaded: /Users/aleksli/Library/Caches/Homebrew/php70-intl-7.0.27.tar.bz2
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-intl/7.0.27_24 --with-php-config=/usr/local/opt/php70/bin/php-config --enable-intl --with-icu-dir=/usr/local/opt/icu4c
==> make
Last 15 lines from /Users/aleksli/Library/Logs/Homebrew/php70-intl/03.make:
                        ^
/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/intl_convertcpp.cpp:59:40: error: unknown type name 'UnicodeString'; did you mean 'icu_61::UnicodeString'?
zend_string* intl_charFromString(const UnicodeString &from, UErrorCode *status)
                                       ^~~~~~~~~~~~~
                                       icu_61::UnicodeString
/usr/local/Cellar/icu4c/61.1/include/unicode/unistr.h:286:20: note: 'icu_61::UnicodeString' declared here
class U_COMMON_API UnicodeString : public Replaceable
                   ^
4 errors generated.
make: *** [intl_convertcpp.lo] Error 1
make: *** Waiting for unfinished jobs....
mkdir collator/.libs
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/collator/collator.c  -fno-common -DPIC -o collator/.libs/collator.o
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/collator/collator_class.c  -fno-common -DPIC -o collator/.libs/collator_class.o
 clang -I/usr/local/Cellar/icu4c/61.1/include -Wno-write-strings -D__STDC_LIMIT_MACROS -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl -DPHP_ATOM_INC -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/include -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/main -I/private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl -I/usr/local/Cellar/php70/7.0.27_19/include/php -I/usr/local/Cellar/php70/7.0.27_19/include/php/main -I/usr/local/Cellar/php70/7.0.27_19/include/php/TSRM -I/usr/local/Cellar/php70/7.0.27_19/include/php/Zend -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext -I/usr/local/Cellar/php70/7.0.27_19/include/php/ext/date/lib -I/usr/local/Cellar/icu4c/61.1/include -DHAVE_CONFIG_H -g -O2 -c /private/tmp/php70-intl-20180402-90827-s9p89m/php-7.0.27/ext/intl/collator/collator_sort.c  -fno-common -DPIC -o collator/.libs/collator_sort.o

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by SMillerDev** [comment]
php 7.0 isn't in homebrew/core so that would be the biggest issue. For the PHP versions that are in core the intl extension is part of the PHP binary though.

**Comment by AleksLi** [comment]
hi @SMillerDev .
I've installed php70-intl using this [instructions](https://github.com/Homebrew/homebrew-php/issues/4831) .

```
brew untap homebrew/php
brew tap kyslik/homebrew-php

brew install kyslik/php/php70-intl
#or 
brew reinstall kyslik/php/php70-intl

brew untap kyslik/homebrew-php
brew tap homebrew/php
```
Those instruction above helped

**Comment by SMillerDev** [comment]
Homebrew/php is deprecated

**Comment by ilovezfs** [comment]
php70 has now been imported into homebrew/core as php@7.0 and includes the intl module built-in statically. `brew upgrade`
