### ISSUE TITLE
flake8 installs version built with python2

### ISSUE THREAD

**Issue by j9ac9k** [Homebrew/homebrew-core#26116]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew gist-logs:

https://gist.github.com/dc473f44ef73436d10f130ffc1cabcf3

To help us debug your issue please explain:
- What you were trying to do (and why)

I am installing the flake8 package.  Installation occurred without a problem.

- What happened (include command output)

Installation succeeded, however the flake8 version provided references CPython 2.7.

```bash
bash-4.4$ brew install flake8
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/flake8-3.5.0.high_sierra.bo
Already downloaded: /Users/ogi/Library/Caches/Homebrew/flake8-3.5.0.high_sierra.bottle.tar.gz
==> Pouring flake8-3.5.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/flake8/3.5.0: 530 files, 5.9MB
bash-4.4$ flake8 --version
3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 2.7.10 on Darwin
bash-4.4$ 
```

- What you expected to happen

Expecting flake8 to be installed against the current homebrew python (3.6.5)

- Step-by-step reproduction instructions (by running `brew install` commands)

```bash
$ brew install flake8
$ flake8 --version
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
This is not a bug. Most Python-using formulae still currently use Python 2 provided by macOS itself.
