### ISSUE TITLE
Can't run "brew doctor" or "brew upgrade".

### ISSUE THREAD

**Issue by CCF100** [Homebrew/homebrew-core#26117]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

Attempting to run brew upgrade or brew doctor produces this:
`Calebs-MacBook-Air:~ calebfontenot1$ brew upgrade
Error: 784: unexpected token at ''
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:64:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:59:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:59:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:59:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:104:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:304:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:295:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:35:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Calebs-MacBook-Air:~ calebfontenot1$ brew doctor
Error: 784: unexpected token at ''
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:64:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:59:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:59:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:59:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:104:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:304:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:295:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:907:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:904:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:904:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'`

**Comment by ilovezfs** [comment]
This is something specific to your machine. You may need to reinstall Homebrew.
