### ISSUE TITLE
Don't want to sound funny but feels like you messed up homebrew/php to bring hell to PHP developers

### ISSUE THREAD

**Issue by ferrazzuk** [Homebrew/homebrew-core#26113]
Don't want to sound funny but feels like you messed up homebrew/php to bring hell to PHP developers

**Comment by ferrazzuk** [comment]
I now believe hell is real ... Thanks Ruby developers.

**Comment by ferrazzuk** [comment]
On a real note. Homebrew/php was good as it was before the update. If at least this update was backwards compatible I would be happy with it. Unless I'm exaggerating and not understanding how to migrate then I'm open to some constructive answers.

**Comment by fxcoudert** [comment]
Please report your problem, fill out the template for new issues. We cannot help you fix a problem that you have not described in detail.

**Comment by SMillerDev** [comment]
As a PHP developer myself, I'm happy macOS doesn't have completely different ways of installing packages anymore compared to upstream. All it takes is a little getting used to the PHP way.

**Comment by ferrazzuk** [comment]
@SMillerDev good to know ... It was just so easier to do the old way. Just an unlink and link and you would be working on a different project which uses a different PHP version. Because of how easy it was a lot of PHP developers (I don't think you're one) started to use homebrew. I can guarantee you a lot of other developer are going to rise the same issue over and over again.

**Comment by ferrazzuk** [comment]
Also this is not to say I'm not willing to do the "proper" way. Its just frustrating how of a big change this is. I mean why put it there in the first place and then from a day to another decide "Hey lets just change it" ...

**Comment by SMillerDev** [comment]
Work on this started almost a year ago: https://github.com/Homebrew/homebrew-core/pull/16067
and an issue was created to inform people halfway through January https://github.com/Homebrew/homebrew-php/issues/4721

**Comment by ferrazzuk** [comment]
@SMillerDev funny enough none of my known PHP developers knew about this. How are we meant to know such changes from a pull request? Why not at least at something to your site informing people of it or add a some sort of "flag" to warn us in the prior updates? I'm sure there would be a more informative way than just expecting all of us using it to keep up to date with pull requests. Not so productive my fellow ruby developer.

**Comment by SMillerDev** [comment]
Like this caveat that was added 2 months ago: https://github.com/Homebrew/homebrew-php/commit/7d187ab980c3a3628db3bfea748868e8f44d0210 ?

**Comment by ferrazzuk** [comment]
@SMillerDev fair enough 👍

**Comment by GBeushausen** [comment]
Wow great work guys. Being with a customer, had to update homebrew and all of a sudden PHP is not working anymore. Can't switch PHP versions and then found out you messed it all up. Thanks.

**Comment by samvdb** [comment]
I agree, thanks for borking every php developer's installation on OSX.

Great job guys

**Comment by ferrazzuk** [comment]
@SMillerDev You guys clearly under estimated your product and how much mac PHP developers depended on it.

**Comment by samvdb** [comment]
For everyone that's experiencing the same issues. Remove all php stuff from brew with brew remove --force and then checkout this project: https://php-osx.liip.ch/

Make sure to update your $PATH variable.

**Comment by SMillerDev** [comment]
Yes, shame on us for spending our weekends and other spare time on a free and open source project that we don't get compensated for.

**Comment by GBeushausen** [comment]
@SMillerDev As most of us make a living using your product, i would have no problem paying you for commercial support. If you don't charge people who would pay you within a blink of an eye, it's your problem. But abandoning this kind of software where so many people rely on it is just plain irresponsible.

**Comment by MikeMcQuaid** [comment]
Everyone complaining needs to read this: https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/.  Some people are getting banned based on their communication in this thread.
