### ISSUE TITLE
how could i install php extensions after homebrewphp deprecated

### ISSUE THREAD

**Issue by ChristianYeah** [Homebrew/homebrew-core#26139]
I just know that the homebrew/php is deprecated, and im not able to install the ext pcntl as before
I tried to build it from source but im stuck in the missing php.h error

SOS

**Comment by kabel** [comment]
It's already built by default. No need to try to install it separately or build it yourself. Run `php -m` and see.

**Comment by ChristianYeah** [comment]
@kabel actually, it's not installed. what should I do atm. thank you

**Comment by ChristianYeah** [comment]
there's something weird as well. I ran ```brew upgrade``` early today, and I want to check installed php ext or php it self using ```brew list | grep php```.  I got the result below. Should I remove all of them and reinstall the php?
```
$ brew list | grep php
php-cs-fixer
php71
php71-intl
php71-xdebug
php@7.1
```
