### ISSUE TITLE
PHP 7.0 - Imap + Imagick libraries

### ISSUE THREAD

**Issue by jsgv** [Homebrew/homebrew-core#26132]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

**

When I did a `brew upgrade` this morning it broke my installed PHP configuration.
I need to install php 7.0 with Imap and Imagick support. 
How can I install these additional libraries with the new Homebrew PHP formulas?

**Comment by vcraescu** [comment]
same here. apparently all the extra extensions i need are gone. :(

**Comment by kabel** [comment]
imagick can/should be install via `pecl install imagick` (`/usr/local/opt/php@7.0/bin/pecl install imagick` for 7.0). Make sure you have the imagemagick dependency installed first from homebrew.

imap has a stability problem and was removed from Homebrew/core at #25579. If you understand the and accept the risk, you can install it from my [tap](https://github.com/kabel/homebrew-php-ext).

**Comment by vcraescu** [comment]
But what about the other? php-redis, php-ampq? Can be install via pecl?

**Comment by kabel** [comment]
Yes, but really these are questions to ask outside of the Homebrew/core issue tracker. Please also review and familiarize yourself with the [pecl site].(https://pecl.php.net/)

**Comment by sschueller** [comment]
You can't just deprecate `homebrew-php` and not migrate all or at least most php extensions. No one uses `pecl` or `pear` anymore these days. Most php extensions are installed via a package manager such as `apt`. 

In addition: 
```
/usr/local/opt/php@7.1/bin/pecl install imagick
```
Results in a `ERROR: failed to mkdir /usr/include/php/ext/imagick`. `/usr` is a protected area of OSX and can not be written in by even using sudo.

**Comment by ilovezfs** [comment]
@sschueller most extensions were indeed migrated and are now included statically (see the output `php -m`). Some that weren't can be found in https://github.com/kabel/homebrew-php-ext

Also, please watch your tone.

**Comment by sschueller** [comment]
For anyone who had problems. 

1. Remove all your old brew php packages. 
2. install php `brew install php@7.1`
3. Relink with `brew link --force php@7.1`
4. update your PECL `pecl channel-update pecl.php.net`
5. Reinstall imagemagick and autoconf `brew reinstall imagemagick` `brew reinstall autoconf`.
6. compile image magick `pecl install imagick`. 
7. Add it to your PHP php.ini (/usr/local/etc/php/7.1/php.ini) `extension=imagick.so`
8. make a symlink to the lib (this may differ on your system): `cd /usr/local/Cellar/php@7.1/7.1.16/lib/php/20160303` `ln -s ../../../pecl/20160303/imagick.so`

**Comment by jsgv** [comment]
@2case I agree. 

If a migration was needed, why not just move all the taps and allow for the same configuration options? Now I have to find an alternative solution for managing my PHP versions.

**Comment by SMillerDev** [comment]
@2case are you paying ours?

**Comment by sschueller** [comment]
@SMillerDev are you telling me there is no support from Apple at all for homebrew? Do you have any funding?

A tool which is vital to so many developers and probably used by tons of Apple employees needs to be properly funded.

**Comment by kabel** [comment]
Let's all remain civil as we work through the pains of shifting priorities, standards, and community policies. Don't forget https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/

**Comment by SMillerDev** [comment]
@sschueller I wish. There was an interesting discussion about that at the Free and Open source Software Developers' European Meeting this year. (https://www.youtube.com/watch?v=RYsHV-SW0Vw)

**Comment by MikeMcQuaid** [comment]
> This php-core decision break so many development environments and was far away from any real life work... and you call others for watch your tone? Sorry, but this is currently time and cost intensiv to rebuild our environments. Are you paying the bills?

@2case Many volunteers (particularly @kabel @javian @ilovezfs @SMillerDev) have spent their evenings and weekends working on this software that you get to use for free. If that makes it slightly harder for you to earn money with Homebrew because you did not plan for the pre-announced date: that is completely and utterly your problem to deal with.

**Comment by javian** [comment]
@sschueller you shouldn't need to perform the last two steps in your guide since pecl should automatically add the line to php.ini and you shouldn't need to create a symlink manually. If this doesn't work by default see https://github.com/Homebrew/homebrew-core/issues/26108#issuecomment-378223868
