### ISSUE TITLE
Misleading caveats for DNSCrypt

### ISSUE THREAD

**Issue by TheIronBorn** [Homebrew/homebrew-core#26135]
https://github.com/Homebrew/homebrew-core/blob/c1c4ae655a4a884b18ae0cd39d49e8b0a2659978/Formula/dnscrypt-proxy.rb#L39-L40
Isn't this no longer true for version >2?  Seems to me default behavior is to use the fastest resolver.

**Comment by TheIronBorn** [comment]
> [Load balancing: pick a set of resolvers, dnscrypt-proxy will automatically measure and keep track of their speed, and balance the traffic across the fastest available ones.](https://github.com/jedisct1/dnscrypt-proxy/blob/master/README.md)

**Comment by ilovezfs** [comment]
@DomT4 thoughts?

**Comment by DomT4** [comment]
Certainly not impossible I missed that line amongst the caveats.

OP is correct here at least, as reflected in the config file [here](https://github.com/jedisct1/dnscrypt-proxy/blob/d4367393c4d0e510cac69d078435203771a33de5/dnscrypt-proxy/example-dnscrypt-proxy.toml#L19-L30). The caveats can be tweaked to reflect that.

**Comment by ilovezfs** [comment]
This should now be fixed @TheIronBorn. Thanks for reporting it

**Comment by TheIronBorn** [comment]
Sorry for the late reply but:

This looks great! thanks
