### ISSUE TITLE
Yarn - cannot brew install yarn - SHA256 Mismatch error

### ISSUE THREAD

**Issue by thehogg13** [Homebrew/homebrew-core#26140]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [-] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

When trying to Run `brew install yarn` , i get a SHA256 mismatch error;

`adm3923@MBP0023  ~/Development/postmunger $ brew config                                                                           
HOMEBREW_VERSION: 1.5.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7fd6210127f088b6ee8708a1d7f4ec2df3fc5bb4
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 45684521b23189968eb66af125a58623be980e00
Core tap last commit: 49 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.16.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A`

` adm3923@MBP0023  ~/Development/postmunger $ brew doctor                                                                             
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libProxyHook.dylib
  /usr/local/lib/libwep_chrome.dylib
  /usr/local/lib/libwep_ff.dylib
  /usr/local/lib/libwep_pref.dylib
  /usr/local/lib/libwep_proxy.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/ares.h
  /usr/local/include/node/ares_version.h
  /usr/local/include/node/nameser.h
  /usr/local/include/node/node_internals.h
  /usr/local/include/node/pthread-fixes.h`

` adm3923@MBP0023  ~/Development/postmunger $ brew install yarn                                                                       
Updating Homebrew...
==> Downloading https://yarnpkg.com/downloads/1.5.1/yarn-v1.5.1.tar.gz
==> Downloading from https://github.com/yarnpkg/yarn/releases/download/v1.5.1/yarn-v1.5.1.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: cd31657232cf48d57fdbff55f38bfa058d2fb4950450bd34af72dac796af4de1
Actual: 8277d6db14352cdc3a337165c9893e14e57677ff591fa23acf563c8ced563825
Archive: /Users/adm3923/Library/Caches/Homebrew/yarn-1.5.1.tar.gz
To retry an incomplete download, remove the file above.`

**Comment by ilovezfs** [comment]
Try
```
brew fetch -f yarn
```

The checksum is correct so this is specific to your machine.
```
Josephs-MacBook-Pro:~ joe$ curl -sL https://yarnpkg.com/downloads/1.5.1/yarn-v1.5.1.tar.gz | shasum -a256 
cd31657232cf48d57fdbff55f38bfa058d2fb4950450bd34af72dac796af4de1  -
```

**Comment by thehogg13** [comment]
👍  - thanks for the help
