### ISSUE TITLE
Eigen patch no longer works with cmake 3.11.0

### ISSUE THREAD

**Issue by ikoruk** [Homebrew/homebrew-core#26158]
When building from source on High Sierra and the most recent cmake, the fix in the patch of eigen.rb no longer works.

```
-- Found BLAS: /usr/lib/libblas.dylib
CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindMPI.cmake:1179 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindMPI.cmake:1196 (_MPI_try_staged_settings)
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindMPI.cmake:1382 (_MPI_check_lang_works)
  cmake/FindPASTIX.cmake:235 (find_package)
  test/CMakeLists.txt:83 (find_package)
```

**Comment by ikoruk** [comment]
https://gist.github.com/ikoruk/5e69de832d2a7f0ba4a8fc0282f03287

`> brew doctor
Your system is ready to brew.`

**Comment by fxcoudert** [comment]
- Do you have `gcc` installed? If not, can you try with `gcc` installed? That's the only thing I can think of.
- Can you try compiling `brew install eigen --HEAD` and report the result?

**Comment by ikoruk** [comment]
Yes with `gcc` installed it works but since Eigen is a header-only library, I don't think it makes sense to force `gfortran` to exist.

`brew install eigen --HEAD` without `gcc` installed fails as well.

**Comment by ilovezfs** [comment]
OK that's only if `libmpc` is installed. I'm still having trouble reproducing this locally.

**Comment by fxcoudert** [comment]
I can reproduce on my system if I unlink gcc.

So apparently this is an upstream bug, still present in head, that is only triggered when `gfortran` is not present on the system. This should be reported upstream, for them to fix.

**Comment by ilovezfs** [comment]
It was accidentally succeeding on my case sensitive file system by not finding `FindPASTIX.cmake`.

If I
```
mv cmake/FindPastix.cmake cmake/FindPASTIX.cmake
```
then I am able to reproduce the failure.

**Comment by chhtz** [comment]
If you think this is an issue with Eigen, could you file it as bug under http://eigen.tuxfamily.org/bz/?
Ideally, also try to bisect the issue to the commit which broke it (or provide a patch that fixes it). 

I use neither macOS nor homebrew, so I can't check without much effort.

**Comment by ikoruk** [comment]
@chhtz I can't report a bug since I can't sign up for an account. I'm not sure exactly what broke it because 3.3.4, which used to work, now doesn't. But I bisected and the breaking revision seems to be  10425: "Improve cmake scripts for Pastix and BLAS detection."

**Comment by ikoruk** [comment]
@chhtz By the way, do you all have any plans to bump the version number any time soon? There have been quite a few bug fixes since last June...

**Comment by mrabbah** [comment]
Getting the same error, while installing opencv3 : brew reinstall -fs opencv, I got this error : "/usr/local/opt/eigen not present or broken Please reinstall eigen. Sorry :(", and when I run : brew reinstall -fs eigen,  I got this error: 
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/rabbah/Library/Logs/Homebrew/eigen/01.cmake:
-- Checking for one of the modules 'hwloc'
-- Found BLAS: /usr/lib/libblas.dylib  
CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage
CMake Error at /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindMPI.cmake:1179 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindMPI.cmake:1196 (_MPI_try_staged_settings)
  /usr/local/Cellar/cmake/3.11.0/share/cmake/Modules/FindMPI.cmake:1382 (_MPI_check_lang_works)
  cmake/FindPASTIX.cmake:235 (find_package)
  test/CMakeLists.txt:83 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/eigen-20180406-16357-o4rshp/eigen-eigen-5a0156e40feb/eigen-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/eigen-20180406-16357-o4rshp/eigen-eigen-5a0156e40feb/eigen-build/CMakeFiles/CMakeError.log".

**Comment by chhtz** [comment]
For a more minimal workaround, you could also try `-DPASTIX_LOOK_FOR_MPI=OFF` -- it looks like the actual bug is in your local FindMPI.cmake, though.

**Comment by fxcoudert** [comment]
`FindMPI.cmake` is from cmake 3.11.0, not a local modification.

**Comment by chhtz** [comment]
Yes, I meant the FindMPI which is installed on your local machine. Try configuring a minimal cmake project, which includes `find_package(MPI QUIET)` (or without the `QUIET`)

**Comment by ikoruk** [comment]
A separate project with find_package(MPI) simply fails to find it with no problems. The problem, as the error states, stems from EnableLanguage of Fortran without any CMAKE_Fortran_COMPILER. I guess this is due to eigen's method to detect whether or not fortran is installed in cmake/FindPASTIX.cmake. I ran reverting to cmake 3.10.0 and I get the same error.

Neither `-DBUILD_TESTING=OFF` or `-DPASTIX_LOOK_FOR_MPI=OFF` seem to help.

**Comment by chhtz** [comment]
Could you post the output of running cmake with `-DBUILD_TESTING=OFF --debug-output`? It looks like FindPASTIX is called from `bench/spbench/CMakeList.txt` as well.

**Comment by ggael** [comment]
Fixed upstream: https://bitbucket.org/eigen/eigen/commits/ba14974d054a so you will have to apply this trivial patch too until 3.3.5 is released (soon)
