### ISSUE TITLE
Request: Add `--keg-only` option to `brew list`

### ISSUE THREAD

**Issue by Zearin** [Homebrew/homebrew-core#26165]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Get a list of all keg-only formulae that I have installed with Homebrew.

- What happened (include command output)

I searched for an appropriate option in the autocompletion, in `brew help list`, and in `man brew`, but cannot find one.

- What you expected to happen

I wanted to find such an option.

- Step-by-step reproduction instructions (by running `brew install` commands)

Type `brew ls --`, then hit tab.

**Comment by ilovezfs** [comment]
This is an interesting suggestion but is a better issue for Homebrew/brew. CC @MikeMcQuaid

**Comment by chdiza** [comment]
I have an external cmd I made that does this.  I don't have access to it right now, but when I'm on the relevant machine I will post that part of the code here.

**Comment by Zearin** [comment]
@chdiza cool! Thanks. 

Do you think this has a chance of becoming an official part of Homebrew (even if it requires moving this Issue to another repo)?

**Comment by Zearin** [comment]
Hm.  That is disappointing to hear…

…But then again, if it was years ago, perhaps it’s worth another shot.  Homebrew may not have been rewritten from scratch during that time, but it _has_ changed quite a bit.

**Comment by MikeMcQuaid** [comment]
> If it's a general brew problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new.

For future reference: please file future issues like this there.

> Get a list of all keg-only formulae that I have installed with Homebrew.

This is a bit niche for us I'm afraid. You can get the information you want with `brew info --installed` and `brew info --json=v1 --installed`. The latter combined with `jq` may be useful.

Sorry!
