### ISSUE TITLE
[Question] How to remove a deprecated formula name?

### ISSUE THREAD

**Issue by mmelvin0** [Homebrew/homebrew-core#26173]
I checked all the documentation and couldn't find an answer to this.

I've upgraded from `homebrew-php/php71` to `php@7.1`, moved over to PECL for the few extensions I need, removed all the `php71-*` packages corresponding to those extensions, and my PHP install is working fine.

I've also ran `brew cleanup php71`.

However, brew list still shows `php71` **and** `php@7.1` installed. This is the case for a few other packages as well.

I noticed that `/usr/local/Cellar/php71` is a symlink to `/usr/local/Cellar/php@7.1`. Is it reasonable to simply remove this symlink? Removing it does remove the entry from `brew list`. Is there a way to do this with some `brew` command instead?

**Comment by Blackskyliner** [comment]
With uninstall -- For me it was easier to uninstall all homebrew-php packages like described here https://github.com/Homebrew/homebrew-core/issues/26107 -- This will make your whole setup like a clean install of php. As if the old tap never existed. :smile: -- In case you wonder where all the extensions went, a just in case link to my other issue: see https://github.com/Homebrew/homebrew-core/issues/26108

The `php71` was auomatically migrated to `php@7.1` by `brew upgrade` and the migration of a package in homebrew is done through symlinking I guess, thats why your setup is as it is now.

**Comment by mmelvin0** [comment]
That's overkill.

I'm just looking to clean up the old package name and trying to confirm:

1. It is just the `/usr/local/Cellar/php71` symlink or if there is other stuff I should look for.
2. Is there an "officially blessed" way to remove the old package name?
3. Is this something that I will happen automatically/in the future and is best just ignored for now.

FWIW, I did remove the `/usr/local/Cellar/php71` symlink and it seems to have the desired result and everything is working fine and the Homebrew seems to no longer know anything about a `php71` package.

**Comment by ilovezfs** [comment]
If it's showing both in the output that sounds like possibly a Homebrew/brew issue. CC @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
This is an implementation detail of `brew list` which basically just runs `ls`. If anyone can figure out how to make it omit symlinks: we'd welcome a PR.
