### ISSUE TITLE
brew php merge: php71-intl (and other shared extensions)

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-core#26203]
as https://github.com/Homebrew/homebrew-php/pull/4798 discussion is archived, can't post there.

but i have note and opinion on my own, if `brew upgrade php@7.1` was able to migrate `php71`, it should similarly remove `php71-intl`, because `intl` extension is now statically compiled into `php@7.1` and the old `php71-intl` just adds the same extension as shared, but fails due icu version mismatch. 

the solution is to just uninstall php71-intl after php@7.1 (or php@7.0, php@7.2 respectively) and manually cleanup config.

```
$ php71 -m|grep intl
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): image not found in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): image not found in Unknown on line 0
intl

$ brew remove php71-intl
Uninstalling /usr/local/Cellar/php71-intl/7.1.14_25... (7 files, 543.6KB)

$ php71 -m|grep intl
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): image not found in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): image not found in Unknown on line 0
intl

$ rm /usr/local/etc/php/7.1/conf.d/ext-intl.ini
$ php71 -m|grep intl
intl
$
```

**Comment by glensc** [comment]
while this seems one time problem, but many will encounter this.

maybe add ass php@7.x caveats note how to upgrade if not possible to remove other packages with php@7.x install process.

**Comment by Goal54** [comment]
I try to install php71-intl to use bin/cake (cakephp). I can't since this change :'( What can I do ?

**Comment by ilovezfs** [comment]
`brew install php@7.1`. The intl module is already built-in statically. See `php -m` output

**Comment by SMillerDev** [comment]
intl is now compiled into the PHP binary

**Comment by Goal54** [comment]
I didn't see it in php-m :/

**Comment by ilovezfs** [comment]
Thanks for the suggestion @glensc. I think at this point we want to keep the caveats in the php formulae focused on how they work currently not on migration issues but we're happy to look at a pull request if you have a specific change in mind.
