### ISSUE TITLE
php formulae no longer support --with-imap

### ISSUE THREAD

**Issue by thewunder** [Homebrew/homebrew-core#26209]
The old formulae in homebrew-php had a --with-imap option

The imap core extension is part of core and not in pecl, so there is no longer an easy way to install this.  Please either restore this option, or just compile with the imap ext (which will also require imap-uw)

**Comment by ilovezfs** [comment]
You can find that one here: https://github.com/kabel/homebrew-php-ext

We had to remove it do to upstream performance issues. See https://github.com/Homebrew/homebrew-core/pull/25579

We may restore it if those are fixed at some point.

**Comment by thewunder** [comment]
Thanks for the quick answer!
