### ISSUE TITLE
How to install php71-apc with new merge?

### ISSUE THREAD

**Issue by borjadinamic** [Homebrew/homebrew-core#26204]
$ brew install php71-apcu-bc
Error: No available formula with the name "php71-apcu-bc"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

How can I install the APC module for PHP71 with the new tap?

**Comment by SMillerDev** [comment]
With the migration to Homebrew-core the php formula has stopped taking over the role of PECL. Installing apcu_bc can (and should) be done through PECL (https://pecl.php.net/package/apcu_bc).

**Comment by ilovezfs** [comment]
In the future please fill out the template in its entirety @borjadinamic
