### ISSUE TITLE
problem with brew install graph-tool

### ISSUE THREAD

**Issue by dautovri** [Homebrew/homebrew-core#26202]
```
brew install graph-tool
Updating Homebrew...
Error: No available formula with the name "graph-tool" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

```
Link to graph-tool
http://formulae.brew.sh/formula/graph-tool

**Comment by hjmallon** [comment]
Graph-tool was in homebrew science. It might work if you follow instructions to add this tap https://github.com/brewsci/homebrew-science.

It would seem to be a bug that they are still listed on the website, see https://github.com/Homebrew/formulae.brew.sh/issues/100

**Comment by commitay** [comment]
PR adding `graph-tool` to this repo: https://github.com/Homebrew/homebrew-core/pull/22819
