### ISSUE TITLE
Install additional PHP-extensions

### ISSUE THREAD

**Issue by FaimMedia** [Homebrew/homebrew-core#26215]
I cannot find any information about how to install additional PHP extensions, such as Phalcon or Imagick.

Since 1.5 this doesn't work anymore:

```
brew install php72-phalcon

Error: No available formula with the name "php72-phalcon" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

```
brew install php72-imagick

Error: No available formula with the name "php72-imagick" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

Websites report:
[http://formulae.brew.sh/formula/php72-phalcon](url): _Formula was removed_
[http://formulae.brew.sh/formula/php72-imagick](url): _Formula was removed_

What? Why?
How can I install extensions with homebrew?

**Comment by jpirkey** [comment]
It's expected that going forward you'll have to use pecl to install those.  The maintainers decided to move hombrew-php to homebrew-core and with that move, dropped the extension packages.  It is either installed with the core package `php` or handled by `pecl`.

**Comment by asentner** [comment]
Has the apache DSO support been dropped? No longer generating a library.

**Comment by FaimMedia** [comment]
@jpirkey So I have to compile them from source on every update?
Seems like to much work for me, I will be switching back to VirtualBox with a Linux OS then.

**Comment by MikeMcQuaid** [comment]
> Seems like to much work for me, I will be switching back to VirtualBox with a Linux OS then.

@FaimMedia Feel free, what tools you use are no real concern of ours.

**Comment by 8090Lambert** [comment]
Fuck

**Comment by HavenShen** [comment]
@MikeMcQuaid That's right for you. The "Topic Terminator".
