### ISSUE TITLE
bre upgrade failed while configuring librsvg

### ISSUE THREAD

**Issue by chriswit68** [Homebrew/homebrew-core#26251]
==> Upgrading 28 outdated packages, with result:
libtensorflow 1.4.1 -> 1.7.0, gmp 6.1.2_1 -> 6.1.2_2, adwaita-icon-theme 3.26.1 -> 3.28.0_1, go 1.9.2 -> 1.10.1, pygobject3 3.26.1 -> 3.28.2, gtk+3 3.22.26 -> 3.22.29_1, gdbm 1.13 -> 1.14.1_1, python 2.7.14 -> 3.6.5, libunistring 0.9.8 -> 0.9.9, gtksourceview3 3.24.6 -> 3.24.7_1, atk 2.26.1 -> 2.28.1_2, geoip 1.6.11 -> 1.6.12, dbus 1.12.2 -> 1.12.4, grafana 4.6.3 -> 5.0.4, c-ares 1.13.0 -> 1.14.0, lua 5.3.4_2 -> 5.3.4_3, influxdb 1.4.2 -> 1.5.1, htop 2.0.2 -> 2.1.0_1, librsvg 2.40.20 -> 2.42.2_1, libtasn1 4.12 -> 4.13, py2cairo 1.15.4 -> 1.16.3, libepoxy 1.4.3 -> 1.5.0_1, p11-kit 0.23.9 -> 0.23.10, protobuf 3.5.1 -> 3.5.1_1, wireshark 2.4.3_1 -> 2.4.6, git 2.15.1 -> 2.17.0, gnutls 3.5.16 -> 3.5.18, gsettings-desktop-schemas 3.24.1 -> 3.28.0
==> Upgrading gsettings-desktop-schemas 
==> Downloading https://homebrew.bintray.com/bottles/gsettings-desktop-schemas-3.28.0.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/0b/0bd6835780ef3b7b9b2940c8c2e33b8257bc367883d897905e3c55ace5c35033?__gda__=exp=1523000538~hmac=ea16a0c6e7e131ad7aee97af0eaaa2b16ed
######################################################################## 100.0%
==> Pouring gsettings-desktop-schemas-3.28.0.high_sierra.bottle.tar.gz
==> /Users/chriswit/opt/homebrew/opt/glib/bin/glib-compile-schemas /Users/chriswit/opt/homebrew/share/glib-2.0/schemas
🍺  /Users/chriswit/opt/homebrew/Cellar/gsettings-desktop-schemas/3.28.0: 96 files, 4.0MB
==> Upgrading gmp 
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/83/8372dcd88e36997d7aacaffb555709348cc2c57703608b3471cbd71f5054f9ed?__gda__=exp=1523000541~hmac=243d593f65b9aaac7becacddf09af1e1ae2
######################################################################## 100.0%
==> Pouring gmp-6.1.2_2.high_sierra.bottle.tar.gz
🍺  /Users/chriswit/opt/homebrew/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
==> Upgrading adwaita-icon-theme 
==> Installing dependencies for adwaita-icon-theme: librsvg
==> Installing adwaita-icon-theme dependency: librsvg
==> Downloading https://download.gnome.org/sources/librsvg/2.42/librsvg-2.42.2.tar.xz
Already downloaded: /Users/chriswit/Library/Caches/Homebrew/librsvg-2.42.2.tar.xz
==> ./configure --prefix=/Users/chriswit/opt/homebrew/Cellar/librsvg/2.42.2_1 --disable-Bsymbolic --enable-tools=yes --enable-pixbuf-loader=yes --enable-introspection=yes
Last 15 lines from /Users/chriswit/Library/Logs/Homebrew/librsvg/01.configure:
checking for gdk-pixbuf-2.0 >= 2.20... yes
checking for gdk-pixbuf-query-loaders... /Users/chriswit/opt/homebrew/opt/gdk-pixbuf/bin/gdk-pixbuf-query-loaders
checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.13 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for glib-2.0 >= 2.10.0 gobject-2.0  >= 2.10.0... yes
checking whether to build miscellaneous tools... yes
checking whether to build Rust code with debugging information... no
checking for gobject-introspection... configure: error: gobject-introspection-1.0 is not installed

READ THIS: https://docs.brew.sh/Troubleshooting

Error: undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x000001023a5c48>
Did you mean?  check_for_tap_ruby_files_locations
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/Users/chriswit/opt/homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump'
/Users/chriswit/opt/homebrew/Library/Homebrew/exceptions.rb:425:in `each'
/Users/chriswit/opt/homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:157:in `rescue in upgrade_formula'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:169:in `upgrade_formula'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:95:in `block in upgrade'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `each'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `upgrade'
/Users/chriswit/opt/homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by tschoonj** [comment]
Thanks for reporting this issue. I opened a PR that will fix this.
