### ISSUE TITLE
Error while upgrading gtksourceview3 / configuring vala

### ISSUE THREAD

**Issue by chriswit68** [Homebrew/homebrew-core#26329]
==> Upgrading gtksourceview3 
==> Installing dependencies for gtksourceview3: graphviz, vala
==> Installing gtksourceview3 dependency: graphviz
==> Downloading https://www.mirrorservice.org/sites/distfiles.macports.org/graphviz/graphviz-2.40.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/Users/chriswit/opt/homebrew/Cellar/graphviz/2.40.1 --without-qt --with-quartz --disable-php --disable-swig --without-pangocairo --without-freetype2 --wit
==> make install
🍺  /Users/chriswit/opt/homebrew/Cellar/graphviz/2.40.1: 500 files, 11.2MB, built in 3 minutes 55 seconds
==> Installing gtksourceview3 dependency: vala
==> Downloading https://download.gnome.org/sources/vala/0.40/vala-0.40.2.tar.xz
==> Downloading from https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnome.org/sources/vala/0.40/vala-0.40.2.tar.xz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/Users/chriswit/opt/homebrew/Cellar/vala/0.40.2
==> make
==> make install
🍺  /Users/chriswit/opt/homebrew/Cellar/vala/0.40.2: 416 files, 13.4MB, built in 3 minutes 36 seconds
==> Installing gtksourceview3
==> Downloading https://download.gnome.org/sources/gtksourceview/3.24/gtksourceview-3.24.7.tar.xz
==> Downloading from https://ftp.fau.de/gnome/sources/gtksourceview/3.24/gtksourceview-3.24.7.tar.xz
######################################################################## 100.0%
==> ./configure --enable-vala=yes --prefix=/Users/chriswit/opt/homebrew/Cellar/gtksourceview3/3.24.7_1
Last 15 lines from /Users/chriswit/Library/Logs/Homebrew/gtksourceview3/01.configure:
checking how to link with libintl... -lintl -Wl,-framework -Wl,CoreFoundation
checking for gtk-doc... no
configure: WARNING:
  You will not be able to create source packages with 'make dist'
  because gtk-doc >= 1.25 is not found.
checking for gtkdoc-check... no
checking for gtkdoc-check... no
checking for gtkdoc-rebase... no
checking for gtkdoc-mkpdf... no
checking whether to build gtk-doc documentation... no
checking for GTKDOC_DEPS... yes
checking for gobject-introspection... no
checking whether to build with code coverage support... no
checking for valgrind... no
configure: error: Vala bindings require GObject Introspection

READ THIS: https://docs.brew.sh/Troubleshooting

Error: undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x0000010223bda8>
Did you mean?  check_for_tap_ruby_files_locations
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/Users/chriswit/opt/homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump'
/Users/chriswit/opt/homebrew/Library/Homebrew/exceptions.rb:425:in `each'
/Users/chriswit/opt/homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:157:in `rescue in upgrade_formula'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:169:in `upgrade_formula'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:95:in `block in upgrade'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `each'
/Users/chriswit/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:92:in `upgrade'
/Users/chriswit/opt/homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by tschoonj** [comment]
#26337 should fix this problem.

Thanks for opening the issue!

**Comment by fxcoudert** [comment]
Thanks @chriswit68 for the report and thanks @tschoonj for the fix!
