### ISSUE TITLE
Upgrading freetds always changes freetds.conf

### ISSUE THREAD

**Issue by wgcltd** [Homebrew/homebrew-core#26348]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen

-----

I submitted this at the Homebrew Community Discussion and was asked to repeat it here.

I have **freetds** set up with Homebrew, but every time it upgrades, it points the symlink /usr/local/etc/freetds.conf to the _new_ version’s freetds.conf file - which of course is not configured correctly. So if freetds is upgraded by Homebrew, I must remember to copy over the old freetds.conf file every time. I tried setting my own .freetds.conf file in my home directory but that does not work either. All programs always use the /usr/local/etc version. Does anyone have a similar issue with this and how to fix?

I got this response:

MikeMcQuaid Leader
This is a bug that indicates that the way the configuration is being installed is incorrect. Could you report this issue to homebrew-core (and fill out the issue template)? Thanks!

**Comment by ilovezfs** [comment]
@wgcltd this is now fixed if you `brew reinstall freetds`

**Comment by wgcltd** [comment]
Ok, I think that did it. /usr/local/etc/freetds.conf is no longer a symlink. Thanks!
