### ISSUE TITLE
Homebrew Python and `install_headers` distutils directive

### ISSUE THREAD

**Issue by SylvainCorlay** [Homebrew/homebrew-core#26347]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

----------- 

I wanted to report that the distutils scheme for homebrew's python does not have the typical behavior with respect to the installation of third-party headers:

When using homebrew's python, 

 - the Python include directory is correctly set to 

   ```
   /usr/local/Cellar/python/X.Y.Z/Frameworks/Python.framework/Versions/X.Y/include/pythonX.Y'
   ```

   which is where the `Python.h` header will be found, and the returned value of `sysconfig.get_path('include')`.

 - However, when installing a Python package that makes use of the `install_headers` distutils directive, the headers for that package will be installed under

   ```
   /usr/local/include/pythonX.Y
   ```

The typical behavior for Python distribution is for the `install_headers` to install headers under the `sysconfig.get_path('include')` directory... Also, I imagine that this directory is probably reserved to the system's python

A means to retrieve the header installation directory has been to get the "distutils_scheme" from pip. Alternatively, one can do

```
dist = Distribution({'name': 'pybind11'})
dist.parse_config_files()
dist_cobj = dist.get_command_obj('install', create=True)
dist_cobj.finalize_options()
print(os.path.dirname(dist_cobj.install_headers))
```

**Comment by ilovezfs** [comment]
This is by design. We want to avoid having third-party stuff end up in the Cellar since it would have to be reinstalled every time the formula is upgraded.
