### ISSUE TITLE
MacVim failed to build on 10.13

### ISSUE THREAD

**Issue by isaachier** [Homebrew/homebrew-core#26352]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs macvim --build-from-source` (where `macvim --build-from-source` is the name of the formula that failed) and included the output link? https://gist.github.com/isaachier/4f4c6dcae9c17428a49929a10d125d39
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Rebuild MacVim from source to fix libraries that were upgraded during previous `brew upgrade`.
- What happened (include command output): Seems that the final installation steps invoked an undefined Ruby method.
- What you expected to happen: The installation to succeed.
- Step-by-step reproduction instructions (by running `brew install` commands): `brew reinstall macvim --build-from-source`.

**Comment by rakkesh** [comment]
https://gist.github.com/isaachier/4f4c6dcae9c17428a49929a10d125d39#file-02-make-L119
>xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

```sh
$ brew info macvim
....
==> Requirements
Build: xcode ✘
```
Firstly, make sure you have `Xcode.app` and then, set it as active developer library.
If you have, `Xcode.app` under `/Applications` directory, then execute the following command -
```sh
$ sudo xcode-select -switch /Applications/Xcode.app
```

**Comment by whalesingswee** [comment]
I am having this issue as well. I can confirm it's not the `Xcode-select` problem. I simply run `brew install macvim --with-override-system-vim` it's not working as well.

**Comment by rakkesh** [comment]
@whalesingswee If `brew install macvim --with-override-system-vim` doesn't work for you, please create another issue with `brew gist-logs macvim`. I am able to build `macvim` with aforementioned formula options - https://gist.github.com/fbefc146af8e55c4ba279fa3cef6cc6c.

**Comment by isaachier** [comment]
I have Xcode and frankly do not believe that error is the root cause. The linking succeeded as mentioned before. The issue remains that the script invokes an undefined method.

**Comment by isaachier** [comment]
Looking over the gist I cannot see the Ruby error I see locally. Let me try to reproduce when I get a chance and I will try the fix above as well.

**Comment by rakkesh** [comment]
@isaachier I would also suggest you to upgrade `Xcode.app` ( `9.3` ) for `macOS 10.13.4`.

**Comment by ilovezfs** [comment]
This is something to do with your local configuration but feel free to keep talking here despite my closing this.

**Comment by isaachier** [comment]
```
$ brew info macvim
macvim: stable 8.0-146 (bottled), HEAD
GUI for vim, made for macOS
https://github.com/macvim-dev/macvim
/usr/local/Cellar/macvim/8.0-146 (2,156 files, 34.4MB) *
  Poured from bottle on 2018-04-09 at 13:20:53
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/macvim.rb
==> Dependencies
Recommended: cscope ✔, python ✔
Optional: lua ✔, luajit ✘, python@2 ✔
==> Requirements
Build: xcode ✔
```

**Comment by isaachier** [comment]
Any ideas why my xcode would have a check but not actually work?

**Comment by whalesingswee** [comment]
@isaachier try running `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

**Comment by isaachier** [comment]
I just updated Xcode and somewhere between that and running the above `sudo xcode-select -switch /Applications/Xcode.app` seems to have fixed it. Thank you all.

**Comment by isaachier** [comment]
It seems somewhere between upgrading Xcode (and opening it once) and using `sudo xcode-select -switch /Applications/Xcode.app` as suggested above solved the issue. Thank you all for your help.
