### ISSUE TITLE
CI failures related to installing homebrew python

### ISSUE THREAD

**Issue by mroch** [Homebrew/homebrew-core#26358]
I've started getting build failures from both Travis and Circle that I think are related to #26287.

```
==> Pouring python@2-2.7.14_3.sierra.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-2
Target /usr/local/bin/2to3-2
is a symlink belonging to python. You can unlink it:
  brew unlink python
To force the link and overwrite all conflicting files:
  brew link --overwrite python@2
To list all files that would be deleted:
  brew link --overwrite --dry-run python@2
Possible conflicting files are:
/usr/local/bin/2to3-2 -> /usr/local/Cellar/python/2.7.14/bin/2to3-2
/usr/local/bin/2to3-2.7 -> /usr/local/Cellar/python/2.7.14/bin/2to3-2.7
/usr/local/bin/idle2 -> /usr/local/Cellar/python/2.7.14/bin/idle2
...
```

https://travis-ci.org/facebook/flow/jobs/364227445
https://circleci.com/gh/facebook/flow/1954

seems like it's already using a homebrew python and failing while trying to overwrite with a different version.

**Comment by ilovezfs** [comment]
Run `brew upgrade python` as a first step and the problem should go away.

**Comment by ilovezfs** [comment]
`brew uninstall python` may also work.

**Comment by mroch** [comment]
@ilovezfs this isn't a bug? seems like it's trying to upgrade from python 2.7.14 to 2.7.14_3, and it's doing it automatically as a dependency of installing something else, and the instructions don't mention either of your suggestions, so it seems like there's room for improvement here

**Comment by ilovezfs** [comment]
@mroch nope not a bug. The `python` formula was upgraded to be Python 3 and a newly added formula, `python@2`, is now Python 2. So if you have something that depends on the new `python@2`, but you haven't upgraded your `python` formula yet, then there will be a conflict between that outdated `python` installation and the new `python@2` formula.
