### ISSUE TITLE
Error: Your Command Line Tools are too outdated

### ISSUE THREAD

**Issue by yufeiliubrown** [Homebrew/homebrew-core#26385]
To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install openssl with command 'brew install openssl'.

- What happened (include command output)
I got an error:
Error: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

- What you expected to happen
However, I already have the most up-to-date version of Xcode and running 'softwareupdate --list' got me nothing.

I also ran 'brew update' and got 'Already up-to-date.'

- Step-by-step reproduction instructions (by running `brew install` commands)
I have mac version '10.13.3' and Xcode version 9.3

**Comment by ilovezfs** [comment]
Run `xcode-select --install` and click install, not get xcode.
