### ISSUE TITLE
wine 3.0 hang when updating configurations at first time

### ISSUE THREAD

**Issue by chuanchan1116** [Homebrew/homebrew-core#26384]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

# Gist-Logs
https://gist.github.com/chuanchan1116/97f4f079c4e31d8d1f30bf3314da13e2

# Problems
When I install wine from clean or upgrade from older version, it always hang at the first-time update of the configurations. 

This problem has been around since devel version in 2.x before and I thought it was a problem in wine, but I found that this bug does not exist in the pkg version [here](https://dl.winehq.org/wine-builds/macosx/pool/winehq-stable-3.0.pkg). I guess it's a problem in the make process.

# Output
running winecfg after upgrading or installing wine for the first time.
```
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0028:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0028:fixme:dwmapi:DwmIsCompositionEnabled 0x6dbd1518
0043:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0xc06600, init_notify 0, handle 0x14ffa40): stub
0028:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0009:err:process:__wine_kernel_init boot event wait timed out
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
002b:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
```

**Comment by fxcoudert** [comment]
No idea :(

**Comment by adunning** [comment]
This was [reported a few months ago on Discourse](https://discourse.brew.sh/t/wine-first-time-configuration-gets-stuck-forever-on-macos/1612), and has something to do with the 64-bit support. I don't quite understand it, because it only happens sometimes: it occurs on my machine if one tries to initialize the prefix by running `winetricks` before doing anything else. Everything is fine if I just run `wine`; or if I set `WINEARCH=win32` with another command (e.g. `WINEARCH=win32 winetricks fontsmooth=rgb` with no existing prefix).

This is why I was [musing about building without 64-bit support](https://discourse.brew.sh/t/changing-wine-formula-to-compile-without-64-bit-support/1946) or putting something in the caveats, but it would be nice to know what is causing this, and if it really is a problem with the Homebrew version.

**Comment by chuanchan1116** [comment]
@adunning I doubt if it is caused by the 64-bit support. This problem appear on my computer after 2.x (I forgot which version). Before I always use 64-bit version and never encountered this problem. Moreover, this problem does not happened on current pkg version distributed from winehq, so I guess the problem may be in the make process.

By the way, I'm using Traditional Chinese locale setting. The package from homebrew only display in English, but one from pkg display Traditional Chinese well. I think the make process is quite different from the one building pkg.

**Comment by LinusU** [comment]
For me this happens not only when running winetricks. I have observed it every time I'm using a fresh wineprefix.

It doesn't happen when running the official prebuilt version from winehq.com, I have tried both 32 and 64bit of that one.

**Comment by ilovezfs** [comment]
Still a problem with 3.0.1?

**Comment by hrabe** [comment]
@ilovezfs Yes, it's still a problem on MacOS using 3.0.1

**Comment by vincent-lu** [comment]
I'm having the same problem reported above, for both version 3.0.0 and 3.0.1

**Comment by warent** [comment]
This should be reopened.

Mac 10.12.6 
wine 3.0.2

Just happened to me as well.

**Comment by SteveBrooker** [comment]
And for me
Mac 10.13.5
Wine 3.0.2

**Comment by ilovezfs** [comment]
Please feel free to open a PR with a fix. Locking.
