### ISSUE TITLE
I try to get php working on OSX 10.13.4. All seems to work properly. Update and doctor show nothing. Then I find, that extensions are missing. I search for intl and get:

### ISSUE THREAD

**Issue by rnrkrft** [Homebrew/homebrew-core#26402]
PHP on OSX 10.13.4
Reinstalled everything
"update" and "doctor" show no problems
But as my script needs some extensions, I found, that they are missing on the system, or are not configured right. I searched for "intl" and got a long list with "failed loading" 

[Failed loading.txt](https://github.com/Homebrew/homebrew-core/files/1894219/Failed.loading.txt)

**Comment by ilovezfs** [comment]
`intl` is included statically. Note the output of `php -m`. You'll need to remove the old config ini files to make those errors go away.

In the future please always fill out the issue template.

**Comment by rnrkrft** [comment]
Sorry, was not finished and not meant to send. One klick to quick.
Thanks for help I worked on it  for hours…
