### ISSUE TITLE
gist no longer works due to GitHub dropping TLS 1.0 support

### ISSUE THREAD

**Issue by gsnedders** [Homebrew/homebrew-core#26400]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
pnin:css2 gsnedders$ brew config
HOMEBREW_VERSION: 1.6.0-2-g4682108
ORIGIN: https://github.com/Homebrew/brew
HEAD: 468210840ca4a80b2f314736ddb9905181a8b3ae
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
bCore tap HEAD: 9e3dd781c3021e457852a8b3f5b0a39ae68ba340
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
reGit: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_74
macOS: 10.12.6-x86_64
w CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11
pnin:css2 gsnedders$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  autoconf213
  cvsps
pnin:css2 gsnedders$ brew gist-logs gist
Error: No logs.
```

I've not fixed all `brew doctor` issues because none relate to Ruby or gist; the unlinked kegs are ones that clash with others, and the unexpected header file is added by an external package.

To help us debug your issue please explain:
- What you were trying to do (and why)

Use the gist command installed by the gist formula

- What happened (include command output)

```
Error: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
```

- What you expected to happen

A gist to be uploaded

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gist
echo foo | gist -
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

I'm hoping you're okay with issues which are "the built formulae doesn't work at all", because I don't know how to fix it. I presume it's the old OpenSSL on macOS and using the system Ruby?

**Comment by commitay** [comment]
Closed via #26401

`brew update && brew upgrade gist`
