### ISSUE TITLE
Homebrew-php cannot install any package view pecl  (no target to make)

### ISSUE THREAD

**Issue by enyosolutions** [Homebrew/homebrew-core#26441]
- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Hello

**I'm having an issue with php install that have been driving me nuts for hours.**

The `Homebrew-php` team has deprecated their php repository and moved it to the core repository. They've also removed a lot of extensions. 

I'm trying to install `apcu`, so i had to upgrade my php install, in order to have `pecl` support and install `apcu`.

But after the upgrade, it's been impossible to install anything using `pecl`. all the installs fail at the same step with the same error message.

    running: make
    make: *** No rule to make target `/private/tmp/pear/temp/pear-build-faouCc1Nmz/yaml-2.0.2/modules/yaml.la', needed by `all'.  Stop.
    ERROR: `make' failed

## Here is what i have tried : 

- installing different packages : yaml / mongodb / intl => same error 
- downloaded the package to install it manually => same error at the make level.
- Remove all php related installs and start fresh (https://github.com/Homebrew/homebrew-core/issues/26107)
- Set the extension directory correctly (https://github.com/Homebrew/homebrew-core/issues/26108)

All that without success. 
**Can some one help me please ?**

## My config : 

- macbook + Sierra
- Homebrew 1.6.0
- php 7.2 (same problem with 7.1)

**Comment by javian** [comment]
Did you remove the php config in `/usr/local/etc/php/7.x...` when you started fresh ? intl is also bundled in the new Formula so you don't need to install that separately .

**Comment by enyosolutions** [comment]
Yes i did, i moved out completely the php folder from `/user/local/etc` . I only one 7.2 in `/usr/local/etc/php`

**Comment by ilovezfs** [comment]
Hopefully this is now fixed if you `brew upgrade`. Let us know if you're still having problems.

**Comment by enyosolutions** [comment]
@ilovezfs i'm still getting the issues. my php version vas bumped to 7.2.4

but still no luck :(
