### ISSUE TITLE
proj has been updated not formulas depending on it

### ISSUE THREAD

**Issue by 3nids** [Homebrew/homebrew-core#26479]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
**Using postgis 2.4.4. after an upgrade**
- What happened (include command output)
```
ERROR:  could not load library "/usr/local/lib/postgresql/rtpostgis-2.4.so": dlopen(/usr/local/lib/postgresql/rtpostgis-2.4.so, 10): Library not loaded: /usr/local/opt/proj/lib/libproj.12.dylib
  Referenced from: /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
  Reason: image not found
```
- What you expected to happen
well, to work!
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

So, formulas which needs new bottles:

* libgeotiff
* libspatialite

**Comment by 3nids** [comment]
brew gist-logs for libspatialite
https://gist.github.com/243803205149df2056ecd1c79df4b145

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ otool -L /usr/local/lib/postgresql/rtpostgis-2.4.so 
/usr/local/lib/postgresql/rtpostgis-2.4.so:
	/usr/local/opt/gdal/lib/libgdal.20.dylib (compatibility version 24.0.0, current version 24.3.0)
	/usr/local/opt/geos/lib/libgeos_c.1.dylib (compatibility version 12.0.0, current version 12.2.0)
	/usr/local/opt/proj/lib/libproj.13.dylib (compatibility version 14.0.0, current version 14.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
iMac-TMP:~ joe$ otool -L /usr/local/opt/libgeotiff/lib/libgeotiff.dylib 
/usr/local/opt/libgeotiff/lib/libgeotiff.dylib:
	/usr/local/opt/libgeotiff/lib/libgeotiff.2.dylib (compatibility version 4.0.0, current version 4.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/proj/lib/libproj.13.dylib (compatibility version 14.0.0, current version 14.0.0)
	/usr/local/opt/jpeg/lib/libjpeg.9.dylib (compatibility version 13.0.0, current version 13.0.0)
	/usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 9.0.0, current version 9.0.0)
iMac-TMP:~ joe$ otool -L /usr/local/opt/libspatialite/lib/libspatialite.dylib 
/usr/local/opt/libspatialite/lib/libspatialite.dylib:
	/usr/local/opt/libspatialite/lib/libspatialite.7.dylib (compatibility version 9.0.0, current version 9.0.0)
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/freexl/lib/libfreexl.1.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/proj/lib/libproj.13.dylib (compatibility version 14.0.0, current version 14.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/opt/sqlite/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/usr/local/opt/geos/lib/libgeos_c.1.dylib (compatibility version 12.0.0, current version 12.2.0)
iMac-TMP:~ joe$ 
```
So you probably just need to run `brew upgrade`.
