### ISSUE TITLE
No formulae for php71-imagick

### ISSUE THREAD

**Issue by agiovinazzi** [Homebrew/homebrew-core#26474]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Before homebrew was moved from homebrew/php to homebrew/core was so simple to install imagick for php (`brew install php71-imagick`).

Now, when i try to install it i get the following errors:
```
Error: No available formula with the name "php71-imagick"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by raphaelsaunier** [comment]
I came here to report this as well; it doesn't seem to be available with the current PHP formula (7.2) either.

**Comment by SMillerDev** [comment]
@raphaelsaunier is correct. With the migration to Homebrew-core the php formula has stopped taking over the role of PECL. Installing imagick can (and should) be done through PECL (https://pecl.php.net/package/imagick).

**Comment by raphaelsaunier** [comment]
Using PECL clearly feels like the better approach. Perhaps this could be listed in the caveats of the formula? The first thing I did was to run `brew info php` and I didn’t see anything about this change…

**Comment by SMillerDev** [comment]
Could you make a pull request for that? (you might have a better idea of the things that should be mentioned there)

**Comment by ilovezfs** [comment]
:+1: to improved caveats
