### ISSUE TITLE
Problem with xfig in MacOS

### ISSUE THREAD

**Issue by enriquesquintana** [Homebrew/homebrew-core#26518]
Hi,

I am trying to install xfig on my MacOS. I followed these steps:
brew tap mistydemeo/homebrew-xfig
brew cask install xquartz
brew install xfig
==> Installing xfig from mistydemeo/xfig
==> Installing dependencies for mistydemeo/xfig/xfig: gmp, mpfr, libmpc, isl, gcc, imake, transfig
==> Installing mistydemeo/xfig/xfig dependency: gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/08/087052cc1b49f5e0c42f5bd54f463f7fca7f7c
######################################################################## 100.0%
==> Pouring gmp-6.1.2_2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
==> Installing mistydemeo/xfig/xfig dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.0.1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a2/a29b4585cb97715cdab177ea586b3fbee2c578
######################################################################## 100.0%
==> Pouring mpfr-4.0.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/4.0.1: 28 files, 4.6MB
==> Installing mistydemeo/xfig/xfig dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.1.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libmpc-1.1.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.1.0: 12 files, 353.9KB
==> Installing mistydemeo/xfig/xfig dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.19.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/23/23c7305a7f227e1749a15584eb203ec9f1f49f
######################################################################## 100.0%
==> Pouring isl-0.19.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.19: 66 files, 3.8MB
==> Installing mistydemeo/xfig/xfig dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-7.3.0_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/ee/eef4c6b68313e913b3c71329575699e960a384
######################################################################## 100.0%
==> Pouring gcc-7.3.0_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gcc/7.3.0_1: 1,486 files, 284MB
==> Installing mistydemeo/xfig/xfig dependency: imake
==> Downloading https://homebrew.bintray.com/bottles/imake-1.0.7_3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/60/60c503d489aea63b678f857c5b58284023b3f7
######################################################################## 100.0%
==> Pouring imake-1.0.7_3.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/imake/1.0.7_3: 144 files, 1.2MB
==> Installing mistydemeo/xfig/xfig dependency: transfig
==> Downloading https://homebrew.bintray.com/bottles/fig2dev-3.2.6a_1.sierra.bottle.tar.g
==> Downloading from https://akamai.bintray.com/fa/faf054ca4097373006a95bde74efc792a663bc
######################################################################## 100.0%
==> Pouring fig2dev-3.2.6a_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/fig2dev/3.2.6a_1: 84 files, 816.2KB
==> Installing mistydemeo/xfig/xfig
==> Downloading http://downloads.sourceforge.net/mcj/xfig.3.2.5c.full.tar.gz
==> Downloading from http://downloads.sourceforge.net/project/mcj/mcj-source/xfig.3.2.5c.
######################################################################## 100.0%
Error: uninitialized constant Formulary::FormulaNamespace463a4d1c15d015f781e9f88cd35d3086::Xfig::DATA
Did you mean?  Data
               Date
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/mistydemeo/homebrew-xfig/xfig.rb:24:in `patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1904:in `prepare_patches'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1094:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'

Any help?

**Comment by woodruffw** [comment]
I'm guessing this is a problem with the [xfig custom tap](https://github.com/mistydemeo/homebrew-xfig), so raising an issue there might be more useful.

(ccing @mistydemeo just in case I'm wrong about that)

**Comment by fxcoudert** [comment]
Indeed, this should be reported to the tap, as xfig is not a core formula.

The latest xfig version builds very nicely on macOS, and the formula should probably be simplified somewhat:

```
class Xfig < Formula
  desc "Interactive drawing tool"
  homepage "https://mcj.sourceforge.net/"
  url "https://downloads.sourceforge.net/project/mcj/xfig-3.2.6a.tar.xz"
  sha256 "a87aeb5d424aadb84ede137291bbe8649551209a807c94f0956fc323b819267c"

  depends_on "jpeg"
  depends_on :x11

  def install
    system "./configure", "--prefix=#{prefix}",
                          "--disable-dependency-tracking",
                          "--disable-silent-rules"
    system "make", "install"
  end

  test do
    assert_match "Xfig #{version}", shell_output("#{bin}/xfig -v 2>&1")
  end
end
```
