### ISSUE TITLE
libfaketime should depend on coreutils

### ISSUE THREAD

**Issue by jsoref** [Homebrew/homebrew-core#26568]
- [x] are reporting a bug others will be able to reproduce and not asking a question.
- [x] have a problem with `brew install` a single, official formula (not cask)?
```sh
$ brew info libfaketime
libfaketime: stable 0.9.7 (bottled), HEAD
Report faked system time to programs
https://github.com/wolfcw/libfaketime
/usr/local/Cellar/libfaketime/0.9.7 (9 files, 93.4KB) *
  Poured from bottle on 2018-04-13 at 13:33:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libfaketime.rb
==> Requirements
Required: macOS >= 10.7 ✔
==> Options
--HEAD
	Install HEAD version
```
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```sh
$ brew gist-logs libfaketime
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
install and use `faketime` (`libfaketime`)

- What happened (include command output)
```sh
$ brew install libfaketime
==> Downloading https://homebrew.bintray.com/bottles/libfaketime-0.9.7.high_sierra.bottle.tar.gz
Already downloaded: /Users/jsoref/Library/Caches/Homebrew/libfaketime-0.9.7.high_sierra.bottle.tar.gz
==> Pouring libfaketime-0.9.7.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libfaketime/0.9.7: 9 files, 93.4KB
$ cp `which date` .
$ faketime '2010-01-01 12:00:00Z' ./date
Running (g)date failed: No such file or directory
Error: Timestamp to fake not recognized, please re-try with a different timestamp.
```

- What you expected to happen
The `libfaketime` package should depend on `coreutils`
- Step-by-step reproduction instructions (by running `brew install` commands)
```sh
brew uninstall --force coreutils
brew install libfaketime
cp `which date` .
faketime '2010-01-01 12:00:00Z' ./date
```

Note: on my system, `coreutils` was installed and linked, and thus `faketime` worked for me.
When I had a colleague install `libfaketime`, `faketime` didn't work, because he hadn't installed `coreutils`. But, essentially `libfaketime` isn't functional without `coreutils`, and thus it should depend on it. For lack of a better reference:
https://github.com/wolfcw/libfaketime/blob/c9a681c3e36c453affb7ff393458478a953d886c/src/faketime.c#L174

Manually "fixing" libfaketime can be achieved by:
`brew install coreutils`
as:
```sh
brew install coreutils
```
After which, this works:
```sh
$ faketime '2010-01-01 12:00:00Z' ./date
Fri Jan  1 07:00:00 EST 2010
```

Note: while my sample includes copying `date` to `.`, that's coincidental. Because of macOS's System Integrity Protection, one can't shim system programs. For our actual use case, we aren't shimming `date`, although we do copy the program we are shimming to a non protected directory in order to shim it.

**Comment by ilovezfs** [comment]
Are you saying it's incompatible with BSD `date` command? That sounds like an upstream porting issue to me.

**Comment by jsoref** [comment]
It *requires* gnu date. That's an upstream choice. And since it requires it, the brew formula needs to make gnu date available.

**Comment by jsoref** [comment]
https://github.com/wolfcw/libfaketime/blob/c9a681c3e36c453affb7ff393458478a953d886c/src/faketime.c#L54

**Comment by ilovezfs** [comment]
Please create an issue upstream about this as I'm not comfortable resorting to a coreutils dependency unless there's some reason the BSD date command cannot do what's needed, which is unlikely.

>the brew formula needs to make gnu date available.

We could simply remove the `faketime` command as the library is still useful without it.

**Comment by jsoref** [comment]
@ilovezfs: in https://github.com/wolfcw/libfaketime/issues/158#issuecomment-381385252 @wolfcw indicates that a distinct package for `faketime` that depended on either a `gdate` or `coreutils` package seems reasonable.

How does that sound to you?

**Comment by ilovezfs** [comment]
@jsoref we'll just depend on `coreutils`. This is now fixed.
