### ISSUE TITLE
i tried installing ipopt in my mac facing the issue:`mumps` is trying to use 'depends_on :mpi' but it should be "open-mpi";

### ISSUE THREAD

**Issue by SarveshShukla23** [Homebrew/homebrew-core#26572]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ yes] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ yes] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [yes ] ran `brew update` and can still reproduce the problem?
- [ yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ yes] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): i was trying to install ipopt for my udacity Mpc project.
- What happened (include command output):while install mumps is trying to use 'depends_on :mpi' but it should be "open-mpi";
- What you expected to happen: download ipopt on my mac
- Step-by-step reproduction instructions (by running `brew install` commands):
i tried installing brew using :
brew install dpo/openblas/ipopt

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
- There is no `mumps` or `ipopt` formula in Homebrew core.
- You are trying to install the `dpo/openblas/ipopt` formula, which is not from Homebrew core: please report the issue to them at https://github.com/dpo/homebrew-openblas/issues
- Despite writing “yes” in the issue template, you did not provide us with `brew gist-logs`, `brew config` and `brew doctor` output so that we can help in any way with your issue.
