### ISSUE TITLE
Macvim no longer installable using --with-override-system-vim

### ISSUE THREAD

**Issue by microwheels** [Homebrew/homebrew-core#26583]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [Gist Log](https://gist.github.com/de81ec42bf823b905b7e4c2b51ec54be)
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was attempting to run `brew install macvim --with-override-system-vim` from my shell because the default vim available on macs doesn't support the features I regularly use.  I've used this successfully on my work machine (last year) but when I attempted to run it on a newly purchased used macbook, it isn't working for me.

Any help or guidance would be greatly appreciated.

Note: `brew install macvim` does work but doesn't use the same archive so it could be an issue with the archive in question.

- What happened (include command output)
The build failed.  Here's the output:
```shell
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-146.tar.gz
Already downloaded: /Users/drewed/Library/Caches/Homebrew/macvim-8.0-146.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp
==> make
Last 15 lines from /Users/drewed/Library/Logs/Homebrew/macvim/02.make:

StripNIB English.lproj/FindAndReplace.nib
    cd /tmp/macvim-20180413-3046-e84rfc/macvim-snapshot-146/src/MacVim
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20180413-3046-e84rfc/macvim-snapshot-146/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20180413-3046-e84rfc/macvim-snapshot-146/src/MacVim/English.lproj/FindAndReplace.nib

** BUILD FAILED **


The following build commands failed:
	StripNIB English.lproj/MainMenu.nib
	StripNIB English.lproj/Preferences.nib
(2 failures)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen
The build to succeed

- Step-by-step reproduction instructions (by running `brew install` commands)
```shell
brew install python3
brew install macvim --with-override-system-vim
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by fxcoudert** [comment]
Solution from the macvim issue tracker:

> If you haven't launched Xcode after updating it, do so now. Xcode will ask for permission to install additional components. Let it install those components.
