### ISSUE TITLE
dcraw fails to download

### ISSUE THREAD

**Issue by bitsapien** [Homebrew/homebrew-core#266]
### Bug reports:

The installation of `dcraw` fails with a 500 Internal Server Error

https://gist.github.com/anonymous/2296d06756be9fcaf8d4188dd154bfec

**Comment by bitsapien** [comment]
A quick-fix before dcraw providers fix the server would be to do this -

```
brew edit dcraw
```
Change this line
```
url "https://www.cybercom.net/~dcoffin/dcraw/archive/dcraw-9.26.0.tar.gz"
```
to 
```
url "http://www.cybercom.net/~dcoffin/dcraw/archive/dcraw-9.26.0.tar.gz"
```
Save the file and exit, run `brew install dcraw` now. It should install without any problems now.

**Comment by ilovezfs** [comment]
Has this been reported to them?

**Comment by ilovezfs** [comment]
This is a secure mirror https://imagemagick.org/download/delegates/dcraw-9.26.0.tar.gz

**Comment by bitsapien** [comment]
Informed the provider. Would you want me to create a pull request after updating the formula with the mirror url?

**Comment by apjanke** [comment]
Added it. https://github.com/Homebrew/homebrew-core/commit/4dbe2400500d5ee6d53b3fa79216fadc797a5f5c

```
$ brew install -s dcraw
==> Using the sandbox
==> Downloading https://www.cybercom.net/~dcoffin/dcraw/archive/dcraw-9.26.0.tar.gz

curl: (22) The requested URL returned error: 500 Internal Server Error
Trying a mirror...
==> Downloading https://imagemagick.org/download/delegates/dcraw-9.26.0.tar.gz
######################################################################## 100.0%
==> clang -o dcraw -I/usr/local/include -L/usr/local/lib dcraw.c -lm -ljpeg -llcms2 -l
🍺  /usr/local/Cellar/dcraw/9.26.0: 3 files, 366K, built in 9 seconds
[/usr/local on ⇄ dcraw-mirror]
$
```

That should take care of this. Once their site is back up, it'll go back to using the main URL; no need to revert the formula later. Feel free to re-open if you have other issues.
