### ISSUE TITLE
 Checksum mismatch for poco 1.9.0

### ISSUE THREAD

**Issue by muellermartin** [Homebrew/homebrew-core#26606]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- ~~[ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~ `bew gist-logs poco` returned `Error: No logs.`
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What I was trying to do (and why)
`brew upgrade --verbose` to upgrade installed packages.
- What happened (include command output)
The upgrade wanted to update `newsboat` and therefore wanted to update its dependency `poco`, but the download of the latter failed:
```
Error: SHA256 mismatch
Expected: 028de410fc78d5f9b1ff400e93ec3d59b9e55a0cbbf0d8fec04636882b72ea45
Actual: 0387bf0f9d313e2311742e1ad0b64e07f2f3e76039eed20e3b9aa9951b88e187
Archive: /Users/martin/Library/Caches/Homebrew/poco-1.9.0.tar.gz
To retry an incomplete download, remove the file above.
```
For a full error log of the upgrade of `poco` see linked Gist at the bottom of the issue.
Deleting the file `/Users/martin/Library/Caches/Homebrew/poco-1.9.0.tar.gz` and redownloading did result in the same error. I also manually downloaded the tarball and checked the signature of the new file. The checksum is indeed different from the one specified in the formula, but the signature of the developers seems to be correct:
```
$ wget https://pocoproject.org/releases/poco-1.9.0/poco-1.9.0-all.tar.gz
…
$ openssl sha -sha256 poco-1.9.0-all.tar.gz 
SHA256(poco-1.9.0-all.tar.gz)= 0387bf0f9d313e2311742e1ad0b64e07f2f3e76039eed20e3b9aa9951b88e187
$ wget https://pocoproject.org/releases/poco-1.9.0/SHASUMS256.txt.asc
…
$ curl https://keybase.io/pocoproject/pgp_keys.asc?fingerprint=9a94fc0b8e686d79ecae10dacd136af3108f7c0b | gpg --import
$ LANG=en gpg --verify SHASUMS256.txt.asc
gpg: Signature made Thu Mar  8 15:34:43 2018 CET
gpg:                using RSA key 9A94FC0B8E686D79ECAE10DACD136AF3108F7C0B
gpg: Good signature from "POCO C++ Libraries <poco@pocoproject.org>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9A94 FC0B 8E68 6D79 ECAE  10DA CD13 6AF3 108F 7C0B
gpg: WARNING: not a detached signature; file 'SHASUMS256.txt' was NOT verified!
```
- What you expected to happen
Successful upgrade including successful download of poco without checksum mismatch.
- Step-by-step reproduction instructions (by running `brew install` commands)
1. `brew upgrade --verbose`

Output from error message, `brew config` and `brew doctor`: https://gist.github.com/muellermartin/60b8f305bc9e81869fa7ab6b25e27407

**Comment by woodruffw** [comment]
I'm able to replicate this:

```sh
$ wget https://pocoproject.org/releases/poco-1.9.0/poco-1.9.0-all.tar.gz
$ sha256sum poco-1.9.0-all.tar.gz 
0387bf0f9d313e2311742e1ad0b64e07f2f3e76039eed20e3b9aa9951b88e187  poco-1.9.0-all.tar.gz
```

I'm guessing they quietly clobbered a release to "fix" something minor.

**Comment by muellermartin** [comment]
Works :) Thanks for fixing the issue!
