### ISSUE TITLE
Agda option --without-ghc@8.2 doesn't work

### ISSUE THREAD

**Issue by karljs** [Homebrew/homebrew-core#26655]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install Agda without the optional GHC dependency.

- What happened (include command output)

Ran `brew install agda --without-ghc@8.2` as suggested by `brew options agda`

- What you expected to happen

Agda to be installed without the GHC formula being pulled in.

- Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew install agda --without-ghc@8.2`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
`ghc@8.2` is still a build-time dependency regardless of the option.
```
  depends_on "ghc@8.2" => :recommended
  if build.with? "ghc@8.2"
    depends_on "cabal-install" => [:build, :test]
  else
    depends_on "cabal-install" => :build
    depends_on "ghc@8.2" => :build
  end
```

**Comment by karljs** [comment]
@ilovezfs If it is only a build-time dependency, why am I forbidden from uninstalling it after the build process is complete?
