### ISSUE TITLE
[feature-request] - dumping out all installation data in homebrew (similarly to linux package managers)

### ISSUE THREAD

**Issue by tmm2018** [Homebrew/homebrew-core#26688]
greetings

it would be nice that whenever you install something on mac using homebrew (no matter if you are using "normal" installation or cask, etc.):
- the terminal dumps out all installation data, similarly to what would happen with any linux package manager

thank you so much :)

**Comment by SMillerDev** [comment]
Looking at the difference between apt and homebrew it's actually pretty similar and you can show more data using the `--verbose` option.
This is however more of a request for the package manager repo: https://github.com/Homebrew/brew instead of the formula repo.

**Comment by tmm2018** [comment]
Hey @SMillerDev 

- I posted the issue on the main repo (brew)
- it was reviewed by a lead programmer of homebrew
- this person is also on the github staff
- my input was not accepted
- not always we have to agree on everything

that's all. 
cheers
