### ISSUE TITLE
p11-kit failed to build on OS X 10.11

### ISSUE THREAD

**Issue by rajiv** [Homebrew/homebrew-core#26703]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

attempting to upgrade p11-kit from 0.23.9 to 0.23.10 and the build failed.

```
==> Upgrading 2 outdated packages, with result:
gnupg 2.2.4 -> 2.2.6, p11-kit 0.23.9 -> 0.23.10
==> Upgrading gnupg 
==> Installing dependencies for gnupg: p11-kit
==> Installing gnupg dependency: p11-kit
==> Downloading https://github.com/p11-glue/p11-kit/releases/download/0.23.10/p11-kit-0.23.10.tar.gz
Already downloaded: /Volumes/black/Users/rajiv/Library/Caches/Homebrew/p11-kit-0.23.10.tar.gz
==> ./configure --disable-silent-rules --disable-trust-module --prefix=/Volumes/black/Users/rajiv/homebrew/Cellar/p11-kit/0.23.10 --sysconfdir=/Volumes/black/Users/ra
==> make
==> make check
Last 15 lines from /Volumes/black/Users/rajiv/Library/Logs/Homebrew/p11-kit/03.make:
# PASS:  31
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/p11-glue/p11-kit/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check] Error 2
```

full logs: https://gist.github.com/rajiv/7a2d79848c9e1841aaf2643e08727738

**Comment by ilovezfs** [comment]
@rajiv sorry I cannot reproduce the error. You can try build with `--debug --verbose` and then inspect the log for the failed test (FAIL: p11-kit/test-server.sh) to see if you can figure out what is wrong.

The test runs
```
bash-3.2$ cat ./p11-kit/test-server.sh
#!/bin/sh

testdir=$PWD/test-server-$$
test -d "$testdir" || mkdir "$testdir"

cleanup () {
  rm -rf "$testdir"
}
trap cleanup 0

cd "$testdir"

unset P11_KIT_SERVER_ADDRESS
unset P11_KIT_SERVER_PID

XDG_RUNTIME_DIR="$testdir"
export XDG_RUNTIME_DIR

"$abs_top_builddir"/p11-kit-server -s --provider "$abs_top_builddir"/.libs/mock-one.so pkcs11: > start.env 2> start.err
if test $? -ne 0; then
    cat start.err
    exit 1
fi

. ./start.env

test "${P11_KIT_SERVER_ADDRESS+set}" == set || exit 1
test "${P11_KIT_SERVER_PID+set}" == set || exit 1

"$abs_top_builddir"/p11-kit-server -s -k > stop.env 2> stop.err
if test $? -ne 0; then
    cat stop.err
    exit 1
fi

. ./stop.env

test "${P11_KIT_SERVER_ADDRESS-unset}" == unset || exit 1
test "${P11_KIT_SERVER_PID-unset}" == unset || exit 1
bash-3.2$ 
```
So maybe you already have a p11 kit server running?

**Comment by rajiv** [comment]
no p11-kit-server was running. i rebooted for good measure, and immediately opened terminal and ran

```
brew up
brew install --debug --verbose p11-kit
```

same failure:

```
...
PASS: test-log
PASS: test-filter
FAIL: p11-kit/test-server.sh
PASS: test-server
PASS: test-transport
...
```

dropped to a shell and in `p11-kit/test-server.sh.log`
```
p11-kit: 'strlen (address) < sizeof (sa.sun_path)' not true at create_socket
FAIL p11-kit/test-server.sh (exit status: 1)
```

i can even replicate this manually in the shell:

```
bash-3.2$ export abs_top_builddir=`pwd`
bash-3.2$ bash -x ./p11-kit/test-server.sh 
+ testdir=/Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/test-server-72884
+ test -d /Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/test-server-72884
+ mkdir /Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/test-server-72884
+ trap cleanup 0
+ cd /Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/test-server-72884
+ unset P11_KIT_SERVER_ADDRESS
+ unset P11_KIT_SERVER_PID
+ XDG_RUNTIME_DIR=/Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/test-server-72884
+ export XDG_RUNTIME_DIR
+ /Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/p11-kit-server -s --provider /Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/.libs/mock-one.so pkcs11:
+ test 1 -ne 0
+ cat start.err
p11-kit: 'strlen (address) < sizeof (sa.sun_path)' not true at create_socket
+ exit 1
+ cleanup
+ rm -rf /Volumes/black/Users/rajiv/tmp/p11-kit-20180422-38762-1mx8pvd/p11-kit-0.23.10/test-server-72884
```

perhaps this is not a homebrew issue? i will file it for upstream.

**Comment by fxcoudert** [comment]
Fixed upstream: https://github.com/p11-glue/p11-kit/pull/149
Thanks @rajiv for the detailed report and for filing it upstream too!
