### ISSUE TITLE
cqlsh don't work with python 2.7.12

### ISSUE THREAD

**Issue by LutzSteinborn** [Homebrew/homebrew-core#2671]
### Bug reports:

cqlsh from the formula cassandra don't work with python 2.7.12 due to the problem reported here:
https://github.com/datastax/python-driver/commit/1afa1f4b2f29fafa99b7f5e551b717278df5515f
with:
`brew switch python 2.7.11`
its coming back to work.

Is it possible to tell in a formula to use a special version of python 2?

**Comment by DomT4** [comment]
I believe this should be fixed by https://github.com/Homebrew/homebrew-core/pull/2697 since it contains `cassandra-driver 3.5.0` which the upstream commit says contains that fix.

**Comment by LutzSteinborn** [comment]
Thank you. Do you when 3.7 is ready? I can live with the workaround using python 2.7.11. It costs me half a day to find out whats going on.
Why have the python guys changed weak.ref() no longer accepting keyword args?

**Comment by DomT4** [comment]
Just waiting for our CI to process my PR there & ensure it all builds/tests fine on 10.9 through 10.11. Shouldn't be _too long_ hopefully. Can't speak to why Python changed anything upstream sadly, that's beyond my knowledge 😢.

**Comment by tdsmith** [comment]
It never worked. https://bugs.python.org/issue17765

**Comment by DomT4** [comment]
Thanks @tdsmith!

@LutzSteinborn Should be fixed now, hopefully. `brew update && brew upgrade cassandra`. Let me know if you run into any issues.
