### ISSUE TITLE
Chromedriver: Incorrect installation instructions

### ISSUE THREAD

**Issue by robbieaverill** [Homebrew/homebrew-core#26759]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs chromedriver
Error: No available formula with the name "chromedriver" 
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 1.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a2817cb023ca5e929fe030d423002992bdabf1b
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8685d318569c1f7a227c6ee3e94489a1c0054744
Core tap last commit: 25 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.1 build 902
Git: 2.11.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_112
macOS: 10.13.2-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.3
XQuartz: N/A
```

To help us debug your issue please explain:
## What you were trying to do (and why)

Install chromedriver, following the instructions on the website: http://brewformulas.org/Chromedriver

## What happened (include command output)

```
$ brew install chromedriver
Error: No available formula with the name "chromedriver" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```

Follow instructions and repeat:

```
$ brew tap caskroom/cask
$ brew install chromedriver
Error: No available formula with the name "chromedriver" 
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```

## What you expected to happen

Chromedriver would be installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

Follow the instructions: http://brewformulas.org/Chromedriver

**NOTE:** Reporting an issue here, as following the "Open new issue" button above the incorrect installation instructions.

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ilovezfs** [comment]
```
brew cask install chromedriver
```

**Comment by robbieaverill** [comment]
Thanks for the reply. Am I able to contribute to fixing the documentation in some way?

**Comment by ilovezfs** [comment]
The message is here https://github.com/Homebrew/brew/blob/master/Library/Homebrew/missing_formula.rb#L105 so you could add some kind of special handling for cask migrations.

**Comment by robbieaverill** [comment]
Thanks. I'm not familiar enough with the homebrew core to make suggestions here, other than adding " or `brew cask install #{new_tap_name}` - I was more talking about updating http://brewformulas.org/Chromedriver to show correct install instructions (assuming it was open sourced somewhere).

**Comment by jrochkind** [comment]
I just ran into the exact same thing on "chromedriver", and found this issue filed.. just an hour ago? Woah. 

The message on `brew install chromedriver` is def confusing. I'm not sure if brew used to work differently and the message on `brew install chromedriver` used to be more likely to lead the user to success?

**Comment by ilovezfs** [comment]
@jrochkind it was moved from Homebrew/homebrew-core to caskroom/homebrew-cask

See
https://github.com/caskroom/homebrew-cask/pull/45029
https://github.com/Homebrew/homebrew-core/pull/25566

**Comment by jrochkind** [comment]
Right, okay, I'm talking about running `brew install chromedriver`, and getting the message 

```
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```

That led me to do exactly the same thing as @robbieaverill. Run `brew tap caskroom/cask ; brew install chromedriver`, which just results in the same message again. 

I don't understand enough about what's going on to know... what's going on.  Did I in fact need to run `brew tap caskroom/cask` prior to `brew cask install chromedriver`, for it to work?  But I needed to know that after `brew tap caskroom/cask`, I needed to run `brew cask install chromedriver`?

At any rate, if I already have run `brew tap caskroom/cask`, and then errantly run `brew install chromedriver` again, just giving me the same message "It was migrated from homebrew/core to caskroom/cask;  You can access it again by running:  brew tap caskroom/cask" does not seem helpful. 

I'm not sure where this message is coming from, or what it's supposed to be telling me?

**Comment by ilovezfs** [comment]
>Did I in fact need to run brew tap caskroom/cask prior to brew cask install chromedriver

No, if you `brew cask install chromedriver` it will automatically tap `caskroom/cask` first if you haven't tapped it already. But it doesn't hurt to run `brew tap caskroom/cask` yourself first.

>But I needed to know that after brew tap caskroom/cask, I needed to run brew cask install chromedriver

Yes. All casks are installed using `brew cask install` not `brew install`.

>I'm not sure where this message is coming from, or what it's supposed to be telling me?

It's telling you that the chromedriver formula is missing from Homebrew/homebrew-core and where to find it now https://github.com/caskroom/homebrew-cask/blob/master/Casks/chromedriver.rb

**Comment by robbieaverill** [comment]
@ilovezfs how do we update the website? The incorrect installation instruction is the issue here, I'd love to change it for you if I can!

**Comment by ilovezfs** [comment]
Which website?

**Comment by robbieaverill** [comment]
http://brewformulas.org/Chromedriver (noted in the original issue)

**Comment by jrochkind** [comment]
Okay, so if I've already run `brew tap caskroom/cask`, and then, being confused about how to use brew, run `brew install chromedriver` again, I get the message again:

```
Error: No available formula with the name "chromedriver"
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
  brew tap caskroom/cask
```

This does not seem to be correct or helpful information. I already did run `brew tap caskroom/cask` -- which in fact I did not need to do. This message is giving me no useful information at all. 

Would it not be better for it to say:

```
Error: No available formula with the name "chromedriver"
It was migrated from homebrew/core to caskroom/cask.
You can access it by running:
  brew cask install chromedriver
```

Am I missing something?

**Comment by ilovezfs** [comment]
Oh OK. That is not part of the Homebrew organization so you'd need to let them know directly.

**Comment by ilovezfs** [comment]
>Am I missing something?

@jrochkind You're not missing anything. You'd need to open a PR to https://github.com/Homebrew/brew if you want to change the messaging.

**Comment by jrochkind** [comment]
Okay, will do.

**Comment by robbieaverill** [comment]
Thanks, docs issue moved to https://github.com/zedtux/brewformulas.org/issues/207

**Comment by jrochkind** [comment]
(I am not actually concerned with the web page @robbieaverill found, I didn't find it myself! Even if I had, if i had run `brew install chromedriver` and gotten a message telling me to run `brew cask install chromedriver` instead, I would have been on the right path. The message from trying to install a migrated-to-cask formula seems a bigger issue to me. I'll try opening an issue on brew... but I think they might tell me I need to open an issue on https://github.com/caskroom/homebrew-cask/ or something instead...)

**Comment by ilovezfs** [comment]
> I'll try opening an issue on brew... but I think they might tell me I need to open an issue on https://github.com/caskroom/homebrew-cask/ or something instead...)

The code for cask lives in https://github.com/Homebrew/brew. Only the casks themselves are in https://github.com/caskroom/homebrew-cask.
