### ISSUE TITLE
failure of php71-redis installation

### ISSUE THREAD

**Issue by v3u3i87** [Homebrew/homebrew-core#26777]
Now, install php71-redis or search the library from braumeister.org. There is no way to know how to install brew install php71-redis as before?

**Figure:**
![image](https://user-images.githubusercontent.com/1936834/38926648-01db16c2-4336-11e8-8ad7-11b44c76f8ec.png)

**brew config:**
HOMEBREW_VERSION: 1.6.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a2817cb023ca5e929fe030d423002992bdabf1b
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 967b4f01cabdd28e9ba0a840ade2b5dcda4bf7e0
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: N/A

**brew tap:**
caskroom/cask
homebrew/bundle
homebrew/core
homebrew/dupes
homebrew/services
homebrew/versions
josegonzalez/php
tideways/profiler

brew doctor there is no problem..

How do you solve these installation problems at the moment?

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by ErwinSteffens** [comment]
For me it is still not working. `php -v`shows:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so' - dlopen(/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so' - dlopen(/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so, 9): image not found in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so' - dlopen(/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so' - dlopen(/usr/local/Cellar/php@7.1/7.1.16_1/lib/php/20160303/redis.so, 9): image not found in Unknown on line 0
PHP 7.1.16 (cli) (built: Apr 12 2018 03:28:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

Pecl installs the `redis.so` file in `/usr/local/lib/php/pecl/20160303/` which (I think) should have been `/usr/local/lib/php/20160303/`.

This is my `/usr/local/lib/php` folder:

```
➜  php ls -la /usr/local/lib/php
total 0
drwxr-xr-x    5 erwin  admin   160 Apr 19 11:36 .
drwxrwxr-x  154 erwin  admin  4928 Apr 19 11:36 ..
lrwxr-xr-x    1 erwin  admin    46 Apr 19 11:36 20160303 -> ../../Cellar/php@7.1/7.1.16_1/lib/php/20160303
lrwxr-xr-x    1 erwin  admin    43 Apr 19 11:36 build -> ../../Cellar/php@7.1/7.1.16_1/lib/php/build
drwxr-xr-x    4 erwin  admin   128 Apr 17 15:16 pecl
```

**Comment by SMillerDev** [comment]
That just means it's trying to load old config files.

**Comment by ErwinSteffens** [comment]
Who is? PHP or pecl?

**Comment by SMillerDev** [comment]
Php is. If you look at the conf.d directory of your php install, there's old configuration there. And pecl should be installing into the pecl directory. 

The easiest solution might be (if there's not too much custom config) to remove all of php 7.1 and all configuration and then reinstalling it.

**Comment by ErwinSteffens** [comment]
Yes, this fixed it, thanks!
