### ISSUE TITLE
gnuplot compilation fails with QT

### ISSUE THREAD

**Issue by pcaridade** [Homebrew/homebrew-core#26867]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install gnuplot with QT 

- What happened (include command output)
Undefined symbols for architecture x86_64:
  "QString::toLower_helper(QString const&)", referenced from:
      _qt_enhanced_open in qt_term.o
ld: symbol(s) not found for architecture x86_64

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install gnuplot --with-aquaterm --with-x11 --with-wxmac --with-qt

brew gist-logs gnuplot
https://gist.github.com/8481f5226015f3f1f3608a6641bc5821

(hope that everything is according to the rules... my first attempt!)

**Comment by rakkesh** [comment]
@pcaridade this seems to me like a local configuration issue, as I am able to build `gnuplot` successfully with the specified options - https://gist.github.com/055f656d98c94d3e8a90cafb8ddc0c2e.

I would suggest you to `brew reinstall qt`, and try installing `gnuplot` again.

**Comment by fxcoudert** [comment]
It looks like a local issue indeed. Also you `brew doctor` warnings indicate you have a very old qt@4 which may be causing trouble. Closing for now.

Testing job on our machine, using your options: `gnuplot --with-aquaterm --with-x11 --with-wxmac --with-qt` https://jenkins.brew.sh/job/Homebrew%20Testing/842/
