### ISSUE TITLE
mysql should not be a prerequisite for percona-toolkit

### ISSUE THREAD

**Issue by utdrmac** [Homebrew/homebrew-core#26896]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- N/A ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- N/A if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install percona-toolkit` - Need the toolkit to run tools against remote MySQL server
- What happened (include command output)
Brew attempted to download and install mysql server on my local machine
- What you expected to happen
Brew should not have downloaded and installed mysql to my local machine. This is not a requirement for running percona toolkit.
- Step-by-step reproduction instructions (by running `brew install` commands)
Single step listed above.

# Formula additions or changes
Please remove mysql as a dependency for percona-toolkit. It is not a dependency. You do not have to have mysql installed in order to use the percona-toolkit tools on remote mysql hosts.

**Comment by commitay** [comment]
> Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.
