### ISSUE TITLE
macvim fails to build

### ISSUE THREAD

**Issue by jrp2014** [Homebrew/homebrew-core#26915]
- [X ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
running brew upgrade 

HOMEBREW_VERSION: 1.6.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5a2817cb023ca5e929fe030d423002992bdabf1b
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ce9d5c849e580a04542e4dca0c43b05e5fcd4dd
Core tap last commit: 11 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: 12-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: N/A

- [X  ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? 

- [X  ]ran `brew update` and can still reproduce the problem?

- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
(all good.)

- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/a00dbb366aa26eb86c12c41ea41b402f

- [n/a ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
J
ust update my version of macvim

- What happened (include command output)

I have also tried removing the old version and reinstalling.  The result is substantially the same:

brew install macvim --with-lua 
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-146.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapshot-146
######################################################################## 100.0%
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tcli
==> make
Last 15 lines from /Users/jrp/Library/Logs/Homebrew/macvim/02.make:
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --strip /tmp/macvim-20180421-38271-1n5bbp0/macvim-snapshot-146/src/MacVim/build/Release/MacVim.app/Contents/Resources/English.lproj/FindAndReplace.nib --output-format human-readable-text /tmp/macvim-20180421-38271-1n5bbp0/macvim-snapshot-146/src/MacVim/English.lproj/FindAndReplace.nib

CopyPlistFile build/Release/MacVim.app/Contents/Resources/KeyBinding.plist KeyBinding.plist
    cd /tmp/macvim-20180421-38271-1n5bbp0/macvim-snapshot-146/src/MacVim
    builtin-copyPlist --outdir /tmp/macvim-20180421-38271-1n5bbp0/macvim-snapshot-146/src/MacVim/build/Release/MacVim.app/Contents/Resources -- KeyBinding.plist

** BUILD FAILED **

The following build commands failed:
	StripNIB English.lproj/MainMenu.nib
	StripNIB English.lproj/Preferences.nib
(2 failures)
make[1]: *** [macvim] Error 65
make: *** [first] Error 2

- What you expected to happen
macvim should just build and install

- Step-by-step reproduction instructions (by running `brew install` commands)

See above.  

# Formula additions or changes

n/a

**Comment by ilovezfs** [comment]
You probably need to launch Xcode and agree to the Terms, etc.

**Comment by jrp2014** [comment]
Great call. Thanks. That was it.  XCode needed to install some updated components.  Now all is good.
