### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by global2alex** [Homebrew/homebrew-core#26919]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install Travis, development and to install on multiple machines. 
- What happened (include command output)

travis login --github-token xxx
```
no implicit conversion of nil into String
for a full error report, run travis report
```

As you can see, brew installs travis with an old version of ruby. 

travis report 
```
System
Ruby:                     Ruby 2.0.0-p481
Operating System:         Mac OS X 10.9.5
RubyGems:                 RubyGems 2.0.14

CLI
Version:                  1.8.8
Plugins:                  none

Auto-Completion:          yes
Last Version Check:       2018-04-21 10:48:08 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis login`:
    TypeError: no implicit conversion of nil into String
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `initialize'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `new'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from /usr/local/Cellar/travis/1.8.8_2/libexec/gems/travis-1.8.8/lib/travis/tools/github.rb:262:in `gh_error'
        from /usr/local/Cellar/travis/1.8.8_2/libexec/gems/travis-1.8.8/lib/travis/tools/github.rb:254:in `rescue in acceptable?'
... 
```

You can install travis with this
```
gem install travis -v 1.8.8 --no-rdoc --no-ri
```

But this is not really a fix, it's an ugly work around for me. I love brew, I want to use it! Can't really use a brewfile to install on a new machine either. 

- What you expected to happen
Install travis, possibly use my homebrew version of ruby? 
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install travis
travis login --github-token xxx

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by commitay** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/26925

`brew update && brew upgrade travis`
