### ISSUE TITLE
HDF5 formula no longer supports mpich

### ISSUE THREAD

**Issue by chissg** [Homebrew/homebrew-core#26974]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Remaining issues (see below) are irrelevant to the problem at hand.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  
```
   Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)  
```
   brew update && brew outdated && brew upgrade && brew cleanup
```
- What happened (include command output)  
```
   ==> Upgrading hdf5 --with-mpi
   Error: /usr/local/opt/open-mpi not present or broken
   Please reinstall open-mpi. Sorry :(
```
- What you expected to happen
Successful upgrade.
- Step-by-step reproduction instructions (by running `brew install` commands)
Either (to duplicate what actually happened):
- Check out homebrew core prior to `dc5b5d699b`
- `brew install mpich`
- `brew install hdf5 --with-mpi`
- Update to HEAD.
- `brew upgrade`
Or (to produce the same error with less effort):
- `brew install mpich`
- `brew install hdf5 --with-mpi`

I understand that this is probably intentional. However: there are multiple MPI implementations for a reason, and people choose to use implementations other than `open-mpi` for perfectly valid reasons. For us, for example, `open-mpi` exhibited problems under certain conditions, whereas `mpich` did not.

Please, is there any documentation or discussion explaining why the `:mpi` dependency is being phased out? This has removed functionality upon which we depend, and has rendered Homebrew less useful to us, which is why I report this as a bug.

**Comment by chissg** [comment]
- Output of `brew config`:
```
HOMEBREW_VERSION: 1.6.1-41-g648a7c7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 648a7c7b1ed540e0629d3ce0a8b68a4a3dc9faed
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 22511f2e939b274a4e0818d82885522279adf654
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: edit
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.4, 1.8.0_162
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: 2.7.11 => /opt/X11
```
- Output of `brew doctor`.
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

**Comment by fxcoudert** [comment]
In January, we phased out generic support for MPI. MPI support for core formulas now requires OpenMPI as reference implementation: https://github.com/Homebrew/homebrew-core/pull/22703 https://github.com/Homebrew/homebrew-core/pull/22820
