### ISSUE TITLE
Pianobar

### ISSUE THREAD

**Issue by stevenbedrick** [Homebrew/homebrew-core#26982]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

     https://gist.github.com/stevenbedrick/7e985c97e70a0e7a23c0543f0fed147b

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I think that the recent version bump to `ffmpeg` broke the existing bottled version of `pianobar`. The current `pianobar` is linked against `/usr/local/opt/ffmpeg/lib/libavcodec.57.dylib`, but in the latest `ffmpeg`, that file has been replaced with `libavcodec.58.dylib` (note version number change). Forcing a source install doesn't work- some header files relating to `libavfilter` are missing (see gist above).

- What happened (include command output)

When running a freshly-installed bottled version of `pianobar`:

```
[~] % pianobar
dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
  Referenced from: /usr/local/bin/pianobar
  Reason: image not found
Abort trap: 6
[~] %
```

- What you expected to happen

I was expecting the executable to run.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
[~] % brew install pianobar
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/pianobar-2017.08.30.sierra.bottle.tar.gz
Already downloaded: /Users/bedricks/Library/Caches/Homebrew/pianobar-2017.08.30.sierra.bottle.tar.gz
==> Pouring pianobar-2017.08.30.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pianobar/2017.08.30: 19 files, 128.6KB
[~] % pianobar
dyld: Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
  Referenced from: /usr/local/bin/pianobar
  Reason: image not found
Abort trap: 6
[~] %
```

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by commitay** [comment]
Thanks for reporting this @stevenbedrick!

`brew update && brew upgrade pianobar`

**Comment by stevenbedrick** [comment]
Thanks so much! 

-SB
