### ISSUE TITLE
tor configuration file specifies non-existent directories for logging

### ISSUE THREAD

**Issue by dlo** [Homebrew/homebrew-core#2699]
The directory for the log file in the torrc configuration does not exist, so logging fails silently if enabled.

In /usr/local/etc/tor/torrc, note the line `## Send all messages of level 'notice' or higher to /usr/local/Cellar/tor/0.2.5.11/var/log/tor/notices.log`. Homebrew does not create the `var` directory under `/usr/local/Cellar/tor/0.2.5.11/`, so the following command (see below) fails silently.

    Log notice file /usr/local/Cellar/tor/0.2.5.11/var/log/tor/notices.log

Fix: create the `/usr/local/Cellar/tor/0.2.5.11/var/log/tor/` directory after tor is installed.

**Comment by DomT4** [comment]
This was actually fixed [here](https://github.com/Homebrew/homebrew-core/commit/cced77d374c39bb760ab36fd1e012ae1dc9699f6), it just hadn't made it into the `stable` bottle until https://github.com/Homebrew/homebrew-core/commit/2cc2611c5bdbec81eceaf5ec8284951232dca02f.

The new configuration file specifies:
```
## Send all messages of level 'notice' or higher to @@HOMEBREW_PREFIX@@/var/log/tor/notices.log
#Log notice file @@HOMEBREW_PREFIX@@/var/log/tor/notices.log
## Send every possible message to @@HOMEBREW_PREFIX@@/var/log/tor/debug.log
#Log debug file @@HOMEBREW_PREFIX@@/var/log/tor/debug.log
```

That `@@HOMEBREW_PREFIX@@` blob is replaced out during installation with whatever your actual Homebrew prefix is, normally `/usr/local`. If you `brew reinstall tor` you'll get that tweak now, but otherwise it'll be resolved on next stable update.

**Comment by dlo** [comment]
@DomT4 I just did a `brew reinstall tor` and no change...anything else I can try?

**Comment by DomT4** [comment]
IIRC the default `torrc` is installed as `torrc.sample`. Perhaps check that?

**Comment by dlo** [comment]
It actually looks like those sample torrc files in /usr/local/etc/tor don't get deleted after a `brew uninstall tor` or a `brew cleanup`. `brew install tor` didn't wipe them either. Seems like a bug?

**Comment by DomT4** [comment]
That's deliberate.

`/usr/local/etc` is "immune" to `brew uninstall` in the majority of cases, the idea being that permanent configuration files are placed there & people are prone to become rightfully grumpy with us if we persistently smash their configurations.

`brew {re}install tor` will replace `torrc.sample` if it hasn't been touched. If `torrc.sample` has been edited `brew` will install the pristine configuration sample fine as `torrc.sample.default`.

**Comment by dlo** [comment]
Yep, `brew reinstall tor` didn't do anything to them either (that was the first command I ran).

**Comment by DomT4** [comment]
I presume your Homebrew is up-to-date?

**Comment by dlo** [comment]
I think? :)

```
$ brew --version
Homebrew 0.9.9 (git revision 0478c; last commit 2016-07-03)
Homebrew/homebrew-core (git revision aedb; last commit 2016-07-03)
```

**Comment by DomT4** [comment]
Looks alright. What's the output of `ls -l /usr/local/etc/tor`?

**Comment by dlo** [comment]
Unfortunately, I manually deleted the previous (non-working) folder after I couldn't get the previous commands to take care of the issue, but here's the current one:

```
$ ls -l /usr/local/etc/tor
total 24
-rw-r--r--  1 dan  admin  9623 Jul  3 15:18 torrc.sample
```

**Comment by DomT4** [comment]
Heh, that's a shame. No worries. What is the output of `cat /usr/local/etc/tor/torrc.sample | grep "notice"`?

**Comment by dlo** [comment]
Looks good to me. :)

```
$ cat /usr/local/etc/tor/torrc.sample | grep "notice"
## Logs go to stdout at level "notice" unless redirected by something
## We advise using "notice" in most cases, since anything more verbose
## Send all messages of level 'notice' or higher to /usr/local/var/log/tor/notices.log
#Log notice file /usr/local/var/log/tor/notices.log
#Log notice syslog
## contacting them. See contrib/tor-exit-notice.html in Tor's source
#DirPortFrontPage /usr/local/etc/tor/tor-exit-notice.html
```

**Comment by DomT4** [comment]
👍. Perhaps worth noting with `tor` is that upstream expect people to configure it a bit out of the box, which is why every line of the sample is commented out by default. We respect upstream's guidance on that choice & don't fiddle with it consequently.

Most formulae from Homebrew will work out of the box, but due to the nature of what `tor` does it can require a little moulding to your own use case.

**Comment by dlo** [comment]
Makes sense--next time anything like this happens in /etc/ I'll try reinstall again to make sure I'm not missing anything. Pretty sure I did it first this time but I bet if you don't hear about this bug from anyone else, it's probably my mistake. Thanks for your help!

**Comment by DomT4** [comment]
No worries at all, happy to help.
