### ISSUE TITLE
python@3.6.5 failed to build on 10.13.4

### ISSUE THREAD

**Issue by gouez** [Homebrew/homebrew-core#27026]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

- What happened (include command output)
==> make html
Last 15 lines from /Volumes/hdd/Library/Logs/Homebrew/python/05.make:
reading sources... [ 41%] library/email.examples
reading sources... [ 41%] library/email.generator
reading sources... [ 41%] library/email.header
reading sources... [ 42%] library/email.headerregistry
reading sources... [ 42%] library/email.iterators
reading sources... [ 42%] library/email.message

Exception occurred:
  File "/Volumes/hdd/bin/homebrew/Cellar/sphinx-doc/1.7.3/libexec/lib/python2.7/site-packages/sphinx/domains/python.py", line 568, in run
    (modname, self.env.doc2path(modules[modname])),
AttributeError: 'DirectiveAdapter' object has no attribute 'env'
The full traceback has been saved in /tmp/sphinx-err-d5CRY8.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [build] Error 2

- What you expected to happen

- Step-by-step reproduction instructions (by running `brew install` commands)
 brew install python

Here's the output of brew-logs python:
https://gist.github.com/873579e846cb972fcf2fccdd5c90fabd

**Comment by anthrotype** [comment]
it seems an issue in sphinx-doc 1.7.3

https://github.com/sphinx-doc/sphinx/issues/4897

by temporarily reverting to sphinx-doc 1.7.2, I was able to build the python 3.6.5 formula.

**Comment by fxcoudert** [comment]
> Here's the output of brew-logs python:
https://gist.github.com/873579e846cb972fcf2fccdd5c90fabd

No it's not :(

**Comment by mcmccaleb** [comment]
Same issue here. Reverting to sphinx-doc 1.7.2 by reverting the first 11 lines of these commits temporarily fixed the issue:
https://github.com/Homebrew/homebrew-core/commit/cd6472cc7e8d1afd76b814290a97404a1a0cd9c8
https://github.com/Homebrew/homebrew-core/commit/5f024b3d0a84951721289e2e35a907bf1c1b9f9a

**Comment by ch-brianzimmer** [comment]
@anthrotype How did you revert back to 1.7.2? I can't find any clean way to do this.

**Comment by ZxMYS** [comment]
Seeing this too

**Comment by mcmccaleb** [comment]
@ch-brianzimmer see my comment above. Edit the file `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb` to point at Sphinx-1.7.2 and `brew reinstall sphinx-doc` then `brew reinstall python3`

**Comment by ilovezfs** [comment]
This is now fixed thanks to @commitay if you `brew upgrade sphinx-doc`
