### ISSUE TITLE
 Error executing action `run` on resource 'execute[tapping homebrew/versions]'

### ISSUE THREAD

**Issue by tashvinyamthi** [Homebrew/homebrew-core#27078]
Hi All,

 I am trying to setup a development environment for my project and I am facing the homebrew/versions error. Teh details of the error as follows: 

    This error is occuring after we upgraded to High Sierra from Sierra. 
   I also ran brew update and and resolved all brew doctor warnings. Still i face the below error:

  Any idea how to resolve this?

* execute[tapping caskroom/versions] action run[2018-04-25T08:31:58-04:00] INFO: Processing execute[tapping caskroom/versions] action run (/Users/vishwajeets/workspace/workstation_setup/cookbooks/homebrew/providers/tap.rb line 40)
[2018-04-25T08:31:58-04:00] INFO: Processing execute[Guard resource] action run (dynamically defined)
caskroom/versions
[2018-04-25T08:32:01-04:00] INFO: execute[Guard resource] ran successfully
 (skipped due to not_if)
     (up to date)
  * homebrew_tap[homebrew/versions] action tap[2018-04-25T08:32:01-04:00] INFO: Processing homebrew_tap[homebrew/versions] action tap (homebrew::install_taps line 23)

    * execute[tapping homebrew/versions] action run[2018-04-25T08:32:01-04:00] INFO: Processing execute[tapping homebrew/versions] action run (/Users/vishwajeets/workspace/workstation_setup/cookbooks/homebrew/providers/tap.rb line 40)
[2018-04-25T08:32:01-04:00] INFO: Processing execute[Guard resource] action run (dynamically defined)

      [execute] Error: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
      
      ================================================================================
      Error executing action `run` on resource 'execute[tapping homebrew/versions]'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of /usr/local/bin/brew tap homebrew/versions ----
      STDOUT: 
      STDERR: Error: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
      ---- End output of /usr/local/bin/brew tap homebrew/versions ----
      Ran /usr/local/bin/brew tap homebrew/versions returned 1
      
      Cookbook Trace:
      ---------------
      /Users/vishwajeets/workspace/workstation_setup/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      /Users/vishwajeets/workspace/workstation_setup/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
      
      Resource Declaration:
      ---------------------
      # In /Users/vishwajeets/workspace/workstation_setup/cookbooks/homebrew/providers/tap.rb
      
       40:     execute "tapping #{new_resource.name}" do
       41:       command "/usr/local/bin/brew tap #{new_resource.name}"
       42:       environment lazy { { 'HOME' => ::Dir.home(homebrew_owner), 'USER' => homebrew_owner } }
       43:       not_if "/usr/local/bin/brew tap | grep #{new_resource.name}"
       44:       user homebrew_owner
       45:     end
       46:   end
      
      Compiled Resource:
      ------------------
      # Declared in /Users/vishwajeets/workspace/workstation_setup/cookbooks/homebrew/providers/tap.rb:40:in `block in class_from_file'
      
      execute("tapping homebrew/versions") do
        action [:run]
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "/usr/local/bin/brew tap homebrew/versions"
        backup 5
        environment #<Chef::DelayedEvaluator:0x007f8949479120@/Users/vishwajeets/workspace/workstation_setup/cookbooks/homebrew/providers/tap.rb:42>
        returns 0
        user "vishwajeets"
        declared_type :execute
        cookbook_name :homebrew
        homebrew_owner "vishwajeets"
        not_if "/usr/local/bin/brew tap | grep homebrew/versions"
      end
      
[2018-04-25T08:32:06-04:00] INFO: Running queued delayed notifications before re-raising exception

**Comment by commitay** [comment]
> homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.

**Comment by SMillerDev** [comment]
You can at least try and remove homebrew/version by running `brew untap homebrew/versions`

**Comment by tashvinyamthi** [comment]
If I run the command brew untap homebrew/versions, I get the follwing error message :
Error: No available tap homebrew/versions.

**Comment by commitay** [comment]
The script you are running needs to be updated so it doesn't tap homebrew/versions.

**Comment by SMillerDev** [comment]
It looks like it's an issue with caskroom/versions though, which is not part of homebrew.
