### ISSUE TITLE
wireshark --with-qt fails to build version 2.6.0

### ISSUE THREAD

**Issue by hsiktas** [Homebrew/homebrew-core#27079]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I want to upgrade wireshark --with-qt to version 2.6.0
- What happened (include command output)

```
==> Upgrading 1 outdated package, with result:
wireshark 2.4.6 -> 2.6.0
==> Upgrading wireshark --with-qt
==> Downloading https://www.wireshark.org/download/src/all-versions/wireshark-2.6.0.tar.xz
Already downloaded: /Users/hakan/Library/Caches/Homebrew/wireshark-2.6.0.tar.xz
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/wireshark/2.6.0 -DCMAKE_BUILD_T
Last 15 lines from /Users/hakan/Library/Logs/Homebrew/wireshark/01.cmake:
-- Configuring done
CMake Error at CMakeLists.txt:2232 (add_executable):
  Cannot find source file:

    ui/macosx/cocoa_bridge.mm

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:2232 (add_executable):
  No SOURCES given to target: wireshark


-- Build files have been written to: /tmp/wireshark-20180425-33492-na8g50/wireshark-2.6.0

READ THIS: https://docs.brew.sh/Troubleshooting 
```
Here is my gist-log:
https://gist.github.com/hsiktas/e357e992f7e3bb49ab9dcebc9a993971
- What you expected to happen
I expected a successful build of wireshark 2.6.0 the Qt-based user interface
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install wireshark --with-qt`

# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.

**Comment by robertleeblairjr** [comment]
I can provide my gist-log, if necessary, but this is identical to the error that I'm receiving today whenever upgrading the wireshark package. Even removing and attempting an install still produces the same error on my MBP running macOS 10.13.4 with the Security Update 2018-001 which was released on April 24, 2018.

**Comment by xeron** [comment]
Same with gtk3:
```
==> Installing wireshark --with-gtk+3
==> Downloading https://www.wireshark.org/download/src/all-versions/wireshark-2.6.0.tar.xz
######################################################################## 100.0%
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/opt/brew/Cellar/wireshark/2.6.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DENABLE_CARES=ON -DENABLE_GNUTLS=ON -DENABLE_
Last 15 lines from /Users/ilarionov/Library/Logs/Homebrew/wireshark/01.cmake:
-- Configuring done
CMake Error at CMakeLists.txt:2397 (add_executable):
  Cannot find source file:

    ui/macosx/cocoa_bridge.mm

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:2397 (add_executable):
  No SOURCES given to target: wireshark-gtk
```

**Comment by DomT4** [comment]
Oh, I've had a fix for this pretty much since it was merged, sorry. It's a simple packaging screw up upstream. I'll push a PR soon; got distracted trying to fix the formula's unrelated `lua` issues.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/27110

**Comment by jumarko** [comment]
@DomT4 do you have any updated on this?

**Comment by DomT4** [comment]
Still waiting on upstream, I'm afraid. I can & will look at the `lua` situation but that's not the primary blocker at this point.

**Comment by ilovezfs** [comment]
This is now fixed if you `brew upgrade`
