### ISSUE TITLE
Python3: Unversioned symlinks are installed to directory not in PATH

### ISSUE THREAD

**Issue by iBobik** [Homebrew/homebrew-core#27140]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/253c222db37140c7e8c7a5bd03e386d7
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install Python 3
- What happened (include command output)
Installed but links python → python3, pip → pip3 etc. does not work because they were created in folder what is not in PATH
- What you expected to happen
Links shoudl be created in some common directory what is in PATH.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install python3
==> Installing dependencies for python: gdbm, openssl, readline, sqlite, xz
…
$ pip
-bash: pip: command not found
$ pip3

Usage:   
  pip3 <command> [options]
…
$ ls -l /usr/local/opt/python/libexec/bin
total 0
lrwxr-xr-x  1 Bobik  admin  26 26 dub 14:15 easy_install -> ../../bin/easy_install-3.6
lrwxr-xr-x  1 Bobik  admin  58 28 bře 12:24 idle -> ../../Frameworks/Python.framework/Versions/3.6/bin/idle3.6
lrwxr-xr-x  1 Bobik  admin  14 26 dub 14:15 pip -> ../../bin/pip3
lrwxr-xr-x  1 Bobik  admin  59 28 bře 12:24 pydoc -> ../../Frameworks/Python.framework/Versions/3.6/bin/pydoc3.6
lrwxr-xr-x  1 Bobik  admin  60 28 bře 12:24 python -> ../../Frameworks/Python.framework/Versions/3.6/bin/python3.6
lrwxr-xr-x  1 Bobik  admin  68 28 bře 12:24 python-config -> ../../Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
lrwxr-xr-x  1 Bobik  admin  16 26 dub 14:15 wheel -> ../../bin/wheel3
```

**Comment by ilovezfs** [comment]
Please see https://github.com/Homebrew/homebrew-core/pull/25060

Upstream still wants `python` to mean Python 2.

**Comment by iBobik** [comment]
@ilovezfs Not a bug but an undocumented feature? ;-)

**Comment by commitay** [comment]
https://docs.brew.sh/Homebrew-and-Python
