### ISSUE TITLE
cloc depends on Regexp

### ISSUE THREAD

**Issue by balrok** [Homebrew/homebrew-core#2714]
Hello since today my cloc command is broken:
```
$ cloc
Can't locate Regexp/Common.pm in @INC (you may need to install the Regexp::Common module) (@INC contains: /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0 /usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0 /usr/local/lib/perl5/site_perl/5.24.0 .) at /usr/local/bin/cloc line 57.
BEGIN failed--compilation aborted at /usr/local/bin/cloc line 57.
```

I guess the solution would be to add:
```depends_on "Regexp::Common" => :perl```
to `cloc.rb`

**Comment by DomT4** [comment]
Should be fixed after `brew update && brew reinstall cloc`.

The issue is upstream's usage of `#!/usr/bin/env perl`, which is a perfectly legit use case, but does present some challenges in being able to predict the environment in all cases.
