### ISSUE TITLE
MariaDB 10.1.15 has vanished

### ISSUE THREAD

**Issue by okket** [Homebrew/homebrew-core#2715]
It's still in the formula, but e.g. the announcement page on mariadb.org is gone [1] and the mirrors do not have sources any more:

```
→ brew install mariadb
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Downloading http://ftp.osuosl.org/pub/mariadb/mariadb-10.1.15/source/mariadb-10.1.15.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mariadb"
Download failed: http://ftp.osuosl.org/pub/mariadb/mariadb-10.1.15/source/mariadb-10.1.15.tar.gz
```

[1] https://mariadb.com/kb/en/mariadb-10115-release-notes/

**Comment by DomT4** [comment]
Thanks for letting us know about this. Upstream's explanation on why this happened is more or less nil, which is a bit frustrating. I've reverted the relevant commits, it should install okay now.
