### ISSUE TITLE
boost-python3 library links are not standard names?

### ISSUE THREAD

**Issue by leolchat** [Homebrew/homebrew-core#27221]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

When installing boost-python3, the installed links are not found by CMake FindBoost since it is looking for a library named `libboost_python3`. On Ubuntu and such, the library name is something like `libboost_python3-py36.so.1.65.1` so I would expect the dylib to be something like `libboost_python3-py36.1.67.0.dylib` or something like that.

But the bottled version has those links:
```
brew link boost-python3 -v
Linking /usr/local/Cellar/boost-python3/1.67.0...
ln -s ../../Cellar/boost-python3/1.67.0/share/doc/boost-python3 boost-python3
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_numpy36-mt.a libboost_numpy36-mt.a
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_numpy36-mt.dylib libboost_numpy36-mt.dylib
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_numpy36.a libboost_numpy36.a
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_numpy36.dylib libboost_numpy36.dylib
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_python36-mt.a libboost_python36-mt.a
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_python36-mt.dylib libboost_python36-mt.dylib
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_python36.a libboost_python36.a
ln -s ../Cellar/boost-python3/1.67.0/lib/libboost_python36.dylib libboost_python36.dylib
9 symlinks created
```

PS in the PR for boost-python3 (#23322) the discussions are showing some of the generated links and they are plain without versioning `libboost_python3.dylib`

**Comment by ilovezfs** [comment]
The names are the default set by Boost 1.67. CMake has already adapted to the change. If a given project is having trouble finding them, that is a problem with that project's CMake files.

**Comment by leolchat** [comment]
Well you are right, CMake 11 seems to have fixed that, but brew doesn't ship that version of cmake (3.10 expect the "old" way https://cmake.org/cmake/help/v3.10/module/FindBoost.html ).

So there is an inconsistency in brew, FindBoost is not part of the project CMake files but part of the brew cmake package :/

**Comment by leolchat** [comment]
I guess I can hack something for all the projects I try to compile (ROS melodic), but this will break a lot of brew formulas too (building from source using cmake) no?

**Comment by commitay** [comment]
> CMake 3.11 seems to have fixed that, but brew doesn't ship that version of cmake 

```
$ brew info cmake
cmake: stable 3.11.1 (bottled), HEAD
Cross-platform make
https://www.cmake.org/
/usr/local/Cellar/cmake/3.11.1 (2,363 files, 32.7MB) *
  Poured from bottle on 2018-04-18 at 06:35:25
```

**Comment by leolchat** [comment]
Seems like cmake was pinned on my machine... Sorry for the noise.

**Comment by ilovezfs** [comment]
@leolchat no worries. I'm glad you tracked down the issue.
