### ISSUE TITLE
[enhancement] - Homebrew/homebre-core - adding jacosx and soundflower+soundflowerbed to homebrew casks

### ISSUE THREAD

**Issue by tmm2018** [Homebrew/homebrew-core#27229]
#### [enhancement] - Homebrew/homebre-core - adding jacosx and soundflower+soundflowerbed to homebrew casks

**IMHO, it would be nice to:**
- *add jackosx to homebrew casks;*
- *add soundflower to homebrew casks;*
- *add soundflowerbed to homebrew casks;*

---

**motivations:**
- *procedure for implementation is quite simple (free & opensource packages with binaries on github and sourceforge)*
- *it would benefit the audio community*
- *it would make it easier to set up stuff*

**Comment by ilovezfs** [comment]
From the issue template
```
# Formula additions or changes
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
We will close issues requesting formulae changes.
```
