### ISSUE TITLE
[enhancement] - homebre/homebrew-core - adding scripts for installing a set of software packages for speciic purposes

### ISSUE THREAD

**Issue by tmm2018** [Homebrew/homebrew-core#27230]
#### [enhancement] - homebre/homebrew-core - adding scripts for installing a set of software packages for speciic purposes

**IMHO, it would be nice to:**
- *add scripts with full software packages meant at specific purposes (i.e.: criptography/pentesting, machine learning, c++ development, computer graphics, sound, image, multimedia, etc.)*

**Comment by ilovezfs** [comment]
Please see https://github.com/Homebrew/brew/issues/2300
