### ISSUE TITLE
PHP Extensions that are not compiled in the primary package

### ISSUE THREAD

**Issue by asentner** [Homebrew/homebrew-core#27273]
This is not a bug report but more of a discussion for the extensions that are not compiled into the primary PHP packages since being moved to the homebrew/core.

There are some very common extensions such as but not limited to the MongoDB driver, imagick, redis, xdebug. Are there plans to add packages for these extensions to be pre-configured to work with the brewed packages and library locations?

I understand one could build the extension from source using the PECL or compiling from the ext path but may be a bit cumbersome since the libraries aren't in the common paths the compiler searches for. Could also make upgrading packages quite a bit more difficult since you would want your extension to be built with the current version of PHP. 

The benefit of the previous PHP packages were the ease of compiling, dependency handling, and the creation of the .ini configuration files in the conf.d.

If you are not planning on adding additional packages, would you be opposed to adding the extensions listed at the beginning of this message to the core package? I would be willing to contribute this update to the repository.

I would be willing to help out with managing the additional packages if this were to be something you'd consider but time being the biggest issue since we rely on these pretty heavily.

I used to manage new PHP RPM packages for RHEL/CentOS for this same reason and did so for many years before others created their own repositories that were pretty well maintained.

Thoughts?

**Comment by ilovezfs** [comment]
@asentner thanks for offering to help out. The current plan is to have people install things using pecl if they can be installed using pecl. You're welcome to maintain [your own tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap), though, as in https://github.com/kabel/homebrew-php-ext

CC @kabel @javian @SMillerDev for any further suggestions.
