### ISSUE TITLE
python2 breaking lldb on osx

### ISSUE THREAD

**Issue by chsitter** [Homebrew/homebrew-core#2730]
### Bug reports:

I've installed vim `brew install vim --replace-system-vi` on my mac and it has a dependency on python2. This dependency seems to be pulling down a 32bit readline.so and possibly other libraries that conflict with system libraries and break other tools. In my case it's lldb

```bash
chsitter: build$ lldb ./container.test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
(lldb) target create "./container.test"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
.... (this repeats for some time)
```

I'm not sure whether this is the right place to raise this, but it seemed fitting.

**Comment by rakkesh** [comment]
Doesn't seem like an issue with Homebrew.

Overriding system `vi`, Homebrew only symlinks `vim` to `/usr/local/bin/vi` 
[`bin.install_symlink "vim" => "vi" if build.with? "override-system-vi"`](https://github.com/Homebrew/homebrew-core/blob/6f4acbc14c8a276047daea3371902f4e3c11dac2/Formula/vim.rb#L109)

`readline` formula is key-only and should not interfere with system libs.

**Comment by MikeMcQuaid** [comment]
It's an issue with the system LLDB and any `python` in the PATH, I suspect. Also agree this isn't a Homebrew issue (or at least: it's not something we can fix).

**Comment by MikeMcQuaid** [comment]
> No package that is installed via a package manager should break a fundamental utility like lldb.

On the flip side: nothing installed into `/usr/local` should break a system utility.

**Comment by mistydemeo** [comment]
The problem is caused by the `six` module not being available. Like Mike said, it looks like the system lldb uses whichever `python` is first on the PATH. The Python script lldb uses requires the `six` module, which is preinstalled with the OS python but not with Homebrew's python. If you `pip install six` then lldb will work fine.

**Comment by tdsmith** [comment]
^ Actually there's a good chance it'll crash because _lldb.so is linked against the system Python!

It's odd to me that we haven't seen this before.

**Comment by tdsmith** [comment]
I can reproduce with Homebrew's python linked by running `pip uninstall six` and launching lldb, though, so I guess it doesn't crash after all.

I propose that this is Apple's bug.

**Comment by chsitter** [comment]
Sounds to me like installing the six module with the python package by default (to avoid screwing up lldb) and raising an issue with Apple would be the right thing to do?

**Comment by tdsmith** [comment]
I'd feel worse about it if anyone had ever complained before, tbh. `six` is fine and bundling it with python would be fine but I don't really want to start curating a shadow stdlib. I propose to close this without action and ask you to file an issue with Apple asking them to modify lldb to use system Python.

**Comment by chsitter** [comment]
Sounds sensible. Guessing nobody uses languages that require lldb to debug any more :)

There are easy ways to fix this, hence it's not really a big issue and I've got it working now, so happy to close it. 

Thanks for looking into it
