### ISSUE TITLE
undefined method `revision' AGAIN?

### ISSUE THREAD

**Issue by popoko2** [Homebrew/homebrew-core#27321]
Hi,

I use  the latest version of the Homebrew.

$brew --version
Homebrew 1.6.2
Homebrew/homebrew-core (git revision c7482; last commit 2018-05-01)

I encountered following error messages.
I also got the error on 'brew cleanup'.

I checked the #27245.
It seems not my case ...

What's wrong?
How to fix it?
Thank you in advance.

$brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  libmpc@0.8
  isl@0.11
  mpfr@2
  gmp@4
  cloog@0.15
  ppl@0.11
  isl@0.14
Error: undefined method `revision' for #<BottleSpecification:0x007fd3ef45af90>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/src256/homebrew-emacs-jp/emacs-jp.rb:19:in `block in <class:EmacsJp>'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:101:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:101:in `bottle'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2086:in `bottle'
/usr/local/Homebrew/Library/Taps/src256/homebrew-emacs-jp/emacs-jp.rb:18:in `<class:EmacsJp>'
/usr/local/Homebrew/Library/Taps/src256/homebrew-emacs-jp/emacs-jp.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1388:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:806:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
$

**Comment by SMillerDev** [comment]
The error is in this formula: https://github.com/src256/homebrew-emacs-jp/blob/master/emacs-jp.rb but that hasn't been updated in 2 years. I'd recommend removing it, or trying to fix it by finding the usage of "revision" and removing it.

**Comment by popoko2** [comment]
HI,

I removed usage of the 'revision' method from the file.
I saw 'brew doctor' worked for me.
Thank you very much.

I attach my fix in-line.

*** emacs-jp.rb.orig	2016-09-19 17:14:31.000000000 +0900
--- emacs-jp.rb	2018-05-01 20:05:23.000000000 +0900
***************
*** 16,22 ****
    end
  
    bottle do
!     revision 1
      sha256 "a799ddefe9768259397652a2b9d40e0b0a8907f658e288dc2096a3f4777a421b" => :el_capitan
      sha256 "ff8230366edd23657a2b2ddcd7fcfc49b3f8ff78a5b2be620908651dd7d2ea94" => :yosemite
      sha256 "3af5f90d7177e8185db5e288f7ead4210156c896b652450117fa8fc3e232bc39" => :mavericks
--- 16,22 ----
    end
  
    bottle do
!     # revision 1
      sha256 "a799ddefe9768259397652a2b9d40e0b0a8907f658e288dc2096a3f4777a421b" => :el_capitan
      sha256 "ff8230366edd23657a2b2ddcd7fcfc49b3f8ff78a5b2be620908651dd7d2ea94" => :yosemite
      sha256 "3af5f90d7177e8185db5e288f7ead4210156c896b652450117fa8fc3e232bc39" => :mavericks
