### ISSUE TITLE
ssh-askpass

### ISSUE THREAD

**Issue by saizai** [Homebrew/homebrew-core#27329]
This pull req provided it, & was closed only for being new: https://github.com/Homebrew/legacy-homebrew/pull/33717

Please rereview that (or others that provide ssh-askpass) & consider for merge.

ETA: Note that it has been updated since that PR.

**Comment by SMillerDev** [comment]
I'm afraid that a pull request for homebrew legacy won't help much, so you'll need to make a new one. What's wrong with the tap though?

**Comment by saizai** [comment]
The tap's OK, but it doesn't show in 'brew search'.

**Comment by SMillerDev** [comment]
It might be easier to fix that in the tap.

**Comment by saizai** [comment]
@SMillerDev I don't know how. @theseal?

**Comment by simmel** [comment]
@SMillerDev What can we fix in the tap to make it findable via `brew search`?

**Comment by simmel** [comment]
AFAICT we have the proper structure: 
https://github.com/theseal/homebrew-ssh-askpass

**Comment by SMillerDev** [comment]
That wasn't the repo that was linked before so I was surprised it even worked with the structure in the repo before. Just installed the real tap to check, but it shows up in search just fine. There's some audit errors that could be fixed but nothing seems broken.

**Comment by saizai** [comment]
$ brew search askpass
==> Searching local taps...
theseal/ssh-askpass/ssh-askpass ✔
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...

(With it installed.)

**Comment by SMillerDev** [comment]
Okay, so it shows in search for everyone. What's the problem with the tap then?

**Comment by simmel** [comment]
On Mon, 2018-05-14 at 03:31:09 -0700, Sai wrote:
>$ brew search askpass
>==> Searching local taps...
>theseal/ssh-askpass/ssh-askpass ✔
>==> Searching taps on GitHub...
>==> Searching blacklisted, migrated and deleted formulae...
>
>(With it installed.)

I think that's the issue that it doesn't show up when it isn't 
installed. But if no taps show up unless installed then that's fine.

**Comment by SMillerDev** [comment]
Homebrew doesn't know about taps unless you tell it where it can find them. I guess this can be closed then.
