### ISSUE TITLE
swiftlint has hardcoded dependency on XCode 7.3 

### ISSUE THREAD

**Issue by cakl** [Homebrew/homebrew-core#2735]
Installing the latest swiftlint version prompts the following error:

`$ brew install swiftlint`
`swiftlint: A full installation of Xcode.app 7.3 is required to compile this software.`

As far as I can see this way it's not possible to use swiftlint with XCode versions <=7.2. The [swiftlint 0.10.0 release message](https://github.com/realm/SwiftLint/releases/tag/0.10.0) says, that swiftlint is linked to the `xcode-select`ed version. So is this hardcoded dependency linking on version 7.3 really necessary?

**Comment by MikeMcQuaid** [comment]
If you can make it build on an earlier version of Xcode: we'll accept a PR to modify that dependency 👍

**Comment by cakl** [comment]
Does not work. My fault, thought the dependency was there because of the xcode-select linking. Sorry!
