### ISSUE TITLE
PowerDNS formula is missing support for very common with-mysql option

### ISSUE THREAD

**Issue by beamerblvd** [Homebrew/homebrew-core#27398]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew gist-logs pdns
Error: No logs.

$ brew config
HOMEBREW_VERSION: 1.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 648a7c7b1ed540e0629d3ce0a8b68a4a3dc9faed
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c09b192b049310f69de80403d48b02e8d1cfac40
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.4
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: N/A

$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why):
Install the PowerDNS formula and use it with the MySQL backend. The MySQL backend is one of the most common, if not _the_ most common, backends for PowerDNS.
- What happened (include command output):
The formula code [pdns.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdns.rb) does not contain any support for a MySQL option and does not pass the `--with-modules ... gmysql` config option when `configure`-ing, so PowerDNS is installed without the `/usr/local/Cellar/pdns/4.1.1/lib/pdns/libgmysqlbackend.so` library object. 
- What you expected to happen:
I expected there to be a `--with-mysql` option, but there is only a `--with-postgresql` option.
- Step-by-step reproduction instructions (by running `brew install` commands):
`brew install pdns --with-mysql` is not a valid option. `brew install pdns` installs PowerDNS without MySQL support.

[This helpful Gist](https://gist.github.com/mkyed/8a317d24b99c960e2546) contains a diff against `pdns.rb` that purports to add support for MySQL (except that it also removes support for PostgreSQL, so it's not a good final solution). In support of this issue, I could formulate a pull request with similar/more complete changes to support MySQL, but I'd like to first know that such a change will be entertained/allowed (i.e., there are no objections, like maybe MySQL support was intentionally omitted for some reason), and I'd also like to know whether I should make efforts to ensure that all possible `--with` variations can be supported simultaneously, or I should just only support one at a time.

**Comment by fxcoudert** [comment]
We're seeing from analytics that `--with-postgresql` option is almost unused:

```
install events in the last 30 days for pdns
================================================================================
1 | pdns                                                          | 39 |  95.12%
2 | pdns --with-postgresql                                        |  1 |   2.44%
3 | pdns --with-postgresql --with-remote                          |  1 |   2.44%
================================================================================
Total                                                             | 41 |    100%
================================================================================
```

It does not seem to justify adding another SQL backend.

**Comment by beamerblvd** [comment]
I would argue that's because PostgreSQL is not a very popular backend for PowerDNS. MySQL is a very popular backend for PowerDNS (again, like I said, possible the most-commonly used). I don't believe the unpopularity of the PostgreSQL option should influence whether we provide a more-common option.

**Comment by fxcoudert** [comment]
We'll consider a pull request, if it builds without trouble and is well-maintained.
