### ISSUE TITLE
imagesnap does not work in High Sierra

### ISSUE THREAD

**Issue by fgsch** [Homebrew/homebrew-core#27396]
See https://github.com/rharder/imagesnap/issues/16 for issue and https://github.com/rharder/imagesnap/pull/17 for fix.

brew config:

```
HOMEBREW_VERSION: 1.6.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 648a7c7b1ed540e0629d3ce0a8b68a4a3dc9faed
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c09b192b049310f69de80403d48b02e8d1cfac40
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3
XQuartz: N/A
```

**Comment by fxcoudert** [comment]
The issue is with the imagesnap project.
Please request upstream to integrated the proposed fixes, and make a new release, so we can update to that.

**Comment by fgsch** [comment]
This issue has been opened with upstream for ages and has not been resolved, hence I opened it here as the package is broken as things stand today.

**Comment by fxcoudert** [comment]
@fgsch I understand your frustration, but we can't maintain packages when upstreams stops to maintain them. If it's totally nonfunctional, we may consider declaring it unsupported on 10.13 to avoid users' frustration.
