### ISSUE TITLE
gdal does not build with MySQL

### ISSUE THREAD

**Issue by uranusjr** [Homebrew/homebrew-core#27442]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/uranusjr/267cefa8ced4b9064854672ef735eb11

To help us debug your issue please explain:
- What you were trying to do (and why)
    Install (actually upgrade from 1.11.5_4) GDAL with MySQL support.

- What happened (include command output)
    Failure with *Error: gdal 2.2.4 did not build*, but everything builds as far as I can tell.

- What you expected to happen
    GDAL upgrades successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)
    ```
    brew install gdal --with-mysql
    ```

**Comment by fxcoudert** [comment]
This is weird, as according to the logs everything did build fine indeed. Can you remove the old gdal, and then install?

**Comment by uranusjr** [comment]
I don’t dare remove it outright because I need it (PostGIS) for work, but I tried moving `/usr/local/Cellar/gdal` somewhere else temporarily and install from scratch. The result seems to be the same. https://gist.github.com/uranusjr/29a3b5d730e6ee841e029b6404a25a28

**Comment by fxcoudert** [comment]
Sorry @uranusjr, it appears to be working fine on our test machines.
Can you run `brew prune` and retry?

**Comment by ilovezfs** [comment]
@uranusjr I'm assuming you figured this out. Please let us know if you're still having a problem.

**Comment by uranusjr** [comment]
Actually no, it still didn’t work for me, but I really can’t risk tearing my working environment down to investigate further, so yeah, let’s leave it here if it only fail for me.
