### ISSUE TITLE
mcrypt missing?

### ISSUE THREAD

**Issue by craigcarnell** [Homebrew/homebrew-core#27561]
Since moving php7.1 to php@7.1 I can't find mcrypt!

php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
snmp
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
zip
zlib

[Zend Modules]

**Comment by SMillerDev** [comment]
You can use pecl to install mcrypt.

**Comment by craigcarnell** [comment]
@SMillerDev Thanks - what is the command? I don't even have pecl installed

**Comment by craigcarnell** [comment]
@SMillerDev It really isn't!

pecl
```
-bash: pecl: command not found
```

**Comment by SMillerDev** [comment]
It is part of both my php installs (as it's compiled with it) so I'm not sure what's going wrong with your install.
```sh
smillerdev@local ~> find /usr/local/Cellar/php* -name pecl
/usr/local/Cellar/php/7.2.5/bin/pecl
/usr/local/Cellar/php/7.2.5/pecl
/usr/local/Cellar/php@5.6/5.6.36/bin/pecl
/usr/local/Cellar/php@5.6/5.6.36/pecl
```

Is the php@7.1 install part of your path?

**Comment by craigcarnell** [comment]
no but I've added it to the path now

find /usr/local/Cellar/php* -name pecl
```
/usr/local/Cellar/php@7.1/7.1.17/bin/pecl
/usr/local/Cellar/php@7.1/7.1.17/pecl
```

pecl install mcrypt
```
Failed to download pecl/mcrypt within preferred state "stable", latest release is version 1.0.1, stability "snapshot", use "channel://pecl.php.net/mcrypt-1.0.1" to install
install failed
```

**Comment by SMillerDev** [comment]
Here's a post about installing mcrypt through pecl: https://forums.cpanel.net/threads/mcrypt-php-extension.617031/

**Comment by SMillerDev** [comment]
Yes, and it works exactly the same way. There's more than enough documentation about this on the internet. It even says how to install it in the error message by the way.
