### ISSUE TITLE
Error: undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by zhangtuoparis13** [Homebrew/homebrew-core#2758]
there is a probleme when i run brew doctor:

`➜  ~ brew doctor

Error: undefined method `include?' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/extend/os/mac/diagnostic.rb:317:in `check_for_beta_xquartz'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'`

Thank you to figure this problem.

**Comment by ahmedelgabri** [comment]
Same here. I followed the steps [here](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Common-Issues.md#brew-upgrade-errors-out) but I don't have an `examples/` folder, plus the error paths is a bit different that what in common issues. It's the same as @zhangtuoparis13 posted, and not in the `examples/` folder as in the common issues.

**Comment by HenrikWL** [comment]
I also have this problem.

**Comment by zhangtuoparis13** [comment]
i works for the moment ,Thank you.

**Comment by ahmedelgabri** [comment]
Thanks @xu-cheng for the quick fix 👍
