### ISSUE TITLE
mit-scheme config/build failed due to error in char size

### ISSUE THREAD

**Issue by matthewprussman** [Homebrew/homebrew-core#2760]
matthews-Air:usr matthewprussman$ brew install mit-scheme --with-x11
==> Downloading https://ftpmirror.gnu.org/mit-scheme/stable.pkg/9.2/mit-scheme-c-9.2.tar.gz
Already downloaded: /Users/matthewprussman/Library/Caches/Homebrew/mit-scheme-9.2.tar.gz
==> etc/make-liarc.sh --prefix=/usr/local/Cellar/mit-scheme/9.2_1 --mandir=/usr/local/Cellar/mit-scheme/9.2_1/share/man
Last 15 lines from /Users/matthewprussman/Library/Logs/Homebrew/mit-scheme/01.make-liarc.sh:
checking size of char... 0
checking size of short... 0
checking size of int... 0
checking size of long... 0
checking size of unsigned char... 0
checking size of unsigned short... 0
checking size of unsigned int... 0
checking size of unsigned long... 0
checking size of void *... 0
checking size of intptr_t... 0
checking size of uintptr_t... 0
checking size of intmax_t... 0
checking size of uintmax_t... 0
configure: error: SIZEOF_CHAR is not 1
configure: error: ./configure failed for microcode

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by matthewprussman** [comment]
Will do, it is specific to building with x11 so far....

**Comment by ilovezfs** [comment]
@matthewprussman any update on this?

**Comment by aw1621107** [comment]
Strangely enough, `brew install mit-scheme --with-x11 --build-from-source` works perfectly for me. I'm on 10.12, though, so not sure whether it's a version difference or something else.

Because configure seems to think the size of everything is 0, my first guess would be that clang is emitting an error or something of the sort.

**Comment by aw1621107** [comment]
Oh, and another question -- do you have /Applications/Xcode.app? That path *exactly*

**Comment by ilovezfs** [comment]
@matthewprussman please let us know if you're still seeing this issue occur.

**Comment by matthewprussman** [comment]
I will try again will x11 support install from a pull request.  Been
developing so needed a working version.
