### ISSUE TITLE
gcc-5.5.0 build failure on Scientific Linux 7

### ISSUE THREAD

**Issue by gipert** [Homebrew/homebrew-core#27650]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# gcc-5.5.0 build failure on Scientific Linux 7
I'm trying to `brew install gcc` on a remote server (on which I don't have sudo permissions -> can't fix some problems reported by `brew doctor`) using Linuxbrew (so installed without sudo). The build process fails with the error:
```
[...]
g++-4.8   -g -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -DGENERATOR_FILE  -o build/genmodes \
    build/genmodes.o build/errors.o ../build-x86_64-unknown-linux-gnu/libiberty/libiberty.a
build/gengenrtl > tmp-genrtl.h
build/gengenrtl: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
[...]
```

Here's the result of [`brew install gcc`](https://gist.github.com/474ada83ed2d24039474edcbe3b2f8ae)
Here's the result of [`brew install gcc --without-glibc`](https://gist.github.com/gipert/b4c62bd2760b2ba5ce35ab0200503d7e)

I don't understand this error because:
```
$ yum list | grep libstdc++
compat-libstdc++-33.x86_64               3.2.3-72.el7               @sl
libstdc++.i686                           4.8.5-16.el7_4.2           @sl-fastbugs
libstdc++.x86_64                         4.8.5-16.el7_4.2           @sl-fastbugs
libstdc++-devel.x86_64                   4.8.5-16.el7_4.2           @sl-fastbugs
compat-libstdc++-33.i686                 3.2.3-72.el7               sl
libstdc++-devel.i686                     4.8.5-16.el7_4.2           sl-fastbugs
libstdc++-docs.x86_64                    4.8.5-16.el7_4.2           sl-fastbugs
libstdc++-static.i686                    4.8.5-16.el7_4.2           sl-fastbugs
libstdc++-static.x86_64                  4.8.5-16.el7_4.2           sl-fastbugs
```
But I'm not that expert... Does this derive from the environment I'm working in (which in any case I can't really modify because I don't have admin rights)?

### steps to reproduce the issue
```
git clone https://github.com/Linuxbrew/brew.git ~/.linuxbrew 
export PATH="~/.linuxbrew/bin:$PATH"
export PATH="~/.linuxbrew/sbin::$PATH"
export MANPATH="$(brew --prefix)/share/man:$MANPATH"
export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
brew install gcc
```

**Comment by commitay** [comment]
Please report this here: https://github.com/Linuxbrew/homebrew-core/issues
