### ISSUE TITLE
brew upgrade should remember brew install options

### ISSUE THREAD

**Issue by claco** [Homebrew/homebrew-core#2767]
While this issue is specifically about the vim formula, I suspect more of them have this same issue w/ dependencies.

Up until about 3 weeks ago, the vim formula would either install the vim bottle (and only the vim bottle), or compile from source. When using the Ansible `homebrew` or `package` module, this meant that vim used the system perl/ruby/python language versions (or whatever you had active in rbenv/plenv/pyenv.

Now, `brew install vim` AND `brew upgrade vim` now pull in the perl/ruby/python bottles as well, which aren't the system language versions or not active versions in pyenv/plenv/rbenv. This means any plugin perviously compiled against other versions of languages (think command-t in ruby as an example) now don't work at all, yielding a broken configuration. 

To combat this, one must `brew install --build-from-source vim` to use the active/system languages. Even worse, if you're upgrading vim, you now have to `brew unlink vim` and then `brew install --build-from-source` again, as `brew upgrade` will simply pull in the perl/ruby/python bottles again.

All gripes aside about vim pulling in these language dependencies, if seems like `brew upgrade x` should remember what `brew install x` had done, so it can repeat the process correctly.

Because it does not, and because of the dependency issues needing `unlink` and a `install`, one can't really use the Ansible `homebrew` module with `state=latest` for some formulas without jumping through hoops.

**Comment by MikeMcQuaid** [comment]
It does remember installation options. In this case the issue is we've added a binary package for the first time and added new options you need to use: https://github.com/Homebrew/homebrew-core/blob/e40dc2e709ff5409c672e31c8f89ad31a3e9712e/Formula/vim.rb#L26-L28. We can't preserve the implied `--build-from-source` as that would mean we could never add binary packages and have them used.

> Because it does not, and because of the dependency issues needing unlink and a install, one can't really use the Ansible homebrew module with state=latest for some formulas without jumping through hoops.

We don't support this module, just FYI.

**Comment by claco** [comment]
'We can't preserve the implied --build-from-source as that would mean we could never add binary packages and have them used.'

Is that because that option propagates down to dependencies?

**Comment by MikeMcQuaid** [comment]
More just that, in this case, it'll imply `--build-from-source` for a package where no binary package was available so it would assume no-one wanted the binary package when it was first introduced.

**Comment by claco** [comment]
FYI, this is now happening in other packages, meaning brew upgrade has an inconsistent behavior as there seems to be no best practice.  https://github.com/Homebrew/homebrew-core/pull/5042

**Comment by MikeMcQuaid** [comment]
This happens with all packages and (probably) always has.

**Comment by chaimleib** [comment]
I have a related issue that brew options like "--with-rc=$HOME/.bashrc.d/myrc.sh" aren't being remembered. The package in question is from `brew install chaimleib/formulae/repoactions`.

**Comment by MikeMcQuaid** [comment]
@chaimleib Can you run `cat /usr/local/Cellar/repoactions/0.0.*/INSTALL_RECEIPT.JSON`? Thanks!

**Comment by chaimleib** [comment]
I upgraded soon after, so here's how it looks now:
```
$ brew info repoactions
chaimleib/formulae/repoactions: stable 0.0.9
Run a script whenever you enter a git repo
https://github.com/chaimleib/repoactions
/usr/local/Cellar/repoactions/0.0.9 (9 files, 32.8K) *
  Built from source on 2016-11-22 at 14:01:07 with: --with-rc=
From: https://github.com/chaimleib/homebrew-formulae/blob/master/repoactions.rb
==> Options
--with-rc=
	Specify where to inject login setup (default: ~/.profile)

$ cat /usr/local/Cellar/repoactions/0.0.*/INSTALL_RECEIPT.json
{"used_options":["--with-rc="],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"changed_files":null,"time":1479852067,"source_modified_time":1479851836,"HEAD":"c3f959d6af36f075600aac63f208d59c30cd602c","stdlib":null,"compiler":"clang","runtime_dependencies":[],"source":{"path":"/usr/local/Homebrew/Library/Taps/chaimleib/homebrew-formulae/repoactions.rb","tap":"chaimleib/formulae","spec":"stable","versions":{"stable":"0.0.9","devel":null,"head":null,"version_scheme":0}}}
```

**Comment by MikeMcQuaid** [comment]
@chaimleib Ok, so it seems we don't store the value used for `ARGV.value` options. Could you create an issue asking for that in Homebrew/brew? Thanks!
