### ISSUE TITLE
Postgis missing dependency on qhull

### ISSUE THREAD

**Issue by grischard** [Homebrew/homebrew-core#27699]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [yes] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [yes] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [yes] ran `brew update` and can still reproduce the problem?
- [yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [yes] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

After pouring postgis-2.4.4_1.high_sierra.bottle.tar.gz, running `ALTER EXTENSION postgis UPDATE TO "2.4.4";`

- What happened (include command output)

```
[local] stereo@gis=#   ALTER EXTENSION postgis UPDATE TO "2.4.4";
ERROR:  58P01: could not load library "/usr/local/lib/postgresql/rtpostgis-2.4.so": dlopen(/usr/local/lib/postgresql/rtpostgis-2.4.so, 10): Library not loaded: /usr/local/opt/qhull/lib/libqhull.7.dylib
  Referenced from: /usr/local/opt/gdal/lib/libgdal.20.dylib
  Reason: image not found
LOCATION:  internal_load_library, dfmgr.c:240
Time: 724.661 ms
```

- What you expected to happen

[local] stereo@gis=#   ALTER EXTENSION postgis UPDATE TO "2.4.4";
ALTER EXTENSION
Time: 468.549 ms
[local] stereo@gis=#

- Step-by-step reproduction instructions (by running `brew install` commands)

```bash

brew install postgis postgresql
createdb -E UTF8 -T template0 gis
echo "CREATE EXTENSION postgis" | psql -d gis
```

- Workaround

`brew install qhull` solved the missing dependency. I'm not sure whether the dependency should be in postgis or in gdal.

**Comment by commitay** [comment]
```
brew linkage --test gdal
Broken dependencies:
  /usr/local/opt/qhull/lib/libqhull.7.dylib (qhull)
```

We have a couple of options to fix this:
```
./configure -h | grep qhull
  --with-qhull=ARG     Include QHull support (ARG=no, yes, internal)
```

@ilovezfs Any preference?

**Comment by fxcoudert** [comment]
Given qhull is very small and gdal already has lots of dependencies, I'd say we make it a dependency.

**Comment by ilovezfs** [comment]
Unless a user is asking for the dep for some purpose we should just disable it.

**Comment by ilovezfs** [comment]
@grischard This is now fixed thanks to @commitay
