### ISSUE TITLE
Homebrew build 3.14 of get_iplayer does not seem to implement new SSL requirement 

### ISSUE THREAD

**Issue by cathorn** [Homebrew/homebrew-core#27706]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was upgrading from 3.13 to 3.14. Everything installs correctly, but the new build generates an SSL error when it attempt to pull a BBC video stream. The source maintainer (dinkypumpkin) says in his online support system that this is because the homebrew maintainer did not implement the new SSL requirement in the most recent release notes. 
- What happened (include command output)
https://forums.squarepenguin.co.uk/attachment.php?aid=325
- What you expected to happen
Under the previous version, 3.13, this command executed with no errors.
- Step-by-step reproduction instructions (by running `brew install` commands)
In a terminal window (one must be in the UK to get access to the BBC)
brew install get_iplayer
get_iplayer https://www.bbc.co.uk/iplayer/episode/b0b2s8d5/joshua-v-klitschko-return-to-wembley

This will generate an SSL error using 3.14

**Comment by fxcoudert** [comment]
Issue should be fixed.
