### ISSUE TITLE
GCC 8.1 bottle fails when brew is not in /usr/local

### ISSUE THREAD

**Issue by andreasnoack** [Homebrew/homebrew-core#27751]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [-] ran `brew doctor`, fixed all issues and can still reproduce the problem? *I'm warned that the installation is outside `/usr/local` but I haven't "fixed" the issue since installing outside `/usr/local` is what triggered this issue*
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/andreasnoack/ce02bc62625bef597615a4e91aa97564
- [-] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Many Julia packages get their binary dependencies from a homebrew installation managed by the Julia package https://github.com/JuliaPackaging/Homebrew.jl. After the latest update of GCC, several users noticed (since it takes forever) that GCC was installed from source.

The command to reproduce this is
```
➜  ~ .julia/v0.6/Homebrew/deps/usr/bin/brew install --force-bottle gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-8.1.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/andreasnoack/Library/Caches/Homebrew/gcc-8.1.0.high_sierra.bottle.tar.gz
==> Pouring gcc-8.1.0.high_sierra.bottle.tar.gz
Error: Failed changing install name in /Users/andreasnoack/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libubsan.1.dylib
  from @@HOMEBREW_CELLAR@@/gcc/8.1.0/lib/gcc/8/i386/libstdc++.6.dylib
    to /Users/andreasnoack/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libstdc++.6.dylib
Error: Updated load commands do not fit in the header of /Users/andreasnoack/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libubsan.1.dylib. /Users/andreasnoack/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libubsan.1.dylib needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
Warning: Bottle installation failed: building from source.
```

and I tried with another fresh clone of homebrew so I think the issue is the path since bottle install works with my "system" homebrew installation.

**Comment by commitay** [comment]
The bottle block is:
```
  bottle do
    sha256 "45cfaae98c9e82d6eb90449a541019c7b5f10c20e0221acc3b1a9b6fe48f5f39" => :high_sierra
    sha256 "5875cde355e4e7611ccd58c3ab4c35ab27740bca99e37de59081953111de4ce0" => :sierra
    sha256 "d38130e28eaf1d76e29f09deb616a5a1063dad898a2856879d93a67f51573ef6" => :el_capitan
  end
```
Without a `cellar :any_skip_relocation` or `cellar :any`, it will be build from source when installed outside of `/usr/local`

**Comment by ilovezfs** [comment]
This is now fixed if you `brew update`

**Comment by andreasnoack** [comment]
> This is now fixed if you `brew update`

No. Just tried and the issue remains.

**Comment by brilhana** [comment]
Same issue on macOS 10.13.4.

**Comment by Roger-luo** [comment]
same issue on Mac OS 10.13.5

**Comment by denizyuret** [comment]
Why is this issue closed?  Still a serious problem effecting Macs trying to use HDF5, JLD, etc.

**Comment by ilovezfs** [comment]
The gcc bottle is not marked as relocatable so we make no guarantees about `--force-bottle` working. We'd happily review a PR changing the formula in some way so that this doesn't happen but none of this maintainers are working on this and we don't just leave issues open no one is working on.

**Comment by denizyuret** [comment]
Is there any workaround to making HDF5, JLD etc. work on OSX besides compiling gcc8?

**Comment by stillyslalom** [comment]
> Our CI programmatically determines if the bottle can be installed outside of /usr/local

Where can the results of these CI runs be found? We need to determine what changed in the CI's attitude towards gcc between v7.3 and v8. This PR seems somewhat related: https://github.com/Homebrew/legacy-homebrew/pull/41568

**Comment by ilovezfs** [comment]
@stillyslalom that's a red herring. Those particular checks have nothing to do with "Error: Updated load commands do not fit in the header" just with whether strings like /usr/local are found.

**Comment by stillyslalom** [comment]
Good to know, but I'd still like to know where the results of the CI runs can be found.

**Comment by nickeubank** [comment]
@ilovezfs This still seems to be causing a lot of problems for folks, especially in Julia libraries that try and build with HDF5 (e.g. @denizyuret comment). Any chance this was closed prematurely?

**Comment by commitay** [comment]
> The gcc bottle is not marked as relocatable so we make no guarantees about --force-bottle working. We'd happily review a PR changing the formula in some way so that this doesn't happen but none of the maintainers are working on this and we don't just leave issues open no one is working on.

**Comment by nickeubank** [comment]
ok, thanks.
