### ISSUE TITLE
Bats Repo is Inactive

### ISSUE THREAD

**Issue by cmcginty** [Homebrew/homebrew-core#27796]
Bats has been forked to https://github.com/bats-core/bats-core due to inactivity of the original maintainer.

**Comment by commitay** [comment]
I'm assuming this is a request that the `bats` formula should be changed to point to https://github.com/bats-core/bats-core?

We aren't going to switch to a fork unless it has become significantly more notable (stars, forks, watchers, etc) than the original repo or original repo "blesses" the fork as the new canonical source.
