### ISSUE TITLE
libquicktime --ffmpeg option broken

### ISSUE THREAD

**Issue by RSully** [Homebrew/homebrew-core#27811]
libquicktime was updated to build against ffmpeg v3, but not v4. The project was updated in Feb of this year to work with ffmpeg v4, but no release was made (and I'm not expecting one) so it may be necessary to include another patch or add an option to build HEAD from git. 

Related #527

**Comment by fxcoudert** [comment]
If libquicktime does not issue new releases, I'd say we remove the option rather than add yet another patch. Option isn't used anyway:

```
install events in the last 30 days
================================================================================
1 | libquicktime                                                  | 18 | 100.00%
================================================================================
```

**Comment by ilovezfs** [comment]
@RSully thanks for reporting this. The option is now gone.

**Comment by RSully** [comment]
It compiles/works fine against ffmpeg@2.8 (and I believe ffmpeg 3), and HEAD works against ffmpeg v4 I believe. 

Without ffmpeg libquicktime is rather useless, as I can't seem to use it for h264 videos.
