### ISSUE TITLE
cfitsio examples bad SHA256

### ISSUE THREAD

**Issue by parejkoj** [Homebrew/homebrew-core#2782]
When I try to install the cfitsio examples via the "--with-examples" argument--`brew install cfitsio --with-examples`--I get a bad SHA256 error, as shown below.

I suspect that the cexamples.zip files changed since the brew was last touched. Should we just update the SHA256 sum?

A gist-log is here, though I'm doubt it is necessary: https://gist.github.com/anonymous/7cead437915e03961e43838fc8dbb3cc

```
$ brew install cfitsio --with-examples
==> Downloading https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio3370.
Already downloaded: /Users/parejkoj/Library/Caches/Homebrew/cfitsio-3.370.tar.gz
==> ./configure --prefix=/usr/local/Cellar/cfitsio/3.370 --enable-reentrant
==> make shared
==> make install
==> make fpack funpack
==> Downloading https://heasarc.gsfc.nasa.gov/docs/software/fitsio/cexamples/cex
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 85b2deecbd40dc2d4311124758784b1ff11db1dd93ac8e7a29f3d6cda5f8aa3d
Actual: ed17b6d0f2a3d9858d6b19a073b2479823b37e501b7fd0ef9fa08988ad7ab8fc
Archive: /Users/parejkoj/Library/Caches/Homebrew/cfitsio--examples-2014.01.23.zip
To retry an incomplete download, remove the file above.
```

**Comment by DomT4** [comment]
Looks like it's been updated, aye:
```
Last-Modified: Wed, 06 Apr 2016 15:24:26 GMT
```
There's actually a `cfitsio` update to `3.390` available as well. We'd review a PR to update both, if you'd like to submit one?

**Comment by DomT4** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/commit/dfc3f215e57b2a988ccd3d997e41d7b2fe7412bf.

**Comment by parejkoj** [comment]
Thank you @DomT4 !
