### ISSUE TITLE
cryptopp failed to build on 10.11.5

### ISSUE THREAD

**Issue by danhstevens** [Homebrew/homebrew-core#2783]
### Bug report:

`brew install cryptopp` fails with:

```
Testing RDSEED generator...

CryptoPP::Exception caught: RDSEED: GCC_RSA_GenerateBlock operation failed
```

### Logs:
https://gist.github.com/anonymous/f217e3a6df7ebcd6b558d7ee96c78aba

**Comment by dunn** [comment]
I guess it's possible those non-Homebrew Node.js headers are causing mischief; you could try moving them out of `/usr/local` temporarily and trying again.

**Comment by c-hamilton** [comment]
Saw the same issue attempting to install ethereal using:  "brew install cpp-ethereum --with-gui" on El Capitan 10.11.4 on 06-09-16

"Testing RDSEED generator...
CryptoPP::Exception caught: RDSEED: GCC_RSA_GenerateBlock operation failed"

Didn't see any Node.js headers in usr/ local/ as suggested by dunn. Not sure how to pull down build logs.
 Hope this helps.

**Comment by dunn** [comment]
@c-hamilton you can get the build logs with `brew gist-logs cpp-ethereum`; but since that's a different formula, please open a separate issue!

**Comment by c-hamilton** [comment]
I opened a new issue here: https://github.com/Homebrew/homebrew-core/issues/2873

**Comment by tdsmith** [comment]
@c-hamilton: You can post the cryptopp build logs with `brew gist-logs cryptopp`.

**Comment by tdsmith** [comment]
It's a test which is failing; I'm not sure how to diagnose that. We started building the tests recently. They pass for me and the test-bot.

@c-hamilton: Can you share the output of `brew config`? I'm wondering if this is somehow an Xcode-only related issue.

**Comment by tdsmith** [comment]
Discussed on cryptopp mailing list: http://comments.gmane.org/gmane.comp.encryption.cryptopp/8028

**Comment by tdsmith** [comment]
And a fix: https://github.com/weidai11/cryptopp/commit/0059f486ad0467d5c4dc692db99a5a5f96c2a733

**Comment by danhstevens** [comment]
Confirmed to be working now. Thanks guys! 👍
