### ISSUE TITLE
brew prune OR brew cleanup seems to mess up .config folder

### ISSUE THREAD

**Issue by trollworkout** [Homebrew/homebrew-core#2786]
Either `brew prune` or `brew cleanup` seems to be messing up my `~/.config` folder either turning it into a file (prev versions) or changing it's perms. I noticed this because older versions of aseprite used to store it's prefs under ~/.config and after both of those commands aseprite no longer wants to run until i erase .config. Now Aseprite has been migrated to ~/Library.. this no longer matters but the this issue still exists with homebrew so I had to report it. 

OSX El Capitan version Homebrew 0.9.9

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by trollworkout** [comment]
@MikeMcQuaid 

I uninstalled  a few brew applications using `brew remove`. Finally I wanted to cleanup the uninstallation using `cleanup` and `prune`.

My ~/.config folder was altered making all other programs that depend on it not run. 

I expected brew to be able to change the contents of ~/.config without altering the folder itself or it's permissions.


`brew install gimp` (installs a lot of dependencies)
`brew remove gimp harfbuzz pango gdk-pixbuf atk gtk gtk+ gt libmf libwmf libwebp librsvg webp py2cairo pygtk dbus gtk+3 gtk-mac-integration hicolor-icon-theme  xz zlib readline python pygobject pkg-config pixman pcre openssl mpfr2 lynx libtiff libpng libffi libepoxy libcroco jpeg icu4c gsettings-desktop-schemas gobject-introspection gmp4 glib gettext gdbm freetype fontconfig cairo babl aalib` (theres a bunch of gimp deps)
`brew cleanup`
`brew doctor` <- this one is just in case i uninstalled something that brew needs
`brew prune`

Now ~/.config folder has different permissions making it no longer usable by other programs or applications that use it.

**Comment by MikeMcQuaid** [comment]
Can you try to recreate that directory and figure out whether it was `cleanup` or `prune`? Thanks.

**Comment by trollworkout** [comment]
@MikeMcQuaid  i will try

**Comment by resistor4u** [comment]
May be unrelated issue, but FWIT i think it's `brew prune`. I haven't used `brew prune` in months, and just about two hours ago used it to prune a lingering symlink. When I went back to `brew update`, i get 
`ldawg @MBP ~$ brew update`
`Warning: git-2.9.1 already installed`
`Error: Git must be installed and in your PATH!`

when i have never experienced this before, or ever had any PATH problems. `which -a git` shows

`/usr/local/bin/git`
`/usr/bin/git`

and `brew doctor` gives me no indication that anything is wrong. i tried `source .bash_profile` and no help there. again, not sure it's related, but just my $.02

**Comment by MikeMcQuaid** [comment]
@resistor4u Unrelated but please run `git fetch; git reset --hard origin/master; brew update` to fix this.

**Comment by ilovezfs** [comment]
@trollworkout please let us know if this is still a problem for you after following the instructions from @MikeMcQuaid
