### ISSUE TITLE
Add adwaita-icon-theme as dependency for gtk+3

### ISSUE THREAD

**Issue by onkarshinde** [Homebrew/homebrew-core#27873]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Build, install and run [GNUSim8085](https://github.com/GNUSim8085/GNUSim8085) on OS X High Sierra (10.13).
- What happened (include command output)
The application has many missing icons in the menu, tool bar and buttons. This is happening because adwaita-icon-theme is not installed. The hicolor-icon-theme does not include all the stock icons.
- What you expected to happen
When gtk+3 was installed the adwaita-icon-theme should have been installed automatically. The icons should show properly.
- Step-by-step reproduction instructions (by running `brew install` commands)
  - brew install autoconf
  - brew install automake
  - brew install pkg-config
  - brew install gtksourceview3
  - git clone https://github.com/GNUSim8085/GNUSim8085.git
  - cd GNUSim8085
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
Run command gnusim8085, this should launch application window. Check missing icons on the toolbar and some of the buttons.

The solution to this problem is to add dependency adwaita-icon-theme to gtk+3 formula. Ubuntu packages include these dependency, so it makes sense for brew to have this dependency as well.

**Comment by tschoonj** [comment]
That's impossible I'm afraid: `gtk+3` is a `:build` time dependency of `adwaita-icon-theme`, as `gtk-update-icon-cache` is required during the `make install` phase. 

The Ubuntu people managed to avoid this by packaging `gtk-update-icon-cache` separately, but we cannot do that.
