### ISSUE TITLE
yafc formula is pointing to a parked domain

### ISSUE THREAD

**Issue by tobiasboyd** [Homebrew/homebrew-core#27906]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Hello! I found this morning I couldn't `brew install yafc` on a new machine - the bottled version segfaults, so I tried `--build-from-source` which fails with a bad hash. I tried to submit the errors with `gist-logs` but it says there aren't any, sigh. Digging a little, I found that the old domain in the formula is now being squatted on. Since it seems like its development is happening on github now, I took a stab at `brew edit yafc` but it throws mystery errors. Here are some relevant bits:

```
[10:04:24] tnboyd:~ $ brew install --build-from-source yafc
==> Downloading http://www.yafc-ftp.com/downloads/yafc-1.3.7.tar.xz
Already downloaded: /Users/tnboyd/Library/Caches/Homebrew/yafc-1.3.7.tar.xz
Error: SHA256 mismatch
Expected: 4b3ebf62423f21bdaa2449b66d15e8d0bb04215472cb63a31d473c3c3912c1e0
Actual: e6ae559f28fd8bbfcd55ff45110cfac7ceeac035c882813f115c17fbe0de00c3
Archive: /Users/tnboyd/Library/Caches/Homebrew/yafc-1.3.7.tar.xz
To retry an incomplete download, remove the file above.
[10:04:37] tnboyd:~ $ brew gist-logs yafc
Error: No logs.
[10:04:40] tnboyd:~ $ brew config
HOMEBREW_VERSION: 1.6.3-40-g7b31a3d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7b31a3d024ccc0f44d96bfb3c41345b8b55583f3
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a07423bf0ac7cc33fdea7b43f55db8fec7309ab
Core tap last commit: 89 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.3.1
XQuartz: 2.7.11 => /opt/X11
[10:04:51] tnboyd:~ $ brew doctor
Your system is ready to brew.
[10:05:14] tnboyd:~ $
```

This _seemed_ like it should work, but all I get is a readline error? I apologize, I haven't tried to edit any formulas before.

```
class Yafc < Formula
  desc "Command-line FTP client"
  homepage "https://github.com/sebastinas/yafc"
  url "https://github.com/sebastinas/yafc/archive/v1.3.7.tar.gz"
  sha256 "332fca7508c2187e45bc7b3c8f1e7288e9cf8109636945035caa628a347869ff"
  revision 1

  bottle do
    sha256 "40c44b84a96b4cf65ee0c1d09a2770ede71e5cfd7fdf9c24504723a8b1eaef3f" => :high_sierra
    sha256 "05ea440c672b5283feaf2597a8c0525d3ff4228cd2347aabd3a69d282d245dd2" => :sierra
    sha256 "9cbbd25ce9019d92e6ed3c8ce5af9533b0d79d79f96b01fc8741016a3bd4eb39" => :el_capitan
    sha256 "3ac839135bac59b4d1d98cb662adc558109167fd21e69976dd39e1e3602de25b" => :yosemite
  end

  depends_on "pkg-config" => :build
  depends_on "readline"
  depends_on "libssh" => :recommended

  def install
    args = %W[
      --prefix=#{prefix}
      --with-readline=#{Formula["readline"].opt_prefix}
    ]
    args << "--without-ssh" if build.without? "libssh"

    system "./configure", *args
    system "make", "install"
  end

  test do
    download_file = testpath/"512KB.zip"
    expected_checksum = Checksum.new("sha256", "07854d2fef297a06ba81685e660c332de36d5d18d546927d30daad6d7fda1541")
    output = pipe_output("#{bin}/yafc -W #{testpath} -a ftp://speedtest.tele2.net/", "get #{download_file.basename}", 0)
    assert_match version.to_s, output
    download_file.verify_checksum expected_checksum
  end
end
```

**Comment by fxcoudert** [comment]
Official Github repo: https://github.com/sebastinas/yafc

**Comment by ilovezfs** [comment]
Please report this there as the README still points to the website.

**Comment by ilovezfs** [comment]
For now we'll use GitHub for the homepage and Debian mirrors for the url https://github.com/Homebrew/homebrew-core/pull/27937
