### ISSUE TITLE
sbt formula using URL shortener, corporate network issues

### ISSUE THREAD

**Issue by bkrodgers** [Homebrew/homebrew-core#27912]
I'm having a problem upgrading sbt through brew.  It looks like the sbt formula (https://github.com/Homebrew/homebrew-core/blob/master/Formula/sbt.rb) is using a URL shortener link of https://piccolo.link/sbt-1.1.5.tgz to download.  

Unfortunately, our corporate network has blocked this URL shortener.  Forcepoint has it categorized as "Elevated Exposure."  While I can put in a request to get this recategorized or whitelisted, is it really necessary to use a URL shortener within a brew formula?  I believe this categorization is done by Forcepoint, not our security office, so this issue will affect others who are behind Forcepoint if they have this category blocked.

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Update sbt on a corporate network

- What happened (include command output)

==> Downloading https://piccolo.link/sbt-1.1.5.tgz
==> Downloading from http://internal-proxy-ip/cgi-bin/blockpage.cgi?ws-session=session-id

- What you expected to happen

Normal upgrade.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew upgrade sbt

```
brew gist-logs sbt
Error: No logs.
```

**Comment by bkrodgers** [comment]
As I think about it, I'm not sure if this issue should be submitted here or to the sbt team, so I just submitted an issue there as well.  Apologies if I should have started with that.

**Comment by woodruffw** [comment]
This is the right place for reporting it, thanks.

I don't think we should be using this (apparently third party?) link shortener either. Unfortunately, it looks (after a very initial look) as if they're hiding the real request by proxying the traffic.

Pinging @ilovezfs for ideas.

**Comment by commitay** [comment]
@woodruffw https://github.com/Homebrew/homebrew-core/pull/27787#issuecomment-388597228

**Comment by woodruffw** [comment]
Hmm, maybe a `mirror` then? I don't remember if we cover this particular case, but it shouldn't be too hard to handle.

@commitay @ilovezfs

**Comment by fxcoudert** [comment]
If we get regular requests, meaning that there is a non-trivial fraction of users who are blocked, I think we should switch to a non-shortened URL. (And ask users to report it upstream, too.)

**Comment by ilovezfs** [comment]
Closing this out since it's an upstream issue.
