### ISSUE TITLE
Installing PHP with newest CURL and OpenSSL

### ISSUE THREAD

**Issue by rinseringma** [Homebrew/homebrew-core#27938]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [V] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [V] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [V] ran `brew update` and can still reproduce the problem?
- [V] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [V] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [V] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
**- What you were trying to do (and why)**
I'm trying to install PHP (latest version) with the latest version of CURL and OpenSSL on my Macbook running MacOSX Sierra.
**- What happened (include command output)**
The latest PHP got installed correctly, but it still was using an outdated version of CURL and so it was using SecureTransport protocol of Mac.

brew install curl --with-openssl

brew install php --with-homebrew-curl
==> Reinstalling php 
Warning: php: this formula has no --with-homebrew-curl option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/php-7.2.5.sierra.bottle.tar.gz
Already downloaded: /Users/rinseringma/Library/Caches/Homebrew/php-7.2.5.sierra.bottle.tar.gz
==> Pouring php-7.2.5.sierra.bottle.tar.gz

**- What you expected to happen**
I was expecting that PHP getting installed using the latest CURL en OpenSSL. Which as been working before migrating to homebrew/core.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install curl --with-openssl
brew install php --with-homebrew-curl

**Comment by louiemiranda** [comment]
Currently having the same issue, we needed a php5.6 with curl to use OpenSSL and not the following.

> php -i | grep "SSL Version"
> SSL Version => SecureTransport

What can we do to change it?

**Comment by louiemiranda** [comment]
I tried to make a tap and tried to explicitly indicate the curl library, but did not work after.

https://github.com/louiemiranda/homebrew-core/pull/1

Any help is much appreciated.

```
UPDATE PHP DEVELOPMENT ENVIRONMENT
TO LATEST USING homebrew/core formulae
MAY 2018
```

> Check curl version and ssl 

`curl -V`

> Check php version and curl ssl

`php -i | grep "SSL Version”`

> Check openssl version

`openssl version -a`

> List all installed php

`brew list | grep php`

> Uninstall curl, php and 

```
brew uninstall curl
brew list | grep curl | xargs brew uninstall
brew list | grep php56- | xargs brew uninstall

```
> Upgrade homebrew

```
brew update
brew upgrade
brew cleanup

```
> Backup old php configs

`sudo mv /usr/local/etc/php /usr/local/etc/php-old`

> Install openssl

> Backup
`sudo mv /usr/bin/openssl /usr/bin/openssl-old`

> Install openssl
`brew install openssl`

> Check
`ls -l /usr/local/opt/openssl`

> Manually link
`sudo ln -s /usr/local/Cellar/openssl/{version}/bin/openssl /usr/bin/openssl`

> Maybe we need the library
```
mkdir -p /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/

```

> Check version

`openssl version -a`

> Install latest curl with openssl

```
brew install curl --with-openssl
brew link curl --force

```
> brew install php5.6 using homebrew/core

https://formulae.brew.sh/formula/php@5.6

`brew install php@5.6`

`php -i | grep "SSL Version"`

**Comment by louiemiranda** [comment]
I GOT IT! I tap and recompiled! works now :)
