### ISSUE TITLE
For payara background service, add JAVA_VERSION env variable.

### ISSUE THREAD

**Issue by josephbruni** [Homebrew/homebrew-core#27947]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [* ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ *] ran `brew update` and can still reproduce the problem?
- [* ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/b872c08f08fe3a00b5d73024de76d38c

To help us debug your issue please explain:
- What you were trying to do (and why)
Tried using 'brew services start payara' to launch payara as a service
- What happened (include command output)
With both java 8 and java 10 installed, the launch failed
- What you expected to happen
Since payara requires java 8, it should launch if java 8 is installed (ignoring java 10)
- Step-by-step reproduction instructions (by running `brew install` commands)
Install both java 8 and java 10.
brew install payara
brew services start payara
.. note that payara is not running because the launchctl script is defaulting to java 10

I was able to get this to work by including the JAVA_VERSION=1.8 environment variable in the homebrew.mxcl.payara.plist file, under "EnvironmentVariables". This allows /usr/bin/java to pick the correct java. Java 10 does not work.

**Comment by apjanke** [comment]
To help us debug this, can you give us more detail on how to determine whether the `payara` service has started correctly?

I'm trying to reproduce this on macOS 10.13 with JDK 10.0.1 installed, and `brew services start payara` at least returns success.

```
[~]
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
[~]
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
[~]
$ brew install payara
==> Downloading https://search.maven.org/remotecontent?filepath=fish/payara/distributions/payara/4.1.2.174/payara-4.1.2.174.zip
Already downloaded: /Users/janke/Library/Caches/Homebrew/payara-4.1.2.174.zip
==> Caveats
You may want to add the following to your .bash_profile:
  export GLASSFISH_HOME=/usr/local/opt/payara/libexec/glassfish
  export PATH=${PATH}:${GLASSFISH_HOME}/bin

To have launchd start payara now and restart at login:
  brew services start payara
Or, if you don't want/need a background service you can just run:
  asadmin start-domain --verbose domain1
==> Summary
🍺  /usr/local/Cellar/payara/4.1.2.174: 1,909 files, 159.4MB, built in 3 seconds
[~]
$ brew services start payara
==> Successfully started `payara` (label: homebrew.mxcl.payara)
[~]
$
```

The right thing to do might be to change the services `plist` file to point to `opt_bin` instead of `opt_libexec`, since those commands are properly wrapped with the `/usr/libexec/java_home` Java locator command. I'd defer to people with more experience with Homebrew `plist` files for Java programs, though.

**Comment by josephbruni** [comment]
I noticed that brew services does not properly detect that the launch actually failed. The call to launchctl succeeded, but payer stops due to incompatibility with Java 9/10; it requires java 8.

The solution I provided — setting the environment variable JAVA_VERSION to 1.8 in the plist — allows the wrapper at /usr/bin/java the opportunity to start the compatible version. The default behavior of the wrapper is to select the highest version. If someone has both 8 and 10 installed, the wrapper will select 10 and fail.

If you want to see if Payara is running, you can execute the “asadmin” command in an attempt to communicate with the DAS.
