### ISSUE TITLE
spades.rb fails on EC2 instances

### ISSUE THREAD

**Issue by ncimb** [Homebrew/homebrew-core#27965]
Not sure if this is the right place to post this but I've contacted SPAdes developers as well.

Currently spades.rb points to:

`url "http://cab.spbu.ru/files/release3.11.1/SPAdes-3.11.1.tar.gz"`

However this URL is inaccessible from Amazon AWS EC2 instances on at least two subnets that I have instances running on. I believe this may be due to the blocking of Amazon EC2 IP's in Russia to disrupt the operation of Telegram messenger. I realise that this is a niche issue, but a download from a source that is not subject to IP blocks would solve it.

**Comment by SMillerDev** [comment]
I think this is both an issue for linuxbrew and for the SPAdes developers.

**Comment by ncimb** [comment]
I had a reply from the SPAdes team, it looks like there might be an alternate source for the download that would satisfy requirements in this case:

> Thank you for your interest in SPAdes.
> SPAdes is also available on gihub: https://github.com/ablab/spades/releases
> We do not maintain brew packages – consider reporting stuff there

**Comment by ncimb** [comment]
@ilovezfs yes, that fails over nicely to the mirror as anticipated, and thanks for the version bump :)
