### ISSUE TITLE
pyenv-virtualenv (1.1.1) can't install a working python 2.6.9

### ISSUE THREAD

**Issue by jsoref** [Homebrew/homebrew-core#27984]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

This won't work while pyenv-virtualenv is pinned to 1.1.1:
https://github.com/Homebrew/homebrew-core/blob/30abddeed8f2b8d6e3d7b5ee313ddcd2c8ff1671/Formula/pyenv-virtualenv.rb#L4
Because the bug was fixed after that was released: pyenv/pyenv-virtualenv#255 

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to set up a python 2.6.9 environment

- What happened (include command output)
```sh
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Traceback (most recent call last):
  File "/Users/jsoref/.pyenv/cache/get-pip.py", line 20649, in <module>
    main()
  File "/Users/jsoref/.pyenv/cache/get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "/Users/jsoref/.pyenv/cache/get-pip.py", line 82, in bootstrap
    import pip._internal
  File "/var/folders/r3/n29fz25x72x191fdv6mhhr3m0000gp/T/tmp9G2AR4/pip.zip/pip/_internal/__init__.py", line 33, in <module>
AttributeError: 'module' object has no attribute 'OPENSSL_VERSION_NUMBER'
error: failed to install pip via get-pip.py
```

- What you expected to happen
```sh
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
/home/jsoref/.pyenv/versions/2.6.9/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/jsoref/.pyenv/versions/2.6.9/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Installing pip from https://bootstrap.pypa.io/2.6/get-pip.py...
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already up-to-date: pip<10 in /home/jsoref/.pyenv/versions/2.6.9/envs/sqlparsing-py269/lib/python2.6/site-packages
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This is the output I get when I used:
```sh
curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
```
on ubuntu bionic (after downgrading libssl-dev to 1.0)

- Step-by-step reproduction instructions (by running `brew install` commands)
```sh
brew install pyenv-virtualenv;
pyenv install 2.6.9;
pyenv virtualenv 2.6.9 test
```

**Comment by vinyldarkscratch** [comment]
_OPENSSL_VERSION_NUMBER was added in python 2.7 so it appears that the default version of get-pip.py being served by bootstrap.pypa.io is no longer compatible with python 2.6._ [¹](https://github.com/pyenv/pyenv-installer/issues/70#issuecomment-374203210)

One thing I'm a little bit curious about is why you're using Python 2.6 rather than 2.7.  The deprecation warning that's appearing on your team states that Python themselves have dropped support for 2.6.  But either way, I've [submitted a pull request to upgrade this formula](https://github.com/Homebrew/homebrew-core/pull/28172).  😉

**Comment by vinyldarkscratch** [comment]
We're at a stand-still with the PR due to a slight confusion in the repository: https://github.com/pyenv/pyenv-virtualenv/issues/264
