### ISSUE TITLE
Chicken-and-egg issue with git installation/upgrade

### ISSUE THREAD

**Issue by julian45** [Homebrew/homebrew-core#27986]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Output of `brew config`:
```
HOMEBREW_VERSION: 1.6.3
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b67917c837f1fb9c5bf2494cfd89b4eee6802802
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: a58ec60cde13604660a765589f64d3dcf0a1cc47
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/julian/.cache/Homebrew
CPU: octa-core 64-bit 0x69e
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: N/A
Git: 2.16.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.47.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.4.0-17134-Microsoft x86_64 GNU/Linux
OS: Ubuntu 16.04.4 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: 20170115_1
```
Output of `brew doctor`: `Your system is ready to brew.`

**NOTE: If it's not clear from `brew config`'s output, I'm running this on WSL.**

**What I was trying to do and why:** `brew upgrade git` to get to the most recent version
**What happened:** Running the above command produced the following output:
```
==> Upgrading 1 outdated package, with result:
git 2.16.2 -> 2.17.0
==> Upgrading git
You must: brew install git
Error: Failure while executing: git config --replace-all homebrew.private true
```
When I ran `brew install git`, as the error said, I got the following (expected) error:
```
Error: git 2.16.2 is already installed
To upgrade to 2.17.0, run `brew upgrade git`
```
For reference, here's the output of `which git`: `/home/linuxbrew/.linuxbrew/bin/git`

**What I expected to happen:** A successful upgrade of `git`
**How to reproduce:** `brew upgrade git`

It's also worth noting that this same situation occurred on a MacBook Air. My apologies if there's an issue out for this already; GitHub's issue filters are super broad, so any mention of git was included in the results of my (specific) searches.

Quiet edit: fixed a copy-paste error

**Comment by ilovezfs** [comment]
This is Homebrew not Linuxbrew. You can report it to them here: https://github.com/Linuxbrew/homebrew-core/issues

**Comment by julian45** [comment]
My apologies, I got sent to the wrong repo somehow.
