### ISSUE TITLE
Wrong dependency relationship on HEIF support of ImageMagick

### ISSUE THREAD

**Issue by hguandl** [Homebrew/homebrew-core#28035]
In https://github.com/Homebrew/homebrew-core/issues/26444 it has been reported that [`imagemagick`](https://github.com/ImageMagick) can add [`libheif`](https://github.com/strukturag/libheif) to support HEIF. A PR https://github.com/Homebrew/homebrew-core/pull/26960 was also raised. But in fact, during https://github.com/Homebrew/homebrew-core/commit/0d4ca9d08c76ef5388665d8e6f71ba330ba6cce0, this issue was not solved completely.

`libheif` needs `libde265` to decode and `x265` to encode. In https://github.com/Homebrew/homebrew-core/commit/0d4ca9d08c76ef5388665d8e6f71ba330ba6cce0, only `libde265` was added to the formula of `imagemagick`, which means the HEIF support is actually not implemented. So it's `--with-libheif` rather than `--with-libde265` that should be added to the formula of `imagemagick`, and a new formula `libheif` should also be created.

https://github.com/Homebrew/homebrew-core/pull/26960 is a usable one. The only problem is that the support for macOS was fixed after some commits of the current release. So we need to use HEAD version or just after https://github.com/strukturag/libheif/commit/a237e50a.

**Comment by ilovezfs** [comment]
And that is why #26960 remains open. In the future, please fill out the template completely.
