### ISSUE TITLE
OpenCV in homebrew-core does not to include opencv_contrib

### ISSUE THREAD

**Issue by blucia0a** [Homebrew/homebrew-core#28040]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
More or less, I was trying to [Install OpenCV with opencv_contrib from homebrew](https://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/).  

Previously, the homebrew/science/opencv3 formula had an option for --with-contrib, which installed opencv_contrib with opencv.  Now the homebrew-core/opencv formula does not have this option.  I was trying to install opencv with opencv_contrib -- without the option, opencv_contrib seems not to be installed; with `--with-contrib` I got `Warning: opencv: this formula has no --with-contrib option so it will be ignored!`

- What happened (include command output)
$`brew install opencv --with-contrib`

> $ brew install opencv --with-contrib
> Warning: opencv: this formula has no --with-contrib option so it will be ignored!
> ==> Downloading https://homebrew.bintray.com/bottles/opencv-3.4.1_5.high_sierra.bottle.tar.gz
> Already downloaded: /Users/blucia0a/Library/Caches/Homebrew/opencv-3.4.1_5.high_sierra.bottle.tar.gz
> ==> Pouring opencv-3.4.1_5.high_sierra.bottle.tar.gz
> 🍺  /usr/local/Cellar/opencv/3.4.1_5: 551 files, 97.8MB

- What you expected to happen
Either opencv_contrib is installed by default, or the --with-contrib option enables the installation of opencv_contrib.

- Step-by-step reproduction instructions (by running `brew install` commands)
`$brew install opencv --with-contrib`

You will see that the option is disabled in the warning I pasted above.  If you exclude the option, opencv_contrib packages are not included in the installation (e.g., opencv2/text).

**Comment by ilovezfs** [comment]
It's always built with contrib https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb#L38
