### ISSUE TITLE
Aspell fails to build with "--with--lang-nb" (norwegian) on 10.13.4

### ISSUE THREAD

**Issue by epichub** [Homebrew/homebrew-core#28074]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
It reports that I do not have xcode 9.3 and should upgrade from 9.2, however app store could not find any update to xcode. However this issue should not be related to xcode.
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
It did work.

To help us debug your issue please explain:
- What you were trying to do (and why)
Tried to install aspell with norwegian dictionary
- What happened (include command output)
command `brew install --with-lang-nb`
output:
```
==> Downloading https://ftp.gnu.org/gnu/aspell/aspell-0.60.6.1.tar.gz
Already downloaded: /Users/epic/Library/Caches/Homebrew/aspell-0.60.6.1.tar.gz
==> Patching
patching file interfaces/cc/aspell.h
==> ./configure --prefix=/usr/local/Cellar/aspell/0.60.6.1_1
==> make install
==> Downloading https://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-2017.01.22-0.tar.bz2
Already downloaded: /Users/epic/Library/Caches/Homebrew/aspell--en-0.tar.bz2
==> ./configure --vars ASPELL=/usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell PREZIP=/usr/local/Cellar/aspell/0.60.6.1_1/bin/prezip
==> make install
==> Downloading https://ftp.gnu.org/gnu/aspell/dict/de/aspell6-de-20030222-1.tar.bz2
Already downloaded: /Users/epic/Library/Caches/Homebrew/aspell--de-20030222-1.tar.bz2
==> ./configure --vars ASPELL=/usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell PREZIP=/usr/local/Cellar/aspell/0.60.6.1_1/bin/prezip
==> make install
==> Downloading https://ftp.gnu.org/gnu/aspell/dict/es/aspell6-es-1.11-2.tar.bz2
Already downloaded: /Users/epic/Library/Caches/Homebrew/aspell--es-1.11-2.tar.bz2
==> ./configure --vars ASPELL=/usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell PREZIP=/usr/local/Cellar/aspell/0.60.6.1_1/bin/prezip
==> make install
==> Downloading https://ftp.gnu.org/gnu/aspell/dict/fr/aspell-fr-0.50-3.tar.bz2
Already downloaded: /Users/epic/Library/Caches/Homebrew/aspell--fr-0.50-3.tar.bz2
==> ./configure --vars ASPELL=/usr/local/Cellar/aspell/0.60.6.1_1/bin/aspell PREZIP=/usr/local/Cellar/aspell/0.60.6.1_1/bin/prezip
==> make install
==> Downloading https://ftp.gnu.org/gnu/aspell/dict/nb/aspell-nb-0.50.1-0.tar.bz2
Already downloaded: /Users/epic/Library/Caches/Homebrew/aspell--nb-0.tar.bz2
aspell-nb-0.50.1-0/bokm�l.alias: Can't create 'aspell-nb-0.50.1-0/bokm�l.alias'
tar: Error exit delayed from previous errors.
Error: Failure while executing: tar xjf /Users/epic/Library/Caches/Homebrew/aspell--nb-0.tar.bz2
```
- What you expected to happen
It should install aspell with norwegian the (NB) dictionary.
- Step-by-step reproduction instructions (by running `brew install` commands)
1. Run `brew install --with-lang-nb`
2. See above output.

The gist is here [https://gist.github.com/4107a49db3ddfbc7991862cb60789360](https://gist.github.com/4107a49db3ddfbc7991862cb60789360)

It seems that the .tar.bz2 file containing the norwegian dictionary contains filenames that does not agree with macOS, I have tried setting different UTF8 and ISO8859-1 locales that contains the norwegian character in the file ("å") through LC_CTYPE and LANG, but it does not seem to work.

**Comment by apjanke** [comment]
I believe this is the same issue as #20108, and the easy fix is probably to remove the `is` and `nb` dictionaries from the Homebrew packages.

**Comment by epichub** [comment]
Well I did want the nb dict for a reason, I do write norwegian from time to time in emacs, which uses aspell for spell checking. But reading issue #20108 I can see that there is a manual way of installing the files?

**Comment by bushwakko** [comment]
I also have the same issue. `nb` is the standard norwegian language package, so not installing it kind of defeats the purpose for me, which is to get norwegian spell checker.

Ref. the #20108 issue, I'd rather you remove is and nb from the list trigger by --with-all-lang, and keeping --with-lang-nb. Ideally, it would be best to fix the issue in brew, as apparently unpacking it works in other contexts.

**Comment by apjanke** [comment]
@epichub Yes, you can still install the dictionaries manually. Like so:

```
wget https://ftpmirror.gnu.org/aspell/dict/nb/aspell-nb-0.50.1-0.tar.bz2
tar xf aspell-nb-0.50.1-0.tar.bz2
cd aspell-nb-0.50.1-0
./configure --vars ASPELL=$(brew --prefix)/bin/aspell PREZIP=$(brew --prefix)/bin/prezip
make install
```

This will throw errors (at the `tar` and `make install` steps), but the main dictionary files will still be installed; it'll just be missing a couple aliases.

For reference, the errors look like this:

```
[~/tmp/aspell/dicts/aspell-nb-0.50.1-0]
$ tar xf aspell-nb-0.50.1-0.tar.bz2
aspell-nb-0.50.1-0/bokm�l.alias: Can't create 'aspell-nb-0.50.1-0/bokm�l.alias'
tar: Error exit delayed from previous errors.
[✘ ~/tmp/aspell/dicts/aspell-nb-0.50.1-0]
$ cd aspell-nb-0.50.1-0
[~/tmp/aspell/dicts/aspell-nb-0.50.1-0/aspell-nb-0.50.1-0]
$ ./configure --vars ASPELL=$(brew --prefix)/bin/aspell PREZIP=$(brew --prefix)/bin/prezip
Finding Dictionary file location ... /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60
Finding Data file location ... /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60
[~/tmp/aspell/dicts/aspell-nb-0.50.1-0/aspell-nb-0.50.1-0]
$ make install
/usr/local/bin/word-list-compress d < nb.cwl | /usr/local/bin/aspell  --lang=nb create master ./nb.rws
mkdir -p /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp nb.rws bokmal.alias bokm�l.alias nb.multi no.alias norsk.alias /usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/
cp: bokm�l.alias: No such file or directory
make: *** [install] Error 1
```

It occurs to me that we could maybe work around this in Homebrew by just having the formula ignore errors from the dictionary installation step (maybe just for known-problematic dictionaries). Though that could take some fiddling with the resource unpack step to get it to ignore errors from `tar`.

@bushwakko At this point, I think that the behavior is the same in both Homebrew and other contexts — an error is thrown in either case. It's just that in the case of Homebrew, `brew` notices the error and stops the installation process, whereas in the manual installation, you can choose to ignore the error and keep going.

**Comment by apjanke** [comment]
Reported upstream: http://lists.gnu.org/archive/html/aspell-devel/2018-05/msg00000.html
