### ISSUE TITLE
hdf5 fails to build with gcc-8

### ISSUE THREAD

**Issue by HDHarry** [Homebrew/homebrew-core#28138]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install hdf5 using gcc-8 because of a project requiring gcc and linking against hdf5. 
- What happened (include command output)
installing hdf5 with compiler set to gcc-8 fails during ```make install```, cannot identify the problem clearly, also not from the log file mentioned in error thrown.
See code below: 
```
pc145:utopia user $ brew install hdf5 --cc=gcc-8
==> Downloading https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.2/src/hdf5-1.10.2.tar.bz2
Already downloaded: /Users/user/Library/Caches/Homebrew/hdf5-1.10.2.tar.bz2
==> autoreconf -fiv
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/hdf5/1.10.2_1 --with-szlib=/usr/local/opt/szip --enable-build-mode=production --enable-fortran --enable-cxx
==> make install
Last 15 lines from /Users/user/Library/Logs/Homebrew/hdf5/03.make:
+ /usr/bin/install -c ./ex_ds1.c /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c/.
+ /usr/bin/install -c ./image24pixel.txt /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c/.
+ /usr/bin/install -c ./image8.txt /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c/.
+ /usr/bin/install -c ./pal_rgb.h /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c/.
+ /usr/bin/install -c run-hlc-ex.sh /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c/.
+ /usr/bin/install -c ./run-hl-ex.sh /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/.
../../../bin/mkdirs /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/fortran
make: *** [install-recursive] Error 1
make: *** Waiting for unfinished jobs....
+ /usr/bin/install -c ./exlite.f90 /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/fortran/.
+ /usr/bin/install -c ./ex_ds1.f90 /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/fortran/.
+ /usr/bin/install -c run-hlfortran-ex.sh /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/fortran/.
../../../bin/mkdirs /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c++
+ /usr/bin/install -c ./ptExampleFL.cpp /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c++/.
+ /usr/bin/install -c run-hlc++-ex.sh /usr/local/Cellar/hdf5/1.10.2_1/share/hdf5_examples/hl/c++/.

READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen
Successful install, as was the case (and is) with gcc-7

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install gcc
brew install hdf5 --cc=gcc-8
```

- Files which may be of use: 
[brew config output](https://github.com/Homebrew/homebrew-core/files/2026524/brew_config.txt)
[brew doctor output](https://github.com/Homebrew/homebrew-core/files/2026529/brew_doctor.txt)
[logfile mentioned in error message](https://github.com/Homebrew/homebrew-core/files/2026533/hdf5_gcc-8_log.txt)

**Comment by fxcoudert** [comment]
Indeed GCC 8 does not support the syntax used by HDF5:

```
$ cat a.c

static void foo (void) __attribute__((noreturn))
{
  ;
}
$ gcc-8 a.c
a.c:2:1: error: attributes should be specified before the declarator in a function definition
 static void foo (void) __attribute__((noreturn))
 ^~~~~~
```

clang says so too, if you ask if for GCC compatibility warnings:

```
$ clang -Wgcc-compat a.c 
a.c:2:39: warning: GCC does not allow 'noreturn' attribute in this position on a function definition [-Wgcc-compat]
static void foo (void) __attribute__((noreturn))
                                      ^
```

This bug should be reported to the HDF5 project.
