### ISSUE TITLE
handbrake v1.1.0 installed via Homebrew crashes, but not the official binary installed from handbrake.fr

### ISSUE THREAD

**Issue by ddribin** [Homebrew/homebrew-core#28139]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Use HandBrakeCLI to convert an MKV to an MP4.

- What happened (include command output)

The HandBrakeCLI built via brew segfaults:

```
% /brew/bin/HandBrakeCLI --input=SampleVideo_1280x720_1mb.mkv --output=SampleVideo_1280x720_1mb.mp4
# ...
zsh: segmentation fault  /brew/bin/HandBrakeCLI --input=SampleVideo_1280x720_1mb.mkv 
```

`brew gits-logs`: https://gist.github.com/ddribin/dc06154004b9769ce93b43ad31b4beb3

- What you expected to happen

HandBrakeCLI should not crash.

- Step-by-step reproduction instructions (by running `brew install` commands)

Download a sample MKV file from https://sample-videos.com, for example [SampleVideo_1280x720_1mb.mkv](https://sample-videos.com/video/mkv/720/big_buck_bunny_720p_1mb.mkv)

```
# brew install handbrake
# HandBrakeCLI --input=SampleVideo_1280x720_1mb.mkv --output=SampleVideo_1280x720_1mb.mp4
```

Using the official HandbrakeCLI v1.1.0 binary [directly from handbrake.fr](https://handbrake.fr/rotation.php?file=HandBrakeCLI-1.1.0.dmg) does not crash.

**Comment by vinyldarkscratch** [comment]
Decided to try this out on my own computer, and couldn't reproduce the issue.  [More details included on the other repository's issue!](https://github.com/donmelton/video_transcoding/issues/209#issuecomment-391223412)

**Comment by ilovezfs** [comment]
@vinyldarkscratch I assume you were testing with bottle. I cannot reproduce the problem with the bottle. The segfault is reproducible with a fresh source build, though.

**Comment by vinyldarkscratch** [comment]
@ilovezfs Your assumption is accurate -- I've learned my lesson and almost never build from source after the [hassle it created for OneShot macOS](https://github.com/GooborgStudios/synglechance/issues/20).  😛

I just tried building from source myself.  During `Encoding: task 1 of 1`, I got a segfault, just like the described issue.

**Comment by fxcoudert** [comment]
Seems like to `-march=native` optimisation…

**Comment by ilovezfs** [comment]
yup

**Comment by ilovezfs** [comment]
Reported upstream https://github.com/HandBrake/HandBrake/issues/1351

**Comment by ilovezfs** [comment]
There's a workaround in the formula now @ddribin. So if you `brew reinstall handbrake` the problem should go away.

**Comment by ddribin** [comment]
@ilovezfs Thanks much! I can confirm it works fine now, after reinstalling.
