### ISSUE TITLE
guile is dependent on bdw-gc 7.6.4 which no longer exists (MacOS 10.13.4)

### ISSUE THREAD

**Issue by omgitsraven** [Homebrew/homebrew-core#28161]
In short: guile depends on bdw-gc, but the latest version of guile seems to be hard-coded to look for bdw-gc 7.6.4, which is no longer available on homebrew (the only version offered is 7.6.6).

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **(no logs)**
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
**brew config:** https://gist.github.com/omgitsraven/6f0a189d39adc65792e5a1892015fd03
**brew doctor:** https://gist.github.com/omgitsraven/678f2380b8efd69a597f6e5a0dc9fe55

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to compile [libfive](https://github.com/libfive/libfive), which depends on guile.
- What happened (include command output)
https://gist.github.com/omgitsraven/eaf2235e0fcdd4197ee93ab81651adb3
- What you expected to happen
It normally reaches 100% and builds successfully.
- Step-by-step reproduction instructions (by running `brew install` commands)

1. Install the dependencies for libfive, i.e. `brew install cmake pkg-config eigen libpng qt guile boost`, and **update** them if possible
2. `brew cleanup` (to make sure that bdw-gc 7.6.4 is no longer around if it was, which I think causes the bug)
3. Follow the rest of the instructions to build libfive, i.e.
```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.11.0  ..
make
```
with the cmake line changed to whatever verison of qt you have installed (5.11.0 as of writing)

You can work around the problem and build successfully by editing the two instances of `7.6.4` in `/usr/local/lib/pkgconfig/guile-2.2.pc` to say `7.6.6`, so this seems to be the only problem.

**Comment by ilovezfs** [comment]
@omgitsraven This should be fixed, thanks to @DomT4, if you `brew reinstall guile`
