### ISSUE TITLE
Which version of Jupyter Notebook?

### ISSUE THREAD

**Issue by lsloan** [Homebrew/homebrew-core#28196]
The [Homebrew formula page for Jupyter Notebook](https://formulae.brew.sh/formula/jupyter) states that it installs Jupyter 1.0.0.  That's a very old version when compared to version 5.2.3, which is what's available via the Jupyter website.  If that formula truly installing Jupyter 1.0.0, or is there something else going on?

**Comment by fxcoudert** [comment]
PyPI says [Jupyter 1.0.0](https://pypi.org/project/jupyter/) is the latest version, though

**Comment by vinyldarkscratch** [comment]
Looks like [Jupyter](https://jupyter.org/) is divided into multiple packages through `pip`.  Even though the primary `jupyter` package is _1.0.0,_ there's a [`jupyter-client`](https://pypi.org/project/jupyter_client/) and [`jupyter-console`](https://pypi.org/project/jupyter_console/) package, which report they are versions 5.2.3 and 5.2.0.  So, the version number may not be reporting right on the Brew formula, but rest assured it's installing 5.2.3.  :wink:

**Comment by lsloan** [comment]
I suggest that the version of the "jupyter" formula be changed from "1.0.0" to the same version as the Jupyter package that does most of the work.  For example, if I install Jupyter Notebook as part of Anaconda Navigator, I'm told that the version I have is 5.4.0.  Homebrew's "jupyter" formula should say the same.

**Comment by fxcoudert** [comment]
I am not sure what versioning system makes most sense… clearly there are a lot of version numbers involved, not sure which one anaconda considers

**Comment by vinyldarkscratch** [comment]
@fxcoudert I’d say that the versioning of jupyter-client is the better one to use if possible.  From what it looks like, that’s the real version number, just to add confusion to the mix.  XD

**Comment by lsloan** [comment]
Thanks, @stale.  (Since you're a bot, I should tell you, that's sarcasm.)
