### ISSUE TITLE
macOS Sierra Issues with llvm37

### ISSUE THREAD

**Issue by EtherTyper** [Homebrew/homebrew-core#2826]
### Bug reports:

Installing llvm37, I get the following error compiling its libc++ standard C implementation:

	../include/string:1938:44: error: 'basic_string<_CharT, _Traits, _Allocator>' is missing exception specification 'noexcept(is_nothrow_copy_constructible<allocator_type>::value)'
	basic_string<_CharT, _Traits, _Allocator>::basic_string(const allocator_type& __a)
                                       ^
	../include/string:1326:40: note: previous declaration is here
	_LIBCPP_INLINE_VISIBILITY explicit basic_string(const allocator_type& __a)

https://gist.github.com/EtherTyper/f2a9cb636622bb90e2f21cc8abcb94d5

**Comment by leepa** [comment]
Hey,

Unfortunately this is not a bug in Homebrew Core as macOS Sierra isn't currently supported. See https://gist.github.com/EtherTyper/f2a9cb636622bb90e2f21cc8abcb94d5#file-00-doctor-out-L0-L163 where is raises that you should do PRs not Issues for things on this version of macOS. Incidentally there's a load of other warnings in your brew doctor that might want looking at.

The error you're seeing there might be related to bad includes around but more likely an upstream issue with LLVM 3.7 on this version of the OS.

**Comment by EtherTyper** [comment]
Yes, I have system/external installations of Node and Python as it points
out. I'll try to fix the exception handling and send a PR, (somehow,) to
LLVM. Sorry for wasting your time, but thanks for pointing me in the right
direction!
