### ISSUE TITLE
Python: does not create symlink to pip

### ISSUE THREAD

**Issue by KiYugadgeter** [Homebrew/homebrew-core#28335]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Homebrew Does not create symlink to pip3 when I install python.
When I installed python3 a few month ago, homebrew create `pip3` symlink on /usr/local/bin.
so I can use pip immediately.
But now It does not create symlink to pip3 that toward pip command.

https://gist.github.com/c4e17e9b540f5aaf6947a76571811d47

**Comment by ilovezfs** [comment]
Please see https://github.com/Homebrew/brew/blob/master/docs/Homebrew-and-Python.md#python-3x-or-python-2x for details of what's installed.
