### ISSUE TITLE
bento4 formula does not include various commands

### ISSUE THREAD

**Issue by nabeards** [Homebrew/homebrew-core#28389]
- [√] are reporting a bug others will be able to reproduce and not asking a question
- [√] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? - [√] ran `brew update` and can still reproduce the problem?
- [√] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [√] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`Error: No logs.`

- [√] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
config:
```
HOMEBREW_VERSION: 1.6.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: e4c02fafdaef5676cf40dd6d16e74976cf54b265
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc221d2aef779ef99834bccc493c3647efe8fa73
Core tap last commit: 12 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.3-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: N/A
XQuartz: N/A
```

doctor:
```
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Install bento4 and get access to its included commands.

- What happened (include command output)
The following commands are missing from the brew package:
```
mp4dash
mp4dashclone
mp4hls
mp4iframeindex
mp42avc
```
- What you expected to happen
Get these commands installed.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install bento4`
`ls -la /usr/local/Cellar/bento4/1.5.1-624/bin/`
-> See that the above mentioned commands are not there.

**Comment by nabeards** [comment]
Additional info: these are commands that point to python scrips in a `utils/` directory at the same level as `bin/`.

**Comment by ilovezfs** [comment]
The formula runs
```
  def install
    cd "Build/Targets/any-gnu-gcc" do
      system "make", "AP4_BUILD_CONFIG=Release"
      bin.install Dir["Release/*"].select { |f| File.executable?(f) }
    end
  end
```
So if those commands aren't there, presumably they were removed upstream. If I run

`xcodebuild -target All -configuration Release` in `Build/Targets/universal-apple-macosx`

Then I see
```
bash-3.2$ ls -l build/Release/{mp4dash,mp4dashclone,mp4hls,mp4iframeindex,mp42avc}
ls: build/Release/mp4dash: No such file or directory
ls: build/Release/mp4dashclone: No such file or directory
ls: build/Release/mp4hls: No such file or directory
-rwxr-xr-x  1 joe  admin  1093680 May 28 09:18 build/Release/mp42avc
-rwxr-xr-x  1 joe  admin  1125760 May 28 09:18 build/Release/mp4iframeindex
```
So we might be able to resurrect those two but I'm not sure what happened to the others.

**Comment by ilovezfs** [comment]
OK I see those are in Source/Python. We really need a `make install` target so this doesn't happen again.

**Comment by nabeards** [comment]
Is there anything else I should provide to help move this issue forward?

**Comment by ilovezfs** [comment]
@nabeards this is now fixed if you `brew upgrade`

**Comment by nabeards** [comment]
@ilovezfs thank you!

**Comment by ilovezfs** [comment]
@nabeards You're welcome!
