### ISSUE TITLE
freerdp failed to build on OSX10.13.4 with --HEAD

### ISSUE THREAD

**Issue by ramasdf** [Homebrew/homebrew-core#28469]
- [ ] I am reporting a bug I see with installing a HEAD version of freerdp using revision "2a6c9e1b8742306097c9940ba3f7d3b18efbcfb7".  I am able to install the stable ver. freerdp-1.0.2_1. 

- [ ] ran `brew update` and can still reproduce the problem? yes, also did `brew cleanup and prune` before update and docter.  
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? yes
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Output to link with 
https://gist.github.com/ramasdf/480bc0d25e29a6fd859642f086dafd21#file-02-make-L1082

To help us debug your issue please explain:
- What you were trying to do (and why).
I am trying to install a newer version of freerdp on Mac OSX 10.13.4, it seems to be failing on the HEAD version, but work on the older/stable ver 1.0.2. Our support script need the newer version of freerdp. 
- What happened (include command output)
I update freerdp with "2a6c9e1b8742306097c9940ba3f7d3b18efbcfb7" from https://github.com/Homebrew/homebrew-core/issues/24047
- What you expected to happen
Properly install freerdp with ver. 2 
- Step-by-step reproduction instructions (by running `brew install` commands)
brew prune
brew cleanup
brew doctor
brew install freerdp --HEAD

**Comment by apjanke** [comment]
Works for me on 10.13.

BUT:

This breakage is normal and expected. When you install something with `--HEAD`, you're asking for the latest, possibly unstable, head of their development repo. So it might be broken at any time.

This is not a problem with the `homebrew-core` `freerdp` formula. It's probably a problem with FreeRdp's current `master`  Please report this as a bug to freerdp.

> Our support script need the newer version of freerdp.

If you're using this in production or redistributing it, you should probably avoid depending on the HEAD version. Instead use their tagged releases, or make a fork and tag your own known-working versions.

**Comment by ramasdf** [comment]
Thanks for the review.
