### ISSUE TITLE
ruby issue (hot/recent) when brew doctor

### ISSUE THREAD

**Issue by dmarinescu** [Homebrew/homebrew-core#28571]
just started to happen few minutes ago, after the latest brew update
brew doctor:

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Ruby version 2.3.7 is unsupported on 10.13. Homebrew
is developed and tested on Ruby 2.3.3, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
Error: no implicit conversion of nil into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `extname'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:363:in `loader_for'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/dependency.rb:33:in `to_formula'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1564:in `missing_dependencies'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:13:in `block in missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:12:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:12:in `missing_deps'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:46:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:38:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

**Comment by dmarinescu** [comment]
of course, running 10.13.6 Beta (17G31f)

**Comment by jmpridgen** [comment]
I am currently getting the same issue

**Comment by JCount** [comment]
Check and see if https://github.com/Homebrew/brew/pull/4263 fixed this for you. It may have, though the warning about the unsupported Ruby version will remain.

**Comment by DomT4** [comment]
I assume `portable-ruby` is going to need an update @MikeMcQuaid, if the intention is to keep tracking the latest release of macOS on Ruby versions? 10.13.6 does indeed ship `ruby 2.3.7p456`.

**Comment by ilovezfs** [comment]
This is fixed if you `brew update`

**Comment by dmarinescu** [comment]
yep, thanks for closing

**Comment by ilovezfs** [comment]
No problem. Thanks for the report @dmarinescu
