### ISSUE TITLE
Qt 5 keg_only

### ISSUE THREAD

**Issue by jakepetroules** [Homebrew/homebrew-core#2860]
The "Qt 5 conflicts Qt 4 (which is currently much more widely used)." message has been around forever, and Qt 5 has been around for almost 5 years now, and just launched its *8th* release.

Qt 4.x is obsolete, and we will never be updating it again. The "much more widely used" is debatable.

It's time to get rid of this message, as it's helping scare off users from Qt 5. This is obviously not good for our ecosystem.

**Comment by UniqMartin** [comment]
You might be interested in #1705, if you haven't seen that yet. I agree with most of your points.

> The "much more widely used" is debatable.

That claim is probably still true for the Qt-using formulae in Homebrew, though we certainly would like to change this and we're probably not going to drag Qt 4 along for macOS 10.12. But as usual, we severely lack manpower to tackle this with more firmness, thus all help is more than welcome.

**Comment by jakepetroules** [comment]
I just pushed 4 pull requests to update some formula to Qt 5, so there's a few more checked off the list.

**Comment by ilovezfs** [comment]
@jakepetroules you're awesome. Thank you!
