### ISSUE TITLE
install ffmpeg macOS High Sierra 10.13.4

### ISSUE THREAD

**Issue by Twwwwizz** [Homebrew/homebrew-core#28613]
I get this warning for $ brew reinstall ffmpeg
Warning: ffmpeg dependency libmodplug was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.

When I try to run ffmpeg I get

$ ffmpeg
dyld: Library not loaded: /usr/local/opt/rubberband/lib/librubberband.2.dylib
Referenced from: /usr/local/bin/ffmpeg
Reason: image not found
Abort trap: 6

How do I install ffmpeg? 

I have made a copy of librubberband.dylib, and renamed to librubberband.2.dylib, and it works - but I don't think that's the best way to go!

**Comment by ilovezfs** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by Twwwwizz** [comment]
Sorry but I'm new here. What is the issue checklist? How do I fill it out, and with what information?

**Comment by SMillerDev** [comment]
If you click new issue, you can pick reproducable bug report. That will provide you with a template for a reproducable bug report.
