### ISSUE TITLE
httpd not serving php files

### ISSUE THREAD

**Issue by 0dp** [Homebrew/homebrew-core#28642]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to reinstall httpd and php because I need php7.2
- What happened (include command output)
`brew install httpd php72`
```
➜  ~ brew reinstall httpd php
==> Reinstalling httpd
==> Downloading https://homebrew.bintray.com/bottles/httpd-2.4.33.high_sierra.bottle.tar.gz
Already downloaded: /Users/odp/Library/Caches/Homebrew/httpd-2.4.33.high_sierra.bottle.tar.gz
==> Pouring httpd-2.4.33.high_sierra.bottle.tar.gz
==> Caveats
DocumentRoot is /usr/local/var/www.

The default ports have been set in /usr/local/etc/httpd/httpd.conf to 8080 and in
/usr/local/etc/httpd/extra/httpd-ssl.conf to 8443 so that httpd can run without sudo.

To have launchd start httpd now and restart at login:
  brew services start httpd
Or, if you don't want/need a background service you can just run:
  apachectl start
==> Summary
🍺  /usr/local/Cellar/httpd/2.4.33: 1,633 files, 26.4MB
==> Reinstalling php
==> Downloading https://homebrew.bintray.com/bottles/php-7.2.6.high_sierra.bottle.tar.gz
Already downloaded: /Users/odp/Library/Caches/Homebrew/php-7.2.6.high_sierra.bottle.tar.gz
==> Pouring php-7.2.6.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set php_ini /usr/local/etc/php/7.2/php.ini system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set php_dir /usr/local/share/pear system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set doc_dir /usr/local/share/pear/doc system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set ext_dir /usr/local/lib/php/pecl/20170718 system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set bin_dir /usr/local/opt/php/bin system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set data_dir /usr/local/share/pear/data system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set cfg_dir /usr/local/share/pear/cfg system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set www_dir /usr/local/share/pear/htdocs system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set man_dir /usr/local/share/man system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set test_dir /usr/local/share/pear/test system
==> /usr/local/Cellar/php/7.2.6/bin/pear config-set php_bin /usr/local/opt/php/bin/php system
==> /usr/local/Cellar/php/7.2.6/bin/pear update-channels
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/7.2/

To have launchd start php now and restart at login:
  brew services start php
Or, if you don't want/need a background service you can just run:
  php-fpm
==> Summary
🍺  /usr/local/Cellar/php/7.2.6: 515 files, 79.1MB
```
- What you expected to happen
After resolving caveats I expect php files to be served by httpd in the bowser.
But php files are not served correctly.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew reinstall httpd php`
add `LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so` to /usr/local/etc/httpd/httpd.conf - modules section.

also add
```
    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>
```

finally add index.php to DirectoryIndex

httpd runs fine and php -v reports
```
PHP 7.2.6 (cli) (built: May 25 2018 06:18:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.6, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by SMillerDev** [comment]
This isn't really a homebrew issue but more of a httpd config issue. 
That being said, do you have an index.php file in `/usr/local/var/www` for httpd to serve?

**Comment by 0dp** [comment]
yes, i've creates a info.php file with `<?php phpinfo(); ?>`

**Comment by SMillerDev** [comment]
and is there anything in the apache log about this?

**Comment by 0dp** [comment]
Not at all, all I can see is httpd is being started and stopped by me
