### ISSUE TITLE
makedepend pkg-config dependency issue in 10.4

### ISSUE THREAD

**Issue by jonathansimmons** [Homebrew/homebrew-core#28675]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  - https://gist.github.com/28b8f69e2496b058db7fa3e7dabce84c

**To help us debug your issue please explain:**
- **What you were trying to do (and why)**
Whenever a new OS is released I take a blank dev and work to rebuild our env from scratch to look for annoying potential errors. The issue arose while trying to install rbenv via homebrew but it seems to be with makedepend, hence my reporting it here.
- **What happened (include command output)**
While trying to install `rbenv` the `makedepend` dependency fails to install giving the following error: 

```bash
jonathansimmons@Jonathans-MacBook-Pro ~ brew install rbenv
==> Installing dependencies for rbenv: makedepend, openssl, ruby-build
==> Installing rbenv dependency: makedepend
==> Downloading https://xorg.freedesktop.org/releases/individual/util/makedepend-1.0.5.tar.bz2
Already downloaded: /Users/jonathansimmons/Library/Caches/Homebrew/makedepend-1.0.5.tar.bz2
==> Downloading https://xorg.freedesktop.org/releases/individual/proto/xproto-7.0.28.tar.gz
Already downloaded: /Users/jonathansimmons/Library/Caches/Homebrew/makedepend--xproto-7.0.28.tar.gz
==> ./configure --disable-silent-rules --prefix=/private/tmp/makedepend-20180605-32672-vpsn3r/makedepend-1.0.5/xproto
==> make install
==> Downloading https://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.0.tar.bz2
Already downloaded: /Users/jonathansimmons/Library/Caches/Homebrew/makedepend--xorg-macros-1.19.0.tar.bz2
==> ./configure --prefix=/private/tmp/makedepend-20180605-32672-vpsn3r/makedepend-1.0.5/xorg-macros
==> make install
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/makedepend/1.0.5
Last 15 lines from /Users/jonathansimmons/Library/Logs/Homebrew/makedepend/05.configure:
checking for rename... yes
checking for fchmod... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for X... configure: error: in `/private/tmp/makedepend-20180605-32672-vpsn3r/makedepend-1.0.5':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables X_CFLAGS
and X_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Error: You are using macOS 10.14.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
```
- **What you expected to happen**
Successful `rbenv` install

- **Step-by-step reproduction instructions (by running `brew install` commands)**
  - Fresh macOS 10.4 install
  - Install homebrew `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
  - install makedepend `brew install makedepend. (for my exact initial use you would install rbenv `brew install rbenv`)

- Misc attempts to fix
  - reinstall pkg-config `brew reinstall pkg-config`
  - install pkg-config from source
  - Specify the `PKG_CONFIG_PATH` env variable like so `brew install rbenv --PKG_CONFIG_PATH=/usr/local/bin/pkg-config`

**Comment by jakecast** [comment]
I hit this same issue, I found it to be a problem with pkg-config not having execute permissions and therefore not be working when building the xorg-macros. I found the fix for the problem to be
`chmod 555 /usr/local/Cellar/pkg-config/0.29.2/bin/pkg-config`

**Comment by jakecast** [comment]
just an update to this. this is actually an issue with the executable_path function in the brew proper repo. many packages will get the incorrect permissions in 10.14
[https://github.com/Homebrew/brew/blob/22e9fd772926e389e264cfb328c3d810b06759f9/Library/Homebrew/extend/os/mac/cleaner.rb#L7](https://github.com/Homebrew/brew/blob/22e9fd772926e389e264cfb328c3d810b06759f9/Library/Homebrew/extend/os/mac/cleaner.rb#L7)

i temp fixed it by changing
`path.mach_o_executable? || path.text_executable?`
to
`path.mach_o_executable? || path.text_executable? || path.executable?`

it's temporary workaround until the mach_o_executable check can be updated for 10.14

**Comment by jonathansimmons** [comment]
I can confirm the permissions adjustment worked for me as well. 

Glad to see this wasn’t a useless report. 

Jonathan Simmons

**Comment by DomT4** [comment]
@woodruffw This might be one that interests you.

**Comment by woodruffw** [comment]
Thanks @DomT4!

Can you send me the offending `pkg-config` binary, @jakecast? `mach_o_executable?` just checks to see if the Mach-O binary contains an executable slice (rather than a shared object/coredump/whatever), so maybe Apple has messed with the constants involved in that check.

**Comment by jakecast** [comment]
@woodruffw i can a bit later, I'm guessing that apple has changed the response of that the mach_data check in [https://github.com/Homebrew/brew/blob/22e9fd772926e389e264cfb328c3d810b06759f9/Library/Homebrew/os/mac/mach.rb#L102](mach_o_executable)

`mach_o_executable` fails to return true on a wide variety of binary files in 10.14
the exec files of bash, ruby, git all fail to return true for `mach_o_executable`. I might be able to take a look at the results of the `mach_data` check tonight.. I'm curious to know what is causing it to fail

**Comment by woodruffw** [comment]
> mach_o_executable fails to return true on a wide variety of binary files in 10.14
> the exec files of bash, ruby, git all fail to return true for mach_o_executable

Yeah, that's definitely not good. Does the `file` utility provide any insight?

**Comment by mistydemeo** [comment]
This has been fixed in https://github.com/Homebrew/ruby-macho/pull/90; tonight we'll be cutting a new ruby-macho release and updating the vendored copy.

**Comment by woodruffw** [comment]
Ah, I didn't put two and two together. I guess we're masking the exception that gets raised on an unknown load command. 

I'll cut the release when I get home, in a bit.

On June 5, 2018 9:31:03 PM EDT, Misty De Meo <notifications@github.com> wrote:
>This has been fixed in https://github.com/Homebrew/ruby-macho/pull/90;
>tonight we'll be cutting a new ruby-macho release and updating the
>vendored copy.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Homebrew/homebrew-core/issues/28675#issuecomment-394911140

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mistydemeo** [comment]
> I guess we're masking the exception that gets raised on an unknown load command.

Yup, that's exactly what happens. We end up treating Mach-O files with unrecognized load commands as not being Mach-O binaries due to the exception handling.

**Comment by woodruffw** [comment]
Just pushed the revendor PR.

I'll take a look into making the exception handling behavior better as well.

**Comment by woodruffw** [comment]
Closing now that https://github.com/Homebrew/brew/pull/4285 is merged.

**Comment by stephencelis** [comment]
I encountered this with a fresh Homebrew installation (in the last hour). Could this still be an issue?

**Comment by woodruffw** [comment]
I don't believe we've published a new version yet, so you probably haven't received the changes. You should be able to test them out by switching to `master` and pulling, though.


On June 7, 2018 9:44:18 AM EDT, Stephen Celis <notifications@github.com> wrote:
>I encountered this with a fresh Homebrew installation (in the last
>hour). Could this still be an issue?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Homebrew/homebrew-core/issues/28675#issuecomment-395425133

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gaoshanyu** [comment]
@woodruffw Do you have a pre-release version for macOS 10.14-Beta? I just want homebrew work well on my MacBook.
