### ISSUE TITLE
cryptopp failed to build on 10.11.4 installing ethereum

### ISSUE THREAD

**Issue by c-hamilton** [Homebrew/homebrew-core#2873]
similar issue to : https://github.com/Homebrew/homebrew-core/issues/2783 

**Error installing cryptopp while running "brew install cpp-ethereum"**

--> ran brew doctor, brew prune, and brew link cmake
--> ran "brew gist-logs cpp-ethereum"
         OUPUT: Error: No logs.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  

Output during install: 
==> make shared all CXX=clang++
  ==> ./cryptest.exe v
Last 15 lines from / . . . /Homebrew/cryptopp/02.cryptest.exe:
[. . .] 
Testing RDSEED generator...
CryptoPP::Exception caught: RDSEED: GCC_RSA_GenerateBlock operation failed

**Hope this helps**

**Comment by tdsmith** [comment]
This is a duplicate of the cryptopp issue. Thanks!
