### ISSUE TITLE
Formulae with URL issues

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#28761]
- [ ] [aws-cloudsearch](https://github.com/Homebrew/homebrew-core/blob/master/Formula/aws-cloudsearch.rb):
```
iMac-TMP:~ joe$ brew fetch aws-cloudsearch
==> Downloading https://s3.amazonaws.com/amazon-cloudsearch-data/cloud-search-tools-v2-2.0.1.0-2014.1

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "aws-cloudsearch"
Download failed: https://s3.amazonaws.com/amazon-cloudsearch-data/cloud-search-tools-v2-2.0.1.0-2014.10.27.tar.gz
```
- [ ] [ballerina](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ballerina.rb): stable url redirects to the homepage
- [ ] [git-credential-manager](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-credential-manager.rb): homepage https://java.visualstudio.com/Docs/tools/gitcredentialmanager is 404
- [ ] [graphviz](https://github.com/Homebrew/homebrew-core/blob/master/Formula/graphviz.rb): homepage https://graphviz.org/ certificate issue (seems to want www. prepended)
- [ ] [infer](https://github.com/Homebrew/homebrew-core/blob/master/Formula/infer.rb): homepage https://fbinfer.com/ certificate outdated

**Comment by oswalpalash** [comment]
Working on this one.

**Comment by ilovezfs** [comment]
@oswalpalash awesome! Thank you :)
