### ISSUE TITLE
Java 10.x build failures

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#28760]
This will serve as a tracking issue for Java related CI failures identified following the Java 9.x to Java 10.x upgrade:

- [ ] asciidoctorj https://gist.github.com/ilovezfs/634ed60280c8cee718603a124f3a50d7
- [ ] blazegraph https://gist.github.com/ilovezfs/14147fc2f4c7184210d070faa71ec7e8
- [x] ceylon https://gist.github.com/ilovezfs/374a43be79cee45bc35a8de4acf02078 https://github.com/Homebrew/homebrew-core/pull/28775
- [x] libreadline-java https://gist.github.com/ilovezfs/11050f8ab084caac092c4dcc065ce93a https://github.com/Homebrew/homebrew-core/pull/28776
- [x] sbt@0.13 https://gist.github.com/ilovezfs/ea495de01783ebe32b28697c15c2502d https://github.com/Homebrew/homebrew-core/pull/28777
- [ ] sqoop https://gist.github.com/ilovezfs/42eb68ded89dc0f12879550c715354cd

CC @apjanke

**Comment by apjanke** [comment]
* asciidoctorj - fixed upstream - https://github.com/asciidoctor/asciidoctorj/pull/644 - just have to wait for new v1.6.0, currently in alpha
* blazegraph - I don't think this is Java 10 related. It also breaks for me with a NullPointerException under Java 7, 8, and 9.
* ceylon - pin to Java 8 #28775
* libreadline-java - pin to Java 8 for compilation #28776
* sbt@0.13 - pin to Java 8 #28777
* sqoop - looks unrelated to Java 10

The sqoop failure looks like it's looking for a hadoop config file in a location not supported by Homebrew 0 note that it's pointing to `$HOMEBREW_PREFIX/libexec`, not `cellar/libexec`. Perhaps it effectively requires one of its dependencies to run something?

```
$ echo $JAVA_HOME                                                                                                                           sqoop-java-8 ✱
/Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home
[/u/l/H/L/T/h/h/Formula]
$ /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/sqoop version                                                                                 sqoop-java-8 ✱
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../hcatalog does not exist! HCatalog jobs will fail.
Please set $HCAT_HOME to the root of your HCatalog installation.
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../accumulo does not exist! Accumulo imports will fail.
Please set $ACCUMULO_HOME to the root of your Accumulo installation.
Warning: /usr/local/Cellar/sqoop/1.4.6_1/libexec/bin/../../zookeeper does not exist! Accumulo imports will fail.
Please set $ZOOKEEPER_HOME to the root of your Zookeeper installation.
ERROR: Cannot execute /usr/local/libexec/hadoop-config.sh.
```

**Comment by apjanke** [comment]
Upstream bug report: https://github.com/asciidoctor/asciidoctorj/issues/662

I'll see about just working around this error in the `test do` code.

**Comment by apjanke** [comment]
Added a workaround to the test code by qualifying `"test.adoc"` as `testpath/"test.adoc"`. (Eww.)

```

    # Absolute path to input file is required to work around upstream bug
    # https://github.com/asciidoctor/asciidoctorj/issues/662
    system bin/"asciidoctorj", "-b", "pdf", testpath/"test.adoc"
```

**Comment by apjanke** [comment]
Upstream bug report for blazegraph: https://jira.blazegraph.com/browse/BLZG-9149

**Comment by MikeMcQuaid** [comment]
Closing as @ilovezfs isn't around to maintain the list any more.
