### ISSUE TITLE
undefined method `sha1' for #<Class:0x007f95a520c348>

### ISSUE THREAD

**Issue by yqllyq** [Homebrew/homebrew-core#28769]
when is was using 
`brew install boost`
 to install boost, i get an error :
`
Error: undefined method `sha1' for #<Class:0x007f95a520c348>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:4:in `<class:Boost>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/boost.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:281:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:461:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:48:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:44:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:44:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:118:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'`

i using `brew update` can not solver it..

**Comment by fxcoudert** [comment]
It appears you are using a very old version of Homebrew. Can you run `brew up`, then paste here the output of `brew config` and `brew doctor`?

**Comment by TrentBrown** [comment]
Having the same trouble.

This is output of "brew config"
```
➜  ~ brew config
HOMEBREW_VERSION: 1.6.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 3081390ff845a6172b9004cf404c3e028e3be745
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0ebeefd949b12749e016161554173522038c98d7
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.12.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_40, 1.7.0_75
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by fxcoudert** [comment]
The error is in the tap `larsimmisch/homebrew-avr` (https://github.com/larsimmisch/homebrew-avr). You need to remove that tap, which is using very old (and outdated) code.

**Comment by KKKKKyle** [comment]
@fxcoudert Could you be more specific about how to remove that tap? I have the same issue and I'm pretty new to homebrew.
