### ISSUE TITLE
Warning: You are using OS X 10.12.

### ISSUE THREAD

**Issue by lincolnge** [Homebrew/homebrew-core#2879]
READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by tdsmith** [comment]
This is the design behavior; thanks!
