### ISSUE TITLE
openssl not installing cert.pem in macOS 10.14

### ISSUE THREAD

**Issue by jonathansimmons** [Homebrew/homebrew-core#28806]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/jonathansimmons/89727bbac13c44b042a3d9120a1e2a1e

To help us debug your issue please explain:
- **What you were trying to do (and why)**
Me again gents, running macOS 10.14 use a gem that required open ssl, for the sake of this issue i'm going to ignore that gem and just use a simple test for open ssl: 
`ruby -rnet/https -e "Net::HTTP.get URI('https://github.com')"`
- **What happened (include command output)**
`openssl::ssl::sslerror: ssl_connect returned=1 errno=0 state=sslv3 read server certificate b: certificate verify failed`
- **What you expected to happen**
A passing ssl connection.
- **Step-by-step reproduction instructions (by running `brew install` commands)**
```
brew update
brew install openssl
```
The openssl install completes but the `ruby -rnet/https -e "Net::HTTP.get URI('https://github.com')"` is still failing. 

**How I fixed it:** 
Further investigation revealed that while the homebrew openssl install was completing it was not actually putting the cert.pem in `/usr/local/etc/openssl`. I stumbled through the internets and found https://github.com/rbenv/ruby-build/issues/380#issuecomment-20550731 and used the initial post to create the pem file and the defined `find_certificate` method to put the cert.pem in place. Then everything started working. 

I wanted to report this here to see if this is actual a problem with how the openssl formula is functioning in macOS 10.14.

**Comment by mistydemeo** [comment]
Hi @jonathansimmons! A gentle reminder, not every one of the maintainers is a "gent" - it never hurts to be inclusive when addressing people. :)

As you might be aware, Homebrew doesn't support OS X 10.4. However, I maintain a fork called [Tigerbrew](https://github.com/mistydemeo/tigerbrew/) that does support Macs on 10.4 - both Intel and PowerPC. There are some packaging differences in Tigerbrew to account for things like this.

**Comment by jonathansimmons** [comment]
Hey @mistydemeo, 
Good reminder, and sorry for the exclusion. We have a mix of devs on our team and you're right, this was bad taste. 

First, yes I was referring to macOS 10.14. 10.4 is just so easy to type. Plus, it was early and I'd not had my coffee yet. 

Allow me to be confused though as to why this would be closed. I'm not asking for immediate support but rather trying to help identify an issue. I'd submit a PR but that is beyond my skillset at the moment. So I thought I'd report it here.

**Comment by mistydemeo** [comment]
I closed it because I thought we were talking about OS X 10.4, which Homebrew doesn't support at all. I can reopen this now that I know we're talking about 10.14!

**Comment by ilovezfs** [comment]
did you also `brew install ruby`?

**Comment by jonathansimmons** [comment]
No, as I’ve never used brew to install ruby. I manage it with rbenv.
