### ISSUE TITLE
swi-prolog --devel fails to build on macOS 10.13.5

### ISSUE THREAD

**Issue by bakirtzisg** [Homebrew/homebrew-core#28809]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install a version of swi-prolog >7.7, but the compilation fails. 

- What happened (include command output)
`==> Downloading http://www.swi-prolog.org/download/devel/src/swipl-7.7.15.tar.gz
Already downloaded: /Users/bakirtzisg/Library/Caches/Homebrew/swi-prolog-7.7.15.tar.gz
==> ./configure --prefix=/usr/local/Cellar/swi-prolog/7.7.15/libexec --mandir=/u
==> make
Last 15 lines from /Users/bakirtzisg/Library/Logs/Homebrew/swi-prolog/02.make:
      _zipOpenNewFileInZip4_64 in zip.o
  "_inflate", referenced from:
      _unzReadCurrentFile in unzip.o
  "_inflateEnd", referenced from:
      _unzCloseCurrentFile in unzip.o
  "_inflateInit2_", referenced from:
      _unzOpenCurrentFile3 in unzip.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../lib/x86_64-darwin17.6.0/libswipl.dylib] Error 1
make[1]: *** Waiting for unfinished jobs....
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/x86_64-darwin17.6.0/libswipl.a(pl-beos.o) has no symbols
ranlib ../lib/x86_64-darwin17.6.0/libswipl.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/x86_64-darwin17.6.0/libswipl.a(pl-beos.o) has no symbols
make: *** [lite] Error 2`

- What you expected to happen
Compiles.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install swi-prolog --devel
https://gist.github.com/bakirtzisg/179d6a8c24c9639981480fc0e096d731

**Comment by JCount** [comment]
I cannot reproduce this, so it very likely is an issue specific to your system. Your `brew doctor` output shows that you have an old version of `zlib`, (version 1.2.6 released 29 Jan 2012), that `swi-prolog` is likely trying to build against, rather than the system default of version 1.2.11.
```
  /usr/local/lib/libz.1.2.6.dylib
  /usr/local/lib/libz.1.dylib
  /usr/local/lib/libz.dylib
```
I suggest (re)moving that `zlib` install if possible, because at least versions <= 1.2.5 are known to cause issues with the `devel` version.

Also, another thing to note, if you didn't realize it, is that you are actually running the equivalent of `brew swi-prolog --with-jpl --with-libarchive --with-xpce --devel` because the option flags are sticky.

**Comment by bakirtzisg** [comment]
Removing the `zlib` libraries listed and `brew install zlib` seems to have fixed the issue.

Thank you for the prompt reply.
