### ISSUE TITLE
R 3.5.0 is missing tcltk, jpg, png and tiff support

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-core#28926]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I updated R from 3.4.2 to 3.5.0_1 to get the latest version

- What happened (include command output)

It installed fine. Afterwards I noticed that support for all image output formats (jpg, png, tiff) as well as for tcl/tk is disabled in this build. This prevents graph generation and output, as well as installation of many (if not the majority) of R libraries (from CRAN as well as other sources) which require TCL/TK and don't allow to disable it.

- What you expected to happen

These formats as well as TCL/TK was available in previous versions. R still supports theme, so support should not be dropped by (minor) upgrade - hopefully never without a deprecation period, as this makes the R binary pretty much useless.

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew upgrade R

# wait a bit
# watch your production environment / productivity go up in flames. :)
# investigate why
$ R -e 'capabilities()'                                                                                                       :(
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE       FALSE       FALSE        TRUE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE       FALSE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 

```

This first line of that output is what shows the problem:

```
       jpeg         png        tiff       tcltk         X11        aqua 
      FALSE       FALSE       FALSE       FALSE       FALSE        TRUE 
```

Neither jpg, png, tiff nor tcltk are supported in this version.

**Comment by dwt** [comment]
I also noticed that this is discussed on the [forum with mixed success for workarounds](https://discourse.brew.sh/t/r-installs-on-high-sierra-without-tcl-tk-support/1190/15). As far as I can determine, the result seems to be that instead of linking against tcltk from the system, it would have to depend on a home-brew shipped version of tclkt, and probably also on xquartz.

There seems to be a guy here who tried to work around this by [reactivating system tcltk support](https://github.com/sethrfore/homebrew-r-srf/blob/master/r.rb) however with mixed success (it doesn't work on my system.). This same workaround is also discussed on [stackoverflow](https://stackoverflow.com/questions/48613209/r-package-geor-wont-install-on-macos-despite-available-tcl-tk-on-the-system)

Still disabling tcltk as well as x11 support and not even providing those as feature flags makes R pretty much unusable, which is why I have filed this bug report here.

**Comment by ilovezfs** [comment]
Please file a pull request if you have some change in mind other than adding options or an X11 dependency.

**Comment by dwt** [comment]
Well, not sure about your plans, but I'd say options or x11 dependency it is. The state this bundle is in right now it is probably better to deprecate and remove. Is that your intention? (Am I missing something?)

**Comment by ilovezfs** [comment]
My intention is to keep the formula exactly as it is but will review PRs for changes to it. If a PR wants to add options to the formula or to add an X11 dep, it will not be accepted.

**Comment by dwt** [comment]
Well, how about adding to the description that if image output or tclkt is required one should switch to the r-app version? (in the hope that is actually equivalent in providing shell tools and libraries to link against)

**Comment by dwt** [comment]
I still have to say I am quite surprised you deem R usable without image output. Sure it's also a mathematical programming language, but I would be quite surprised if users don't eventually want to create a graph.

**Comment by MikeMcQuaid** [comment]
> I still have to say I am quite surprised you deem R usable without image output.

To repeat myself from https://discourse.brew.sh/t/r-installs-on-high-sierra-without-tcl-tk-support/1190/26?u=mikemcquaid: looking at the analytics (https://formulae.brew.sh/analytics/) I suspect some of the 7,254 people who installed it in the last 30 days would disagree with you.

> but I'd say options or x11 dependency

Homebrew/homebrew-core is gradually moving to being a binary package manager. This means reducing the amount that users need to build from source as it's far more error prone. Options mean having to build from source. It's also worth noting since we've removed the options from the R formula we've seen the numbers of errors on users installing it drop dramatically.

macOS does not ship X11 and has not for a long time at this point. Applications that require X11 on macOS have not been fully ported to macOS so we are not including new ones and reducing the numbers we package.

Despite all of the above Homebrew is designed such that you can [create and maintain your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) where you can do pretty much whatever you'd like. What's not going to happen is for small numbers of people to convince us to change the approach that allows us to support large numbers of people without frequent errors.
