### ISSUE TITLE
Elasticsearch cannot be installed when using default java cask install.

### ISSUE THREAD

**Issue by TalosThoren** [Homebrew/homebrew-core#28947]
- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
brew gist-logs elasticsearch@5.6
Error: No logs.
```
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew doctor
Your system is ready to brew.
```

```
$brew config
HOMEBREW_VERSION: 1.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3081390ff845a6172b9004cf404c3e028e3be745
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4564ae4114a6e08141b4ae1da690883c2db5aab6
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.13.5-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: N/A
XQuartz: N/A
```
To help us debug your issue please explain:
- What you were trying to do (and why)
Install elasticsearch or elasticsearch@5.6 formula via `brew bundle` from a Brewfile. The java cask is installed, but defaults to java10. The elasticsearch formulae have a hardcoded requirement for java 1.8.

- What happened (include command output)
Errors with:
```
elasticsearch: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install homebrew/cask-versions/java8
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
```

- What you expected to happen
elasticsearch should install after installing the "java" cask. 

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install java
brew install elasticsearch@5.6
```

**Comment by commitay** [comment]
`brew cask install caskroom/versions/java8`

**Comment by TalosThoren** [comment]
Thanks, I should have checked if elasticsearch supported java10 before reporting this.
