### ISSUE TITLE
Tesseract Formula --with-serial-num-pack training data odd location

### ISSUE THREAD

**Issue by darth-pr** [Homebrew/homebrew-core#2899]
The serial num pack puts it training data into a different location rather than where the other packages put their data. I believe the following line needs to be updated in the formula:

From 
      (pkgshare/"tessdata").install resource("snum")

To
       resource("snum").stage { mv "snum.traineddata", share/"tessdata" }

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by darth-pr** [comment]
Will do testing out the change now to see if it works.

**Comment by DomT4** [comment]
Yeah, they should either all be in `pkgshare` or all be in `share`. I tried to express this in the prior PR 🙈.

**Comment by darth-pr** [comment]
pull request sent https://github.com/Homebrew/homebrew-core/pull/2907

**Comment by chrismattmann** [comment]
thanks for fixing this @darth-pr no worries @DomT4
