### ISSUE TITLE
qt5 --with-mysql fails to build on macOS: 10.13.5-x86_64

### ISSUE THREAD

**Issue by apaiva** [Homebrew/homebrew-core#29013]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/apaiva/f56698fc9eff0ba407829186d42a56f1

- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew gist-logs worked.

To help us debug your issue please explain:
- What you were trying to do (and why)

Reinstall qt5 with mysql support.   I've been using qt5 via pyqt for some time now and recently needed to add mysql support.  I've uninstalled qt5 and attempted to install again with "brew install -v qt5 --with-mysql"; however, the build fails.

- What happened (include command output)

Full output is in the gist, but here's the first error is:

qsql_mysql.cpp:235:9: error: unknown type name 'my_bool'
        my_bool nullIndicator;
        ^

- What you expected to happen

Clean build.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install -v --build-from-source qt5 --with-mysql

**Comment by apjanke** [comment]
I can reproduce on my own 10.3.5 box. Here's a gist-logs from a single-threaded build that's easier to read and spot the errors in: https://gist.github.com/2fdc6e416d6b1def761d0aeb647fdbea

**Comment by apjanke** [comment]
Based on https://github.com/brianmario/mysql2/issues/838#issuecomment-293312824, looks like `my_bool` was renamed to `bool` in MySQL 8, and it looks like Qt 5.11 is still targeting MySQL 5.7. I'm going to try modifying the Qt formula to use the versioned `mysql@5.7` and see how that goes.
