### ISSUE TITLE
Unable to Install Forumula jq (and oniguruma)

### ISSUE THREAD

**Issue by bmkaiser** [Homebrew/homebrew-core#29039]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install jq formula (and its dependency oniguruma)
- What happened (include command output)
Received error about not being able symlink (output included) because usr/local/include is not writable. When I try to fix by running `brew link jq` or `brew link oniguruma` that also fails
- What you expected to happen
I expected jq to install without errors
- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install jq
==> Installing dependencies for jq: oniguruma
==> Installing jq dependency: oniguruma
==> Downloading https://homebrew.bintray.com/bottles/oniguruma-6.8.2.high_sierra.bottle.tar.gz
Already downloaded: /Users/bkaiser/Library/Caches/Homebrew/oniguruma-6.8.2.high_sierra.bottle.tar.gz
==> Pouring oniguruma-6.8.2.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/oniggnu.h
/usr/local/include is not writable.

You can try again using:
  brew link oniguruma
==> Summary
🍺  /usr/local/Cellar/oniguruma/6.8.2: 17 files, 1.2MB
==> Installing jq
==> Downloading https://homebrew.bintray.com/bottles/jq-1.5_3.high_sierra.bottle.tar.gz
Already downloaded: /Users/bkaiser/Library/Caches/Homebrew/jq-1.5_3.high_sierra.bottle.tar.gz
==> Pouring jq-1.5_3.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/jq.h
/usr/local/include is not writable.

You can try again using:
  brew link jq
==> Summary
🍺  /usr/local/Cellar/jq/1.5_3: 19 files, 946.6KB
```
```
$ brew link jq
Linking /usr/local/Cellar/jq/1.5_3... 
Error: Could not symlink include/jq.h
/usr/local/include is not writable.
```
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  oniguruma
  jq
```
```
$ brew config
HOMEBREW_VERSION: 1.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3081390ff845a6172b9004cf404c3e028e3be745
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fbabc99fcf13f3e82254fec472f1fee896cbf3f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A
```

**Comment by bmkaiser** [comment]
```
$ ls -al /usr/local/include
ls: /usr/local/include: No such file or directory
```

**Comment by SMillerDev** [comment]
That folder is supposed to be created by the homebrew install script. You'd need to create it manually then I guess.
