### ISSUE TITLE
Brew install ant error

### ISSUE THREAD

**Issue by bacigalupe** [Homebrew/homebrew-core#29034]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): Trying to install ant using brew
- What happened (include command output): Installation failed. 
**Error: Failed to download resource "ant". Download failed: Couldn't determine mirror, try again later.**
- What you expected to happen: Ant to be installed
- Step-by-step reproduction instructions (by running `brew install` commands): 
**brew install ant**

![src1](https://user-images.githubusercontent.com/2863938/41397875-e2a9cce2-6fb5-11e8-939d-11a180fc3ac8.png)
![src2](https://user-images.githubusercontent.com/2863938/41397876-e2c527da-6fb5-11e8-9bed-6a275cfc2356.png)
![src3](https://user-images.githubusercontent.com/2863938/41397878-e2e0dc5a-6fb5-11e8-82dc-53bd8a5abc58.png)

**Comment by SMillerDev** [comment]
It's working fine here:
```sh
sean@sean-mac ~> brew install ant
==> Downloading https://www.apache.org/dyn/closer.cgi?path=ant/binaries/apache-ant-1.10.3-bin.tar.xz
==> Best Mirror http://apache.mirror.triple-it.nl/ant/binaries/apache-ant-1.10.3-bin.tar.xz
######################################################################## 100.0%
🍺  /usr/local/Cellar/ant/1.10.3: 1,645 files, 37.2MB, built in 9 seconds
```

Could it be an issue with your network connection? What happens when you do open the URL manually?

**Comment by bacigalupe** [comment]
Hi Sean,
thanks. It worked now. Not sure exactly what was the issue. The URL was accessible.
Thanks again. I'm closing this.
