### ISSUE TITLE
kubernetes-cli doesn't work with bottles and always builds from source

### ISSUE THREAD

**Issue by errordeveloper** [Homebrew/homebrew-core#29042]
So kubernetes-cli (aka kubectl) ignores bottles (at least in non-default prefix). Please note that in a fresh install building from source also requires go to be built.

I've looked at kops and kubernetes-helm formulas, and both set `cellar :any_skip_relocation`, however simply adding it (https://github.com/Homebrew/homebrew-core/pull/29040#issuecomment-397335699) turns out unacceptable and bot should be able to detect it instead. I'm not able to tell what's the problem at the moment, so I'll open an issue and let's come back to it.

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/29040#issuecomment-397412133

We'd review a pull request fixing that in `brew` or you can `brew install --force-bottle` for now.
