### ISSUE TITLE
 include binutils "as/gas" in hombrew binutils build

### ISSUE THREAD

**Issue by cartazio** [Homebrew/homebrew-core#29177]
NB: i'm happy to figure out the implied/associated pull request if i can figure the binutils build/configure process a bit better

on OSX the default / system assembler "as" is a wrapper for clang/llvm's built in linker, but more precisely its whatever version of that which apple decided to ship with their CLI tools that week. I've had a few encounters over time where I've wanted to compare results for different assemblers, and each time i reach over to the brew install binutils, I find myself saddened to see theres no inclusion of the binutils/gnu assembler!

https://ghc.haskell.org/trac/ghc/ticket/15207 is my most recent debugging misadventure where comparing what would happen with gas along side other combinations would have been possibly quite helpful

I went and did a build of binutils from source earlier today, and it does seem that the top level configure / recursive make may not be building GAS, but when i cd gas ; ./configure ; make that low and behold theres now a binary in that directory named as-new.

i'm pretty unfamliar with the build/configure process for binutils, so there may be a better way to build gas

further more: it looks like its a version of gas i built, aka "2.30" is pretty current at least with respect to fancy x86_64 extensions, though i've only done limited testing locally so far

would this addition/inclusion/change in whats provided by brew's binutils be welcome (i imagine it would be a useful aid in debugging one vector of OSX specific build issues)

how can ihelp make this happen?

cc @ilovezfs

**Comment by mistydemeo** [comment]
I'm definitely up for reviewing a PR to add this!

I would like to understand more about why it's not built by default. The configure script warns:

```
*** This configuration is not supported in the following subdirectories:
     ld gas gprof
    (Any other directories should still work fine.)
```

It is certainly true that we can `cd` into `gas` and it appears to build just fine - but I think it'd be good to understand the warning before we end up shipping a new tool. :)

**Comment by ilovezfs** [comment]
See also https://github.com/Homebrew/homebrew-core/pull/20050

**Comment by mistydemeo** [comment]
Looking at the configure script, `gas` is not installed because it is in the list of `noconfigdirs`, which is added as a part of this switch statement:

```bash
case "${target}" in
  *-*-chorusos)
    ;;
  aarch64-*-darwin*)
    noconfigdirs="$noconfigdirs ld gas gdb gprof"
    noconfigdirs="$noconfigdirs sim target-rda"
    ;;
  arm-*-darwin*)
    noconfigdirs="$noconfigdirs ld gas gdb gprof"
    noconfigdirs="$noconfigdirs sim target-rda"
    ;;
  powerpc-*-darwin*)
    noconfigdirs="$noconfigdirs ld gas gdb gprof"
    noconfigdirs="$noconfigdirs sim target-rda"
    ;;
  i[3456789]86-*-darwin*)
    noconfigdirs="$noconfigdirs ld gprof"
    noconfigdirs="$noconfigdirs sim target-rda"
    ;;
  x86_64-*-darwin[912]*)
    noconfigdirs="$noconfigdirs ld gas gprof"
    noconfigdirs="$noconfigdirs sim target-rda"
    ;;
# etc
```

In other words, it looks like disabling `gas` on Darwin is intentional. The closest to an explanation I can find is this changelog entry from 2009:

```
2009-07-02  Tristan Gingold  <gingold@adacore.com>

	* configure.ac: Do not exclude gas for i386-*-darwin.
	Add a case for x86_64-*-darwin.
	* configure: Regenerate.
```

Presumably `gas` was broken on x86_64 at this point? It is in fact true that it's enabled on 32-bit Darwin targets. If we want to look into reenabling this, I'd like to talk to the upstream developers and see how they feel about it.

**Comment by ilovezfs** [comment]
👍 to discussing this with upstream @cartazio

**Comment by fxcoudert** [comment]
GNU binutils simply do not support as or ld on macOS.

**Comment by ilovezfs** [comment]
does it work though?

**Comment by fxcoudert** [comment]
No.

```
$ clang -S a.c
$ as a.s -o a.o
$ clang a.o  
$ ./a.out 
1.85731

$ ./bin/as a.s -o a.o
a.s: Assembler messages:
a.s:2: Error: unknown pseudo-op: `.macosx_version_min'
$ vim a.s  # Edit out the unknown pseudo-op
$ ./bin/as a.s -o a.o
$ clang a.o          
ld: sectionForAddress(0xF8) address not in any section file 'a.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ilovezfs** [comment]
@cartazio that looks like a pretty good reason not to build `as`, no?
