### ISSUE TITLE
mysql formula does not uninstall cleanly, or mysql@5.7 doesn't work

### ISSUE THREAD

**Issue by matthewspeck** [Homebrew/homebrew-core#29173]
On a completely clean macOS High Sierra install, I brew installed the mysql formula, not realizing it was recently updated to 8.x. I brew uninstalled the mysql formula, and brew installed the mysql@5.7 formula. The mysql client cannot connect:
`$ mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)`

Turns out, the server can't start:
`$ mysql.server start
Starting MySQL
./usr/local/Cellar/mysql@5.7/5.7.22/bin/mysqld_safe: line 647: /usr/local/var/mysql/<hostname>.err: No such file or directory
Logging to '/usr/local/var/mysql/<hostname>.err'.
/usr/local/Cellar/mysql@5.7/5.7.22/bin/mysqld_safe: line 144: /usr/local/var/mysql/<hostname>.err: No such file or directory
/usr/local/Cellar/mysql@5.7/5.7.22/bin/mysqld_safe: line 198: /usr/local/var/mysql/<hostname>.err: No such file or directory
/usr/local/Cellar/mysql@5.7/5.7.22/bin/mysqld_safe: line 906: /usr/local/var/mysql/<hostname>.err: No such file or directory
/usr/local/Cellar/mysql@5.7/5.7.22/bin/mysqld_safe: line 144: /usr/local/var/mysql/<hostname>.err: No such file or directory
 ERROR! The server quit without updating PID file (/usr/local/var/mysql/<hostname>.pid).`

Investigation suggests exactly these symptoms when trying to run 5.7 after an incompletely uninstalled 8.x installation. It could also be that the mysql@5.7 formula is broken. I've tried all the stuff with chown and chmod on various /tmp/ directories and files.

**Comment by matthewspeck** [comment]
Running sudo mysql.server start does log to an error file. Relevant error:
`2018-06-18T17:08:39.825080Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.`
Taking that advice:
`$ sudo mysql_upgrade
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.`

**Comment by matthewspeck** [comment]
If I ask homebrew to remove a formula, it should _remove_ the formula, not leave the system in a broken state that interferes with a future formula. If I `brew doctor` at that point, it should _fix_ the new formula, not think the system is in a working state. Either or both of the `mysql` or `mysql@5.7` formulae are incorrect.

**Comment by SMillerDev** [comment]
Removing mysql doesn't remove the data on Linux either, there's actually no precedent I know of for removing user data when removing a program.

**Comment by matthewspeck** [comment]
The trouble is that the system is now in an apparently unrecoverable state, due specifically to the incomplete removal of one formula (I never added any data before uninstalling). How am I to proceed?

**Comment by Neodork** [comment]
@matthewspeck The error you mentioned in https://github.com/Homebrew/homebrew-core/issues/29173#issuecomment-398127286 is actually created by a conflict between the MySQL 8 and MySQL 5 installations.

MySQL v5 is unable to start due to incompatible log files you can workaround that by backup up the `ib_logfile` files within the `/usr/local/var/mysql` folder. Then restarting MySQL 5 will regenerate the file.

**MySQL error log:**
```
2018-06-18T11:22:59.119244Z 0 [Note] InnoDB: Completed initialization of buffer pool
2018-06-18T11:22:59.133263Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2018-06-18T11:22:59.133567Z 0 [ERROR] InnoDB: Unsupported redo log format. The redo log was created with MySQL 8.0.11. Please follow the instructions at http://dev.mysql.com/doc/refman/5.7/en/upgrading-downgrading.html
2018-06-18T11:22:59.133590Z 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2018-06-18T11:22:59.578008Z 0 [ERROR] Plugin 'InnoDB' init function returned error.
2018-06-18T11:22:59.578053Z 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2018-06-18T11:22:59.578066Z 0 [ERROR] Failed to initialize builtin plugins.
2018-06-18T11:22:59.578085Z 0 [ERROR] Aborting
```

**Comment by Alexia** [comment]
This new mysql@8.0 formula really should not install over top of the existing older mysql formulas without at least producing a warning.  I just spent my morning manually fixing this after it was installed over top the old formula.

**Comment by SMillerDev** [comment]
You told it to upgrade though and it did, quite successfully. Otherwise every update would need a warning that it could break things, thus rendering the warning useless.

**Comment by rowild** [comment]
I uninstalled mysql 8 and brew install mysql@5.7 again (after cleanup and doctor). Now I get:
`mysql command not found`.
What do i have to do to make mysql5.7 run?

**Comment by SMillerDev** [comment]
Probably have to link it first (more info available in the caveats)

**Comment by rowild** [comment]
Damn it! I just read the line in question... One of those incidents, where I had to post the problem just to find the solution just 2 seconds afterwards... Sorry!
And thank you, @SMillerDev for replying so quickly!

**Comment by neilctm** [comment]
I did `brew install mysql@5.7` then `brew switch mysql 5.7.22`

**Comment by Itsindigo** [comment]
Ty @mistydemeo, your command worked for me.

Had some really weird behaviours prior to that:

```
~/projects/hostmaker-api (production)
 🙈 👉  which mysql
/usr/local/opt/mysql@5.7/bin/mysql
~/projects/hostmaker-api (production)
 🙈 👉  mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 28
Server version: 8.0.12 Homebrew
```
