### ISSUE TITLE
Request to upgrade Node formula to 10.5.0

### ISSUE THREAD

**Issue by neokio** [Homebrew/homebrew-core#29265]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Here's my `brew config`:
```
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f17a4691e8dedbace9dd180165258db9b2bea24
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: 12-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A
```

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm using the latest brew formula for Node, 10.4.1. After updating to OSX 10.13.5, I noticed that `gulp` was failing with the error:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33261
    at Object.fs.fchmod (fs.js:1058:11)
    at Object.fchmod (/Users/n/www/etherium_beta/node_modules/graceful-fs/polyfills.js:237:17)
    at mode (/Users/n/www/etherium_beta/node_modules/vinyl-fs/lib/file-operations.js:237:10)
    at onStat (/Users/n/www/etherium_beta/node_modules/vinyl-fs/lib/file-operations.js:227:14)
    at /Users/n/www/etherium_beta/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:185:5)
```
A cursory google revealed this post ... https://github.com/gulpjs/gulp/issues/2177 ... indicating that it was a Node 10 bug ... https://github.com/nodejs/node/issues/20498 ... which has been fixed in Node 10.5.0, released 6 hours ago. 

From what I've seen, the Homebrew crew is magnificent at regularly updating node. So this post is little more than a "Yeah, yer killin' it!" cheer and fingers crossed for a speedy update, as downgrading to node@8 isn't an option, and I'm dead in the water without a working gulp.

So ... "Go team!" Apologies if this isn't the correct venue for this post, if not I'd like to know where. Thanks :)

**Comment by ilovezfs** [comment]
look at https://github.com/Homebrew/homebrew-core/pulls
