### ISSUE TITLE
OpenCV in homebrew-core does not to include opencv_contrib (despite formula referencing it)

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#29261]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Re-opening https://github.com/Homebrew/homebrew-core/issues/28040 from @blucia0a since it was closed and locked

@ilovezfs  said:
> It's always built with contrib https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb#L38

* However, opencv_contrib is nowhere to be found in installation directory under:
/Users/timothee/homebrew/Cellar/opencv/3.4.1_5/include/opencv2/

* Side question: is this a good idea to lock outdated issues? with the lock there is no cross reference from https://github.com/Homebrew/homebrew-core/issues/28040 to this issue, so someone looking at the other issue will not know to look at this issue as a follow-up

* NOTE: with `brew install --keep-tmp opencv` , we indeed have `opencv-3.4.1/opencv_contrib/` files, however seems like these are not being used in build process

**Comment by commitay** [comment]
> opencv_contrib is nowhere to be found in installation directory under ...

It builds with contrib, it doesn't ship an `opencv_contrib` folder.

> Side question: is this a good idea to lock outdated issues

Yes.

> however seems like these are not being used in build process

https://github.com/Homebrew/homebrew-core/blob/60cbb03221b2ca55f9ea0e2b87cdc69ee425bf81/Formula/opencv.rb#L65

https://github.com/opencv/opencv_contrib#how-to-build-opencv-with-extra-modules
