### ISSUE TITLE
Unable to install ffmpeg with options (keep encountering the "JavaRequirement unsatisfied!" error message)

### ISSUE THREAD

**Issue by rEes9P** [Homebrew/homebrew-core#29313]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Here is my `brew config` log**
```
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f331594dbb82eb5ef6b1e9956b44a80c6231980e
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.5-x86_64
CLT: 10.0.0.0.1.1527767617
Xcode: 9.4.1
XQuartz: N/A
```

**Here is my `brew doctor` log**
`Your system is ready to brew.`

**What I was trying to do**
I was trying to install ffmpeg with options
`brew install ffmpeg --with-chromaprint --with-fdk-aac --with-fontconfig --with-freetype --with-frei0r --with-game-music-emu --with-libass --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-librsvg --with-libsoxr --with-libssh --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-rubberband --with-sdl2 --with-snappy --with-speex --with-srt --with-tesseract --with-theora --with-tools --with-two-lame --with-wavpack --with-webp --with-x265 --with-xz --with-zeromq --with-zimg`

**What happened (including command output)**
I got an error message stating that Java was required
```
ant: Java 1.8+ is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install java
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
```

**What I expected to happen**
For the installation to go through smoothly without having to encounter the Java requirement. FYI, the command `brew install ffmpeg` installs without any issues and in the past (over a year ago) I was also able to install ffmpeg with the following options successfully
`brew install ffmpeg --with-chromaprint --with-fdk-aac --with-fontconfig --with-freetype --with-frei0r --with-game-music-emu --with-libass --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-libsoxr --with-libssh --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-rubberband --with-schroedinger --with-sdl2 --with-snappy --with-speex --with-tesseract --with-theora --with-tools --with-two-lame --with-wavpack --with-webp --with-x265 --with-xz --with-zeromq --with-zimg`

**Comment by mistydemeo** [comment]
I think this is coming from libbluray, which has a `depends_on :java => ["1.8", :build]` dependency. That was added in f5f3b20bfbb, about six months ago. In this case it probably shouldn't be trying to build libbluray from source, though, so that shouldn't be fatal.

**Comment by ilovezfs** [comment]
The error is emanating from `depends_on :java => "1.8+"` in ant. Even though libbluray only has

```
  depends_on "ant" => :build
```
and we're pouring the libbluray bottle, that requirement ends up being enforced.

```
iMac-TMP:~ joe$ brew install libbluray
ant: Java 1.8+ is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew-Cask:
 brew cask install java
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
iMac-TMP:~ joe$ 
```

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ brew deps --tree --include-requirements libbluray
libbluray
├── fontconfig
│   └── freetype
│       └── libpng
└── freetype
    └── libpng

iMac-TMP:~ joe$ brew deps --tree --include-requirements --include-build libbluray
libbluray
├── :java = 1.8
├── ant
│   └── :java >= 1.8
├── pkg-config
├── fontconfig
│   ├── pkg-config
│   └── freetype
│       └── libpng
└── freetype
    └── libpng

```
