### ISSUE TITLE
python

### ISSUE THREAD

**Issue by cppguru** [Homebrew/homebrew-core#29311]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 
https://gist.github.com/6ee839646458c2da6e03cff168e54798
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install python3 and pyobjc module and work with MacOS Cocoa applications

- What happened (include command output)
`brew install python --framework`
`pip3 install pyobjc`
`python3`
`>>> import objc`
`>>> import Foundation`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`ModuleNotFoundError: No module named 'Foundation'`

- What you expected to happen
I expected the Foundation module to be found.  It works with python2.  Tried upgrading, tried uninstalling and reinstalling, nothing works.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install python --framework`
`pip3 install pyobjc`
`python3`
`>>> import objc`
`>>> import Foundation`

**Comment by mistydemeo** [comment]
Hm, I'm not able to confirm this behaviour. Are you sure that `pip3` and `python3` are both the Homebrew-installed tools, and not something else in your PATH? Have you asked the pyobjc developers for help? We're not able to provide help for bugs that originate in third-party modules that weren't installed in Homebrew, unless something in Homebrew is causing the bugs.

**Comment by cppguru** [comment]
`python3` and `pip3` are indeed from Homebrew.  If I `brew uninstall python` both are gone.
`which pip3` is `/usr/local/bin/pip3`.
`which python3` is `/usr/local/bin/python3`.

`$ ls -l /usr/local/bin/pip3`
`lrwxr-xr-x  1 xxx  admin  33 Jun 22 04:32 /usr/local/bin/pip3 -> ../Cellar/python/3.6.5_1/bin/pip3`

`$ ls -l /usr/local/bin/python3`
`lrwxr-xr-x  1 xxx  admin  36 Jun 22 04:32 /usr/local/bin/python3 -> ../Cellar/python/3.6.5_1/bin/python3`

I did not talk to `pyobjc` developers as this works for a friend of mine who did not install `python3` using HomeBrew.  On another machine the `import Foundation` works if I run `/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/bin/python3`.  (Not, if I run `/usr/local/bin/python3`.)  But not on my home laptop.  I have tried to uninstall all versions of python.  Then install it again.  Makes no difference.  I have no clue what else I can do.

**Comment by cppguru** [comment]
I have uninstalled `python` again, deleted `/usr/local/lib/python3.6/` by hand, then reinstalled, `pip3 install pyobjc`, now it works.
