### ISSUE TITLE
Install/Update of git fails with --with-gettext option

### ISSUE THREAD

**Issue by Stargator** [Homebrew/homebrew-core#29322]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): I was trying to update 2.17.1 version of git to 2.18.0 because the newer versions contains performance fixes and I wanted to stay up to date.

- What happened (include command output):
brew upgrade
```bash
Error: Not upgrading 3 pinned packages:
go 1.10.3, nginx 1.15.0, gnupg 2.2.8
==> Upgrading 1 outdated package, with result:
git 2.17.1 -> 2.18.0
==> Upgrading git --with-pcre2 --with-gettext --with-perl
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.18.0.tar.xz
Already downloaded: /Users/johnmcmahon/Library/Caches/Homebrew/git-2.18.0.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.18.0 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
Last 15 lines from /Users/johnmcmahon/Library/Logs/Homebrew/git/01.make:
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make: *** [levenshtein.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [line-range.o] Error 1
make: *** [ident.o] Error 1
make: *** [hex.o] Error 1
1 error generated.
make: *** [kwset.o] Error 1
1 error generated.
make: *** [list-objects.o] Error 1
1 error generated.
make: *** [line-log.o] Error 1
```
- What you expected to happen:
I expected the new version of git to be installed without issue.

- Step-by-step reproduction instructions (by running `brew install` commands):
1. `brew install git --with-pcre2 --with-gettext --with-perl`

1. `brew update && brew outdated && brew missing && brew prune && brew cleanup && brew doctor`

1. `brew upgrade`

- **Workaround**

I **uninstalled* git `brew uninstall git`` then via trial and error, slowly removed the additional `--with` options until the formula installed without issue.

Which landed me at running `brew install git --with-pcre2 --with-perl`, **Note**: that `--with-gettext` was removed and the installation worked after that.

- brew config output:
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f331594dbb82eb5ef6b1e9956b44a80c6231980e
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_141
macOS: 10.13.1-x86_64
CLT: N/A
Xcode: 9.2
XQuartz: N/A
- brew doctor output:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (9.2) is outdated.
Please update to Xcode 9.4 (or delete it).
Xcode can be updated from the App Store.

**Comment by Stargator** [comment]
Additional note, I had copied the Git formula locally (with the 2.17.1 version) and tried to install with the options `--with-pcre2 --with-gettext --with-perl` and it failed as well, so I don't know what's changed to cause a conflict between gettext and git

**Comment by mistydemeo** [comment]
Can you please provide the output of `brew gist-logs git`?

**Comment by Stargator** [comment]
https://gist.github.com/Stargator/0d836b9d3b86c82c678a8cfbea797a36

**Comment by mistydemeo** [comment]
Hm, it looks like it's not finding `libintl.h`. It looks like it's building in stdenv, so the gettext flags aren't making it to the compiler.

I noticed your Xcode is outdated. Can you try upgrading that?

```
Warning: Your Xcode (9.2) is outdated.
Please update to Xcode 9.4 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by Stargator** [comment]
I cannot upgrade Xcode as I am on a corporate machine and have to wait for the update to come through corporate channels

**Comment by ilovezfs** [comment]
Can you please try and provide the output of
```
mkdir brew20180628
cd brew20180628
brew bundle dump
mv Brewfile Brewfile.before
brew uninstall --ignore-dependencies $(brew deps --include-build --include-optional git)
brew bundle dump
mv Brewfile Brewfile.after
diff Brewfile.before Brewfile.after
brew install git --with-pcre2 --with-gettext --with-perl
brew gist-logs git
```

**Comment by Stargator** [comment]
Output is below. Do not that I couldn't uninstall git because `Error: No such keg: /usr/local/Cellar/atk`

Because of that, I believe the [Brewfiles](https://gist.github.com/Stargator/3b3bf35e48fb5dd0c5764250e9f9ea24) are indentical.

```bash
mkdir brew20180628
$ cd brew20180628/
$ brew bundle dump
$ mv Brewfile Brewfile.before
$ brew uninstall --ignore-dependencies $(brew deps --include-build --include-optional git)
Error: No such keg: /usr/local/Cellar/atk
$ brew bundle dump
$ mv Brewfile Brewfile.after
$ diff Brewfile.before Brewfile.after
$ brew install git --with-pcre2 --with-gettext --with-perl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 4 taps (homebrew/cask-versions, homebrew/core, homebrew/cask, dart-lang/dart).
==> Updated Formulae
algernon                    chakra                      docfx                       gopass                      maxwell                     saltstack                   webpack
annie                       conan                       erlang@20                   groonga                     netpbm                      silk                        xonsh
ansible                     dart-lang/dart/dart@2       feh                         joplin                      open-scene-graph            skaffold                    zstd
bitrise                     dhall-json                  fn                          kompose                     paket                       streamlink
cfengine                    diffoscope                  fortio                      libphonenumber              rsyslog                     tkdiff

Warning: git 2.18.0 is already installed and up-to-date
To reinstall 2.18.0, run `brew reinstall git`
$ brew gist-logs git
https://gist.github.com/8fc4401d112eab73311511ac92d1a4d1
```

**Comment by ilovezfs** [comment]
Ah OK, sorry. You need to use `-f` also for the uninstall step

```
$ brew uninstall -f --ignore-dependencies $(brew deps --include-build --include-optional git)
```

**Comment by Stargator** [comment]
The [Brewfiles can be found here.](https://gist.github.com/Stargator/7fd7cb4364c947bbeb102605bfbac86c)

```bash
mkdir brew20180629
$ cd brew20180629/
$ brew bundle dump
$ mv Brewfile Brewfile.before
$ brew uninstall -f --ignore-dependencies $(brew deps --include-build --include-optional git)
Uninstalling autoconf... (71 files, 3.0MB)
Uninstalling automake... (131 files, 3MB)
Uninstalling boost... (13,506 files, 447.6MB)
Uninstalling curl... (423 files, 3MB)
Uninstalling gdbm... (38 files, 1.1MB)
Uninstalling gettext... (1,934 files, 16.9MB)
Uninstalling icu4c... (250 files, 67.3MB)
Uninstalling libffi... (16 files, 297.0KB)
Uninstalling libtool... (71 files, 3.7MB)
Uninstalling openssl... (1,792 files, 12.3MB)
Uninstalling pcre... (204 files, 5.3MB)
Uninstalling pcre2... (224 files, 5.3MB)
Uninstalling perl... (4,855 files, 120.2MB)
Uninstalling pkg-config... (11 files, 627.1KB)
Uninstalling python... (9,144 files, 155.9MB)
Uninstalling python@2... (7,516 files, 123.5MB)
Uninstalling readline... (46 files, 1.5MB)
Uninstalling sphinx-doc... (2,675 files, 41.4MB)
Uninstalling sqlite... (11 files, 3.5MB)
Uninstalling xz... (92 files, 1MB)
$ brew bundle dump
$ mv Brewfile Brewfile.after
$ diff Brewfile.before Brewfile.after
12d11
< brew "boost"
23,24d21
< brew "icu4c"
< brew "readline"
33,34d29
< brew "pcre2"
< brew "pkg-config"
$ brew install git --with-pcre2 --with-gettext --with-perl
Warning: git 2.18.0 is already installed and up-to-date
To reinstall 2.18.0, run `brew reinstall git`
Error: Git must be installed and in your PATH!
Warning: git 2.18.0 is already installed and up-to-date
To reinstall 2.18.0, run `brew reinstall git`
$ brew gist-logs git
https://gist.github.com/3f7f8fec1cda6ba9cd004035858f55e1
```

**Comment by ilovezfs** [comment]
Looks like it was successful? To be sure

```
brew uninstall -f git
brew install git --with-pcre2 --with-gettext --with-perl
brew gist-logs git
```

**Comment by Stargator** [comment]
Hey, brew found this issue!

```bash
$ brew uninstall -f git
$ brew install git --with-pcre2 --with-gettext --with-perl
==> Installing dependencies for git: pcre2, gettext, perl
==> Installing git dependency: pcre2
==> Downloading https://homebrew.bintray.com/bottles/pcre2-10.31.high_sierra.bottle.tar.gz
Already downloaded: /Users/johnmcmahon/Library/Caches/Homebrew/pcre2-10.31.high_sierra.bottle.tar.gz
==> Pouring pcre2-10.31.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pcre2/10.31: 224 files, 5.3MB
==> Installing git dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.high_sierra.bottle.tar.gz
Already downloaded: /Users/johnmcmahon/Library/Caches/Homebrew/gettext-0.19.8.1.high_sierra.bottle.tar.gz
==> Pouring gettext-0.19.8.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.8.1: 1,935 files, 16.9MB
==> Installing git dependency: perl
==> Downloading https://homebrew.bintray.com/bottles/perl-5.28.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/johnmcmahon/Library/Caches/Homebrew/perl-5.28.0.high_sierra.bottle.tar.gz
==> Pouring perl-5.28.0.high_sierra.bottle.tar.gz
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.bash_profile
==> Summary
🍺  /usr/local/Cellar/perl/5.28.0: 2,456 files, 63MB
==> Installing git --with-pcre2 --with-gettext --with-perl
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.18.0.tar.xz
Already downloaded: /Users/johnmcmahon/Library/Caches/Homebrew/git-2.18.0.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.18.0 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
Last 15 lines from /Users/johnmcmahon/Library/Logs/Homebrew/git/01.make:
1 error generated.
1 error generated.
1 error generated.
1 error generated.
make: *** [hex.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [levenshtein.o] Error 1
make: *** [ident.o] Error 1
make: *** [line-range.o] Error 1
1 error generated.
make: *** [kwset.o] Error 1
1 error generated.
make: *** [list-objects.o] Error 1
1 error generated.
make: *** [line-log.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Git update broken https://github.com/Homebrew/homebrew-core/issues/29568
Install/Update of git fails with --with-gettext option https://github.com/Homebrew/homebrew-core/issues/29322

Error: Your Xcode (9.2) is outdated.
Please update to Xcode 9.4 (or delete it).
Xcode can be updated from the App Store.

$ brew gist-logs git
https://gist.github.com/94cdfc7a04fc36693b2adf1f698f98d2
```

**Comment by mistydemeo** [comment]
Is there a file named `~/Library/Logs/Homebrew/git/01.make.cc`? Your logs have been missing one of the files I've expected to see.

**Comment by Stargator** [comment]
```bash
$ ls ~/Library/Logs/Homebrew/git/
00.options.out	01.make		02.make		03.make		04.make		05.make		06.make		07.make
```

**Comment by Stargator** [comment]
@mistydemeo Does my last update clarify or help in anyway?

**Comment by Stargator** [comment]
@mistydemeo or @ilovezfs I confirmed that `~/Library/Logs/Homebrew/git/01.make.cc` is missing, is there something I should do?

**Comment by Stargator** [comment]
@mistydemeo or @ilovezfs Still waiting for a response.

**Comment by Stargator** [comment]
And now I am getting the same issue when I try to install git 2.19.0_1.

**Comment by Stargator** [comment]
I had to drop --with-curl and --with-openssl in order for git to install

**Comment by Stargator** [comment]
This issue has been resolved by the removal of additional git options
