### ISSUE TITLE
[root] formula does not link against python@2 correctly.

### ISSUE THREAD

**Issue by kratsg** [Homebrew/homebrew-core#29377]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

https://gist.github.com/kratsg/05e0f1523dd79f9c460e9cc71990afd6

```
kratsg:~$ brew install root --with-python@2 --without-python
....
kratsg:~$ . /usr/local/bin/thisroot.sh
kratsg:~$ python
Python 2.7.14 (default, Mar 22 2018, 15:04:47) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/root/6.12.06/lib/root/ROOT.py", line 24, in <module>
    import cppyy
  File "/usr/local/Cellar/root/6.12.06/lib/root/cppyy.py", line 61, in <module>
    import libPyROOT as _backend
ImportError: dynamic module does not define init function (initlibPyROOT)
```

Brew doctor: system raring to brew (no issues)

What I expect to happen: being able to import PyROOT without issues as in all previous versions of homebrew-root.

(Original report: #26921)

**Comment by mistydemeo** [comment]
It looks like we may need to remove that option, unfortunately. According to the ROOT developers, PyROOT no longer supports being built against multiple Pythons; it now only works with the version of Python ROOT itself was built against. https://root-forum.cern.ch/t/root-working-only-with-python3/28329/4

**Comment by mistydemeo** [comment]
Strangely, I'm not able to reproduce. It looks like I'm using a point release newer of Python, but I don't think that would affect anything?

```
$ python
Python 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
>>> cppyy
<module 'cppyy' from '/usr/local/Cellar/root/6.14.00/lib/root/cppyy.pyc'>
>>> import libPyROOT
>>> import libPyROOT as _backend
>>> _backend
<module 'libPyROOT' from '/usr/local/Cellar/root/6.14.00/lib/root/libPyROOT.so'>
```

**Comment by mistydemeo** [comment]
Actually, looking at the versions, it looks like you have ROOT 6.12.06. Does this still happen if you upgrade to 6.14.00?

**Comment by mistydemeo** [comment]
Ping - is this still an issue?

**Comment by kratsg** [comment]
Indeed, this went away with 6.14.00.
