### ISSUE TITLE
ImageMagick v6.9.5-2

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#2937]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?  (N/A since I just ran it recently.)  

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.  

----

I'm filing this issue as a placeholder for when I have time to file the actual pull request required to propagate this ImageMagick update to the rest of the Homebrew community  later, but it's perfectly fine by me if anybody decides that they want to swoop in and ninja-resolve this before I get to it.

**Comment by dunn** [comment]
Already swooped! https://github.com/Homebrew/homebrew-core/pull/2935

**Comment by RandomDSdevel** [comment]
OK, cool!  Thanks for the help, @dunn!
