### ISSUE TITLE
Installing Python 3 next to pre-v1.5.0 Python 2 produces 'upgrade instead' error

### ISSUE THREAD

**Issue by bkimmett** [Homebrew/homebrew-core#29373]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
Cobalt:somefolder bkimmett$ brew gist-logs python
Error: No logs.
```

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
Cobalt:somefolder bkimmett$ brew config
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 89b66f09a5c2fc58e7239e4d3666744c28bd40fa
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11
```
```
Cobalt:somefolder bkimmett$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install Python 3. Python 2 was already installed through Homebrew (using `brew install python` prior to when the Python formula was changed in v1.5.0.

- What happened (include command output)
When I tried to install Python 3, I received an error:
```
Cobalt:somefolder bkimmett$ brew install python3
Error: python 2.7.11 is already installed
To upgrade to 3.6.5_1, run `brew upgrade python`
```

I then tried to install Python 2, assuming that brew would detect the existing Python install and simply modify its internal state to account for it, and otherwise take no action - which would enable me to install Python 3 from scractch after the change was over. Instead, it started reinstalling Python 2 from scratch:
```Cobalt:somefolder bkimmett$ brew install python@2
==> Installing dependencies for python@2: openssl, readline, sqlite
==> Installing python@2 dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2o_2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2o_2.sierra.bottle.tar.gz
^C
```

- What you expected to happen
I assumed that brew would detect the existing Python install, and turn the current install of 'python' into a 'python@2' install by modifying its internal state (that is, letting itself know that the install of python was a Version 2 install and should be labeled accordingly). Once this was done, brew should have automatically installed Python 3.  
  
Alternately, brew could have detected the existing python installation during `brew upgrade` to/past version 1.5.0, realized that it was Python 2, and renamed which formula was already installed in its internal state accordingly, so that this error would not come up.

- Step-by-step reproduction instructions (by running `brew install` commands)
   * Have an existing installation of Python 2 created by `brew install python` prior to the v1.5.0 change in the Python formula.
   * Run `brew install python3`.

**Comment by ilovezfs** [comment]
This is expected behavior. `brew upgrade python` or `brew uninstall python` must be run before using the new `python@2` formula. The old `python3` formula was migrated to `python`, not the other way around.

**Comment by bkimmett** [comment]
While it is, as you say, expected behavior, I don't think it's intuitive for the casual user who's upgrading their Python. I've always felt that Brew typically does the intuitive thing if the situation is ambiguous.
