### ISSUE TITLE
Saltstack should be named Salt

### ISSUE THREAD

**Issue by kedare** [Homebrew/homebrew-core#29404]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

The `saltstack` formula should be named `salt`.
SaltStack is the name of the company behind the `salt` product/project, it doesn't really make sense to use this name for the formula.

**Comment by ilovezfs** [comment]
This makes sense given the [naming on PyPI](https://pypi.org/project/salt/) in other package managers
https://repology.org/metapackage/salt/versions
vs.
https://repology.org/metapackage/saltstack/versions

I have opened https://github.com/Homebrew/homebrew-core/pull/29773

**Comment by ilovezfs** [comment]
It's now renamed! Thanks for the suggestion @kedare

**Comment by kedare** [comment]
Great, thanks :)
