### ISSUE TITLE
cimg 2.3.0 Formula Fails to Install Because of Invalid Hash (again…)

### ISSUE THREAD

**Issue by Frizlab** [Homebrew/homebrew-core#29413]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  -> No need for brew config or doctor for this issue; it’s a shasum mismatch.

Trying to upgrade cimg on my machine, compiling from source, I get a shasum mismatch. Homebrew expects `70d1b23ccf1959e0bbadea1a5b1f87c95642528e3ce8deb02f95a4b01f6ddb22` but gets `b9edd5a4ab49a2eea81d6ea2e10c47ed9fee3c20cef7d15e4be4cb52002cb6d0`.
It happened before with cimg 2.0.4 (https://github.com/dtschump/CImg/issues/155, cc @dtschump).

**Comment by ilovezfs** [comment]
This is now fixed via the 2.3.1 release. Thanks for reporting @Frizlab
