### ISSUE TITLE
msbuild is not included in mono

### ISSUE THREAD

**Issue by mcclure** [Homebrew/homebrew-core#29420]
"msbuild" is a critical tool for use of modern C#. It is normally found distributed with either the Mono or .NET Core packages.

`brew install mono` does not include msbuild. Nor is there a standalone msbuild package. With the most current mono ("mono: stable 5.12.0.226 (bottled)") `which msbuild` returns nothing.

In this issue in the msbuild repo https://github.com/Microsoft/msbuild/issues/1685 several mono project members confirm mono is included with the official mono release on their website.

**Expected behavior**: Either msbuild should be included with mono, there should be an msbuild package, or there should be an msbuild package which mono depends on.

Why I am filing: I encountered this error https://github.com/OmniSharp/omnisharp-vscode/issues/2011 Which the person in the issue said was fixed by upgrading msbuild. But I don't have an msbuild on my system, at all.

Template questions:

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [NO] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [YES] ran `brew update` and can still reproduce the problem?
- [REPORTS AN OLD XCODE AND A MISSING PYTHON DEPENDENCY. IRRELEVANT TO C#] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- ["Error: No logs."] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1b23cc14a8162dd0bb59977b23a0e00c62941217
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.2-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11
```

**Comment by mcclure** [comment]
See https://github.com/Homebrew/homebrew-core/pull/29422

**Comment by ilovezfs** [comment]
`brew upgrade` and you should now have `msbuild` thanks to @mistydemeo
