### ISSUE TITLE
PHP does not have json1 support enabled

### ISSUE THREAD

**Issue by Paris** [Homebrew/homebrew-core#29449]
# Background

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew gist-logs php`: https://gist.github.com/Paris/3d79026edeb103912e9b77921a9ed469

# Problem

PHP's SQLite3 module not have the [json1](https://www.sqlite.org/json1.html) build flag, furthermore it cannot be loaded as an external extension for security reasons.

Test code:
```
$db = new \SQLite3(':memory:');
echo $db->querySingle('SELECT sqlite_version()'), PHP_EOL;
$j = ['this' => 'is', 'a' => [2, true, null]];
$q = 'select json_extract(\'' . json_encode($j) . '\', \'$.a[0]\');';
$r = $db->querySingle($q);
echo $q, PHP_EOL, "  → ", $r, PHP_EOL;
$db->close();
```

Output on Homebrew:
```
3.20.1
PHP Warning:  SQLite3::querySingle(): Unable to prepare statement: 1, no such function: json_extract in /Users/paris/Documents/Development/powerbot/www/tests/run.php on line 11
select json_extract('{"this":"is","a":[2,true,null]}', '$.a[0]');
  → 
```

Output on Ubuntu Bionic with `php7.2-sqlite3` installed:
```
3.11.0
select json_extract('{"this":"is","a":[2,true,null]}', '$.a[0]');
  → 2
```

**Comment by SMillerDev** [comment]
Is json1 part of the used sqlite build though?

**Comment by Paris** [comment]
Yes is its both macOS and Homebrew's sqlite3 package are built with json1 and don't need to have it loaded as a external extension.

**Comment by SMillerDev** [comment]
I'm not entirely sure what the issue is then. PHP not picking up on the SQLite extensions?

**Comment by Zegnat** [comment]
I am not sure where PHP is getting its SQLite from, but not from Homebrew? I have SQLite from Homebrew, and this version is able to use the `json_extract`:

```
$ /usr/local/opt/sqlite/bin/sqlite3
SQLite version 3.24.0 2018-06-04 19:24:41
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select json_extract('{"this":"is","a":[2,true,null]}', '$.a[0]');
2
```

But even after a `brew reinstall php --build-from-source`, I am still only seeing SQLite version 3.20.1 in use by PHP. And the `json_extract()` does not work.

I haven’t looked into it any further, but this makes it sound like the problem would be solved if Homebrew used its own SQLite during the built?

**Comment by Zegnat** [comment]
I had another look. PHP bundles SQLite inside of both ext/sqlite3 and ext/pdo_sqlite. The latter even seems to be able to use the version bundled with the former – though I might be mistaken as I am not used to reading and interpreting GNU autoconf files. Unless you configure a different path for building (or disable the extension entirely) those bundled files will be used. The bundled version is the 3.20.1 we were seeing.

I have been successful in using Homebrew’s SQLite by patching the PHP formula as follows:

```patch
diff --git a/Formula/php.rb b/Formula/php.rb
index 5f4ec6c61..3d7d23a4d 100644
--- a/Formula/php.rb
+++ b/Formula/php.rb
@@ -33,6 +33,9 @@ class Php < Formula
   depends_on "pcre"
   depends_on "unixodbc"
   depends_on "webp"
+
+  option "with-sqlite", "Build using Homebrew SQLite for pdo_sqlite and sqlite3 extentions."
+  depends_on "sqlite" => [:build, :optional]

   needs :cxx11

@@ -142,6 +145,9 @@ class Php < Formula
       --with-zlib
     ]

+    args << "--with-sqlite3=#{Formula["sqlite"].opt_prefix}" if build.with? "sqlite"
+    args << "--with-pdo-sqlite=#{Formula["sqlite"].opt_prefix}" if build.with? "sqlite"
+
     if MacOS.version < :lion
       args << "--with-curl=#{Formula["curl"].opt_prefix}"
     else
```

I was then able to do:

```
$ brew reinstall php --build-from-source --with-sqlite
```

(I think the `--build-from-source` is optional? No harm.)

I know there has been a lot of discussion about what to include in this new PHP formula, and what to exclude, when it was brought over from the old homebrew/php tap. There might have been a reason not to link it against Homebrew’s SQLite. There might be a reason not to add this back as an optional flag.

Would a PR like this still be appreciated?

**Comment by Paris** [comment]
Yes @Zegnat please post a PR.
