### ISSUE TITLE
Calling 'depends_on :perl' is disabled!

### ISSUE THREAD

**Issue by ctlxu** [Homebrew/homebrew-core#29463]
An error message showed up when running "brew upgrade git" on my mac OS 10.12.6:
=======================================
Error: Calling 'depends_on :perl' is disabled!
Use 'depends_on "perl"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/git.rb:45:in `<class:Git>'
Please report this to the homebrew/core tap!
Or, even better, submit a PR to fix it!
=======================================
Please help to fix the issue. Thanks.

**Comment by SMillerDev** [comment]
Please fill out the issue form, without it it's very hard to debug the reason for your issue.

**Comment by fxcoudert** [comment]
You have a very outdated git formula. Run `brew up` and try again. If that does not work, run `brew update-reset`:

```
       update-reset
              Fetches and resets Homebrew and all tap repositories using git(1) to their  latest  origin/master.  Note
              this will destroy all your uncommitted or committed changes.
```
