### ISSUE TITLE
request: qt@5.9

### ISSUE THREAD

**Issue by dagheyman** [Homebrew/homebrew-core#29471]
Any chance for a Qt@5.9 version? It's considered [LTS](http://blog.qt.io/blog/2017/05/11/introducing-long-term-support-qt-5-9/) by Qt, and there are some regression bugs in Qt 5.11 (in my case it is [QTBUG-67663](https://bugreports.qt.io/browse/QTBUG-67663)).

**Comment by SMillerDev** [comment]
Pull requests are always welcome

**Comment by dagheyman** [comment]
Yes, asking first, because of the discussion [here](https://github.com/Homebrew/homebrew-core/issues/23234).

@ilovezfs wrote:
> Given this is the first mention of any interest in an @5.9, and the motivation sounds theoretical, I don't think this would be a good use of our CI resources, as qt builds take several hours.

I guess that makes me the second mention.

**Comment by Noctem** [comment]
This could be useful for people that compile qBittorrent themselves. There are some bugs in qBittorrent (like invisible progress bars qbittorrent/qbittorrent#8988) with both Qt 5.10 and 5.11, so I've been building [this formula](https://gist.github.com/Noctem/87a5247a4da5540fb6a6b55a94e518b6) to use with it.

**Comment by ilovezfs** [comment]
Thanks for the suggestion @dagheyman but I still don't think the level of demand for this warrants the CI resources it requires.
