### ISSUE TITLE
bew install cdiff: Error: SHA256 mismatch

### ISSUE THREAD

**Issue by bes** [Homebrew/homebrew-core#29485]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Here is the requested output from above:

```
brew gist-logs cdiff
Error: No logs.

brew install cdiff                                                                                                        1 ↵
==> Downloading https://github.com/ymattw/cdiff/archive/1.0.tar.gz
Already downloaded: /Users/bes/Library/Caches/Homebrew/cdiff-1.0.tar.gz
Error: SHA256 mismatch
Expected: d9aa95299973cf25cba9d62a41df845ec4c5d391b9aca4d84f32fcefecccd846
Actual: 50725ea8b0ea0e7e70b41fd0aebd3ab92a097a825c2bdf22fb487f97c6151db1
Archive: /Users/bes/Library/Caches/Homebrew/cdiff-1.0.tar.gz
To retry an incomplete download, remove the file above.

brew gist-logs cdiff                                                                                                      1 ↵
Error: No logs.

brew config                                                                                                               1 ↵
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 571b46213c70ca1573da6d0425b0bd6df34961ee
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.16.3 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: 9.4.1
XQuartz: N/A

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/bes/miniconda2/bin/python2-config
  /Users/bes/miniconda2/bin/python2.7-config
  /Users/bes/miniconda2/bin/python-config
  /Users/bes/miniconda2/bin/ncursesw6-config
```

To help us debug your issue please explain:
- What you were trying to do (and why)
```
brew install cdiff
```

Why: I would really like to use cdiff.

- What happened (include command output)
```
brew install cdiff                                                                                                        1 ↵
==> Downloading https://github.com/ymattw/cdiff/archive/1.0.tar.gz
Already downloaded: /Users/bes/Library/Caches/Homebrew/cdiff-1.0.tar.gz
Error: SHA256 mismatch
Expected: d9aa95299973cf25cba9d62a41df845ec4c5d391b9aca4d84f32fcefecccd846
Actual: 50725ea8b0ea0e7e70b41fd0aebd3ab92a097a825c2bdf22fb487f97c6151db1
Archive: /Users/bes/Library/Caches/Homebrew/cdiff-1.0.tar.gz
To retry an incomplete download, remove the file above.
```

A manual check of the downloaded archive shows that it indeed does not have a matching sha256 checksum to what is specified in this git:

```
gsha256sum /Users/bes/Library/Caches/Homebrew/cdiff-1.0.tar.gz
50725ea8b0ea0e7e70b41fd0aebd3ab92a097a825c2bdf22fb487f97c6151db1  /Users/bes/Library/Caches/Homebrew/cdiff-1.0.tar.gz
```

Compare with sha256 specified here https://github.com/Homebrew/homebrew-core/blob/master/Formula/cdiff.rb

- What you expected to happen
cdiff to be properly installed

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install cdiff
```

Thanks!

**Comment by mistydemeo** [comment]
Looks like the tarball was probably regenerated because of the repo rename.

**Comment by mistydemeo** [comment]
cc #28674

**Comment by mistydemeo** [comment]
Fixed by merging that PR and updating to the latest ydiff.
