### ISSUE TITLE
libiomp needs to create a symbol link named libgomp

### ISSUE THREAD

**Issue by yecloud** [Homebrew/homebrew-core#2949]
### Bug reports:

After libiomp installed, there is only one lib file is created which is /usr/local/lib/libiomp5.dylib
But most applications are configured with **-lgomp** argument in their makefile.
So, libiomp needs to create a symbol link named libgomp to support popular compiling and linking activities.

ln -s /usr/local/lib/libiomp5.dylib /usr/local/lib/libgomp.dylib

**Comment by MikeMcQuaid** [comment]
> But most applications are configured with -lgomp argument in their makefile.

Which applications?

**Comment by yecloud** [comment]
The application is libiomp

$ brew info libiomp
libiomp: stable 20150701 (bottled)
Manage multiple threads in an OpenMP program as it executes
https://www.openmprtl.org/download
/usr/local/Cellar/libiomp/20150701 (8 files, 536.3K) *
  Poured from bottle on 2016-07-12 at 16:01:40
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libiomp.rb
==> Dependencies
Build: cmake ✔

**Comment by yecloud** [comment]
I'm working on siril which is an image processing tool. The -lgomp is generated by automake/autoconfig. The configure script will generate the makefile with -lgomp once it found OpenMP support (by export CC=clang-omp). So it is not controlled by end-user or developer.
It seems -lgomp is a standard usage and in the policy of auto-tools.

**Comment by yecloud** [comment]
If CC=clang, then OpenMP is nor enabled, so there is no -lgomp passed to makefile.

**Comment by MikeMcQuaid** [comment]
> I'm working on siril which is an image processing tool.

Working on a Homebrew formula for it?

> If CC=clang, then OpenMP is not enabled, so there is no -lgomp passed to makefile.

I'm not sure this is a bug, then?

**Comment by yecloud** [comment]
> Working on a Homebrew formula for it?

yes

> I'm not sure this is a bug, then?

no

**Comment by MikeMcQuaid** [comment]
You're going to have to be more verbose/explicit in your replies and issues if you want your bugs fixed. Can you explain more, please?

**Comment by yecloud** [comment]
libiomp create only one single lib file which is libiomp5.dylib
Once the OpenMP is enabled for clang, the autoconfig/automake tool will recognize it and pass an option '-lgomp' to the makefile in order to enable OpenMP for the program to be built.
But there is no libgomp in the system at all. The program can not be built successfully.
If I make a symbol link:
ln -s /usr/local/lib/libiomp5.dylib /usr/local/lib/libgomp.dylib
Then the option '-lgomp' is working and the making process will finish with no error.

**Comment by MikeMcQuaid** [comment]
It seems https://gcc.gnu.org/projects/gomp/ is only for GCC (not Clang) so it sounds like the upstream project needs to be fixed to not just look for `gomp`

**Comment by yecloud** [comment]
Yes, -lgomp is a gcc style option.
But I don't think the auto-tools could add a policy to check iomp instead of gomp on OS/X.
clang have been pretending it is a gcc from the very begging, so clang supports most common gcc options.
And we could see a lot of such example, postfix will create a 'sendmail' program to pretend it is sendmail, vim create an 'vi' to pretend it is vi.
So iomp should also create a 'gomp' to pretend it is gomp for compatibility perpose.

**Comment by MikeMcQuaid** [comment]
> But I don't think the auto-tools could add a policy to check iomp instead of gomp on OS/X.

It definitely could add that if it chose to do so.

> So iomp should also create a 'gomp' to pretend it is gomp for compatibility perpose.

I don't agree for now but: thanks for the information. We'll consider reopening this in future if it causes problems for additional formulae.

**Comment by DomT4** [comment]
> We'll consider reopening this in future if it causes problems for additional formulae.

I presume by this you meant to close the Issue?

**Comment by MikeMcQuaid** [comment]
@DomT4 I did, thanks.
