### ISSUE TITLE
Git update broken

### ISSUE THREAD

**Issue by boajer** [Homebrew/homebrew-core#29568]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I trying to update git formula, as an precondition, that probably had an influence, is the fact of migration from one machine to another, with help of embeded migrationn assistance. I've did it several times before, without any issue, but not it looks like `brew doctor` shows a lot of things. Please see attached `gist` 
In case of this matter migration happed from MB13'' 2015->2016.
- What happened (include command output)
https://gist.github.com/boajer/f36427016a536665a3baaaa4d17ab2b6
- What you expected to happen
new version of git formula to be installed
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew update`

**Comment by mistydemeo** [comment]
It looks like you have some non-Homebrew installed headers in `/usr/local/include`; these are interfering with the build. In particular, `/usr/local/include/stdint.h` and other headers like it are interfering with the system headers.

**Comment by boajer** [comment]
I would assume the same, but the machine with this issue is a migrated
version of another one, where everything works awesome. So I can assume
that libs you are referring two are originally introduced by home brew
itself. I will be happy to try anything you can propose me for fixing this,
preferably excluding wiping all data :)

**Comment by mistydemeo** [comment]
The headers listed weren't installed by Homebrew; you can find them in the list of "Unbrewed header files". :) I would recommend looking over that list of headers to determine what you think you might need and what you don't, and delete headers from that list you think you don't need. In particular, headers that shadow system headers like `stdint.h` will cause problems.

**Comment by boajer** [comment]
I will try, thank you, but that is bit surprising, as the laptop on which I observe that issue, is just a migrated copy of  another where, where everything work excellent, nothing is reported by `brew doctor, so I suspect same libs, headers and all other components supposed to be same. 
Is there any way how to figure out what software may require that header files?

**Comment by mistydemeo** [comment]
Unfortunately I can't predict which of those headers might be needed by other things you have installed. My suggestion would be to move all of the headers listed in your `brew doctor` to a temporary directory so that you have backups in case you discover that you need some of them later.
