### ISSUE TITLE
Python 3.7 update breaks cffi

### ISSUE THREAD

**Issue by jlaine** [Homebrew/homebrew-core#29601]
Since the python formula was updated to 3.7 the cffi package has ceased to work, and bombs:

```
ImportError: dlopen(/Users/travis/build/jlaine/aiortc/.eggs/cffi-1.11.5-py3.7-macosx-10.12-x86_64.egg/_cffi_backend.so, 2): Symbol not found: __PyThreadState_Current
  Referenced from: /Users/travis/build/jlaine/aiortc/.eggs/cffi-1.11.5-py3.7-macosx-10.12-x86_64.egg/_cffi_backend.so
  Expected in: flat namespace
 in /Users/travis/build/jlaine/aiortc/.eggs/cffi-1.11.5-py3.7-macosx-10.12-x86_64.egg/_cffi_backend.so
```

This was encountered as part of a CI run on travis, the full build log is here:

https://travis-ci.org/jlaine/aiortc/jobs/398564350

**Comment by ilovezfs** [comment]
If you preinstall cffi, it'll be fine. The problem is the easy_install version of cffi is actually an old version built for python 3.4.

See https://bitbucket.org/cffi/cffi/issues/367/problems-installing-other-packages-with

The proper fix is to stop using easy_install and rely on modern pip mechanisms only.

**Comment by ilovezfs** [comment]
See also https://www.python.org/dev/peps/pep-0518/ for info about the deprecation of `setup_requires`

**Comment by jlaine** [comment]
Fair enough, thanks for all the pointers, I'll close this issue.

**Comment by ilovezfs** [comment]
@jlaine you're welcome!

**Comment by ilovezfs** [comment]
@jlaine fyi the offending files have now been removed by cffi upstream so the problem is fixed. See https://bitbucket.org/cffi/cffi/issues/367/problems-installing-other-packages-with#comment-46512656

**Comment by jlaine** [comment]
Great, it's good too have the root cause identified. Thanks again for your quick response

**Comment by ilovezfs** [comment]
You're welcome!
