### ISSUE TITLE
Augeas 1.5 is broken for Elektra

### ISSUE THREAD

**Issue by raetiacorvus** [Homebrew/homebrew-core#2961]
Hi,

current augeas 1.5 seems to be broken when using it with the ausgeas plugin for libelektra.

Using the bottled version of 1.5 results in `Syntax error in lens definition` while --HEAD works without problems.

After some further testing I made the following discoveries:
switching the HEAD to the `version-1.5` tag in the augeas formula also results in a working installation.
Whereas building and installing augeas from the source package results in the same error as state above.

The only difference between the two is that source package builds use `configure` whereas git source builds use `autogen.sh`.

I was not able to reproduce this error on Arch Linux and another member of the team stated the same for Debian.

Related Issue in libelektra:
https://github.com/ElektraInitiative/libelektra/issues/812

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)
