### ISSUE TITLE
MongoDB 4 Upgrade Issues

### ISSUE THREAD

**Issue by mclassdesigns** [Homebrew/homebrew-core#29622]
Not sure if I'm alone here, but Homebrew upgraded my installation of MongoDB to version 4 and I cleaned out version 3.6 from my system before realizing there were some steps I needed to do to make the upgrade successful, as shown here:

https://docs.mongodb.com/manual/release-notes/4.0-upgrade-standalone/

The upgrade requires three key steps:

1. Upgrade to SCRAM authentication: https://docs.mongodb.com/manual/release-notes/3.0-scram/
2. Remove the use of the $isolated operator
3. The "featureCompatibilityVersion" must be set to 3.6

I'm assuming this has led to the problem I'm facing. From my mongo.log:

"IMPORTANT: UPGRADE PROBLEM: The data files need to be fully upgraded to version 3.6 before attempting an upgrade to 4.0; see http://dochub.mongodb.org/core/4.0-upgrade-fcv for more details."

So, now I need to revert to MongoDB 3.6, but that package is no longer available. Only version 3.4 is available and it seems you can't perform the upgrade steps above in version 3.4.

Is there something I'm missing, or does someone have any advice?

**Comment by ilovezfs** [comment]
@mclassdesigns You can now `brew install mongodb@3.6` and use that to perform the tweaks. See https://github.com/Homebrew/homebrew-core/pull/29641
