### ISSUE TITLE
Brew update fails (Error: Fetching /usr/local failed!)

### ISSUE THREAD

**Issue by jonaslierschied** [Homebrew/homebrew-core#2970]
- [x] Ran `brew update` and retried your prior step?

> error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/.git/refs/remotes/origin/master.lock': File exists.
> 
> If no other git process is currently running, this probably means a
> git process crashed in this repository earlier. Make sure no other git
> process is running and remove the file manually to continue.
> error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/Library/Taps/homebrew/homebrew-core/.git/refs/remotes/origin/master.lock': File exists.
> 
> If no other git process is currently running, this probably means a
> git process crashed in this repository earlier. Make sure no other git
> process is running and remove the file manually to continue.
> error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/Library/Taps/caskroom/homebrew-cask/.git/refs/remotes/origin/master.lock': File exists.
> 
> If no other git process is currently running, this probably means a
> git process crashed in this repository earlier. Make sure no other git
> process is running and remove the file manually to continue.
> Error: Fetching /usr/local failed!
> Fetching /usr/local/Library/Taps/homebrew/homebrew-core failed!
> Fetching /usr/local/Library/Taps/caskroom/homebrew-cask failed!

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: Your Homebrew is outdated.
> You haven't updated for at least 24 hours. This is a long time in brewland!
> To update Homebrew, run `brew update`.

- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

> I tried running `sudo chown -R $(whoami) $(brew --prefix)`, but unfortunately no difference in behavior.

### Bug reports:

Yesterday I did a fresh install of OS X El Capitan (10.11.5) as well as set up my settings etc. In this process Homebrew for me is the key to do it very quick and efficient. Today I wanted to continue with the setup but I recognised that I have a problem updating brew -- yesterday the update function as well as installing all my apps and other stuff worked without problem. 
The strange thing is, that I still can download apps via cask or other stuff via brew install, only the update function of brew does not work.

I did the above mentioned steps as well as checked the URLs of GitHub (git -C /usr/local remote -v) -- the solution of this [issues](https://github.com/Homebrew/brew/issues/52).

> origin	https://github.com/Homebrew/brew (fetch)
origin	https://github.com/Homebrew/brew (push)

I also did brew config:

> HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: cdf4f42ab951214fb7fac0781091783552415944
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d95ccdd5168d89e500d49222af001f13cf5430c
Core tap last commit: 25 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.5-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A

Unfortunately I have no idea what it could be and I really appreciate every help of you guys. Thanks a lot in advance. Cheers, Jonas

**Comment by DomT4** [comment]
Are you running any scripts that could auto-update Homebrew? Setting `HOMEBREW_DEVELOPER` could do that, as would using something like [my tool here](https://github.com/DomT4/homebrew-autoupdate). It's unlikely to be that if you're hitting repeated `brew update` failures though rather than a single instance.

If this happens repeatedly rather than as a one-off failure try:

```
rm -f /usr/local/Library/Taps/homebrew/homebrew-core/.git/refs/remotes/origin/master.lock
rm -f /usr/local/.git/refs/remotes/origin/master.lock
rm -f /usr/local/Library/Taps/caskroom/homebrew-cask/.git/refs/remotes/origin/master.lock
brew update
```

And then `brew update` again if that's successful to see if it reproduces.

**Comment by jonaslierschied** [comment]
@DomT4: Thanks for your tip. 

The following appears after I ran the delete commands and updated brew:

> /usr/local/Library/Homebrew/cmd/update.sh: line 14:  4046 Segmentation fault: 11  "$GIT_EXECUTABLE" "$@"
/usr/local/Library/Homebrew/cmd/update.sh: line 14:  4044 Segmentation fault: 11  "$GIT_EXECUTABLE" "$@"
/usr/local/Library/Homebrew/cmd/update.sh: line 14:  4048 Segmentation fault: 11  "$GIT_EXECUTABLE" "$@"
Error: Fetching /usr/local failed!
Fetching /usr/local/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Library/Taps/caskroom/homebrew-cask failed!

I would say no changes, or? What now? Thanks a lot.

**Comment by MikeMcQuaid** [comment]
@jonaslierschied what does `which git` show? If it's a Homebrew-installed one try to `brew reinstall git`.

**Comment by jonaslierschied** [comment]
@MikeMcQuaid: Thanks for your tip. `Which git` shows the following path `/usr/bin/git`. I guess it is not an Hombrew-installed version, or?

**Comment by MikeMcQuaid** [comment]
@jonaslierschied Are you on a Hackintosh by any chance? Can we see your `brew config`.

**Comment by jonaslierschied** [comment]
@MikeMcQuaid Thanks for your reply. I dont think that I am on a Hackintosh? Why do you think so?

My `brew config` is as follows

> HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: cdf4f42ab951214fb7fac0781091783552415944
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d95ccdd5168d89e500d49222af001f13cf5430c
Core tap last commit: 5 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.5-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A

**Comment by jonaslierschied** [comment]
Hey guys, any idea or tip on my issues. 
Today I recognized the following folder: `bash_completion.d` (path: `/usr/local/etc`). I dont know why this folder is there. The only content is file named `brew`. When I delete this folder and try to update brew via terminal (`brew update`), the following lines are printed in the terminal:
`error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/.git/refs/remotes/origin/master.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/Library/Taps/homebrew/homebrew-core/.git/refs/remotes/origin/master.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/Library/Taps/caskroom/homebrew-cask/.git/refs/remotes/origin/master.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
Error: Fetching /usr/local failed!
Fetching /usr/local/Library/Taps/homebrew/homebrew-core failed!
Fetching /usr/local/Library/Taps/caskroom/homebrew-cask failed!
To restore the stashed changes to /usr/local run:
  'cd /usr/local && git stash pop'`

The last two lines are new compared to before. Thanks for your help.

**Comment by UniqMartin** [comment]
`etc/bash_completion.d/brew` in `/usr/local` belongs to Homebrew and is part of its Git repository, so you shouldn't be deleting this. The additional two lines of output are related to this, as removing this means you made local modifications and `brew update` reverted them to restore Homebrew to a pristine state before the update.

The problem is that your Git is crashing for some reason and we don't know why. You could try removing the lock files and re-running `brew update` as suggested earlier, but I suspect you will see the same crashes again.

If that's the case, you might be having problems with your hard disk (or SSD) or some other hardware problem. Maybe the Git installed as part of the Command Line Tools got corrupted somehow. Have you tried running First Aid in Disk Utility on your system hard drive lately?

**Comment by jonaslierschied** [comment]
Hi @UniqMartin,

thanks for your answer. Is it possible to delete my current git version and install a fresh git?
I checked my hardware but there is no, at least obvious, hardware issue. As you said, I did run First Aid in Disk Utility but nothing unusual. 

What now? Any ideas? Thanks a lot guys.

**Comment by UniqMartin** [comment]
If your installation of the Command Line Tools got corrupted, it would be best to reinstall it. Sadly, I'm not aware of an easy way to do that, but maybe others will have a suggestion.

As a workaround, you could try and install a different Git via Homebrew, i.e. `brew install git`. It should be picked up automatically next time you run `brew update`, but you can check to make sure by looking at the `Git:` line in the output of `brew config`.

**Comment by DomT4** [comment]
> If your installation of the Command Line Tools got corrupted, it would be best to reinstall it. Sadly, I'm not aware of an easy way to do that, but maybe others will have a suggestion.

I generally go for the blunt axe method of doing:
```
sudo rm -rf /Library/Developer/CommandLineTools/
xcode-select --install
```

**Comment by jonaslierschied** [comment]
Hi guys,

as you can see in my `brew config`, I have installed via brew git. Unfortunately nothing changed -- the same error appears. Also to delete the command line tools as well as to install them does not effect the behavior. 

> HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: cdf4f42ab951214fb7fac0781091783552415944
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d95ccdd5168d89e500d49222af001f13cf5430c
Core tap last commit: 8 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.5-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: N/A

Other suggestions? Thanks a lot.

**Comment by jonaslierschied** [comment]
Do you guys think if I reset my OS X completely that the bug is gone? Thanks

**Comment by UniqMartin** [comment]
> Also to delete the command line tools as well as to install them does not effect the behavior.

If the behavior is unchanged even after re-installing CLT and trying with the Git offered by Homebrew, then I suspect there's some corruption in the respective Git repositories (possibly due to a previous crashed Git run). This shouldn't normally cause Git to misbehave this gravely, but it's a possible explanation …

Can you try whether the following succeeds or whether it reveals any issues?

```sh
cd "$(brew --repository)" && git fsck --no-dangling
```

What happens if you try manually fetching updates for a Git repository like in the following?

```sh
cd "$(brew --repository)" && git fetch origin
```

> Do you guys think if I reset my OS X completely that the bug is gone? Thanks

This might be something to try as a last resort, but that's not something I would consider just yet. Have you considered (or tried) completely uninstalling Homebrew and then re-installing it from scratch? You should be able to dump all installed formulae and casks using `brew bundle dump` (unless the Git misbehavior also prevents you from tapping the homebrew/bundle repository). This will create a `Brewfile` with all relevant information in the current working directory and can be later used with `brew bundle` to re-install all formulae/casks.

**Comment by jonaslierschied** [comment]
Thanks @UniqMartin for your tips and sorry the longer pause. Here are my results about the steps I should do.

> cd "$(brew --repository)" && git fsck --no-dangling
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6298/6298), done.

> cd "$(brew --repository)" && git fetch origin
remote: Counting objects: 687, done.
remote: Compressing objects: 100% (278/278), done.
remote: Total 687 (delta 544), reused 534 (delta 397), pack-reused 0
Receiving objects: 100% (687/687), 101.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (544/544), completed with 89 local objects.
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/.git/refs/remotes/origin/master.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
From https://github.com/Homebrew/brew
 ! cdf4f42..9f6cb8e  master     -> origin/master  (unable to update local ref)

I havent thought yet about reinstallaing Homebrew from scratch, but I can do it also as a next step. Besides `brew bundle dump` what do I have to do for a reinstall of Homebrew?  Thanks a lot.

**Comment by UniqMartin** [comment]
> Here are my results about the steps I should do.

Please retry the second step after removing the pointed out lock file (as you already did several times before). They always get re-created and remain after a crash, but as long as they are there, Git will complain that they are there and won't do everything it would normally do. (The point of this test was to see if Git also crashes when invoked on the Homebrew repository, but outside of the Homebrew update process.)

> I havent thought yet about reinstallaing Homebrew from scratch, but I can do it also as a next step. Besides `brew bundle dump` what do I have to do for a reinstall of Homebrew? Thanks a lot.

Please have a look at https://github.com/Homebrew/install. Aside from that, the procedure is roughly:

1. Just in case, have a backup of your system/Homebrew before continuing.
2. `brew bundle dump` to generate a `Brewfile` and put that in a safe place.
3. Use the uninstaller to remove Homebrew.
4. Use the installer to install Homebrew from scratch.
5. Use `brew bundle` with the previously generated `Brewfile` to install all formulae and casks that were previously installed.

**Comment by jonaslierschied** [comment]
Hi @UniqMartin,

I did what you asked for. Here are the result to the second step, after I deleted the lock file:
> cd "$(brew --repository)" && git fetch origin
error: cannot lock ref 'refs/remotes/origin/master': Unable to create '/usr/local/.git/refs/remotes/origin/master.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
From https://github.com/Homebrew/brew
 ! cdf4f42..209d9e8  master     -> origin/master  (unable to update local ref)

So unfortunately no change... I think the last line beginning with exclamation mark is new. Does this line help to solve the problem? Thanks to all and have a nice weekend.

**Comment by UniqMartin** [comment]
To be honest, I don't know what is going on on your end and why you continue to have issues with these lock files and Git apparently misbehaving. I'm running out of ideas here, short of the previously suggested reinstall of Homebrew.

The issue seems to be really specific to your system and not a problem with Homebrew as such, so I'm not sure how much further we can go with trying to help you. Sorry about that!

**Comment by jonaslierschied** [comment]
Hey guys,

I am really sorry for not answering and reporting after a such long period. Just want to give you some updates on my issue. Unfortunately nothing has changed, I still have the same problem as I described above. I tried the two (radical) solutions: 1. delete and reinstall Homebrew and 2. reinstall of OSX.

As I mentioned before, both solution have not changed anything. I still get the same error and I am not sure what causes it. In the following, I describe what happened after the two approaches:

1. I deleted Homebrew as described above -- the deletion worked quite well. Unfortunately I was not able to reinstall Homebrew. Terminal accepted my command, worked on it and it seemed that Homebrew was installed. However, Terminal did not accept brew commands afterwards. I have to mention that I can not rule out the possibility that I did a mistake... That means maybe I screwed off this solution by myself.
2. I reinstalled OSX 10.11.6 and installed Homebrew afterwards. It worked quite well, for example  I installed all my apps via Cask. Then I adjust my system based on [Mathias dotfiles](https://github.com/mathiasbynens/dotfiles) as well as [OS-X-Security-and-Privacy-Guide](https://github.com/drduh/OS-X-Security-and-Privacy-Guide) and the problem occurred again: in short, I still can use Homebrew but I am not able to update Homebrew anymore. The exact mentioned error code from above occurs if I try to update.

So my problem is really specific to my system and not a problem with Homebrew itself. I actually believe that it is much more a problem with Git. I have found different Crash Reports of Git (3 files), in the folder (/Users/username/Library/Logs/), which I attached as ZIP-file to this post. (FYI, I was not able to attach the files without zipping them, because GitHub does not know the file ending .crash.) Because I am not familiar with reading/analysing Crash Reports, it would be great if someone could give me some feedback on it. 

Thank you very much in advance and best regards,
Jonas

[Git Crash report.zip](https://github.com/Homebrew/homebrew-core/files/440793/Git.Crash.report.zip)

**Comment by MikeMcQuaid** [comment]
> Then I adjust my system based on Mathias dotfiles as well as OS-X-Security-and-Privacy-Guide and the problem occurred again: in short, I still can use Homebrew but I am not able to update Homebrew anymore. The exact mentioned error code from above occurs if I try to update.

I'd suggest something in here has broken your Git. I'm afraid if Git is crashing there's nothing we can do here, sorry.

**Comment by Joshsteverson** [comment]
FWIW I was able to resolve this issue by running `brew install <package>`. This appears to have forced the update and now I am able to run `brew update` without error.
