### ISSUE TITLE
PETSc complex support is missing after migration

### ISSUE THREAD

**Issue by izaid** [Homebrew/homebrew-core#29737]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

PETSc only supports one kind of datatype (either real or complex), chosen at build time. When PETSc was migrated from homebrew-science a few months ago, I believe there was an option for complex support in the formula that didn't get brought over.

Would it be possible to update the PETSc formula so that it includes support for complex numbers? Probably, there needs to be two packages, something like petsc-real (which can be the default petsc) and petsc-complex. This is exactly what Ubuntu does: https://packages.ubuntu.com/xenial/libpetsc-complex-3.6.2-dev

Right now, users who want to use complex numbers have to use their own formula of PETSc, which amounts to simply changing `"--with-scalar-type=real"` to "--with-scalar-type=complex".
 
I believe @fmahebert did the migration, so pinging him here.

- What happened (include command output)

PETSc only supports real numbers.

- What you expected to happen

An option for PETSc to also support complex numbers.

- Step-by-step reproduction instructions (by running `brew install` commands)

N/A

**Comment by fmahebert** [comment]
Hi @izaid. When I migrated PETSc it was indicated to me that I should not use options (see discussion in PR #23598), so I made the choice to build real support only.

Providing two packages, for real and complex builds, may be an acceptable approach — the Homebrew devs will have to comment.

**Comment by izaid** [comment]
@ilovezfs Yes, we can certainly build two libraries with one formula. The problem I guess is what the library names are and which ones does `libpetsc` link to? I just checked the Ubuntu behaviour, and they have `libpetsc_real.so` and `libpetsc_complex.so`, which separately come from `libpetsc` and `libpetsc-complex` packages. If you only have one installed, then `libpetsc` links to that one. If you have both, I'm not sure if it is the only installed mostly recently or just `libpetsc_real`.

I don't mind if there are two formulas or one formula with both.

@fmahebert Thanks for replying so quickly!

**Comment by izaid** [comment]
Just raising this again. Pinging @ilovezfs because I need his help.

I'm happy to make the changes here. The existing formula is: https://github.com/Homebrew/homebrew-core/blob/master/Formula/petsc.rb

I literally just need to replace `"--with-scalar-type=real"` with `"--with-scalar-type=complex"`. Should I just make a new install section like so?

```

  def install
    ENV["CC"] = "mpicc"
    ENV["CXX"] = "mpicxx"
    ENV["F77"] = "mpif77"
    ENV["FC"] = "mpif90"
    system "./configure", "--prefix=#{prefix}",
                          "--with-debugging=0",
                          "--with-scalar-type=real",
                          "--with-x=0"
    system "make", "all"
    system "make", "install"
    system "./configure", "--prefix=#{prefix}",
                          "--with-debugging=0",
                          "--with-scalar-type=complex",
                          "--with-x=0"
    system "make", "all"
    system "make", "install"
  end
``` 

Expect somehow the second library also needs to be renamed `libpetsc-complex`...

**Comment by ilovezfs** [comment]
```
args = %W[
  --prefix=#{prefix}
  --with-debugging=0
  --with-x=0
]
```

```
system "./configure", "--with-scalar-type=real", *args
```
and
```
system "./configure", "--with-scalar-type=complex", *args
```

**Comment by ilovezfs** [comment]
>Expect somehow the second library also needs to be renamed libpetsc-complex...

You'd have to check the Ubuntu package to see how they're doing that.

**Comment by izaid** [comment]
Thanks @ilovezfs. I'll make some changes and report back.

**Comment by ilovezfs** [comment]
@izaid btw the rocksdb formula is similar in doing a double build if you want something to look at.
