### ISSUE TITLE
csvkit 1.0.2 & python 3.7.0 produces a lot of deprecation warnings

### ISSUE THREAD

**Issue by jillesvangurp** [Homebrew/homebrew-core#29775]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I installed csvkit using homebrew. After python 3 updated to 3.7.0 with a brew upgrade, the output of any csvqsl command includes a lot of python deprecation warnings. I noticed, brew currently installs an older version 1.0.2_04. I verified that 1.0.3 (current stable) installed via pip3 does not have this issue. So, the solution would be to update the formula to install that. 

- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install csvkit
csvsql
```

produces a lot of non fatal warnings like 

```
/usr/local/Cellar/csvkit/1.0.2_4/libexec/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py:405: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
/usr
```

**Comment by SMillerDev** [comment]
This is a problem with csvkit then, and should probably be reported here: https://github.com/wireservice/csvkit/issues

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew-core/pull/29777

**Comment by jillesvangurp** [comment]
Thanks @ilovezfs. I'd have to read up on how to update homebrew formulas to do this.

**Comment by ilovezfs** [comment]
@jillesvangurp you're welcome. This should now be fixed if you run `brew upgrade csvkit`.
