### ISSUE TITLE
Irssi

### ISSUE THREAD

**Issue by angaron** [Homebrew/homebrew-core#29808]
Hi,

When building Irssi from source (macOS 10.14 and 10.13) it doesn't support Perl scripting so no plugin will work, this do not occur when installing from keg (macOS 10.13).

**Comment by ilovezfs** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
