### ISSUE TITLE
Installing Terminator on macOS 10.14

### ISSUE THREAD

**Issue by kmbuki** [Homebrew/homebrew-core#29805]
`brew install terminator` throws up this error

Error: gtk+: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gtk+.rb:46: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gtk+.rb:54: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gtk+.rb:67: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^

**Comment by ilovezfs** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**
