### ISSUE TITLE
Request for python@3.6

### ISSUE THREAD

**Issue by holymonson** [Homebrew/homebrew-core#29836]
Python is upgrade to 3.7 and breaks compatibility. Many fundamental libraries like __Twisted__ and __pyyaml__ are not ready for 3.7, then breaks even more applications.

Could you please bring back python@3.6 ? At least until pyhon3.7 is widely in production?

**Comment by ilovezfs** [comment]
There is no plan to add a python@3.6 at this time. See discussion on https://github.com/Homebrew/homebrew-core/pull/10239

>Many fundamental libraries like Twisted and pyyaml are not ready for 3.7

PyYAML 3.13 is Python 3.7 compatible. I'm not sure what the situation is with Twisted but you'll need to take that up with them.
