### ISSUE TITLE
Composer command not working after update

### ISSUE THREAD

**Issue by brainworker** [Homebrew/homebrew-core#29858]
After Homebrew/php update to homebrew/core, I have updated php to php@7.1. Everything works fine. PHP cli works too and I can see right php.ini files loaded using php --ini

**php --ini output**
Configuration File (php.ini) Path: /usr/local/etc/php/7.1
Loaded Configuration File:         /usr/local/etc/php/7.1/php.ini
Scan for additional .ini files in: /usr/local/etc/php/7.1/conf.d
Additional .ini files parsed:      /usr/local/etc/php/7.1/conf.d/ext-opcache.ini,
/usr/local/etc/php/7.1/conf.d/ext-xdebug.ini

**ps aux | grep 'php-fpm' output**
$ ps aux | grep 'php-fpm'
irnbru           59029   0.0  0.0  4495996   3392   ??  S    10:53am   0:35.89 /usr/local/opt/php@7.1/sbin/php-fpm --nodaemonize
irnbru           59028   0.0  0.0  4486964   3880   ??  S    10:53am   0:03.36 /usr/local/opt/php@7.1/sbin/php-fpm --nodaemonize
irnbru           59014   0.0  0.1  4478152   7032   ??  S    10:53am   0:00.23 /usr/local/opt/php@7.1/sbin/php-fpm --nodaemonize

However composer just stopped working. composer command hangs php and while composer commands is hanging, nginx also times out while connecting to php-fpm. When composer command is terminated, nginx works fine. It seems composer command is somehow hanging php.

Have reinstalled composer using 
brew install composer. I can see composer executable in /usr/local/bin.

**brew Doctor output**
$ brew doctor
Your system is ready to brew.

**brew config output**
 brew config
HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: c814199a791867ab75f90a22715e2475706b13d8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2a2996af5336f38c64b303872a69be13ed37ed6c
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_65
macOS: 10.13.5-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

**Comment by SMillerDev** [comment]
Is there any errors in the output if you increase the verbosity of composer during the commands?

**Comment by brainworker** [comment]
Hey,
Found the issue. It was being caused by Xdebugger. 

Thanks @SMillerDev for looking into it.
