### ISSUE TITLE
Incompatible library version: _snappy.so requires version 4.0.0 or later, but libsnappy.1.dylib provides version 1.0.0

### ISSUE THREAD

**Issue by SolomonSHY** [Homebrew/homebrew-core#29877]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Was trying to use Snappy as installed by Brew with python-snappy

- What happened (include command output)

`alembic upgrade head`

File "/Users/solomonsia/nuber-account-provisioner/env/lib/python2.7/site-packages/merckx/lib/protocol.py", line 9, in <module>
    import snappy
  File "/Users/solomonsia/nuber-account-provisioner/env/lib/python2.7/site-packages/snappy.py", line 45, in <module>
    from _snappy import CompressError, CompressedLengthError, \
ImportError: dlopen(/Users/solomonsia/nuber-account-provisioner/env/lib/python2.7/site-packages/_snappy.so, 2): Library not loaded: /usr/local/lib/libsnappy.1.dylib
  Referenced from: /Users/solomonsia/nuber-account-provisioner/env/lib/python2.7/site-packages/_snappy.so
  Reason: Incompatible library version: _snappy.so requires version 4.0.0 or later, but libsnappy.1.dylib provides version 1.0.0

- What you expected to happen

Expected the libsnappy.1.dylib downloaded from brew to be version 4.0.0 or later as required by _snappy.so.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install snappy`

**Comment by ilovezfs** [comment]
This is a problem with the dependent software not the Homebrew snappy formula. Please report it to whoever is distributing _snappy.so, which needs to be built again against the current version of libsnappy.
