### ISSUE TITLE
Jpeg

### ISSUE THREAD

**Issue by jamesashton20** [Homebrew/homebrew-core#29884]
hi tried to install brew jpeg dependancy getting SHA256 error...

> Downloading http://www.ijg.org/files/jpegsrc.v9c.tar.gz
Already downloaded: /Users/jamesashton/Library/Caches/Homebrew/jpeg-9c.tar.gz
Error: SHA256 mismatch
Expected: 650250979303a649e21f87b5ccd02672af1ea6954b911342ea491f351ceb7122
Actual: fdf900267092bc67bd7786b86c462e69f9ed52bed838809b6ba28b298be879f6
Archive: /Users/jamesashton/Library/Caches/Homebrew/jpeg-9c.tar.gz
To retry an incomplete download, remove the file above.

**Comment by ilovezfs** [comment]
Yes I'm looking for a good mirror. In the mean time you can use https://dl.bintray.com/homebrew/mirror/jpeg-9c.tar.gz and download it directly to your Homebrew cache in ~/Library/Caches/Homebrew

**Comment by jamesashton20** [comment]
Awesome! thanks! completely new to homebrew, so hitting snags, but learning, but thank you so so much for the quick response! :) James
