### ISSUE TITLE
mongodb - Error: undefined local variable or method `dep_f' for Homebrew:Module

### ISSUE THREAD

**Issue by kpmueller** [Homebrew/homebrew-core#29899]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

1) Install mongodb@3.2 on macos high sierra

2) Force link mongodb@3.2 formula when it's already linked. (as part of a script)

- What happened (include command output)

```brew link mongodb@3.2 --force

Error: undefined local variable or method `dep_f' for Homebrew:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:43:in `block in link'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:28:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:28:in `link'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

- What you expected to happen

It to succeed 

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install mongodb@3.2
brew link mongodb@3.2 --force
brew link mongodb@3.2 --force
```

**Comment by ilovezfs** [comment]
Fixed if you `brew update`. Thanks for reporting!

**Comment by kpmueller** [comment]
@ilovezfs thanks for fixing so fast!

**Comment by ilovezfs** [comment]
You're welcome!
