### ISSUE TITLE
Hugo is now (v0.43) partially CGO dependant

### ISSUE THREAD

**Issue by bep** [Homebrew/homebrew-core#29898]
See #29891

Also see https://discourse.gohugo.io/t/hugo-0-43-released/12814/21

This release adds, among many other things, SCSS/SASS support. Since this requires CGO (which requires a C/C++ installation, XCode on MacOS), it is hidden behind a build flag:

```bash
 go build -tags extended
```

For the release binaries on GitHub we now produce a double set. I'm not sure what Homebrew should do, but I suspect many would want the "extended" version.

**Comment by felicianotech** [comment]
I agree. I don't know how but I'd suggest the Brew formula to build Hugo v0.43 and on as the extended version. My PR updated the Hugo version but I don't know how to make it depend on CGO.

So if someone can mark this GitHub Issue as "Help Wanted". :smile:

**Comment by bep** [comment]
I can certainly create a PR if

1) This is OK with Brew (whoever that is)
2) @ilovezfs or someone else can confirm that this builds on a XCode-enabled MacOS builder?

**Comment by SMillerDev** [comment]
1. You're always free to make a pull requests, that's what keeps homebrew running after all.
2. Aren't the command line tools enough? Cause those can be guaranteed.

**Comment by SMillerDev** [comment]
Those are required to use homebrew so that should work then 😄
