### ISSUE TITLE
gawk has incorrect dependency on readline

### ISSUE THREAD

**Issue by michelemauro** [Homebrew/homebrew-core#29919]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Running `awk`.

- What happened (include command output)

```
mim$ awk
dyld: Library not loaded: /usr/local/Cellar/readline/7.0.3_1/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
Trace/BPT trap: 5

```

- What you expected to happen

```
mim$ awk
Usage: awk [POSIX or GNU style options] -f progfile [--] file ...
...
```

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade readline`

Gist logs AFTER repairing the problem:

```
mim$ brew gist-logs readline
https://gist.github.com/17d9272d6c7793c192c643a1586a7892
MacBook-Air-di-Michele:shootingplan mim$ brew gist-logs gawk
Error: No logs.
```

Caution: I am on macOS 10.9, I don't know if this is peculiar of this OS. It doesn't seem like it, however, but it could be my fault.

My take on this is that gawk 4.2.1:

```
air-di-michele:shootingplan mim$ brew info gawk
gawk: stable 4.2.1
```

has a somewhat hard dependency on readline 7.0.3_1. When readline is upgraded to 7.0.5, this link is broken. By reverting to the previous version, everything seems to be fine again.

If someone can verify this on a later OS, I hope my report have been helpful.
If this can be verified as not happening in a recent OS, I can live with it and this report can be immediately closed.

Thank you very much for your high-quality work.

**Comment by SMillerDev** [comment]
this should fix it: https://github.com/Homebrew/homebrew-core/pull/29921

**Comment by ilovezfs** [comment]
I'm not sure where that `awk` is from but it's not Homebrew's.

```
iMac-TMP:homebrew-core joe$ otool -L /usr/local/bin/awk
/usr/local/bin/awk:
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.5.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1259.20.0)
	/usr/local/opt/readline/lib/libreadline.7.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/mpfr/lib/libmpfr.6.dylib (compatibility version 7.0.0, current version 7.1.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by michelemauro** [comment]
@ilovezfs , on my system `awk` comes from Homebrew:

```
mim$ which awk
/usr/local/bin/awk
mim$ ls -la /usr/local/bin/awk
lrwxr-xr-x  1 mim  staff  28 26 Feb 15:44 /usr/local/bin/awk -> ../Cellar/gawk/4.2.1/bin/awk
```

**Comment by ilovezfs** [comment]
OK. Then I suggest you run `brew reinstall gawk`.

**Comment by ilovezfs** [comment]
@michelemauro did you run reinstall? What does otool show now?
