### ISSUE TITLE
Carthage macOS dependency

### ISSUE THREAD

**Issue by gusc** [Homebrew/homebrew-core#29923]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Running homebrew upgrade on macOS 10.11 (El Capitan) using Ansible - standard infrastructure management.

- What happened (include command output)

The upgrade step fails with a dependency error in carthage formula, because it depends on Xcode 9 which can be installed only on macOS 10.12+. It stops the rest of the upgrades.

Command output:
```
carthage: A full installation of Xcode.app 9.0 is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode 9.0 cannot be installed on macOS 10.11.
You must upgrade your version of macOS.
Error: An unsatisfied requirement failed this build.
```

- What you expected to happen

Don't upgrade Carthage (don't even propose to upgrade) as it's dependencies are not met and continue with the rest of the upgrades.
- Step-by-step reproduction instructions (by running `brew install` commands)

`brew update & brew upgrade`

- Solution:

Add `depends_on :macos => :sierra` to https://github.com/Homebrew/homebrew-core/blob/master/Formula/carthage.rb

**Comment by ilovezfs** [comment]
`depends_on :macos => :sierra` would be redundant and wouldn't change the exit code.
