### ISSUE TITLE
Issue with wxpython and wxmac. 

### ISSUE THREAD

**Issue by deepio** [Homebrew/homebrew-core#29938]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
install wxpython (any version from 2.8-3.0)

installation didn't fail, but the program itself does. installing wxpython, automatically installs wxmac. 

- What happened (include command output)

It installed without an issue, until you import wx in python. 

Tried `wxpython`, and `wxmac`.

`import wx` when having just `wxmac` installed => `ImportError: No module named wx`

`import wx` when having `wxpython` installed => 
```
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
```

- What you expected to happen
have wx work of course! ;P
- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install wxpython`
`python`
`import wx`

or 
`brew install wxmac`
`python`
`import wx`

**Comment by SMillerDev** [comment]
wxmac isn't a python module, it's this repo: https://github.com/wxWidgets/wxWidgets as for wxpython, you're probably better off installing it through pip: https://pypi.org/project/wxPython/

**Comment by deepio** [comment]
@SMillerDev No can do, needs to be the old and depricated version of wxPython, because I need to update another project that uses it to the latest wx.

**Comment by mistydemeo** [comment]
Just to check, is that warning fatal / terminating your program? Or is it just telling you about the mismatch?

**Comment by deepio** [comment]
Once wx is installed with brew or from source, the next step is to install the application(toolkit) that I need to update, which fails without wx. WX is a package to make GUIs on multiple platforms. I can build the toolkit without wx and use the toolkit. But the goal is to update the app to use the latest version of wx.

**Comment by mistydemeo** [comment]
I'm not sure I understand, I'm sorry. Here's my attempt at reproing, which works for me:

1. `brew install wxpython`
2. `python`
3. Run the following:

```
>>> import wx
/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py:16633: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
>>> app = wx.App()
>>> frame = wx.Frame(None, title='Test')
>>> frame.Show()
True
>>> app.MainLoop()
```

wxPython prints a warning, but it is not fatal - it still works, and I get the expected application window shown.

**Comment by deepio** [comment]
@mistydemeo You are right, problem must be elsewhere. Thank you for your time.
