### ISSUE TITLE
Trying to install shellcheck initiated a build from source rather than using the bottle

### ISSUE THREAD

**Issue by sitsofe** [Homebrew/homebrew-core#29973]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to install shellcheck

- What happened (include command output)

Rather than using the bottle shellcheck tried to build itself (and ghc) from source...

- What you expected to happen

Pre-built bottle to be used.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install shellcheck
```
This issue happened on two separate macOS 10.12 installs. However in both cases after stopping the source build and doing:
```
brew install ghc
```
The bottle for ghc was found. Once this was installed doing
```
brew install shellcheck
```
quickly found and installed the bottle. Attaching log:
[homebrew-log.txt](https://github.com/Homebrew/homebrew-core/files/2184204/homebrew-log.txt)

**Comment by SMillerDev** [comment]
You seem to be having the same issue reported here: https://discourse.brew.sh/t/url-malformed-download-from-bottles-failed/2537/8
