### ISSUE TITLE
Librdkafka: version is not the latest to match *nix and Win distros 0.11.4 < 0.11.5

### ISSUE THREAD

**Issue by jefh** [Homebrew/homebrew-core#29984]
Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by ilovezfs** [comment]
0.11.4 is the current release.

**Comment by SMillerDev** [comment]
> To get formulae added or changed in Homebrew please file a Pull Request
