### ISSUE TITLE
mysql doesn't shut down daemon on uninstall

### ISSUE THREAD

**Issue by rdp** [Homebrew/homebrew-core#29995]
- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/ba3bb98c591603439ecda90263aefe2e

To help us debug your issue please explain:
- What you were trying to do (and why)
remove mysql
- What happened (include command output)
removal occurred but daemon continued
- What you expected to happen
daemon should have been shutdown
- Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install mysql
$ brew services start mysql
$ brew remove mysql

now do a ps, note that the database daemon is still running...even though files have been removed from under it...

**Comment by rdp** [comment]
darn, so close to lucky issue no. 30000 ... :)

**Comment by rdp** [comment]
It's not really stale but I'll let it go that way since I don't personally plan on fixing it :)

**Comment by rakkesh** [comment]
@rdp as this issue is related to all formulae with a `service` available, it need to be resolved in [brew](https://github.com/Homebrew/brew). Suggest you to file an issue at https://github.com/Homebrew/brew/issues

**Comment by MikeMcQuaid** [comment]
This is expected behaviour, sorry.
