### ISSUE TITLE
vim: :py3file causes a DeprecationWarning

### ISSUE THREAD

**Issue by dancek** [Homebrew/homebrew-core#30013]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

---

I received [a bug for a Vim plugin I maintain](https://gitlab.com/code-stats/code-stats-vim/issues/6) and started investigating. Turns out the current version of Vim from Homebrew prints a warning whenever the `:py3file` command is used.

An easy way to reproduce:

1. `brew install vim`
2. `touch empty.py`
3. `vim --cmd "py3file empty.py" --cmd quit`

The output I get is the following:

```
Error detected while processing pre-vimrc command line:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

The output should be empty. On Arch Linux it is, so this might not be a Vim bug. They have Python 3.6.6 though, while Homebrew has 3.7.0. Not sure if that matters; `imp` has been deprecated since 3.4.

Here's the gist-logs link: https://gist.github.com/b507ebda487967837f76f14dce38dbbf

**Comment by ilovezfs** [comment]
This is an issue for upstream to resolve with Python 3.7.

**Comment by ilovezfs** [comment]
See https://github.com/vim/vim/issues/3117

**Comment by ilovezfs** [comment]
@dancek This is now fixed in https://github.com/Homebrew/homebrew-core/pull/30357
