### ISSUE TITLE
Formula request: ConTeXt

### ISSUE THREAD

**Issue by nitrocode** [Homebrew/homebrew-core#30018]
I hope this is the right area to request formulae.

I wrote up this issue https://github.com/Homebrew/brew/issues/4443#issuecomment-403705226 and was recommended to post the request here.

In short, there is a mac shell script

```
mkdir $HOME/context
cd $HOME/context
rsync -av rsync://contextgarden.net/minimals/setup/first-setup.sh .
sh ./first-setup.sh --modules=all --engine=luatex
```

That I'd like to replace with `brew install context`

Thank you!

**Comment by commitay** [comment]
To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
