### ISSUE TITLE
Pulseaudio formula is broken on latest OSX it seems.

### ISSUE THREAD

**Issue by allnash** [Homebrew/homebrew-core#30062]
I am on OSX 10.13.5 (17F77)

Here is the Error:

```

parec -d "$MONITOR" | sox -t raw -r 44100 -sLb 16 -c 2 - ~/Taped_Recording_$TIME.wav

W: [] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

Please verify this formula again. Email me or comment on this issue if I can help you debug in any way.

Thanks.

**Comment by SMillerDev** [comment]
Can you fill out the issue template please? It's really required to allow us to debug things.

**Comment by ilovezfs** [comment]
In addition to completing the template, please `brew upgrade` because pulseaudio 12.1 was just released.

**Comment by iMichka** [comment]
Yes, please run `brew upgrade`. If it still fails, please open a new issue for the new version of `pulseaudio`, and fill out the issue template. Thanks.

**Comment by allnash** [comment]
ok works now.
