### ISSUE TITLE
Wrong description for "aterm" formula

### ISSUE THREAD

**Issue by jsmaniac** [Homebrew/homebrew-core#30098]
Commit 758f6e95332ffdb89a2ecf802bbd2cf045816985 added a description to a lot of formulas, but the one for the  `aterm` formula is wrong.

The current description for the `aterm` formula lists it as the "AfterStep terminal emulator".

The AfterStep terminal emulator resides at http://www.afterstep.org/aterm.php, but the software packaged in this formula comes from https://strategoxt.org/Tools/ATermFormat, which seems to be the "ATerm (Annotated Term) Format", and apparently has nothing to do with the terminal emulators.

**Comment by SMillerDev** [comment]
Good catch, could you make a pull request to change it to the correct description?
