### ISSUE TITLE
opencolorio: won't build "--with-java" enabled

### ISSUE THREAD

**Issue by kangstarr** [Homebrew/homebrew-core#3010]
### Bug reports:
When installing opencolorio with the "--with-java" parameter it constantly fails.

brew gist-logs opencolorio
https://gist.github.com/a3f81ea911c5f70176f19ecb6a9a7c51

$ brew reinstall ocio --with-docs --with-python --with-java
==> Reinstalling opencolorio with --with-docs, --with-python, --with-java
==> Downloading https://github.com/imageworks/OpenColorIO/archive/v1.0.9.tar.gz
Already downloaded: /Users/architech/Library/Caches/Homebrew/opencolorio-1.0.9.tar.gz
==> Downloading https://github.com/imageworks/OpenColorIO/commit/ebd6efc036b6d0b17c869e3342f17f9c5ef8bbfc.diff
Already downloaded: /Users/architech/Library/Caches/Homebrew/opencolorio--patch-eab670cdd0278c610ecd6c059cb12f3042395d474259ddd18b7b8e242ad82810.diff
==> Patching
==> Applying ebd6efc036b6d0b17c869e3342f17f9c5ef8bbfc.diff
patching file export/OpenColorIO/OpenColorABI.h.in
patching file export/OpenColorIO/OpenColorIO.h
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/opencolorio/1.0.9 -DCMAKE_BUILD
==> make
Last 15 lines from /Users/architech/Library/Logs/Homebrew/opencolorio/02.make:
[ 87%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyGroupTransform.cpp.o
[ 87%] Linking CXX executable ociobakelut
[ 87%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyLogTransform.cpp.o
[ 87%] Built target ociobakelut
[ 88%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyLook.cpp.o
[ 88%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyLookTransform.cpp.o
[ 89%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyMain.cpp.o
[ 89%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyMatrixTransform.cpp.o
[ 89%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyProcessor.cpp.o
[ 90%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyProcessorMetadata.cpp.o
[ 90%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyTransform.cpp.o
[ 91%] Building CXX object src/pyglue/CMakeFiles/PyOpenColorIO.dir/PyUtil.cpp.o
[ 91%] Linking CXX shared module PyOpenColorIO.so
[ 91%] Built target PyOpenColorIO
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

**Comment by dunn** [comment]
I can reproduce this.  Would you mind reporting this to the developers?  It seems like an upstream bug.

**Comment by MikeMcQuaid** [comment]
Closing out upstream issues.
