### ISSUE TITLE
brew search yields 'Error: 'pt_PT' cannot be parsed to a Locale'

### ISSUE THREAD

**Issue by ohjho** [Homebrew/homebrew-core#30124]
- What you were trying to do (and why)
Try to do `brew search` to look for new packages
for example I did `brew search chrome`
- What happened (include command output)
did `brew cask install chrome` which worked but after that `brew search` doesn't work:
`Error: 'pt_PT' cannot be parsed to a Locale  
Please report this bug:  
  https://docs.brew.sh/Troubleshooting  
/usr/local/Homebrew/Library/Homebrew/locale.rb:15:in `parse'  
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:141:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl.rb:141:in `language_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:37:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:31:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:67:in `cask'
/usr/local/Homebrew/Library/Homebrew/compat/hbc/cask_loader.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:113:in `cask'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/battle-net.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:57:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:20:in `block in each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask.rb:19:in `each'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:26:in `select'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:26:in `search_string'
/usr/local/Homebrew/Library/Homebrew/searchable.rb:7:in `search'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/search.rb:29:in `search_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/search.rb:83:in `search'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
`
- What you expected to happen
i expected brew search to give results
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install  
brew update  
brew cask search chrome`

**Comment by SMillerDev** [comment]
@ilovezfs this seems more like a brew issue than a core issue right?

**Comment by ilovezfs** [comment]
Yes and would need template completed.

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew is the place for issues like this, as has been stated.
