### ISSUE TITLE
Brew install local formula Fails - keepass-cli

### ISSUE THREAD

**Issue by gopinath-langote** [Homebrew/homebrew-core#30152]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
 --> I am trying to create new formula locally & install it on my machine via brew
- What happened (include command output)
--> 
Getting Following Error
```
Getting Updating Homebrew...
==> Downloading https://github.com/gopinath-langote/keepass-cli/archive/1.0.tar.gz
Already downloaded: /Users/gopinathlangote/Library/Caches/Homebrew/keepass-cli-1.0.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/keepass-cli/1.0
Last 15 lines from /Users/gopinathlangote/Library/Logs/Homebrew/keepass-cli/01.configure:
2018-07-17 12:45:24 +0530

./configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/usr/local/Cellar/keepass-cli/1.0


READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen
--> I should be able to install formula
- Step-by-step reproduction instructions (by running `brew install` commands)
--> Run `brew install`

# Gist Link
https://gist.github.com/6a9bdc64999990aa1b4a4a1526e1a078

**Comment by SMillerDev** [comment]
You can't call a configure script that isn't there, your repo 
https://github.com/gopinath-langote/keepass-cli is missing the files you're trying to execute.

**Comment by gopinath-langote** [comment]
@SMillerDev 
Thanks for the response. I want to understand what configure script do.

So that I can decide whether to add configure script or not.

**Comment by SMillerDev** [comment]
https://robots.thoughtbot.com/the-magic-behind-configure-make-make-install
