### ISSUE TITLE
high sierra 10.13.6

### ISSUE THREAD

**Issue by atisdi** [Homebrew/homebrew-core#30167]
Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by ilovezfs** [comment]
@atisdi did you need something?
