### ISSUE TITLE
imagemagick 6.9.5-2 fails to build on 10.11.5 with xcode 8.0 command line tool.

### ISSUE THREAD

**Issue by dchammond** [Homebrew/homebrew-core#3019]
# General steps:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

```
imagemagick (6.9.5-0 < 6.9.5-2)
==> Upgrading 1 outdated package, with result:
imagemagick 6.9.5-2
==> Upgrading imagemagick
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.5-2.tar.xz
######################################################################## 100.0%
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/6.9.5-2 --disable-silent-rules --enable-shared --enable-static --with-modules --enable-openmp --enable-hdri=yes --enable-fftw=yes --with-openjp2 --with-quantum-depth=32 --with-rsvg --wit
Last 15 lines from /Users/Dillon/Library/Logs/Homebrew/imagemagick/01.configure:
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
configuring ImageMagick 6.9.5-2
checking whether build environment is sane... yes
checking for style of include used by make... GNU
checking for gcc... gcc-6
checking whether the C compiler works... no
configure: error: in `/private/tmp/imagemagick-20160713-64666-twify2/ImageMagick-6.9.5-2':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
imagemagick 7.0.2-1 https://github.com/Homebrew/homebrew-core/pull/2209
Upgrade: ImageMagick 7.0.x-y https://github.com/Homebrew/homebrew-core/issues/1828
imagemagick 6.9.5-2 fails to build on 10.12 PB1 with Xcode 8.0 https://github.com/Homebrew/homebrew-core/issues/2962
```

I had this same exact bug with imagemagick 6.9.5-1.

Out put of `brew gist-logs imagemagick`

https://gist.github.com/dchammond/a7fc44edafff4ac518ac81aed7915ac8

I installed imagemagick as so: `brew install imagemagick --with-fftw --with-fontconfig --with-ghostscript --with-hdri --with-jp2 --with-librsvg --with-libwmf --with-little-cms --with-little-cms2 --with-openexr --with-openmp --with-pango --with-quantum-depth-32 --with-webp --with-x11`

@DomT4

**Comment by zmwangx** [comment]
You're compiling with gcc 6.1.0 from Homebrew rather than clang 8.0 from Xcode 8 beta. Could you unlink gcc (`brew unlink gcc`) and try again?

By the way, from [`config.log`](https://gist.github.com/dchammond/a7fc44edafff4ac518ac81aed7915ac8#file-config-log-L162)

```
configure:5180: gcc-6    conftest.c  >&5
ld: library not found for -lSystem
```

so `ld` can't seem to `/usr/lib/libSystem.dylib`.

**Comment by DomT4** [comment]
It's worth mentioning that using Xcode 8 on 10.11, whilst technically supported by Apple, is a _"Really Bad Idea"_ ™️.

It's proving to be harder to unbreak Xcode 8 with OS X 10.11 than it has been with macOS 10.12 so far. I really, _really_ recommend people don't bother, at least till Xcode 8 is a bit further along the development path.

**Comment by dchammond** [comment]
@zmwangx 
Unfortunately unlink gcc did not work, it produced the same set of errors.

In addition, why is `libSystem.dylib` missing? Is that because of my newer Xcode version?

@DomT4 

I definitely get what you are saying and in all honesty I'm not surprised if a bunch of my packages can't upgrade until Sierra is actually released publicly.  Funny enough, I believe the reason I switched to Xcode 8 was to fix another package (though I can't remember which one.)

**Comment by MikeMcQuaid** [comment]
Not sure how we can help here I'm afraid so closing out.
