### ISSUE TITLE
Cannot tap brewsci/science (Mac OS 10.13.3)

### ISSUE THREAD

**Issue by vvirkki** [Homebrew/homebrew-core#30222]
I'm trying to install saga-gis formula on my Mac 10.13.3 through Homebrew. However, once the formula starts tapping brewsci/science, I get a stack of errors about invalid formulas. I've tried the usual troubleshooting steps but the error persists. My brew config and brew doctor are attached in https://gist.github.com/vvirkki/7e1b9ccd4b89484e0db092397cd94846

brewsci/science (https://github.com/brewsci/homebrew-science) seems to be deprecated maybe around six months ago and my OS seems to be released in January. Maybe the deprecation has broken something and now it's impossible to tap this package?

My only command to produce errors is brew tap brewsci/science

Vilis-MacBook-Air:hydrostreamer vvirkki$ brew tap brewsci/science
==> Tapping brewsci/science
Cloning into '/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science'...
remote: Counting objects: 468, done.
remote: Compressing objects: 100% (465/465), done.
remote: Total 468 (delta 1), reused 153 (delta 1), pack-reused 0
Receiving objects: 100% (468/468), 429.98 KiB | 967.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-xml.rb
uninitialized constant #<Class:0x000000010209fdc8>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-files.rb
uninitialized constant #<Class:0x00000001015f5058>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/osgearth.rb
uninitialized constant #<Class:0x00000001016377a0>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/ome-common.rb
uninitialized constant #<Class:0x0000000101dee548>::MinimumMacOSRequirement
Did you mean?  MaximumMacOSRequirement
Error: Cannot tap brewsci/science: invalid syntax in tap!

**Comment by ilovezfs** [comment]
Sorry https://github.com/brewsci/homebrew-science is not supported by the Homebrew organization so you'll need to report this there.
