### ISSUE TITLE
mysql (and flavors) readline keybindings not working

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-core#30230]
The key combinations do not work with `mysql` client:
- `^R` (ctrl+r) - reverse history search - `reverse-search-history`
- `M-<BACKSPACE>` (alt+backspace) - `backward-kill-word` 

but these do not work when launching `mysql`, but work fine with `bash` (brew version):

```
➔ bind -p | grep -E 'reverse-search-history|backward-kill-word'
"\e\C-h": backward-kill-word
"\e\C-?": backward-kill-word
# non-incremental-reverse-search-history (not bound)
# non-incremental-reverse-search-history-again (not bound)
"\C-r": reverse-search-history
# shell-backward-kill-word (not bound)
➔ which bash
/usr/local/bin/bash
➔ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
```

```
➔ which mysql
/usr/local/bin/mysql
➔ mysql --version
mysql  Ver 14.14 Distrib 5.7.22-22, for osx10.13 (x86_64) using  EditLine wrapper
```

tested with `mysql` client coming from following packages:
- `mysql`
- `percona-server`

**Comment by apjanke** [comment]
It looks like the current version of MySql, at least in Homebrew, is built with libedit/editline instead of readline.

https://stackoverflow.com/questions/20363737/mysql-reverse-i-search
https://bugs.mysql.com/bug.php?id=60465

> The key binding can be set via the ~/.editrc file by adding the following line: "bind "^R" em-inc-search-prev". See man editrc for more details.

**Comment by apjanke** [comment]
My impression is that upstream favors libedit because of the license. MySQL dual-licenses under GPL and a commercial license, and the GPL readline is not compatible with their commercial license.

Homebrew tries to stick closely to upstream's decisions and defaults.
