### ISSUE TITLE
node-build not integrated with ndenv

### ISSUE THREAD

**Issue by philipmw** [Homebrew/homebrew-core#30245]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

[ndenv](https://github.com/riywo/ndenv) supports integration with [node-build](https://github.com/riywo/node-build) to install Node versions. The ndenv formula installs node-build as a dependency. However, ndenv itself does not find node-build.

- What happened (include command output)

````
% ndenv
ndenv 0.4.0
Usage: ndenv <command> [<args>]

Some useful ndenv commands are:
   commands    List all available ndenv commands
   local       Set or show the local application-specific Node version
   global      Set or show the global Node version
   shell       Set or show the shell-specific Node version
   rehash      Rehash ndenv shims (run this after installing executables)
   version     Show the current Node version and its origin
   versions    List all Node versions available to ndenv
   which       Display the full path to an executable
   whence      List all Node versions that contain the given executable
````

- What you expected to happen

````
f% ndenv
ndenv 0.4.0
Usage: ndenv <command> [<args>]

Some useful ndenv commands are:
   commands    List all available ndenv commands
   local       Set or show the local application-specific Node version
   global      Set or show the global Node version
   shell       Set or show the shell-specific Node version
   install     Install a Node version using the node-build plugin
   uninstall   Uninstall a specific Node version
   rehash      Rehash ndenv shims (run this after installing executables)
   version     Show the current Node version and its origin
   versions    List all Node versions available to ndenv
   which       Display the full path to an executable
   whence      List all Node versions that contain the given executable
````

I got this output by installing `node-build` manually as per its README.

- Step-by-step reproduction instructions (by running `brew install` commands)

* `brew install ndenv`
* `ndenv`
* `git clone https://github.com/riywo/node-build.git $(ndenv root)/plugins/node-build`
* `ndenv`

````

**Comment by DomT4** [comment]
Go away bot, it's on my list of things to look at.

**Comment by igas** [comment]
Interesting. I think I found the problem. While we have:
```
depends_on "node-build" => :recommended
```
In `ndenv` formula. It's actually not the right one.

https://github.com/riywo/node-build is the one that `ndenv` expects (`ndenv-install`, `ndenv-uninstall`) and looks in path, while `node-build` formula is https://github.com/nodenv/node-build which installs `nodenv-install` & `nodenv-uninstall`. Note missing **O** in the first set.
