### ISSUE TITLE
feh ERROR: Can't open X display. It *is* running, yeah?

### ISSUE THREAD

**Issue by aurquiel** [Homebrew/homebrew-core#30287]
i am ussing ubuntu 18.04 server version fresh install, i installed feh in order to test the viewing of an image in the terminal, gnome terminal, but after the installation of feh when i run "feh imageName.jpg" the following output has appeared "feh ERROR: Can't open X display. It *is* running, yeah?"

**Comment by commitay** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Issues with Linuxbrew formulae should be reported here: 
https://github.com/Linuxbrew/homebrew-core/issues
