### ISSUE TITLE
No default my.cnf

### ISSUE THREAD

**Issue by Paul-Morris** [Homebrew/homebrew-core#30286]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ yes ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ no ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ yes ] ran `brew update` and can still reproduce the problem?
- [ yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ yes ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

```
Default options are read from the following files in the given order:
/etc/my.cnf /etc/mysql/my.cnf /usr/local/etc/my.cnf ~/.my.cnf 

```
Added my own my.cnf for custom settings in mysql!

- What happened (include command output)

```
Paul@iMac.local:/usr/local/Cellar/mysql/5.7.22$brew services list
Name    Status  User Plist
httpd   started Paul /Volumes/osx/Users/Paul/Library/LaunchAgents/homebrew.mxcl.httpd.plist
mysql   error   Paul /Volumes/osx/Users/Paul/Library/LaunchAgents/homebrew.mxcl.mysql.plist
```

There is no default my.cnf (my-default.cnf) anywhere that I can find. Shouldn't it be in support-files?  Not sure if this is by design but I don't know what to put in it to correct mysql startup problems

- What you expected to happen
Expected to see:

An included my.cnf (my-default.cnf) example that I can copy into my mysql server to adjust settings.

- Step-by-step reproduction instructions (by running `brew install` commands)

1. Create a my.cnf in /usr/local/Cellar/mysql/5.7.22

2. I added this because it was in my osx mysql my.cnf but it doesn't work:

```
Default Homebrew MySQL server config
[mysqld]
# Only allow connections from localhost
bind-address = 127.0.0.1
```

3. Restart homebrew mysql with "brew services restart mysql"

4. brew services list will now show red beside the mysql service indicating a startup error

5. had to delete my.cnf to fix it!

**Comment by ilovezfs** [comment]
At least with the current bottle, `brew install mysql` does indeed install my.cnf
```
bash-3.2$ ls -l /usr/local/etc/my.cnf
ls: /usr/local/etc/my.cnf: No such file or directory
bash-3.2$ brew install mysql
==> Downloading https://homebrew.bintray.com/bottles/mysql-8.0.12.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mysql--8.0.12.high_sierra.bottle.tar.gz
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

To have launchd start mysql now and restart at login:
  brew services start mysql
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql/8.0.12: 255 files, 233.0MB
bash-3.2$ ls -l /usr/local/etc/my.cnf
-rw-r--r--  1 joe  admin  113 Aug  6 23:36 /usr/local/etc/my.cnf
bash-3.2$ 
```
