### ISSUE TITLE
llvm 3.8.0 fails to upgrade on 10.11.5 with Xcode 8.0 command line tools

### ISSUE THREAD

**Issue by dchammond** [Homebrew/homebrew-core#3030]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

```
==> Upgrading 1 outdated package, with result:
llvm 3.8.0
==> Upgrading llvm
==> Downloading http://llvm.org/releases/3.8.0/llvm-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/cfe-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/clang-tools-extra-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/libcxx-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/lld-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/libunwind-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/openmp-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/polly-3.8.0.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.0/compiler-rt-3.8.0.src.tar.xz
######################################################################## 100.0%
==> cmake -G Unix Makefiles /private/tmp/llvm-20160715-37545-losdj6/llvm-3.8.0.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/llvm/3.8.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOS
==> make
Last 15 lines from /Users/Dillon/Library/Logs/Homebrew/llvm/02.make:
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(trampoline_setup.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(addtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(divtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(multf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(trampoline_setup.c.o) has no symbols
[ 55%] Built target clang_rt.cc_kext_x86_64_osx
[ 55%] Built target clang_rt.cc_kext_x86_64h_osx
make[3]: *** [all] Error 2
make[2]: *** [tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
make[1]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
llvm: openmp/clang changes https://github.com/Homebrew/homebrew-core/pull/3028
llvm and openmp https://github.com/Homebrew/homebrew-core/issues/1254
```

`brew gist-logs llvm`
https://gist.github.com/dchammond/097d0e82d1af9354fa2d612625df845f

`llvm` was installed with `--with-clang`

**Comment by pkryger** [comment]
The same thing happens with on clang 7.3: https://gist.github.com/pkryger/2ec0f7da78e25c676358eb84c9ec2479

**Comment by jinyuanxie** [comment]
Also fails to upgrade on 10.11.6 with XCode 8.0

https://gist.github.com/jinyuanxie/ed24dc86217a225761203aabb6be6714

**Comment by ilovezfs** [comment]
I suggest you just switch to the bottle since `--with-clang` is now the default, so it's already included in the bottle.

@xu-cheng @UniqMartin any way we can stop old `--with-clang` options from unnecessarily triggering source builds? It seems options that are already the default should be filtered out from the install receipt in upgrade (and reinstall).

**Comment by UniqMartin** [comment]
> any way we can stop old `--with-clang` options from unnecessarily triggering source builds?

I was hoping this was already the case. I guess unused options are dropped if they are removed from the formula and deprecated options are for sure remapped to their new name, but it's quite possible the code isn't handling the case where the default changes, i.e. `--with-lang` becomes `--without-clang`. I'd have to take a closer look …

**Comment by ilovezfs** [comment]
default on -> default off
default on -> non-optional dependency
default off -> default on
default off -> non-optional dependency

I think none of those cases are handled.

**Comment by ilovezfs** [comment]
@UniqMartin https://github.com/Homebrew/brew/blob/4b2c4ef25835a87b5bac4fb26eae91dbfed93863/Library/Homebrew/formula_installer.rb#L86 looks problematic :)

**Comment by UniqMartin** [comment]
@ilovezfs I think that part of the code is fine, but what might need some tweaking is the code that is responsible for populating those `options`. Sadly, it doesn't seem like I'm finding the time to take a closer look …

**Comment by DomT4** [comment]
Can people retry after a `brew update`? Rewrote a blob of the formula with the `3.8.1` LLVM upgrade.

**Comment by dchammond** [comment]
@DomT4 

Ran `brew update` twice and tried to upgrade to llvm 3.8.1... no luck so far :(

```
==> Upgrading 1 outdated package, with result:
llvm 3.8.1
==> Upgrading llvm
==> Downloading http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/cfe-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/clang-tools-extra-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/openmp-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/libcxx-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/lld-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/polly-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/libunwind-3.8.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.8.1/compiler-rt-3.8.1.src.tar.xz
######################################################################## 100.0%
==> cmake -G Unix Makefiles /private/tmp/llvm-20160717-29186-1mx8be4/llvm-3.8.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/llvm/3.8.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBO
==> make
Last 15 lines from /Users/Dillon/Library/Logs/Homebrew/llvm/02.make:
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(multf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(trampoline_setup.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(addtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(divtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(multf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(trampoline_setup.c.o) has no symbols
[ 55%] Built target clang_rt.cc_kext_x86_64h_osx
make[3]: *** [all] Error 2
make[2]: *** [tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
make[1]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
make: *** [all] Error 2
```

New Gist-Log

https://gist.github.com/968e0b34a861c4ebedb2244c383633a2

**Comment by ilovezfs** [comment]
Perhaps one of you can try this in an empty brew installation with a freshly created dummy user account. Since this doesn't seem to impact our build bot, I suspect something is different in your environment or Cellar, etc. even if we haven't identified exactly what that is yet.

**Comment by maxim-belkin** [comment]
From the logs:
1. Homebrew build logs for llvm on Mac OS X 10.11.5
2. `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`
3. `/tmp/llvm-20160717-29186-1mx8be4/llvm-3.8.1.src/projects/compiler-rt/lib/builtins/eprintf.c:14:10: fatal error: 'stdio.h' file not found`

So, you are on 10.11.5, using SDK for 10.12.
Can you post the result of `locate stdio.h`?

**Comment by dchammond** [comment]
@maxim-belkin https://gist.github.com/fd9b0a26306331bebaf78ef409f622f6

**Comment by maxim-belkin** [comment]
So, the problem is the following: in your Xcode MacOSX SDK is in:
`/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/`. Note **no** extra `10.12` after MacOSX. 
To Homebrew this means that SDK version is `nil` (`os/mac/sdk.rb`), so it somehow defaults to the similar path with `...MacOSX10.12.sdk/` at the end (note line `SDKROOT: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk` 
).
So, the question how to fix this is for Homebrew developers ( @UniqMartin @MikeMcQuaid @DomT4 )

**Comment by TheAifam5** [comment]
```
Last 15 lines from /Users/theaifam5/Library/Logs/Homebrew/llvm/03.make:
      DNBThreadSetRegisterValueByID(int, unsigned long long, unsigned int, unsigned int, DNBRegisterValue const*) in DNB.cpp.o
  "MachProcess::GetNumSupportedHardwareWatchpoints() const", referenced from:
      DNBWatchpointGetNumSupportedHWP(int) in DNB.cpp.o
  "CFBundle::CopyExecutableURL() const", referenced from:
      DNBResolveExecutablePath(char const*, char*, unsigned long) in DNB.cpp.o
  "_debugserverVersionNumber", referenced from:
      RNBRemote::HandlePacket_qGDBServerVersion(char const*) in RNBRemote.cpp.o
  "_debugserverVersionString", referenced from:
      ASLLogCallback(void*, unsigned int, char const*, __va_list_tag*) in debugserver.cpp.o
      _main in debugserver.cpp.o
ld: symbol(s) not found for architecture x86_64
```
command:
```
brew install --with-toolchain --with-shared-libs --with-python --with-lldb --with-libcxxabi --with-all-targets --universal llvm
```

**Comment by UniqMartin** [comment]
> So, the problem is the following: in your Xcode MacOSX SDK is in:

I'm not sure what the true issue is, but this is most certainly not the cause of the trouble. Apple has indeed changed their SDK path to a version-agnostic name, i.e. `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` (that's why the `locate` results print this path), but they continue to provide a symbolic link under `/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk`, thus things should continue to work unless some build system resolves this to a canonical path and then trips over the missing version number in the result.

I'm wondering for how long Apple is planning to keep the symbolic link around. If the answer isn't “indefinitely”, we're probably well advised to tweak our SDK lookup logic.

> Why not just use official version from: http://llvm.org/releases/download.html
> (LLVM 3.8.0)

In its core, Homebrew is a from-source package manager, that just happens to provide binaries for the default build configuration (no options specified). For a formula to be included in homebrew/core it needs to build from source or to be provided in a platform-agnostic form (like a Java JAR file). Relying on upstream binaries creates also a fair amount of practical problems, e.g. we no longer have an influence on the build environment, unclear and possibly limiting support for different macOS versions, and sometimes also simple things like delayed release of upstream binaries (notice that at the time of writing there are no 3.8.1 binaries for macOS).

**Comment by ELLIOTTCABLE** [comment]
I'm running into this too, unfortunately:

Logs for `brew install llvm --with-all-targets --with-graphviz --with-lldb --with-ocaml --with-python --with-shared-libs --with-toolchain`: https://gist.github.com/ELLIOTTCABLE/5d4c3efcf6ea27ba57c28cf49c70bfd8

**Comment by UniqMartin** [comment]
@ELLIOTTCABLE You seem to be running Xcode 7.3.1, so this doesn't exactly match the issue title. You're seeing similar errors to @TheAifam5. I'm not able to debug this at the moment, but you could try going back to an installation without options and then start adding the options one after another until one of the options causes the build to fail. That would help with identifying which option (and thus which part of LLVM) is causing the build to fail.

**Comment by timotheecour** [comment]
ping: just ran into this issue (brew install llvm fails on OSX 10.11.6

**Comment by ilovezfs** [comment]
>If the answer isn't “indefinitely”, we're probably well advised to tweak our SDK lookup logic.

Maybe simplest answer in the short term at least would be to resolve to canonical path and grab version info directly from the plist.

**Comment by ilovezfs** [comment]
Try without the lldb option.

**Comment by pbrumm** [comment]
@dchammond  did you get this resolved?   My output looks exactly like yours.  I have tried a few different options for llvm and with none.

```
brew install llvm
==> Using the sandbox
==> Downloading http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/cfe-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--clang-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/clang-tools-extra-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--clang-extra-tools-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/openmp-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--openmp-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/libcxx-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--libcxx-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/libunwind-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--libunwind-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/lld-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--lld-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/polly-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--polly-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/compiler-rt-3.8.1.src.tar.xz
Already downloaded: /opt/boxen/cache/homebrew/llvm--compiler-rt-3.8.1.tar.xz
==> cmake -G Unix Makefiles /private/tmp/llvm-20160829-38506-bpeze4/llvm-3.8.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/opt/boxen/homebrew/Cellar/llvm/3.8.1 -DCMAKE_BUILD_TYPE=Rele
==> make
Last 15 lines from /Users/pbrumm/Library/Logs/Homebrew/llvm/02.make:
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(multf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(trampoline_setup.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(addtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(divtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(multf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.cc_kext_x86_64h_osx.a(trampoline_setup.c.o) has no symbols
[ 55%] Built target clang_rt.cc_kext_x86_64h_osx
make[3]: *** [all] Error 2
make[2]: *** [tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
make[1]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
llvm: fix build on >= El Capitan https://github.com/Homebrew/homebrew-core/pull/3076
llvm 3.8.0 fails to upgrade on 10.11.5 with Xcode 8.0 command line tools https://github.com/Homebrew/homebrew-core/issues/3030
```


https://gist.github.com/anonymous/9d431237701e0761da9e12d3217131f2

**Comment by dchammond** [comment]
@pbrumm The only way I fixed it was by completely uninstalling the Xcode 8 beta and reverting to 7.3.1 with the 7.3.1 command line tools.

**Comment by pbrumm** [comment]
Actually looking it at my xcode is 7.3.1 so the error is the same but downgrading wouldn't help.

gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by apjanke** [comment]
I'm having what looks like a similar problem on OS X 10.11.6 with Xcode 7.3.1. I'm adding it to this thread since it matches at least some of the users' issues here; let me know if I should break this out in to a separate non-Xcode-8 issue.

I'm doing a plain `brew install -s llvm` with no options, and getting that `'stdio.h' file not found` error.

Command: `HOMEBREW_MAKE_JOBS=1 brew install -v --build-from-source llvm`
Build logs: https://gist.github.com/eb09592cc1d6a94ca4562f7d9fdd742e

It fails during the `compiler-rt` component.

Excerpt with error:

```
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    COMPILER_RT_PREFIX
    COMPILER_RT_SRC_ROOT


-- Build files have been written to: /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-bins
cd /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-bins && /usr/local/Cellar/cmake/3.6.1/bin/cmake -E touch /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-stamps//compiler-rt-configure
[ 87%] Cleaning compiler-rt...
cd /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-bins && /Library/Developer/CommandLineTools/usr/bin/make clean
cd /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-bins && /usr/local/Cellar/cmake/3.6.1/bin/cmake -E touch /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-stamps//compiler-rt-clean
[ 87%] Performing build step for 'compiler-rt'
cd /tmp/llvm-20160901-33556-1jq16jw/tools/clang/runtime/compiler-rt-bins && /Library/Developer/CommandLineTools/usr/bin/make
Scanning dependencies of target clang_rt.eprintf
[  0%] Building C object lib/builtins/CMakeFiles/clang_rt.eprintf.dir/eprintf.c.o
clang-3.8: warning: no such sysroot directory: '-mmacosx-version-min=10.5'
/tmp/llvm-20160901-33556-j22nxu/llvm-3.8.1.src/projects/compiler-rt/lib/builtins/eprintf.c:14:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make[5]: *** [lib/builtins/CMakeFiles/clang_rt.eprintf.dir/eprintf.c.o] Error 1
make[4]: *** [lib/builtins/CMakeFiles/clang_rt.eprintf.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
make[1]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
make: *** [all] Error 2
```

Weird warning about the sysroot that looks like an option; may be a command line getting messed up in there.

Also looks like maybe the subordinate `make` command isn't being verbose and echoing the commands it's running. Anyone know an easy way to pass a flag to the subordinate `cmake` or `make` to get it to be verbose?

**Comment by apjanke** [comment]
Build with `brew install -s llvm --without-compiler-rt` got rid of the error for me; I think that localizes it to compiler-rt, at least for the one I'm encountering.

**Comment by maxim-belkin** [comment]
The gist-logs don't have the excerpt that you posted.

**Comment by apjanke** [comment]
Did you download the gist or view it online? It's long and gets truncated in GitHub's online viewer so you won't see the error unless you download it. (The `02.make` that displays as 740ish lines on the web page is actually 2,100 lines long.)

**Comment by maxim-belkin** [comment]
Oh, wow! didn't know that! Thanks for the tip!

**Comment by apjanke** [comment]
NP. It's not obvious, because the file which is truncated has the message about truncation at the *top* of that file's display, and not at the bottom where the in-file truncation occurs. Easy to scroll past and miss it.

**Comment by timotheecour** [comment]
now seems to work fine:

Updated Homebrew from 5d5b9a7 to 6622b56.

brew install llvm
Warning: llvm-3.8.1 already installed

xcode-select version 2343.

**Comment by maxim-belkin** [comment]
And `locate  /stdio\.h` gives you .... ?

**Comment by timotheecour** [comment]
```
locate /stdio\.h | grep MacOSX.platform
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1/tr1/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdio.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/stdio.h
```

**Comment by maxim-belkin** [comment]
:) that question was for @apjanke

**Comment by pbrumm** [comment]
I wipe and reinstalled brew to get llvm back.  but it installed quickly so it didn't require compile.

I think my challenge is that I added --with-clang to an install without really needing too.   when that failed even when I tried to run without that arg something was stuck and keeping that --with-clang flag and trying to compile llvm.   

does the command 

`brew install -s llvm --without-compiler-rt  `

work by forcing you out of the --with-clang? And using prebuilt llvm?

**Comment by maxim-belkin** [comment]
`--with-clang` is one of the default options now so you don't need to pass it. It might be that when you pass it, Homebrew somehow decides that it needs to build `llvm` from source.
When you wiped out `brew`, you probably `fixed` some problem that was forcing Homebrew to not use a bottle ( = prebuilt llvm in your terminology). 

Neither `-s` nor `--without-compiler-rt` change `--with-clang` option.
`-s` is short for `source`, _i.e._ `--build-from-source` 
`--without-compiler-rt` is short for ... ;)

**Comment by pbrumm** [comment]
that sounds right.   wiping was the only way I could figure out how to have it stop trying to build llvm from source.

**Comment by apjanke** [comment]
I don't have `locate` set up, but:

```
$ find /usr -name stdio.h
/usr/include/c++/4.2.1/tr1/stdio.h
/usr/include/stdio.h
/usr/include/sys/stdio.h
/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/tr1/stdio.h
/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.2.0/include/ssp/stdio.h
/usr/local/Cellar/llvm/3.8.1/include/c++/v1/stdio.h
/usr/local/Cellar/sdcc/3.5.0/share/sdcc/include/pic16/stdio.h
/usr/local/Cellar/sdcc/3.5.0/share/sdcc/include/stdio.h
find: /usr/sbin/authserver: Permission denied
```

I have the CLT installed, version 7.3.1.

```
OS X: 10.11.6-x86_64
Xcode: 7.3.1 => /Applications/Xcode-7.3.1.app/Contents/Developer
CLT: 7.3.1.0.1.1461711523
```

Hmm. I have renamed my `Xcode.app` to a non-default name. `xcode-select` is pointed at it, but perhaps it's causing some confusion nonetheless?

I think next thing I'm going to do is a) un-rename Xcode, b) fire up a clean VM on my end to see if I can get a good build there, and c) run a dummy LLVM build on Jenkins to see how it runs, and compare logs.

**Comment by maxim-belkin** [comment]
`brew install findutils` should install `locate`.
I don't think the non-default location of Xcode matters, but worth a try.
I've successfully built llvm on a system with:
```
OS X: 10.12-x86_64
Xcode: 8.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT: N/A
X11: 2.7.9 => /opt/X11
```
At home I have 10.11 with CLT 7.3.1 so I will compare my logs to yours to see what's different.

**Comment by MikeMcQuaid** [comment]
or just `alias locate='mdfind -name'` 😀

**Comment by apjanke** [comment]
Nice.

For reference:

```
$ mdfind -name stdio.h
/usr/local/Cellar/boost/1.61.0_1/include/boost/iostreams/filter/stdio.hpp
/Users/janke/Dropbox/opp/working/vlc/extras/tools/m4/lib/stdio.h
/usr/include/sys/stdio.h
/usr/include/xlocale/_stdio.h
/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
/usr/include/c++/4.2.1/tr1/stdio.h
/usr/include/secure/_stdio.h
/usr/include/stdio.h
/usr/local/Cellar/gcc/6.2.0/include/c++/6.2.0/tr1/stdio.h
/usr/local/Cellar/gcc/6.2.0/lib/gcc/6/gcc/x86_64-apple-darwin15.6.0/6.2.0/include/ssp/stdio.h
```

**Comment by maxim-belkin** [comment]
Can you do that in your /Application folder?

**Comment by apjanke** [comment]
```
$ cd /Applications
[/Applications]
$ find . -name stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/c++/4.2.1/tr1/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/c++/4.2.1/tr1/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1/tr1/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/iPhoneOS.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/iPhoneOS.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/iPhoneSimulator.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/iPhoneSimulator.sdk/usr/include/sys/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include/stdio.h
./Xcode-7.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include/sys/stdio.h
[/Applications]
$
```

**Comment by International** [comment]
I can also confirm that `brew install -s llvm --without-compiler-rt` works for me. Thank you!

**Comment by ilovezfs** [comment]
Is this still a problem with 3.9.1?

**Comment by MikeMcQuaid** [comment]
> Is this still a problem with 3.9.1?

Assuming not.
