### ISSUE TITLE
gst-plugins-base 1.14.2 compilation error

### ISSUE THREAD

**Issue by philn** [Homebrew/homebrew-core#30341]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew upgrade` fails for the gst-plugins-base recipe. Please see the logs: https://gist.github.com/b2a9d3ee68b5b973e99d6e23bd107271

**Comment by philn** [comment]
As this is related to gobject-introspection I suspect other gst recipes might fail as well but the upgrade fails early due to this error already.

**Comment by philn** [comment]
Any hints about this would be appreciated! Maybe @ilovezfs would have some ideas?
The gstreamer1.0 recipe doesn't have this issue, .typelib files are correctly generated. I'll try to compare both builds...

**Comment by SMillerDev** [comment]
Since it does build on the Jenkins servers, it must be something in your environment. What happens when you try to pour the bottle?

**Comment by philn** [comment]
I suppose that would work :) How can I do it for a formula that was configured previously to build from source?
Anyway I'd like to figure out what's wrong here.

**Comment by SMillerDev** [comment]
you can just remove the current install and install without specifying that it should build from source.

**Comment by philn** [comment]
OK that works, but I've lost ogg/vorbis/theora support :( For the time being I can live with this workaround... Whenever I find the time and motivation to debug this I'll file a new issue if appropriate.
