### ISSUE TITLE
'brew update' fails on 10.11.5 with incorrect 'Git must be installed and in your PATH!'

### ISSUE THREAD

**Issue by smrobinson** [Homebrew/homebrew-core#3037]
### Bug reports:
brew update fails, complaining it can't find git. I last ran 'update' about 3 weeks ago with no problem. doctor reports nothing, git is on PATH and runs. I ran 'brew upgrade tomcat' with no problem.

Output files here: https://gist.github.com/smrobinson/59daa19939afe0923a32554592fc250f

This is reported by another user in a comment today on https://github.com/Homebrew/homebrew-core/issues/2786 but I don't see a separate issue for it.

**Comment by darkbrow** [comment]
https://github.com/Homebrew/brew/issues/520

**Comment by resistor4u** [comment]
#3029 yeeup, this worked for me. any idea what broke/caused this?

**Comment by DomT4** [comment]
We did. We moved [some elements](https://github.com/Homebrew/brew/commit/a02be9eea204264ce48827ac365c8b53b986d66a) but forgot to change [this line](https://github.com/Homebrew/brew/commit/0d0519d48d32b9f12d37edb5a5127f34d70d8347) at the same time, so it borked on finding `git`.

```bash
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
Is the answer. That'll solve any issues. Apologies again for the inconvenience.

**Comment by smrobinson** [comment]
Sorry I missed #3029. I really did look through the list but I think the is:open flag was set and I didn't search, just browsed down the list.

**Comment by DomT4** [comment]
No worries, it happens. Hope all is working for you again now.
