### ISSUE TITLE
aria2 failed to build on 10.11.5

### ISSUE THREAD

**Issue by mjgardner** [Homebrew/homebrew-core#3038]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whom) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

https://gist.github.com/mjgardner/dc1206a4961353c35096f3812c0fadb5

**Comment by smoothdvd** [comment]
==> Upgrading 1 outdated package, with result:
aria2 1.25.0
==> Upgrading aria2
==> Downloading https://github.com/aria2/aria2/releases/download/release-1.25.0/aria2-1.25.0.tar.xz
Already downloaded: /Users/alexgao/Library/Caches/Homebrew/aria2-1.25.0.tar.xz
==> ./configure --prefix=/usr/local/Cellar/aria2/1.25.0 --with-appletls --without-openssl --without-gnutls --without-libgmp --without-libnettle --without-libgcrypt --with-libssh2
Last 15 lines from /Users/alexgao/Library/Logs/Homebrew/aria2/01.configure:
checking for xml2-config... /usr/bin/xml2-config
checking for libxml - version >= 2.6.24... yes (version 2.9.2)
checking for SQLITE3... no
configure: WARNING: No package 'sqlite3' found
checking whether to enable Mac OS X native SSL/TLS... yes
checking for main in -lcrypt32... no
checking for main in -lsecur32... no
checking for main in -ladvapi32... no
checking for wincrypt.h... no
checking for security.h... no
checking for LIBSSH2... no
configure: WARNING: Package 'zlib', required by 'libssh2', not found
configure: error: in `/private/tmp/aria2-20160716-75705-12pj0vj/aria2-1.25.0':
configure: error: libssh2 is requested but not found in the system.
See `config.log' for more details

**Comment by ilovezfs** [comment]
This PR fixes the issue https://github.com/Homebrew/homebrew-core/issues/3038

**Comment by ilovezfs** [comment]
This is now fixed, if you brew update.

**Comment by smoothdvd** [comment]
@ilovezfs Thanks
