### ISSUE TITLE
php formula creates incorrect `pecl` symlink - unable to install PHP extensions.

### ISSUE THREAD

**Issue by romaninsh** [Homebrew/homebrew-core#30396]
After clean install of `php` and using `pecl install xdebug` the extension is not loadable. The reason for this is incorrect `pecl` symlink.

```
MacBook-Pro:7.2.8 rw$ pwd
/usr/local/Cellar/php/7.2.8
MacBook-Pro:7.2.8 rw$ ls -l | grep pecl
lrwxr-xr-x   1 rw  admin     23 23 Jul 13:38 pecl -> /usr/local/lib/php/pecl
```

If I fix symlink manually and reinstall:

```
rm pecl
ln -sf lib/php pecl

# lrwxr-xr-x   1 rw  admin      7 23 Jul 14:33 pecl -> lib/php

pecl uninstall xdebug
pecl install xdebug
```

Then extension works. This can be observed by installing different version of php:

```
$ brew install php@7.1
...
==> Summary
🍺  /usr/local/Cellar/php@7.1/7.1.20: 514 files, 67.2MB
MacBook-Pro:7.2.8 rw$ cd /usr/local/Cellar/php@7.1/7.1.20/
MacBook-Pro:7.1.20 rw$ ls -la | grep pecl
lrwxr-xr-x   1 rw  admin      23 23 Jul 14:35 pecl -> /usr/local/lib/php/pecl
```

I suspect that the problem might be here:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb#L199

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by SMillerDev** [comment]
What does `php -i | grep extension_dir` show you? because for the latest php it should be `/usr/local/lib/php/pecl/20170718/`. If it's not, that might be why you can't load extensions.

**Comment by romaninsh** [comment]
extension_dir => /usr/local/Cellar/php/7.2.8/lib/php/20170718 => /usr/local/Cellar/php/7.2.8/lib/php/20170718

**Comment by SMillerDev** [comment]
Each major version, yes. That's what the date is for. It's the php api version.

**Comment by javian** [comment]
The reason for this could be that you had php 7.1 installed before it was migrated to homebrew-core. I vaguely remember this type of issue. If you remove the old config and have the system create a new one it should be fine.

**Comment by romaninsh** [comment]
I tried the following:

```
MacBook-Pro:7.2.9_2 rw$ rm -rf /usr/local/lib/php/
MacBook-Pro:7.2.9_2 rw$ brew remove php
Uninstalling /usr/local/Cellar/php/7.2.9_2... (515 files, 74.9MB)
php 7.2.8 1 is still installed.
MacBook-Pro:php rw$ brew install php
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/php-7.2.9_2.high_sierra.bottle.tar.gz
Already downloaded: /Users/rw/Library/Caches/Homebrew/php--7.2.9_2.high_sierra.bottle.tar.gz
==> Pouring php--7.2.9_2.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set php_ini /usr/local/etc/php/7.2/php.ini system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set php_dir /usr/local/share/pear system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set doc_dir /usr/local/share/pear/doc system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set ext_dir /usr/local/lib/php/pecl/20170718 system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set bin_dir /usr/local/opt/php/bin system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set data_dir /usr/local/share/pear/data system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set cfg_dir /usr/local/share/pear/cfg system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set www_dir /usr/local/share/pear/htdocs system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set man_dir /usr/local/share/man system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set test_dir /usr/local/share/pear/test system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear config-set php_bin /usr/local/opt/php/bin/php system
==> /usr/local/Cellar/php/7.2.9_2/bin/pear update-channels
==> Caveats
..snip


MacBook-Pro:php rw$ cd 7.2.9_2/
MacBook-Pro:7.2.9_2 rw$ ls -la

lrwxr-xr-x   1 rw  staff     23 25 Aug 08:58 pecl -> /usr/local/lib/php/pecl
```

 /usr/local/lib/php is built and created every time.

**Comment by SMillerDev** [comment]
That doesn't change the config though, that config is in /usr/local/etc/php. And the existence of /usr/local/lib/php shouldn't be a problem.
