### ISSUE TITLE
brew install ideviceinstaller error 

### ISSUE THREAD

**Issue by sky15179** [Homebrew/homebrew-core#30394]
Error: cython: undefined method `undent' for #<String:0x00000001039328b8>

brew config
HOMEBREW_VERSION: 1.7.0-91-gdb29903
ORIGIN: https://github.com/Homebrew/brew
HEAD: db299035ac8d2b3024d4f32f27761fba5066973f
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ffa6faf8c7c2cba71e51180d8556a89ab7a3f153
Core tap last commit: 66 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.4
XQuartz: N/A

**Comment by SMillerDev** [comment]
Please use the issue template as defined here:
https://github.com/Homebrew/homebrew-core/issues/new?template=Reproducible-Bug-Report.md
