### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by sky15179** [Homebrew/homebrew-core#30393]
==> Upgrading bash-completion
==> Downloading http://7xkcej.dl1.z0.glb.clouddn.com/bottles/bash-completion-1.3
######################################################################## 100.0%
==> Pouring bash-completion-1.3_3.high_sierra.bottle.tar.gz
Error: undefined method `undent' for #<String:0x00000001010d1158>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/bash-completion.rb:46:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:610:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:659:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:153:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:98:in `block in upgrade'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:95:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:95:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'

brew config
HOMEBREW_VERSION: 1.7.0-91-gdb29903
ORIGIN: https://github.com/Homebrew/brew
HEAD: db299035ac8d2b3024d4f32f27761fba5066973f
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ffa6faf8c7c2cba71e51180d8556a89ab7a3f153
Core tap last commit: 66 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: N/A
Xcode: 9.4
XQuartz: N/A

**Comment by SMillerDev** [comment]
Please use the issue template as defined here: 
https://github.com/Homebrew/homebrew-core/issues/new?template=Reproducible-Bug-Report.md

As for the undent issue, @MikeMcQuaid had a fix for that in brew afaik.

**Comment by MikeMcQuaid** [comment]
> Core tap HEAD: ffa6faf8c7c2cba71e51180d8556a89ab7a3f153

This is not a commit in this tap and you have an old version of this formula. Please remove any local Git changes (e.g. run `brew update-reset`) and try again.
