### ISSUE TITLE
MySQL v8.0.11 Fails to Build From Source and Install Under OS X v10.11.6 'El Capitan'

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#30405]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please always confirm that you:  

- [x] are reporting a bug others will be able to reproduce and not asking a question.  If you're not sure or want to ask a question, do so on our Discourse:  https://discourse.brew.sh.  
- [x] have a problem with `brew install`ing (or `upgrade`ing or `reinstall`ing) a single, official formula (not cask)?  If it's a general `brew` problem, please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose.  If it's a `brew cask` problem, please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose.  If it's a tap&thinsp;—&thinsp;e.g.:  Homebrew/homebrew-php&thinsp;—&thinsp;problem, please file this issue at the tap.  
- [x] ran `brew update` and can still reproduce the problem?  
- [x] ran `brew doctor`, fixed all issues, and can still reproduce the problem?  
- [ ] ~~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~  (N/A; see the next checklist item.)  
- [x] if `brew gist-logs` didn't work (or wasn't applicable:)  ran `brew config` and `brew doctor` and included their output with your issue?  

To help us debug your issue please explain:  

- What you were trying to do (and why:)  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Upgrade my local, built-from-source copy of MySQL from v5.7.22 to v8.0.11 in the course of going through my normal routine of keeping all of my software tools up to date (with respect to packages' latest stable releases, as usual.)  

- What happened (include command output:)  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Homebrew failed to upgrade MySQL from v5.7.22 to v8.0.11.  My logs are:  

   - [here](https://gitlab.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/MySQL/v8.0.11/Recorded%20Attempts/First%20Recorded%20Attempt/With%20%60HOMEBREW_BUILD_FROM_SOURCE=1%60) (from when I _did_ set `HOMEBREW_BUILD_FROM_SOURCE=1`.)  
   - [here](https://gitlab.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/MySQL/v8.0.11/Recorded%20Attempts/First%20Recorded%20Attempt/With%20%60HOMEBREW_BUILD_FROM_SOURCE%60%20Undefined) (from when I _didn't._)  

   In both cases, the exact point of failure appeared as follows:  

   ```
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mysql.rb
   ==> Upgrading 1 outdated package, with result:
   mysql 5.7.22 -> 8.0.11
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/cmake.rb
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sphinx-doc.rb
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openssl.rb
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb
   /usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pkg-config.rb
   mysql: macOS Sierra or newer is required.
   Error: mysql: An unsatisfied requirement failed this build.
   ```

   This is due to #20538 introducing said OS X/macOS release requirement to avoid https://bugs.mysql.com/bug.php?id=86711.  

- What you expected to happen:  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For Homebrew to successfully build the new version of MySQL from source and install it in the old version's place.  

- Step-by-step reproduction instructions (by running `brew` commands:)  

   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Given that I originally installed MySQL on my machine `--with-debug`, `--with-embedded`<sup>*</sup>, `--with-local-infile`, and `--with-test` in either of the following cases:  

   - _With_ `HOMEBREW_BUILD_FROM_SOURCE=1` (not supported with issue resolution:)  

      ```
      HOMEBREW_BUILD_FROM_SOURCE=1 brew upgrade -vd --build-from-source mysql
      ```

      (Note that setting that environment variable as shown above, as usual and would be expected, _probably_ doesn't make any difference with respect to this issue, as upgrading MySQL would not depend on upgrading any of its dependencies since they're already up to date, but, as usual, I typically see this anyway just for consistency's sake.)  

   - _Without_ `HOMEBREW_BUILD_FROM_SOURCE=1` (given to show that this issue also occurs under a _supported_ configuration:)  

      ```
      brew upgrade -vd --build-from-source mysql
      ```

---

<sup>*</sup>&thinsp;I seem to recall reading something about the embedded server being removed from MySQL in the v8.x/v8.0.x release series in the project's release notes somewhere, but I can't remember exactly where and haven't searched back through them to check yet.  Besides, that can be addressed separately anyway.  

---

P. S.:  I would have brought this up sooner, but I was focusing exclusively on another, unrelated Homebrew issue when I ran into this.  Apologies for the delay.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For the record, I did start working on a [PR-staging branch](https://github.com/RandomDSdevel/homebrew-core/tree/fix-mysql-on-El-Capitan) to both fix this issue and address a point I raised in [a Discourse thread I started](
https://discourse.brew.sh/t/confusion-regarding-mysqls-in-formula-compiler-support-declaration/2465) by making the following (still WIP) changes:  

```
diff --git a/Formula/mysql.rb b/Formula/mysql.rb
index 986789590e..5e496b3647 100644
--- a/Formula/mysql.rb
+++ b/Formula/mysql.rb
@@ -28,14 +28,30 @@ class Mysql < Formula
   # Note: MySQL themselves don't support anything below Sierra.
   depends_on :macos => :yosemite
 
+  # According to https://dev.mysql.com/doc/refman/8.0/en/source-installation.html's section on
+  # 'Source Installation System Requirements,' MySQL:
+  needs :cxx11
+
   # https://bugs.mysql.com/bug.php?id=86711
   # https://github.com/Homebrew/homebrew-core/pull/20538
+  # https://github.com/Homebrew/homebrew-core/pull/… # Finish adding when I get a PR number
+                                                     # assigned.
   fails_with :clang do
     build 800
     cause "Wrong inlining with Clang 8.0, see MySQL Bug #86711"
   end
-  # GCC is not supported either, so exclude for El Capitan.
-  depends_on :macos => :sierra if DevelopmentTools.clang_build_version == 800
+  if DevelopmentTools.clang_build_version == 800
+    depends_on "llvm" => :build
+    ENV["HOMEBREW_CC"] = "llvm_clang"
+  end
+  # Apple's GCC shim (which redirects to AppleClang) is thus not supported either.
+  fails_with :gcc_4_2
+
+  # According to https://dev.mysql.com/doc/refman/8.0/en/source-installation.html's section on
+  # 'Source Installation System Requirements,' MySQL also:
+  ("4.3".."4.7").each do |v|
+    fails_with :gcc => v
+  end
 
   conflicts_with "mysql-cluster", "mariadb", "percona-server",
     :because => "mysql, mariadb, and percona install the same binaries."
```

but it turned out that they weren't sufficient to solve the problem.  Upon attempting a test build prior to submitting my changes as a PR, I encountered the following error:  

```
⋮
[ 22%] Building C object plugin/group_replication/libmysqlgcs/CMakeFiles/mysqlgcs.dir/src/bindings/xcom/xcom/task.c.o
cd /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang -DHAVE_CONFIG_H -DHAVE_LIBEVENT1 -DHAVE_OPENSSL -DRAPIDJSON_NO_SIZETYPEDEFINE -DUNISTR_FROM_CHAR_EXPLICIT=explicit -DUNISTR_FROM_STRING_EXPLICIT=explicit -DXCOM_HAVE_OPENSSL -D_USE_MATH_DEFINES -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11 -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/include -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/rapid -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/libbinlogevents/include -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/libbinlogevents/export -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/xdr_gen -isystem /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/extra/zlib -isystem /usr/local/opt/openssl/include -isystem /usr/include/editline -isystem /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/extra/lz4 -isystem /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/extra/rapidjson/include  -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Wwrite-strings -Wconditional-uninitialized -Wextra-semi -Wmissing-noreturn -Wunreachable-code-break -Wunreachable-code-return -fPIC -g -fno-omit-frame-pointer  -DENABLED_DEBUG_SYNC -DSAFE_MUTEX   -Wno-conditional-uninitialized -Wno-unused-variable -Wno-unused-function -Wno-conversion -Wno-switch -DMYSQL_DYNAMIC_PLUGIN -o CMakeFiles/mysqlgcs.dir/src/bindings/xcom/xcom/task.c.o   -c /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c
/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c:239:2: error: "Need CLOCK_MONOTONIC"
#error "Need CLOCK_MONOTONIC"
 ^
/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c:261:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
  clock_gettime(CLOCK_MONOTONIC, &t);
                ^
/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c:269:17: error: use of undeclared identifier 'CLOCK_REALTIME'
  clock_gettime(CLOCK_REALTIME, &t);
                ^
3 errors generated.
make[2]: *** [plugin/group_replication/libmysqlgcs/CMakeFiles/mysqlgcs.dir/src/bindings/xcom/xcom/task.c.o] Error 1
make[1]: *** [plugin/group_replication/libmysqlgcs/CMakeFiles/mysqlgcs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 22%] Linking CXX static library libgtest.a
cd /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/unittest/gunit && /usr/local/Cellar/cmake/3.12.0/bin/cmake -P CMakeFiles/gtest.dir/cmake_clean_target.cmake
cd /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/unittest/gunit && /usr/local/Cellar/cmake/3.12.0/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/link.txt --verbose=1
/usr/bin/ar qc libgtest.a  CMakeFiles/gtest.dir/__/__/source_downloads/googletest-release-1.8.0/googletest/src/gtest-all.cc.o
/usr/bin/ranlib libgtest.a
[ 22%] Built target gtest
make: *** [all] Error 2
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
⋮
```

Should I attempt to fix this by applying a solution like those similarly applied to other formulas in the past as found via [a GitHub search of Homebrew Core for `CLOCK_MONOTONIC`](https://github.com/Homebrew/homebrew-core/search?q=CLOCK_MONOTONIC&unscoped_q=CLOCK_MONOTONIC)?  I'd also have to do the same for `CLOCK_REALTIME`, as well.

**Comment by ilovezfs** [comment]
My understanding was the build also failed with gcc as you seem to have confirmed. We can only build on CI with Xcode's clang or the latest gcc. If you can get it to build with gcc then we could revisit the `depends_on :macos => :sierra`

**Comment by RandomDSdevel** [comment]
@ilovezfs:  

> My understanding was the build also failed with gcc as you seem to have confirmed.  …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Are you referring to the additional `fails_with :gcc => …` statements I have that new `each do` block add in addition to the `fails_with :gcc_4_2` I put above that to exclude Apple's GCC shim from use?  That's only for GCC releases below v4.8.  I thought it was clear enough (both from context and from prior discussion) that I only inserted said code to meet MySQL's 'Source Installation System Requirements,' as listed in [the project's documentation for 'Installing MySQL from Source'](https://dev.mysql.com/doc/refman/8.0/en/source-installation.html), which clearly states that the package requires:  

> ⋮
>
> * MySQL 8.0 source code permits use of C++11 features.  To enable a good level of C++11 support across all supported platforms, the following minimum compiler versions apply:  
>
>    * GCC:  4.8 or higher
>
>    ⋮

Again, I also referenced this in [that Discourse thread I mentioned earlier](https://discourse.brew.sh/t/confusion-regarding-mysqls-in-formula-compiler-support-declaration/2465), if you'll recall.  

> …We can only build on CI with Xcode's clang or the latest gcc.  …

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OK.  

> …If you can get it to build with gcc then we could revisit the `depends_on :macos => :sierra`

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Roger, wilco.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;A few questions:  

* Would the `needs :cxx11` I already added to acknowledge MySQL's build requirements actually take care of the whole dance with respect to avoiding unusable GCC versions for me?  (`brew`'s source and docs might say, but I haven't checked them yet.)  
* I've been guessing that I'd need to have MySQL's formula `depends_on` the formula for the compiler I want to use before I set `HOMEBREW_CC` to it (due to the sandbox,) but is that really the case, or would `brew` handle that for me?  
* Additionally, is there a better way to tell `brew` which compiler a formula wants/needs to use than using that environment variable, perhaps in the form of a Homebrew DSL statement?  
* Could you answer my question from the second half of https://github.com/Homebrew/homebrew-core/issues/30405#issuecomment-407219924?  

Thanks in advance.

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;With respect to one of those questions&thinsp;—&thinsp;namely, this one:  

> ⋮
>
> * Would the `needs :cxx11` I already added to acknowledge MySQL's build requirements actually take care of the whole dance with respect to avoiding unusable GCC versions for me?  
> ⋮

—, having looked through that part of Homebrew's source now lets me answer it myself.  To whit, as of this writing:  

1. `Formula.needs` is defined like so on [lines 2,497–2,499 of `Library/Homebrew/formula.rb`](https://github.com/Homebrew/brew/blob/b335a7357b7c02603ee9a5e15a666563ce02654c/Library/Homebrew/formula.rb#L2497-L2499):  

   ```
   ⋮

   def needs(*standards)
     specs.each { |spec| spec.needs(*standards) }
   end

   ⋮
   ```

1. This calls `SoftwareSpec#needs()`, defined thusly on [lines 212–216 of `Library/Homebrew/software_spec.rb`](https://github.com/Homebrew/brew/blob/b335a7357b7c02603ee9a5e15a666563ce02654c/Library/Homebrew/software_spec.rb#L212-L216):  

   ```
   ⋮

   def needs(*standards)
     standards.each do |standard|
       compiler_failures.concat CompilerFailure.for_standard(standard)
     end
   end

   ⋮
   ```

1. This then calls `CompilerFailure.for_standard()`, defined [in `Library/Homebrew/compilers.rb` at lines 34–38](https://github.com/Homebrew/brew/blob/b335a7357b7c02603ee9a5e15a666563ce02654c/Library/Homebrew/compilers.rb#L34-L38):  

   ```
   ⋮

   def self.for_standard(standard)
     COLLECTIONS.fetch(standard) do
       raise ArgumentError, "\"#{standard}\" is not a recognized standard"
     end
   end

   ⋮
   ```

1. Finally, that calls a member function `fetch()` (likely defined somewhere in Ruby's core language implementation or standard library for all Ruby collections) on `COLLECTIONS`, whose definition lives on [lines 68–93 of `Library/Homebrew/compiler.rb`](https://github.com/Homebrew/brew/blob/b335a7357b7c02603ee9a5e15a666563ce02654c/Library/Homebrew/compilers.rb#L68-L93):  

   ```
   ⋮

   COLLECTIONS = {
     cxx11: [
       create(:gcc_4_0),
       create(:gcc_4_2),
       create(:clang) { build 425 },
       create(gcc: "4.3"),
       create(gcc: "4.4"),
       create(gcc: "4.5"),
       create(gcc: "4.6"),
     ],
     cxx14: [
       create(:clang) { build 600 },
       create(:gcc_4_0),
       create(:gcc_4_2),
       create(gcc: "4.3"),
       create(gcc: "4.4"),
       create(gcc: "4.5"),
       create(gcc: "4.6"),
       create(gcc: "4.7"),
       create(gcc: "4.8"),
     ],
     openmp: [
       create(:clang),
     ],
   }.freeze

   ⋮
   ```

   where `freeze` is also defined on…all Ruby objects, I think, since it involves the language's garbage collector?  

You might (probably) know some (or most or all) of this already, though, @ilovezfs.  In any case, the answer to my former question that I can now address here is 'no, I'd have to use `needs :cxx14` to abstract a lot of the compiler requirements needed here away into more compact Homebrew DSL.'  I don't yet know, however, if MySQL uses any C++14 internally, as, again, its build instructions state only that, at a a minimum, C++11 is required…, but _then_ they go and state a minimum required GCC version that matches up with said compiler offering suitable C++14 support, so I won't yet know which way to go with this until I either hear further recommendations here or check upstream (perhaps by spelunking around a bit in _its_ code) to see which language standard they're _really_ using…

**Comment by RandomDSdevel** [comment]
@ilovezfs:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now that I've looked through `~/Library/Logs/Homebrew/mysql/01.cmake`, it seems that the `CLOCK_MONOTONIC`/`CLOCK_REALTIME` issue I described as having encountered in the second half of [my first reply to this issue discussion thread after my OP](https://github.com/Homebrew/homebrew-core/issues/30405#issuecomment-407219924) (repeated here for the sake of locality of reference:  

> ```
> ⋮
> [ 22%] Building C object plugin/group_replication/libmysqlgcs/CMakeFiles/mysqlgcs.dir/src/bindings/xcom/xcom/task.c.o
> cd /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang -DHAVE_CONFIG_H -DHAVE_LIBEVENT1 -DHAVE_OPENSSL -DRAPIDJSON_NO_SIZETYPEDEFINE -DUNISTR_FROM_CHAR_EXPLICIT=explicit -DUNISTR_FROM_STRING_EXPLICIT=explicit -DXCOM_HAVE_OPENSSL -D_USE_MATH_DEFINES -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11 -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/include -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/rapid -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/libbinlogevents/include -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/libbinlogevents/export -I/tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/xdr_gen -isystem /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/extra/zlib -isystem /usr/local/opt/openssl/include -isystem /usr/include/editline -isystem /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/extra/lz4 -isystem /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/extra/rapidjson/include  -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Wwrite-strings -Wconditional-uninitialized -Wextra-semi -Wmissing-noreturn -Wunreachable-code-break -Wunreachable-code-return -fPIC -g -fno-omit-frame-pointer  -DENABLED_DEBUG_SYNC -DSAFE_MUTEX   -Wno-conditional-uninitialized -Wno-unused-variable -Wno-unused-function -Wno-conversion -Wno-switch -DMYSQL_DYNAMIC_PLUGIN -o CMakeFiles/mysqlgcs.dir/src/bindings/xcom/xcom/task.c.o   -c /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c
> /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c:239:2: error: "Need CLOCK_MONOTONIC"
> #error "Need CLOCK_MONOTONIC"
>  ^
> /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c:261:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
>   clock_gettime(CLOCK_MONOTONIC, &t);
>                 ^
> /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c:269:17: error: use of undeclared identifier 'CLOCK_REALTIME'
>   clock_gettime(CLOCK_REALTIME, &t);
>                 ^
> 3 errors generated.
> make[2]: *** [plugin/group_replication/libmysqlgcs/CMakeFiles/mysqlgcs.dir/src/bindings/xcom/xcom/task.c.o] Error 1
> make[1]: *** [plugin/group_replication/libmysqlgcs/CMakeFiles/mysqlgcs.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 22%] Linking CXX static library libgtest.a
> cd /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/unittest/gunit && /usr/local/Cellar/cmake/3.12.0/bin/cmake -P CMakeFiles/gtest.dir/cmake_clean_target.cmake
> cd /tmp/mysql-20180722-30410-1m16rkn/mysql-8.0.11/unittest/gunit && /usr/local/Cellar/cmake/3.12.0/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/link.txt --verbose=1
> /usr/bin/ar qc libgtest.a  CMakeFiles/gtest.dir/__/__/source_downloads/googletest-release-1.8.0/googletest/src/gtest-all.cc.o
> /usr/bin/ranlib libgtest.a
> [ 22%] Built target test
> make: *** [all] Error 2
> /usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
> BuildError: Failed executing: make 
> ⋮
> ```

) shouldn't have happened in the first place, as CMake had this to say on the matter:  

```
⋮
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - not found
⋮
-- Performing Test HAVE_CLOCK_REALTIME
-- Performing Test HAVE_CLOCK_REALTIME - Failed
⋮
```

Why `buildpath/"plugin/group_replication/libmysqlgcs/src/bindings/xcom/xcom/task.c"` appeared not to respect this, I don't know.  

P. S.:  That GCC build attempt you asked for was delayed by me having to upgrade said compiler to v8.2.0 after Homebrew picked that release up, but it's still coming.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MySQL doesn't appear to support (or even _handle_) being built with GCC on OS X/macOS.  (If I had to guess, I'd say upstream is forcibly respecting platform compiler use conventions.)  If I try building with GCC, MySQL's CMake configuration step errors out early with:  

```
⋮
CMake Error at cmake/os/Darwin.cmake:53 (MESSAGE):
  Unsupported compiler!
Call Stack (most recent call first):
  CMakeLists.txt:251 (INCLUDE)


-- Configuring incomplete, errors occurred!
⋮
```

Passing CMake `-D FORCE_UNSUPPORTED_COMPILER` might work, but probably wouldn't fly in the MySQL formula…  Ah, well; back to the drawing board…🤔, _pulls hair out._

**Comment by RandomDSdevel** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Y'know, adding `[[gnu::noinline]]`/`__attribute__((noinline))` to the affected functions in MySQL's source might work…
