### ISSUE TITLE
libcanberra fails to build GTK+3 support due to X11 bindings

### ISSUE THREAD

**Issue by spotlightishere** [Homebrew/homebrew-core#30476]
I:

- [x] am reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- My filesystem is case-insensitive and I'm running the latest beta of Mojave, but from my understanding those have nothing to do with this.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- https://gist.github.com/spotlightishere/77642c129801734230ee36ad6a024f60

To help us debug your issue please explain:
- What you were trying to do (and why)

I was attempting to build libcanberra with GTK+3 support for another project.

- What happened (include command output)

I ran `brew install libcanberra --with-gtk+3` and it installed without GTK+3 support, instead building normally.

Citing from `config.log`:
```
configure:19509: checking for GTK3
configure:19516: $PKG_CONFIG --exists --print-errors " gtk+-3.0 gthread-2.0 glib-2.0 >= 2.32 gdk-3.0 x11 "
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
```

Similar options likewise fail to actually build with the given feature due to no X11. `pkg-config --debug --exists --print-errors=1 libcanberra-gtk3` confirms this.

Upon editing the formula to contain `depends_on :x11`, configure shows GTK+3 support added, but _fails_ due to GTK+3 not being built itself with X11 support:
```
canberra-gtk.c:29:10: fatal error: 'gdk/gdkx.h' file not found
#include <gdk/gdkx.h>
```

- What you expected to happen

`libcanberra` installs with GTK+3 support.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install libcanberra --with-gtk+3
pkg-config --debug --exists --print-errors=1 libcanberra-gtk3
# edit formula to depend on x11
brew install libcanberra --with-gtk+3
```

**Comment by DomT4** [comment]
> canberra-gtk.c:29:10: fatal error: 'gdk/gdkx.h' file not found
#include <gdk/gdkx.h>

If it's expecting GTK+3 to be built with `x11` the option essentially will need to be removed. GTK with `x11` is a dead horse in brewland.
