### ISSUE TITLE
Megatools -- outdated, compiles but doesnt work

### ISSUE THREAD

**Issue by IvanTurgenev** [Homebrew/homebrew-core#30480]
Not knowledgeable enough to update the formulae myself latest is
https://github.com/megous/megatools/archive/1.10.0.zip
fixes a lot of stuff (megaput etc)current formula is 1.9.98

**Comment by SMillerDev** [comment]
Here's some resources to help you get started with contributing to homebrew 
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

It's easier than it might appear most of the time.

**Comment by IvanTurgenev** [comment]
I tried ended up with a zlib.h error couldnt solve

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/pull/30510
