### ISSUE TITLE
Browsh

### ISSUE THREAD

**Issue by and09** [Homebrew/homebrew-core#30502]
Anybody can add Browsh browser?
https://github.com/browsh-org/browsh

**Comment by SMillerDev** [comment]
You can 👍 (if it meets [these](https://docs.brew.sh/Acceptable-Formulae))

Here's some resources to help you get started. Though you might need to make this a tap.
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
https://docs.brew.sh/Formula-Cookbook

**Comment by letarg0** [comment]
A kiedy będzie po polsku ta dokumentacja?
