### ISSUE TITLE
gnupg@1.4 can't find dependencies for communicating with keyservers

### ISSUE THREAD

**Issue by kmasaryk** [Homebrew/homebrew-core#30542]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Attempting to run:
```
$ gpg1 --keyserver keyserver.ubuntu.com --recv 5234BF2B
```

- What happened (include command output)
```
gpg: requesting key 5234BF2B from hkp server keyserver.ubuntu.com
gpg: unable to execute program `/usr/local/Cellar/gnupg@1.4/1.4.23/libexec/gnupg/gpgkeys_curl': No such file or directory
gpg: no handler for keyserver scheme `hkp'
gpg: keyserver receive failed: keyserver error
```

- What you expected to happen
Public key should be downloaded, via curl, and imported to local keyring.

- Step-by-step reproduction instructions (by running `brew install` commands)
Command listed above.

- Additional information
gpgkeys_curl exists but with a '1' appended to it:
```
$ ls -1 /usr/local/Cellar/gnupg\@1.4/1.4.23/libexec/gnupg/
gpgkeys_curl1
gpgkeys_finger1
gpgkeys_hkp1
gpgkeys_ldap1
```

- Workaround
```
$ cd /usr/local/Cellar/gnupg\@1.4/1.4.23/libexec/gnupg
$ ln -s gpgkeys_curl1 gpgkeys_curl
$ ln -s gpgkeys_hkp1 gpgkeys_hkp
```

**Comment by DomT4** [comment]
Closed via https://github.com/Homebrew/homebrew-core/commit/8319ffd314cb39db9ef920f5b138b74f0255aad7.
