### ISSUE TITLE
possible typo in pythia installation

### ISSUE THREAD

**Issue by amajumder** [Homebrew/homebrew-core#30586]
I am trying to install pythia from davidchall/hep  on high Sierra 10.13.6
and get the following issue, looks like a typo:
I have already tapped davidchall/hep, and that went fine. 

$ brew install pythia
==> Installing pythia from davidchall/hep
==> Installing dependencies for davidchall/hep/pythia: hepmc, lhapdf
==> Installing davidchall/hep/pythia dependency: hepmc
==> Downloading https://dl.bintray.com/davidchall/bottles-hep/hepmc-2.06.09.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring hepmc-2.06.09.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/hepmc/2.06.09: 75 files, 2.3MB
==> Installing davidchall/hep/pythia dependency: lhapdf
==> Downloading https://dl.bintray.com/davidchall/bottles-hep/lhapdf-6.2.1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lhapdf-6.2.1.high_sierra.bottle.tar.gz
Error: undefined method `undent' for #<String:0x00007f91d41ec4f0>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/lhapdf.rb:49:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:610:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:659:in `finish'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:592:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:553:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:553:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:553:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:271:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'

**Comment by DomT4** [comment]
See https://github.com/davidchall/homebrew-hep/issues/135, https://github.com/davidchall/homebrew-hep/pull/136, etc. That tap needs a style/syntax update essentially, but it's outside of Homebrew's control so will need action from @davidchall.
