### ISSUE TITLE
Error: Calling 'depends_on :mysql' is disabled!

### ISSUE THREAD

**Issue by IcyW** [Homebrew/homebrew-core#30710]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I don't know what to report (or what I am reporting) just as the one reported  [here](https://github.com/Homebrew/homebrew-core/issues/24599), but I got this message when running `brew install qt`：

> Updating Homebrew...
Error: Calling 'depends_on :mysql' is disabled!
Use 'depends_on "mysql"' instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb:30:in `<class:Qt>'
Please report this to the homebrew/core tap!
Or, even better, submit a PR to fix it!

**Comment by IcyW** [comment]
@SMillerDev thank you for your reply!
I got 504 Error when updating homebrew yesterday. I've solved this problem by downloading portable-ruby-2.0.0-p648.leopard_64.bottle.tar.gz and putting it in /Users/${USER}/Library/Caches/Homebrew/.

**Comment by fxcoudert** [comment]
`brew update-reset` is usually a good option for these cases:

```
o   update-reset: Fetches and resets Homebrew and all tap repositories using git(1) to their latest
    origin/master. Note this will destroy all your uncommitted or committed changes.
```

Glad to hear you fixed your issue in any case!
