### ISSUE TITLE
Error: brew install openocd

### ISSUE THREAD

**Issue by gyz1990** [Homebrew/homebrew-core#30716]
$ brew install openocd --enable_ft2232_libftdi --enable_stlink

Error: Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/automake.rb:18:in `<class:Automake>'
Please report this to the homebrew/core tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-core/issues

**Comment by SMillerDev** [comment]
Please fill out the template. It helps a lot with debugging issues. Did you run brew update?
