### ISSUE TITLE
No more pymol?

### ISSUE THREAD

**Issue by MZLAKg2aGGFs8yi** [Homebrew/homebrew-core#30721]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install pymol from brew
- What happened (include command output)
brew install homebrew/science/pymol
*****homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.
brew search pymol
*****No formula or cask found for "pymol".
- What you expected to happen
the package pymol seems to be lost during the migration. Please put it back.
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install homebrew/science/pymol
brew search pymol

**Comment by SMillerDev** [comment]
> Please put it back.
Pull requests are welcome, only the most used formulae were migrated initially.
It would need to pass [these requirements](https://docs.brew.sh/Acceptable-Formulae) though.
