### ISSUE TITLE
install root from bottle failed, but build from source worked.

### ISSUE THREAD

**Issue by ryounsumiko** [Homebrew/homebrew-core#30726]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I installed root from a bottle by `brew install root` and succeed,
then test it by `brew test root`. It ends up with the output:

Testing root
==> /bin/bash test.bash
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -O2 -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
Results was:
With exit code 256
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
input_line_3:37:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
input_line_9:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
In file included from input_line_10:1:
/private/tmp/root-test-20180802-77387-19boclr/test.C:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
Error: root: failed
<0> expected but was
<1>.

On the other hand, the error won't show up if I install by `brew install root --build-from-source`.
The gist-logs output is at https://gist.github.com/ryounsumiko/770c48eea36b4a941a67fc993178650a

My theory is either the bottled version doesn't pick up correct compiler, or my /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ doesn't run correctly.

In addition, the output of `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -v` :
clang++: The build tool has reset ENV; --env=std required.
I don't know if this is expected.

**Comment by DomT4** [comment]
> On the other hand, the error won't show up if I install by brew install root --build-from-source.

The bottles are built on CI with both Xcode & the CLT package installed, whereas you've only the latter installed locally. This does cause issues in places, most notably with things like `gcc`; seems possible that `root` has a similar issue.

**Comment by ryounsumiko** [comment]
Ok, I see. I don't want to install Xcode, so I'll build it locally.
Thank you.
