### ISSUE TITLE
Need tcl-tk with x-11 enabled

### ISSUE THREAD

**Issue by specter119** [Homebrew/homebrew-core#30765]
[xcrysden](http://www.xcrysden.org/) is a Crystalline and molecular structure visualisation program. I have add it to [brewsci/homebrew-science #193](https://github.com/brewsci/homebrew-science/pull/193), but it needs a tcl-tk with x-11 enabled, according to [this](https://github.com/agiliopadua/homebrew-extras/issues/2#issuecomment-410141203).

Then I put the `with-x11` option back to tcl-tk #30756,  also I don't know way https://github.com/Homebrew/homebrew-core/commit/ea815d684c7897ecc7712bb41a3012b2facb6722 remove `with-x11`. But I think xcrysden really need `with-x11`, how about bringing it back to tcl-tk?

**Comment by SMillerDev** [comment]
You could maintain your own tap where this is supported

**Comment by commitay** [comment]
We're trying to retire x11 options and dependancies from formulae.

If you need x11 support with `tcl-tk` please do as suggested above and host it in your own tap.
