### ISSUE TITLE
ImportError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by havvg** [Homebrew/homebrew-core#3078]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

All I did was `brew install asciinema`.

```bash
$ asciinema auth
Traceback (most recent call last):
  File "/usr/local/Cellar/asciinema/1.3.0/libexec/bin/asciinema", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'
```

from asciinema/asciinema#169

**Comment by DomT4** [comment]
Bit strange. I _think_ `pkg_resources` is provided by `setuptools`, which Homebrew's `python3` provides. Are you using Homebrew's Python3 or an external one?

**Comment by havvg** [comment]
I just reinstalled python3 by running

```
$ brew reinstall python3
$ pip3 install --upgrade pip setuptools wheel
```

Now it's working, thank you for your hint on python3, I only did it with `python` itself (2.7).

**Comment by monajalal** [comment]
Have the same error 
```
Monas-MacBook-Pro:~ mona$ pip install pip-autoremove
Traceback (most recent call last):
  File "//anaconda/bin/pip", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by ilovezfs** [comment]
@monajalal please open a new issue and fill out the issue template.
