### ISSUE TITLE
Mysql@5.7 install - can't run mysqld from command line or connect via client

### ISSUE THREAD

**Issue by markl181** [Homebrew/homebrew-core#30815]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Y] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [Y] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [No logs - formula did not fail]
- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Brew config:
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6e12fbdf421cc9420dd800d5d5b7e6553588b47b
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A

Brew doctor:
Your system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why) - installed mysql@5.7 formula on factory reset MBP (the mysql client I use [sequel pro] does not support mysql 8). I initially installed mysql formula, when I realized this was now mysql 8 I uninstalled it and installed the new version
- What happened (include command output) - when I attempt to run mysqld from command line I get -'bash: mysqld: command not found'. When I attempt to connect through the mysql client I get 'MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)' or 'MySQL said: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)' if I try a socket connection

- What you expected to happen - should be able to run mysqld from command line and connect through client
- Step-by-step reproduction instructions (by running `brew install` commands)
1. run brew install mysql@5.7
2. run brew services start mysql@5.7
3. run mysqld - command not found

note - this is a factory reset MBP from today, the only other formulae I installed were php@7.1 and httpd. I just tried a different mysql client and the error there is 'Operation failed: File /etc/my.cnf doesn't exist'. It looks like there is a my.cnf in /usr/local/etc but no other file with that name is present

**Comment by JCount** [comment]
This should hopefully be fixed by https://github.com/Homebrew/homebrew-core/pull/30821. 🤞

**Comment by ilovezfs** [comment]
The mysql@5.7 formula is keg_only so you need to add it to your PATH.
```
 echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.bash_profile
```

Note the caveats for `mysql@5.7` mention this when you install it:
```
iMac-TMP:~ joe$ brew install mysql@5.7
==> Downloading https://homebrew.bintray.com/bottles/mysql@5.7-5.7.23.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring mysql@5.7-5.7.23.el_capitan.bottle.tar.gz
==> Caveats
We've installed your MySQL database without a root password. To secure it run:
    mysql_secure_installation

MySQL is configured to only allow connections from localhost by default

To connect run:
    mysql -uroot

mysql@5.7 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have mysql@5.7 first in your PATH run:
  echo 'export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"' >> ~/.bash_profile

For compilers to find mysql@5.7 you may need to set:
  export LDFLAGS="-L/usr/local/opt/mysql@5.7/lib"
  export CPPFLAGS="-I/usr/local/opt/mysql@5.7/include"


To have launchd start mysql@5.7 now and restart at login:
  brew services start mysql@5.7
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql@5.7/bin/mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql@5.7/5.7.23: 317 files, 235.2MB
iMac-TMP:~ joe$
```
