### ISSUE TITLE
brew bump-formula-pr failed

### ISSUE THREAD

**Issue by Loki-Astari** [Homebrew/homebrew-core#30828]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> https://gist.github.com/Loki-Astari/e054427f4133d51a739c713e4ca0fe8d
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
> Trying to update formula with `brew bump-formula-pr`
> An error was generated and I was asked to report the bug.
- What happened (include command output)
> See Below
- What you expected to happen
> Formulae to be updated
- Step-by-step reproduction instructions (by running `brew install` commands)
> See Below

````
> brew clone git@github.com:Loki-Astari/homebrew-core.git
# Stuff removed for brevity.
> brew bump-formula-pr --tag=1.6.0 --revision=1a5399fadcc513b4c67a317746898a8d2c341fbb  --strict thors-serializer
Already up-to-date.
==> replace "1.5.7" with "1.6.0"
==> replace "c391b49a36c7432a3fadbbb3e602bba1f61d4078" with "1a5399fadcc513b4c67a317746898a8d2c341fbb"
Error: key not found: "clone_url"
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:296:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:296:in `block in bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `block in cd'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:271:in `cd'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/bump-formula-pr.rb:272:in `bump_formula_pr'
/usr/local/Homebrew/Library/Homebrew/brew.rb:87:in `<main>'
````

**Comment by ilovezfs** [comment]
@commitay mentioned seeing this the other day. I think it may be caused by certain unexpected results from the GitHub API. It was not reliably reproducible on demand, so you can try again and the problem may just go away.
```
git -C "$(brew --repo homebrew/core)" reset --hard
```

**Comment by Loki-Astari** [comment]
````
> git -C "$(brew --repo homebrew/core)" reset --hard
> brew bump-formula-pr --tag=1.6.0 --revision=1a5399fadcc513b4c67a317746898a8d2c341fbb  --strict thors-serializer
Updated 1 tap (homebrew/core).
==> Updated Formulae
bear                                                                                 firebase-cli
==> replace "1.5.7" with "1.6.0"
==> replace "c391b49a36c7432a3fadbbb3e602bba1f61d4078" with "1a5399fadcc513b4c67a317746898a8d2c341fbb"
remote: Counting objects: 484181, done.
remote: Compressing objects: 100% (179865/179865), done.
remote: Total 484181 (delta 306136), reused 479508 (delta 301467), pack-reused 0
Receiving objects: 100% (484181/484181), 172.80 MiB | 11.89 MiB/s, done.
Resolving deltas: 100% (306136/306136), completed with 3858 local objects.
M	Formula/thors-serializer.rb
Switched to a new branch 'thors-serializer-1.6.0'
[thors-serializer-1.6.0 3f1e66f882] thors-serializer 1.6.0
 1 file changed, 2 insertions(+), 2 deletions(-)
````

Seems to have worked.

**Comment by Loki-Astari** [comment]
Closing as comments above fixed the issue.

> git -C "$(brew --repo homebrew/core)" reset --hard
