### ISSUE TITLE
Rust fails to install on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by anowlcalledjosh** [Homebrew/homebrew-core#30839]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

What I tried: installing ripgrep via `brew install ripgrep`, which depends on Rust.

What happened: installing Rust failed; this is the output:

```
$ brew install ripgrep
==> Installing dependencies for ripgrep: rust
==> Installing ripgrep dependency: rust
==> Downloading https://static.rust-lang.org/dist/rustc-1.28.0-src.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/Users/jh36/homebrew/Cellar/rust/1.28.0 --release-chann
==> make
==> make install
==> Downloading https://static.rust-lang.org/dist/2018-07-20/cargo-0.28.0-x86_64
######################################################################## 100.0%
==> ./install.sh --prefix=/private/tmp/rust-20180803-94140-eaw0j5/rustc-1.28.0-s
==> Cloning https://github.com/rust-lang/cargo.git
Updating /Users/jh36/Library/Caches/Homebrew/rust--cargo--git
remote: Counting objects: 42338, done.
remote: Compressing objects: 100% (10677/10677), done.
remote: Total 42338 (delta 31462), reused 42092 (delta 31223), pack-reused 0
Receiving objects: 100% (42338/42338), 15.34 MiB | 5.58 MiB/s, done.
Resolving deltas: 100% (31462/31462), completed with 179 local objects.
From https://github.com/rust-lang/cargo
 * [new tag]         0.29.0     -> 0.29.0
 * [new tag]           0.1.0      -> 0.1.0
 * [new tag]           0.10.0     -> 0.10.0
 * [new tag]           0.11.0     -> 0.11.0
 * [new tag]           0.12.0     -> 0.12.0
 * [new tag]           0.13.0     -> 0.13.0
 * [new tag]           0.14.0     -> 0.14.0
 * [new tag]           0.2.0      -> 0.2.0
 * [new tag]           0.3.0      -> 0.3.0
 * [new tag]           0.4.0      -> 0.4.0
 * [new tag]           0.5.0      -> 0.5.0
 * [new tag]           0.6.0      -> 0.6.0
 * [new tag]           0.7.0      -> 0.7.0
 * [new tag]           0.8.0      -> 0.8.0
 * [new tag]           0.9.0      -> 0.9.0
 * [new tag]           v0.0.1-pre -> v0.0.1-pre
==> Checking out tag 0.29.0
Previous HEAD position was 1e95190e Auto merge of #5577 - matklad:revert-deps-beta, r=alexcrichton
HEAD is now at 96a2c7d1 Auto merge of #5722 - alexcrichton:beta-next, r=alexcrichton
HEAD is now at 96a2c7d1 Auto merge of #5722 - alexcrichton:beta-next, r=alexcrichton
==> cargo install --root /Users/jh36/homebrew/Cellar/rust/1.28.0
Last 15 lines from /Users/jh36/Library/Logs/Homebrew/rust/05.cargo:
                                                    ^
<scratch space>:25:1: note: expanded from here
__AVAILABILITY_INTERNAL__MAC_10_7_DEP__MAC_10_13_MSG
^
14 errors generated.
make[2]: *** [src/CMakeFiles/git2internal.dir/streams/stransport.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/git2internal.dir/all] Error 2
make: *** [all] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /private/tmp/rust-20180803-94140-eaw0j5/rustc-1.28.0-src/.brew_home/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.31/src/lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


READ THIS: https://docs.brew.sh/Troubleshooting
```

What I expected: Rust should build and install successfully.

`brew gist-logs rust`: https://gist.github.com/2ebcaa3a3b82c5eeeac3a3bda670a275

Unfortunately I'm unable to fix either of the warnings `brew doctor` reports, sorry.

This looks maybe related to #29360?

**Comment by ilovezfs** [comment]
If you install Xcode.app, then is the build successful?

**Comment by anowlcalledjosh** [comment]
I'm not that familiar with macOS, but it looks like installing Xcode will be more trouble than I can really justify for now, sorry – combination of me a) not having root, and b) not needing a Rust install enough to justify trying to get someone to install it for me. Thanks anyway!

Feel free to close if that's the only sensible thing to try.

**Comment by javian** [comment]
Is there a reason why you can't use the bottled versions ?

**Comment by DomT4** [comment]
OP has Homebrew installed in a non-standard location and the `rust` bottle isn't `cellar :any`, sadly.
