### ISSUE TITLE
Allow python 3.6 installation

### ISSUE THREAD

**Issue by erseco** [Homebrew/homebrew-core#30870]
Some packages are still not compatible with python 3.7 so will be useful allowing to install the 3.6 version

**Comment by SMillerDev** [comment]
It might be better to report the issues to the upstream maintainers, homebrew can't really be shipping old software because some things don't work with the new stuff.

**Comment by erseco** [comment]
Yes, I reported (and PRed) some libraries but meanwhile I will still use python 3.6 (zappa and hug reqs), for that, I install the formula of the last python 3.6 commit:
´´´
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
´´´
as viewed in https://stackoverflow.com/questions/51125013/how-can-i-install-a-previous-version-of-python-3-in-macos-using-homebrew

Best regards!
