### ISSUE TITLE
AdoptOpenJDK Formula?

### ISSUE THREAD

**Issue by gjmveloso** [Homebrew/homebrew-core#30872]
Hi Team,

Does someone know any limitation that prevent us from creating a Formula targeting [AdoptOpenJDK](https://adoptopenjdk.net/) installation on macOS.

Just installed it from the installer but would love to have this auto-updated/managed by Homebrew.

Probably we faced issues on installing java and other Java binaries that I'm not aware of and prefer to hear your thoughts before starting coding and proposing a openjdk formula :)

Thanks,
Gustavo

**Comment by SMillerDev** [comment]
There's a Java cask already, and I'd say the non-binary software requirement here https://docs.brew.sh/Acceptable-Formulae kinda excludes AdoptOpenJDK from normal formula.

**Comment by iMichka** [comment]
Hi. Yes, these are prebuilt binaries, so this can not be added here. There is a java cask, so there could be a AdoptOpenJDK cask too I guess. Feel free to submit a pull request there: https://github.com/Homebrew/homebrew-cask
