### ISSUE TITLE
Would not install - MacOS 10.6.8 - curl issue?

### ISSUE THREAD

**Issue by mrkapqa** [Homebrew/homebrew-core#30882]
Hello ,

i am trying to install Homebrew with this formula

 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

however i get error here

==> Downloading and installing Homebrew...
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Failed during: /bin/bash -o pipefail -c '/usr/bin/curl -fsSL https://github.com/Homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1'

i have installed curl via macports

curl --version
curl 7.61.0 (x86_64-apple-darwin10.8.0) libcurl/7.61.0 OpenSSL/1.0.2o zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5)
Release-Date: 2018-07-11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy PSL

**Comment by mrkapqa** [comment]
seems to install now after

sudo port install git

**Comment by mrkapqa** [comment]
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
curl: (35) Unknown SSL protocol error in connection to homebrew.bintray.com:443 
==> Downloading https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.3.7/portable-ruby-2.3.7.leopard_64.bottle.tar.gz
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Failed to download https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.leopard_64.bottle.tar.gz and https://github.com/Homebrew/homebrew-portable-ruby/releases/download/2.3.7/portable-ruby-2.3.7.leopard_64.bottle.tar.gz!

Do not file an issue on GitHub about this: you will need to figure out for
yourself what issue with your internet connection restricts your access to
both Bintray (used for Homebrew bottles/binary packages) and GitHub
(used for Homebrew updates).
Error: Failed to install vendor Ruby.
Error: Git must be installed and in your PATH!

**Comment by SMillerDev** [comment]
We're not supporting macOS 10.6 anymore, and the default curl is too old to connect to modern servers. You could try https://github.com/mistydemeo/tigerbrew though.

**Comment by mrkapqa** [comment]
Hello ,

thank you , i will try that out on PPC Mac .

But on Intel Mac Pro ,

why does Homebrew

brew config


not pick up the updated curl i have installed through macports? or the git?

Thank you.

Am 08.08.18 um 08:49 schrieb Sean Molenaar:

**Comment by SMillerDev** [comment]
It's not just for PPC. It's also just for versions that are too old to be supported by homebrew, like your version. And mac ports is not related to homebrew so they don't necessarily share installs of software.

**Comment by rdp** [comment]
See also https://apple.stackexchange.com/questions/280203/install-old-version-of-homebrew-on-snow-leopard/317350#317350
