### ISSUE TITLE
Error: SHA256 mismatch when installing git-lfs 

### ISSUE THREAD

**Issue by IcyW** [Homebrew/homebrew-core#30912]
A question from [here](https://github.com/git-lfs/git-lfs/issues/3174#issue-348170144)

I got 
> ==> Downloading https://github.com/git-lfs/git-lfs/archive/v2.1.1.tar.gz
==> Downloading from https://codeload.github.com/git-lfs/git-lfs/tar.gz/v2.1.1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 655c1e9bf931afb958c2b81de5c1c38b3ebd6831a04ca5fdcf58cba05e2948d8
Actual: 096bb2bfbb61313ba299c919bcb49fa92cfb1bdcdcbe06d8375dfdb672886aa9

after `brew install git-lfs`.

Running on MacOS High Sierra, 10.13.6.

**Comment by DomT4** [comment]
That version is pretty outdated. What's your `brew config`?

**Comment by IcyW** [comment]
@DomT4 
> HOMEBREW_VERSION: >1.2.0 (no git repository)
ORIGIN: http://android.oa.com/brew
HEAD: 73cd2a1db885d25fc5d91bc7d7aab6518d5c97c7
Last commit: 11 months ago
Core tap ORIGIN: http://android.oa.com/homebrew-core
Core tap HEAD: d4d47e537962f1f41c39ab82b55ae84d1d41183d
Core tap last commit: 1 year, 2 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: http://android.oa.com/homebrew/
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/bin/python3.6
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 1.8.0_181, 1.6.0_65-b14-468
macOS: 10.13.6-x86_64
Xcode: 9.4.1
CLT: 9.4.1.0.1.1528165917
X11: N/A

**Comment by DomT4** [comment]
```
ORIGIN: http://android.oa.com/brew
HEAD: 73cd2a1
Last commit: 11 months ago
Core tap ORIGIN: http://android.oa.com/homebrew-core
Core tap HEAD: d4d47e5
Core tap last commit: 1 year, 2 months ago
```

Well, there's an issue. Is that origin/core origin change a deliberate choice? It looks like there's some kind of issue updating against those origins.

**Comment by IcyW** [comment]
Oh I see.
Would you pls tell me how to change the `Core tap ORIGIN`?

**Comment by DomT4** [comment]
It's probably useful to check your shell profile to work out where it's being set. To reset it to the official upstream:

```
git -C /usr/local/Homebrew remote set-url origin https://github.com/Homebrew/brew.git
```
and:
```
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core remote set-url origin https://github.com/Homebrew/homebrew-core.git
```

**Comment by SMillerDev** [comment]
You probably also need to change the git repo for homebrew/brew (on mobile right now so I can't give you the commands) but your version of brew is also a lot behind.

**Comment by SMillerDev** [comment]
Wrong button

**Comment by DomT4** [comment]
> Another syntax error occurred after I tried brew update and brew install git-lfs

You're far enough behind that I'd try this:
```
cd $(brew --repo) && git fetch && git reset --hard origin/master && cd $(brew --repo homebrew/core) && git fetch && git reset --hard origin/master && brew update
```

**Comment by IcyW** [comment]
Thank you so much!

**Comment by DomT4** [comment]
Everything resolved?

**Comment by IcyW** [comment]
Yep git-lfs 2.5.1 is already installed and up-to-date! 👍

**Comment by DomT4** [comment]
Great! Glad things seem to be working for you again.
