### ISSUE TITLE
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!

### ISSUE THREAD

**Issue by xiaoyu1201** [Homebrew/homebrew-core#30917]
I'm trying to install Homebrew on Mac ios version 10.13.5 , and here is the error information:

```
HEAD is now at 7ed3be53 Merge pull request #4642 from mistydemeo/mac_sdk_path_teerror: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
Updated 1 tap (miktex/miktex).
==> Cleaning up /Library/Caches/Homebrew...
==> Migrating /Library/Caches/Homebrew to /Users/song/Library/Caches/Homebrew...
==> Deleting /Library/Caches/Homebrew...
==> Updated Formulae
miktex/miktex/miktex ✔
Error: Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gobject-introspection.rb:14:in `<class:GobjectIntrospection>'
Please report this to the homebrew/core tap!
Or, even better, submit a PR to fix it!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-core/issues
Failed during: /usr/local/bin/brew update --force
```
When I run brew doctor, there is the same error

`Error: Calling 'depends_on ... => :run' is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gobject-introspection.rb:14:in `<class:GobjectIntrospection>'`

**Comment by SMillerDev** [comment]
This was removed in March, I think you need to reset your homebrew-core tap to the latest version. You can do this by running `brew update-reset`.

**Comment by xiaoyu1201** [comment]
I have tried the `brew update-reset`
Still, it doesn't work, the information is as follow:

`==> Fetching /usr/local/Homebrew...

==> Resetting /usr/local/Homebrew...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to and reset branch 'master'

==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
remote: Counting objects: 122745, done.
remote: Compressing objects: 100% (34895/34895), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

==> Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.

==> Fetching /usr/local/Homebrew/Library/Taps/miktex/homebrew-miktex...

==> Resetting /usr/local/Homebrew/Library/Taps/miktex/homebrew-miktex...
Branch 'master' set up to track remote branch 'master' from 'origin'.
Reset branch 'master'
Your branch is up to date with 'origin/master'.`

**Comment by xiaoyu1201** [comment]
I have tried the 

`git config --global http.postBuffer 524288000`

but still the error occurs

**Comment by SMillerDev** [comment]
Is there any way you can try this with a different internet connection? Because it doesn't seem to be stable enough to update brew.

**Comment by tocaata** [comment]
@xiaoyu1201 you can use tsinghua mirror. Go to https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/.
But this issue still exists with this mirror. Follow this steps to fix it.
git clone https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git. 
copy the directory homebrew-core to /usr/local/Homebrew/Library/Taps/homebrew/.

**Comment by DomT4** [comment]
Let us know if any further help is required here, but closing for now.
