### ISSUE TITLE
gcc v6 does not support isl v0.20

### ISSUE THREAD

**Issue by cal2u** [Homebrew/homebrew-core#31006]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Please always confirm that you:
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/cal2u/7b288ed8d7a4172fc90faa6419e7bdb7
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):
`brew install gcc@6`
Installing gcc 6 or 7 is a requirement for mujoco-py (https://github.com/openai/mujoco-py/issues/25). I have gcc 8.1.0 currently (installed via homebrew).
- What happened (include command output):
Install failed due to issue with isl
```
==> ../configure --build=x86_64-apple-darwin17.7.0 --prefix=/usr/local/Cellar/gc
==> make bootstrap
Last 15 lines from /Users/caleb/Library/Logs/Homebrew/gcc@6/02.make:
                 ^
11 errors generated.
make[3]: *** [graphite-isl-ast-to-gimple.o] Error 1
../../gcc/graphite-optimize-isl.c:59:19: error: use of undeclared identifier 'isl_space_dim'
  unsigned dims = isl_space_dim (space, isl_dim_set);
                  ^
../../gcc/graphite-optimize-isl.c:62:3: error: use of undeclared identifier 'isl_space_free'
  isl_space_free (space);
  ^
2 errors generated.
make[3]: *** [graphite-optimize-isl.o] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2
```
- What you expected to happen:
I expected the install to succeed
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install isl`
`brew install gcc@6`

Running `brew switch isl 0.19` before `brew install gcc@6` fixed the issue.

**Comment by cal2u** [comment]
This patch might be relevant - not sure how brew handles formula versioning #30639

**Comment by iMichka** [comment]
Hi. Thanks for reporting this. Did you try out the patch locally? If it works for you, would you mind opening a pull request for this?
https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md

**Comment by rakkesh** [comment]
@jrabary you could try the relevant patch mentioned by @cal2u,

```diff
diff --git a/Formula/gcc@6.rb b/Formula/gcc@6.rb
index 0d39521c8f..4419bca225 100644
--- a/Formula/gcc@6.rb
+++ b/Formula/gcc@6.rb
@@ -53,6 +53,10 @@ class GccAT6 < Formula
     end
   end

+  # isl 0.20 compatibility
+  # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86724
+  patch :DATA
+
   def install
     # GCC will suffer build errors if forced to use a particular linker.
     ENV.delete "LD"
@@ -191,3 +195,16 @@ class GccAT6 < Formula
     end
   end
 end
+
+__END__
+diff --git a/gcc/graphite.h b/gcc/graphite.h
+index 4e0e58c..be0a22b 100644
+--- a/gcc/graphite.h
++++ b/gcc/graphite.h
+@@ -37,6 +37,8 @@ along with GCC; see the file COPYING3.  If not see
+#include <isl/schedule.h>
+#include <isl/ast_build.h>
+#include <isl/schedule_node.h>
++#include <isl/id.h>
++#include <isl/space.h>
+typedef struct poly_dr *poly_dr_p;
```

**Comment by cal2u** [comment]
Hi, sorry for not following up sooner. I'm testing the patch now and will hopefully be submitting a pull request shortly.

**Comment by hjelmn** [comment]
gcc@8 has this same problem

**Comment by DomT4** [comment]
`gcc@8` was fixed in 02d6827fa94956d9515e75ed21571d0822b4c0d3. If it isn't you may need to make sure `brew update` is functioning as expected for you by looking at `brew config` and the `Core tap last commit` output.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/pull/31105#issuecomment-413256747

**Comment by hjelmn** [comment]
Yeah, meant to say gcc@7. Just did a brew update then brew install gcc@7 and got:

```
==> ../configure --build=x86_64-apple-darwin17.7.0 --prefix=/usr/local/Cellar/gcc@7/7.3.0 --libdir=/usr/local/Cellar/gcc@7/7.3.0/lib/gcc/7 --enable-
==> make
Last 15 lines from /Users/L151441/Library/Logs/Homebrew/gcc@7/02.make:
                 ^
11 errors generated.
make[3]: *** [graphite-isl-ast-to-gimple.o] Error 1
../../gcc/graphite-optimize-isl.c:57:19: error: use of undeclared identifier 'isl_space_dim'
  unsigned dims = isl_space_dim (space, isl_dim_set);
                  ^
../../gcc/graphite-optimize-isl.c:60:3: error: use of undeclared identifier 'isl_space_free'
  isl_space_free (space);
  ^
2 errors generated.
make[3]: *** [graphite-optimize-isl.o] Error 1
rm gcc.pod
make[2]: *** [all-stage1-gcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
I posted a new comment after I caught your edit. Essentially if anyone wants to submit the same patch for `gcc@7` we'd be happy to accept it.
