### ISSUE TITLE
neo4j installed on OSX with Java > 1.8 prohibts login

### ISSUE THREAD

**Issue by thinkberg** [Homebrew/homebrew-core#31090]
To help us debug your issue please explain:
- What you were trying to do (and why)
Run neo4j on an up-to-dat machine.

- What happened (include command output)
Login into neo4j failed for unknown reasons.

- What you expected to happen
Login to work.

- Step-by-step reproduction instructions (by running `brew install` commands)
  - Install Java 1.9 or Java 1.10 and use `brew services start neo4j`, check that it's running using the latest java version (1.10 in my case)
  - Try to open `localhost:7474` and login using neo4j / neo4j as user/password (if new install)
  - it will fail and in the logs you find a strange error for a UTF-8 encoder missing
- remove Java 1.9/1.10 and it works again

I think the formula may want check and set the correct version and fail if no Java 1.8 is installed for now.

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/aff452c8548e75a25c011370e11095482f8c9878.
