### ISSUE TITLE
Cannot force link to node 8 install

### ISSUE THREAD

**Issue by dschinkel** [Homebrew/homebrew-core#31186]
**Tried to downgrade Node 10 to Node 8.  Here is what I tried:**

`brew unlink node`
`brew install node@8`
`echo 'export PATH="/usr/local/opt/node@6/bin:$PATH"' >> ~/.bash_profile`
`brew link --force node@8`

**Then I get:**

Error: Could not symlink lib/node_modules/npm/appveyor.yml
Target /usr/local/lib/node_modules/npm/appveyor.yml
already exists. You may want to remove it:
  rm '/usr/local/lib/node_modules/npm/appveyor.yml'

To force the link and overwrite all conflicting files:
  brew link --overwrite node@8

To list all files that would be deleted:
  `brew link --overwrite --dry-run node@8`

**And if I try running** `brew link --overwrite node@8` I get:

**Warning: node@8 is keg-only and must be linked with --force**

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/node@8/bin:$PATH"' >> ~/.zshrc

**I checked and `.zshrc` and also my `.bash_profil`both have that path already.**

**If I run** `brew link --overwrite --dry-run node@8` the list is huge.

I don't understand why this just doesn't work.  I don't see what else I'm missing here.

**Comment by MikeMcQuaid** [comment]
What about `brew link --overwrite --force node@8`?

**Comment by dschinkel** [comment]
yea doesn't work either:

Linking /usr/local/Cellar/node@8/8.11.3_1... 4287 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/node@8/bin:$PATH"' >> ~/.zshrc
