### ISSUE TITLE
brew install gcc --HEAD failing on 10.13.6

### ISSUE THREAD

**Issue by hyukjaepark** [Homebrew/homebrew-core#31241]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? ==> It says Error: No logs.

> $ brew gist-logs gcc                                                                                                            
Error: No logs.

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

> $ brew config                                                                                                                           
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6a245c05110c240e680da594c2cc6038998b82e
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0792f4bac27343525a119195467ae14c8c0a31b4
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A

> $ brew doctor                                                                                                                           
Your system is ready to brew.
                                                                                                                                           
 
To help us debug your issue please explain:
- What you were trying to do (and why) 
I was trying to brew install gcc --HEAD so that I can try c++17 features
- What happened (include command output) 
The formula failed with the following error message:

......
A    /private/tmp/d20180818-8190-yfj4q9/zlib/zutil.h
Export complete.
==> Patching
patching file gcc/graphite.h
Hunk #1 FAILED at 37.
1 out of 1 hunk FAILED -- saving rejects to file gcc/graphite.h.rej
Error: undefined method `ErrorDuringExecution' for Utils:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils/popen.rb:18:in `safe_popen_write'
/usr/local/Homebrew/Library/Homebrew/patch.rb:70:in `apply'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1104:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1104:in `patch'
/usr/local/Homebrew/Library/Homebrew/build.rb:119:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1117:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:564:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2036:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:120:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:189:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:188:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:115:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:93:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2014:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1112:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:113:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:564:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:110:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:191:in `<main>'
                                                                 
- What you expected to happen
I expected gcc to be installed successfully
- Step-by-step reproduction instructions (by running `brew install` commands)
First I ran "brew upgrade" and "brew update"
Since I installed "gcc --HEAD" before, it was trying to update it, but failed with the same error message above.
After multiple tries of "brew update" and getting the same error messages, I uninstalled the formula by running "brew uninstall gcc"
then, I reran "brew update" to update other formulas
After running "brew doctor" to make sure everything is ok, I ran "brew install gcc --HEAD", but got the same error message.

Any help on this would be greatly appreciated.

Thanks,

HJP

**Comment by DomT4** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/31242/commits/bfe1e3af97833b534e668c3137ea85301e485ffa. Let us know if that's not the case after a `brew update`.

**Comment by hyukjaepark** [comment]
thanks for quick fix!
