### ISSUE TITLE
OpenVdb 5.2 update..

### ISSUE THREAD

**Issue by oscarbg** [Homebrew/homebrew-core#31255]

**Comment by SMillerDev** [comment]
Please fill out the issue template.

**Comment by DomT4** [comment]
You're welcome to submit a pull request but otherwise it's a case of waiting for someone else to get to the update. As @SMillerDev notes, please don't erase the issue template in future, thanks.

**Comment by oscarbg** [comment]
Ok.. thanks..

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/15d17c2218869da29c3623aff479c1259a047811.
