### ISSUE TITLE
nginx Formula does not use the latest OpenSSL version because of "Passenger"

### ISSUE THREAD

**Issue by ryanrbftp** [Homebrew/homebrew-core#31307]
We have noticed the homebrew formula for nginx is purposely using the older branch of OpenSSL 1.0.x instead of the latest 1.1 branch.

It seems to be doing this because of the passenger module option:
`depends_on "openssl" # don't switch to 1.1 until passenger is switched, too`

Hardly anybody uses passenger and because the formula is using the old OpenSSL version, nobody can make use of TLSv3 that nginx supports.

Please, can the formula be updated to compile nginx with OpenSSL 1.1 branch?

**Comment by DomT4** [comment]
We're not moving anything over to `openssl@1.1` until at least the first 1.1.1 stable release, which will contain the recently finalised TLSv1.3 rather than any of the prior draft versions. After that point we will _consider_ moving specific formulae across in certain circumstances.
