### ISSUE TITLE
jenv does not work out of the box

### ISSUE THREAD

**Issue by mmoehring** [Homebrew/homebrew-core#31390]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/04a69ca09c98759f8d18981c58b419b3
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
I installed jenv. The installation was successful but does not work out of the box.

Adding a JVM fails
-------------------

    $ jenv add /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home/
    ln: /Users/mmoehring/.jenv/versions/oracle64-10.0.2: No such file or directory

This is because because the installation does not create ``~/.jenv/versions``. After creating the directory the command worked. There is also issue https://github.com/gcuisinier/jenv/issues/207. I'm not sure if this is a jenv or a Homebrew bug.

Switching of JVMs fails
-----------------------
Java does not use the correct version set via ``jenv local`` or ``jenv global``.
According to https://github.com/gcuisinier/jenv#gettings-started you have to set

        $ echo 'eval "$(jenv init -)"' >> ~/.bash_profile

There is a test in the formula which uses ``jenv init`` but I think it does not set it in the .bash_profile (I don't know ruby.)
There is also no documentation for setting it manually, like in other formulas. After adding the line to bash_profile (and sourcing) the JVM switching worked.

**Comment by mmoehring** [comment]
As I just found out here https://github.com/gcuisinier/jenv/issues/77#issuecomment-161571251 the directory ``.jenv/versions`` should be created by the ``init``command when restarting the shell (it does). So the first bug ("Adding a JVM fails") is not a bug. It works as intended.

**Comment by MikeMcQuaid** [comment]
> I'm not sure if this is a jenv or a Homebrew bug.

This is a `jenv` bug. We do not ever modify your home directory on installation.



> There is also no documentation for setting it manually, like in other formulas.

We do not document things that are not Homebrew-exclusive information. This is prominent in the README for the tool.
