### ISSUE TITLE
vtk failed to build on 10.13

### ISSUE THREAD

**Issue by darraghr** [Homebrew/homebrew-core#31400]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install a program called engrid, but am getting an error: `fatal error: 'QVTKWidget.h' file not found`. Someone suggested installing `vtk --with-qt` would fix the problem, however I am having trouble with that as well.

- What happened (include command output)
When I use `brew install vtk --with-qt` the installation does not complete. The gist output is here: https://gist.github.com/darraghr/a37b21259dcb4322b059d7213afe0b38 and this is the terminal output:

> $ brew install vtk --with-qt
> ==> Downloading https://www.vtk.org/files/release/8.1/VTK-8.1.1.tar.gz
> Already downloaded: /Users/darraghr/Library/Caches/Homebrew/vtk--8.1.1.tar.gz
> ==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/vtk/8.1.1 -DC
> ==> make
> Last 15 lines from /Users/darraghr/Library/Logs/Homebrew/vtk/02.make:
> cd /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Wrapping/Tools && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/gcc-7 -DVTK_IN_VTK -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Wrapping/Tools -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Wrapping/Tools -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Common/Core -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Common/Core -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Utilities/KWSys -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Utilities/KWIML -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Utilities/KWIML -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Utilities/KWSys  -DNDEBUG   -o CMakeFiles/vtkWrappingTools.dir/vtkWrapText.c.o   -c /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Wrapping/Tools/vtkWrapText.c
> [  0%] Building CXX object Utilities/KWSys/vtksys/CMakeFiles/vtksys.dir/SystemInformation.cxx.o
> cd /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Utilities/KWSys/vtksys && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/g++-7  -DKWSYS_NAMESPACE=vtksys -DVTK_IN_VTK -Dvtksys_EXPORTS -DKWSYS_BUILD_SHARED=1 -DKWSYS_CXX_HAS_ATOL=1 -DKWSYS_CXX_HAS_ATOLL=1 -DKWSYS_CXX_HAS_GETLOADAVG=1 -DKWSYS_SYSTEMINFORMATION_HAS_BACKTRACE=1 -DKWSYS_SYSTEMINFORMATION_HAS_CPP_DEMANGLE=1 -DKWSYS_SYSTEMINFORMATION_HAS_SYMBOL_LOOKUP=1 -DKWSYS_SYS_HAS_IFADDRS_H=1 -DKWSYS_USE_LONG_LONG=1 -DSIZEOF_VOID_P=8 -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Utilities/KWSys -I/tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Utilities/KWSys  -DNDEBUG -fPIC   -std=c++11 -o CMakeFiles/vtksys.dir/SystemInformation.cxx.o -c /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/Utilities/KWSys/vtksys/SystemInformation.cxx
> [  0%] Linking C static library ../../lib/libvtkWrappingTools-8.1.a
> cd /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Wrapping/Tools && /usr/local/Cellar/cmake/3.12.1/bin/cmake -P CMakeFiles/vtkWrappingTools.dir/cmake_clean_target.cmake
> cd /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Wrapping/Tools && /usr/local/Cellar/cmake/3.12.1/bin/cmake -E cmake_link_script CMakeFiles/vtkWrappingTools.dir/link.txt --verbose=1
> /usr/bin/ar qc ../../lib/libvtkWrappingTools-8.1.a  CMakeFiles/vtkWrappingTools.dir/vtkParse.tab.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseData.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseMain.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseExtras.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseMangle.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseMerge.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseString.c.o CMakeFiles/vtkWrappingTools.dir/vtkParseHierarchy.c.o CMakeFiles/vtkWrappingTools.dir/vtkParsePreprocess.c.o CMakeFiles/vtkWrappingTools.dir/vtkWrap.c.o CMakeFiles/vtkWrappingTools.dir/vtkWrapText.c.o
> /usr/bin/ranlib ../../lib/libvtkWrappingTools-8.1.a
> [  0%] Built target vtkWrappingTools
> [  1%] Linking CXX shared library ../../../lib/libvtksys-8.1.dylib
> cd /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Utilities/KWSys/vtksys && /usr/local/Cellar/cmake/3.12.1/bin/cmake -E cmake_link_script CMakeFiles/vtksys.dir/link.txt --verbose=1
> /usr/local/Homebrew/Library/Homebrew/shims/mac/super/g++-7   -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names   -compatibility_version 1.0.0 -current_version 1.0.0 -o ../../../lib/libvtksys-8.1.1.dylib -install_name /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/lib/libvtksys-8.1.1.dylib CMakeFiles/vtksys.dir/ProcessUNIX.c.o CMakeFiles/vtksys.dir/Base64.c.o CMakeFiles/vtksys.dir/EncodingC.c.o CMakeFiles/vtksys.dir/MD5.c.o CMakeFiles/vtksys.dir/System.c.o CMakeFiles/vtksys.dir/Directory.cxx.o CMakeFiles/vtksys.dir/DynamicLoader.cxx.o CMakeFiles/vtksys.dir/EncodingCXX.cxx.o CMakeFiles/vtksys.dir/Glob.cxx.o CMakeFiles/vtksys.dir/RegularExpression.cxx.o CMakeFiles/vtksys.dir/SystemTools.cxx.o CMakeFiles/vtksys.dir/CommandLineArguments.cxx.o CMakeFiles/vtksys.dir/FStream.cxx.o CMakeFiles/vtksys.dir/SystemInformation.cxx.o
> cd /tmp/vtk-20180823-50175-1f1sjov/VTK-8.1.1/build/Utilities/KWSys/vtksys && /usr/local/Cellar/cmake/3.12.1/bin/cmake -E cmake_symlink_library ../../../lib/libvtksys-8.1.1.dylib ../../../lib/libvtksys-8.1.1.dylib ../../../lib/libvtksys-8.1.dylib
> [  1%] Built target vtksys
> make: *** [all] Error 2
> 
> READ THIS: https://docs.brew.sh/Troubleshooting

- What you expected to happen
I expected the installation to complete with no errors as is usually the case with other formulas.

- Step-by-step reproduction instructions (by running `brew install` commands)
I get the error doing `brew install vtk --with-qt`, `brew install vtk --with-python --with-qt`, `brew install vtk --without-python@2 --with-qt`, `brew install vtk --with-python --without-python@2 --with-qt`, and then the same if I install vtk without qt, and then try reinstalling with any of those options.

**Comment by yguclu** [comment]
The same thing has just happened to me on Mac OS 10.11.6 with Xcode 8.2.1 and its command line tools. Installing VTK with the command
```
brew install vtk --with-python --without-python@2 --with-qt
```
fails just as above. After searching in the verbose output I think this is the error:
```
[  6%] Tcl Wrapping - generating vtkInformationInformationVectorKeyTcl.cxx
cd /tmp/vtk-20180828-52214-10s0xhd/VTK-8.1.1/build/Common/Core && ../../bin/vtkWrapTcl-8.1 @/tmp/vtk-20180828-52214-10s0xhd/VTK-8.1.1/build/Common/Core/vtkCommonCoreTCL.Release.args -o /tmp/vtk-20180828-52214-10s0xhd/VTK-8.1.1/build/Common/Core/vtkInformationInformationVectorKeyTcl.cxx /tmp/vtk-20180828-52214-10s0xhd/VTK-8.1.1/Common/Core/vtkInformationInformationVectorKey.h
/tmp/vtk-20180828-52214-10s0xhd/VTK-8.1.1/Wrapping/PythonCore/vtkPythonArgs.cxx:105:7: error: assigning to 'char *' from incompatible type 'const char *'
    a = PyUnicode_AsUTF8(o);
      ^ ~~~~~~~~~~~~~~~~~~~
/tmp/vtk-20180828-52214-10s0xhd/VTK-8.1.1/Wrapping/PythonCore/vtkPythonArgs.cxx:311:11: note: in instantiation of function template specialization 'vtkPythonGetStringValue<char>' requested here
          vtkPythonGetStringValue(o, a, "string or None required"));
          ^
```

**Comment by lowderchris** [comment]
I'm still running into this issue. After the release of macOS Mojave, I'll attempt to recreate this on a fresh install of the OS unless there are any fixes in the meantime.

**Comment by daspecster** [comment]
So this worked for me to install `vtk` on Mojave 10.14

```
brew install vtk --with-python --without-python@2 --HEAD
```

**Comment by FieldMrFive** [comment]
> So this worked for me to install `vtk` on Mojave 10.14
> 
> ```
> brew install vtk --with-python --without-python@2 --HEAD
> ```

yes, compile vtk from master on Mojave solves it.

**Comment by lowderchris** [comment]
I can confirm that on a fresh install of Mojave,

`brew install vtk --with-python --without-python@2 --with-qt --HEAD`

worked just fine to install. Of course, now pip3 isn't able to see it as a functioning version of VTK, but that's another story...

**Comment by fxcoudert** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-core/pull/33076
