### ISSUE TITLE
srtp not built as part of gstreamer-plugins-bad package, missing dependency on srtp

### ISSUE THREAD

**Issue by drott** [Homebrew/homebrew-core#31426]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I am trying to run webrtc examples on gstreamer with the scripts from https://github.com/centricular/gstwebrtc-demos

There are a couple of obstacles on the way to getting gstreamer-webrtc working correctly on Mac, one of them is that the `srtp` plugin is not built due to libsrtp / srtp package not being a dependency of `gstreamer-plugins-bad`. I suggest to add it, at least as an optional dependency.

- What happened (include command output)

gstreamer webrtc connection cannot be established due to missing plugin srtp.

- What you expected to happen

webrtc connection to be established.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install brew gst-plugins-bad`
=> fails

`brew edit gst-plugins-bad`
Add
`depends_on "srtp" => :optional`

Rebuild with 
`brew reinstall --debug  --verbose --build-from-source --with-srtp --with-gnutls gst-plugins-bad `

Profit! As the plugin is now there.

**Comment by DomT4** [comment]
We'll consider a PR, if you wish to submit one.
