### ISSUE TITLE
compile error by installing cgal

### ISSUE THREAD

**Issue by krikox** [Homebrew/homebrew-core#315]
### Bug reports:

I try to install cgal with brew, but I get the error message after the downloading:

> Downloading https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.7/CGAL-4.7.tar.gz
> ######################################################################## 100,0%Error: Failed to download resource "cgal"
> Download failed: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.7/CGAL-4.7.tar.gz

After downloading and instlling it manually I get the error:

> 
> Error: compile error
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:1: Invalid char `\037' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:1: Invalid char `\213' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:1: Invalid char `\010' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:1: Invalid char `\010' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:1: Invalid char `\334' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:1: Invalid char `\232' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: Invalid char `\246' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: Invalid char `\325' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: Invalid char `\033' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: Invalid char `\332' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: Invalid char `\243' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: Invalid char `\356' in expression
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4: syntax error, unexpected tCONSTANT, expecting $end
> ...{K▒▒iw:▒▒v▒u▒A▒e▒q▒"▒▒▒▒l܆▒?_]d;$Y▒▒▒▒K|▒?...
>                               ^
> Please report this bug:
>     https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
> /home/krikox/.cache/Homebrew/CGAL-4.7.tar.gz:4:in `load_formula'
> /home/krikox/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
> /home/krikox/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
> /home/krikox/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
> /home/krikox/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
> /home/krikox/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
> /home/krikox/.linuxbrew/Library/Homebrew/extend/ARGV.rb:18:in `formulae'
> /home/krikox/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
> /home/krikox/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
> /home/krikox/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'
> /home/krikox/.linuxbrew/Library/brew.rb:83:in `send'
> /home/krikox/.linuxbrew/Library/brew.rb:83

I've found somewhere the hint that it could be caused due to the wrong ruby environment. For that reason I've downgraded it to the version 1.8 but it haven't influenced anything.

(there are no logs in brew gist-logs cgal)

**Comment by dunn** [comment]
Somehow the URL got munged; it should be https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.7/CGAL-4.7.tar.gz

You can `brew edit cgal` to fix that locally until #321 is merged.

**Comment by MikeMcQuaid** [comment]
> /home/krikox/.linuxbrew/Library/brew.rb:83

We don't support Linux here, I'm afraid, please report this to Linuxbrew. Also, https://github.com/Homebrew/homebrew-core/pull/321 was merged so this may be no longer required.
