### ISSUE TITLE
Can't instal homebrew

### ISSUE THREAD

**Issue by subaiku** [Homebrew/homebrew-core#3152]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Sorry I am not a coder, just trying to figure out how to install homebrew. I keep getting this error:

Library/Aliases: Can't remove already-existing dir
Library/Formula: Can't remove already-existing dir
tar: Error exit delayed from previous errors.
Failed during: /bin/bash -o pipefail -c '/usr/bin/curl -fsSL https://github.com/Homebrew/brew/tarball/master | /usr/bin/tar xz -m --strip 1'

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by DomT4** [comment]
It looks like you've got a partial installation of Homebrew in `/usr/local` already? You may wish to use the uninstall script referenced [on this page](https://github.com/Homebrew/install) to remove that before reinstalling again.

**Comment by DomT4** [comment]
Closing as dead, but please shout if we can offer any assistance here still. Thanks!
