### ISSUE TITLE
pgloader fails to build

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-core#31591]
```
==> make pgloader-standalone BUILDAPP=buildapp
buildapp    --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                       --sbcl sbcl                            \
                       --load-system pgloader               \
                       --load src/hooks.lisp                   \
                       --entry pgloader:main                   \
                       --dynamic-space-size 4096         \
                       --compress-core                    \
                       --output build/bin/pgloader
;; loading system "pgloader"
Fatal SIMPLE-ERROR:
  Compilation failed: Undefined instruction: MOVZXD in
 (INST MOVZXD RESULT MEMREF) in /private/tmp/pgloader-20180830-29874-1686zsk/pgloader-3.5.2/lib/nibbles/sbcl-opt/x86-64-vm.lisp
make: *** [pgloader-standalone] Error 1
```

**Comment by iMichka** [comment]
FYI this fails also to build on Linux with the same error message ...

**Comment by iMichka** [comment]
And it also fails on High Sierra for me, so I think the build is probably completely broken right now.

**Comment by DomT4** [comment]
Terrific. Thanks for looking into this @iMichka!

**Comment by ktully23** [comment]
I followed the instructions on the pgloader github for installing on a Mac which was 
`brew install --HEAD pgloader` 
That gave me the same error as @DomT4 but when I tried 
`brew install pgloader`
it installed successfully

**Comment by SMillerDev** [comment]
Installing with HEAD specified is generally a bad idea since it breaks a lot of nice homebrew features. Since it also breaks on Linux I'd assume it's an upstream issue.

**Comment by rtr321** [comment]
I have the same issue. Has anyone figured out how to fix this?

**Comment by vinitkumar** [comment]
It is crashing for me too on mojave. Anybody figured out how to get it installed?

**Comment by vinitkumar** [comment]
For anybody else bitten by this issue: Just compile it manually

```sh
git clone git@github.com:dimitri/pgloader.git --depth=1
make pgloader
```
https://github.com/dimitri/pgloader#more-options-when-building-from-source

**Comment by SMillerDev** [comment]
If that works a `--HEAD` install should work now too.

**Comment by vinitkumar** [comment]
@SMillerDev Sadly it doesn't. I tried that too.

**Comment by techdragon** [comment]
This just failed for me while upgrading everything after updating to macOS Mojave.

**Comment by jvosloo** [comment]
On Mac Mojave, I'm having no luck with:
`brew install pgloader`
`brew install --HEAD pgloader`

I'm getting the same error as reported initially.

Any ideas?

**Comment by iMichka** [comment]
I think it would be great if somebody could open an issue on the pgloader bugtracker so that we get some help from their devs.

**Comment by wannymiarelli** [comment]
Mojave here - brew install pgloader worked for me, --HEAD was failing.

**Comment by jvosloo** [comment]
> Mojave here - brew install pgloader worked for me, --HEAD was failing.

Yup - as per my updated comment above: `brew install pgloader` now also worked for me.

**Comment by iMichka** [comment]
What Xcode and CLT version do you have?
Please provide your `brew config`.

**Comment by fxcoudert** [comment]
pgloader developer declined to publish a point-release with the fix: https://github.com/dimitri/pgloader/issues/832 I am this closing this issue: the bug is known, reported to upstream, ball is in their court.

I am trying again a CI job for us to see what's the current state: https://jenkins.brew.sh/job/Homebrew%20Testing/1107/

**Comment by fxcoudert** [comment]
pgloader still fails to build on all three macOS versions:

```
==> make pgloader-standalone BUILDAPP=buildapp
buildapp    --require sb-posix --require sb-bsd-sockets --require sb-rotate-byte                        \
                       --sbcl sbcl                            \
                       --load-system pgloader               \
                       --load src/hooks.lisp                   \
                       --entry pgloader:main                   \
                       --dynamic-space-size 4096         \
                       --compress-core                    \
                       --output build/bin/pgloader
;; loading system "pgloader"
Fatal SIMPLE-ERROR:
  Compilation failed: Undefined instruction: MOVZXD in
 (INST MOVZXD RESULT MEMREF) in /private/tmp/pgloader-20181108-18607-5cehsv/pgloader-3.5.2/lib/nibbles/sbcl-opt/x86-64-vm.lisp
```

**Comment by cegg** [comment]
Mac OS High Sierra 10.13.6. Im y case,  `brew install` works without `--HEAD` and ives that MOVZXD error with `--HEAD`
