### ISSUE TITLE
Should url shorteners be used?

### ISSUE THREAD

**Issue by txdv** [Homebrew/homebrew-core#31597]
I came across one when installing sbt.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/sbt.rb#L4

I mean it serves no other purpose then to look cool.

We do have a sha, so we check the validity of the package.

But... What if the service goes down? Are dead urls being monitored?

**Comment by woodruffw** [comment]
See https://github.com/Homebrew/homebrew-core/pull/27787 and https://github.com/Homebrew/homebrew-core/issues/27912 -- upstream treats this shortened URL as canonical and hasn't provided us with another one.

> But... What if the service goes down? Are dead urls being monitored?

Empirically, this hasn't been more of an issue for upstreams that use mirroring/shortening services than those that haven't. A more subtle issue is corporate firewalls, which one of the issues I referenced above concerns. You can help us out here by complaining directly to the upstream -- we'll happily switch to a direct URL if they provide us with one 😄

**Comment by woodruffw** [comment]
Upstream tracking issue: https://github.com/sbt/sbt/issues/4165

**Comment by txdv** [comment]
statistics, thanks for the clarifications, should have searched a bit more!
