### ISSUE TITLE
imagemagick 7.0.8-11 fails to build on mac 10.13.6

### ISSUE THREAD

**Issue by kaelzhang** [Homebrew/homebrew-core#31594]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

```sh
brew install imagemagick --with-webp
```

- What happened (include command output)

Fails to compile

```
Updating Homebrew...
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick--7.0.8-11.tar.xz
Already downloaded: /Users/kael/Library/Caches/Homebrew/imagemagick--7.0.8-11.tar.xz
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.8-11 --disable-silent-rules --enable-shared --enable-static --with-modules --disable-opencl --disable-openmp --with-webp=yes --without-openjp2 --without-gslib --with-gs-font-dir=/usr
Last 15 lines from /Users/kael/Library/Logs/Homebrew/imagemagick/01.configure:
checking for ssize_t... yes
checking for uid_t in sys/types.h... yes
checking for uint8_t... unsigned char
checking for uint16_t... unsigned short int
checking for uint32_t... yes
checking for uint64_t... yes
checking for uintmax_t... no
checking for uintptr_t... yes
checking for unsigned long long int... (cached) yes
checking for locale_t... yes
checking for float_t... yes
checking for double_t... yes
checking size of float_t... configure: error: in `/private/tmp/imagemagick-20180830-32097-1xg41v8/ImageMagick-7.0.8-11':
configure: error: cannot compute sizeof (float_t)
See `config.log' for more details

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
imagemagick: ship a safer security policy https://github.com/Homebrew/homebrew-core/pull/31558
```

Gist logs are available [here](https://gist.github.com/a887baf588d89d422ef45d5e09b5c164).

- What you expected to happen

Should succeed.

- Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install imagemagick --with-webp
```

Without the `--with-webp` option, `brew install` works

**Comment by DomT4** [comment]
You have a bunch of unexpected headers in `/usr/local/include` which conflict with the system, not least `/usr/local/include/stdint.h`, which seems to be causing the issue here. If you handle some of those unexpected headers, I suspect the build will work.
