### ISSUE TITLE
ffmbc fails to build: No file to patch

### ISSUE THREAD

**Issue by lenlo** [Homebrew/homebrew-core#31738]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Installing ffmbc fails while patching:
```
$ brew install ffmbc
==> Downloading https://drive.google.com/uc?export=download&id=0B0jxxycBojSwTEgtbjRZMXBJREU
==> Downloading from https://doc-04-4s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/80rjatdlgkpnjt717h41v3vu730r654h/1535961600000/03686078983744581292/*/0B0j
######################################################################## 100.0%
==> Patching
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/doc/texi2pod.pl b/doc/texi2pod.pl
|index 18531be..88b0a3f 100755
|--- a/doc/texi2pod.pl
|+++ b/doc/texi2pod.pl
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
357
```

For the record, `grew gist-logs` succeeds, but produces no logs:
```
$ brew gist-logs ffmbc
Error: No logs.
```

**Comment by lenlo** [comment]
It looks to my somewhat untrained eye as if homebrew isn't realizing that the downloaded package file ("0B0jxxycBojSwTEgtbjRZMXBJREU?e=download") is bzip2'ed and therefore fails to unzip it.

**Comment by fxcoudert** [comment]
Yes, the problem is that `brew` stopped recognising the URL `https://drive.google.com/uc?export=download&id=0B0jxxycBojSwTEgtbjRZMXBJREU` as a `.tar.bz2` file. @reitermarkus can you take a look?

**Comment by lenlo** [comment]
Thanks. I found a workaround by adding `response-content-disposition=attachment%3B%20filename%3Dffmbc-0.7.2.tar.gz` to the URL. This is recognized by brew and will cause the saved filename to be `ffmbc-0.7.2.tar.gz`, but I had to change the base URL to `https://doc-04-4s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/dk9hutg27jesmcmiprtl8bqkl0lass3t/1536156000000/03686078983744581292/*/0B0jxxycBojSwTEgtbjRZMXBJREU?e=download` in the process as the original URL led to a redirect. Since Google may change the redirect in the future, this workaround is less than ideal so I'm hoping that there is a better solution.

```
  #url "https://drive.google.com/uc?export=download&id=0B0jxxycBojSwTEgtbjRZMXBJREU"
  url "https://doc-04-4s-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/dk9hutg27jesmcmiprtl8bqkl0lass3t/1536156000000/03686078983744581292/*/0B0jxxycBojSwTEgtbjRZMXBJREU?e=download&response-content-disposition=attachment%3B%20filename%3Dffmbc-0.7.2.tar.gz"
```
