### ISSUE TITLE
Formulas whose source cannot be downloaded

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#31779]
As part of building bottles for 10.14, we are finding a number of formulas where the source is unavailable (i.e., `brew fetch -s` fails). I am listing them here for investigation:

- [x] backupninja
- [ ] bigloo
- [x] blink1 (https://github.com/todbot/blink1/issues/341)
- [x] bower (https://github.com/bower/bower/issues/2527)
- [x] cattle
- [x] citus
- [x] cracklib
- [x] dante
- [x] euca2ools
- [x] eventlog
- [x] fmsx (#32307)
- [x] fuego
- [x] git-secret
- [x] graph-tool
- [x] ii
- [x] jerasure (#32305)
- [x] jerm
- [x] libghthash
- [x] libgtop
- [x] libquicktime
- [x] logentries
- [x] lsh (3a90f089375a66f805d9348cc4b7657b63a93902)
- [x] mediatomb
- [x] noweb
- [x] np2
- [x] nuttcp
- [x] openrtsp
- [x] qd
- [x] rkhunter
- [x] shogun
- [x] simutrans
- [x] spim
- [x] stlink
- [x] tcpflow (#32412)
- [x] tgui (#32413)
- [x] unp64 (#32414)
- [x] wrangler
- [x] wumpus
- [x] xmount
- [x] xqilla
- [x] xu4

**Comment by walinga** [comment]
It looks like the checksum for `qd` changed without the version changing. I don't see a github repo where I can leave an issue though.
