### ISSUE TITLE
mpd: caveats suggest $XDG_CONFIG_HOME but upstream doesn't use XDG paths on macOS

### ISSUE THREAD

**Issue by smancill** [Homebrew/homebrew-core#31794]
The caveats for mpd show:

https://github.com/Homebrew/homebrew-core/blob/2c0d6b2ec844cb96f053fb0a40d6c83e7881b2ea/Formula/mpd.rb#L115-L123

But upstream does not enable XDG support on macOS:

https://github.com/MusicPlayerDaemon/MPD/blob/282859a62a4f26093c7d602dbb39a9522d255ce0/src/fs/StandardDirectory.cxx#L22-L25

The $XDG_CONFIG_HOME path may be removed from the caveats (not ideal for people who wants to keep their home directory clean), or the formula could enable XDG support by defining `USE_XDG` when running configure.

**Comment by fxcoudert** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/commit/5d8945bb46f754cebf30a6f1e738073d392e94cf
Given that upstream deliberately chooses to disable XDG on macOS, let's keep it that way.
