### ISSUE TITLE
formula xmount build from source wrong tag

### ISSUE THREAD

**Issue by graphitewindows** [Homebrew/homebrew-core#31801]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[gist-logs.txt](https://github.com/Homebrew/homebrew-core/files/2350346/gist-logs.txt)
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
[Brew-doctor.txt](https://github.com/Homebrew/homebrew-core/files/2350347/Brew-doctor.txt)
[Brew-config.txt](https://github.com/Homebrew/homebrew-core/files/2350348/Brew-config.txt)

To help us debug your issue please explain:
- What you were trying to do (and why)
Build xmount from source with the --build-from-source option

- What happened (include command output)
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.
==> Cloning https://code.pinguin.lu/diffusion/XMOUNT/xmount.git
Updating /Users/lab/Library/Caches/Homebrew/xmount--git
==> Checking out tag v0.7.6
HEAD is now at d0f67c4... ADMIN: Updating previous tag
HEAD is now at d0f67c4 ADMIN: Updating previous tag
Error: v0.7.6 tag should be a417af7382c3e18fb8bd1341cc3307b09eefd578
but is actually d0f67c46632a69ff1b608e90ed2fba8344ab7f3d

- What you expected to happen
xmount should build and install

- Step-by-step reproduction instructions (by running `brew install` commands)
1. run: brew install xmount --build-from-source
2. Read error message that states that the 0.7.6 tag is wrong.  It looks like the developer made minor modifications resulting in a different hash for the same tag.  (See: https://code.pinguin.lu/diffusion/XMOUNT/)  Guessing the install script for this formula just needs to be updated to reflect the new hash.

**Comment by fxcoudert** [comment]
Thanks @graphitewindows for the bug report!
