### ISSUE TITLE
Add Plugins Manager as a standard plugin

### ISSUE THREAD

**Issue by edwinm** [Homebrew/homebrew-core#31883]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

This is not a bug, but a feature request.

- What you were trying to do (and why)

Use the Plugins Manager in jmeter after installing with plugins, so I can easily install more plugins from the GUI.

- What happened (include command output)

Installed without Plugins Manager plugin

- What you expected to happen

Installed with Plugins Manager plugin

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install jmeter --with-plugins`

---

Output of `brew gist-logs jmeter`:

https://gist.github.com/d625af80111bd447e4f9313cd687bc8a

**Comment by SMillerDev** [comment]
Could you also fill out the rest of the issue template? It helps a lot with trying to debug issues.

**Comment by SMillerDev** [comment]
That option doesn't install the plugin manager by the way. As per the description it only does the following:
> add JMeterPlugins Standard, Extras, ExtrasLibs, WebDriver and Hadoop

So to install the plugin manager you'd have to follow the instructions on the website: https://jmeter-plugins.org/wiki/PluginsManager/#JMeter-Plugins-Manager

**Comment by edwinm** [comment]
I request the addition of Plugin Manager to the list of standard plugins because I think that's useful for other jmeter users.

In other words, add Plugin Manager to "JMeterPlugins Standard, Extras, ExtrasLibs, WebDriver and Hadoop".

**Comment by SMillerDev** [comment]
Pull requests are welcome, but it might not get accepted as homebrew generally tries to avoid software that does it's own updates.
