### ISSUE TITLE
String:0x0000000102327a78

### ISSUE THREAD

**Issue by andraderenew** [Homebrew/homebrew-core#31898]
Renes-MacBook-Air-2:~ andraderenew$ brew install pegasus htcondor
==> Installing pegasus from pegasus-isi/tools
==> Downloading https://download.pegasus.isi.edu/pegasus/4.8.4/pegasus-4.8.4.tar
######################################################################## 100.0%
==> ant clean dist-common doc-manpages
Error: undefined method `undent' for #<String:0x0000000102327a78>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/pegasus-isi/homebrew-tools/pegasus.rb:78:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:591:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:640:in `finish'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

**Comment by SMillerDev** [comment]
This is an issue with the pegasus-isi/tools tap. Homebrew can't fix those unfortunately.

**Comment by DomT4** [comment]
Filed https://github.com/pegasus-isi/homebrew-tools/issues/5 upstream.
