### ISSUE TITLE
Homebrew doesn't like a missing /usr/local/Frameworks

### ISSUE THREAD

**Issue by AlexanderWillner** [Homebrew/homebrew-core#31920]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>`

- What you were trying to do (and why): ```Installing python```
- What happened (include command output): 
```
$ brew install python
...
==> Pouring python-3.7.0.mojave.bottle.3.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
```
- What you expected to happen: ```Installed python```
- Step-by-step reproduction instructions (by running `brew install` commands): ```see above```
- Further information: actually the same as #19286 - however, it was closed. Maybe due to my update to Mojave the folder was removed. Still, either ```brew doctor``` or ```brew link``` should handle this situation better.

**Comment by DomT4** [comment]
Are you running `master` or `stable` if you check `git -C "$(brew --repo)" status`?

I think this was more cleanly handled in https://github.com/Homebrew/brew/pull/4844 but that hasn't yet made its way into a tagged release.

**Comment by AlexanderWillner** [comment]
It's on ```stable```. Ok, then this will be handled soon.

**Comment by DomT4** [comment]
Aye, a new tag should land sometime this week I expect. Let us know if you encounter this anywhere after that point.

_(I assume you manually created the directory to resolve the issue in the mean time?)_
