### ISSUE TITLE
Folly 2018.09.10.00 (latest) is missing a header (upstream issue)

### ISSUE THREAD

**Issue by paulrosania** [Homebrew/homebrew-core#31959]
Folly added `folly/detail/Futex-inl.h` and it isn't picked up by the autotools install. This breaks anything depending on futexes.

I've filed a PR upstream: https://github.com/facebook/folly/pull/926

Folly releases weekly, so this will hopefully fix-forward quickly. Posting here in case anyone else runs into similar issues before they're fixed.

**Comment by frank-origo** [comment]
Encountered same issue.

**Comment by paulrosania** [comment]
This issue is fixed in v2018.09.10.01. :)

https://github.com/facebook/folly/pull/926#issuecomment-420090812
