### ISSUE TITLE
Please provide a option to build python with openssl@1.1

### ISSUE THREAD

**Issue by moonfruit** [Homebrew/homebrew-core#31981]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I want use some function that only exists in `python` build with `openssl@1.1`. Like TLS 1.3 and scrypt.

- What happened (include command output)

Now, `python` only compile with `openssl` which is 1.0. And `brew` not provide a option to build python with `openssl@1.1`.

- What you expected to happen

If `brew` can provide a option like `--with-openssl@1.1`, that will be great.

- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by fxcoudert** [comment]
What is the need for a Python linked with openssl 1.1?

It is very unlikely to happen before we migrate everything to openssl 1.1, given that we try very hard to avoid mixed dependency chains with openssl 1.0 and 1.1.

**Comment by DomT4** [comment]
It will build against `openssl@1.1` unproblematically today, but it basically can't happen until the entire recursive dependency tree _(not an issue here with the current dependencies)_ and _(much more problematically)_ the entire `brew uses --include-build --recursive python` tree is also using `openssl@1.1`, especially given `brew`'s strict check on versioned formulae being in the same recursive tree as their non-versioned counterparts.

Good luck to whoever that task falls on 🙃.

**Comment by moonfruit** [comment]
@fxcoudert If you want to use TLS 1.3 and scrypt in `python`, you will need a python that build with `openssl@1.1`.
According to [scrypt](https://docs.python.org/3/library/hashlib.html#hashlib.scrypt) and [SSLContext [3]](https://docs.python.org/3/library/ssl.html#ssl.SSLContext)

**Comment by fxcoudert** [comment]
I am going to close this, as this needs to be handled as part of a larger transition of Homebrew to `openssl@1.1`.
