### ISSUE TITLE
Why installing Vim with Python@2 installs Python2?

### ISSUE THREAD

**Issue by 097115** [Homebrew/homebrew-core#31990]
`brew install vim --with-python@2` installs Python2 even though macOS has it's own Python2.

I understand that this is an intended behaviour and not a bug (so I don't really think the issue templates can applied here). What I don't understand is **why** this is an intended behaviour. Because the following problems arise:

  - brew installs Python2, which I absolutely don't need;
  - brew [replaces the default Python2](https://github.com/Homebrew/homebrew-core/issues/24761), which results in Vim looking for packages in `/usr/local/lib/python2.7/site-packages` instead of `/Library/Python/2.7/site-packages/`. Sure, I can symlink but what the hell? :) 

[Brew's announcement](https://brew.sh/2018/01/19/homebrew-1.5.0/) on Python clearly states that:

> macOS has provided Python 2.7 since OS X Lion (10.7) so you can update formulae that need Python 2 today by removing `depends_on "python"` so they use the system python instead.

...which again makes me ask the same thing: Why the [Vim formulae](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb) wasn't updated this suggested way?

Thanks.

**Comment by MikeMcQuaid** [comment]
> so I don't really think the issue templates can applied here

Please fill them out in future anyway.



> Why the [Vim formulae](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb) wasn't updated this suggested way?

It uses Python 3 by default. People can't agree on whether they prefer Homebrew's Python 2 or the system Python 2 so we went with the analytics data to decide what was the most popular.

**Comment by 097115** [comment]
@MikeMcQuaid, then, how do I install Vim with the system Python2 now?

**Comment by MikeMcQuaid** [comment]
We don't support that but you could do so in your own formula.
