### ISSUE TITLE
OpenSSL with ECDSA

### ISSUE THREAD

**Issue by jschlyter** [Homebrew/homebrew-core#32007]
When upgrading OpenSSL to 1.1.1 (new LTS version), please enable support for EDDSA as this will be used by Unbound. I'd be happy to help and verify if required.

**Comment by SMillerDev** [comment]
I'm not sure what Unbound is, but pull requests are always welcome.

**Comment by SMillerDev** [comment]
That was the wrong button 😒

**Comment by fxcoudert** [comment]
@jschlyter I couldn't find documentation on how to enable that when configuring openssl. Could you link to the relevant documentation?

**Comment by fxcoudert** [comment]
ECDSA is enabled by default in the latest OpenSSL, but we cannot enable it by default for Unbound, for the reasons explained here: https://github.com/Homebrew/homebrew-core/pull/32029
