### ISSUE TITLE
Pruned 0 symbolic links and 4 directories from /usr/local

### ISSUE THREAD

**Issue by xhaythemx** [Homebrew/homebrew-core#32017]
after updating homebrew , and purned it , i get this message " Pruned 0 symbolic links and 4 directories from /usr/local " 
and i cant get rid of it , it keeps showing , what does it mean , thanks

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
