### ISSUE TITLE
Shouldn't postgresql be installed with a database directory set?

### ISSUE THREAD

**Issue by marcandre** [Homebrew/homebrew-core#32024]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I installed postgresql with `brew install postgresql`.

Trying to create a DB with rails and `rake db:create` fails. I believe it's because there is no data directory set, as told by:

    $ pg_ctl status
    pg_ctl: no database directory specified and environment variable PGDATA unset

Shouldn't that be taken care of by `brew install postgresql`? Note that there's info on how to migrate data from an old version of postgresql, but no info on how to set it up.

I tried `brew uninstall postgresql && brew install postgresql`.

gist-log: https://gist.github.com/28bd927e1ca831322cd076990f4d4858

I hope I'm not missing something obvious here. I also doubled checked there wasn't anything relevant in my .bash_profile; `$ export | grep PGDATA` is empty.

**Comment by MikeMcQuaid** [comment]
We do not ever edit your `.bash_profile` for you automatically. If there's a way to configure postgresql such that `PGDATA` is somehow not needed we'd welcome a PR for it. Thanks!
