### ISSUE TITLE
Tomcat version update

### ISSUE THREAD

**Issue by dmreshet** [Homebrew/homebrew-core#32026]
brew install tomcat doesn't work now because https://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-9/v9.0.11/bin/apache-tomcat-9.0.11.tar.gz was removed.
New path is https://www.apache.org/dyn/closer.cgi?path=/tomcat/tomcat-9/v9.0.12/bin/apache-tomcat-9.0.12.tar.gz
Please update it.

**Comment by SMillerDev** [comment]
Could you make a pull request for that?
It's fairly easy with the documentation provided [here](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request)

**Comment by coreyderosa** [comment]
@aaricpittman has updated tomcat, the pull request has been merged and it working
