### ISSUE TITLE
Wireshark description is wrong

### ISSUE THREAD

**Issue by awfki** [Homebrew/homebrew-core#32069]
This really has nothing to do with homebrew-core, it's about the description of [Wireshark on the brewformulas.org](http://brewformulas.org/Wireshark). 

The description for Wireshark is actually for a book.  The front page at wireshark.org is a mess so it's no wonder a good description wasn't pulled.

The best I could find is under [Get Aquainted > About](https://www.wireshark.org/#aboutWS) and says:

- Wireshark is the world’s foremost and widely-used network protocol analyzer. It lets you see what’s happening on your network at a microscopic level and is the de facto (and often de jure) standard across many commercial and non-profit enterprises, government agencies, and educational institutions. Wireshark development thrives thanks to the volunteer contributions of networking experts around the globe and is the continuation of a project started by Gerald Combs in 1998.

Thanks

**Comment by fxcoudert** [comment]
The Homebrew project does not control this text. Please report the issue to https://gitlab.com/zedtux/brewformulas.org
