### ISSUE TITLE
Installing git --without-completions installs completions

### ISSUE THREAD

**Issue by beverku** [Homebrew/homebrew-core#32081]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Trying to install `brew install git --without-completions`

The --without-completions is necessary so those git completions are not preferred over the plugins from oh my zxh

See: 
https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git-extras#os-x-homebrew-setup
https://www.raphael-brugier.com/blog/fix-git-completion-zsh-mac-homebrew/

- What happened (include command output)

$ brew install git --without-completions
Warning: git: this formula has no --without-completions option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/git-2.19.0_1.high_sierra.bottle.tar.gz
Already downloaded: /Users/auser/Library/Caches/Homebrew/downloads/2091d3f7be5509498044a0fc65f6ba898956774ea968c796eeea61c604b0a408--git-2.19.0_1.high_sierra.bottle.tar.gz
==> Pouring git-2.19.0_1.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.19.0_1: 1,512 files, 318.2MB

$ brew config
HOMEBREW_VERSION: 1.7.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88e69f5a8835bd9a05c37dadfcc25b3e9dada340
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ec4edfc01a108b0a092985056b65a4a646f7b385
Core tap last commit: 34 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.15.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2, 1.8.0_181
macOS: 10.13.6-x86_64
CLT: 9.4.1.0.1.1528165917
Xcode: N/A
XQuartz: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/auser/.pyenv/shims/python3.5m-config
  /Users/auser/.pyenv/shims/python3.5-config
  /Users/auser/.pyenv/shims/python-config
  /Users/auser/.pyenv/shims/python3-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

- What you expected to happen

The installation to skip installing git completions
It seems this option was removed in this commit: https://github.com/Homebrew/homebrew-core/commit/f710a1395f44224e4bcc3518ee9c13a0dc850be1#diff-3e84bae646d908b93e043833873d316d

I read through some of the discussion here: https://github.com/Homebrew/homebrew-core/issues/31510 
So if you choose to close this defect I understand why, but this option was useful.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install git --without-completions`

**Comment by MikeMcQuaid** [comment]
> Warning: git: this formula has no --without-completions option so it will be ignored!

This is intentional, sorry.
