### ISSUE TITLE
Error on install root: gcc was built with a different C++ standard library (libstdc++ from clang) 

### ISSUE THREAD

**Issue by XueqiLi** [Homebrew/homebrew-core#32112]
When I try to install root I get this error:
`root dependency gcc was built with a different C++ standard library (libstdc++ from clang). This may cause problems at runtime.`

And when I try to run the root it gives me errors:

```
input_line_1:1:10: fatal error: 'new' file not found
input_line_3:37:10: fatal error: 'string' file not found
input_line_9:1:10: fatal error: 'iostream' file not found
```

I have tried `brew reinstall $(brew deps root)` but it does not help.

**Comment by SMillerDev** [comment]
Could you fill out the issue template? It really helps a lot with debugging issues.

**Comment by XueqiLi** [comment]
- [ x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
* Tried another Mac and it happened again. So I am assuming it should be able to reproduce for others.
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
* 'Error: No logs.'
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 1.7.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 88e69f5a8835bd9a05c37dadfcc25b3e9dada340
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d9ed4328af94a63fc0d7ea958d0ed48d7066bf7e
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 9.4.1
XQuartz: N/A
```
doctor told me my system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install root`
- What happened (include command output)
`root dependency gcc was built with a different C++ standard library (libstdc++ from clang). This may cause problems at runtime.`
and there is errors at runtime.
- What you expected to happen
no error and I can run root?
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install root`

**Comment by fxcoudert** [comment]
Please give the entire output from `brew install --verbose root` and `brew info root` after installing. We need to know things like whether it was installed from a bottle or from source, etc.

**Comment by XueqiLi** [comment]
```
# el at Xueqis-MBP-13 in ~ [18:26:21]
→ brew install --verbose root
Updating Homebrew...
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> Updated Formulae
sqlite ✔                          dbhash                            sqldiff                           sqlite-analyzer                   terragrunt                        vim

Warning: root 6.14.04 is already installed and up-to-date
To reinstall 6.14.04, run `brew reinstall root`

# el at Xueqis-MBP-13 in ~ [18:26:30]
→ brew info root
root: stable 6.14.04 (bottled), HEAD
Object oriented framework for large scale data analysis
https://root.cern.ch
/usr/local/Cellar/root/6.14.04 (5,496 files, 285.3MB) *
  Poured from bottle on 2018-09-16 at 12:57:41
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/root.rb
==> Dependencies
Build: cmake ✘
Required: davix ✔, fftw ✔, gcc ✔, graphviz ✔, gsl ✔, lz4 ✔, openssl ✔, pcre ✔, tbb ✔, xrootd ✔, xz ✔
Recommended: python ✔
Optional: python@2 ✔
==> Options
--with-python@2
	Build with python@2 support
--without-python
	Build without python support
--HEAD
	Install HEAD version
==> Caveats
Because ROOT depends on several installation-dependent
environment variables to function properly, you should
add the following commands to your shell initialization
script (.bashrc/.profile/etc.), or call them directly
before using ROOT.

For bash users:
  . /usr/local/bin/thisroot.sh
For zsh users:
  pushd /usr/local >/dev/null; . bin/thisroot.sh; popd >/dev/null
For csh/tcsh users:
  source /usr/local/bin/thisroot.csh

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/root
==> Analytics
install: 681 (30d), 3064 (90d), 8367 (365d)
install_on_request: 637 (30d), 2733 (90d), 7383 (365d)
build_error: 28 (30d)
```

**Comment by calemhoffman** [comment]
Same issue as mentioned, tried all items mentioned.

`HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 125520f007b2d98af39c372a7f761bf385a4cfc1
Core tap last commit: 31 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101400
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11`

`root
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -O2 -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
Results was:
With exit code 256
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
input_line_3:37:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
   ------------------------------------------------------------
  | Welcome to ROOT 6.14/04                http://root.cern.ch |
  |                               (c) 1995-2018, The ROOT Team |
  | Built for macosx64                                         |
  | From tags/v6-14-04@v6-14-04, Aug 23 2018, 17:00:44         |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

input_line_9:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~`

**Comment by rasmack** [comment]
This may or may not be relevant, but I found that Apple had decided to change the location of a lot of standard headers. Check that you still have a /usr/include directory. If not, install this package:

/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14. pkg

That fixed my problems compiling Root from source. YMMV.

**Comment by XueqiLi** [comment]
> This may or may not be relevant, but I found that Apple had decided to change the location of a lot of standard headers. Check that you still have a /usr/include directory. If not, install this package:
> 
> /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14. pkg
> 
> That fixed my problems compiling Root from source. YMMV.

Thank you! It work. Though I still get different C++ standard library error on install, there is no runtime error anymore.

**Comment by fxcoudert** [comment]
We're tracking further Root issues in Homebrew here: #32949
