### ISSUE TITLE
To sort all deps in all formulas alphabetically

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#32134]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I see that a lot of formulas doesn't follow `audit --new-formula` rule that enforces sorting dependencies alphabetically.
- What happened (include command output)
```
$ brew audit --fix --new-formula --strict subversion --online
subversion:
  * C: 15: col 3: New formulae should not use `deprecated_option`
  * C: 20: col 3: Formulae should not have an `option`
  * C: 27: col 3: [Corrected] dependency "scons" (line 27) should be put before dependency "swig" (line 26)
  * C: 28: col 3: [Corrected] dependency "apr" (line 28) should be put before dependency "apr-util" (line 27)
  * C: 28: col 3: [Corrected] dependency "scons" (line 28) should be put before dependency "apr" (line 27)
  * C: 31: col 3: [Corrected] dependency "scons" (line 31) should be put before dependency "apr-util" (line 28)
  * C: 32: col 3: [Corrected] dependency "scons" (line 32) should be put before dependency "lz4" (line 31)
  * C: 33: col 3: [Corrected] dependency "openssl" (line 33) should be put before dependency "sqlite" (line 32)
  * C: 33: col 3: [Corrected] dependency "scons" (line 33) should be put before dependency "openssl" (line 32)
  * C: 34: col 3: [Corrected] dependency "openssl" (line 34) should be put before dependency "utf8proc" (line 33)
  * C: 34: col 3: [Corrected] dependency "scons" (line 34) should be put before dependency "sqlite" (line 32)
  * C: 35: col 3: [Corrected] dependency "scons" (line 35) should be put before dependency "utf8proc" (line 33)
  * C: 37: col 3: [Corrected] dependency "scons" (line 37) should be put before dependency "perl" (line 34)
  * C: 38: col 3: [Corrected] dependency "openssl" (line 38) should be put before dependency "perl" (line 34)
  * C: 42: col 3: [Corrected] dependency "gettext" (line 42) should be put before dependency "gnupg" (line 41)
  * Dependency 'sqlite' may be unnecessary as it is provided by macOS; try to build this formula without it.
  * Formulae should not have optional or recommended dependencies
  * Formulae should not have optional or recommended dependencies
  * Formulae should not have optional or recommended dependencies
  * Formulae should not have optional or recommended dependencies
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
Error: 21 problems in 1 formula detected, 13 problems corrected
```
- What you expected to happen
All deps must be already sorted.
- Step-by-step reproduction instructions (by running `brew install` commands)
```brew audit --fix --new-formula --strict subversion --online```

**Comment by yurikoles** [comment]
Should I submit separate commits for each formula, all I can do it in one?

**Comment by commitay** [comment]
Please see the discussion in https://github.com/Homebrew/brew/pull/4862
