### ISSUE TITLE
`git` installed from bottle takes too much disk space than from source due to link deference

### ISSUE THREAD

**Issue by georgexsh** [Homebrew/homebrew-core#32131]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

install git with homebrew

- What happened (include command output)

git installed from bottle (https://homebrew.bintray.com/bottles/git-2.19.0_1.high_sierra.bottle.tar.gz), takes 318.2MB on disk:

```
==> Summary
🍺  /usr/local/Cellar/git/2.19.0_1: 1,512 files, 318.2MB
```

if install git from source with `--build-from-source`, takes only 40MB on disk:

```
==> Summary
🍺  /usr/local/Cellar/git/2.19.0_1: 1,511 files, 40MB, built in 2 minutes 35 seconds
```

- What you expected to happen

bottled git installed could take less disk.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install git
brew install --build-from-source git
```

- brew gist-logs result

https://gist.github.com/georgexsh/5e3a616c6c85d93b9c580d36db6bb6c7

git organizes subcommands in `libexec/git-core`, generally on Unix like platforms, they are hard links, and in the bottle tarball downloaded, they are hard links as intended, but after poured, those hand links got dereferenced as copies, which occupied much more disk space.

**Comment by SMillerDev** [comment]
This seems like an issue for homebrew/brew.

**Comment by georgexsh** [comment]
```
==> Pouring git-2.19.0_1.high_sierra.bottle.tar.gz
tar xf /Users/georgexsh/Library/Caches/Homebrew/downloads/2091d3f7be5509498044a0fc65f6ba898956774ea968c796eeea61c604b0a408--git-2.19.0_1.high_sierra.bottle.tar.gz -C /var/folders/kj/frymmr4x1qlgdw4fvg1ddq240000gp/T/d20180917-13285-tr0imi
cp -pR /var/folders/kj/frymmr4x1qlgdw4fvg1ddq240000gp/T/d20180917-13285-tr0imi/git/. /usr/local/Cellar/git
```

I think the problem is when brew pouring a bottle tarball, it uses `cp -pR` to move files to tje finall dest, but `cp` cannot preserve hard links, they all become copies:

```
     -R    If source_file designates a directory, cp copies the directory
           and the entire subtree connected at that point.  If the
           source_file ends in a /, the contents of the directory are
           copied rather than the directory itself.  This option also
           causes symbolic links to be copied, rather than indirected
           through, and for cp to create special files rather than copying
           them as normal files.  Created directories have the same mode as
           the corresponding source directory, unmodified by the process'
           umask.

           In -R mode, cp will continue copying even if errors are
           detected.

           Note that cp copies hard-linked files as separate files.  If you
           need to preserve hard links, consider using tar(1), cpio(1), or
           pax(1) instead.
```

maybe git formula could use symlinks, like XCode (https://opensource.apple.com/source/Git/Git-78/).

**Comment by lembacon** [comment]
@georgexsh It would be nice if you could open a PR for that, thanks!
