### ISSUE TITLE
Impossible to install wine devel/head at all with latest macOS/Xcode

### ISSUE THREAD

**Issue by AuroraWright** [Homebrew/homebrew-core#32257]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
At the moment, it's impossible for users to install anything but the stable branch of `wine` on macOS 10.13/10.14 with the latest updates applied, due to the macOS 10.14 SDK (bundled in Xcode 10) not having 32 bit support. A possible solution could be, given the clang toolchain in Xcode 10 still supports 32 bit binaries (unlike the SDK), having the wine bottle download the 10.13 SDK and using it for the build (according to the MinimumSDKVersion key in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist, SDKs starting from 10.11 are technically supported by this Xcode version). I tested building with Xcode 10 and the 10.13 SDK (in a hacky way given brew automatically selects the highest number SDK), and after solving an unrelated issue in the `wine` bottle, everything built and works as expected.

**Comment by fxcoudert** [comment]
Do you know what is Wine's position on the 32-bit deprecation in macOS Mojave?

**Comment by fxcoudert** [comment]
Fixing in #32266 by making it clearer what works and doesn't. Thanks for reporting!
