### ISSUE TITLE
llvm and llvm@6 lack the bottles for High Sierra

### ISSUE THREAD

**Issue by equal-l2** [Homebrew/homebrew-core#32308]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

---

As noted in title, `llvm` and `llvm@6` currently lack the bottles for High Sierra, though they have the bottles for Mojave, Sierra, or El Capitan.

**Comment by javian** [comment]
Looks like the High Sierra bottle job crashed and wasn't noticed since some of the software that uses llvm doesn't build correctly and always throws ci into red.

**Comment by javian** [comment]
Started the rebuild of the bottle now and we can merge it in once its completed. Thanks for noticing @equal-l2 !

**Comment by vszakats** [comment]
I can confirm that `llvm` is bottled fine [now](https://github.com/Homebrew/homebrew-core/commit/c44b347200282e9419c5ae9e0350e934593e8dad) on High Sierra — Thanks for the quick fix!

**Comment by equal-l2** [comment]
0f631d2 and c44b347 solved the issue.
Thank you for the fix.

**Comment by mbutrovich** [comment]
Thank you for the quick fix!

**Comment by fxcoudert** [comment]
Thanks for reporting, thanks @javian for fixing, and sorry everyone!
