### ISSUE TITLE
"brew install gnuplot --with-qt" fails on MacOS 10.13.6 with "C compiler cannot create executables"

### ISSUE THREAD

**Issue by bipcuds** [Homebrew/homebrew-core#32339]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew gist-logs link: https://gist.github.com/8c92ef8b8f009c60ef3a071679a7db26

To help us debug your issue please explain:
- What you were trying to do (and why):
I am able to install gnuplot using simply "brew install gnuplot --with-x11". However, when I reinstall (or remove, then install from scratch) "brew install gnuplot --with-qt --with-x11 --with-aquaterm", the configure script throws a "C compiler cannot create executables" error. (Also happens if I just run simple "brew reinstall gnuplot --with-qt").

- What happened (include command output):

> brew reinstall gnuplot --with-qt --with-x11 --with-aquaterm
==> Reinstalling gnuplot --with-aquaterm --with-qt --with-x11
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.2.4/gnuplot-5.2.4.tar.gz
Already downloaded: /Users/kball/Library/Caches/Homebrew/downloads/6e6dcf6b504a00cc6a5cf7e98e94845da41ce404fcd05cb24129a65317a8dfff--gnuplot-5.2.4.tar.gz
==> Downloading http://apps.jcns.fz-juelich.de/src/libcerf/libcerf-1.5.tgz
Already downloaded: /Users/kball/Library/Caches/Homebrew/downloads/5a94c4a074674a61e21642882831a899566e05f752fd8dea04bdec60adbcc4cc--libcerf-1.5.tgz
==> ./configure --prefix=/private/tmp/gnuplot-20180921-43052-14ev3b1/gnuplot-5.2.4/libcerf --enable-static --disable-shared
Last 15 lines from /Users/kball/Library/Logs/Homebrew/gnuplot/01.configure:
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin17.7.0
checking host system type... x86_64-apple-darwin17.7.0
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/gnuplot--libcerf-20180921-43052-pmtjjj/libcerf-1.5':
configure: error: C compiler cannot create executables
See `config.log' for more details
...

- What you expected to happen:

    Expected formula to be installed without error. ("configure" should pass; assume some problem with Xcode, paths, or library locations, but have not found the problem.)

- Step-by-step reproduction instructions (by running `brew install` commands):

(installed Xcode 10.0 
(Selected Command Line Tools option in Xcode: Settings -> Locations (only one version of CLT listed))
sudo xcodebuild -license
brew install gnuplot --with-qt --with-x11 --with-aquaterm

Note:
> xcode-select -p
/Applications/Xcode.app/Contents/Developer
> xcode-select -v
xcode-select version 2349.
> xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

Also:
I had problems in Homebrew with the Git installed to /usr/bin throwing error like "cannot find /usr/share/git-core/templates" - that path does not exist. I instead installed Git 2.18.0 to /usr/local/bin, and added "[init]\n templatedir = /usr/local/git/share/git-core/templates" to my ~/.gitconfig.

**Comment by MikeMcQuaid** [comment]
Please run `xcode-select --install` to update your CLT.

**Comment by bipcuds** [comment]
Mike,

As I had mentioned, the result of "xcode-select --install" is as follows:

    xcode-select: error: command line tools are already installed, use
"Software Update" to install updates

I had seen this mentioned as  "fix" several times, but it doesn't fix the
problem. I did in fact just update CLT yesterday (9/23/18 update) for Xcode
10.0, from the App Store. Under Xcode -> Settings -> Locations, there is
still only one version of CLT listed (Xcode 10.0 (10A255)).

Path/version information for CLT is as follows:

    [601]> xcode-select -p
    /Applications/Xcode.app/Contents/Developer
    [602]> xcode-select -v
    xcode-select version 2349.

**Comment by MikeMcQuaid** [comment]
@bipcuds Can I see your latest `brew config` output?

**Comment by bipcuds** [comment]
My "brew config" output is as follows:

> brew config
HOMEBREW_VERSION: 1.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: d639559c4de48faad79d3ecb1ec84dc851ea66f2
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 60a233f5833dcaa5196d39ac0919eb89e394a8d2
Core tap last commit: 4 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 =>
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11

**Comment by MikeMcQuaid** [comment]
> HOMEBREW_VERSION: 1.7.5

Please `brew update` and try again.

Can you confirm you're receiving the same 

> configure: error: in `/private/tmp/gnuplot--libcerf-20180921-43052-pmtjjj/libcerf-1.5': configure: error: C compiler cannot create executables See`config.log' for more details

message?

**Comment by MikeMcQuaid** [comment]
@bipcuds Can you compile C code outside of Homebrew using the system compiler?

**Comment by bipcuds** [comment]
Apparently not. Just trying to compile a simple Hello World is hitting significant path issues (apologies, I am a *nix compiler guy - haven't actually tried compiling on Mac so far):

> cat hello.c 
#include <stdio.h>

int main(void) {
   printf("Hello!\n");
   return 0;
}

[kball@10-4-5-186 ~/Toolbox/benchmarks/mpi/mpi-counter/src]
[644]> ls -l $(which cc)
lrwxr-xr-x  1 root  admin  5 Sep 23 14:39 /usr/bin/cc -> clang
[kball@10-4-5-186 ~/Toolbox/benchmarks/mpi/mpi-counter/src]
[645]> cc -v -o hello hello.c
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /usr/bin
 "/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name hello.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -resource-dir /usr/lib/clang/10.0.0 -fdebug-compilation-dir /Users/kball/Toolbox/benchmarks/mpi/mpi-counter/src -ferror-limit 19 -fmessage-length 130 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.13.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/3t/xtzcddjd6cd6dvxwz70wl81c0000gn/T/hello-11290a.o -x c hello.c
clang -cc1 version 10.0.0 (clang-1000.10.44.2) default target x86_64-apple-darwin17.7.0
ignoring nonexistent directory "/usr/lib/clang/10.0.0/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/usr/bin/ld" -demangle -lto_library /usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -macosx_version_min 10.13.0 -o hello /var/folders/3t/xtzcddjd6cd6dvxwz70wl81c0000gn/T/hello-11290a.o -lSystem
dyld: Library not loaded: @rpath/libtapi.dylib
  Referenced from: /usr/bin/ld
  Reason: image not found
clang: error: unable to execute command: Abort trap: 6
clang: error: linker command failed due to signal (use -v to see invocation)

I also have gcc at /usr/bin/gcc (can't tell if this is from the OS, or installed from Homebrew or other source. I don't see a "gcc" packages listed in "brew list"). It compiles just fine:

[652]> gcc -o hello hello.c
[653]> otool -L hello
hello:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
[kball@10-4-5-186 ~/Toolbox/benchmarks/mpi/mpi-counter/src]
[654]> ./hello 
Hello!
