### ISSUE TITLE
Unable to install JavaHL Libraries on macOS 10.13.6 High Sierra (command not found)

### ISSUE THREAD

**Issue by m1thrand1r** [Homebrew/homebrew-core#32334]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Installing JavaHL Libraries with command: brew install --universal --java subversion
Support for Eclipse Plugin

- What happened (include command output)
$ brew install --universal --java subversion
Warning: subversion: --java was deprecated; using --with-java instead!
Warning: subversion: this formula has no --universal option so it will be ignored!
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.10.2.tar.bz2
Already downloaded: /Users/stalherm/Library/Caches/Homebrew/downloads/891bd5f606e2553db3534719644e0fee38f62a2e8f0d048d11bbb3092e982904--subversion-1.10.2.tar.bz2
==> Patching
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
Already downloaded: /Users/stalherm/Library/Caches/Homebrew/downloads/3f4e2cb0f268fb9db7a761edccb60bdbdacb9923f8b2140e8c0a30b6792958a6--serf-1.3.9.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.10.2/libexec/serf GSSAPI=/usr CC=/usr/bin/clang CFLAGS=-Os -w -pipe -march=native -mmacosx
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.10.2 --enable-optimize --disable-mod-activation --disable-nls --with-apr-util=/usr/local/opt/apr-util --wit
==> make
==> make install
==> make tools
==> make install-tools
==> make swig-py
==> make install-swig-py
==> make swig-pl
==> make install-swig-pl
==> make javahl
==> make install-javahl
==> make swig-rb EXTRA_SWIG_LDFLAGS=-L/usr/lib
Last 15 lines from /Users/stalherm/Library/Logs/Homebrew/subversion/14.make:
2018-09-21 16:12:12 +0200

make
swig-rb
EXTRA_SWIG_LDFLAGS=-L/usr/lib

/bin/sh "/private/tmp/subversion-20180921-83635-lnja8/subversion-1.10.2/libtool" --tag=CC --silent --mode=compile none  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/private/tmp/subversion-20180921-83635-lnja8/subversion-1.10.2/subversion/bindings/swig/ruby/libsvn_swig_ruby -prefer-pic -c -o subversion/bindings/swig/ruby/svn_client.lo subversion/bindings/swig/ruby/svn_client.c
/private/tmp/subversion-20180921-83635-lnja8/subversion-1.10.2/libtool: line 1760: none: command not found
make: *** [subversion/bindings/swig/ruby/svn_client.lo] Error 1
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `write': Broken pipe (Errno::EPIPE)
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `puts'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:49:in `rescue in block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:31:in `block (3 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:30:in `block (2 levels) in safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `open'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:27:in `block in safe_fork'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:26:in `safe_fork'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:719:in `build'
	from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:311:in `install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:321:in `install_formula'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:253:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `each'
	from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:251:in `install'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

READ THIS: https://docs.brew.sh/Troubleshooting

=== > Installation failed.

- What you expected to happen
===> Java HL Libraries to be installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

Just called this one command:

$ brew install --universal --java subversion

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by m1thrand1r** [comment]
Could you be more specific!? I answered all the questions in the checkliste, didn't I?

**Comment by MikeMcQuaid** [comment]
> [ ]  ran `brew update` and can still reproduce the problem?
> [ ]  ran `brew doctor`, fixed all issues and can still reproduce the problem?
> [ ]  ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> [ ]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by m1thrand1r** [comment]
Ah, sorry.

[ x] ran brew update and can still reproduce the problem?
New installation. Tried brew update.
[ x] ran brew doctor, fixed all issues and can still reproduce the problem?
No issues.
[ -] ran brew gist-logs <formula> (where <formula> is the name of the formula that failed) and included the output link?
[ -] if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

I cannot reproduce that now because I copied the javahl libraries from another computer. Dirty, but I got it to work.

**Comment by MikeMcQuaid** [comment]
In future we need the `brew gist-logs` output. If you can't reproduce now there's nothing for us to do here.

**Comment by toeklk** [comment]
FWIW,

I have exactly the same error when running `brew upgrade subversion`.

`==> make swig-rb EXTRA_SWIG_LDFLAGS=-L/usr/lib
/bin/sh "/private/tmp/subversion-20181002-55007-1g1zbkh/subversion-1.10.2/libtool" --tag=CC --silent --mode=compile none  -I/Users/kgad/homebrew/opt/sqlite/include -I/Users/kgad/homebrew/opt/readline/include -I/Users/kgad/homebrew/opt/openssl/include -isystem/Users/kgad/homebrew/include -F/Users/kgad/homebrew/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/private/tmp/subversion-20181002-55007-1g1zbkh/subversion-1.10.2/subversion/bindings/swig/ruby/libsvn_swig_ruby -prefer-pic -c -o subversion/bindings/swig/ruby/svn_client.lo subversion/bindings/swig/ruby/svn_client.c
/private/tmp/subversion-20181002-55007-1g1zbkh/subversion-1.10.2/libtool: line 1760: none: command not found
make: *** [subversion/bindings/swig/ruby/svn_client.lo] Error 1`

Strangely enough, brew gist-logs asks for my github key, but doesn't return a result

` brew gist-logs subversion && echo error code 0`

returns

`error code 0`

[kgad@FM00022 ~]$  
 brew config
HOMEBREW_VERSION: 1.7.6-55-g52d04dc
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 52d04dc97c38690a1202a2621ba0ae8846543731
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f12ebaefd2097352d07c64eacb9d01184176568
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /Users/kgad/homebrew
HOMEBREW_REPOSITORY: /Users/kgad/homebrew
HOMEBREW_CELLAR: /Users/kgad/homebrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_GITHUB_API: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /Users/kgad/homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /Users/kgad/homebrew/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_40, 1.7.0_51
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
[kgad@FM00022 ~]$  
 brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/kgad/homebrew/anaconda3/bin/icu-config
  /Users/kgad/homebrew/anaconda3/bin/freetype-config
  /Users/kgad/homebrew/anaconda3/bin/xslt-config
  /Users/kgad/homebrew/anaconda3/bin/libpng16-config
  /Users/kgad/homebrew/anaconda3/bin/python3.6m-config
  /Users/kgad/homebrew/anaconda3/bin/libpng-config
  /Users/kgad/homebrew/anaconda3/bin/xml2-config
  /Users/kgad/homebrew/anaconda3/bin/python3-config
  /Users/kgad/homebrew/anaconda3/bin/curl-config
  /Users/kgad/homebrew/anaconda3/bin/ncursesw6-config
  /Users/kgad/homebrew/anaconda3/bin/pcre2-config
  /Users/kgad/homebrew/anaconda3/bin/pcre-config
  /Users/kgad/homebrew/anaconda3/bin/python3.6-config

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  subversion

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.
