### ISSUE TITLE
Missing JPL library in swi-prolog

### ISSUE THREAD

**Issue by theochampion** [Homebrew/homebrew-core#32364]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Hi, I'm trying to use JPL with swi-prolog on Mac OS High sierra and I noticed that when I install it via homebrew, the `libjpl.dylib` is missing. However, when I download the same version (`.dmg`) from the swi-prolog website, the library is here.

```
ls /usr/local/Cellar/swi-prolog/7.6.4/libexec/lib/swipl-7.6.4/lib/x86_64-darwin17.3.0/
```
give me
```
cgi.dylib               json.dylib              porter_stem.dylib       sgml2pl.dylib           time.dylib
crypt.dylib             libedit4pl.dylib        process.dylib           sha4pl.dylib            turtle.dylib
crypto4pl.dylib         libswipl.a              prolog_stream.dylib     snowball.dylib          uid.dylib
double_metaphone.dylib  libswipl.dylib          protobufs.dylib         socket.dylib            unicode4pl.dylib
files.dylib             md54pl.dylib            rdf_db.dylib            ssl4pl.dylib            unix.dylib
hashstream.dylib        memfile.dylib           readline4pl.dylib       streaminfo.dylib        uri.dylib
http_stream.dylib       ntriples.dylib          readutil.dylib          syslog.dylib            websocket.dylib
isub.dylib              pdt_console.dylib       rlimit.dylib            table.dylib             zlib4pl.dylib
```

I also noticed there is a `--with-jpl` option but when I add this option the result is even worst, I get no libraries at all

```
ls /usr/local/Cellar/swi-prolog/7.6.4/libexec/lib/swipl-7.6.4/lib/x86_64-darwin17.7.0/
```
```
libswipl.a      libswipl.dylib
```

Any idea why ?

Thanks !

**Comment by MikeMcQuaid** [comment]
Note sure why, sorry. We'll review a PR to try and improve the situation.
