### ISSUE TITLE
gcc@4.9 failed to build on 10.14

### ISSUE THREAD

**Issue by tilthouse** [Homebrew/homebrew-core#32425]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
There is one config script (`/Applications/Postgres.app/Contents/Versions/9.6/bin/gdal-config`) that certainly doesn't seem related

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/tilthouse/0d1346ffd5ae30ae3386a852081f833d

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Reinstall `gcc@4.9` after Mojave upgrade

- What happened (include command output)
```
$ brew reinstall gcc@4.9
[... snip ... many lines of output, see gist...]
libtool: link: ranlib .libs/libquadmath.a
libtool: link: ( cd ".libs" && rm -f "libquadmath.la" && ln -s "../libquadmath.la" "libquadmath.la" )
make: *** [bootstrap] Error 2
```

- What you expected to happen
Reinstall to succeed

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install gcc@4.9

**Comment by tilthouse** [comment]
I did a `brew clean -s` and rerun and got a different error

https://gist.github.com/tilthouse/ecfebee20a82ce4de119ace6f2aff952

**Comment by fxcoudert** [comment]
Thanks for the report. Yes, GCC 4.9 and GCC 5 are unsupported on macOS Mojave. This is now clearly indicated: https://github.com/Homebrew/homebrew-core/commit/0d7509ea6597ece65400d0bfedbb3801235f4438
