### ISSUE TITLE
upx 3.95 output of binary 'go' file can not run on macOS

### ISSUE THREAD

**Issue by hmage** [Homebrew/homebrew-core#32422]
Already reported upstream and fixed in devel branch -- https://github.com/upx/upx/issues/222

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
run go binary compressed with upx 3.95

- What happened (include command output)
`[1]    9461 killed     ./go-test`
- What you expected to happen
compiled and upx-compressed go binlary work as normal
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install go upx
mkdir go-test
cd go-test
cat << EOF > go-test.go
package main

import "fmt"

func main() {
	fmt.Println("Hello World")
}
EOF
go build
upx go-test
./go-test
```

**Comment by fxcoudert** [comment]
> Already reported upstream and fixed in devel branch

Then it will be in Homebrew when the next release is made. In the meantime, you can `brew install --HEAD upx`

**Comment by hmage** [comment]
HEAD in upx/upx defaults to `master`, and `master` is not updated between releases, their development branch is in `devel`, you might want to update upx formula to pull from `devel` when passed --HEAD.

**Comment by hmage** [comment]
Alternatively, you can just download a patch https://github.com/upx/upx/commit/4d1c754af943f4640062884f38742fd97a6bda0d.patch and apply it, like 4.94 had.
