### ISSUE TITLE
PHP7.2 module fails to load in macOS mojave (14.2)

### ISSUE THREAD

**Issue by paschaldev** [Homebrew/homebrew-core#32436]
just updated to macOS mojave and unfortunately I can't get `php7_module` to load with the default apache on macOS.

Firstly, I installed with `brew install php`, after successfully installing. I added this line to my apache as instructed in terminal 

### httpd.conf

```conf
...
LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so
...
```

Now when I run `sudo apachectl restart`, I tried to reload my webpage and I get no response as if the server did not start at all. So I ran `sudo apachectl` and I see this in my terminal.

```
httpd: Syntax error on line 178 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php/lib/httpd/modules/libphp7.so into server: dlopen(/usr/local/opt/php/lib/httpd/modules/libphp7.so, 10): no suitable image found.  Did find:\n\t/usr/local/opt/php/lib/httpd/modules/libphp7.so: code signature in (/usr/local/opt/php/lib/httpd/modules/libphp7.so) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.\n\t/usr/local/opt/php/lib/httpd/modules/libphp7.so: stat() failed with errno=22
```

Looked online and found about a problem related to SIP on Mac so I turned SIP off from recovery with `csrutil disable`. Restarted my system and when I run `sudo apachetl`, I get this new error.

```
httpd: Syntax error on line 178 of /private/etc/apache2/httpd.conf: Cannot load local/opt/php/lib/httpd/modules/libphp7.so into server: dlopen(/usr/local/opt/php/lib/httpd/modules/libphp7.so, 10): Symbol not found: _libiconv\n  Referenced from: /usr/local/opt/php/lib/httpd/modules/libphp7.so\n  Expected in: /usr/lib/libiconv.2.dylib\n in /usr/local/opt/php/lib/httpd/modules/libphp7.so
```

**Comment by SMillerDev** [comment]
It's not made to work with the default apache and disabling SIP is a terrible advice in any case.

**Comment by paschaldev** [comment]
Alright thank you @SMillerDev. Found a way out

**Comment by samir76** [comment]
@paschaldev Can you share with us the way out that you found to solve the issue, please.

**Comment by paschaldev** [comment]
@samir I restarted my system and somehow it started working

**Comment by samir76** [comment]
@paschaldev restarting didn't work for me, but I found an answer that worked from this link - 
https://stackoverflow.com/questions/44981521/homebrew-php-7-1-macos-sierra-apache-syntax-error

**Comment by pratiksahu** [comment]
- Install homebrew apache (brew install httpd)
- disable the default apache (sudo launchctl unload -w /System/Library/LaunchDaemons/org.apache.httpd.plist)
- update the httpd configuration for php7 module (/usr/local/etc/httpd is the path for new apache) 
- LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so
- brew services restart httpd
- Default configuration of http of homebrew uses port 8080 - you can update the configuration in httpd.conf to 80

**Comment by SMillerDev** [comment]
Those are both solutions to a different problem though. The initial problem was an iconv library that could no longer be found. This is a solution for a completely missing PHP binary.

**Comment by francosalcedo** [comment]
I have the same problem, some viable solution? :(

**Comment by SMillerDev** [comment]
If  you have the issue in the main post, could you print the output of `brew linkage php`?

**Comment by yagrasdemonde** [comment]
The solution is like @pratiksahu said : you have to install new apache server (with brew install httpd).
and deactivate built in apache Mac Os. It seems the built in apache Mac Os doesn't work with php 7.2.

For me it works like a charm.

**Comment by SMillerDev** [comment]
That's a completely different issue then was first raised, @francosalcedo if you have the same issue as @paschaldev can you make a new issue? This one is getting derailed
