### ISSUE TITLE
brew doctor Throws "unexpected token" Error on macOS 10.14

### ISSUE THREAD

**Issue by MichaelFoss** [Homebrew/homebrew-core#32430]
Preface
------------------
* I am reporting a bug others will be able to reproduce and not asking a question
* I ran `brew update` and can still reproduce the problem
* I tried to run `brew doctor`, but an error was thrown
* I ran `brew config` and `brew doctor` and included their output
* I updated Xcode to 10.0 and re-installed Xcode Command Line Tools

Description
------------------
Prior to upgrading to macOS Mojave (10.14), `brew update` and `brew upgrade` were run. It stalled when upgrading `ffmpeg` and I had to `kill -9` Homebrew to stop it (control+C did not work).

After finishing, I tried running `brew doctor`; however, it throws an error message (full message attached):
> `Error: 419: unexpected token at '"/usr/lib/libS/usr/local/Cellar/autoconf/2.69'`

Upgrading to Mojave did not fix the issue.

Running `brew gist-logs ffmpeg` yields the following output:
> `Error: No logs.`

Steps to Reproduce
------------------
1. Run `brew doctor`

Expected Results
------------------
The command should run to completion and list all problems and fixes.

Actual Results
------------------
The program errors out prior to completion.

Attachments
------------------
1. [brew-config.txt](https://github.com/Homebrew/homebrew-core/files/2416958/brew-config.txt)
1. [brew-doctor.txt](https://github.com/Homebrew/homebrew-core/files/2416960/brew-doctor.txt)

**Comment by MichaelFoss** [comment]
[brew-config.txt](https://github.com/Homebrew/homebrew-core/files/2416957/brew-config.txt)

**Comment by fxcoudert** [comment]
Can you remove the file at `~/Library/Caches/Homebrew/linkage.db` and try again, please?

**Comment by MichaelFoss** [comment]
```
$ cd ~/Library/Caches/Homebrew/
$ mv linkage.db linkage.db.bak
$ brew doctor
Your system is ready to brew.
