### ISSUE TITLE
reqeuest to update for JMeter 5.0

### ISSUE THREAD

**Issue by rickyngan** [Homebrew/homebrew-core#32442]
reqeuest to update for JMeter 5.0

https://jmeter.apache.org/download_jmeter.cgi
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/java.rb

Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by SMillerDev** [comment]
Please file a pull request to get a formula changed.

**Comment by johannespfeiffer** [comment]
see https://github.com/Homebrew/homebrew-core/pull/32526
