### ISSUE TITLE
MacVim 8.1.-151 on Mojave has issues - CoreText rendering issues

### ISSUE THREAD

**Issue by bertjwregeer** [Homebrew/homebrew-core#32440]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to use MacVim using the CoreText renderer to allow for proper scrolling

- What happened (include command output)

MacVim started flickering, this is a known issue: https://github.com/macvim-dev/macvim/issues/751

- What you expected to happen

MacVim to work

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install macvim
mvim -u NONE
```

Notice that it flickers.

This is a known issue: https://github.com/macvim-dev/macvim/issues/751 and is due to changes in the new SDK, compiled against an older version of the SDK everything works as expected. Even on Mojave, the MacVim formula should continue to use the High Sierra compiled versions of MacVim until this bug is fixed upstream.

**Comment by SMillerDev** [comment]
Our build system can't readily swap out software from earlier macOS versions. If you want to use an older SDK you'll have to compile the software yourself using `brew --from- source install macvim`

**Comment by fxcoudert** [comment]
As you stated, this is not specific to Homebrew. There is a workaround which can be used:

> the workaround was to disable Core Text rending in the advanced preferences

(I am surprised that no-one from MacVim tested it on Mojave betas that have been available for months.)

**Comment by fxcoudert** [comment]
@bertjwregeer again, I understand that this is a workaround, and has limited interest. A real fix should be issued by the MacVim team in a future version. We distribute it. If you have a machine with Xcode 9 and the old SDK, then it will build using that (and work fine). If you have a machine with Xcode 10 and the latest SDK, then there is nothing we can do.

As for bottles, they are always built using the latest SDK, we can't let each formula specify versions of Xcode and SDK, that would be impossible to manage.

(Also of note: next time there is an update of the macvim formula, bottles will be rebuilt on High Sierra, and they will be built again the new SDK this time…)
