### ISSUE TITLE
macOS Mojave, brew install opencascade  , fail

### ISSUE THREAD

**Issue by mahaidong** [Homebrew/homebrew-core#32452]
Error: An exception occured within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - adm/cmake/occt_csf.cmake

**Comment by fxcoudert** [comment]
Please fill out the issue template so we can investigate.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
