### ISSUE TITLE
cockroach failed to build on MacOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by alexgerstein** [Homebrew/homebrew-core#32465]
To help us debug your issue please explain:

## What you were trying to do (and why)
I was trying to install cockroach-db with brew after upgrading to MacOS 10.14 (Mojave).
` brew install cockroach`
 
## What happened (include command output)
https://gist.github.com/alexgerstein/0781fd6260aec1d6edbd4126bd5a27dd
`brew install cockroach` failed due to an undefined symbol for architecture '_fn_complete'. See linked Gist for more detail.

## What you expected to happen
I expect installation to complete successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)
`brew install cockroach`

Xcode and command line tools are installed and up to date.

Changing the command line tool direction between /Library/Developer/CommandLineTools and /Applications/Xcode.app/Contents/Developer did not make a difference.

**Comment by enjoylife** [comment]
Related: https://github.com/knz/go-libedit/pull/12

**Comment by fxcoudert** [comment]
I filed a bug with the upstream project: https://github.com/cockroachdb/cockroach/issues/30765

**Comment by knz** [comment]
This is adressed in go-libedit in https://github.com/knz/go-libedit/pull/13 

we'll update the dependency in cockroachdb

**Comment by fxcoudert** [comment]
@knz what is the current status of this?

**Comment by knz** [comment]
Fixed for crdb 2.0 and 2.1.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
