### ISSUE TITLE
qt@5.5 fails to configure on MacOS Mojave 10.14

### ISSUE THREAD

**Issue by kurtmueller42** [Homebrew/homebrew-core#32467]
gist: https://gist.github.com/kurtmueller42/ff2d7738aaef3db610ea35b386145466

Reproduction:

1. Installed homebrew on a newly setup macbook pro High Sierra
2. Installed MacOS Mojave
3. `brew install qt55`

**Comment by fxcoudert** [comment]
Given that qt@5.5 is not supported on Mojave, and it fails to build, there are two options for us:
- declare it unsupported with `depends_on MaximumMacOSRequirement => :high_sierra`
- remove it altogether, since it does not follow the requirements for versioned formulas: https://docs.brew.sh/Versions

**Comment by eagletmt** [comment]
Same here with High Sierra.
It seems to be caused by Xcode upgrade (10.0), not OS upgrade.

**Comment by fxcoudert** [comment]
It can be the Xcode 10 toolchain, or the 10.14 SDK (which is now used by default on High Sierra with Xcode 10).

**Comment by MikeMcQuaid** [comment]
@fxcoudert I reckon remove it 👍.

**Comment by MahmoudFayed** [comment]
I understand your decision to delete qt@5.5, but we distributed projects that uses this formula.
Now our projects including (The Ring programming language - version 1.8 for macOS) will not work!
Where is the backup for this formula? So we can install it on old macOS versions?

**Comment by MikeMcQuaid** [comment]
> I understand your decision to delete qt@5.5, but we distributed projects that uses this formula.
> Now our projects including (The Ring programming language - version 1.8 for macOS) will not work!
> Where is the backup for this formula? So we can install it on old macOS versions?

`brew extract --help` should help you.

**Comment by fxcoudert** [comment]
If you are hosting formulas that use `qt@5.5`, you can extract the formula from Core (as it was before we removed it) and host it yourself.

**Comment by MahmoudFayed** [comment]
Thanks

**Comment by AlexVentura** [comment]
I have install `Mojave` OS X form scratch and now when I execute `brew install qt55` I got the following errors:
```sh
Error: No available formula with the name "qt55"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
Is there anyway to be able to install `Qt 5.5`?

**Comment by fxcoudert** [comment]
Not from Homebrew core, we do not provide this version anymore, as it failed to build on recent macOS versions.
