### ISSUE TITLE
Md5sha1sum

### ISSUE THREAD

**Issue by ybc3066978** [Homebrew/homebrew-core#32466]
Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by SMillerDev** [comment]
Please fill out the issue template. Right now it's impossible to know what your issue is.
