### ISSUE TITLE
Ruby Runs Away and fills up entire disk!!??

### ISSUE THREAD

**Issue by blue-j** [Homebrew/homebrew-core#32475]
This is a new one!  Any time I `brew install` or `brew cleanup`, I get multiple Ruby processes that **_fill up my entire disk_**.  I don't see anything happening in the Cellar that indicates a storage pile-up.  It is entirely reproducible.  I get the disk space back by killing the ruby processes.  (It did seem to start after i ran the `brew cask cleanup` command for the first time).  My machine is otherwise behaving fine.

Here's my config:

HOMEBREW_VERSION: 1.7.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: f239b7a62790cfb4f33bda9aab7597d43f1b1e3b
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a2aa4aecd954223776009a42316fb95d09318716
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: git
HOMEBREW_MACOS_VERSION_NUMERIC: 101306
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
CLT headers: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11

**Comment by fxcoudert** [comment]
Please fill the issue template, including `brew doctor` output.
Also, where is the disk space consumed? What files are created?

**Comment by vitorlee** [comment]
Same problem here.
macOS 10.14

**Comment by blue-j** [comment]
brew doctor evinced nothing. I couldn’t discover where the storage was being consumed. I sat down to discover that methodically, ran a brew update, and the problem disappeared and was no longer reproducible. I assumed the team discovered and addressed the issue in the update.

**Comment by fxcoudert** [comment]
We have had a few `brew` updates recently, which might have fixed it. Closing for now.
