### ISSUE TITLE
brew cleanup Error: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by joedborg** [Homebrew/homebrew-core#32487]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [NA] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [NA] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Run `brew cleanup` on MacOS Mojave
- What happened (include command output)
```
Error: no implicit conversion of nil into String
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:121:in `escape'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:121:in `stale_cask?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:61:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:253:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:239:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:239:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:163:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:30:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```
- What you expected to happen
No error
- Step-by-step reproduction instructions (by running `brew install` commands)
Upgrade to MacOS Mojave
`brew cleanup`

**Comment by joedborg** [comment]
Have also tried `brew update-reset && brew update`

**Comment by SMillerDev** [comment]
This seems to be a bug report for brew, not the software available through it.
