### ISSUE TITLE
Mojave PHP@5.6 Cellar Not Work Well

### ISSUE THREAD

**Issue by oceanv** [Homebrew/homebrew-core#32485]
1. on a clean mojave os environment，i install php@5.6 with this code `brew install php@5.6`
2. after all download finish, modify http.conf at `/usr/local/etc/httpd/httpd.conf` 
3. add code `LoadModule php5_module /usr/local/opt/php@5.6/lib/httpd/modules/libphp5.so`
4. add code `AddType application/x-httpd-php .php`
5. restart apache by `sudo apachectl restart`
6. visit the test page `test.php` with code `phpinfo();`
7. the result is `ERR_EMPTY_RESPONSE`
8. and the http head is below:
    - Request URL: http://127.0.0.1/test.php
    - Referrer Policy: no-referrer-when-downgrade
    - Provisional headers are shown
    - Upgrade-Insecure-Requests: 1
    - User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like 
    - Gecko) Chrome/69.0.3497.100 Safari/537.36
9. i also attemp to repair by commod in below:
   -  `brew uninstall php@5.6`
   - `brew install --build-from-source php@5.6`
   - this also don't work
10. the same cofigure is work with php@7.1 is ok
11. i don't now what to do , help me please!

**Comment by fxcoudert** [comment]
Tracked as #32434 
Please provide an error log / backtrace there.
