### ISSUE TITLE
undefined method `shelljoin' for nil:NilClass

### ISSUE THREAD

**Issue by ALiuGuanyan** [Homebrew/homebrew-core#32495]
When I use brew install Julia on OS 10.14, the terminal shows me `Error: undefined method `shelljoin' for nil:NilClass`

**Comment by SMillerDev** [comment]
Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

Without it it'd be impossible to debug your issue. I'll close this so you can make a new one.
