### ISSUE TITLE
[BUG] Segmentation fault

### ISSUE THREAD

**Issue by MacFlurry** [Homebrew/homebrew-core#32493]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ brew upgrade] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ wdiff-1.2.2_1.high_sierra.bottle.tar.gz] have a problem with `brew upgrade` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- I'm trying to do a `brew upgrade`
- While pouring  wdiff-1.2.2_1.high_sierra.bottle.tar.gz , `/usr/local/Homebrew/Library/Homebrew/cache_store.rb:31: [BUG] Segmentation fault at 0x00007f97ea7ffffe`
- I expected to have no Crash Report log information
- `brew upgrade`
- Crash report at `https://gist.github.com/MacFlurry/d804172bd7f1a8866f329ee793708452`

**Comment by SMillerDev** [comment]
While this is a bug for homebrew/brew, you can probably fix it by removing `~/Library/Caches/Homebrew/linkage.db`

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
