### ISSUE TITLE
Provide different python versions

### ISSUE THREAD

**Issue by bsipocz** [Homebrew/homebrew-core#32513]
It would be super useful to be able to install different python versions with homebrew. E.g. as `brew install python@3.6.5` or  `python@3.5.5`. I've recently switched to use homebrew, and this is a feature that I miss most from my previous solution.

My developer environment (and as far as I know it's not uncommon in python land) is to install python from the main package management system, but then manage python packages for those versions independently by pip. 
Some people like to work within conda environment, that case this issue is non existent, but as I work on releasing packages, I like to keep my development environment free from that extra layer and install directly from pypi.

**Comment by commitay** [comment]
Please see the discussion in https://github.com/Homebrew/homebrew-core/pull/10239

**Comment by bsipocz** [comment]
Thanks. I know that pyenv is an option, but that's a route I wasn't keen to take, it adds an extra layer of complexity though not as much as conda that I mentioned above.

 Seeing that other people would have liked to have what I proposed above, but it's still not supported, probably the solution would be for me to return to use other package managers.
