### ISSUE TITLE
sshfs is outdated

### ISSUE THREAD

**Issue by clavichord93** [Homebrew/homebrew-core#32517]
The sshfs in homebrew-core is 2.10.0, which is outdated.
The latest sshfs is 3.5.0. Any idea about updating sshfs?

**Comment by SMillerDev** [comment]
Homebrew depends on users filing pull requests to update software. It just seems like nobody updated it yet.

**Comment by commitay** [comment]
See the linked issues in https://github.com/Homebrew/homebrew-core/pull/15418
