### ISSUE TITLE
homebrew-core/Formula/hydra.rb

### ISSUE THREAD

**Issue by 98882qqqrent** [Homebrew/homebrew-core#3253]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Formula Requests:

homebrew-core/Formula/hydra.rb is version 8.1

But version which I need to run is 8.2

https://github.com/vanhauser-thc/thc-hydra/releases

Is it going to be updated?

Thankyou

**Comment by Numbermaniac** [comment]
You can always [do it yourself](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md), if you want.

**Comment by DomT4** [comment]
Yup, that'd be ideal. If you want something that isn't already part of `homebrew/core` yet, PRs are the best way to get it done quickly.
