### ISSUE TITLE
Python3 slow performance compared to Python2

### ISSUE THREAD

**Issue by bartskowron** [Homebrew/homebrew-core#32556]
Since the Python@2 was fixed (#22743), I have checked the same benchmark[1] on the recent versions and noticed regression for Python3 that wasn't before.

macOS 10.13.6:
python(bundled) - 3.9504430294s
python2 - 3.93767094612s
python3 - 7.765639066696167s (x2 slower)
pypy2 - 0.0655200481415s
pypy3 - 0.06621408462524414s

Ubuntu 18.04 (via VirtualBox)
python2 - 2.97942495346s
python3 - 4.268168210983276s (x1.5 slower but still with nice result)

There is 100% performance regression on Python3 from Homebrew.

Also, worth to notice that virtualised (on the same machine) Ubuntu gives the best performance.

[1] Benchmark test:
```python
import time

def f(n):
    while n > 0:
        n -= 1

start = time.time()
f(100000000)
stop = time.time()
print(stop-start)
```

**Comment by fxcoudert** [comment]
On my laptop with Mojave:

Version | Time
----- | ----
system Python 2 | 2.65 s
Homebrew Python 2 | 2.23 s
Homebrew Python 3 | 4.64 s
Anaconda Python 3 | 4.29 s

Not sure there is a problem specific to Homebrew here…

**Comment by MikeMcQuaid** [comment]
> Not sure there is a problem specific to Homebrew here…

Agreed.

We'll review PRs that improve performance.
