### ISSUE TITLE
openvpn on osx 10.9: homebrew-core/Formula/openvpn.rb

### ISSUE THREAD

**Issue by pvtmert** [Homebrew/homebrew-core#3257]
hi there,
since last update to formula, i cannot install new version, thus fails to upgrade other packages as well

    openvpn: OS X Yosemite or newer is required.

either allow tun-tap (which is moved to cask btw) on mavericks, or just force mavericks to be in last supported version

thx

**Comment by ilovezfs** [comment]
Indeed: https://github.com/Homebrew/homebrew-core/pull/3103

You'll need to uninstall it, or maintain a version in your own tap. For 10.10 and above tuntap isn't required, and we have no way of testing things that require tuntap currently, so anything a hard dependency on tuntap (e.g., openvpn on Mavericks) has been boneyarded or restricted accordingly.
