### ISSUE TITLE
Weechat fails to build on macOS Mojave with `--with-ruby` flag

### ISSUE THREAD

**Issue by ahmedelgabri** [Homebrew/homebrew-core#32572]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/ahmedelgabri/6d3b1dd37e4cc165f17de4b406ebfcf3

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):

Install `weechat` on macOS Mojave 

- What happened (include command output)

```
λ brew install weechat --with-curl --with-python@2 --with-perl --with-lua --with-ruby
==> Reinstalling weechat --with-perl --with-ruby --with-curl --with-lua --with-python@2
==> Downloading https://weechat.org/files/src/weechat-2.2.tar.xz
Already downloaded: /Users/ahmed/Library/Caches/Homebrew/downloads/1e8f2922e8b1e82f9b31cd3e5fd3b312e1fd9ee6feb768ae9daf36acf70f2d5f--weechat-2.2.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/weechat/2.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DENABLE_MAN=ON -DENABLE_GUILE=OFF -DCA_FILE=/u
==> make install VERBOSE=1
Last 15 lines from /Users/ahmed/Library/Logs/Homebrew/weechat/02.make:
[ 51%] Building C object src/plugins/irc/CMakeFiles/irc.dir/irc-upgrade.o
cd /tmp/weechat-20180930-54766-1ajp4ka/weechat-2.2/build/src/plugins/irc && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DENABLE_NLS -DHAVE_CONFIG_H -DHAVE_GCRYPT -DHAVE_GNUTLS -DHAVE_ICONV -DHAVE_ZLIB -DWEECHAT_LICENSE=\"GPL3\" -DWEECHAT_VERSION=\"2.2\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_LARGE_FILES -Dirc_EXPORTS -I/usr/local/include -I/tmp/weechat-20180930-54766-1ajp4ka/weechat-2.2/build  -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -fPIC   -fPIC -fPIC -o CMakeFiles/irc.dir/irc-upgrade.o   -c /tmp/weechat-20180930-54766-1ajp4ka/weechat-2.2/src/plugins/irc/irc-upgrade.c
[ 51%] Linking C shared module python.so
cd /tmp/weechat-20180930-54766-1ajp4ka/weechat-2.2/build/src/plugins/python && /usr/local/Cellar/cmake/3.12.2/bin/cmake -E cmake_link_script CMakeFiles/python.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -ldl  -framework CoreFoundation -u _PyMac_Error /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/Python -o python.so CMakeFiles/python.dir/weechat-python.o CMakeFiles/python.dir/weechat-python-api.o /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib ../libweechat_plugins_scripts.a
[ 51%] Built target python
[ 51%] Linking C shared module irc.so
cd /tmp/weechat-20180930-54766-1ajp4ka/weechat-2.2/build/src/plugins/irc && /usr/local/Cellar/cmake/3.12.2/bin/cmake -E cmake_link_script CMakeFiles/irc.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o irc.so CMakeFiles/irc.dir/irc.o CMakeFiles/irc.dir/irc-bar-item.o CMakeFiles/irc.dir/irc-buffer.o CMakeFiles/irc.dir/irc-channel.o CMakeFiles/irc.dir/irc-color.o CMakeFiles/irc.dir/irc-command.o CMakeFiles/irc.dir/irc-completion.o CMakeFiles/irc.dir/irc-config.o CMakeFiles/irc.dir/irc-ctcp.o CMakeFiles/irc.dir/irc-debug.o CMakeFiles/irc.dir/irc-ignore.o CMakeFiles/irc.dir/irc-info.o CMakeFiles/irc.dir/irc-input.o CMakeFiles/irc.dir/irc-message.o CMakeFiles/irc.dir/irc-mode.o CMakeFiles/irc.dir/irc-modelist.o CMakeFiles/irc.dir/irc-msgbuffer.o CMakeFiles/irc.dir/irc-nick.o CMakeFiles/irc.dir/irc-notify.o CMakeFiles/irc.dir/irc-protocol.o CMakeFiles/irc.dir/irc-raw.o CMakeFiles/irc.dir/irc-redirect.o CMakeFiles/irc.dir/irc-sasl.o CMakeFiles/irc.dir/irc-server.o CMakeFiles/irc.dir/irc-upgrade.o /usr/local/lib/libgnutls.dylib -L/usr/local/opt/libgcrypt/lib -lgcrypt -L/usr/local/opt/libgpg-error/lib -lgpg-error -lresolv
[ 51%] Built target irc
[ 51%] Linking C shared module perl.so
cd /tmp/weechat-20180930-54766-1ajp4ka/weechat-2.2/build/src/plugins/perl && /usr/local/Cellar/cmake/3.12.2/bin/cmake -E cmake_link_script CMakeFiles/perl.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang   -Wall -Wextra -Werror-implicit-function-declaration -DNDEBUG -bundle -Wl,-headerpad_max_install_names     -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lpthread -ldl -lm -lutil -lc -o perl.so CMakeFiles/perl.dir/weechat-perl.o CMakeFiles/perl.dir/weechat-perl-api.o /usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE/libperl.dylib ../libweechat_plugins_scripts.a
[ 51%] Built target perl
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
WeeChat fails to build --with-python https://github.com/Homebrew/homebrew-core/issues/30509
```

- What you expected to happen:

To install `weechat`

- Step-by-step reproduction instructions (by running `brew install` commands):

Any other variation of this command works fine, except when I add `--with-ruby`

```
brew install weechat --with-curl --with-python@2 --with-perl --with-lua --with-ruby
```

**Comment by MindTooth** [comment]
Works fine for me.  So maybe there is something with your config.

Care to run the following:

1: `brew update-reset && brew update`

2: `brew --config` and post it.

3: `brew install weechat --with-curl --with-python@2 --with-perl --with-lua --with-ruby --verbose | pbcopy`
and copy that into a Gist or something.

**Comment by ahmedelgabri** [comment]
`brew --config`

```
HOMEBREW_VERSION: 1.7.6-70-g8f03ea7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8f03ea7ca9f9452cd75ac9d6ec99f8f502cdf877
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c774db44013931a2f69885d0e117d739d2fce58b
Core tap last commit: 22 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: /usr/local/opt/git/bin/git
HOMEBREW_FORCE_BREWED_GIT: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_INSTALL_BADGE: ⚽️
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_ROOT: /usr/local
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/opt/git/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

& here is a gist with the output https://gist.github.com/ahmedelgabri/38663fc4f7766eccc06c2a3b2a159c17

**Comment by MindTooth** [comment]
Have you reinstalled Ruby yet?  As you've told that it is crashing when you have `--with-ruby`.

I had some issues with `brew style` and spent a night installing, reinstalling Ruby.  And it popped into my that an old Ruby might be the issue.

**Comment by MindTooth** [comment]
The error seems to be:
```sh
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/ruby/ruby.h:24:10: fatal error: 'ruby/config.h' file not found
```

Care to run `xcode-select -p` and post the path?  Followed the tips of [StackOverflow](https://stackoverflow.com/questions/26434642/yosemite-upgrade-broke-ruby-h).

**Comment by ahmedelgabri** [comment]
`xcode-select -p` returns `/Library/Developer/CommandLineTools` 

This issue seems similar too https://github.com/Homebrew/homebrew-core/issues/32464

**Comment by MindTooth** [comment]
Did you try:
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by ahmedelgabri** [comment]
Didn't help, still getting the same error.

**Comment by MindTooth** [comment]
Last I can think of is that you try to download the commandline tools from https://developer.apple.com/download/more/?name=command%20line%20tools.

I've seen it solve some issues for others.

**Comment by viing937** [comment]
> `xcode-select -p` returns `/Library/Developer/CommandLineTools`
> 
> This issue seems similar too #32464

Yes, it seems the same problem.
Did you try `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`, which I mentioned in https://github.com/Homebrew/homebrew-core/issues/32464?

**Comment by ahmedelgabri** [comment]
@viing937 	didn't see that comment, tried it & yes it fixed the problem. Thanks!

@MindTooth more info can be found here (search for "macOS_SDK_headers_for_macOS_10.14.pkg") https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes

**Comment by MindTooth** [comment]
Would you look at that..  Glad it worked out for you.

**Comment by ahmedelgabri** [comment]
> Would you look at that.. Glad it worked out for you.

You mean as open a PR to fix the issue? I don't mind, but honestly I dunno where to start & how to do it :)

**Comment by MindTooth** [comment]
@ahmedelgabri: https://www.youtube.com/watch?v=EF8GhC-T_Mo 🤣

**Comment by ahmedelgabri** [comment]
@MindTooth funny video, but I'm sorry. Don't understand what you mean :) 

I'll close the issue since the issue was fixed for me.

**Comment by MindTooth** [comment]
Ment it as a realization.  E.g. "Ohh, would you look at that..  He finally made it." 😉
