### ISSUE TITLE
unable to install atlassian-cli

### ISSUE THREAD

**Issue by iqarmy** [Homebrew/homebrew-core#32584]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/6465ebe733a7ac47c99caf16fa365547
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install atlassian-cli formulae
- What happened (include command output)
$ brew install atlassian-cli
==> Downloading https://bobswift.atlassian.net/wiki/download/attachments/16285777/atlassian-cli-8.0.0-distribution.zip
Already downloaded: /Users/victori/Library/Caches/Homebrew/downloads/ea225576eb32454b139b5a7da4e231c2cab091600774448c21cadb46a1a02066--name=atlassian-cli-8.0.0-distribution.zip
Error: An exception occured within a child process:
  ArgumentError: parent directory is world writable but not sticky
- What you expected to happen
Successfull installation of atlassian-cli
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install atlassian-cli

**Comment by fxcoudert** [comment]
Poking @reitermarkus who knows the unpack code well…
