### ISSUE TITLE
graph-tool failed to build on 10.14

### ISSUE THREAD

**Issue by 6ui11aum3** [Homebrew/homebrew-core#32592]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
_Install the library graph-tool for python3 on my Mac_
- What happened (include command output)
_Error during the installation_
- What you expected to happen
_Successfully install the library graph-tool for python3_
- Step-by-step reproduction instructions (by running `brew install` commands)
_All I did is install homebrew, and then I ran:_
brew install graph-tool

I attached the error output.
[brew_config.txt](https://github.com/Homebrew/homebrew-core/files/2434089/brew_config.txt)
[brew_install_graphtool.txt](https://github.com/Homebrew/homebrew-core/files/2434090/brew_install_graphtool.txt)

**Comment by snail123815** [comment]
I have the same problem, same error output.
Compiling from source code worked for me (once), but while using it, there was some problem with matplotlib back end.

**Comment by fxcoudert** [comment]
Partial fix can be found in #32851
I am trying to complete it
