### ISSUE TITLE
Using LLVM and OpenMP in Xcode for iOS

### ISSUE THREAD

**Issue by GitZChen** [Homebrew/homebrew-core#3266]
Not sure if this is the right place to ask this question, but we are trying to use openMP in Xcode -> actually porting an open-source C++ project that uses Eigen to iOS. After clang-omp has been moved to boneyard, the steps/configs outlined in the [clang-omp doc](https://clang-omp.github.io/) are no longer valid. So we are wondering if anyone would be willing to offer a new tutorial to use the latest llvm and OpenMP package with Xcode? Thanks!

Currently, we have tried adding `i386;arm` to `-DLIBOMP_ARCH=x86_64;` in the llvm formula, then `brew install llvm --universal --with-all-targets --with-clang --with-lldb --with-toolchain` and finally use the generated llvm 3.8.1 toolchain in Xcode, but it's not linking properly for iOS devices (arm64) or the Simulator (i386) - 

> `ld: warning: URGENT: building for iOS simulator, but linking against dylib (/usr/local/Cellar/llvm/3.8.1/Toolchains/LLVM3.8.1.xctoolchain/usr/lib/libc++.dylib) built for OSX. Note: This will be an error in the future.
Undefined symbols for architecture i386: ...` 

Also, would you guys consider offering an option to build the llvm and clang package for iOS' architectures in homebrew? @DomT4  @MikeMcQuaid 

Thank you for your hard work!
Zachary

**Comment by DomT4** [comment]
> So we are wondering if anyone would be willing to offer a new tutorial to use the latest llvm and OpenMP package with Xcode? Thanks!

There are some hints as to this in the LLVM formula already :)
```ruby
    (testpath/"omptest.c").write <<-EOS.undent
      #include <stdlib.h>
      #include <stdio.h>
      #include <omp.h>

      int main() {
          #pragma omp parallel num_threads(4)
          {
            printf("Hello from thread %d, nthreads %d\\n", omp_get_thread_num(), omp_get_num_threads());
          }
          return EXIT_SUCCESS;
      }
    EOS

    system "#{bin}/clang", "-L#{lib}", "-fopenmp", "-nobuiltininc",
                           "-I#{lib}/clang/#{version}/include",
                           "omptest.c", "-o", "omptest"
    testresult = shell_output("./omptest")
```
From that we could guess, although I haven't tested this, new Xcode build steps would be:

* `brew install llvm`
* Create a new Xcode project.
* Under Build Settings:
  * Add a new user-defined setting CC with the value `/usr/local/opt/llvm/bin/clang`
  * Add `-fopenmp` to Other C Flags
  * Add `/usr/local/opt/llvm/lib/clang/3.8.1/include` to Header Search Paths
  * Add `/usr/local/opt/llvm/lib` to Library Search Paths
  * Set Enable Modules (C and Objective-C) to `No`.
* Under Build Phases:
  * Add `/usr/local/opt/llvm/lib/libiomp5.dylib` to Link Binary With Libraries
* Done. You can now #include <omp.h> and start using `#pragma omp` ... in your source code.

Using the provided blob of code [here](https://gist.githubusercontent.com/clang-omp/638a40f3a797315661d6/raw/0a4711e2123f621c1a6656d6e447018df333ea8a/hello.c) that seems to work for me:
```
~> ~/Downloads/Hello/build/Debug/Hello
Hello from thread 0, nthreads 8
Hello from thread 2, nthreads 8
Hello from thread 3, nthreads 8
Hello from thread 4, nthreads 8
Hello from thread 1, nthreads 8
Hello from thread 7, nthreads 8
Hello from thread 6, nthreads 8
Hello from thread 5, nthreads 8

~> otool -L ~/Downloads/Hello/build/Debug/Hello
	/usr/local/opt/llvm/lib/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by DomT4** [comment]
> Also, would you guys consider offering an option to build the llvm and clang package for iOS' architectures in homebrew?

Depends what this would entail in terms of addition to the formula, but yeah, probably.

**Comment by GitZChen** [comment]
Hi @DomT4 ! Thanks for your response. I just tried your steps and there are still some problems. 

The first is that clang 3.8.1's module.modulemap clash with that of Swift's in Xcode's default toolchain. Solved that problem by moving `/usr/local/opt/llvm/lib/clang/3.8.1/include` from **Header Search Paths** to User defined `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH`. Now Swift uses the default headers and C & C++ uses the new headers. Not sure if there's a better way of solving this problem or what the actual problem was? The errors were a bunch of `Redefinition of module 'xxx'` and I had Enable Modules set to NO.

The second problem is a lot more confusing - the project built successfully but still with the linker warnings: 
```
URGENT: building for iOS simulator, but linking against dylib (/usr/local/opt/llvm/lib/**libomp.dylib/libc++.dylib**) built for OSX. 
Note: This will be an error in the future.
``` 
then crashed immediately after launching saying 
```
dyld: Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib.
...
Reason: no suitable image found.  Did find:
	/usr/local/opt/llvm/lib/libomp.dylib: mach-o, but not built for iOS simulator
```
Thought that since I enabled the `--universal` flag and had `-DLIBOMP_ARCH=x86_64;i386;arm` when building the llvm formula, the libraries should have been built for the target architectures? And with the Xcode project compiled and linked successfully, we can assume that i386 symbols are present, right? So what does it mean "dylib built for OSX instead of simulator??"

Thanks for your help!
Zachary

**Comment by MikeMcQuaid** [comment]
Closing this not to say @DomT4 shouldn't reply but just that this isn't a Homebrew issue.

**Comment by DomT4** [comment]
@GitZChen Your follow up question is out of my ballpark I'm afraid. I can answer fairly simple questions about compilers but beyond that I really _really_ try to avoid dealing with them. @aw1621107 & @maxim-belkin do a fair bit of work on `llvm` stuff with Homebrew & may have a better idea.

**Comment by GitZChen** [comment]
@MikeMcQuaid My apologies - thought that this isn't really that Homebrew related but got no where else to go. Sorry!

@DomT4 No worries! Thank you for all your work and for trying to answer all my questions! Really this is Apple being stupid on compatibility with open-source stuff and helping developers. If they had done better in this area, homebrew would never have to exist in the first place. I'll try PM'ing @aw1621107  & @maxim-belkin on the side. Thanks again!

**Comment by maxim-belkin** [comment]
I don't know if I can be of much help here. Currently, Homebrew detects the XCode SDK installed and uses `-isysroot ....SDKs/MacOSX10.XX.sdk`. To build libs for iOS simulator, you have to make Homebrew use isysroot for the iOS simulator. And add something like [`-mios-simulator-version-min=8.0`](https://gist.github.com/SquaredTiki/d5da9d1c1ee78a587c76)

Try using the solutions from [here](http://stackoverflow.com/questions/26558038/ld-building-for-ios-simulator-but-linking-against-dylib-built-for-macosx-file) and [there](http://stackoverflow.com/questions/23092201/ld-building-for-ios-simulator-but-linking-against-dylib).
