### ISSUE TITLE
Error installing datomic in macOS Mojave

### ISSUE THREAD

**Issue by aldofunes** [Homebrew/homebrew-core#32668]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **[https://gist.github.com/aldofunes/b638eed1e72bfc43c693d414600b132a](https://gist.github.com/aldofunes/b638eed1e72bfc43c693d414600b132a)**
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Problem

I want to install datomic in my freshly-formatted Mac (macOS Mojave). However it breaks with a strange ENOTFOUND error.

## Command
The command I ran was `brew install datomic`

## Output
Here is the output:
```
| => brew install datomic
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 3e6531ad3 to c97d3b0fb.
No changes to formulae.

==> Downloading https://my.datomic.com/downloads/free/0.9.5703
Already downloaded: /Users/homeuser/Library/Caches/Homebrew/downloads/26d1e1fc890d22f5586b2f8bcced53d9a9c9a754675156889b8e122540cc6f2a--0.9.5703
Error: An exception occured within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - config/samples/free-transactor-template.properties
```

## Info
```
| => brew -v
Homebrew 1.7.6-91-gc97d3b0
Homebrew/homebrew-core (git revision 3bce; last commit 2018-10-03)
Homebrew/homebrew-cask (git revision 6b5397; last commit 2018-10-03)
```

macOS: 10.14 (18A391)

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by ryanmtaylor** [comment]
@MikeMcQuaid is this sufficiently filled out?  I'm having the same issue.  Thanks in advance!

Also this problem makes sense, Datomic needs that license key (obtained on their website) in order to run

**Comment by MikeMcQuaid** [comment]
@ryanmtaylor Does that mean Datomic is not open source?

**Comment by ryanmtaylor** [comment]
Datomic is not open source, that's correct.

For the record datomic-free does not require any license key and has a license which allows its binaries to be redistributed freely (e.g. in another open source project).   The only difference is datomic-free has imposed limitations so it won't scale for enterprise etc. projects.  Figured it was worth mentioning.

**Comment by MikeMcQuaid** [comment]
Datomic will need to be removed from Homebrew. It could be added to Homebrew Cask.

**Comment by fxcoudert** [comment]
Closing, as we definitely won't support a closed-source formula in core :)
