### ISSUE TITLE
Imagemagick 7.0.8-12 fails to build on macOS Mojave

### ISSUE THREAD

**Issue by kangstarr** [Homebrew/homebrew-core#32673]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/1ee47b74595f1a2e75f0d0c3de252d3f

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade Imagemagick from 7.0.8-11_2 -> 7.0.8-12

- What happened (include command output)
$ brew upgrade
==> Upgrading 1 outdated package, with result:
imagemagick 7.0.8-11_2 -> 7.0.8-12
==> Upgrading imagemagick --with-fftw --with-hdri --with-libheif --with-opencl --with-openmp --with-perl --with-zero-configuration --with-fo
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick--7.0.8-12.tar.xz
Already downloaded: /Users/skang/Library/Caches/Homebrew/downloads/bd9450cb9fc103c6f39f02f69a35aa97f13f0f39ef3bf2e4913c77bbe37f8521--imagemagick--7.0.8-12.tar.xz
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.8-12 --disable-silent-rules --enable-shared --enable-static
Last 15 lines from /Users/skang/Library/Logs/Homebrew/imagemagick/01.configure:
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
configuring ImageMagick 7.0.8-12
checking whether build environment is sane... yes
checking for style of include used by make... GNU
checking for gcc... gcc-8
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/imagemagick-20181003-57547-1t877jc/ImageMagick-7.0.8-12':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

- What you expected to happen
I would expect it to build properly

- Step-by-step reproduction instructions (by running `brew install` commands)
brew upgrade imagemagick

**Comment by fxcoudert** [comment]
For some reason it's trying to use `gcc-8` as compiler, instead of the system `clang`…

**Comment by phyllisstein** [comment]
It looks like the `gcc` thing is a long-established bugfix for this package: <https://github.com/Homebrew/homebrew-core/issues/2932#issuecomment-232163213>. That said, I was able to get _a little_ farther by installing the Xcode Command Line Tools for Mojave, but failed on another error:

```
checking for libltdl...
checking ltdl.h usability... no
checking ltdl.h presence... no
checking for ltdl.h... no
checking for lt_dlinit in -lltdl... yes
checking if libltdl package is complete... no -- some components failed test
configure: error: in `/private/tmp/imagemagick-20181004-69907-pdmbe3/ImageMagick-7.0.8-12':
configure: error: libltdl is required for modules and OpenCL builds
See `config.log' for more details
```

Adding `--env=std` to my install incantation got me the farthest, but failed on an attempt to include `<libxml/parser.h>`:

```
MagickCore/property.c:105:12: fatal error: libxml/parser.h: No such file or directory
 #  include <libxml/parser.h>
            ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [MagickCore/MagickCore_libMagickCore_7_Q16HDRI_la-property.lo] Error 1
```

The workaround that finally got the whole thing built was to reinstall the Command Line Tools, reinstall GCC to make sure I had the Mojave bottle, and run:

```bash
brew install --with-fftw --with-hdri --with-libheif --with-opencl --with-openmp --with-fontconfig --with-ghostscript --with-liblqr --with-librsvg --with-libwmf --with-little-cms2 --with-openexr --with-openjpeg --with-pango --with-webp --with-x11 --env=std --interactive imagemagick
```

...followed by this command, at the interactive prompt:

```bash
LDFLAGS="-L/usr/local/opt/libxml2/lib -L/usr/local/Cellar/liblqr/0.4.2/lib" CFLAGS="-I/usr/local/opt/libxml2/include/libxml2 -I/usr/local/Cellar/liblqr/0.4.2/include" LIBRARY_PATH=/usr/local/opt/libxml2/include/libxml2:/usr/local/Cellar/liblqr/0.4.2/include LD_LIBRARY_PATH=/usr/local/opt/libxml2/include/libxml2:/usr/local/Cellar/liblqr/0.4.2/include PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig" ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.8-12 --disable-dependency-tracking --disable-silent-rules --enable-shared --enable-static --with-freetype=yes --enable-openmp --with-webp=yes --with-openjp2 --enable-hdri=yes --with-rsvg --with-fontconfig=yes && make install
```

**Comment by fxcoudert** [comment]
OpenMP option is removed, the error should not happen anymore.
