### ISSUE TITLE
brew upgrade ldc fails: fatal error: 'llvm/IR/Attributes.gen' file not found

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#32689]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  llvm_wasm.bak1
  opencv.bak1
  opencv_dbg

Warning: Your Homebrew's prefix is not /usr/local.

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/6900647ea4278d3a5c00b4967614bbf6
the error is here: https://gist.githubusercontent.com/timotheecour/6900647ea4278d3a5c00b4967614bbf6/raw/e08063d677970cf97c01ded875b6ecd1025e86e8/04.make

fatal error: 'llvm/IR/Attributes.gen' file not found

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew upgrade ldc fails: fatal error: 'llvm/IR/Attributes.gen' file not found

/cc @commitay @kinke

**Comment by kinke** [comment]
LDC 1.11 doesn't support LLVM 7, that's new in v1.12...

**Comment by commitay** [comment]
PR to depend on `llvm@6`. #32693
