### ISSUE TITLE
brew upgrade went sideways, asked to report this 

### ISSUE THREAD

**Issue by wrightmac** [Homebrew/homebrew-core#32687]
It has been some time since I updated my brew installation.  I have a MacBookPro (11,5) running Mac OS X 10.12.6. I did a 'brew update' and then I went todo a 'brew upgrade' on my installation. After a couple of minutes I received the input I am pasting below. It stated that I should report it. 

➜  ~ brew upgrade
==> Upgrading 8 outdated packages, with result:
avrdude 6.3 -> 6.3_1, glib 2.58.0_1 -> 2.58.1, node 10.10.0 -> 10.11.0, poppler 0.68.0 -> 0.69.0_1, qt 5.11.1 -> 5.11.2, sqlite 3.25.1 -> 3.25.2, unrar 5.6.6 -> 5.6.7, yarn 1.9.4 -> 1.10.1
==> Upgrading qt
==> Downloading https://homebrew.bintray.com/bottles/qt-5.11.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring qt-5.11.2.sierra.bottle.tar.gz
==> Caveats
We agreed to the Qt open source license for you.
If this is unacceptable you should uninstall.

qt is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have qt first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.zshrc

For compilers to find qt you may need to set:
  export LDFLAGS="-L/usr/local/opt/qt/lib"
  export CPPFLAGS="-I/usr/local/opt/qt/include"

For pkg-config to find qt you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/qt/5.11.2: 9,502 files, 301.8MB
==> Upgrading sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.25.2.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlite-3.25.2.sierra.bottle.tar.gz
==> Caveats
Homebrew has detected an existing SQLite history file that was created
with the editline library. The current version of this formula is
built with Readline. To back up and convert your history file so that
it can be used with Readline, run:

  sed -i~ 's/\\040/ /g' ~/.sqlite_history

before using the `sqlite` command-line tool again. Otherwise, your
history will be lost.

sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have sqlite first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
  export CPPFLAGS="-I/usr/local/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/sqlite/3.25.2: 11 files, 3.7MB
==> Upgrading node
==> Downloading https://homebrew.bintray.com/bottles/node-10.11.0.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring node-10.11.0.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/10.11.0: 3,940 files, 49.4MB
==> Upgrading poppler
==> Installing dependencies for poppler: glib, nspr, nss
==> Installing poppler dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.58.1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glib-2.58.1.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/locale/be/LC_MESSAGES/glib20.mo
/usr/local/share/locale/be/LC_MESSAGES is not writable.

You can try again using:
  brew link glib
==> Summary
🍺  /usr/local/Cellar/glib/2.58.1: 435 files, 18.4MB
==> Installing poppler dependency: nspr
==> Downloading https://homebrew.bintray.com/bottles/nspr-4.20.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring nspr-4.20.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/nspr/4.20: 92 files, 1.2MB
==> Installing poppler dependency: nss
==> Downloading https://homebrew.bintray.com/bottles/nss-3.39.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring nss-3.39.sierra.bottle.tar.gz
==> Caveats
nss is keg-only, which means it was not symlinked into /usr/local,
because Firefox can pick this up instead of the built-in library, resulting in
random crashes without meaningful explanation.

Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1142646 for details.

If you need to have nss first in your PATH run:
  echo 'export PATH="/usr/local/opt/nss/bin:$PATH"' >> ~/.zshrc

For compilers to find nss you may need to set:
  export LDFLAGS="-L/usr/local/opt/nss/lib"
  export CPPFLAGS="-I/usr/local/opt/nss/include"

For pkg-config to find nss you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/nss/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/nss/3.39: 220 files, 25.5MB
==> Installing poppler
==> Downloading https://homebrew.bintray.com/bottles/poppler-0.69.0_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring poppler-0.69.0_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/poppler/0.69.0_1: 445 files, 23MB
==> Upgrading unrar
==> Downloading https://homebrew.bintray.com/bottles/unrar-5.6.7.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring unrar-5.6.7.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/unrar/5.6.7: 6 files, 508.6KB
==> Upgrading avrdude
==> Installing dependencies for avrdude: libhid
==> Installing avrdude dependency: libhid
==> Downloading https://homebrew.bintray.com/bottles/libhid-0.2.16.sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring libhid-0.2.16.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/libhid/0.2.16: 17 files, 178.3KB
==> Installing avrdude
==> Downloading https://homebrew.bintray.com/bottles/avrdude-6.3_1.sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring avrdude-6.3_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/avrdude/6.3_1: 14 files, 1.9MB
==> Upgrading yarn
==> Downloading https://yarnpkg.com/downloads/1.10.1/yarn-v1.10.1.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/49970642/7cc7a700-c14a-11e8-959d-a2
######################################################################## 100.0%
🍺  /usr/local/Cellar/yarn/1.10.1: 14 files, 4.3MB, built in 4 seconds
Error: 784: unexpected token at '{"keg_files_dylibs":{"/usr/local/Cellar/pyqt@4/4.12.1_1/bin/pylupdate4":["/usr/local/opt/qt@4/lib/QtXml.framework/Versions/4/QtXml","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/bin/pyrcc4":["/usr/local/opt/qt@4/lib/QtXml.framework/Versions/4/QtXml","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/Qt.so":["/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtCore.so":["/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtDeclarative.so":["/usr/local/opt/qt@4/lib/QtDeclarative.framework/Versions/4/QtDeclarative","/usr/local/opt/qt@4/lib/QtScript.framework/Versions/4/QtScript","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/local/opt/qt@4/lib/QtSvg.framework/Versions/4/QtSvg","/usr/local/opt/qt@4/lib/QtGui.framework/Versions/4/QtGui","/usr/local/opt/qt@4/lib/QtSql.framework/Versions/4/QtSql","/usr/local/opt/qt@4/lib/QtXmlPatterns.framework/Versions/4/QtXmlPatterns","/usr/local/opt/qt@4/lib/QtNetwork.framework/Versions/4/QtNetwork","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtDesigner.so":["/usr/local/opt/qt@4/lib/QtScript.framework/Versions/4/QtScript","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/local/opt/qt@4/lib/QtXml.framework/Versions/4/QtXml","/usr/local/opt/qt@4/lib/QtGui.framework/Versions/4/QtGui","/usr/local/opt/qt@4/lib/QtDesigner.framework/Versions/4/QtDesigner","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtGui.so":["/usr/local/opt/qt@4/lib/QtGui.framework/Versions/4/QtGui","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtHelp.so":["/usr/local/opt/qt@4/lib/QtHelp.framework/Versions/4/QtHelp","/usr/local/opt/qt@4/lib/QtSql.framework/Versions/4/QtSql","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/local/opt/qt@4/lib/QtGui.framework/Versions/4/QtGui","/usr/local/opt/qt@4/lib/QtNetwork.framework/Versions/4/QtNetwork","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtMultimedia.so":["/usr/local/opt/qt@4/lib/QtMultimedia.framework/Versions/4/QtMultimedia","/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices","/System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio","/System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit","/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox","/usr/local/opt/qt@4/lib/QtGui.framework/Versions/4/QtGui","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtNetwork.so":["/usr/local/opt/qt@4/lib/QtNetwork.framework/Versions/4/QtNetwork","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/QtOpenGL.so":["/usr/local/opt/qt@4/lib/QtOpenGL.framework/Versions/4/QtOpenGL","/usr/local/opt/qt@4/lib/QtGui.framework/Versions/4/QtGui","/usr/local/opt/qt@4/lib/QtCore.framework/Versions/4/QtCore","/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL","/System/Library/Frameworks/AGL.framework/Versions/A/AGL","/usr/lib/libc++.1.dylib","/usr/lib/libSystem.B.dylib"],"/usr/local/Cellar/pyqt@4/4.12.1_1/lib/python2.7/site-packages/PyQt4/Qt/usr/local/Cellar/pyqt/5.10.1_1'
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:185:in `json_string_to_ruby_hash'
/usr/local/Homebrew/Library/Homebrew/linkage_cache_store.rb:71:in `fetch_hash_values'
/usr/local/Homebrew/Library/Homebrew/linkage_cache_store.rb:53:in `fetch_type'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:84:in `check_dylibs'
/usr/local/Homebrew/Library/Homebrew/linkage_checker.rb:25:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `new'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:247:in `block (3 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:241:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:241:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:230:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:261:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:230:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:261:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:231:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:230:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:332:in `check_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:86:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
➜  ~

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by fxcoudert** [comment]
Can you remove the file at `~/Library/Caches/Homebrew/linkage.db` and try again, please? It probably will fix the issue.

**Comment by MikeMcQuaid** [comment]
> * ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> * [ ]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
