### ISSUE TITLE
smlnj - fails to install

### ISSUE THREAD

**Issue by vinay** [Homebrew/homebrew-core#32722]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

Yes

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Yes. I am trying to install smlnj and it fails. It seems to be a problem with the latest update of smlnj. It was working with the previous version.

- [x] ran `brew update` and can still reproduce the problem?

Yes

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Yes

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Yes. Output Link -> https://gist.github.com/vinay/7bdb4e9bf65f4eb9a92e4e7b3919a267

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

gist-logs worked, and have included the output link above

To help us debug your issue please explain:
- What you were trying to do (and why)

Ran a brew upgrade to upgrade my smlnj installation. It failed. I then uninstalled smlnj and tried reinstalling it. It still fails with the same message.

- What happened (include command output)

Please see below for complete command output.

Vinays-Mac-mini:~ vinay$ brew install smlnj
==> Downloading http://smlnj.cs.uchicago.edu/dist/working/110.84/config.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/e9e5fab85f3819fb0719631c82c5c402b7ca5108349f723ced716ed5d4852c83--config.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/cm.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/45cb3032536f4238ca9516897f95c2e0d412245c83abe77a1727a1759a8ebb05--cm.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/compiler.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/5fea99bb4cbc0c84d63b8112f9e2199733daa66eb42f904af20d26c133bfcff4--compiler.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/runtime.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/afee0970c47b38ed24c8c5fcd21702ccc220cf1702f3a1948978698c0de46f84--runtime.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/system.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/8320a1fc237cd23e8bc608b1ca384af13e6c07e2023623681760bb77d8569030--system.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/boot.x86-unix.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/8a9569bf3b5aef7b0a1154bb43fda8e0ef90b8ab565c67c5cf20481dafd0fdb0--boot.x86-unix.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/MLRISC.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/28442081510228ac826ff1c1e7e0a56863c9630fe8327c4a9a52d4e4834132d9--MLRISC.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/smlnj-lib.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/ab1906932c275278e73aaef2ea4487d363ae0cf7775f10039d116ee05dc359fc--smlnj-lib.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/ckit.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/cd2e547263bb04077bac3e40b6296316102a8abab705aaa4d626932735d2b020--ckit.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/nlffi.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/8df40056c64d0edcd8f2d4556ea5242318aa369c35a017ee560a049691a5e34e--nlffi.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/cml.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/3d41fe487b1bdb14d58d944bd535db013dad56410d8511afb07f1d9d047b1200--cml.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/eXene.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/4a6877d648c629c646b2b23c0adaaa75b0c39fe1900484ba578384b9018e9170--eXene.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/ml-lpt.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/303b053091e25cbbf7f9b24a3f36d1d55567bd13e1f06c2cd6ccc7337fb37981--ml-lpt.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/ml-lex.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/9da193db4b492d431a916e94ffcc756c3b0c9c161bbffc06dd081385d2b12d68--ml-lex.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/ml-yacc.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/50e4902035b0b726bcf56a010283cbe96bf3aaa33123262cbe4ec82b3dae6496--ml-yacc.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/ml-burg.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/1860129fa9114c360187517882fff1d282cc867780b25002f25bff27cf3fc580--ml-burg.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/pgraph.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/fb69bd2ab24e5e7b36682e316153ae32a372bcf5d0dc06501e77abf0e4213067--pgraph.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/trace-debug-profile.tg
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/019b6506ba2ead42a9db573c43b71106ea33d38b9717e5465aaab2fa45c9343b--trace-debug-profile.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/heap2asm.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/469b66dd9b3a0811af5722fc6be9568f2c02c5bebb04c86327e952f723004874--heap2asm.tgz
==> Downloading https://www.smlnj.org/dist/working/110.84/smlnj-c.tgz
Already downloaded: /Users/vinay/Library/Caches/Homebrew/downloads/5a8efe43da0e3ea77438001560fae7572a6697d40fb104e18cba544848fb5373--smlnj-c.tgz
==> config/install.sh
Last 15 lines from /Users/vinay/Library/Logs/Homebrew/smlnj/01.install.sh:
  "_fopen$DARWIN_EXTSN", referenced from:
      _OpenFile in gen-common.o
  "_fprintf", referenced from:
      _main in gen-sizes-e7ec9c.o
      _OpenFile in gen-common.o
      _CloseFile in gen-common.o
  "_fwrite$UNIX2003", referenced from:
      _main in gen-sizes-e7ec9c.o
      _OpenFile in gen-common.o
      _CloseFile in gen-common.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [gen-sizes] Error 1
make: *** [all] Error 2
config/install.sh: !!! Run-time system build failed for some reason.

READ THIS: https://docs.brew.sh/Troubleshooting

- What you expected to happen

For the install to complete successfully

- Step-by-step reproduction instructions (by running `brew install` commands)

Run 'brew install smlnj'

**Comment by fxcoudert** [comment]
Xcode 10 on macOS 10.13 does not support 32-bit builds anymore. smlnj does not (yet) support 64-bit builds. You can try to use `--force-bottle` to install binaries built on our Sierra machines.
