### ISSUE TITLE
wxPython formula needs to be updated for Python 3

### ISSUE THREAD

**Issue by bittner** [Homebrew/homebrew-core#32744]
The formula for wxPython [depends on Python@2](https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxpython.rb#L16), as for what I understand. This should be updated to Python@3.

Is it possible to provide a package for both Python@2 and Python@3? If yes, could someone point me into the right direction (towards the documentation), so I may be able to prepare a PR?

Comments
------
- _Readers landing here from a search engine_ --> It may be easier to [install wxPython via pip](https://wiki.wxpython.org/How%20to%20install%20wxPython#Installing_wxPython-Phoenix_using_pip), e.g.
```bash
python3 -m pip install wxPython
```

**Comment by xzcvczx** [comment]
i think if wxpython is updated to 4+ there will either need to be @'d to support old versions as a lot of things in homebrew still only support the python2 version or a seperate formula, wxpython4+ is often referred to as wxPython Phoenix on wxpython's website.

**Comment by fxcoudert** [comment]
We are slowly migrating all formulas from Python 2 to Python 3 (where supported). wxpython seems to be difficult, so any help in the form of a pull request is welcome.
