### ISSUE TITLE
Terminator provided by homebrew never shows command prompt

### ISSUE THREAD

**Issue by maxrudolph** [Homebrew/homebrew-core#32760]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**I've attempted to follow your instructions for submitting a bug report.**

- [ X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/800dba7f05c0170255f842affbf142d3
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
N/A

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install a usable copy of Terminator
- What happened (include command output)
When I run terminator, the window opens but there is no command prompt. I can right click in terminator and get the popup menu, and access preferences, but I never see the shell.
- What you expected to happen
I expected to see a shell prompt in terminator
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install terminator
terminator -d

I attach the output from running terminator with debugging:
[log.txt](https://github.com/Homebrew/homebrew-core/files/2452106/log.txt)

**Comment by fxcoudert** [comment]
poke @tschoonj

**Comment by tschoonj** [comment]
This formula hasn't worked properly for years, ever since we moved to gtk+2's `quartz` backend.

It appears they have moved to gtk+3 now, and an [update](https://launchpad.net/terminator/+download) has been available for quite some time.

Feel free to open a PR with the updated formula.

**Comment by maxrudolph** [comment]
@tschoonj I tried to get this to compile but ultimately I think that some additional work will be necessary to make it work with the quartz backend. I think that it might be a good move to remove the Homebrew formula for now since it is known not to work.

**Comment by tschoonj** [comment]
Does this mean that you did get it to compile and run?

If so and it doesn't work properly then it may be indeed best to delete it for now. Feel free to open a PR for that.

**Comment by fxcoudert** [comment]
@maxrudolph libffi is keg-only, so you need `ENV.prepend_path "PKG_CONFIG_PATH", Formula["libff"].opt_lib/"pkgconfig"`
