### ISSUE TITLE
HomeBrew'ed MacVim display is bad - blinks all the time

### ISSUE THREAD

**Issue by balajirama** [Homebrew/homebrew-core#32771]
To reproduce this:
- What you were trying to do (and why)
I was trying to simply start MacVim. I did this because I may want to use it to write text files. Nothing unusual 

- What happened (include command output)
The MacVim window is blinking a lot. See the attached video file (zipped).

[macvim-blink.mov.gz](https://github.com/Homebrew/homebrew-core/files/2453205/macvim-blink.mov.gz)

- What you expected to happen
MacVim should not blink like this and let me work.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install macvim
gvim

**Comment by fxcoudert** [comment]
This was reported in #32440
Unfortunately, this will need to be fixed by Macvim: 
https://github.com/macvim-dev/macvim/issues/751
