### ISSUE TITLE
Build error for qjackctl

### ISSUE THREAD

**Issue by muellermartin** [Homebrew/homebrew-core#3278]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Running `brew install qjackctl` fails for me with basically this error in the configure step:

    configure: error: qmake-qt5 not found in current PATH. Maybe QT development environment isn't available. (qt5-devel)

Full log files as requested in the issue template: https://gist.github.com/muellermartin/cb2815e53d5243022bdf921dd9eb24b3

This issue could be obsoleted by #2260 if there would be a readily available build.

**Comment by muellermartin** [comment]
I was able to fix this error by adding an additional flag to the configure script (`--with-qt5=#{Formula["qt5"].prefix}`) in the formula. Unfortunately this leads to another error during the compilation phase (`qjackctlInterfaceComboBox.cpp:213:21: error: variable length array of non-POD element type 'QString'`) which seems to be an upstream issue. I'll investigate further and if I find a fix, I'll post it here.

**Comment by muellermartin** [comment]
I've now found a way to make it compile. The error including a patch in form of a pull request is submitted upstream as rncbc/qjackctl#17 and rncbc/qjackctl#18. I'll add the missing configure flag and this patch to the formula and submit it as PR here.

**Comment by DomT4** [comment]
Closing in favour of your https://github.com/Homebrew/homebrew-core/pull/3281 PR.
