### ISSUE TITLE
Glances fails to run on Mojave

### ISSUE THREAD

**Issue by RainmakerRaw** [Homebrew/homebrew-core#32809]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? "Error: No logs"
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? https://pastebin.com/ebHKLmbx

To help us debug your issue please explain:
- What you were trying to do (and why)
Tried to install glances (brew install glances). Installs successfully but errors out with traceback when run.
- What happened (include command output)
% glances
Traceback (most recent call last):
  File "/usr/local/Cellar/glances/3.0.2/libexec/bin/glances", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
- What you expected to happen
Glances should have launched in the terminal.
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install glances
glances

**Comment by fxcoudert** [comment]
I cannot reproduce this locally (on Mojave). What is the output of `brew info python@2`? What happens if you open a `python` shell (`/usr/local/opt/python@2/bin/python2`) and run `import pkg_resources`?

**Comment by RainmakerRaw** [comment]
% brew info python@2          
python@2: stable 2.7.15 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@2/2.7.15_1 (4,184 files, 75.8MB) *
  Poured from bottle on 2018-09-05 at 23:51:49
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python@2.rb
==> Dependencies
Build: pkg-config ✔, sphinx-doc ✘
Required: gdbm ✔, openssl ✔, readline ✔, sqlite ✔
Optional: tcl-tk ✘
==> Options
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--HEAD
	Install HEAD version
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 0 (30d), 0 (90d), 0 (365d)
install_on_request: 0 (30d), 0 (90d), 0 (365d)
build_error: 75 (30d)

I issued a reinstall of python@2 (since your post reminded me of some issues with it during the Mojave beta), and now glances works again. Thanks so much for that, and apologies for the extraneous bug report.

**Comment by fxcoudert** [comment]
No problem.
