### ISSUE TITLE
Hunspell

### ISSUE THREAD

**Issue by deronnax** [Homebrew/homebrew-core#32821]
Hello. Pyhunspell co-maintainer here.

We get a HUGE amount of issues on github/pyhunspell because pyhunspell doesn't build on macOS X. This is because there is no `/usr/local/lib/libhunspell.a` provided by the formula. It looks like lib hunspell has the version number in its name and it should not (other libraries do not, like for example gettext: `libgettextpo.a -> ../Cellar/gettext/0.19.8.1/lib/libgettextpo.`)
(whereas libhunspell gives `libhunspell-1.6.a -> ../Cellar/hunspell/1.6.2/lib/libhunspell-1.6.a`

There many pages on the internet giving advices to fix, most of them being doing the linking yourself using a version-less path. For example, see http://pankdm.github.io/hunspell.html

I think that's something the formula should do but it has been forgotten.
Unless I'm wrong, could you do that ?

**Comment by MikeMcQuaid** [comment]
Could you try to submit a pull request to modify the Hunspell formula? That will be easier to discuss. Note if upstream do not provide that symlink then it's on either pyhunspell or hunspell to discuss and change that rather than Homebrew to modify what upstream installs.

**Comment by deronnax** [comment]
I don't have a mac at home and I don't know brew, sorry. I'll try to tell upstream hunspell what you told me

**Comment by fxcoudert** [comment]
Expanding on what @MikeMcQuaid said… Our formula is very simple:

```
    system "autoreconf", "-fiv"
    system "./configure", "--disable-dependency-tracking",
                          "--prefix=#{prefix}",
                          "--with-ui",
                          "--with-readline"
    system "make"
    system "make", "check"
    system "make", "install"
```

So all the magic is done inside the hunspell Makefiles: they deliberately choose to install the static library under a versioned name. See the `Makefile.am` at https://github.com/hunspell/hunspell/blob/master/src/hunspell/Makefile.am

Either `pyhunspell` should better detect the versioned static libraries (or use another mechanism such as `pkg-config`), or `hunspell` needs to install that symbolic link as part of their `make install`.
