### ISSUE TITLE
g++-8 fatal error:/usr/local/bin/gnm returned 1 exit status in macOS10.14 Mojave

### ISSUE THREAD

**Issue by SuperChenSSS** [Homebrew/homebrew-core#32839]
![image](https://user-images.githubusercontent.com/17025439/46656073-c64ed200-cbdf-11e8-8b63-3ba46a7cf5be.png)

**Comment by fxcoudert** [comment]
This is due to a bug in `binutils`: #32516

**Comment by zbeekman** [comment]
@fxcoudert & fellow @homebrew-core maintainers: I just hit this too. Do you know: is brewed gcc supposed to be pulling in brewed binutils? I would have thought that it would be using the xcode shipped tools for linking etc. It seems like a bug that brewed gcc is using binutils, no?
