### ISSUE TITLE
intltool: intltool-update doesn't fully work due to xgettext not in $PATH

### ISSUE THREAD

**Issue by xzcvczx** [Homebrew/homebrew-core#32874]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
while trying to run intltool-update on a po file specified to use xgettext an error is thrown by intltool-update/sh
```
sh: xgettext: command not found
*** GNU xgettext is not found on this system!
*** Without it, intltool-update can not extract strings.
```

this appears to be due to intltool-update(.in):769
```
my $XGETTEXT = $ENV{"XGETTEXT"} || "xgettext";
```

as xgettext is part of the gettext brew formula it is not linked into /usr/local and therefore xgettext is not in $PATH as it is not part of the gettext included in macOS.

as this script seems to be reliant on GNU gettext is it worth making GNU gettext a prereq (or at least recommended) and patching intltool-update to either set an env variable (XGETTEXT) or to replace xgettext with a full path to the brew'd xgettext.

steps to reproduce
```
brew install gettext intltool
intltool-update <po file that has a xgettext specifier>
```

**Comment by MikeMcQuaid** [comment]
Would rather not patch anything that wouldn't be accepted upstream. Adding `gettext` as a dependency seems like the right option 👍

**Comment by xzcvczx** [comment]
adding gettext as a dependency is not enough as its still not in $PATH so will achieve nothing

**Comment by MikeMcQuaid** [comment]
We can set `XGETTEXT`, right? A wrapper script that sets that variable seems like it might be a better fit.

**Comment by xzcvczx** [comment]
can you explain why it would be a better fit please

**Comment by MikeMcQuaid** [comment]
We do not like to have long-running patches that will not be merged upstream.

**Comment by MikeMcQuaid** [comment]
@xzcvczx Why the close?
