### ISSUE TITLE
PHP 7.1.22 ldap crash

### ISSUE THREAD

**Issue by kampfq** [Homebrew/homebrew-core#32913]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
use php-ldap after update to the latest php@7.1 (7.1.22)

- What happened (include command output)
http error_log:
[Thu Oct 11 13:13:33.112041 2018] [core:notice] [pid 49989] AH00052: child pid 28695 exit signal Abort trap (6)
109654 Assertion failed: (LDAP_VALID( ld )), function ldap_set_option, file options.c, line 456.
- What you expected to happen
should not throw an error, php@7.1 7.1.20 works

- Step-by-step reproduction instructions (by running `brew install` commands)

brew update php@7.1
use ldap_set_option()

**Comment by SMillerDev** [comment]
> [ x] if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

Could you fill out the issue template with not just ticking boxes please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by kampfq** [comment]
sorry for that :(

**Comment by SMillerDev** [comment]
Gonna leave this one closed (thanks for the info though) and track this issue on https://github.com/Homebrew/homebrew-core/issues/32916
