### ISSUE TITLE
wcslib - please support fortran (support seems to have been omitted)

### ISSUE THREAD

**Issue by xipmix** [Homebrew/homebrew-core#32912]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ y ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ y ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ y ] ran `brew update` and can still reproduce the problem?
- [ y ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ y ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ y ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 1.7.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c54a657cd5987cba2718f7012a55101324fde8b1
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 70e0139bcbde3e0d43c1e89c15cdb6970d095f80
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GIT: /usr/local/opt/git/bin/git
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.19.1 => /usr/local/opt/git/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 1.7.0_67
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: 8.2
XQuartz: 2.7.11 => /opt/X11

```

To help us debug your issue please explain:
- What you were trying to do (and why)
I want to build wcslib with fortran include files. This was possible in earlier versions.

- What happened (include command output)
```
$ brew reinstall wcslib --with-fortran
==> Reinstalling wcslib 
Warning: wcslib: this formula has no --with-fortran option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/wcslib-5.19.1.el_capitan.bottle.tar.
Already downloaded: /Users/administrator/Library/Caches/Homebrew/downloads/d5bb8e1e112e7bf65b235e9a89c0703e2b405e174a4cbef779d51888a41f282a--wcslib-5.19.1.el_capitan.bottle.tar.gz
==> Pouring wcslib-5.19.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/wcslib/5.19.1: 317 files, 9.6MB
```

- What you expected to happen
It would install the fortran include files alongside the  C ones

- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install wcslib
$ brew reinstall wcslib --with-fortran
```

**Comment by SMillerDev** [comment]
Since wcslib was added there have never been options to enable fortran. As you can see here: https://github.com/Homebrew/homebrew-core/blob/1d7516f0ea71990ab3c50f7daf7e8271bdeff3a5/Formula/wcslib.rb 

You could make your own version in a [tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) where you build the fortran files though.

**Comment by xipmix** [comment]
I was referring to https://github.com/brewsci/homebrew-science/blob/master/Formula/wcslib.rb which existed before the package moved to core. Since you don't seem interested in adding it, I'll make a tap.
