### ISSUE TITLE
LDAP issues with Mojave PHP7.0+

### ISSUE THREAD

**Issue by shujoe** [Homebrew/homebrew-core#32916]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  https://gist.github.com/7b3887ba54a331521857cc27f5e3afef
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I was trying to run the ldap_connect('ldaps:\\something:port') method and received the HTML page:
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

Looking at the error.log for apache I see this:
Assertion failed: (LDAP_VALID( ld )), function ldap_get_option, file options.c, line 114.
[Thu Oct 11 08:53:17.749420 2018] [core:notice] [pid 1331] AH00052: child pid 2051 exit signal Abort trap (6)

This is with PHP 7.0, 7.1, and 7.2 - I have not tried 5.6 since it isn't used by us.

Even running the ldap_connect() with no parameters produces the same error.

I created a regular docker container using the same exact code and it works fine using the latest version of PHP.

**Comment by SMillerDev** [comment]
@kabel you've looked into this before for 7.3 right? Any ideas on what the issue could be?

**Comment by pdelre** [comment]
I believe I'm running into the same issue on High Sierra (10.13.4), only I'm unable to run `php` at all.

```
$ /usr/local/opt/php/bin/php -v
dyld: Library not loaded: /usr/local/opt/openldap/lib/libldap-2.4.2.dylib
  Referenced from: /usr/local/opt/php/bin/php
  Reason: image not found
[1]    87350 abort      php -v
```

However I was able to resolve by installing `libiconv` & `openldap`. Best I can figure https://github.com/Homebrew/homebrew-core/commit/e79a3dad4f1163067fcff3b6c673d161f8de8fdb, added the `if DevelopmentTools.clang_build_version >= 1000` directives for the two libraries which is affecting the installation. I'm an end user, so I don't have any insight on what changes are needed for a PR without possibly causing unknown side effects.

**Comment by shujoe** [comment]
A co-worker has Sierra still and is getting a Segment Fault (the fix for 5.6 doesn't seem to work)  at certain points running the latest PHP 7.2.

He does not require libiconv or openldap - so he doesn't experience the same issue either.

**Comment by kabel** [comment]
This has to be an upstream regression with something exclusive to the httpd libphp7 module in the latest releases. Perhaps another case of the libs loaded by php and httpd not playing nicely together as was the case with snmp. I went back to my previous install: `brew switch php 7.2.10` and ran the following script through a properly configured httpd and it worked as expected.

```php
<?php
var_dump(ldap_connect('localhost'));
```

I get the reproducible [crash](https://gist.github.com/kabel/11fbb03b9c4e5f2a092e120a3070bbdf) when I switch back to 7.2.11. The script runs fine when run from cli on both versions.

**Comment by SteppingHat** [comment]
I'm having the same issue. For all versions of PHP >= 7.0 on macOS Mojave, LDAP does not work. I have both reinstalled and compiled from source PHP 7.2 and receive the following message in my Apache logs when loading a page that relies on LDAP.

    Assertion failed: (LDAP_VALID( ld )), function ldap_unbind_ext, file unbind.c, line 46.
    [Fri Oct 12 13:58:06.122852 2018] [core:notice] [pid 34621] AH00052: child pid 35420 exit signal Abort trap (6)

I can confirm everything was okay before upgrading to Mojave, however once upgrading and running a brew update (which I needed to do to fix some other packages) it was only then that LDAP stopped working.

Upon inspecting phpinfo, the configure command that has built PHP from the bottle includes `'--with-ldap=/usr/local/opt/openldap'` which tells me that we are compiling PHP with an attempt to link in the openldap library into it. What is more interesting is that prior to commit [`e34b54e`](https://github.com/Homebrew/homebrew-core/commit/e79a3dad4f1163067fcff3b6c673d161f8de8fdb), there was no descriptor to define `openldap` and `libiconv` at all - regardless of the check for `clang_build_version`.

I made an attempt to recompile PHP with some of these changes reverted to see if they were the problem however I still received the same issues when conducting the same test.

I believe there isn't an issue with the build from brew, more so an upstream issue along the lines of what @kabel has pointed out - though I haven't been able to explore and find the exact point of failure.

**Comment by SMillerDev** [comment]
Can someone who's actually running into this issue file it at bugs.php.net?

**Comment by SteppingHat** [comment]
[Bug filed @ php.net](https://bugs.php.net/bug.php?id=77005)

**Comment by shujoe** [comment]
Thanks everyone!

I guess I'll use the docker container I created until this is resolved.

**Comment by SteppingHat** [comment]
> Thanks everyone!
> 
> I guess I'll use the docker container I created until this is resolved.

I was in the process of making a docker container leading up to this coincidentally. However I've run into issues with projects with a number of files (Symfony particually) slowing down execution because of OSXFUSE being terribly slow bridging the host and guest file systems together. I'm getting +60s pageload times which isn't stellar. ☹️

**Comment by shujoe** [comment]
I'm in the same boat with a Symfony project.

Also, I tried doing the brew switch and 7.2.10 wouldn't work either.

**Comment by kabel** [comment]
I did more digging into the root cause. What I'm seeing is the system macOS Mojave LDAP libs (LDAP Framework) are no longer binary compatible with openldap. The crash report that I [provided](https://github.com/Homebrew/homebrew-core/issues/32916#issuecomment-429196640) shows that both the system LDAP and openldap libs are loaded into httpd at the time of the crash. It looks like cURL is pulling in the system LDAP.

cURL, both system and homebrew, is a bag of problems in homebrew php right now because it now brings in mixed LDAP and mixed crypto.

I can [patch](https://gist.github.com/kabel/849a065eb44022b2ce375285bec780f2) PHP 7.2 and older to use system LDAP again, **but** PHP 7.3 will require [new symbols](https://bugs.php.net/bug.php?id=76433) that only openldap exposes.

In my opinion, we should make _all_ php versions depend on openldap, as the upstream recommends/supports. However, in doing so we'd have to drop curl or vendor it in as a resource that builds with openssl and openldap. @javian @SMillerDev, any thoughts?

**Comment by phronesis** [comment]
I ran into a similar issue after switching from PHP 7.2 to PHP 7.1. Installing `libiconv` & `openldap` as suggested by @pdelre fixed it for me.

**Comment by charpun** [comment]
`brew install openldap` and `brew reinstall php --build-from-source` seemed to fix this for me.

**Comment by javian** [comment]
`openldap` should already be a requirement to php if clang 10 is installed for all php formulas.

`depends_on "openldap" if DevelopmentTools.clang_build_version >= 1000` 

I'm not sure why that hasn't worked for you.

**Comment by javian** [comment]
@kabel @SMillerDev would you have a gut feeling on the uptake of curl functions in php ? I would imagine removing it would impact a fair amount of users.

**Comment by kabel** [comment]
> would you have a gut feeling on the uptake of curl functions in php ? I would imagine removing it would impact a fair amount of users.

Yes, removing it would likely result in some heavy push-back. curl provides one of the most [commonly](https://packagist.org/packages/ext-curl/dependents) used interfaces for doing HTTP requests (think server-side web services).

**Comment by SteppingHat** [comment]
Are there any workarounds for this? Installing openldap and building php from source doesn't seem to work for me.

**Comment by heiglandreas** [comment]
This is not a bug in the PHP sources as they require OpenLDAP. And when I read [Kevins Comment](https://github.com/Homebrew/homebrew-core/issues/32916#issuecomment-429501813) correctly then Mojave breaks that.

**Comment by shujoe** [comment]
I've not found any workarounds besides using Docker - which is painfully slow.  Is there any ETA to when or how this may be fixed?

I actually have a co-worker have the same problem on High Sierra with the same error now.  I tried re-installing from source on that machine and Mojave and neither worked.

**Comment by kabel** [comment]
Just put in a PR to try and address this. Another work-around would be to configure apache to use php-fpm instead, which is arguably the better SAPI to use as it's compatible with the threaded apache MPMs (the php process is isolated from httpd).
