### ISSUE TITLE
proftpd fails to run as a service, but works if start as root

### ISSUE THREAD

**Issue by lunks** [Homebrew/homebrew-core#32933]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **(No logs)**
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`:

```
HOMEBREW_VERSION: 1.7.7-23-g17154ab
ORIGIN: https://github.com/Homebrew/brew
HEAD: 17154abf466f35f781fc977baf4908f1aaf194f8
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4c56b82e97189248330e9c8136ec8e9da25f0d7f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_181
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
```

`brew doctor`: Some unrelated python headers, can add on request.

To help us debug your issue please explain:
- What you were trying to do (and why):
Run proftpd with `sudo brew services start proftpd`
- What happened (include command output):
Running `sudo brew services start proftpd`, output from `tail -f /var/log/system.log` is:
```
Oct 11 18:33:05 Coltrane proftpd[56621]: 10.0.1.2 - ProFTPD killed (signal 15)
Oct 11 18:33:05 Coltrane proftpd[56621]: 10.0.1.2 - ProFTPD 1.3.6 standalone mode SHUTDOWN
```
- What you expected to happen
For it to run as when I run.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install proftpd`
`sudo brew services proftpd start`
`/var/log/system.log` output should be:
```
10.0.1.2 - ProFTPD 1.3.6 (stable) (built Tue Aug 21 2018 12:24:32 BST) standalone mode STARTUP
```

Doing `sudo -s` to switch to `root` and running `proftpd` works.
`/usr/local/etc/proftpd.conf`: https://gist.github.com/lunks/066097d0a5bfce7af778954d7010247b

**Comment by MikeMcQuaid** [comment]
> Some unrelated python headers, can add on request.

Please always include your `brew doctor` output.

**Comment by lunks** [comment]
`brew doctor` output:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h
```

**Comment by fxcoudert** [comment]
You would need to run proftpd under a debugger (`lldb`) to get a backtrace of the crash. Or get the backtrace from the crash report, stored somewhere in your `~/Library` folder.
