### ISSUE TITLE
Inscape install on Mac OSX El Capitan - download error

### ISSUE THREAD

**Issue by SL06** [Homebrew/homebrew-core#32983]
AnneMini:~ bouillon$ brew install inkscape
==> Installing inkscape from caskformula/caskformula
==> Downloading https://launchpad.net/inkscape/0.92.x/0.92.2/+download/inkscape-0.92.2.tar.bz2
Already downloaded: /Users/bouillon/Library/Caches/Homebrew/downloads/3e16227cc7b60cf452cbbdbe1f45f0c365882d5436c4ca79f9ad6061e184d68a--inkscape-0.92.2.tar.bz2
==> Downloading https://gitlab.com/inkscape/inkscape/commit/93ccf03162cd2e46d962822d5507865f3451168c.diff
Already downloaded: /Users/bouillon/Library/Caches/Homebrew/downloads/369b021412bac03164fd51cdf072f9e402caea5fabf430466d2d9779d6208a36--93ccf03162cd2e46d962822d5507865f3451168c.diff
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 1f037cc29cee8e0c60ab4753d4151741c8170e4849129bac68fdc60925eb971d
Actual: 7ce4f70f1cb03cd0bab7dc94821a89bf71600bd59c763ae0d78c48f33db3d9ac
Archive: /Users/bouillon/Library/Caches/Homebrew/downloads/369b021412bac03164fd51cdf072f9e402caea5fabf430466d2d9779d6208a36--93ccf03162cd2e46d962822d5507865f3451168c.diff
To retry an incomplete download, remove the file above.

**Comment by fxcoudert** [comment]
@SL06 you need to report this issue here: https://github.com/caskformula/homebrew-caskformula/issues
