### ISSUE TITLE
Plist file for OfflineImap has the path in the wrong order.

### ISSUE THREAD

**Issue by MassimoLauria** [Homebrew/homebrew-core#3298]
The plist installed by the 
`brew services start offlineimap` specifies the following value for the PATH variable:

`/usr/bin:/bin:/usr/sbin:/sbin:#{HOMEBREW_PREFIX}/bin`

while it should be 

`#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin`

This is important for offlineimap because it uses python to run, and it make sense that 
it uses the homebrew python (if available) instead of the default Apple one. This is even more important if offlineimap configuration uses a python file. One example is to use python code to store and retrieve passwords from the OSX keyring.

**Comment by MikeMcQuaid** [comment]
> This is important for offlineimap because it uses python to run, and it make sense that 
> it uses the homebrew python (if available) instead of the default Apple one. This is even more important if offlineimap configuration uses a python file. One example is to use python code to store and retrieve passwords from the OSX keyring.

Incorrect. Offline IMAP is configured to always use the system Python so this is desirable and intentional.

**Comment by MassimoLauria** [comment]
But then if the python script in the configuration requires some packages to be installed, these must be installed in the system site-package (or in the user one).
