### ISSUE TITLE
lsh failed to build on 10.14

### ISSUE THREAD

**Issue by gwjo** [Homebrew/homebrew-core#32991]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

gist-logs: https://gist.github.com/8df3e8359f1d2125c85e6bdd96314d17

To help us debug your issue please explain:
- What you were trying to do (and why)
Install lsh, via the `brew install lsh` command
- What happened (include command output)
https://gist.github.com/gwjo/3fad426de4f5d5ef54b74c4d3f56b30f
- What you expected to happen
Successful install of lsh
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install lsh`

**Comment by fxcoudert** [comment]
lsh is unmaintained, this will be fixed by removing the formula from Homebrew core: #33027
