### ISSUE TITLE
Wine not detecting CUPS printers

### ISSUE THREAD

**Issue by adunning** [Homebrew/homebrew-core#32997]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

- What you were trying to do (and why)

Print from Wine applications.

- What happened (include command output)

No printers appear; when printing, I receive the message `fixme:winspool:WINSPOOL_EnumPrintersW We don't handle PRINTER_ENUM_CONNECTIONS`.

- What you expected to happen

All CUPS printers appear automatically, as when using wine-stable from Cask.

- Step-by-step reproduction instructions (by running `brew install` commands)

1. Install Wine via `brew install wine`.
2. Run Notepad with `wine notepad`.
3. Go to File > Print.

I have reproduced this on two computers that did not previously have any version of Wine installed.

A [similar report](https://forum.winehq.org/viewtopic.php?f=8&t=22250) from a Linux distribution might suggest that it has something to do with 32-bit and 64-bit CUPS. But the really strange thing is that after installing and uninstalling Wine Stable and running it on the prefix, the printers are detected, which might imply there's some configuration step that we're missing.

**Comment by fxcoudert** [comment]
We've just updated wine to 3.0.3, is the issue still there?

**Comment by adunning** [comment]
Yes, sorry!

**Comment by fxcoudert** [comment]
What do you mean by this

> after installing and uninstalling Wine Stable and running it on the prefix

**Comment by adunning** [comment]
I meant installing Wine via `brew cask install wine-stable`, then running the Wine Stable app on the prefix previously installed with Homebrew Wine.

**Comment by adunning** [comment]
Not sure if anything can be done about this – I haven't yet found the source of the problem.

**Comment by adunning** [comment]
I really can't see this getting fixed. Given how much trouble this formula causes, should we think about making it cask-only?

**Comment by fxcoudert** [comment]
It's a possibility we may have to consider, especially now that it doesn't build from source on Mojave and High Sierra…

**Comment by adunning** [comment]
Would that be best considered as a pull request or on Discourse?

**Comment by fxcoudert** [comment]
We would welcome combined pull requests, one here and one on Cask!

**Comment by adunning** [comment]
I did some work on the Cask version in <https://github.com/Homebrew/homebrew-cask/pull/56280>, which brought to light that this is a bug in Wine not specific to the Homebrew build. I also realized that the Homebrew formula has the advantage of allowing one to run Wine without X11, so I think I'll leave it for now.
