### ISSUE TITLE
wine does not install on Mojave (10.14)

### ISSUE THREAD

**Issue by apenngrace** [Homebrew/homebrew-core#33114]
When trying to install wine with `brew install wine`, it exits on error:

```
==> Downloading https://dl.winehq.org/wine/source/3.0/wine-3.0.3.tar.xz
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/360aac6f680e0ea1cf4c6018a69b9accff0f73afd5e9bbf419c0f816957ae655--wine-3.0.3.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/74c2566/wine/2.14.patch
Already downloaded: /Users/andrew/Library/Caches/Homebrew/downloads/d06acb9dce25009cf81be12fbb50a415406c5fd03a8a43d719fe8f9ba43321b5--2.14.patch
==> Patching
==> Applying 2.14.patch
patching file dlls/wined3d/context.c
Hunk #1 succeeded at 1600 (offset 169 lines).
Hunk #2 succeeded at 1629 (offset 169 lines).
Hunk #3 succeeded at 1652 (offset 169 lines).
Hunk #4 succeeded at 1680 (offset 169 lines).
Hunk #5 succeeded at 1981 (offset 196 lines).
Error: Wine cannot currently be installed from source on
macOS 10.14.
You may wish to try:
  brew install wine --force-bottle
Error: An exception occurred within a child process:
  SystemExit: exit
```
Here is the gist from `brew gist-logs wine`: https://gist.github.com/7416d13092ee287bc2c0b10d4dffeb53

- output of brew config is in the gist (above)
- output of brew doctor: `Your system is ready to brew.`

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by fxcoudert** [comment]
Wine does not build from source on Mojave (or High Sierra) since Apple deprecated 32-bit builds. The wine team has not yet updated the software to compile on those platforms.

Please use `brew install wine --force-bottle` to install the prebuilt binaries, which are built on Sierra but work on High Sierra and Mojave.
