### ISSUE TITLE
csshx not working on Mac OS 10.14 Mojave

### ISSUE THREAD

**Issue by chrispassas** [Homebrew/homebrew-core#33133]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

`Trying to run 'csshx myserver.com myserver2.com'`

- What happened (include command output)
Getting error output

> **** ERROR **** PerlObjCBridge:: sendObjcMessage: Can't get NSMethodSignature for message "qualifiedSpecifier"
> **** ERROR **** PerlObjCBridge: error [1] sending message [NSObject qualifiedSpecifier] at /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level/PerlObjCBridge.pm line 248.
> - What you expected to happen

Expected csshx to open multiple ssh windows normally.

> - Step-by-step reproduction instructions (by running `brew install` commands)

1. brew install csshx
2. csshx server1.com server2.com

brew gist-logs csshx
https://gist.github.com/c08dc9cea30a0fb83d5d9fe99f921a68

**Comment by chrispassas** [comment]
Found others had this issue with OS X 10.14 beta. There solution was to use an older version. Just mentioning in case it helps.

https://github.com/brockgr/csshx/issues/94

**Comment by fxcoudert** [comment]
Apparently there is even a fix, although it has not been merged yet: https://github.com/brockgr/csshx/pull/97

Thanks for reporting, others might find it useful. I will close this issue, but it can serve as documentation for other users.
