### ISSUE TITLE
zenity [and others] failed to build on 10.11 - pcre error

### ISSUE THREAD

**Issue by Tilogorn** [Homebrew/homebrew-core#3316]
I can't update several formulas due to the same error in configure scripts:

```
checking for PCRE... yes
checking for Unicode support in PCRE... no
configure: error: *** The system-supplied PCRE does not support Unicode properties or UTF-8.
```

Concerned are in my case:

- atk
- gdk-pixbuf
- glib
- gobject-introspection
- gsettings-desktop-schemas
- gtk+3
- harfbuzz
- libgsf
- pango
- zenity

I removed and reinstalled the brew pcre formula (although it says `system-supplied`, just a try). After that, PCRE (the brew version in the path) gives the following output:

```
$ which pcretest
/usr/local/bin/pcretest

$ ls -la /usr/local/bin/ | grep pcretest
[...]  pcretest -> ../Cellar/pcre/8.39/bin/pcretest

$ pcretest -C
PCRE version 8.39 2016-06-14
Compiled with
  8-bit support
  UTF-8 support
  16-bit support
  UTF-16 support
  32-bit support
  UTF-32 support
  Unicode properties support
  Just-in-time compiler support: x86 64bit (little endian + unaligned)
  Newline sequence is LF
  \R matches all Unicode newlines
  Internal link size = 2
  POSIX malloc threshold = 10
  Parentheses nest limit = 250
  Default match limit = 10000000
  Default recursion depth limit = 10000000
  Match recursion uses stack
```

which seems correctly. My guess is, that the configure script searches for pcre in an absolute path, finding a native shipped version with Mac OS X which does not support UTF-8 support (although I can't find one!). 

More debug information:

```
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1455aa3da6335b1eeb284e61171cff524c620fa3
Last commit: 35 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0c8b36de6eccaa072c4c1699311c524fe615c540
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_40, 1.6.0_65-b14-468
OS X: 10.11.5-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

`brew doctor` has no warnings leading in this direction

**Comment by ilovezfs** [comment]
Can you please try this in a new dummy user account and see if it still occurs?

**Comment by Tilogorn** [comment]
Just created a fresh OS X User and can confirm the same behavior.

**But I could resolve the issue:**

I discovered something else. I could observe that every time the listed formulas failed it was the configure script of their dependency `glib`. As  `glib` itself is listed as `outdated` in my case, I updated that formula manually with `brew upgrade glib` first. Result:

- `glib` as a dependency of zenity, atk, ... could not be automatically upgraded, because of pcre error

```
==> Installing dependencies for zenity: glib, gobject-introspection, gdk-
==> Installing zenity dependency: glib
==> ./configure --disable-maintainer-mode --disable-silent-rules --disable-dtrac
configure: error: *** The system-supplied PCRE does not support Unicode properties or UTF-8.
```

- `glib` as a formula itself **could be updated** because it first built a (new?) version of `pcre``

```
$ brew upgrade glib
==> Upgrading 1 outdated package, with result:
glib 2.48.1
==> Upgrading glib
==> Installing dependencies for glib: pcre
==> Installing glib dependency: pcre
==> make
==> make test
==> make install

==> Installing glib
==> make
==> make install
```

So it seems, that the build-process is another one when `glib` is a dependency of `brew upgrade [anotherpackage]` and when it's the formula itself which is upgraded.

After `glib` and `pcre` were upgraded, I could upgrade everything else.

**Comment by ilovezfs** [comment]
Why is it building everything from source?

**Comment by Tilogorn** [comment]
Can't tell you. I'm just executing a standard brew with standard commands on a (pretty) standard OS X.
Is there a global "build-from-source"-option, that may have been triggered through what-ever?

**Comment by ilovezfs** [comment]
You'd have to have exported
```
export HOMEBREW_BUILD_FROM_SOURCE=1
```
in your profile.

But I'm wondering if it's building everything `--universal` for some reason.

**Comment by Tilogorn** [comment]
It's definitely not exported - at least not in my own initiated terminal sessions, including my .bash_profile

```
$ export -p | grep BREW
declare -x HOMEBREW_GITHUB_API_TOKEN="xxx"
```

If I can test sth. for you regarding the `--universal`-option, let me know

**Comment by ilovezfs** [comment]
The INSTALL_RECEIPT.json for each of the formulae would be helpful. Also, if you can still trigger the error, `brew gist-logs fooformula` may help as well.

**Comment by Tilogorn** [comment]
I think some of the packages did just not disappear from `outdatet` because the whole `upgrade`-process was interrupted.
As `glib` is now updated, I can't trigger the error anymore. 

Here are some INSTALL_RECEIPT.json of the surely affected packages:

zenity:
```
{
  "used_options": [],
  "unused_options": [
    "--with-webkitgtk"
  ],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "time": 1469793162,
  "source_modified_time": 1458755990,
  "HEAD": null,
  "stdlib": null,
  "compiler": "clang",
  "source": {
    "path": "/usr/local/Library/Taps/homebrew/homebrew-core/Formula/zenity.rb",
    "tap": "homebrew/core",
    "spec": "stable"
  }
}
```

pango:
```
{
  "used_options": [],
  "unused_options": [
    "--universal"
  ],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "time": 1469793136,
  "source_modified_time": 1460388612,
  "HEAD": null,
  "stdlib": null,
  "compiler": "clang",
  "source": {
    "path": "/usr/local/Library/Taps/homebrew/homebrew-core/Formula/pango.rb",
    "tap": "homebrew/core",
    "spec": "stable"
  }
}
```

atk:
```
{
  "used_options": [],
  "unused_options": [
    "--universal"
  ],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "time": 1469793132,
  "source_modified_time": 1458549830,
  "HEAD": null,
  "stdlib": null,
  "compiler": "clang",
  "source": {
    "path": "/usr/local/Library/Taps/homebrew/homebrew-core/Formula/atk.rb",
    "tap": "homebrew/core",
    "spec": "stable"
  }
}

```

glib - probably not affected (see note at beginning of this post) - but the "problem solver":
```
{
  "used_options": [
    "--universal"
  ],
  "unused_options": [
    "--with-test"
  ],
  "built_as_bottle": false,
  "poured_from_bottle": false,
  "time": 1469792709,
  "source_modified_time": 1462871856,
  "HEAD": "3469f177f043b163e0c362b0fa10f9f99c31114b",
  "stdlib": null,
  "compiler": "clang",
  "source": {
    "path": "/usr/local/Library/Taps/homebrew/homebrew-core/Formula/glib.rb",
    "tap": "homebrew/core",
    "spec": "stable"
  }
}
```

**Comment by DomT4** [comment]
> I removed and reinstalled the brew pcre formula (although it says system-supplied, just a try).

Potentially worth noting that the build script here, when it says `system-supplied`, means nothing more than _"This exists on the system"_. It's not making a determination as to why it appears on the system or where it originated from.

**Comment by ilovezfs** [comment]
@DomT4 the glib install receipt does indeed have "--universal" ... I wonder how that got in there originally.

**Comment by DomT4** [comment]
Closing as this seems to have gone dead, but please do ping if we can help further. Thanks!
