### ISSUE TITLE
terraform

### ISSUE THREAD

**Issue by navreddy36** [Homebrew/homebrew-core#33184]
There are some problems with the CLI configuration:

Error: Error parsing /Users/naveen/.terraformrc: At 1:1: illegal char

As a result of the above problems, Terraform may not behave as intended.

Terraform v0.11.8

Your version of Terraform is out of date! The latest version
is 0.11.9. You can update by downloading from www.terraform.io/downloads.html

**Comment by fxcoudert** [comment]
Please fill the full issue template so we can help you.
