### ISSUE TITLE
PyRoot appears broken in Root (MacOS 10.14)

### ISSUE THREAD

**Issue by rasmack** [Homebrew/homebrew-core#33195]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
No logs
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
https://pastebin.com/nKY0T12K
The clhep-stuff is because I installed that myself earlier.

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried using PyRoot and got a segmentation violation

- What happened (include command output)
A minimal session importing something from ROOT is found here:
https://pastebin.com/VN0geBxq

As far as I can tell, the python version used is correct:

```
PN-BG-MACRM:C++ RM$ ls -alh `which python`
lrwxr-xr-x  1 RM  admin    38B 12 Okt 12:05 /usr/local/bin/python -> ../Cellar/python@2/2.7.15_1/bin/python
```
- What you expected to happen
I just expected python to load the module.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install root
python
from ROOT import gROOT

Side note: I have zero idea whether this is a Root issue, a python issue or a Homebrew issue, but I'm starting here, as the python in question is supplied by Homebrew (Root dependency).

**Comment by rasmack** [comment]
I guess I should say, then, that the issue persists.

**Comment by corrodis** [comment]
If I understand that right, `brew install root` has a dependency on python which refers to python3. If you install root, python3 is also installed hence pyRoot for python3 is built. Try using python3. 
If you run `brew info root` you'll see that there is supposed to be a `--with-python@2` option. Unfortunately, this option seems to be broken.

**Comment by rasmack** [comment]
Sorry. I should probably have responded here. Indeed it was a not-so-easy-to-spot dependency on Python3. Installing from source as suggested fixes the problem. Thanks.
