### ISSUE TITLE
rust downloads and executes files not part of resources

### ISSUE THREAD

**Issue by Midar** [Homebrew/homebrew-core#33214]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Build rust

- What happened (include command output)
```
brew -v install rust
[…]
downloading https://static.rust-lang.org/dist/2018-08-02/rust-std-1.28.0-x86_64-apple-darwin.tar.gz
######################################################################## 100.0%
extracting /private/tmp/rust-20181020-47984-u7moxr/rustc-1.29.2-src/build/cache/2018-08-02/rust-std-1.28.0-x86_64-apple-darwin.tar.gz
downloading https://static.rust-lang.org/dist/2018-08-02/rustc-1.28.0-x86_64-apple-darwin.tar.gz
######################################################################## 100.0%
extracting /private/tmp/rust-20181020-47984-u7moxr/rustc-1.29.2-src/build/cache/2018-08-02/rustc-1.28.0-x86_64-apple-darwin.tar.gz
downloading https://static.rust-lang.org/dist/2018-08-02/cargo-0.29.0-x86_64-apple-darwin.tar.gz
######################################################################## 100.0%
extracting /private/tmp/rust-20181020-47984-u7moxr/rustc-1.29.2-src/build/cache/2018-08-02/cargo-0.29.0-x86_64-apple-darwin.tar.gz
```

- What you expected to happen
These files should have been resource and not downloaded and executed without verification.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew -v install rust

**Comment by Midar** [comment]
Ah, there was not the usual text about verification, and since it's not a resource included with a hash, I just assumed it wasn't verified. If it is, that makes things better. But I guess the question remains why download them during make rather than having them as a resource?

**Comment by MikeMcQuaid** [comment]
Not all files are downloaded with resources. This is intentional. If you've checked the code and shown they aren't being verified with a checksum and/or using HTTPS then let us know and we can look at a workaround.
