### ISSUE TITLE
grace exiting with SIGSYS

### ISSUE THREAD

**Issue by john139** [Homebrew/homebrew-core#3322]
### Bug reports:

Hello,
I used xmgrace which I successfully installed with homebrew (OS X 10.11.4), unfortunately I had to reinstall grace (with brew update and brew upgrade) and now I can't run it because the following error appears:

~$ xmgrace 
Warning: locale not supported by Xlib, locale set to C
Warning: Widget must be a VendorShell.
Warning: translation table syntax error: Unknown event type :   EnterWindow
Warning: ... found while parsing '<EnterWindow>:			ManagerEnter()'
Warning: String to TranslationTable conversion encountered errors

Oops! Got SIGSYS

Please use "Help/Comments" to report the bug.
Abort trap: 6

I have searched on the Internet, but the only place where this issue was discussed was here
https://github.com/Homebrew/legacy-homebrew/issues/27840#event-105239860, it was an optimisation problem. Could you please tell me if it is the same problem now or something else?

**Comment by mistydemeo** [comment]
This issue was moved to Homebrew/homebrew-x11#221
