### ISSUE TITLE
Hombrew Cleanup Crash

### ISSUE THREAD

**Issue by nixneus** [Homebrew/homebrew-core#33220]
Dear all,

When I execute brew cleanup I obtain the following. Could someone tell me what is the issue?
I am using MACOSX (Sierra 10.12.6).

Thank you in advance,

Neus

me@where:~$ brew cleanup
Error: unknown version :x86_64_linux
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:23:in `block in from_symbol'
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `fetch'
/usr/local/Homebrew/Library/Homebrew/os/mac/version.rb:22:in `from_symbol'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:60:in `block in find_older_compatible_tag'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:53:in `find_older_compatible_tag'
/usr/local/Homebrew/Library/Homebrew/extend/os/mac/utils/bottles.rb:31:in `find_matching_tag'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:94:in `fetch_checksum_for'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:381:in `checksum_for'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:368:in `tag?'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:96:in `bottled?'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/forwardable.rb:202:in `bottled?'
/usr/local/Homebrew/Library/Homebrew/formula.rb:343:in `bottle'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:20:in `file_outdated?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:106:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:60:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:264:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:250:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:250:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:192:in `cleanup_formula'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:156:in `block in clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:155:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:155:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:30:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

**Comment by fxcoudert** [comment]
Please fill the issue template, including full output of `brew config` and `brew doctor`. Otherwise we really can't do much to help.
