### ISSUE TITLE
watchman: watchman-wait fails, probably due to python2/python3 mishap

### ISSUE THREAD

**Issue by tomjakubowski** [Homebrew/homebrew-core#33227]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?  - I did not fix all problems, none seemed particularly relevant.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? here you are: https://gist.github.com/tomjakubowski/78428c47f5dd75d394c085748c2997ef
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I installed the `watchman` package. `watchman` ships with a Python application called `watchman-wait`. 

When I run `watchman-wait .`, I see this error:

```
% watchman-wait .
Traceback (most recent call last):
  File "/usr/local/Cellar/watchman/4.9.0_1/libexec/bin/watchman-wait", line 185, in <module>
    for _, sub in subscriptions.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

This error strongly suggests some kind of issue around python2/python3, because py3k removed `dict.iteritems()`. The formula lists a dependency on the "python" package, which is python 3, but this script appears to be only compatible with python2.

Oddly enough, the shebang in the script refers to `/usr/local/opt/python/bin/python3.7`.

```
#!/usr/local/opt/python/bin/python3.7
from __future__ import print_function
import pywatchman
import argparse
import os
import sys
import time


def fieldlist(s):
    # helper for splitting a list of fields by comma
    return s.split(',')

parser = argparse.ArgumentParser(
    formatter_class=argparse.RawDescriptionHelpFormatter,
    description="""
watchman-wait waits for changes to files.  It uses the watchman service to
efficiently and recursively watch your specified list of paths.
```

**Comment by tomjakubowski** [comment]
I can't reproduce with `brew install --HEAD` as of today. Apparently upstream made everything compatible with python2 and python3 since their latest official release 4.7.0: https://facebook.github.io/watchman/docs/release-notes.html#watchman-480-never-formally-released

**Comment by fxcoudert** [comment]
watchman is officially compatible with Python 2 & 3: https://github.com/facebook/watchman/blob/master/python/setup.py
But apparently there was a bug, indeed.

We would welcome a pull request to add a `patch do` block with patch URL `https://github.com/facebook/watchman/commit/17958f7d.diff?full_index=1`

**Comment by tomjakubowski** [comment]
hooray! :tada: thank you, everyone!
