### ISSUE TITLE
Can no longer install cspice

### ISSUE THREAD

**Issue by blogabe** [Homebrew/homebrew-core#33290]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/df8541a239fade87abd71c030f8edf65

To help us debug your issue please explain:
- What you were trying to do (and why)
Install cspice but the `csh makeall.csh` command isn't executing properly.  I tried installing w/ debug mode and noticed the archive is still archived, but unsure if that's default behavior.

- What happened (include command output)
```
$ brew install cspice
==> Downloading https://naif.jpl.nasa.gov/pub/naif/toolkit/C/MacIntel_OSX_AppleC
######################################################################## 100.0%
==> csh makeall.csh
Last 15 lines from /Users/blogabe/Library/Logs/Homebrew/cspice/01.csh:
2018-10-22 21:03:30 -0700

csh
makeall.csh

makeall.csh: No such file or directory.

READ THIS: https://docs.brew.sh/Troubleshooting
```

- What you expected to happen
Successful installation

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install cspice`

**Comment by fxcoudert** [comment]
```
  url "https://naif.jpl.nasa.gov/pub/naif/toolkit/C/MacIntel_OSX_AppleC_64bit/packages/cspice.tar.Z"
  mirror "https://dl.bintray.com/homebrew/mirror/cspice-66.tar.Z"
```

yet `brew` does not detect it as an archive that it can uncompress.

/move brew
