### ISSUE TITLE
Upgrading numpy with `--HEAD` fails if `pythran` is installed

### ISSUE THREAD

**Issue by fish2000** [Homebrew/homebrew-core#33303]
The log of the failure is here: https://gist.github.com/fish2000/6bcbbc2dcaae5535f29785006774d887

… one can work around the issue by `pip`-uninstalling `pythran`, upgrading numpy via `brew upgrade` or `brew reinstall (…)`, and then `pip`-reinstalling `pythran` afterwards. 

For the curious and/or Pythonically inclined, it seems to be a Cython upstream bug, wherein Cython (which is an integral component of numpy’s build system) tries to use a numpy feature before it exists – q.v. gist link _supra_ in which a Cython component references the module member `numpy.generic` – but only in a branch of code whose execution is triggered by the presence of `pythran`… I’ll report it upstream too.

----------------
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?… sorta (see above)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by fxcoudert** [comment]
Hi @fish2000, thanks for the report. I think it is such a corner case (if it requires `HEAD` and `pip install phytran` to occur) that we're not likely to work around it…

**Comment by MikeMcQuaid** [comment]
Closing as an upstream issue. Thanks for filing there!
