### ISSUE TITLE
SQLite fails to upgrade

### ISSUE THREAD

**Issue by Minoru** [Homebrew/homebrew-core#33309]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh

    > At least two other people ran into the same issue as I did, see https://github.com/travis-ci/travis-ci/issues/10275.

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?

    > I run it at the beginning of each Travis job, and I've had multiple Travis jobs since this issue popped up.
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

    > I don't have Apple hardware, and debugging on CI is no fun. Pardon, but I think it's easier for someone to try and reproduce this locally.
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.7.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: c54a657cd5987cba2718f7012a55101324fde8b1
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9f42578d816cccdf4db3b52af7a34e615098dea3
Core tap last commit: 51 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.1 build 902
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1
macOS: 10.13.3-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.4.1 => /Applications/Xcode-9.4.1.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.0 (or delete it).
Xcode can be updated from the App Store.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

    > I'm trying to upgrade SQLite on Travis so I can build my application.
- What happened (include command output)

    > `brew update` finished fine. `brew outdated "sqlite" || brew upgrade "sqlite"` seem to upgrade SQLite but return an error that fails the Travis build.
    >
    > The output is rather large, please see it here: https://travis-ci.org/newsboat/newsboat/jobs/444297923#L1567
- What you expected to happen

    > I expected `brew outdated "sqlite" || brew upgrade "sqlite"` to upgrade SQLite and exit with a "success" error code. It did exactly that [just a few days ago](https://travis-ci.org/newsboat/newsboat/jobs/444138864#L1550).
    >
    > Apparently, SQLite formula haven't been updated since then, so I have no idea where the failure is coming from. Travis folk [say they didn't deploy anything over the weekend](https://github.com/travis-ci/travis-ci/issues/10275#issuecomment-431719772).
- Step-by-step reproduction instructions (by running `brew install` commands)

    ```
    brew update
    brew outdated "sqlite" || brew upgrade "sqlite"
    ```

**Comment by MikeMcQuaid** [comment]
I don't see any failures in the Travis CI output. Please reproduce this outside of Travis CI. Additionally note we don't support Xcode 9.4 any longer.

**Comment by BanzaiMan** [comment]
There is a [failed `brew link`](https://travis-ci.org/newsboat/newsboat/jobs/444297923#L1698) that appears to have caused the nonzero exit status.
