### ISSUE TITLE
libsecret assumes gsed; fails if `brew install gnu-sed --with-default-names`

### ISSUE THREAD

**Issue by andreasabel** [Homebrew/homebrew-core#33316]
Issue is: `libsecret.rb` assumes `gsed`; fails if `brew install gnu-sed --with-default-names`

Suspect code:
https://github.com/Homebrew/homebrew-core/blob/bdba8323cc938ddf71e9735c8a6fde2cb2bae905/Formula/libsecret.rb#L38-L41

Comment:
Despite all the serious threats of persecution and death uttered by `brew install` and the issue template, I am reporting this problem which has surfaced in similar situations.  See 

  https://github.com/petere/homebrew-postgresql/issues/29

for another instance of this problem.

If installing `gnu-sed` with
```
brew install gnu-sed --with-default-names
```
then the system does not know the command `gsed`.  Consequently, we get errors like the following:
```
brew install libsecret

==> Downloading https://download.gnome.org/sources/libsecret/0.18/libsecret-0.18.6.tar.xz
==> Downloading from https://ftp.acc.umu.se/pub/GNOME/sources/libsecret/0.18/libsecret-0.18.6.tar.xz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libsecret/0.18.6_1 --enable-introspec
==> make install
Last 15 lines from /Users/abel/Library/Logs/Homebrew/libsecret/02.make:
install

gdbus-codegen --interface-prefix org.freedesktop.Secret. \
		--generate-c-code temp-dbus-generated --c-namespace SecretGen libsecret/org.freedesktop.Secrets.xml
gsed -e $'1i\\\n#define GLIB_DISABLE_DEPRECATION_WARNINGS' \
		-e 's/secret_gen_/_secret_gen_/g' -e 's/type-/type/g' \
		-e 's/temp-dbus-generated.h/secret-dbus-generated.h/g' \
		temp-dbus-generated.c > secret-dbus-generated.c
gsed -e 's/secret_gen_/_secret_gen_/g' -e 's/type-/type/g' \
		temp-dbus-generated.h > secret-dbus-generated.h
/bin/sh: gsed: command not found
/bin/sh: gsed: command not found
make: *** [secret-dbus-generated.c] Error 127
make: *** Waiting for unfinished jobs....
make: *** [secret-dbus-generated.h] Error 127

Do not report this issue to Homebrew/brew or Homebrew/core!


Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures and other breakages.
Please create pull-requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this old version,
you are responsible for resolving any issues you experience.
```
I included all the threats of `brew install` uttered to me as issue reporter for your amusement. They are unrelated to the problem at hand which is the simple failure
```
/bin/sh: gsed: command not found
```

The issue can be worked around in the known manner by installing GNU sed as `gsed` (no option `--with-default-names`):
```
brew uninstall gnu-sed
brew install gnu-sed
brew install libsecret
```

Cheers to the brewers!

**Comment by MikeMcQuaid** [comment]
> brew install gnu-sed --with-default-names

@fxcoudert Suggestion: remove that option?

@andreasabel Thanks! Please always fill out the issue template in future.

**Comment by fxcoudert** [comment]
@MikeMcQuaid  I'm thinking we need to have a consistent policy for `--with-default-names` option. I'd rather remove them all, and add a systematic `gnubin` directory for people who want to use those. But I don't have time to deal with it just now.

**Comment by MikeMcQuaid** [comment]
@fxcoudert That makes sense to me (but I wonder if the `gnubin` directory added to the PATH will create similar problems).

If you don't have time for now: maybe open a help wanted issue with a suggested approach?
