### ISSUE TITLE
FLTK should be upgraded to r13078 to support Mojave

### ISSUE THREAD

**Issue by llyang** [Homebrew/homebrew-core#33342]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  - Install and use FLTK for GUI programming
- What happened (include command output)
  - Installed version (1.3.4-2) does not work on Mojave (as reported in http://www.fltk.org/str.php?L3496)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
  - brew install fltk
  - Write a simple FLTK program and compile
  - The resulting executable shows a blank window

**Comment by fxcoudert** [comment]
We ship stable, released versions. We will not update to a specific revision that upstream does not deem stable enough to be a release.

**Comment by llyang** [comment]
> We ship stable, released versions. We will not update to a specific revision that upstream does not deem stable enough to be a release.

This doesn't make sense if the "stable" version is unusable.

Is it possible to add a new formula for the development version? It is known that FLTK doesn't release very often, which means that the homebrew version might be unusable on Mojave (or a newer version of macOS) for a long time.

**Comment by maxieds** [comment]
@llyang and for anyone who is still searching for a better solution to this problem see the build instructions for the FLTK 1.4.x tap [here](https://github.com/gtDMMB/homebrew-core). **FYI:** my related *with-cairo* [pull request](https://github.com/Homebrew/homebrew-core/pull/33358) was also turned down because even though Mojave will not run with FLTK 1.3.x, 1.4.x is still considered too bleeding edge to be included as a stock brew formula...

**Comment by llyang** [comment]
@maxieds Thanks!

**Comment by fxcoudert** [comment]
@llyang if the bug was fixed by fltk, we definitely would consider a patch to the stable version

**Comment by MikeMcQuaid** [comment]
> This doesn't make sense if the "stable" version is unusable.

Suggestion: that's feedback to provide to FLTK rather than us.

**Comment by llyang** [comment]
> > This doesn't make sense if the "stable" version is unusable.
> 
> Suggestion: that's feedback to provide to FLTK rather than us.

Thanks. I've submitted a request to FLTK whether it's possible to backport the Mojave support to the stable version.
