### ISSUE TITLE
httpd 2.4.37 mojave bottle missing mod_deflate.so

### ISSUE THREAD

**Issue by fluff** [Homebrew/homebrew-core#33368]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

---

The bottle for httpd 2.4.37 on mojave appears to be missing `mod_deflate.so`. It is present in the httpd 2.4.35 mojave bottle, as well as the 2.4.37 high_sierra bottle:

```
% curl --silent -L https://homebrew.bintray.com/bottles/httpd-2.4.37.high_sierra.bottle.tar.gz|tar tvzf -|grep mod_deflate.so
-r--r--r--  0 brew   staff   33240 Oct 18 16:34 httpd/2.4.37/lib/httpd/modules/mod_deflate.so

% curl --silent -L https://homebrew.bintray.com/bottles/httpd-2.4.35.mojave.bottle.tar.gz|tar tvzf -|grep mod_deflate.so
-r--r--r--  0 brew   staff   33240 Sep 18 02:54 httpd/2.4.35/lib/httpd/modules/mod_deflate.so

% curl --silent -L https://homebrew.bintray.com/bottles/httpd-2.4.37.mojave.bottle.tar.gz|tar tvzf -|grep mod_deflate.so
### (note: no lines output and no mod_deflate.so here)
```

This causes a brew upgrade to fail to start (or even stop) apache after upgrading from 2.4.35 to 2.4.37 with: 
```
httpd: Syntax error on line 110 of /usr/local/etc/httpd/httpd.conf: Cannot load lib/httpd/modules/mod_deflate.so into server: dlopen(/usr/local/opt/httpd/lib/httpd/modules/mod_deflate.so, 10): image not found
```
unless of course mod_deflate is removed from the configuration, but missing mod_deflate support seems like a regression.

**Comment by fxcoudert** [comment]
Probably a problem with zlib detection.

**Comment by fxcoudert** [comment]
Can someone post a link to the output of `brew gist-logs httpd` after running `brew reinstall -s --verbose httpd`?

**Comment by cbetancourt** [comment]
https://gist.github.com/36f552e34cbbfa18f34133ee3ea718c2

**Comment by fxcoudert** [comment]
Both `mod_deflate` and `mod_xml2enc` are correctly built and linked on my Mojave system (Xcode and CLT installed). @cbetancourt reports the same on a system with CLT but not Xcode.

Somehow, on our CI machines (which build the bottles), these two modules are not built.

**Comment by cbetancourt** [comment]
The only difference between my system today and when I first upgraded to httpd@2.4.37 is a patch release of Mojave 10.14.1, which I installed last night.

**Comment by fxcoudert** [comment]
@cbetancourt we will soon update our CI machines to 10.14.1 and Xcode 10.1, so we will know :)

**Comment by n0nag0n** [comment]
I reinstalled from bottle, and reinstalled from source, and in both cases I still get issues finding mod_deflate.

```
httpd: Syntax error on line 111 of /usr/local/etc/httpd/httpd.conf: Cannot load lib/httpd/modules/mod_deflate.so into server: dlopen(/usr/local/opt/httpd/lib/httpd/modules/mod_deflate.so, 10): image not found
```

The modules that do get installed are below.

```
httpd.exp                   mod_authz_groupfile.so      mod_dir.so                  mod_log_debug.so            mod_proxy_hcheck.so         mod_socache_dbm.so
mod_access_compat.so        mod_authz_host.so           mod_dumpio.so               mod_log_forensic.so         mod_proxy_http.so           mod_socache_memcache.so
mod_actions.so              mod_authz_owner.so          mod_echo.so                 mod_logio.so                mod_proxy_scgi.so           mod_socache_shmcb.so
mod_alias.so                mod_authz_user.so           mod_env.so                  mod_macro.so                mod_proxy_uwsgi.so          mod_speling.so
mod_allowmethods.so         mod_autoindex.so            mod_expires.so              mod_md.so                   mod_proxy_wstunnel.so       mod_ssl.so
mod_asis.so                 mod_brotli.so               mod_ext_filter.so           mod_mime.so                 mod_ratelimit.so            mod_status.so
mod_auth_basic.so           mod_buffer.so               mod_file_cache.so           mod_mime_magic.so           mod_reflector.so            mod_substitute.so
mod_auth_digest.so          mod_cache.so                mod_filter.so               mod_mpm_event.so            mod_remoteip.so             mod_suexec.so
mod_auth_form.so            mod_cache_disk.so           mod_headers.so              mod_mpm_prefork.so          mod_reqtimeout.so           mod_unique_id.so
mod_authn_anon.so           mod_cache_socache.so        mod_heartbeat.so            mod_mpm_worker.so           mod_request.so              mod_unixd.so
mod_authn_core.so           mod_cgi.so                  mod_heartmonitor.so         mod_negotiation.so          mod_rewrite.so              mod_userdir.so
mod_authn_dbd.so            mod_cgid.so                 mod_http2.so                mod_proxy.so                mod_sed.so                  mod_usertrack.so
mod_authn_dbm.so            mod_charset_lite.so         mod_include.so              mod_proxy_ajp.so            mod_session.so              mod_version.so
mod_authn_file.so           mod_data.so                 mod_info.so                 mod_proxy_balancer.so       mod_session_cookie.so       mod_vhost_alias.so
mod_authn_socache.so        mod_dav.so                  mod_lbmethod_bybusyness.so  mod_proxy_connect.so        mod_session_crypto.so       mod_watchdog.so
mod_authnz_fcgi.so          mod_dav_fs.so               mod_lbmethod_byrequests.so  mod_proxy_express.so        mod_session_dbd.so          
mod_authz_core.so           mod_dav_lock.so             mod_lbmethod_bytraffic.so   mod_proxy_fcgi.so           mod_setenvif.so             
mod_authz_dbd.so            mod_dbd.so                  mod_lbmethod_heartbeat.so   mod_proxy_fdpass.so         mod_slotmem_plain.so        
mod_authz_dbm.so            mod_dialup.so               mod_log_config.so           mod_proxy_ftp.so            mod_slotmem_shm.so          
```

I just updated to 10.14.1 last night.

**Comment by fxcoudert** [comment]
@n0nag0n can you post your `brew config` output?

**Comment by n0nag0n** [comment]
Sure @fxcoudert 
```
HOMEBREW_VERSION: 1.8.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 422257067cc46d86138baa0e8e453348c2829cee
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2ecd0bc996d7cb0f243e99559ab69f34b47083b8
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.14.1-x86_64
CLT: N/A
Xcode: 10.1
```

**Comment by fxcoudert** [comment]
@n0nag0n so apparently, Xcode without CLT works, CLT alone or Xcode + CLT doesn't.

**Comment by n0nag0n** [comment]
I'm sure it has to do with that CLT issue, cause I definitely have command line tools installed. I've had brew running on here for quiet some time with that installed (years) @fxcoudert

**Comment by fluff** [comment]
Maybe this is related? From the Xcode 10 release notes at https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes?language=objc search for "`usr/include`" and there is a reference to a `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` file?

**Comment by SMillerDev** [comment]
That one is only a temporary fix if any, it'll go away soon and usage is discouraged afaik.

**Comment by fxcoudert** [comment]
Fixed, thanks @kabel !
