### ISSUE TITLE
Why is this new version of my release not automatically submitted pr to update?

### ISSUE THREAD

**Issue by waruqi** [Homebrew/homebrew-core#33373]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen

New release(xmake v2.2.2): https://github.com/tboox/xmake/releases
But now it is still v2.2.1, https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+xmake+is%3Aclosed

Do I need to manually submit pr to update it now?

- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by fxcoudert** [comment]
Please open a pull request for the update. You can use the `brew bump-formula-pr` command to do it automatically for you.

**Comment by waruqi** [comment]
Thanks
