### ISSUE TITLE
brew upgrade/install hangs on Mojave

### ISSUE THREAD

**Issue by sigpet** [Homebrew/homebrew-core#33409]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install awscli
- What happened (include command output)
install hangs for a very very long time, debug output
$> brew upgrade -vv
==> Upgrading 1 outdated package:
awscli 1.16.30 -> 1.16.40
==> Upgrading awscli
rm /usr/local/bin/aws
rm /usr/local/bin/aws_completer
rm /usr/local/etc/bash_completion.d/aws_bash_completer
rm /usr/local/share/awscli
rm /usr/local/share/zsh/site-functions/_aws
rm /usr/local/share/zsh/site-functions/aws_zsh_completer.sh
==> Downloading https://homebrew.bintray.com/bottles/awscli-1.16.40.mojave.bottle.tar.gz
Already downloaded: /Users/sigpet/Library/Caches/Homebrew/downloads/8a2f2c4b9a28451128e257525299e4b4df204888161e7eb972ec9238ae93836b--awscli-1.16.40.mojave.bottle.tar.gz
==> Verifying 8a2f2c4b9a28451128e257525299e4b4df204888161e7eb972ec9238ae93836b--awscli-1.16.40.mojave.bottle.tar.gz checksum
==> Pouring awscli-1.16.40.mojave.bottle.tar.gz
tar xf /Users/sigpet/Library/Caches/Homebrew/downloads/8a2f2c4b9a28451128e257525299e4b4df204888161e7eb972ec9238ae93836b--awscli-1.16.40.mojave.bottle.tar.gz -C /var/folders/bt/g2nsnxgn33x9504zfxfxdc400000gn/T/d20181026-10902-7a7hv9
cp -pR /var/folders/bt/g2nsnxgn33x9504zfxfxdc400000gn/T/d20181026-10902-7a7hv9/awscli/. /usr/local/Cellar/awscli
Here is where it hangs.
running the same command in terminal as my user directly hangs the same,
running the cp command in terminal using sudo copies immediately

- What you expected to happen
Expected awscli to be installed immediately

- Step-by-step reproduction instructions (by running `brew install` commands)
See above

**Comment by sigpet** [comment]
I'd like to add
If laptop is started in "safe mode" brew install works fine, when booted back into normal issue comes back.

**Comment by MikeMcQuaid** [comment]
> * install hangs for a very very long time

How long, out of interest?

> * [x]  ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> * [x]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

You didn't do these, please do.



> If laptop is started in "safe mode" brew install works fine

What do you mean by "safe mode"?

**Comment by sigpet** [comment]
It hangs for a very long time, I've never had the patience to wait for it to finish, escaped to "safe boot" and run from there.  
Scanning size of source and destination show it's copying but very very slow., awscli source was 87Mb but after around 30 minutes only 57Kb had been copied.
I'm not the only one having this issue, my laptop is new 15" 2018, colleague has 15" late 2015 recently upgraded to Mojave and ran into the same issue. I really think this is Mojave issue, just wondering if someone else is running into this issue and maybe has a solution.
I've never had this problem with cask installs.

brew gist-logs came up empty, probably because I didn't let the install finish.

Sorry, "safe mode" = "safe boot" in Mac. You hold down shift while starting the machine to enter into it.

Siggi

**Comment by sigpet** [comment]
I've left the installer running for couple of hours and it didn't finish copying less than 100Mb in that time.

$> brew gist-logs awscli
Error: No logs.

$> brew config
HOMEBREW_VERSION: 1.8.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdd8e9b7cf1e53322492e1e90f685c19bdfde506
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 70dbed503a7c05f7b7583d4a77fd23553a98dd8e
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: N/A

$> brew doctor
Your system is ready to brew.

**Comment by MikeMcQuaid** [comment]
Cam you confirm what filesystem and hard drive type (e.g. SSD/Fusion/HDD) both the relevant files/directories are on?

**Comment by sigpet** [comment]
Files/directories can be seen above in the verbose output of the command

This is brand new MacBook Pro (15-inch, 2018)

Storage info:
  Available:	196.94 GB (196,936,867,840 bytes)
  Capacity:	499.96 GB (499,963,174,912 bytes)
  Mount Point:	/
  File System:	APFS
  Writable:	Yes
  Ignore Ownership:	No
  BSD Name:	disk1s1
  Volume UUID:	BAFB5B78-F60D-4074-9FDB-20BC2730095E
  Physical Drive:
  Device Name:	APPLE SSD AP0512M
  Media Name:	AppleAPFSMedia
  Medium Type:	SSD
  Protocol:	PCI-Express
  Internal:	Yes
  Partition Map Type:	Unknown
  SMART Status:	Verified

Disk info:
Volume name : Macintosh HD
Volume type : APFS Volume
BSD device node : disk1s1
Mount point : /
File system : APFS (Encrypted)
Connection : PCI-Express
Device tree path : IODeviceTree:/PCI0@0/RP17@1B/ANS2@0/AppleANS2Controller
Writable : Yes
Is case-sensitive : No
File system UUID : BAFB5B78-F60D-4074-9FDB-20BC2730095E
Volume capacity : 499,963,174,912
Available space (Purgeable + Free) : 198,627,604,671
Purgeable space : 1,657,194,687
Free space : 196,970,409,984
Used space : 300,659,175,424
File count : 1,081,481
Owners enabled : Yes
Is encrypted : Yes
System Integrity Protection supported : Yes
Can be verified : Yes
Can be repaired : Yes
Bootable : No
Journaled : No
Disk number : 1
Partition number : 1
Media name : 
Media type : Generic
Ejectable : No
Solid state : Yes
SMART status : Not Supported
Parent disks : disk1

**Comment by MikeMcQuaid** [comment]
Are `/var/folders/bt/g2nsnxgn33x9504zfxfxdc400000gn/T/d20181026-10902-7a7hv9/awscli/` and `/usr/local/Cellar/awscli` on the same volume, yeh?

**Comment by sigpet** [comment]
Yes, only one disk/ one partition on the laptop

**Comment by javian** [comment]
Is it only failing with `awscli` or does the same happen with other Formulae ?

**Comment by jeremyk** [comment]
Install/upgrade is hanging for me as well. Running with --verbose shows it stopping when trying to run something like this:
```
/usr/bin/sandbox-exec -f /private/tmp/homebrew20181214-12579-h1n37n.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-macho-2.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.30.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rubocop-0.61.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/unicode-display_width-1.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/powerpack-0.1.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/plist-3.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parser-2.5.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/parallel-1.12.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/backports-3.11.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/activesupport-5.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/i18n-1.1.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle-standalone/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.3/lib:/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib:/Library/Ruby/Site/2.3.0:/Library/Ruby/Site/2.3.0/x86_64-darwin18:/Library/Ruby/Site/2.3.0/universal-darwin18:/Library/Ruby/Site:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin18:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb --verbose
```
That file `/private/tmp/homebrew20181214-12579-h1n37n.sb` doesn't exist (checking in another terminal while this is hung.

**Comment by jeremyk** [comment]
Any chance this can be reopened or should I file a new issue?

**Comment by MikeMcQuaid** [comment]
This is specific to the relevant users systems. Unless you can identify what the issue is on your machine so we have more details to fix this we cannot do anything, sorry.
