### ISSUE TITLE
GnuPG should install libexec binaries

### ISSUE THREAD

**Issue by jlmuir** [Homebrew/homebrew-core#33436]
The `gnupg` package should install its `libexec` binaries to `/usr/local/libexec`.  For example, the `gpg-preset-passphrase` utility is sometimes needed, and there's no way to invoke it besides the versioned cellar path (e.g., `/usr/local/Cellar/gnupg/2.2.10/libexec`).

**Comment by SMillerDev** [comment]
The best way to get this fixed is a pull request.

**Comment by jlmuir** [comment]
OK, while I was preparing to make a PR, I discovered that `gpgconf` can emit the `libexec` path, so I can just use that to avoid referring to the version of GnuPG currently installed:

```
$ gpgconf --list-dirs libexecdir
/usr/local/Cellar/gnupg/2.2.10/libexec
```

So, never mind, I'll just use that to invoke `gpg-preset-passphrase`.
