### ISSUE TITLE
Please update uriparser to 0.9.0, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [Homebrew/homebrew-core#33439]
Hi!

Just a quick heads up that [uriparser 0.9.0](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.0) with security fixes has been released.

Thanks for updating!

**Comment by SMillerDev** [comment]
Thanks for the info but homebrew works best when people make a pull request when they notice something is out of date. You can do it pretty easily using `brew bump-formula-pr`

**Comment by hartwork** [comment]
I don't have macOS or brew around. I develop uriparser.

**Comment by fxcoudert** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-core/pull/33452
