### ISSUE TITLE
"brew uninstall unixodbc" come error !

### ISSUE THREAD

**Issue by gougoushan** [Homebrew/homebrew-core#33476]
Uninstalling /usr/local/Cellar/unixodbc/2.3.4... (43 files, 2.0MB)
Error: Calling 'depends_on ... => :run' is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/unixodbc.rb:15

**Comment by SMillerDev** [comment]
Could you fill out the issue template? It really makes debugging your issue a lot easier. I'm going to close this until we have the information we need to debug. Please don't make a new issue.
