### ISSUE TITLE
clang-format failed to build

### ISSUE THREAD

**Issue by ploxiln** [Homebrew/homebrew-core#3347]
brew gist-logs: https://gist.github.com/anonymous/fd188c3f572069dae561ed54029df44e

the gist of the gist:

```
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.11' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
```

This seems very similar to https://github.com/Homebrew/legacy-homebrew/issues/42221 where the fix was to make a `/Applications/Xcode.app` symlink. I don't have any Xcode installed, but of course I do have the command-line build tools installed (and built many homebrew formulae from source over the years). Does this formula really need the full Xcode.app installed? Should the description say so?

**Comment by DomT4** [comment]
Sigh, this again. Can you try sticking `ENV.delete("SDKROOT")` on the first line inside the `def install` block and see if `brew install clang-format` works for you then? Thanks.

**Comment by ploxiln** [comment]
That didn't seem to have the desired effect.

```
[pierce@plo-pro Formula]$ git diff
diff --git a/Formula/clang-format.rb b/Formula/clang-format.rb
index bbc3bde..0366a87 100644
--- a/Formula/clang-format.rb
+++ b/Formula/clang-format.rb
@@ -41,6 +41,7 @@ class ClangFormat < Formula
   depends_on "subversion" => :build
 
   def install
+    ENV.delete("SDKROOT")
     (buildpath/"projects/libcxx").install resource("libcxx")
     (buildpath/"tools/clang").install resource("clang")
 
[pierce@plo-pro Formula]$ brew install clang-format
==> Cloning http://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-06-27/
(... same failure)
```

new gist-logs just in case: https://gist.github.com/anonymous/308da5da1e34997734801131a77fc61a

**Comment by ilovezfs** [comment]
@DomT4 since @ploxiln is on 10.11 not 10.10, it's very unlikely to be our favorite issue, and indeed it's not. The problem here is that @ploxiln doesn't have Xcode, and the build system is too daft to figure out that in that case it should just set `CMAKE_OSX_SYSROOT` to `"/"`. So it's fixed by adding to the formula:
```
      args << "-DCMAKE_OSX_SYSROOT=/" unless MacOS::Xcode.installed?
```

**Comment by ploxiln** [comment]
That worked, thanks.

```
[pierce@plo-pro Formula]$ git diff
diff --git a/Formula/clang-format.rb b/Formula/clang-format.rb
index bbc3bde..9fd1edc 100644
--- a/Formula/clang-format.rb
+++ b/Formula/clang-format.rb
@@ -46,6 +46,7 @@ class ClangFormat < Formula
 
     mkdir "build" do
       args = std_cmake_args
+      args << "-DCMAKE_OSX_SYSROOT=/" unless MacOS::Xcode.installed?
       args << "-DLLVM_ENABLE_LIBCXX=ON"
       args << ".."
       system "cmake", "-G", "Ninja", *args
[pierce@plo-pro Formula]$ brew install clang-format
==> Cloning http://llvm.org/svn/llvm-project/llvm/tags/google/stable/2016-06-27/
Updating /Users/pierce/Library/Caches/Homebrew/clang-format--svn
==> Downloading http://llvm.org/releases/3.8.0/libcxx-3.8.0.src.tar.xz
Already downloaded: /Users/pierce/Library/Caches/Homebrew/clang-format--libcxx-3.8.0.tar.xz
==> Cloning http://llvm.org/svn/llvm-project/cfe/tags/google/stable/2016-06-27/
Updating /Users/pierce/Library/Caches/Homebrew/clang-format--clang--svn
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/l
==> ninja clang-format
/usr/local/Cellar/clang-format/2016-06-27: 10 files, 1.5M, built in 3 minutes 44 seconds
[pierce@plo-pro Formula]$ clang-format --version
clang-format version 3.9.0 (tags/google/stable/2016-06-27)
```

**Comment by ilovezfs** [comment]
@ploxiln you're welcome :)

**Comment by DomT4** [comment]
@ilovezfs Yeah, I discounted that possibility initially because we handle `sysroot` in `superenv`, but of course because there's a recursive `scons` dep it builds under `stdenv`. Sigh.

Feel free to chuck that into the formula & close here.
