### ISSUE TITLE
apache-spark formula includes the non-working docker-image-tool.sh script

### ISSUE THREAD

**Issue by dbolkensteyn** [Homebrew/homebrew-core#33486]
Steps to reproduce:
1. `brew install apache-spark` (version 2.3.2)
2. this will create the file `lrwxr-xr-x  1 dinesh  admin  53 Oct 26 18:02 /usr/local/bin/docker-image-tool.sh -> ../Cellar/apache-spark/2.3.2/bin/docker-image-tool.sh` 
3. which is actually not usable. `docker-image-tool.sh -t myspark build` fails with the following error message:
```
Cannot find docker image. This script must be run from a runnable distribution of Apache Spark.
```

=> It seems that the installation is incomplete.

FYI, this tool is mentioned in the instructions for running Apache Spark on a Kubernetes cluster: https://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images

**Comment by dbolkensteyn** [comment]
Quick update: The script actually works as expected, but only when executed from the `/usr/local/Cellar/apache-spark/2.3.2/libexec` working directory.

**Comment by MikeMcQuaid** [comment]
Please fill in the issue template as requested, thanks!

**Comment by fxcoudert** [comment]
We're not doing anything special about this file, and it appears to be a deliberate upstream choice to make it runnable from since the Apache Spark install path. The error message is rather specific.

I am thus closing the issue.

**Comment by dbolkensteyn** [comment]
Makes sense - thank you @fxcoudert
