### ISSUE TITLE
Trying to install i3 yields confusing error messages

### ISSUE THREAD

**Issue by Feliix42** [Homebrew/homebrew-core#33481]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)  
I wanted to install the `i3` window manager by running `brew install i3`.

- What happened (include command output)  
The formula was not found and hence, `i3` not installed. But the output was somewhat confusing:
```
[felix@Samaritan] $ brew install i3
Error: No available formula with the name "i3"
It was migrated from homebrew/x11 to homebrew/core.
```
The output indicated that I somehow misconfigured `brew`, as it was not able to find the formula although it was just moved from homebrew/x11 to homebrew/core. It took me a great deal of debugging and searching to find out that `i3` was removed in #27486. 😭 

- What you expected to happen  
The package would be installed or brew would provide the information that the package has been removed/is no longer available. Therefore, the migration message should be removed. I would have opened a PR in `homebrew/x11` but I realized that it is now archived and read-only.

- Step-by-step reproduction instructions (by running `brew install` commands)  
Just run `brew install i3`.

---

For reference, my `brew config` output:
```
HOMEBREW_VERSION: 1.8.0-60-g3e44ed6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3e44ed61599dfffee91bf4a3f203e3c8f1f482c3
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5e7728216e0c825dbe6ee347b1432dada577eca
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_112
macOS: 10.14-x86_64
CLT: N/A
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment]
What's the output of your `brew tap`?

**Comment by Feliix42** [comment]
I'm tapped into
```
beeftornado/rmtree
clangen/musikcube
hawkw/grub
hawkw/x86_64-pc-elf
homebrew/bundle
homebrew/cask
homebrew/cask-versions
homebrew/completions
homebrew/core
homebrew/dupes
homebrew/games
homebrew/php
homebrew/science
homebrew/services
homebrew/x11
koekeishiya/formulae
mopidy/mopidy
neomutt/neomutt
neonichu/formulae
redox-os/gcc_cross_compilers
```

I suppose untapping `homebrew/x11` would solve the issue?

**Comment by MikeMcQuaid** [comment]
Yes, untapping all the deprecated Homebrew taps (completions, dupes, games, php, science, x11) would be a good idea.
