### ISSUE TITLE
Change in commit SHA intentional, not malicious; need merge approval

### ISSUE THREAD

**Issue by stevebang** [Homebrew/homebrew-core#33490]
As recommended by @fxcoudert (see https://github.com/Homebrew/homebrew-core/pull/33382#issuecomment-433500132), I am letting you know that the re-tag of the InfluxDB 1.6.4 release was intentional. The dev team did a rebuild of the version, rather than change the version number. [FYI -- this will not happen again -- everyone agreed to change version numbers when a new build, even if nothing changed in the OSS (non-Enterprise) build.] Please allow the merge to proceed ASAP.  Thanks!

**Comment by MikeMcQuaid** [comment]
Thanks @stevebang for the heads up!
