### ISSUE TITLE
Vault is no longer able to connect to Vault server running on private network with VPN

### ISSUE THREAD

**Issue by tglawless** [Homebrew/homebrew-core#33507]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I'm updating Vault which I use as a client on my Mac to connect to a Vault server over a VPN connection.

- What happened (include command output)
I upgraded from Vault v0.10.2 to v0.11.4 and Vault is no longer able to resolve the IP address using the DNS servers provided by my VPN connection.

```shell
brew install vault --with-dynamic
Warning: vault: this formula has no --with-dynamic option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/vault-0.11.4.high_sierra.bottle.tar.gz
Already downloaded: /Users/<USER_NAME>/Library/Caches/Homebrew/downloads/4680f47e4251390885a1a98bc508e9b988cdae247232b146518724b4991a11ba--vault-0.11.4.high_sierra.bottle.tar.gz
==> Pouring vault-0.11.4.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/vault/0.11.4: 6 files, 91.0MB
```

- What you expected to happen
Vault v0.11.4 should support the `--with-dynamic` option as v0.10.2 did allowing me to install vault with cgo enabled.

- Step-by-step reproduction instructions (by running `brew install` commands)
1) brew install vault --with-dynamic
2) See wanring `Warning: vault: this formula has no --with-dynamic option so it will be ignored!`
3) When connecting to Vault server over VPN, Vault displays error: `Error authenticating: Put https://<HOSTNAME>/v1/auth/github/w3-rre/login: dial tcp: lookup <HOSTNAME> on 192.168.1.1:53: no such host`

**Comment by tglawless** [comment]
The error isn't an authentication error.  It's a DNS lookup error.  For reference see this issue: https://github.com/Homebrew/homebrew-core/pull/7238

**Comment by fxcoudert** [comment]
- We are trying to cut down the number of options used in Homebrew
- `--with-dynamic` was rarely used (0.91% of installs)
- Upstream ships static versions.
- It really sounds more like a bug with go, that should be fixed there.

For these reasons, I am going to close this, as we are not going to revert.
