### ISSUE TITLE
Git send-email broken, cannot find Homebrew Perl Net/SMTP/SSL.pm

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew-core#33524]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? --> No logs for Perl. 
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### What you were trying to do (and why)

Sending an email with `git send-email` using Homebrew Git.

### What happened (include command output)

At first I got this error:

```
➜ git send-email origin/master
…
Can't locate Net/SMTP/SSL.pm in @INC (you may need to install the Net::SMTP::SSL module) (@INC contains: /usr/local/Cellar/git/2.19.1/share/perl5 /Library/Developer/CommandLineTools/Library/Perl/5.18/darwin-thread-multi-2level /Applications/Xcode.app/Contents/Developer/Library/Perl/5.18/darwin-thread-multi-2level /Users/werner/perl5/lib/perl5/darwin-thread-multi-2level /Users/werner/perl5/lib/perl5 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/Cellar/git/2.19.1/libexec/git-core/git-send-email line 1497.
```

I guess the issue is that `@INC` simply does not contain the path where the module is installed.

I then ran `brew reinstall perl`, followed the caveat instructions, then `brew reinstall git --with-openssl`, then a `cpanm Net::SMTP::SSL`:

```
➜ cpanm Net::SMTP::SSL
--> Working on Net::SMTP::SSL
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Net-SMTP-SSL-1.04.tar.gz ... OK
Configuring Net-SMTP-SSL-1.04 ... OK
==> Found dependencies: IO::Socket::SSL
--> Working on IO::Socket::SSL
Fetching http://www.cpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.060.tar.gz ... OK
Configuring IO-Socket-SSL-2.060 ... OK
==> Found dependencies: Net::SSLeay, Mozilla::CA
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ... OK
Configuring Net-SSLeay-1.85 ... OK
Building and testing Net-SSLeay-1.85 ... OK
Successfully installed Net-SSLeay-1.85
--> Working on Mozilla::CA
Fetching http://www.cpan.org/authors/id/A/AB/ABH/Mozilla-CA-20180117.tar.gz ... OK
Configuring Mozilla-CA-20180117 ... OK
Building and testing Mozilla-CA-20180117 ... OK
Successfully installed Mozilla-CA-20180117
Building and testing IO-Socket-SSL-2.060 ... OK
Successfully installed IO-Socket-SSL-2.060
Building and testing Net-SMTP-SSL-1.04 ... OK
Successfully installed Net-SMTP-SSL-1.04
4 distributions installed
```

Now I got a different error:

```
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/werner/perl5/lib/perl5/darwin-thread-multi-2level/auto/Net/SSLeay/SSLeay.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /Users/werner/perl5/lib/perl5/darwin-thread-multi-2level/auto/Net/SSLeay/SSLeay.bundle
  Expected in: flat namespace

error: git-send-email died of signal 6
```

So I removed `~/perl5` directory completely, got rid of the `eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"` statement in my `.zshrc`,  and did a normal `cpan Net::SMTP::SSL`.

Now I'm back to the original error.

### What you expected to happen

I expected Git to be able to send the email using Homebrew `perl`.

### Step-by-step reproduction instructions (by running `brew install` commands)

All I know is that I did these at some point:

```
brew install git
brew install perl
brew install cpanminus
```

I had also added the `eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"` line – as suggested in the Perl formula caveat – while troubleshooting, but ended up removing it again.

### Debug Output

```
$ brew doctor
…
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/werner/.pyenv/shims/python3.6m-config
  /Users/werner/.pyenv/shims/python-config
  /Users/werner/.pyenv/shims/python3-config
  /Users/werner/.pyenv/shims/python3.6-config

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/fuse-ext2.pc
```

```
$ brew config
HOMEBREW_VERSION: 1.8.0-76-gcbb2e1b
ORIGIN: https://github.com/Homebrew/brew
HEAD: cbb2e1b3dd63e1b9621c67b619aad8c914772041
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: febbf812cc2e65a19d1aea835121d6dd3631578a
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144
macOS: 10.13.6-x86_64
CLT: 10.0.0.0.1.1535735448
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11
```

**Comment by slhck** [comment]
> Git will not use Homebrew's Perl unless it depends on it.

Ah, I thought it would, since `@INC` already contains `/usr/local/Cellar/git/2.19.1/share/perl5` and so on.

> Is Net::SMTP::SSL installed on the macOS system Perl?

No, I don't have it on the system, as I'm kind of hesitant to system-install anything these days, particularly when using replacements of system binaries (like Python, Ruby, Perl, …).

What would be the proper way to install it if `/usr/local/bin/[perl,cpan]` take precedence over `/usr/bin/[perl,cpan]`? Is a `sudo cpan Net::SMTP::SSL` enough? (I don't want to screw up permissions…)

**Comment by MikeMcQuaid** [comment]
I don't know the "proper" way as I don't use Perl or this Git module, sorry.

**Comment by slhck** [comment]
Ok, no worries. I don't want this to become a support discussion, obviously.

I'm more interested in whether there's a way to communicate this to end users, to avoid people messing with their system, and if so, whether that'd be something that needs to be added to the Git formula.

See also https://github.com/Homebrew/homebrew-core/issues/12870 which dates back to when the Git formula actually had a `--with-perl` option and where it says:

> This basically seems to be broken out of the box, but indeed, having a custom/brewed perl means you need to give git some extra places to look. We can either support custom perl's a little better or we can vendor some perl modules into the git formula.

… maybe @DomT4 has some ideas?

**Comment by MikeMcQuaid** [comment]
Dom isn't working on Homebrew any more really.



> I'm more interested in whether there's a way to communicate this to end users, to avoid having people mess with their system, and if so, whether that'd be something that needs to be added to the Git formula.

Yeh, that'd be ideal.

**Comment by slhck** [comment]
So I first tried:

```
$ sudo -H /usr/bin/cpan Net::SMTP::SSL
```

but that installs into `/var/root/perl5/` which is also not part of the directories Git looks into. I removed `/var/root/.cpan` and `/var/root/perl5` completely, then ran:

```
$ sudo /usr/bin/cpan Net::SMTP::SSL
```

which installed into `/Library/Perl/5.18/` and made `git send-email` work.

I wonder if this solution is generalizable/safe enough to put it into the Git formula's caveats, but I guess I'll send a PR and we'll see.

**Comment by DomT4** [comment]
I'm slowly extracting myself from using Homebrew so the advice I can give is limited, but you could try `inreplace`-ing the script with `s.gsub! "#!/usr/bin/perl", "#!/usr/bin/perl -T"`.

I haven't checked but I suspect that would work. It's a sticking plaster over the broader issue of perl-in-brew usage but it's quick/simple/fairly pain-free. Hope this helps some, @slhck.
