### ISSUE TITLE
Gcc 6.5.0 not found in GNU ftp and mirrors

### ISSUE THREAD

**Issue by olemis** [Homebrew/homebrew-core#33543]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

For months [Skycoin Travis CI macos builds](https://travis-ci.org/simelo/skycoin) have been installing `gcc=6.4.0-2` . 

- What happened (include command output)

Since Friday , after the upgrade of the `gcc@6` formula to `gcc=6.5.0` , recent builds are failing . Initially [builds timed out](https://travis-ci.org/simelo/skycoin/jobs/447322764) . Now, [file is not found](https://travis-ci.org/simelo/skycoin/jobs/448470886#L2067-L2078) .

- What you expected to happen

`gcc@6` installed successfully, after downloading packages . Maybe revert formula to work with `gcc@6.4.0-2` once again ?

- Step-by-step reproduction instructions (by running `brew install` commands)

See [build steps](https://travis-ci.org/simelo/skycoin/jobs/448470886/config) for further details. Besides :

```sh

$ git remote -v
origin	https://github.com/Homebrew/homebrew-core (fetch)
origin	https://github.com/Homebrew/homebrew-core (push)

$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git log -n 1
commit 92bf96e55a50a81baad43434ada0053a67b8a45d (HEAD -> master, origin/master, origin/HEAD)
Author: Jason Karns <jason.karns@gmail.com>
Date:   Tue Oct 30 18:38:53 2018 -0400

    node-build 3.0.22 (#33523)

$ grep '.tar.xz' Formula/gcc\@6.rb
  url "https://ftp.gnu.org/gnu/gcc/6.5.0/gcc-6.5.0.tar.xz"
  mirror "https://ftpmirror.gnu.org/gcc/6.5.0/gcc-6.5.0.tar.xz"

$ wget -O /dev/null https://ftp.gnu.org/gnu/gcc/6.5.0/gcc-6.5.0.tar.xz
--2018-10-31 01:54:27--  https://ftp.gnu.org/gnu/gcc/6.5.0/gcc-6.5.0.tar.xz
Resolving ftp.gnu.org (ftp.gnu.org)... 208.118.235.20
Connecting to ftp.gnu.org (ftp.gnu.org)|208.118.235.20|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-31 01:54:28 ERROR 404: Not Found.

$ wget -O /dev/null https://ftpmirror.gnu.org/gcc/6.5.0/gcc-6.5.0.tar.xz
--2018-10-31 01:54:42--  https://ftpmirror.gnu.org/gcc/6.5.0/gcc-6.5.0.tar.xz
Resolving ftpmirror.gnu.org (ftpmirror.gnu.org)... 208.118.235.200
Connecting to ftpmirror.gnu.org (ftpmirror.gnu.org)|208.118.235.200|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://mirrors.tripadvisor.com/gnu/gcc/6.5.0/gcc-6.5.0.tar.xz [following]
--2018-10-31 01:54:43--  https://mirrors.tripadvisor.com/gnu/gcc/6.5.0/gcc-6.5.0.tar.xz
Resolving mirrors.tripadvisor.com (mirrors.tripadvisor.com)... 199.102.235.174
Connecting to mirrors.tripadvisor.com (mirrors.tripadvisor.com)|199.102.235.174|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-31 01:54:44 ERROR 404: Not Found.

```

**Comment by SMillerDev** [comment]
That should be tar.gz looking at their web interface. Could you make a pull request to update that? (In which case, don't forget the checksums)

**Comment by olemis** [comment]
The right URL should be https://ftp.gnu.org/gnu/gcc/gcc-6.5.0/gcc-6.5.0.tar.xz

**Comment by olemis** [comment]
in any case , the installation of version `6.5.0` makes [Travis builds time out](https://travis-ci.org/simelo/skycoin/jobs/447322764#L2032-L2047).

**Comment by commitay** [comment]
Will be fixed by https://github.com/Homebrew/homebrew-core/pull/33544

**Comment by commitay** [comment]
> in any case , the installation of version 6.5.0 makes Travis builds time out.

The builds are timing out because it's building `gcc` from source. We have stopped bottling binaries for el capitan, I suggest switching to a newer `osx_image`.

**Comment by olemis** [comment]
@MikeMcQuaid `HOMEBREW_BUILD_FROM_SOURCE` does not solve the issue , [builds still time out](https://travis-ci.org/simelo/skycoin/jobs/449081488) after [adding the env var](https://github.com/simelo/skycoin/commit/c2328b4231e4a0c3ae5a6be60a2d07169110ec6c) .
