### ISSUE TITLE
graphviz --with-app failed to build on 10.13

### ISSUE THREAD

**Issue by mrpippy** [Homebrew/homebrew-core#33570]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Trying to install graphviz --with-app (`brew install graphviz --with-app`) on 10.13.6, with latest Xcode and CLT (10.1) installed. The `xcodebuild` step fails when compiling Attributes.xib, without any obvious error message being printed.

https://gist.github.com/mrpippy/50c3e8bd374df4273c4ee0d1ca1db746

**Comment by fxcoudert** [comment]
```
CompileXIB /tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx/English.lproj/MainMenu.xib (in target: application)
    cd /tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode.app/Contents/Developer/usr/bin/..
    /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module Graphviz --output-partial-info-plist /tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx/build/graphviz.build/Release/application.build/English.lproj/MainMenu-PartialInfo.plist --auto-activate-custom-fonts --target-device mac --minimum-deployment-target 10.13 --output-format human-readable-text --compile /tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx/build/Release/Graphviz.app/Contents/Resources/English.lproj/MainMenu.nib /tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx/English.lproj/MainMenu.xib
/* com.apple.ibtool.document.warnings */
/tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx/English.lproj/MainMenu.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
/* com.apple.ibtool.document.errors */
/tmp/graphviz-20181031-18964-1msp6r3/graphviz-2.40.1/macosx/English.lproj/MainMenu.xib:global: error: Compiling for earlier than macOS 10.6 is no longer supported. [12]
```

**Comment by fxcoudert** [comment]
Thanks @mrpippy for the bug report. This is an issue of graphviz's `MainMenu.xib` file, which is set to build on a very old macOS version, not supported anymore in Xcode 10. Can you please open a bug report with them so they can fix it?

(I am not aware of a way to modify this setting from the command line, so we probably cannot work around the issue from Homebrew.)

**Comment by MikeMcQuaid** [comment]
Suggestion: remove `--with-app` as Homebrew does a bad job at supporting `.app`s (they should be in Homebrew Cask).
