### ISSUE TITLE
/usr/local/Cellar/gcc/8.2.0/include/c++/8.2.0/cwchar:44:10: fatal error: wchar.h: No such file or directory on 10.14.1

### ISSUE THREAD

**Issue by amelialdrew** [Homebrew/homebrew-core#33590]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ yes] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ yes] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [yes ] ran `brew update` and can still reproduce the problem?
- [yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [yes ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

After installing the new Mojave and Xcode, I've tried to compile some code that was working fine before and it is coming up with the error in the title. I have run all the suggested commands, restarted the terminal etc. and nothing has fixed it. Please let me know if I can provide any more information.

**Comment by amelialdrew** [comment]
Link to gist here: https://gist.github.com/amelialdrew/67353dc85d033fb27b1b74690d2ceb12

**Comment by amelialdrew** [comment]
Also this error: fatal error: sys/cdefs.h: No such file or directory

**Comment by SMillerDev** [comment]
This guy seemed to be succesful by reinstalling xcode

https://stackoverflow.com/questions/52517784/codeblocks-c-compiling-with-macos-mojave-fatal-error-sys-cdefs-h-no-such

**Comment by fxcoudert** [comment]
Please report in full: what brew command you were trying to run, what is the error output, etc. Here it is not clear enough for us to help you. It does not actually look like a Homebrew problem.

**Comment by amelialdrew** [comment]
Hi - you may be right that this is not a problem with homebrew itself, however reinstalling gcc with brew has fixed one error (I now get fatal error: mpi.h: No such file or directory) - so it looks like it may have been a problem with the interaction of homebrew with the new Mojave. Does this sound likely? In any case, apologies if this is the wrong place to report the error. Any help with this new error would be appreciated!

**Comment by Paalon** [comment]
I saw the same error after updating to macOS Mojave. `brew reinstall gcc` solved this.
