### ISSUE TITLE
brew install wine 404 error

### ISSUE THREAD

**Issue by imzzy** [Homebrew/homebrew-core#3363]
when run brew install wine  with https://www.davidbaumgold.com/tutorials/wine-mac/

==> Installing wine dependency: libtiff
==> Downloading http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/t/tiff/tiff_4.

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libtiff--patch"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/t/tiff/tiff_4.0.6-1.debian.tar.xz

**Comment by DomT4** [comment]
You need to `brew update`.

**Comment by imzzy** [comment]
thank you. i will try it again. @DomT4
