### ISSUE TITLE
Add ENABLE_TCL to weechat formula

### ISSUE THREAD

**Issue by CaledoniaProject** [Homebrew/homebrew-core#33671]
Please add `--with-tcl` option to the weechat formula

```
option "with-tcl", "Build the TCL module"

args << "-DENABLE_TCL=OFF" if build.without? "tcl"
```

**Comment by fxcoudert** [comment]
The weechat formula already has way too many options, so it's unlikely that we add a new one. We would, however, consider a pull request that builds against the system Tcl (which is always present) for all users.

**Comment by CaledoniaProject** [comment]
It won't compile on Mojave now, I had to disable TCL.

**Comment by xiangsheng** [comment]
Same problem, can't compile on Mojave.
