### ISSUE TITLE
coreutils man pages are not resolved

### ISSUE THREAD

**Issue by ipatch** [Homebrew/homebrew-core#33680]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

```shell
brew install coreutils
```

The default `man` command on macOS will not pickup on the the man pages contained within `$brew_prefix/opt/coreutils/libexec/gnuman`

**Ex**

```shell
man who
```

will still pick up on the BSD man page.

- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

## Fix

I did a bandaid fix to link `gnubin` to `bin` and `gnuman` to `man`.  Long story short macOS doesn't require of any man page specific setting files within `/etc`.  That said, creating a `bin` and `man` directories within the same sibling directory and having the `bin` directory contained within the `$PATH` will allow the `man` command to pickup on the path to the man page.

cheers 🍻
Chris

**Comment by fxcoudert** [comment]
The caveats for coreutils say this:

```
==> Caveats
All commands have been installed with the prefix 'g'.

If you really need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:

    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
```

So this is by design, so as not to shadow the existing utils.

**Comment by ipatch** [comment]
yeah that info you reference is outdated, as setting the `MANPATH` on macOS is problematic.

**Comment by fxcoudert** [comment]
@ipatch can you explain what you mean by “setting the MANPATH on macOS is problematic”? It's working here, and I don't remember bug reports about it.

`man grep` gives me BSD grep man page. `MANPATH=/usr/local/Cellar/grep/3.1/libexec/gnuman man grep` gives me `GNU grep 3.1` man page.

**Comment by ipatch** [comment]
@fxcoudert

macOS hasn't honored the `$MANPATH` environment variable in quite some time.  Doing a search for `macos $MANPATH` in a popular search engine yields, [this](https://hints.macworld.com/article.php?story=20031014053111192) as the top result.  And the second result in the search yieds, [this](https://superuser.com/questions/589242/cannot-find-man-pages-in-osx-manpath-issue)

You can see how macOS constructs the path to man pages by running

```shell
man -d
```

and if you have a directory, ie. `/mr/super/fancy/bin` and `/mr/super/fancy/man` then you will notice how macOS dynamically adds `/mr/super/fancy/man` to the search path for man pages, all the while not setting the `$MANPATH` environment variable.

From my experience when I explicitly set `MANPATH` for my interactive user environment, ie. when running fish shell,

```shell
set -gx MANPATH "/usr/share/man"
```

and then run `man brew` it returns

```conf
No manual entry for brew
```

I believe this happens on macOS because **explicitly** setting **MANPATH** to a path on the local system will erase / remove all the paths that macOS has dynmaically added to search for man pages.  So when searching for man pages that aren't in `/usr/share/man` macOS is unable to locate them.

Now knowing all this, when running `brew info coreutils` and I see,

```
Additionally, you can access their man pages with normal names if you add
the "gnuman" directory to your MANPATH from your bashrc as well:

    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
```

I can't but think this shouldn't be the in the **Caveats** section because all other search paths for man pages are removed.

**Comment by fxcoudert** [comment]
That's unfortunate. Not sure how to fix it.

**Comment by MikeMcQuaid** [comment]
I cannot reproduce the issue; `MANPATH` works as documented for me. Please provide step-by-step instructions in Bash or ZSH that demonstrate this problem.

**Comment by ipatch** [comment]
@fxcoudert thanks for sharing. 👍

I put together an asciicast demonstrating how setting the `$MANPATH` env var on macOS explicitly is not required for the homebrew version of **bash** to pick up on the man pages for coreutils.  Second, I'll be the first to say that I don't entirely know what is going on when it comes to working with the `$MANPATH` env var on macOS, but just sharing what I know.

[![macos-manpath-weirdness](https://asciinema.org/a/210124.svg)](https://asciinema.org/a/210124)

Third, adding the `:` as @fxcoudert states does in fact keep the `MANPATH`s intact.
