### ISSUE TITLE
cling fails on MacOS Mojave 10.14, unaware of LLVM package

### ISSUE THREAD

**Issue by Zyrsha** [Homebrew/homebrew-core#33693]
I've installed the latest homebrew packages for LLVM + Clang 7.0.0:

`brew install llvm --with-toolchain --with-lldb --with-python@2`
`brew install cling`

I'd like to use Cling with Clang 7 and _LIBCPP_VERSION 7000

On Mojave, we now have these errors:
```
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
Results was:
With exit code 256
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_VERSION '6000'
  Extraction of runtime standard library version was: ''
```

There seems to be a few problems going on here:
- Cling not working at all on Mojave (similar to issue #32949)
- Cling build misconfigured and using wrong Clang, and wrong _LIBCPP_VERSION
- Cling formula unaware of LLVM package

**Comment by Zyrsha** [comment]
I think it needs a formula for ``brew install cling --with-llvm`` - to utilize llvm's clang and libcpp.

cling is a counterpart to clang and it is based on clang, so it would make sense to use them together if you have installed clang and cling, instead of them being incompatible.

**Comment by fxcoudert** [comment]
Thanks @Zyrsha for the report. The Mojave failure was fixed in https://github.com/Homebrew/homebrew-core/pull/33950

Regarding cling not using clang from Homebrew's llvm, I believe it is intentional.
