### ISSUE TITLE
[formula request] domterm

### ISSUE THREAD

**Issue by trusktr** [Homebrew/homebrew-core#33722]
It'd be nice to have [`domterm`] on brew. https://domterm.org

Happy to make a PR if I get a chance.

(Is there another place I should be making formula requests?)

**Comment by SMillerDev** [comment]
Formula requests are only acceptable as pull requests. The idea is that if the requester doesn't want to spend the effort crafting a formula there clearly isn't enough request for it.

Looking forward to a pull request and I'll close this one in the meantime.
