### ISSUE TITLE
rTorrent Install

### ISSUE THREAD

**Issue by dannymichel** [Homebrew/homebrew-core#338]
Last 15 lines from /Users/danny/Library/Logs/Homebrew/rtorrent/03.make:
      std::vector<torrent::File*, std::allocator<torrent::File*> >::_M_range_check(unsigned long) const in libsub_root.a(command_download.o)
      std::vector<torrent::Tracker*, std::allocator<torrent::Tracker*> >::_M_range_check(unsigned long) const in libsub_ui.a(element_tracker_list.o)
      std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::at(unsigned long) const in libsub_display.a(window_file_list.o)
      std::vector<torrent::Tracker*, std::allocator<torrent::Tracker*> >::_M_range_check(unsigned long) const in libsub_display.a(window_tracker_list.o)
  "std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      _main in main.o
      core::DownloadFactory::log_created(core::Download*, torrent::Object*)    in libsub_core.a(download_factory.o)
      core::DownloadFactory::receive_load()      in libsub_core.a(download_factory.o)
      utils::Lockfile::locked_by_as_string[abi:cxx11]() const in libsub_utils.a(lockfile.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [rtorrent] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by dunn** [comment]
Unfortunately due to the large number of build errors encountered when trying to build rtorrent and libtorrent on Mac OSX, we've removed them from Homebrew.  We're sorry for the inconvenience.
