### ISSUE TITLE
paraview failed to build on os x 10.11.5

### ISSUE THREAD

**Issue by thomasfangyi** [Homebrew/homebrew-core#3388]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

brew install paraview failed on os x 10.11.5
`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).
gist-logs at https://gist.github.com/thomasfangyi/9810b3322cfdd3581c8d1f222917e9fe

**Comment by ilovezfs** [comment]
This has already been fixed upstream: http://www.paraview.org/Bug/view.php?id=16001

If you'd like, you can open a pull request upgrading the formula to the current, fixed version. Alternatively, you can apply the patch from that link, or change the dependency to ffmpeg28 from homebrew/versions, or wait for someone else to upgrade the formula.

**Comment by ilovezfs** [comment]
Also, paraview is in homebrew/science not homebrew/core, so this issue should really be closed, and reopened here: https://github.com/Homebrew/homebrew-science/issues

**Comment by thomasfangyi** [comment]
Sorry for raising the issue in the incorrect repo. I will move this issue to science

**Comment by ilovezfs** [comment]
@thomasfangyi no problem at all. Thanks for bringing this to our attention.
