### ISSUE TITLE
Correct way to use homebrew/nvm/node in a development environment?

### ISSUE THREAD

**Issue by Zephilim** [Homebrew/homebrew-core#3393]
I have always thought it was good practice to have minimal access rights for whatever devlopment work you're doing. So that means your general developer account (the interactive logged in user) should not be an admin. My interactive account is 'kramer'. I then have another account which is an admin account, called 'homebrew'. Whenever I search for issues regarding installing packages such as Node, there is never any mention of the user that the installs are performed as and what type of account that is. So if there are any problems regarding access rights, I never know how to start resolving the issue. So my questions are:

"should I have a separate admin account that I use for performing installtions via homebrew? In this scenario, the homebrew account is only used for installations not for general development work and the homebrew account is the owner of /usr/local and /usr/loca/Cellar". (this is currently what I have tried to do, but appears to be failing me)

or:

"should my interactive user, (in my case kramer) have admin rights and also be the account I do all my development as? This option carries further risks as it means I open up my system to accidental, and possible erroneous modifications"

Essentially I would like to know what the idomatic 'correct' way of working as a developer is, in terms of installatios with homebrew.

Also, do I need to be using nvm as well as homebrew at the same time?

I have nvm installed, which looks like it is causing problems with attempts to install node via homebrew.

### The state of my currently 'broken' system is this:

- nvm installed (installed as standard user kramer)
- homebrew installed (as admin user homebrew)
- homebrew account is the owner of /usr/local and /usr/local/Cellar
- there is a long list of unbrewed header files in /usr/local/include as warned by brew doctor (but brew doctor said to ignore these, before I tried to install node via homebrew). I think these unbrewed header files are related to the fact that I have nvm installed.
- I attempted to install node using _homebrew install node_ (as user homebrew), but this failed: 

```
bash-3.2$ brew install node
==> Downloading https://homebrew.bintray.com/bottles/node-6.3.1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring node-6.3.1.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/node
Target /usr/local/bin/node
already exists. You may want to remove it:
  rm '/usr/local/bin/node'

To force the link and overwrite all conflicting files:
  brew link --overwrite node

To list all files that would be deleted:
  brew link --overwrite --dry-run node

```

So how do I fix my setup and please can you let me know the user type (admin or standard) for any operation as this is key to this requsest. Do I need nvm? It appears to be interfering with homebrew, but I thought using nvm was a sensible thing to do.

Also, I have not yet seen any comprehensive introductory information on homebrew terminology. I have seen many articles that refer to bottles, taps etc, but very little in the way of what these terms mean. Thanks

PS: this is another arfticle I wrote about the woes of installing Node:
[Node fails to install via homebrew](https://github.com/thechangelog/ping/issues/531#issuecomment-235883219
)

**Comment by MikeMcQuaid** [comment]
> Essentially I would like to know what the idomatic 'correct' way of working as a developer is, in terms of installatios with homebrew.

Use Homebrew as your default, admin user and use all software installed by Homebrew as that user too.

**Comment by Zephilim** [comment]
Hi Mike, thanks for your response. It's a litte brief however. What about nvm? What should I do with that? Stop using it and remove? And what you're saying then is that you main developer account should be an admin and install everything and do all development as an admin? Sounds dangerous to me.

**Comment by MikeMcQuaid** [comment]
> What about nvm?

I'd use the same user for nvm and Homebrew. 


> And what you're saying then is that you main developer account should be an admin and install everything and do all development as an admin?

Yes.

> And where is there comprehensive infomation on Homebrew?

You'll have to be a lot more specific.
