### ISSUE TITLE
Swift toolchain has broken SourceKit

### ISSUE THREAD

**Issue by egorzhdan** [Homebrew/homebrew-core#33960]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to install Swift toolchain using brew by running `brew install swift`.

- What happened (include command output)

Swift toolchain was installed, brew didn't print any errors. However the toolchain is broken – more specifically, SourceKit does not include `SourceKitService.xpc` file (`<toolchain>/usr/lib/sourcekitd.framework/XPCServices/`) which is present in all Apple's toolchains (OSS & Xcode) and is required for SourceKit to work properly.

Right now SourceKit crashes on first request, presumably, because the client part cannot connect to the backend (which is missing):
~~~
Assertion failed: (GlobalConn), function getGlobalConnection, file /tmp/swift-20180809-59536-drjj2h/swift/tools/SourceKit/tools/sourcekitd/bin/XPC/Client/sourceAssertion failed: (GlobalConn), function getGlobalConnection, file /tmp/swift-20180809-59536-drjj2h/swift/tools/SourceKit/tools/sourcekitd/bin/XPC/Client/sourcekitd.cpp, line 336.
Assertion failed: (GlobalConn), function getGlobalConnection, file /tmp/swift-20180809-59536-drjj2h/swift/tools/SourceKit/tools/sourcekitd/bin/XPC/Client/sourcekitd.cpp, line 336.
kitd.cpp, line 336.
~~~
thrown from here: https://github.com/apple/swift/blob/master/tools/SourceKit/tools/sourcekitd/bin/XPC/Client/sourcekitd.cpp#L318

https://gist.github.com/egorzhdan/e6b5a4b0f8d8f528045155f325da0019

- What you expected to happen

I expect SourceKit XPC version to be included in the toolchain, since it is included in all Apple's toolchains.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install swift
cd "/usr/local/Cellar/swift/4.1.3/Swift-4.1.3.xctoolchain/usr/lib/sourcekitd.framework"
```

**P.S.**
AFAIU Swift build script can only build either XPC or in-proc version at once. Since the formula includes `sourcekit-inproc` argument (why? in-proc version is not included in toolchains on macOS) the script doesn't build XPC version. 
https://github.com/apple/swift/blob/master/tools/CMakeLists.txt#L6

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by fxcoudert** [comment]
We have updated swift to 4.2.1. If the issue isn't fixed, we'd appreciate a pull request. Right now we use both `sourcekit-inproc` and `sourcekit-xpc-service` as components.

**Comment by egorzhdan** [comment]
The issue is present in 4.2.1, so I've created a PR – #34516.

**Comment by fxcoudert** [comment]
Thanks @egorzhdan!
