### ISSUE TITLE
Downloading sox source code fails

### ISSUE THREAD

**Issue by hmage** [Homebrew/homebrew-core#3398]
```
hmage@iiHMD:~$ brew install sox --with-flac --with-lame --with-libao --with-libsndfile --with-libvorbis --with-opusfile --with-opencore-amr
==> Downloading https://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2.tar.gz
==> Downloading from http://downloads.sourceforge.net/#!/project/sox/sox/14.4.2/sox-14.4.2.tar.gz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: b45f598643ffbd8e363ff24d61166ccec4836fea6d3888881b8df53e3bb55f6c
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Users/hmage/Library/Caches/Homebrew/sox-14.4.2.tar.gz
To retry an incomplete download, remove the file above.
```

The file that sourceforge gives out is actually an HTML page:

```
hmage@iiHMD:~$ curl -L https://downloads.sourceforge.net/project/sox/sox/14.4.2/sox-14.4.2.tar.gz
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'http://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

It seems to me that whenever they are DDoS'ed they ban all bots, including homebrew downloaders.

That's very unfortunate because about 500 formulas download source code from there:
```
hmage@iiHMD:/usr/local/Library/Formula$ git grep -l 'url .*sourceforge.net'|wc -l
     521
```

In case of sox, adding a mirror URL should help.

**Comment by DomT4** [comment]
> It seems to me that whenever they are DDoS'ed they ban all bots, including homebrew downloaders.

Not necessarily a DDoS with SF. SF is prone to breaking on a regular basis, for a variety of reasons, which is a large part of why Homebrew moved our own binaries (bottles) to Bintray a fair while ago now. Sadly, we are entirely powerless as to where upstream developers choose to host their projects.

They block download functionality on the website at times when things break, and `curl` _(which Homebrew's `fetch` uses)_ and other downloader tools are redirected to the failure HTML page as noted.

I can no longer reproduce this, so they may have resolved it. Can you check again? Thanks.

**Comment by hmage** [comment]
Yes, SF is correctly sending redirects to curl now.

Maybe, as a long term plan, mirror the sources too?

**Comment by DomT4** [comment]
Bintray provide us with a significant amount of free storage, and we mirror a couple handfuls of source tarballs known to be gone upstream or have regular issues upstream, but the feeling amongst the team is that we'd be taking liberties with their generosity if we mirror _a lot_ of upstream packages. The entire SF archive would definitely qualify as "a lot".

It's worthwhile talking to upstreams about SF & whether they've considered alternatives, essentially.
