### ISSUE TITLE
Unsupported special dependency :maximum_macos

### ISSUE THREAD

**Issue by Existence01** [Homebrew/homebrew-core#33999]
▶ brew install wine
Error: Unsupported special dependency :maximum_macos
Please report this bug:
  https://docs.brew.sh/Troubleshooting.html
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:120:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/compat/dependency_collector.rb:64:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:88:in `parse_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:52:in `build'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:29:in `add'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:165:in `depends_on'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:42:in `block in <class:Wine>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2145:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2145:in `head'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:33:in `<class:Wine>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:7:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:453:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:47:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:43:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:115:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

OS:
macOS High Sierra 10.13.6 (17G65)
Homebrew 1.5.4
Homebrew/homebrew-core (git revision 6f74a; last commit 2018-11-11)

**Comment by SMillerDev** [comment]
Your homebrew is a very old version, you need to run `brew update`

**Comment by fxcoudert** [comment]
If `brew update` does not fix it, `brew update-reset` is the second step to try.
To help you further we would need a full description of the issue, as requested by the issue template, which needs to be filled.
