### ISSUE TITLE
P7zip

### ISSUE THREAD

**Issue by stieglitz16** [Homebrew/homebrew-core#33990]
Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by SMillerDev** [comment]
As the template you posted already says, please fill out one of the templates at https://github.com/Homebrew/homebrew-core/issues/new/choose
