### ISSUE TITLE
Install duply 1.11.3

### ISSUE THREAD

**Issue by SchwarzM** [Homebrew/homebrew-core#3399]
brew install duply
currently leads to:
Error: SHA256 mismatch
Expected: 585757a02abc91bcc0e37004eef735794d6581d1a30ec68303c6c04833b20940
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
 
anybody else with that problem ?

**Comment by ilovezfs** [comment]
```
$ openssl dgst -sha256 <(curl -s -L https://downloads.sourceforge.net/project/ftplicity/duply%20%28simple%20duplicity%29/1.11.x/duply_1.11.3.tgz)
SHA256(/dev/fd/63)= 585757a02abc91bcc0e37004eef735794d6581d1a30ec68303c6c04833b20940
```
Nope.

```
brew fetch --retry duply
```
should fix it.

**Comment by DomT4** [comment]
SF had some downtime yesterday. That was probably the cause for the original error.
