### ISSUE TITLE
passenger failed to build on 10.14.1

### ISSUE THREAD

**Issue by cmoel** [Homebrew/homebrew-core#34002]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/PicoDasRobot/2aa2141f4200bfad50acce1fc87c0061
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? `brew gist-logs` worked

To help us debug your issue please explain:
- What you were trying to do (and why)
  Run `brew upgrade passenger` to get on the latest version
- What happened (include command output)
  I made a gist of the output from running `brew upgrade passenger` here: https://gist.github.com/cmoel/adf1097f82e6133904aadd744af2a1ee
- What you expected to happen
  I expected passenger to successfully update
- Step-by-step reproduction instructions (by running `brew install` commands)
  - `brew update`
  - `brew outdated`
  - `brew upgrade passenger`

**Comment by MikeMcQuaid** [comment]
@cmoel Can you `brew update` this and try again? This may have been fixed by https://github.com/Homebrew/homebrew-core/pull/34060

**Comment by cmoel** [comment]
Thanks @MikeMcQuaid. I ran `brew update` and `brew upgrade passenger` and it failed again. The last line output before the failure was `==> rake nginx`. Here are the results of `brew gist-logs passenger`: https://gist.github.com/5a89150dafd0289ba7fb23d880c733ca.

How else can I help with this issue?

**Comment by MikeMcQuaid** [comment]
You may want to ask the passenger project directly.

**Comment by CamJN** [comment]
@cmoel https://gist.github.com/PicoDasRobot/5a89150dafd0289ba7fb23d880c733ca#file-01-rake-L456 passenger can't find alloca.h, which should have been provided by xcode. I don't know why it didn't put it in place but that's what you should look into.

**Comment by felixbuenemann** [comment]
I have the same error, and alloca.h exists in both `/usr/include/alloca.h` and `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/alloca.h`.

**Comment by cmoel** [comment]
I've also verified alloca.h exists in both `/usr/include/alloca.h` and `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/alloca.h` but I'm not sure how to make sure it's included when building `passenger`.

**Comment by CamJN** [comment]
Well, we leave finding alloca.h to ruby, it's literally just [`mkmf`'s `have_header`](http://ruby-doc.org/stdlib-2.5.0/libdoc/mkmf/rdoc/MakeMakefile.html#method-i-have_header) method. What happens if you run `ruby -rmkmf -e 'puts have_header("alloca.h")'` outside of homebrew?

**Comment by cmoel** [comment]
It looks like it finds it successfully:
```
$ ruby -rmkmf -e 'puts have_header("alloca.h")'
checking for alloca.h... yes
true
```
Maybe there's some other context where ruby isn't finding the header? I attempted `brew upgrade passenger` again immediately after running `ruby -rmkmf -e 'puts have_header("alloca.h")'` and it failed again for the same reason: https://gist.github.com/PicoDasRobot/9b12cd289cb5733a2ac917e365c9e1bc#file-01-rake-L457.

**Comment by CamJN** [comment]
That's pretty weird, @MikeMcQuaid any ideas why mkmf can find the header outside homebrew but not inside?

**Comment by cmoel** [comment]
I just confirmed by running this:
```
$ /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -rmkmf -e 'puts have_header("alloca.h")'
checking for alloca.h... /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:524:in `with_werror'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
        from -e:1:in `<main>'

```

**Comment by MikeMcQuaid** [comment]
Our build environment and compiler flag handling is different to the macOS default. Can’t provide more help than that, sorry.

**Comment by CamJN** [comment]
Then I'll attribute this to one of those differences. Sorry guys.

**Comment by MikeMcQuaid** [comment]
There's also the `brew doctor` warnings and the option that could cause this. I'd recommend avoiding the option and therefore not building from source (and the option will be removed in future anyway).

**Comment by CamJN** [comment]
That's a good point, @cmoel can you remove the rbenv passenger shim and try again?

**Comment by seven1m** [comment]
On my machine, the problem was not a missing `alloca.h` (that header file was just checked first)... the problem was a missing `ruby/config.h` which is a [known Mojave issue](https://stackoverflow.com/questions/53135863/macos-mojave-ruby-config-h-file-not-found). The [answer here](https://stackoverflow.com/questions/53135863/macos-mojave-ruby-config-h-file-not-found) fixed the problem for me and I was then able to install Passenger as usual.

**Comment by cmoel** [comment]
🙌 That solved it for me. Thanks @seven1m!
