### ISSUE TITLE
Diffoscope depends on progressbar for reporting progress

### ISSUE THREAD

**Issue by thedrow** [Homebrew/homebrew-core#34031]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Invoke diffoscope with the `--progress` option.
- What happened (include command output)
Got the following error:
```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/diffoscope/104/libexec/lib/python3.7/site-packages/diffoscope/main.py", line 467, in main
    log_handler = ProgressManager().setup(parsed_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/diffoscope/104/libexec/lib/python3.7/site-packages/diffoscope/progress.py", line 77, in setup
    bar = ProgressBar()
  File "/home/linuxbrew/.linuxbrew/Cellar/diffoscope/104/libexec/lib/python3.7/site-packages/diffoscope/progress.py", line 194, in __init__
    import progressbar
```
- What you expected to happen
Diffoscope should report progress
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install diffoscope
diffoscope --progress dir1/ dir2/
```

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/34058
