### ISSUE TITLE
 atlassian-cli #ArgumentError: parent directory is world writable but not sticky

### ISSUE THREAD

**Issue by chukka** [Homebrew/homebrew-core#34051]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
```
Already couple of  issues exist in Discourse :
https://discourse.brew.sh/t/argumenterror-parent-directory-is-world-writable-but-not-sticky/3041
https://discourse.brew.sh/t/parent-directory-is-world-writable-but-not-sticky/3386/4

```
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
```
Logs : 
$ brew doctor
Your system is ready to brew.
```
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install atlassian-cli
- What happened (include command output)
```
brew install -d atlassian-cli 
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/atlassian-cli.rb
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java -version
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java -version
/usr/local/Homebrew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/atlassian-cli.rb
/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/bin/java -version
==> Downloading https://bobswift.atlassian.net/wiki/download/attachments/16285777/atlassian-cli-8.0.0-distribution.zip
/usr/bin/curl -q --show-error --user-agent Homebrew/1.8.2\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.1\)\ curl/7.54.0 --location --silent --head https://bobswift.atlassian.net/wiki/download/attachments/16285777/atlassian-cli-8.0.0-distribution.zip
Already downloaded: /Users/test/Library/Caches/Homebrew/downloads/ea225576eb32454b139b5a7da4e231c2cab091600774448c21cadb46a1a02066--name=atlassian-cli-8.0.0-distribution.zip
unzip -qq /Users/test/Library/Caches/Homebrew/downloads/ea225576eb32454b139b5a7da4e231c2cab091600774448c21cadb46a1a02066--name=atlassian-cli-8.0.0-distribution.zip -d /private/tmp/d20181114-29867-o7u7sg
cp -pR /private/tmp/d20181114-29867-o7u7sg/atlassian-cli-8.0.0/. /private/tmp/atlassian-cli-20181114-29867-acngel/atlassian-cli-8.0.0
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
ArgumentError: parent directory is world writable but not sticky
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 


$ brew doctor
Your system is ready to brew.

$ brew config
HOMEBREW_VERSION: 1.8.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6f458aaed494eaab92622f41f9f1967add00b0f4
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3df860f0748c32d38933c90d6344665fb3e0a29f
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_171, 1.8.0_161
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```
- What you expected to happen
successful install of atlassian-cli
- Step-by-step reproduction instructions (by running `brew install` commands)
` $ brew install atlassian-cli`

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/brew/issues/5324 where there's more discussion.
