### ISSUE TITLE
x264 with mp4 support?

### ISSUE THREAD

**Issue by dzg** [Homebrew/homebrew-core#34050]
How can I install x264 with MP4 support?

I tried `--with-l-smash`, `--with-10-bit`, `--with-mp4=gpac` but nothing works

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
