### ISSUE TITLE
Dovecot 2.3.2.1 fables to start - "Group doesn't exist: dovecot"

### ISSUE THREAD

**Issue by jameslbrown** [Homebrew/homebrew-core#34158]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I've managed to install Dovecot 2.3.2.1 using: brew install dovecot --build-from-source

See [https://discourse.brew.sh/t/add-options-to-configure-in-formula-dovecot-with-mysql/2655/6]

When I start Dovecot I get:

> Fatal: service(stats) Group doesn't exist: dovecot (See service stats { unix_listener /usr/local/var/run/dovecot/stats-writer { group } } setting)

This was discussed and closed back in April 2018. Is there anything that can be done? 

default_login_user = _dovenull
default_internal_user = _dovecot

Do we just have to create a user 'dovecot'? Ie no underscore at the front.

**Comment by MikeMcQuaid** [comment]
> Do we just have to create a user 'dovecot'?

Yes.

We could adjust the configuration in `post_install`, though, so it uses the default user instead? If you're interested in that: could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by jameslbrown** [comment]
> On 17 Nov 2018, at 6:31 am, Mike McQuaid <notifications@github.com> wrote:
> 
> Do we just have to create a user 'dovecot'?
> 
> Yes.
> 
> We could adjust the configuration in post_install, though, so it uses the default user instead? If you're interested in that: could you try and open a pull request? This document <https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request> should help and we're happy to walk you through anything else.
> 
> Thanks!
> 
Thanks Mike.

I don’t know enough to do the post_install pull request - it’s a bit beyond my capabilities. I’m not sure what to put In the def post_install.

I’ll just have to create a ‘dovecot’ user.
