### ISSUE TITLE
Warning: ldap_start_tls(): Unable to start TLS

### ISSUE THREAD

**Issue by nohnaimer** [Homebrew/homebrew-core#34181]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
macOS Mojave 10.14.1, php 7.2.12 configured:
`
./configure’ ‘–prefix=/usr/local/Cellar/php/7.2.12’ ‘–localstatedir=/usr/local/var’ ‘–sysconfdir=/usr/local/etc/php/7.2’ ‘–with-config-file-path=/usr/local/etc/php/7.2’ ‘–with-config-file-scan-dir=/usr/local/etc/php/7.2/conf.d’ ‘–with-pear=/usr/local/Cellar/php/7.2.12/share/php/pear’ ‘–enable-bcmath’ ‘–enable-calendar’ ‘–enable-dba’ ‘–enable-dtrace’ ‘–enable-exif’ ‘–enable-ftp’ ‘–enable-fpm’ ‘–enable-intl’ ‘–enable-mbregex’ ‘–enable-mbstring’ ‘–enable-mysqlnd’ ‘–enable-opcache-file’ ‘–enable-pcntl’ ‘–enable-phpdbg’ ‘–enable-phpdbg-webhelper’ ‘–enable-shmop’ ‘–enable-soap’ ‘–enable-sockets’ ‘–enable-sysvmsg’ ‘–enable-sysvsem’ ‘–enable-sysvshm’ ‘–enable-wddx’ ‘–enable-zip’ ‘–with-apxs2=/usr/local/opt/httpd/bin/apxs’ ‘–with-bz2=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-fpm-user=_www’ ‘–with-fpm-group=_www’ ‘–with-freetype-dir=/usr/local/opt/freetype’ ‘–with-gd’ ‘–with-gettext=/usr/local/opt/gettext’ ‘–with-gmp=/usr/local/opt/gmp’ ‘–with-icu-dir=/usr/local/opt/icu4c’ ‘–with-jpeg-dir=/usr/local/opt/jpeg’ ‘–with-kerberos=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-layout=GNU’ ‘–with-ldap-sasl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-libxml-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-libedit=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-libzip’ ‘–with-mhash=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-mysql-sock=/tmp/mysql.sock’ ‘–with-mysqli=mysqlnd’ ‘–with-ndbm=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-openssl=/usr/local/opt/openssl’ ‘–with-password-argon2=/usr/local/opt/argon2’ ‘–with-pdo-dblib=/usr/local/opt/freetds’ ‘–with-pdo-mysql=mysqlnd’ ‘–with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc’ ‘–with-pdo-pgsql=/usr/local/opt/libpq’ ‘–with-pdo-sqlite=/usr/local/opt/sqlite’ ‘–with-pgsql=/usr/local/opt/libpq’ ‘–with-pic’ ‘–with-png-dir=/usr/local/opt/libpng’ ‘–with-pspell=/usr/local/opt/aspell’ ‘–with-sodium=/usr/local/opt/libsodium’ ‘–with-sqlite3=/usr/local/opt/sqlite’ ‘–with-tidy=/usr/local/opt/tidy-html5’ ‘–with-unixODBC=/usr/local/opt/unixodbc’ ‘–with-webp-dir=/usr/local/opt/webp’ ‘–with-xmlrpc’ ‘–with-xsl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-zlib=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-curl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr’ ‘–with-ldap=/usr/local/opt/openldap’ ‘–with-iconv=/usr/local/opt/libiconv’
`
and installed without warnings and errors
- What happened (include command output)
Simple script to connect Ad Ldap:
```
<?php
$con =  ldap_connect('serverAD.test.com', 389);
ldap_set_option($con, LDAP_OPT_PROTOCOL_VERSION, 3);
ldap_set_option($con, LDAP_OPT_REFERRALS, 0);
if ($con) {
	echo "Соединение успешно установлено...<br />";
} else {
     echo "Соединение не удалось...<br />";
}
$ldapbind=false;
if (ldap_start_tls($con😂 {
 	$ldapbind = ldap_bind($con, 'user@test.com', 'Password');
}
ldap_close($con);
if(!$ldapbind)
    echo "ERROR";
else
	echo "OK";
?>
```
- What you expected to happen
![2018-11-16 18 51 57](https://user-images.githubusercontent.com/8865830/48631945-bd1c0680-e9d0-11e8-8374-f7e2a3089748.png)
- Step-by-step reproduction instructions (by running `brew install` commands)
But if I try connect on terminal use command:
```
ldapsearch -D "user@test.com" -W -p 389 -h srv1.test.com -b “DC=test,DC=com” -s sub -x -Z “(sAMAccountName=filter)”
```
everything work fine (that is, openldap client and openssl nothing to do with)

Any idea what might be wrong?

**Comment by MikeMcQuaid** [comment]
This doesn't seem to be a Homebrew issue.

**Comment by nohnaimer** [comment]
Why? On Linux same configuration works fine!
CentOS 7 x64 nginx + php-fpm 7.2.12

**Comment by kabel** [comment]
@nohnaimer The issue was likely closed because you didn't provide compelling evidence that what you are experiencing is a failure that can be attributed to how the package is built. A more likely explanation is that there is some kind of configuration or run-time conflict that explains what you're seeing. In any case, your issue report becomes more of a support request for the upstream software rather than something actionable the package maintainers can try to fix.

That said, there are some known issues with mixed LDAP and crypto implementations in the Mojave php package that we're trying to [address](https://github.com/Homebrew/homebrew-core/pull/33909).

The `ldapsearch` command you are using is likely `/usr/bin/ldapsearch` which is the macOS system's binary. That uses a different ldap implementation than what we have in the php package. It also contains a different crypto (TLS) implementation. I'm curious if you reran `ldapsearch` with `-ZZ` instead of `-Z`, as the latter will silently ignore StartTLS failures and your PHP script does not. Also to compare apples to apples, you'd want to use the `/usr/local/opt/openldap/bin/ldapsearch` binary to accurately test the ldap library that's used in the php package.

That's the best support advice I can give, other than that it's up to you to debug and try to diagnose why there were TLS connection issues.

**Comment by nohnaimer** [comment]
@kabel thanks bro. You right! macOS openldap was configured correctly, but another was used in php! After adding **TLS_REQCERT	never** in /usr/local/etc/openldap/ldap.conf it all worked!

Thanks for helping!
