### ISSUE TITLE
Unable to build qt

### ISSUE THREAD

**Issue by metawade** [Homebrew/homebrew-core#34241]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I need to install xpdf, which needs qt
  
- What happened (include command output)

See https://gist.github.com/318cbbf23eefafb9c4aea73421f496c3

Last 15 lines from /Users/wmh/Library/Logs/Homebrew/qt/02.make:

See //build/config/sysroot.gni:62:3: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
See //BUILD.gn:69:5: which caused the file to be included.
    "//net:net_unittests",
    ^--------------------
Command ... snipped ... returned non-zero exit status 1
Building gn manually in a temporary directory for bootstrapping...
Building gn using itself to out/Release...
Project ERROR: GN build error!
make[3]: *** [sub-gn-pro-make_first] Error 3
make[2]: *** [sub-buildtools-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2

- What you expected to happen

For qt to be installed without error.

- Step-by-step reproduction instructions (by running `brew install` commands)

% brew install qt
... wait for an hour

Note that this is similar to https://github.com/Homebrew/homebrew-core/issues/21809 and https://github.com/Homebrew/homebrew-core/issues/31309.

I am unable to use /usr/local as my prefix for the same reasons as cited in 21809. 
Note that 31309 was closed due to lack of response from OP. I'm having a similar issue.

**Comment by MikeMcQuaid** [comment]
> I am unable to use /usr/local as my prefix for the same reasons as cited in 21809.

Sorry, that's our supported configuration. We'll accept pull requests to fix this.
