### ISSUE TITLE
TTFAutoHint upgrade fails

### ISSUE THREAD

**Issue by DPattee** [Homebrew/homebrew-core#34257]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/6efa53cd73bd39373052d91846a9ba3a
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to upgrade TTFAutoHint from 1.6 to 1.8.2, because it is the only remaining out of date package when running brew upgrade
- What happened (include command output)

    ==> Upgrading 1 outdated package:
    ttfautohint 1.6 -> 1.8.2
    ==> Upgrading ttfautohint --with-qt
    ==> Downloading https://downloads.sourceforge.net/project/freetype/ttfautohint/1.8.2/ttfautohint-1.8.2.tar.gz
    Already downloaded: /Users/xcaiver/Library/Caches/Homebrew/downloads/5d6093004d37d21251be7fac840fba291eb992d8546c9b795f4c51ebd723c3c3--ttfautohint-1.8.2.tar.gz
    ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/ttfautohint/1.8.2 --without-doc
    Last 15 lines from /Users/xcaiver/Library/Logs/Homebrew/ttfautohint/01.configure:
    checking whether wcsstr is declared without a macro... yes
    checking whether wcstok is declared without a macro... yes
    checking whether wcswidth is declared without a macro... yes
    checking whether wcsftime is declared without a macro... yes
    checking for stdint.h... (cached) yes
    checking for HARFBUZZ... yes
    checking for qmake... /usr/local/opt/qt/bin/qmake
    checking for moc... /usr/local/opt/qt/bin/moc
    checking for uic... /usr/local/opt/qt/bin/uic
    checking for rcc... /usr/local/opt/qt/bin/rcc
    checking whether host operating system is Darwin... yes
    checking whether QMAKESPEC environment variable is set... no, using -spec macx-g++
    Info: creating stash file /private/tmp/ttfautohint-20181118-68764-4temow/ttfautohint-1.8.2/conftest.dir/.qmake.stash
    Project ERROR: failed to parse default search paths from compiler output
    configure: error: Calling /usr/local/opt/qt/bin/qmake -spec macx-g++ failed.

- What you expected to happen
For the upgrade to succeed...
- Step-by-step reproduction instructions (by running `brew install` commands)
brew upgrade ttfautohint

https://gist.github.com/6efa53cd73bd39373052d91846a9ba3a

**Comment by MikeMcQuaid** [comment]
Does this work without `--with-qt`?

**Comment by DPattee** [comment]
The --with-qt is coming from 'somewhere'... The actual command I entered was just '_brew upgrade ttfautohint_'

Even if I enter '_brew upgrade ttfautohint --without-qt_' (which should be a valid parameter) that gets stripped and it still adds the --with-qt back in:

 ```
 ~    brew upgrade ttfautohint --without-qt
==> Upgrading 1 outdated package:
ttfautohint 1.6 -> 1.8.2
==> Upgrading ttfautohint --with-qt
==> Downloading https://downloads.sourceforge.net/project/freetype/ttfautohint/1.8.2/ttfautohint-1.8.2.tar.gz
Already downloaded: /Users/xcaiver/Library/Caches/Homebrew/downloads/5d6093004d37d21251be7fac840fba291eb992d8546c9b795f4c51ebd723c3c3--ttfautohint-1.8.2.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/ttfautohint/1.8.2 --without-doc
Last 15 lines from /Users/xcaiver/Library/Logs/Homebrew/ttfautohint/01.configure:
checking whether wcsstr is declared without a macro... yes
checking whether wcstok is declared without a macro... yes
checking whether wcswidth is declared without a macro... yes
checking whether wcsftime is declared without a macro... yes
checking for stdint.h... (cached) yes
checking for HARFBUZZ... yes
checking for qmake... /usr/local/opt/qt/bin/qmake
checking for moc... /usr/local/opt/qt/bin/moc
checking for uic... /usr/local/opt/qt/bin/uic
checking for rcc... /usr/local/opt/qt/bin/rcc
checking whether host operating system is Darwin... yes
checking whether QMAKESPEC environment variable is set... no, using -spec macx-g++
Info: creating stash file /private/tmp/ttfautohint-20181119-70557-13tkl74/ttfautohint-1.8.2/conftest.dir/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
configure: error: Calling /usr/local/opt/qt/bin/qmake -spec macx-g++ failed.

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
TTFAutoHint upgrade fails https://github.com/Homebrew/homebrew-core/issues/34257

 ~  
```

I worry that if I uninstall the older version and clean install the newer version that I'll lose the repro for the bug, even if I uninstall/reinstall the older version directly again

**Comment by MikeMcQuaid** [comment]
@DPattee Yes, we maintain options on upgrade. If you don't need the `--with-qt` option you could consider doing `brew uninstall ttfautohint; brew install ttfautohint` which may resolve your issue.

**Comment by DPattee** [comment]
Yea uninstalling and installing without the --with-qt works. Even fresh installs trying to have --with-qt are broken though. Same error as the upgrade I was trying earlier.

**Comment by lemzwerg** [comment]
@MikeMcQuaid: Mike, while I appreciate that you keep homebrew running I wonder why the homebrew team (or the OP) didn't contact me as the upstream maintainer so that I can try to fix this...

Without being able to test I guess that the problem is a modification of homebrew itself. Please have a look at https://github.com/Homebrew/homebrew-core/pull/30429; you can see that originally I set `QMAKESPEC='macx-clang'` to make the configure script select the proper Qt spec file, and that I was asked to remove it since homebrew was able to handle this by itself.  Looking at the OP reports it seems that setting `QMAKESPEC` is necessary again...

@anthrotype, could you test the formula before commit 0998b4eb8b1a2cc50c0fa4b3ae78eecfa519847f whether the modification of the abovementioned pull request works?

BTW, what must I do to be automatically informed if there are problems with `ttfautohint.rb`?

**Comment by anthrotype** [comment]
@lemzwerg ok, i'll try to build the previous formula with the `--with-qt` option by inserting `QMAKESPEC='macx-clang'` and see if it works (i first need to update xcode 10).

@SMillerDev the option was useful because it allowed to easily build the GUI version of ttfautohint. It would be good to restore it.

**Comment by lemzwerg** [comment]
What about splitting off a `ttfautohint-GUI.rb` formula?
