### ISSUE TITLE
Requesting adding OpenFOAM 

### ISSUE THREAD

**Issue by luzpaz** [Homebrew/homebrew-core#34327]
FreeCAD may soon need OpenFOAM as a dependency. We're trying to get more adoption of this application in to the package ecosystem.
Currently we're tracking it via repology:
Could we get it added to homebrew (and subsequently linuxbrew) ?

[![Packaging status](https://repology.org/badge/vertical-allrepos/openfoam.svg)](https://repology.org/metapackage/openfoam/versions)

**Comment by SMillerDev** [comment]
So, the template you removed to post your own text has some instructions on how to get software added to homebrew. I'm going to close this issue since it doesn't use the template.

**Comment by luzpaz** [comment]
I'm not on OSX or I would of made a PR @SMillerDev

**Comment by SMillerDev** [comment]
You could always base your PR on linuxbrew and see the macOS status in Jenkins.
