### ISSUE TITLE
mosh: block transient dependency on python@2 via protobuf

### ISSUE THREAD

**Issue by javabrett** [Homebrew/homebrew-core#34345]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
`brew install mosh` to install `mosh` and its true dependencies (`protobuf`).

- What happened (include command output)
First thing installed is the (`recommended`) `protobuf` dependency `python@2`:
```
 brew install mosh
==> Installing dependencies for mosh: python@2 and protobuf
==> Installing mosh dependency: python@2
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.15_1.high_sierra.bottle.6.tar.gz
----- >-8 ----- >-8 -----
```

- What you expected to happen
I expect bottles for `mosh` and its dependency `protobuf` to be installed.  I don't expect `python@2` to be installed, since it is only a `recommended` for `protobuf`, and `mosh` doesn't need it at all.  As far as `mosh` is concerned, `python@2` is a bunch of old bloat.

- Step-by-step reproduction instructions (by running `brew install` commands)
` brew install mosh`

See also: https://discourse.brew.sh/t/mosh-recipe-avoiding-python-2-via-protobuf/3466

**Comment by MikeMcQuaid** [comment]
This is intentional behaviour. `:recommended` dependencies are used by default. It's likely this dependency becomes a default dependency in future: https://github.com/Homebrew/homebrew-core/issues/31510.

**Comment by zbeekman** [comment]
IMO, It might also be worth examining why python packages are recommending python@2 as we go through and remove options. It may indeed make sense in some cases to remove the python@2 dependencies if there is not a compelling reason to have them. This, however, should be examined as part of efforts in #31510.

**Comment by MikeMcQuaid** [comment]
> IMO, It might also be worth examining why python packages are recommending python@2 as we go through and remove options.

In general if they use the network the system Python isn't set up for sufficiently new TLS. If they don't it may be for bindings with the newer Python.

**Comment by javabrett** [comment]
The very first question that should be asked of any `python@2` dependency or option is - why is it not `python` (3).  Python 2 is approaching EOL, see https://pythonclock.org/ .  If packages have some hard dependency on Python 2, they need to fix that.  If not, they should be moved to Python 3.  Perhaps a separate issue is warranted.

If I knew either protobuf or homebrew better, I would probably claim that the posture on this issue is now that `protobuf` should be decomposed into `protobuf` and `protobuf-python@2`/`protobuf-python`.  Does that sound right?

Looks like protobuf is just assuming that Python is popular-enough that the client for it should be built and installed, and that it should default to Python 2.  There's a unrelated Python notes in https://github.com/protocolbuffers/protobuf/blob/master/python/README.md .
