### ISSUE TITLE
qt has reference to xcode-beta.app directory

### ISSUE THREAD

**Issue by dvj** [Homebrew/homebrew-core#34340]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Linking `qt` libraries with cmake
- What happened (include command output)
```
CMake Error at /usr/local/Cellar/qt/5.11.2/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "gl.h" in
  "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers;/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers".
```
- What you expected to happen
find `gl.h`
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install qt`
grep beta /usr/local/Cellar/qt/5.11.2/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake

Installing `qt` has a cmake file with a path to `/Applications/xcode-beta.app/...`. This leads to problems if using the non-beta version of XCode.

Solution: Produce bottle with updated XCode, and have `/usr/local/Cellar/qt/5.11.2/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake` reference `/Applications/xcode.app/...`

**Comment by SMillerDev** [comment]
If it's just a bottle rebuild. Could you make a pull request that adds `revision 1` (or higher if it already has a revision) underneath the version in the QT formula?

**Comment by fxcoudert** [comment]
Issue fixed in 
https://github.com/Homebrew/homebrew-core/commit/19c03632bc67fea99563ce0c6563e2eab167e61b
