### ISSUE TITLE
TomeePlus

### ISSUE THREAD

**Issue by ThPetillot** [Homebrew/homebrew-core#34353]
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "tomee-plus"
Download failed: https://www-us.apache.org/dist/tomee/tomee-1.7.4/apache-tomee-1.7.4-plus.tar.gz

**Comment by SMillerDev** [comment]
Could you fill out the issue template? The questions on there are pretty essential in figuring out what is wrong. I'm going to close this issue until you fill out the issue template.
