### ISSUE TITLE
MisterTea/et/et failed to build on 10.14.1

### ISSUE THREAD

**Issue by shivanker** [Homebrew/homebrew-core#34358]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
## What you were trying to do (and why)

Trying to install the formula [MisterTea/et/et](https://github.com/MisterTea/homebrew-et/) after updating to MacOS 10.14.1. I know it's a third-party formula, but the original author is not able to reproduce the issue and there is no problem manually building from source. (the issue is being tracked at https://github.com/MisterTea/homebrew-et/issues/5 too) We're kind of at a loss here, and looking for help from the brew core community.

## What happened (include command output)

brew update failed on this formula after upgrading to MacOS 10.14.1. Uninstalling and reinstalling didn't help - here is the full gist for logs - https://gist.github.com/shivanker/e5699e431e55041b81841a6a18bbbcc0

The failure happens at:
```
[ 93%] Linking CXX executable etserver
/usr/local/Cellar/cmake/3.12.4/bin/cmake -E cmake_link_script CMakeFiles/etserver.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -DET_VERSION='"5.1.8"' -DELPP_NO_DEFAULT_LOG_FILE -DELPP_FEATURE_CRASH_LOG -DELPP_THREAD_SAFE -DELPP_HANDLE_SIGABRT -Wall -std=c++11 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/etserver.dir/src/terminal/TerminalServer.cpp.o CMakeFiles/etserver.dir/src/terminal/UserTerminalRouter.cpp.o  -o etserver libTerminalCommon.a libet-lib.a /usr/local/lib/libprotobuf.dylib /usr/local/lib/libgflags.dylib /usr/local/lib/libsodium.dylib -lutil -lresolv
Undefined symbols for architecture x86_64:
  "el::Configuration::Configuration(el::Configuration const&)", referenced from:
   ...
```

## Step-by-step reproduction instructions

On MacOS 10.14.1, with XCode 10.1 and latest CLT,
`brew install MisterTea/et/et`

**Comment by MikeMcQuaid** [comment]
> Trying to install the formula [MisterTea/et/et](https://github.com/MisterTea/homebrew-et/) after updating to MacOS 10.14.1. I know it's a third-party formula, but the original author is not able to reproduce the issue and there is no problem manually building from source. (the issue is being tracked at [MisterTea/homebrew-et#5](https://github.com/MisterTea/homebrew-et/issues/5) too) We're kind of at a loss here, and looking for help from the brew core community.

Sorry, we cannot support third-party formulae here.
