### ISSUE TITLE
Vsts-cli bottle checksum failure after package update in PR 34037

### ISSUE THREAD

**Issue by atbagga** [Homebrew/homebrew-core#34398]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Reproductions Steps:**

brew install vsts-cli 
There is a checksum failure on the bottle on installing on high-sierra.
Is this due to CI issue we  were facing? INstallation does finish by source build and work eventually. 

**Logs here for reference:** 
Atuls-MBP: atbagga$ brew install vsts-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 05e670e1b to 158a34bda.
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
fx                                                                                                     kubespy
==> Updated Formulae
vsts-cli ✔                                                                                             pulumi

Warning: vsts-cli 0.1.3 is already installed and up-to-date
To reinstall 0.1.3, run `brew reinstall vsts-cli`
Atuls-MBP: atbagga$ brew reinstall vsts-cli
==> Reinstalling vsts-cli 
==> Downloading https://homebrew.bintray.com/bottles/vsts-cli-0.1.3.high_sierra.bottle.tar.gz
######################################################################## 100.0%
**Error: SHA256 mismatch
Expected: f581e56644210416738424264db59d1264e40959d7a24dc762fce10b385f3650
Actual: 07d7621e12494cf85135b3775877b9ef14704587b58122b650e6e7834eef64e4**
Archive: /Users/atbagga/Library/Caches/Homebrew/downloads/ee31577ef75e005a09434feaba40fc5335af7e501cd58d83ffb8cdab092c32cb--vsts-cli-0.1.3.high_sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.

I cleared the cached bottle. Brew uninstalled vsts-cli and installed again and I see same error as above.

_Originally posted by @atbagga in https://github.com/Homebrew/homebrew-core/pull/34037/comment#issuecomment-441166256_

**Comment by atbagga** [comment]
Apologies for not following the  template. I created this issue using link in the PR page and it didn't give me an option to select or fill out a template.

**Comment by MikeMcQuaid** [comment]
@atbagga Thanks! Which PR page/link?

**Comment by atbagga** [comment]
![image](https://user-images.githubusercontent.com/11888714/48938550-8ea1ac80-ef37-11e8-875a-d82cf5329759.png)

**Comment by MikeMcQuaid** [comment]
@atbagga Cool, thanks.

**Comment by MikeMcQuaid** [comment]
> * [ ]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Can you provide this information?

**Comment by atbagga** [comment]
Sharing the output. Although the issue is no longer reproducible. So I closed the issue. 
Apologies for the false alarm.

https://gist.github.com/atbagga/f287f7dae5349428bc9f24972a651f20

Thanks!
