### ISSUE TITLE
llvm: lldb_codesign identity must be available to build with LLDB

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#34447]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Tried running `brew install --with--lldb llvm`, but got the following output:

```
llvm: lldb_codesign identity must be available to build with LLDB:
https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt
Error: An unsatisfied requirement failed this build.
```

I followed the instructions at https://llvm.org/svn/llvm-project/lldb/trunk/docs/code-signing.txt to a tee, and rebooted, so there should be no issue.

[`brew config`](https://gist.github.com/67e0468fa5cf7be6fc1099191b314cf5)
[`brew doctor`](https://gist.github.com/22b6287b3419fe7fff2256d4b49c7fa1)

**Comment by MikeMcQuaid** [comment]
You'll need to debug this yourself I'm afraid, analytics shows it's definitely working for some users.
