### ISSUE TITLE
brew unlink/link node does not manage npm symlink

### ISSUE THREAD

**Issue by bval** [Homebrew/homebrew-core#34475]
- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

I want to temporarily unlink node so I can use another version temporarily. I `brew unlink node` and yet the `/usr/local/bin/npm` symlink remains. If I manually remove it and proceed, when I go back to `brew link node` it is not replaced. I can only get it back via `brew reinstall node`.

- What happened (include command output)

```
→ brew unlink node
Unlinking /usr/local/Cellar/node/11.2.0... 7 symlinks removed

→ ls -la /usr/local/bin/npm
lrwxr-xr-x  1 bvalentine  admin  46 Nov 26 10:45 /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
```

```
→ rm /usr/local/bin/npm 

→ brew link node
Linking /usr/local/Cellar/node/11.2.0... 7 symlinks created

→ ls -la /usr/local/bin/npm
ls: /usr/local/bin/npm: No such file or directory
```

```
→ brew reinstall node
==> Reinstalling node 
==> Downloading https://homebrew.bintray.com/bottles/node-11.2.0.mojave.bottle.1.tar.gz
Already downloaded: /Users/bvalentine/Library/Caches/Homebrew/downloads/a7dff4575247d3ed7c19015c49d0a53c444d9dd606b90ac74c020ab42f89af0b--node-11.2.0.mojave.bottle.1.tar.gz
==> Pouring node-11.2.0.mojave.bottle.1.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/11.2.0: 3,936 files, 47MB

→ ls -la /usr/local/bin/npm
lrwxr-xr-x  1 bvalentine  admin  46 Nov 26 10:53 /usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
```

- What you expected to happen

`brew link`/`brew unlink` should manage all symlinks added by `brew install`.

- Step-by-step reproduction instructions (by running `brew install` commands)

See above.

**Comment by MikeMcQuaid** [comment]
This is intentional, I'm afraid, and a product of how we install `npm` in a way that plays nice with upstream and upgrades.
