### ISSUE TITLE
python@2: unable to import zlib when compiled on Mojave

### ISSUE THREAD

**Issue by sashkab** [Homebrew/homebrew-core#34511]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

https://gist.github.com/sashkab/f020a5bfe09b0e88fa9ef46cacdf472d

I've used slightly modified version of the python@2.rb formulae, only modification for this test was update revision from `1` to `2` and forced to build on macOS Mojave with the latest updates and latest CLT to compile Python 2.7 from source. Upon successful compilation, I was not able to import the zlib package:

```
$ /usr/local/Cellar/python@2/2.7.15_2/bin/python -c "import zlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named zlib
```

I've seen few resolved issues or accepted pull requests mentioning this, but didn't have a chance to dig deeper.

**Comment by sashkab** [comment]
Looks like there is already pull for this (adding zlib import test) in #34473, which fails on Mojave as of now.

**Comment by fxcoudert** [comment]
Yes we are working on it.

**Comment by fxcoudert** [comment]
Should be fixed now.

**Comment by sashkab** [comment]
Not fixed for me.

```sh
$ brew install python@2 -s
/usr/local/Cellar/python@2/2.7.15_1/bin/python -c "import zlib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named zlib
```

**Comment by sashkab** [comment]
Opened  #34549 followup.
