### ISSUE TITLE
Some builds fail due to the "m" in Versions/3.7/include/python3.7m

### ISSUE THREAD

**Issue by Zyrsha** [Homebrew/homebrew-core#34512]
**STEPS TO REPRODUCE THE **REPRODUCIBLE** BUG REPORT**
1) Install MacOS Mojave
2) Install brew and clang and any version of python via brew
3) Attempt to compile boost - https://www.boost.org/doc/libs/1_68_0/more/getting_started/unix-variants.html
4) Fails on all macOS / brew installs due to the "m" in Versions/3.7/include/python3.7m

**SPECIFIC REPRODUCIBLE COMMANDS THAT WERE USED TO COMPILE BOOST PROVIDED BELOW**

I've had a couple builds fail because of the 'm' in the path:
`/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m`

For example, when attempting to build Boost:
```
./bootstrap.sh --with-toolset=clang --with-python=/usr/local/bin/python3 --with-python-root=/usr/local/bin/python3 --with-python-version=3.7
./b2 -q --debug-configuration toolset=clang cxxflags="-stdlib=libc++ -std=c++17" linkflags="-stdlib=libc++ -std=c++17"
```

It will produce:
```
notice: [python-cfg] Configuring python...
notice: [python-cfg]   user-specified version: "3.7"
notice: [python-cfg]   user-specified cmd-or-prefix: "/usr/local/bin/python3"
notice: [python-cfg] Checking interpreter command "/usr/local/bin/python3"...
notice: [python-cfg] running command '/usr/local/bin/python3 -c "from sys import *; print('version=%d.%d\nplatform=%s\nprefix=%s\nexec_prefix=%s\nexecutable=%s' % (version_info[0],version_info[1],platform,prefix,exec_prefix,executable))" 2>&1'
notice: [python-cfg] ...requested configuration matched!
notice: [python-cfg] Details of this Python configuration:
notice: [python-cfg]   interpreter command: "/usr/local/bin/python3"
notice: [python-cfg]   include path: "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7"
notice: [python-cfg]   library path: "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config" "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib"
```

This will cause the build to fail, because `"include path: "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7"` without the 'm' is a nonexistent path.

**Comment by SMillerDev** [comment]
This is the exact same post as before, still without filling out the template.
https://github.com/Homebrew/homebrew-core/issues/34485

**Comment by Zyrsha** [comment]
I already provided the full bug report with all relevant information needed to understand the issue. You want me to fill out a form that has 0 information in it?

**Comment by Zyrsha** [comment]
I already provided the full bug report with all relevant information needed to understand the issue. You want me to fill out a form that has 0 information in it? And only post spam repeating the same exact very obvious words, pasted yet again to say the same?

**Comment by Zyrsha** [comment]
I already provided the full bug report with all relevant information needed to understand the issue. You want me to fill out a form that has 0 additional useful information in it? You want me post spam more additional repeating the same very obvious words, pasted yet again to say the same ... in a text formatting style you like?

bizarre

**Comment by Zyrsha** [comment]
I already provided the full bug report with all relevant information needed to understand the issue. You want me to fill out a form that has 0 additional useful information in it? You want me post spam more additional repeating the same very obvious words, pasted yet again to say the same ... because it's in a pretty print text formatting style you like?

**Comment by Zyrsha** [comment]
I already provided the full bug report with all relevant information needed to understand the issue. You want me to fill out a form that has 0 additional useful information in it? You want me post additional spam repeating the same very obvious words, pasted yet again to say the same ... because it's in a pretty print text formatting style you like?

**Comment by SMillerDev** [comment]
Yes.

**Comment by Zyrsha** [comment]
I already provided the full bug report with all relevant information needed to understand the issue. You want me to fill out a form that has 0 additional useful information in it? You want me post additional spam repeating the same very obvious words, pasted yet again to say the same ... because it's in a pretty print text formatting style you like?

It's not fair of you to ask me to waste my time. I already provided all of the information.

**Comment by SMillerDev** [comment]
Life isn't fair. Until I have the required information about brew versions and whatnot that would be in the template you're wasting both our times.

**Comment by Zyrsha** [comment]
Ok, we can just leave an outstanding bug and issue in brew causing all Boost builds to fail because "SMillerDev" didn't like the way that I typed pretty print formatting.

**Comment by Zyrsha** [comment]
Ok, we can just leave an outstanding bug and issue in brew causing all Boost builds to fail for all users attempting to use Python because "SMillerDev" didn't like the way that I typed pretty print formatting.

**Comment by MikeMcQuaid** [comment]
@Zyrsha From the issue template:

> **If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

We ask you for the information we need. If you want our help (which we are not obliged to give you): you do so on our terms.

**Comment by Zyrsha** [comment]
Hey guys, I'm too busy. I have 18 hours of work to do today.

I left you all the information you need. I have to work now.

It is your choice to leave a serious outstanding issue in brew affecting a common library because you didn't like as pretty print formatting I typed.

**Comment by Zyrsha** [comment]
Hey guys, I'm too busy. I have 18 hours of work to do today.

I left you all the information you need. I have to work now.

It is your choice to leave a serious outstanding issue in brew affecting a common library because you didn't like as pretty print formatting I typed. That will affect other users, and it will harm other users - users who have no idea who *I* am.

**Comment by MikeMcQuaid** [comment]
If you're too busy to fill out the template: we're too busy to help you.

**Comment by SMillerDev** [comment]
> That will affect other users, and it will harm other users - users who have no idea who I am.
And all they need to do is fill out the issue template to help us debug it. That's a sweet deal if I ever saw one.
