### ISSUE TITLE
macvim depends on both lua and luajit

### ISSUE THREAD

**Issue by moonfruit** [Homebrew/homebrew-core#34527]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install `macvim` with `lua` **or** `luajit`.

- What happened (include command output)

Homebrew's `macvim` depends on both `lua` and `luajit`. And it really can only use one of them. Currently, only `luajit` worked.

- What you expected to happen

let `macvim` depend only on `lua` or `luajit`, not both.
I recommend using `lua`, because `luajit` only support for Lua 5.1, and it doesn’t seem to be moving forward. Nowadays, Lua is 5.3, and will be 5.4 not far away.

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install macvim`

**Comment by meritozh** [comment]
**macvim** formula should provide opts like `--with-lua` and `--with-luajit`. I have used a vim plugin named `color_coded`, [it doesn't support luajit](https://github.com/jeaye/color_coded/blob/16e71d6f5850849c6ffc9a06a7c952e27d351866/cmake/check_luajit.cmake#L10).

Now, I cann't rebuild macvim without luajit simply.
