### ISSUE TITLE
Winetricks

### ISSUE THREAD

**Issue by WinMin** [Homebrew/homebrew-core#34531]
$ brew install winetricks

fatal: Needed a single revision
==> Downloading https://github.com/Winetricks/winetricks/archive/20180815.tar.gz
Already downloaded: /Users/swing/Library/Caches/Homebrew/downloads/2f9d6507fce3a4aa799a48b0c5759fa5b416a119dad263cde7d52a8c7f3f86e9--winetricks-20180815.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 6dc22357ea1f857b7283250f7c6a68b9dee97e672bbea9a9c45c573d73634200
Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Archive: /Users/swing/Library/Caches/Homebrew/downloads/2f9d6507fce3a4aa799a48b0c5759fa5b416a119dad263cde7d52a8c7f3f86e9--winetricks-20180815.tar.gz
To retry an incomplete download, remove the file above.

**Comment by SMillerDev** [comment]
Could you please fill out the issue template? It's needed to help you debug issues. I'll close this until you do.
