### ISSUE TITLE
libgcrypt fails to build on 10.12

### ISSUE THREAD

**Issue by nreilly** [Homebrew/homebrew-core#3456]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

libgcrypt fails to build on 10.12. 

https://gist.github.com/nreilly/e3afa8f2fd5873de49306d65277b6a33

**Comment by DomT4** [comment]
Known issue. See https://github.com/Homebrew/homebrew-core/issues/1957.
