### ISSUE TITLE
Formula request: CloudFormation Lint

### ISSUE THREAD

**Issue by matsev** [Homebrew/homebrew-core#34584]
CloudFormation Lint is a tool that 

> Validate CloudFormation yaml/json templates against the CloudFormation spec and additional checks

https://github.com/awslabs/cfn-python-lint

Related formula: [awscli](https://formulae.brew.sh/formula/awscli)
Related issue: https://github.com/awslabs/cfn-python-lint/issues/493

**Comment by SMillerDev** [comment]
Please consult the issue template regarding feature requests. Feature requests should be done as pull requests.
