### ISSUE TITLE
Pebble-SDK fails to upgrade/reinstall on High Sierra (no bottle)

### ISSUE THREAD

**Issue by BenjaminHCCarr** [Homebrew/homebrew-core#34594]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/a4171c8ee2ef6987dec4312d57d2384c

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Pebble-SDK is out of date, trying to brew upgrade `pebble-sdk`

- What happened (include command output)

no bottle was found:
```
 bottle do
    root_url "http://pebble-sdk-homebrew.s3.amazonaws.com"
    cellar :any
    sha256 "bcbebcf5c8f6631374044d86d3c6b007a9e6440c83c2fbb3741693e17818aa62" => :el_capitan
    sha256 "f14ce854035de57dbcc9f8ab390071491aee81a37456cf325b28ac5a80020989" => :sierra
  end
```

```
brew reinstall pebble-sdk
==> Reinstalling pebble/pebble-sdk/pebble-sdk 
==> Downloading http://pebble-sdk-homebrew.s3.amazonaws.com/pebble-sdk-4.5.el_ca
######################################################################## 100.0%
==> Pouring pebble-sdk-4.5.el_capitan.bottle.tar.gz
Error: undefined method `undent' for #<String:0x00007fec159c56e0>
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/pebble/homebrew-pebble-sdk/pebble-sdk.rb:228:in `caveats'
/usr/local/Homebrew/Library/Homebrew/caveats.rb:17:in `caveats'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `empty?'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:613:in `caveats'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:664:in `finish'
/usr/local/Homebrew/Library/Homebrew/reinstall.rb:34:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:51:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:45:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:45:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```
- What you expected to happen

An upgrade to `pebble-sdk`

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade --force pebble-sdk`
or
`brew reinstall pebble-sdk`

The bottle fails and it tries to install from source

----

There are no `bottles` for `High Sierra` or `Mojave` I am on high sierra.
The bottle fails and it tries to install from source
https://gist.github.com/a4171c8ee2ef6987dec4312d57d2384c

----

```
brew config
HOMEBREW_VERSION: 1.8.4-9-g30c90dc
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 30c90dcc3b03f9046b43af5efe256eda7263158c
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fbee5d45821506f3b91045ca1dc8ed2e4f910aa
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_102
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

Related `Formulae missing High Sierra bottles`: Homebrew/homebrew-core#18493

**Comment by SMillerDev** [comment]
Sorry but the pebble SDK isn't part of homebrew itself. It's in a custom tap and therefore we can't support it. You'll have to file this in the pebble SDK tap.

**Comment by fxcoudert** [comment]
Here is the place to file the issue: https://github.com/pebble/homebrew-pebble-sdk/issues
