### ISSUE TITLE
Release usbmuxd 1.1.0 as stable in homebrew formula

### ISSUE THREAD

**Issue by tvolkert** [Homebrew/homebrew-core#34601]
A [recent change](https://github.com/libimobiledevice/libimobiledevice/commit/f1ee0fd8b2b1dd65c64f5a67e208efc708295caa) to `libimobiledevice` bumped the constraint on `libusbmuxd` to >= version `1.1.0`. The current `usbmuxd` homebrew package is version `1.0.10`.

As a result, homebrew `--HEAD` installs of `libimobiledevice` no longer build without a `--HEAD` install of `usbmuxd`.

Is it possible to release `usbmuxd` `1.1.0` as stable?

**Comment by tvolkert** [comment]
@FunkyM @nikias

**Comment by SMillerDev** [comment]
Homebrew only allows requests for updates/software in the form of pull requests. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request this documentation will help you implement a version bump.
