### ISSUE TITLE
e2fsprogs head is broken

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#34686]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://git.io/fpoi0

To help us debug your issue please explain:
- What you were trying to do (and why)
```
brew upgrade --HEAD e2fsprogs
```
- What happened (include command output)
```
making install in e2fsck
	MKDIR_P /usr/local/Cellar/e2fsprogs/HEAD-75da667/sbin /usr/local/Cellar/e2fsprogs/HEAD-75da667/share/man/man8
make[1]: config/install-sh: No such file or directory
make[1]: *** [installdirs] Error 1
make: *** [install-progs-recursive] Error 1
```
- What you expected to happen
Formula installs.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew upgrade --HEAD e2fsprogs
```

**Comment by fxcoudert** [comment]
We welcome pull requests for HEAD issues, but we typically do not consider them as support issues.
