### ISSUE TITLE
Bottle become unusable after dependency changes

### ISSUE THREAD

**Issue by vitalyster** [Homebrew/homebrew-core#34736]
I did contribute to [libswiften formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libswiften.rb), it depends on [boost](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb). Several times after boost update bottled libswiften became unusable because of changed and missing boost symbols, building from source still works. What is the correct way to tell homebrew rebuild bottle without updating formula?

**Comment by SMillerDev** [comment]
This isn't related to homebrew-core but to brew. You can change the revision to rebuild the bottles though.

**Comment by MikeMcQuaid** [comment]
The way to make Homebrew rebuild these is ensure the ‘test do’ block reproduces this error.

**Comment by vitalyster** [comment]
@MikeMcQuaid I did add test [there](https://github.com/Homebrew/homebrew-core/pull/34738) - but I'm not sure. Will it try to run test with bottle? When boost is updated - will it rerun test? If test fails - will it try to rebuild bottle at try to build again?

**Comment by MikeMcQuaid** [comment]
It will try to run the test when boost is updated and we won’t merge if the test fails (assuming it was already passing).
