### ISSUE TITLE
Wireshark build from source fails: Undefined symbols

### ISSUE THREAD

**Issue by mischnic** [Homebrew/homebrew-core#34754]
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? 
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Building wireshark from source on High Sierra (because I want `--with-qt`) fails:

```
$ brew install -s wireshark
...
[  8%] Linking C executable run/extcap/randpktdump
/usr/local/Cellar/cmake/3.13.1/bin/cmake -E cmake_link_script CMakeFiles/randpktdump.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -fvisibility=hidden  -Wall -Wextra -Wendif-labels -Wpointer-arith -Wformat-security -fwrapv -fno-strict-overflow -Wvla -Waddress -Wattributes -Wdiv-by-zero -Wignored-qualifiers -Wpragmas -Wno-overlength-strings -Wno-long-long -Wheader-guard -Wframe-larger-than=32768 -Wc++-compat -Wunused-const-variable -Wshadow -Wno-pointer-sign -Wold-style-definition -Wstrict-prototypes -Wlogical-op -Wjump-misses-init -Wshorten-64-to-32 -Werror=implicit -Wcomma  -Qunused-arguments -std=gnu99  -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  -pie CMakeFiles/randpktdump.dir/extcap/extcap-base.c.o CMakeFiles/randpktdump.dir/extcap/randpktdump.c.o  -o run/extcap/randpktdump  -L/usr/local/Cellar/glib/2.58.1/lib  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/ui  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/ui/gtk  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/ui/qt  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/capchild  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/caputils  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/codecs  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/epan  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/randpkt_core  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/wiretap  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/writecap  -L/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/wsutil -Wl,-rpath,/usr/local/Cellar/glib/2.58.1/lib -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/ui -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/ui/gtk -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/ui/qt -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/capchild -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/caputils -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/codecs -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/epan -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/randpkt_core -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/wiretap -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/writecap -Wl,-rpath,/tmp/wireshark-20181204-70209-1c48lj8/wireshark-2.6.5/wsutil run/librandpkt_core.a run/libui.a run/libwiretap.8.0.5.dylib /usr/local/lib/libglib-2.0.dylib /usr/lib/libz.dylib run/libwsutil.9.0.0.dylib -framework CoreFoundation /usr/local/lib/libglib-2.0.dylib -lgmodule-2.0 -lglib-2.0 -lintl /usr/local/lib/libgcrypt.dylib /usr/local/lib/libgpg-error.dylib /usr/lib/libz.dylib /usr/local/lib/libgnutls.dylib 
Undefined symbols for architecture x86_64:
  "_randpkt_example_close", referenced from:
      _main in randpktdump.c.o
  "_randpkt_example_init", referenced from:
      _main in randpktdump.c.o
  "_randpkt_example_list", referenced from:
      _main in randpktdump.c.o
      _help in randpktdump.c.o
  "_randpkt_find_example", referenced from:
      _main in randpktdump.c.o
  "_randpkt_loop", referenced from:
      _main in randpktdump.c.o
  "_randpkt_parse_type", referenced from:
      _main in randpktdump.c.o
ld: symbol(s) not found for architecture x86_64
```

https://gist.github.com/mischnic/c486288af4d3c9b3a3913d092f240287

**Comment by SMillerDev** [comment]
I can't find that output anywhere in the gist log you posted. Are you sure that's the correct one?

**Comment by mischnic** [comment]
@SMillerDev I've rerun the build with only one make job. The real error seems to be a different one: https://gist.github.com/mischnic/c486288af4d3c9b3a3913d092f240287#file-02-make-L386-L404

**Comment by mischnic** [comment]
@MikeMcQuaid Yes

**Comment by MikeMcQuaid** [comment]
`brew cask install wireshark` may be useful for you for now. We are moderately likely to remove this option if it's failing as Homebrew doesn't handle GUIs well.

**Comment by mischnic** [comment]
But this issue has nothing to do with the Qt GUI, `brew install -s wireshark` builds just the command line tools.

**Comment by MikeMcQuaid** [comment]
Sorry, I misread: I thought you said this _did_ fail only with the Qt option.

In that case, I'm not sure I understand what you meant by:

> Building wireshark from source on High Sierra (because I want `--with-qt`) fails:

**Comment by mischnic** [comment]
> In that case, I'm not sure I understand what you meant by:
>> Building wireshark from source on High Sierra (because I want --with-qt) fails:

Filling in the issue template:

> To help us debug your issue please explain:
> - What you were trying to do (and why)

**Comment by MikeMcQuaid** [comment]
So you wish to install wireshark `--with-qt` but it fails to reinstall with or without `--with-qt`, right?

**Comment by mischnic** [comment]
Correct

**Comment by apjanke** [comment]
I'm unable to reproduce on 10.13.6, even if I downgrade to Xcode 9.4.1 to match your setup. `brew install -s wireshark` works fine for me. Here's my build logs from a single-job build: https://gist.github.com/d9e7528a70735146161f0b06f7cb4327.

Here's something unusual: looking at the difference between our `CMakeCache.txt` files in the build logs, I see it detecting several library-related utility commands in your `/usr/local/bin` for which it's picking up the system ones in `/usr/bin` on my system.

```
$ diff ~/Library/Logs/Homebrew/wireshark/CMakeCache.txt ~/Downloads/c486288af4d3c9b3a3913d092f240287-4fde60cd7cb636e77d530776b76759a6bb0324f9/CMakeCache.txt
[...]
< CMAKE_AR:FILEPATH=/usr/bin/ar
---
> CMAKE_AR:FILEPATH=/usr/local/bin/ar
273c273
< CMAKE_NM:FILEPATH=/usr/bin/nm
---
> CMAKE_NM:FILEPATH=/usr/local/bin/nm
276c276
< CMAKE_OBJCOPY:FILEPATH=CMAKE_OBJCOPY-NOTFOUND
---
> CMAKE_OBJCOPY:FILEPATH=/usr/local/bin/objcopy
279c279
< CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump
---
> CMAKE_OBJDUMP:FILEPATH=/usr/local/bin/objdump
302c302
< CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib
---
> CMAKE_RANLIB:FILEPATH=/usr/local/bin/ranlib
352c352
< CMAKE_STRIP:FILEPATH=/usr/bin/strip
---
> CMAKE_STRIP:FILEPATH=/usr/local/bin/strip
367c367
[...]
```

I think it's unusual to have `ar`, `nm`, `objcopy`, and the like supplied by Homebrew. They're provided by binutils, but the Homebrew formula for binutils is keg-only. Do you have the Homebrew binutils installed and force-linked? Or have binutils or another source of these utilities installed to `/usr/local` through some other process? Perhaps that's altering the behavior of the `/usr/local/Cellar/cmake/3.13.1/bin/cmake -E cmake_link_script CMakeFiles/randpktdump.dir/link.txt --verbose=1` step.

**Comment by mischnic** [comment]
@apjanke `brew unlink binutils` fixed it!
