### ISSUE TITLE
node@10 does not use macOS

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#34831]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Steps to reproduce

```
$ brew install node@10
==> Downloading http://7xkcej.dl1.z0.glb.clouddn.com/bottles/node@10-10.13.0.hig
######################################################################## 100.0%
==> Pouring node@10-10.13.0.high_sierra.bottle.tar.gz
==> Caveats
node@10 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have node@10 first in your PATH run:
  echo 'export PATH="/usr/local/opt/node@10/bin:$PATH"' >> ~/.bash_profile

For compilers to find node@10 you may need to set:
  export LDFLAGS="-L/usr/local/opt/node@10/lib"
  export CPPFLAGS="-I/usr/local/opt/node@10/include"

==> Summary
🍺  /usr/local/Cellar/node@10/10.13.0: 3,630 files, 45.6MB
```

Run the `node` executable

```
$ PATH="/usr/local/opt/node@10/bin:$PATH" node --version
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.62.dylib
  Referenced from: /usr/local/opt/node@10/bin/node
  Reason: image not found
Abort trap: 6
```

I have the latest icu4c installed, although it should not be linked

```
$ brew info icu4c
icu4c: stable 62.1 (bottled) [keg-only]
C/C++ and Java libraries for Unicode and globalization
https://ssl.icu-project.org/
/usr/local/Cellar/icu4c/62.1 (253 files, 67.5MB)
  Built from source on 2018-08-16 at 02:41:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/icu4c.rb
==> Caveats
icu4c is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

$ brew link icu4c
Warning: Refusing to link macOS-provided software: icu4c
If you need to have icu4c first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile
```

### Workaround

Only when I manually link the `icu4c` keg into `/usr/local/opt/icu4c` does `node` work

```
$ ln -s /usr/local/Cellar/icu4c/62.1 /usr/local/opt/icu4c
$ /usr/local/opt/node@10/bin/node --version
v10.13.0
```

**Comment by hanxue** [comment]
Building `node@10` from source fails because `icu4c` is expected to be linked

```
$ brew reinstall node@10 --build-from-source
==> Reinstalling node@10 
Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/icu4c not present or broken
Please reinstall icu4c. Sorry :(
```

**Comment by MikeMcQuaid** [comment]
> Building `node@10` from source fails because `icu4c` is expected to be linked

That's not the case; `/usr/local/opt/icu4c` should be present even if it's unlinked.
