### ISSUE TITLE
"brew postgresql-upgrade-database" confusing output

### ISSUE THREAD

**Issue by StasD** [Homebrew/homebrew-core#34878]
Hello,
When I run the command "brew postgresql-upgrade-database", it outputs (among other things) at the end: "once you start the new server, consider running: ./analyze_new_cluster.sh"
And also: "Running this script will delete the old cluster's data files: ./delete_old_cluster.sh"
These 2 lines are apparently produced by "pg_upgrade" program.
But I have no clue whatsoever where to look for these two .sh scripts... The output does not give any indication about it.
So, 1) When I run "brew postgresql-upgrade-database", can you please add more info in the output about where to find these files .
2) For now, can you please just tell me where these files might be... :)
Thanks.

P.S.: Finally found them at the "/usr/local/var/log/" folder (by looking at your ruby script, line "(var/"log").cd do" gave me some clue...)
So, nevermind 2), but the output still needs to be improved, as it took me quite a while to find those files...

**Comment by MikeMcQuaid** [comment]
> So, 1) When I run "brew postgresql-upgrade-database", can you please add more info in the output about where to find these files .

This should be suggested to `pg_upgrade` maintainers instead.



> 2) For now, can you please just tell me where these files might be... :)

Sorry, we don't provide that level of support. Consider asking on our Discourse.

In future please always fill out the issue template.

**Comment by StasD** [comment]
As I understand, pg_upgrade creates those scripts in the current working directory. It assumes that when you call it, you know what directory you are in, so it does not provide the full path.
But when pg_upgrade is called indirectly, in this case by your script, it is the responsibility of your script to let the user know the path of the working directory, because you explicitly set it in the script. So, it is the fault of **YOUR** script, and not pg_upgrade's, that I spent 2 hours looking for those bash script files which are essential to finish the upgrade process, which is what your script is designed for...

**Comment by MikeMcQuaid** [comment]
@StasD Wow: you're literally complaining that some utility I created in my spare time to make your life easier didn't make it quite as easy as you wanted. You don't seem to understand how open source works: https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/

**Comment by StasD** [comment]
For me personally, the change I'm arguing about here is not needed at all anymore, as the next time when I run your program, I will know where to look for those scripts. I just feel sorry for other people who will want to run scripts mentioned in pg_upgrade's output, but could not find them. If you don't want to do anything about it, that's fair enough. Convincing pg_upgrade developers seems even less realistic: they are part of much bigger project which is not even on GitHub. At least Google will probably index this page which might help somebody... :)

**Comment by MikeMcQuaid** [comment]
> If you don't want to do anything about it

I don't have the motivation but it seems neither do you so: there we go.
