### ISSUE TITLE
Subversion fails to build on High Sierra

### ISSUE THREAD

**Issue by MagnusMG** [Homebrew/homebrew-core#34883]
I have run brew update twice and brew doctor. I also ran gist-logs and got the link https://gist.github.com/543b919ffe251e786633a240fb0bd91b.

I am running osx 10.13.6.

I tried to install subversion, using the command 'brew install subversion --with-java'.

It resulted in the following output:
==> Installing subversion --with-java
==> Downloading https://www.apache.org/dyn/closer.cgi?path=subversion/subversion-1.10.2.tar.bz2
Already downloaded: /Users/xgumag/Library/Caches/Homebrew/downloads/891bd5f606e2553db3534719644e0fee38f62a2e8f0d048d11bbb3092e982904--subversion-1.10.2.tar.bz2
==> Patching
patching file subversion/bindings/swig/perl/native/Makefile.PL.in
patching file build/get-py-info.py
==> Downloading https://www.apache.org/dyn/closer.cgi?path=serf/serf-1.3.9.tar.bz2
Already downloaded: /Users/xgumag/Library/Caches/Homebrew/downloads/3f4e2cb0f268fb9db7a761edccb60bdbdacb9923f8b2140e8c0a30b6792958a6--serf-1.3.9.tar.bz2
==> /usr/local/opt/scons/bin/scons PREFIX=/usr/local/Cellar/subversion/1.10.2/libexec/serf GSSAPI=/usr CC=/usr/bin/clang C
==> /usr/local/opt/scons/bin/scons install
==> ./configure --prefix=/usr/local/Cellar/subversion/1.10.2 --enable-optimize --disable-mod-activation --disable-nls --wi
==> make
Last 15 lines from /Users/xgumag/Library/Logs/Homebrew/subversion/04.make:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:36:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:354:49: error: expected a version of the form 'major[.minor[.subminor]]'
                                    macos(10.3, API_TO_BE_DEPRECATED),
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
                                              ^
4 errors generated.
make: *** [subversion/libsvn_subr/macos_keychain.lo] Error 1

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by MagnusMG** [comment]
OK, I'm really sorry, but I don't understand what is lacking in my original post. I really tried to find any similar issues before I posted, I tried to read up on what do to before I posted, and I tried to follow the template. From your reaction I understand that I did NOT include all the necessary info, but I still can't figure out what to add.

"- What you were trying to do (and why)"
I was trying to install subversion, so that I could use subversion on my computer.

"- What happened (include command output)"
The make failed. See attached error messages (original post).

"- What you expected to happen"
I expected the make not to fail. I expected subversion to be installed.

"- Step-by-step reproduction instructions (by running `brew install` commands)"
brew install --with-java subversion

I'm really sorry if I annoy ye with a stupid posting, and I really appreciate all the work ye put into this software and I really try to be careful with yer time, but this is as far as I get. Please tell me what other information you need.

**Comment by MikeMcQuaid** [comment]
That should be enough. If you create an issue in future please use the template on https://github.com/Homebrew/homebrew-core/issues/new?template=Reproducible-Bug-Report.md as it makes it easier to quickly see if all the information has been provided. Thanks!

**Comment by fxcoudert** [comment]
```
In file included from subversion/libsvn_subr/macos_keychain.c:42:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:36:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:354:49: error: expected a version of the form 'major[.minor[.subminor]]'
                                    macos(10.3, API_TO_BE_DEPRECATED),
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:355:46: error: expected a version of the form 'major[.minor[.subminor]]'
                                    ios(2.0, API_TO_BE_DEPRECATED),
                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:356:50: error: expected a version of the form 'major[.minor[.subminor]]'
                                    watchos(1.0, API_TO_BE_DEPRECATED),
                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Security.framework/Headers/SecTrust.h:357:47: error: expected a version of the form 'major[.minor[.subminor]]'
                                    tvos(2.0, API_TO_BE_DEPRECATED));
                                              ^
```

**Comment by fxcoudert** [comment]
This is now fixed! Thanks @mistydemeo
