### ISSUE TITLE
couchdb 1.7.1_8 still broken on mojave, no .ini files in the bottle

### ISSUE THREAD

**Issue by srl295** [Homebrew/homebrew-core#34958]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

Note: this is pretty much the same as https://github.com/Homebrew/homebrew-core/issues/30063 

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/srl295/312b3302ffc39a20feba50112c52df61
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (n/a)

To help us debug your issue please explain:
- What you were trying to do (and why)

install couchdb

- What happened (include command output)

install was successful, but couchdb did not start.

- What you expected to happen

successful install

- Step-by-step reproduction instructions (by running `brew install` commands)

```
# to reproduce, make sure you don't already have a working couchdb
brew services stop couchdb
# you could delete all of /usr/local/etc/couchdb
rm -rf /usr/local/etc/couchdb/*.ini
$ brew install couchdb
==> Downloading https://homebrew.bintray.com/bottles/couchdb-1.7.1_8.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring couchdb-1.7.1_8.mojave.bottle.tar.gz
==> Caveats
To test CouchDB run:
    curl http://127.0.0.1:5984/
The reply should look like:
    {"couchdb":"Welcome","uuid":"....","version":"1.7.1","vendor":{"version":"1.7.1-1","name":"Homebrew"}}

To have launchd start couchdb now and restart at login:
  brew services start couchdb
Or, if you don't want/need a background service you can just run:
  couchdb
==> Summary
🍺  /usr/local/Cellar/couchdb/1.7.1_8: 612 files, 13.0MB
srl@qormi:/tmp
$ brew services start couchdb
==> Successfully started `couchdb` (label: homebrew.mxcl.couchdb)
srl@qormi:/tmp
$ ls -l /usr/local/etc/couchdb/*.ini
ls: /usr/local/etc/couchdb/*.ini: No such file or directory
(1) srl@qormi:/tmp
$ curl http://127.0.0.1:5984/
curl: (7) Failed to connect to 127.0.0.1 port 5984: Connection refused
```

—————

- The couchdb bottle https://homebrew.bintray.com/bottles/couchdb-1.7.1_8.mojave.bottle.tar.gz has no `default.ini` file, but version 7  https://homebrew.bintray.com/bottles/couchdb-1.7.1_7.mojave.bottle.tar.gz  of the bottle had the file. 

- installing with `brew install couchdb -s` was successful

- I would have reopened #30063  if I could, because according to https://github.com/Homebrew/homebrew-core/pull/30064#issuecomment-405987023 this wasn't really fixed before, just worked around by rebuilding the bottle

**Comment by fxcoudert** [comment]
Our `postinstall` code does this:

```
    # default.ini is owned by CouchDB and marked not user-editable
    # and must be overwritten to ensure correct operation.
    if (etc/"couchdb/default.ini.default").exist?
      # but take a backup just in case the user didn't read the warning.
      mv etc/"couchdb/default.ini", etc/"couchdb/default.ini.old"
      mv etc/"couchdb/default.ini.default", etc/"couchdb/default.ini"
    end
```

but the bottle does not have a `etc/couchdb/default.ini.default` file. In fact, it does not have an `etc` directory at all.

**Comment by fxcoudert** [comment]
Reinstall from source with `brew install -s couchdb` does not generate any files in `etc`.

**Comment by fxcoudert** [comment]
@srl295 can you please test and comment on #34978?
