### ISSUE TITLE
Linking fails with gstreamermm

### ISSUE THREAD

**Issue by aMarcireau** [Homebrew/homebrew-core#34952]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/aMarcireau/940ede2197c028db9bd6785df7caca81

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install gstreamermm to link a program that works with Linux and older versions of macOS and uses the function `Gst::Bus::pop(Gst::ClockTime)`.

- What happened (include command output)
Linking fails with the error:
```
Undefined symbols for architecture x86_64:
  "Gst::Bus::pop(unsigned long long)"
```

Reinstalling the formula from source solved the issue: `brew reinstall --build-from-source gstreamermm`. 

A little bit of digging shows that the dylib provided by the bottle contains an incorrect signature for this function:
```sh
nm -g --demangle /usr/local/lib/libgstreamermm-1.0.dylib | grep Bus::pop
# output
0000000000019f44 T Gst::Bus::pop(Gst::MessageType)
0000000000019f12 T Gst::Bus::pop()
0000000000019f78 T Gst::Bus::pop(unsigned long)
0000000000019fac T Gst::Bus::pop(unsigned long, Gst::MessageType)
```

The headers show that this function expects a `ClockTime` parameter (*bus.h*, line 371), typedef'ed as a `GstClockTime` (*clockutils.h*, line 37), typedef'ed as a `guint64` (*gstclock.h*, line 46), typedef'ed as a `unsigned long long` (*glibconfig.h*, line 52). 

After recompiling from source, the library has the correct signature:
```sh
nm -g --demangle /usr/local/lib/libgstreamermm-1.0.dylib | grep Bus::pop
# output
0000000000019f44 T Gst::Bus::pop(Gst::MessageType)
0000000000019f12 T Gst::Bus::pop()
0000000000019f78 T Gst::Bus::pop(unsigned long long)
0000000000019fac T Gst::Bus::pop(unsigned long long, Gst::MessageType)
```

**Comment by SMillerDev** [comment]
I think this would be solvable by rebuilding the bottles. Could you make a pull request that adds `revision 1` underneath the url in the formula?

**Comment by fxcoudert** [comment]
Why would it have changed though? We need to understand that before we start bumping revision numbers.

**Comment by tschoonj** [comment]
strange... I guess it must have been redefined recently in glibconfig.h then. Interestingly `unsigned long long` and `unsigned long` are both 8 bytes, so I would have expected that they would have been recognised as identical by the compiler/linker.

Anyway my recommendation is also to revbump and rebuild the bottle.
