### ISSUE TITLE
Missing php@7.0 in homebrew

### ISSUE THREAD

**Issue by henkrehorst** [Homebrew/homebrew-core#34998]
PHP version 7.0 is missing in homebrew

**Comment by igas** [comment]
Answer here https://github.com/Homebrew/homebrew-core/pull/34739

Fill the template next time otherwise it would be closed immediately without explanation.

**Comment by samgranger** [comment]
I have created a tap for users that need 7.0:
`brew tap samgranger/homebrew-php`

Installation will take a while since I still need to create a bottle but will update once that has been done.

**Comment by sanik90** [comment]
@samgranger thanks, for now this would be temporary fix, accidentally updated brew last week wonder why I can't run my php
