### ISSUE TITLE
Problem with the SQLCipher update to v4.0.0 - doesn't easily open databases encrypted with prior versions

### ISSUE THREAD

**Issue by justinclift** [Homebrew/homebrew-core#34991]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~
  * Not relevant in this instance
- [x] ~if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~
  * Not relevant in this instance

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

***

Looks like the SQLCipher formula was updated to SQLCipher 4.0.0 a few days ago: https://github.com/Homebrew/homebrew-core/pull/34659.

One problem (pretty major) is that this new update of SQLCipher isn't (by default) going to open any databases encrypted by previous versions.

It **may** not be a complete blocker, as users should (prior to opening a database) technically be able to run some commands to change the settings the database is then opened with:

&nbsp; &nbsp; https://www.zetetic.net/blog/2018/11/30/sqlcipher-400-release/#compatibility

With that done, an older database should open.

Not sure of the best approach for handling this though?  eg:

* Should the version bump be reverted to keep using v3.4.2 of SQLCipher for now instead?
  * Maybe a SQLCipher4 formula for this instead?
* Should some kind of obvious warning about this be plastered where the user will see it?
* Also not sure if upstream should consider this a "bug" or not.  Still trying to think that through personally. :wink:

**Comment by justinclift** [comment]
@aguynamedben may be of interest to you too. :smile:

**Comment by justinclift** [comment]
Additional info about the commands needing to be manually run prior to opening existing databases:

&nbsp; &nbsp; https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283

**Comment by justinclift** [comment]
No worries at all.  Thinking about this overnight, I'm tending towards thinking SQLCipher itself should probably have an automatic fallback when opening databases to the previous defaults. eg so previous version databases are likely to open ok, and still retain the on disk format of the previous version.

Will likely fill out a bug report on upstream SQLCipher repo about his later on today, after thinking about it a bit more.  If the above behaviour can be adjusted (eg in v4.0.1 of SQLCipher), that would solve the issue here in Homebrew too. :smile:

**Comment by aguynamedben** [comment]
@justinclift +1, a breaking on update seems unexpected, especially given that SQLite/SQLCipher is commonly used in embedded/portable scenarios where there's not a sysadmin around to run commands.

I'll also +1 the forum or GitHub issue too (don't see one yet).

**Comment by justinclift** [comment]
As a temporary measure, I've created a tap specifically for SQLCipher 3.4.2:

&nbsp; &nbsp; https://github.com/justinclift/homebrew-sqlcipher3

Hopefully that's only needed temporarily, until a better solution is found. :smile:

**Comment by justinclift** [comment]
Created the upstream issue for discussion: https://github.com/sqlcipher/sqlcipher/issues/296

**Comment by MikeMcQuaid** [comment]
> Should the version bump be reverted to keep using v3.4.2 of SQLCipher for now instead?
> * Maybe a SQLCipher4 formula for this instead?

We'd consider a PR for a sqlicipher@3 formula but reverting back is likely to cause more issues than it would solve at this point.

**Comment by justinclift** [comment]
Yeah, it's no easy choice here.  Let's see how the discussion with upstream goes.  If the fallback behaviour can be implemented, and done so in short order (no idea), that would probably be the more optimal solution.

**Comment by brodybits** [comment]
I would definitely favor the following:
* sqlcipher@3 formula, with a warning that it is deprecated and maybe should not be considered the most secure
* Latest sqlcipher formula should show a warning message, as already suggested by @justinclift
* The tool should try a fallback if it cannot open the database with the given password, as I suggested in <https://github.com/sqlcipher/sqlcipher/issues/296#issuecomment-446612878>

**Comment by MikeMcQuaid** [comment]
> * with a warning that it is deprecated and maybe should not be considered the most secure

If we'd need to do this: we will not add the formula.

**Comment by aguynamedben** [comment]
I think from a Homebrew perspective a simple warning (i.e. `brew info`, printed after install) is sufficient. If I recall, this is exactly what Postgres does when it changes its on-disk format. The Homebrew user is expected to heed the warning and upgrade the on-disk format themselves via a few manual steps.
