### ISSUE TITLE
Contributing.md not reachable from start page

### ISSUE THREAD

**Issue by JMoVS** [Homebrew/homebrew-core#35]
the very useful document [Contributing.md](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) for the formula part is currently not reachable when one simply starts from the readme.md of this repository. Also, going to homebrew-documentation only results in the end on [Contributing.md from homebrew/brew](https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md) that doesn't really help with creating formulae. The contributing.md in this repo should be reachable via links starting from this repository's Readme.md.

**Comment by ilovezfs** [comment]
@mikemcquaid Should the link be updated to point to the absolute path https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md or should https://github.com/Homebrew/brew/blob/master/.github/CONTRIBUTING.md be made more useful or even replaced with a copy of https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md or something else?

**Comment by mikemcquaid** [comment]
@ilovezfs I think linking to `CONTRIBUTING.md` from this repo's README seems like the best fit 👍
