### ISSUE TITLE
php 7.3 fpm has wrong directory

### ISSUE THREAD

**Issue by bingalls** [Homebrew/homebrew-core#35005]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  https://gist.github.com/f5aa47e00309e9e795f0bb3707faffca
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install php`  # version 7.3
Trying to run php-fpm
- What happened (include command output)
php-fpm
[11-Dec-2018 14:08:07] ERROR: failed to open error_log (/usr/var/local/log/php-fpm.log): No such file or directory (2)
[11-Dec-2018 14:08:07] ERROR: failed to post process the configuration
[11-Dec-2018 14:08:07] ERROR: FPM initialization failed

- What you expected to happen
I did not expect /usr/var/ as System Integrity Protection prevents creation of this dir. I expected `/usr/local/var/`
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install php`
`php-fpm`
aborts with error: /usr/var/local/log/php-fpm.log should be `/usr/local/var/log/php-fpm.log`

**Comment by SMillerDev** [comment]
This is a setting in `/usr/local/etc/php*` though, are you sure this is the configuration that was shipped and you didn't still have an older file?

**Comment by bingalls** [comment]
I found the issue. Homebrew does not use /usr/local/etc/php-fpm.conf but `/etc/php-fpm.conf`
Homebrew runs php-fpm as root. It is confusing, because homebrew does not log to /var/log but rather to /usr/local/var/log. Also, I was getting warnings of a non-root user ignoring `user` & `group` configuration. Sadly, I am still getting `http 502` errors, which were not a problem before upgrading to php 7.3. php-fpm is known to cause such errors. Note that I use Laravel Valet.

**Comment by bingalls** [comment]
Here is a quick fix: set `pcre.jit = 0` in php.ini for php >= v7. This solves problems with composer, such as `composer global update`. Otherwise, the homebrew formulae for pcre & pcre2 should be (or able to be) compiled with the *jit* option. If I don't hear back, I'll make a pull request.
