### ISSUE TITLE
libwbxml removed option, why?

### ISSUE THREAD

**Issue by m-emelchenkov** [Homebrew/homebrew-core#35007]
What happened with options in commit 13c5296910115ee42685b12d6880284969d01219 (git show 13c5296910115ee42685b12d6880284969d01219). Someone removed a necessary option which I introduced in 53974ab9040de28193bd044793630bb4b26e2909. I have not received any notifications about this also. If it was done by mistake then revert the commit.

**Comment by igas** [comment]
Please fill the issue template next time, it stated that we close issues without it.

See #31510 for the rationale behind removing options from formulas.
