### ISSUE TITLE
Error: SHA256 mismatch for libusb

### ISSUE THREAD

**Issue by ericzered** [Homebrew/homebrew-core#3504]
Hello,
I'm trying to install ideviceinstaller for my appium tests.
But when I do "brew install --HEAD ideviceinstaller" I have a mismatch error for libusb.

logs :
==> Installing dependencies for ideviceinstaller: libusb, usbmuxd, makedepend, libimobiledevice, libzip
==> Installing ideviceinstaller dependency: libusb
==> Downloading https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.19/libusb-1.0.19.tar.bz2
Error: SHA256 mismatch
Expected: 6c502c816002f90d4f76050a6429c3a7e0d84204222cbff2dce95dd773ba6840
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821

Is it related to a sourceforge issue ?
Thanks

**Comment by DomT4** [comment]
Unsure about the specific mismatch here, but you may need to `brew update`. The current `libusb` version we ship is `1.0.20` & the primary download URL is from upstream's GitHub rather than SourceForge _(partly in the hope of avoiding aforementioned not infrequent SF downtime)_.

**Comment by reidpr** [comment]
It's a SF issue. I'm having the same problem with `gnuplot`, down to the same incorrect hash. Here's the content of the file:

```
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="//sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'http://sourceforge.net/home.html';
}
</script>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>
</body></html>
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ openssl dgst -sha256 <(curl -s -L https://downloads.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.19/libusb-1.0.19.tar.bz2)
SHA256(/dev/fd/63)= 6c502c816002f90d4f76050a6429c3a7e0d84204222cbff2dce95dd773ba6840
```

**Comment by ilovezfs** [comment]
```
Josephs-MacBook-Pro:~ joe$ openssl dgst -sha256 <(curl -s -L "https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.4/gnuplot-5.0.4.tar.gz")
SHA256(/dev/fd/63)= 151cb845728bde75eb9d1561b35140114a05a7c52a52bd35b4b2b3d944e0c31e
```
It's fine.

**Comment by DomT4** [comment]
I'm unable to reproduce any problems with SF currently, but it wouldn't surprise me if there was an issue there. Their Twitter confirmed an issue [a couple hours back](https://twitter.com/sfnet_ops/status/760109235292078083).

**Comment by ericzered** [comment]
Few hours after, it's ok, same command was ok and libusb is installed.
I was just unlucky to try exactly when SF was in trouble.
Thanks ! Have a nice day everybody

**Comment by ilovezfs** [comment]
@ericzered also don't forget to brew update and brew upgrade since 1.0.20 is current version for libusb not 1.0.19
