### ISSUE TITLE
tinyproxy service via homebrew.mxcl.tinyproxy.plist has a wrong path

### ISSUE THREAD

**Issue by dup2** [Homebrew/homebrew-core#35040]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config output:
```
HOMEBREW_VERSION: 1.8.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 38493a35a2abe722c527ffebf9c2fbf9bc4d3825
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 830db7ae79167ab9036d9267980ecd80c3fc4134
Core tap last commit: 88 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

I installed `tinyproxy` which creates files in `/usr/local/opt/tinyproxy` (symlinked) as below:
```
/usr/local/opt/tinyproxy/AUTHORS
/usr/local/opt/tinyproxy/COPYING
/usr/local/opt/tinyproxy/ChangeLog
/usr/local/opt/tinyproxy/INSTALL_RECEIPT.json
/usr/local/opt/tinyproxy/NEWS
/usr/local/opt/tinyproxy/README
/usr/local/opt/tinyproxy/README.md
/usr/local/opt/tinyproxy/TODO
/usr/local/opt/tinyproxy/bin
/usr/local/opt/tinyproxy/bin/tinyproxy
/usr/local/opt/tinyproxy/homebrew.mxcl.tinyproxy.plist
/usr/local/opt/tinyproxy/share
/usr/local/opt/tinyproxy/share/man
/usr/local/opt/tinyproxy/share/man/man5
/usr/local/opt/tinyproxy/share/man/man5/tinyproxy.conf.5
/usr/local/opt/tinyproxy/share/man/man8
/usr/local/opt/tinyproxy/share/man/man8/tinyproxy.8
/usr/local/opt/tinyproxy/share/tinyproxy
/usr/local/opt/tinyproxy/share/tinyproxy/stats.html
/usr/local/opt/tinyproxy/share/tinyproxy/default.html
/usr/local/opt/tinyproxy/share/tinyproxy/debug.html
/usr/local/opt/tinyproxy/share/doc
/usr/local/opt/tinyproxy/share/doc/tinyproxy
/usr/local/opt/tinyproxy/share/doc/tinyproxy/AUTHORS
/usr/local/opt/tinyproxy/share/doc/tinyproxy/README
/usr/local/opt/tinyproxy/share/doc/tinyproxy/README.md
/usr/local/opt/tinyproxy/share/doc/tinyproxy/NEWS
```

This includes a service which can be managed with `brew services`.

The services fails to start due to a wrong path in the file `homebrew.mxcl.tinyproxy.plist`- in this plist file, the service binary is configured to be at `/usr/local/opt/tinyproxy/sbin/tinyproxy` which is wrong. Instead the binary is at `/usr/local/opt/tinyproxy/bin/tinyproxy` (in the directory *bin* instead of *sbin*)

**Comment by igas** [comment]
Hi, thank you for your report. Mind to send PR? you already explained everything, should be 1 character change :)

**Comment by dup2** [comment]
Sure thing, hope it is ok - I noticed that there is no ${opt_bin} documented at https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md so I used ${bin}
