### ISSUE TITLE
mtr should be installed setuid so it doesn't require sudo

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-core#35085]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to use mtr without sudo

- What happened (include command output)

```
% mtr 1.1 
Failure to open IPv4 sockets: Operation not permitted
Failure to open IPv6 sockets: Operation not permitted
mtr: Failure to start mtr-packet: Invalid argument
```

- What you expected to happen

mtr should just work

- Step-by-step reproduction instructions (by running `brew install` commands)

```
% brew install mtr
% mtr 1.1 
```

This was already discussed [here](https://github.com/Homebrew/legacy-homebrew/issues/166) but then just closed on moving repos. Basically on all linux distros mtr is installed as setuid root, and I am arguing (as did the people in https://github.com/Homebrew/legacy-homebrew/issues/166) that this should also be the default for home-brew. If you disagree, please at least consider adding this as an option to the formula.

**Comment by fxcoudert** [comment]
This has been declined multiple times already: Homebrew's policy is to not install setuid binaries. See https://github.com/Homebrew/homebrew-core/pull/14428 https://github.com/Homebrew/legacy-homebrew/issues/50207 https://github.com/Homebrew/legacy-homebrew/issues/43862 https://github.com/Homebrew/legacy-homebrew/issues/40992
