### ISSUE TITLE
units_cur using system python instead of brew installed on

### ISSUE THREAD

**Issue by wwzhang** [Homebrew/homebrew-core#35145]
units_cur is a program of gnu-units, and basically a python script to update currencies. It calls system python 2.7 with /usr/bin/python on line 1, which could cause a problem for modules, such as I use and install modules only for python3 installed with brew

**Comment by SMillerDev** [comment]
Could you fill out the issue template? It really contains some import information and I'll close this issue until you edited your post to include that information.
