### ISSUE TITLE
error on 'brew update' after correcting/setting 'LC_ALL' to 'de_CH.UTF-8'

### ISSUE THREAD

**Issue by RogerWeihrauch** [Homebrew/homebrew-core#35155]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [-] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):
Due to the fact on having changed the different locale setting (de_CH.UTF8) as defined in standard install of linuxbrew (LC_ALL=en_US.UTF-8), additionally I get an error on 'Error: Fetching /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core failed!'

- What happened (include command output):
when executing brew update, brew upgrade, brew doctor, I get the hint on not to be able to change LC_ALL from linuxbrew side:

debian@JessiE:~$ brew doctor
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Your system is ready to brew.
debian@JessiE:~$ nano /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh
debian@JessiE:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /home/linuxbrew/.linuxbrew/Homebrew/Library && git stash && git clean -d -f
debian@JessiE:~$ cd /home/linuxbrew/.linuxbrew/Homebrew/Library && git stash && git clean -d -f
Saved working directory and index state WIP on stable: e659ce9cd Revert test/language/java to upstream [Linux]
debian@JessiE:

- What you expected to happen:
Well, from my point of view I was surprised about this error; did expect linuxbrew just to work after install.
- Step-by-step reproduction instructions (by running `brew install` commands)
In my env I can execute brew upfdate, brew upgrade and brew doctor wit aleays the same error messages (find attached txt file and brew_conf):

[LinuxBrew_error.txt](https://github.com/Homebrew/homebrew-core/files/2683007/LinuxBrew_error.txt)
[brew_conf.txt](https://github.com/Homebrew/homebrew-core/files/2683008/brew_conf.txt)

**Comment by SMillerDev** [comment]
This isn't the correct place to report issues with linuxbrew. It has it's own version of homebrew-core.

**Comment by MikeMcQuaid** [comment]
Also, do not create issues after editing Homebrew.
