### ISSUE TITLE
gcc on mojave miss the system includes to /usr/local/include

### ISSUE THREAD

**Issue by howard0su** [Homebrew/homebrew-core#35181]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
MacBook-Air:src howardsu$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have external commands with conflicting names.
Found command `brew-aspell-dictionaries` in following places:
  /usr/local/Homebrew/Library/Taps/gtdmmb/homebrew-core/cmd/brew-aspell-dictionaries.rb
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/cmd/brew-aspell-dictionaries.rb
Found command `brew-postgresql-upgrade-database` in following places:
  /usr/local/Homebrew/Library/Taps/gtdmmb/homebrew-core/cmd/brew-postgresql-upgrade-database.rb
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/cmd/brew-postgresql-upgrade-database.rb

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

MacBook-Air:pages howardsu$ brew config
HOMEBREW_VERSION: 1.8.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 38493a35a2abe722c527ffebf9c2fbf9bc4d3825
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 497ca906fc12248322b8faba601c280a7256bba8
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.7.0_71
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

To help us debug your issue please explain:
- What you were trying to do (and why)
Compile code under gcc with some local installed brew package. The issue is the new compiler doesn't include /usr/local/include as a system include folder.

- What happened (include command output)
target/common/emu/fltk.cpp:28:10: fatal error: FL/Fl.H: No such file or directory
 #include <FL/Fl.H>
          ^~~~~~~~~
compilation terminated.

- What you expected to happen
successfully compile the code
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install gcc
brew install fltk
compile the following code:
// a.c
#include <FL/Fl.H>

void main() { return; }

**Comment by MikeMcQuaid** [comment]
> * ran `brew config` and `brew doctor` and included their output with your issue?

@howard0su Please provide this output.

CC @fxcoudert for clarification on the expected behaviour here.

**Comment by howard0su** [comment]
provided all details.

**Comment by MikeMcQuaid** [comment]
> so I feel like this is "sort of" a bug.
> We could try to configure GCC with `--with-local-prefix`

@fxcoudert Feel free to close out or open/request a PR; your call.

**Comment by MikeMcQuaid** [comment]
@fxcoudert Oh, and: thanks! ❤️
