### ISSUE TITLE
[FR] To ship Polemarch

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#35190]
>[Polemarch](http://about.polemarch.org/en/stable/) is a service for infrastructure orchestration based on [ansible](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb). Simple WEB gui for infrastructure orchestration using ansible playbooks.

I'm not good on python/pypi. Please help ship to create this formula.

**Comment by SMillerDev** [comment]
As per the issue template: 
> To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

I'm gonna close this for not following the issue template. If you make a start with the pull request I'd be happy to help though. (not that I'm great with python)

**Comment by MikeMcQuaid** [comment]
Come on @yurikoles, you know to read the issue template by now.

**Comment by yurikoles** [comment]
@MikeMcQuaid but it's not an issue.

You suppose it to be:
Steps to reproduce
```
 brew install polemarch
Error: No available formula with the name "polemarch" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by MikeMcQuaid** [comment]
@yurikoles You created an issue so please always fill in the issue template. Also, the generic issue template (if this was not a reproducible bug report) specifically says:

> To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
