### ISSUE TITLE
gnuplot 5.2.5 crashes with wxt terminal on 10.13.6

### ISSUE THREAD

**Issue by ldeniau** [Homebrew/homebrew-core#35194]
My gist-log can be found at:
https://gist.github.com/ldeniau/17fc20dfdbbeefa14b2299e46f936999

Summary:
The following commands run in a gnuplot session (script or interactive)

set term wxt 0
plot sin(x)
set term wxt 1
plot sin(x)

will immediately generate a
Segmentation fault: 11

It looks like a known multi-threading incompatibility of the wxt (wxmac) terminal, that should be disabled by the compilation directive -DWXT_MONOTHREADED. But GDB reports two threads when running these commands in a script (not sure that they belong to wxt driver).

Best,
Laurent.

**Comment by fxcoudert** [comment]
We build `gnuplot` with `wxmac` by letting `configure` autodetect all settings. If the resulting binary does not work, it needs to be reported to `gnuplot` so they fix their `configure`/`Makefile`.
