### ISSUE TITLE
GNU mv won't rename files with case changes only

### ISSUE THREAD

**Issue by bengaywins** [Homebrew/homebrew-core#35234]
Summary:
Trying to rename files from Foo_Bar.txt to foo_bar.txt fails with GNU mv in Coreutils versions 8.29 and 8.30 at least.

Steps to reproduce:
1. `touch Foo_Bar.txt`
2. Using the GNU mv:`mv Foo_Bar.txt foo_bar.txt`

Expected result:
File is renamed

Actual result:
Errors out with `mv: 'Foo_Bar.txt' and 'foo_bar.txt' are the same file`

More info:
If I use the built-in Mac mv (/bin/mv) this succeeds.

**Comment by SMillerDev** [comment]
I'd expect the build in mv to just ignore it since macOS systems are usually case insensitive. While the gnu one will try to move it to find out that macOS thinks it's the same.

**Comment by SMillerDev** [comment]
Either way this isn't an issue in brew but in CoreUtils afaik
