### ISSUE TITLE
Superenv breaks ruby HEAD (2.6) JIT

### ISSUE THREAD

**Issue by Gaelan** [Homebrew/homebrew-core#35250]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? [Nothing related, and it seems fairly clear what's going wrong]
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/Gaelan/b7602dbfc164a77125a0601896fd2942
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to test out the (unreleased) ruby 2.6's JIT support, using a brew-installed Ruby.
- What happened (include command output)
```
$ brew install ruby --HEAD                                                                                                      
==> Cloning https://github.com/ruby/ruby.git
Updating /Users/gaelan/Library/Caches/Homebrew/ruby--git
==> Checking out branch trunk
Already on 'trunk'
Your branch is up to date with 'origin/trunk'.
HEAD is now at 13c15be avoid passing unnecessary options to download method
==> autoconf
==> ./configure --prefix=/usr/local/Cellar/ruby/HEAD-13c15be_1 --enable-shared --disable-silent-rules --with-sitedir=/usr/local/lib/ruby/site_ruby --wi
==> make
==> make install
==> Downloading https://rubygems.org/rubygems/rubygems-2.7.7.tgz
Already downloaded: /Users/gaelan/Library/Caches/Homebrew/downloads/8edf965aff4dd1c5d1818fd4f847abc6be5be00353d7f0eb3809d10daab52110--rubygems-2.7.7.tgz
==> /usr/local/Cellar/ruby/HEAD-13c15be_1/bin/ruby setup.rb --prefix=/private/tmp/ruby-20181218-30135-1f9g3kc/vendor_gem
==> Caveats
By default, binaries installed by gem will be placed into:
  /usr/local/lib/ruby/gems/2.6.0/bin

You may want to add this to your PATH.

ruby is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have ruby first in your PATH run:
  echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile

For compilers to find ruby you may need to set:
  export LDFLAGS="-L/usr/local/opt/ruby/lib"
  export CPPFLAGS="-I/usr/local/opt/ruby/include"

For pkg-config to find ruby you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/ruby/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/ruby/HEAD-13c15be_1: 18,890 files, 27.8MB, built in 5 minutes 15 seconds
$ ruby --jit --jit-verbose=2 foo.rb                                                                                                 
MJIT: CC defaults to /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
MJIT: tmp_dir is /var/folders/48/4qjy_0q122zf0xxr3y0m87w00000gn/T/
Creating precompiled header
Starting process: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -w -O3 -emit-pch -o /var/folders/48/4qjy_0q122zf0xxr3y0m87w00000gn/T//_ruby_mjit_hp50626u0.h.gch /usr/local/Cellar/ruby/HEAD-13c15be_1/include/ruby-2.6.0/x86_64-darwin18/rb_mjit_min_header-2.6.0.h
clang: The build tool has reset ENV; --env=std required.
MJIT warning: Making precompiled header failed on compilation. Stopping MJIT worker...
```
- What you expected to happen
I expected Ruby's JIT to run successfully.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install ruby --HEAD
touch foo.rb
ruby --jit --jit-verbose=2 foo.rb
```
# Probable Explanation
(I'm not sure what the policy is on supporting HEAD builds, but since 2.6.0 is releasing soonish (they've released an `rc2`), it seems that the 2.6.0 release will have the same issue)

Ruby's JIT works by compiling the Ruby code to C, then compiling the C code. It [appears](https://github.com/ruby/ruby/blob/8b13cbce7e700917e7760e013447c13dabd8f6b0/configure.ac#L255) to bake the compile-time $CC into the executable and use that compiler in its JIT. In brew, that $CC is `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang`, which doesn't work outside of a `brew install`. Not sure what the best solution is—maybe we need upstream changes to allow the compiler used at runtime to be different from $CC. (Maybe you already can? I don't speak autoconfig)

**Comment by MikeMcQuaid** [comment]
> I'm not sure what the policy is on supporting HEAD builds

We don't support them.



> In brew, that $CC is `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang`, which doesn't work outside of a `brew install`. Not sure what the best solution is—maybe we need upstream changes to allow the compiler used at runtime to be different from $CC. (Maybe you already can? I don't speak autoconfig)

Yes, we'll need a way to specify the JIT compiler rather than assuming it can use `$CC`.

**Comment by fxcoudert** [comment]
Release ruby 2.6 is working fine, and we don't generally support HEAD builds, so closing.

**Comment by Gaelan** [comment]
Ruby "works fine", but the JIT is still broken:

```
$ brew install ruby
$ /usr/local/opt/ruby/bin/ruby --jit --jit-verbose=2 /tmp/foo.rb 
MJIT: CC defaults to /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang
MJIT: tmp_dir is /var/folders/48/4qjy_0q122zf0xxr3y0m87w00000gn/T/
Creating precompiled header
Starting process: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -w -O3 -emit-pch -o /var/folders/48/4qjy_0q122zf0xxr3y0m87w00000gn/T//_ruby_mjit_hp27622u0.h.gch /usr/local/Cellar/ruby/2.6.1/include/ruby-2.6.0/x86_64-darwin18/rb_mjit_min_header-2.6.1.h
clang: The build tool has reset ENV; --env=std required.
MJIT warning: Making precompiled header failed on compilation. Stopping MJIT worker...
```

Technically ruby isn't "broken" (because the JIT falls back to running normally), but homebrew's build system does break a feature. I'd argue this should stay open

**Comment by MikeMcQuaid** [comment]
@Gaelan At some point someone who cares about the JIT working will need to submit a pull request to fix it (or do enough research to make it very easy for a Homebrew maintainer to make the necessary changes)

**Comment by hukendo** [comment]
> Technically ruby isn't "broken" (because the JIT falls back to running normally), but homebrew's build system does break a feature. I'd argue this should stay open

it's not bug in Homebrew. You need fix enviroment. reinstall Command Line Tools
