### ISSUE TITLE
ledger: dependencies

### ISSUE THREAD

**Issue by emKaroly** [Homebrew/homebrew-core#35254]
My issue is about [ledger formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ledger.rb)
it is installing the whole boost package(600MB) as dependency while it is not necessary.
I have opened an [issue(#1697)](https://github.com/ledger/ledger/issues/1697) in ledger repo  about brew installing the whole boost package and they said it is not necessary to install it

**Comment by SMillerDev** [comment]
You could file a pull request to remove it or maintain your own tap where it doesn't pull in dependencies for commonly used features.

**Comment by emKaroly** [comment]
> You could file a pull request to remove it or maintain your own tap where it doesn't pull in dependencies for commonly used features.

I never edited homebrew formulas :-(

**Comment by fxcoudert** [comment]
The upstream issue's message is not “boost is not necessary”, but:

> doesn't require the whole boost library, only some parts of it

namely, the filesystem, iostreams, regex, system, python modules. Homebrew does not split boost into subpackages, so boost is necessary for ledger unless it only uses header-only modules (which is not the case).

**Comment by emKaroly** [comment]
> The upstream issue's message is not “boost is not necessary”, but:
> 
> > doesn't require the whole boost library, only some parts of it
> 
> namely, the filesystem, iostreams, regex, system, python modules. Homebrew does not split boost into subpackages, so boost is necessary for ledger, unless it were to only use header-only modules (which is not the case).

So you are saying that it OK to install 600MB dependency for an 10+ MB cli tool?

**Comment by SMillerDev** [comment]
Yeah, if that makes it the most usable version of the software for the most users.

**Comment by emKaroly** [comment]
> Yeah, if that makes it the most usable version of the software for the most users.

Do you think that it would be possible to split boost library as [Debian packages](https://packages.debian.org/buster/ledger) using it? Maybe it would be worth it because many software depends on some parts of boost.
