### ISSUE TITLE
Suggestion: rename gnuman to man for coreutils, findutils and some other similar formulas

### ISSUE THREAD

**Issue by moonfruit** [Homebrew/homebrew-core#35310]
In order to avoid duplicate names with system commands, some formulas install the command with the prefix `g`, and install the default names into the directory `libexec/gnubin`. And meantime these formulas install the `man` manuals into the directory `libexec/gnuman`.

For example, formula `grep`'s Caveats says:

> The command has been installed with the prefix "g".
> If you do not want the prefix, install using the "with-default-names"
> option.
> 
> If you need to use these commands with their normal names, you
> can add a "gnubin" directory to your PATH from your bashrc like:
>   PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
> 
> Additionally, you can access their man pages with normal names if you add
> the "gnuman" directory to your MANPATH from your bashrc as well:
>   MANPATH="/usr/local/opt/grep/libexec/gnuman:$MANPATH"

According to that, if I want to use the command with it's default name, I can put `libexec/gnubin` to my `PATH`. And if want to use the `man` manual with the default name, I must put `libexec/gnuman` to `MANPATH`.

What I suggest is that **homebrew install the `man` manual with it's default name in `libexec/man` instead of `libexec/gnuman`**.

**Why?** Because `man man` says:

> In addition, for each directory in the command search path (we'll call it a "command directory") for which  you  do  not  have  a  MAN-
> PATH_MAP  statement,  man  automatically  looks  for a manual page directory "nearby" namely as a subdirectory in the command directory
> itself or in the parent directory of the command directory.

So, if homebrew install the `man` manual with it's default name in `libexec/man`, when I put `libexec/gnubin` to my `PATH`, the `man` manual is also ready to use. And we don't need to use `MANPATH`.

I test it on my macbook, it works.

**Comment by fxcoudert** [comment]
That sounds nice, and we would welcome a pull request to that effect.
