### ISSUE TITLE
git: stable 2.20.1 (bottled) missing send-email

### ISSUE THREAD

**Issue by royger** [Homebrew/homebrew-core#35330]
- ran `brew update` and can still reproduce the problem?

Yes

- ran `brew doctor`, fixed all issues and can still reproduce the problem?

Yes

- ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
% brew gist-logs git
Error: No logs.
```
- if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
% brew config && brew doctor
HOMEBREW_VERSION: 1.8.6-14-ga2b4d4a
ORIGIN: https://github.com/Homebrew/brew
HEAD: a2b4d4aac294ec0872cd84d44f65bd5bd507e166
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5c7948dbb28d23039b59699e6a1a38299b2f43d2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```
To help us debug your issue please explain:
- What you were trying to do (and why)

The last git package seems to be missing the send-email functionality:
```
% /usr/local/bin/git send-email
git: 'send-email' is not a git command. See 'git --help'.
% brew info git
git: stable 2.20.1 (bottled), HEAD
Distributed revision control system
https://git-scm.com
/usr/local/Cellar/git/2.19.1 (1,518 files, 40.1MB)
  Poured from bottle on 2018-10-11 at 12:47:03
/usr/local/Cellar/git/2.19.2 (1,520 files, 40.1MB)
  Poured from bottle on 2018-12-05 at 15:59:19
/usr/local/Cellar/git/2.20.1 (1,526 files, 41.3MB) *
  Poured from bottle on 2018-12-19 at 12:16:38
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb
==> Dependencies
Required: gettext ✔, pcre2 ✔
Optional: openssl ✔, curl ✘
==> Options
--with-curl
	Use Homebrew's version of cURL library
--with-openssl
	Build with Homebrew's OpenSSL instead of using CommonCrypto
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Analytics
install: 244,244 (30 days), 607,346 (90 days), 1,929,708 (365 days)
install_on_request: 214,065 (30 days), 539,047 (90 days), 1,584,494 (365 days)
build_error: 0 (30 days)
```
- What happened (include command output)
```
% /usr/local/bin/git send-email
git: 'send-email' is not a git command. See 'git --help'.
```
- What you expected to happen

Be able to use the send-email command, like in previous versions.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
% brew install git
% /usr/local/bin/git send-email
```

**Comment by fxcoudert** [comment]
This is a deliberate choice: https://github.com/Homebrew/homebrew-core/pull/35125

**Comment by royger** [comment]
I don't understand, why is i broken? It has been working just fine for me with every homebrew git version. Granted I had to install the perl modules, but that's a user choice. Removing send-email simply doesn't even give the user a choice.

At least an option should be added to restore previous behaviour.

**Comment by MikeMcQuaid** [comment]
> At least an option should be added to restore previous behaviour.

We're not adding more options, sorry: https://github.com/Homebrew/homebrew-core/issues/31510

We'll consider a PR that re-adds it and installs all relevant modules along with a test to verify it works.

**Comment by royger** [comment]
I'm not sure I understand the reason for removing the send-email functionality when it's not actually causing any other parts of the git package to malfunction.

Was it because there was a constant influx of issues reported against git send-email not working?

git send-email is a non-optional part of my workflow, and without it the homebrew git package is just useless. I understand there are projects that work only with pull requests and branches, but there are a lot of projects out there that still require developers to send patches to mailing lists. I expect I won't be the only one impacted by this unilateral decision.

TBH I don't think removing functionality in the name of good user experience is the way to move forward, not at least without a way to restore such functionality. In fact this change made my user experience much worse.

**Comment by MikeMcQuaid** [comment]
@royger Please read the linked issue to better understand the motivations for this. You have a two options:

- create a version of this formula in your own tap that works how you want it to
- submit the pull request with `test do` tests for re-adding this functionality by default

Both options require work on your part because you care about the change. That's how open source works.

**Comment by bk2204** [comment]
This is causing discussion on the Git list, including suggestions for feature development to work around this issue. It would be nice if this issue could be reopened so users have a place to get support, since when users install Git, they expect a complete, fully functional Git, and removing features causes a support burden for upstream.

If Homebrew doesn't want to install modules in the system Perl, it might be possible to depend on the Homebrew Perl and ship modules in that. I'm not particularly picky about a solution, but as an upstream contributor, I'd appreciate it if upstream didn't get reports about missing features from Homebrew's Git.

**Comment by royger** [comment]
Quite a lot of open source projects operate under [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), which IMO would mean adding a big warning message for a reasonable amount of time to the send-email script noticing it will go away in further releases of homebrew packaged git, so that people using it can take time to fix the situation. 

It's obvious that people that care about the feature should take the time to fix it or probe it's not broken, but you need to give them a notice and a fair amount of time to address the situation.

**Comment by MikeMcQuaid** [comment]
We’ll run our project and issue tracker how we think is best, thanks.

I’m going to take a look at this in the coming weeks (reminder: it’s Christmas Eve so a major holiday for many people) but if anyone who cares wants to open a PR before that: please do.

**Comment by bk2204** [comment]
Certainly, you're free to operate your project and issue tracker as you see fit, and certainly nobody expects anything to be done over the holidays. Any fix here would be great, and should I have time and the ability to come up with a good solution, I'll send a PR.

**Comment by jpassaro** [comment]
@MikeMcQuaid @fxcoudert
Would you folks be open to a pull request that
a) created a (non-optional) dependency on Homebrew Perl, and
b) restored the `send-email` script that my previous pull request removed?

I did not realize that removing `send-email` would be such a breaking change for folks. Sorry @royger. You can, I think, get it working by getting the script from git/git and installing it on your own PATH but I recognize this was disruptive and you have my apologies.

As I said in #35125, it seems the only way to get it working is to do `sudo cpan` or link against Perl. The first is obviously not something Homebrew should suggest to users, so it might be that depending on a perl that we can manipulate as users is the only way to get `git-send-email`, and by extension git itself, working fully.

**Comment by woodruffw** [comment]
Just as an additional datapoint: Ubuntu doesn't include `git-send-email` in their `git` package, you have to install `git-email` for it.

If optional dependencies are out of the picture, then creating a separate formula (with a hard brew Perl dep) might be a good approach.

**Comment by fxcoudert** [comment]
Optional dependency is not an option. If we can include so that it works, we should, otherwise we'll have to leave it out.

**Comment by MikeMcQuaid** [comment]
I would like to avoid a whole Perl dependency for a single script. We should be able to vendor the necessary modules.

**Comment by jpassaro** [comment]
I think this is safe to close as of fdc6005
