### ISSUE TITLE
Separate build and runtime dependencies

### ISSUE THREAD

**Issue by activatedgeek** [Homebrew/homebrew-core#3534]
As of now, all Homebrew packages only have other packages as dependencies. Some packages are built on the host at the time of installation. This leads to installation of extra build dependencies which are only required for the compilation of the binary but not during the runtime.

Should such dependencies be automatically removed once the installation is complete?

Or, should the user be allowed to list and remove such build dependencies?

**Comment by MikeMcQuaid** [comment]
A good question. We don't keep track of dependencies explicitly yet (but will when we implement https://github.com/Homebrew/brew-evolution/blob/master/003-install-bottles-of-arbitrary-versions.md CC @sjackman) so for now this would be tricky. `brew missing`/`brew doctor` do the opposite to what you've said and will shout if you've removed something you shouldn't have.

As this is a feature request: would you mind refiling it on either Homebrew/brew or, ideally, write a proposal for Homebrew/brew-evolution?

Thanks!

**Comment by activatedgeek** [comment]
@MikeMcQuaid I've opened the issue there so that it has more eyes. Let me have look at the proposal and see if I can contribute. Thank you!

**Comment by MikeMcQuaid** [comment]
Great, thanks!
