### ISSUE TITLE
OpenCV SFM library missing

### ISSUE THREAD

**Issue by jhihn** [Homebrew/homebrew-core#35340]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Use OpenCV's FishEye routines, which are in opencv_sfm (Structure from motion)

- What happened (include command output)
OpenCV seemed to install ok, I ran make for my software,
Everything compiled ok, ran it, got:
dyld: Library not loaded: /usr/local/opt/opencv/lib/libopencv_sfm.3.4.dylib
  Reason: image not found

I did an `ls /usr/local/opt/opencv/lib/libopencv_sfm.3.4.dylib` and it did not exist. I was able to find it anywhere on the filesystem. I think brew just didn't build it?

- What you expected to happen
The library to exist and be loaded

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install opencv
ls /usr/local/opt/opencv/lib/libopencv_sfm.3.4.dylib
<and have it be there>
I also tried brew install opencv --with-contrib but per https://github.com/Homebrew/homebrew-core/issues/28040#issuecomment-390439856, it is always there.

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libqmdnsengine.0.1.0.dylib
  /usr/local/lib/libzbar.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/qmdnsengine/abstractserver.h
  /usr/local/include/qmdnsengine/bitmap.h
  /usr/local/include/qmdnsengine/browser.h
  /usr/local/include/qmdnsengine/cache.h
  /usr/local/include/qmdnsengine/dns.h
  /usr/local/include/qmdnsengine/hostname.h
  /usr/local/include/qmdnsengine/mdns.h
  /usr/local/include/qmdnsengine/message.h
  /usr/local/include/qmdnsengine/prober.h
  /usr/local/include/qmdnsengine/provider.h
  /usr/local/include/qmdnsengine/qmdnsengine_export.h
  /usr/local/include/qmdnsengine/query.h
  /usr/local/include/qmdnsengine/record.h
  /usr/local/include/qmdnsengine/resolver.h
  /usr/local/include/qmdnsengine/server.h
  /usr/local/include/qmdnsengine/service.h
  /usr/local/include/zbar.h
  /usr/local/include/zbar/Decoder.h
  /usr/local/include/zbar/Exception.h
  /usr/local/include/zbar/Image.h
  /usr/local/include/zbar/ImageScanner.h
  /usr/local/include/zbar/Processor.h
  /usr/local/include/zbar/Scanner.h
  /usr/local/include/zbar/Symbol.h
  /usr/local/include/zbar/Video.h
  /usr/local/include/zbar/Window.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libzbar.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/zbar.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libzbar.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  numpy

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/etc/bash_completion.d/_brew_services
$ brew config
HOMEBREW_VERSION: 1.8.6-17-g1a78cc7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a78cc77d407077fd5ce09856165fb13722b3212
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8d0d13e425ea70d42d9597cd90e38e8949150329
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_131
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1

**Comment by fxcoudert** [comment]
Upstream documentation (https://docs.opencv.org/3.1.0/db/db8/tutorial_sfm_installation.html) states:

> The module is only available for Linux/GNU systems

so this appears to be expected on macOS.

**Comment by fxcoudert** [comment]
Hum, actually that note is gone in later versions…

**Comment by jhihn** [comment]
I was able to build OpenCV 4.0.0 with SFM from source on MacOS. Brew is shipping 3.4, I don't know if that makes a difference.

**Comment by fxcoudert** [comment]
We have a PR open for 4.0.1, but some other software does not work with it: https://github.com/Homebrew/homebrew-core/pull/35521

**Comment by jhihn** [comment]
Still an issue with 4.0.1
