### ISSUE TITLE
Homebrew-php cannot install any package view pecl (no target to make)

### ISSUE THREAD

**Issue by xxxdepot88** [Homebrew/homebrew-core#35398]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Hi, on mojave I have installed php@5.6, php@7.1, php@7.2 and php@7.3. I am trying to add extensions with pecl but I am getting "make: *** No rule to make target" below is example output for pecl install apcu and xdebug. I did try reinstalling php removing /usr/local/etc/php/7.3 with no luck, I also removed and reinstalled CommandLineTools "xcode-select --install" etc 

$ which php
/usr/local/bin/php

$ which pecl
/usr/local/bin/pecl

$ php -v
PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies

$ php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

$ pecl install apcu
downloading apcu-5.1.16.tgz ...
Starting to download apcu-5.1.16.tgz (94,032 bytes)
.....................done: 94,032 bytes

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in Validator.php on line 1933

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/Cellar/php/7.3.0/share/php/pear/PEAR/PackageFile/v2/Validator.php on line 1933
38 source files, building
running: phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
Enable internal debugging in APCu [no] : n
building in /private/tmp/pear/temp/pear-build-usernameIaYt99/apcu-5.1.16
running: /private/tmp/pear/temp/apcu/configure --with-php-config=/usr/local/opt/php/bin/php-config --enable-apcu-debug=n
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking target system type... x86_64-apple-darwin18.2.0
checking for PHP prefix... /usr/local/Cellar/php/7.3.0
checking for PHP includes... -I/usr/local/Cellar/php/7.3.0/include/php -I/usr/local/Cellar/php/7.3.0/include/php/main -I/usr/local/Cellar/php/7.3.0/include/php/TSRM -I/usr/local/Cellar/php/7.3.0/include/php/Zend -I/usr/local/Cellar/php/7.3.0/include/php/ext -I/usr/local/Cellar/php/7.3.0/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php/7.3.0/pecl/20180731
checking for PHP installed headers prefix... /usr/local/Cellar/php/7.3.0/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 1.1.1 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable APCu support... yes, shared
checking if APCu should be allowed to use rwlocks... yes
checking if APCu should be built in debug mode... n
checking if APCu should clear on SIGUSR1... no
checking if APCu will use mmap (or shm)... yes
checking if APCu should utilize spinlocks before flocks... no
checking whether the target compiler supports builtin atomics... yes
configure: WARNING: APCu has access to native rwlocks
configure: WARNING: APCu has access to mutexes
checking for sigaction... yes
checking for union semun... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking valgrind/memcheck.h usability... no
checking valgrind/memcheck.h presence... no
checking for valgrind/memcheck.h... no
checking for shm_open in -lrt... no
checking whether to include code coverage symbols... no
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from cc object... failed
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... no
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
running: make
make: *** No rule to make target `/private/tmp/pear/temp/pear-build-usernameIaYt99/apcu-5.1.16/modules/apcu.la', needed by `all'.  Stop.
ERROR: `make' failed

$ pecl install xdebug
downloading xdebug-2.6.1.tgz ...
Starting to download xdebug-2.6.1.tgz (283,961 bytes)
..........................................................done: 283,961 bytes

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in Validator.php on line 1933

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/Cellar/php/7.3.0/share/php/pear/PEAR/PackageFile/v2/Validator.php on line 1933
79 source files, building
running: phpize
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731
building in /private/tmp/pear/temp/pear-build-usernameF0rBmr/xdebug-2.6.1
running: /private/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/opt/php/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking target system type... x86_64-apple-darwin18.2.0
checking for PHP prefix... /usr/local/Cellar/php/7.3.0
checking for PHP includes... -I/usr/local/Cellar/php/7.3.0/include/php -I/usr/local/Cellar/php/7.3.0/include/php/main -I/usr/local/Cellar/php/7.3.0/include/php/TSRM -I/usr/local/Cellar/php/7.3.0/include/php/Zend -I/usr/local/Cellar/php/7.3.0/include/php/ext -I/usr/local/Cellar/php/7.3.0/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/Cellar/php/7.3.0/pecl/20180731
checking for PHP installed headers prefix... /usr/local/Cellar/php/7.3.0/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 1.1.1 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable Xdebug support... yes, shared
checking whether to enable Xdebug developer build flags... no
checking Check for supported PHP versions... supported (7.3.0)
checking for gettimeofday... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sys/poll.h usability... yes
checking sys/poll.h presence... yes
checking for sys/poll.h... yes
checking for cos in -lm... yes
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from cc object... failed
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... no
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.2.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
running: make
make: *** No rule to make target `/private/tmp/pear/temp/pear-build-usernameF0rBmr/xdebug-2.6.1/modules/xdebug.la', needed by `all'.  Stop.
ERROR: `make' failed

$ brew config
HOMEBREW_VERSION: 1.8.6-36-gf050e42
ORIGIN: https://github.com/Homebrew/brew
HEAD: f050e42d7d40fd0050e63e263be2aa3eed68ef83
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 147b22af7105aea724dbfb339916ac582f7e1442
Core tap last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
CLT headers: 10.1.0.0.1.1539992718

$ brew doctor
Your system is ready to brew.

$ brew list
apr
gettext
libiconv
nghttp2
re2c
apr-util	
glib		
libpng		
node		
readline
argon2		
gmp		
libpq		
oniguruma	
redis
aspell		
httpd		
libsodium	
openjpeg	
sqlite
autoconf	
icu4c		
libtiff		
openldap	
tidy-html5
boost		
imagemagick	
libtool		
openssl		
unixodbc
brotli		
jansson		
libyaml		
pcre		
webp
c-ares		
jemalloc	
libzip		
php		
wp-cli
composer	
jpeg		
little-cms2	
php@5.6		
xz
curl-openssl	
jq		
mcrypt		
php@7.1		
zsh
freetds		
libev		
mhash		
php@7.2
freetype	
libevent	
mysql		
pkg-config
gdbm		
libffi		
ncurses		
python

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by SMillerDev** [comment]
What does `php -i | grep extension_dir` show?

**Comment by xxxdepot88** [comment]
> What does `php -i | grep extension_dir` show?

$ php -i | grep extension_dir
extension_dir => /usr/local/lib/php/pecl/20180731 => /usr/local/lib/php/pecl/20180731
sqlite3.extension_dir => no value => no value

$ cd /usr/local/lib/php/pecl/20180731
  
$ ls -la
total 0

$ which sqlite3
/usr/bin/sqlite3

**Comment by caiblack** [comment]
Seeing similar issue on High Sierra.

$ php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'gettext' (tried: /usr/local/lib/php/pecl/20180731/gettext (dlopen(/usr/local/lib/php/pecl/20180731/gettext, 9): image not found), /usr/local/lib/php/pecl/20180731/gettext.so (dlopen(/usr/local/lib/php/pecl/20180731/gettext.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'gettext' (tried: /usr/local/lib/php/pecl/20180731/gettext (dlopen(/usr/local/lib/php/pecl/20180731/gettext, 9): image not found), /usr/local/lib/php/pecl/20180731/gettext.so (dlopen(/usr/local/lib/php/pecl/20180731/gettext.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl' (tried: /usr/local/lib/php/pecl/20180731/intl (dlopen(/usr/local/lib/php/pecl/20180731/intl, 9): image not found), /usr/local/lib/php/pecl/20180731/intl.so (dlopen(/usr/local/lib/php/pecl/20180731/intl.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'intl' (tried: /usr/local/lib/php/pecl/20180731/intl (dlopen(/usr/local/lib/php/pecl/20180731/intl, 9): image not found), /usr/local/lib/php/pecl/20180731/intl.so (dlopen(/usr/local/lib/php/pecl/20180731/intl.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring' (tried: /usr/local/lib/php/pecl/20180731/mbstring (dlopen(/usr/local/lib/php/pecl/20180731/mbstring, 9): image not found), /usr/local/lib/php/pecl/20180731/mbstring.so (dlopen(/usr/local/lib/php/pecl/20180731/mbstring.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'mbstring' (tried: /usr/local/lib/php/pecl/20180731/mbstring (dlopen(/usr/local/lib/php/pecl/20180731/mbstring, 9): image not found), /usr/local/lib/php/pecl/20180731/mbstring.so (dlopen(/usr/local/lib/php/pecl/20180731/mbstring.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/local/lib/php/pecl/20180731/mysqli (dlopen(/usr/local/lib/php/pecl/20180731/mysqli, 9): image not found), /usr/local/lib/php/pecl/20180731/mysqli.so (dlopen(/usr/local/lib/php/pecl/20180731/mysqli.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/local/lib/php/pecl/20180731/mysqli (dlopen(/usr/local/lib/php/pecl/20180731/mysqli, 9): image not found), /usr/local/lib/php/pecl/20180731/mysqli.so (dlopen(/usr/local/lib/php/pecl/20180731/mysqli.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/local/lib/php/pecl/20180731/pdo_mysql (dlopen(/usr/local/lib/php/pecl/20180731/pdo_mysql, 9): image not found), /usr/local/lib/php/pecl/20180731/pdo_mysql.so (dlopen(/usr/local/lib/php/pecl/20180731/pdo_mysql.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/local/lib/php/pecl/20180731/pdo_mysql (dlopen(/usr/local/lib/php/pecl/20180731/pdo_mysql, 9): image not found), /usr/local/lib/php/pecl/20180731/pdo_mysql.so (dlopen(/usr/local/lib/php/pecl/20180731/pdo_mysql.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'xmlrpc' (tried: /usr/local/lib/php/pecl/20180731/xmlrpc (dlopen(/usr/local/lib/php/pecl/20180731/xmlrpc, 9): image not found), /usr/local/lib/php/pecl/20180731/xmlrpc.so (dlopen(/usr/local/lib/php/pecl/20180731/xmlrpc.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'xmlrpc' (tried: /usr/local/lib/php/pecl/20180731/xmlrpc (dlopen(/usr/local/lib/php/pecl/20180731/xmlrpc, 9): image not found), /usr/local/lib/php/pecl/20180731/xmlrpc.so (dlopen(/usr/local/lib/php/pecl/20180731/xmlrpc.so, 9): image not found)) in Unknown on line 0
PHP 7.3.0 (cli) (built: Dec  7 2018 11:01:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
[renameme@holycrap ~]$ ll /usr/local/lib/php/pecl/20180731/gettext
ls: /usr/local/lib/php/pecl/20180731/gettext: No such file or directory
[renameme@holycrap ~]$ ll /usr/local/lib/php/pecl/20180731/
ls: /usr/local/lib/php/pecl/20180731/: No such file or directory

**Comment by SMillerDev** [comment]
that's not a similar issue at all, your PHP is just trying to load extensions that aren't there anymore due to a version upgrade. Just do `pecl install xmlrpc` and all the others you need.

**Comment by caiblack** [comment]
Ah, I see now. "gettext", "pdo_mysql", and "xmlrpc" are old and gone.

I may been the wrong channel here, but how do I "fix" Homebrew to not use or attempt to find those old versions?

**Comment by SMillerDev** [comment]
That's in your PHP config, homebrew doesn't do anything about it.

**Comment by caiblack** [comment]
Thanks, @SMillerDev.

**Comment by caiblack** [comment]
Just for anyone searching for resolution to the same issue:

In my "/usr/local/etc/php/7.3/php.ini", I had manually uncommented the extensions listed in my error above because I knew that I needed them in my project. Well, I had been using PHP 5.6 previously. Things have **changed** with PHP 7.3.

After re-commenting those extension lines, everything works as expected.
