### ISSUE TITLE
CMUS: Error: invalid option: --with-ffmpeg

### ISSUE THREAD

**Issue by ibrokemypie** [Homebrew/homebrew-core#35459]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
brew gist-logs cmus
Error: No logs.
```
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
brew config
HOMEBREW_VERSION: 1.8.6-38-g8842832
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8842832cf412382d8c74dc9c5399bd122f44e0c9
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9ebbc474d816c5d0dda77117e74679e0cccb40aa
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Install cmus with ffmpeg and opusfile support so I could listen to my library which is in various formats including opus
- What happened (include command output)
brew refused, stating that --with-ffmpeg wasnt an option.
I tried reversing them so opus was first, it refused saying that wasnt an option.
I tried with the options before cmus, same thing.
- What you expected to happen
Build and install cmus with ffmpeg and opusfile support
- Step-by-step reproduction instructions (by running `brew install` commands)
``brew install cmus --with-ffmpeg --with-opusfile``

**Comment by fxcoudert** [comment]
- Can you please paste your input and output exactly, inside a code block? Things are working here, so it's possible you have included a weird Unicode or control character in your command.
- Can you paste the output of `brew info cmus`?

**Comment by ibrokemypie** [comment]
```
brew reinstall cmus --with-ffmpeg --with-opusfile
Error: invalid option: --with-ffmpeg
```

weirdly, I just tried it again manually uninstall and reinstalling, something which I had already tried, in the same terminal window even, and this time it has worked. No idea whats going on but I guess this can be close now?

**Comment by fxcoudert** [comment]
Closing.
