### ISSUE TITLE
isync formula forces dependency on berkeley-db

### ISSUE THREAD

**Issue by dabrahams** [Homebrew/homebrew-core#3545]
berkeley-db should actually be an optional dependency; having it installed when you build simply disables one obscure feature of isync (called AltMap).  I tried to edit the formula and submit a pull request, but I'm not sure how to do without breaking the bottles, which are linked against Berkeley DB.  Unfortunately, isync's configure doesn't have an option (like `--without-bdb`) to disable its use of Berkeley DB, but if Berkeley DB isn't found during configure isync will build without it.

P.S. this is a concern for me because Berkeley DB introduces an AGPL3 dependency.

**Comment by MikeMcQuaid** [comment]
> I tried to edit the formula and submit a pull request, but I'm not sure how to do without breaking the bottles, which are linked against Berkeley DB.

That's OK, we'll create new bottles when we pull. Could you try again to open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
@dabrahams hello again! This will fix it: https://github.com/Homebrew/homebrew-core/pull/3677.

**Comment by ilovezfs** [comment]
@dabrahams Fixed.

**Comment by dabrahams** [comment]
I :heart: @ilovezfs
