### ISSUE TITLE
glfw and glew missing framework declarator in pkg-config

### ISSUE THREAD

**Issue by reinderien** [Homebrew/homebrew-core#35493]
- [✓] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [✓] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [✓] ran `brew update` and can still reproduce the problem?
- [✓] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [✓] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs glew
Error: No logs.
```

- [✓] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c328977c091c9cdf730bfd297c006553cd4d5876
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.4, 1.8.0_172, 1.8.0_162, 1.7.0_80
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

To help us debug your issue please explain:

**What you were trying to do (and why)**
I am trying to build a very basic OpenGL application using glew and glfw libraries.

**What happened (include command output)**
When I run `pkg-config`, I get:

```
$ pkg-config --libs glew glfw3
-L/usr/local/Cellar/glew/2.1.0/lib -L/usr/local/Cellar/glfw/3.2.1/lib -lGLEW -lglfw
```

**What you expected to happen**
I expect `-framework OpenGL` to be included in the output of `pkg-config`. Since it isn't, the application fails to link. The workaround is to manually add `-framework OpenGL` to `$ldflags`, but this should not be needed.

**Step-by-step reproduction instructions (by running `brew install` commands)**

```
brew install glew glfw
pkg-config --libs glew glfw3
```

**Comment by reinderien** [comment]
For reference, the unmodified `pkg-config` file seems to be here:

https://github.com/nigels-com/glew/blob/master/glew.pc.in

**Comment by fxcoudert** [comment]
We are not modifying the `.pc` files for `glew` and `glfw`, and are coming directly from their respective upstream project. You will have to take that complain up with them, it is the behaviour they decided on.
