### ISSUE TITLE
Homebrew Mac OSX Mojave llvm fatal error: 'wchar.h' file 

### ISSUE THREAD

**Issue by austindavidbrown** [Homebrew/homebrew-core#35506]
Compile this program with llvm 7.0.1 on Mac OSX Mojave with command line tools installed without Xcode:

```cpp
#include <iostream>
int main() {
  std::cout << "foo";
}
```
and get this error:

```
/usr/local/Cellar/llvm/7.0.1/include/c++/v1/wchar.h:119:15: fatal error: 'wchar.h' file
      not found
#include_next <wchar.h>
              ^~~~~~~~~
1 error generated.
```

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by austindavidbrown** [comment]
This post has the solution.

https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave
