### ISSUE TITLE
Parallele build of llvm 7.0.1 fails on macOS 10.14.2

### ISSUE THREAD

**Issue by ducky427** [Homebrew/homebrew-core#35513]
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I am trying to install llvm 7.0.1 using homebrew on macOS 10.14.2. I get the following error:

```
gmake[9]: Leaving directory '/private/tmp/llvm-20181228-67831-vj4niq/llvm-7.0.1.src/build/tools/clang/runtime/compiler-rt-bins'
gmake[8]: *** [CMakeFiles/Makefile2:4023: lib/asan/CMakeFiles/RTAsan_dynamic.osx.dir/all] Error 2
gmake[8]: Leaving directory '/private/tmp/llvm-20181228-67831-vj4niq/llvm-7.0.1.src/build/tools/clang/runtime/compiler-rt-bins'
gmake[7]: *** [Makefile:130: all] Error 2
gmake[7]: Leaving directory '/private/tmp/llvm-20181228-67831-vj4niq/llvm-7.0.1.src/build/tools/clang/runtime/compiler-rt-bins'
gmake[6]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/build.make:116: tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
gmake[6]: Leaving directory '/private/tmp/llvm-20181228-67831-vj4niq/llvm-7.0.1.src/build'
gmake[5]: *** [CMakeFiles/Makefile2:35099: tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
gmake[5]: Leaving directory '/private/tmp/llvm-20181228-67831-vj4niq/llvm-7.0.1.src/build'
gmake[4]: *** [Makefile:155: all] Error 2
gmake[4]: Leaving directory '/private/tmp/llvm-20181228-67831-vj4niq/llvm-7.0.1.src/build'
make[3]: *** [tools/xcode-toolchain/CMakeFiles/build-xcode-toolchain] Error 2
make[2]: *** [tools/xcode-toolchain/CMakeFiles/build-xcode-toolchain.dir/all] Error 2
make[1]: *** [tools/xcode-toolchain/CMakeFiles/install-xcode-toolchain.dir/rule] Error 2
make: *** [install-xcode-toolchain] Error 2
```

Here is the gist-logs for it: https://gist.github.com/ducky427/7a674353e7688a55ca4b1846a67ae91c

**Comment by uyjulian** [comment]
Getting same error here.

**Comment by goxberry** [comment]
I can also reproduce this error.

**Comment by ducky427** [comment]
Setting `HOMEBREW_MAKE_JOBS` to `2` doesn't work but setting it to `1` does work.

**Comment by goxberry** [comment]
Replacing the Unix Makefiles backend with Ninja resolves this bug, and should also accelerate the build without altering `HOMEBREW_MAKE_JOBS` at the cost of adding `ninja` as a build dependency.

**Comment by goxberry** [comment]
@fxcoudert Given that #35562 was reverted, should this issue be reopened? I still see issues with building LLVM from source on macOS 10.13.6 & XCode 10 with GNU Make and Ninja, on macOS 10.13.6 & XCode 9.2 with GNU Make, and on macOS 10.14.2 & XCode 10 with GNU Make.

**Comment by fxcoudert** [comment]
> I still see issues with building LLVM from source on macOS 10.13.6 & XCode 10 with GNU Make and Ninja

So ninja does not fix the issue, after all?

**Comment by dominiklohmann** [comment]
I got it to work by increasing my ulimit es explained [here](https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/). This fixes the resource issues when using Unix Makefiles.

**Comment by goxberry** [comment]
@fxcoudert Ninja fixes the issue on macOS 10.14.2 with XCode 10. I don’t have access to all of my machines at the moment, but I can test on macOS 10.13.6 with XCode 9.2 and macOS 10.14.2 with XCode 10.1 within the next day or two, and in a few days, I’ll have access to another machine with macOS 10.13.6 with XCode 10.

**Comment by fxcoudert** [comment]
Apparently, not for everyone. And the issues does not manifest with make on our CI machines. We thus need to understand what causes the issue, and if there is a systematic workaround.

Ninja is _not_ acceptable at this time, as it bloats the size of all the libraries (see #35562) for reasons unknown so far.

**Comment by raylee** [comment]
A data point: I had the same problem under 10.14.3. Following the instructions in the page linked to in https://github.com/Homebrew/homebrew-core/issues/35513#issuecomment-451647115 works for me as well.

**Comment by fxcoudert** [comment]
I'm going to close this for now, as the root cause seems to lie outside of Homebrew, there is a known work-around and the builds are fine on our CI.

I would suggest you report the bug upstream.
