### ISSUE TITLE
kakoune doesn't work properly because of ncurses 5 on OSX

### ISSUE THREAD

**Issue by joakin** [Homebrew/homebrew-core#35514]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
=> brew gist-logs kakoune
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
=> brew config
HOMEBREW_VERSION: 1.8.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 858c5e1afb0eb00079a4f014e8fbedf9065d50e4
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d111a9fd1551365d9b6f02288b26693295a13c11
Core tap last commit: 36 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_VISUAL: nvim
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.1-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
```
```
=> brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

Using an installed formula: `kakoune`

- What happened (include command output)

Trying to use the mouse with the editor. Run `kak long-file.txt` and try to scroll or drag with the mouse.

I found an issue in kakoune itself: https://github.com/mawww/kakoune/issues/2651

Apparently kakoune in OSX builds against a very old ncurses version (5.4) ([info](https://github.com/mawww/kakoune/issues/2651#issuecomment-450127199)).

It was [suggested by the maintainers](https://github.com/mawww/kakoune/issues/2651#issuecomment-450238199) that the brew formula should specify a more recent ncurses version.

- What you expected to happen

Mouse scrolling on kakoune should work fine on OSX like it does on Linux.

- Step-by-step reproduction instructions (by running `brew install` commands)

* `brew install kakoune`
* `kak long-file-that-you-can-scroll.txt`
*  Try scrolling up and down with the mouse
* Expected
    * Mouse scrolling and clicking-dragging selection works
* Actual
    * Mouse scrolling only works scrolling upwards

**Comment by fxcoudert** [comment]
We would consider a PR that uses `ncurses` as a dependency in the `kakoune` formula.
