### ISSUE TITLE
eyeD3 fails when using the display plugin

### ISSUE THREAD

**Issue by halloleo** [Homebrew/homebrew-core#35512]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/halloleo/d9ec997f4662df8645f080f7b3f444ab

### What you were trying to do (and why)

After installing eye-d3 I tried using `eyeD3` with the `display` plugin (because it is listed in the installed plugins - checked via `eyeD3 -L).

### What happened (include command output)

Got the error that the `grako` package is missing:

```
Unknown module 'grako'
Please install grako! E.g. $ pip install grako
```

### What you expected to happen

Proper output of eyeD3 with the display plugin. (In the sample case output of the album information.)

### Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install eye-d3`
2. `eyeD3 <mp3-file>  -P display -p '%A%' `

**Comment by Moisan** [comment]
PR #35666 should have fixed this issue. Feel free to reopen if that's not the case.
