### ISSUE TITLE
Doesn't allow building cairo with xlib backend

### ISSUE THREAD

**Issue by npyl** [Homebrew/homebrew-core#35539]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to install `cairo` in order to compile conky with cairo support.

- What happened (include command output)

Cairo installed just fine, but I realised that it didn't install the xlib backend support.
Thus, I tried with `brew install cairo --with-xlib` which is a supported switch (by cairo library) as I can see from [cairo.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cairo.rb) and (i guess) used to be supported according to [this](https://github.com/Homebrew/homebrew-core/issues/16646) issue.

- What you expected to happen

Install cairo with xlib support.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew update
brew install cairo --with-x11
# or even with
# brew install cairo --with-xlib
```

**Comment by npyl** [comment]
Instead, all brew does is print this message:
<img width="848" alt="screenshot 2018-12-29 at 14 10 39" src="https://user-images.githubusercontent.com/12190878/50538148-8c082780-0b73-11e9-80d2-e7bc13c0fc0b.png">

**Comment by fxcoudert** [comment]
Indeed, we do not support building cairo with X11 / Xlib. That option was removed in https://github.com/Homebrew/homebrew-core/pull/27484 and we are unlikely to introduce it again (see #31510 for the reason).

A solution would be to maintain a custom `cairo` formula in a personal tap.

**Comment by SMillerDev** [comment]
Taps are up to you, homebrew doesn't need to accept anything for it.
