### ISSUE TITLE
brew install hbase The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by 91xcode** [Homebrew/homebrew-core#35535]
brew install hbase

==> Downloading https://www.apache.org/dyn/closer.cgi?path=hbase/hbase-1.2.8/hbase-1.2.8-bin.tar.gz
==> Downloading from http://mirrors.shu.edu.cn/apache/hbase/hbase-1.2.8/hbase-1.2.8-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-eu.apache.org/dist/hbase/hbase-1.2.8/hbase-1.2.8-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-us.apache.org/dist/hbase/hbase-1.2.8/hbase-1.2.8-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "hbase"
Download failed: https://www-us.apache.org/dist/hbase/hbase-1.2.8/hbase-1.2.8-bin.tar.gz

i can not find this files...  i use brew update    it is not work!!!

**Comment by SMillerDev** [comment]
Can you please fill out the issue template? It contains information that is important to debug the issue you have. I'm going to close this until you add the required information.
