### ISSUE TITLE
`qcachegrind` formula builds but unusable: qt.qpa.plugin: Could not find the Qt platform plugin

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#35547]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
N/A since it builds find
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
N/A

```
brew install qcachegrind
works

qcachegrind
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by fxcoudert** [comment]
Can you confirm whether installing from source fixes the issue? `brew reinstall -s qcachegrind`

**Comment by fxcoudert** [comment]
This is working fine on our test machines… we need a full output of `brew gist-logs qcachegrind` after you run `brew reinstall -s qcachegrind` to try and understand what is happening

**Comment by timotheecour** [comment]
//gist.github.com/429f0f46cafd615ed17714e464c7519b

**Comment by fxcoudert** [comment]
What version of Qt do you have installed?

**Comment by timotheecour** [comment]
ping

**Comment by SMillerDev** [comment]
Does the issue still occur?

**Comment by timotheecour** [comment]
yes, exact same issue

**Comment by yunosh** [comment]
This still happens with the latest qt and qcachegrind
