### ISSUE TITLE
p11-kit fails to build on my machine with the bottled libffi

### ISSUE THREAD

**Issue by adamv** [Homebrew/homebrew-core#35559]
When trying to `brew upgrade emacs` from 25.x to 26.x, `p11-kit` fails to build on my machine with the bottled `libffi`.

The `p11-kit` compilation fails to find the `ffi.h` header file.

This is almost certainly caused by me not doing a standard install into `/usr/local`.

Doing a build-from-source installation of libffi allowed the emacs upgrade to proceed as expected.

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
