### ISSUE TITLE
openssl - Error: Permission denied - /usr/local/etc/openssl/certs

### ISSUE THREAD

**Issue by peterromfeldhk** [Homebrew/homebrew-core#3559]
Hi,

I found a locked issue here https://github.com/Homebrew/legacy-homebrew/issues/29238

Just wanted to say what the actual problem was, older openssl installations don't have this directory `/usr/local/etc/openssl/certs`,
The error says permission denied, but its actually directory doesn't exist!

Full Error:
```
==> Installing openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2h_1.el_capitan.bottle.tar.gz
Already downloaded: /Users/pair/Library/Caches/Homebrew/openssl-1.0.2h_1.el_capitan.bottle.tar.gz
==> Pouring openssl-1.0.2h_1.el_capitan.bottle.tar.gz
Error: Permission denied - /usr/local/etc/openssl/certs
Warning: Bottle installation failed: building from source.
==> Downloading https://www.openssl.org/source/openssl-1.0.2h.tar.gz
Already downloaded: /Users/pair/Library/Caches/Homebrew/openssl-1.0.2h.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2h_1 --openssldir=/usr/local/etc/openssl no-ssl2 zlib-dynamic shared enab
==> make depend
==> make
==> make test
==> make install MANDIR=/usr/local/Cellar/openssl/1.0.2h_1/share/man MANSUFFIX=ssl
Last 15 lines from /Users/pair/Library/Logs/Homebrew/openssl/05.make:
SSL_want_read.3ssl => SSL_want.3ssl
SSL_want_write.3ssl => SSL_want.3ssl
SSL_want_x509_lookup.3ssl => SSL_want.3ssl
installing man3/SSL_write.3ssl
installing man3/d2i_SSL_SESSION.3ssl
i2d_SSL_SESSION.3ssl => d2i_SSL_SESSION.3ssl
installing man3/ssl.3ssl
Cannot create directory /usr/local/etc/openssl/certs: Permission denied
created directory `/usr/local/Cellar/openssl/1.0.2h_1/bin'
created directory `/usr/local/Cellar/openssl/1.0.2h_1/lib'
created directory `/usr/local/Cellar/openssl/1.0.2h_1/lib/engines'
created directory `/usr/local/Cellar/openssl/1.0.2h_1/lib/pkgconfig'
created directory `/usr/local/Cellar/openssl/1.0.2h_1/include'
created directory `/usr/local/Cellar/openssl/1.0.2h_1/include/openssl'
make: *** [install_sw] Error 13

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
openssl broken on 10.6.8 https://github.com/Homebrew/homebrew-core/issues/2766
```

I moved `/usr/local/etc/openssl` to `/usr/local/etc/openssl.bak` because i did not want to mess around with permissions. When i got a bit more curious later i found that `/usr/local/etc/openssl/certs` was actually missing:

```
> sudo ls -lah /usr/local/etc/openssl.bak/
total 600
drwxr-xr-x   5 exicon  admin   170B Jan  4  2016 .
drwxrwxr-x  12 pair    admin   408B Aug  3 09:57 ..
-rw-r--r--   1 exicon  admin   285K Jan  4  2016 cert.pem
drwxr-xr-x   9 exicon  admin   306B Mar 10  2015 misc
-rw-r--r--   1 exicon  admin    11K Jan  4  2016 openssl.cnf
```

Hope that helps :)

**Comment by MikeMcQuaid** [comment]
I'm not sure I totally understand here; is a change needed to the formula? If so, could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by peterromfeldhk** [comment]
I was going a bit through the source, but i have 0 ruby exp and couldn't find anything pointing to the problem.

I also don't know how to get old formulas, but if you wanna reproduce the error:

* uninstall openssl
* remove/backup `/usr/local/etc/openssl`
* get and install about 1 year old formula
* after installed old, try to install new formula, you most likely get permission error
* mkdir `/usr/local/etc/openssl/certs`, with right permissions
* install new formula again, most likely will succeed now

**Comment by peterromfeldhk** [comment]
sorry it was indeed a permission error with previous user installed openssl
