### ISSUE TITLE
Apache mesos 1.0

### ISSUE THREAD

**Issue by leaxoy** [Homebrew/homebrew-core#3561]
Apache mesos has released major version 1.0.  Can someone update it?

**Comment by DomT4** [comment]
You're more than welcome to try & submit a PR.

Happy to help as best we can with the process, but it looks increasingly like it'll need someone familiar with `mesos` to help get it through; has already scared off two maintainers, heh: https://github.com/Homebrew/homebrew-core/pull/3538.

**Comment by leaxoy** [comment]
Thx😀
