### ISSUE TITLE
`llvm` should not ship `libomp`

### ISSUE THREAD

**Issue by adah1972** [Homebrew/homebrew-core#35634]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

This is not about an official formula. I have already asked on Discourse, and SMillerDev suggests an issue on homebrew-core might be more appropriate.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Irrelevant.

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Irrelevant.

To help us debug your issue please explain:
- What you were trying to do (and why)

Build something (like ImageMagick) using llvm and libomp.

- What happened (include command output)

The resulting binary depends on /usr/local/opt/llvm/lib/libomp.dylib.

- What you expected to happen

The resulting binary should depend on /usr/local/opt/libomp/lib/libomp.dylib, not the llvm one.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install -s https://raw.githubusercontent.com/adah1972/homebrew-core/no-std/Formula/imagemagick.rb
otool -L /usr/local/bin/magick
```

**Comment by fxcoudert** [comment]
Contrary to Debian, Homebrew's choice is to ship compilers with their full runtime as a single package. `gcc` includes all runtimes libraries, including `libgomp`, and `llvm` includes `libomp`.

At some point, we introduced `libomp` to help some software circumvent the fact that Apple does not ship the openmp runtime libraries, although its compilers are OpenMP capable. The discussion was that, while it was somewhat contrary to our general rule (do not ship the same software in two different forms), it was useful to some users. The `cryfs` formula is using that. However, we should not cripple the `llvm` formula (which as 132,567 downloads a year) by removing one of its runtime libraries, and it should stay a complete, standalone package. That's the best user experience.

----

Now, coming to the specific issue at hand, which is #35519: you want Homebrew's imagemagick to ship with OpenMP support. It should be possible to achieve this by passing the right flags to the system compiler and linking against Homebrew's `libomp`, as `crysfs` does. So either you haven't found the right variables yet, or their `configure` script is not flexible enough to allow it. The former is a problem for us to fix, the second is a problem for ImageMagick to fix.

I would also like to note that ImageMagick ships a binary distribution of their product for macOS, and it does not include OpenMP…

**Comment by adah1972** [comment]
Thanks for the detailed explanation and the fix for ImageMagick (also good to know how to make ./configure detect OpenMP with Apple Clang).
