### ISSUE TITLE
php 7.3 imagick - Symbol not found: __zval_ptr_dtor

### ISSUE THREAD

**Issue by ramyareye** [Homebrew/homebrew-core#35630]
- What you were trying to do (and why)
I try php -v
- What happened (include command output)
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20170718/imagick.so' (tried: /usr/local/lib/php/pecl/20170718/imagick.so (dlopen(/usr/local/lib/php/pecl/20170718/imagick.so, 9): Symbol not found: __zval_ptr_dtor
  Referenced from: /usr/local/lib/php/pecl/20170718/imagick.so
  Expected in: flat namespace
 in /usr/local/lib/php/pecl/20170718/imagick.so), /usr/local/lib/php/pecl/20180731//usr/local/lib/php/pecl/20170718/imagick.so.so (dlopen(/usr/local/lib/php/pecl/20180731//usr/local/lib/php/pecl/20170718/imagick.so.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/pecl/20170718/imagick.so' (tried: /usr/local/lib/php/pecl/20170718/imagick.so (dlopen(/usr/local/lib/php/pecl/20170718/imagick.so, 9): Symbol not found: __zval_ptr_dtor
  Referenced from: /usr/local/lib/php/pecl/20170718/imagick.so
  Expected in: flat namespace
 in /usr/local/lib/php/pecl/20170718/imagick.so), /usr/local/lib/php/pecl/20180731//usr/local/lib/php/pecl/20170718/imagick.so.so (dlopen(/usr/local/lib/php/pecl/20180731//usr/local/lib/php/pecl/20170718/imagick.so.so, 9): image not found)) in Unknown on line 0
PHP 7.3.0 (cli) (built: Dec  7 2018 11:01:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0, Copyright (c) 1999-2018, by Zend Technologies
```
- What you expected to happen
I need it to work!
- Step-by-step reproduction instructions (by running `brew install` commands)
I installed php, imagick and defined ext-imagick.ini file under `/usr/local/etc/php/7.3/conf.d` :
```
extension = "/usr/local/lib/php/pecl/20170718/imagick.so"
```

**Comment by SMillerDev** [comment]
You configured 7.3 to load 7.2 extensions, that won't work. Try reinstalling it through pecl.

**Comment by ramyareye** [comment]
I upgraded it through brew and tried to install it again with pecl, no chance.
possible to give me a guide ? 
thanks

**Comment by SMillerDev** [comment]
set `extension_dir = "/usr/local/lib/php/pecl/20180731"` in php.ini. If that's not set already.
run `pecl install imagick`
change `extension = "/usr/local/lib/php/pecl/20170718/imagick.so"` to `extension = "imagick"` in your config file.

**Comment by SMillerDev** [comment]
I'm going to close this since it's a user config issue and not an issue with brew.

**Comment by ramyareye** [comment]
Thanks for explanation, I should complete it:
set `extension_dir = "/usr/local/lib/php/pecl/20180731"` in php.ini. If that's not set already.
run pecl install imagick
