### ISSUE TITLE
Cannot make zsh include pcre even when installing from source

### ISSUE THREAD

**Issue by strindberg** [Homebrew/homebrew-core#35649]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/52683114aec00b8dc3db5887ec97cfb2
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Since the zsh formula no longer accepts options (because of #31510 I assume), I tried to configure zsh to include PCRE support by editing the zsh formula and then reinstall zsh from source. However, pcre support is still not built into my installation of zsh. At start, zsh reports:

failed to load module `zsh/pcre': dlopen(/usr/local/Cellar/zsh/5.6.2_1/lib/zsh/pcre.bundle, 9): image not found

This is what I did to include pcre:
- brew remove zsh
- brew edit zsh
- I added the line '"--enable-pcre",' to the configure options in the formula, and saved.
- brew install -s --verbose --debug zsh

I can see in the log from configure that the pcre configuration is taken into account, but as I start zsh, I see the above-mentioned message.

**Comment by SMillerDev** [comment]
We don't support modified formula (that add back features homebrew removed). If you have trouble compiling zsh you should take that up with the ZSH developers.

**Comment by strindberg** [comment]
I'm not sure I follow: is it no longer possible to use "brew edit <formula>" to keep a local modification of a formula?

**Comment by SMillerDev** [comment]
It sure is, but we can't support every change everyone does. We support the software versions we ship and test. If you change them support is up to you.

**Comment by mrietveld** [comment]
This is not a problem with zsh -- the problem is that brew install -s does not use the formula provided. (If you locally edit the formula nd then do brew install -s, the options used in the 'install' part of the formula will not be used.

**Comment by mrietveld** [comment]
So, I did the following: 
1. saved output from `brew install -s zsh`
2. did `brew uninstall zsh; brew install -i -s zsh`
3. ran the exact same commands (`./configure ..`, `make install`, etc.. ) in the interactive build
4. everything worked. 

In other words, doing the same things that the non-interactive build does, but in the interactive build, produces a different result than in the non-interactive build. This would suggest to me that the problem is with brew, not with the zsh build.
