### ISSUE TITLE
Many formulas remove options

### ISSUE THREAD

**Issue by JackDrogon** [Homebrew/homebrew-core#35661]
Recently I found that many softwar removed the option, such as `erlang`, `global`, `vim`. So how can I   use those past options.

**Comment by fxcoudert** [comment]
This is discussed in #31510 

You can maintain formulas in a personal tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
You can browse the repository to check for older versions of the formulas, with options, or use the `brew extract --version` command.
