### ISSUE TITLE
Gmsh GUI broken

### ISSUE THREAD

**Issue by PierreMarchand20** [Homebrew/homebrew-core#35664]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I just installed Gmsh using `brew install gmsh --with-fltk --with-opencascade`, it seems to work except the GUI. Nothing appear in the options
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/15056323/50640254-9c9a1280-0f64-11e9-817f-3eaa97e6c74c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/15056323/50640589-96586600-0f65-11e9-8baa-4eba448b1162.png">

Then I installed it with the binaries on their website and it works great, so may be it comes from the compilation ?
Here the gist : https://gist.github.com/PierreMarchand20/44d9af3eaf7bf7b375f85caf17693296

**Comment by Moisan** [comment]
From [gmsh README](https://gitlab.onelab.info/gmsh/gmsh/blob/master/README.txt):
```
Building the graphical user interface requires FLTK 1.3.2 or
higher (FLTK-dev 1.4 is required on macOS Mojave; http://fltk.org)
```
Current version of `fltk` on homebrew-core is `stable 1.3.4-2` which probably explain the issue.

**Comment by Moisan** [comment]
Feel free to ask fltk for a new tagged release.

**Comment by PierreMarchand20** [comment]
Well, it seems that it won't be fix anytime soon #33342. It would be nice to put a warning or say that this option is not available with Mojave. At the end, homebrew is a package management system, so one would expect to not have this kind of problem. But I guess it should be done when trying to install fltk, so I will report the issue to them.

**Comment by PierreMarchand20** [comment]
I just saw that in Homebrew 2.0.0, all options will be removed, does it mean that we will not be able to install gmsh with fltk ?

**Comment by Ziudin** [comment]
Mungkin
