### ISSUE TITLE
Fltk issue on Mojave

### ISSUE THREAD

**Issue by PierreMarchand20** [Homebrew/homebrew-core#35682]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I am aware of #33342, but then installing fltk 1.3.4 on Mojave should not be possible. It would prevent installing it as a dependency and ending up with a broken install (see my issue with gmsh #35664).

**Comment by Moisan** [comment]
As @fxcoudert stated in #33342, we ship stable releases. Stable in the sense that upstream releases it as stable. Regarding #35664, there are two possible solutions: (1) contact upstream (`fltk`) and ask for a 1.4 release as soon as possible; (2) create [your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) with `fltk` 1.4. See [this tap](https://github.com/gtDMMB/homebrew-core) for example with `fltk` 1.4.

**Comment by PierreMarchand20** [comment]
Well, I still think it is weird that I can install a broken library because of a dependency while using a dependency manager. 

As for as I know (but I do not know that mush otherwise I would have suggested a PR), it is possible to put condition on the version of the OS and the dependencies I think it would be relevant to add the fact that `fltk` lower that 1.4 cannot be installed on Mojave. Otherwise, you will end up with countless issues on the same topic.

**Comment by PierreMarchand20** [comment]
Notice that I am not asking to add `fltk` 1.4 before it gets to a stable version, I just think that for the sake of consistency, it should not be able to install `fltk` lower that 1.4 with Mojave.

**Comment by fxcoudert** [comment]
Maybe we should declare `fltk` unsupported on High Sierra and Mojave, indeed (both have 10.14 SDK). https://www.fltk.org/str.php?L3496

Or we should see if this single patch can fix the issue: https://github.com/fltk/fltk/commit/f76d2a2bf8c35c0c313f05bbd6deda49dd344efc
But I'm not even sure it applies on top of 1.3

**Comment by crmoore** [comment]
@fxcoudert It does with some massaging.  Macports has it applied to their fltk pacakge.  I'm running the following in a local tap, and it's working.

```
class FltkAT1342 < Formula
  desc "Cross-platform C++ GUI toolkit"
  homepage "https://www.fltk.org/"
  url "https://www.fltk.org/pub/fltk/1.3.4/fltk-1.3.4-2-source.tar.gz"
  mirror "https://dl.bintray.com/homebrew/mirror/fltk-1.3.4-2.tar.gz"
  version "1.3.4-2"
  sha256 "25d349c18c99508737d48f225a2eb26a43338f9247551cab72a317fa42cda910"

  bottle do
    sha256 "fbf193393bb8d95b303e3e9bdda7b7808c8211b06ec76017ef386f3dac3ca8aa" => :mojave
    sha256 "5dd4bbb5cf10af5e0a1ff2f29c6d12657f09626fab43811b441b27c677afd0af" => :high_sierra
    sha256 "e22929035ced94a301c1294de6d305079e34d9709d3e9551b19555ab2f06656e" => :sierra
    sha256 "5481ffce354c2c98ed7634b036d678c7476780085e1a518af186f2e4b22d2c31" => :el_capitan
  end

  depends_on "jpeg"
  depends_on "libpng"

  def install
    system "./configure", "--prefix=#{prefix}",
                          "--enable-threads",
                          "--enable-shared"
    system "make", "install"
  end

  patch :p0 do
    url "https://raw.githubusercontent.com/macports/macports-ports/master/aqua/fltk/files/patch-fix_empty_window.diff"
    sha256 "9483adfc70c25bd560c4400972d8d12d288ee78c27b1c03c965aa59818e59152"
  end


  test do
    (testpath/"test.cpp").write <<~EOS
      #include <FL/Fl.H>
      #include <FL/Fl_Window.H>
      #include <FL/Fl_Box.H>
      int main(int argc, char **argv) {
        Fl_Window *window = new Fl_Window(340,180);
        Fl_Box *box = new Fl_Box(20,40,300,100,"Hello, World!");
        box->box(FL_UP_BOX);
        box->labelfont(FL_BOLD+FL_ITALIC);
        box->labelsize(36);
        box->labeltype(FL_SHADOW_LABEL);
        window->end();
        return 0;
      }
    EOS
    system ENV.cxx, "test.cpp", "-L#{lib}", "-lfltk", "-o", "test"
    system "./test"
  end
end
```

**Comment by fxcoudert** [comment]
@crmoore would you mind submitting a pull request for us?

**Comment by crmoore** [comment]
@fxcoudert done https://github.com/Homebrew/homebrew-core/pull/35881
