### ISSUE TITLE
openjazz doesn't display video on Mojave

### ISSUE THREAD

**Issue by Kreeblah** [Homebrew/homebrew-core#35730]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/Kreeblah/0b1b2d26e5576c869059c85f0c28f80f
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) I was trying to install openjazz.
- What happened (include command output) openjazz and its dependencies appeared to install correctly, however when starting it, a window appears without any video (it's just grey inside).  Hitting the enter key a few times led to sounds I'd expect to hear, so it does seem to be running.  Just without video output.
- What you expected to happen I expected openjazz to run with audio and video.
- Step-by-step reproduction instructions (by running `brew install` commands) `brew install openjazz`, then `openjazz`

**Comment by SMillerDev** [comment]
This seems to be an issue in SDL, the underlaying software. https://github.com/Homebrew/homebrew-core/issues/33016 tracks this but it seems the version openjazz uses is no longer supported.
