### ISSUE TITLE
Warning: opencv dependency gcc was built with a different C++ standard

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#35764]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
```
Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdb_tim
  gdb
  llvm_wasm.bak1
  opencv.bak1
  ripgrep

Warning: Your Homebrew's prefix is not /usr/local.
```

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
brew gist-logs opencv
https://gist.github.com/ab9b1ce011bc49e6f3e122856c2221f8

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
N/A

## note
* when I ran `brew upgrade opencv` today, it failed, but may be hard to reproduce, because the 2nd time it worked (but with this warning, which is reproducible)

* also reported here https://github.com/Homebrew/homebrew-core/issues/34783#issuecomment-445466879 but the issue was about another package

@fxcoudert said here https://github.com/Homebrew/homebrew-core/issues/34783#issuecomment-445526826
> The warning is actually not an issue, it's a false positive. Are you experiencing problems beyond the warning?

however, this doesn't give me confidence that it won't cause subtle issues (eg different output down the line)

**Comment by fxcoudert** [comment]
I can confirm this is a false positive. `openblas` is built with `gcc` dependency because it uses `gfortran`, but it's not actually using that C++ library.
