### ISSUE TITLE
Evince required shared-mime-info

### ISSUE THREAD

**Issue by kno10** [Homebrew/homebrew-core#35795]
On a fresh homebrew installation, evince cannot open PDF files.

Installing `shared-mime-info` solves this problem. Hence, evice should depend on this.

**Comment by SMillerDev** [comment]
Hey, please fill out the entire issue template when reporting issues. It really helps a lot in solving the problem you might have (even if you don't see the need for it). In your case it might even be better to forego the issue completely and just make a pull request.

Either way closing this (until we have more information).

**Comment by kno10** [comment]
I think the explanation is pretty clear, a missing dependency.
As I have no idea how homebrew works (I just tried it, but I will not be a long-term mac user, so I do not intend to learn the inner workings), don't expect a pull request from me.
This issue report is all that I'll do: report a problem, and how to fix it.
For _me_ this settles it (it works now for me now). If you want to _also_ solve it for _other_ users, maybe just add the dependency. (for an earlier incomplete attempt to fix this, see Homebrew/legacy-homebrew/issues/45168)
