### ISSUE TITLE
wget 1.20.1 MacOS 10.14.2 dyld library error

### ISSUE THREAD

**Issue by tatoalo** [Homebrew/homebrew-core#35802]
- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was updating wget to the latest version (1.20.1), installation went fine but I can't launch wget anymore. Same thing would happen after a remove, cleanup and reinstalling process.
- What happened (include command output)
When attempting to launch wget:
`dyld: Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
[1]    76327 abort      wget`
- What you expected to happen
Launch as usual.
- Step-by-step reproduction instructions (by running `brew install` commands)
brew update && brew upgrade, or brew install wget if on a system without it.

On my system there's no pcre so I guess that's the problem, I've got pcre2 with a bunch of different versions of libpcre2-xx.x.dylib.
Wget is clearly trying to take something from a location that doens't exist, I don't think to understand, though, why the latest version would try to go back to an old version of pcre.
[doctor.log](https://github.com/Homebrew/homebrew-core/files/2737143/doctor.log)
[config.log](https://github.com/Homebrew/homebrew-core/files/2737144/config.log)

**Comment by fxcoudert** [comment]
Opportunistic linkage when we rebuilt the bottle recently for `libidn2`. Sorry about that. #35805 should fix it.

**Comment by fxcoudert** [comment]
In the meantime, `brew reinstall -s wget` will get it working for you.

**Comment by tatoalo** [comment]
Thank you very much, building directly from source indeed fixed it 😃 .
