### ISSUE TITLE
Feature request: build/provide sox with sndfile support

### ISSUE THREAD

**Issue by Rodeo314** [Homebrew/homebrew-core#35810]
#35684 removed the option to custom-build sox with sndfile

sox requires sndfile for input/output of Core Audio Format (CAF) files. Said container format is useful to handle processing of large files (formats such as WAV and AIFF are limited to 4 GB, which is only 77 minutes of 24-bit 6-channel uncompressed audio) and seems widely supported by at least Apple's own software.

**Comment by fxcoudert** [comment]
Fixed.
