### ISSUE TITLE
My macOS can't install nginx-full --with-rtmp-module with brew!

### ISSUE THREAD

**Issue by carmyang** [Homebrew/homebrew-core#35818]
Last login: Wed Jan  9 09:07:32 on console
localhost:~ CarmYang$ nginx
nginx: [emerg] unknown directive "rtmp" in /usr/local/etc/nginx/nginx.conf:118
localhost:~ CarmYang$ brew uninstall nginx
Uninstalling /usr/local/Cellar/nginx/1.15.8... (23 files, 1.5MB)
localhost:~ CarmYang$ brew tap denji/homebrew-nginx
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
hcloud              mariadb             serverless          wget

localhost:~ CarmYang$ brew tap denji/homebrew-nginx
localhost:~ CarmYang$ brew install nginx-full --with-rtmp-module
==> Installing dependencies for nginx-full: rtmp-nginx-module
Error: rtmp-nginx-module is already installed from !
Please `brew uninstall rtmp-nginx-module` first."
localhost:~ CarmYang$ 
localhost:~ CarmYang$ brew uninstall rtmp-nginx-module
Error: No such keg: /usr/local/Cellar/rtmp-nginx-module
localhost:~ CarmYang$ 
localhost:~ CarmYang$ 

How can I do for this?

**Comment by fxcoudert** [comment]
Please report this issue to the tap from which you are installing it: https://github.com/denji/homebrew-nginx/issues/new
