### ISSUE TITLE
Possible issue with mono formula

### ISSUE THREAD

**Issue by grahamj1978** [Homebrew/homebrew-core#35848]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ X] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

There seems to be some kind of issue with the most recent 1 or 2 versions of the mono formula for brew. I use it with ckan, and when trying to start it gives a mono related error. An error that does not occur according to the discussion here (https://github.com/KSP-CKAN/CKAN/issues/2630 1) when installing mono directly without brew. Any idea how to fix this, since I’d prefer to use brew rather than dealing with miscellaneous package (.pkg) installers?

**Comment by MikeMcQuaid** [comment]
Please provide more information on what the issue is and how to reproduce ti.

**Comment by MikeMcQuaid** [comment]
Cool, thanks. 



> Also, it was recently suggested in CKAN issue #2630 that a missing libmono-system-native library might be the cause of the issue.

It could be. Could you see if that's installed by the `mono` formula and, if not, consider submitting a pull request to add it? Thanks!

**Comment by HebaruSan** [comment]
Debian had the same problem (I assume there was some unexpected change upstream affecting everyone?), and they fixed it by adding `/usr/lib/libmono-system-native.so*` to their `mono-runtime-common` package.

https://salsa.debian.org/dotnet-team/mono/commit/fcb8084be66074f5315728c2783348fb4c1bb0aa

What would that look like for Homebrew? All I see in mono.rb is configure/make/make install.

**Comment by HebaruSan** [comment]
It's still a problem. What kind of activity is needed?

**Comment by tjnycum** [comment]
Confirming this is still a problem.

**Comment by MikeMcQuaid** [comment]
None of the maintainers are working on this so someone affected by the problem will need to step up and submit a pull request. Saying "this is a problem" does not help solve it.

**Comment by HebaruSan** [comment]
Is there a specific maintainer who is responsible for the mono package?

**Comment by SMillerDev** [comment]
Nope, all packages are the responsibility of the public. The maintainers are just here to guide it all.

**Comment by HebaruSan** [comment]
@tjnycum , what are some of the other packages that are affected?

**Comment by HebaruSan** [comment]
Recent activity

**Comment by SMillerDev** [comment]
There isn't.
