### ISSUE TITLE
openCV version 3 formula does not exist

### ISSUE THREAD

**Issue by alyssaq** [Homebrew/homebrew-core#35869]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Performed a regular update of Homebrew and opencv3 was replaced with opencv4.0.1.
Theres no opencv@3 formula.

- What happened (include command output)
```
brew search opencv
==> Formulae
opencv ✔           opencv@2
```
where opencv is 4.0.1

- What you expected to happen
`brew search opencv` should have opencv (latest), opencv@3 and opencv@2

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install opencv` replaces version 3 with 4 and no formula to downgrade.

**Comment by ShuchangXu** [comment]
currently following commands can install opencv 3.4.5
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/aaf45348653fc45674b7d798404f2cc9700e6f9c/Formula/opencv.rb`

**Comment by fxcoudert** [comment]
See https://github.com/Homebrew/homebrew-core/pull/35761
