### ISSUE TITLE
Knot Resolver 3.2.1 cannot start

### ISSUE THREAD

**Issue by camachat** [Homebrew/homebrew-core#35915]
Got this error:
`> cat /usr/local/var/log/kresd.log 
[system] error: standard input is not a terminal or pipe; use '-f 1' if you want non-interactive mode.  Commands can be simply added to your configuration file or sent over the tty/$PID control socket.`
I think '-f 1' is needed to be added into "ProgramArguments".

**Comment by camachat** [comment]
This can fix the issue.
`diff --git a/Formula/knot-resolver.rb b/Formula/knot-resolver.rb
index 06ea555398..f2d98ced31 100644
--- a/Formula/knot-resolver.rb
+++ b/Formula/knot-resolver.rb
@@ -67,6 +67,8 @@ class KnotResolver < Formula
         <string>#{sbin}/kresd</string>
         <string>-c</string>
         <string>#{etc}/kresd/config</string>
+        <string>-f</string>
+        <string>1</string>
       </array>
       <key>StandardInPath</key>
       <string>/dev/null</string>
`

**Comment by fxcoudert** [comment]
Can you please open a pull request?

**Comment by crystalneth** [comment]
Had same issue - found same resolution. Must add `-f 1` to executable options.

**Comment by camachat** [comment]
Pull request has been created: https://github.com/Homebrew/homebrew-core/pull/36020

**Comment by fxcoudert** [comment]
Thanks!
