### ISSUE TITLE
procedure described in CONTRIBUTING.md modifies the master branch

### ISSUE THREAD

**Issue by DanGrayson** [Homebrew/homebrew-core#35920]
The procedure described in the file https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md has a drawback, in that after the user has added a commit to the master branch of homebrew-core, the command `git update` leaves that commit in place, and thus doesn't restore the state of brew to what comes solely from upstream.  If the resulting pull request is rejected, or if the user's efforts have introduced bugs, then the naive user will find it hard to restore the state of their system to something clean.  Normally a user would want to add the commit to a branch other than `master`, so they can return to the master branch later and have a clean system.

**Comment by DanGrayson** [comment]
I've just looked at https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request and it seems to be a good git tutorial.  If `CONTRIBUTING.md` would mention it before suggesting editing, testing, and committing, it would help.

Also, in light of the message that one gets when submitting a pull request about being banned from ever submitting a pul request again if you do things the wrong way, it might be good to have a remark toward the start saying that git experts can do what they usually do with regard to the repository on their machine and with regard to submitting the pull request.

Another idea to consider would be to improve `brew doctor` so it would report the existence of local modifications and suggest ways to remove or evade them, if desired.

Here's another remark: the item
```
* leave the `bottle` as-is
```
is not understandable.  One problem is the hyphen, which makes one suggest that `as-is` is an identifier to be found in the code.  Another problem is that we know we don't have access to any bottles, as they are built for us on a remote server.  Perhaps the remark is really aimed at the user who is worried about how the hashcodes in the `bottle do ... end` section of the formula will get updated.  I could suggest a clearer way to say that, if that's what the original concern is.

**Comment by MikeMcQuaid** [comment]
@DanGrayson Could you send a pull request with suggested changes to that file? It's easier to discuss code than discussions about code. Thanks!
