### ISSUE TITLE
Issue building new formula on High Sierra

### ISSUE THREAD

**Issue by zawapete** [Homebrew/homebrew-core#35935]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`
```
HOMEBREW_VERSION: 1.9.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 241ee989bb6a917cb6000a1aa06aa341c465a1b3
Last commit: 2 days ago
Core tap ORIGIN: git@zawapete.github.com:Homebrew/homebrew-core.git
Core tap HEAD: f6214d386f4b1283e70298acadcfe4f1fffaad1c
Core tap last commit: 4 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/zawapete/Library/Logs/Homebrew
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1, 1.8.0_144
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

`brew doctor`
```
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Adding back rakshasa's libtorrent/rtorrent formulas

- What happened (include command output)
Build by homebrew fails on High Sierra due to erroneous math.h include

- What you expected to happen
Build to succeed, like when building directly from sources

- Step-by-step reproduction instructions (by running `brew install` commands)
cd $(brew --repo homebrew/core)
git remote add libtorrent https://github.com/zawapete/homebrew-core
git pull zawapete libtorrent-rtorrent
git checkout libtorrent-rtorrent
brew install --build-from-source libtorrent-rakshasa

I tried some weeks ago to add the formulas and have the same issue on both High Sierra and Mojave: narrowed down to https://github.com/Homebrew/homebrew-science/issues/6394#issuecomment-337586186, it still fails on High Sierra as you can see on CI: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/36054/version=high_sierra/testReport/junit/brew-test-bot/high_sierra/install_libtorrent_rakshasa/

Cannot reproduce the issue when building directly from sources

**Comment by fxcoudert** [comment]
This discussion can take place in your PR: https://github.com/Homebrew/homebrew-core/pull/35797

**Comment by zawapete** [comment]
@fxcoudert sadly, the discussione is not taking place in the PR
