### ISSUE TITLE
diffuse:  pygtk import failure despite homebrew showing it being installed

### ISSUE THREAD

**Issue by deftdawg** [Homebrew/homebrew-core#35944]
1. brew install diffuse
2. pygtk is installed as a dependency
3. run diffuse

Here is the output:
```
$ diffuse
Traceback (most recent call last):
  File "/usr/local/bin/diffuse", line 124, in <module>
    import pygtk
ImportError: No module named pygtk

$ brew search pygtk
==> Formulae
pygtk ✔
```

**Comment by jumpkick** [comment]
```
$ /usr/bin/python --version # python magic line from /usr/local/bin/diffuse  
Python 2.7.10

/usr/local/bin/python --version # python installed by homebrew
Python 2.7.15

$ /usr/local/bin/python  /usr/local/bin/diffuse  # this works
```

Edit the magic line or apply the following diff:
```
--- /usr/local/bin/diffuse  2019-01-12 16:30:40.000000000 -0500
+++ /usr/local/bin/diffuse      2019-01-12 16:30:48.000000000 -0500
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/local/bin/python
 # -*- coding: utf-8 -*-

 # Copyright (C) 2006-2014 Derrick Moser <derrick_moser@yahoo.com>
```

And it will work

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/diffuse.rb seems to rewrite the python requirement to the system python. Is the pygtk package required?

**Comment by deftdawg** [comment]
@SMillerDev that doesn't really make sense...  There's a depends on pygtk, which I would assume to mean it depends on homebrew installing pygtk to its copy of python...  Then the formula goes and changes the the magic line to the system's interpreter which does have pygtk installed.
