### ISSUE TITLE
Cryfs bottle built against wrong cryptopp version

### ISSUE THREAD

**Issue by smessmer** [Homebrew/homebrew-core#35947]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Gist-logs: https://gist.github.com/8fc40b776774c51fa3f549eda4a6fb61

Installing cryfs

    brew install cryfs

installs cryfs from a bottle that was built against cryptopp 7.0.0, but homebrew installs cryptopp 8.0.0 as a dependency. This causes a segfault when running cryfs. When installing cryfs from source

    brew install -s cryfs

everything works fine.

More info here: https://github.com/cryfs/cryfs/issues/242

The bottles should be rebuilt with the new cryptopp version.

Additionally, I'm not sure if this is enough to fix this. Will this somehow cause issues for existing users? What if somebody updates their cryptopp locally while not changing cryfs? Will this break in a similar fashion?

**Comment by SMillerDev** [comment]
Could you make a pull request that changes the cryfs formula to include a test that fails if the crytopp link is too old? That way we won't update crytopp without rebuilding cryfs.
And in addition to that you could add a `revision 1` block underneath the `url` block to rebuild it for everyone.

**Comment by smessmer** [comment]
Adding a test case is unfortunately not possible since it is a fuse file system and mounting that from a homebrew unit test fails with

    fuse: failed to exec mount program: Operation not permitted

If you know how to make this work, please let me know. I'd love to have a test case in the formula.

I'll add the revision parameter, thanks :)
https://github.com/Homebrew/homebrew-core/pull/35958

**Comment by SMillerDev** [comment]
Does it fail differently if the vrong version is loaded?

**Comment by MikeMcQuaid** [comment]
Is there a way to e.g. verify the linkage? Otherwise this will happen again the next time `cryptopp ` is upgraded.

**Comment by smessmer** [comment]
I'm not very familiar with osx, not sure if there's tools to check executables for that. Aren't there mechanisms to ensure ABI compatibility? I know that on Linux there's the .so version numbers for this.

I could probably write a test case that asserts that running cryfs fails in a certain way (i.e. fails with missing permissions) and therefore does not fail in another way (i.e. failing because of ABI) but that sounds very fragile to me too. Say suddenly the permission is not missing, then the test case would fail in a false positive.

Also note that the next cryfs release (due in a few weeks) will have the cryptopp library statically linked, so it won't be an issue anymore.

**Comment by MikeMcQuaid** [comment]
> I'm not very familiar with osx, not sure if there's tools to check executables for that. Aren't there mechanisms to ensure ABI compatibility? I know that on Linux there's the .so version numbers for this.

We do check this stuff and the current checks do not seem to be sufficient, that's the point unfortunately.

> I could probably write a test case that asserts that running cryfs fails in a certain way (i.e. fails with missing permissions) and therefore does not fail in another way (i.e. failing because of ABI) but that sounds very fragile to me too. Say suddenly the permission is not missing, then the test case would fail in a false positive.

That would be ideal. Could you add that to your PR?

> Also note that the next major cryfs release (v0.10 due in a few weeks) will have the cryptopp library statically linked, so it won't be an issue anymore.

We may still end up configuring it to link dynamically but yes that seems positive.

**Comment by smessmer** [comment]
ok I added it

**Comment by smessmer** [comment]
This is fixed
