### ISSUE TITLE
Ruby 2.6.0_1 failing without gmp

### ISSUE THREAD

**Issue by elindsey** [Homebrew/homebrew-core#35956]
I ran a brew update && brew upgrade to pull in the latest ruby (2.6.0_1).

The post install step failed with:

`dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/Cellar/ruby/2.6.0_1/bin/ruby
  Reason: image not found`

Manually installing gmp via brew install gmp fixed the issue. Is there an unmodeled dependency in the latest ruby formula?

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

$ brew config
HOMEBREW_VERSION: 1.9.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 241ee989bb6a917cb6000a1aa06aa341c465a1b3
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e27422dcd5a3b9056ac533818b7e4b18ffe60252
Core tap last commit: 25 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/eli/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.2-x86_64
CLT: N/A
Xcode: 10.1

$ brew doctor
Your system is ready to brew.

**Comment by fxcoudert** [comment]
I think it got linked in while we were rebuilding bottles following the big `readline` update.

Rebuilding bottles at https://jenkins.brew.sh/job/Homebrew%20Testing/1141/
Meanwhile, you can `brew reinstall -s ruby` to fix the issue

**Comment by fxcoudert** [comment]
Fixed in 66abe7790933b3321dc9f3d212031c6219d9c5e7, you can `brew reinstall` to get the correct bottles. Sorry about that.

**Comment by swrobel** [comment]
The same problem exists with `Ruby@2.3`. Are those bottles going to be rebuilt?
