### ISSUE TITLE
llvm fails to build without full Xcode

### ISSUE THREAD

**Issue by fcelda** [Homebrew/homebrew-core#35954]
llvm fails to build from source without full Xcode. This was introduced with #34419 (commit 38c4a8e43d2) where toolchain build was forced and `--with-toolchain` option removed.

I have to build LLVM from source because I need new _lldb_ which is optional (`--with-lldb`) in the formula however I do not want to install full Xcode.

Build output snippet:
```
==> cmake -G Unix Makefiles .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Ce
Last 15 lines from /Users/jvcelak/Library/Logs/Homebrew/llvm/02.cmake:
  command.


CMake Warning at tools/xcode-toolchain/CMakeLists.txt:60 (message):
  Failed to detect the version of an installed copy of Xcode, falling back to
  highest supported version.  Set XCODE_VERSION to override.


CMake Error at tools/xcode-toolchain/CMakeLists.txt:80 (message):
  Could not identify toolchain dir


-- Configuring incomplete, errors occurred!
```

This is what fails in llvm's cmake:
```
$ xcodebuild -version
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

I will be happy to open a PR with the fix but would like to consult the solution first. Here are some options:

1. Add option `--without-toolchain` to allow disabling of Xcode toolchain build. Users will have the toolchain in bottles but there will be a way to rebuild llvm without full Xcode.
2. Always build _lldb_ and remove `--with-lldb` option. This is not general solution but eliminates my need of building LLVM from source. Problem is that _lldb_ needs to be code-signed to work properly. Users would have to sign lldb after installation manually.
3. Revert #34419 entirely: No toolchain in bottle and `--with-toolchain` option.

Other suggestions are welcome as well. What do you prefer?

---

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Comment by MikeMcQuaid** [comment]
We are in the process of removing all options (https://github.com/Homebrew/homebrew-core/issues/31510) so do not wish to re-add any. LLDB cannot be enabled automatically because it requires code signing which is not setup on our CI boxes.

I'd suggest that we either add `depends_on :xcode => :build` or remove the toolchain option. I would prefer the prior.

**Comment by fcelda** [comment]
Neither of the options you suggest make me happy. Does it mean the option to build LLDB will be eventually removed as well?

I understand the motivation to change the defaults or remove options that are not used but this particular case justifies existence of the option. I think removing all options blindly is in conflict with the goal of improving the user experience. LLVMs is not the first formula that "broke" for me due to this cleanup.

**Comment by fcelda** [comment]
Sorry @MikeMcQuaid, I didn't say this was anyones mistake. I appreciate the time you invest into Homebrew. It just doesn't prevent me being unhappy about the option removal effort as it breaks my own use case.

Speaking of LLDB, does it also mean that any binaries which require code signing won't be packaged in the future? Does it make sense to open an issue to discuss options or is it a no-go? One solution I have in my mind is to install the unsigned binaries (could be from bottles) into some non-default path and providing documentation to the users how to sign the code manually.

Thanks.

**Comment by MikeMcQuaid** [comment]
> Sorry @MikeMcQuaid, I didn't say this was anyones mistake. I appreciate the time you invest into Homebrew.

That's OK @fcelda and thanks for the kind words ❤️.



> Speaking of LLDB, does it also mean that any binaries which require code signing won't be packaged in the future?

They won't be packaged if code signing is required for the build to succeed.

> One solution I have in my mind is to install the unsigned binaries (could be from bottles) into some non-default path and providing documentation to the users how to sign the code manually.

Yes, I agree, if they can be done after the fact that's fine with me. We could even provide a helper application like [`brew postgresql-upgrade-database`](https://github.com/Homebrew/homebrew-core/blob/master/cmd/brew-postgresql-upgrade-database.rb) that would do it for users.

Can `lldb` be done after the fact? If so I'll adjust the `llvm` formula to build it and then we can figure out signing at a later point. How's that sound?

**Comment by fcelda** [comment]
> Yes, I agree, if they can be done after the fact that's fine with me.

Thanks great news. Thanks.

> Can lldb be done after the fact? If so I'll adjust the llvm formula to build it and then we can figure out signing at a later point. How's that sound?

I do not know the answer. Let me try that and I will let you know.

**Comment by fcelda** [comment]
@MikeMcQuaid It looks like LLDB cannot be compiled without code-signing. It's required for the included tests. I made it work locally on my machine but it required patching.

It probably doesn't make sense to include LLDB in the LLVM formula. I also found out LLDB can be compiled out-of-tree with the latest LLVM bottle so that will probably be preferred for everyone.

**Comment by MikeMcQuaid** [comment]
> It probably doesn't make sense to include LLDB in the LLVM formula. I also found out LLDB can be compiled out-of-tree with the latest LLVM bottle so that will probably be preferred for everyone.

@fcelda Yeh, this sounds ideal. Thanks for checking in and reporting back ❤️
