### ISSUE TITLE
mongodb does not show version

### ISSUE THREAD

**Issue by richardsimko** [Homebrew/homebrew-core#35996]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

When installing mongodb using homebrew the mongo tools don't display their version correctly:

```
$ mongodump --version
mongodump version:
git version:
Go version: go1.11.4
os: darwin
arch: amd64
compiler: gc
```

```
$ mongorestore --version
mongorestore version:
git version:
Go version: go1.11.4
os: darwin
arch: amd64
compiler: gc
```

```
$ mongo --version
MongoDB shell version v4.0.5
git version: 3739429dd92b92d1b0ab120911a23d50bf03c412
allocator: system
modules: none
build environment:
distarch: x86_64
target_arch: x86_64
```

This issue does not exist with the official release of the tools (See https://jira.mongodb.org/browse/TOOLS-2193?focusedCommentId=2113950&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2113950)

Brew config and doctor output: https://gist.github.com/richardsimko/77eee82dd50452ef50298e5a4e638a90

**Comment by xdg** [comment]
I suspect the build script needs to be setting the ldflags using the `print_ldflags` shell helper, which sets the version based on git tags.  See how the tools repo [build.sh](https://github.com/mongodb/mongo-tools/blob/master/build.sh#L24) script does it.

**Comment by richardsimko** [comment]
This is still an issue
