### ISSUE TITLE
install problem image not found

### ISSUE THREAD

**Issue by pdavis39** [Homebrew/homebrew-core#36005]
sandbox:couchdb $ couchdb
Apache CouchDB 1.7.1 (LogLevel=info) is starting.
{"init terminating in do_boot",{{badmatch,{error,{bad_return,{{couch_app,start,[normal,["/usr/local/etc/couchdb/default.ini","/usr/local/etc/couchdb/local.ini"]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,couch_primary_services,{shutdown,{failed_to_start_child,collation_driver,"dlopen(/usr/local/Cellar/couchdb/1.6.1_9/lib/couchdb/erlang/lib/couch-1.6.1/priv/lib/couch_icu_driver.so, 2): image not found"}}}}}},[{couch_server_sup,start_server,1,[{file,"couch_server_sup.erl"},{line,98}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}]}}}}}},[{couch,start,0,[{file,"couch.erl"},{line,18}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

I did a medium json file install and it appeared to hang.  after a while I uninstalled and reinstalled couchdb and now get the error above

Thanks in advance for your assistance,

Paul

**Comment by fxcoudert** [comment]
Please fill the full issue template, please.
