### ISSUE TITLE
Request ruby not being keg_only

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/homebrew-core#36030]
I think that `ruby` formula should not be `keg_only` for the following reasons:

* This behaviour is not consistent with other similar formulae such as `python@2`, `python`, `perl`, `php`. Unlike other binaries (e.g. curl) offered by macOS, brew ruby is not a simple replacement to the system ruby. 
  * Installing gem in system ruby requires sudo, which is not idiomatic way in brew.
  * System ruby has already reached **EOL** (Ref: https://www.ruby-lang.org/en/downloads/). I don't think it is a good idea to encourage users to use system ruby.
  * If users run `brew install ruby`, the behaviour of `keg_only` would be surprise. And they have to take many extra steps to use brew ruby properly.
  * Other softwares (including softwares outside brew) which use ruby and gem will only lookup them in the default path instead of unusual paths like `/usr/local/opt/ruby/bin` and `/usr/local/lib/ruby/gems/2.6.0/bin`.
* Since brew 1.9, force linking ruby is impossible.
* The ruby gems currently are installed in a **versioned** path `/usr/local/lib/ruby/gems/2.6.0/bin` instead of `/usr/local/bin/`. This means the users need to update this path in all sort of places whenever there is a major update in ruby, which could be cumbersome.

**Comment by fxcoudert** [comment]
poke @MikeMcQuaid @mistydemeo

**Comment by MikeMcQuaid** [comment]
> * Installing gem in system ruby requires sudo, which is not idiomatic way in brew.

This is not correct. `gem install --user`.

> * System ruby has already reached **EOL** (Ref: https://www.ruby-lang.org/en/downloads/). I don't think it is a good idea to encourage users to use system ruby.

This is not correct: `In security maintenance phase (will EOL soon!)`. Apple provide security updates for the system Ruby when warranted.

> * If users run `brew install ruby`, the behaviour of `keg_only` would be surprise. And they have to take many extra steps to use brew ruby properly.

This applies to everything that's `keg_only`. It's also easier to keep the Ruby versions in sync when they are keg-only. Additionally, there are non-trivial issues when an invalid `ruby` is in the `PATH` with e.g. using gems as part of `brew tests` that were resolved by making this `keg_only`.

> * Other softwares (including softwares outside brew) which use ruby and gem will only lookup them in the default path instead of unusual paths like `/usr/local/opt/ruby/bin` and `/usr/local/lib/ruby/gems/2.6.0/bin`.

This also applies to the path used by `rbenv` rubies which does not seem to be a problem there.

> * Since brew 1.9, force linking ruby is impossible.

This is why instructions are provided to avoid the need for a force link.

> * The ruby gems currently are installed in a **versioned** path `/usr/local/lib/ruby/gems/2.6.0/bin` instead of `/usr/local/bin/`. This means the users need to update this path in all sort of places whenever there is a major update in ruby, which could be cumbersome.

This applies to various keg-only software too. Additionally, this applies to `gem install --user` which is a part of Ruby.

As a result I think it's worth this remaining as-is, sorry.
