### ISSUE TITLE
libtiff: TIFF_UINT64_T conflicts with uint64 defined in macOS SDK cssmconfig.h

### ISSUE THREAD

**Issue by miniupnp** [Homebrew/homebrew-core#36035]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

It is not possible to include both tiff.h and ApplicationService.h in the same .c source : 
```
#import <ApplicationServices/ApplicationServices.h>
#include <tiffio.h>
```

The error is : 
```
$ make
cc -Wall   -c -o tifftest.o tifftest.c
In file included from tifftest.c:3:
In file included from /usr/local/include/tiffio.h:31:
/usr/local/include/tiff.h:76:23: error: typedef redefinition with different
      types ('unsigned long' vs 'uint64_t' (aka 'unsigned long long'))
typedef TIFF_UINT64_T uint64;
                      ^
/System/Library/Frameworks/Security.framework/Headers/cssmconfig.h:51:18: note: 
      previous definition is here
typedef uint64_t uint64;
                 ^
1 error generated.
make: *** [tifftest.o] Error 1

```

I believe TIFF_UINT64_T should be defined as unsigned long long and not unsigned long, even if both are 64bits.
see https://github.com/macports/macports-ports/blob/master/graphics/tiff/files/patch-configure.ac.diff

**Comment by fxcoudert** [comment]
Please report this bug to libtiff.

**Comment by miniupnp** [comment]
Le 15/01/2019 à 12:50, FX Coudert a écrit :
>
> Please report this bug to libtiff.
>
It has been done for a long time now :(

http://bugzilla.maptools.org/show_bug.cgi?id=2464
