### ISSUE TITLE
brew install nginx error 

### ISSUE THREAD

**Issue by huangminlinux** [Homebrew/homebrew-core#3604]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

Last 15 lines from /Users/HuminiOS/Library/Logs/Homebrew/pcre/01.configure:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/pcre-20160804-14142-1o95og5/pcre-8.39':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
zenity [and others] failed to build on 10.11 - pcre error https://github.com/Homebrew/homebrew-core/issues/3316
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Whether the new system does not work

**Comment by MikeMcQuaid** [comment]
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.
> Please create pull-requests instead of filing issues.

Note this text.

**Comment by DomT4** [comment]
> brew gist-logs <formula>
(where <formula> is the name of the formula that failed to build).

This text, as well. Particularly interested in your `brew doctor` &  `brew config`. The error here makes it seem likely that you're possibly still using Xcode 7.x/CLT 7.x?

**Comment by Whirlwind** [comment]
I have same problem. And I fixed it by select Xcode 8 Command Line Tool in the Xcode 8.(current Xcode 7.3)

**Comment by MikeMcQuaid** [comment]
> I have same problem. And I fixed it by select Xcode 8 Command Line Tool in the Xcode 8.(current Xcode 7.3)

Assuming that's the fix,
