### ISSUE TITLE
Bat formula ships outdated fish completions

### ISSUE THREAD

**Issue by ohcibi** [Homebrew/homebrew-core#36116]
See https://github.com/sharkdp/bat/issues/372

Bat has removed its fish completions but this formula does install broken ones.

**Comment by ohcibi** [comment]
@fxcoudert This has already been decided upstream. See the linked issues. The one piece thats missing is this formula. The files are generated but they are not intended to be shipped automatically.

I would make sourcing those files optional for users of this formula. If I just remove the `install........fish` line, all generated files that are not "installed" will be removed on the next `brew cleanup` is that correct?

**Comment by fxcoudert** [comment]
I have read the upstream issue, and the relevant commit https://github.com/sharkdp/bat/pull/391 which only affects CI. This is, according to upstream, “temporary”. So clarification on the status would be welcome.

As I said, a pull request not to install the completion files is welcome.
