### ISSUE TITLE
Postgresql 11.1 symbol not found

### ISSUE THREAD

**Issue by fantasticfears** [Homebrew/homebrew-core#36129]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/33d596c248cf9baae22b4f9790ce58c9

To help us debug your issue please explain:
- What you were trying to do (and why)
I tried to install pg11.1. And I use pg_cli to test it. It didn't work so I used pg_ctl to start pg. It didn't work so I know it's upstream problem. 
- What happened (include command output)
The upgrade from pg10 failed. So I deleted the data. New db folder is populated by brew.
```
> pg_ctl -D /usr/local/var/postgres start
waiting for server to start....2019-01-17 22:53:36.328 CET [61762] FATAL:  could not load library "/usr/local/lib/postgresql/cstore_fdw.so": dlopen(/usr/local/lib/postgresql/cstore_fdw.so, 10): Symbol not found: _AllocSetContextCreate
          Referenced from: /usr/local/lib/postgresql/cstore_fdw.so
          Expected in: /usr/local/Cellar/postgresql/11.1_1/bin/postgres
         in /usr/local/lib/postgresql/cstore_fdw.so
2019-01-17 22:53:36.328 CET [61762] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
```
- What you expected to happen
pg_ctl starts the PG.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
> brew install postgresql (or reinstall)
> pg_ctl -D /usr/local/var/postgres start
```

**Comment by SMillerDev** [comment]
Can you check if the file exists? (`/usr/local/lib/postgresql/cstore_fdw.so`)

**Comment by fantasticfears** [comment]
`SHA256(/usr/local/lib/postgresql/cstore_fdw.so)= f0b85a0b0c598fd20cbfcd4c511ef3e14b165d90d3119ca41f77eb194c5438b4`. A 66kb file

**Comment by MikeMcQuaid** [comment]
Please try to remove those libraries from `brew doctor` and `brew reinstall postgres`.

**Comment by fantasticfears** [comment]
I think a bottle doesn't affect by dylibs. Alright, I did a reinstall after sorting out all doctor warnings. It's the same. `cstore_fdw.so` has the same sha256.

**Comment by MikeMcQuaid** [comment]
> * It didn't work so I know it's upstream problem.

You mean Homebrew or the PostgreSQL project?

No idea what's going on here, sorry. Can you try to completely delete all `postgres` files and try again? Seems to be something specific to your system.

**Comment by fantasticfears** [comment]
I did a reinstall of the plugin. It's fixed now. Thanks for the help.
