### ISSUE TITLE
macOS 10.12 Sierra CMake Compatibility

### ISSUE THREAD

**Issue by kushalj1997** [Homebrew/homebrew-core#3612]
Hi,

Trying to install clang-format, and cmake doesn't install. Same thing happens when I try to install on it's own. Is CMake not supported on OS X 10.12 yet?

https://gist.github.com/75f558682fae385258d99badbd8c9b7d

==> Installing dependencies for clang-format: cmake,
==> Installing clang-format dependency: cmake
==> Downloading https://cmake.org/files/v3.6/cmake-3.6.1.ta
Already downloaded: /Users/jollygama/Library/Caches/Homebrew/cmake-3.6.1.tar.gz
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.6.1 --no
Last 15 lines from /Users/jollygama/Library/Logs/Homebrew/cmake/01.bootstrap:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk

  Please set CMAKE_OSX_DEPLOYMENT_TARGET to 10.11 or lower.
Call Stack (most recent call first):
  Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:19 (project)

-- Configuring incomplete, errors occurred!
See also "/tmp/cmake-20160804-8544-1gxqkoa/cmake-3.6.1/CMakeFiles/CMakeOutput.log".
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by kushalj1997** [comment]
Yes I have. I ran brew update, doctor, and upgrade several times and upgrade fails everytime it gets to cmake and python3 on OSX 10.12. Bootstrap error. All permissions are set. This is not a duplicate issue.

**Comment by MikeMcQuaid** [comment]
From your `brew doctor` output.
> Warning: Your Xcode (7.3.1) is outdated
> Please update to Xcode 8.0.
>Xcode can be updated from
>   https://developer.apple.com/xcode/downloads/

**Comment by floatingatoll** [comment]
```
Last 15 lines from /Users/coral/Library/Logs/Homebrew/cmake/01.bootstrap:
  file STRINGS file
  "/Library/Frameworks/Gtk.framework/Headers/gtk/gtk/gtkversion.h" cannot be
  read.
```

After 10.11->10.12 upgrade, this file appears to have moved:

```
ls: /Library/Frameworks/Gtk.framework/Headers/gtk/gtk/gtkversion.h: No such file or directory
-rw-rw-r--  1 root  admin  1898 Sep 25  2009 /Library/Frameworks/Gtk.framework/Headers/gtk/gtkversion.h
```

**Comment by DomT4** [comment]
@floatingatoll That's unrelated. You'll need to move that out of the way at least temporarily, see https://github.com/Homebrew/legacy-homebrew/issues/39732. CMake is difficult to control, it more or less roams wherever it wants to to find dependencies. This can be problematic, as it is in this case.

**Comment by antbryan** [comment]
> From your brew doctor output:

>>Warning: Your Xcode (7.3.1) is outdated
Please update to Xcode 8.0.
Xcode can be updated from
https://developer.apple.com/xcode/downloads/

FYI, I have Xcode 8.0 beta 4 installed on 10.12 PB3 & also see this (don't know if it will say that until 8.0 final). 

Also have this issue.

**Comment by DomT4** [comment]
> FYI, I have Xcode 8.0 beta 4 installed on 10.12 PB3 & also see this (don't know if it will say that until 8.0 final).

What is your `brew config` and `xcode-select -p`?

**Comment by antbryan** [comment]
brew config:

> HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b33b1af073979c8a699ed9688dba37fb7e74f0b5
Last commit: 7 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3b372a55d0b814de9fe2f25c21c98192b35f49c4
Core tap last commit: 4 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.12-x86_64
Xcode: 7.3.1
CLT: 8.0.0.0.1.1469826870
X11: N/A

xcode-select -p:

> /Applications/Xcode.app/Contents/Developer

**Comment by DomT4** [comment]
That looks like your `xcode-select -p` is still pointing at the stable Xcode rather than the beta one, which is named slightly differently. That'll be why you're seeing the `doctor` warning.

**Comment by antbryan** [comment]
doh @DomT4 that was it, thanks! perhaps the text could be updated for clueless people like me?

cmake upgrades now. so @kushalj1997, you may want to try Xcode beta Preferences, Locations, & switch Command Line Tools to 8.0.

**Comment by kushalj1997** [comment]
Yup, updated to Xcode 8.0 and everything just worked flawlessly. New brew config:

HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: a9ab066654913a369cefccd13284d9d912dd5bb9
Last commit: 33 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3b372a55d0b814de9fe2f25c21c98192b35f49c4
Core tap last commit: 42 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.12-x86_64
Xcode: 8.0 => /Applications/Xcode-beta.app/Contents/Developer
CLT: 8.0.0.0.1.1469826870
X11: 2.7.9 => /opt/X11
