### ISSUE TITLE
[`doxygen.rb`] Post-Build CMake Failures With `--with-llvm` Option Enabled After Recent LLVM Upgrade

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#3614]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?  (N/A)

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

After having Homebrew update LLVM from v3.6.2 to v3.8.1&thinsp;—&thinsp;to clarify why I skipped v3.8.0, I was on vacation when `llvm.rb` was updated to propagate it to Homebrew end users&thinsp;—, I began to experience issues with Doxygen when I called it from within CMake as part of refreshing the Xcode project files I have it generate for my non-Homebrew (development) copy of LLVM's `master` branch.  I believe that this is because I installed Doxygen from source with the `--with-llvm` option enabled, and seeing if rebuilding it from source and reinstalling it would resolve my problem did indeed do so.  As such, I propose that we give `doxygen.rb` a `revision` bump if this is done when upgrading one of a formula's dependencies breaks one of its options.  If such a change is welcomed, then either I can apply it when I get around to doing so or somebody else can swoop in and take care of making it; please leave this issue open as a placeholder in the meantime.  If not, then I guess I'll just come back to find that this issue has been closed, then, won't I?

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by DomT4** [comment]
> As such, I propose that we give doxygen.rb a revision bump if this is done when upgrading one of a formula's dependencies breaks one of its options. If such a change is welcomed, then either I can apply it when I get around to doing so or somebody else can swoop in and take care of making it; please leave this issue open as a placeholder in the meantime.

Note that Homebrew has a policy of not `revision` bumping formulae with only optional links to the breaking change because `revision`s are a blunt instrument which forces everyone to reinstall regardless of whether they've used the option or not.

We sometimes make exceptions, usually based on analytics data showing option usage in that formula is unusually heavy, but that isn't the case for `doxygen` with just over 1.5% of all "known" installations using the LLVM option.

**Comment by RandomDSdevel** [comment]
@DomT4:  Right.  Sorry for making unnecessary noise here on GitHub!  (I _swear_ I may have recently seen a comment to similar effect somewhere here, too…)

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  
> To help us debug this issue can you explain:
> 
> - What you were trying to do (and why)
> - What happened
> - What you expected to happen
> - Step-by-step reproduction instructions (with as minimal input data as possible)

Unfortunately for this issue, I can't do that now:  doing a `brew reinstall -vd --build-from-source doxygen --with-graphviz --with-llvm --with-qt5` fixed my problem, so I can no longer reproduce it.  In any case, you guys decided to close this issue, so I think I can assume we're done here, anyway.

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel Yep, thanks for replying though!

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  Yeah, you're welcome!
