### ISSUE TITLE
find_package(TBB ) fails for home brew installation

### ISSUE THREAD

**Issue by hjmjohnson** [Homebrew/homebrew-core#36164]
https://github.com/Homebrew/homebrew-core/blob/c8c56a16a2c6b496bd8c088204516b11b5006960/Formula/tbb.rb#L39

The generation of the config file for TBB does not result in a valid packages.

test
```
# Put this cmake file in a directory, run "cmake ."  finding TBB results in a FATAL_ERROR from cmake 
cmake_minimum_required(VERSION 3.0)
find_package(TBB REQUIRED CONFIG)
if(NOT TBB_FOUND)
   message(FATAL_ERROR "NO TBB")
else()
  message(STATUS "FOUND TBB")
endif()
```

```
CMake Error at /usr/local/lib/cmake/TBB/TBBConfig.cmake:77 (message):
  Missed required Intel TBB component: tbb
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/johnsonhj/src/tester/CMakeFiles/CMakeOutput.log".
```

The issue is that the file `/usr/local/lib/cmake/TBB/TBBConfig.cmake` is not valid with respect to the installed components. 

- Relative path of 'get_filename_component(_tbb_root "${_tbb_root}" PATH)' is wrong
- Both debug and release are required 'if (EXISTS "${_tbb_release_lib}" AND EXISTS "${_tbb_debug_lib}")'

The package is built with make, but then the cmake module is configured and installed separately.

**Comment by SMillerDev** [comment]
If you know a fix could you file a pull request to change it. If you don't know a fix could you edit the post to include the information in the issue template? I'm going to close this until we have at least that information as it's required to debug this.

**Comment by hjmjohnson** [comment]
I'm tracking down the problem.   It is related to bugs (inconsistencies) in both TBB and homebrew.  The optimal solution is to fix both.

I think I know the fix for homebrew, but I need to test it.  (First I need to learn how to develop in homebrew).

Change:  `"-DSAVE_TO=lib/cmake/TBB", `   --> "-DSAVE_TO=cmake/TBB",
and
Change:  `(lib/"cmake"/"TBB").install Dir["lib/cmake/TBB/*.cmake"]` --> ` (l"cmake"/"TBB").install Dir["cmake/TBB/*.cmake"]`

The default TBB paths are the only ones that configure properly.   Alternatively, we could patch TBB to make it configure properly.

**Comment by hjmjohnson** [comment]
@SMillerDev   Thank you for your feedback.  I was able to fine tune and test the behavior more completely this morning.  

https://github.com/Homebrew/homebrew-core/pull/36175

upstream fixes:  https://github.com/01org/tbb/pull/119

**Comment by hjmjohnson** [comment]
Waiting for TBB to approve and update changes.

**Comment by fxcoudert** [comment]
Thanks @hjmjohnson for the detailed report, and for following up with upstream. We are now waiting on their fix, and will welcome a pull request once they have decided on a course of action.

**Comment by hjmjohnson** [comment]
@fxcoudert OK, but TBB is terribly broken in home-brew right now.  It would be better to NOT install the TBBConfig.cmake files.  (The pathing in these files is wrong, they point to the wrong directories for where the libraries exist.)

The presence of those files cause immediate unrecoverable "FATAL_ERRORS" when cmake finds them.  If they were not installed, at least other approaches could be used.

**Comment by fxcoudert** [comment]
@hjmjohnson we have several formulas inside Homebrew that are building and working fine, so it's not broken for all users. I would be happy to consider alternatives as pull requests, but the best solution is really for upstream to fix the issue.
