### ISSUE TITLE
gnuradio package no longer installs gnuradio-companion GUI tool

### ISSUE THREAD

**Issue by zhovner** [Homebrew/homebrew-core#36165]
- [x] are reporting a bug others will be able to reproduce 
- [x] have a problem with `brew install` 
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

## Bug report:
After installing `gnuradio`, the `gnuradio-companion` executable is no longer installed. Bottled version does not contain `gnuradio-companion`. 
This issue was happens before https://github.com/Homebrew/homebrew-core/issues/9317

## The reason:
Commit https://github.com/Homebrew/homebrew-core/commit/fff4ad2aede0dcdd5a3649ec123a5266589b4a0c caused the problem.
@fxcoudert can you please explain why this options removed?

### brew config
```
HOMEBREW_VERSION: 1.9.2-35-gcf32929
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf32929116b2d5193bad9d78cc627d097cf7612c
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c8c56a16a2c6b496bd8c088204516b11b5006960
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/a/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.2
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
The reasoning is discussed in https://github.com/Homebrew/homebrew-core/issues/31510
