### ISSUE TITLE
apache-spark java version

### ISSUE THREAD

**Issue by leomikezee** [Homebrew/homebrew-core#36259]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?

> yes

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

> yes

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

> Error: No logs.

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

> brew config:
> HOMEBREW_VERSION: 1.9.2
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
> Last commit: 8 days ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 6841a6ec4b9052dec1e466580e42b1f0bc5d2323
> Core tap last commit: 11 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_LOGS: /Users/liaomaizi/Library/Logs/Homebrew
> CPU: octa-core 64-bit haswell
> Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
> Clang: 10.0 build 1000
> Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Curl: 7.54.0 => /usr/bin/curl
> Java: 11.0.2
> macOS: 10.14.2-x86_64
> CLT: 10.1.0.0.1.1539992718
> Xcode: 10.1
> XQuartz: 2.7.11 => /opt/X11

> brew doctor:
> Your system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why)

> I was trying to install apache-spark

- What happened (include command output)

> I got error message that JavaRequirement unsatisfied!

- What you expected to happen

> I have installed the latest java. According to the homepage of Spark, Spark runs on Java 8+.

- Step-by-step reproduction instructions (by running `brew install` commands)

> brew install apache-spark

**Comment by leomikezee** [comment]
> Whats the full output of `brew install apache-spark`?

apache-spark: Java 1.8 is required to install this formula.
JavaRequirement unsatisfied!
You can install with Homebrew Cask:
 brew cask install homebrew/cask-versions/java8
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.

**Comment by leomikezee** [comment]
> Also, how did you install java?

brew cask install java

**Comment by MikeMcQuaid** [comment]
Sorry, I misread this earlier: apache-spark needs `brew cask install java8`. If it can be made to work with the latest Java we'll accept a PR to change the formula. Thanks!

**Comment by leomikezee** [comment]
@MikeMcQuaid I tried running examples from the Spark website with only the latest Java installed, it seems work fine.
