### ISSUE TITLE
cannot brew cleanup after updating python

### ISSUE THREAD

**Issue by geokal** [Homebrew/homebrew-core#36311]
After doing brew upgrade as usual. Python upgraded but doing brew cleanup says the following
`brew cleanup
Removing: /usr/local/Cellar/python/3.7.2... (2,211 files, 34.1MB)
Error: Directory not empty @ dir_s_rmdir - /usr/local/Cellar/python/3.7.2`

My brew doctor:

`Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.dylib
  /usr/local/lib/libpng15.15.dylib
  /usr/local/lib/libpspell.15.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la`

My brew config:

`brew config
HOMEBREW_VERSION: 1.9.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6841a6ec4b9052dec1e466580e42b1f0bc5d2323
Core tap last commit: 65 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/giorgosk/Library/Logs/Homebrew
CPU: quad-core 64-bit arrandale
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11`

doing cd into the directory, the following items show up:

`cd /usr/local/Cellar/python/3.7.2`

`Frameworks		Python Launcher 3.app	share`

Should I move them in /usr/local/bin ? or delete the dir manually?

**Comment by SMillerDev** [comment]
I'd suggest deleting them manually.
