### ISSUE TITLE
Emacs cask should satisfy mu formula's emacs dependency

### ISSUE THREAD

**Issue by dustinpaluch** [Homebrew/homebrew-core#36310]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### To reproduce: 
I installed the emacs cask `brew cask install emacs`, then mu `brew install mu`, which lists emacs as a dependency.

### What I expected:
I expected the emacs cask to satisfy the emacs dependency of mu.

### What I got:
Instead, homebrew downloaded and installed the non-cask emacs.

```
Homebrew 1.9.2
Homebrew/homebrew-core (git revision 6841; last commit 2019-01-22)
```

**Comment by SMillerDev** [comment]
Casks are different from formula and afaik can't be specified or used as a dependency (java is a special case there)

**Comment by MikeMcQuaid** [comment]
Yes, @SMillerDev is right here. If you're annoyed at having duplicate `emacs` you can either `brew unlink emacs` or adjust your PATH. The only issue I can see is that the `brew install emacs` link step may not succeed; if that's the case please let me know and I'll look at addressing it.

**Comment by dustinpaluch** [comment]
@SMillerDev I figured since `brew cask info emacs` returns 
```
emacs: 26.1-2
https://emacsformacosx.com/
/usr/local/Caskroom/emacs/26.1-2 (5 files, 274.7KB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/emacs.rb
```
That brew must know that I have emacs 26.1-2.

@MikeMcQuaid, yes, when the non-cask emacs is installed to satisfy the mu dependency, the link step fails.

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/ebrowse
Target /usr/local/bin/ebrowse
already exists. You may want to remove it:
  rm '/usr/local/bin/ebrowse'

To force the link and overwrite all conflicting files:
  brew link --overwrite emacs

To list all files that would be deleted:
  brew link --overwrite --dry-run emacs

Possible conflicting files are:
/usr/local/bin/ebrowse -> /Applications/Emacs.app/Contents/MacOS/bin/ebrowse
/usr/local/bin/emacs -> /Applications/Emacs.app/Contents/MacOS/Emacs
/usr/local/bin/emacsclient -> /Applications/Emacs.app/Contents/MacOS/bin/emacsclient
/usr/local/bin/etags -> /Applications/Emacs.app/Contents/MacOS/bin/etags
```

**Comment by MikeMcQuaid** [comment]
@dustinpaluch I have a similar issue with `docker`, personally. What would you think if `emacs` just avoided linking by default if the `emacs` cask was installed?

**Comment by dustinpaluch** [comment]
@MikeMcQuaid It's hard to disagree with the homebrew maintainer when he has your same problem. =)

Knowing little about the internals of homebrew, I'd still like to know why we can check if the emacs cask is installed (to avoid linking), but not allow formulas to check for/depend on (specific versions of) Casks, just for the sake of understanding.

**Comment by MikeMcQuaid** [comment]
> Knowing little about the internals of homebrew, I'd still like to know why we can check if the emacs cask is installed (to avoid linking), but not allow formulas to check for/depend on (specific versions of) Casks, just for the sake of understanding.

To be clear: both are technically possible but if we want to check for or depend on casks in cases like this we will need to be able to allow a package to be depending on a cask _or_ a formula and we don't have the capacity or facility to be able to test for both in CI (or have maintainers support both options) so we insist that formulae depend on formulae unless they can't exist e.g. for systemwide stuff like XQuartz, OSXFUSE, Java.
