### ISSUE TITLE
Weechat cannot use the included curl module

### ISSUE THREAD

**Issue by ericboehs** [Homebrew/homebrew-core#36342]
**Edit:** I tried installing `--with-curl` from the old version but not `--with-ruby` (and a few others) and it worked. So it seems the culprit isn't curl but some combination of the 10 dependencies:
```bash
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/4bdc1ce82824246dfa49d002033e1d6b2fcabe81/Formula/weechat.rb --with-python@2 --with-perl --with-curl
```

-----

- **What you were trying to do (and why)**
Download a script via `/script install` within weechat
- **What happened (include command output)**
The script was not downloaded. No output was displayed.
- **What you expected to happen**
The script to be able to download succesfully
- **Step-by-step reproduction instructions (by running `brew install` commands)**
brew install weechat # See repro gist below

## Investigation
I investigated this a bit as everything was working perfectly from my two-week old install of weechat. (Originally I installed weechat with `brew install weechat --with-python@2`.) I wanted to install a perl script within weechat so I uninstalled weechat and ran the same command with `--with-perl` appended. I was greeted with some warnings saying the flags were ignored.

I looked at the history of the weechat formula and saw that all the options had been added to the build command per https://github.com/Homebrew/homebrew-core/issues/31510. I tried using the previous version of the weechat formula with success (I ran `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/4bdc1ce82824246dfa49d002033e1d6b2fcabe81/Formula/weechat.rb --with-python@2 --with-perl`).

One-by-one, I added dependencies until I narrowed it down to installing weechat with `--with-curl`.  I'm not sure what is causing this to fail on my machine but I'd be interested to see if others are experiencing this.

**Gist Log**: https://gist.github.com/ericboehs/6ee5df63b8a8aa6d6832dbcb23aa85e1
**Script to reproduce**: https://gist.github.com/ericboehs/b76b7f20e72735337040041d694f239d

**Comment by MikeMcQuaid** [comment]
`brew uninstall --force weechat; brew install weechat` should get you a working installation again. We have removed the options from this formula.

**Comment by ericboehs** [comment]
@SMillerDev Yes.

@MikeMcQuaid That did not fix it.

Has anyone tried the repro script I provided?

**Comment by MikeMcQuaid** [comment]
@ericboehs If you `brew uninstall --force weechat; brew install weechat` do you have the same problem?

> Has anyone tried the repro script I provided?

I believe that you're right on that but that alone doesn't point to a solution.

**Comment by ericboehs** [comment]
@MikeMcQuaid Yes. I did per your last comment. I'm interested to see if others have the issue I'm having.

If this is a widespread problem, I'd think we'd want to remove `--with-curl` from the default installation option. I don't know the reasons `--with-curl` was originally added, perhaps we could lookup the commits/authors to find out more. Since there are approximately 50 installs of weechat a day, I'd expect a handful of users coming to report an issue by now.

**Comment by MikeMcQuaid** [comment]
> If this is a widespread problem, I'd think we'd want to remove `--with-curl` from the default installation option. I don't know the reasons `--with-curl` was originally added, perhaps we could lookup the commits/authors to find out more.

We're not passing an option, we're just providing a `curl` dependency. If that's enough to break `weechat` it seems like a bug in `weechat` itself.

**Comment by ericboehs** [comment]
I don't know enough about homebrew or weechat to weigh in on where the bug lies. I'm just reporting that since commit 692c1526320, where curl became a required dependency of weechat, I can no longer use integral features of weechat.

**Comment by ericboehs** [comment]
It looks like this is a known issue over at weechat's issues: https://github.com/weechat/weechat/issues/359

They closed the issue saying that it's not an issue with weechat.

**Comment by MikeMcQuaid** [comment]
@ericboehs I've tried to reproduce this in https://github.com/Homebrew/homebrew-core/pull/36409 but it fails with or without the `curl` dependency for me. Mind taking a look?

**Comment by MikeMcQuaid** [comment]
I've tried and failed to reproduce or fix this issue in https://github.com/Homebrew/homebrew-core/pull/36409 and resetting back to old versions and an unable to do so. @ericboehs if you're able to make a PR that fixes this issue we'll happily review it.

**Comment by ericboehs** [comment]
@javian I didn't realize what `gist-logs` was doing; I was just mindlessly following the GitHub Issue template. Here is the output from `brew gist-logs weechat` after installing the most recent (failing) version of weechat from homebrew: https://gist.github.com/ericboehs/66f67393cb20f7751f3ba7f1228368c1.

**Comment by ericboehs** [comment]
This has been resolved per https://github.com/Homebrew/homebrew-core/commit/73183d25db11e0848e3a67001cdfda4be2e1306c.
