### ISSUE TITLE
bash-completion@2: should source completion scripts in $(brew --prefix)/etc/bash_completion.d

### ISSUE THREAD

**Issue by weibeld** [Homebrew/homebrew-core#36377]
The completion scripts of other formulas in the `$(brew --prefix)/etc/bash_completion.d` folder are not sourced anymore (Mojave). It still worked when I installed `bash-completion@2` 11 days ago. So, maybe it has to do with this PR #35992.

**Comment by SMillerDev** [comment]
We'll need the filled out issue template to help you debug. 

Some thoughts: did you follow the new caveats already?

**Comment by weibeld** [comment]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Using automatically installed completion scripts of Homebrew formulas in  `/usr/local/etc/bash_completion.d` (assuming `brew --prefix` is `/usr/local` for the rest of the issue).

## What happened (include command output)

The completions in `/usr/local/etc/bash_completion.d` don't work.

## What you expected to happen

That the completions work. I previously installed `bash-completion@2` before 14 Jan 2019 and then these completions worked as expected. There was a PR on 14 January  #35992.

## Step-by-step reproduction instructions (by running `brew install` commands)

~~~bash
brew uninstall bash-completion@2
brew uninstall kubernetes-cli  # As an example formula that has a completion script
# Remove any previous commands of bash-completion@2 from ~/.bahsrc or ~/.bash_profile
# Start new shell
brew install bash-completion@2
# Add [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh" to ~/.bashrc
# Start new shell (completions in /usr/local/share/bash-completion/completions work now, test it with wget --f[tab][tab])
brew install kubernetes-cli  # Adds file /usr/local/etc/bash_completion.d/kubectl (completion script)
# Start new shell
kubectl [tab][tab]  # Completion does NOT work
~~~

In the end, completion for the `kubectl` example command doesn't work, even though the Homebrew formula added a completion script to `/usr/local/etc/bash_completion.d/`.

If I manually source `/usr/local/etc/bash_completion.d/kubectl` then completion works. So, it seems that `bash_completion` does not source the completion scripts in `/usr/local/etc/bash_completion.d`.

**Comment by weibeld** [comment]
Adding `--sysconfdir=#{etc}` to `./configure` in the formula (which was removed in #35992) fixes the problem. I created a PR here #36383.

**Comment by fxcoudert** [comment]
poke @maxim-belkin

**Comment by weibeld** [comment]
***

Point 1:

So then the point of confusion is that `bash-completion@2` has nothing to do with `/usr/local/etc/bash_completion.d`, whereas `bash-completion` had. The thing is that many formulas put their completion scripts in `/usr/local/etc/bash_completion.d`, probably because with `bash-completion` they were automatically sourced at this location.

And this is behaviour is also still assumed in the instructions of many tools, for example, `kubectl` [here](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion), or `docker` [here](https://docs.docker.com/docker-for-mac/#bash) (i.e. just put the completion scripts in `/usr/local/etc/bash_completion.d` and everything will work, no need to source them individually).

So, this setup won't work anymore when updating from `bash-completion` to `bash-completion@2`. Users might get confused and documentations of third-party tools would need to be rewritten (they're basically incorrect now if the recommend `bash-completion@2` but still propose the old approach of installing completion scripts). So wouldn't it make sense to still maintain the support for `/usr/local/etc/bash_completion.d` in `bash-completion@2`?

***

Point 2:

I saw what you said about the nature of `/usr/local/etc/profile.d/bash-completion.sh`. It's a symlink with the current version and a hard file if adding `--sysconfdir=#{dir}`.

However, I don't know why, but when I install the formula from a locally edited source and with `--sysconfdir=#{dir}`, the completion scripts in `/usr/local/etc/bash_completion.d` start working immediately, and with the upstream version (without `--sysconfdir=#{dir}`) they don't.

The commands look like this:

~~~bash
$ brew install -s /Users/dw/Desktop/homebrew-core/Formula/bash-completion@2.rb
==> Downloading https://github.com/scop/bash-completion/releases/download/2.8/bash-completion-2.8.tar.xz
Already downloaded: /Users/dw/Library/Caches/Homebrew/downloads/9f11fab67aca82865c14287082d3e18302b096bf8ab8a6657b14838cae3933de--bash-completion-2.8.tar.xz
==> ./configure --prefix=/usr/local/Cellar/bash-completion@2/2.8 --sysconfdir=/usr/local/etc
==> make install
==> Caveats
Add the following to your ~/.bash_profile:
  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
==> Summary
🍺  /usr/local/Cellar/bash-completion@2/2.8: 666 files, 932.4KB, built in 15 seconds
~~~

Completions in `/usr/local/etc/bash_completion.d` work.

~~~bash
$ brew install bash-completion@2
==> Downloading https://homebrew.bintray.com/bottles/bash-completion@2-2.8.mojave.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring bash-completion@2-2.8.mojave.bottle.1.tar.gz
==> Caveats
Add the following to your ~/.bash_profile:
  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
==> Summary
🍺  /usr/local/Cellar/bash-completion@2/2.8: 667 files, 933.8KB
~~~

Completions in `/usr/local/etc/bash_completion.d` don't work.

**Comment by maxim-belkin** [comment]
What do you mean when you say `Completions in /usr/local/etc/bash_completion.d work.` or ...`don't work`?

**Comment by maxim-belkin** [comment]
OK, here is what happens (I assume you source `/usr/local/etc/profile.d/bash_completion.sh`):

`configure` script has the following line
```
compatdir=$sysconfdir/bash_completion.d
```
The default value for `sysconfdir` is `${prefix}/etc`. With `--sysconfdir=#{etc}`, `./configure` script in `bash-completion@2` changes default value for `BASH_COMPLETION_COMPAT_DIR` from 
```
/usr/local/Cellar/bash-completion@2/2.8/etc/bash_completion.d
```
to
```
/usr/local/etc/bash_completion.d
```
When one sources `/usr/local/etc/profile.d/bash_completion.sh`, it also sources files in `$BASH_COMPLETION_COMPAT_DIR`.

So, what you observe is, essentially, a by-product: `bash-completion@2` sources  all files in `$BASH_COMPLETION_COMPAT_DIR` which, when configured with `--sysconfdir=#{etc}`, is `/usr/local/etc/bash_completion.d`.

**Comment by maxim-belkin** [comment]
A note on `BASH_COMPLETION_COMPAT_DIR` (from `doc/bash_completion.txt`):

> *BASH_COMPLETION_COMPAT_DIR*::                                                     
    Directory for pre-dynamic loading era (pre-2.0) backwards compatibility        
    completion files that are loaded eagerly from `bash_completion` when it is  
    loaded. If unset or null, the default compatibility directory to use is        
    `/etc/bash_completion.d`.

**Comment by weibeld** [comment]
So wouldn't it make sense to set `BASH_COMPLETION_COMPAT_DIR` to a useful value, i.e. `/usr/local/etc/bash_completion.d`, because most formulas install their completion scripts there?

**Comment by maxim-belkin** [comment]
1. The purpose of `BASH_COMPLETION_COMPAT_DIR` is very different from "normal" use
2. `/usr/local/etc/bash_completion.d` should be sourced by users even when `bash-completion@2` is not installed.

**Comment by weibeld** [comment]
So, is this the official way how `bash-completion@2` works? That users are responsible themselves for completion scripts other formulas put in `/usr/local/etc/bash_completion.d` or elsewhere?

**Comment by weibeld** [comment]
Yeah, it makes sense as a design decision. Especially because it's possible to use completion scripts without `bash-completion` (for example, the [completion script for Git](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) works without `bash-completion` and it even works with Bash 3.2). So in that case, if one used only completion scripts that don't depend on `bash-completion`, one would have to manually source them too.

But there is just currently a confusion about this topic, which is reflected in issues like [here](https://github.com/kubernetes/kubectl/issues/37) and [here](https://github.com/kubernetes/kubernetes/issues/27876), and has to do with Bash 3.2 vs Bash 4.1+ and `bash-completion` vs `bash-completion@2`.

The following two situations are currently possible on a Mac. The first one applies by default:

- macOS by default uses Bash 3.2 
- Uses `bash-completion`
- Completion scripts that other formulas put in `/usr/local/etc/bash_completion.d` are sourced automatically by `bash-completion`
    - That's what's described in the "setting up auto-completion" documentations of many tools
- **BUT:** many completion scripts in general don't work properly with Bash 3.2, because they make use of completion features of Bash 4.1+ (resulting in `command not found` errors, and non-actions where there should be actions)

If a macOS user upgraded to Bash 4.1+ (which is recommend), the situation looks as follows:

- Bash 4.1+
- Uses `bash-completion@2`
- Other formulas still put their completion scripts in `/usr/local/etc/bash_completion.d`
- **BUT:** the user is now responsible him/herself to source any completion scripts in `/usr/local/etc/bash_completion.d` (or anywhere else on the system)

The second scenario is the recommended one for every macOS user (it's a pity that Apple includes a completely outdated version of Bash in macOS, otherwise, a lot of the confusion wouldn't be there). 

I'm trying to clear this up to figure out how to more clearly state these situations in tools that use `bash-completion` (any version). For example, documentations like [here](https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion) or [here](https://docs.docker.com/docker-for-mac/#bash) would need to be updated. I also wrote an article about it [here](https://itnext.io/programmable-completion-for-bash-on-macos-f81a0103080b), which in that case I need to update to reflect the correct behaviour of `bash-completion@2`.

**Comment by weibeld** [comment]
`bash-completion` installs its completion scripts to `/usr/local/etc/bash_completion.d` and it sources all the scripts in this directory. Other formulas also install their completion scripts to this directory, which means that `bash-completion` sources them too. For that reason, if you used `bash-completion`, you didn't need to source your own scripts in `/usr/local/etc/bash_completion.d`, because it was already done by `bash-completion`, even if it was just a side-effect.

This changed with `bash-completion@2`: scripts in `/usr/local/etc/bash_completion.d` are not sourced by anything anymore, and you need to take care of it yourself.

But the documentations I referred to above still assume that you can put something in `/usr/local/etc/bash_completion.d` and it gets magically sourced. Because it was like this with `bash-completion`, even if it was not by design, but just a side effect.

**Comment by weibeld** [comment]
There is nothing wrong with the design of `bash-completion` and `bash-completion@2`, but it seems its correct usage is not fully understood, which results in some confusion.

**Comment by maxim-belkin** [comment]
> There is nothing wrong with the design of `bash-completion` and `bash-completion@2`, but it seems its correct usage is not fully understood, which results in some confusion.

I disagree. Formula, in my opinion, should not be sourcing files that reside outside of its "Cellar". Formula should be able to instruct user on "Best practices", but this should be responsibility of the user. Currently, besides providing their own Bash completions, `bash-completion*` formulae source files outside of its Cellar - not cool.

**Comment by weibeld** [comment]
It's possible, I don't know Homebrew well enough for this. But so this would only be the case in `bash-completion`, right? Because in `bash-completion@2`, the `/usr/local/share/bash-completion` folder, as well as `/usr/local/etc/profile.d/bash_completion.sh` are symlinked into the Cellar.

So was this the reason to change `bash-completion@2` like this, to fix this design flaw in `bash-completion`?
