### ISSUE TITLE
llvm@4 formula does a string replacement without escaping

### ISSUE THREAD

**Issue by chrisseaton** [Homebrew/homebrew-core#36386]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Use `scan-build`, because I wanted to run static analysis on some C code.

- What happened (include command output)

It prints

```
Possible unintended interpolation of @4 in string at /usr/local/opt/llvm@4/bin/scan-build line 1433.
```

- What you expected to happen

Not to print that.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install llvm@4
$ export LLVM4_HOME=/usr/local/opt/llvm@4
$ export PATH="$LLVM4_HOME/bin:$PATH"
$ touch test.c
$ scan-build --use-analyzer `which clang` -c test.c
```

The issue is that you're doing this text replacement

```ruby
inreplace "#{share}/clang/tools/scan-build/bin/scan-build", "$RealBin/bin/clang", "#{bin}/clang"
```

https://github.com/Homebrew/homebrew-core/blob/bd61515ed4f9bdca20b0466561279263bd996fa5/Formula/llvm%404.rb#L114

You need to escape this string so that it's valid Perl source code.

```
$ brew gist-logs llvm@4
Error: No logs.
```

```
$ brew config
HOMEBREW_VERSION: 1.9.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7be9ac1e9d550df18392550d611c5ff10b91292b
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fb7fcf421eb4581ce11a634ed2e8a70866a7fe00
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/chrisseaton/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2, 1.8.0_201
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@2
```

**Comment by SMillerDev** [comment]
could you make a pull request to include this solution?

**Comment by chrisseaton** [comment]
I can try, but I don't know Perl to know what needs to be escaped. I might look if Perl has a separate string syntax that doesn't do interpolation, like Ruby does.

**Comment by chrisseaton** [comment]
The issue's still there.

**Comment by fxcoudert** [comment]
In Perl strings enclosed in double quotes, `@` should be quoted to `\@`.

**Comment by fxcoudert** [comment]
@chrisseaton can you test the pull request at #37028 please?

**Comment by chrisseaton** [comment]
@fxcoudert sorry I'm not sure I'm doing this properly - I don't see the `@` being escaped. I already had `llvm@4` installed, so I uninstalled it and tried to install again. That overwrote the patch I applied from this PR, so I applied it again and I think I'm using it when I `brew install llvm@4` but as I say I don't see the `@` being escaped.

I don't know anything about Homebrew development so I'm not sure what the workflow is supposed to be, and to know if the patch I've applied in `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` is being used or somehow bypassed. Is the `llvm@4/4.0.1_1/.brew/llvm@4.rb` in the binary bottle used instead of this patched version? It seems like I have both a `llvm@4.rb` in the bottle and a `llvm@4.rb` in this repository?

**Comment by fxcoudert** [comment]
You need to apply the patch to the formula, then `brew reinstall -s llvm@4`: note the `-s` which will force a rebuild from source, ensuring the patch is indeed take into account.

**Comment by fxcoudert** [comment]
Should be fixed, please ask to reopen if it's not the case.

**Comment by chrisseaton** [comment]
That works, thanks.
