### ISSUE TITLE
B2sum missing "-c" options

### ISSUE THREAD

**Issue by hajes** [Homebrew/homebrew-core#36384]
macOS 10.14.2 + brew

I do not know why but there is missing `b2sum -c <checksum_file>` in macOS version. Debian 9 b2sum version contains "-c" option for checking list of files.

`b2sum --help`
`Usage: b2sum [OPTION]... [FILE]...`

`With no FILE, or when FILE is -, read standard input.`

 ` -a <algo>    hash algorithm (blake2b is default): `
               `[blake2b|blake2s|blake2bp|blake2sp]`
  `-l <length>  digest length in bits, must not exceed the maximum for`
               `the selected algorithm and must be a multiple of 8`
  `--tag        create a BSD-style checksum`
  `--help       display this help and exit`

Any suggestions, please?

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by hajes** [comment]
Unsure, what else do you need???

use any Apple PC with macOS X and type `b2sum -c <checksum-file>`

RESULT:

`b2sum: invalid option -- c`

- [] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

- [X] ran `brew update` and can still reproduce the problem?
YES

- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
YES

- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

`brew gist-logs b2sum
Error: No logs.`


To help us debug your issue please explain:
- What you were trying to do (and why)

checksum list of files in external file as suppose to work on Linux systems such as Debian 9

- What happened (include command output)

`b2sum: invalid option -- c`

- What you expected to happen

read external file and check hash of files inside the list

- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by hajes** [comment]
Debian Linux 2.6.32

b2sum --help

Usage: b2sum [OPTION]... [FILE]...
Print or check BLAKE2 (512-bit) checksums.

With no FILE, or when FILE is -, read standard input.

  -b, --binary         read in binary mode
  -c, --check          read BLAKE2 sums from the FILEs and check them
  -l, --length         digest length in bits; must not exceed the maximum for
                       the blake2 algorithm and must be a multiple of 8
      --tag            create a BSD-style checksum
  -t, --text           read in text mode (default)

The following five options are useful only when verifying checksums:
      --ignore-missing  don't fail or report status for missing files
      --quiet          don't print OK for each successfully verified file
      --status         don't output anything, status code shows success
      --strict         exit non-zero for improperly formatted checksum lines
  -w, --warn           warn about improperly formatted checksum lines

      --help     display this help and exit
      --version  output version information and exit

The sums are computed as described in RFC 7693.  When checking, the input
should be a former output of this program.  The default mode is to print a
line with checksum, a space, a character indicating input mode ('*' for binary,
' ' for text or where binary is insignificant), and name for each FILE.

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Full documentation at: <http://www.gnu.org/software/coreutils/b2sum>
or available locally via: info '(coreutils) b2sum invocation'

**Comment by SMillerDev** [comment]
it seems like this package is also part of coreutils. What does the b2sum from `brew install coreutils` do?

**Comment by hajes** [comment]
uninstalled b2sum and installed coreutils.

b2sum in coreutils contains "-c" option.

Perhaps, erase "b2sum" formulae and refer b2sum to coreutils

it looks like standalone b2sum is some obsolete version or so
