### ISSUE TITLE
Mojave: Git uses broken tcl-tk

### ISSUE THREAD

**Issue by kubark42** [Homebrew/homebrew-core#36390]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, official formula (not cask)? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

===============

Problem: `git-gui`, a subcomponent of git bundled with the git release, does not function correctly with Mojave (C.f. https://www.mail-archive.com/git@vger.kernel.org/msg166887.html)

This is because MacOS uses an antiquated version of Tcl/Tk. Apparently `git` shipped by homebrew doesn't use homebrew's tcl-tk package, but instead makes a copy of Apple's old version.

It is unlikely Apple will ever update their version of Tcl/Tk, as it is bundled in order to support macOS internals. (C.f. https://discussions.apple.com/thread/8066794). 

Fortunately, the recent Tcl/Tk v8.6.9 resolves the issue and there have been reports that getting the git binary directly from https://sourceforge.net/projects/git-osx-installer/files/git-2.20.1-intel-universal-mavericks.dmg/download?use_mirror=autoselect allows `git-gui` to work as expected.

Proposed solution: have `git` use Homebrew's `tcl-tk` package, either by default or by `--configure` flag.

**Comment by MikeMcQuaid** [comment]
We can't justify adding a `tcl-tk` dependency for all Git users and we're not adding more options to formulae, sorry. If it's completely useless we should remove it from the package.

**Comment by kubark42** [comment]
`git-gui` is a built-in GUI tool for git, https://git-scm.com/download/gui/linux. I don't quite follow the arguments here. Could we have this issue open for discussion a little longer because something doesn't feel quite right here.

Anecdotally, It's a very useful tool for people who routinely use git cross-platform since it is the only GUI which you can be sure you will have. It'd be a shame to have brew on macOS become the only platform where developers can't depend on uniformity.

**Comment by MikeMcQuaid** [comment]
> `git-gui` is a built-in GUI tool for `git`, ["Git comes with built-in GUI tools for committing (git-gui) and browsing (gitk)"](https://git-scm.com/downloads/guis).

Yep, I'm familiar with it, thanks. As noted on the mailing list thread: `gitk` still works.

> I don't quite follow the argument being made for allowing part of `git` to atrophy inside `brew`.

I'm not making that argument but I am saying I disagree with adding a heavy GUI dependency for the minority of users who use `git-gui` in comparison to the many better alternatives. This is also something that could be fixed in the upstream Git project.

> Anecdotally, `git-gui` is a very useful tool for people who routinely use `git` cross-platform since it is the only GUI which you can be sure you will have. It'd be a shame to have `brew` on macOS become the only platform where developers can't depend on uniformity.

That may be an argument for keeping it around if it isn't completely useless, then.

> Something doesn't quite feel right here, could we have this issue open for discussion a little longer?

Sorry, no. We can continue discussion in a closed issue but the status of this indicates the Homebrew maintainers have triaged it and don't plan on working on a change here.

**Comment by arichardson** [comment]
I really miss having a working git-gui since I update to mojave. I have now memorized where the dialog buttons should be but it is quite annoying to use. Since adding tcl-tk as a dependency is not acceptable, how about splitting out git-gui to a separate formula? Or is that also not acceptable?

**Comment by SMillerDev** [comment]
I think having it in a cask might be the best option here.

**Comment by kubark42** [comment]
A cask would be nice. I can't agree with the assertion that there are better alternatives out there. Cross-platform consistency is critical in my field.

**Comment by SMillerDev** [comment]
Cross platform consistency isn't much of a problem for most people using a macOS package manager afaik. If you could make this into a cask I guess that'd be your best solution.
