### ISSUE TITLE
Error parsing option bluray-device (option not found)

### ISSUE THREAD

**Issue by jbrodriguez** [Homebrew/homebrew-core#36440]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
⟩ brew gist-logs mpv
Error: No logs.
```

- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
⟩ brew config
HOMEBREW_VERSION: 1.9.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a912c369125caca5e1e3929e942bbb946ce6367
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4851f31df8a4f5ce3e4b254646a9f9e82dab25e7
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/someone/Library/Logs/Homebrew
HOMEBREW_NO_ANALYTICS: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_172
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

```
⟩ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
install mpv with bluray and archive support

- What happened (include command output)

```
$ mpv bd:// --bluray-device=Bluray.iso
Error parsing option bluray-device (option not found)
```

- What you expected to happen
should have been installed with libbluray libarchive support

- Step-by-step reproduction instructions (by running `brew install` commands)
```
⟩ brew install mpv --with-libbluray --with-libarchive --with-libdvdnav --with-libdvdread --with-bundle
Warning: mpv: this formula has no --with-bundle option so it will be ignored!
Warning: mpv: this formula has no --with-libarchive option so it will be ignored!
Warning: mpv: this formula has no --with-libbluray option so it will be ignored!
Warning: mpv: this formula has no --with-libdvdnav option so it will be ignored!
Warning: mpv: this formula has no --with-libdvdread option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/mpv-0.29.1_2.high_sierra.bottle.1.tar.gz
Already downloaded: /Users/someone/Library/Caches/Homebrew/downloads/c0beac9adf8137390fbb6fa80db63644bc62e4fa07ba5549ae83b28a2d7b1419--mpv-0.29.1_2.high_sierra.bottle.1.tar.gz
==> Pouring mpv-0.29.1_2.high_sierra.bottle.1.tar.gz
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/mpv/0.29.1_2: 74 files, 87.2MB
```

This commit:

https://github.com/Homebrew/homebrew-core/commit/1fdd9b152760e9d743964dd955c1ae816a3ca191

removed the config options, but I'm not sure what the alternative should be now.

**Comment by SMillerDev** [comment]
The alternative would be to maintain your own version that has these options or, if they make sense for the majority of users, propose them as a default in a pull request.

**Comment by SMillerDev** [comment]
@mlindner please stop hijacking issues.

**Comment by mlindner** [comment]
@SMillerDev I am not hijacking any issues. This is the exact issue I am having. The options I need (namely bluray and dvd support among others) is now no longer available.

**Comment by SMillerDev** [comment]
Why is it not an option? There's tooling and documentation for it. If you have trouble with either you can open an issue.

Gonna close this now as the answer to the initial question was given hours ago.
