### ISSUE TITLE
brew install gtk-mac-integration only installs for Python 2

### ISSUE THREAD

**Issue by posita** [Homebrew/homebrew-core#36443]
```
$ brew install gtk-mac-integration
…
$ python2 -c 'import gtk ; print("okay")'
2019-01-27 09:31:04.003 Python[93560:12045017] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
okay
$ python3 -c 'import gtk ; print("okay")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gtk'
```

I filed #35853 earlier, when Python 2 support was removed from `libxml2` and `libxslt` and was informed that was by design. I'm trying to port chirp to Python3, which requires `libxml2`, `libxslt`, and `gtk-mac-integration`. In its current state, brew cannot run chirp in either Python2 or Python3.

**Comment by SMillerDev** [comment]
Does upstream support python 3?

**Comment by tschoonj** [comment]
When you run `import gtk`, you are importing `pygtk`, not `gtk-mac-integration`.

So your failure only reflects the fact that `pygtk` is not supported by python3.

If you want to use gtk-mac-integration in python 2, you will need to call `import gtkosx_application`.
In python3 things are different as one is expected to use the gobject-introspection bindings, so you will need to call `from gi.repository import GtkosxApplication`.
