### ISSUE TITLE
ask-cli subtly broken – remove, if unfixable?

### ISSUE THREAD

**Issue by alexbepple** [Homebrew/homebrew-core#36444]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/ed622b73c723d493e30bea8c0a91513f
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

## What you were trying to do (and why)

I wish to use ask-cli, https://www.npmjs.com/package/ask-cli, for which there is a Homebrew core formula, https://github.com/Homebrew/homebrew-core/blob/master/Formula/ask-cli.rb

## What happened (include command output), what you expected to happen

The formula installs without any obvious problems. Some functionality also works as intended, including `ask init` and `ask deploy`. However, some commands fail, e.g. `ask lambda` produces

    ask-lambda(1) does not exist, try --help`

instead of

    Usage: ask-lambda
    $ ask lambda [command]
    The Lambda command enables you to retrieve and post code for an AWS Lambda function.
    [...]

I have tried `--build-from-source` with same results.

I have tried editing the formula (`brew edit ask-cli`) and replacing the line

    system "npm", "install", *Language::Node.std_npm_install_args(libexec)

with

    system "npm", "-g", "install", *Language::Node.std_npm_install_args(libexec)

i.e. to install it globally – to no avail.

It seems that `ask-cli` can only be installed with `npm -g`, cp. https://stackoverflow.com/questions/51533580/ask-cli-api-or-lambda-does-not-exist

As the current formula is partially broken and there seems no clear way how to fix it, I suggest removing it. The current state is very confusing. You install it, some stuff works. So when `ask lambda` does not work, you first look at yourself for the problem.

**Comment by SMillerDev** [comment]
This seems like it's failing to pick up information in the environment. I'd say it's preferable to fix the issue.

**Comment by alexbepple** [comment]
If it’s fixable: sure. I am out of my depth, though.

**Comment by SMillerDev** [comment]
the version bump in https://github.com/Homebrew/homebrew-core/pull/36468 might help already.

**Comment by SMillerDev** [comment]
Could you test again after doing an upgrade?

**Comment by alexbepple** [comment]
@SMillerDev Are you open to removing a defunct formula now?

**Comment by SMillerDev** [comment]
>@SMillerDev Are you open to removing a defunct formula now?

@alexbepple sure, this isn't one though. I actually fixed it locally but forgot to make a pull request for it. I'll see if I can get to that today.

**Comment by alexbepple** [comment]
@SMillerDev Cool. Thanks. Looking forward to it.

**Comment by SMillerDev** [comment]
Should be fixed with the merger of #37096

**Comment by SMillerDev** [comment]
You might need to install from source using `brew install -s ask-cli` the next version will have this fix included in the bottle.

**Comment by alexbepple** [comment]
Thanks. :)
