### ISSUE TITLE
SOX brew fails w Ogg/Vorbis flag

### ISSUE THREAD

**Issue by itsalljustaride** [Homebrew/homebrew-core#3646]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [NA] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Tried building SOX with Ogg/Vorbis flags. Regular brew install sox works, but vorbis returns following:

https://gist.github.com/8c1149cb475ebace33fce86f3fcfb1a8

Thanks.

**Comment by itsalljustaride** [comment]
Also seems to raise a similar issue when I try "brew install sox --with-lame".

**Comment by ilovezfs** [comment]
You can try
```
brew update
brew uninstall -f lame
brew prune
brew install lame
brew install --with-libvorbis  --with-lame sox
```

**Comment by itsalljustaride** [comment]
That worked. Thanks!
