### ISSUE TITLE
Now new version: vim. YouCompleteMe unavailable: requires Vim compiled with Python 2.x support

### ISSUE THREAD

**Issue by zhaoxi1988** [Homebrew/homebrew-core#36462]
background: [python2 python3](https://github.com/Homebrew/homebrew-core/issues/36407)

```
Homebrew 1.9.3-14-g2cc5086
Homebrew/homebrew-core (git revision 97535e; last commit 2019-01-26)
Homebrew/homebrew-cask (git revision eab42; last commit 2019-01-26)
```

**Comment by SMillerDev** [comment]
Please fill out the issue template, without it it's very hard to debug issues. As for your plugins not installing, those aren't distributed by homebrew so it's probably not something you'll get active support for. I'd rather suggest pointing the author of your plugin to https://pythonclock.org/ and asking for python 3 support.

**Comment by SMillerDev** [comment]
Gonna close this now until the info required by the template is present.
