### ISSUE TITLE
brew services start postgresql@10 fails to start postgresql server

### ISSUE THREAD

**Issue by ckhall** [Homebrew/homebrew-core#36536]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 1.9.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6a912c369125caca5e1e3929e942bbb946ce6367
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b8d4a5e33d4d87ee22ad15dcdc87f2075acd5d81
Core tap last commit: 46 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /Users/ckhall/Library/Logs/Homebrew
HOMEBREW_NO_GITHUB_API: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

```
$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

install and run postgresql@10 formulae using `brew services` command

- What happened (include command output)

after successfully installing postgresql@10 formulae via `brew install postgresql@10`, i then attempted to start postgresql using `brew services start postgresql@10`.

```
$ brew services start postgresql@10
==> Successfully started `postgresql@10` (label: homebrew.mxcl.postgresql@10)
```

however, no postgresql server is running, but the plist file was copied to ~/Library/LaunchAgents

```
$ pwd && ls homebrew*
/Users/ckhall/Library/LaunchAgents
homebrew.mxcl.postgresql@10.plist
```

- What you expected to happen

The postgresql server to start.  After reviewing the formulae, it appears that it initializes the db incorrectly at https://github.com/Homebrew/homebrew-core/blob/06492f99ec16feafdebd1be8752ef622653ae0b2/Formula/postgresql%4010.rb#L88

The plist file specifies the server data directory at https://github.com/Homebrew/homebrew-core/blob/06492f99ec16feafdebd1be8752ef622653ae0b2/Formula/postgresql%4010.rb#L113 but this is not the same name it was initialized with on line 88.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>homebrew.mxcl.postgresql@10</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/postgresql@10/bin/postgres</string>
    <string>-D</string>
    <string>/usr/local/var/postgresql@10</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/usr/local</string>
  <key>StandardOutPath</key>
  <string>/usr/local/var/log/postgresql@10.log</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/log/postgresql@10.log</string>
</dict>
</plist>
```

manually changing the data directory name to `postgresql@10` fixes the issue.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install postgresql@10
brew services start postgresql@10
tail /usr/local/var/log/postgresql@10.log (to check for errors)
cat ~/Library/LaunchAgents/homebrew.mxcl.postgresql@10.plist
```

**Comment by elizabrock** [comment]
I think that PR https://github.com/Homebrew/homebrew-core/pull/35577 is the fix for this issue.
