### ISSUE TITLE
v8 installs a packaged libicuuc.dylib to /usr/local/lib thus conflicting with icu4c caveat  

### ISSUE THREAD

**Issue by edporras** [Homebrew/homebrew-core#36551]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

A user reported a conflicting issue trying to install a gem I wrote that depends on `icu4c`. While investigating, we tracked it down to the [`v8`](https://formulae.brew.sh/formula/v8) formula linking a packaged `libicuuc.dylib` to `/usr/local/lib`:

```
$ ls -l /usr/local/lib/libicuuc.dylib 
lrwxr-xr-x  1 admin  admin    42B Jan 28 22:06 /usr/local/lib/libicuuc.dylib -> ../Cellar/v8/7.1.302.28/lib/libicuuc.dylib
```

This seems like an error as the `icu4c` is [marked `keg-only` to avoid conflicts with the bundled macOS library](https://github.com/Homebrew/homebrew-core/blob/master/Formula/icu4c.rb#L16).

- What you expected to happen

I expect to not find `/usr/local/lib/libicuuc.dylib` 😀

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install v8
ls -l /usr/local/lib/libicuuc.dylib
```

**Comment by rainkinz** [comment]
For details on how to reproduce this, see: https://github.com/edporras/edn_turbo/issues/6

**Comment by edporras** [comment]
Output of the last two items in the check list: 

```sh
~ $ brew gist-logs v8
Error: No logs.
~ $ brew config
HOMEBREW_VERSION: 2.0.0-14-ge1caf63
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1caf63cecee6a7e003a77d8381fa5a06b5f0768
Last commit: 5 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 385c946a4ad879cde422d33b84fdbcccb2b7d5bd
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/admin/Library/Logs/Homebrew
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_161
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
~ $ brew doctor
Your system is ready to brew.
```

**Comment by edporras** [comment]
There is still an issue with `v8` conflicting with the `icu-4c` formula caveat.

**Comment by fxcoudert** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/38140
