### ISSUE TITLE
Add `cargo` alias for the `rust` formula

### ISSUE THREAD

**Issue by waldyrious** [Homebrew/homebrew-core#36560]
I'm not sure the alias feature is meant to be used for cases like this. There are some similar cases, such as the `diction` formula that installs both the `diction` and the `style` binaries, and therefore has a `style` alias; and `dos2unix` which has a `unix2dos` alias for the same reason -- among others.  If this would be ok, I'll gladly submit a PR.

If not, my next question would be: is there a way to add extra data to be searched by [the code](https://github.com/Homebrew/brew/blob/0f270d81154303e7908fc668016dc400682c13eb/Library/Homebrew/cmd/install.rb#L344-L357) that searches for similarly named formulae (or some equivalent mechanism)? I tried reading the contribution documentation but couldn't find anything related to this.

**Comment by jonchang** [comment]
You could add something to [missing_formula.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/missing_formula.rb). Feel free to open a pull request and I (or another maintainer) will review it.

**Comment by waldyrious** [comment]
Thanks for the pointer, @jonchang! I've submitted https://github.com/Homebrew/brew/pull/5678 following your suggestion.
