### ISSUE TITLE
Mednafen performance fell off a cliff because of SDL 2.0.9

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew-core#36564]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

SDL 2.0.9 has an upstream bug which causes severe performance degradation in at least one app, Mednafen. The framerate is capped at approximately 28FPS instead of the expected 60FPS. This bug was introduced by a single commit between SDL 2.0.8 and 2.0.9, and reproduces using the tip of SDL's hg repository build outside Homebrew. Here's the upstream bug report: https://bugzilla.libsdl.org/show_bug.cgi?id=4481

Steps to reproduce:
1. `brew install mednafen`.
2. Download a freeware game, such as [Super Bat Puncher](http://morphcat.de/superbatpuncher/).
3. Run `mednafen "Super Bat Puncher Demo.nes"`.
4. Open the FPS counter with shift+F1.

Expected behaviour:

The game should run at or around 60FPS.

Actual behaviour:

The game runs at or around 28FPS, with broken sound and half-speed gameplay.

**Comment by fxcoudert** [comment]
Not sure why the label `bug` (which implies the problem is in the formula) rather than `upstream-bug`, given that the problem comes from SDL 2.0.9 itself, rather than any configuration or modification made in Homebrew.
