### ISSUE TITLE
ruby@2.4 bottle depends on gmp, despite not being listed as dependency

### ISSUE THREAD

**Issue by chriso** [Homebrew/homebrew-core#36612]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/3a9a10d421b6574263fcd892c8a61a9d
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

---

`ruby@2.4`, when installed from bottle, depends on `gmp`. This is fine, however [it isn't listed as an explicit dependency](https://github.com/Homebrew/homebrew-core/blob/d1cd79303014e83e6887ac83d7ba204f85ec31ae/Formula/ruby%402.4.rb#L16-L19) and so ruby is unusable:

```
$ brew install ruby@2.4
==> Downloading https://homebrew.bintray.com/bottles/ruby@2.4-2.4.5_1.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ruby@2.4-2.4.5_1.mojave.bottle.tar.gz
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/Cellar/ruby@2.4/2.4.5_1/bin/ruby
  Reason: image not found
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall ruby@2.4`
==> Caveats
<snip>
==> Summary
🍺  /usr/local/Cellar/ruby@2.4/2.4.5_1: 13,891 files, 33.1MB
```

```
$ /usr/local/opt/ruby@2.4/bin/ruby --version
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/opt/ruby@2.4/bin/ruby
  Reason: image not found
zsh: abort      /usr/local/opt/ruby@2.4/bin/ruby --version
$ otool -L /usr/local/opt/ruby@2.4/bin/ruby 
/usr/local/opt/ruby@2.4/bin/ruby:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1560.12.0)
	/usr/local/Cellar/ruby@2.4/2.4.5_1/lib/libruby.2.4.5.dylib (compatibility version 2.4.0, current version 2.4.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

It works if I manually install `gmp`:

```
$ brew install gmp
<snip>
$ /usr/local/opt/ruby@2.4/bin/ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]
```

Curiously, if I install from source the `gmp` dependency disappears and it works as expected:

```
$ brew uninstall gmp
<snip>
$ brew reinstall ruby@2.4 --build-from-source
<snip>
$ /usr/local/opt/ruby@2.4/bin/ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-darwin18]
$ otool -L /usr/local/opt/ruby@2.4/bin/ruby 
/usr/local/opt/ruby@2.4/bin/ruby:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1560.12.0)
	/usr/local/Cellar/ruby@2.4/2.4.5_1/lib/libruby.2.4.5.dylib (compatibility version 2.4.0, current version 2.4.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by chdiza** [comment]
This sounds like an inadvertent, opportunistic link during bottling.

**Comment by jonchang** [comment]
Thanks for reporting this. Could either of you @chriso @chdiza that are experiencing this please run `brew linkage ruby@2.4` and paste the results here? If it says that `gmp` is an undeclared dependency can you open a pull request that bumps the revision of `ruby@2.4` and check the build logs to see if `brew linkage` reports the same thing again? Thanks!

**Comment by chriso** [comment]
@jonchang 

Fresh install:

```
$ brew install ruby@2.4
==> Downloading https://homebrew.bintray.com/bottles/ruby@2.4-2.4.5_1.mojave.bottle.tar.gz
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/4873193c92ef70f7d71d3984e265c6473564d5e8d3ae25ab2e3be959da6b9ae3--ruby@2.4-2.4.5_1.mojave.bottle.tar.gz
==> Pouring ruby@2.4-2.4.5_1.mojave.bottle.tar.gz
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /usr/local/Cellar/ruby@2.4/2.4.5_1/bin/ruby
  Reason: image not found
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall ruby@2.4`
==> Caveats
By default, binaries installed by gem will be placed into:
  /usr/local/lib/ruby/gems/2.4.0/bin

You may want to add this to your PATH.

ruby@2.4 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have ruby@2.4 first in your PATH run:
  echo 'export PATH="/usr/local/opt/ruby@2.4/bin:$PATH"' >> ~/.zshrc

For compilers to find ruby@2.4 you may need to set:
  export LDFLAGS="-L/usr/local/opt/ruby@2.4/lib"
  export CPPFLAGS="-I/usr/local/opt/ruby@2.4/include"

==> Summary
🍺  /usr/local/Cellar/ruby@2.4/2.4.5_1: 13,891 files, 33.1MB
```

The command you asked for:

```
$ brew linkage ruby@2.4
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  /usr/lib/libSystem.B.dylib
  /usr/lib/libffi.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libutil.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/gdbm/lib/libgdbm.6.dylib (gdbm)
  /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/opt/readline/lib/libreadline.8.dylib (readline)
  /usr/local/Cellar/ruby@2.4/2.4.5_1/lib/libruby.2.4.5.dylib (ruby@2.4)
Broken dependencies:
  /usr/local/opt/gmp/lib/libgmp.10.dylib (gmp)
Undeclared dependencies with linkage:
  gdbm
```

**Comment by jonchang** [comment]
Thanks. Since building from source fixed this please open a pull request bumping the `revision` of `ruby@2.4`, that should fix the bottle.

**Comment by chriso** [comment]
See https://github.com/Homebrew/homebrew-core/pull/36879
