### ISSUE TITLE
brew install vim --with-client-server fails on macOS 10.14.2

### ISSUE THREAD

**Issue by broesler** [Homebrew/homebrew-core#36610]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I am attempting to install vim with +client-server enabled. I have had this option working before on older macOS versions, via homebrew. When I run `brew install vim --with-client-server`, I get the usage info followed by `Error: invalid option: --with-client-server`.

As a workaround, I changed the `./configure` line in the Formula to use `--with-x` instead of `--without-x`, and ran
```
brew install -s vim
```
to compile from source. Compilation gave an error when looking for X11 headers. Output of `brew gist-logs vim` is in the [Gist here](https://gist.github.com/broesler/6b14b87bcac810545d80c152c11575e9).

I have already reinstalled XQuartz, and it appears the "missing" headers are located in `/opt/X11/include/X11/`, but homebrew is just not finding them. Any help is much appreciated!

**Comment by zbeekman** [comment]
To elaborate a little bit more, X11 support in homebrew-core formulae is deprecated and/or being removed from formulae. If a package builds a fancy X11 or Qt gui, it probably shouldn't be in homebrew-core in most cases.

If a package had an option removed, and there's a compelling case for building the functionality that was provided by the removed option by default (i.e., it won't break other packages, it doesn't surprise users with new/different behavior) then we're open to PRs that change the default configure flags for packages.

As an ignorant Emacs user (*ducks*) I will also note that you can install:

- `vim` (which obviously doesn't currently suite your needs)
- `macvim` which is compiled with `--with-features=huge` so you may have more luck with client-server there
- `neovim`
- `macvim` cask (has GUI etc.) `brew cask install macvim`

Do any of these other packages suit your needs?
