### ISSUE TITLE
bash-completion@2: filename completion not working with tilde and glob

### ISSUE THREAD

**Issue by weibeld** [Homebrew/homebrew-core#36623]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

## What you were trying to do (and why)

If a word includes a tilde (`~`) or a wildcard glob (`*`),  the filename completion when hitting *Tab* does not work. This is only the case if `bash-completion@2` is installed. If it is not installed, completion works as expected. Bash version is 5.0.

The problem doesn't occur with *bash-completion 2.8* on Linux.

## What happened (include command output)

Below, *"Expected"* shows the behaviour if `bash-completion@2` is not installed, and *"What happened"* shows what happens when `bash-completion@2` is installed.

### File completion with tildes

Expected:

~~~bash
$ ls ~/Desk[tab]  # Completes to ~/Desktop
~~~

What happened:

~~~bash
$ ls ~/Desk[tab]  # Nothing happens
~~~

### File completion with globs

Expected:

~~~bash
$ ls *.md[tab]  # Completes to README.md
~~~

See [screencast](https://asciinema.org/a/meTExPCte0n5rfmIJNG8k675M).

What happened:

~~~bash
$ ls *.md[tab]  # Expands to \*.md, hitting [tab] again expands to \\\*.md, and so on
~~~

See [screencast](https://asciinema.org/a/4rZ3qqC30Elq0GHV3sXFDe0vN).

## What you expected to happen

See above.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above.

***

~~~bash
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 1.9.3-107-g1920eec
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 1920eecb7104301647af0bcf548144f2d85f4e27
Last commit: 79 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c5d5fdfdb192eb8c5748bab75206a88f2e6bfe9e
Core tap last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/dw/Library/Logs/Homebrew
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_171, 1.8.0_65
macOS: 10.14.2-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
~~~

**Comment by fxcoudert** [comment]
Hi @weibeld, we are not doing any specific configuration of the `bash-completion@2` formula when we install it, so it sounds like it is an upstream problem, which should be reported here: https://github.com/scop/bash-completion/issues

(Sorry for the long delay in replying to this issue…)
