### ISSUE TITLE
openconnect does not recognize the attempt-reconnect hook

### ISSUE THREAD

**Issue by gzm55** [Homebrew/homebrew-core#36637]
- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): update the vpnc-script in openconnect formula
- What happened (include command output): old vpnc-script does not handle the new hook reason `attempt-reconnect` of the `openconnect 8.0 +`
- What you expected to happen: vpnc-script can handle `attempt-reconnect` hook reason
- Step-by-step reproduction instructions (by running `brew install` commands)
  - brew install openconnect
  - use openconnect to create a vpn tunnel
  - disconnect the pyhsical network then reconnect it

**Comment by fxcoudert** [comment]
It looks like we could update the script with the latest version: http://git.infradead.org/users/dwmw2/vpnc-scripts.git/commitdiff/1000e0f6dd7d6bff163169a46359211c1fc3a6d2

**Comment by fxcoudert** [comment]
Fixed!
