### ISSUE TITLE
clang-format was stuck at 3.9. brew upgrade clang-format didn't bump version

### ISSUE THREAD

**Issue by vlovich** [Homebrew/homebrew-core#36633]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem? N/A
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? N/A
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? N/A

To help us debug your issue please explain:
- What you were trying to do (and why)
Install clang-format recipe.

- What happened (include command output)
Installs really old clang-format 3.9.0

- What you expected to happen
clang-format upstream is already on version 9.0. Seems to build & install fine.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install clang-format

To get latest version need to do brew install clang-format --HEAD (& uninstall first if already installed). Would be nice if latest version was bumped so that brew upgrade would pick it up.

Version info: https://formulae.brew.sh/formula/clang-format

**Comment by vlovich** [comment]
Updating title. After uninstall & reinstall it seems to have finally upgraded to 8.0 so not sure why mine was stuck at such an old version.

**Comment by fxcoudert** [comment]
Hi @vlovich, I am not sure either and it is difficult to guess without the output of `brew doctor` and `brew config`. I'm glad the problem has vanished. In the future, if that happens, running `brew update-reset` can be a solution, it will remove local modifications to the taps, which can often be the source of such issues.
