### ISSUE TITLE
Webpack wrong version?

### ISSUE THREAD

**Issue by panosru** [Homebrew/homebrew-core#36676]
Hello, I'm running `brew install webpack` but when I run `webpack --version` I got wrong version...

![image](https://user-images.githubusercontent.com/400362/52177248-bd08f700-27c6-11e9-9ac3-21b75f0bb4ec.png)

Also, webpack 4.29.0 has been released 14 days ago

Thanks!

## Update
Ah I see the `3.2.1` is related to `webpack-cli`, but how to check the webpack version?

![image](https://user-images.githubusercontent.com/400362/52177322-eece8d80-27c7-11e9-82fe-545a6c4d22b1.png)

**Comment by javian** [comment]
If you look in the Formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/webpack.rb you will see that it uses the webpack-cli resource which is versioned at `3.2.1` at the moment. The update is managed as any other updates by editing the formula and submitting a PR or using `brew bump-formula-pr` command.
