### ISSUE TITLE
icu4c links to libraries with relative path

### ISSUE THREAD

**Issue by MaartenBent** [Homebrew/homebrew-core#36685]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
Created a topic [here](https://discourse.brew.sh/t/boost-with-icu-uses-relative-library-paths/4047/2), suggested to open in issue.
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Use CMake with [fixup_bundle](https://cmake.org/cmake/help/latest/module/BundleUtilities.html) to create a stand-alone package of my application. My application uses `Boost`, which since the last upgrade depends on `icu4c`.
- What happened (include command output)
`Boost` got depended on `icu4c`. 
A failure when collecting the external libraries, because some libraries are linked with a relative path (`@loader_path`).
```
CMake Error at /usr/local/Cellar/cmake/3.13.3/share/cmake/Modules/BundleUtilities.cmake:451 (message):
  otool -l failed: 1

  /Library/Developer/CommandLineTools/usr/bin/objdump:
  '@loader_path/libicudata.63.dylib': No such file or directory
```
- What you expected to happen
The library should have an absolute path so other tools are able to find it.
Or `Boost` should not depend on `icu4c`.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install icu4c
otool -L /usr/local/opt/icu4c/lib/libicui18n.63.dylib

/usr/local/opt/icu4c/lib/libicui18n.63.dylib:
   /usr/local/opt/icu4c/lib/libicui18n.63.dylib (compatibility version 63.0.0, current version 63.1.0)
    @loader_path/libicuuc.63.dylib (compatibility version 63.0.0, current version 63.1.0)
    @loader_path/libicudata.63.dylib (compatibility version 63.0.0, current version 63.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

Notice `@loader_path` in the library paths.

Is there any rationale why `Boost` has `icu4c` enabled by default, while it was previously only an option? If I look [here](https://formulae.brew.sh/formula/boost), only very few people use `Boost` with `icu4c`.

**Comment by sjackman** [comment]
PR https://github.com/Homebrew/brew/pull/5413 that I mentioned previously has not yet been merged.
@woodruffw Are you interested in reviving this PR `mac/keg_relocate: Rewrite rpaths in install names`? If so, would you like to address this issue regarding `@loader_path` while you're at it?

**Comment by woodruffw** [comment]
Yep. I need to re-colocate my Mac Mini for builds, but I should be able to do that this week. Addressing `@loader_path` within that same PR shouldn't be too hard.

**Comment by sjackman** [comment]
Thanks, William!

**Comment by Acionyx** [comment]
Hello, any updates on this issue? I'm waiting for fix too

**Comment by sjackman** [comment]
Hi, Vladislav. I haven't yet fully understood the problem. `@loader_path` should work if it's set correctly. Can you please elaborate on your particular issue?

**Comment by sjackman** [comment]
In particular, does your issue arise during `brew install` command, and if so, can you please report `brew gist-logs` for the failed formula?

**Comment by Acionyx** [comment]
Yes, of course.
As i understand situation, I'm not experiencing issue with brew itself, but with one library which is installed via brew. I got exactly same error as described in this issue. I hope you can steer me into right way to solve this problem.
I have a repo which will help you to reproduce this bug quickly. I'm running its build on macOS with latest packages installed (icu4c 63.1). 
Here is a link (https://github.com/colobot/colobot/) and here is manual for macOS (https://github.com/colobot/colobot/blob/master/INSTALL-MacOSX.md).
Actually you can try to clone and build it, it takes 5-10 minutes.
I getting an error at 'make package' step exactly like in this issue:
```
Run CPack packaging tool...
CPack: Create package using Bundle
CPack: Install projects
CPack: - Run preinstall target for: colobot
CPack: - Install project: colobot
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/BundleUtilities.cmake:451 (message):
  otool -l failed: 1

  /Library/Developer/CommandLineTools/usr/bin/objdump:
  '@loader_path/libicudata.63.dylib': No such file or directory

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/BundleUtilities.cmake:520 (get_item_rpaths)
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/BundleUtilities.cmake:658 (set_bundle_key_values)
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/BundleUtilities.cmake:934 (get_bundle_keys)
  /Users/vladislavbogomaz/Documents/projects/colobot/build/desktop/cmake_install.cmake:39 (fixup_bundle)
  /Users/vladislavbogomaz/Documents/projects/colobot/build/cmake_install.cmake:40 (include)


CPack Error: Error when generating package: colobot
make: *** [package] Error 1
```


I'm not familiar with building CPP code, so i cannot define myself is it a bug in project, or it is a bug with brew/icu4c/boost/etc. But what i definitely know - 1 year ago i built this project successfully on macOS too.

**Comment by sjackman** [comment]
It may be a bug in `cmake` rather than Homebrew.
What does `brew linkage boost` and `grep -rl libicudata.63.dylib $(brew --prefix boost)/lib` report on your system?

**Comment by Acionyx** [comment]
```
> brew linkage boost
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/icu4c/lib/libicudata.63.1.dylib (icu4c)
  /usr/local/opt/icu4c/lib/libicui18n.63.dylib (icu4c)
  /usr/local/opt/icu4c/lib/libicuuc.63.dylib (icu4c)
Variable-referenced libraries:
  @loader_path/libboost_atomic-mt.dylib
  @loader_path/libboost_chrono-mt.dylib
  @loader_path/libboost_chrono.dylib
  @loader_path/libboost_context-mt.dylib
  @loader_path/libboost_date_time-mt.dylib
  @loader_path/libboost_date_time.dylib
  @loader_path/libboost_filesystem-mt.dylib
  @loader_path/libboost_filesystem.dylib
  @loader_path/libboost_log-mt.dylib
  @loader_path/libboost_log.dylib
  @loader_path/libboost_regex-mt.dylib
  @loader_path/libboost_regex.dylib
  @loader_path/libboost_serialization-mt.dylib
  @loader_path/libboost_serialization.dylib
  @loader_path/libboost_system-mt.dylib
  @loader_path/libboost_system.dylib
  @loader_path/libboost_thread-mt.dylib
  @loader_path/libboost_timer-mt.dylib
  @loader_path/libboost_timer.dylib
```

```
> grep -rl libicudata.63.dylib $(brew --prefix boost)/lib
```

Last command returns nothing.

**Comment by sjackman** [comment]
Please report the output of `brew linkage --reverse boost`. If it's really long, you could post it in a gist, or copy-and-paste just the part that references `libicudata.63.1.dylib`

**Comment by Acionyx** [comment]
Here it is: https://gist.github.com/Acionyx/1b59dab2c05574116425143dd6b55336

**Comment by sjackman** [comment]
Thanks. It seems it's the `icu4c` package that uses `@loader_path` (not Boost).
```
❯❯❯ brew linkage icu4c
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/Cellar/icu4c/63.1/lib/../lib/libicudata.63.1.dylib (icu4c)
  /usr/local/Cellar/icu4c/63.1/lib/libicudata.63.dylib (icu4c)
  /usr/local/Cellar/icu4c/63.1/lib/libicui18n.63.dylib (icu4c)
  /usr/local/Cellar/icu4c/63.1/lib/libicuio.63.dylib (icu4c)
  /usr/local/Cellar/icu4c/63.1/lib/libicutu.63.dylib (icu4c)
  /usr/local/Cellar/icu4c/63.1/lib/libicuuc.63.dylib (icu4c)
Variable-referenced libraries:
  @loader_path/libicudata.63.dylib
  @loader_path/libicui18n.63.dylib
  @loader_path/libicutu.63.dylib
  @loader_path/libicuuc.63.dylib
```

These files all exist, so it seems to me like a bug in `cmake`. For example:
```
❯❯❯ otool -L ~/.homebrew/opt/icu4c/lib/libicui18n.63.1.dylib | grep @loader_path
	@loader_path/libicuuc.63.dylib (compatibility version 63.0.0, current version 63.1.0)
	@loader_path/libicudata.63.dylib (compatibility version 63.0.0, current version 63.1.0)
```

**Comment by sjackman** [comment]
I suggest reporting this issue to the `cmake` developers. If you do, please post the URL of that issue here, so that we can follow the conversation.

**Comment by Acionyx** [comment]
Here is a link: https://gitlab.kitware.com/cmake/cmake/issues/19035

Thank you, Shaun!
