### ISSUE TITLE
Brew valgrind not working osx mojave

### ISSUE THREAD

**Issue by x4vi99** [Homebrew/homebrew-core#36683]
I'm trying to install valgrind with brew in OSX Mojave, and I get the following error:  

valgrind: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/valgrind.rb:1: syntax error, unexpected tCONSTANT, expecting end-of-input
git://sourceware.org/git/valgrind.gitclass Valgrind < Formula

I searched on the internet and modified the source webpage of valgrind homebrew because they said it may solve it. But still getting errors. Please someone help.

**Comment by SMillerDev** [comment]
Could you please fill out the issue template? It's really essential in trying to debug issues. This can be reopened once the required information has been provided.

**Comment by o4dev** [comment]
I experienced this issue as well. Currently, Valgrind requires a few patches for Mojave.
I made a tap which uses these: https://github.com/o4dev/homebrew-valgrind-mojave

**Comment by x4vi99** [comment]
Thank you!

--
Xavi Amat García
/Bachelor Student/

Computer science engineering
Information&Communication Technology

[M.] +34 671 190 146 
xavi.amat.99@gmail.com
xavier.amat01@estudiant.upf.edu





This message is exclusively addressed to the recipient and may contain private or confidential information. If you have received it by mistake, let us know and destroy it. Keep in mind that you are not allowed to use it.

Before printing this message, think about the environment.

Aquest missatge s'adreça exclusivament a la persona destinatària i pot contenir informació privada o confidencial. Si l'heu rebut per error comoniqueu-nos-ho i destruïu-lo, i tingueu present que no teniu autorització per fer-ne cap ús. 

Abans d'imprimir aquest missatge penseu en el medi ambient.

Este mensaje está dirigido exclusivamente al destinatario y puede contener información privada o confidencial. Si lo ha recibido por error háganoslo saber y destruyalo, y tenga en cuenta que no tiene autorización para usarlo.

Antes de imprimir este mensaje piense en el medio ambiente.
