### ISSUE TITLE
brew cleanup fails due to clang build version < 600

### ISSUE THREAD

**Issue by menicosia** [Homebrew/homebrew-core#36709]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

    I think `brew cleanup` is called after many routine commands: `==> `brew cleanup` has not been run in 30 days, running now...`

- What happened (include command output)

    ```
    → brew cleanup -vn
    Error: Calling 'fails_with :clang' with 'build' < 600 is disabled! There is no replacement.
    Please report this to the homebrew/core tap:
      /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:38
    ```

- What you expected to happen

    No errors. :)

- Step-by-step reproduction instructions (by running `brew install` commands)

    I don't think I can provide this, but I did run `brew doctor` and got the following output:

    ```
    → brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry or file an issue; just ignore this. Thanks!

    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
      /usr/local/lib/libnnz11.dylib
      /usr/local/lib/libociei.dylib
      /usr/local/lib/libocijdbc11.dylib
      /usr/local/lib/libyaml-0.2.dylib

    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected header files:
      /usr/local/include/yaml.h

    Warning: Unbrewed .la files were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected .la files:
      /usr/local/lib/libyaml.la

    Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected .pc files:
      /usr/local/lib/pkgconfig/yaml-0.1.pc

    Warning: Unbrewed static libraries were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected static libraries:
      /usr/local/lib/libyaml.a

    Warning: Broken symlinks were found. Remove them with `brew cleanup`:
      /usr/local/bin/apm
      /usr/local/bin/atom
      /usr/local/bin/blueutil
      /usr/local/bin/docker
      /usr/local/bin/docker-compose.backup
      /usr/local/bin/docker-credential-osxkeychain.backup
      /usr/local/bin/docker-machine
      /usr/local/bin/hyperkit
      /usr/local/bin/mocha
      /usr/local/bin/notary
      /usr/local/bin/ovftool
      /usr/local/bin/vagrant
      /usr/local/bin/vim-update
      /usr/local/bin/vmnet-cfgcli
      /usr/local/bin/vmnet-cli
      /usr/local/bin/vmware-vdiskmanager
      /usr/local/bin/vpnkit.backup
    Error: Calling 'fails_with :clang' with 'build' < 600 is disabled! There is no replacement.
    Please report this to the homebrew/core tap:
      /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:38
    ```

**Comment by fxcoudert** [comment]
Hi @menicosia, sorry for the long delay in replying to this. It is hard to diagnose without having the output of `brew config`, as requested in the issue template, but… it appears you have local modifications of your `homebrew-core` tap, because the latest version of the `python` formula does not have such a problem.

So, please run `brew update-reset` to remove all local modifications to the taps, then `brew up` again. This should fix the issues!
