### ISSUE TITLE
imagemagick 7.0.8-25 not installing --with-openexr

### ISSUE THREAD

**Issue by fsiddi** [Homebrew/homebrew-core#36748]
When trying to:

```
brew install imagemagick --with-openexr
```

I get the message:

```
Error: invalid option: --with-openexr
```

By looking [at the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/imagemagick.rb) it looks like the option was removed. I browsed the history of the formula but could not find the commit where that happened.

Is there any other way to install imagemagick with OpenEXR via brew? By looking a the [formula page](https://formulae.brew.sh/formula/imagemagick) it looks like a few people are installing --with-openexr.

**Comment by slhck** [comment]
Two options:

- You or someone else can create a tap that adds back this option.
- The dependency on `openexr` is added as a default – you could create a PR for that.

In the long term I think there should be a tap containing multimedia-related formulae with their options added back (including `ffmpeg`, `imagemagick` and others). Currently thinking about how to best do this without fragmenting the whole ecosystem.

**Comment by fsiddi** [comment]
Thanks for the quick reaction. Could you confirm that adding `openexr` back as a default would be as simple as this?

```
diff --git a/Formula/imagemagick.rb b/Formula/imagemagick.rb
index b2df6c247..6fa3bd415 100644
--- a/Formula/imagemagick.rb
+++ b/Formula/imagemagick.rb
@@ -24,6 +24,7 @@ class Imagemagick < Formula
   depends_on "libtiff"
   depends_on "libtool"
   depends_on "little-cms2"
+  depends_on "openexr"
   depends_on "openjpeg"
   depends_on "webp"
   depends_on "xz"
@@ -43,6 +44,7 @@ class Imagemagick < Formula
       --with-modules
       --with-openjp2
       --with-webp=yes
+      --with-openexr
       --without-gslib
       --with-gs-font-dir=#{HOMEBREW_PREFIX}/share/ghostscript/fonts
       --without-fftw
```

Do you have any insights in why this option was removed in the first place?

**Comment by slhck** [comment]
See https://github.com/Homebrew/homebrew-core/issues/31510

The patch seems correct, feel free to provide a PR and the maintainers will look at it.

**Comment by DavidCWGA** [comment]
Related issue: imagemagick has lost support for HEIF/HEIC. This used to be a build time option before build time options were removed. Can it be added to the default config?

I can't create a new issue for this because it requires me to jump through "gist-logs" hoops, but that doesn't seem relevant.

**Comment by SMillerDev** [comment]
>Related issue: imagemagick has lost support for HEIF/HEIC. This used to be a build time option before build time options were removed. Can it be added to the default config? ...

@DavidCWGA https://github.com/Homebrew/homebrew-core/issues/36748#issuecomment-460739797 also applies here

**Comment by fxcoudert** [comment]
It is now part of the default configuration.
