### ISSUE TITLE
Feature suggestion: Disavow support for --HEAD and allow "HEAD-only" options.

### ISSUE THREAD

**Issue by mlindner** [Homebrew/homebrew-core#36763]
Currently with the recent changes made, all custom options have been removed causing a lot of hardship for longtime homebrew users. The reason given is that these options apparently cause high support burdens on the core maintainers of homebrew itself.

As an alternate solution, can we add an option to basically bypass homebrew entirely with a warning that use of such option means that homebrew disavows any support or warranty for such option. This flag would either be pre-defined options like was previously allowed (but would only function on --HEAD or some other experimental flag) or would be flag that would allow passing of options directly to the configure script that homebrew calls, bypassing other homebrew options. I think this would cover most uses for people. This would allow a way to opt-out of homebrew's control temporarily for specific packages that special options are needed. (Especially as apparently homebrew's new policy is to block any non-free software which is again a new policy.)

**Comment by SMillerDev** [comment]
If only people would actually read those warnings and not just blindly copy paste commands from blog posts this might actually be a solution. 

This is a request that should be in Homebrew/brew though, and even there feature requests are only accepted as pull requests.

**Comment by billylindeman** [comment]
@SMillerDev Good to know you're actively hostile towards users of homebrew.  The removal of options _HAS_ caused quite a headache.  Just look at the number of issues due to that change flowing into this project...

I can't believe such a change was ramrodded through without regard for the number of developers that depend on brew to manage their environment.

**Comment by SMillerDev** [comment]
Just the fact that you're responding to a month old thread is a good indication as to why homebrew can't both be actively developing at any given time and consult users for every change. Except the people who are actively working on making homebrew better it just takes ages to consult the homebrew users. 

A lot of the maintainers are actually developers by the way and they seem to be fine with managing their environment. And if you want to have a bigger say in the way homebrew does things, just contribute.

**Comment by mlindner** [comment]
@SMillerDev The maintainers are of course going to be the ones most familiar with homebrew. Developing with them as the target user base is not a wise idea. Homebrew is effectively turning itself into a new product entirely unlike what Homebrew was in the past. This is why you're seeing all this resistance. The project has abandoned the idea of what made homebrew great and caused it's rapid adoption and is instead turning it into something like a binary-based package management system like yum or apt-get. It's unfortunate that the project is removing the features that made Homebrew great. Homebrew is dead basically.

**Comment by SMillerDev** [comment]
It's unfortunate that you see it this way, homebrew stil has a lot of users every day who don't seem to mind any of this. I'm a big proponent of using the best tool for the job and if Homebrew isn't that tool for you that's absolutely fine.
I'm personally gonna remain a Homebrew user though, and I know quite some people who feel the same way so it's not completely dead yet 😄 .
