### ISSUE TITLE
Proposal for removing `locate` from findutils gnubin

### ISSUE THREAD

**Issue by glensc** [Homebrew/homebrew-core#36771]
Problem:
1. I don't like macOS find
2. I like macOS locate

So, for the first problem, I've added findutils gnubin to path:
```
==> Caveats
All commands have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
```

But that makes `locate` also prefer the gnu variant. Would such patch be accepted to remove installing `locate` to gnubin, because the system locate already works out of the box and provides background indexing realtime, and the macOS find is just crippled compared to the gnu find i've accustomed to. And there still remains `glocate` to prefer gnu variant.

for example simple find with no arguments works for gnu `find` or `find -type f`, but fails for macOS variant, which is just annoying as it's all in my muscle memory.

```
$ /usr/bin/find -type f
/usr/bin/find: illegal option -- t
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
$ /usr/bin/find
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

**Comment by fxcoudert** [comment]
No, the point of `gnubin` is to make all binaries accessible, even those that shadow system ones. I understand this doesn't match your preferences, but we need to keep these things systematic, or it will not be understandable by all users.

I suggest you remove `gnubin` from your path and use an alias for `find`, or symlink `find` into your `$HOME/bin`.
