### ISSUE TITLE
brew cleanup & doctor failing

### ISSUE THREAD

**Issue by amingilani** [Homebrew/homebrew-core#36802]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I honestly don't know what's up, but here:

```
 ✘ gilani@redbull  ~/Sandbox/payreporter   master ●  brew doctor
Error: Calling 'fails_with :clang' with 'build' < 600 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpfr@2.rb:23

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-core/issues
 ✘ gilani@redbull  ~/Sandbox/payreporter   master ●  brew gist-logs mpfr@2.rb:23
Error: No available formula with the name "mpfr@2.rb:23"
 ✘ gilani@redbull  ~/Sandbox/payreporter   master ●  brew cleanup
Error: Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gringo.rb:21

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-core/issues
 ✘ gilani@redbull  ~/Sandbox/payreporter   master ●  brew gist-logs gringo
Error: Calling needs :cxx11 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gringo.rb:21
```

**Comment by amingilani** [comment]
`brew config`:

```
brew config
HOMEBREW_VERSION: 2.0.1-4-g29fd1d0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 29fd1d05dd46284a7cd2cd33abce47599ca3d8c0
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fbe5f11471748ac696089a00a2c1396945de3cda
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/gilani/Library/Logs/Homebrew
HOMEBREW_VISUAL: nano
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144, 1.8.0_102
macOS: 10.14.3-x86_64
CLT: N/A
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
What does `brew info mpfr@2` say?

**Comment by fxcoudert** [comment]
You local copy of the `homebrew-core` tap has some modifications, that are not compatible with current `brew` version. This is the `mpfr@2` formula, in particular, but there are likely to be others.

Please run `brew update-reset`, then `brew up`, it should fix the issues. If not, feel free to give use additional information below.
