### ISSUE TITLE
MariaDB service doesn't come up after `brew update`

### ISSUE THREAD

**Issue by konung** [Homebrew/homebrew-core#36801]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

###  Steps to Reproduce
0.  Assumes you already have MariaDb installed ( latest version as of this is 10.3.12-MariaDB)
1. `brew update; brew upgrade; brew cleanup; brew doctor`
2. Restart macbook ( usually the issue occurs even without the restart.)
3. MariaDB service doesn't come up automatically
4. Restarting via `brew services restart mariadb` doesn't help.
6. The issue occurs even if MariaDB package is not getting updated. 

### Brew prints this error

```shell

Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted

```

### Known old issue

The issue is old, and a solution to fix it has been reported on this ticket: https://github.com/Homebrew/legacy-homebrew/issues/31760 

### The FIX (temporary)

```shell
mkdir /usr/local/etc/my.cnf.d
```

This works. That is until the next update. It happened 3 times over the past couple of months.  My "solution" is to just alias 

```shell
alias brewski='brew update; brew upgrade; brew cleanup; brew doctor; mkdir /usr/local/etc/my.cnf.d
```

 in `~/.config/fish/config.fish` for now 

Thank you

**Comment by SMillerDev** [comment]
Does this directory get removed every time?

**Comment by konung** [comment]
Yep I tired it today several times and it seems so . Hence my shell alias.

Have a great day!

Nick

**Comment by SMillerDev** [comment]
The formula defines that there's should be a directory created as well. I think this might be a case of excessive cleanup.

**Comment by MikeMcQuaid** [comment]
> 2\. brew update; brew upgrade; brew cleanup; brew doctor

Please narrow this down to a single command and paste the output of that command.

**Comment by konung** [comment]
Looks like `brew cleanup` is the culprit and `brew doctor` doesn't fix it ( I'm not sure it supposed to) 

See screenshot for break down by steps with `mysql -v` command run after each step.
![screen shot 2019-02-08 at 10 03 01 am](https://user-images.githubusercontent.com/72493/52489791-cad4c880-2b88-11e9-9bea-f10d9cfa76c5.png)

**Comment by MikeMcQuaid** [comment]
Can you try to run `brew reinstall mariadb; brew cleanup` and share the output here?

**Comment by konung** [comment]
Just FYI , I have completely removed MariaDB using `brew remove mariadb --force`  && ` brew install mariadb --force` to see if that would fix the issue, and it didn't.

**Comment by konung** [comment]
Just saw your message. :) 
Here is the screenshot running the command as you suggested. 

![screen shot 2019-02-08 at 10 12 02 am](https://user-images.githubusercontent.com/72493/52490291-0328d680-2b8a-11e9-90c8-899418ba33a3.png)

**Comment by MikeMcQuaid** [comment]
I've opened a PR in https://github.com/Homebrew/homebrew-core/pull/36956 to work on this.
