### ISSUE TITLE
bacula-fd doesn't have lzo as requirement

### ISSUE THREAD

**Issue by dmd** [Homebrew/homebrew-core#36826]
The 'bacula-fd' tap needs 'lzo' as a requirement.

**Comment by fxcoudert** [comment]
We would welcome a pull request.

**Comment by dmd** [comment]
At least on Mojave, I found I got:

```
$ /usr/local/opt/bacula-fd/bin/bacula-fd
dyld: Library not loaded: /usr/local/opt/lzo/lib/liblzo2.2.dylib
  Referenced from: /usr/local/opt/bacula-fd/bin/bacula-fd
  Reason: image not found
Abort trap: 6
```

Doing a `brew install lzo` resolved the issue.

**Comment by fxcoudert** [comment]
We need to rebottle then: https://jenkins.brew.sh/job/Homebrew%20Mojave%20Testing/767/

**Comment by fxcoudert** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/commit/429049df496d3b9413cf5b10cb3eafb963e2d2c9
