### ISSUE TITLE
Kibana

### ISSUE THREAD

**Issue by conet** [Homebrew/homebrew-core#36847]
I installed kibana 6.6.0 and got the following error while trying to use it:

<img width="529" alt="screenshot 2019-02-09 at 17 33 11" src="https://user-images.githubusercontent.com/11311763/52522647-cc89b380-2c90-11e9-8f3b-5d46ca213b4c.png">

**Comment by SMillerDev** [comment]
Please fill out the issue template, otherwise it's near impossible to help you. This can be reopened when the required information is present.

**Comment by conet** [comment]
Sorry I followed the open issue from this page: will open another one: https://brewformulas.org/kibana

**Comment by SMillerDev** [comment]
Yeah, that page is not associated with homebrew whats however. You'll have to fill out the issue template according to the homebrew rules if you want homebrew maintainers to help.
