### ISSUE TITLE
kibana formula installs incomplete kibana version 6.6.0

### ISSUE THREAD

**Issue by conet** [Homebrew/homebrew-core#36857]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install kibana and use it.
- What happened (include command output)
Install worked without issues but the installed package is unusable (not all files are present) see this:
<img width="529" alt="screenshot 2019-02-09 at 17 33 11" src="https://user-images.githubusercontent.com/11311763/52526128-cb6e7b80-2cbc-11e9-8574-34ac3691f7f2.png">

- What you expected to happen
Kibana to work as intended
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install kibana
kibana
open http://localhost:5601/

**Comment by conet** [comment]
This is my second try after failing with #36847, I did not check the last two because this is not a case of a failing formula but of a formula that produces an unusable installation. I just tried to be helpful and report this, if I failed to follow the procedure the second time, never mind, just forget it, I won't use homebrew for kinaba.

**Comment by chrmoritz** [comment]
This should be fixed by https://github.com/Homebrew/homebrew-core/pull/36821 which just got merged. Running `brew upgrade` should fix your issue now.

**Comment by conet** [comment]
It's indeed fixed by #36821, thanks.
