### ISSUE TITLE
FFTW3 depends on open-mpi but not mpich

### ISSUE THREAD

**Issue by JBlaschke** [Homebrew/homebrew-core#36871]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Here it is: https://gist.github.com/6b60ca4a616a0d8c0f3b27434f7fc5b0

To help us debug your issue please explain:
- What you were trying to do (and why)

Installing `fftw` from source, so that it builds the `fftw3_mpi` and `fiftw3_omp` libraries (which, by the way are not included in the bottle)

- What happened (include command output)

```
==> Downloading http://fftw.org/fftw-3.3.8.tar.gz
Already downloaded: /Users/johannesblaschke/Library/Caches/Homebrew/downloads/3f5fe7907dd970a931a3957db73eea98df7fdc07b15e587c3a68a5bb30cef684--fftw-3.3.8.tar.gz
==> ./configure --enable-single --enable-shared --prefix=/usr/local/Cellar/fftw/3.3.8 --enable-threads --enable-mpi --enable-openmp --enable-sse2
==> make install
Last 15 lines from /Users/johannesblaschke/Library/Logs/Homebrew/fftw/02.make:
      _after_problem_rcopy_from in mpi_bench-mpi-bench.o
      _after_problem_rcopy_to in mpi_bench-mpi-bench.o
  "_ompi_mpi_int", referenced from:
      _import_wisdom in mpi_bench-mpi-bench.o
  "_ompi_mpi_long", referenced from:
      _mkplan in mpi_bench-mpi-bench.o
  "_ompi_mpi_op_land", referenced from:
      _import_wisdom in mpi_bench-mpi-bench.o
  "_ompi_mpi_op_max", referenced from:
      _bench_cost_postprocess in mpi_bench-mpi-bench.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [mpi-bench] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen

It was supposed to run to completion.

- Step-by-step reproduction instructions (by running `brew install` commands)

Background: for my application, I need `mpich` and _not_ `open-mpi`. As well as `fftw` with mpi enabled (i.e. I need the `fftw3_mpi` library). Therefore, before installing `fftw`, I ran:
```
brew unlink mpich
brew install open-mpi
brew unlink open-mpi
brew link mpich 
```
Then I ran `brew install fftw --build-from-source` which yielded the error above. Note that by swapping out the `depends_on "open-mpi"` line in `Fftw.rb` with `depends_on "mpich"` fixes this problem, but would cause the same kind of problem for other users.

I suggest either creating different versions of the fftw formula... or letting it depend on _either_ mpich or open-mpi.

**Comment by fxcoudert** [comment]
All Homebrew core formulas that depend on MPI need to build with OpenMPI, which is a consistent choice made throughout Homebrew. We cannot support two different MPI implementations, but you can do so by creating and hosting an `fftw-mpich` formula in a personal tap if you wish: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by JBlaschke** [comment]
@fxcoudert Thanks for the info.

In case someone else finds this issue, I've created a tap: https://github.com/JBlaschke/homebrew-mpich-tools containing the MPICH-based formula FFTW

```
brew tap JBlaschke/mpich-tools
brew install fftw-mpich
```

then set linker path to point at `/usr/local/Cellar/fftw-mpich/3.3.8/lib`
