### ISSUE TITLE
neomutt fails to build on 10.14.2 ("Unable to find GPGME", but installed)

### ISSUE THREAD

**Issue by thomergil** [Homebrew/homebrew-core#36887]
Run: `brew install --HEAD neomutt`
Gist: https://gist.github.com/f3039955f5c105b055be71077d8bca4e

```
[...]
Checking for gpgme.h...ok
Checking libs for gpgme_new...-lgpgme
Error: Unable to find GPGME
```

gpgme has been installed:

```
$ brew list | grep gpg
gpgme
libgpg-error
```

**Comment by fxcoudert** [comment]
Build error only happens in HEAD builds, for which we don't offer support. Stable version builds fine: https://jenkins.brew.sh/job/Homebrew%20Testing/1153/
