### ISSUE TITLE
Need to revert PR for InfluxDB 1.7.3

### ISSUE THREAD

**Issue by stevebang** [Homebrew/homebrew-core#36918]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I searched the docs and Google and could not find how to remove a Homebrew formula from availability.  Either the last PR (not submitted by me) needs to be reverted or the formula needs to be disabled.  If you've doc'ed how to do this, point me to the docs.

This is the last PR, which was closed:
https://github.com/Homebrew/homebrew-core/pull/35967

Thanks,
Steve

- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by stevebang** [comment]
InfluxDB 1.7.4 PR has been submitted https://github.com/Homebrew/homebrew-core/pull/36968

**Comment by fxcoudert** [comment]
Not sure what was the problem in the first place, but the formula was updated to 1.74.
