### ISSUE TITLE
Issue on mac, it requested to notify core group.

### ISSUE THREAD

**Issue by RyanKramer** [Homebrew/homebrew-core#36920]
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling MacOS.prefer_64_bit? is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/erlang@20.rb:69

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
