### ISSUE TITLE
When can we expect PHP 7.1.26 in brew?

### ISSUE THREAD

**Issue by br0ther** [Homebrew/homebrew-core#36933]
Latest patch version in brew is 7.1.25 (https://github.com/Homebrew/homebrew-core/blob/master/Formula/php@7.1.rb#L4) now.
But its officially not supported. See: http://php.net/releases/
Latest 7.1.26 has been released month ago (10 Jan 2019 http://php.net/ChangeLog-7.php#7.1.26), but it's still not in the repository.
This brings some inconvenience.
Thanks,
Andrew

**Comment by SMillerDev** [comment]
As soon as a user submits a pull request for it. 

https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula should help you to be the hero that updates PHP 7.1 for everyone who needs it.

**Comment by SMillerDev** [comment]
(since we don't allow feature/update requests I'm gonna close this one though)

**Comment by alebcay** [comment]
@br0ther, for your information, `php@7.1` is now at 7.1.26.
