### ISSUE TITLE
Please incorporate --with-fdk-aac into ffmpeg

### ISSUE THREAD

**Issue by montagne27** [Homebrew/homebrew-core#36938]
Hello,

Your questionnable move to remove all options from Homebrew has left me without access to the "libfdk_aac" encoder for ffmpeg, which is the highest-quality AAC encoder, as [ffmpeg's own documentation](https://trac.ffmpeg.org/wiki/Encode/AAC) says here:

> Fraunhofer FDK AAC (libfdk_aac)
> This is currently the highest-quality AAC encoder available with ffmpeg.

and here:

> For AAC-LC: libfdk_aac > Native FFmpeg AAC encoder (aac).
> For HE-AAC you have one choice: libfdk_aac.

Furthermore, if I look at [the Homebrew analytics for the ffmpeg formula](https://formulae.brew.sh/formula/ffmpeg), "--with-fdk-aac" was easily one of the most commonly used options. Please incorporate "--with-fdk-aac" into ffmpeg.

**Comment by SMillerDev** [comment]
Please make a pull request as we don't accept issues requesting features.

**Comment by montagne27** [comment]
Unfortunately, solutions like "making a pull request" are beyond my expertise. I don't even know what they mean. If I am not a developer, how to I propose the "--with-fdk-aac" option as default?

**Comment by montagne27** [comment]
Browsing the current pull requests, I found [#36327](https://github.com/Homebrew/homebrew-core/pull/36327), in which @MikeMcQuaid says:

> We cannot legally distribute bottles with FDK AAC so we will not do so.

I guess this means that "--with-fdk-aac" will never be default, whatever arguments I make or other users make, such as @zmwangx in the same pull request:

> Please add back `fdk-aac`. AAC is one of the (two) most widely audio codecs and fdk-aac was the de facto standard of AAC encoding with FFmpeg for years

**Comment by retokromer** [comment]
@montagne27 There is a version of old [formula](https://github.com/varenc/homebrew-ffmpeg-with-options) which allows you to pass options.

**Comment by montagne27** [comment]
@retokromer Brilliant! Thank you very much, it worked flowlessly. Now, I just have to hope that "ffmpeg-with-options" will remain compatible with future versions of Homebrew.

**Comment by MikeMcQuaid** [comment]
> I guess this means that "--with-fdk-aac" will never be default, whatever arguments I make or other users make

Yes. Please do this research before opening issues in future and you'll avoid asking the Homebrew project to break the law to meet your needs, thanks.

**Comment by montagne27** [comment]
@MikeMcQuaid I did do research about existing "Issues" with the ffmpeg formula, prior to opening my own one. Only later did I find out the discussion was in "Pull requests" instead of in "Issues". Please keep in mind that I am a visitor and that it's normal if I am not familiar with where everything is. Just like you're unfamiliar the first time you're visiting a hospital or a public library. The problem with forcing people to make "Pull requests" is that you're excluding anyone who is not a developer. Can't someone who has studied humanities instead of software engineering have relevant opinions or raise valid issues about Homebrew? Also, I am not asking you to break the law by providing me the compiled binary: I am asking for the option to compile this binary from source. After all, isn't that Homebrew's purpose? Anyway, opening this "Issue" allowed me to find out about ["ffmpeg-with-options"](https://github.com/varenc/homebrew-ffmpeg-with-options), so I guess it wasn't meaningless for me. Who knows? Some other visitor might also find it meaningful.

**Comment by MikeMcQuaid** [comment]
> After all, isn't that Homebrew's purpose?

No, it's not a from-source package manager.



> Some other visitor might also find it meaningful.

Yes, I hope so too.

Thanks!

**Comment by sidneys** [comment]
> > After all, isn't that Homebrew's purpose?
> 
> No, it's not a from-source package manager.
> 
> > Some other visitor might also find it meaningful.
> 
> Yes, I hope so too.
> 
> Thanks!

Dear @MikeMcQuaid,

with regards to your last comment: Is the removal of Homebrews' `--HEAD` installation feature currently planned / on the roadmap?

Cheers,
S

**Comment by SMillerDev** [comment]
@sidneys that option serves a very different purpose from all options that have now been removed so afaik it isn't on the roadmap to be removed.
