### ISSUE TITLE
confluent-oss 5.1.0: zookeeper log configuration is broken

### ISSUE THREAD

**Issue by misha-tectonic** [Homebrew/homebrew-core#36955]
- Installed `confluent-oss`
- Ran `zookeeper-server-start /usr/local/etc/kafka/zookeeper.propreties`
- Got
```
mkdir: /usr/local/bin/../logs: Permission denied
[0.002s][error][logging] Error opening log file '/usr/local/bin/../logs/zookeeper-gc.log': No such file or directory
[0.002s][error][logging] Initialization of output 'file=/usr/local/bin/../logs/zookeeper-gc.log' using options 'filecount=10,filesize=102400' failed.
Invalid -Xlog option '-Xlog:gc*:file=/usr/local/bin/../logs/zookeeper-gc.log:time,tags:filecount=10,filesize=102400', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I worked around it by explicitly supplying the directory: `LOG_DIR=$HOME/tmp/zookeeper zookeeper-server-start /usr/local/etc/kafka/zookeeper.properties`

Either `kafka-run-class` needs to be modified to not assume log directory relative to itself, or `zookeeper-server-start` needs to pass `LOG_DIR` into `kafka-run-class`.

Gist: https://gist.github.com/misha-tectonic/6096ac2f704eaf4e3fbebda5458d0e08

**Comment by misha-tectonic** [comment]
This is ridiculous.

**Comment by jonchang** [comment]
Please always fill out the issue template:

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

I doubt any of the maintainers use this software; as we are a small volunteer team we rely on the community to identify and fix these kinds of issues as they arise. [Please open a pull request making this change](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request). You'll want to use `write_env_script` or `env_script_all_files` to pass the environment to the commands you're using (check other formulae for examples if you need guidance).
