### ISSUE TITLE
pyenv path setup

### ISSUE THREAD

**Issue by koliyo** [Homebrew/homebrew-core#36952]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Coding python in VS Code after instsalling pyenv via homebrew.
See https://github.com/Microsoft/vscode-python/issues/4377

 
- What happened (include command output)

Pyenv package does not install all libexec binaries, or export an updated `PATH` variable

This only works if i modify my PATH explicitly (this is what VS Code python extension executes)
```
$ bash /usr/local/Cellar/pyenv/1.2.9/libexec/pyenv-which python3.5
/usr/local/Cellar/pyenv/1.2.9/libexec/pyenv-which: line 38: pyenv-version-name: command not found
```

- What you expected to happen

Configure paths

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install pyenv`

**Comment by SMillerDev** [comment]
Homebrew never changes environment variables.

**Comment by koliyo** [comment]
Ok, fair enough, but maybe as part of `brew link` ?
```
$ brew link -n pyenv   
Would link:
/usr/local/bin/pyenv
/usr/local/bin/pyenv-install
/usr/local/bin/pyenv-uninstall
/usr/local/bin/python-build
```

Honestly, I do not care that much, I would always use the main `pyenv` executable instead of the specific ones like `pyenv-which`, ie instead use`pyenv which`.

All I want is for my VS Code environment to work properly. I just wanted to address the problem here as well, in case the VC Code people want some input on the homebrew pyenv setup.
