### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [Homebrew/homebrew-core#36976]
<img width="572" alt="2019-02-14 7 03 00" src="https://user-images.githubusercontent.com/16648917/52782939-42c05880-308b-11e9-8a5d-c0041cc93af2.png">
How to resolve the  problem?

**Comment by SMillerDev** [comment]
Not the right place to file this issue and missing a lot of information but from the screenshot I can tell your internet connection isn't working. There's nothing we can do to help there either.

**Comment by zhuiyizhiqiu** [comment]
Maybe I need VPN?

**Comment by SMillerDev** [comment]
Could be, I can't really help you debug network issues.
