### ISSUE TITLE
nasm broken

### ISSUE THREAD

**Issue by szha** [Homebrew/homebrew-core#36972]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install nasm`
- What happened (include command output)
```
==> Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.xz
curl: (7) Failed to connect to www.nasm.us port 443: Connection refused
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "nasm"
Download failed: https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/nasm-2.14.02.tar.xz
```
- What you expected to happen
I expect nasm to be successfully installed
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew update; brew install nasm`

**Comment by szha** [comment]
This link is currently broken. https://github.com/Homebrew/homebrew-core/blob/master/Formula/nasm.rb#L4

**Comment by szha** [comment]
This tag is available: https://repo.or.cz/nasm.git/commit/74246c499ea4313fb8837977dc0c135fc50567c0

**Comment by SMillerDev** [comment]
This should be reported to upstream. Homebrew can't really help with upstream releases being broken. You should really be able to use the bottles homebrew provides though.

**Comment by szha** [comment]
@SMillerDev the release is not broken. The mirror is. It was my understanding that this repo decides which mirror to use for a formula. If that's incorrect, I'm happy to report this upstream as suggested.

**Comment by SMillerDev** [comment]
This isn't a mirror though, it's the official website for the project.

**Comment by szha** [comment]
Link is working now.
