### ISSUE TITLE
Switch recently added man-db to keg only; not GNU, muscle-memory

### ISSUE THREAD

**Issue by RalphCorderoy** [Homebrew/homebrew-core#36981]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

A formula for _man-db_ was recently added by @maxim-belkin. It configures a prefix `g` so the resulting `gman`, etc., don't clash with the system's. I think it would be better for the formula to drop the prefix and to be _keg only_ so the user then has a choice how to access the command. _man-db_ is not a GNU project, the normal meaning of the `g` prefix, and man(1) is such a common command that muscle-memory types `man ls` and doesn't want re-training when non-Homebrew systems are still being used. Because `man groff' will use the old, crufty, system man the user might take a while to notice issues, realise the problem, and have to re-start with `gman groff'. I think most would prefer to make the explicit choice after brewing man-db to make its `man` their default.

AIUI, once keg only, after `brew install man-db` the user is prompted with the edits to make to their profile to add the new executables' directory to their PATH. They could also choose another avenue, like symlinking into ~/bin, or a bash alias, etc.

I'm not a Mac/Homebrew user so sorry if I have some of the terminology wrong. I've an interest in man-db, and the underlying man-page formatter. This issue resulted from a private email discussion involving Maxim, among others.

**Comment by jonchang** [comment]
`brew info man-db` says:

```
==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "bin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/man-db/libexec/bin:$PATH"
```

So you can add this to your PATH variable if you'd like to use `man-db` by default.

**Comment by RalphCorderoy** [comment]
Thanks @jonchang. Is something similar shown on installation?
It doesn't cover the `g` prefix being used for a non-GNU package. Is the `g` prefix commonly used by other formulas, and are any of them non-GNU too?

The discussion on the original https://github.com/Homebrew/homebrew-core/pull/36469 started with keg-only being the way to do it, and only deviated after objections from the PR's author. `g` was one solution grasped. I think the original idea was a better fit.

**Comment by maxim-belkin** [comment]
The above "caveats" message does show up upon installation, so careful people should know what to do. I [strongly agree](https://github.com/Homebrew/homebrew-core/pull/36769#pullrequestreview-200776904) that `g` prefix in this situation is at odd and inconsistent but is what is used in other  formulae. I don't know if any other non-gnu formula uses `g` prefix. I [suggested](https://github.com/Homebrew/homebrew-core/pull/36629#issuecomment-460010927) a few alternatives but ... you know, no one other than myself expressed this concern and we had to reach a consensus within a reasonable amount of time.
