### ISSUE TITLE
Installing llvm --with-lldb; error unknown option

### ISSUE THREAD

**Issue by rrahn** [Homebrew/homebrew-core#36992]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Trying to install llvm with --with-lldb --python options enabled.

- What happened (include command output)
```
Error: invalid option: --with-lldb
```
and depending on what to put first
```
Error: invalid option: --with-python
```
It also failed with either one of them.

- What you expected to happen

Install llvm with lldb

- Step-by-step reproduction instructions (by running `brew install` commands)

```
 brew install --with-lldb --with-python llvm
```

Brew config
```console
~/D/s/s/u/a/p/policy $ brew config
HOMEBREW_VERSION: 2.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: e32c1515432a938093d5ef1d8c4b4408991873df
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fbe06926a0c0ce934741a600fd2f3375e2156140
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/rmaerker/Library/Logs/Homebrew
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202, 1.8.0_192, 1.8.0_181, 1.8.0_172, 1.8.0_162, 1.8.0_152, 1.8.0_144, 1.8.0_141, 1.8.0_131, 1.8.0_121
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```
brew doctor
```
~/D/s/s/u/a/p/policy $ brew doctor
Your system is ready to brew.
```
Note, before updating to mojave (sierra) and Xcode this worked for me. 
I did a fresh reinstall of homebrew and it didn't change. All reported issues on llvm describe some compiler error, but here the options are not known, so I am confused about what I am doing wrong.
Thanks for your help.

**Comment by javian** [comment]
The options have been removed so it will no longer work - see #31510 for more information.

**Comment by rrahn** [comment]
Ok thanks for the clarification.
