### ISSUE TITLE
Don't install node when there is nvm?

### ISSUE THREAD

**Issue by dj-hedgehog** [Homebrew/homebrew-core#3700]
I manage my installed node versions with `nvm`.
When I install a formula like [jsdoc3](https://github.com/Homebrew/homebrew-core/blob/master/Formula/jsdoc3.rb) which `depends_on "node"` it will install node again and probably override my current Node.

Is there a recommended procedure how to act in such cases?
I will soon make a PR for my first formula. I'm interested to make it depend on node but not install it when there is already a node binary.

**Comment by MikeMcQuaid** [comment]
> and probably override my current Node.

It will not override your current node as long as you put `$(which nvm)` before `/usr/local/bin` in your `$PATH`.



> I will soon make a PR for my first formula. I'm interested to make it depend on node but not install it when there is already a node binary.

For things we have depending on node: we need a `depends_on "node"`.

**Comment by dj-hedgehog** [comment]
Alright, thank for clearing that up.
