### ISSUE TITLE
can't find php@5.6 on Mac

### ISSUE THREAD

**Issue by killua0083** [Homebrew/homebrew-core#37019]
I search the php formula using : `brew search php`
there just php@7.1  php@7.2   php and so on, I find some tap and was told it is out of date, please tell me how to install php@5.6 via brew.
Thank you.

**Comment by jonchang** [comment]
Please always fill out the issue template. PHP 5.6 has been end-of-lifed by upstream so Homebrew will no longer package it.

**Comment by matejsvajger** [comment]
@jonchang How about supporting the legacy projects? 

I'm having a hard time understanding this decision when there is still more than half of the php powered websites on v5.6 out there.

**Comment by SMillerDev** [comment]
You'll have to take this up with PHP upstream. Homebrew policy is simply not to package something without support from upstream. If you want to keep using insecure unsupported versions that's entirely up to you but homebrew won't help you do it.
