### ISSUE TITLE
brew install imagemagick: invalid option: --with-librsvg

### ISSUE THREAD

**Issue by davethegr8** [Homebrew/homebrew-core#37037]
It seems homebrew no longer supports installing librsvg as part of https://github.com/Homebrew/homebrew-core/pull/36079

Can I please suggest this option (or librsvg support) be restored? Imagemagick's support of svg is rather poor, and there is years of stackoverflow/forum posts that suggest installing with this flag. Dropping this support breaks imagemagick's support of svg, which will cause people to seek workarounds or other installation methods, ultimately reducing the usefulness of homebrew. 

This change landed a couple of weeks ago, and as people begin to upgrade they will find their workflows are broken and their images are no longer converting, leading down the same time-consuming hole I just dug through.

Thanks.

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by iMichka** [comment]
This is a bug tracker, and the issue template needs to be filled out. The template suggests that you should discuss that kind of topic on https://discourse.brew.sh
