### ISSUE TITLE
invalid attribute for formula 'lime': version ("") commandeering brew

### ISSUE THREAD

**Issue by lschumm** [Homebrew/homebrew-core#37053]
I've been trying to write a formula for a `pip` package I've been working on called `lime`, in order to make it available through `brew`. I wrote the following formula:

```
class Lime < Formula
  include Language::Python::Virtualenv
  
  version "1.0.2"

  desc "Lime is an experimental, stack-based, purely functional programming language."
  homepage "https://limelang.xyz"
  url "https://gitlab.com/lschumm/lime/-/archive/1.0.2/lime-1.0.2.tar.gz"
  sha256 "a3724027515402a0aa2400a7b30b6469ffc47d53e087f9aa8ccaa4ad7733ea20"
  head "https://gitlab.com/lschumm/lime"
  
  def install
    virtualenv_install_with_resources
  end
end
```

However, whenever I try to `brew install` this package from my tap ([lschumm/homebrew-tap](https://github.com/lschumm/homebrew-tap)), it gives me the following error:

```
Error: invalid attribute for formula 'lime': version ("")
```

I have tried various positions of the `version` statement, and have also tried removing it completely from the file–all which return the same error.

# Debugging Info
[brew config](https://gist.github.com/lschumm/6f3a26409f32761d8c3790df46501c64)
[brew doctor](https://gist.github.com/lschumm/8938d3a810b7b5939e0247cd7b9dd0ab)

**Comment by fxcoudert** [comment]
I cannot reproduce this, if I install your formula in a local tap it works fine for me. I mean, it can't install because the URL is 404, but it does not show the error you have.

Try removing `version`, since it should be autodetected from the URL.

**Comment by lschumm** [comment]
oh whoops, i guess i forgot to `git push --tags` for `1.0.2`.

after completely removing and reinstalling `brew`, installing the package works. however, in no other way was i able to get rid of the faulty package–should this be the case?

**Comment by fxcoudert** [comment]
If a formula is invalid, yes it can make brew crash. That's why we work very hard at testing all formulas in Homebrew core! :)

**Comment by lschumm** [comment]
@fxcoudert i still think it's not really ideal to have a faulty formula corrupt the entire system, whether the user's fault or not. neither `brew uninstall` nor `brew doctor` could help in this situation–both threw the same error.

**Comment by SMillerDev** [comment]
It's not ideal that users can change something that breaks but such are the problems of configuration files (which formulae are broadly). If you have a suggestion on how to handle invalid formulae better, please file a pull request to Homebrew/brew with the solution. I'd love to review that for everyone's benefit.
