### ISSUE TITLE
rgbds: source code bundle sha256 hash has changed due to re-tag of v0.3.8

### ISSUE THREAD

**Issue by mattcurrie** [Homebrew/homebrew-core#37115]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
Your system is ready to brew.
```
```
HOMEBREW_VERSION: 2.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 117c24f4b6294e037431d3a850ced6955d53e26f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1d69808199f49539eeca54e9b48bada210bde2dc
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.NpGg4e8LTM/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/matt/Library/Logs/Homebrew
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 9.2
XQuartz: 2.7.11 => /opt/X11

```
To help us debug your issue please explain:
- What you were trying to do (and why)

Installing rgbds from source fails because the source code bundle's sha256 hash has changed due to a re-tag of v0.3.8

- What happened (include command output)

```
==> Downloading https://github.com/rednex/rgbds/archive/v0.3.8.tar.gz
==> Downloading from https://codeload.github.com/rednex/rgbds/tar.gz/v0.3.8
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: fbf983cff2246b5169a66a61c182c3dd2b8d484bd683c5af94ede74ad983cc1f
Actual: 264f5e98ccdccb51b05dac80d9d37ddae769863c97f726b87be692edd5612256
Archive: /Users/matt/Library/Caches/Homebrew/downloads/3bd63d01050176226d1cf184bfda45ed4478ad7c85cf8dcf7941d642b3cdb0b1--rgbds-0.3.8.tar.gz
To retry an incomplete download, remove the file above.
```

- What you expected to happen

Successful install from source.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install --build-from-source rgbds
```

---

I've updated the formula with a revision and new sha256. PR: https://github.com/Homebrew/homebrew-core/pull/37113

The formula in the PR currently fails the strict audit with the following output:

```
brew audit --strict rgbds
rgbds:
  * stable: sha256 changed without the version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.
Error: 1 problem in 1 formula detected
```

Reason for sha256 sum change: https://github.com/rednex/rgbds/pull/325

**Comment by fxcoudert** [comment]
Fixed, thanks for reporting.
