### ISSUE TITLE
brew install fails due to dependencies

### ISSUE THREAD

**Issue by thanedar** [Homebrew/homebrew-core#3711]
I was trying to install hhvm on El Capitan after adding the tap and it failed due to missing cmake while installing llvm as the first dependency; but cmake is listed as a dependency later in the list of dependencies.

> ==> Installing dependencies for hhvm/hhvm/hhvm: llvm, automake, cmake, dwarfutils, gmp, mpfr, gawk, libelf, libtool, md5sha1sum, ocaml, ocamlbuild, pkg-config, homebrew/versions/boost160, freetype, fontconfig, libtiff, webp, gd, gettext, gflags, glog, icu4c, imagemagick, jemalloc, libevent, memcached, libmemcached, libzip, lz4, mhash, mcrypt, pcre, tbbz

Not sure if related but I found these two similar issues on the legacy repository
[#22245](https://github.com/Homebrew/legacy-homebrew/issues/22245) and [#24324](https://github.com/Homebrew/legacy-homebrew/issues/24324) 

Log for `brew install hhvm -dv` is attached
[brew error at 2016-08-08 12.24.23.txt](https://github.com/Homebrew/homebrew-core/files/407264/brew.error.at.2016-08-08.12.24.23.txt)

`brew gist-logs hhvm`
ERROR: No logs.

**Comment by ilovezfs** [comment]
What's the output of `brew info cmake`?

**Comment by thanedar** [comment]
At that point, I definitely did not have cmake installed locally and to get around the issue, I first did 
`brew install cmake` 
then repeated 
`brew install hhvm`
and this time it ran successfully.

In case it helps, the output now is given below:

> sudhanshu@Sudhanshus-MacBook-Pro:~$ brew info cmake
cmake: stable 3.6.1 (bottled), HEAD
Cross-platform make
https://www.cmake.org/
/usr/local/Cellar/cmake/3.6.1 (2,028 files, 27.8M) *
  Poured from bottle on 2016-08-08 at 12:23:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cmake.rb
==> Dependencies
Build: sphinx-doc ✘
==> Options
--with-completion
	Install Bash completion (Has potential problems with system bash)
--without-docs
	Don't build man pages
--HEAD
	Install HEAD version
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by ilovezfs** [comment]
One thing I noticed, which may or may not be relevant, is that the formula is outdated with

https://github.com/hhvm/homebrew-hhvm/blob/master/hhvm.rb#L21
```
depends_on "llvm" => [:build, "with-clang", "with-libcxx"]
```
clang is now always on, and libcxx defaults on, with the option being `--without-libcxx` to disable it, so
```
depends_on "llvm" => :build
```
should be all that's needed, in which case it should just pour the bottle.

**Comment by thanedar** [comment]
I wanted to install hhvm on Mac so I followed [these steps](https://github.com/hhvm/homebrew-hhvm#installation)
`brew tap hhvm/hhvm`
`brew install hhvm`

For hhvm dependencies were as listed above, note first dependency listed is llvm and third is cmake

My system did not have cmake already installed on it before trying the hhvm install.

brew install for llvm also depends on cmake and failed with error that cmake was not installed though cmake was to be installed in the subsequent steps. 

With the note by @ilovezfs, I am not sure if this issue needs to be on homebrew side or the hhvm formula side since changing the order of dependencies (to have first cmake and then the rest) because installing cmake first and then installing hhvm fixed the error for me.

Hope this helps, please let me know if you need any other info that may help.

**Comment by ilovezfs** [comment]
Yup,
```
iMac-TMP:local joe$ brew uninstall -f llvm cmake
Uninstalling llvm... (1,815 files, 612.6M)
Uninstalling cmake... (2,028 files, 27.8M)
iMac-TMP:local joe$ brew install hhvm
==> Installing hhvm from hhvm/hhvm
==> Installing dependencies for hhvm/hhvm/hhvm: llvm, cmake, dwarfutils, libelf, imagemagick, 
==> Installing hhvm/hhvm/hhvm dependency: llvm
Error: /usr/local/opt/cmake not present or broken
Please reinstall cmake. Sorry :(
```

**Comment by ilovezfs** [comment]
The immediate problem is that their formula needs to be updated:
```
depends_on "llvm" => :build
```

The larger homebrew/problem is that it's getting confused because the option set matches the default, which one could argue is a formula bug not a brew bug, but is a point where we could be more robust.

So for example, if you change it to
```
depends_on "llvm" => [:build,  "without-libcxx"]
```
(which uses a real, non-default option), then the problem goes away. Of course in this case you want `with-libcxx`, which is why they need to update their formula to say
```
depends_on "llvm" => :build
```
which is a win for everyone since then it can use the bottle, whereas previously it couldn't.

**Comment by MikeMcQuaid** [comment]
Please report this to their tap, thanks!

**Comment by ilovezfs** [comment]
Interestingly this same problem just came up again here:
https://bot.brew.sh/job/Homebrew%20Science%20Pull%20Requests/5477/version=yosemite/console

also with a somewhat surprising symptom:
```
==> Installing homebrew/science/pocl dependency: llvm
==> Using the sandbox
Error: /usr/local/opt/xz not present or broken
Please reinstall xz. Sorry :(
```
