### ISSUE TITLE
brew install geoipupdate raise error

### ISSUE THREAD

**Issue by RidingRoad** [Homebrew/homebrew-core#37116]
brew install geoipupdate
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/bottles/ge
######################################################################## 100.0%
==> Pouring geoipupdate-3.1.1.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/geoipupdate/3.1.1/bin/geoipupdate -v
🍺  /usr/local/Cellar/geoipupdate/3.1.1: 13 files, 97.2KB
==> `brew cleanup` has not been run in 30 days, running now...
Error: Calling 'fails_with :clang' with 'build' < 600 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/postgresql.rb:39

**Comment by SMillerDev** [comment]
Please fill out the issue template, without it it's almost impossible to debug your issue. I'm closing this until the required information is provided.

**Comment by RidingRoad** [comment]
try it again and it's ok.
