### ISSUE TITLE
Linker error with PHP@7.2 and enabled ZTS

### ISSUE THREAD

**Issue by thgutmann** [Homebrew/homebrew-core#37141]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [yes ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ yes] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ yes] ran `brew update` and can still reproduce the problem?
- [ yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Hi
I tried to install php@7.2 from source with the --enable-maintainer-zts flag enabled. I enabled this using brew edit php@7.2

Command: brew install --build-from-source php@7.2

The linker fails with this message:
make: *** [sapi/cli/php] Error 1
Undefined symbols for architecture x86_64:
  "thread-local wrapper routine for _tsrm_ls_cache", referenced from:
      _zim_IntlDateFormatter___construct in dateformat_create.o
      _timezone_convert_to_datetimezone in timezone_class.o
      _zif_intlcal_from_date_time in calendar_methods.o
      _zif_intlcal_to_date_time in calendar_methods.o
      _php_intlgregcal_constructor_body(_zend_execute_data*, _zval_struct*, unsigned char) in gregoriancalendar_methods.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/phpdbg/phpdbg] Error 1

Check the gist here: https://gist.github.com/thgutmann/711a0b07d426139ea7ad9bb08f596c66

Any ideas?
Thanks, Theo

**Comment by SMillerDev** [comment]
Can't really help you debug changes you made. Afaik ZTS just causes a lot of problems in general and that's why it's disabled by default.

**Comment by iMichka** [comment]
This is not a supported configuration. And also a good example of why we removed options: they are unmaintained and often do not work.

To get this to work, I would try to seek help on the php bug tracker / mailing list. They may be able to help you fix this.

I'll close this issue, as this is not an issue in homebrew. You may also open a discussion on our discourse (https://discourse.brew.sh), some php experts may help you there.
