### ISSUE TITLE
luajit: Libs flags in pkgconfig aren't compatible with linking a shared library

### ISSUE THREAD

**Issue by tomaskrizek** [Homebrew/homebrew-core#37169]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

When compiling a C project using dependency detection via pkg-config (e.g. when using meson build system), `Libs:` flags are added to the compilation command. [`luajit.pc`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/luajit.rb#L53) has `-pagezero_size 10000 -image_base 100000000`, which are necessary when building *main executable* on 64b OS X (as mentioned in [upstream](https://luajit.org/install.html) ). However, adding these flags by default is incompatible with building *shared libraries* and attempting to do so fails during linking with `ld: -pagezero_size option can only be used when linking a main executable`

Link against a static version of luajit is also not possible, since that fails with `ld: unknown option: -E`

- What happened (include command output)
```
clang  -o modules/edns_keepalive/edns_keepalive.dylib 'modules/edns_keepalive/e8e6181@@edns_keepalive@sha/edns_keepalive.c.o' -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -bundle -Wl,-undefined,dynamic_lookup contrib/libcontrib.a lib/libkres.a /usr/local/lib/libknot.dylib /usr/local/Cellar/libuv/1.26.0/lib/libuv.dylib -lpthread -ldl -llmdb /usr/local/lib/libdnssec.dylib /usr/local/Cellar/gnutls/3.5.18/lib/libgnutls.dylib -pagezero_size 10000 -image_base 100000000 /usr/local/Cellar/luajit/2.0.5/lib/libluajit-5.1.dylib -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/../../contrib -Wl,-rpath,@loader_path/../../lib -Wl,-rpath,/usr/local/lib -Wl,-rpath,/usr/local/Cellar/gnutls/3.5.18/lib  
ld: -pagezero_size option can only be used when linking a main executable
```

- What you expected to happen

dynamic library (module) links successfully against luajit when using pkg-config for dependency detection

**Comment by vcunat** [comment]
Let me try pinging some recent `luajit.rb` contributors: @commitay, @fxcoudert.

**Comment by tomaskrizek** [comment]
Workaround for future generations using meson: use `partial_dependency()` and avoid using `link_args`, e.g.:

```
luajit = dependency('luajit')
luajit_dep = luajit.partial_dependency(compile_args: true, link_args: false, links: true, includes: true, source: true)
```
