### ISSUE TITLE
git-ftp upgrade fails

### ISSUE THREAD

**Issue by Alok** [Homebrew/homebrew-core#372]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

I try to update `git-ftp` and get the following error.

https://gist.github.com/4d36004ca76a115e3a2437f904387f1b
```
==> Upgrading git-ftp
==> Downloading https://github.com/git-ftp/git-ftp/archive/1.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/git-ftp-1.2.0.tar.gz
==> make prefix=/usr/local/Cellar/git-ftp/1.2.0 install
==> make -C man man
Error: No such file or directory - man/man1/git-ftp.1
```

**Comment by DomT4** [comment]
Should be fixed after a `brew update` via https://github.com/Homebrew/homebrew-core/commit/036be8df344b138bf44d42a666c2f37da93ce432. Let us know if you hit any further problems. Thanks for the report!
