### ISSUE TITLE
cmus  --with-ffmpeg 'invalid option'

### ISSUE THREAD

**Issue by stylerw** [Homebrew/homebrew-core#37217]
**Bug:** cmus wails to install with  `Error: invalid option: --with-ffmpeg` in most recent versions

**Steps to Reproduce:** `brew install cmus --HEAD --with-ffmpeg`.  This returns `Error: invalid option: --with-ffmpeg`.

**Desired behavior:** `cmus` installs with ffmpeg, as it had previously on my system.  ffmpeg worked fine until around a month ago, when i noticed a cmus update had broken ffmpeg.  This is needed to play back Apple Lossless files.

A previous bug had this issue, but said it ran on later runs.  I've been working on this for a few days, and have had no issues.

**Troubleshooting Steps:**
- `brew update` run twice
- `brew doctor` is clean (output below, but only anaconda-related things)
```
~ % brew doctor  
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/wstyler/anaconda3/bin/icu-config
  /Users/wstyler/anaconda3/bin/krb5-config
  /Users/wstyler/anaconda3/bin/freetype-config
  /Users/wstyler/anaconda3/bin/xslt-config
  /Users/wstyler/anaconda3/bin/libpng16-config
  /Users/wstyler/anaconda3/bin/python3.7-config
  /Users/wstyler/anaconda3/bin/libpng-config
  /Users/wstyler/anaconda3/bin/xml2-config
  /Users/wstyler/anaconda3/bin/python3.7m-config
  /Users/wstyler/anaconda3/bin/python3-config
  /Users/wstyler/anaconda3/bin/curl-config
  /Users/wstyler/anaconda3/bin/ncursesw6-config
  /Users/wstyler/anaconda3/bin/pcre-config
```
- No logs when running `brew gist-logs cmus`
- `brew config` below:
```
~ % brew config
HOMEBREW_VERSION: 2.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 117c24f4b6294e037431d3a850ced6955d53e26f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1c7339c86234b92e73b15072325b5a3ca4d276e2
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ArkoY3mFZP/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/wstyler/Library/Logs/Homebrew
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
Options have been removed from homebrew core. This is expected behavior. If you think ffmpeg is a dependency that would benefit the majority of users you could propose ffmpeg support as a default. If you don't you'll have to maintain your own version of the formula in a tap.

**Comment by stylerw** [comment]
Huh, that's some unexpected expected behavior.  Well, then yes, I absolutely propose it be the default, given that ffmpeg support is the only thing that makes cmus able to play many of the default file formats on macOS.  Is there a formal process for proposing this?  Or have I just done so?

**Comment by SMillerDev** [comment]
The way to propose it as a default is to make a pull request changing this to the default behavior.

As for the error message, that's just the error you get when you use an option that doesn't exist. It'd be almost impossible to add custom error message for this.
