### ISSUE TITLE
Cannot install curl with libssh2

### ISSUE THREAD

**Issue by EatBreatheCode** [Homebrew/homebrew-core#37255]
Tried running
`brew install curl -with-libssh2`

Output:
`Error: invalid option: -with-libssh2`

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by SMillerDev** [comment]
This is correct. Options have been removed from homebrew core. If you think this option should be a default for all users you can propose it as a default.

**Comment by EatBreatheCode** [comment]
Does this mean I have to compile it without home brew?

**Comment by iMichka** [comment]
No, you can also host you own formula somewhere in an external tap. Or open a pull request here to add it back, but not as an option.

**Comment by SMillerDev** [comment]
You can still have homebrew compile it, especially if you propose it as a default. Otherwise you'll have to use `brew extract` to move the formula to a tap for yourself where you can edit it easily.

**Comment by SMillerDev** [comment]
See docs.brew.sh if you want to do the latter.

**Comment by EatBreatheCode** [comment]
If someone could give me a step-by-step, it would be VERY much appreciated.

**Comment by iMichka** [comment]
There is no real step-by-step. We will not provide that. This is out of our scope.

We provided a link to the docs. If there is a specific question we can try to answer it. But we can not provide a step-by-step for that kind of requests.

**Comment by marcelomazza** [comment]
@EatBreatheCode check https://github.com/marcelomazza/homebrew-curl-libssh2

**Comment by equal-l2** [comment]
For future reference, you can also install curl with libssh2 support by installing `curl-openssl` (with a bunch of the other dependencies)
