### ISSUE TITLE
Brew installed Readline library errors. Pyenv installed Python 3.5 is requiring Readline 7, but Brew installs only Readline 8

### ISSUE THREAD

**Issue by chluther** [Homebrew/homebrew-core#37304]
Following an upgrade to MacOS Mojave I rebuilt my Python development environment using Homebrew and Pyenv.  I then began experiencing Readline library errors where Pyenv installed Python 3.5 was requiring Readline 7, was referencing Brew's Readline, but Brew installs only Readline 8.  While I'm not sure if this is a HOMEBREW READLINE package bug per se, it may suggest additional documentation is needed.

- I first updated XCODE and my SDK headers ( https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035624 ). 
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

- Using homebrew I installed the Pyenv, Readline and XZ.
`$ brew update
$ brew install pyenv readline xz`

- Then using Pyenv I installed the various Python packages:
`$ pyenv install 3.5.0
$ pyenv install 2.7.10`

- The Pyenv installer advised me that it was using Homebrew's readline.
`Installing Python-3.5.0...
python-build: use readline from homebrew`

- When I attempt to run a Python program I get the error:
`ImportError: dlopen(/Users/me/.pyenv/versions/3.5.0/lib/python3.5/lib-dynload/readline.cpython-35m-darwin.so, 
2): Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
Referenced from: /Users/me/.pyenv/versions/3.5.0/lib/python3.5/lib-dynload/readline.cpython-35m-darwin.so
Reason: image not found`

- Looking in /usr/local/opt/readline/lib all I see is version 8 libraries.
`$ ls /usr/local/opt/readline/lib
libhistory.8.0.dylib    libhistory.a        libreadline.8.0.dylib   libreadline.a       pkgconfig
libhistory.8.dylib  libhistory.dylib    libreadline.8.dylib libreadline.dylib`

Agreed, this problem may not technically be a bug, but related to missing documentation. At this point I don't know if I should: A) figure out how to install readline v.7 via homebrew, or B) somehow update pyenv to not use homebrew's readline but install the library itself, or C) something else entirely.  But I highly suspect someone else will encounter this problem so I'm starting here.

**Comment by szb512** [comment]
Have you tried installing Readline 7?

**Comment by chluther** [comment]
Well, yes, but I didn't see an earlier version available as a brew option.

```
$ brew search readline
==> Formulae
libreadline-java                                                  with-readline                                                     homebrew/linuxbrew-core/with-readline
readline ✔                                                        homebrew/linuxbrew-core/readline                                  homebrew/portable-ruby/portable-readline

```

I stepped away from the keyboard and eventually gave up on installing readline via Homebrew.  Since I had pyenv installed, I  ended up using pip to install an earlier version of readline within that project. 
``
$ pip install --upgrade pip setuptools
$ pip install readline
$ pip list
Package           Version
----------------- -------
astroid           2.0.4  
click             6.7    
envkey            1.1.0  
isort             4.3.4  
lazy-object-proxy 1.3.1  
mccabe            0.6.1  
pip               19.0.3 
pylint            2.1.1  
python-dotenv     0.7.1  
readline          6.2.4.1
setuptools        40.8.0 
six               1.11.0 
typed-ast         1.1.0  
Unidecode         1.0.23 
virtualenv        16.0.0 
wrapt             1.10.11
``
