### ISSUE TITLE
Git uses non-English language when English is set as OS language

### ISSUE THREAD

**Issue by auduchinok** [Homebrew/homebrew-core#37331]
Another repro case for #31980 is Git 2.21.0. It uses a wrong language again.
#31980 is now closed and locked so I have to create another issue instead of adding a comment there.

A workaround is the same: one has to delete wrongly used localizations by hand.

**Comment by SMillerDev** [comment]
Or define a specific language using the environment variables git allows for. If this is an issue it should be reported upstream.

**Comment by luispuerto** [comment]
I have the same problem... 

Can you tell me @auduchinok how can one delete those wrongly used localizations by hand???

@SMillerDev Can you tell me how can I pass environment variables to git system wide? The problem is not to use git on terminal but some apps get the wrong language from git.

**Comment by SMillerDev** [comment]
If setting it in bashrc doesn't work is say your best bet is to file a bug report with the offending program.

**Comment by luispuerto** [comment]
@SMillerDev if install the binaries offered by the developer, the issue doesn’t happen at all. The issue is related to homebrew build or install. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by luispuerto** [comment]
Por that reason I understand that I can’t file an issue with the offending program. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SMillerDev** [comment]
Binaries and program are very vague terms. If you think something is incorrect in homebrew, report it to homebrew. If you think a program shouldn't pick up the language you've set, report it upstream.

**Comment by luispuerto** [comment]
Upstream are going to tell me that I should install the binary they provide.

**Comment by auduchinok** [comment]
> Can you tell me @auduchinok how can one delete those wrongly used localizations by hand???

Sure, in my case it was
```
rm -rf /usr/local/Cellar/git/2.21.0/share/locale/ru
```
to make Git use English language on OS where English is the system language. Everything has been working as expected before #31799.

**Comment by luispuerto** [comment]
thanks @auduchinok!! 

I decided just to rename it, just in case, and i used this command: 

```shell
find $(brew --prefix)/Cellar/git -type d -name "es" -print0 | xargs -I{} mv {} {}.back
```
