### ISSUE TITLE
Unable to specify --with-sdl or --with-sdl2 flag for qemu

### ISSUE THREAD

**Issue by cookiesowns** [Homebrew/homebrew-core#37340]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Attempting to install qemu with the sdl flag in order to allow certain images with Packer to display video output ( console output )

Unfortunately it appears in the latest change the command options to add the option flag of building/installing qemu with sdl/sdl2 has been removed.

Sort of modifying the formulae manually and installing it with it there's no option to get a working qemu & packer together with homebrew on OSX.

**Comment by SMillerDev** [comment]
Generally the option was almost never used. If you want a non-standard configuration you'll have to maintain it yourself indeed, or if you think it should be a default for everyone you can make a pull request to change it.

**Comment by SMillerDev** [comment]
Either way, this is expected so I'm closing this issue.
