### ISSUE TITLE
emacs is a default dependency of notmuch, which means any formula depends on notmuch will install emacs.

### ISSUE THREAD

**Issue by ahmedelgabri** [Homebrew/homebrew-core#37363]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why): 
Installing `neomutt`

- What happened (include command output): 
Installed `emacs` as a dependency because it depends on `gettext` which depends on `emacs` by default now after removing options.

https://github.com/Homebrew/homebrew-core/blob/0d035f5271e545f43df08fd5097e4cc73e17652d/Formula/gettext.rb#L29

https://github.com/Homebrew/homebrew-core/blob/0d035f5271e545f43df08fd5097e4cc73e17652d/Formula/neomutt.rb#L16

- What you expected to happen: 
To not install `emacs`

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install neomutt
```

**Comment by tschoonj** [comment]
`gettext` is not the one dragging `emacs` in, `notmuch` is, as shown by the output of `brew deps --tree neomutt`:

```
neomutt
├── gettext
├── gpgme
│   ├── gnupg
│   │   ├── adns
│   │   ├── gettext
│   │   ├── gnutls
│   │   │   ├── gmp
│   │   │   ├── libtasn1
│   │   │   ├── libunistring
│   │   │   ├── nettle
│   │   │   │   └── gmp
│   │   │   ├── p11-kit
│   │   │   │   └── libffi
│   │   │   └── unbound
│   │   │       ├── libevent
│   │   │       │   └── openssl
│   │   │       └── openssl
│   │   ├── libassuan
│   │   │   └── libgpg-error
│   │   ├── libgcrypt
│   │   │   └── libgpg-error
│   │   ├── libgpg-error
│   │   ├── libksba
│   │   │   └── libgpg-error
│   │   ├── libusb
│   │   ├── npth
│   │   └── pinentry
│   │       ├── libassuan
│   │       │   └── libgpg-error
│   │       └── libgpg-error
│   ├── libassuan
│   │   └── libgpg-error
│   └── libgpg-error
├── libidn
├── lmdb
├── notmuch
│   ├── emacs
│   │   └── gnutls
│   │       ├── gmp
│   │       ├── libtasn1
│   │       ├── libunistring
│   │       ├── nettle
│   │       │   └── gmp
│   │       ├── p11-kit
│   │       │   └── libffi
│   │       └── unbound
│   │           ├── libevent
│   │           │   └── openssl
│   │           └── openssl
│   ├── glib
│   │   ├── gettext
│   │   ├── libffi
│   │   └── pcre
│   ├── gmime
│   │   ├── glib
│   │   │   ├── gettext
│   │   │   ├── libffi
│   │   │   └── pcre
│   │   └── gpgme
│   │       ├── gnupg
│   │       │   ├── adns
│   │       │   ├── gettext
│   │       │   ├── gnutls
│   │       │   │   ├── gmp
│   │       │   │   ├── libtasn1
│   │       │   │   ├── libunistring
│   │       │   │   ├── nettle
│   │       │   │   │   └── gmp
│   │       │   │   ├── p11-kit
│   │       │   │   │   └── libffi
│   │       │   │   └── unbound
│   │       │   │       ├── libevent
│   │       │   │       │   └── openssl
│   │       │   │       └── openssl
│   │       │   ├── libassuan
│   │       │   │   └── libgpg-error
│   │       │   ├── libgcrypt
│   │       │   │   └── libgpg-error
│   │       │   ├── libgpg-error
│   │       │   ├── libksba
│   │       │   │   └── libgpg-error
│   │       │   ├── libusb
│   │       │   ├── npth
│   │       │   └── pinentry
│   │       │       ├── libassuan
│   │       │       │   └── libgpg-error
│   │       │       └── libgpg-error
│   │       ├── libassuan
│   │       │   └── libgpg-error
│   │       └── libgpg-error
│   ├── python@2
│   │   ├── gdbm
│   │   ├── openssl
│   │   ├── readline
│   │   └── sqlite
│   │       └── readline
│   ├── talloc
│   ├── xapian
│   └── zlib
├── openssl
└── tokyo-cabinet
```

**Comment by ahmedelgabri** [comment]
Thanks for `brew deps --tree neomutt` I didn't know about that.

But it's the same issue still, why pull in an editor by default as a dependency?

**Comment by tschoonj** [comment]
Your new title is still wrong: `emacs` is not a default dependency of `gettext`, in fact is has no dependencies at all. I know `configure` is invoking `--with-emacs`, but this does not imply that `gettext` is a dependency. AFAIK the only consequence of this option is that a number of Emacs related Lisp files are added to `prefix/share/emacs`.

If you don't like that `notmuch` drags in `gettext`, feel free to open a PR that removes it.

**Comment by ahmedelgabri** [comment]
Fixed the title.

> If you don't like that `notmuch` drags in `gettext`, feel free to open a PR that removes it.

For me, the problem is `notmuch` dragging `emacs` not `gettext`. And I can open a PR to remove that, yes?

**Comment by tschoonj** [comment]
Well you can open the PR, but I cannot guarantee it will be merged in 😄 

I guess there was significant usage of this option, which is why it was made default during the Great Option Removal.

**Comment by ahmedelgabri** [comment]
Done https://github.com/Homebrew/homebrew-core/pull/37390
