### ISSUE TITLE
FreeRadius install does not compile openDirectory.dylib

### ISSUE THREAD

**Issue by KONSTRUKTEUR** [Homebrew/homebrew-core#37438]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install FreeRadius on two different machines running Mojave.

- What happened (include command output)
I installed FreeRadius via brew, but no rlm_opendirectory.dylib compiled on both systems

- What you expected to happen
I expected compiled FreeRadius to have 

> • rlm_opendirectory.a 
> • rlm_opendirectory.dylib 
> • rlm_opendirectory.la 

files in /usr/local/Cellar/freeradius-server/3.0.17/lib/ according to the [documentation by Apple](https://developer.apple.com/support/macos-server/macOS-Server-Service-Migration-Guide.pdf) and FreeRadius, but no rlm_opendirectory.* files are compiled.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
[~]$ brew install freeradius-server
==> Downloading https://homebrew.bintray.com/bottles/freeradius-server-3.0.17.mojave.bottle.tar.gz
Already downloaded: /Users/ME/Library/Caches/Homebrew/downloads/5b99d5255333417d82ae04d247dc5b154599552c2cbe92b9c4606209c236502b--freeradius-server-3.0.17.mojave.bottle.tar.gz
==> Pouring freeradius-server-3.0.17.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/freeradius-server/3.0.17: 851 files, 10.6MB
```

but no rlm_opendirectory.* present.

I had to compile manually:
A. `tar zxvf freeradius-server-3.0.0.tar.gz`
B.  `cd freeradius-server-3.0.0`
C. `./configure --enable-developer=yes --localstatedir=/var --with-openssl-lib-dir=/usr/local/lib`
D. `make`
E. `sudo make install`

and copied the files over.

When running `brew gist-log` >
```
[~]$ brew gist-logs freeradius-server
Error: No logs.
```

```
[~]$ brew config
HOMEBREW_VERSION: 2.0.2-101-g5eb79b5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5eb79b552c50abb0c35fdd8f70e9cccbc391598e
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 55b07164dbe49795be132976d64675357f3a16fe
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/ME/Library/Logs/Homebrew
CPU: 24-core 64-bit arrandale
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
CLT headers: 10.1.0.0.1.1539992718
[~]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-versions
Untap them with `brew untap`.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/DUMFeatureSelection.h
  /usr/local/include/FeatureEnumDefinitions.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php@7.0
  python
  php@5.6
[~]$ 
```

I tried:
`[~]$ brew edit freeradius-server`
and added
```
--enable-developer=yes
--with-experimental-modules
```

but the openDirectory still does not compile.

Thanks in advance!

**Comment by fxcoudert** [comment]
We do not wish to enable “developer” or “experimental” features in Homebrew core. Maybe the solution is for you to create a personal tap? https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by KONSTRUKTEUR** [comment]
> We do not wish to enable “developer” or “experimental” features in Homebrew core. Maybe the solution is for you to create a personal tap? https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

Thanks for your feedback. I will take a look at your link!!!

Though I still do not understand why the openDirectory libraries do not compile through brew even when editing the formula and adding the relative arguments, but when downloading from freeradius and compiling the openDirectory libraries are compiled.

Why could that be?

Thanks in advance!

**Comment by fxcoudert** [comment]
Did you recompile from source (`brew reinstall -s`) after editing the formula? Otherwise, things are going to get installed from our binary bottles, despite the formula modification.

**Comment by KONSTRUKTEUR** [comment]
> Did you recompile from source (`brew reinstall -s`) after editing the formula? Otherwise, things are going to get installed from our binary bottles, despite the formula modification.
> 
> I'm closing this issue, but we can continue commenting.

No, I was not aware of the fact that I had to use `brew reinstall -s`.
Now they compiled. Thank you so much! I learned something new.

I will take a look into creating a tap.
