### ISSUE TITLE
wordnet 3.0

### ISSUE THREAD

**Issue by arademaker** [Homebrew/homebrew-core#37442]
not bug report !!  Feature request!! I didn't find a template for that!

Hi @vszakats,

Wordnet formula ~> I would like to be able to have Wordnet 3.0 instead of the Wordnet 3..1 . Maybe allow the user to choose the DB version that he wants to use by default ?

**Comment by SMillerDev** [comment]
Homebrew only accepts feature requests in the form of pull requests so I'm going to close this issue.
