### ISSUE TITLE
No bash-completion on docker install

### ISSUE THREAD

**Issue by petr-ujezdsky** [Homebrew/homebrew-core#37506]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Use bash-completion for `docker` command
Eg. `$ docker st<TAB>`

- What happened (include command output)
bash-completion for `docker` does not work. It tries to complete it searching for local files instead of available sub-commands.
During `docker` installation it gives you a note that the bash-completion is installed:

```
$ brew info docker
docker: stable 18.09.3 (bottled)
Pack, ship and run any application as a lightweight container
https://www.docker.com/
/usr/local/Cellar/docker/18.09.3 (8 files, 72.2MB)
  Poured from bottle on 2019-03-02 at 11:08:23
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker.rb
==> Dependencies
Build: go ✘
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 34,154 (30 days), 94,051 (90 days), 366,834 (365 days)
install_on_request: 29,967 (30 days), 82,421 (90 days), 299,570 (365 days)
build_error: 0 (30 days)
```

But there are actually no files
```
$ ls -l /usr/local/etc/bash_completion.d | grep docker
$
```

- What you expected to happen
I expect to either actually copy the desired bash-completion files into `/usr/local/etc/bash_completion.d` or remove the note if it is not supported.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install docker
$ . ~/bash_profile
$ docker st<TAB>
```

**Comment by fxcoudert** [comment]
This is working fine here:

```
$ ls -lh /usr/local/etc/bash_completion.d/docker
lrwxr-xr-x  1 fx  admin    56B Mar  6 14:29 /usr/local/etc/bash_completion.d/docker -> ../../Cellar/docker/18.09.3/etc/bash_completion.d/docker
```

Can you:

- `brew reinstall docker`
- post the output of `brew doctor` and `brew config`?
