### ISSUE TITLE
brew audit error - incompatible library version - please report this bug

### ISSUE THREAD

**Issue by denniscote** [Homebrew/homebrew-core#37551]
I am reporting a error generated during a "brew audit" command since the error output said "please report this bug".

I copied the error message text and my brew doctor and brew config output to a gist  at 
https://gist.github.com/denniscote/9a687158e32446c5bc898905755e3608

**Comment by denniscote** [comment]
To resolve this issue I had to delete the portable-ruby directory and portable-ruby-version file at /usr/local/Homebrew/Library/Homebrew/vendor/ and then I deleted the entire directory at /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/

Then I ran the "brew audit " command. This causes all the ruby gems to be reinstalled which recreates the /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/ directory. This time the gems are built using the system ruby, so the incompatible library error is resolved.

After this brew doctor said that I had uncommitted modifications to homebrew, so I took its advice and ran the command

`cd /usr/local/Homebrew/Library && git stash && git clean -d -f`

Now brew doctor is happy, and I can audit a formula. My brew config now reports:

`Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby`

instead of the the portable-ruby as I had before.

**Comment by fxcoudert** [comment]
I'm going to close for now, thanks for reporting the fix. Not sure exactly what went wrong…
