### ISSUE TITLE
ImageMagic@6 pkg-config bug

### ISSUE THREAD

**Issue by matejsp** [Homebrew/homebrew-core#37591]
**Test with 6.x**
```
brew install imagemagick@6
pkg-config --list-all
```
it is missing imagemagick in a list (MagickWand-6, MagickCore-6, ...)

**Test with 7.x**
```
brew install imagemagick
pkg-config --list-all
```
you can find imagemagick v7 in the list as it should be:
```
MagickCore-7.Q16HDRI  MagickCore - MagickCore - C API for ImageMagick (ABI Q16HDRI)
MagickWand-7.Q16HDRI  MagickWand - MagickWand - C API for ImageMagick (ABI Q16HDRI)
```

**Workaround**
```
export PKG_CONFIG_PATH=/usr/local/Cellar/imagemagick\@6/6.9.10-27/lib/pkgconfig/
pkg-config --list-all
```
you can see imagemagick v6 in the list
```
ImageMagick-6.Q16     ImageMagick - ImageMagick - convert, edit, and compose images (ABI Q16)
MagickWand-6.Q16      MagickWand - MagickWand - C API for ImageMagick (ABI Q16)
MagickCore-6.Q16      MagickCore - MagickCore - C API for ImageMagick (ABI Q16)
```

I have tried with only one version installed (just to be sure there is no PATH conflict)

**Comment by fxcoudert** [comment]
Yeah, it is desired behavior because:

```
==> Caveats
imagemagick@6 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.
```

You will indeed have to set `PKG_CONFIG_PATH` manually to use it. This avoids conflicts with the main version of the package.

**Comment by matejsp** [comment]
I see :) Based on the different distros (Debian, Fedora, Ubuntu, Centos, ...):
https://pkgs.org/download/imagemagick
https://pkgs.org/download/ImageMagick

The most used and supported version is unfortunately still 6.9 and not 7.
For cross platform development 6.9 is still the latest.
I would turn around the key-only flag between 6 and 7 for a time being.

But I guess the current decision was already made up some time ago.
