### ISSUE TITLE
Passenger 6.0.2 ngx_http_passenger_module.so is not compatible with nginx 1.15.9

### ISSUE THREAD

**Issue by syakovyn** [Homebrew/homebrew-core#37615]
**passenger 6.0.2** is bundled with **ngx_http_passenger_module.so** built against **nginx 1.15.8** instead of **nginx 1.15.9**.

Error message when starting nginx:
_module “/usr/local/opt/passenger/libexec/modules/ngx_http_passenger_module.so” version 1015008 instead of 1015009 in /usr/local/etc/nginx/nginx.conf_

The workaround is to build **passenger** from sources after installing nginx:
_brew reinstall --build-from-source passenger_

**Comment by fxcoudert** [comment]
Fixed
