### ISSUE TITLE
wget failed to build on 10.11.6

### ISSUE THREAD

**Issue by lcn2** [Homebrew/homebrew-core#3762]
wget failed to build on 10.11.6

https://gist.github.com/5ab74fb549470ef7fad39e04b42b70e7

**Comment by MikeMcQuaid** [comment]
@lcn2 This is likely due to the files `brew doctor` is warning about. Can you try to `brew reinstall wget` after they are removed? Thanks!

**Comment by lcn2** [comment]
Hello Mike,

When we de-installed the calc RPM, we able to install wget and gnuplot.

It seems the RPM package of calc-devel, which installs *.h files into /usr/local/include,
somehow confuses both packages.  Code / Applications built for calc depends on those
include files so they are expected by the calc developer base to be installed into /usr/local.  

BTW: We have received requests from calc users to create a brew for calc.
	  How should we handle this conflict in the future?

chongo (Landon Curt Noll) /\oo/\

=-=

**Comment by MikeMcQuaid** [comment]
> When we de-installed the calc RPM, we able to install wget and gnuplot.

Cool, closing.
