### ISSUE TITLE
gnuplot failed to build on 10.11.6

### ISSUE THREAD

**Issue by lcn2** [Homebrew/homebrew-core#3763]
gnuplot failed to build on 10.11.6

See:

https://gist.github.com/5f75a3f17b11a1ab2636a4dbe236f1ee

**Comment by MikeMcQuaid** [comment]
@lcn2 This is likely due to the files `brew doctor` is warning about. Can you try to `brew reinstall $(brew deps gnuplot) gnuplot` after they are removed? Thanks!

**Comment by lcn2** [comment]
Hello Mike,

When we de-installed the calc RPM, we able to install wget and gnuplot.

It seems the RPM package of calc-devel, which installs *.h files into /usr/local/include,
somehow confuses both packages.  Code / Applications built for calc depends on those
include files so they are expected by the calc developer base to be installed into /usr/local.  

BTW: We have received requests from calc users to create a brew for calc.
	  How should we handle this conflict in the future?

chongo (Landon Curt Noll) /\oo/\

=-=

**Comment by MikeMcQuaid** [comment]
> When we de-installed the calc RPM, we able to install wget and gnuplot.

Cool, closing.

**Comment by MikeMcQuaid** [comment]
> It seems the RPM package of calc-devel, which installs *.h files into /usr/local/include,
> somehow confuses both packages.  Code / Applications built for calc depends on those
> include files so they are expected by the calc developer base to be installed into /usr/local.

Homebrew does not support this configuration.

> BTW: We have received requests from calc users to create a brew for calc.
> 	  How should we handle this conflict in the future?

https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md#add-a-new-formula-for-foo-version-234-from-url should help with adding a new formula.
