### ISSUE TITLE
brew upgrade bazel 401 Unauthorized

### ISSUE THREAD

**Issue by zhangqianghd** [Homebrew/homebrew-core#37639]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Regular update 
- What happened (include command output)
Run brew upgrade bazel  and get URL returned error:401 Unauthorized,then to download souce code and to build.
But building from souce is to slowly ,so I Ctrl+C stopped the process.
- What you expected to happen
Use bottle to finish update not build from source.Because the building process will spend a long time.
- Step-by-step reproduction instructions (by running `brew install` commands)
brew upgrade bazel
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
fn
==> Upgrading 1 outdated package:
bazel 0.23.0 -> 0.23.1
==> Upgrading bazel 
==> Downloading https://homebrew.bintray.com/bottles/bazel-0.23.1.mojave.bottle.tar.gz
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "bazel"
Download failed: https://homebrew.bintray.com/bottles/bazel-0.23.1.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/bazelbuild/bazel/releases/download/0.23.1/bazel-0.23.1-dist.zip
^C^C

**Comment by jonchang** [comment]
Thanks for reporting this. I've fixed this in ca6b39ae991c21cb1d535527338dfaeef021d132.

**Comment by jonchang** [comment]
Run `brew update && brew install bazel` to get the new version.
