### ISSUE TITLE
GhostScript "illegal hardware instruction"

### ISSUE THREAD

**Issue by mskblackbelt** [Homebrew/homebrew-core#37654]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I've installed the Homebrew version of `ghostscript` (v. 9.26) on my Mac Pro (3,1) running macOS 10.14.3. It generally works, but I was trying to get it to work with [MaTeX](https://github.com/szhorvat/MaTeX), which requires the flag `-dNoOutputFonts`. Running a command with this flag results in the following error:

    illegal hardware instruction  gs -o gt-gs1.pdf -dNoOutputFonts -sDEVICE=pdfwrite gt.pdf

Removing the `-dNoOutputFonts` flag results in successful conversion of the file. I've tried installing the bottled version of GhostScript as well as building from source, but it makes no difference. Here is the link to the output of `brew gist-logs gs` after building from source: 

<https://gist.github.com/mskblackbelt/2a4588e07447f1e2fec136b9dcbce1e7>

I realize there are a few items in the output for `brew doctor`. They are generally related to CocoAspell and have never caused issues before.

**Comment by fxcoudert** [comment]
This is working here locally. It may be an issue with your specific PDF file, can you share it? Can you reproduce the issue an all PDF files?

**Comment by mskblackbelt** [comment]
Nothing special about the PDF, literally anything with text will do. If there isn't any text in the PDF, the error doesn't manifest (presumably GhostScript is smart enough not to call the problematic instruction if there's no text). I tried it on two files created via LaTeX, one made by Mathematica (just a circle with "foo" printed in the center). For the record, I tried this on my Mac Mini (2014) at home and GhostScript(bottled version) works just fine. 

Is it possible that the Xeon in the 2008 Mac Pro doesn't support some assumed instruction used by GhostScript? Perhaps something related to Metal that the compiler assumes is present in a machine running Mojave? 

I'll try installing a copy of GhostScript from <https://pages.uoregon.edu/koch/> now and see if that version works.

**Comment by mskblackbelt** [comment]
Verified, the version of GhostScript 9.26 available at <https://pages.uoregon.edu/koch/Ghostscript-9.26.pkg> is able to convert text to vectors with the `dNoOutputFonts` on the 2008 Mac Pro.

**Comment by fxcoudert** [comment]
Unless I'm wrong, the “Mac Pro 3,1” does not support Mojave. Homebrew assumes an officially supported target when compiling, and on Mojave that means Nehalem or later. That is probably the reason why your Penryn CPU is throwing errors.

One hack to make it work would be to force it to install the High Sierra bottle.

**Comment by mskblackbelt** [comment]
I suspected that might be an issue, which is why I did `--build-from-source`. Since this apparently didn't occur, is there a way to set a flag in `brew --config` to force support for the Penryn architecture? At least in situations when I specify `--build-from-source`? It would also be nice have Homebrew check for support when installing from bottles (though I assume that check is _just_ for the OS version, since that should (usually) define an appropriate list of requirements).

**Comment by mskblackbelt** [comment]
I see that I can do `brew install foo --build-bottle --bottle-arch=penryn`. Is that appropriate if I'm not trying to redistribute the bottle?

**Comment by fxcoudert** [comment]
I think `--bottle-arch` is the workaround you're looking for, indeed (I forgot it actually existed). Since we can't actually test on unsupported hardware, we do not want to support it either.

**Comment by mskblackbelt** [comment]
Sounds good, thanks for the troubleshooting assistance. Last questions:

- Can I directly pour a bottle made for a previous version of macOS (i.e., High Sierra), or do I need to download from Bintray and move manually? I couldn't find a command reference after the removal of `homebrew/versions`. 
- Can I set a build flag for Homebrew (maybe via a CFLAGS variable?)to target the Penryn architecture when building from source (the only mention of architecture on the Homebrew page manual is with respect to bottle creation)? It seems odd that there isn't a way for Homebrew to detect the architecture on the machine doing the build.
