### ISSUE TITLE
Keybase 1.0.17 fails to build

### ISSUE THREAD

**Issue by BM5k** [Homebrew/homebrew-core#3767]
Not sure if this is a macOS 10.12 issue (beta 16A286a) or an issue with the keybase formula.

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

https://gist.github.com/anonymous/1d969203e36b639a96a515e302ac1db3

**Comment by DomT4** [comment]
Stable `go` is dead on Sierra after some changes Apple implemented.

You'll need to `brew rm go && brew install go --devel` until 1.7 lands stable. If it doesn't work after that, feel free to shout.
