### ISSUE TITLE
brew upgrade stuck and drain all cpu resource.

### ISSUE THREAD

**Issue by LOGANLEEE** [Homebrew/homebrew-core#37678]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem? yes
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? yes
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why) : brew upgrade
- What happened (include command output): brew upgrade
- What you expected to happen : upgrade finish well.
- Step-by-step reproduction instructions (by running `brew install` commands) : brew upgrade

as you 

`
==> Upgrading gcc 
Warning: Building gcc from source:
  The bottle needs the Xcode CLT to be installed.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.3.0/gcc-8.3.0.tar.xz

(i will skip progress line )
 100.0%
==> ../configure --build=x86_64-apple-darwin18.2.0 --prefix=/usr/local/Cell
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
`

i've been suffer this symptoms quite a while.

**Comment by SMillerDev** [comment]
Did you try installing the xcode commandline tools as it requests?

Furthermore, debugging anything is almost impossible without the issue template filled out. I'm going to close this until the required information is provided.

**Comment by LOGANLEEE** [comment]
ya i was about too that what i've done to solve this 
anyway thanks.
