### ISSUE TITLE
groff 1.22.4 is missing font families from devpdf

### ISSUE THREAD

**Issue by remorse** [Homebrew/homebrew-core#37703]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

I was trying to use the `N` font family in PDF output. This worked just fine under 1.22.3, also installed from Homebrew. When I upgraded to 1.22.4, the `N` font family no longer existed in `/usr/local/share/groff/1.22.4/font/devpdf`

```
$  groff -Tpdf -Kutf8 groff/1255923.groff > pdf/1255923.pdf
troff: groff/1255923.groff:13: warning: can't find font 'NR'
troff: groff/1255923.groff:60: warning: can't find font 'NI'
```

The output PDF has the wrong font in it (and the wrong spacing).

I looked at `/usr/local/share/groff/1.22.4/font/devpdf`, and it only has the `C`, `EURO`, `H`, `S`, `T`, and `ZD` font families. I expect to see at least also the `B` and `N` families.

I asked the groff mailing list about this, and they said that they did not change which families are provided by `devpdf`, so that the `B` and `N` families should be there, and suggested that I should file a bug against Homebrew.

Thanks!

**Comment by fxcoudert** [comment]
We need the output of `brew gist-logs`, or `brew doctor` and `brew config`,  at least.

**Comment by remorse** [comment]
```
buxtehude:~ rem16$ brew gist-logs groff
Error: No logs.
buxtehude:~ rem16$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-php
Untap them with `brew untap`.
buxtehude:~ rem16$ brew config
HOMEBREW_VERSION: 2.0.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6865aee729ebc28dfa4af6fdbaeec297df0ac34c
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d75f314198afe8bd1805b7d4d5666e5078cc1b08
Core tap last commit: 70 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.Vmz4etdfWA/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/rem16/Library/Logs/Homebrew
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.20.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by remorse** [comment]
Hi! I did some more research over the weekend, and I discovered that my ticket is partly incorrect, but that there is still something wrong.

First, my error: my memory was that I had installed `groff` 1.22.3 from a bottle, but this was (probably) not true -- on my home computer, 1.22.3 was installed from source. Although my work computer no longer has the 1.22.3 version on it, my guess is that it was also installed from source.

I assumed it was installed from a bottle because, if you look at `brew info groff`, there are no options listed, so why would I compile it? And on my work computer (where I am dealing with this issue), the 1.22.3 installation was removed (possibly I did a cleanup pass myself, but there also seems to be an auto-clean thing going on from time to time?) before I discovered this issue.

If you look at `brew info groff` on my home computer though, it says:

```
/usr/local/Cellar/groff/1.22.3 (788 files, 14.9MB)
  Built from source on 2018-07-05 at 21:38:07 with: --with-gropdf --with-grohtml --with-gpresent
```

and on my home computer, the list of fonts in `/usr/local/Cellar/groff/1.22.3/share/groff/1.22.3/font/devpdf` is much larger:

```
ls -1 /usr/local/Cellar/groff/1.22.3/share/groff/1.22.3/font/devpdf:
AB
ABI
AI
AR
BMB
BMBI
BMI
BMR
CB
CBI
CI
CR
DESC
EURO
Foundry
HB
HBI
HI
HNB
HNBI
HNI
HNR
HR
NB
NBI
NI
NR
PB
PBI
PI
PR
S
TB
TBI
TI
TR
U-AB
U-ABI
U-AI
U-AR
U-BMB
U-BMBI
U-BMI
U-BMR
U-CB
U-CBI
U-CI
U-CR
U-HB
U-HBI
U-HI
U-HNB
U-HNBI
U-HNI
U-HNR
U-HR
U-NB
U-NBI
U-NI
U-NR
U-PB
U-PBI
U-PI
U-PR
U-S
U-TB
U-TBI
U-TI
U-TR
U-ZCMI
U-ZD
ZCMI
ZD
download
enc/
map/
util/
```

(compare with 1.22.4:

```
ls -1 /usr/local/Cellar/groff/1.22.4/share/groff/1.22.4/font/devpdf:
CB
CBI
CI
CR
DESC
EURO
Foundry
HB
HBI
HI
HR
S
TB
TBI
TI
TR
ZD
download
enc/
map/
```
)

It looks like in commit `da1975623922cf2d64ced525ddee7e36511d42ab`, the options that could be passed for manual compilation were removed (log comment "groff: remove options", and `git diff a00da69af561e13691c9a66ca46fa2709ea752b7:Formula/groff.rb da1975623922cf2d64ced525ddee7e36511d42ab:Formula/groff.rb` from the `homebrew-core` directory backs this up).

According to the groff mailing list, the purpose of `--with-gropdf` is to ensure that `ghostscript` is available, because most of the fonts -- except Times, Courier, and Helvetica -- are gleaned from the ghostscript files. (Probably due to a licensing thing?)

So, it looks like I either need the bottle to be compiled in an environment with ghostscript installed, or I at least need the `--with-gropdf` option to be available for the formula so I can get the fonts I need.

(It is *really* hard to install fonts for groff manually (you have to edit various font files in FontForge, change tables, adjust some metrics -- at least, according to the various sources I can find online), so I *really* want the fonts that it will do all the work for as a part of the install process.)

Thanks!

**Comment by jonchang** [comment]
It sounds like you just need `ghostscript` with `groff`? Feel free to [open a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) to `groff` adding that dependency; if you need help we can guide you through any issues you might have. Thanks!

**Comment by remorse** [comment]
Hi! Not everyone will need `ghostscript` as a dependency. The issue is that I need to be able to pass the `--with-gropdf` option to the configure system, and make that require Ghostscript.

I guess that means I need to revert commit `da1975623922cf2d64ced525ddee7e36511d42ab`?

**Comment by fxcoudert** [comment]
Locally you can revert the commit. It's unlikely we are going to do that for all users, because of the weight of ghostscript as a dependency. Ultimately, it is a problem of `groff` not being easily configurable at runtime.

Closing, but thanks for opening this issue and the discussion, which may help other users facing this issue in the future.

**Comment by remorse** [comment]
Because of the way this works, that means that I cannot use Homebrew to install Groff in a way that has the fonts that I want, correct? There seems to be no way to pass the flag to the installer, even when installing from source, so in order to install Groff I will have to abandon Homebrew?

**Comment by fxcoudert** [comment]
You can have a locally modified formula, adding your flags. And you can also maintain it in your own tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by remorse** [comment]
I guess one last question, I'm confused why adding a flag that optionally adds Ghostscript would be a problem -- now that I know the issue, I'm fine with installing from source and not having it in the bottle, but it seems awkward to have to create a separate formula, a separate repository, etc., just to add one optional flag to the install command...

**Comment by fxcoudert** [comment]
We are not accepting options in Homebrew core formulas anymore: we don't have enough CI power to test them, they bitrot and often break.

**Comment by remorse** [comment]
Sorry, another question -- if I do have to create and maintain my own "tap", how do I explicitly tell Homebrew that it *should* override and replace the existing Groff formula? The page you linked to tells me that I should put some sort of prefix to avoid conflicts, but in this case I will *want* to conflict -- if anything were to depend on Groff, I would want that to install *my* version, not the Homebrew core version...

**Comment by remorse** [comment]
Re not accepting options, could Homebrew be enhanced to accept flags when compiling from source? Is there already a way when compiling from source to pass parameters that I missed?

**Comment by remorse** [comment]
Hi! I'm sorry to bother, but how do I explicitly tell Homebrew that the version of the groff formula in my tap should supersede the one in homebrew-core?
