### ISSUE TITLE
PHP, OpenSSL, Composer and not found cert bundle

### ISSUE THREAD

**Issue by UlrichThomasGabor** [Homebrew/homebrew-core#37702]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install brew versions of PHP and Composer and run Composer

- What happened (include command output)
Running composer with brew PHP version results in
```
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```

- What you expected to happen
If I install PHP and Composer from brew, I'd expect it to work without modifying configuration files.

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install php composer
composer update # I used it on a `typo3/cms-base-distribution` project
```

[It seems that the OpenSSL formula builds a CA bundle out of the keychain](https://github.com/Homebrew/homebrew-core/blob/63063c790f814ff24a6d66631b7174f59e2dbeaa/Formula/openssl.rb#L71), but PHP does not find it. I fixed this by editing `/usr/local/etc/php/7.3/php.ini` and setting the following settings:
```
openssl.cafile=/usr/local/etc/openssl/cert.pem
openssl.capath=/usr/local/etc/openssl/certs
```

I think the lines should be there by default. Googling for the issue results in a lot of questions concerning this error message and a lot of weird "fixes", which do not help. It is necessary to understand the problem thoroughly (Keychain vs. file based certs), what the problem is (PHP does not find certs) and understand what the OpenSSL formula is doing (exporting keychain to files). I doubt it should be necessary to understand all that to have a working composer installation out of Homebrew.

**Comment by jonchang** [comment]
Can you [open a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) making this change? It looks like the `php` formula is already modifying the default `php.ini` so you'd just need to add some more code pointing to the right place. If you need guidance we can help you through any questions you might have. Even a partial pull request is fine since talking over code is easier.

**Comment by UlrichThomasGabor** [comment]
@jonchang PR #37881 has been submitted long ago, but nothing has been done with it and now it is already marked as stale.

**Comment by UlrichThomasGabor** [comment]
Reopening until the PR has been merged.

**Comment by UlrichThomasGabor** [comment]
What is with this issue? It's a problem, I found out how to fix it, I submitted a pull request, which fixes the issue, but nothing is happening. Is not clear what the problem is? Is not clear that the solution is right?

**Comment by zbeekman** [comment]
@UlrichThomasGabor Sorry for the delay. The PR was submitted while our CI infra was really struggling, and maintaining homebrew feels like trying to drink from a firehose sometimes. I've re-opened and unlocked your PR. Hopefully it will get through CI relatively short order. Please keep an eye out for any CI failures, and investigate them. If they're because your changes broke something or failed audits, then please address them as quickly as you can. If it appears that there is a failure due to a problem with CI feel free to ping me.

Thanks!

**Comment by UlrichThomasGabor** [comment]
PR was merged.
