### ISSUE TITLE
libkml formulae doesn't support pkg-config

### ISSUE THREAD

**Issue by razor85** [Homebrew/homebrew-core#37701]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I tried to reference libkml from pkg-config and the information just isn't there. 
`brew ls libkml` also doesn't list any *.pc for this formulae

**Comment by SMillerDev** [comment]
Does upstream provide this information?

**Comment by razor85** [comment]
The google code repository doesn't, but the official github repository does. Since the formulae is based on the old repository, I don't know what's the right thing to do.

**Comment by SMillerDev** [comment]
If there's an official Github repo we might want to use that one. (Could you make a pull request?)

**Comment by razor85** [comment]
How should I proceed to do that? I believe the official repository is in https://github.com/google/libkml

**Comment by SMillerDev** [comment]
You could change the formula file to point to the new repo url. It doesn't seem like there's a recent release though. So your issue won't be fixed by it.

**Comment by fxcoudert** [comment]
No, sadly there is not recent release. The right thing to do here would be to ask upstream to cut a new release.
