### ISSUE TITLE
Same issue on a closed one https://github.com/Homebrew/homebrew-core/issues/33481

### ISSUE THREAD

**Issue by ipstone** [Homebrew/homebrew-core#37727]
Hello, I am trying to install i3 (on mac, and also trying on linux) through homebrew, but I have the same issue as in : https://github.com/Homebrew/homebrew-core/issues/33481 (it was closed, but the issue doesn't seem to be resolved).

When I am doing `brew intall i3`, it shows: 
```
Error: No available formula with the name "i3"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
i386-elf-binutils                 i386-elf-gcc                      i386-elf-gdb                      i386-elf-grub
To install one of them, run (for example):
  brew install i386-elf-binutils
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

I already followed the suggestions in the closed issue, but it didn't solve , still no i3 target is found.

Thanks

**Comment by equal-l2** [comment]
`i3` cannot be in homebrew-core, since its dependency `cairo` doesn't support X11 anymore. See https://github.com/Homebrew/homebrew-core/pull/27486.

**Comment by jonchang** [comment]
Please always fill out the issue template. Formulae with hard x11 dependencies have been removed.
