### ISSUE TITLE
brew upgrade causing invalid byte sequence error

### ISSUE THREAD

**Issue by sam-iitj** [Homebrew/homebrew-core#3772]
satsaxen  ~  Documents  Queues  queues-0.6.1  1  brew upgrade
==> Upgrading 37 outdated packages, with result:
ant 1.9.7, cmake 3.6.1, erlang 19.0.2, fontconfig 2.11.1_4, freetype 2.6.5, gcc 6.1.0_1, gd 2.2.3, gdbm 1.12, git 2.9.2, gmp 6.1.1, gnuplot 5.0.4, isl 0.17.1, libpng 1.6.23, libtiff 4.0.6_2, lua 5.2.4_4, mpfr 3.1.4, mysql 5.7.14, neo4j 3.0.3, node 6.3.1, openssl 1.0.2h_1, pcre 8.39, pkg-config 0.29.1_1, pyenv 20160726, pyqt 4.11.4, python 2.7.12, python3 3.5.2_1, qscintilla2 2.9.3, qt 4.8.7_2, rabbitmq 3.6.4, sbt 0.13.12, scala 2.11.8, sip 4.18.1, sqlite 3.14.0, unixodbc 2.3.4, vim 7.4.2152, zeromq 4.1.5, zsh-completions 0.19.0
==> Upgrading ant
Error: invalid byte sequence in UTF-8
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/vendor/okjson.rb:265:in `match'
/usr/local/Library/Homebrew/vendor/okjson.rb:265:in `numtok'
/usr/local/Library/Homebrew/vendor/okjson.rb:254:in `tok'
/usr/local/Library/Homebrew/vendor/okjson.rb:214:in `lex'
/usr/local/Library/Homebrew/vendor/okjson.rb:45:in `decode'
/usr/local/Library/Homebrew/utils/json.rb:10:in `load'
/usr/local/Library/Homebrew/utils/github.rb:176:in `open'
/usr/local/Library/Homebrew/utils/github.rb:277:in `private_repo?'
/usr/local/Library/Homebrew/tap.rb:509:in `read_or_set_private_config'
/usr/local/Library/Homebrew/tap.rb:150:in `private?'
/usr/local/Library/Homebrew/formula_installer.rb:207:in `install'
/usr/local/Library/Homebrew/cmd/upgrade.rb:96:in `upgrade_formula'
/usr/local/Library/Homebrew/cmd/upgrade.rb:66:in `block in upgrade'
/usr/local/Library/Homebrew/cmd/upgrade.rb:65:in `each'
/usr/local/Library/Homebrew/cmd/upgrade.rb:65:in `upgrade'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'

Here, brew config 

SATSAXEN-M-X01U:~ satsaxen$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bcb5cf680ae83de77e0ab35657f6d7fd014b28a0
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.2.1 => /usr/local/git/bin/git
Perl: /usr/bin/perl
Python: /Users/satsaxen/anaconda/bin/python => /Users/satsaxen/anaconda/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_51
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: N/A
X11: 2.7.8 => /opt/X11

**Comment by mistydemeo** [comment]
> https://git.io/brew-troubleshooting

Please read this guide and follow the instructions listed there.

**Comment by DomT4** [comment]
Closing as this seems to have gone dead, but please do ping if we can help further. Thanks!
