### ISSUE TITLE
Docker CLI

### ISSUE THREAD

**Issue by brunowego** [Homebrew/homebrew-core#37756]
Hi everybody, this is not an issue, I am getting a confusing about `brew install docker`, I take a look in the formula and I see that is the Docker CLI in fact.

If I rename this formula and submit, will be accept?

**Comment by brunowego** [comment]
By compare with another OS and yours respective package managers, we will see that are using the correct name:

## APT

```sh
sudo apt update
sudp apt install -y docker-ce-cli
```

## YUM

```sh
sudo yum check-update
sudp yum install -y docker-ce-cli
```


## Chocolatey

```sh
choco install -y docker-cli
```

**Comment by jonchang** [comment]
Please always fill out the [issue template](https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md). This is better framed as a pull request or a question on our Discourse forum.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
