### ISSUE TITLE
Missing opencv binaries

### ISSUE THREAD

**Issue by infusion** [Homebrew/homebrew-core#37769]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I wanted to use opencv to train haar files. To do so the binaries `opencv_createsamples, opencv_haartraining, opencv_traincascade` need to be used. Neither of them is installed per default using brew. 

I installed opencv with `brew install opencv`, which should include the missing files. Without reproducing the solution, they need to be added [manually](http://answers.opencv.org/question/2460/where-is-createsamples-application/) apparently.

**Comment by fxcoudert** [comment]
We configure and install opencv by running `make install`, so we do not choose which binaries are installed. In the case of the binaries you're mentioning, it appears this decision was made by the OpenCV project: see https://github.com/opencv/opencv/issues/13231

**Comment by infusion** [comment]
Thanks for this finding! I'll do it differently then.
