### ISSUE TITLE
can not download apache-flink by 'brew install apache-flink'

### ISSUE THREAD

**Issue by bruce1408** [Homebrew/homebrew-core#37776]
brew install apache-flink:
there are errors as following:
==>Downloading https://archive.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.11.tgz
curl: (22) The requested URL returned error: 503 Service Unavailable
Error: An exception occurred within a child process:
     DownloadError: Failed to download resource "apache-flink"
Download failed: https://archive.apache.org/dist/flink/flink-1.7.2/flink-1.7.2-bin-hadoop27-scala_2.11.tgz

the command does not work.

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
