### ISSUE TITLE
Calling 'fails_with :clang' with 'build' < 600 is disabled!

### ISSUE THREAD

**Issue by qiulihong** [Homebrew/homebrew-core#37814]
==> Downloading https://homebrew.bintray.com/bottles/jansson-2.12.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring jansson-2.12.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/jansson/2.12: 11 files, 157.5KB
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /Users/leonqiu/Library/Caches/Homebrew/gdbm--1.18.1.mojave.bottle.tar.gz... (197KB)
Removing: /usr/local/Cellar/openssl/1.0.2h_1... (1,691 files, 12MB)
Removing: /usr/local/Cellar/openssl/1.0.2p... (1,793 files, 12MB)
Removing: /Users/leonqiu/Library/Caches/Homebrew/openssl--1.0.2p.mojave.bottle.tar.gz... (3.7MB)
Removing: /Users/leonqiu/Library/Caches/Homebrew/readline--7.0.5.mojave.bottle.tar.gz... (497.6KB)
Removing: /Users/leonqiu/Library/Caches/Homebrew/sqlite--3.25.3.mojave.bottle.tar.gz... (1.8MB)
Removing: /usr/local/Cellar/wget/1.17.1... (9 files, 1.5MB)
Error: Calling 'fails_with :clang' with 'build' < 600 is disabled! There is no replacement.
Please report this to the homebrew/core tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:38

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
