### ISSUE TITLE
TigerVNC using only 1/4 of display when running on Retina display

### ISSUE THREAD

**Issue by lukego** [Homebrew/homebrew-core#37872]
Issue tigervnc/tigervnc#805 (*Display uses 1/4 of screen while mouse uses whole screen coordinates*) seems to only be reproducible using the binaries from homebrew and not the binaries from upstream. 

Could really be an issue with the homebrew package?

**Comment by jonchang** [comment]
Please always fill out the issue template:

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by lukego** [comment]
Sorry about that. I had already filled in the long issue template when submitting to the TigerVNC repo and so I hoped that this would be sufficient to "forward" the issue here rather than starting from scratch.

My bad but won't bother reporting problems to homebrew again.

**Comment by zuxy** [comment]
It's a regression caused by the recent FLTK 1.3.5 commit. Reverting FLTK to 1.3.4-2 fixes the problem.
