### ISSUE TITLE
yara.rb formula has invalid configure option

### ISSUE THREAD

**Issue by knightsc** [Homebrew/homebrew-core#37875]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Was trying to test the yara hombrew formula

- What happened (include command output)

https://github.com/Homebrew/homebrew-core/blob/master/Formula/yara.rb#L32

I noticed an invalid configure option. If you run a configure yourself and try to pass `--with-crpyto` you'll get the following

`configure: WARNING: unrecognized options: --with-crpyto`

- What you expected to happen

The configuration command should be correct and not have this warning

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install yara` and look through the output of the build process

**Comment by SMillerDev** [comment]
I guess that should be `with-crypto`? Could you make a pull request to fix it?

**Comment by knightsc** [comment]
Yes, sorry it should be `--with-crypto`. I've created a PR to update this

**Comment by SMillerDev** [comment]
Thanks!

**Comment by fxcoudert** [comment]
Thanks for the report and pull request @knightsc !
