### ISSUE TITLE
ammonite-repl is built incorrectly

### ISSUE THREAD

**Issue by dbingham** [Homebrew/homebrew-core#37884]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Gist logs: https://gist.github.com/7e133319f805ca831ed4daf74037be04

It appears that `ammonite-repl`'s brew file is slightly incorrect.  If you do a `brew install ammonite-repl` it installs correctly with no errors or warnings:
```
$ brew install ammonite-repl
==> Downloading https://github.com/lihaoyi/Ammonite/releases/download/1.6.4/2.12-1.6.4
Already downloaded: /Users/dbingham/Library/Caches/Homebrew/downloads/7a66dc0898c321afc1d8cf3a100f37c19c4636cc8c03d2cd49a21a25160432f6--2.12-1.6.4
🍺  /usr/local/Cellar/ammonite-repl/1.6.4: 4 files, 27.6MB, built in 3 seconds
```

But if you look at the file it creates, the first line is wrong:
```
$ head -1 /usr/local/bin/amm
@ 2>/dev/null # 2>nul & echo off & goto BOF
```

Whereas if you follow the instructions on the [ammonite homepage](https://ammonite.io/#Ammonite-REPL), the file that you end up with starts with this:
```
$ head -2 amm
#!/usr/bin/env sh
@ 2>/dev/null # 2>nul & echo off & goto BOF
```

And is otherwise the same thereafter.

This matters because when you have `bash` and `bashdb` installed and configured locally (i.e. link the bashdb into the bash share dir) the version of `amm` installed by homebrew launches the bash debugger instead of launching the ammonite REPL.  Whereas the one from the ammonite homepage launches correctly.  To reproduce the error do this:
```
$ brew install bash
$ brew install bashdb
$ brew install ammonite-repl
$ ln -s "$(brew --prefix bashdb)/share/bashdb" "$(brew --prefix bash)/share/bashdb"
$ amm
```

You should land in the bash debugger.  The correct behavior is that you should land in the ammonite REPL.

**Comment by dbingham** [comment]
Hello!  This is not stale.  In fact, it is still a bug!  Thanks, mr. bot.

**Comment by dbingham** [comment]
I will admit... it is rather quiet in here.

**Comment by SMillerDev** [comment]
Clearly nobody is working on it, maybe you should try making a pull request that attempts to fix the issue? You use the software so you'd know better than a random maintainer how it should work.
Either way there's no point in you fighting with the stalebot.

**Comment by dbingham** [comment]
@SMillerDev Somebody created it?  I'd update it and submit a pull request if I knew how.  Unfortunately I don't and learning it is probably a bit beyond what I can do at the moment.

Doesn't mean that it isn't a bug.  It _is_ a bug.  No reason to close it.  I outlined in the description above what the proper result is.  I just don't know how to make homebrew do that.  Perhaps someone else knows how and will be able to take the information, correct the issue, and properly close out the issue?

**Comment by dbingham** [comment]
@SMillerDev The formula was updated recently by @igas.  Perhaps @igas would be willing to take a look if you reopen it?

I do understand the purpose of the stale bot but this genuinely isn't stale in the sense that it is irrelevant.  It is still broken even in the most recent update of the formula.  So I was just bumping past the automated check.  I don't see any policies or anything preventing that, so I assumed it would be OK.  If you'd prefer I can just create a new issue.  Let me know.

**Comment by SMillerDev** [comment]
The stalebot isn't just for irrelevant items. It's also for issues that'll never be fixed. This is clearly something nobody was fixing (because they probably don't know how either). You're basically asking homebrew to keep all issues open until the right person for that issue comes along, combs through weeks of issues and finds it. That won't ever happen, you're better of experimenting and fixing it yourself, learning something in the process and maybe even helping other users.
