### ISSUE TITLE
R switched to built with openblas

### ISSUE THREAD

**Issue by kiendang** [Homebrew/homebrew-core#37898]
[R](https://github.com/Homebrew/homebrew-core/blob/master/Formula/r.rb) used to be built with Accelerate framework (similar to the official binary provided by cran), but switched to Openblas in this commit https://github.com/Homebrew/homebrew-core/commit/f9325e5e63ba812d1a2d5fd405811e313f782ff1 which I understand is for removing options. Is it a potential oversight where the wrong default build option was kept?
@fxcoudert

**Comment by SMillerDev** [comment]
A very significant portion of the users seem to have installed it with the option for openblas (almost 10%) so it was clearly popular. Maybe fx can comment if that was the eventual reason.

**Comment by fxcoudert** [comment]
A large fraction of users was using the option, and some BLAS-based packages have been reporting issues with Apple's Accelerate (bugs and crashes). Other large-scale scientific projects have started moving away from Accelerate: https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate

All those factors contributed to me deciding to switch R.

**Comment by kiendang** [comment]
Thanks for clarifying.
