### ISSUE TITLE
homebrew built OS X mplayer is broken

### ISSUE THREAD

**Issue by eltoneo** [Homebrew/homebrew-core#37926]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran ` <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
Hi,
I'm having same OS X mplayer problem as following link:  
[link](https://superuser.com/questions/1364372/how-to-make-mplayer-use-subtitles)
VLC media player displays subtitles, but not homebrew build mplayer, on OS X.
Thanks,
eltoneo

**Comment by eltoneo** [comment]
Hi,
Hitting 'v' key should toggle subtitles ON/OFF.

> 
$ brew info mplayer
mplayer: stable 1.3.0, HEAD
UNIX movie player
https://mplayerhq.hu/
/usr/local/Cellar/mplayer/1.3.0_1 (11 files, 27.7MB) *
  Built from source on 2019-03-13 at 18:02:13
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mplayer.rb
==> Dependencies
Build: yasm ✔
Required: libcaca ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 3,009 (30 days), 8,163 (90 days), 19,524 (365 days)
install_on_request: 2,275 (30 days), 6,300 (90 days), 17,062 (365 days)
build_error: 0 (30 days)
$ 
*******
Thanks,
eltoneo

**Comment by SMillerDev** [comment]
This seems like a feature request to build mplayer with freetype and fontconfig. Unfortunately homebrew only accepts feature requests as pull requests. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#set-up-your-own-fork-of-the-homebrew-repository should help you get started with those. If you have questions, don't be hesitant to ask them on https://discourse.brew.sh/ or in the pull request.

**Comment by eltoneo** [comment]
Hi Sean,
You are mistaken.  Homebrew installs ‘freetype’ and ‘fontconfig’ just fine on their own.  The problem is that homebrew builds mplayer without ‘.SRT’ subtitle file support on OS X and the link I posted pertains to that, as well as what I have observed on my Macbook Pro, too. Therefore my request to you is to build mplayer with srt file support on OS X.
Thanks,
eltoneo

**Comment by eltoneo** [comment]
Hi,
Please reopen #37926 so that srt ‘subtitle’ file support can be added to homebrew mplayer build on OS X.
On linux, key ‘v’ toggles subtitles ON/OFF.
thx
eltoneo
