### ISSUE TITLE
Error building gdk-pixbuf on Amazon's custom Linux they use on EC2

### ISSUE THREAD

**Issue by pmarreck** [Homebrew/homebrew-core#37945]
I'm coding on a stock EC2 Amazon instance, which is Linux (Amazon Linux AMI), here's the output of `uname -a`:
```
$ uname -a
Linux ip-172-31-10-1 4.14.88-72.76.amzn1.x86_64 #1 SMP Mon Jan 7 19:47:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I get the below error while updating Erlang, which then tries to update its dependencies:

==> Installing erlang dependency: gdk-pixbuf
==> Downloading https://download.gnome.org/sources/gdk-pixbuf/2.38/gdk-pixbuf-2.38.1.tar.xz
Already downloaded: /home/ec2-user/.cache/Homebrew/downloads/7c93cc7704e6634fd8c82707948ba6b2987abf5ec6355318b75221c34dc00c9b--gdk-pixbuf-2.38.1.tar.xz
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
gdk-pixbuf/meson.build:
  expected replacement of "  bin = executable(bin_name, bin_source,\n                   dependencies: gdk_pixbuf_deps + [ gdkpixbuf_dep ],\n                   include_directories: [ root_inc, gdk_pixbuf_inc ],\n                   c_args: common_cflags + gdk_pixbuf_cflags,\n                   install: true)" with "  bin = executable(bin_name, bin_source,\n                   dependencies: gdk_pixbuf_deps + [ gdkpixbuf_dep ],\n                   include_directories: [ root_inc, gdk_pixbuf_inc ],\n                   c_args: common_cflags + gdk_pixbuf_cflags,\n                   install: true, install_rpath: '/home/linuxbrew/.linuxbrew/Cellar/gdk-pixbuf/2.38.1/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/python/lib:/home/linuxbrew/.linuxbrew/opt/ncurses/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/gettext/lib:/home/linuxbrew/.linuxbrew/opt/libffi/lib:/home/linuxbrew/.linuxbrew/opt/bzip2/lib:/home/linuxbrew/.linuxbrew/opt/pcre/lib:/home/linuxbrew/.linuxbrew/opt/gdbm/lib:/home/linuxbrew/.linuxbrew/opt/openssl/lib:/home/linuxbrew/.linuxbrew/opt/readline/lib:/home/linuxbrew/.linuxbrew/opt/sqlite/lib:/home/linuxbrew/.linuxbrew/opt/xz/lib:/home/linuxbrew/.linuxbrew/opt/python@2/lib:/home/linuxbrew/.linuxbrew/opt/util-linux/lib:/home/linuxbrew/.linuxbrew/opt/glib/lib:/home/linuxbrew/.linuxbrew/opt/jpeg/lib:/home/linuxbrew/.linuxbrew/opt/libpng/lib:/home/linuxbrew/.linuxbrew/opt/libtiff/lib:/home/linuxbrew/.linuxbrew/opt/libxml2/lib')"

**Comment by pmarreck** [comment]
Additional note: Problem occurs even if I `brew cleanup -s`

I've been getting this error for over a week now and have been unable to update Erlang on my main dev machine as a result.

**Comment by SMillerDev** [comment]
This should be in linuxbrew-core

**Comment by iMichka** [comment]
This should be discussed here: https://github.com/Homebrew/linuxbrew-core/pull/11862
