### ISSUE TITLE
Clang-format version don't work with 

### ISSUE THREAD

**Issue by prsolucoes** [Homebrew/homebrew-core#37964]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Problem:
The formula "clang-format" install a version of clang-format that ignore "CompactNamespaces: true" that put namespaces in one single line as described here:
https://clang.llvm.org/docs/ClangFormatStyleOptions.html#CompactNamespaces

Steps:

1 - brew install clang-format
2 - install ezored from git (ezored.com)
3 - run: ```python make.py clang format```

Result:
The namespace is:
```
namespace ezored
{
namespace data
{
```

Instead of:

```
namespace ezored { namespace data {
```

Can anyone help me?

**Comment by fxcoudert** [comment]
Would that be fixed in version 2019-01-18?

**Comment by prsolucoes** [comment]
My version already is 2019-01-18

**Comment by fxcoudert** [comment]
The version currently in Homebrew core is `2018-12-18`, so you have to report this to where you installed it from.

**Comment by prsolucoes** [comment]
Yes, sorry.

My version is from 2018:

```
Error: clang-format 2018-12-18 already installed
```

How i can install 2019 version?
