### ISSUE TITLE
Broken link for Metasploit

### ISSUE THREAD

**Issue by 0ero1ne** [Homebrew/homebrew-core#37989]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

============================================================

`brew cask install metasploit
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://osx.metasploit.com/metasploit-framework-5.0.10+20190301143738-1rapid7-1.pkg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-5.0.10+20190301143738-1rapid7-1.pkg
`
Won't be able to install Metasploit from Brew.

**Comment by hyuraku** [comment]
@0ero1ne 
Could you submit this issue to [Homebrew-cask](https://github.com/Homebrew/homebrew-cask/issues)?
This is the problem about Homebrew-cask.

**Comment by 0ero1ne** [comment]
Will do, sorry about the confusion.
