### ISSUE TITLE
[BUG] brew.sh (Homebrew 2.0.5-dirty) 

### ISSUE THREAD

**Issue by AndrianD** [Homebrew/homebrew-core#38030]
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:565:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:287:in `block in migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:285:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:285:in `migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:126:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:126:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by SMillerDev** [comment]
Both the wrong place for this pull request and you forgot to fill out the issue template, which makes it impossible to debug.

**Comment by AndrianD** [comment]
> Both the wrong place for this pull request and you forgot to fill out the issue template, which makes it impossible to debug.

Oh sorry, here is the context:
I run this command:
`brew update && brew upgrade && brew cleanup`
and at the end of execution it gives me these error in console.

Thank you very much for your help

**Comment by equal-l2** [comment]
@AndrianD You should open an issue on Homebrew/brew, not here.

**Comment by AndrianD** [comment]
OK,
I move it here:
https://github.com/Homebrew/brew/issues/5896

Thanks @equal-l2  for your suggestions!
