### ISSUE TITLE
Update to v1.8.23 so Homebrew tap pulls the latest version

### ISSUE THREAD

**Issue by rachhunter** [Homebrew/homebrew-core#38062]
The Homebrew tap for Mac users still references go-ethereum v1.8.22 because the file here https://github.com/Homebrew/homebrew-core/blob/master/Formula/ethereum.rb needs an update to v1.8.23. Please update this file.

Refer to Homebrew here: https://formulae.brew.sh/formula/ethereum#default (still references v1.8.22)

**Comment by SMillerDev** [comment]
Homebrew only allows version bumps as pull requests, not as issues. It's pretty easy to fix. Look at https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request for more information

**Comment by rachhunter** [comment]
There's no use doing a pull request on Homebrew if the file in Github isn't updated, right?

Updating the file to reference 'v1.8.23' in a Github pull request is easy enough, but do the 'sha256' values need to change too? Where do they come from?

**Comment by SMillerDev** [comment]
Homebrew's information is in github, changing it will change homebrew. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula has the command you need to update both the version and the SHA hash. If that doesn't work for some reason, the SHA is just the hash of the downloaded file.

**Comment by rachhunter** [comment]
@BrewTestBot Is this something you could apply your expertise to please. :-)

**Comment by SMillerDev** [comment]
That's a bot, it doesn't actually have any expertise. It just performs some actions based on a predefined set of conditions.

**Comment by fxcoudert** [comment]
Version 1.8.23 was not incorporated into Homebrew because of a bug. See https://github.com/Homebrew/homebrew-core/pull/37575 and https://github.com/ethereum/go-ethereum/issues/19173

We will try the next version when it is released, hopefully the bug will be fixed by then.

**Comment by rachhunter** [comment]
Thanks @fxcoudert - that's good to know.
