### ISSUE TITLE
zxing-cpp segfaults with --search-multi

### ISSUE THREAD

**Issue by kousu** [Homebrew/homebrew-core#38082]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I want to be able to do I/O with QR codes. `brew install qrencode` works great, but `zxing` is giving me trouble, specifically

```
$ brew install zxing-cpp
$ zxing --search-multi code.png
Segmentation fault: 11
```

on

![code](https://user-images.githubusercontent.com/987487/54658705-29a13200-4aa5-11e9-8aa9-70956654e6ed.png)

Using an image without a QR code in it doesn't cause this:
```
$ zxing -v --search-multi table.png 
Hybrid binarizer failed: zxing::ReaderException: No code detected
Global binarizer failed: zxing::ReaderException: No code detected
```

![table](https://user-images.githubusercontent.com/987487/54658710-2c9c2280-4aa5-11e9-8dd0-a1a97239cf9f.png)

And not using --search-multi works fine:

```
$ zxing -v code.png 
Hybrid binarizer succeeded: 
    {2-3}LZ7BDOso7qsr7cs0MV5NDQPYxEVeCMxsupw5zFGQf4GBn3u+nOcRjmKZT6UZO886fmqy/i6NTuUlc+otO6ZlpvXEVc0Dfvw1G+2s/zKElUi552dZv8bDvP88q89DmylL4bu6mtzTUKaDr+GI4WgoTZ
Global binarizer succeeded: 
    {2-3}LZ7BDOso7qsr7cs0MV5NDQPYxEVeCMxsupw5zFGQf4GBn3u+nOcRjmKZT6UZO886fmqy/i6NTuUlc+otO6ZlpvXEVc0Dfvw1G+2s/zKElUi552dZv8bDvP88q89DmylL4bu6mtzTUKaDr+GI4WgoTZ
```

```
$ zxing -v table.png 
Hybrid binarizer failed: zxing::ReaderException: No code detected
Global binarizer failed: zxing::ReaderException: No code detected
```

I expect: this not to segfault.

This showed up when trying to use python-zxinglight because that wrapper *always* uses multi mode: https://github.com/lubo/zxinglight/issues/5.

I tried rebuilding from scratch (https://github.com/glassechidna/zxing-cpp/issues/74#issuecomment-474677200) and got a different error:

```
$ ./zxing -v --search-multi code.png 
Hybrid binarizer failed: zxing::IllegalArgumentException: This luminance source does not support cropping.
Global binarizer failed: zxing::IllegalArgumentException: This luminance source does not support cropping.
```

So I don't know if https://github.com/Homebrew/homebrew-core/blob/master/Formula/zxing-cpp.rb is pointing at an older commit (it doesn't look like it to me?) or what.

-----

```
$ brew config
HOMEBREW_VERSION: 2.0.5-10-g15495f0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 15495f0bde38eed7dd2869601833f07fbf7b03a4
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d7538ec535e1aa86627238e744e62fedcd6e9f66
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.lZboGoNFA9/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/kousu/Library/Logs/Homebrew
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
^[[AGit: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.3-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libdino.0.0.dylib
  /usr/local/lib/libqlite.0.1.dylib
  /usr/local/lib/libxmpp-vala.0.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/dino.h
  /usr/local/include/dino_i18n.h
  /usr/local/include/qlite.h
  /usr/local/include/xmpp-vala.h

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  numpy
```

**Comment by fxcoudert** [comment]
Actually, it looks like `zxing-cpp` is not maintained/supported anymore. We're shipping 2.3.0, dated 29 November 2013, and the cpp part was removed in the next release (3.0.0):

> iphone/, cpp/, objc/, and glass-mirror/ are retired

Removal from Homebrew core proposed in https://github.com/Homebrew/homebrew-core/pull/38088
