### ISSUE TITLE
Openssl Header files not installed

### ISSUE THREAD

**Issue by jshaker000** [Homebrew/homebrew-core#38098]
I am working on doing development with the C API for openSSL. When I install the openssl package, the C headers are not installed to either /usr/include or /usr/local/include.  
I don't know if this is intentional or not, but I would appreciate it if brew included this files OR offered a development package for openssl so I can have parity with my linux boxes.

I am running on High Sierra

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
