### ISSUE TITLE
brew upgrade node (v11.12.0) failure

### ISSUE THREAD

**Issue by ChildrenGreens** [Homebrew/homebrew-core#38116]
`log:`
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "node"
Download failed: https://homebrew.bintray.com/bottles/node-11.12.0.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.

**Comment by SMillerDev** [comment]
Not a brew issue and didn't fill out the issue template but bintray is having issues: https://status.bintray.com/

**Comment by SMillerDev** [comment]
Not a brew issue and didn't fill out the issue template but bintray is having issues: https://status.bintray.com/
