### ISSUE TITLE
Missing formula for libssh2-1-dev

### ISSUE THREAD

**Issue by VitaliiIsaenko** [Homebrew/homebrew-core#38123]
I faced [the issue](https://stackoverflow.com/questions/55263324/install-ssh2-extension-having-homebrew-and-php-7-3/55276806?noredirect=1#comment97284873_55276806) after updating my project that requires ssh2 extension to php 7.3 with `brew install php`.   
It would be great if we had the `libssh2-1-dev` formula mentioned in the answer to my question on SO in homebrew! As I think more and more people will face the problem.  
Thank you!

Related links:  
https://github.com/docker-library/php/issues/767  
https://stackoverflow.com/questions/561024/install-pecl-ssh2-extension-for-php

**Comment by SMillerDev** [comment]
The first two lines of the issue template are in direct contradiction with this issue. I'm closing it for exactly those reasons.

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

> - [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

**Comment by fxcoudert** [comment]
Homebrew core formula `libssh2` includes development files.
