### ISSUE TITLE
[i3lock]Error: No formulae found in taps

### ISSUE THREAD

**Issue by mikhailbaum** [Homebrew/homebrew-core#38145]
Hello guys,
I'm trying to install i3lock on my mac. So I tried to type
 
brew install i3lock

What I see next

Error: No available formula with the name "i3lock" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

What I can do with it?

**Comment by SMillerDev** [comment]
It's not available but maybe you can add it for everyone looking for it, you can use the documentation on docs.brew.sh for that. Unfortunately I'll have to close this issue as it doesn't follow the issue template rules.
