### ISSUE TITLE
Please provide llvm@7

### ISSUE THREAD

**Issue by arthaud** [Homebrew/homebrew-core#38141]
Hi everyone,

Since Homebrew now provides LLVM 8, could you please provide `llvm@7`, the same way you provide `llvm@4`, `llvm@5` and `llvm@6`?

Thank you

**Comment by arthaud** [comment]
Sorry, I just saw https://github.com/Homebrew/homebrew-core/pull/38139

**Comment by SMillerDev** [comment]
In the issue template you removed it says that requests for formula are only accepted as pull requests.
