### ISSUE TITLE
llvm@7 missing from tap

### ISSUE THREAD

**Issue by paulohefagundes** [Homebrew/homebrew-core#38148]
Ok, the formula for **llvm** was recently upgraded from 7 to 8 #38093 

The problem is that there's no **llvm@7** for users who are using that in their builds.

you can see the issue by doing `brew search llvm`. You'll notice that `llvm@7` is not listed there

I'm no expert, but I think the fix would be to copy of the old (prior to 8.0) `Formula/llvm.rb to` -> `Formula/llvm@7.rb`

**Comment by SMillerDev** [comment]
Please follow the issue template, it (among other things) states that all formula requests should be done as a pull request.

**Comment by paulohefagundes** [comment]
sorry about that, it looks like #38139 is already opened thanks
