### ISSUE TITLE
Current icecream 1.2 icecc-create-env script fails if path to pre-built clang 7.0 or 8.0 is relative

### ISSUE THREAD

**Issue by jwatt** [Homebrew/homebrew-core#38187]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [*] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [*] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Trying to create a toolchain for icecc from the clang 7.0 or 8.0 pre-built binaries from the clang website I ran:

```
wget http://releases.llvm.org/8.0.0/clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
tar xvf clang+llvm-8.0.0-x86_64-apple-darwin.tar.xz
/usr/local/Cellar/icecream/1.2/libexec/icecc/icecc-create-env --clang ./clang+llvm-8.0.0-x86_64-apple-darwin/bin/clang /usr/local/Cellar/icecream/1.2/libexec/icecc/compilerwrapper
```

This almost completes successfully, but just before the end this happens:

```
<snip>
adding file /usr/lib/dyld
adding file /usr/bin/gcc
adding file /usr/bin/g++
cp: /usr/bin/clang=clang+llvm-7.0.0-x86_64-apple-darwin/bin/clang: No such file or directory
md5: /tmp/iceccenvXpgCqn/usr/bin/clang=clang+llvm-7.0.0-x86_64-apple-darwin/bin/clang: No such file or directory
creating e73d7f938c400c359d12d935b3fc67a3.tar.gz
tar: usr/bin/clang=clang+llvm-7.0.0-x86_64-apple-darwin/bin/clang: Cannot stat: No such file or directory
tar: Error exit delayed from previous errors.
Couldn't create archive
```

It seems that the path to `clang+llvm-8.0.0-x86_64-apple-darwin/bin/clang` specified to ice-cc-create-env needs to be an absolute path to avoid this error.

This gotcha could be removed if this script would fix up a relative path to an absolute path to use internally.

Filing this here since this didn't happen to me on Fedora, so presumably it's an issue with Homebrew customizations?

**Comment by fxcoudert** [comment]
We basically run `configure --enable-clang-wrappers && make install`, so I don't think there is anything Homebrew-specific in our configuration. You'll probably find better support asking upstream.

**Comment by jwatt** [comment]
Okay, thanks.
