### ISSUE TITLE
404 Error for ffmpeg

### ISSUE THREAD

**Issue by SheinH** [Homebrew/homebrew-core#38219]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/SheinH/f5c98a0ff93f2586a9045010d90b2be1

Simple error, the ffmpeg bottle version 4.1.2 gives a 404 error. 

https://homebrew.bintray.com/bottles/ffmpeg-4.1.2.mojave.bottle.tar.gz

**Comment by fxcoudert** [comment]
This is working from where I am, and the bottle link is not 404.
Bintray has been having some hiccups earlier, maybe that's it: https://status.bintray.com
Otherwise, a network error on your end.

**Comment by SheinH** [comment]
Oh the link is working again. It most likely was the bintray server problems that caused the 404.
