### ISSUE TITLE
Wine bottle is broken

### ISSUE THREAD

**Issue by wirelyre** [Homebrew/homebrew-core#38253]
# Checklist

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] ~~have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.~~
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ~~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~
- [X] ~~if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~~

# Environment

- macOS Mojave (10.14.3)
- APFS (case-sensitive)
- brew is in `/usr/local`

```
$ brew install wine --force-bottle
==> Downloading https://homebrew.bintray.com/bottles/wine-4.0.sierra.bottle.tar.gz
==> Pouring wine-4.0.sierra.bottle.tar.gz
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/wine/4.0/libexec/bin/fc-cache -frv
==> Caveats
You may also want winetricks:
  brew install winetricks
==> Summary
🍺  /usr/local/Cellar/wine/4.0: 8,989 files, 656.4MB
```

# Error

```
$ wine explorer
dyld: Library not loaded: /usr/local/Cellar/wine/4.0/lib/libwine.1.dylib
  Referenced from: /usr/local/Cellar/wine/4.0/lib/../bin/wineserver
  Reason: no suitable image found.  Did find:
	/usr/local/Cellar/wine/4.0/lib/libwine.1.dylib: mach-o, but wrong architecture
	/usr/local/Cellar/wine/4.0/lib/libwine.1.dylib: stat() failed with errno=1
	/usr/local/lib/libwine.1.dylib: mach-o, but wrong architecture
	/usr/local/Cellar/wine/4.0/lib/libwine.1.0.dylib: mach-o, but wrong architecture
	/usr/local/Cellar/wine/4.0/lib/libwine.1.0.dylib: mach-o, but wrong architecture

$ file /usr/local/Cellar/wine/4.0/{bin/wine,bin/wineserver,lib/libwine.1.0.dylib}
/usr/local/Cellar/wine/4.0/bin/wine:              Mach-O executable i386
/usr/local/Cellar/wine/4.0/bin/wineserver:        Mach-O 64-bit executable x86_64
/usr/local/Cellar/wine/4.0/lib/libwine.1.0.dylib: Mach-O dynamically linked shared library i386
```

Evidently `wineserver` is built 64-bit but links to `lib/libwine.1.dylib` instead of `lib64/libwine.1.dylib`.

**Comment by wirelyre** [comment]
It turns out all libraries in `lib64` also link to `lib/libwine.1.dylib`.

One quick fix is to replace the `lib` directory and use the `wine64` binary directly:

```sh
pushd /usr/local/Cellar/wine/4.0
mv lib lib32
mkdir lib
cp lib64/*.dylib lib
popd

wine64 explorer
```

It's also possible to relink the objects:

```sh
pushd /usr/local/Cellar/wine/4.0
find lib64 -type f -name '*.so' -exec \
     install_name_tool -change /usr/local/Cellar/wine/4.0/{lib,lib64}/libwine.1.dylib {} \;
sudo install_name_tool -change /usr/local/Cellar/wine/4.0/{lib,lib64}/libwine.1.dylib bin/wine64
sudo install_name_tool -change /usr/local/Cellar/wine/4.0/{lib,lib64}/libwine.1.dylib bin/wineserver
popd

wine explorer
```

**Comment by wirelyre** [comment]
A much cleaner method is to create a universal binary (with both architectures).

```sh
pushd /usr/local/Cellar/wine/4.0
lipo {lib,lib64}/libwine.1.dylib -create -output lib/libwine.1.dylib
popd

wine explorer
```

**Comment by zbeekman** [comment]
@wirelyre any chance you could open up a PR for the `lipo` approach?

The latest wine bottle runs, but creates a bunch of errors.

(Also, please confirm that this is still an issue with the latest bottle.)

**Comment by wirelyre** [comment]
@zbeekman Appears to have been fixed in 4.0_1 by correct `rpath`s. 🎉 

I can still make a PR if necessary, otherwise I'll close this issue once I've tried loading the binary in a few more ways.

**Comment by zbeekman** [comment]
Wine seemed to produce fewer errors/warnings for me when I ran the `lipo` command you suggested. That could be a good post install step. Please experiment and see if it's worth doing. If you're satisfied, then please go ahead and close this ticket.

**Comment by zbeekman** [comment]
@wirelyre are you going to submit a PR to add the `lipo` step to the build?

I'm closing this issue because the original problem seems to be fixed.

**Comment by wirelyre** [comment]
Sorry, I got sidetracked by my cross compiler.

I couldn't find any scenario where launching a process is affected by the `lipo` step. It's still possible that it might fix something I couldn't check, like `LoadLibrary` in a user executable, but that seems pretty unlikely — most platforms separate 64-bit and 32-bit objects anyway, and they load both just fine.

Thanks for your time!
