### ISSUE TITLE
could not import gdal on jupyter notebook (mac os sierra 10.12.6)

### ISSUE THREAD

**Issue by quangnrds** [Homebrew/homebrew-core#38318]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
run brew update and upgrade and brew reinstall gdal following the Marquardt's advice.
- What happened (include command output)
the result shows that seem ok but still could not import gdal on jupyter notebook with mac os sierra 10.12.6.
<img width="620" alt="brewInfo_again" src="https://user-images.githubusercontent.com/32257024/55010688-32e74d00-5017-11e9-9ed8-491d61e117dd.png">
 
- What you expected to happen
finding the cause and fix it in order to import gdal on jupyter notebook
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by SMillerDev** [comment]
How did you install jupyter notebook?

**Comment by quangnrds** [comment]
Hi, 
I do not remember exactly because it was around 2 years ago. The way I open JN in virtualenv is:
"Source ./py3_ven/bin/activate" Actually, Gdal is the first one does not work on my JN, I've used quite a lot of libraries without any error.
Please give me some advice!
Thanks so much!
Cheers,
Quang

**Comment by SMillerDev** [comment]
Afaik virtualenv doesn't actually use anything in homebrew and just ships their own python versions. This would mean that it's a virtualenv issue instead.

**Comment by cmarquardt** [comment]
Well,

the virtual environment has links pointing to whatever is the user's python installation. If that's the one from homebrew, it will use homebrew's python.

@quangnrds - how did you create the virtual environment? As far as I remember, the default is to not include python modules which are installed system-wide. Thus, you have to install python modules you need, say with `pip`. If you install some homebrew software, especially after you've created the virtual environment, you probably won't see it in the virtual environment.

You could do the following:

 - deactivate the virtualenv
 - run python and try to import gdal. Does that work? Then you know if gdal is installed. If it doesn't work, your gdal installation from homebrew is probably broken.

If gdal works outside of your virtualenv, switch into your virtualenv. If importing it doesn't work, you could try

    pip install gdal

*inside* the virtualenv and try again - as far as I understand, this installs the python bindings of gdal, but requires an installation of actual library in the system.

**Comment by quangnrds** [comment]
hi,
Thank you very much for your clear explanation.
Yes I remembered that I've installed some homebrew software before but did not know well at that time I began with Python. You know how to check?
I've just tried running python3 outside virtualenv to import GDAL and did new installation for anaconda3, launched Jupyter notebook to import GDAL but both are unsuccessful.
I also did "pip install gdal" inside virtualenv and it said "Failed building wheel for gdal", could you please have a look and help me to solve this issue.
Thanks so much!
Cheers,
Quang
<img width="633" alt="FailedBuuildingWheelGDAL2" src="https://user-images.githubusercontent.com/32257024/55051686-d6bd1100-5088-11e9-8919-98fe1c0ca7fd.png">
<img width="573" alt="FailedBuuildingWheelGDAL1" src="https://user-images.githubusercontent.com/32257024/55051687-d6bd1100-5088-11e9-934a-392a448857a8.png">

**Comment by cmarquardt** [comment]
Oh. You are using anaconda for Python?

The thing is: You can use Homebrew and Anaconda in parallel. However, when it comes to modules for Python, you very likely have to stay in one ecosystem. In your case that means that if you want to use gdal with Anaconda's python, you should install gdal from Anaconda - using the homebrew gdal won't work because Anaconda doesn't even know it's there. So maybe try

    conda install gdal

If that still doesn't work, you should contact the Anaconda help channels; the homebrew people really can't help with Anaconda.

Sorry I can't help more...

**Comment by quangnrds** [comment]
Hi Marquardt,
Thank you very much for your time and your kind. I have successfully launched gdal following your guide ;)
Best,
Quang

**Comment by cmarquardt** [comment]
I'm glad it worked!

**Comment by cmarquardt** [comment]
Hey,

I think this can be closed for a long time - could one of the maintainers be so kind?

Thanks.
