### ISSUE TITLE
shipping  botteled libmatio-1.5.12 compiled against hdf5 1.10.4 not 1.10.5

### ISSUE THREAD

**Issue by massich** [Homebrew/homebrew-core#38320]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I am using `matio` client code and I get an error saying that headers and library missmatch. I can reproduce it in several machines (also travis)

**Comment by SMillerDev** [comment]
Are you saying that matio points to the wrong version of hdf5?

**Comment by fxcoudert** [comment]
@massich Since you did not fill the required information, so it's hard to know exactly what you're doing, and how it fails:

- which formula? we have no `matio`, is it `libmatio`?
- what is the `gist-logs`, or `brew config` and `brew doctor` output?
- what are the versions of `hdf5` and `libmatio` you have installed?
- what command are you running?
- what is the exact error message?

And, although it was not part of the template:
- if you run `brew reinstall -s libmatio`, does it fix your issue?

**Comment by massich** [comment]
reinstalling from source does work. I guess that this means that we need to fix the shipping.

**Comment by massich** [comment]
apart from that matio stable release is 1.5.14 I guess it would be good to setup a repo with CI that checks all this to easily open PRs. Maybe with github actions or something. Are you aware of any project doing something like this?

**Comment by fxcoudert** [comment]
We already do this: when `hdf5` is rebuilt, all formulas that depend on it have their linkage checked and their test run. So this means that the `libmatio` test is not good enough.

Could you think of a better test, and open a pull request with a revision bump please?
