### ISSUE TITLE
Octave 5.1.0 fails to install struct and parallel packages from sourceforge

### ISSUE THREAD

**Issue by sunilshah** [Homebrew/homebrew-core#38358]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

octave 5.1.0 installs fine on Mac OS 10.13.6 using brew.  octave package control installs fine from sourceforge. 

However, octave packages struct and parallel fail to install from sourceforge.  This is possibly an issue with sourceforge code updates for compatibility with the octave version 5.1.0.    

A possible (untested) workaround may be to install the latest developmental versions rather than the released sourceforge version. 

I am posting it here so that other users know about the issue until it is fixed.  

In octave 
~~~~
> pkg install -forge struct 
fails with 

./error-helpers.h:31:22: error: unknown type name 'octave_execution_exception'; did you mean 'octave::execution_exception'?
void c_verror (const octave_execution_exception&, const char *, ...);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~
                     octave::execution_exception
/usr/local/Cellar/octave/5.1.0/include/octave-5.1.0/octave/errwarn.h:35:9: note: 'octave::execution_exception' declared here
  class execution_exception;
        ^
error-helpers.cc:36:17: error: unknown type name 'octave_execution_exception'; did you mean 'octave::execution_exception'?
c_verror (const octave_execution_exception&, const char *fmt, ...)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
                octave::execution_exception
/usr/local/Cellar/octave/5.1.0/include/octave-5.1.0/octave/errwarn.h:35:9: note: 'octave::execution_exception' declared here
  class execution_exception;
        ^
error-helpers.cc:60:8: error: no member named 'cerr' in namespace 'std'
  std::cerr << msg;
  ~~~~~^
3 errors generated.
make: *** [error-helpers.o] Error 1
CXXFLAGS="-I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home/include/darwin -Wno-deprecated-declarations" /usr/local/Cellar/octave/5.1.0/bin/mkoctfile-5.1.0 -c error-helpers.cc

pkg: error running `make' for the struct package.
error: called from
    configure_make at line 99 column 9
    install at line 184 column 7
    pkg at line 441 column 9

octave:4> pkg install -forge parallel

pserver.cc:172:13: error: use of undeclared identifier 'command_editor'; did you mean 'octave::command_editor'?
            command_editor::increment_current_command_number ();
            ^~~~~~~~~~~~~~
            octave::command_editor
/usr/local/Cellar/octave/5.1.0/include/octave-5.1.0/octave/../octave/cmd-edit.h:39:3: note: 'octave::command_editor' declared here
  command_editor
  ^
pconnect.cc:536:35: error: use of undeclared identifier 'octave_env'
          std::string directory = octave_env::get_current_directory ();
                                  ^
pserver.cc:1119:23: error: use of undeclared identifier 'octave_env'
          int cd_ok = octave_env::chdir (directory.c_str ());
                      ^
pserver.cc:1122:13: error: use of undeclared identifier 'octave_env'
            octave_env::chdir ("/tmp");
            ^
1 error generated.

**Comment by SMillerDev** [comment]
This should be reported to upstream. Brew can't do anything about this as homebrew only ships tagged releases.
