### ISSUE TITLE
Brewing CPUMiner-OPT

### ISSUE THREAD

**Issue by Tomcatt** [Homebrew/homebrew-core#38384]
Was trying to install the latest version of cpuminer-opt 3.8.8.1

Typing in:
brew install cpuminer-opt
returns:
Error: cpuminer-opt is a head-only formula
Install with `brew install --HEAD cpuminer-opt`

So I type in the following:
brew install --HEAD cpuminer-opt

Then I get the next error:
==> Cloning https://github.com/JayDDee/cpuminer-opt.git
Updating /Users/bluecheese/Library/Caches/Homebrew/cpuminer-opt--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at bfd1c00 v3.8.8.1
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/cpuminer-opt/HEAD-bfd1c00
Last 15 lines from /Users/bluecheese/Library/Logs/Homebrew/cpuminer-opt/01.configure:
2019-03-27 00:09:15 -0700

./configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/usr/local/Cellar/cpuminer-opt/HEAD-bfd1c00

configure: WARNING: unrecognized options: --disable-debug
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."

READ THIS: https://docs.brew.sh/Troubleshooting

I'm not too sure how homebrew works compared to full Linux system so I'm not sure how to fix this myself.

**Comment by SMillerDev** [comment]
That's not a homebrew-core formula. You can check where you got it from using `brew info cpuminer-opt`. But I can't really help you debug cause it's not maintained by homebrew as an organization.
