### ISSUE TITLE
Passenger 6.0.2 ngx_http_passenger_module.so is not compatible with nginx 1.15.10

### ISSUE THREAD

**Issue by syakovyn** [Homebrew/homebrew-core#38391]
**passenger 6.0.2_1** is bundled with **ngx_http_passenger_module.so** built against **nginx 1.15.9** but the latest **nginx is 1.15.10**.

Error message when starting nginx:
_module “/usr/local/opt/passenger/libexec/modules/ngx_http_passenger_module.so” version 1015009 instead of 1015010 in /usr/local/etc/nginx/nginx.conf_

The build of **passenger** from sources after installing nginx fails (log attached):
_brew reinstall --build-from-source passenger_

[01.rake.txt](https://github.com/Homebrew/homebrew-core/files/3013102/01.rake.txt)

**Comment by CamJN** [comment]
Just like last time I'm surprised this wasn't caught by the test, in my testing locally, nginx -t -c ./nginx.conf fails if the passenger module was built against the wrong nginx. (fails here meaning it writes to stderr and returns non-zero). Is there something more I need to assert for it to fail? I just copied the nginx test and added the passenger module load and some passenger directive to ensure that it does indeed load the module.

I'm not sure about how exactly the homebrew CI determines which formulae to test when another formula changes, maybe the passenger test wasn't run at all?

**Comment by syakovyn** [comment]
The issue with build from sources seems to be related to https://github.com/boostorg/atomic/issues/15.

**Comment by CamJN** [comment]
ok i need to update the vendored boost, but that doesn't explain the test thing

**Comment by CamJN** [comment]
BTW releasing a new Passenger is blocked on https://github.com/rvm/rvm/issues/4465, so I might need to backport a patch to the homebrew formula.

**Comment by CamJN** [comment]
https://github.com/Homebrew/homebrew-core/pull/38435

**Comment by cefigueiredo** [comment]
I have nginx 1.15.11 and installing passenger with `brew install passenger --build-from-source` fixed the wrong module.

**Comment by CamJN** [comment]
Yes, the homebrew formula is seemingly blocked on getting a patch landed that allows compilation on the latest llvm. They don't like the big backported boost patch needed to get the latest passenger compiling so there's nothing to do but wait for the next passenger release which is itself blocked on the next rvm release.
