### ISSUE TITLE
Must I uninstall a formula prior to testing it?

### ISSUE THREAD

**Issue by mattdipasquale** [Homebrew/homebrew-core#3840]
Should I first `brew uninstall foo` before following the steps to [contribute a fix to the `foo` formula][1]?

  [1]: https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md#contribute-a-fix-to-the-foo-formula

**Comment by DomT4** [comment]
Sometimes. If you're making minor style changes only, not generally. If you're rewriting a test, not generally. If you're making changes that impact how a formula is built/installed _(installing a new file, removing a current file, version bumps, etc)_, yes.

Hope that helps! Feel free to leave another comment if there's anything more specific you had in mind.

**Comment by mattdipasquale** [comment]
OK. Thank you. :-)
