### ISSUE TITLE
I cannot set the baud rate when using socat in OSX

### ISSUE THREAD

**Issue by Mon-ius** [Homebrew/homebrew-core#38474]
## Hardware

- MACOS 10.14.3 (18D109)

## Target 

- debug usb serial device using socat with 115200 baud rate.
- `socat -v -x - /dev/ttyACM0,raw,nonblock,echo=0,crnl,b115200`

It works fine in Linux, but I have to connect to the raspberry pi.
If anybody know how to do it with macOS? 

## Addition

I also try to set the stty rate with `stty -f /dev/cu.usbmodem14101 115200` in mac. 

But it will be reset if I start a socat session.

Another stupid but effective is using `echo`, `tail`, and `cat`.

It likes:
-  `stty -f /dev/cu.usbmodem14101 115200`
- `cat /dev/cu.usbmodem14101 > /tmp/serial_stupid`
- `tail -f /tmp/serial_stupid`
In another terminal window, 
-  `stty -f /dev/cu.usbmodem14101 115200`
- `echo -ne "AT\r\n" > /dev/cu.usbmodem14101`

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

In addition to that this seems like something that the developers of socat are much better suited to debug.

**Comment by Mon-ius** [comment]
But there seemed no one maintain the socat anymore. You can just try` brew install socat` in osx. Then try any serial device from `ls -al /dev/cu.*`.

In my situation is: 
```
ls -al /dev/cu.*
crw-rw-rw-  1 root  wheel   20,   1 Mar 27 20:58 /dev/cu.Bluetooth-Incoming-Port
crw-rw-rw-  1 root  wheel   20,  71 Mar 29 11:26 /dev/cu.usbmodem143201
crw-rw-rw-  1 root  wheel   20,  69 Mar 29 11:40 /dev/cu.usbserial-FTFMMPHX
```

Then use socat with the `b115200` option like:
```

socat -v,-x -  /dev/cu.usbserial-FTFMMPHX,raw,nonblock,echo=0,b115200,crnl
2019/03/29 11:50:26 socat[57290] E parseopts(): unknown option "b115200"
```

Also the `ospeed` and `ispeed` like:
```
socat -v,-x -  /dev/cu.usbserial-FTFMMPHX,raw,nonblock,echo=0,crnl,ispeed=115200,ospeed=115200
2019/03/29 11:51:43 socat[57761] E tcsetattr(5, TCSADRAIN, 0x7ffeebbc9bd0): Invalid argument
```

Hope it's the debug information you want.

**Comment by iMichka** [comment]
If there is nobody maintaining it, this is another problem. We can’t do anything about that. We only provide the package as-is, with only limited support. The Oscar developers are the only one who can help you.

In the long term, if nobody maintains it, we may even need to remove the package from Homebrew.

If I was you, i would maybe even look for an alternative to socat, if you can not get any support from upstream.
