### ISSUE TITLE
brew install gdb with python 3 does not build

### ISSUE THREAD

**Issue by amrit-poudel** [Homebrew/homebrew-core#38566]
I am unable to build gdb 8.2 in mac osx mojave 10.14.3 (with gcc 8.2) using python3.7.

python3 was installed using brew install python3 and is in the PATH. 

Using brew edit gdb, 
I have changed --with-python=/usr to /path/to/python3
Also, added
ENV['CFLAGS']='-I/path/to/python3/include'
ENV['CC']='gcc'
ENV['CXX']='g++'

I keep getting missing <Python.h> and <frameobject.h> related error even after including CFLAGS.

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
