### ISSUE TITLE
brew reinstall open-mpi | make command fails

### ISSUE THREAD

**Issue by AmrMKayid** [Homebrew/homebrew-core#38574]
I was trying to reinstall **open-mpi** but the installations failed when applying make command as indicated in the attached photo

<img width="1058" alt="Screen Shot 2019-04-01 at 2 45 32 PM" src="https://user-images.githubusercontent.com/18689888/55329357-aad9cb00-548e-11e9-86fb-34e1d52a6420.png">

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
