### ISSUE TITLE
Can not open commit history.

### ISSUE THREAD

**Issue by sai8786** [Homebrew/homebrew-core#38595]
Github can not load commit history and errors out saying its taking too long. 

Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by jonchang** [comment]
Please always fill out the issue template. You'll have to use e.g. `brew log <formula>` instead.
