### ISSUE TITLE
c++ issue: '_Atomic' does not name a type

### ISSUE THREAD

**Issue by gdolsson** [Homebrew/homebrew-core#38607]
I'm trying to compile some software and I am running into this error:

CXX StringRoutines.cpp
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83,
                from StringRoutines.cpp:14:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
 _Atomic u_long          cr_ref;  /* reference count */
 ^~~~~~~
make[4]: *** [StringRoutines.o] Error 1
make[3]: *** [install] Error 2
make[2]: *** [build_cpptraj] Error 2
make[1]: *** [serial] Error 2
make: *** [install] Error 2

After some digging around it seems that this is caused by some c++ related issue, technically I guess it is an macOS issue though anyway:
https://apple.stackexchange.com/questions/355049/compilation-error-with-mojave-error-atomic-does-not-name-a-type

And apparently the source code needs to be patched to build properly on macOS 10.14:
https://gist.github.com/eschnett/f912c6b791e29c83477575017271db16

Could you please apply this patch and push so that the homebrew version of gcc works properly again?

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
