### ISSUE TITLE
Unsupported special dependency :maximum_macos

### ISSUE THREAD

**Issue by anx1ang** [Homebrew/homebrew-core#38603]
➜  wzw brew update
Fast-forwarded master to origin/master.
Updated 1 tap (homebrew/core).
==> Updated Formulae
apache-arrow                            apache-arrow-glib                       atomist-cli                             rakudo-star                             ruby-build                              vert.x
Error: Unsupported special dependency :maximum_macos
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:128:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/compat/dependency_collector.rb:63:in `parse_symbol_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:96:in `parse_spec'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:52:in `build'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `block in fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:39:in `fetch'
/usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:29:in `add'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:165:in `depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `block in depends_on'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2211:in `depends_on'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:24:in `<class:Wine>'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/wine.rb:7:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:27:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:47:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:102:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:239:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:93:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:89:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:229:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:280:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:311:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:294:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1386:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `each'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `flat_map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1384:in `installed'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:506:in `migrate_formula_rename'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:101:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

macos 10.14.3 (18D109)

**Comment by jonchang** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
