### ISSUE TITLE
Brew upgrade multimarkdown fails

### ISSUE THREAD

**Issue by CCRMaster** [Homebrew/homebrew-core#38618]
I have been trying run brew upgrade multimarkdown however it fails in the linker.
I have the Xcode command line utilities installed OK and I have also done brew update 
and brew upgrade. All other packages upgraded OK only Multimarkdown fails.
I have also been running brew doctor and dealt with some missing or corrupted links.
I have done a brew cleanup, rebooted the Mac and tried to run
brew upgrade multimarkdown multiple times, but always with the same negative result.
I have run brew gist-logs multimarkdown and the resulting gist is here:
https://gist.github.com/CCRMaster/f02ea72bfa4bfd5ce7674dbc6503befc

I suppose there is something simple but I am not able to see what it might be.

**Comment by CCRMaster** [comment]
I see the original run of the brew upgrade multimarkdown command is absent in the gist.
Here is a copy of the command output:
bash-3.2$ brew upgrade multimarkdown
==> Upgrading 1 outdated package:
multimarkdown HEAD-193c09a -> HEAD-193c09a
==> Upgrading multimarkdown 
==> Cloning https://github.com/fletcher/MultiMarkdown-6.git
Updating /Users/admin/Library/Caches/Homebrew/multimarkdown--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 1e633b8 Merge pull request #151 from fletcher/revert-148-convenience-script-PATH
==> make release
==> make
Last 15 lines from /Users/admin/Library/Logs/Homebrew/multimarkdown/02.make:
  "_stdin_buffer", referenced from:
      _main in main.c.o
  "_token_pool_drain", referenced from:
      _main in main.c.o
  "_token_pool_free", referenced from:
      _main in main.c.o
  "_token_pool_init", referenced from:
      _main in main.c.o
  "_unzip_data_to_path", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [multimarkdown] Error 1
make[1]: *** [CMakeFiles/multimarkdown.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you do not read fill out the issue template repeatedly you will be blocked from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.

**Comment by CCRMaster** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I have been trying run 'brew upgrade multimarkdown' on MacOS however it fails in the linker. 
I have the Xcode command line utilities installed OK and I have also done brew update
and brew upgrade. All other packages upgraded OK only Multimarkdown fails.
I have also been running brew doctor and dealt with some missing or corrupted links.
I have done a brew cleanup, rebooted the Mac and tried to run
'brew upgrade multimarkdown' multiple times, but always with the same negative result.
I have run 'brew gist-logs multimarkdown' and the resulting gist is here:
https://gist.github.com/CCRMaster/f02ea72bfa4bfd5ce7674dbc6503befc

To me it seems that the linker does not find the correct library. I have contacted the
developer of Mulitmarkdown, Fletcher T. Penney, who says he has not created the formula
for version 6 on Homebrew. If I look at the formula at:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/multimarkdown.rb
I find no history or trace of who contributed this formula. There has been reported problems
with compiling this version on Mojave, see:
https://github.com/fletcher/MultiMarkdown-6/issues/142
This problem is referred to in the Mulitmarkdown formula, see under 'def install'

My output when running 'brew upgrade multimarkdown' is:
bash-3.2$ brew upgrade multimarkdown
==> Upgrading 1 outdated package:
multimarkdown HEAD-193c09a -> HEAD-193c09a
==> Upgrading multimarkdown 
==> Cloning https://github.com/fletcher/MultiMarkdown-6.git
Updating /Users/admin/Library/Caches/Homebrew/multimarkdown--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 1e633b8 Merge pull request #151 from fletcher/revert-148-convenience-script-PATH
==> make release
==> make
Last 15 lines from /Users/admin/Library/Logs/Homebrew/multimarkdown/02.make:
  "_stdin_buffer", referenced from:
      _main in main.c.o
  "_token_pool_drain", referenced from:
      _main in main.c.o
  "_token_pool_free", referenced from:
      _main in main.c.o
  "_token_pool_init", referenced from:
      _main in main.c.o
  "_unzip_data_to_path", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [multimarkdown] Error 1
make[1]: *** [CMakeFiles/multimarkdown.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
