### ISSUE TITLE
'brew install git' and '>=' error

### ISSUE THREAD

**Issue by ehansler** [Homebrew/homebrew-core#3864]
If anyone could help me it would be greatly appreciated. I am not incredibly knowledgable when it comes to this. Please see attached errors when I try to do a brew update. trying to install wine. please advise and thank you in advance!!

![screen shot 2016-08-13 at 7 41 45 pm](https://cloud.githubusercontent.com/assets/21014805/17646206/2ddb199c-618e-11e6-8658-7503258d2cd0.png)

**Comment by dunn** [comment]
Could you post the output of `brew config` and `brew doctor`, please? Thanks!

**Comment by ehansler** [comment]
I am running on 10.6.8 so i'm trying to use xquartz instead of xcode.
![screen shot 2016-08-13 at 7 52 04 pm](https://cloud.githubusercontent.com/assets/21014805/17646238/b0786732-618f-11e6-9bef-af6f6c3e78a4.png)
![screen shot 2016-08-13 at 7 52 48 pm](https://cloud.githubusercontent.com/assets/21014805/17646239/b07dd37a-618f-11e6-97c0-9bae7a4e7e0a.png)

**Comment by dunn** [comment]
XQuartz is a window manager; it's not a substitute for Xcode.  You need either Xcode or the Command Line Tools in order to use Homebrew.

**Comment by ehansler** [comment]
Thank you for the clarification. Is it possible to get Command Line Tools for 10.6.8? I'm trying to find a version but most sites are telling me to search in the downloads section of xcode, which I obviously cant get due to my outdated operating system.

**Comment by dunn** [comment]
It should be available at https://developer.apple.com/download/more/

**Comment by DomT4** [comment]
IIRC there's no separate Command Line Tools package for 10.6.x. You'll likely have to grab Xcode, which should be `3.2.6` on 10.6.

**Comment by ilovezfs** [comment]
>IIRC there's no separate Command Line Tools package for 10.6.x. You'll likely have to grab Xcode, which should be 3.2.6 on 10.6.

Right, it's an option in the installer.

**Comment by ehansler** [comment]
Thank you for the help from all of you. Still some small problems persisting. Can I just download or mirror something for the MPFR that can't be built? See attached.
![screen shot 2016-08-14 at 12 23 37 pm](https://cloud.githubusercontent.com/assets/21014805/17650390/77ce6608-621a-11e6-943b-79ad1c5a8ecf.png)

**Comment by ilovezfs** [comment]
You may want to try tigerbrew and see if it has the same issue: https://github.com/mistydemeo/tigerbrew

**Comment by MikeMcQuaid** [comment]
I'm afraid we don't support 10.6 so we'll accept pull requests to improve this but aren't able to do so ourselves. Sorry!
