### ISSUE TITLE
Issues with percona-toolkit package

### ISSUE THREAD

**Issue by selfagency** [Homebrew/homebrew-core#38663]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Use `percona-toolkit` after installation. If I manually compile it from source it works fine.

- What happened (include command output)
After successfully installing, any attempt to execute any of the tools produces: `Segmentation fault: 11`

- What you expected to happen
For the app to work without failing

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install percona-toolkit
pt-heartbeat
pt-table-sync
```

```
➜ brew update; brew doctor; brew gist-logs percona-toolkit;
Updated 1 tap (homebrew/cask).
No changes to formulae.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/daniel/.pyenv/shims/python3.7-config
  /Users/daniel/.pyenv/shims/python3.7m-config
  /Users/daniel/.pyenv/shims/python-config
  /Users/daniel/.pyenv/shims/python3-config
  /Users/daniel/Dev/kifa-web/node_modules/.bin/common-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
Error: No logs.

➜ brew config
HOMEBREW_VERSION: 2.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1337da0f891aebb85accb094d63e401da1b53cba
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 581b3142650fc49a6794d494f9260b27dcf95d84
Core tap last commit: 41 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/daniel/Library/Logs/Homebrew
CPU: dodeca-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: 10.2
CLT headers: 10.2.0.0.1.1552586384
```

**Comment by SMillerDev** [comment]
When I execute `pt-heartbeat` or `pt-table-sync` it just prints the help. What happens when you run `brew test percona-toolkit`?

**Comment by selfagency** [comment]
I don't know if there was an update or if it's something I changed on my end but it appears to work now.
