### ISSUE TITLE
Mutt UTF-8 support is broken

### ISSUE THREAD

**Issue by keltia** [Homebrew/homebrew-core#38709]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [*] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew gist-logs mutt:
https://gist.github.com/keltia/41241b153a8c688c44a3855621c941f7

To help us debug your issue please explain:
- What you were trying to do (and why

I upgraded mutt to 1.11.4, opened a mailbox containing mails with diacritics and other UTF-8 characters and now, UTF-8 does not seem to be correctly displayed, both for graphical drawing characters and diacritics (see screenshots).

mutt -v
```
Mutt 1.11.4 (2019-03-13)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 18.2.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libiconv: 1.11
hcache backend: tokyocabinet 1.4.48

Compiler:
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Configure options: '--disable-dependency-tracking' '--disable-warnings' '--prefix=/usr/local/Cellar/mutt/1.11.4' '--enable-debug' '--enable-hcache' '--enable-imap' '--enable-pop' '--enable-sidebar' '--enable-smtp' '--with-gss' '--with-sasl' '--with-ssl=/usr/local/opt/openssl' '--with-tokyocabinet' '--enable-gpgme' 'CC=clang'

Compilation CFLAGS: -g -O2

Compile options:
-DOMAIN
+DEBUG
-HOMESPOOL  +USE_SETGID  +USE_DOTLOCK  +DL_STANDALONE  +USE_FCNTL  -USE_FLOCK
+USE_POP  +USE_IMAP  +USE_SMTP
+USE_SSL_OPENSSL  -USE_SSL_GNUTLS  +USE_SASL  +USE_GSS  +HAVE_GETADDRINFO
+HAVE_REGCOMP  -USE_GNU_REGEX
+HAVE_COLOR  +HAVE_START_COLOR  +HAVE_TYPEAHEAD  +HAVE_BKGDSET
+HAVE_CURS_SET  +HAVE_META  +HAVE_RESIZETERM  +HAVE_FUTIMENS
+CRYPT_BACKEND_CLASSIC_PGP  +CRYPT_BACKEND_CLASSIC_SMIME  +CRYPT_BACKEND_GPGME
-EXACT_ADDRESS  -SUN_ATTACHMENT
+ENABLE_NLS  -LOCALES_HACK  +HAVE_WC_FUNCS  +HAVE_LANGINFO_CODESET  +HAVE_LANGINFO_YESEXPR
+HAVE_ICONV  -ICONV_NONTRANS  -HAVE_LIBIDN  -HAVE_LIBIDN2  +HAVE_GETSID  +USE_HCACHE
+USE_SIDEBAR  -USE_COMPRESSED  -USE_INOTIFY
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/Cellar/mutt/1.11.4/share/mutt"
SYSCONFDIR="/usr/local/Cellar/mutt/1.11.4/etc"
EXECSHELL="/bin/sh"
-MIXMASTER

To contact the developers, please mail to <mutt-dev@mutt.org>.
To report a bug, please contact the Mutt maintainers via gitlab:
    https://gitlab.com/muttmua/mutt/issues
```

- What happened (include command output)

See screenshots.  Output is completely garbled.  It happens with both Terminal.app and iTerm2.
https://www.dropbox.com/s/k67hegs5hmb5wqe/Screenshot%202019-04-05%2012.18.06.png?dl=0
https://www.dropbox.com/s/e3q46n5jf6tsal8/Screenshot%202019-04-05%2012.28.06.png?dl=0

- What you expected to happen

I manually re-compiled mutt from sources and it works perfectly.

See other screenshots.
https://www.dropbox.com/s/i7oxgjui22c94ji/Screenshot%202019-04-05%2012.18.42.png?dl=0
https://www.dropbox.com/s/qdqfaz8406uju7u/Screenshot%202019-04-05%2012.28.27.png?dl=0

```
Mutt 1.11.4 (2019-03-13)
Copyright (C) 1996-2016 Michael R. Elkins and others.
Mutt comes with ABSOLUTELY NO WARRANTY; for details type `mutt -vv'.
Mutt is free software, and you are welcome to redistribute it
under certain conditions; type `mutt -vv' for details.

System: Darwin 18.2.0 (x86_64)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libiconv: 1.11
libidn: 1.35 (compiled with 1.35)
hcache backend: tokyocabinet 1.4.48

Compiler:
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Configure options: '--disable-warnings' '--enable-hcache' '--enable-imap' '--enable-pop' '--enable-sidebar' '--enable-smtp' '--with-sasl' '--with-ssl=/usr/local/opt/openssl' '--with-tokyocabinet' '--enable-gpgme' 'CC=clang' 'CFLAGS=-O2 -pipe'

Compilation CFLAGS: -O2 -pipe

Compile options:
-DOMAIN
-DEBUG
-HOMESPOOL  +USE_SETGID  +USE_DOTLOCK  +DL_STANDALONE  +USE_FCNTL  -USE_FLOCK
+USE_POP  +USE_IMAP  +USE_SMTP
+USE_SSL_OPENSSL  -USE_SSL_GNUTLS  +USE_SASL  -USE_GSS  +HAVE_GETADDRINFO
+HAVE_REGCOMP  -USE_GNU_REGEX
+HAVE_COLOR  +HAVE_START_COLOR  +HAVE_TYPEAHEAD  +HAVE_BKGDSET
+HAVE_CURS_SET  +HAVE_META  +HAVE_RESIZETERM  +HAVE_FUTIMENS
+CRYPT_BACKEND_CLASSIC_PGP  +CRYPT_BACKEND_CLASSIC_SMIME  +CRYPT_BACKEND_GPGME
-EXACT_ADDRESS  -SUN_ATTACHMENT
+ENABLE_NLS  -LOCALES_HACK  +HAVE_WC_FUNCS  +HAVE_LANGINFO_CODESET  +HAVE_LANGINFO_YESEXPR
+HAVE_ICONV  -ICONV_NONTRANS  +HAVE_LIBIDN  -HAVE_LIBIDN2  +HAVE_GETSID  +USE_HCACHE
+USE_SIDEBAR  -USE_COMPRESSED  -USE_INOTIFY
-ISPELL
SENDMAIL="/usr/sbin/sendmail"
MAILPATH="/var/mail"
PKGDATADIR="/usr/local/share/mutt"
SYSCONFDIR="/usr/local/etc"
EXECSHELL="/bin/sh"
-MIXMASTER

To contact the developers, please mail to <mutt-dev@mutt.org>.
To report a bug, please contact the Mutt maintainers via gitlab:
    https://gitlab.com/muttmua/mutt/issues
```

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install mutt
mutt -f <mailbox>

**Comment by fxcoudert** [comment]
Hi @keltia 👋 

> I manually re-compiled mutt from sources and it works perfectly

By that, do you mean “compile from source outside of Homebrew” or “run `brew reinstall -s mutt`”?

**Comment by fxcoudert** [comment]
I have:

```
LANG="fr_FR.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

and I can't reproduce.

**Comment by keltia** [comment]
"Outside of Homebrew" as in `tar xf ; ./configure ; make`

Locale is UTF-8 of course.
```
LC_CTYPE=UTF-8
LANG=en_US.UTF-8
```

**Comment by keltia** [comment]
And `brew reinstall -s mutt` didn't fix it :(
