### ISSUE TITLE
The corsixth program / install seem broken

### ISSUE THREAD

**Issue by Kaganis** [Homebrew/homebrew-core#38789]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Yes ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [Yes ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [Yes ] ran `brew update` and can still reproduce the problem?
- [Yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Yes ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

$ brew gist-logs corsixth
Error: No logs.

$ - [Yes ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

$ brew config
HOMEBREW_VERSION: 2.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1337da0f891aebb85accb094d63e401da1b53cba
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9e64f0318f85c12ce363d6dfe72d3077446e8e2f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_LOGS: /Users/robin/Library/Logs/Homebrew
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: N/A
CLT headers: 10.2.0.0.1.1552586384

$ brew doctor
Your system is ready to brew.

To help us debug your issue please explain:
- What you were trying to do (and why)

Run corsixth.

- What happened (include command output)

Fresh install of corsixth, when run gives the following error & only gives the option of exiting:

$ corsixth
An error has occurred in CorsixTH:
cannot open /usr/local/Cellar/corsixth/0.62/CorsixTH.app/Contents/Resources//CorsixTH.lua: No such file or directory
stack traceback:
	[C]: in function 'assert'
	[C]: in ?

- What you expected to happen

Never run the program before, so not 100% sure, but I believe it asks for the location of the Theme Hospital data files?

- Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install corsixth
(Usual install output)
$ corsixth

**Comment by Kaganis** [comment]
I've also opened an issue with the corsixth GitHub tracker, in case it's a bug their end instead of a packaging issue.  Apologies if that's turns out to be the case.

**Comment by TheCycoONE** [comment]
The issue in our tracker is https://github.com/CorsixTH/CorsixTH/issues/1518
From our perspective this appears to be a packaging issue.

**Comment by jonchang** [comment]
If upstream provides a `.dmg` file then it might be more suitable to just use that and migrate this formula to Homebrew/cask, rather than building a `.app`. We generally don't want formulae that build `.app`s: https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app

**Comment by Kaganis** [comment]
Commenting to mainly stop the stale bot.

Current state: The formula still exists & hasn't been updated.  No cask for corsixth has appeared.

**Comment by SMillerDev** [comment]
The bot is correct and just waiting won't fix the issue. A pull request can be opened to fix this.
