### ISSUE TITLE
ansible add CredSSP support

### ISSUE THREAD

**Issue by jkroepke** [Homebrew/homebrew-core#38795]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
try to establish a connection to an windows host via winrm with CredSSP authentification fails.
- What happened (include command output)
```
fatal: [windows]: UNREACHABLE! => {
    "changed": false,
    "unreachable": true
}

MSG:

credssp: requests auth method is credssp, but requests-credssp is not installed
```
- What you expected to happen
Ansible can connect without issues
- Step-by-step reproduction instructions (by running `brew install` commands)

https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#credssp

Connect to an windows host with this settings:
inventory.yml
```
all:
  hosts:
    windows-host:
      ansible_connection: winrm
      ansible_user: admin
      ansible_password: password
      ansible_winrm_transport: credssp
      ansible_winrm_server_cert_validation: ignore
```
Then run:
```
ansible -i inventory.yaml windows-host -m win_ping
```

**Comment by jonchang** [comment]
Looks like this would require adding that Python package as a new `resource` block in the `ansible` formula. See these instructions for opening a pull request: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request; even incomplete code is fine as we can help you through the rest.

**Comment by jkroepke** [comment]
@jonchang Can you help on the PR? #39161 

Did I miss something?
