### ISSUE TITLE
version dependency for osxfuse

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-core#38809]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### archivemount not working due to invalid OSXFuse dependency

After installing archivemount, I got this error

```
$ archivemount 
dyld: Library not loaded: /usr/local/lib/libosxfuse.2.dylib
  Referenced from: /usr/local/bin/archivemount
  Reason: Incompatible library version: archivemount requires version 12.0.0 or later, but libosxfuse.2.dylib provides version 10.0.0
Abort trap: 6
```

OSX Fuse is installed, but I had an old version, 2.7.5, rather than the latest version 3.8.3

### Version Dependency for OSXFuse

Instead of 

`depends_on :osxfuse`

Can we include version dependency for OSX Fuse requirement?

`depends_on :osxfuse => "3.0.0"`

**Comment by fxcoudert** [comment]
Sorry, in the current way Homebrew is working we can't really control the version of requirements like fuse. Always update to the latest version to be sure it works :)
