### ISSUE TITLE
Cannot update charthage on osx 10.14.4 and xcode 10.2

### ISSUE THREAD

**Issue by romansavrulin** [Homebrew/homebrew-core#38810]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Logs
https://gist.github.com/06b4a7ead990cd21653402f6ee4a6983

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to update a carthage package from version: 0.26.2. You currently are on 0.33.0

- What happened (include command output)

```
rs$ brew reinstall carthage
==> Reinstalling carthage
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/rs/Library/Caches/Homebrew/carthage--git
==> Checking out tag 0.33.0
Error: Xcode >=10.2 requires macOS >=10.14.4 to build Swift formulae.
```

- What you expected to happen

Successful package update

- Step-by-step reproduction instructions (by running `brew install` commands)

see above

## NB

i've noticed a strange condition here

https://github.com/Homebrew/homebrew-core/blob/893d2b0451b482af8ed944e04577d6e8a590f8f8/Formula/carthage.rb#L17-L20

Is it supposed to be like this?

**Comment by MikeMcQuaid** [comment]
Run `brew update-reset` and try again.
