### ISSUE TITLE
Problem with gcc

### ISSUE THREAD

**Issue by flyunet** [Homebrew/homebrew-core#38929]
Hi there,
I'm trying to compile gcc with home-brew installed gcc but I'm experiencing different issues.

In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/sysctl.h:83,
                 from ../../gcc/config/darwin-driver.c:30:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/ucred.h:94:2: error: '_Atomic' does not name a type
  _Atomic u_long          cr_ref;  /* reference count */
  ^~~~~~~
make[3]: *** [darwin-driver.o] Error 1
make[3]: *** Waiting for unfinished jobs....
rm gfortran.pod gcc.pod
make[2]: *** [all-stage2-gcc] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by SMillerDev** [comment]
Please fill out the issue template as it is impossible to debug issues without it. I'm going to close this until the required information is provided.
