### ISSUE TITLE
Removing options for brew builds removes functionality. (eg - Emacs)

### ISSUE THREAD

**Issue by anmoljagetia** [Homebrew/homebrew-core#38927]
I have been an avid user of brew and it definitely makes mac automation quite on par with Linux.  I couldn't fit this into any of the pre-baked format so I am a little bit confused, therefore, I am opening a standard issue. 

https://github.com/Homebrew/homebrew-core/pull/36070 <- PR breaks the --cocoa functionality and unfortunately, makes installing emacs using brew quite difficult. Emacs on mac is a little bit complicated so the `cask` version of emacs doesn't work with `daemon` mode, therefore each launch of Emacs is about a 5-6 second for me. Installing --cocoa version enabled me to run emacs in daemon mode so that the first launch took 5-6seconds but each subsequent launch was lightning quick which made for an extremely pleasant experience.

Under the present arrangement, running `brew install emacs` installs the terminal version and doesn't allow the GUI version to be installed even with arguments and `brew cask install emacs` doesn't work with the emacs daemon mode, there both the options are not suitable. I have also seen the discussion over at https://github.com/Homebrew/homebrew-core/issues/31510 and I do agree that it makes maintenance hard, but is there a possibility of making exceptions for a few packages like emacs (common and widely used) to have options enabled or maybe a separate formula with the options enabled? I know I can solve this my maintaining my own tap, however, I feel if a lot of users can benefit from something like this, it might make sense to keep it in the main core itself?

Would like to know your thoughts on the same along with any pointers you might have for me to deal with something like this?

P.S. - Please be gentle, newbie dev here.

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by iMichka** [comment]
This kind of questions are better asked here: https://discourse.brew.sh
