### ISSUE TITLE
brew install gdb with python 3 built, but gdb debug fail

### ISSUE THREAD

**Issue by inevity** [Homebrew/homebrew-core#38934]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Use the --interactive to build the gdb.
brew install -i gdb
modify the gdb/python/python-config.py  to support python3.
change the line" if getvar('LINKFORSHARED') is not None:" to " if not getvar('PYTHONFRAMEWORK'):" 
./configure CPPFLAGS="-I/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.7/include/python3.7m"  --prefix=/usr/local/Cellar/gdb/8.2.1 -enable-targets=all --with-python=/usr/local/bin/python3 --disable-binutils
make
make install-gdb
exit

The issue is that 
Have set "set startup-with-shell off", and sign.
When debug, lead gdb stopped.
```
cython --gdb cython_file.pyx 
 python setup.py build_ext --inplace
cygdb .
cy run python_file.py ---lead gdb stopped.
```
or if delete the "set startup-with-shell off",

cy run python_file.py ---lead gdb omit
```
(gdb) cy run python_file.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Cython/Debugger/libpython.py", line 2345, in run
    self.finish_executing(gdb.execute('run ' + args, to_string=True))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/Cython/Debugger/libpython.py", line 2065, in execute
    _execute(command, from_tty)
gdb.error: During startup program terminated with signal ?, Unknown signal.
Error occurred in Python command: During startup program terminated with signal ?, Unknown signal.
```
Please ref https://stackoverflow.com/questions/21033553/cython-debugging-put-a-break-point

**Comment by inevity** [comment]
source is 
```
#include <stdio.h>
int main() { printf("hello world\n"); }
```

If set set startup-with-shell off, gdb a.out, b main, r ,hang
if delete set startup-with-shell off", gdb a.out, b main,r, During startup program terminated with signal ?, Unknown signal.

**Comment by SMillerDev** [comment]
I mean, if you modify the formula it's not really broken in homebrew. Your modifications break it.

**Comment by inevity** [comment]
Oh, Even use the bottle gdb 8.2.1, not build by myself  i also met the issue Error occurred in Python command: During startup program terminated with signal SIGTRAP, Trace/breakpoint trap.

**Comment by inevity** [comment]
I did not modify the formula, in fact , only apply patches in the formula, and add those option  CPPFLAGS and --with-python=/usr/local/bin/python3.   Other op is same as formula. such as make,make install-gdb
