### ISSUE TITLE
PyPy3 3.6-7.1.0

### ISSUE THREAD

**Issue by johnthagen** [Homebrew/homebrew-core#38951]
The PyPy team has released a new PyPy3 that supports Python 3.6: https://pypy.org/download.html

It would be very helpful if the Homebrew formula supported this version: PyPy3.6 v7.1.0.

**Comment by SMillerDev** [comment]
Please make a pull request. The homebrew project doesn't accept feature requests as issues (as was in the template you removed)

**Comment by johnthagen** [comment]
@SMillerDev Just so I understand, if I don't know *how* to add 7.1.0 or if I am not the PyPy formula author, there isn't a way to request it be updated? That's totally fine, it just wasn't clear to me.

How would I go about requesting this?

**Comment by SMillerDev** [comment]
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula has all the information you need to bump a software version.
