### ISSUE TITLE
boost regex not found on High Sierra

### ISSUE THREAD

**Issue by winsento** [Homebrew/homebrew-core#38963]
When trying to build mapnik on high Sierra, we get an error:
```
Checking for C++ library boost_regex... no
Checking if boost_regex was built with ICU unicode support... (cached) no
...
Exiting... the following required dependencies were not found:
   - boost regex (more info see: https://github.com/mapnik/mapnik/wiki/Mapnik-Installation & http://www.boost.org)

```
https://github.com/OSGeo/homebrew-osgeo4mac/pull/1091#issuecomment-481453399

On Sierra builds well https://github.com/OSGeo/homebrew-osgeo4mac/pull/1091#issuecomment-481461667

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
