### ISSUE TITLE
brew install hashcat produces error

### ISSUE THREAD

**Issue by odoglv1** [Homebrew/homebrew-core#38974]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
     - [Link is here](https://gist.github.com/odoglv1/02912201c4fe40379536a37e2d2e83d5)
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
     - Trying to install formula hashcat for a ctf.
- What happened (include command output)
     - Running `brew install hashcat` says `Error: No available formula with the name "hashcat"`. Running `brew update` and `brew doctor` hasn't fixed the issue.
- What you expected to happen
      - I expected this to install the formula hashcat--I've run this command with no issue in the past but for whatever reason brew no longer seems to recognize that formula.
- Step-by-step reproduction instructions (by running `brew install` commands)
     - Run `brew install hashcat`

**Comment by odoglv1** [comment]
I should add I've been able to reproduce this issue on multiple MacBooks running Mojave 10.14.4 and homebrew 2.1.1. My brew config output is [here](https://gist.github.com/odoglv1/78df7d07f414b3ac66b28f5758e5549e).

**Comment by SMillerDev** [comment]
Can you run `brew update-reset` and try again?

**Comment by odoglv1** [comment]
Thanks, that worked.
