### ISSUE TITLE
opencv 4.0.1 => 4.1.0 upgrade fails: sha256 incorrect for patch file

### ISSUE THREAD

**Issue by slippycheeze** [Homebrew/homebrew-core#38970]
`brew gist-logs opencv` did not work: "No logs."
Find the requested output of `brew gist-logs` and other commands at https://gist.github.com/slippycheeze/085df167f18a631bd788fe354edab9d8

That includes `brew info` and `brew upgrade opencv`.

When running the upgrade process, opencv grabs the source, then grabs a patch and fails because the sha256 is incorrect:

```
==> Downloading https://github.com/opencv/opencv/pull/14308.patch?full_index=1
Already downloaded: /Users/slippycheeze/Library/Caches/Homebrew/downloads/d147bd546d02183983a13d3ec79f058102fe6d68dd2220f090de8a2b9df99d02--14308.patch
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 9de405097cbafeadf0b980083edf1ff6b1a18e452bffea2b88a235c36677a1f8
  Actual: c48a6a769f364e6f61bc99cf47a6e664c85246c9fcd4a201afc408158fc4f1ef
 Archive: /Users/slippycheeze/Library/Caches/Homebrew/downloads/d147bd546d02183983a13d3ec79f058102fe6d68dd2220f090de8a2b9df99d02--14308.patch
To retry an incomplete download, remove the file above.

brew upgrade opencv  11.03s user 9.49s system 94% cpu 21.790 total
] gsha256sum /Users/slippycheeze/Library/Caches/Homebrew/downloads/d147bd546d02183983a13d3ec79f058102fe6d68dd2220f090de8a2b9df99d02--14308.patch
c48a6a769f364e6f61bc99cf47a6e664c85246c9fcd4a201afc408158fc4f1ef  /Users/slippycheeze/Library/Caches/Homebrew/downloads/d147bd546d02183983a13d3ec79f058102fe6d68dd2220f090de8a2b9df99d02--14308.patch
```

As gsha256sum says, the calculated one is correct, the formula sha256 is wrong.  Not sure why.  Entirely reproducible for me.  Removing the file and running the process again gets the same patch, with the same sha256.  Fetching that URL directly, same sha256.  So, only the formula believes it should be different.

This happens, obviously, when `brew upgrade opencv` tries to build from source.  Not sure why it does that, but I assume the answer is that I'm in a homedir-only install, and the bottle can't be used in that location.  

Unfortunately, I'm not able to use /usr/local for employer-related reasons, but I believe this is incorrect in the formula, and would fail for any attempt to build from source, not simply because I'm doing something uncommon.

**Comment by SMillerDev** [comment]
Hey, please fill out the entire issue template when reporting issues. It really helps a lot in solving the problem you might have (even if you don't see the need for it)

**Comment by SMillerDev** [comment]
In this case it seems like upstream changed the file. Could you contact them to confirm it's not something malicious?

**Comment by fxcoudert** [comment]
This was fixed in 44c5fd9ee5b9af40b8d0eddcef006df9778562c5

**Comment by slippycheeze** [comment]
@SMillerDev – I'm sorry, could you let me know what part of the template I failed to complete?  I double-checked before submitting, and rechecked now, and I believe all the content is present.

Of course, you wouldn't say that if it really was, so I'm clearly (still) missing something I should have done.  If you let me know I can at least mess up differently next time. :)

**Comment by SMillerDev** [comment]
You're missing the list of checkboxes that are there to give an easy overview of the steps taken. Not just the steps at the bottom are important but the formatting helps in getting a quick overview of the status of the steps someone took. Most of the information is also there hidden in your text but it's not as easy to filter out as it is in the template.
