### ISSUE TITLE
brew install nifi fails for nifi-1.9.1

### ISSUE THREAD

**Issue by RioLynnnnn** [Homebrew/homebrew-core#38989]
- [*] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [*] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?

> Yes

- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?

> Yes

- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
bash-3.2$ brew gist-logs nifi
Error: No logs.
```
- [*] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
bash-3.2$ brew config
HOMEBREW_VERSION: 2.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4f73e61649fcfc5aaa779c311e2514619ce01e7
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9803a34cec2f4bb0235077d60ab8848e39cb11cc
Core tap last commit: 89 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /Users/ctsuser1/Library/Logs/Homebrew
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11, 1.8.0_201, 1.8.0_192
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: 10.2
CLT headers: 10.2.0.0.1.1552586384
```
To help us debug your issue please explain:
- What you were trying to do (and why)

> brew install nifi

- What happened (include command output)
```
bash-3.2$ brew install nifi
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/nifi/1.9.1/nifi-1.9.1-bin.tar.gz
==> Downloading from https://www-us.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-eu.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-us.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "nifi"
Download failed: https://www-us.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz
```
- What you expected to happen

> It should install nifi

- Step-by-step reproduction instructions (by running `brew install` commands)
```
bash-3.2$ brew install nifi
==> Downloading https://www.apache.org/dyn/closer.cgi?path=/nifi/1.9.1/nifi-1.9.1-bin.tar.gz
==> Downloading from https://www-us.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-eu.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://www-us.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "nifi"
Download failed: https://www-us.apache.org/dist/nifi/1.9.1/nifi-1.9.1-bin.tar.gz
```

**Comment by SMillerDev** [comment]
What happens when you manually open that url?

**Comment by RioLynnnnn** [comment]
Did check that, its actually not available anymore.

> The requested file or directory is not on the mirrors

Infact 1.9.2 is available. By changing the .rb file to latest one should fix it.

**Comment by SMillerDev** [comment]
Cool, could you do that? There's a tutorial here if you need help: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula

**Comment by RioLynnnnn** [comment]
Did it using different user, will wait for merge. Thanks for motivating.

**Comment by SMillerDev** [comment]
You're very welcome. There's so many packages in homebrew, it only works well if everyone who notices that something is outdated actually bumps the version.  You just helped everyone else using nifi on macOS.

**Comment by fxcoudert** [comment]
Fixed by @leenusn in https://github.com/Homebrew/homebrew-core/pull/39027
