### ISSUE TITLE
icu4c update broke node

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew-core#39090]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? --> it's not an installation that's failing
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run `node` which I installed through Homebrew.

## What happened (include command output)

```
➜ node
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.63.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
[1]    91634 abort      node
```

## What you expected to happen

`node` should have been bumped or re-linked to prevent this library issue?

## Step-by-step reproduction instructions (by running `brew install` commands)

I had done a Brew upgrade before which upgraded `icu4c` (notice the date):

```
➜ brew info icu4c
icu4c: stable 64.2 (bottled) [keg-only]
C/C++ and Java libraries for Unicode and globalization
https://ssl.icu-project.org/
/usr/local/Cellar/icu4c/64.2 (257 files, 69.2MB)
  Poured from bottle on 2019-04-19 at 08:19:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/icu4c.rb
==> Caveats
icu4c is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have icu4c first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc

For compilers to find icu4c you may need to set:
  export LDFLAGS="-L/usr/local/opt/icu4c/lib"
  export CPPFLAGS="-I/usr/local/opt/icu4c/include"

For pkg-config to find icu4c you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"

==> Analytics
install: 256,261 (30 days), 802,255 (90 days), 2,959,307 (365 days)
install_on_request: 8,028 (30 days), 28,577 (90 days), 118,406 (365 days)
build_error: 0 (30 days)
```

`node` however was last upgraded a few weeks ago:

```
➜ brew info node
node: stable 11.14.0 (bottled), HEAD
Platform built on V8 to build network applications
https://nodejs.org/
/usr/local/Cellar/node/11.13.0 (4,417 files, 50.4MB) *
  Poured from bottle on 2019-04-03 at 10:05:35
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/node.rb
==> Dependencies
Build: pkg-config ✔, python@2 ✔
Required: icu4c ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 381,308 (30 days), 1,098,932 (90 days), 4,050,423 (365 days)
install_on_request: 280,322 (30 days), 815,742 (90 days), 2,984,360 (365 days)
build_error: 0 (30 days)
```

When I `brew reinstall node`, everything is back to normal:

```
➜ brew reinstall node
==> Reinstalling node
==> Downloading https://homebrew.bintray.com/bottles/node-11.14.0_1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/ed/ed16ba63432c967a7debc3374a064a3b10cd3f71e649c122ca8d2384c8f3d736?__gda__=exp=1555667292~hmac=4fa9458103860febee6dec173a86a6bdfd3e8b793f
######################################################################## 100.0%
==> Pouring node-11.14.0_1.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/11.14.0_1: 4,502 files, 50.6MB
Removing: /Users/werner/Library/Caches/Homebrew/node--11.13.0.mojave.bottle.tar.gz... (13.9MB)

➜ node
>
```

So I guess that this kind of reverse-dependency didn't get bumped?

(I've had this sort of stuff happen to me previously with ffmpeg and x264, every few months when the "main" formula wasn't bumped but the child dependency was.)

## System info

Brew config:

<details>
<pre>
HOMEBREW_VERSION: 2.1.1-29-g8f5be03
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8f5be03cb8270f7fd1d4053c0ece60f7ac7de098
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fa421cfc34548eb48bc236460584c9f4fa16b22
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DISPLAY: :0.0
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.4-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
</pre>
</details>

Brew doctor:

<details>
<pre>
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/werner/.pyenv/shims/python3.6m-config
  /Users/werner/.pyenv/shims/python3.7-config
  /Users/werner/.pyenv/shims/python3.7m-config
  /Users/werner/.pyenv/shims/python-config
  /Users/werner/.pyenv/shims/python3-config
  /Users/werner/.pyenv/shims/python3.6-config
</pre>
</details>

**Comment by SMillerDev** [comment]
Your node version was outdated either way. An upgrade of node would have fixed it.

**Comment by slhck** [comment]
But this version wasn't installed when I upgraded all today?

**Comment by SMillerDev** [comment]
Apparently not.  Notice the older version in the path of your info command.

```
➜ brew info node
node: stable 11.14.0 (bottled), HEAD
Platform built on V8 to build network applications
https://nodejs.org/
/usr/local/Cellar/node/11.13.0 (4,417 files, 50.4MB) *
  Poured from bottle on 2019-04-03 at 10:05:35
```

**Comment by slhck** [comment]
Then that's the bug. It should have been upgraded. I ran an upgrade on all formulae which triggered the icu4c upgrade but not the node one.

**Comment by slhck** [comment]
I see that https://github.com/Homebrew/homebrew-core/commit/64dd7f5c763c12cd91ba0881c7df2376ec6309ea was made right at that time. Maybe the upgrade was just before that?

**Comment by slhck** [comment]
I should add that this is the same issue as https://github.com/Homebrew/homebrew-core/issues/33364 which is about two dependent formulas that are left in an inconsistent state. I *should* have gotten the `node` revision 1 which was released 22 days ago, but I didn't. So this is definitely a bug somewhere in the upgrade path.
