### ISSUE TITLE
boost 1.69 introduced dependency on zstd?

### ISSUE THREAD

**Issue by colindean** [Homebrew/homebrew-core#39111]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
# What you were trying to do (and why)

Run `ledger`

# What happened (include command output)

```
$ ledger
dyld: Library not loaded: /usr/local/opt/zstd/lib/libzstd.1.dylib
  Referenced from: /usr/local/opt/boost/lib/libboost_iostreams-mt.dylib
  Reason: image not found
Abort trap: 6
```
# What you expected to happen

I expected `ledger` not to crash with a library loading error.

# Step-by-step reproduction instructions (by running `brew install` commands)

I ran `brew upgrade` this morning for the first time in a while and everything upgraded without a hitch. When I ran `ledger`, I got the above message. It seems that `boost` was included in the upgrade and that **Homebrew's `boost` 1.69 establishes a new dependency on `zstd` that [is not declared](https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb#L16)**.

I attempted a from-source rebuild of `ledger` with `brew reinstall ledger -s` and executing ledger built thusly fails with the same error.

When I try to run `brew gist-logs ledger`, I get this:

```
brew gist-logs -v ledger
Error: Not Found
```
so config and doctor output is here: https://gist.github.com/colindean/19caf431ab51b6eb9a70d5b93d56b9b9

## Workaround

After installing `zstd` manually with `brew install zstd`, I can successfully execute `ledger`.

**Comment by fxcoudert** [comment]
Fixed, thanks @colindean for reporting it!
