### ISSUE TITLE
`rpmsign` (in rpm formula) can't sign packages

### ISSUE THREAD

**Issue by RangerRick** [Homebrew/homebrew-core#39120]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

FYI, `brew gist-logs rpm` just prints `Error: No logs.` presumably because RPM passed. It wasn't clear if I needed to include that from your checklist.

To help us debug your issue please explain:
- What you were trying to do (and why)

  Sign an rpm using the `rpmsign` executable.

- What happened (include command output)

```
rpmsign --resign /tmp/repo/yum/stable/common/packagecloud/noarch/*.rpm
/tmp/repo/yum/stable/common/packagecloud/noarch/opennms-alec-plugin-1.0.0-1.noarch.rpm:
gpg: Fatal: passphrase-fd is invalid: Bad file descriptor
^C
```

  Note that I had to control-C the command.  It didn't error out, just got stuck, presumably because it didn't talk to gpg correctly.

- What you expected to happen

  RPM uses GPG to sign the package.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gnupg rpm
cat <<END > ~/.rpmmacros
%_gpg_name <your-gpg-key-name>
%_source_filedigest_algorithm 0
%_binary_filedigest_algorithm 0
%_source_payload w0.bzdio
%_binary_payload w0.bzdio
%__gpg_sign_cmd %{__gpg} gpg --batch --no-verbose --force-v3-sigs --no-armor --passphrase-fd 3 --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} %{__plaintext_filename}
END
rpmsign --resign /path-to-package.rpm
```

**Comment by RangerRick** [comment]
Is there a better way to report issues like this? Not sure how to make sure the `rpm` maintainer sees this...

**Comment by MikeMcQuaid** [comment]
@RangerRick There's no specific maintainers for individual packages and we don't tend to keep open issues where they aren't affecting multiple people and have ongoing activity. Your best bet is to figure this out yourself and submit a pull request. Thanks!

**Comment by wiggin15** [comment]
For anyone coming here through a search engine query (like me):
The problem here is related to the configuration set in `~/.rpmmacros`. Using `--passphrase-fd 3` (to tell gpg to read the passphrase from "stdin") apparently worked in older versions of "gpg" (where "stdin" was file descriptor 3, it seems) but does not work in newer versions of "gpg" (we used rpmsign on Ubuntu, and upgrading from Ubuntu 14.04 with gpg v1.4.16 to Ubuntu 18.04 with gpg v2.2.4 caused the same issue). For us, removing this flag altogether from `~/.rpmmacros` fixed the issue.
