### ISSUE TITLE
Diffuse formula doesnt install properly

### ISSUE THREAD

**Issue by KeynesYouDigIt** [Homebrew/homebrew-core#39170]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```bash
# this is the formula, right?
$ brew gist-logs diffuse
Error: No logs.
```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install diffuse since im tragically on a project that doesnt use git
- What happened (include command output)
same issue as https://github.com/Homebrew/homebrew-core/issues/35944
```bash
$brew reinstall diffuse
==> Reinstalling diffuse
==> Downloading https://homebrew.bintray.com/bottles/diffuse-0.4.8_2.high_sierra.bottle.tar.gz
Already downloaded: /Users/vince/Library/Caches/Homebrew/downloads/23e048bb6f24258c6f75bbf9fd7ec6335b511f5e34c3c2afb423d122fa7b2f83--diffuse-0.4.8_2.high_sierra.bottle.tar.gz
==> Pouring diffuse-0.4.8_2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/diffuse/0.4.8_2: 69 files, 1.3MB
~ ⌚ 13:02:55
$ brew update
Already up-to-date.

~ ⌚ 13:03:57
$ brew doctor
Your system is ready to brew.

~ ⌚ 13:04:06
$ diffuse
Traceback (most recent call last):
  File "/usr/local/bin/diffuse", line 124, in <module>
    import pygtk
ImportError: No module named pygtk


```

- What you expected to happen
diffuse to run normally with all its dependencies installed (pip install pygtk did not work)

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install diffuse && diffuse`

**Comment by KeynesYouDigIt** [comment]
Dont know much abotu homebrew... is there somewhere I can submit a PR for the formula?

**Comment by SMillerDev** [comment]
Docs.brew.sh can help you get started with that.

**Comment by zbeekman** [comment]
@KeynesYouDigIt I can confirm that the formula is broken. Off the top of my head I'm not 100% sure how to fix this. It may be that the pygtk formula needs modifications...

**Comment by fxcoudert** [comment]
It was rebuilt and rebottled from source at 2c7c239b59cfeda614f516e926333023d61b9f53 so the issue seems gone now.
