### ISSUE TITLE
gpgme: add qt bindings

### ISSUE THREAD

**Issue by sl1pkn07** [Homebrew/homebrew-core#39173]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
kmymoney (https://kmymoney.org/) (https://github.com/KDE-mac/homebrew-kde/blob/master/Formula/kmymoney.rb) needs the Qt bindings for add crypto support in it.

- What happened (include command output)
if run `brew ls gpgme --verbose` , the Qt bindings files is missing. also, in the `gpgme.rb` formula, Qt is not added to dependency (https://github.com/Homebrew/homebrew-core/blob/master/Formula/gpgme.rb)

- What you expected to happen
include the Qt bindings, the files is https://www.archlinux.org/packages/core/x86_64/qgpgme/files/ (list taked from archlinux repository). and the script for build it https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gpgme you can see the Qt(5-base) in the depends/makedepends in here https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gpgme#n13 and here https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gpgme#n49

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install gpgme` 
`brew ls gpgme --verbose` (for see the installed files)
`brew install KDE-mac/kde/kmymoney.rb --verbose`

and see this output:

~~~
--cut--
 -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
 -- Could NOT find QGpgme (missing: QGpgme_DIR)
--cut--
~~~

i can make a PR with the changes. but i'm not sure if you want add this "feature". or you prefeer make a custom formula with the feature enabled in the `KDE-mac/kde` repo?

greetings

**Comment by SMillerDev** [comment]
That's not really an issue in homebrew. While you could make a pull request to enable compilation with QT to the gpgme formula, the kmymoney formula isn't under homebrew's control. They could alternatively make their own version of gpgme.

**Comment by fxcoudert** [comment]
Discussion taking place in #39197
