### ISSUE TITLE
evince: File type PDF document (application/pdf) is not supported

### ISSUE THREAD

**Issue by inclucive-dev1** [Homebrew/homebrew-core#39183]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```shell
$ brew gist-logs evince
Error: can't modify frozen String
```

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```shell
$ brew config
HOMEBREW_VERSION: 2.1.1-54-gaa26032
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: aa260326cc8e039108e90b90b379615f4cecdba9
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9a723fa49288ae13088a6947d0add02edf66ee48
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.18.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_31
macOS: 10.14.4-x86_64
CLT: N/A
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
```

To help us debug your issue please explain:
- What you were trying to do (and why)

Install evince via `brew install evince`. Open any PDF file with `evince`.

- What happened (include command output)

No output or error message. In GUI of `evince`, I see the error message mentioned in the title of this issue.

- What you expected to happen

Expected `evince` to open any PDF file that every other PDF reader can open.

- Step-by-step reproduction instructions (by running `brew install` commands)

    brew install evince
    evince &

Open any PDF file with evince and see it fail to open.

**Comment by inclucive-dev1** [comment]
Should I revert to High Sierra? Or is *evince 3.30.2* also not working on High Sierra (I think I was using 3.28)? Can someone verify before I revert to High Sierra?

It seems Mojave is still not completely caught up. [Inkscape has a problem too](https://github.com/Homebrew/homebrew-cask/issues/62404).

**Comment by tschoonj** [comment]
I can confirm this problem. It appears to be related to glib, as [`g_content_type_is_mime_type`](https://github.com/GNOME/evince/blob/712edc34ee8b74967a4a3a13f0be983f397f060e/libdocument/ev-document-factory.c#L61) always returns `FALSE`.

Investigating...

**Comment by tschoonj** [comment]
I opened a Glib ticket at https://gitlab.gnome.org/GNOME/glib/issues/1762

**Comment by tschoonj** [comment]
This problem will occur on every system that has Glib 2.60.x installed by the way and is not tied to the Evince version.
