### ISSUE TITLE
Have there been no updates in the past 4 days, or is something broken?

### ISSUE THREAD

**Issue by Numbermaniac** [Homebrew/homebrew-core#3918]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

`brew update` just keeps telling me everything is up-to-date for the past 4 or so days. I remember reading in a discussion here that brew update was broken for some people if they updated during a certain time; or has there just been no updates for the past couple of days? Looks to me like formula upgrades have been merged in...

**Comment by dunn** [comment]
Somethink broke 😿.  There was a bug in the update code, and anyone who updated before it was patched had `brew update` broken.  The fix it to manually update once:
```
cd $(brew --prefix) && git fetch origin && git reset --hard origin/master
```
So sorry for the inconvenience!

**Comment by Numbermaniac** [comment]
Perfect, it's working now! Thanks :D
