### ISSUE TITLE
Compile webp with libtiff support

### ISSUE THREAD

**Issue by palmerj** [Homebrew/homebrew-core#39326]
Current cwebp can not read tiff files. Please Compile webp with libtiff support

**Comment by SMillerDev** [comment]
Currently this is not following the required bug report template.
Please follow the issue template

**Comment by SMillerDev** [comment]
In addition to that, this seems to be a feature request and homebrew only accepts those as pull requests.

**Comment by palmerj** [comment]
OK tough but fair I guess.

**Comment by palmerj** [comment]
PR #39329 created
