### ISSUE TITLE
Permissions issue when linking python3 on MacOS Mojave

### ISSUE THREAD

**Issue by vbastos** [Homebrew/homebrew-core#39331]
I am running into a similar issue to #19286 ad #20985. The Framework directory was not created. The details are below.

- [ x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ failed ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
install python
- What happened (include command output)
➜  ~ brew install python
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
presto

Warning: python 3.7.3 is already installed, it's just not linked
You can use `brew link python` to link this version.
➜  ~ brew link python
Linking /usr/local/Cellar/python/3.7.3... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
- What you expected to happen
I expected brew to install python
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install python

my brew Config output:
➜  ~ brew config
HOMEBREW_VERSION: 2.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4f73e61649fcfc5aaa779c311e2514619ce01e7
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5e30ef879827a10507600482a8f2d6e30d551a6b
Core tap last commit: 53 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ygusnn0hXi/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/vbastos/Library/Logs/Homebrew
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.4-x86_64
CLT: N/A
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11

**Comment by SMillerDev** [comment]
That's strange, what's the output of `brew doctor`?

**Comment by vbastos** [comment]
I have manually fixed the problem, but before I manually created the directory the output of brew doctor was:

➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python

**Comment by zbeekman** [comment]
Is this because of sip? Can users write to `/usr/local` by default? I have so much trouble keeping this straight, and remembering what I've done to each of my machines.

**Comment by zbeekman** [comment]
Some testing seems to indicate that this is due to sip and/or default ownership & permissions on `/usr/local`. I'm not sure if there is a way for homebrew to solve this on behalf of the user.

**Comment by zbeekman** [comment]
Sorry for the noise, but this seems likely to be caused by having installed homebrew a long time ago. [The installer gets sudo privs](https://github.com/Homebrew/install/blob/master/install#L230) to create a number of directories on behalf of the user and set permissions accordingly. Homebrew then never asks for sudo again in most circumstances. I suppose some sort of check could be added that the requisite default directories exist, and then warn the user or offer to create them when they don't.

**Comment by SMillerDev** [comment]
That should be part of brew doctor already (the check)
