### ISSUE TITLE
Installing `mercurial` with `--with-custom-python` causing missing dependency warning

### ISSUE THREAD

**Issue by samdmarshall** [Homebrew/homebrew-core#3938]
### Bug reports:

The formula `mercurial` provides an option `--with-custom-python` which will "Install against the python in PATH instead of Homebrew's python". I used this to prevent installing another version of python 2 on my system and to instead use the system version. This seems to work, but results in a warning when running `brew doctor` as missing the python dependency. Running `brew missing` and `brew info mercurial` after installing with this flag both indicate this missing dependency. As this is an explicit formula option, I don't think it should be displaying the behavior of a warning of a missing dependency when I explicitly told it to not install it.

Log: https://gist.github.com/samdmarshall/1e3a3b37d2500567668d235943f0cd82

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for thoughts on this.

**Comment by tdsmith** [comment]
I agree it's poor behavior but it's related to weaknesses in our dependency specification and resolution model (dependencies are specified on the class body; conditionals on the class body are evaluated at definition and not instantiation) and I'm not sure how to provide the desired behavior for mercurial without inviting this issue. I think doctor output is advisory and this is a cosmetic issue so I don't think this is actionable; sorry!

**Comment by samdmarshall** [comment]
To get this addressed, should an issue be opened on https://github.com/Homebrew/brew for the resolver to be able to handle this better?

**Comment by tdsmith** [comment]
I think that would be the right place for it but I don't think it'll get picked up unless someone sketches out an implementation, sorry.

I'll close this; maintainers, please re-open if you think we can fix this in the mercurial formula.

**Comment by samdmarshall** [comment]
@tdsmith I went to go file an issue, and noticed the feature request part of the issue template on https://github.com/Homebrew/brew, should this be part of the https://github.com/Homebrew/brew-evolution repo instead? as this is a fundamental change to the existing behavior of the brew dependency resolve.

**Comment by tdsmith** [comment]
This feels more like an acknowledgement of a deficiency more than a feature request so I'd say `brew` but I don't have strong feelings.
