### ISSUE TITLE
Coreutils: "Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail"

### ISSUE THREAD

**Issue by briancrink** [Homebrew/homebrew-core#39397]
- [✅] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [✅] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [✅] ran `brew update` and can still reproduce the problem?
- [✅] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [✅] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [✅] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install coreutils` to install greadlink to fix the "readlink -f" error on mac
- What happened (include command output)
`brew doctor` returns "Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail."
- What you expected to happen
`brew doctor` -> "Your system is ready to brew."
- Step-by-step reproduction instructions (by running `brew install` commands)
1. `brew install coreutils`
2. `brew doctor`

`echo $PATH` -> `/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

brew config:

```
HOMEBREW_VERSION: 2.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4f73e61649fcfc5aaa779c311e2514619ce01e7
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3d745f43d53c5d42489dbea12349cd32c32f5a3c
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.dy2gBbNsQS/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/briancrink/Library/Logs/Homebrew
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
The brew install doesn't edit your path so this must be something you did manually. And the brew doctor check is correct so it's not really a bug.
