### ISSUE TITLE
LDAP Mojave PHP 7.3

### ISSUE THREAD

**Issue by adrazich** [Homebrew/homebrew-core#39407]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? auth failed even with Github token set
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? https://gist.github.com/adrazich/bbf05b81e68dbc434f89a8f5c3884bd2

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to connect to LDAP via:

```
ldap_connect('ldap://localhost/');
```

Even attempting to set debug options before attempting to connect causes this issue:

```
ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);
```

- What happened (include command output)

Page receives an `ERR_EMPTY_RESPONSE`.

When I checked the apache error log I saw this:

```
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /usr/local/etc/openldap/ldap.conf
ldap_init: using /usr/local/etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
Assertion failed: (LDAP_VALID( ld )), function ldap_set_option, file options.c, line 456.
```

- What you expected to happen
LDAP to connect without crashing.

- Step-by-step reproduction instructions (by running `brew install` commands)

I just did a fresh install on Mojave. I installed PHP via:

```
brew install php@7.3
```

#### Other things I've tried:
- I tried to reinstall openldap and php that was [mentioned as a fix on a previous issue](https://github.com/Homebrew/homebrew-core/issues/32916#issuecomment-430761327).
- I tried installing libiconv that was [mentioned as a fix on a previous issue](https://github.com/Homebrew/homebrew-core/issues/32916#issuecomment-440272950).

#### Etc:
- `ldapsearch` via the LDAP CLI works

**Comment by UlrichThomasGabor** [comment]
Seems to work for me on Mojave:
```
$ ls -lah $(which php)
lrwxr-xr-x  1 ug  admin    27B  7 Mai 17:57 /usr/local/bin/php -> ../Cellar/php/7.3.5/bin/php
$ php -r "ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL, 7);"
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /usr/local/etc/openldap/ldap.conf
ldap_init: using /usr/local/etc/openldap/ldap.conf
ldap_init: HOME env is /Users/ug
ldap_init: trying /Users/ug/ldaprc
ldap_init: trying /Users/ug/.ldaprc
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
```

Maybe try `brew update && brew reinstall php`?

**Comment by adrazich** [comment]
@UlrichThomasGabor Thank you! That seemed to have worked! I don't know what has changed because I tried uninstalling and reinstalling previously with no success.

However, it seems that using the native apache server with homebrew's PHP does not work still. I continue getting the following error in my apache log:

```
ldap_url_parse_ext(ldap://localhost/)
ldap_init: trying /usr/local/etc/openldap/ldap.conf
ldap_init: using /usr/local/etc/openldap/ldap.conf
ldap_init: HOME env is NULL
ldap_init: trying ldaprc
ldap_init: LDAPCONF env is NULL
ldap_init: LDAPRC env is NULL
Assertion failed: (LDAP_VALID( ld )), function ldap_set_option, file options.c, line 456.
[Wed May 22 08:03:25.963352 2019] [core:notice] [pid 76] AH00052: child pid 1164 exit signal Abort trap (6)
```

That said, if I shut down the native apache and use homebrew's apache install with homebrew's PHP install it works. I'm not sure if it's supposed to work with the navtive apache server but it has for me in the past. I'll continue using homebrew's apache instead.

I've been using docker containers which has had slightly slower load times so I'm happy to go back to my local setup. :) Thanks again.

**Comment by UlrichThomasGabor** [comment]
I fixed a cert-based issue, maybe your problem was somehow related, see commit f3c54fb29f5689a64a3e3f8375b9baa6786b1237. This may also explain why it works with some webserver and not with another—because they use different `php.ini`s.
