### ISSUE TITLE
ncurses terminfo database built with wrong header

### ISSUE THREAD

**Issue by z0rc** [Homebrew/homebrew-core#39478]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

This is complicated one, please bear with me for long explanation.

`slang` library is able to read ncurses terminfo database. It has its own parser. The problem is: terminfo database from brew's ncurses isn't compatible with it.

`man term` defines storage format for database, it reads:
```
 The header section begins the file.  This section contains six short integers in the format described below.  These integers are

    (1) the magic number (octal 0432);
```
Upon opening any file from `/usr/local/Cellar/ncurses/6.1/share/terminfo/` (let's stick to `/usr/local/Cellar/ncurses/6.1/share/terminfo/78/xterm-256color` as it's the most common) in hex editor, we see `1E 02` as first two bytes, as this is signed 16-bit integer, it's actually `21E` which translates into `1036` in octal. Now open `/usr/share/terminfo/78/xterm-256color` (macOS bundled) in hex editor, first two bytes are `1A 01`, which is `11A` singed 16-bit int, or `432` octal.

Also I've checked various linux distributions, everywhere terminfo header is `0432`, only in brew's ncurses it's wrong.

Now, how to test this. First symlink terminfo database to `/usr/local/share/terminfo` (#39477). There is `mc` (Midnight Commander) which is built with `slang` by default. Configure `.tmux.conf` with `set -g default-terminal "tmux-256color"`, the terminfo for this entry isn't available in macOS default terminfo database, but available in brew's ncurses database (that's why `/usr/local/share/terminfo` symlink is needed). Launch `tmux`, then launch `mc`. You'll see the following:
```
Unknown terminal: tmux-256color
Check the TERM environment variable.
Also make sure that the terminal is defined in the terminfo database.
Alternatively, set the TERMCAP environment variable to the desired
termcap entry.
```
This is actually message from `slang` library as it wasn't able to read terminfo definition.

Using `dtruss mc` you can check, that `slang` finds tmux-256color terminfo under `/usr/local/share/74/tmux-256color` but skips it. Here is relevant source from `slang` (src/sltermin.c):
```c
/*
 * The majority of the comments found in the file were taken from the
 * term(4) man page on an SGI.
 */

/* Short integers are stored in two 8-bit bytes.  The first byte contains
 * the least significant 8 bits of the value, and the second byte contains
 * the most significant 8 bits.  (Thus, the value represented is
 * 256*second+first.)  The value -1 is represented by 0377,0377, and the
 * value -2 is represented by 0376,0377; other negative values are illegal.
 * The -1 generally means that a capability is missing from this terminal.
 * The -2 means that the capability has been cancelled in the terminfo
 * source and also is to be considered missing.
 */

static int make_integer (unsigned char *buf)
{
   register int lo, hi;
   lo = (int) *buf++; hi = (int) *buf;
   if (hi == 0377)
     {
	if (lo == 0377) return -1;
	if (lo == 0376) return -2;
     }
   return lo + 256 * hi;
}

/*
 * The compiled file is created from the source file descriptions of the
 * terminals (see the -I option of infocmp) by using the terminfo compiler,
 * tic, and read by the routine setupterm [see curses(3X).]  The file is
 * divided into six parts in the following order:  the header, terminal
 * names, boolean flags, numbers, strings, and string table.
 *
 * The header section begins the file.  This section contains six short
 * integers in the format described below.  These integers are (1) the magic
 * number (octal 0432); (2) the size, in bytes, of the names section; (3)
 * the number of bytes in the boolean section; (4) the number of short
 * integers in the numbers section; (5) the number of offsets (short
 * integers) in the strings section; (6) the size, in bytes, of the string
 * table.
 */

#define MAGIC 0432
```
```c
static FILE *open_terminfo (char *file, SLterminfo_Type *h)
{
   FILE *fp;
   unsigned char buf[12];

   /* Alan Cox reported a security problem here if the application using the
    * library is setuid.  So, I need to make sure open the file as a normal
    * user.  Unfortunately, there does not appear to be a portable way of
    * doing this, so I am going to use 'setfsgid' and 'setfsuid', which
    * are not portable.
    *
    * I will also look into the use of setreuid, seteuid and setregid, setegid.
    * FIXME: Priority=medium
    */
   fp = fopen (file, "rb");
   if (fp == NULL) return NULL;

   if ((12 == fread ((char *) buf, 1, 12, fp) && (MAGIC == make_integer (buf))))
     {
	h->name_section_size = make_integer (buf + 2);
	h->boolean_section_size = make_integer (buf + 4);
	h->num_numbers = make_integer (buf + 6);
	h->num_string_offsets = make_integer (buf + 8);
	h->string_table_size = make_integer (buf + 10);
     }
   else
     {
	fclose (fp);
	fp = NULL;
     }
   return fp;
}
```
Which can be read as: open terminfo file, read it's header, if it matches MAGIC octal `0432`, then parse it and return file pointer, else return NULL. This NULL later used to determine whether this is valid terminfo file or not.

Which brings up back to initial issue. The brew's ncurses terminfo database built in way it doesn't match `term` storage format.

Interesting enough, that brew's ncurses is able to parse this database, for example `infocmp` from brew's ncurses reads terminfo for `tmux-256color` just fine. So this is only a matter of database compatibility with other libraries, `slang` in particular.

**Comment by fxcoudert** [comment]
We're not doing any specific handling of GNU ncurses library in Homebrew, so the bug is from ncurses itself.

**Comment by laggardkernel** [comment]
How do you use terminfo `tmux-256color` on macOS? I tried to dump `tmux-256color` from brew installed `ncurses` and compile the terminfo with system tic `/usr/bin/tic`. But this causes some of my apps (nnn and ranger) unable to be displayed in color within tmux.

More detail here, https://github.com/tmux/tmux/issues/1584#issuecomment-466378606

For the time being, I just use `xterm-256color`. Although it works well with `TERM=xterm-256color`, I still wish to configure it in the right way with `tmux-256color`.
