### ISSUE TITLE
Can't install formula imapsync

### ISSUE THREAD

**Issue by root42** [Homebrew/homebrew-core#39482]
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I tried to install formula imapsync.

- What happened (include command output)

```
arne.schmitz@mail:~$ brew install imapsync
==> Downloading https://imapsync.lamiral.info/dist2/imapsync-1.882.tgz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "imapsync"
Download failed: https://imapsync.lamiral.info/dist2/imapsync-1.882.tgz

```

- What you expected to happen

I expected for imapsync to be installed. It seems the upstream URL disappeared. Also current imapsync seems to be a newer release. See https://imapsync.lamiral.info/ for details.

- Step-by-step reproduction instructions (by running `brew install` commands)

See above.

Output of brew config, doctor et al:

```
arne.schmitz@mail:~$ brew install imapsync
==> Downloading https://imapsync.lamiral.info/dist2/imapsync-1.882.tgz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "imapsync"
Download failed: https://imapsync.lamiral.info/dist2/imapsync-1.882.tgz
arne.schmitz@mail:~$ brew doctor
Your system is ready to brew.
arne.schmitz@mail:~$ brew gist-logs imapsync                                                     
Error: No logs.
arne.schmitz@mail:~$ brew config
HOMEBREW_VERSION: 2.1.1-112-g7da51b4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7da51b4a742f988c9801de09951f82ab5aecb04e
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: b55f114965d26909463147d9cdaaa0ce08b6a1a6
Core tap last commit: 22 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/arne.schmitz/.cache/Homebrew
HOMEBREW_LOGS: /home/arne.schmitz/.cache/Homebrew/Logs
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.21.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.4.0-042stab127.2 x86_64 GNU/Linux
OS: Ubuntu 16.04.6 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
```

**Comment by SMillerDev** [comment]
It seems the source is behind a pay wall and shouldn't be in homebrew because of this. @homebrew/core other suggestions/insights?

**Comment by iMichka** [comment]
Yes, it's 60 euros. And I have some doubts about the licence: https://imapsync.lamiral.info/LICENSE

I think this can be removed.

**Comment by MikeMcQuaid** [comment]
👍 to remove.

**Comment by root42** [comment]
What about the github repo:


https://github.com/imapsync/imapsync


Can we build from that, or simply fork it?


It's still a very useful tool.


Cheers,

Arne


Am 3. Mai 2019 um 7:45 schrieb Michka Popoff <notifications@github.com>:



Yes, it's 60 euros. And I have some doubts about the licence: https://imapsync.lamiral.info/LICENSE

I think this can be removed.

**Comment by MikeMcQuaid** [comment]
We could consider building from that repo instead, yup. The license seems to be public domain which isn't technically open source but is near enough for our purposes.

**Comment by claui** [comment]
@MikeMcQuaid 👍 for keeping. The license should be fair enough for our purposes, even though the OSI has never evaluated it.

Just for the record, the Fedora Project (which is by no means an authoritative source on legal things) [claims the license to be GPL-compatible](https://fedoraproject.org/wiki/Licensing/NLPL).

**Comment by vszakats** [comment]
It's also possible that the URL just disappeared due to a new release, as the comment warns in the formula. Visiting https://imapsync.lamiral.info/dist2/ shows a new, downloadable release: https://imapsync.lamiral.info/dist2/imapsync-1.921.tgz

**Comment by fxcoudert** [comment]
Opened a PR to restore the formula: https://github.com/Homebrew/homebrew-core/pull/39626
