### ISSUE TITLE
sphinx: postgresql no longer supported after options removal

### ISSUE THREAD

**Issue by gorj-tessella** [Homebrew/homebrew-core#39506]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I attempted to install sphinx with postgresql support, as documented at https://freelancing-gods.com/thinking-sphinx/v4/installing_sphinx/mac.html. This was a previously available option with `brew install sphinx --with-postgresql`. However as of Jan 13 it is no longer possible to install sphinx with postgresql support (or for that matter to install without mysql) due to the following commit: https://github.com/Homebrew/homebrew-core/commit/42ad547dd443d8d541bd2f30c37d9313abcb77d4.

**Comment by fxcoudert** [comment]
This is by design, and part of the removal of options. We cannot maintain (and test) software with different database backends. You could maintain a `sphinx-postgresql` formula in a personal tap if many users are interested: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
