### ISSUE TITLE
icu4c: Keep old versions

### ISSUE THREAD

**Issue by andreasabel** [Homebrew/homebrew-core#39567]
Homebrew carelessly removes old versions, breaking working installs.  I have this recurring problem with `icu4c`.  Here is my latest instance:
```
$ brew install node.js
...
==> Installing dependencies for node: icu4c
...
=> Summary
🍺  /usr/local/Cellar/icu4c/64.2: 257 files, 69.2MB
...
==> node
$ agda ...
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.62.dylib
  Referenced from: /Users/abel/agda/dist-2.6.1/build/agda-tests/agda-tests
  Reason: image not found
```
So, the old dylib `libicuuc.62.dylib` silently disappear, leaving all programs compiled against it broken.

Seems consciencious to clean up the "old", "disposable" stuff, but what if things __depend__ on it?  Package managing 101!?

**Comment by SMillerDev** [comment]
All the stuff that depends on it is updated alongside. If you keep something outdated for a long time you should really keep that in a private tap cause homebrew aims to only ever have the latest supported versions of software.

**Comment by zbeekman** [comment]
As a corollary, if icu4c gets updated, but other formula that depend on it aren't updated (they should be revision bumped if we detect linkage with icu4c) then do please let us know. But in general we revision bump everything that has linkage to icu4c when we ship a new version (and yes, this takes a long, long, long time).

If you don't like this behavior, you can set `HOMEBREW_NO_INSTALL_CLEANUP=1` in your environment but then you'll have to manually manage which old versions you want to cleanup and which you want to keep.

Another idea is to `brew pin icu4c` but this is is likely to break something, so I would advise you not to do this, and caution you that you'll be on your own from a support perspective if you do.
