### ISSUE TITLE
ngspice seems to depend on fftw

### ISSUE THREAD

**Issue by yunesj** [Homebrew/homebrew-core#39576]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew install ngspice

$ ngspice
dyld: Library not loaded: /usr/local/opt/fftw/lib/libfftw3.3.dylib
  Referenced from: /usr/local/bin/ngspice
  Reason: image not found
Abort trap: 6

```

IIRC, installing `fftw` fixed the problem.

**Comment by issyl0** [comment]
Thanks for reporting this, @yunesj! I could reproduce this, so I've pushed a fix in the PR linked above.
