### ISSUE TITLE
boost process 1.69 is broken on osx, pleas upgrade to 1.70

### ISSUE THREAD

**Issue by maddanio** [Homebrew/homebrew-core#39594]
the way some of the signaling functions are called. its known afaik. I dont have the exact issues at hand, if you want i can find them.
solutin would be to upgrade to 1.70 which just came out.
to work around this i currently have to build head, which is annoying, since it takes forever and i have to keep doing it when any dependency lib changes.

**Comment by scpeters** [comment]
see https://github.com/Homebrew/homebrew-core/pull/38890
