### ISSUE TITLE
Kafka failed to build on 10.12

### ISSUE THREAD

**Issue by slothspot** [Homebrew/homebrew-core#3962]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Kafka fails to build on 10.12 with Gradle 3 installed: 

https://gist.github.com/96512d98a8ef50b315d2f42074831c4e

**Comment by MikeMcQuaid** [comment]
> Warning: Your Xcode (7.3.1) is outdated
> Please update to Xcode 8.0.
> Xcode can be updated from
>  https://developer.apple.com/xcode/downloads/

**Comment by slothspot** [comment]
I do have Xcode 8.0 beta 6 installed, so I don't understand why brew doesn't pick it up, and Kafka is Java/Scala code, which fails due to Gradle/Ant things according to log, so this problem has no relation to Xcode and C/C++ compilers

**Comment by slothspot** [comment]
After sudo xcode-select -switch /Applications/Xcode-beta.app/Contents/Developer/ result is the same:

https://gist.github.com/anonymous/e61ed2826d2498586f1f0074e2f03ca4

**Comment by MikeMcQuaid** [comment]
> Ran brew doctor, fixed as many issues as possible and retried your prior step?

You did not do this but checked it anyway. You've still not updated XQuartz either. This is unlikely to be the cause but it would be good if you either followed the instructions or stated that you did not do so. 

Also please note:

> Please create pull-requests instead of filing issues.

You may want to comment in https://github.com/Homebrew/homebrew-core/issues/1957 instead.

**Comment by slothspot** [comment]
Thanks for your response. At this moment I think that problem has no relation to Xcode, maxOS but there is a problem with Gradle version and plugins. I will try to fix this problem and PR result

**Comment by slothspot** [comment]
Build of Kafka depends on Gradle < 3.0 due to usage of deprecated useAnt property of Scala plugin. Because I don't understand how to depend build of Kafka on older version of Gradle I propose to use Scala 2.11-based official Kafka binary build instead of source build. If it's ok, I'll prepare PR

**Comment by MikeMcQuaid** [comment]
Yeh, may as well check out a PR, thanks 👍
