### ISSUE TITLE
Serving multiple v8 versions at once.

### ISSUE THREAD

**Issue by pinepain** [Homebrew/homebrew-core#3966]
V8 is known to break BC across minor releases but at this time only v8 5.1 provided.

What about serving multiple V8 version under different names, e.g, `v8-5.2`, `v8-5.3`, `v8-5.4` and so on.  [Current `v8` formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/v8.rb)  can be deprecated in a favor of `v8-5.1` or for some time they both can be hosted in parallel, to be discussed.

This will let host multiple versions at once which will also open possibility for seamless upgrades between minor versions.

At this time I host vanilla `v8` myself - https://github.com/pinepain/php-v8/blob/master/scripts/homebrew/v8.rb and build it semi-automatic using some scripts and templates.

I really need this as I plan to publish [php-v8](https://github.com/pinepain/php-v8) extension, different version of which requires different v8 versions (because of bugfixes, deprecations removal and so on).

I already follow this practice providing different `libv8` version for Ubuntu in - https://launchpad.net/~pinepain.

/cc @DomT4

**Comment by MikeMcQuaid** [comment]
> What about serving multiple V8 version under different names, e.g, v8-5.2, v8-5.3, v8-5.4 and so on.

We would accept this in https://github.com/Homebrew/homebrew-versions but not this repository. See https://github.com/Homebrew/brew/issues/620 for how we plan on handling this better in future.

**Comment by pinepain** [comment]
@MikeMcQuaid thank you for the hint! Is it ok to provide a PR or we need to discuss this first there?

**Comment by MikeMcQuaid** [comment]
You could provide a homebrew/versions PR.

**Comment by DomT4** [comment]
Note the +/-2 requirement in `homebrew/versions`. There's some minor flexibility but I can live without 10 different V8 versions to look after indefinitely.
