### ISSUE TITLE
Formula "alpine": server down

### ISSUE THREAD

**Issue by polluks** [Homebrew/homebrew-core#39686]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

````
admin ~$ brew install alpine
==> Downloading http://alpine.freeiz.com/alpine/release/src/alpine-2.20.tar.xz
##O#- #                                                                        
curl: (22) The requested URL returned error: 410 Gone
Error: Failed to download resource "alpine"
Download failed: http://alpine.freeiz.com/alpine/release/src/alpine-2.20.tar.xz
````
I recommend http://alpine.x10host.com/alpine/release/src/alpine-2.20.tar.xz

**Comment by fxcoudert** [comment]
The current version is 2.21, and the URL we are using currently are:

```
  homepage "https://repo.or.cz/alpine.git"
  url "https://ftp.osuosl.org/pub/blfs/conglomeration/alpine/alpine-2.21.tar.xz"
  mirror "https://fossies.org/linux/misc/alpine-2.21.tar.xz"
```

You need to run `brew up` so that you are updated to the latest version of the formula.

**Comment by polluks** [comment]
What's wrong?
````
admin ~$ brew up -v
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git rev-parse -q --verify HEAD
5d74ac4c65d33ef30c3982220db1d4ac461faadb
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
5d74ac4c65d33ef30c3982220db1d4ac461faadb
==> git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null
refs/remotes/origin/master
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git rev-parse -q --verify HEAD
f2ee7eedaa9ccc2b82f1540237efe7b3b89fa18a
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
Already up-to-date.
==> git rev-parse -q --verify HEAD
f2ee7eedaa9ccc2b82f1540237efe7b3b89fa18a
Already up-to-date.
````

**Comment by fxcoudert** [comment]
No idea, please provide information required in the issue template (like `brew config` and `brew doctor` output)
