### ISSUE TITLE
`brew install valgrind` gives error on macOS Mojave

### ISSUE THREAD

**Issue by DilumAluthge** [Homebrew/homebrew-core#39774]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
  - **Valgrind is a homebrew-core formula, located here: [https://github.com/Homebrew/homebrew-core/blob/master/Formula/valgrind.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/valgrind.rb)**
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  - **`brew gist-logs valgrind` gives me the message `Error: No logs.`** 
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  - **Links:**
    - **[Output of `brew config`](https://gist.github.com/DilumAluthge/fd5b8bc65c040a49bcdbcdb54e426454)**
    - **[Output of `brew doctor`](https://gist.github.com/DilumAluthge/ae2df30ff207143d08b6b0f559877195)**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# What you were trying to do (and why)
I was trying to install Valgrind. I ran the following two commands on my computer:
1. `brew update`
2. `brew install valgrind`

# What happened (include command output)
I received the following output:
```
valgrind: This formula either does not compile or function as expected on macOS
versions newer than High Sierra due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

# What you expected to happen
I expected that Homebrew would install Valgrind.

# Step-by-step reproduction instructions (by running `brew install` commands)
Run the following commands on a computer running macOS Mojave
1. `brew update`
2. `brew install valgrind`

**Comment by SMillerDev** [comment]
The explanation why is in the error. This is an issue with upstream and should be fixed there.

**Comment by iFredOS** [comment]
@SMillerDev When this will be fixed?

**Comment by jonchang** [comment]
@iFredOS this is an issue with upstream. Please track the issue there: https://bugs.kde.org/show_bug.cgi?id=399584
