### ISSUE TITLE
Octave fails to build from source (java changes)

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/homebrew-core#39848]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/496f8476fdc52e6893177d95a5573809
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Build octave from source to transition to OpenBLAS
On master this still fails w/

`brew install -s octave`

- What happened (include command output)

```
build-aux/install-sh -c -d scripts/java/org/octave && \
        ( cd ./scripts/java; \
          "/Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/bin/javac" -source 1.6 -target 1.6 -Xlint:-options \
                     -d /private/tmp/octave-20190514-42663-hrgy0r/octave-5.1.0/scripts/java \
                     org/octave/ClassHelper.java )
Updating 'libgui/languages/uk_UA.qm'...
    Generated 48 translation(s) (0 finished and 48 unfinished)
    Ignored 863 untranslated source text(s)
build-aux/install-sh -c -d scripts/java/org/octave && \
        ( cd ./scripts/java; \
          "/Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/bin/javac" -source 1.6 -target 1.6 -Xlint:-options \
                     -d /private/tmp/octave-20190514-42663-hrgy0r/octave-5.1.0/scripts/java \
                     org/octave/Matrix.java )
Updating 'libgui/languages/zh_CN.qm'...
    Generated 856 translation(s) (842 finished and 14 unfinished)
    Ignored 55 untranslated source text(s)
build-aux/install-sh -c -d scripts/java/org/octave && \
        ( cd ./scripts/java; \
          "/Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home/bin/javac" -source 1.6 -target 1.6 -Xlint:-options \
                     -d /private/tmp/octave-20190514-42663-hrgy0r/octave-5.1.0/scripts/java \
                     org/octave/OctClassLoader.java )
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/ibeekman/Library/Caches/Homebrew/java_cache
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/ibeekman/Library/Caches/Homebrew/java_cache
Picked up _JAVA_OPTIONS:  -Duser.home=/Users/ibeekman/Library/Caches/Homebrew/java_cache
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
```

- What you expected to happen

Install octave from source

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install -s --verbose octave`

**Comment by zbeekman** [comment]
This relates to #39226 and #39809

**Comment by schoeps** [comment]
So it's supposed to be an OpenJDK problem? We use OpenJDK 11.0.2+9 for octave-app.

@apjanke did you add a particular fix for OpenJDK which I do not remember?

**Comment by zbeekman** [comment]
well, I don't think it's an OpenJDK problem per-se, just that we switched the default java (provided through a cask) to use openjdk instead of oracle recently. It looks like there are two lines that set source and target to 1.6 and they just need to be bumped to 1.7 to build:

```
Makefile.in
30418:    "$(JAVAC)" -source 1.6 -target 1.6 -Xlint:-options \

scripts/java/module.mk
50:       "$(JAVAC)" -source 1.6 -target 1.6 -Xlint:-options \
```

Does this need an upstream patch? Should there be some logic to determine if the java used supports 1.6? Or should it just be unilaterally bumped to 1.7?

**Comment by zbeekman** [comment]
Here is the recent java discussion: https://github.com/Homebrew/homebrew-cask-versions/issues/7253

**Comment by zbeekman** [comment]
Patch submitted upstream: https://savannah.gnu.org/patch/index.php?9806

Merging #39809 will close & fix this issue thanks to the patch.

**Comment by apjanke** [comment]
> @apjanke did you add a particular fix for OpenJDK which I do not remember?

Nope; OpenJDK is a drop-in replacement for Oracle JDK.

This sounds like just a JDK version thing, where JDK 12 has dropped support for 1.6 source/target formats. I think you'd have the same issue if you were running Oracle JDK 12.
