### ISSUE TITLE
gwenhywfar: cmake files points to linux name scheme (.so.soversion) instead of macos name scheme (.soversion.dylib)

### ISSUE THREAD

**Issue by sl1pkn07** [Homebrew/homebrew-core#39852]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
build new version of kmymoney (https://github.com/KDE-mac/homebrew-kde/blob/kmymonney%2Blibalkimia/Formula/kmymoney.rb)
- What happened (include command output)
~~~
CMake Error at /usr/local/lib/cmake/gwenhywfar-4.20/gwenhywfar-config.cmake:7 (message):
  File or directory
  /usr/local/Cellar/gwenhywfar/4.20.0/lib/libgwenhywfar.so.60 referenced by
  variable GWENHYWFAR_LIBRARIES does not exist !
Call Stack (most recent call first):
  /usr/local/lib/cmake/gwenhywfar-4.20/gwenhywfar-config.cmake:26 (set_and_check)
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
  /usr/local/lib/cmake/aqbanking-5.7/aqbanking-config.cmake:20 (find_dependency)
  CMakeLists.txt:220 (find_package)


-- Configuring incomplete, errors occurred!
- What you expected to happen
~~~
- Step-by-step reproduction instructions (by running `brew install` commands)
simply `brew install kmymoney.rb --verbose` when tap the repository and `brew pull` the commits up to the latest commit in the cited branch

`cat` the file `/usr/local/lib/cmake/gwenhywfar-4.20/gwenhywfar-config.cmake` or `/usr/local/Cellar/gwenhywfar/4.20.0/lib/cmake/gwenhywfar-4.20/gwenhywfar-config.cmake` (as you prefeer) and see the line 7
~~~
set_and_check(GWENHYWFAR_LIBRARIES "${exec_prefix}/lib/libgwenhywfar.so.60")
~~~

seems the name of the library extension is hardcoded by upstream https://github.com/aqbanking/gwenhywfar/blob/master/gwenhywfar-config.cmake.in#L26

and should be change it in homebrew side to point it to use macos library name scheme (.soname.dylib) when is builded or prepare to build

greetings

**Comment by zbeekman** [comment]
> seems the name of the library extension is hardcoded by upstream [aqbanking/gwenhywfar:gwenhywfar-config.cmake.in@`master`#L26](https://github.com/aqbanking/gwenhywfar/blob/master/gwenhywfar-config.cmake.in#L26) [](/aqbanking/gwenhywfar/blob/HEAD@{2019-05-14T18:16:48Z}/gwenhywfar-config.cmake.in#L26)
> 
> and should be change it in homebrew side to point it to use macos library name scheme (.soname.dylib) when is builded or prepare to build

This is a problem with upstream. (And the formula you're using it for is in a 3rd party tap.) As such, please report it upstream. If you report it to them and they are receptive to fixing it, then we would consider the contribution of a patch in homebrew (via a pull request) while we wait for upstream to publish the next release containing the fix.
