### ISSUE TITLE
Byobu: Copy and paste does not work out of the box

### ISSUE THREAD

**Issue by timothybasanov** [Homebrew/homebrew-core#39853]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Issue: After installing Byobu via HomeBrew tmux copy & paste does not work

Steps to reproduce:
1. `brew install byobu`
1. `byobu`
1. Make a tmux copy to clipboard action for say "foo"
1. <kbd>⌘V</kbd>

Expected: Clipboard works and "foo" is printed
Actual: Clipboard uses previous value, "foo" is not there

Workaround:
1. `brew install reattach-to-user-namespace`
1. Update tmux configs to use it: 
    ```bash
    tee --append ~/.byobu/keybindings.tmux <<EOF
    bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'command -v reattach-to-user-namespace >/dev/null && reattach-to-user-namespace pbcopy || pbcopy'
    EOF
    ```

Debug info:
```bash
> brew gist-logs byobu
Error: No logs.

> brew config
HOMEBREW_VERSION: 2.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: b4f73e61649fcfc5aaa779c311e2514619ce01e7
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c1f1304c3f0d6b419e54511b173ba7ed152e511
Core tap last commit: 3 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.hTgjBIieu8/org.macosforge.xquartz:0
HOMEBREW_LOGS: /Users/tbasanov/Library/Logs/Homebrew
HOMEBREW_VISUAL: subl -w
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202
macOS: 10.14.4-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: N/A
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11

> brew doctor
Your system is ready to brew.
```

**Comment by timothybasanov** [comment]
I'm not 100% sure, but it could be that the fix should be done instead on @dustinkirkland's side.

**Comment by dustinkirkland** [comment]
Hmm, I'm happy to review patches...  I still maintain Byobu, but I use it almost exclusively on Linux.  I'm delighted that others use it on MacOS with Homebrew, but I'm really a Mac user.  So if someone can triage and send a patch, I'm happy to take a look.  Thanks!

**Comment by iMichka** [comment]
As stated above, it looks like this is an upstream bug. No action is required on our side, so I'll just close this.
