### ISSUE TITLE
libelf: link rot

### ISSUE THREAD

**Issue by kousu** [Homebrew/homebrew-core#39870]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`libelf` uses a link-rotted upsteam: 

```
$ brew install --build-from-source libelf
==> Downloading http://www.mr511.de/software/libelf-0.8.13.tar.gz
######################################################################## 100.0%
curl: (6) Could not resolve host: leere.seite
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "libelf"
Download failed: http://www.mr511.de/software/libelf-0.8.13.tar.gz
```

It's been Bottled, so `brew install libelf` currently works.

```
$ brew gist-logs libelf
Error: No logs.

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  clang-format
  numpy
```

**Comment by jonchang** [comment]
Looks like we won't be able to continue packaging `libelf`. I've opened a pull request to drop this formula from Homebrew.

**Comment by kousu** [comment]
Maybe it'll come back in a few days or maybe someone broke into their website or we can contact the author and see what's up, or maybe we can rehost the code if someone can find a copy. Please don't be too hasty. This is an important dep of the arm cross compiler.

On May 15, 2019 3:03:42 AM EDT, Jonathan Chang <notifications@github.com> wrote:
>Looks like we won't be able to continue packaging `libelf`. I've opened
>a pull request to drop this formula from Homebrew.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Homebrew/homebrew-core/issues/39870#issuecomment-492530845

-- 
kousu

**Comment by zbeekman** [comment]
Looks like libelf moved to the elftoolchain project on SF: https://wiki.freebsd.org/LibElf

**Comment by kousu** [comment]
I don't think that's the same libelf, but maybe it's just as good or better.

There's a mirror of the GPL libelf at https://github.com/WolfgangSt/libelf. It looks like it's one below the same version that was removed: 0.8.12. There's also https://sourceforge.net/p/elftoolchain/code/HEAD/tree/branches/release-branch-0.7/ (which is the freebsd/sf.net libelf) which seems to be a drop-in compatible BSD-licensed replacement.  I'm going to see if either builds and test it by building avrdude.

**Comment by kousu** [comment]
I've spent all day trying to get the BSD libelf to build, but I'm stumped. My efforts are at https://github.com/kousu/homebrew-core/tree/libelf-bsd. I'm stuck on:

- the tests are failing because of [Darwin's wacky linker](https://blogs.oracle.com/dipol/dynamic-libraries,-rpath,-and-mac-os); I can patch around it with Brew's `MachO::Tools.change_install_name()` I think, and/or by setting `bmake LIBDIR="@rpath"` and `LD_LIBRARY_PATH`, but I have my doubts about how that will interact with installing the libs to their final homes; and because 
- even if I skip the tests (`bmake WITH_TESTS=no`), `install` fails with "no such file or directory" because the script from `bmake` that is supposed to make sure the install targets exist:

```
inc_mkdirs:
    for d in ${inc_mkdir_list:O:u}; do \
        @test -d ${DESTDIR}$$d || \
        ${INSTALL} -d ${INC_INSTALL_OWN} -m 775 ${DESTDIR}$$d; \
    done
```

is just not running for some reason. I am done with this for today. Maybe I will take another crack at it.

**Comment by kousu** [comment]
Anyway, @vszakats discovered a mirror of the GNU libelf on archive.org, and submitted that: https://github.com/Homebrew/homebrew-core/pull/39936

Probably that's safer than quietly switching gcc and avrdude to build against a BSD library.
