### ISSUE TITLE
Boost failed to build on 10.11.6 when setting --cc=gcc-4.2 and --build-from-source

### ISSUE THREAD

**Issue by themantalope** [Homebrew/homebrew-core#3991]
Hi All,

I'm trying to build boost with the GNU compiler version 4.2 (also installed with brew). Here is a link to the gist-logs: https://gist.github.com/themantalope/5733739f6a868457f601ae9a247dd0f4

Please let me know if anything else is needed.

**Comment by MikeMcQuaid** [comment]
It's very likely Boost can't build with GCC 4.2. Can I ask why you need to build on that version?

**Comment by themantalope** [comment]
I was trying to build with GCC 4.2 because another project which depended on boost suggested compiling with GCC 4.2 as well, and I wanted to make sure that the libraries and project were all compiled with the same compiler. If there is no way around this then that's fine, just let me know.

**Comment by MikeMcQuaid** [comment]
There's likely no way around that. We always suggest using default compilers.
