### ISSUE TITLE
Cannot get node@6.4.0

### ISSUE THREAD

**Issue by albinekb** [Homebrew/homebrew-core#3993]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
I want to upgrade to node 6.4.0, I've seen that it's in master (https://github.com/Homebrew/homebrew-core/blob/master/Formula/node.rb)
```
❯ brew update
Already up-to-date.
```
```
❯ brew upgrade node
Error: node 6.3.1 already installed
```
```
❯ brew install node --HEAD
Warning: node-6.3.1 already installed
```
Am i doing something wrong or have i misunderstood how brew works?

**Comment by DomT4** [comment]
You're probably stuck behind the bug we [tweeted about](https://twitter.com/MacHomebrew/status/763686348041641984). If you:
```bash
cd $(brew --repo); git fetch; git reset --hard origin/master
```
Can you `brew upgrade node` okay?

**Comment by dunn** [comment]
`brew update && brew upgrade node` should do what you want; you're trying to install the HEAD version of node, which is different from the stable version (which is 6.4.0).

**Comment by albinekb** [comment]
That worked! Thanks, missed the tweet 👍

**Comment by dunn** [comment]
Oops, didn't see you tried `brew upgrade node` in addition to `brew install --HEAD`.

**Comment by DomT4** [comment]
@albinekb Sorry for the inconvenience! 😢.

**Comment by albinekb** [comment]
@DomT4 No problem, brew is still the best thing ever 💜 I'll make sure to help others stuck on the same problem

**Comment by DomT4** [comment]
Thanks! ❤️

These sorts of issues should almost never happen once we declare `Homebrew` (the core code) 1.0. We've been pushing a lot of changes lately to get there & the breakage here managed to slip past our test-suite.

**Comment by albinekb** [comment]
And sorry for not reading the big headline in the readme AND missing the line in the issue-template, a bit tired i guess.. 💤 😴

**Comment by DomT4** [comment]
I spent a whole hour this evening debugging a piece of code that wasn't working to discover that everything was broken because I'd used the wrong variable in the wrong place; I cannot judge mistakes of tiredness today, evidently 😄.
