### ISSUE TITLE
asciidoctor missing/unlinked man page

### ISSUE THREAD

**Issue by geraldcombs** [Homebrew/homebrew-core#39948]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I was trying to view the asciidoctor man page in order to learn about its various command line options.

- What happened (include command output)

`man` couldn't find the man page:
```
$ man asciidoctor
No manual entry for asciidoctor
```

- What you expected to happen

I expected `man asciidoctor` to show me the asciidoctor(1) man page.

- Step-by-step reproduction instructions (by running `brew install` commands)

1. Run `brew install asciidoctor`
1. Run `find /usr/local/Cellar/asciidoctor -name asciidoctor.1`. On my system, this shows that asciidoctor.1 exists in `/usr/local/Cellar/asciidoctor/2.0.9/libexec/gems/asciidoctor-2.0.9/man`.
1. Run `man asciidoctor`. On my system this returns "No manual entry for asciidoctor".

**Comment by jonchang** [comment]
Hi @geraldcombs thanks for reporting this issue. Can you please [open a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) fixing this? Looking at the `asciidoctor` formula you should just need to add a `man1.install` directive to get the manpage included. Feel free to open a pull request even with an incomplete solution, since reviewing code will be easier.
