### ISSUE TITLE
Carthage is causing `brew update` to fail on TravisCI Yosemite image

### ISSUE THREAD

**Issue by bobsummerwill** [Homebrew/homebrew-core#3996]
It appears that something has changed within Homebrew within the last few hours which is causing TravisCI OS X Yosemite images which were previously working to break.   This breakage might be sporadic, rather than 100% reproducible.

`brew update && brew upgrade` within those TravisCI projects is now failing like so:

    carthage: A full installation of Xcode.app 7.3 is required to compile this software.
    Installing just the Command Line Tools is not sufficient.
    Xcode can be installed from the App Store.
    Error: An unsatisfied requirement failed this build.

The TravisCI Yosemite image has xcode 7.1, not xcode 7.3.

Which appears to be the same as this (closed) issue, CC @mdiep.   I haven't determined whether this is a Homebrew Formula issue, or something else.

https://github.com/Carthage/Carthage/issues/473#issuecomment-240579594

For our projects, we aren't using carthage at all, but are just hitting this issue during a standard `brew update && brew upgrade` prior to doing any of our project-specific stuff.

Here is an instance of the failure https://travis-ci.org/ethereum/cpp-ethereum/builds/153117739.

Best wishes!

**Comment by mistydemeo** [comment]
Looking at the `brew upgrade`, your TravisCI image has an older carthage already installed; it's trying to upgrade from source, which is failing because of the Xcode version.

**Comment by mdiep** [comment]
Newer Carthage requires Swift 2.2 which is only in Xcode 7.3. This is fallout from the rapidly changing Swift language and its lack of backwards compatibility. There's no way to build recent Carthage on Xcode 7.1. It's literally impossible.

You'll need to upgrade to a newer Xcode version or live with older versions of Carthage.

**Comment by bobsummerwill** [comment]
Hey @mistydemeo and @mdiep,

Thanks for the speedy replies, but there is something more to this issue, I think.

Look at https://travis-ci.org/ethereum/cpp-ethereum/builds/153117739

Why isn't the same issue happening for the OS X Mavericks configuration, which uses xcode 6.2?

More importantly, why is this issue appearing just today, literally just a few hours ago, with the TravisCI configuration not changing, where the carthage formula has seemingly not changed in over 2 weeks?    Did something change with bottles?

**Comment by bobsummerwill** [comment]
RE: `You'll need to upgrade to a newer Xcode version or live with older versions of Carthage.`

So I don't think that updating xcode is possible within that TravisCI image.    Living with an older version of carthage is entirely possible, because we're not even using carthage.   That would, however, mean avoiding a blanket `brew upgrade` and replacing that with a prescriptive list of specific package names, which is a maintenance burden which I would really like to avoid.

I imagine this issue will hit a bunch of TravisCI users as well as us.    Though I still can't put my finger on exactly why this issue has started happening just today.    **What changed?** :-)

**Comment by MikeMcQuaid** [comment]
> Newer Carthage requires Swift 2.2 which is only in Xcode 7.3. This is fallout from the rapidly changing Swift language and its lack of backwards compatibility. There's no way to build recent Carthage on Xcode 7.1. It's literally impossible.

I have no idea if it's possible but using our `swift` formula may allow Carthage (and other Swift things) to be built on older versions of Xcode/OS X if anyone want to try a PR.

> I imagine this issue will hit a bunch of TravisCI users as well as us. Though I still can't put my finger on exactly why this issue has started happening just today.

I'm afraid we don't support Travis CI specifically so you'd need to contact them to ask.

> What changed? :-) 

A newer version of Carthage was released.
