### ISSUE TITLE
minidlna's "Caveats" mentions a non-existent binary

### ISSUE THREAD

**Issue by numbermaniac** [Homebrew/homebrew-core#39984]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (`Error: No logs.`)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)
----
I installed `minidlna` using `brew install minidlna`.  The caveats listed after installing said:
```
Simple single-user configuration:

mkdir -p ~/.config/minidlna
cp /usr/local/opt/minidlna/share/minidlna/minidlna.conf ~/.config/minidlna/minidlna.conf
ln -s YOUR_MEDIA_DIR ~/.config/minidlna/media
minidlnad -f ~/.config/minidlna/minidlna.conf -P ~/.config/minidlna/minidlna.pid

To have launchd start minidlna now and restart at login:
  brew services start minidlna
Or, if you don't want/need a background service you can just run:
  minidlna
```
Initially I couldn't find `minidlnad` to complete the 4th command, but eventually I found it at `/usr/local/sbin/minidlnad` (Not sure why it's not in regular `/usr/local/bin`, but alright). After running that command, I tried to follow that last line which simply says to run `minidlna`. However, I can't seem to find a binary with that name anywhere.

```sh
> sudo find /usr/ | grep -i minidlna
/usr//local/sbin/minidlnad
/usr//local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/minidlna.rb
/usr//local/var/homebrew/linked/minidlna
/usr//local/opt/minidlna
/usr//local/Cellar/minidlna
/usr//local/Cellar/minidlna/1.2.1_1
/usr//local/Cellar/minidlna/1.2.1_1/homebrew.mxcl.minidlna.plist
/usr//local/Cellar/minidlna/1.2.1_1/INSTALL_RECEIPT.json
/usr//local/Cellar/minidlna/1.2.1_1/.brew
/usr//local/Cellar/minidlna/1.2.1_1/.brew/minidlna.rb
/usr//local/Cellar/minidlna/1.2.1_1/ChangeLog
/usr//local/Cellar/minidlna/1.2.1_1/AUTHORS
/usr//local/Cellar/minidlna/1.2.1_1/sbin
/usr//local/Cellar/minidlna/1.2.1_1/sbin/minidlnad
/usr//local/Cellar/minidlna/1.2.1_1/README
/usr//local/Cellar/minidlna/1.2.1_1/TODO
/usr//local/Cellar/minidlna/1.2.1_1/COPYING
/usr//local/Cellar/minidlna/1.2.1_1/NEWS
/usr//local/Cellar/minidlna/1.2.1_1/share
/usr//local/Cellar/minidlna/1.2.1_1/share/minidlna
/usr//local/Cellar/minidlna/1.2.1_1/share/minidlna/minidlna.conf
/usr//local/share/minidlna
```

All the lines that end in `minidlna` are folders, not files. Bash says "minidlna: command not found". Is the binary missing, or is the Caveats message incorrect? Should it tell me to run `minidlnad` instead?

**brew config**
```
HOMEBREW_VERSION: 2.1.2-56-g5a63de0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a63de02237b7639796844888c57da5e03d4ec5f
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f140c105c1331bd98a6afaae0103f489ae5e347
Core tap last commit: 35 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_102
macOS: 10.14.4-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
```
**brew doctor**: https://gist.github.com/numbermaniac/3256749cc9b5c2c62d43ccad30ff21c7

**Comment by SMillerDev** [comment]
`/usr//local/Cellar/minidlna/1.2.1_1/sbin/minidlnad` is in your list. 

> Should it tell me to run minidlnad instead?

It does

**Comment by numbermaniac** [comment]
@SMillerDev No, the Caveats section says to run `minidlna`, NOT `minidlnad`. One letter difference. It tells me to run `minidlna` which does not exist, but fails to mention `minidlnad`.
