### ISSUE TITLE
why supervisor start with --nodaemon option

### ISSUE THREAD

**Issue by mitoop** [Homebrew/homebrew-core#39986]
In [supervisor.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/supervisor.rb) supervisor init with `--nodaemon` option,
Could i ask why do this? In fact,  in `/usr/local/etc/supervisord.ini` , config has option `nodaemon` option 
```
nodaemon=false               ; start in foreground if true; default false
```
What i want to say is that  user can change `nodaemon` option  in `/usr/local/etc/supervisord.ini` manually, when set in supervisor.rb, it will force start in foreground.

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by mitoop** [comment]
@iMichka Sorry, got it.
