### ISSUE TITLE
Independent Datadir for different versions of MySQL

### ISSUE THREAD

**Issue by tomy0000000** [Homebrew/homebrew-core#39983]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Giving Different Versions of MySQL their Independent Data Directory

By Default,
every mysql formula sets datadir to a default of _var/"mysql"_
So If one tries to install multiple mysql versions,
the datadir will be messed up by the newly installed version.
As for the results,
some version may still be functioning while others were not so lucky
(Situation may differs)

So what I'm proposing is
giving different versions of mysql formula a different datadir,
for example _mysql@5.7_ a datadir of _var/mysql@5.7_ corresponds to the formula name.
I've tested on my machine that this configuration **works**.

However, one thing worth mentioning is that
They'll have to share the same default my.cnf,
which means there can **only be one mysql server be running** simultaneously.
(without any additional argument passed)
Perhaps this should be mentioned in every mysql formula

- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install mysql@5.7
brew services start mysql@5.7
brew services stop mysql@5.7
brew install mysql
brew services start mysql
brew services stop mysql
brew services start mysql@5.7
# mysql@5.7 failed to start
```

```bash
brew edit mysql@5.7
# (Chang Following)
# def datadir
#     var/"mysql"
# (Into)
# def datadir
#     var/"mysql@5.7"
brew install mysql@5.7
brew install mysql
# mysql and mysql@5.7 both functioning
```

**Comment by MikeMcQuaid** [comment]
> They'll have to share the same default my.cnf, which means there can **only be one mysql server be running** simultaneously.

Given this I'm not sure what the advantage would be? Note we shouldn't change the default for `mysql` and would need to have a fallback for `mysql@5.6` and friends to avoid breaking existing configurations. There's a decent argument that `mysql@5.6` with a new install (i.e. no existing data) could use its own `datadir` and configuration, though.

Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by iMichka** [comment]
This has been open since May. You could submit a pull request so that we can discuss the implementation. Looks like you are the only one needing this right now, as nobody else commented on this issue. I'll close this as we won't be spending more time on this right now.
