### ISSUE TITLE
Qt 5 assistant not found

### ISSUE THREAD

**Issue by Nelson-numerical-software** [Homebrew/homebrew-core#40036]
It seems that Qt 5 Assistant is not packaged with Qt available in brew.
Could you explain why ? (license ?)
Or did I miss something ?

**Comment by SMillerDev** [comment]
Nobody packaged it yet. You could make a pull request to change that.

**Comment by Nelson-numerical-software** [comment]
Sorry, but I am currently only an user of Brew (it is a great tools)
here qt4 assistant formulae https://github.com/gmrandazzo/homebrew-gmr/blob/master/qt-assistant-compat.rb maybe easy to port from qt4  to qt5 (?)

**Comment by SMillerDev** [comment]
We don't accept formula requests as issues. If you don't care enough to make this adjustment to the formula, how can you expect the maintainers to care enough to maintain it?

**Comment by Nelson-numerical-software** [comment]
hum, so where can I create a request for this feature (formula) ?

**Comment by SMillerDev** [comment]
You can create a pull request to contribute the required change. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
