### ISSUE TITLE
Update to RJVB's afsctool fork

### ISSUE THREAD

**Issue by saizai** [Homebrew/homebrew-core#40041]
[Current Homebrew version](https://github.com/Homebrew/homebrew-core/blob/master/Formula/afsctool.rb) fails on Mojave with the error "Expecting f_type of 17, 23 or 24. f_type is 25."

[RJVB's fork](https://github.com/RJVB/afsctool) works just fine, and also has some other improvements like multithreading.

Please update the formula to point to the @RJVB version.

**Comment by fxcoudert** [comment]
It's not an official fork, and does not appear to be widely used (per our policy: https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md)

**Comment by RJVB** [comment]
>It's not an official fork

Define "official fork"??

Not that I care one way or another; I'd never use or recommend HB and didn't push for my version to be used in MacPorts (which I do use) either.

**Comment by SMillerDev** [comment]
Someone made the official software, homebrew really only deviates from that upstream unless a fork is appointed as the official successor by upstream.

**Comment by RJVB** [comment]
As I thought, that's not a fork anymore O:^)

**Comment by SMillerDev** [comment]
If it's a completely new piece of software a new formula could be made if it meets the requirements defined in the documentation: https://docs.brew.sh/Acceptable-Formulae#acceptable-formulae

**Comment by sdsnatcher** [comment]
Brkirch's afsctool had its last release ages ago (half a decade) and doesn't work on newer macOS releases.

IMHO, this means that it doesn't comply with the following requirement anymore, and should be deprecated in favour of RJVB's version:
- be maintained (i.e. the last release wasn’t ages ago, it works without patching on all supported macOS releases and has no outstanding, unpatched security vulnerabilities)

**Comment by Antonz0** [comment]
So, it was just closed without even considering latest comments by @SMillerDev  and @sdsnatcher  ?

**Comment by RJVB** [comment]
FWIW, my fork is now in MacPorts (hint, hint ;))

**Comment by SMillerDev** [comment]
> So, it was just closed without even considering latest comments by @SMillerDev  and @sdsnatcher  ?

@Antonz0 those are after closure, but please make a pull request to perform changes.
