### ISSUE TITLE
OS X 11.12 install git error

### ISSUE THREAD

**Issue by henjue** [Homebrew/homebrew-core#4004]
apple@MacBook  ~/android/cm  brew install git
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Volumes/android in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Volumes/android in PATH, mode 040777
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16/rbconfig.rb:213: warning: Insecure world writable dir /Volumes/android in PATH, mode 040777
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.9.0.tar.xz
######################################################################## 100.0%
==> make install prefix=/usr/local/Cellar/git/2.9.0 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
Last 15 lines from /Users/apple/Library/Logs/Homebrew/git/01.make:
'unistd.h' file not found
./git-compat-util.h:158:10: fatal error: 'unistd.h' file not found
#include <unistd.h>
         ^#include <unistd.h>
         ^

#include <unistd.h>
         ^
1 error generated.
make: *** [hex.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
1 error generated.
make: *** [kwset.o] Error 1
make: *** [ident.o] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
'brew install git' and '>=' error https://github.com/Homebrew/homebrew-core/issues/3864
hg-git 0.8.5 (new formula) https://github.com/Homebrew/homebrew-core/pull/2577
git-webui 1.2.0 (new formula) https://github.com/Homebrew/homebrew-core/pull/1648
cannot install on Mac OSX 10.8.5 ==> Downloading and installing Homebrew... You must: brew install git You must: brew install git Error: Git is unavailable https://github.com/Homebrew/homebrew-core/issues/2385
git-stree: added deprecation warning and fixed line order https://github.com/Homebrew/homebrew-core/pull/1842
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

But also note:

> Warning: You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages.

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

In fact: I'll reopen this when you follow this.
