### ISSUE TITLE
Gitlab CI Multi Runner : Is it possible to use the Docker for Mac installed version instead of the docker formula ?

### ISSUE THREAD

**Issue by shulard** [Homebrew/homebrew-core#4005]
Hello,

I tried to install Gitlab CI Multi Runner formula on my computer and faced a little issue. I currently use the Docker For Mac binaries.

This formula depends on Docker so when I install it, the docker formula is installed... With that process I have 2 docker versions on my mac, the brew one and the docker for mac one.

Is it possible to only depends on a docker binary, not only the brew one ?

**Comment by MikeMcQuaid** [comment]
> Is it possible to only depends on a docker binary, not only the brew one ?

Not currently, sorry.
