### ISSUE TITLE
Some Java formula upgrade failed

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#40085]
https://github.com/Homebrew/homebrew-core/pull/39682
https://github.com/Homebrew/homebrew-core/pull/39691
https://github.com/Homebrew/homebrew-core/pull/39705

I will try to downgrade to the original one and rerun the PR to see if the issue still exists.

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/39997

**Comment by fxcoudert** [comment]
These need to be fixed one by one, I don't think there is anything systematic about it.
