### ISSUE TITLE
I don't know where to ask for FEATURE REQUEST for mpd, please help

### ISSUE THREAD

**Issue by nadstaky** [Homebrew/homebrew-core#40098]
I DO know that this is a place for bug report.

The fact is that I can't find where is "Feature request".

I'd like someone to give me a link PLEASE 👍 

OR : my feature request is "Add pulseaudio support for mpd player daemon"

Thanks in advance.

PLEASE DON'T CLOSE BEFORE GIVING ME INSTRUCTIONS....

Eric

**Comment by iMichka** [comment]
Hi

You could ask somebody to look at it at https://discourse.brew.sh.

We only accept pull requests when you ask for a feature request, sorry.
