### ISSUE TITLE
post-install hook for git-lfs

### ISSUE THREAD

**Issue by technoweenie** [Homebrew/homebrew-core#4010]
Do formulas have some kind of post-install hook? I want the `git-lfs` formula to run `git lfs install` at the end, which sets up some `filter.lfs.*` values in the user's global git config. I initially tried this:

```diff
diff --git a/Formula/git-lfs.rb b/Formula/git-lfs.rb
index 7b00fcb..fd74a83 100644
--- a/Formula/git-lfs.rb
+++ b/Formula/git-lfs.rb
@@ -16,6 +16,7 @@ class GitLfs < Formula
   def install
     system "./script/bootstrap"
     bin.install "bin/git-lfs"
+    system "git", "lfs", "install"
   end
```

I didn't see any mention of it during install. Then I realized that's because it was grabbing the bottle instead of building locally. Is there some way to get the `git-lfs` formula to run on every source or bottle install, maybe even when the version is linked?

**Comment by MikeMcQuaid** [comment]
You could use a `post_install` method:

```
  def post_install
    system "#{bin}/git-lfs", "install"
  end
```

However: 

> in the user's global git config

We generally avoid ever automatically running commands that change stuff in `$HOME` so you may want to just print `caveats` for this. CC @DomT4 for thoughts on this, though.

**Comment by technoweenie** [comment]
Thanks @MikeMcQuaid, I think I'll go the `caveats` route. Then we can also suggest `git lfs install --system` if users wish.  :metal:

**Comment by DomT4** [comment]
Aye, as a rule nothing in `install` or `post_install` should deliberately touch anything outside of `HOMEBREW_PREFIX`.
