### ISSUE TITLE
gcc fails during make on OS X 10.11.5

### ISSUE THREAD

**Issue by jennybrown8** [Homebrew/homebrew-core#4013]
I ran brew update twice.  I ran brew doctor and it said 'ready to brew' - no warnings.  Permissions should be good as other brew packages are working.

`brew install gcc` fails during make with the error:

```
make[4]: *** [multi-do] Error 1
make[3]: *** [all-multi] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2
```

which is captured in the gist logs:
https://gist.github.com/anonymous/976b414fb79172ecb48f8ff66341bd74

XCode and XCode CLT are up to date (7.3.1).  This is on a test machine which is re-imaged and reinstalled daily, and which has been failing daily now for a while on this error.  I'm the admin and have full control of the install configuration, so experimenting / troubleshooting should be fairly easy.

The gcc dependency is being pulled in because it's used by gdal, but it appears to be gcc itself that's failing to build.  As far as I know I am not version-pinning and am accepting whichever version is latest.

**Comment by MikeMcQuaid** [comment]
Not sure on the problem here or how to fix but:

> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/homebrew
> HOMEBREW_CELLAR: /usr/local/homebrew/Cellar

If you create `/usr/local/Cellar` it'll use that for your HOMEBREW_CELLAR and then you'll be able to use the binary package instead.

**Comment by DomT4** [comment]
New `gcc` was merged today. Might be worth trying `brew update` & attempting the installation again.

**Comment by jennybrown8** [comment]
It appears to be happening still.

**Comment by dunn** [comment]
> It appears to be happening still.

Is it the same error?  Could you post `gist-logs` for the new version?

**Comment by jennybrown8** [comment]
Fresh gist logs:  https://gist.github.com/7ce0693b2513b68455240f3ddda9129c

Error appears to be the same at a surface read, although the messages aren't exactly informative to the casual reader.

```
make[4]: *** [multi-do] Error 1
make[3]: *** [all-multi] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [all-stage1-target-libgcc] Error 2
make[1]: *** [stage1-bubble] Error 2
make: *** [bootstrap] Error 2

```

**Comment by dunn** [comment]
The actual error is higher up, but I don't know enough in this domain to fix it:
```
../../../../libgcc/libgcc2.c:2114:12: error: 'stderr' undeclared (first use in this function)
   fprintf (stderr, string, expression, line, filename);
^~~~~~

**Comment by MikeMcQuaid** [comment]
> If you create /usr/local/Cellar it'll use that for your HOMEBREW_CELLAR and then you'll be able to use the binary package instead.

@jennybrown8 I'd advise you do this instead as we seem to be stuck and can't figure out how to fix this, I'm afraid.
