### ISSUE TITLE
Issues with kqueue in Mono for filesystem watching on OS X 10.14.1

### ISSUE THREAD

**Issue by kqr** [Homebrew/homebrew-core#40138]
This relates to [issue #331](https://github.com/fsharp/FsAutoComplete/issues/331) on [FsAutoComplete](https://github.com/fsharp/FsAutoComplete).

Steps to reproduce:

1. Boot fresh OS X 10.14.1.
2. `brew install mono`.
3. Clone FsAutoComplete.
4. Build FsAutoComplete with `build.sh`.
5. Run FsAutoComplete with `mono src/FsAutoComplete/bin/Release/net461/fsautocomplete.exe`.
6. Try to load a project in FsAutoComplete with `project "src/FsAutoComplete/FsAutoComplete.fsproj"`.
7. Get exception attached below.

Steps to work around:

1. Run FsAutoComplete with `MONO_MANAGED_WATCHER=disabled` to get around kqueue filesystem watcher issues.
2. Try to load a project in FsAutoComplete with `project "src/FsAutoComplete/FsAutoComplete.fsproj"`.
3. See project loaded successfully.

Steps to solve:

1. Install mono from www.mono-project.com instead of Homebrew.
2. Run FsAutoComplete with `mono src/FsAutoComplete/bin/Release/net461/fsautocomplete.exe`.
3. Try to load a project in FsAutoComplete with `project "src/FsAutoComplete/FsAutoComplete.fsproj"`.
4. See project loaded successfully.

In summary:

1. The mono runtime distributed with Homebrew seems to have some issue the official distribution does not.
2. This is related to the runtime and not the compiler, because the official distribution runs code compiled by the Homebrew distribution.
3. This is related to kqueue because turning off the filesystem watcher in FsAutoComplete seems to work around the issue in the runtime distributed with Homebrew.

I am sorry I haven't got an easier way to reproduce this – I don't know very much about what's going wrong (and I'm not very well versed in OS X generally). I'll happily receive suggestions for things to try to work out more specifically what could be wrong.

I understand this issue is not strictly related to the homewbrew infrastructure, and is more about a specific package distributed over homebrew, but this is the only place I could think of to report this.

**Comment by UlrichThomasGabor** [comment]
Maybe try the `--build-from-source` option? If this version does not work either, there may be a difference between the build process used by brew (see [mono.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mono.rb)) and the way it is build for the official website.

**Comment by ZzAntares** [comment]
Not the OP but for the record I did reinstalled mono with the `--build-from-source` flag, but in the end I had the same results. Only downloading the installer from mono-project.com make the error go away.

**Comment by fxcoudert** [comment]
Does this happen after update to the latest `mono`?

**Comment by iMichka** [comment]
Let's close this. The issue can be reopened if there still an issue with the latest version of `mono` in brew.
