### ISSUE TITLE
whois formula missing mkpasswd binary

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#40147]
Debian currently bundles `mkpasswd`, an important security utility, in its whois package:

https://packages.debian.org/stretch/amd64/whois/filelist

Homebrew features a whois package, however this binary is omitted from installation.

https://formulae.brew.sh/formula/whois

Can we please make sure that the full set of artifacts in the whois package get installed in macOS, so that mac users can enjoy the use of `mkpasswd`?

**Comment by SMillerDev** [comment]
If by "can we make sure to" you mean "I'll make a pull request to" then absolutely. Otherwise homebrew doesn't accept feature requests as issues.
