### ISSUE TITLE
Not possible compile Go 1.7 with newer CLT on macOS Sierra

### ISSUE THREAD

**Issue by deepj** [Homebrew/homebrew-core#4015]
Git logs: https://gist.github.com/deepj/f9514ed6ecd2c92f19dd5df2ff71a333

After yesterday's update of CLT I can't compile Go again. With previous CLT I could compile Go 1.7.

`brew doctor` doesn't report any issues.

**Comment by DomT4** [comment]
Track https://github.com/Homebrew/brew/pull/741. We're working on it.
