### ISSUE TITLE
`brew update` fails, just reports "Already up-to-date."

### ISSUE THREAD

**Issue by romellem** [Homebrew/homebrew-core#4016]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

---

As the title says, running `brew update` from my command line gives a message of "**Already up-to-date.**" even though I can see from this repo I should be getting some new formulas.

Currently, my **core** version is at commit [bcb5cf68](https://github.com/Homebrew/homebrew-core/commit/bcb5cf680ae83de77e0ab35657f6d7fd014b28a0), as you can see from the output from `brew config`:

```
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 06fe347de97975dc01e726f87bf07a56a6fb713e
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bcb5cf680ae83de77e0ab35657f6d7fd014b28a0
Core tap last commit: 8 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.9.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.8.0_66
OS X: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
https://github.com/homebrew/brew#update-bug should fix this for you.

**Comment by romellem** [comment]
Awesome, tried searching on Google before posting an issue, but somehow that didn't come up.

Fixed the issue completely.

Thanks!

**Comment by MikeMcQuaid** [comment]
Also added more notes in here https://github.com/Homebrew/homebrew-core/commit/14790e3b57017db006feaf0a941a13cf12d8bcfe

**Comment by fuzzyroddis** [comment]
Could the fix please be accompanied with what caused the problem?

**Comment by MikeMcQuaid** [comment]
@fuzzyroddis https://github.com/Homebrew/brew/pull/669#discussion_r74397616. Have added a better future workaround in https://github.com/Homebrew/brew/pull/689 and a test that would have caught this in b9d5b11f321a359b462aa2c353c2bdb483930fb3.
