### ISSUE TITLE
Unable to install octave on OSX 10.11.6

### ISSUE THREAD

**Issue by jackson312** [Homebrew/homebrew-core#4030]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

# Please follow the general troubleshooting steps first:

- [x ] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

I am unable to install octave on OSX 10.11.6.

I have tried `brew uninstall -f $(brew deps -r octave)` but this did not help
https://gist.github.com/c25181835983b286ac686566dfa16ab8

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#4075
