### ISSUE TITLE
mpop: Support for TLS isn't compiled in

### ISSUE THREAD

**Issue by baskerville** [Homebrew/homebrew-core#40349]
This is a recent regression: running `mpop -a` yields `mpop: support for TLS is not compiled in`.

And, as expected,`mpop --version | grep TLS` yields `TLS/SSL library: none`.

**Comment by MikeMcQuaid** [comment]
From the issue template:

> **Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

If you add the necessary information to this issue (don't create a new one, please) then this issue may be reopened.
