### ISSUE TITLE
brew install dnsmasq prints with post-install step did not complete successfully

### ISSUE THREAD

**Issue by unmec** [Homebrew/homebrew-core#40366]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Install dnsmasq

- What happened (include command output)
```brew install dnsmasq``` prints the following:
```
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall dnsmasq`
```
When ```brew postinstall dnsmasq```, it gives the exact same error message.

- What you expected to happen
It should run without error.

- Step-by-step reproduction instructions (by running `brew install` commands)
Just run ```brew install dnsmasq```

My ```brew gist-logs dnsmasq``` output:
```
Error: No logs.
```

My ```brew config``` output:
```
HOMEBREW_VERSION: 2.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 099b047349d4ec67519206f15401d0e1cf90e953
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe8e2491071aa410f402fdf71555cfa8b4619bb1
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 9.0.4, 1.8.0_171, 1.6.0_65-b14-468
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
```

My ```brew doctor``` output:
```
Your system is ready to brew.
```

I am also able to reproduce this issue by running ``` brew reinstall dnsmasq```.

**Comment by MikeMcQuaid** [comment]
> When `brew postinstall dnsmasq`, it gives the exact same error message.

What's the output of `brew postinstall dnsmasq --verbose --debug`? Thanks!

**Comment by unmec** [comment]
Thanks for the hint, I did run ```--verbose``` before but found no helpful message, however with ```--debug```, it reveals the reason:
```
==> An exception occurred within a child process:
  Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/local/var/lib/misc
```

Then I just manually create ```misc``` folder with ```sudo``` and ```brew reinstall dnsmasq``` returns no more error message.

Thanks!
