### ISSUE TITLE
Problem with installing xDebug with PHP Homebrew

### ISSUE THREAD

**Issue by AnthonyWebDev** [Homebrew/homebrew-core#40399]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Hi everyone,

I am currently working with PHP 7.3.5 installed via Homebrew. Until here, everything is okay.
Today i wanted to install `xDebug` with `pecl` so i did a `pecl install xdebug` everything was running good until i get this error message :

`Build process completed successfully
Installing '/usr/local/Cellar/php/7.3.5/pecl/20180731/xdebug.so'

Warning: mkdir(): File exists in System.php on line 294
PHP Warning:  mkdir(): File exists in /usr/local/Cellar/php/7.3.5/share/php/pear/System.php on line 294

Warning: mkdir(): File exists in /usr/local/Cellar/php/7.3.5/share/php/pear/System.php on line 294
ERROR: failed to mkdir /usr/local/Cellar/php/7.3.5/pecl/20180731`

Is there any link with the symlink in `/usr/local/Cellar/php/7.3.5/` ? Check it ou :

`[7.3.5] $ ls -la
lrwxr-xr-x   1 anthony  staff     23 24 mai 00:47 pecl -> /usr/local/lib/php/pecl`

Thanks for your help guys !

**Comment by SMillerDev** [comment]
So, what's the content of `/usr/local/lib/php/pecl` then?

**Comment by CameronPorter95** [comment]
I had the same problem, there was a pecl shortcut in ```/usr/local/Cellar/php@7.1/7.1.22/``` I just deleted that and it worked. I'm assuming it wasn't needed since it didn't point anywhere.
