### ISSUE TITLE
Docker v1.12.1 compilation crashes with "ld: weak import of symbol '_SecCertificateCopyNormalizedIssuerContent'"

### ISSUE THREAD

**Issue by spaquet** [Homebrew/homebrew-core#4047]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

# Please follow the general troubleshooting steps first:

- [X ] Ran `brew update` and retried your prior step? ->Already up-to-date
- [X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

brew upgrade docker

==> Upgrading 1 outdated package, with result:
docker 1.12.1
==> Upgrading docker
==> Using the sandbox
==> Cloning https://github.com/docker/docker.git
Updating /Users/spaquet/Library/Caches/Homebrew/docker--git
==> Checking out tag v1.12.1
==> hack/make.sh dynbinary-client
Last 15 lines from /Users/spaquet/Library/Logs/Homebrew/docker/01.make.sh:
hack/make.sh
dynbinary-client

# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#

---> Making bundle: dynbinary-client (in bundles/1.12.1/dynbinary-client)
Building: bundles/1.12.1/dynbinary-client/docker-1.12.1
# crypto/x509
ld: weak import of symbol '_SecCertificateCopyNormalizedIssuerContent' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`brew gist-logs docker`
https://gist.github.com/c3c43394fda9f5d4c71f26a095ef842f

**Comment by deepj** [comment]
@MikeMcQuaid Hello, how this is fixed? Because it's still occurring with up-to-date Homebrew. Thanks for an answer in advance.

**Comment by MikeMcQuaid** [comment]
@deepj Please open a new issue and follow the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by deepj** [comment]
@MikeMcQuaid Ok, I'll make it soon. Just don't have my mac near except my iPad. But my issue is the same as above. So probably it'd be a duplicitity.
