### ISSUE TITLE
[syncthing] launchd fails starting up

### ISSUE THREAD

**Issue by Kriechi** [Homebrew/homebrew-core#4051]
The plist for syncthing to be loaded with `brew services start syncthing` only writes an error messages to the stderr logfile for me, and does not successfully launch syncthing.

Latest formula with included launchd plist file I'm testing with is [here](https://github.com/Homebrew/homebrew-core/blob/d62a98e89bee4ebbfd832dc566e0e95f93e983e3/Formula/syncthing.rb#L31-L60) (v0.14.4).

I get repeated error message in `/usr/local/var/log/syncthing.log`:
```
19:38:57 FATAL: No home directory found - set $HOME (or the platform equivalent).
...
```
Which, of course, makes sense. How should syncthing know where the config is, and for which user to run?

Maybe it would be a suitable solution to update the formula with the latest plist file from the syncthing repo? However, I'm not sure how the username could be supplied as option. https://github.com/syncthing/syncthing/blob/master/etc/macosx-launchd/syncthing.plist

Or am I missing something - like a general location where to put a config?
The [syncthing docs](https://docs.syncthing.net/users/config.html) only mention user-level paths where config files are looked for.

/cc a few recent editors on that formula:
@saratovsource @MikeLund  @mbi @boone

**Comment by MikeMcQuaid** [comment]
Are you running it with `brew services start` or `sudo brew services start`?

**Comment by Kriechi** [comment]
Good question - which lead me to a solution, thanks!
  1. I didn't know that running `brew services ...` with or without sudo made a difference.
  2. From previous tries and fiddling around, it seems the plist then was owned by root and so I couldn't overwrite it. 
  3. Apparently `/usr/local/var/log/syncthing.log` was then owned by `root:admin` which let syncthing fail silently.

I'm not sure how I ended up in this situation - but seems like I dug myself in deep.
Now it seems to work. Thanks!

A minor thing remains:
Shouldn't the plist in the formula be updated to reflect the latest state from the syncthing-repo plist?

**Comment by angularly** [comment]
Running `sudo brew services start` does not add the plist file to `~/Library/LaunchAgents`

So this does not seem to be a fix...

I am also getting the FATAL error:
`19:38:57 FATAL: No home directory found - set $HOME (or the platform equivalent).`

It seems the users home dir [have to be specified](https://github.com/syncthing/syncthing/issues/3395) in the plist file.

**Comment by MikeMcQuaid** [comment]
If you run it with `sudo`: yes, you need to specify it in the plist file.
