### ISSUE TITLE
jsonnet >=v0.13.0 is missing the new binary jsonnetfmt

### ISSUE THREAD

**Issue by guidoiaquinti** [Homebrew/homebrew-core#40680]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
After installing the latest version of `jsonnet` I was trying to use the new `jsonnetfmt` as `jsonnet fmt` has been deprecated in the last release
- What happened (include command output)
`command not found: jsonnetfmt`
- What you expected to happen
`jsonnetfmt` can be executed
- Step-by-step reproduction instructions (by running `brew install` commands)

    1. `brew install jsonnet`
    2.  ```
        jsonnet --version
        Jsonnet commandline interpreter v0.13.0
        ```
    3.  ```
        jsonnetfmt
        command not found: jsonnetfmt
        ```

Note: this is a regression introduced 17 hours ago by the latest `jsonnet` release. See [here](https://github.com/google/jsonnet/releases/tag/v0.13.0) for more info

**Comment by iwoloschin** [comment]
The fix is simple on the formula, just add `bin.install "jsonnetfmt"` to the install stanza...but I've got no idea how to regenerate the bottle so I had to install from source (which is fine because it compiles quickly).

Quick steps to manually fix:
1) `brew edit jsonnet`
2) Add `bin.install "jsonnetfmt"` under line 18
3) `brew reinstall -s jsonnet`

I can try to make a PR, but I'm not familiar with the process so it might take a bit.

**Comment by fxcoudert** [comment]
Yes, please file a pull request.
(This is what happens when upstream does not provide a `make install` target…)

**Comment by fxcoudert** [comment]
Thanks @guidoiaquinti and @mkmik
