### ISSUE TITLE
Cannot load sqlite3 in php@7.2 apache module

### ISSUE THREAD

**Issue by caplod** [Homebrew/homebrew-core#40783]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

output from brew gist-logs php@7.2:
https://gist.github.com/caplod/707a197f923a3b6afb8d36bf8189f5a2

OSX 10.14.5

brew install php@7.2 is successfull

however when I include the php extension into the buildin apache I get:

`
sudo apachectl configtest
`
`
httpd: Syntax error on line 178 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so into server: dlopen(/usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so, 10): Symbol not found: _sqlite3_enable_load_extension\n  Referenced from: /usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so\n  Expected in: /usr/lib/libsqlite3.dylib\n in /usr/local/opt/php@7.2/lib/httpd/modules/libphp7.so
`

So it looks like php tries to use system sqlite.
How can I use the brew installed version?

**Comment by SMillerDev** [comment]
> output from brew gist-logs php@7.2

That link is failing

> however when I include the php extension into the buildin apache I get

You shouldn't use the buildin apache with homebrew's PHP. Just use the one from homebrew.

**Comment by caplod** [comment]
I updated the link for brew gist-logs php@7.2. Sorry for the wrong link.

I installed http with `brew install httpd`and enabled the homebrews php@7.2 in `/usr/local/etc/httpd/httpd.conf`

Its working fine now.
