### ISSUE TITLE
mysql-client package 404s

### ISSUE THREAD

**Issue by selfagency** [Homebrew/homebrew-core#40797]
- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Install `mysql-client`.

- What happened (include command output)
```
daniel@selfagency-macpro ~ % brew install mysql-client --HEAD
Updating Homebrew...
==> Downloading https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-boost-5.7.23.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
```

- What you expected to happen
```
For the package to not 404
```

- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install mysql-client --HEAD
```

I didn't include the gist-logs because I'm running 10.15 and it won't generate them. If you enter `https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-boost-5.7.23.tar.gz` into a browser, the URL 404s as well. I looked around on the MySQL site to see if there's a new CDN location, but it seems they may have deprecated `mysql-client` all together in favor of `mysql-shell`.

**Comment by scpeters** [comment]
I looked at one of the mysql mirrors, and there are newer versions of that package available, but it seems they aren't hosting 5.7.23 anymore. Would you be willing to make a pull request to update the version of this formula?

* https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by selfagency** [comment]
#40816

**Comment by selfagency** [comment]
I tried and failed.

**Comment by scpeters** [comment]
Sorry, I meant to include this link in my earlier comment:

http://mysql.mirrors.pair.com/Downloads/MySQL-5.7/

It looks like 5.7.26 is available as well. Do you mind trying a pull request for that version instead?

**Comment by selfagency** [comment]
That URL throws SSL errors when upgraded and when I try to curl from http, it downloads an error page. I tried upgrading with:

```
brew bump-formula-pr --tag=5.7.24 mysql-client
```

But the end result was a failed build.

**Comment by selfagency** [comment]
Filed a bug with MySQL.

https://bugs.mysql.com/bug.php?id=95740

**Comment by dasoran** [comment]
I meet same problem. Thank you for your Issue and PR @selfagency.


Although I do not know this information is useful for you, I was able to build 8.0.16 (the same version as mysql Formula).
https://gist.github.com/dasoran/d25c565c8a4ed4bf27d81b0a47e3e219

Is it not good to make it 8 series like mysql Formula?

**Comment by selfagency** [comment]
This build is apparently broken on Linux as well for the very same reasons:

https://bugs.mysql.com/bug.php?id=95740

**Comment by selfagency** [comment]
There is a fix coming in version 5.7.28

**Comment by SMillerDev** [comment]
Kinda makes me chuckle that they dismissed it as a homebrew issue while it was their fault

**Comment by comanl** [comment]
Fixed with lines <homebrew-core>/Formula/mysql-client.rb
  url "https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-boost-5.7.26.tar.gz"
  sha256 "effca6d3aceebc286a9fb046257330d125cc2f4def87081c286bfc4df3d974d1"

**Comment by selfagency** [comment]
@comanl Fixed how? The 5.7.26 build fails due to an error in the build process itself.

**Comment by comanl** [comment]
It is not fixed. I've posted to mysql developers
https://bugs.mysql.com/bug.php?id=81652

**Comment by comanl** [comment]
Any chances to get the lib 5.7.23 from somewhere?

**Comment by comanl** [comment]
I found it on net - https://mirrors.yangxingzhen.com/mysql/mysql-boost-5.7.23.tar.gz. After I downloaded locally is works again. Definitively a bug of MYSQL DEV Team

**Comment by fxcoudert** [comment]
Fixing as part of https://github.com/Homebrew/homebrew-core/pull/43860
