### ISSUE TITLE
Segmentation fault with curl-openssl

### ISSUE THREAD

**Issue by panosru** [Homebrew/homebrew-core#40812]
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

Today I found out that composer wasn't working, I quickly realised that it was a curl issue and while I trying to check why, I saw that while curl package is working fine, curl-openssl isn't.

![image](https://user-images.githubusercontent.com/400362/59152626-b7f7d500-8a50-11e9-827c-d4d7705db5d9.png)

I removed php, php-imap (from another tap), phplint and curl-openssl and re-installed php but curl-openssl is a dependency for php package, and now I'm kind of stuck since I'm not sure how to resolve the issue and why is it happening.

There are all my installed packages:
![image](https://user-images.githubusercontent.com/400362/59152652-4cface00-8a51-11e9-878f-4267edfea709.png)

Any suggestion or hint is very welcome!

Thanks!

**Comment by panosru** [comment]
I have updated my post to match the requirements of the template.

Any help would be appreciated, I'm still trying to figure out the issue.

It works fine on my MacBook Pro but on on my desktop :(

I run a tail on  my zsh history and I run the latest almost 200 commands (since last working period of curl) on my MacBook Pro and is still working, but I haven't done anything other than that on my desktop except of running "brew cask upgrade --greedy" but I don't think that this is the source of the issue.

Thanks!

**Comment by SMillerDev** [comment]
Could you try reinstalling php and curl-openssl? And, if you don't regularly do that, upgrade all packages.

**Comment by panosru** [comment]
@SMillerDev I have already uninstalled php and curl-openssl, I also run `brew list | xargs brew reinstall` but the issue with curl remains :(

**Comment by mbence** [comment]
Reverting to 7.65.0 ([this commit](https://github.com/Homebrew/homebrew-core/commit/b32507a8c94f7d7162899ad08f0fdfabd8179b08#diff-7f7b6ff023a169544d5c9c1e3771a797) of @lembacon) solved the issue for me. I edited the formula locally and reinstalled curl-openssl.

**Comment by panosru** [comment]
@mbence Thanks for the input! Could you please let me know can I revert to that version?

I tried to run `brew install curl-openssl@7.65.0` but it didn't worked

**Comment by fxcoudert** [comment]
If the problem persists with `--from-source`, it is almost certainly a bug in curl itself, since we (Homebrew) have made no other changes between 7.65.0 and 7.65.1 except use the newer sources. It would be interesting to report this to curl, so they can fix it.

**Comment by panosru** [comment]
@fxcoudert thanks for the info!

I would report it but to be honest, I still don't know why I had this issue on my desktop but on my MacBook v7.65.1 works fine... :/

**Comment by mbence** [comment]
I believe they already fixed it: https://github.com/curl/curl/issues/3995 
Should be in 7.65.2.

**Comment by fxcoudert** [comment]
Thanks… closing

**Comment by Krinkle** [comment]
Should this stay open until 7.65.2 is provided by Homebrew? Latest is still 7.65.1, which segfaults.

**Comment by it-can** [comment]
7.65.2 has just been released!

**Comment by rkoblev** [comment]
I don't know if my issue is related to this, but I've fixed my segfaults by adding hostname to /etc/hosts:
1. Run "hostname" (my output "Romans-MacBook-Pro.local") 
2. Add to "/etc/hosts" as "127.0.0.1       localhost Romans-MacBook-Pro.local"

**Comment by it-can** [comment]
@rkoblev was a problem with Curl in 7.65.1, now it's fixed in 7.65.2
