### ISSUE TITLE
Doxygen v1.8.11 Installs Successfully on OS X v10.11.6 'El Capitan,' but Crashes When Run (Using Non-Standard Options)

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#4081]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whom) $(brew --prefix)`?~~  N/A

### Bug reports:

The options I used were `--with-graphviz`, `--with-llvm`, and `--with-qt5`.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Doxygen) are my build logs.  The build and installation phases both succeed, but later invocations of Doxygen via the command line fail; some example output follows:  

```
Bryces-HD-1-TB:~ zadmin$ doxygen -v
dyld: Library not loaded: @rpath/libc++abi.1.dylib
  Referenced from: /usr/local/opt/llvm/lib/libc++.1.dylib
  Reason: image not found
Trace/BPT trap: 5
```

Note that running these commands…:  

```
brew uninstall -vd --doxygen
brew install -vd --build-from-source doxygen --with-graphviz --with-qt5
```

…(that is, manually reinstalling Doxygen from a build of it from source completed successfully _without_ the `--with-llvm` option, bypassing any option caching Homebrew appeared it might do in `brew reinstall` even when supplied new options) resolved the issue.

**Comment by RandomDSdevel** [comment]
Also note that I mistakenly filed this in [CMake's bug tracker](https://gitlab.kitware.com/cmake/cmake/issues) due to the circumstances under which I was seeing this bug manifest itself.  See this issue's [related CMake issue]()https://gitlab.kitware.com/cmake/cmake/issues/16251 (now closed in favor of this one) for more details on that.

**Comment by MikeMcQuaid** [comment]
So looks like `--with-llvm` is broken? Will probably accept a patch to fix or remove it.

**Comment by DomT4** [comment]
Pretty sure the problem is that @RandomDSdevel's `llvm` has been built with `--with-libcxxabi`, which we know has been problematic in terms of linking.

**Comment by RandomDSdevel** [comment]
@DomT4:  Ah, blast!  Are you guys currently still looking into that, and, if so, which issue or issues are relevant here?

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel We are not.

**Comment by DomT4** [comment]
We're open to solutions, but basically we've reached the point where we're all a bit lost on why this is problematic 😕, which is why the option remains off by default despite us turning a lot on by default recently.

**Comment by MikeMcQuaid** [comment]
(we should remove this option)

**Comment by RandomDSdevel** [comment]
@DomT4:  
> We're open to solutions, but basically we've reached the point where we're all a bit lost on why this is problematic 😕, which is why the option remains off by default despite us turning a lot on by default recently.  

Agh, uck!  Well, I'll be watching this space (wish I could contribute, but I'm not knowledgeable enough about the problem to do so…)  

@MikeMcQuaid:  
> (we should remove this option)

Agreed for now unless we can mark options with the `conflicts-with` element from Homebrew's DSL (w. r. t. LLVM's `--with-libcxxabi` option,) but, IIRC, that only applies to formulae.
