### ISSUE TITLE
abcde: Missing MusicBrainz::DiscID perl module dependency

### ISSUE THREAD

**Issue by MisterDA** [Homebrew/homebrew-core#40824]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? *No logs*
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? *Doctor says system healthy*
[brew_config.txt](https://github.com/Homebrew/homebrew-core/files/3269611/brew_config.txt)

abcde apparently requires the MusicBrainz::DiscID perl module, which is a binding to the libdiscid library.

```sh
$ abcde -d /dev/rdisk2
Can't locate MusicBrainz/DiscID.pm in @INC (you may need to install the MusicBrainz::DiscID module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /usr/local/bin/abcde-musicbrainz-tool line 18.
BEGIN failed--compilation aborted at /usr/local/bin/abcde-musicbrainz-tool line 18.
[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT
```

I tried to install the module with cpan, but abcde is still unable to find it. I think that perl include path need to be configured, but I don't know how. This is what I tried:

```sh
$ cpan install MusicBrainz::DiscID
# skipped, nothing special, install succeeded
$ export PERL5LIB=/usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level
$ abcde -d /dev/rdisk2
dyld: lazy symbol binding failed: Symbol not found: _Perl_xs_handshake
  Referenced from: /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level/auto/MusicBrainz/DiscID/DiscID.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_xs_handshake
  Referenced from: /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level/auto/MusicBrainz/DiscID/DiscID.bundle
  Expected in: flat namespace

[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT
```

If it’s impossible to install automatically this dependency, post-install instructions would be great.

Thanks!

**Comment by MaddSauer** [comment]
+1

**Comment by davidmankin** [comment]
I had the same problem yesterday with just a `brew reinstall perl`. I don’t think I even have abcde intentionally installed. 

See a related issue with Mac ports here: https://trac.macports.org/ticket/48948

**Comment by daemqn** [comment]
I have the same issue !

**Comment by iMichka** [comment]
Could somebody open a pull request for this?
You can add the dependency to the formula. Please have a look at the `ack` formula on how to add perl resources to a formula.

**Comment by MisterDA** [comment]
Why was this issue closed? Is the formula fixed? If it is, please reference the commit or the PR. If not, I'd suggest reopening the issue since it has drawn users and bug reporters.

**Comment by iMichka** [comment]
It does not work like this.

No maintainer fixed it. We do not have the manpower to fix this. We are understaffed, unpaid volunteers, doing this one our free time.

The community can fix it, as anyone can open a pull request. The solution has been given, we can also provide guidance and help for newcomers needing help to open a pull request. Anybody stumbling on this issue can open a pull request and fix this.

There are more than 200 open pull requests and 24 issues right now. We are trying to delegate as much as possible to the community.

This allows to reduce maintainer burnout, by focusing on the major issues.

**Comment by Al2Klimov** [comment]
Why don't you just add a label like "help wanted" and keep it open?

**Comment by iMichka** [comment]
We don't do that here. I mean, we can do it for a few weeks, but if nothing has been done after one month, we just close the issue.

Docker has more than 3500 open issues: https://github.com/moby/moby/issues
Rust has more than 5000 open issues: https://github.com/rust-lang/rust/issues
Python has more than 100 open issues: https://github.com/python/cpython/pulls

We want to avoid to be in that situation, were you have 10 year old open issues, where nobody knows it is still relevant or not. And then some maintainer needs to sort that out, which would take ages. Better cleanup the backlog from time to time.

For example: if nobody opens a pull request for `abcde`, this issue will stay open for the next 5 years. Keeping the issue open or closed does not change anything to the issue.
The only difference is maintainer sanity, and that we can see what we are really working on right now.
