### ISSUE TITLE
Running Ruby's IRB results in an error

### ISSUE THREAD

**Issue by sos4nt** [Homebrew/homebrew-core#40872]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

### What you were trying to do (and why)

I installed Ruby in order to run IRB, Ruby's REPL.

### What happened (include command output)

I got an error:
```
$ irb
Traceback (most recent call last):
	2: from /usr/local/opt/ruby/bin/irb:23:in `<main>'
	1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem irb (>= 0.a) with executable irb (Gem::GemNotFoundException)
```

### What you expected to happen

I expected to see IRB's prompt. Or to put it another way: I expect a clean install of Ruby to come with working IRB.

### Step-by-step reproduction instructions (by running `brew install` commands)

I installed Ruby via:
```
$ brew install ruby
```
The above command installed Ruby 2.6.3 sucessfully.

Homebrew then told me that because the formula is keg-only, I had to add the executable directory to my PATH which I did:
```
export PATH="/usr/local/opt/ruby/bin:$PATH"
```
Trying to execute `irb` resulted in the aforementioned error.

Apparently, Ruby can't find the IRB gem, although it was installed under `/usr/local/opt/ruby/lib/ruby/gems/2.6.0/gems/`:
```
$ ls -1 /usr/local/opt/ruby/lib/ruby/gems/2.6.0/gems
bundler-1.17.2
bundler-1.17.3
did_you_mean-1.3.0
irb-1.0.0           <- here it is
minitest-5.11.3
net-telnet-0.2.0
power_assert-1.1.3
rake-12.3.2
rdoc-6.1.0
test-unit-3.2.9
xmlrpc-0.3.0
```
I can even run IRB by manually executing its binary:
```
$ /usr/local/opt/ruby/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb
irb(main):001:0>
```

**Comment by bsiegel** [comment]
It looks like Homebrew's patch for the Gem module is no longer sufficient since the introduction of "default gems" in Ruby 2.6.0: https://stackoverflow.com/questions/54393939/homebrew-install-ruby-keg-only-cant-find-gem

**Comment by marhel** [comment]
I had the same issue, and it seems that Homebrew misconfigures RubyGems by overriding the default_dir, so it no longer points to the location of [Ruby's default gems](https://stdgems.org/). See https://stackoverflow.com/a/58337190/12193894
