### ISSUE TITLE
Incorrect link to Linuxbrew issue tracker at https://docs.brew.sh/Troubleshooting

### ISSUE THREAD

**Issue by taa1** [Homebrew/homebrew-core#40901]
https://docs.brew.sh/Troubleshooting#check-to-see-if-the-issue-has-been-reported

> Search the [Homebrew/homebrew-core issue tracker](https://github.com/Homebrew/homebrew-core/issues) or [Homebrew/linuxbrew-core issue tracker](https://github.com/Homebrew/homebrew-core/issues) to see if someone else has already reported the same issue.

Both links are the same: 

>https:// github.com/ Homebrew/ **homebrew**-core/ issues

I believe the one for Linuxbrew should be: 

>https:// github.com/ Homebrew/ **linuxbrew**-core/ issues

**Comment by taa1** [comment]
It's confusing to try to report a documentation problem. The only template that applied was this one:

> Don’t see your issue here? [Open a regular issue.](https://github.com/Homebrew/homebrew-core/issues/new)

Trying again.

-----

https://docs.brew.sh/Troubleshooting#check-to-see-if-the-issue-has-been-reported

> Search the [Homebrew/homebrew-core issue tracker](https://github.com/Homebrew/homebrew-core/issues) or [Homebrew/linuxbrew-core issue tracker](https://github.com/Homebrew/homebrew-core/issues) to see if someone else has already reported the same issue.

Both links are the same: 

>https:// github.com/ Homebrew/ **homebrew**-core/ issues

I believe the one for Linuxbrew should be: 

>https:// github.com/ Homebrew/ **linuxbrew**-core/ issues

**Comment by SMillerDev** [comment]
It might be easier to make a pull request to homebrew/brew. Since that is where the documentation lives. Homebrew-core is merely the target of the link
