### ISSUE TITLE
Why remove --with-default-names option, any alternatives?

### ISSUE THREAD

**Issue by hitzhangjie** [Homebrew/homebrew-core#40919]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

To help us debug your issue please explain:

- What you were trying to do (and why)
   brew install with option '-with-default-names', but this option deprecated, do you provide any alternative method? let users manage gnubin path and links is a terriable idea, worse than deprecate this option. I think developer know what they do when install with option '-with-default-names'.
- What happened (include command output)
   install failed, it says 'no such option: --with-default-names'.
- What you expected to happen
  install without prefix 'g'
- Step-by-step reproduction instructions (by running `brew install` commands)
   brew install gnu-indent --with-default-names

**Comment by hitzhangjie** [comment]
don't know why close this

**Comment by hitzhangjie** [comment]
this method removing options is awful

**Comment by equal-l2** [comment]
Some formula has `gnubin` directory, which contains symlink to executables which lacks 'g' prefix.
Doesn't the formula you want to install have one?

**Comment by SMillerDev** [comment]
> this method removing options is awful

The time for feedback on that was almost a year ago. 

> don't know why close this

It says so in the message from the bot

> let users manage gnubin path and links is a terriable idea, worse than deprecate this option. 

The lack of complaints about formulae not building since this change says otherwise. 

> I think developer know what they do when install with option '-with-default-names'.

You can think that, but my experience as a maintainer says otherwise. You'll just have to add the formula to your path.
