### ISSUE TITLE
zim: Icons not displayed - probably incorrectly XDG_DATA_DIRS

### ISSUE THREAD

**Issue by vladmihaisima** [Homebrew/homebrew-core#40953]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? _Not applicable, package installs._
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 

- brew config output:

```
HOMEBREW_VERSION: 2.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: db58b9f41b70a331dbe9b8371527a23e8ddcc718
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: db83309a948a00eb480281c5a203a74546843ae4
Core tap last commit: 20 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_201
macOS: 10.14.5-x86_64
CLT: 11.0.0.0.1.1559496560
Xcode: N/A
CLT headers: 11.0.0.0.1.1559496560
```

- brew doctor output:

```
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.7m/greenlet/greenlet.h
```

To help us debug your issue please explain:

- What you were trying to do (and why) _Install and use zim desktop wiki (https://github.com/Homebrew/homebrew-core/blob/master/Formula/zim.rb)_
- What happened (include command output) _zim installs and runs but can't find all icons although the corresponding packages are installed. This can be quite annoying as some icons that expand sub-pages in the tree view are missing so it's hard to expand them. The output of zim is:_

```
(zim:98413): Gtk-WARNING **: 14:39:15.736: Could not find the icon 'zim-add-bookmark'. 
The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
WARNING: Could not find all icon sizes for the application icon
```

- What you expected to happen _All icons are found. I think failure to find icons is due an improper setting of XDG_DATA_DIRS. For the file /usr/local/Cellar/zim/0.71.1/bin/zim (generated from the zim.rb) it is:_
`XDG_DATA_DIRS="/usr/local/Cellar/zim/0.71.1/libexec/share"`
_and probably should be_
`XDG_DATA_DIRS="/usr/local/Cellar/zim/0.71.1/libexec/share:/usr/local/share"`

_With the above change zim works as expected and icons are found_

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install
zim
```

_Some icons are missing, check for example in the top right of the window by the search box there should be a magnifier._

**Comment by SMillerDev** [comment]
Could you make a pull request to change this? It should be fairly straightforward.

**Comment by vladmihaisima** [comment]
I could (and will) the earliest next week, wanted to make at least a note somewhere ...

**Comment by mikewolfe** [comment]
I also had this issue. After applying the fix suggested above I still had no icons. However, after running:
```
brew install adwaita-icon-theme
```
I no longer had any issues with the icons showing up. This was apparently also an issue with xdot awhile back which is how I found the fix: https://github.com/Homebrew/homebrew-core/issues/19187

Couldn't find any guidelines on commenting on open issues, but I would be happy to provide additional information (i.e. brew doctor/ brew config output) if needed. Wanted to add on here for others having similar issues with installing Zim

**Comment by fxcoudert** [comment]
Fixing in https://github.com/Homebrew/homebrew-core/pull/43897, thanks for the report and comments
