### ISSUE TITLE
aspell

### ISSUE THREAD

**Issue by rrthomas** [Homebrew/homebrew-core#40976]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew gist-logs aspell: Error: No logs.

brew doctor: Your system is ready to brew.

brew config:

HOMEBREW_VERSION: 2.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: db58b9f41b70a331dbe9b8371527a23e8ddcc718
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 255b8e25d596eeaf7aa3f1af65e1dfefc9932a37
Core tap last commit: 83 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit nehalem
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A

To help us debug your issue please explain:

- What you were trying to do (and why)

Spellcheck a file with aspell with language "nds".

- What happened (include command output)

$ aspell --lang=nds check README
Error: The file "/usr/local/Cellar/aspell/0.60.6.1_1/lib/aspell-0.60/qwertz.kbd" can not be opened for reading.

- What you expected to happen

If I use another language that is listed in `aspell dump dicts`, it works.

It seems the above-mentioned file is simply missing.

- Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install aspell
$ aspell --lang=nds check foo.txt

**Comment by fxcoudert** [comment]
Where should that `qwertz.kbd` file come from?

**Comment by rrthomas** [comment]
This is a good question, @fxcoudert! I cannot find a full answer to that, except that it is not in current aspell git, but it and a number of other `.kbd` files are supplied in various patches to the aspell bug tracker; see https://github.com/GNUAspell/aspell/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keyboard

So it seems there are a few options options:

1. Add and distribute these `.kbd` files
2. Remove the dictionaries that depend on them until a version of aspell is released with the extra files
3. Remove the reference to undistributed `.kbd` files from the dictionaries.

I notice that for example Ubuntu (which I use) does not distribute the Plattdüütsh spelling file that relies on this keyboard file.

As you may know, the `.kbd` files are not essential; they are used to improve aspell's guesses about typos by providing information on the standard keyboard layout used for each language, and hence which keys are near each other.

**Comment by fxcoudert** [comment]
If they're not officially published/integrated, we won't ship them, sorry. The issue has to be addressed by upstream.

**Comment by rrthomas** [comment]
That's fine, but in that case please can you remove the nds dictionary, as it is broken without the qwertz.kbd file.

**Comment by fxcoudert** [comment]
We build the list of included dictionaries from the official appel list at ftp://ftp.gnu.org/gnu/aspell/dict/0index.html

**Comment by rrthomas** [comment]
That's fine, but as I said, the dictionary file for nds relies on a keyboard file that you don't ship. Therefore, it won't work. So please either ship the keyboard file or don't ship the dictionary.

**Comment by SMillerDev** [comment]
Please file an issue with aspel about the missing keyboard file. Homebrew doesn't change anything about it and only ships the included dictionaries from upstream.

**Comment by rrthomas** [comment]
I will do that as well, but it's not quite that simple: as I'm sure you know, the dictionaries are not part of the Aspell sources. Therefore, this is not simply an upstream but; it's a result of the way that brew distributes aspell, and, in particular, puts all of the dictionaries in a single package.

**Comment by fxcoudert** [comment]
Aspell ships both the software and the dictionaries (they're listed and hosted on the same server). They can fix this by:
- shipping the keyboard file alongside the dictionary
- including it in the source
- listing it separately (in which case we'll add it to our install procedure)

If we remove the nds dictionary, we "fix" it for now but when the situation is later fixed at aspell, we'll have another issue filed with "why don't you ship the nds dictionary".

As a result, the general Homebrew philosophy is that we don't manually fix issues in our formulas, by making special cases. We simply don't have the manpower to start tweaking every little detail :(

**Comment by rrthomas** [comment]
See https://github.com/GNUAspell/aspell/issues/555

**Comment by rrthomas** [comment]
Thanks for the explanation above.

The problem for me is that as upstream maintainer of enchant, I can no longer test against Aspell in my macOS builds, as the tests fail: they reasonably assume they should be able to load every listed dictionary.
