### ISSUE TITLE
glib upgrade fails with `meson.build:620:2: ERROR: Unknown compiler(s): [['clang']]`

### ISSUE THREAD

**Issue by albertmichaelj** [Homebrew/homebrew-core#41071]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

In trying to update glib from `2.60.3` to `2.60.4_1`, the upgrade fails. The output of `brew upgrade glib` is below:
```
$ brew upgrade glib
==> Upgrading 1 outdated package:
glib 2.60.3 -> 2.60.4_1
==> Upgrading glib 
==> Downloading https://download.gnome.org/sources/glib/2.60/glib-2.60.4.tar.xz
Already downloaded: /Users/Michael/Library/Caches/Homebrew/downloads/0b257e9910276994ee9384ec16938c91bb73b22839e2c1002a21e6de8e8bb54a--glib-2.60.4.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6164294a7/glib/hardcoded-paths.diff
Already downloaded: /Users/Michael/Library/Caches/Homebrew/downloads/7a31846424d243e8c4ab3c738fb92a52aa1a0522d78af7b1ec92cc3729cad494--hardcoded-paths.diff
==> Patching
==> Applying hardcoded-paths.diff
patching file gio/gdbusprivate.c
patching file gio/xdgmime/xdgmime.c
patching file glib/gutils.c
==> meson --prefix=/Users/Michael/.brew/Cellar/glib/2.60.4_1 -Diconv=native -Dgio_module_dir=/Users/Michael/.brew/lib/gi
Last 15 lines from /Users/Michael/Library/Logs/Homebrew/glib/01.meson:
Checking if "strerror_r() returns char *" compiles: NO
Checking for function "snprintf" : YES
Checking for function "strcasecmp" : YES
Checking for function "strncasecmp" : YES
Header <sys/sysmacros.h> has symbol "major" : NO
Header <sys/mkdev.h> has symbol "major" : NO
Header <sys/types.h> has symbol "major" : YES
Header <dlfcn.h> has symbol "RTLD_LAZY" : YES
Header <dlfcn.h> has symbol "RTLD_NOW" : YES
Header <dlfcn.h> has symbol "RTLD_GLOBAL" : YES
Message: Checking whether to use statfs or statvfs .. statfs

meson.build:620:2: ERROR: Unknown compiler(s): [['clang']]

A full log can be found at /private/tmp/glib-20190618-86589-1ibp44/glib-2.60.4/build/meson-logs/meson-log.txt

Do not report this issue to Homebrew/brew or Homebrew/core!
```
The link that is output from `brew gist-logs glib` is [here](https://gist.github.com/0e7b80d441237e3872a5e143e007f5e9).

I had to cancel a previous `brew upgrade glib` command in the middle of running, and then this problem started happening. It is now blocking upgrading other packages. Any thoughts on why it says it can't find `clang`? If I run `which clang` it returns `/usr/bin/clang` as expected.

**Comment by fxcoudert** [comment]
poke @tschoonj

**Comment by tschoonj** [comment]
No idea really... You may want to open an issue on the meson github repo.

**Comment by albertmichaelj** [comment]
I opened an issue with them as well. Any suggestions on things to try to fix it?

**Comment by albertmichaelj** [comment]
No one has responded yet with meson. Any ideas on things to try? I uninstalled the previous version thinking something about it was causing the conflict, and now I can't reinstall the new version of glib. Any troubleshooting steps that I may have missed?

I appreciate your time and help.

**Comment by iMichka** [comment]
Your brew is not installed in our canonical path, this is why it tries to build from source. In that case the configuration is a little bit exotic and we do not have enough manpower to fix this issue right now. I would wait for upstream meson to fix this. Not sure we can do much more right now. Unless some maintainer finds some spare time.

The only solution is to dig through the meson source code and find the bug. Or wait for the upstream devs to help you.

**Comment by albertmichaelj** [comment]
I definitely understand that installing outside of /usr/local is not the preferred user behavior. However, this is not the problem for my case. I created a new homebrew installation in `~/brew-test` instead of `~/.brew` (which is my old installation) just to see if I could install glib there. It installed just fine. Everything else on the machine is identical (I just replaced the path with the new brew installation).

Something went wrong when I had to cancel the installation of glib on my original homebrew installation. That's why I uninstalled it and tried to reinstall it. However, for the life of me, I don't know what the solution is outside of just starting completely fresh with my homebrew installation (which I would **really** rather not do).

Given that this probably isn't a meson issue at it's core (since things went just fine with a fresh brew installation) are there any options for trying to restore my homebrew installation to a working state?

**Comment by SMillerDev** [comment]
Did you try removing the homebrew cache in `/Users/<user>/Library/Caches/Homebrew/`?

**Comment by albertmichaelj** [comment]
I have (at least I've deleted everything I can fine associated with glib), but I haven't just nuked the whole folder with a `rm -rf *`. Is that what I should do?

Note that there is now someone else reporting the same issue on meson on my other issue I've opened up https://github.com/mesonbuild/meson/issues/5506. It's also not a conflict with something in the existing installation because I reinstalled everything into a new homebrew installation that I had in the previous installation (at a custom location `~/homebrew-test`), and I can still install glib just fine.

Something happened when I canceled the install, and now it's just broken. I don't understand how that can be, but certainly there is some file that was left behind somewhere.

I reported this as an issue for brew at https://github.com/Homebrew/brew/issues/6244 because it seems to be a bug in brew, not in this formula specifically. However, @MikeMcQuaid just closed the issue out of hand without even asking for more information.

This is a bug in brew, and I'm happy to try to help diagnose it, but I don't really know where to go from here. It is not an issue with a custom location, and it is not a conflict with either an existing package or something on my path as evidenced by everything working just fine in my new installation (with the same path save for the brew bin location). Please let me know if you have suggestions for how to diagnose this.

**Comment by MikeMcQuaid** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!

I quote your own output that tells you not to file this issue. Your `brew doctor` output additionally tells you not to file this issue.



> This is a bug in brew, and I'm happy to try to help diagnose it, but I don't really know where to go from here.

Open an issue in Discourse and the wider community may be able to help you. We will not be continuing to help you in this issue because you're running an unsupported configuration, this is not reproducible and, frankly, you're resorted in calling me "arrogant" in https://github.com/Homebrew/brew/issues/6244 so I have no desire to have the maintainers spend any more of our free time helping you.
