### ISSUE TITLE
 curl-openssl: Usage of c-ares breaks domain specific resolvers

### ISSUE THREAD

**Issue by ddelbondio** [Homebrew/homebrew-core#41286]
This is not an actual installation issue, but the configuration of curl-openssl breaks the OSX standard functionality ([custom doamin specific resolvers](https://apple.stackexchange.com/questions/74639/do-etc-resolver-files-work-in-mountain-lion-for-dns-resolution))

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? -> failed
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 2.1.6-24-g573acc8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 573acc85a6cf7d7f69fc1022d33820607f755d93
Last commit: 60 seconds ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 552c5a7b7d539187269cc3a845484609575c9969
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.3, 11.0.1.6, 1.8.0_212, 1.7.0_79
macOS: 10.14.4-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
```

To help us debug your issue please explain:

- What you were trying to do (and why)
Use the custom dns defined in /etc/resolvers/* from curl
- What happened (include command output)
Curl is not using the system provided resolver but implements its custom resolver using c-ares.

```
> /usr/local/Cellar/curl-openssl/7.65.1/bin/curl -v http://local.test
* Could not resolve: local.test (Domain name not found)
curl: (6) Could not resolve: local.test (Domain name not found)
```

- What you expected to happen
The same behaviour as system and homebrew standard curl:

```
> /usr/local/Cellar/curl/7.65.1/bin/curl -v http://local.test
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to local.test (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: local.test
> User-Agent: curl/7.65.1
> Accept: */*
> ... 8<

> /usr/bin/curl -v http://local.test
* Rebuilt URL to: http://local.test/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to local.test (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: local.test
> User-Agent: curl/7.54.0
> Accept: */*
> ... 8<
```

- Step-by-step reproduction instructions (by running `brew install` commands)

```
# Setup custom resolver redirecting *.test to 127.0.0.1 (see link above)
brew install curl-openssl
/usr/local/Cellar/curl-openssl/7.65.1/bin/curl -v http://local.test
```

Generally the [curl-openssl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl-openssl.rb) formula seems to build curl with quite different features than the regular [curl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/curl.rb) formula. I could not figure out the reason for that from the history, it just seems to be rather inconsistent. 

Other than the c-ares flag, I have not yet encountered any problems with these specific flags though.

**Comment by MikeMcQuaid** [comment]
Why does the system `curl` or `curl` formula not work for your use-case?

**Comment by ddelbondio** [comment]
I am actually using PHP which uses `curl-openssl`. I just simplified my example it to show the root problem.

**Comment by MikeMcQuaid** [comment]
I see, thanks, that's helpful. I'm not sure that this is something we can do anything about but it may be worth filing an issue with the upstream modules?

**Comment by ddelbondio** [comment]
Looking at the details from `c-ares`, it is probably somewhat out of scope to support such OS specific behaviour. 

Is there a specific reason why `curl-openssl` is compiled with `c-ares` support? Judging from a quick [Github search](https://github.com/search?l=PHP&p=4&q=CURLOPT_DNS_INTERFACE&type=Code), the feature c-ares enables is pretty much unused by any PHP code, as most of these hits are just wrapper libraries. The only other user of `curl-openssl`, `fb-client`, also doesn't use any of the curl options which only work when compiled with `c-ares`.

IMHO it would be better to simply compile `curl-openssl` without `c-ares` support.

**Comment by MikeMcQuaid** [comment]
> Is there a specific reason why `curl-openssl` is compiled with `c-ares` support?

Yes, various users have used/requested it. `curl-openssl` is also used by users directly outside of just PHP.

> IMHO it would be better to simply compile `curl-openssl` without `c-ares` support.

We'll review a PR for this but cannot promise it'll get merged. 

Closing as an upstream issue, thanks!

**Comment by webpatser** [comment]
i have a small workaround:

uninstall curl-openssl

`brew uninstall --ignore-dependencies curl-openssl`

then install it from source

`brew install -s  curl-openssl --head`

now curl and PHP are happy. When this bug is  fixed just uninstall again and install the release version again.

**Comment by ddelbondio** [comment]
Thank you for the explanation.

Would it make sense to compile `curl` with `c-ares` as well or even generally sync the compile flags, except openssl of course, for both versions?

**Comment by MikeMcQuaid** [comment]
> Would it make sense to compile `curl` with `c-ares` as well or even generally sync the compile flags, except openssl of course, for both versions?

No, sorry. The `curl` formula is intentionally minimal and `curl-openssl` maximal.
