### ISSUE TITLE
qdoc is missing from qt formulae

### ISSUE THREAD

**Issue by ABBAPOH** [Homebrew/homebrew-core#41314]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

I was trying to build a [Qbs](http://github.com/qbs/qbs) using Qt installed via Brew:
$ brew install qt
$ brew install qbs
$ git clone git@github.com:qbs/qbs.git
$ cd qbs
$ mkdir build
$ qbs setup-toolchains --detect
$ qbs setup-qt /usr/local/bin/qmake brew-qt
$ qbs config profiles.brew-qt.baseProfile xcode-macosx-x86_64
$ qbs build -f ../qbs.qbs -p "qbs documentation"

- What happened (include command output)
However, when I try to build a documentation, compilation fails, because qdoc binary is not present in Qt formulae. Qbs shipped with Brew does not include docs too, but ideally it should.

Restoring build graph from disk
Building for configuration default
ERROR: /usr/local/Cellar/qbs/1.13.1/share/qbs/imports/qbs/ModUtils/utils.js:441 Error: Error running '/usr/local/Cellar/qt/5.12.3/bin/qdoc': execve: No such file or directory
The following products could not be built for configuration default:
qbs documentation

See also similar log here: https://travis-ci.com/ABBAPOH/qbs/jobs/210759408

- What you expected to happen
I expect documentation to be built successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)

See above or simplified version below:
$ brew install qt
$ which qmake
/usr/local/bin/qmake
$ qmake --version
QMake version 3.1
Using Qt version 5.12.3 in /usr/local/Cellar/qt/5.12.3/lib
$ which qdoc
$ qdoc
-bash: qdoc: command not found

======
It seems that qdoc was removed in [this issue](https://github.com/Homebrew/homebrew-core/issues/29415). Also, in the final comment there's a patch that returns qdoc. But it seems that that patch was never applied.
Please, return qdoc to the qt package.

**Comment by SMillerDev** [comment]
We don't accept feature requests as issues for homebrew. If you want something changed in a formula you'll have to make a pull request (as is indicated in the first checkbox that you ticked)
