### ISSUE TITLE
GCC 6.1.0 - curl: (35) SSL certificate problem - Failed to download resource "gcc--patch"

### ISSUE THREAD

**Issue by matkara** [Homebrew/homebrew-core#4136]
Hello,

I have issues building gcc 6.1.0 without the multiline support to activate the OpenMP support as suggested when installing gcc 6.1.0 without this additional installation option.
Here it what I get:

```
[matkara@Tooslocal]$ sudo brew reinstall gcc --without-multilib
==> Reinstalling gcc with --without-multilib
==> Using the sandbox
==> Downloading https://ftpmirror.gnu.org/gcc/gcc-6.1.0/gcc-6.1.0.tar.bz2
Already downloaded: /Users/matkara/Library/Caches/Homebrew/gcc-6.1.0.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c963247c6b/gcc/gcc-6.1.0_infinite_memory_snacking.patch

curl: (35) SSL certificate problem: Couldn't understand the server certificate format
Error: Failed to download resource "gcc--patch"
Download failed: https://raw.githubusercontent.com/Homebrew/formula-patches/c963247c6b/gcc/gcc-6.1.0_infinite_memory_snacking.patch
```

Does anyone encounter the same issue?
It is only a download/certificate issue, it is probably trivial to fix. I tried to follow recommendations from here: https://github.com/meteor/meteor/issues/3770 
But it has no effect.

The Gist-log:
https://gist.github.com/e6dd7f3cc88d9b2e19122a9382cbc60a

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MikeMcQuaid** [comment]
Closing in favour of https://github.com/Homebrew/brew/issues/796 which describes the problem.

**Comment by jamver** [comment]
For anybody looking for a possible resolution to this issue...

I encountered this issue specifically after updating to macOS Sierra (10.12), with resolution coming from the workaround from [this legacy-homebrew ticket](https://github.com/Homebrew/legacy-homebrew/issues/32019#issuecomment-180162137):

```
cd ~
sudo wget http://curl.haxx.se/ca/cacert.pem
export CURL_CA_BUNDLE=~/cacert.pem
```

I'd be interested to know the correct fix.  e.g. Update system ca bundle?  Apple patch required for system bundle?
