### ISSUE TITLE
`brew install --HEAD doxygen` fails

### ISSUE THREAD

**Issue by iamitava** [Homebrew/homebrew-core#41441]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (`brew gist-logs` failed with `Error: No logs.`)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? (at end)

To help us debug your issue please explain:

- What you were trying to do (and why)

  I was trying to install `doxygen` from latest source (`--HEAD`), since I wanted to try out a feature not available in their last release.

- What happened (include command output)

  This failed to build.

  ```
  $ brew install --HEAD doxygen
  ==> Cloning https://github.com/doxygen/doxygen.git
  Updating /Users/<username>/Library/Caches/Homebrew/doxygen--git
  ==> Checking out branch master
  Already on 'master'
  Your branch is up to date with 'origin/master'.
  HEAD is now at c44632a Merge pull request #7075 from tirolerstefan/feature/doxysearch_wildcard
  ==> Downloading https://github.com/doxygen/doxygen/commit/889eab308b564c4deba4ef58a3f134a309e3e9d1.diff?full_index=1
  Already downloaded: /Users/<username>/Library/Caches/Homebrew/downloads/15e26635c2afad4b2715d684f536dfb9e6f3f3bd1088229669894f7852a47e0f--889eab308b564c4deba4ef58a3f134a309e3e9d1.diff
  ==> Patching
  ==> Applying 889eab308b564c4deba4ef58a3f134a309e3e9d1.diff
  patching file src/config.xml
  Hunk #1 FAILED at 2594.
  1 out of 1 hunk FAILED -- saving rejects to file src/config.xml.rej
  Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/doxygen--patch-20190628-47828-g38a3q/889eab308b564c4deba4ef58a3f134a309e3e9d1.diff` exited with 1.
  ```
- What you expected to happen

  I expected `doxygen` to be built and installed successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)

  `brew install --HEAD doxygen`

The `doxygen` formula was [patched](https://github.com/Homebrew/homebrew-core/blob/master/Formula/doxygen.rb#L19-L24) in 0b5bdd3 to fix #35815.  Since the issue was already fixed in upstream as per [this comment](https://github.com/Homebrew/homebrew-core/issues/35815#issuecomment-453278807), this patch should be limited to the "stable" version, i.e., wrapped in a `stable do` block.

However, not applying the patch to HEAD alone is insufficient, as current HEAD has some changes that fail to build with the stock version of `bison` installed on macOS (reported in doxygen/doxygen#7091).  This can be fixed by either requiring a build dependency on `bison`, or alternatively by patching the file in question (see referenced issue).

This patch to the doxygen formula worked for me:

```patch
diff --git a/Formula/doxygen.rb b/Formula/doxygen.rb
index 25dfd5636..1b212549e 100644
--- a/Formula/doxygen.rb
+++ b/Formula/doxygen.rb
@@ -15,12 +15,17 @@ class Doxygen < Formula
   end
 
   depends_on "cmake" => :build
+  head do
+    depends_on "bison" => :build
+  end
 
-  # Fix build breakage for 1.8.15 and CMake 3.13
-  # https://github.com/Homebrew/homebrew-core/issues/35815
-  patch do
-    url "https://github.com/doxygen/doxygen/commit/889eab308b564c4deba4ef58a3f134a309e3e9d1.diff?full_index=1"
-    sha256 "ba4f9251e2057aa4da3ae025f8c5f97ea11bf26065a3f0e3b313b9acdad0b938"
+  stable do
+    # Fix build breakage for 1.8.15 and CMake 3.13
+    # https://github.com/Homebrew/homebrew-core/issues/35815
+    patch do
+      url "https://github.com/doxygen/doxygen/commit/889eab308b564c4deba4ef58a3f134a309e3e9d1.diff?full_index=1"
+      sha256 "ba4f9251e2057aa4da3ae025f8c5f97ea11bf26065a3f0e3b313b9acdad0b938"
+    end
   end
 
   def install
```

If this looks good, I can open a PR.

---

<details>
<summary>brew config output</summary>

```
$ brew config
HOMEBREW_VERSION: 2.1.6-37-g686760d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 686760d100d1a518863805247a606cc1cef12a87
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae1e766bffc6a7045436a44ca233ccbd79ddd514
Core tap last commit: 83 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_212
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
```

</details>

<details>
<summary>brew doctor output</summary>

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A .pydistutils.cfg file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
```

</details>

**Comment by fxcoudert** [comment]
Thanks, we welcome a PR. Please note that `url` and `sha256` should be scoped inside `stable do` block as well (look how other formulas with that block do it).

`depends_on "bison" => :build if build.head?` is also probably be better: no need to have a full block, and it's a build-only dependency
