### ISSUE TITLE
dnscrypt-proxy not running as root and cannot bind to port 53

### ISSUE THREAD

**Issue by kim0** [Homebrew/homebrew-core#41551]
- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

$ brew gist-logs dnscrypt-proxy
Error: No logs.

To help us debug your issue please explain:

- What you were trying to do (and why)

Trying to install and run dnscrypt-proxy as my main resolver in OSX to secure my DNS

- What happened (include command output)

While the service shows success
```
brew services start dnscrypt-proxy
==> Successfully started `dnscrypt-proxy` (label: homebrew.mxcl.dnscrypt-proxy)
brew services list
Name           Status  User Plist
dbus           stopped
dnscrypt-proxy started kim0 /Users/kim0/Library/LaunchAgents/homebrew.mxcl.dnscrypt-proxy.plist
dnsmasq        stopped
docker-machine stopped
```
I'm finding the below in the log file and my DNS is not working
```
[2019-07-02 14:11:34] [NOTICE] Network connectivity detected
[2019-07-02 14:11:34] [NOTICE] Source [public-resolvers.md] loaded
[2019-07-02 14:11:34] [NOTICE] Source [opennic.md] loaded
[2019-07-02 14:11:34] [NOTICE] dnscrypt-proxy 2.0.25
[2019-07-02 14:11:34] [NOTICE] Loading the set of forwarding rules from [forwarding-rules.txt]
[2019-07-02 14:11:34] [FATAL] listen udp 127.0.0.1:53: bind: permission denied
```

- What you expected to happen

dnscrypt-proxy is able to listen to port 53 and serve requests

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install dnscrypt-proxy
brew services start dnscrypt-proxy

- Workaround(s)
Either of `sudo brew services start` or marking the binary as setuid work. I prefer the setuid option bec the binary can't really listen to port 53 if it's not root afaict

- I notice the plist file in the formula as a section saying User = root. Apparently this is not applied in the real plist file as seen below

```
$ cat /Users/kim0/Library/LaunchAgents/homebrew.mxcl.dnscrypt-proxy.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>homebrew.mxcl.dnscrypt-proxy</string>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>ProgramArguments</key>
    <array>
      <string>/usr/local/opt/dnscrypt-proxy/sbin/dnscrypt-proxy</string>
      <string>-config</string>
      <string>/usr/local/etc/dnscrypt-proxy.toml</string>
    </array>

    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
  </dict>
</plist>
```

**Comment by SMillerDev** [comment]
What happens to the plist if you reinstall it?

**Comment by kim0** [comment]
@SMillerDev .. by chance, yesterday while debugging this, I brew uninstalled dnscrypt-proxy and reinstalled it .. It still is broken. Also I noticed that when I "brew services stop" it, the plist file gets deleted, then when I start the service, it gets created again .. And all that time, without the user=root part

**Comment by MindTooth** [comment]
Why not with `sudo`?  I've always installed using `sudo` and have not had any issues.  Maybe that was wrong of me?

If I'm not mistaken, if installed with `sudo` you have systemwide DNS protection, and not just for your local user.

**Comment by livid** [comment]
You will need `sudo` when starting services with lower ports:

```
sudo brew services start dnscrypt-proxy
```

**Comment by iMichka** [comment]
Looks like @livid provided a solution. Will close this here. `sudo` is not always needed for `brew services` but in some cases I guess it is.
