### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by MoguG** [Homebrew/homebrew-core#4156]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo); git fetch; git reset --hard origin/master; brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

$ brew search sublime text2

**ERROR**:undefined method `[]' for nil:NilClass
/usr/local/Library/Homebrew/vendor/okjson.rb:151:in `block in objparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:145:in `loop'
/usr/local/Library/Homebrew/vendor/okjson.rb:145:in `objparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:119:in `valparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:191:in `block in arrparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:188:in `loop'
/usr/local/Library/Homebrew/vendor/okjson.rb:188:in `arrparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:120:in `valparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:166:in `pairparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:148:in `block in objparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:145:in `loop'
/usr/local/Library/Homebrew/vendor/okjson.rb:145:in `objparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:102:in `textparse'
/usr/local/Library/Homebrew/vendor/okjson.rb:46:in `decode'
/usr/local/Library/Homebrew/utils/json.rb:10:in `load'
/usr/local/Library/Homebrew/utils/github.rb:176:in `open'
/usr/local/Library/Homebrew/cmd/search.rb:133:in `block in search_tap'
/usr/local/Library/Homebrew/cmd/search.rb:151:in `yield'
/usr/local/Library/Homebrew/cmd/search.rb:151:in `search_tap'
/usr/local/Library/Homebrew/cmd/search.rb:117:in `block (2 levels) in search_taps'

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by dunn** [comment]
If you're trying to install Sublime Text, you need Homebrew Cask:
```
brew tap caskroom/cask
brew cask install sublime-text
