### ISSUE TITLE
pip crash on brew installed python3

### ISSUE THREAD

**Issue by QYQSDTC** [Homebrew/homebrew-core#41632]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. 
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
doesn't work
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
*brew doctor*
``` 
Warning: You have the following deprecated, official taps tapped:
  Homebrew/homebrew-versions
Untap them with `brew untap`.

Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this pre-release version.


Warning: Ruby version 2.6.3 is unsupported on 10.15. Homebrew
is developed and tested on Ruby 2.3.7, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```

*brew config*

```
HOMEBREW_VERSION: 2.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: fddf5b16bd8df577380a1d810d17825ef611b81f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 33faa0a49e64e7c5206525801db2c80e85dcb1e8
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.1, 12, 11.0.2, 11.0.1, 11, 10.0.2, 10.0.1, 10, 9.0.4, 9.0.1, 9, 1.8.0_144, 1.8.0_141, 1.8.0_131, 1.8.0_121
macOS: 10.15-x86_64
CLT: N/A
Xcode: 11.0 => /Applications/Xcode-beta.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11
```
To help us debug your issue please explain:

- update pip
- pip crashed
- update smoothly
- At first, I was trying to update my python packages and there were certification problem:
```
Could not fetch URL https://pypi.apple.com/simple
```
Then I reinstalled python3 by running 
brew reinstall python3
after this I can still run python3 but not pip.
Run any pip command will cause the crush:
<img width="1000" alt="Screen Shot 2019-07-05 at 03 53 36" src="https://user-images.githubusercontent.com/15608306/60686013-0033d700-9ed9-11e9-90d0-ed35d92abbc4.png">

**Comment by QYQSDTC** [comment]
The interesting thing is I download the installer from python.org and installed it, the pip runs well.

**Comment by SMillerDev** [comment]
You gotta fill out any of the things that give us information about your homebrew setup. Those checkmarks really aren't optional if you expect people to help you solve the issue.

**Comment by QYQSDTC** [comment]
@SMillerDev sorry for that, I have already updated the comment.

**Comment by SMillerDev** [comment]
See, brew doctor is telling me you shouldn't have filled this issue because you're using a beta of macOS. There's so many things that could go wrong in the combination with Apple shipping their own python 3 that nobody considered yet (because it's a beta and we're not going to work around things apple might fix) that I'm going to close this. If you find a solution, don't hesitate to make a pull request. But there's simply too much instability in the beta to make it worthwhile to figure this out for you.
