### ISSUE TITLE
Tachyon formula changed to Alluxio

### ISSUE THREAD

**Issue by miguelarauj1o** [Homebrew/homebrew-core#4188]
### Formula Requests:

[tachyon.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tachyon.rb) has been update to [Alluxio](http://www.alluxio.org).

I can try to handle this, but only after thursday because I'm very busy right now.

**Comment by MikeMcQuaid** [comment]
> I can try to handle this, but only after thursday because I'm very busy right now.

We'll wait, thanks!
