### ISSUE TITLE
NoMethodError: undefined method `preferred_arch' for OS::Mac:Module

### ISSUE THREAD

**Issue by mxye** [Homebrew/homebrew-core#41904]
- [ y] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [y ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [y ] ran `brew update` and can still reproduce the problem?
- [ y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ no] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ no] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The two above answers are no because I can't log onto github there... But the error looks like this:
```
==> Checking out branch pdf2htmlEX
your branch is up to date with 'origin/pdf2htmlEX'.
Already on 'pdf2htmlEX'
Error: An exception occurred within a child process:
NoMethodError: undefined method 'preferred_arch' for OS::Mac:Module
```

A similar error was raised before about linuxbrew and was in theory fixed. See https://github.com/Linuxbrew/brew/issues/675

- What you were trying to do (and why):
I was trying to install an official formula "pdf2htmlex" from linuxbrew on a red hat docker container. 

- What happened (include command output)
`brew install pdf2htmlex`. 
Additional note, may be irrelevant: Dependencies installed OK with the exception of Perl, which failed the post-installation. But I have installed Perl with `yum install` beforehand, anticipating this issue.
This error occurs at the last step, when installing pdf2htmlex itself. 

- What you expected to happen
I expected the installation to go through, or at least not producing this particular error. 

- Step-by-step reproduction instructions (by running `brew install` commands)

1. build the docker container with
Dockerfile:
```
FROM some_basic_red_hat_image_that_has_nothing_installed
RUN yum install -y nano which curl g++ gawk git m4 make patch tar file perl perl-Data-Dumper\
&& yum clean all \
&& rm -rf /var/cache/yum

RUN useradd -m -s /bin/bash linuxbrew
RUN echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew
ENV PATH /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH
ENV SHELL /bin/bash
RUN yes |sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```
2. After successfully building the docker image, log into the image container as the user linuxbrew

3. run `brew install pdf2htmlex`: Towards the end of the installation, one sees the above error.

**Comment by SMillerDev** [comment]
This isn't the repo for linuxbrew. Check homebrew/linuxbrew-core for that.
