### ISSUE TITLE
Revert PostgreSQL Formula to 11.3

### ISSUE THREAD

**Issue by shawnweeks** [Homebrew/homebrew-core#41997]
Postgres 11.4 has a major bug and breaks most applications. See https://www.postgresql.org/message-id/15580-d1a6de5a3d65da51%40postgresql.org. We should revert the formula or provide a way to install 11.3 until this is fixed.

**Comment by shawnweeks** [comment]
This isn't a bug with Homebrew, we've just pushed a formula release that has a rather serious bug upstream and is unusable with no easy way to rollback. I don't see how the bug report checklist applies here

**Comment by SMillerDev** [comment]
The recommended course of action is in the issue template.

**Comment by shawnweeks** [comment]
I don't see how the template actually supports a bug with version of external software but I've filled it out the best I can.

**Comment by SMillerDev** [comment]
>  are reporting a bug others will be able to reproduce and _**not asking a question or requesting software**_. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. _**To get software added or changed in Homebrew please file a Pull Request**_

I've marked the applicable words from the first bulletpoint of the template.

**Comment by shawnweeks** [comment]
I'm not in a position to contribute to this project at this time. I was merely letting you know that there is an active issue with the current published version that will be effecting other users and other Homebrew Formulas like Grafana.
