### ISSUE TITLE
unusable packages (sdl1 and gdb)

### ISSUE THREAD

**Issue by nsklaus** [Homebrew/homebrew-core#42035]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
yes, everybody can reproduce

- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
no, brew ran fine. the problem is just that it is offering to install broken packages.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/nsklaus/69ee5408caa1849b2e0ec78c9856b339
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
use sdl1 and gdb to dev personal project

- What happened (include command output)
sdl1 won't render anything and gdb is not being code signed and cannot be used.

- What you expected to happen
sdl1 to render properly and gdb to work properly

- Step-by-step reproduction instructions (by running `brew install` commands)
install went fine in both cases, it is just that the installed package are not functioning correctly.
--

hi, 
brew is offering to install sdl1 and gdb, but, they don't work properly.

- sdl1 is not rendering anything.
- gdb complains about not being code signed, and is not usable either.

it is good that these package are being offered by brew,
but please make it so they can be used. 

Issues for these packages have been opened before, 
and have now been closed, marked as resolved, but they are Not.
some said it's an upstream issue and the burden of the fix is onto them.
well, ok, but then don't acknowledge they are broken and offer these packages in the same time as if they were fine. mark them broken, append a suffix, put a note, or something.
oh, and `brew install gdb --HEAD` also failed. 
here's the output:
```
kmbp: build
$ brew install gdb --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Cloning https://sourceware.org/git/binutils-gdb.git
Updating /Users/klaus/Library/Caches/Homebrew/gdb--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at dfd6917457 x86: make RegMem an opcode modifier
==> ./configure --prefix=/usr/local/Cellar/gdb/HEAD-dfd6917 --enable-targets=all --with-python=/usr --disable-binutils
==> make
Last 15 lines from /Users/klaus/Library/Logs/Homebrew/gdb/02.make:
                                     ^
darwin-nat-info.c:620:25: error: use of undeclared identifier 'target_gdbarch'
  if (gdbarch_addr_bit (target_gdbarch ()) <= 32)
                        ^
darwin-nat-info.c:657:35: error: use of undeclared identifier 'target_gdbarch'
        uiout->field_core_addr ("start", target_gdbarch (), r_start);
                                         ^
darwin-nat-info.c:658:33: error: use of undeclared identifier 'target_gdbarch'
        uiout->field_core_addr ("end", target_gdbarch (), r_start + r_size);
                                       ^
5 errors generated.
make[2]: *** [darwin-nat-info.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-gdb] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
unusable packages (sdl1 and gdb) https://github.com/Homebrew/homebrew-core/issues/42035
kmbp: build
$
```

my test environment is macbookpro 12,1 (early 2015) and macos mojave 10.14.5.
if requested i can reproduce and execute commands or giving outputs, logs and so on..
thanks

**Comment by nsklaus** [comment]
i've updated my issue with the requested format.

**Comment by SMillerDev** [comment]
I've edited your issue to use the original template text, the bot is difficult that way.

**Comment by nsklaus** [comment]
thank you

**Comment by jonchang** [comment]
GDB requiring code signing is a macOS restriction, we can't do anything about that. `brew info gdb` will give you instructions on how to get it working.

Can you post code that reproduces your error with sdl?

**Comment by nsklaus** [comment]
@jonchang 
sdl1 produce no particular errors, it just show a blank window, nothing being rendered at all.
and about gdb i understand it is a macos restriction, but the point is: the result is not usable.
why offer it seemingly as if it was just another package, in working order, where it is not. 
there's always a reason. i'm not trying to understand the 'why' it doesn't work.
i'm just looking at the result. it is not in working order.

**Comment by jonchang** [comment]
There are specific steps that you need to take to get gdb to work. I have gdb working fine for me after following the steps in `brew info gdb`. As you were told on Discourse, there are thousands of people who are using this package, apparently successfully. There are extra steps but we can't do anything about it since it's a macOS restriction.

That issue you linked seems to be related to `sdl` vs `sdl2`, and build instructions that are specific macOS, which you'll have to debug yourself. Other extremely popular packages like ffmpeg are using sdl with no problems.

**Comment by nsklaus** [comment]
@jonchang 
i'm now seeing the 'caveats message, when installing gdb.

```
==> Caveats
gdb requires special privileges to access Mach ports.
You will need to codesign the binary. For instructions, see:

  https://sourceware.org/gdb/wiki/BuildingOnDarwin
```

maybe i didn't noticed it before, but it is good that it is there.
thank you for your reply.

**Comment by lonelykid** [comment]
May be a stupid question, but I'm unable to get it to work. I've followed all the instructions.
It used to be working with and only with sudo privilege.
But now it gets stuck when I run the debugged program
Starting program: /path to debugged file
[New Thread 0x1203 of process 68164]
The gdb process will not exit and cannot be killed. Only reboot will eliminate it.
This is pretty much similar to what used to happen without a sudo.
