### ISSUE TITLE
gnupg should depend on pinentry-mac

### ISSUE THREAD

**Issue by Splarv** [Homebrew/homebrew-core#42113]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The subject of this issue duplicate #18011, but there is another reason for this. And due to #18011 is closed for commenting, I forced to open new issue about it. The reason is:

The brew gpg depend in pinetry. The brew pinentry come with `pinentry-curses` and `pinentry-tty`, the default symlink `pinentry` point to `pinentry-curses`. I tried to use gpg to sign commits in git. But with git gpg is not work. The error is:

  $ git commit -m '3'
  error: gpg failed to sign the data
  fatal: failed to write commit object

I tried to directly point in ~/.gnupg/gpg-agent.conf to pinentry-curses and pinentry-tty, the result is the same. The workaround is to set empty password for the key. Or install  pinentry-mac and point in ~/.gnupg/gpg-agent.conf to it, after this git correctly working and signing commits. So IMHO, gnupg must depend on pinentry-mac, not on pinentry-curses/tty, and so all be work by default. Or at list mention about this issue in the formulae info of the gpg.

Just for bureaucracy:

$ brew gist-logs gpg
Error: No logs.

$ brew config
HOMEBREW_VERSION: 2.1.7-41-g7615dff
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7615dffc0a5f3674610821a34e5699820e6af83f
Last commit: 36 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 270f5f1
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by Splarv** [comment]
$ brew config
HOMEBREW_VERSION: 2.1.7-41-g7615dff
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7615dffc0a5f3674610821a34e5699820e6af83f
Last commit: 36 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 270f5f1b7eba8c1c9652ec9b5d2599162db0db16
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.2.1
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by SMillerDev** [comment]
This isn't really a bug but a feature/change request. And those should be filed as pull requests.

**Comment by Splarv** [comment]
Git don't work with gpg by now without visible reason. And this is a bug.

**Comment by SMillerDev** [comment]
Gpg isn't just for git. I'd say the lack of a visible reason is a bug in git or gpg. But homebrew does exactly what it's supposed to.

**Comment by Splarv** [comment]
Don't agree. This is a homebrew who install gpg in configuration when git don't work and btw homebrew itself heavily depend on git. :) The root of the problem is in homebrew dependences.

**Comment by SMillerDev** [comment]
If you disagree with the current state you could make a pull request. But it's not a bug to install just gpg if you ask for gpg. Just because you can do a ton of stuff with it doesn't mean that the default install should include everything.

**Comment by Splarv** [comment]
Yep, but gpg already pull pinentry-curses and pinentry-tty (depends on package pinentry), that don't work with git, instead of pinentry-mac which fine and even can use (optionaly) MacOS keyring for passwords.

That the homebrew install dependences which created problems and sometimes don't work, instead of install alternative dependences that working shiningly, looked like a bug of dependences.

Well, at least if someone will meet the same bug and will google it, he'll can read from here how to solve it and about the devs thinking this is not a bug. :)
