### ISSUE TITLE
wget --with-debug isn't working

### ISSUE THREAD

**Issue by TheKnarf** [Homebrew/homebrew-core#42127]
- What you were trying to do (and why)

I'm trying to run `wget` with the debug option using `wget -d`. 
This gives me `Debugging support not compiled in. Ignoring --debug flag.`.

According to [this discourse.brew.sh](https://discourse.brew.sh/t/how-to-install-wget-with-debug-support/1672/2) discussion I should be able to install a version of `wget` with debug support using `brew reinstall wget --with-debug`. This does not work.

- What happened (include command output)

```
➜  beerjs git:(dev) ✗ brew reinstall wget --with-debug
Usage: brew reinstall [options] formula

Uninstall and then install formula (with existing and any appended install
options).

Unless HOMEBREW_NO_INSTALL_CLEANUP is set, brew cleanup will be run for the
reinstalled formulae or, every 30 days, for all formulae.

    -d, --debug                      If brewing fails, open an interactive
                                     debugging session with access to IRB or a
                                     shell inside the temporary build directory
    -s, --build-from-source          Compile formula from source even if a
                                     bottle is available.
        --force-bottle               Install from a bottle if it exists for the
                                     current or newest version of macOS, even if
                                     it would not normally be used for
                                     installation.
        --keep-tmp                   Don't delete the temporary files created
                                     during installation.
    -f, --force                      Install without checking for previously
                                     installed keg-only or non-migrated
                                     versions.
    -v, --verbose                    Print the verification and postinstall
                                     steps.
        --display-times              Print install times for each formula at the
                                     end of the run.
    -h, --help                       Show this message.
Error: invalid option: --with-debug
```

- What you expected to happen

I expected brew to reinstall wget with debug support

- Step-by-step reproduction instructions (by running `brew install` commands)

Run either of these commands to get the same error:

`brew install wget --with-debug`

or 

`brew reinstall wget --with-debug`

**Comment by SMillerDev** [comment]
Options like that were removed almost a year ago. If you want to modify the behavior of a formula and you think 80% of homebrew users would consider it useful you can make a pull request. And otherwise you can copy the formula into a personal tap.
