### ISSUE TITLE
Can not Instal Node.js OSX 10.12 error 

### ISSUE THREAD

**Issue by balouchi26** [Homebrew/homebrew-core#4216]
I was trying to install node on MacBook pro 2015 OSX 10.12 but not getting installed

make[3]: *** [liblzma_la-hardware_physmem.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [liblzma_la-block_util.lo] Error 1
2 errors generated.
make[3]: *** [liblzma_la-common.lo] Error 1
make[3]: *** [liblzma_la-filter_common.lo] Error 1
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../.. -I../../src/liblzma/api -I../../src/liblzma/common -I../../src/liblzma/check -I../../src/liblzma/lz -I../../src/liblzma/rangecoder -I../../src/liblzma/lzma -I../../src/liblzma/delta -I../../src/liblzma/simple -I../../src/common -DTUKLIB_SYMBOL_PREFIX=lzma_ -D_THREAD_SAFE -pthread -fvisibility=hidden -Wall -Wextra -Wvla -Wformat=2 -Winit-self -Wmissing-include-dirs -Wstrict-aliasing -Wfloat-equal -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Waggregate-return -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls -g -O2 -c ../common/tuklib_cpucores.c -o liblzma_la-tuklib_cpucores.o >/dev/null 2>&1
2 errors generated.
make[3]: *** [liblzma_la-index.lo] Error 1
make[3]: *** [liblzma_la-easy_preset.lo] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**Comment by dunn** [comment]
Please post your `brew gist-logs node`, please.

**Comment by balouchi26** [comment]
Where can I find this as I'm new to OSX

**Comment by balouchi26** [comment]
Shafqats-MBP:~ shafqatbalouch$ brew gist-logs node
Error: No logs.

**Comment by dunn** [comment]
What was the command you ran to install node?

Can you post `brew config` and `brew doctor` as well?

**Comment by balouchi26** [comment]
I ran the install command with -fs and its installing perfect

brew install node -fs
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for node: xz, pkg-config
==> Installing node dependency: xz
==> Using the sandbox
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
Already downloaded: /Users/shafqatbalouch/Library/Caches/Homebrew/xz-5.2.2.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.2
==> make install
🍺  /usr/local/Cellar/xz/5.2.2: 91 files, 1.4M, built in 32 seconds
==> Installing node dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/pkg-config/0.29.1_1 --disable-host-to
==> make
==> make check
==> make install
🍺  /usr/local/Cellar/pkg-config/0.29.1_1: 10 files, 627.4K, built in 1 minute 29 seconds
==> Installing node
==> Downloading https://nodejs.org/dist/v6.4.0/node-v6.4.0.tar.xz

**Comment by balouchi26** [comment]
It worked, congrats! I'm good to go with Node.js, npm, and Grunt.

npm install -g grunt-cli
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/lib
└─┬ grunt-cli@1.2.0 
  ├─┬ findup-sync@0.3.0 
  │ └─┬ glob@5.0.15 
  │   ├─┬ inflight@1.0.5 
  │   │ └── wrappy@1.0.2 
  │   ├── inherits@2.0.1 
  │   ├─┬ minimatch@3.0.3 
  │   │ └─┬ brace-expansion@1.1.6 
  │   │   ├── balanced-match@0.4.2 
  │   │   └── concat-map@0.0.1 
  │   ├── once@1.3.3 
  │   └── path-is-absolute@1.0.0 
  ├── grunt-known-options@1.1.0 
  ├─┬ nopt@3.0.6 
  │ └── abbrev@1.0.9 
  └── resolve@1.1.7

**Comment by balouchi26** [comment]
Any technical explanation to what happen will be great @dunn

**Comment by balouchi26** [comment]
I ran the following command

brew install node -fs

**Comment by balouchi26** [comment]
Last login: Wed Aug 24 19:01:52 on ttys000
Restored session: Wed Aug 24 19:14:01 EDT 2016
Shafqats-MBP:~ shafqatbalouch$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 72846fac47eb16e1f423b02637e11476e15752cd
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a143b527da2d73567b830ec668ae1be96108ab5f
Core tap last commit: 52 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.12-x86_64
Xcode: N/A
CLT: 8.0.0.0.1.1471054766
X11: N/A

**Comment by balouchi26** [comment]
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by dunn** [comment]
> I ran the install command with -fs and its installing perfect

How did you try to install it the first time?

**Comment by balouchi26** [comment]
without  -fs
brew install node

**Comment by DomT4** [comment]
Pretty sure your original failure came from `xz`, not `node`. For whatever reason, `xz` built successfully the second time, which allowed the rest of the build queue culminating in `node` to finish successfully.

**Comment by MikeMcQuaid** [comment]
Node is installed so closing this.
