### ISSUE TITLE
brew install gcc hanging on macOS Sierra Public Beta 5

### ISSUE THREAD

**Issue by zg** [Homebrew/homebrew-core#4223]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

`brew install gcc` is hanging on macOS Sierra Public Beta 5. I left my computer to go get food and came back an hour later only to find that it was still on the `make bootstrap` step.

**Comment by mistydemeo** [comment]
How fast is your computer? Building GCC can take a very long time, and if you have a slow computer or if your CPU was busy with other things, taking over an hour is actually pretty normal.

**Comment by zg** [comment]
![screen shot 2016-08-24 at 23 36 00](https://cloud.githubusercontent.com/assets/407905/17959180/88c71ce8-6a53-11e6-8dbf-c8bacfeeb406.png)

**Comment by zg** [comment]
I'm running on a 2013 MacBook Pro with an Intel i5 and 4GB of memory.

**Comment by MikeMcQuaid** [comment]
Yes, it may take more than an hour. Give it 6-8 hours and let us know if it still didn't build.

**Comment by zg** [comment]
Wow.

**Comment by zg** [comment]
I probably should have run `brew install --verbose gcc` before opening this.

Thank you for the replies.

**Comment by zg** [comment]
FWIW: `🍺  /usr/local/Cellar/gcc/6.2.0: 1,435 files, 275.2M, built in 80 minutes 39 seconds`

**Comment by skube** [comment]
FWIW: `🍺  /usr/local/Cellar/gcc/7.1.0: 1,486 files, 283.8MB, built in 922 minutes 48 seconds`

on 2.9 GHz Intel Core i5 MBP w/ 8GB
