### ISSUE TITLE
macvim 8.1-157 - interesting checksum on source tarball

### ISSUE THREAD

**Issue by andistern** [Homebrew/homebrew-core#42304]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`Error:    No logs`

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
brew config
HOMEBREW_VERSION: 2.1.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 549a40bedb32171912a449d8d0e7bcae02d5b432
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a7f3781788ecfc1450ef4129acbf9cd332e8e6e6
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_INSTALL_CLEANUP: 1
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_31
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

```
brew doctor

...
Warning: You have unlinked kegs in your Cellar.
...
  wireshark


```
To help us debug your issue please explain:

- What you were trying to do (and why)
`brew upgrade -s macvim`
- What happened (include command output)
```
==> Upgrading 1 outdated package:
macvim 8.1-156 -> 8.1-157
==> Upgrading macvim 
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-157.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapshot-157
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: dbe7f4b19231989bb24f1e3e42f1372451974d8a224ba17498a103c325635e0a
  Actual: cb2f5ff0828bcc5e04c816998599b1a05685fd432e56d82c395780208c3263e3
 Archive: /Users/astern/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
To retry an incomplete download, remove the file above.

```

- What you expected to happen
install snapshot 157 of macvim
- Step-by-step reproduction instructions (by running `brew install` commands)
```
rm /Users/astern/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
```
```
wget https://github.com/macvim-dev/macvim/archive/snapshot-157.tar.gz
```
```
shasum -a 256 snapshot-157.tar.gz
cb2f5ff0828bcc5e04c816998599b1a05685fd432e56d82c395780208c3263e3  snapshot-157.tar.gz
```
How else could I support you?

regards

A.

**Comment by SMillerDev** [comment]
Could you check with upstream if that was meant to happen? And if it was, make a pull request with a link to the answer from upstream?

**Comment by andistern** [comment]
There was no comment regarding the snapshot 157 version, just an update...
... no clue after reading https://stackoverflow.com/questions/46514831/how-read-the-current-upstream-for-a-git-branch ... no ressources for diving into further researching ...
please supply a pointer to further information, ideally step by step guide ;-)
Thank you!

**Comment by SMillerDev** [comment]
> There was no comment regarding the snapshot 157 version, just an update...
> ... no clue after reading https://stackoverflow.com/questions/46514831/how-read-the-current-upstream-for-a-git-branch ... no ressources for diving into further researching ...
> please supply a pointer to further information, ideally step by step guide ;-)
> Thank you!

I think you're looking at the wrong kind of upstream. I meant this: https://en.wikipedia.org/wiki/Upstream_(software_development). You should ask the macvim developers if the change was intentional. If it was you can make the change in homebrew using this guide: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by snobb** [comment]
I've got the same issue:
```$ brew install -s macvim
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-157.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapshot-157
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: dbe7f4b19231989bb24f1e3e42f1372451974d8a224ba17498a103c325635e0a
  Actual: 6447bce4ec7b7f67327da8f7b2e9d4f4b748c1afb90f781fecb6b4a3f54cf0a0
 Archive: /Users/kozadaev/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
To retry an incomplete download, remove the file above.
```
The the actual checksum look different from the one in the problem description. So looks like the brew expects the old checksum, while the snapsho-157 keeps changing without incrementing the version (which is odd).

**Comment by andistern** [comment]
... back from holidays ;-)) & many thanks to vaga . should perhaps close this one, as https://github.com/macvim-dev/macvim/issues/934 is correct?
