### ISSUE TITLE
Consider removing rtorrent from Homebrew boneyard

### ISSUE THREAD

**Issue by zg** [Homebrew/homebrew-core#4233]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

I was able to successfully install and run `rtorrent` on my Macbook Pro:

<img width="698" alt="screen shot 2016-08-25 at 11 59 57" src="https://cloud.githubusercontent.com/assets/407905/17982143/7ef9b442-6abb-11e6-8110-6bcf2b1f74ac.png">

[`brew gist-logs rtorrent`](https://gist.github.com/c5d5fc2cc9212eb3021ce247f7f147c7)

[`brew gist-logs libtorrent`](https://gist.github.com/a4f405f1e837e098e900b76edc2ea99a)

**Comment by MikeMcQuaid** [comment]
We will consider it when it builds with Clang so we can produce a binary package for it.

**Comment by zg** [comment]
How can I teat building it with clang?

**Comment by MikeMcQuaid** [comment]
`brew install rtorrent --cc=clang`

**Comment by zg** [comment]
Is this fixable?

```
$ brew install rtorrent --cc=clang
==> Installing rtorrent from homebrew/boneyard
==> Installing dependencies for homebrew/boneyard/rtorrent: libtorrent
==> Installing homebrew/boneyard/rtorrent dependency: libtorrent
==> Downloading http://rtorrent.net/downloads/libtorrent-0.13.6.tar.gz
Already downloaded: /Users/zzatking/Library/Caches/Homebrew/libtorrent-0.13.6.tar.gz
==> sh autogen.sh
==> ./configure --prefix=/usr/local/Cellar/libtorrent/0.13.6 --with-kqueue --enable-ipv6
==> make
==> make install
🍺  /usr/local/Cellar/libtorrent/0.13.6: 70 files, 1.2M, built in 1 minute 14 seconds
==> Installing homebrew/boneyard/rtorrent
==> Downloading http://rtorrent.net/downloads/rtorrent-0.9.6.tar.gz
Already downloaded: /Users/zzatking/Library/Caches/Homebrew/rtorrent-0.9.6.tar.gz
==> sh autogen.sh
==> ./configure --prefix=/usr/local/Cellar/rtorrent/0.9.6
==> make
Last 15 lines from /Users/zzatking/Library/Logs/Homebrew/rtorrent/03.make:
make[3]: *** [download_factory.o] Error 1
In file included from download_store.cc:56:
In file included from ./download.h:41:
/usr/local/Cellar/libtorrent/0.13.6/include/torrent/download_info.h:43:10: fatal error: 'tr1/functional' file not found
#include <tr1/functional>
         ^
1 error generated.
make[3]: *** [dht_manager.o] Error 1
1 error generated.
1 error generated.
make[3]: *** [download_list.o] Error 1
make[3]: *** [download_store.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
rtorrent was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
```

**Comment by MikeMcQuaid** [comment]
@zg Maybe but it's not up to Homebrew to do so, you'll need to submit patches to the upstream project and when they have a new release that builds with Clang we'll consider readding it.

**Comment by zg** [comment]
> @zg Maybe but it's not up to Homebrew to do so, you'll need to submit
> patches to the upstream project and when they have a new release that
> builds with Clang we'll consider readding it.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Homebrew/homebrew-core/issues/4233#issuecomment-242664217

My thought was that there was a dependency that could be included but I
guess not.

Thanks for getting back to me.
