### ISSUE TITLE
include-what-you-use does not work on C++ files out of the box

### ISSUE THREAD

**Issue by ptomato** [Homebrew/homebrew-core#42538]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software.
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS?
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Description ###

I am trying to run include-what-you-use on a C++ program. It looks like Homebrew's include-what-you-use only works on C programs. There is a [test for C programs in the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/include-what-you-use.rb#L46-L73) which I verified on my system with both `brew test include-what-you-use` as well as recreating the test manually.

When I run the same test but in C++, by renaming `main.c` to `main.cpp`, I get an error saying that the compiler cannot find a definition for `size_t`. See below for exact error output. Trying include-what-you-use on more complicated C++ programs gives different errors, especially when including C++ standard library headers.

I would expect a minimal program like this to run correctly out of the box, giving the same output as the expected output in the test linked above.

In any case it seems like a good idea to put a similar minimal test for C++ into the formula.

### Step-by-step reproduction instructions ###

```
$ brew install include-what-you-use
==> Downloading https://homebrew.bintray.com/bottles/include-what-you-use-0.12.m
Already downloaded: /Users/ptomato/Library/Caches/Homebrew/downloads/191922a9d8a4eeda5452d0e8706d082f159c8f2a152454ff61158f0af62e33b6--include-what-you-use-0.12.mojave.bottle.tar.gz
==> Pouring include-what-you-use-0.12.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/include-what-you-use/0.12: 163 files, 30MB
$ cat >direct.h <<EOF
#include <stddef.h>
size_t function() { return (size_t)0; }
EOF
$ cat >indirect.h <<EOF
#include "direct.h"
EOF
$ cat >main.cpp <<EOF
#include "indirect.h"
int main() { return (int)function(); }
EOF
$ include-what-you-use main.cpp 
In file included from main.cpp:1:
In file included from ./indirect.h:1:
./direct.h:2:1: error: unknown type name 'size_t'
size_t function() { return (size_t)0; }
^
./direct.h:2:29: error: use of undeclared identifier 'size_t'; did you mean
      'sizeof'?
size_t function() { return (size_t)0; }
                            ^~~~~~
                            sizeof
./direct.h:2:35: error: expected expression
size_t function() { return (size_t)0; }
                                  ^
```

### Debug output ###
```
$ brew gist-logs include-what-you-use
Error: No logs.
$ brew config
HOMEBREW_VERSION: 2.1.8-13-g6db1c73
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6db1c7383f5fed67a4c18e131f6b26d1aa5eb418
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 46d20bdd1a21b27008cca01cfc87322b50283aab
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.3
CLT headers: 10.2.1.0.1.1554506761
XQuartz: 2.7.11 => /opt/X11
$ brew doctor
Your system is ready to brew.
```

**Comment by tschoonj** [comment]
It works when I replace `#include <stddef.h>` with `#include <cstddef>` in `direct.h`.

**Comment by ptomato** [comment]
That doesn't seem correct, though; `<cstddef>` ought to define `std::size_t`, not `size_t`.

**Comment by fxcoudert** [comment]
The formula tests are created to make sure that the software is compiled properly, and cannot be exhaustive tests. We maintain over 4,000 formulas and cannot catch every bug in each one.

Given that this looks like an upstream issue, please report it to https://include-what-you-use.org/
If with their help debugging it turns out that it's a problem in how we build it, we'll try to help and fix the formula (or happily consider a pull request doing just that).

**Comment by ptomato** [comment]
I am pretty sure it's a packaging issue where there is a confusion between the Xcode headers and homebrew clang headers, possibly related to https://github.com/include-what-you-use/include-what-you-use/issues/438. I can open it upstream but I'm fairly sure they'll just close it.
