### ISSUE TITLE
Refactor ngHTTP2 to Have Cython as a Build-Time Dependency, Not as a Vendored Resource

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#4254]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~  N/A

I've noticed that [`nghttp2.rb`'s current revision](https://github.com/Homebrew/homebrew-core/blob/336fa03a3fcfa8bcd456939fb1307a951805718c/Formula/nghttp2.rb) has the following on [lines 37–40](https://github.com/Homebrew/homebrew-core/blob/336fa03a3fcfa8bcd456939fb1307a951805718c/Formula/nghttp2.rb#L37-L40):  

```
⋮
  resource "Cython" do
    url "https://pypi.python.org/packages/b1/51/bd5ef7dff3ae02a2c6047aa18d3d06df2fb8a40b00e938e7ea2f75544cac/Cython-0.24.tar.gz"
    sha256 "6de44d8c482128efc12334641347a9c3e5098d807dd3c69e867fa8f84ec2a3f1"
  end
⋮
```

Shouldn't this be removed and replaced by something like '`depends_on "cython" => :build`' earlier up in the `class Nghttp2 < Formula`?  Also, I didn't see a `stable do` block anywhere.  Should this be fixed, too?

**Comment by DomT4** [comment]
I'm not sure whether you're misunderstanding the formula or I'm misunderstanding you here, so apologies if it's the latter.

`depends_on` lines generally refer to formulae, particularly these days. We used to sometimes do things like `depends_on "cython" => :python` but it was really bad UX & has been replaced by resourcing as widely as possible. Since there's no `cython` formulae, all that would happen is Homebrew would panic that the `depends_on` could not be fulfilled with something like:
```
No available formula with the name "cython" (dependency of nghttp2)
```

The `cython` element is also never permanently installed. It is built in the buildpath & used to install the Python3 bindings if that option has been invoked, and then the buildpath is discarded with the `cython` element inside of it.

> Also, I didn't see a stable do block anywhere. Should this be fixed, too?

`stable do` doesn't have to be explicit. If it isn't there, the main block is taken to be implicitly stable. Really, the only time `stable do` should exist is if stable needs an exclusive element that `devel` or `head` do not, such as a resource, a dependency, a patch, etc.

**Comment by tdsmith** [comment]
> Shouldn't this be removed and replaced by something like `depends_on "cython" => :build`

We could start doing this instead of resourcing it in individual formulas. I proposed this at one point but it never felt urgent.

**Comment by DomT4** [comment]
Yeah, I vaguely remember there being a discussion on a `cython` formulae and the consensus was 👍. If someone wants to do that I'd be fine with it still, like we did with `sphinx-doc`.

**Comment by RandomDSdevel** [comment]
@DomT4:  
> I'm not sure whether you're misunderstanding the formula or I'm misunderstanding you here, so apologies if it's the latter.  
>
> ⋮

No, that's OK; after reading on through the rest of your reply, I'm convinced it was the former, so my bad (😆…)  

> ⋮
>
> `depends_on` lines generally refer to formulae, particularly these days.  …

OK, I'm following you so far.  

> …We used to sometimes do things like `depends_on "cython" => :python` but it was really bad UX…

How so, exactly?  

> … & has been replaced by resourcing as widely as possible.  …

Right.  

> …Since there's no `python` formulae, …

Doh, I should have checked to see whether such a formula existed before I filed this issue!  😆

> …all that would happen is Homebrew would panic that the `depends_on` could not be fulfilled with something like:  
> 
>     No available formula with the name "cython" (dependency of nghttp2)
> 
> ⋮

Hmm, that _would_ be annoying!  

> ⋮
> 
> The `cython` element is also never permanently installed.  …

_I_ wouldn't mind having Cython installed permanently, at least on _my_ machine, since other Python-requiring formulas might use it as well.  

> …It is built in the buildpath & used to install the Python3 bindings if that option has been invoked, and then the buildpath is discarded with the `cython` element inside of it.  
>
> ⋮

Would it possibly be any faster if Cython were built _outside_ of the build path and then symbolically linked _into_ it, or is the version of it that's downloaded and installed a pre-built binary from upstream?  

> ⋮
>> Also, I didn't see a `stable do` block anywhere.  Should this be fixed, too?  
>
> `stable do` doesn't have to be explicit.  If it isn't there, the main block is taken to be implicitly stable.  Really, the only time `stable do` should exist is if stable needs an exclusive element that `devel` or `head` do not, such as a resource, a dependency, a patch, etc.  

OK, thanks for clarifying that!  

<hr />

@tdsmith:  
>> Shouldn't this be removed and replaced by something like `depends_on "cython" => :build`?  
>
> We could start doing this instead of resourcing it in individual formulas. I proposed this at one point but it never felt urgent.  

I think that would feel a bit more natural and would save us Homebrew contributors and you maintainers from having to go in to every single formula and updating every instance of a resource every single time upstream supplied updates for it&thinsp;—&thinsp;oh, and that reminds me:  I almost forgot to note for reference in the near future that `nghttp2.rb`'s `cython` resource appears to be out of date.  In any case, I'd be interested in following any discussions that end up happening about this possible direction, so let me know if anybody starts any again somewhere and I'll subscribe to the relevant thread.  

<hr />

@DomT4:  
> Yeah, I vaguely remember there being a discussion on a `cython` [formula] and the consensus was 👍. If someone wants to do that I'd be fine with it still, like we did with `sphinx-doc`.  

Should I, either you or @tdsmith, or somebody else go ahead and create a placeholder issue for this in anticipation of whoever might end up getting around to submitting a pull request first, then?

**Comment by tdsmith** [comment]
>  is the version of [Cython] that's downloaded and installed a pre-built binary from upstream?

It is not. It adds about a minute to the build.

>  you maintainers from having to go in to every single formula and updating every instance of a resource every single time upstream supplied updates for it 

We generally don't do this unless there's a security issue; if it works, it doesn't need to be the latest and greatest, and new versions sometimes introduce regressions!

**Comment by DomT4** [comment]
> How so, exactly?

If we couldn't `python -c "import cython"` as part of pre-build checks installation would fail hard and request you take the necessary step, meaning automated installations of those formulae were deeply impractical. Also meant building against the latest upstream release every time, which may have introduced bugs and makes reproducible builds across a significant period of time an impossibility.

>  or is the version of it that's downloaded and installed a pre-built binary from upstream?

We don't use prebuilt Python binaries from upstream. Tim may want to elaborate on that, but that's the skinny of it.

> I think that would feel a bit more natural and would save us Homebrew contributors and you maintainers from having to go in to every single formula and updating every instance of a resource every single time upstream supplied updates for it 

Note that there's no broad plan at all to make this a regular thing for every Python resource we ever vendor into any formula. We'll do it for very specific cases, usually when that resource is only needed for build & is needed by a significant number of formulae.

> somebody else go ahead and create a placeholder issue for this in anticipation of whoever might end up getting around to submitting a pull request first, then?

We don't really do placeholder issues, because they tend to be placeholder issues until the end of time itself 🙈. People almost never pick them up, and they quickly get buried on the tracker. If you care I'd probably submit a PR, or otherwise trust Tim & I not to forget this is on Homebrew's to-do list.

**Comment by RandomDSdevel** [comment]
@tdsmith:  
>> …is the version of [Cython] that's downloaded and installed a pre-built binary from upstream?
> It is not. It adds about a minute to the build.
>
> ⋮

Ah, so I guess it wouldn't really be that much of a priority to try and reduce that, then.  

> ⋮
>
>> …you maintainers from having to go in to every single formula and updating every instance of a resource every single time upstream supplied updates for it 
> We generally don't do this unless there's a security issue; if it works, it doesn't need to be the latest and greatest, and new versions sometimes introduce regressions!  

Oh, right; there is _that_ aspect of it (heh, should've thought a little more about possible consequences of being over-eager about propagating updates to other Homebrew end-users.)  

<hr />

@DomT4:  
>> How so, exactly?  
> If we couldn't `python -c "import python"` as part of pre-build checks installation would fail hard and request you take the necessary step, meaning automated installations of those formulae were deeply impractical. Also meant building against the latest upstream release every time, which may have introduced bugs and makes reproducible builds across a significant period of time an impossibility.  
>
> ⋮

Again, I should have thought harder about the possible consequences here.  😆

> ⋮
>
>> …or is the version of it that's downloaded and installed a pre-built binary from upstream?  
> We don't use prebuilt Python binaries from upstream.  Tim may want to elaborate on that, but that's the skinny of it.  
>
> ⋮

I was referring to Cython, but, OK, that's what I thought; I just wanted to make sure that I understood the situation here on that front correctly.  

> ⋮
>> I think that would feel a bit more natural and would save us Homebrew contributors and you maintainers from having to go in to every single formula and updating every instance of a resource every single time upstream supplied updates for it…
> Note that there's no broad plan at all to make this a regular thing for every Python resource we ever vendor into any formula.  We'll do it for very specific cases, usually when that resource is only needed for build & is needed by a significant number of formulae.  

OK, that makes sense.  

> ⋮
>> …somebody else go ahead and create a placeholder issue for this in anticipation of whoever might end up getting around to submitting a pull request first, then?  
> We don't really do placeholder issues, because they tend to be placeholder issues until the end of time itself 🙈. People almost never pick them up, and they quickly get buried on the tracker. If you care I'd probably submit a PR, or otherwise trust Tim & I not to forget this is on Homebrew's to-do list.

My personal experience with this&thinsp;—&thinsp;in particular, with how, as mentioned by @dunn, [Issue #2937:  'ImageMagick v6.9.5-2'](https://github.com/Homebrew/homebrew-core/issues/2937) got swooped/sneaked up upon and taken care of by @zmwangx pretty quickly&thinsp;—&thinsp;suggests otherwise, but OK, that's fine by me.

**Comment by zmwangx** [comment]
> My personal experience with this — in particular, with how, as mentioned by @dunn, Issue #2937: 'ImageMagick v6.9.5-2' got swooped/sneaked up upon and taken care of by @zmwangx pretty quickly — suggests otherwise, but OK, that's fine by me.

To tell the truth, I hardly ever check the issue tracker. I updated IM because I regularly update IM, not because there's an issue for it.

**Comment by DomT4** [comment]
> Again, I should have thought harder about the possible consequences here.

Hey, if you did, us maintainers would be almost completely redundant. We might as well be useful whilst we're here 😉.

> and taken care of by @zmwangx pretty quickly — suggests otherwise

To be fair, @zmwangx is a fairly rare Homebrew contributor in terms of the combination of frequency of contributions, the high quality of those contributions & sometimes proactively plucking things off the Issue tracker. Very few non-maintainer contributors take on as much as @zmwangx does.

**Comment by RandomDSdevel** [comment]
@DomT4, @zmwangx:  
>> ⋮
>>>> …somebody else go ahead and create a placeholder issue for this in anticipation of whoever might end up getting around to submitting a pull request first, then?  
>>>
>>> We don't really do placeholder issues, because they tend to be placeholder issues until the end of time itself 🙈. People almost never pick them up, and they quickly get buried on the tracker. If you care I'd probably submit a PR, or otherwise trust Tim & I not to forget this is on Homebrew's to-do list.
>>
>> My personal experience with this&thinsp;—&thinsp;in particular, with how, as mentioned by @dunn, [Issue #2937:  'ImageMagick v6.9.5-2'](https://github.com/Homebrew/homebrew-core/issues/2937) got swooped/sneaked up upon and taken care of by @zmwangx pretty quickly&thinsp;—&thinsp;suggests otherwise, but OK, that's fine by me.  
> To tell the truth, I hardly ever check the issue tracker. I updated IM because I regularly update IM, not because there was an issue for it.

> To be fair, @zmwangx is a fairly rare Homebrew contributor in terms of the combination of frequency of contributions, the high quality of those contributions & sometimes proactively plucking things off the Issue tracker. Very few non-maintainer contributors take on as much as @zmwangx does.

OK, so it was just a coincidence of timing!  😆

**Comment by tdsmith** [comment]
I think the conversation is over so closing this; let me know if there's something actionable here I'm ignoring!

**Comment by RandomDSdevel** [comment]
@tdsmith:  We were thinking of creating a Cython formula for ngHTTP2 to use as a resource dependency, but that can be discussed later in a separate issue if you like.

**Comment by DomT4** [comment]
We'd be especially interested in a PR 😉.

**Comment by RandomDSdevel** [comment]
I'll see if I can make the time to get around to creating one, then.

**Comment by DomT4** [comment]
Thanks! If you get stuck feel free to file a broken PR & we'll work from there. A broken PR is safer than an Issue when it comes to chance of being forgotten.

**Comment by RandomDSdevel** [comment]
Will do, then!
