### ISSUE TITLE
SDCC 3.9.0 compiler fails to locate crt0iz.o which should be included

### ISSUE THREAD

**Issue by JamesDunne** [Homebrew/homebrew-core#42542]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Y] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [Y] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
[brew.config.txt](https://github.com/Homebrew/homebrew-core/files/3438816/brew.config.txt)
[brew.doctor.txt](https://github.com/Homebrew/homebrew-core/files/3438817/brew.doctor.txt)

To help us debug your issue please explain:

- What you were trying to do (and why)
Use brew's version of `sdcc` 3.9.0 to compile a test application for PIC18 microcontroller with an empty main() function.
- What happened (include command output)
```
$ sdcc --use-non-free -mpic16 -p18f46k22 main.c
crt0iz.o: No such file or directory
```
- What you expected to happen
Expected clean compilation with no errors.

The tarball binary distribution of sdcc for macos-amd64 (taken from their sourceforge site) includes the `crt0iz.o` file (and other variants) in the `share/sdcc/lib/pic16/` folder. This brew distribution does not include this folder at all.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install sdcc
$ cat > main.c
#include <pic18fregs.h>

#pragma config XINST=OFF

void main(void) {
}
$ sdcc --use-non-free -mpic16 -p18f46k22 main.c
crt0iz.o: No such file or directory
```

**Comment by fxcoudert** [comment]
Sorry for the long delay, I think none of the maintainers have ever used that software so it's hard to know what's the issue and how to fix. But it seems unlikely to be a bug specific to Homebrew, since we install the software make `configure && make && make install`, without any particular steps.

Where is the `crt0iz.o` file supposed to come from?
