### ISSUE TITLE
VTK formula binary has hardcoded dependency on Python 3.7.3 which may not be installed

### ISSUE THREAD

**Issue by themightyoarfish** [Homebrew/homebrew-core#42555]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
Error: No logs.
```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 2.1.8-35-g86e64cb
ORIGIN: https://github.com/Homebrew/brew
HEAD: 86e64cbb4e0014207b48ed1722675805d75c3ba6
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 84988df6fcf76a1203dd245d6dba76afde9b1b1d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_212
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libCppUnit_clang90_v3_0.dylib
  /usr/local/lib/libGCBaseTest_clang90_v3_0.dylib
  /usr/local/lib/libGCBase_clang90_v3_0.dylib
  /usr/local/lib/libGenApi_clang90_v3_0.dylib
  /usr/local/lib/libLog_clang90_v3_0.dylib
  /usr/local/lib/libMathParser_clang90_v3_0.dylib
  /usr/local/lib/libNodeMapData_clang90_v3_0.dylib
  /usr/local/lib/libResUsageStat_clang90_v3_0.dylib
  /usr/local/lib/libXmlParser_clang90_v3_0.dylib
  /usr/local/lib/liblog4cpp_clang90_v3_0.dylib
```

I am using VTK as a CMake dependency, and the build process for VTK make use of Python:

https://github.com/Homebrew/homebrew-core/blob/84988df6fcf76a1203dd245d6dba76afde9b1b1d/Formula/vtk.rb#L27

The `VTKTargets.cmake` file which gets generated by the build process contains a hardcoded dependency on the location of the Python interpreter used for building:
```
…
set_target_properties(vtkPythonInterpreter PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr;cxx_override"
  INTERFACE_LINK_LIBRARIES "vtkCommonCore;@@HOMEBREW_CELLAR@@/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Python;vtksys"
)
```

This Python version is not necessarily installed on the system downloading the package, so using VTK will fail. There seem to be the following options:

- Raise this issue with the VTK developers so they do not hardcode the dependency in the generated cmake files
- Have an option for the VTK formula to build without Python
- Somehow encode a dependency on a specific Python version in the homebrew formula

I am not versed in how Homebrew works, so apologies if this issue is something VTK needs to fix, but I'm wondering if anything could be done on the homebrew side that avoids building VTK from source.

---

A small CMake project is here:

**CMakeLists.txt:**
```
project(test)

find_package(VTK REQUIRED)

add_executable(test test.cpp)
target_link_libraries(test ${VTK_LIBRARIES})
```

**test.cpp:**
```
int main(int argc, char *argv[])
{
    return 0;
}
```

**Comment by themightyoarfish** [comment]
It seems that this Python issue is an ongoing problem in the vtk community: https://gitlab.kitware.com/vtk/vtk/issues/17214

Maybe the Homebrew build can somehow use the `OPTIONAL_PYTHON_LINK` flag that is used somewhere in VTK, but I don't see immediately where to pass it.

**Comment by MikeMcQuaid** [comment]
> * Somehow encode a dependency on a specific Python version in the homebrew formula

This is already the case.

> * Raise this issue with the VTK developers so they do not hardcode the dependency in the generated cmake files

This seems like a good idea.

**Comment by themightyoarfish** [comment]
If that is the case, how come I can install VTK which depdends on 3.7.3 even though that Python version is not installed?

**Comment by MikeMcQuaid** [comment]
It doesn't. It depends on whatever the latest version of Python is. It sounds like the issue is that these files need either regenerated for each Python version (which can happen by writing a `test do` block test that will fail unless it's updated) or using the correct Python path at `$HOMEBREW_PREFIX/opt/python/bin/python`

**Comment by lawrence-c** [comment]
Just hit this issue on a new machine when installing `pcl` with `brew install pcl`... 

`pcl` depends on `vtk`, which on the [formula page](https://formulae.brew.sh/formula/vtk), says it depends on Python 3.7.4, which I then get an error in the code similar to:
```
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/Python', needed by ....
```
Which doesn't exist as Python 3.7.3 is not installed.

I can workaround this by running `brew install vtk --build-from-source`, then `brew install pcl`, however this increases the install time quite significantly.
