### ISSUE TITLE
Formula gts: gts-config fetched depreciated path to glib

### ISSUE THREAD

**Issue by soteran** [Homebrew/homebrew-core#42567]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? >>> No logs.
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 

To help us debug your issue please explain:

- What you were trying to do (and why)
Trying to use gts-config to pick the necessary libraries for gts
- What happened (include command output)

<pre>
$ gts-config --cflags
-I/usr/local/Cellar/pcre/8.43/include -I/usr/local/Cellar/glib/2.60.4_1/include/glib-2.0 -I/usr/local/Cellar/glib/2.60.4_1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/gts/0.7.6_1/include
</pre>

or:

<pre>
$ gts-config --libs
-L/usr/local/Cellar/gts/0.7.6_1/lib -lgts -L/usr/local/Cellar/glib/2.60.4_1/lib -L/usr/local/opt/gettext/lib -lglib-2.0 -lintl -lm
</pre>

Both are showing the depreciated location `usr/local/Cellar/glib/2.60.4_1` for glib headers and libraries.

- What you expected to happen

The correct location is usr/local/Cellar/glib/2.60.6

- Step-by-step reproduction instructions (by running `brew install` commands)

See above. The problem is not with the installation of the gts formula itself, but the output of the gts-config command

Attached outputs:

brew config output:

<pre>
HOMEBREW_VERSION: 2.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 549a40bedb32171912a449d8d0e7bcae02d5b432
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 84988df6fcf76a1203dd245d6dba76afde9b1b1d
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.6.0_65-b14-468
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
</pre>

brew doctor has only a usual warning about some of my selfbuild applications with ./configure scripts: `Warning: "config" scripts exist outside your system or Homebrew directories. `, but they all build under /opt/local without conflicts with brew.

**Comment by fxcoudert** [comment]
Fixed in dd363f576c32653b87818a738b8d4f2f66d36aec
