### ISSUE TITLE
web100clt fails to build due to openssl issue on 10.11

### ISSUE THREAD

**Issue by stevenscb** [Homebrew/homebrew-core#426]
Having an issue installing web100clt from current bottle and from source on 10.11. 'brew link openssl --force' fixes the issue on a second install attempt (from source, the bottle is still broken).

See below:

Not working: 
[https://gist.github.com/anonymous/3fc81ec3f4db4510e1a92627c708eb70](https://gist.github.com/anonymous/3fc81ec3f4db4510e1a92627c708eb70)

See lines 125-131; 183 in '01.configure'

To fix:
```
brew link openssl --force
brew reinstall --build-from-source web100clt
```

Afterwards, working:
[https://gist.github.com/anonymous/15225bc17aaba71adb8bb91f7df94d67](https://gist.github.com/anonymous/15225bc17aaba71adb8bb91f7df94d67)

See same lines in '01.configure'

I realize force-linking openssl is probably not the best way to fix this and may cause other issues with my system but I use this tool often for work so that is acceptable for now. Just wanted to post an Issue to make others aware and see if we can work out the root cause.

Any time spent / insight / suggestions greatly appreciated.

-Bradley

**Comment by DomT4** [comment]
Oh, heh. The bottle includes a single manpage for El Cap. I'll look into this shortly, I suspect it's searching a set of default paths and coming up empty on 10.11.

**Comment by DomT4** [comment]
Should be fixed after a `brew update`. Thanks for the report!
