### ISSUE TITLE
xapian version incorrect, breaks upgrades

### ISSUE THREAD

**Issue by rnkn** [Homebrew/homebrew-core#42656]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

There seems to be something fish going on with the xapian version number. The formula has been updated by `homebrew-test-bot@lists.sfconservancy.org` to a bottle with version number 103, however this does not match the current version number xapian provides on [their website](https://xapian.org/) which is 1.4.12.

Obviously this is a problem if people install version "103" and then never get "upgraded" to version 1.4.12.

Also, please review your issue template. It's really not cool.

**Comment by SMillerDev** [comment]
The issue template isn't meant to be cool, it's meant to help people debug your issues. 

It seems the autodetected version in the last xapian update was wrong and nobody caught it. If you could make a pull request to update to 1.4.12 we can use that to reset the version number to what it should be.

**Comment by rnkn** [comment]
I'm getting this ""invalid multibyte character" error.
~~~
% brew bump-formula-pr --url https://oligarchy.co.uk/xapian/1.4.12/xapian-core-1.4.12.tar.xz --sha256 4f8a36da831712db41d38a039fefb5251869761a58be28ba802994bb930fac7c xapian -n  
######################################################################## 100.0%
Error: xapian-core-1.4.12.tar.xz: /Users/Paul/Library/Caches/Homebrew/Formula/xapian-core-1.4.12.tar.xz:1: invalid multibyte char (UTF-8)
~~~
Happens with 1.4.11 too.

**Comment by SMillerDev** [comment]
You need to do `--url=some.url` instead of the space

**Comment by rnkn** [comment]
Of course, how silly of me. Brb.

**Comment by rnkn** [comment]
As feared:
~~~
==> replace /https:\/\/oligarchy\.co\.uk\/xapian\/RELEASE\/1\.4\/xapian\-core\-1\.4\.11_git103\.tar\.xz/ with "https://oligarchy.co.uk/xapian/1.4.12/xapian-co
==> replace "7402311ac96c4386894eab8e240c5c022ad695757710dc437514a551e6f1d3f1" with "4f8a36da831712db41d38a039fefb5251869761a58be28ba802994bb930fac7c"
Error: You probably need to bump this formula manually since changing the
version from 103 to 1.4.12 would be a downgrade.
~~~
Manual Rubying goes above my paygrade I'm afraid.

**Comment by SMillerDev** [comment]
I usually have no idea what I'm doing with ruby either. It's just replacing url and hash A with url and hash B. If you open the file (brew edit <formula>) you'll see it's actually pretty easy.

**Comment by SMillerDev** [comment]
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request should be a good guide for this

**Comment by rnkn** [comment]
That would be fine, except I've done that before, and instead of just merging my commit, the maintainers applied my changes and committed themselves, leaving me with a dirty repo history. Fool me once...

**Comment by alebcay** [comment]
This issue is addressed in https://github.com/Homebrew/homebrew-core/pull/42795.

--

On a side note...

> That would be fine, except I've done that before, and instead of just merging my commit, the maintainers applied my changes and committed themselves, leaving me with a dirty repo history. Fool me once...

This is to avoid the usual Git fast-forward/merge boilerplate of "Merge <branch> into <branch>" that really clutters up the history. It's quite a common practice in environments where many people are committing and the repo moves so fast that not everyone may be committing off of a very recent revision.

An easy way I work around this is just to keep a local, clean `master` branch that I always `git pull upstream master && git push origin master` where `upstream` is this repo. Then all my PRs all just start with `git checkout -b <branch>`, ensuring that I'm working off of a clean copy of this repo.

**Comment by rnkn** [comment]
Thanks for doing the codes.

> This is to avoid the usual Git fast-forward/merge boilerplate of "Merge [branch] into [branch]" that really clutters up the history. It's quite a common practice in environments where many people are committing and the repo moves so fast that not everyone may be committing off of a very recent revision.

This is a misunderstand of git... maybe coming from an SVN background? It is a distributed VCS, so there is no need for everyone to be working off the most recent copy of upstream. What you're describing is A Feature Not A Bug.

> An easy way I work around this is just to keep a clean `master` branch on my fork that I always `git pull upstream master && git push origin master` where `upstream` is this repo. Then all my PRs all just start with `git checkout -b [branch]`, ensuring that I'm working off of a clean copy of this repo.

Lol I'm not doing that.

**Comment by alebcay** [comment]
>  This is a misunderstand of git... maybe coming from an SVN background? It is a distributed VCS, so there is no need for everyone to be working off the most recent copy of upstream. What you're describing is A Feature Not A Bug.

I'm well aware that this is not required (I've never used `svn` before) but in any case, it keeps the commit history clean and I personally hate trudging through merge commits.

> Lol I'm not doing that.

Then don't.

**Comment by SMillerDev** [comment]
> Lol I'm not doing that.

If you're not willing to work with the maintainers trying to help you, why should they help you?
https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/
