### ISSUE TITLE
fish: brew autocompletion not working

### ISSUE THREAD

**Issue by robsonpeixoto** [Homebrew/homebrew-core#4276]
After the homebrew changes, the auto-completion are not working.
If you try to autocomplete the `brew install` you will get this error:
```
➜  Formula git:(master) ✗ brew install No matches for wildcard '$formuladir/*.rb'.
/usr/local/Cellar/fish/2.3.1/share/fish/completions/brew.fish (line 3):     ls $formuladir/*.rb | sed 's/.rb$//' | sed "s|^$formuladir||"
                                                                               ^
in function '__fish_brew_formulae'
       	called on standard input

in command substitution
       	called on standard input
```

**Comment by robsonpeixoto** [comment]
I tried it, but it's very slow. Any sugestion ?
```fish
function __fish_brew_formulae
    find (brew --repository)/Library/Taps -type f -path '*/Formula/*' -name '*.rb' | xargs -n 1 basename | sed 's/.rb$//'
end
```

**Comment by iurii-polishchuk** [comment]
Got the same problem.

**Comment by dunn** [comment]
Is `/usr/local/Cellar/fish/2.3.1/share/fish/completions/brew.fish` provided by us or by Fish?

**Comment by robsonpeixoto** [comment]
The homebrew provide a fish completion? Why not remove the fish completion provided by fish and use the official?
```
❯ ls -l /usr/local/opt/fish/share/fish/completions/brew.fish
-rw-r--r--  1 robinho  admin  16245 Aug 27 13:47 /usr/local/opt/fish/share/fish/completions/brew.fish
```

**Comment by bfontaine** [comment]
@dunn It’s from Fish: https://github.com/fish-shell/fish-shell/blob/master/share/completions/brew.fish

**Comment by dunn** [comment]
OK, then this should probably be filed with the Fish developers.

**Comment by MikeMcQuaid** [comment]
Close out upstream issues that we're not fixing ourselves. @robsonpeixoto please report this to fix itself.

**Comment by floam** [comment]
We fixed it in fish on git master. I'd suggest applying the same fix to the formula for working brew completions for your users: https://github.com/fish-shell/fish-shell/pull/3309
