### ISSUE TITLE
Problem with package libetonyek and liblangtag

### ISSUE THREAD

**Issue by barufa** [Homebrew/homebrew-core#42821]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
It seems that there is a problem with libetonyek and liblangtag. When I run `pkg-config --cflags libetonyek-0.1` it report that liblangtag is not available, and it is requiered by libetonyek-0.1

  I find this error while trying to add libetonyek to Xapain. In particular it fails at configure time (with the macros PKG_CHECK_MODULES).
- What happened (include command output)
```
Brunos-iMac:~ bruno$ pkg-config --cflags libetonyek-0.1
Package liblangtag was not found in the pkg-config search path.
Perhaps you should add the directory containing `liblangtag.pc'
to the PKG_CONFIG_PATH environment variable
Package 'liblangtag', required by 'libetonyek-0.1', not found
```
- What you expected to happen
```
Brunos-iMac:xapian bruno$ pkg-config --cflags libetonyek-0.1
-I/usr/local/Cellar/libetonyek/0.1.9/include/libetonyek-0.1
-I/usr/local/Cellar/librevenge/0.0.4/include/librevenge-0.0
-I/usr/include/libxml2
```
- Step-by-step reproduction instructions (by running `brew install` commands)
1 Be sure that you don't have liblangtag in your system.
2 Run brew install libetonyek
3 Run pkg-config -cflags libetonyek-0.1

Here is the output of `brew config` and `brew doctor`
```
Brunos-iMac:Desktop bruno$ brew config
HOMEBREW_VERSION: 2.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3dab11263c7d3ae568bd585932b393ef526fc5b2
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8fe484e17225333a34f1196039126128f289e8d1
Core tap last commit: 15 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dual-core 64-bit nehalem
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
Brunos-iMac:Desktop bruno$ brew doctor
Your system is ready to brew.
```

And here the output of find (just in case):

```
Brunos-iMac:xapian bruno$ find /usr -name liblangtag*.pc
/usr/local/Cellar/libetonyek/0.1.9/libexec/lib/pkgconfig/liblangtag.pc
/usr/local/lib/pkgconfig/liblangtag.pc
Brunos-iMac:xapian bruno$ find /usr -name liblangtag*.pc
/usr/local/Cellar/libetonyek/0.1.9/libexec/lib/pkgconfig/liblangtag.pc
```

If I run `ln -s /usr/local/Cellar/libetonyek/0.1.9/libexec/lib/pkgconfig/liblangtag.pc /usr/local/lib/pkgconfig/liblangtag.pc`, it seems to make `pkg-config -cflags` work but `PKG_CHECK_MODULES` still fails.

I also find that installing `liblangtag` from source code solves the problem.

I am running `MacOS HighSierra 10.13` in a virtual machine(with Virtual Box).
I was able to reproduce this error on a fresh virtual machine.

**Comment by jonchang** [comment]
Not sure why `liblangtag` is vendored into `libetonyek`'s `libexec`. The pull request that added this was https://github.com/Homebrew/legacy-homebrew/pull/49990. If you'd like to change this please file a pull request

Typically you would set `PKG_CONFIG_PATH=/usr/local/Cellar/libetonyek/0.1.9/libexec/lib/pkgconfig` rather than messing with symlinks like this.

**Comment by jonchang** [comment]
If you'd like to change this please file a pull request. Thanks!
