### ISSUE TITLE
osslsigncode missing libgsf -- msi support broken

### ISSUE THREAD

**Issue by zone117x** [Homebrew/homebrew-core#42859]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Use the `osslsigncode` tool for verifying an `.msi` file -- a common use case. 

- What happened (include command output)

```
brew install osslsigncode
osslsigncode verify myfile.msi 
libgsf is not available, msi support is disabled
Failed
```

- What you expected to happen

The tool to show the validation status of the msi file rather than failing due to missing `libgsf`. 

- Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install osslsigncode
# grab any msi file, can be any valid msi file, for example nodeJS 
curl https://nodejs.org/dist/v10.16.1/node-v10.16.1-x64.msi -o node.msi
# try validate
osslsigncode verify node.msi
> libgsf is not available, msi support is disabled: node.msi
> Failed
```

* `brew gist-logs osslsigncode`: https://gist.github.com/zone117x/bb02ac1d07535fb4e483e005f862632f

#### Notes

* This appears to be a regression of the same bug fixed in https://github.com/Homebrew/legacy-homebrew/pull/26026
* The `libgsf` dependency appears to have been removed from the formula in this commit:
https://github.com/Homebrew/homebrew-core/commit/dabea97708333d84247c1d9ab1f269e38204f699
* Source where gsf is checked: https://github.com/dmcgowan/osslsigncode/blob/04d656da78b7136c3f65f9ba265f39bf8a403a48/osslsigncode.c#L2951
* Other osslsigncode packages with the libgsf dependency:
  * https://www.freshports.org/security/osslsigncode
  * https://github.com/macports/macports-ports/blob/master/devel/osslsigncode/Portfile

**Comment by jonchang** [comment]
Can you please open a pull request for this? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should walk you through the steps and we can help you with any issues you encounter once we see some code. Thanks!
