### ISSUE TITLE
stgit: HEAD does not build when using brew

### ISSUE THREAD

**Issue by royger** [Homebrew/homebrew-core#42902]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/royger/c99615a768ddb23df1a29e51e3db78a0

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Instal stgit HEAD version, to check whether a bug reported to upstream has been fixed.

- What happened (include command output)

Build failed, attached gist show the output.

- What you expected to happen

Build succeeding. Checking out stgit repo and building it outside of homebrew works fine, ie:

$ git clone https://github.com/ctmarinas/stgit.git
$ cd stgit
$ make all

- Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install stgit --HEAD --fetch-HEAD --verbose

**Comment by alebcay** [comment]
It looks like we need to have Git tags available when building from `HEAD`, so something like this would fix the install block on `HEAD`:
```
def install
  # building from head runs "git describe", so have tags available
  system "git", "fetch", "--tags" if build.head?

  ENV["PYTHON"] = "python" # overrides 'python2' built into makefile
  system "make", "prefix=#{prefix}", "all"
  system "make", "prefix=#{prefix}", "install"
end
```
The `HEAD` version of `stgit` seems to depend on GitPython, so tests fail.

**Comment by jonchang** [comment]
@royger we don't provide support for `HEAD` builds, only via pull requests. Please open a pull request if you'd like to see this build fixed. `brew` asks you to file a pull request, not an issue. As you didn't follow those instructions I'm closing this issue.
