### ISSUE TITLE
Error in brew install pango

### ISSUE THREAD

**Issue by marchinidavide** [Homebrew/homebrew-core#42900]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I did run a `brew upgrade` and got strange messages from pango.
Perfomed `brew uninstall pango` and following is output from the subsequent `brew install pango`. Anyone aware of what I should do now or if I did something terribly wrong?

```
==> Downloading https://homebrew.bintray.com/bottles/pango-1.44.3.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "pango"
Download failed: https://homebrew.bintray.com/bottles/pango-1.44.3.mojave.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://download.gnome.org/sources/pango/1.44/pango-1.44.3.tar.xz
Already downloaded: /Users/dm/Library/Caches/Homebrew/downloads/906f2c68a12615afdbfa9795f6e0b7193721540dfd3bb92c9099c7207143bc92--pango-1.44.3.tar.xz
==> meson --prefix=/usr/local/Cellar/pango/1.44.3 -Ddefault_library=both -Dintrospection=true -Duse_fontconfig=true ..
Last 15 lines from /Users/dm/Library/Logs/Homebrew/pango/01.meson:
2019-08-07 15:30:30 +0200

meson
--prefix=/usr/local/Cellar/pango/1.44.3
-Ddefault_library=both
-Dintrospection=true
-Duse_fontconfig=true
..

Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.51.1/libexec/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by marchinidavide** [comment]
Did a `brew post install python` and was able to install pango and get no more errors from running `brew missing`.
Still don't get why I was getting this part of the error:
```
==> Downloading https://homebrew.bintray.com/bottles/pango-1.44.3.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "pango"
```

**Comment by robertleeblairjr** [comment]
This is an issue with bintray serving bottles because it's happening on my computer with other formula. I'm guessing devs for both are aware and resolving the problem.

**Comment by lembacon** [comment]
We've republished those bottles, this issue should have been fixed now. Please try again.
