### ISSUE TITLE
ledger: compile errors on 10.14.5

### ISSUE THREAD

**Issue by IrvinDitz** [Homebrew/homebrew-core#42964]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
I was upgrading installed formulas with `brew upgrade`, among others `boost`, `boost-python` and `ledger` were selected for upgrade, however upgrade of the `ledger` failed.
I have removed all three mentioned formulas with `brew remove`, ran `brew cleanup` and `bre update` and tried to re-install `ledger` with `brew install` all to the same result -- `ledger` is failing to build.

- What happened (include command output)
```
$ brew install ledger
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing dependencies for ledger: boost and boost-python
==> Installing ledger dependency: boost
==> Downloading https://homebrew.bintray.com/bottles/boost-1.70.0.mojave.bottle.tar.gz
Already downloaded: /Users/aid/Library/Caches/Homebrew/downloads/96b91a362ceb5bc9712aaeee55c18fdf4a721269e15394cf33601db7eb73d526--boost-1.70.0.mojave.bottle.tar.gz
==> Pouring boost-1.70.0.mojave.bottle.tar.gz
🍺  /Users/aid/brew/Cellar/boost/1.70.0: 13,983 files, 521.8MB
==> Installing ledger dependency: boost-python
==> Downloading https://homebrew.bintray.com/bottles/boost-python-1.70.0.mojave.bottle.tar.gz
Already downloaded: /Users/aid/Library/Caches/Homebrew/downloads/a1189842bea9afd3664d398530b96931804a9a7076fabd0d62d40587ca615cbe--boost-python-1.70.0.mojave.bottle.tar.gz
==> Pouring boost-python-1.70.0.mojave.bottle.tar.gz
🍺  /Users/aid/brew/Cellar/boost-python/1.70.0: 460 files, 17.7MB
==> Installing ledger
==> Downloading https://github.com/ledger/ledger/archive/v3.1.3.tar.gz
Already downloaded: /Users/aid/Library/Caches/Homebrew/downloads/06b65e6493eb07c0829fd4bfd1f9385aecb509f440660db3f512427ebec8bcf3--ledger-3.1.3.tar.gz
==> ./acprep opt make --jobs=4 --output=build --prefix=/Users/aid/brew/Cellar/ledger/3.1.3_1 --boost=/Users/aid/brew/opt
Last 15 lines from /Users/aid/Library/Logs/Homebrew/ledger/01.acprep:
/Users/aid/brew/include/boost/math/special_functions/math_fwd.hpp:885:9: note: 'isnan' declared here
   bool isnan BOOST_NO_MACRO_EXPAND(T t);
        ^
19 errors generated.
make[2]: *** [src/CMakeFiles/libledger.dir/csv.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
19 errors generated.
make[2]: *** [src/CMakeFiles/libledger.dir/generate.cc.o] Error 1
19 errors generated.
make[2]: *** [src/CMakeFiles/libledger.dir/stats.cc.o] Error 1
19 errors generated.
make[2]: *** [src/CMakeFiles/libledger.dir/convert.cc.o] Error 1
make[1]: *** [src/CMakeFiles/libledger.dir/all] Error 2
make: *** [all] Error 2
acprep: ERROR: Execution failed: make -j4

Do not report this issue to Homebrew/brew or Homebrew/core!
```

- What you expected to happen
`ledger` got build and installed successfully.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install ledger`

**Comment by fxcoudert** [comment]
Being fixed as part of https://github.com/Homebrew/homebrew-core/pull/43661
