### ISSUE TITLE
brew info gives error on upgraded pinned formula

### ISSUE THREAD

**Issue by koallen** [Homebrew/homebrew-core#4301]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~

### Bug reports:

Previously, I pinned `gcc` since I don't wanna upgrade it. Later `r` is upgraded and that forced a upgrade to `gcc` (from `5.3.0` to `6.1.0`). Just now I was trying to run `brew info gcc`, and I get an error saying `Error: /usr/local/Cellar/gcc/5.3.0 is not a directory`. This is similar to Homebrew/legacy-homebrew#46044.

I have to manually do `brew unpin gcc` and `brew pin gcc` so that I can get the correct info.

Is there some logical error in handling `brew info` with pinned packages?

**Comment by ilovezfs** [comment]
I cannot reproduce this issue:
https://gist.github.com/ilovezfs/84e9d7118576d73b8b1efcd29981f2ac

**Comment by ilovezfs** [comment]
Ah I can!
```
iMac-TMP:homebrew-core joe$ brew cleanup -n gcc
Would remove: /usr/local/Cellar/gcc/5.3.0 (1,390 files, 254.8M)
==> This operation would free approximately 254.8M of disk space.
iMac-TMP:homebrew-core joe$ brew cleanup gcc
Removing: /usr/local/Cellar/gcc/5.3.0... (1,390 files, 254.8M)
==> This operation has freed approximately 254.8M of disk space.
iMac-TMP:homebrew-core joe$ brew list --pinned
gcc
iMac-TMP:homebrew-core joe$ brew info gcc
Error: /usr/local/Cellar/gcc/5.3.0 is not a directory
```
You ran brew cleanup :)
That is a :bug: indeed, but one for Homebrew/brew https://github.com/Homebrew/brew

**Comment by koallen** [comment]
I was about to say that I ran `brew cleanup` and that might be the cause of the error.

Sorry for posting to the wrong repo. After `brew` changed the repo names, I mis-interpreted `homebrew-core` as the package manager. So should I create an issue there? (at `brew`)

Again, sorry about that!

**Comment by ilovezfs** [comment]
@koallen no need to apologize. yes it would be helpful if you closed this & reopened in the brew repo.

**Comment by koallen** [comment]
Opened an issue at `Homebrew/brew`, closing this now.
