### ISSUE TITLE
_ftp user not integrated into pure-ftpd, proftpd

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#43027]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (`brew gist-logs pure-ftpd` and `brew gist-logs proftpd` both error)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```console
$ brew config
HOMEBREW_VERSION: 2.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3dab11263c7d3ae568bd585932b393ef526fc5b2
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 2548c98c55c734edbadba1ccdc5fadad34babdef
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.19.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

To help us debug your issue please explain:

- What you were trying to do (and why)

Install and run an FTP server.

- What happened (include command output)

Both pure-ftpd and proftpd require a lot of manual configuration before they work, especially with anonymous default FTP client connections.

- What you expected to happen

I expected the Homebrew default configurations for pure-ftpd and proftpd to automatically integrate with a default macOS [_]ftp UNIX account.

- Step-by-step reproduction instructions (by running `brew install` commands)

1. Install pure-ftpd or proftpd.
2. Run `brew services start <pure-ftpd|proftpd>`
3. `lftp localhost -e 'ls;quit'`

Instead of a directory listing for anonymous FTP user chroot, I get connection timeouts.

**Comment by iMichka** [comment]
Hi. Nobody has picked up this issue since Aug 11.

This may be a homebrew bug. This may be an upstream bug. This may be a configuration issue on your side. Who knows ... but it looks like nobody picked this issue up.

> Both pure-ftpd and proftpd require a lot of manual configuration before they work

It would be great if somebody could setup the right configuration in the formula.

I will close this issue, pull requests are welcome to improve the situation.
