### ISSUE TITLE
vsftpd missing secure_chroot_dir

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#43026]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (`$ brew gist-logs vsftpd` => `Error: No logs.`)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Run vsftpd

- What happened (include command output)

```console
$ brew info vsftpd
vsftpd: stable 3.0.3 (bottled)
Secure FTP server for UNIX
https://security.appspot.com/vsftpd.html
/usr/local/Cellar/vsftpd/3.0.3 (13 files, 260.0KB) *
  Poured from bottle on 2019-08-11 at 09:09:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vsftpd.rb
==> Caveats
To use chroot, vsftpd requires root privileges, so you will need to run
`sudo vsftpd`.
You should be certain that you trust any software you grant root privileges.

The vsftpd.conf file must be owned by root or vsftpd will refuse to start:
  sudo chown root /usr/local/etc/vsftpd.conf

To have launchd start vsftpd now and restart at startup:
  sudo brew services start vsftpd
Or, if you don't want/need a background service you can just run:
  sudo vsftpd
==> Analytics
install: 266 (30 days), 808 (90 days), 3,610 (365 days)
install_on_request: 267 (30 days), 804 (90 days), 3,593 (365 days)
build_error: 0 (30 days)

$ sudo brew services start vsftpd
==> Successfully started `vsftpd` (label: homebrew.mxcl.vsftpd)

~$ lftp localhost -e 'ls; quit'
`ls' at 0 [500 OOPS: vsftpd: not found: directory given in 'secure_chroot_dir':/usr/share/empty]
```

- What you expected to happen

An FTP client such as lftp would be able to connect to vsftpd.

**Comment by iMichka** [comment]
Hi. Nobody has picked up this issue since Aug 11.

This may be a homebrew bug. This may be an upstream bug. This may be a configuration issue on your side. Who knows ... but it looks like nobody picked this issue up.

The only thing I can see is that the formula contains something like
```
    # make install has all the paths hardcoded; this is easier:
    sbin.install "vsftpd"
    etc.install "vsftpd.conf"
    man5.install "vsftpd.conf.5"
    man8.install "vsftpd.8"
```

This is quite ... dirty. There should be a proper `make install` step provided by upstream, which properly setups everything. Any other solution is only hacking around and not really robust.

I will close this issue, pull request are welcome to improve the situation.
