### ISSUE TITLE
clisp: no package lock error in REPL / warning in command line

### ISSUE THREAD

**Issue by sam-s** [Homebrew/homebrew-core#43043]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs clisp
Error: No logs.
```

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 925ec737fba1db97d0170c56de982900711cacd3
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c7c5f3c5bd7fbb333e8143ae5953cbdf067e7946
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: /usr/bin/vim
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1
macOS: 10.14.6-x86_64
CLT: 11.0.0.0.1.1559496560
Xcode: 10.3
CLT headers: 11.0.0.0.1.1559496560
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
$
```

To help us debug your issue please explain:

- What you were trying to do (and why)

[Define a function named with an ANSI CL symbol.](https://stackoverflow.com/q/57454517/850781)

- What happened (include command output)

```
$ clisp -q -norc -x '(defun class () 42)'
CLASS
$
```

alternatively:
```
$ clisp -q -norc
> (defun class () 42)
CLASS
> (quit)
$
```

- What you expected to happen

When I build clisp from sources myself, it works correctly:
```
$ ./clisp -q -norc -x '(defun class () 42)'
WARNING: DEFUN/DEFMACRO(CLASS): #<PACKAGE CLOS> is locked
         Ignore the lock and proceed
CLASS
$
```
(same on clisp distributed with ubuntu).

alternatively:
```
$ ./clisp -q -norc
[1]> (defun class () 42)

** - Continuable Error
DEFUN/DEFMACRO(CLASS): #<PACKAGE CLOS> is locked
If you continue (by typing 'continue'): Ignore the lock and proceed
The following restarts are also available:
ABORT          :R1      Abort main loop
Break 1 [2]> (quit)
$
```

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install clisp
$ clisp -q -norc -x '(defun class () 42)'
```

**Comment by bhaible** [comment]
What is `clisp --version` in the version built by Homebrew, and what is `clisp --version` in the version you built yourself, from source?

**Comment by sam-s** [comment]
git head:
```
$ ./clisp --version
GNU CLISP 2.49.93+ (2018-02-18) (built 3770997114) (memory 3770997755)
Software: GNU C 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.20.17) 
gcc -W -Wswitch -Wcomment -Wpointer-arith -Wreturn-type -Wmissing-declarations -Wimplicit -Wno-sign-compare -Wno-format-nonliteral -Wno-shift-negative-value -O -fwrapv -fno-strict-aliasing -DUNIX_BINARY_DISTRIB -DNO_ASM -DENABLE_UNICODE -DDYNAMIC_FFI -DDYNAMIC_MODULES -DNO_GETTEXT  libgnu.a -L/usr/local/opt/readline/lib -lreadline -lncurses -L/Users/sam.steingold/src/top/lib -lffcall -liconv -L/usr/local/lib -lsigsegv -L/usr/local/lib -lunistring  
SAFETY=0 TYPECODES WIDE_HARD GENERATIONAL_GC SPVW_BLOCKS SPVW_PURE SINGLEMAP_MEMORY
libsigsegv 2.12
libiconv 1.11
libreadline 8.0
libffcall 2.1
Features: (READLINE REGEXP WILDCARD SYSCALLS I18N LOOP COMPILER CLOS MOP CLISP ANSI-CL COMMON-LISP LISP=CL INTERPRETER LOGICAL-PATHNAMES SOCKETS GENERIC-STREAMS SCREEN FFI UNICODE BASE-CHAR=CHARACTER WORD-SIZE=64 UNIX MACOS)
C Modules: (clisp i18n syscalls regexp readline)
Installation directory: /Users/sam.steingold/src/clisp/gitlab/build-O/
User language: ENGLISH
Machine: X86_64 (X86_64) BZ-C02XR5CGJG5L
```
homebrew:
```
$ clisp --version
GNU CLISP 2.49 (2010-07-07) (built on mojave-2.local [10.88.172.143])
Software: GNU C 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5) 
clang -m64 -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -O -DUNIX_BINARY_DISTRIB -DENABLE_UNICODE -DDYNAMIC_MODULES -DNO_GETTEXT -I.   -lreadline -lncurses  -liconv -lsigsegv libgnu_cl.a -L/usr/X11/lib
SAFETY=0 HEAPCODES STANDARD_HEAPCODES WIDE_HARD GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.12
libiconv 1.11
libreadline 8.0
Features: (REGEXP SYSCALLS I18N LOOP COMPILER CLOS MOP CLISP ANSI-CL COMMON-LISP LISP=CL INTERPRETER SOCKETS GENERIC-STREAMS LOGICAL-PATHNAMES SCREEN UNICODE BASE-CHAR=CHARACTER WORD-SIZE=64 UNIX MACOS)
C Modules: (clisp i18n syscalls regexp)
Installation directory: /usr/local/Cellar/clisp/2.49_2/lib/clisp-2.49/
User language: ENGLISH
Machine: X86_64 (X86_64) BZ-C02XR5CGJG5L
```

**Comment by bhaible** [comment]
In other words, you are requesting that Homebrew upgrades its clisp version to one that includes the fix of https://sourceforge.net/p/clisp/bugs/701/ .

That would be either git head https://gitlab.com/gnu-clisp/clisp or the latest prerelease https://haible.de/bruno/gnu/clisp-2.49.92.tar.bz2 .

**Comment by SMillerDev** [comment]
Homebrew doesn't ship pre-release software. Your best option is to make a pull request as soon as the main release is out.

**Comment by iMichka** [comment]
Upstream needs to tag a release. Or you could try to submit the patch with the fix to homebrew, until there is a new release. That's all we can do on our side. The bug is in `clisp` initially, not in homebrew.
