### ISSUE TITLE
mosh --HEAD fails patch step

### ISSUE THREAD

**Issue by sbromberger** [Homebrew/homebrew-core#43078]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
`brew install mosh --HEAD` fails with a patch error.
- What happened (include command output)
```
seth@snoopy:~/scripts$ brew install mosh --HEAD
==> Cloning https://github.com/mobile-shell/mosh.git
Updating /Users/seth/Library/Caches/Homebrew/mosh--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at b1da700 Fix Appveyor build.
==> Downloading https://github.com/mobile-shell/mosh/commit/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch?full_index=1
Already downloaded: /Users/seth/Library/Caches/Homebrew/downloads/77f892463b3ff68493dd24ebe65bf0939c63382ae00bc1b036be6b9941aca9dd--e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch
==> Patching
==> Applying e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch
patching file src/network/network.cc
Hunk #1 FAILED at 332.
1 out of 1 hunk FAILED -- saving rejects to file src/network/network.cc.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/mosh--patch-20190813-20334-18flrsj/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0.patch` exited with 1.
```

- What you expected to happen
mosh to be installed.
- Step-by-step reproduction instructions (by running `brew install` commands)
see above.

Brew config:
```
seth@snoopy:~/Library/Caches/Homebrew/downloads$ brew config
HOMEBREW_VERSION: 2.1.10-4-gfe954c7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: fe954c76d5537ec5d52518b9c033b2b3a37df55c
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b7d38f247d646975d6186b005729a1343ad96e21
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
```

**Comment by SMillerDev** [comment]
Maybe the patch is already part of upstreams master branch. Either way, you'll have to make a pull request yourself because HEAD installs aren't actively supported since they're a moving target.

**Comment by fxcoudert** [comment]
We welcome a pull request to fix this, but maintainers do not have the people-power to actually fix these issues ourselves.
