### ISSUE TITLE
postgresql post_install step keeps failing in Sierra and High Sierra CI

### ISSUE THREAD

**Issue by alebcay** [Homebrew/homebrew-core#43142]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Attempted to update formulae, some of which are depended upon by other formulae that also specify `postgresql` as a dependency

- What happened (include command output)
CI fails on Sierra/High Sierra with the following error:
```
==> Pouring postgresql-11.4.high_sierra.bottle.tar.gz
==> /usr/local/Cellar/postgresql/11.4/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgres
Last 150 lines from /Users/brew/Jenkins/workspace/core/logs/postgresql/post_install.01.initdb:
2019-08-15 09:03:43 +0100

/usr/local/Cellar/postgresql/11.4/bin/initdb
--locale=C
-E
UTF-8
/usr/local/var/postgres

The files belonging to this database system will be owned by user "brew".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/postgres ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default timezone ... Europe/London
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... 2019-08-15 09:03:43.775 BST [19573] FATAL:  could not create shared memory segment: No space left on device
2019-08-15 09:03:43.775 BST [19573] DETAIL:  Failed system call was shmget(key=5432001, size=56, 03600).
2019-08-15 09:03:43.775 BST [19573] HINT:  This error does *not* mean that you have run out of disk space.  It occurs either if all available shared memory IDs have been taken, in which case you need to raise the SHMMNI parameter in your kernel, or because the system's overall limit for shared memory has been reached.
	The PostgreSQL documentation contains more information about shared memory configuration.
child process exited with exit code 1
initdb: removing contents of data directory "/usr/local/var/postgres"
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall postgresql`
```
- What you expected to happen
Successful post-install of `postgresql`.
- Step-by-step reproduction instructions (by running `brew install` commands)
As a simple example, `brew install --only-dependencies mapnik` (on Sierra or High Sierra). Since I'm on Mojave and this issue is specifically happening in the CI, I'm not really sure how reproducible this is.

---

This issue is blocking some merge requests (causing CI failures). I'll try to keep this list up-to-date.
- #42383
- #42462
- #42531
- #42846
- #42971
- #43101
- #43205 

This issue has also appeared in some pull requests, but somehow been resolved. I've tried looking at them but have not figured out how the issue in question was resolved. Maybe it's just luck, but I've tried some rebuilds and I haven't gotten any of the blocked PRs to fix themselves.
- #42453
- #42559

**Comment by scpeters** [comment]
I just rebooted the VM's in bot.brew.sh and I think the shared memory issue should be resolved.

**Comment by alebcay** [comment]
I will try rerunning a few of these PR tests and hopefully everything is good to go.
