### ISSUE TITLE
findutils causes problems with Google's Flutter framework 

### ISSUE THREAD

**Issue by rowild** [Homebrew/homebrew-core#43292]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

For those, who work with Flutter, be aware that some flutter commands do not work well, when "findutils" is installed; you will most likely encounter a "find: invalid mode '+100'" error. The following describes the problem, when switching channels in order to test the desktop functionality of Flutter.

- What you were trying to do (and why)
Switch to Flutter's "master" channel in order to test the new "Desktop" features. The documentations says, it is required to switch to "master channel" and run a "flutter update"

- What happened (include command output)
"flutter channel master" will start downloading, but result in a "find: invalid mode '+100'"
So will any subsequent flutter commands like "flutter doctor", "flutter updates" etc.

- What you expected to happen
Regular download; flutter's regular command line feedbacks on "flutter doctor" etc...)

- Step-by-step reproduction instructions (by running brew install commands)
1. Install flutter (see https://flutter.dev/docs/get-started/install/macos)
2. Run "flutter channel master"
3. Watch the command line feedback

- Solution
Uninstall "findutils": "brew uninstall findutils"

Issue reported on Stackoverflow:
https://stackoverflow.com/questions/55663577/flutter-cannot-switch-channel

**Comment by jonchang** [comment]
`findutils` by default installs its replacement `find` command as `gfind`. So unless you forced the linking of these replacement commands as `find` this issue typically shouldn't come up.

```
$ brew info findutils
[...]
==> Caveats
All commands have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
```

If you run a non-standard setup (e.g., using GNU replacements for BSD tools) it shouldn't surprise you when other tools break. This isn't an issue with Homebrew (since we don't package `flutter`).

**Comment by SMillerDev** [comment]
That's not a homebrew issue though. It's a flutter issue

**Comment by rowild** [comment]
Quite right, but in case people are looking for issues, I thought I mention it here...

**Comment by rowild** [comment]
@jonchang I didn't do any weird setup as you describe, just the normal out-of-the-box one.

You guys should respect the fact that there could be troubles arising and investigate a bit more instead of just shooting back "It is not a findutils problem" and closing the issue... too often reactions like these proofed wrong...

**Comment by rowild** [comment]
And besides - just for the sake of a respectful work together: you make is such a hussle to report something compared to other platforms (which can be even bigger), that an immediate closedown like this one makes me rethink if I ever post anything again. Your quick shoot-outs are not very respectful to those who participate - which is, what you tell people to do, or at least can do. But all YOU do is playing gods. Not good.

**Comment by SMillerDev** [comment]
> investigate a bit more 

If you update something that isn't in homebrew and that suddenly breaks afterwards, what are the other possible causes than "it's in the part that changed"?

> you make is such a hussle to report something compared to other platforms (which can be even bigger)

That might be true, but the size of the platform doesn't really determine the requirements for the people involved. Oftentimes bigger platforms are backed by companies, making the people working on it employees. Homebrew has made decisions geared towards wasting as little time of the volunteers as possible. That might end up with some false positives, but from what I saw in the closed issues you made you simply ignored the text that said "use the template or the issue will be closed" and got the issue autoclosed by the bot.

**Comment by jonchang** [comment]
I did consider your issue thoughtfully, since this error message implies that `flutter` is calling `find` and not `gfind`. I would appreciate it if you didn't accuse me (and other volunteer maintainers) of being dismissive of your problem.

>     * "flutter channel master" will start downloading, but result in a "find: invalid mode '+100'"

```console
$ /usr/bin/find /dev/null -perm +100
[returns successfully]
$ gfind /dev/null -perm +100
gfind: invalid mode ‘+100’
```
