### ISSUE TITLE
brew install --HEAD get_iplayer fails because the formula specifies a non-existing branch

### ISSUE THREAD

**Issue by madrobby** [Homebrew/homebrew-core#43330]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

The formula specifies the `develop` branch for the HEAD option but this branch doesn’t exist in the `get_iplayer` repository.

```
==> Cloning https://github.com/get-iplayer/get_iplayer.git
Cloning into '/Users/thomasfuchs/Library/Caches/Homebrew/get_iplayer--git'...
warning: Could not find remote branch develop to clone.
fatal: Remote branch develop not found in upstream origin
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "get_iplayer"
Failure while executing; `git clone --depth 1 --branch develop https://github.com/get-iplayer/get_iplayer.git /Users/thomasfuchs/Library/Caches/Homebrew/get_iplayer--git` exited with 128. Here's the output:
Cloning into '/Users/thomasfuchs/Library/Caches/Homebrew/get_iplayer--git'...
warning: Could not find remote branch develop to clone.
fatal: Remote branch develop not found in upstream origin
```

**Comment by jonchang** [comment]
We don't support `HEAD` builds in homebrew-core, but would review a pull request that addresses this issue. Could you please [open a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) making the fix? Thanks!
