### ISSUE TITLE
Vtk build fails to work

### ISSUE THREAD

**Issue by rambalachandran** [Homebrew/homebrew-core#4337]
I installed vtk in Mac 10.10.5 with homebrew. These are the steps that I followed for installation
```
brew update
brew doctor
brew install --with-icu --build-from-source boost
brew install --with-python --with-qt vtk
```

However when I try to start python and do `import vtk` it fails with an error that says
```
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
```
I ran gist-logs for the last step and it is located in the following location [https://gist.github.com/20e2f5181f2601a7aafa13aa83286e13]

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#4165
