### ISSUE TITLE
gnuplot fails to work with the term pdfcairo

### ISSUE THREAD

**Issue by gaochenyi** [Homebrew/homebrew-core#43396]
## Checklist

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software.
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS?
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>`
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Issue

- What you were trying to do (and why)
  - I am using the bottled `gnuplot` with the term `pdfcairo`.
- What happened (include command output)
  - It works well with the term `pdfcairo` before. But it fails to do so today.
- What you expected to happen
  - `gnuplot` works well with `pdfcairo` like before.
  - `gnuplot` works eight days ago. It seems to be broken after a `brew cleanup`.
- Step-by-step reproduction instructions (by running `brew install` commands)

```shell
brew install cairo pango gnuplot
```

package  | version |
---------|---------|
 cairo   | 1.16.0 (bottled), HEAD |
 pango   | 1.44.5 (bottled), HEAD |
 gnuplot |  5.2.7 (bottled), HEAD |

```gnuplot
# script for gnuplot
set term pdfcairo
set output 'test.pdf'
test
set output
```

Then with the above script gnuplot is expected to produce a PDF file which looks like

![test](https://user-images.githubusercontent.com/32761974/63587799-6edb0a00-c5d7-11e9-84a3-dbf592dddaf1.png)

But it actually looks like

![test pdf](https://user-images.githubusercontent.com/32761974/63587863-a0ec6c00-c5d7-11e9-8120-464666e003c2.png)

```shell
$ brew config
HOMEBREW_VERSION: 2.1.10-52-g4822241
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4822241d6fd7de1a4ee04a9f39058410e61203a5
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 82495eedd0e6c274ac47d40f1feb1fa004f427b4
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.1
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: 8.3.3 => /Applications/Xcode8.app/Contents/Developer
XQuartz: 2.7.11 => /opt/X11
```

## Update

`pango` seems to be blamed. After switching to an old version of `pango`, `gnuplot` works with `pdfcairo` as expected.

The hint is from [an issue in legacy-homebrew](https://github.com/Homebrew/legacy-homebrew/issues/11901)

**Comment by jonchang** [comment]
In that case, I think this would be a good issue to [raise upstream with the pango developers](https://gitlab.gnome.org/GNOME/pango/issues). One possible route is to identify the problematic change with `git bisect`, if you have the time for that.

**Comment by fxcoudert** [comment]
It really sounds like a pango bug. Closing here, unless there is evidence that this is specific to Homebrew.

**Comment by plessl** [comment]
pdfcairo is still broken on macOS Catalina.

Did someone find a workaround how to install a correctly working pango/gnuplot combination with homebrew? Using the HEAD versions doesn't help and older versions of pango are no longer available in Homebrew.

**Comment by tautomer** [comment]
> It really sounds like a pango bug. Closing here, unless there is evidence that this is specific to Homebrew.

It is indeed [a pango problem](https://gitlab.gnome.org/GNOME/pango/issues/422). Reverting pango to 1.43 will solve the problem, but pango@1.43 isn't available from brew any more unfortunately.

Possible to bring it back for the time being? It took me a whole morning to figure out how to compile it maunally.

> pdfcairo is still broken on macOS Catalina.
> 
> Did someone find a workaround how to install a correctly working pango/gnuplot combination with homebrew? Using the HEAD versions doesn't help and older versions of pango are no longer available in Homebrew.

Install meson and ninja, `brew install meson ninja`.

Download and extract [pango 1.43](https://download.gnome.org/sources/pango/1.43).

Go to `pango-1.43.0`, run 

```shell
meson --prefix=/usr/local/Cellar/pango/1.43.0 -Ddefault_library=both -Dintrospection=true -Duse_fontconfig=true ..
```

This will create a whole lot of files in the parent folder, so you would better put `pango-1.43.0` in some sort of temp or junk folder.

Go back to the parent folder, run `ninja && ninja install`. 

Then switch to 1.43 with `brew switch pango 1.43` and re-install gnuplot `brew reinstall gnuplot`.

**Comment by karplus** [comment]
Tautomer's advice did not help, as ninja failed, with a bunch of error messages.

It looks like brew is no longer an acceptable way to install gnuplot, because the homebrew cannot maintain a consistent set of versions of packages that work together, rather defeating the purpose of having an installer system.

**Comment by fxcoudert** [comment]
If you want to help, you can report the issue to the Pango developers so they can fix it. Everything else is just words but not useful to fixing the issue.
