### ISSUE TITLE
OpenCV 3.4.5_1 depends on libopenblasp-r0.3.5.dylib rather than libopenblasp-r0.3.7.dylib

### ISSUE THREAD

**Issue by hoonkai** [Homebrew/homebrew-core#43424]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install OpenCV 3.4.5 using `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/42abf2c5fa00318e2bffca6afa2455a61ba63d8f/Formula/opencv.rb` with line `needs :cxx11` removed.
- What happened (include command output)
The install completes, but the resulting `/usr/local/opt/opencv/lib/libopencv_core.3.4.dylib` depends on `usr/local/opt/openblas/lib/libopenblasp-r0.3.5.dylib` rather than the latest `usr/local/opt/openblas/lib/libopenblasp-r0.3.7.dylib` which `brew` installs as a dependency.

```
brew reinstall /Volumes/Data/Projects/homebrew-core/Formula/opencv.rb
==> Reinstalling opencv
Warning: opencv 4.1.0_3 is available and more recent than version 3.4.5_1.
==> Installing dependencies for opencv: openblas
==> Installing opencv dependency: openblas
==> Downloading https://homebrew.bintray.com/bottles/openblas-0.3.7.high_sierra.bottle.tar.gz
Already downloaded: /Users/mchan/Library/Caches/Homebrew/downloads/1bbbe8d5bf40f969531e12c9c4127d9fc3ab1acc3cade8802b2be7c3239fc593--openblas-0.3.7.high_sierra.bottle.tar.gz
==> Pouring openblas-0.3.7.high_sierra.bottle.tar.gz
==> Caveats
openblas is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BLAS and LAPACK in the Accelerate framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/usr/local/opt/openblas/lib"
  export CPPFLAGS="-I/usr/local/opt/openblas/include"

For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openblas/0.3.7: 22 files, 120.5MB
==> Installing opencv
==> Downloading https://homebrew.bintray.com/bottles/opencv-3.4.5_1.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d8/d8b90363d87d13279244a656d925460a180279c0adba63ac8f3b5d5025af7797?__gda__=exp=1566
######################################################################## 100.0%
==> Pouring opencv-3.4.5_1.high_sierra.bottle.tar.gz
Warning: opencv dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/opencv/3.4.5_1: 635 files, 239.2MB
Removing: /Users/mchan/Library/Caches/Homebrew/opencv--3.4.5_1.high_sierra.bottle.tar.gz... (85.2MB)
==> Caveats
==> openblas
openblas is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BLAS and LAPACK in the Accelerate framework.

For compilers to find openblas you may need to set:
  export LDFLAGS="-L/usr/local/opt/openblas/lib"
  export CPPFLAGS="-I/usr/local/opt/openblas/include"

For pkg-config to find openblas you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig"
```
- What you expected to happen
`libopencv_core.3.4.dylib` should depend on `libopenblasp-r0.3.7.dylib` which `brew` installs.
- Step-by-step reproduction instructions (by running `brew install` commands)
1) Checkout `42abf2c5fa00318e2bffca6afa2455a61ba63d8f`
2) Remove or comment out line containing `needs :cxx11` in `Formula/opencv.rb`
3) Run `brew install /path/homebrew-core/Formula/opencv.rb`
4) Run `vi /usr/local/opt/opencv/lib/libopencv_core.3.4.dylib` and search for `openblas`. You will find the occurrence `/usr/local/opt/openblas/lib/libopenblasp-r0.3.5.dylib`.

**Comment by jonchang** [comment]
> Install OpenCV 3.4.5 using `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/42abf2c5fa00318e2bffca6afa2455a61ba63d8f/Formula/opencv.rb` with line `needs :cxx11` removed.

Thanks for the report, but unfortunately we don't support this use case. Attempting to do so regardless will ask you to use `brew extract` instead.
