### ISSUE TITLE
sqlmap now supports python3.x

### ISSUE THREAD

**Issue by JayceCao** [Homebrew/homebrew-core#43458]
Since sqlmap now supports python3.x, will we remove the python@2 dependency of sqlmap?  
From sqlmap's project:
```
sqlmap works out of the box with Python version 2.6, 2.7 and 3.x on any platform.
```

**Comment by jonchang** [comment]
Hi @JayceCao please open a pull request for this change. [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) will help you get started and we would be happy to help you through any issues that you encounter after the pull request has been opened.
