### ISSUE TITLE
rclone package has problems with bash completion

### ISSUE THREAD

**Issue by marco-brandizi** [Homebrew/homebrew-core#43506]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?

- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?

**[This](https://github.com/Homebrew/homebrew-core/files/3545361/brew-doctor.txt) is what I got from `brew doctor`**

- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

**Yields this**:

```bash
10:20:09 [admin@brandizmac ~]$ brew gist-logs rclone
Error: No logs.
10:20:37 [admin@brandizmac ~]$
```

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**[This](https://github.com/Homebrew/homebrew-core/files/3545339/brew-config.txt) is what I got from `brew config`**.

To help us debug your issue please explain:

- What you were trying to do (and why)

**I've installed rclone and everything works fine except...**

- What happened (include command output)

**...that, when I login as root (`su - root`) I get an error from the bash completion integration script**:

```bash
10:20:15 [brandizi@brandizmac ~]$ su - root
Password:
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: syntax error near unexpected token `<'
-sh: /usr/local/etc/bash_completion.d/rclone: line 266: `            done < <(command rclone listremotes)'
10:20:18 [root@brandizmac ~]#
```

Note that this happens for the root user only. I tried to see if it is missing something from the PATH, or file permissions, but no luck.

- What you expected to happen

**No complaints and bash completion working for rclone (works for other users)**

- Step-by-step reproduction instructions (by running `brew install` commands)

  1. `brew install rclone`
  1. `sudo - root`
  1. It gives me the error above.

**Comment by SMillerDev** [comment]
Have you tried reporting this upstream?

**Comment by marco-brandizi** [comment]
Hi @SMillerDev. Sorry, I'm pretty new to the organisation of Home Brew, what do you mean, upstream? I came up to this repo following the URL reported by `brew info rclone`.

**Comment by SMillerDev** [comment]
I mean the rclone project themselves. Homebrew only packages the software.

**Comment by marco-brandizi** [comment]
@SMillerDev, sorry, I believed the bash completion work is made/maintained by Home Brew packagers, I didn't know rclone has a command to generate the file at issue.

I've [filed this same issue](https://github.com/rclone/rclone/issues/3489) to them now, sorry for the confusion.
