### ISSUE TITLE
Reinstalling with fewer options still builds with the omitted options

### ISSUE THREAD

**Issue by oguzserbetci** [Homebrew/homebrew-core#43514]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> [brew gist-logs emacs-plus](https://gist.github.com/ab3801ab7f2b8cbaf01cc62975ac3bed)
> [brew gist-logs universal-ctags](https://gist.github.com/3c5aa5b7449cc8d1c2a5536aae395ddb)
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
I was trying to reinstall a package with some install options removed. First I installed emacs-plus with 3 options and then reinstalled it with only 2 of those options.
```
brew install emacs-plus --with-no-frame-refocus --without-spacemacs-icon --with-no-titlebar 
brew reinstall emacs-plus --with-no-frame-refocus --without-spacemacs-icon
```
- What happened (include command output)
Reinstall still used the `--with-no-titlebar` option.

- What you expected to happen
Reinstall not using the `--with-no-titlebar` option.
- Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install emacs-plus --with-no-frame-refocus --without-spacemacs-icon --with-no-titlebar 
brew reinstall emacs-plus --with-no-frame-refocus --without-spacemacs-icon
```

**Comment by oguzserbetci** [comment]
I reproduced this with removing and installing `universal-ctags` with `brew install --HEAD universal-ctags --with-jansson --with-libyaml` and then ` brew reinstall --HEAD universal-ctags --with-libyaml`.

To check whether brew actually used the omitted options I ran `ctags --list-features`. The output included json support which means that brew reinstalled with the omitted options.

**Comment by SMillerDev** [comment]
Yes, reinstall doesn't change the install parameters. It simply installs again.

**Comment by oguzserbetci** [comment]
Oh, yes I just had a look at the man page and it is mentioned there. Sorry to bother.
