### ISSUE TITLE
Imagemagick formulae needs to be updated

### ISSUE THREAD

**Issue by michaeljohnsargent** [Homebrew/homebrew-core#4354]
I'm having an issue with the current link to imagemagick - "404 Not Found"

```brew` install imagemagick --with-jasper 08-30-16 10:34:49 ==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.5-7.tar.xz```

```curl: (28) Connection timed out after 5338 milliseconds Trying a mirror... ==> Downloading https://www.imagemagick.org/download/ImageMagick-6.9.5-7.tar.xz```

```curl: (22) The requested URL returned error: 404 Not Found Error: Failed to download resource "imagemagick" Download failed: https://www.imagemagick.org/download/ImageMagick-6.9.5-7.tar.xz```

Can someone assist?

**Comment by ilovezfs** [comment]
any chance you're behind a firewall, vpn, proxy server, etc. etc.?

**Comment by michaeljohnsargent** [comment]
No. Straight through ISP.

Michael

Michael Sargent
Software Engineer
LinkedIn - http://www.linkedin.com/in/michaeljohnsargent
Cell - 843.323.7418

**Comment by michaeljohnsargent** [comment]
ImageMagick-6.9.5-7.tar.xz is not listed on https://www.imagemagick.org/download/

**Comment by ilovezfs** [comment]
is the bintray link working if u put it in the browser? https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.5-7.tar.xz

**Comment by michaeljohnsargent** [comment]
Yes. It does work. Thanks.
Is there a way to install the file locally using brew?

**Comment by ilovezfs** [comment]
can you try brew updating first
```
Warning: imagemagick-6.9.5-8 already installed
```

you're a version behind

**Comment by michaeljohnsargent** [comment]
I ran `cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update` 
and then tried `brew install imagemagick --with-jasper` again. All is well thank you for being so responsive!

**Comment by ilovezfs** [comment]
@michaeljohnsargent you probably were bitten by https://twitter.com/MacHomebrew/status/763686348041641984

and you're welcome!
