### ISSUE TITLE
clisp installation does not include "full"

### ISSUE THREAD

**Issue by benknoble** [Homebrew/homebrew-core#43569]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/27e3ac9a7cc95c62944d7e67814460d8

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Install `clisp`, and load external modules (e.g., those found in `full`).

- What happened (include command output)

```bash
# clisp -K full
clisp: /usr/local/Cellar/clisp/2.49_2/lib/clisp-2.49/full/lisp.run: No such file or directory
# clisp -q -norc -x "(require 'pcre)"
*** - LOAD: A file with name PCRE does not exist
```

- What you expected to happen

The `full` linkset should be there, and loading a module should work.

- Step-by-step reproduction instructions (by running `brew install` commands)

```bash
# brew install clisp
## run any of the above commands
# ls "$(brew --prefix)"/Cellar/clisp/2.49_2/lib/clisp-2.49/
base/
build-aux/
data/
linkkit/
## notice that base is present, but full is not
```

**Comment by fxcoudert** [comment]
We basically install `clisp` by downloading the source and running `configure && make`, so if the “full packages” are not present as part of `clisp` itself, we're not distributing them indeed. The project does not look actively maintained, since there was no release since 2010.

We would welcome a pull request if you know how to install these packages as part of the formula, and you think they would be useful for the majority of clisp users.

**Comment by benknoble** [comment]
Not so: this mirror has commits as recent as July 2019: https://github.com/lisp-mirror/clisp ?

**Comment by benknoble** [comment]
I've given up; this is harder than it should be. Unfortunately, SBCL (recent updates) has no readline support, so I'm stuck with clisp for now.
