### ISSUE TITLE
V8 with --with-readline not building

### ISSUE THREAD

**Issue by fmccabe** [Homebrew/homebrew-core#4356]
# Please follow the general troubleshooting steps first:
- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

Tried to install v8 with readline. 
I ran

> brew install v8 --with-readline

I get C++ compiler errors:
.././src/ia32/assembler-ia32-inl.h:343:8: error: cast from pointer to smaller type 'int32_t' (aka 'int') loses information
  x_ = reinterpret_cast<int32_t>(x);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
.././src/ia32/assembler-ia32-inl.h:348:8: error: cast from pointer to smaller type 'int32_t' (aka 'int') loses information
  x_ = reinterpret_cast<int32_t>(ext.address());
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.././src/ia32/assembler-ia32-inl.h:354:8: error: cast from pointer to smaller type 'int32_t' (aka 'int') loses information
  x_ = reinterpret_cast<int32_t>(internal_offset);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.././src/ia32/assembler-ia32-inl.h:382:8: error: cast from pointer to smaller type 'int32_t' (aka 'int') loses information
  x_ = reinterpret_cast<int32_t>(addr);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by fmccabe** [comment]
I tried to run brew gist-logs but got an authentication error.
Everything else I did.

———
Frank McCabe
Senior Software Architect
Phone: 650-919-8856 | Email: fmccabe@instartlogic.com <mailto:yourname@instartlogic.com> 
Instart Logic | 450 Lambert Ave, Palo Alto, CA 94306 | instartlogic.com <http://instartlogic.com/>

**Comment by MikeMcQuaid** [comment]
Can you create a gist manually with your `brew config`, `brew doctor` output? Thanks!

**Comment by fmccabe** [comment]
Not sure how to do that. Can you point me to some documentation?
Thanks
Frank
———
Frank McCabe
Senior Software Architect
Phone: 650-919-8856 | Email: fmccabe@instartlogic.com <mailto:yourname@instartlogic.com> 
Instart Logic | 450 Lambert Ave, Palo Alto, CA 94306 | instartlogic.com <http://instartlogic.com/>

**Comment by fmccabe** [comment]
This is the gist-log 
https://gist.github.com/aaec344b41e44a6867067df2de2235a8

**Comment by MikeMcQuaid** [comment]
It's trying to build `ia32` for some reason and failing. It could be related to one of the `brew doctor` warnings such as dylibs, headers or case-sensitive filesytem.

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.
