### ISSUE TITLE
request:  option to brew qscintilla2 --with-qt4

### ISSUE THREAD

**Issue by EconGeo** [Homebrew/homebrew-core#4365]
`qscintialla2` formula is causing problems with installing `qgis-214`, due to `qscintialla2` brewing with `qt5` now rather than `qt`.  Request option for `qscintilla2 --with-qt4` to get `qgis-214` problem resolved, as QGIS won't brew with `qt5`, which is a dependency now for `qscintilla2`

https://github.com/OSGeo/homebrew-osgeo4mac/issues/151

**Comment by cbertelli** [comment]
Isn't there a way to know that something depends on some formula? This is not a minor problem.

**Comment by MikeMcQuaid** [comment]
@EconGeo We're slowly getting rid of Qt4 support in all formulae as it's not supported any longer and won't work on macOS Sierra.

@cbertelli We welcome pull requests for all problems. We're all volunteers working in our spare time.

**Comment by cbertelli** [comment]
Mine was not a rhetoric question or a lack of gratitude for you and others that work on the brew core formulas, but a real question. What are the formulæ that still depend on Qt4?  In the case of QGIS (and other "vertical" software) the upstream has not completed the transition, so qscintilla2 should be built with Qt4 support to work with these formulæ (or corresponding taps have to provide a qscintilla2-qt4). Anyway I think a good strategy for the transition to Qt5 implies more cooperation; imposing a change may cause disruptions as this one.

**Comment by MikeMcQuaid** [comment]
@cbertelli Thanks. I'm afraid upstreams need to be responsible for fixing these issues themselves. We've had open issues about this for a while and it's been an open issue with Qt for a while.
