### ISSUE TITLE
New Ruby bottle results in `dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib`

### ISSUE THREAD

**Issue by dalemyers** [Homebrew/homebrew-core#43839]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
  <summary><code>brew config</code></summary>
  <pre>
HOMEBREW_VERSION: 2.1.11-13-g5194870
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5194870b9d8019407922e52b97be13a024fa663b
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b541c27b39997f199544eb24ddc4043367a67f2a
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.2
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3 => /Applications/Xcode_10.3.app/Contents/Developer
CLT headers: 10.3.0.0.1.1562985497
</pre>
</details>

<details>
<summary><code>brew doctor</code></summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/dalemy/.pyenv/shims/python3.6m-config
  /Users/dalemy/.pyenv/shims/python-config
  /Users/dalemy/.pyenv/shims/python3-config
  /Users/dalemy/.pyenv/shims/python3.6-config
</pre>
</details>

To help us debug your issue please explain:

Installing the latest Ruby bottle on macOS can result in the error `dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib`. The reason for this is that there is an undeclared dependency on `gmp`. This can be seen by running `brew linkage ruby`. On a machine where `gmp` is not installed it is listed as a broken dependency, but on a machine where `gmp` is installed, it is listed as an undeclared dependency.

This issue appears to have been introduced with the following commit: https://github.com/Homebrew/homebrew-core/commit/3526a6e7a7bfafe241ef79a8fb6b86194958dd6e

Additionally, this issue has happened before. It may be worth investigating why this issue reoccurred: https://github.com/Homebrew/homebrew-core/issues/35956

**Comment by jonchang** [comment]
```console
$ brew linkage ruby
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  /System/Library/Frameworks/Security.framework/Versions/A/Security
  /usr/lib/libSystem.B.dylib
  /usr/lib/libffi.dylib
  /usr/lib/libncurses.5.4.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libutil.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (libyaml)
  /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (openssl@1.1)
  /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (openssl@1.1)
  /usr/local/opt/readline/lib/libreadline.8.dylib (readline)
  /usr/local/Cellar/ruby/2.6.4_2/lib/libruby.2.6.dylib (ruby)
```
