### ISSUE TITLE
"brew install lastpass-cli --with-pinentry --with-doc" fails

### ISSUE THREAD

**Issue by donatj** [Homebrew/homebrew-core#4383]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Trying to install the lastpass CLI with documentation according to their dirrections here: https://github.com/lastpass/lastpass-cli

```bash
brew install lastpass-cli --with-pinentry --with-doc
```

The full log is here: 

https://gist.github.com/donatj/a8bf38d78ed0681dde237912b1f4b4ac

This is from the brew gist-logs:

https://gist.github.com/7dc60c219b94cc9995da5876b5e36e57

**Comment by apjanke** [comment]
I'm unable to reproduce on my 10.11.6 box, whose configuration looks similar to yours.

Here's the error:

```
a2x --no-xmllint -f manpage lpass.1.txt
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20160831-75484-1k9j5ac/lastpass-cli-1.0.0/lpass.1.xml" returned non-zero exit status 6
make: *** [lpass.1] Error 1
```

According to the [xsltproc docs](http://xmlsoft.org/XSLT/xsltproc.html), exit status 6 means there was an error in one of the documents, so the actual problem might be happening earlier in the `a2x` toolchain.

The stuff in your `brew doctor` output suggests:
 * you have an unbrewed `graphviz` installed, and the brewed one is unlinked
 * your brewed `openssl` is linked, but it probably shouldn't be

But it seems unlikely either of those are affecting this.

It's not apparent to me what's breaking here. Maybe someone else has some ideas?

**Comment by apjanke** [comment]
(And while we're on the subject, it's weird that the man pages are optional in the `lastpass-cli` formula. Seems like that should be the default, or the only way to build it.)

**Comment by ninjatux** [comment]
@donatj it happened to me too but a second run solved the problem

**Comment by dunn** [comment]
@ninjatux how did it fail the first time?

**Comment by ninjatux** [comment]
@dunn I'm sorry but I didn't kept the log because the second run made it work without problems.

**Comment by dunn** [comment]
> xsltproc is hitting the internet to retrieve things such as the docbook manpage XSL, as well as the docbook DTD, and fails if it can't.

This seems like the most likely cause; ideally we'd include those files as `resource` blocks; if someone wants to open a PR for that it'd be very welcome!

**Comment by Dispader** [comment]
I'm getting the same error, and a second run doesn't seem to make a difference:

```Bash
(~){azazel}10:39am] brew install lastpass-cli --with-pinentry --with-doc
==> Using the sandbox
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v1.0.0.tar.gz
Already downloaded: /Users/jake/Library/Caches/Homebrew/lastpass-cli-1.0.0.tar.gz
==> make PREFIX=/usr/local/Cellar/lastpass-cli/1.0.0 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/1.0.0/share/man install-doc
Last 15 lines from /Users/jake/Library/Logs/Homebrew/lastpass-cli/02.make:
2016-11-01 10:40:02 -0500

make
MANDIR=/usr/local/Cellar/lastpass-cli/1.0.0/share/man
install-doc

a2x --no-xmllint -f manpage lpass.1.txt
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20161101-33512-ljhm8n/lastpass-cli-1.0.0/lpass.1.xml" returned non-zero exit status 5
make: *** [lpass.1] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

(~){azazel}10:40am] brew install lastpass-cli --with-pinentry --with-doc
==> Using the sandbox
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v1.0.0.tar.gz
Already downloaded: /Users/jake/Library/Caches/Homebrew/lastpass-cli-1.0.0.tar.gz
==> make PREFIX=/usr/local/Cellar/lastpass-cli/1.0.0 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/1.0.0/share/man install-doc
Last 15 lines from /Users/jake/Library/Logs/Homebrew/lastpass-cli/02.make:
2016-11-01 10:40:11 -0500

make
MANDIR=/usr/local/Cellar/lastpass-cli/1.0.0/share/man
install-doc

a2x --no-xmllint -f manpage lpass.1.txt
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20161101-34559-snxgak/lastpass-cli-1.0.0/lpass.1.xml" returned non-zero exit status 5
make: *** [lpass.1] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

**Comment by MikeMcQuaid** [comment]
@Dispader Please feel free to open a new issue when you've read and followed https://git.io/brew-troubleshooting.
