### ISSUE TITLE
VTK Python modules installed to incorrect location

### ISSUE THREAD

**Issue by milljm** [Homebrew/homebrew-core#43953]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [-] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

Not exactly. `brew install` works fine. VTK is installed and working. It is the Python component of VTK which is incorrect.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/0a211ba4dfb18791f45f0d2f88dcfbfd

When I look at that gist, I notice this is my supposed fix.?. Which I have been mocking with `brew edit vtk` (hence revision 3). I am not going to pretend to know how `brew gist-logs` figured that out, even after I started over by removing /usr/local/*

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Import VTK using Python.

- What happened (include command output)

The path to python/site-packages is not where it should be. It appears to be located at:

   /usr/local/opt/vtk/lib/usr/local/Cellar/vtk/8.2.0_2/lib/python3/site-packages

Not at all where the Ruby formula says it should be.

- What you expected to happen

I expect site-packages to reside at:

   /usr/local/opt/vtk/lib/python3.7/site-packages

- Step-by-step reproduction instructions (by running `brew install` commands)

Install Homebrew...
```pre
brew update
brew install vtk
```

**Comment by milljm** [comment]
I have a PR incoming to resolve this.

**Comment by iMichka** [comment]
I maybe broke it when cleaning the formula up a few days ago: #43557

**Comment by milljm** [comment]
I can remove my PR if you want? I am just in the process of completing all the pre-reqs `brew test vtk` at the moment.

My caveat section also does not pass the audit (.to_s splice). But I do not know another way to obtain Python's major.minor version.

**Comment by iMichka** [comment]
Please submit it, I will review it and help you get it merged.

**Comment by milljm** [comment]
Thank you! Will do.

**Comment by iMichka** [comment]
> 8.2.0_2

The current version is 8.2.0_3. You did not update brew.
I tried with the current version and everything works fine. I could run python3 and import vtk out of the box.

The relevant site packages folders are:
/usr/local/opt/vtk/lib/python3.7/site-packages
/usr/local/Cellar/vtk/8.2.0_3/lib/python3.7/site-packages/

**Comment by iMichka** [comment]
Oups, edit on my side: I tried out your fix, and this is why I got revision 3.
The paths are correctly set after your change:
/usr/local/opt/vtk/lib/python3.7/site-packages
/usr/local/Cellar/vtk/8.2.0_3/lib/python3.7/site-packages/

No need to change the PYTHONPATH though, it worked out of the box.
