### ISSUE TITLE
irssi 1.2.2_1 requires utf8proc

### ISSUE THREAD

**Issue by jeversol** [Homebrew/homebrew-core#44058]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

Irssi 1.2.2_1 appears to have a dependency upon the utf8proc library which is not included in the forumlae. 

```
$ irssi
dyld: Library not loaded: /usr/local/opt/utf8proc/lib/libutf8proc.2.dylib
  Referenced from: /usr/local/bin/irssi
  Reason: image not found
fish: 'irssi' terminated by signal SIGABRT (Abort)
```

I did a `brew reinstall irssi` just to ensure everything went well, and no errors were received. Manually installing the utf8proc forumulae (`brew install utf8proc`) resolved the issue.

To confirm the issue, I ran the following steps:

```
$ brew remove utf8proc
Uninstalling /usr/local/Cellar/utf8proc/2.4.0... (10 files, 644.2KB)
$ brew remove irssi
Uninstalling /usr/local/Cellar/irssi/1.2.2_1... (299 files, 4MB)
irssi 1.2.2_1.reinstall is still installed.
Remove all versions with `brew uninstall --force irssi`.
$ brew remove --force irssi
Uninstalling irssi... (299 files, 4MB)
$ brew cleanup
 Pruned 0 symbolic links and 1 directories from /usr/local
$ brew install irssi
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/irssi-1.2.2_1.mojave.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/downloads/6e068d293e52549dbd2a9543929cf51d6a2e128811d98fd33feee2f4c6e39bde--irssi-1.2.2_1.mojave.bottle.tar.gz
==> Pouring irssi-1.2.2_1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/irssi/1.2.2_1: 299 files, 4MB
$ irssi
dyld: Library not loaded: /usr/local/opt/utf8proc/lib/libutf8proc.2.dylib
  Referenced from: /usr/local/bin/irssi
  Reason: image not found
fish: 'irssi' terminated by signal SIGABRT (Abort)
$ brew install utf8proc
==> Downloading https://homebrew.bintray.com/bottles/utf8proc-2.4.0.mojave.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/downloads/da9a53b6bbc108aee6b4018d6bdeadfd80aeb88330d06376024ca52f49f4e351--utf8proc-2.4.0.mojave.bottle.tar.gz
==> Pouring utf8proc-2.4.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/utf8proc/2.4.0: 10 files, 644.2KB
$ irssi
<irssi launches successfully>
```
Here is the output from brew doctor and brew config:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libjson-c.2.dylib
  /usr/local/lib/libykclient.3.dylib
  /usr/local/lib/libykpers-1.1.dylib
$ brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 00853ee225168becf0ea57b26d11f8821b878d54
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_60, 1.8.0_31
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497```

Thanks!

**Comment by fxcoudert** [comment]
Can you run `brew up && brew reinstall irssi`, after having removed `utf8proc`? It should work now.

**Comment by fxcoudert** [comment]
Rebottled in https://github.com/Homebrew/homebrew-core/commit/868cb454ff2d0eb871546b89e23b0bb025b7313e
