### ISSUE TITLE
PHP 7.3.9_1 has problem with CURL-OPENSSL 7.65.3_1

### ISSUE THREAD

**Issue by michalper** [Homebrew/homebrew-core#44050]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
**php -v
to check latest php version**
- What happened (include command output)
**dyld: Library not loaded: /usr/local/opt/libidn2/lib/libidn2.0.dylib
  Referenced from: /usr/local/opt/curl-openssl/lib/libcurl.4.dylib
  Reason: image not found**
Abort trap: 6
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

> brew update
> brew upgrade
> ==> Upgrading curl-openssl 
> ==> Installing dependencies for curl-openssl: libssh2, libevent, nghttp2 and rtmpdump
> ==> Upgrading 1 outdated package:
> php 7.3.9 -> 7.3.9_1
> ==> Upgrading php 
> ==> Downloading https://homebrew.bintray.com/bottles/php-7.3.9_1.mojave.bottle.tar.gz
> ==> Downloading from https://akamai.bintray.com/4b/4b6b3ea4704f2debd9d506e3c8820d2958b7e1eca6daece64796ca9a03e364d1?__gda__=exp=1568024192~hmac=2ff9cf7f901737e12d39bda75d9dbbaee90b83c20d3f9ba03f23763f
> ######################################################################## 100.0%
> ==> Pouring php-7.3.9_1.mojave.bottle.tar.gz
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set php_ini /usr/local/etc/php/7.3/php.ini system
> Last 15 lines from /Users/michalper/Library/Logs/Homebrew/php/post_install.01.pear:
> 2019-09-09 12:04:51 +0200
> 
> /usr/local/Cellar/php/7.3.9_1/bin/pear
> config-set
> php_ini
> /usr/local/etc/php/7.3/php.ini
> system
> 
> dyld: Library not loaded: /usr/local/opt/libidn2/lib/libidn2.0.dylib
>   Referenced from: /usr/local/opt/curl-openssl/lib/libcurl.4.dylib
>   Reason: image not found
> Warning: The post-install step did not complete successfully
> You can try again using `brew postinstall php`

**Comment by fxcoudert** [comment]
Can you run `brew up && brew reinstall curl-openssl` and then try to reinstall php?

**Comment by michalper** [comment]
> MacBook-Pro-Peru:~ michalper$ brew up && brew reinstall curl-openssl 
> Updated 1 tap (homebrew/core).
> No changes to formulae.
> ==> Reinstalling curl-openssl 
> ==> Downloading https://homebrew.bintray.com/bottles/curl-openssl-7.65.3_1.mojave.bottle.1.tar.gz
> ==> Downloading from https://akamai.bintray.com/1a/1a091d64204dedaeb5000d653764648be7f6d2af6378820a7e34d6cdb4d9207f?__gda__=exp=1568030320~hmac=b6d4811bdabdea2e20560af5a6526e23707d8963c6e7c52e4bb568b2
> ######################################################################## 100.0%
> ==> Pouring curl-openssl-7.65.3_1.mojave.bottle.1.tar.gz
> ==> Caveats
> curl-openssl is keg-only, which means it was not symlinked into /usr/local,
> because macOS already provides this software and installing another version in
> parallel can cause all kinds of trouble.
> 
> If you need to have curl-openssl first in your PATH run:
>   echo 'export PATH="/usr/local/opt/curl-openssl/bin:$PATH"' >> ~/.bash_profile
> 
> For compilers to find curl-openssl you may need to set:
>   export LDFLAGS="-L/usr/local/opt/curl-openssl/lib"
>   export CPPFLAGS="-I/usr/local/opt/curl-openssl/include"
> 
> ==> Summary
> 🍺  /usr/local/Cellar/curl-openssl/7.65.3_1: 451 files, 3.4MB
> Removing: /Users/michalper/Library/Caches/Homebrew/curl-openssl--7.65.3.mojave.bottle.tar.gz... (1MB)
> Removing: /Users/michalper/Library/Caches/Homebrew/curl-openssl--7.65.3_1.mojave.bottle.tar.gz... (1MB)
> MacBook-Pro-Peru:~ michalper$ brew reinstall php
> ==> Reinstalling php 
> ==> Downloading https://homebrew.bintray.com/bottles/php-7.3.9_1.mojave.bottle.tar.gz
> Already downloaded: /Users/michalper/Library/Caches/Homebrew/downloads/d3fcea0bcce8716b5dabde55cd49f0576c235a6480e6671aec016f114cf910a4--php-7.3.9_1.mojave.bottle.tar.gz
> ==> Pouring php-7.3.9_1.mojave.bottle.tar.gz
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set php_ini /usr/local/etc/php/7.3/php.ini system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set php_dir /usr/local/share/pear system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set doc_dir /usr/local/share/pear/doc system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set ext_dir /usr/local/lib/php/pecl/20180731 system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set bin_dir /usr/local/opt/php/bin system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set data_dir /usr/local/share/pear/data system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set cfg_dir /usr/local/share/pear/cfg system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set www_dir /usr/local/share/pear/htdocs system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set man_dir /usr/local/share/man system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set test_dir /usr/local/share/pear/test system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear config-set php_bin /usr/local/opt/php/bin/php system
> ==> /usr/local/Cellar/php/7.3.9_1/bin/pear update-channels
> ==> Caveats
> To enable PHP in Apache add the following to httpd.conf and restart Apache:
>     LoadModule php7_module /usr/local/opt/php/lib/httpd/modules/libphp7.so
> 
>     <FilesMatch \.php$>
>         SetHandler application/x-httpd-php
>     </FilesMatch>
> 
> Finally, check DirectoryIndex includes index.php
>     DirectoryIndex index.php index.html
> 
> The php.ini and php-fpm.ini file can be found in:
>     /usr/local/etc/php/7.3/
> 
> To have launchd start php now and restart at login:
>   brew services start php
> Or, if you don't want/need a background service you can just run:
>   php-fpm
> ==> Summary
> 🍺  /usr/local/Cellar/php/7.3.9_1: 521 files, 77.0MB

> MacBook-Pro-Peru:~ michalper$ php -v
> PHP 7.3.9 (cli) (built: Sep  8 2019 14:56:33) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
>     with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
>     with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies

THANKS FOR YOUR HELP
