### ISSUE TITLE
collectd 'write_http' plugin missing dependency yajl

### ISSUE THREAD

**Issue by sp-ricard-valverde** [Homebrew/homebrew-core#44099]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

````
$ brew config && brew doctor
HOMEBREW_VERSION: 2.1.11-49-gf98efa1
ORIGIN: https://github.com/Homebrew/brew
HEAD: f98efa11abb46391a3fc3dbc685d6bd182755854
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b18ce0807b1713df7827e7feb28b3f99c53ebea7
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: 24-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode-10.2.1.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_162
macOS: 10.14.6-x86_64
CLT: 11.0.0.0.1.1564155526
Xcode: 10.2.1 => /Applications/Xcode-10.2.1.app/Contents/Developer
CLT headers: 11.0.0.0.1.1564155526
Your system is ready to brew.
````

To help us debug your issue please explain:

- **Q**: What you were trying to do (and why)
Run brew-installed _collectd_ 5.9.0_3 with plugin 'write_http'
- **Q**: What happened (include command output)
_collectd_ launchctl daemon failed with output:
````
$
[2019-09-10 10:30:24] plugin_load: plugin "logfile" successfully loaded.
[2019-09-10 10:30:24] plugin_load: plugin "cpu" successfully loaded.
[2019-09-10 10:30:24] plugin_load: plugin "df" successfully loaded.
[2019-09-10 10:30:24] plugin_load: plugin "disk" successfully loaded.
[2019-09-10 10:30:24] plugin_load: plugin "interface" successfully loaded.
[2019-09-10 10:30:24] plugin_load: plugin "load" successfully loaded.
[2019-09-10 10:30:24] plugin_load: plugin "memory" successfully loaded.
ERROR: dlopen("/usr/local/Cellar/collectd/5.9.0_3/lib/collectd/write_http.so") failed: dlopen(/usr/local/Cellar/collectd/5.9.0_3/lib/collectd/write_http.so, 2): Library not loaded: /usr/local/opt/yajl/lib/libyajl.2.dylib
  Referenced from: /usr/local/Cellar/collectd/5.9.0_3/lib/collectd/write_http.so
  Reason: image not found. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
[2019-09-10 10:30:24] dlopen("/usr/local/Cellar/collectd/5.9.0_3/lib/collectd/write_http.so") failed: dlopen(/usr/local/Cellar/collectd/5.9.0_3/lib/collectd/write_http.so, 2): Library not loaded: /usr/local/opt/yajl/lib/libyajl.2.dylib
  Referenced from: /usr/local/Cellar/collectd/5.9.0_3/lib/collectd/write_http.so
  Reason: image not found. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
[2019-09-10 10:30:24] plugin_load: Load plugin "write_http" failed with status 2.
[2019-09-10 10:30:24] There is a `Node' block within the configuration for the write_http plugin. The plugin either only expects "simple" configuration statements or wasn't loaded using `LoadPlugin'. Please check your configuration.
Error: Parsing the config file failed!
````
- **Q**: What you expected to happen
_collectd_ to start successfully, as it does in previous version 5.9.0_**2**
- **Q**: Step-by-step reproduction instructions (by running `brew install` commands)
````
brew install collectd
echo "LoadPlugin write_http" >> /usr/local/etc/collectd-user.conf
launchctl load /Library/LaunchDaemons/homebrew.mxcl.collectd.plist
````

**Comment by fxcoudert** [comment]
Should be fixed now. Can you run `brew up && brew reinstall collectd`, then see if it is fixed for you?

**Comment by sp-ricard-valverde** [comment]
All good, many thanks for the quick fix 👍
