### ISSUE TITLE
peco 0.4.2 upgrade fails during glide install

### ISSUE THREAD

**Issue by hakamadare** [Homebrew/homebrew-core#4412]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

When running the command `brew upgrade peco`, I get a failure from inside the `install` method of the formula:

```
$ brew upgrade peco
==> Upgrading 1 outdated package, with result:
peco 0.4.2
==> Upgrading peco
==> Using the sandbox
==> Downloading https://github.com/peco/peco/archive/v0.4.2.tar.gz
Already downloaded: /opt/boxen/cache/homebrew/peco-0.4.2.tar.gz
==> glide install
Last 15 lines from /Users/rk/Library/Logs/Homebrew/peco/01.glide:
2016-09-01 09:17:43 -0400

glide
install

[INFO] 	Downloading dependencies. Please wait...
[ERROR]	Cache directory unavailable: mkdir /Users/rk/.glide: operation not permitted

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

I apologize, when I ran `brew gist-logs peco`, I got an error message (likely unrelated to this issue):

```
$ brew gist-logs peco
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes it has: ["repo", "user"]
Create a new personal access token: https://github.com/settings/tokens
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: {
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/gists/#create-a-gist"
}
```

Looking at the documentation for glide, this suggests to me that `glide install` is running into a permissions problem; perhaps work around it by setting `$GLIDE_HOME` to a temp dir or something?

**Comment by ilovezfs** [comment]
@hakamadare voilà https://github.com/Homebrew/homebrew-core/pull/4413

**Comment by hakamadare** [comment]
nice :) i just submitted #4414 with an alternate fix, both seem fine to me.

**Comment by ilovezfs** [comment]
@hakamadare cool. that will work for sure, but it's not necessary because the buildpath is already in a temporary directory. By the way, I think this is actually an upstream glide bug because we set HOME to buildpath/".brew_home" so it should be using buildpath/".brew_home/.glide" but upstream isn't respecting the value of the HOME environment variable for some reason.
