### ISSUE TITLE
Kubebuilder recipe does not create a setup that works with Kubebuilder test suites

### ISSUE THREAD

**Issue by fbiville** [Homebrew/homebrew-core#44175]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
<hr/>

To help us debug your issue please explain:

**What you were trying to do (and why)**

I am trying to use Kubebuilder to scaffold custom controllers and CRDs.

The controllers' test suites are generated assuming that a Kubebuilder installation includes a `bin/` directory (default path: `/usr/local/kubebuilder/bin`, overridable with envvar `KUBEBUILDER_ASSETS`) with the following binaries:

 - `kube-apiserver`
 - `etcd`
 - `kubectl`

**What happened (include command output)**

The current Homebrew setup for `kubebuilder` is:
```
➜  ~ tree /usr/local/Cellar/kubebuilder/2.0.0
/usr/local/Cellar/kubebuilder/2.0.0
├── INSTALL_RECEIPT.json
├── LICENSE
├── README.md
└── bin
    └── kubebuilder

1 directory, 4 files
```

This means that a Homebrew installation of `kubebuilder` is currently not in a usable state beyond code generation (i.e. the generated tests cannot run).

**What you expected to happen**

I expect the `bin` folder to include not only `kubebuilder` but also:

 - `kube-apiserver`
 - `etcd`
 - `kubectl`

And `KUBEBUILDER_ASSETS` envvar to be set against that directory.

**Step-by-step reproduction instructions (by running `brew install` commands)**

 - `brew install kubebuilder tree`
 - `tree /usr/local/Cellar/kubebuilder/2.0.0`

**Comment by iMichka** [comment]
We manually install the files here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kubebuilder.rb#L27-L28

Ideally there should be a `make install` step, and we should be delegating this operation to upstream, who will make a wiser choice on what files need to be installed.

As this is not the case, and this issue has been open since Sept. 12, and we do not have the bandwidth to respond to all requests, I'll close this issue. From our perspective this is a feature request, not a real bug on our side. I would be willing to review a pull request which adds the needed files during the install step.
