### ISSUE TITLE
Please update to Expat 2.2.8 with security fixes

### ISSUE THREAD

**Issue by hartwork** [Homebrew/homebrew-core#44281]
https://github.com/libexpat/libexpat/releases/tag/R_2_2_8

Thank you!

**Comment by SMillerDev** [comment]
From the issue template:

> To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

**Comment by hartwork** [comment]
@SMillerDev I don't use macOS or Homebrew so I would not be able to test a pull request. I fixed the vulnerability, but I cannot help with the upgrade.

**Comment by SMillerDev** [comment]
That's fine, we have CI for that

**Comment by hartwork** [comment]
@SMillerDev if you look at https://github.com/libexpat/libexpat/issues/342 , a full release already takes hours and I will not provide pull requests for every relevant distro on earth on top — that doesn't scale. It's enough work to notify every party who needs to know, already. There has to be a line somewhere.

**Comment by SMillerDev** [comment]
@hartwork  if you look at https://github.com/Homebrew/homebrew-core/pulls, there is already a lot of work to package software that does make pull requests, it's pretty much impossible to package updates if people just make an issue instead of a PR — that doesn't scale. It's enough work to package the people following procedure, already. There has to be a line somewhere.

**Comment by hartwork** [comment]
> @hartwork if you look at https://github.com/Homebrew/homebrew-core/pulls, there is already a lot of work to package software that does make pull requests, it's pretty much impossible to package updates if people just make an issue instead of a PR — that doesn't scale. It's enough work to package the people following procedure, already. There has to be a line somewhere.

If I browse through https://github.com/Homebrew/homebrew-core/pulls there are many labelled `new formula` and many labelled `build failure`. I would hope that there is someone on the homebrew team who cares about security fixes to existing packages more than about new packages, regarding urgency, pull request or not.

Regarding scale, I'm maintaining packages in some GNU/Linux distribution myself and I newer heard anyone say there that we'll be doomed without user pull requests, while great to have. Packages have maintainers, people open bump request bugs, maintainer updates package — works well most of the time. Maybe the two projects are different, could be — I don't know. But that's where I'm coming from.

I didn't intend this to escalate. I explained why I won't do a pull request myself and the related reasoning is still valid. If we continue discussing this, I would ask you to stop copying my words because I don't consider that… a great idea. How do you want us and this ticket to continue? What would you want me to do — other than a pull request — next time there is an update with security fixes?

Best, Sebastian

**Comment by issyl0** [comment]
Homebrew has the latest [expat 2.2.8](https://github.com/Homebrew/homebrew-core/pull/44259) available to users now. :+1:

**Comment by hartwork** [comment]
@ilovezfs I saw you bumped Expat here a [multiple times](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+expat+is%3Aclosed+author%3Ailovezfs) — could you help out with a PR for 2.2.8?

**Comment by alebcay** [comment]
I have opened #44299 to bump `expat` to 2.2.8. To address some other concerns you brought up:

>  I would hope that there is someone on the homebrew team who cares about security fixes to existing packages more than about new packages, regarding urgency, pull request or not.

Most of these pull requests are _not_ opened by the Homebrew team. Some of us open pull requests in our spare time, but I think it would be accurate to say that a good chunk of our PRs are opened by people not on the team.

On the other hand, people have opened pull requests for security fixes for other software before. They do generally get reviewed and pushed through faster. But again - maintainers are generally _reviewing_, not _opening_, these pull requests.

> Packages have maintainers, people open bump request bugs, maintainer updates package — works well most of the time. Maybe the two projects are different, could be — I don't know. But that's where I'm coming from.

I understand that this is how a lot of package repositories work. Homebrew does _not_ designate a maintainer for any particular package. The `homebrew-core` team, which is responsible for maintaining this repository of actual package definitions, contains 19 people. At the time of writing, the core repo contains 4821 packages. If the `homebrew-core` team were to assume responsibility for these packages on their own, then that would come out to each maintainer being responsible for maintaining roughly 254 packages. This _definitely_ does not scale.

Keep in mind that many of these packages are very niche and that the maintainers of this repo don't use much of the software that we package. For example, I have never used or developed `expat` before. In fact, I have never used most of the software that I bump here on Homebrew.

> What would you want me to do — other than a pull request — next time there is an update with security fixes?

Ask someone else to open a pull request. It can be a maintainer here, or someone who's not a maintainer.
