### ISSUE TITLE
Neovim 0.4.2 spits out odd stderr messages

### ISSUE THREAD

**Issue by spencerwi** [Homebrew/homebrew-core#44324]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Upgrade neovim to 0.4.x, now that 0.4.2 is released.
- What happened (include command output)
When running Neovim commands that involved opening a new "split" from a full-screen buffer (like editing a file that fills the screen, then opening `:Termdebug`), messages like this get dumped into a seemingly-random place on the screen until a Ctrl-L terminal force-redraw is issued:
```
resize_buffer[0]: start oldrow=0 newrow=17
  Copying oldrow=0 to newrow=17
  Ran out of content to fill screen; we should pop scrollback 16 rows
  Ran out of content to fill screen; we should move 1 rows from 17 to 0
resize_buffer[1]: start oldrow=0 newrow=17
  Copying oldrow=0 to newrow=17
  Ran out of content to fill screen; we should pop scrollback 16 rows
  Ran out of content to fill screen; we should move 1 rows from 17 to 0
```
Running `nvim 2>/dev/null` as the command to launch neovim prevents this, suggesting that the messages are supposed to be sent to stderr. When using binaries obtained directly from Neovim's [own "releases" page](https://github.com/neovim/neovim/releases/tag/v0.4.2), this behavior does not occur.
- What you expected to happen
The behavior should be the same as with binaries obtained from Neovim's releases page (no stderr messages appearing at random spots)
- Step-by-step reproduction instructions (by running `brew install` commands)
1. `brew install neovim`
2. `nvim some-file-that-will-fill-the-screen`
3. In neovim, `:packadd termdebug`
4. In neovim `:Termdebug`
5. The stderr messages will appear: 
![image](https://user-images.githubusercontent.com/2829379/64963030-80c26c80-d866-11e9-9c9b-eb02d7624766.png)

**Comment by jason0x43** [comment]
I have also observed this, specifically when using fzf-vim's `:Files` command. As the OP points out, starting neovim with `2> /dev/null` prevents the issue.

**Comment by fxcoudert** [comment]
poke @xu-cheng

**Comment by xu-cheng** [comment]
cc @justinmk

**Comment by justinmk** [comment]
MIN_LOG_LEVEL when building?

**Comment by fxcoudert** [comment]
`libvterm` was built with `make install PREFIX=whatever`

**Comment by justinmk** [comment]
See https://github.com/neovim/neovim/issues/11031#issuecomment-531923040

**Comment by bfredl** [comment]
libvterm released 0.1.1 http://www.leonerd.org.uk/code/libvterm/libvterm-0.1.1.tar.gz
Update the formula to use it and the issue should go away

**Comment by fxcoudert** [comment]
Is it fixed by https://github.com/Homebrew/homebrew-core/pull/44349 ?

**Comment by kule** [comment]
@fxcoudert Yep, I did ```brew reinstall neovim``` and it updated to libvterm 0.1.1 and all is working correctly now.
