### ISSUE TITLE
percona-toolkit forgets to depend on pidof

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#44327]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why) Run `pt-mysql-summary` from the percona-toolkit formula.
- What happened (include command output)

```console
pidof: command not found
```

- What you expected to happen

The formula to properly specify all of its dependencies.

- Step-by-step reproduction instructions (by running `brew install` commands)

```console
$ brew install percona-toolkit

$ command -V pidof
-bash: command: pidof: not found

$ pt-mysql-summary -- --user='root' --password='...' --protocol=TCP
...
pidof: command not found
```

**Comment by SMillerDev** [comment]
That seems to be an error indeed. Could you make a pull request to add the dependency?

**Comment by mcandre** [comment]
**Update**

In fact, it's not just pidof, which is easily provided, but other parts of percona-toolkit are specifically written to assume a Linux host:

```console
grep: /proc/2147/environ: No such file or directory
```

As well as sudo privileges. I'm grateful that developers are attempting to port as much of percona-toolkit as possible to macOS, but in practice this system works best when running directly on the same (Linux) node as the MySQL server deployment.

**Comment by fxcoudert** [comment]
Yes, the `/proc` filesystem is not something we can fake in Homebrew :)
Can you report this as upstream bug?
