### ISSUE TITLE
Split formulas into subdirectories?

### ISSUE THREAD

**Issue by blueyed** [Homebrew/homebrew-core#44346]
Please consider splitting formulas into subdirectories (e.g. by first letter) to allow for browsing it at https://github.com/Homebrew/homebrew-core/tree/master/Formula.

While you can create a path manually (I was looking for https://github.com/Homebrew/homebrew-core/blob/master/Formula/neovim.rb and https://github.com/Homebrew/homebrew-core/blob/master/Formula/libvterm.rb), it might make things more pleasant in general.

I can also see that it's not really necessary, and likely not that trivial - so feel free to close this as wont-fix.

**Comment by SMillerDev** [comment]
@MikeMcQuaid probably has a better explanation but this has been requested before and my understanding is that it would significantly slow down all brew operations due to slower git operations.

**Comment by MikeMcQuaid** [comment]
In general this will be a lot of work for little return beyond "it makes the GitHub UI easier to use".

https://formulae.brew.sh is a better way of browsing formulae.

**Comment by blueyed** [comment]
Understood, thanks!
