### ISSUE TITLE
Dependencies with .pc files relying on libffi should point to the keg

### ISSUE THREAD

**Issue by nox** [Homebrew/homebrew-core#44345]
As explained in https://github.com/Homebrew/homebrew-core/issues/40179#issuecomment-524543724:

> Homebrew installs pkg-config files from non-keg-only crates that just cannot work because they themselves refer to files from libffi that just cannot be found. Homebrew is basically installing things that just can't work. Saying that we should export env variables every time is way worse than just a caveat for people wishing to use libffi directly.
> 
> Why aren't the pkg-config files from the crates that depend on libffi not using paths to the libffi keg as suggested in [this comment](https://github.com/Homebrew/homebrew-core/issues/40179#issuecomment-503954146)?

glib's various pkgconfig files should be pointing to libffi's pkgconfig file from libffi's keg.

**Comment by nox** [comment]
What? The checklist doesn't apply to this ticket, and it's about some fundamental decision Homebrew needs to make for itself. Should it install things that just won't work as is?

**Comment by SMillerDev** [comment]
How do they not work? Can you fill out the template to help us understand how they're not working?

**Comment by nox** [comment]
It was explained multiple times in #40179 but the issue was closed prematurely, I only opened this one to try and make some progress about it. If you want details, go read and reopen that one.
