### ISSUE TITLE
please update aqbanking / Gwenhywfar - current version is unusable

### ISSUE THREAD

**Issue by Hinnack** [Homebrew/homebrew-core#44381]
because of PSD2 the current version of aqbanking is unusable with any European bank.

brew install --HEAD aqbanking does not work, as it requires Gwenhywfar version >=4.99.10.0... 
and it seems that Gwenhywfar does not support the --HEAD option and only installs 4.20.0.0

**Comment by SMillerDev** [comment]
Homebrew relies on the public submitting pull requests to keep software up to date. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request can help you get started being the hero that updates a piece of software for every homebrew user out there.
