### ISSUE TITLE
Varnish Cache 4.1.3 Update

### ISSUE THREAD

**Issue by craigcarnell** [Homebrew/homebrew-core#4438]
Please update varnish. It is currently on 4.1.0

Latest is 4.1.3

Thank you

**Comment by dunn** [comment]
Anyone can update a formula.  If you want to give it a shot, that'd be great! Take a look at https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by craigcarnell** [comment]
@dunn PR created https://github.com/Homebrew/homebrew-core/pull/5067
