### ISSUE TITLE
Failed to download Passenger-6.0.4 error 401 forbidden

### ISSUE THREAD

**Issue by skunkworker** [Homebrew/homebrew-core#44477]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [n/a] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [n/a] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

When trying to update Passenger-6.0.4 high sierra I got a 401 when trying to download from homebrew.bintray.com.

`https://homebrew.bintray.com/bottles/passenger-6.0.4.high_sierra.bottle.tar.gz`

```
Already up-to-date.
==> Upgrading 1 outdated package:
passenger 6.0.3 -> 6.0.4
==> Upgrading passenger
==> Downloading https://homebrew.bintray.com/bottles/passenger-6.0.4.high_sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "passenger"
Download failed: https://homebrew.bintray.com/bottles/passenger-6.0.4.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/phusion/passenger/releases/download/release-6.0.4/passenger-6.0.4.tar.gz
```

```
$ wget https://homebrew.bintray.com/bottles/passenger-6.0.4.high_sierra.bottle.tar.gz                                                  
--2019-09-20 23:08:54--  https://homebrew.bintray.com/bottles/passenger-6.0.4.high_sierra.bottle.tar.gz
Resolving homebrew.bintray.com (homebrew.bintray.com)... 52.35.217.225, 54.201.76.60
Connecting to homebrew.bintray.com (homebrew.bintray.com)|52.35.217.225|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
```

I saw the error in my update log and trying to get the updated binary I ran into a 401 which I hadn't seen before.

**Comment by wtremmel** [comment]
I have the same problem. Seems that https://homebrew.bintray.com/bottles is suddenly password protected.

**Comment by divinerites** [comment]
same here with `hugo`. General issue I guess.

```
==> Upgrading hugo 
==> Downloading https://homebrew.bintray.com/bottles/hugo-0.58.3.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 401 Unauthorized
```

**Comment by SMillerDev** [comment]
It's a bunch of formula that were merged improperly so the bottles aren't made public. I'll fix it in a bit.

**Comment by SMillerDev** [comment]
Should be fixed now. Can anyone confirm?

**Comment by jerryskye** [comment]
@SMillerDev confirmed with `hugo 0.58.3`. Thanks for the fix! ❤️

**Comment by divinerites** [comment]
confirmed Ok. Thanks.
