### ISSUE TITLE
cmake boost 1.71 component MPI not found.

### ISSUE THREAD

**Issue by jimages** [Homebrew/homebrew-core#44492]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Configure cmake-project using the following CMakeLists stub:
```
## Boost
FIND_PACKAGE(Boost REQUIRED  COMPONENTS mpi)
```
- What happened (include command output)
cmake can't find the boost-mpi cmake file.
```
- The Build type is Debug
-- Found OpenMP.
CMake Error at /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_mpi"
  (requested version 1.71.0) with any of the following names:

    boost_mpiConfig.cmake
    boost_mpi-config.cmake

  Add the installation prefix of "boost_mpi" to CMAKE_PREFIX_PATH or set
  "boost_mpi_DIR" to a directory containing one of the above files.  If
  "boost_mpi" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/3.14.5/share/cmake/Modules/FindBoost.cmake:266 (find_package)
  CMakeLists.txt:64 (FIND_PACKAGE)
```
- What you expected to happen
Configuration should complete without errors.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install boost boost-mpi` can cause the problem.

# References
## brew config
```
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 4 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8eeed377bde6937127b70bcc66769984743549dd
Core tap last commit: 24 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.2.1
XQuartz: 2.7.11 => /opt/X11
```

## Doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/psqlodbca.la
  /usr/local/lib/psqlodbcw.la

Warning: Some installed formulae are not readable:
  mongodb: unknown version :mountain_lion
```

**Comment by jimages** [comment]
it seems the `boost_mpi-config.cmake` or `boost_mpiConfig.cmake` is missing even after installing  the `boost` and `boost-mpi`.

**Comment by henryiii** [comment]
I expect this is related to #44093. A temporary workaround is listed there, too.
