### ISSUE TITLE
kustomize 3.2.0 bottle returns 401 Unauthorized

### ISSUE THREAD

**Issue by wosc** [Homebrew/homebrew-core#44504]
The current `kustomize` bottle is not downloadable:

```
$ brew upgrade kustomize -v
==> Upgrading 1 outdated package:
kustomize 3.1.0 -> 3.2.0
==> Upgrading kustomize
rm /usr/local/bin/kustomize
==> Downloading https://homebrew.bintray.com/bottles/kustomize-3.2.0.sierra.bottle.tar.gz
/usr/bin/curl -q --show-error --user-agent Homebrew/2.1.11-109-g4326a7b\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.12.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/schnerring/Library/Caches/Homebrew/downloads/ff2d45ee6d58062db3d5f1884ee772664e193e598044ca8b148783db5d6fd034--kustomize-3.2.0.sierra.bottle.tar.gz.incomplete https://homebrew.bintray.com/bottles/kustomize-3.2.0.sierra.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "kustomize"
Download failed: https://homebrew.bintray.com/bottles/kustomize-3.2.0.sierra.bottle.tar.gz
```

Thanks for your help!

Below is the full issue checklist (even though I don't imagine it's very relevant here):
<details>
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 2.1.11-109-g4326a7b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4326a7b22e53604fe70e2c2a6edb90a16238a1d6
Last commit: 39 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c9b113bc6812dc74c598c8f860017e42fba8d78
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13, 1.8.0_202
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/schnerring/bin/rsspull-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker-machine
  gnupg
  go
  hyperkit
  postgresql

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```
</details>

**Comment by jonchang** [comment]
Thanks for the report, please run `brew update` and try again.

**Comment by wosc** [comment]
Works like a charm, thank you very much!
