### ISSUE TITLE
Installing git-annex reports 401 Unauthorized

### ISSUE THREAD

**Issue by nirgo** [Homebrew/homebrew-core#44570]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
**NOTE:** I am **not** behind a proxy.

- What you were trying to do (and why)
`# brew install git-annex`
- What happened (include command output)
```
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "git-annex"
Download failed: https://homebrew.bintray.com/bottles/git-annex-7.20190912.mojave.bottle.tar.gz
```

- What you expected to happen
I expected the latest `git-annex` to install

- Step-by-step reproduction instructions (by running `brew install` commands)
`# brew update`
`# brew install git-annex`

**Comment by nirgo** [comment]
It's installing correctly now.

**Comment by SMillerDev** [comment]
Totally forgot to answer this one. It was an issue with merges, was fixed a couple of hours ago.
