### ISSUE TITLE
Concern regarding mpv removal

### ISSUE THREAD

**Issue by sashkab** [Homebrew/homebrew-core#44585]
I have a concern regarding removal of the mpv formulae in #44282. Commit, b18f104f14350b58b9d6d5b8280af073327bf0b8, references `brew cask install mpv` which will install mpv built by someone somewhere. 

mpv cask was added by Homebrew/homebrew-cask#29055, which says 

>```
> # laboratory.stolendata.net/~djinn/mpv_osx was verified as official when first introduced to the cask
>```

But in the pull request I see zero references to the proof of verification that laboratory.stolendata.net/~djinn/mpv_osx was verified. Nor, I see any mentions of that url in the mpv project.

Removal of mpv formulae should be reverted and pointed to the current master, or verification proof posted somewhere easy to find.

**Comment by sashkab** [comment]
This is a problem referencing recent removal, which can lead to use of something from untrusted and unverified location.

**Comment by sashkab** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

**Comment by jonchang** [comment]
It’s on the mpv website: https://mpv.io/installation/

**Comment by sashkab** [comment]
Thanks @jonchang.
