### ISSUE TITLE
root failed to build on 10.14.6

### ISSUE THREAD

**Issue by ryounsumiko** [Homebrew/homebrew-core#44635]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
I tried to upgrade root to 6.18.04 by building from source. Note that I only installed Command Line tools but not Xcode app
- What happened (include command output)
  - Terminal outputs:
$ brew upgrade root
==> Upgrading 1 outdated package:
root 6.16.00_2 -> 6.18.04
==> Upgrading root
Warning: Building root from source:
  The bottle hardcodes locations inside Xcode.app
==> Downloading https://root.cern.ch/download/root_v6.18.04.source.tar.gz
Already downloaded: /Users/Ryounsumiko/Library/Caches/Homebrew/downloads/1511d0ae4c485809b6fc7a7a092f406a573f0ce6672bd5ca720eedf7943e5dba--root_v6.18.04.source.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/root/6.18.04 -D
==> make install
Last 15 lines from /Users/Ryounsumiko/Library/Logs/Homebrew/root/02.make:
In file included from /tmp/root-20190927-98684-1tbp87k/root-6.18.04/builddir/include/TDictionary.h:44:
In file included from /tmp/root-20190927-98684-1tbp87k/root-6.18.04/builddir/include/TNamed.h:26:
In file included from /tmp/root-20190927-98684-1tbp87k/root-6.18.04/builddir/include/TString.h:26:
/tmp/root-20190927-98684-1tbp87k/root-6.18.04/builddir/include/TMathBase.h:159:18: error: expected unqualified-id
   { return std::signbit(a);  }
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/math.h:170:5: note: expanded from macro 'signbit'
    ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
    ^
16 errors generated.
make[2]: *** [core/CMakeFiles/Core.dir/G__Core.cxx.o] Error 1
make[1]: *** [core/CMakeFiles/Core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 73%] Built target MetaCling
make: *** [all] Error 2

  - gist log:
  https://gist.github.com/8611950679769bb32499e8807ff22eda
- What you expected to happen
Successful building.
- Step-by-step reproduction instructions (by running `brew install` commands)
I ran `$ brew upgrade root`, but I think it could be reproduced by `$ brew install root` as well.

**Comment by fxcoudert** [comment]
poke @henryiii

**Comment by henryiii** [comment]
Sorry for the delay, was traveling all last week in CA to see family and just got back. A few questions:

* Why did this not download the bottle?
* Do you have the full SDK? I've always installed XCode so not sure what comes without it. You got to 73 percent so I would assume everything?
* Are you on 10.14's SDK or 10.15? (Xcode updated a couple of weeks ago, on my desktop I have the 10.15 SDK even though I'm on 10.14 as 10.15 is only on gold master and not released yet)

**Comment by ryounsumiko** [comment]
> Why did this not download the bottle?

Because I only installed Xcode CTL instead of the complete app. See #30726

> Do you have the full SDK? I've always installed XCode so not sure what comes without it. You got to 73 percent so I would assume everything?

As I said, I have CTL only but it used to work, so I believe I have everything needed.

> Are you on 10.14's SDK or 10.15? (Xcode updated a couple of weeks ago, on my desktop I have the 10.15 SDK even though I'm on 10.14 as 10.15 is only on gold master and not released yet)

10.15

**Comment by henryiii** [comment]
I rather expect there's a problem building ROOT with 10.15, then.

Why is that reporting the 10.14 location, actually? `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/math.h`

**Comment by henryiii** [comment]
Very similar issue: https://root-forum.cern.ch/t/problem-installing-root-v6-14-06-on-macos-mojave-version-10-14-2/32228

**Comment by ryounsumiko** [comment]
I don't know why the compiler looks for 10.14 location but the path is soft linked to 10.15:
$ greadlink -f /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/math.h
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h

**Comment by henryiii** [comment]
Looks like signbit showed up here too: https://discourse.brew.sh/t/mac-os-10-15-catalina-issues/5001. Is your base operating system 10.14 or 10.15 GM?

**Comment by ryounsumiko** [comment]
My OS is 10.14.6

**Comment by henryiii** [comment]
Works fine with 10.14 tools and 10.15 Xcode (not sure how that happens, assuming tools are the important one):

```
brew install root --build-from-source
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from dc35cf4e3 to 203f8d66a.
Updated 2 taps (homebrew/core and homebrew/cask).
No changes to formulae.

==> Downloading https://root.cern.ch/download/root_v6.18.04.source.tar.gz
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/root/6.18.04 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCLING_CXX_PATH=clang++ -DCMAKE_INSTA
==> make install
Warning: root dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
==> Caveats
Because ROOT depends on several installation-dependent
environment variables to function properly, you should
add the following commands to your shell initialization
script (.bashrc/.profile/etc.), or call them directly
before using ROOT.

For bash users:
  . /usr/local/bin/thisroot.sh
For zsh users:
  pushd /usr/local >/dev/null; . bin/thisroot.sh; popd >/dev/null
For csh/tcsh users:
  source /usr/local/bin/thisroot.csh
For fish users:
  . /usr/local/bin/thisroot.fish

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/root
==> Summary
🍺  /usr/local/Cellar/root/6.18.04: 5,220 files, 308.2MB, built in 39 minutes 1 second
```

I don't know how to get the 10.15 tools, deleting them then running `xcode-select --install` installs 10.14 again.

**Comment by henryiii** [comment]
This is interesting, in the formula:

https://github.com/Homebrew/homebrew-core/blob/0346c1eeb8cb25541118e78013f2a2af19fed3de/Formula/root.rb#L47-L48

Can you check the value for you, and/or try changing this with `brew edit root`?

**Comment by ryounsumiko** [comment]
> Can you check the value for you, and/or try changing this with brew edit root?
my $SDKROOT is empty and this line is already there. Hence I don't think this make any difference.

> I don't know how to get the 10.15 tools, deleting them then running xcode-select --install installs 10.14 again.

I did a easy but maybe incorrect way to build with 10.14 sdk:
I soft linked `/Library/Developer/CommandLineTools/MacOS10.14.sdk` to `/Library/Developer/CommandLineTools/MacOS.sdk 1`,  which looks like a backup of 10.14 sdk.
As a result, I got:
$ xcrun --show-sdk-version
10.14.5

I proceeded to build root and got the same "signbit" error at different place.
gist-log:
https://gist.github.com/ryounsumiko/fab5fb6f7655f3c0cf46f45e1cf7fddc

**Comment by pcanal** [comment]
See the related https://root-forum.cern.ch/t/error-while-re-compiling-root-with-xcode-11/36133/18

**Comment by pcanal** [comment]
I got the error about signbit until I rebuild from scratch with SDKROOT and -DPYTHON_INCLUDE_DIR:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/python2.7

**Comment by henryiii** [comment]
macOS 10.15 was released today so I'm going to try that (probably will finish downloading and installing after I leave today, so tomorrow). I think mixing OS, CLT, and SDK versions tend to cause issues.

**Comment by ryounsumiko** [comment]
Okay, I reinstalled CLT and successfully built root. FYI, the sdk version I got is 10.14.6, which is different from the backup (10.14.5).
I'd like to wait for a while to upgrade to Catalina so I can't test if it is solely due to 10.15 sdk or mixing versions now.

**Comment by henryiii** [comment]
I'm rebuilding with Catalina, will know if it works tomorrow.

**Comment by ryounsumiko** [comment]
Great. Then I think the issue is solved.
