### ISSUE TITLE
Schismtracker fails to launch on macOS Mojave

### ISSUE THREAD

**Issue by fuzzy76** [Homebrew/homebrew-core#44665]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

```
[fuzzy76@PeAr-MacBook-Pro:~] brew config
HOMEBREW_VERSION: 2.1.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 37714b5ce1e4909d4d61de2af98343c7012f7cd9
Last commit: 5 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4f31187d3624daf191612ef2965a20f34c27a89f
Core tap last commit: 67 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Applications
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.0
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

Schismtracker is broken. It opens a blank window, and the menus doesn't work.

All I do is `brew install schismtracker` followed by `schismtracker`.

I notice that the latest version of schismtracker is distributed as an app, so it should probably be converted to a cask.

**Comment by fuzzy76** [comment]
Closed upstream here: https://github.com/schismtracker/schismtracker/issues/211

**Comment by jonchang** [comment]
> I notice that the latest version of schismtracker is distributed as an app, so it should probably be converted to a cask.

This sounds like a good plan. Upstream's README also suggests that Homebrew builds are unsupported.

Do you think you could open a pull request against Homebrew-cask and and Homebrew-core that does this? Here's [how to add a cask](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md) and [how to add a formula to core](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request).

**Comment by fuzzy76** [comment]
Sorry, I don't have time to get into brewing atm. :-/

**Comment by equal-l2** [comment]
Schism Tracker is now available on cask.

**Comment by equal-l2** [comment]
@jonchang Would you close this, since `scism-tracker` is now moved to cask?
