### ISSUE TITLE
neovim HEAD requires utf8proc

### ISSUE THREAD

**Issue by keltor** [Homebrew/homebrew-core#44701]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Installing neovim --HEAD

- What happened (include command output)

==> make install
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/neovim/HEAD-b1
Last 15 lines from /Users/keltor/Library/Logs/Homebrew/neovim/06.cmake:
    UTF8PROC_INCLUDE_DIR=<not found>
    UTF8PROC_LIBRARY=<not found>

  You may use CMake GUI, cmake -D or ccmake to modify the values.  Delete
  CMakeCache.txt to discard all values and force full re-detection if
  necessary.

Call Stack (most recent call first):
  cmake/FindUTF8PROC.cmake:16 (libfind_process)
  CMakeLists.txt:365 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/neovim-20190929-25392-3ufjb1/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/neovim-20190929-25392-3ufjb1/build/CMakeFiles/CMakeError.log".

READ THIS: https://docs.brew.sh/Troubleshooting

- What you expected to happen

neovim to be installed
- Step-by-step reproduction instructions (by running `brew install` commands)

brew install --HEAD neovim

To fix this, I installed utf8proc and then installed neovim again with success.

https://gist.github.com/keltor/f84fccd5f12c492d47ac2b66bcbe9772 <= brew gist-log neovim

**Comment by jonchang** [comment]
Thanks for your report. Unfortunately Homebrew does not support HEAD builds and relies on its users to contribute fixes where necessary. Please see [this document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) for our general contributing guidelines and [this pull request](https://github.com/Homebrew/homebrew-core/pull/41131) for an example of how you might fix a HEAD build.
