### ISSUE TITLE
mariadb: (re)move data-dir setting from plist to my.cnf

### ISSUE THREAD

**Issue by procodix** [Homebrew/homebrew-core#44717]
In plist "data-dir" parameter is predefined to /usr/local/var...

Problem: Some users prefer the data directory to be at some other place. However we cannot change it in my.cnf, because data-dir as start parameter in plist has precedence. Currently only solution is, to modify plist after every mariadb update and to remove the parameter.

Solution: Remove the parameter, and set data-dir in my.cnf. Thus the normal config-file reading order allows to change the directory permanently as is done in many other services.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by SMillerDev** [comment]
Could you make a pull request that does this?

**Comment by procodix** [comment]
sorry, dont have the repo locally.

**Comment by SMillerDev** [comment]
If you have homebrew you have the repo. But you can also make edits through the github website.

**Comment by procodix** [comment]
done before ;-)

**Comment by iMichka** [comment]
@procodix looks like you never opened the pull request in our repo. Could you have a look please?
