### ISSUE TITLE
Build fails for mldonkey

### ISSUE THREAD

**Issue by lxman** [Homebrew/homebrew-core#4475]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by lxman** [comment]
/usr/local/bin/ocamlc.opt -cc clang  -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/networks/direct_connect  -I src/networks/fasttrack  -I src/networks/fileTP  -I src/networks/bittorrent  -I src/networks/donkey -I +camlp4 -c src/utils/cdk/zip.mli
ocamlopt.opt -inline 10    -I src/utils/extlib  -I src/utils/cdk  -I src/utils/bitstring  -I src/utils/lib  -I src/utils/ocamlrss  -I src/utils/xml-light  -I src/utils/net  -I tools  -I src/daemon/common  -I src/daemon/driver  -I src/utils/mp3tagui  -I src/config/unix  -I src/networks/direct_connect  -I src/networks/fasttrack  -I src/networks/fileTP  -I src/networks/bittorrent  -I src/networks/donkey -I +camlp4 -c src/utils/cdk/zip.ml
File "src/utils/cdk/zip.ml", line 30, characters 10-23:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "src/utils/cdk/zip.ml", line 75, characters 10-15:
Error: Multiple definition of the extension constructor name Error.
       Names must be unique in a given structure or signature.
make: *** [src/utils/cdk/zip.cmx] Error 2

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by lxman** [comment]
Yeah, sorry, left out:

https://gist.github.com/c6588f6f0155a790c8467f9a73986a79 and 10.12

**Comment by MikeMcQuaid** [comment]
It may well be your `brew doctor` warnings; I recommend removing those files.

**Comment by lxman** [comment]
Yeah, was pretty sure that was a red herring, but pulled them out anyway.

Output from brew doctor is now this.

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Build output still results in:

File "src/utils/cdk/zip.ml", line 75, characters 10-15:
Error: Multiple definition of the extension constructor name Error.
       Names must be unique in a given structure or signature.
make: *** [src/utils/cdk/zip.cmx] Error 2

https://gist.github.com/89d71a2d20afc6c13c7046d290322bf5

Going to put my files back now . . .

**Comment by MikeMcQuaid** [comment]
Thanks for trying anyway ❤️

**Comment by dunn** [comment]
Could you try compiling outside of Homebrew, and see if it still happens?

**Comment by lxman** [comment]
As a matter of fact, I do have a devel system set up, and I have tried compile, and after ./configure and make, the exact same error occurs.

For the sake of comparison, one might reference another fellow's recent experience here:

https://mail-index.netbsd.org/pkgsrc-bugs/2016/08/08/msg060125.html

Though I have mastered a number of other languages over my time, OCaml is not one of them yet, so I do not have an answer, but my conclusion at this point is that this is definitely a bug in the OCaml code that needs to be fixed. I am researching and if I manage a solution I will post back.

**Comment by ilovezfs** [comment]
@lxman it's fixed in this "unofficial mirror" (see http://mldonkey.sourceforge.net/Download)
```
diff --git a/Formula/mldonkey.rb b/Formula/mldonkey.rb
index b79b0cb..5aadb7d 100644
--- a/Formula/mldonkey.rb
+++ b/Formula/mldonkey.rb
@@ -3,6 +3,7 @@ class Mldonkey < Formula
   homepage "http://mldonkey.sourceforge.net/Main_Page"
   url "https://downloads.sourceforge.net/project/mldonkey/mldonkey/3.1.5/mldonkey-3.1.5.tar.bz2"
   sha256 "74f9d4bcc72356aa28d0812767ef5b9daa03efc5d1ddabf56447dc04969911cb"
+  head "https://github.com/ygrek/mldonkey.git", :branch => "next"
 
   bottle do
     sha256 "7f635c25dd8a70b579ad8876f5101ddc0255b009116f9f2d855ec97981eb9d52" => :el_capitan
@@ -11,13 +12,7 @@ class Mldonkey < Formula
     sha256 "43647a2a802978b9e6dcab2a42f4883cd679e151ed8a9775a1ceb82fa993384f" => :mountain_lion
   end
 
-  # Fix a comment that causes an error in recent ocaml;
-  # fixed upstream, will be in the next release.
-  patch do
-    url "https://github.com/ygrek/mldonkey/commit/c91a78896526640a301f5a9eeab8b698923e285c.patch"
-    sha256 "1fb503d37eed92390eb891878a9e6d69b778bd2f1d40b9845d18aa3002f3d739"
-  end
-
+  depends_on "autoconf" => :build
   depends_on "camlp4" => :build
   depends_on "ocaml" => :build
   depends_on "pkg-config" => :build
```

**Comment by lxman** [comment]
I'll wait for the next build then. Thank you.

**Comment by ilovezfs** [comment]
you're welcome :)
```
brew install -dv --HEAD mldonkey
```
if you want to use the diff above.

**Comment by ilovezfs** [comment]
@lxman This is fixed by https://github.com/Homebrew/homebrew-core/pull/4711.

**Comment by ilovezfs** [comment]
@lxman #4711 has shipped

https://github.com/Homebrew/homebrew-core/commit/1d0941345c9efdb788974d7a24ca0826500b1f74
https://github.com/Homebrew/homebrew-core/commit/1585a6890b00fb29ea6361ad106a19d71a07d8af

so you can `brew update` and it should work now.

**Comment by lxman** [comment]
And so it does  :)
