### ISSUE TITLE
opensc symlinks to library problematic

### ISSUE THREAD

**Issue by huntermatthews** [Homebrew/homebrew-core#44786]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x ] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
Attempting to use the opensc brew formula with a supported smartcard in OSX high sierra to ssh with the smartcards provided key.

Core issue is that while the brew install opensc WORKS, it puts a symlink and not the library itself in /usr/local/lib. 

This is an "interaction" bug and not a brew bug per se:
brew install opensc puts symlinks in /usr/local/lib  -- and while /usr/local/lib is a whitelisted directory in openssh  the agent specifically does not allow symlinks.

This is documented in opensc bug #1008,
https://github.com/OpenSC/OpenSC/issues/1008

which helpfully links to the openssh release notes which noted the change:
http://www.openssh.com/txt/release-7.4

I'm perfectly aware that brew creates symlinks here by design - I hesitated to even file this bug against brew. But a) Perhaps the bug report itself will help others see the problem (even if you guys close it as "NOTABUG" which I'd totally understand) b) perhaps there is a way to make this work in brew world - I'm a brew USER - not an expert at all.

I apologize if this is a known issue. I did search and did not find this issue in the brew bug reports.

- What you were trying to do (and why)
Use brew installed opensc to enable smartcard ssh / ssh-agent support

- What happened (include command output)
> ssh-add -s /usr/local/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11:
Could not add card "/usr/local/lib/opensc-pkcs11.so": agent refused operation

- What you expected to happen
If I replace the symlink to opensc-pkcs11.so with a simple copy:
> cd /usr/local/lib
> rm opensc-pkcs11.so
> cp ../Cellar/opensc/0.19.0_1/lib/opensc-pkcs11.so .
> ssh-add -s /usr/local/lib/opensc-pkcs11.so
Enter passphrase for PKCS#11:
Card added: /usr/local/lib/opensc-pkcs11.so

- Step-by-step reproduction instructions (by running `brew install` commands)

1.

**Comment by SMillerDev** [comment]
Is there any configuration that could be done to allow symlinks? If there is weer should just make that the default.

**Comment by huntermatthews** [comment]
https://man.openbsd.org/ssh-agent
 -P (the relevant option here) only appears to add /change dirs - not allow/disallow symlinks.

From the relevant release notes: (http://www.openssh.com/txt/release-7.4)
 * ssh-agent will refuse to load PKCS#11 modules outside a whitelist
   of trusted paths by default. The path whitelist may be specified
   at run-time.

I don't see any wiggle room for allowing symlinks. Is the opposite possible? Tell brew that for this formula (and specifically this one file) use a cp/hardlink rather than a symlink?

**Comment by SMillerDev** [comment]
Using symlinks is such an integral part of homebrew that I doubt this would be feasible.

**Comment by MikeMcQuaid** [comment]
> Using symlinks is such an integral part of homebrew that I doubt this would be feasible.

Yup, sorry.
