### ISSUE TITLE
formula "duplicity" 0.8.03 does not include "paramiko" library (required for SFTP) macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by colini** [Homebrew/homebrew-core#44783]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
No output from `brew gist-logs duplicity`
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
https://gist.github.com/colini/95f7b8b020555f6efc34ef015171256c

To help us debug your issue please explain:

- What you were trying to do (and why)
Formula "duplicity" 0.8.03 installs correctly and runs.  But if you attempt to backup via SFTP it fails because the required pypi library "paramiko" is not installed by the formula.

- What happened (include command output)
duplicity installs and runs successfully, but since the formula does not include the paramiko dependency, you cannot backup via SFTP.  See below for steps to reproduce.

- What you expected to happen
I expect duplicity to be able to backup via SFTP.  Or add an option flag to the formula to include paramiko.

- Step-by-step reproduction instructions (by running `brew install` commands)
~ $ brew install duplicity
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://homebrew.bintray.com/bottles/duplicity-0.8.03.sierra.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/1d65afdc1aebb5b3649591def2664b51687e68a69754abaed6b8ee1b2a0e4ea3--duplicity-0.8.03.sierra.bottle.tar.gz
==> Pouring duplicity-0.8.03.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/duplicity/0.8.03: 1,044 files, 11MB

~ $ duplicity --verbosity 8 ~ sftp://example.com/backups
Using archive dir: /Users/user/.cache/duplicity/a723146404b98358ec19e2c2517bbaae
Using backup name: a723146404b98358ec19e2c2517bbaae
Import of duplicity.backends.adbackend Succeeded
Import of duplicity.backends.azurebackend Succeeded
Import of duplicity.backends.b2backend Succeeded
Import of duplicity.backends.botobackend Succeeded
Import of duplicity.backends.cfbackend Succeeded
Import of duplicity.backends.dpbxbackend Succeeded
Import of duplicity.backends.gdocsbackend Succeeded
Import of duplicity.backends.giobackend Succeeded
Import of duplicity.backends.hsibackend Succeeded
Import of duplicity.backends.hubicbackend Succeeded
Import of duplicity.backends.imapbackend Succeeded
Import of duplicity.backends.jottacloudbackend Succeeded
Import of duplicity.backends.lftpbackend Succeeded
Import of duplicity.backends.localbackend Succeeded
Import of duplicity.backends.mediafirebackend Succeeded
Import of duplicity.backends.megabackend Succeeded
Import of duplicity.backends.multibackend Succeeded
Import of duplicity.backends.ncftpbackend Succeeded
Import of duplicity.backends.onedrivebackend Succeeded
Import of duplicity.backends.par2backend Succeeded
Import of duplicity.backends.pcabackend Succeeded
Import of duplicity.backends.pydrivebackend Succeeded
Import of duplicity.backends.rsyncbackend Succeeded
Import of duplicity.backends.ssh_paramiko_backend Succeeded
Import of duplicity.backends.ssh_pexpect_backend Succeeded
Import of duplicity.backends.swiftbackend Succeeded
Import of duplicity.backends.sxbackend Succeeded
Import of duplicity.backends.tahoebackend Succeeded
Import of duplicity.backends.webdavbackend Succeeded
Using temporary directory /var/folders/5w/vydk493s747f327twkqjprhw0000gr/T/duplicity-me4_bj9g-tempdir
Backend error detail: Traceback (innermost last):
  File "/usr/local/bin/duplicity", line 101, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 87, in with_tempdir
    fn()
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/dup_main.py", line 1520, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/commandline.py", line 1201, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/commandline.py", line 1072, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/backend.py", line 229, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/Cellar/duplicity/0.8.03/libexec/lib/python3.7/site-packages/duplicity/backend.py", line 217, in get_backend_object
    raise BackendException(_(u"Could not initialize backend: %s") % str(sys.exc_info()[1]))
 duplicity.errors.BackendException: Could not initialize backend: No module named 'paramiko'

**BackendException: Could not initialize backend: No module named 'paramiko'**

**As a workaround:**
Since duplicity is installed into a virtual environment, it's possible to workaround by installing paramiko manually:
~ $ source /usr/local/Cellar/duplicity/0.8.03/libexec/bin/activate
(libexec) ~ $ pip install paramiko
Collecting paramiko
<... snip ...>
Successfully installed asn1crypto-0.24.0 bcrypt-3.1.7 cffi-1.12.3 cryptography-2.7 paramiko-2.6.0 pycparser-2.19 pynacl-1.3.0
(libexec) ~ $ deactivate

It is now possible to backup using SFTP.

Gist of my config: https://gist.github.com/colini/95f7b8b020555f6efc34ef015171256c

**Comment by kendfinger** [comment]
I am working on a PR for this now. I am also adding Backblaze B2 support.
