### ISSUE TITLE
Remove pbrt

### ISSUE THREAD

**Issue by qaisjp** [Homebrew/homebrew-core#44781]
The [`pbrt`](https://github.com/Homebrew/homebrew-core/blob/7125239f9e6d9771e217fddedc7d79eb2d360b74/Formula/pbrt.rb) formula currently refers to v2 (https://github.com/mmp/pbrt-v2) rather than the latest v3 (https://github.com/mmp/pbrt-v3).

It does not look binaries are available anywhere, https://www.pbrt.org/users-guide.html.

The v3 repo does not tag releases and so in similar fashion to #38389, it should be removed.

I am happy to provide a pull request for this.

**Comment by qaisjp** [comment]
edited

**Comment by SMillerDev** [comment]
Please make a pull request. The issue template also mentions this.

> To get software added or changed in Homebrew please file a Pull Request

**Comment by qaisjp** [comment]
Alright. Will do. Just wanted to propose it first and gauge whether such a change would be approved.
