### ISSUE TITLE
Error: git: Unsupported special dependency :perl

### ISSUE THREAD

**Issue by ngtuna** [Homebrew/homebrew-core#44844]
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? -> tried with no luck.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs vim
Error: vim: Unsupported special dependency :python
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.1.11-163-g62f5e8f
ORIGIN: https://github.com/Homebrew/brew
HEAD: 62f5e8f6114ded9c9928f57229da6a9b4829eb13
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c6030ebaed278384bc5474e899ddaa910e01a492
Core tap last commit: 1 year, 9 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 9.0 build 900
Git: 2.10.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_112
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A
```

To help us debug your issue please explain:

- What you were trying to do (and why)
Upgrade vim

- What happened (include command output)
```
 $ brew update
Already up-to-date.
 $ brew uninstall vim
Error: No such keg: /usr/local/Cellar/vim
 $ brew install vim
Updating Homebrew...
Error: vim: Unsupported special dependency :python
 $ brew update
Already up-to-date.
 $ brew doctor

Warning: Some installed formulae are not readable:
  asciinema: Unsupported special dependency :python3
  aspcud: "cxx14" is not a recognized standard
  azure-cli: Unsupported special dependency :python3
  clingo: "cxx14" is not a recognized standard
  git: Unsupported special dependency :perl
  go: unknown version :mountain_lion
  clingo: "cxx14" is not a recognized standard
  jsonnet: "cxx11" is not a recognized standard
  mercurial: Unsupported special dependency :python
  mongodb: unknown version :mountain_lion
  opam: "cxx11" is not a recognized standard
Error: git: Unsupported special dependency :perl
```
- What you expected to happen
`brew doctor` works fine.
`brew install vim` works fine.

- Step-by-step reproduction instructions (by running `brew install` commands)
I dont know if this happens on others machine.

**Comment by fxcoudert** [comment]
```
 $ brew update
Already up-to-date.
```

but:

> `Core tap last commit: 1 year, 9 months ago`

There is a problem, your homebrew-core tap is not being updated. Try `brew update-reset`:

```
   update-reset [repository]
       Fetch  and  reset  Homebrew and all tap repositories (or any specified repository) using git(1) to their latest
       origin/master.

       Note: this will destroy all your uncommitted or committed changes.
```

**Comment by ngtuna** [comment]
That works. Thanks for your quick support and sorry for my late response :-)
