### ISSUE TITLE
imapsync fails up-to-date check (1.921 vs. 1.945)

### ISSUE THREAD

**Issue by PeterSommerlad** [Homebrew/homebrew-core#44854]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
I was installing and running imapsync. It works, but fails its built-in up-to-date-test

- What happened (include command output)

```
This imapsync is not up to date. ( local 1.921 < official 1.945 )( Use --noreleasecheck to avoid this release check. )

```

- What you expected to happen

The most recent version of imapsync should be available.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew update
$ brew upgrade
$ brew install imapsync
$ imapsync
...
Here is imapsync 1.921 on host MacBook-Pro-2, a darwin system with 2.8/2.9 free GiB of RAM
with Perl 5.18.4 and Mail::IMAPClient 3.42
$Id: imapsync,v 1.921 2019/02/18 10:21:03 gilles Exp gilles $
This imapsync is not up to date. ( local 1.921 < official 1.945 )( Use --noreleasecheck to avoid this release check. )
Homepage: https://imapsync.lamiral.info/
```

**Comment by SMillerDev** [comment]
The fix is very easy and documented here: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula

You could be the hero that fixes this for all users of homebrew 😊

**Comment by PeterSommerlad** [comment]
I tried, but as a newbie to maintaining formulas, I have no idea how to cross the initial hickup:

```
$ brew bump-formula-pr --url "https://imapsync.lamiral.info/dist2/imapsync-1
.945.tgz" --sha256 "38c8bceea28ff9a4f533d67e945ef5c0025d81a1d312239c17f38234971ce529" -n -v imapsync
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.8M  100 13.8M    0     0  5948k      0  0:00:02  0:00:02 --:--:-- 5949k
Error: imapsync-1.945.tgz: /Users/XXXX/Library/Caches/Homebrew/Formula/imapsync-1.945.tgz:1: Invalid char `\x1F' in expression
/Users/XXXX/Library/Caches/Homebrew/Formula/imapsync-1.945.tgz:1: invalid multibyte char (UTF-8)

```

Any help?

**Comment by fxcoudert** [comment]
@PeterSommerlad the command would be `brew bump-formula-prl --url=https://imapsync.lamiral.info/dist2/imapsync-1.xxx.tgz imapsync`

**Comment by basictheprogram** [comment]
I think this should be re-opened or a new issue opened. I can duplicate the error. This behavior.
```
$ brew bump-formula-pr --url "https://imapsync.lamiral.info/dist2/imapsync-1.945.tgz"
```
```
Updating Homebrew...
==> Auto-updated Homebrew!
<snip>
==> Updated Formulae
<snip>
Error: imapsync-1.945.tgz: /Users/tanner/Library/Caches/Homebrew/Formula/imapsync-1.945.tgz:1: Invalid char `\x1F' in expression
```
