### ISSUE TITLE
LaTeXML Can't locate XML/LibXML.pm in @INC

### ISSUE THREAD

**Issue by CAMOBAP795** [Homebrew/homebrew-core#44950]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Brew logs

<details>
<summary>brew gist-logs latexml</summary>
<p>

```text
Error: No logs.
```

</p>
</details>

<details>
<summary>brew config</summary>
<p>

```text
HOMEBREW_VERSION: 2.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7e0eaae2bd6600500c961ac342b5d817b25b571
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8c3fce5c8a8ff1f90bd37f2c0a6b993b775c0ca0
Core tap last commit: 77 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13-zulu-13.27+9, 12.0.2-zulu-12.3+11, 11.0.4-zulu-11.33+15, 1.8.0_222-zulu-8.40.0.25, 1.7.0_232-zulu-7.31.0.5
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 10.3
CLT headers: 10.3.0.0.1.1562985497
```

</p>
</details>

<details>
<summary>brew doctor</summary>
<p>

```text
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/share/man/man1/prj2make.1
```

</p>
</details>

### What you were trying to do (and why)

`brew install latexml`

### What happened (include command output)

`brew install latexml` finished successfully

```
==> Downloading https://homebrew.bintray.com/bottles/latexml-0.8.4.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/e7/e7c78acf6bb580fdb949777719972a806c1d7d349d9e826b338572bedde6cf5c?__gda__=exp=1570398229~hmac=5dbbb40407c07f4e3eb78cab884810a56a725ec2d79eb27ff028ebdfdebecfc3&response-content-disposition=attachment%3Bfilename%3D%22latexml-0.8.4.mojave.bottle.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX1_CEWPBp0KQPAg2ZCbhTNvB3Mq12VGHPvlx0nKMa3NHZDA195wixK1gsEMNMdUeBzcUsoo_v9bJ9CQZ8aRVJVWSoIEYjOtg62LklC2DKEJPfj3bch2AHm97oaUW1itAFDdRcZK85i7veg&response-X-Checksum-Sha1=228330c7fced65319a0be912b4cb64bbebc62b4e&response-X-Checksum-Sha2=e7c78acf6bb580fdb949777719972a806c1d7d349d9e826b338572bedde6cf5c
==> Pouring latexml-0.8.4.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/latexml/0.8.4: 970 files, 9.7MB
```

But `latexml --VERSION` doesn't work

```
Can't locate XML/LibXML.pm in @INC (you may need to install the XML::LibXML module) (@INC contains: /usr/local/Cellar/latexml/0.8.4/libexec/bin/../lib /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/darwin-thread-multi-2level /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5 /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0 /usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0 /usr/local/lib/perl5/site_perl/5.30.0/darwin-thread-multi-2level /usr/local/lib/perl5/site_perl/5.30.0) at /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/LaTeXML/Common/Object.pm line 16.
BEGIN failed--compilation aborted at /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/LaTeXML/Common/Object.pm line 16.
Compilation failed in require at /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/LaTeXML/Common/Error.pm line 16.
BEGIN failed--compilation aborted at /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/LaTeXML/Common/Error.pm line 16.
Compilation failed in require at /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/LaTeXML/Core.pm line 18.
BEGIN failed--compilation aborted at /usr/local/Cellar/latexml/0.8.4/libexec/lib/perl5/LaTeXML/Core.pm line 18.
Compilation failed in require at /usr/local/Cellar/latexml/0.8.4/libexec/bin/latexml line 19.
latexml --VERSION always return 1
```

### What you expected to happen

`latexml --VERSION` should print actual version

### Step-by-step reproduction instructions (by running `brew install` commands)

 - `brew install latexml`
 - `latexml --VERSION`

**Comment by jonchang** [comment]
Do you have brewed perl installed? Does it still error if you run `brew unlink perl && latexml --VERSION`?

**Comment by iMichka** [comment]
No response since Oct. 7. I'll close this issue, we can reopen this later if the asked questions have been answered.
