### ISSUE TITLE
Incorrect warning on official Catalina release

### ISSUE THREAD

**Issue by dougaitken** [Homebrew/homebrew-core#44988]
Maybe related to #44776? 

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

I run `brew update` and `brew upgrade` regularly to ensure everything is up to date.

Looks like I did that too early today.

- What happened (include command output)

`brew upgrade`

> Warning: You are using macOS 10.15.
> We do not provide support for this pre-release version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub, Discourse, Twitter or IRC. You are responsible for resolving any issues you experience while you are running this pre-release version.

`brew config` output:

<details>
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7e0eaae2bd6600500c961ac342b5d817b25b571
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cc9af791ee7bde9f4c0d0f42829823ef6632a800
Core tap last commit: 12 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15-x86_64
CLT: N/A
Xcode: 11.0
</details>

- What you expected to happen

Not to be told I'm on a pre-release build? 

- Step-by-step reproduction instructions (by running `brew install` commands)

* Update to macOS Catalina
* Open terminal
* Type `brew upgrade`
* Hit return

**Comment by jonchang** [comment]
There is already an open pull request for this: https://github.com/Homebrew/brew/pull/6500

**Comment by dougaitken** [comment]
Thanks @jonchang - to explain, I was confused about the different repos and didn't look in https://github.com/Homebrew/brew as it was a core issue rather than something else.
