### ISSUE TITLE
MacVim + Catalina errors

### ISSUE THREAD

**Issue by 9mm** [Homebrew/homebrew-core#44995]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 2.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7e0eaae2bd6600500c961ac342b5d817b25b571
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 108901e01853adf472516ffc9f76c74327b53780
Core tap last commit: 36 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_202
macOS: 10.15-x86_64
CLT: N/A
Xcode: 11.1
```

```

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  vim

Warning: You are using macOS 10.15.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.


Warning: Ruby version 2.6.3 is unsupported on 10.15. Homebrew
is developed and tested on Ruby 2.3.7, and may not work correctly
on other Rubies. Patches are accepted as long as they don't cause breakage
on supported Rubies.
```

To help us debug your issue please explain:

- What you were trying to do (and why)

Install `macvim`, either from scratch (with `brew uninstall` and `brew clean`) or restall with `brew reinstall -s macvim`)

- What happened (include command output)

```
brew install -s macvim

==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-157.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapshot-157
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: dbe7f4b19231989bb24f1e3e42f1372451974d8a224ba17498a103c325635e0a
  Actual: 6447bce4ec7b7f67327da8f7b2e9d4f4b748c1afb90f781fecb6b4a3f54cf0a0
 Archive: /Users/9mm/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
To retry an incomplete download, remove the file above.
```

- What you expected to happen

It to work without error

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install -s macvim` or `brew reinstall -s macvim`

**Comment by SMillerDev** [comment]
That's not a Catalina issue. That's a situation where upstream retagged something. Please ask the macvim developers if this change was intentional.

**Comment by bmulholland** [comment]
Does seem like an issue for the formula maintainer but the devs are working around it: https://github.com/macvim-dev/macvim/issues/934

**Comment by SMillerDev** [comment]
Homebrew doesn't have formula maintainers. All of the community maintains all of the formulae. Seeing that upstream issue, you could also make a pull request to change the checksum and fix it for everyone.

**Comment by bmulholland** [comment]
@SMillerDev Cool, didn't know that. Next time I'll do a PR. Thanks!
