### ISSUE TITLE
mariadb: Unable to login as root after installing

### ISSUE THREAD

**Issue by MrBlueSkies** [Homebrew/homebrew-core#45003]
I installed mariadb via brew, and right after install I am unable to login as "root".

> computer:~ USER$ brew doctor
Your system is ready to brew.
computer:~ USER$ brew update && brew upgrade
Already up-to-date.
computer:~ USER$ ls -la /Library/LaunchDaemons/homebrew*
-rw-r--r--  1 root  admin  447  7 Lok 22:09 /Library/LaunchDaemons/homebrew.mxcl.httpd.plist
computer:~ USER$ ls -la /Library/LaunchAgents/homebrew*
ls: /Library/LaunchAgents/homebrew*: No such file or directory
computer:~ USER$ ls -la ./Library/LaunchAgents/homebrew*
-rw-r--r--  1 USER  staff  447  6 Lok 15:15 ./Library/LaunchAgents/homebrew.mxcl.httpd.plist
computer:~ USER$ ls -la /etc/init.d/mysql
ls: /etc/init.d/mysql: No such file or directory
computer:~ USER$ ls -la /usr/local/etc/init.d/mysql
ls: /usr/local/etc/init.d/mysql: No such file or directory
computer:~ USER$ ls -la /usr/local/var/mysql
ls: /usr/local/var/mysql: No such file or directory
computer:~ USER$ brew install mariadb
==> Downloading https://homebrew.bintray.com/bottles/mariadb-10.4.6_1.mojave.bottle.tar.gz
Already downloaded: /Users/USER/Library/Caches/Homebrew/downloads/da94d6d110c528b69b9fc1e007fa68a66c6dd403ed332a2f57c98e22780dd44c--mariadb-10.4.6_1.mojave.bottle.tar.gz
==> Pouring mariadb-10.4.6_1.mojave.bottle.tar.gz
==> /usr/local/Cellar/mariadb/10.4.6_1/bin/mysql_install_db --verbose --user=USER --basedir=/usr/local/Cellar/mariadb/10.4.6_1 -
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.
>
>MySQL is configured to only allow connections from localhost by default
>
>To connect:
>    mysql -uroot
>
>To have launchd start mariadb now and restart at login:
  brew services start mariadb
Or, if you don't want/need a background service you can just run:
  mysql.server start
==> Summary
🍺  /usr/local/Cellar/mariadb/10.4.6_1: 745 files, 173.3MB
computer:~ USER$ brew services start mariadb
==> Successfully started `mariadb` (label: homebrew.mxcl.mariadb)
computer:~ USER$ mysql -uroot
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
computer:~ USER$ mysql -uroot -p
ERROR 1698 (28000): Access denied for user 'root'@'localhost'

**Comment by boltomli** [comment]
`sudo MySQL -uroot` works fine for me

**Comment by SMillerDev** [comment]
That's a feature. Read the mariadb releasenotes
