### ISSUE TITLE
Dropbear disregards $PREFIX and looks for keys in system /etc

### ISSUE THREAD

**Issue by fancsali** [Homebrew/homebrew-core#45017]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- Wanted to have a separate, customised ssh environment on my Mac, without interfering with the default ssh.
- Decided to go for dropbear: `brew install dropbear`.
- Which installed version `v2019.78`.
- Tried to run it, which returned:
```
$ dropbear -FE -p6022

[11649] Oct 08 18:05:26 Failed loading /etc/dropbear/dropbear_rsa_host_key
[11649] Oct 08 18:05:26 Failed loading /etc/dropbear/dropbear_dss_host_key
[11649] Oct 08 18:05:26 Failed loading /etc/dropbear/dropbear_ecdsa_host_key
[11649] Oct 08 18:05:26 Early exit: No hostkeys available. 'dropbear -R' may be useful or run dropbearkey.
````

- Expected behaviour is to look for the config and keys in $PREFIX/etc (`/usr/local` in my case).

Output of above commands:
- `brew config`:

```
HOMEBREW_VERSION: 2.1.12-35-g59e3cc7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 59e3cc79903a59172f857285bc0411d10ee68d03
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a035f9f7cbc4de3353b703a250280d5e2e78b064
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_101, 1.7.0_80
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

- `brew doctor`:
Your system is ready to brew.

**Comment by SMillerDev** [comment]
That seems like a problem with dropbear?

**Comment by fancsali** [comment]
Well, I haven't checked the code; but it's either the dropbear code not giving a damn about the $PREFIX or there's something going pear-shaped with the way homebrew injects that value and compiles dropbear.

**Comment by fxcoudert** [comment]
We're configuring by passing both `--prefix=`  and `--sysconfdir=`. These are not taken into account by `dropbear`, apparently: https://github.com/mkj/dropbear/blob/0afcfafbb993c856db65e033569539f66491cc1b/default_options.h#L22
