### ISSUE TITLE
gdb --HEAD compilation fails

### ISSUE THREAD

**Issue by bikeNomad** [Homebrew/homebrew-core#45028]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew-config output:
```
HOMEBREW_VERSION: 2.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a035f9f7cbc4de3353b703a250280d5e2e78b064
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_TEMP: /usr/local/tmp
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1000
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2, 1.8.0_112
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

brew-doctor output:
```
Your system is ready to brew.
```
To help us debug your issue please explain:

- What you were trying to do (and why)

I was trying to `brew install --HEAD gdb` in hopes that it would work on my system.

- What happened (include command output)

```
==> Cloning https://sourceware.org/git/binutils-gdb.git
Updating /Users/ned/Library/Caches/Homebrew/gdb--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 3abea05d9b Remove two unused items from windows-nat.c
==> ./configure --prefix=/usr/local/Cellar/gdb/HEAD-3abea05 --enable-targets=all --with-python=/usr --disable-binutils
==> make
Last 15 lines from /Users/ned/Library/Logs/Homebrew/gdb/02.make:
In file included from ./exceptions.h:23:
./ui-out.h:129:26: error: expected unqualified-id
  tmp.kind = field_kind::STRING;
                         ^
ada-exp.c:125:16: note: expanded from macro 'STRING'
#define STRING 265
               ^
  CXX    ada-valprint.o
  CXX    ada-varobj.o
  CXX    addrmap.o
2 errors generated.
make[2]: *** [ada-exp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-gdb] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting
```

- What you expected to happen

I expected gdb to build and install correctly.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install --HEAD gdb
```

**Comment by iMichka** [comment]
We don't provide support for HEAD builds, only via pull requests. Please open a pull request if you'd like to see this build fixed. `brew` asks you to file a pull request, not an issue.
