### ISSUE TITLE
Qt on macOS Catalina: QWebEngine is missing

### ISSUE THREAD

**Issue by danieleds** [Homebrew/homebrew-core#45027]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [DOES NOT FAIL]
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Logs

<details><summary>brew gist-logs qt</summary>

    Error: No logs.

</details>

<details><summary>brew config</summary>

```
HOMEBREW_VERSION: 2.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a035f9f7cbc4de3353b703a250280d5e2e78b064
Core tap last commit: 13 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13
macOS: 10.15-x86_64
CLT: N/A
Xcode: 11.1
XQuartz: 2.7.11 => /opt/X11
```

</details>

<details><summary>brew doctor</summary>

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/daniele/miniconda3/bin/python3.7-config
  /Users/daniele/miniconda3/bin/xml2-config
  /Users/daniele/miniconda3/bin/python3.7m-config
  /Users/daniele/miniconda3/bin/python3-config
  /Users/daniele/miniconda3/bin/ncursesw6-config
```

</details>

### What you were trying to do (and why)

I need the QtWebEngine library from the Qt package. I am on macOS Catalina.

### What happened (include command output)

`brew install qt` does not show any error, but the QtWebEngine library is not installed.
In fact:

```
$ pkg-config --libs Qt5Core
-F/usr/local/Cellar/qt/5.13.1/lib -framework QtCore
$ pkg-config --libs Qt5WebEngine
Package Qt5WebEngine was not found in the pkg-config search path.
Perhaps you should add the directory containing `Qt5WebEngine.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Qt5WebEngine' found
```

The same version of Qt (5.13.1) **worked fine on macOS Mojave.**

### What you expected to happen

I should be able to find QtWebEngine.

### Step-by-step reproduction instructions (by running `brew install` commands)

* `brew install qt`
* `pkg-config --libs Qt5WebEngine`

**Comment by danieleds** [comment]
Temporary workaround:

    wget https://homebrew.bintray.com/bottles/qt-5.13.1.mojave.bottle.tar.gz
    brew reinstall ./qt-5.13.1.mojave.bottle.tar.gz

(installs bottle for Mojave)

**Comment by fxcoudert** [comment]
We build the same way in Catalina as in Mojave, so I am not sure why Qt5WebEngine would be disabled. Can you report the bug to Qt?

**Comment by fxcoudert** [comment]
I've reported the bug to Qt: https://bugreports.qt.io/browse/QTBUG-79338

**Comment by fxcoudert** [comment]
Somehow, now it doesn't even build anymore: https://bugreports.qt.io/browse/QTBUG-79340

**Comment by fxcoudert** [comment]
Fixed by using upstream patches: https://github.com/Homebrew/homebrew-core/pull/45597
