### ISSUE TITLE
Octave 4.0.3 missing dependencies on lcms and libpng-1.5?

### ISSUE THREAD

**Issue by wobytides** [Homebrew/homebrew-core#4507]
- [y ] Ran `brew update` and retried your prior step?
- [y ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

During `brew install octave` with default options, it complained about not being able to find `-llcms`. I did `brew install lcms` (not lcms2!) and this error was resolved.

Then I tried again, and had a similar error with -libpng15. Unfortunately there's nothing in versions for this. I'm a bit of a novice, so not really sure what to do at this point.

Thanks!
Tom

**Comment by ilovezfs** [comment]
octave is in homebrew/science not homebrew/core. Please reopen this issue over there https://github.com/Homebrew/homebrew-science/
