### ISSUE TITLE
Build failed: nvm

### ISSUE THREAD

**Issue by mbeall** [Homebrew/homebrew-core#4520]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Original error occurred when trying to upgrade nvm. However after removing and trying to install nvm again, I still get the following error.

    Error: undefined local variable or method `shell_profile' for #<Formulary::FormulaNamespace04637aebbac9f42aa8b16bb58c3b99b8::Nvm:0x007f853d9b9c08>
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb:24:in `caveats'
    /usr/local/Library/Homebrew/caveats.rb:12:in `caveats'
    /usr/local/Library/Homebrew/caveats.rb:29:in `empty?'
    /usr/local/Library/Homebrew/formula_installer.rb:484:in `caveats'
    /usr/local/Library/Homebrew/formula_installer.rb:513:in `finish'
    /usr/local/Library/Homebrew/cmd/install.rb:273:in `install_formula'
    /usr/local/Library/Homebrew/cmd/install.rb:150:in `block in install'
    /usr/local/Library/Homebrew/cmd/install.rb:150:in `each'
    /usr/local/Library/Homebrew/cmd/install.rb:150:in `install'
    /usr/local/Library/Homebrew/brew.rb:91:in `<main>'

`brew gist-logs nvm` output: `**Error**: No logs.`

**Comment by justrhysism** [comment]
I do have a result from `gist-logs` for the same issue: https://gist.github.com/justrhysism/e320d7c004ea0df75c134f18f9be3ecd

**Comment by gnawhleinad** [comment]
This will be 🔧 with https://github.com/Homebrew/brew/pull/876.

**Comment by pzrq** [comment]
Looks like this is resolved upstream as @gnawhleinad identified.

After a `brew update && brew uninstall nvm && brew install nvm` and following the Terminal instructions the following no longer triggers, i.e. `nvm` works correctly for me:

```
$ brew install nvm
==> Using the sandbox
==> Downloading https://github.com/creationix/nvm/archive/v0.31.7.tar.gz
==> Downloading from https://codeload.github.com/creationix/nvm/tar.gz/v0.31.7
######################################################################## 100.0%
Error: undefined local variable or method `shell_profile' for #<Formulary::FormulaNamespace04637aebbac9f42aa8b16bb58c3b99b8::Nvm:0x007fcde31a1680>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/nvm.rb:24:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:12:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:29:in `empty?'
/usr/local/Library/Homebrew/formula_installer.rb:484:in `caveats'
/usr/local/Library/Homebrew/formula_installer.rb:513:in `finish'
/usr/local/Library/Homebrew/cmd/install.rb:273:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `install'
/usr/local/Library/Homebrew/brew.rb:91:in `<main>'
```
