### ISSUE TITLE
SBCL 1.5.7 exits with a segmentation fault on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by mnzluca** [Homebrew/homebrew-core#45229]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Logs
<details><summary>brew gist-logs sbcl output</summary>

`Error: No logs.`
</details>

<details><summary>brew config output</summary>

`````
HOMEBREW_VERSION: 2.1.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: aa043c1d678afd26f50156a83417c296cb9d5a4b
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b9b63ef5e275d31b285c83c6b4d83cd1803d58e7
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.1
CLT headers: 11.0.0.0.1.1567737322
XQuartz: 2.7.11 => /opt/X11
`````
</details>

<details>
<summary>  brew doctor output:
</summary>

`Your system is ready to brew.`
</details>

To help us debug your issue please explain:

### What you were trying to do (and why)

Running sbcl from command line in macOS 10.15. The command was successful in macOS 10.14. Performing `brew reinstall sbcl` does not help.

### What happened (include command output)

After starting the program exits with a segmentation fault.

`````
This is SBCL 1.5.7, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
mmap: Operation not permitted
fatal error encountered in SBCL pid 66013(tid 0x732fd40):
Can't allocate 0x8000000 bytes for space 4

Segmentation fault: 11
`````

### What you expected to happen

The sbcl REPL should have started and be ready to accept user input

### Step-by-step reproduction instructions (by running `brew install` commands)

Simply installing sbcl from the bottle `sbcl-1.5.7.mojave.bottle` and trying to run on macOS 10.15 suffices:
`$ brew install sbcl`
`$ sbcl`

**Comment by fxcoudert** [comment]
Can you please report this issue to upstream (the sbcl project)? Right now, it looks like `sbcl` doesn't support Catalina at all. It cannot build from source on Catalina.

**Comment by bitmappergit** [comment]
This is not true. When building sbcl from master source using sbcl 1.5.6 works fine for me. However, sbcl 1.5.7 doesn't work.

**Comment by bitmappergit** [comment]
```
~/sbcl-sbcl > sbcl
This is SBCL 1.5.7.52-fd4972d13, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (format t "hello, world~%")
hello, world
NIL
* %                                                                                                                                                                                 ~/sbcl-sbcl > uname -a
Darwin bitmappers-MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
```

**Comment by SMillerDev** [comment]
If the latest version doesn't work, that means it doesn't work.

**Comment by bitmappergit** [comment]
Sorry, yeah, I was a bit rude in how I said that. The latest release does not work, but the trunk version works fine.

**Comment by SMillerDev** [comment]
That's fine. The question still stands though cause there's not much homebrew can do about it. The fix is mostly to have a release that works.

**Comment by fridayd** [comment]
Actually, homebrew could not include sbcl-1.5.7, but instead stay at 1.5.6.

**Comment by SMillerDev** [comment]
I don't know if there's an official place documenting this. But homebrews policy is "no backsies" when it comes to updates. Upstream should fix their stuff if it's broken. Homebrew shouldn't pick an older version.

**Comment by wahjava** [comment]
Following diff works for `brew install -s sbcl`:

```diff
diff --git a/Formula/sbcl.rb b/Formula/sbcl.rb
index ff4242e..fd1b1fb 100644
--- a/Formula/sbcl.rb
+++ b/Formula/sbcl.rb
@@ -20,6 +20,16 @@ class Sbcl < Formula
     sha256 "7c21c89fd6ec022d4f17670c3253bd33a4ac2784744e4c899c32fbe27203d87e"
   end
 
+  # Fix for SBCL 1.5.7
+  patch :p1 do
+    url "https://github.com/sbcl/sbcl/commit/07d135b0dd4e7c34bc0dce6aac07570d66e297ee.diff"
+    sha256 "41df695b16825705023184d5861cc9e04249ff8c182d188a69297a7a75a3185a"
+  end
+  patch :p1 do
+    url "https://github.com/sbcl/sbcl/commit/5cefb8506b7d8d9a0277236eb3f7e76c4428ac10.diff"
+    sha256 "6e80eb038f7df1fe9e4d3cd72b0a101f254acc0e615bf295db6f2dd2b8dbca5a"
+  end
+
   def install
     # Remove non-ASCII values from environment as they cause build failures
     # More information: https://bugs.gentoo.org/show_bug.cgi?id=174702
```

HTH

**Comment by SMillerDev** [comment]
Could you make a pull request for that? And maybe someone can ask upstream for a release including these fixes regardless?

**Comment by jonchang** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/commit/411c2c5be2fea673f34144cde0ded6195a16ab80
