### ISSUE TITLE
brew install mos 

### ISSUE THREAD

**Issue by t2fi** [Homebrew/homebrew-core#45240]
Hi,

I am installing home-brew mos and I receive this error. Can someone please help?

Mac Sierra 10.13.6

Command was 'brew install mos'

==> Installing mos from cesanta/mos
==> Downloading https://github.com/mongoose-os/mos/archive/b14a864da77d6f3b0b1ad
Already downloaded: /Users/a123/Library/Caches/Homebrew/downloads/ea529fdde558376c595d4703d70ba164011cd3778087b68f36a1a42884545829--mos-b14a864da77d6f3b0b1ad591876b41cf06e70bab.tar.gz
==> Note: Go package cache does not exist, next step may take a long time
==> govendor sync
Last 15 lines from /Users/a123/Library/Logs/Homebrew/mos/01.govendor:
Cloning into '/private/tmp/mos-20191013-1789-yv16p4/mos-b14a864da77d6f3b0b1ad591876b41cf06e70bab/.cache/govendor/github.com/docker/docker'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Remotes failed for:
Failed for "cloud.google.com/go/compute/metadata" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/compute/metadata"
Failed for "cloud.google.com/go/iam" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/iam"
Failed for "cloud.google.com/go/internal/optional" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/internal/optional"
Failed for "cloud.google.com/go/internal/version" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/internal/version"
Failed for "cloud.google.com/go/pubsub" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/pubsub"
Failed for "cloud.google.com/go/pubsub/apiv1" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/pubsub/apiv1"
Failed for "cloud.google.com/go/pubsub/internal/distribution" (failed to ping remote repo): unrecognized import path "cloud.google.com/go/pubsub/internal/distribution"
Failed for "github.com/Microsoft/go-winio" (failed to clone repo): exit status 128

**Comment by dawidd6** [comment]
You already opened the issue where it truly belongs: https://github.com/cesanta/homebrew-mos/issues/5.
