### ISSUE TITLE
Brew Install Nginx with Modsecurity

### ISSUE THREAD

**Issue by vanquishsecurity2** [Homebrew/homebrew-core#45253]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ Yes ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ Yes ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

- [ Yes] ran `brew update` and can still reproduce the problem?
- [ Yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ Gives error] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ Yes
[brew_output_nginx_modsecurity.txt](https://github.com/Homebrew/homebrew-core/files/3721431/brew_output_nginx_modsecurity.txt)
] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why):

https://formulae.brew.sh/formula/nginx
brew install nginx --with-modsecurity
- What happened (include command output):
Help file was outputted with error "Error: invalid option: --with-modsecurity"
- What you expected to happen:
Installed Nginx with Modsecurity 
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install nginx --with-modsecurity

**Comment by vanquishsecurity2** [comment]
Output attached.
[brew_output_nginx_modsecurity.txt](https://github.com/Homebrew/homebrew-core/files/3721432/brew_output_nginx_modsecurity.txt)

**Comment by vanquishsecurity2** [comment]
Who's the genius who came up with removing options? https://github.com/Homebrew/homebrew-core/issues/31510

FYI, Nginx install is not supported on Mac OS X, and my project needs ModSecurity complied with Nginx.

**Comment by fxcoudert** [comment]
> Who's the genius who came up with removing options?

The maintainers who are doing the hard work of maintaining the code base, after extensive discussion and assessment of the situation.

You can use your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap), even share it with others. Or another software distribution channel that is more to your taste.
