### ISSUE TITLE
Error: stack level too deep

### ISSUE THREAD

**Issue by poplarmedia** [Homebrew/homebrew-core#45285]
I received this error after upgrading ffmpeg, x264 and x265 on MacOS Mojave:

`Removing: /usr/local/Cellar/ffmpeg/4.2.1... (287 files, 56.5MB)
Removing: /usr/local/Cellar/x264/r2917... (11 files, 5.9MB)
Removing: /usr/local/Cellar/x265/3.1.2... (11 files, 35.2MB)
Error: stack level too deep
Please report this bug:
  https://docs.brew.sh/Troubleshooting

I ran brew update and brew doctor 2x with no issues.

Sett attached file
[brew-error-mac.txt](https://github.com/Homebrew/homebrew-core/files/3721765/brew-error-mac.txt)

Thanks,
Matt

**Comment by fxcoudert** [comment]
Please file this as an issue in `brew` itself, and be sure to provide the information requested in that template, so we can debug the issue: https://github.com/Homebrew/brew/issues
