### ISSUE TITLE
Incompatible diff in isync recipe

### ISSUE THREAD

**Issue by gpanders** [Homebrew/homebrew-core#45293]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Output of `brew gist-logs isync`:**
```
Error: No logs.
```

**brew config:**
```
HOMEBREW_VERSION: 2.1.13-52-g16d477c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16d477c696153d7bfcca1c6ffe1fecafc3aa54fc
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5612a02239caed4babb6edb7c9f0142ea5a1dcb4
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: vi
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 1.8.0_112
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.1
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

**brew doctor:**
```
﻿Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.7m/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  emacs
```

* * *

When installing `isync` using `brew install --HEAD isync`, I get the following error:
```
==> Cloning https://git.code.sf.net/p/isync/isync.git
Updating /Users/ganders/Library/Caches/Homebrew/isync--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 462fed5 Merge branch '1.3'
==> Patching
patching file configure.ac
Hunk #1 FAILED at 94.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
626
```

Examining the [isync formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/isync.rb) shows the following diff:
```
-    AC_CHECK_LIB(crypto, CRYPTO_lock, [LIBCRYPTO=-lcrypto])
+    AC_CHECK_LIB(crypto, HMAC_Update, [LIBCRYPTO=-lcrypto])
```

However, the source for `isync` (found [here](https://sourceforge.net/p/isync/isync/ci/master/tree/)) has the following instead of `CRYPTO_lock`:
```
    AC_CHECK_LIB(crypto, X509_cmp, [LIBCRYPTO=-lcrypto])
```

This change was made in [8959c6](https://sourceforge.net/p/isync/isync/ci/8959c6b791676a77b6432e5090490730020471e2/) on 2019-09-10.

I think what is happening is that the diff does not apply so the build fails. Modifying the diff in the `isync` formula to use `X509_cmp` instead of `CRYPTO_lock` fixes the error.

**EDIT**: It looks like this only happens when using `brew install --HEAD isync`, since `HEAD` contains the commit that changed the patch, while the most recent tag (`1.3.1`) does not (so the old patch still applies). Instead of trying to apply two different patches (one for `--HEAD` and one without), would it be better to just wait until `isync` releases their next release to update the formula?

**Comment by fxcoudert** [comment]
To fix it, the patch can be scoped inside a `stable do` block, as in the `terminator` formula. We welcome a pull request doing that!
