### ISSUE TITLE
Node builds but fails to symlink on Catalina

### ISSUE THREAD

**Issue by Sasquiche** [Homebrew/homebrew-core#45332]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Attempted to `brew install node`

- What happened (include command output)
Received an error that the 'brew link' step did not complete successfully. 
The formula built, but is not symlinked into /usr/local.
Could not symlink **share/doc/node/gdbinit**
**usr/local/share/doc/node** is not writable.

`brew link node` returns the same error

Also received the warning that the post-install step was not successful.
Ran `brew postinstall node` 
Returns the same error

- What you expected to happen
Previous to Catalina I can't recall ever having an issue installing node through brew. 

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install node`

```
% brew doctor
Your system is ready to brew.
```

```
% brew config
OMEBREW_VERSION: 2.1.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1702e51392fd4afcae2b8c521511e43479a1156
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cdb21523405dfc40347ce31499d0daf880eb8c25
Core tap last commit: 79 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.22.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.2
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
CLT headers: 11.0.0.0.1.1567737322
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
Can you check what the permissions are on those folders? (I'd they even exist)

**Comment by iMichka** [comment]
No response since Oct. 15. I'll close this issue, we can reopen this later if the asked questions have been answered.
