### ISSUE TITLE
How can I trigger auto update for one package

### ISSUE THREAD

**Issue by frostming** [Homebrew/homebrew-core#45343]
I am the maintainer of `legit` and I have publishes some releases in the past month, but I didn't see any updates on the formula.

I would like to know how can I enable the auto update? Is there any error in my formula definition?
https://github.com/Homebrew/homebrew-core/blob/master/Formula/legit.rb

**Comment by SMillerDev** [comment]
There is no auto update. It's all humans.

**Comment by frostming** [comment]
@SMillerDev Thanks for your reply, I saw a bunch of PRs with a simple sentence "Created with brew bump-formula-pr." I thought that was some kind of bots.

**Comment by fxcoudert** [comment]
- `brew bump-formula-pr` is a way to create a pull request with minimal intervention.
- Some projects (like `glooctl`) have PRs created automatically as part of the release process.
