### ISSUE TITLE
`vim` from macvim package can't run on catalina due to linking wrong ruby framework version

### ISSUE THREAD

**Issue by glyph** [Homebrew/homebrew-core#45444]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs macvim
Error: No logs.
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```console
$ brew config
HOMEBREW_VERSION: 2.1.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1702e51392fd4afcae2b8c521511e43479a1156
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f686ae9a7bc69804e4c198213fe829ca0164c82b
Core tap last commit: 7 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13
macOS: 10.15-x86_64
CLT: N/A
Xcode: 11.1
XQuartz: 2.7.11 => /opt/X11
```

```console
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A .pydistutils.cfg file was found in $HOME, which may cause Python
builds to fail. See:
  https://bugs.python.org/issue6138
  https://bugs.python.org/issue4655

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  docker-machine
  python
  gnupg
```

To help us debug your issue please explain:

- What you were trying to do (and why)

run `vim`

- What happened (include command output)

```
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/libruby.2.3.0.dylib
  Referenced from: /usr/local/Cellar/macvim/8.1-157/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
zsh: abort      vim
```

- What you expected to happen

`vim` to start

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install macvim`, `vim` seems to be it

**Comment by glyph** [comment]
I tried to install from source to see if it could build correctly, and got a checksum mismatch:

```
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-157.tar.gz
==> Downloading from https://codeload.github.com/macvim-dev/macvim/tar.gz/snapshot-157
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: dbe7f4b19231989bb24f1e3e42f1372451974d8a224ba17498a103c325635e0a
  Actual: 6447bce4ec7b7f67327da8f7b2e9d4f4b748c1afb90f781fecb6b4a3f54cf0a0
 Archive: /Users/glyph/Library/Caches/Homebrew/downloads/a2bf89c012fe784b3fbbe52088edf84d635cf9d0f81126ded4d56e27cb72429f--macvim-snapshot-157.tar.gz
To retry an incomplete download, remove the file above.
```

Removing the file doesn't help.

**Comment by glyph** [comment]
(Installing with `--HEAD` does work, though.)

**Comment by mvcouwen** [comment]
It is being worked on. It should be solved once #45455 builds and gets merged.

**Comment by mvcouwen** [comment]
Should be solved by PR #45624.

**Comment by fxcoudert** [comment]
Fixed indeed

**Comment by glyph** [comment]
Thanks so much for addressing this!
