### ISSUE TITLE
Built-in PHP server fails to locate includes on Catalina

### ISSUE THREAD

**Issue by djnotes** [Homebrew/homebrew-core#45452]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? **Here's the output of brew doctor**
>Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

>Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config

>Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
- [x] ran `brew gist-logs php` (where `<formula>` is the name of the formula that failed) and included the output link? Yes, https://gist.github.com/djnotes/794fc563d51b0a929981165eab908158 
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)? 
  I am trying to run php's built-in server by running `php -S localhost:8080 .`. 
- What happened (include command output)? 
The server starts but fails to serve php files over the web. Output (on web and server log):  
>HP Warning:  Unknown: failed to open stream: Resource temporarily unavailable in Unknown on line 0
[Thu Oct 17 03:57:20 2019] PHP Fatal error:  Unknown: Failed opening required '.' (include_path='.:/usr/local/Cellar/php/7.3.10/share/php/pear') in Unknown on line 0

- What you expected to happen? Nothing!
- Step-by-step reproduction instructions (by running `brew install` commands)  
1. Open a terminal (on Catalina it is zsh by default).    
2. cd to your php source directory   
3. Run `php -S localhost:8080 .`  
4. Browse http://localhost:8080 with a web browser     

To solve it, I tried removing and reinstalling via brew remove php, brew install php, updating HomeBrew, building from source, using ini_set() in the beginning of my script to give the correct include path; none of them worked.

**Comment by SMillerDev** [comment]
what if you run it in bash?

**Comment by djnotes** [comment]
@SMillerDev with bash the same error occurs.    
Output for bash:   
>mac:computer me$ bash

>The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ php -S 0:8000 .
PHP 7.3.10 Development Server started at Thu Oct 17 06:27:23 2019
Listening on http://0:8000
Document root is /Users/me/src/project
Press Ctrl-C to quit.
[Thu Oct 17 06:27:31 2019] PHP Warning:  Unknown: failed to open stream: Resource temporarily unavailable in Unknown on line 0
[Thu Oct 17 06:27:31 2019] PHP Fatal error:  Unknown: Failed opening required '.' (include_path='.:/usr/local/Cellar/php/7.3.10/share/php/pear') in Unknown on line 0
[Thu Oct 17 06:27:31 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Thu Oct 17 06:27:31 2019] PHP Fatal error:  Unknown: Failed opening required '.' (include_path='.:/usr/local/Cellar/php/7.3.10/share/php/pear') in Unknown on line 0


Weird! Not sure whether this is a HomeBrew issue, because I tried running internal server with a php I have in /usr/bin (which I cannot rm with sudo whatsoever), and got the same error.   
I have been cursing myself for days for upgrading to Catalina :(

**Comment by SMillerDev** [comment]
Then you're calling the wrong php. What does `which php` tell you?

**Comment by djnotes** [comment]
```
mac:computer me$ which php
/usr/local/bin/php
```
/usr/local/bin/php and /usr/local/Cellar/php/7.3.10/bin/php both respond the same to `--version`:  
>PHP 7.3.10 (cli) (built: Sep 30 2019 19:59:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.10, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.10, Copyright (c) 1999-2018, by Zend Technologies

And then, there is `/usr/bin/php --version` that says:   
>PHP 7.3.8 (cli) (built: Aug 24 2019 19:38:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies

Does this mean I have three PHPs on my system? It's confusing. Guess my mac is infested by `php`.

**Comment by djnotes** [comment]
Do you think uninstalling and reinstalling HomeBrew is  helpful?

**Comment by kabel** [comment]
I don't think you're running the program correctly. `php -S localhost:8080 .` means start a built-in server and respond to requests by running a php file named `.`. If you meant `.` to be the document root, you need to use the `-t` or `--docroot` option.
