### ISSUE TITLE
brew update && brew upgrade on macbook

### ISSUE THREAD

**Issue by hkcperry** [Homebrew/homebrew-core#45462]
==> Pouring gedit-3.34.0_1.mojave.bottle.tar.gz
==> /usr/local/opt/glib/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas
==> /usr/local/opt/gtk+3/bin/gtk3-update-icon-cache -qtf /usr/local/share/icons/hicolor
🍺  /usr/local/Cellar/gedit/3.34.0_1: 1,579 files, 14.4MB
Removing: /usr/local/Cellar/gedit/3.32.0... (1,579 files, 14.5MB)
Removing: /usr/local/Cellar/python@2/2.7.16... (3,706 files, 50.6MB)

ran in command line:
brew update && brew upgrade

and ended up with the following error:

Error: undefined method `any?' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:268:in `block (3 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:266:in `select'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:266:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:296:in `block (2 levels) in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:263:in `block in broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cache_store.rb:17:in `use'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:262:in `broken_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:367:in `check_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:114:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

**Comment by fxcoudert** [comment]
Please file the **full** issue template, including output from commands `brew doctor` (should be empty) and `brew config`.
