### ISSUE TITLE
Formulae without Catalina bottles and missing source

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/homebrew-core#45514]
Currently, these formulae are missing their source:

- [x] activemq (downloads and is `bottle :unneeded`)
- [x] aiccu
- [x] akka (downloads and is `bottle :unneeded`)
- [x] alluxio (downloads and is `bottle :unneeded`)
- [x] alure
- [x] apache-ctakes (downloads and is `bottle :unneeded`)
- [x] apache-drill (downloads and is `bottle :unneeded`)
- [x] apache-flink (downloads and is `bottle :unneeded`)
- [x] apache-geode (downloads and is `bottle :unneeded`)
- [x] apache-spark (downloads and is `bottle :unneeded`)
- [x] apache-zeppelin (downloads and is `bottle :unneeded`)
- [x] app-engine-java (downloads and is `bottle :unneeded`)
- [x] app-engine-python (downloads and is `bottle :unneeded`)
- [x] aptly
- [x] arangodb (downloads but needs bottle)
- [x] artifactory (downloads and is `bottle :unneeded`)
- [x] audiofile
- [x] aws-google-auth
- [x] ballerina (downloads and is `bottle :unneeded`)
- [x] bdsup2sub
- [x] beast
- [x] bltool (downloads and is `bottle :unneeded`)
- [x] boost-python@1.59 (downloads but needs bottle)
- [x] bup
- [x] clozure-cl (downloads but needs bottle)
- [x] cmu-pocketsphinx (downloads but needs bottle)
- [x] confluent-platform (downloads and is `bottle :unneeded`)
- [x] cromwell (downloads and is `bottle :unneeded`)
- [x] cuba
- [x] dashing
- [x] dasm
- [x] dbxml (downloads but needs bottle)
- [x] dcal
- [x] debianutils
- [x] dita-ot (downloads and is `bottle :unneeded`)
- [x] druid (downloads and is `bottle :unneeded`)
- [x] dtrx
- [x] efl (downloads but needs bottle)
- [x] elasticsearch (downloads and is `bottle :unneeded`)
- [x] elasticsearch@2.4 (downloads and is `bottle :unneeded`)
- [x] elasticsearch@5.6 (downloads and is `bottle :unneeded`)
- [x] elvish
- [x] embree
- [x] enigma (downloads but needs bottle)
- [x] flume (downloads and is `bottle :unneeded`)
- [x] freedink (downloads but needs bottle)
- [x] freeswitch
- [x] fuseki
- [x] galen (downloads and is `bottle :unneeded`)
- [x] gcc@4.9 (downloads but needs bottle)
- [x] gcc@5 (downloads but needs bottle)
- [x] gcc@6 (downloads but needs bottle)
- [x] gcc@7 (downloads but needs bottle)
- [x] geoserver (downloads and is `bottle :unneeded`)
- [x] ghc@8.2 (downloads but needs bottle)
- [x] gitbucket (downloads and is `bottle :unneeded`)
- [x] glassfish (downloads and is `bottle :unneeded`)
- [x] grails (downloads and is `bottle :unneeded`)
- [x] grakn (downloads and is `bottle :unneeded`)
- [x] graph-tool (downloads but needs bottle)
- [x] gtk-gnutella
- [x] gwt (downloads and is `bottle :unneeded`)
- [x] hapi-fhir-cli (downloads and is `bottle :unneeded`)
- [x] haskell-stack (downloads but needs bottle)
- [x] icon
- [x] imapsync
- [x] ipbt
- [x] jboss-forge (downloads and is `bottle :unneeded`)
- [x] jsvc
- [x] jupyter (downloads but needs bottle)
- [x] kettle (downloads and is `bottle :unneeded`)
- [x] kubernetes-service-catalog-client
- [x] languagetool (downloads and is `bottle :unneeded`)
- [x] ldc (downloads but needs bottle)
- [x] lemon
- [x] liblzf
- [x] libngspice
- [x] libxc
- [x] llvm@6 (downloads but needs bottle)
- [x] llvm@7 (downloads but needs bottle)
- [x] logstash (downloads and is `bottle :unneeded`)
- [x] macvim
- [x] mahout (downloads and is `bottle :unneeded`)
- [x] mariadb@10.2
- [x] mariadb@10.3
- [x] maxwell (downloads and is `bottle :unneeded`)
- [x] mdds
- [x] mecab-unidic-extended (downloads but needs bottle)
- [x] metabase (downloads and is `bottle :unneeded`)
- [x] mobiledevice
- [x] montage (downloads but needs bottle)
- [x] newlisp
- [x] nifi-registry (downloads and is `bottle :unneeded`)
- [x] norm
- [x] nuxeo (downloads and is `bottle :unneeded`)
- [x] otf2bdf
- [x] pachi (downloads but needs bottle)
- [x] pgpool-ii
- [x] pig (downloads and is `bottle :unneeded`)
- [x] plank
- [x] predictionio (downloads and is `bottle :unneeded`)
- [x] presto (downloads and is `bottle :unneeded`)
- [x] psftools
- [x] puzzles
- [x] questdb
- [x] quex
- [x] redpen (downloads and is `bottle :unneeded`)
- [x] rethinkdb (downloads but needs bottle)
- [x] riak
- [x] riemann (downloads and is `bottle :unneeded`)
- [x] rtptools
- [x] signal-cli (@issyl0 - it downloaded fine and is `bottle :unneeded`)
- [x] simutrans (downloads but needs bottle)
- [x] solr (downloads and is `bottle :unneeded`)
- [x] solr@7.7 (downloads and is `bottle :unneeded`)
- [x] sonarqube-lts (downloads and is `bottle :unneeded`)
- [x] spigot
- [x] sshconfigfs
- [x] stanford-corenlp (downloads and is `bottle :unneeded`)
- [x] stanford-ner (downloads and is `bottle :unneeded`)
- [x] stanford-parser (downloads and is `bottle :unneeded`)
- [x] tarantool (downloads but needs bottle)
- [x] tika (downloads and is `bottle :unneeded`)
- [x] titan-server (downloads and is `bottle :unneeded`)
- [x] tomee-jax-rs
- [x] tomee-plume
- [x] tomee-plus (downloads and is `bottle :unneeded`)
- [x] unyaffs
- [x] urweb (downloads but needs bottle)
- [x] walkmod (downloads and is `bottle :unneeded`)
- [x] wesnoth (@issyl0 - seems to work, just a bit slow)
- [x] widelands (downloads but needs bottle)
- [x] wildfly-as (downloads and is `bottle :unneeded`)
- [x] xmount
- [x] xpdf

---

The list was generated using this script:

```bash
#!/usr/bin/env bash

set -euo pipefail

pushd "$(brew --repo homebrew/core)/Formula"

missing_catalina_bottle=( $(grep -R --files-without-match 'catalina' . | sort) )

popd

touch working.txt missing.txt

for formula in ${missing_catalina_bottle[@]}; do
  name="$(basename "${formula}" '.rb')"

  if grep -q "${name}" working.txt missing.txt; then
    continue
  fi

  if brew fetch --build-bottle "${name}"; then
    echo "${name}" >> working.txt
  else
    echo "${name}" >> missing.txt
  fi
done
```

**Comment by InnovativeInventor** [comment]
Macvim not working for me on Catalina.

**Comment by SeekingMeaning** [comment]
Status of remaining items:

- [ ] clozure-cl #50152
- [ ] cuba (awaiting email reply from Thomas Hahn)
- [ ] efl #50161
- [ ] ghc@8.2 #50585
- [x] kubernetes-service-catalog-client
- [x] liblzf
- [x] mobiledevice
- [x] xmount

(This is also a personal checklist so it's easier to see what's left)

**Comment by SeekingMeaning** [comment]
Should `cuba` be removed? I’m waiting for a reply from the author, but should the formula even be maintained anymore? Its stats are 2 installs in the past month, and 72 in the last year, giving it 6 installs per month.

**Comment by SMillerDev** [comment]
Is it broken?

**Comment by SeekingMeaning** [comment]
Other than a checksum change due to a post-release edit, no, it’s not broken. My original pull request #49131 builds successfully but fails audit due to the change.

**Comment by SMillerDev** [comment]
In that case there isn't really a need to remove it.

**Comment by SeekingMeaning** [comment]
liblzf is fixed :tada:

**Comment by iMichka** [comment]
Cool. Looks like all the list is checked now. Thanks to all for the hard work.

We can soon start with the next issue for Big Sur bottles, and it will surely be a lot of fun :)
