### ISSUE TITLE
Rubocop Styling broke Homebrew

### ISSUE THREAD

**Issue by jules2689** [Homebrew/homebrew-core#45531]
Overview
---
This Pull Request seems to have broken Homebrew: https://github.com/KernelPanicAUS/homebrew-core/pull/2306

System
---
This is on my 10.14.6 Mac OS. System ruby is:

```
/.../ ➜ /usr/bin/ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

What is the problem?
---
This is a problem because the PR introduces newer Ruby syntax in https://github.com/Homebrew/homebrew-core/commit/4987fbbe7ce9874607d28a95d4c27b578970d98b

The lack of a `begin` is a problem because that wasnt introduced until Ruby 2.5: https://blog.bigbinary.com/2017/10/24/ruby-2.5-allows-rescue-inside-do-end-blocks.html

Macs ship with Ruby 2.3.x, which is what I suspect Homebrew uses (system ruby)

**Comment by jonchang** [comment]
Homebrew ships its own copy of ruby that it uses internally, which was recently updated to 2.6 in https://github.com/Homebrew/brew/pull/6556. Could you [please fill out the issue template](https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md)? This can be reopened once you do.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by jules2689** [comment]
@jonchang Sorry for not filling it out. For some reason I didn't even register it was there 😓 I've filled it out now taking into account that Homebrew is supposed to be Ruby 2.6.

Thank you for any help!

**Comment by jonchang** [comment]
> HOMEBREW_VERSION: 2.1.13

Something is preventing your Homebrew installation from updating. [The change to 2.6 occurred in v2.1.14](https://github.com/Homebrew/brew/releases/tag/2.1.14)

**Comment by jules2689** [comment]
Do you have suggestions on debugging that?

**Comment by jonchang** [comment]
Yup, that would do it. You can also try `brew update-reset` in the future.
