### ISSUE TITLE
mpg123 1.25.12 - Segfault when playing http stream on 10.15 Catalina

### ISSUE THREAD

**Issue by vom513** [Homebrew/homebrew-core#45535]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Using mpg123 to stream music.

- What happened (include command output)

Segmentation fault:

```
michele@scambox ~ % mpg123 http://necta.burn.net:8000/nectarine
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
	version 1.25.12; written and copyright by Michael Hipp and others
	free software (LGPL) without any warranty but with best wishes

Directory: http://necta.burn.net:8000/

Terminal control enabled, press 'h' for listing of keys and functions.

Playing MPEG stream 1 of 1: nectarine ...
ICY-NAME: Nectarine Demoscene Radio
ICY-URL: https://www.scenestream.net/
zsh: segmentation fault  mpg123 http://necta.burn.net:8000/nectarine

```

- What you expected to happen

Music to play.

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install mpg123
mpg123 http://necta.burn.net:8000/nectarine

I have tried this with other streams, and it segfaults with them as well.  Playing local mp3 files works fine (so I'm assuming it's not an audio issue causing this).  Also - mpg123 1.25.12 from Brew running on my 10.14.latest Mojave box works fine.

My brew config/doctor output is [here](https://gist.github.com/vom513/2e9f6cb5ea251df35004b4223c385ec1)

**Comment by fxcoudert** [comment]
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x00007fff6e73d476 libdyld.dylib`stack_not_16_byte_aligned_error
```

Another stack-checking code generation issue 😭

**Comment by fxcoudert** [comment]
You can run `brew reinstall mpg123` and it will now be fixed.

**Comment by vom513** [comment]
Wow that was fast.  Can confirm this is fixed.  Thanks so much.
