### ISSUE TITLE
Use binary package of bat

### ISSUE THREAD

**Issue by JayceCao** [Homebrew/homebrew-core#45581]
Can we use the binary package of bat (https://github.com/Homebrew/homebrew-core/blob/master/Formula/bat.rb) directly? releases of the official GitHub offers binary package for macOS: https://github.com/sharkdp/bat/releases/download/v0.12.1/bat-v0.12.1-x86_64-apple-darwin.tar.gz

**Comment by fxcoudert** [comment]
Homebrew builds software from source.
