### ISSUE TITLE
'brew install -s guile' crashes on mac os 10.15

### ISSUE THREAD

**Issue by dankegel** [Homebrew/homebrew-core#45602]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software.
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? 
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

To help us debug your issue please explain:

- What you were trying to do (and why)

Install guile from source (to verify it still builds with latest xcode)

- What happened (include command output)

Build aborted; last lines of the log are e.g.

4880 Segmentation fault: 11  | GUILE_AUTO_COMPILE=0
../meta/build-env guild snarf-check-and-output-texi >
guile-procedures.texi
make[3]: *** [guile-procedures.texi] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=37827 for more details, including a stack dump, as this happens even if just building guile without brew.

- What you expected to happen

Build succeeded

- Step-by-step reproduction instructions (by running `brew install` commands)

brew install -s guile

**Comment by SMillerDev** [comment]
This isn't a homebrew issue then.

**Comment by fxcoudert** [comment]
It isn't, but we can work around it. It's the Xcode 11 stack checking bug again…
