### ISSUE TITLE
Qemu hangs and allows no user input on MacOS Catalina

### ISSUE THREAD

**Issue by jos-b** [Homebrew/homebrew-core#45615]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
Trying to use the `qemu-system-x86_64` binary from the `qemu` package. I am trying to run a `.bin` boot sector using Qemu with the following arguments:
```
qemu-system-x86_64 -drive format=raw,file=target/x86_64-freja/debug/bootimage-freja.bin
```
- What happened (include command output)
Nothing, no command output.

The window opens like I would expect, all menu items are present but the window immediately goes into not responding mode and I cannot click anything.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20439493/67163873-3d2eb700-f36c-11e9-99d1-59361ec08b6e.png">

- What you expected to happen
Qemu would start and would be able to run the bin file.
- Step-by-step reproduction instructions (by running `brew install` commands)
It is not required to have a bin file to run, the Qemu binary hangs even when passed no arguments.

Try the following:
```
$ brew install qemu
$ qemu-system-x86_64
```

There is no command output and the window will open and hang immediately.

**Comment by fxcoudert** [comment]
What does `brew test qemu` say on your machine?

**Comment by jos-b** [comment]
@fxcoudert Works fine:
```
joseph@Josephs-MacBook-Air freja % brew test qemu
Testing qemu
==> /usr/local/Cellar/qemu/4.1.0/bin/qemu-system-i386 --version
==> Downloading https://dl.bintray.com/homebrew/mirror/FD12FLOPPY.zip
Already downloaded: /Users/joseph/Library/Caches/Homebrew/downloads/a05ee327a96c5b47e989a49b4c5e226a22949f6e296321f8cbb10f87e366582e--FD12FLOPPY.zip
==> /usr/local/Cellar/qemu/4.1.0/bin/qemu-img info FLOPPY.img
```

**Comment by fxcoudert** [comment]
Is this the same issue as https://github.com/Homebrew/homebrew-core/pull/43315 perchance?

**Comment by jos-b** [comment]
Indeed, that fix does solve this one.

**Comment by fxcoudert** [comment]
Then it's an upstream issue, really 😢
