### ISSUE TITLE
llvm --HEAD must require xcode 

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#4564]
I have
```
$ xcode-select -p
/Library/Developer/CommandLineTools
```
# Please follow the general troubleshooting steps first:

- [*] Ran `brew update` and retried your prior step?
- [*] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:
```
Last 15 lines from /Users/yurikoles/Library/Logs/Homebrew/llvm/01.cmake:
  command.

CMake Warning at tools/xcode-toolchain/CMakeLists.txt:60 (message):
  Failed to detect the version of an installed copy of Xcode, falling back to
  highest supported version.  Set XCODE_VERSION to override.

CMake Error at tools/xcode-toolchain/CMakeLists.txt:80 (message):
  Could not identify toolchain dir

-- Configuring incomplete, errors occurred!
See also "/tmp/llvm-20160906-13025-1s9nevg/CMakeFiles/CMakeOutput.log".
See also "/tmp/llvm-20160906-13025-1s9nevg/CMakeFiles/CMakeError.log".
```
Running `xcode-select -s /Applications/Xcode.app` had resolved issue.

Full log: https://gist.github.com/yurikoles/e0c7a4431d65c4228f2b549fcc2a1470

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by yurikoles** [comment]
I'm not sure may be there is specific option that does require Xcode.

**Comment by MikeMcQuaid** [comment]
What options are you using?

**Comment by yurikoles** [comment]
It seems like `--with-toolchain` causes this problem. I will send a PR in short time, if there is God's Will.

**Comment by DomT4** [comment]
Closing in favour of the PR. Thanks for filing one.
