### ISSUE TITLE
Mac Python bottles do not take into account XCode version.

### ISSUE THREAD

**Issue by arlaneenalra** [Homebrew/homebrew-core#45642]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/adada09b8efa85e64bfdca6c9b8eaa6a

To help us debug your issue please explain:

- What you were trying to do (and why)

Install packages using pip after upgrading XCode to the most recent version.

- What happened (include command output)

pip installs requiring C-code compilation fail. Primarily due to the:

```
python3-config  --cflags
-I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers
```

Note the specific paths referencing locations inside the XCode app.

- What you expected to happen

pip installs should just work.

- Step-by-step reproduction instructions (by running `brew install` commands)

* brew instal python
* run `python3.7-config --cflags`

**Comment by fxcoudert** [comment]
```
CLT: 10.3.0.0.1.1562985497
Xcode: 11.1
```

Probably a very bad idea, having two different versions in CLT and Xcode app.

**Comment by arlaneenalra** [comment]
@fxcoudert That's a reasonable complication... Either CLT 11.1 doesn't exist or I can't download it on our network for some reason I'm unaware of. So I recreated this with a clean system without XCode installed at all. 

The results are similar: https://gist.github.com/arlaneenalra/3577711fc623d145ecffe9bfbee6b7c8

`python3-config` references multiple paths that don't exist when python is installed via the bottle.

On the other hand, if you do a `-s` based install it gives you:
```
copy-of-catalina:Developer testu$ python3.7-config --cflags
-I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers
```
Which references the CommandLineTools path and not anything in XCode. For some reason the python build seems to prefer XCode over the Command Line tools stuff when it builds and records those paths in python3-config for later use, which means the bottles are tied not only to the OS version but also to the XCode and Command Line tools versions.

**Comment by arlaneenalra** [comment]
I had to re-run that a couple of times to prove to my self I hadn't screwed something up:

`brew gist-logs python`:

https://gist.github.com/arlaneenalra/24f42a64c4eb86d30735e9cfd29b1099#file-01-configure-L15-L16

```
CFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers
LDFLAGS=-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
```

And `pyton3-config --cflags --ldflags`:

```
copy-of-catalina:Developer testu$ python3-config --cflags --ldflags
-I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers
-L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -ldl -framework CoreFoundation
```

**Comment by jamiesnape** [comment]
In `/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_sysconfigdata_m_darwin_darwin.py` (for the latest bottle), I am seeing hard-coded paths (configure-time generated, I believe) to the Xcode directory instead of command line tools, which is definitely not what I would expect given `satisfy { MacOS::CLT.installed? }`.

**Comment by scorchio** [comment]
I don't know if this is related, but on a `pip install psutil`, I'm getting 

```
Compiling with an SDK that doesn't seem to exist: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk
```

...on a 10.14 machine which has the command line tools selected (and no Xcode at all).

**Comment by scorchio** [comment]
This is still an issue for me - once I moved to 3.7.6, it broke again. As a workaround I did `brew reinstall python3 --build-from-source`, with that, it's getting configured to use the right SDK... @arlaneenalra have you ran into this again by any chance?

**Comment by arlaneenalra** [comment]
@scorchio I've since upgraded to Catalina and so far that bottle is not exhibiting this issue.
