### ISSUE TITLE
Would it be better to rename osmfilter to osmctools?

### ISSUE THREAD

**Issue by kkdd** [Homebrew/homebrew-core#45664]
Hello,
Would it be better to rename an existing formula ```osmfilter``` to ```osmctools```?  That's because ```brew install osmfilter``` installs [osmctools](https://gitlab.com/osm-c-tools/osmctools), which includes osmfilter, osmconvert and osmupdate commands.

```console
$ brew search osmctools
No formula or cask found for "osmctools".
Closed pull requests:
osmtools 1.0 (new formula) (https://github.com/Homebrew/legacy-homebrew/pull/30308)
```
------------

Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose

To get formulae added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)

If you want to ask a question please do so on our Discourse: https://discourse.brew.sh

We will close issues asking questions or requesting formulae changes without comment.

**Comment by fxcoudert** [comment]
We welcome a pull request to add an alias
