### ISSUE TITLE
install tmux on 10.12

### ISSUE THREAD

**Issue by avelino** [Homebrew/homebrew-core#4568]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd $(brew --repo) && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

avelino@cr69 ~ $ brew install tmux
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for tmux: doxygen, openssl, libevent
==> Installing tmux dependency: doxygen
==> Using the sandbox
==> Downloading https://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.12.src.tar.gz
Already downloaded: /Users/avelino/Library/Caches/Homebrew/doxygen-1.8.12.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/doxygen/1.8.12 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
Last 15 lines from /Users/avelino/Library/Logs/Homebrew/doxygen/01.cmake:
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/Platform/Darwin.cmake:84 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET (10.12) is greater than CMAKE_OSX_SYSROOT SDK:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk

  Please set CMAKE_OSX_DEPLOYMENT_TARGET to 10.11 or lower.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:15 (project)

-- Configuring incomplete, errors occurred!
See also "/tmp/doxygen-20160906-2608-6q3t1r/doxygen-1.8.12/build/CMakeFiles/CMakeOutput.log".

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
avelino@cr69 ~ $

**Comment by dunn** [comment]
> READ THIS: https://git.io/brew-troubleshooting

😉

**Comment by avelino** [comment]
```
avelino@cr69 ~ $ brew update
Already up-to-date.
avelino@cr69 ~ $  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Your Xcode (7.3.1) is outdated
Please update to Xcode 8.0.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/

avelino@cr69 ~ $ xcode-select -v
xcode-select version 2345.
avelino@cr69 ~ $ brew gist-logs tmux
Error: No logs.
```

**Comment by zmwangx** [comment]
> avelino@cr69 ~ $ brew gist-logs tmux
Error: No logs.

Could you please try again?

```
$ brew install tmux; brew gist-logs tmux
```

If still no logs, care to check the directory `~/Library/Logs/Homebrew/tmux`? Thanks.

**Comment by avelino** [comment]
Sorry, in command line not select `xcode 8` change via `xcode-select --switch` and GG

**Comment by zmwangx** [comment]
Glad you resolved this, I should have seen that big warning in doctor's output 🙈 

@DomT4 Any update on [making it a hard fail if people try to brew install stuff with Xcode 7 on 10.12](https://github.com/Homebrew/homebrew-core/issues/1957#issuecomment-243273287)?

**Comment by DomT4** [comment]
I'll try and get around to it tonight/tomorrow/Friday, but I've got some stuff going on in life at the moment that's pretty severely curtailing the amount of time I have for Homebrew. You're welcome to finish off the PR or work on your own if you wish to jump over me.

**Comment by zmwangx** [comment]
@DomT4 No rush!
