### ISSUE TITLE
docker-compose: Abort trap: 6

### ISSUE THREAD

**Issue by LukeCarrier** [Homebrew/homebrew-core#45687]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

In trying to get Docker engine and compose working I ran into a problem executing docker-compose:

```console
% docker-compose --help
Abort trap: 6
```

[Results of a verbose run](https://gist.github.com/LukeCarrier/805dd734c03c62886b5ffee0944aa22c):

```console
/usr/local/Cellar/docker-compose/1.24.1_1/libexec/bin/python3.7 -v /usr/local/bin/docker-compose 2>&1 | tee debug.log
```

This is despite a successful installation:

```console
% brew install docker-compose
==> Downloading https://homebrew.bintray.com/bottles/docker-compose-1.24.1_1.cat
Already downloaded: /Users/lukecarrier/Library/Caches/Homebrew/downloads/42d046903ea48cae86fe1278e38a5effa77e53a00b9f8d331ffeb338bba6e864--docker-compose-1.24.1_1.catalina.bottle.tar.gz
==> Pouring docker-compose-1.24.1_1.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/docker-compose/1.24.1_1: 1,194 files, 13.4MB
```

```console
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
% ls /usr/local/sbin
php-fpm
% brew gist-logs docker-compose
Error: No logs.
% brew config
HOMEBREW_VERSION: 2.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bf8015bc44878d432fb9da4f11e1d8abcef8f32
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 80c190fa2d7b283c857a0e1bfb70a03a9ca11587
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: 11.1
CLT headers: 11.0.0.0.1.1567737322
```

**Comment by fxcoudert** [comment]
Does this still happen if you run `brew reinstall -s docker-compose`?

**Comment by jpmckinney** [comment]
What’s the Crash Report in the Console app say? I was getting abort trap 6 with Salt (also runs Python) and the crash report indicated an issue with libcrypto.

**Comment by slaughter550** [comment]
Encountered the same thing on Catalina using either `zsh` or `bash`
https://gist.github.com/slaughter550/ffa06027b842426a05c19deb17d4a5d1

**Comment by andiradulescu** [comment]
This is connected to openssl. I fixed it by linking libssl.dylib & libcrypto.dylib to /usr/local/lib

`brew install openssl
cd /usr/local/lib
sudo ln -s /usr/local/opt/openssl/lib/libssl.dylib libssl.dylib
sudo ln -s /usr/local/opt/openssl/lib/libcrypto.dylib libcrypto.dylib`

More about it here: https://stackoverflow.com/a/58596931/639708

**Comment by slaughter550** [comment]
That didn't end up helping me unfortunately

```aslaughter@c02yp05ljgh6 lib % brew reinstall -s docker-compose                               
==> Reinstalling docker-compose 
==> Downloading https://github.com/docker/compose/archive/1.24.1.tar.gz
Already downloaded: /Users/aslaughter/Library/Caches/Homebrew/downloads/cbb40814fe26a9662e06040d15eb72705776ed2970eea095df0d9553c0ad8417--compose-1.24.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622bdf/virtualenv-16.7.4.tar.gz
Already downloaded: /Users/aslaughter/Library/Caches/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/docker-compose--homebrew-virtualenv-20191028-60394-zllmug/target --install-scripts=/private/tmp/doc
==> python3 -s /private/tmp/docker-compose--homebrew-virtualenv-20191028-60394-zllmug/target/bin/virtualenv -p python3 /usr/local/Cellar/docker-compose/1.24.1_1/libexec
==> /usr/local/Cellar/docker-compose/1.24.1_1/libexec/bin/pip install -v --no-binary :all: --ignore-installed /private/tmp/docker-compose-20191028-60394-161wylo/compose-1.24.1
Last 15 lines from /Users/aslaughter/Library/Logs/Homebrew/docker-compose/03.pip:
  Removing source in /private/tmp/pip-install-7ua8o0nm/certifi
  Removing source in /private/tmp/pip-install-7ua8o0nm/docker-pycreds
  Removing source in /private/tmp/pip-install-7ua8o0nm/paramiko
  Removing source in /private/tmp/pip-install-7ua8o0nm/pynacl
  Removing source in /private/tmp/pip-install-7ua8o0nm/cffi
  Removing source in /private/tmp/pip-install-7ua8o0nm/pycparser
Removed build tracker '/private/tmp/pip-req-tracker-_pj7pzjy'
ERROR: Could not build wheels for pynacl which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.24.1_1/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/docker-compose/1.24.1_1/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 426, in run
    ", ".join(r.name for r in build_failures)))
pip._internal.exceptions.InstallationError: Could not build wheels for pynacl which use PEP 517 and cannot be installed directly```

**Comment by slaughter550** [comment]
Appears to be related to https://github.com/saltstack/salt/issues/55084 and someone is attempting to fix it https://github.com/Homebrew/homebrew-core/pull/45895

**Comment by Bo98** [comment]
Does this still happen with 1.25, which is now available on Homebrew?

**Comment by mediaessenz** [comment]
> Does this still happen with 1.25, which is now available on Homebrew?

Looks good for me

**Comment by SunMar** [comment]
yes indeed, same for me. before upgrading I removed the workaround (removed the symlinks in /usr/local), and starting seeing the abort again. then I upgraded to 1.25 and the abort is gone :) thnx!
