### ISSUE TITLE
Kustomize fails to install/run properly on MacOs Catalina

### ISSUE THREAD

**Issue by austinchambers** [Homebrew/homebrew-core#45909]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ("Error: no logs." was outputted) ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

*Brew Doctor Output*
[brewErrors.txt](https://github.com/Homebrew/homebrew-core/files/3780367/brewErrors.txt)

*Brew Config Output*
[brewConfig.txt](https://github.com/Homebrew/homebrew-core/files/3780373/brewConfig.txt)

To help us debug your issue please explain:
* Reproduced on a call with two Catalina users. The non-Catalina user did not encounter the issue. 

- What you were trying to do (and why)
Install Kustomize for use with Replicated/Kubernetes

- What happened (include command output)
Installation did not raise errors, but running "kustomize" failed. 
```Austins-MBP-2:rep austin$ brew install kustomize
==> Downloading https://homebrew.bintray.com/bottles/kustomize-3.2.1.catalina.bo
Already downloaded: /Users/austin/Library/Caches/Homebrew/downloads/ae5b92d0f44815a068c031b643e597785fc3cee2e3eb1119b22e124fc42f069a--kustomize-3.2.1.catalina.bottle.tar.gz
==> Pouring kustomize-3.2.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/kustomize/3.2.1: 3 files, 32.7MB
Austins-MBP-2:rep austin$ kustomize
-bash: /usr/local/bin/kustomize: cannot execute binary file```
- What you expected to happen
Kustomize should run. 

- Step-by-step reproduction instructions (by running `brew install` commands)
1. Run ```brew install kustomize``` on MacOs Catalina machine
2. Run ```kustomize```

**Comment by austinchambers** [comment]
Workaround was to manually install Kustomize via: 
```opsys=darwin
curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
  grep browser_download |\
  grep $opsys |\
  cut -d '"' -f 4 |\
  grep /kustomize/v |\
  sort | tail -n 1 |\
  xargs curl -O -L
tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
./kustomize version```

**Comment by fxcoudert** [comment]
Issue due to https://github.com/Homebrew/brew/issues/6539
Catalina bottle temporarily removed in https://github.com/Homebrew/homebrew-core/commit/fcd3cd4d32ead1fba88a46190ca5465deae5e84a
