### ISSUE TITLE
Gtk+-3.0  

### ISSUE THREAD

**Issue by z-ninja** [Homebrew/homebrew-core#45941]
Hi, not sure if this is the right place, but did not find any other better place to report issue.
My program crushing by gtk backend library.
Report shows it crashes on call gdk_quartz_window_set_title -> NSWindow setTitle:
invoked by gtk_widget_show call.
Is anyone have similar situation?

`Process:               nw_mjolnir_loader-mac [3034]
Path:                  /Users/USER/Desktop/*/nw_mjolnir_loader-mac
Identifier:            nw_mjolnir_loader-mac
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [3033]
Responsible:           nw_mjolnir_loader-mac [3034]
User ID:               501

Date/Time:             2019-10-29 15:59:42.313 +0100
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        CEAB88D6-A68D-5084-DE70-7410E407AFBF

Sleep/Wake UUID:       1F868ABE-7151-4E32-B296-D7CBC0784C74

Time Awake Since Boot: 13000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: Invalid parameter not satisfying: aString != nil

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fffb47657bb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffc8ed2a2a objc_exception_throw + 48
2   CoreFoundation                      0x00007fffb476a312 +[NSException raise:format:arguments:] + 98
3   Foundation                          0x00007fffb61bd390 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
4   AppKit                              0x00007fffb23fab9f -[NSWindow setTitle:] + 149
5   libgdk-3.0.dylib                    0x0000000113d376b6 gdk_quartz_window_set_title + 214
6   libgdk-3.0.dylib                    0x0000000113d34b74 _gdk_quartz_display_create_window_impl + 1524
7   libgdk-3.0.dylib                    0x0000000113d10c09 gdk_window_new + 953
8   libgtk-3.0.dylib                    0x0000000113751ecf gtk_window_realize + 1247
9   libgobject-2.0.0.dylib              0x00000001142c4d58 _g_closure_invoke_va + 216
10  libgobject-2.0.0.dylib              0x00000001142db483 g_signal_emit_valist + 1395
11  libgobject-2.0.0.dylib              0x00000001142dbee2 g_signal_emit + 130
12  libgtk-3.0.dylib                    0x000000011372cf3a gtk_widget_realize + 282
13  libgtk-3.0.dylib                    0x0000000113751313 gtk_window_show + 211
14  libgobject-2.0.0.dylib              0x00000001142c4b60 g_closure_invoke + 208
15  libgobject-2.0.0.dylib              0x00000001142da766 signal_emit_unlocked_R + 1270
16  libgobject-2.0.0.dylib              0x00000001142db741 g_signal_emit_valist + 2097
17  libgobject-2.0.0.dylib              0x00000001142dbee2 g_signal_emit + 130
18  libgtk-3.0.dylib                    0x000000011372c727 gtk_widget_show + 247
19  libnw_ui.dylib                      0x0000000112179fc7 _ZN10_nw_window5_showEv + 3399 // instruction is last call of my program before crash.
`
I am using Mac Siera 10.12
Compiling with gcc code::blocks
Homebrew latest stable release, installed yesterday.

**Comment by SMillerDev** [comment]
Sierra isn't supported by Apple or homebrew anymore and the issue doesn't follow the issue template at all, aside from it not being homebrew software. I'm closing this.
