### ISSUE TITLE
terragrunt -- not required terraform

### ISSUE THREAD

**Issue by limakzi** [Homebrew/homebrew-core#46024]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

- I am trying to install `terragrunt` formulae on OSX.

## What happened (include command output)

- `terragrunt` formulae requires `terraform`

<details>
  <summary>Command output</summary>
  <pre>

limakzi-macbook:~ limakzi-root$ brew install terragrunt
Updating Homebrew...
==> Installing dependencies for terragrunt: terraform
==> Installing terragrunt dependency: terraform
Error: Cannot install terraform because conflicting formulae are installed.
  tfenv: because tfenv symlinks terraform binaries

Please `brew unlink tfenv` before continuing.

Unlinking removes a formula's symlinks from /usr/local. You can
link the formula again after the install finishes. You can --force this
install, but the build may fail or cause obscure side effects in the
resulting software.
limakzi-macbook:~ limakzi-root$

  </pre>
</details>

## What you expected to happen

I expect `terragrunt` to install and do not conflict with `tfenv`.
These are two complete separate binaries. `terraform` version can be easily managed with `tfenv`. The conflict with `terragrunt` will happen on _application-level_ when versions will be no compatible.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install tfenv
$ brew install terragrunt
```

**Comment by SMillerDev** [comment]
Does it depend on the existence of a terraform? Then we will make it depend on the terraform formula. Any other dependencies would be error prone and difficult to keep track of.

**Comment by limakzi** [comment]
@SMillerDev Unfortunately, I would disagree.

- Having a `terraform` dependency on `terragrunt`, causes the problem, that user **HAS TO** install specific `terraform` version.
- As `terraform` seems to be problematic because of versions upgrades, teams tend to manage its version in `tfenv` (which is kept in the infrastructure code, per reference [[1]]).  This is a standard procedure among operators.
- `terragrunt` solves different problems than `tfenv`. 
- Having **many** infrastructures or trying to verify the code stability between infrastructures (and `terraform` upgrades), this dependency makes it extremely difficult.
- Last, but not least. Having `terragrunt` installed without `terraform`, by the following procedure:

```
$ brew install tfenv
$ brew unlink tfenv
$ brew install terragrunt
$ brew unlink terraform
``` 

We end up with the following _very clear_ output.
```
/tmp/terraform took 6s 71ms ⇣69% ≫ terragrunt validate-all
[terragrunt] 2019/11/01 07:59:41 Setting download directory for module /tmp/terraform to /tmp/terraform/.terragrunt-cache
[terragrunt] 2019/11/01 07:59:41 Stack at /tmp/terraform:
  => Module /tmp/terraform (excluded: false, dependencies: [])
[terragrunt] [/tmp/terraform] 2019/11/01 07:59:41 Module /tmp/terraform must wait for 0 dependencies to finish
[terragrunt] [/tmp/terraform] 2019/11/01 07:59:41 Running module /tmp/terraform now
[terragrunt] [/tmp/terraform] 2019/11/01 07:59:41 Reading Terragrunt config file at /tmp/terraform/terragrunt.hcl
[terragrunt] [/tmp/terraform] 2019/11/01 07:59:41 Running command: terraform --version
[terragrunt] [/tmp/terraform] 2019/11/01 07:59:41 Module /tmp/terraform has finished with an error: exec: "terraform": executable file not found in $PATH
[terragrunt] 2019/11/01 07:59:41 Encountered the following errors:
exec: "terraform": executable file not found in $PATH
[terragrunt] 2019/11/01 07:59:41 Unable to determine underlying exit code, so Terragrunt will exit with error code 1

/tmp/terraform ⇣69% ≫
```

Your concerns might be very easily addressed with very post-install information, that `terragrunt` formulae does not installs `terraform` and its version has be managed by the user.
(This information is often presented when we speak about `$PATH` modification)
In the end, I accept this of closing issue.

[1]: https://github.com/tfutils/tfenv#min-required

**Comment by SMillerDev** [comment]
You want new installs of software not to throw errors though, no matter how clear they are. You could probably copy the terragrunt formula over to a tap without the dependency though.

**Comment by limakzi** [comment]
@SMillerDev  

-  As I said, I completely understand your perspective, got the purpose. From user experience, you as maintainer, would be blamed for non-working software, every time it does not work, regardless of root-causes. ;-) So, the more smooth installation goes, the better opinions you have, the more users use this product.

- Thank you for the idea of creating separate `tap`; actually this is a good compromise for me. 
I will share it somewhere here.

- What I normally do recently, I create a `docker image` _toolbox_ and we share it between operators. You just run a Docker container and have a completely unified environment completely independent on operating system. (_Offtopic_)

Thank you for your support.
