### ISSUE TITLE
Pango with X11 support

### ISSUE THREAD

**Issue by jtanx** [Homebrew/homebrew-core#4602]
### Formula Requests:

I'd like to build Pango with X11 support. Is it possible to add back optional X11 support like how it's currently done with Cairo?

**Comment by zmwangx** [comment]
If you submit a PR we'd be happy to review (but it's not guaranteed to be merged).

**Comment by zmwangx** [comment]
Oops sorry I replied too soon. If support was removed there probably was a valid reason, and in that case it may be hard to appeal the decision. In this case the reasons are in https://github.com/Homebrew/legacy-homebrew/pull/39868. Plus the fact that we don't really like X11, but if it's optional we may include it, so maybe you could try and open a PR and justify X11 support there.

**Comment by jtanx** [comment]
Yes, I can make a PR. At present, Fontforge's GUI requires X11 support.

**Comment by zmwangx** [comment]
And we don't like GUI stuff in core, not even optional 😃 

There's a cask for GUI Fontforge: `brew cask install fontforge`.

**Comment by jtanx** [comment]
Nonetheless, this is more so that I can build the GUI in Fontforge's CI process.

**Comment by zmwangx** [comment]
I see.

**Comment by ilovezfs** [comment]
you could just stick it in a tap

**Comment by DomT4** [comment]
Closing in favour of the PR.
