### ISSUE TITLE
Installed the latest neomutt HEAD - neovim not found

### ISSUE THREAD

**Issue by andreas-bulling** [Homebrew/homebrew-core#46036]
Hi,

I had a working setup but after installing the latest HEAD version of neomutt I can't edit any messages in neomutt anymore but see the following error message on the console:

`sh: ../Cellar/neovim/HEAD-efaf473/bin/nvim: No such file or directory`

Any ideas what could cause this?

**UPDATE**
If I change dir to `/usr/local/Cellar` first it works. Is the path hardcoded for some reason?

**Comment by fxcoudert** [comment]
We do not provide support for HEAD, but we will accept a pull request fixing it.

**Comment by andreas-bulling** [comment]
Sure, happy to provide one. Any idea/hint what could cause this problem?
