### ISSUE TITLE
opencv contrib 4.1.1 is not the latest version for opencv 4.1.2

### ISSUE THREAD

**Issue by toruwest** [Homebrew/homebrew-core#46053]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/toruwest/066e8ab0a7e779af86fdc16692b10ffe

I think opencv_contrib 4.1.1 described in opencv.rb is not the latest version for the OpenCV 4.1.2.

I edit the opencv.rb with command "brew edit opencv" as follows and download succeeded.
Now I am trying to build it.

brew edit opencv 
resource "contrib" do
&nbsp;&nbsp;     #url "https://github.com/opencv/opencv_contrib/archive/4.1.1.tar.gz"
&nbsp;&nbsp;     url "https://github.com/opencv/opencv_contrib/archive/4.1.2.tar.gz"
&nbsp;&nbsp;    #sha256 "9f85d380758498d800fec26307e389620cde8b1a2e86ab51cddc5200fbe37102"
&nbsp;&nbsp;    sha256 "0f6c3d30baa39e3e7611afb481ee86dea45dafb182cac87d570c95dccd83eb8b"
  end

## What happened (include command output)
<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by SMillerDev** [comment]
https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request has instructions on how to do this the easy way. Please don't open issues for formula that you edited yourself though. The issue list is for software as it's distributed in homebrew-core.

**Comment by chenrui333** [comment]
@toruwest, we just released a new update. Can you test it at your end? Thanks!

**Comment by toruwest** [comment]
SMillerDev
 I'm sorry for the  inconvenience. I will do so in the future.
chenrui333 
 Solved, thank you very much.
