### ISSUE TITLE
pssh: ”ValueError: the fd 4 must be in non-blocking mode”

### ISSUE THREAD

**Issue by acdha** [Homebrew/homebrew-core#46084]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] N/A: ran `brew gist-logs <formula>` — “No Logs”
- [ ] N/A: if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run pssh

## What happened (include command output)

pssh failed with what appears to be a Python 3 compatibility issue which was patched by various Linux distributions but not upstream: https://bugs.archlinux.org/task/46571

<details>
  <summary>Command output</summary>
  <pre>

$ pssh -i -h all-hosts -- uptime
Traceback (most recent call last):
  File "/usr/local/bin/pssh", line 118, in <module>
    do_pssh(hosts, cmdline, opts)
  File "/usr/local/bin/pssh", line 71, in do_pssh
    manager = Manager(opts)
  File "/usr/local/Cellar/pssh/2.3.1/libexec/lib/python3.7/site-packages/psshlib/manager.py", line 42, in __init__
    self.iomap = IOMap()
  File "/usr/local/Cellar/pssh/2.3.1/libexec/lib/python3.7/site-packages/psshlib/manager.py", line 215, in __init__
    signal.set_wakeup_fd(wakeup_writefd)
ValueError: the fd 4 must be in non-blocking mode

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install pssh`
1. `pssh -H anyserver.example.org uptime`

**Comment by fxcoudert** [comment]
Fixing it in https://github.com/Homebrew/homebrew-core/issues/46084
