### ISSUE TITLE
brew install mit-scheme failed 

### ISSUE THREAD

**Issue by FrankRomanos** [Homebrew/homebrew-core#461]
Last 15 lines from /Users/romanos/Library/Logs/Homebrew/mit-scheme/01.make-liarc.sh:
;  Loading "triv.pkg"... done
;  Dumping "cref-unx.pkd"... done
;... done
;Loading "cref.cbf"...
;  Compiling file: "./anfile.bin" => "./anfile.c"... done
;  Compiling file: "./conpkg.bin" => "./conpkg.c"... done
;  Compiling file: "./forpkg.bin" => "./forpkg.c"...
;The object (#[compiled-closure 12 ("rtlcon" #x1) #x7 #xdf2ea #x684c13] #[compiled-procedure 13 ("cfg3" #x23) #x3 #xe29da] plus-fixnum #f . 19), passed as the second argument to apply, is not the correct type.
;To continue, call RESTART with an option number:
; (RESTART 1) => Return to read-eval-print level 1.

2 error> 
End of input stream reached.
Moriturus te saluto.
make: *** [stamp_liarc-compile-scheme] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-x11/issues

please help me.i'm almost crazy!!!

**Comment by DomT4** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please try to follow the Issue template as well. It goes through some common troubleshooting steps and also requests a `brew gist-logs <formula>` without which we can't do much but guess what the problem is.

**Comment by FrankRomanos** [comment]
I try to solve this problem by myself.but finally i failed.


RomanosdeMacBook-Pro:~ romanos$ brew update
Updated 1 tap (homebrew/core).
==> Updated Formulae
ansible             jenkins             libsass             uncrustify        
RomanosdeMacBook-Pro:~ romanos$ brew upadate
Error: Unknown command: upadate
RomanosdeMacBook-Pro:~ romanos$ brew update
Already up-to-date.
RomanosdeMacBook-Pro:~ romanos$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/bin/scheme
    /usr/local/lib/mit-scheme-x86-64

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:
  brew install libsigsegv readline

Run `brew missing` for more details.
RomanosdeMacBook-Pro:~ romanos$ brew prune /usr/local/bin/scheme
Pruned 2 symbolic links and 2 directories from /usr/local
RomanosdeMacBook-Pro:~ romanos$ brew prune /usr/local/lib/mit-scheme-x86-64
RomanosdeMacBook-Pro:~ romanos$ brew install libsigsegv readline
==> Downloading https://homebrew.bintray.com/bottles/libsigsegv-2.10.el_capitan.bottle.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/libsigsegv-2.10.el_capitan.bottle.2.tar.gz
==> Pouring libsigsegv-2.10.el_capitan.bottle.2.tar.gz
🍺  /usr/local/Cellar/libsigsegv/2.10: 10 files, 103.8K
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/readline-6.3.8.el_capitan.bottle.tar.gz
==> Pouring readline-6.3.8.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.


Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 46 files, 2.0M
RomanosdeMacBook-Pro:~ romanos$ brew install mit-scheme
==> Installing mit-scheme from homebrew/x11
==> Downloading http://ftpmirror.gnu.org/mit-scheme/stable.pkg/9.2/mit-scheme-c-9.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/mit-scheme-9.2.tar.gz
==> etc/make-liarc.sh --prefix=/usr/local/Cellar/mit-scheme/9.2_1 --mandir=/usr/local/Cellar/mit-scheme/9.2_1/share/man
Last 15 lines from /Users/romanos/Library/Logs/Homebrew/mit-scheme/01.make-liarc.sh:
;  Loading "triv.pkg"... done
;  Dumping "cref-unx.pkd"... done
;... done
;Loading "cref.cbf"...
;  Compiling file: "./anfile.bin" => "./anfile.c"... done
;  Compiling file: "./conpkg.bin" => "./conpkg.c"... done
;  Compiling file: "./forpkg.bin" => "./forpkg.c"...
;The object (#[compiled-closure 12 ("rtlcon" #x1) #x7 #xdf2ec #x68466d] #[compiled-procedure 13 ("cfg3" #x23) #x3 #xe29dc] plus-fixnum #[false 14 #x110323310] . #[compiled-entry 15 () #x0 #x684645]), passed as the second argument to apply, is not the correct type.
;To continue, call RESTART with an option number:
; (RESTART 1) => Return to read-eval-print level 1.

2 error> 
End of input stream reached.
Moriturus te saluto.
make: *** [stamp_liarc-compile-scheme] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-x11/issues

RomanosdeMacBook-Pro:~ romanos$

**Comment by FrankRomanos** [comment]
I need response!!!!!!

**Comment by mikemcquaid** [comment]
> I need response!!!!!!

Then read https://git.io/brew-troubleshooting and do what it says. You have not followed the instructions.

**Comment by FrankRomanos** [comment]
Perhaps my english is not as well.i try to followed the instructions,but it does't work.:(

**Comment by mikemcquaid** [comment]
@FrankRomanos You need to run `brew gist-logs mit-scheme`

**Comment by FrankRomanos** [comment]
@mikemcquaid   and then?DDDD
READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-x11/issues

RomanosdeMacBook-Pro:~ romanos$ brew gist-logs mit-scheme
https://gist.github.com/d15c7154dbfaaa9817bb7ddfd2f0244a

**Comment by mikemcquaid** [comment]
Thanks, that should help.

**Comment by FrankRomanos** [comment]
@mikemcquaid please tell me detail.I am a noob.

**Comment by ilovezfs** [comment]
@FrankRomanos Please try
```
brew install --build-bottle -dv mit-scheme
```

**Comment by FrankRomanos** [comment]
I fix it by u way,thanks a lot!!!!!!!!!!!!!!!I love u!!!!!!DDDDDDDDDDDDD
@ilovezfs

**Comment by ilovezfs** [comment]
@FrankRomanos you're quite welcome.

**Comment by ilovezfs** [comment]
@FrankRomanos If you `brew update`, the regular `brew install --build-from-source mit-scheme` should also now work. Plus, there is a "bottle" there for OS X 10.11 El Capitan so you don't have to build from source at all, unless you want to.

**Comment by FrankRomanos** [comment]
@ilovezfs  Thanks,that helps me a lot.U r fucking awesome.
