### ISSUE TITLE
opencv crashes python with "ERROR: flag 'flagfile' was defined more than once"

### ISSUE THREAD

**Issue by jamiebullock** [Homebrew/homebrew-core#46143]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.1.15-107-g5da322d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5da322d6be314e5f8b1729e91e60be743a1e7d8e
Last commit: 19 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4b817972ed61e5c2606e2ec76b1e44bfa6839d35
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_111
macOS: 10.15.1-x86_64
CLT: N/A
Xcode: 11.1
```

```
$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

I was trying to use opencv in python 3.7 after installing via homebrew

## What happened (include command output)

The python interpreter crashed

<details>
  <summary>Command output</summary>
  <pre>

 ERROR: flag 'flagfile' was defined more than once (in files '/tmp/gflags-20190312-19083-1vlp253/gflags-2.2.2/src/gflags.cc' and '/tmp/gflags-20191102-68746-1gvk5vm/gflags-2.2.2/src/gflags.cc').

  </pre>
</details>

## What you expected to happen

The opencv module is imported successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew instal opencv@4
python3.7
>>> import cv2
```

**Comment by Bo98** [comment]
> `in files '/tmp/gflags-20190312-19083-1vlp253/gflags-2.2.2/src/gflags.cc' and '/tmp/gflags-20191102-68746-1gvk5vm/gflags-2.2.2/src/gflags.cc'`

Can you try cleaning up your `/tmp` folder? Not quite sure why it's picking up things in there though post-install.

**Comment by maurizio-catellani** [comment]
I have the same problem. 
brew edit opencv
-DBUILD_opencv_java=ON
-DBUILD_opencv_text=ON

brew install --build-from-source opencv

opencv crashes python with "ERROR: flag 'flagfile' was defined more than once" https://github.com/Homebrew/homebrew-core/issues/46143

**Comment by odwrotnie** [comment]
Same here:

```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../lib/liblibprotobuf.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 24%] Built target libprotobuf
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
opencv crashes python with "ERROR: flag 'flagfile' was defined more than once" https://github.com/Homebrew/homebrew-core/issues/46143
```

**Comment by odwrotnie** [comment]
Same here:

```
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
/usr/bin/ranlib ../lib/liblibprotobuf.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(arenastring.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(io_win32.cc.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../lib/liblibprotobuf.a(gzip_stream.cc.o) has no symbols
[ 24%] Built target libprotobuf
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
opencv crashes python with "ERROR: flag 'flagfile' was defined more than once" https://github.com/Homebrew/homebrew-core/issues/46143
```

**Comment by iMichka** [comment]
```
brew edit opencv
-DBUILD_opencv_java=ON
-DBUILD_opencv_text=ON
```

This is not something we provide / support. We ship software as-is. The current version has not bug if I understand well, and you are trying to enable more flags.

If this fails to build for you, then you should try to debug it yourself and submit a pull request to fix it. We do not have the manpower to fix this for you, sorry.
