### ISSUE TITLE
node_exporter (for prometheus) doesn't report version information

### ISSUE THREAD

**Issue by sitsofe** [Homebrew/homebrew-core#46212]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Get the version of node_exporter (the version number is also not produced by the information that node_exporter provides to prometheus).

## What happened (include command output)

No version number was returned.

<details>
  <summary>Command output</summary>
  <pre>
node_exporter, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.12.5
  </pre>
</details>

## What you expected to happen

Version number to be shown.

## Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install node_exporter
node_exporter --version
node_exporter &
curl -s localhost:9100/metrics | grep node_exporter_build_info{
node_exporter_build_info{branch="",goversion="go1.12.5",revision="",version=""} 1
kill %
```

**Comment by fxcoudert** [comment]
Thanks @Bo98 for the fix

**Comment by sitsofe** [comment]
@Bo98, @fxcoudert - thank you!
