### ISSUE TITLE
Nginx with PHP FPM is blank page

### ISSUE THREAD

**Issue by elviskudo** [Homebrew/homebrew-core#46254]
## What you were trying to do (and why)

I'd try install nginx with brew
```brew install nginx```
then i install php-fpm
```brew install php```
and i check port 9000 is there

## What happened (include command output)

when i run my laravel app, blank page

Please help me

Note: my brew version is 2.x.x

Thanks for your help

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
