### ISSUE TITLE
MariaDB and my.cnf.d

### ISSUE THREAD

**Issue by benjibee** [Homebrew/homebrew-core#46252]
## Checklist

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Brew ouput

<details>
  <summary>brew config</summary>
  <pre>HOMEBREW_VERSION: 2.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bf8015bc44878d432fb9da4f11e1d8abcef8f32
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: abe6ea8c740520c22b9f0e444b35bf872e396031
Core tap last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>Your system is ready to brew.</pre>
</details>

<details>
  <summary>brew gist-logs mariadb</summary>
  <pre>Error: No logs.</pre>
</details>

## What you were trying to do (and why)

Access Maria DB via `mysql` or `mysql -uroot` to interact with database.

## What happened (include command output)

<details>
  <summary>mysql: Can't read dir of '/usr/local/etc/my.cnf.d'</summary>
  <pre>
  $ mysql -uroot
  mysql: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
  Fatal error in defaults handling. Program aborted
  </pre>
</details>

## What you expected to happen

An interactive mysql session to begin (i.e. `MariaDB [(none)]>` prompt).

## Step-by-step reproduction instructions

- `brew install mariadb`
- `brew services start mariadb`
- run `brew prune` ([#31760](https://github.com/Homebrew/legacy-homebrew/issues/31760)) or `brew update` or `brew cleanup` ([#2792](https://github.com/Homebrew/brew/issues/2792))
- `mysql -uroot`

## Current fix

As noted by many others in closed / stale issues (see above references), this is fixed by running `mkdir /usr/local/etc/my.cnf.d`.

While this issue _may_ be related to either Homebrew core, or a specific formula, the previous issues were closed but not fixed. Running update, prune, or cleanup should not break the Maria DB install resorting in a fix only to be found by browsing issues on Github. A likely remedy would be creating an empty file inside of the above directory, but I'm not 100% sure the best route.

**Comment by Bo98** [comment]
@benjibee The cause of the issue has now been fixed, but a rebuild can't be performed just yet due to #46453. The issue will be fixed when the next update to MariaDB is out, due very soon.

**Comment by Bo98** [comment]
@benjibee 10.4.10 is up now, try it out.

**Comment by benjibee** [comment]
I'm no longer able to reproduce the issue, looks fixed to me, thanks for the update!

I'd close the issue if it weren't already closed!
