### ISSUE TITLE
10.12 - python --universal build failed

### ISSUE THREAD

**Issue by sashkab** [Homebrew/homebrew-core#4630]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I need to use universal version of Python. I use `brew install python --universal` and build all required libraries with `--universal` flag. When attempting to install python on fresh install of Sierra, I've run into error. See https://gist.github.com/3b23cad2266f54ba8b4af1d2c8c3dadd. 

Error happens because of [missing QuickTime/QuickTime.h](https://gist.github.com/anonymous/3b23cad2266f54ba8b4af1d2c8c3dadd#file-02-make-L122). 

Upstream [issue 27806](https://bugs.python.org/issue27806).

**Comment by sashkab** [comment]
There is a patch available which should fix compilation issue of 32-bit. -- https://bugs.python.org/file44693/issue27806_v2.patch. 

I'll try to get pull request ready sometime later this week.

**Comment by rebelliard** [comment]
@sashkab can you explain how to do this?

**Comment by sashkab** [comment]
@rebelliard  -- how to do what? compile universal python on macOS Sierra?

**Comment by rebelliard** [comment]
@sashkab apply that patch. When I do `git apply issue27806_v3.patch` I get

```
error: Include/pymactoolbox.h: No such file or directory
error: Mac/Modules/ColorPickermodule.c: No such file or directory
error: Mac/Modules/MacOS.c: No such file or directory
error: Mac/Modules/OSATerminology.c: No such file or directory
error: Mac/Modules/app/_Appmodule.c: No such file or directory
error: Mac/Modules/carbonevt/_CarbonEvtmodule.c: No such file or directory
error: Mac/Modules/ctl/_Ctlmodule.c: No such file or directory
error: Mac/Modules/dlg/_Dlgmodule.c: No such file or directory
error: Mac/Modules/drag/_Dragmodule.c: No such file or directory
error: Mac/Modules/help/_Helpmodule.c: No such file or directory
error: Mac/Modules/ibcarbon/_IBCarbon.c: No such file or directory
error: Mac/Modules/icn/_Icnmodule.c: No such file or directory
error: Mac/Modules/list/_Listmodule.c: No such file or directory
error: Mac/Modules/mlte/_Mltemodule.c: No such file or directory
error: Mac/Modules/qt/_Qtmodule.c: No such file or directory
error: Mac/Modules/te/_TEmodule.c: No such file or directory
error: Mac/Modules/win/_Winmodule.c: No such file or directory
error: Python/mactoolboxglue.c: No such file or directory
```
