### ISSUE TITLE
Running brew upgrade after 30 days breaks it

### ISSUE THREAD

**Issue by sim4life** [Homebrew/homebrew-core#46305]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Y] ran `brew update` and can still reproduce the problem?
- [N] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [N] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I ran:
`$ brew update && brew upgrade`

## What happened (include command output)

There were errors in the upgrade. Even `brew doctor` is throwing errors as can be seen in the later logs

```
==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1d: 7,983 files, 17.9MB
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /usr/local/Cellar/openssl@1.1/1.1.1c... (7,963 files, 17.9MB)
Error: formulae require at least a URL
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:247:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:198:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:263:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:355:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:331:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:70:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:43:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:296:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:280:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:280:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:170:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:162:in `periodic_clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:145:in `install_formula_clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:134:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:134:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:112:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

<details>
  <summary>Command output</summary>
  <pre>

  ==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1d: 7,983 files, 17.9MB
==> `brew cleanup` has not been run in 30 days, running now...
Removing: /usr/local/Cellar/openssl@1.1/1.1.1c... (7,963 files, 17.9MB)
Error: formulae require at least a URL
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:247:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:198:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:263:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:355:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:331:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:70:in `stale_formula?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:43:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:296:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:280:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:280:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:170:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:162:in `periodic_clean!'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:145:in `install_formula_clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:138:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:134:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:134:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:112:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

  </pre>
</details>

## What you expected to happen

Successful upgrade without errors after more than 30-days

## Step-by-step reproduction instructions (by running `brew install` commands)

`$ brew config`
```
HOMEBREW_VERSION: 2.1.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bf8015bc44878d432fb9da4f11e1d8abcef8f32
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 296e17683a8f227559c80cd4394f8b7d0ffbd5e6
Core tap last commit: 31 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: --appdir=/Users/shah/Applications
HOMEBREW_GITHUB_API_TOKEN: set
CPU: dodeca-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```
`$ brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
Error: formulae require at least a URL
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:247:in `determine_active_spec'
/usr/local/Homebrew/Library/Homebrew/formula.rb:198:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:114:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:263:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:317:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:355:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:331:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:721:in `block in check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `each'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:720:in `check_for_unreadable_installed_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:60:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:52:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:52:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

**Comment by alebcay** [comment]
It looks like there are some malformed formulae in your Homebrew installation somewhere. Do you have any other taps configured?

Also, is your core tap commit history clean? You can check that with `git -C /usr/local/Homebrew/Library/Taps/Homebrew/homebrew-core status`.

**Comment by fxcoudert** [comment]
You have a formula somewhere without a URL, as @alebcay stated.
Audit your taps and report this to the tap causing the issue. Running `brew update-reset` should fix the issue if the problem is a local modification.
