### ISSUE TITLE
Error building with gcc using Xcode  when including sstream header

### ISSUE THREAD

**Issue by xianaiyang** [Homebrew/homebrew-core#46371]
c++ source file:

`#include<sstream>
int main(int argc, char* argv[]){
  return 0;
}`

compile command:
g++-9 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I/usr/include -c test.cpp

comile error:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdlib.h:128,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/cstdlib:75,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/ext/string_conversions.h:41,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/bits/basic_string.h:6493,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/string:55,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/bits/locale_classes.h:40,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/bits/ios_base.h:41,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/ios:42,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/istream:38,
                 from /usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/sstream:38,
                 from test.cpp:1:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:40:48: error: expected initializer before '__alloc_size'
   40 | void *malloc(size_t __size) __result_use_check __alloc_size(1);
      |                                                ^~~~~~~~~~~~usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/cstdlib:144:11: error: '::calloc' has not been declared
  144 |   using ::calloc;
      |           ^~~~~~
/usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/cstdlib:151:11: error: '::malloc' has not been declared
  151 |   using ::malloc;
      |           ^~~~~~
/usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/cstdlib:164:11: error: '::realloc' has not been declared
  164 |   using ::realloc;
      |           ^~~~~~~

when i remove -isysroot or -I/usr/include, the compile error gone

**Comment by Bo98** [comment]
Can you post the output of `brew config`? Just want to see if it's related to other known GCC issues.

**Comment by fxcoudert** [comment]
GCC updated, should fix it: https://github.com/Homebrew/homebrew-core/pull/45585
