### ISSUE TITLE
GCC 9.2 with XCode 11.0 incorrestly assumes aligned_alloc availability on Mac OS 10.14.5

### ISSUE THREAD

**Issue by boris-kolpackov** [Homebrew/homebrew-core#46393]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/boris-kolpackov/e5c22b47b86e49345ceacceb510ebda0

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

```
$ cat <<EOF >aa.c
#include <stdlib.h>

int main ()
{
  free (aligned_alloc (8, 2));
  return 0;
}
EOF

$ gcc-9 aa.c
$ ./a.out
dyld: Symbol not found: _aligned_alloc
  Referenced from: /Users/build/./a.out
  Expected in: /usr/lib/libSystem.B.dylib
```

Note that this also affects C++ compilation.

## What you expected to happen

I get the expected diagnostics if compiling in the C99 mode.

```
$ gcc-9 -std=c99 aa.c
aa.c: In function 'main':
aa.c:5:9: warning: implicit declaration of function 'aligned_alloc' [-Wimplicit-function-declaration]
```

## Step-by-step reproduction instructions (by running `brew install` commands)

On Mac OS 10.14.5:

```
brew install --build-from-source gcc  
```

Note: built from source in order to get fix for issue #44579

Then perform the above compilation steps.

## Additional information

```
$ cd /usr/local/Cellar/gcc/9.2.0_1/include/
$ grep -ir aligned_alloc *
c++/9.2.0/cstdlib:#if __cplusplus >= 201703L && defined(_GLIBCXX_HAVE_ALIGNED_ALLOC)
c++/9.2.0/cstdlib:# undef aligned_alloc
c++/9.2.0/cstdlib:#if __cplusplus >= 201703L && defined(_GLIBCXX_HAVE_ALIGNED_ALLOC)
c++/9.2.0/cstdlib:  using ::aligned_alloc;
c++/9.2.0/ext/malloc_allocator.h:#if __cplusplus > 201402L && _GLIBCXX_HAVE_ALIGNED_ALLOC
c++/9.2.0/ext/malloc_allocator.h:	    __ret = static_cast<_Tp*>(::aligned_alloc(alignof(_Tp),
c++/9.2.0/x86_64-apple-darwin18/bits/c++config.h:/* Define to 1 if you have the `aligned_alloc' function. */
c++/9.2.0/x86_64-apple-darwin18/bits/c++config.h:#define _GLIBCXX_HAVE_ALIGNED_ALLOC 1
```

```
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:50:10: note: 'aligned_alloc' declared here
   void    *aligned_alloc(size_t __alignment, size_t __size) __result_use_check __alloc_size(2) __OSX_AVAILABLE(10.15) __IOS_AVAILABLE(13.0) __TVOS_AVAILABLE(13.0) __WATCHOS_AVAILABLE(6.0);
```

It seems this is related to GCC not recognizing `__OSX_AVAILABLE(10.15)` in the `aligned_alloc` declaration and the workaround discussed in issue #44579.

Let me know if you need any additional information or if you need me to try anything.

**Comment by fxcoudert** [comment]
Is there a way we can “force” GCC to not define `_GLIBCXX_HAVE_ALIGNED_ALLOC`? Like a `configure` flag?

**Comment by boris-kolpackov** [comment]
That would only be a partial solution since the user code will still "see" `aligned_alloc()` during compilation.

One admittedly hackish way to work around this for good it to comment out the `aligned_alloc` declaration in `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h` and then rebuild GCC from source.

**Comment by Bo98** [comment]
Do you have a `/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk`? The GCC build could be modified to use that.

**Comment by boris-kolpackov** [comment]
Yes:

```
$ ls -l /Library/Developer/CommandLineTools/SDKs/
total 0
lrwxr-xr-x  1 root  wheel   15 Oct 30 07:35 MacOSX.sdk -> MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 Jul 16 00:44 MacOSX10.14.sdk
drwxr-xr-x  8 root  wheel  256 Aug 30 06:48 MacOSX10.15.sdk
```

Interestingly, Clang from the Command Line Tools for XCode 11.0 by default uses 10.14 SDK:

```
$ clang++ -std=c++17 -v aa.cxx
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name aa.cxx -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=10.14 -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 512.4 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/usr/local/include -stdlib=libc++ -internal-isystem /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1 -Wno-framework-include-private-from-public -Wno-atimport-in-framework-header -Wno-extra-semi-stmt -Wno-quoted-include-in-framework-header -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /Users/build -ferror-limit 19 -fmessage-length 131 -stack-protector 1 -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.14.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/0r/18yy118s21d5rqpxbqm_wc_h0000gn/T/aa-ca507e.o -x c++ aa.cxx
clang -cc1 version 11.0.0 (clang-1100.0.33.8) default target x86_64-apple-darwin18.6.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks (framework directory)
```

I wonder shouldn't GCC do the same by default?

**Comment by Bo98** [comment]
> I wonder shouldn't GCC do the same by default?

Yes, and I believe that will fix many of the Mojave issues with GCC.

The presence of two SDKs in the CLTs is a relatively new thing. System headers moved from /usr/include to the SDK with Mojave, which at that point was the latest SDK. Now that the Catalina SDK is also included, and is the default SDK, that's when things started breaking since it's looking at system headers in the latest SDK - something that wasn't an issue before since there was either a /usr/include (pre-Mojave) or the Mojave SDK was the latest.

**Comment by boris-kolpackov** [comment]
For comparison, here is what I have SDKs-wise with CLT for XCode 10.2.1 (again on 10.14.5):

```
$ ls -l /Library/Developer/CommandLineTools/SDKs/
total 0
lrwxr-xr-x  1 root  wheel   15 Oct 30 07:35 MacOSX.sdk
drwxr-xr-x  7 root  wheel  224 Jul 16 00:44 MacOSX10.14.sdk -> MacOSX.sdk
```

Notice that symlinks are the other way around now.

**Comment by boris-kolpackov** [comment]
I can confirm that manually changing the `MacOSX.sdk` symlink to point to `MacOSX10.14.sdk` instead of `MacOSX10.15.sdk` and then reinstalling GCC from source fixes the problem.

**Comment by fxcoudert** [comment]
I am trying a fix in https://github.com/Homebrew/homebrew-core/pull/45585

**Comment by fxcoudert** [comment]
GCC updated, should fix it: https://github.com/Homebrew/homebrew-core/pull/45585
