### ISSUE TITLE
OpenSSL 1.0 removal

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#46454]
OpenSSL 1.0 will reach EOL on 2019-12-31. Here are the few remaining formulas that depend on it, and need to be fixed (or removed). They are sorted by analytics (higher usage first):

- [x] mysql-connector-c
- [x] erlang@19 ~(needed by couchdb)~
- [x] rethinkdb
- [x] freerdp
- [x] thrift@0.9
- [x] ruby@2.0
- [x] erlang@17 (needed by riak)
- [x] bulk_extractor
- [x] nut
- [x] ipmiutil
- [x] freeswitch
- [x] libcapn
- [x] virtuoso
- [x] pound

**Edit:** Sadly, we have added new formulas with OpenSSL 1.0 dependency (by mistake)

- [x] awsume https://github.com/Homebrew/homebrew-core/pull/45270
- [x] dvc https://github.com/Homebrew/homebrew-core/pull/45709
- [x] manticoresearch https://github.com/Homebrew/homebrew-core/pull/42026

**Comment by Bo98** [comment]
freeswitch won't be on that list for very long (#46367).

**Comment by fxcoudert** [comment]
### libcapn

- The issue was reported, no answer given https://github.com/adobkin/libcapn/issues/45
- No commit to repository since 2017

**Comment by jnozsc** [comment]
ruby 2.0 is EOL for a while
https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/

**Comment by jnozsc** [comment]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/ruby@2.0.rb

https://apple.stackexchange.com/questions/47664/what-is-apples-policy-for-supporting-security-updates-on-older-versions-of-os-x

https://apple.stackexchange.com/questions/257627/ruby-version-on-macos-sierra

it seems ruby@2.0 in homebrew-core is kept in order to support Mac OSX 10.12 or prior . 
Mac OSX 10.13 has built-in ruby version 2.3.3

So if homebrew-core decide to stop support Mac OSX 10.12 or prior, it should be safe to remove it

**Comment by fxcoudert** [comment]
@Bo98 we need to migrate `mysql-connector-c` to its latest version (we ship a very old one). As far as I understand, the distribution of mysql-connector-c has changed, and is now part of the source package for mysql-client. Would you be able to help and provide a PR for updating `mysql-connector-c`? Many thanks in advance…

**Comment by Bo98** [comment]
I'll need to check what the actual differences are. You're right that I think it merged into mysql-client  but I'm not sure why they were separate things to begin with. I'll try create something using mysql-connector-c and see if it's compatible with mysql-client.

We should definitely also offer mysql-client 8.0. I'm not sure why there's a comment saying [to use 5.7](https://github.com/Homebrew/homebrew-core/blob/9d230fb5a19656fe3e039f91ce2d4b894e2a19bc/Formula/mysql-client.rb#L4) when a mysql-client@5.7 seems a viable option.

I'll get back to you shortly.

**Comment by Bo98** [comment]
Linking the relevant pull request here for reference: #46566

**Comment by efiop** [comment]
Hi guys!

Sorry for accidentally using 1.0 in dvc. Created https://github.com/Homebrew/homebrew-core/pull/46829 to fix that.

Thanks for maintaining homebrew 🙏 !

**Comment by valmack** [comment]
Just curious. Why the removal?

**Comment by SMillerDev** [comment]
Because of the first sentence in the issue.
