### ISSUE TITLE
git 2.24.0 on Mojave stopped working for https

### ISSUE THREAD

**Issue by hynek** [Homebrew/homebrew-core#46466]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have updated git the other day as part of my regular `brew update; brew upgrade` routine.

## What happened (include command output)

Git stopped working when I try to access an https-based repo with the following error:

```
❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...

dyld: Symbol not found: _curl_global_sslset
  Referenced from: /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
```

<details>
  <summary>Command output</summary>
  <pre>
❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...
dyld: Symbol not found: _curl_global_sslset
  Referenced from: /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
❯ brew config
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: be9505b6549ebd2da50af9a28d0760c7d2c14ba5
Core tap last commit: 55 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_INSTALL_CLEANUP: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 10.0.2, 1.8.0_202
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.2
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/hynek/.pyenv/shims/python3.5m-config
  /Users/hynek/.pyenv/shims/python2-config
  /Users/hynek/.pyenv/shims/python3.4m-config
  /Users/hynek/.pyenv/shims/python3.6m-config
  /Users/hynek/.pyenv/shims/python3.7-config
  /Users/hynek/.pyenv/shims/python2.7-config
  /Users/hynek/.pyenv/shims/python3.7m-config
  /Users/hynek/.pyenv/shims/python3.5-config
  /Users/hynek/.pyenv/shims/python-config
  /Users/hynek/.pyenv/shims/python3-config
  /Users/hynek/.pyenv/shims/python3.6-config
  /Users/hynek/.pyenv/shims/python3.4-config
  /Users/hynek/.local/bin/pre-commit-validate-config
  /Users/hynek/.local/bin/ansible-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python
  </pre>
</details>

(I need my pyenv and I can't link your Python but that should be very much unrelated)

## What you expected to happen

That git keeps working.

## Step-by-step reproduction instructions (by running `brew` commands)

On **Mojave**:

```
$ brew install git
...
$ git clone https://github.com/Homebrew/brew/
```

I have tried `brew reinstall -s git` but it doesn't help either.

**Comment by MikeMcQuaid** [comment]
Moved to correct repository. Did this happen before you updated to Xcode 11.1? Does `/usr/lib/libcurl.4.dylib` exist? Does `brew reinstall -s git` produce identical messaging afterwards? What about `brew reinstall --force-bottle git?`

**Comment by hynek** [comment]
Thank you for your quick turnaround and sorry for messing up the repo (I'm a Patreon donor if that makes me look a tad less bad ;))!

>  Did this happen before you updated to Xcode 11.1?

I want to say it happened after. I tend to update everything quite fast, and since Xcode is came before git 2.24.0. I don't usually use git for https, I found out by running `pre-commit update` that suddenly stopped working.

---

`/usr/lib/libcurl.4.dylib` does exist (and looks "ancient"):

```
❯ ll /usr/lib/libcurl.4.dylib
.rwxr-xr-x 850k root  4 May  9:03 /usr/lib/libcurl.4.dylib
```

For the record:

```
❯ otool -L /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
/usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https:
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
	/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/local/opt/pcre2/lib/libpcre2-8.0.dylib (compatibility version 9.0.0, current version 9.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
```

---

Yes, same error:

```
❯ brew reinstall -s git
==> Reinstalling git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.24.0.tar.xz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/28d42cc9863211a58efb913a1f549d1b8929defac2800eca2807c32effb092b2--git-2.24.0.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.24.0 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make
==> make test
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.24.0.tar.xz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/407aeeaac7c5bdca332357cc79004cb51ee16e050696d25e2b622538b33bb133--git-manpages-2.24.0.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.24.0.tar.xz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/efc0f754979ec2400b32033ff95eac3573cfd6e768e470f886dcc5d6fb09b3b0--git-htmldocs-2.24.0.tar.xz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Net-SMTP-SSL-1.04.tar.gz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/0726c68dac390b617cefcc880f076b50795463c1fba286d46a53082ebed2bc9d--Net-SMTP-SSL-1.04.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.24.0: 1,546 files, 45.2MB, built in 30 seconds
❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...
dyld: Symbol not found: _curl_global_sslset
  Referenced from: /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
```

---

Same error:

```
❯ brew reinstall --force-bottle git
==> Reinstalling git
==> Downloading https://homebrew.bintray.com/bottles/git-2.24.0.mojave.bottle.tar.gz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/2668f2476a95ce37e0adb737cf469eb8da52941134cb6d61b95750dec4e6591f--git-2.24.0.mojave.bottle.tar.gz
==> Pouring git-2.24.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.24.0: 1,547 files, 45.5MB

~ took 4s
❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...
dyld: Symbol not found: _curl_global_sslset
  Referenced from: /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
```

**Comment by MikeMcQuaid** [comment]
You might want/need to uninstall Xcode 11 temporarily and try again after that.

**Comment by hynek** [comment]
I have good and bad news:

```
❯ brew reinstall --force-bottle git
==> Reinstalling git
==> Downloading https://homebrew.bintray.com/bottles/git-2.24.0.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/36/36d3b48999a9252ea1a25fa54cd5305259c713d78d14be8161ea206357c1e120?__gda__=exp=1573140049~hmac=e412da230829a6f270531568b1d5102830df20e35336c5b6579c45268a681cf4&response-content-disposition=attachment%3Bfilename%3D%22git-2.24.0.mojave.bottle.tar.gz%22&response-content-t
######################################################################## 100.0%
==> Pouring git-2.24.0.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.24.0: 1,547 files, 45.5MB

~ took 7s
❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...
dyld: Symbol not found: _curl_global_sslset
  Referenced from: /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/git/2.24.0/libexec/git-core/git-remote-https

~
❯ brew reinstall -s git
==> Reinstalling git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.24.0.tar.xz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/28d42cc9863211a58efb913a1f549d1b8929defac2800eca2807c32effb092b2--git-2.24.0.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.24.0 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make
==> make test
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.24.0.tar.xz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/407aeeaac7c5bdca332357cc79004cb51ee16e050696d25e2b622538b33bb133--git-manpages-2.24.0.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.24.0.tar.xz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/efc0f754979ec2400b32033ff95eac3573cfd6e768e470f886dcc5d6fb09b3b0--git-htmldocs-2.24.0.tar.xz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Net-SMTP-SSL-1.04.tar.gz
Already downloaded: /Users/hynek/Library/Caches/Homebrew/downloads/0726c68dac390b617cefcc880f076b50795463c1fba286d46a53082ebed2bc9d--Net-SMTP-SSL-1.04.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.24.0: 1,546 files, 45.2MB, built in 38 seconds

~ took 40s
❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...
remote: Enumerating objects: 128564, done.
remote: Total 128564 (delta 0), reused 0 (delta 0), pack-reused 128564
Receiving objects: 100% (128564/128564), 30.63 MiB | 6.70 MiB/s, done.
Resolving deltas: 100% (94344/94344), done.

~ took 6s
❯ which git
/usr/local/bin/git

~
❯ brew config
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1b8d40f742a260b69e2aa9ea93d15d286a3a5640
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_INSTALL_CLEANUP: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 12.0.1, 10.0.2, 1.8.0_202
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

---

It looks like the bottle is broken, but source works, if there's no Xcode?

**Comment by Bo98** [comment]
I can't reproduce this issue but our configurations might differ: Does `git config --global --get http.sslBackend` output anything?

**Comment by hynek** [comment]
> I can't reproduce this issue but our configurations might differ: Does `git config --global --get http.sslBackend` output anything?

No, I get an empty line back.

**Comment by Bo98** [comment]
Hmm, interesting. Maybe it's somewhere else like `--system`.

I have now been able to reproduce the issue with `git config --global http.sslBackend openssl`. The issue however does also happen with Xcode's git:

```
$ /usr/bin/git clone https://github.com/Homebrew/brew
Cloning into 'brew'...
dyld: lazy symbol binding failed: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

dyld: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
```

But not the CLT git:

```
$ /Library/Developer/CommandLineTools/usr/bin/git clone https://github.com/Homebrew/brew
Cloning into 'brew'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
...
```

**Comment by Bo98** [comment]
I've reported the issue with Xcode git: FB7433034

This doesn't fully answer why it is happening with Homebrew's git though.

**Comment by Bo98** [comment]
The problem is Homebrew is using the wrong headers for compling against the system curl. Xcode ships with the 10.15 SDK which has:

```
$ grep "#define LIBCURL_VERSION_NUM" /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/curl/curlver.h
#define LIBCURL_VERSION_NUM 0x074001
```

while the CLT has the 10.14 SDK with the correct headers for Mojave:

```
$ grep "#define LIBCURL_VERSION_NUM" /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/curl/curlver.h
#define LIBCURL_VERSION_NUM 0x073600
````

I can submit a patch to use the CLT.

**Comment by gavsim** [comment]
Hi, is there a way to resolve this issue whilst awaiting for the update to be published? Rollback to git 2.23?

**Comment by hynek** [comment]
I'm very sorry, but I'm afraid it didn't work @MikeMcQuaid:

```
==> Upgrading git
==> Downloading https://homebrew.bintray.com/bottles/git-2.24.0_1.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f0/f09352676d42d56861f4440b26af02ce050165a6e648ac0bedf21af4226249d8?__gda__=exp=1573812638~hmac=86801a0693b3
######################################################################## 100.0%
==> Pouring git-2.24.0_1.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.24.0_1: 1,547 files, 45.5MB
Removing: /usr/local/Cellar/git/2.24.0... (1,546 files, 45.2MB)
==> Caveats
==> git
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git

❯ git clone https://github.com/Homebrew/brew/
Cloning into 'brew'...
dyld: Symbol not found: _curl_global_sslset
  Referenced from: /usr/local/Cellar/git/2.24.0_1/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib
 in /usr/local/Cellar/git/2.24.0_1/libexec/git-core/git-remote-https
```

I have _not_ re-installed Xcode – any suggestions what to do?

**Comment by Bo98** [comment]
Can you try build from source again? When I tested the fix locally it worked fine, but maybe there's something different about the CI setup compared to mine.

**Comment by Bo98** [comment]
Yeah build from souce works absolutely fine for me:

```
$ brew install -s git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.24.0.tar.xz
Already downloaded: /Users/bo/Library/Caches/Homebrew/downloads/28d42cc9863211a58efb913a1f549d1b8929defac2800eca2807c32effb092b2--git-2.24.0.tar.xz
==> make install prefix=/usr/local/Cellar/git/2.24.0_1 sysconfdir=/usr/local/etc CC=clang CFLAGS= LDFLAGS= NO_OPENSSL=1 APPLE_COMMON_CRYPTO=1
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make
==> make test
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.24.0.tar.xz
Already downloaded: /Users/bo/Library/Caches/Homebrew/downloads/407aeeaac7c5bdca332357cc79004cb51ee16e050696d25e2b622538b33bb133--git-manpages-2.24.0.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.24.0.tar.xz
Already downloaded: /Users/bo/Library/Caches/Homebrew/downloads/efc0f754979ec2400b32033ff95eac3573cfd6e768e470f886dcc5d6fb09b3b0--git-htmldocs-2.24.0.tar.xz
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Net-SMTP-SSL-1.04.tar.gz
Already downloaded: /Users/bo/Library/Caches/Homebrew/downloads/0726c68dac390b617cefcc880f076b50795463c1fba286d46a53082ebed2bc9d--Net-SMTP-SSL-1.04.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.24.0_1: 1,546 files, 45.1MB, built in 50 seconds
$ git config --global http.sslBackend openssl
$ git clone https://github.com/github/Spoon-Knife
Cloning into 'Spoon-Knife'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.
```

I don't quite understand why the CI that built the bottle is different.

**Comment by hynek** [comment]
I can confirm that `brew reinstall -s git` **does** work.

**Comment by MikeMcQuaid** [comment]
> I don't quite understand why the CI that built the bottle is different.

We have a different CLT version. If you can figure out how to make a Ruby-only check to identify the difference in your configuration we can add that to a bottle check (so it'll build from source otherwise).

**Comment by MikeMcQuaid** [comment]
Remind me (all) your CLT/Xcode versions?

**Comment by Bo98** [comment]
I was on Xcode 11.1 but for some reason my CLT was on 10.3.0.0.1.1562985497 (usually it gets updated in Software Update). I've sorted that now.

I've found the issue though. Apple made a blunder in CLT for 11.0 (and 11.1 since there wasn't one for that) - they accidentally shipped 10.15 Curl headers in the 10.14 SDK. System headers _must_ match system libraries - this is how the Git issue started - and from 10.14 onwards those headers lie in the SDK after the removal of `/usr/include`.

From comparing the pkg files, the problem appears to have been fixed in the 11.2 CLT - I'll install Xcode 11.2 shortly to confirm.

In the meantime, until the CI is updated, I'm not really sure what to do. We're using the wrong `curlver.h` so Git is using newer API that the 10.14 library does not support.

**Comment by Bo98** [comment]
Ok sorry, a correction since I misread it: 11.0 CLT _does_ work but **not** if you have ever previously installed 10.x on that system. 11.2 doesn't change fix it - the symlinks have been broken by the installer. You might well even find a "MacOSX.sdk 1" folder.

When you next get around to upgrading CLT - you _have_ to delete `/Library/Developer/CommandLineTools/SDKs` before running the installer.

That's perhaps why they did not offer an upgrade path via Software Update - it was broken.

After deleting the SDKs folder and reinstalling the 11.2 CLT, builds started working again:

```
$ git clone https://github.com/github/Spoon-Knife
Cloning into 'Spoon-Knife'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.
```


Bit of a mess really.

**Comment by Bo98** [comment]
This is what it looks like when the CLT installer has broken our SDKs:

```
$ ls -l /Library/Developer/CommandLineTools/SDKs_old
total 0
lrwxr-xr-x 1 root wheel  15 Nov 15 21:24 MacOSX.sdk -> MacOSX10.15.sdk
drwxr-xr-x 7 root wheel 224 Nov 15 19:45 MacOSX.sdk 1
lrwxr-xr-x 1 root wheel  10 Oct 11 17:49 MacOSX10.14.sdk -> MacOSX.sdk
drwxr-xr-x 8 root wheel 256 Nov 15 21:24 MacOSX10.15.sdk
```

**Comment by hynek** [comment]
Not sure if it's still relevant, but I'm on:

```
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
```

**Comment by Bo98** [comment]
Just to update you that the latest binary (2.24.0_2) should now work. I tested it out on my machine and could no longer reproduce the issue.
