### ISSUE TITLE
Mariadb formula is failing

### ISSUE THREAD

**Issue by gabbanaesteban** [Homebrew/homebrew-core#46500]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**brew config output:**

```
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 526c409fc99d182b8f24f4548c04c9b20973735c
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/gabbanaesteban/.cache/Homebrew
HOMEBREW_LOGS: /home/gabbanaesteban/.cache/Homebrew/Logs
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.20.1 => /bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 5.0.0-32-generic x86_64 GNU/Linux
OS: Ubuntu 19.04 (disco)
Host glibc: 2.29
/usr/bin/gcc: 8.3.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**brew doctor output:**

```
Your system is ready to brew.
```

## What you were trying to do (and why)

Install mariadb using brew

## What happened (include command output)

The URL used in the formula responses with not found

<details>
  <summary>Command output</summary>
  <pre>

 curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "mariadb"
Download failed: https://downloads.mariadb.org/f/mariadb-10.4.9/source/mariadb-10.4.9.tar.gz

  </pre>
</details>

## What you expected to happen

Get mariadb installed

## Step-by-step reproduction instructions (by running `brew install` commands)

run: brew install mariadb

**Comment by fxcoudert** [comment]
See https://github.com/Homebrew/homebrew-core/issues/46453
