### ISSUE TITLE
Formula Request: git-scan

### ISSUE THREAD

**Issue by balupton** [Homebrew/homebrew-core#4652]
https://github.com/totten/git-scan

I'd happily do a pull request, providing I can get some help in doing so. There is a prebuilt phar file that is hosted elsehwere, the repo can also be cloned and built providing php, composer, and box are installed. Building from source seems best as that way versioning is easier I'd imagine.

Some pointers in the right direction would be great! I've already looked at:

- https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md
- https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook

/cc https://github.com/totten/git-scan/issues/7

**Comment by vladshablinsky** [comment]
Seems like [GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/audit.rb#L598).

But you can always [create a tap](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) with that formula yourself.

**Comment by vladshablinsky** [comment]
Closing for now.
