### ISSUE TITLE
Missing mpv.app bundle

### ISSUE THREAD

**Issue by chainikdn** [Homebrew/homebrew-core#46532]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

install mpv and get a mpv.app

## What happened (include command output)

mpv.app is missing since the mpv.rb restoration with ver. 0.30.0

## What you expected to happen

in the previous mpv.rb version there was a call to the bundle generator
```
system "python3", "TOOLS/osxbundle.py", "build/mpv"
    prefix.install "build/mpv.app
```
and now it's missing

**Comment by fxcoudert** [comment]
This is on purpose, most Homebrew formulas do not install `.app` bundles, but apps that run from command-line. If you want/need the `.app`, please use the cask.

**Comment by chainikdn** [comment]
I don't want the cask cause it doesn't support Vapoursynth.

**Comment by SMillerDev** [comment]
You can maintain a copy in your own tap that builds the app.

**Comment by StV0911** [comment]
> You can maintain a copy in your own tap that builds the app.

Could you please describe to a total noob like me the steps how to do it?
Big thanks for help

**Comment by droukd** [comment]
> Could you please describe to a total noob

Just add

```
    system "python3", "TOOLS/osxbundle.py", "build/mpv"
    prefix.install "build/mpv.app"
```
after `system "python3", "waf", "install"`
in install file located `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpv.rb`.
Then reinstall with building from source:
`brew reinstall -s mpv`

And here is your app, ready to go on the system:
`ln -s /usr/local/Cellar/mpv/0.30.0/mpv.app /Applications`

**Comment by StV0911** [comment]
> > Could you please describe to a total noob
> 
> Just add
> 
> ```
>     system "python3", "TOOLS/osxbundle.py", "build/mpv"
>     prefix.install "build/mpv.app"
> ```
> 
> after `system "python3", "waf", "install"`
> in install file located `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mpv.rb`.
> Then reinstall with building from source:
> `brew reinstall -s mpv`
> 
> And here is your app, ready to go on the system:
> `ln -s /usr/local/Cellar/mpv/0.30.0/mpv.app /Applications`

@droukd 
big thanks to you!
It works like a charme!!! :-)
Greetings
StV
