### ISSUE TITLE
omniorb only build a python2 package, nothing for python3

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/homebrew-core#46586]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [n/a] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install the `omniorb` package.

## What happened (include command output)

`omniorb` should build a python package, but only builds one for python 2.7.

## What you expected to happen

`omniorb` has supported python 3 for years.  Homebrew's default python version is 3.  Python 2 will be EOL'd in ≈1 month.  Homebrew shouldn't only ship python 2.7 packages.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install omniorb`

**Comment by SMillerDev** [comment]
Would you mind making a pull request to change it?

**Comment by alexchandel** [comment]
@SMillerDev What's the proper method of configuring against Homebrew's python 3 in a formula?

I built by adding ` depends_on "python"` and changing the `bindings`' configure to `system "./configure", "--prefix=#{prefix}", "PYTHON=/usr/local/bin/python3.7"`, but hardcoding the Homebrew prefix & version seems wrong.

**Comment by SMillerDev** [comment]
`#{Formula["python"]}.opt_prefix` should work and then `/bin/python`

**Comment by fxcoudert** [comment]
`PYTHON=python3` should do it.

**Comment by alexchandel** [comment]
As in `"PYTHON=#{Formula["python"].opt_prefix}/bin/python"` ?

Strangely `PYTHON=python3` threw an error, but perhaps that was because `depends_on "python"` was missing.

**Comment by fxcoudert** [comment]
Yes, `PYTHON=python3` should find `python3` in its `PATH`, but that needs `depends_on "python"` in the formula

**Comment by iMichka** [comment]
As this is more a feature request than a real bug, and the content of the pull request has been discussed above, I'll close the issue. Please open a pull request with the needed changes when you have time.
