### ISSUE TITLE
mysql doesn't actually link OpenSSL@1.1

### ISSUE THREAD

**Issue by bjoernpollex-sc** [Homebrew/homebrew-core#46601]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## `brew config` output
```
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5561705c81aa5279992353fe1a9836acc59d53d
Core tap last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 10.0.1, 1.8.0_181
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```

## `brew doctor` output
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/bjoernpollex/.local/bin/devpi-gen-config
  /Users/bjoernpollex/.pyenv/shims/python2-config
  /Users/bjoernpollex/.pyenv/shims/python3.6m-config
  /Users/bjoernpollex/.pyenv/shims/python3.7-config
  /Users/bjoernpollex/.pyenv/shims/python2.7-config
  /Users/bjoernpollex/.pyenv/shims/python3.7m-config
  /Users/bjoernpollex/.pyenv/shims/python-config
  /Users/bjoernpollex/.pyenv/shims/python3-config
  /Users/bjoernpollex/.pyenv/shims/python3.6-config

Warning: Some installed formulae are not readable:
  phantomjs: uninitialized constant #<Class:0x00007fecc610e518>::MinimumMacOSRequirement

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
```

## What you were trying to do (and why)

I was trying to install the Python package [`mysqlclient`][1]. 

## What happened (include command output)

The installation fails because it cannot link `OpenSSL`: 
```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -Dversion_info=(1,4,5,'final',0) -D__version__=1.4.5 -I/usr/local/Cellar/mysql/8.0.18/include/mysql -I/Users/bjoernpollex/.pyenv/versions/3.7.2/envs/mysqlclient-test/include -I/Users/bjoernpollex/.pyenv/versions/3.7.2/include/python3.7m -c MySQLdb/_mysql.c -o build/temp.macosx-10.14-x86_64-3.7/MySQLdb/_mysql.o
    clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/bjoernpollex/.pyenv/versions/3.7.2/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/bjoernpollex/.pyenv/versions/3.7.2/lib build/temp.macosx-10.14-x86_64-3.7/MySQLdb/_mysql.o -L/usr/local/Cellar/mysql/8.0.18/lib -lmysqlclient -lssl -lcrypto -o build/lib.macosx-10.14-x86_64-3.7/MySQLdb/_mysql.cpython-37m-darwin.so
    ld: library not found for -lssl
```

The reason for that is that `mysqlclient` relies on `mysql_config` to report all required flags. However, `mysql_config --libs` has the following output:
```
-L/usr/local/Cellar/mysql/8.0.18/lib -lmysqlclient -lssl -lcrypto
```
The problem is that `libssl` from OpenSSL is not on that path, because it is keg-only. The build can be fixed by explicitly setting the `LDFLAGS` environment variable to point to the correct path.

## What you expected to happen

The installation should succeed and correctly link against the same OpenSSL version used by `mysql` itself.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install mysql
pip install mysqlclient  # you might want to run this inside a virtual environment
```

[1]: https://github.com/PyMySQL/mysqlclient-python

**Comment by bjoernpollex-sc** [comment]
I'm not entirely sure how this is supposed to work, but I see two potential issues:

1. The `mysql` formula sets [`-DWITH_SSL=yes`][1]. According to the [MySQL documentation][2], this means: _"Use the system OpenSSL library if present, else the library bundled with the distribution."_  According to the [Formula-Cookbook][3], this should be handled as shown in the [`clamav`][4] formula: `--with-openssl=#{Formula["openssl"].opt_prefix}`
2. As far as I understand, the above does not apply when pouring from a bottle. Here, the information returned by `mysql_config` would need to be adapted to the local system somehow. Is this possible?

[1]: https://github.com/Homebrew/homebrew-core/blob/a5561705c81aa5279992353fe1a9836acc59d53d/Formula/mysql.rb#L60
[2]: https://dev.mysql.com/doc/refman/5.6/en/source-configuration-options.html#option_cmake_with_ssl
[3]: https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#check-for-dependencies
[4]: https://github.com/Homebrew/homebrew-core/blob/89c4574ef1a6d15e92196637ff315a0a4bb3e289/Formula/clamav.rb#L37

**Comment by Bo98** [comment]
> mysql doesn't actually link OpenSSL@1.1

Are you sure? Check `brew linkage mysql`.

> The mysql formula sets -DWITH_SSL=yes. According to the MySQL documentation, this means: "Use the system OpenSSL library if present, else the library bundled with the distribution."

This is no longer true. There is no "bundled" SSL library. `yes` is supposed to be the same as `system`. But on MySQL 5.x, that isn't quite true (see #46379). 8.0 may be different however.

> Here, the information returned by mysql_config would need to be adapted to the local system somehow.

What would be different? openssl@1.1 is a dependency so that formula can be expected to be installed.

You're right though that mysql_config doesn't have a OpenSSL `-L` in it, and I don't think it ever has. This may be an upstream issue.

**Comment by Bo98** [comment]
Ok, `-DWITH_SSL=<path>` has now been changed in 8.0 to work dynamically, but it has no effect on `mysql_config` compared with how it is now:

```
$ mysql_config --libs
-L/usr/local/Cellar/mysql/8.0.18_1/lib -lmysqlclient -lssl -lcrypto
```

**Comment by bjoernpollex-sc** [comment]
@Bo98 I agree, in that case, I'll close this one and reach out to the MySQL folks. Thanks for your support!
