### ISSUE TITLE
Force Xcode8 in xcode-select on Sierra

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#4664]
How about forcing/reminding users to use Xcode 8 in xcode-select? Because there is many issues with Xcode 7 on Sierra.

As for now brew is forcing to install Xcode 8, but does not check it's activation in xcode-select.

**Comment by yurikoles** [comment]
I had installed Xcode 8, but continued to use `/Library/Developer/CommandLineTools`

**Comment by DomT4** [comment]
> I had installed Xcode 8, but continued to use /Library/Developer/CommandLineTools

That's fine, as long as the CLT is up-to-date.

**Comment by MikeMcQuaid** [comment]
We do this.
