### ISSUE TITLE
Glade 3.20.0 failed to install on OS X 10.11

### ISSUE THREAD

**Issue by bnovember** [Homebrew/homebrew-core#4665]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I have used homebrew to install glade before, but it was constantly crashing to the point where it was nearly unusable, so I tried to uninstall it and reinstall it, but now every time I input "brew install glade" I get this message:

Error: undefined method `rebuild' for #<BottleSpecification:0x007fda8306e068>

I also get the same error message when running brew doctor, so it might be more than just a problem with the installation of glade alone. This sequence of paths is always printed after the error message, I don't know if it helps but maybe it means something significant:

/usr/local/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb:9:in `block in <class:Jpeg>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1731:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb:7:in `<class:Jpeg>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/jpeg.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:175:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formulary.rb:234:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1132:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1130:in `map'
/usr/local/Library/Homebrew/formula.rb:1130:in `installed'
/usr/local/Library/Homebrew/diagnostic.rb:884:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:42:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Library/brew.rb:87:in `<main>'

I need to complete this GUI and I am having trouble installing glade from source on my computer so any help would be really appreciated. Thanks.

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by DomT4** [comment]
> Error: undefined method `rebuild' for #BottleSpecification:0x007fda8306e068

Try the suggested step. Surprised if that doesn't resolve the issue for you:
```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```

**Comment by bnovember** [comment]
Thanks this helped a lot!
