### ISSUE TITLE
pkg-config dependencies on keg-only formulae don't work

### ISSUE THREAD

**Issue by burke** [Homebrew/homebrew-core#4669]
We use [libgda](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libgda.rb), which depends on [libxml2](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libxml2.rb).

Building against libgda more or less requires the use of `pkg-config`. Fortunately, `libgda-5.0` and most of its dependencies are linked into `/usr/local/lib/pkgconfig`.

Unfortunately, since libxml2 is a keg-only formula, it isn't linked, so `pkg-config --exists libgda-5.0` fails with the default `PKG_CONFIG_PATH`, since `libgda-5.0` specifies `libxml-2.0` as a dependency, and `pkg-config` is unable to locate it.

i.e.

#### To reproduce

```
brew install libgda
gem install gda
```

#### To work around

```
brew install libgda
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig
gem install gda
```

Maybe it makes sense to link `pkgconfig` items even when dealing with keg-only formulae? I'm not sure what the answer is here but this feels awkward.

**Comment by DomT4** [comment]
> Maybe it makes sense to link pkgconfig items even when dealing with keg-only formulae?

Whatever the answer is, it isn't going to be this. Doing this essentially breaks the `keg_only` safety mechanism for anything that uses or has access to `pkg-config` both inside and outside of Homebrew.

**Comment by burke** [comment]
That does make sense.

In this particular case I found the behaviour surprising and difficult to debug, since `pkg-config` fails in a fairly non-informative way when a dependency is missing.

libgda is not a very commonly-used library on macOS so it's perhaps not worth fixing for this case alone, but I would imagine there are other things that depend on libxml2 and use pkg-config.

One answer, I guess, would be to print a warning post-install if a package includes pkgconfig files and also depends on a keg_only formula which includes pkgconfig files, but I'm not sure how hard it is to derive that bit of information.

**Comment by DomT4** [comment]
I tweaked the messaging a bit so now in the little post-install caveats you get a nudge about `PKG_CONFIG_PATH` as well where it's necessary.

```
This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
    PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
```
