### ISSUE TITLE
automake build fails if Xcode has a space in the path

### ISSUE THREAD

**Issue by VivaLosDoyers** [Homebrew/homebrew-core#4673]
automake does not build if the path to Xcode contains a space.

In my case, it was: /Applications/Xcode 8.app
Which was named this way since I need to keep Xcode 7 installed as well.

```
==> ./configure --prefix=/usr/local/Cellar/automake/1.15
==> make install
Last 15 lines from /Users/mmiller/Library/Logs/Homebrew/automake/02.make:
install

  GEN      bin/automake
  GEN      bin/aclocal
  GEN      doc/aclocal.1
  GEN      doc/automake.1
  GEN      runtest
  GEN      t/ax/cc-no-c-o
  GEN      t/ax/shell-no-trail-bslash
  GEN      lib/Automake/Config.pm
  GEN      t/ax/test-defs.sh
  GEN      doc/aclocal-1.15.1
  GEN      doc/automake-1.15.1
make: /Applications/Xcode: No such file or directory
make: *** [install-am] Error 1
```
I renamed the Xcode 8 GM from Xcode.app to Xcode 8.app, because I need to keep 7.1.3 installed. It seems 

Workaround: Renaming Xcode 8.app to Xcode8.app (sans the space), fixes this problem. Still, it shouldn't be necessary.

**Comment by VivaLosDoyers** [comment]
I now see brew doctor specifically warns against this sort of thing. Closing!

**Comment by ilovezfs** [comment]
@VivaLosDoyers FWIW, you could poke upstream about this :)

**Comment by VivaLosDoyers** [comment]
@ilovezfs do you mean reporting this to GNU?

The last time I emailed RMS, it went...poorly :)

**Comment by ilovezfs** [comment]
yep, reporting to GNU. The bug system, not the paranoiac.

**Comment by DomT4** [comment]
Poking RMS with problems impacting a not-completely-free operating system sounds fun 😈. Quite a lot of stuff borks if the path to Xcode has spacing in it, but yeah, feel free to report this upstream & see if they're willing to do something about it.
