### ISSUE TITLE
imagemagick@6.rb has broken URLs

### ISSUE THREAD

**Issue by voldy17** [Homebrew/homebrew-core#46758]
Hello. The URLs listed for 6.9.10-71 (for both the main URL and the mirror) are incorrect, and point to nonexistent files. This results in a Homebrew installation error for imagemagick@6: `curl: (22) The requested URL returned error: 404 Not Found`

Moreover, the newer version 6.9.10-72 was released.

**Comment by fxcoudert** [comment]
> the newer version 6.9.10-72 was released

Can you please provide a pull request to update? Thanks

**Comment by Bo98** [comment]
Is there a reason the mirror hasn't worked? I updated it to `-71` last time and I assumed there was an automated setup for it. Maybe I missed something.

**Comment by voldy17** [comment]
I'm not sure—I didn't have an issue when I upgraded imagemagick on a workstation that had an older version of imagemagick, but ran into this issue when trying to do a fresh install of imagemagick on a workstation that never had it to begin with. In any case, I made a pull request for it! #46759

**Comment by fxcoudert** [comment]
@Bo98 possibly the maintainer who merged the PR forgot to run `brew mirror` at the same time

**Comment by Bo98** [comment]
Ok that makes sense if there's an extra step involved. Sounds it could easily have been missed.
