### ISSUE TITLE
Formula for qt misses include and library path for build from source

### ISSUE THREAD

**Issue by federkamm** [Homebrew/homebrew-core#46756]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to build Qt with Vulkan support (because).

## What happened (include command output)

"brew install -s qt" didn't consider my vulkan libraries in /usr/local (installed with "brew diy").

## What you expected to happen

Qt is building with vulkan support

## Step-by-step reproduction instructions (by running `brew install` commands)

I don't want to write a step-by-step instruction.  It was difficult enough to get vulkan installed and I don't want to burden you to need to reproduce this.

The problem in the end is, that the qt "configure" is stupid and doesn't look at the same places as the (brew) compiler (in /usr/local/bin) does.  It looks for the vulkan header at "the usual places" (which don't include /usr/local) and doesn't find it and decides, it wouldn't be installed and disables it's build.

So actually Qt should be fixed, but since it's more realistic to get this formula updated, I report the "bug" here.

The work around is to add the flag "-I /usr/local/include" to Qt's ./configure call (note the space betwean the flag and the path!).  Probably also "-L /usr/local/lib" should be added and just to be save even "-F /usr/local/Frameworks".  (I don't know which other predependence checks would rely on it.)

With this patch to the qt formula "brew install -s qt" configured and built qt with vulkan support on my computer.

**Comment by fxcoudert** [comment]
Homebrew cannot offer support for such build configurations (building with additional software). We only support build-from-source in known configurations (the ones we can test).

> So actually Qt should be fixed

Indeed. This should be reported and fixed upstream.

Or, if you really want to have a mechanism within Homebrew, you could maintain a patched version in your own tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
