### ISSUE TITLE
macOS Catalina - conjure-up Formula is broken, Jenkins build is broken on master

### ISSUE THREAD

**Issue by apeschel** [Homebrew/homebrew-core#46760]
I'm going to go off format from the issue template here, because it's not appropriate. The conjure-up formula appears to be completely broken on Catalina, and it's blocking Jenkins runs from succeeding.

There appears to be no way to get a functional conjure-up on Catalina with the conjure-up formula at this time.

As a result, it's impossible to open any valid PRs based on master at the moment, since master cannot pass Jenkins CI on Catalina.

I'm not sure what the right option here is, but one of these is probably needed:

* Release a hotfix for the conjure-up formula
* Disable the catalina conjure-up Jenkins CI test.
* Remove the conjure-up formula until it is fixed

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?

## What you were trying to do (and why)

I have been working to get a PR to pass Jenkins CI, but have been encountering unrelated failures on the conjure-up formula for Catalina. I was able to reproduce the failure on my local Catalina machine, so there is pretty strong evidence at this point that the conjure-up Formula is broken on Catalina.

## What happened (include command output)

On macOS Catalina, conjure-up installed from a bottle fails to run, and immediately exits with a non-zero exit code.

Attempting to install conjure-up from source results in a compilation failure:

```
==> /usr/local/Cellar/conjure-up/2.6.9/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/conjure-up--PyNaCl-20191114-54713-1f0704k/PyNaCl-1.3.0
Last 15 lines from /Users/apeschel/Library/Logs/Homebrew/conjure-up/29.pip:
  'build/bdist.macosx-10.15-x86_64' does not exist -- can't clean it
  'build/scripts-3.7' does not exist -- can't clean it
  removing 'build'
Failed to build PyNaCl
Cleaning up...
  Removing source in /private/tmp/pip-req-build-0k23y1h5
Removed build tracker '/private/tmp/pip-req-tracker-_2jv78mn'
ERROR: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/conjure-up/2.6.9/libexec/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/conjure-up/2.6.9/libexec/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 426, in run
    ", ".join(r.name for r in build_failures)))
pip._internal.exceptions.InstallationError: Could not build wheels for PyNaCl which use PEP 517 and cannot be installed directly

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by apeschel** [comment]
Note, there's no relevant gist-log for this:

```
$ brew gist-logs conjure-up
Error: Not Found
```

**Comment by apeschel** [comment]
This appears to be an issue with the `PyNaCl` library, which does not support the `--no-binary` option that is hard coded into every Homebrew `pip install` command. Commenting out this line allows the `conjure-up` build to complete successfully, but results in a runtime error for the missing NaCl library.

Refer to this issue for more info: https://github.com/Homebrew/brew/issues/6200

**Comment by Bo98** [comment]
PyNaCl supports source builds. What’s happening is that there is an error during the build process. Unfortunately I suspect the error can’t be seen in the excerpt above as it is above the 15 line cutoff.

**Comment by bayandin** [comment]
`PyNaCl` uses `libsodium` which [crashes on Xcode < 11.2](https://github.com/jedisct1/libsodium/issues/881). There is a [PR for updating Xcode](https://github.com/Homebrew/brew/pull/6702) is waiting for Xcode update on CI node.

A possible workaround is building `PyNaCl` against homebrew's `libsodium`:
```diff
diff --git a/Formula/conjure-up.rb b/Formula/conjure-up.rb
index 6961171a3e..60777767f9 100644
--- a/Formula/conjure-up.rb
+++ b/Formula/conjure-up.rb
@@ -17,6 +17,7 @@ class ConjureUp < Formula
   depends_on "jq"
   depends_on "juju"
   depends_on "juju-wait"
+  depends_on "libsodium"
   depends_on "libyaml"
   depends_on "pwgen"
   depends_on "python"
@@ -156,6 +157,9 @@ class ConjureUp < Formula
   resource "PyNaCl" do
     url "https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz"
     sha256 "0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c"
+
+    # Allow PyNaCl use libsodium 1.0.18: backport of https://github.com/pyca/pynacl/pull/541
+    patch :DATA
   end
 
   resource "pyRFC3339" do
@@ -248,6 +252,9 @@ class ConjureUp < Formula
     venv.pip_install resource("cffi") # needs to be installed prior to bcrypt
     res = resources.map(&:name).to_set - ["cffi"]
 
+    # Use installed libsodium for PyNaCl
+    ENV["SODIUM_INSTALL"] = "system"
+
     res.each do |r|
       venv.pip_install resource(r)
     end
@@ -262,3 +269,23 @@ class ConjureUp < Formula
                      :exist?
   end
 end
+
+__END__
+diff --git a/setup.py b/setup.py
+index 691291d60607c01f3f443700f22dfdbcc101b11a..3c61ae185b48a5f70be26d8f56083ac78574e036 100644
+--- a/setup.py
++++ b/setup.py
+@@ -138,12 +138,10 @@ def run(self):
+             if e.errno != errno.EEXIST:
+                 raise
+
+-        # Ensure all of our executanle files have their permission set
++        # Ensure all of our executable files have their permission set
+         for filename in [
+                 "src/libsodium/autogen.sh",
+                 "src/libsodium/compile",
+-                "src/libsodium/config.guess",
+-                "src/libsodium/config.sub",
+                 "src/libsodium/configure",
+                 "src/libsodium/depcomp",
+                 "src/libsodium/install-sh",
```

I'd rather wait for Xcode update anyway

**Comment by fxcoudert** [comment]
I've removed the `conjure-up` bottle for Catalina: 464069f02f9f67bdea8a7caf5816d53707e02eb7

**Comment by apeschel** [comment]
@fxcoudert Much appreciated, thank you!
