### ISSUE TITLE
istioctl is not built correctly

### ISSUE THREAD

**Issue by howardjohn** [Homebrew/homebrew-core#46790]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

I don't have a mac so the below is not relevant

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install istioctl 1.4.0

## What happened (include command output)

See https://github.com/istio/istio/issues/17849 for details

`istioctl manifest` is incorrect:
```
✗ istioctl manifest generate | grep 'image:'                 
        image: /citadel:1.4.0
        image: /galley:1.4.0
        image: gcr.io/istio-release/proxyv2:1.4.0
        image: /proxyv2:1.4.0
        image: /sidecar_injector:1.4.0
```

## What you expected to happen

When running from the official istioctl binaries:
```
$ istioctl manifest generate | grep image:
        image: docker.io/istio/citadel:1.4.0
        image: docker.io/istio/galley:1.4.0
        image: docker.io/istio/proxyv2:1.4.0
        image: docker.io/istio/proxyv2:1.4.0
        image: docker.io/istio/sidecar_injector:1.4.0
```

Can this be fixed or a disclaimer added? Our users are installing via a homebrew the istio project doesn't operate and expecting things to work, then attribute the failures back to Istio when things don't

**Comment by fxcoudert** [comment]
> via a homebrew the istio project doesn't operate

We definitely welcome pull requests to fix known issues!

**Comment by howardjohn** [comment]
Can you set `HUB=docker.io` environment variable? I can't figure out where you are building this, if you can point me to it I can send a PR

I can also change the default on istio side, maybe that makes more sense

**Comment by es1o** [comment]
I have the same problem.

I've created a bug in istio github, but istion installed from releases works: https://github.com/istio/istio/issues/19029

**Comment by fxcoudert** [comment]
Our build is very simple: https://github.com/Homebrew/homebrew-core/blob/master/Formula/istioctl.rb#L26

> I can also change the default on istio side, maybe that makes more sense

Maybe.

**Comment by iMichka** [comment]
As a pull request has been opened for this (#46790), I'll close the issue. The discussion can continue on the pull request.
