### ISSUE TITLE
Open-Zwave using wrong version

### ISSUE THREAD

**Issue by Fishwaldo** [Homebrew/homebrew-core#46866]
The formula to build Open-Zwave is not using the latest released versions. 

Versions are released on http://old.openzwave.com/downloads/ and not via the Githib Releases tab, hence the current version is out of date. The current release of OZW is 1.6.962 where as the homebrew is using 1.6.0!

**Comment by fxcoudert** [comment]
We welcome a pull request to update the formula: https://github.com/Homebrew/homebrew-core/pulls
