### ISSUE TITLE
Vault UI not available in this binary

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/homebrew-core#46881]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use the Vault UI

```
vault server -dev
```

## What happened (include command output)

http://127.0.0.1:8200/ui/

In the browser:
Vault UI is not available in this binary

## What you expected to happen

A usable UI in dev mode

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install vault
vault server -dev
open http://127.0.0.1:8200/ui/

**Comment by fxcoudert** [comment]
>  ran brew gist-logs <formula> (where <formula> is the name of the formula that failed) and included the output link?

Nope.

>  if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

Nope.

We welcome a pull request to add it. Right now, we compile with `make dev`, so it appears that upstream is not including it by default.

**Comment by brandonkal** [comment]
It be make bin. Though as they provide some binaries already, that approach would make more sense

**Comment by fxcoudert** [comment]
> they provide some binaries already

Homebrew needs to compile from source
