### ISSUE TITLE
error during protobuf 3.0.2 install

### ISSUE THREAD

**Issue by jmhodges** [Homebrew/homebrew-core#4688]
brew was up to date.

ran `brew upgrade protobuf` to go from 3.0.0 to 3.0.2, and then repeated with uninstalling both versions and ran the install again.

Both of those have this output:

    $  brew install protobuf
    ==> Downloading https://homebrew.bintray.com/bottles/protobuf-3.0.2.el_capitan.bot
    Already downloaded: /Users/jmhodges/Library/Caches/Homebrew/protobuf-3.0.2.el_capitan.bottle.tar.gz
    ==> Pouring protobuf-3.0.2.el_capitan.bottle.tar.gz
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'getusersitepackages'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'getusersitepackages'
    ==> Caveats
    Editor support and examples have been installed to:
      /usr/local/Cellar/protobuf/3.0.2/share/doc/protobuf
    ==> Summary
    🍺  /usr/local/Cellar/protobuf/3.0.2: 250 files, 15.8M

Not sure what's going on there.

**Comment by ilovezfs** [comment]
@jmhodges probably something wrong with your python

**Comment by jmhodges** [comment]
Not sure what that would be. It's the homebrew 2.7.12. My other machine using the OS X default python 2 didn't have the problem.

*shrugs*

**Comment by DomT4** [comment]
CC @tdsmith. Think we've seen this one before, but can't remember what the issue was.

Your `brew config` might be useful.

**Comment by ilovezfs** [comment]
I'd suggest moving the /usr/local/lib/python2.7/site-packages out of the way and reinstalling python.

**Comment by tdsmith** [comment]
Deactivate any virtualenvs prior to installing packages with Homebrew.

**Comment by ilovezfs** [comment]
Assuming this is now fixed.

**Comment by boxed** [comment]
Deactivating the virtualenv before installing is the ticket. But there's still some issue with homebrew because after the failed install it claims it's installed :P
