### ISSUE TITLE
gnuplot not installing with aquaterm support

### ISSUE THREAD

**Issue by alexander-mead** [Homebrew/homebrew-core#46923]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install gnuplot with aquaterm support

## What happened (include command output)

Command: `brew install gnuplot --with-aquaterm`
Output: `Error: invalid option: --with-aquaterm`

<details>
  <summary>brew gist-logs gnuplot</summary>
  <pre>
Error: No logs.
  </pre>
</details>

<details>
  <summary>brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.1.16-87-gd65ad9f
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d65ad9fe1a96fd895d24e097a3d69b9d280ee902
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c3e5374693e080939a2a09e19f0d4c6fb339b64e
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: /usr/bin/emacs
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.2.1
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>
Your system is ready to brew.
  </pre>
</details>

<details>
  <summary>brew info gnuplot</summary>
  <pre>
gnuplot: stable 5.2.7 (bottled), HEAD
Command-driven, interactive function plotting
http://www.gnuplot.info/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnuplot.rb
==> Dependencies
Build: pkg-config ✔
Required: gd ✔, libcerf ✔, lua ✔, pango ✔, qt ✔, readline ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 8,549 (30 days), 26,508 (90 days), 152,298 (365 days)
install_on_request: 5,123 (30 days), 15,456 (90 days), 87,349 (365 days)
build_error: 0 (30 days)
  </pre>
</details>

## What you expected to happen

I expected gnuplot to be installed with aquaterm support. I note that if I do `brew info gnuplot` (see above) `--with-aquaterm` is not listed as an option, but in that case I don't understand why https://formulae.brew.sh/formula/gnuplot suggests that there have been 36 installs with aquaterm support in the last 30 days.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install gnuplot --with-aquaterm`

**Comment by SMillerDev** [comment]
Yes, options have been removed well over a year ago. If you want to modify the way it installs you'll have to maintain a separate copy of a formula in a tap.
