### ISSUE TITLE
Change from mysql-connector-c to mysql-client doesn't contain header files

### ISSUE THREAD

**Issue by merrill-oakland** [Homebrew/homebrew-core#46994]
## Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [- ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install mysql-connector-c to be used with installing MySQL-python.

## What happened (include command output)

When attempting to install MySQL-python, it cannot file my_config.h

<details>
  <summary>Command output</summary>
  <pre>
√ ~ % brew install python2
√ ~ % brew install mysql
√ ~ % brew unlink mysql
√ ~ % brew install mysql-connector-c
√ ~ % brew link mysql --overwrite
?1 ~ % pip install MySQL-python==1.2.3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting MySQL-python==1.2.3
  Downloading https://files.pythonhosted.org/packages/9a/81/924d6799494cf7fb24370335c2f782088d6ac4f79e4137d4df94cea3582c/MySQL-python-1.2.3.tar.gz (70kB)
     |████████████████████████████████| 71kB 3.0MB/s 
Building wheels for collected packages: MySQL-python
  Building wheel for MySQL-python (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-fTye0N/MySQL-python/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-fTye0N/MySQL-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-DYl2Mr --python-tag cp27
       cwd: /private/tmp/pip-install-fTye0N/MySQL-python/
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-2.7
  copying _mysql_exceptions.py -> build/lib.macosx-10.15-x86_64-2.7
  creating build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  copying MySQLdb/__init__.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  copying MySQLdb/converters.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  copying MySQLdb/connections.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  copying MySQLdb/cursors.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  copying MySQLdb/release.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  copying MySQLdb/times.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
  creating build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/__init__.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/CR.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/ER.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/REFRESH.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
  running build_ext
  building '_mysql' extension
  creating build/temp.macosx-10.15-x86_64-2.7
  clang -fno-strict-aliasing -fno-common -dynamic -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Dversion_info=(1,2,3,'final',0) -D__version__=1.2.3 -I/usr/local/Cellar/mysql-client/8.0.18/include/mysql -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _mysql.c -o build/temp.macosx-10.15-x86_64-2.7/_mysql.o
  _mysql.c:36:10: fatal error: 'my_config.h' file not found
  #include "my_config.h"
           ^~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for MySQL-python
  Running setup.py clean for MySQL-python
Failed to build MySQL-python
Installing collected packages: MySQL-python
    Running setup.py install for MySQL-python ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-fTye0N/MySQL-python/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-fTye0N/MySQL-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-qzCptl/install-record.txt --single-version-externally-managed --compile
         cwd: /private/tmp/pip-install-fTye0N/MySQL-python/
    Complete output (30 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-2.7
    copying _mysql_exceptions.py -> build/lib.macosx-10.15-x86_64-2.7
    creating build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    copying MySQLdb/converters.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    copying MySQLdb/connections.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    copying MySQLdb/release.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    copying MySQLdb/times.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb
    creating build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/REFRESH.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.15-x86_64-2.7/MySQLdb/constants
    running build_ext
    building '_mysql' extension
    creating build/temp.macosx-10.15-x86_64-2.7
    clang -fno-strict-aliasing -fno-common -dynamic -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Dversion_info=(1,2,3,'final',0) -D__version__=1.2.3 -I/usr/local/Cellar/mysql-client/8.0.18/include/mysql -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _mysql.c -o build/temp.macosx-10.15-x86_64-2.7/_mysql.o
    _mysql.c:36:10: fatal error: 'my_config.h' file not found
    #include "my_config.h"
             ^~~~~~~~~~~~~
    1 error generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-fTye0N/MySQL-python/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-fTye0N/MySQL-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-qzCptl/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

  </pre>
</details>

## What you expected to happen

All expected headers/files from mysql-connector-c should be present.

## Step-by-step reproduction instructions (by running `brew install` commands)

<pre>
√ ~ % brew install python2
√ ~ % brew install mysql
√ ~ % brew unlink mysql
√ ~ % brew install mysql-connector-c
√ ~ % brew link mysql --overwrite
?1 ~ % pip install MySQL-python==1.2.3
</pre>

## Brew config & doctor 
<details>
  <summary>brew config & brew doctor</summary>
<pre>
√ ~ % brew config                                                                                                                              15:53:19
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 03addf34c9730dda2639bf4b6ec56b44538d8a7d
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 11.0.0.0.1.1567737322
Xcode: N/A
CLT headers: 11.0.0.0.1.1567737322
√ ~ % brew doctor                                                                                                                              15:53:36
Your system is ready to brew.
</pre>
</details>

# Analysis
In and around https://github.com/Homebrew/homebrew-core/commit/01fa86b54a291702edfa36948bc67e7e807a94f1, mysql-connector-c was merged and aliased to mysql-client, but comparing what was previously in /usr/local/Cellar/mysql-connector-c/6.1.11/include and what is in the new /usr/local/Cellar/mysql-client/8.0.18/include, it would seem that all headers are missing, making it not a drop in replacement for the old mysql-connector-c.

**Comment by Bo98** [comment]
> it would seem that all headers are missing

There seems to be some there for me:

```
$ ls /usr/local/Cellar/mysql-client/8.0.18/include/mysql
errmsg.h       my_compress.h  mysql.h       mysql_version.h
field_types.h  my_list.h      mysql_com.h   mysqld_error.h
my_command.h   mysql          mysql_time.h
```

Are you saying it's completely empty for you?

In terms of my_config.h, that is no longer shipped with MySQL 8.0. If you have applications which need it, mysql-client@5.7 has been made available for those compatibility reasons.

**Comment by merrill-oakland** [comment]
D'oh, I was one level too shallow when I ls'ed that. Yeah, that is the files.

And yeah, I was able to do with with @5.7. Sorry to have bothered you with this :/

For others who may stumble upon this, this worked for me:
<pre>
brew install mysql
brew unlink mysql
brew install mysql-client@5.7
brew link mysql-client@5.7 -f
brew link mysql
</pre>

I'm sure there is some better way of doing this, but it is what I could come up with to get the module I need to actually build.

**Comment by merrill-oakland** [comment]
Oh yeah, thanks for your help!

**Comment by Bo98** [comment]
Yeah `brew link` sucks. If you have a way to pass in the mysql_config binary or even a pkg-config file, that would be ideal. But it seems mysql-python hasn't been updated since 2014 so you may be forced with what you have.

I note that you are installing server files too (presumably for another reason since you don't need it to install mysql-client). If you want to have a server, unless you want 8.0, you could also use `mysql@5.7`. All server distributions contain the client files as well, including headers.

**Comment by merrill-oakland** [comment]
Yeah, the particular use case is that I have an application (Moodle) that I want/need to use with current mysql, but there is a helper utility (not written by me) to make dev work easier, but it uses this outdated MySQL-python to do its work.

I know it will break someday, but I'm going to try and push that someday out as long as I can.
