### ISSUE TITLE
Backport Security Fixes for Samba, upgrade it, or kill it.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-core#470]
The branch of Samba we've been on for a while now was EOL'd in 2015, and has consequently stopped receiving security fixes. Putting it mildly getting stuck in this position isn't exactly desirable. You can see just _how much_ Debian has had to backport for this branch of Samba [here](http://metadata.ftp-master.debian.org/changelogs//main/s/samba/samba_3.6.6-6+deb7u9_changelog).

Options:
* Piggyback on Debian, borrow and refine their patches where necessary, bump the revision.
* Upgrade to 4.4.2. @nijikon started work on that [here](https://github.com/Homebrew/legacy-homebrew/pull/47328), I'm not sure on the status of it. I think @mistydemeo said something long long ago about the build system being problematic for OS X on newer releases but I could be misremembering.
* Kill it with 🔥.

**Comment by mikemcquaid** [comment]
> Upgrade to 4.4.2. @nijikon started work on that here, I'm not sure on the status of it. I think @mistydemeo said something long long ago about the build system being problematic for OS X on newer releases but I could be misremembering.
> Kill it with 🔥.

I vote one of these.

**Comment by apjanke** [comment]
Same here. Even if we wanted to do all that backporting work (which I don't think we do), distributing a major EOL'd service with security ramifications like Samba sounds like a bad idea; not something we should be handing our users without some informed opt-in on their part.

I'm not confident that we are even qualified to determine whether we're correctly backporting security fixes to an unsupported version.

**Comment by DomT4** [comment]
I've started working on this and made a fair chunk of progress.

Cleared up two fairly painful-to-debug issues (They've been reported upstream by others, one fixed by FreeBSD's team, one left ignored semi-predictably) but am now stuck on an issue right near the end of the build I haven't managed to work around yet, so I've reported that upstream, where it may well be ignored.

The download numbers for this formula are significant enough to merit fixing it, but upstream OS X support is fairly frustrating. Hopefully they'll get back to me on my bug report and we'll have something shippable soon, but otherwise it'll just have to die.

**Comment by apjanke** [comment]
Ping.

I dunno about you folks, but I'm rather nervous about still shipping a no-security-fixes EOLed-and-highlighted-in-red version to end users. I'd say it's probably time to boneyard it, and bring it back once we can get a supported version building again.

<img width="776" alt="screen shot 2016-05-21 at 8 17 30 pm" src="https://cloud.githubusercontent.com/assets/2618447/15451457/22dfe53e-1f91-11e6-9621-4c1e097134b3.png">

(We're shipping 3.6.25.)

**Comment by DomT4** [comment]
Oh, I have an update ready locally.

I'd been sat on it because there are a few build bugs I had to fix or had been fixed by external folks and needed to be pinged upstream, and then amongst everything else I'd just forgotten about it.

**Comment by DomT4** [comment]
I tell a lie, there's an error remaining in the build process I hadn't managed to kill yet. I'm not going to dive into Samba at 2 in the morning, but I'll set aside some time this PM.

**Comment by MikeMcQuaid** [comment]
Thanks @DomT4!

**Comment by joneskoo** [comment]
@DomT4 Are you still waiting for response from samba upstream? My experiences working with samba have been good, but you are probably right that OS X is hardly a primary platform for most of the developers.

If you're still struggling, have you tried the #samba irc channel on freenode? Maybe someone there may be able to help.

**Comment by DomT4** [comment]
The problem is more "me" at this point, to be honest.

My methodology here has been to extract the tarball, run the build testsuite, run into failure _(repeatedly)_, check the upstream bug tracker to see if that failure has been reported, check FreeBSD's bug tracker & package patches for the same reason, if I know how to fix it leave a comment or submit a patch to that upstream bug report, if I don't know how to fix it do some googling/ducking/your favourite search engine phrase here/etc.

It's a ridiculously time intensive process and there's quite a lot on my plate at the moment; things that require me to have a solid, lengthy block of time are struggling to get slotted into life.

To date:

```diff
diff --git a/Formula/samba.rb b/Formula/samba.rb
index 9fb66d1..aa7ae9b 100644
--- a/Formula/samba.rb
+++ b/Formula/samba.rb
@@ -1,8 +1,8 @@
 class Samba < Formula
   desc "SMB/CIFS file, print, and login server for UNIX"
   homepage "https://samba.org/"
-  url "https://download.samba.org/pub/samba/stable/samba-3.6.25.tar.gz"
-  sha256 "8f2c8a7f2bd89b0dfd228ed917815852f7c625b2bc0936304ac3ed63aaf83751"
+  url "https://download.samba.org/pub/samba/stable/samba-4.4.4.tar.gz"
+  sha256 "262f9edabbd1c0112819b5063718588c22b0ee4c1a2f648f79f233fdfba25c8b"
 
   bottle do
     revision 1
@@ -12,6 +12,9 @@ class Samba < Formula
     sha256 "f6c02ca7f1dd074a3b5c021810351904cbe8b447bd81adc9598e64e1eb342e10" => :mountain_lion
   end
 
+  depends_on "pkg-config" => :build
+  depends_on "gnutls"
+
   conflicts_with "talloc", :because => "both install `include/talloc.h`"
 
   # Once the smbd daemon is executed with required root permissions
@@ -22,36 +25,51 @@ class Samba < Formula
   # Fixes the Grouplimit of 16 users os OS X.
   # Bug has been raised upstream:
   # https://bugzilla.samba.org/show_bug.cgi?id=8773
+  # Still seems to be relevant, even for 4.x series.
   patch :DATA
 
   conflicts_with "jena",
     :because => "both install `tdbbackup` and `tdbdump` binaries"
 
   def install
-    cd "source3" do
-      # This stops samba dumping .msg and .dat files directly into lib
-      # It can't be set with a configure switch - There isn't one that fine-grained.
-      # https://bugzilla.samba.org/show_bug.cgi?id=11120
-      inreplace "configure", "${MODULESDIR}", "#{share}/codepages"
+    # I'm not completely sure why this works, but it seems to do so.
+    # https://bugzilla.samba.org/show_bug.cgi?id=11811
+    inreplace "lib/param/loadparm.h", "#include <talloc.h>",
+              "#include <talloc.h>\n#include <time.h>"
 
-      system "./configure", "--disable-debug",
-                            "--prefix=#{prefix}",
-                            "--with-configdir=#{prefix}/etc",
-                            "--without-ldap",
-                            "--without-krb5"
+    # https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208767
+    # https://bugzilla.samba.org/show_bug.cgi?id=11864
+    inreplace "source3/client/smbspool_krb5_wrapper.c",
+              "clearenv();", "environ[0] = NULL;"
 
-      # https://bugzilla.samba.org/show_bug.cgi?id=11113
-      inreplace "Makefile" do |s|
-        s.gsub! /(lib\w+).dylib(.[\.\d]+)/, "\\1\\2.dylib"
-      end
+    args = %W[
+      --prefix=#{prefix}
+      --sysconfdir=#{etc}
+      --without-ldap
+      --without-ads
+      --without-gettext
+      --enable-fhs
+      --enable-gnutls
+    ]
+    # "ACL support not available on Darwin/MacOS".
+    args << "--without-acl-support"
+    # This tells the waf build process to ignore WAFCACHE if set.
+    args << "--nocache"
 
-      (prefix/"private").mkpath
-      (prefix/"var/locks").mkpath
+    system "./configure", *args
 
-      system "make", "install"
-      # makefile doesn't have an install target for these
-      (lib/"pkgconfig").install Dir["pkgconfig/*.pc"]
-    end
+    # https://bugzilla.samba.org/show_bug.cgi?id=11113
+    #inreplace "Makefile" do |s|
+    #  s.gsub! /(lib\w+).dylib(.[\.\d]+)/, "\\1\\2.dylib"
+    #end
+
+    (prefix/"private").mkpath
+    (prefix/"var/locks").mkpath
+
+    system "make"
+    system "make", "install"
+    # makefile doesn't have an install target for these
+    (lib/"pkgconfig").install Dir["pkgconfig/*.pc"]
 
     # Install basic example configuration
     inreplace "examples/smb.conf.default" do |s|
@@ -71,7 +89,7 @@ class Samba < Formula
         <string>#{plist_name}</string>
         <key>ProgramArguments</key>
         <array>
-          <string>#{sbin}/smbd</string>
+          <string>#{opt_sbin}/smbd</string>
           <string>-s</string>
           <string>#{etc}/smb.conf</string>
         </array>

```

The `"clearenv();"` bug should have been fixed in 4.4.4 but I haven't checked the new source yet to make sure.

This is the current build error:

```
[3623/3667] Linking default/source3/modules/libvfs_module_linux_xfs_sgid.dylib
[3624/3667] Linking default/source3/smbd/smbd
[3625/3667] Linking default/source3/modules/libvfs_module_time_audit.dylib
[3626/3667] Linking default/source3/modules/libvfs_module_shadow_copy.dylib
Undefined symbols for architecture x86_64:
  "_getgrent_r", referenced from:
      _test_enum_r_group in nss_tests_1.o
  "_getpwent_r", referenced from:
      _test_enum_r_passwd in nss_tests_1.o
[3627/3667] Linking default/source3/modules/libvfs_module_shell_snap.dylib
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Waf: Leaving directory `/private/tmp/samba-20160613-20390-awnvo3/samba-4.4.4/bin'
```
That function doesn't exist on OS X, AFAIK, and indeed the build script checks a bunch of those to see whether or not they exist, but that one seems to sneak in unconditionally regardless of the prior check and I haven't yet had the time to go punch it on the nose yet.

**Comment by MikeMcQuaid** [comment]
Let's kill it.

**Comment by apjanke** [comment]
:+1: to killing it. This is turning in to a "porting to OS X" project instead of just packaging.

**Comment by DomT4** [comment]
Dead: https://github.com/Homebrew/homebrew-boneyard/commit/e1563874a233c0afc8e10b7733d00635fd552201.
