### ISSUE TITLE
graphviz requires patch to build with ghostscript 9.18

### ISSUE THREAD

**Issue by karanlyons** [Homebrew/homebrew-core#4704]
Apologies for not just submitting a pull, but I’m unsure of how exactly this should be implemented (inreplace or patch?).

ghostscript 9.18 renamed some of their identifiers for errors: they now use the `gs_error_` prefix instead of `e_` as previously. This only affects one file in graphviz: plugin/gs/gvloadimage_gs.c.

More information (Google thankfully saved me from debugging this myself) can be found here: http://lists.linuxfromscratch.org/pipermail/blfs-book/2015-October/056960.html

A quick test with adding `inreplace "plugin/gs/gvloadimage_gs.c", ' e_', ‘ gs_error_'` to the formula succeeds, but I’m not sure that’s the preferred way to make this change.

**Comment by ilovezfs** [comment]
the inreplace would be fine. the main thing here is to get the problem reported upstream so they can fix it "for real" and then slip the link to your upstream issue into the pr.

**Comment by karanlyons** [comment]
There’s already been a fix made in the repo for graphviz (https://github.com/ellson/graphviz/blob/master/plugin/gs/gvloadimage_gs.c#L36-L51) but I don’t think it’s made it to release yet.

**Comment by ilovezfs** [comment]
Ah, OK. Then, if possible, we'll want to add that commit as a `patch do` block inside a `stable do` block, assuming it applies cleanly to 2.38.0 and builds.

**Comment by karanlyons** [comment]
Done at https://github.com/Homebrew/homebrew-core/pull/4705

**Comment by zmwangx** [comment]
Closing in favor of the PR.
