### ISSUE TITLE
enchant formula symlink enchant-2.pc to enchant.pc

### ISSUE THREAD

**Issue by hfiguiere** [Homebrew/homebrew-core#47074]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Compile something that uses enchant but not enchant-2

## What happened (include command output)

It fails because enchant-2 doesn't have the same API. However it detect the dependency because Brew symlink enchant.pc making pkgconfig believe that enchant is here (with the old API)

See the formula:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/enchant.rb#L24

## What you expected to happen

That with enchant 2.x there be no enchant.pc.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install enchant.

**Comment by Bo98** [comment]
Looking at what other repositories do:
* Debian (experimental) uses enchant.pc only.
* Alpine uses enchant-2.pc only.
* CentOS uses enchant-2.pc only.
* Fedora uses enchant-2.pc only.

We'll need to also see how other formulae which depend on enchant behave if this is changed.

**Comment by hfiguiere** [comment]
Enchant 2 has a different API hence the `enchant-2.pc`. This is not gratuitous it's just the way things are done. 

Fedora, which I have right here, also ship 1.6 for those packages that haven't been updated to the newer API.

**Comment by fxcoudert** [comment]
OK to remove the symlink if that doesn't break building these:

```
$ brew uses --recursive enchant
evince                  gitg                    gnome-latex             gspell                  gtranslator
gedit                   gnome-builder           gnome-recipes           gtkspell3
```
