### ISSUE TITLE
Coreutils: missing --reflink support (not brew's fault; patch available)

### ISSUE THREAD

**Issue by Artoria2e5** [Homebrew/homebrew-core#47082]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (It did not fail)

## What you were trying to do (and why)

APFS is very cool with all these copy-on-write features, but there is no such thing as a working reflink=auto in any current implementations. The system cp has `-c` but does not retry as a normal copy after failure, and the GNU cp simply does not support reflink and always falls back to normal copy.

## What happened / reproduction0

```
$ time gdd if=/dev/urandom of=test bs=64M count=8
8+0 records in
8+0 records out
536870912 bytes (537 MB, 512 MiB) copied, 1.21565 s, 442 MB/s

real 0m1.235s
user 0m0.002s
sys 0m1.187s
$ time gcp --reflink=auto test test.2

real 0m0.689s
user 0m0.002s
sys 0m0.360s
```

## What you expected to happen

`--reflink=auto` should be instant.

## Fixing this issue

I have a patch to add support for reflinking:
* On 8.31: Artoria2e5/coreutils@bcbc36a
* On future HEAD: Artoria2e5/coreutils@22fccf1

It is upstreamed in the [mailing-list](https://lists.gnu.org/archive/html/coreutils/2019-11/msg00001.html), but from the looks of it not many people use macOS on there.

I figured that instead of just creating a PR (without changing bottles and stuff) it would be more appropriate to have a pretext for it as an issue. Plus, you can have a chance at [turning some extra knobs such as the one in `ginstall`](https://unix.stackexchange.com/a/550932/73443)...

**Comment by fxcoudert** [comment]
Sorry, we don't include experimental functionality. Your best course of action is to make your case to upstream to get it included.
