### ISSUE TITLE
Geocouch shasum changed

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-core#471]
The SHA sum for the current `geocouch` file (https://github.com/couchbase/geocouch/archive/couchdb1.3.x.tar.gz) has changed some time between July 2014 and now, so attempts to install from source get a SHA mismatch error.

```
$ brew install geocouch -s
==> Using the sandbox
==> Downloading https://github.com/couchbase/geocouch/archive/couchdb1.3.x.tar.gz
Already downloaded: /Library/Caches/Homebrew/geocouch-1.3.0.tar.gz
Error: SHA256 mismatch
Expected: 0f678b5b79f5385c5c11349b662bb897047c72e8056dfb19f0f1e484d9348953
Actual: 1bad2275756e2f03151d7b2706c089b3059736130612de279d879db91d4b21e7
Archive: /Library/Caches/Homebrew/geocouch-1.3.0.tar.gz
To retry an incomplete download, remove the file above.
```

I've posted this upstream at https://forums.couchbase.com/t/geocouch-couchdb1-3-x-tar-gz-checksum-changed/7889.

**Comment by DomT4** [comment]
It changes every now and again. See https://github.com/Homebrew/homebrew-core/pull/436, https://github.com/Homebrew/legacy-homebrew/issues/42498, https://github.com/Homebrew/legacy-homebrew/issues/49813, etc.

The problem in part is that we're not using a real tarball. It's tied to the upstream [branch](https://github.com/couchbase/geocouch/tree/couchdb1.3.x) and every time they push a new commit or do something that tweaks the git history the checksum borks.

We could probably deal with this more obviously by using a git checkout, branch and revision, but that won't address the root problem that we're not using a "real" tag or release point.

**Comment by apjanke** [comment]
I think this is also a problem with a redirect not being followed, too. I get the same SHA when I download other geocouch versions as a `resource` in a formula.

I'll just bump the SHA value once I get the redirect figured out; you're right about other options not addressing the problem.
