### ISSUE TITLE
Use notarization for pre-built Catalina binaries

### ISSUE THREAD

**Issue by paulmillr** [Homebrew/homebrew-core#47129]
Starting from 2020, Catalina would require apps to be [notarized](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution).

I think homebrew should use notarization and sign binaries. This would fix the "unproven software" warnings.

**Comment by jonchang** [comment]
I don’t see anything in the linked article suggesting that this would apply to command line software that Homebrew installs in 2020. Since we don’t set the quarantine flag on binary bottles poured I don’t think we need notarization quite yet. Happy to be corrected though if you have a better link.

**Comment by paulmillr** [comment]
I think it’s applied to all software.

**Comment by SMillerDev** [comment]
This is not the place for this issue as it's not about the software that homebrew builds but about the wag the brew install process works. 

Do you have any sources to back that claim about the requirement in 2020 up?

**Comment by paulmillr** [comment]
I was not able to find proper place for the issue, github issue templates don't have an option about `wag`.

Just tried setting time manually to 2020. Seems like it works! So, can't confirm this.

**Comment by SMillerDev** [comment]
Reading the documentation you send it also seems to be about apps that you build using xcode which is not the case for most homebrew software. I'm going to close this and you should create an issue with actual sources for your claims in `homebrew/brew` if you can find them.
