### ISSUE TITLE
Dynamic lib support for llvm?

### ISSUE THREAD

**Issue by fduxiao** [Homebrew/homebrew-core#47142]
Why only static libs are provided for llvm?  [`llvm-hs`](https://github.com/llvm-hs/llvm-hs) support only linking against dynamic libs if you don't specify the compilation flag explicitly. [It is suggested](https://github.com/llvm-hs/llvm-hs/issues/283) that I should always link against dynamic libs in a developing environment(e.g. MacBook). Could you configure `llvm` to provide dynamic libs?

**Comment by Bo98** [comment]
The LLVM formula already does come with libLLVM.dylib. This contains all of LLVM's components in a single shared library. We use LLVM_BUILD_LLVM_DYLIB to do that:

> If enabled, the target for building the libLLVM shared library is added. This library contains all of LLVM’s components in a single shared library.

The other approach of splitting this shared library into individual components is strongly discouraged by LLVM:

> BUILD_SHARED_LIBS is only recommended for use by LLVM developers. If you want to build LLVM as a shared library, you should use the LLVM_BUILD_LLVM_DYLIB option.

**Comment by Bo98** [comment]
I think I see the issue you are having. Unfortunately, `llvm-config` is non-functional by default when you build a combined shared library. It expects `libLLVM-9.dylib` but LLVM's build scripts only install `libLLVM.dylib`. `llvm-config` has been broken by default on macOS for a few years now, but does work on Linux I believe.

I've opened a pull request to discuss what we can do from our side.

**Comment by fduxiao** [comment]
👍

**Comment by fduxiao** [comment]
Wait a second. I have tried solving this by making a symbolic link. Originally, stack (a Haskell build tool) only complained about the missing versioned shared lib `llvm-config: error: libLLVM-9.dylib is missing`. However, after I had made the symbolic link (`llvm-config --share-mode` still gives `static`), it continued to complained about other missing shared libs:
```
llvm-hs> llvm-config: error: missing:
llvm-hs> /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMDemangle.dylib
llvm-hs> llvm-config: error: missing:
llvm-hs> /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMSupport.dylib
llvm-hs> llvm-config: error: missing:
llvm-hs> /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMAArch64Info.dylib
... ...
```

Is this also caused by the same issue with llvm?

**Comment by Bo98** [comment]
I'll check when the CI finished the build - it's far too long to do it on my own machine - but does `llvm-config --link-shared` function?

**Comment by fduxiao** [comment]
@Bo98 Sorry for late response. I tried with `llvm-config --link-shared --shared-mode` and it gave
```
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMDemangle.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMSupport.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMAArch64Info.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMAArch64Utils.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMBinaryFormat.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMDebugInfoMSF.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMDebugInfoCodeView.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMMC.dylib
llvm-config: error: missing: /usr/local/Cellar/llvm/9.0.0_1/lib/libLLVMAArch64Desc.dylib
......
```
Also, I tried compiling this [example](https://github.com/llvm/llvm-project/tree/master/llvm/examples/BrainF) with
```shell
$ clang++ `llvm-config --cxxflags --ldflags --system-libs --libs core orcjit native mcjit --link-shared` BrainF.cpp BrainFDriver.cpp
```
llvm still complains about the missing libs, but I can compile it without `--link-shared` flag :
```shell
$ clang++ `llvm-config --cxxflags --ldflags --system-libs --libs core orcjit native mcjit` BrainF.cpp BrainFDriver.cpp
$ otool -L a.out
a.out:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/local/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```
It seems that `a.out` is linked statically but I have no idea why it is linked against the libc++ provided by llvm. There is no extra flags set in the environment.

**Comment by fxcoudert** [comment]
This should be fixed on the LLVM side, really.
