### ISSUE TITLE
john: fopen: /usr/local/share/john/john.conf: No such file or directory

### ISSUE THREAD

**Issue by Phuker** [Homebrew/homebrew-core#47164]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `john` formula, and run it

## What happened (include command output)

I run `john` command, and see this:

<details>
  <summary>Command output</summary>
  <pre>
$ john
fopen: /usr/local/share/john/john.conf: No such file or directory
  </pre>
</details>

## What you expected to happen

No error, and john runs like this:

```
$ john
John the Ripper password cracker, version 1.9.0
Copyright (c) 1996-2019 by Solar Designer
```

## Step-by-step reproduction instructions (by running `brew install` commands)

Just run:

```shell
brew install john
```
It download a bottle and installed as normal. And then:

```
$ john
fopen: /usr/local/share/john/john.conf: No such file or directory
```

As i checked it, `/usr/local/share/john` not even exist. And this is how i fix it manually:

```shell
cd /usr/local/share
ln -s /usr/local/Cellar/john/1.9.0/libexec john
cd john
cp john.ini john.conf
```

and now it seem works.

My versions:

```
$ brew config
HOMEBREW_VERSION: 2.1.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3aa7624284c43180a3f3a71aeaa9263092868e12
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 992e817c65f5ab22df5d7f1eb08e38924eeafd9a
Core tap last commit: 62 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_202
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
CLT headers: 10.3.0.0.1.1562985497
```

Discussion before at discourse.brew.sh: [https://discourse.brew.sh/t/john-fopen-usr-local-share-john-john-conf-no-such-file-or-directory-is-it-reproducible/6328](https://discourse.brew.sh/t/john-fopen-usr-local-share-john-john-conf-no-such-file-or-directory-is-it-reproducible/6328)

**Comment by nicmilot** [comment]
I had the same problem and used the same fix as Phuker. Thanks a lot

**Comment by issyl0** [comment]
In progress in #49454.

**Comment by glensc** [comment]
I was about to report the same issue. The program should include caveats or made work out of the box.


```
➔ brew install john
==> Downloading https://homebrew.bintray.com/bottles/john-1.9.0.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/77/775f6a757aa829e874edb00b184a6c8cff028506f971d5b220b36194feb0c6eb?__gda__=exp=1580901022~hmac=064cada43485ed7f5f
######################################################################## 100.0%
==> Pouring john-1.9.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/john/1.9.0: 36 files, 19.6MB

➔ john
fopen: /usr/local/share/john/john.conf: No such file or directory
➔
```

**Comment by coderanger** [comment]
A quick solution:

```
cp /usr/local/Cellar/john/1.9.0/libexec/john.ini ~/.john/john.conf
```

**Comment by MicrosoftAxel** [comment]
Still the same problem. Fixed worked
