### ISSUE TITLE
assimp5 find_package(assimp) failing

### ISSUE THREAD

**Issue by lrapetti** [Homebrew/homebrew-core#47210]
- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ n/a ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ n/a ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have installed assimp via `brew install assimp`, but cmake is failing in finding it via `find_package(assimp)` since `assimp5` was merged (previous working commit: https://raw.githubusercontent.com/Homebrew/homebrew-core/ca08d3c78a9a8f4e6a5249389442ebcb962eea0d/Formula/assimp.rb)

## What happened (include command output)

The output of the error is the following:
```
CMake Error at /usr/local/lib/cmake/assimp-5.0/assimpTargets.cmake:85 (message):
  The imported target "assimp::assimp" references the file

     "/usr/local/lib/libassimp.dylib.5"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/assimp-5.0/assimpTargets.cmake"

  but not all the files it references.
```

**Comment by lrapetti** [comment]
Related issue in assimp https://github.com/assimp/assimp/issues/2760

**Comment by Bo98** [comment]
We can carry the patch for it, though ideally the patch should be approved upstream first.

**Comment by fxcoudert** [comment]
Thanks. Once the patch is merged upstream, we'll gladly consider a pull request to ship it in our formula.

**Comment by lrapetti** [comment]
> Thanks. Once the patch is merged upstream, we'll gladly consider a pull request to ship it in our formula.

@fxcoudert the fix is now merged https://github.com/assimp/assimp/pull/2765

**Comment by nuclearsandwich** [comment]
@fxcoudert I opened #47792 which incorporates the patch from upstream.
