### ISSUE TITLE
Conflict between Octave and TexShop

### ISSUE THREAD

**Issue by kallewoof** [Homebrew/homebrew-core#4732]
Installing octave gives a

```Error: You must `brew link ghostscript` before homebrew/science/octave can be installed```

However, `brew link ghostscript` gives

```
Linking /usr/local/Cellar/ghostscript/9.19...
Error: Could not symlink bin/dvipdf
Target /usr/local/bin/dvipdf
already exists. You may want to remove it:
  rm '/usr/local/bin/dvipdf'
```

but this file (and others) are a part of the TexShop installation (***I think***), and I don't want to remove them as I don't want to risk breaking TexShop. (I don't know how to verify whether this is the case or not.)

**Comment by zmwangx** [comment]
>  a part of the TexShop installation

You mean part of the MacTeX distribution.

Yes, unfortunately MacTeX does ship ghostscript which conflicts with Homebrew. However, according to `/Applications/TeX/What Is Installed.pdf`,

> The Macintosh comes with a distiller which converts postscript to pdf: /usr/bin/pstopdf. For this reason, it is not essential to install Ghostscript when installing TeX. However some TeX style ﬁles assume the existence of Ghostscript and many people prefer to distill using it. Any Ghostscript installation will do, and some users have the Fink or MacPorts distributions, which all work well with TeX. For others we provide the latest version of Ghostscript in this package.

so I would say overriding them isn't too big a deal (also, MacTeX 2016 ships ghostscript 9.19 which is the same version shipped by Homebrew). I've done that before (though I don't have gs linked right now) and didn't run into trouble. Still, proceed with caution and don't blame me if your stuff breaks.

I'm closing this issue since there's not much we can do with software you install outside Homebrew. Please don't hesitate to ask if you have further questions.

**Comment by zmwangx** [comment]
> some users have the Fink or MacPorts distributions

By the way, it's a shame they don't mention Homebrew (but this document was written long ago and haven't changed since). Probably I'll file a bug somewhere 😛

**Comment by kallewoof** [comment]
Thanks for the info! So there's no way to convince HomeBrew that I have a functional GhostScript installed for Octave? I guess this is a MacTex issue ultimately.

**Comment by zmwangx** [comment]
> So there's no way to convince HomeBrew that I have a functional GhostScript installed for Octave?

One of the reasons Homebrew *just works* 99% of the time (disclaimer: I haven't actually checked the percentage) is that we depend on things that we have tested instead of letting you satisfy dependencies however you want. Our installation also depends on some internal "cellar" paths which you won't have if you did not install gs through Homebrew.

> I guess this is a MacTex issue ultimately.

Not really, they ship ghostscript with good will, and installing to `/usr/local` is perfectly valid. Conflicts between different software projects are ultimately inevitable though since there's not a single overarching consortium coordinating all projects, which is a good thing. (Plus the fact that we even have conflicting formulae inside Homebrew.)

**Comment by ilovezfs** [comment]
@zmwangx Given https://github.com/Homebrew/brew/blob/master/Library/Homebrew/requirements.rb#L78-L94 this is more than something we can write off. I think we need to consider make ghostscript, etc. keg_only unless someone can convince MacTex upstream to move their stuff elsewhere.

**Comment by ilovezfs** [comment]
@kallewoof in the case of octave, you can replace the ghostscript and pstoedit dependencies with a `depends_on :tex` which will then use your MacTex installation for those commands.

**Comment by zmwangx** [comment]
> this is more than something we can write off.

Makes sense, didn't think about `depends_on :tex`.

> keg_only 

No problem with that.

> convince MacTex upstream to move their stuff elsewhere

`/Library/TeX/texbin` is a natural choice for TeX-related binaries but then where does ghostscript actually live? It doesn't fit into `/Library/TeX/Distributions`. I'd say this is a dead end.

**Comment by zmwangx** [comment]
> in the case of octave, you can replace the ghostscript and pstoedit dependencies with a depends_on :tex which will then use your MacTex installation for those commands.

Com'on let's don't confuse users.

**Comment by ilovezfs** [comment]
>Com'on let's don't confuse users.

I've personally dealt with this octave problem in that exact way because the current situation is rather broken, which a brief search of octave in the homebrew/science repo's issues will show you.

**Comment by ilovezfs** [comment]
>I'd say this is a dead end.

My current view is we should probably kill off the relevant formulae in favor of a :tex dependency (i.e., in favor of the MacTex cask).

**Comment by zmwangx** [comment]
> My current view is we should probably kill off the relevant formulae in favor of a :tex dependency.

Asking people to download a 2.8G installer which deflates to 5.2G isn't particularly encouraging. Also, gs isn't part of TeXLive so asking people to depend on `:tex` for gs is rather weird.

We don't have a mechanism to specify if some dependency is already met, do we?

**Comment by DomT4** [comment]
Stuff with any new hard `:tex` dependency would be banished to the `tex` tap, FWIW.

**Comment by ilovezfs** [comment]
@DomT4 yes and that's perfectly fine if it means actually works properly ;)

**Comment by kallewoof** [comment]
I'm not really well-versed on the subject but the MacTex docs seem to indicate ghostscript is not needed, which seems to indicate the problem should ideally be solved by removing ghostscript in MacTex. Maybe with a 'if you do need ghostscript, grab HomeBrew and brew install ghostscript' notice on their end. MacTex is bloated as it is, making it smaller can't be a bad thing.

> C'mon let's don't confuse users.

To be honest, I was at a dead end here, and the comment at least gave me *a* solution that didn't involve me hoping that things work out with two conflicting installations of the same package. That being said, I don't actually know how to do what was suggested, but I can figure that out on my own.

**Comment by zmwangx** [comment]
> I was at a dead end here.

Well, can't you just force link?

Of course you'll run into permission issues, but it's easy to list stuff that needs to be overwritten (`brew link -n gs`) and change the ownership of those files first.

> That being said, I don't actually know how to do what was suggested, but I can figure that out on my own.

Which is why I said "don't confuse users".

But here's what he meant. Apply this patch to `octave.rb`:

```diff
@@ -106,11 +106,13 @@ class Octave < Formula
   depends_on "readline"       => :recommended
   depends_on "arpack"         => :recommended
   depends_on "epstool"        => :recommended
-  depends_on "ghostscript"    => :recommended  # ps/pdf image output
+  # depends_on "ghostscript"    => :recommended  # ps/pdf image output
   depends_on "gl2ps"          => :recommended
   depends_on "graphicsmagick" => :recommended  # imread/imwrite
   depends_on "transfig"       => :recommended

+  depends_on :tex             => :recommended
+
   # conditional dependecies (explicit options)
   depends_on "curl"            if build.with?("curl") && MacOS.version == :leopard
   depends_on "fftw"            if build.with? "fftw"
@@ -120,7 +122,7 @@ class Octave < Formula
   depends_on "hdf5"            if build.with? "hdf5"
   depends_on :java => "1.6+"   if build.with? "java"
   depends_on "llvm"            if build.with? "jit"
-  depends_on "pstoedit"        if build.with? "ghostscript"
+  # depends_on "pstoedit"        if build.with? "ghostscript"
   depends_on "qhull"           if build.with? "qhull"
   depends_on "qrupdate"        if build.with? "qrupdate"
   depends_on "suite-sparse"    if build.with? "suite-sparse"
```

Hopefully I didn't screw up.

**Comment by ilovezfs** [comment]
>Hopefully I didn't screw up.

Yup, that looks good to me.

**Comment by ilovezfs** [comment]
>We don't have a mechanism to specify if some dependency is already met, do we?

What do you mean?

**Comment by zmwangx** [comment]
> What do you mean?

```
if TeXRequirement.satisfied?
  # golden
else
  depends_on "ghostscript"
end
```

Something like that?

**Comment by zmwangx** [comment]
Or a mechanism for alternative dependency: `:tex` or `"ghostscript"`.

**Comment by ilovezfs** [comment]
We could create a :ghostscript requirement that can be fulfilled by MacTex cask or ghostscript keg only formula.

**Comment by ilovezfs** [comment]
But given how much hatred there is of :tex and requirements, a keg only formula that's used regardless of whether you have MacTex is probably the solution that annoys the smallest number of people.

**Comment by zmwangx** [comment]
Kind of an overkill (I think requirements are for popular and somewhat hard-to-meet dependencies), but at least it solves the problem, so I'm cool with that.

**Comment by ilovezfs** [comment]
The existence of requirements is overkill, and they all probably create approximately 3x as many problems as they solve.

**Comment by zmwangx** [comment]
Huh.

**Comment by ilovezfs** [comment]
In other words, in the short term, we should probably see how far we can get just by going keg only with the problem children.

**Comment by zmwangx** [comment]
👍

**Comment by zmwangx** [comment]
@ilovezfs Care to submit a PR?

**Comment by ilovezfs** [comment]
maybe after I'm done battling the five million hdf5 PRs lol

**Comment by zmwangx** [comment]
You should put them in one PR and set Jenkins timeout to 32767 minutes.

**Comment by ilovezfs** [comment]
yeah, you haven't dealt with the science tap much yet, have you?

**Comment by zmwangx** [comment]
No, not a fan of science apparently :trollface:
