### ISSUE TITLE
How to install openssl 1.0?

### ISSUE THREAD

**Issue by Paxa** [Homebrew/homebrew-core#47348]
Update updating some packages I got alot of broken tools: ruby (via rbenv), python, mysql, etc that all have runtime dependencies to openssl 1.0

How to bring back openssl 1.0?

**Comment by Paxa** [comment]
Worked like this:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/64555220bfbf4a25598523c2e4d3a232560eaad7/Formula/openssl.rb -f
```
No issues so far with dependencies compiled for `openssl@1.1`

**Comment by SMillerDev** [comment]
You should just upgrade the tools to allow them to use the new openssl. 1.0 is deprecated and will be practically insecure in a month.

**Comment by Paxa** [comment]
May sounds easy to upgrade all tools. But I have too many tools to upgrade, and need to actually do some work instead of recompiling all ruby with all extensions and many other tools

Many languages have native extensions and `brew upgrade` can not know about them.

IMO brew should still keep `openssl@1.0` at least for 1 month and show warning, instead of breaking things

**Comment by pululin** [comment]
I had the same problem.
