### ISSUE TITLE
Homebrew pkg-config issue assimp 5.0

### ISSUE THREAD

**Issue by ctreffs** [Homebrew/homebrew-core#47405]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config:`
```sh
HOMEBREW_VERSION: 2.2.0-39-g1c9e30e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c9e30e24f2bcbb7a59a3b88704fdb87b22c5a81
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 350f7ec04c6030438688cce516636c70ca05d9b1
Core tap last commit: 53 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_191, 1.8.0_102, 1.7.0_80
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.1 => /Applications/Xcode-11.1.app/Contents/Developer
CLT headers: 10.3.0.0.1.1562985497
XQuartz: 2.7.11 => /opt/X11
```
## What you were trying to do (and why)

Access `assimp: stable 5.0.0 (bottled)`  using `assimp.pc`.

## What happened (include command output)

The library could not be found, since the pkg-config file did not point to the right directory.

## What you expected to happen

The library should be found in the include directory.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install assimp`
2. `pkg-config assimp --libs --cflags`

---

The current package of assimp available via homebrew seems to have an issue in it's pkg-config file.

Specifically the include path seems to be formed wrong.

I'm testing this on macOS Mojave 10.14.6 (18G2016) with HOMEBREW_VERSION: 2.2.0 and the latests formulae.

The last version of `assimp.pc` looked like this:
```sh
prefix=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0
exec_prefix=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0/
libdir=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0/lib
includedir=@@HOMEBREW_PREFIX@@/Cellar/assimp/4.1.0/include

Name: Assimp
Description: Import various well-known 3D model formats in an uniform manner.
Version: 4.1.0
Libs: -L${libdir} -lassimp
Libs.private: -lstdc++ -lz
Cflags: -I${includedir}

```
whereas the current file looks like this:

```sh
prefix=@@HOMEBREW_CELLAR@@/assimp/5.0.0
exec_prefix=@@HOMEBREW_CELLAR@@/assimp/5.0.0/
libdir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/lib
includedir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/../include/include

Name: Assimp
Description: Import various well-known 3D model formats in an uniform manner.
Version: 5.0.0
Libs: -L${libdir} -lassimp
Libs.private: -lstdc++ -lz
Cflags: -I${includedir}
```

The change that causes the issue is the following line:
`includedir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/../include/include`
which imo should look like this:
`includedir=@@HOMEBREW_CELLAR@@/assimp/5.0.0/include`

I am willing to help to resolve this issue if someone could point me in the right direction where to update what :-)

---

I created a related issue in the assimp issue tracker: https://github.com/assimp/assimp/issues/2804

**Comment by fxcoudert** [comment]
The change is an intentional choice by upstream: see https://github.com/assimp/assimp/commit/b506d35999edcec448b71fa3545f937b9f04dcc2

This should be fixed by `assimp`. The path they write is wrong, and not only for Homebrew, but for any install that sets `CMAKE_INSTALL_PREFIX`.
