### ISSUE TITLE
Beagle package not providing GPU plugin

### ISSUE THREAD

**Issue by kusalananda** [Homebrew/homebrew-core#47523]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

* `brew gist-logs beagle` outputs `Error: No logs.`
* `brew doctor` outputs `Your system is ready to brew.`
* `brew config` output below:

```
HOMEBREW_VERSION: 2.2.0-61-g3383ae7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3383ae7736e71dc96e7ad0875a8fd823e0db92dc
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f5fdc6f7869b610b1bb4cdf10aaac779ebb85638
Core tap last commit: 75 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 11.2.0.0.1.1571444319
Xcode: 11.2.1
CLT headers: 11.2.0.0.1.1571444319
```

## What you were trying to do (and why)

Trying to use the `beagle` package from Homebrew with `mrbayes` (from the `brewsci/bio` cask) works, but `beagle`, as packaged by Homebrew, does not allow for using GPU plugins (these are not compiled in the `beagle` package).

## What happened (include command output)

The MrBayes program does not use GPU at all, but can be made to use the Beagle library, which should support running on GPUs.  Starting MrBayes and giving it the `showbeagle` command does not show a GPU resource even on hardware with a GPU available. This is due to the Beagle library not having been compiled to support GPU.

<details>
  <summary>Command output</summary>
  <pre>
$ mb

                            MrBayes 3.2.7a x86_64

                      (Bayesian Analysis of Phylogeny)

              Distributed under the GNU General Public License

               Type "help" or "help <command>" for information
                     on the commands that are available.

                   Type "about" for authorship and general
                       information about the program.

MrBayes > Showbeagle

   Available resources reported by beagle library:
        Resource 0:
        Name: CPU
        Flags: PROCESSOR_CPU PRECISION_DOUBLE PRECISION_SINGLE COMPUTATION_SYNCH
             EIGEN_REAL EIGEN_COMPLEX SCALING_MANUAL SCALING_AUTO
             SCALING_ALWAYS SCALING_DYNAMIC SCALERS_RAW SCALERS_LOG
             VECTOR_NONE VECTOR_SSE THREADING_NONE THREADING_CPP

   BEAGLE version: 3.1.2

 </pre>
</details>

## What you expected to happen

The `Showbeagle` command in MrBayes should show a GPU resource.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install mrbayes`
2. `mb` followed by `Showbeagle` as show above.

**Comment by iMichka** [comment]
If you know how to modify the formula to enable the GPU feature, we would be willing to review a pull request for this (this is not really a bug on our side, just a missing feature flag somewhere).

II doubt we have the bandwidth to fix this issue right now, so we will need the help from the community here.

**Comment by jonchang** [comment]
I don't think we can do this homebrew-core because building it would require the CUDA framework, which we cannot support on our continuous integration infrastructure.

Your best bet is to install the beagle developer's release of beagle and build mrbayes from source.
