### ISSUE TITLE
openssl: files remain in etc/openssl after uninstall

### ISSUE THREAD

**Issue by scpeters** [Homebrew/homebrew-core#4752]
### Bug reports:

After a fresh install with the instructions from http://brew.sh, installing and then removing openssl shows that files are left behind in the `<prefix>/etc/openssl` folder:

~~~
$ brew install openssl && brew remove openssl
...
$ brew doctor
Your system is ready to brew.
$ find /usr/local/etc
/usr/local/etc
/usr/local/etc/openssl
/usr/local/etc/openssl/cert.pem
/usr/local/etc/openssl/certs
/usr/local/etc/openssl/misc
/usr/local/etc/openssl/misc/c_hash
/usr/local/etc/openssl/misc/c_info
/usr/local/etc/openssl/misc/c_issuer
/usr/local/etc/openssl/misc/c_name
/usr/local/etc/openssl/misc/CA.pl
/usr/local/etc/openssl/misc/CA.sh
/usr/local/etc/openssl/misc/tsget
/usr/local/etc/openssl/openssl.cnf
/usr/local/etc/openssl/private
~~~

If "leave no trace" is desired after uninstalling a formula, we could possibly add some expectations to the brew test-bot to check for this.

**Comment by chdiza** [comment]
That's on purpose, if I recall correctly.

**Comment by DomT4** [comment]
Yes. We don't purge `/usr/local/etc` or `/usr/local/var` unless the things in either of those directories is actually a symlink from the Cellar, but the desired behaviour is for configuration and log files/etc to be permanent.

**Comment by scpeters** [comment]
Great, that makes total sense. I was actually going to report that the python package doesn't delete the `/usr/local/lib/python2.7/site-packages` folder after `brew remove python`, but I reported this first since `openssl` is a dependency.

Is the `site-packages` folder retained according to the same logic?

**Comment by DomT4** [comment]
Yes. Partially a safety mechanism; other formulae may have been installed by brew into `/usr/local/lib/python2.7/site-packages` and removing that directory because `python` was removed is a solid way to invite unexpected & significant breakage.

That directory is used for global bindings regardless of whether those bindings are built against Homebrew's or Apple's Python, for example.

**Comment by scpeters** [comment]
Thanks for the explanation!
