### ISSUE TITLE
SHA256 mismatch when building `automake` from source

### ISSUE THREAD

**Issue by nva14** [Homebrew/homebrew-core#47557]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`brew gist-logs automake`:
`Error: No logs.`
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Building `automake` from source with `brew install --build-from-source automake`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://git.savannah.gnu.org/cgit/automake.git/patch/?id=a348d830659fffd2cfc42994524783b07e69b4b5
-#O#- #   #                                                                   
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 7a57ca2b91f7f3c0b168cf5ffbc8a1b2168f3886bcadcc15412281472dace3ce
  Actual: c048ce853eef073a5dfce34fcf9af786e8525e384e01dbbf4e6066623985d4c7
 Archive: /Users/nva/Library/Caches/Homebrew/downloads/d1a7da67f605d4ecad31b6a1084d23e41059c58dbc9929a139cb461f36540c3d--596e9e130f38ae068ac6150b2d62eafd544900f6..a348d830659fffd2cfc42994524783b07e69b4b5.patch
To retry an incomplete download, remove the file above.

  </pre>
</details>

## What you expected to happen

SHA256 match expected value

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew update` then `brew install --build-from-source automake`

brew config: 

<pre>
HOMEBREW_VERSION: 2.2.0-65-g2b34c10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2b34c1055fce2609de3aa6ea28fc251c9d875485
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cc307630acd25208a68941b148abaf03941b0a73
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS: 1
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.1-x86_64
CLT: 11.2.0.0.1.1571444319
Xcode: N/A
CLT headers: 11.2.0.0.1.1571444319`
</pre>
brew doctor:

`Your system is ready to brew.`

**Comment by SMillerDev** [comment]
Please run the commands in the template to give some more information on the failure.

**Comment by Bo98** [comment]
The patch in question seems a little prone to checksum changes whenever upstream updates their cgit server. Perhaps it is worth rehosting in Homebrew/formula-patches if we are going to use it.

**Comment by nva14** [comment]
> Please run the commands in the template to give some more information on the failure.

I updated OP with outputs from `brew gist-logs automake`, `brew config` and `brew doctor`. Everything seems fine.

**Comment by fxcoudert** [comment]
Thanks @nva14 for reporting this issue!
