### ISSUE TITLE
Package depency path not included in build environment

### ISSUE THREAD

**Issue by cbcoutinho** [Homebrew/homebrew-core#47572]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I'm unable to find the manpages associated with a package I installed via homebrew. The problem is due to the fact that the configure script cannot find the executables of `sphinx-doc`, one of the dependencies, due to the fact that that package doesn't append anything to the path.

Building from a fresh git clone shows that if you don't have `sphinx`, `notmuch` is built without manpages, and if you have `sphinx` then it adds them to the build.

How do you add to the path during build so that configure script can find the `sphinx` executables?

From the `sphinx-doc` package:

    ==> Caveats
    sphinx-doc is keg-only, which means it was not symlinked into /usr/local,
    because this formula is mainly used internally by other formulae.
    Users are advised to use `pip` to install sphinx-doc.

    If you need to have sphinx-doc first in your PATH run:
      echo 'export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"' >> ~/.zshrc

See how sphinx-doc is a dependency to the build:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/notmuch.rb

## What you were trying to do (and why)

I want to have the manpages installed for the `notmuch` package

## What happened (include command output)

The `notmuch` package is bottled without the manpages because the build cannot find the `sphinx-doc` executables/scripts.

## What you expected to happen

Sphinx dependency is correctly added to build environment path.

**Comment by alebcay** [comment]
I'm not able to reproduce this locally. `brew install notmuch`, which installs from bottle, followed by `man notmuch` shows the `notmuch` manpages.

**Comment by cbcoutinho** [comment]
I should have been more specific - the current man pages available are only `notmuch(3)` if I remember correctly (not at my computer) . There should be others such as `notmuch-address(1)` and `notmuch-count(1)`, which are available when built from source and `sphinx-dox` is available

**Comment by fxcoudert** [comment]
Using `depends_on "sphinx-doc" => :build` already puts the `sphinx-doc` binaries in the `PATH`. The fact that it is keg-only only means that it is not symlinked into `/usr/local`, but `brew` knows to put its build dependencies in the `PATH`.

**Comment by cbcoutinho** [comment]
@fxcoudert 

Could it be a python path issue? If it's able to find sphinx-build, then the other conditional is probably failing.

The offending lines in `configure` are:

```shell
    if command -v sphinx-build > /dev/null && ${python} -m sphinx.writers.manpage > /dev/null 2>&1 ; then
	printf "Yes.\n"
	have_sphinx=1
    else
```

https://github.com/notmuch/notmuch/blob/release/configure#L716-L719

**Comment by fxcoudert** [comment]
```
± python3 -m sphinx.writers.manpage   
/usr/local/opt/python/bin/python3.7: Error while finding module specification for 'sphinx.writers.manpage' (ModuleNotFoundError: No module named 'sphinx')
```

I think the proper fix is therefore:

```
ENV.append_path "PYTHONPATH", Formula["sphinx-doc"].opt_libexec/"lib/python3.7/site-packages"
```

**Comment by cbcoutinho** [comment]
I tried that fix and the `PYTHONPATH` is empty when I attempt to build locally. Does appending to an empty variable work in this case?

**Comment by cbcoutinho** [comment]
@fxcoudert 

I tried to append the path to PYTHONPATH, but it doesn't seem to have an effect - when I try to install the package in debug mode PYTHONPATH is blank.

**Comment by cbcoutinho** [comment]
This is not stale - I'm still waiting for help on this issue

**Comment by fxcoudert** [comment]
Given that the formula works, with only some doc missing, we're not going to keep the issue open if it's not actively been worked on. We simply don't have enough maintainer time to debug all such minor issues. We'll gladly accept a pull request if you or someone else finds a fix.

To get help from the community, you can also try our discussion board: https://discourse.brew.sh
