### ISSUE TITLE
LINKFORSHARED: Link error due to "-u _PyMac_Error"

### ISSUE THREAD

**Issue by ampli** [Homebrew/homebrew-core#4758]
The definition of `LINKFORSHARED` as set by [Formula/python3.rb#L221]
(https://github.com/Homebrew/homebrew-core/blob/0a7d0a9c43bc8e5e6bb58c0b2d8d373ddc79ff9e/Formula/python3.rb#L221), contains `-u _PyMac_Error` . However, this symbol is not defined anymore in the Python library.

As a result, linking to the Python library when embedding fails with the error:
```
Undefined symbols for architecture x86_64:
  "_PyMac_Error", referenced from:
     -u command line option
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When `-u _PyMac_Error` is removed, the linking succeeds and the language bindings work fine.

**Comment by tdsmith** [comment]
Thanks for reporting!
