### ISSUE TITLE
swftools (swfdump command) segfaults on catalina

### ISSUE THREAD

**Issue by frescoraja** [Homebrew/homebrew-core#47590]
## swftools installed on mac OS X Catalina

I have found that if I install swftools from a computer with catalina, i cannot run some swftools commands that work from other systems that had swftools installed before upgrading to Catalina

I have confirmed that copying the `/usr/local/Cellar/swftools` from a computer with Mojave or High Sierra fixes the issue on my mac with Catalina 

thanks for looking into this

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 

Just says `No Logs.`

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
  <summary>`brew config` command ouput</summary>
  <pre>
HOMEBREW_VERSION: 2.2.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d7de295dfbc5e581106e2b1f674496b5e25a773
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5b9bd0e888f045285a0c2b538f8d39d3e2610df5
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_SBIN: /usr/local/sbin
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.1
macOS: 10.15.1-x86_64
CLT: 1100.0.33.8
Xcode: 11.2.1
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>

<details>
  <summary>`brew doctor` command output</summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libiconv.2.dylib
  /usr/local/lib/libintl.8.dylib
  /usr/local/lib/libutil.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
  /usr/local/include/python3.7m/greenlet/greenlet.h
  </pre>
</details>

## What you were trying to do (and why)

use `swfdump --action` or `swfdump -D` command on mac with OS Catalina freshly installed

## What happened (include command output)

segmentation fault error on all SWF files i've tried

(output truncated, not very important)

<details>
  <summary>Command output</summary>
  <pre>
global flags: 0800
                 flags 00000800 [mouse release], 41 bytes actioncode
[1]    75983 segmentation fault  swfdump -D ./lib/test_files/980x150_barillaNY-x6xoWO9.swf
  </pre>
</details>

## What you expected to happen

dump of swf file

## Step-by-step reproduction instructions (by running `brew install` commands)

from a computer with Mac OS X 10.15.1 Catalina installed:
1) `brew install swftools`
2) `swfdump -D <path to SWF file>` or `swfdump --action <path to SWF file>`

I have also tried building `swftools` from [source](http://www.swftools.org/swftools-2013-04-09-1007.tar.gz) from a pc with mac OS X Catalina and I get the same results. here's a crash report:

<details>
<summary>swfdump crash</summary>
<pre>
Process:               swfdump [23578]
Path:                  /usr/local/bin/swfdump
Identifier:            swfdump
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [64504]
Responsible:           iTerm2 [28350]
User ID:               501

Date/Time:             2019-12-07 00:48:49.475 -0500
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Bridge OS Version:     4.1 (17P1081)
Anonymous UUID:        225E30CE-3FEA-5684-2023-86C571C1FB36

Time Awake Since Boot: 14000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [23578]

Application Specific Information:
dyld2 mode

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libdyld.dylib                 	0x00007fff70779386 stack_not_16_byte_aligned_error + 0
1   ???                           	0x0000000000000800 0 + 2048

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000000000021a8  rbx: 0x00007fdc70d03b40  rcx: 0xf608c7584a7800f4  rdx: 0x0000000000000043
  rdi: 0x00007fdc70d03b40  rsi: 0x00007ffeee084660  rbp: 0x0000000000000800  rsp: 0x00007ffeee084188
   r8: 0x00000000c70d03cb   r9: 0x00000000c70d03cd  r10: 0x00000000ffffe7ff  r11: 0x0000000101bea220
  r12: 0x00007ffeee084660  r13: 0x00007fdc70d00560  r14: 0x0000000000000001  r15: 0x00000000fffff7ff
  rip: 0x00007fff70779386  rfl: 0x0000000000010202  cr2: 0x0000000101bce0e0
  
Logical CPU:     2
Error Code:      0x00000000
Trap Number:     13

Binary Images:
       0x101b79000 -        0x101be8fff +swfdump (0) <85E589BA-A22D-3A86-A548-1E5DFBBF64B9> /usr/local/bin/swfdump
       0x101c5b000 -        0x101c91ffb +libmp3lame.0.dylib (0) <1A3FD3F1-449E-30E8-BB96-D841D578F9D3> /usr/local/opt/lame/lib/libmp3lame.0.dylib
       0x101ccc000 -        0x101cd0fff +libgif.dylib (0) <7C4F033C-607E-385A-8A49-E23517F8AF24> /usr/local/opt/giflib/lib/libgif.dylib
       0x101cda000 -        0x101d07ff3 +libjpeg.9.dylib (0) <097A43C2-81FA-3EDB-BB6E-94062657531D> /usr/local/opt/jpeg/lib/libjpeg.9.dylib
       0x101d0e000 -        0x101d89fff +libfreetype.6.dylib (0) <02EE484C-8D5B-36C3-988B-00DD0C7369FE> /usr/local/opt/freetype/lib/libfreetype.6.dylib
       0x101da3000 -        0x101dc6ff7 +libpng16.16.dylib (0) <B7CE95CF-E67E-39EB-8DF5-B89849A02BDA> /usr/local/opt/libpng/lib/libpng16.16.dylib
       0x110dbc000 -        0x110e4cb5f  dyld (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770> /usr/lib/dyld
    0x7fff6d5d3000 -     0x7fff6d5d4ff3  libSystem.B.dylib (1281) <1DD1BCD2-2C85-3B81-8CAF-224FB042F441> /usr/lib/libSystem.B.dylib
    0x7fff6d8a4000 -     0x7fff6d8b0fff  libbz2.1.0.dylib (44) <F3D26C17-BC6E-3A83-A3BB-137343C87303> /usr/lib/libbz2.1.0.dylib
    0x7fff6d8b1000 -     0x7fff6d904fff  libc++.1.dylib (800.7) <1D42387D-206A-3F06-9B5F-705B83EAC295> /usr/lib/libc++.1.dylib
    0x7fff6d905000 -     0x7fff6d919fff  libc++abi.dylib (800.7) <D89ABFBF-3754-35AB-BAEE-FBF14857F79B> /usr/lib/libc++abi.dylib
    0x7fff6f413000 -     0x7fff6f444ff6  libobjc.A.dylib (781) <D866A31E-5CB1-3327-8D22-C4F83C9225D0> /usr/lib/libobjc.A.dylib
    0x7fff6faeb000 -     0x7fff6fafdfff  libz.1.dylib (76) <3EC7A143-AF2D-35EE-9C08-542B2907E3D2> /usr/lib/libz.1.dylib
    0x7fff70563000 -     0x7fff70568ff7  libcache.dylib (83) <74F6459D-3606-3ADB-9808-F6B0FE70062D> /usr/lib/system/libcache.dylib
    0x7fff70569000 -     0x7fff70574ff7  libcommonCrypto.dylib (60165) <1333752F-5117-3E86-803A-06E166D80C8C> /usr/lib/system/libcommonCrypto.dylib
    0x7fff70575000 -     0x7fff7057cfff  libcompiler_rt.dylib (101.2) <0437EBEF-8191-3912-A365-D6BB75C7A810> /usr/lib/system/libcompiler_rt.dylib
    0x7fff7057d000 -     0x7fff70586fff  libcopyfile.dylib (166.40.1) <7FAF372E-BAD5-30E6-A8F2-A3D06B91DC80> /usr/lib/system/libcopyfile.dylib
    0x7fff70587000 -     0x7fff7061efef  libcorecrypto.dylib (866.40.8) <AE25C9EE-5D63-3E49-B3AA-D482D35C085A> /usr/lib/system/libcorecrypto.dylib
    0x7fff70735000 -     0x7fff70776ff0  libdispatch.dylib (1173.40.5) <1FF421B6-4BF0-3B5F-8F56-5ED3B3EFE06F> /usr/lib/system/libdispatch.dylib
    0x7fff70777000 -     0x7fff707acfff  libdyld.dylib (733.6) <2FA4B359-624B-337C-9207-CDCF841C2E52> /usr/lib/system/libdyld.dylib
    0x7fff707ad000 -     0x7fff707adffb  libkeymgr.dylib (30) <7EEF9246-30B4-34DD-8AD6-79679D1A7784> /usr/lib/system/libkeymgr.dylib
    0x7fff707bb000 -     0x7fff707bbff7  liblaunch.dylib (1738.40.10) <CC02D5B3-A95D-3B16-8EE5-D62521CFE899> /usr/lib/system/liblaunch.dylib
    0x7fff707bc000 -     0x7fff707c1ff7  libmacho.dylib (949.0.1) <6C3E49B2-594D-3B9D-82DB-C4ABEB9788AB> /usr/lib/system/libmacho.dylib
    0x7fff707c2000 -     0x7fff707c4ff3  libquarantine.dylib (110.40.3) <A1BCAA32-A194-3DBE-9930-8F49A4AEF284> /usr/lib/system/libquarantine.dylib
    0x7fff707c5000 -     0x7fff707c6ff7  libremovefile.dylib (48) <DD7AE862-F179-3C07-A4FC-5775DDD4D3E6> /usr/lib/system/libremovefile.dylib
    0x7fff707c7000 -     0x7fff707defff  libsystem_asl.dylib (377.40.1) <ECE44856-D279-3B5D-A0AA-8BE421D200C4> /usr/lib/system/libsystem_asl.dylib
    0x7fff707df000 -     0x7fff707dffff  libsystem_blocks.dylib (74) <DC521115-905A-3A0D-9337-C55FACCEA85F> /usr/lib/system/libsystem_blocks.dylib
    0x7fff707e0000 -     0x7fff70867ff7  libsystem_c.dylib (1353.41.1) <5AD50779-955E-3F56-BCB9-1E14833B3455> /usr/lib/system/libsystem_c.dylib
    0x7fff70868000 -     0x7fff7086bfff  libsystem_configuration.dylib (1061.40.2) <7A2329E0-3C84-3DB7-BC32-E7796C50D621> /usr/lib/system/libsystem_configuration.dylib
    0x7fff7086c000 -     0x7fff7086fff7  libsystem_coreservices.dylib (114) <DF341577-A307-3722-BB24-D4AACEAB19B3> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff70870000 -     0x7fff70877fff  libsystem_darwin.dylib (1353.41.1) <E862B5B1-A367-39CA-8319-B2F9DFADF606> /usr/lib/system/libsystem_darwin.dylib
    0x7fff70878000 -     0x7fff7087fffb  libsystem_dnssd.dylib (1096.40.7) <2A9C6F3E-427B-332E-BDD3-D4651306F3DE> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff70880000 -     0x7fff70881ffb  libsystem_featureflags.dylib (17) <B94C0052-B75A-3169-80AA-5F480588AF6E> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff70882000 -     0x7fff708cfff7  libsystem_info.dylib (538) <18CC56C5-5325-3375-BF99-FAE7F4F19DDD> /usr/lib/system/libsystem_info.dylib
    0x7fff708d0000 -     0x7fff708fcff7  libsystem_kernel.dylib (6153.41.3) <18918E9C-45BC-3D5A-A6B6-3DBC60EEE2E1> /usr/lib/system/libsystem_kernel.dylib
    0x7fff708fd000 -     0x7fff70944ff7  libsystem_m.dylib (3178) <636A1A1C-7AFC-3E82-B86B-0173912A3437> /usr/lib/system/libsystem_m.dylib
    0x7fff70945000 -     0x7fff7096cff7  libsystem_malloc.dylib (283.40.1) <F82A587B-44A2-3699-A218-9D3ECEE23D5A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff7096d000 -     0x7fff7097aff3  libsystem_networkextension.dylib (1095.40.22) <7F206A43-A941-3BAB-AE3A-16169F2FE6AB> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff7097b000 -     0x7fff70984fff  libsystem_notify.dylib (241) <C95CC58E-35E7-3828-AA2A-6EED73C12DE5> /usr/lib/system/libsystem_notify.dylib
    0x7fff70985000 -     0x7fff7098efe7  libsystem_platform.dylib (220) <0CCDD81F-0891-3400-8A97-6CAC3BBBE2F9> /usr/lib/system/libsystem_platform.dylib
    0x7fff7098f000 -     0x7fff70999ff7  libsystem_pthread.dylib (416.40.3) <53C65598-9E9E-36FF-BDC2-74F228E58C5C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff7099a000 -     0x7fff7099effb  libsystem_sandbox.dylib (1217.41.1) <2183D15E-2CFD-3160-80CE-A948F0529005> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7099f000 -     0x7fff709a1fff  libsystem_secinit.dylib (62.40.2) <D2782294-ACDC-30FF-A794-B4C1B324526B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff709a2000 -     0x7fff709a9ffb  libsystem_symptoms.dylib (1238.40.4) <A44E4405-E22E-32E9-83DE-8C7A82401DA0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff709aa000 -     0x7fff709c0ff2  libsystem_trace.dylib (1147.40.13) <376CC435-E656-37D9-A5FF-C49B6E4525E2> /usr/lib/system/libsystem_trace.dylib
    0x7fff709c2000 -     0x7fff709c7ffb  libunwind.dylib (35.4) <44448F1F-08E5-3425-ADBA-C38A9E8F90C7> /usr/lib/system/libunwind.dylib
    0x7fff709c8000 -     0x7fff709fcff6  libxpc.dylib (1738.40.10) <99CC9436-D653-3762-ADBB-9054EBD1BA2B> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 9524
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=359.5M resident=0K(0%) swapped_out_or_unallocated=359.5M(100%)
Writable regions: Total=154.6M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=154.6M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            34.1M       12 
MALLOC guard page                   24K        4 
MALLOC_MEDIUM (reserved)         112.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        1 
Stack                             8192K        2 
__DATA                            1063K       49 
__DATA_CONST                        28K        3 
__LINKEDIT                       353.3M        8 
__OBJC_RO                         32.0M        1 
__OBJC_RW                         1780K        2 
__TEXT                            6392K       47 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            604.5M      133 
TOTAL, minus reserved VM space   492.5M      133 
</pre>
</details>

**Comment by fxcoudert** [comment]
This is due to a wrong-code bug in the clang compiler shipped with Xcode 11, prior to Xcode 11.3. I've built new binary bottles for it, with Xcode 11.3, so it should now be fixed. You can `brew reinstall swftools`

**Comment by frescoraja** [comment]
thanks, it is working after `brew reinstall swftools`
