### ISSUE TITLE
？

### ISSUE THREAD

**Issue by daisenrong** [Homebrew/homebrew-core#47610]
~ brew update
.git/rebase-apply/patch:4438: trailing whitespace.

.git/rebase-apply/patch:4440: space before tab in indent.
 	mkdir -p ${OUI_PATH}
.git/rebase-apply/patch:14738: trailing whitespace.

.git/rebase-apply/patch:20037: space before tab in indent.
 					if (c->size() != size())
.git/rebase-apply/patch:20038: space before tab in indent.
 						return false;
warning: squelched 166 whitespace errors
warning: 171 lines add whitespace errors.
error: Failed to merge in the changes.
hint: Use 'git am --show-current-patch' to see the failed patch
Error: 767: unexpected token at '{
<<<<<<< HEAD
  "ansible19": "ansible@19",
  "ansible20": "ansible@20",
=======
>>>>>>> nethack: update 3.6.3 bottle.

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:558:in `formula_renames'
/usr/local/Homebrew/Library/Homebrew/tap.rb:696:in `formula_renames'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:239:in `block in report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:237:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:237:in `report'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:411:in `add'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:100:in `block in update_report'
/usr/local/Homebrew/Library/Homebrew/tap.rb:587:in `block (2 levels) in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:586:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:586:in `block in each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:585:in `each'
/usr/local/Homebrew/Library/Homebrew/tap.rb:585:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:89:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
➜  ~

**Comment by SMillerDev** [comment]
Missing issue template and title

**Comment by daisenrong** [comment]
sorry
