### ISSUE TITLE
`watch` does not respect 256 colors

### ISSUE THREAD

**Issue by tomasdev** [Homebrew/homebrew-core#47649]
Compare the following:
`$ watch -n 5 -t -c ./ticker.sh AAPL GPRO GOOG BTC-USD`
<img width="441" alt="Screenshot 2019-12-09 at 14 00 07" src="https://user-images.githubusercontent.com/364033/70437858-d8026280-1a8c-11ea-8dbe-b17f578df79f.png">
`$ while true; do clear; ./ticker.sh AAPL GPRO GOOG BTC-USD; sleep 5; done`
<img width="438" alt="Screenshot 2019-12-09 at 14 04 22" src="https://user-images.githubusercontent.com/364033/70437860-d89af900-1a8c-11ea-8c4d-dc6865404ef5.png">

Why would `watch -c` only parse 8 colors instead of 256? On Linux, watch works as expected.

**Comment by SMillerDev** [comment]
Please fill out the issue template

**Comment by equal-l2** [comment]
> On Linux, watch works as expected.

Which distro?
