### ISSUE TITLE
Upgrade to latest Git 2.24.1 etc with security fixes

### ISSUE THREAD

**Issue by jmurty** [Homebrew/homebrew-core#47708]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update to latest 2.24.1 release of Git that has security fixes per https://lore.kernel.org/git/xmqqr21cqcn9.fsf@gitster-ct.c.googlers.com/T/#u via https://github.blog/2019-12-10-multiple-git-vulnerabilities-in-2-24-and-older/

## What happened (include command output)

The latest version currently available is `2.24.0_2` which does not include the security fixes (latest update to https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb was 19 days ago)

<details>
  <summary>Command output</summary>
  <pre>
$ brew update && brew info git
Already up-to-date.
git: stable 2.24.0 (bottled), HEAD
Distributed revision control system
https://git-scm.com
/usr/local/Cellar/git/2.24.0_2 (1,547 files, 45.1MB) *
  Poured from bottle on 2019-12-11 at 09:43:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb
  </pre>
</details>

## What you expected to happen

Get git version 2.24.1 or an equivalent version that includes security fixes.

## Step-by-step reproduction instructions (by running `brew install` commands)

- `brew update`, then
- `brew install git` (initially) or `brew upgrade git`

**Comment by jonchang** [comment]
Please search for open pull requests before opening issues. https://github.com/Homebrew/homebrew-core/issues/47708

**Comment by jmurty** [comment]
Sorry, will do in future. Here's the relevant PR https://github.com/Homebrew/homebrew-core/pull/47696

**Comment by SMillerDev** [comment]
In addition to that, don't make issues for updates/feature requests at all. https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request will tell you how to update a formula. There is no reason why you couldn't be the one to update something for homebrew users.
