### ISSUE TITLE
'shntool' package missing 'shorten' dependency

### ISSUE THREAD

**Issue by jishaq** [Homebrew/homebrew-core#47714]
The shntool package requires the presence of the shorten codec in order to work.  "brew install shntool" does not install this dependency, however this dependency is readily available and quite easy to build from source.  

As a result, any shntool operation to compress or decompress will fail.  Here is the example using the (attached) 'test.shn' file, which is a compressed wav file (please unzip before using for testing):

<pre>
Jeffs-MacBook-Pro:~ jishaq$ shntool conv ~/Desktop/test.shn
shntool [conv]: warning: failed to read data from input file using format: [shn]
shntool [conv]:          + you may not have permission to read file: [/Users/jishaq/Desktop/test.shn]
shntool [conv]:          + arguments may be incorrect for decoder: [shorten]
shntool [conv]:          + verify that the decoder is installed and in your PATH
shntool [conv]:          + this file may be unsupported, truncated or corrupt
</pre>
 
To fix this issue, brew needs to install the shorten codec as a dependency.  In order to install the shorten codec:

1) Download the shorten-3.6.1 tarball from:  https://web.archive.org/web/20170607112233/http://etree.org/shnutils/shorten/dist/src/shorten-3.6.1.tar.gz

2) Decompress the tarball (tar -xcf shorten-3.6.1.tar.gz)

3) cd into the shorten-3.6.1 directory

4) ./configure

5) make

6) make check

7) sudo make install

Now, when you run the same comman, shntool is successful:

<pre>
Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ shntool conv ~/Desktop/test.shn
Converting [/Users/jishaq/Desktop/test.shn] (4:30.31) --> [/Users/jishaq/Desktop/test.wav] : 100% OK
Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ 
</pre>

- [ X] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use brew to install the shntool package, which is used to losslessly compress and decompress audio files, to decompress test.shn.

## What happened (include command output)

After installing the shntool package, issuing the command 'shntool conv test.shn' results in an error "verify that the decoder is installed and in your PATH".  After installing the 'shorten' decoder, the error goes away and shntool functions correctly.

<details>
  <summary>Command output</summary>
  <pre>
Jeffs-MacBook-Pro:~ jishaq$ brew install shntool
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
detekt                     powerline-go               skymaker
==> Updated Formulae
bumpversion         fx                  now-cli             tor
bup                 geogram             nsd                 traefik
certbot             glib-networking     ocaml-num           traefik@1
diffr               glooctl             pdnsrec             vim
dnscrypt-proxy      ios-deploy          phpstan             vips
erlang              ncmpc               scrcpy
faust               neomutt             serverless
frotz               node                terragrunt

==> Downloading https://homebrew.bintray.com/bottles/shntool-3.0.10.mojave.bottl
######################################################################## 100.0%
==> Pouring shntool-3.0.10.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/shntool/3.0.10: 23 files, 347.2KB

Jeffs-MacBook-Pro:~ jishaq$ shntool conv ~/Desktop/test.shn
shntool [conv]: warning: failed to read data from input file using format: [shn]
shntool [conv]:          + you may not have permission to read file: [/Users/jishaq/Desktop/test.shn]
shntool [conv]:          + arguments may be incorrect for decoder: [shorten]
shntool [conv]:          + verify that the decoder is installed and in your PATH
shntool [conv]:          + this file may be unsupported, truncated or corrupt
  </pre>
</details>

## What you expected to happen

No error message.  Instead:

Converting [/Users/jishaq/Desktop/test.shn] (4:30.31) --> [/Users/jishaq/Desktop/test.wav] : 100% OK
Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$  ### shntool successfully decompresses test.shn into test.wav

## Step-by-step reproduction instructions (by running `brew install` commands)

Jeffs-MacBook-Pro:~ jishaq$ brew install shntool
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
detekt                     powerline-go               skymaker
==> Updated Formulae
bumpversion         fx                  now-cli             tor
bup                 geogram             nsd                 traefik
certbot             glib-networking     ocaml-num           traefik@1
diffr               glooctl             pdnsrec             vim
dnscrypt-proxy      ios-deploy          phpstan             vips
erlang              ncmpc               scrcpy
faust               neomutt             serverless
frotz               node                terragrunt

==> Downloading https://homebrew.bintray.com/bottles/shntool-3.0.10.mojave.bottl
######################################################################## 100.0%
==> Pouring shntool-3.0.10.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/shntool/3.0.10: 23 files, 347.2KB

Jeffs-MacBook-Pro:~ jishaq$ shntool conv ~/Desktop/test.shn
shntool [conv]: warning: failed to read data from input file using format: [shn]
shntool [conv]:          + you may not have permission to read file: [/Users/jishaq/Desktop/test.shn]
shntool [conv]:          + arguments may be incorrect for decoder: [shorten]
shntool [conv]:          + verify that the decoder is installed and in your PATH
shntool [conv]:          + this file may be unsupported, truncated or corrupt

Jeffs-MacBook-Pro:~ jishaq$ brew update
Already up-to-date.

Jeffs-MacBook-Pro:~ jishaq$ brew doctor
Your system is ready to brew.

Jeffs-MacBook-Pro:~ jishaq$ brew gist-logs shntool
Error: No logs.

Jeffs-MacBook-Pro:~ jishaq$ brew config
HOMEBREW_VERSION: 2.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe99bd9823fadea1cf918b1ed8366de7f40d336
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c331c32fa7fbad93330d467de149ac36108124db
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.2.1
CLT headers: 10.3.0.0.1.1562985497

###
###
###
###
###
###
###
###

Jeffs-MacBook-Pro:~ jishaq$ cd ~/Desktop/
Jeffs-MacBook-Pro:Desktop jishaq$ tar -xvf shorten-3.6.1.tar.gz 
x shorten-3.6.1/
x shorten-3.6.1/include/
x shorten-3.6.1/include/config.h.in
x shorten-3.6.1/include/binary.h
x shorten-3.6.1/include/shorten.h
x shorten-3.6.1/include/config.h
x shorten-3.6.1/include/stamp-h1
x shorten-3.6.1/README
x shorten-3.6.1/configure.ac
x shorten-3.6.1/aclocal.m4
x shorten-3.6.1/Makefile.am
x shorten-3.6.1/Makefile.in
x shorten-3.6.1/configure
x shorten-3.6.1/AUTHORS
x shorten-3.6.1/COPYING
x shorten-3.6.1/ChangeLog
x shorten-3.6.1/INSTALL
x shorten-3.6.1/NEWS
x shorten-3.6.1/config.guess
x shorten-3.6.1/config.sub
x shorten-3.6.1/depcomp
x shorten-3.6.1/install-sh
x shorten-3.6.1/missing
x shorten-3.6.1/doc/
x shorten-3.6.1/doc/tr156.ps
x shorten-3.6.1/doc/LICENSE
x shorten-3.6.1/doc/TODO
x shorten-3.6.1/doc/tr156.tex
x shorten-3.6.1/man/
x shorten-3.6.1/man/Makefile.am
x shorten-3.6.1/man/Makefile.in
x shorten-3.6.1/man/shorten.1
x shorten-3.6.1/utils/
x shorten-3.6.1/utils/Makefile.am
x shorten-3.6.1/utils/Makefile.in
x shorten-3.6.1/utils/Sulawalaw.c
x shorten-3.6.1/utils/array.c
x shorten-3.6.1/utils/exit.c
x shorten-3.6.1/utils/mkbshift.c
x shorten-3.6.1/src/
x shorten-3.6.1/src/Makefile.am
x shorten-3.6.1/src/Makefile.in
x shorten-3.6.1/src/aiff.c
x shorten-3.6.1/src/dupfinfo.c
x shorten-3.6.1/src/fixio.c
x shorten-3.6.1/src/hsgetopt.c
x shorten-3.6.1/src/license.c
x shorten-3.6.1/src/lpc.c
x shorten-3.6.1/src/main.c
x shorten-3.6.1/src/poly.c
x shorten-3.6.1/src/riffwave.c
x shorten-3.6.1/src/shorten.c
x shorten-3.6.1/src/vario.c
x shorten-3.6.1/tests/
x shorten-3.6.1/tests/Makefile.am
x shorten-3.6.1/tests/Makefile.in
x shorten-3.6.1/tests/test-errors.sh
x shorten-3.6.1/tests/test-general.sh
x shorten-3.6.1/tests/test-seek.sh
x shorten-3.6.1/tests/mono/
x shorten-3.6.1/tests/mono/seekable.shn
x shorten-3.6.1/tests/mono/test.aiff
x shorten-3.6.1/tests/mono/test.aiff.shn
x shorten-3.6.1/tests/mono/test.shn
x shorten-3.6.1/tests/mono/test.skt
x shorten-3.6.1/tests/mono/test.wav
x shorten-3.6.1/tests/stereo/
x shorten-3.6.1/tests/stereo/test.aiff.shn
x shorten-3.6.1/tests/stereo/seekable.shn
x shorten-3.6.1/tests/stereo/test.aiff
x shorten-3.6.1/tests/stereo/test.shn
x shorten-3.6.1/tests/stereo/test.skt
x shorten-3.6.1/tests/stereo/test.wav

Jeffs-MacBook-Pro:Desktop jishaq$ cd shorten-3.6.1
Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ ./configure
checking build system type... i386-apple-darwin18.7.0
checking host system type... i386-apple-darwin18.7.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for a BSD-compatible install... /usr/bin/install -c
checking for gawk... (cached) awk
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for main in -lm... yes
configure: checking for headers
checking for ANSI C header files... (cached) yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking for inttypes.h... (cached) yes
configure: checking for win32 environment
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
configure: checking for data types
checking for unsigned long... yes
checking size of unsigned long... 8
configure: checking for library functions
checking for strerror... yes
checking for truncate... yes
configure: creating ./config.status
config.status: creating man/Makefile
config.status: creating utils/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating Makefile
config.status: creating include/config.h
config.status: executing depfiles commands
configure: ready to compile.

shorten is now configured with the following options:

version:  3.6.1
install:  /usr/local/bin

Type 'make' to build shorten.  Afterwards,
type 'make check' to run some verification tests.

Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ make
Making all in man
make[1]: Nothing to be done for `all'.
Making all in utils
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT Sulawalaw.o -MD -MP -MF .deps/Sulawalaw.Tpo -c -o Sulawalaw.o Sulawalaw.c
mv -f .deps/Sulawalaw.Tpo .deps/Sulawalaw.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT array.o -MD -MP -MF .deps/array.Tpo -c -o array.o array.c
mv -f .deps/array.Tpo .deps/array.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT exit.o -MD -MP -MF .deps/exit.Tpo -c -o exit.o exit.c
mv -f .deps/exit.Tpo .deps/exit.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT mkbshift.o -MD -MP -MF .deps/mkbshift.Tpo -c -o mkbshift.o mkbshift.c

###
###
###
###
###

1668 warnings generated.
mv -f .deps/fixio.Tpo .deps/fixio.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT hsgetopt.o -MD -MP -MF .deps/hsgetopt.Tpo -c -o hsgetopt.o hsgetopt.c
mv -f .deps/hsgetopt.Tpo .deps/hsgetopt.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT license.o -MD -MP -MF .deps/license.Tpo -c -o license.o license.c
mv -f .deps/license.Tpo .deps/license.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT lpc.o -MD -MP -MF .deps/lpc.Tpo -c -o lpc.o lpc.c
mv -f .deps/lpc.Tpo .deps/lpc.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
mv -f .deps/main.Tpo .deps/main.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT poly.o -MD -MP -MF .deps/poly.Tpo -c -o poly.o poly.c
mv -f .deps/poly.Tpo .deps/poly.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT riffwave.o -MD -MP -MF .deps/riffwave.Tpo -c -o riffwave.o riffwave.c
mv -f .deps/riffwave.Tpo .deps/riffwave.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT shorten.o -MD -MP -MF .deps/shorten.Tpo -c -o shorten.o shorten.c
mv -f .deps/shorten.Tpo .deps/shorten.Po
gcc -DHAVE_CONFIG_H -I. -I../include     -g -O2 -MT vario.o -MD -MP -MF .deps/vario.Tpo -c -o vario.o vario.c
mv -f .deps/vario.Tpo .deps/vario.Po
gcc  -g -O2   -o shorten aiff.o dupfinfo.o fixio.o hsgetopt.o license.o lpc.o main.o poly.o riffwave.o shorten.o vario.o ../utils/Sulawalaw.o ../utils/array.o ../utils/exit.o -lm 
Making all in tests
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.

Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ make check
Making check in man
make[1]: Nothing to be done for `check'.
Making check in utils
make[1]: Nothing to be done for `check'.
Making check in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-am
make[2]: Nothing to be done for `check-am'.
Making check in tests
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS

=========================  shorten error tests  ==========================

+ Running error tests against mono benchmark files...

shorten: cannot use -e, -k or -i with data on standard input
shorten: for more information use: shorten -h
shorten: cannot use -e, -k or -i with data on standard input
shorten: for more information use: shorten -h
shorten: cannot use -e, -k or -i with data on standard input
shorten: for more information use: shorten -h
shorten: will not input data from a tty
shorten: for more information use: shorten -h
shorten: will not input data from a tty
shorten: for more information use: shorten -h
shorten: will not input data from a tty
shorten: for more information use: shorten -h
shorten: will not output data to a tty
shorten: for more information use: shorten -h
shorten: will not output data to a tty
shorten: for more information use: shorten -h
shorten: missing seek table filename for -S
shorten: for more information use: shorten -h
shorten: number of bytes to copy must be positive
shorten: for more information use: shorten -h
shorten: block size must be greater than zero
shorten: for more information use: shorten -h
shorten: number of channels must be greater than zero
shorten: for more information use: shorten -h
shorten: number of bytes to discard must be positive
shorten: for more information use: shorten -h
shorten: number of blocks for mean estimation must be positive
shorten: for more information use: shorten -h
shorten: Useful signal to noise ratios are positive
shorten: for more information use: shorten -h
shorten: linear prediction order must be in the range 0 ... 64
shorten: for more information use: shorten -h
shorten: linear prediction order must be in the range 0 ... 64
shorten: for more information use: shorten -h
shorten: quantisation level must be positive
shorten: for more information use: shorten -h
shorten: unknown file type: bad
shorten: for more information use: shorten -h
shorten: currently supported versions are in the range 1 ... 3
shorten: for more information use: shorten -h
shorten: currently supported versions are in the range 1 ... 3
shorten: for more information use: shorten -h
shorten: -k, -s and -S can only be used on shorten files
shorten: for more information use: shorten -h
shorten: -k, -s and -S can only be used on shorten files
shorten: for more information use: shorten -h
shorten: -k, -s and -S can only be used on shorten files
shorten: for more information use: shorten -h
shorten: cannot use -s with -S
shorten: for more information use: shorten -h
shorten: cannot use -e with -i
shorten: for more information use: shorten -h
shorten: cannot use -e with -k
shorten: for more information use: shorten -h
shorten: cannot use -i with -k
shorten: for more information use: shorten -h
shorten: cannot use -e with -x
shorten: for more information use: shorten -h
shorten: cannot use -i with -x
shorten: for more information use: shorten -h
shorten: cannot use -x with -k
shorten: for more information use: shorten -h
shorten: cannot use -x with -s
shorten: for more information use: shorten -h
shorten: cannot use -x with -S
shorten: for more information use: shorten -h
shorten: cannot use -k with -s
shorten: for more information use: shorten -h
shorten: cannot use -k with -S
shorten: for more information use: shorten -h
shorten: the predictor order must be less than the block size
shorten: for more information use: shorten -h
shorten: the -u flag is only applicable to ulaw coding
shorten: for more information use: shorten -h
shorten: too many filenames
shorten: for more information use: shorten -h
shorten: EOF on input when discarding header
shorten: for more information use: shorten -h
shorten: EOF on input when discarding header
shorten: for more information use: shorten -h
shorten: file 'seekable.shn' already contains seek information
shorten: for more information use: shorten -h
shorten: file 'test.shn' does not contain seek information
shorten: for more information use: shorten -h
shorten: could not open file 'missing.wav' for input
shorten: for more information use: shorten -h
shorten: could not open file 'missing.shn' for input
shorten: for more information use: shorten -h
shorten: input file is not a valid RIFF WAVE file
shorten: for more information use: shorten -h

+ Running error tests against stereo benchmark files...

shorten: cannot use -e, -k or -i with data on standard input
shorten: for more information use: shorten -h
shorten: cannot use -e, -k or -i with data on standard input
shorten: for more information use: shorten -h
shorten: cannot use -e, -k or -i with data on standard input
shorten: for more information use: shorten -h
shorten: will not input data from a tty
shorten: for more information use: shorten -h
shorten: will not input data from a tty
shorten: for more information use: shorten -h
shorten: will not input data from a tty
shorten: for more information use: shorten -h
shorten: will not output data to a tty
shorten: for more information use: shorten -h
shorten: will not output data to a tty
shorten: for more information use: shorten -h
shorten: missing seek table filename for -S
shorten: for more information use: shorten -h
shorten: number of bytes to copy must be positive
shorten: for more information use: shorten -h
shorten: block size must be greater than zero
shorten: for more information use: shorten -h
shorten: number of channels must be greater than zero
shorten: for more information use: shorten -h
shorten: number of bytes to discard must be positive
shorten: for more information use: shorten -h
shorten: number of blocks for mean estimation must be positive
shorten: for more information use: shorten -h
shorten: Useful signal to noise ratios are positive
shorten: for more information use: shorten -h
shorten: linear prediction order must be in the range 0 ... 64
shorten: for more information use: shorten -h
shorten: linear prediction order must be in the range 0 ... 64
shorten: for more information use: shorten -h
shorten: quantisation level must be positive
shorten: for more information use: shorten -h
shorten: unknown file type: bad
shorten: for more information use: shorten -h
shorten: currently supported versions are in the range 1 ... 3
shorten: for more information use: shorten -h
shorten: currently supported versions are in the range 1 ... 3
shorten: for more information use: shorten -h
shorten: -k, -s and -S can only be used on shorten files
shorten: for more information use: shorten -h
shorten: -k, -s and -S can only be used on shorten files
shorten: for more information use: shorten -h
shorten: -k, -s and -S can only be used on shorten files
shorten: for more information use: shorten -h
shorten: cannot use -s with -S
shorten: for more information use: shorten -h
shorten: cannot use -e with -i
shorten: for more information use: shorten -h
shorten: cannot use -e with -k
shorten: for more information use: shorten -h
shorten: cannot use -i with -k
shorten: for more information use: shorten -h
shorten: cannot use -e with -x
shorten: for more information use: shorten -h
shorten: cannot use -i with -x
shorten: for more information use: shorten -h
shorten: cannot use -x with -k
shorten: for more information use: shorten -h
shorten: cannot use -x with -s
shorten: for more information use: shorten -h
shorten: cannot use -x with -S
shorten: for more information use: shorten -h
shorten: cannot use -k with -s
shorten: for more information use: shorten -h
shorten: cannot use -k with -S
shorten: for more information use: shorten -h
shorten: the predictor order must be less than the block size
shorten: for more information use: shorten -h
shorten: the -u flag is only applicable to ulaw coding
shorten: for more information use: shorten -h
shorten: too many filenames
shorten: for more information use: shorten -h
shorten: EOF on input when discarding header
shorten: for more information use: shorten -h
shorten: EOF on input when discarding header
shorten: for more information use: shorten -h
shorten: file 'seekable.shn' already contains seek information
shorten: for more information use: shorten -h
shorten: file 'test.shn' does not contain seek information
shorten: for more information use: shorten -h
shorten: could not open file 'missing.wav' for input
shorten: for more information use: shorten -h
shorten: could not open file 'missing.shn' for input
shorten: for more information use: shorten -h
shorten: input file is not a valid RIFF WAVE file
shorten: for more information use: shorten -h

PASS: test-errors.sh

========================  General shorten tests  =========================

+ Running general shorten tests against mono benchmark files...

  + Checking wav test files...
  + Checking aiff test files...

+ Running general shorten tests against stereo benchmark files...

  + Checking wav test files...
  + Checking aiff test files...

PASS: test-general.sh

=======================  shorten seek table tests  =======================

+ Running seek table tests against mono benchmark files...

creating seek table file: 'seektest.skt'
creating seek table file: 'seektest.skt'
creating seek table file: 'nametest.ext.skt'
appending seek table to 'seektest.shn'
creating seek table file: 'stdin.skt'
creating seek table file: 'stdin.skt'
appending seek table to 'seektest.shn'
appending seek table to 'test.shn'
removing seek table from file 'seekable.shn'

+ Running seek table tests against stereo benchmark files...

creating seek table file: 'seektest.skt'
creating seek table file: 'seektest.skt'
creating seek table file: 'nametest.ext.skt'
appending seek table to 'seektest.shn'
creating seek table file: 'stdin.skt'
creating seek table file: 'stdin.skt'
appending seek table to 'seektest.shn'
appending seek table to 'test.shn'
removing seek table from file 'seekable.shn'

PASS: test-seek.sh
==================
All 3 tests passed
==================
make[1]: Nothing to be done for `check-am'.

Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ sudo make install
Password:
Making install in man
make[2]: Nothing to be done for `install-exec-am'.
test -z "/usr/local/share/man/man1" || .././install-sh -c -d "/usr/local/share/man/man1"
 /usr/bin/install -c -m 644 './shorten.1' '/usr/local/share/man/man1/shorten.1'
Making install in utils
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
test -z "/usr/local/bin" || .././install-sh -c -d "/usr/local/bin"
  /usr/bin/install -c 'shorten' '/usr/local/bin/shorten'
make[3]: Nothing to be done for `install-data-am'.
Making install in tests
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.

Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ shntool conv ~/Desktop/test.shn
Converting [/Users/jishaq/Desktop/test.shn] (4:30.31) --> [/Users/jishaq/Desktop/test.wav] : 100% OK
Jeffs-MacBook-Pro:shorten-3.6.1 jishaq$ 

###
###
###
###
###

[test.shn.zip](https://github.com/Homebrew/homebrew-core/files/3948672/test.shn.zip)

**Comment by SMillerDev** [comment]
If you've successfully compiled it with `shorten` locally, could you make a pull request for this? https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request could help you

**Comment by fxcoudert** [comment]
Debian ships shntool without shorten, too (https://packages.debian.org/sid/shntool), so it's apparently not a required dependency.

(Both shntool and shorten are unmaintained, apparently…)

**Comment by jishaq** [comment]
As a former live show taper and digital archivist with several thousand gigs of music in the "Shorten" lossless compression format, I have been using the "shntool" utility for almost a decade, and consider myself an expert with this tool.

I can assure you that shntool is not useful without being able to perform its **namesake** conversions to/from the shn format, via the 'shorten' codec dependency I've noted above.  As such, there is no point in neither brew nor Debian to provide this utility without also providing the "shorten" library.

How shntool may be packaged in various linux distros has no bearing on the truth of my previous statement:  It is just as neutered in Debian as it is via Brew.

There are very few tools around anymore that can work with the "shn" format, particularly on the Mac platform.  There are zero which are free, as shntool is:  I would therefore urge you either to reconsider including the "shorten" codec dependency, which appears to be quite a simple task; or, simply to omit the shntool package from your library of available packages as it is useless without it.  I would be happy to perform validation testing in the case of the former.

**Comment by SMillerDev** [comment]
While homebrew core might not ship the exact configuration you want or need, you can just create your own copy of the formula that you can install through homebrew. https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap can help you with this.
