### ISSUE TITLE
Update tmux bash completions

### ISSUE THREAD

**Issue by truthdoug** [Homebrew/homebrew-core#4776]
The comments in `/usr/local/etc/bash_completions.d/tmux` indicate that the code is based on code from [this github repository](https://github.com/przepompownia/tmux-bash-completion). The readme on that repo now says:

> I deprecated this repository in favor of currently maintained
> 
> https://github.com/imomaliev/tmux-bash-completion

It'd be good to have the tmux completions updated.

**Comment by zmwangx** [comment]
I see this in the current tmux formula:

```ruby
  resource "completion" do
    url "https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/homebrew_1.0.0/completions/tmux"
    sha256 "05e79fc1ecb27637dc9d6a52c315b8f207cf010cdcee9928805525076c9020ae"
  end
```

and apparently it was updated in 6472d0c64ebbabb4bf20975b9116dd0686af4738. If you installed tmux 2.2 before that commit (very likely), just run `brew reinstall tmux` and you're golden.
