### ISSUE TITLE
glew cmake files point to bogus xcode location

### ISSUE THREAD

**Issue by spyroot** [Homebrew/homebrew-core#47767]
Hey folks,

I've noticed all paths in glew.cmake are wrong.
/usr/local/Cellar/glew/2.1.0/lib/cmake/glew/glew-targets.cmake

Notice it point to a xcode beta location and osx10.14.sdk. in my case it normal xcode 11.1 and MacOSX10.15.sdk

INTERFACE_LINK_LIBRARIES "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework;/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework"

HOMEBREW_VERSION: 2.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe99bd9823fadea1cf918b1ed8366de7f40d336
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 341a18f3a1519c866e017dab3dbd7a2f4c4566cb
Core tap last commit: 71 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 13
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.1
CLT headers: 10.3.0.0.1.1562985497

version head.

glew: stable 2.1.0 (bottled), HEAD
OpenGL Extension Wrangler Library
https://glew.sourceforge.io/
/usr/local/Cellar/glew/2.1.0 (39 files, 3MB) *
  Poured from bottle on 2019-12-12 at 15:24:45
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/glew.rb
==> Dependencies
Build: cmake ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 3,473 (30 days), 9,661 (90 days), 38,488 (365 days)
install-on-request: 1,705 (30 days), 5,207 (90 days), 20,378 (365 days)
build-error: 0 (30 days)

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
