### ISSUE TITLE
why does `brew doctor` say I haven't updated in 24 hours when I have?

### ISSUE THREAD

**Issue by wellsoliver** [Homebrew/homebrew-core#4788]
I have a cronjob at midnight to run `brew update` and it's working, and then when I run:

`stat $(brew --prefix)/.git/refs/heads/master`

It says:

`16777224 4105814 -rw-r--r-- 1 wells admin 0 41 "Sep 13 00:00:10 2016" "Sep 13 00:00:10 2016" "Sep 13 00:00:10 2016" "Sep 13 00:00:10 2016" 4096 8 0 /usr/local/.git/refs/heads/master`

Clearly showing it's been updated. But running `brew doctor`says:

`Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run brew update.`

Which isn't true. Why does this happen?

**Comment by zmwangx** [comment]
Please show us you `brew config`.

**Comment by wellsoliver** [comment]
```
$ brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a264cf59733fa8e0f69f8e6567e069a8cfd8bde
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 25f426714df13e7f430d940f5e92e3c0cfcfca9f
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

**Comment by zmwangx** [comment]
```
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5a264cf59733fa8e0f69f8e6567e069a8cfd8bde
Last commit: 33 hours ago
```

Might be referring to this.

**Comment by wellsoliver** [comment]
Well that's out of my control and unrelated to my local install, right? That's just the last time someone committed something to the branch, right?

**Comment by zmwangx** [comment]
Yes. Anyway, what's the big deal?

**Comment by wellsoliver** [comment]
There isn't one. I was just kind of going nuts about my cron job not doing what I really, really thought my cronjob was doing. Sanity check!

**Comment by zmwangx** [comment]
Nah, `brew doctor` is just supposed to be informative (and extra paranoid I would say). Just run `brew update` often and you're good. If you think you hit an update bug there's always

```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```

**Comment by zmwangx** [comment]
Closing this. Do ask if there's anything else we can help with.

**Comment by UniqMartin** [comment]
This check hasn't been updated since we split the package manager and its formulae into two separate repositories. There's a lot less activity on the package manager side and there can be times when it doesn't change for more than 24 hours, which in itself is a non-issue.

I guess it would be a good idea to modify the check to inspect both repositories and only warn if both haven't been updated for 24 hours. @wellsoliver If you felt like poking our code a bit, tracking down the origin of this warning message and then modifying the associated check should be relatively straightforward. A PR that improves this would certainly be welcome!
