### ISSUE TITLE
sshfs 2.10 does not work on mojave with osxfuse 3.10.4 (cask) that wants sshfs 2.5

### ISSUE THREAD

**Issue by cbertelli** [Homebrew/homebrew-core#47914]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing sshfs to use remote directories

## What happened (include command output)

I installed sshfs 2.10 without issues, it run without warnings as well, but the remote directories that I wanted to mount were not really mounted.
When listing mounted directory I got the error:
`Device not configured`.
Only using version 2.05 (pkg) found on osxfuse site I got sshfs working.

I shoud add that running brew gist-logs I got this error
`Error: Your Xcode (11.0) is outdated.
Please update to Xcode 11.3 (or delete it).
Xcode can be updated from the App Store.
`
but, installing from a bottle, I may think this is not so important; anyway I got no warning using brew.

<details>
  <summary>Command output</summary>
  <pre>

 Device not configured

  </pre>
</details>

## What you expected to happen

after mounting with
`sshfs user@host.doma.in:/home/user ~/mnt/server -o idmap=user -o follow_symlinks -o defer_permissions -o allow_other`
I expected to get the remote home mounted on ~/mnt/server.
What I got instead is the error detailed before.

## Step-by-step reproduction instructions (by running `brew install` commands)

I got no warning.
I had sshfs 2.05, I think; after upgrading osxfuse, I upgraded sshfs as well.
Since upgrading I got the error.

I noticed that the suggested version of sshfs on the site of osxfuse was 2.05, I unistalled version 2.10 and copied the content of sshfs-2.50.pkg outside the /usr/local tree.
Version 2.5 allowed me to mount the remote directories as I needed.

**Comment by fxcoudert** [comment]
Tried to update to the latest sshfs version: https://github.com/Homebrew/homebrew-core/pull/47971
it is apparently not compatible with osxfuse. This should be reported to osxfuse.
