### ISSUE TITLE
Error building llvm38 --with-{asan,ubsan,clang}

### ISSUE THREAD

**Issue by dymk** [Homebrew/homebrew-core#4796]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

Running: 
`brew install llvm38 --with-asan --with-ubsan --with-clang`

Fails with several errors similar to: 
`cp: /private/tmp/llvm38-20160913-55727-18ab3nz/tools/clang/runtime/compiler-rt/clang_darwin/profile_ios/libcompiler_rt.a: No such file or directory`

Full build log and errors: 

https://gist.github.com/dymk/62f019e5b9b8f91f91d1f4855dd898a8

It seems that some archives are assumed to be generated, but are indeed not during compilation.

**Comment by zmwangx** [comment]
Please use `brew gist-logs llvm38` to generate a gist with all the logs as well as your system & brew information that we need, rather than rolling your own.

**Comment by dymk** [comment]
`gist-logs` output: https://gist.github.com/102013f95c81aa4526cd10231dc1abf6

**Comment by MikeMcQuaid** [comment]
This was migrated to homebrew/core.
