### ISSUE TITLE
brew services start mongodb-community@4.2 --p 28018 fail

### ISSUE THREAD

**Issue by LargeOrange** [Homebrew/homebrew-core#47967]
I want to start mongo on the specified port.

I try "brew services start mongodb-community@4.2 --p 28018", but get "Error: 28018 is not a url or existing file"

**Comment by iMichka** [comment]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by SMillerDev** [comment]
Mongo isn't shipped by homebrew either. You'll have to file an issue in their tap.

**Comment by MikeMcQuaid** [comment]
Also we don't support specifying ports.
