### ISSUE TITLE
postgresql v12.1 causes ruby to crash with __NSPlaceholderDate initialize

### ISSUE THREAD

**Issue by directionless** [Homebrew/homebrew-core#47997]
Hi, this is a somewhat incomplete bug report. I know that must be frustrating.

I think the postgresql 12.1 cask is triggering a repeat of https://bugs.ruby-lang.org/issues/14009

I recently upgraded a bunch of stuff in brew. After doing so, my rails app broke. It was manifesting much as the above bug. Downgrading to `postgresql@11` fixed that issue, installing @12 re-triggered it. I see at least one other recent issue like this (https://github.com/rbenv/ruby-build/issues/1385 https://github.com/puma/puma/issues/2084) and I've see another couple comments on the internet. 

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use rails and postgres

## What happened (include command output)

Ruby crashes

<details>
  <summary>Command output</summary>
  <pre>
web    | objc[44155]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
web    | objc[44155]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
  </pre>
</details>

## What you expected to happen

Ruby should not crash

## Step-by-step reproduction instructions (by running `brew install` commands)

Sadly, this one I'm at a loss for.

```
brew install postgresql@12
brew link postgresql@12 --force
gem uninstall pg
bundle install
```

But I don't have an isolated ruby test case

**Comment by directionless** [comment]
Not sure it helps any, but otool output.

<details>
  <summary>otool link on v11</summary>
  <pre>
dover:~ seph$ otool -L /usr/local/opt/postgresql@11/lib/libpq.5.dylib
/usr/local/opt/postgresql@11/lib/libpq.5.dylib:
	/usr/local/opt/postgresql@11/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.11.0)
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
  </pre>
</details>

<details>
  <summary>otool link on v12</summary>
  <pre>
dover:~ seph$ otool -L /usr/local/opt/postgresql\@12/lib/libpq.5.dylib 
/usr/local/opt/postgresql@12/lib/libpq.5.dylib:
	/usr/local/opt/postgresql/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.12.0)
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos (compatibility version 5.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/System/Library/Frameworks/LDAP.framework/Versions/A/LDAP (compatibility version 1.0.0, current version 2.4.0)
  </pre>
</details>

**Comment by SMillerDev** [comment]
Can you post `brew config` and `brew doctor`? And did you try reporting this upstream to postgres?

**Comment by directionless** [comment]
<details>
  <summary>doctor and config output</summary>
  <pre>
dover:k2 seph$ brew doctor; echo ""; brew config
Your system is ready to brew.

HOMEBREW_VERSION: 2.2.1-42-g205a086
ORIGIN: https://github.com/Homebrew/brew
HEAD: 205a08653bd6f12047114772b6b9fef14374f979
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: da5be93c871a99fb4e69dd47be67a41fa722d376
Core tap last commit: 57 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_VISUAL: vi
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_192
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3
</pre>
</details>

I haven't tried reporting to postgres yet. I don't yet understand enough about how homebrew builds to know if it's a formula bug, or an upstream bug

**Comment by fxcoudert** [comment]
Hi @directionless, there seems to be no indication that this is specific to Homebrew. In fact it seems to be happening quite deep inside Ruby's internals. I would suggest you open a bug report with them, it is unlikely we can do anything on our end, sorry.

**Comment by directionless** [comment]
It may be build dependent. I'll see if a straight postgresql 12.1 build can reproduce outside outside homebrew

**Comment by ojab** [comment]
It's probably https://www.postgresql.org/message-id/94f70eee-eb72-88d7-ff8f-53cfbe130a69%40crunchydata.com, so postgresql should be rebuild with krb5 from homebrew to fix that.

**Comment by ojab** [comment]
See also https://github.com/ged/ruby-pg/issues/311

**Comment by fxcoudert** [comment]
Should be fixed by this then: https://github.com/Homebrew/homebrew-core/pull/47494
