### ISSUE TITLE
Using homebrew installed python in xonsh

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/homebrew-core#4800]
Currently the python env is created by
virtualenv_create(libexec, "python3")

'ls' shows it is linked to the system python
/usr/local/Cellar/xonsh/0.4.6/libexec/lib/python3.5/copy.py -> ../../../../../../opt/python3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py

Can I use brewed python3 instead?

**Comment by zmwangx** [comment]
That's not system Python 3. It's clearly a brew path which resolves to `/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py`. It's just that the brewed Python 3 was built with a framework layout rather than traditional Unix layout.
