### ISSUE TITLE
Installing the nushell formula also installs rust

### ISSUE THREAD

**Issue by TimDeve** [Homebrew/homebrew-core#48005]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
No logs
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 
Does not seem applicable

## What you were trying to do (and why)

Install the nushell formula.

## What happened (include command output)

The formula started to install rust as a dependency

<details>
  <summary>Command output</summary>
  <pre>

==> Installing dependencies for nushell: rust
==> Installing nushell dependency: rust
==> Downloading https://homebrew.bintray.com/bottles/rust-1.39.0.mojave.bottle.tar.gz
Already downloaded: /Users/myuser/Library/Caches/Homebrew/downloads/d1ee7a1176de1bf7aa7bc8f6ff94ff8e48304b793a7c6ff992beed54c6f3fa27--rust-1.39.0.mojave.bottle.tar.gz
==> Pouring rust-1.39.0.mojave.bottle.tar.gz
  </pre>
</details>

## What you expected to happen

Only install the nushell binary and dependencies needed for the running the binary (openssl?). Rust seems to only be needed to build nushell, so it should not be installed when just pouring the bottle.

This is especially a problem as the canonical way to install rust locally is to use rustup and as such I don't want brew to install it as well.

## Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install nushell
```

**Comment by jonchang** [comment]
Can you please fill out the full issue template?

**Comment by TimDeve** [comment]
I have omitted as the output of brew config and brew doctor as they don't seem applicable to this situation.

**Comment by TimDeve** [comment]
It seems that `=> :build` needs to be added to this [line](https://github.com/Homebrew/homebrew-core/blob/dd63f6e36c52dd7a81b972722446a96f4e80ae54/Formula/nushell.rb#L16) but I'm not familiar enough with formula creation to be sure I won't break anything by creating a PR.

**Comment by SMillerDev** [comment]
> It seems that `=> :build` needs to be added to this [line](https://github.com/Homebrew/homebrew-core/blob/dd63f6e36c52dd7a81b972722446a96f4e80ae54/Formula/nushell.rb#L16) but I'm not familiar enough with formula creation to be sure I won't break anything by creating a PR.

That's what we have tests for. Don't worry about breakage.

**Comment by TimDeve** [comment]
Cool, I'll do that then.

**Comment by TimDeve** [comment]
The PR is here: #48009

**Comment by fxcoudert** [comment]
Fixed
