### ISSUE TITLE
"Wireshark: Permission denied" in Terminal after installing cask "wireshark"

### ISSUE THREAD

**Issue by cs-1** [Homebrew/homebrew-core#48099]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

  My issue is regarding a cask, is there an equivalent of `brew gist-logs` for casks? I did a `brew cask audit` and it didn't show any problems.

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Here's the output of `brew config`:

```
HOMEBREW_VERSION: 2.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe99bd9823fadea1cf918b1ed8366de7f40d336
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 25f2bbf1d01bdcaa04878e7e45042d3fdbb9ef18
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => curl
Java: 12.0.1
macOS: 10.15.2-x86_64
CLT: 11.3.0.0.1.1574140115
Xcode: 11.3
CLT headers: 11.3.0.0.1.1574140115
XQuartz: 2.7.11 => /opt/X11
```

`brew doctor` says "Your system is ready to brew.".

## What you were trying to do (and why)

I installed wireshark by issuing `brew cask install wireshark` to install the latest version of wireshark.

## What happened (include command output)

Whenever you open a terminal the following error message appears:

<details>
  <summary>Command output</summary>
  <pre>
Wireshark: Permission denied
  </pre>
</details>

## What you expected to happen

After the wireshark installation there shouldn't be any error messages when opening a terminal. These messages started to appear with the upgrade to wireshark 3.2. It was not present in earlier versions (also installed with `brew cask install wireshark`).

## Step-by-step reproduction instructions (by running `brew install` commands)

- `brew cask install wireshark`
- Open any terminal (Terminal.app or iTerm2 etc.).

**Comment by SMillerDev** [comment]
You should create an issue with the cask repo:
https://github.com/Homebrew/homebrew-cask. But if I had to guess I'd say that it runs Wireshark somewhere in your bashrc/zshrc

**Comment by cs-1** [comment]
Arg. Sorry, I messed the repo up. I'll close the issue here and re-open it there.
