### ISSUE TITLE
g++ produces many warnings with Xcode 8's clang as assembler

### ISSUE THREAD

**Issue by q-p** [Homebrew/homebrew-core#4812]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

GCC still uses clang's internal assembler. When that clang is the one from Xcode 8 (`Apple LLVM version 8.0.0 (clang-800.0.38)`), it produces many warnings such as

```
/var/folders/mk/y7lk0xrx72lcn_2q3d12jcch0000gn/T//cc1dR6yG.s:3:11: warning: section "__textcoal_nt" is deprecated
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
/var/folders/mk/y7lk0xrx72lcn_2q3d12jcch0000gn/T//cc1dR6yG.s:3:11: note: change section name to "__text"
        .section __TEXT,__textcoal_nt,coalesced,pure_instructions
                 ^      ~~~~~~~~~~~~~
```

As this is mostly about weak symbols, it mostly happens with templated code (as such symbols are often linked weakly).

clang bug: https://llvm.org/bugs/show_bug.cgi?id=28427
gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71767 (which also contains a patch renaming the sections)

It would be very helpful if home-brew's gcc-formula patched the section names, if clang 3.8 or Xcode 8 are used.

**Comment by fxcoudert** [comment]
This was fixed upstream and integrated into the latest release (GCC 6.3), which is now in homebrew.

**Comment by ilovezfs** [comment]
It still "needs" to be backported to the older versions, however.

**Comment by fxcoudert** [comment]
If homebrew aims at providing support for older GCC versions on newer OSes, yes (but that's far from trivial). If it chooses to follow upstream, it might get backported to 5.x, but not to earlier versions.

**Comment by ilovezfs** [comment]
in any case I'm closing this since the main formula is fixed and no one is actively working on the backports
