### ISSUE TITLE
PR build checks take over 7 hours

### ISSUE THREAD

**Issue by okigan** [Homebrew/homebrew-core#48130]
see snapshot, please add a timeout (20 minutes?)

<img width="1078" alt="Screen Shot 2019-12-20 at 4 53 39 PM" src="https://user-images.githubusercontent.com/478302/71300443-a8cfd900-2349-11ea-86c9-be92c7484fe6.png">

**Comment by jonchang** [comment]
Sorry, we won't be doing this. Some pull requests will just take a long time due to testing reverse dependencies.

**Comment by SMillerDev** [comment]
We want things to be checked and build, a 20 minutes timeout will allow about 20% of all formula to build and test within the timeout window. These slow builds are unfortunately one of the problems of package management.
