### ISSUE TITLE
g'mic not supporting FFT properly

### ISSUE THREAD

**Issue by manyjeans** [Homebrew/homebrew-core#48196]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to use the rodilius filter on an image using the g’mic CLI installed through brew (brew install gmic) on a mac but I am getting the following error: “Specified real and imaginary parts have non 2^N dimension along the Y-axis)”

Any ideas what can be done to fix this issue?

## What happened (include command output)

<pre>
gmic -input input/world.jpg rodilius 10,4,400,16 smooth 60,0,1,1,4 normalize_local 10,16 -output output/world_rodilius.jpg
</pre>

<details>
  <summary>Command output</summary>
  <pre>
[gmic]-0./ Start G’MIC interpreter.
[gmic]-0./ Input file ‘input/world.jpg’ at position 0 (1 image 1024x1024x1x3).
[gmic]-1./ Apply rodilius filter on image [0] with amplitude 10, thickness 4, sharpness 400, 16 orientations, offset 0 and brighter color mode.
[gmic] *** Error in ./rodilius/*repeat/*local/(…)/*local/convolve_fft/*repeat/*local/ *** Command ‘fft’: gmicList::FFT(): Specified real and imaginary parts (1280,1280,1,3) have non 2^N dimension along the Y-axis.
</pre>
</details>

## What you expected to happen

I expected the command to complete properly. I reached out to the creator of G'MIC, who mentioned that this is _"definitely a broken package issue. The CLI tool has been compiled without linking it against the libfftw, so this error appears. The package maintainer must enable the libfftw when compiling G’MIC (which is usually enabled by default), to let G’MIC compute the FFT of images with arbitrary sizes."_

## Step-by-step reproduction instructions (by running `brew install` commands)

Given standard image (world.jpg) passed as input:

<pre>
brew install gmic
gmic -input world.jpg rodilius 10,4,400,16 smooth 60,0,1,1,4 normalize_local 10,16 -output world_rodilius.jpg
</pre>

**Comment by alebcay** [comment]
For reference, relevant upstream discussion from which the issue is excerpted is at https://discuss.pixls.us/t/fft-specified-real-and-imaginary-parts-have-non-2-n-dimension-along-the-y-axis/15355/4.

**Comment by alebcay** [comment]
Built `gmic` from source via Linuxbrew in WSL Debian Stretch (don't have access to my macOS machine right now). Unable to reproduce the issue.
```
❯ gmic -input world.jpg rodilius 10,4,400,16 smooth 60,0,1,1,4 normalize_local 10,16 -output world_rodilius.jpg
[gmic]-0./ Start G'MIC interpreter.
[gmic]-0./ Input file 'world.jpg' at position 0 (1 image 3000x3002x1x3).
[gmic]-1./ Apply rodilius filter on image [0] with amplitude 10, thickness 4, sharpness 400, 16 orientations, offset 0 and brighter color mode.
[gmic]-1./ Smooth image [0] anisotropically, with amplitude 60, sharpness 0, anisotropy 1, alpha 1, sigma 4, dl 0.8, da 30, 
precision 2, nearest-neighbor interpolation and fast approximation enabled.
[gmic]-1./ Normalize image [0] locally, with amplitude 10, radius 16, neighborhood smoothness 4% and average smoothness 2%.
[gmic]-1./ Output image [0] as jpg file 'world_rodilius.jpg', with quality 100% (1 image 3000x3002x1x3).
[gmic]-1./ End G'MIC interpreter.
```
Maybe there's something wrong with the macOS build process or bottles?

@manyjeans, could you please try the operation from both the bottled `gmic` (just plain `brew install gmic`) and also built from source on your own machine (`brew install --build-from-source gmic`) and see if the issue also happens there?

**Comment by manyjeans** [comment]
@alebcay - confirming that the comment works fine when building from source! Thank you very much for your help

**Comment by alebcay** [comment]
Thanks for the info, the issue may be with our bottling infrastructure when the most recent bottle/binary was produced. Leaving the issue open for now until we can verify what caused the issue.

**Comment by SMillerDev** [comment]
@alebcay got time to add a revision to the formula to see if it fixes the issues?

**Comment by alebcay** [comment]
Bumped revision and improved test to cover the command used above in #48236.

**Comment by alebcay** [comment]
Should be resolved now, please shout/reopen if this is not the case.
