### ISSUE TITLE
Seem to can't install perl

### ISSUE THREAD

**Issue by Al2Klimov** [Homebrew/homebrew-core#48194]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/Al2Klimov/a2a67e0d748b6fe05a1c5380c0279e2a

## What you were trying to do (and why)

I've set up a fresh Homebrew instance and installed perl.

## What happened (include command output)

The command didn't complete successfully.

<details>
  <summary>Command output</summary>
  <pre>
==> Tapping homebrew/core
Cloning into '/private/var/folders/3h/0nn80rp973b08bd0r56g5pd80000gn/T/tmp.UpVZWViZ/homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 5095, done.
remote: Counting objects: 100% (5095/5095), done.
remote: Compressing objects: 100% (4892/4892), done.
remote: Total 5095 (delta 50), reused 317 (delta 8), pack-reused 0
Receiving objects: 100% (5095/5095), 4.13 MiB | 3.68 MiB/s, done.
Resolving deltas: 100% (50/50), done.
Tapped 2 commands and 4879 formulae (5,137 files, 12.8MB).
==> Downloading https://www.cpan.org/src/5.0/perl-5.30.0.tar.gz
Already downloaded: /Users/aklimov/Library/Caches/Homebrew/downloads/feadffeb2768864300cbf981f5ab948437d1a756cbce21ae441f9d912377112c--perl-5.30.0.tar.gz
==> ./Configure -des -Dprefix=/private/var/folders/3h/0nn80rp973b08bd0r56g5pd80000gn/T/tmp.UpVZWViZ/homebrew/Cellar/perl/5.30.0 -Dprivlib=/private/var/folders/3h/0nn80rp973b08bd0r56g5pd80000gn/T/tmp.UpVZW
==> make
Last 15 lines from /Users/aklimov/Library/Logs/Homebrew/perl/02.make:
Processing auxiliary/LBTest.txt
Processing ScriptExtensions.txt
Processing IndicSyllabicCategory.txt
Processing BidiBrackets.txt
Processing IndicPositionalCategory.txt
Processing VerticalOrientation.txt
Processing EquivalentUnifiedIdeograph.txt
Processing EmojiData.txt
Finishing processing Unicode properties
Compiling Perl properties
Creating Perl synonyms
Writing tables
Making pod file
Making test script
Updating 'mktables.lst'

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
perl 5.30.1 https://github.com/Homebrew/homebrew-core/pull/46843
➜  tmp.UpVZWViZ # Note the red arrow at the beginning of this line indicating the failure of the previous command.
  </pre>
</details>

## What you expected to happen

The command completed successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `pushd $(mktemp -d)`
2. `mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew`
3. `export PATH="$(pwd)/homebrew/bin:$PATH"`
4. `brew install perl`

**Comment by SMillerDev** [comment]
You're using a non-standard install path, which might break configuration as it's not tested (and is documented as "use at your own peril"). The output also literally tells you not to make an issue for your problem.

**Comment by iMichka** [comment]
Exactly, it's written in the logs:
`Do not report this issue to Homebrew/brew or Homebrew/core!`
