### ISSUE TITLE
wine failed to build on 10.11.6 Error: Empty archive

### ISSUE THREAD

**Issue by SODACANS** [Homebrew/homebrew-core#4820]
Running `brew install wine` gives the following output:

> ==> Installing dependencies for wine: xz, libpng, freetype, jpeg, pkg-config, libtool, libusb, libusb-compat, fontconfig, libtiff, webp, gd, libgphoto2, little-cms2, jasper, libicns, makedepend, openssl, net-snmp, sane-backends, libtasn1, gmp, nettle, gnutls
> ==> Installing wine dependency: xz
> ==> Using the sandbox
> ==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
> ######################################################################## 100.0%
> ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.2
> ==> make install
> 🍺  /usr/local/Cellar/xz/5.2.2: 91 files, 1.8M, built in 34 seconds
> ==> Installing wine dependency: libpng
> ==> Downloading ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.25.tar.xz
> ######################################################################## 100.0%
> Error: Empty archive

I have run `brew update` many times and the output says it is up-to-date. Also `brew doctor` says I am ready to brew. I have tried uninstalling and reinstalling xz and clearing ~Library/Caches/Homebrew/ of the libpng-1.6.25.tar.xz file to force it to redownload. Running `brew gist-logs wine` and `brew gist-logs libpng` both give

> Error: No logs.

Here is the output of `brew config`:

> HOMEBREW_VERSION: 0.9.9
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: 985e772278da3cf84ea998d97695e3c17b984775
> Last commit: 3 hours ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: d8764c105feb474b47fe291815112ae1d0fb91ef
> Core tap last commit: 2 hours ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: quad-core 64-bit skylake
> Homebrew Ruby: 2.0.0-p648
> Clang: 8.0 build 800
> Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Perl: /usr/bin/perl
> Python: /usr/bin/python
> Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
> Java: 1.8.0_101
> OS X: 10.11.6-x86_64
> Xcode: 8.0
> CLT: N/A
> X11: 2.7.9 => /opt/X11

**Comment by zmwangx** [comment]
Same issue as https://github.com/Homebrew/brew/issues/969. Please see discussion there.

**Comment by DomT4** [comment]
Please `brew update && brew reinstall xz`. Should be fixed now by https://github.com/Homebrew/brew/pull/970's merge.

**Comment by SODACANS** [comment]
Thanks for the update :) seems to be working now.
