### ISSUE TITLE
`rustup-init` formula should not depend on `rust` formula

### ISSUE THREAD

**Issue by Centaur** [Homebrew/homebrew-core#48211]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

upgrade rustup-init to the latest version 1.21.0

## What happened (include command output)

`rustup-init` formula depends on `rust` formula, and the `make` step of `rust` formula never ends.

## What you expected to happen

`rustup` is the tool for installing rust, should not depend on it. Actually, I have not problem installing rust 1.40.0 by using `rustup update`.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade rustup-init`

**Comment by SMillerDev** [comment]
Since it depends on the existence of the cargo command, it does depend on a version of rust.
