### ISSUE TITLE
SHA256 mismatch error yara

### ISSUE THREAD

**Issue by reyder** [Homebrew/homebrew-core#4822]
Hi, I have problem installing yara package.

```
==> Installing dependencies for radare2: yara
==> Installing radare2 dependency: yara
==> Using the sandbox
==> Downloading https://github.com/VirusTotal/yara/archive/v3.5.0.tar.gz
Already downloaded: /Users/reyder/Library/Caches/Homebrew/yara-3.5.0.tar.gz
Error: SHA256 mismatch
Expected: ff2ee440515684c272df52febc8b73e730ca99ce194c24bd3cb43bec2b4c47f2
Actual: 4bc72ee755db85747f7e856afb0e817b788a280ab5e73dee42f159171a9b5299
Archive: /Users/reyder/Library/Caches/Homebrew/yara-3.5.0.tar.gz
```

I downloaded it manually and hash is different `4bc72ee755db85747f7e856afb0e817b788a280ab5e73dee42f159171a9b5299 `

**Comment by ilovezfs** [comment]
Yeah
```
1f7f1592 (ilovezfs              2016-08-03 22:36:38 -0700  4)   url "https://github.com/VirusTotal/yara/archive/v3.5.0.tar.gz"
```
But they retagged it 8 days ago https://github.com/VirusTotal/yara/releases/tag/v3.5.0

so that needs to be updated.

**Comment by hillu** [comment]
Seems like it. Diffing against the contents of the tarball I used for the Debian package:

<pre>
$ diff -uir yara-3.5.0 yara-3.5.0-new
Only in yara-3.5.0/tests/data: cdak_1024x768.exe
Only in yara-3.5.0/tests/data: old_ArmaFP.exe
Only in yara-3.5.0-new/tests/data: tiny
Only in yara-3.5.0/tests/data: tiny.exe
Only in yara-3.5.0-new/tests/data: tiny-idata-51ff
Only in yara-3.5.0/tests/data: tiny-idata-51ff.exe
Only in yara-3.5.0-new/tests/data: tiny-idata-5200
Only in yara-3.5.0/tests/data: tiny-idata-5200.exe
diff -uir yara-3.5.0/tests/test-pe.c yara-3.5.0-new/tests/test-pe.c
--- yara-3.5.0/tests/test-pe.c	2016-08-02 22:08:18.000000000 +0200
+++ yara-3.5.0-new/tests/test-pe.c	2016-09-06 22:09:47.000000000 +0200
@@ -6,13 +6,13 @@
   yr_initialize();
 
   assert_true_rule_file("import \"pe\" rule test { condition: pe.imports(\"KERNEL32.dll\", \"DeleteCriticalSection\") }",
-      "tests/data/tiny.exe");
+      "tests/data/tiny");
 
   assert_true_rule_file("import \"pe\" rule test { condition: pe.imports(\"KERNEL32.dll\", \"DeleteCriticalSection\") }",
-      "tests/data/tiny-idata-51ff.exe");
+      "tests/data/tiny-idata-51ff");
 
   assert_false_rule_file("import \"pe\" rule test { condition: pe.imports(\"KERNEL32.dll\", \"DeleteCriticalSection\") }",
-      "tests/data/tiny-idata-5200.exe");
+      "tests/data/tiny-idata-5200");
 
   yr_finalize();
   return 0;
diff -uir yara-3.5.0/tests/test-rules.c yara-3.5.0-new/tests/test-rules.c
--- yara-3.5.0/tests/test-rules.c	2016-08-02 22:08:18.000000000 +0200
+++ yara-3.5.0-new/tests/test-rules.c	2016-09-06 22:09:47.000000000 +0200
@@ -1034,35 +1034,6 @@
   assert_false_rule(
       "rule test { condition: entrypoint >= 0 }",
       NULL);
-
-  /* https://github.com/VirusTotal/yara/issues/373 */
-  assert_true_rule_file(
-      "import \"pe\" \
-       rule test { \
-        condition: pe.entry_point == 0x18 }",
-      "tests/data/old_ArmaFP.exe");
-
-  assert_true_rule_file(
-      "import \"pe\" \
-       rule test { \
-       strings: $right = { BE B0 11 40 00 } \
-        condition: $right at pe.entry_point }",
-      "tests/data/old_ArmaFP.exe");
-  /* $wrong = { 0B 01 4C 6F 61 64 4C } */
-
-  /* https://github.com/VirusTotal/yara/issues/399 */
-  assert_true_rule_file(
-      "import \"pe\" \
-       rule test { \
-        condition: pe.entry_point == 2 }",
-      "tests/data/cdak_1024x768.exe");
-
-  assert_true_rule_file(
-      "import \"pe\" \
-       rule test { \
-        strings: $a0 = { 68 00 00 42 00 31 C0 40 EB 58 } \
-        condition: $a0 at pe.entry_point }",
-      "tests/data/cdak_1024x768.exe");
 }
</pre>

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/homebrew-core/commit/827bc1e6cd934f8b4866da7ed3c716190f30fd19
