### ISSUE TITLE
fontconfig fails to perform post installation steps

### ISSUE THREAD

**Issue by arobinson** [Homebrew/homebrew-core#4825]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

`lease note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libecomlodr.dylib

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    dbus
`

- [ X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Issue occurs while running "brew postinstall fontconfig"

Error reported:
`==> Using the sandbox
==> Regenerating font cache, this may take a while
==> /usr/local/Cellar/fontconfig/2.12.1_1/bin/fc-cache -frv
Last 15 lines from /Users/andrew/Library/Logs/Homebrew/fontconfig/post_install.01.fc-cache:
2016-09-14 18:32:36 -0600

/usr/local/Cellar/fontconfig/2.12.1_1/bin/fc-cache
-frv

dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /usr/local/Cellar/fontconfig/2.12.1_1/lib/libfontconfig.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
  Referenced from: /usr/local/Cellar/fontconfig/2.12.1_1/lib/libfontconfig.1.dylib
  Expected in: /usr/lib/libSystem.B.dylib

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues`

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

https://gist.github.com/b0d3cb746245c663affb3fa30a19adba

**Comment by DomT4** [comment]
Please try `brew update && brew reinstall fontconfig`. Thanks!

**Comment by saj** [comment]
Works for me.

Was this fixed by `1d7aa1f` to Homebrew/homebrew-core?

**Comment by zmwangx** [comment]
Yes. Closing for now, please ask if there are still problems.
