### ISSUE TITLE
Suggestion: ask before performing breaking upgrades

### ISSUE THREAD

**Issue by JonRowe** [Homebrew/homebrew-core#48259]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade numpy as a demonstration of a package upgrade to help someone else debug timing issues.

## What happened (include command output)

brew upgraded many packages which I assume are related dependencies but also included a postgres major version which broke my install (due to #47077)

## What you expected to happen

brew to only upgrade numpy and not touch postgres

## Step-by-step reproduction instructions (by running `brew install` commands)

1) have an existing postgres 11 install with postgis 2.5
2) have an existing numpy installation
2) `brew upgrade numpy`

## What I'd like to happen

Brew detects upgrade to postgres required, package is flagged as breaking on upgrade, brew warns me of this and asks if I want to continue.

I feel this is the simplest solution, many packages are known to have upgrade problems, if homebrew detects a package update like this is selected it could warn me at least and I could abort and work out a manual work around.

**Comment by SMillerDev** [comment]
Homebrew-core just manages the package repo. You should move this issue to the homebrew/brew repo.
In addition to that, homebrew is meant to keep your software always up to date. If you don't ever update it, things will break way more often than when you use it as intended.

**Comment by JonRowe** [comment]
> Brew detects upgrade to postgres required, package is flagged as breaking on upgrade, brew warns me of this and asks if I want to continue.

Ah ok, the issue template makes it sound like it belongs here as its reproducible by a single `brew update`.

> In addition to that, homebrew is meant to keep your software always up to date. If you don't ever update it, things will break way more often than when you use it as intended.

I agree, however upgrading a package should also not break it, which it does with postgres + postgis. Going from postgres 11 and postgis 2.5 to postgres 12 and postgis 3 does not allow you to transfer databases as there is no postgis@2.5 package, no way 

If it had asked me if I wanted todo this today, when I was trying to finish things up for the holidays, I could have stopped work 2 hours earlier (as thats how much time it wasted).

**Comment by JonRowe** [comment]
Moving to homebrew/brew

**Comment by iMichka** [comment]
> If it had asked me if I wanted todo this today, when I was trying to finish things up for the holidays, I could have stopped work 2 hours earlier (as thats how much time it wasted

And we are doing all this work on our free time, (sometimes during our holidays, on the weekends, and in the evenings), as unpaid volunteers, while being understaffed. So keep in mind that stuff may break. And we owe you nothing, and should not feel pressured to fix anything just because you lost 2 work hours (which are paid by your employer anyway).

**Comment by JonRowe** [comment]
> And we are doing all this work on our free time, (sometimes during our holidays, on the weekends, and in the evenings), as unpaid volunteers, while being understaffed. So keep in mind that stuff may break. And we owe you nothing, and should not feel pressured to fix anything just because you lost 2 work hours (which are paid by your employer anyway).

Apologies, I did not mean it to come across as if I was pressuring you, as the maintainer of another Ruby library I fully understand the volunteer nature of open source, I was frustrated by the comment about "things breaking more often when you don't upgrade" (as a freelancer I am not paid for time lost like this) and attempting to emphasise that this is a frustrating situation that should not have happened.

Thanks for all your work and happy holidays.
