### ISSUE TITLE
SDL2 bottle is not codesigned on Catalina

### ISSUE THREAD

**Issue by VKoskiv** [Homebrew/homebrew-core#48356]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install SDL2.

## What happened (include command output)

SDL2 installed normally, but the installed `.dylib` is not codesigned at all:

<details>
  <summary>Command output</summary>
  <pre>

  vkoskiv@vMBP ~/D/d/c-ray> brew install sdl2
==> Downloading https://homebrew.bintray.com/bottles/sdl2-2.0.10.catalina.bottle.tar.gz
Already downloaded: /Users/vkoskiv/Library/Caches/Homebrew/downloads/de8d828cb5dafcd203abebcb0d301a84733cae8ede51987f9bc5483a8abb005f--sdl2-2.0.10.catalina.bottle.tar.gz
==> Pouring sdl2-2.0.10.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/sdl2/2.0.10: 87 files, 4.6MB
vkoskiv@vMBP ~/D/d/c-ray>

  </pre>
</details>

<details>
  <summary>No codesigning in the resulting .dylib</summary>
  <pre>
    vkoskiv@vMBP ~/D/d/c-ray> codesign -v /usr/local/lib/libSDL2-2.0.0.dylib
/usr/local/lib/libSDL2-2.0.0.dylib: code object is not signed at all
In architecture: x86_64
  </pre>
</details>

## What you expected to happen

To have a codesigned dynamic library installed in `/usr/local/lib/`

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install sdl2`
And then check the codesigning of the shared library
`codesign -v /usr/local/lib/libSDL2-2.0.0.dylib`

As a workaround, you can sign it yourself if you have a signing key:

`codesign -f -s "$signteam" /usr/local/lib/libSDL2-2.0.0.dylib`

If the `.dylib` isn't codesigned on Catalina, you get the following run-time error when developing software:

<details>
<summary>Example runtime error</summary>
<pre>
dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib
  Referenced from: /Users/vkoskiv/Library/Developer/Xcode/DerivedData/VKGui-fnloaopadakcvzcoujgtyvqvrohq/Build/Products/Debug/VKGui
  Reason: no suitable image found.  Did find:
	/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib: code signature in (/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/lib/libSDL2-2.0.0.dylib: code signature in (/usr/local/lib/libSDL2-2.0.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/usr/local/Cellar/sdl2/2.0.10/lib/libSDL2-2.0.0.dylib: code signature in (/usr/local/Cellar/sdl2/2.0.10/lib/libSDL2-2.0.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
</pre>
</details>

As far as I can tell, this is an issue only with the homebrew distribution, I verified that the binary downloaded from libsdl.org is indeed signed.

<details>
<summary>`brew config` output</summary>
<pre>
HOMEBREW_VERSION: 2.2.2-18-ge7a2fde
ORIGIN: https://github.com/Homebrew/brew
HEAD: e7a2fdeb651cdc449cea6dc7bc4fa391b2843c66
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dc0492178d710889bb28cee91006232eed6061f7
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.1, 10.0.2
macOS: 10.15.2-x86_64
CLT: N/A
Xcode: 11.3
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>

<details>
<summary>`brew doctor` output</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/fuse-ext2.pc

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  mysql

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
</pre>
</details>

**Comment by SMillerDev** [comment]
Homebrew doesn't codesign anything so this is exactly as expected.

**Comment by VKoskiv** [comment]
Why is the SDL2 package compiled by Homebrew developers and distributed unsigned, when it is available for download from libsdl.org as a signed package?
Not saying this is wrong per se, just trying to understand the rationale.
@SMillerDev

**Comment by SMillerDev** [comment]
Because homebrew compiles everything from source so the upstream binaries don't factor into it. If you want the officially signed version you can download from upstream, if you want an easy install you can pick the ones from homebrew.

**Comment by VKoskiv** [comment]
Could we add a caveat to the package to let users know to download from libsdl.org if the homebrew binary doesn't work?

**Comment by SMillerDev** [comment]
If the software doesn't work of you just compile it from source it's not really open source and should be removed from homebrew. Why would it not work without code signing?

**Comment by Kerndog73** [comment]
Is there a similar reason why the SDL2 formula doesn't install the framework? Is it just "not right for Homebrew"?

**Comment by SMillerDev** [comment]
Because nobody made it install the framework yet.
