### ISSUE TITLE
`g++-9 -D_XOPEN_SOURCE=600` command fails for program that includes system_error header

### ISSUE THREAD

**Issue by karen-arutyunov** [Homebrew/homebrew-core#48372]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] ran `brew update` and can still reproduce the problem?

Yes.

- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Yes.

- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
 % brew gist-logs gcc
Error: No logs.
```
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
% brew config
HOMEBREW_VERSION: 2.2.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 13f508d0dc8ada1726ee09a750285d7447ac3df4
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 38eddfa379c0b6d441917f1bf438d8f30d4f6a72
Core tap last commit: 16 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit penryn
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: 11.0.33.16
Xcode: N/A
% brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

I'm trying to compile with g++-9 a small program that reproduces the bug that prevents building ICU 65.1 (https://github.com/unicode-org/icu).

## What happened (include command output)

When the -D_XOPEN_SOURCE=600 option is added to the g++-9 command line, the compilation of a C++ program that includes the system_error header fails.

<details>
  <summary>Command output</summary>
  <pre>
In file included from /usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/system_error:39,
                 from test.cxx:1:
/usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/x86_64-apple-darwin19/bits/error_constants.h:135:24: error: 'EOWNERDEAD' was not declared in this scope
  135 |       owner_dead =     EOWNERDEAD,
      |                        ^~~~~~~~~~
/usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/x86_64-apple-darwin19/bits/error_constants.h:151:34: error: 'ENOTRECOVERABLE' was not declared in this scope
  151 |       state_not_recoverable =    ENOTRECOVERABLE,
      |                                  ^~~~~~~~~~~~~~~
  </pre>
</details>

## What you expected to happen

The compilation is expected to succeed.

## Step-by-step reproduction instructions (by running `brew install` commands)
```
% brew install gcc
% cat <<EOF >test.cxx
#include <system_error>

int main (int argc, char* argv[])
{
}
EOF
% g++-9 test.cxx
% g++-9 -D_XOPEN_SOURCE=600 test.cxx
In file included from /usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/system_error:39,
                 from test.cxx:1:
/usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/x86_64-apple-darwin19/bits/error_constants.h:135:24: error: 'EOWNERDEAD' was not declared in this scope
  135 |       owner_dead =     EOWNERDEAD,
      |                        ^~~~~~~~~~
/usr/local/Cellar/gcc/9.2.0_2/include/c++/9.2.0/x86_64-apple-darwin19/bits/error_constants.h:151:34: error: 'ENOTRECOVERABLE' was not declared in this scope
  151 |       state_not_recoverable =    ENOTRECOVERABLE,
      |                                  ^~~~~~~~~~~~~~~

```

**Comment by fxcoudert** [comment]
Please report this issue to GCC (http://gcc.gnu.org/bugzilla), it is a problem in the libstdc++ headers. It was also reported to MacPorts (https://trac.macports.org/ticket/58930), and it is not specific to the way Homebrew builds GCC.

The problem is that libstdc++ guards the use of `EOWNERDEAD` with `_GLIBCXX_HAVE_EOWNERDEAD`, which is a compile-time determined constant. But `EOWNERDEAD` availability is dependent on the value of `_XOPEN_SOURCE`.
