### ISSUE TITLE
wine won't install in Catalina 

### ISSUE THREAD

**Issue by ballo** [Homebrew/homebrew-core#48416]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Install wine
## What happened (include command output)
`➜  ~ brew install wine
Error: No available formula with the name "wine" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
twine-pypi                 winetricks                 winexe
To install one of them, run (for example):
  brew install twine-pypi
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.`

## What you expected to happen
This command used to install wine

## Step-by-step reproduction instructions (by running `brew install` commands)
Frech install of Catalina and brew, then try to install wine

**Comment by ballo** [comment]
I suppose this is due to 
https://github.com/Homebrew/homebrew-core/pull/46556

I guess I'll try building it

**Comment by iMichka** [comment]
The answer is given in https://github.com/Homebrew/homebrew-core/pull/46556#issuecomment-559938873.

> Help upstream fix the issues and submit the formula again. Or extract the formula into your own tap. But in it's current form wine has no place in homebrew-core.

So this is the current status.
