### ISSUE TITLE
GCC, GCC@8 can't create appropriate precompiled header

### ISSUE THREAD

**Issue by openingnow** [Homebrew/homebrew-core#48503]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

Produce same log for every cellar I installed. Maybe this is not directly linked with my problem I guess?
```
$ brew gist-logs gcc
Error: undefined method `length' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:145:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 2.2.2-50-gc0b9167
ORIGIN: https://github.com/Homebrew/brew
HEAD: c0b9167642e7db21ba68bc06205d3054a77d7fb7
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 455ceb70cdfd59ed0dd2b6c13d3498e973394232
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CASK_OPTS: --appdir=/Applications --fontdir=/Library/Fonts
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: 11.3.0.0.1.1574140115
Xcode: N/A

$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)
Precompile standard headers with GCC.

## What happened (include command output)
To reproduce bug, I installed gcc, gcc@8, gcc@7.
hello.hpp
```cpp
#include <iostream>
#include <regex>
#include <random>
```

hello.cpp
```cpp
#include "hello.hpp"

void say(std::string t)
{
	std::cout << t << std::endl;
}
```
gcc@7 produces precompiled header correctly and uses it.
```
$ g++-7 -c hello.hpp && g++-7 -c hello.cpp -H -Winvalid-pch
! hello.hpp.gch
 hello.cpp
```
`! hello.hpp.gch` means compiler uses this precompiled header file.
BTW, gcc@8 and gcc doesn't work as expected.

```
$ g++-8 -c hello.hpp && g++-8 -c hello.cpp -H -Winvalid-pch
hello.cpp:1:21: warning: hello.hpp.gch: had text segment at different address
 #include "hello.hpp"
                     ^
x hello.hpp.gch
. hello.hpp
.. /usr/local/Cellar/gcc@8/8.3.0_2/include/c++/8.3.0/iostream
... /usr/local/Cellar/gcc@8/8.3.0_2/include/c++/8.3.0/x86_64-apple-darwin19/bits/c++config.h
.... lots of header files/
````
`x hello.hpp.gch` means compiler doesn't uses this precompiled header file.

Same happens for g++-9.

When I run that command at gcc-9.2.0 at Arch, it works well like gcc@7 do.

**Comment by fxcoudert** [comment]
We didn't change the way we build GCC between 7 and 8, so this is probably not Homebrew-specific. I suggest you file a bug report against GCC so they can investigate the issue: https://gcc.gnu.org/bugzilla
