### ISSUE TITLE
Maintain multiple Qt versions

### ISSUE THREAD

**Issue by phoerious** [Homebrew/homebrew-core#48541]
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Qt has a history of only maintaining up to three versions of macOS, which requires that we stay on an older Qt version when building binaries for our application (KeePassXC).

Unfortunately, brew only maintains the newest release of Qt (5.14 right now). It would be nice if you could provide at least 5.13 (very buggy release) and 5.12 as well. Right now I always need to find the right Git commit in this repository to install an older version of the formula and a brew upgrade will reinstall the new upstream version again.

**Comment by fxcoudert** [comment]
As far as I can tell, Qt older versions do not satisfy our criteria for versioned formulas: https://docs.brew.sh/Versions
Namely, the older versions are not maintained over time (no security patches published once the next major version is released).

Probably the best solution for you is to maintain older Qt versions in a personal tap: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by phoerious** [comment]
Qt 5.12 is an LTS release that will be supported until 2021.

**Comment by fxcoudert** [comment]
That's good to know, and could be included if all criteria are fulfilled (please file a pull request). Note that we still wouldn't provide binaries (bottles) for macOS versions not supported by Apple, so there is no real advantage in your use case, compared to maintaining the formula in your own tap.
