### ISSUE TITLE
mpfr@2 formula has undefined error on macOS 10.15.2 (Catalina)

### ISSUE THREAD

**Issue by nickycutesc** [Homebrew/homebrew-core#48553]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to resolve a warning for the formula mpfr@2 when running 'brew doctor'. I was trying to debug a separate brew issue.

## What happened (include command output)

I ran 'brew doctor' and received the following output:

<details>
  <summary>Command output</summary>
  <pre>

  Warning: Some installed formulae are not readable:
  mpfr@2: undefined method `undent' for #<String:0x00007fd9aeafc1e0>

  </pre>
</details>

I then ran 'brew gist-logs mpfr@2' and received the following output:

<details>
  <summary>Command output</summary>
  <pre>

  Error: undefined method `length' for nil:NilClass

Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:145:in `gist_logs'   

/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `\<main>'

  </pre>
</details>

## What you expected to happen

I was expecting to receive more detailed fixes about the formula, such as 'run brew link' on the formula.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew doctor
brew gist-logs mpfr@2

gist link: https://gist.github.com/nickycutesc/1b35916974dfc37944e3ead766f812e2

**Comment by fxcoudert** [comment]
This formula was removed from Homebrew core on 24 January 2018. That it's still present on your system probably means you have local modifications of the Homebrew core tap, which you should fix.

If you want to get rid of all modifications and start over from a clean slate, do `brew update-reset`:

```
   update-reset [repository]
       Fetch  and  reset  Homebrew and all tap repositories (or any specified repository) using git(1) to their latest
       origin/master.

       Note: this will destroy all your uncommitted or committed changes.
```

**Comment by nickycutesc** [comment]
Ok, thanks!

**Comment by nickycutesc** [comment]
@fxcoudert how did you determine that the formula was removed from Homebrew? Is there a specific command and/or documentation listing removed formulas?

**Comment by nickycutesc** [comment]
@fxcoudert  ok, I figured it out. Is there a way to uninstall/remove removed formulas when they are removed?
