### ISSUE TITLE
mit-scheme march=native doesn't always work

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#486]
I saw this on a Skylake iMac where `--build-from-source` didn't work but `--build-bottle` did. The same workaround seems to have resolved the problem reported in #461, where the architecture was not Skylake, so it's a bit more widespread of an issue than I'd originally thought.

Although this is clearly an upstream bug, is there a preferred way to force `-march=core2` (or something else that solves the problem in another way) for a single formula until this is actually fixed?

**Comment by mikemcquaid** [comment]
> Although this is clearly an upstream bug, is there a preferred way to force -march=core2 (or something else that solves the problem in another way) for a single formula until this is actually fixed?

I'm not sure, I don't think there is, but this sounds like a good idea 👍

**Comment by ilovezfs** [comment]
@mikemcquaid this seems to do the trick: https://github.com/Homebrew/homebrew-x11/pull/202
