### ISSUE TITLE
Unable to install older rubies/gems

### ISSUE THREAD

**Issue by coding-bunny** [Homebrew/homebrew-core#48658]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing the `mysql2` gem on Ruby 2.3.1 for legacy projects that we still need to support.
This requires the openSSL 1.0 package in order to compile properly.

## What happened (include command output)

Basically compilation fails because HomeBrew now links automatically against the 1.1 version since it got removed  in the latest update.

<details>
  <summary>Command output</summary>
  <pre>

Installing mysql2 0.4.4 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/olivar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4/ext/mysql2
/Users/olivar/.rbenv/versions/2.3.1/bin/ruby -I /Users/olivar/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0 -r ./siteconf20200107-33176-jvjnhu.rb extconf.rb --with-mysql-dir\=/usr/local/Cellar/mysql/8.0.18_1
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Cannot find include dir(s) /usr/local/Cellar/mysql/8.0.18_1/include
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/Users/olivar/.rbenv/versions/2.3.1/bin/$(RUBY_BASE_NAME)
        --with-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/olivar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-19/2.3.0-static/mysql2-0.4.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/olivar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mysql2-0.4.4 for inspection.
Results logged to /Users/olivar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-19/2.3.0-static/mysql2-0.4.4/gem_make.out

An error occurred while installing mysql2 (0.4.4), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.4.4'` succeeds before bundling.

In Gemfile:
  mysql2

  </pre>
</details>

## What you expected to happen

To have an option to use openSSL 1.0, even if this is no longer maintained

## Step-by-step reproduction instructions (by running `brew install` commands)

There's a small work-around:

`bundler config build.mysql2 "--with-mysql-dir=$(brew --prefix mysql@5.6)"`

This will actually make the compilation work, since I had this installed with old openSSL, however this throws a lot of warnings when running commands. The core issue that we cannot "upgrade tools" to use the newer openSSL since this is legacy versions.

**Comment by SMillerDev** [comment]
> To have an option to use openSSL 1.0, even if this is no longer maintained

[Create a tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) and then [extract openssl 1.0 to it](https://docs.brew.sh/Manpage#extract-options-formula-tap). Other than this you're out of luck, homebrew only packages software that is supported by upstream, anything else would be plain irresponsible.
