### ISSUE TITLE
aws-okta package is broken

### ISSUE THREAD

**Issue by bazimov** [Homebrew/homebrew-core#48728]
When we install aws-okta with `brew install aws-okta` then running aws-okta giving error. Introduced in https://github.com/Homebrew/homebrew-core/commit/31868f8ff0b4d7aebe305c5acf7a5f28fa1103f0#diff-8987f2dd164c4087c93e950056dfccb4 
```
cannot execute binary file
```
Here aws-okta's own response to the issue.
https://github.com/segmentio/aws-okta/issues/267

**Comment by bayandin** [comment]
Look like another example of https://github.com/Homebrew/brew/issues/6539

Workaround by removing Catalina bottle
