### ISSUE TITLE
gcc: unable to complete the make process

### ISSUE THREAD

**Issue by ghostintheshellarise** [Homebrew/homebrew-core#4883]
While I was preparing my Macbook for the installation of Xgboost using

`brew install gcc --without-multilib`

 I encountered the below error message when my machine is running

`make bootstrap`

and following error message 

`Last 15 lines from /Users/SimonTse/Library/Logs/Homebrew/gcc/02.make:
tail: /Users/SimonTse/Library/Logs/Homebrew/gcc/02.make: No such file or directory`

**Comment by dunn** [comment]
Please follow the whole troubleshooting checklist, thanks! https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

**Comment by fxcoudert** [comment]
Issue has not been reported by any others, and gives no troubleshooting details. Could be closed?

**Comment by mtrevi** [comment]
@fxcoudert I had the same issue but with XCode Version 8.2.1 it seems fixed, I'm able to run `brew install gcc --without-multilib` without any problem.

**Comment by ilovezfs** [comment]
@ghostintheshellarise can you confirm this is fixed for you too now?

**Comment by fxcoudert** [comment]
I'm closing for now, please reopen with details if this still occurs.
