### ISSUE TITLE
proof-general should have a more recent release (upstream issue)

### ISSUE THREAD

**Issue by tchajed** [Homebrew/homebrew-core#4887]
As @zmwangx pointed out in #4853, Proof General should really release a new version since the latest release of 4.2 is from October 2012.

Tracking this here since we'll want to update Homebrew if and when a version is tagged.

**Comment by zmwangx** [comment]
To repeat myself,

> It seems that upstream is not referring to tarball downloads anywhere, and instead asking people to clone and install from git master branch. Could you please ask upstream whether they'll tag releases again? If not it will be a problem for us as packager.

Have you contacted upstream about this problem? Opening an issue here won't lead to any progress automatically unless there's someone contacting the upstream. We're a small team, so we have to rely on the contributions of actual users of upstream software — like you — to make things happen. Thanks.

**Comment by tchajed** [comment]
Officially reported as ProofGeneral/PG#109.

**Comment by zmwangx** [comment]
👍

**Comment by dunn** [comment]
4.4 is tagged and merged.
