### ISSUE TITLE
ssdb installed fail

### ISSUE THREAD

**Issue by hainuo** [Homebrew/homebrew-core#4898]
```
$  brew install ssdb                     
==> Using the sandbox
==> Downloading https://github.com/ideawu/ssdb/archive/1.9.2.tar.gz
==> Downloading from https://codeload.github.com/ideawu/ssdb/tar.gz/1.9.2

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ssdb"
Download failed: https://github.com/ideawu/ssdb/archive/1.9.2.tar.gz

```

**Comment by ilovezfs** [comment]
do you mind filing an issue upstream and asking what happened to the tag https://github.com/ideawu/ssdb/releases

**Comment by ilovezfs** [comment]
@zmwangx oy

```
<a class="btn btn-lg btn-success" href="https://github.com/ideawu/ssdb/archive/master.zip">
			<i class="glyphicon glyphicon-download"></i>
			Download <span style="font-size: 60%;">(1.9.3)</span>
		</a>
```
http://ssdb.io/

**Comment by zmwangx** [comment]
What's the problem, I love master. /s

**Comment by dunn** [comment]
https://github.com/ideawu/ssdb/issues/995

**Comment by dunn** [comment]
@zmwangx they do too: https://github.com/ideawu/ssdb/issues/995#issuecomment-252460768

**Comment by zmwangx** [comment]
Haha. Guess upstream needs to be taught how real people install and upgrade software, and how package managers work.

**Comment by zmwangx** [comment]
Or we can cut random dated releases for them. But "master is always stable" projects should cut courtesy releases; that's just the norm.

**Comment by dunn** [comment]
Well they retagged the current master as 1.9.2, so we can use that, and hope they do keep it up.

**Comment by zmwangx** [comment]
> hope they do keep it up

Doubt it, but I guess we can press them again when 1.9.2 breaks...

**Comment by zmwangx** [comment]
Fix in #5734.

**Comment by dunn** [comment]
You beat me!

**Comment by zmwangx** [comment]
Haha

**Comment by zmwangx** [comment]
Might be worth checking if I missed something.

**Comment by zmwangx** [comment]
🚢 'ed.
