### ISSUE TITLE
Current AWS CLI formula (awscli@1.17.0) requires updating to 1.17.3

### ISSUE THREAD

**Issue by davidjdixon** [Homebrew/homebrew-core#49095]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Since the current awscli package forces use of Python 3.8, it is getting caught out with a (recently fixed) bug due to use of incorrect syntax.

This can be determined by running pretty much any aws cli command. My own test scenario was using `aws sts assume-role`

## What happened (include command output)

Multiple error messages produced to stdout such as:
`/usr/local/Cellar/awscli/1.17.0/libexec/lib/python3.8/site-packages/jmespath/visitor.py:32: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is 0 or x is 1:`

## What is required to correct

The current version of the awscli is 1.17.3, which contains the fix for these syntax errors. I would raise a PR for this myself, but the fix appears so trivial it would likely be easier for a core dev (or someone more familiar with the Homebrew PR process) to raise rather than me trying to follow this as my first PR.

**Comment by issyl0** [comment]
Homebrew is only as good as its contributors make it. Making PRs for version bumps is trivial, as you say. We have the `brew bump-formula-pr` to automate the process - it takes seconds. We look forward to your first Homebrew PR, @davidjdixon! 💪

**Comment by davidjdixon** [comment]
I have no isssue at all with some suggesting performing a PR and being instructive in how to do so, the fact this issue was closed purely based on the fact it was not a PR is contemptible.

Let ignore the fact that such an issue follows a non trivial amount of assessment, research and trial and error to identify the root cause and that the contributor was working very late and wanted to do one last useful thing before leaving the office, but the fact that it does not also come with a few lines of code is enough to openly dismiss the issue raised.

This could have been handled by verifying the issue, and asking for a PR from the notifier or someone else with some additional time to look into it, but instead we get a self-rituous response that heavily indicates that contributions are only measured by code changes.

I would have expected such a reply 5 years ago for open source projects, but I’m surprised this attitude is still so pervasive. It’s a good job that the only users of open source projects are developers with an intimate knowledge of code changes and pull request processes... on no, wait...

**Comment by SMillerDev** [comment]
It’s a good job that the only users of open source projects are developers with an intimate knowledge of code changes and pull request processes... on no, wait...

If you would have looked up the command before getting on your high horse or even tried it you would have seen that barely any knowledge is needed. It's all done automatically. But don't worry, the couple of people managing tens of pull requests a day, every day, in their free time will also validate your issue for you and run a single command because you didn't feel you could run the command they offered.
