### ISSUE TITLE
Issues with python under macOS Catalina 10.15.2

### ISSUE THREAD

**Issue by souzapd** [Homebrew/homebrew-core#49140]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried to post-install the ```python``` formula on Homebrew 2.2.3-11-gdfe028a, under macOS Catalina 10.15.2.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew postinstall python 
==> Postinstalling python
==> /usr/local/Cellar/python/3.7.6_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.6_1/bin/python3 -s setup.py --no-user-cfg insta
Last 15 lines from /Users/David/Library/Logs/Homebrew/python/post_install.02.python3:
--no-user-cfg
install
--force
--verbose
--install-scripts=/usr/local/Cellar/python/3.7.6_1/bin
--install-lib=/usr/local/lib/python3.7/site-packages
--single-version-externally-managed
--record=installed.txt

running install
running build
running build_py
running install_lib
copying build/lib/pip/_internal/configuration.py -> /usr/local/lib/python3.7/site-packages/pip/_internal
error: could not delete '/usr/local/lib/python3.7/site-packages/pip/_internal/configuration.py': Permission denied
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`

  </pre>
</details>

## What you expected to happen

For the post-installation to be successful.

## Step-by-step reproduction instructions (by running `brew install` commands)

```brew update && brew upgrade```

**Comment by fxcoudert** [comment]
> - [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> - [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

There's a reason we are asking you to follow these steps… it's hard for us to debug without this information.

Also, what are the owner, group, and permission of `/usr/local/lib/python3.7/site-packages/pip/_internal/configuration.py` and its parents directories?
```
/usr/local/lib/python3.7/site-packages/pip/_internal/configuration.py
/usr/local/lib/python3.7/site-packages/pip/_internal
/usr/local/lib/python3.7/site-packages/pip
/usr/local/lib/python3.7/site-packages
/usr/local/lib/python3.7
/usr/local/lib
```

**Comment by souzapd** [comment]
> Also, what are the owner, group, and permission of ```/usr/local/lib/python3.7/site-packages/pip/_internal/configuration.py``` and its parents directories?

There you go:
[output.txt](https://github.com/Homebrew/homebrew-core/files/4081009/output.txt)


Couldn't run the ```gist-logs``` (because I haven't set up git on this computer). ```brew doctor``` doesn't point to anything wrong. This is the output for ```brew config```:

```
$ brew config            
HOMEBREW_VERSION: 2.2.3-11-gdfe028a
ORIGIN: https://github.com/Homebrew/brew
HEAD: dfe028a731e2ddb81bbe575d966c658b2177195c
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 97ea72c6388d35aa68a29a6c65522c838b17f2fc
Core tap last commit: 19 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.2-x86_64
CLT: 11.0.33.16
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11
```

**Comment by fxcoudert** [comment]
There should be nothing owned by `root`. That couldn't have happened by normal `brew` usage, since `brew` does not run with root privileges.

Fix the permissions so you own all the files, such as `sudo chown -R David /usr/local/lib`
