### ISSUE TITLE
Any `brew` command leads to the same error

### ISSUE THREAD

**Issue by MWYang** [Homebrew/homebrew-core#4925]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

I ran `brew update` like usual before seeing this; not sure if it's relevant: `Auto packing the repository in background for optimum performance.`

I then ran into two symlinking issues which I was able to resolve:
```
Error: Could not symlink bin/easy_install
Target /usr/local/bin/easy_install
already exists. You may want to remove it:
  rm '/usr/local/bin/easy_install'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python
```
and
```
Error: Could not symlink bin/easy_install-2.7
Target /usr/local/bin/easy_install-2.7
already exists. You may want to remove it:
  rm '/usr/local/bin/easy_install-2.7'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python
```
but this last one I haven't been able to get past:
```
Error: Could not symlink bin/ccache-swig
Target /usr/local/bin/ccache-swig
is a symlink belonging to swig. You can unlink it:
  brew unlink swig

To force the link and overwrite all conflicting files:
  brew link --overwrite swig304

To list all files that would be deleted:
  brew link --overwrite --dry-run swig304
```
It seems like any non `--help` invocation of `brew` will result in this, including `doctor`.

Thank you in advance!

**Comment by ilovezfs** [comment]
This is https://github.com/Homebrew/brew/issues/987. Please see that issue.
