### ISSUE TITLE
Homepage of rsense gives 404

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-core#4929]
The homepage for `rsense` (http://cx4a.org/software/rsense/) gives an HTTP 404.

The URL for the tarball is still fine though.

**Comment by zmwangx** [comment]
Time to boneyard I guess.

**Comment by rwhogg** [comment]
> Time to boneyard I guess.

cx4a.org still exists; maybe there's another page for rsense. Large chunks of it aren't in English, but maybe we could just use the Github repo if nothing else.

**Comment by rwhogg** [comment]
Ah:

https://github.com/m2ym/rsense:
> This project is closed.

Yeah, maybe it is.

**Comment by zmwangx** [comment]
> cx4a.org still exists

Yeah, Tomohiro Matsuyama is a quite famous developer actually, I know him mainly for Emacs auto-complete mode. But as you noticed the project is probably dead.

Care to submit a boneyard PR?

```
$ brew boneyard-formula-pr rsense
```

(I usually pass `--local` too.)

**Comment by zmwangx** [comment]
FWIW this formula is also unpopular: 153 installs since the beginning of analytics, 20 in the last month.
