### ISSUE TITLE
Different layout to Apache downloaded tar [Hadoop-3.2.1]

### ISSUE THREAD

**Issue by tallamjr** [Homebrew/homebrew-core#49356]
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to use Homebrew to install `hadoop` on a `macOS-10.15.2`.

## What happened (include command output)

`brew install hadoop` works fine and it installs in the expected place.

The main issue that was discovered is that the layout of the of the directory after extracting from the tarball is not the same as one would get it they were to install from downloaded version on one of the Apache Mirrors.

The knock-on effect is that documentation across the web is not consistent as it expects say `$HADOOP_COMMON_LIB_NATIVE_DIR` to exist at `$HADOOP_HOME/lib/native` but this directory is not "extracted" (as one example)

If we compare the directory layout (with `$ \ls`) we can see that for Homebrew we have:
```
11:37:38 ✘ /usr/local/Cellar/hadoop/3.2.1  ::

INSTALL_RECEIPT.json
LICENSE.txt
NOTICE.txt
README.txt
bin
libexec
sbin
```
..and for Apache Mirror download:
```
11:39:11 ✔ ~/bin/hadoop-3.2.1  ::

LICENSE.txt
NOTICE.txt
README.txt
bin
etc
include
lib
libexec
sbin
share
```

Note the extra `share`, `lib` and `etc` directories at the top level. These folders do exist (except for `lib`) lower in the tree but for consistancy, the extraction from the Apache Mirror tar should be the same as what is created by Homebrew.

I would like to try and edit this, I know there is an option `brew edit` but I'm very new to Ruby and quite confused about how I can address this.

Please do let me know if actually perhaps this is OK and I am just missing something subtle about getting it install in general

## What you expected to happen

I would expect `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hadoop.rb` to include the `lib` directory in `def install` command:
<details>
  <summary>`def install`</summary>
  <pre>

```
  def install
    rm_f Dir["bin/*.cmd", "sbin/*.cmd", "libexec/*.cmd", "etc/hadoop/*.cmd"]
    libexec.install %w[bin sbin libexec share etc]
    bin.write_exec_script Dir["#{libexec}/bin/*"]
    sbin.write_exec_script Dir["#{libexec}/sbin/*"]
    libexec.write_exec_script Dir["#{libexec}/libexec/*.sh"]
    # Temporary fix until https://github.com/Homebrew/brew/pull/4512 is fixed
    chmod 0755, Dir["#{libexec}/*.sh"]
  end

```
  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install hadoop && ls /usr/local/Cellar/hadoop/3.2.1/`

**Comment by SMillerDev** [comment]
If you think those directories are useful to the majority of people you can make a pull request. Just being consistent with the contents of a tarbal is not a good enough reason to change it though.

**Comment by tallamjr** [comment]
Fair enough, perhaps it does not warrant a change here. The inconsistency just means certain environment variables need to be changed compared to how they are laid out in the installation guides of [Hadoop](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html)

I would open a PR and continue the discussion but I have no idea where to start as I am completely unfamiliar with Ruby.

I'll close this for now.

**Comment by SMillerDev** [comment]
I'm mostly unfamiliar with ruby as well. Luckily the homebrew layer on top of it makes it pretty readable.
