### ISSUE TITLE
MySQL 8.0 default collation should be utf8mb4_0900_ai_ci

### ISSUE THREAD

**Issue by saveriomiroddi** [Homebrew/homebrew-core#49411]
The MySQL 8.0 formula compiles `utf8mb4_general_ci` as the [default collation](https://github.com/Homebrew/homebrew-core/blob/91f4df97adc4fcb9459b1a8dbd026c9fa1e45c31/Formula/mysql.rb#L46).

Such collation has been the MySQL 8.0 default before GA, however, on the GA release, it's been [changed to `utf8mb4_0900_ai_ci`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_collation_server).

The default collation should therefore be changed, as it can cause problems when connecting to an 8.0 server with the standard defaults.

**Comment by SMillerDev** [comment]
Gonna close this since there's a pull request.
