### ISSUE TITLE
hg-fast-export doesn’t install all the files

### ISSUE THREAD

**Issue by zagy** [Homebrew/homebrew-core#49424]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/zagy/90565c91ac808a1fdc9bb7eadfec6d81
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

converting ht repo to git.

## What happened (include command output)

```
$ hg-fast-export.sh -r /some/hg/repo
Traceback (most recent call last):
File “/usr/local/Cellar/hg-fast-export/190913/bin/hg-fast-export.py”, line 14, in 
import pluginloader
ImportError: No module named pluginloader
[…]
```

And indeed it’s not there in /usr/local/Cellar/hg-fast-export:
```
/usr/local/Cellar/hg-fast-export/190913
/usr/local/Cellar/hg-fast-export/190913/INSTALL_RECEIPT.json
/usr/local/Cellar/hg-fast-export/190913/bin
/usr/local/Cellar/hg-fast-export/190913/bin/hg-reset.py
/usr/local/Cellar/hg-fast-export/190913/bin/hg-fast-export.sh
/usr/local/Cellar/hg-fast-export/190913/bin/hg2git.pyc
/usr/local/Cellar/hg-fast-export/190913/bin/hg2git.py
/usr/local/Cellar/hg-fast-export/190913/bin/hg-reset.sh
/usr/local/Cellar/hg-fast-export/190913/bin/hg-fast-export.py
/usr/local/Cellar/hg-fast-export/190913/.brew
/usr/local/Cellar/hg-fast-export/190913/.brew/hg-fast-export.rb
/usr/local/Cellar/hg-fast-export/190913/README.md
```

## What you expected to happen

Converted repo, no error.

## Step-by-step reproduction instructions (by running `brew install` commands)

<pre>
jrrr ○  ➜  ~  brew install hg-fast-export
==> Downloading https://github.com/frej/fast-export/archive/v190913.tar.gz
Already downloaded: /Users/zagy/Library/Caches/Homebrew/downloads/417a41bf89c0a513ff2c3067ad9d3c14ca03a9cb6a61d543a15b3a77e7d803b1--fast-export-190913.tar.gz
🍺  /usr/local/Cellar/hg-fast-export/190913: 8 files, 49.1KB, built in 4 seconds

jrrr ○  ➜  ~  cd /tmp
jrrr ○  ➜  /tmp  mkdir hg-repo
jrrr ○  ➜  /tmp  cd hg-repo
jrrr ○  ➜  hg-repo  hg init
jrrr ☿   ➜  hg-repo  cd ..
jrrr ○  ➜  /tmp  mkdir git-repo
jrrr ○  ➜  /tmp  cd git-repo
jrrr ○  ➜  git-repo  git init
Initialized empty Git repository in /private/tmp/git-repo/.git/
jrrr ±  ➜  git-repo git:(master)  git config core.ignoreCase false
jrrr ±  ➜  git-repo git:(master)  hg-fast-export.sh -r ../hg-repo                                                                             /tmp/git-repo
Traceback (most recent call last):
  File "/usr/local/Cellar/hg-fast-export/190913/bin/hg-fast-export.py", line 14, in <module>
    import pluginloader
ImportError: No module named pluginloader
/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-fast-import statistics:
---------------------------------------------------------------------
Alloc'd objects:       5000
Total objects:            0 (         0 duplicates                  )
      blobs  :            0 (         0 duplicates          0 deltas of          0 attempts)
      trees  :            0 (         0 duplicates          0 deltas of          0 attempts)
      commits:            0 (         0 duplicates          0 deltas of          0 attempts)
      tags   :            0 (         0 duplicates          0 deltas of          0 attempts)
Total branches:           0 (         0 loads     )
      marks:           1024 (         0 unique    )
      atoms:              0
Memory total:          2360 KiB
       pools:          2048 KiB
     objects:           312 KiB
---------------------------------------------------------------------
pack_report: getpagesize()            =       4096
pack_report: core.packedGitWindowSize = 1073741824
pack_report: core.packedGitLimit      = 35184372088832
pack_report: pack_used_ctr            =          0
pack_report: pack_mmap_calls          =          0
pack_report: pack_open_windows        =          0 /          0
pack_report: pack_mapped              =          0 /          0
---------------------------------------------------------------------
</pre>

**Comment by SMillerDev** [comment]
I'm not entirely sure what you are trying to do (keep in mind that homebrew maintainers aren't using all tools homebrew ships)

> converting ht repo to git.

I have no idea what that is, or why homebrew has anything to do with it.

> Converted repo, no error.

I guess nobody wants errors but can you say a little more on what makes you think homebrew is doing things wrong here?

**Comment by zagy** [comment]
Sorry. `hg-fast-export` converts a local hg (mercurial) repository to git. The current install doesn't do that, because there are python files missing. It does an `import pluginloader in `hg-fast-export.py, line 14`, but the pluginloader isn't installed; hence the `ImportError`.

The pluginloader and other files are there in the upstream repo (https://github.com/frej/fast-export).

**Comment by alexreg** [comment]
I confirm that I'm also getting this.

(As a separate issue, it seems I have to use pip's mercurial installation rather than Homebrew's for this to work, but oh well.)

**Comment by bayandin** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/49977
