### ISSUE TITLE
instructions for apcupsd does not copy org.apcupsd.apcupsd.plist to the correct location

### ISSUE THREAD

**Issue by dmd** [Homebrew/homebrew-core#49458]
https://github.com/Homebrew/homebrew-core/blob/e4d7e3e28aaf7b6ec32e9a6b88008c5e28b52ead/Formula/apcupsd.rb#L74 

 

That file is actually located at `lib/Library/LaunchDaemons/org.apcupsd.apcupsd.plist`  (note the `lib`), so the instructions do not work.

**Comment by SMillerDev** [comment]
Could you make a pull request to fix it?

**Comment by dmd** [comment]
Thanks!
