### ISSUE TITLE
Adding MPI1 compatibility to open-mpi configure

### ISSUE THREAD

**Issue by marcosvanella** [Homebrew/homebrew-core#49514]
### Description of feature/enhancement

Would it be possible to add MPI1 backward compatibility to the open-mpi configuration? 
It would require adding the --enable-mpi1-compatibility flag on the configure flags of open mpi (args in homebrew-core/Formula/open-mpi.rb). This will maintain the capability to compile with mpi variables deprecated and removed on the latest open-mpi.
See for example:
https://github.com/open-mpi/ompi/issues/6114#issuecomment-446279495

### Justification

Trying to compile the Open-MPI wrapper for the Intel Math Kernel library on Mac OSX, with which one can use the MKL library with openmpi, requires this. The wrapper source code uses MPI_Address, which is one of the removed variables.

Thank you.

**Comment by SMillerDev** [comment]
Unless upstream recommends shipping with it or it's widely shipped on Linux I don't think this will happen. A better option might be to help fix projects that aren't up to date.

**Comment by marcosvanella** [comment]
Thank you Sean, I will get in touch with Intel compiler support and make them aware of this. This is not a problem using intel MPI, but they don't provide this library for Mac OSX.
