### ISSUE TITLE
Git usage output when running brew commands

### ISSUE THREAD

**Issue by tjsimmons** [Homebrew/homebrew-core#4955]
For the past two weeks or so, every time I run a brew command, I receive git usage output. The brew commands still work. Below is the output from `brew update`.

`~ tj@Njoror$ brew update
usage: git rev-parse --parseopt [<options>] -- [<args>...]

    --keep-dashdash       keep the `--` passed as an arg
    --stop-at-non-option  stop parsing after the first non-option argument
    --stuck-long          output in stuck long form

usage: git rev-parse --parseopt [<options>] -- [<args>...]

    --keep-dashdash       keep the `--` passed as an arg
    --stop-at-non-option  stop parsing after the first non-option argument
    --stuck-long          output in stuck long form

usage: git rev-parse --parseopt [<options>] -- [<args>...]

    --keep-dashdash       keep the `--` passed as an arg
    --stop-at-non-option  stop parsing after the first non-option argument
    --stuck-long          output in stuck long form

usage: git rev-parse --parseopt [<options>] -- [<args>...]

    --keep-dashdash       keep the `--` passed as an arg
    --stop-at-non-option  stop parsing after the first non-option argument
    --stuck-long          output in stuck long form

Already up-to-date.`

This isn't a breaking issue, but is still rather irritating. I've run brew update several times, reset the repo for the Aug10/11 issue. Attached are gists from brew config and brew doctor. The `brew doctor` output about XCode only popped up yesterday. The issue was occurring long before that.

`brew config` - https://gist.github.com/tjsimmons/dba283d52f80b9cb10842223714e3f57
`brew doctor` - https://gist.github.com/tjsimmons/84a9476888cf6815850db6459ee7c32f

**Comment by MikeMcQuaid** [comment]
Can I see a gist of your `brew update --debug --verbose --force` output? Thanks!

**Comment by tjsimmons** [comment]
Here it is.

https://gist.github.com/tjsimmons/7cabaf4582d829a938fd6e4002b6c365

**Comment by MikeMcQuaid** [comment]
It looks like this is coming from `git rebase`, weird. What's in your `~/.gitconfig`?

**Comment by tjsimmons** [comment]
https://gist.github.com/tjsimmons/5d0b71ac14e73f4b27680affab0347a0

**Comment by mjhoy** [comment]
Does `git rebase` work normally for you in git repositories?

(`git rebase` is, to my understanding, ultimately a shell script which makes calls out to `git rev-parse`. Perhaps it is somehow calling out to a different version of git than it expects.)

**Comment by tjsimmons** [comment]
I don't know, actually. I've always used Mercurial instead of git (although I did just convert all of my repositories to git).

**Comment by mjhoy** [comment]
Here's a quick way to test it out.

```sh
mkdir test-git-repo
cd test-git-repo
git init
touch foo
git add foo
git commit -m 'foo commit'
git branch other
touch bar
git add bar
git commit -m 'bar commit'
git checkout other
touch baz
git add baz
git commit -m 'baz commit'
git rebase master
```

Now `git-log` should give you something like,

```
$ git log --oneline
7073309 baz commit
6c22c03 bar commit
0b28165 foo commit
```

**Comment by notDavid** [comment]
I'm not sure if this is related, but i'm also seeing git output, i'll just post some logs in case it helps: https://gist.github.com/notDavid/ec6b9a44318d7d56047f2ef7b2183c2f#file-brew-config-log

**Comment by tjsimmons** [comment]
@mjhoy Just tested this.

`    testrep tj@Njoror$ git rebase master`
`usage: git rev-parse --parseopt [<options>] -- [<args>...]`

    --keep-dashdash       keep the `--` passed as an arg
    --stop-at-non-option  stop parsing after the first non-option argument
    --stuck-long          output in stuck long form

**Comment by mjhoy** [comment]
@tjsimmons weird. What does `which git` report? Also, `git --version`?

**Comment by tjsimmons** [comment]
`~ tj@Njoror$ which git`
`/usr/local/bin/git`
`~ tj@Njoror$ git --version`
`git version 2.10.0`

**Comment by mjhoy** [comment]
I assume you installed with homebrew? Try uninstalling/reinstalling it.

```sh
brew uninstall git
brew install git
```

**Comment by tjsimmons** [comment]
I had, yes @mjhoy. I think something just got messed up with my core brew installation - I haven't updated/upgraded in a few days (certainly before the 1.0 release!), and it still said brew was up-to-date when I ran it tonight.

I just completely removed homebrew, rebooted, and re-installed it. The issue seems to have been resolved.
