### ISSUE TITLE
nethack save directory is deleted during upgrade

### ISSUE THREAD

**Issue by timvisher** [Homebrew/homebrew-core#49571]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
    N/A
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
    https://gist.github.com/timvisher/fb5220c5b37ddbc29a7547093eb44548

## What you were trying to do (and why)

`brew upgrade nethack` without losing my save.

## What happened (include command output)

The upgrade went through but the save directory was deleted.

<details>
  <summary>Command output</summary>
  <pre>

$ brew upgrade nethack
Updating Homebrew...
==> Upgrading 1 outdated package:
nethack 3.6.4_1 -> 3.6.5
==> Upgrading nethack
==> Downloading https://homebrew.bintray.com/bottles/nethack-3.6.5.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d3/d3dd937be7a736b64c8f793aae2ac76e77d4e8cf60886a6decf06dd627d8ff19?__gda__=exp=15
######################################################################## 100.0%
==> Pouring nethack-3.6.5.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/nethack/3.6.5: 15 files, 8.5MB
Removing: /usr/local/Cellar/nethack/3.6.4_1... (16 files, 8.7MB)
==> Checking for dependents of upgraded formulae...
==> No dependents found!

  </pre>
</details>

## What you expected to happen

Upgrading nethack without losing libexec/save.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. brew install some prior version of nethack
2. Start and save a game.
3. `brew upgrade nethack`
4. See that the save directory was recreated and the save file is nowhere.

**Comment by jonchang** [comment]
How do Linux distributions handle this issue? Where are Nethack saves located on those distros?

**Comment by timvisher** [comment]
@jonchang I can't speak to everything but after a brief exploration of ubuntu it appears they store their saves in `/var/games/nethack/save`:

```
docker run -it --rm ubuntu:bionic
apt update && apt install nethack-console
play and save a game
ls /var/games/nethack/save/
```

But I guess more importantly can you help me understand what you're getting at? IIUC the issue is simply that during the upgrade the save directory is just overwritten which I believe that line is meant to prevent? If you upgrade nethack the binary but leave the save directory alone then, assuming save compatibility, things should just work.

**Comment by jonchang** [comment]
> If you upgrade nethack the binary but leave the save directory alone then, assuming save compatibility, things should just work.

Yes, that is pretty obviously the solution but in practice it’s unclear how to implement it for Homebrew as we link things into the user prefix from our Cellar, including the nethack playground. 

Nethack has its saves and data files relative to its playground (that’s `/var/games/nethack` above), but on upgrades we want to update the data files but not the saves. The easiest way would be to just copy those over into a folder in `share` but I’m not sure I like that solution as I’d prefer something that uses our homebrew links and doesn’t break things for current users of nethack who already have saves they’d like to keep.

**Comment by timvisher** [comment]
I have found something that looks oh so tantalizingly like a solution to this (although I wouldn't know the best way to express it in a formula). If you look at the [3.6.4 Guidebook](https://www.nethack.org/v364/Guidebook.html) and search for SAVEDIR you can see an advertised option for config files that is supposed to allow you to to modify the location create/read saved games (at least according to [the code_features.txt file](https://github.com/NetHack/NetHack/blob/NetHack-3.6/DEVEL/code_features.txt#L36-L79) and [this example config file](https://github.com/NetHack/NetHack/blob/9cd694740d7e34af081568098baeb407f0280d25/sys/share/NetHack.cnf#L89) in the 3.6 branch).

Unfortunately, when I set that in my `~/.nethackrc` file in my docker container `nethack-console` says it's a bad option:

```
root@a3d8095a2565:~# /usr/games/nethack
Bad option line: "SAVEDIR=/var/games/nethack_saves"
```

I'm trying to get some answer from #nethack@freenode but haven't heard back yet.

Would something simple like:

1. Making `libexec/save` a symlink to something outside of the update tree so that updates didn't overwrite it

1. Scripting a 'copy to saves to temp, do upgrade, copy saves back from temp' 

Work?

Also do I finally have this right that `skip_clean` doesn't have anything to do with installation/updating and instead has something to do with `cleaner.rb`?

**Comment by jonchang** [comment]
Thanks, that pointed me in the right direction. I've opened #50868 for this.

**Comment by timvisher** [comment]
Fantastic! I'd like to confirm it locally, if I can.

That should be as simple as:

1. Copy my saves somewhere in case it doesn't work.
1. `brew update`
1. `brew reinstall nethack`

Right?

**Comment by jonchang** [comment]
Yes

**Comment by timvisher** [comment]
This is fantastic. The only hiccup seems to be that the save is still _deleted_ on a reinstall if it had previously been installed using the old libexec `HACKDIR`.

But once the VARPLAYGROUND has been set to /usr/local/share/nethack and I do a reinstall it preserves my save. My LFDV is so happy. She was quaking in her `[oS` before despite having her `/oW` and her stack of `5 B?oGen`. xD
