### ISSUE TITLE
distcc is not stable and is too old

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#4958]
distcc 3.2rc1 is from 2011. There wasn't new releases since that date.
Last stable release is 3.1 from 2008.

**Comment by MikeMcQuaid** [comment]
That's something to talk to upstream about.

**Comment by yurikoles** [comment]
https://github.com/Homebrew/homebrew-core/pull/4953#issuecomment-247854177

**Comment by zmwangx** [comment]
Yeah, and I meant you (or someone) needs to talk to the upstream.

**Comment by TafThorne** [comment]
Upstream being the distcc project?  Everything is a bit quiet over there but I am trying to keep things chugging along where I can.  There was a 3.2 branch started but that seems to have slowed in May.  I will see if I can prompt/help people to get that finished off at least.  That would give a slightly more stable and much more recent revision for people to work on.  https://github.com/distcc/distcc/pull/178 is the place disucssing the 3.2 release as  far as I can see.

**Comment by MikeMcQuaid** [comment]
> Upstream being the distcc project?

Yep!

**Comment by TafThorne** [comment]
Thank you for confirming.  I will see what can be done in terms of 3.2 or something.
