### ISSUE TITLE
[404]Formulas that use Google Code hosting

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#4961]
- [ ] [distcc](../blob/master/Formula/distcc.rb) addressed in PR #4953
- [ ] [iphotoexport](../blob/master/Formula/iphotoexport.rb) 
- [ ] [jsdoc-toolkit](../blob/master/Formula/jsdoc-toolkit.rb)
- [ ]  [msktutil](../blob/master/Formula/msktutil.rb) PR #4963

**Comment by zmwangx** [comment]
#4280.
