### ISSUE TITLE
vim 8.2.150 segfaults with various plugins

### ISSUE THREAD

**Issue by gotcha** [Homebrew/homebrew-core#49641]
See https://github.com/vim/vim/issues/5541

The issue is fixed in 8.2.160. Would it be worth making a new release without waiting for 8.2.200 ?

**Comment by gotcha** [comment]
FTR, the plugins are not the culprits, Vim is.

**Comment by gotcha** [comment]
see comments on #49420

**Comment by iMichka** [comment]
Hi. Please try to fill out the issue template next time you open an issue.

You can open a pull request to update to 8.2.160. We try to bump only each 50 versions ... but as it is broken, we can just bypass that rule and get a new version out faster.
