### ISSUE TITLE
Installs numpy despite pip install

### ISSUE THREAD

**Issue by Jmuccigr** [Homebrew/homebrew-core#49646]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installed formula that required numpy.

## What happened (include command output)

The homebrew formulas insist on installing numpy, even though it's already installed via pip. (Obviously the brew install of numpy doesn't work given the  existing pip install.)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

I'd expect the formula to find numpy and not try to install it.

(I've seen #24396 which seems relevant and suggests that the formulas can't be made to check for pip's numpy.)

**Comment by jonchang** [comment]
Which formulae precisely do not use the brewed numpy?

**Comment by Jmuccigr** [comment]
I don't have brewed numpy. I have it installed via pip.

The formulae that require numpy are opencv and gdal2.

**Comment by SMillerDev** [comment]
Homebrew doesn't support depending on dependencies outside of the homebrew ecosystem. It introduces way more issues than it solves.

**Comment by Jmuccigr** [comment]
Thanks. This brew-vs-pip issue seems to be fairly common, based on my searching. I'll try to use brew instead of pip and see what happens.
