### ISSUE TITLE
[epic] camlp4 EOL

### ISSUE THREAD

**Issue by igas** [Homebrew/homebrew-core#49661]
[camlp4](https://github.com/ocaml/camlp4) has been discontinued and does not compile with latest ocaml anymore.

Formulas that depends on it:

- [x] coccinelle (146 installs - 365d) [#50756]
- [x] fstar (216 installs - 365d) [#49745]
- [x] lablgtk (430 installs - 365d) [#49670]
- [x] mldonkey (220 installs - 365d) [#49707]
- [x] neal (42 installs - 365d) [#50755]
- [x] zero-install (135 installs - 365d) [#50754]

**Comment by Bo98** [comment]
I looked at zero-install a couple months ago and just about fixed it. 0.15 is out now so I'll have a look again later this week.

**Comment by Bo98** [comment]
Sorted.
