### ISSUE TITLE
emacs: failed to build on 10.11.6

### ISSUE THREAD

**Issue by zarzen** [Homebrew/homebrew-core#4981]
Logs have been uploaded at [build log](https://gist.github.com/anonymous/681ebf7d86bacfd0b2eb0ef564f24708)

And I'm sure, I have installed xcode command line tools. C compiler works fine, because I can build emacs from source file.

**Comment by zmwangx** [comment]
Sorry to hear this, but we cannot provide support for external taps (because we have no control over the code)... Could you please report this to https://github.com/d12frosted/homebrew-emacs-plus/issues? Thanks.

**Comment by zarzen** [comment]
Actually, I have same issues with compile emacs from home-brew core taps.
This is the command I used: `brew install --with-cocoa --srgb emacs`

```configure: error: in `/private/tmp/emacs-20160920-15267-osf60f/emacs-25.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
```
The detail log is here: [log](https://gist.github.com/anonymous/d2e4abd33236357bd0890fea989d0719)

**Comment by zmwangx** [comment]
Rather than reopening this issue, could you please open a new issue for the core emacs problem?

**Comment by dunn** [comment]
The Xcode/CLT mismatch may be the issue:
```
macOS: 10.11.6-x86_64
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
```
Could you try downgrading Xcode to 7.3?

**Comment by dunn** [comment]
@zmwangx I just renamed the issue.

**Comment by zarzen** [comment]
@dunn Sure, I will try.
But why? I mean, why home-brew think system should use xcode7.3?

**Comment by ilovezfs** [comment]
that command is not correct.

```
brew install --with-cocoa --srgb emacs
```
srgb is the default and the option is `--without-librsvg`.

This is not reproducible on Xcode 8 + CLT 7.3.1* as far as I can tell.

**Comment by zmwangx** [comment]
> that command is not correct.

Yeah, but `--srgb` is ignored and won't cause real trouble.

I also can't reproduce fwiw.

**Comment by ilovezfs** [comment]
@zmwangx yes, just noting that it's irrelevant.

```
iMac-TMP:~ joe$ brew config|grep 'Xcode:\|CLT:'; xcode-select -p
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
/Applications/Xcode.app/Contents/Developer
iMac-TMP:~ joe$ brew instal --with-cocoa emacs
==> Using the sandbox
==> Downloading https://ftpmirror.gnu.org/emacs/emacs-25.1.tar.xz
Already downloaded: /Users/joe/Library/Caches/Homebrew/emacs-25.1.tar.xz
==> ./configure --disable-silent-rules --enable-locallisppath=/usr/local/share/emacs/site-lisp --info
==> make
==> make install
==> Caveats
Please try the Cask for a better-supported Cocoa version:
  brew cask install emacs

To have launchd start emacs now and restart at login:
  brew services start emacs
Or, if you don't want/need a background service you can just run:
  emacs

.app bundles were installed.
Run `brew linkapps emacs` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/emacs/25.1: 4,045 files, 119.4M, built in 1 minute 12 seconds
iMac-TMP:~ joe$ 
```

**Comment by ilovezfs** [comment]
```
checking whether the C compiler works... no
```

@zarzen what is the output of 
```
xcode-select -p
```

**Comment by zarzen** [comment]
@ilovezfs 
`brew config|grep 'Xcode:\|CLT:'; xcode-select -p` output:
```
Xcode: 8.0
CLT: 7.3.1.0.1.1461711523
```
` xcode-select -p` output:
```
/Library/Developer/CommandLineTools
```

**Comment by ilovezfs** [comment]
Yup, that's the cause. See https://github.com/Homebrew/brew/pull/1001#issuecomment-247840168.

Assuming your Xcode is /Applications/Xcode.app, you can fix it by running
```
sudo xcode-select -r
```

**Comment by zarzen** [comment]
It works!
@ilovezfs Thanks!

**Comment by ilovezfs** [comment]
@zarzen no problem :)
