### ISSUE TITLE
Generate formulae.brew.sh data process is broken

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#49840]
Broken since the latest node-build PR merge, https://github.com/Homebrew/homebrew-core/runs/428749667

```
brew formula-analytics  --days-ago=365 --json --os-version > _data/analytics/os-version/365d.json
brew formula-analytics  --days-ago=30 --json --all-core-formulae-json --build-error > _data/analytics/build-error/homebrew-core/30d.json
Error: Options --json and --all-core-formulae-json are mutually exclusive.
rake aborted!
```

**Comment by issyl0** [comment]
The `brew formula-analytics` command was switched to use `CLI::Parser` in https://github.com/Homebrew/homebrew-formula-analytics/pull/129.

**Comment by issyl0** [comment]
Ah, this issue spans three repos! Fixing now in [https://github.com/Homebrew/formulae.brew.sh/pull/244.
