### ISSUE TITLE
mysql8.0.19 provides system-wide libssl.1.1.dylib leading to incompatibilities w/ unrelated software

### ISSUE THREAD

**Issue by Achimh3011** [Homebrew/homebrew-core#49915]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
Did not work.
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

> brew config
HOMEBREW_VERSION: 2.2.5-28-gb8c2e96
ORIGIN: https://github.com/Homebrew/brew
HEAD: b8c2e96ee6390803df7bbbc39e66d400b8ebcf52
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1252f760fe029bcafb6025bd4b3835a8dfe00264
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2, 11.0.6, 1.8.0_242, 1.8.0_181, 1.8.0_131, 1.8.0_102, 1.8.0_20, 1.7.0_67
macOS: 10.15.3-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

## What you were trying to do (and why)

I tried to run the SynologyDrive.app from Synology and it wouldn't start.

## What happened (include command output)

Logs indicated problems with SSL. When I ran the main program of the package manually with

    DYLD_PRINT_LIBRARIES=YES $HOME/.SynologyDrive/SynologyDrive.app/Contents/MacOS/cloud-drive-ui

I found that it picked up `/usr/local/lib/libssl.1.1.dylib`, which is a symlink to `../Cellar/mysql/8.0.19/lib/libssl.1.1.dylib`.

## What you expected to happen

mysql formula should not install a system-wide libssl, even more so when the openssl package installs its libs keg-only.

## Step-by-step reproduction instructions (by running `brew install` commands)

    brew install mysql
    # install SynologyDrive from https://global.download.synology.com/download/Tools/SynologyDriveClient/2.0.1-11061/Mac/Installer/synology-drive-client-11061.dmg
    open $HOME/.SynologyDrive/SynologyDrive.app

SynologyDrive will fail to start.

**Comment by MikeMcQuaid** [comment]
> SynologyDrive will fail to start.

This is an issue with SynologyDrive and not Homebrew. If `mysql` can be convinced to not install that library in that location and still function: we'll review a PR. Thanks!

**Comment by Achimh3011** [comment]
The symptom is a third-party app failing, but the issue is a homebrew app poisoning a common library directory. So far I had assumed that homebrew cared about such side effects.

**Comment by SMillerDev** [comment]
Homebrew cares about being useful but if the only thing failing is something that homebrew doesn't ship, then it's hardly a homebrew issue.

**Comment by MikeMcQuaid** [comment]
@Achimh3011 We care enough to review and probably merge a pull request. Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by Achimh3011** [comment]
I can try to prepare a pull request, I already considered that when opening the issue. 

It feels a bit counterintuitive that the issue needs to be closed for it and even expect that other projects would not welcome a PR on a closed issue, but if it is different here, then be it so.

**Comment by MikeMcQuaid** [comment]
> It feels a bit counterintuitive that the issue needs to be closed for it and even expect that other projects would not welcome a PR on a closed issue, but if it is different here, then be it so.

Thanks. I appreciate we run our issue tracker a bit differently and that's sometimes confusing. Open issues are broadly "maintainers plan on working on this and/or we're actively soliciting help on a well-scoped, solvable issue".
