### ISSUE TITLE
brew install phplint SSL certificate problem

### ISSUE THREAD

**Issue by andytriboletti** [Homebrew/homebrew-core#49920]
- [ ] ran `brew update` and can still reproduce the problem?
yes

- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
brew gist-logs phplint
Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
brew config
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e6c5f7c9e296f7b749e2d18369315e660de3428f
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_77, 1.7.0_79
macOS: 10.15.3-x86_64
CLT: 11.0.33.5
Xcode: 11.3.1

## What you were trying to do (and why)
brew install phplint

I am trying to cleanup my php code.

## What happened (include command output)

It failed because of an ssl error.

<details>
  <summary>Command output</summary>
  <pre>
brew install phplint  
==> Downloading https://www.icosaedro.it/phplint/phplint-4.0_20190206.tar.gz
curl: (60) SSL certificate problem: unable to get local issuer certificate    
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "phplint"
Download failed: https://www.icosaedro.it/phplint/phplint-4.0_20190206.tar.gz

  </pre>
</details>

## What you expected to happen

brew install phplint should install phplint

**Comment by SMillerDev** [comment]
You should try and fix the issues in brew doctor and report this issue to the phplint developers if it persists after that. This isn't specific to homebrew.

**Comment by andytriboletti** [comment]
Thank you.
