### ISSUE TITLE
Ant now requires that I specify JAVA_HOME if openjdk is not installed

### ISSUE THREAD

**Issue by rhwood** [Homebrew/homebrew-core#49959]
Prior to #46437, ant ran with the user-selected and installed Java (i.e. the Java found when using `java` at the command line, but since then, that java cannot be used without specifying JAVA_HOME.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run ant using the macOS default Java because I installed the Java version (AdoptOpenJDK 11) that I need to use.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
% ant               
We cannot run Java, please ensure you have Java installed.
  We have tried to execute /usr/local/opt/openjdk/bin/java but failed.
If you have installed Java in a unusual place you can set JAVA_HOME
to the directory containing the Java installation.
  </pre>
</details>

## What you expected to happen

ant to run without the above error.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install ant && brew uninstall --ignore-dependencies openjdk`

**Comment by rhwood** [comment]
This occurs with the maven and spotbugs casks as well, and maybe others. I have one (1) JVM that I installed and wish to use, but am somewhat surprised that homebrew is now:
1. installing JDKs that are "keg only"
2. not deferring first to the java on the user's path

**Comment by SMillerDev** [comment]
> installing JDKs that are "keg only"

All software that has a version of it on macOS is keg only. See openssl for example, it would break a lot of people's system outside of homebrew software otherwise.

> not deferring first to the java on the user's path

The only reason homebrew software ever used a non-brewed Java was because Java is quite difficult to compile and nobody bothered yet. Outside of conventions like `JAVA_HOME` homebrew will always use a homebrew version of software if it's available.

**Comment by rhwood** [comment]
ant Installed by homebrew worked as expected a week ago, but I can’t find any discussion of the desirability of this change other than to note that this PR was months ago marked “do not merge” and then recently merged anyway.

**Comment by MikeMcQuaid** [comment]
> brew uninstall --ignore-dependencies openjdk

It is expected behaviour that applications will not work when you uninstall their dependencies.

**Comment by rhwood** [comment]
This then leads to another question: why was the ant launcher from upstream completely rewritten to require a specific java and not the java on the classpath? You have basically forced (unannounced) a new dependency that wasn’t needed previously.

**Comment by rhwood** [comment]
I should have mentioned; I specifically want to use the openjdk@11 (and only the openjdk@11) homebrew package as a dependency; requiring that I use the specifically (per upstream) not to be supported for more than 6 months version is somewhat bothersome.

**Comment by SMillerDev** [comment]
Yes, you have to specify `JAVA_HOME` or use the Java version that homebrew points to. Which in ants case will be the latest one.

**Comment by MikeMcQuaid** [comment]
> You have basically forced (unannounced) a new dependency that wasn’t needed previously

Yes. This is par for the course when using a package manager.
