### ISSUE TITLE
ansible not finding pyrax

### ISSUE THREAD

**Issue by adejongh** [Homebrew/homebrew-core#5003]
Ok - so this was working until Saturday night as I was using the ansible rackspace modules to configure infrastructure on rackspace.  I.e. it could find the pyrax module.  Trust me, I've run it 1000s of times.

Earlier today I uninstalled ansible using brew, and reinstalled it - I did this because there was parts of an older version of ansible (2.1.0.0) still lurking in the Cellar/ansible folder.  I also uninstalled docker and docker-engine.  After I did this ansible now suddenly cannot find the pyrax module.  Now I don't understand how this worked before since it appears Ansible is running /usr/bin/python - *but it did*.  Also I don't have pyrax installed anywhere else using pip either.

My question is - why is pyrax even bundled with ansible in the /usr/local/Cellar/ansible/2.1.1.0/libexec/lib/python2.7/site-packages if ansible can't find it?  Somehow this must have worked before as well.  Any thoughts?

**Comment by zmwangx** [comment]
Sorry to hear this, but could you please be a little bit more specific than "ansible not finding pyrax"? What exact error messages did you see?

> Earlier today I uninstalled ansible using brew, and reinstalled it - I did this because there was parts of an older version of ansible (2.1.0.0) still lurking in the Cellar/ansible folder. 

Old versions in cellar shouldn't matter and you can always `brew cleanup ansible` or even manually blow away `/usr/local/Cellar/ansible/<whatever-old-version>`. No uninstall and reinstall needed.

For mission critical stuff you probably want to make sure the new version works before blowing away the old keg. If the new version doesn't work and you still have a working old keg you could always

```
brew switch ansible 2.1.0.0
```

**Comment by adejongh** [comment]
To clarify - I am running a playbook with Ansible that configures rackspace.  To do this the "ansible_connection=local" is set in my inventory as to execute the tasks locally on the control host (the mac).  I then get this error:
fatal: [dev]: FAILED! => {"changed": false, "failed": true, "msg": "pyrax is required for this module"}

I.e. the same as the 100s of other posts where there is confusion as to what python is in use and Ansible can't find pyrax.  Now there are lots of advice on how to fix this - e.g. by adding python_interpreter to the host config in the inventory.

The confusing part is that this had worked, and then stopped.  I can see pyrax is packaged with the brew Ansible install - but apparently not found?  Hence my question on why it is even packaged?

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for thoughts.

**Comment by tdsmith** [comment]
What happens when you run `$(brew --prefix ansible)/libexec/bin/python -c 'import pyrax'`?

**Comment by adejongh** [comment]
$(brew --prefix ansible)/libexec/bin/python -c 'import pyrax'
/usr/local/opt/ansible/libexec/lib/python2.7/site-packages/novaclient/client.py:830: UserWarning: 'get_client_class' is deprecated. Please use `novaclient.client.Client` instead.
  warnings.warn(_LW("'get_client_class' is deprecated. "

Not sure why I am getting that, but in any case.

**Comment by zmwangx** [comment]
That's just a `UserWarning`, `pyrax` is importing fine.

**Comment by adejongh** [comment]
I think the problem lies with the fact that ansible starts up with its own embedded python, but with ansible_connection=local it starts using /usr/bin/python to execute tasks.  Not sure why.  The system python obviously has no idea of what pyrax is.

The bizarre bit is that this exact playbook was working happily, so something must have changed.

**Comment by tdsmith** [comment]
Yes; we started using virtualenv encapsulation instead of setting PYTHONPATH, which solved some tricky problems layering ansible and python3, but will cause problems if you were expecting child processes to find the bundled site-packages by inheriting the environment. This is the first thing I've heard that we've broken since we made the change a couple weeks ago; I was expecting more fireworks!

You should try `pip install --user pyrax` if you want /usr/bin/python to be able to find the pyrax module; if you can find a way to use `sys.executable` as the subprocess interpreter that should work, too.

**Comment by adejongh** [comment]
What exactly did the change entail?  Maybe it will help me understand what changed, and where.

I am still baffled how this could have worked before?  Just thinking this will be super confusing to users.

**Comment by zmwangx** [comment]
In case Tim wasn't clear enough, previously when you run `ansible` you were running a system-wide Python with brew paths injected into `PYTHONPATH`. This will be clear if we look at a formula that hasn't been migrated to use `virtualenv_install_with_resources`, e.g. `grip`.

```
$ brew install grip
$ cat /usr/local/Cellar/grip/4.3.2/bin/grip
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/grip/4.3.2/libexec/lib/python3.5/site-packages:/usr/local/Cellar/grip/4.3.2/libexec/vendor/lib/python3.5/site-packages" exec "/usr/local/Cellar/grip/4.3.2/libexec/bin/grip" "$@"
```

Then in `/usr/local/Cellar/grip/4.3.2/libexec/bin/grip`:

```
$ head -1 /usr/local/Cellar/grip/4.3.2/libexec/bin/grip
#!/usr/local/opt/python3/bin/python3.5
```

See, that's system-wide.

As for virtualenv encapsulation, what we're installing with brew nowadays is almost (not quite, because we make a `libexec` separation, but that's not important for the purpose of understanding what we do) what you would get with

```
$ virtualenv venv
$ . venv/bin/activate
$ pip install ansible
$ PATH=$PWD/venv/bin:$PATH
```

Now when you run `ansible`, it's using a Python within `venv`:

```
$ head -1 venv/bin/ansible
#!/Volumes/ramdisk/venv/bin/python3.5
```

Or in the case of ansible installed with brew:

```
$ head -1 /usr/local/bin/ansible
#!/usr/local/Cellar/ansible/2.1.1.0/libexec/bin/python
```

That Python have the correct module search paths baked in, but that's not true for `/usr/bin/python`.

**Comment by adejongh** [comment]
I understand.  This, however, is a departure from how it worked before.  It is strange no-one else had issues with this?

Do you have the commits / pull requests / issues for this somewhere?  Thanks for the quick responses!

**Comment by zmwangx** [comment]
> Do you have the commits / pull requests / issues for this somewhere?

Not sure what you mean by this, everything is on GitHub of course...

**Comment by adejongh** [comment]
Yeah - instead of me searching through all the commits, I was hoping you could point me in the direction of the change.

**Comment by adejongh** [comment]
Ok, so finding it wasn't too hard sorry:  https://github.com/Homebrew/homebrew-core/pull/4471

**Comment by adejongh** [comment]
Hmm - I wonder if it would not have been better to add a note with the formula to say that this had changed.  It took me a bit of time to figure out I had to use the PYTHONPATH to fix python not finding pyrax.  And to figure out Ansible was using /usr/bin/python etc. - just a lot of time that will wasted collectively.

**Comment by dunn** [comment]
Is there anything actionable here?  Otherwise I'll go ahead and close this issue.

**Comment by adejongh** [comment]
A closing comment from my side would be that it would have been better to make this formula change with a newer version of Ansible, instead of updating an existing version.  I am not sure if this is possible with brew, but it would have been much less "surprising" if a working install behaves different on a reinstall.  Thanks for all the responses - it did help me understand an resolve the problem on my end.
