### ISSUE TITLE
lcov 1.14 cannot read gcov files from gcc 9.2.0  

### ISSUE THREAD

**Issue by zackw** [Homebrew/homebrew-core#50043]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?  
  *(I can't do this, I do not have shell access to the machine where the problem is, it's a Travis CI build worker.  However, the problem is due to a known upstream bug, see below for further explanation.)*
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?  
  *(see above)*
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  *(see above)*

## What you were trying to do (and why)

I was trying to build a piece of software on Travis CI's OSX build workers, using Homebrew's default GCC (which is currently 9.2.0), and then use `lcov` (also from Homebrew, version 1.14) to package up coverage results from the testsuite.  Coverage processing fails, because Homebrew's `lcov` 1.14 cannot process the `.gcda` and `.gcno` files produced by the `gcov` utility from GCC 9.2.0.

This is a known upstream bug in lcov: https://github.com/linux-test-project/lcov/issues/58  It has been fixed already by these two commits:
 - https://github.com/linux-test-project/lcov/commit/ebfeb3e179e450c69c3532f98cd5ea1fbf6ccba7
 - https://github.com/linux-test-project/lcov/commit/75fbae1cfc5027f818a0bb865bf6f96fab3202da

but those patches have not yet made it into a release.

I can't figure out if formulae are capable of applying patches to a package's source code.  If they can, it would be nice to add those two commits to the Homebrew package of lcov.

## What happened (include command output)

The following is an excerpt from https://travis-ci.org/besser82/libxcrypt/jobs/649043763

<details>
  <summary>Command output</summary>
  <pre>
$ rvm $brew_ruby do brew bundle --verbose --global
/usr/local/bin/brew tap homebrew/bundle
==> Tapping homebrew/bundle
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-bundle'...
Tapped 1 command (101 files, 255.7KB).
Skipping install of autoconf formula. It is already up-to-date.
Using autoconf
Skipping install of automake formula. It is already up-to-date.
Using automake
Skipping install of gcc formula. It is already up-to-date.
Using gcc
Installing lcov formula. It is not currently installed.
==> Downloading https://homebrew.bintray.com/bottles/lcov-1.14.high_sierra.bottle.tar.gz
==> Pouring lcov-1.14.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/lcov/1.14: 17 files, 566.9KB
[...]
gcov-9 is /usr/local/bin/gcov-9
+lcov --gcov-tool gcov-9 --directory . --capture --output-file all_coverage.info
Capturing coverage data from .
Found gcov version: 9.2.0
Scanning . for .gcda files ...
geninfo: WARNING: /Users/travis/build/besser82/libxcrypt/build/lib/libcrypt_la-alg-des.gcno: Overlong record at end of file!
Found 69 data files in .
Processing lib/libcrypt_la-alg-des.gcda
geninfo: WARNING: cannot find an entry for alg-des.c##18b2c852c0edeffadf6cc9e0c9c509e2.gcov in .gcno file, skipping file!
geninfo: WARNING: cannot find an entry for byteorder.h##ae93dab466d845fca9fc8a160120b720.gcov in .gcno file, skipping file!
geninfo: WARNING: /Users/travis/build/besser82/libxcrypt/build/lib/libcrypt_la-alg-gost3411-2012-core.gcno: Overlong record at end of file!
Processing lib/libcrypt_la-alg-gost3411-2012-core.gcda
  </pre>
</details>

## What you expected to happen

The command

    lcov --gcov-tool gcov-9 --directory . --capture --output-file all_coverage.info

should not throw errors.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gcc lcov
cat > hello.c <<\EOF
#include <stdio.h>
int main(void)
{
    puts("hello world");
    return 0;
}
EOF
gcc-9 -g -O2 --coverage -o hello hello.c
./hello
lcov --gcov-tool gcov-9 --directory . --capture --output-file all_coverage.info
```

**Comment by SMillerDev** [comment]
Patches are able to be applied in formulae but the better way is to request a release from upstream.

**Comment by bayandin** [comment]
I have asked regarding the next release in https://github.com/linux-test-project/lcov/issues/58#issuecomment-585381245

At the same time, I've prepared a PR with patches and some improvements in installation/test processes: https://github.com/Homebrew/homebrew-core/pull/50070

**Comment by bayandin** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/50070
