### ISSUE TITLE
Qt5 is outdated

### ISSUE THREAD

**Issue by mjdev** [Homebrew/homebrew-core#5004]
Hey guys,

Qt 5.7 is out since June, why is the Qt5 formula still on 5.6.x?

Thanks,
Magnus

**Comment by mistydemeo** [comment]
See #2087 for discussion - we looked into it. There were compatibility issues with OS X 10.9 which are resolved in 5.7.1, so we're waiting for that release.

**Comment by mjdev** [comment]
I see, thank you!
