### ISSUE TITLE
awscli is moving to a cask

### ISSUE THREAD

**Issue by lazzurs** [Homebrew/homebrew-core#50057]
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [*] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The package awscli has moved to version 2 which is distributed as a macOS pkg rather than a python package. The macOS package also includes all the dependencies that the awscli needs.

Pull request for the cask homebrew/homebrew-cask#76967 and for the formula homebrew/homebrew-core#50056

**Comment by vitorgalvao** [comment]
“is moving to a cask” is inaccurate; we’re still discussing it. There’s no need to open both an issue and a PR; the latter suffices for the discussion.

**Comment by lazzurs** [comment]
I will close this issue and leave the two pull requests open.
