### ISSUE TITLE
libwebsockets should be built with -DLWS_WITH_DISTRO_REOMMENDED

### ISSUE THREAD

**Issue by PerBothner** [Homebrew/homebrew-core#50074]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
(`Error: no logs.`)
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

    HOMEBREW_VERSION: 2.2.5
    ORIGIN: https://github.com/Homebrew/brew
    HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
    Last commit: 10 days ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: 57524a9b4d1c4b883b01e743fb6ae01225c21cec
    Core tap last commit: 2 hours ago
    HOMEBREW_PREFIX: /usr/local
    CPU: quad-core 64-bit broadwell
    Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
   Clang: 11.0 build 1100
    Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
    Curl: 7.64.1 => /usr/bin/curl
    macOS: 10.15.3-x86_64
    CLT: 11.3.1.0.1.1576735732
    Xcode: N/A

## What you were trying to do (and why)

I am trying to build [DomTerm](https://domterm/org) with default options.  This builds "resources' (JavaScript files etc) in a zip/jar file that libwebsockets can server directly without uncompressing them - but only if libwebsockets has been built with `LWS_WITH_ZIP_FOPS`.

Note the `libwebsockets/READMEs/README.build.md` recommends that distro packagers (which I think includes Homebrew) should set `LWS_WITH_DISTRO_RECOMMENDED` - which implicitly sets `LWS_WITH_ZIP_FOPS`.

## What happened (include command output)

The build of DomTerm fails.  (I can get it to work if I configure DomTerm with an extra option.)

## What you expected to happen

The build completes.

## Step-by-step reproduction instructions (by running `brew install` commands)

You can see the problem in https://github.com/Homebrew/homebrew-core/blob/master/Formula/libwebsockets.rb

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!

**Comment by PerBothner** [comment]
One conflict I noticed: `LWS_WITH_LIBEVENT` is enabled by the current formula, while `LWS_WITH_DISTRO_RECOMMENDED` enables `LWS_WITH_LIBEV` and disables `LWS_WITH_LIBEVENT` with the comment (see CMakeLists.txt):

    # libev + libevent cannot coexist at build-time

I don't know either libevent or libev, nor their respective advantages or otherwise.  I can ask the libwebsockets maintainer for an opinion, but presumably the formula creater has a reason for chosing libevent rather than libev.

**Comment by MikeMcQuaid** [comment]
You can try to submit a PR and if it breaks stuff it will show up in CI.
