### ISSUE TITLE
Pgloader should not depend on postgresql formula, or should respect version-locked formula

### ISSUE THREAD

**Issue by jasonab** [Homebrew/homebrew-core#50076]
## What you were trying to do (and why)

Install pgloader

## What happened (include command output)

postgresql formula installed along with pgloader

## What you expected to happen

I already have postgresql@11 installed, I did not expect a parallel version to be installed

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install pgloader

Note that it is not necessary to have a local install of postgresql installed to run pgloader. The Debian version does not have this dependency.

**Comment by MikeMcQuaid** [comment]
> postgresql formula installed along with pgloader

This is expected as it has a dependency.

> Note that it is not necessary to have a local install of postgresql installed to run pgloader. The Debian version does not have this dependency.

It is needed at build-time so it has the dependency. You can ignore the parallel version: it is not harming you.
