### ISSUE TITLE
Brew fails to find /usr/local/Library/Homebrew/brew.rb during auto update

### ISSUE THREAD

**Issue by zcourts** [Homebrew/homebrew-core#5009]
See the attached output.
[brew-update-error.txt](https://github.com/Homebrew/homebrew-core/files/481720/brew-update-error.txt)

It continues to work fine but thought i'd report it in case it was meant to do something important that I just haven't stumbled across yet but `brew install|update|doctor` worked after.

**Comment by ilovezfs** [comment]
@zcourts Please report in https://github.com/Homebrew/brew/issues/987.
