### ISSUE TITLE
formulae syncthing: plist created with log file path not writable by other users

### ISSUE THREAD

**Issue by MasinAD** [Homebrew/homebrew-core#50119]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
secuinfra@SI-C001:/Users/masin % brew update
Already up-to-date.
secuinfra@SI-C001:/Users/masin % brew doctor
Your system is ready to brew.
secuinfra@SI-C001:/Users/masin % brew gist-logs syncthing
Error: No logs.
secuinfra@SI-C001:/Users/masin % brew config
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e9746a2d19c4ef99733beb17d2c2d7a905563e42
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.0.33.17
Xcode: N/A
secuinfra@SI-C001:/Users/masin % brew doctor
Your system is ready to brew.
secuinfra@SI-C001:/Users/masin %
```

## What you were trying to do (and why)
Using an administrative account to brew the syncthing formulae. Using the result with another user.

## What happened (include command output)
Starting syncthing in terminal works. Starting as service fails with error 78.

## What you expected to happen
I expected to simply use the generated plist without caring for stuff like read and write permissions.

## Step-by-step reproduction instructions (by running `brew install` commands)
1.  Have two accounts, one adminstrative and one without administrative rights.
2. Brew formulae with your administrative account, e.g. using `su admin` and then `brew install syncthing`
3. (optional) `brew link syncthing`. I don't know if I did this before.
3. Start service as regular user using `launchctl load Library/LaunchAgents/homebrew.mxcl.syncthing.plist`. Alternatively `brew services start syncthing`.
4. Watch happening nothing!

I investigated using LaunchControl which showed me that the StandardErrorPath and StandardOutPath were not writable by the service. After commenting out the respective lines, the service started.

## What I didn't do
I did not uninstall the formulae.

I cannot remember if I ever used `brew services start syncthing` before, and when which I account I used.

Also, I'm new to macOS and Homebrew, so I don't understand the workings of both yet. :-)

## Proposed solution
Make homebrew services log into .local path in user's home directory.

**Comment by SMillerDev** [comment]
You ran brew services with the other user before. These paths are suggested by the developers of the tools and we're going to stick to them. If you're using a multi user setup you'll just have to be careful who the owner of the log directory is.
