### ISSUE TITLE
arangodb: checksum mismatch

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/homebrew-core#50113]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Build bottle for `arangodb` for linux.

## What happened (include command output)

Checksum mismatch error.

<details>
  <summary>Command output</summary>
  <pre>

  ==> brew install --verbose --build-bottle arangodb
==> Downloading https://download.arangodb.com/Source/ArangoDB-3.6.0.tar.gz
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 8ccb5568eb47e7e6dc49cfa2c07cd6b13a3be38716f3eba961634cd19a4f8031
  Actual: ebdc4afea0a1cd15f992f6edacaa3c4f2cdb23acdcdd8d7bc3d1f000564ec523
 Archive: /github/home/.cache/Homebrew/downloads/60bc1ad973ed91405aabc685a78cea59864495595c02388fcadf33f3ae5e7dcf--ArangoDB-3.6.0.tar.gz
To retry an incomplete download, remove the file above.

  </pre>
</details>

## What you expected to happen

No checksum mismatch error.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install --build-from-source arangodb`

**Comment by dawidd6** [comment]
Should we just swap the checksum in formula or dig it on why it has changed?

**Comment by SMillerDev** [comment]
Always check why it has changed.
