### ISSUE TITLE
dnsmasq fails to start using brew services with default plist

### ISSUE THREAD

**Issue by ryankask** [Homebrew/homebrew-core#50117]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to start dnsmasq with `sudo brew services start dnsmasq` after running `brew cleanup`. I did this so I could run dnasmasq.

## What happened (include command output)

`brew cleanup` removes empty configuration directories that are required to be present when starting the dnsmasq service using the default list.

Here is the output of `brew cleanup`:

```
$ brew cleanup -n
Would remove (empty directory): /usr/local/etc/dnsmasq.d/ppp
Would remove (empty directory): /usr/local/etc/dnsmasq.d/dhcpc
```

It also purges /usr/local/etc/dnsmasq.d because that becomes empty when the directories above are purged. That prevents dnsmasq from starting. See below.

```
$ sudo brew services restart dnsmasq
Password:
Stopping `dnsmasq`... (might take a while)
==> Successfully stopped `dnsmasq` (label: homebrew.mxcl.dnsmasq)
Warning: Taking root:admin ownership of some dnsmasq paths:
  /usr/local/Cellar/dnsmasq/2.80/sbin
  /usr/local/Cellar/dnsmasq/2.80/sbin/dnsmasq
  /usr/local/opt/dnsmasq
  /usr/local/opt/dnsmasq/sbin
  /usr/local/var/homebrew/linked/dnsmasq
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
==> Successfully started `dnsmasq` (label: homebrew.mxcl.dnsmasq)
```

The service reports that is started but after inspecting the console, I see:

```
default	08:34:33.079132-0500	dnsmasq	cannot access directory /usr/local/etc/dnsmasq.d: No such file or directory
default	08:34:33.079425-0500	dnsmasq	FAILED to start up
```

## What you expected to happen

dnsmasq to start.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install dnsmasq`
2. `brew cleanup` -> `Pruned 0 symbolic links and 3 directories from /usr/local`
3. `sudo brew services restart dnsmasq`
4. fail - /usr/local/etc/dnsmasq.d does not exist because it was purged by `brew cleanup`

## Configuration

```
$ brew config
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e9746a2d19c4ef99733beb17d2c2d7a905563e42
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_VISUAL: emacs
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1, 1.8.0_232
macOS: 10.15.3-x86_64
CLT: 11.0.33.17
Xcode: 11.3.1
```

**Comment by berndkrannich** [comment]
Stumbled across the same thing. I believe this was introduced by #47722 (cc: @mcdado, @chenrui333) adding a config parameter to dnsmasq which requires `/usr/local/etc/dnsmasq.d` to exist.

Now, I ran this on a freshly installed Mac so my initial assumption was that `/usr/local/etc/dnsmasq.d` doesn't exist by default, but I can't rule out that @ryankask's observation is what created the issue for me, too, in other words that I ran a `brew cleanup` somewhen during the setup process.

**Comment by mcdado** [comment]
Okay, that makes sense... I didn't know that brew cleanup removes empty directories! Well, could it then be possible to exclude that directory or to create a dummy file that keeps brew cleanup from removing it?

Anyway, you initial assumption shouldn't be right, because the formula's post_install does create the paths, if I'm not mistaken.

**Comment by jonchang** [comment]
Can you add `skip_clean ...` to dnsmasq and try your steps again? That should prevent the cleaner from removing those files. If it works please open a pull request, thanks!

**Comment by ryankask** [comment]
@jonchang I gave it a shot here https://github.com/ryankask/homebrew-core/commit/1c3d8aa9488ddabb380624e2061ee21da1da1618 but it doesn't work.

```
$ brew cleanup --dry-run
Would remove (empty directory): /usr/local/etc/dnsmasq.d/ppp                                              Would remove (empty directory): /usr/local/etc/dnsmasq.d/dhcpc
```

According to [this comment](https://github.com/Homebrew/brew/issues/6276#issuecomment-532629656) `skip_clean` "is an instruction to the installer but not to brew cleanup. [...] Putting a .keepme file in that directory is the best bet to avoid cleaning." I don't see any .keepme files being added.

**Comment by jonchang** [comment]
Try adding those files in the post install step then.

**Comment by mcdado** [comment]
> Try adding those files in the post install step then.

I'm on it.

**Comment by mcdado** [comment]
@ryankask  @berndkrannich try `brew reinstall dnsmasq`

**Comment by ryankask** [comment]
Thanks! The issue has been resolved.

**Comment by berndkrannich** [comment]
@mcdado: Confirmed to be working on my end, too. Thank you very much for looking into the topic!
