### ISSUE TITLE
"brew install zeromq --HEAD" fails

### ISSUE THREAD

**Issue by kozo2** [Homebrew/homebrew-core#5017]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

```
bash-3.2$ brew install zeromq --HEAD
==> Using the sandbox
==> Cloning https://github.com/zeromq/libzmq.git
Updating /Users/knishida/Library/Caches/Homebrew/zeromq--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/zeromq/HEAD-4039858 --without-libsodium
==> make
Last 15 lines from /Users/knishida/Library/Logs/Homebrew/zeromq/03.make:
2016-09-20 17:28:24 +0900

make

Making all in doc
make[1]: Nothing to be done for `all'.
make[1]: *** No rule to make target `src/pollset.cpp', needed by `src/src_libzmq_la-pollset.lo'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [all-recursive] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

```

and here is the `brew gist-logs zeromq' link

https://gist.github.com/anonymous/d1b1a4ccd180661aeff389293468ea10

**Comment by ilovezfs** [comment]
This fixes it.
```
iMac-TMP:homebrew-core joe$ git diff -- Formula/zeromq.rb 
diff --git a/Formula/zeromq.rb b/Formula/zeromq.rb
index bc4d158..11d3c75 100644
--- a/Formula/zeromq.rb
+++ b/Formula/zeromq.rb
@@ -34,6 +34,8 @@ class Zeromq < Formula
   def install
     ENV.universal_binary if build.universal?
 
+    (buildpath/"src").install_symlink buildpath/"pollset.cpp"
+
     args = ["--disable-dependency-tracking", "--prefix=#{prefix}"]
     if build.with? "libpgm"
       # Use HB libpgm-5.2 because their internal 5.1 is b0rked.
```

**Comment by zmwangx** [comment]
They should sort this out themselves.

**Comment by ilovezfs** [comment]
indeed.

**Comment by kozo2** [comment]
@ilovezfs Thanks. Your patch worked well. 
Is it OK if I send your patch as pull request to https://github.com/Homebrew/homebrew-core/blob/master/Formula/zeromq.rb ?

**Comment by zmwangx** [comment]
@kozo2 Glad it worked, but no, we don't patch our formula for such glaring omissions, and since it's HEAD this workaround will break once they issue a fix. It should be easy to ask upstream to fix this.

**Comment by ilovezfs** [comment]
@kozo2 it would be best to start out by reporting the problem upstream.

**Comment by kozo2** [comment]
@zmwangx @ilovezfs I understood what you said. I will ask https://github.com/zeromq/libzmq to fix this.

**Comment by zmwangx** [comment]
I think it's okay to close this, because that's all we can do on our side.

**Comment by kozo2** [comment]
Got it.

**Comment by bluca** [comment]
Sorry for the breakage, fixed by merging https://github.com/zeromq/libzmq/pull/2113

**Comment by kozo2** [comment]
Thank you!
