### ISSUE TITLE
homeschick fish config file hardcodes incorrect path

### ISSUE THREAD

**Issue by ax42** [Homebrew/homebrew-core#50237]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installed `homeshick` and then tried to run the `homeshick`command from the fish shell.

## What happened (include command output)

Error message.

<details>
  <summary>Command output</summary>
  <pre>
╰─$ homeshick
fish: Unknown command /Users/ax/.homesick/repos/homeshick/bin/homeshick
- (line 1):
begin; /Users/ax/.homesick/repos/homeshick/bin/homeshick
       ^
from sourcing file -
	called on line 61 of file /usr/local/Cellar/fish/3.0.2/share/fish/functions/eval.fish

in function 'eval'
	called on line 18 of file /usr/local/share/fish/vendor_functions.d/homeshick.fish

in function 'homeshick'
	called on standard input
  </pre>
</details>

## What you expected to happen

Command should work.

Running with the full path (`/usr/local/bin/homeshick`) works.

## Step-by-step reproduction instructions (by running `brew install` commands)

Issue seems to be that `/usr/local/share/fish/vendor_functions.d/homeshick.fish` contains the hard-coded path `$HOME/.homesick/repos/homeshick/bin/homeshick`, which would be correct if homeshick had been installed manually, but incorrect when installed via `brew`.  

Modifying the `homesick.fish` file to the correct path fixes the issue.

## brew config output
```
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1a3eac9692a7fda0b3c008b302524edccb1cf6c9
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.0.33.8
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
That seems like a fish bug, can you report it there?

**Comment by ax42** [comment]
It seems specific to the brew installation as the “normal” installation would have the binary in the place pointed to by the config file.  I don’t know brew formulas well - is it possible for the brew installation to modify that file during installation?

Alexis

**Comment by SMillerDev** [comment]
It is, but fish is generally aware of the existence of homebrew so they can just account for that. The issue isn't the homebrew install, it's fish pointing to the wrong location.
