### ISSUE TITLE
phpdbg readline support not enabled

### ISSUE THREAD

**Issue by aleksandrs-ledovskis** [Homebrew/homebrew-core#50253]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Checklist is redundant, but if you wish...

## What you were trying to do (and why)

`brew install php`

Installing [`php`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/php.rb) formula, in addition to `php(1)` binary provides some support utils, among them the `phpdbg(1)`. It is a gdb/lldb-style interactive CLI debugger.

## What happened (include command output)

By cursory look `phpdbg` works just fine, however when trying to use extended entry of commands (think, `<TAB>` completion or history lookup with keyboard arrow keys) it instead prints them out as shell escape combinations - a telltale sign of missing `readline` implementation.

This is confirmed by `Readline   unavailable` line in `phpdbg info` output.

<details>
  <summary>Command output</summary>
  <pre>
$ phpdbg info
[Welcome to phpdbg, the interactive PHP debugger, v7.4.2]
To get help using phpdbg type "help" and press enter
[Please report bugs to <http://bugs.php.net/report.php>]
[Could not open file /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/info]
prompt> info
Execution Context Information

Readline   unavailable
  </pre>
</details>

## What you expected to happen

Using up/down/left/right and `<TAB>` completion keys works in `phpdbg` session.

---

### Possible fix

Applying following patch locally

```patch
diff --git a/Formula/php.rb b/Formula/php.rb
index 464b4aafe8..28c30a0515 100644
--- a/Formula/php.rb
+++ b/Formula/php.rb
@@ -35,6 +35,7 @@ class Php < Formula
   depends_on "openldap"
   depends_on "openssl@1.1"
   depends_on "sqlite"
+  depends_on "readline"
   depends_on "tidy-html5"
   depends_on "unixodbc"
   depends_on "webp"
@@ -116,6 +117,7 @@ class Php < Formula
       --enable-pcntl
       --enable-phpdbg
       --enable-phpdbg-webhelper
+      --enable-phpdbg-readline
       --enable-shmop
       --enable-soap
       --enable-sockets
@@ -139,6 +141,7 @@ class Php < Formula
       --with-ldap-sasl
       --with-libxml
       --with-libedit
+      --with-readline
       --with-mhash#{headers_path}
       --with-mysql-sock=/tmp/mysql.sock
       --with-mysqli=mysqlnd
```

makes `phpdbg info` output 

```
prompt> info
Execution Context Information

Readline   no
Libedit    yes
```

This mitigates the issue. I do not have time to check if `readline` configuration options are necessary or if only `enable-phpdbg-readline` is key to solution, so welcoming input.

**Comment by SMillerDev** [comment]
Please make a pull request, you already have the changes and it saves someone from copying your work next they run into it.
