### ISSUE TITLE
librsvg package update

### ISSUE THREAD

**Issue by kukosk** [Homebrew/homebrew-core#50314]
I'm not sure if this is a good place to ask, but I didn't find any better. Is it possible to update the librsvg formula to the latest version? It seems like the current version has some issues with rendering. A lot of my svgs look really bad when converted to png compared to some of the previous versions of librsvg. And it also seems to behave inconsistently sometimes. It produces different outputs each time it's ran.

**Comment by SMillerDev** [comment]
It's very possible to update it. You can find the required documentation here: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request
