### ISSUE TITLE
No gpg-zip support

### ISSUE THREAD

**Issue by jhrr** [Homebrew/homebrew-core#50353]
## What you were trying to do (and why)

Install and use `gpg-zip`.

## What happened (include command output)

Is there a reason that `gpg-zip` option was removed in [a1bbbaa](https://github.com/Homebrew/homebrew-core/commit/a1bbbaa13a6d95372f947551ae3d44854f8264c4)?

## What you expected to happen

At the minimum to be able to install `gpg-zip` along with `gnupg` using a flag. 

```
brew install gnupg --with-gpg-zip
```

Thanks for all the hard work, ganbate.

**Comment by SMillerDev** [comment]
Yes, options break often. If you want to install something that isn't part of the default formula you should host it in a personal tap.
