### ISSUE TITLE
brew install tomcat@7  trying to access URL which do not exists anymore.

### ISSUE THREAD

**Issue by RRSR** [Homebrew/homebrew-core#50389]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ Yes] ran `brew update` and can still reproduce the problem?
- [ Yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ Yes there were no logs] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ Yes] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

`==> Downloading https://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-7/v7.0.
==> Downloading from http://mirrors.estointernet.in/apache/tomcat/tomcat-7/v7.0.

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://downloads.apache.org/tomcat/tomcat-7/v7.0.99/bin/apache-

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "tomcat@7"
Download failed: https://downloads.apache.org/tomcat/tomcat-7/v7.0.99/bin/apache-tomcat-7.0.99.tar.gz`

  

  </pre>
</details>

## What you expected to happen
I expected the tomcat to get downloaded and installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

Just execute the command `brew install tomcat@7 `

**Comment by SMillerDev** [comment]
While there is a pull request open that will update tomcat and resolve this, it might also be worth asking the tomcat developers why they immediately remove an older version once a new one is released. Beyond that there's nothing you or I can do but wait until the new release is merged and the issue (temporarily) resolved.

**Comment by bayandin** [comment]
WIll be fixed in https://github.com/Homebrew/homebrew-core/pull/50379

**Comment by RRSR** [comment]
It is working now. The command `brew install tomcat@7` is pointing to the http://apachemirror.wuchna.com/tomcat/tomcat-7/v7.0.100/bin now instead of the old/deleted version `7.0.99` which was giving `404`. 
Thanks.
