### ISSUE TITLE
Rust package does not include clippy or rustfmt

### ISSUE THREAD

**Issue by evitalis** [Homebrew/homebrew-core#50397]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to run `clippy` and `rustfmt` to format Rust code which is being developed on OSX, but found the tools missing and they are not present in brew.

## What happened (include command output)

Binaries were not found in the path

## What you expected to happen

`clippy` and `rustfmt` either included with the Rust package (preferred) or as suppliemental packages.

I see there was a previous PR to add this but it wanted to use nightly instead of stable. Other OS seem to have this resolved and these binaries come with the main Rust package, or as separate packages using the stable release.

These tools are relied upon by Rust developers and not all of them want to use `rustup` and prefer to stick to OS (or close to OS) packages.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew update`
2. `brew install rust`
3. Attempt to run `clippy` or `rustfmt`
4. `brew search clippy && brew search rustfmt`
4a. Results in no packages being found

**Comment by SMillerDev** [comment]
Please create a pull request. The homebrew project does not allow feature requests as issues.
