### ISSUE TITLE
Formula 'sshrc' source disappeared, formula should be removed

### ISSUE THREAD

**Issue by kbd** [Homebrew/homebrew-core#50444]
The formula 'sshrc'[1] no longer works because the source repository[2] has been deleted. In fact, the whole github account has been deleted.

[1] https://github.com/Homebrew/homebrew-core/blob/master/Formula/sshrc.rb
[2] https://github.com/Russell91/sshrc

**Comment by samford** [comment]
I ran across this in the past when checking for version updates, so thanks for reminding me. I created a PR that will delete the formula, if merged.
