### ISSUE TITLE
gdb Catalina bottle compiled without LZMA

### ISSUE THREAD

**Issue by mikeryan** [Homebrew/homebrew-core#50449]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to run GDB against binaries with LZMA compressed debugging symbols.

## What happened (include command output)

GDB prints out the following warning:

`warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time`

GDB configuration shows that it was compiled `--without-lzma`

<details>
  <summary>Command output</summary>
  <pre>

warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time,

gdb> show configuration
This GDB was configured as follows:
   configure --host=x86_64-apple-darwin19.3.0 --target=x86_64-apple-darwin19.3.0
             --with-auto-load-dir=:${prefix}/share/auto-load
             --with-auto-load-safe-path=:${prefix}/share/auto-load
             --with-expat
             --with-gdb-datadir=/usr/local/Cellar/gdb/9.1/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/local/Cellar/gdb/9.1/lib/gdb (relocatable)
             --without-libunwind-ia64
             --without-lzma
             --without-babeltrace
             --without-intel-pt
             --without-mpfr
             --without-xxhash
             --with-python=/System/Library/Frameworks/Python.framework/Versions/2.7
             --without-guile
             --disable-source-highlight
             --with-separate-debug-dir=/usr/local/Cellar/gdb/9.1/lib/debug (relocatable)

  </pre>
</details>

## What you expected to happen

GDB can load the symbols due to being compiled with LZMA support

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install gdb`
2. inside `gdb` run `show configuration`
3. look for `--without-lzma`

# Workaround

Reinstall gdb from source, making sure the `xz` package (with liblzma) is installed.

Example: `brew reinstall -s gdb`

**Comment by bayandin** [comment]
Thanks for the report @mikeryan, it should be fixed in https://github.com/Homebrew/homebrew-core/pull/50458
