### ISSUE TITLE
awscli not bottled for sierra

### ISSUE THREAD

**Issue by cscetbon** [Homebrew/homebrew-core#5045]
Hi,

I've seen that when there is a version update of a bottled Formula, a sierra version will be created. However, what about for formulas not updated since OS X Sierra came out ? On my host, brew wants to upgrade awscli but as there is no bottle, it wants me to install Xcode, which I don't really want...

Thanks

**Comment by zmwangx** [comment]
I had it bottled for Sierra in 4164543 but then it was updated to 1.10.64 and lost its bottle. I've queued it up for bottling and will notify you when it's done (expect that in a few hours).

**Comment by zmwangx** [comment]
Bottled in 48e0f33.

**Comment by cscetbon** [comment]
@zmwangx Is there a way for someone like me to trigger it or can it only done by a maintainer ?

**Comment by zmwangx** [comment]
> Is there a way for someone like me to trigger it 

Unfortunately no, or our CI will probably be overwhelmed.

**Comment by cscetbon** [comment]
okay @zmwangx, thank you for the information.

**Comment by zmwangx** [comment]
Oh by the way I'm not implying that you'll abuse our bot if you're given the permissions. Just saying it will be overwhelmed if everyone tries to bottle their own favorite.

**Comment by cscetbon** [comment]
No worries, that's what I understood :)
