### ISSUE TITLE
maven now, erroneously, requires openjdk - If you're a user of maven, you are able to ensure you have a jdk installed

### ISSUE THREAD

**Issue by jcolson** [Homebrew/homebrew-core#50531]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [✔️  ] ran `brew update` and can still reproduce the problem?
- [✔️ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [✔️ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [✔️ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

upgraded maven to 3.6.3

## What happened (include command output)

openjdk became a dependency

<details>
  <summary>Command output</summary>
  <pre>

  brew missing
  maven: openjdk

  </pre>
</details>

## What you expected to happen

not to have a dependency on openjdk

Is there a 'bug' filed asking for this dependency (I can't locate it)?  Was there undue load on the maintainers because there wasn't a dependency to openjdk?  It's logical to assume if one is a user of maven they are able to ensure they have a jdk installed, this should not be forced.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew upgrade

**Comment by jonchang** [comment]
> Is there a 'bug' filed asking for this dependency (I can't locate it)? Was there undue load on the maintainers because there wasn't a dependency to openjdk?

Yes, see https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies. Java is one of these non-Homebrew dependencies fulfilled by a `Requirement` which causes us, the maintainers of Homebrew, many problems as outlined in that historical document.

See https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies#today and https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap for details on how to use an externally installed Java.

**Comment by jcolson** [comment]
for those looking for a non openjdk dependency required tap

brew install jcolson/taps/maven-noopenjdk
