### ISSUE TITLE
Message on python@2 is wrong

### ISSUE THREAD

**Issue by hyperknot** [Homebrew/homebrew-core#50546]
There are 3 main issue with the message on python@2.

1. The `brew extract` command is not working because the package name contains "@" as per: https://github.com/Homebrew/brew/issues/7057 Moreover this really feels to make as hard as possible to use `brew extract`, I found absolutely no help on the linked page on how to set up an old version in a local tap. 

2. The linked commit hash is wrong, that contains the already deleted file, what we need is: 86a44a

3. I believe a much better solution would simply recommend to use:
```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/python@2.rb
```

I don't understand how can anything be unstable in an old git hash, which will never be updated in the future? All this will achieve is people getting angry at homebrew, and trying to look up brew commands from random internet sources which will break up their brew installation.

If Python 2 had a lifetime of 20 years with all the scientific papers requiring it for reproducible results, then why not make it a tiny bit more nicer for users to install this old version? In my opinion all what'd need to be on that page is that simple `brew install https://raw.githubusercontent.com`.

**Comment by SMillerDev** [comment]
Python 2 is outdated and installing it should in no way be encouraged or simplified. People had 11 years to update.

**Comment by hyperknot** [comment]
I'm not telling you to add support, but to at least make sure the message given is valid. 

You realize there were 1.3 million Python@2 installs in the last 365 days? You believe they'll just disappear because some maintaners wish so?

This way I believe homebrew is the only package manager which is actively removing working Python 2.7 from working macOS versions, and is doing everything to be hostile against users who need to use Python 2.7, including giving invalid instructions.

**Comment by jonchang** [comment]
You agreed to the [Code of Conduct](https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md#code-of-conduct) when opening an issue. Moreover you did not fill out the issue template as requested. Your hyperbole is unnecessary. Please be more respectful when communicating with maintainers. 

Python 2 still exists at `/usr/bin/python` so your assertion that Homebrew is removing Python from macOS is not supported. Please see https://github.com/Homebrew/brew/pull/7066 for work on fixing issue with `brew extract`.
