### ISSUE TITLE
sbt's "openjdk" dependency pulls in JDK 13

### ISSUE THREAD

**Issue by eed3si9n** [Homebrew/homebrew-core#50649]
Ref https://github.com/Homebrew/homebrew-core/commit/b812e5988bd82740e59b72684c79f64d9b6175d3#diff-bdf3fc0debecefebed7b56c142626381R11

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/16a70480726f125b3f962d52838e97bf

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install sbt and use my existing Java installation.

## What happened (include command output)

sbt is running with JDK 13.0.2.

<details>
  <summary>Command output</summary>

```
$ sbt 'eval sys.props("java.version")'
[warn] No sbt.version set in project/build.properties, base directory: /private/tmp/foo
[info] Loading settings for project global-plugins from idea.sbt,vimquit.sbt,plugins.sbt,pgp.sbt ...
[info] Loading global plugins from /Users/eed3si9n/.sbt/1.0/plugins
[info] Set current project to foo (in build file:/private/tmp/foo/)
[info] ans: String = 13.0.2
```

  </pre>
</details>

The reason this is problematic for sbt is because it is a _build tool_, used to to build libraries and applications on JVM. Changing the JVM version suddenly is a breaking change itself, but the even bigger issue is that the JVM version has a transitive property ("contagious"). Once a library is published with JDK 13, then the consumer has to use JDK 13 too.

For tooling and library authors, this usually means sticking to the lowest stable JDK version. Even for application authors, upgrading from one JDK version to another is a decision we don't make lightly. Certainly not by `brew upgrade` accidents.

## What you expected to happen

Use the JDK that's installed in the environment.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
# comment out sdkman or jenv in dotfiles

brew install sbt
java -version
sbt 'eval sys.props("java.version")'
```

## notes

https://github.com/Homebrew/homebrew-core/issues/50536

**Comment by SMillerDev** [comment]
Homebrew will use brewed dependencies where possible. The fact that other Java versions were previously possible was an unfortunate side-effect of java not being built from source as a formula. The current situation is the intended usage within Homebrew. If people want to use a different dependency the best course of action is to maintain it in a tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.

Just a couple of points to highlight:
- The `openjdk` installed as a dependency is not symlinked anywhere and will be used only if `JAVA_HOME` is not set

- If you'd like to use another Java installation feel free to set `JAVA_HOME` to any Java you want

- Using some random/installed by default Java is not reliable for software shipping.

**Comment by kshakir** [comment]
If anyone else trips over this and does NOT want to export JAVA_HOME, you can still install older versions of the sbt Formula that don't use openjdk-13 nor JAVA_HOME.

NOTE: openjdk pulling in JDK 13 is a problem for my system, as our older sbt projects were tripping over https://github.com/sbt/sbt/issues/5093 / https://github.com/scala/bug/issues/11608. Instead of upgrading all of those projects _now_ I've rolled back my machine to "Using some random/installed by default Java"

To install the last sbt Formula without openjdk-13 / JAVA_HOME I first uninstalled sbt then used:

```
brew install \
https://raw.githubusercontent.com/Homebrew/homebrew-core/5653c3d32c939514088e85639acadd5ce7cb163e/Formula/sbt.rb
```
