### ISSUE TITLE
apache-spark formula depends on the wrong java version

### ISSUE THREAD

**Issue by ArtsiomiTechArt** [Homebrew/homebrew-core#50686]
As far as I found **brew install apache-spark** command loads the wrong java version. 
It loads apache-spark v2.4.5 ( java 1.8 is required ) and open jdk v13

To Reproduce this,
1. brew install apache-spark
2. run **spark-shell** command
3. run next code snippet:
`sc.parallelize(1 to 10).take(10)`

Result:
`java.lang.IllegalArgumentException: Unsupported class file major version 57
  at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
  at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
  at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
  at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
`

Workaround:
- Open **load-spark-env.sh** file
- Add `export JAVA_HOME="{path_to_java_8}"` line

**Comment by Bo98** [comment]
Thanks. Looks like test we have was insufficient to catch this.

@reitermarkus Do we have a particular strategy for formulae which require Java/OpenJDK 8 or are they still all using the old Java requirement system?

**Comment by SMillerDev** [comment]
there's an openjdk@1.8 right?

**Comment by Bo98** [comment]
I don't see it in homebrew-core.

**Comment by SMillerDev** [comment]
Apparently there isn't, I could have sworn there was.

**Comment by MikeMcQuaid** [comment]
I believe we can't build it from source so it should stick on a `depends_on :java => ...`.

**Comment by dshorthouse** [comment]
Have the same problem. Can someone walk me through the workaround? Have tried to implement what @ArtsiomiTechArt suggested but can't seem to get it stick. I also have openjdk version "1.8.0_242" listed with a /usr/libexec/java_home -V.

**Comment by reitermarkus** [comment]
There is no `openjdj@1.8` because it can't be built on any macOS version we support.

In that case it should use the old system with a `"1.8"` instead of `"1.8+"`.
