### ISSUE TITLE
aria2 build failed on macOS Sierra

### ISSUE THREAD

**Issue by clavichord93** [Homebrew/homebrew-core#5069]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

```
$ brew install aria2
==> Using the sandbox
==> Downloading https://github.com/aria2/aria2/releases/download/release-1.27.1/
Already downloaded: /Users/Zheng/Library/Caches/Homebrew/aria2-1.27.1.tar.xz
==> ./configure --prefix=/usr/local/Cellar/aria2/1.27.1 --with-appletls --withou
Last 15 lines from /Users/Zheng/Library/Logs/Homebrew/aria2/01.configure:
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/aria2-20160921-6816-1dsatrz/aria2-1.27.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
```

```
$ brew gist-logs aria2
https://gist.github.com/89246a4c17b54e130ca1832c984215c5
```

**Comment by L3viathan** [comment]
I got similar messages (with different packages) after upgrading to Sierra and fixed it with `xcode-select --install` (as described [here](https://github.com/Homebrew/brew/blob/master/docs/Common-Issues.md#upgrading-macos))

**Comment by clavichord93** [comment]
@L3viathan But I have installed Command Line Tools with Xcode. I don't want to install Command Line Tools again.

**Comment by zmwangx** [comment]
Xcode and Command Line Tools are different things.

**Comment by clavichord93** [comment]
@zmwangx But if I installed Xcode, I will have Command Line Tools installed, is it right?

**Comment by zmwangx** [comment]
It's not right.

**Comment by clavichord93** [comment]
@zmwangx Can you explain?

**Comment by zmwangx** [comment]
As I said they are different things. `sudo xcode-select install` to install CLT.

**Comment by ilovezfs** [comment]
What are the outputs from these commands?

xcode-select -p
brew config
ls /Applications | grep Xcode

**Comment by ilovezfs** [comment]
Oh I see in your gist that you posted that you have Xcode 7 and are on Sierra. You need to just upgrade your Xcode to Xcode 8.
