### ISSUE TITLE
freerdp(HEAD) failed to build on 10.11.6

### ISSUE THREAD

**Issue by swarren83** [Homebrew/homebrew-core#5077]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

brew install --HEAD freerdp fails to build due to the following error:

    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/time.h:177:5: note: previous declaration is here
    int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
        ^
    1 error generated.

https://gist.github.com/swarren83/1c7fd1aed896fb22afab665b9f57b7a3

**Comment by nonamed108** [comment]
I submitted an upstream fix to try and get this addressed: 
[https://github.com/FreeRDP/FreeRDP/pull/3511](url)

For now you can 'brew edit freerdp' and add the following patch to the 'head' block:

    patch do
      url "https://github.com/nonamed108/FreeRDP/commit/ed697fa.diff"
      sha256 "054a72a59e93cbfb82a2ce635f25a74e15a7a7cdad72cca887c1ba44b235901d"
    end

**Comment by nonamed108** [comment]
Fixed upstream - so this issue can be closed now.
