### ISSUE TITLE
git not found (anymore), but it's there and I can't see any problem ?!

### ISSUE THREAD

**Issue by Tormen** [Homebrew/homebrew-core#50770]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [n/a ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

My brew stopped working seemingly out of the blue and for no good reason:

Really strange as `brew doctor` and when I interrupt the `brew update` after 10min of nothingness with `ctrl+c` tell me: Git is not in my PATH... but it is!

For now I am a dead duck, as without git... not much is possible ;)

Please see here for the output of `git doctor` and `git config` and some other commands: 
https://gist.github.com/Tormen/bdf23e0fe4d2d54cdd5a820bed939639

Also please note:

- git is in the PATH
- git is executable
- git runs well, when I execute `git --version` I get: git version 2.21.1 (Apple Git-122.3)
- I never had a problem with this git problem until today
- git also detects the git repo of Homebrew:

```
: admin@macado /usr/local/Homebrew %;git branch
  master
* stable
: admin@macado /usr/local/Homebrew %;ls -la .git
total 544
drwxrwxr-x   13 admin  admin     416 Feb 27 17:36 .
drwxrwxr-x   20 admin  admin     640 Feb 26 11:46 ..
-rw-rw-r--    1 admin  admin   15138 Feb 26 11:46 FETCH_HEAD
-rw-rw-r--    1 admin  admin     981 Feb 26 11:46 GITHUB_HEADERS
-rw-rw-r--    1 admin  admin      23 Feb 26 11:46 HEAD
-rw-rw-r--    1 admin  admin     463 Feb 26 11:46 config
-rw-rw-r--    1 admin  admin      73 Dec 23 23:26 description
drwxrwxr-x   13 admin  admin     416 Dec 23 23:26 hooks
-rw-rw----    1 admin  admin  245659 Feb 27 17:36 index
drwxrwxr-x    3 admin  admin      96 Dec 23 23:26 info
drwxrwxr-x    4 admin  admin     128 Dec 23 23:26 logs
drwxrwxr-x  216 admin  admin    6912 Feb 17 17:25 objects
drwxrwxr-x    5 admin  admin     160 Dec 23 23:26 refs
: admin@macado /usr/local/Homebrew %;git log
commit 27fa87c94a6cf7be40fc8f8fc96bc7c387b7781e (HEAD -> stable, tag: 2.2.6)
Merge: 3e27e7a81 06841497b
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Mon Feb 17 12:41:39 2020 +0000

    Merge pull request #7042 from pthariensflame/improvement/imgbot
    
    [ImgBot] Optimize images

...
```

## What you were trying to do (and why)

`git cask install gog-downloader` (because I own gog games)

## What happened (include command output)

I first pressed `ctrl+c` ater >10min

<details>
  <summary>Command output</summary>
  <pre>

brew cask install gog-downloader
==> Installing dependencies for git: pcre2
==> Installing git dependency: pcre2
Updating Homebrew...
^C
Error: Git must be installed and in your PATH!
^C
: admin@macado ~ %;

  </pre>
</details>

## What you expected to happen

it uses the Apple git - like it always did until now - to update Homebrew 
and then installs the cask

## Step-by-step reproduction instructions (by running `brew install` commands)

See above.

**Comment by Tormen** [comment]
I am sure this can help to narrow down the problem. Not sure if it's normal that all the "-z" and -n" are all empty... 

I just *really* don't get why the `git --version` it runs seems to fail and if I run it on the CLI it works just fine ?!?!?! :(((

```
brew update --debug
+ [[ -z '' ]]
+ [[ -z '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ export HOMEBREW_UPDATE_TO_TAG=1
+ HOMEBREW_UPDATE_TO_TAG=1
+ [[ -z '' ]]
+ HOMEBREW_AUTO_UPDATE_SECS=300
+ [[ -e /usr/local/Cellar ]]
+ [[ ! -w /usr/local/Cellar ]]
+ [[ ! -w /usr/local/Homebrew ]]
+ [[ -n '' ]]
+ git --version
+ [[ -d /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core ]]
+ brew install git
+ /usr/local/bin/brew install git
==> Installing dependencies for git: pcre2
==> Installing git dependency: pcre2
^C
+ unset GIT_EXECUTABLE
+ git --version
+ odie 'Git must be installed and in your PATH!'
+ onoe 'Git must be installed and in your PATH!'
+ [[ -t 2 ]]
+ [[ -z '' ]]
+ echo -ne '\033[4;31mError\033[0m: '
Error: + [[ 1 -eq 0 ]]
+ echo 'Git must be installed and in your PATH!'
Git must be installed and in your PATH!
+ exit 1
: admin@macado /usr/local/Homebrew %;git --version
git version 2.21.1 (Apple Git-122.3)
```

**Comment by Bo98** [comment]
Help & support should go to https://discourse.brew.sh rather than here.

Here's the search order Homebrew does for Git:
* If `$HOMEBREW_FORCE_BREWED_GIT` is set, use `PREFIX/opt/git/bin/git` where `PREFIX` is `/usr/local` by default.
* If `$HOMEBREW_GIT_PATH` is set, use that (developers only).
* Use anything returned in `type -aP git` that is NOT `/usr/bin/git`.
* Use the result of `/usr/bin/xcrun -find git` (if `/usr/bin/xcode-select -print-path` is set and not `/`)
* `/Applications/Xcode.app/Contents/Developer/usr/bin/git` (may be the same as above)
* `/usr/bin/git`

If you post this on Discourse, it would be useful to try run `git --version` on these.

**Comment by Tormen** [comment]
Thanks @Bo98 !

I had posted it here, because if brew says git isn't there but it is, then this is a bug and should be fixed, no ?

But I'll post it on Discourse then and I did include `git --version` already :)

**Comment by Bo98** [comment]
> I had posted it here, because if brew says git isn't there but it is, then this is a bug and should be fixed, no ?

That's very possible, but considering there aren't other reports about it then there's nothing to say it's not something specific to your machine. I'll be happy to fix the issue if we find a bug.

> I did include `git --version` already.

Sorry, what I meant is to go through the search flow I detailed above and run that on each of the gits you see - not just the first one on the path. `type -aP git` is probably the most interesting one.

**Comment by Tormen** [comment]
@Bo98 : Fair enough :))

For continuity: I posted it here:
https://discourse.brew.sh/t/git-not-found-anymore-but-its-there/7040

And I will try to add the `git --version` infos.

**Comment by Tormen** [comment]
@Bo98 the 4th point in your list is a hit and points to `/Library/Developer/CommandLineTools/usr/bin/git`
but I can't find anything wrong with this git either.

This is sooooo strange :((

**Comment by Tormen** [comment]
If anyone stumbles across this: 

The problem was missing executable bit was missing on `$HOMEBREW_LIBRARY/Homebrew/shims/scm/git`

Solution: 
`chmod +x $(brew --prefix)/Homebrew/Library/Homebrew/shims/scm/git`

**Comment by SMillerDev** [comment]
That means your git config probably strips executable bits and this will break again on the next brew update
