### ISSUE TITLE
no-more-secrets fails to build on macOS Sierra

### ISSUE THREAD

**Issue by stephenwade** [Homebrew/homebrew-core#5080]
I can't build no-more-secrets on Sierra. I get the error:

    /bin/sh: /usr/bin/sudo: Operation not permitted
    make: *** [/usr/include/ncurses.h] Error 126

Here's the output from `brew gist-logs no-more-secrets`:

https://gist.github.com/ca796adafecc4254a3d090f5dbf09979

**Comment by zmwangx** [comment]
It appears that you don't have `/usr/include/ncurses.h` (because you hit code that's only executed when `/usr/include/ncurses.h` is not present), which is a sign that your macOS is cooked. What happens when you

```sh
$ ls -l /usr/include/ncurses.h
```

**Comment by stephenwade** [comment]
Hm. I don't seem to have a `/usr/include` folder.

This computer is a fresh install of one of the public betas, upgraded to the final release a few days ago. What do you mean by "cooked"?

**Comment by zmwangx** [comment]
I guess you have neither Xcode nor CLT installed? (I'm not familiar with this configuration because installing Xcode and CLT is the first thing I do in every macOS install.)

Please show me your `brew config` and `brew doctor`.

And probably `sudo xcode-select --install` too.

**Comment by zmwangx** [comment]
> I guess you have neither Xcode nor CLT installed?

Wait, that's not right. You can't install brew with neither Xcode nor CLT... Anyway, show me your `brew config` and `brew doctor` as I said above, thanks.

**Comment by stephenwade** [comment]
```
stephen@stephen-retina:~$ brew config
HOMEBREW_VERSION: 1.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee25e2b3466f8d84b2ac9a67edbc9bf3900b8edc
Last commit: 88 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48e0f33e711c6415a0b8988627235ecf7e2a65ae
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.1/bin/ruby
Java: 1.8.0_102
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: N/A
```

```
stephen@stephen-retina:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.
```

Seems I don't have the command-line tools installed. I thought I did, but maybe I need to reinstall it now that I've upgraded to the final release. I'll try `sudo xcode-select --install` and see whether it starts working.

**Comment by zmwangx** [comment]
Oh sorry, those are already in your gist-logs, what was I thinking... Anyway, please try `sudo xcode-select --install` to install CLT first.

**Comment by stephenwade** [comment]
Sure enough, the installation succeeds now. I'm surprised `brew doctor` didn't warn me that the CLT wasn't installed.

**Comment by zmwangx** [comment]
There are people on the team who try hard to make sure brew works in Xcode-only or CLT-only environments, but I'm not part of the effort and not a big fan of that effort... The effort seems to be getting harder over time too. This is kind of a peculiar case because the Makefile goes straight for `/usr/include/ncurses.h` rather than rely on search paths which should be handled in an Xcode-only environment, so CLT is required to actually install the headers into `/usr/include`.
