### ISSUE TITLE
Broken install of homebrew. Can't uninstall or reinstall now.

### ISSUE THREAD

**Issue by drhectapus** [Homebrew/homebrew-core#5084]
Trying to learn Rails via the Lynda course so am completely new to Homebrew. 

I copied the following into terminal:
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
`

During this, I was on a train and my wifi must have broke as we went into a tunnel, so I received the following fatal error msg:
`==> Downloading and installing Homebrew...
fatal: unable to access 'https://github.com/Homebrew/brew/': Failed to connect to github.com port 443: Operation timed out
Failed during: git fetch origin master:refs/remotes/origin/master -n --depth=1`

When I try re-installing, I get the following:
`It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin Cellar etc Frameworks Homebrew include lib opt sbin share var`

And when I try uninstalling, I still get no luck:
`Failed to locate Homebrew!`

Please advise!

**Comment by MikeMcQuaid** [comment]
Ok, let's try to do this somewhat manually:
```
cd /usr/local/Homebrew
git init
git remote add origin https://github.com/Homebrew/brew
git fetch --all
git checkout -B master origin/master
cd /usr/local
ln -s /usr/local/Homebrew/bin/brew /usr/local/bin
```
and see if it's working. If not: shout with what failed.

**Comment by drhectapus** [comment]
@MikeMcQuaid working perfectly now, thank u!

**Comment by kifreez** [comment]
@MikeMcQuaid You saved my day!!!

**Comment by asiegler408** [comment]
I just ran into the same thing because of dumb new-guy mistakes, and these instructions were a *lifesaver*... THANK YOU!!!!

**Comment by Abrasha** [comment]
I fixed this just by force deleting Homebrew directory:

    sudo rm -rf /usr/local/Homebrew/

And then I launched installation again.
The reason was that I had no `git` installed on my system.
