### ISSUE TITLE
Build cannot find batteries 2.5.2

### ISSUE THREAD

**Issue by vmrsss** [Homebrew/homebrew-core#5085]
please help with the following

### Bug reports:

Build downloads batteries 2.5.2 correctly, but then fails to find it and stops. Here is the terminal output. 
"""
brew install fstar
==> Using the sandbox
==> Cloning https://github.com/FStarLang/FStar.git
Updating ~/Library/Caches/Homebrew/fstar--git
==> Checking out tag v0.9.2.0
==> opam init --no-setup
==> Downloading http://download.camlcity.org/download/findlib-1.5.5.tar.gz
==> Downloading https://github.com/ocaml-batteries-team/batteries-included/archive/v2.5.2.tar.gz
Already downloaded: ~/Library/Caches/Homebrew/fstar--batteries-2.5.2.tar.gz
==> Downloading https://forge.ocamlcore.org/frs/download.php/1471/zarith-1.3.tgz
==> Downloading http://mjambon.com/releases/yojson/yojson-1.1.6.tar.gz
==> opam install ocamlfind=1.5.5 batteries=2.5.2 zarith=1.3 yojson=1.1.6
Last 15 lines from ~/Logs/Homebrew/fstar/02.opam:
2016-09-22 02:03:03 +0100

opam
install
ocamlfind=1.5.5
batteries=2.5.2
zarith=1.3
yojson=1.1.6

Your request can't be satisfied:
  - No package matches batteries.2.5.2.

No solution found, exiting

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by vmrsss** [comment]
HI Mike, new to home-brew, I thought i did follow the steps. I'll try again asap

**Comment by MikeMcQuaid** [comment]
No worries, thanks!
