### ISSUE TITLE
Node v6.6.0 fails on macOS Sierra - In file included from ../deps/gtest/src/gtest-filepath.cc:32: ../deps/gtest/include/gtest/gtest-message.h:49:10: fatal error: 'limits' file not found #include <limits>

### ISSUE THREAD

**Issue by ithiru** [Homebrew/homebrew-core#5087]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

https://gist.github.com/anonymous/795bb694f5d0986ff64e7b3f4fa5c745

In file included from ../deps/gtest/src/gtest-filepath.cc:32:
../deps/gtest/include/gtest/gtest-message.h:49:10: fatal error: 'limits' file not found
#include <limits>

**Comment by mistydemeo** [comment]
You'll need to upgrade to Xcode 8.

**Comment by ithiru** [comment]
oh, thanks !

**Comment by mistydemeo** [comment]
Let me know if you have more problems after that!

**Comment by DomT4** [comment]
Wondering if we should make not running the latest Xcode a hard failure for everyone, not just folks running prerelease macOS versions. I think this is the 5th or 6th Issue in the last 24 hours 😕.

**Comment by ilovezfs** [comment]
That, and also `sudo xcode-select -r` if pointing at CLT on 10.11

**Comment by mistydemeo** [comment]
@DomT4 I think that'd be smart.

**Comment by ithiru** [comment]
@mistydemeo I installed command lines tools and it worked like Charm, I agree with @DomT4 that if the install fails with pre-requisite it would be great. Let me know if I can do something to make it happen.

`brew doctor` **does** say Xcode is out dated, but I thought it is fine.

**Comment by ilovezfs** [comment]
@DomT4 if you hurry a PR for your suggestion, it will probably make it into 1.0.3

**Comment by DomT4** [comment]
@ilovezfs Saw your Slack ping, cheers 🙇. Will poke at it shortly.

**Comment by DomT4** [comment]
https://github.com/Homebrew/brew/pull/956
