### ISSUE TITLE
I can't use this code. "brew install gcc"

### ISSUE THREAD

**Issue by Tanesan** [Homebrew/homebrew-core#50906]
I use linux brew on the web server.
I want to use Django, So, I have to install python.
I could do an SSH connection to the server.
I can't do anything from there.
What code should I enter?

>>>$  sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> This script will install:
/home/*******/.linuxbrew/bin/brew
/home/*******/.linuxbrew/share/doc/homebrew
/home/*******/.linuxbrew/share/man/man1/brew.1
/home/*******/.linuxbrew/share/zsh/site-functions/_brew
/home/*******/.linuxbrew/etc/bash_completion.d/brew
/home/*******/.cache/Homebrew/
/home/*******/.linuxbrew/Homebrew
==> The following new directories will be created:
/home/*******/.linuxbrew/bin
/home/*******/.linuxbrew/etc
/home/*******/.linuxbrew/include
/home/*******/.linuxbrew/lib
/home/*******/.linuxbrew/sbin
/home/*******/.linuxbrew/share
/home/*******/.linuxbrew/var
/home/*******/.linuxbrew/opt
/home/*******/.linuxbrew/share/zsh
/home/*******/.linuxbrew/share/zsh/site-functions
/home/*******/.linuxbrew/var/homebrew
/home/*******/.linuxbrew/var/homebrew/linked
/home/*******/.linuxbrew/Cellar
/home/*******/.linuxbrew/Caskroom
/home/*******/.linuxbrew/Homebrew
/home/*******/.linuxbrew/Frameworks

Press RETURN to continue or any other key to abort
==> /bin/mkdir -p /home/*******/.linuxbrew
==> /bin/chown *******:******* /home/*******/.linuxbrew
==> /bin/mkdir -p /home/*******/.linuxbrew/bin /home/*******/.linuxbrew/etc /home/*******/.linuxbrew/include /home/*******/.linuxbrew/lib /home/*******/.linuxbrew/sbin /home/*******/.linuxbrew/share /home/*******/.linuxbrew/var /home/*******/.linuxbrew/opt /home/*******/.linuxbrew/share/zsh /home/*******/.linuxbrew/share/zsh/site-functions /home/*******/.linuxbrew/var/homebrew /home/*******/.linuxbrew/var/homebrew/linked /home/*******/.linuxbrew/Cellar /home/*******/.linuxbrew/Caskroom /home/*******/.linuxbrew/Homebrew /home/*******/.linuxbrew/Frameworks
==> /bin/chmod g+rwx /home/*******/.linuxbrew/bin /home/*******/.linuxbrew/etc /home/*******/.linuxbrew/include /home/*******/.linuxbrew/lib /home/*******/.linuxbrew/sbin /home/*******/.linuxbrew/share /home/*******/.linuxbrew/var /home/*******/.linuxbrew/opt /home/*******/.linuxbrew/share/zsh /home/*******/.linuxbrew/share/zsh/site-functions /home/*******/.linuxbrew/var/homebrew /home/*******/.linuxbrew/var/homebrew/linked /home/*******/.linuxbrew/Cellar /home/*******/.linuxbrew/Caskroom /home/*******/.linuxbrew/Homebrew /home/*******/.linuxbrew/Frameworks
==> /bin/chmod 755 /home/*******/.linuxbrew/share/zsh /home/*******/.linuxbrew/share/zsh/site-functions
==> /bin/chown ******* /home/*******/.linuxbrew/bin /home/*******/.linuxbrew/etc /home/*******/.linuxbrew/include /home/*******/.linuxbrew/lib /home/*******/.linuxbrew/sbin /home/*******/.linuxbrew/share /home/*******/.linuxbrew/var /home/*******/.linuxbrew/opt /home/*******/.linuxbrew/share/zsh /home/*******/.linuxbrew/share/zsh/site-functions /home/*******/.linuxbrew/var/homebrew /home/*******/.linuxbrew/var/homebrew/linked /home/*******/.linuxbrew/Cellar /home/*******/.linuxbrew/Caskroom /home/*******/.linuxbrew/Homebrew /home/*******/.linuxbrew/Frameworks
==> /bin/chgrp ******* /home/*******/.linuxbrew/bin /home/*******/.linuxbrew/etc /home/*******/.linuxbrew/include /home/*******/.linuxbrew/lib /home/*******/.linuxbrew/sbin /home/*******/.linuxbrew/share /home/*******/.linuxbrew/var /home/*******/.linuxbrew/opt /home/*******/.linuxbrew/share/zsh /home/*******/.linuxbrew/share/zsh/site-functions /home/*******/.linuxbrew/var/homebrew /home/*******/.linuxbrew/var/homebrew/linked /home/*******/.linuxbrew/Cellar /home/*******/.linuxbrew/Caskroom /home/*******/.linuxbrew/Homebrew /home/*******/.linuxbrew/Frameworks
==> Downloading and installing Homebrew...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 131782 (delta 0), reused 1 (delta 0), pack-reused 131775
Receiving objects: 100% (131782/131782), 31.65 MiB | 12.83 MiB/s, done.
Resolving deltas: 100% (96694/96694), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
 * [new tag]         1.3.4      -> 1.3.4
 * [new tag]         1.3.5      -> 1.3.5
 * [new tag]         1.3.6      -> 1.3.6
 * [new tag]         1.3.7      -> 1.3.7
 * [new tag]         1.3.8      -> 1.3.8
 * [new tag]         1.3.9      -> 1.3.9
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.4.2      -> 1.4.2
 * [new tag]         1.4.3      -> 1.4.3
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.10     -> 1.5.10
 * [new tag]         1.5.11     -> 1.5.11
 * [new tag]         1.5.12     -> 1.5.12
 * [new tag]         1.5.13     -> 1.5.13
 * [new tag]         1.5.14     -> 1.5.14
 * [new tag]         1.5.2      -> 1.5.2
 * [new tag]         1.5.3      -> 1.5.3
 * [new tag]         1.5.4      -> 1.5.4
 * [new tag]         1.5.5      -> 1.5.5
 * [new tag]         1.5.6      -> 1.5.6
 * [new tag]         1.5.7      -> 1.5.7
 * [new tag]         1.5.8      -> 1.5.8
 * [new tag]         1.5.9      -> 1.5.9
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.10     -> 1.6.10
 * [new tag]         1.6.11     -> 1.6.11
 * [new tag]         1.6.12     -> 1.6.12
 * [new tag]         1.6.13     -> 1.6.13
 * [new tag]         1.6.14     -> 1.6.14
 * [new tag]         1.6.15     -> 1.6.15
 * [new tag]         1.6.16     -> 1.6.16
 * [new tag]         1.6.17     -> 1.6.17
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.6.3      -> 1.6.3
 * [new tag]         1.6.4      -> 1.6.4
 * [new tag]         1.6.5      -> 1.6.5
 * [new tag]         1.6.6      -> 1.6.6
 * [new tag]         1.6.7      -> 1.6.7
 * [new tag]         1.6.8      -> 1.6.8
 * [new tag]         1.6.9      -> 1.6.9
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         1.7.1      -> 1.7.1
 * [new tag]         1.7.2      -> 1.7.2
 * [new tag]         1.7.3      -> 1.7.3
 * [new tag]         1.7.4      -> 1.7.4
 * [new tag]         1.7.5      -> 1.7.5
 * [new tag]         1.7.6      -> 1.7.6
 * [new tag]         1.7.7      -> 1.7.7
 * [new tag]         1.8.0      -> 1.8.0
 * [new tag]         1.8.1      -> 1.8.1
 * [new tag]         1.8.2      -> 1.8.2
 * [new tag]         1.8.3      -> 1.8.3
 * [new tag]         1.8.4      -> 1.8.4
 * [new tag]         1.8.5      -> 1.8.5
 * [new tag]         1.8.6      -> 1.8.6
 * [new tag]         1.9.0      -> 1.9.0
 * [new tag]         1.9.1      -> 1.9.1
 * [new tag]         1.9.2      -> 1.9.2
 * [new tag]         1.9.3      -> 1.9.3
 * [new tag]         2.0.0      -> 2.0.0
 * [new tag]         2.0.1      -> 2.0.1
 * [new tag]         2.0.2      -> 2.0.2
 * [new tag]         2.0.3      -> 2.0.3
 * [new tag]         2.0.4      -> 2.0.4
 * [new tag]         2.0.5      -> 2.0.5
 * [new tag]         2.0.6      -> 2.0.6
 * [new tag]         2.1.0      -> 2.1.0
 * [new tag]         2.1.1      -> 2.1.1
 * [new tag]         2.1.10     -> 2.1.10
 * [new tag]         2.1.11     -> 2.1.11
 * [new tag]         2.1.12     -> 2.1.12
 * [new tag]         2.1.13     -> 2.1.13
 * [new tag]         2.1.14     -> 2.1.14
 * [new tag]         2.1.15     -> 2.1.15
 * [new tag]         2.1.16     -> 2.1.16
 * [new tag]         2.1.2      -> 2.1.2
 * [new tag]         2.1.3      -> 2.1.3
 * [new tag]         2.1.4      -> 2.1.4
 * [new tag]         2.1.5      -> 2.1.5
 * [new tag]         2.1.6      -> 2.1.6
 * [new tag]         2.1.7      -> 2.1.7
 * [new tag]         2.1.8      -> 2.1.8
 * [new tag]         2.1.9      -> 2.1.9
 * [new tag]         2.2.0      -> 2.2.0
 * [new tag]         2.2.1      -> 2.2.1
 * [new tag]         2.2.2      -> 2.2.2
 * [new tag]         2.2.3      -> 2.2.3
 * [new tag]         2.2.4      -> 2.2.4
 * [new tag]         2.2.5      -> 2.2.5
 * [new tag]         2.2.6      -> 2.2.6
HEAD is now at 6a42a66 Merge pull request #7047 from iMichka/shebang
==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/portable-ruby-2.6.3.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.6.3.x86_64_linux.bottle.tar.gz
==> Tapping homebrew/core
Cloning into '/home/*******/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (328/328), done.
remote: Compressing objects: 100% (211/211), done.
remote: Total 820942 (delta 196), reused 190 (delta 117), pack-reused 820614
Receiving objects: 100% (820942/820942), 299.37 MiB | 24.36 MiB/s, done.
Resolving deltas: 100% (557585/557585), done.
Tapped 2 commands and 4972 formulae (5,234 files, 330.3MB).
==> Installing dependencies for curl: patchelf, m4, gmp, mpfr, libmpc, isl@0.18, zlib, binutils, linux-headers, glibc, gcc, pkg-config and openssl@1.1
==> Installing curl dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.10.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/405227c46362964d2bc2e9ff6428fe082dff4dbd3a4b0b29453743f71923304b--patchelf-0.10.x86_64_linux.bottle.tar.gz
==> Pouring patchelf-0.10.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/patchelf/0.10: 8 files, 873.5KB
==> Installing curl dependency: m4
==> Downloading https://linuxbrew.bintray.com/bottles/m4-1.4.18.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/9fbd4721316274995db37b5f92441b550d09bd131339ecc447377ee886970363--m4-1.4.18.x86_64_linux.bottle.tar.gz
==> Pouring m4-1.4.18.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/m4/1.4.18: 13 files, 1.1MB
==> Installing curl dependency: gmp
==> Downloading https://linuxbrew.bintray.com/bottles/gmp-6.2.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/0bdf02541fafcf4086bb1c8cdb102c7759064428ae49a79b808ebf83cce490d1--gmp-6.2.0.x86_64_linux.bottle.tar.gz
==> Pouring gmp-6.2.0.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/gmp/6.2.0: 23 files, 3.9MB
==> Installing curl dependency: mpfr
==> Downloading https://linuxbrew.bintray.com/bottles/mpfr-4.0.2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/e1cafd8261512613dd2c8f348649b4ab6654c6290ad7be540d19c6cccd56acfc--mpfr-4.0.2.x86_64_linux.bottle.tar.gz
==> Pouring mpfr-4.0.2.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/mpfr/4.0.2: 29 files, 5.2MB
==> Installing curl dependency: libmpc
==> Downloading https://linuxbrew.bintray.com/bottles/libmpc-1.1.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/366984cb086372edd145a2d6ac5a96b80ce5c6b2d77626722231ebf4a55de9e8--libmpc-1.1.0.x86_64_linux.bottle.tar.gz
==> Pouring libmpc-1.1.0.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/libmpc/1.1.0: 13 files, 1.5MB
==> Installing curl dependency: isl@0.18
==> Downloading https://linuxbrew.bintray.com/bottles/isl@0.18-0.18.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/ac5bbc01c5aa0b49aa7415c5930ccd8b81a1329b7da248911faf2e06c128ba9c--isl@0.18-0.18.x86_64_linux.bottle.tar.gz
==> Pouring isl@0.18-0.18.x86_64_linux.bottle.tar.gz
==> Caveats
isl@0.18 is keg-only, which means it was not symlinked into /home/*******/.linuxbrew,
because this is an alternate version of another formula.

For compilers to find isl@0.18 you may need to set:
  export LDFLAGS="-L/home/*******/.linuxbrew/opt/isl@0.18/lib"
  export CPPFLAGS="-I/home/*******/.linuxbrew/opt/isl@0.18/include"

For pkg-config to find isl@0.18 you may need to set:
  export PKG_CONFIG_PATH="/home/*******/.linuxbrew/opt/isl@0.18/lib/pkgconfig"

==> Summary
🍺  /home/*******/.linuxbrew/Cellar/isl@0.18/0.18: 81 files, 6.4MB
==> Installing curl dependency: zlib
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/e26d7f94e9190e27f35a0ca17586414d88d5bb82ae7927206a18556eab619109--zlib-1.2.11.x86_64_linux.bottle.tar.gz
==> Pouring zlib-1.2.11.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/zlib/1.2.11: 12 files, 392KB
==> Installing curl dependency: binutils
==> Downloading https://linuxbrew.bintray.com/bottles/binutils-2.34.x86_64_linux.bottle.1.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/89689a109fb683160a75fad3a6b3d8a96155e50b37de5ccc3e9f15155d605b93--binutils-2.34.x86_64_linux.bottle.1.tar.gz
==> Pouring binutils-2.34.x86_64_linux.bottle.1.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/binutils/2.34: 4,665 files, 279.8MB
==> Installing curl dependency: linux-headers
==> Downloading https://linuxbrew.bintray.com/bottles/linux-headers-4.4.80.x86_64_linux.bottle.t
Already downloaded: /home/*******/.cache/Homebrew/downloads/2dfc91a92fc1bd00ed90bcf9ec0b1649d3fd5c40a90b7589ae1c017713f6958d--linux-headers-4.4.80.x86_64_linux.bottle.tar.gz
==> Pouring linux-headers-4.4.80.x86_64_linux.bottle.tar.gz
🍺  /home/*******/.linuxbrew/Cellar/linux-headers/4.4.80: 772 files, 3.5MB
==> Installing curl dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/3c17421daad583cfd4fad587b8e1260f19385344f309d7ae11e0c2bb6b75d801--glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/
Last 15 lines from /home/*******/.cache/Homebrew/Logs/glibc/01.configure:
2020-03-02 00:05:31 +0900

../configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/home/*******/.linuxbrew/Cellar/glibc/2.23
--enable-obsolete-rpc
--without-selinux
--with-binutils=/home/*******/.linuxbrew/opt/binutils/bin
--with-headers=/home/*******/.linuxbrew/opt/linux-headers/include

READ THIS: https://docs.brew.sh/Troubleshooting

==> Installing dependencies for git: glibc, gcc, pkg-config, gpatch, ncurses, gettext, bzip2, pcre2, openssl@1.1, curl, libbsd and expat
==> Installing git dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/3c17421daad583cfd4fad587b8e1260f19385344f309d7ae11e0c2bb6b75d801--glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/
Last 15 lines from /home/*******/.cache/Homebrew/Logs/glibc/01.configure:
2020-03-02 00:05:39 +0900

../configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/home/*******/.linuxbrew/Cellar/glibc/2.23
--enable-obsolete-rpc
--without-selinux
--with-binutils=/home/*******/.linuxbrew/opt/binutils/bin
--with-headers=/home/*******/.linuxbrew/opt/linux-headers/include

READ THIS: https://docs.brew.sh/Troubleshooting

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Next steps:
- Install the Homebrew dependencies if you have sudo access:
  Debian, Ubuntu, etc.
    sudo apt-get install build-essential
  Fedora, Red Hat, CentOS, etc.
    sudo yum groupinstall 'Development Tools'
  See https://docs.brew.sh/linux for more information.
- Configure Homebrew in your ~/.bash_profile by running
    echo 'eval $(/home/*******/.linuxbrew/bin/brew shellenv)' >>~/.bash_profile
- Add Homebrew to your PATH
    eval $(/home/*******/.linuxbrew/bin/brew shellenv)
- We recommend that you install GCC by running:
    brew install gcc
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh

And,
$ echo 'eval $(/home/*******/.linuxbrew/bin/brew shellenv)' >>~/.bash_profile
$ eval $(/home/*******/.linuxbrew/bin/brew shellenv)
$ brew install gcc

==> Installing dependencies for curl: glibc, gcc, pkg-config and openssl@1.1
==> Installing curl dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/3c17421daad583cfd4fad587b8e1260f19385344f309d7ae11e0c2bb6b75d801--glibc-2.23.tar.gz
Updating Homebrew...
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/
Last 15 lines from /home/*******/.cache/Homebrew/Logs/glibc/01.configure:
2020-03-02 00:07:48 +0900

../configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/home/*******/.linuxbrew/Cellar/glibc/2.23
--enable-obsolete-rpc
--without-selinux
--with-binutils=/home/*******/.linuxbrew/opt/binutils/bin
--with-headers=/home/*******/.linuxbrew/opt/linux-headers/include

READ THIS: https://docs.brew.sh/Troubleshooting

==> Installing dependencies for git: glibc, gcc, pkg-config, gpatch, ncurses, gettext, bzip2, pcre2, openssl@1.1, curl, libbsd and expat
==> Installing git dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/3c17421daad583cfd4fad587b8e1260f19385344f309d7ae11e0c2bb6b75d801--glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/
Last 15 lines from /home/*******/.cache/Homebrew/Logs/glibc/01.configure:
2020-03-02 00:07:56 +0900

../configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/home/*******/.linuxbrew/Cellar/glibc/2.23
--enable-obsolete-rpc
--without-selinux
--with-binutils=/home/*******/.linuxbrew/opt/binutils/bin
--with-headers=/home/*******/.linuxbrew/opt/linux-headers/include

READ THIS: https://docs.brew.sh/Troubleshooting

==> Installing dependencies for gcc: glibc
==> Installing gcc dependency: glibc
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
Already downloaded: /home/*******/.cache/Homebrew/downloads/3c17421daad583cfd4fad587b8e1260f19385344f309d7ae11e0c2bb6b75d801--glibc-2.23.tar.gz
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/
Last 15 lines from /home/*******/.cache/Homebrew/Logs/glibc/01.configure:
2020-03-02 00:08:06 +0900

../configure
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/home/*******/.linuxbrew/Cellar/glibc/2.23
--enable-obsolete-rpc
--without-selinux
--with-binutils=/home/*******/.linuxbrew/opt/binutils/bin
--with-headers=/home/*******/.linuxbrew/opt/linux-headers/include

READ THIS: https://docs.brew.sh/Troubleshooting

"brew install python3"
If you enter this, you get the same error as above.

**Comment by Bo98** [comment]
For help & support, please go to https://discourse.brew.sh.

If you believe this a genuine bug and not specific to your machine, then open an issue at https://github.com/Homebrew/linuxbrew-core instead. Linux's glibc formula is very different to that on macOS.
