### ISSUE TITLE
Remctl install through brew fails (3.10 no longer accessible, updated to 3.12)

### ISSUE THREAD

**Issue by djh816** [Homebrew/homebrew-core#5092]
Remctl 3.10 is no longer accessible on http://archives.eyrie.org/software/remctl/ and has been updated to 3.12. Keeping the existing .xz archive preference the new URL is http://archives.eyrie.org/software/kerberos/remctl-3.12.tar.xz and the sha256 checksum is 95d890b2bb8abf93ef0c60369ecdd3afdf87d64c8ac1b20162f3121b72e70aab. Manually editing the formula allows install but I figured this should be reported as it should be a quick fix. Thanks!

**Comment by dunn** [comment]
Would you like to try opening a PR?  Take a look at https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by leee** [comment]
Russ Allbery updated remctl to 3.13 just now - I will provide a pull request for the current version.

**Comment by leee** [comment]
@djh816 - I have provided a pull request to update the remctl formula for use of remctl 3.13. You should be able to close this issue now modulo accepted and merged pull request.

@dunn - link appears broken.

**Comment by dunn** [comment]
Yeah, I forgot to update my text snippet. Thanks!

**Comment by djh816** [comment]
Thanks for the tips and the pull request. Closing this issue :)
