### ISSUE TITLE
libquicktime: stable 1.2.4 does not compile with --with-ffmpeg

### ISSUE THREAD

**Issue by kzahedi** [Homebrew/homebrew-core#510]
### Bug reports:

I am trying to compile libquicktime (1.2.4) with

brew install libquicktime --with-ffmpeg

Fresh installation of ffmpeg, x264, libav, libquicktime, etc did not solve the issue. The error message is:
>
Last 15 lines from /Users/zahedi/Library/Logs/Homebrew/libquicktime/02.make:
20 errors generated.
lqt_ffmpeg.c:630:13: error: use of undeclared identifier 'CODEC_ID_INDEO3'; did you mean 'AV_CODEC_ID_INDEO3'?
      .id = CODEC_ID_INDEO3,
            ^~~~~~~~~~~~~~~
            AV_CODEC_ID_INDEO3
/usr/local/Cellar/ffmpeg/3.0.1/include/libavcodec/avcodec.h:135:5: note: 'AV_CODEC_ID_INDEO3' declared here
    AV_CODEC_ID_INDEO3,
    ^
make[3]: *** [video.lo] Error 1
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [lqt_ffmpeg.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
<

`brew gist-logs libquicktime`
https://gist.github.com/bbe6433743a10c55a2a1d380e63073c0

A quick research on the internet revealed, that (at least on debian) this is solved in the newest version of libquicktime (1.2.4-5)

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739325

**Comment by ilovezfs** [comment]
Yup, issue reproduced. It was broken by ffmpeg 3.0

I smell :skull: or a vendored ffmpeg 2.8.6

**Comment by ilovezfs** [comment]
Here's the ffmpeg 3 patch from Arch.
https://projects.archlinux.org/svntogit/community.git/tree/trunk/libquicktime-ffmpeg3.patch?h=packages/libquicktime

**Comment by kzahedi** [comment]
Worked like a charm. Thanks a million!

**Comment by ilovezfs** [comment]
You're welcome!
