### ISSUE TITLE
update os 10,12 and xcode8 don't brew update 1.0.0

### ISSUE THREAD

**Issue by CoderBOBO** [Homebrew/homebrew-core#5113]
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
How to solve it？

**Comment by ilovezfs** [comment]
I think you are affected by https://twitter.com/MacHomebrew/status/763686348041641984

**Comment by zmwangx** [comment]
Closing due to lack of info and *a* solution provided. Shout if you have more problems.
