### ISSUE TITLE
openjdk@11/11.0.6 symlink libjli.dylib broken

### ISSUE THREAD

**Issue by pteyssier** [Homebrew/homebrew-core#51150]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Error: No logs.
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I upgraded my openjdk@11 to 11.0.6  with "brew upgrade"

## What happened (include command output)
brew upgrade command was succesfull but...
My application based on Eclipse could not start anymore with the error "Failed to create the Java Virtual Machine".
More precisely, the error was:
Error: could not find libjava.dylib
Failed to GetJREPath()

After investigation I found out that the symlink for libjli.dylib was broken, to fix it, the solution is:
sudo ln -sf /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home/lib/jli/libjli.dylib /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/MacOS

<details>
  <summary>Command output</summary>
  <pre>

- brew config

HOMEBREW_VERSION: 2.2.9-2-g01d5e53
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01d5e53120843327de4cf8d3ee18b55f01a3bce8
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bc1307fbb741d4b711c1957fdb0e02dc8e8164a5
Core tap last commit: 19 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.6, 1.8.0_231, 1.8.0_151
macOS: 10.14.6-x86_64
CLT: 11.0.0.0.1.1559496560
Xcode: N/A

- brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The following directories do not exist:
/usr/local/Frameworks
/usr/local/sbin

You should create these directories and change their ownership to your account.
  sudo mkdir -p /usr/local/Frameworks /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/sbin
  </pre>
</details>

## What you expected to happen

I expect the "Caveats" part from formula to mention also to type:
sudo ln -sf /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home/lib/jli/libjli.dylib /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/MacOS

## Step-by-step reproduction instructions (by running `brew install` commands)

1)brew install openjdk@11
2)Download Talend Open Studio (Eclipse based app, so I think it can be reproduced with Eclipse too) and launch it.

I also reproduced and fixed on a coworkers laptop.

**Comment by Bo98** [comment]
This appears to be an upstream bug: https://bugs.openjdk.java.net/browse/JDK-8238225.

I will have a look and see if the backported patch works.

**Comment by bayandin** [comment]
Will be fixed in 11.0.7 release: https://bugs.openjdk.java.net/browse/JDK-8238772

**Comment by bayandin** [comment]
Should be fixed by https://github.com/Homebrew/homebrew-core/pull/53221

**Comment by bayandin** [comment]
I'm closing the issue. @pteyssier feel free to reopen it if openjdk@11 update to 11.0.7 won't help
