### ISSUE TITLE
rpm "find-provides" is missing

### ISSUE THREAD

**Issue by RangerRick** [Homebrew/homebrew-core#5116]
### Bug reports:

Using RPM to build a package, it tries to run `find-provides` but it does not exist:

```
Processing files: opennms-minion-19.0.0-0.20160921.1.noarch
Processing files: opennms-minion-container-19.0.0-0.20160921.1.noarch
error: Couldn't exec /usr/local/Cellar/rpm/5.4.15/lib/rpm/find-provides: No such file or directory
getOutputFrom(): Broken pipe
failed to build tools/packages/minion/minion.spec
```

The only `find-provides` file that exists in the brew container is `/usr/local/Cellar/rpm/5.4.15/lib/rpm/find-provides.perl` and it is a single-line shell script that contains:

``` sh
#!/bin/sh

exec /usr/lib/rpm/find-provides
```

...which does not exist.  :)

`brew gist-logs rpm` just prints:

```
Error: No logs.
```

**Comment by RangerRick** [comment]
I tried changing the RPM formula to 5.4.17, but it looks like there are some compilation issues that need patching.

**Comment by afb** [comment]
@RangerRick : there were some work done (for 5.4.16) in #737 if you want to continue with it...

The find-provides for Darwin haven't been kept up-to-date, and the internal scripts are mostly for ELF (not Mach-O). I think the "best" external scripts for find-requires/find-provides come from the Japanese RPM distribution "[OS X WorkShop](http://www.bach-phys.ritsumei.ac.jp/OSXWS/)", but the internal generator is the default in rpm5. You would also want to provide patched `bash` shell, with --rpm-provides functionality.

**Comment by afb** [comment]
There's an updated formula for 5.4.17 in 7a3b977bb7ee8efee522cb195947db1dae1abc93 now.
Requires upgrading berkeley-db to 6.2 (b747f11cb0a6a22f1c2ae5545a2e1faf7901145b) first...

But it still looks you have edited your rpmbuild macros ?
And if you do that, then *you* need to provide the scripts.

```
#
# Use internal dependency generator rather than external helpers?
# 0 - Use external generator
# 1 - Use internal generator if available
# 2 - Use __scriptlet_requires to process scriptlet dependencies
%_use_internal_dependency_generator	1

```

The old ones are here: (and in the build folder / autodeps)
http://rpm5.org/cvs/fileview?f=rpm/autodeps/darwin.prov
http://rpm5.org/cvs/fileview?f=rpm/autodeps/darwin.req

Do they still work ? If so, they could be installed by rpm too:
    `(lib/"rpm/find-provides").install "autodeps/darwin.prov"`
    `(lib/"rpm/find-requires").install "autodeps/darwin.req"`

**Comment by MikeMcQuaid** [comment]
Closing due to some unanswered questions. We'd consider accepting a PR to upgrade/improve this.
