### ISSUE TITLE
awscli fails to reinstall/unistall due to root user directory ownership

### ISSUE THREAD

**Issue by Me-ion** [Homebrew/homebrew-core#51181]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Tried to reinstall/uninstall awscli

## What happened (include command output)

Run command `brew reinstall awscli` or `brew uninstall awscli`.
Commands fail with error message:

<details>
  <summary>Command output</summary>
  <pre>

  Error: Could not remove awscli backup keg! Do so manually:
  sudo rm -rf /usr/local/Cellar/awscli/2.0.0.reinstall

  </pre>
</details>

## What you expected to happen

Commands should work

## Step-by-step reproduction instructions (by running `brew install` commands)

This is due to `__pycache__` directory being owned by root.
```
mymachine:~ myuser$ ls -la /usr/local/Cellar/awscli/2.0.0/libexec/lib/python3.8/
total 72
drwxr-xr-x  59 myuser  staff   1888 Mar  5 01:48 .
drwxr-xr-x   3 myuser  staff     96 Feb 10 10:36 ..
lrwxr-xr-x   1 myuser  staff     98 Feb 10 10:36 LICENSE.txt -> ../../../../../python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/LICENSE.txt
lrwxr-xr-x   1 myuser  staff    100 Feb 10 10:36 __future__.py -> ../../../../../python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/__future__.py
drwxr-xr-x  42 root  staff   1344 Mar  5 01:48 __pycache__
lrwxr-xr-x   1 myuser  staff    101 Feb 10 10:36 _bootlocale.py
.........
```

## brew config output

```
mymachine:~ myuser$ brew config
HOMEBREW_VERSION: 2.2.9-6-g42477a1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 42477a1aaa7276aad17f4196e435926ecec366ca
Last commit: 16 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: eb1fdb84e2924289bcc8c85ee45081bf83dc024d
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.1, 1.8.0_232
macOS: 10.15.3-x86_64
CLT: 11.0.33.17
Xcode: 11.3.1
```

**Comment by Bo98** [comment]
Could it be that `awscli` was run as root before?

**Comment by Me-ion** [comment]
This happens consistently on "fresh" installs

**Comment by SMillerDev** [comment]
Homebrew never has root access after the initial install and never will. If something is owned by root you did something manually that caused this.
