### ISSUE TITLE
bpython failed to build on 10.11.6

### ISSUE THREAD

**Issue by bams** [Homebrew/homebrew-core#5124]
https://gist.github.com/1a2a6544667a96698561160bd63fcabc

here is the error when install from pip:
  ----------------------------------------
 Failed building wheel for bpython
  Running setup.py clean for bpython
Failed to build bpython
Installing collected packages: bpython
  Running setup.py install for bpython ... error
    Complete output from command /usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/wy/fqjdhnb55_3b756_89mqfm0m0000gn/T/pip-build-Drhw6j/bpython/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/wy/fqjdhnb55_3b756_89mqfm0m0000gn/T/pip-HCKFpk-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_sphinx_man
    error: error in 'build_dir' option: 'build' does not exist or is not a directory
  ----------------------------------------

**Comment by zmwangx** [comment]
Unless you can prove this only occurs with brewed python (shout if you can), we do not provide support for upstream software.

**Comment by zmwangx** [comment]
(Also, I can't reproduce.)
