### ISSUE TITLE
sbcl on macOS Sierra

### ISSUE THREAD

**Issue by egorenar** [Homebrew/homebrew-core#5125]
Hi,

sbcl cannot be built on macOS Sierra.
I tried brew update and doctor, it doesn't help.

brew gist-logs:
https://gist.github.com/anonymous/f5a0a21779a7d52ede7b46c53704036a

error message:
--------------------------

==> ./make.sh --prefix=/usr/local/Cellar/sbcl/1.3.9 --xc-host=/private/tmp/sbcl--bootstrap64-20160922-52658-heaser/sbcl-1.2.11-x86-
Last 15 lines from /Users/egorenar/Library/Logs/Homebrew/sbcl/01.make.sh:
//header files match between first and second GENESIS -- good

real	1m40.728s
user	1m33.572s
sys	0m6.714s
//entering make-target-2.sh
//doing warm init - compilation phase
This is SBCL 1.3.9, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
make-target-2.sh: line 48: 53333 Killed: 9               ./src/runtime/sbcl --core output/cold-sbcl.core --lose-on-corruption --no-sysinit --no-userinit < make-target-2.lisp

Regards

**Comment by dunn** [comment]
OK, I'm seeing the same thing.  If you have the time, could you check upstream to see if this is an issue with SBCL itself?

**Comment by egorenar** [comment]
The problems seems to be with Xcode 8.

https://trac.macports.org/changeset/151301
https://echelog.com/logs/browse/macports/1472940000

**Comment by dunn** [comment]
Doesn't looks like MacPorts bothered to report the issue; if you could that'd be awesome, otherwise I'll get to it when I can.

**Comment by egorenar** [comment]
upstream is already fixed.

**Comment by ilovezfs** [comment]
that's good news. perhaps you can encourage them to tag a new release then.

**Comment by egorenar** [comment]
it's planned for the end of the next week, i'll get back then.

**Comment by dunn** [comment]
Thank you!

**Comment by cielavenir** [comment]
I used `export SBCL_MACOSX_VERSION_MIN=10.5; brew install sbcl`...

**Comment by egorenar** [comment]
unfortunately,
export SBCL_MACOSX_VERSION_MIN=10.5
doesn't work for me.

**Comment by Juev** [comment]
Is it strange, because export ... =10.5 work for me

**Comment by egorenar** [comment]
cleanup and install again did it for me too now :)
Thanks for the hint.

**Comment by dunn** [comment]
I don't have Sierra on my personal computer, so if anyone wants to try applying this upstream patch, let me know if SBCL builds:
```diff
diff --git a/Formula/sbcl.rb b/Formula/sbcl.rb
index f4edb1f..e355b39 100644
--- a/Formula/sbcl.rb
+++ b/Formula/sbcl.rb
@@ -1,11 +1,18 @@
 class Sbcl < Formula
   desc "Steel Bank Common Lisp system"
   homepage "http://www.sbcl.org/"
-  url "https://downloads.sourceforge.net/project/sbcl/sbcl/1.3.9/sbcl-1.3.9-source.tar.bz2"
-  sha256 "af0f09d4379113dfd5aa255279cb3df9cb9cac0bcd65369cc43dd857ca51de6e"
-
   head "http://git.code.sf.net/p/sbcl/sbcl", :using => :git

+  stable do
+    url "https://downloads.sourceforge.net/project/sbcl/sbcl/1.3.9/sbcl-1.3.9-source.tar.bz2"
+    sha256 "af0f09d4379113dfd5aa255279cb3df9cb9cac0bcd65369cc43dd857ca51de6e"
+
+    patch do
+      url "https://github.com/dunn/formula-patches/raw/73068cd8d00e03cc09497dd4b2ae1be0dd4f0fa1/sbcl/patch-Fix-building-with-the-latest-Xcode-on-OSX.diff"
+      sha256 "de550c3deb07bfe9eef8e777fd814c259dc9b9e26d331c70f75613dcfab390e3"
+    end
+  end
+
   bottle do
     sha256 "1ff2ac16bbbbee191454e73048c05bee6707b680a787b1521874114a05a8f82f" => :el_capitan
     sha256 "bf4c061b3d038cdc96d3d6fa1dcb5af1e19554b97e7af3f34916fb7d980b1f88" => :yosemite

**Comment by egorenar** [comment]
It fails with the following message

```
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/sbcl/sbcl/1.3.9/sbcl-1.3.9-source.tar.bz2
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl-1.3.9.tar.bz2
==> Downloading https://github.com/dunn/formula-patches/raw/73068cd8d00e03cc09497dd4b2ae1be0dd4f0fa1/sbcl/patch-Fix-building-with-the-latest-Xcode-on-OSX
==> Downloading from https://raw.githubusercontent.com/dunn/formula-patches/73068cd8d00e03cc09497dd4b2ae1be0dd4f0fa1/sbcl/patch-Fix-building-with-the-lat
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-base-target-features.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-e101d7dc015ea71c15a58a5c54777283c89070bf7801a13cd3b3a1969a6d8b75.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-make-doc.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-7c21c89fd6ec022d4f17670c3253bd33a4ac2784744e4c899c32fbe27203d87e.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-posix-tests.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-06908aaa94ba82447d64cf15eb8e011ac4c2ae4c3050b19b36316f64992ee21d.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-use-mach-exception-handler.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-089b8fdc576a9a32da0b2cdf2b7b2d8bfebf3d542ac567f1cb06f19c03eaf57d.diff
==> Patching
==> Applying patch-Fix-building-with-the-latest-Xcode-on-OSX.diff
patching file NEWS
Hunk #1 FAILED at 10.
1 out of 1 hunk FAILED -- saving rejects to file NEWS.rej
patching file src/runtime/darwin-os.c
patching file src/runtime/thread.h
patching file src/runtime/x86-64-darwin-os.c
patching file src/runtime/x86-darwin-os.c
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/sbcl--patch-20160925-46859-1y162pc/patch-Fix-building-with-the-latest-Xcode-on-OSX.diff
```

**Comment by egorenar** [comment]
It is odd but

the trick `export SBCL_MACOSX_VERSION_MIN=10.5; brew install sbcl` doesn't not always work.

**Comment by dunn** [comment]
Ugh, sorry. That's something I could have tested locally.  This patch block should apply:
```ruby
    patch do
      url "https://github.com/dunn/formula-patches/raw/dd3a4309ef9e892df341b30cec394b7cf3a31834/sbcl/patch-Fix-building-with-the-latest-Xcode-on-OSX.diff"
      sha256 "abb4ec2ff353d4c57e0e1d4b0421986c634a7be5977b18fa4229b9894eab3f3e"
    end

**Comment by egorenar** [comment]
The new patch worked but the installation just hangs now.
Or maybe just taking too long, but i waited quite long and then stopped the installation.

`
$ brew install sbcl
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/sbcl/sbcl/1.3.9/sbcl-1.3.9-source.tar.bz2
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl-1.3.9.tar.bz2
==> Downloading https://github.com/dunn/formula-patches/raw/dd3a4309ef9e892df341b30cec394b7cf3a31834/sbcl/patch-Fix-building-with-the-latest-Xcode-on-OSX
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-abb4ec2ff353d4c57e0e1d4b0421986c634a7be5977b18fa4229b9894eab3f3e.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-base-target-features.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-e101d7dc015ea71c15a58a5c54777283c89070bf7801a13cd3b3a1969a6d8b75.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-make-doc.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-7c21c89fd6ec022d4f17670c3253bd33a4ac2784744e4c899c32fbe27203d87e.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-posix-tests.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-06908aaa94ba82447d64cf15eb8e011ac4c2ae4c3050b19b36316f64992ee21d.diff
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/c5ffdb11/sbcl/patch-use-mach-exception-handler.diff
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--patch-089b8fdc576a9a32da0b2cdf2b7b2d8bfebf3d542ac567f1cb06f19c03eaf57d.diff
==> Patching
==> Applying patch-Fix-building-with-the-latest-Xcode-on-OSX.diff
patching file src/runtime/darwin-os.c
patching file src/runtime/thread.h
patching file src/runtime/x86-64-darwin-os.c
patching file src/runtime/x86-darwin-os.c
==> Applying patch-base-target-features.diff
patching file base-target-features.lisp-expr
Hunk #1 succeeded at 230 with fuzz 2 (offset 11 lines).
Hunk #2 succeeded at 477 (offset 71 lines).
==> Applying patch-make-doc.diff
patching file doc/make-doc.sh
==> Applying patch-posix-tests.diff
patching file contrib/sb-posix/posix-tests.lisp
Hunk #2 succeeded at 168 with fuzz 1 (offset 5 lines).
Hunk #3 succeeded at 341 (offset 13 lines).
Hunk #4 succeeded at 357 (offset 12 lines).
Hunk #5 succeeded at 540 (offset 29 lines).
Hunk #6 succeeded at 714 (offset 46 lines).
==> Applying patch-use-mach-exception-handler.diff
patching file customize-target-features.lisp
==> Downloading https://downloads.sourceforge.net/project/sbcl/sbcl/1.2.11/sbcl-1.2.11-x86-64-darwin-binary.tar.bz2
Already downloaded: /Users/egorenar/Library/Caches/Homebrew/sbcl--bootstrap64-1.2.11.tar.bz2
==> ./make.sh --prefix=/usr/local/Cellar/sbcl/1.3.9 --xc-host=/private/tmp/sbcl--bootstrap64-20160925-61623-1u5x4nx/sbcl-1.2.11-x86-64-darwin/src/runtime
`

`
./src/runtime/sbcl --core output/cold-sbcl.core --lose-on-corruption --no-sysinit --no-userinit
`

**Comment by ssunday** [comment]
I am also experiencing the same problem as @egorenar. I did a cleanup and update but it hangs on the `.make.sh` portion. I've stopped the installation because I believed it was hanging (which seems to be the case.) 

Using `export SBCL_MACOSX_VERSION_MIN=10.5; brew install sbcl` gets me to this after the `.make.sh` line:
```
; B2:       0F0B10           BREAK 16                         ; Invalid argument count trap
; B5: L6:   6A60             PUSH 96
; B7:       BEC0691100       MOV ESI, 1141184                 ; alloc_tramp
; BC:       FFD6             CALL RSI
; BE:       415B             POP R11
; C0:       EB9C             JMP L1
; C2: L7:   6A10             PUSH 16
; C4:       B9C0691100       MOV ECX, 1141184                 ; alloc_tramp
; C9:       FFD1             CALL RCX
; CB:       415B             POP R11
; CD:       EBBF             JMP L3
*
WARNING! Some of the contrib modules did not build successfully or pass
their self-tests. Failed contribs:"
  sb-concurrency

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
sbcl on macOS Sierra https://github.com/Homebrew/homebrew-core/issues/5125
```

Which basically tells me to come here, which I already was. But here I am! 

Seems like `sb-concurrency` was what did the install in, but this is my first time installing `sbcl` from `brew`. My other computer had it installed from source, I think, and has macOS Sierra installed. I will try to verify if SBCL functions on that computer when I get the chance.

**Comment by dunn** [comment]
Thanks for trying!  My guess is that there are more changes required than the one commit I backported; looks like we'll have to wait until the release.

**Comment by kubark42** [comment]
`export SBCL_MACOSX_VERSION_MIN=10.5; brew install sbcl` worked for me, but I had to wait >3 minutes.

```
$> export SBCL_MACOSX_VERSION_MIN=10.5; brew install sbcl
.
.
.
./make.sh --prefix=/usr/local/Cellar/sbcl/1.3.9 --xc-host=/private/tmp/sbcl-
==> sh install.sh
🍺  /usr/local/Cellar/sbcl/1.3.9: 1,313 files, 69.2M, built in 3 minutes 27 seconds
$>
```

**Comment by egorenar** [comment]
SBCL 1.3.10 is up.

http://downloads.sourceforge.net/project/sbcl/sbcl/1.3.10/sbcl-1.3.10-source.tar.bz2

**Comment by dunn** [comment]
And https://github.com/Homebrew/homebrew-core/pull/5433 is merged! Let us know if anything doesn't seem to be working right.

**Comment by egorenar** [comment]
Thanks, it works.

**Comment by ssunday** [comment]
Works! Thanks!
