### ISSUE TITLE
Where is python2?

### ISSUE THREAD

**Issue by ah1102** [Homebrew/homebrew-core#51268]
Where to fсk python2? Why, when I give the brew install python command, python3 is installed, not python2. Developers are you stoned there? Why is separation so difficult?

**Comment by Bo98** [comment]
> Where to fсk python2?

I recommend not having intercourse with EOL software.

**Comment by ah1102** [comment]
And I recommend you quit! There are many more where python2 is used and only some modules are installed under it, and you deleted it from the repository. Do you think at all with your head or do you have a hamburger head place?

**Comment by ah1102** [comment]
And who attributed it to end-of-life? You yourself?

**Comment by Bo98** [comment]
https://www.python.org/doc/sunset-python-2/

**Comment by SMillerDev** [comment]
Please read our code of conduct and adjust your interactions accordingly.

https://github.com/Homebrew/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ah1102** [comment]
You have an unfinished raw product with some problems. What can be your attitude? Treating users like shit.
