### ISSUE TITLE
brew install luajit --HEAD fails on macOS Catalina

### ISSUE THREAD

**Issue by jnozsc** [Homebrew/homebrew-core#51272]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install luajit --HEAD` on macOS 10.15.3

## What happened (include command output)

fail to install

here is the link from `brew gist-logs` https://gist.github.com/jnozsc/a6a67a2a1929d9196c4f32a4092813be

## What you expected to happen

install successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install luajit --HEAD`

**Comment by jnozsc** [comment]
btw `brew install luajit` works fine on my local, just for some investigation, I want to install luajit version 2.1 by add `--HEAD` to the install command, and it fails

**Comment by issyl0** [comment]
We don't officially support HEAD builds. If you can figure out how to fix it, either raise a PR upstream to fix the bug and ask for a new release, or a PR here to include the fixes in an `if build.head?` conditional.

For official support, I'd suggest installing the stable release of `luajit`.

**Comment by Bo98** [comment]
As some guidance:

Your build failed with:
```
CLT: 11.0.33.8
Xcode: N/A
```

yet `brew config` seems to report:
```
CLT: 11.3.1.0.1.1576735732
Xcode: N/A
```

There are known compiler bugs in Xcode & CLT 11.0-11.2 on Catalina, which may be the cause of your issue. Can you try make sure 11.3 is installed?

**Comment by jnozsc** [comment]
Thank Bo98

After reinstall `xcode-select`, now I can install --HEAD, there must be something mess with my local environment 

Thanks so much
