### ISSUE TITLE
antlr is not in the CLASSPATH

### ISSUE THREAD

**Issue by ricglz0201** [Homebrew/homebrew-core#51368]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install antlr to use it without having to set-up the `CLASSPATH`, `antlr4` y `grun`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
    brew install antlr
    echo $CLASSPATH
  </pre>
</details>

## What you expected to happen

That the $CLASSPATH was shown

## Step-by-step reproduction instructions (by running `brew install` commands)

<details>
  <summary>Command output</summary>
  <pre>
    brew install antlr
    echo $CLASSPATH
  </pre>
</details>

**Comment by SMillerDev** [comment]
Homebrew will never edit environment variables. Why would you need the classpath to be set by the install?

**Comment by ricglz0201** [comment]
I thought that it would be a more direct process than installing it separately and still adding. I also thought that it would be possible because in the [repo](https://github.com/Homebrew/homebrew-core/blob/master/Formula/antlr.rb) it seems to be modifying the `CLASSPATH`

**Comment by SMillerDev** [comment]
It does add it to the classpath. But only while running antlr. It won't modify the global environment variable.

**Comment by ricglz0201** [comment]
I see, thank you
