### ISSUE TITLE
brew upgrade openapi-generator breaks minikube

### ISSUE THREAD

**Issue by JavascriptMick** [Homebrew/homebrew-core#51376]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

upgrade openapi-generator to latest version because my current version was out of date.

## What happened (include command output)

I ran.

brew upgrade openapi-generator

openapi-generator was upgraded but minikube was also unexpectedly upgraded to a version that was broken per this issue (https://github.com/kubernetes/minikube/issues/6943).  I am now working through resolution of minikube issues.

Note that I was unable to capture the logs at the point where determination was made to upgrade minikube.

<details>
  <summary>brew upgrade openapi-generator</summary>
  <pre>

brew gist-logs minikube
Error: No logs.
brew gist-logs openapi-generator
You can create a new personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile

GitHub User: 
------------------------------------------------------
brew info minikube
minikube: stable 1.8.1 (bottled), HEAD
Run a Kubernetes cluster locally
https://minikube.sigs.k8s.io/
/usr/local/Cellar/minikube/1.8.1 (8 files, 60MB) *
  Poured from bottle on 2020-03-09 at 16:53:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/minikube.rb
==> Dependencies
Build: go ✘, go-bindata ✘
Required: kubernetes-cli ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
------------------------------------------------------
brew info openapi-generator
openapi-generator: stable 4.2.3, HEAD
Generate clients, server & docs from an OpenAPI spec (v2, v3)
https://openapi-generator.tech/
/usr/local/Cellar/openapi-generator/4.2.3_1 (4 files, 20.9MB) *
  Built from source on 2020-03-09 at 16:54:16
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openapi-generator.rb
==> Dependencies
Required: openjdk ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 1,966 (30 days), 4,665 (90 days), 17,320 (365 days)
install-on-request: 1,962 (30 days), 4,657 (90 days), 17,305 (365 days)
build-error: 0 (30 days)

  </pre>
</details>

## What you expected to happen

openapi-generator would be upgraded

## Step-by-step reproduction instructions (by running `brew install` commands)

step 1) brew upgrade openapi-generator

**Comment by SMillerDev** [comment]
There must be a shared dependency somewhere. Either way "I updated to a release that upstream broke" is not really something that can be fixed by brew.
