### ISSUE TITLE
Install node 6.6 failed in macOS sierra

### ISSUE THREAD

**Issue by nealsun** [Homebrew/homebrew-core#5145]
Still install node 6.6 failed, macOS sierra and xCode 8 is up to date.

```
==> make install
Last 15 lines from /Users/sunweirong/Library/Logs/Homebrew/node/02.make:
       ^
../deps/openssl/asm/x64-elf-gas/aes/aesni-sha256-x86_64.s:4002:1: error: unknown directive
.size aesni_cbc_sha256_enc_avx2,.-aesni_cbc_sha256_enc_avx2
^
../deps/openssl/asm/x64-elf-gas/aes/aesni-sha256-x86_64.s:4003:1: error: unknown directive
.type aesni_cbc_sha256_enc_shaext,@function
^
../deps/openssl/asm/x64-elf-gas/aes/aesni-sha256-x86_64.s:4004:8: error: invalid alignment value
.align 32
       ^
../deps/openssl/asm/x64-elf-gas/aes/aesni-sha256-x86_64.s:4354:1: error: unknown directive
.size aesni_cbc_sha256_enc_shaext,.-aesni_cbc_sha256_enc_shaext
^
make[1]: *** [/private/tmp/node-20160923-13014-ypqea/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/asm/x64-elf-gas/aes/aesni-sha256-x86_64.o] Error 1
make: *** [node] Error 2
```
### Bug reports:

https://gist.github.com/f3c09782e018f61f34b5bd59eb3ea7b9

**Comment by ahankinson** [comment]
You need to update your XCode command-line tools. `xcode-select --install`

**Comment by stpdenis** [comment]
same issue, Sierra clean install
`==> make install
Last 15 lines from /Users/denis/Library/Logs/Homebrew/node/02.make:
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_dyn.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_dyn.o ../deps/openssl/openssl/crypto/engine/eng_dyn.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_err.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_err.o ../deps/openssl/openssl/crypto/engine/eng_err.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_fat.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_fat.o ../deps/openssl/openssl/crypto/engine/eng_fat.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_init.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_init.o ../deps/openssl/openssl/crypto/engine/eng_init.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_lib.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_lib.o ../deps/openssl/openssl/crypto/engine/eng_lib.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_list.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_list.o ../deps/openssl/openssl/crypto/engine/eng_list.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_openssl.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_openssl.o ../deps/openssl/openssl/crypto/engine/eng_openssl.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_pkey.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_pkey.o ../deps/openssl/openssl/crypto/engine/eng_pkey.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_rdrand.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_rdrand.o ../deps/openssl/openssl/crypto/engine/eng_rdrand.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_table.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/eng_table.o ../deps/openssl/openssl/crypto/engine/eng_table.c
  clang '-D_REENTRANT' '-DPURIFY' '-DOPENSSL_NO_COMP' '-DOPENSSL_NO_SSL3' '-DOPENSSL_NO_HEARTBEATS' '-DENGINESDIR="/dev/null"' '-DTERMIOS' '-DOPENSSLDIR="/System/Library/OpenSSL/"' '-D_DARWIN_USE_64_BIT_INODE=1' '-DL_ENDIAN' '-DAES_ASM' '-DCPUID_ASM' '-DOPENSSL_BN_ASM_MONT' '-DOPENSSL_CPUID_OBJ' '-DSHA1_ASM' '-DSHA256_ASM' '-DSHA512_ASM' '-DGHASH_ASM' '-DVPAES_ASM' '-DBN_ASM' '-DBF_ASM' '-DBNCO_ASM' '-DDES_ASM' '-DLIB_BN_ASM' '-DMD5_ASM' '-DOPENSSL_BN_ASM' '-DRIP_ASM' '-DRMD160_ASM' '-DWHIRLPOOL_ASM' '-DWP_ASM' '-DOPENSSL_BN_ASM_MONT5' '-DOPENSSL_BN_ASM_GF2m' '-DOPENSSL_IA32_SSE2' '-DBSAES_ASM' '-DDSO_DLFCN' '-DHAVE_DLFCN_H' -I../deps/openssl -I../deps/openssl/openssl -I../deps/openssl/openssl/crypto -I../deps/openssl/openssl/crypto/asn1 -I../deps/openssl/openssl/crypto/evp -I../deps/openssl/openssl/crypto/md2 -I../deps/openssl/openssl/crypto/modes -I../deps/openssl/openssl/crypto/store -I../deps/openssl/openssl/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/.deps//private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/tb_asnmth.o.d.raw   -c -o /private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/tb_asnmth.o ../deps/openssl/openssl/crypto/engine/tb_asnmth.c
sh: /usr/local/opt/pkg-config/bin/touch: No such file or directory
make[1]: *** [/private/tmp/node-20160924-6758-5d2ch2/node-v6.6.0/out/Release/obj.target/openssl/deps/openssl/openssl/crypto/engine/tb_asnmth.o] Error 127
make[1]: *** Waiting for unfinished jobs....
make: *** [node] Error 2`

**Comment by nico29** [comment]
Same issue. Also I installed openssl but still no luck. @stpdenis Did you do something special after having openssl installed? Thanks.

**Comment by stpdenis** [comment]
@nico29 no, nothing special:
brew install node --> ERROR
brew install openssl --> SUCCESS
brew install node --> SUCCESS

**Comment by nealsun** [comment]
@stpdenis,  still failed, actually I installed openssl before.

**Comment by DomT4** [comment]
There was a bug in some version of OpenSSL previously that caused similar failures, so perhaps related and Node didn't pick up the upstream fix or something. There's a new Node release due soonish I believe for the recent OpenSSL security fix, which may iron things out.

You could try `brew install node --with-openssl` in the mean time.

**Comment by nealsun** [comment]
@DomT4 ,  with `brew install node --with-openssl`, I got another error.
```
Last 15 lines from /Users/sunweirong/Library/Logs/Homebrew/node/02.make:
1 error generated.
make[1]: *** [/private/tmp/node-20160925-46484-1d13h30/node-v6.6.0/out/Release/obj.target/cares/deps/cares/src/ares_create_query.o] Error 1
In file included from ../deps/cares/src/ares_data.c:18:
../deps/cares/src/ares_setup.h:32:10: fatal error: 'ares_config.h' file not found
In file included from ../deps/cares/src/ares_destroy.c:18:
../deps/cares/src/ares_setup.h:32:10: fatal error: 'ares_config.h' file not found
#include "ares_config.h"
         ^
#include "ares_config.h"
         ^
1 error generated.
1 error generated.
make[1]: *** [/private/tmp/node-20160925-46484-1d13h30/node-v6.6.0/out/Release/obj.target/cares/deps/cares/src/ares_destroy.o] Error 1
make[1]: *** [/private/tmp/node-20160925-46484-1d13h30/node-v6.6.0/out/Release/obj.target/cares/deps/cares/src/ares_data.o] Error 1
make: *** [node] Error 2
```

**Comment by nico29** [comment]
I tried that too, unfortunately that also failed ➡️ https://gist.github.com/anonymous/cf5cd09bd4a5e84a39bb4748a696e930 😿

**Comment by nico29** [comment]
Okay at last node managed to installed. 
The formula appears to have been update [with this commit](https://github.com/Homebrew/homebrew-core/commit/4fdd781d53d3fccb35a3c2be286b9849ff807adc): 
I just linked to the new openssl@1.1 but I am not sure that is related as the screenshot shows.
![capture d ecran 2016-09-26 a 17 08 51](https://cloud.githubusercontent.com/assets/3858041/18839715/4534dba0-840c-11e6-93e6-ae243c7d82aa.png)
@nealsun how is it for you?

Thank you for your help!

**Comment by DomT4** [comment]
I'm not sure how you managed to link `openssl`. We've blocked that recently because it can introduce security issues with things linking to our headers but the libraries in `/usr/lib`.

`node` has a Sierra bottle now, so you ended up pouring that rather than building from source, which is what @nealsun seems to be trying to do.

**Comment by nico29** [comment]
I manually created a symblink from the Cellar to `usr/local/bin` which appeared earlier in my path. In fact I did this for test purposes and removed this link afterwards. 
Okay @DomT4 thanks for your answer!

**Comment by nealsun** [comment]
`brew install node` works now. Thanks all.

**Comment by DomT4** [comment]
Great. Closing as resolved. Thanks for letting us know! 🙇
