### ISSUE TITLE
Terminating active homebrew process

### ISSUE THREAD

**Issue by statesof** [Homebrew/homebrew-core#5159]
So I had installed homebrew on one user account and ended up deleting that account on my computer because it was redundant. Now trying to finish installing ruby onto my main account and keep running into the "Error: Another active Homebrew process is already in progress." message.

I believe the original homebrew is somehow "stuck" running on my computer under the account that I deleted. Tried to uninstall homebrew on my current account with scripts but didn't help.

I know next to nothing about coding at this point so an easy copy/ paste fix would be great, would love to just terminate the current homebrew process that is running but I do not know how.

**Comment by zmwangx** [comment]
```
/usr/bin/pkill ruby
```

**Comment by zmwangx** [comment]
If that doesn't work

```
sudo /usr/bin/pkill ruby
```

It worked if a subsequent run of

```
/usr/bin/pgrep ruby
```

prints nothing.

**Comment by ilovezfs** [comment]
Pretty sure this is caused by the lock files in /usr/local/var/homebrew/locks which you just need to remove.

**Comment by zmwangx** [comment]
And killing the processes will release the locks, no?

**Comment by ilovezfs** [comment]
Usually, but there can be leftovers depending on how something died.

**Comment by statesof** [comment]
Tried the above codes, but it did not solve the problem, here's the exact code problems I run into when installing ruby, I'm using the [http://railsapps.github.io/installrubyonrails-mac.html](url) method:

$ brew install gpg
/usr/local/Homebrew/Library/Homebrew/utils/lock.sh: line 19: /usr/local/var/homebrew/locks/update: Permission denied
-e:1:in `initialize': Bad file descriptor (Errno::EBADF)
	from -e:1:in `new'
	from -e:1:in `<main>'
Error: Another active Homebrew process is already in progress.
Please wait for it to finish or terminate it to continue.
Warning: gnupg2-2.0.30_2 already installed
michaels-MacBook-Pro:~ mikeblaney$

**Comment by zmwangx** [comment]
Then

```
rm -rf /usr/local/var/homebrew/locks
```

**Comment by statesof** [comment]
Hey zmwangx just did that and got a permission denied on all of the locks

**Comment by zmwangx** [comment]
`sudo rm -rf /usr/local/var/homebrew/locks`.

But maybe you need to check the mode of other things too.

**Comment by statesof** [comment]
Is there a way to just terminate whichever homebrew process is currently still active? I put in your last code it didn't seem to affect anything.

**Comment by zmwangx** [comment]
The pkill ruby should have terminated everything. Or try terminating all bash processes too.

**Comment by statesof** [comment]
What code do I have to put in to do that? Sorry but I'm incredibly new to this.

**Comment by zmwangx** [comment]
If you're incredibly new to this I suggest you use Activity Monitor...

**Comment by sgoendoer** [comment]
The pkill ruby didnt change a thing for me. How to fix this?

**Comment by Parth-Mehrotra** [comment]
Having the same issue:
```
➜  ~ sudo /usr/bin/pkill ruby                 

➜  ~ sudo rm -rf /usr/local/var/homebrew/locks
➜  ~ brew install maven                       
mkdir: /usr/local/var/homebrew/locks: Permission denied
/usr/local/Homebrew/Library/Homebrew/utils/lock.sh: line 19: /usr/local/var/homebrew/locks/update: No such file or directory
-e:1:in `initialize': Bad file descriptor (Errno::EBADF)
	from -e:1:in `new'
	from -e:1:in `<main>'
Error: Another active Homebrew process is already in progress.
Please wait for it to finish or terminate it to continue.
Error: Permission denied - /usr/local/var/homebrew/locks
```
I've deleted everything in `/tmp`, deleted all the locks, not sure what's causing this.

**Comment by MikeMcQuaid** [comment]
You need to `chown -R $(whoami) /usr/local/var/homebrew`.
