### ISSUE TITLE
rust 1.42.0 upgrade issue tracker

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#51695]
Creating this issue to track rust 1.42.0 upgrade (#51653)

# build failure
- `diesel`
- `gitg`
- `grin`
- `grin-wallet`
- `pijul`
- `rav1e`

# test failure
- `broot` (#51678, broot 0.13.4 upgrade)

# shasum mismatch
- `gleam`

**Comment by Bo98** [comment]
All of this, besides `gleam`, is already listed in #50815.

**Comment by chenrui333** [comment]
Closing this in favor of that then.
