### ISSUE TITLE
Missing dependencies for Wine

### ISSUE THREAD

**Issue by florian** [Homebrew/homebrew-core#517]
I'm sorry if this is the wrong place to report this.
Installing Wine using homebrew isn't possible anymore because dependencies are missing:

```
~ $ brew install wine
==> Installing dependencies for wine: libpng, freetype, jpeg, libtool, libusb, libusb-compat, fontconfig, libtiff, gd, libgphoto2, little-cms2, jasper, libicns, makedepend, openssl, sane-backends
==> Installing wine dependency: libpng
==> Downloading ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/libpng-1.6.18.tar.xz

curl: (78) RETR response: 550
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/libpng-1.6.18.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libpng"
Download failed: https://dl.bintray.com/homebrew/mirror/libpng-1.6.18.tar.xz
```

**Comment by UniqMartin** [comment]
`libpng` 1.6.18 is an old version and the current version provided by Homebrew is 1.6.21. Please run `brew update` to update your Homebrew installation and then try again. (Afterwards, you might also want to run `brew upgrade` to upgrade formulae you have already installed to the newest available version.)

**Comment by florian** [comment]
Thanks, that did fix the problem :)
