### ISSUE TITLE
plantuml: please place also plantuml.jar in stable location

### ISSUE THREAD

**Issue by tko** [Homebrew/homebrew-core#51700]
Emacs orgmode wants the path to `plantuml.jar` in its configuration. Unfortunately on every upgrade of the formula that path changes, on one day its
`/usr/local/Cellar/plantuml/1.2020.1/libexec/plantuml.jar` and 
`/usr/local/Cellar/plantuml/1.2020.2/libexec/plantuml.jar` the next.

Please place the `plantuml.jar` file in a stable location that doesn't change on every upgrade, similar to the `plantuml` executable.

**Comment by Bo98** [comment]
Does `/usr/local/opt/plantuml/libexec/plantuml.jar` work for you?

**Comment by tko** [comment]
🤦‍♂ yes. Thanks.

In my defence I tried
- brew list
- fd plantuml /usr/local

and afterwards also
- find -name plantuml.jar /usr/local
- mdfind -name plantuml.jar

and none of them show the stable location 😞
