### ISSUE TITLE
legit bottle: bash completion line end using '\r\n'

### ISSUE THREAD

**Issue by JarryShaw** [Homebrew/homebrew-core#51719]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Just installing/upgrading [`legit`](https://github.com/frostming/legit).

## What happened (include command output)

After installing/upgrading `legit`, when opening a new Terminal on macOS, the following error message will occur:

```
-bash: /usr/local/etc/bash_completion.d/legit: line 1: syntax error near unexpected token `$'\r''
'bash: /usr/local/etc/bash_completion.d/legit: line 1: `_legit()
```

As I check the file, bash completion script from  the *bottled* `legit` formula has its line end using `\r\n`:

```
$ xxd /usr/local/etc/bash_completion.d/legit
00000000: 5f6c 6567 6974 2829 0d0a 7b0d 0a20 2020  _legit()..{..   
00000010: 206c 6f63 616c 2063 7572 2070 7265 7620   local cur prev 
00000020: 6f70 7473 0d0a 2020 2020 434f 4d50 5245  opts..    COMPRE
```

Whilst the original release from `legit` (sampling from v1.2.0), the bash completion script has its line end using `\n`:

```
$ xxd legit-1.2.0/extra/bash-completion/legit
00000000: 5f6c 6567 6974 2829 0a7b 0a20 2020 206c  _legit().{.    l
00000010: 6f63 616c 2063 7572 2070 7265 7620 6f70  ocal cur prev op
00000020: 7473 0a20 2020 2043 4f4d 5052 4550 4c59  ts.    COMPREPLY
```

## What you expected to happen

The line end should be `\n` as always.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install legit
==> Downloading https://homebrew.bintray.com/bottles/legit-1.2.0_1.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/6f/6f7e454a8d416d41ec0a3a002c54e9db0563afc4a1cc8ad6be14eeaaf21c4f9b?__gda__=exp=1584152592
######################################################################## 100.0%
==> Pouring legit-1.2.0_1.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/legit/1.2.0_1: 846 files, 8.4MB
$ source ~/.bash_profile 
-bash: /usr/local/etc/bash_completion.d/legit: line 1: syntax error near unexpected token `$'\r''
'bash: /usr/local/etc/bash_completion.d/legit: line 1: `_legit()
```

**Comment by Bo98** [comment]
Thanks for letting us know. Does `brew install -s legit` work? I get the sense it won't as it appears that the CRLF line endings appear in the original PyPI archive we are downloading from:

https://files.pythonhosted.org/packages/75/99/e17f2b4d1939e806091721949acc664de5ad36a32187cd3222107b002400/legit-1.2.0.tar.gz

It may be worth raising this issue with upstream.

**Comment by JarryShaw** [comment]
Alright, it's sure from the original PyPI archive... I'm notifying the upstream. 🤦‍♂
