### ISSUE TITLE
brew: command not found

### ISSUE THREAD

**Issue by sunnyjiechao** [Homebrew/homebrew-core#51761]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I install homebrew on my MacBook Pro via the method from the official website and succeeded to install it in my macOS, but I can't find and use the `brew` command ever.

#### step1 - open the local bin folder:
`jaydeMacBook-Pro:bin jay$ cd /usr/local/bin`

#### step2 - check brew if contains in this folder, yes it is
`jaydeMacBook-Pro:bin jay$ ls`
`brew			pip3.7			python3.7`

`jaydeMacBook-Pro:bin jay$ ./brew`
`-bash: ./brew: No such file or directory`

`jaydeMacBook-Pro:bin jay$ cat brew `
`cat: brew: No such file or directory`

`jaydeMacBook-Pro:bin jay$ cd brew `
`-bash: cd: brew: No such file or directory`

`jaydeMacBook-Pro:bin jay$ brew`
`-bash: brew: command not found`

I have no idea why the brew command can't be used in my macOS？？

## What you expected to happen

I wish the brew command is normal to use!

## Step-by-step reproduction instructions (by running `brew install` commands)

None

**Comment by SMillerDev** [comment]
You need to adjust your PATH. Add `PATH=/usr/local/bin:$PATH` to your `.zshrc` file

**Comment by SMillerDev** [comment]
Closing this since it's a config issue and shouldn't be in homebrew-core but on discourse.
