### ISSUE TITLE
gdb-9.1 hangs on macOS Catalina at the very first excution 

### ISSUE THREAD

**Issue by alanzhai219** [Homebrew/homebrew-core#51777]
env:
hardware: MacBook Pro (15-inch, 2018)
os: macOS-Catalina-14.15.3

cmd:
1. brew install gdb # gdb-9.1 will be installed.
2. follow https://sourceware.org/gdb/wiki/PermissionsDarwin#Troubleshooting_code-signing

try-to-do:
gdb ./hello_out

happens:
1. at the very first run, thread is hanging after setting line number;
2. run 'Ctrl-Z' to suspend;
3. run gdb again, it works well.

bug:
after restart macOS, first run gdb will catch such 'hang'

**Comment by SMillerDev** [comment]
This seems like something that should be reported upstream. If it works the second time it doesn't seem to be a homebrew issue.
