### ISSUE TITLE
php 7.4.3 pecl search or install anything will got notice

### ISSUE THREAD

**Issue by lanlin** [Homebrew/homebrew-core#51831]
## check list

- [yes] ran `brew update` and can still reproduce the problem?
- [yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [no] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [no] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have installed PHP 7.4.3 (`brew install php`),
the installed package name as `homebrew-bottles/bottles/php-7.4.3.high_sierra.bottle.tar.gz`
then I run this command

```shell
pecl search redis
pecl install redis
```

## What happened (include command output)

I got some notice below

<details>
  <summary>pecl search redis output</summary>
  <pre>
Retrieving data...0%

Notice: Trying to access array offset on value of type null in Remote.php on line 550
Notice: Trying to access array offset on value of type null in /usr/local/Cellar/php/7.4.3/share/php/pear/PEAR/Command/Remote.php on line 550
Notice: Trying to access array offset on value of type null in Remote.php on line 551
Notice: Trying to access array offset on value of type null in /usr/local/Cellar/php/7.4.3/share/php/pear/PEAR/Command/Remote.php on line 551
Matched packages, channel pecl.php.net:

=======================================
Package Stable/(Latest) Local
redis   5.2.0 (stable)        PHP extension for interfacing with Redis
  </pre>
</details>

<details>
  <summary>pecl install redis output</summary>
  <pre>
Notice: Trying to access array offset on value of type bool in REST.php on line 181
Notice: Trying to access array offset on value of type bool in /usr/local/Cellar/php/7.4.3/share/php/pear/PEAR/REST.php on line 181
Notice: Trying to access array offset on value of type bool in REST.php on line 181
Notice: Trying to access array offset on value of type bool in /usr/local/Cellar/php/7.4.3/share/php/pear/PEAR/REST.php on line 181
Notice: Trying to access array offset on value of type bool in REST.php on line 181
Notice: Trying to access array offset on value of type bool in /usr/local/Cellar/php/7.4.3/share/php/pear/PEAR/REST.php on line 181
Notice: Trying to access array offset on value of type bool in REST.php on line 181
Notice: Trying to access array offset on value of type bool in /usr/local/Cellar/php/7.4.3/share/php/pear/PEAR/REST.php on line 181

downloading redis-5.2.0.tgz ...
Starting to download redis-5.2.0.tgz (251,462 bytes)
.....................................................................................
  </pre>
</details>

## What you expected to happen

the correct output should like this

```shell
pecl search redis
Retrieving data...0%
=======================================
Package Stable/(Latest) Local
redis   5.2.0 (stable)        PHP extension for interfacing with Redis
```

```shell
pecl install redis
downloading redis-5.2.0.tgz ...
Starting to download redis-5.2.0.tgz (251,462 bytes)
.....................................................................................
```

here is the php pecl version info
 
```shell
PEAR Version: 1.10.10
PHP Version: 7.4.3
Zend Engine Version: 3.4.0
Running on: Darwin fooMacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64 x86_64
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```shell
brew update
brew cleanup
brew install php
pecl search redis
pecl install redis
```

**Comment by SMillerDev** [comment]
What happens when you run `which pecl`?

**Comment by lanlin** [comment]
```shell
/usr/local/bin/pecl
```

**Comment by SMillerDev** [comment]
That seems to be a bug in pecl then. This should be reported to the PHP developers in that case.
