### ISSUE TITLE
travis fails to run after installed

### ISSUE THREAD

**Issue by cburgmer** [Homebrew/homebrew-core#51845]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
$ brew gist-logs travis
Error: No logs.
```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48a1637b24a0c329905a981f4cff547c7fa47943
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d7e7114767e205075e9d0faaac21868bce5e3b1f
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.25.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 13.0.2
macOS: 10.15.3-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1

$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

I'm trying to run the `travis` command and it fails due to an issue inside one of it's dependencies (the gh gem).

The reason I don't file a bug report over at travis is because #51735 changed a lot of dependencies back in time, and I don't feel comfortable tasking the travis devs to fix an issue if newer versions are available.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ travis encrypt 0123456789012345678901234567890123456789
/usr/local/Cellar/travis/1.8.11/libexec/gems/faraday-0.9.2/lib/faraday/request/retry.rb:30: warning: constant ::Fixnum is deprecated
undefined method `try' for #<Faraday::Env:0x00007f93020dc950>
for a full error report, run travis report

$ travis report
System
Ruby:                     Ruby 2.6.3-p62
Operating System:         Mac OS X 10.15.3
RubyGems:                 RubyGems 3.0.3

CLI
Version:                  1.8.11
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2020-03-18 14:22:04 +0100

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)

Last Exception
An error occurred running `travis encrypt`:
    NoMethodError: undefined method `try' for #<Faraday::Env:0x00007f93020dc950>
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/remote.rb:71:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/normalizer.rb:8:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/parallel.rb:27:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/wrapper.rb:87:in `generate_response'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/remote.rb:88:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `request'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/gh-0.13.3/lib/gh/remote.rb:106:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `head'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/travis-1.8.11/lib/travis/cli/repo_command.rb:120:in `detect_api_endpoint'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/travis-1.8.11/lib/travis/cli/repo_command.rb:22:in `setup'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/travis-1.8.11/lib/travis/cli/command.rb:197:in `execute'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/travis-1.8.11/lib/travis/cli.rb:64:in `run'
        from /usr/local/Cellar/travis/1.8.11/libexec/gems/travis-1.8.11/bin/travis:18:in `<top (required)>'
        from /usr/local/Cellar/travis/1.8.11/libexec/bin/travis:23:in `load'
        from /usr/local/Cellar/travis/1.8.11/libexec/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
  </pre>
</details>

**Comment by fkmclane** [comment]
I'm also affected by this and did a little digging (before I saw this issue) to see what was going on, so I'll just add a bit more information.

Here's a reference to when this issue initially occurred in 2015 and where the Travis folks updated the gh gem to resolve the issue: travis-ci/travis.rb#265 (#51735 downgraded this gem below the fixed version in the 1.18.11 formula update)

It looks like #51735 downgraded several gem dependencies even though they all appear to be supported dependency versions in the [travis.gemspec](https://github.com/travis-ci/travis.rb/blob/v1.8.11/travis.gemspec) for version 1.18.11 unless I'm misunderstanding the [pessimistic operator](https://guides.rubygems.org/patterns/#pessimistic-version-constraint) (I've been known to make mistakes often so I apologize if I am misunderstanding). I'm not sure if the downgrade was included in the PR due to issues people were having or for some other reason.

I hope this is an easy fix of just bumping the gem versions and I appreciate all of the hard work from the Homebrew maintainers!

**Comment by SMillerDev** [comment]
@chenrui333

**Comment by chenrui333** [comment]
ack, let me take a look.

**Comment by chenrui333** [comment]
This is my local test, seems fine. (But I can upgrade the faraday as it shows as deprecation warning.)
```
$ travis env list
/usr/local/Cellar/travis/1.8.11/libexec/gems/faraday-0.9.2/lib/faraday/request/retry.rb:30: warning: constant ::Fixnum is deprecated
# environment variables for xx


$ travis encrypt xx
Please add the following to your .travis.yml file:

  secure: "cOa7hTohBF5+PN/jlrU74uJJ5AV4IRrFY8pn3sMDZSd+pd7apRX8WqbQ/Oz0jLuNWE/c0ln8Fm7UVsw9hQgKOlcDBSplrzu0SSGYMTgtEDtVnViiahWVd1IVaVSQNVkHjB4OymlQRsvaUSc5QZ8J7hpsRoRyEcM9/axHaTtZ/tbq8Iaa9AO8i+kblPH7h1boRNUBCUYd+xOpAqyxsvEIv2Y/a0Dd44no80hRDj7Dprb4yt06fq0btrN7BH89mLzfjbmayrjn6QH6PVYIVRTvsFTvH16diGD3RZSTDd0gAXAnuABshbl2PD9DoikwKKDBKE8RzPMQ/8rDRUui0Is0AfV8XJhlS0ebt8mM2pHM2O5pfN5KmAu/lsP76k5MI6f6C/SR0q7pFysCPT38N9fUidPkaXDeCqv75ukn3843oR4h+bm53t2+bSlbbQbEokl/n+P5aTAxbhKtYKum/n35t0+LpmP9WTX9v1kmxbzgMz7IJElfgID3jvlau8U8AVaFHxjB06oKHi+m8FtW0yMnplmFp7puGPcmDKIWGFMSvScVQ5QjjQ6xIm1j//513IS8DqypJF9pHlTy8+psh8+9ZijbTAB30fgtNet0jO5UIYkIJN4N4oQiEvyFXnTLol7tZA9MNwdd0u/SCKklUp5GMOQkxnMCckCEDlEUq5AnR8M="

Pro Tip: You can add it automatically by running with --add.
```

**Comment by chenrui333** [comment]
my `travis report`:

```
$ travis report
System
Ruby:                     Ruby 2.6.3-p62
Operating System:         Mac OS X 10.15.3
RubyGems:                 RubyGems 3.0.3

CLI
Version:                  1.8.11
Plugins:                  none
Auto-Completion:          no
Last Version Check:       2020-03-22 15:17:52 -0400

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                as "chenrui333"
Verify SSL:               yes
Enterprise:               no

Endpoints
com:                      https://api.travis-ci.com/ (access token)
org:                      https://api.travis-ci.org/ (access token, current)

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```

**Comment by chenrui333** [comment]
BTW, the dependencies downgrade followed rubygem spec in the repo. I am going to upgrade back again.

**Comment by chenrui333** [comment]
I created a revert PR for bumping the dependencies back, hopefully it works for you.

At least the warning goes away for `travis env list` now for me.

**Comment by fkmclane** [comment]
@chenrui333

I think the error might not have occurred for you above as it might not have had to talk to the GitHub API in your case as the `encrypt` command (relevant code is [here](https://github.com/travis-ci/travis.rb/blob/a032a4f23aa1d6e31ca27e471cad6feae2e5256e/lib/travis/cli/repo_command.rb#L110-L126)) only uses the GitHub API in the fallback case of no endpoint defined it seems. I got the error myself from trying `travis login --com` which uses the GitHub API in the login process.

Thanks for making the new PR! If I get a chance, I'll test it out with the `login` command again.

**Comment by chenrui333** [comment]
Let me try logout and login to see what is going on.

**Comment by chenrui333** [comment]
@fkmclane @cburgmer I just published a new release, can any of you give another try to see if it works for your favor? Thanks!

**Comment by cburgmer** [comment]
Looks good on my side. We might want to wait for @fkmclane to confirm, but otherwise I'm happy to close this. Thanks for the swift responses everybody!

**Comment by fkmclane** [comment]
I just pulled the latest revision and it works for me. Thanks everyone!

**Comment by chenrui333** [comment]
Thanks for the feedback!! Gonna close this issue now. 

Feel free to open a new one if you run into another issue. Cheers!

**Comment by chenrui333** [comment]
FYI, travis just made a new release v1.8.12
https://github.com/Homebrew/homebrew-core/pull/52054
