### ISSUE TITLE
Stable Rust (1.11.0) formula contains much older `cargo` package than official release.

### ISSUE THREAD

**Issue by nomoon** [Homebrew/homebrew-core#5185]
I noticed this because the version of `cargo` released with Rust 1.11.0 should support a new `cdylib` crate type, and I was getting errors. So I did some version comparison between the formula and the official installer.

Homebrew current El Capitan bottle:
```
rustc -V  => rustc 1.11.0
cargo -V => cargo 0.11.0 (259324c 2016-05-20)
```

Rust-lang.org installer "stable":
```
rustc 1.11.0 (9b21dcd6a 2016-08-15)
cargo 0.12.0-nightly (6b98d1f 2016-07-04)
```

It looks like the formula specifies https://github.com/Homebrew/homebrew-core/blob/master/Formula/rust.rb#L11 off the inaccurately-tagged https://github.com/rust-lang/cargo/releases/tag/0.11.0 which is far older (May 20) than the actual release version (July 4, for Rust v.11.10 released on August 15). The correct https://github.com/rust-lang/cargo commit appears to be rust-lang/cargo@6b98d1f8abf5b33c1ca2771d3f5f3bafc3407b93 and the code is also available via https://static-rust-lang-org.s3.amazonaws.com/cargo-dist/2016-07-05/cargo-nightly-x86_64-apple-darwin.tar.gz (which reports `0.12.0-nightly (6b98d1f 2016-07-04)`)

This issue means that Cargo does not actually possess all the advertised of the release listed on the Rust site. But if I'm not mistaken, a fix is as easy as updating the commit/dates in the formula.

**Comment by zmwangx** [comment]
> This issue means that Cargo does not actually possess all the advertised of the release listed on the Rust site. But if I'm not mistaken, a fix is as easy as updating the commit/dates in the formula.

We would welcome a PR for that.

**Comment by nomoon** [comment]
@zmwangx Currently working on it. While I'm at it, trying to figure out why stable checks out the cargo git repo at a commit and *then* just downloads the pre-compiled binaries and installs them.

**Comment by alexcrichton** [comment]
Ah yes to clarify the Cargo version does not match the Rust version, so today with Rust 1.12 released Cargo's correct version to use is 0.13.0

**Comment by nomoon** [comment]
Cargo's stable release number rarely (never) actually matches the one released with stable rust. Hence the original purpose of #5194

**Comment by DomT4** [comment]
This was resolved.
