### ISSUE TITLE
problem installing eccodes

### ISSUE THREAD

**Issue by YanchunHe** [Homebrew/homebrew-core#51894]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
```
$ brew update
Already up-to-date.
```
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libnco.la
  /usr/local/lib/libnco_c++.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libnco.a
  /usr/local/lib/libnco_c++.a

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
```

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
https://gist.github.com/87e976c3692851766d12a7cf3ba0c2ef
```

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
```
$ brew install eccodes
```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew install eccodes
==> Downloading https://software.ecmwf.int/wiki/download/attachments/45757960/eccodes-2.17.0-Source.tar.gz
==> Downloading from https://confluence.ecmwf.int//download/attachments/45757960/eccodes-2.17.0-Source.tar.gz
######################################################################## 100.0%
==> cmake .. -DENABLE_NETCDF=ON -DENABLE_PNG=ON -DENABLE_PYTHON=OFF
==> make install
Last 15 lines from /nird/home/yanchun/.cache/Homebrew/Logs/eccodes/02.make:
make[2]: Leaving directory `/tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build'
[ 79%] Built target tigge_check
/nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E cmake_copy_f90_mod fortran/modules/eccodes.mod fortran/CMakeFiles/eccodes_f90.dir/eccodes.mod.stamp GNU
/nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E touch fortran/CMakeFiles/eccodes_f90.dir/eccodes_f90.f90.o.provides.build
[ 79%] Linking Fortran shared library ../lib/libeccodes_f90.so
cd /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran && /nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E remove /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/lib/libeccodes_f90.so
cd /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran && /nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E cmake_link_script CMakeFiles/eccodes_f90.dir/link.txt --verbose=1
/nird/home/u1/yanchun/.linuxbrew/bin/gfortran -fPIC -O3 -DNDEBUG -funroll-all-loops -finline-functions  -Wl,--disable-new-dtags -shared -Wl,-soname,libeccodes_f90.so -o ../lib/libeccodes_f90.so CMakeFiles/eccodes_f90.dir/grib_fortran.c.o CMakeFiles/eccodes_f90.dir/grib_f90.f90.o CMakeFiles/eccodes_f90.dir/eccodes_f90.f90.o   -L/nird/home/u1/yanchun/.linuxbrew/opt/isl@0.18/lib  -L/nird/home/u1/yanchun/.linuxbrew/opt/openssl@1.1/lib  -Wl,-rpath,"\$ORIGIN/../lib" ../lib/libeccodes.so /nird/home/u1/yanchun/.linuxbrew/lib/libpng.so /nird/home/u1/yanchun/.linuxbrew/lib/libz.so -lm /nird/home/u1/yanchun/.linuxbrew/lib/libjasper.so /nird/home/u1/yanchun/.linuxbrew/lib/libjpeg.so -lpthread
cd /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran && /nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E make_directory /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/include
cd /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran && /nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E copy /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran/modules/./eccodes.mod /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/include
cd /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran && /nird/home/u1/yanchun/.linuxbrew/Cellar/cmake/3.16.5/bin/cmake -E copy /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/fortran/modules/./grib_api.mod /tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build/include
make[2]: Leaving directory `/tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build'
[ 79%] Built target eccodes_f90
make[1]: Leaving directory `/tmp/eccodes-20200319-37285-18ytfkg/eccodes-2.17.0-Source/build'
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install eccodes
```

**Comment by SMillerDev** [comment]
```
Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

```
