### ISSUE TITLE
Request- GPSd 3.20+

### ISSUE THREAD

**Issue by jessica-mulein** [Homebrew/homebrew-core#51961]
This is not a bug, but merely a request for a more recent GPSd (3.20+)

**Comment by jessica-mulein** [comment]
The GPSd in brew is currently 3.17, released 07-Sep-2017. There's a GPSd 3.20 released Jan 2020 that has additional symbols.

**Comment by SMillerDev** [comment]
Homebrew requests should be done in the form of pull requests. Here's a guide to help you get started: https://docs.brew.sh/Updating-Software-in-Homebrew
