### ISSUE TITLE
ghostscript 9.52: bottle SHA256 mismatch

### ISSUE THREAD

**Issue by squircle** [Homebrew/homebrew-core#52005]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade ghostscript via `brew upgrade`

## What happened (include command output)

- SHA256 mismatch on Mojave bottle: expected `24e2c3c772a647b41c6a082c79bbd7b20b74d4ed8a587d0e712eeab85ce16d43`, actual `8906a4dbf2513963a4710f351e3426622c259bd888c760e4c08a9436860b4014`
- Verified that https://homebrew.bintray.com/bottles/ghostscript-9.52.mojave.bottle.tar.gz has "Actual" hash from multiple network connections, and appears to be a valid archive
- **Neither the High Sierra or Catalina SHA256 hashes match either**
- Bottle hashes were changed by commit 66a5775be1f484bb90e8876f37d664447a3aa348

<details>
  <summary>Command output</summary>
  <pre>

no-dns-yet:~ squircle$ brew upgrade -v --force-bottle ghostscript
==> Upgrading 1 outdated package:
ghostscript 9.51 -> 9.52
==> Upgrading ghostscript 9.51 -> 9.52
rm /usr/local/bin/dvipdf
rm /usr/local/bin/eps2eps
rm /usr/local/bin/gpcl6
rm /usr/local/bin/gs
rm /usr/local/bin/gsbj
rm /usr/local/bin/gsc
rm /usr/local/bin/gsdj
rm /usr/local/bin/gsdj500
rm /usr/local/bin/gslj
rm /usr/local/bin/gslp
rm /usr/local/bin/gsnd
rm /usr/local/bin/gsx
rm /usr/local/bin/gxps
rm /usr/local/bin/lprsetup.sh
rm /usr/local/bin/pdf2dsc
rm /usr/local/bin/pdf2ps
rm /usr/local/bin/pf2afm
rm /usr/local/bin/pfbtopfa
rm /usr/local/bin/pphs
rm /usr/local/bin/printafm
rm /usr/local/bin/ps2ascii
rm /usr/local/bin/ps2epsi
rm /usr/local/bin/ps2pdf
rm /usr/local/bin/ps2pdf12
rm /usr/local/bin/ps2pdf13
rm /usr/local/bin/ps2pdf14
rm /usr/local/bin/ps2pdfwr
rm /usr/local/bin/ps2ps
rm /usr/local/bin/ps2ps2
rm /usr/local/bin/unix-lpr.sh
rm /usr/local/include/ghostscript
rm /usr/local/lib/libgs.9.51.dylib
rm /usr/local/lib/libgs.9.dylib
rm /usr/local/lib/libgs.dylib
rm /usr/local/share/doc/ghostscript
rm /usr/local/share/ghostscript
rm /usr/local/share/man/man1/dvipdf.1
rm /usr/local/share/man/man1/eps2eps.1
rm /usr/local/share/man/man1/gs.1
rm /usr/local/share/man/man1/gsbj.1
rm /usr/local/share/man/man1/gsdj.1
rm /usr/local/share/man/man1/gsdj500.1
rm /usr/local/share/man/man1/gslj.1
rm /usr/local/share/man/man1/gslp.1
rm /usr/local/share/man/man1/gsnd.1
rm /usr/local/share/man/man1/pdf2dsc.1
rm /usr/local/share/man/man1/pdf2ps.1
rm /usr/local/share/man/man1/pf2afm.1
rm /usr/local/share/man/man1/pfbtopfa.1
rm /usr/local/share/man/man1/printafm.1
rm /usr/local/share/man/man1/ps2ascii.1
rm /usr/local/share/man/man1/ps2epsi.1
rm /usr/local/share/man/man1/ps2pdf.1
rm /usr/local/share/man/man1/ps2pdf12.1
rm /usr/local/share/man/man1/ps2pdf13.1
rm /usr/local/share/man/man1/ps2pdf14.1
rm /usr/local/share/man/man1/ps2pdfwr.1
rm /usr/local/share/man/man1/ps2ps.1
==> Downloading https://homebrew.bintray.com/bottles/ghostscript-9.52.mojave.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/89/8906a4dbf2513963a4710f351e3426622c259bd888c760e4c08a9436860b4014?__gda__=exp=1584841994~hmac=b0440963639c24f17ad4ab4e21b2decfe10978f81c98dc2c49f014be5f32a839&response-content-disposition=attachment%3Bfilename%3D%22ghostscript-9.52.mojave.bottle.tar.gz%22&response-content-type=application%2Fgzip&requestInfo=U2FsdGVkX1_Z-FxxO1k2pAe0EvUf-8khd5kawXv9jnC9I_rRDZSAzJswo_9CD4MWxb-IMfPt3R-1PHAYRHSIG0l9x3CGDVzl-Hotql3cCWMH9SOXrDoU61fGpzyXmpiZVjkN4x3I9t7DF1ODnMHH8A&response-X-Checksum-Sha1=e2b85b13d1eef6e681dc84c1141d7ebbe3baaf67&response-X-Checksum-Sha2=8906a4dbf2513963a4710f351e3426622c259bd888c760e4c08a9436860b4014
/usr/bin/curl -q --globoff --show-error --user-agent Homebrew/2.2.10\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.14.6\)\ curl/7.54.0 --fail --location --remote-time --continue-at 0 --output /Users/squircle/Library/Caches/Homebrew/downloads/91f3c9535bda739dd9663190e036d7661f4e27463b96ea05c9b5db5a98ca9abe--ghostscript-9.52.mojave.bottle.tar.gz.incomplete https://akamai.bintray.com/89/8906a4dbf2513963a4710f351e3426622c259bd888c760e4c08a9436860b4014\?__gda__=exp=1584841994\~hmac=b0440963639c24f17ad4ab4e21b2decfe10978f81c98dc2c49f014be5f32a839\&response-content-disposition=attachment\%3Bfilename\%3D\%22ghostscript-9.52.mojave.bottle.tar.gz\%22\&response-content-type=application\%2Fgzip\&requestInfo=U2FsdGVkX1_Z-FxxO1k2pAe0EvUf-8khd5kawXv9jnC9I_rRDZSAzJswo_9CD4MWxb-IMfPt3R-1PHAYRHSIG0l9x3CGDVzl-Hotql3cCWMH9SOXrDoU61fGpzyXmpiZVjkN4x3I9t7DF1ODnMHH8A\&response-X-Checksum-Sha1=e2b85b13d1eef6e681dc84c1141d7ebbe3baaf67\&response-X-Checksum-Sha2=8906a4dbf2513963a4710f351e3426622c259bd888c760e4c08a9436860b4014
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 32.3M  100 32.3M    0     0  5751k      0  0:00:05  0:00:05 --:--:-- 5565k
==> Verifying 91f3c9535bda739dd9663190e036d7661f4e27463b96ea05c9b5db5a98ca9abe--ghostscript-9.52.mojave.bottle.tar.gz checksum
Error: SHA256 mismatch
Expected: 24e2c3c772a647b41c6a082c79bbd7b20b74d4ed8a587d0e712eeab85ce16d43
  Actual: 8906a4dbf2513963a4710f351e3426622c259bd888c760e4c08a9436860b4014
 Archive: /Users/squircle/Library/Caches/Homebrew/downloads/91f3c9535bda739dd9663190e036d7661f4e27463b96ea05c9b5db5a98ca9abe--ghostscript-9.52.mojave.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
[snip]
  </pre>
</details>

## What you expected to happen

Upgrade from bottle with correct SHA256 hash (installation from source subsequently succeeds)

## Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew upgrade ghostscript` or `brew install ghostscript`

### `brew config`
```
HOMEBREW_VERSION: 2.2.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48a1637b24a0c329905a981f4cff547c7fa47943
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d69912d55f9f0b653a3aadd99f862494d4efce99
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
```

### `brew doctor`
`Your system is ready to brew.`

**Comment by iMichka** [comment]
Fixed by #52016
