### ISSUE TITLE
"illegal hardware instruction" running gstreamer from bottle

### ISSUE THREAD

**Issue by danielepolencic** [Homebrew/homebrew-core#52007]
- [x] ran `brew update` and can still reproduce the problem? yes
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? yes
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Logs for gstream-plugin-good: https://gist.github.com/danielepolencic/84de691604b936b001bd4b7f5cc4964c
Logs for gstream: https://gist.github.com/danielepolencic/061b356cc2d7b83bfe8cd7b9add86d96

## What you were trying to do (and why)

I can use Gstream to demo input and output video correctly with the following command:

```bash
gst-launch-1.0 autovideosrc device=/dev/video0 ! autovideosink
```

However, as soon as I change `autovideosink` to `osxvideosink` (from the gst-plugin-good), I can see this error:

```bash
~ ❯❯❯ gst-launch-1.0 autovideosrc device=/dev/video0 ! osxvideosink

Setting pipeline to PAUSED ...
[1]    30984 illegal hardware instruction  gst-launch-1.0 autovideosrc device=/dev/video0 ! osxvideosink
```

This is the same error as #23581

The original ticket suggested that the error could be either in gstream or gst-plugin-good.

Since the demo pipeline works with Gstreamer, I thought the issue could have been with the plugin.

I decided to rebuild it from source, it didn't help.
I decided to rebuild both gstreamer and the plugin from source with:

```bash
brew install --build-from-source gstreamer gst-plugins-good 
```

It didn't help either, same error.
I decided to build `gst-plugins-good` from HEAD. This fails at `./autogen.sh` silent. I had a look at the repo on my filesystem and I couldn't find the file, so I think the formula might be out of sync.

**Comment by SMillerDev** [comment]
Are you running a hackingtosh or did you install a macOS version that your hardware doesn't officially support?

**Comment by danielepolencic** [comment]
I use a MacBook Pro (15-inch, Late 2016).

FYI, I installed the packages from the official GStreamer website and it worked.
