### ISSUE TITLE
node fails on npm stage

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#5200]
I'm runnings Sierra with latest Xcode & CLT.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

https://gist.github.com/yurikoles/b6dde4ae0e5a07884b6460813014b53b

`Error: No such file or directory - /usr/local/Cellar/node/6.6.0/libexec/npm/lib/node_modules/npm`

**Comment by DomT4** [comment]
```
2016-09-25 14:37:50 +0300

make
install

node cli.js install -g -f 
Error: EPERM: operation not permitted, mkdir '/Users/yurikoles/.node_modules'
    at Error (native)
```

Can you provide `env | grep npm` and `env | grep NPM`? Also `cat ~/.npmrc`. Thanks!

**Comment by yurikoles** [comment]
```
$ env | grep npm
npm_config_prefix=/Users/yurikoles/.node_modules
```
`$ env | grep NPM`
gives nothing

```
$ cat ~/.npmrc
cat: /Users/yurikoles/.npmrc: No such file or directory
```

**Comment by DomT4** [comment]
Is this fixed? You closed the Issue.

**Comment by yurikoles** [comment]
I had retried with `npm_config_prefix` set to empty value and it's build fine.
