### ISSUE TITLE
Please test/review Python for issue 22490

### ISSUE THREAD

**Issue by jaraco** [Homebrew/homebrew-core#52046]
In [bpo-22490](https://bugs.python.org/issue22490), a bugfix is now in place for an issue where __PYVENV_LAUNCHER__ would leak to the interpreter and child processes. The fix was applied today to the master, 3.8, and 3.7 branches.

One action item that remained was to test the change against homebrew. Please consider testing one of these branches against homebrew as time permits. Thanks.

**Comment by SMillerDev** [comment]
Can you make a test script that would prove this is resolved?

**Comment by jonchang** [comment]
I suspect that this is the reproduction as originally stated in https://github.com/pypa/pip/issues/2031

```console
# incorrect
% /usr/local/opt/python/bin/python3 -c "import os; print(os.environ['__PYVENV_LAUNCHER__'])"
/usr/local/Cellar/python/3.7.7/bin/python3

# correct
% /usr/bin/python -c "import os; print(os.environ['__PYVENV_LAUNCHER__'])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: '__PYVENV_LAUNCHER__'
```

And it seems the relevant patches are here:

master: https://github.com/python/cpython/pull/9516
3.8: https://github.com/python/cpython/pull/19110
3.7: https://github.com/python/cpython/pull/19111

**Comment by tdsmith** [comment]
The lingering manifestation of this in Homebrew was the case here: https://bugs.python.org/issue22490#msg283859

```
The persistence of __PYVENV_LAUNCHER__ poisons the sys.executable of virtualenv interpreters launched as a subprocess of another Python interpreter:

$ virtualenv -p python3 test

# Expected
$ test/bin/python3 -c 'import sys; print(sys.executable)'
/Users/tim/test/bin/python3

# Not expected
$ /usr/local/bin/python3 -c 'import subprocess; subprocess.call(["/Users/tim/test/bin/python3", "-c", "import sys; print(sys.executable)"])'
/usr/local/bin/python3

# This is the right outcome, but we had to delete __PYVENV_LAUNCHER__ manually
$ /usr/local/bin/python3 -c 'import subprocess, os; del os.environ["__PYVENV_LAUNCHER__"]; subprocess.call(["/Users/tim/test/bin/python3", "-c", "import sys; print(sys.executable)"])'
/Users/tim/test/bin/python3
```

We could identify that this is fixed if running the second case gave e.g. `/Users/tim/test/bin/python3`.

I don't think there's anything Homebrew-specific about this anymore; there was an issue with script shebangs but pip 6 (which is quite old now) fixed that for us.

**Comment by iMichka** [comment]
@tdsmith brought some insights and I understand, this looks good now, or at least pip 6 already fixed this for us back then. So the fix does not change anything for us I guess.

Thanks for merging the patch though!
