### ISSUE TITLE
fileutils.rb:239:in `mkdir': Permission denied @ dir_s_mkdir - /private/tmp (Errno::EACCES)

### ISSUE THREAD

**Issue by e71828** [Homebrew/homebrew-core#52119]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem? 
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? 
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 

## What you were trying to do (and why)

brew install  usbmuxd

## What happened (include command output)

failed

<details>
  <summary>Command output</summary>
  <pre>

Traceback (most recent call last):
	13: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	12: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	11: from /usr/local/Homebrew/Library/Homebrew/global.rb:28:in `<top (required)>'
	10: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/config.rb:56:in `<top (required)>'
	 7: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/pathname.rb:578:in `mkpath'
	 6: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	 5: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	 4: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	 3: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	 2: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	 1: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': Permission denied @ dir_s_mkdir - /private/tmp (Errno::EACCES)
  </pre>
</details>

## What you expected to happen

no error

**Comment by SMillerDev** [comment]
Please actually read the check boxes when you tick them. This is not enough information to debug this. It can be reopened when it contains all the information needed.
