### ISSUE TITLE
Missing bottles for pdftk-java 3.0.9 (404)

### ISSUE THREAD

**Issue by nmk** [Homebrew/homebrew-core#52138]
All of the bottle URLs listed in https://formulae.brew.sh/api/formula/pdftk-java.json for pdftk-java 3.0.9 for catalina, mojave and high_sierra return 404. All bottles for 3.0.8 are present (changing 3.0.9 to 3.0.8 in the URL downloads the bottle as expected).

Installing pdftk-java 3.0.9 always builds from source because the bottle cannot be found.

As there are hashes for the bottle files in the JSON above I assume the files were created (and hashed) but could not be uploaded.

Was there a problem with uploading the files to bintray?

**Comment by Bo98** [comment]
Thanks for the report. I've queued a new bottle build.

Looks like it was accidentally merged without triggering the bottle upload.
