### ISSUE TITLE
Resource from github not downloaded prior to unpack on linux

### ISSUE THREAD

**Issue by Firefly35** [Homebrew/homebrew-core#52176]
- [ ] ran `brew update` and can still reproduce the problem? => Already up-to-date.
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? => built library doesn't conflict with brew and come from a personal build
- [ ] ran `brew gist-logs <formula>` -> https://gist.github.com/Firefly35/0bd85b3b8bcbfbdc5839187f17a5f51e

## What you were trying to do (and why)

brew install remaken

## What happened (include command output)
On linux Mint :
==> Installing remaken from b-com/sft
==> Downloading https://github.com/b-com-software-basis/remaken/releases/download/Ubuntu1804%2Fremaken-1.5.2/remaken
Already downloaded: /home/ltouraine/.cache/Homebrew/downloads/87adde81c60a6d62977dea3b872a97c57572e9a78acd3e238165129e3c91ef59--remaken
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /home/ltouraine/.cache/Homebrew/remaken--qmake--git

<details>
  <summary>Command output</summary>
  <pre>
On linux Mint :
==> Installing remaken from b-com/sft
==> Downloading https://github.com/b-com-software-basis/remaken/releases/download/Ubuntu1804%2Fremaken-1.5.2/remaken
Already downloaded: /home/ltouraine/.cache/Homebrew/downloads/87adde81c60a6d62977dea3b872a97c57572e9a78acd3e238165129e3c91ef59--remaken
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /home/ltouraine/.cache/Homebrew/remaken--qmake--git

  </pre>
</details>

## What you expected to happen
The same behavior I get on Mac
==> Installing remaken from b-com/sft
==> Downloading https://github.com/b-com-software-basis/remaken/releases/download/macOS-Mojave%2Fremaken-1.5.2/remaken
Already downloaded: /Users/ltouraine/Library/Caches/Homebrew/downloads/9525d2e7e0139bd2c7eb3c4a50ce56f7fd6f1303ac1bce5a8983aae5fa9f4078--remaken
==> echo
==> mkdir -p $HOME/.remaken/rules
==> ln -s /usr/local/Cellar/remaken/1.5.2/share/remaken/qmake $HOME/.remaken/rules/
🍺  /usr/local/Cellar/remaken/1.5.2: 165 files, 44.2MB, built in 4 seconds

## Step-by-step reproduction instructions (by running `brew install` commands)
brew tap b-com/sft
brew install remaken

**Comment by Bo98** [comment]
I'm not entirely sure why it's different on macOS vs Linux, but the formula file in that tap should be using `stage` rather than `unpack`.

**Comment by Firefly35** [comment]
Thanks for your reply,
I'm not sure I understand the difference between 'stage' and 'unpack', can
you explain the difference please ?

Le jeu. 26 mars 2020 à 17:29, Bo Anderson <notifications@github.com> a
écrit :

**Comment by Bo98** [comment]
`stage` fetches and unpacks the resource. `unpack` skips the fetching/downloading.

No formula in homebrew-core uses `unpack` directly.

**Comment by Firefly35** [comment]
thanks a lot

Le ven. 27 mars 2020 à 10:52, Bo Anderson <notifications@github.com> a
écrit :
