### ISSUE TITLE
Fixing formuale that are not compatible with go1.14

### ISSUE THREAD

**Issue by roopakv** [Homebrew/homebrew-core#52184]
Continuation of discussion from #51909. Moving out to unblock 1.14.1

The following formuale have issues on master (quoting @Bo98):

- [ ] `wellington` hasn't been buildable for well over a year. I don't know if any Go we ship will work with it. A release was requested in 2018.
  - `HEAD` build works, but there's been no release. https://github.com/wellington/wellington/issues/213
- [ ] `dvm` has also been broken for at least a few months. go@1.13 will not fix it, but maybe something prehistoric will.
  - https://github.com/howtowhale/dvm/issues/193
- [ ] `perkeep` only works with go@1.10. This isn't really acceptable, but the next release will support newer Go. ETA: [who knows?](https://github.com/perkeep/perkeep/issues/1307)
- [x] `tunnel` could probably use go@1.13. Done in #52189
  - I have opened PR https://github.com/labstack/tunnel-client/pull/11 for Go 1.14.
- [ ] `gor`
  - I reached out to them to ask them to release a new version which includes `go.mod` which will unblock us. https://github.com/buger/goreplay/issues/739
- [ ] `charm` pulls in a dependency which no longer exists. Only the current HEAD build works.
  - https://github.com/juju/charmstore-client/issues/209

**Comment by miha-pece** [comment]
Syncthing formula also has a problem, my is now broken when I upgraded to 1.4.0. More informed persons than me are pointing to problems with go 1.14 ([link](https://github.com/syncthing/syncthing/issues/6435)).

**Comment by Bo98** [comment]
I am unable to reproduce the issue. Is there a particular command or configuration you are using that triggers the crash?

I can go ahead ship a new build with Go 1.14.1 regardless. A test case would have just been useful to prevent it reoccurring.

**Comment by miha-pece** [comment]
The issue is probably relevant for older processors. I have Mac Pro 2009. That was suggested:
https://github.com/syncthing/syncthing-macos/issues/107#issuecomment-603835787

**Comment by Bo98** [comment]
@miha-pece Can you try again now? It should be working now upon a `brew upgrade syncthing`.

**Comment by miha-pece** [comment]
It works now, thank you.

**Comment by ryboe** [comment]
A [new release](https://github.com/juju/charmstore-client/releases/tag/2.2.0) of `charmstore-client` just landed.
