### ISSUE TITLE
unable to install with --build-from-source

### ISSUE THREAD

**Issue by mrinella** [Homebrew/homebrew-core#52183]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ Y] ran `brew update` and can still reproduce the problem?

mrinella@Mark-Rinella-MacBook-Pro ~ % brew update
Already up-to-date.

- [ Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cmake
  php
  mysql

(have php@7.2 and mysql@5.7 installed alongside PHP 7.4 and MySQL 8.0, cmake shows as unlinked when brew doctor is run during the install process.)

- [Y ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/339ff64e2ac81589480aa297cf6bd89c

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

upgrade or reinstall or clean install of cmake

All other homebrew packages built from source. 

mrinella@Mark-Rinella-MacBook-Pro ~ % brew config
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 26e125fc09298c120e2d3bf5dc557493fdeb0f49
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.0.0.1.1583798712
Xcode: 11.4

mrinella@Mark-Rinella-MacBook-Pro ~ % brew list
apr			jpeg			openldap
apr-util		libde265		openssl@1.1
argon2			libev			pcre
aspell			libevent		pcre2
autoconf		libffi			perl
automake		libheif			php
bash			libidn			php-code-sniffer
bison			libmetalink		php-cs-fixer
brotli			libomp			php@7.2
c-ares			libpng			php@7.3
cmake			libpq			phpmd
composer		libsodium		pkg-config
cunit			libssh2			protobuf
curl-openssl		libtiff			python
dnsmasq			libtool			readline
doxygen			libxml2			redis
freetds			libyaml			rtmpdump
freetype		libzip			ruby
gdbm			little-cms2		shared-mime-info
gettext			lua			sphinx-doc
git			meson			sqlite
glib			mysql			sysbench
gmp			mysql-client		tidy-html5
gnu-sed			mysql-client@5.7	truncate
httpd			mysql@5.7		unixodbc
icu4c			nasm			vim
ilmbase			ncurses			webp
imagemagick		nghttp2			x265
intltool		ninja			xz
itstool			oniguruma		zsh
jansson			openexr
jemalloc		openjpeg

## What happened (include command output)

Install does not complete

<details>
  <summary>Command output</summary>
  <pre>

-- Performing Test run_pic_test
-- Performing Test run_pic_test - Success
then hangs ...

  </pre>
</details>

## What you expected to happen

previous versions built without issue

## Step-by-step reproduction instructions (by running `brew install` commands)

'brew install --force --build-from-source --verbose cmake' stalls after:

**Comment by SMillerDev** [comment]
Why are you building cmake from source?

**Comment by Bo98** [comment]
We managed to build CMake just a couple days ago across three different macOS versions so we're unable to reproduce the issue. That said, we were using Xcode/CLT 11.3 and have not tried 11.4 yet.

I notice you mention it sticking after `run_pic_test`, but your gist-logs has no mention of that. Is it inconsistent?

**Comment by mrinella** [comment]
Installing svn with Homebrew solved the issue.

Prior to installing, when it was building cmake, after run_pic_test it would try:

/usr/local/Homebrew/Library/Homebrew/shims/mac/super/svn --version

which did not give a response even though it looks correctly linked to git 

/usr/local/Homebrew/shims/Mac/super 
lrwxr-xr-x   1 mrinella  admin    13 Mar 26 20:38 svn -> ../../scm/svn

/usr/local/Homebrew/Library/Homebrew/shims/scm
lrwxr-xr-x  1 mrinella  admin     3 Mar 26 20:38 svn -> git

and /usr/local/Homebrew/Library/Homebrew/shims/mac/super/git --version

returns: 

git version 2.26.0

Curious if this is an issue with 10.15.4, Homebrew or the cmake formula. Log of successful build from source is here:

https://gist.github.com/1498f32192cd024092941b0b828b30ab

Thanks for your help on this.

**Comment by mrinella** [comment]
Sean,

On why building from source, I need to use mysql@5.7 and when I installed the precompiled version is was very unstable. I ended up building that from source and it solved the issue. Thought I might as well build all its dependencies from source as well when I went through that process.

Mark

**Comment by Bo98** [comment]
`/usr/local/Homebrew/Library/Homebrew/shims/mac/super/svn` is a wrapper.

You can use `/usr/local/Homebrew/Library/Homebrew/shims/mac/super/svn --homebrew=print-path` to see what actual SVN binary it is trying.

**Comment by MikeMcQuaid** [comment]
Sorry, we do not support failures that occur when building from source.
