### ISSUE TITLE
osm2pgsql brew install has Seg Fault 11 crash when using --tag-transform-script option on macOS 10.14.6

### ISSUE THREAD

**Issue by and-viceversa** [Homebrew/homebrew-core#52193]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Gist is [here](https://gist.github.com/d2d455f08290382a9dc6753b0e9a8aea)
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
-I am trying to render my own Open Street Map tiles using Mapnik.
-osm2pgsql is part of the tutorial at [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/blob/master/INSTALL.md)

## What happened (include command output)
I went through the openstreetmap-carto install tutorial and got Segmentation Fault 11 on the following command:
`osm2pgsql -G --hstore --style openstreetmap-carto.style --tag-transform-script openstreetmap-carto.lua -d gis ~/path/to/data.osm.pbf`

<details>
  <summary>Command output</summary>
  <pre>

Signal 11 (segmentation fault)

  </pre>
</details>

## What you expected to happen
I expected osm2pgsql to properly load .pbf files into postgres according to the tutorial

## Step-by-step reproduction instructions (by running `brew install` commands)
```
brew install postgresql
brew install postgis
brew install osm2pgsql

createdb gis
psql -d gis -c 'CREATE EXTENSION postgis; CREATE EXTENSION hstore;'

osm2pgsql -G --hstore --style openstreetmap-carto.style --tag-transform-script openstreetmap-carto.lua -d gis ~/path/to/data.osm.pbf

```

## Other Notes
This command succeeds without the `--tag-transform-script option` (however this is required for osm-carto stylesheets).

I played with `ulimit` and `osm2pgsql -C` options, no joy.

This did not work either:
```
brew install --build-from-source luajit
brew install --build-from-source osm2pgsql
```

The solution was to clone the osm2pgsql repo and build my own, which passed all tests and works properly with the --tag-transform-script Lua option.

All of this to say, I think there is a problem with the way osm2pgsql is built for Homebrew. This Seg Fault problem has been popping up more and more in recent versions of macOS with varying solutions, and is most likely not a problem with osm2pgsql itself. Please see [here](https://discourse.brew.sh/t/snort-and-macos-mojave-10-14-2-segmentation-fault-11/3977) for a the same bug in an unrelated brew install.

Please see original issue thread posted on their repo [here](https://github.com/openstreetmap/osm2pgsql/issues/1092).

**Comment by Bo98** [comment]
Hard to tell really. "segmentation fault" just means "it crashed", and not really much can be deduced from that alone.

Can you run it through `lldb` or something and see if you can get a backtrace?

**Comment by and-viceversa** [comment]
Could you please walk me through using `lldb` for this? After going through the `man` page it keeps telling me it "can't attach" to the process...
