### ISSUE TITLE
SDL 2.0.12 dependent projects fail to build

### ISSUE THREAD

**Issue by AJenbo** [Homebrew/homebrew-core#52261]
After SDL was updated to 2.0.12 builds of DevilutionX has started failing with the following message:

```
make[2]: *** No rule to make target `/usr/local/Cellar/sdl2/2.0.12/lib/libSDL2.so', needed by `devilutionx.app/Contents/MacOS/devilutionx'.  Stop.

make[2]: *** Waiting for unfinished jobs....

[ 99%] Building CXX object CMakeFiles/devilutionx.dir/SourceX/dvlnet/udp_p2p.cpp.o

make[1]: *** [CMakeFiles/devilutionx.dir/all] Error 2

make: *** [all] Error 2

The command "sudo cmake --build . --target package -j $(sysctl -n hw.physicalcpu)" exited with 2.
```

Brew file
https://github.com/Homebrew/homebrew-core/blob/master/Formula/sdl2.rb

DevilutionX build log:
https://travis-ci.org/github/diasurgical/devilutionX/builds/667931776

Travis build config:
https://github.com/diasurgical/devilutionX/blob/master/.travis.yml

**Comment by Bo98** [comment]
This appears to be an issue upstream rather than our bug: https://bugzilla.libsdl.org/show_bug.cgi?id=5039

**Comment by AJenbo** [comment]
Arh, I did think that looked a bit unusual. Thanks for looking in to the issue.
