### ISSUE TITLE
brew install --HEAD mtr fails

### ISSUE THREAD

**Issue by meingtsla** [Homebrew/homebrew-core#52274]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
% brew gist-logs mtr
Error: No logs.
```

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
% brew config
HOMEBREW_VERSION: 2.2.11-17-g6530e33
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 6530e333b39d9fa171d85b6c82edd51483c223d1
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 975ed7dc9672a228bc1cddd7b1c7850ce0246a1a
Core tap last commit: 54 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.0.33.17
Xcode: N/A
% brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

```brew install --HEAD mtr```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

% brew install --HEAD mtr
==> Cloning https://github.com/traviscross/mtr.git
Updating /Users/ech/Library/Caches/Homebrew/mtr--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 155f76a Merge pull request #340 from Sea-n/master
==> Downloading https://github.com/traviscross/mtr/pull/315.patch?full_index=1
Already downloaded: /Users/ech/Library/Caches/Homebrew/downloads/82d9d939303d8fceb7a3ae071ecd49a5f075e0fb451b308653b555ffbae74336--315.patch
==> Patching
==> Applying 315.patch
patching file packet/probe.c
Hunk #1 FAILED at 323.
Hunk #2 FAILED at 364.
2 out of 2 hunks FAILED -- saving rejects to file packet/probe.c.rej
Error: Failure while executing; `patch -g 0 -f -p1 -i /private/tmp/mtr--patch-20200328-68684-oref05/315.patch` exited with 1.

  </pre>
</details>

## What you expected to happen

I expect to be able to install latest git version of mtr.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above.

It appears the formula attempts to apply a patch that has already been merged, as seen below in lines 22-26:

```
# Pull request submitted upstream as https://github.com/traviscross/mtr/pull/315
  patch do
    url "https://github.com/traviscross/mtr/pull/315.patch?full_index=1"
    sha256 "c67b455198d4ad8269de56464366ed2bbbc5b363ceda0285ee84be40e4893668"
  end
```

**Comment by issyl0** [comment]
We don't officially support HEAD builds. We'd accept PR here to only apply the patch if the version is stable (`unless build.head?`). Alternatively, we can wait for a new release of `mtr` where we can remove the patch entirely.
