### ISSUE TITLE
Many Warnings

### ISSUE THREAD

**Issue by isaacew** [Homebrew/homebrew-core#52325]
I have been trying to clean-up the numerous warnings within Brew doctor and have struggled quite a bit. 

## Brew Update
 ```
Already up-to-date.
```

## Brew Doctor

<details>
  <summary>Brew Doctor output</summary>
  <pre>
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/pkg-config
  /opt/local/bin/MagickCore-config
  /opt/local/bin/MagickWand-config
  /opt/local/bin/scrollkeeper-config
  /opt/local/bin/icu-config
  /opt/local/bin/freetype-config
  /opt/local/bin/xslt-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/python3.7-config
  /opt/local/bin/Magick++-config
  /opt/local/bin/libpng-config
  /opt/local/bin/pspell-config
  /opt/local/bin/xml2-config
  /opt/local/bin/python3.7m-config
  /opt/local/bin/gsl-config
  /opt/local/bin/curl-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/Wand-config
  /opt/local/bin/Magick-config
  /opt/local/bin/uuid-config
  /opt/local/bin/pcre-config
  /opt/local/bin/nspr-config
  /opt/local/bin/xml-config
  /opt/local/bin/rarian-sk-config
  /opt/local/bin/ncurses6-config
  /opt/local/bin/nss-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  vim
  ghostscript
  p11-kit

Warning: Some installed formulae are not readable:
  pyqt@4: Unsupported special dependency :python3

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/share/ghostscript/9.10/Resource/Font/logo10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logo8.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logo9.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logobf10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logod10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logosl10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logosl8.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/logosl9.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/manfnt.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy10.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy5.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy6.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy7.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy8.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasy9.pfb
  /usr/local/share/ghostscript/9.10/Resource/Font/wasyb10.pfb
  /usr/local/share/git-gui
  /usr/local/share/gitk
  /usr/local/share/pkgconfig/py3cairo.pc
  /usr/local/share/pkgconfig/pycairo.pc
  /usr/local/var/homebrew/linked/py2cairo
  /usr/local/var/homebrew/linked/py3cairo
  /usr/local/var/homebrew/linked/pygobject3
  /usr/local/var/homebrew/linked/qt-legacy-formula
 </pre>
</details>

<details>
  <summary>Cleanup output</summary>
  <pre>
Permission denied @ apply2files - /usr/local/share/ghostscript/9.10/Resource/Font/logo10.pfb
 </pre>
</details>
<details>

  <summary> Config output</summary>
  <pre>
HOMEBREW_VERSION: 2.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa8fe0fc396550c23156043cd07550fc6ae6a27a
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4659abb729f7485dea7a14888cc88d2d805854bf
Core tap last commit: 87 minutes ago
HOMEBREW_PREFIX: /usr/local
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: 11.4
XQuartz: 2.7.11 => /opt/X11
</pre>
</details>

## Notes
- I am trying to get the cleanup command to work.
- I have tried reinstalling homebrew and I still have the same issues
- I have tried to overwrite the link for each of the missing links
- I have tried to uninstall and reinstall ghostscript, vim, and p11-kit

## What you expected to happen
I expected cleanup to return with no errors

**Comment by SMillerDev** [comment]
Somehow you changed the permissions on the install. You can use `chown` to change them back.

**Comment by SMillerDev** [comment]
This is not an issue in homebrew, you should ask these questions in discourse (as is in the issue template)
