### ISSUE TITLE
molten-vk missing required headers

### ISSUE THREAD

**Issue by tellowkrinkle** [Homebrew/homebrew-core#52331]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  - Formula installs fine but doesn't include enough files to work fully
  - (Result: `Error: No logs.`)

## What you were trying to do (and why)

Install `molten-vk` and compile `qt5` with vulkan support

## What happened (include command output)

The program I was trying to compile (qt5 with vulkan support) failed because the `mvk_vulkan.h` included in `molten-vk` contains the following includes:
```c
#include <vulkan/vulkan.h>
#include <vulkan-portability/vk_extx_portability_subset.h>
```
however it does not include either of those libraries.  `vulkan/vulkan.h` exists in the formula `vulkan-headers` (which molten-vk does not have as a dependency), and I couldn't find a formula that included `vulkan-portability`

<details>
  <summary>Command output</summary>
  <pre>
/usr/local/include/MoltenVK/mvk_vulkan.h:47:10: fatal error: 'vulkan-portability/vk_extx_portability_subset.h' file not found
#include &lt;vulkan-portability/vk_extx_portability_subset.h&gt;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  </pre>
</details>

## What you expected to happen

Programs that include `MoltenVK/mvk_vulkan.h` compile fine

## Step-by-step reproduction instructions (by running `brew install` commands)

- `brew install molten-vk`
- `echo "#include <MoltenVK/mvk_vulkan.h>" > test.c`
- `echo "int main() { return 0; }" >> test.c`
- `clang test.c`

**Comment by Bo98** [comment]
Try `clang -I/usr/local/opt/molten-vk/libexec/include test.c`. All the Vulkan headers seem to be put in there - perhaps it should be split out a little.

**Comment by tellowkrinkle** [comment]
Ahh yeah they're all there
