### ISSUE TITLE
moreutils build fails on docbook (OSX 10.8)

### ISSUE THREAD

**Issue by dcwar** [Homebrew/homebrew-core#524]
Title says most of it: trying to build `moreutils`, which fails on `docbook`. For whatever it's worth, docbook does successfully build on Tigerbrew….

Gist of console output:
https://gist.github.com/dcwar/395f9d9be7d5d313458e4b6070743c3c

**Comment by ilovezfs** [comment]
This is a ruby 1.8.7 issue. Fastest workaround is to `brew install ruby`, and in your profile set `HOMEBREW_DEVELOPER=1` and `HOMEBREW_RUBY_PATH=/usr/local/opt/ruby/bin/ruby`, at least temporarily while installing the docbook formula. 10.8, HOMEBREW_DEVELOPER, and HOMEBREW_RUBY_PATH are all things not actually supported by Homebrew, so be aware things may break, the sky may fall, etc.

**Comment by mikemcquaid** [comment]
@ilovezfs Probably worth adding a `depends_on :ruby => "2.0"`

**Comment by ilovezfs** [comment]
Oh I'll just fix it :)

**Comment by ilovezfs** [comment]
@dcwar Here's an actual fix: https://github.com/Homebrew/homebrew-core/pull/529

**Comment by ilovezfs** [comment]
@dcwar That PR is superseded by https://github.com/Homebrew/brew/pull/135

If you'd like to try it,
```
brew pull https://github.com/Homebrew/brew/pull/135
```

**Comment by ilovezfs** [comment]
Closed via https://github.com/Homebrew/brew/pull/135

Please brew update and try again.

**Comment by dcwar** [comment]
Thanks so much! Was tied up on another project and this certainly fixed the docbook issue.
