### ISSUE TITLE
dovecot crash with _clock_gettime not found

### ISSUE THREAD

**Issue by brabalan** [Homebrew/homebrew-core#5255]
### Bug reports:

The `imap` process keeps crashing with the following line in the Console

```
Sep 26 16:16:20 charm-ecran ReportCrash[61922]: Saved crash report for imap[61921] version 0 to /Library/Logs/DiagnosticReports/imap_2016-09-26-161620_top.crash
```

The crash report mentions this:

```
Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /usr/local/Cellar/dovecot/2.2.25/lib/dovecot/libdovecot.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
```

I applied the same fix than 964f9dc (I’m on OS X 10.11 with XCode 8) and it fixes the issue.

**Comment by ilovezfs** [comment]
Cool. Looks like we should add that envvar to superenv too. This is the third one that it's fixed today.

**Comment by DomT4** [comment]
@ilovezfs 👍 PR would be wonderful ❤️

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.

**Comment by DomT4** [comment]
I presume this was fixed? A bump was merged in 353cdf918e43de26cb11acce933373297a6b6f09 that passed CI at least.

**Comment by MikeMcQuaid** [comment]
Seems so, cheers @DomT4.

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ nm /usr/local/Cellar/dovecot/2.2.28/lib/dovecot/libdovecot.0.dylib |grep clock
000000000005d075 T _i_my_clock_gettime
iMac-TMP:~ joe$ 
```
