### ISSUE TITLE
brew cleanup failure

### ISSUE THREAD

**Issue by FbMbg** [Homebrew/homebrew-core#52563]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

I tried to execute my little "script" to update my Mac (it's literally just `brew update && brew upgrade && brew cleanup && brew cask upgrade && softwareupdate --install -a`), and it failed. Then I noticed that the error message contained "cleanup" quite often, so I ran `brew cleanup` alone and confirmed that it's this command that fails. 

## What happened

<details>
  <summary>`brew cleanup` output</summary>
  <pre>
Error: no implicit conversion of nil into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:104:in `escape'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:104:in `stale_cask?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:41:in `stale?'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:296:in `block in cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:280:in `each'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:280:in `cleanup_cache'
/usr/local/Homebrew/Library/Homebrew/cleanup.rb:170:in `clean!'
/usr/local/Homebrew/Library/Homebrew/cmd/cleanup.rb:42:in `cleanup'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
  </pre>
</details>

## What you expected to happen

It should have cleanup the unneeded files and symlinks

## Step-by-step reproduction instructions

- upgrade from 10.15.3 to 10.15.4
- run `brew update` and then `brew cleanup`

Again, all issues with `brew doctor` are solved, and the newest Command Line Tools are installed.

**Comment by SMillerDev** [comment]
This should be reported to homebrew/brew. When you report it there please don't remove anything from the issue template. All the information we ask you for is important for debugging and the issue will be closed if you don't provide it.
