### ISSUE TITLE
Ruby upgrade…gems path not (?)

### ISSUE THREAD

**Issue by Zearin** [Homebrew/homebrew-core#52597]
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem? 
  **(N/A)**
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  **(N/A)**
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  **(N/A)**

## What you were trying to do (and why)
Upgrade Ruby.

## What happened (include command output)

The upgrade went fine, but the caveats notice still points to a path for gem binaries for the previous installation.
 
<details>
  <summary>Command output</summary>
  <pre>
```
==> Pouring ruby-2.7.1.catalina.bottle.tar.gz
==> Caveats
By default, binaries installed by gem will be placed into:
  /usr/local/lib/ruby/gems/2.7.0/bin
```
  </pre>

</details>

## What you expected to happen

I think the gem path should mirror the installation...right?  (I’m 
not a regular ruby user.  I just like to keep the latest version for the occasional exploration.)

## Step-by-step reproduction instructions (by running `brew install` commands)

Upgrade ruby.

**Comment by Bo98** [comment]
This is the way Ruby behaves. Gems are generally installed to a directory which has the "patch" part of the version set to 0. This is because Gems installed for 2.7.x are generally compatible with other 2.7.x versions and thus don't require reinstalling.

See the output of: `/usr/local/opt/ruby/bin/ruby -e 'print Gem.ruby_api_version'`.

**Comment by Zearin** [comment]
Cool.  Thanks for the education! 👍
