### ISSUE TITLE
Regression / not updated - graphviz

### ISSUE THREAD

**Issue by ayroblu** [Homebrew/homebrew-core#52596]
See:
#44754

This issue exists again, workaround at the time no longer works

Also of note is the comments at the bottom: https://gitlab.com/graphviz/graphviz/issues/1320

Perhaps some flags aren't being passed in somewhere

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
