### ISSUE TITLE
Warning: Your Homebrew is outdated.

### ISSUE THREAD

**Issue by zg** [Homebrew/homebrew-core#5261]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

I ran `brew update` and then `brew doctor`, but I still get this warning:

```
Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
```

`brew tap`, if relevant:

```sh
$ brew tap
homebrew/core
```

**Comment by DomT4** [comment]
Can you try:
```bash
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
```
If that doesn't work, can you provide `brew config`? Thanks.

**Comment by DomT4** [comment]
This might be a false warning, FWIW, but should be easy enough to find out via the above. We recently removed that `doctor` check as it's not especially relevant now we've moved to tagged releases for users.

**Comment by zg** [comment]
```sh
$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
remote: Counting objects: 47, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 47 (delta 36), reused 32 (delta 21), pack-reused 0
Unpacking objects: 100% (47/47), done.
From https://github.com/Homebrew/brew
   6e57355..7ccc554  master     -> origin/master
HEAD is now at 7ccc554 Merge pull request #1153 from zmwangx/m4a-fixtures
Updated 1 tap (homebrew/core).
==> Updated Formulae
openssl ✔
==> Deleted Formulae
aeskeyfind
$ brew update && brew doctor
Already up-to-date.
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

:+1: 😄

**Comment by DomT4** [comment]
Cool. That solving the problem does make me wonder if it was a false warning, but if it was it'll be resolved when the next tag is cut. Make sure you `brew upgrade openssl` there, the update today was a security release 😉.

Closing as fixed. Shout if you have any more issues 😃.
