### ISSUE TITLE
Dependency issues: libpng, zlib, pkg-config 

### ISSUE THREAD

**Issue by jbattat** [Homebrew/homebrew-core#52612]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Found a possible dependency issue with libpng and zlib, or a pkg-config issue.  (1) zlib is not installed when running `brew install libpng`.  Even after installing `zlib` separately with `brew install zlib`, `pkg-config` doesn't find it.

## What happened (include command output)

On a fresh install of Catalina

`$ brew install libgd`
`$ brew install gtk+`
`$ brew install libpng`
`$ brew install pkg-config`
```
$ pkg-config --cflags gtk+-2.0 
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'libpng', not found
```
OK, will install zlib separately:
`$ brew install zlib`
```
$ pkg-config --cflags gtk+-2.0 
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'libpng', not found
```

OK, will try setting `PKG_CONFIG_PATH`:

```
$ locate zlib.pc
/usr/local/Cellar/zlib/1.2.11/lib/pkgconfig/zlib.pc
...
$ export PKG_CONFIG_PATH=/usr/local/Cellar/zlib/1.2.11/lib/pkgconfig/zlib.pc
$ echo $PKG_CONFIG_PATH
/usr/local/Cellar/zlib/1.2.11/lib/pkgconfig/zlib.pc
```
But same error message:
```
$ pkg-config --cflags gtk+-2.0 
Package zlib was not found in the pkg-config search path.
Perhaps you should add the directory containing `zlib.pc'
to the PKG_CONFIG_PATH environment variable
Package 'zlib', required by 'libpng', not found
```
<details>
  <summary>Command output</summary>
  <pre>

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jbattat/.pyenv/shims/python-config
  /Users/jbattat/.pyenv/shims/python3-config
  /Users/jbattat/.pyenv/shims/python3.8-config
  /Applications/root_v6.20.04/bin/root-config

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

  </pre>
</details>

**Comment by tschoonj** [comment]
see https://github.com/Homebrew/brew/issues/5068

**Comment by MikeMcQuaid** [comment]
Closing in favour of reopening https://github.com/Homebrew/brew/issues/5068.
