### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by Clint2166** [Homebrew/homebrew-core#5262]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I hope that i am doing this correctly.  I am having problems with installing home-brew on OS X 10.11.6.  I believe that i may have a botched installation.  I try tin install now and it says that i have to uninstall.  When i try to uninstall it says it can't find home-brew.  Thanks.

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by zmwangx** [comment]
With the extremely limited information you posted, I would recommend the following:

```sh
PATH=/usr/local/bin:$PATH
sudo chown $(whoami):admin /usr/local/bin
[[ -f /usr/local/Homebrew/bin/brew ]] && ln -sf ../Homebrew/bin/brew /usr/local/bin/brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by Clint2166** [comment]
I appreciate the answer.  I am available to provide whatever additional information you may need.

**Comment by Clint2166** [comment]
appears that seems to have fixed the issue.  I can’t say thanks enough.

**Comment by zmwangx** [comment]
Glad to know.
