### ISSUE TITLE
libquicktime --ffmpeg option is broken with ffmpeg 3

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#527]
See https://github.com/Homebrew/homebrew-core/issues/510

There appears to be no upstream activity at this point, but the `--ffmpeg` option does still build fine against ffmpeg 2. Various Linux distributions are still publishing it with ffmpeg 3 patches such as

https://projects.archlinux.org/svntogit/community.git/tree/trunk/libquicktime-ffmpeg3.patch?h=packages/libquicktime

So choices are to boneyard it, vendor in ffmpeg 2.x, remove the ffmpeg option and wait for something else to break as well, use one of the various the third-party patches that get the ffmpeg option working with ffmpeg 3, or something else if someone has another idea.

**Comment by mikemcquaid** [comment]
I think remove the option.

**Comment by DomT4** [comment]
^ 👍. Unless the patch has been accepted upstream, which doesn't sound likely, don't really want to carry it indefinitely.

**Comment by ilovezfs** [comment]
@DomT4 Looks like https://github.com/Homebrew/homebrew-versions/pull/1238 should allow `depends_on "ffmpeg" => :optional` to become
```
depends_on "homebrew/versions/ffmpeg28" => :optional
```

**Comment by ilovezfs** [comment]
Actually it looks like upstream did merge an ffmpeg 3 patch. It's just hard to see because it's CVS.

http://libquicktime.cvs.sourceforge.net/viewvc/libquicktime/libquicktime/plugins/ffmpeg/video.c?r1=1.130&r2=1.131&pathrev=HEAD

http://libquicktime.cvs.sourceforge.net/viewvc/libquicktime/libquicktime/plugins/ffmpeg/video.c?view=log&r1=1.131&pathrev=HEAD

**Comment by DomT4** [comment]
I'm fine with either applying the patches or using `depends_on "homebrew/versions/ffmpeg28" => :optional`. I prefer the former quite strongly, but `¯\_(ツ)_/¯`

**Comment by mikemcquaid** [comment]
Probably also prefer the patch in this case if it's been merged 👍

**Comment by MikeMcQuaid** [comment]
Closing out upstream issues.
