### ISSUE TITLE
gcc and qt5 failed to build on 10.12

### ISSUE THREAD

**Issue by gregvirgin** [Homebrew/homebrew-core#5272]
Build of gcc and qt5 either run forever or run for many hours until the build stops working. If it fails, it simply gives the last few lines of what appears to be a normal build process. This was a fresh install of homebrew on a fresh OS install of Sierra.

- [Y] Ran `brew update` and retried your prior step?
- [Y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [NA] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

`brew gist-logs <formula>`
gcc: https://gist.github.com/267756fd0fb7ef075b14b488ed86c2e0
qt5: https://gist.github.com/da49c5cd0e1b42eab9809cd4967f0f9f

Assuming they may be related, so posting both of them.

**Comment by zmwangx** [comment]
gcc shouldn't be a problem, install CLT (`sudo xcode-select --install`) and try again.

Qt5 problem is known and tracked in multiple places, notably #1705 #4841.

**Comment by zmwangx** [comment]
"run forever": use `brew install foo --verbose` to monitor progress.

**Comment by gregvirgin** [comment]
Got it. Don't know how I missed that, sorry for the noise.
