### ISSUE TITLE
mit-scheme uses svm1 instead of x86_64

### ISSUE THREAD

**Issue by cleichner** [Homebrew/homebrew-core#52925]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [formula succeeded] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install a library ([scmutils](http://groups.csail.mit.edu/mac/users/gjs/6946/installation.html)) for mit-scheme.

## What happened (include command output)

I got an architecture not supported error: 
https://lists.gnu.org/archive/html/mit-scheme-devel/2020-04/msg00003.html

<details>
  <summary>Command output</summary>
  <pre>

```
~/D/scmutils-20190830 ❯❯❯ ls
COPYING       calculus      general       mechanics     numerics      solve
INSTALL       display       install.sh    mechanics.com poly          uninstall.sh
README        enclose       kernel        mechanics.sh  simplify      units
~/D/scmutils-20190830 ❯❯❯ export MITSCHEME_HEAP_SIZE=100000
export MITSCHEME_BAND=mechanics.com
~/D/scmutils-20190830 ❯❯❯ mit-scheme
MIT/GNU Scheme running under OS X
Type `^C' (control-C) followed by `H' to obtain information about interrupts.


Bad compiled-code version in FASL File: /usr/local/Cellar/mit-scheme/10.1.10/lib/mit-scheme-svm1/mechanics.com
File has: compiled-code interface 3; architecture 14.
Expected: compiled-code interface 3; architecture 13.

Microcode Error: No error handlers.
Error code 0x3a (fasload-compiled-mismatch).

**** Stack Trace ****

{0x119273fb8}
    Return code: [return-code pop-return-error]
    _expression_: #F
{0x119273fc8}
    Return code: [return-code internal-apply]
    _expression_: #F
{0x119273fd8}  ...: [false 0x2]
{0x119273fe0}  ...: [primitive LOAD-BAND]
{0x119273fe8}  ...: "/usr/local/Cellar/mit-scheme/10.1.10/lib/mit-scheme-svm1/mechanics.com"
{0x119273ff0}
    Return code: [return-code non-existent-continuation]
    _expression_: #F

No error handler.
~/D/scmutils-20190830 ❯❯❯
```

  </pre>
</details>

## What you expected to happen
Have mit-scheme libraries compiled for x86_64 work on my x86_64 machine (or have an option to select the native architecture). 

This is how that is supposed to run:
```
MIT/GNU Scheme running under OS X
Type `^C' (control-C) followed by `H' to obtain information about interrupts.

Copyright (C) 2019 Massachusetts Institute of Technology
This is free software; see the source for copying conditions. There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Image saved on Friday August 30, 2019 at 11:20:36 PM
  Release 10.1.10                || Microcode 15.3 || Runtime 15.7 || SF 4.41 || LIAR/x86-64 4.118
  SOS 1.8                        || XML 1.0        || Edwin 3.117  || X11 1.3 || X11-Screen 1.0
  ScmUtils Mechanics.Summer 2019

1 ]=> (edit)

```
## Step-by-step reproduction instructions (by running `brew install` commands)

brew install mit-scheme
wget http://groups.csail.mit.edu/mac/users/gjs/6946/scmutils-20190830.tar.gz
tar xvf scmutils-20190830.tar.gz
cd scmutils-20190830
./install.sh
./mechanics.sh

**Comment by Bo98** [comment]
This appears to have happened because there is no longer a portable C version available, which was used in the past. It looks like it was mistakenly thought by a contributor that “portable SVM” was the replacement.

Apart from downgrading to 9.2, there’s not any easy fix to this. Someone willing could put in the effort to rewrite the formula to compile with a bootstrapped mit-scheme. Pull requests are always welcome here.

Downloading prebuilt x86_64 binaries and shipping that is not an option. Everything in homebrew-core must be built from source - as is the case with many package repositories. Using the binaries to build from source and then shipping what was built from source is acceptable, but will require a pull request to Homebrew/brew to add mit-scheme to the whitelist.

**Comment by riastradh** [comment]
I regret to inform you that neither the 'portable C' version nor the 'portable SVM' version is what you think of as 'built from source'; Homebrew has been using what you think of as a 'prebuilt binary' all along.  The 'portable C' version just uses C as portable assembly language, and the 'portable SVM' version uses a byte code interpreter.  Today they are only useful for running MIT Scheme on CPU architectures for which there's no native compiler back end; there is no reason to prefer them over the native amd64 version on macOS -- the main difference is that they're a lot slower.

It would be nice if there were a way to bootstrap using, say, a C compiler toolchain and a true source-only distribution, but someone would have to do the work to make it happen.  But if you're happy bootstrapping from an existing binary distribution, it's easy -- just pick a staging directory, say /tmp/staging, extract the binary distribution and run `./configure --prefix=/tmp/staging && make -j8 && make install` in mit-scheme-X.Y.Z-x86-64/src, and then extract the source distribution and with /tmp/staging/bin in PATH run `./Setup.sh && ./configure && make -j8 && make install` in mit-scheme-X.Y.Z.

**Comment by jonchang** [comment]
> But if you're happy bootstrapping from an existing binary distribution, it's easy -- just pick a staging directory, say /tmp/staging, extract the binary distribution and run `./configure --prefix=/tmp/staging && make -j8 && make install` in mit-scheme-X.Y.Z-x86-64/src, and then extract the source distribution and with /tmp/staging/bin in PATH run `./configure && make -j8 && make install` in mit-scheme-X.Y.Z/src. (Substitute your favourite number of make jobs for `-j8` according to taste.)

I think we already do this for a number of formulae including e.g., rust. Could you open a pull request that does this?

**Comment by Bo98** [comment]
Looking at some other repositories, I see a number have got it wrong and also don’t really know what the portable C source is. Homebrew isn’t alone in that regards.

Yes, we are happy to bootstrap from an existing binary and that looks to be the way forward.

**Comment by duncanmak** [comment]
@Bo98 Can you take a look at #55136?
