### ISSUE TITLE
brew link mysql@5.6 crashes

### ISSUE THREAD

**Issue by snarfed** [Homebrew/homebrew-core#53030]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

i had `mysql` stable 8.0.19 (bottled) installed, but i wanted 5.6. i ran `brew uninstall mysql`, then `brew install mysql@5.6`; both worked fine. i then noticed that `mysql` was still not yet in my path, which i wanted. i saw this warning in the install output:

_mysql@5.6 is keg-only, which means it was not symlinked into /usr/local, because this is an alternate version of another formula._

...but i was stubborn, so i tried `brew link mysql@5.6` anyway, and it crashed:

```
Error: undefined method `by_macos?' for :versioned_formula:Symbol
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:71:in `block in link'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:40:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/link.rb:40:in `link'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

i ran `brew update` twice and fixed all of `brew doctor`'s warnings, but `brew link mysql@5.6` still crashes with the above error.

if it's not supposed to work for mysql@5.6, that's fine. i'm guessing you still don't want it to crash though. 😁 

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install mysql@5.6
brew link mysql@5.6
```

## Environment details
Mac OS X 10.15.4.

```
$ uname -a
Darwin heaven.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
$ brew --version
Homebrew 2.2.12-56-g793407a
Homebrew/homebrew-core (git revision 5a155; last commit 2020-04-12)
Homebrew/homebrew-cask (git revision ac110; last commit 2020-04-12)
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 2.2.12-56-g793407a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 793407a2e080980636c3ec274429cff2e345672b
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5a155a707c46c3249d89285d6567ebeb6a32dffa
Core tap last commit: 14 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.UIQXxt0VBp/org.macosforge.xquartz:0
HOMEBREW_EDITOR: emacsclient
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.25.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 9.0.1, 1.8.0_25, 1.7.0_80
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: 11.4
XQuartz: 2.7.11 => /opt/X11
```

**Comment by snarfed** [comment]
not specific to `mysql@5.6`; i get the same thing when i try to install and link `mysql@5.7`.

**Comment by issyl0** [comment]
Oops, thanks for the report! This should be fixed by https://github.com/Homebrew/brew/pull/7337. Please `brew update` and try linking again.

**Comment by snarfed** [comment]
confirmed, thanks for the quick fix!
