### ISSUE TITLE
vmtk failed to build on OS X 10.11.6

### ISSUE THREAD

**Issue by diederikfr12** [Homebrew/homebrew-core#5304]
Vmtk failed to build on OS X 10.11.6

Homebrew is up to date, system is ready to brew, no permission errors.

### Bug reports:

I have an error while installing vmtk using homebrew. According to the installation instructions for MacOSX on vmtk.org I deleted: brew python, brew vtk, brew vmtk and brew insighttoolkit and afterwards tried to install vmtk, but I keep getting the same error message. I have Xcode 8.0 installed.

ld: warning: directory not found for option 'L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenCL.framework'
[ 46%] Built target vtkvmtkComputationalGeometryPythonD
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

https://gist.github.com/cb304b0e7f8f573c07cbabc88731f0e0

Could you please help me?

**Comment by dunn** [comment]
I wonder if that 10.11 SDK path is hardcoded in the build script?  It correctly looks for 10.12 elsewhere.

**Comment by dunn** [comment]
Oh, is this a custom formula you wrote?

**Comment by diederikfr12** [comment]
This is not a custom formula from me, I followed the instructions of vmtk.org

http://www.vmtk.org/download/#mac-osx-packages

Due to an unresolved issue in homebrew-science with VTK, in order to install vmtk you need to apply a temporary workaround.

Remove brew python, if installed

brew uninstall python
Remove older versions of vmtk installed with brew:

brew uninstall vmtk
brew uninstall vtk
brew uninstall insight toolkit
Then install vmtk:

brew install https://raw.githubusercontent.com/vmtk/vmtk/master/distribution/homebrew/vmtk.rb

**Comment by dunn** [comment]
OK, thanks.  Since it's from the VMTK repository, though (https://github.com/vmtk/vmtk/tree/master/distribution/homebrew), this is probably something they'll need to fix on their end.  Sorry for the inconvenience!
