### ISSUE TITLE
XercesC static link borked in 3.2.3

### ISSUE THREAD

**Issue by asmaloney** [Homebrew/homebrew-core#53090]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was updating XercesC from 3.2.2 to 3.2.3.

## What happened (include command output)

My code links to the static xerces-c lib and has been working for years.

After updating I get a bunch of link errors:

<details>
  <summary>Link Errors</summary>
  <pre>
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::upperCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSUnicodeConverter::lowerCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_CFStringCreateMutableWithExternalCharactersNoCopy", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::upperCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSUnicodeConverter::lowerCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_CFStringLowercase", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::lowerCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_CFStringUppercase", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::upperCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_CreateTextEncoding", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::discoverLCPEncoding() in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSUnicodeConverter::makeNewXMLTranscoder(char16_t const*, xercesc_3_2::XMLTransService::Codes&, unsigned long, unsigned int, xercesc_3_2::MemoryManager*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_TECClearConverterContextInfo", referenced from:
      xercesc_3_2::MacOSTranscoder::transcodeFrom(unsigned char const*, unsigned long, char16_t*, unsigned long, unsigned long&, unsigned char*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSTranscoder::transcodeTo(char16_t const*, unsigned long, unsigned char*, unsigned long, unsigned long&, xercesc_3_2::XMLTranscoder::UnRepOpts) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSTranscoder::canTranscodeTo(unsigned int) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_TECConvertText", referenced from:
      xercesc_3_2::MacOSTranscoder::transcodeFrom(unsigned char const*, unsigned long, char16_t*, unsigned long, unsigned long&, unsigned char*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSTranscoder::transcodeTo(char16_t const*, unsigned long, unsigned char*, unsigned long, unsigned long&, xercesc_3_2::XMLTranscoder::UnRepOpts) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSTranscoder::canTranscodeTo(unsigned int) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_TECCreateConverter", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::makeNewXMLTranscoder(char16_t const*, xercesc_3_2::XMLTransService::Codes&, unsigned long, unsigned int, xercesc_3_2::MemoryManager*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_TECDisposeConverter", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::makeNewXMLTranscoder(char16_t const*, xercesc_3_2::XMLTransService::Codes&, unsigned long, unsigned int, xercesc_3_2::MemoryManager*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSTranscoder::~MacOSTranscoder() in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_TECGetTextEncodingFromInternetName", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::makeNewXMLTranscoder(char16_t const*, xercesc_3_2::XMLTransService::Codes&, unsigned long, xercesc_3_2::MemoryManager*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_UCCompareText", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::compareIString(char16_t const*, char16_t const*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSUnicodeConverter::compareNIString(char16_t const*, char16_t const*, unsigned long) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_UCCreateCollator", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::MacOSUnicodeConverter(xercesc_3_2::MemoryManager*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_UCDisposeCollator", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::~MacOSUnicodeConverter() in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_UpgradeScriptInfoToTextEncoding", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::discoverLCPEncoding() in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_curl_easy_cleanup", referenced from:
      xercesc_3_2::CurlURLInputStream::~CurlURLInputStream() in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_easy_getinfo", referenced from:
      xercesc_3_2::CurlURLInputStream::CurlURLInputStream(xercesc_3_2::XMLURL const&, xercesc_3_2::XMLNetHTTPInfo const*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_easy_init", referenced from:
      xercesc_3_2::CurlURLInputStream::CurlURLInputStream(xercesc_3_2::XMLURL const&, xercesc_3_2::XMLNetHTTPInfo const*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_easy_setopt", referenced from:
      xercesc_3_2::CurlURLInputStream::CurlURLInputStream(xercesc_3_2::XMLURL const&, xercesc_3_2::XMLNetHTTPInfo const*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_global_cleanup", referenced from:
      xercesc_3_2::CurlNetAccessor::~CurlNetAccessor() in libxerces-c.a(CurlNetAccessor.cpp.o)
      xercesc_3_2::CurlNetAccessor::cleanupCurl() in libxerces-c.a(CurlNetAccessor.cpp.o)
  "_curl_global_init", referenced from:
      xercesc_3_2::CurlNetAccessor::CurlNetAccessor() in libxerces-c.a(CurlNetAccessor.cpp.o)
      xercesc_3_2::CurlNetAccessor::CurlNetAccessor() in libxerces-c.a(CurlNetAccessor.cpp.o)
      xercesc_3_2::CurlNetAccessor::initCurl() in libxerces-c.a(CurlNetAccessor.cpp.o)
  "_curl_multi_add_handle", referenced from:
      xercesc_3_2::CurlURLInputStream::CurlURLInputStream(xercesc_3_2::XMLURL const&, xercesc_3_2::XMLNetHTTPInfo const*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_cleanup", referenced from:
      xercesc_3_2::CurlURLInputStream::~CurlURLInputStream() in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_fdset", referenced from:
      xercesc_3_2::CurlURLInputStream::readMore(int*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_info_read", referenced from:
      xercesc_3_2::CurlURLInputStream::readMore(int*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_init", referenced from:
      xercesc_3_2::CurlURLInputStream::CurlURLInputStream(xercesc_3_2::XMLURL const&, xercesc_3_2::XMLNetHTTPInfo const*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_perform", referenced from:
      xercesc_3_2::CurlURLInputStream::readMore(int*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_remove_handle", referenced from:
      xercesc_3_2::CurlURLInputStream::~CurlURLInputStream() in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_multi_timeout", referenced from:
      xercesc_3_2::CurlURLInputStream::readMore(int*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_slist_append", referenced from:
      xercesc_3_2::CurlURLInputStream::CurlURLInputStream(xercesc_3_2::XMLURL const&, xercesc_3_2::XMLNetHTTPInfo const*) in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_curl_slist_free_all", referenced from:
      xercesc_3_2::CurlURLInputStream::~CurlURLInputStream() in libxerces-c.a(CurlURLInputStream.cpp.o)
  "_kCFAllocatorDefault", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::upperCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSUnicodeConverter::lowerCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
  "_kCFAllocatorNull", referenced from:
      xercesc_3_2::MacOSUnicodeConverter::upperCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
      xercesc_3_2::MacOSUnicodeConverter::lowerCase(char16_t*) in libxerces-c.a(MacOSUnicodeConverter.cpp.o)
ld: symbol(s) not found for architecture x86_64

  </pre>
</details>

## What you expected to happen

I would expect that replacing a static library with a minor version change would not produce link errors.

## Step-by-step reproduction instructions (by running `brew install` commands)

Try to link with Cellar/xerces-c/3.2.3/lib/libxerces-c.a.

## Output of `brew config` and `brew doctor` commands

<pre>
$ brew gist-logs xerces-c
Error: No logs.

$ brew config
HOMEBREW_VERSION: 2.2.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 2ae26808a6793c78f749835aed2ab84cd2fa6544
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 52803b6454d3f1c18998ab2ded50067bf35c750e
Core tap last commit: 38 minutes ago
HOMEBREW_PREFIX: /Users/maloney/dev
HOMEBREW_REPOSITORY: /Users/maloney/dev
HOMEBREW_CELLAR: /Users/maloney/dev/Cellar
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /Users/maloney/dev/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.0 => /Users/maloney/dev/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1

NOTE: All of the following complaints look like the Molten/Vulkan libs/headers I have installed seperately.

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libMoltenVK.dylib
  /usr/local/lib/libSPIRV-Tools-shared.dylib
  /usr/local/lib/libVkLayer_api_dump.dylib
  /usr/local/lib/libVkLayer_khronos_validation.dylib
  /usr/local/lib/libshaderc_shared.1.dylib
  /usr/local/lib/libvulkan.1.2.131.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/SPIRV/GLSL.ext.AMD.h
  /usr/local/include/SPIRV/GLSL.ext.EXT.h
  /usr/local/include/SPIRV/GLSL.ext.KHR.h
  /usr/local/include/SPIRV/GLSL.ext.NV.h
  /usr/local/include/SPIRV/GLSL.std.450.h
  /usr/local/include/SPIRV/GlslangToSpv.h
  /usr/local/include/SPIRV/Logger.h
  /usr/local/include/SPIRV/SPVRemapper.h
  /usr/local/include/SPIRV/SpvBuilder.h
  /usr/local/include/SPIRV/SpvTools.h
  /usr/local/include/SPIRV/bitutils.h
  /usr/local/include/SPIRV/disassemble.h
  /usr/local/include/SPIRV/doc.h
  /usr/local/include/SPIRV/hex_float.h
  /usr/local/include/SPIRV/spvIR.h
  /usr/local/include/glslang/Include/BaseTypes.h
  /usr/local/include/glslang/Include/Common.h
  /usr/local/include/glslang/Include/ConstantUnion.h
  /usr/local/include/glslang/Include/InfoSink.h
  /usr/local/include/glslang/Include/InitializeGlobals.h
  /usr/local/include/glslang/Include/PoolAlloc.h
  /usr/local/include/glslang/Include/ResourceLimits.h
  /usr/local/include/glslang/Include/ShHandle.h
  /usr/local/include/glslang/Include/Types.h
  /usr/local/include/glslang/Include/arrays.h
  /usr/local/include/glslang/Include/intermediate.h
  /usr/local/include/glslang/Include/revision.h
  /usr/local/include/glslang/MachineIndependent/Initialize.h
  /usr/local/include/glslang/MachineIndependent/LiveTraverser.h
  /usr/local/include/glslang/MachineIndependent/ParseHelper.h
  /usr/local/include/glslang/MachineIndependent/RemoveTree.h
  /usr/local/include/glslang/MachineIndependent/Scan.h
  /usr/local/include/glslang/MachineIndependent/ScanContext.h
  /usr/local/include/glslang/MachineIndependent/SymbolTable.h
  /usr/local/include/glslang/MachineIndependent/Versions.h
  /usr/local/include/glslang/MachineIndependent/attribute.h
  /usr/local/include/glslang/MachineIndependent/gl_types.h
  /usr/local/include/glslang/MachineIndependent/glslang_tab.cpp.h
  /usr/local/include/glslang/MachineIndependent/iomapper.h
  /usr/local/include/glslang/MachineIndependent/localintermediate.h
  /usr/local/include/glslang/MachineIndependent/parseVersions.h
  /usr/local/include/glslang/MachineIndependent/preprocessor/PpContext.h
  /usr/local/include/glslang/MachineIndependent/preprocessor/PpTokens.h
  /usr/local/include/glslang/MachineIndependent/propagateNoContraction.h
  /usr/local/include/glslang/MachineIndependent/reflection.h
  /usr/local/include/glslang/Public/ShaderLang.h
  /usr/local/include/glslang/SPIRV/GLSL.ext.AMD.h
  /usr/local/include/glslang/SPIRV/GLSL.ext.EXT.h
  /usr/local/include/glslang/SPIRV/GLSL.ext.KHR.h
  /usr/local/include/glslang/SPIRV/GLSL.ext.NV.h
  /usr/local/include/glslang/SPIRV/GLSL.std.450.h
  /usr/local/include/glslang/SPIRV/GlslangToSpv.h
  /usr/local/include/glslang/SPIRV/Logger.h
  /usr/local/include/glslang/SPIRV/SPVRemapper.h
  /usr/local/include/glslang/SPIRV/SpvBuilder.h
  /usr/local/include/glslang/SPIRV/SpvTools.h
  /usr/local/include/glslang/SPIRV/bitutils.h
  /usr/local/include/glslang/SPIRV/disassemble.h
  /usr/local/include/glslang/SPIRV/doc.h
  /usr/local/include/glslang/SPIRV/hex_float.h
  /usr/local/include/glslang/SPIRV/spvIR.h
  /usr/local/include/shaderc/env.h
  /usr/local/include/shaderc/shaderc.h
  /usr/local/include/shaderc/status.h
  /usr/local/include/shaderc/visibility.h
  /usr/local/include/spirv-tools/libspirv.h
  /usr/local/include/vulkan/vk_icd.h
  /usr/local/include/vulkan/vk_layer.h
  /usr/local/include/vulkan/vk_platform.h
  /usr/local/include/vulkan/vk_sdk_platform.h
  /usr/local/include/vulkan/vulkan.h
  /usr/local/include/vulkan/vulkan_android.h
  /usr/local/include/vulkan/vulkan_core.h
  /usr/local/include/vulkan/vulkan_fuchsia.h
  /usr/local/include/vulkan/vulkan_ggp.h
  /usr/local/include/vulkan/vulkan_ios.h
  /usr/local/include/vulkan/vulkan_macos.h
  /usr/local/include/vulkan/vulkan_metal.h
  /usr/local/include/vulkan/vulkan_vi.h
  /usr/local/include/vulkan/vulkan_wayland.h
  /usr/local/include/vulkan/vulkan_win32.h
  /usr/local/include/vulkan/vulkan_xcb.h
  /usr/local/include/vulkan/vulkan_xlib.h
  /usr/local/include/vulkan/vulkan_xlib_xrandr.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libHLSL.a
  /usr/local/lib/libOGLCompiler.a
  /usr/local/lib/libOSDependent.a
  /usr/local/lib/libSPIRV-Tools-link.a
  /usr/local/lib/libSPIRV-Tools-opt.a
  /usr/local/lib/libSPIRV-Tools-reduce.a
  /usr/local/lib/libSPIRV-Tools.a
  /usr/local/lib/libSPIRV.a
  /usr/local/lib/libSPVRemapper.a
  /usr/local/lib/libglslang.a
  /usr/local/lib/libshaderc.a
  /usr/local/lib/libshaderc_combined.a
  /usr/local/lib/libspirv-cross.a

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
</pre>

**Comment by Bo98** [comment]
Static libraries don't automatically link in dependencies like shared libraries to. xerces-c depends on libcurl and CoreServices.framework. The included CMake files also don't help as they are for the shared library only.

I don't see how this changed in 3.2.3 though.

> has been working for years.

We only started shipping the static library about a year ago, a few months after 3.2.2 was released.

**Comment by asmaloney** [comment]
> has been working for years.

:-) I was compiling it myself before. I didn't remember when it started on brew.

Well this is odd. I've never needed to link anything extra (regardless of if I built it or brew did) and this is the only change I made when I compiled first thing this morning...

The (10 year old, CMake-based) project has never had commands to link libcurl or CoreServices and I've been using the static lib successfully.

I just looked up how I used to build it (3.1.2):
<pre>
./configure CFLAGS="-Os -arch x86_64 -mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}" CXXFLAGS="-Os -arch x86_64 -mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET}" --prefix="${INSTALL_HERE}" --enable-shared=false
</pre>

I haven't looked at the changes in xerces-c - is it possible this changed there?

**Comment by Bo98** [comment]
We do compile xerces-c with CMake rather than autotools so maybe there's a difference in implementation there - might be worth testing out.

The only 3.2.3-specific change I'm aware of is that the static library has been renamed from `libxerces-c-3.2.a` to `libxerces-c.a`.

**Comment by asmaloney** [comment]
Hrm. After investigating I'm still not 100% sure what's going on.

I'm just going to switch to using the dynamic lib since it's not critical that I link statically.

Thank you for your time. I appreciate it!
