### ISSUE TITLE
`brew install zig` installs broken zig: Unable to find target for this triple (no targets are registered)

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#53198]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
only irrelevant unrelated issues
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
NA

## What you were trying to do (and why)

`brew install zig`
(tried both `brew install zig` and `brew install --build-from-source zig` (after brew uninstall zig))
this works, see gist: https://gist.github.com/timotheecour/f7dc4baa86f256695307731e35177dde

then use it:
`zig build-exe --c-source thelloc.c --library c`

## What happened (include command output)
Unable to find target for this triple (no targets are registered)

## What you expected to happen
works, just like it does when I download and unzip https://github.com/ziglang/zig/releases/download/0.6.0/zig-macos-x86_64-0.6.0.tar.xz and use `export PATH=/Users/timothee/Downloads/zig-macos-x86_64-0.6.0/:$PATH`

## Step-by-step reproduction instructions (by running `brew install` commands)
see above

## links
root cause of https://github.com/ziglang/zig/issues/5055

**Comment by SMillerDev** [comment]
It seems the upstream install instructions create a broken install as you figured out. Can you cross-post of there's new instructions there?

**Comment by timotheecour** [comment]
yes, please keep this open though to make life easy towards a fix

**Comment by andrewrk** [comment]
Here's how homebrew can fix this immediately:

 * Stop passing `-DZIG_PREFER_CLANG_CPP_DYLIB=ON`
 * Add this patch:

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -384,6 +384,9 @@ target_link_libraries(zig_cpp LINK_PUBLIC
     ${CLANG_LIBRARIES}
     ${LLD_LIBRARIES}
     ${LLVM_LIBRARIES}
+    "-Wl,/usr/local/opt/llvm/lib/libPolly.a"
+    "-Wl,/usr/local/opt/llvm/lib/libPollyPPCG.a"
+    "-Wl,/usr/local/opt/llvm/lib/libPollyISL.a"
 )
 
 add_library(opt_c_util STATIC ${OPTIMIZED_C_SOURCES})
```

This will solve the problem until LLVM 10.0.1 is released with a fix to https://bugs.llvm.org/show_bug.cgi?id=44870.

**Comment by timotheecour** [comment]
https://github.com/ziglang/zig/pull/5092 would avoid having to patch

**Comment by Bo98** [comment]
I'll look at the situation tomorrow - it's quite late here. From first glance, I'm happy with either way.

**Comment by Bo98** [comment]
Looks like Zig has many other linkage issues depending on how LLVM is built. I explicitly disabled z3 support here: https://github.com/Homebrew/homebrew-core/commit/e3753ac073f67dce6ef3c6bcca20bc65b8650435. It wasn't activated in the bottles we built, but it may have been for those who build from source and had z3 installed already. There is likely more. As such, I can only realistically provide support for Zig when LLVM and/or Zig is installed from a bottle.

The short-term patch for Polly is now applied to the Zig formula. Please run `brew upgrade zig`.
