### ISSUE TITLE
BOOT_JVM_OPTIONS is not passed on to boot anymore

### ISSUE THREAD

**Issue by borkdude** [Homebrew/homebrew-core#53209]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Didn't work.
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? See below.

## What you were trying to do (and why)

I upgraded boot with `brew upgrade boot-clj`.

I have a script where I pass on some settings to `BOOT_JVM_OPTS`:

```
if [ -f .boot-jvm-options ]; then
  OPTS=`cat .boot-jvm-options`
fi

BOOT_JVM_OPTIONS="$OPTS $BOOT_JVM_OPTIONS" boot "$@"
```

This used to work until I upgraded with `brew upgrade boot-clj`.

## What you expected to happen

I expect boot to pick up on `BOOT_JVM_OPTIONS` like it used to.

Installing the boot script from the Github repo and placing that on the path works as expected.

```
$ brew config
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3a6cd5e6e9181cfd910dfbf6214b46c6dcd9d07c
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.ZSEOLshB3L/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.26.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.3, 1.8.0_212
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

**Comment by Bo98** [comment]
Let me know if it works now after a `brew upgade boot-clj`.

**Comment by borkdude** [comment]
@Bo98 That seems to have fixed it. Thanks!
