### ISSUE TITLE
Ruby 2.7.1 and 2.7.1_1 - new issues with Bundler not present in 2.7.0

### ISSUE THREAD

**Issue by sd-trailhead-james** [Homebrew/homebrew-core#53247]
When the Ruby formula was originally updated to v2.7.0, everything worked perfectly, as did the Ruby 2.6.x versions that I had been using previously via `brew install ruby`.

Since the formula was updated to Ruby 2.7.1 and still after the update to formula version 2.7.1_1, I have noticed that I have to manually perform `gem install bundler` prior to being able to use Bundler.

Unfortunately when I perform `gem install bundler` inside a formula, I encounter permissions issues stating that the Homebrew dir where gems live can't be written to.

So I'm opening up this issue in the hopes that someone familiar with what changed between 2.7.0* and 2.7.1* for the Ruby formula can spot what happened that might have caused this and either help me to get the formula fixed or help me with a workaround that I can bake into my formula that depends on Ruby.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] (n/a) ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```shell
$ brew config

HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0295d3e628326f1786b36d5f0e1a68fda6de8a80
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A
```

```shell
$ brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.7m/greenlet/greenlet.h

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.kshrc
```

## What you were trying to do (and why)

I want to install Ruby and use the included Bundler executable, `bundle`, to do something simple, like `bundle exec ls`.

I ran the command `/usr/local/Cellar/ruby/2.7.1_1/bin/bundle exec ls`

## What happened (include command output)

```shell
Gem::GemNotFoundException: can't find gem bundler (= 2.1.4) with executable bundle
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/rubygems.rb:252:in `bin_path'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/rubygems_integration.rb:223:in `bin_path'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/cli/exec.rb:25:in `run'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/exe/bundle:46:in `block in <top (required)>'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
  /usr/local/Cellar/ruby/2.7.1_1/lib/ruby/gems/2.7.0/gems/bundler-2.1.2/exe/bundle:34:in `<top (required)>'
  /usr/local/Cellar/ruby/2.7.1_1/bin/bundle:23:in `load'
  /usr/local/Cellar/ruby/2.7.1_1/bin/bundle:23:in `<main>'
```
## What you expected to happen

A successful execution of `bundle exec ls`, i.e. a list of files in PWD is output to STDOUT.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install ruby` or `brew install ruby@2.7`
2. `cd /project/with/a/Gemfile`
3. `/usr/local/Cellar/ruby/2.7.1_1/bin/bundle exec ls`
4. Observe error report generated by Bundler
5. To fix the problem, run `/usr/local/Cellar/ruby/2.7.1_1/bin/gem install bundler` and repeat step 3 -for successful output.

NOTE: those instructions assume a fresh, clean macOS Catalina machine with a brand new installation of Homebrew. To reset a non-new Homebrew instance back to being able to reproduce the problem:

* Make sure `/usr/local/lib/ruby/gems/2.7.0/gems/bundler-*/exe/bundler` doesn't exist on disk
* Bundler can be uninstalled via `/usr/local/Cellar/ruby/2.7.1_1/bin/gem uninstall bundler`

**Comment by Bo98** [comment]
Thanks for the detailed report!

I think the issue is that Rubygem's bundler and Ruby's bundler don't match in versions. I'll try get that fixed.

**Comment by sd-trailhead-james** [comment]
@Bo98 I can confirm Ruby@2.7.1_2 no longer has the problem. Thank you so much!
