### ISSUE TITLE
Problem with home brew

### ISSUE THREAD

**Issue by rafiindrabi** [Homebrew/homebrew-core#53257]
I am not able to update Homebrew on my mac OSX Yosermite 10.10.5

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by rafiindrabi** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by rafiindrabi** [comment]
I am not able to update Homebrew on my mac OSX Yosermite 10.10.5

**Comment by SMillerDev** [comment]
That is correct, homebrew and apple haven't supported that version for about 10 years.
