### ISSUE TITLE
gettext-0.20.2.catalina.bottle.tar.gz lack emacs lisp files

### ISSUE THREAD

**Issue by alshopov** [Homebrew/homebrew-core#53283]
The bottle https://bintray.com/api/ui/download/homebrew/bottles/gettext-0.20.2.catalina.bottle.tar.gz does not contain the emacs lips files for po-mode.
The bottles for High Sierra and Mojave for the same version however contain it. All packages should contain them as evidenced from https://github.com/Homebrew/homebrew-core/blob/master/Formula/gettext.rb#L29

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by alshopov** [comment]
Respectfully - I do believe I have provided enough information to whomever is maintaining the gettext formula. The `configure` command I linked has the `--with-emacs` argument, therefore as usual the compiled bottle **should** contain the EMACS lisp files - for example when you extract `https://bintray.com/api/ui/download/homebrew/bottles/gettext-0.20.2.mojave.bottle.tar.gz` you will get `po-compat.el`, `po-compat.elc`, `po-mode.el`, `po-mode.elc`, `start-po.el`, `start-po.elc` in  the `gettext/0.20.2/share/emacs/site-lisp/gettext` directory. No such files are available for the Catalina bottle (also linked).

I am OK if you decide to not fix this - I might be the only one affected or it might have been a temporary problem with the build machine. Still, if anyone else has the problem - here is the workaround to be indexed by search machines:
```
# this is shell, 'Cellar' is your cellar
mkdir -p /usr/local/Cellar/gettext/0.20.2/share/emacs/site-lisp/gettext/
# copy *el, and possibly *.elc files either from the mojave bottle
# or from https://ftp.gnu.org/gnu/gettext/gettext-0.20.2.tar.xz
```

**Comment by SMillerDev** [comment]
Why not just fill out the issue template? You clearly have the information required and it makes it easier for everyone.
