### ISSUE TITLE
freeciv install is broken

### ISSUE THREAD

**Issue by pjlsergeant** [Homebrew/homebrew-core#53288]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```$ brew gist-logs freeciv
Error: No logs.```

- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 31a8a991ce7536d6cafa3e40de873292352ed274
Core tap last commit: 69 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit dunno
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.3-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A
```

```$ brew doctor
Your system is ready to brew.```

<!-- To help us debug your issue, please complete these sections: -->

## What you were trying to do (and why)

Install and play freeciv.

## What happened (include command output)

brew appears to install a broken version:

<details>
  <summary>Command output</summary>
  <pre>

```$ freeciv-gtk2
2020-04-18 10:35:56.382 freeciv-gtk2[57179:319840] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
2: Loading tileset "amplio2".```

Hit Start, and then Start again on the next screen, and:

`Segmentation fault: 11`

  </pre>
</details>

## What you expected to happen

The game to load

## Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by pjlsergeant** [comment]
[log.txt](https://github.com/Homebrew/homebrew-core/files/4496001/log.txt)

**Comment by jonchang** [comment]
>  CPU: octa-core 64-bit dunno

What computer is this running on? Are you using a hackintosh?

**Comment by pjlsergeant** [comment]
No, this is a new MacBook Air

**Comment by jonchang** [comment]
I've opened #53290 which migrates freeciv to use the new recommended gtk+3 client.

Can you send me the output of `sysctl -n hw.cpufamily` when you run it from the Terminal? Thanks!

**Comment by jonchang** [comment]
Try running `brew upgrade freeciv` then `freeciv-gtk3`

**Comment by pjlsergeant** [comment]
@jonchang 

`$ sysctl -n hw.cpufamily
943936839`

**Comment by pjlsergeant** [comment]
Hi @jonchang -- upgrading the client has indeed fixed the segfault, and the game is playable. However, there are many small missing pieces from the UI along with a lot of warnings to the console, which I believe are due to a missing gtk theme? Should this be a separate ticket or an appeal to upstream, or what?
