### ISSUE TITLE
llvm 10.0.0_2 missing dependency

### ISSUE THREAD

**Issue by elindsey** [Homebrew/homebrew-core#53355]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

The bottles built for llvm 10.0.0_2 appear to link the z3 theorem prover, but do not model this as a required dependency:

$ /usr/local/opt/llvm/bin/clang
dyld: Library not loaded: /usr/local/opt/z3/lib/libz3.dylib
  Referenced from: /usr/local/Cellar/llvm/10.0.0_2/lib/libLLVM.dylib
  Reason: image not found
Abort trap: 6

Explicitly satisfying that dep with `brew install z3` works. Removing the dep would be preferable.

**Comment by Bo98** [comment]
Thanks! Should be fixed now.
