### ISSUE TITLE
re-Install homebrew failed in EI Capitan 10.11.2

### ISSUE THREAD

**Issue by CrazyPopLin** [Homebrew/homebrew-core#5335]
- [ ✔️] Ran `brew update` and retried your prior step?  
No response, and just stuck there.
- [✔️ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

> Warning: A newer Command Line Tools release is available.
> Update them from Software Update in the App Store.
> 
> 
> Warning: Anaconda is known to frequently break Homebrew builds, including Vim and
> MacVim, due to bundling many duplicates of system and Homebrew-available
> tools.
> 
> If you encounter a build failure please temporarily remove Anaconda
> from your $PATH and attempt the build again prior to reporting the
> failure to us. Thanks!
> 
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
> 
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>     /Users/Crazymumu/anaconda2/bin/curl-config
>     /Users/Crazymumu/anaconda2/bin/freetype-config
>     /Users/Crazymumu/anaconda2/bin/libdynd-config
>     /Users/Crazymumu/anaconda2/bin/libpng-config
>     /Users/Crazymumu/anaconda2/bin/libpng16-config
>     /Users/Crazymumu/anaconda2/bin/python-config
>     /Users/Crazymumu/anaconda2/bin/python2-config
>     /Users/Crazymumu/anaconda2/bin/python2.7-config
>     /Users/Crazymumu/anaconda2/bin/xml2-config
>     /Users/Crazymumu/anaconda2/bin/xslt-config
>     /opt/local/bin/icu-config
>     /opt/local/bin/ncurses6-config
>     /opt/local/bin/ncursesw6-config
>     /opt/local/bin/python2.7-config
>     /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
>     /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
>     /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
> 
> Warning: Python is installed at /Library/Frameworks/Python.framework
> 
> Homebrew only supports building against the System-provided Python or a
> brewed Python. In particular, Pythons installed to /Library can interfere
> with other software installs.
> 
> Warning: You have MacPorts or Fink installed:
>   /opt/local/bin/port
> 
> This can cause trouble. You don't have to uninstall them, but you may want to
> temporarily move them out of the way, e.g.
> 
>   sudo mv /opt/local ~/macports
> 
> Warning: Unbrewed dylibs were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected dylibs:
>     /usr/local/lib/libD4P11_ICBC.dylib
>     /usr/local/lib/libD4PinPad_ICBC.dylib
>     /usr/local/lib/libD4Token_ICBC.dylib
> 
> Warning: Your Xcode (7.2) is outdated
> Please update to Xcode 8.0.
> Xcode can be updated from the App Store.
> 
> 
> Warning: Broken symlinks were found. Remove them with `brew prune`:
>     /usr/local/bin/sublime

- [✔️ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?  
I didn't see this problem.

### Bug reports:
First I installed old  version of homebrew and I need to `brew update`, with no response. Then I google and follow the [tutorial:part2](https://digitizor.com/install-homebrew-osx-el-capitan/) uninstall and re-install homebrew.  
In the re-install, I got error:  

> ==> Tapping homebrew/core
> Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
> remote: Counting objects: 3726, done.
> remote: Compressing objects: 100% (3617/3617), done.
> remote: Total 3726 (delta 13), reused 979 (delta 1), pack-reused 0
> Receiving objects: 100% (3726/3726), 2.95 MiB | 49.00 KiB/s, done.
> Resolving deltas: 100% (13/13), done.
> Checking connectivity... done.
> Tapped 3605 formulae (3,753 files, 9.2M)
> error: RPC failed; result=18, HTTP code = 200
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> Error: Fetching /usr/local/Homebrew failed!
> Failed during: /usr/local/bin/brew update --force  

**brew config** output:  
> HOMEBREW_VERSION: >1.0.0 (no git repository)
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: ff4636bd85b28ebf0d6a94422b76896e4606cf6a
> Last commit: 3 hours ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: c5cc4ca3ecdfc67a72a20842f6f4c35e0d8d0edc
> Core tap last commit: 20 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_REPOSITORY: /usr/local/Homebrew
> HOMEBREW_CELLAR: /usr/local/Cellar
> HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
> CPU: quad-core 64-bit broadwell
> Homebrew Ruby: 2.0.0-p645
> Clang: 7.0 build 700
> Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
> Perl: /usr/bin/perl
> Python: /Users/Crazymumu/anaconda2/bin/python => /Users/Crazymumu/anaconda2/bin/python2.7
> Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
> Java: 1.8.0_65
> macOS: 10.11.2-x86_64
> Xcode: 7.2
> CLT: 7.2.0.0.1.1447826929
> X11: N/A
> MacPorts/Fink: /opt/local/bin/port

Right now, I am using Mac EI Capitan 10.11.2. All three steps output above done after re-install failed.   
Any suggestions will be thankful.

**Comment by MikeMcQuaid** [comment]
> Warning: A newer Command Line Tools release is available.
> Update them from Software Update in the App Store.



> Warning: Your Xcode (7.2) is outdated
> Please update to Xcode 8.0.
> Xcode can be updated from the App Store.

These are not causing your problem but you should do so ASAP.



> Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
> remote: Counting objects: 3726, done.
> remote: Compressing objects: 100% (3617/3617), done.
> remote: Total 3726 (delta 13), reused 979 (delta 1), pack-reused 0
> Receiving objects: 100% (3726/3726), 2.95 MiB | 49.00 KiB/s, done.
> Resolving deltas: 100% (13/13), done.
> Checking connectivity... done.
> Tapped 3605 formulae (3,753 files, 9.2M)
> error: RPC failed; result=18, HTTP code = 200
> fatal: The remote end hung up unexpectedly
> fatal: early EOF
> fatal: index-pack failed
> Error: Fetching /usr/local/Homebrew failed!
> Failed during: /usr/local/bin/brew update --force

This is an error talking to GitHub. There's nothing we can do about it; just rerun `brew update --force` on a good internet connection until it works. If you still can't get it working: contact GitHub support. Sorry!
