### ISSUE TITLE
Favor CLT over Xcode

### ISSUE THREAD

**Issue by michaelblyons** [Homebrew/homebrew-core#5337]
### Troubleshooting:

- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
    + [x] Sort of. See below.

### Bug reports:

I have an old Xcode left over from somewhere, and I had been getting by on CLT until this week. Now homebrew complains that Xcode is out of date even though `xcode-select` is pointed at CLT. 

Is this desired/expected behavior?

```
$ brew config
...
macOS: 10.12-x86_64
Xcode: 6.3.2
CLT: 8.0.0.0.1.1472435881

$ brew upgrade
Error: Your Xcode (6.3.2) is outdated
Please update to Xcode 8.0.
Xcode can be updated from the App Store.

$ xcode-select -p
/Library/Developer/CommandLineTools
```

If so, can I purge Xcode and expect Homebrew to work again?
(I'm filing a new issue rather than posting on #4664.)

**Comment by zmwangx** [comment]
> If so, can I purge Xcode and expect Homebrew to work again?

Yes.

**Comment by DomT4** [comment]
Yeah. If you don't want to use Xcode, get rid of it. If you want to keep it around, please update it to 8.0.
