### ISSUE TITLE
cario 'formulae not found'

### ISSUE THREAD

**Issue by TimJSwan89** [Homebrew/homebrew-core#53391]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Not a link; only this error message:
```
$ brew gist-logs cario
Error: No available formula with the name "cario"
```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.2.13-82-g2bbcab5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bbcab56152d1ff19bbe20a7d310619f167e1f03
Last commit: 8 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 474c67ebc0be15d72830844d8af0b1c5dc9fb836
Core tap last commit: 23 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.iHtVLXYd5K/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_144, 1.7.0_51
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
XQuartz: 2.7.11 => /opt/X11
```

doctor: `Your system is ready to brew.`

## What you were trying to do (and why)

Install `cario`. It is a dependency for `manim`

## What happened (include command output)

<details>
  <summary>
$ brew install cario
</summary>
  <pre>

Updating Homebrew...
Error: No available formula with the name "cario" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

  </pre>
</details>

## What you expected to happen

I expected at least keyword cario, pycario, or py2cario to be found by the search, if not installed.

cario, directly, recommends using MacPorts or fink, last edited 2018:
```
sudo port install cairo
sudo port upgrade cairo
sudo apt-get install cairo
```

However, I see no indication from them that the library is supported by homebrew.

A third-party website, http://macappstore.org/cairo/, suggest in an article dated June 2017 that `brew install cario` functioned at some point.

## Step-by-step reproduction instructions (by running `brew install` commands)

All of the following report no taps or cask:
```
$ brew install cario
$ brew install pycario
$ brew install py2cario
$ brew cask install cario
```
Note: I don't have a good comprehension of exactly how this package manager is organized with casks, bottles, etc. So, I have no idea if it's attempting to "search the appropriate one for cario"

**Comment by Bo98** [comment]
It's `cairo` not `cario`.
