### ISSUE TITLE
mu 1.4 led to some issues

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew-core#53393]
First, `mu index` no longer recognizes `--rebuild` as an option.

https://github.com/Homebrew/homebrew-core/blob/5720b821081d4cf95774527ae1916b3a5d9627c8/Formula/mu.rb#L47

The formula recommends users run `mu index --rebuild` after an update. However, after the update to 1.4, `mu index --rebuild` leads to this error, "error: Unknown option --rebuild (0)." That said, the documentation for `mu` also doesn't seem up to date regarding this change: `--rebuild` still appears in `man mu-index`. So, I'm not sure what—if anything—homebrew should do.

Second, I had to rerun `mu init` after the upgrade to 1.4—`mu` wouldn't function otherwise. That led to a lot of Glib warnings. (Gist here: https://gist.github.com/telemachus/56d209fedead0a24eef6114d4b5da889.) I'm not sure if this is an upstream problem or a mismatch between `glib` and the homebrew bottle. This second problem is probably related to this: https://github.com/djcb/mu/issues/1645.

**Comment by Bo98** [comment]
> The formula recommends users run mu index --rebuild after an update. However, after the update to 1.4, mu index --rebuild leads to this error, "error: Unknown option --rebuild (0)." That said, the documentation for mu also doesn't seem up to date regarding this change: --rebuild still appears in man mu-index. So, I'm not sure what—if anything—homebrew should do.

Yeah, upstream still recommend `mu index --rebuild` in the error output too: https://github.com/djcb/mu/blob/24a6b71bd0552429d3faf32ccf0a4237d50c132a/toys/mug/mug.c#L237-L240

I might just delete the mention of `mu index --rebuild` from the formula. It is up to upstream to properly document what should be done on upgrades - not Homebrew.

> I'm not sure if this is an upstream problem or a mismatch between `glib` and the homebrew bottle

It is an upstream problem. They don't null-terminate this GOptionEntry array:

https://github.com/djcb/mu/blob/58b462d4c3b19601bea21864103ed35e37942809/mu/mu-config.c#L143-L149

**Comment by telemachus** [comment]
Okay. I filed a bug upstream about the problem with `mu index --rebuild`.

https://github.com/djcb/mu/issues/1647
