### ISSUE TITLE
brew cleanup may break running tmux server

### ISSUE THREAD

**Issue by roolebo** [Homebrew/homebrew-core#53394]
I'm not filling some of the points below as they're not applicable for the issue.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I've been using my laptop remotely for a long period and I did run brew update a couple times during the period. I have uptime of 46 days and tmux was running happily for 39 days. Today I run brew update on the remote laptop and tried to reattach to a tmux session I left in the middle of interactive git rebase.

## What happened (include command output)

tmux is not able to attach to existing sessions anymore.

<details>
  <summary>Command output</summary>
  <pre>$ tmux at -d
open terminal failed: can't find terminfo database</pre>
</details>

## What you expected to happen

Attachment to a currently running tmux session succeeds after brew update.

## Root cause

One of the brew updates was followed by brew cleanup. The latter one deleted ncurses used by running tmux server:
```
$ lsof -p $(pgrep tmux)
COMMAND   PID        USER   FD   TYPE             DEVICE   SIZE/OFF                NODE NAME
tmux    48420 user  cwd    DIR                1,4       7328               31550 /Users/user
tmux    48420 user  txt    REG                1,4     568092             2380450 /usr/local/Cellar/tmux/3.0a/bin/tmux
tmux    48420 user  txt    REG                1,4     308312             2320123 /usr/local/Cellar/ncurses/6.1/lib/libncursesw.6.dylib
tmux    48420 user  txt    REG                1,4     248376             2385371 /usr/local/Cellar/libevent/2.1.11_1/lib/libevent-2.1.7.dylib
tmux    48420 user  txt    REG                1,4    1558736 1152921500311885593 /usr/lib/dyld
tmux    48420 user    0u   CHR                3,2        0t0                 310 /dev/null
tmux    48420 user    1u   CHR                3,2        0t0                 310 /dev/null
tmux    48420 user    2u   CHR                3,2        0t0                 310 /dev/null
tmux    48420 user    3   PIPE 0x2e0a1f22c59beb7d      16384                     ->0x513a8de784ac9f40
tmux    48420 user    4   PIPE 0x513a8de784ac9f40      16384                     ->0x2e0a1f22c59beb7d
tmux    48420 user    6u  unix 0x3cfffad7f4fcdebb        0t0                     /private/tmp/tmux-501/default
tmux    48420 user    7u   CHR              15,24   0t639631                 579 /dev/ptmx
tmux    48420 user   18u   CHR              15,21    0t19846                 579 /dev/ptmx
tmux    48420 user   20u   CHR              15,11 0t75530701                 579 /dev/ptmx
tmux    48420 user   21u   CHR              15,19   0t128970                 579 /dev/ptmx

$ ls /usr/local/Cellar/ncurses
6.2
```

`/usr/local/Cellar/ncurses/6.1/lib/libncursesw.6.dylib` doesn't exist anymore.
## Workaround

1. Make a symlink to the missing ncurses library (my tmux server process still depends on 6.1 as can be seen from lsof output above and I have ncurses 6.2 installed):
```
ln -s /usr/local/Cellar/ncurses/6.2 /usr/local/Cellar/ncurses/6.1
```
2. Reattach to all tmux sessions and gracefully close all windows within them
3. Delete the temporary symlink:
```
rm /usr/local/Cellar/ncurses/6.1
```
New tmux sessions can be created/detatched/reattached properly after that but the issue may appear again after another `brew cleanup`. The following issues concern ncurses update on macOS:
tmux/tmux#743 and kovidgoyal/kitty#370

**Comment by SMillerDev** [comment]
It's your own responsibility to restart services after an upgrade. Homebrew can't really help you there.

**Comment by roolebo** [comment]
It's not only about restarting. I would that if I could. I had perfectly running tmux session with many windows I worked in for more than a month then I suddenly couldn't split a window in the session. There was an error that disappeared fast. So I decided to detach the session and attach again, that's how I noticed the error. The point is that brew cleanup breaks currently running program that is not a daemon/service.

I can see a few possible ways how the issue can be handled:
1. Disable auto cleanup altogether with `HOMEBREW_NO_INSTALL_CLEANUP`. This should work as a workaround but I'll lose automatic cleanup. And if I decide to run `brew cleanup` manually I always have to remember about all programs currently running.
2. Make the cleanup a little bit smarter and less damaging to the running applications. `brew cleanup` shouldn't touch packages, i.e. files and libraries still being used by applications. Luckily lsof has an option to check open files and directories in a subtree:
```
       +D D     causes lsof to search for all open instances of directory D and all the files and directories it contains to its complete depth.

                Processing of the +D option does not follow symbolic links within D unless the -x or -x  l option is also specified.  Nor does it search for open files on file system mount points on subdirectories of  D  unless the -x or -x  f option is also specified.

                Note: the authority of the user of this option limits it to searching for files that the user has permission to examine with the system stat(2) function.

                Further note: lsof may process this option slowly and require a large amount of dynamic memory to do it.
                This is because it must descend the entire directory tree, rooted at D, calling stat(2) for each file and directory, building a list of all the files it finds, and searching that list for a match with every open file.  When directory D is large, these steps can take a long time, so use this option prudently.
```

The option can be used to check if cleanup of a package should be skipped during an update if a program still uses the package version. Next time the program is restarted (with new dependencies) the information is cleared and cleanup can proceed with removal of an old package version.

A version of a package is typically contained in a separate directory. So, only limited amount of files has to be checked. Here's an example how lsof could check if something is using ncurses and its execution time:
```
# with no tmux running
$ time lsof +D /usr/local/Cellar/ncurses/6.2
lsof +D /usr/local/Cellar/ncurses/6.2  0.05s user 0.20s system 104% cpu 0.237 total
# with tmux running
$ time lsof +D /usr/local/Cellar/ncurses/6.2
COMMAND  PID    USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
tmux    6214 roolebo  txt    REG    1,4   312924 9965227 /usr/local/Cellar/ncurses/6.2/lib/libncursesw.6.dylib
tmux    6216 roolebo  txt    REG    1,4   312924 9965227 /usr/local/Cellar/ncurses/6.2/lib/libncursesw.6.dylib
lsof +D /usr/local/Cellar/ncurses/6.2  0.04s user 0.20s system 104% cpu 0.236 total
```

**Comment by SMillerDev** [comment]
You updated tmux and 30 days later it ran cleanup. While I’m sure people would be okay reviewing a pull request to block cleanup from removing anything that is in use, the real solution here is for users to restart long running services after an update.

**Comment by MikeMcQuaid** [comment]
> While I’m sure people would be okay reviewing a pull request to block cleanup from removing anything that is in use, the real solution here is for users to restart long running services after an update.

Agreed.

**Comment by roolebo** [comment]
I've seen the issue again on another laptop, couldn't open new windows in tmux. Luckily I had no important business in the windows so I closed everything and restarted tmux.

I may come again with a PR to homebrew/brew repo that adds the check to cleanup command.
