### ISSUE TITLE
shibboleth-sp no longer compiles on Sierra

### ISSUE THREAD

**Issue by FranklinChen** [Homebrew/homebrew-core#5339]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

shibboleth-sp no longer compiles on Sierra.

https://gist.github.com/19b239ddd3e5853140c463419a9779cc

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).
### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by FranklinChen** [comment]
Salient part of the error:

```
checking for apr-1-config... apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.
/usr/local/Homebrew/Library/Homebrew/shims/super/apr-1-config

Failed to execute apr-1-config --cflags

Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
  xcodebuild -license
  sudo xcode-select -switch /path/to/Xcode.app


Failed to execute apr-1-config --cppflags

Xcode and/or the CLT appear to be misconfigured. Try one or both of the following:
  xcodebuild -license
  sudo xcode-select -switch /path/to/Xcode.app

checking for apu-1-config... apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.
no
configure: error: Unable to locate apu-1-config, may need --with-apu1 option.
```

**Comment by dunn** [comment]
Apple removed `apr-1-config` from Xcode 8.  Could you try adding `depends_on "apr"` to the formula, and see if that fixes it? Thanks!

**Comment by fxcoudert** [comment]
This seems to have been fixed, closing.
