### ISSUE TITLE
ponyc 4.0 bottle on 10.11.6 appears to only work with Xcode 8

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew-core#5346]
See #5343, specifically [this comment](https://github.com/Homebrew/homebrew-core/pull/5343#issuecomment-250327795).

If someone could test `brew install -s ponyc` on El Capitan with Xcode 7.3.1 that would be great (I don't have a VM for that).

**Comment by leee** [comment]
@zmwangx is 7.2 acceptable?

```
leee@null ~> sw_vers -productVersion
10.11.4
leee@null ~> xcodebuild -version
Xcode 7.2
Build version 7C68
leee@null ~>
```

**Comment by zmwangx** [comment]
No. And this issue has been fixed two weeks ago. I just forgot to close this issue.

**Comment by zmwangx** [comment]
> No.

By no I mean the bottle doesn't work with 7.2.

Whether building from source works I'm not completely sure. I suppose it should.

**Comment by leee** [comment]
@zmwangx - looks sane to me. http://web.mit.edu/leee/Public/contrib/homebrew-core-5346.txt

**Comment by zmwangx** [comment]
Cool.

**Comment by SeanTAllen** [comment]
@zmwangx we have a user reporting that building from source doesn't work. I'm trying to get them to supply you with more details.
