### ISSUE TITLE
Cannot install gettext in PATH

### ISSUE THREAD

**Issue by Lekensteyn** [Homebrew/homebrew-core#53485]
## What you were trying to do (and why)

I was trying to install the gettext package to obtain the `envsubst` program and make it available in `PATH`.

## What happened (include command output)

As `brew install gettext` suggested the package was keg-only, I ran `brew link --force gettext` a suggested earlier. However, recently this stopped working (no links were created).

<details>
  <summary>Command output</summary>

```
$ brew install gettext
...
==> Pouring gettext-0.20.2.catalina.bottle.tar.gz
==> Caveats
gettext is keg-only, which means it was not symlinked into /usr/local,
because macOS provides BSD gettext.

If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find gettext you may need to set:
  export LDFLAGS="-L/usr/local/opt/gettext/lib"
  export CPPFLAGS="-I/usr/local/opt/gettext/include"

==> Summary
🍺  /usr/local/Cellar/gettext/0.20.2: 1,923 files, 18.6MB
$ brew link --force gettext
Warning: Refusing to link macOS provided/shadowed software: gettext
If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find gettext you may need to set:
  export LDFLAGS="-L/usr/local/opt/gettext/lib"
  export CPPFLAGS="-I/usr/local/opt/gettext/include"
```
</details>

## What you expected to happen

I would expect `envsubst` to become available in `$PATH`.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew install gettext`
2. `brew link --force gettext` (ideally optional)
3. `which envsubst`

## Additional information
The error message claims that `gettext` is shadowed software which was recently (11 April 2020) prevented from linking in Homebrew/homebrew-core@7f32e23a65f3ca0b0a495541bd2913af9120a0c7 by @MikeMcQuaid .

However gettext (the program) does not appear to be installed on macOS 10.15 nor 10.14. None of its libraries are installed:

```
$ find / -type f 2>/dev/null | grep -E '/lib(asprintf|gettext|intl|textstyle)'
/usr/local/Cellar/gettext/0.20.2/lib/...
<no other relevant results>
```

Fow what is worth, the tag was added long time ago in 2009 by @mxcl via Homebrew/homebrew-legacy@bd67abc1216132a3366339e85bb7f0bcc9511883:
> GNU GetText breaks eg. Ruby 1.9 builds, and some other formula I have been building too. But it is required by eg. glib. So to solve this we are going to by default not symlink gettext into the Homebrew prefix.

**Comment by SMillerDev** [comment]
This advice is in the output of your command, which is a way better suggestion then force linking.

```
If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile
```

**Comment by Lekensteyn** [comment]
I did that, but I am not sure whether the keg-only requirement is still valid. gettext is not provided by macOS, contrary to the suggested text.

The only reason I can think of why it would cause failures is due to bad build scripts that somehow check for the availability of `gettext` and trigger wrong behavior. I do not know how Ruby 1.9 builds "and other formula" failed in the past though.

**Comment by MikeMcQuaid** [comment]
Yup, you're right, this is likely no longer accurate. Opening https://github.com/Homebrew/homebrew-core/pull/53489 to try de-keg-onlying it. If that doesn't work well we'll at least update the description.
