### ISSUE TITLE
Patchers beware: cgit patches are dangerous

### ISSUE THREAD

**Issue by zmwangx** [Homebrew/homebrew-core#5353]
I just found out the patch https://anonscm.debian.org/cgit/reproducible/diffoscope.git/patch/?id=261be7 in `diffoscope.rb` now reports different checksum. After fiddling around a little bit, apparently it's caused by a `cgit v0.11.2` to `cgit v0.12` change... 🙈 

I wonder how many of our patches are broken or will be broken due to cgit updates. I'll run an automated check when I have time. People are welcome to beat me to it.

**Comment by MikeMcQuaid** [comment]
Nice spot. A `brew audit` check plus moving these to the homebrew/patches repo seems like the best call 👍

**Comment by DomT4** [comment]
Yeah, we migrated a bunch of them in the past because they broke far too often but it was never audited.

**Comment by ilovezfs** [comment]
I reported this to cgit upstream: https://lists.zx2c4.com/pipermail/cgit/2016-December/003445.html
