### ISSUE TITLE
postgresql puts the SDK include path in the include search list

### ISSUE THREAD

**Issue by fxdupont** [Homebrew/homebrew-core#53676]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/c50c076a9d75f34fe13ab1a762c31a4a
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to build a C++ application using postgresql and boost. The pg_config tool returns a CPPFLAGS with -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include in it and this makes the search of the math.h header file to select the wrong one (SDK one vs clang one).

## What happened (include command output)

cat > bad.cc << EOF
#include <cmath>
EOF
` work well`
g++ -c bad.cc
`fail!`
g++ -c `pg_config --cppflags` bad.cc

<details>
  <summary>Command output</summary>
  <pre>
In file included from bad.cc:1:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: 
      no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: 
      no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: 
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h:749:12: note: 
      'finite' declared here
extern int finite(double)
           ^
In file included from bad.cc:1:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: 
      no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: 
      no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
....
  </pre>
</details>
## What you expected to happen

just to build without errors.

## Step-by-step reproduction instructions (by running `brew install` commands)

`important: system is 10.15.4`
uname -a
> Darwin petrus.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

`important too: Xcode is 11.4.1`
xcodebuild -version
> Xcode 11.4.1
> Build version 11E503a

`IMHO the source of the problem`
which xml2-config
> /usr/bin/xml2-config

`and (split on two lines)`
xml2-config --cflags
> -I/Applications/Xcode.app/Contents/Developer/Platforms/
> MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

`install last postgresql bottle`
brew install postgresql

`create test file`
cat > bad.cc << EOF
#include <cmath>
EOF

`compile it using postgresql CPPFLAGS`
g++ -c `pg_config --cppflags` bad.cc
> bugs

### Findings

I debugged the build of postgresql to find the source of the incorrect include directory: it is from xml2-install from postgresql configure --with-libxml argument. Of course using the homebrew libxml2 instead of the system one should solve the issue but it will add a dependency which is IMHO not justified so I looked for a better solution.

There is already something against silly values returned by system xml2-config in the formula:
```
    # avoid adding the SDK library directory to the linker search path
    ENV["XML2_CONFIG"] = "xml2-config --exec-prefix=/usr"
```
I suggest to change the exec-prefix by prefix. Note that XML2_CONFIG is used in the postgresql configure only for cflags and libs so effects will be only what we expect.

I tried a patched formula to install postgresql from sources and get:

pg_config --cppflags
> -I/usr/local/Cellar/icu4c/66.1/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include -I/usr/include

The SDK include is replaced by -I/usr/include.

The test bad.cc compiles and my application (Kea, local reference of this is https://gitlab.isc.org/isc-projects/kea/-/issues/1199) builds.

I can propose a PR if you'd like (usually PRs are more about new formulas...).

**Comment by Bo98** [comment]
> -I/usr/include.

That's arguably wrong, but happens to work because Homebrew injects the libxml2 includes itself and `/usr/include` doesn't exist on Mojave and later so the `-I` does nothing.

Looking at the PostgreSQL configure script, does it work if you remove the line altogether? It seems that in absence of `XML2_CONFIG`, it uses pkg-config - which likely works better (`pkg-config libxml-2.0 --cflags` returns nothing on Catalina).

**Comment by fxdupont** [comment]
On my box /usr/include does not exist and it is not a problem because of the multiple isysroot both builtin and added by for instance pg_config (hopefully because /usr is not writable even by root with SIP).

I think the -I/usr/include does nothing so removing it should also do nothing...

About the PostgreSQL configure script its code for XML is:
```
#
# XML
#
PGAC_ARG_BOOL(with, libxml, no, [build with XML support],
              [AC_DEFINE([USE_LIBXML], 1, [Define to 1 to build with XML support. (--with-libxml)])])

if test "$with_libxml" = yes ; then
  PGAC_PATH_PROGS(XML2_CONFIG, xml2-config)
  AC_ARG_VAR(XML2_CONFIG, [path to xml2-config utility])dnl
  if test -n "$XML2_CONFIG"; then
    for pgac_option in `$XML2_CONFIG --cflags`; do
      case $pgac_option in
        -I*|-D*) CPPFLAGS="$CPPFLAGS $pgac_option";;
      esac
    done
    for pgac_option in `$XML2_CONFIG --libs`; do
      case $pgac_option in
        -L*) LDFLAGS="$LDFLAGS $pgac_option";;
      esac
    done
  fi
fi

AC_SUBST(with_libxml)
```
so it does not use pkg-config (this BTW does not change your argument).
For cflags it does not matter but the libs are different: in `-lxml2 -lz -lpthread -licucore -lm` I am afraid the `-lxml2` is required.

**Comment by fxdupont** [comment]
This is later:
```
if test "$with_libxml" = yes ; then
  AC_CHECK_LIB(xml2, xmlSaveToBuffer, [], [AC_MSG_ERROR([library 'xml2' (version >= 2.6.23) is required for XML support])])
fi
```
so `-lxml2` should be added to LIBS when it was not before.

**Comment by Bo98** [comment]
Ah, yes the pkg-config changes seem to have not been released yet. It will be arriving in 12.3 coming soon.

**Comment by Bo98** [comment]
> I think the -I/usr/include does nothing

We should check High Sierra where it does do something.

**Comment by fxdupont** [comment]
I have some Mojave boxes so I can help you:
xml2-config --cflags returns `xml2-config --cflags
-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/
Developer/SDKs/MacOSX.sdk/usr/include/libxml2` and with --prefix=/usr
`-I/usr/include/libxml2` so IMHO it should work.

**Comment by Bo98** [comment]
It probably should still return the original path on Mojave - but if you think people interfacing PostgreSQL headers don't need libxml2 in the include path then feel free to create a pull request.

**Comment by fxdupont** [comment]
The bug still remains. Any new?

**Comment by Bo98** [comment]
Is this still happening? It should be fixed in 12.3 which landed in homebrew-core at the weekend.

**Comment by fxdupont** [comment]
It was not fixed. BTW changing the PostgreSQL version did not help because the source of the problem is the libxml2 dependency which was not updated...

As it seems that the markup ate some details the easiest way to trigger the bug is to compile a C++ file including the cmath header file with the flags returned by pg_config.

**Comment by Bo98** [comment]
Ah yes, `XML2_CONFIG` wasn't removed from the formula file - apologies.

**Comment by Bo98** [comment]
The change in #54985 should fix this. The flag is gone entirely:

> pg_config --cppflags
> -I/usr/local/Cellar/icu4c/66.1/include -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include

**Comment by fxdupont** [comment]
Thanks. It works now. Closing!
