### ISSUE TITLE
Fail to install syncthing-inotify: SHA256 mismatch 

### ISSUE THREAD

**Issue by raptium** [Homebrew/homebrew-core#5369]
I've tried several times with `brew install syncthing-inotify` and brew says `SHA256 mismatch` constantly.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/syncthing-inotify.rb#L5

The above line which contains the SHA checksum was updated on Jul 19, however syncthing-inotify [v0.8.3](https://github.com/syncthing/syncthing-inotify/releases/tag/v0.8.3) was tagged on 25 Sep. I don't think it is possible to predict an SHA checksum for a future release 2 months in advance :-)

**Comment by Clete2** [comment]
Made a PR for you. See #5511.

**Comment by DomT4** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-core/pull/5511. Thanks for filing that @Clete2.
