### ISSUE TITLE
libxml2 2.9.4 schema validation issue (downgrade to 2.9.3)

### ISSUE THREAD

**Issue by bertterheide** [Homebrew/homebrew-core#5370]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Formula Requests:

libxml2 version 2.9.4 currently has an issue that prevents schema validation, see: https://bugs.alpinelinux.org/issues/6080.

Is it possible to downgrade the version requested by homebrew to 2.9.3?

Thanks.

**Comment by MikeMcQuaid** [comment]
> Is it possible to downgrade the version requested by homebrew to 2.9.3?

We'd rather apply the upstream patch instead: https://git.gnome.org/browse/libxml2/commit/?id=3169602058bd2d04913909e869c61d1540bc7fb4

Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by bertterheide** [comment]
@MikeMcQuaid, is it not better to wait for an official release of libxml2 version 2.9.5 (that includes this commit)?

**Comment by MikeMcQuaid** [comment]
Perhaps but we don't roll-back versions so it's either an official upstream patch or just wait.

**Comment by ilovezfs** [comment]
@bertterheide did you have a particular concern? There doesn't appear to be anything especially exciting in the patch.

**Comment by DomT4** [comment]
As with most `libxml2` releases there were multiple security fixes in the 2.9.4 release, so downgrading and deliberately reintroducing security issues to people's installations smells bad.

**Comment by CrazyPython** [comment]
(poking thread so an update can be received)

**Comment by MikeMcQuaid** [comment]
@CrazyPython Please don't do that, thanks. Closing this but we'll accept a PR if it's still needed.
