### ISSUE TITLE
`libreadline.6.dylib`: missing R/RStudio dependency after `readline` 7.0 update

### ISSUE THREAD

**Issue by pat-s** [Homebrew/homebrew-core#5374]
I just ran brew update & upgrade, updating `readline` to V 7.0.

Afterwards, `R` failed to open with the error message:
`dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/Cellar/r/3.3.1_2/R.framework/Versions/3.3/Resources/lib/libR.dylib
  Reason: image not found
Abort trap: 6`

`RStudio` just shows a yellow exclamation mark when opening. 

I fixed it by copying the new `libreadline.7.0.dylib` and renaming it to `libreadline.6.dylib` in the `/usr/local/opt/...` folder.

**Comment by ilovezfs** [comment]
It needs to be rebuilt. See https://github.com/Homebrew/homebrew-science/issues/4366#issuecomment-250440625

**Comment by MikeMcQuaid** [comment]
@ilovezfs We should start leaning on the versions changes for this in future: https://github.com/Homebrew/brew/issues/620#issue-168841432

I'll try to write up some docs on how to do this soon but it'll basically be: rename existing formula to version format, add alias, add new formula, switch alias after everything is 🆒

**Comment by MikeMcQuaid** [comment]
@ilovezfs And also: consider moving very popular formulae like this into core.

**Comment by ilovezfs** [comment]
Created a tracking thread in science: https://github.com/Homebrew/homebrew-science/issues/4367

**Comment by MikeMcQuaid** [comment]
(to be explicit though: you're following the process you've always done so I'm not criticising anything here at all)

**Comment by ilovezfs** [comment]
@MikeMcQuaid shall I apply that procedure for https://github.com/Homebrew/homebrew-core/pull/5364? :)

**Comment by MikeMcQuaid** [comment]
@ilovezfs Yeh, that'd be perfect 👍

**Comment by skycaptain** [comment]
Is readline 6 still available via Homebrew? I'm using R on a daily basis. Maybe - just maybe - it'll be wise to provide a homebrew/versions formula for fundamental libs like readline before updating to not stop people from working and update the fundamental formula when all its dependencies are updated too.

**Comment by nicholaspufal** [comment]
FTR: this also broke Ruby's 2.3.1 compilation. It also expects to use version 6 instead.

Also, if you try to use any debugging tool (such as `pry`) it will break too because that relies on version 6.

Doing this update was a really bad idea :( There should be a versioning mechanism in place.

**Comment by ilovezfs** [comment]
brew update to the latest r, which now points at the new readline, and things should be back to normal.
