### ISSUE TITLE
open-scene-graph - Looking for socket in socket - not found (10.12)

### ISSUE THREAD

**Issue by kolen** [Homebrew/homebrew-core#5389]
macOS 10.12

Logs:
https://gist.github.com/anonymous/152c6db5a84192abac24359b6afb89fe

**Comment by kolen** [comment]
Seems that bottle is successfully built: 965e3b8a858aa967f140a2cca7f9be88dfad4218

**Comment by davenquinn** [comment]
I've also got this problem. Formula `--with-qt5` builds unsuccessfully. QT is installed (bottled). The bottled formula builds, but I need the QT links for working with OSGEarth.

**Comment by ilovezfs** [comment]
This fixes it: https://github.com/Homebrew/homebrew-core/pull/6013

**Comment by ilovezfs** [comment]
The current version in homebrew is now 3.5.5 which does not have this bug.

@kolen thank you for reporting this!
