### ISSUE TITLE
Launchctl in a test block does not load a service any longer

### ISSUE THREAD

**Issue by lifepillar** [Homebrew/homebrew-core#5393]
I am seeing the problem in the subject under macOS 10.12 when testing the `launch_socker_server` formula, or in the `madlib` formula from homebrew-science (see https://github.com/Homebrew/homebrew-science/pull/4360).

For example, `brew test launch_socker_server` produces this message in the console:

```
com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100050.Aqua):
Caller not allowed to perform action: launchctl.11317, action = service bootstrap,
code = 1: Operation not permitted, uid = 501, euid = 501, gid = 20, egid = 20, asid = 100050
```

Similarly for `madlib`: from the command line, the PostgreSQL service is started, but not when it is launched from the test.

I have tried to replace the deprecated `load` subcommand with `bootstrap` and any imaginable combination of target domains, but without success (I always get permission denied). Any idea what is going on?

**Comment by MikeMcQuaid** [comment]
This is a sandbox error and we'll need to provide read/write access to those locations or just rewrite these tests to be more compatible.

**Comment by zbentley** [comment]
Resolving this issue would be very useful; if I had access to `launchctl`, I could write much more thorough tests for several things. 

However, it'd be important to prevent config leaks (e.g. tests blow up, leave stuff in launchd that wasn't there before). That's probably accomplished easiest by making sure code reviewers give `test` blocks a fair amount of scrutiny; it could also be accomplished via a convenience wrapper function for `launchd` that ensures things get uninstalled on exit no matter what.

**Comment by MikeMcQuaid** [comment]
> just rewrite these tests to be more compatible.

I'd suggest this is the best fix here. We'll review a PR for Homebrew/brew which adds sandbox paths where necessary, though.
