### ISSUE TITLE
Brew update fails with permissions denied when two users are using brew on machine

### ISSUE THREAD

**Issue by emartynov** [Homebrew/homebrew-core#53937]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem? 
This is the output of the update:
```
touch: /usr/local/Homebrew/.git/FETCH_HEAD: Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied
/usr/local/Homebrew/Library/Homebrew/cmd/update.sh: line 548: /usr/local/Homebrew/.git/UPDATE_FAILED: Permission denied
touch: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git/FETCH_HEAD: Permission denied
error: cannot open .git/FETCH_HEAD: Permission denied
/usr/local/Homebrew/Library/Homebrew/cmd/update.sh: line 548: /usr/local/Homebrew/.git/UPDATE_FAILED: Permission denied
fatal: Unable to create '/usr/local/Homebrew/.git/index.lock': Permission denied
fatal: Unable to create '/usr/local/Homebrew/.git/index.lock': Permission denied
error: could not lock config file .git/config: Permission denied
Already up-to-date.
```

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
This is the output of the doctor:
```
Your system is ready to brew.
```

## What you were trying to do (and why)

Update brew.

## What happened (include command output)

Was not able to update.

## Step-by-step reproduction instructions (by running `brew install` commands)

The permissions for the folder are:
```
ls -la /usr/local/Homebrew/.git/FETCH_HEAD
-rw-r--r--  1 user2  admin  15863 Apr 17 12:29 /usr/local/Homebrew/.git/FETCH_HEAD
```

The permissions for ~ folder are:
```
drwxr-xr-x+ 36 user1  staff   1152 Apr 28 23:42 .
```

User1 was created during mac setup. It has admin label in the Mac preferences.
User2 was created through user preferences as admin.
User2 ran `brew doctor` and applied all suggestions for the folder permissions.

**Comment by SMillerDev** [comment]
1. This issue is related to the package manager and not to the packages so should not be here.

1. https://docs.brew.sh/FAQ#why-does-homebrew-say-sudo-is-bad
> If you need to run Homebrew in a multi-user environment, consider creating a separate user account especially for use of Homebrew.

Homebrew assumes your system is single user to make it's install work and this assumption holds true for the vast majority of installs. If you need a multi user setup making a homebrew user might be the best way.
