### ISSUE TITLE
Question regarding ~/Library/Caches/Homebrew

### ISSUE THREAD

**Issue by zg** [Homebrew/homebrew-core#5395]
Why doesn't ~/Library/Caches/Homebrew get wiped when running `brew clean`? Just curious, as I noticed there were a lot of \*.tar.* files sitting in that folder but they don't seem relevant.

**Comment by DomT4** [comment]
By default we don't purge anything newer than 14 days old. If you want to be punchier you can choose the days:
```bash
brew cleanup --prune=0
```
for everything.
```bash
brew cleanup --prune=2
```
for everything older than 2 days, etc.

**Comment by zg** [comment]
Sweet, thank you for the timely response. 😄

**Comment by DomT4** [comment]
No worries 😃. Not sure if you were aware, but most `brew` subcommands now have a `--help` flag with a decent usage output.
