### ISSUE TITLE
Check URL Error Message

### ISSUE THREAD

**Issue by nagymusic** [Homebrew/homebrew-core#53998]
I'm using tiMIDIty to compose MIDI data using [Abjad](https://abjad.github.io/). The .py files compile with no problem and the timidity playback is fine, except that I get this error message in the terminal every time::

`Check URL type=7 Check URL type=2 Check URL type=1 open url (type=1, name=/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg) url_file_open(/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg)`

Would you happen to have any suggestions on how to make the error message go away? Do I need to configure the .cfg file? 

Thank you!

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by nagymusic** [comment]
Of course! Could you advise on how to fill out the issue template. I’m sorry for asking, but can’t seem to find a link or option. Is it one of these options: https://github.com/Homebrew/homebrew-core/issues/new/choose <https://github.com/Homebrew/homebrew-core/issues/new/choose>

Thank you!

**Comment by SMillerDev** [comment]
It was prefilled when you made this issue, it is the first option in the links you send

**Comment by nagymusic** [comment]
I just resubmitted my question. I did the best I could. My apologies for I’m relatively new to the forum.
I appreciate your patience and help.

Thank you!
