### ISSUE TITLE
Check URL Error Message with Timidity

### ISSUE THREAD

**Issue by nagymusic** [Homebrew/homebrew-core#54001]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm using tiMIDIty installed with homebrew on a Mac: timidity: stable 2.15.0 (bottled) I use it to compose MIDI data using [Abjad](https://abjad.github.io/). The .py files compile with no problem and the timidity playback is fine, except that I get this error message below.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
Check URL type=7 Check URL type=2 Check URL type=1 open url (type=1, name=/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg) url_file_open(/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg)
  </pre>
</details>

## What you expected to happen

Not to receive the error message.

## Step-by-step reproduction instructions (by running `brew install` commands)

I installed timidity using `brew install timidity` as explained on this [page](https://formulae.brew.sh/formula/timidity).

**Comment by SMillerDev** [comment]
What command do you run when that error shows up?

**Comment by nagymusic** [comment]
I run timidity file_name.midi

**Comment by issyl0** [comment]
Timidity will now print the output that you'd expect: what file is playing and which instruments it's using. Please `brew upgrade timidity` to get the fixed version.

Thanks for submitting this issue and for using Homebrew, @nagymusic!

**Comment by nagymusic** [comment]
Thank you! It’s working like a charm.
