### ISSUE TITLE
Have adoptopenjdk8 installed but Gradle depends on openjdk

### ISSUE THREAD

**Issue by javenwang** [Homebrew/homebrew-core#54009]
## What you were trying to do (and why)

I want to upgrade Gradle from 6.1.1 to 6.3, and I've adoptopenjdk8 installed.

## What happened (include command output)

Homebrew try to install openjdk when I upgrade Gradle

<details>
  <summary>Command output</summary>
  <pre>
$ brew cask list | grep openjdk
adoptopenjdk11
adoptopenjdk8
</pre>
<pre>
$ brew upgrade gradle
==> Upgrading 1 outdated package:
gradle 6.1.1 -> 6.3
==> Upgrading gradle 6.1.1 -> 6.3
==> Installing dependencies for gradle: openjdk
==> Installing gradle dependency: openjdk
^C
  </pre>
</details>

## What you expected to happen

Homebrew should not install openjdk

**Comment by SMillerDev** [comment]
Homebrew switched to a source build Java version months ago so we can better test dependencies and updates. This is intended behavior.
