### ISSUE TITLE
Check URL Error Message with Timidity

### ISSUE THREAD

**Issue by nagymusic** [Homebrew/homebrew-core#54000]
I'm using tiMIDIty installed with homebrew on a Mac: `timidity: stable 2.15.0 (bottled)` I use it to compose MIDI data using [Abjad](https://abjad.github.io/). The .py files compile with no problem and the timidity playback is fine, except that I get this error message below. 

`Check URL type=7 Check URL type=2 Check URL type=1 open url (type=1, name=/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg) url_file_open(/usr/local/Cellar/timidity/2.15.0/share/timidity/timidity.cfg)
`

I ran `brew doctor` and `brew cleanup`, but the issue persisted.
Would you happen to have any suggestions on how to make the error message go away? Do I need to configure the `'timidity.cfg'` file?

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by SMillerDev** [comment]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?



## What you were trying to do (and why)



## What happened (include command output)



<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen



## Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by nagymusic** [comment]
I’m sorry for double-emailing you, but I did follow the template. Should I have left the instructions? I figured I may remove them. In included the information I had to the best of my ability.

I perfectly understand if you still wish to close my question. I simply wanted to ask for clarification since I  accidentally posted my query on a different list.

**Comment by SMillerDev** [comment]
Yes, all of the template must be in your issue. Don't remove any of it.

**Comment by SMillerDev** [comment]
This is also printed rather large at the start of the template:

# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by nagymusic** [comment]
Okay. I’m just about to submit it again. I’m including the information to the best of my ability. Thanks for your patience!
