### ISSUE TITLE
glib: gmacros.h assertions fail on macOS

### ISSUE THREAD

**Issue by twogee** [Homebrew/homebrew-core#5404]
[This discussion](http://stackoverflow.com/questions/39686986/can-t-install-perl-module-glib-on-os-x-el-capitan) describes the issue. Please look at suggestions from [Michael Schwern](https://github.com/schwern).

**Comment by MikeMcQuaid** [comment]
Can you summarise the discussion/solution here, please?

**Comment by zmughal** [comment]
Just gathering some details on why this is failing:

On my system:

`/usr/local/Cellar/glib/2.50.0/lib/glib-2.0/include/glibconfig.h:52`
```c
typedef unsigned long guint64;
```

`/usr/local/Cellar/glib/2.50.0/include/glib-2.0/glib/gtypes.h:422`
```c
static inline gboolean _GLIB_CHECKED_ADD_U64 (guint64 *dest, guint64 a, guint64 b) {
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  return !__builtin_uaddll_overflow(a, b, (unsigned long long *) dest); }
```

The specific failure appears when the `-arch i386` flag is used for `clang` as follows:
```bash
# Fails
bash-3.2$ clang `pkg-config --libs --cflags glib-2.0` -arch x86_64 -arch i386 test.c 2>/dev/null && echo "Success"

# Succeeds
bash-3.2$ clang `pkg-config --libs --cflags glib-2.0` -arch x86_64  test.c 2>/dev/null && echo "Success"
Success

# Succeeds
bash-3.2$ clang `pkg-config --libs --cflags glib-2.0`   test.c 2>/dev/null && echo "Success"
Success
```

So in that `i386` case, the error is an assertion failure due to a mismatch in the typedefs:
```error
In file included from test.c:2:
In file included from /usr/local/Cellar/glib/2.50.0/include/glib-2.0/glib.h:30:
In file included from /usr/local/Cellar/glib/2.50.0/include/glib-2.0/glib/galloca.h:32:
/usr/local/Cellar/glib/2.50.0/include/glib-2.0/glib/gtypes.h:423:3: error: '_GStaticAssertCompileTimeAssertion_0' declared as an array with a negative size
  G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/glib/2.50.0/include/glib-2.0/glib/gmacros.h:232:103: note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                                                                      ^~~~~~~~~~~~~~~
1 error generated.
```

This `-arch i386` flag appears due to the system Perl's `ccflags` configuration:
```bash
bash-3.2$ perl -MConfig -E 'say $Config{ccflags}'
-arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector
```

**Comment by zmughal** [comment]
Fix:

```bash
ARCHFLAGS="-arch x86_64" cpanm --verbose Glib
```

This tells Perl's ExtUtils::MakeMaker to only build Glib as a 64-bit library.

**Comment by MikeMcQuaid** [comment]
As there's no `brew install` that seems to produce this and MacPorts is patching it's an upstream issue that should be reported, addressed and patched there. We will take patches that have been accepted upstream in a PR.

**Comment by gioele** [comment]
FYI: the upstream bug report can be found at <https://bugzilla.gnome.org/show_bug.cgi?id=780238>.

**Comment by ilovezfs** [comment]
The way to fix this in Homebrew is to just use `ENV.refurbish_args` in a formula. We apply this automatically when formulae use `make` but otherwise do not.
