### ISSUE TITLE
Bottle+Cask at the same time?

### ISSUE THREAD

**Issue by mccarverone** [Homebrew/homebrew-core#54134]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to install HandBrake from bottle (which is the CLI) and HandBrake from cask (which is the GUI) at the same time. No compiling involved so I think gist-logs are unnecessary?

## What happened (include command output)

If I install homebrew from bottle while homebrew cask is already installed I get "skipping link" and the cli does not get installed.

<details>
  <summary>Command output</summary>
  <pre>

riccardo@mangiafuoco ~ % brew install handbrake --verbose
==> Downloading https://homebrew.bintray.com/bottles/handbrake-1.3.1.catalina.bottle.tar.gz
Already downloaded: /Users/riccardo/Library/Caches/Homebrew/downloads/ca97875c057feebae938166f9069411248b844338cc7c7aeba8ac2582ce26c7d--handbrake-1.3.1.catalina.bottle.tar.gz
==> Verifying ca97875c057feebae938166f9069411248b844338cc7c7aeba8ac2582ce26c7d--handbrake-1.3.1.catalina.bottle.tar.gz checksum
==> Pouring handbrake-1.3.1.catalina.bottle.tar.gz
tar xof /Users/riccardo/Library/Caches/Homebrew/downloads/ca97875c057feebae938166f9069411248b844338cc7c7aeba8ac2582ce26c7d--handbrake-1.3.1.catalina.bottle.tar.gz -C /var/folders/8f/6lzf2jt13d78kbg8b9d9dypm0000gn/T/d20200502-716-n4pn3o
cp -pR /var/folders/8f/6lzf2jt13d78kbg8b9d9dypm0000gn/T/d20200502-716-n4pn3o/handbrake/. /usr/local/Cellar/handbrake
chmod -Rf +w /var/folders/8f/6lzf2jt13d78kbg8b9d9dypm0000gn/T/d20200502-716-n4pn3o
==> Finishing up
==> handbrake cask is installed, skipping link.
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200502-1287-378xok.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/handbrake.rb
==> Summary
🍺  /usr/local/Cellar/handbrake/1.3.1: 8 files, 36.8MB

  </pre>
</details>

## What you expected to happen

Everything is fine when I pour the bottle without having the cask installed.

<details>
  <summary>Command output</summary>
  <pre>

riccardo@mangiafuoco ~ % brew install handbrake --verbose  
==> Downloading https://homebrew.bintray.com/bottles/handbrake-1.3.1.catalina.bottle.tar.gz
Already downloaded: /Users/riccardo/Library/Caches/Homebrew/downloads/ca97875c057feebae938166f9069411248b844338cc7c7aeba8ac2582ce26c7d--handbrake-1.3.1.catalina.bottle.tar.gz
==> Verifying ca97875c057feebae938166f9069411248b844338cc7c7aeba8ac2582ce26c7d--handbrake-1.3.1.catalina.bottle.tar.gz checksum
==> Pouring handbrake-1.3.1.catalina.bottle.tar.gz
tar xof /Users/riccardo/Library/Caches/Homebrew/downloads/ca97875c057feebae938166f9069411248b844338cc7c7aeba8ac2582ce26c7d--handbrake-1.3.1.catalina.bottle.tar.gz -C /var/folders/8f/6lzf2jt13d78kbg8b9d9dypm0000gn/T/d20200502-1661-5wbwa5
cp -pR /var/folders/8f/6lzf2jt13d78kbg8b9d9dypm0000gn/T/d20200502-1661-5wbwa5/handbrake/. /usr/local/Cellar/handbrake
chmod -Rf +w /var/folders/8f/6lzf2jt13d78kbg8b9d9dypm0000gn/T/d20200502-1661-5wbwa5
==> Finishing up
ln -s ../Cellar/handbrake/1.3.1/bin/HandBrakeCLI HandBrakeCLI
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200502-2233-1w1xql3.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/handbrake.rb
==> Summary
🍺  /usr/local/Cellar/handbrake/1.3.1: 8 files, 36.8MB

  </pre>
</details>

Then I might as well install the cask and I get both installed correctly.

Looks like this is an expected behaviour? But it doesn't make sense to me.

Many thanks
Riccardo

**Comment by SMillerDev** [comment]
Both install the same thing so there is no real way to get this to work.

**Comment by mccarverone** [comment]
I am sorry I didn't quite get your reply.

The cask version only includes the .app (GUI) while the bottle only includes the cli. They are not the same thing.

**Comment by SMillerDev** [comment]
They are both handbrake, they both install the same libraries and they're not meant to be used at the same time.
