### ISSUE TITLE
Bison: Source Code is Not Found

### ISSUE THREAD

**Issue by mingtsay** [Homebrew/homebrew-core#54260]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrading outdated packages with command `brew update && brew upgrade`.

## What happened (include command output)

DownloadError: Failed to download resource "bison"

<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading bison 3.5.4 -> 3.5.91
==> Downloading https://ftp.gnu.org/gnu/bison/bison-3.5.91.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ftpmirror.gnu.org/bison/bison-3.5.91.tar.xz
==> Downloading from https://mirrors.kernel.org/gnu/bison/bison-3.5.91.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "bison"
Download failed: https://ftpmirror.gnu.org/bison/bison-3.5.91.tar.xz
  </pre>
</details>

## What you expected to happen

The `bison` package should switch to an exists version.
This should be fixed by changing the url to the exists version of this package.
The `3.5.91` is a beta version, not a release version. (https://github.com/Homebrew/homebrew-core/commit/b5c3e88e122274ca52c74374b4b9001e1ddfa5cb#commitcomment-38906782)

## Step-by-step reproduction instructions (by running `brew install` commands)

For `bison` is not installed: `brew install bison`
For having `bison` version <= `3.5.4`: `brew update && brew upgrade bison`

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/pull/54259

**Comment by mingtsay** [comment]
Note for the users ever have this error:
`Error: File exists @ dir_s_mkdir - /usr/local/Cellar/bison/3.5.4/.brew`

Uninstall `bison` and reinstall it will solve this problem:
`brew remove bison && brew install bison`

Affect to who has installed version `3.5.4` and brew is trying to upgrade it from `3.5.4` to `3.5.4`.

**Comment by Bo98** [comment]
If it's reproducable, it might be a bug in `brew`.

**Comment by mingtsay** [comment]
Reproduce steps:

1. `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula`
2. `brew remove bison` to ensure you don't have `bison` installed.
3. `git checkout 348a8a58f2bc665f5c75be6febefc23f13605bc4 bison.rb` for `bison` version `3.5.4`
4. `HOMEBREW_NO_AUTO_UPDATE=1  brew install bison` to install the specified version of `bison`.
5. `git checkout 0058caaa5159082c9ec689983925dd79c5b21639 bison.rb` for `bison` version `3.5.4` (downgraded)
6. `HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade bison` to upgrade `bison` to the downgraded one.

<details>
  <summary> Reproduce command for copy and paste</summary>
  <pre>
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
brew remove bison
git checkout 348a8a58f2bc665f5c75be6febefc23f13605bc4 bison.rb
HOMEBREW_NO_AUTO_UPDATE=1  brew install bison
git checkout 0058caaa5159082c9ec689983925dd79c5b21639 bison.rb
HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade bison</pre>
</details>

<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading 1 outdated package:
bison 3.5.4 -> 3.5.4
==> Upgrading bison 3.5.4 -> 3.5.4
==> Downloading https://ftp.gnu.org/gnu/bison/bison-3.5.4.tar.xz
Already downloaded: /Users/mt/Library/Caches/Homebrew/downloads/0cd0b972eeb61898d808838afbf7d7142f74bab484acb305448d24e60dd18dce--bison-3.5.4.tar.xz
==> ./configure --prefix=/usr/local/Cellar/bison/3.5.4
==> make install
Error: File exists @ dir_s_mkdir - /usr/local/opt/bison/.brew</pre>
</details>

Cleaning up:

1. `cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula`
2. `git reset --hard HEAD` to switch to the latest Formula list and ignore changes.
3. `brew remove bison && brew install bison` to reinstall latest `bison`

<details>
  <summary> Cleaning up command for copy and paste</summary>
  <pre>
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
git reset --hard HEAD
brew remove bison && brew install bison</pre>
</details>
