### ISSUE TITLE
`nvm exec` fails when installing nvm via homebrew

### ISSUE THREAD

**Issue by libinvarghese** [Homebrew/homebrew-core#54275]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs nvm` https://gist.github.com/537173084c9ad20d53828353f576dac1
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I was trying to execute `nvm exec`, to run a command under a specific version of node.
```
nvm exec 12.16.2 echo hello
```

However I get
```
Running node v12.16.2 (npm v6.14.4)
nvm:854: no such file or directory: /Users/xxxx/.nvm/nvm-exec
```

After following the instruction in https://github.com/nvm-sh/nvm/issues/856#issuecomment-417187758 , it started to work.

I would suggest to add the instructions in https://github.com/nvm-sh/nvm/issues/856#issuecomment-417187758 as part the formula caveats, which will be displayed immediately after `brew install nvm` or in `brew log nvm`

## What happened (include command output)
As per the instructions in `brew install nvm` I have set to `~/.nvm`, and since nvm looks for nvm-exec in the NVM_DIR, it is failing

<details>
  <summary>Command output</summary>
  <pre>
Running node v12.16.2 (npm v6.14.4)
nvm:854: no such file or directory: /Users/xxxx/.nvm/nvm-exec
  </pre>
</details>

## What you expected to happen
```
Running node v12.16.2 (npm v6.14.4)
hello
```

## Step-by-step reproduction instructions (by running `brew install` commands)
I am using zsh
```
brew install nvm
mkdir ~/.nvm

cat <<EOF > ~/.zshrc
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
EOF

zsh -l

nvm install 12.6.2
nvm exec 12.16.2 echo hello
```

## Resolution
```
cd ~/.nvm
ln -s $(brew --prefix nvm)/nvm-exec
```
I would advise to add this to the formula caveats

**Comment by SMillerDev** [comment]
I consider the fact that it's looking for these files in an upstream bug. As a programmer I understand where it's coming from but this means it's impossible to package it.

**Comment by libinvarghese** [comment]
Yes, I understand it is not possible to package it. Hence I advice to add this info in the [caveats](https://docs.brew.sh/Formula-Cookbook#caveats) section of the formula.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) should help and we're happy to walk you through anything else.

Thanks!
