### ISSUE TITLE
Trying to install flexbar 

### ISSUE THREAD

**Issue by JackCrook** [Homebrew/homebrew-core#54298]
- [Y] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I am trying to install Flexbar using " brew install homebrew/core/flexbar "

## This is the output: 
Error: No available formula with the name "homebrew/core/flexbar" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.

**Comment by SMillerDev** [comment]
Flexbar is not available in homebrew so this is the correct behaviour. https://docs.brew.sh/Adding-Software-to-Homebrew can help you to get it added to homebrew though.
