### ISSUE TITLE
Emscripten formula does not install node dependencies

### ISSUE THREAD

**Issue by kevzettler** [Homebrew/homebrew-core#54438]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
`brew install emscripten` 
and use the `emcc` executable

## What happened (include command output)
```
emcc: error: html-minifier-terser was not found! Please run "npm install" in Emscripten root directory to set up npm dependencies!
```

```
 kevs-mbp:flare-engine kevzettler$ which emcc
/usr/local/bin/emcc
kevs-mbp:flare-engine kevzettler$ ls -lash /usr/local/bin/emcc
0 lrwxr-xr-x  1 kevzettler  admin    37B May  8 15:51 /usr/local/bin/emcc -> ../Cellar/emscripten/1.39.15/bin/emcc
```

## Step-by-step reproduction instructions (by running `brew install` commands)

see: https://github.com/emscripten-core/emscripten/issues/11117

emscripten formula expects post-install dependencies with `npm` that are missing from the home brew formula. This is obvious because the formula installs `node` as a dependency but does nothing else with it . 

see: https://github.com/Homebrew/homebrew-core/blob/master/Formula/emscripten.rb

**Comment by kevzettler** [comment]
The formula needs to run `npm install` within `/usr/local/Cellar/emscripten/1.39.15/libexec/`

**Comment by bayandin** [comment]
This should have been fixed by https://github.com/Homebrew/homebrew-core/pull/54737

@kevzettler could you please check if it works for you
