### ISSUE TITLE
Problem accessing home-brew but pre installed pkgs are full functional

### ISSUE THREAD

**Issue by bumblebee2311** [Homebrew/homebrew-core#54439]
Please help me with the issue I am facing. In zsh terminal (MacOS Catalina)

~% brew upgrade
Updating Homebrew...
Traceback (most recent call last):
	13: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
	12: from /usr/local/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	11: from /usr/local/Homebrew/Library/Homebrew/global.rb:36:in `<top (required)>'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Homebrew/Library/Homebrew/config.rb:56:in `<top (required)>'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/pathname.rb:578:in `mkpath'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': Permission denied @ dir_s_mkdir - /private/tmp (Errno::EACCES)

**Comment by SMillerDev** [comment]
For some reason `/tmp` is inaccessible. Make sure that your user can write there.

**Comment by bumblebee2311** [comment]
I used an open source software https://github.com/Kevin-De-Koninck/Clean-Me after using this I am unable to use home-brew package manager, but the pre-installed softwares like wget etc are still fully functional.
Unable to execute any brew command, returns the same error.
Please help me 🙏

**Comment by bumblebee2311** [comment]
Please can you help me walk through the process,  in reference to the /tmp inaccessibility.

**Comment by SMillerDev** [comment]
Okay, you probably enabled the features marked "dangerous". Have you tried turning it off and on again?

[it crowd](https://giphy.com/gifs/made-by-me-the-it-crowd-FspLvJQlQACXu)

**Comment by bumblebee2311** [comment]
😭Shit !,
Now what should I do?, I unknowingly used the 'dangerous' feature

**Comment by SMillerDev** [comment]
I'm closing this since it's not an issue with homebrew. I'd recommend searching for the error "Permission denied /private/tmp" online.
