### ISSUE TITLE
glm CMake target has incorrect include directory

### ISSUE THREAD

**Issue by omcnoe** [Homebrew/homebrew-core#54500]
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [*] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to link my project to the glm library using CMake.

## What happened (include command output)

The `glmConfig.cmake` file at `/usr/local/lib/cmake/glm` creates the glm target like so:

```
cmake_minimum_required(VERSION 3.2 FATAL_ERROR)
cmake_policy(VERSION 3.2)

set(GLM_VERSION 0.9.9)

get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if (_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Set the old GLM_INCLUDE_DIRS variable for backwards compatibility
set(GLM_INCLUDE_DIRS ${_IMPORT_PREFIX})

add_library(glm::glm INTERFACE IMPORTED)
set_target_properties(glm::glm PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES ${GLM_INCLUDE_DIRS})

mark_as_advanced(glm_DIR)
set(_IMPORT_PREFIX)
```

So the value of `GLM_INCLUDE_DIRS` is `/usr/local/lib`. But homebrew installs the glm headers at 
`/usr/local/include`. This bug would not have previously been noticed, but CMake on macos no longer includes `/usr/local/include` in the include search path by default. So now when linking a target to glm, it will not find the glm headers automatically.

I am not sure if this is an upstream issue with glm, or if it's something that can be fixed in homebrew?

## What you expected to happen

The CMake glm target should have the correct include directory.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. brew install cmake
2. brew install glm
3. find_package(glm REQUIRED) and then link to the glm library

```
~ % brew config
HOMEBREW_VERSION: 2.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: e1f3b0b971dccb72780b2ef33fafde158cb3909e
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7b6532f367e70798aaba2a1c070cf56d9b267ba8
Core tap last commit: 40 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.4-x86_64
CLT: 11.4.1.0.1.1586360307
Xcode: N/A
~ % brew doctor
Your system is ready to brew.
~ % 

```

**Comment by linzichao** [comment]
Should it change the path in [/Homebrew/Library/Taps/homebrew/homebrew-core/Formula](https://github.com/Homebrew/homebrew-core/blob/726d980a98f022a71c0f4e17d628cddfcd27fbbe/Formula/glm.rb#L27)?

It might be Line 27.

```ruby
def install
    mkdir "build" do
      system "cmake", "..", *std_cmake_args
      system "make"
    end
    include.install "glm"
    lib.install "cmake"
    (lib/"pkgconfig/glm.pc").write <<~EOS
      prefix=#{prefix}
      includedir=${prefix}/include
      Name: GLM
      Description: OpenGL Mathematics
      Version: #{version.to_s.match(/\d+\.\d+\.\d+/)}
      Cflags: -I${includedir}
    EOS

    cd "doc" do
      system "doxygen", "man.doxy"
      man.install "html"
    end
    doc.install Dir["doc/*"]
 end
```

If it is the right path, I can try to work on it. 🙂

**Comment by Bo98** [comment]
This seems like an upstream problem. Homebrew doesn't really touch the CMake config file.

**Comment by omcnoe** [comment]
@Bo98 That's what I thought. Upstream works, as the config file is in the right location in the repo. Sadly seem to have closed their github issues...

**Comment by Bo98** [comment]
Yep - upstream are not interested in maintaining it. It was initially removed along with the `pc` file (which Homebrew provides instead) as well as `make install` support.

The only reason the CMake config was added back was because someone sent a pull request. Someone will have to do that if they want it fixed.
