### ISSUE TITLE
Merged PR has wrong author attributed

### ISSUE THREAD

**Issue by wren** [Homebrew/homebrew-core#54705]
- [x] ran `brew update` and can still reproduce the problem?
- [n/a] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [n/a] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [n/a] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was going over the formula for the project that I maintain (jrnl) to ensure quality, and verify the updates for our new releases.

## What happened (include command output)

While looking at the changes to the jrnl formula, I saw that a PR I had worked on didn't have my name attached.

I submitted a PR to update a formula (#50593). It was approved, and seems to have made it into the repo (commit [a2addf52cc](https://github.com/Homebrew/homebrew-core/commit/a2addf52cc)). The problem is that the commit doesn't attribute me as author (even though it links back to my PR). The author is the person who did one of the commits in the PR. After which I did some updates to complete the formula (with another co-author). Both the author of the first commit, and my co-author were attributed in the final squashed commit, but my name was completely left out.

I'm not familiar with your project's merge strategy (squash and rebase?), but if that process is automated, this might point at a bug there.

## What you expected to happen

I would expect that all authors from a PR be properly attributed in the squashed commit.

## Step-by-step reproduction instructions (by running `brew install` commands)
```
cd $(brew --repository homebrew/core)
git show a2addf52cc
```
(or view the links above)

**Comment by jonchang** [comment]
We use a rebase workflow. In that case the maintainer squashed the commits and authorship information was lost, as it's rare that a pull request has more than one author. This repository handles hundreds of pull requests a week, so every now and then something will slip through. Sorry!

To avoid this happening in future pull requests, please ensure that there's one formula per commit and one commit per formula.

No maintainers are currently working on this, but we'd accept pull requests to better manage this information. The solution would be to add a `--autosquash` option or similar to [`brew pr-pull`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/pr-pull.rb) to handle trailers such as `Co-authored-by` and `Signed-off-by`, and properly squashing multiple commits that modify a formula.

**Comment by sjackman** [comment]
To ensure correct attribution, please use `git commit --amend && git push --force` to update your PR. Sorry for the loss of attribution. It's not intentional.
