### ISSUE TITLE
jack fails to build in macOS 10.12

### ISSUE THREAD

**Issue by djmoch** [Homebrew/homebrew-core#5474]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Build broken in Sierra:

https://gist.github.com/djmoch/514def78d74049ae2fc4ff5420a6bcde

**Comment by zmwangx** [comment]
Should be fixed by #5487.

**Comment by zmwangx** [comment]
Fixed in #5487.
