### ISSUE TITLE
conflict between couchdb and ejabberd

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/homebrew-core#54888]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update the version of `wxmac` in https://github.com/Homebrew/homebrew-core/pull/54881 and the CI running `brew test-bot --only-formulae` revealed a conflict between couchdb and ejabberd -- https://github.com/Homebrew/homebrew-core/pull/54881/checks?check_run_id=683436843#step:6:44

## What happened (include command output)

This can be replicated by trying to install `couchdb` and `ejabberd` manually:
<details>
  <summary>Command output</summary>
  <pre>
$ brew install couchdb ejabberd
==> Downloading https://homebrew.bintray.com/bottles/couchdb-3.1.0.catalina.bottle.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/35f8944116423b657bc269481b0a14e544278cdf2320253e5448033c0fabeb20--couchdb-3.1.0.catalina.bottle.tar.gz
==> Pouring couchdb-3.1.0.catalina.bottle.tar.gz
==> Caveats
If your upgrade from version 1.7.2_1 then your old database path is "/usr/local/var/lib/couchdb".

The database path of this installation: /usr/local/var/couchdb/data".

If you want to migrate your data from 1.x to 2.x then follow this guide:
https://docs.couchdb.org/en/stable/install/upgrading.html

To have launchd start couchdb now and restart at login:
  brew services start couchdb
Or, if you don't want/need a background service you can just run:
  couchdb
==> Summary
🍺  /usr/local/Cellar/couchdb/3.1.0: 1,580 files, 46.7MB
==> Downloading https://homebrew.bintray.com/bottles/ejabberd-20.04.catalina.bottle.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/6890a8629a63900e04fea83279091a094b5daffb691d74d2735b3ea1e862181e--ejabberd-20.04.catalina.bottle.tar.gz
==> Pouring ejabberd-20.04.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/jiffy-1.0.4/ebin/jiffy.app
Target /usr/local/lib/jiffy-1.0.4/ebin/jiffy.app
is a symlink belonging to couchdb. You can unlink it:
  brew unlink couchdb

To force the link and overwrite all conflicting files:
  brew link --overwrite ejabberd

To list all files that would be deleted:
  brew link --overwrite --dry-run ejabberd

Possible conflicting files are:
/usr/local/lib/jiffy-1.0.4/ebin/jiffy.app -> /usr/local/Cellar/couchdb/3.1.0/lib/jiffy-1.0.4/ebin/jiffy.app
/usr/local/lib/jiffy-1.0.4/ebin/jiffy.beam -> /usr/local/Cellar/couchdb/3.1.0/lib/jiffy-1.0.4/ebin/jiffy.beam
/usr/local/lib/jiffy-1.0.4/ebin/jiffy_utf8.beam -> /usr/local/Cellar/couchdb/3.1.0/lib/jiffy-1.0.4/ebin/jiffy_utf8.beam
/usr/local/lib/jiffy-1.0.4/priv/jiffy.so -> /usr/local/Cellar/couchdb/3.1.0/lib/jiffy-1.0.4/priv/jiffy.so
==> Caveats
If you face nodedown problems, concat your machine name to:
  /private/etc/hosts
after 'localhost'.

To have launchd start ejabberd now and restart at login:
  brew services start ejabberd
Or, if you don't want/need a background service you can just run:
  /usr/local/sbin/ejabberdctl start
==> Summary
🍺  /usr/local/Cellar/ejabberd/20.04: 801 files, 14.6MB
==> Caveats
==> couchdb
If your upgrade from version 1.7.2_1 then your old database path is "/usr/local/var/lib/couchdb".

The database path of this installation: /usr/local/var/couchdb/data".

If you want to migrate your data from 1.x to 2.x then follow this guide:
https://docs.couchdb.org/en/stable/install/upgrading.html

To have launchd start couchdb now and restart at login:
  brew services start couchdb
Or, if you don't want/need a background service you can just run:
  couchdb
==> ejabberd
If you face nodedown problems, concat your machine name to:
  /private/etc/hosts
after 'localhost'.

To have launchd start ejabberd now and restart at login:
  brew services start ejabberd
Or, if you don't want/need a background service you can just run:
  /usr/local/sbin/ejabberdctl start
  

  </pre>
</details>

## What you expected to happen
I'm not sure what the appropriate solution is - it looks like the offending Erlang 'jiffy' library installed by both is version 1.0.4, so they probably can both use it successfully. However, since the `brew link` failure is considered an error, CI fails.

## Step-by-step reproduction instructions (by running `brew install` commands)
`brew install couchdb ejabberd`

**Comment by SMillerDev** [comment]
Could you make a pull request to mark both as conflicting?

**Comment by bayandin** [comment]
This was fixed in https://github.com/Homebrew/homebrew-core/pull/54665
