### ISSUE TITLE
tomcat formula doesn't fully install tomcat

### ISSUE THREAD

**Issue by JetForMe** [Homebrew/homebrew-core#54892]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? Error: Not Found
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.2.16-69-g9fcaa46
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9fcaa46cdf04652e95668737a23ab248a8b7a73f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ca64172118d2ba5e870f4b59a1b4e9e8932c9d9b
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.l0G5HLygY4/org.macosforge.xquartz:0
HOMEBREW_EDITOR: bbedit -w --resume +1
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 13.0.2, 1.8.0_45, 1.7.0_17, 1.7.0_09
macOS: 10.15.4-x86_64
CLT: N/A
Xcode: 11.4.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

Trying to install and run `tomcat`.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew install tomcat
==> Downloading https://www.apache.org/dyn/closer.lua?path=tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
Already downloaded: /Users/rmann/Library/Caches/Homebrew/downloads/e26e6e888a5dbdc959d410989b6936f9d42d3c6dbf9434e695ad1d7f943cdde4--apache-tomcat-9.0.35.tar.gz
==> Caveats
To have launchd start tomcat now and restart at login:
  brew services start tomcat
Or, if you don't want/need a background service you can just run:
  catalina run
==> Summary
🍺  /usr/local/Cellar/tomcat/9.0.35: 642 files, 14.9MB, built in 15 seconds

$ catalina run
Cannot find /usr/local/tomcat/bin/setclasspath.sh
This file is needed to run this program

  </pre>
</details>

Even after copying the `setclasspath.sh` file from the direct download, Tomcat won't launch:

```
$ catalina run
Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /usr/local/opt/openjdk
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Error: Could not find or load main class org.apache.catalina.startup.Bootstrap
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.startup.Bootstrap
```

Downloading the distribution from the vendor’s website and following their simple instructions (set `CATALINA_HOME` to the untarred file) works out of the box.

## What you expected to happen

I expected tomcat to launch in its default configuration.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `$ brew install tomcat`
2. `$ catalina run`

**Comment by dtrodrigues** [comment]
I was unable to reproduce the issue:

<pre>
$ brew install tomcat
==> Downloading https://www.apache.org/dyn/closer.lua?path=tomcat/tomcat-9/v9.0.35/bin/apache-tomcat-9.0.35.tar.gz
Already downloaded: /Users/username/Library/Caches/Homebrew/downloads/e26e6e888a5dbdc959d410989b6936f9d42d3c6dbf9434e695ad1d7f943cdde4--apache-tomcat-9.0.35.tar.gz
==> Caveats
To have launchd start tomcat now and restart at login:
  brew services start tomcat
Or, if you don't want/need a background service you can just run:
  catalina run
==> Summary
🍺  /usr/local/Cellar/tomcat/9.0.35: 642 files, 14.9MB, built in 8 seconds
$ catalina run
Using CATALINA_BASE:   /usr/local/Cellar/tomcat/9.0.35/libexec
Using CATALINA_HOME:   /usr/local/Cellar/tomcat/9.0.35/libexec
Using CATALINA_TMPDIR: /usr/local/Cellar/tomcat/9.0.35/libexec/temp
Using JRE_HOME:        /usr/local/opt/openjdk
Using CLASSPATH:       /usr/local/Cellar/tomcat/9.0.35/libexec/bin/bootstrap.jar:/usr/local/Cellar/tomcat/9.0.35/libexec/bin/tomcat-juli.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
18-May-2020 02:25:30.799 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.35
18-May-2020 02:25:30.805 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          May 5 2020 20:36:20 UTC
18-May-2020 02:25:30.805 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.35.0
18-May-2020 02:25:30.806 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Mac OS X
18-May-2020 02:25:30.807 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.15.4
18-May-2020 02:25:30.808 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          x86_64
18-May-2020 02:25:30.808 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/Cellar/openjdk/13.0.2+8_2/libexec/openjdk.jdk/Contents/Home
18-May-2020 02:25:30.809 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           13.0.2+8
18-May-2020 02:25:30.809 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
18-May-2020 02:25:30.810 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/Cellar/tomcat/9.0.35/libexec
18-May-2020 02:25:30.811 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/Cellar/tomcat/9.0.35/libexec
18-May-2020 02:25:30.852 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
18-May-2020 02:25:30.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
18-May-2020 02:25:30.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
18-May-2020 02:25:30.853 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/Cellar/tomcat/9.0.35/libexec/conf/logging.properties
18-May-2020 02:25:30.854 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
18-May-2020 02:25:30.854 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
18-May-2020 02:25:30.854 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
18-May-2020 02:25:30.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
18-May-2020 02:25:30.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
18-May-2020 02:25:30.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/Cellar/tomcat/9.0.35/libexec
18-May-2020 02:25:30.855 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/Cellar/tomcat/9.0.35/libexec
18-May-2020 02:25:30.856 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/Cellar/tomcat/9.0.35/libexec/temp
18-May-2020 02:25:30.856 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The Apache Tomcat Native library which allows using OpenSSL was not found on the java.library.path: [/Users/username/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
18-May-2020 02:25:31.447 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
18-May-2020 02:25:31.538 INFO [main] org.apache.catalina.startup.Catalina.load Server initialization in [1,088] milliseconds
18-May-2020 02:25:31.620 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
18-May-2020 02:25:31.620 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.35]
18-May-2020 02:25:31.637 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/docs]
18-May-2020 02:25:32.089 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/docs] has finished in [452] ms
18-May-2020 02:25:32.090 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/manager]
18-May-2020 02:25:32.156 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/manager] has finished in [66] ms
18-May-2020 02:25:32.157 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/examples]
18-May-2020 02:25:32.654 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/examples] has finished in [497] ms
18-May-2020 02:25:32.655 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/ROOT]
18-May-2020 02:25:32.703 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/ROOT] has finished in [48] ms
18-May-2020 02:25:32.704 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/host-manager]
18-May-2020 02:25:32.761 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/Cellar/tomcat/9.0.35/libexec/webapps/host-manager] has finished in [57] ms
18-May-2020 02:25:32.770 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-May-2020 02:25:32.784 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [1,244] milliseconds


$ brew config
HOMEBREW_VERSION: 2.2.16-69-g9fcaa46-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9fcaa46cdf04652e95668737a23ab248a8b7a73f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ca64172118d2ba5e870f4b59a1b4e9e8932c9d9b
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: REMOVED
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.5, 1.8.0_242
macOS: 10.15.4-x86_64
CLT: 1103.0.32.59
Xcode: 11.4.1
XQuartz: 2.7.11 => /opt/X11
</pre>

**Comment by dtrodrigues** [comment]
What do you get when you run `which catalina`? Is it `/usr/local/tomcat/bin/catalina`? Do you still have `CATALINA_HOME` set as an envonment variable? It should be `/usr/local/bin/catalina` which contains `/usr/local/Cellar/tomcat/9.0.35/libexec/bin/catalina.sh` within it which allows it to find `/usr/local/Cellar/tomcat/9.0.35/libexec/bin/setclasspath.sh`.

**Comment by JetForMe** [comment]
Hmm, I'm not sure now, since I downloaded it manually and I've been running it from the unpacked directory, but here's what's left over in my `/usr/local`:

```
$ ls -l `which catalina`
lrwxr-xr-x  1 rmann  admin    36B May 17 22:52 /usr/local/bin/catalina@ -> ../Cellar/tomcat/9.0.35/bin/catalina
$ echo $CATALINA_HOME
/usr/local/tomcat
$ ls -l /usr/local/tomcat
lrwxr-xr-x  1 root  wheel    32B May 17 22:30 /usr/local/tomcat@ -> /usr/local/Cellar/tomcat/9.0.35/
```

I think the problem is `Cellar/tomcat/9.0.35/bin` has `catalina` and `Cellar/tomcat/9.0.35/libexec/bin` has the real stuff (I do see the other scripts in there).

**Comment by dtrodrigues** [comment]
Can you try clearing  your `$CATALINA_HOME` variable or have it explicitly point to `/usr/local/Cellar/tomcat/9.0.35/libexec`? Since you already have `$CATALINA_HOME` set, the `catalina.sh` script won't set it correctly.  You could also probably technically link `/usr/local/tomcat` to `/usr/local/Cellar/tomcat/9.0.35/libexec`, but the best thing is probably just to clear the environment variable and let the startup script find the correct directory.

**Comment by JetForMe** [comment]
Hmm, set or cleared, `catalina run` now seems to work. I'm sure "fixed" whatever was wrong in the flurry of activity I've been engaged in since yesterday. Sorry to waste your time, it seems to be working now, although I couldn't tell you why. Thanks!

**Comment by dtrodrigues** [comment]
Excellent! Can you mark this issue as closed if things are working okay for you now?
