### ISSUE TITLE
Neo4J does not install version 4

### ISSUE THREAD

**Issue by kenahoo** [Homebrew/homebrew-core#54922]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` see https://gist.github.com/kenahoo/6459fb94a11023237bc90fe71781bc85

## What you were trying to do (and why)

Install latest version of `neo4j`, by doing `brew update` and `brew install neo4j`.

## What happened (include command output)

Version 3.5.14 was installed.

<details>
  <summary>Command output</summary>
  <pre>

% brew info neo4j
neo4j: stable 3.5.14
Robust (fully ACID) transactional property graph database
https://neo4j.com/
/usr/local/Cellar/neo4j/3.5.14 (141 files, 165.9MB) *
  Built from source on 2020-05-18 at 17:08:59
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/neo4j.rb
==> Requirements
Required: java = 1.8 ✔
==> Caveats
To have launchd start neo4j now and restart at login:
  brew services start neo4j
Or, if you don't want/need a background service you can just run:
  neo4j start
==> Analytics
install: 811 (30 days), 2,500 (90 days), 17,177 (365 days)
install-on-request: 786 (30 days), 2,391 (90 days), 15,288 (365 days)
build-error: 0 (30 days)

  </pre>
</details>

## What you expected to happen

I was expecting the latest version, 4.0.4, to be installed.

I'm not sure whether Neo4J version 4 is available as a vanilla tarball by direct download URL anymore (at least, I couldn't find one by poking around their web site, ergo why I came to `brew` to do that for me), which might be why the formula hasn't been updated?

It looks like maybe the way to get version 4 installed is to do `brew cask install neo4j` instead of `brew install neo4j` - if that's the case, can some output be added to the text of `brew info neo4j` to indicate it?  

Also - if that situation is permanent, should the non-cask installation be removed and replaced with a `neo4j@3` item?  I think I've seen that happen for other things that became casks, but I'm not sure what the policy is.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install neo4j`

**Comment by SMillerDev** [comment]
If you want something updated you should open a pull request. Homebrew doesn't allow update requests as issues.

**Comment by kenahoo** [comment]
I mentioned in my message that I don't know whether an update is possible - I'm not sure whether the PR should be a doc update, a version update to the latest version, or the deprecation/deletion of the formula.  Without clarity on that, I don't think I'll open a PR for any of those.

**Comment by SMillerDev** [comment]
If an update is possible that's always the preferred way.
