### ISSUE TITLE
configure: error: zlib not installed

### ISSUE THREAD

**Issue by ben2803** [Homebrew/homebrew-core#5498]
### Bug reports:

Trying to install Wine on  Mac OS X 10.12 and I keep getting this error... I'm pretty much a complete 0 when it comes to programming, I was following someones guide on how to do it. 

`checking for zlibVersion in -lz... no
checking for z_zlibVersion in -lz... no
configure: error: zlib not installed`

and then it told me to report the error here... any help would be appreciated; even better if you can somehow explain it like I'm 5

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!
