### ISSUE TITLE
TigerVNC using only 1/4 of display when running on Retina display

### ISSUE THREAD

**Issue by xipmix** [Homebrew/homebrew-core#54992]
# Issue checklist

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

This issue was previously reported in Homebrew/homebrew-core/issues/37872 and closed because required information was not provided. A commenter noted that there is a workaround, installing an earlier version of fltk.

## What happened (include command output)

I tried to install the previous version of fltk (1.3.4-2) to work around the issue with 1.3.5.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install fltk@1.3.4-2
Error: No available formula with the name "fltk@1.3.4-2" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
  </pre>
</details>

## What you expected to happen

Version 1.3.4-2 would be installed.

## Step-by-step reproduction instructions (by running `brew install` commands)
<pre>
$brew update
$ brew install fltk@1.3.4-2
</pre>

## Additional information
<pre>
$ brew config
HOMEBREW_VERSION: 2.2.17-29-gb2fc8ad
ORIGIN: https://github.com/Homebrew/brew
HEAD: b2fc8ad7b3fa874ac76f4ee2fba48f7535487caa
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 20d2a8835a31a7ac2de554d0c1627b90631381ad
Core tap last commit: 73 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.9GjVCp0oi3/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1100
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.

$ brew gist-logs fltk
Error: No logs.

$ brew info  fltk
fltk: stable 1.3.5 (bottled)
Cross-platform C++ GUI toolkit
https://www.fltk.org/
/usr/local/Cellar/fltk/1.3.5 (329 files, 5.1MB) *
  Poured from bottle on 2019-03-29 at 20:42:18
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/fltk.rb
==> Dependencies
Required: jpeg ✔, libpng ✔
==> Analytics
install: 3,651 (30 days), 11,050 (90 days), 44,681 (365 days)
install-on-request: 258 (30 days), 848 (90 days), 4,076 (365 days)
build-error: 0 (30 days)

</pre>

**Comment by SMillerDev** [comment]
Homebrew doesn't support picking any version of software. We either ship the latest version or a special versioned formula, you'd be able to find either with `brew search`. 

Fltk only ships the latest version so your best option is to check if a version with a fix has been released and updating the formula. Or you could use `brew extract` to get an older  version and maintain it in a personal tap.

**Comment by jonchang** [comment]
This is an upstream issue with fltk. If you can figure out how to patch it to get it to work with TigerVNC, feel free to open a pull request. c.f. https://github.com/TigerVNC/tigervnc/issues/867

**Comment by xipmix** [comment]
Thanks. I reported it with them https://www.fltk.org/str.php?L3536+P0+S-2+C0+I0+E0+V1.3%25+Q
I doubt I'm going to have time to bisect it for them.
