### ISSUE TITLE
exit from octave-gui does not finish 

### ISSUE THREAD

**Issue by schloegl** [Homebrew/homebrew-core#55007]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
[brew-config.txt](https://github.com/Homebrew/homebrew-core/files/4655611/brew-config.txt)

## What you were trying to do (and why)

Use the GUI version of octave, and exit from it. 

## What happened (include command output)

Starting the gui version of octave works fine, but when trying to exit, the cursor switches to the rotating disk in rainbow colors, and the octave window never finishes (I've waited for at least 10 minutes). 

<details>
  Opening a terminal and start octave with 
      octave --gui 
  After the octave gui has opened, and trying to exit  by typing "exit" 
  <summary>Command output</summary>
  <pre>

  </pre>
</details>

## What you expected to happen

I expect that that exit finishes, and octave closes. 

## Step-by-step reproduction instructions (by running `brew install` commands)
  brew install octave 
  octave --gui 
   >>> exit 

  brew reinstall --build-from-source octave 
  shows the same problem.

**Comment by SMillerDev** [comment]
What lead you to assume that this is a bug in homebrew?

**Comment by schloegl** [comment]
Because on Linux, I do not see this problem.

**Comment by schloegl** [comment]
I've submitted now also a bug report to upstream
    https://savannah.gnu.org/bugs/?58409

**Comment by zhiyuanzhai** [comment]
The problem still exists......

**Comment by jonchang** [comment]
This is an upstream problem, see https://savannah.gnu.org/bugs/?50025 to help out.
