### ISSUE TITLE
ffmpeg requires libbluray build dep to install

### ISSUE THREAD

**Issue by xzcvczx** [Homebrew/homebrew-core#55034]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

install ffmpeg

## What happened (include command output)

libbluray installed from bottle fine, when i try to install ffmpeg it will fail with the error below when java is only a build dep for libbluray (which is already installed from bottle)

<details>
  <summary>Command output</summary>
  <pre>

  $ brew -v install ffmpeg
libbluray: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8

  </pre>
</details>

issue has occurred for myself running mojave and another person who tried it running catalina

## What you expected to happen

it to install without wanting a build dep of (the already installed) libbluray

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install ffmpeg

### brew config
```
HOMEBREW_VERSION: 2.2.17-53-g67d1bc6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 67d1bc6fb746e2c505330d308f5e991a0a1567f8
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d6369c8537e7de31f76a1a3d0e1b2589022ed6b1
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build 1001
Git: 2.20.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 11.0.2
macOS: 10.14.5-x86_64
CLT: 10.2.1.0.1.1554506761
Xcode: 10.3
```
the same happens on catalina with latest version of xcode

###brew doctor
```
brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae were deleted!
You should find replacements for the following formulae:
  python@2
  wine
  gradle@5.0

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gradle

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.profile

Warning: Your Xcode (10.3) is outdated.
Please update to Xcode 11.3.1 (or delete it).
Xcode can be updated from the App Store.

```

as above issue also occurs on catalina with latest xcode

**Comment by jonchang** [comment]
This should be fixed in https://github.com/Homebrew/brew/issues/7618. Run `brew update` and try again.
