### ISSUE TITLE
brew test node failing

### ISSUE THREAD

**Issue by ryenus** [Homebrew/homebrew-core#55032]
#### Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew test node`

## What happened (include command output)

it fails with errors:

<details>
  <summary>Command output</summary>
  <pre>

  
$ brew test node
Testing node
==> /usr/local/Cellar/node/14.3.0/bin/node /private/tmp/node-test-20200521-52675-h191e5/test.js
==> /usr/local/Cellar/node/14.3.0/bin/node -e 'console.log(new Intl.NumberFormat("en-EN").format(1234.5
==> /usr/local/Cellar/node/14.3.0/bin/node -e 'console.log(new Intl.NumberFormat("de-DE").format(1234.5
==> /usr/local/bin/npm -ddd --cache=/Users/i317779/Library/Caches/Homebrew/npm_cache --build-from-sourc
==> /usr/local/bin/npm -ddd --cache=/Users/i317779/Library/Caches/Homebrew/npm_cache --build-from-sourc
==> /usr/local/bin/npx cowsay hello
npx: installed 10 in 17.295s
Killing child processes...
Error: node: failed
SIGTERM
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:72:in `read'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:72:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:357:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:62:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:32:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:93:in `block in test'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:41:in `each'
/usr/local/Homebrew/Library/Homebrew/dev-cmd/test.rb:41:in `test'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

  </pre>
</details>

## What you expected to happen

`brew test node` should succeed

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install node
brew test node
```

**Comment by Bo98** [comment]
I can't reproduce locally, and neither can I on our CI:

```
$ brew test node
Testing node
==> /usr/local/Cellar/node/14.3.0/bin/node /private/tmp/node-test-20200521-14719-12oasyg/test.js
==> /usr/local/Cellar/node/14.3.0/bin/node -e 'console.log(new Intl.NumberFormat("en-EN").format(1234.56))'
==> /usr/local/Cellar/node/14.3.0/bin/node -e 'console.log(new Intl.NumberFormat("de-DE").format(1234.56))'
==> /usr/local/bin/npm -ddd --cache=/Users/bo/Library/Caches/Homebrew/npm_cache --build-from-source install npm@latest
==> /usr/local/bin/npm -ddd --cache=/Users/bo/Library/Caches/Homebrew/npm_cache --build-from-source install bufferutil
==> /usr/local/bin/npx cowsay hello
npx: installed 10 in 1.922s
```

It seems like there's something different from your setup so you'll need to debug some more yourself to try and find why it doesn't work for you.

**Comment by chrmoritz** [comment]
It's looks like you have damaged your `npm`/`npx` installation (in `/usr/local/bin`) somehow.

Could you try to run `brew postinstall node` and then try `brew test node` again?

**Comment by chelli0783** [comment]
See memories
