### ISSUE TITLE
brew info is failing

### ISSUE THREAD

**Issue by gbstan** [Homebrew/homebrew-core#55153]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew info [any_formula]
## What happened (include command output)

brew info fzf

<details>
  <summary>Command output</summary>
  <pre>

Error: undefined local variable or method `formula' for Homebrew:Module
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:112:in `block in print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:105:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:105:in `each_with_index'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:105:in `print_info'
/usr/local/Homebrew/Library/Homebrew/cmd/info.rb:92:in `info'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

  </pre>
</details>

## What you expected to happen

Get info about the formula

## Step-by-step reproduction instructions (by running `brew install` commands)

brew info any_brew_formula

**Comment by gbstan** [comment]
It seems it works now after a brew update; brew upgrade; brew cleanup -s

**Comment by issyl0** [comment]
Glad it works again!
