### ISSUE TITLE
Erlang/OTP 23 missing doc chunks

### ISSUE THREAD

**Issue by maxnordlund** [Homebrew/homebrew-core#55217]
Not really relevant, see rest of issue below (although I did run `brew doctor` and verified it does not affect my Erlang installation).

- [x] ~ran `brew update` and can still reproduce the problem?~
- [x] ~ran `brew doctor`, fixed all issues and can still reproduce the problem?~
- [ ] ~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~
- [ ] ~if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~

## What you were trying to do (and why)

Erlang/OTP 23 introduced doc chunks, a standardized way of storing documentation in BEAM files. Unfortunately the brew formulae does not build these.

## What happened (include command output)

```console
$ erl # Open an Erlang shell
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.0  (abort with ^G)
1> h(lists). % Try to access the documentation for `lists`

   lists

  There is no documentation for lists
ok
2>
```

## What you expected to happen

```console
$ erl # Open an Erlang shell
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V11.0  (abort with ^G)
1> h(lists). % Try to access the documentation for `lists`

   lists

  This module contains functions for list processing.

  Unless otherwise stated, all functions assume that position numbering
  starts at 1. That is, the first element of a list is at position 1.
more (y/n)? (y) n
ok
2>
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```console
$ brew install erlang # works
$ erl # open an Erlang shell
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.0  (abort with ^G)
1> h(lists). % Try to access the documentation for `lists`
```

You can use [kerl][], or [asdf-erlang][] that uses [kerl][] under the hood, to build your own Erlang distribution. That one will include the chunks.

Using `kerl`:
```console
$ export KERL_BUILD_DOCS=yes
$ export KERL_DOC_TARGETS=chunks # Should be the default, but better safe then sorry
$ kerl build 23.0.1 23.0.1
$ kerl install 23.0.1 /your/favourite/path/to/23.0.1
```

Using `asdf`
```console
$ export KERL_BUILD_DOCS=yes
$ export KERL_DOC_TARGETS=chunks # Should be the default, but better safe then sorry
$ asdf install erlang 23.0
$ asdf shell erlang 23.0
```

I'm not too familiar with the building process, but these two issue in [kerl][] should hopefully be enough to port over the change to `brew`.

https://github.com/kerl/kerl/issues/334
https://github.com/kerl/kerl/pull/336

[kerl]: https://github.com/kerl/kerl
[asdf-erlang]: https://github.com/asdf-vm/asdf-erlang

**Comment by maxnordlund** [comment]
Ping @chenrui333 and @Bo98

**Comment by maxnordlund** [comment]
@chenrui333 could you take a look a this, please

**Comment by Bo98** [comment]
I believe this is already done but it wasn't reported back here. Try `brew upgrade erlang` and see if it works.

**Comment by chenrui333** [comment]
Like @Bo98 said, you should see the fix with `brew upgrade erlang`

**Comment by maxnordlund** [comment]
Aha, I didn't see that. Weird that Github didn't close this, #57433 does mention this issue. Thanks

**Comment by chenrui333** [comment]
I think it might be because of the non-normal merge flow that we used for merging the formulae PRs. :)

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/issues/61770
