### ISSUE TITLE
Cabal v1 install deprecation

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-core#55253]
Cabal v1-installs are deprecated. One part of it, Cabal sandboxes, [will be removed](https://github.com/haskell/cabal/commit/6248c74280a54382f85079f58a1ea40ba0db9476) in cabal-install 3.4. Homebrew uses Cabal sandboxes in `Language::Haskell::Cabal`.

As such, the module has been deprecated in Homebrew 2.3. This issue tracks migration of formulae to Cabal v2.

For the simplest formulae:
* Use `system "cabal", "v2-update"` and `system "cabal", "v2-install", *std_cabal_v2_args` instead of `install_cabal_package`
* Remove `require "language/haskell"` and `include Language::Haskell::Cabal`.
* If possible, use the newest GHC that is compatible.

| Formula | PR | Merged? | Comment |
| :--- | :---: | :---: | :--- |
| `agda` | #59709 & #67014 | ✅ | |
| `allureofthestars` | #67259 | ✅ | |
| `bench` | #55877 | ✅ | |
| `bnfc` | #55854 | ✅ | |
| `cedille` | #67282 | ✅ | |
| `cgrep` | #55878 | ✅ | |
| `cmt` | #55879 | ✅ | |
| `cryptol` | #59329 | ✅ | |
| `dhall-bash` | #55848 | ✅ | |
| `dhall-json` | #55849 | ✅ | |
| `dhall-lsp-server` | #55847 | ✅ | |
| `dhall-yaml` | #55850 | ✅ | |
| `dhall` | #55833 | ✅ | |
| `elm` | #67404 | ✅ | |
| `futhark` | #51767 & #58534 | ✅ | |
| `ghc@8.6` | | ❌ | `language/haskell` require removed in #65285 |
| `ghc@8.8` | | ❌ | `language/haskell` require removed in #65285 |
| `ghc` | | ❌ | `language/haskell` require removed in #65285<br>`head` removed in #67360 |
| `git-annex` | #59330 | ✅ | |
| `hadolint` | #49412 & #58532 | ✅ | |
| `haskell-stack` | #59267 | ✅ | |
| `highlighting-kate` | #55874 | ✅ | Formula deleted |
| `hlint` | #56582 & #58531 | ✅ | |
| `hopenpgp-tools` | #59345 | ✅ | |
| `idris` | #67343 | ✅ | |
| `mighttpd2` | #55880 | ✅ | |
| `pandoc-citeproc` | #59346 | ❌ | Formula disabled in #65285 |
| `pandoc-crossref` | #59347 | ✅ | |
| `pandoc` | #58074 & #58533 | ✅ | |
| `psc-package` | #59348 | ✅ | |
| `shelltestrunner` | #59349 | ✅ | |
| `taskell` | #59350 | ✅ | |
| `texmath` | #67169 | ✅ | |

**Comment by pthariensflame** [comment]
@Bo98 #55833 is taking care of `dhall`.  I'll probably end up doing the rest of them too.

**Comment by pthariensflame** [comment]
@Bo98 #55847, #55848, #55849, and #55850 are ready!

**Comment by pthariensflame** [comment]
As is #55854…maybe.

**Comment by MikeMcQuaid** [comment]
@bo98 @SeekingMeaning What's the latest on this? These seem to be `odisabled` rather than `odeprecated` now so these formulae aren't installing from source at all now, right?

**Comment by carlocab** [comment]
Built and tested Agda locally. PR here: https://github.com/Homebrew/homebrew-core/pull/66980

**Comment by SeekingMeaning** [comment]
Failures remaining after https://github.com/Homebrew/homebrew-core/pull/65285 (Remove language/haskell require)

```
brew install --verbose --build-bottle agda
brew test --verbose allureofthestars
brew install --build-from-source agda
brew install --verbose --build-bottle cedille
brew install --verbose --build-bottle elm
brew install --verbose --build-bottle idris
brew install --verbose --build-bottle texmath
```

**Comment by carlocab** [comment]
I've been looking at them. I don't think fixes will come as easily as with `agda` or `texmath`.
