### ISSUE TITLE
Language::Python.rewrite_python_shebang deprecation

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-core#55255]
`Language::Python.rewrite_python_shebang` has been deprecated in Homebrew 2.3 in favour of `rewrite_shebang`. Uses of the function should be replaced by `rewrite_shebang detected_python_shebang, <files>`. The formula may need a `include Language::Python::Shebang`.

This issue tracks migration.

- [x] `git-filter-repo` - #56027
- [x] `glib` - #57584
- [x] `gobject-introspection` - #55383
- [x] `gupnp` - #56410
- [x] `meson` - #57371 
- [x] `scons` - #57374
- [x] `spades` - #57373

**Comment by tschoonj** [comment]
I think I took care of `gobject-introspection` in #55383. Sorry, wasn't aware you had an issue open over this.

**Comment by Bo98** [comment]
Thanks for helping out!

**Comment by Rylan12** [comment]
PRs have been created for the remaining formula except for `glib`.

For `glib`, there is an open PR to upgrade to 2.64.4, so I requested that these changes be made there as well.

**Comment by Rylan12** [comment]
All occurrences of `Language::Python.rewrite_python_shebang` in homebrew-core have now been replaced with `rewrite_shebang`
