### ISSUE TITLE
json-fortran reads integer greater than 9 into 1

### ISSUE THREAD

**Issue by gh4ag** [Homebrew/homebrew-core#55280]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?

- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

=> "Error: No logs."

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`

> HOMEBREW_VERSION: 2.2.17-103-ga56c305
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: a56c305f87bb45dd3850c302d9ab4173df0adb23
> Last commit: 6 hours ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 50a8b1bb411a89e56466c6efce6d9a02b4639b7b
> Core tap last commit: 57 minutes ago
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.IEPiLoaLiZ/org.macosforge.xquartz:0
> HOMEBREW_MAKE_JOBS: 4
> CPU: quad-core 64-bit haswell
> Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
> Clang: 10.0 build 1001
> Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
> Curl: 7.54.0 => /usr/bin/curl
> Java: 13.0.2
> macOS: 10.14.6-x86_64
> CLT: 10.3.0.0.1.1562985497
> Xcode: N/A
> XQuartz: 2.7.11 => /opt/X11

`brew doctor`

> Warning: Unbrewed dylibs were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected dylibs:
>   /usr/local/lib/libgfortran.3.dylib
> 
> Warning: Unbrewed .la files were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected .la files:
>   /usr/local/lib/libgfortran.la
> 
> Warning: Unbrewed static libraries were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected static libraries:
>   /usr/local/lib/libgfortran.a

## What you were trying to do (and why)

I have installed gfortran and json-fortran using Homebrew. However, there seem to be something wrong with the latest json-fortran formula (v. 8.0.0) when it comes to reading integer from json files. 

## What happened (include command output)

`brew install json-fortran` 

worked.

I then had the following json called `file.json`:

```
{
	"data":{
		"num":[8, 12],
		"obj":"ABC"
	}
}
```

And I try to compile the following code test.f90:

```
PROGRAM Test
	use json_module
	type(json_file) :: json
	logical :: found
	real, dimension(:), allocatable :: rArray
	integer(kind=4), dimension(:), allocatable :: val    !! value

	print *, "Reading json..."

	! initialize the class
	call json%initialize(strict_integer_type_checking=.true.)

	! read the file
    call json%load(filename='file.json')

    ! retreive value from json
	call json%get('data.num', val, found)

	print *, "Num: ", int(val)

	! print the file to the console
	call json%print()

	! clean up
    call json%destroy()
    if (json%failed()) stop 1
	
END PROGRAM Test

```

I compiled using:

```
gfortran -c -std=legacy -I/usr/local/var/homebrew/linked/json-fortran/include test.f90
gfortran -o prog test.o -O3 -std=legacy -lz /usr/local/var/homebrew/linked/json-fortran/lib/libjsonfortran.a
chmod +x prog
./prog
```

<details>
  <summary>Command output</summary>
  <pre>
 Reading json...
 Num:            8           1
{
  "data": {
    "num": [
      8,
      1
    ],
    "obj": "ABC"
  }
}
  </pre>
</details>

## What you expected to happen

I should have got:

 Reading json...
 Num:            8           **12**
{
  "data": {
    "num": [
      8,
      **12**
    ],
    "obj": "ABC"
  }
}

## Step-by-step reproduction instructions (by running `brew install` commands)

See above

## Origin of problem

I suspect a missing flag during the compilation of json-fortran with gcc9.3 ...

**Comment by claui** [comment]
> I suspect a missing flag during the compilation of json-fortran with gcc9.3 ...

Which flag are you referring to?

**Comment by gh4ag** [comment]
> > I suspect a missing flag during the compilation of json-fortran with gcc9.3 ...
> 
> Which flag are you referring to?

I was thinking about the `--with-unicode-support` flag found on the project git (https://github.com/jacobwilliams/json-fortran)  that is no longer supported by homebrew. However, it is included directly into the formula `"-DENABLE_UNICODE:BOOL=TRUE"` (https://github.com/Homebrew/homebrew-core/blob/master/Formula/json-fortran.rb). So it is a wrong lead.

I am attempting an install from source to see if it makes a difference.

A way to circumvent this issue from a user point of view is to use float notation in json "12.0" instead of "12" and then cast it to int in the fortran. But this is an ugly workaround. Other coders using the lates version of json-fotran under Ubuntu don't have this issue, so it must be build related.

**Comment by gh4ag** [comment]
Installing from source didn't solve the problem. The issue is either from the configuration of the build or from another issue (gcc compatibility or from the project source code itself).

**Comment by SMillerDev** [comment]
Have you tried building from source outside of homebrew?

**Comment by gh4ag** [comment]
Yes, I have found the error. It comes from the evolution of the package from the version 7 (https://github.com/jacobwilliams/json-fortran/releases/tag/7.1.0) to 8. It is not a Homebrew build issue. However, I would recommend allowing installing version 7 on Homebrew.

In deed:
`brew install json-fortran@7` 

I have tried and it is not possible at the moment.

**Comment by claui** [comment]
Closing as an upstream issue.
