### ISSUE TITLE
Screenresolution HEAD won't build using Xcode 8

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#5541]
I'm transferring this out of #1957.  Whether on El Capitan or Sierra, Xcode 8 has broken `screenresolution` EDIT: when building from HEAD; stable works.

```
==> make CC=clang
sed -e "s/@VERSION@/\"1.7dev\"/" < version-tmpl.h > version.h
clang   -arch i386 -arch x86_64 main.c -c -o main.o
clang   -arch i386 -arch x86_64 cg_utils.c -c -o cg_utils.o
clang   -arch i386 -arch x86_64 -framework Foundation -framework ApplicationServices main.o cg_utils.o -o screenresolution
Undefined symbols for architecture x86_64:
  "_MIN", referenced from:
      _listAvailableModes in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [screenresolution] Error 1
```
It still builds just fine on El Cap when Xcode 7.3.1 is installed.

I've [reported this](https://github.com/jhford/screenresolution/issues/25) upstream.

**Comment by mistydemeo** [comment]
Is this only when building `HEAD`? The stable version works okay for me.

**Comment by chdiza** [comment]
Yeah, sorry forgot to mention that part.  I'll change the issue title.

**Comment by mistydemeo** [comment]
I'm not 100% sure of the header dependency chain here, but the most likely source of this macro is in `sys/param.h`. I'm going to guess that header was, somewhere along the chain, being implicitly required on older versions of OS X, but isn't in the 10.12 SDK. If I add an `#include <sys/param.h>` to main.c, then screenresolution builds and works.

**Comment by mistydemeo** [comment]
Submitted a PR: https://github.com/jhford/screenresolution/pull/26

Since this is `HEAD`, its being broken is pretty normal, so it's okay for it to stay broken until the PR is merged. That said, this project doesn't look to be particularly active.

**Comment by chdiza** [comment]
Thanks!  Probably it's dead, but I guess we'll wait a while to see if it gets picked up since the fix is simple and already PR'd for the maintainer.

**Comment by dunn** [comment]
I guess there's no reason to boneyard this, since current stable builds?  At least not until it breaks on future macOS releases.

If it does end up being merged, though, we can pick this up in a PR.
