### ISSUE TITLE
Openfortivpn: update overwrites configuration file

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [Homebrew/homebrew-core#55420]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [✓] ran `brew update` and can still reproduce the problem?
- [✓] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [✓] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [✓] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

When updating [_openfortivpn_](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openfortivpn.rb), the location of the configuration file changes with each new version. The _openfortivpn_ configuration file lives under `#{prefix}` by default and `#{prefix}` changes with each version.

For example for 1.14.0 the configuration file is:
```
/usr/local/Cellar/openfortivpn/1.14.0/etc/openfortivpn/config
```
and for 1.14.1 it changes to:
```
/usr/local/Cellar/openfortivpn/1.14.1/etc/openfortivpn/config
````

Users have to re-create the configuration with each update.

## What happened (include command output)

The location of the configuration file changes with each update, giving end-users the impression that the configuration file is "overwritten" (see https://github.com/adrienverge/openfortivpn/issues/721). The have to re-create the configuration file with each update.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install openfortivpn
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and homebrew/core).
[...]
==> Downloading https://github.com/adrienverge/openfortivpn/archive/v1.14.1.tar.gz
Already downloaded: /home/a-sac-ns-brainvisa/Library/Caches/Homebrew/downloads/18b9b5016a7b1de4142ed9aa01225dd41cac3048efe64173293acf940ee30a4f--openfortivpn-1.14.1.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/openfortivpn/1.14.1
==> make install
🍺  /usr/local/Cellar/openfortivpn/1.14.1: 9 files, 165.2KB, built in 20 seconds
$ 
$ ls -l /usr/local/Cellar/openfortivpn/1.14.1/etc/openfortivpn/
total 8
-rw-------  1 xxxxxxxx  xxxxx  147 May 29 08:50 config
$ 
$ ls -l /usr/local/etc/openfortivpn/config 
lrwxr-xr-x  1 xxxxxxxx xxxxx  56 May 29 08:50 /usr/local/etc/openfortivpn/config -> ../../Cellar/openfortivpn/1.14.1/etc/openfortivpn/config
$ 
  </pre>
</details>

## What you expected to happen

The configuration file location should not depend on the version of _openfortivpn_, so that the configuration file does not have to be changed again and again after each update. The location should not be inside the `HOMEBREW_CELLAR` so it persists across upgrades.

## Step-by-step reproduction instructions (by running `brew install` commands)

By default _openfortivpn_ installs its configuration file under `#{prefix}` and the formula doesn't attempt to change that:
https://github.com/Homebrew/homebrew-core/blob/fc6de2e38a07c08a7b0da9e9f263f83ed815ad5d/Formula/openfortivpn.rb#L20-L22

I'm not a specialist but I understand the formula should install the configuration file into **`#{etc}`** instead:
[Where do I place consistent configuration files ? (beginner’s question)](https://discourse.brew.sh/t/where-do-i-place-consistent-configuration-files-beginners-question/1250)

So change the formula from:
```
    system "./configure", "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}"
```
to something like this:
```
    system "./configure", "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}/openfortivpn"
```

**Comment by SMillerDev** [comment]
That seems like a good change. Could you make a pull request for it?

**Comment by jonchang** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/55421
