### ISSUE TITLE
LLVM on Catalina

### ISSUE THREAD

**Issue by jpz** [Homebrew/homebrew-core#55491]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

## What you were trying to do (and why)

I am trying to build llvm from sources, using `brew install llvm -s`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew install llvm -s
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/d3fd1500-6ddd-11ea-8246-7da96f5124f6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang-tools-extra-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/a021ef80-6ddd-11ea-9f82-d80e70d72f2b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/compiler-rt-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/926c6a00-6ddd-11ea-848c-a2f8f37b9068?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/libcxx-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/900a1000-6ddd-11ea-87c2-1d50f4199546?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/libunwind-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/8e404c80-6ddd-11ea-9646-fd70cc766c1e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/lld-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/8c768900-6ddd-11ea-9a7e-37239d63a73b?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/lldb-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/82ed2100-6ddd-11ea-943f-8e56b05c7c85?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/openmp-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/d743d100-6ddc-11ea-9c9f-ba2ad050b876?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/polly-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/d0b55980-6ddc-11ea-9b6c-3853f87d6572?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/llvm-10.0.0.src.tar.xz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/75821432/6a7d0680-6ddd-11ea-981a-8fe49cad1bb2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWN
######################################################################## 100.0%
==> cmake -G Unix Makefiles .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;openmp;polly -DLLVM_ENABLE_RUNTIMES=compiler-rt;libcxx;libunwind -DLIBOMP_ARCH=x86_64 -DLLVM_POLLY_LI
==> make
Last 15 lines from /Users/jasonz/Library/Logs/Homebrew/llvm/02.make:
[100%] Generating /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/lib/clang/10.0.0/lib/darwin/libclang_rt.cc_kext_ios.a
[100%] Built target clang_rt.cc_kext_ios
Scanning dependencies of target builtins
[100%] Built target builtins
Scanning dependencies of target compiler-rt
[100%] Built target compiler-rt
[ 86%] No install step for 'builtins'
cd /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes/builtins-bins && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E echo_append
cd /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes/builtins-bins && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E touch /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes/builtins-stamps//builtins-install
[ 86%] Completed 'builtins'
cd /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E make_directory /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes/CMakeFiles
cd /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E touch /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes/CMakeFiles/builtins-complete
cd /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E touch /tmp/llvm-20200530-78876-h4m6l0/llvm-10.0.0.src/llvm/build/runtimes/builtins-stamps//builtins-done
[ 86%] Built target builtins
make: *** [all] Error 2
  </pre>
</details>

https://gist.github.com/58767852a1ed15e2dafca09bcef46fa0

## What you expected to happen

I was expecting to see build succeed.

## Step-by-step reproduction instructions (by running `brew install` commands)

I have been scrupulous to ensure I had latest versions of xcode after reading other issues on here.

```
$ for c in $(which clang) "xcrun clang" /Library/Developer/CommandLineTools/usr/bin/clang ; do   echo -n "$c:" ; $c -v 2>&1 | head -n1 | grep -Eo '([0-9]+\.){3}[0-9]+' ; done | column -t -s:

/usr/bin/clang  1103.0.32.62
xcrun clang     /Library/Developer/CommandLineTools/usr/bin/clang  1103.0.32.62
```

Thus, the failing install is performed with following command:

`brew install llvm -s`

**Comment by alebcay** [comment]
Thanks for reporting this issue, apologies that we haven't gotten around to looking at it recently. LLVM is currently building away on my own Catalina machine and I've yet to see it fail (will report if that changes).

Looking through your logs though, this seems to be the culprit:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h:749:12: note: 'finite' declared here
extern int finite(double)
           ^
[snip]

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
```

This seems to indicate an issue related to the macOS SDK/SDKROOT. Hoping some other maintainers can have some other thoughts on how to resolve this.

**Comment by jpz** [comment]
Ok, I understand the error message.  `cmath` includes `math.h`

If `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ math.h` is included, this will work.

If `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/math.h` is included instead, it will cause this compiler error.  This is because `fpclassify` is a complex macro and the `using` statement will not compile, and will not have compiled in the previous version of the SDK also (I have both and the header file is unchanged.)

So this suggests there's a problem in the include path.

**Comment by alebcay** [comment]
[I think we usually work around this error with something like this](https://github.com/Homebrew/homebrew-core/blob/40692ff59b40de804ef3c71b0ce922be17a08bd9/Formula/zeromq.rb#L28). Do you know if this issue occurs with all Catalina configurations, or is this something new? I noticed that this issue was opened not soon after Xcode 11.5 was released.

**Comment by jpz** [comment]
Aha, thanks for this.  Yeah as I said, cleaned out XCode and the SDK and reinstalled to make my environment as clean as possible, and you mentioned you were able to reproduce - so I reckon it might be a Catalina issue.  (I'd not tried doing this on Mojave so I can't speak for how it was prior.)

I'm going to play with adding that snippet you linked (but substitute :high_sierra for :catalina) to `llvm.rb` and see if it fixes it, and make a pull request if it works.  It might take a few goes to see if I can get a build to work...

**Comment by alebcay** [comment]
I'm just wondering if the issue is due to the Xcode update (since `llvm` was building fine on Catalina in the past) or if somehow the issue has been on Catalina for a while and we're just seeing it now.

Basically, whether to condition that snippet on `MacOS.version == :catalina` or `Development.clang_build_version >= 1103`.
