### ISSUE TITLE
bcel link needs to be updated: bcel-6.4.0 to bcel-6.4.1

### ISSUE THREAD

**Issue by izu0421** [Homebrew/homebrew-core#55516]
PLEASE NOTE: THERE WAS A SIMILAR ISSUE BEFORE: https://github.com/Homebrew/homebrew-core/issues/44608.

Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
Error: No logs.
- [x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
bash-3.2$ brew config
HOMEBREW_VERSION: 2.3.0-2-g8a5e32c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a5e32ccc2236f2732b53c39514b36f7941b2feb
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a7c29d2d185a29cc61e6dda90f4a392b7ae904e9
Core tap last commit: 2 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.zs9Iohr2gu/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
XQuartz: 2.7.11 => /opt/X11

## What you were trying to do (and why)

Tried to install Apache Ant by running brew install ant. PLEASE NOTE: THIS HAD BEEN AN ISSUE BEFORE: https://github.com/Homebrew/homebrew-core/issues/44608.

## What happened (include command output)

Installation failed: 

brew install ant
...
Error: Failed to download resource "ant--bcel"
Download failed: https://downloads.apache.org/commons/bcel/binaries/bcel-6.4.0-bin.tar.gz

## What you expected to happen

This item was deleted: https://downloads.apache.org/commons/bcel/binaries/bcel-6.4.0-bin.tar.gz
Now, it should be: https://downloads.apache.org/commons/bcel/binaries/bcel-6.4.1-bin.tar.gz

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install ant

**Comment by izu0421** [comment]
This can be solved with brew edit ant

**Comment by izu0421** [comment]
Can be temporarily solved with brew edit ant...

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
