### ISSUE TITLE
Pretty much every brew command suspends/goes to background

### ISSUE THREAD

**Issue by mlevin2** [Homebrew/homebrew-core#55510]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run the brew command to search for and install a formula. By the way, `speedtest-cli` is just an example. This has been happening for a while now with every formula, so I don't suspect it is formula-specific.

## What happened (include command output)

Pretty much every brew command I run seems to go to the background or get suspended. I'm using zsh.

<details>
  <summary>Command output</summary>
  <pre>
$ brew search speedtest
[1]  + 21599 suspended (signal)  brew search speedtest
$ ==> Formulae
speedtest-cli ✔

[1]  + 21599 done       brew search speedtest
$ brew reinstall speedtest-cli
[1]  + 21777 suspended (signal)  brew reinstall speedtest-cli
$ ==> Downloading https://github.com/sivel/speedtest-cli/archive/v2.1.2.tar.gz
Already downloaded: /Users/mlevin/Library/Caches/Homebrew/downloads/09ba5ef7cfff3d66ed652c2f5120826332f6b24683bb5976d130a28b613519b8--speedtest-cli-2.1.2.tar.gz
==> Reinstalling speedtest-cli
🍺  /usr/local/Cellar/speedtest-cli/2.1.2: 7 files, 84.9KB, built in 4 seconds

[1]  + 21777 done       brew reinstall speedtest-cli
$ 
</pre>
</details>

## What you expected to happen

brew to behave normally :-)

## Step-by-step reproduction instructions (by running `brew install` commands)

brew search speedtest

## Other output

From `brew doctor` and `brew config`. As you can see, `brew doctor` causes the command to be suspended, while `brew config` does not. I have no idea what is going on here!

<details>
  <summary>Command output</summary>
  <pre>
$ brew doctor
[1]  + 25859 suspended (signal)  brew doctor
$
$ jobs
[1]  + suspended (signal)  brew doctor
$ fg %1
[1]  + 25859 continued  brew doctor
[1]  + 25859 suspended (signal)  brew doctor
$
$
$
$ jobs
[1]  + running    brew doctor
$
$ jobs
[1]  + suspended (signal)  brew doctor
$ fg %Your system is ready to brew.

[1]  + 25859 done       brew doctor
$ brew config
HOMEBREW_VERSION: 2.3.0-2-g8a5e32c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a5e32ccc2236f2732b53c39514b36f7941b2feb
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: affae481e774311d7820bad5de7d0bc2275e0d03
Core tap last commit: 26 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xQOL2NIBTR/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.8.0_252, 1.8.0_102, 1.8.0_92, 1.8.0_74, 1.8.0_66, 1.8.0_60, 1.8.0_51, 1.8.0_31, 1.8.0_05, 1.8.0, 1.7.0_79, 1.7.0_76, 1.7.0_71, 1.7.0_55, 1.7.0_51, 1.7.0_45, 1.7.0_11, 1.7.0_10
macOS: 10.15.4-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.4.1
XQuartz: 2.7.11 => /opt/X11
$

$ brew gist-logs speedtest-cli
[1]  + 28128 suspended (signal)  brew gist-logs speedtest-cli
$
$ jobs
[1]  + running    brew gist-logs speedtest-cli
$
$ jobs
[1]  + running    brew gist-logs speedtest-cli
$ fg
[1]  + 28128 continued  brew gist-logs speedtest-cli

https://gist.github.com/e37e86f9edeb743d12fb9c91da1b651f
$
$
</pre>
</details>

**Comment by MikeMcQuaid** [comment]
Please open this in Discourse, I cannot reproduce and have never seen this before so it's almost 100% likely to be an issue with your local shell configuration.
