### ISSUE TITLE
Building python 3.6 (python3 --devel) fails on MacPro, Sierra;

### ISSUE THREAD

**Issue by derphilipp** [Homebrew/homebrew-core#5565]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Trying to build python3.6 (via Package 'python3' with parameter '--devel') fails on MacPro, but succeeds on MacBookPro (both Sierra);

[Build Gist](https://gist.github.com/derphilipp/af8920b402c87f7c10ee86eb8c2462ee)

**Comment by derphilipp** [comment]
Update: Switching from the default `bash` as shell  to `zsh` (installed from homebrew) results in the build working;

**Comment by SkyFather** [comment]
Actually I am already using zsh, but not working at all.. I also missed my pip3.

**Comment by tdsmith** [comment]
does `env | grep PYTHON` show anything in your usual bash setup?

**Comment by derphilipp** [comment]
Just a  `PYTHONSTARTUP=/home/phw/.pythonrc`
But that happens with both shells - and it justs sets python to use readline:

```python
try:
    import readline
except ImportError:
    print("Module readline not available")
else:
    import rlcompleter
    if 'libedit' in readline.__doc__:
        readline.parse_and_bind("bind ^I rl_complete")
    else:
        readline.parse_and_bind("tab: complete")
```

**Comment by tdsmith** [comment]
Failure is here: https://gist.github.com/derphilipp/af8920b402c87f7c10ee86eb8c2462ee#file-02-make-L215

Can't reproduce; don't know what to make of it yet.

**Comment by tdsmith** [comment]
The code emitting the errors: https://github.com/python/cpython/blob/3.6/Modules/getpath.c

**Comment by framirez-bz** [comment]
I had the same issue...  here is what worked for me:

I ran 

`brew doctor` 

which returned: 

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Xcode is configured with an invalid path.
You should change it to the correct path:
  sudo xcode-select -switch /Users/username/Downloads/Xcode.app
```

After I ran that command I was able to install python and install additional python related items. I needed pycurl so ran 

`pip -v install pycurl`

things have been working fine.

**Comment by santagada** [comment]
I tried using zsh to install it and it didn't work, and brew doctor also didn't have any problems to report so I just installed it with --force-bottle and it is working for now. I know my homebrew installs it from source because I had some flag set, but I can't remember which.

**Comment by MikeMcQuaid** [comment]
@santagada `brew uninstall python3; brew install python3` may be a better bet for future reference.

**Comment by yxwzaxns** [comment]
I had the same issue when I upgrade python3.5 to 3.6, I had a result when checking for getaddrinfo:

```
checking getaddrinfo bug... yes
Fatal: You must get working getaddrinfo() function.
       or you can specify "--disable-ipv6".
```
so I can't upgrade succeed
how can to resolve the problem

**Comment by tdsmith** [comment]
That's not a related error and it looks kind of bizarre! Make sure you have the latest version of Xcode for your OS installed and please open a new ticket with the output of `brew gist-logs python3`.
