### ISSUE TITLE
After upgrade to mkvtoolnix 47.0.0 on Mojave, package tools fail due to missing library

### ISSUE THREAD

**Issue by donmelton** [Homebrew/homebrew-core#55686]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ X] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
Error: No logs.
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was just doing a `brew update` and then `brew upgrade`. My normal morning routine.

After getting the upgrade to mkvtoolnix 47.0.0, none of the tools in that package work anymore.

Here's what happens now when you run `mkvmerge`:

```
mkvmerge --version
dyld: Library not loaded: /usr/local/opt/fmt/lib/libfmt.6.dylib
  Referenced from: /usr/local/bin/mkvmerge
  Reason: image not found
Abort trap: 6
```

And the reason why that library is not loaded is because it doesn't exist. At least, not at that location.

Clearly something is wrong with the updated formula.

## What happened (include command output)

After my upgrade to mkvtoolnix 47.0.0 on my Mojave system, all of that package's tools fail due to a missing library.

I've confirmed the same thing happens for another user. So it's not just me.

<details>
  <summary>Command output</summary>
  <pre>

  brew update
  brew upgrade
  mkvmerge --version

  </pre>
</details>

## What you expected to happen

Well, I kind of expected `mkvmerge` to actually work.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above.

**Comment by SMillerDev** [comment]
Do you have fmt installed?

**Comment by donmelton** [comment]
@SMillerDev Sure. It's at `/usr/bin/fmt`. Why?

**Comment by SMillerDev** [comment]
Because it's not defined as a dependency and I wanted to know where it went wrong

**Comment by donmelton** [comment]
@SMillerDev The `fmt` tool is built into every Unix system. Why would it be a dependency?

**Comment by SMillerDev** [comment]
on macOS, usually because system tools are outdated

**Comment by Bo98** [comment]
Should be fixed now.

**Comment by donmelton** [comment]
@Bo98 Confirmed. I had to reinstall `mkvtoolnix` but I expected that. My thanks to @SMillerDev and you all!
