### ISSUE TITLE
install pkg control produces internal compiler error

### ISSUE THREAD

**Issue by CDWilliams2019** [Homebrew/homebrew-core#55856]
# Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose or we will close it without comment.

pkg install -forge control
<built-in>: internal compiler error: Illegal instruction: 4
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make: *** [slicotlibrary.a] Error 1
make: *** Waiting for unfinished jobs....
tar -xzf slicot.tar.gz
/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin/mkoctfile-4.4.1
-Wall -Wno-deprecated-declarations  __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp;
/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin/mkoctfile-4.4.1
-c *.f

pkg: error running `make' for the control package.
error: called from
   configure_make at line 99 column 9
   install at line 184 column 7
   pkg at line 437 column 9

**Comment by claui** [comment]
Please use the issue template.

**Comment by CDWilliams2019** [comment]
Hello Claudia:

I am trying to use the issue template but I have not done this before and it is not working for me.

Is there an example somewhere of how to complete an issue template?

I have put an 'x' in each of the [x] boxes for the 4 questions.

I have typed responses for each of the ## questions.

I have run 
   brew update
   brew doctor
 brew gist-logs octave

several times and get lots of warnings.

I cannot upgrade Xcode so I have uninstalled it.

But the green "submit new issue" remains dim so I cannot activate it.

Here is the error I get when I try to install the control package for Octave v4.4.1 on Mac OS X High Sierra
======================================

>> pkg install -forge control
<built-in>: internal compiler error: Illegal instruction: 4
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make: *** [slicotlibrary.a] Error 1
make: *** Waiting for unfinished jobs....
tar -xzf slicot.tar.gz
/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin/mkoctfile-4.4.1 -Wall -Wno-deprecated-declarations  __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
cp TG04BX.fortran ./sltmp/TG04BX.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cd sltmp; /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin/mkoctfile-4.4.1 -c *.f

pkg: error running `make' for the control package.
error: called from
    configure_make at line 99 column 9
    install at line 184 column 7
    pkg at line 437 column 9
>>
=======================================
I have tried to file a bug report with the Octave people but they say it is a Home Brew problem not an Octave problem

My apologies for being a confused newbie to this process.

Best regards,
Christopher

**Comment by claui** [comment]
Thanks @CDWilliams2019 for clearing that up. Reopening.

**Comment by SMillerDev** [comment]
Please copy this into a comment and fill it out then. Providing all of the information in it is very important. When you say "I get a lot of issues in `brew doctor` and `brew gist-log` any of these could be causing your problem and without it we have no way to help.

```
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<!-- To help us debug your issue, please complete these sections: -->

## What you were trying to do (and why)

<!-- replace me -->

## What happened (include command output)

<!-- replace me -->

<details>
  <summary>Command output</summary>
  <pre>

  <!-- replace this with the command output -->

  </pre>
</details>

## What you expected to happen

<!-- replace me -->

## Step-by-step reproduction instructions (by running `brew install` commands)

<!-- replace me -->

```
