### ISSUE TITLE
Formula.md5 is disabled

### ISSUE THREAD

**Issue by testzugang** [Homebrew/homebrew-core#5586]
When installing SWIG the following error occurs:

`brew install https://raw.github.com/cobrateam/formulae/master/swig.rb`
######################################################################## 100,0%
Error: Calling Formula.md5 is disabled!
Use Formula.sha256 instead.
/Users/mg/Library/Caches/Homebrew/Formula/swig.rb:6:in `<class:Swig>'
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils.rb:86:in `odeprecated'
/usr/local/Homebrew/Library/Homebrew/utils.rb:94:in `odisabled'
/usr/local/Homebrew/Library/Homebrew/compat/md5.rb:3:in `md5'
/Users/mg/Library/Caches/Homebrew/Formula/swig.rb:6:in `<class:Swig>'
/Users/mg/Library/Caches/Homebrew/Formula/swig.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:153:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:222:in `factory'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:107:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'

**Comment by MikeMcQuaid** [comment]
That formula is broken. Use `brew install swig` or report this to https://github.com/cobrateam/homebrew-formulae.
