### ISSUE TITLE
gnu units: invalid/unprintable unicode code points

### ISSUE THREAD

**Issue by adrianVmariano** [Homebrew/homebrew-core#55902]
Mike McQuaid said to post this as an issue here, but this template doesn't really fit the issue, which is not about installation but about how GNU Units functions under MacOS with UTF_8.  

# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I don't believe this is an installation issue so I don't think the above stuff is relevant.  My access to MacOS is limited, just for testing purposes.  If this turns out to be relevant then I'll get access to get these test results.  

## What you were trying to do (and why)

I am the author of GNU units.  Years ago I got the complaint that certain unicode characters were flagged as invalid/unprintable only on the mac.  I had to comment out these characters in definitions.units.  Recently somebody told me this was fixed.  I gained access to a mac runing MacOS 10.15.4 and installed units with homebrew but the "MaOS fail" entries still failed.  

I noticed, however, that they worked under vim, which seemed odd.  Why would they be invalid characters under units but valid under vim?  

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

If "fails in MacOS" lines of definitions.units are uncommented then units displays "invalid/non-printing UTF-8" warning messages

  </pre>
</details>

## What you expected to happen

What I hoped would happen was correct handling of the utf-8 input. 

## Step-by-step reproduction instructions (by running `brew install` commands)

With installed copy of GNU units, uncomment the definitions.units lines that say "fails under MacOS" or "MacOS fail".  Invoke units with "units".   Warning messages "invalid/nonprinting UTF-8" appear.

**Comment by gromgit** [comment]
I uncommented the three glyphs you mentioned (1/7, 1/9 and 1/10), then ran `units`...and got no error messages in Mojave.

I'd like to test this further, so how do I go about generating an output that contains one or all of these problem glyphs?

**Comment by adrianVmariano** [comment]
I'm not sure what you mean when you ask how to generate an output (input?) that contains the problem glyphs.  I think the test of uncommenting those entries in definitions.units and invoking units suffices as a test.  If you wanted to try a further test you could pass as input <1/7>m as input, where <1/7> is the utf8 for 1/7, then a blank line, and see if it correctly displays '0.1428 m'.   If I pass the 1/7 character as input after units is running it gives me the message "Error: invalid/nonprinting UTF-8".   If I do this under linux it just tells me "Unknown unit" (because the line is commented out still).   If you are looking for a minimal test case you could copy just one of the lines from definitions.units that contains a problem glyph to a file by itself and invoke units with -f on that file.  Or I suppose just invoke units and pass it offending glyphs on input and see what happens.  (If they aren't defined in the database they should be "unknown unit" rather than "invalid/nonprinting UTF-8".)

On my available test mac (which is running 10.15.5) when I uncomment those entries and run 'gunits' I get:

gunits: invalid/nonprinting UTF-8 on line 7312 of 'definitions.units'
gunits: invalid/nonprinting UTF-8 on line 7313 of 'definitions.units'
gunits: invalid/nonprinting UTF-8 on line 7314 of 'definitions.units'
3116 units, 109 prefixes, 109 nonlinear units

Could this behavior depend on some other installed/missing packages?  Or other environment configuration?

**Comment by gromgit** [comment]
_Mea culpa_, my previous comment was literally correct: I'd run `units` instead of `gunits`, and hence got a false negative.

Anyway, I wrote a test program to sanity-check `definitions.units` by reading it and using the same `wchar` routines as units to tear the input apart. I ran it as follows:
```
tail -n +7294 definitions.units | head -n 30 | ./test-mb
```
to just look at the abovementioned section. Here's what I discovered:
On Ubuntu 18.04, all outputs (length, bytes, strings) were correct:
```
<=[45] 23 e2 85 90 2d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 7c 37 20 20 20 23 20 66 61 69 6c 73 20 75 6e 64 65 72 20 4d 61 63 4f 53 
=>[43,43]#⅐-               1|7   # fails under MacOS
<=[45] 23 e2 85 91 2d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 7c 39 20 20 20 23 20 66 61 69 6c 73 20 75 6e 64 65 72 20 4d 61 63 4f 53 
=>[43,43]#⅑-               1|9   # fails under MacOS
<=[45] 23 e2 85 92 2d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 7c 31 30 20 20 23 20 66 61 69 6c 73 20 75 6e 64 65 72 20 4d 61 63 4f 53 
=>[43,43]#⅒-               1|10  # fails under MacOS
```
On Mojave, `wcswidth()` returns -1 on the three problematic strings:
```
<=[45] 23 e2 85 90 2d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 7c 37 20 20 20 23 20 66 61 69 6c 73 20 75 6e 64 65 72 20 4d 61 63 4f 53 
=>[43,-1]#⅐-               1|7   # fails under MacOS
<=[45] 23 e2 85 91 2d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 7c 39 20 20 20 23 20 66 61 69 6c 73 20 75 6e 64 65 72 20 4d 61 63 4f 53 
=>[43,-1]#⅑-               1|9   # fails under MacOS
<=[45] 23 e2 85 92 2d 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 31 7c 31 30 20 20 23 20 66 61 69 6c 73 20 75 6e 64 65 72 20 4d 61 63 4f 53 
=>[43,-1]#⅒-               1|10  # fails under MacOS
```

You can try running my test program on Catalina to verify those results. It seems like something's still b0rken in macOS `wchar`-ville.

**Comment by adrianVmariano** [comment]
Two other things:  I got a user report that "it's been fixed" and was supposedly working.  (When I followed up with that user with questions I got no reply.)   Another observation is that on my test mac I can edit definitions.units in vi and everything works:  the glyphs 1/7, 1/9 and 1/10 all display (though they seem a bit wide).   Does this work because wcswidth isn't used?  My friend doesn't have a dev environment set up on the mac so I'd have to install that to actually compile code there, but it seems unlikely I'd observe different results than what you're getting.

**Comment by gromgit** [comment]
> I got a user report that "it's been fixed" and was supposedly working. (When I followed up with that user with questions I got no reply.)

Perhaps they made the same mistake I did. :grimacing: 

> Another observation is that on my test mac I can edit definitions.units in vi and everything works: the glyphs 1/7, 1/9 and 1/10 all display (though they seem a bit wide). Does this work because wcswidth isn't used?

I looked through the Vim source code, and they indeed do _not_ call `wcswidth()`, though there's an unused and very old [third-party implementation](http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c) in the source distribution.

**Comment by gromgit** [comment]
@adrianVmariano  I just upgraded my macOS box to Catalina, so I tried running my test code again, and I can confirm that Catalina's `wcswidth` is still broken in the same way. Probably the only thing that can be done at this stage is to find a `wcswidth` alternative for your purposes, so I think this issue can be closed. Good luck with finding a solution!

**Comment by iMichka** [comment]
Closing as this is not a brew issue.
