### ISSUE TITLE
`brew link` did not complete successfully (Ruby)

### ISSUE THREAD

**Issue by chrisfinazzo** [Homebrew/homebrew-core#5593]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

I encountered this issue when updating to a new version of Ruby 2.3.1. Currently, all of my projects are on 2.1.0 or 2.3.0, so this may just be an artifact of running an old version, but the behavior is odd.

For completeness sake, my `brew config`  is as follows: 

<img width="697" alt="screen shot 2016-10-04 at 11 38 02 am" src="https://cloud.githubusercontent.com/assets/1534882/19081090/178c52d4-8a27-11e6-9b8b-bb0167a11297.png">

Running `brew gist-logs ruby` reports nothing as this isn't really a failed build, but Ruby simply doing the wrong thing. The obvious concern is breaking things with `brew link --overwrite` as the files it would touch are central to a working setup.

<img width="697" alt="screen shot 2016-10-03 at 7 46 23 pm" src="https://cloud.githubusercontent.com/assets/1534882/19081390/10810b46-8a28-11e6-937c-02ce19a3328e.png">

P.S: Pay no attention to the `book` command, that's not Homebrew's fault.

**Comment by MikeMcQuaid** [comment]
What does `ls -lha /usr/local/bin/rake` show?

**Comment by chrisfinazzo** [comment]
<img width="697" alt="screen shot 2016-10-04 at 11 50 16 am" src="https://cloud.githubusercontent.com/assets/1534882/19081581/c202fa64-8a28-11e6-982a-84fe599b3521.png">

**Comment by ilovezfs** [comment]
brew doctor says ... ?

**Comment by MikeMcQuaid** [comment]
In that case this is expected behaviour. Homebrew did not create this file so it refuses to delete it automatically. You can choose what to do by following the printed instructions.
