### ISSUE TITLE
'brew install kallisto' taking forever because of gcc install 

### ISSUE THREAD

**Issue by csa005** [Homebrew/homebrew-core#55963]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by csa005** [comment]
Trying to install kallisto. 
Stuck on gcc install and taking really long. 
Expected install to be shorter, 
brew install kallisto

**Comment by SMillerDev** [comment]
Please actually perform the actions that you marked as done. This can be reopened when the required information is provided

**Comment by csa005** [comment]
Ran all actions, issue still remains that this screen has not changes since last night 
![Screen Shot 2020-06-09 at 8 10 51 AM](https://user-images.githubusercontent.com/66677957/84145907-c0e70200-aa28-11ea-8ca3-148c1e9b8fa8.png)

**Comment by SMillerDev** [comment]
> ran brew gist-logs <formula> (where <formula> is the name of the formula that failed) **and included the output link?**
if brew gist-logs didn't work: ran brew config and brew doctor **and included their output with your issue?**

You missed these two parts at the very least
