### ISSUE TITLE
glib 2.50.0 build fails during patching (10.8)

### ISSUE THREAD

**Issue by dcwar** [Homebrew/homebrew-core#5602]
Hi!

It seems that glib 2.50.0 will not build on 10.8 as a result of the patches failing. In the gist of the console output (below), the failure begins on line 275, when "patching file gio/Makefile.in".

Console output:
https://gist.github.com/dcwar/5348464a7ac57ecf646efa16cae14043

Many thanks!

**Comment by ilovezfs** [comment]
@dcwar mind testing https://github.com/Homebrew/homebrew-core/pull/5530?

**Comment by dcwar** [comment]
Successful build!
