### ISSUE TITLE
404 on poetry install

### ISSUE THREAD

**Issue by austinbutler** [Homebrew/homebrew-core#56022]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install poetry`

I get a 404 on work VPN, home internet, and cellular data.

## What happened (include command output)

404 downloading the bottle for 1.0.9.

<details>
  <summary>Command output</summary>
  <pre>
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/poetry-1.0.9.catalina.bottle.tar.gz
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "poetry"
Download failed: https://homebrew.bintray.com/bottles/poetry-1.0.9.catalina.bottle.tar.gz
  </pre>
</details>

## What you expected to happen

Bottle download works.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install poetry`

**Comment by jonchang** [comment]
Thanks for the report, should be fixed now.
