### ISSUE TITLE
404 for brew install lastpass-cli

### ISSUE THREAD

**Issue by tobinus** [Homebrew/homebrew-core#56034]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Two colleagues of mine also got the same error when they tried.

## What you were trying to do (and why)

Tried installing the `lastpass-cli` formula.

## What happened (include command output)

While dependencies were downloaded successfully, lastpass-cli itself failed to download.

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles/curl-7.70.0.catalina.bottle.tar.gz
Already downloaded: /Users/n643674/Library/Caches/Homebrew/downloads/0dd6194ae8605b961d6c4d53d4fade5e478c2d6b45e59f64c83df221fc609920--curl-7.70.0.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/libgpg-error-1.38.catalina.bottle.tar.gz
Already downloaded: /Users/n643674/Library/Caches/Homebrew/downloads/aa6778a1846b489cc47c658f4a4d584b7bbec1b910a430152d252b18dba8428b--libgpg-error-1.38.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/lastpass-cli-1.3.3_1.catalina.bottle.2.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "lastpass-cli"
Download failed: https://homebrew.bintray.com/bottles/lastpass-cli-1.3.3_1.catalina.bottle.2.tar.gz
  </pre>
</details>

## What you expected to happen

I expected the installation to succeed.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install lastpass-cli`

**Comment by iMichka** [comment]
There is an ongoing bintray incident: https://status.bintray.com/

> We have encountered some issues with our backend servers, which may impact the downloads and the users may experience degraded performance, our team is working on fixing the same.

**Comment by tobinus** [comment]
I was not aware of that website, thanks!
