### ISSUE TITLE
Dupe of #56021.

### ISSUE THREAD

**Issue by ipolyzos** [Homebrew/homebrew-core#56038]
@alebcay, @SMillerDev  both PRs for updating kamel (#56021; and #56002)  are closed as duplicate to search other. Could you please reopen and merge?

**Comment by SMillerDev** [comment]
#56002 is still open but failing

**Comment by ipolyzos** [comment]
> #56002 is still open but failing

I was working on #56021 this n should be ok

**Comment by issyl0** [comment]
Kamel has been updated. Thanks!
