### ISSUE TITLE
Missing jpegtran dependency breaks `jhead -autorot`

### ISSUE THREAD

**Issue by mgol** [Homebrew/homebrew-core#5616]
Homebrew 1.0.6
Homebrew/homebrew-core (git revision 737a; last commit 2016-10-05)
macOS 10.12 (16A323)

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

```
$ brew install jhead
$ jhead -autorot 0.jpg
sh: jpegtran: command not found

Error : Problem executing specified command
in file '0.jpg'
```

**Comment by mgol** [comment]
`brew install imagemagick` fixes the issue. Should it be a dependency of `jhead`?

**Comment by MikeMcQuaid** [comment]
@mgol Sounds like a `:recommended` dependency, yeh. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by zmwangx** [comment]
`jpegtran(1)` is provided by `jpeg`, not `imagemagick`.
