### ISSUE TITLE
Please return Vapoursynth to mpv.rb

### ISSUE THREAD

**Issue by chainikdn** [Homebrew/homebrew-core#56173]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

For some odd reason https://github.com/Homebrew/homebrew-core/pull/55906 was approved, completely removing the Vapoursynth dependency from mpv.  We really need it back.

**Comment by claui** [comment]
@chainikdn I assume you noticed the part of the description in #55906 where it says the dependency could no longer be found at build time. That’s hardly an “odd reason”.

If it happens to work again in a future release of mpv or Vapoursynth, we’re happy to review a PR that re-adds the dependency.

Closing the issue for now but feel free to comment anyway if you have any helpful information for us.

**Comment by chainikdn** [comment]
Ok, so why "the dependency could no longer be found at build time"?
Vapoursynth package is still here.

**Comment by chainikdn** [comment]
Here's a helpful information: the issue is in python-3.8 installation, since python-3.8.pc is missing in pkgconfig and vapoursynth-script.pc depends on python-3.8, so mpv's check for the vapoursynth-script fails.

**Comment by claui** [comment]
https://github.com/Homebrew/homebrew-core/pull/55906#issuecomment-642915745

**Comment by claui** [comment]
Thanks @chainikdn for the pointer. Reopening.

**Comment by claui** [comment]
I second what https://github.com/Homebrew/homebrew-core/pull/55906#issuecomment-643069693 says so closing this again now. Feel free to open a PR.
