### ISSUE TITLE
User's PYTHONPATH is ignored by IPython

### ISSUE THREAD

**Issue by akira-okumura** [Homebrew/homebrew-core#56195]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
% brew gist-logs ipython
Error: No logs.
```

```
% brew config 
HOMEBREW_VERSION: 2.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 28ed0801ed5807e176e62a3ba66e47ec867ec17d
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1985363326eb9a1cdfaf599dcfb8ab2ad9440518
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 2
CPU: dual-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A
```

## What you were trying to do (and why)

I tried to use a Python package that is not installed in default search paths and set the `PYTHONPATH` variable in `~/.zshrc` to add the non-standard package location.

## What happened (include command output)

`PYTHONPATH` is overwritten by the `ipython` bash script.

<details>
  <summary>Command output</summary>
  <pre>
% export PYTHONPATH=/Applications:$PYTHONPATH
% ipython
Python 3.8.3 (default, May 27 2020, 20:54:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os 
   ...: print( 'PYTHONPATH = ', os.environ['PYTHONPATH'] )                      
PYTHONPATH =  /usr/local/Cellar/ipython/7.15.0/libexec/lib/python3.8/site-packages:/usr/local/Cellar/ipython/7.15.0/libexec/vendor/lib/python3.8/site-packages
  </pre>
  <pre>
% which ipython
/usr/local/bin/ipython
% cat `which ipython`
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/ipython/7.15.0/libexec/lib/python3.8/site-packages:/usr/local/Cellar/ipython/7.15.0/libexec/vendor/lib/python3.8/site-packages" exec "/usr/local/Cellar/ipython/7.15.0/libexec/bin/ipython" "$@"
  </pre>
</details>

## What you expected to happen

`PYTHONPATH` should not be overwritten. It should be inherited from the shell environment.

If you install IPython by the `pip3` command, `PYTHONPATH` is not overwritten.

```
% brew install python
% rehash
% pip3 install ipython
% rehash
% cat `which ipython`
#!/usr/local/opt/python/bin/python3.7
# -*- coding: utf-8 -*-
import re
import sys
from IPython import start_ipython
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(start_ipython())
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```
% /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
% brew install ipython
% export PYTHONPATH=/Applications:$PYTHONPATH
% ipython
Python 3.8.3 (default, May 27 2020, 20:54:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os 
   ...: print( 'PYTHONPATH = ', os.environ['PYTHONPATH'] )                      
PYTHONPATH =  /usr/local/Cellar/ipython/7.15.0/libexec/lib/python3.8/site-packages:/usr/local/Cellar/ipython/7.15.0/libexec/vendor/lib/python3.8/site-packages
```

I confirmed this behavior with a clean 10.15.5 virtual machine.

**Comment by gromgit** [comment]
@akira-okumura  That's now fixed. `brew update`, `brew upgrade`, test it for yourself, then you can close this issue.

**Comment by akira-okumura** [comment]
Thank you very much.
