### ISSUE TITLE
Enable http server while installing fluent-bit

### ISSUE THREAD

**Issue by championshuttler** [Homebrew/homebrew-core#56214]
Enable the http server while installing fluent-bit in macos, the flag for http monitoring server is `DFLB_HTTP_SERVER=on` 

https://docs.fluentbit.io/manual/administration/monitoring

**Comment by issyl0** [comment]
We'd gladly review a [pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) that enables this feature! Please always fill out the issue template when raising issues.
