### ISSUE TITLE
Missing dependencies of black

### ISSUE THREAD

**Issue by isac322** [Homebrew/homebrew-core#56328]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

### Output of `brew gist-logs black`

```
Error: No logs.
```

### Output of `brew config`

```
HOMEBREW_VERSION: 2.4.0-41-g0125c4c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0125c4cd56b1e9a238206090dbf3f6a24a463c7d
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7a12c4e47ad249f720c32caa3f64060f9dff619e
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A
```

## What you were trying to do (and why)

```bash
brew install black
blackd
```

to run [blackd](https://black.readthedocs.io/en/stable/blackd.html)

## What happened (include command output)

1. After brew install

```
Traceback (most recent call last):
  File "/usr/local/bin/blackd", line 5, in <module>
    from blackd import patched_main
  File "/usr/local/Cellar/black/19.10b0_2/libexec/lib/python3.8/site-packages/blackd.py", line 9, in <module>
    from aiohttp import web
ModuleNotFoundError: No module named 'aiohttp'
```

2. After `/usr/local/Cellar/black/19.10b0_2/libexec/bin/python3.8 -m pip install aiohttp`

```
Traceback (most recent call last):
  File "/usr/local/bin/blackd", line 5, in <module>
    from blackd import patched_main
  File "/usr/local/Cellar/black/19.10b0_2/libexec/lib/python3.8/site-packages/blackd.py", line 10, in <module>
    import aiohttp_cors
ModuleNotFoundError: No module named 'aiohttp_cors'
```

3. After `/usr/local/Cellar/black/19.10b0_2/libexec/bin/python3.8 -m pip install aiohttp_cors`

```
blackd version 19.10b0 listening on localhost port 45484
INFO:aiohttp.access:127.0.0.1 [15/Jun/2020:05:42:30 +0000] "POST / HTTP/1.1" 200 13515 "-" "Java/11.0.7"
```

## What you expected to happen

```
blackd version 19.10b0 listening on localhost port 45484
INFO:aiohttp.access:127.0.0.1 [15/Jun/2020:05:42:30 +0000] "POST / HTTP/1.1" 200 13515 "-" "Java/11.0.7"
```

without installing extra dependencies manually.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install black
blackd
```

---

I'm a newbie in MacOS and Homebrew. Could you please add those dependencies to the formula?

**Comment by linzichao** [comment]
I have the same issue.
I can add it.

**Comment by isac322** [comment]
It works! thanks @linzichao !
