### ISSUE TITLE
MacVim Failed to installing from source on 10.11.6

### ISSUE THREAD

**Issue by tonkoshkurik** [Homebrew/homebrew-core#5639]
Before MacVim been installed from bottle but it's have wrong Python directory. So, i found solution install macvim from source but here is another trouble...
Here is [Gist-logs](https://gist.github.com/tonkoshkurik/3f3571d2a7aa1db1a33d5f4515669312)

**Comment by ilovezfs** [comment]
What's the output of
```
xcode-select -p
```

**Comment by tonkoshkurik** [comment]
`/Library/Developer/CommandLineTools`

**Comment by ilovezfs** [comment]
```
sudo xcode-select -r
```

**Comment by ilovezfs** [comment]
@tonkoshkurik I assume it's fixed now if you try again?

**Comment by tonkoshkurik** [comment]
@ilovezfs  amazing!!) Thank you so much

**Comment by ilovezfs** [comment]
You're welcome :)
