### ISSUE TITLE
Cryptopp can't be bottled

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-core#56394]
Cryptopp can only be ran on the same architecture so we can't use bottles right now. We should resolve this.

For more info https://github.com/Homebrew/homebrew-core/pull/56341 and https://github.com/Homebrew/homebrew-core/pull/41700

**Comment by fxcoudert** [comment]
The formula was removed in f5961382fd70bc3594b50b21d475a4844fe5cee8
