### ISSUE TITLE
Node/NPM Version mismatch causes ERR_OUT_OF_RANGE

### ISSUE THREAD

**Issue by gitbugr** [Homebrew/homebrew-core#56405]
## What you were trying to do (and why)

upgrade node.js / npm

## What happened (include command output)

node was updated to latest, npm is a version behind, causing a mismatch.

<details>
  <summary>Command output</summary>
  <pre>
        ➜ npm i -g npm
        npm ERR! code ERR_OUT_OF_RANGE
        npm ERR! The value of "err" is out of range. It must be a negative integer. Received 
        ➜ node --version
        v14.4.0
        ➜ npm --version
        6.14.4
  </pre>
</details>

## What you expected to happen

no, error, should be on right version
```
➜ node --version
v14.4.0
➜ npm --version
6.14.5
```

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install node`

## Temp fix:

This **should** have been fixed, but this wasn't merged:
https://github.com/Homebrew/homebrew-core/pull/55761

as a workaround, we can use this:

```
brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/de4804aa087e2483d2d4c5350e197bd173d3f47c/Formula/node.rb
```

**Comment by SMillerDev** [comment]
For anyone reading this, before you install a package from a random link on the internet you should probably check what it does.

**Comment by gitbugr** [comment]
> For anyone reading this, before you install a package from a random link on the internet you should probably check what it does.

Sorry, should've put a warning. Changed the link to point to the specific commit for security.
The commit is from the PR I mentioned and contains a single-line change to bump the version number of npm.

Diff here:
https://github.com/Homebrew/homebrew-core/pull/55761/commits/de4804aa087e2483d2d4c5350e197bd173d3f47c

**Comment by gromgit** [comment]
@gitbugr, is this still an issue, now that #57178 has been put to bed? If not, please close it.

**Comment by gitbugr** [comment]
This was fixed in https://github.com/Homebrew/homebrew-core/commit/0071894417adc7f206707b4b08a0f5e5d18174fb
