### ISSUE TITLE
Go 1.14.4 upgrade failures

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-core#56539]
From https://github.com/Homebrew/homebrew-core/pull/55639

```console
brew test --verbose annie
brew install --build-from-source charm
brew test --verbose darksky-weather
brew install --build-from-source dashing
brew test --verbose dashing
brew install --build-from-source dvm
brew test --verbose faas-cli
brew install --build-from-source gor
brew test --verbose jabba
rm -rf /Users/brew/Library/Caches/Homebrew
brew install --build-from-source perkeep
brew install --build-from-source source-to-image
brew install --build-from-source sync_gateway
brew install --build-from-source wellington
```

@Bo98 will let you edit this with more detail when you get a chance!

**Comment by roopakv** [comment]
@Bo98 I would love to help to either remove these or fix them. I don't understand how to decide so please let me know what needs to be done and I'll get on it

**Comment by SMillerDev** [comment]
Just update to the latest go and run one of the commands above. It won't complete succesfully but from there you can fix it.

**Comment by roopakv** [comment]
@SMillerDev the thing is, many of these repos like wellington or perkeep have issues building, or changes need to happen in those repos. In those cases I have already filed issues or sent PRs to some of those repos (around go 1.14.1's release). There has been no response.

IMHO in those cases the best case should be to remove from brew?

I could go an do the issue filing for the remaining repos but want to make sure there is one strategy we use for all the failing formulae

**Comment by SMillerDev** [comment]
If upstream doesn't respond and it doesn't build the formula can be removed. But we should try and help them first, preferably by providing pull requests.

**Comment by roopakv** [comment]
So in a case like this: https://github.com/buger/goreplay/issues/739 where I have opened an issue for them to cut a new release and they haven't done so yet, can I go ahead and send a PR removing the `gor` formula?

**Comment by SMillerDev** [comment]
While that's an edge case where they have the support but no release, but since it barely has any installs... sure.

**Comment by alebcay** [comment]
Just fired off an email to three `goreplay` devs - hopefully that will garner more of a response 🤞.

**Comment by alebcay** [comment]
Install for `source-to-image` is failing due to upstream tag's revision seeming to have changed. Opened an issue asking for upstream to clarify on this change: https://github.com/openshift/source-to-image/issues/1047.

**Comment by alebcay** [comment]
`dvm` should be fixed by https://github.com/Homebrew/homebrew-core/pull/56740.

**Comment by dawidd6** [comment]
`wellington`: https://github.com/wellington/wellington/issues/218

**Comment by alebcay** [comment]
`source-to-image` should be fixed by #56836.

**Comment by alebcay** [comment]
`annie` seems to have worked without any issues in #56867.

**Comment by dawidd6** [comment]
> `annie` seems to have worked without any issues in #56867.

The test might be flaky tho. Since it relies on a video that is pulled from internet.

**Comment by chenrui333** [comment]
Closing this in favor of [go1.15 tracker](#59698)
