### ISSUE TITLE
curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.

### ISSUE THREAD

**Issue by patryk** [Homebrew/homebrew-core#5655]
I want to install curl with HTTP2 support, but instead it stops working altogether. I get the message for whatever request I try to invoke:
`curl: (4) A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.`

The install command is:
`brew install curl --with-nghttp2`

`brew gist-logs curl`
https://gist.github.com/5aaf5e5f16ef37147cc48be7555f503d

**Comment by tdsmith** [comment]
Does the error persist if you rename your curlrc?

**Comment by patryk** [comment]
Dang, you're right. This is what I had in my `.curlrc`:
`--false-start
--compressed`

After I commented out `--false-start`, it resumed working fine. I believe it is because openssl does not support it. Unfortunately the error message is absolutely un-helpful :( Thanks for pointing it out.

Safe to close this issue.
