### ISSUE TITLE
Typo in git-extras caveats

### ISSUE THREAD

**Issue by drewbrew** [Homebrew/homebrew-core#56696]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [N/A] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

(The formulas did not fail; this is only a typo, so logs are needless)

## What you were trying to do (and why)

Install git-extras (for extra git completion)

## What happened (include command output)

The installation executed successfully, but the caveats list the wrong file.

<details>
  <summary>Command output</summary>
  <pre>

  ==> Checking for dependents of upgraded formulae...
==> No dependents found!
==> Downloading https://homebrew.bintray.com/bottles/git-extras-6.0.0.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-extras-6.0.0.catalina.bottle.tar.gz
==> Caveats
To load Zsh completions, add the following to your .zschrc:
  source /usr/local/opt/git-extras/share/git-extras/git-extras-completion.zsh

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/git-extras/6.0.0: 146 files, 331.3KB

  </pre>
</details>

## What you expected to happen

It should point to `.zshrc`, not `.zschrc`.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install git-extras`

**Comment by drewbrew** [comment]
I have a fix [here](https://github.com/drewbrew/homebrew-core/commit/b78cf1e1fb359b818394fa4879dc8a26fb454834) but I'm having noob problems trying to get homebrew to install from my branch (likely PEBKAC issue).

**Comment by issyl0** [comment]
That change will fix the issue. Feel free to raise a PR with your fix, @drewbrew.

**Comment by issyl0** [comment]
Fixed! :tada: (The issue didn't auto-close because of the way we merge PRs.)
