### ISSUE TITLE
Initial install of Homebrew a complete failure; how to clean up the mess?!

### ISSUE THREAD

**Issue by bsdforge** [Homebrew/homebrew-core#5674]
I attempted an initial install of Homebrew on OSX 10.6.8, as instructed at http://brew.sh/
eg; /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Which resulted in a myriad of errors (appended to this report). How can I back out?
I'm left with a boat load of new folders, and files with alternate permissions, and locations.
Thank you for all your time, and consideration.

--Chris

errors attached:

[BREW_BARF.txt](https://github.com/Homebrew/homebrew-core/files/517340/BREW_BARF.txt)

**Comment by bsdforge** [comment]
OK. Was finally able to sort it out.
All attempts to implement uninstall failed due to the brew binary being unavailable.
So I made a few additional attempts to run the install method, and was able to finally
discover that it didn't know how to properly create all the necessary directories. So
when I finally determined *which* directories were missing, and where, I created them,
and again, ran the install script. It then managed to nearly complete. But required a
great bit of "hand holding" on my part to finally get through the entire process.
I'm puzzled that this turned out to be such a chore. I am performing all this on a
*vanilla* install of OSX 10.6, which was followed by the apple 10.6.8Combo update.
I also installed the Xcode from the install DVD, along with the UNIX supplement. Does
this also require something else? Reading the online documentation revealed no
additional requirements other than what I already had.

Anyway, thanks for any attention you may have given this.

--Chris

**Comment by MikeMcQuaid** [comment]
> So when I finally determined which directories were missing, and where, I created them,
> and again, ran the install script

Which were they?

> I'm puzzled that this turned out to be such a chore.

10.6 is extremely outdated at this point so we're not able to do any testing on it hence problems like this, unfortunately.

**Comment by bsdforge** [comment]
Thank you for your reply!

    So when I finally determined which directories were missing, and where, I created them,
    and again, ran the install script

Which were they?

The only one I can remember off the top of my head, was Library
(/usr/local/Library) I wish I could remember the others, but have since lost my
terminal history. :-(

    I'm puzzled that this turned out to be such a chore.

10.6 is extremely outdated at this point so we're not able to do any testing on it hence problems like this, unfortunately.

Sure. I understand. But other than the initial install, it (HomeBrew) has worked as
expected -- or should I say; as UNexpected. ;-)
I'd be happy to provide a testbed, if should you have a need to test compatibility for
anything.

Thanks again!

--Chris

**Comment by MikeMcQuaid** [comment]
> The only one I can remember off the top of my head, was Library
> (/usr/local/Library)

Ok, that's good to know. I believe it should be created on first login but I'll consider adding it to the installer anyway.

**Comment by MikeMcQuaid** [comment]
Actually, sorry, I misread that: that shouldn't be created or required by the current Homebrew installer. Did you use the Tigerbrew installer instead?

**Comment by bsdforge** [comment]
Hello Mike, and thank you for the reply.
Dunno. I used the instructions on brew.sh:
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
It doesn't appear to be version specific, but have no idea "what's under the hood" ;-)
Thanks again, for taking the time to reply!

--Chris

**Comment by MikeMcQuaid** [comment]
@bsdforge Thanks. I'll try to reproduce on a 10.6 VM in future.

**Comment by MikeMcQuaid** [comment]
@bsdforge That will be fixed in https://github.com/Homebrew/install/pull/76

**Comment by bsdforge** [comment]
Thanks! :-)
