### ISSUE TITLE
HOMEBREW_PREFIX set incorrectly on default installation script

### ISSUE THREAD

**Issue by thandy1212** [Homebrew/homebrew-core#5675]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

My Issue is concerning the default installation script at http://brew.sh/index.html. Whenever I use it to install homebrew after uninstalling it, it sets the HOMEBREW_PREFIX variable to usr/local/homebrew as opposed to usr/local 

https://gist.github.com/thandy1212/08be1820bcc6bc7ac1e04ae164f95a7c

**Comment by chdiza** [comment]
/usr/local/homebrew is the new default location.  It's supposed to go there now.

**Comment by chdiza** [comment]
Ahh, never mind, I'm an idiot and can't read :)

**Comment by thandy1212** [comment]
It'd make sense if it were the new default location and I'm fine with that solution that just means there is a bug with brew doctor since it still gives a warning saying "usr/local" should be the default value for HOMEBREW_PREFIX

**Comment by ilovezfs** [comment]
@thandy1212 HOMEBREW_PREFIX default is still /usr/local. HOMEBREW_REPOSITORY is the one that has changed to /usr/local/Homebrew as the new default.

**Comment by ilovezfs** [comment]
@thandy1212 in any case, we're going to need more information (preferably Terminal transcripts) about what you're doing because https://github.com/Homebrew/install/blob/master/install#L5-L6 freezes those variables at the correct values.

**Comment by ilovezfs** [comment]
Please let us know if this is still happening for you.

**Comment by thandy1212** [comment]
Hi sorry for forgetting to get back to this. I think I managed to fix this issue by manually setting HOME_PREFIX to /usr/local in my .bash_profile file as an environment variable for my shell. 


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: ilovezfs <notifications@github.com> Date: 10/20/16  9:43 PM  (GMT-05:00) To: Homebrew/homebrew-core <homebrew-core@noreply.github.com> Cc: thandy1212 <thandy1212@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Homebrew/homebrew-core] HOMEBREW_PREFIX set incorrectly on
  default installation script (#5675) 
Please let us know if this is still happening for you. 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Homebrew/homebrew-core","title":"Homebrew/homebrew-core","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Homebrew/homebrew-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ilovezfs in #5675: Please let us know if this is still happening for you. "}],"action":{"name":"View Issue","url":"https://github.com/Homebrew/homebrew-core/issues/5675#issuecomment-255273113"}}}
