### ISSUE TITLE
brew commands not working

### ISSUE THREAD

**Issue by webpick77** [Homebrew/homebrew-core#5676]
Brew installed successfully on Sierra 10.12 with Xcode 8, but very Brew command (except help) results in failure with the following text:

brew search
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
fatal: https://github.com/Homebrew/homebrew-core/info/refs download error - The requested URL returned error: 403 Forbidden
Error: Failure while executing: git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --depth=1 -q
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q

thanks

**Comment by MikeMcQuaid** [comment]
What does `brew config`, `which git` and `git --version` show?

**Comment by webpick77** [comment]
Mike
Thanks for offering to help.

brew config
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
error: invalid key: --file=/usr/local/Homebrew/.git/config
HOMEBREW_VERSION: >1.0.0 (no git repository)
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap: N/A
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 1.6.0.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: N/A

brad$ which git
/usr/local/bin/git

brad$ git --version
git version 1.6.0.2

**Comment by MikeMcQuaid** [comment]
> Git: 1.6.0.2 => /usr/local/bin/git

You should delete this with `rm /usr/local/bin/git` as it's very old and has caused problems with your installation.

**Comment by webpick77** [comment]
Suhweet. That worked.
Thanks Mike.
