### ISSUE TITLE
Package nauty should install headers in /usr/local/include/nauty

### ISSUE THREAD

**Issue by mkoeppe** [Homebrew/homebrew-core#56908]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Using nauty (`/usr/local/lib/libnauty.a`) as a callable library.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ ls -l /usr/local/include/*nauty*
lrwxr-xr-x  1 mkoeppe  staff  37 Feb 27 12:00 /usr/local/include/nauty.h -> ../Cellar/nauty/26r12/include/nauty.h
$ ls -l /usr/local/Cellar/nauty/26r12/include/*
-rw-r--r--  1 mkoeppe  staff  53468 Oct 14  2019 /usr/local/Cellar/nauty/26r12/include/nauty.h
$ ls -l /usr/local/lib/libnauty.*
lrwxr-xr-x  1 mkoeppe  staff  36 Feb 27 12:00 /usr/local/lib/libnauty.a -> ../Cellar/nauty/26r12/lib/libnauty.a
  </pre>
</details>

## What you expected to happen

1. The header file `nauty.h` should be installed as `/usr/local/nauty/nauty.h`, to match the installation scheme of major Linux distributions (debian, fedora, ...) and Conda-forge; and other nauty headers should be installed in `/usr/local/nauty/` as well. See https://github.com/Normaliz/Normaliz/issues/332 

2. A shared library should be installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

<pre>
$ brew install nauty
</pre>

**Comment by Bo98** [comment]
> A shared library should be installed.

Upstream actually don't support or provide a shared library. The only reason it exists in Debian is because they _heavily_ patch the build scripts.

**Comment by mkoeppe** [comment]
That's correct.

**Comment by SMillerDev** [comment]
Homebrew doesn't do patches unless software doesn't build without them and even then we require they be accepted upstream first.

Please file a pull request or an issue with the nauty developers and then homebrew can ship the library too.

**Comment by mkoeppe** [comment]
OK, what about the issue regarding the header file installation.

**Comment by SMillerDev** [comment]
If upstream agrees it should be shipping header files we'll automatically start shipping them too on the next release

**Comment by jonchang** [comment]
Hopefully fixed in https://github.com/Homebrew/homebrew-core/commit/d18e1d90c1fd561e9ba85231253594954a8c1d45

**Comment by mkoeppe** [comment]
Thank you.
