### ISSUE TITLE
brew install -- possible security issue

### ISSUE THREAD

**Issue by lovelydreamer** [Homebrew/homebrew-core#5700]
env: 
re-Install of brew and updated, and clean install of OS X 1 week ago. Xcode 7.3.1.

issue: 
one of my packages through brew might be compromised. I was having issues downloading dependencies (I previously installed NodeJS through the website, big mistake to forget about brew!). It took a few tries to clean out all the files, hence the `--overwrite` below.

details: 
Partway through `brew install npm` (or possibly `npm install node`) I was prompted for root access. It failed my password three times but was accurate. Wanting more information, I did a search:
 `cat /private/var/log/system.log | grep "password"  `
 
```
Oct  8 14:53:27 christinas-MacBook-Pro CoreServicesUIAgent[11474]: error -1 while removing quarantine data on path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/share/man/man3/des_read_2passwords.3ssl
Oct  8 14:53:27 christinas-MacBook-Pro CoreServicesUIAgent[11474]: error -1 while removing quarantine data on path /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/share/man/man3/des_read_password.3ssl
Oct  8 15:43:53 christinas-MacBook-Pro sudo[35678]: christina : 3 incorrect password attempts ; TTY=ttys000 ; PWD=/Users/christina ; USER=root ; COMMAND=/usr/local/bin/brew link --overwrite node
```

What concerns me is the occurrence of the word password above in Xcode. Is this normal?

**Comment by MikeMcQuaid** [comment]
Homebrew will never intentionally prompt for your root password, just FYI.

> Partway through brew install npm (or possibly npm install node) I was prompted for root access.

Can you try again and check which one? We control the prior but not the latter. You can run `sudo -k` before-hand to ensure that it can't use an existing `sudo` session to authenticate with no password.

**Comment by lovelydreamer** [comment]
I removed and tried both this morning and didn't get the prompt again. I noticed last night's logs have installation activity.  
`cat /private/var/log/install.log | open -f`
So I'm about to wipe the computer and start again. There's no use digging around trying to trace something like this! When I reinstall fresh, I'll let you know which package it is.

**Comment by MikeMcQuaid** [comment]
Thanks! Will close for now but happy to reopen later.
