### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hktalent** [Homebrew/homebrew-core#5701]
mac os X 10.12

```
$ brew install xctool -v
see error.txt file
[error.txt](https://github.com/Homebrew/homebrew-core/files/518048/error.txt)

```

**Comment by MikeMcQuaid** [comment]
From your original output.

> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by zmwangx** [comment]
Known issue, https://github.com/facebook/xctool/issues/716. Upstream promised a release, but haven't done so a week later. There's nothing we can do. You can `brew install xctool --HEAD` for now.

Already tracked in #5488.
