### ISSUE TITLE
Question on Tactic: When Possible to Compile for Apple Silicon, Use `pour_bottle?` in Particular Formula to Avoid Bottle Install?

### ISSUE THREAD

**Issue by jdhealy** [Homebrew/homebrew-core#57100]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  - Not applicable

_Less facing a problem and more running a tactic by y'all to see if it’s viable for `homebrew-core`…_

## What you were trying to do (and why)

> Apple Silicon Mac porting tip #⁣14: If you're running in Rosetta and you fork/exec/posix_spawn the OS will *prefer* to launch the child in Rosetta, too (if the target only has an arm64 slice, then it will run natively). If you want to apply your own preference, use ...

〜 https://twitter.com/kubamracek/status/1275862876931022848

Looking to avoid the above (important to our users) — and knowing we can query Xcode on whether it can compile for `arm64` `macosx` — I'd like to add a `def pour_bottle?` to my formula to skip bottle installing when Xcode can build a universal `arm64`/x86_64` target.

## What happened (include command output)

Wrote it, and it works:

```ruby
  def pour_bottle?
    awk_query = <<-'EOD'
      /usr/bin/awk '
        BEGIN {
          RS = "\0"
          split("", match_array, ":")
          first_query = "^.*if defined[^\w]__arm64__[^\w]$"
          second_query = "^[[:space:]]*typedef[[:space:]]+u_int64_t[[:space:]]"
        } {
          RS = "\n"
          while(( getline line<$0) > 0 ) {
            if ( line ~ first_query ) { match_array[0] = line; continue }
            if ( length(match_array[0]) > 0 && line ~ second_query ) {
              printf "arm64"; exit 0
            } else { split("", match_array, ":") }
          }
          RS = "\0"
        }
      '
    EOD
    find_source_path_components = "Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
    find_command = "/usr/bin/find -P #{Shellwords.escape(MacOS::Xcode.prefix)}/#{find_source_path_components} -ipath '*arm*/types.h' -print0"

    %x{#{find_command} | #{awk_query}} != "arm64"
  end
```

So, to put an example: under [Xcode 12A6159](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes) bottles install as expected; with [Xcode 12A8158a](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-for-macos-universal-apps-beta-release-notes) (as it correctly delineates from the `def pour_bottle?`), the `def install` compilation occurs (Xcode 12A8158a runs on Catalina on Intel, and on Big Sur on both Intel and Apple Silicon) and the resulting binary could be (say) Migration-Assistant–moved onto an Apple Silicon Mac and avoid the Rosetta-derived `posix_spawn` behavior described above.

## What you expected to happen

Looking for opinions on whether that `def pour_bottle?` code (and the tactic behind it) fits the general homebrew-core criteria, and would be viable.

Would love to get people’s thoughts…

## Step-by-step reproduction instructions (by running `brew install` commands)

N/A

**Comment by SMillerDev** [comment]
I really don't get what you're trying to accomplish here, or even what "your formula" is since we don't have a concept of dedicated maintainers. But if you want to change bottle behavior you should make a pull request for Homebrew/brew.

**Comment by jdhealy** [comment]
Oh, probably missed the mark on explaining this then — not sure this is across-the-board desirable (so, not aiming to land this on Homebrew/brew).

It's desirable for a particular program ( [`Formula/carthage.rb`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/carthage.rb)) which makes a lot of `posix_spawn` calls. If a Intel-only bottle were to be installed, under-Rosetta `posix_spawn` subprocesses would — even if a Apple-Silicon–supporting arm64 slice of the target subprocess is available — incur the performance difference of Rosetta.

I'd wager Carthage users would rather have recompilation of Carthage upon `brew install` (if an Xcode that can build a Intel+Apple·Silicon target is `xcode-select`-ed).

**Comment by SMillerDev** [comment]
Wouldn't this be mitigated by having specific bottles for ARM? Because the code for this already exists.

**Comment by jdhealy** [comment]
Does the current homebrew bottling system (as of today, no expectation that it would) create those ARM-only macosx bottles?

**Comment by SMillerDev** [comment]
No, because homebrew doesn't run on arm yet due to missing symbols errors in the ruby version shipped in the first beta.
