### ISSUE TITLE
Error in pandoc-include-code.rb preventing installing brew on new system

### ISSUE THREAD

**Issue by ladislas** [Homebrew/homebrew-core#57245]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was running the install script with:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

## What happened (include command output)

```console
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 741442 (delta 14), reused 16 (delta 8), pack-reused 741416
Receiving objects: 100% (741442/741442), 298.58 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (490908/490908), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/pandoc-include-code.rb
pandoc-include-code: undefined method `license' for #<Class:0x00007fbdbe3ad300>
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.
```

The issue comes from here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pandoc-include-code.rb#L13

## What you expected to happen

The installation to work.

## Step-by-step reproduction instructions (by running `brew install` commands)

Run the install script on a new system.

**Comment by SarahH12099** [comment]
Yeah, same issue here, just set up macOS Catalina and got that issue, thank you for fixing it, hopefully they will merge it for everybody to get it.

**Comment by carlioth** [comment]
I'm also getting this. All new installs failing on mac. Noticed that the build catched it when merged to master: https://github.com/Homebrew/homebrew-core/actions/runs/154495678
