### ISSUE TITLE
GCC 10.1 failures

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-core#57337]
Failures are:

- muparser, needs a revision bump
- mlpack, I don't understand it right now
- x264, needs a revision bump (for 10.13 only)

Test failure:

- adios2
- ncview, only on 10.14… random fluke?

Pre-existing audit failures:
- hdf5, hdf5@1.10, hdf5@1.8
- netcdf, pnetcdf
- pgplot
- plplot

_Originally posted by @fxcoudert in https://github.com/Homebrew/homebrew-core/pull/54364#issuecomment-653447153_

**Comment by MikeMcQuaid** [comment]
(thanks for opening this)

**Comment by fxcoudert** [comment]
- I can't reproduce `ncview` failure, it works fine now
- `adios2` is an upstream issue, reported here: https://github.com/ofiwg/libfabric/issues/5898
