### ISSUE TITLE
rename heroku-toolbelt to heroku

### ISSUE THREAD

**Issue by dickeyxxx** [Homebrew/homebrew-core#574]
We're in the process of changing the branding a bit of the Heroku CLI and dropping the Toolbelt brand. Toolbelt originally implied that it included Git and Foreman, but now it does not include Git and Foreman has moved into the CLI as `heroku local`.

There is already an alias so that people can install `heroku` instead of `heroku-toolbelt`. Can we rename the formula and reverse the alias? Will this break updates for people?

**Comment by mikemcquaid** [comment]
Yeh, we can rename formulae now so 👍 to this.

**Comment by dickeyxxx** [comment]
great!

**Comment by mikemcquaid** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/issues/880
