### ISSUE TITLE
Needlessly building ":build" deps for formulas that are already installed

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#5740]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I noticed this problem with `diff-pdf`, but it's probably because of a bug in `brew`'s deciding which deps need to be installed.

`brew install --build-from-source diff-pdf` will incorrectly try to build and install `:build` deps for `openjpeg`, even when `openjpeg` has already been poured from a bottle.

Reproduce: Pour the bottles for `diff-pdf`'s dependencies: `brew install wxmac cairo poppler`  Notice that `openjpeg` is now installed, since it's a recursive dep.  Other recursive deps are poured too.

Now, do `brew install --build-from-source diff-pdf`.  What should happen is that `diff-pdf` starts being built forthwith (all of its deps are already installed).  What actually happens is that `brew` starts trying to build `cmake`, `doxygen`, and `sphinx-doc`, because those are deps of `openjpeg`.  But, those are *:build* deps of `openjpeg`, and `openjpeg` has already been poured and is therefore already built.

My *guess* is that `brew` is simply failing to filter out the ":build" deps from its list of things it needs to do before it can build `diff-pdf`.  Even though `diff-pdf` is going to be built rather than poured, that doesn't mean that all of its deps need to be :built.

**Comment by ilovezfs** [comment]
You could try adding a check for whether the dependent is already installed and prune in that case too perhaps here:

https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L365-L366

**Comment by chdiza** [comment]
> You could try adding a check for whether the dependency is already installed and prune in that case too perhaps here:

I have no idea how to do this.  I'm not qualified to make a PR or give an accurate diagnosis.

**Comment by MikeMcQuaid** [comment]
Mind resubmitting to homebrew/brew instead?

**Comment by chdiza** [comment]
Done :)

**Comment by MikeMcQuaid** [comment]
@chdiza Thanks!
