### ISSUE TITLE
Gstreamer outdated --HEAD formula

### ISSUE THREAD

**Issue by jaguarondi** [Homebrew/homebrew-core#57430]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I installed gstreamer and plugins and ran into the exact same issue as #52007. I tried to build --HEAD to get more insight about the problem and found out that GStreamer removed the autogen.sh script. Build now use meson/ninja instead: [Building from source using meson](https://gstreamer.freedesktop.org/documentation/installing/building-from-source-using-meson.html?gi-language=c)

## What happened (include command output)

```
⇒  brew install gstreamer --HEAD
==> Cloning https://anongit.freedesktop.org/git/gstreamer/gstreamer.git
Updating /Users/davidbourgeois/Library/Caches/Homebrew/gstreamer--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at eea1ac156 ptp: Add GNU Hurd to the list of supported platforms and fix the Solaris name
==> ./autogen.sh
Last 15 lines from /Users/davidbourgeois/Library/Logs/Homebrew/gstreamer/01.autogen.sh:
2020-07-04 11:35:20 +0200

./autogen.sh


READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```

Likely useless but here's the gist-log: https://gist.github.com/e82be08d5d744ef4ef4e05f619f7837b

**Comment by glyng1** [comment]
Dear Homebrew/homebrew-core,

I am looking for kind supoort and new to work and tools.

Reaching out for kind assistance.

Kind Regards,
Glyn

**Comment by jonchang** [comment]
> Please create pull requests instead of asking for help on Homebrew's GitHub, Discourse, Twitter or IRC.

Please open a pull request to fix the build system migration for HEAD builds.
