### ISSUE TITLE
Android NDK version is incorrectly auto-detected by formula

### ISSUE THREAD

**Issue by gordonmcshane** [Homebrew/homebrew-core#5746]
### Bug reports:

Formula detects architecture (x86_64) as version (86.64) instead of actual version (e.g. r13b)
It will probably require the addition of a version entry.

My attempt at a fix:
PR #5747

**Comment by ilovezfs** [comment]
I think we also need a `version_scheme` bump here since
```
irb(main):001:0> Version.new("r13") > Version.new("86.64")
=> false
```
so people will be stranded :(
