### ISSUE TITLE
emscripten formula should use "tot" (upstream) instead "fastcomp" 

### ISSUE THREAD

**Issue by MaxGraey** [Homebrew/homebrew-core#57480]
fastcomp deprecated and will be [removed soon](https://github.com/emscripten-core/emscripten/issues/11319)

**Comment by SMillerDev** [comment]
Please make a pull request to change these, you are probably the best person to figure out what needs to change and homebrew doesn't accept change requests as issues.

**Comment by MaxGraey** [comment]
I'll try but I'm not familiar with homebrew infrastructure
