### ISSUE TITLE
"brew install -s ppl" fails - 401 Unauthorized

### ISSUE THREAD

**Issue by mkoeppe** [Homebrew/homebrew-core#57499]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew reinstall -s ppl

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading http://www.cs.unipr.it/git/gitweb.cgi?p=ppl/ppl.git;a=commitdiff_plain;h=c39f6a07b51f89e365b05ba4147aa2aa448febd7
==> Downloading from https://www.cs.unipr.it/git/gitweb.cgi?p=ppl/ppl.git;a=commitdiff_plain;h=c39f6a07b51f89e365b05ba4147aa2aa448febd7
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "ppl--patch"
Download failed: http://www.cs.unipr.it/git/gitweb.cgi?p=ppl/ppl.git;a=commitdiff_plain;h=c39f6a07b51f89e365b05ba4147aa2aa448febd7
  </pre>
</details>

## What you expected to happen

a clean installation

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install -s ppl || brew reinstall -s ppl

**Comment by chenrui333** [comment]
@mkoeppe thanks for the bug reporting, I filed a PR to fix the build from source code issue.

**Comment by chenrui333** [comment]
@mkoeppe, we merged the fix, let us know if it is still an issue.

**Comment by mkoeppe** [comment]
Thanks! I can confirm that it works now.
