### ISSUE TITLE
Installing uwsgi with python3 still uses python2

### ISSUE THREAD

**Issue by maneyko** [Homebrew/homebrew-core#5751]
After doing a clean install

``` bash
brew uninstall --force uwsgi
brew install uwsgi --with-python --with-python3
```

and using a test flask app

``` python
# hello.py

from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return 'Hello world!'
```

uwsgi **still** uses python2 even when specifying python3 as a command line argument

``` bash
uwsgi --plugin python3 --http-socket :8080 --module hello --callable app
```

The following patch fixed the problem on my machine, it seems that running python2 to install the python3 plugin [doesn't do anything](https://stackoverflow.com/questions/16264213/uwsgi-python3-plugin-doesnt-work).

``` patch
diff --git a/Formula/uwsgi.rb b/Formula/uwsgi.rb
index 4e191d7..5632032 100644
--- a/Formula/uwsgi.rb
+++ b/Formula/uwsgi.rb
@@ -124,7 +124,7 @@ class Uwsgi < Formula
     python_versions = ["python", "python2"]
     python_versions << "python3" if build.with? "python3"
     python_versions.each do |v|
-      system "python", "uwsgiconfig.py", "--verbose", "--plugin", "plugins/python", "brew", v
+      system v, "uwsgiconfig.py", "--verbose", "--plugin", "plugins/python", "brew", v
     end

     bin.install "uwsgi"
```

**Comment by dunn** [comment]
Would you like to try opening a PR? Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by ilovezfs** [comment]
Happy to accept a PR for this as @dunn said.
