### ISSUE TITLE
404 Not Found when trying to install `circleci` 0.1.8599

### ISSUE THREAD

**Issue by globau** [Homebrew/homebrew-core#57527]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Steps to reproduce

```
glob ~$ brew update && brew install circleci
Already up-to-date.
==> Downloading https://homebrew.bintray.com/bottles/circleci-0.1.8599.catalina.bottle.1.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "circleci"
Download failed: https://homebrew.bintray.com/bottles/circleci-0.1.8599.catalina.bottle.1.tar.gz
```

The bottle's URL was valid at some stage - from another system:

```
~$ brew info circleci
circleci: stable 0.1.8599 (bottled)
Enables you to reproduce the CircleCI environment locally
https://circleci.com/docs/2.0/local-cli/
/usr/local/Cellar/circleci/0.1.8599 (5 files, 13.9MB) *
  Poured from bottle on 2020-07-05 at 05:27:27
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/circleci.rb
==> Dependencies
Build: go ✘
```

**Comment by jonchang** [comment]
Thanks for the report. Please run `brew update` and try again.
