### ISSUE TITLE
Auto-complete on awscli formula broken

### ISSUE THREAD

**Issue by amancevice** [Homebrew/homebrew-core#57541]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install the `awscli` formula and use tab completion.

## What happened (include command output)

The formula installed cleanly, but tab completion fails with the error references in this github issue: https://github.com/aws/aws-cli/issues/5338

<details>
  <summary>Command output</summary>
  <pre>

  Traceback (most recent call last):
  File "/usr/local/bin/aws_completer", line 36, in <module>
    main()
  File "/usr/local/bin/aws_completer", line 28, in main
    autocomplete(command_line, command_index)
  File "/usr/local/Cellar/awscli/2.0.28/libexec/lib/python3.8/site-packages/awscli/autocomplete/main.py", line 61, in autocomplete
    results = completer.autocomplete(command_line, position)
  File "/usr/local/Cellar/awscli/2.0.28/libexec/lib/python3.8/site-packages/awscli/autocomplete/completer.py", line 42, in autocomplete
    parsed = self._parser.parse(command_line, index)
  File "/usr/local/Cellar/awscli/2.0.28/libexec/lib/python3.8/site-packages/awscli/autocomplete/parser.py", line 145, in parse
    global_args = self._index.arg_names(lineage=[], command_name='aws')
  File "/usr/local/Cellar/awscli/2.0.28/libexec/lib/python3.8/site-packages/awscli/autocomplete/local/model.py", line 104, in arg_names
    results = db.execute(self._ARG_NAME_QUERY,
  File "/usr/local/Cellar/awscli/2.0.28/libexec/lib/python3.8/site-packages/awscli/autocomplete/db.py", line 33, in execute
    return self._connection.execute(query, kwargs)
sqlite3.OperationalError: no such table: param_table

  </pre>
</details>

## What you expected to happen

tab completion should work.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install awscli

`brew config` output:

```
HOMEBREW_VERSION: 2.4.3-91-gf72328d
ORIGIN: https://github.com/Homebrew/brew
HEAD: f72328d9c048c28d3fb6b0354ad4f76da887c72e
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a82afbb6068a93804b204751a61d6e2ecfccdaf9
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_EDITOR: vi
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: 11.5
```

`brew doctor` output:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/amancevice/.pyenv/shims/python3.7-config
  /Users/amancevice/.pyenv/shims/python3.7m-config
  /Users/amancevice/.pyenv/shims/python-config
  /Users/amancevice/.pyenv/shims/python3-config
  /Users/amancevice/.pyenv/shims/python3.8-config
```

**Comment by jonchang** [comment]
Looks like we need to run [this script](https://github.com/aws/aws-cli/blob/v2/scripts/gen-ac-index) at some point during install. Could you open a pull request (and possibly improve the `test do` block to ensure that we catch this issue going forward)? Thanks!

**Comment by amancevice** [comment]
Thanks, @jonchang — pull request created #57547

**Comment by amancevice** [comment]
resolved
