### ISSUE TITLE
Undesired behavior of using brewed openjdk when JAVA_HOME is not set

### ISSUE THREAD

**Issue by edwardxia** [Homebrew/homebrew-core#57589]
Currently, I found the following pattern is used on many formulas in java eco system ([search results](https://github.com/Homebrew/homebrew-core/search?q=%3AJAVA_HOME+%3D%3E+%22%24%7BJAVA_HOME%3A-%23%7BFormula%5B%22openjdk%22%5D.opt_prefix%7D%7D%22&unscoped_q=%3AJAVA_HOME+%3D%3E+%22%24%7BJAVA_HOME%3A-%23%7BFormula%5B%22openjdk%22%5D.opt_prefix%7D%7D%22)):

``` rb
      (bin/basename).write_env_script file, :JAVA_HOME => "${JAVA_HOME:-#{Formula["openjdk"].opt_prefix}}"
```

What this does is create a wrapper like this one for maven:

``` sh
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/usr/local/opt/openjdk}" exec "/usr/local/Cellar/maven/3.6.3_1/libexec/bin/mvn"  "$@"
```

What happens here is that all java based commands using this wrapper would use brewed openjdk as long as JAVA_HOME environment variable is not set, and this generates some unexpected behaviors. One example is that in a corporate setting with in house Artifactory for maven that uses in house signed CA certificate. The in house CA certificate is bundled with in house JDK keystore, but not with brewed openjdk. Therefore, when running maven with brew openjdk, it would result in certificate chain error.

---

I understand that the motivation behind this change was probably to make sure a compatible JDK version is always used so that we won't have version compatibility problem. This behavior is sort of inline with how we dealt with formulas that linked to brewed openssl. However, I don't feel that it's the right solution for java eco system.

IMO, for java based application, the system default java should be selected when JAVA_HOME is not set.

I would recommend that we revert this pattern back to where we do not hardwire with brewed openjdk.

Of course another way to solve it is to add `export JAVA_HOME="$(/usr/libexec/java_home)"` to `~/.bashrc` or alike. If we're not going to change this wrapper behavior of using openjdk, at least we should add caveats in these formulas to warn user about JAVA_HOME and JDK.

**Comment by jonchang** [comment]
We won't be making this change as it would require users to install additional software before running any Java formulae. If Java were installed by default on macOS it might be a different story, but users generally expect running `brew install maven && mvn` to work out of the box. See [this document](https://docs.brew.sh/Building-Against-Non-Homebrew-Dependencies) for more historical context.

**Comment by jonchang** [comment]
Please always use the issue template.

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
