### ISSUE TITLE
How to handle g_get_user_config_dir?

### ISSUE THREAD

**Issue by MikeLund** [Homebrew/homebrew-core#5762]
Hi,

I am trying to update the bottle for apt-dater to the most recent version. The problem I am running into is that the code uses [g_get_user_config_dir](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-config-dir), which relates to XDG_CONFIG_HOME or something.

The problem is, it will check in ~/.config/apt-dater for program configs, because that's what g_get_user_config_dir returns. But the configs are already existing in /usr/local/etc/apt-dater/ (which links to ../../Cellar/apt-dater/1.0.3/etc/apt-dater/).

How is the best way to handle this? It seems like there must be a normal way to handle this (other than doing stuff with the code), because this is a semi-common issue where programs like to throw stuff in ~/.config, but still has config elsewhere (in the --prefix).

Thanks for any advise!

**Comment by MikeMcQuaid** [comment]
We override `$HOME` during the build so it doesn't matter if it checks there during installation. At runtime it actively should check in `~/.config` too.
