### ISSUE TITLE
Formula nim.rb is missing source for nimsuggest

### ISSUE THREAD

**Issue by ericem** [Homebrew/homebrew-core#57620]
- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## brew gist-logs nim

```
Error: No logs.
```

## What you were trying to do (and why)

I was trying to install the nimlsp utility (a language server plugin for nim) using the nimble package manger for nim. When building nimlsp, nimble needs the nimsuggest source, which is included with nim during a manual installation. (Note: nimsuggest can be used as both a library and a binary) The nim.rb  Formula does not bundle the nimsuggest source and only bundles the nimsuggest binary. 

## What happened (include command output)

List nimsuggest directory:
```
ls /usr/local/Cellar/nim/1.2.4/nim/nimsuggest
```

The nimsuggest directory is missing:
```
ls: /usr/local/Cellar/nim/1.2.4/nim/nimsuggest: No such file or directory

```

## What you expected to happen

List nimsuggest directory:```
ls /usr/local/Cellar/nim/1.2.4/nim/nimsuggest
```

The nimsuggest source is included:
```
crashtester.nim    nimsuggest.nim     nimsuggest.nim.cfg nimsuggest.nimble  sexp.nim           tester.nim         test
```

The nimsuggest source comes in the nim source tarball and should be installed with the nim Formula:

```
wget https://nim-lang.org/download/nim-1.2.4.tar.xz
tar xvf nim-1.2.4.tar.xz
ls nim-1.2.4/nimsuggest/

crashtester.nim    nimsuggest.nim     nimsuggest.nim.cfg nimsuggest.nimble  sexp.nim           tester.nim         tests
```

## Step-by-step reproduction instructions (by running `brew install` commands)

- brew install nim
- ls /usr/local/Cellar/nim/1.2.4/nim/nimsuggest

**Comment by gromgit** [comment]
No distro I've seen distributes Nim sources in their binary packages, and since they're not needed for Nim to work, this is unlikely to happen. Upstream already acknowledges this and [offers a workaround in their documentation](https://github.com/PMunch/nimlsp#installing-nimlsp):

> However if you have installed nimlsp in a different way you might run into issues where it can't find certain files during compilation/running. To fix this you need to grab a copy of Nim sources and then point nimlsp at them on compile-time by using -d:explicitSourcePath=PATH, where PATH is where you have your Nim sources.

Alternatively, you could create a new `nimlsp` formula that builds the LSP software, and imports the Nim source tarball as a legitimate `resource`. This can then be version-bumped along with the main `nim` formula in the usual way.

**Comment by dtrodrigues** [comment]
@ericem can this issue be closed?
