### ISSUE TITLE
batik: Unable to access jarfile

### ISSUE THREAD

**Issue by alexreg** [Homebrew/homebrew-core#57695]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Simply run the `batik` program (from the *batik* formula). For example,

```sh
batik -h
```

## What happened (include command output)

I got an error, "unable to access jarfile". Indeed, the file `/usr/local/Cellar/batik/1.13/libexec/batik-1.13.jar` does not exist.

<details>
  <summary>Command output</summary>
  <pre>

    Error: Unable to access jarfile /usr/local/Cellar/batik/1.13/libexec/batik-1.13.jar

  </pre>
</details>

The contents of the `/usr/local/Cellar/batik/1.13/libexec/` directory is:

```
batik-rasterizer-1.13.jar
batik-slideshow-1.13.jar
batik-squiggle-1.13.jar
batik-svgpp-1.13.jar
batik-ttf2svg-1.13.jar
lib
```

[Here](https://gist.github.com/4f5065f31426c227e4268c72c3844153) are the Gist logs for the *batik* formula.

## What you expected to happen

The help output should have been successfully printed.

## Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew install batik
batik -h
```

**Comment by gromgit** [comment]
I've submitted a PR that fixes the core installation issue, but that means `batik -h` still won't work, since there's no `batik` app JAR in the release. If you're sure that JAR should exist, please inform upstream about their packaging error.

**Comment by alexreg** [comment]
Thanks. (I am in fact not at all sure whether it should exist; I just started using batik.)
