### ISSUE TITLE
ansible@2.8 depends on python@3.8 but should on python@3.7

### ISSUE THREAD

**Issue by arvenil** [Homebrew/homebrew-core#57719]
I need ansible@2.8 but IMHO that formula has a bug making it impossible to work.
https://github.com/Homebrew/homebrew-core/blob/99decbea6523c2c47d5bd15e1b7398eb142eed84/Formula/ansible%402.8.rb#L22-L24

The problem with python version is even stated in the comment. The ansible 2.8 should be paired with max python 3.7, but right now it depends on `python` formula which now points to `3.8`. I think the issue happen because previously `python` formula was pointing to `3.7` - which was correct for ansible 2.8, but now `python` formula points to `3.8` so I guess ansible@2.8 formula should have dependency on `python@3.7` formula instead of `python`.

Is there any easy and quick way to hot modify this formula to get it properly installed on my local machine?

**Comment by SMillerDev** [comment]
The easiest way is to make a pull request that points this to `python@3.7`.

**Comment by Rylan12** [comment]
> Is there any easy and quick way to hot modify this formula to get it properly installed on my local machine?

If it's a local issue where it doesn't make sense to have a PR, you can always edit formulae locally and build it from source by running `brew install -s <foo>`.

(This is also helpful if you're waiting for a PR to be merged but still need the updated version locally)

**Comment by iMichka** [comment]
Fixed by #57720
