### ISSUE TITLE
Formula python gone and issue with python@3.8

### ISSUE THREAD

**Issue by cbrnr** [Homebrew/homebrew-core#57712]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  ```Error: Not Found```
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
HOMEBREW_VERSION: 2.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: f455fe28a7a47b51af090b308e95535d6cf0a423
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3e559ee9667cd55a21aa4bfaa50074cea090b4fb
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 11.5.0.0.1.1588476445
Xcode: N/A
```

After a `brew update`, my previously installed `python@3.8` was updated and now whenever I start the interpreter I get the following error:

```
Error processing line 1 of /usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.8/3.8.3_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

Furthermore, I then thought that maybe this happened because the `python` formula would now ship Python 3.8 - but apparently there is no `python` formula anymore, only `python@3.8`.

This error might also be the reason why VS Code cannot auto-detect this Python interpreter anymore.

**Comment by Bo98** [comment]
> apparently there is no `python` formula anymore, only `python@3.8`.

`python` is now an alias. So `brew install python` will install `python@3.8`. Things like `/usr/local/opt/python` will symlink to `python@3.8`. `python@3.7` is available should you need it.

The error you have is because of an old/broken matplotlib file you have: `/usr/local/lib/python3.8/site-packages/matplotlib-nspkg.pth`. Deleting it may fix your issue.

**Comment by cbrnr** [comment]
Thanks, this solved the problem.
