### ISSUE TITLE
openshift-cli v1.3.0 oadm is oc binary

### ISSUE THREAD

**Issue by danni** [Homebrew/homebrew-core#5777]
The openshift-cli 1.3.0 formula has the oadm command as a symlink to the oc binary, but it doesn't seem to be working. They've now added an 'oc adm' command. There's nothing in the changelog indicating that the oadm symlink should have stopped working though.

Could potentially replace oadm with a script that does `exec oc adm $@`?

**Comment by MikeMcQuaid** [comment]
> Could potentially replace oadm with a script that does exec oc adm $@?

@danni Good idea; either that or just delete the existing symlink. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by MikeMcQuaid** [comment]
Closing due to no response.
