### ISSUE TITLE
python@3.8: easy_install-3.8 fails because it requires setuptools==46.0.0

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew-core#57782]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I linked an already installed `python@3.8` because `brew doctor` said `python@3.8` wasn't linked.

I got an error when I ran `easy_install-3.8 --version`.  For some reason, `easy_install-3.8` requires `setuptools==46.0.0`, but I have a newer version of `setuptools` installed.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ brew doctor 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.8

$ brew link python@3.8 
Linking /usr/local/Cellar/python@3.8/3.8.3_2... 
Error: Could not symlink bin/easy_install-3.8
Target /usr/local/bin/easy_install-3.8
already exists. You may want to remove it:
  rm '/usr/local/bin/easy_install-3.8'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.8

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.8

$ /usr/local/bin/easy_install-3.8 --version 
setuptools 49.1.0 from /usr/local/lib/python3.8/site-packages (Python 3.8)

$ more /usr/local/bin/easy_install-3.8 
#!/usr/local/opt/python@3.8/bin/python3.8
\# -\*- coding: utf-8 -\*-
import re
import sys
from setuptools.command.easy_install import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

$ brew link --overwrite python@3.8
Linking /usr/local/Cellar/python@3.8/3.8.3_2... 25 symlinks created

$ /usr/local/bin/easy_install-3.8 --version
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (setuptools 49.1.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('setuptools==46.0.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/easy_install-3.8", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3258, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3270, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools==46.0.0' distribution was not found and is required by the application

$ greadlink -f /usr/local/bin/easy_install-3.8 
/usr/local/Cellar/python@3.8/3.8.3_2/bin/easy_install-3.8

$ more /usr/local/Cellar/python@3.8/3.8.3_2/bin/easy_install-3.8
#!/usr/local/opt/python@3.8/bin/python3.8
\# EASY-INSTALL-ENTRY-SCRIPT: 'setuptools==46.0.0','console_scripts','easy_install-3.8'
__requires__ = 'setuptools==46.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('setuptools==46.0.0', 'console_scripts', 'easy_install-3.8')()
    )
  </pre>
</details>

## What you expected to happen
`/usr/local/bin/easy_install-3.8 --version` should output its version instead of errors, and it should not require `setuptools==46.0.0`.

## Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew install python@3.8` before the above commands.  I don't know if the `easy_install-3.8` file that existed before it was overwritten with a symlink will be created by the install, as I have no clue why that file existed in the first place.

## Output of `brew gist-logs python@3.8`

https://gist.github.com/00f0452e641a90f2c1e3df3077378079

**Comment by Bo98** [comment]
I can't reproduce this:

```
$ easy_install-3.8 --version
setuptools 46.0.0 from /usr/local/lib/python3.8/site-packages (Python 3.8)
```

What `setuptool` egg directories do you have under `/usr/local/lib/python3.8/site-packages/setuptools`?

**Comment by rgoldberg** [comment]
@Bo98 Thanks for checking.

I don't know much about Python or its packaging, including egg directories, so sorry if the following contains more directories than you want…

```
$ find /usr/local/lib/python3.8/site-packages/setuptools -type d 

/usr/local/lib/python3.8/site-packages/setuptools
/usr/local/lib/python3.8/site-packages/setuptools/_vendor
/usr/local/lib/python3.8/site-packages/setuptools/_vendor/packaging
/usr/local/lib/python3.8/site-packages/setuptools/_vendor/packaging/__pycache__
/usr/local/lib/python3.8/site-packages/setuptools/_vendor/__pycache__
/usr/local/lib/python3.8/site-packages/setuptools/__pycache__
/usr/local/lib/python3.8/site-packages/setuptools/command
/usr/local/lib/python3.8/site-packages/setuptools/command/__pycache__
/usr/local/lib/python3.8/site-packages/setuptools/extern
/usr/local/lib/python3.8/site-packages/setuptools/extern/__pycache__
/usr/local/lib/python3.8/site-packages/setuptools/_distutils
/usr/local/lib/python3.8/site-packages/setuptools/_distutils/__pycache__
/usr/local/lib/python3.8/site-packages/setuptools/_distutils/command
/usr/local/lib/python3.8/site-packages/setuptools/_distutils/command/__pycache__
```

**Comment by Bo98** [comment]
Does `brew postinstall python@3.8` help? That should reinstall setuptools, wheel and pip.

**Comment by rgoldberg** [comment]
Thanks, that fixed it.

It reverted setuptools & pip to older versions, so the `setuptools==46.0.0` requirement in the file referenced by the symlink `/usr/local/bin/easy_install-3.8` was met.  

I then upgraded both setuptools & pip to the latest versions.  This overwrote the `/usr/local/bin/easy_install-3.8` symlink with a new file (not a symlink) that didn't include the `setuptools==46.0.0` requirement.

The setuptools version requirement in `/usr/local/Cellar/python@3.8/3.8.3_2/bin/easy_install-3.8` should be handled differently.  Either:

- `setuptools==46.0.0` should be changed to a "greater than or equal to" requirement
- if some version older than 46.0.0 is detected, the script should offer to upgrade to 46.0.0
- if some version newer than 46.0.0 is detected, the script should offer to downgrade to 46.0.0, then reinstall the newer version (or the latest version, if it would be hard to revert back to the previously installed version)
