### ISSUE TITLE
Failed to reinstall/update graphviz

### ISSUE THREAD

**Issue by xning** [Homebrew/homebrew-core#5779]
Am I missing anything?

    bj:Homebrew ny$ brew reinstall graphviz
    ==> Reinstalling graphviz with --with-bindings
    ==> Using the sandbox
    ==> Downloading http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.38.0.tar.gz
    Already downloaded: /Users/nano/Library/Caches/Homebrew/graphviz-2.38.0.tar.gz
    ==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6a6a1a3/graphviz/patch-gvloadimage_gs.c.diff
    Already downloaded: /Users/nano/Library/Caches/Homebrew/graphviz--patch-bcc0758dd9e0ac17bd1cde63a55a613124814002b470ac4a7a0c421c83a253ab.diff
    ==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/ec8d133/graphviz/patch-project.pbxproj.diff
    Already downloaded: /Users/nano/Library/Caches/Homebrew/graphviz--patch-7c8d5c2fd475f07de4ca3a4340d722f472362615a369dd3f8524021306605684.diff
    ==> Patching
    ==> Applying patch-gvloadimage_gs.c.diff
    patching file plugin/gs/gvloadimage_gs.c
    ==> Applying patch-project.pbxproj.diff
    patching file macosx/graphviz.xcodeproj/project.pbxproj
    ==> ./configure --prefix=/usr/local/Cellar/graphviz/2.38.0_1 --without-qt --with-quartz --without-pangocairo --without-freetype2 --without-x --without-rsvg
    ==> make install
    Last 15 lines from /Users/nano/Library/Logs/Homebrew/graphviz/02.make:
    inline _LIBCPP_INLINE_VISIBILITY       char* strstr(      char* __s1, const char* __s2) {return ::strstr(__s1, __s2);}
                                                 ^
    /usr/include/string.h:89:7: note: previous declaration is here
    char    *strstr(const char *__big, const char *__little);
             ^
      CXX      libgv_java_la-gv_java.lo
      CXX      libgv_lua_la-gv_lua.lo
      CXX      libgv_perl_la-gv_perl.lo
    5 errors generated.
    make[4]: *** [libgv_R_la-gv_R.lo] Error 1
    make[4]: *** Waiting for unfinished jobs....
    make[3]: *** [install-recursive] Error 1
    make[2]: *** [install-recursive] Error 1
    make[1]: *** [install-recursive] Error 1
    make: *** [install] Error 2
    
    READ THIS: https://git.io/brew-troubleshooting
    If reporting this issue please do so at (not Homebrew/brew):
      https://github.com/Homebrew/homebrew-core/issues

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do

**Comment by xning** [comment]
Thanks.

**Comment by tpetry** [comment]
@xning How did you solve it? Have the exact same problem and the common troubleshooting hints do not work.
