### ISSUE TITLE
Install curl with same options as macOS builtin curl

### ISSUE THREAD

**Issue by rgoldberg** [Homebrew/homebrew-core#57795]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Can you install curl with the same options as the macOS builtin curl (/usr/bin/curl)?

That would allow users to use Homebrew curl for all the same cases as the macOS builtin, just with the newest version.

On my macOS 10.15.5 machine, the builtin curl has all of the installed features that the latest Homebrew curl has, but the builtin also has additional installed features.

Builtin curl is:

```bash
$ /usr/bin/curl --version
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

Whereas latest Homebrew curl is:

```bash
$ /usr/local/opt/curl/bin/curl --version
curl 7.71.1 (x86_64-apple-darwin19.5.0) libcurl/7.71.1 SecureTransport zlib/1.2.11
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```

## What you expected to happen

Homebrew curl should have the same options as the macOS builtin curl.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install curl
/usr/local/opt/curl/bin/curl --version
/usr/bin/curl --version
```

I don't have any gist logs because:

```bash
brew gist-logs curl
Error: No logs.
```

**Comment by claui** [comment]
See the corresponding [FAQ entry](https://docs.brew.sh/FAQ#how-can-i-specify-different-configure-arguments-for-a-formula).

**Comment by rgoldberg** [comment]
Can you explain why the default installation of Homebrew curl doesn't contain the same features as the macOS builtin curl?

It would seem to make sense to have the same features…

**Comment by gromgit** [comment]
> Can you explain why the default installation of Homebrew curl doesn't contain at least all the features supported by the macOS builtin curl?

Homebrew is a _community_ project, so formulae are maintained by the community, not just by a handful of maintainers. This means the general state of formulae actually reflects the needs of the community quite accurately; if it didn't, someone would `brew edit` the "offending" formula rather quickly...and submit a pull request if they felt the community would benefit from it.

So it would appear that no one felt the need for a Kerberos-enabled `curl`, for instance, even though the Apple binary supports it. If you have a need for a Homebrew `curl` that supports more exotic features, and you think others do too, [make it happen](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request).

**Comment by rgoldberg** [comment]
I don't think that closing issues without any explanation helps maintain or grow a community.

No opportunity for discussion was allowed before one person decided to close this issue, and now almost no one will see this issue.

That seems to indicate that Homebrew is maintained by a handful of maintainers who are disdainful of the community at large.

If you really need to separate backburner issues from more urgent ones, you should use priority tags instead of just closing issues.

If someone who already knows the curl installer options and/or Homebrew formula standard practices saw this issue and agreed with its proposed change, then they could have implemented it much faster than I possibly could.

I won't go through the trouble to learn how to edit the curl formula unless I know that the change that I've proposed will be accepted.

And closing an issue with a curt reply and no discussion seems to indicate that any changes to the formula won't be accepted.

So, will my proposed change will be accepted if a correct, efficient, elegant PR is submitted?

If not, why?

If so, then please leave the issue open until it is implemented, or until maintainers change their minds about accepting it and provide an explanation for their change of mind.

**Comment by claui** [comment]
> I don't think that closing issues without any explanation

Your original question did not ask for an explanation. The question was whether you can install curl with specific options, nothing more.

No way to anticipate whether or not you would proceed to ask for the why.

> helps maintain or grow a community.

That’s not how we use the issue tracker at Homebrew.

We already have a place where the people who **use** Homebrew can discuss to their hearts content: https://discourse.brew.sh

The issue tracker is where **maintainers** track pending work items. If the work is done, we close
the issue. If you ask for help on how to do a particular thing, and your question gets answered, we close the issue.

> No opportunity for discussion was allowed

No, that would be _locking_ the issue.
The issue status does not close the discussion. How else would we be discussing here right now?

> That seems to indicate that Homebrew is maintained by a handful of maintainers who are disdainful of the community at large.

Would it make sense for Homebrew maintainers to dedicate hours and hours to working on a community project if they actually hated the community?

> you should use priority tags

No, sorry. We’re quite happy with the way we organize our work items.

> It would make more sense to discuss the actual issue that I raised

You asked how to change a formula despite it being already answered in our FAQ. What do you expect?

> please leave the issue open until it is implemented

The only thing that would accomplish is Homebrew maintainers drowning in thousands of open issues.

> why would you suggest that I should waste time creating a PR without knowing that it will be accepted?

That’s just how GitHub works. If you don’t feel that’s your thing, then why contribute?

Yes, it generally makes sense to ask beforehand whether we would consider a PR.

But not for a one-liner. If you’re not even willing to spend time on a one-line pull request unless maintainers give you a pre-approval rubber stamp, then you may want to re-consider contributing to Homebrew after all.

You don’t have to.

**Comment by rgoldberg** [comment]
Will a well-written PR for this change be accepted if submitted? I still don't know…

Detailed responses to the recent comment from @claui:

> Your original question did not ask for an explanation. The question was whether you can install curl with specific options, nothing more.
>
> No way to anticipate whether or not you would proceed to ask for the why.

When I wrote "Can you install…" I meant can you, the Homebrew maintainers, change the install such that default Homebrew curl has the same features as the macOS builtin curl.  Sorry it wasn't clear, but my later line did state: "Homebrew curl should have the same options as the macOS builtin curl." which (to me) implies a change to the curl core formula (yes, this could have been more explicitly written as "Homebrew core curl should by default include at least all the same optional features as the macOS builtin curl without having to modify the formula.").

> We already have a place where the people who **use** Homebrew can discuss to their hearts content: https://discourse.brew.sh

I already asked about this issue there, and was told by someone that the intent was to keep the features of Homebrew curl synced with those of macOS builtin curl.  See https://discourse.brew.sh/t/please-install-curl-with-same-options-as-macos-curl/8301/4

From what I was told there, it seemed like this issue should be a pending work item, as the curl features are obviously not in sync.

> The issue status does not close the discussion. How else would we be discussing here right now?

I wrote "No opportunity for discussion was allowed before one person decided to close this issue".  That is correct.  There was no opportunity for discussion **_before_** the issue was closed, which is different than opportunity for discussion **_after_** the issue was closed.

> Would it make sense for Homebrew maintainers to dedicate hours and hours to working on a community project if they actually hated the community?

I wrote "disdainful of the community at large", which is different than "hate the community".  Someone can care about working on a project while still being disdainful of the community at large.  I also said "seems to indicate", allowing for alternative explanations.

> > It would make more sense to discuss the actual issue that I raised
> 
> You asked how to change a formula despite it being already answered in our FAQ. What do you expect?

My above quote was a reply to @gromgit (not to you, @claui), who told me how to submit a PR instead of discussing whether or not my suggested change should be accepted (which is what I meant by "discuss the actual issue that I raised"), and instead of discussing how I could secure approval.  That seems to be putting the cart before the horse.

> The only thing that would accomplish is Homebrew maintainers drowning in thousands of open issues.

If you used priority tags, then Homebrew maintainers wouldn't drown at all.  You could label as "Backlog" all unresolved issues that you would have closed in the current workflow, and filter those out.  You could see the same exact issues as you currently see, but everyone would also be able to easily see unimplemented requests to either discuss, vote, or work on them.  Right now, if someone wants to contribute, open backlog requests aren't easily distinguishable from completed or rejected requests.

> That’s just how GitHub works. If you don’t feel that’s your thing, then why contribute?

Many GitHub projects that I've seen actually prefer an issue to be submitted and approval granted before a PR is submitted.  You might prefer to get one-liner PRs without an issue being opened, but it's not the sole way in which GitHub works.

> But not for a one-liner. If you’re not even willing to spend time on a one-line pull request unless maintainers give you a pre-approval rubber stamp, then you may want to re-consider contributing to Homebrew after all.

I didn't know the mapping between curl installer options & the features listed in `curl --version`.  I don't know Ruby or how formula are generally written.  While both should be easy to learn, when I added to the curl formula some curl installer options that I found via research, the features to which they should have mapped weren't actually included with a new curl install using the modified formula, yet no errors reported.  I also don't know how to run your build and/or testing suite, etc., so there are many things I'd potentially have to learn to get this "one-liner" working.

If someone who already has all the requisite knowledge saw this issue and agreed that it makes sense to align the Homebrew curl optional features with those of the macOS builtin curl, then it should take around as much time for them to write the "one-liner" themselves as for them to review any "one-liner" submitted by me or by anyone else. Thus it seems a much more efficient use of everyone's time to have the people who would accept the PR know about the requested change and to decide if it makes sense doing this before anyone actually does it.

**Comment by claui** [comment]
> When I wrote "Can you install…" I meant can you, the Homebrew maintainers, change the install such that default Homebrew curl has the same features as the macOS builtin curl. Sorry it wasn't clear

Noted. As @SMillerDev [said on Discourse](https://discourse.brew.sh/t/please-install-curl-with-same-options-as-macos-curl/8301/6), Homebrew generally doesn’t accept feature requests without an accompanying PR.

> the intent was to keep the features of Homebrew curl synced with those of macOS builtin curl.

Correct, that’s indeed the intent.

> there are many things I'd potentially have to learn to get this "one-liner" working.

I was referring to the Kerberos feature @gromgit mentioned. Only just now did I realize there are a couple more features missing than just Kerberos. So I’m going to retract my _one-liner_ estimate. Apologies.

For the record, the following features appear to be missing for feature parity:

- `GSS-API`
- `HTTP2`
- `HTTPS-proxy`
- `Kerberos`
- `MultiSSL`
- `SPNEGO`

> Thus it seems a much more efficient use of everyone's time to have the people who could accept the PR know about the requested change and to decide if it makes sense doing this before anyone actually tries to implement it.

Thanks for clarifying. Now I feel I understand your point much better than initially.
I still disagree though.

If I understand you correctly, you’d have preferred the following run of events: 1. you post an issue requesting the feature, 2. the issue stays open, 3. someone more experienced (hopefully) finds the issue and 4. writes a PR with less effort than you would have had.
That’s completely understandable from your point of view. The thing is though: that’s just not how we use this issue tracker. Homebrew maintainers use it for tracking their own work. Any dilution of that, e. g. having to apply some kind of filter, is not acceptable for us, sorry. Our premise is: _open issue_ `==` _maintainer to-do,_ and we’re not willing to change that.

If you want visibility for your use case, _and at the same time don’t want to do the PR yourself_ (which you didn’t mention in the original Discourse thread), then the issue tracker is the wrong place for your request. On our Discourse, threads will stay open indefinitely, even for years, and Homebrew enthusiasts do frequent the Discourse.

**Comment by claui** [comment]
Related: https://github.com/Homebrew/homebrew-core/pull/52045#issuecomment-602559290

**Comment by claui** [comment]
> Will a well-written PR for this change be accepted if submitted? I still don't know…

@SMillerDev already [answered that on the Discourse thread](https://discourse.brew.sh/t/please-install-curl-with-same-options-as-macos-curl/8301/8):

> it’s almost impossible to tell if it would be accepted without seeing the change and the impact.

**Comment by rgoldberg** [comment]
> > Will a well-written PR for this change be accepted if submitted? I still don't know…
> 
> @SMillerDev already [answered that on the Discourse thread](https://discourse.brew.sh/t/please-install-curl-with-same-options-as-macos-curl/8301/8):
> 
> > it’s almost impossible to tell if it would be accepted without seeing the change and the impact.

It sounds like everyone involved so far is fine with replicating options from macOS builtin curl, as long as nothing untoward is discovered in the process.  i.e. no one currently has any specific objections other than we need to ensure that nothing bad happens.  Should anyone else be consulted about the advisability of making this change?

PS: @SMillerDev mentioned the above after I created this issue, otherwise I would have discussed all this on Discourse instead of creating an issue.

> If I understand you correctly, you’d have preferred the following run of events: 1. you post an issue requesting the feature, 2. the issue stays open, 3. someone more experienced (hopefully) finds the issue and 4. writes a PR with less effort than you would have had.
> That’s completely understandable from your point of view. The thing is though: that’s just not how we use this issue tracker. Homebrew maintainers use it for tracking their own work. Any dilution of that, e. g. having to apply some kind of filter, is not acceptable for us, sorry. Our premise is: _open issue_ `==` _maintainer to-do,_ and we’re not willing to change that.
> 
> If you want visibility for your use case, _and at the same time don’t want to do the PR yourself_ (which you didn’t mention in the original Discourse thread), then the issue tracker is the wrong place for your request. On our Discourse, threads will stay open indefinitely, even for years, and Homebrew enthusiasts do frequent the Discourse.

I'd be willing to do the PR myself, but I just want confirmation that no one in the approval chain has any specific known objections.  I'd also prefer if someone else could do it if they can implement it around as quickly as reviewing any PR from me.

Who is the most knowledgeable about / in control of the curl formula?  I saw some names in the git log for the formula, but I would prefer to not bother random people.

Is there any way to mark Discourse threads as feature requests and/or bug reports?  Is there any way to mark them as accepted in principle, pending review of an actual implementation in a PR?  That should greatly simplify finding conceptually approved issues to work on, finding issues that still need to be discussed before they're conceptually approved, and finding requests for help.

If this doesn't yet exist, maybe new separate Discourse categories could be created for each type of thread.

If people frequently open issues in GitHub that should be in Discourse instead, you could either have instructions that you can copy & paste into a closing comment with instructions about reposting the issue in Discourse, or you could even automate the reposting (I assume the former would be much simpler).

Or if you want to track backlog issues in GitHub without them remaining open, you could apply a backlog label and still close the issues.  So, you could still find backlog issues separately from closed resolved or rejected issues without polluting the open issues.

**Comment by SMillerDev** [comment]
> Who is the most knowledgeable about / in control of the curl formula? I saw some names in the git log for the formula, but I would prefer to not bother random people.

Homebrew doesn't have specific maintainers. Anyone working on a formula more often is purely coincidence.

As for the issue vs discourse thing. Issues are just here to track ongoing work as far as homebrew is concerned. The only reason to have an issue and a pull request is if there's more pull requests to follow (for example updating everything to python@3.8).

Discourse is just for general discussions and support, not to track work. 

Think of it as cooking dinner, you might want to talk to people about food (discourse) or you might want to actually make it (pull request). But putting up a notice for the neighborhood that you're going to cook isn't helping anyone (issues). Unless you cooking affects everyone else's dinner.

**Comment by claui** [comment]
> Or if you want to track backlog issues in GitHub without them remaining open, you could apply a backlog label and still close the issues.

That’s actually not too bad an idea.

We could close the issue and tack on a **help wanted** tag for discoverability.
I wouldn’t object to that.

**Comment by claui** [comment]
> I just want confirmation that no one in the approval chain has any specific known objections

Judging from Homebrew `curl`’s history and from our intent to maintain feature parity, I don’t see why we wouldn’t consider a PR that aims to add the missing features.

**Comment by SeekingMeaning** [comment]
Just for the record curl-openssl has all the features of Apple curl except MultiSSL:

```
$ /usr/local/opt/curl-openssl/bin/curl --version
curl 7.71.1 (x86_64-apple-darwin19.5.0) libcurl/7.71.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 c-ares/1.16.1 libssh2/1.9.0 nghttp2/1.41.0 librtmp/2.3
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

```
$ /usr/bin/curl --version
curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets
```

**Comment by SMillerDev** [comment]
> Might be worth noting that Apple curl uses LibreSSL instead of OpenSSL

This is intentional (by Apple) since they deprecated (or even removed) openssl from macOS a long time ago.

> Maybe we should replace the current curl formula with curl-openssl

We won't, they server very different purposes. `curl` is supposed to be a newer replacement for `/usr/bin/curl` and `curl-openssl` is there mostly to coexist with other tools that require `curl` with additional features and/or openssl.

**Comment by alebcay** [comment]
Re-opening issue due to it now being actionable/in progress.

**Comment by MikeMcQuaid** [comment]
> Judging from Homebrew `curl`’s history and from our intent to maintain feature parity, I don’t see why we wouldn’t consider a PR that aims to add the missing features.

In short (to expand on comments on this PRs): this would require adding a bunch of additional dependencies (and formulae) to a very widely used formula based on the request from a single user. I think that's excessive, in this case, and a custom formula would be a better fit.

**Comment by iMichka** [comment]
We (finally) got rid of curl-openssl and curl has been improved: #58274

I think this solves the initial request from this issue.
