### ISSUE TITLE
RfI: formulae issie

### ISSUE THREAD

**Issue by chrisAtRedis** [Homebrew/homebrew-core#57794]
Quick question: how do I report issues for a certain package that not necessarily upstream-related but may have to do with OSX-specific packaging? Couldn't find the info in the FAQ so opening an issue here.

# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by claui** [comment]
Unless it’s a bug in Homebrew itself, then an issue should be filed in the same repository to which the formula belongs.

I can’t find any formula called `issie` so I’m afraid that I can’t help you unless you clarify.

Closing for now but feel free to add further
clarification.
