### ISSUE TITLE
qt5 fails to build under MAC OS 10.12 (Sierra)

### ISSUE THREAD

**Issue by Andres-M-Rios** [Homebrew/homebrew-core#5785]
### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

gt5 fails to build on final steps under MAC OSX 10.12 (Sierra)

https://gist.github.com/c93211b085d7aeead2521c4232c9e24f

**Comment by zmwangx** [comment]
Upstream problem, known and tracked elsewhere. #5488 #5391
