### ISSUE TITLE
Installing samtools via linuxbrew results in failure to download Amazon S3 urls

### ISSUE THREAD

**Issue by cmdcolin** [Homebrew/homebrew-core#57907]
I found that using linuxbrew to download samtools causes issue

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [N/A] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/cmdcolin/6cb00af5617ad5d35e93ff5f473bd6ba 
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I would like to use samtools to download from an Amazon S3 URL on a linuxbrew environment. This works when samtools is installed using APT using the same command, but when using linuxbrew, it produces an error

## What happened (include command output)

```
$ samtools view https://s3.amazonaws.com/jbrowse.org/genomes/hg19/skbr3/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.splitters.bam 1:1-10000 -o out.sam
[E::idx_test_and_fetch] Error reading "https://s3.amazonaws.com/jbrowse.org/genomes/hg19/skbr3/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.splitters.bam.bai"
Segmentation fault (core dumped)
$ samtools --version
samtools 1.10
Using htslib 1.10.2
Copyright (C) 2019 Genome Research Ltd.
$ which samtools
/home/linuxbrew/.linuxbrew/bin/samtools
```

## What you expected to happen

Note: I did this fully after installing htslib so it did not interfere with the previous commands

```
sudo apt install samtools
 /usr/bin/samtools view https://s3.amazonaws.com/jbrowse.org/genomes/hg19/skbr3/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.splitters.bam 1:1-10000 -o out.sam
rm *.bai
```
This same command works where the homebrew one did not. I manually remove the successful download of the bai file from the /usr/bin/samtools run so as not to contaminate other runs using the linuxbrew samtools as the bai downloading step is the failure point

## Step-by-step reproduction instructions (by running `brew install` commands)

Installing samtools via linuxbrew on a fresh ubuntu 20 AWS EC2 instance with ssd
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
brew install hello
hello # works
brew install samtools
samtools view https://s3.amazonaws.com/jbrowse.org/genomes/hg19/skbr3/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.splitters.bam 1:1-10000 -o out.sam # produces error and segmentation fault
```

Build from source for both htslib and samtools does not help

```
brew reinstall --build-from-source htslib
brew reinstall --build-from-source samtools
samtools view https://s3.amazonaws.com/jbrowse.org/genomes/hg19/skbr3/reads_lr_skbr3.fa_ngmlr-0.2.3_mapped.splitters.bam 1:1-10000 -o out.sam # still fails
```

I have not confirmed anything on macOS. I am not really sure but a possible point of reference might be the curl or openssl formulas which samtools depends on via curl (samtools->htslib->curl->openssl)

**Comment by cmdcolin** [comment]
I also understand this is a bit obscure but I was not sure where to put this issue. If it is recommended to be moved let me know. I thought it may not strictly be a samtools issue because of the linuxbrew association here

**Comment by cmdcolin** [comment]
There is some work in the upstream samtools repo on this issue now, so a fix for this would probably be pending a new samtools release

**Comment by jonchang** [comment]
We should pull in this htslib patch once it's merged. https://github.com/samtools/htslib/pull/1105

**Comment by jonchang** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/58458
