### ISSUE TITLE
NoMethodError: undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by watsy0007** [Homebrew/homebrew-core#57913]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew upgrade`

## What happened (include command output)

I exec `brew upgrade --verbose`

```
Updating Homebrew...
Warning: You are using macOS 10.16.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

==> Upgrading 3 outdated packages:
sbt 1.3.12 -> 1.3.13
node 14.4.0 -> 14.5.0
libzip 1.7.1 -> 1.7.2
==> Upgrading sbt 1.3.12 -> 1.3.13
==> Downloading https://github.com/sbt/sbt/releases/download/v1.3.13/sbt-1.3.13.tgz
Already downloaded: /Users/watsy0007/Library/Caches/Homebrew/downloads/c81324436e9377f9a8b1de327fc2a7ee6b6a87b3dd3425affcd19a1e151675f3--sbt-1.3.13.tgz
==> Verifying c81324436e9377f9a8b1de327fc2a7ee6b6a87b3dd3425affcd19a1e151675f3--sbt-1.3.13.tgz checksum
rm /usr/local/bin/sbt
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200714-73489-1vuvqqd.sb nice ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/sbt.rb --verbose
ln -s ../Cellar/sbt/1.3.12/bin/sbt sbt
Error: An exception occurred within a child process:
  NoMethodError: undefined method `path' for nil:NilClass
Did you mean?  paths
```

## What you expected to happen

upgrade success.

**Comment by SMillerDev** [comment]
> Warning: You are using macOS 10.16.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.
