### ISSUE TITLE
glib build from source fails 

### ISSUE THREAD

**Issue by jnozsc** [Homebrew/homebrew-core#57925]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install -s glib`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

==> Installing glib
==> Patching
==> Applying hardcoded-paths.diff
patching file gio/gdbusprivate.c
Hunk #1 succeeded at 2471 (offset 364 lines).
Hunk #2 succeeded at 2481 (offset 364 lines).
patching file gio/xdgmime/xdgmime.c
patching file glib/gutils.c
Hunk #1 succeeded at 2497 (offset 417 lines).
==> meson --prefix=/usr/local/Cellar/glib/2.64.4 --libdir=/usr/local/Cellar/glib/2.64.4/lib -Diconv=
==> ninja -v
==> ninja install -v
Error: An exception occurred within a child process:
  Utils::InreplaceError: inreplace failed
/usr/local/Cellar/glib/2.64.4/lib/pkgconfig/glib-2.0.pc:
  expected replacement of "Cflags:-I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include" with "Cflags:-I${includedir}/glib-2.0 -I${libdir}/glib-2.0/include -I/usr/local/opt/gettext/include"

  </pre>
</details>
https://gist.github.com/jnozsc/80a4026828638a5f91ebe9289e51d93b

## What you expected to happen

build without issue

## Step-by-step reproduction instructions (by running `brew install` commands)

run `brew install -s glib`

**Comment by Rylan12** [comment]
Thanks for bringing this up! The fix should be in #57926

**Comment by Rylan12** [comment]
Just so you know, building from source is an unsupported configuration. In the future, please open a PR to fix the issue rather than creating an issue here.

**Comment by Bo98** [comment]
Not particularly surprising I'm seeing this break - it's happened before. I wondered when this day would come.

**Comment by Rylan12** [comment]
@Bo98 is there a bigger issue here that can be solved?

I don't know how often something like this happens, but would a method that matches things like this better be useful?

I'm thinking, for example:

```ruby
cflags("foo", "bar")
```

could match all of the following:

```
Cflags:-Ifoo -Ibar
Cflags: -Ifoo -Ibar
Cflags:-Ibar -Ifoo
Cflags: -Ibar -Ifoo
```

My lack of understanding of the specifics here is showing, so maybe this isn't an issue that needs to be solved. Or, maybe this should be extended to more than `cflags`.

**Comment by Bo98** [comment]
I suppose ideally we wouldn't be using `inreplace` at all but there's probably not much we can do about that.

I don't expect this to break 3rd time so I'm fine with merging the change as already proposed. The space mistakedly disappeared in some `meson` refactoring and only has now returned.

**Comment by Rylan12** [comment]
Assuming the `meson` issue was a one-time issue and this is just "reverting back to normal", so to say, I think that's reasonable. However, if things like this happen pretty often and require these sorts of trivial changes (e.g. adding/removing a space), it might be a good idea to come up with a better solution.

It sounds like that's not the case here, though, which is good 👍
