### ISSUE TITLE
openssl can't bootstrap certificates in sandbox

### ISSUE THREAD

**Issue by MSch** [Homebrew/homebrew-core#5793]
It seems that the bootstrapping of openssl's certificates is broken. When I run `security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain` in Terminal.app I get a list of certificates, but when I added a `puts certs_list` to the `post_install` section of the `openssl` formula it was _empty_.

I suspect that's because of the sandboxing.

**Comment by tdsmith** [comment]
I can't reproduce.

**Comment by MikeMcQuaid** [comment]
@tdsmith That's enough for me to close. 

@MSch if you can pin down the exact cause we'll accept a PR. We're also happy to help you narrow this down.

**Comment by MSch** [comment]
@MikeMcQuaid awesome!

I can reproduce this on some Macs but not on others. I'd like to narrow it down to the sandbox.

Can you point me in the right direction so I can write a minimal script that just runs `security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain` in the same sandbox that's used by homebrew? Knowing where/how is the Homebrew sandbox set up should be enough for me to do that.

Would that be enough to reopen the issue?

**Comment by MSch** [comment]
Ah I've found https://github.com/Homebrew/brew/blob/master/Library/Homebrew/sandbox.rb by myself.

So to confirm: If the file gets created correctly with `brew install openssl --no-sandbox` but not with `brew install openssl` the issue is narrowed down to the sandbox?

**Comment by tdsmith** [comment]
Running `brew postinstall openssl` should be enough if it's responsive to
--no-sandbox, which maybe it should be if it isn't.

**Comment by MSch** [comment]
@tdsmit yep that reproduced it

```
macmini01:~ ci$ brew postinstall openssl
==> Using the sandbox
macmini01:~ ci$ ls -l /usr/local/etc/openssl/cert.pem
-rw-r--r--  1 ci  admin  0 Oct 12 07:40 /usr/local/etc/openssl/cert.pem
macmini01:~ ci$ brew postinstall --no-sandbox openssl
macmini01:~ ci$ ls -l /usr/local/etc/openssl/cert.pem
-rw-r--r--  1 ci  admin  261425 Oct 12 07:40 /usr/local/etc/openssl/cert.pem
```

Looking at the sandbox logs I've figured out the problem, it's with `Sandbox.allow_write_temp_and_cache`, it does not use `DARWIN_USER_CACHE_DIR` and `DARWIN_USER_TEMP_DIR` but hardcodes the paths where it assumes those directories exist.

Would a PR fixing it by shelling out to `getconf DARWIN_USER_CACHE_DIR` respective `getconf DARWIN_USER_TEMP_DIR` and then following the symlink (if exists) be accepted or is this a too-special situation you do not want to handle in homebrew?

```
SandboxViolation: security(87866) deny file-write-data /Volumes/CI/ci/.darwin_user_cache_dir/mds/mds.lock
```

**Comment by MikeMcQuaid** [comment]
@MSch You could consider setting `HOMEBREW_TEMP` instead/as well.

**Comment by MSch** [comment]
@MikeMcQuaid Good idea! That works as a fix. Thanks!
