### ISSUE TITLE
Bulk add licenses

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/homebrew-core#57933]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I  have a [branch](https://github.com/dtrodrigues/homebrew-core/tree/license) which adds 118 commits for licenses to homebrew-core formulae. Can a maintainer merge these in? I didn't open a PR since doing so (even a draft PR) would kick of CI for all of the formulae - https://github.com/Homebrew/brew/pull/7762#issuecomment-652275106
## What happened (include command output)

<details>
  <summary>Updated licenses</summary>
  <pre>
allure (Apache-2.0)
amp (GPL-3.0)
ansible-lint (MIT)
archi-steam-farm (Apache-2.0)
asciidoctorj (Apache-2.0)
atdtool (BSD-3-Clause)
atomicparsley (GPL-2.0)
autoenv (MIT)
autorest (MIT)
avra (GPL-2.0)
aws-shell (Apache-2.0)
ccm (Apache-2.0)
cdk8s (Apache-2.0)
choose-rust (GPL-3.0)
closure-compiler (Apache-2.0)
conserver (BSD-3-Clause)
crowdin (MIT)
csvtomd (MIT)
dehydrated (MIT)
denominator (Apache-2.0)
detekt (Apache-2.0)
dex2jar (Apache-2.0)
docker-squash (MIT)
doctest (MIT)
dxpy (Apache-2.0)
eg-examples (MIT)
eject (MIT)
ekg2 (GPL-2.0)
eralchemy (Apache-2.0)
fcitx-remote-for-osx (GPL-3.0)
flank (Apache-2.0)
fluxctl (Apache-2.0)
gdub (MIT)
gimme-aws-creds (Apache-2.0)
git-town (MIT)
giter8 (Apache-2.0)
gleam (Apache-2.0)
gluon (MIT)
grip (MIT)
grpcui (MIT)
heksa (Apache-2.0)
howdoi (MIT)
ilmbase (BSD-3-Clause)
itk (Apache-2.0)
jerryscript (Apache-2.0)
jinja2-cli (BSD-2-Clause)
jobber (MIT)
jsdoc3 (Apache-2.0)
juju (AGPL-3.0)
keepkey-agent (LGPL-3.0)
kumo (MIT)
latexindent (GPL-3.0)
libhttpseverywhere (LGPL-3.0)
libimobiledevice (LGPL-2.1)
macos-trash (MIT)
mandown (MIT)
mariadb-connector-c (LGPL-2.1)
mdbook (MPL-2.0)
mdxmini (GPL-2.0)
miruo (GPL-3.0)
ncmpcpp (GPL-2.0)
nest (GPL-2.0)
networkit (MIT)
node-sass (MIT)
nu (Apache-2.0)
nvm (MIT)
oauth2_proxy (MIT)
onednn (Apache-2.0)
opencolorio (BSD-3-Clause)
openexr (BSD-3-Clause)
oq (MIT)
osm-pbf (LGPL-3.0)
packmol (MIT)
pacparser (LGPL-3.0)
pandoc-include-code (MPL-2.0)
pdf2svg (GPL-2.0)
peru (MIT)
pick (MIT)
po4a (GPL-2.0)
prefixsuffix (GPL-2.0)
protobuf-swift (Apache-2.0)
pwsafe (GPL-2.0)
pygitup (MIT)
pyvim (BSD-3-Clause)
qp (MIT)
rbenv-default-gems (MIT)
rbenv-vars (MIT)
redis (BSD-3-Clause)
redis@4.0 (BSD-3-Clause)
rest-shell (Apache-2.0)
rethinkdb (Apache-2.0)
ry (MIT)
s2n (Apache-2.0)
saltwater (BSD-3-Clause)
savana (LGPL-3.0)
sbjson (BSD-3-Clause)
shml (MIT)
sjk (Apache-2.0)
skktools (GPL-2.0)
slackcat (MIT)
sonic (MPL-2.0)
spring-loaded (Apache-2.0)
stlink (BSD-3-Clause)
tbb (Apache-2.0)
tbox (Apache-2.0)
tre-command (MIT)
trezor-agent (LGPL-3.0)
twarc (MIT)
unoconv (GPL-2.0)
uptoc (MIT)
vapor (MIT)
wren (MIT)
wren-cli (MIT)
xtensor (BSD-3-Clause)
xxh (BSD-2-Clause)
zim (GPL-2.0)
zoxide (MIT)
zurl (GPL-3.0)
  </pre>
</details>

## What you expected to happen

n/a

## Step-by-step reproduction instructions (by running `brew install` commands)

n/a

**Comment by Bo98** [comment]
Done. Thanks @dtrodrigues!
