### ISSUE TITLE
Add a few more licenses

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/homebrew-core#57938]
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Similar to https://github.com/Homebrew/homebrew-core/issues/57933, 6 new licenses at https://github.com/dtrodrigues/homebrew-core/tree/license

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by Bo98** [comment]
Merged. Thanks!
