### ISSUE TITLE
A couple more licenses

### ISSUE THREAD

**Issue by dtrodrigues** [Homebrew/homebrew-core#57947]
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Similar to https://github.com/Homebrew/homebrew-core/issues/57933 and https://github.com/Homebrew/homebrew-core/issues/57938, 8 more licenses are added at https://github.com/dtrodrigues/homebrew-core/tree/license that are in the NPM Registry.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$  for u in $(grep "^  url \"https://registry.npm" $(grep -L license  *rb) | cut -d\" -f2); do echo -n $u && curl -s $u | tar -xzOf - package/package.json | jq .license; done
https://registry.npmjs.org/autocode/-/autocode-1.3.1.tgz"Apache-2.0"
https://registry.npmjs.org/bit-bin/-/bit-bin-14.8.8.tgz"Apache-2.0"
https://registry.npmjs.org/fauna-shell/-/fauna-shell-0.11.4.tgz"MPL-2.0"
https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.3.2.tgz"MIT"
https://registry.npmjs.org/joplin/-/joplin-1.0.164.tgz"MIT"
https://registry.npmjs.org/now/-/now-19.1.2.tgz"Apache-2.0"
https://registry.npmjs.org/react-native-cli/-/react-native-cli-2.0.1.tgz"BSD-3-Clause"
https://registry.npmjs.org/triton/-/triton-7.10.0.tgz"MPL-2.0"

  

  </pre>
</details>

**Comment by Bo98** [comment]
Merged. Thanks again!
