### ISSUE TITLE
Broken vim after python update

### ISSUE THREAD

**Issue by mafrosis** [Homebrew/homebrew-core#5794]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

After the recent python update, my vim is broken:

    E887: Sorry, this command is disabled, the Python's site module could not be loaded.

Vim is linked to a non-existent directory. Output from `vim --version`:

	VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  7 2016 05:29:44)
	MacOS X (unix) version
	Included patches: 1-22
	Compiled by Homebrew
	Huge version without GUI.  Features included (+) or not (-):
	+acl             +file_in_path    +mouse_sgr       +tag_old_static
	+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
	+autocmd         +float           +mouse_urxvt     -tcl
	-balloon_eval    +folding         +mouse_xterm     +termguicolors
	-browse          -footer          +multi_byte      +terminfo
	++builtin_terms  +fork()          +multi_lang      +termresponse
	+byte_offset     -gettext         -mzscheme        +textobjects
	+channel         -hangul_input    +netbeans_intg   +timers
	+cindent         +iconv           +num64           +title
	-clientserver    +insert_expand   +packages        -toolbar
	+clipboard       +job             +path_extra      +user_commands
	+cmdline_compl   +jumplist        +perl            +vertsplit
	+cmdline_hist    +keymap          +persistent_undo +virtualedit
	+cmdline_info    +lambda          +postscript      +visual
	+comments        +langmap         +printer         +visualextra
	+conceal         +libcall         +profile         +viminfo
	+cryptv          +linebreak       +python          +vreplace
	+cscope          +lispindent      -python3         +wildignore
	+cursorbind      +listcmds        +quickfix        +wildmenu
	+cursorshape     +localmap        +reltime         +windows
	+dialog_con      -lua             +rightleft       +writebackup
	+diff            +menu            +ruby            -X11
	+digraphs        +mksession       +scrollbind      -xfontset
	-dnd             +modify_fname    +signs           -xim
	-ebcdic          +mouse           +smartindent     -xpm
	+emacs_tags      -mouseshape      +startuptime     -xsmp
	+eval            +mouse_dec       +statusline      -xterm_clipboard
	+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
	+extra_search    -mouse_jsbterm   +syntax
	+farsi           +mouse_netterm   +tag_binary
	   system vimrc file: "$VIM/vimrc"
	     user vimrc file: "$HOME/.vimrc"
	 2nd user vimrc file: "~/.vim/vimrc"
	      user exrc file: "$HOME/.exrc"
	       defaults file: "$VIMRUNTIME/defaults.vim"
	  fall-back for $VIM: "/usr/local/share/vim"
	Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
	Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib 
	-L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        
	-lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 
	-fstack-protector-strong -L/usr/local/lib  
	-L/usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level/CORE 
	-lperl -lm -lutil -lc -F/usr/local/Cellar/python/2.7.12_1/Frameworks -framework Python  
	 -lruby.2.3.0 -lobjc -L/usr/local/Cellar/ruby/2.3.1_2/lib

Note the `-F/usr/local/Cellar/python/2.7.12_1/Frameworks` in the final section.

Running `brew info python` shows:

    python: stable 2.7.12 (bottled), HEAD
    Interpreted, interactive, object-oriented programming language
    https://www.python.org
    /usr/local/Cellar/python/2.7.12_2 (3,477 files, 46.7M) *
      Poured from bottle on 2016-10-11 at 13:25:30
    From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
    ... snip ...

I tried `brew upgrade vim` and `brew uninstall vim && brew install vim`.

Thanks!

**Comment by jbeezley** [comment]
Same issue here.  Reinstalling from source fixed it for me.  `brew install -s vim`

**Comment by MikeMcQuaid** [comment]
CC @tdsmith.

**Comment by tdsmith** [comment]
Mea culpa. Fixed by #5750.

**Comment by mafrosis** [comment]
Thank you wonderful @Homebrew people
