### ISSUE TITLE
Missing Ansible systemd module

### ISSUE THREAD

**Issue by jas02** [Homebrew/homebrew-core#5796]
Hi,

I am using Ansible 2.1.2.0 from Homebrew 1.0.7. There is missing systemd.py module file (should be located in `/usr/local/Cellar/ansible/2.1.2.0/libexec/lib/python2.7/site-packages/ansible/modules/core/system/systemd.py`.

Please look on this issue, it's impossible to use Ansible systemd module without it.

Workaround is to download manually module from: `https://raw.githubusercontent.com/ansible/ansible-modules-core/devel/system/systemd.py` an save to the directory mentioned above.

Also, related to missing systemd.py, there are missing (required) files `/usr/local/Cellar/ansible/2.1.2.0/libexec/lib/python2.7/site-packages/ansible/module_utils/_text.py` and `six.py`.

Thanks 

Lumir

**Comment by tdsmith** [comment]
I do not think the current version of Ansible in Homebrew ships with that module. "systemd - Manage services: New in version 2.2." https://docs.ansible.com/ansible/systemd_module.html
