### ISSUE TITLE
Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib

### ISSUE THREAD

**Issue by sstadick** [Homebrew/homebrew-core#5799]
- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
```
Warning: Your XQuartz (2.7.8) is outdated.
Please install XQuartz 2.7.9 (or delete it):
  https://xquartz.macosforge.org

Warning: Your Xcode (7.3.1) is outdated.
Please update to Xcode 8.0 (or delete it).
Xcode can be updated from the App Store.
```

### Bug reports:

I can't run bash. When I do I get the following error. 
```
$ bash
  dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
  Referenced from: /usr/local/bin/bash
  Reason: image not found
Trace/BPT trap: 5
```

It looks like there is a newer version of libreadline: 
```
$ ls /usr/local/opt/readline/lib/libreadline*
/usr/local/opt/readline/lib/libreadline.7.0.dylib /usr/local/opt/readline/lib/libreadline.a
/usr/local/opt/readline/lib/libreadline.7.dylib   /usr/local/opt/readline/lib/libreadline.dylib
```

I have tried `brew remove readline` `brew update` `brew install readline`, and this didn't fix it. This all started a few days ago after doing a brew install of gnuplot.

**Comment by ilovezfs** [comment]
You need to upgrade bash ...

**Comment by sstadick** [comment]
I had no idea bash was linked to brew. Worked though, thank you!
`brew upgrade bash`

**Comment by jabbson** [comment]
What helped me was
```
cd $(brew --prefix readline)/lib
ln -s libreadline.dylib libreadline.6.dylib
```

**Comment by ilovezfs** [comment]
@jabbson that fix is not correct.

**Comment by geeksweep** [comment]
was there a fix here that i just missed?? I too am having this error when trying to run ./worldserver (3.3.5)

<img width="532" alt="screen shot 2017-04-07 at 3 37 24 pm" src="https://cloud.githubusercontent.com/assets/1126840/24816797/236679a0-1ba8-11e7-9898-b5a93dd4eddc.png">

when i try to upgrade bash i get the error that bash wasnt installed

<img width="734" alt="screen shot 2017-04-07 at 3 38 14 pm" src="https://cloud.githubusercontent.com/assets/1126840/24816827/4232e94a-1ba8-11e7-85b4-f4e0b50b2783.png">

anything i missed here?

(using mac osx 10.11.6)

**Comment by acalism** [comment]
`$ brew upgrade`
will upgrade all package installed by home-brew.

**Comment by pacav69** [comment]
i tried brew upgrade and that didn't upgrade bash
so i did 
brew upgrade bash
and that upgraded bash and now no more errors

**Comment by douglasresende** [comment]
I just make a link to the new version! (It's not a good ideia, but work)
```ln -s /usr/local/opt/readline/lib/libreadline.7.dylib /usr/local/opt/readline/lib/libreadline.6.dylib```
