### ISSUE TITLE
Python: requested URL Not found

### ISSUE THREAD

**Issue by JBallin** [Homebrew/homebrew-core#58084]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **On my work comp, don't want to add personal github creds to Terminal - is there a way to generate the same logs locally and manually update to a gist?**
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
  <summary>Command output</summary>
  <pre>
$ brew doctor
Your system is ready to brew.
$ brew config
HOMEBREW_VERSION: 2.4.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0f6bc6274f8fc0cfc19636688fc8aa6752d0c296
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4123dac50ed55ff2666294eade9a496b616b34a3
Core tap last commit: 6 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.27.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.5-x86_64
CLT: 1103.0.32.62
Xcode: N/A
  </pre>
</details>

## What you were trying to do (and why)

Update packages

## What happened (include command output)

Python URL returned 404, which resulted in building from source instead of bottle.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install python@3.8
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
cadence

==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.4.catalina.bottle.1.tar.gz
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "python@3.8"
Download failed: https://homebrew.bintray.com/bottles/python%403.8-3.8.4.catalina.bottle.1.tar.gz
Warning: Bottle installation failed: building from source.
  </pre>
</details>

## What you expected to happen

Update packages without error and build python from bottle, not source

## Step-by-step reproduction instructions (by running `brew install` commands)

`$ brew reinstall python`

**Comment by LanikSJ** [comment]
I know this doesn't help solve the problem for everyone but I found a way to work around the problem if you don't want to build the package from source.

```bash
wget -O /Users/LanikSJ/Library/Caches/Homebrew/downloads/031761fcf6e5a7e55b26fc10479c3904b23335de214073f016b77e7ea1d3092c--python@3.8-3.8.4.catalina.bottle.1.tar.gz https://homebrew.bintray.com/bottles/python%403.8-3.8.4.catalina.bottle.tar.gz
```
That will download the package from the correct location and save it in the Homebrew cache.  After that run `brew upgrade` just like you normally would.  Not sure if the SHA in the file name would be the same for everyone.  You might want to run `brew update && brew upgrade` first just to see what that file name should be.  You'll see something like this:

```bash
==> Pouring python@3.8-3.8.4.catalina.bottle.1.tar.gz
tar: Error opening archive: Failed to open '/Users/LanikSJ/Library/Caches/Homebrew/downloads/031761fcf6e5a7e55b26fc10479c3904b23335de214073f016b77e7ea1d3092c--python@3.8-3.8.4.catalina.bottle.1.tar.gz'
Error: Failure while executing; `tar xof /Users/LanikSJ/Library/Caches/Homebrew/downloads/031761fcf6e5a7e55b26fc10479c3904b23335de214073f016b77e7ea1d3092c--python@3.8-3.8.4.catalina.bottle.1.tar.gz -C /var/folders/59/rb3p8ppj5p536tdyg3v85kww0000gn/T/d20200716-38180-1mv102c` exited with 1. Here's the output:
tar: Error opening archive: Failed to open '/Users/LanikSJ/Library/Caches/Homebrew/downloads/031761fcf6e5a7e55b26fc10479c3904b23335de214073f016b77e7ea1d3092c--python@3.8-3.8.4.catalina.bottle.1.tar.gz'
```
Hope this helps someone. 🙂

**Comment by Bo98** [comment]
Fixed now. The PR didn't really need to be merged with bottles so I just reverted the bottle commit.

**Comment by JBallin** [comment]
Works! Thanks.

**Comment by claui** [comment]
Thanks for reporting @JBallin!
