### ISSUE TITLE
daemontools: /service directory permission issue

### ISSUE THREAD

**Issue by zdavatz** [Homebrew/homebrew-core#58222]
Normally the `service` directory for `daemontools` resides in `/service`. For Debian/Ubuntu it resides in `/etc/service`. 

The problem:
For `big Sur` trying to create a `service` directory in `/`results in:
```
➜  / sudo mkdir /service
Password:
mkdir: /service: Read-only file system
➜  /
```
I think it would would make sense to move the `service` directory to `/etc/service`. See also:
https://formulae.brew.sh/formula/daemontools

@claui can you help with this?

**Comment by SMillerDev** [comment]
Does homebrew define this directory specifically? Otherwise it probably should be `/usr/local/etc/service`. That way homebrew can also ensure it exists.

**Comment by zdavatz** [comment]
According to [DJ Berstein](https://cr.yp.to/djb.html) the Dir has to be `/service`. Debian/Ubuntu moved that to `/etc/service` on Gentoo it remains in `/service`. If you make it work with `/usr/local/etc/service` that would be great.

**Comment by claui** [comment]
> If you make it work with `/usr/local/etc/service` that would be great.

I’m going to have a look.

**Comment by zdavatz** [comment]
thank you @claui 👍
