### ISSUE TITLE
shebang of script installed in system site packages venv points to system python

### ISSUE THREAD

**Issue by thomasgilgenast** [Homebrew/homebrew-core#58248]
## issue checklist

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/ee13082ab314fabe447174eff2a44e36
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Note: as shown in the gist log I do have a non-Homebrew node.js install in `/usr/local/`; I don't think this interacts with Python at all though.

I initially opened this issue at pypa/pip#8600, but it appears to be an issue in Homebrew.

## What you were trying to do (and why)

I was trying to pip install a package in a system site packages Python venv created from a Python interpreter provided by the Homebrew Python 3.8 formula.

I was doing this because I use venvs to keep Python environments isolated, but there is a particular package I need that cannot be installed via pip, so I install it once manually into the system Python and share it to my venvs using the `--system-site-packages` flag.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
% brew install python
Warning: python@3.8 3.8.4 is already installed and up-to-date
To reinstall 3.8.4, run `brew reinstall python@3.8`
% /usr/local/opt/python@3.8/bin/python3.8 -m venv --system-site-packages venv-test
OR
% /usr/local/Cellar/python@3.8/3.8.4/bin/python3.8 -m venv --system-site-packages venv-test
% source venv-test/bin/activate
(venv-test)% venv-test/bin/python -c 'import sys; print(sys.executable)'
/usr/local/opt/python@3.8/bin/python3.8
(venv-test)% venv-test/bin/pip install tox
Collecting tox
  Using cached tox-3.17.1-py2.py3-none-any.whl (82 kB)
Requirement already satisfied: virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0 in /usr/local/lib/python3.8/site-packages (from tox) (20.0.27)
Collecting packaging>=14
  Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
Collecting pluggy>=0.12.0
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.8/site-packages (from tox) (1.15.0)
Collecting py>=1.4.17
  Using cached py-1.9.0-py2.py3-none-any.whl (99 kB)
Requirement already satisfied: filelock>=3.0.0 in /usr/local/lib/python3.8/site-packages (from tox) (3.0.12)
Collecting toml>=0.9.4
  Using cached toml-0.10.1-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: distlib<1,>=0.3.1 in /usr/local/lib/python3.8/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox) (0.3.1)
Requirement already satisfied: appdirs<2,>=1.4.3 in /usr/local/lib/python3.8/site-packages (from virtualenv!=20.0.0,!=20.0.1,!=20.0.2,!=20.0.3,!=20.0.4,!=20.0.5,!=20.0.6,!=20.0.7,>=16.0.0->tox) (1.4.4)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing, packaging, pluggy, py, toml, tox
Successfully installed packaging-20.4 pluggy-0.13.1 py-1.9.0 pyparsing-2.4.7 toml-0.10.1 tox-3.17.1
(venv-test)% tox --version
Traceback (most recent call last):
  File ".../venv-test/bin/tox", line 5, in <module>
    from tox import cmdline
ModuleNotFoundError: No module named 'tox'
(venv-test)% head -n 1 venv-test/bin/tox
#!/usr/local/opt/python@3.8/bin/python3.8
  </pre>
</details>

## What you expected to happen

I expected that
 1. when python is run from the venv, `sys.executable` would point to the venv's interpreter,
 2. when packages were installed inside the venv, their shebang would point to the venv's interpreter, and
 3. when a script installed in the venv is run, it would successfully import the corresponding package.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
% brew install python
% python3 -m venv --system-site-packages venv-test
% source venv-test/bin/activate
(venv-test)% python -c 'import sys; print(sys.executable)'  # points to system python interpreter
(venv-test)% pip install tox                                # installs into venv as expected
(venv-test)% tox --version                                  # fails with ModuleNotFoundError
(venv-test)% head -n 1 venv-test/bin/tox                    # points to system python interpreter
```

## My understanding/workaround

I think Homebrew generates a file `/usr/local/lib/python3.8/site-packages/sitecustomize.py`. This file contains specific logic at the end which overwrites `sys.executable` on [this line of the formula](https://github.com/Homebrew/homebrew-core/blob/31e1c99/Formula/python@3.8.rb#L302). My guess is that when `--system-site-packages` is off, this file never gets read and the venv works as normal (I can confirm that the behavior of `sys.executable` is as expected when `--system-site-packages` is not passed).

If I modify `/usr/local/lib/python3.8/site-packages/sitecustomize.py` to re-overwrite `sys.executable` if python is actually being invoked from a venv, everything works as expected. For example, I can write something like:

```python
for p in sys.path:
    if 'venv' in p:
        sys.executable = p.split('lib')[0] + 'bin/python'
```

though I am sure there must be better ways to detect whether or not python was invoked from a venv.

**Comment by Cerebus** [comment]
Setting `PYTHONEXECUTABLE=/path/to/venv/bin/python` prevents Homebrew `sitecustomize.py` from schwacking sys.executable, but since this env var isn't part of `activate`, it's a poor substitute for a fix.

**Comment by Cerebus** [comment]
Removing the last two lines of `sitecustomize.py` also fixes the issue, but that might have unforeseen consequences.

**Comment by Cerebus** [comment]
Better workaround: If using virtualenvwrapper, set premkvirtualenv:
```
#!/bin/bash
# This hook is run after a new virtualenv is created and before it is activated.
# argument: name of new environment
echo "export PYTHONEXECUTABLE=$WORKON_HOME/$1/bin/python" >> "$1/bin/activate"
```

PYTHONEXECUTABLE can be `unset` in postdeactivate.
