### ISSUE TITLE
Brew stuck installing apache

### ISSUE THREAD

**Issue by yillivs** [Homebrew/homebrew-core#5829]
So I tried to install apache through homebrew from homebrew/apache and after a bit I lost connection. So the package is missing some dependencies.

`brew missing
libevent: doxygen
nghttp2: doxygen
spdylay: doxygen`

Then I run

'brew install
Operation already in progress for doxygen
Another active Homebrew process is already using doxygen.
Please wait for it to finish or terminate it to continue'

In fact all the associated files that were going to install with apache say that message even if I try to run brew uninstall on them.

**Comment by MikeMcQuaid** [comment]
Try to run `brew cleanup` and try again.

**Comment by yillivs** [comment]
I had a terminal instance open in a tab that was running the brew install so there was an ssh process still open and a ruby process open. Killing them fixed the problem. Thanks!
