### ISSUE TITLE
ffmpeg requiring old libx264

### ISSUE THREAD

**Issue by xinaesthete** [Homebrew/homebrew-core#5844]
Similar issue to https://github.com/Homebrew/legacy-homebrew/issues/27866

*edit:* I tried `brew reinstall ffmpeg --build-from-source`, the result of which is what I now have installed.

    dyld: Library not loaded: /usr/local/lib/libx264.144.dylib
      Referenced from: /usr/local/bin/ffmpeg
      Reason: image not found
    Trace/BPT trap: 5

Looking in my `lib` folder:

    peter$ ls /usr/local/lib/libx264*
    /usr/local/lib/libx264.148.dylib	/usr/local/lib/libx264.a		/usr/local/lib/libx264.dylib

gist-log is here: [gist-log](https://gist.github.com/a80094f107da8e79c45d96075a2c8c19)

There are some complaints about `freetype2 not found` as well, which might warrant filing a separate issue, but I don't believe relates to my problem.

**Comment by retokromer** [comment]
I cannot reproduce your error. It works fine on my side. Did you `brew doctor`?

**Comment by xinaesthete** [comment]
Several times...

**Comment by retokromer** [comment]
OK

**Comment by xinaesthete** [comment]
I like that it now suggests

    These open issues may also help:
    ffmpeg requiring old libx264 https://github.com/Homebrew/homebrew-core/issues/5844

when I try reinstall again.

:)

Thanks for looking into it; obviously LMK if there's anything else I should try etc.

**Comment by retokromer** [comment]
Very useful suggestion indeed ;-)

**Comment by MikeMcQuaid** [comment]
@xinaesthete Looks like you have a few packages that need uninstalled and installed again. I'd probably advise a `brew bundle dump; brew uninstall --force $(brew list); brew bundle` to reinstall them again.

**Comment by xinaesthete** [comment]
During `brew bundle` it failed to install ffmpeg.  Now I (unsurprisingly) get `-bash: /usr/local/bin/ffmpeg: No such file or directory`.

Console output during `brew bundle`:

```
Warning: ffmpeg: --with-ffplay was deprecated; using --with-sdl instead!
==> Using the sandbox
==> Downloading https://ffmpeg.org/releases/ffmpeg-3.1.4.tar.bz2
Already downloaded: /Users/peter/Library/Caches/Homebrew/ffmpeg-3.1.4.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/3.1.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-libfreetype --enable-libtheora --enable-libvorbis --enable-libvpx --enable-librtmp --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libass --enable-libspeex --enable-libschroedinger --enable-libfdk-aac --enable-libopus --enable-frei0r --disable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I@@HOMEBREW_CELLAR@@/openjpeg/2.1.2/include/openjpeg-2.1 --enable-nonfree --enable-vda
Last 15 lines from /Users/peter/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-frei0r
--disable-lzma
--enable-libopenjpeg
--disable-decoder=jpeg2000
--extra-cflags=-I@@HOMEBREW_CELLAR@@/openjpeg/2.1.2/include/openjpeg-2.1
--enable-nonfree
--enable-vda

ERROR: freetype2 not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
ffmpeg requiring old libx264 https://github.com/Homebrew/homebrew-core/issues/5844
Failed in installing ffmpeg
```


https://gist.github.com/866f31bdd13e018c87077cd227376054

Cheers!

**Comment by MikeMcQuaid** [comment]
Is `freetype` installed? If not do `brew install freetype ffmpeg` and try again.

**Comment by xinaesthete** [comment]
`Warning: freetype-2.7 already installed`.  I think I had tried that earlier, but was worth trying again after the bundle stuff.

**Comment by MikeMcQuaid** [comment]
You may need to do a `brew reinstall openjpeg`. Also, if you haven't run `brew update` recently do that too.

**Comment by xinaesthete** [comment]
No dice I'm afraid.  May as well dump another one of these: https://gist.github.com/ab2fd0594068a178adf55f161a884f30

**Comment by MikeMcQuaid** [comment]
@xinaesthete You need to `brew update --force` (twice) and then reinstall everything again, sorry. You hit a bug that was only for a small numbers of people today.

**Comment by xinaesthete** [comment]
Brilliant, working now.  Many thanks @MikeMcQuaid
