### ISSUE TITLE
Openconnect formula broken due to missing resource at given URL 

### ISSUE THREAD

**Issue by jgraciahlrs** [Homebrew/homebrew-core#58702]
- [ X] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing formula openconnect

## What happened (include command output)
Downloading resources/dependencies failed.

<details>
  <summary>Command output</summary>
  <pre>
brew install openconnect

==> Downloading http://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob_plain
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 3ddd9d6b46e92d76e6e26d89447e3a82d797ecda125d31792f14c203742dea0f
  Actual: f4cc1633f9758ddc931d8ceeaba288194e9657765286a83cd323723f48a27bc1
  </pre>
</details>

## What you expected to happen
Download the resource `vpnc-script` as per 
```
$ grep -A 4 "resource \"vpnc-script" /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openconnect.rb 
  resource "vpnc-script" do
    url "http://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob_plain/c0122e891f7e033f35f047dad963702199d5cb9e:/vpnc-script"
    sha256 "3ddd9d6b46e92d76e6e26d89447e3a82d797ecda125d31792f14c203742dea0f"
  end
```
However, the given URL does not work, more specifically the repo `dwmw2/vpnc-scripts.git/` seems to have disappeared. curl returns a listing of projects on the server, not the expected resource. 

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install openconnect

**Comment by SMillerDev** [comment]
Upstream seems to have removed this file. Their documentation is now also broken because of this. Could you create an issue with the openconnect project and link it here?

**Comment by jgraciahlrs** [comment]
Opened an issue at upstream: 
https://gitlab.com/openconnect/openconnect/-/issues/170

**Comment by jgraciahlrs** [comment]
Missing/broken repo was reinstated at upstream. Solves issue.
