### ISSUE TITLE
bison 3.7 fails to build, Ubuntu 16.04.6 LTS and on macOS

### ISSUE THREAD

**Issue by thbtppl** [Homebrew/homebrew-core#58819]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Update packages with `brew upgrade`, including `bison` 

configure stage seems ok but `make install` failed

<details>
  <summary>Command output</summary>
  <pre>

```
==> Upgrading bison 3.6.4 -> 3.7 
==> Downloading https://ftp.gnu.org/gnu/bison/bison-3.7.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/disk1/tappel/.linuxbrew/Cellar/bison/3.7
brew info bison
==> make install
Last 15 lines from /home/tappel/.cache/Homebrew/Logs/bison/02.make:
  CC       lib/libbison_a-printf-args.o
  CC       lib/libbison_a-printf-parse.o
  CC       lib/libbison_a-vasnprintf.o
  AR       lib/libbison.a
  CCLD     src/bison
/disk1/tappel/.linuxbrew/bin/ld: src/bison-complain.o: in function `complains':
complain.c:(.text+0x756): undefined reference to `ostream_printf'
/disk1/tappel/.linuxbrew/bin/ld: complain.c:(.text+0x7ef): undefined reference to `styled_ostream_set_hyperlink'
/disk1/tappel/.linuxbrew/bin/ld: complain.c:(.text+0x813): undefined reference to `styled_ostream_set_hyperlink'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4328: src/bison] Error 1
make[2]: Leaving directory '/tmp/bison-20200728-41019-txmr08/bison-3.7'
make[1]: *** [Makefile:9050: install-recursive] Error 1
make[1]: Leaving directory '/tmp/bison-20200728-41019-txmr08/bison-3.7'
make: *** [Makefile:9511: install] Error 2

```

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install bison`

Gist link: [https://gist.github.com/69644d0b2c75ce163c78d6b8cd98c39c](https://gist.github.com/69644d0b2c75ce163c78d6b8cd98c39c)

**Comment by iMichka** [comment]
I transferred the issue to the homebrew-core repository as it will be fixed there first.

**Comment by 846047144** [comment]
./configure --prefix=/usr/local/Cellar/bison/3.7
==> make install
Last 15 lines from /Users/mzx/Library/Logs/Homebrew/bison/02.make:
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/libbison.a(libbison_a-u8-uctomb.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/libbison.a(libbison_a-wctype-h.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/libbison.a(libbison_a-gl_xlist.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: lib/libbison.a(libbison_a-xsize.o) has no symbols
  CCLD     src/bison
Undefined symbols for architecture x86_64:
  "_ostream_printf", referenced from:
      _complains in bison-complain.o
  "_styled_ostream_set_hyperlink", referenced from:
      _complains in bison-complain.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/bison] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by fxcoudert** [comment]
We can depend on gettext 0.21, or wait for upstream to fix the bug in bison 3.7.1 (as announced in https://lists.gnu.org/archive/html/bug-bison/2020-07/msg00043.html)

**Comment by alebcay** [comment]
Just as a side note, the flags in `configure` do not properly disable `gettext` support (i.e. `--without-libtextstyle-prefix` does nothing at the moment - if present, `bison` 3.7 will still link to `gettext` 0.21).

**Comment by alebcay** [comment]
`bison` 3.7.1 has been released but despite passing `--without-libintl-prefix` and `--without-libtextstyle-prefix`, `gettext` components still seem to get linked in if present. Could someone please try and confirm?

**Comment by miccal** [comment]
@alebcay apologies in advance -- I submitted https://github.com/Homebrew/homebrew-core/pull/59052 before I saw your above comment, and it has been merged.

**Comment by alebcay** [comment]
No worries. It's not like the upgrade is causing a further regression - at least the source builds now. It's just a matter of the `gettext` linkage that we need to look into still.
