### ISSUE TITLE
brew install hhvm results in error 2 on os x el captain 10.11.6

### ISSUE THREAD

**Issue by Haszprus** [Homebrew/homebrew-core#5882]
Hi,

I need to set up hhvm on my machine. I tried to brew install hhvm but it resulted in the following error:

[ 10%] Built target hack
make: *** [all] Error 2

Gist: https://gist.github.com/865b5f31ab828f59d0d3a0b17829e9c8

My brew is up to date and I've addressed the only issue that the brew doctor found (it was just a missing documentation anyways)

Thank you for your help in advance.

**Comment by MikeMcQuaid** [comment]
Please report this to the hhvm/hhvm tap.
