### ISSUE TITLE
Replace meson-internal with meson

### ISSUE THREAD

**Issue by SeekingMeaning** [Homebrew/homebrew-core#58943]
See #43437

> As the original author of this formula, my recommendation is to keep this formula for now. My plan is to gradually replace formulas that are currently using it, to use the regular meson instead, when an update for them becomes available. This approach has led to me being able to remove most of them already.
> 
> For this switch to the regular meson to be possible, the meson build scripts of the package may need to be updated: I have been adding patches for this whenever necessary, which are then accepted upstream.
> 
> It should certainly not be used for new formulas.

Also note: https://github.com/Homebrew/homebrew-core/pull/59740#issuecomment-674818674

> > `libjson-glib-1.0.0.dylib provides version 0.0.0`
> 
> This is a bug and should be fixed before migrating away from `meson-internal`. `meson-internal` is a workaround for this very bug.
> 
> For any migration away from `meson-internal`, please verify the output of `otool -L` - do not rely on the CI to do so for you as some formulae have no dependents.

Remaining dependents:

| Formula | PR | Merged? |
| :--- | :---: | :---: |
| `json-glib` | #60986 | :white_check_mark: |
| `libgusb` | #58926 | :white_check_mark: |
| `libgxps` | #59741 | :white_check_mark: |
| `libhttpseverywhere` | #59742 | :white_check_mark: |
| `libmpdclient` | #58939 | :white_check_mark: |
| `mesa` |  #61750 | ✅  |

**Comment by dtrodrigues** [comment]
@SeekingMeaning @chenrui333 can this be closed now that the update to `mesa` was merged and the `meson-internal` formula removed?

**Comment by alebcay** [comment]
I think we should also deprecate/disable/remove the `meson-internal` formula prior to closing this. At the moment, `meson-internal` still exists as a regular formula.

**Comment by tschoonj** [comment]
IMHO the time has come to remove the `meson-internal` formula. No one should be using this anymore.
