### ISSUE TITLE
gnuradio bottles failing, build from source failing

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#58983]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Issue

During testing of GCC it became apparent that:
- none of the bottles for gnuradio can be found (on 10.15, 10.14 and 10.13)

```
==> brew fetch --retry gnuradio
==> FAILED
==> Downloading https://homebrew.bintray.com/bottles/gnuradio-3.7.13.4_15.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
```

- gnuradio does not build from source, without hundreds of doxygen errors:

```
error: problems opening map file /private/tmp/gnuradio-20200801-87594-1lhw0c2/gnuradio-3.7.13.4/build/docs/doxygen/html/vector__sink__b_8h__incl.map for inclusion in the docs!
If you installed Graphviz/dot after a previous failing run, 
try deleting the output directory and rerun doxygen.
error: problems opening map file /private/tmp/gnuradio-20200801-87594-1lhw0c2/gnuradio-3.7.13.4/build/docs/doxygen/html/vector__sink__c_8h__incl.map for inclusion in the docs!
```

See this job https://github.com/Homebrew/homebrew-core/pull/58455/checks?check_run_id=935005535 for detailed output.

**Comment by jonchang** [comment]
We're updating gnuradio aren't we? https://github.com/Homebrew/homebrew-core/pull/58818

**Comment by fxcoudert** [comment]
Does not explain why the bottles would have disappeared.

**Comment by SMillerDev** [comment]
Can you see them in bintray?

**Comment by jonchang** [comment]
Ah, this was probably due to the recent bintray outage. Let me check the merge from around that time.

**Comment by fxcoudert** [comment]
They're not in bintray. The merge of the revision bump was de49e72d3c383616fd0a7c8695760139cd8cef50 but no bottles were committed.

**Comment by jonchang** [comment]
Looks like bottles were never built in https://github.com/Homebrew/homebrew-core/pull/53874. We should merge #58818 as soon as possible to address this since the current version of gnuradio fails to build from source.
