### ISSUE TITLE
brew install ponyc failed to install llvm on macOS 10.12

### ISSUE THREAD

**Issue by tony-austin** [Homebrew/homebrew-core#5900]
refer:
https://github.com/Homebrew/homebrew-core/issues/5346

event:
brew install ponyc

==> Installing dependencies for ponyc: llvm

==> Installing ponyc dependency: llvm

==> Using the sandbox

==> Downloading http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/cfe-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--clang-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/clang-tools-extra-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--clang-extra-tools-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/openmp-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--openmp-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/libcxx-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--libcxx-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/libunwind-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--libunwind-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/lld-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--lld-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/polly-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--polly-3.8.1.tar.xz

==> Downloading http://llvm.org/releases/3.8.1/compiler-rt-3.8.1.src.tar.xz

Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--compiler-rt-3.8.1.tar.xz

==> cmake -G Unix Makefiles /private/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/Users/tony/brew/Cellar/llvm/3.8.1 -DCMAKE_BUILD_TYPE=Re

==> make

Last 15 lines from /Users/tony/Library/Logs/Homebrew/llvm/02.make:

[ 21%] Building CXX object tools/lld/lib/ReaderWriter/MachO/CMakeFiles/lldMachO.dir/ShimPass.cpp.o

cd /tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO && /Users/tony/brew/Library/Homebrew/shims/super/clang++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/.  -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -DNDEBUG     -o CMakeFiles/lldMachO.dir/ShimPass.cpp.o -c /tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/ShimPass.cpp

[ 21%] Building CXX object tools/lld/lib/ReaderWriter/MachO/CMakeFiles/lldMachO.dir/StubsPass.cpp.o

cd /tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO && /Users/tony/brew/Library/Homebrew/shims/super/clang++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/.  -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -DNDEBUG     -o CMakeFiles/lldMachO.dir/StubsPass.cpp.o -c /tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/StubsPass.cpp

[ 21%] Building CXX object tools/lld/lib/ReaderWriter/MachO/CMakeFiles/lldMachO.dir/TLVPass.cpp.o

cd /tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO && /Users/tony/brew/Library/Homebrew/shims/super/clang++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/.  -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -DNDEBUG     -o CMakeFiles/lldMachO.dir/TLVPass.cpp.o -c /tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/TLVPass.cpp

[ 21%] Building CXX object tools/lld/lib/ReaderWriter/MachO/CMakeFiles/lldMachO.dir/WriterMachO.cpp.o

cd /tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO && /Users/tony/brew/Library/Homebrew/shims/super/clang++   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/tools/lld/include -I/tmp/llvm-20161014-62709-y6ibe3/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/include -I/tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/.  -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -std=c++11 -DNDEBUG     -o CMakeFiles/lldMachO.dir/WriterMachO.cpp.o -c /tmp/llvm-20161014-62709-jkahtw/llvm-3.8.1.src/tools/lld/lib/ReaderWriter/MachO/WriterMachO.cpp

[ 21%] Linking CXX static library ../../../../../lib/liblldMachO.a

cd /tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO && /Users/tony/brew/Cellar/cmake/3.6.2/bin/cmake -P CMakeFiles/lldMachO.dir/cmake_clean_target.cmake

cd /tmp/llvm-20161014-62709-y6ibe3/tools/lld/lib/ReaderWriter/MachO && /Users/tony/brew/Cellar/cmake/3.6.2/bin/cmake -E cmake_link_script CMakeFiles/lldMachO.dir/link.txt --verbose=1

/usr/bin/ar qc ../../../../../lib/liblldMachO.a  CMakeFiles/lldMachO.dir/ArchHandler.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_arm64.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86.cpp.o CMakeFiles/lldMachO.dir/ArchHandler_x86_64.cpp.o CMakeFiles/lldMachO.dir/CompactUnwindPass.cpp.o CMakeFiles/lldMachO.dir/GOTPass.cpp.o CMakeFiles/lldMachO.dir/LayoutPass.cpp.o CMakeFiles/lldMachO.dir/MachOLinkingContext.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryReader.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileBinaryWriter.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileFromAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileToAtoms.cpp.o CMakeFiles/lldMachO.dir/MachONormalizedFileYAML.cpp.o CMakeFiles/lldMachO.dir/ShimPass.cpp.o CMakeFiles/lldMachO.dir/StubsPass.cpp.o CMakeFiles/lldMachO.dir/TLVPass.cpp.o CMakeFiles/lldMachO.dir/WriterMachO.cpp.o

/usr/bin/ranlib ../../../../../lib/liblldMachO.a

[ 21%] Built target lldMachO

make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

If reporting this issue please do so at (not Homebrew/brew):

  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:

llvm 3.9.0 https://github.com/Homebrew/homebrew-core/pull/4579

llvm --HEAD must require xcode https://github.com/Homebrew/homebrew-core/pull/4651

llvm 3.8.0 fails to upgrade on 10.11.5 with Xcode 8.0 command line tools https://github.com/Homebrew/homebrew-core/issues/3030

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do this.

**Comment by tony-austin** [comment]
'''
NZLCMAC16:~ tony$ brew update
Already up-to-date.
NZLCMAC16:~ tony$ brew update
Already up-to-date.
NZLCMAC16:~ tony$ brew doctor
Your system is ready to brew.
NZLCMAC16:~ tony$ brew install ponyc
==> Installing dependencies for ponyc: llvm
==> Installing ponyc dependency: llvm
==> Using the sandbox
==> Downloading http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/cfe-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--clang-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/clang-tools-extra-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--clang-extra-tools-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/openmp-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--openmp-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/libcxx-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--libcxx-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/libunwind-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--libunwind-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/lld-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--lld-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/polly-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--polly-3.8.1.tar.xz
==> Downloading http://llvm.org/releases/3.8.1/compiler-rt-3.8.1.src.tar.xz
Already downloaded: /Users/tony/Library/Caches/Homebrew/llvm--compiler-rt-3.8.1.tar.xz
==> cmake -G Unix Makefiles /private/tmp/llvm-20161016-87294-1rj2t1i/llvm-3.8.1.src -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAK
==> make
Last 15 lines from /Users/tony/Library/Logs/Homebrew/llvm/02.make:
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(parityti2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(popcountti2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(powitf2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(subvti3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(subtf3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(trampoline_setup.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(ucmpti2.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(udivmodti4.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(udivti3.c.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libclang_rt.builtins_i386_10.4.a(umodti3.c.o) has no symbols
[  7%] Built target clang_rt.builtins_i386_10.4
make[3]: *** [all] Error 2
make[2]: *** [tools/clang/runtime/compiler-rt-stamps/compiler-rt-build] Error 2
make[1]: *** [tools/clang/runtime/CMakeFiles/compiler-rt.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
llvm 3.9.0 https://github.com/Homebrew/homebrew-core/pull/4579
brew install ponyc failed to install llvm on macOS 10.12 https://github.com/Homebrew/homebrew-core/issues/5900
llvm 3.8.0 fails to upgrade on 10.11.5 with Xcode 8.0 command line tools https://github.com/Homebrew/homebrew-core/issues/3030
'''

**Comment by tony-austin** [comment]
`NZLCMAC16:/ tony$ hash -l |egrep "llvm-gcc|clang"
builtin hash -p /usr/bin/clang clang
builtin hash -p /usr/bin/llvm-gcc llvm-gcc
NZLCMAC16:/ tony$ ls -l /usr/bin/llvm-gcc
lrwxr-xr-x  1 root  wheel  5 21 Sep 18:29 /usr/bin/llvm-gcc -> clang
NZLCMAC16:/ tony$ /usr/bin/clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by ilovezfs** [comment]
Please `brew uninstall llvm` first.

**Comment by tony-austin** [comment]
```NZLCMAC16:~ tony$ brew uninstall llvm
Error: No such keg: /Users/tony/brew/Cellar/llvm```

**Comment by ilovezfs** [comment]
Please brew update and try again with the latest llvm and ponyc

**Comment by tony-austin** [comment]
My Cellar was configured to /Users/tony/brew/Cellar; have moved it to /usr/local/Cellar; re-linked a lot of kegs, and ran brew prune. Ran brew doctor again. Ran brew install ponyc, had to remove old ponyc ( was installed from source ) from /usr/local/bin. Ran brew link --overwrite. Ran brew update twice and brew doctor again, all clean now. This installed ponyc version 0.6.0_1 with llvm 3.9.0. Thanks for your patience and help. This may now be closed.

**Comment by ilovezfs** [comment]
@tony-austin excellent. Glad you got it working!
