### ISSUE TITLE
"brew update" destroyed my "brew" executable!

### ISSUE THREAD

**Issue by astavely** [Homebrew/homebrew-core#59048]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x ]if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew update

## What happened (include command output)

The command failed with the output as shown below.  After that, "brew upgrade glib" or "brew install glib" or "brew doctor" or "brew update" or "brew _anything else_" gives me:

-bash: /usr/local/bin/brew: No such file or directory

My /usr/local/Cellar directory is still there and appears to be undamaged.

I'm running Mac OS X version 10.11.6.  I last ran "brew" yesterday and it worked normally.
<details>
  <summary>Command output</summary>
  <pre>

warning: unable to unlink .gitignore: Permission denied
warning: unable to unlink .yardopts: Permission denied
warning: unable to unlink CODEOFCONDUCT.md: Permission denied
warning: unable to unlink CONTRIBUTING.md: Permission denied
warning: unable to unlink LICENSE.txt: Permission denied
warning: unable to unlink SUPPORTERS.md: Permission denied
error: unable to unlink old 'README.md' (Permission denied)
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master

  </pre>
</details>

## What you expected to happen

brew should have worked as normal after the "update" command.  It has worked fine for me until now.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew update
brew _anything_

**Comment by SMillerDev** [comment]
This is not about a formula so it shouldn't be here, and it's on an unsupported macOS version so it should not even be on github. You can make a post on discourse.brew.sh to see if anyone wants to help.
