### ISSUE TITLE
sierra: gnuplot 5.0.5 fails to compile

### ISSUE THREAD

**Issue by silberzwiebel** [Homebrew/homebrew-core#5904]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I've updated from OS X 10.7.5 to macOS 10.12 sierra and facing a build problem while updating gnuplot to 5.0.5:

```
In file included from term.c:1202:
In file included from ./term.h:410:
../term/cairo.trm:89:10: fatal error: 'glib.h' file not found
#include "glib.h"               /* For guint32 */
         ^
1 error generated.
make[4]: *** [term.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

[Here is the build-log.](https://gist.github.com/b7a857c4578798667b391496363c8cea)

**Comment by MikeMcQuaid** [comment]
Is `glib` installed? What options is it being installed with? Thanks!

**Comment by silberzwiebel** [comment]
The problem was fixed by uninstalling everything installed with homebrew and then re-installing the necessary packages (see https://github.com/Homebrew/homebrew-core/issues/5905).
