### ISSUE TITLE
sierra: c++ cgal-project fails to link to mpfr

### ISSUE THREAD

**Issue by silberzwiebel** [Homebrew/homebrew-core#5905]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I've updated my mac to sierra 10.12 from os x 10.7.5 a few days ago. I'm using cgal 4.9 installed via homebrew with a c++ project.
Before I updated the mac, my project compiled fine. Now the same commands (cmake & make) result in a link error:
```
[100%] Linking CXX executable sl-model
ld: warning: directory not found for option '-L/Users/username/Documents/sl-model/@@HOMEBREW_PREFIX@@/lib'
ld: library not found for -l@@HOMEBREW_PREFIX@@/lib/libmpfr.dylib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sl-model] Error 1
make[1]: *** [CMakeFiles/sl-model.dir/all] Error 2
make: *** [all] Error 2
```

sl-model is the name of the project.

**Comment by MikeMcQuaid** [comment]
Please `brew reinstall libmpfr` and try again. Also, in future please follow the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by silberzwiebel** [comment]
Thanks for the quick reply.

```
$brew reinstall libmpfr
Error: No available formula with the name "libmpfr"
$ brew reinstall mpfr
==> Reinstalling mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-3.1.5.sierra.bottle.tar.gz
Already downloaded: /Users/thomas_admin/Library/Caches/Homebrew/mpfr-3.1.5.sierra.bottle.tar.gz
==> Pouring mpfr-3.1.5.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/3.1.5: 25 files, 3.6M
```

Didn't help with the problem, unfortunately (I tried this also before but didn't report, sorry.)
 
I ran `brew update` more than twice, didn't help. `brew doctor` says `Your system is ready to brew.`. As suggested in the [Common Issues](https://github.com/Homebrew/brew/blob/master/docs/Common-Issues.md), I also did
```
xcode-select --install
brew upgrade
```

This resulted in two build failures, reported [here](https://github.com/Homebrew/homebrew-core/issues/5904) and [here](https://github.com/Homebrew/homebrew-tex/issues/33). As they are not related to CGAL (at least, I do not think so), I filed this issue before the other two are resolved.
I just started Xcode (I do have 8.0) and it installed some more stuff. Unfortunately, this also did not help me with my issue (I did everything several times all over, i.e., deleted the build folder, make clean, brew reinstall ..., etc.)

**Comment by MikeMcQuaid** [comment]
> Didn't help with the problem, unfortunately (I tried this also before but didn't report, sorry.)

You saw the identical errors afterwards? If so, you may need to uninstall/reinstall everything unfortunately with `brew bundle dump && brew uninstall --force $(brew list) && brew bundle`.

**Comment by dunn** [comment]
Any luck?

**Comment by silberzwiebel** [comment]
Sorry for the late reply, I had a few free days.
I ran your command @MikeMcQuaid which uninstalled everything installed by homebrew. The reinstallation didn't work, though:
```
> brew bundle
Error: Invalid Brewfile: (eval):165: syntax error, unexpected tIDENTIFIER, expecting end-of-input
cask '==> We'll set permissions properly so ...
```

But this is not a big deal, I think I installed too much anyway. I then reinstalled `cgal` and some other necessary packages and now my project compiles again.
Thanks for the help!

**Comment by MikeMcQuaid** [comment]
CC @Homebrew/cask Is there a way to coax `brew cask` first-run output so it's not on stdout?

**Comment by MikeMcQuaid** [comment]
Glad you got sorted @silberzwiebel!

**Comment by jawshooah** [comment]
@MikeMcQuaid Even better: https://github.com/Homebrew/brew/issues/1332
