### ISSUE TITLE
The pcl library installed by "brew install pcl" can not be used.

### ISSUE THREAD

**Issue by crissallan** [Homebrew/homebrew-core#59064]
## What you were trying to do (and why)
I want to use the pcl library(PointCloudLibrary) on my MacBook. So I install the pcl and all dependcies by using homebrew.
However, once I "#include" the header files from the pcl library, it would raise error.

I think the problem is caused by the "boost" library (version 1.73.0) which is also installed by using homebrew. e.g. the boost library of version 1.73.0 doesn't have the endian.hpp file in include/boost/detail/, but in version 1.72.0.

But the pcl of homebrew can only be supported by the boost with version 1.73.0.

## What happened (include command output)

`#include <iostream>`
`#include <pcl/io/pcd_io.h>`
`#include <pcl/point_types.h>`
`#include <pcl/registration/icp.h>`

`int main (int argc, char** argv)`
`{`
    `pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_in (new pcl::PointCloud<pcl::PointXYZ>);`
    `pcl::PointCloud<pcl::PointXYZ>::Ptr cloud_out (new pcl::PointCloud<pcl::PointXYZ>);`
    `return 0;`
`}`

  <summary> /usr/local/include/boost/detail/endian.hpp:9:10: fatal error: 'boost/predef/detail/endian_compat.h' file not found </summary>
  <pre>

## Step-by-step reproduction instructions (by running `brew install` commands)

'brew install pcl'

Then build a test project for pcl, fill the CMakeList.txt as below:

`cmake_minimum_required(VERSION 2.6)`
`project(ProcessPointCloud)`

`set(CMAKE_CXX_STANDARD 11)`

`message("msg" ${CMAKE_FRAMEWORK_PATH})`

`set(PCL_DIR "/usr/local/Cellar/pcl/1.9.1_9.reinstall/share/pcl-1.9/")`
`find_package(PCL 1.9 REQUIRED)`

`include_directories(${PCL_INCLUDE_DIRS})`
`link_directories(${PCL_LIBRARY_DIRS})`
`add_definitions(${PCL_DEFINITIONS})`

`add_executable(ProcessPointCloud main.cpp)`

`target_link_libraries(ProcessPointCloud ${PCL_LIBRARIES})`

Then run the c++ code above in main.cpp

**Comment by dtrodrigues** [comment]
The current version of `pcl` is version `1.9.1`, which looks like it doesn't support Boost 1.73. `endian_compat.h` was removed in https://github.com/boostorg/predef/commit/aa6e232bf170ad8b856aff9e7c70334f77441c7f, between Boost 1.72 and Boost 1.73.

The current PR to upgrade pcl is at https://github.com/Homebrew/homebrew-core/pull/59146, and should resolve this issue.
