### ISSUE TITLE
uwsgi: failed to run with --http key

### ISSUE THREAD

**Issue by achikin** [Homebrew/homebrew-core#5908]
```
brew install uwsgi --with-python
uwsgi --plugin python,http --http :9000 --wsgi-file myapp/wsgi.py
!!! UNABLE to load uWSGI plugin: dlopen(/usr/local/Cellar/uwsgi/2.0.14/libexec/uwsgi/http_plugin.so, 10): Symbol not found: _uwsgi_opt_corerouter
  Referenced from: /usr/local/Cellar/uwsgi/2.0.14/libexec/uwsgi/http_plugin.so
  Expected in: dynamic lookup
 !!!
uwsgi: option `--http' is ambiguous
getopt_long() error
```

gist-logs https://gist.github.com/d85cccc0c420e5854076c8811155b6fd

**Comment by MikeMcQuaid** [comment]
What happens if you install without `--with-python`, can you try that? What does `brew test uwsgi` output?

**Comment by achikin** [comment]
→ brew test uwsgi
Testing uwsgi
==> Using the sandbox
*** Starting uWSGI 2.0.14 (64bit) on [Sat Oct 15 01:20:14 2016] ***
compiled with version: 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38) on 14 October 2016 14:11:14
os: Darwin-15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64
nodename: moo
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /private/tmp/uwsgi-test-20161015-56697-1n3e7e0
detected binary path: /usr/local/Cellar/uwsgi/2.0.14/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 4864
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8080 fd 3
Python version: 2.7.12 (default, Oct 11 2016, 05:24:00)  [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x7f83295055d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72760 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7f83295055d0 pid: 56705 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 56705, cores: 1)
==> curl localhost:8080
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[pid: 56705|app: 0|req: 1/1] 127.0.0.1 () {24 vars in 245 bytes} [Sat Oct 15 01:20:16 2016] GET / => generated 11 bytes in 0 msecs (HTTP/1.1 200) 1 headers in 44 bytes (2 switches on core 0)
100    11    0    11    0     0   1800      0 --:--:-- --:--:-- --:--:--  2200

**Comment by achikin** [comment]
Same result when installing without python

**Comment by dunn** [comment]
Can you try building uwsgi outside of Homebrew and see if this still occurs?

**Comment by achikin** [comment]
1) downloaded latest stable version 2.0.14(same as in brew) from here https://projects.unbit.it/downloads/uwsgi-2.0.14.tar.gz
```
-> make
......
ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
*** error linking uWSGI ***
make: *** [all] Error 1
```
I've created a new issue in uwsgi about this https://github.com/unbit/uwsgi/issues/1389

**Comment by achikin** [comment]
https://github.com/unbit/uwsgi/issues/1364

**Comment by achikin** [comment]
I've managed to build it from source adding `xml = expat` line to buildconf/default.ini and now my default.ini looks like this
```
[uwsgi]
main_plugin = python,gevent
inherit = base
xml = expat
```
The issue does not reproduce with built from source version.

**Comment by achikin** [comment]
Any updates on the issue?

**Comment by MikeMcQuaid** [comment]
@achikin No, sorry. We'll accept a pull request for a patch, fix or new upstream release.

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.
