### ISSUE TITLE
Deprecating old taps in favour of core repository

### ISSUE THREAD

**Issue by Leandros** [Homebrew/homebrew-core#5909]
Recently we've added `tldr` to the homebrew core repositories, which formerly lived in it's own [tap](https://github.com/tldr-pages/homebrew-tldr). 

We've cleaned up a little and remove said tap, but since we have received reports from users that `tldr` is gone (specifically https://github.com/tldr-pages/tldr/issues/1118).

How can we properly deprecate the tap and point users automatically, even those who still have the tap registered, to the core? I was of the assumption this is already done, if this isn't the case, is there an official way?

**Comment by MikeMcQuaid** [comment]
If people do `brew install tldr` it'll work fine but `brew install tldr/tldr/tldr` (or whatever your tap is called) will fail. This issue is pretty good timing as this is on my list of things to look at imminently.

**Comment by Leandros** [comment]
Sweet. How is update/upgrade handled in the case of the sudden missing of a tap?

**Comment by MikeMcQuaid** [comment]
`update` will say it's deleted if it's just the formula, Git will probably complain if the repo doesn't exist and `upgrade` will never show a new version, I think.

**Comment by Leandros** [comment]
If that's the case, that would confirm the reports of our users.
This specific user was getting a git error:

```
Error: Fetching /usr/local/Homebrew/Library/Taps/tldr-pages/homebrew-tldr failed!
```

Thanks for looking into it! 🏆

**Comment by MikeMcQuaid** [comment]
@Leandros I'd advise recreating the repo for now until this issue details that has been addressed.

**Comment by MikeMcQuaid** [comment]
@Leandros Actually, the new fix will also involve you have a repo present that it uses to redirect people to the new formula so I'd advise keeping it around indefinitely, disabling issues and noting in the README it's deprecated and what to do instead.

**Comment by MikeMcQuaid** [comment]
@Leandros You can now migrate your tap and users will get "nagged" in https://github.com/Homebrew/brew/pull/1371 (not in a tagged release but coming soon). You'll still need to keep your tap around for now but can update the README to note it being deprecated.
