### ISSUE TITLE
gdb failure on macOS Sierra

### ISSUE THREAD

**Issue by caipre** [Homebrew/homebrew-core#5912]
Ran into this problem today. Running `gdb` on a binary quits with message:
 >  During startup program terminated with signal ?, Unknown signal.

This is an open bug in gdb upstream: https://sourceware.org/bugzilla/show_bug.cgi?id=20266
A workaround is to disable SIP, as discussed here: https://sourceware.org/ml/gdb/2016-10/msg00009.html

Should we add a message in the caveats section for Sierra users?

**Comment by MikeMcQuaid** [comment]
Does it not work with SIP at all? We won't recommend disabling SIP to end-users as it's a security feature.

**Comment by caipre** [comment]
In fact, the proposed workaround doesn't work for me (macOS Sierra 10.12.1 Beta). I tried `csrutil enable --without debug`, as suggested in the mailing list, as well as with SIP fully disabled. Same error in both cases.

Closing, as this seems like it has to be fixed by Apple or gdb upstream.

**Comment by Salamit** [comment]
This resolved the issue for me: http://stackoverflow.com/questions/39702871/gdb-kind-of-doesnt-work-on-macos-sierra/40437725#40437725

**Comment by dsantosp12** [comment]
@Salamit this is not solving the issue for me. I tried writing set startup-with-shell off to a .gdbinit located in my ~/ and it is not working. Any other ideas?

**Comment by Salamit** [comment]
If you followed instructions as in the video then I'm sorry, that is all I've got.
