### ISSUE TITLE
brew install cgal 5.0.3_1 does not exit 0

### ISSUE THREAD

**Issue by VincentRouvreau** [Homebrew/homebrew-core#59131]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to `brew install graphviz doxygen boost eigen gmp mpfr tbb cgal ` because my software is built on top of these guys.

## What happened (include command output)

Since cgal is now version 5.0.3_1, brew install cgal exit with a code status that is no more 0 but 1. It makes my [CI fails](https://github.com/VincentRouvreau/brew_github_actions/runs/943880283).
```
==> Installing cgal
==> Pouring cgal-5.0.3_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/cgal/5.0.3_1: 3,343 files, 34.9MB
##[error]Process completed with exit code 1.
```
Please find below a github actions like yml to reproduce the issue:

<details>
  <summary>Command output</summary>
  <pre>

name: brew install

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  build:
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']
    name: Build wheels for Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          brew update
          brew install boost eigen gmp mpfr cgal

  </pre>
</details>

## What you expected to happen

`brew install boost eigen gmp mpfr cgal` shall exit a 0 status code.
By the way, cgal is perfectly installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install boost eigen gmp mpfr cgal
echo $?

## Comments
* I tried this command on a MacOSx catalina virtual machine but it returns the correct exit status
* I had the same issue on Azure pipeline with OSx 10.14
* macos-latest means 10.15 on github actions

**Comment by SMillerDev** [comment]
We can't debug just based on your CI settings. Please provide the information in the checkboxes on the top of the template. The issue can be reopened after.
