### ISSUE TITLE
"az" command from azure-cli fails due to file permissions

### ISSUE THREAD

**Issue by LnxGnome** [Homebrew/homebrew-core#59215]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ Yes ] ran `brew update` and can still reproduce the problem?
- [ Yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ Wants OS update, can't do right now... ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
$ brew gist-logs azure-cli
Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

(no other output)

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
$ brew config
HOMEBREW_VERSION: 2.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 85250e720999af2009cdf2128d66bd30b75423ab
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_261, 1.6.0_65-b14-466.1
macOS: 10.15.5-x86_64
CLT: 11.0.33.17
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:  <<-- from Yubikey and WKHTMLTOX software, not brew.
  /usr/local/lib/libcrypto.1.0.0.dylib
  /usr/local/lib/libcrypto.dylib
  /usr/local/lib/libjson-c.2.dylib
  /usr/local/lib/libwkhtmltox.0.12.6.dylib
  /usr/local/lib/libykclient.3.dylib
  /usr/local/lib/libykcs11.1.dylib
  /usr/local/lib/libykcs11.dylib
  /usr/local/lib/libykpers-1.1.dylib
  /usr/local/lib/libykpiv.1.dylib
  /usr/local/lib/libykpiv.dylib
  /usr/local/lib/libyubikey.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  python@3.8
  gnupg

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/lib/docker/cli-plugins

## What you were trying to do (and why)

Run "az" command as a user that was not the installer of brew.

## What happened (include command output)

User that has installed brew does not generate any error.   Any other user generates `PermissionError`:  error.  It is cause by file permissions.

<details>
  <summary>Command output</summary>
  <pre>
user2% az
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
....
  File "/usr/local/Cellar/azure-cli/2.9.1/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1626, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/local/Cellar/azure-cli/2.9.1/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/PKG-INFO'
</pre>

<pre>
user2% find /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info -ls
11826494        0 drwxr-xr-x    8 admin         staff                 256 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info
11826495        8 -rw-------    1 admin         staff                 889 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/PKG-INFO
11826496       16 -rw-r--r--    1 admin         staff                4711 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/installed-files.txt
11826497        8 -rw-------    1 admin         staff                2659 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/SOURCES.txt
11826498        8 -rw-------    1 admin         staff                  26 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/requires.txt
11826499        8 -rw-------    1 admin         staff                  18 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/top_level.txt
11826500        8 -rw-------    1 admin         staff                   1 Jul 31 04:06 /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/dependency_links.txt
  </pre>
</details>

## What you expected to happen

File permissions should be set so that any user can run the 'az' command without this error.

<details>
<summary>example</summary>
<pre>
user2% az
     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|

Welcome to the cool new Azure CLI!
</pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)
<pre>
admin$ brew install azure-cli
admin$ az
     /\
    /  \    _____   _ _  ___ _
   / /\ \  |_  / | | | \'__/ _\
  / ____ \  / /| |_| | | |  __/
 /_/    \_\/___|\__,_|_|  \___|

Welcome to the cool new Azure CLI!
</pre>
....
(log in as other user)
....
<pre>
user2% az
Traceback (most recent call last):
(displays traceback, as in Command Output above)
</pre>

This was fixed by setting group permissions to 'read' for all files in this directory (admin$ chmod g+r /usr/local/Cellar/azure-cli/2.10.0/libexec/lib/python3.8/site-packages/azure_cosmos-3.1.0-py3.8.egg-info/*)

**Comment by SMillerDev** [comment]
Brew is not meant to provide multi user installs, this situation is intentional. If you want this to be different you can make a pull request and we'll review it.

**Comment by LnxGnome** [comment]
Wow, it's worked so well for years for me like this that I'm surprised.
