### ISSUE TITLE
scrcpy formula uses old version v1.14 instead of v1.15

### ISSUE THREAD

**Issue by carstenhag** [Homebrew/homebrew-core#59278]
- [x] ran `brew update` and can still reproduce the problem?
- [x] (not applicable) ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade scrcpy to the latest version v1.15 https://github.com/Genymobile/scrcpy/releases

## What happened (include command output)

Got a notice from brew upgrade, that scrcpy 1.14 is already installed.

<details>
  <summary>Command output</summary>
  <pre>
brew upgrade scrcpy

Warning: scrcpy 1.14_1 already installed

brew gist-logs scrcpy
Error: No logs.

brew config

HOMEBREW_VERSION: 2.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ed3856d30e7e818f88ec4d82e8b8444e6f10cb1f
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_MAKE_JOBS: 12
CPU: dodeca-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 12.0.1
macOS: 10.15.5-x86_64
CLT: N/A
Xcode: 11.6

  </pre>
</details>

## What you expected to happen

The scrcpy formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/scrcpy.rb is not hardcoding version numbers, but instead dynamically checking the release section or updating the latest version number in another way.

## Step-by-step reproduction instructions (by running `brew install` commands)

Well... this issue template really doesn't make sense for outdated versions :D.

**Comment by iMichka** [comment]
Please open a pull request to update the version, see https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

We rely on the community to keep most packages up to date.

**Comment by carstenhag** [comment]
Well, my issue was more about automating the version numbers, so that we don't need one PR for every future release there will ever be.

**Comment by iMichka** [comment]
I am not sure I understand your request. Can you re-explain me the issue you are seeing with other words? What commands did you use and what did you expect / what happened?

**Comment by carstenhag** [comment]
I thought homebrew formulas support github releases as in, if there's a new stable github release, a formula can make of the github api to check for the latest version and download that. Currently apparently one always needs to manually look up the new version number, hash, etc. Which seems really cumbersome. Hope that clarified my request a bit :).  ---- On Fr, 07 Aug 2020 08:58:00 +0200  notifications@github.com  wrote ----
I am not sure I understand your request. Can you re-explain me the issue you are seeing with other words? What commands did you use and what did you expect / what happened?

**Comment by iMichka** [comment]
Yes, right now it is manual.

We have the https://github.com/Homebrew/homebrew-livecheck project that is being worked on (With the support of Google Summer of Code). This allows to check for version updates automatically. We plan to automatise the opening of pull requests based on this later on.

The `brew bump-formula-pr` command does help speed things up. If you use it and the build is green; we can get your update merged in less than an hour (if a maintainer is around to review and merge the change). Which is actually not that slow :)

**Comment by SMillerDev** [comment]
There is github actions that do that. Or you can do `brew bump-formula-pr --url=url formula`
