### ISSUE TITLE
gifski: re-add video support

### ISSUE THREAD

**Issue by kornelski** [Homebrew/homebrew-core#59370]
gifski (https://github.com/Homebrew/homebrew-core/blob/master/Formula/gifski.rb) supports ffmpeg 4 now, so video support can be re-added to the formula.

Ping @whoiswillma

**Comment by whoiswillma** [comment]
I'm not sure what you mean by add video support, though I'm willing to take on the work this entails. I'm new to homebrew and esp. to processes related to homebrew-core. Perhaps @MikeMcQuaid would know what to do?

**Comment by kornelski** [comment]
Add `--features=video` to the `cargo build` args, and ffmpeg dependency.

**Comment by jonchang** [comment]
Please open a pull request for this, thanks.

**Comment by jonchang** [comment]
> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
