### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by hktalent** [Homebrew/homebrew-core#5944]
mac os x 10.12
$ brew upgrade
==> Upgrading 1 outdated package, with result:
libtorrent-rasterbar 1.1.1
==> Upgrading libtorrent-rasterbar
==> Using the sandbox
==> Downloading https://github.com/arvidn/libtorrent/releases/download/libtorren
Already downloaded: /Users/xiatian/Library/Caches/Homebrew/libtorrent-rasterbar-1.1.1.tar.gz
==> ./configure --disable-silent-rules --enable-encryption --prefix=/usr/local/C
Last 15 lines from /Users/xiatian/Library/Logs/Homebrew/libtorrent-rasterbar/01.configure:
checking python extra linking flags... -u _PyMac_Error Python.framework/Versions/2.7/Python
checking consistency of all components of python development environment... no
configure: error: in `/private/tmp/libtorrent-rasterbar-20161015-92343-1ojrd4i/libtorrent-rasterbar-1.1.1':
configure: error: 
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LIBS environment variable.
  Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

**Comment by MikeMcQuaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do.

**Comment by hktalent** [comment]
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /opt/local/bin/apr-1-config
  /opt/local/bin/apu-1-config
  /opt/local/bin/caca-config
  /opt/local/bin/croco-0.6-config
  /opt/local/bin/curl-config
  /opt/local/bin/dnet-config
  /opt/local/bin/freetype-config
  /opt/local/bin/gdlib-config
  /opt/local/bin/glib-config
  /opt/local/bin/gpg-error-config
  /opt/local/bin/gtk-config
  /opt/local/bin/gts-config
  /opt/local/bin/icu-config
  /opt/local/bin/imlib2-config
  /opt/local/bin/krb5-config
  /opt/local/bin/libgcrypt-config
  /opt/local/bin/libnet-config
  /opt/local/bin/libpng-config
  /opt/local/bin/libpng16-config
  /opt/local/bin/Magick++-config
  /opt/local/bin/Magick-config
  /opt/local/bin/MagickCore-config
  /opt/local/bin/MagickWand-config
  /opt/local/bin/ncurses6-config
  /opt/local/bin/ncursesw6-config
  /opt/local/bin/netpbm-config
  /opt/local/bin/pcap-config
  /opt/local/bin/pcre-config
  /opt/local/bin/pkg-config
  /opt/local/bin/python-config
  /opt/local/bin/python2-config
  /opt/local/bin/python2.7-config
  /opt/local/bin/uuid-config
  /opt/local/bin/Wand-config
  /opt/local/bin/xml2-config
  /opt/local/bin/xslt-config
  /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
  /opt/local/bin/
  /usr/local/bin/

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /opt/local/bin/pkg-config

`./configure` may have problems finding brew-installed packages using
this other pkg-config.

**Comment by MikeMcQuaid** [comment]
The `brew doctor` and MacPorts issues are almost certainly your problem.
