### ISSUE TITLE
[tmuxinator] Homebrew's /usr/local/bin/tmuxinator wrapper leaks GEM_HOME environment variable into the resulting tmux environment

### ISSUE THREAD

**Issue by nertzy** [Homebrew/homebrew-core#59484]
## What you were trying to do (and why)

I am using tmuxinator to maintain my tmux sessions. I am a Ruby developer and when I use my tmux sessions, I want the environment within to be correct so that I may develop my Ruby projects without tmuxinator interfering.

## What happened (include command output)

I installed tmuxinator via Homebrew. I set up a tmuxinator session, and ran it. Homebrew set an environment variable in order to get tmuxinator to properly load its RubyGems dependencies. That environment variable survives through the various forking that tmuxinator does to get tmux up and running, and thus leaks into any processes running within that tmux server.

<details>
  <summary>Command output</summary>
  <pre>
❯ echo $GEM_HOME
/usr/local/Cellar/tmuxinator/2.0.1/libexec

❯ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.7.1 (2020-03-31 patchlevel 83) [x86_64-darwin19]
  - INSTALLATION DIRECTORY: /usr/local/Cellar/tmuxinator/2.0.1/libexec
  - USER INSTALLATION DIRECTORY: /Users/dev/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /Users/dev/.rbenv/versions/2.7.1/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/Cellar/tmuxinator/2.0.1/libexec/bin
  - SPEC CACHE DIRECTORY: /Users/dev/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/dev/.rbenv/versions/2.7.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /usr/local/Cellar/tmuxinator/2.0.1/libexec
     - /Users/dev/.gem/ruby/2.7.0
     - /Users/dev/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/dev/.rbenv/versions/2.7.1/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /Users/dev/.rbenv/shims
     - /Users/dev/.rbenv/shims
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/dev/.rbenv/shims
     - /usr/local/sbin
  </pre>
</details>

## What you expected to happen

I expected tmuxinator's gem path not to be listed in my environment. I also expected the `GEM_HOME` environment variable not to be set to 

## Step-by-step reproduction instructions (by running `brew install` commands)

- `brew install tmuxinator`
- `tmux kill-server` (make sure tmux is not running)
- `tmuxinator new my-session`
- Set contents to:
```
name: my-session
root: ~/
windows:
  - shell: bash
```
- `tmuxinator start my-session`
- Make sure you are in the tmux session
- `echo $GEM_HOME`
- `gem env`

**Comment by nertzy** [comment]
See https://github.com/Homebrew/homebrew-core/blob/2a38c199646844242391e223b903f504a2a3670c/Formula/tmuxinator.rb#L47

**Comment by nertzy** [comment]
There's also a short discussion at https://discourse.brew.sh/t/why-does-tmuxinator-sets-gem-home/7296

**Comment by jonchang** [comment]
It's not clear to me that this is a Homebrew bug rather than something that tmuxinator needs to address. Specifically:

> That environment variable survives through the various forking that tmuxinator does to get tmux up and running, and thus leaks into any processes running within that tmux server.

It seems like tmuxinator should be doing (or have an option to) filter certain environment variables for the processes that it forks off. Homebrew needs to set `GEM_HOME` otherwise tmuxinator can't find its gems. If it can't find its gems, it won't work.

If there's an alternative here, please open a pull request; as I see it there's nothing to be done in Homebrew.
