### ISSUE TITLE
Ice 3.6.3 fails due build due to missing php header

### ISSUE THREAD

**Issue by rleigh-codelibre** [Homebrew/homebrew-core#5952]
https://gist.github.com/455726814d7a35d890d1840e7c7c3614

Looks like it's missing a `:build` dependency on php?

```
Error: Failed to download resource "ice"
Download failed: https://homebrew.bintray.com/bottles/ice-3.6.3_1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://github.com/zeroc-ice/ice/archive/v3.6.3.tar.gz
==> Downloading from https://codeload.github.com/zeroc-ice/ice/tar.gz/v3.6.3
######################################################################## 100.0%
==> Downloading https://zeroc.com/download/homebrew/db-5.3.28.NC.brew.tar.gz
==> Downloading from https://download.zeroc.com/homebrew/db-5.3.28.NC.brew.tar.gz
######################################################################## 100.0%
==> ../dist/configure --disable-debug --prefix=/usr/local/Cellar/ice/3.6.3_1/libexec --mandir=/usr/local/Cellar/ice/3.6.3_1/libexec/man --enable-cxx
==> make install
==> make install prefix=/usr/local/Cellar/ice/3.6.3_1 embedded_runpath_prefix=/usr/local/Cellar/ice/3.6.3_1 USR_DIR_INSTALL=yes SLICE_DIR_SYMLINK=yes
==> make install prefix=/usr/local/Cellar/ice/3.6.3_1 embedded_runpath_prefix=/usr/local/Cellar/ice/3.6.3_1 USR_DIR_INSTALL=yes SLICE_DIR_SYMLINK=yes
==> make install prefix=/usr/local/Cellar/ice/3.6.3_1 embedded_runpath_prefix=/usr/local/Cellar/ice/3.6.3_1 USR_DIR_INSTALL=yes SLICE_DIR_SYMLINK=yes
Last 15 lines from /Users/rleigh/Library/Logs/Homebrew/ice/05.make:

Creating /usr/local/Cellar/ice/3.6.3_1/share/php...
Creating /usr/local/Cellar/ice/3.6.3_1/lib/php/extensions...
making install in src
making install in php5
xcrun clang++ -c -I. -pthread -I../../../cpp/include -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -arch x86_64 -O2 -DNDEBUG -Wall -Werror -mmacosx-version-min=10.9 Communicator.cpp
In file included from Communicator.cpp:10:
In file included from ./Communicator.h:13:
./Config.h:53:10: fatal error: 'php.h' file not found
#include "php.h"
         ^
1 error generated.
make[2]: *** [Communicator.o] Error 1
make[1]: *** [install] Error 1
make: *** [install] Error 1
```

/cc @externl

**Comment by externl** [comment]
I thought that PHP was always installed on OS X/macOS so long as you had the developer tools installed? @rleigh-codelibre, does your system not have the php installed?

**Comment by zmwangx** [comment]
`/usr/include/php/main/php.h` is provided by CLT. Please install CLT by running

```
sudo xcode-select --install
```

and your issue should be resolved.

**Comment by ilovezfs** [comment]
I don't think that's a proper resolution of this issue CC @MikeMcQuaid

**Comment by externl** [comment]
Doesn't Homebrew automatically try/ask to install the CLT?

**Comment by ilovezfs** [comment]
@externl not if you have Xcode.

**Comment by rleigh-codelibre** [comment]
I think that it's likely that it's command-line tools related.  I did have them installed, but possibly something screwed up when I upgraded to Sierra.  I'll try to sort it out and if that's the cause I'll close this.

**Comment by zmwangx** [comment]
> but possibly something screwed up when I upgraded to Sierra.

Major OS upgrades erase CLT.

**Comment by rleigh-codelibre** [comment]
I think the problem is that for whatever reason, it's installed (or thinks it's installed) both the 7.3 and 8.0 tools, despite only xcode 8.0 being installed.  Might need to reinstall it all if I can't resolve the issue.  Either way, looks like it's my system at fault rather than the formula being problematic.

**Comment by rleigh-codelibre** [comment]
Yes, it's building fine but took several runs of the App store updater before it resolved the multiple versions and installed just the 8.0/12.0 command line tools.  Not sure why that got screwed up by the updater, but it's working now.
