### ISSUE TITLE
go 1.15 upgrade failure tracker

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#59698]
**Final failures:**

- `brew install --build-from-source charm` --  known issue https://github.com/juju/charmstore-client/issues/209
- `brew install --build-from-source grv` (on Mojave only) -- known issue https://github.com/rgburke/grv/issues/107
- ~~`brew install --build-from-source wellington` -- known issue https://github.com/wellington/wellington/issues/218~~ Fixed by https://github.com/Homebrew/homebrew-core/pull/60776

**Switched to `go@1.14`**
- `algernon` -- https://github.com/lucas-clemente/quic-go/issues/2614
- `caddy` --  https://github.com/lucas-clemente/quic-go/issues/2614
- `ipfs` -- https://github.com/lucas-clemente/quic-go/issues/2614
- ~~`syncthing` -- https://github.com/lucas-clemente/quic-go/issues/2614~~ Fixed by https://github.com/Homebrew/homebrew-core/pull/60781
- `kyma-cli` -- https://github.com/kyma-project/cli/issues/557

source, https://github.com/Homebrew/homebrew-core/pull/59486#issuecomment-674359331

**Comment by chenrui333** [comment]
go 1.5.1 upgrade failures

10.15

Error: 16 failed steps!
brew install --build-from-source charm
brew install --build-from-source charm-tools
brew test --retry --verbose darksky-weather
brew test --retry --verbose darksky-weather
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew test --retry --verbose gitleaks
brew install --build-from-source helm@2
brew install --build-from-source krakend
brew install --build-from-source landscaper
brew install --build-from-source prest
brew install --build-from-source prometheus
brew install --build-from-source ship
brew install --build-from-source velero
brew install --build-from-source wellington
brew install --build-from-source wiki

10.14

Error: 13 failed steps!
brew install --build-from-source charm
brew install --build-from-source charm-tools
brew test --retry --verbose darksky-weather
brew test --retry --verbose darksky-weather
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew test --retry --verbose gitleaks
brew install --build-from-source grv
brew install --build-from-source helm@2
brew install --build-from-source landscaper
brew install --build-from-source prest
brew install --build-from-source velero
brew install --build-from-source wellington

10.13

Error: 12 failed steps!
brew install --build-from-source charm
brew install --build-from-source charm-tools
brew test --retry --verbose darksky-weather
brew test --retry --verbose darksky-weather
brew install --build-from-source dashing
brew test --retry --verbose dashing
brew test --retry --verbose gitleaks
brew install --build-from-source helm@2
brew install --build-from-source landscaper
brew install --build-from-source prest
brew install --build-from-source velero
brew install --build-from-source wellington

**Comment by chenrui333** [comment]
gitleaks tests out fine in my local.

**Comment by chenrui333** [comment]
helm@2 and landscaper do have issues

**Comment by chenrui333** [comment]
velero v1.5.0 tag was deleted, raised an issue (https://github.com/vmware-tanzu/velero/issues/2903)

**Comment by chenrui333** [comment]
wellington build issue tracker, https://github.com/wellington/wellington/issues/218

**Comment by chenrui333** [comment]
go 1.15.2 upgrade failures log
```
10.14
Error: 6 failed steps!
brew install --build-from-source charm
brew install --build-from-source grv
brew install --build-from-source helm@2
brew install --build-from-source landscaper
brew install --build-from-source minikube
brew install --build-from-source velero

10.13, 10.15
Error: 5 failed steps!
brew install --build-from-source charm
brew install --build-from-source helm@2
brew install --build-from-source landscaper
brew install --build-from-source minikube
brew install --build-from-source velero
```

**Comment by fxcoudert** [comment]
Between Big Sur bottling, and the upcoming ARM bottling, we'll have plenty of opportunity to track these build-from-source failures. Keeping a separate tracking bug does not seem useful at the moment.
