### ISSUE TITLE
sqlite 3.33.0 upgrade failure tracker

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/homebrew-core#59707]
10.15
```
brew test --retry --verbose agda
brew install freeling
brew install --only-dependencies swift-protobuf
```

10.14
```
brew test --retry --verbose agda
brew install freeling
```

10.13
```
brew test --retry --verbose agda
brew test --retry --verbose buku
brew install freeling
```

ref, https://github.com/Homebrew/homebrew-core/pull/59667#issuecomment-674450014

**Comment by gromgit** [comment]
`freeling` conflicts with three other formulae. I'll issue a PR to fix that.

Sidenote: Two of the four formulae have deprecated licenses. Should I fix them in the same PR, or issue a separate PR for license changes?

**Comment by jonchang** [comment]
Might as well update the license if you're updating the formula already. Thanks @gromgit

**Comment by chenrui333** [comment]
agda fix PR got merged.
