### ISSUE TITLE
libvirt 6.6.0 fails to load shared libraries

### ISSUE THREAD

**Issue by sshambar** [Homebrew/homebrew-core#59738]
Fresh install of libvirt on Catalina, and ran the following as local (non-root) user:

$ /usr/local/Cellar/libvirt/6.6.0/sbin/libvirtd -v -f /usr/local/etc/libvirt/libvirtd.conf

this results in the following errors:

... info : virModuleLoad:113 : Module '/usr/local/Cellar/libvirt/6.6.0/lib/libvirt/connection-driver/libvirt_driver_secret.so' does not exist                                            
... info : virModuleLoad:113 : Module '/usr/local/Cellar/libvirt/6.6.0/lib/libvirt/connection-driver/libvirt_driver_storage.so' does not exist    
etc...                                       

virsh fails with:
$ virsh list
error: failed to connect to the hypervisor
error: no connection driver available for <null>

Examining the library directory shows the extensions are incorrect:

$ ls /usr/local/Cellar/libvirt/6.6.0/lib/libvirt/connection-driver
libvirt_driver_qemu.bundle    libvirt_driver_storage.bundle
libvirt_driver_secret.bundle  libvirt_driver_vbox.bundle

Creating symlinks to .so files with "for f in *; do ln -s $f ${f%.bundle}.so; done" fixes the errors.

Also created symlinks in the adjacent libvirt directories:  lock-driver/, storage-backend/,  and storage-file/

Restarting libvirtd as above allows virsh to correctly connect:
$ virsh list
 Id   Name   State
--------------------

This is probably the result of a missing configure option in libvirt.rb, but I'm not sure which...

**Comment by SMillerDev** [comment]
That's the same command as we run in our tests and it passes there. Are these defined in your configuration?

**Comment by sshambar** [comment]
Which tests are you referring to?  The libvirt.rb tests just run "virsh -v" (which doesn't require a daemon running)... "virsh list" connects to a running libvirtd via the socket file, and so requires libvirtd to be started and have the drivers loaded.

I checked the source, and src/driver.c has ".so" hard-coded as the file suffix, so it appears the installed the driver files need to have that suffix.

I ran an interactive build, and libtool is appending .bundle to any module names; that feature originates from configure's *darwin section: 
shrext_cmds='`test .$module = .yes && echo .bundle || echo .dylib`'
... and that's from the m4/libtool.m4 macro.

So it appears that the error is in the distributed m4/libtool.m4 file.  I ran autogen.sh --no-git before compiling and the module files where named with ".so" as expected (brew version of libtool installs a "working" libtool.m4).

If the build formula is updated to use the full autoconf toolset (as used in the git build.head version), then things should work out.

Easy fix?

**Comment by SMillerDev** [comment]
I think you should report this upstream, since using `.so` as a file extension on macOS is like using `.exe` for your binaries. It's really not the standard. Upstream should support either the right extension for the right os or allow the packaging party to configure it.

**Comment by sshambar** [comment]
I appears to be a distribution foulup... I checked https://libvirt.org/sources/libvirt-6.5.0.tar.xz and it has the same "shrext_cmds" as homebrew's libtool (and upstreams)... someone changed the shrext_cmds in the latest 6.6.0 distribution.

Since this is not in libvirt source control, I could try sending something to the mailing list... it's unclear where to report issues with the tarball...

**Comment by sshambar** [comment]
The response from the libvirt developers is that they're moving to the Meson build system in 6.7.0, so won't bother to fix the 6.6.0 tarball... from the email response:

"Daniel P. Berrangé" <berrange@redhat.com>:
> So I'd suggest you do the minimum possible to get 6.6.0 working on
> homebrew, by just applying a local patch to the tarball for that
> problem code, since this will be a one-off problem.

I've submitted a pull request which uses autogen.sh in the build.

Since the brew audit indicated a fix needed for the license, I corrected it to the GPL-2.0+ in accordance with Formula Cookbook: "Formulae that have different licenses for different parts of their software should specify only the more restrictive license"

**Comment by yoonsikp** [comment]
Isn't this issue solved?

**Comment by sshambar** [comment]
Yep, and libvirt is also at version 6.7.0 now on homebrew.  Closing....
