### ISSUE TITLE
z3 HEAD failed to build on 10.10

### ISSUE THREAD

**Issue by mantognini** [Homebrew/homebrew-core#598]
### Bug report:

When trying to build `z3` with the `--HEAD` option, I get an exception (see below) that can be ignored and still result in a successful build and install of the formula.

Basically, this happens:

```
brew install -vd --HEAD z3
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/z3.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/z3.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/Z3Prover/z3.git
Updating /Library/Caches/Homebrew/z3--git
git config remote.origin.url https://github.com/Z3Prover/z3.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 271b56a Merge branch 'master' of https://github.com/Z3Prover/z3
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
Utils::InreplaceError: inreplace failed
scripts/mk_util.py:
  expected replacement of "dist-packages" with "site-packages"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 2
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/python.rb
==> python scripts/mk_make.py --prefix=/usr/local/Cellar/z3/HEAD --staticlib
[...]
==> Summary
🍺  /usr/local/Cellar/z3/HEAD: 68 files, 62.6M, built in 2 minutes 33 seconds
```

I quickly tested the installed files and it seems to work just fine.

[Here's the logs](https://gist.github.com/277cbf978e06406d0a3bab9721e55f42). However, it seems not to contain the relevant bits...

I don't actually know if it's an issue with brew or z3, so CC one of z3's contributor (@NikolajBjorner) just in case.

Let me know if you need more information.

**Comment by NikolajBjorner** [comment]
It looks to me that it is "brew" related. The exception location is inside the "brew" code path. 
The output related to Z3 goes through without any issues.

**Comment by ilovezfs** [comment]
This is due to https://github.com/Z3Prover/z3/commit/4c11037d70db1ef8c533395cf298aaf1e1505255

**Comment by DomT4** [comment]
Should be fixed via https://github.com/Homebrew/homebrew-core/commit/db99c6132947a998bd64047755a382407480d319.

**Comment by mantognini** [comment]
It is! 👍
