### ISSUE TITLE
[Feature request] unbound DNS resolver with optional python bindings

### ISSUE THREAD

**Issue by croessner** [Homebrew/homebrew-core#5985]
My question is short:

Is it possible to extend the current unbound formula to give an option to also install the python bindings to the unbound DNS resolver?

That would be awesome :-)

Thanks in advance

**Comment by MikeMcQuaid** [comment]
Yes, should be possible. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by croessner** [comment]
I created a fork from homebrew-core and set up a branch "croessner".

https://github.com/croessner/homebrew-core/tree/croessner

I edited the unbound.rb file with "brew edit unbound", but I came to a point, were I do not get any further :-(

`...
checking for python... /usr/local/opt/python/bin/python
checking for the distutils Python package... yes
checking for Python include path... -I/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7
checking for Python library path... -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib -L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7
checking for Python site-packages path... /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
checking consistency of all components of python development environment... yes`

Compile fails with:

`/bin/sh ./install-sh -c -m 644 ./libunbound/python/unbound.py /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/unbound.py
./install-sh: ./libunbound/python/unbound.py does not exist.
make: *** [pyunbound-install] Error 1
make: *** Waiting for unfinished jobs....
cp: /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_inst.33587_: Operation not permitted
make: *** [pythonmod-install] Error 1`

I tried to learn from other formulae, but it did not work. Whatever I tried, same errors.

Can you give me a hint, what I could do to get the fromula done?

Thanks

**Comment by croessner** [comment]
https://github.com/croessner/homebrew-core/blob/croessner/Formula/unbound.rb

**Comment by MikeMcQuaid** [comment]
CC our resident Python expert @tdsmith

**Comment by tdsmith** [comment]
You want to not see:

`checking for Python site-packages path... /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`

You can try adding `PYTHON_SITE_PKG=#{lib}/python2.7/site-packages` to the `configure` arguments.

**Comment by tdsmith** [comment]
Er, you don't want to see it because the destination should be inside unbound's prefix and not elsewhere on the system.

**Comment by croessner** [comment]
Not sure, if I understood you correctly. First of all thanks. I think the PYTHON_SITE_PKG fixed one issue.

One remains:

`/usr/local/opt/swig/bin/swig -python -o libunbound/python/libunbound_wrap.c -I. -I/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPY_MAJOR_VERSION=2 ./libunbound/python/libunbound.i
...
/bin/sh ./install-sh -c -m 644 ./libunbound/python/unbound.py /usr/local/Cellar/unbound/1.5.10/lib/python2.7/site-packages/unbound.py
./install-sh: ./libunbound/python/unbound.py does not exist.`

This time, I also compiled with --debug and ropped into a shell. I checked unbound.py and the file exists after the swig call. But I do not understand, why it can not be found. Any ideas?

pwd
/private/tmp/unbound-20161017-65453-7s5y56/unbound-1.5.10/libunbound/python

ls -l unbound.py

-rw-r--r--  1 croessner  admin  36348 17 Okt 19:45 unbound.py

I hope I am close to success :-)

**Comment by croessner** [comment]
Problem solved :-)

So simple: There was missing: system "make"

I prepare the pull request now

**Comment by croessner** [comment]
Sorry, if I ask again. I have send you a pull request. I know that the audit for this package does not succeed. But I do not see the problem:

`otool -L ../../../Cellar/unbound/1.5.10/lib/python2.7/site-packages/_unbound.so
../../../Cellar/unbound/1.5.10/lib/python2.7/site-packages/_unbound.so:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1348.0.0)
	/usr/local/Cellar/unbound/1.5.10/lib/libunbound.2.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/libevent-2.0.5.dylib (compatibility version 7.0.0, current version 7.9.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)`

As you can see, the python module is linked against Python-2.7. Even if this is hardcoded, the path will never change, as there will be no Python-2.x anymore and unbound does not have Python-3-support.

So is it possible to accept my formula?

If not, can somebody please help me fixing it? I really try hard to do my best.

**Comment by MikeMcQuaid** [comment]
@croessner Best way to get help fixing it is to open a PR and we'll help you iterate on it. Thanks!
