### ISSUE TITLE
403 error when trying to install x265

### ISSUE THREAD

**Issue by chaos-git** [Homebrew/homebrew-core#59867]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install ffmpeg`

## What happened (include command output)

Failed in install x265 due to a 403 error. Hitting the BitBucket link directly shows that the repo is no longer available as BitBucket no longer supports Mercurial.

<details>
  <summary>Command output</summary>
  <pre>

$ brew install x265
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
mariadb@10.4
==> Updated Formulae
Updated 11 formulae.

Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/5bdbf3b3fdadaf72744884b98b74a2ff887bd63a20b246f811a222a146ad7b64--pkg-config-0.29.2.tar.gz
==> Downloading https://ftp.gnu.org/gnu/gdbm/gdbm-1.18.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/c6e5196e3cea2a139cb849d508032f117c6351da5fe84323dc13ad2a0600264a--gdbm-1.18.1.tar.gz
==> Downloading https://www.openssl.org/source/openssl-1.1.1g.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/1178a9e293b3f8231b3a09a91b1a4cc8bf765526148a37a720ba4a89d49e3aff--openssl-1.1.1g.tar.gz
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.0-patches/readline80-001
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/47beb8acfca2f2c1f4c481f864e786627a8ba6e0dbdd0fc87a9d2bee461681c7--readline80-001
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.0-patches/readline80-002
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/c00dd25d193a8318f8c1387f51f4e497634b1392278fc65dbf14bb388199baef--readline80-002
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.0-patches/readline80-003
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/1c985b03f188d6b79dae2b15fbe1aa25b76a01503c2d9ccaf78900e9fdd395d9--readline80-003
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.0-patches/readline80-004
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/d362e6fd90dbb0314fa033ad3424721460f0b8b067309f035368b13d4a123399--readline80-004
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/2dd06cc6b778b6977a66d7986a2c0e71e557ff460a093af91f0f77a60d4e6d14--readline-8.0.tar.gz
==> Downloading https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/5e52b8b0330f34548b7eecfdac41259cbbf426fc52aba671aed35c19feebc11d--sqlite-autoconf-3330000.tar.gz
==> Downloading https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/a13e2dce533a3dcb05b2f1b86fc45eac1f6ebf737b54ef7d3089994649d28aa8--xz-5.2.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/8e/38259f4a44944a92068d5ff77230511a4c685604b47a81318f9e5cf2cc24/setuptools-49.2.0.zip
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/3076c60e0e877e751ede5c4601e3a6dd3bbdd83a9a9415c27907671c9da74a10--setuptools-49.2.0.zip
==> Downloading https://files.pythonhosted.org/packages/08/25/f204a6138dade2f6757b4ae99bc3994aac28a5602c97ddb2a35e0e22fbc4/pip-20.1.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/bdc0898a739d3f47fd1eb7b8e5173a7e616e2c3419b5d17f734fedccadd42e9b--pip-20.1.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/553d732b4cf117039b60aab1f75ac3e6f6869a9fa3127b4107984fa5b084a00b--wheel-0.34.2.tar.gz
==> Downloading https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tar.xz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/7ff503a4798dde74540e982331b43b4d745c0820c44473c983e70d03372af86d--Python-3.8.5.tar.xz
==> Downloading https://files.pythonhosted.org/packages/b1/72/2d70c5a1de409ceb3a27ff2ec007ecdd5cc52239e7c74990e32af57affe9/virtualenv-15.2.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/e390edd594d1668ad899868951573cc02842e8f82003ec75bd388377d3a3f373--virtualenv-15.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/cc/b4/ed8dcb0d67d5cfb7f83c4d5463a7614cb1d078ad7ae890c9143edebbf072/alabaster-0.7.12.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/6fe7e7241e703f9e3f03f1600efd5a1f03bb466b8bc79871d35be3da87239d71--alabaster-0.7.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/34/18/8706cfa5b2c73f5a549fdc0ef2e24db71812a2685959cff31cbdfc010136/Babel-2.8.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/8d4c478d299c27ce1162824cbaa27104239a9a486c58cc763a911281d905d0ea--Babel-2.8.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/40/a7/ded59fa294b85ca206082306bba75469a38ea1c7d44ea7e1d64f5443d67a/certifi-2020.6.20.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/6d38870043164763b1340f7ac33977f902c5fe9864bc10e7fe2b25fa55064281--certifi-2020.6.20.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/e0/3d435b34abd2d62e8206171892f174b180cd37b09d57b924ca5c2ef2219d/docutils-0.16.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/bee502905dc3428f44a8c0cb547106a3931a395c3c2cf973848a0c0032fc0998--docutils-0.16.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ea/b7/e0e3c1c467636186c39925827be42f16fee389dc404ac29e930e9136be70/idna-2.10.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/70659672fb0872c9cfb410161104337eae58aca1a607a5c63a2a452757d6faf0--idna-2.10.tar.gz
==> Downloading https://files.pythonhosted.org/packages/e4/9f/0452b459c8ba97e07c3cd2bd243783936a992006cf4cd1353c314a927028/imagesize-1.2.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/ce4f2407ec2acdfd8aa5357f5d14900318ec172b8f6d77eb3cba4f9bc72db9d3--imagesize-1.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/64/a7/45e11eebf2f15bf987c3bc11d37dcc838d9dc81250e67e4c5968f6008b6c/Jinja2-2.11.2.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/35edb62c9dadaf8a485c3064d37cdab7bbbc38de4365ade27167eff7bfe70ef1--Jinja2-2.11.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/ef7c3d863a1666e25931c26c999dd56b38582d198b145c01c2909f386351bc46--MarkupSafe-1.1.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/3d/fb/a70f636102045fc646656f2221c7fcdf92f7a9d71ba7c9875a949a58b3e8/numpydoc-1.1.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/cd83174980fca91e1cb0e06a81d7aac39564f4679d44e2e8ff6695365d22c401--numpydoc-1.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/55/fd/fc1aca9cf51ed2f2c11748fa797370027babd82f87829c7a8e6dbe720145/packaging-20.4.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/618253f89f8800b545faf121702b2204b673a275fb39b80c65ced932f251f034--packaging-20.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6e/4d/4d2fe93a35dfba417311a4ff627489a947b01dc0cc377a3673c00cf7e4b2/Pygments-2.6.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/e542fd16bcd5225dc9cc09cc3213f88cfbabd6021267426b56dfa4303d4785c0--Pygments-2.6.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c1/47/dfc9c342c9842bbe0036c7f763d2d6686bcf5eb1808ba3e170afdb282210/pyparsing-2.4.7.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/f62c96d488908268a2499dd686ece4b13d1deb6000d0cbda1fc4742d22397d0e--pyparsing-2.4.7.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fa/63/759ff01d90ad08fbec19954c71f474c0c0e613850a6419b4b6a4ea79f5e9/python-docs-theme-2020.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/7113bb147f0c228b7a10dd86368847be528faaa3254a0e18810b7e9db4f5d1a0--python-docs-theme-2020.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f4/f6/94fee50f4d54f58637d4b9987a1b862aeb6cd969e73623e02c5c00755577/pytz-2020.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/128204d3967805dfecd020006a6fd0200bc78a6e08b2dc730909e1d2cd825240--pytz-2020.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/da/67/672b422d9daf07365259958912ba533a0ecab839d4084c487a5fe9a5405f/requests-2.24.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/7e1ce5456c1e5077e6702980eb352f8eca9dc685bf8b03f5376e6311756bb99d--requests-2.24.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/21/1b/6b8bbee253195c61aeaa61181bb41d646363bdaa691d0b94b304d4901193/snowballstemmer-2.0.0.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/548ae4f5d5a61192f0db37a495ba492b82ce584701c64246b178a37278210c2a--snowballstemmer-2.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/9f/01/ad9d4ebbceddbed9979ab4a89ddb78c9760e74e6757b1880f1b2760e8295/sphinxcontrib-applehelp-1.0.2.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/1570c2b2bf9ce0b9c5e994a7ada997dff2474f85f5a7db7f3d27644d82bdf0e7--sphinxcontrib-applehelp-1.0.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/98/33/dc28393f16385f722c893cb55539c641c9aaec8d1bc1c15b69ce0ac2dbb3/sphinxcontrib-devhelp-1.0.2.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/857c58712c97e9ef60252ece34766e3701540fa8bc51528ce47b4cc90dc1d90c--sphinxcontrib-devhelp-1.0.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c9/2e/a7a5fef38327b7f643ed13646321d19903a2f54b0a05868e4bc34d729e1f/sphinxcontrib-htmlhelp-1.0.3.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/9b0d74c2bbdeb91290b2d9a1c27e660211551417f3a88e1925c7e94d970a6ed0--sphinxcontrib-htmlhelp-1.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b2/e8/9ed3830aeed71f17c026a07a5097edcf44b692850ef215b161b8ad875729/sphinxcontrib-jsmath-1.0.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/0cac3fdf6ce0ddabef294d3fbde4de8265e0c47f14daaa259388f4dd1805549c--sphinxcontrib-jsmath-1.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b1/8e/c4846e59f38a5f2b4a0e3b27af38f2fcf904d4bfd82095bf92de0b114ebd/sphinxcontrib-qthelp-1.0.3.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/8e4c6f7bdec732ed005f10a8bfc2cb56e0487656133ad214825ab85e0beecfbd--sphinxcontrib-qthelp-1.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ac/86/021876a9dd4eac9dae0b1d454d848acbd56d5574d350d0f835043b5ac2cd/sphinxcontrib-serializinghtml-1.1.4.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/7d31dacff6edf58aa41b3a127e8f3c8040b26e29b936fbfe56b1946997216127--sphinxcontrib-serializinghtml-1.1.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/05/8c/40cd6949373e23081b3ea20d5594ae523e681b6f472e600fbc95ed046a36/urllib3-1.25.9.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/372f58f5f3129b2a54e87c3e8ee9130aa82f22944c8850cca0ba76bcb1d92941--urllib3-1.25.9.tar.gz
==> Downloading https://files.pythonhosted.org/packages/4b/2b/84e00ab4c6103ebe38b3c1f0d574d46a7b8fb1dccb4d41a6ec0b9d15aacd/Sphinx-3.1.2.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/d94fd70439a4832e5c4fa2ce34fd4dbff63e8e3026a99336f8d2abbc8026db36--Sphinx-3.1.2.tar.gz
==> Downloading https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1.tar.gz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/5e53b7cb6265f6281636a5a5d6ad96c069f256bd03d44842e1294fb66fb16622--cmake-3.18.1.tar.gz
==> Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.03/nasm-2.15.03.tar.xz
Already downloaded: /Users/chaoize/Library/Caches/Homebrew/downloads/42a9d0b36130ebf52b25f5ce91b8672589dd589aebaa90ae70d8c90a47461602--nasm-2.15.03.tar.xz
==> Downloading https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "x265"
Download failed: https://bitbucket.org/multicoreware/x265/downloads/x265_3.4.tar.g

  </pre>
</details>

## What you expected to happen

Successful install of x265

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install x265`

**Comment by chaos-git** [comment]
```
$ brew config
HOMEBREW_VERSION: 2.4.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 19ef93288573e565cec82679d0cd834a4ad080ab
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1f2119ba15080dd1b08ee7d56cea2970a26885c1
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.14.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_265
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A
chaoize-mbp:Desktop chaoize$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gettext

Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

```

**Comment by retokromer** [comment]
There is already an open [PR](https://github.com/Homebrew/homebrew-core/pull/59866).

**Comment by chaos-git** [comment]
Nice, I'll close
