### ISSUE TITLE
TigerVNC using only 1/4 of display when running on Retina display

### ISSUE THREAD

**Issue by weakunix** [Homebrew/homebrew-core#59910]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [*] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

tiger-vnc got upgraded as a dependence which now only uses 1/4 of the client window on a retina display iMac. This is a previously reported/closed [issue](https://github.com/Homebrew/homebrew-core/issues/37872), but it doesn't seem to have been resolved. I also tried to downgrade fltk from 1.3.5 to 1.3.4-2 according to the prior issue, but it did not fix the problem for me -- rather the window became entirely blank.

## What happened (include command output)

<details>
  <summary>brew config</summary>
  <pre>

[brew_config.txt](https://github.com/Homebrew/homebrew-core/files/5101011/brew_config.txt)

  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>

[brew_config.txt](https://github.com/Homebrew/homebrew-core/files/5101011/brew_config.txt)

  </pre>
</details>

**Comment by SMillerDev** [comment]
As mentioned in that issue it's a bug upstream, not in homebrew. See https://github.com/TigerVNC/tigervnc/issues/805
