### ISSUE TITLE
GNU Radio volk seg faults when running volk_profile 

### ISSUE THREAD

**Issue by citizenrich** [Homebrew/homebrew-core#59921]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run volk_profile after installing GNU Radio.

## What happened (include command output)

Segmentation fault.
<details>
  <summary>Command output</summary>
  <pre>

RUN_VOLK_TESTS: volk_8u_x3_encodepolarpuppet_8u(131071,1987)
generic completed in 1764.34 ms
u_ssse3 completed in 522.744 ms
Segmentation fault: 11

  </pre>
</details>

## What you expected to happen

volk_profile completes.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gnuradio
volk_profile
```
The GNU Radio formula was recently updated. Thanks folks! 

Volk is on version 2.0 for the brew formula. volk_profile seg faults for the 2.0 version on macos, see: https://github.com/gnuradio/volk/issues/292 This means that the volk_profile utility doesn't complete and this affects performance as SIMD is disabled for GNU Radio. There is a fix from 2019 in volk for the seg fault.

Can the volk version be bumped up? Including @iMichka as recent updater of the GNU Radio brew formula (and thanks for that!) and @michaelld who is macos dev for GR.

('m not a dev of these projects, but just an observation to consider is that in the upcoming 3.9 GNU Radio release that volk is a separate dependency and is in its own repo now but also a submodule in GNU Radio 3.8 maintenance branch. This means that volk in future can be a separate brew formula and perhaps that is a way to consider solving this seg fault issue.)

```
$ brew info gnuradio
gnuradio: stable 3.8.1.0 (bottled), HEAD
SDK providing the signal processing runtime and processing blocks
https://gnuradio.org/
/usr/local/Cellar/gnuradio/3.8.1.0_1 (3,080 files, 92.5MB) *
  Poured from bottle on 2020-08-14 at 15:43:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gnuradio.rb
License: GPL-3.0
==> Dependencies
Build: cmake ✔, doxygen ✔, pkg-config ✔, swig ✔
Required: boost ✔, fftw ✔, gmp ✔, gsl ✔, gtk+3 ✔, log4cpp ✔, numpy ✔, portaudio ✔, pygobject3 ✔, pyqt ✔, python@3.8 ✔, qt ✔, qwt ✔, uhd ✔, zeromq ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 1,394 (30 days), 2,268 (90 days), 8,677 (365 days)
install-on-request: 1,228 (30 days), 2,006 (90 days), 7,519 (365 days)
build-error: 0 (30 days)
$ gnuradio-config-info -v
3.8.1.0
$ volk-config-info -v
2.0
```

**Comment by jonchang** [comment]
Please file an issue with gnuradio asking them to cut a new release that includes an updated volk dependency. We might consider a patch that just has the bug fix but this is more upstream's responsibility to keep their vendored dependencies up to date.

**Comment by citizenrich** [comment]
So, the Volk folks tagged a new release which provides proper optimization for macOS and fixes that outstanding issue.
https://github.com/gnuradio/volk/releases/tag/v2.4.0

**Comment by alebcay** [comment]
> So, the Volk folks tagged a new release which provides proper optimization for macOS and fixes that outstanding issue.
> [gnuradio/volk@`v2.4.0` (release)](https://github.com/gnuradio/volk/releases/tag/v2.4.0)

`volk` has been updated to 2.4.0 in https://github.com/Homebrew/homebrew-core/commit/ff84115e1de9fc8cdd52693fb6a41488682c3bb6.
