### ISSUE TITLE
`rust-analyzer` formula version not displaying correctly

### ISSUE THREAD

**Issue by neeldug** [Homebrew/homebrew-core#59937]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? N/A
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
brew config:
```
HOMEBREW_VERSION: 2.4.12-233-gebafc70
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebafc70bcb0bdfb44eefa9d17f159334540d2400
Last commit: 57 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ac4139a644726ba3d009839e040c64b5319965a0
Core tap last commit: 18 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SlRh9TiMln/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
CPU: 16-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 1103.0.32.62
Xcode: 11.6
XQuartz: 2.7.11 => /opt/X11
```

## What you were trying to do (and why)

I tried running `rust-analyzer --version`, just to see whether it's up-to-date with the binary.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

 rust-analyzer ???????

  </pre>
</details>

## What you expected to happen

rust-analyzer _version hash here_

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install rust-analyzer`

**Comment by dtrodrigues** [comment]
It's likely due to Homebrew using the source tar vs checking out the git repository. https://github.com/Homebrew/homebrew-core/pull/59945 should fix this.

**Comment by dtrodrigues** [comment]
Fixed now:
```
$ brew update && brew upgrade rust-analyzer && rust-analyzer --version
...
rust-analyzer 0b2b9a5
```
