### ISSUE TITLE
mitmproxy fails to build on 10.12

### ISSUE THREAD

**Issue by agatti** [Homebrew/homebrew-core#6020]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Gist with the error report available at https://gist.github.com/agatti/29e54347dfab7741447d3cd6159607e9

Thank you!

**Comment by tdsmith** [comment]
This should depend_on :python.

**Comment by agatti** [comment]
That commit did not really fix the problem here, unfortunately.  New gist is here: https://gist.github.com/2c90759ef64de08d6cea914b60e1dbff

Reading through it, it seems to be a Pillow problem:

>    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting
>    Running setup.py install for Pillow: finished with status 'error'

**Comment by ilovezfs** [comment]
Can you try installing the CLT please.

```
xcode-select --install
```

**Comment by ilovezfs** [comment]
Closed via #6215.
