### ISSUE TITLE
ninja: python integrations fail for case-sensitive file systems

### ISSUE THREAD

**Issue by aharrison24** [Homebrew/homebrew-core#60265]
I've not included `gist-logs` output because I don't believe it's relevant to this issue. Please see below for an explanation.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
  **No issues, other than that it does correctly point out that I have a case-sensitive file system.**
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  **Not applicable. The formula installs fine. The problem occurs when I use the installed `ninja` binary**
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
  **Not applicable**

## What you were trying to do (and why)

I tried to use the `ninja -t browse` tool.

Repro steps:
```
brew install cmake ninja

touch CMakeLists.txt
cmake -GNinja .

ninja -t browse
```

## What happened (include command output)
The `ninja -t browse` command failed with an `execvp` error:
```
$ ninja -t browse
ninja: execvp: Not a directory
```

## What you expected to happen
I expected a local server to be launched by `ninja` and a browser window to be opened.

## Explanation of the issue

**This is not a problem for case-insensitive systems. It only occurs on case-sensitive file systems.**

Running `ninja -t browse` requires ninja to invoke python. The path to the python executable is baked-in to ninja at compile-time via a compile definition called `NINJA_PYTHON`:
https://github.com/ninja-build/ninja/blob/a63fb13322aac3ca56e008757eb0514d96549ab5/src/browse.cc#L50

`NINJA_PYTHON` is configured as part of the ninja bootstrap script:
https://github.com/ninja-build/ninja/blob/a63fb13322aac3ca56e008757eb0514d96549ab5/configure.py#L323

It comes from the `--with-python` option to `configure.py`, which has its default set here:
https://github.com/ninja-build/ninja/blob/a63fb13322aac3ca56e008757eb0514d96549ab5/configure.py#L217

So if you don't override the default, then `NINJA_PYTHON` gets set to the result of the expression:
```
os.path.basename(sys.executable))
```

On my system, `sys.executable` evaluates to:
```
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
```
Once you pass it through `os.path.basename` you're left with just `'Python'`.

On a case-**insensitive** MacOS system, trying to invoke a binary called `Python` results in `/usr/bin/python` being used.

On a case-**sensitive** MacOS system, no command called `Python` can be found. That's the reason for the `execvp` failure. 

## Suggested fix

I was able to 'fix' the issue on my machine by editing the following line in the `ninja.rb` formula:

#### OLD
```
system "python", "configure.py", "--bootstrap"
```
#### NEW
```
system "python", "configure.py", "--bootstrap", "--with-python=python"
```

I'm not sure how robust this is as a solution, though I doubt it's any less robust than the current situation, where the system `python` executable is picked up 'accidentally' because of case-insensitivity.

**Comment by aharrison24** [comment]
To reproduce the issue on a case-sensitive file system:
```
brew install cmake ninja

touch CMakeLists.txt
cmake -GNinja .

ninja -t browse
```

**Comment by SMillerDev** [comment]
Does this not occur outside of homebrew?

**Comment by aharrison24** [comment]
It's possible that this is an issue with upstream ninja, because of the way it bakes the python path in to the `ninja` executable. But they have provided a customisation point for users to provide an alternative python path. It seems reasonable to be expected to specify that in the homebrew formula.

**Comment by SMillerDev** [comment]
If the assumptions Ninja make in their build process are wrong they should be notified and preferably a patch should be provided to them. If homebrew can work around it is irrelevant in such situations.

**Comment by alastair-harrison-oxb** [comment]
OK, I'll try to raise an issue upstream.

**Comment by aharrison24** [comment]
FWIW I've raised a PR upstream to address this issue. If/when it lands, it will require the homebrew recipe to switch to building ninja with CMake, rather than the custom python script that is currently used.

**Comment by dtrodrigues** [comment]
`brew upgrade ninja` should now have support for browse mode on case-sensitive filesystems. Thanks for fixing it upstream @aharrison24!

**Comment by aharrison24** [comment]
Amazing! Thank you!
