### ISSUE TITLE
qt5 fails to build with mysql support

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#6032]
### Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~  N/A
### Bug reports:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As noted in [this comment](https://github.com/Homebrew/homebrew-core/issues/5947#issuecomment-254346583) on [Issue #5947:  'qt5 fails to upgrade to 5.6.2 on Sierra with Xcode 8.'](https://github.com/Homebrew/homebrew-core/issues/5947), I split this off from that bug report since I'm seeing issues on a different version of OS X/macOS.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/v5.7.0/First%20Recorded%20Attempt) are my logs.  I'm guessing the presence of a `build.sandbox.log` indicates that my problem is most likely due to some kind of sandbox violation.  Please note, however, that these are from a `brew reinstall` attempt since I thought the `brew upgrade` attempts I made beforehand might be failing due to the possibility that formula changes other than the version bump could have affected these previous build attempts (there was more than one.)  Unfortunately, this overwrote the earlier logs I had, so I can't provide them.

**Comment by ilovezfs** [comment]
What's the output of `xcode-select -p`?

If it's the CLT then you need to run `sudo xcode-select -r`

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Running `xcode-select -p` outputs `/Applications/Xcode.app/Contents/Developer`.

**Comment by ilovezfs** [comment]
what options are in the install receipt

**Comment by RandomDSdevel** [comment]
Where would I find that again, if you don't mind pointing me in the right direction?

**Comment by ilovezfs** [comment]
should be /usr/local/opt/qt5/INSTALL_RECEIPT.json which you can put in a gist

**Comment by RandomDSdevel** [comment]
OK, thanks!  I'll do that right now, then…

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Ta-da, [here](https://gist.github.com/RandomDSdevel/54f2ab7c048e9df7d21a0b047e740061) it is!

**Comment by ilovezfs** [comment]
I'd suggest just `brew uninstall qt5; brew install qt5` and use the bottle. But if you really do want the extra options I think this patch is probably sufficient https://github.com/yezezey/homebrew-core/commit/28f46e6c4db62946dbebb2adceaa8964042890c9

**Comment by RandomDSdevel** [comment]
There doesn't happen to be a pull request to integrate those changes into mainline Homebrew Core, does there?  I'm completely lacking in experience when it comes to patching formulas.  (Well, I've edited formulas to fix software builds by patching _them_, but methinks that's, at least in part, an entirely different kettle of fish…)

**Comment by apjanke** [comment]
One more data point: I did `brew install qt5 --with-mysql` on OS X 10.11.6 with the current formula, and the build completed. But it picked up the system OpenSSL library, which we don't want. (And Homebrew's `postgresql`, even though I didn't request it.)

```
$ brew linkage qt5
System libraries:
  /System/Library/Frameworks/AGL.framework/Versions/A/AGL
...
  /usr/lib/libssl.0.9.8.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/mysql/lib/libmysqlclient.20.dylib (mysql)
  /usr/local/opt/postgresql/lib/libpq.5.dylib (postgresql)
...
Possible undeclared dependencies:
  postgresql
```

If I find some time, I'll look at that patch for inclusion in core. No guarantees, though; qt5's very long build time makes it hard to work with.

**Comment by apjanke** [comment]
BTW you'd need to pull more than that one patch, I think. There are multiple Qt5 openssl-related commits on that branch in yezezey's repo. Need to grab all the openssl-related stuff around where that patch changes things.

**Comment by ilovezfs** [comment]
@apjanke there's also https://github.com/Homebrew/homebrew-core/pull/5619/files. Note especially line 127.

**Comment by apjanke** [comment]
Ah, great. That looks like it covers it.

**Comment by RandomDSdevel** [comment]
@apjanke, @ilovezfs:  Thanks for taking the time to figure this out despite whatever hassles it might have caused you!  Yeah, Qt _does_ take a painfully long time to build, doesn't it?  (And _you_ guys have _newer_ machines…)

**Comment by ilovezfs** [comment]
@RandomDSdevel why aren't you using the bottle?

**Comment by RandomDSdevel** [comment]
@ilovezfs:  I just prefer having the functionality offered by Homebrew formulas' extra build options available and like building from source in general, that's all.  Just consider my usage patterns an additional source of testing coverage!  😜

**Comment by ilovezfs** [comment]
@RandomDSdevel I don't mind if you want to build from source. Just making sure it's not forcing you into building from source for some reason.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Yeah, it was a manual choice on my part.  I can understand your concern, though, as I know that isn't Homebrew's default behavior.

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel Is your issue resolved here? It's not clear to me. Thanks!

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  Given that none of the other issues mentioned here are related to this one in any way other than that this one has been hindering me in any attempts to contribute to solving those other ones, probably not, but I'm running a build right now just to make sure.  I'll post my new logs when it finishes if it errors out.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  OK, my build failed once again, so [here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/v5.7.0/Second%20Recorded%20Attempt) are the relevant logs.

**Comment by MikeMcQuaid** [comment]
I'm afraid I'm not sure what's going on here but amended the issue title to be a little clearer.

**Comment by ilovezfs** [comment]
@MikeMcQuaid this was already fixed in steve3d's PR. It's just waiting for Andrew or me to get to it.

**Comment by MikeMcQuaid** [comment]
@ilovezfs Ah, cool, thanks.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Didn't you ask @steve3d to split his MySQL/OpenSSL changes out of [that PR](https://github.com/Homebrew/homebrew-core/pull/5619) in [this comment](https://github.com/Homebrew/homebrew-core/pull/5619#issuecomment-254043471)?

**Comment by ilovezfs** [comment]
@RandomDSdevel indeed.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Given that @steve3d's contribution history for the year (scroll down a bit on [his user page filtered to show only the relevant results](https://github.com/steve3d?tab=overview&from=2016-10-01&to=2016-10-26) if the page doesn't jump there automatically upon being opened) shows that he hasn't wandered back over here to Homebrew Core since he submitted PR #5619, may I assume that either you (or I, if it's safe to work on a PR locally when you aren't sure whether the state of your Homebrew installation could be considered clean or not) should do the work of splitting that part of the PR out into another one for him?  If you want _me_ to do it, though, you'll probably have to help me make sure I grab the right changes from his attempted contribution.

**Comment by apjanke** [comment]
I'm actually working on this right now. Might take a bit to actually get the PR posted, because the build takes a while and this requires testing multiple combinations of build options.

**Comment by RandomDSdevel** [comment]
@apjanke:  All right, great!  Post a link to that PR once you get it submitted, would you?

**Comment by apjanke** [comment]
Of course.

**Comment by apjanke** [comment]
Here's a PR: #6309. Would you mind testing it and see if it fixes things for you? Works for me locally, in that `qt5 --with-postgresql --with-mysql` builds successfully, and the linkage looks okay.

**Comment by steve3d** [comment]
That PR will fail, because only if you give the qmake where to find `-lssl`, the mysql/postgresql plugin will always fail.

because `mysql_config --libs` will give the `-lssl` but without the location of  libssl.1.0.0.dylib, it will fail without doubt.

I'm working on a new PR to fix this.

**Comment by ilovezfs** [comment]
>That PR will fail, because if you don't give the qmake where to find -lssl, the mysql/postgresql plugin will always fail.

@steve3d I'm not sure how to reconcile that comment with @apjanke's saying `qt5 --with-postgresql --with-mysql builds successfully, and the linkage looks okay`.

**Comment by steve3d** [comment]
@ilovezfs, sorry, my mistake, @apjanke 's PR will success, it's the same with my first pr, because we all add `-L/usr/local/opt/openssl/lib` to global link flags, this will cause another minor problem, which is every qt module how have this link flag, even if you only need the qtcore module.

**Comment by steve3d** [comment]
@ilovezfs , this is not a qt related bug, check my comments on my own PR #6319

**Comment by steve3d** [comment]
I've updated my PR, turns out the real problem is `mysql_config --libs` and `mysql_config --libs_r` both have `-lssl -lcrypto` flags, these caused the real problem, as to postgresql, it's already works fine.

mysql_config returned that any library using libmysql should also link to openssl library, this only needed for static linking, as for dynamic link, there is no need to link to openssl library when you want to link mysql libs.

so until mysql_config's problem been fixed, the only option is to patch qtbase/configure to filter out `-lssl -lcrypto` from mysql_config's result.

**Comment by steve3d** [comment]
and more digging:
```
Usage: /usr/bin/mysql_config [OPTIONS]
Options:
        --cflags         [-I/usr/include/mysql ]
        --include        [-I/usr/include/mysql]
        --libs           [-L/usr/lib  -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto]
        --libs_r         [-L/usr/lib  -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto]
        --plugindir      [/usr/lib/mysql/plugin]
        --socket         [/var/run/mysqld/mysqld.sock]
        --port           [0]
        --version        [10.1.18]
        --libmysqld-libs [-L/usr/lib  -lmysqld -lpthread -lz -lm -ldl -lssl -lcrypto -lpcre -lcrypt -llz4 -laio]
        --variable=VAR   VAR is one of:
                pkgincludedir [/usr/include/mysql]
                pkglibdir     [/usr/lib]
                plugindir     [/usr/lib/mysql/plugin]
```

this is the default mariadb 10.1.18 under ubuntu, it also have `-lssl -lcrypto`.

**Comment by ilovezfs** [comment]
@steve3d since the brew mysql and postgresql formulae unconditionally depend on openssl, why would we try to disable that feature in qt5?

**Comment by steve3d** [comment]
@ilovezfs because the libssl.1.0.0.dylib and libcrypto.1.0.0.dylib was not installed on /usr/local/lib, so with these link flags, qt will refuse to build mysql sql plugin, (this is not a error, without mysql, qt still builds)

in order to get mysql plugin working, one of these are needed

1. install libssl.1.0.0.dylib and libcrypto.1.0.0.dylib to /usr/local/lib
2. add -L/usr/local/opt/openssl/lib to linker flags, either global(which will cause every qt model have this flag), or patch qt's configure to only add this to mysql plugin
3. remove `-lssl -lcrypto` from either mysql_config( seems it's not a good solution, because default linux also have these), or remove it in qt's configure.

unless of course, You don't need a mysql plugin for qt with homebrew.

**Comment by apjanke** [comment]
@RandomDSdevel It would be nice to be able to test Qt's mysql functionality so we can see what's going on at run time once we get this built. Do you have an example of some code or a program we could use to exercise this plugin? What are you using it for?

**Comment by RandomDSdevel** [comment]
@apjanke:  Unfortunately, I do not _currently_ have any true _personal_ use cases for using Qt's MySQL functionality just yet, but am setting it up to prepare for the general eventuality that I _might_ have to use it in the future.  (I actually tend to do this for a _lot_ of software and, like somebody else who said they do likewise&thinsp;—&thinsp;can't find that issue/PR comment for the life of me, though…&thsinp;—, similarly 'go crazy/wild and enable all the options.')  This is due to the fact that these are still 'early'(-ish) days for me when it comes to my activity on the development scene and am still kind of experimenting with and exploring what I can do.  I can still help you guys test Homebrew-driven builds of Qt on my machine, though if you think that would help!  How would I go about doing that with the PR you linked earlier, by the way, or should I possibly just wait until you and/or @ilovezfs deliver a new version of it that somehow addresses the issues @steve3d raised with it?  I _may_ also be able to help you guys look for a possible test case even though I don't have one to present to you guys myself, though that will probably have to wait until tomorrow since I'm about to call it a night.

**Comment by RandomDSdevel** [comment]
Heh, whoops; sorry!  Helping you guys find a test/use case for the functionality this issue complains blocks building Qt 5 nearly slipped my mind last time I was on the computer since I've once again found myself buried in e-mails again lately.  I'll try and remember to see if I can find anything soon, OK?

**Comment by RandomDSdevel** [comment]
Ah, just saw #6374!  Good to know this is still being worked on.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  I'm actually still not able to build Qt after upgrading my local instance of Homebrew Core and thereby applying PR #6319, but I'll file a separate, new issue for this, as I don't think it's related at _all_ to _this_ one.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid, @ilovezfs, @apjanke:  OK, I have, as you can see by the reference notice posted automatically by GitHub to this thread, created a new issue for my outstanding build issues in the form of [#6766:  'Qt v5.7.0 Still Fails to Build on OS X v10.11.6 'El Capitan' After Resolution of Issue #6032'](https://github.com/Homebrew/homebrew-core/issues/6766).  Hopefully we can get this sorted out once and for all this time…
