### ISSUE TITLE
Squashfs 'bus error' on macOS Sierra

### ISSUE THREAD

**Issue by hellvesper** [Homebrew/homebrew-core#6034]
I always got a 'bus error' when trying to unpack squashfs file using the unsqashfs command from squashfs tools. So i found a fixed sources (https://github.com/pieceofsummer/squashfs-tools) and looks like it works properly. I suggest use this sources instead of official or add this fix to patch.

**Comment by dunn** [comment]
Is that the new official upstream?  If not, the patch should be submitted to the upstream before we'll accept it.

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.
