### ISSUE TITLE
brew update  error

### ISSUE THREAD

**Issue by owen19891030** [Homebrew/homebrew-core#6040]
when I input “brew update ”， it suddenly shows that log:
    error: The last gc run reported the following. Please correct the root cause
    and remove .git/gc.log.
   Automatic cleanup will not be performed until the file is removed.
   warning: There are too many unreachable loose objects; run 'git prune' to remove them.

I do like that: "cd "$(brew --repo)" && git prune && git gc" 
this problem still exists

**Comment by MikeMcQuaid** [comment]
Try `brew update --verbose`; it may not be coming from `brew --repo`.

**Comment by ilovezfs** [comment]
This happened on test-bot at least once as well. In that case, it was the homebrew/core repo.

**Comment by owen19891030** [comment]
I find the error ,it's in taps homebrew-science,not core
