### ISSUE TITLE
nim.rb: missing nim man pages

### ISSUE THREAD

**Issue by slonik-az** [Homebrew/homebrew-core#60498]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Install nim with `brew install nim`

## What happened (include command output)
Nim successfully installs latest  nim-1.2.6 from bottle including 'nim', 'nimble', etc executables. But corresponding man pages are missing
```
$ man nim
No manual entry for nim
```
<details>
  <summary>Command output</summary>
  <pre>
No manual entry for nim
  </pre>
</details>

## What you expected to happen
It is expected that a man-page for `nim`, `nimble` are available. Linux distributions like Ubuntu do include these man pages in the binary installation packages.

**Comment by dtrodrigues** [comment]
`brew update && brew reinstall nim` includes the man pages now.
