### ISSUE TITLE
libvirt libvirt_driver_qemu.so No such file or directory

### ISSUE THREAD

**Issue by virajkanwade** [Homebrew/homebrew-core#60514]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

virtqemud

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

2020-09-02 00:12:48.558+0000: 4785651136: info : libvirt version: 6.6.0
2020-09-02 00:12:48.558+0000: 4785651136: info : hostname: XXX.local
2020-09-02 00:12:48.558+0000: 4785651136: error : virModuleLoad:110 : Failed to find module '/usr/local/Cellar/libvirt/6.6.0/lib/libvirt/connection-driver/libvirt_driver_qemu.so': No such file or directory

  </pre>
</details>

## What you expected to happen

I do see /usr/local/Cellar/libvirt/6.6.0/lib/libvirt/connection-driver/libvirt_driver_qemu.bundle

So maybe the compilation options need to be configured to generate shared library .so file

**Comment by SMillerDev** [comment]
`.bundle` is just the macOS standard naming for shared libraries. It should just pick that one up.

CC @iMichka

**Comment by virajkanwade** [comment]
@SMillerDev Well, Sorry, I don't know the internals of virtqemud. It is not working because it cant find .so file.

**Comment by gromgit** [comment]
Looks related to #59738, and therefore fixed by #59846. Please `brew update`, then `brew upgrade libvirt`.

**Comment by virajkanwade** [comment]
@gromgit Thanks. That worked.
