### ISSUE TITLE
gdal failed to build on 10.10.5

### ISSUE THREAD

**Issue by earthflat** [Homebrew/homebrew-core#6052]
Dears,

Since a while I have a problem with building gdal after version 1.11.3_1. All newer gdal-version, currently version 1.11.5, do not build anymore. I need to use the same options as before:

--with-armadillo --with-complete --with-libkml --with-opencl --with-postgresql --with-python3 --with-mysql --with-unsupported

Omitting '--with-unsupprted' has no effect.
Until version 1.11.3_1 updating and installing worked fine so I still have to stick with this version.

Please find the Gist log here:
https://gist.github.com/anonymous/e9ffc401a91c6461346dc668c8ecfd45

Hope somebody can help.
Thanks!

**Comment by MikeMcQuaid** [comment]
Let's continue in the original issue in https://github.com/Homebrew/homebrew-core/issues/3958.
