### ISSUE TITLE
Is sonar-runner still needed if sonar-scanner exists?

### ISSUE THREAD

**Issue by markph0204** [Homebrew/homebrew-core#6055]
[sonar-scanner](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sonar-scanner.rb) and [sonar-runner](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sonar-runner.rb) both exist.  Should sonar-runner be marked for retirement?

If Homebrew only provides latest version of SonarQube - then you can easily retire old 'sonar-runner'.  See for more info/details:  http://stackoverflow.com/questions/39850646/sonarqube-runner-vs-scanner/39852490#39852490

**Comment by MikeMcQuaid** [comment]
Removed it, thanks!
