### ISSUE TITLE
MPlayer dose not support https

### ISSUE THREAD

**Issue by masterhou** [Homebrew/homebrew-core#60573]
# Bug report
MPlayer 1.4-4.2.1 (C) 2000-2019 MPlayer Team
Can't init Apple Remote.

Playing https://xxxx.mp4
libavformat version 58.27.102 (internal)
https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
Failed to open https://xxxx.mp4

try: 
brew install mplayer --with-openssl
Error: invalid option: --with-openssl

but ffplay https://xxxx.mp4 is OK

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
