### ISSUE TITLE
RabbitMq with rabbitmq-server command is not running on MAC CATALINA 10.15.5 

### ISSUE THREAD

**Issue by grewal25** [Homebrew/homebrew-core#60655]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to run Rabbitmq on my MAC CATALINA 10.15.5 and seeing this error everytime I run rabbitmq-server .

## What happened (include command output)

$rabbitmq-server

Crash dump is being written to erl_crash.dump...done
init terminating in do_boot ()

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

I expect it to run the server

## Step-by-step reproduction instructions (by running `brew install` commands)

1. brew update

2. brew install rabbitmq

3. export PATH=$PATH:/usr/local/sbin in ~/.bashrc

4. run rabbitmq-server

5. Error: 
Crash dump is being written to erl_crash.dump...done
init terminating in do_boot ()

**Comment by SMillerDev** [comment]
I just did a clean install of rabbitmq and it's dependencies and can't reproduce this on catalina. Please actually follow the issue template and we can reopen it when we have the required info.

**Comment by grewal25** [comment]
how did you do the clean up? Because I removed Erlang and Rabbitmq few times but it is still giving me same error.

**Comment by SMillerDev** [comment]
I just never had either installed.

**Comment by grewal25** [comment]
yes, I did on my wife's computer and it worked. I have no clue why it is not working on my machine.
