### ISSUE TITLE
Bottles missing for ocamlsdl

### ISSUE THREAD

**Issue by Kreeblah** [Homebrew/homebrew-core#60741]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I submitted https://github.com/Homebrew/homebrew-core/pull/60740 and it was going through the CI checks.

## What happened (include command output)

The CI job failed when downloading the following bottles:
https://homebrew.bintray.com/bottles/ocamlsdl-0.9.1_14.high_sierra.bottle.tar.gz
https://homebrew.bintray.com/bottles/ocamlsdl-0.9.1_14.mojave.bottle.tar.gz
https://homebrew.bintray.com/bottles/ocamlsdl-0.9.1_14.catalina.bottle.tar.gz

## What you expected to happen

I would have expected the dependent files to still be there.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew fetch --retry ocamlsdl

**Comment by SMillerDev** [comment]
@chenrui333 ui did the ocaml merge. Any ideas?
