### ISSUE TITLE
icu4c 67.1 install error

### ISSUE THREAD

**Issue by sylar2019** [Homebrew/homebrew-core#60759]
# Bug report

/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block in system': Failed executing: make (BuildError)
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:142:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:154:in `rescue in <main>'
	7: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:439:in `dump'
	6: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:385:in `issues'
	5: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:389:in `fetch_issues'
	4: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:314:in `issues_for_formula'
	3: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:302:in `search_issues'
	2: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:409:in `search'
	1: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:227:in `open_api'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:279:in `raise_api_error': curl failed!   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current (GitHub::HTTPNotFoundError)

**Comment by gromgit** [comment]
Please fill in the issue template. You haven't shared enough information to determine what the issue is.
