### ISSUE TITLE
Caveat missing for "sbin" binaries

### ISSUE THREAD

**Issue by bartskowron** [Homebrew/homebrew-core#60763]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

This where all it started ;)

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

config:
```HOMEBREW_VERSION: 2.4.16
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2a4c9f610e69b9fed1eec61ac2c53e4b11a32e4c
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 642b748a2f1029ee2afb0188a5ced5d543be4456
Core tap last commit: 70 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1597368733
Xcode: 11.7
```

doctor:
```Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

## What you were trying to do (and why)

I was installing a package that contains targeted binaries in "sbin" directory.

## What happened (include command output)

Nothing happened. I run `brew install arping` and the installation went smoothly. However, no information about a necessity to add sbin to $PATH in caveat during installation.

## What you expected to happen

I expected to receive a caveat similar to the one from `brew doctor` that suggests to add `sbin` directory to the $PATH as this path was not set in my environment.

Please see: https://github.com/Homebrew/legacy-homebrew/pull/38778
It looks like this problem was already fixed in 2016 or we have a regression.

**Comment by SMillerDev** [comment]
We have a doctor check and the install script mentions it AFAIK. I don't think we should be spamming people about a location with binaries that by convention aren't for regular users.

**Comment by bartskowron** [comment]
> We have a doctor check and the install script mentions it AFAIK. I don't think we should be spamming people about a location with binaries that by convention aren't for regular users.

Please read the original topic here: https://github.com/Homebrew/legacy-homebrew/pull/38778

There are already enough arguments to inform people about it. And looks like everybody agreed about it even if there were already some concerns. To inform especially people who wanted to install the particular application. They expect to use brew to have working environment, no to make another layer of manual installing/configuration. Otherwise, what is a purpose of the Homebrew?

**Comment by SMillerDev** [comment]
I did read the issue, and it seems that general caveat is now known as a doctor check. That PR is pre-1.0 and we're currently approaching 2.5. A lot has happened in the meantime.

**Comment by bartskowron** [comment]
I might be wrong but once I installed arping and didn't get any information such as output of doctor, caveat or suggestion to take a look into doctor. It basically seems installed with zeroconf. As long as I understand there should be automatically printed information from the doctor which does not happen.

The PR is old, I referred to it just to show already discussed arguments about "sbin" matters and that some kind of information should be done. I guess it was working as expected but stopped in the meantime.

**Comment by dtrodrigues** [comment]
Are you sure nothing was printed when you installed `arping`? I removed `/usr/local/sbin` from my path and installed `arping` and got the following warning:
```
$ brew install arping
==> Downloading https://homebrew.bintray.com/bottles/arping-2.21_1.catalina.bottle.tar.gz
==> Pouring arping-2.21_1.catalina.bottle.tar.gz
Warning: /usr/local/sbin is not in your PATH
You can amend this by altering your /Users/username/.bash_profile file.
==> Summary
🍺  /usr/local/Cellar/arping/2.21_1: 6 files, 84.5KB
```

**Comment by bartskowron** [comment]
You are correct. I missed it.
This actually show the real scenario that happened to me. I installed multiple packages at that time. As post install informations are presented at the end of the installation process, I only verified the summary with caveats displayed for all the installed packages. There was no warning there.

**Comment by jonchang** [comment]
Looks like this is solved then.
