### ISSUE TITLE
Error: icu4c 67.1 did not build

### ISSUE THREAD

**Issue by sylar2019** [Homebrew/homebrew-core#60760]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew install icu4c

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

==> Formula
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb
==> Configuration
HOMEBREW_VERSION: 2.4.16
ORIGIN: https://mirrors.cloud.tencent.com/homebrew/brew.git
HEAD: 2a4c9f610e69b9fed1eec61ac2c53e4b11a32e4c
Last commit: 7 days ago
Core tap ORIGIN: https://mirrors.cloud.tencent.com/homebrew/homebrew-core.git
Core tap HEAD: 65a3e7ef015a9838cd11041afe4d141243aef241
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.cloud.tencent.com/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 9.0 build 900
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.2, 1.8.0_211, 1.8.0_152, 1.8.0_40
macOS: 10.12.6-x86_64
CLT: 9.2.0.0.1.1510905681
Xcode: N/A
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
HOMEBREW_GIT: git
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin

Error: icu4c 67.1 did not build
Logs:
     /Users/sylar/Library/Logs/Homebrew/icu4c/00.options.out
     /Users/sylar/Library/Logs/Homebrew/icu4c/01.configure
     /Users/sylar/Library/Logs/Homebrew/icu4c/01.configure.cc
     /Users/sylar/Library/Logs/Homebrew/icu4c/02.make
     /Users/sylar/Library/Logs/Homebrew/icu4c/02.make.cc
Do not report this issue to Homebrew/brew or Homebrew/core!

Traceback (most recent call last):
	25: from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'
	24: from /usr/local/Homebrew/Library/Homebrew/build.rb:140:in `install'
	23: from /usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
	22: from /usr/local/Homebrew/Library/Homebrew/build.rb:145:in `block in install'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1192:in `brew'
	20: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2161:in `stage'
	19: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:86:in `stage'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:111:in `unpack'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:201:in `mktemp'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	12: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `block in unpack'
	11: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2181:in `block in stage'
	10: from /usr/local/Homebrew/Library/Homebrew/utils.rb:492:in `with_env'
	 9: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2182:in `block (2 levels) in stage'
	 8: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1199:in `block in brew'
	 7: from /usr/local/Homebrew/Library/Homebrew/build.rb:177:in `block (2 levels) in install'
	 6: from /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb:32:in `install'
	 5: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	 4: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	 3: from /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/icu4c.rb:34:in `block in install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1975:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1975:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2037:in `block in system': Failed executing: make (BuildError)
	9: from /usr/local/Homebrew/Library/Homebrew/brew.rb:142:in `<main>'
	8: from /usr/local/Homebrew/Library/Homebrew/brew.rb:154:in `rescue in <main>'
	7: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:439:in `dump'
	6: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:385:in `issues'
	5: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:389:in `fetch_issues'
	4: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:314:in `issues_for_formula'
	3: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:302:in `search_issues'
	2: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:409:in `search'
	1: from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:227:in `open_api'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:279:in `raise_api_error': curl failed!   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current (GitHub::HTTPNotFoundError)
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  171k    0  171k    0     0   8423      0 --:--:--  0:00:20 --:--:--  7036

  </pre>
</details>

## What you expected to happen

brew install boost -v

**Comment by SMillerDev** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!

You're running an unsupported macOS version.

**Comment by SMillerDev** [comment]
Also, you're not using the homebrew source. You're using an unsupported mirror.
