### ISSUE TITLE
mbedtls 2.23.0 build fails due to 'missing' python 3

### ISSUE THREAD

**Issue by HenkPoley** [Homebrew/homebrew-core#60778]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrading mbedtls 2.16.6 -> 2.23.0 from source. I have python@3.8 version 3.8.5 installed (with brew).

Failure probably has to do with these changes (my `cmake` is 3.18.2) so the build doesn't properly find python 3: https://github.com/ARMmbed/mbedtls/pull/3125

`brew gist-logs mbedtls`:
* supported system: https://gist.github.com/fc7a4ef6135326d3f98c317c1f8c66be
* 'un'supported system (same error): https://gist.github.com/520265770fb01d4a1a4b525017f24345

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew upgrade --build-from-source mbedtls
==> Upgrading 1 outdated package:
mbedtls 2.16.6 -> 2.23.0
==> Upgrading mbedtls 2.16.6 -> 2.23.0 
==> Downloading https://github.com/ARMmbed/mbedtls/archive/mbedtls-2.23.0.tar.gz
Already downloaded: /Users/henk/Library/Caches/Homebrew/downloads/904abe66ab307886754d8d99f96e512b94e3c6b9d970575ece7a4587c637a062--mbedtls-mbedtls-2.23.0.tar.gz
==> cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On
Last 15 lines from /Users/henk/Library/Logs/Homebrew/mbedtls/01.cmake:
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at tests/CMakeLists.txt:21 (message):
  Cannot build test suites without Python 3

-- Configuring incomplete, errors occurred!
See also "/tmp/mbedtls-20200908-60439-1sufr9g/mbedtls-mbedtls-2.23.0/CMakeFiles/CMakeOutput.log".

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

The build system to find python 3 and just continue to work.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade --build-from-source mbedtls`

Note: mbedtls 2.24.0 didn't have a fix for this either.

**Comment by SMillerDev** [comment]
Why are you building it from source?

**Comment by HenkPoley** [comment]
Because otherwise it doesn't work in my particular setup.

Is there a trick to make it go? If you like I can submit the mbedtls 0.24.0 Formula, and then someone can fix that one before a pre-built bottle is made.

btw, HEAD also won't compile: 

```
$ brew install --build-from-source mbedtls --HEAD
==> Cloning https://github.com/ARMmbed/mbedtls.git
Updating /Users/henk/Library/Caches/Homebrew/mbedtls--git
==> Checking out branch development
Already on 'development'
Your branch is up to date with 'origin/development'.
HEAD is now at 1ffec8f Merge pull request #3501 from stevew817/feature/transparent_drivers_trial
==> cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On
Last 15 lines from /Users/henk/Library/Logs/Homebrew/mbedtls/01.cmake:
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
CMake Error at tests/CMakeLists.txt:21 (message):
  Cannot build test suites without Python 3


-- Configuring incomplete, errors occurred!
See also "/tmp/mbedtls-20200908-73557-1lxkgmj/CMakeFiles/CMakeOutput.log".

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by SMillerDev** [comment]
You can try setting `Python3_EXECUTABLE` to `#{Formula["python@3.8"].opt_bin}/python3` in the cmake flags as it's suggesting. Though the bottle builds worked fine so I think this is an issue in your setup.

Either way updates are always welcome.

**Comment by HenkPoley** [comment]
So I have 2 broken macOS sytems?

**Comment by HenkPoley** [comment]
I guess with the release of 2.24.0 with the 'fix' in this can close now.

I am wondering though if this is not some kind of bug in the brew system that makes python3 available to the builds.

**Comment by paul-elliott-arm** [comment]
This would appear to be a cmake issue, however I am tracking this issue here : https://github.com/ARMmbed/mbedtls/issues/3690

I will also submit a workaround fix shortly. In future, please do feel free to submit bugs directly to us!
