### ISSUE TITLE
 -- Configuring incomplete, errors occurred! See also "/tmp/ettercap-20200910-2433-1gtdywk/ettercap-0.8.3.1/build/CMakeFiles/CMakeOutput.log". See also "/tmp/ettercap-20200910-2433-1gtdywk/ettercap-0.8.3.1/build/CMakeFiles/CMakeError.log".

### ISSUE THREAD

**Issue by ma8ai** [Homebrew/homebrew-core#60873]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by ma8ai** [comment]
brew install

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
