### ISSUE TITLE
ssreflect install fails

### ISSUE THREAD

**Issue by dgenin** [Homebrew/homebrew-core#609]
When running `brew install ssreflect` build fails with

File "src/ssrmatching.mli", line 76, characters 14-34:
Error: Unbound type constructor glob_constr_and_expr
make[1]: *** [src/ssrmatching.cmi] Error 2
make: *** [all] Error 2

gist-logs link: https://gist.github.com/b436a33d81a717b8c0893114479680ed

**Comment by ilovezfs** [comment]
Yes, this is a known issue: https://github.com/Homebrew/homebrew-core/issues/342

As mentioned in this [comment](https://github.com/Homebrew/homebrew-core/issues/342#issuecomment-212914717), the present brew version is superseded by https://github.com/math-comp/math-comp, which I'd recommend you try installing with opam as described in their readme there.

**Comment by ilovezfs** [comment]
@dgenin You can `brew pull 1166` if you'd like to test out the fix: https://github.com/Homebrew/homebrew-core/pull/1166

**Comment by ilovezfs** [comment]
#1166 is now merged: https://github.com/Homebrew/homebrew-core/commit/d3d1627443f3d2be8947fad46ab22b008a194e28

So if you brew update, you should be able to install a bottled binary of the fixed version.

**Comment by dgenin** [comment]
@ilovezfs I ended up installing ssreflect via opam but it's great that you got this fixed. I will try the brew version when I next upgrade Coq.
