### ISSUE TITLE
`brew install pkg1 pkg2 ...` : should show brew install pkgi right before installing each one

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-core#6097]
eg use case:
```
./bin/brew install `brew list --full-name`
```
it may crash while installing one of the packages, but it can be non-obvious to guess which one it crashed at.

Or, when `brew install single_pckg` is called from another program

**Comment by bfontaine** [comment]
It already prints `==> Installing <formula> [from <tap>]` before installing each one.

**Comment by MikeMcQuaid** [comment]
> It already prints ==> Installing <formula> [from <tap>] before installing each one.

Closing due to this.
