### ISSUE TITLE
Leaps remote pair programming application

### ISSUE THREAD

**Issue by andyjeffries** [Homebrew/homebrew-core#610]
### Formula Request:

I understand that **the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md).** however, I don't really know where to start.

I want to get https://github.com/Jeffail/leaps in to Homebrew as it's really awesome for remote pair programming (even within the same office if you're lazy/in the flow).

If anyone can point me to a simple doc or example on getting a Golang based application in to Homebrew I'm happy to work on it, then submit a PR.

cc: @jeffail.

**Comment by ilovezfs** [comment]
You'll want to clone https://github.com/Homebrew/homebrew-core/ and grep for 'depends_on "go"' and 'go_resource' and 'godep' in the Formula directory for examples.

https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#specifying-gems-python-modules-go-projects-etc-as-dependencies

**Comment by andyjeffries** [comment]
Thanks for your help so far @ilovezfs. I've got a first version here:

https://github.com/andyjeffries/homebrew-core/commit/85e7a4f736c78e612f40daf79706003bb9400240

All dependencies are already vendored. However, I now have two questions:

1) How to do I test my formula locally?

2) There are already compiled releases available from https://github.com/Jeffail/leaps/releases/tag/v0.5.0 but I don't know how to make these in to bottles?

Thanks.

**Comment by ilovezfs** [comment]
You're welcome.

To test it locally, you can add a symlink to leaps.rb (you need to rename the file) in /usr/local/Library/Taps/homebrew-core. Then run `brew install --build-from-source -dv leaps`.

To run the test block `brew test -v leaps` after it's successfully installed.

To audit the formula, `brew audit --strict leaps`.

Bottling is done automatically by the bottle bot whenever a formula is added or updated.

If you want to make a bottle locally, `brew test-bot leaps` is the simplest way.

**Comment by andyjeffries** [comment]
Thanks for all this.  So, I've got it installing and working (I can brew install it and run it and it works fine).

I've got the formula audited with zero problems.

I ran the test-bot command, but it failed with this (I don't think it's anything to do with my formula):

```

  1) Failure:
TapTest#test_install_git_error [/usr/local/Library/Homebrew/test/test_tap.rb:202]:
[ErrorDuringExecution]
 exception expected, not
Class: <Errno::ENOENT>
Message: <"No such file or directory - /var/folders/m7/dhj5rp051j32p98zwqbtxrnw0000gn/T/homebrew_tests20160426-90051-1nrhk1k/prefix/Library/Taps/user/homebrew-repo">
---Backtrace---
/usr/local/Library/Homebrew/extend/pathname.rb:50:in `lstat'
/usr/local/Library/Homebrew/extend/pathname.rb:50:in `lstat'
/usr/local/Library/Homebrew/extend/pathname.rb:50:in `compute_disk_usage'
/usr/local/Library/Homebrew/extend/pathname.rb:21:in `abv'
/usr/local/Library/Homebrew/tap.rb:227:in `install'
/usr/local/Library/Homebrew/test/test_tap.rb:203:in `block (2 levels) in test_install_git_error'
/usr/local/Library/Homebrew/test/testing_env.rb:83:in `shutup'
/usr/local/Library/Homebrew/test/test_tap.rb:203:in `block in test_install_git_error'
---------------

849 runs, 2044 assertions, 1 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
rake aborted!
Command failed with status (1): [ruby -I"lib:/usr/local/Library/Homebrew/test" -I"/usr/local/Library/Homebrew/test/vendor/bundle/ruby/2.0.0/gems/rake-10.5.0/lib" "/usr/local/Library/Homebrew/test/vendor/bundle/ruby/2.0.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "/usr/local/Library/Homebrew/test/test_ARGV.rb" "/usr/local/Library/Homebrew/test/test_bash.rb" "/usr/local/Library/Homebrew/test/test_blacklist.rb" "/usr/local/Library/Homebrew/test/test_bottle_collector.rb" "/usr/local/Library/Homebrew/test/test_bottle_filename.rb" "/usr/local/Library/Homebrew/test/test_bottle_hooks.rb" "/usr/local/Library/Homebrew/test/test_bottle_tag.rb" "/usr/local/Library/Homebrew/test/test_build_environment.rb" "/usr/local/Library/Homebrew/test/test_build_options.rb" "/usr/local/Library/Homebrew/test/test_caveats.rb" "/usr/local/Library/Homebrew/test/test_checksum.rb" "/usr/local/Library/Homebrew/test/test_checksum_verification.rb" "/usr/local/Library/Homebrew/test/test_cleaner.rb" "/usr/local/Library/Homebrew/test/test_cleanup.rb" "/usr/local/Library/Homebrew/test/test_cmd_audit.rb" "/usr/local/Library/Homebrew/test/test_cmd_info.rb" "/usr/local/Library/Homebrew/test/test_commands.rb" "/usr/local/Library/Homebrew/test/test_compiler_failure.rb" "/usr/local/Library/Homebrew/test/test_compiler_selector.rb" "/usr/local/Library/Homebrew/test/test_dependencies.rb" "/usr/local/Library/Homebrew/test/test_dependency.rb" "/usr/local/Library/Homebrew/test/test_dependency_collector.rb" "/usr/local/Library/Homebrew/test/test_dependency_expansion.rb" "/usr/local/Library/Homebrew/test/test_diagnostic.rb" "/usr/local/Library/Homebrew/test/test_download_strategies.rb" "/usr/local/Library/Homebrew/test/test_ENV.rb" "/usr/local/Library/Homebrew/test/test_exceptions.rb" "/usr/local/Library/Homebrew/test/test_formula.rb" "/usr/local/Library/Homebrew/test/test_formula_installer.rb" "/usr/local/Library/Homebrew/test/test_formula_installer_bottle.rb" "/usr/local/Library/Homebrew/test/test_formula_lock.rb" "/usr/local/Library/Homebrew/test/test_formula_pin.rb" "/usr/local/Library/Homebrew/test/test_formula_spec_selection.rb" "/usr/local/Library/Homebrew/test/test_formula_support.rb" "/usr/local/Library/Homebrew/test/test_formula_validation.rb" "/usr/local/Library/Homebrew/test/test_formulary.rb" "/usr/local/Library/Homebrew/test/test_hardware.rb" "/usr/local/Library/Homebrew/test/test_inreplace.rb" "/usr/local/Library/Homebrew/test/test_integration_cmds.rb" "/usr/local/Library/Homebrew/test/test_json.rb" "/usr/local/Library/Homebrew/test/test_keg.rb" "/usr/local/Library/Homebrew/test/test_language_go.rb" "/usr/local/Library/Homebrew/test/test_language_module_requirement.rb" "/usr/local/Library/Homebrew/test/test_mach.rb" "/usr/local/Library/Homebrew/test/test_migrator.rb" "/usr/local/Library/Homebrew/test/test_mpi_requirement.rb" "/usr/local/Library/Homebrew/test/test_options.rb" "/usr/local/Library/Homebrew/test/test_patch.rb" "/usr/local/Library/Homebrew/test/test_patching.rb" "/usr/local/Library/Homebrew/test/test_pathname.rb" "/usr/local/Library/Homebrew/test/test_pkg_version.rb" "/usr/local/Library/Homebrew/test/test_requirement.rb" "/usr/local/Library/Homebrew/test/test_resource.rb" "/usr/local/Library/Homebrew/test/test_sandbox.rb" "/usr/local/Library/Homebrew/test/test_software_spec.rb" "/usr/local/Library/Homebrew/test/test_stdlib.rb" "/usr/local/Library/Homebrew/test/test_string.rb" "/usr/local/Library/Homebrew/test/test_tab.rb" "/usr/local/Library/Homebrew/test/test_tap.rb" "/usr/local/Library/Homebrew/test/test_update_report.rb" "/usr/local/Library/Homebrew/test/test_utils.rb" "/usr/local/Library/Homebrew/test/test_version_subclasses.rb" "/usr/local/Library/Homebrew/test/test_versions.rb" "/usr/local/Library/Homebrew/test/test_x11_requirement.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
Warning: File leak is detected
TapTest#test_install_git_error [/usr/local/Library/Homebrew/test/test_tap.rb:202]
```

The only problem is the `brew test -v leaps` part.  If I run the command it runs I get this:

```
15:54 andy  $ /usr/local/Cellar/leaps/0.5.0/bin/leaps --help
Usage of /usr/local/Cellar/leaps/0.5.0/bin/leaps:
  -address string
    	The HTTP address to bind to (default ":8080")
  -all
    	Display all files, including hidden
15:54 andy  $ 
```

If I run it through `brew test -v leaps` I get:

```
15:53 andy  $ brew test -v leaps
Testing leaps
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160426-90991-yqve1p.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /Users/andy/Code/vendor/homebrew-core/Formula/leaps.rb -v
==> /usr/local/Cellar/leaps/0.5.0/bin/leaps --help
Usage of /usr/local/Cellar/leaps/0.5.0/bin/leaps:
  -address string
    	The HTTP address to bind to (default ":8080")
  -all
    	Display all files, including hidden
Error: leaps: failed
Failed executing: /usr/local/Cellar/leaps/0.5.0/bin/leaps --help
/usr/local/Library/Homebrew/formula.rb:1481:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1418:in `open'
/usr/local/Library/Homebrew/formula.rb:1418:in `system'
/Users/andy/Code/vendor/homebrew-core/Formula/leaps.rb:85:in `block in <class:Leaps>'
/usr/local/Library/Homebrew/formula.rb:1327:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:36:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1323:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

Any ideas?  Then I can squash these commits and raise the PR.

Thanks for your help.

**Comment by andyjeffries** [comment]
https://github.com/Homebrew/homebrew-core/compare/master...andyjeffries:master

**Comment by ilovezfs** [comment]
The problem with the test is that the exit code needs to be 0 unless you tell it otherwise. So you'd want something like this instead:
```
shell_output("#{bin}/leaps --help 2>/dev/null", 2)
```
However, some kind of functional test would be preferable if it's at all possible.

The test-bot failure is a bit more mysterious. Maybe you can try running `brew tests -v` and see if it sheds any light.

**Comment by andyjeffries** [comment]
I don't know how feasible a functional test would be (or how easy to write). It'd need to run leaps, curl a particular port and look for a string, then kill the background running leaps.  I'll change it to the above first (I'll give it a test first).

**Comment by ilovezfs** [comment]
There are several tests like what you just described in the Formula directory. For example, `websocketd.rb`.

**Comment by andyjeffries** [comment]
Yeah, thanks @ilovezfs I actually found another one (algernon or something like that) because I was thinking "surely someone else has done this" and have got a working test that fires up the server, hits it and shuts it down.

Just looking at the test-bot failure (after doing a `brew update`).  More to follow...

**Comment by andyjeffries** [comment]
The test-bot failed again exactly the same (but I'm thinking it's something weird in my homebrew installation, I sometimes get errors updating).

`brew tests -v` just returned the same error.

I'll raise the PR and see if anyone else gets it.

**Comment by ilovezfs** [comment]
You can move your brew installation out of the way temporarily to test that theory.

```
mkdir ~/Documents/brew-20160426
sudo mv /usr/local ~/Documents/brew-20160426
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tests -v
```

**Comment by andyjeffries** [comment]
I tried that and things went horribly wrong (no git utility any more) so I put it back.

I've raised the PR now - at some point I'll wipe my homebrew installation and re-install, but I need my system to be working too much to do it now...

https://github.com/Homebrew/homebrew-core/pull/627

**Comment by ilovezfs** [comment]
That's odd, unless it has to do with your profile, since git is usually just `/usr/bin/git`, which runs `/Applications/Xcode.app/Contents/Developer/usr/bin/git`.

Anyway, make sure you can run `brew tests` without any failures when it's convenient to do so.

Thanks for the PR.
