### ISSUE TITLE
Octave 5.2.0 built without qscintilla2 editor

### ISSUE THREAD

**Issue by siko1056** [Homebrew/homebrew-core#61141]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew gist-logs octave
Error: No logs.

$ brew config
HOMEBREW_VERSION: 2.5.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c7e4a3d8b9835a94edb3a6744b6f66cac06cf064
Last commit: 20 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ab7a1fda247ecdf796906bb6e6b9abdbd642741
Core tap last commit: 58 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 12.0.31.1
Xcode: 11.5
```

## What you were trying to do (and why)

I opened GNU Octave in GUI mode and wanted to open the Editor widget.  Usually available by a GUI option and inside a tab in the default view.

```
octave --gui
```

## What happened (include command output)

The qscintilla2 based builtin editor is not available

```
>> __octave_config_info__ ("QSCINTILLA")
ans = 0
```

## What you expected to happen

I expected the qscintilla2 based builtin editor to open.

The solution to this would be to build Octave with qscintilla2 support, i.e., configure

https://github.com/Homebrew/homebrew-core/blob/master/Formula/octave.rb

using

https://github.com/Homebrew/homebrew-core/blob/master/Formula/qscintilla2.rb

I am involved in Octave development, but don't know much about Homebrew development, neither I am a regular Homebrew user myself.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install octave
```

**Comment by SMillerDev** [comment]
Feature requests should be done as pull requests. Just give it a try and we can always help if you can't figure it out.
