### ISSUE TITLE
why is wxmac built with --disable-debug?

### ISSUE THREAD

**Issue by rkitover** [Homebrew/homebrew-core#6117]
The formula for wxmac specifies `--disable-debug` in the configure args.

According to: http://docs.wxwidgets.org/trunk/overview_debugging.html

> Starting with wxWidgets 2.9.1 debugging features are always available by default (and not only in a special "debug" build of the library) and you need to predefine wxDEBUG_LEVEL symbol as 0 when building both the library and your application to remove them completely from the generated object code. However the debugging features are disabled by default when the application itself is built with NDEBUG defined (i.e. in "release" or "production" mode) so there is no need to do this, unless the resources of the system your application will be running on are unusually constrained (notice that when asserts are disabled their condition is not even evaluated so the only run-time cost is a single condition check and the extra space taken by the asserts in the code).

In other words, minimal debug code is normally included in the built library and has practically no run-time cost.

When the library is built with `--disable-debug`, and you built your sources with `-DwxDEBUG_LEVEL=1`, the resulting objects cannot link.

Would it be possible to remove this flag?

**Comment by apjanke** [comment]
I had to read through that section a few times to really understand it, but I think I get it.

Removing `--disable-debug` seems to make sense. Given the minimal cost, that would make the bottled library more flexible, and it seems to be the way that wxmac upstream expects you to do things, so we may as well conform.

Would like the hear from another maintainer or two before doing so, though.

**Comment by MikeMcQuaid** [comment]
> Removing --disable-debug seems to make sense. Given the minimal cost, that would make the bottled library more flexible, and it seems to be the way that wxmac upstream expects you to do things, so we may as well conform.
> 
> Would like the hear from another maintainer or two before doing so, though.

Sounds good to me. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by rkitover** [comment]
Sent #6195
