### ISSUE TITLE
brew update raises unexpected token error for java11

### ISSUE THREAD

**Issue by jameskrach** [Homebrew/homebrew-core#61240]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Just run `brew update`

## What happened (include command output)

brew raised the error in the output below and said to report the issue.

<details>
  <summary>Command output</summary>
  <pre>

  $ brew update
Updated Homebrew from 21d4c1ffc to 871abe8b9.
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
...
==> Renamed Formulae
...
==> New Casks
...
==> Updated Casks
...
==> Deleted Casks
java11
Error: 767: unexpected token at '{
  "java11": "homebrew/core",
}
'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tap.rb:544:in `tap_migrations'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:300:in `block in migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:298:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:298:in `migrate_tap_migration'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:122:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/update-report.rb:122:in `update_report'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'

  </pre>
</details>

## What you expected to happen
I didn't expect it to raise an error

## Step-by-step reproduction instructions (by running `brew install` commands)
I just ran `brew update`. I've included the output of `brew config` and `brew doctor` at [this link](https://gist.github.com/jameskrach/754518c666ea32a6f6ade3c57901df37)

**Comment by miccal** [comment]
Already fixed in https://github.com/Homebrew/homebrew-cask-versions/pull/9633.

**Comment by jameskrach** [comment]
Ah I see. I figured I’d point it out in case no one else saw it. Thanks!
