### ISSUE TITLE
swagger-codegen install fails - MethodDeprecatedError java_home_cmd

### ISSUE THREAD

**Issue by black-snow** [Homebrew/homebrew-core#61252]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  https://gist.github.com/ca0d050723941d81c59438364f8a4631
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `swagger-codegen` via brew.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
brew install swagger-codegen
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 34 formulae.

==> Downloading https://github.com/swagger-api/swagger-codegen/archive/v3.0.20.tar.gz
==> Downloading from https://codeload.github.com/swagger-api/swagger-codegen/tar.gz/v3.0.20
######################################################################## 100.0%
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling Language::Java.java_home_cmd is disabled! Use Language::Java.java_home or Language::Java.overridable_java_home_env instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/swagger-codegen.rb:21
  </pre>
</details>

## What you expected to happen

Successful install

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install swagger-codegen`

**Comment by black-snow** [comment]
Thanks for moving the issue @jonchang

**Comment by issyl0** [comment]
This was done in https://github.com/Homebrew/homebrew-core/commit/1a42c0bff6b527566e3fd3127168ef70e6b38735 - thanks again!
