### ISSUE TITLE
ansible missing keyring dependency

### ISSUE THREAD

**Issue by hryamzik** [Homebrew/homebrew-core#61305]
# Bug report

Running anisble with a keyring lookup fails:

```yaml
- debug: msg="{{ lookup('keyring','mysql joe') }}"
```

```
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'keyring'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Can't LOOKUP(keyring): missing required python library 'keyring'"}
```

As keyring is missing in [formula deps](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb)

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
