### ISSUE TITLE
have run upgrade twice - run doctor and this repeats

### ISSUE THREAD

**Issue by TaterFTL** [Homebrew/homebrew-core#61357]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

machine is buggy - tried to upgrade brew - ran brew doctor and was instructed to post to troubleshooting
## What happened (include command output)

% brew doctor 
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: There's not a working version of xattr.
Traceback (most recent call last):
  File "/usr/bin/xattr", line 8, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Error: wrong number of arguments (given 2, expected 1)
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/system_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:17:in `system_command'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:971:in `check_cask_xattr'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:53:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

normal output
## Step-by-step reproduction instructions (by running `brew install` commands)

https://gist.github.com/TaterFTL/a92860e5772299e9a4dbaa14c18eb6e1

**Comment by miccal** [comment]
@TaterFTL please post the output of your `brew config`, thanks.

**Comment by jonchang** [comment]
There's a `brew doctor` bug (which I will shortly file a fix for), but you should have seen the following text:

> Your Python installation has a broken version of setuptools.
> To fix, reinstall macOS or run 'sudo /usr/bin/python -m pip install -I setuptools'.

**Comment by TaterFTL** [comment]
Hey there sorry my machine has been totally crashed and I’m trying to get it back up will send the logs as soon as possible
