### ISSUE TITLE
mac os 10.12

### ISSUE THREAD

**Issue by LIMo927** [Homebrew/homebrew-core#6137]
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing nginx-full from homebrew/nginx
Error: undefined method `rebuild' for #<BottleSpecification:0x007fc501aca9b8>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb:9:in `block in <class:Makedepend>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb:7:in `<class:Makedepend>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/makedepend.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/dependency.rb:32:in `to_formula'
/usr/local/Library/Homebrew/dependency.rb:93:in `block in expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:80:in `expand'
/usr/local/Library/Homebrew/dependency.rb:93:in `block in expand'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependencies.rb:9:in `each'
/usr/local/Library/Homebrew/dependency.rb:80:in `expand'
/usr/local/Library/Homebrew/formula.rb:1220:in `recursive_dependencies'
/usr/local/Library/Homebrew/requirement.rb:196:in `expand'
/usr/local/Library/Homebrew/formula.rb:1226:in `recursive_requirements'
/usr/local/Library/Homebrew/formula_installer.rb:312:in `expand_requirements'
/usr/local/Library/Homebrew/formula_installer.rb:262:in `compute_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:129:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:122:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:213:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:93:in `install'
/usr/local/Library/brew.rb:84:in `<main>'

**Comment by MikeMcQuaid** [comment]
> https://git.io/brew-troubleshooting

Read this and report it to Homebrew/homebrew-nginx.
