### ISSUE TITLE
pecl install pdo error, pecl fails ERROR: `make INSTALL_ROOT="/private/tmp/pear/temp/pear-build-..."

### ISSUE THREAD

**Issue by kemoc** [Homebrew/homebrew-core#61477]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
yes
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
yes
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
it's pecl
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
it's pecl

## What you were trying to do (and why)

run:
```
pecl install pdo
```

## What happened (include command output)

```
running: make

Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/private/tmp/pear/temp/pear-build-radoslawzadrogaWDl0Hm/install-PDO-1.0.3" install
Installing shared extensions:     /private/tmp/pear/temp/pear-build-radoslawzadrogaWDl0Hm/install-PDO-1.0.3/usr/local/Cellar/php@7.3/7.3.22/pecl/20180731/
cp: modules/*: No such file or directory
make: *** [install-modules] Error 1
ERROR: `make INSTALL_ROOT="/private/tmp/pear/temp/pear-build-radoslawzadrogaWDl0Hm/install-PDO-1.0.3" install' failed
```

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

installed PDO

## Step-by-step reproduction instructions (by running `brew install` commands)

`pecl install pdo`

**Comment by SMillerDev** [comment]
https://pecl.php.net/package/PDO says that it shouldn't be used anymore, it hasn't had updates since 2006. This is because PDO has been part of PHP itself since PHP 5.1.
