### ISSUE TITLE
hdf5 package missing pkg-config .pc file

### ISSUE THREAD

**Issue by xanderdunn** [Homebrew/homebrew-core#61490]
On Ubuntu 18.04, installing hdf5 with `sudo apt install libhdf5-dev` places a pkg-config file at `/usr/lib/x86_64-linux-gnu/pkgconfig/hdf5.pc`:
```
Name: HDF5
Description: Hierarchical Data Format 5 (HDF5)
Version: 1.8.13
Requires:
Cflags: -I/usr/include/hdf5/serial
Libs: -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5
```

However, I am unable to find a .pc file when installing hdf5 via Homebrew `brew install hdf5` on my macOS 10.15.6:
`find / -name "hdf5.pc" 2> /dev/null`.
`pkg-config --libs hdf5`.
`brew ls hdf5`

Including a .pc file would greatly aid my ability to write a [cross platform HDF5 Swift library](https://github.com/xanderdunn/HDF5Kit) that finds the location of the headers and libs on both linux and Mac without passing custom arguments to `swift build`.

**Comment by SMillerDev** [comment]
If you can find a way to make it do that if happily review a pull request.

**Comment by xanderdunn** [comment]
Thanks @SMillerDev, I'm not very familiar with HomeBrew. I've never written anything for it. Are .pc files typically a part of the package being installed rather than a part of HomeBrew? Do packages likes openssl and cairo have .pc files because the underlying libraries come with it, not because HomeBrew is doing anything? It looks like `apt` added a .pc file on top of the base hdf5 package. If including a .pc file on top of a package isn't something HomeBrew does, then perhaps I need to open this issue on the HDF5 project instead? 

I do see pkg-config file generation was added in HDF5 [1.10.2](https://github.com/HDFGroup/hdf5/blob/e54f5a14d28cf9eb1226ce7feab2e2600d3984b4/release_docs/HISTORY-1_10.txt#L1109). Assuming that's still working, I wonder if it's not being generated on a macOS build.

**Comment by jonchang** [comment]
> Are .pc files typically a part of the package being installed rather than a part of HomeBrew? Do packages likes openssl and cairo have .pc files because the underlying libraries come with it, not because HomeBrew is doing anything?

Yes, we rarely never write our own pkg-config files.

> It looks like apt added a .pc file on top of the base hdf5 package. If including a .pc file on top of a package isn't something HomeBrew does, then perhaps I need to open this issue on the HDF5 project instead?

Possibly, yes.

> I do see pkg-config file generation was added in HDF5 1.10.2. Assuming that's still working, I wonder if it's not being generated on a macOS build.

Based on that link, it seems that pkg-config support is only included in the cmake build. Currently we build hdf5 using autotools. https://github.com/HDFGroup/hdf5/blob/e54f5a14d28cf9eb1226ce7feab2e2600d3984b4/release_docs/HISTORY-1_10.txt#L370-L375

**Comment by fxcoudert** [comment]
Thanks @xanderdunn for opening the upstream issue. Right now, HDF5 recommends building with autotools on Unix, so we'll continue to do that.
