### ISSUE TITLE
caddy: Regression in PR #60060

### ISSUE THREAD

**Issue by lukasbestle** [Homebrew/homebrew-core#61621]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **(no, formula didn't fail installing)**
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I installed `caddy 2.1.1_1` using Homebrew because I wanted to install it on a new machine.

## What happened (include command output)

`caddy` was successfully installed, but the output of `caddy version` does not meet expectations:

<details>
  <summary>Command output</summary>
  <pre><code>$ brew install caddy
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://homebrew.bintray.com/bottles/caddy-2.1.1_1.catalina.bottle.2.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/c623c1ab4422a4fc4cfe49603ee0eebd64ed8c54d195d8a36bf59cea08d0325f?response-content-disposition=attac
######################################################################## 100.0%
==> Pouring caddy-2.1.1_1.catalina.bottle.2.tar.gz
==> Caveats
To have launchd start caddy now and restart at login:
  brew services start caddy
Or, if you don't want/need a background service you can just run:
  caddy run --config /usr/local/etc/Caddyfile
==> Summary
🍺  /usr/local/Cellar/caddy/2.1.1_1: 7 files, 40.9MB</code></pre>

<pre><code>$ caddy version
v2.1.1 => /private/tmp/caddy-20200909-23695-90m6ax/caddy-2.1.1
</code></pre>
</details>

## What you expected to happen

The version that is printed by `caddy version` should include the signed hash of the installed code:

```
$ caddy version
v2.1.1 h1:X9k1+ehZPYYrSqBvf/ocUgdLSRIuiNiMo7CvyGUQKeA=
```

## Reason and fix

This is a regression caused by https://github.com/Homebrew/homebrew-core/pull/60060.

Go can only reproducibly build modules if Go itself downloads the code and its dependencies. Once a custom path is passed, Go takes that path as the absolute truth and skips calculating hashes.

#60060 should be reverted.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install caddy
caddy version
```

---

Pinging @mholt, the developer of Caddy.

**Comment by SMillerDev** [comment]
Why is this hash important to the functionality of the program?

**Comment by hairyhenderson** [comment]
So, one downside of the way caddy is built in the brew formula is we get [stack traces](https://caddy.community/t/caddy-v-panic-duplicate-metrics-collector-registration-attempted/9915) with stuff like this:

```
github.com/caddyserver/caddy/vHEAD.init.1()
	github.com/caddyserver/caddy/vHEAD@v0.0.0-00010101000000-000000000000/metrics.go:14 +0xb2
```

Makes it very hard for me to trust that the right code is actually being compiled.

**Comment by francislavoie** [comment]
@SMillerDev It's important to have the same version style of information in all builds of Caddy, because it makes it easier to figure out exactly what version of the code someone is running.

This makes `brew` the only build system that does this sort of thing, every other distribution builds with proper version information.

Please revert #60060.

**Comment by hairyhenderson** [comment]
The root issue really is that the `xcaddy` `--with` arg is meant to specify a _module_, not Caddy itself. What's happening is that the produced binary is now calling `init()` twice, which is having some bad side-effects.

If you must build the caddy binary from source, just use `go build -trimpath ./cmd/caddy` instead.

**Comment by bayandin** [comment]
> If you must build the caddy binary from source, just use `go build -trimpath ./cmd/caddy` instead.

This sounds right to me.
@hairyhenderson would you like to create a PR?

**Comment by mholt** [comment]
@hairyhenderson 

> If you must build the caddy binary from source, just use go build -trimpath ./cmd/caddy instead.

That won't embed any version information, unfortunately, due to [a long-standing bug in Go](https://github.com/golang/go/issues/29228).

If you're going to use the `go` tool directly, it's easy enough anyway since you're not building with plugins, to just follow these steps: https://github.com/caddyserver/caddy#with-version-information-andor-plugins (create a main.go file and then build that instead of Caddy's main.go directly).

If you're going to use xcaddy, just run `xcaddy build <version>` -- no need for `--with` which destroys the version information, negating the benefit.

**Comment by hairyhenderson** [comment]
> @hairyhenderson would you like to create a PR?

Sure.

> [...] just follow these steps [...]

Oh right, thanks @mholt.

**Comment by lukasbestle** [comment]
Using `go build` will probably violate `brew`s linting rules and therefore won't pass automated testing. This was the reason I suggested to build a custom tool (which became `xcaddy`) in the first place.

**Comment by mholt** [comment]
> Using go build will probably violate brew's linting rules and therefore won't pass automated testing. 

I've got bad news for you then about what `xcaddy` does...

**Comment by lukasbestle** [comment]
@mholt I know! But `xcaddy` was in use in the `brew` formula since 2.0.0 and it worked just fine. It really doesn't matter that `xcaddy` does the same stuff internally as long as `brew` doesn't know about that when linting the formula code.

**Comment by francislavoie** [comment]
> While we are at it, switch back to go@1.14 for now (see #61620 (comment)).

That's not necessary, Go 1.15 can be used for v2.2+. I just think you should at least pin to a version.

**Comment by mholt** [comment]
Ah, right, I think I remember something about that.

Using xcaddy is fine then, just without the `--with`.

And ... please don't downgrade Go. :)

**Comment by lukasbestle** [comment]
Well, you as the devs decide what to do with the Go version. I'm not sure if `brew` allows pinning Go to 1.15 as that is the current version. But if it does – sure!

I thought @francislavoie meant we needed to downgrade, but then this was a misunderstanding of @francislavoie's comment on my end.
