### ISSUE TITLE
Suricata wont install: "Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by marcus-cr** [Homebrew/homebrew-core#6162]
While attempting to install Suricata I received the following error message. Tried `brew update ; brew update ; brew doctor` before attempting to install again, same error.

> Undefined symbols for architecture x86_64:
  "_pcre_free_study", referenced from:
      _DetectIPProtoRegister in detect-ipproto.o
      _DetectUrilenRegister in detect-urilen.o
      _ParseSizeDeinit in util-misc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [suricata] Error 1
make[1]: *** [install] Error 2
make: *** [install-recursive] Error 1

Here's the [gist-log](https://gist.github.com/cc4cd9bbdb5da447f92ad2c217d92211), just in case.

**Comment by MikeMcQuaid** [comment]
Please try to `brew reinstall pcre; brew reinstall suricata` . Thanks!

**Comment by marcus-cr** [comment]
Awesome, done deal! Much appreciated.
