### ISSUE TITLE
Neo4j 4.1.x requires java 11, but the formula requires java 8

### ISSUE THREAD

**Issue by viraptor** [Homebrew/homebrew-core#61713]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- N/A ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- N/A if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install neo4j

## What happened (include command output)

Neo4j 4.1.2 installed, with output:

```
==> Upgrading neo4j 4.1.1 -> 4.1.2
neo4j: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: neo4j: An unsatisfied requirement failed this build.
```

However neo4j 4.x requires java 11 see https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-software 

`/usr/local/Cellar/neo4j/4.1.1/libexec/bin/neo4j` explicitly mentions:
```
* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
```

## What you expected to happen

Install should require java 11.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install neo4j
```

**Comment by SMillerDev** [comment]
Here's some documentation on how to resolve this for yourself: https://docs.brew.sh/Updating-Software-in-Homebrew

You'd need to change `depends_on :java` to `depends_on "openjdk@11"`
