### ISSUE TITLE
Libgda incomplete

### ISSUE THREAD

**Issue by M-Rick** [Homebrew/homebrew-core#6173]
The Libgda formula is fairly incomplete. It's missing all the UI tools to manage graphically the databases.
It's missing gda-browser-5.0 and gda-control-center-5.0 binaries, and libgda-ui-5.0.4.dylib, libgdadata-5.0.0.dylib libraries.

Software like Gnumeric are unable to access libgda and the extension is not built.

**Comment by MikeMcQuaid** [comment]
We'll accept an pull request to build these optionally (as long as they don't need X11).
