### ISSUE TITLE
Update pypy download links

### ISSUE THREAD

**Issue by lovasoa** [Homebrew/homebrew-core#61748]
This is a follow-up on #51006. The download links in the pypy formulae are now dead. The new download links are on python.org :

 - https://www.pypy.org/download.html
 - https://downloads.python.org/pypy/pypy3.6-v7.3.2-src.tar.bz2

> It will by the end of May. We don’t know yet where to.

_Originally posted by @mattip in https://github.com/Homebrew/homebrew-core/pull/51006#issuecomment-596078637_

**Comment by mattip** [comment]
The URL https://downloads.python.org/pypy/ will be the canonical URL for the foreseeable future.

**Comment by lovasoa** [comment]
It looks like the links have already been updated, sorry !
