### ISSUE TITLE
Erlang: `fop` dependency was added for supporting chunked docs but doesn't appear to be required.

### ISSUE THREAD

**Issue by idyll** [Homebrew/homebrew-core#61770]
# Bug report

In a previous release of Erlang it appears `fop` was added as a dependency so that Erlang is able to support chunked docs.

See:  http://blog.erlang.org/OTP-23-Highlights/ -- specifically:
> The ordinary doc build is extended with the generation of .chunk files for all OTP modules. You can run make docs DOC_TARGETS=chunks to build only the EEP 48 chunks. Running just make docs without setting the DOC_TARGETS variable will build all formats (html, man, pdf, chunks).

I would like to open a PR to remove `fop` as a dependency, but wanted to discuss via an issue first just in case my assumptions are wrong.

Assuming no one has an issue with this I will open a PR and link it to the ticket.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Remove the `fop` dependency from Erlang. This should speed up the builds as it removes openjdk as an upstream dependency of Erlang.

## What happened (include command output)

I have tested this out locally and as far as I can tell removing the dependency on `fop` works find with otp 23.1

## Step-by-step reproduction instructions (by running `brew install` commands)

- brew edit erlang
- (remove fop dependency)
- brew install erlang
- run `erl` and then ` h(lists,sort,2).` 

you should then see the chunked doc for lists, sort,2.

**Comment by idyll** [comment]
@gromgit can you comment on this? I don't think we actually need `fop` and I would like to remove it if we can.

**Comment by SMillerDev** [comment]
Please make a pull request for this and add something to the test block that would fail if it didn't work.

**Comment by idyll** [comment]
> Please make a pull request for this and add something to the test block that would fail if it didn't work.

Thoughts on a test would be helpful... I have manually tested and the two things that should happen did:

1. chunk files are present (for example in lib/kernel/doc/chunks).
2. the PDF files are empty and say they are generated with fakefop

The problem with a test that looks for the chunked files is that they live in a directory that includes the version number - for example `kernel-7.1` which will change...

**Comment by SMillerDev** [comment]
We have `#{version.major_minor}` for that.

**Comment by gromgit** [comment]
> @gromgit can you comment on this? I don't think we actually need `fop` and I would like to remove it if we can.

I added `fop` to the v23.0 formula because one of the following was true (I can't remember which):
1. the Homebrew build on my local machine failed without it
1. the build succeeded, but didn't build the chunks

If the current version can build chunks without `fop`, go for it.

**Comment by chenrui333** [comment]
I can see this error in the erlang@21 and erlang@22 builds

```
*********************************************************************
**********************  DOCUMENTATION INFORMATION  ******************
*********************************************************************

documentation  : 
                 fop is missing.
                 Using fakefop to generate placeholder PDF files.

*********************************************************************
```

I also just linked the previous PR and issue discussions.

**Comment by maxnordlund** [comment]
As far as I know, you don't need fop to build any of the other doc types. The only hard requirements is `xsltproc`, because the core OTP docs are written in XML (but some of the newer parts uses edoc).

For testing maybe you can use `code:get_doc/1`, but it syntheses documentation from `debug_info` and I believe homebrews Erlang is built with `debug_info`. So you need to filter out the type spec somehow.

**Comment by idyll** [comment]
> For testing maybe you can use code:get_doc/1, but it syntheses documentation from debug_info and I believe homebrews Erlang is built with debug_info. So you need to filter out the type spec somehow.

Yeah I was exploring that but as you've noted it can work even without the chunks.

Looking at the original ticket, https://github.com/Homebrew/homebrew-core/issues/55217, I think it should be sufficient to prove that `h(lists)` works in a test?

The other option would be to write a test that looks for the chunk files. But that's tricky because they are in directories that include a version number (which isn't the version number for OTP).

`fop` should not be a requirement. `system "make", "docs", "DOC_TARGETS=chunks"` is sufficient.

**Comment by maxnordlund** [comment]
`h/1` is a shell only function (lives in `shell_default`) that uses `code:get_doc/1` under the hood with the same caveats. But there's hope, I just noticed something:

```erl
2> code:get_doc(erl_lint).
{ok,{docs_v1,[{file,"erl_lint.erl"},{location,0}],
             erlang,<<"application/erlang+html">>,
             #{<<"en">> =>
    % ... more stuff 
3> code:get_doc(erl_error).
{ok,{docs_v1,0,erlang,<<"application/erlang+html">>,none,
             #{generated => true,otp_doc_vsn => {1,0,0}},
    % ... more stuff 
```

<details>
<summary>
Digging through the OTP source I found the definition of the record:</summary>

```erlang
-define(NATIVE_FORMAT,<<"application/erlang+html">>).
-define(CURR_DOC_VERSION, {1,0,0}).
-record(docs_v1, {anno,
                  beam_language = erlang,
                  format = ?NATIVE_FORMAT,
                  module_doc,
                  metadata = #{ otp_doc_vsn => ?CURR_DOC_VERSION },
                  docs}).


-record(docs_v1_entry, {kind_name_arity,
                        anno,
                        signature,
                        doc,
                        metadata}).
```

 https://github.com/erlang/otp/blob/master/lib/kernel/include/eep48.hrl
</details>

I noticed two things. First off the `generated => true` for the second example. Then I also noticed that it also was missing the module docs, and instead had `none` in it's place. This has to mean even if it generate docs from `debug_info`, the module docs will be missing.

Putting it together, this will be true if chunks are present, and false if not, even in the case of generated spec docs: `{ok, {docs_v1, _, _, _, ModuleDoc, _, _}} = code:get_doc(lists), ModuleDoc =/= none`

**Comment by iMichka** [comment]
Let's discuss the final details in the PR #61771
