### ISSUE TITLE
Installing homebrew on mac gives error

### ISSUE THREAD

**Issue by sudipta17** [Homebrew/homebrew-core#61800]
![Screenshot 2020-10-01 at 10 16 37 AM](https://user-images.githubusercontent.com/33668301/94769253-3ce9c900-03cf-11eb-9836-0a45918a3471.png)
# Bug report
Tried to run the command   
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" to install homebrew but it always keeps showing this error.

**Comment by Dids** [comment]
Check the pinned issue (https://github.com/Homebrew/homebrew-core/issues/61772).

**Comment by SMillerDev** [comment]
As mentioned, duplicate issue.

**Comment by sudipta17** [comment]
Yes, the issue still persists. No solution is mentioned over there.

**Comment by SMillerDev** [comment]
The solution is trying until it works really.
