### ISSUE TITLE
terragrunt formula will not honor terraform being installed by the hashicorp tap.

### ISSUE THREAD

**Issue by grimm26** [Homebrew/homebrew-core#61831]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] ran `brew update` and can still reproduce the problem?
- [x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

install terragrunt with hashicorp's tap of terraform

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

 ❯ brew install terragrunt
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/terraform-0.13.3.catalina.bottle.tar.gz
Already downloaded: /Users/mkeisler/Library/Caches/Homebrew/downloads/181696da4bf09bfcc0f0be9eec1d8081adef2949f011ece68eb506c0a99b9617--terraform-0.13.3.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/terragrunt-0.25.2.catalina.bottle.tar.gz
Already downloaded: /Users/mkeisler/Library/Caches/Homebrew/downloads/3826690631b8c4992f886c8f7b6de1c3ca89c89969a953fc01638373e9a771a4--terragrunt-0.25.2.catalina.bottle.tar.gz
==> Installing dependencies for terragrunt: terraform
Error: terraform is already installed from hashicorp/tap!
Please `brew uninstall terraform` first."

  </pre>
</details>

## What you expected to happen

install terragrunt

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install hashicorp/tap/terraform
brew install terragrunt

**Comment by SMillerDev** [comment]
This is expected behaviour. `hashicorp/tap/terraform` is not the same thing as `terraform` (which is `homebrew/core/terraform`)

**Comment by grimm26** [comment]
@SMillerDev is it possible to have the terragrunt formula honor either one as a dependency?

**Comment by SMillerDev** [comment]
Technically, yes. Practically Homebrew won't be pointing to 3rd party taps for dependencies since we don't control the quality or the policy of those.

**Comment by SMillerDev** [comment]
You could consider hosting a copy of terragrunt in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap. That way you can make it depend on whatever you want.
