### ISSUE TITLE
libxml2 include files are **not** present in /usr/include as indicated by Library/Homebrew/os/mac/pkgconfig/10.12/libxml-2.0.pc on 10.12

### ISSUE THREAD

**Issue by LudovicRousseau** [Homebrew/homebrew-core#6186]
Gist with my configuration: https://gist.github.com/LudovicRousseau/c2c4c8af70b62ea49407df303acabe02

Homebrew provides ``Library/Homebrew/os/mac/pkgconfig/10.12/libxml-2.0.pc`` but the content is wrong/bogus.

The Formula libxml2 is **NOT** installed. I get:
```
$ pkg-config --cflags libxml-2.0
-I/usr/include/libxml2
```

But I also have:
```
$ ls /usr/include/libxml2
ls: /usr/include/libxml2: No such file or directory
```

My problem is that the check for libxml2 works with autoconf but the compilation of my program fails with:
```
foobar: fatal error: 'libxml/parser.h' file not found
```

The header files for libxml2 provided by Apple are in:
```
$ ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2/
libxml
```

A simple patch would be:
```
--- /var/folders/jb/2mvc64nx74b76qjg_5yk8zs00000gn/T//Wbl74b_libxml-2.0.pc  2016-10-23 10:32:00.000000000 +0200
+++ Library/Homebrew/os/mac/pkgconfig/10.12/libxml-2.0.pc   2016-10-23 10:31:55.000000000 +0200
@@ -1,4 +1,4 @@
-prefix=/usr
+prefix=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr
 exec_prefix=${prefix}
 libdir=${exec_prefix}/lib
 includedir=${prefix}/include
```
and the compilation+link now works.

I guess there is a better (more Homebrew) way to indicate the ``.h`` files are provided by Xcode in ``MacOSX.sdk`` and not in ``/usr/include/``.

The other ``.pc`` files in ``Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12`` have the same problem. ``/usr/include/`` does not exist in Sierra 10.12 (at least on my version).

**Comment by ilovezfs** [comment]
I think you need the CLT installed for them to be there.
```
xcode-select --install
```

**Comment by ilovezfs** [comment]
Probably the simplest solution here would be to unconditionally require the CLT. However, that is usually discarded as an idea whenever it comes up, so an alternative would be to provide two sets of pkg-config files, one for when Xcode is installed and one for when it's not, or one for when the CLT is installed and one for when it's not, and then set PKG_CONFIG_PATH accordingly.

Other possibilities would be hacking the pkg-config formula (yuck), or using a superenv shim to pass --define-variable=prefix=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr whenever the CLT is not installed (but then that would requiring hacking all formulae whose configure uses an absolute pkg-config path and probably be more hassle than it was worth).

However, the status quo is probably perfectly fine since the CLT provided those files on 10.11 as well, and it has not been much of a problem to date, so I think this falls into the "won't fix" bucket at this point.

**Comment by MikeMcQuaid** [comment]
> one for when Xcode is installed and one for when it's not, or one for when the CLT is installed and one for when it's not, and then set PKG_CONFIG_PATH accordingly.

This would be my preferred solution.

**Comment by ilovezfs** [comment]
Not convinced any "solution" is needed since this basically falls into the speculatively fixing bugs category right now.

**Comment by MikeMcQuaid** [comment]
> Not convinced any "solution" is needed since this basically falls into the speculatively fixing bugs category right now.

Agreed. If you have a specific issue with a formula, please let us know. Thanks!

**Comment by LudovicRousseau** [comment]
Thanks for the fast feedback.

``xcode-select --install`` fixed the problem.

Maybe ``brew doctor`` could *suggest* this command if CLT is not installed?
Or maybe brew could enable the ``Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12`` pkg-config files only if CLT is installed?

**Comment by MikeMcQuaid** [comment]
@LudovicRousseau If you can point to a specific formula with this issue we can look at a fix.

**Comment by LudovicRousseau** [comment]
The problem is not with a specific formula but with homebrew itself.

1. install homebrew
2. Xcode CLT are **NOT** installed
3. libxml2 formula from homebrew is **NOT** installed
4. try to build a (external) software that uses libxml2
5. libxml2 is detected and found using pkg-config and the ``Library/Homebrew/os/mac/pkgconfig/10.12/libxml-2.0.pc`` file provided by homebrew
6. ``libxml-2.0.pc`` (from homebrew) indicates that the libxml2 header files are in ``/usr/include/libxml2`` but that is not the case and the compilation fails
6. ``libxml-2.0.pc`` (from homebrew) indicates that the libxml2 header files are in ``/usr/include/libxml2`` but that is not true and the compilation fails

I understand this problem is not easy to fix and I agree if the bug is closed with no solution.
I know what was wrong and have a working configuration now.

**Comment by MikeMcQuaid** [comment]
> The problem is not with a specific formula

Our point is: does it affect any specific formulae you can point to? That helps prioritise it accordingly.

**Comment by LudovicRousseau** [comment]
> Our point is: does it affect any specific formulae you can point to?

Not to my knowledge.
