### ISSUE TITLE
yarn and node dependency

### ISSUE THREAD

**Issue by cvlmtg** [Homebrew/homebrew-core#6187]
I have node.js installed on my system through a tool like NVM, node binary is in the $PATH etc, yet whenever I install or update yarn homebrew install its node formula because it's listed as a dependency.

Would it be possibile to avoid installing brew's node if a node binary is already in the path? thank!

**Comment by MikeMcQuaid** [comment]
This is possible but we'll need someone to add a pull request to do so to Homebrew/brew to add support for `depends_on :node`/`NodeRequirement`.
