### ISSUE TITLE
RubyBuild caveat adds 900ms to shell profile time

### ISSUE THREAD

**Issue by dduugg** [Homebrew/homebrew-core#61967]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was installing the `ruby-build` formula, which [suggests](https://github.com/Homebrew/homebrew-core/blob/ef09fca/Formula/ruby-build.rb#L26) adding a line to one's `shell_profile`.

## What happened (include command output)
Adding this line increased time-to-prompt by 900ms on my MBP (2.7 Ghz Quad-Core Intel Core i7), a 5x slowdown.

## What you expected to happen
This caveat should include a disclaimer about the latency issue (or, better yet, replace it with a faster alternative).

## Step-by-step reproduction instructions (by running `brew install` commands)
```sh
~ % time brew --prefix openssl@1.1
/usr/local/opt/openssl@1.1
brew --prefix openssl@1.1  0.55s user 0.33s system 96% cpu 0.908 total
```

**Comment by claui** [comment]
Very good point. I’ve found the following workaround to work best:

```
$(brew --prefix)/opt/openssl@1.1
```

It’s not easy to fix this in Homebrew itself. We’ll consider a PR for the caveat though.

Closing the issue as there’s no immediate maintainer to-do but feel free to continue the discussion here.
