### ISSUE TITLE
[python-markdown] Formula should be removed

### ISSUE THREAD

**Issue by rspeed** [Homebrew/homebrew-core#6202]
1. Python already has its own package management system (`pip`).
1. The module is easily installed via `pip install Markdown`.
1. No formulas are dependent on `python-markdown`.

There doesn't seem to be any reason for this formula to exist.

**Comment by MikeMcQuaid** [comment]
We duplicate a bunch of things that you can `pip install` because some people find Homebrew to be preferable for installing applications (this installs `markdown_py`) than `pip`. We're getting people installing this through our analytics so I'd rather not remove it.

**Comment by rspeed** [comment]
`markdown_py` is also installed via `pip`

**Comment by rspeed** [comment]
```
rspeed~  pip install Markdown
Collecting Markdown
  Using cached Markdown-2.6.7.zip
Building wheels for collected packages: Markdown
  Running setup.py bdist_wheel for Markdown ... done
  Stored in directory: /Users/rspeed/Library/Caches/pip/wheels/34/53/13/36d28723fa9a091576fbb516003d33085a114f35b823faf05e
Successfully built Markdown
Installing collected packages: Markdown
Successfully installed Markdown-2.6.7
rspeed~  markdown_py
# hello!
<h1>hello!</h1>
```

**Comment by MikeMcQuaid** [comment]
Some people would rather install it through Homebrew.

**Comment by rspeed** [comment]
I seem to recall that one of the principles of Homebrew is to not maintain packages for things that already have their own native package manager. The exception is for packages that have difficulty installing on OS X, which is why there's the `homebrew/python` tap.

**Comment by MikeMcQuaid** [comment]
This is the case for libraries but not applications.

**Comment by rspeed** [comment]
Not according to its [documentation](https://pythonhosted.org/Markdown/cli.html):

> While Python-Markdown is primarily a python library, a command line script is included as well.

The script is just a convenience feature.

**Comment by MikeMcQuaid** [comment]
I'm not sure why this being in Homebrew is causing you problems.

**Comment by rspeed** [comment]
I noticed a formula that goes against the guidelines of the project and reported it. Sorry I tried to help.

**Comment by bfontaine** [comment]
We often make exceptions to that guideline for applications (vs. libraries). If it were a new formula we _could_ have a debate on that but since it’s already in the tap it’s simpler to keep it there.

**Comment by rspeed** [comment]
As I pointed out by quoting its documentation, `python-markdown` is intended to be used as a library. Plus there's another formula to install John Gruber's markdown script.
