### ISSUE TITLE
frpc 0.34.1 bottle HTTP code 404

### ISSUE THREAD

**Issue by icpz** [Homebrew/homebrew-core#62022]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
n/a
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
n/a

## What you were trying to do (and why)

```bash
brew upgrade frpc
```

## What happened (include command output)

`curl` report 404 while accessing bottle URL.

<details>
  <summary>Command output</summary>
  <pre>

==> Upgrading frpc 0.34.0 -> 0.34.1
==> Downloading https://homebrew.bintray.com/bottles/frpc-0.34.1.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Error: Failed to download resource "frpc"
Download failed: https://homebrew.bintray.com/bottles/frpc-0.34.1.catalina.bottle.tar.gz

  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew update

brew upgrade frpc
```

**Comment by Rylan12** [comment]
Thanks for the report, @icpz!

This should be fixed in #62031

**Comment by Rylan12** [comment]
@icpz this should be fixed now.

**Comment by icpz** [comment]
Thanks!
