### ISSUE TITLE
Inko 0.8.0 released and changes the build process

### ISSUE THREAD

**Issue by YorickPeterse** [Homebrew/homebrew-core#62063]
The formula for [Inko](https://inko-lang.org) is [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/inko.rb), and currently is for version 0.7.0. Over night I released 0.8.0, which comes with a few changes to the build process. I'm not sure what the best process is for updating the formula, and how to update the bottled versions.

0.8.0 introduces the following changes:

1. The build and install process is now a two-step process. `make build` will just build the VM, and `make install` will move files into place. 
1. The `PREFIX` variable is used to set an installation prefix (e.g. `/usr/local/bin`), while `DESTDIR` is used by `make install` to move files into place. `DESTDIR` defaults to `PREFIX`. So if you want to load files at runtime from `/usr/local/` but temporarily install packages into `./foo` (e.g. a packaging chroot of some sort), you'd use: `make build PREFIX=/usr/local && make install PREFIX=/usr/local DESTDIR=./tmp`. `PREFIX` should be set for both if you want to overwrite the default.
1. Archives are now located at `https://releases.inko-lang.org/VERSION.tar.gz`, such as https://releases.inko-lang.org/0.8.0.tar.gz. The SHA256 checksums are at `https://releases.inko-lang.org/VERSION.tar.gz.sha256`, e.g. https://releases.inko-lang.org/0.8.0.tar.gz.sha256
    * I noticed the formula uses an archive provided by GitLab. I recommend using the archives on releases.inko-lang.org instead, as these don't contain unnecessary files such as runtime unit tests, documentation, etc.
1. The archives don't contain a directory such as `inko-0.8.0` or anything like that; instead they directly contain the source code.
1. libclang is no longer a dependency

With 0.8.0 it's also easier to build using a system installation of libffi. For Homebrew it means inko can depend on the libffi provided by homebrew, if desired. When done, the following dependencies are not necessary: automake, autoconf, libtool. To enable this, you must build Inko using `make build FEATURES='libinko/libffi-system'`.

A good reference is the Arch Linux PKGBUILD for version 0.8.0: https://gitlab.com/inko-lang/archlinux-inko/-/blob/master/PKGBUILD

If any more information is necessary please let me know :smiley:

**Comment by SMillerDev** [comment]
We don't really accept update requests (although I appreciate the detailed information). https://docs.brew.sh/Updating-Software-in-Homebrew can help you update the formula, the bottles will be done by CI.

**Comment by YorickPeterse** [comment]
@SMillerDev That sounds fair. When submitting a PR, so I need to remove the existing bottle section?

**Comment by SMillerDev** [comment]
No need, just do your updates and that's it.

**Comment by YorickPeterse** [comment]
I'll close this in favour of the draft PR https://github.com/Homebrew/homebrew-core/pull/62072.
