### ISSUE TITLE
Box2D

### ISSUE THREAD

**Issue by marmichalski** [Homebrew/homebrew-core#62099]
Hi,

First of all, excuse me if that's not the right place for an issue like this.

The box2d has been removed years ago because of a checksum mismatch (#4482), but not so recently, a new version has been released: https://github.com/erincatto/box2d/releases/tag/v2.4.0

Will this lib ever comeback to brew or it's gone forever?

Thanks 😊

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by marmichalski** [comment]
> https://docs.brew.sh/Adding-Software-to-Homebrew

Alright, done. Thought that removed formula might need some form of approval before being introduced back. :)
