### ISSUE TITLE
macOS Sierra: pyqt with qt5

### ISSUE THREAD

**Issue by chincheta0815** [Homebrew/homebrew-core#6216]
In my opinion it would make sense to compile pyqt4 (pyqt.rb) against qt5 on macOS Sierra. 

I know that qt4 is not supported anymore by upstream but maybe there is a possiblity to at least support pyqt4 driven tools as far as possible (like puddletag).

If a compilation of pyqt4 against qt5 which should be possible due to pyqt's homepage we could at least support a bit on macOS Sierra.

If this idea is okay: 
How would I call the formula or how would I implement that in the respective forums? The easiest way would be to put it into pyqt.rb with a caveat telling what happens under Sierra plus some routines into the formula.

Hope this idea is not too stupid...

**Comment by ilovezfs** [comment]
You may want to have a look at https://github.com/cartr/homebrew-qt4

**Comment by chincheta0815** [comment]
Thanks for that.

Am I "allowed" to put a "depends on" for that tap into the puddletag formula or is there another tap for such macOS Sierra unsupported things?

That's why I thought to pyqt with qt5... Is that generally a bad idea?

I just want to be uptodate and get some homebrew-philisophy as input...

**Comment by ilovezfs** [comment]
>Am I "allowed" to put a "depends on" for that tap into the puddletag formula or is there another tap for such macOS Sierra unsupported things?

You can do that manually but I'd suggest you poke @cartr and see if he's willing to accept some or all of the "boneyarded" Qt 4 dependent formulae into his tap.

**Comment by chincheta0815** [comment]
Okay poking @cartr would make sense.
To make that manually would be little bit, say stupid... It would be better in homebrew...

So I understand it won't make sense to do an official pyqt.rb with qt5just for macOS Sierra?

**Comment by ilovezfs** [comment]
There's already a pyqt5. You can recommend https://github.com/spyder-ide/qtpy to upstreams as a way to smooth their transition to Qt 5. It's being used successfully by git-cola already (https://github.com/git-cola/git-cola).

**Comment by cartr** [comment]
Making a version of `pyqt` that uses Qt5 doesn't make a whole lot of sense. PyQt is a pretty thin wrapper around Qt's API, so a "Qt5 version of PyQt4" would pretty much just be PyQt5. You'd probably still have to update your software to use it, and at that point you might as well just upgrade to PyQt5.

I've added the boneyarded Qt4 formulae (including `puddletag`) to my tap. I haven't tested everything, so please feel free to submit an issue or Pull Request if something doesn't work, or if there's another package you'd like me to add.

**Comment by ilovezfs** [comment]
>I've added the boneyarded Qt4 formulae (including puddletag) to my tap.

@cartr Thanks! By the way, here's the corresponding tracking thread https://github.com/Homebrew/homebrew-core/issues/1705, which you might find useful.
