### ISSUE TITLE
System still linked to gcc 5 wit gcc 6 installed

### ISSUE THREAD

**Issue by mckunkel** [Homebrew/homebrew-core#6225]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ X] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [NA ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
I just upgraded from OSX 10.10 Yosemite to 10.12 Sierra. Upgraded homebrew. Had to force remove gcc 5 and install gcc 6. 
However, when I build ROOT from source or Homebrew I see the following:

> ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/5.2.0/lib/gcc/5'

Since I have tried to build ROOT from their source, and I see the same error, I can only conclude that this has to be a gcc via homebrew issue.
Here is come brew info gcc
> michaelkunkel:QFactor_MK$ brew info gcc
gcc: stable 6.2.0 (bottled), HEAD
GNU compiler collection
https://gcc.gnu.org
/usr/local/Cellar/gcc/6.2.0 (1,435 files, 274.7M) *
  Poured from bottle on 2016-10-24 at 12:04:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb
==> Dependencies
Required: gmp ✔, libmpc ✔, mpfr ✔, isl ✔
==> Options
--with-all-languages
	Enable all compilers and languages, except Ada
--with-java
	Build the gcj compiler
--with-jit
	Build the jit compiler
--with-nls
	Build with native language support (localization)
--without-fortran
	Build without the gfortran compiler
--without-multilib
	Build without multilib support
--HEAD
	Install HEAD version
==> Caveats
GCC has been built with multilib support. Notably, OpenMP may not work:
  https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60670
If you need OpenMP support you may want to
  brew reinstall gcc --without-multilib

Here is some system info

> michaelkunkel:QFactor_MK$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12
BuildVersion:	16A323

Here is my homebrew configuation

> michaelkunkel:QFactor_MK$ brew config
HOMEBREW_VERSION: 1.0.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0296439c832a915be9b73456c0c26bc6c79c271d
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ccbfe2ae35a3dfb9eda2d83f939509ad0ec7b4f9
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_51
macOS: 10.12-x86_64
Xcode: 8.0
CLT: 8.0.0.0.1.1472435881
X11: 2.7.9 => /opt/X11

**Comment by ilovezfs** [comment]
`root` is a homebrew/science formula. Please re-open this there. You'll need to supply significantly more information including logs for anyone to be able to help you, though.

**Comment by mckunkel** [comment]
No, I stated perfectly clear that this is not a ROOT issue. Please read thoroughly what I posted.

**Comment by ilovezfs** [comment]
I did, and you'll have to take this up with science and provide a lot more logs as I said.

**Comment by mckunkel** [comment]
How can this be a ROOT issue, when the same warning is produced if I build ROOT from source....i.e https://root.cern.ch

Also there is no log file to give, because it only shows at complication of a script. It does not affect the build of ROOT.

**Comment by ilovezfs** [comment]
what is the output of
```
ls /usr/local/Cellar/gcc
```

**Comment by mckunkel** [comment]
michaelkunkel:~$ ls /usr/local/Cellar/gcc
6.2.0
michaelkunkel:~$
