### ISSUE TITLE
qt failed to build on 10.12

### ISSUE THREAD

**Issue by kleinjm** [Homebrew/homebrew-core#6232]
Having an issue installing `qt` on Sierra. The last line of output from the failure report is
```bash
make: *** [sub-plugins-make_default-ordered] Error 2
```

https://gist.github.com/f868b4e80d47db2c38d49c48e8a5f6e3

**Comment by ilovezfs** [comment]
Did you remove the maximum OS requirement?

**Comment by kleinjm** [comment]
Thanks for the fast reply. Yes I commented out
```ruby
# depends_on MaximumMacOSRequirement => :el_capitan
```
On line 36 of `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/qt.rb`

**Comment by ilovezfs** [comment]
You'll need to use https://github.com/cartr/homebrew-qt4 if you want qt4.

**Comment by kleinjm** [comment]
That worked! Thanks for the fast reply. 
For anyone else having this issue, make sure you `brew linkapps qt` after install.
