### ISSUE TITLE
php56-mongodb _clock_gettime error at runtime

### ISSUE THREAD

**Issue by ABXAdmin** [Homebrew/homebrew-core#6236]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

---

**The error:** 
```
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php56-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/opt/php56-mongodb/mongodb.so
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5
```

I followed the troubleshooting instructions, uninstalled and reinstalled php56 and php56-mongodb and am still getting this error. I know this is related to many other tickets, but the methods shown in the other tickets to fix the issue didn't help.

I've got xcode v8 installed with the v7.3x CLT.

I am unsure as to the brew doctor results. I get many warnings, but they appear to be due to having installed quite a bit outside of homebrew. Everything seems to work correctly except for the php56-mongodb driver. The legacy php56-mongo driver continues to work. I do have unbrewed dylibs but am unsure if one, or many of them may be causing an issue here:

```
Unexpected delis:

  /usr/local/lib/dccmtr.dylib
  /usr/local/lib/libCalibrationHandler.dylib
  /usr/local/lib/libCIEHandler.dylib
  /usr/local/lib/libCompression.dylib
  /usr/local/lib/libcurl.4.dylib
  /usr/local/lib/libDeviceManager.dylib
  /usr/local/lib/libErrorHandler.dylib
  /usr/local/lib/libICMManager.dylib
  /usr/local/lib/libMCCAppManager.dylib
  /usr/local/lib/libMCCEngineWrapper.dylib
  /usr/local/lib/libmcrypt.4.4.8.dylib
  /usr/local/lib/libMonitorDDCCISDK.dylib
  /usr/local/lib/libProtocolEngine.dylib
  /usr/local/lib/libQM2Lib.dylib
  /usr/local/lib/libssh2.1.dylib
  /usr/local/lib/Spyder.dylib
  /usr/local/lib/Spyder3.dylib
```

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-php#3737
