### ISSUE TITLE
Missing plugins for dnscrypt-proxy with ldns dependency met

### ISSUE THREAD

**Issue by marcus-cr** [Homebrew/homebrew-core#6244]
`$ brew install dnscrypt-proxy --with-plugins` only installs two of six available plugins. I tried reinstalling after brewing ldns but the last four plugins still won't install.

The last four are supposed to be installed if LDNS is installed, as seen in the original repo makefile 0d7eae9 for the makefile. **Edit**: correct link to source path for plugins [here](https://github.com/jedisct1/dnscrypt-proxy/tree/master/src/plugins):

> SUBDIRS = \
>     example \
>     example-logging
> 
> if USE_LDNS
> SUBDIRS += \
>     example-ldns-aaaa-blocking \
>     example-ldns-blocking \
>     example-ldns-opendns-deviceid \
>     example-ldns-opendns-set-client-ip
> endif

**Comment by dunn** [comment]
We'd love a PR to fix this! Take a look at https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.

**Comment by marcus-cr** [comment]
I'll see what I can do but I can't make promises. Will have to figure out how Homebrew works and installs formulae.

**Comment by marcus-cr** [comment]
Unfortunately I don't have the expertise or time to figure out how these plugins are created when brewing. 

Since not having the AAAA blocking plugin severely delays my communications, I'm going to have to abandon this formulae all together and opt for source install. 

Without this plugin Homebrewed dnscrypt-proxy is useless since connection times have double/tripled while awaiting AAAA queries.

**Comment by marcus-cr** [comment]
Still investigating

**Comment by marcus-cr** [comment]
@MikeMcQuaid and @dunn: The solution was _too_ simple after much overthinking.
