### ISSUE TITLE
Installation instructions result in a syntax error on the fish shell

### ISSUE THREAD

**Issue by kansaichris** [Homebrew/homebrew-core#62494]
# Bug report

## What I was trying to do (and why)

Install `ruby-build` on the fish shell along with `rbenv` to easily switch between different Ruby versions.

## What happened

Following [the installation instructions](https://github.com/Homebrew/homebrew-core/blob/457e51160cf5257c3592bc6f7e478f8751360cac/Formula/ruby-build.rb#L26), I added the following line to `~/.config/fish/config.fish`:

    export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"

This results in the following error when opening a new fish shell session:

```
~/.config/fish/config.fish (line 18): $(...) is not supported. In fish, please use '(brew)'.
export RUBY_CONFIGURE_OPTS="--with-openssl-dir="$(brew --prefix openssl@1.1)
                                                ^
from sourcing file ~/.config/fish/config.fish
	called during startup
```

## What I expected to happen

I expected to be able to open a new fish shell session without encountering any errors.

## Step-by-step reproduction instructions

1. `brew install ruby-build`
2. `echo 'export RUBY_CONFIGURE_OPTS="--with-openssl-dir="$(brew --prefix openssl@1.1)' >> ~/.config/fish/config.fish`
3. Open a new fish shell session.

## Possible fix

Replace [this line](https://github.com/Homebrew/homebrew-core/blob/457e51160cf5257c3592bc6f7e478f8751360cac/Formula/ruby-build.rb#L26) with:

```ruby
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=#{'$' unless shell_profile == '~/.config/fish/config.fish'}(brew --prefix openssl@1.1)"
```

I'd be happy to open a pull request if you'd find that to be helpful.

**Comment by SMillerDev** [comment]
Export also isn't really a fish way. That should be `set -gx` then. Generally all the instructions (not just for brew) are for posix compliant shells though, which fish intentionally isn't. If you fix ruby-build there will still be tons of messages that won't work in fish.

**Comment by kansaichris** [comment]
Oh, interesting. Be that as it may, [fish shell profiles are explicitly listed](https://github.com/Homebrew/brew/blob/0732a86a246b238e2a8d838f2335e8e707732393/Library/Homebrew/utils/shell.rb#L78) by Homebrew, so it probably wouldn't hurt to update the message here. Agreed that it may not be worth the effort to try and fix every single message that doesn't work in fish, but I think it would be nice to try and fix any syntax errors that are actually reported by users.

**Comment by max-sixty** [comment]
Somewhat relatedly — the installation instructions for brew itself aren't compatible with fish:

```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" 
```

I'm guessing there's a deliberate reason this can't be something like:

```
curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | /bin/bash
```

**Comment by kansaichris** [comment]
Just checking in: would anyone object to me opening a pull request to fix this particular issue for `ruby-build`?

**Comment by kansaichris** [comment]
Just checking in again: would anyone object to me opening a pull request to fix this particular issue for ruby-build?

**Comment by MikeMcQuaid** [comment]
Sorry, yes @kansaichris, I don't think it's worth changing `ruby-build` in this way, sorry.
