### ISSUE TITLE
libsndfile-1.0.30.tar.bz2 Error: SHA256 mismatch

### ISSUE THREAD

**Issue by aritjahja** [Homebrew/homebrew-core#62524]
# Bug report

## What you were trying to do (and why)
I'm using macOS 10.11.6 El Capitan and I was trying to install ffmpeg.
The error said that there is an SHA256 mismatch. Apparently the developers have uploaded the file again.

## What happened (include command output)
The upgrade/install process is terminated by an error.
<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://github.com/erikd/libsndfile/releases/download/v1.0.30/li
Already downloaded: ~/Library/Caches/Homebrew/downloads/71cd51640a04d9625f2f0f94915ff20da52fb52e61808a2027c9c0754a0d736b--libsndfile-1.0.30.tar.bz2
Error: SHA256 mismatch
Expected: ec898634766595438142c76cf3bdd46b77305d4a295dd16b29d024122d7a4b3f
Actual: 9df273302c4fa160567f412e10cc4f76666b66281e7ba48370fb544e87e4611a
  </pre>
</details>

## brew config
<details>
  <summary>output of brew config</summary>
  <pre>
HOMEBREW_VERSION: 2.5.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 588f5f1713cd095bbeddef1d7919132531941474
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1d65f095e9970615d7336647a93db9f9712f1959
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.xqPd7lqS7P/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit sandybridge
Clang: 8.0 build 800
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.43.0 => /usr/bin/curl
Java: 10.0.1, 1.6.0_65-b14-468
macOS: 10.11.6-x86_64
CLT: 8.2.0.0.1.1480973914
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>

## brew doctor
<details>
  <summary>output of brew doctor</summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.
  </pre>
</details>

## What you expected to happen
I'm expected the upgrade process would complete without errors.

## Step-by-step reproduction instructions (by running `brew install` commands)
brew install ffmpeg
OR
brew update ffmpeg
OR
brew install lbsndfile
OR
brew update lbsndfile

**Comment by cocode** [comment]
+1

I hit this today.

**Comment by SMillerDev** [comment]
Please make a pull request to change this. We don't accept change requests as issues.
