### ISSUE TITLE
Update Failure on MacOS due to lack of .bash_profile on 10.15.7 new install

### ISSUE THREAD

**Issue by joebasirico** [Homebrew/homebrew-core#62562]
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

This was a completely new install on a completely new OS. 
I executed:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"` 

Everything went well until brew tried to update. Then I reliably got the following error:
```
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding read data remaining
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128.
Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.
Failed during: /usr/local/bin/brew update --force
```
I tried to execute `brew update` and `brew update --force` and `brew doctor`
Updates failed in the same way, doctor returned no errors.

## Resolution
After some digging I found that some people were asking about my $PATH, when I executed `cat $PATH`  I got

```
cat: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin: No such file or directory
```

That led me to discover that MacOS didn't include a .bash_profile on the new install.

executing `touch .bash_profile` and re-running the installer fixed everything

## Recommendation
The installer should check for the existence of .bash_profile and warn or create the file.

**Comment by jonchang** [comment]
> Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128.
> Error: Failure while executing; `/usr/local/bin/brew tap homebrew/core` exited with 1.

This is a known issue that we are currently experiencing with Github. Likely just retrying it fixed the network problems.

> cat: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin: No such file or directory

This failed because you should have used `echo $PATH`.
