### ISSUE TITLE
brew cleanup fails at stash-cli

### ISSUE THREAD

**Issue by justinpitts** [Homebrew/homebrew-core#6259]
### Bug reports:

The brew cleanup command fails:

    Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/stash-cli:1: syntax error, unexpected ..
    ../Formula/atlassian-cli.rb
      ^
    /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/stash-cli:1: unknown regexp options - atlaa

The full output is here: https://gist.github.com/justinpitts/df79e213f6328eb86ccc13f49d0ec195

I am experiencing this problem on 2 systems.

Things I have tried:
1. brew update, more than twice
2. repeating brew cleanup

Also, I have run brew doctor. It complains of some unexpected dylibs and static libs, and that xcode is outdated. I wildly guess that none of these are a problem here.

**Comment by justinpitts** [comment]
@nijikon is there a way for me to test this?

**Comment by ilovezfs** [comment]
`brew update` and it should be fixed

**Comment by justinpitts** [comment]
Confirmed:
    [justin.pitts:~] 4s 1 % brew update
    Updated 1 tap (homebrew/core).
    ==> Updated Formulae
    buku
    [justin.pitts:~] 5s % brew cleanup
    Removing: /Users/justin.pitts/Library/Caches/Homebrew/stash-cli-5.3.0.zip... (6M)
    ==> This operation has freed approximately 6M of disk space.

Thanks!

**Comment by ilovezfs** [comment]
Thanks for reporting it
