### ISSUE TITLE
output when using `make`

### ISSUE THREAD

**Issue by pvinis** [Homebrew/homebrew-core#626]
I would like to see the output of `make` when installing something from `HEAD`. Is there a way to do that?
Currently I just get the `==> make` instruction, and then I just wait.. It would be nice if I could actually see what `make` it printing.

**Comment by ilovezfs** [comment]
`--debug --verbose`

**Comment by pvinis** [comment]
aha. would it make sense to make it into an env variable that, when set, it always installs with `--verbose`?

**Comment by ilovezfs** [comment]
It would make sense to make it into one if it were not already one :)
`export HOMEBREW_VERBOSE=1` in your profile. There's also `HOMEBREW_DEBUG` but that's not something you'd usually want to set persistently.

**Comment by pvinis** [comment]
oh snap. i skipped that.. thank you very much.
