### ISSUE TITLE
awscli Sierra bottle returns 404

### ISSUE THREAD

**Issue by kenips** [Homebrew/homebrew-core#6266]
https://homebrew.bintray.com/bottles/awscli-1.11.9.sierra.bottle.tar.gz is returning 404 for me. Any idea @nijikon?

**Comment by nijikon** [comment]
@kenips on it, keep you posted

**Comment by lembacon** [comment]
@nijikon The same for libuv and nghttp2.

**Comment by nijikon** [comment]
Will verify all recently pulled.

**Comment by cblecker** [comment]
Same with ssllabs-scan on el_capitan.
```
Error: Failed to download resource "ssllabs-scan"
Download failed: https://homebrew.bintray.com/bottles/ssllabs-scan-1.4.0.el_capitan.bottle.tar.gz
```

**Comment by ilovezfs** [comment]
awscli is fixed, so closing this. We can track any other broken links in a separate issue if necessary.

**Comment by nijikon** [comment]
All bottles have been fixed.
