### ISSUE TITLE
Getting error while installing node via terminal

### ISSUE THREAD

**Issue by Thirudhas** [Homebrew/homebrew-core#6269]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

Hi,

I have installed 10.12[Sierra] OS and I tried to uninstall and install node via terminal but I am getting the below error: 
"==> Pouring node-7.0.0.sierra.bottle.tar.gz
Error: The brew link step did not complete successfully". 

Again I tried to uninstall and install but it is throwing Warning as:
Warning: node-7.0.0 already installed, it's just not linked.. 
Kindly help me to resolve this error.

**Comment by zmwangx** [comment]
```
$ brew uninstall -f node
$ brew install node
```

**Comment by Thirudhas** [comment]
Thanks @zmwangx, 

Installation success after trying this command $ brew link --overwrite node

**Comment by crmpicco** [comment]
Thanks @Thirudhas - that also worked for me on Mac OSX El Capitan.

**Comment by w3code** [comment]
Thank, it worked for me, too. (Mac OS Sierra)
