### ISSUE TITLE
Operation not permitted - Pictures/Photos Library.photoslibrary

### ISSUE THREAD

**Issue by karnauskas** [Homebrew/homebrew-core#62847]
```
MacOSX 10.15.7
$ brew --version  
Homebrew 2.5.6-33-g8437f51
Homebrew/homebrew-core (git revision 77294; last commit 2020-10-13)
Homebrew/homebrew-cask (git revision acec0; last commit 2020-10-13)
```
Issue:
```
$ brew search test  
Error: Operation not permitted - Pictures/Photos Library.photoslibrary
```

Why `brew` is wondering to directories it's not permitted to when searching? Why `brew` requires access to `Pictures` folder?

**Comment by SMillerDev** [comment]
What does `pwd` return? Because I bet that's just the directory you're running brew in. Otherwise, fill out the issue template and we can reopen this.
