### ISSUE TITLE
CDN URL for MySQL changed

### ISSUE THREAD

**Issue by frdmn** [Homebrew/homebrew-core#6291]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Apparently the download URL for MySQL changed. At least the [current one](https://github.com/Homebrew/homebrew-core/blob/b363e6b/Formula/mysql.rb#L4) returns a 404:

```shell
$ curl -iL https://cdn.mysql.com/Downloads/MySQL-5.7/mysql-boost-5.7.16.tar.gz
HTTP/1.1 404 Not Found
Server: Apache
Content-Length: 16
Date: Wed, 26 Oct 2016 10:14:05 GMT
Connection: keep-alive
Content-Type: application/x-tar-gz

File not found."%
```

I did a bit of research and found this (working) URL instead:

```
$ wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-boost-5.7.16.tar.gz
mysql-boost-5.7.16.tar.gz         100%[====================>]  57.75M  79.4MB/s    in 0.7s

$ shasum -a 256 mysql-boost-5.7.16.tar.gz
43fc282f807353ff77ead21efb5f85f7f214c2a5362762a8cc370ae1c075095a  mysql-boost-5.7.16.tar.gz
```

**Comment by dunn** [comment]
Are you still seeing a 404? I can access the current URL.

**Comment by frdmn** [comment]
@dunn you are right, apparently just a temporary outage. Thanks for the reply 👍
