### ISSUE TITLE
yq formula is missing shell completions

### ISSUE THREAD

**Issue by isaacl** [Homebrew/homebrew-core#62927]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yq.rb

is missing completions.  The library provides them with the following:

- bash: `yq shell-completion -V bash` 
- zsh: `yq shell-completion -V zsh`
- fish: `yq shell-completion -V fish`

**Comment by SMillerDev** [comment]
We don't accept feature requests as issues. Please refer to https://docs.brew.sh/Updating-Software-in-Homebrew
