### ISSUE TITLE
Unable to initialize PostgreSQL 12 database

### ISSUE THREAD

**Issue by nertzy** [Homebrew/homebrew-core#62930]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to set up a PostgreSQL 12 database.

## What happened (include command output)

I try to generate a data directory using:
```
❯ /usr/local/opt/postgresql@12/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@12
```

(Side note: the output of `brew info postgresql@12` does not give the correct command for setting up a PostgreSQL 12 database.)

But I get:
```
performing post-bootstrap initialization ... 2020-10-15 09:04:05.276 CDT [36419] FATAL:  could not access file "$libdir/dict_snowball": No such file or directory
```

<details>
  <summary>Command output</summary>
  <pre>
❯ /usr/local/opt/postgresql@12/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@12
The files belonging to this database system will be owned by user "dev".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /usr/local/var/postgresql@12 ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... America/Chicago
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... 2020-10-15 09:04:05.276 CDT [36419] FATAL:  could not access file "$libdir/dict_snowball": No such file or directory
2020-10-15 09:04:05.276 CDT [36419] STATEMENT:  CREATE FUNCTION dsnowball_init(INTERNAL)
	    RETURNS INTERNAL AS '$libdir/dict_snowball', 'dsnowball_init'
	LANGUAGE C STRICT;

child process exited with exit code 1
initdb: removing data directory "/usr/local/var/postgresql@12"
  </pre>
</details>

## What you expected to happen

It should be possible to create a PostgreSQL database.

## Step-by-step reproduction instructions (by running `brew install` commands)

* `brew install postgresql@12`
* `/usr/local/opt/postgresql@12/bin/initdb --locale=C -E UTF-8 /usr/local/var/postgresql@12`

**Comment by jonchang** [comment]
Hmm, we're setting pkglibdir properly to `lib/postgres`, but pg_config still thinks its loadable modules belong in `lib`.

**Comment by jonchang** [comment]
Ah, it's a clever Makefile.

Looks like us setting `pkglibdir` wasn't really doing much, since the Makefile was just appending `postgres` to `libdir` anyway. For non-keg-only builds `libdir` is HOMEBREW_PREFIX/lib, which doesn't have the string "postgres" in it, so it gets properly appended. But for keg-only builds `libdir` is `/usr/local/opt/postgresql@12/lib`, so the Makefile thinks it doesn't need to append `postgres` to form `pkglibdir`.

https://github.com/postgres/postgres/blob/b05fe7b442fd185b9705c537adb602b3b9d49518/src/Makefile.global.in#L119-L124

Can you try to open a pull request for this (bumping the postgresql@12 revision as well) and also fix the test to catch this in the future? Thanks!

**Comment by ruurd** [comment]
> Ah, it's a clever Makefile.
> 
> Looks like us setting `pkglibdir` wasn't really doing much, since the Makefile was just appending `postgres` to `libdir` anyway. 

AFAIK it does the same for include and other directories. Right?

**Comment by juni0r** [comment]
I just ran into the same problem attempting a fresh install of `postgresql@12`. As I understand it, the formula is currently broken and there is no workaround?

**Comment by jzaleski** [comment]
> I just ran into the same problem attempting a fresh install of `postgresql@12`. As I understand it, the formula is currently broken and there is no workaround?

To unblock my development team I have taken @ashkulz's PR: https://github.com/Homebrew/homebrew-core/pull/62992 and pushed it to my personal "tap" w/ the aforementioned commit: https://github.com/jzaleski/homebrew-jzaleski/commit/6c88a0108d6174afcd8656d0f5efdb186aadfdbb

This is intended to be a temporary work-around, licensed as is, for **development only** and will be torn down once this issue is resolved.

I hope this helps.

**Comment by ruurd** [comment]
Why? There is a working postgresql@12 available currently. Then you can install from source against that.

**Comment by jzaleski** [comment]
> Why? There is a working postgresql@12 available currently. Then you can install from source against that.
> We're having fun with the recipe of postgis to run that against the latest postgresql recipe (postgresql v13.0) but are seemingly running into CI problems. :(

If you're referring to my comment specifying the `-s` (`--build-from-source`) flag for the currently published revision, this **did not** work. We were going for a _mostly_ drop-in solution w/ this tap[ped] version. Once this issue has been resolved it will be torn down as I have no desire to support it long-term.

Sorry you're having issues w/ `postgis`, when it works it's great (story of my life), but when it doesn't it's quite the pain.

**Comment by ruurd** [comment]
Ummm not really I'm just the footsoldier trying to get it to work really... Other than that let's first see if we can get this thing compiled and generated then take it from there.

**Comment by jonchang** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/62992.

**Comment by ruurd** [comment]
\o/ \o/

**Comment by jzaleski** [comment]
Removed the patched formula from my tap as promised now that this has made it into the mainline. Thanks for the quick turn around team.

**Comment by juni0r** [comment]
Thanks for fixing this so quickly. Have a good day everyone! 🚀
