### ISSUE TITLE
Emacs: cocoa support by default 

### ISSUE THREAD

**Issue by edrex** [Homebrew/homebrew-core#6298]
Most everyone is going to want to build emacs with cocoa support. Can we enable this by default so most folks can use the bottle build?

**Comment by MikeMcQuaid** [comment]
> Most everyone is going to want to build emacs with cocoa support.

Actually our analytics show twice the number of people install it without Cocoa support. We don't support it by default because Homebrew is not designed (and doesn't work as well) for building GUIs compared to e.g. Homebrew Cask.

**Comment by edrex** [comment]
Thanks for the quick response. I'd say that's not exactly apples to apples since a) some people will just be taking the defaults without looking at options and b) some people who are aware of cocoa won't want to wait for the build and so will go for the bottle.

I haven't been closely following the big reorganization of homebrew and the introduction of casks. I'll try the cask build. If that's the best way to install .apps going forward, folks like me will need to make sure the various first party projects' READMEs' OS X install instructions get updated.
