### ISSUE TITLE
Git not built with libpcre by default

### ISSUE THREAD

**Issue by charliesome** [Homebrew/homebrew-core#6308]
Homebrew's git formula does not build with libpcre by default, meaning using `git grep` with the `-P` flag fatals with the following error:

```
fatal: cannot use Perl-compatible regexes when not compiled with USE_LIBPCRE
```

I _do_ have libpcre installed:

```
λ brew install pcre
Warning: pcre-8.39 already installed
```

\- but it doesn't seem like whether optional dependencies are installed has any bearing on whether they're enabled or not.

It would be really nice if git were built with libpcre by default.

This could be done by upgrading libpcre to a required dependency (it's a pretty common dependency these days so it's probably reasonable to assume it's already installed and available) in a large number of cases.

Or, if it's not desirable to make libpcre a hard dependency, perhaps it might be possible to conditionally enable it by default if libpcre is already installed?

**Comment by chdiza** [comment]
Or just brew it using the `--with-pcre` option provided in the git formula.  That's what it's there for.

> perhaps it might be possible to conditionally enable it by default if libpcre is already installed?

HB is trying to make this sort of thing impossible.  But, you could try brewing with `--env=std` and see if that results in an already-there `pcre` getting picked up.  (OTOH, even if that works, you might as well just pass `--with-pcre`.)

**Comment by ilovezfs** [comment]
The bottled brew lacks several nice-to-have options in an effort to keep the dependencies minimal. `brew info git` to see the list of extra goodies available if you're willing to build it from source.
