### ISSUE TITLE
brew install python3 does not work - previous solutions not working

### ISSUE THREAD

**Issue by wm-shashank** [Homebrew/homebrew-core#63098]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to install python 3 using following command:
brew install python3

## What happened (include command output)
1. Firstly it hangs at Updating Homebrew... (running endlessly)
2. On interruption (Ctrl-C), it throws following output:
<details>
  <summary>No available formula or cask with the name python3</summary>
  <pre>
  Error: No available formula or cask with the name "python3".
==> Searching for similarly named formulae...
This similarly named formula was found:
python3
To install it, run:
  brew install python3
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

  </pre>
</details>

## What you expected to happen
install python 3.7 or above 

## Step-by-step reproduction instructions (by running `brew install` commands)
Machine: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
Specs: 2.9 GHz Dual-Core Intel Core i5/ 16 GB 2133 MHz LPDDR3
OS: MacOS Catalina 10.15.6 (19G2021)

- Had installed python3, x-code command line tools and anaconda from web before downloading homebrew
- once these problems on homebrew surfaced, following the advice of many on forums, I had removed direct installations of Python 3.7/3.8/3.9.
- Removed all PATH references, sanitized .zshrc and .bash_profile files and restarted machines
- Started with brew install python : got the following output
Warning: python 2.7.14 is already installed and up-to-date
To reinstall 2.7.14, run `brew reinstall python`

- Did a reinstall of python (went through fine) and after which checked the version
python --version
Python 2.7.16

- Searched for available python installations:
brew search python
==> Formulae
app-engine-python           gst-python                  micropython                 python3
boost-python                ipython                     python ✔                    wxpython
boost-python@1.59           ipython@5                   python-markdown             zpython
==> Casks
homebrew/cask/awips-python                              homebrew/cask/mysql-connector-python
homebrew/cask/kk7ds-python-runtime

- Ran brew update
brew update
Runs endlessly with no response on command line

- Ran brew upgrade
brew upgrade
Updating Homebrew... (Hangs here, running endlessly)

- Ran brew doctor
brew doctor
Your system is ready to brew.

- Ran brew cleanup
brew cleanup
(all clean)

- Ran brew config
brew config

HOMEBREW_VERSION: 2.5.6-74-g4e8d374
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e8d37494231718d501e04c482bdd764f6b2587a
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f5882150c3c5af3376a63daea5ca1d7883ce6aef
Core tap last commit: 3 years ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -w
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.1, 10.0.1, 9.0.4
macOS: 10.15.6-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: N/A

- Ran brew gist-logs python3
brew gist-logs python3
Error: python3: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python3.rb:14

- Ran brew install for python3 head block
brew install python3@head

Error: No available formula or cask with the name "python3@head".
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

- Ran brew install for python3 for the specific version
brew install python@3.8

Error: No available formula or cask with the name "python@3.8".
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

- Ran brew install for python3
brew install python3
Updating Homebrew... (Hangs here, running endlessly)
Interrupt with Ctrl+C

Error: No available formula or cask with the name "python3".
==> Searching for similarly named formulae...
This similarly named formula was found:
python3
To install it, run:
  brew install python3
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

Please help.

**Comment by bayandin** [comment]
> * Firstly it hangs at Updating Homebrew... (running endlessly)
> * On interruption (Ctrl-C), it throws following output:

You really need to wait until the finish of `brew update`. Currently, your homebrew-code installation quite outdated:

> Core tap HEAD: [f588215](https://github.com/Homebrew/homebrew-core/commit/f5882150c3c5af3376a63daea5ca1d7883ce6aef)
> Core tap last commit: 3 years ago

We didn't have `python3` that time.

**Comment by SMillerDev** [comment]
You might want to run `brew update-reset` to get it to a more current state and skipping all checks. Because it's surely gonna take a long time otherewise.

**Comment by wm-shashank** [comment]
Thanks @SMillerDev and @bayandin. brew update-reset got the job done quickly.
