### ISSUE TITLE
Boost-python3 doesn't work after upgrading to 1.74.0_1 

### ISSUE THREAD

**Issue by alvaropalmaaste** [Homebrew/homebrew-core#63359]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I updated boost-python3, from 1.74.0 to 1.74.0_1, as suggested by brew update -n

## What happened (include command output)

My application relying on boost-python3 stopped compiling, the error now is:

CMake Error at /usr/local/lib/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/boost_python-1.74.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python39-mt.dylib (3.9, Boost_PYTHON_VERSION=3.8)

  * libboost_python39-mt.a (3.9, Boost_PYTHON_VERSION=3.8)

  * libboost_python39.dylib (3.9, Boost_PYTHON_VERSION=3.8)

  * libboost_python39.a (3.9, Boost_PYTHON_VERSION=3.8)

I modified my CMake file to use boost-python39 instead, but that library doesn't exists (since brew hasn't updated python3 to 3.9 yet). So, to make it work, I manually copied back the 3.8 versions from a not-yet-updated machine.

<details>
  <summary>Command output</summary>
  <pre>

CMake Error at /usr/local/lib/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/boost_python-1.74.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python39-mt.dylib (3.9, Boost_PYTHON_VERSION=3.8)

  * libboost_python39-mt.a (3.9, Boost_PYTHON_VERSION=3.8)

  * libboost_python39.dylib (3.9, Boost_PYTHON_VERSION=3.8)

  * libboost_python39.a (3.9, Boost_PYTHON_VERSION=3.8)

  </pre>
</details>

## What you expected to happen

The application should have continued compiling normally.

## Step-by-step reproduction instructions (by running `brew` commands)

Simply `brew upgrade` and then recompile.

## Output of `brew config` and `brew doctor` commands

<pre>
HOMEBREW_VERSION: 2.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: abf214c01ff1edb57acf7e23d5eb24a777335e11
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 77c3face71d5e767f908925d1e5a17d858990b1c
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2
macOS: 10.15.7-x86_64
CLT: 12.1.0.0.1.1602137645
Xcode: 12.1
</pre>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  re2
</pre>

**Comment by fxcoudert** [comment]
The libraries are present, they're built, and they're found:

```
The following variants have been tried and rejected:
libboost_python39-mt.dylib (3.9, Boost_PYTHON_VERSION=3.8)
libboost_python39-mt.a (3.9, Boost_PYTHON_VERSION=3.8)
libboost_python39.dylib (3.9, Boost_PYTHON_VERSION=3.8)
libboost_python39.a (3.9, Boost_PYTHON_VERSION=3.8)
```

But they're rejected because `Boost_PYTHON_VERSION` is 3.8. What sets this variable? What is the relevant part of the `CMakeLists.txt`?

**Comment by alvaropalmaaste** [comment]
Actually, I was explicitly setting the Boost Python module to use the 3.8 version:

    set(PYTHON_PACKAGE "python38")
    set(BOOST_REQUIRED_PACKAGES "${BOOST_REQUIRED_PACKAGES}" "${PYTHON_PACKAGE}")

I changed that to `python39` and now it compiles, but the linker complains:
```
 /usr/local/Cellar/cmake/3.18.4/bin/cmake -E cmake_link_script CMakeFiles/opp_python.dir/link.txt --verbose=1
ccache /usr/local/opt/ccache/libexec/c++  -pedantic-errors -ferror-limit=1 -march=native -Wall -Werror -Wfatal-errors -Wextra -g -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names -o ../../../../../lib/Release/opp_python.dylib -install_name @rpath/opp_python.dylib CMakeFiles/opp_python.dir/opp_python.cpp.o  ../../../../../lib/Release/libopp_container_static.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_stacktrace_addr2line-mt.a /usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/libpython3.8.dylib -ldl /Applications/CPLEX_Studio128/cplex/lib/x86-64_osx/static_pic/libcplex.a /usr/local/lib/libgurobi81.dylib /usr/local/lib/libboost_python39-mt.a

Undefined symbols for architecture x86_64:
  "_PyCMethod_New", referenced from:
      boost::python::objects::class_base::def_no_init() in libboost_python39-mt.a(class.o)
  "__Py_NewReference", referenced from:
      boost::python::objects::function::function(boost::python::objects::py_function const&, boost::python::detail::keyword const*, unsigned int) in libboost_python39-mt.a(function.o)
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
```
I guess because the rest of MacOSX still relies on Python3.8 (no Python3.9 has been provided by brew yet AFAIK).

So, maybe boost-python shouldn't be updated until the whole Python infrastructure is also updated?

**Comment by fxcoudert** [comment]
We are shipping `python@3.9`, and `boost-python3` is using it:

```
$ brew info boost-python3
boost-python3: stable 1.74.0 (bottled), HEAD
C++ library for C++/Python3 interoperability
https://www.boost.org/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/boost-python3.rb
License: BSL-1.0
==> Dependencies
Build: numpy ✘
Required: boost ✘, python@3.9 ✘
```

**Comment by alvaropalmaaste** [comment]
Ahhhh, but I have to manually install it...I didn't know that. I usually just make `brew upgrade`, which didn't bring python@3.9 (but did bring boost-python@3.9):
```
[10:58 cmp@macmini1 -> ~] brew info python
python@3.8: stable 3.8.6 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.8/3.8.6 (4,341 files, 69.7MB) *
  Poured from bottle on 2020-10-09 at 11:28:19
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.8.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 540,360 (30 days), 1,473,790 (90 days), 3,777,287 (365 days)
install-on-request: 232,026 (30 days), 559,126 (90 days), 765,849 (365 days)
build-error: 0 (30 days)
[10:59 cmp@macmini1 -> ~] brew upgrade -n
[10:59 cmp@macmini1 -> ~]
```

**Comment by SMillerDev** [comment]
No, it's a separate package. So you now have `python` and `python@3.9` installed.

**Comment by alvaropalmaaste** [comment]
I just noticed I was forcing my Python CMake script to `3.8`:
```
if(APPLE)
    set(Python3_ROOT_DIR "/usr/local/opt/python@3.8/")
endif()
```
However, if I remove that setting, Boost-Python3 (using Python 3.9) still fails (since CMake still detects Python 3.8 as the default):
```
Undefined symbols for architecture x86_64:
  "_PyCMethod_New", referenced from:
      boost::python::objects::class_base::def_no_init() in libboost_python39-mt.a(class.o)
  "__Py_NewReference", referenced from:
      boost::python::objects::function::function(boost::python::objects::py_function const&, boost::python::detail::keyword const*, unsigned int) in libboost_python39-mt.a(function.o)
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
``` 
It works if I set it back, this time pointing to 3.9:
```
if(APPLE)
    set(Python3_ROOT_DIR "/usr/local/opt/python@3.9/")
endif()
```
So I guess that's going to be my workaround.

**Comment by fxcoudert** [comment]
Our main `python` formula was migrated to `python@3.9`, so closing as this should now be fixed.
