### ISSUE TITLE
`brew --prefix openssl` returns 1.0.2 if both 1.0.2 and 1.1.1 are installed

### ISSUE THREAD

**Issue by eregon** [Homebrew/homebrew-core#63370]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Software like [ruby-install](https://github.com/postmodern/ruby-install/blob/c339bf6ca481ec6fac7fd18ec537f46bed0d1ec5/share/ruby-install/ruby/functions.sh#L24) depends on `brew --prefix openssl` returning something sensible.

It seems that if openssl 1.0.2 was installed and openssl 1.1.1 installed later, `brew --prefix openssl` still returns the old one.
This is unexpected, OpenSSL 1.0 is EOL and should not be used anymore.

This notably happens on GitHub Actions:
https://github.com/eregon/setup-ruby-test/runs/1298933056?check_suite_focus=true
```
Run brew --prefix openssl
/usr/local/opt/openssl@1.0.2t

Run brew info openssl
openssl@1.1: stable 1.1.1h (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2t (1,787 files, 12.4MB)
  Built from source on 2020-10-17 at 21:36:12
/usr/local/Cellar/openssl@1.1/1.1.1h (8,067 files, 18.5MB)
  Poured from bottle on 2020-10-17 at 21:19:02

Run brew info openssl@1.1
openssl@1.1: stable 1.1.1h (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2t (1,787 files, 12.4MB)
  Built from source on 2020-10-17 at 21:36:12
/usr/local/Cellar/openssl@1.1/1.1.1h (8,067 files, 18.5MB)
  Poured from bottle on 2020-10-17 at 21:19:02
...
```

Related issues:
https://github.com/ruby/setup-ruby/issues/97#issuecomment-715430929
https://github.com/oracle/truffleruby/issues/1830

Debug info:
https://github.com/eregon/setup-ruby-test/runs/1298977387?check_suite_focus=true
```
Run brew config
HOMEBREW_VERSION: 2.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: abf214c01ff1edb57acf7e23d5eb24a777335e11
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5a91200d6813d2c14e6787b70707571e82485c8
Core tap last commit: 6 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_COLOR: set
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 11.0 build 1103
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 13.0.2, 12.0.2, 11.0.8, 1.8.0_265, 1.7.0_272
macOS: 10.15.7-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: 11.7 => /Applications/Xcode_11.7.app/Contents/Developer
```

**Comment by eregon** [comment]
On GitHub Actions, it's probably the fault of https://github.com/actions/virtual-environments/blob/0d46520ccf08c3780f879b324d81639975be3fcd/images/macos/provision/core/openssl.sh#L18-L22

I've seen multiple people having this issue though:
https://github.com/oracle/truffleruby/issues/1830

**Comment by SMillerDev** [comment]
We don't ship openssl 1.0.2 anymore. We can't really fix this hack that GitHub does either since they don't seem to be installing it through homebrew. I'd recommend opening an issue with them.

**Comment by eregon** [comment]
Thanks for the quick reply.
I mentioned it on https://github.com/actions/virtual-environments/issues/1745.

Was `openssl` pointing at 1.1 before 1.0.2 before <nothing> and before 1.1 now?
I think I've seen endless confusion with this.

**Comment by SMillerDev** [comment]
openssl used to be "whatever is latest" and with the 1.1 migration it became an alias for `openssl@1.1`. So if you have a copy of the actual `openssl.rb` it'll be installing 1.0.2.
