### ISSUE TITLE
Missing node@14 formulae

### ISSUE THREAD

**Issue by mgcrea** [Homebrew/homebrew-core#63419]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install node` currently brings node@15 and it does not look like we have an easy option to rollback to node@14.

## What happened (include command output)

```
▶ brew install node@14   
```

<details>
  <summary>Command output</summary>
  <pre>

Error: No available formula or cask with the name "node@14".

  </pre>
</details>

**Comment by Rylan12** [comment]
A PR that adds the `node@14` formula is in progress in #63410

If that's not accepted, you can [maintain your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

More info about versioned formulae [here](https://docs.brew.sh/Versions)
