### ISSUE TITLE
Why mono formula without xsp

### ISSUE THREAD

**Issue by fractalzombie** [Homebrew/homebrew-core#6350]
I do brew install mono, and have:

<img width="1440" alt="2016-10-28 15 09 53" src="https://cloud.githubusercontent.com/assets/5721336/19806020/a5624184-9d20-11e6-990c-ebf6b5c83eec.png">

Why mono formula installs without xsp?

OS: Mac OS Sierra

**Comment by Daniel15** [comment]
If you're building a new website, consider using ASP.NET Core 1.0 rather than ASP.NET 4.0 or 4.5. You don't need XSP for ASP.NET Core 😄

**Comment by MikeMcQuaid** [comment]
I don't know why it does/does not have it. If you wish to submit a pull request to add it we'll review it.
