### ISSUE TITLE
`brew install jbangdev/tap/jbang` keeps saying its keg-only; worked in earlier versions of brew

### ISSUE THREAD

**Issue by maxandersen** [Homebrew/homebrew-core#63512]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

do `brew install jbangdev/tap/jbang` and have it just work.
no explicit linking working.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  brew install jbangdev/tap/jbang
==> Installing jbang from jbangdev/tap
==> Downloading https://github.com/jbangdev/jbang/releases/download/v0.52.0/jbang-0.52.0.zip
Already downloaded: /Users/max/Library/Caches/Homebrew/downloads/c6c32a4cdc57dd1ff26332f293cae7da04f2fdac15a997f93cc8e34a6a7bc5ca--jbang-0.52.0.zip
==> Caveats
jbang is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have jbang first in your PATH run:
  echo 'export PATH="/usr/local/opt/jbang/bin:$PATH"' >> ~/.zshrc

==> Summary
🍺  /usr/local/Cellar/jbang/0.52.0: 58 files, 5.8MB, built in 4 seconds

  </pre>
</details>

## What you expected to happen

that it would not be keg-only and just install. this worked in past (I'm author of jbang and made the formula).

The error says jbang is an alternate version of another formula ..but that is not true and there seem to be zero other brew formulas named jbang.

any ideas/hints on what could be causing this ?

**Comment by dtrodrigues** [comment]
Since January 29, the formula has included
`keg_only :versioned_formula`
https://github.com/jbangdev/homebrew-tap/commit/9cb6968fd4377e699f631b288d97ef84b31bab10#diff-7ab6f881efc2df9b30b287f418284fee313d4a757d81fe8c443705555640ea55

> jbang is keg-only, which means it was not symlinked into /usr/local,

comes from `key_only`

and
> because this is an alternate version of another formula.

comes from `:versioned_formula`

**Comment by SMillerDev** [comment]
This is not a homebrew-core formula. Please report any issues to the tap.
