### ISSUE TITLE
brew install ffmpeg --with-libvpx is failing

### ISSUE THREAD

**Issue by Ajaay** [Homebrew/homebrew-core#6352]
# Please follow the general troubleshooting steps first:
- [done ] Ran `brew update` and retried your prior step?
- [done] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [n/a ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

Brew install ffmpeg is working fine, but if I try to install with options it just sits at make install with CPU pegged at 100. There seems to be a terminal loop between ruby, sh and clang.

https://gist.github.com/2515e03a1fa774955033fb132bdc22d0

**Comment by zmwangx** [comment]
Be patient? Looking at the logs, you interrupted while libavformat is still being compiled. Add the --verbose flag so that you can see the compilation progress in real time. FFmpeg builds aren't exactly fast, but they're nothing compared to certain formulae which could easily take hours.

(Suggest close.)

**Comment by Ajaay** [comment]
Ok I'll give it another go with verbose. Just felt like something was up because the standard build completes within a minute or two, whereas I left this for 20 minutes with CPU pegged at 100%.

On 29 Oct 2016, at 13:24, Zhiming Wang <notifications@github.com<mailto:notifications@github.com>> wrote:


Be patient? Looking at the logs, you interrupted while libavformat is still being compiled. Add the --verbose flag so that you can see the compilation progress in real time. FFmpeg builds aren't exactly fast, but they're nothing compared to certain formulae which could easily take hours.

(Suggest close.)

**Comment by zmwangx** [comment]
"The standard build" is downloading a pre-compiled binary package followed by unpacking it.

**Comment by dunn** [comment]
Have you had a chance to try compiling it again?

**Comment by Ajaay** [comment]
Yes tried again and followed progress with verbose. Just took a while to complete.

Thanks
