### ISSUE TITLE
fzf is reporting --version of (brew)

### ISSUE THREAD

**Issue by runbmp** [Homebrew/homebrew-core#63545]
Hello,

`brew install fzf`
```
❯ fzf --version
 (brew)
```

This is causing fzf.vim to not work because it can't verify that fzf is in fact version `0.24.0`
https://github.com/junegunn/fzf.vim/issues/1150

I am not fluent in Ruby, but this looks suspicious
https://github.com/Homebrew/homebrew-core/blob/6aff73d492351f644ac6f79b750c3b5b890776d3/Formula/fzf.rb#L22

update: will be closed by https://github.com/Homebrew/homebrew-core/pull/63548

**Comment by fxcoudert** [comment]
Thanks for the report and PR!
