### ISSUE TITLE
Permissions error on new Kibana install.

### ISSUE THREAD

**Issue by Toontje** [Homebrew/homebrew-core#63594]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/53ce09c1c08b2ffcceea5ac58bb3080c
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Start kibana expecting no errors.

## What happened (include command output)

Kibana starts. Interface is available and usable but during startup i get the following error:
<details>
  <summary>Command output</summary>
  <pre>
  log   [09:42:02.260] [info][listening] Server running at http://localhost:5601
  log   [09:42:03.761] [info][server][Kibana][http] http server running at http://localhost:5601
  log   [09:42:04.849] [info][plugins][reporting] Extracting [/usr/local/Cellar/kibana-full/7.9.2/libexec/.chromium/chromium-312d84c-darwin.zip] to [/usr/local/Cellar/kibana-full/7.9.2/libexec/x-pack/plugins/reporting/chromium/headless_shell-darwin/headless_shell]
 error  [09:42:04.861] [warning][process] UnhandledPromiseRejectionWarning: Error: Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.
    at safeCheck (/usr/local/Cellar/kibana-full/7.9.2/libexec/node_modules/del/index.js:37:9)
    at mapper (/usr/local/Cellar/kibana-full/7.9.2/libexec/node_modules/del/index.js:73:4)
    at /usr/local/Cellar/kibana-full/7.9.2/libexec/node_modules/p-map/index.js:57:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at emitWarning (internal/process/promises.js:97:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)
 error  [09:42:04.862] [warning][process] Error: Cannot delete files/directories outside the current working directory. Can be overridden with the `force` option.
    at safeCheck (/usr/local/Cellar/kibana-full/7.9.2/libexec/node_modules/del/index.js:37:9)
    at mapper (/usr/local/Cellar/kibana-full/7.9.2/libexec/node_modules/del/index.js:73:4)
    at /usr/local/Cellar/kibana-full/7.9.2/libexec/node_modules/p-map/index.js:57:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
  </pre>
</details>

## What you expected to happen

Kibana to start without issues.

## Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install kibana-full
(Kibana installs)
$ kibana
(Kibana starts and throws the messages shown before.

Gist: https://gist.github.com/53ce09c1c08b2ffcceea5ac58bb3080c

<details>
  <summary>Commands</summary>
  <pre>
[tmachielsen@Laptop:~] which kibana
/usr/local/bin/kibana
[tmachielsen@Laptop:~] cat /usr/local/bin/kib
kibana           kibana-keystore  kibana-plugin
[tmachielsen@Laptop:~] cat /usr/local/bin/kibana
#!/bin/bash
KIBANA_PATH_CONF="/usr/local/etc/kibana" DATA_PATH="/usr/local/var/lib/kibana/data" exec "/usr/local/Cellar/kibana-full/7.9.2/libexec/bin/kibana"  "$@"
  </pre>
</details>

**Comment by SMillerDev** [comment]
What makes you suspect this is a brew issue?

**Comment by Toontje** [comment]
Since this is a clean install using Homebrew, maybe the formula is incorrect? If this is the wrong place to open issues for brew formulae, please point me to the correct place to file those.

**Comment by SMillerDev** [comment]
It's the correct place, but this seems like a kibana issue more than a brew issue where it seems to install some non-free components after brew explicitly removing them.

**Comment by Toontje** [comment]
OK, understood. I will post the same message on the Elastic forums. Let's see if i get something from there. I hope they don't send me to the Homebrew forum... ;-)
