### ISSUE TITLE
Restore txt2tags@2.6 since txt2tags 3.x is not the follower of txt2tags 2.6

### ISSUE THREAD

**Issue by andreasabel** [Homebrew/homebrew-core#63617]
Contrary what the version numbers suggest, txt2tags 3.x is __not__ the follower of txt2tags 2.6.  txt2tags 3.x __removed__ lots of features (targets) from version 2.6 and changed the behavior of the kept targets.  
Thus, when updating the txt2tags formula to 3.7 in https://github.com/Homebrew/homebrew-core/pull/51560, the 2.6 version should have been kept as `txt2tags@2.6`.

Please bring back txt2tags 2.6 to homebrew! 

Thanks!

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by Rylan12** [comment]
Yes, please always fill out the issue template.

Homebrew is an evergreen package manager which means that we always keep formulae at the latest versions. If you would like to maintain your own tap with a `txt2tags@2` formula, you're welcome to do so (`brew extract` is your friend here as mentioned in the [docs](https://docs.brew.sh/Versions))

If you think having a `txt2tags@2` formula meets all of our [versioned formula requirements](https://docs.brew.sh/Versions) and should be added to Homebrew/core, you're welcome to open a PR re-adding it (and explaining why you believe it should be re-added).

**Comment by andreasabel** [comment]
No issue template came up when I wrote this report.  Maybe because I got here from the `blob` and clicked "reference this line in a new issue" (only that I never referenced the line in the end).

> we always keep formulae at the latest versions.

What is your concept of version?  If `Foo1` does `Bar` but `Foo2` does `Baz` is then `Foo2` a new version of `Foo1` only because it says so?

I reported this as a bug because #51560 should have been careful not to overwrite the installer for `txt2tags` `v2` with the one of `v3`, but keep the `v2` around as well.

You wouldn't remove Python2 either just because there is Python3 now.

**Comment by SMillerDev** [comment]
> What is your concept of version? If Foo1 does Bar but Foo2 does Baz is then Foo2 a new version of Foo1 only because it says so?

Yes, that's how software versioning is widely understood to work. If you think the developers shouldn't have released v3 with missing features that's a discussion you should have with them.

> You wouldn't remove Python2 either just because there is Python3 now.

We would and we did.

**Comment by andreasabel** [comment]
> > What is your concept of version? If Foo1 does Bar but Foo2 does Baz is then Foo2 a new version of Foo1 only because it says so?
> 
> Yes, that's how software versioning is widely understood to work. If you think the developers shouldn't have released v3 with missing features that's a discussion you should have with them.

The policies I am aware of,
- Semantic Versioning https://semver.org/
- Haskell Package Versioning Policy https://pvp.haskell.org/

allow breaking changes in the major version, a strong reason to keep the previous major version around.
Would be interested in a similar document that explains
> how software versioning is widely understood

> > You wouldn't remove Python2 either just because there is Python3 now.
> 
> We would and we did.

Indeed, https://stackoverflow.com/questions/60298514/how-to-reinstall-python2-from-homebrew, would never have guessed that you go that far.  I am speechless.

I think this gives me the final push to try [nix](https://nixos.org).
> ... packages ... never change after they have been built. ...
> ... operations like upgrading or uninstalling an application cannot break other applications ...

They even have what I am looking for: https://search.nixos.org/packages?query=txt2tags

# Workaround

Apparently (as recommended for python2) one can also brew from an older version by supplying the commit hash, in this case cfaad055907944ea0f5a520dd8a481c99fb0d447 .

This is how, including the removal of the previous installation `txt2tags` (v3):
```
$ brew unlink txt2tag
$ wget https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/txt2tags.rb
$ brew install txt2tags.rb
$ python2 /usr/local/bin/txt2tags --version
txt2tags version 2.6 <http://txt2tags.org>
```
If this is how you intend things, so be it.

**Comment by Rylan12** [comment]
> The policies I am aware of,
> 
> * Semantic Versioning https://semver.org/
> * Haskell Package Versioning Policy https://pvp.haskell.org/
> 
> allow breaking changes in the major version, a strong reason to keep the previous major version around.
> Would be interested in a similar document that explains

Correct, which is why we allow versioned formulae.

As [stated above](https://github.com/Homebrew/homebrew-core/issues/63617#issuecomment-718169726), you are encouraged to open a PR that adds the formula.

> Apparently (as recommended for python2) one can also brew from an older version by supplying the commit hash, in this case [cfaad05](https://github.com/Homebrew/homebrew-core/commit/cfaad055907944ea0f5a520dd8a481c99fb0d447) .

Yes, this will work. I'd recommend making your own tap and using `brew extract` as I mentioned above.

---

I'm not sure what you're hoping to accomplish with this debate. You've been given two options for how to use `txt2tags` 2.6 with Homebrew and you have decided to none of them.

**Comment by MikeMcQuaid** [comment]
> I'm not sure what you're hoping to accomplish with this debate.

That's why it's stopping. Locked.
