### ISSUE TITLE
sshguard not working on Sierra

### ISSUE THREAD

**Issue by jinschoi** [Homebrew/homebrew-core#6361]
### Bug reports:

Sierra introduced the unified logger, so sshd logs no longer appear in /var/log/system.log where the supplied launchd plist file assumes it will find them.

After some experimentation, I found that this will allow it to continue to work:
- Create a shell script with the following contents:

``` sh
#!/bin/sh

/usr/bin/log stream --level info --style syslog --type log --predicate 'processImagePath endswith "sshd"' | /usr/local/opt/sshguard/sbin/sshguard
```
- Call that script from /Library/LaunchDaemons/homebrew.mxcl.sshguard.plist

**Comment by dunn** [comment]
Is this something that can be fixed upstream?

**Comment by jinschoi** [comment]
No, because it is an integration issue.

**Comment by dunn** [comment]
Sorry, I may have misread.  So it's a problem with our generated plist file?  If so, we'd love a pull request updating it!

**Comment by jinschoi** [comment]
The main issue is that sshguard is looking for sshd log entries where the OS is no longer putting them. I managed to cobble up something that works, but I'm not familiar enough with all the systems involved to be confident that it's the correct fix. I was kind of hoping that someone who is more comfortable with sshguard would chime in and make the fix, but if nobody like that exists here, I can try to put together a pull request.

**Comment by dunn** [comment]
> The main issue is that sshguard is looking for sshd log entries where the OS is no longer putting them.

That does sound to me like an upstream issue; sshguard should be updated to look for logs in the new location on Seirra.

**Comment by MikeMcQuaid** [comment]
> I can try to put together a pull request.

That would be good, thanks. [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
