### ISSUE TITLE
brew install python@3.9 fails

### ISSUE THREAD

**Issue by rdzman** [Homebrew/homebrew-core#63619]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

**Please note:** _Due to the fact that I do not have Homebrew on a local machine, only on the GitHub servers that run GitHub Actions, I was not able to easily run `brew doctor` or `brew gist-logs`. However, [someone else claims](https://github.com/actions/virtual-environments/issues/1926) they were able to reproduce the issue locally, so I suspect it is not something specific to the Homebrew installation._

## What you were trying to do (and why)

Install GNU Octave on macOS runners in a GitHub Action workflow for CI testing of Octave code in some of my repositories, using the following commands:

```
brew update
brew install octave
```

## What happened (include command output)

`brew install octave` fails due to a dependency on `python@3.9`. It appears the installation of `python@3.9` is failing at the `brew link` stage:

<details>
  <summary>Command output</summary>
  <pre>

==> Installing octave dependency: python@3.9
==> Pouring python@3.9-3.9.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
Warning: These files were overwritten during `brew link` step:
The formula built, but is not symlinked into /usr/local
Could not symlink lib/pkgconfig/python3-embed.pc
Target /usr/local/lib/pkgconfig/python3-embed.pc
is a symlink belonging to python@3.8. You can unlink it:
  brew unlink python@3.8

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/lib/pkgconfig/python3-embed.pc -> /usr/local/Cellar/python@3.8/3.8.6/lib/pkgconfig/python3-embed.pc
/usr/local/lib/pkgconfig/python3.pc -> /usr/local/Cellar/python@3.8/3.8.6/lib/pkgconfig/python3.pc
/usr/local/Frameworks/Python.framework/Headers -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Headers
/usr/local/Frameworks/Python.framework/Python -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Python
/usr/local/Frameworks/Python.framework/Resources -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Resources
/usr/local/Frameworks/Python.framework/Versions/Current -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/Current
/usr/local/bin/2to3
/usr/local/bin/idle3
/usr/local/bin/pydoc3
/usr/local/bin/python3
/usr/local/bin/python3-config
/usr/local/share/man/man1/python3.1

They have been backed up in /Users/runner/Library/Caches/Homebrew/Backup

  </pre>
</details>

## What you expected to happen

Successful install of octave and all of its dependencies.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew update
brew install octave
```

... or ...

```
brew update
brew install python@3.9
```

## Additional Notes
- This was reported in actions/virtual-environments#1926 and a collaborator was able to reproduce it, claiming it was probably a brew issue, likely introduced in Homebrew/homebrew-core@200fc9d.
- My current workaround is to eliminate the `brew update` line.

**Comment by maxim-lobanov** [comment]
Additional context:
If machine has already had `python@3.9` installed before this commit: https://github.com/Homebrew/homebrew-core/commit/200fc9d, `brew update && brew install python@3.9` will fail with this error. As a result, installing any tools where `python@3.9` is dependency will fail too

**Comment by SMillerDev** [comment]
Probably `brew upgrade` will fix this since you only have python 3.9 as a dependency it won't update 3.8 to relinquish the symlinks. @fxcoudert any ideas on a better fix?

**Comment by fxcoudert** [comment]
If it's a runner node, why is `python@3.8` present? This is the root of the issue.
The options given by the error message should both work: `brew unlink python@3.8` before installing `python@3.9`, or `brew link --overwrite python@3.9` after.

**Comment by maxim-lobanov** [comment]
@fxcoudert , @SMillerDev , I can reproduce it on my local box too:
Some time ago, I have installed `python@3.8` on my box, then I have installed a bunch of other tools that brought `python@3.9` as dependency. After https://github.com/Homebrew/homebrew-core/commit/200fc9d installing any tool that depend on `python@3.9` fails with the issue above.
Some customers continue using `python@3.8` because 3.9 was released just month ago and not all libraries / code support it. I guess it is common use-case.
Am I right that it is intended breaking change for this use-case and customers have to use workaround above?

The same for GitHub Actions CI. Hosted machines still have `python@3.8` installed as a default Python. `python@3.9` is installed as a dependency of other tools. After this commit, installation of any tools that depend on `python@3.9` fails with the error above. Of course, we have plans to switch default Python to 3.9 on Hosted machines but we can't do it immediately because it is significant breaking change that should be announced in advance

**Comment by SMillerDev** [comment]
Yes, unfortunately the install mechanism isn't smart enough to handle this on it's own. So it'll need an upgrade before.

For actions to keep using the older python you'd need to just add 3.8 to path first when you've done the upgrade.

**Comment by maxim-lobanov** [comment]
@SMillerDev , Thank you for clarification.

Just one more question from my side: we would like to keep python@3.8 for now as default until we do proper communication.
Am I right that we should invoke
```
brew install python@3.8
brew link python@3.8 --force
```
As I can see it creates all necessary symlinks and both python@3.8 and python@3.9 work as expected. Just want to double check.

**Comment by SMillerDev** [comment]
I can't really recommend this. As the `--force` argument implies it's a forceful overwrite of existing files. It might work, it might break all software that depends on 3.9. I can't say for certain.

In addition you'd have to do this again after any 3.9 update AFAIK.

**Comment by MikeMcQuaid** [comment]
@maxim-lobanov If you (or anyone else here) can reproduce from a clean Homebrew install by checking out specific Homebrew-core revisions and installing in a certain order: that would help.

@fxcoudert We should probably consider adding additional `link_overwrite` lines to handle this.

**Comment by maxim-lobanov** [comment]
I think it is related to two PRs:
- Convert `python@3.8` to keg-only: https://github.com/Homebrew/homebrew-core/commit/25f8eeb394c2f60e3b56f0a39f1abd523fa65b17
- Convert `python@3.9` from keg-only to default python: https://github.com/Homebrew/homebrew-core/commit/200fc9d

@MikeMcQuaid , I was able to reproduce it with the following steps on clean MacOS 10.15 VM:
```bash
# Install homebrew
HOMEBREW_INSTALL_URL="https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
/bin/bash -c "$(curl -fsSL ${HOMEBREW_INSTALL_URL})"

# Go to homebrew repo directory
cd $(brew --repo)/Library/Taps/homebrew/homebrew-core

# Checkout any revision before two pull-requests above
git checkout d787a354a4a1ffc6708d66dea984b983ac2925cb
# Prevent automatic brew update
export HOMEBREW_NO_AUTO_UPDATE=1

# Install python 3.8
brew install python@3.8

# Install Python 3.9 or any tool that consume it as dependency
brew install python@3.9

# Go to the latest commit
git checkout HEAD
brew update

# Install any formula that depends on python@3.9 or install it directly.
brew install python@3.9
```
Use case above is our use-case in CI when CI machines still have python@3.8 as default because VM machines were built before these changes. After these changes installing any packages that depend on python@3.9 is broken and requires extra steps from customers.

Or even simpler case:
```bash
# Install homebrew
HOMEBREW_INSTALL_URL="https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
/bin/bash -c "$(curl -fsSL ${HOMEBREW_INSTALL_URL})"

# Go to homebrew repo directory
cd $(brew --repo)/Library/Taps/homebrew/homebrew-core

# Checkout any revision before two pull-requests above
git checkout d787a354a4a1ffc6708d66dea984b983ac2925cb
# Prevent automatic brew update
export HOMEBREW_NO_AUTO_UPDATE=1

# Install python 3.8
brew install python@3.8

# Go to the latest commit
git checkout HEAD
brew update

# Install any formula that depends on python@3.9 or install it directly.
brew install python@3.9
```
In the case above, we even didn't have python@3.9 before. We just had python@3.8 that works perfectly for us. And we decide to install some tool that requires python@3.9. Installation will fail and brew will force us to link python@3.9.

Both use-cases above fail with the following error:
<details><summary>CLICK ME</summary>
<p>
```
Mac-2006:homebrew-core runner$ brew install python@3.9
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/fb4e0fa1e5bd0801809e88ee99df2640974bb3953e0ebfe56541ff1ba2fd486
######################################################################## 100.0%
==> Pouring python@3.9-3.9.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink lib/pkgconfig/python3-embed.pc
Target /usr/local/lib/pkgconfig/python3-embed.pc
is a symlink belonging to python@3.8. You can unlink it:
  brew unlink python@3.8

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.9

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.9

Possible conflicting files are:
/usr/local/lib/pkgconfig/python3-embed.pc -> /usr/local/Cellar/python@3.8/3.8.6/lib/pkgconfig/python3-embed.pc
/usr/local/lib/pkgconfig/python3.pc -> /usr/local/Cellar/python@3.8/3.8.6/lib/pkgconfig/python3.pc
/usr/local/Frameworks/Python.framework/Headers -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Headers
/usr/local/Frameworks/Python.framework/Python -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Python
/usr/local/Frameworks/Python.framework/Resources -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Resources
/usr/local/Frameworks/Python.framework/Versions/Current -> /usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/Current
Warning: These files were overwritten during `brew link` step:
/usr/local/bin/2to3
/usr/local/bin/idle3
/usr/local/bin/pydoc3
/usr/local/bin/python3
/usr/local/bin/python3-config
/usr/local/share/man/man1/python3.1

They have been backed up in /Users/runner/Library/Caches/Homebrew/Backup
==> /usr/local/Cellar/python@3.9/3.9.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts
==> /usr/local/Cellar/python@3.9/3.9.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts
==> /usr/local/Cellar/python@3.9/3.9.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.9/3.9.0_1: 4,447 files, 72MB
Removing: /usr/local/Cellar/python@3.9/3.9.0... (4,459 files, 72.3MB)
Removing: /Users/runner/Library/Caches/Homebrew/python@3.9--3.9.0.catalina.bottle.1.tar.gz... (18.0MB)
Mac-2006:homebrew-core runner$ 
```
</p>
</details>

**Comment by fxcoudert** [comment]
As a general comment: I think it is best practice, after running `brew update`, to run `brew upgrade` to have an homogeneous environment. There are, I think, other problems that could arise from installing formulas after updating if you haven't upgraded other formulas.

**Comment by MikeMcQuaid** [comment]
@fxcoudert That shouldn't be the case. We should be enforcing that requirement ourselves in code rather than expecting users to do so.

**Comment by fxcoudert** [comment]
@MikeMcQuaid I must confess I never really understood why `brew update` and `brew upgrade` are separate operations

**Comment by SMillerDev** [comment]
Because Mike really likes Apt. I just don't see how we can enforce this in code without resulting in dirty hacks though. The only thing I can think of is "when we update `A`, also update any `A@1`, `A@2`".

**Comment by fxcoudert** [comment]
The only file that is not already `link_overwrite` is `lib/pkgconfig/python3-embed.pc`. I've opened a PR for this: https://github.com/Homebrew/homebrew-core/pull/63665

In a clean install, this PR gets rid of the problem described above at https://github.com/Homebrew/homebrew-core/issues/63619#issuecomment-718593870

**Comment by maxim-lobanov** [comment]
@fxcoudert , @MikeMcQuaid  thank you for fixing it! I have checked and it works as expected after your PR.

Off-topic question about Python installation:
What is the best way to freeze python@3.8 after these changes and link it as default?
For now, I get the following error:
![image](https://user-images.githubusercontent.com/16715858/97565986-53e40100-19f7-11eb-8cc1-8b2682ede2c4.png)
but @SMillerDev mentioned that `brew link --force` is not recommended way.

**Comment by fxcoudert** [comment]
@maxim-lobanov If you do not have `python@3.9` installed, linking `python@3.8` should not be a problem. If you want to have both, then you'll have to make a choice about which is linked.

**Comment by maxim-lobanov** [comment]
@fxcoudert , We need to have both but 3.8 as default one.
In my understanding, we should invoke
```bash
brew install python@3.8
brew install python@3.9
brew link python@3.8 --force
```
But I am a bit concerned that @SMillerDev mentioned https://github.com/Homebrew/homebrew-core/issues/63619#issuecomment-718404594

**Comment by MikeMcQuaid** [comment]
@maxim-lobanov `--force` is fine/expected for now. I'm working towards a nicer workflow in https://github.com/Homebrew/brew/pull/9009
