### ISSUE TITLE
NTFS-3G mounting script not working correctly on macOS Catalina

### ISSUE THREAD

**Issue by dragonandy** [Homebrew/homebrew-core#63732]
# Bug report

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

NTFS-3G automount files not showing in finder
an option `-o auto_xattr` is needed in the script

## What happened (include command output)

https://github.com/osxfuse/osxfuse/issues/574
ntfs-3g mounted volumes cant show files in Finder, It only shows folders. after some digging It happen to be an NTFS-3g problem and there is a workaround by add `auto_xattr` option when mounting NTFS volumes. It could done by modify the `mount_ntfs` automount script in the `ntfs-3g.rb` formula.

## What you expected to happen

I modify the script to make it works on macOS Catalina, I need someone else to test ntfs-3g formula from macOS 10.10 to 10.16, because I only have a macbook with 10.15 installed and the fix is only tested on my macbook

## Step-by-step reproduction instructions (by running `brew install` commands)

NONE

**Comment by MikeMcQuaid** [comment]
We don't support the use of software.

**Comment by dragonandy** [comment]
Agree 
but the automount script is provided by the `ntfs-3g.rb` file.
I create a pull request to fix it. Hope for the merge, its quite important to make it run out of the box.😉
