### ISSUE TITLE
mpv fails due : 10.11 > 1 error generated?

### ISSUE THREAD

**Issue by mrkapqa** [Homebrew/homebrew-core#63910]
# Bug report

## What you were trying to do (and why)

install mpv + vapoursynth via svp4mac homebrew script.

https://pastebin.ubuntu.com/p/5fWs8MPZbd/

it fails after considerable time with the following output

## What happened (include command output)

==> Installing mpv dependency: openjdk
==> Patching
==> Applying f80a6066e45c3d53a61715abfe71abc3b2e162a1.patch
patching file src/hotspot/share/runtime/sharedRuntime.cpp
Hunk #1 succeeded at 2850 (offset -6 lines).
==> Applying 4622a18a72c30c4fc72c166bee7de42903e1d036.patch
patching file src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m
==> ./configure --without-version-pre --without-version-opt --with-version-build=9 --with-toolchain-path=/usr/bin --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk --with-extra-ldflags=-headerpad_max_install_names --with-boot-jdk=/private/tmp/openjdk-20201101-20313-kr3y4n/jdk15u-jdk-15.0.1-ga/boot-jdk/Contents/Home --with-boot-jdk-jvmargs=-Duser.home=/Users/rich/Library/Caches/Homebrew/java_cache --with-debug-level=release --with-native-debug-symbols=none --enable-dtrace --with-jvm-variants=server
==> make images
Last 15 lines from /Users/rich/Library/Logs/Homebrew/openjdk/02.make:
./src/jdk.incubator.jpackage/share/native/applauncher/AppLauncher.cpp:224:41: error: default initialization of an object of const type 'const (anonymous namespace)::ResetLastErrorMsgAtEndOfScope' without a user-provided default constructor
    const ResetLastErrorMsgAtEndOfScope resetLastErrorMsg;
                                        ^
                                                          = {}
1 error generated.

* All command lines available in /private/tmp/openjdk-20201101-20313-kr3y4n/jdk15u-jdk-15.0.1-ga/build/macosx-x86_64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [main] Error 2
make: *** [images] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

## What you expected to happen

to build successfully, 

i did post this here because i could not think of any other more appropriate place.

thank you for considering.

**Comment by SMillerDev** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!
Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

**Comment by mrkapqa** [comment]
pl3qse let me know if i can do anything about it, thanks.

**Comment by smoretti** [comment]
Same issue for me.
I am stuck to update subversion that requires openjdk at build time
