### ISSUE TITLE
iwyu (include-what-you-use) install fails

### ISSUE THREAD

**Issue by acgetchell** [Homebrew/homebrew-core#64078]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

> Error: No logs.

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

> adam@hapkido ~ $ brew config
HOMEBREW_VERSION: 2.5.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c822206a05cd7fffe526b8e0fa2f45365be72a5
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fa04848b21d7ab9c89978e1d6fec9920ef4e4a5e
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.M17SRggg4g/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
Clang: N/A
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.1.0.0.1.1602137645
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

> adam@hapkido ~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

> Warning: Unknown support status

> Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

> Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

> Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/python3.7-config
  /usr/local/Caskroom/miniconda/base/bin/python3.7m-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
  /usr/local/Caskroom/miniconda/base/bin/ncurses6-config

## What you were trying to do (and why)

> brew install iwyu

## What happened (include command output)

There's a permission error.

<details>
  <summary>Command output</summary>
  <pre>

  > adam@hapkido ~ $ brew install iwyu
==> Downloading https://homebrew.bintray.com/bottles/include-what-you-use-0.14.catalina.bottle.tar.gz
Already downloaded: /Users/adam/Library/Caches/Homebrew/downloads/56abbf52ed865ce0214adccf1381d381d5334cf9eb09d212419f24713a9bccb6--include-what-you-use-0.14.catalina.bottle.tar.gz
==> Pouring include-what-you-use-0.14.catalina.bottle.tar.gz
cp: /var/folders/by/dzryzz_14_qcbkkwl4jmqrf40000gn/T/d20201103-7532-1m82xdb/include-what-you-use/./0.14/libexec/bin/include-what-you-use: Permission denied
Error: Failure while executing; `cp -pR /var/folders/by/dzryzz_14_qcbkkwl4jmqrf40000gn/T/d20201103-7532-1m82xdb/include-what-you-use/. /usr/local/Cellar/include-what-you-use` exited with 1. Here's the output:
cp: /var/folders/by/dzryzz_14_qcbkkwl4jmqrf40000gn/T/d20201103-7532-1m82xdb/include-what-you-use/./0.14/libexec/bin/include-what-you-use: Permission denied

> Warning: Bottle installation failed: building from source.
xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
See `man xcode-select` for more details.
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/adam/Library/Caches/Homebrew/downloads/8f9c536881abdd0cce6d863fe46fe556198abb8916d8673a3b3b5e958bdb6d78--576c30a31ec3f6592a0fd68b0d19cb0880203569.patch
  </pre>
</details>

## What you expected to happen

That Include-What-You-Use would install.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install iwyu

**Comment by gromgit** [comment]
Just did a successful test install from bottle. so it shouldn't be a permissions issue in the bottle.

Try `rm -fr /usr/local/Cellar/include-what-you-use`, then `brew install` again.

**Comment by SMillerDev** [comment]
Also try fixing the errors in `brew doctor`.

**Comment by acgetchell** [comment]
The warnings from `brew doctor` are a result of installing `miniconda`.

Still getting permission denied. The folder doesn't actually exist.

```
adam@hapkido ~ $ rm -rf /usr/local/Cellar/include-what-you-use
adam@hapkido ~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
Homebrew's ability to download packages. See:
  https://github.com/Homebrew/brew/issues/5558

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/python3.7-config
  /usr/local/Caskroom/miniconda/base/bin/python3.7m-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
  /usr/local/Caskroom/miniconda/base/bin/ncurses6-config
adam@hapkido ~ $ brew install iwyu
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
tree-sitter
==> Updated Formulae
Updated 18 formulae.
==> New Casks
ibm-aspera-connect
==> Updated Casks
axure-rp         flipper          hstracker        obsidian         roboform
boost-note       hackintool       memo             plex
==> Deleted Casks
aspera-connect

==> Downloading https://homebrew.bintray.com/bottles/include-what-you-use-0.14.catalina
Already downloaded: /Users/adam/Library/Caches/Homebrew/downloads/56abbf52ed865ce0214adccf1381d381d5334cf9eb09d212419f24713a9bccb6--include-what-you-use-0.14.catalina.bottle.tar.gz
==> Pouring include-what-you-use-0.14.catalina.bottle.tar.gz
cp: /var/folders/by/dzryzz_14_qcbkkwl4jmqrf40000gn/T/d20201104-17842-s1bwzo/include-what-you-use/./0.14/libexec/bin/include-what-you-use: Permission denied
Error: Failure while executing; `cp -pR /var/folders/by/dzryzz_14_qcbkkwl4jmqrf40000gn/T/d20201104-17842-s1bwzo/include-what-you-use/. /usr/local/Cellar/include-what-you-use` exited with 1. Here's the output:
cp: /var/folders/by/dzryzz_14_qcbkkwl4jmqrf40000gn/T/d20201104-17842-s1bwzo/include-what-you-use/./0.14/libexec/bin/include-what-you-use: Permission denied

Warning: Bottle installation failed: building from source.
==> Patching
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/adam/Library/Caches/Homebrew/downloads/8f9c536881abdd0cce6d863fe46fe556198abb8916d8673a3b3b5e958bdb6d78--576c30a31ec3f6592a0fd68b0d19cb0880203569.patch
```

**Comment by MikeMcQuaid** [comment]
> xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
> 
> Use ```
> sudo xcode-select --switch path/to/Xcode.app
> ```
> 
>  to specify the Xcode that you wish to use for command line developer tools, or use ```
> xcode-select --install
> ```
> 
>  to install the standalone command line developer tools.

This looks likely to be a problem.

> Warning: You have installed Bitdefender. The "Traffic Scan" option interferes with
> Homebrew's ability to download packages. See:
> [Homebrew/brew#5558](https://github.com/Homebrew/brew/issues/5558)

As does this.

As a result: closing.

**Comment by acgetchell** [comment]
Yep. Uninstalling BitDefender and miniconda resulted:
```
adam@hapkido ~ $ brew update
Updated 1 tap (homebrew/cask).
==> Updated Casks
brave-browser                    grandtotal                       rocket-chat                      texmacs
adam@hapkido ~ $ brew doctor
Your system is ready to brew.
adam@hapkido ~ $ brew install iwyu
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
spires

==> Downloading https://homebrew.bintray.com/bottles/include-what-you-use-0.14.catalina.bottle.tar.gz
Already downloaded: /Users/adam/Library/Caches/Homebrew/downloads/56abbf52ed865ce0214adccf1381d381d5334cf9eb09d212419f24713a9bccb6--include-what-you-use-0.14.catalina.bottle.tar.gz
==> Pouring include-what-you-use-0.14.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/include-what-you-use/0.14: 351 files, 36.7MB
```

**Comment by MikeMcQuaid** [comment]
> * [x]  ran `brew doctor`, fixed all issues and can still reproduce the problem?

Glad you got it fixed. I don't want to hammer this home too hard but that's why we ask you to do this before opening issues.
