### ISSUE TITLE
llvm@10 is removed in favor of llvm@11

### ISSUE THREAD

**Issue by MichielDerhaeg** [Homebrew/homebrew-core#64094]
https://github.com/Homebrew/homebrew-core/commit/4f931e6e7b6c1242f2a7f5f5410577fcf3e1a294#diff-5e996f93f5a1c45f4e6fc81331d60ad9171f503668b9d2521cce250d3c164dd9
This commits removes `llvm@10` in favor of `llvm@11`.
Is there a good reason why `llvm@10` was removed? I still rely on this particular version.
Can't the old version be left in place?

**Comment by SMillerDev** [comment]
That commit updates llvm, see https://github.com/Homebrew/homebrew-core/pull/63938 for the state of llvm@10

**Comment by MichielDerhaeg** [comment]
@SMillerDev Thanks :)
