### ISSUE TITLE
Terragrunt brew tap should point to v0.26.0

### ISSUE THREAD

**Issue by ina-stoyanova** [Homebrew/homebrew-core#64095]
# Bug report
Terragrunt release with tag **v0.26.1** has been deleted, and is therefore wrong. The latest version released is **v0.26.0**.
This is a result of releasing the latest terragrunt code with the wrong version number. Since then, that's been corrected, however, this tap still seems to point & return `v0.26.1`.

For more details on the latest release:
The URL should be changed to: https://github.com/gruntwork-io/terragrunt/archive/v0.26.0.tar.gz 
You can find the release notes here: https://github.com/gruntwork-io/terragrunt/releases/tag/v0.26.0

The v.0.26.1 release cannot be found:
https://github.com/gruntwork-io/terragrunt/releases/tag/v0.26.1

Could advise on next steps how to update this brew tap? I've filed an issue describing 
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install terragrunt latest verison

## What happened (include command output)

Brew installs `v0.26.1`, when that doesn't correspond to a release in terragrunt. 

<details>
  <summary>Command output</summary>
  <pre>

```
~ brew install terragrunt                         
Warning: terragrunt 0.26.1 is already installed and up-to-date
To reinstall 0.26.1, run `brew reinstall terragrunt`
~ terragrunt --version                                                                                                   
terragrunt version v0.26.1
```
  </pre>
</details>

## What you expected to happen

Terragrunt brew tap to be pointing & installing the v0.26.0 version

## Step-by-step reproduction instructions (by running `brew install` commands)

1. Run `brew install terragrunt`
2. Go to Terragrunt releases page 
3. See that the latest release is `v0.26.0`

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
