### ISSUE TITLE
Abseil needs to be compiled with set(CMAKE_POSITION_INDEPENDENT_CODE ON)

### ISSUE THREAD

**Issue by root42** [Homebrew/homebrew-core#64167]
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

[brew_config.txt](https://github.com/Homebrew/homebrew-core/files/5494744/brew_config.txt)
[brew_doctor.txt](https://github.com/Homebrew/homebrew-core/files/5494749/brew_doctor.txt)

## What you were trying to do (and why)

Tried to install grpc by doing "brew install grpc".

## What happened (include command output)

<details>
  <summary>brew install grpc</summary>
  <pre>

==> Cloning https://github.com/grpc/grpc.git
Updating /home/aschmitz/.cache/Homebrew/grpc--git
==> Checking out tag v1.32.0
HEAD is now at 414bb8322d Merge pull request #24074 from markdroth/1.32-release
HEAD is now at 414bb8322d Merge pull request #24074 from markdroth/1.32-release
Entering 'third_party/abseil-cpp'
Entering 'third_party/benchmark'
Entering 'third_party/bloaty'
Synchronizing submodule url for 'third_party/googletest'
Synchronizing submodule url for 'third_party/libFuzzer'
Synchronizing submodule url for 'third_party/re2'
Entering 'third_party/bloaty/third_party/googletest'
Entering 'third_party/bloaty/third_party/libFuzzer'
Entering 'third_party/bloaty/third_party/re2'
Entering 'third_party/boringssl-with-bazel'
Entering 'third_party/cares/cares'
Entering 'third_party/envoy-api'
Entering 'third_party/gflags'
Synchronizing submodule url for 'doc'
Entering 'third_party/gflags/doc'
Entering 'third_party/googleapis'
Entering 'third_party/googletest'
Entering 'third_party/libuv'
Entering 'third_party/protobuf'
Synchronizing submodule url for 'third_party/benchmark'
Synchronizing submodule url for 'third_party/googletest'
Entering 'third_party/protobuf/third_party/benchmark'
Entering 'third_party/protobuf/third_party/googletest'
Entering 'third_party/protoc-gen-validate'
Entering 'third_party/re2'
Entering 'third_party/udpa'
Entering 'third_party/zlib'
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/abseil-cpp
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/benchmark
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/bloaty
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/bloaty/third_party/googletest
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/bloaty/third_party/libFuzzer
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/bloaty/third_party/re2
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/boringssl-with-bazel
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/cares/cares
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/envoy-api
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/gflags
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/gflags/doc
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/googleapis
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/googletest
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/libuv
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/protobuf
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/protobuf/third_party/benchmark
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/protobuf/third_party/googletest
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/protoc-gen-validate
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/re2
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/udpa
/home/aschmitz/.cache/Homebrew/grpc--git/third_party/zlib
==> cmake ../.. -DBUILD_SHARED_LIBS=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_INSTALL=ON -DgRPC_ABSL_PROVIDER=package -DgRPC_CARES_PROVIDER=package -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_SSL_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_RE2_PROVIDER=package
==> make install
Last 15 lines from /home/aschmitz/.cache/Homebrew/Logs/grpc/02.make:
[  4%] Building CXX object CMakeFiles/grpc_plugin_support.dir/src/compiler/php_generator.cc.o
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5 -Dgrpc_plugin_support_EXPORTS -I/tmp/grpc-20201105-4431-lel4ei/include -I/tmp/grpc-20201105-4431-lel4ei -I/tmp/grpc-20201105-4431-lel4ei/third_party/address_sorting/include -I/tmp/grpc-20201105-4431-lel4ei/src/core/ext/upb-generated -I/tmp/grpc-20201105-4431-lel4ei/src/core/ext/upbdefs-generated -I/tmp/grpc-20201105-4431-lel4ei/third_party/upb -I/tmp/grpc-20201105-4431-lel4ei/cmake/build/gens -DNDEBUG -fPIC -std=c++11 -o CMakeFiles/grpc_plugin_support.dir/src/compiler/php_generator.cc.o -c /tmp/grpc-20201105-4431-lel4ei/src/compiler/php_generator.cc
[  4%] Building CXX object CMakeFiles/grpc_plugin_support.dir/src/compiler/python_generator.cc.o
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5 -Dgrpc_plugin_support_EXPORTS -I/tmp/grpc-20201105-4431-lel4ei/include -I/tmp/grpc-20201105-4431-lel4ei -I/tmp/grpc-20201105-4431-lel4ei/third_party/address_sorting/include -I/tmp/grpc-20201105-4431-lel4ei/src/core/ext/upb-generated -I/tmp/grpc-20201105-4431-lel4ei/src/core/ext/upbdefs-generated -I/tmp/grpc-20201105-4431-lel4ei/third_party/upb -I/tmp/grpc-20201105-4431-lel4ei/cmake/build/gens -DNDEBUG -fPIC -std=c++11 -o CMakeFiles/grpc_plugin_support.dir/src/compiler/python_generator.cc.o -c /tmp/grpc-20201105-4431-lel4ei/src/compiler/python_generator.cc
[  5%] Building CXX object CMakeFiles/grpc_plugin_support.dir/src/compiler/ruby_generator.cc.o
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5 -Dgrpc_plugin_support_EXPORTS -I/tmp/grpc-20201105-4431-lel4ei/include -I/tmp/grpc-20201105-4431-lel4ei -I/tmp/grpc-20201105-4431-lel4ei/third_party/address_sorting/include -I/tmp/grpc-20201105-4431-lel4ei/src/core/ext/upb-generated -I/tmp/grpc-20201105-4431-lel4ei/src/core/ext/upbdefs-generated -I/tmp/grpc-20201105-4431-lel4ei/third_party/upb -I/tmp/grpc-20201105-4431-lel4ei/cmake/build/gens -DNDEBUG -fPIC -std=c++11 -o CMakeFiles/grpc_plugin_support.dir/src/compiler/ruby_generator.cc.o -c /tmp/grpc-20201105-4431-lel4ei/src/compiler/ruby_generator.cc
[  5%] Linking CXX shared library libgrpc_plugin_support.so
/home/linuxbrew/.linuxbrew/Cellar/cmake/3.18.4/bin/cmake -E cmake_link_script CMakeFiles/grpc_plugin_support.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5 -fPIC -DNDEBUG -shared -Wl,-soname,libgrpc_plugin_support.so.1 -o libgrpc_plugin_support.so.1.32.0 CMakeFiles/grpc_plugin_support.dir/src/compiler/cpp_generator.cc.o CMakeFiles/grpc_plugin_support.dir/src/compiler/csharp_generator.cc.o CMakeFiles/grpc_plugin_support.dir/src/compiler/node_generator.cc.o CMakeFiles/grpc_plugin_support.dir/src/compiler/objective_c_generator.cc.o CMakeFiles/grpc_plugin_support.dir/src/compiler/php_generator.cc.o CMakeFiles/grpc_plugin_support.dir/src/compiler/python_generator.cc.o CMakeFiles/grpc_plugin_support.dir/src/compiler/ruby_generator.cc.o  /home/linuxbrew/.linuxbrew/lib/libprotoc.so /home/linuxbrew/.linuxbrew/lib/libprotobuf.so -ldl -lrt -lm -lpthread -lpthread 
/home/linuxbrew/.linuxbrew/Cellar/cmake/3.18.4/bin/cmake -E cmake_symlink_library libgrpc_plugin_support.so.1.32.0 libgrpc_plugin_support.so.1 libgrpc_plugin_support.so
make[2]: Leaving directory '/tmp/grpc-20201105-4431-lel4ei/cmake/build'
[  5%] Built target grpc_plugin_support
make[1]: Leaving directory '/tmp/grpc-20201105-4431-lel4ei/cmake/build'
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

I would expect for grpc to install fine. Closer inspection shows that abseil wasn't compiled with -fPIC so it can't link to grpc. See the attached log from grpc for details

[brew_install_grpc.txt](https://github.com/Homebrew/homebrew-core/files/5494754/brew_install_grpc.txt)

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install grpc

**Comment by SMillerDev** [comment]
@Homebrew/linux ?

**Comment by jonchang** [comment]
Pretty sure this is somewhat related to https://github.com/Homebrew/homebrew-core/issues/62589. I don't know if we ever figured out a satisfactory resolution to these grpc/abseil/etc problems.

**Comment by root42** [comment]
> @Homebrew/linux ?

Oh, sorry. Did I put this in the wrong section? Is this not a problem on macOS as well?

**Comment by root42** [comment]
> Pretty sure this is somewhat related to #62589. I don't know if we ever figured out a satisfactory resolution to these grpc/abseil/etc problems.

I am currently compiling with fPIC enabled. Let’s see if that fixes at least this one problem. Not sure if it opens up other problems.

**Comment by fxcoudert** [comment]
Closing as no progress is being made, not sure this is an issue on macOS.
