### ISSUE TITLE
FFMPEG 3.2 Doesn't Install / Upgrade

### ISSUE THREAD

**Issue by zenopopovici** [Homebrew/homebrew-core#6418]
## Long story short

```
./configure
--prefix=/usr/local/Cellar/ffmpeg/3.2
--enable-shared
--enable-pthreads
--enable-gpl
--enable-version3
--enable-hardcoded-tables
--enable-avresample
--cc=clang
--host-cflags=
--host-ldflags=
--enable-libfaac
--enable-libmp3lame
--enable-libx264
--enable-libxvid
--enable-opencl
--disable-lzma
--enable-nonfree
--enable-vda

Unknown option "--enable-libfaac".
See ./configure --help for available options.
```

## Logs:
https://gist.github.com/eb1d0f73dccc55c81769f5f6a4d75ad3

**Comment by jrosengren** [comment]
It looks like support for libfaac was removed:

http://git.videolan.org/?p=ffmpeg.git;a=commit;h=dc0f711459e0c682bf9f94ba38d26736e90cff45

**Comment by retokromer** [comment]
Consider using FFmpeg’s native AAC encoder (`-c:a aac`).

**Comment by jrosengren** [comment]
This isn't a runtime issue, it's a compilation issue.

**Comment by schoeps** [comment]
I guess someone should make a PR removing `--with-faac` and adding `deprecated_option "with-faac"    => "with-fdk-aac"`.

**Comment by retokromer** [comment]
As long as I know `faac` is not the same as Fraunhofer’s `fdk-aac`.

**Comment by schoeps** [comment]
They are different but faac is not supported anymore (see the commit message posted above), so the best options is switching to fdk-aac.

**Comment by retokromer** [comment]
May I disagree? The best option, in my opinion, is to switch to the native AAC encoder.

**Comment by schoeps** [comment]
The problem occurs if a user has explicitly asked for `faac`, so the user was probably not happy with the native implementation. In either case `faac` is not supported upstream, so homebrew should remove the switch. I would follow the recommendation of the VLC team and recommend `fdk-aac` instead. I am not going to open a PR since I am not using `ffmpeg` much.

**Comment by dunn** [comment]
I think the best thing to do is just remove the option; the `deprecated_option` method is for when we rename a switch, which isn't what's happening here.

**Comment by zmwangx** [comment]
> The problem occurs if a user has explicitly asked for faac, so the user was probably not happy with the native implementation.

The native implementation is relatively new, that's all. Pretty sure it's better than faac in almost every way possible at this point.
