### ISSUE TITLE
'make' and 'remake' conflict

### ISSUE THREAD

**Issue by J-M0** [Homebrew/homebrew-core#64187]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
<summary>brew config</summary>
<pre>
HOMEBREW_VERSION: 2.5.8-72-g0e36cdc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0e36cdcf0fae2fca4b8defe53ac86c16790c92ee
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4dd0e28f30746df0d8431569739fb2561e9c0cfb
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 10.0 build 1001
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_141
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
</pre>
</details>

<details>
<summary>brew doctor</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  libmsiecf

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  opencv@2

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/jmorris/.pyenv/shims/python3.5m-config
  /Users/jmorris/.pyenv/shims/python3.6m-config
  /Users/jmorris/.pyenv/shims/python3.7-config
  /Users/jmorris/.pyenv/shims/python3.7m-config
  /Users/jmorris/.pyenv/shims/python3.5-config
  /Users/jmorris/.pyenv/shims/python-config
  /Users/jmorris/.pyenv/shims/python3-config
  /Users/jmorris/.pyenv/shims/python3.6-config
  /Users/jmorris/.pyenv/shims/python3.8-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  remake
</pre>
</details>

## What you were trying to do (and why)

Install `remake`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles/remake-4.3-1.5.mojave.bottle.tar.gz
Already downloaded: /Users/jmorris/Library/Caches/Homebrew/downloads/78e97e2be4235be4fbde27579f1c05aab4c54383762a4c750c7b5edb35cc3e70--remake-4.3-1.5.mojave.bottle.tar.gz
==> Pouring remake-4.3-1.5.mojave.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/info/make.info
Target /usr/local/share/info/make.info
is a symlink belonging to make. You can unlink it:
  brew unlink make

To force the link and overwrite all conflicting files:
  brew link --overwrite remake

To list all files that would be deleted:
  brew link --overwrite --dry-run remake

Possible conflicting files are:
/usr/local/share/info/make.info -> /usr/local/Cellar/make/4.3/share/info/make.info
/usr/local/share/info/make.info-1 -> /usr/local/Cellar/make/4.3/share/info/make.info-1
/usr/local/share/info/make.info-2 -> /usr/local/Cellar/make/4.3/share/info/make.info-2
==> Summary
🍺  /usr/local/Cellar/remake/4.3-1.5: 14 files, 1.5MB
  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install make
brew install remake
```
##

I wanted to submit a PR to fix this, but didn't know if I should just add `conflicts_with` to the formulas or if we should try to make them install side by side. I personally like the latter option but that might require patches for `remake`.

**Comment by MikeMcQuaid** [comment]
> I wanted to submit a PR to fix this, but didn't know if I should just add `conflicts_with` to the formulas or if we should try to make them install side by side. I personally like the latter option but that might require patches for `remake`.

A PR would be great, thanks! I'd say mark them as conflicting for now and when any patches are merged upstream in remake we can consider removing it.

**Comment by J-M0** [comment]
OK, I'll submit a PR later today or tomorrow

**Comment by iMichka** [comment]
Fixed by #64384
