### ISSUE TITLE
willgit link failure

### ISSUE THREAD

**Issue by verdurin** [Homebrew/homebrew-core#6423]
'willgit' failed to link, with the following error:

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/git-rank-contributors
Target /usr/local/bin/git-rank-contributors
is a symlink belonging to git-utils. You can unlink it:
  brew unlink git-utils

To force the link and overwrite all conflicting files:
  brew link --overwrite willgit

To list all files that would be deleted:
  brew link --overwrite --dry-run willgit

Possible conflicting files are:
/usr/local/bin/git-rank-contributors -> /usr/local/Cellar/git-utils/1.0/bin/git-rank-contributors
/usr/local/bin/git-wtf -> /usr/local/Cellar/git-utils/1.0/bin/git-wtf

**Comment by dunn** [comment]
Sounds like we need to mark `willgit` and `git-utils` as conflicting.

**Comment by dunn** [comment]
Depending on which version of `git-rank-contributors` you want, run `brew link --overwrite <formula>` for that formula.
