### ISSUE TITLE
Elmer failed to build on OS 10.12.1

### ISSUE THREAD

**Issue by Norwinvd** [Homebrew/homebrew-core#6424]
Hello,

thanks for supporting the Elmer installation by home-brew.
I get stuck, I hope you can fix this.

Please find a copy of the error below.

Cheers,
Norwin

### Bug reports:
==> cmake ../ -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/elmer/HEAD-d3bf396 -DWITH
Last 15 lines from /Users/Norwin/Library/Logs/Homebrew/elmer/01.cmake:
-Wno-dev

-- The Fortran compiler identification is GNU 6.2.0
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/CMakeDetermineCCompiler.cmake:57 (message):
  Could not find compiler set in environment variable CC:

  /usr/local/opt/gcc/bin/gcc-7.
Call Stack (most recent call first):
  CMakeLists.txt:17 (PROJECT)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs elmer`: https://gist.github.com/4e325ec341eae76cc5728b07b7652934
(where `<formula>` is the name of the formula that failed to build).

**Comment by dunn** [comment]
This issue was moved to ElmerCSC/homebrew-elmerfem#5

**Comment by dunn** [comment]
You're trying to install a formula that's not part of our core tap, so I moved the issue to the third-party repository.
