### ISSUE TITLE
`brew install fish --HEAD` fails with error

### ISSUE THREAD

**Issue by zx8** [Homebrew/homebrew-core#64371]
Originally raised upstream @ https://github.com/fish-shell/fish-shell/issues/7469, but directed here as it seems to be caused by the recent PR https://github.com/Homebrew/homebrew-core/pull/64348 (ping @fxcoudert)

---

# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading 1 outdated package:
fish HEAD-bff1f1a -> HEAD-e5061bc
==> Upgrading fish HEAD-bff1f1a -> HEAD-e5061bc
==> Cloning https://github.com/fish-shell/fish-shell.git
Updating /Users/zx8/Library/Caches/Homebrew/fish--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at e5061bcda docs: Use `string split -n` for pkg-config
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
CMakeLists.txt:
  expected replacement of "CODESIGN_ON_MAC(${target})" with ""
  </pre>
</details>

## What you expected to happen

Fish `HEAD` revision would be installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew instead fish --HEAD`

**Comment by fxcoudert** [comment]
HEAD builds are supported on a best effort only. We will consider pull requests, but will not directly fix specific issues. (I will open a PR in this case, as it's a trivial fix)
