### ISSUE TITLE
log4cxx missing symbols

### ISSUE THREAD

**Issue by spaghetti-** [Homebrew/homebrew-core#6437]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

```
dyld: lazy symbol binding failed: Symbol not found: _apr_stat$INODE64
  Referenced from: /usr/local/opt/log4cxx/lib/liblog4cxx.10.dylib
  Expected in: flat namespace

dyld: Symbol not found: _apr_stat$INODE64
  Referenced from: /usr/local/opt/log4cxx/lib/liblog4cxx.10.dylib
  Expected in: flat namespace
```

```
❯ brew info log4cxx
log4cxx: stable 0.10.0 (bottled)
Library of C++ classes for flexible logging
https://logging.apache.org/log4cxx/index.html
/usr/local/Cellar/log4cxx/0.10.0 (185 files, 6.1M) *
  Built from source on 2016-10-31 at 02:22:00 with: --c++11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/log4cxx.rb
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
Required: apr-util ✔
==> Options
--c++11
        Build using C++11 mode
--universal
        Build a universal binary
```

Seems like log4cxx is finding the apr provided by CTL instead of Homebrew (`apr` and `apr-util` are installed, latest version)

Looks correct according to otool though

```
❯ otool -L liblog4cxx.dylib
liblog4cxx.dylib:
        /usr/local/opt/log4cxx/lib/liblog4cxx.10.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib (compatibility version 6.0.0, current version 6.4.0)
        /usr/local/opt/apr/libexec/lib/libapr-1.0.dylib (compatibility version 6.0.0, current version 6.2.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
        /usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version 8.0.0)
        /usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
```

**Comment by MikeMcQuaid** [comment]
> Seems like log4cxx is finding the apr provided by CTL instead of Homebrew (apr and apr-util are installed, latest version)

Can you give an example of what you're running to get this output? Thanks!

**Comment by M-Mueller** [comment]
I ran into the same problem but I think it is an issue with `apr`, which does not define the required symbols:
```
> nm /usr/local/Cellar/apr/1.5.2_3/libexec/lib/libapr-1.0.dylib | grep -i INODE64
                 U _fstat$INODE64
                 U _lstat$INODE64
                 U _opendir$INODE64
                 U _readdir_r$INODE64
                 U _rewinddir$INODE64
                 U _stat$INODE64
```
In the system apr these symbols are defined:
```
> nm /usr/lib/libapr-1.0.dylib | grep -i INODE64
000000000000a057 T _apr_dir_open$INODE64
000000000000a141 T _apr_dir_read$INODE64
000000000000a334 T _apr_dir_rewind$INODE64
000000000000b22a T _apr_file_info_get$INODE64
000000000000b09d T _apr_file_info_get_locked$INODE64
000000000000b367 T _apr_stat$INODE64
                 U _fstat$INODE64
                 U _lstat$INODE64
                 U _opendir$INODE64
                 U _readdir_r$INODE64
                 U _rewinddir$INODE64
                 U _stat$INODE64
```
Here is minimum example:
[example.zip](https://github.com/Homebrew/homebrew-core/files/575530/example.zip)

**Comment by lloydc99** [comment]
I had the same problem and the fix in #5599 fixed my problem.

It seems too version specific to push as a fix though.

[log4cxx_apr-patch](https://gist.github.com/lloydc99/811603d21e0078e894e2702882d5469e#file-log4cxx_apr-patch)

**Comment by MikeMcQuaid** [comment]
Sorry but none of you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ilovezfs** [comment]
@spaghetti- @M-Mueller @lloydc99 the formula should be fixed now if you `brew update`

Thanks for reporting this @spaghetti- and thank you @M-Mueller for that test, which I've incorporated into the formula as well.
