### ISSUE TITLE
nifi 1.9.2 no more available

### ISSUE THREAD

**Issue by VishalTejaswi** [Homebrew/homebrew-core#64404]
Did check that, its actually not available anymore.

> The requested file or directory is not on the mirrors

Infact 1.9.2 is available. By changing the .rb file to latest one should fix it.

_Originally posted by @RioLynnnnn in https://github.com/Homebrew/homebrew-core/issues/38989#issuecomment-484183708_

**Comment by VishalTejaswi** [comment]
Available latest version is 1.21.1 with sha256 key as https://downloads.apache.org/nifi/1.12.1/nifi-1.12.1-bin.tar.gz.sha256 , can someone please update it.

**Comment by Rylan12** [comment]
`nifi` was updated to version 1.12.1 over a month ago in #61977 

In the future, the best way to get a formula updated is to open a PR that updates it ([these docs](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request#submit-a-new-version-of-an-existing-formula) might be helpful).

If something isn't working, please open a new issue and fill out the issue template so we can help.
