### ISSUE TITLE
Bug: watchman + non standard homebrew dir

### ISSUE THREAD

**Issue by aren55555** [Homebrew/homebrew-core#6454]
I have brew installed in my home directory; `which brew` results in: `/Users/aren/homebrew/bin/brew`

If I run `brew install watchman` it will be installed from the bottle; and as a result the `--enable-statedir=#{var}/run/watchman` will evaluate to `--enable-statedir=/usr/local/var/run/watchman`

The `post_install` will then create `/Users/aren/homebrew/var`. The `/usr/local/var/run/watchman` directory will not be created.

This is problematic; and `watchman version` will return the error:

```
2016-10-31T16:59:25,440: [3053900736] while computing sockname: failed to create /usr/local/var/run/watchman/aren-state: No such file or directory
```

However; if install watchman and build from source `brew install --build-from-source watchman`, subsequently running `watchman version` will successfully return:

```json
{
    "version": "4.7.0"
}
```

Is there a way to update the `watchman.rb` build script such that non standard homebrew directories can be supported when simply doing `brew install watchman`

**Comment by ilovezfs** [comment]
@MikeMcQuaid this appears to be a rather nasty bug. The bottle is deemed relocatable even though there's still a hard-coded `/usr/local/var/run/watchman` in `libexec/"bin/watchman"`, which does not get corrected during relocation.

**Comment by ilovezfs** [comment]
@MikeMcQuaid I think this bug was caused by the migration because the repository check (`if keg_contain?(repository, keg, ignores)`) no longer covers `/usr/local`, only `/usr/local/Homebrew`, and when the prefix is `/usr/local`, `bottle` only checks `/usr/local/opt` for the prefix check (`if keg_contain?(prefix_check, keg, ignores)`) so `/usr/local/var/run/watchman` now goes totally under the radar.

**Comment by ilovezfs** [comment]
Ah I see the repository check was only added after the migration so this problem may go all the way back to 6718ca119c11bebb1f2d901a4ae15a2193837cf1

**Comment by alexkrolick** [comment]
This appears to have resurfaced as https://github.com/facebook/watchman/issues/495
