### ISSUE TITLE
Allow some way of specifying "Node.js-ish" dependency

### ISSUE THREAD

**Issue by Daniel15** [Homebrew/homebrew-core#6458]
Hi! I work on [Yarn](https://yarnpkg.com/), a package manager for JavaScript. Currently, our Homebrew formula specifies [a dependency on Node.js](https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb#L17). This is not ideal for people that use other methods of installing Node.js, such as [nvm]( http://nvm.sh) or [n](https://github.com/tj/n). For those people, Homebrew will install a separate version of Node.js, likely blowing away the version installed by `nvm` or `n`.

I'd like to propose some way of allowing packages to declare that they require a "node.js-ish environment".  For example, Yarn could declare that it needs some node.js-ish environment, and installing *either* Node.js *or* nvm through Homebrew would fulfill that requirement. On Debian, this would be done with a *virtual package*

I'm sorry I'm not very familiar with Homebrew - I recently switched from Mac OS back to Windows so I can't really look into this myself.

Also see https://github.com/yarnpkg/yarn/issues/1116

**Comment by bfontaine** [comment]
There’s currently a pull-request for that; see https://github.com/Homebrew/brew/pull/1408.

**Comment by Daniel15** [comment]
Oh cool, thanks for the info 😄
