### ISSUE TITLE
Missing Revision bump in bash formula

### ISSUE THREAD

**Issue by csalch-indeed** [Homebrew/homebrew-core#64582]
# Bug report
|

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

There were two changes to the Bash formula in the last week:
https://github.com/Homebrew/homebrew-core/commit/6e1b1f6b4c74586dcb243e6651c4b83750a22e5b#diff-674ca280e13032da45e03edcc6a901fc3e5c9fa7505df6cf7710c1563a45b4d6

and 
https://github.com/Homebrew/homebrew-core/commit/26ed174a94aa81aff563f7f3c692345ac07166ba#diff-674ca280e13032da45e03edcc6a901fc3e5c9fa7505df6cf7710c1563a45b4d6

The first introduced a bug that was difficult to detect or reproduce and is now difficult to upgrade out of because there was not a revision change even though the formula itself changed. This seems like a mistake to me ..

Can someone give insight no what's happening here? I would have expected the revision to field of the formula to change if the bottle was rebuilt...

## What you were trying to do (and why)

Install bash via homebrew.

## What happened (include command output)

The bash formula installed, but we have different builds on different machines depending on when they were installed. Even though the formula has changed, there is no way to update to the most recent version/build without removing and reinstalling the formula by hand.

Note: I'm starting working in a clone of homebrew core checked out to https://github.com/Homebrew/homebrew-core/commit/43ab8ac99ad79972238df1da1dc0c42f09d9c7e0#diff-674ca280e13032da45e03edcc6a901fc3e5c9fa7505df6cf7710c1563a45b4d6 to illustrate the issue.

<details>
  <summary>Command output</summary>
  <pre>

csalch@IT-USA-25903 Formula % brew install ./bash.rb
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/bash-5.0.18.catalina.bottle.1.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ca367f96ad5c40ae70b155af67d0a4ab772b16c55ccfc99b9317ae0afbbbc493?response-content-disposition=attachment%3Bfilename%3D%22bash-5.0.18.catalina.bottle.1.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvY2EzNjdmOTZhZDVjNDBhZTcwYjE1NWFmNjdkMGE0YWI3NzJ
######################################################################## 100.0%
==> Pouring bash-5.0.18.catalina.bottle.1.tar.gz
🍺  /usr/local/Cellar/bash/5.0.18: 150 files, 10.4MB
Removing: /Users/csalch/Library/Caches/Homebrew/bash--5.0.18.catalina.bottle.1.tar.gz... (2.9MB)
csalch@IT-USA-25903 Formula % git status
HEAD detached at 43ab8ac99a
nothing to commit, working tree clean
csalch@IT-USA-25903 Formula % brew upgrade bash
Updating Homebrew...
Warning: bash 5.0.18 already installed
csalch@IT-USA-25903 Formula % brew remove bash --ignore-dependencies
Uninstalling /usr/local/Cellar/bash/5.0.18... (150 files, 10.4MB)

Warning: The following may be bash configuration files and have not been removed!
If desired, remove them manually with `rm -rf`:
  /usr/local/etc/bash_completion
  /usr/local/etc/bash_completion.d
csalch@IT-USA-25903 Formula % brew install bash
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/bash-5.0.18.catalina.bottle.2.tar.gz
Already downloaded: /Users/csalch/Library/Caches/Homebrew/downloads/3b274810b9320a175c0e4b21ff4371d456f04a3f9cfdcb31dd1fcc1b2376ef9f--bash-5.0.18.catalina.bottle.2.tar.gz
==> Pouring bash-5.0.18.catalina.bottle.2.tar.gz
🍺  /usr/local/Cellar/bash/5.0.18: 150 files, 10.3MB
csalch@IT-USA-25903 Formula %

  </pre>
</details>

## What you expected to happen

I expected `brew upgrade bash` to install the most recent build. Especially since the builds for these three commits are different:
https://github.com/Homebrew/homebrew-core/commit/9591758fd8a565abf98d13ffd87c66e5e12ad579
https://github.com/Homebrew/homebrew-core/commit/43ab8ac99ad79972238df1da1dc0c42f09d9c7e0
https://github.com/Homebrew/homebrew-core/commit/afbb6a32bc2c52fc4274cda1162be94b6a7307ed

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew remove bash --ignore-dependencies
git clone git@github.com:Homebrew/homebrew-core.git
cd homebrew-core
git checkout 43ab8ac99ad79972238df1da1dc0c42f09d9c7e0
brew install ./Formula/bash.rb
brew update
brew upgrade bash
```

**Comment by fxcoudert** [comment]
If you installed bash in the short window where it had issues, you can fix it with `brew reinstall bash`

We only increase the revision number if we want all users to be migrate to the new version. This was not the case, given the old version was working well and we only wanted to fix the build on newer installations.
