### ISSUE TITLE
pgbouncer won't start with provided configuration

### ISSUE THREAD

**Issue by davidfetter** [Homebrew/homebrew-core#64623]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## Nothing
```
pgbouncer -q /usr/local/etc/pgbouncer.ini
```

<details>
  <summary></summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

I expected pgbouncer to start. Examining the logs showed that the path to the pid file named in the config file did not exist.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install pgbouncer
pgbouncer -q /usr/local/etc/pgbouncer.ini
```

This could be fixed a couple of ways: by ensuing that `/usr/local/var/run` exists and is a directory, or by changing the configuration provided to point to a path that already exists.

**Comment by jonchang** [comment]
Can you open a pull request for this adding a `post_install` to pgbouncer? Thanks!

**Comment by davidfetter** [comment]
I'll stare at a few `post_install` scripts and make sure the one I do is safe, idempotent, and so forth.
