### ISSUE TITLE
MacOS big sur compatibility issue

### ISSUE THREAD

**Issue by NawafSwe** [Homebrew/homebrew-core#64732]
getting this issue after updating my mac to big sur 
You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or any other official channels. You are responsible for
resolving any issues you experience while you are running this
released but not yet supported version.

**Comment by Rylan12** [comment]
Not sure what to say, the message is pretty clear.
