### ISSUE TITLE
blink1 - Permission denied.

### ISSUE THREAD

**Issue by brettswift** [Homebrew/homebrew-core#6478]
brew updated.   It only shows xcode is out of date. 
 
### Bug reports:

`blink1`  shows permission denied.   The blink1 website says to chown 777 the blink1 directory which seems overkill - however I did it anyways..  still no luck. 

```
/usr/local/Homebrew ➤ 8d5df2e|stable✓
$ brew update
Already up-to-date.

/usr/local/Homebrew ➤ 8d5df2e|stable✓
$ brew upgrade blink1 
Error: blink1 1.98 already installed

/usr/local/Homebrew ➤ 8d5df2e|stable✓
$ blink1 -h 
zsh: permission denied: blink1


```

**Comment by mistydemeo** [comment]
`blink1` installs its executable under the name `blink1-tool`, not `blink1` - does that work for you?

**Comment by brettswift** [comment]
Uhm, yea. :)   Thanks..  I guess the blink1 is put there by the desktop app or something else.
