### ISSUE TITLE
libcaca - Add --HEAD support?

### ISSUE THREAD

**Issue by equal-l2** [Homebrew/homebrew-core#6482]
`libcaca` has the own repository on github now.
https://github.com/cacalabs/libcaca

Simply adding `head "https://github.com/cacalabs/libcaca"` in formula seems not working.
Can you make the formula to support `--HEAD` option?

**Comment by bfontaine** [comment]
Can you try a pull-request? 🙂

**Comment by ilovezfs** [comment]
@bfontaine no need https://github.com/Homebrew/homebrew-core/pull/6484.

**Comment by ilovezfs** [comment]
@equal-l2 if you `brew update` it should work now.

**Comment by equal-l2** [comment]
@ilovezfs It seems to be working correctly.
Thank you for your work.
