### ISSUE TITLE
You are using macOS 11.0. We do not provide support for this pre-release version.

### ISSUE THREAD

**Issue by hzzhongjian** [Homebrew/homebrew-core#65006]
==> Installing dependencies for git-lfs: go, autoconf, automake, libtool, libyaml and ruby
==> Installing git-lfs dependency: go
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.15.5/bin/go install -race std
==> go build
Last 15 lines from /Users/robin/Library/Logs/Homebrew/go/03.go:
2020-11-17 21:13:43 +0800

go
build

go: github.com/yuin/goldmark@v1.1.27: Get "https://proxy.golang.org/github.com/yuin/goldmark/@v/v1.1.27.mod": dial tcp 216.58.200.241:443: i/o timeout

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
go-jira: added zsh completion https://github.com/Homebrew/homebrew-core/pull/63420
go 1.15 upgrade failure tracker https://github.com/Homebrew/homebrew-core/issues/59698
linkerd 2.9.0 is built with go 1.15 which leads to x509 error https://github.com/Homebrew/homebrew-core/issues/64498
[epic] Remove GOPATH for go modules formula https://github.com/Homebrew/homebrew-core/issues/47627

Error: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

**Comment by SMillerDev** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!
