### ISSUE TITLE
Add nghttp2 to unbound

### ISSUE THREAD

**Issue by ian351c** [Homebrew/homebrew-core#65027]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgraded to unbound 1.12 hoping for DNS over HTTP support. Unfortunately this requires unbound to be compiled with nghttp2 support and that is not the case right now.

## What happened (include command output)

Unbound installs fine and can be configured for DNS over HTTPS, but upon startup the following entry appears in the log file: "warning: Unbound is not compiled with nghttp2. This is required to use DNS-over-HTTPS."

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew

**Comment by alebcay** [comment]
Addressed in #65573.
