### ISSUE TITLE
Download failed: https://bugzilla.opensuse.org/attachment.cgi?id=746044

### ISSUE THREAD

**Issue by jonathanong** [Homebrew/homebrew-core#65127]
# Bug report

Trying to install libvips on a new Apple Mac mini M1 (Apple Silicon). It fails at a download step:

```zsh
==> Downloading https://bugzilla.opensuse.org/attachment.cgi?id=746044
-=O=-               #    #     #     #                                        
curl: (7) Failed to connect to bugzilla.opensuse.org port 443: Operation timed out
Error: Failed to download resource "libxml2--patch"
Download failed: https://bugzilla.opensuse.org/attachment.cgi?id=746044
```

NOTE: I understand that Apple Silicon is not supported, but this seems to be a resource issue that would occur on any system that compiles from scratch.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
  - no output
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```zsh
brew install libvips
```

## What happened (include command output)

```zsh
% brew config
HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bdb039cc19d85bc8b5e451378db266b1c8168a56
Core tap last commit: 71 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit dunno
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-arm64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
Rosetta 2: false
```

<details>
  <summary>Command output</summary>
  <pre>
jong@JonathansMiniM1 hopics-server % brew install libvips
Warning: You are running macOS on a arm64 CPU architecture.
We do not provide support for this (yet).
Reinstall Homebrew under Rosetta 2 until we support it.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.

==> Downloading https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/f764a0eb59db42aae5fc86f1ba2e36f8c68e29b2cdc98b295a0533f50716bc95--cfitsio-3.49.tar.gz
==> Downloading https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/ade51fddb351cd85e1645e43543cff053bc2f667ec8a7eb1c7554ac301a30d4b--gmp-6.2.1.tar.xz
==> Downloading http://isl.gforge.inria.fr/isl-0.22.1.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/32dbb5c5213a848139ed5f078f07d42f469fc0d9632da11b85c6588e98f5a4bb--isl-0.22.1.tar.xz
==> Downloading https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/3f11146de08683840db066a410717a2bbb406d32c5fea9303bc5aa68aa258cfd--mpfr-4.1.0.tar.xz
==> Downloading https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/de6ea7959f72f1055c234c989bcc9a1cf8ead082d5d062b3a511d02857adddef--mpc-1.2.1.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/7baf6e2f/gcc/bigsur.diff
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/b09b60b5cbfe9a4f8def153bcb9a44251d54a2caa572c63ca5d9ffab785637ce--bigsur.diff
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-10.2.0/gcc-10.2.0.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/c8d4ca732a98ae691d04472b15de6d9e06a09016499af6ff16c4f55081bfc6b9--gcc-10.2.0.tar.xz
==> Downloading https://www.open-mpi.org/software/hwloc/v2.3/downloads/hwloc-2.3.0.tar.bz2
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/061c85acec9c6add73a54a8c24451dd97dcf734eabc724e1a64ddb57496b29db--hwloc-2.3.0.tar.bz2
==> Downloading https://github.com/libevent/libevent/archive/release-2.1.12-stable.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/f04d06e973407046885d2ddc9dcff2efa53ae2dd877656adfc8b6a7221113a70--libevent-release-2.1.12-stable.tar.gz
==> Downloading https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.5.tar.bz2
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/ae9adb0e9e8255c986a4297e818a8384ca37314a17e70a1a5e7396d3e698ee92--openmpi-4.0.5.tar.bz2
==> Downloading http://fftw.org/fftw-3.3.8.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/3f5fe7907dd970a931a3957db73eea98df7fdc07b15e587c3a68a5bb30cef684--fftw-3.3.8.tar.gz
==> Downloading https://downloads.sourceforge.net/project/libpng/libpng16/1.6.37/libpng-1.6.37.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/02881c49026280becca480eff6a11a40341074335b81330f2b71819a28822150--libpng-1.6.37.tar.xz
==> Downloading https://downloads.sourceforge.net/project/freetype/freetype2/2.10.4/freetype-2.10.4.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/c9e85cd23f3c5b8c363d49fcd787f1606bb58b639ddcccd2d7d95dee364822ca--freetype-2.10.4.tar.xz
==> Downloading https://github.com/freedesktop/fontconfig/commit/6def66164a36eed968aae872d76acfac3173d44a.patch?full_index=1
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/02935d80e5d69d69ee7b07a3dedad09c68bfa3c2ce599aa1536c24f20fa79cc7--6def66164a36eed968aae872d76acfac3173d44a.patch
==> Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.13.1.tar.bz2
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/707a631c311b2e5c4cf1797f81dba360fe6147b5f49a1797547d8c768a8bde71--fontconfig-2.13.1.tar.bz2
==> Downloading https://sourceforge.net/p/giflib/bugs/_discuss/thread/4e811ad29b/c323/attachment/Makefile.patch
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/96a5fa155b0ad1a98cc4d577b7806eedfadcde973df641a6e90cf257b08e3598--Makefile.patch
==> Downloading https://downloads.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/516725ea41ab2e3e2e554c736ec0ef0e0d7fcb52e597a831e2398422843276bd--giflib-5.2.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/06/8c/eb8a0ae49eba5be054ca32b3a1dca432baee1d83c4f125d276c6a5fd2d20/virtualenv-20.1.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/b4e86049c816dde47c7a914a6db0f94a5688cb385de88d3bb08edd041e561aa6--virtualenv-20.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdirs-1.4.4.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/b25916e85753e80fccf86f2f1ba088b86d1a82c93cd36bdb72613c81cb830c55--distlib-0.3.1.zip
==> Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/6132211d03cc3113b135a5b72510e3b6ea1df5bf527eb89d71c3f45085c252a7--filelock-3.0.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/cc/b4/ed8dcb0d67d5cfb7f83c4d5463a7614cb1d078ad7ae890c9143edebbf072/alabaster-0.7.12.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/6fe7e7241e703f9e3f03f1600efd5a1f03bb466b8bc79871d35be3da87239d71--alabaster-0.7.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/41/1b/5ed6e564b9ca54318df20ebe5d642ab25da4118df3c178247b8c4b26fa13/Babel-2.9.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/eb74dad8d11547564933a00dbd651b8caa869f35ec55294b7e067036e652e425--Babel-2.9.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/e6/de/879cf857ae6f890dfa23c3d6239814c5471936b618c8fb0c8732ad5da885/certifi-2020.11.8.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/63d25501458c6585c22167278509e1d1e4ee323ecb43f0ff5ba2712d0930b052--certifi-2020.11.8.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/e0/3d435b34abd2d62e8206171892f174b180cd37b09d57b924ca5c2ef2219d/docutils-0.16.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/bee502905dc3428f44a8c0cb547106a3931a395c3c2cf973848a0c0032fc0998--docutils-0.16.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ea/b7/e0e3c1c467636186c39925827be42f16fee389dc404ac29e930e9136be70/idna-2.10.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/70659672fb0872c9cfb410161104337eae58aca1a607a5c63a2a452757d6faf0--idna-2.10.tar.gz
==> Downloading https://files.pythonhosted.org/packages/e4/9f/0452b459c8ba97e07c3cd2bd243783936a992006cf4cd1353c314a927028/imagesize-1.2.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/ce4f2407ec2acdfd8aa5357f5d14900318ec172b8f6d77eb3cba4f9bc72db9d3--imagesize-1.2.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/64/a7/45e11eebf2f15bf987c3bc11d37dcc838d9dc81250e67e4c5968f6008b6c/Jinja2-2.11.2.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/35edb62c9dadaf8a485c3064d37cdab7bbbc38de4365ade27167eff7bfe70ef1--Jinja2-2.11.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/ef7c3d863a1666e25931c26c999dd56b38582d198b145c01c2909f386351bc46--MarkupSafe-1.1.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/55/fd/fc1aca9cf51ed2f2c11748fa797370027babd82f87829c7a8e6dbe720145/packaging-20.4.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/618253f89f8800b545faf121702b2204b673a275fb39b80c65ced932f251f034--packaging-20.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/5d/0e/ff13c055b014d634ed17e9e9345a312c28ec6a06448ba6d6ccfa77c3b5e8/Pygments-2.7.2.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/3f5e8c5dd84d5fe9df30847774768dfee7fcd4838a3d7bcf5da71eba0fcd5224--Pygments-2.7.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c1/47/dfc9c342c9842bbe0036c7f763d2d6686bcf5eb1808ba3e170afdb282210/pyparsing-2.4.7.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/f62c96d488908268a2499dd686ece4b13d1deb6000d0cbda1fc4742d22397d0e--pyparsing-2.4.7.tar.gz
==> Downloading https://files.pythonhosted.org/packages/09/07/448a8887c7195450604dfc0305d80d74324c36ee18ed997664051d4bffe3/pytz-2020.4.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/dd971a84c902bf675b90c04965899326f00110c5395df7d08d76084e85379eb5--pytz-2020.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/9f/14/4a6542a078773957aa83101336375c9597e6fe5889d20abda9c38f9f3ff2/requests-2.25.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/198c5176a7a115ee1870681a8caba7fd6efb519884aa16ed86b2e53bf7c92067--requests-2.25.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/21/1b/6b8bbee253195c61aeaa61181bb41d646363bdaa691d0b94b304d4901193/snowballstemmer-2.0.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/548ae4f5d5a61192f0db37a495ba492b82ce584701c64246b178a37278210c2a--snowballstemmer-2.0.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/9f/01/ad9d4ebbceddbed9979ab4a89ddb78c9760e74e6757b1880f1b2760e8295/sphinxcontrib-applehelp-1.0.2.
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/1570c2b2bf9ce0b9c5e994a7ada997dff2474f85f5a7db7f3d27644d82bdf0e7--sphinxcontrib-applehelp-1.0.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/98/33/dc28393f16385f722c893cb55539c641c9aaec8d1bc1c15b69ce0ac2dbb3/sphinxcontrib-devhelp-1.0.2.ta
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/857c58712c97e9ef60252ece34766e3701540fa8bc51528ce47b4cc90dc1d90c--sphinxcontrib-devhelp-1.0.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/c9/2e/a7a5fef38327b7f643ed13646321d19903a2f54b0a05868e4bc34d729e1f/sphinxcontrib-htmlhelp-1.0.3.t
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/9b0d74c2bbdeb91290b2d9a1c27e660211551417f3a88e1925c7e94d970a6ed0--sphinxcontrib-htmlhelp-1.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b2/e8/9ed3830aeed71f17c026a07a5097edcf44b692850ef215b161b8ad875729/sphinxcontrib-jsmath-1.0.1.tar
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/0cac3fdf6ce0ddabef294d3fbde4de8265e0c47f14daaa259388f4dd1805549c--sphinxcontrib-jsmath-1.0.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b1/8e/c4846e59f38a5f2b4a0e3b27af38f2fcf904d4bfd82095bf92de0b114ebd/sphinxcontrib-qthelp-1.0.3.tar
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/8e4c6f7bdec732ed005f10a8bfc2cb56e0487656133ad214825ab85e0beecfbd--sphinxcontrib-qthelp-1.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/ac/86/021876a9dd4eac9dae0b1d454d848acbd56d5574d350d0f835043b5ac2cd/sphinxcontrib-serializinghtml-
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/7d31dacff6edf58aa41b3a127e8f3c8040b26e29b936fbfe56b1946997216127--sphinxcontrib-serializinghtml-1.1.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/19/80/b2a19b372f16bc846fd156de8d9b3a9b1092aef1f1963d800b0f8c76a67a/urllib3-1.26.1.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/56e906c71d477ad6283f8e3ebe57863177fdfa5011dd696a146d3901f7eb54a1--urllib3-1.26.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/16/06/9a7ce305cf7c31d5f167f83e37c159e8b79ebe595b627cbc7d73d8468e81/Sphinx-3.3.1.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/bd3abf7d55cbc8526ef1345aecc76420269ad8c0321283227ee55374042aeb4d--Sphinx-3.3.1.tar.gz
==> Downloading https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/bb11533563004cdfcffb2210c073677f4146dbea89c1b48e9471a96cb1be0069--cmake-3.18.4.tar.gz
==> Downloading https://github.com/ninja-build/ninja/commit/2f3e5275e2ea67cb634488957adbb997c2ff685f.patch?full_index=1
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/ecc737305b23088678aed714ad9e10658fe1fc9b82c8af8255f96f78f506db0a--2f3e5275e2ea67cb634488957adbb997c2ff685f.patch
==> Downloading https://github.com/ninja-build/ninja/archive/v1.10.1.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/d0aa9bad5dd53f5822123f0a4f79d76f23c7921c6f076b2a92b20bf3ac80b137--ninja-1.10.1.tar.gz
==> Downloading https://github.com/mesonbuild/meson/releases/download/0.56.0/meson-0.56.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/5f6695feed847ffe9f6e5ef84931caa0e47a6c603e683c7f8026d6af21b2d0da--meson-0.56.0.tar.gz
==> Downloading https://sourceware.org/pub/libffi/libffi-3.3.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/df395aced2b6e5f77d3d02dae7d38dfc927bf58ceee4c98193be2318d0dc7c77--libffi-3.3.tar.gz
==> Downloading https://ftp.pcre.org/pub/pcre/pcre-8.44.tar.bz2
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/26d6d64b1dd138a02838ae49167401caeec92d83115d0822fbee5fbe50139599--pcre-8.44.tar.bz2
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6164294a75541c278f3863b111791376caa3ad26/glib/hardcoded-paths.diff
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/54f3f612bdfc9bfc09633176c7673816fe2a2188e470bf48d60d826bdf6bf21a--hardcoded-paths.diff
==> Downloading https://download.gnome.org/sources/glib/2.66/glib-2.66.2.tar.xz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/d84365340156c2341f3e3ebd947f3cf93efb2ded74b72412243bd95ac8f1abb6--glib-2.66.2.tar.xz
==> Downloading https://www.ijg.org/files/jpegsrc.v9d.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/23faa446d5ad2c8f0a288f26af4c4f70666394f107eb58154ab432da5f6705d1--jpegsrc.v9d.tar.gz
==> Downloading https://download.osgeo.org/libtiff/tiff-4.1.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/a2e14ab74f7606d02a36f9ff3130fb0f68725728ebc2f092fa228599a9db9422--tiff-4.1.0.tar.gz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/98c39e09/ghostscript/config.patch
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/c91924918bc1ee76098652c48a7f507119fd79f11a9c7359a93aa05a261eea48--config.patch
==> Downloading https://downloads.sourceforge.net/project/gs-fonts/gs-fonts/8.11%20%28base%2035%2C%20GPL%29/ghostscript-fonts-std-8.11.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/88570590ca21f2e13196537698364cde58f3e7b46115cae4896f2febef83d500--ghostscript-fonts-std-8.11.tar.gz
==> Downloading https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9533/ghostpdl-9.53.3.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/c1de83b49cf4300a187f48ff4eae6fa1ea47658cb58d9ce2970761f86a145d99--ghostpdl-9.53.3.tar.gz
==> Downloading https://github.com/strukturag/libde265/releases/download/v1.0.8/libde265-1.0.8.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/4b70b74d0e2fc25ef7f1f5c02c9991391e8e8def385f2abc6e00022ef117c563--libde265-1.0.8.tar.gz
==> Downloading https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
Already downloaded: /Users/jong/Library/Caches/Homebrew/downloads/275f23fce0ca19bc7e760d481db42baf10a03868c357814a925df3c787dc7007--intltool-0.51.0.tar.gz
==> Downloading https://bugzilla.opensuse.org/attachment.cgi?id=746044
-=O=-               #    #     #     #                                        
curl: (7) Failed to connect to bugzilla.opensuse.org port 443: Operation timed out
Error: Failed to download resource "libxml2--patch"
Download failed: https://bugzilla.opensuse.org/attachment.cgi?id=746044
  </pre>
</details>

## What you expected to happen

To complete the following:

```zsh
brew install libvips
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```zsh
brew install libvips
```

**Comment by jonchang** [comment]
Not really anything Homebrew can do about it. https://twitter.com/openSUSE/status/1329078508971122696

**Comment by SMillerDev** [comment]
In addition there's this note in your install output:
> Warning: You are running macOS on a arm64 CPU architecture.
We do not provide support for this (yet).
Reinstall Homebrew under Rosetta 2 until we support it.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.

and this one:
> Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.
