### ISSUE TITLE
Remove old fixes/workarounds

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#65180]
Over time, we tend to keep in formulas some "workarounds" or fixes for old versions of OS or Xcode, that are not longer needed anymore.

Examples I can think of are:

- Passing `gl_cv_func_ftello_works=yes` to configure, which is not needed since Catalina 10.15.1 (it was libc issue in the .0 macOS release)
- Adding `-fno-stack-check` to `CFLAGS`, which used to work around an Xcode 10.0 compiler bug that was fixed in later Xcode versions

These should probably be removed, but it takes time to create these pull requests (ideally separate pull requests for each formula, to avoid opportunistic linking if we touch many formulas at once). Help wanted!

**Comment by bayandin** [comment]
I've removed mentioned workarounds manually, and then have created a bunch of PRs with this script:

```bash
#! /usr/bin/env bash

set -x

pushd $(brew --repo homebrew/homebrew-core)
for f in coreutils findutils gawk gettext gnu-sed gnu-tar gnutls lftp wget; do
    git checkout -b "remove-old-workaround-$f"
    git add "Formula/$f.rb"
    git commit -m "$f: remove gl_cv_func_ftello_works=yes workaround"
    git push -u fork
    gh pr create --title "$f: remove gl_cv_func_ftello_works=yes workaround" --body "See https://github.com/Homebrew/homebrew-core/issues/65180"
    git checkout master
done

for f in ansible ansible@2.8 aom azure-cli erlang@20 ghc git-delta guile guile@2 libtommath mpg123 openttd ufraw x265; do
    git checkout -b "remove-old-workaround-$f"
    git add "Formula/$f.rb"
    git commit -m "$f: remove -fno-stack-check workaround"
    git push -u fork
    gh pr create --title "$f: remove -fno-stack-check workaround" --body "See https://github.com/Homebrew/homebrew-core/issues/65180"
    git checkout master
done

popd
```

**Comment by fxcoudert** [comment]
Thank for the help! I'll close this now
