### ISSUE TITLE
file-roller fails to install

### ISSUE THREAD

**Issue by joelittlejohn** [Homebrew/homebrew-core#652]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

Can't install file-roller due to:

`org.gnome.FileRoller.gschema.xml:41:31  Error on line 41 char 31: Only one <summary> element allowed inside <key>.  --strict was specified; exiting.`

Full logs at:
https://gist.github.com/anonymous/095782a1538efdb71fe1865b1af09e51

**Comment by dunn** [comment]
Here's the upstream issue from 2015; there's been no response and this error still occurs on 3.20.1 so I think we're going to have to remove this formula from Homebrew.

**Comment by ilovezfs** [comment]
This fixes it:
```
diff --git a/Formula/file-roller.rb b/Formula/file-roller.rb
index 7af5972..ea8968e 100644
--- a/Formula/file-roller.rb
+++ b/Formula/file-roller.rb
@@ -22,6 +22,9 @@ class FileRoller < Formula
   depends_on "gnome-icon-theme"
 
   def install
+    inreplace "configure",
+      "$(AM_V_GEN) $(GLIB_COMPILE_SCHEMAS) --strict --dry-run $(addprefix --schema-file=,$(gsettings__enum_file)) --schema-file=$< && mkdir -p $(@D) && touch $@",
+      "$(AM_V_GEN) $(GLIB_COMPILE_SCHEMAS) --dry-run $(addprefix --schema-file=,$(gsettings__enum_file)) --schema-file=$< && mkdir -p $(@D) && touch $@"
     # forces use of gtk3-update-icon-cache instead of gtk-update-icon-cache. No bugreport should
     # be filed for this since it only occurs because Homebrew renames gtk+3's gtk-update-icon-cache
     # to gtk3-update-icon-cache in order to avoid a collision between gtk+ and gtk+3.

```

Unless someone wants to bother with a more "proper" fix like this one:
https://github.com/mate-desktop/mate-utils/commit/c4df12f12d21ea7d4bc0d656bd5f93539c078d93
