### ISSUE TITLE
macdeployqt utility broken in Brew's Qt package

### ISSUE THREAD

**Issue by martinrotter** [Homebrew/homebrew-core#65269]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Install latest qt formula, compile some Qt-base program (**which uses QtWebEngine module**) and deploy it with `macdeployqt`. All Qt-dependencies are then "assembled" by the tool into single application "directory" structure, which can be then merged into DMG for example. Then run the program via DMG on clean Mac machine without homebrew.

## What happened (include command output)
App crashes (or does not work correctly) because homebrew's macdeployqt tool does not set correctly "rpath" and/or "executable_path" of QtWebEngine's libraries within output deployment folder.

This problem is not present in official Qt/Mac distribution.

## What you expected to happen
App runs fine just like when processed with official distributions' macdeployqt tool.

Relevant tickets: https://github.com/martinrotter/rssguard/issues/147 https://bugreports.qt.io/browse/QTBUG-84200

Specifically, this command makes DMG package: `macdeployqt '..../..../app-output-compiled-folder' -dmg`

You can check faulty app here: https://bintray.com/martinrotter/rssguard/Development/LinuxMacOs#files (download newest DMG file) and you will see errors in terminal when launched.

**Comment by SMillerDev** [comment]
Please give all the information in the checkboxes. It's required for proper debugging.

**Comment by martinrotter** [comment]
All remaining checkboxes are out-of-scope for me, do not have Mac machine, sorry not that rich. :)
