### ISSUE TITLE
gnuradio: cannot find blocks or Python modules installed from other packages 

### ISSUE THREAD

**Issue by rgov** [Homebrew/homebrew-core#65387]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install additional blocks for GNU Radio, for instance with the `gr-osmosdr` formula.

## What happened (include command output)

The package installed, but GNU Radio (Companion) does not find the new blocks.

This seems to be because the file `/usr/local/etc/gnuradio/conf.d/grc.conf` only references the GNU Radio keg, and other packages install new blocks into their own kegs.

```
[grc]
global_blocks_path = /usr/local/Cellar/gnuradio/3.8.2.0_3/share/gnuradio/grc/blocks
```

(As an aside, the `xterm_executable` setting also is not valid for macOS.)

Additionally, its Python environment does not know about the Python modules installed by other packages, so you could not use the blocks even if they were loaded:

```
$ /usr/local/Cellar/gnuradio/3.8.2.0_3/libexec/venv/bin/python
>>> import sys,pprint; pprint.pprint(sys.path)
['',
 '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',
 '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
 '/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload',
 '/usr/local/Cellar/gnuradio/3.8.2.0_3/libexec/venv/lib/python3.9/site-packages',
 '/usr/local/Cellar/gnuradio/3.8.2.0_3/lib/python3.9/site-packages',
 '/usr/local/opt/numpy/lib/python3.9/site-packages',
 '/usr/local/opt/py3cairo/lib/python3.9/site-packages',
 '/usr/local/opt/pygobject3/lib/python3.9/site-packages',
 '/usr/local/opt/sip/lib/python3.9/site-packages',
 '/usr/local/opt/pyqt/lib/python3.9/site-packages',
 '/usr/local/opt/volk/lib/python3.9/site-packages']
```

Note that `/usr/local/opt/gr-osmosdr/lib/python3.9/site-packages` is not included. 

## What you expected to happen

1. GNU Radio would find the blocks if the default configuration pointed to `$(brew --prefix)/share/gnuradio/grc/blocks`.

2. The Python modules associated with these blocks should be loadable from the gnuradio Python environment:

    ```
    $ /usr/local/Cellar/gnuradio/3.8.2.0_3/libexec/venv/bin/python
    >>> import osmosdr  # should succeed
    ```

## Step-by-step reproduction instructions (by running `brew install` commands)

Install with `brew install gnuradio gr-osmosdr`

Start `gnuradio-companion` and note that it outputs:

```
Block paths:
	/usr/local/Cellar/gnuradio/3.8.2.0_3/share/gnuradio/grc/blocks
```

Also notice that there is no `OsmoSDR` folder on the right-hand list of blocks, because those definition files are not provided by the `gnuradio` formula directly.

----

<details>
 <summary>brew config output</summary>

```
HOMEBREW_VERSION: 2.5.11-151-g5d0c686
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5d0c6864e9067f63f7f0d4e40b2ffc6db8ad49cb
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff6837d72c9db03b79d4749fa9d767a26b8605b5
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.qDl49TWDmO/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 11.0.2, 9.0.4, 1.8.0_162
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11
```
</details>

**Comment by rgov** [comment]
I could submit a patch for this with some guidance. I mainly don't know how Homebrew expects to handle the `gnuradio` virtual environment being extended to find Python packages from other kegs.

**Comment by SMillerDev** [comment]
It doesn't. Kegs are intentionally kept separate. Unless the tool has a way to add blocks locations at runtime I don't think there is a way to do this with homebrew.
