### ISSUE TITLE
Formulae without head spec, while they have the own Github repository

### ISSUE THREAD

**Issue by equal-l2** [Homebrew/homebrew-core#6540]
The following formulae don't have head spec, while their description says that they have the own repository on Github.

I will make PR for each formula when I have time, but I would greatly appreciate anyone's help.

- [ ] aces_container
- [ ] acmetool
- [x] admesh
- [ ] adplug
- [ ] advancecomp
- [ ] afflib
- [ ] amazon-ecs-cli
- [ ] ammonite-repl
- [ ] ansible-cmdb
- [ ] apache-brooklyn-cli
- [ ] ape
- [ ] apktool
- [ ] archi-steam-farm
- [ ] aria2
- [ ] arping
- [ ] artifactory-cli-go
- [ ] arx
- [ ] atdtool
- [ ] atf
- [ ] ats2-postiats
- [ ] aurora-cli
- [ ] aws-apigateway-importer
- [ ] aws-keychain
- [ ] b2-tools
- [ ] b2sum
- [ ] bagit
- [ ] bde
- [ ] beanstalkd
- [ ] bee
- [ ] betty
- [ ] bib-tool
- [ ] bitrise
- [ ] blackbox
- [ ] blitzwave
- [ ] boot-clj
- [ ] borg
- [ ] brew-pip
- [ ] brightness
- [ ] btpd
- [ ] buku
- [ ] burl
- [ ] cadubi
- [ ] cake
- [ ] calabash
- [ ] ccat
- [ ] cconv
- [ ] certstrap
- [ ] cf4ocl
- [ ] cgal
- [ ] chaiscript
- [ ] charm-tools
- [ ] charm
- [ ] choose-gui
- [ ] clens
- [ ] cless
- [ ] cli53
- [ ] clipper
- [ ] cmark
- [ ] cocoapods
- [ ] coda-cli
- [ ] codequery
- [ ] colortail
- [ ] confuse
- [ ] contacts
- [ ] convox
- [ ] corelocationcli
- [ ] cosi
- [ ] couchdb-lucene
- [ ] cowsay
- [ ] cpp-netlib
- [ ] cssembed
- [ ] csvprintf
- [ ] ctail
- [ ] ctl
- [ ] cucumber-cpp
- [ ] curlpp
- [ ] cxxtest
- [ ] daemonize
- [ ] dasht
- [ ] ddate
- [ ] deis
- [ ] deisctl
- [ ] desk
- [ ] diff-pdf
- [ ] ditaa
- [ ] dnstwist
- [ ] docker-clean
- [ ] docker-gen
- [ ] docker-machine-nfs
- [ ] dockutil
- [ ] dovecot
- [ ] drip
- [ ] dropbox-uploader
- [ ] dshb
- [ ] dssim
- [ ] dvm
- [ ] dynamips
- [ ] elixirscript
- [ ] elm
- [ ] emp
- [ ] ent
- [ ] envv
- [ ] eot-utils
- [ ] epubcheck
- [ ] eris
- [ ] es
- [ ] extract_url
- [ ] fail2ban
- [ ] fb-adb
- [ ] fcgiwrap
- [ ] fcitx-remote-for-osx
- [ ] fdk-aac-encoder
- [ ] fdupes
- [ ] feedgnuplot
- [ ] ffind
- [ ] finatra
- [ ] flex
- [ ] fmt
- [ ] format-udf
- [ ] fourstore
- [ ] freeling
- [ ] frege-repl
- [ ] frege
- [ ] fsw
- [ ] fswatch
- [ ] fwup
- [ ] g3log
- [ ] galen
- [ ] gcviewer
- [ ] gdub
- [ ] geckodriver
- [ ] get-flash-videos
- [ ] gflags
- [ ] ghc
- [ ] gibo
- [ ] gimme
- [ ] git-credential-manager
- [ ] git-fresh
- [ ] git-lfs
- [ ] git-number
- [ ] git-octopus
- [ ] git-open
- [ ] git-series
- [ ] git-test
- [ ] git-town
- [ ] git-when-merged
- [ ] giter8
- [ ] github-markdown-toc
- [ ] gitless
- [ ] gitversion
- [ ] glbinding
- [ ] glog
- [ ] glslang
- [ ] glyr
- [ ] gnuradio
- [ ] gofabric8
- [ ] google-sparsehash
- [ ] gost
- [ ] gpm
- [ ] grails
- [ ] grip
- [ ] grt
- [ ] gumbo-parser
- [ ] gvp
- [ ] gws
- [ ] h2o
- [ ] hadolint
- [ ] hardlink-osx
- [ ] hashpump
- [ ] hayai
- [ ] hbase
- [ ] hebcal
- [ ] henplus
- [ ] hesiod
- [ ] hexcurse
- [ ] hoedown
- [ ] honcho
- [ ] htop-osx
- [ ] http-parser
- [ ] httpstat
- [ ] hunspell
- [ ] hyperscan
- [ ] icdiff
- [ ] ice
- [ ] icecream
- [ ] ievms
- [ ] imapfilter
- [ ] infer
- [ ] ios-webkit-debug-proxy
- [ ] iproute2mac
- [ ] irods
- [ ] jfrog-cli-go
- [ ] jmxtrans
- [ ] john-jumbo
- [ ] jooby-bootstrap
- [ ] jpeg-archive
- [ ] jrnl
- [ ] jsmin
- [ ] json_spirit
- [ ] jsonnet
- [ ] jsonpp
- [ ] jsonschema2pojo
- [ ] jvmtop
- [ ] kafkacat
- [ ] karn
- [x] known_hosts
- [ ] kobalt
- [ ] kommit
- [ ] kotlin
- [ ] kyua
- [ ] lastfmfpclient
- [ ] leaps
- [ ] lego
- [ ] leveldb
- [ ] libbson
- [ ] libcec
- [ ] libcue
- [ ] libebur128
- [ ] libepoxy
- [ ] libfreefare
- [ ] libgadu
- [ ] libgraphqlparser
- [ ] libgroove
- [ ] libical
- [ ] libilbc
- [ ] liblastfm
- [ ] libltc
- [ ] libmusicbrainz
- [ ] libmwaw
- [ ] libnfs
- [ ] libphonenumber
- [ ] libpointing
- [ ] librsync
- [ ] libscrypt
- [ ] libsoundio
- [ ] libspectre
- [ ] libtess2
- [ ] libucl
- [ ] libvidstab
- [ ] libvoikko
- [ ] libwebm
- [ ] libxdg-basedir
- [ ] linkerd
- [ ] liquibase
- [ ] llnode
- [ ] loc
- [ ] logtalk
- [ ] lrdf
- [ ] lutok
- [ ] macosvpn
- [ ] mdbtools
- [ ] mdr
- [ ] mdxmini
- [ ] mergepbx
- [ ] metashell
- [ ] micropython
- [ ] minisat
- [ ] minisign
- [ ] miruo
- [ ] mkvalidator
- [ ] mkvtomp4
- [ ] mlogger
- [ ] mlt
- [ ] mlton
- [ ] mobiledevice
- [ ] modgit
- [ ] modman
- [ ] mon
- [ ] mongodb
- [ ] mongroup
- [ ] mono
- [ ] mosml
- [ ] mpdviz
- [ ] mr
- [ ] mspdebug
- [ ] mstch
- [ ] mysql-search-replace
- [ ] nbimg
- [ ] ndpi
- [ ] nesc
- [ ] nethogs
- [ ] nfdump
- [ ] no-more-secrets
- [ ] noti
- [ ] nu
- [ ] nyancat
- [ ] odo
- [ ] odt2txt
- [ ] onetime
- [ ] oniguruma
- [ ] openslide
- [ ] opentsdb
- [ ] osm-pbf
- [ ] osquery
- [ ] osrm-backend
- [ ] pacapt
- [ ] packer
- [ ] paket
- [ ] partio
- [ ] pbrt
- [ ] pdf2json
- [ ] pdf2svg
- [ ] pdftoedn
- [ ] pdnsrec
- [ ] pegtl
- [ ] pex
- [ ] pgformatter
- [ ] pgtoolkit
- [ ] pick
- [ ] picocom
- [ ] pillar
- [ ] pk
- [ ] pkgdiff
- [ ] plowshare
- [ ] plustache
- [ ] pmd
- [ ] pmdmini
- [ ] pngpaste
- [ ] points2grid
- [ ] ponyc
- [ ] ponysay
- [ ] poster
- [ ] pre-commit
- [ ] prettyping
- [ ] prometheus
- [ ] protobuf-c
- [ ] protobuf-swift
- [ ] psql2csv
- [ ] ptex
- [ ] pugixml
- [ ] pwntools
- [ ] pybind11
- [ ] qpm
- [ ] qxmpp
- [ ] rancher-cli
- [ ] rancher-compose
- [ ] rbenv-communal-gems
- [ ] rbenv-use
- [ ] rbenv-whatis
- [ ] rclone
- [ ] recode
- [ ] redir
- [ ] redo
- [ ] redpen
- [ ] redsocks
- [ ] rem
- [ ] repl
- [ ] rethinkdb
- [ ] rgxg
- [ ] rhino
- [ ] ringojs
- [ ] rmlint
- [ ] rocksdb
- [ ] rolldice
- [ ] rswift
- [ ] rtmidi
- [ ] runcocoa
- [ ] scala
- [ ] scmpuff
- [ ] scriptcs
- [ ] sec
- [ ] seexpr
- [ ] selecta
- [ ] setweblocthumb
- [ ] sfcgal
- [ ] sflowtool
- [ ] shellinabox
- [ ] shml
- [ ] shocco
- [ ] sift
- [ ] sipp
- [ ] skinny
- [ ] slackcat
- [ ] slurm
- [ ] sngrep
- [ ] spark
- [ ] sparkey
- [ ] spdylay
- [ ] sqtop
- [ ] sshtrix
- [ ] ssllabs-scan
- [ ] st
- [ ] stdman
- [ ] stlviewer
- [ ] stout
- [ ] supervisor
- [ ] syntaxerl
- [ ] sysdig
- [ ] tailor
- [ ] tcpkali
- [ ] tcpreplay
- [ ] tcptraceroute
- [ ] tcptunnel
- [ ] td
- [ ] textql
- [ ] tgui
- [ ] tidy-html5
- [ ] tidyp
- [ ] tiff2png
- [ ] tinyproxy
- [ ] tippecanoe
- [ ] tlassemble
- [ ] tmux-cssh
- [ ] tnef
- [ ] todolist
- [ ] topgit
- [ ] trace2html
- [ ] traildb
- [ ] transmission
- [ ] trash
- [ ] tutum
- [ ] twtxt
- [ ] uberftp
- [ ] ubertooth
- [ ] unibilium
- [ ] uptimed
- [ ] urbit
- [ ] utf8proc
- [ ] v8
- [ ] vassh
- [ ] vavrdiasm
- [ ] vc4asm
- [ ] vcsh
- [ ] vegeta
- [ ] vera++
- [ ] vifm
- [ ] voldemort
- [ ] voms
- [ ] wakeonlan
- [ ] waon
- [ ] webdis
- [ ] webkit2png
- [ ] websocketd
- [ ] wifi-password
- [ ] wiggle
- [ ] wiki
- [ ] wiredtiger
- [ ] xar-mackyle
- [ ] xdelta
- [ ] xxhash
- [ ] yadm
- [ ] yajl
- [ ] yaml-cpp
- [ ] yank
- [ ] yuicompressor
- [ ] zbackup
- [ ] zero-install
- [ ] zmqpp
- [ ] znapzend
- [ ] zorba
- [ ] zsh-autosuggestions
- [ ] zsh-git-prompt
- [ ] zsh-history-substring-search
- [ ] zsh-navigation-tools
- [ ] zstd

**Comment by bfontaine** [comment]
Good idea! I just made one for `known_hosts` (#6541).

**Comment by ilovezfs** [comment]
I'd actually prefer we absolutely *not* do this. In many cases it's deliberate that we do not have a head spec, and do not want to support one.

**Comment by zmwangx** [comment]
Compiling head is often tricky, and it's not a good user experience anyway (both in terms of upgrades and how easy head builds break) so I personally wouldn't recommend head spec for day to day use. From my experience they're usually reserved for debugging purposes. Therefore, I think it's a bad idea to blindly add them. Instead, add them one at a time, when the need is there.

**Comment by MikeMcQuaid** [comment]
Agreed with above. Add them only when a user wants to use them.
