### ISSUE TITLE
`borgbackup` inappropriately deprecated

### ISSUE THREAD

**Issue by ahesford** [Homebrew/homebrew-core#65525]
The formula for `borgbackup` declares a deprecation because it requires FUSE:

https://github.com/Homebrew/homebrew-core/blob/bb6902bbafc601020a0c7fae3a4a9018de48ba0f/Formula/borgbackup.rb#L23

However, according to upstream documentation, the preference is for packagers to list one of the Python FUSE packages as a requirement *if one is available*:

https://github.com/borgbackup/borg/blob/master/setup.py#L80-L83

Most of `borgbackup` will work perfectly fine without FUSE, and in fact the only part that requires FUSE is a user-facing convenience method for browsing backups. If FUSE will stop working with macOS, the right thing to do is stop requiring FUSE, not deprecate a useful package.

**Comment by bayandin** [comment]
Would you create a PR with formula undeprecation, removing fuse-related stuff a revision bump?

**Comment by fxcoudert** [comment]
I've removed the FUSE dependency

**Comment by ahesford** [comment]
Thanks, I have drastically reduced my use of macOS and don't really have a good homebrew testbed these days.
