### ISSUE TITLE
ninja doesn’t have a runtime python dependency

### ISSUE THREAD

**Issue by Optiligence** [Homebrew/homebrew-core#65552]
pretty sure this is missing a ` => :build`
https://github.com/Homebrew/homebrew-core/blob/7033053c7ee61010b4363dd3e09977735cbc1727/Formula/ninja.rb#L23
arch build script as reference
https://github.com/archlinux/svntogit-community/blob/e653a9a9d1412e201c93bcc1ca32c3da6c32123a/trunk/PKGBUILD#L14

**Comment by iMichka** [comment]
Some commands in the package need it though:
https://github.com/Homebrew/homebrew-core/pull/61585

So we decided to ship it.

**Comment by fxcoudert** [comment]
@iMichka I'm not sure, I'm looking at the current install and nothing depends on python

**Comment by iMichka** [comment]
Back then `ninja -t browse` would fail without Python. On Mac it would silently use system Python 2, but that one has been EOL since then.

Did ninja maybe change their code and removed the need for Python?

**Comment by fxcoudert** [comment]
So you're right it still has a python in a string inside the binary. Uncool.
But it can build without cmake, on the other hand :)
