### ISSUE TITLE
Manual not installed for youtube-dl

### ISSUE THREAD

**Issue by Nathaniel-Wu** [Homebrew/homebrew-core#65567]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Current `youtube-dl.rb` formulae doesn't install the manual or it fails to do so.
Tried to modify `youtube-dl.rb` to Install its manual but the standard way doesn't work.

## What happened (include command output)

`man.install Dir[libexec/"share/man/*"]` doesn't work, no symlink created
`man1.install libexec/"share/man/man1/youtube-dl.1"` doesn't work, no symlink created
`ln_sf libexec/"share/man/man1/youtube-dl.1", HOMEBREW_PREFIX/"share/man/man1"` works but it creates an absolute path symlink (not an issue, just mentioning)
It's probably because `man.install` was interfered by `virtualenv_install_with_resources`? I'm not familiar with homebrew code base.

<details>
  <summary>Command output</summary>
  <pre>

  

  </pre>
</details>

## What you expected to happen

`man1.install libexec/"share/man/man1/youtube-dl.1"` should create a symlink file `/usr/local/share/man/man1/youtube-dl.1 -> ../../../Cellar/youtube-dl/2020.11.21.1/libexec/share/man/man1/youtube-dl.1`

## Step-by-step reproduction instructions (by running `brew install` commands)

append `man1.install libexec/"share/man/man1/youtube-dl.1"` after `virtualenv_install_with_resources` on line 20 in `youtube-dl.rb`

**Comment by dtrodrigues** [comment]
Fixed now - https://github.com/Homebrew/homebrew-core/pull/65569
