### ISSUE TITLE
Flyway is failing to execute with different user

### ISSUE THREAD

**Issue by brunojcm** [Homebrew/homebrew-core#65576]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/f4c458fff995c3c7879a9ba98c14c63d

## What you were trying to do (and why)

Run flyway with a different user than the one managing homebrew.

## What happened (include command output)

Permission denied while trying to execute the binary.

<details>
  <summary>Command output</summary>
  <pre>

$ flyway
/usr/local/bin/flyway: line 2: /usr/local/Cellar/flyway/7.2.1/libexec/flyway: Permission denied
/usr/local/bin/flyway: line 2: exec: /usr/local/Cellar/flyway/7.2.1/libexec/flyway: cannot execute: Undefined error: 0

  </pre>
</details>

## What you expected to happen

Flyway should run without issues.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install flyway
su - any_other_user
flyway -v
```

## Workaround
```
sudo chmod g+x /usr/local/Cellar/flyway/7.2.1/libexec/flyway
```

**Comment by jonchang** [comment]
Can you please [open a pull request](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) to make this change? Thanks!
