### ISSUE TITLE
Wireshark fails to fully install

### ISSUE THREAD

**Issue by nschombu** [Homebrew/homebrew-core#6562]
After running "brew install wireshark" the installation process takes place like normal but when I try to find wireshark in my applications it does not exist.  The /usr/local data is present; just the application file does not exist.  Tried rebooting and all troubleshooting tips with no success.

**Comment by MikeMcQuaid** [comment]
Wireshark's GUI is not installed by default as Homebrew does not support GUI applications well. `brew cask install wireshark` will provide the GUI.
