### ISSUE TITLE
dylibbundler is missing an up to date release source

### ISSUE THREAD

**Issue by jjeising** [Homebrew/homebrew-core#6564]
This release of [macdylibbundler](https://github.com/auriamg/macdylibbundler) referenced in [dylibbundler.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dylibbundler.rb) was published 2013-11-06. Since then the upstream repository contains multiple bug fixes and there might be even [further issues](https://github.com/chearon/macdylibbundler/commit/ed632990f8e1eedef2056dfa532abc3f6b779dec) reducing the usefulness of the release. 

There are currently no formulas depending on this formula.
```
$ brew update
Already up-to-date.
$ brew uses dylibbundler
$
```

**Comment by ilovezfs** [comment]
If you can convince upstream to create a new tag, we can look at putting out a new release.
