### ISSUE TITLE
Would it be possible to not include netcdf-fortran in netcdf formula but have its own formula? 

### ISSUE THREAD

**Issue by mcuntz** [Homebrew/homebrew-core#65654]
# Bug report

Checklist and brew config/doctor results are below.

The formula for netcdf automatically installs netcdf-c, netcdf-c++, and netcdf-fortran, which are three separate distributions. The latter two (C++ and Fortran) depend on the C-version, though. It is not possible to install the C-version only with the current netcdf formula.

This is problematic if you are using several Fortran compilers. Fortran uses .mod files that have the exact same purpose as the .h files in C. But these .mod files are produced by the compilers during compile time and they are not standardised. This means that different compilers use different formats for the .mod files. .mod files produced with GNU's gfortran cannot be used by Intel's ifort, for example.
This is why one has to install netcdf-fortran for Intel separately. 

The current netcdf formula installs netcdf.mod, amongst others, produced with gfortran in /usr/local/include (/usr/local/Cellar/netcdf/4.7.4_1/include/ if unlinked) together with the C .h files. The same is true with the libraries libnetcdff.* together with libnetcdf.* (note the extra f on the first lib).

The intel compiler hence fails to install netcdf-fortran because it becomes confused by the different libraries, i.e. the gfortran version and the one it is currently building. The library compiles but running test programs fails.

This happens if I just leave netcdf in /usr/local/lib (and include) and also if I brew unlink netcdf, because then I have to tell the Intel compiler the location of the C-version of netcdf and it finds the same gfortran Fortran files as before.

The solution would be to have netcdf-fortran as its own formula. On my system:
```
brew deps --installed | grep netcdf
cdo: gcc hdf5 isl jpeg libmpc libpng mpfr netcdf proj szip
eccodes: gcc hdf5 isl jpeg libmpc libpng mpfr netcdf szip
gdal: cairo cfitsio epsilon expat fontconfig freetype freexl gcc gdbm geos gettext giflib glib hdf5 isl jpeg json-c libdap libffi libgeotiff libmpc libpng libtool libxml2 little-cms2 lzo mpfr netcdf nspr numpy openjpeg openssl@1.1 pcre pixman poppler popt proj qt readline sqlite szip unixodbc webp xerces-c xz zstd
nco: antlr@2 gcc gsl hdf5 isl libmpc mpfr netcdf szip texinfo udunits
ncview: gcc hdf5 isl libmpc libpng mpfr netcdf szip udunits
netcdf: gcc hdf5 isl libmpc mpfr szip
pcl: boost cminpack eigen flann fontconfig freetype gcc gdbm glew hdf5 icu4c isl jpeg libmpc libomp libpcap libpng libusb mpfr netcdf openssl@1.1 pyqt qhull qt readline sip sqlite szip vtk@8.2 xz
vtk@8.2: boost fontconfig freetype gcc gdbm hdf5 icu4c isl jpeg libmpc libpng mpfr netcdf openssl@1.1 pyqt qt readline sip sqlite szip xz
```
None of the above packages need the fortran version of netcdf (I checked that). But I do not have an overview of other packages on homebrew. They would need to be updated to depend on netcdf and netcdf-fortran then.

Issue Checklist. Please note that netcdf is currently unlinked on my system because I tried to get it out of the way for ifort.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
> brew gist-logs netcdf
Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```
I have the version 12.2 installed. There is only the beta version of 12.3 available at the Apple developper site.

```
> brew config
HOMEBREW_VERSION: 2.5.11-214-g918fbcc
ORIGIN: https://github.com/Homebrew/brew
HEAD: 918fbcc26317deb4e575e7791504c48adb3d5a58
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: deda5a05551ab74d5313af112d3bb2054f9b6af8
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.4Qc2hlzWHC/org.macosforge.xquartz:0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 10.15.7-x86_64
CLT: 1103.0.32.62
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11
```

```
> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  vtk@8.2

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/cuntz/.pyenv/shims/python2-config
  /Users/cuntz/.pyenv/shims/python3.7-config
  /Users/cuntz/.pyenv/shims/python2.7-config
  /Users/cuntz/.pyenv/shims/python3.7m-config
  /Users/cuntz/.pyenv/shims/python-config
  /Users/cuntz/.pyenv/shims/python3-config
  /Users/cuntz/.pyenv/shims/ncursesw6-config
  /Users/cuntz/.pyenv/shims/python3.8-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  netcdf
```

**Comment by carlocab** [comment]
These are the formulae that currently depend on netcdf:
```
❯ brew uses --include-build netcdf
cdo                   gdal                  gmt@5                 nco                   petsc                 vtk
eccodes               gmt                   libbi                 ncview                petsc-complex         vtk@8.2
```
Do any of them depend on netcdf-fortran? (I know you have most of them installed and have said those do not.)

**Comment by SMillerDev** [comment]
Anything is possible, but homebrew doesn't take feature requests as issues. If you want something to change you'll have to make a pull request with these changes.

**Comment by mcuntz** [comment]
I checked all the formulae that depend on netcdf as given by carlocab (brew uses --include-build netcdf). None uses the Fortran library of netcdf.
I hence see this not as a feature request but as a real issue. Something unused is installed that floods my namespace with unnecessary "junk" that blocks essential functioning.

I can try to split the netcdf formula in two, netcdf and netcdf-fortran. I would do the netcdf-fortran keg_only to avoid flooding of the /usr/local namespace. I will try following https://docs.brew.sh/Formula-Cookbook.
I have never done this and it would probably need some fine-tuning from an experienced developper. It would also be very advantageous if the person who maintains the netcdf formula, would maintain also the netcdf-formula because both are developed  in parallel. This means if one bumps up the netcdf-c version, one should also look for new versions of netcdf-fortran.

**Comment by carlocab** [comment]
I am sympathetic with your position that this is a bug and not a feature request. However, I am not a Homebrew maintainer, so my opinion doesn't really carry a lot of weight on this issue, unfortunately.

I had a look at the netcdf formula and disentangling it looks tricky. However, feel free to tag me in your PR if you need help, and I'll do my best. A few things to add:

1. I'm not sure that is the right use of `keg_only`, but I could be wrong. My understanding is that this is meant for formulae that shadow something that's already provided by macOS.
2. I don't think there is a person assigned to maintaining the netcdf formula (not formally, at least). It would be good if you could chip in with the maintenance of the relevant formulae going forward.

**Comment by gromgit** [comment]
Also not a maintainer, but I have opinions of my own.

> However, I am not a Homebrew maintainer, so my opinion doesn't really carry a lot of weight on this issue, unfortunately.

Lots of folks have opinions, and they post them as issues, but in the end, someone's gotta do the work. What really makes maintainers sit up and take notice are PRs, that can be reviewed, improved...and sometimes rejected.

> I'm not sure that is the right use of `keg_only`, but I could be wrong. My understanding is that this is meant for formulae that shadow something that's already provided by macOS.

I think it's more of a generic tool for whenever conflicts are expected, like older versions of the same formula (since they usually install files with the same names) or OS shadowing, as you mentioned. If `netcdf-fortran` can't be installed alongside `netcdf` or any other formula, `keg_only` can be considered...or `conflicts_with`, depending on the situation.

> I don't think there is a person assigned to maintaining the netcdf formula (not formally, at least--I know other package managers function differently).

Yes, Homebrew formulae are _entirely_ user-driven, with Homebrew maintainers stepping in only if a void needs filling. This means that over time, as more users complain about formula issues but nobody (including the original submitter, who may be long gone) PRs any solutions, the maintainers are left with the unenviable task of fixing something they have no domain knowledge about. Many restrictions that Homebrew users grumble about actually make this burden manageable in the long term.
