### ISSUE TITLE
Also link old python version frameworks into `/usr/local/Frameworks/Python.framework/Versions`

### ISSUE THREAD

**Issue by itsayellow** [Homebrew/homebrew-core#65711]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://gist.github.com/itsayellow/5da645767f766e907106fc3b6e9bc87c

## What you were trying to do (and why)

Macvim is still using the Framework for Python 3.8.  Until macvim development can catch up with Python3.9 being the hombrew default, I installed `brew install python@3.8` in order for python support in macvim to be operational.  Unfortunately Macvim expects to see the directory `/usr/local/Frameworks/Python.framework/Versions/3.8` which is not installed as a symlink for the non-default Homebrew python version.

This is a recurring problem every time the default python in homebrew is upgraded and removes the link in `/usr/local/Frameworks/Python.framework/Versions` for the previous version.

See https://github.com/macvim-dev/macvim/issues/1116

## What happened (include command output)

`python@3.8` installed fine, but did not install a symlink to its Framework at `/usr/local/Frameworks/Python.framework/Versions/3.8`

<details>
  <summary>Command output</summary>
  <pre>
> brew install python@3.8                      
==> Downloading https://homebrew.bintray.com/bottles/python%403.8-3.8.6_2.catali
Already downloaded: /Users/mclapp/Library/Caches/Homebrew/downloads/98404cfdcceb6aff0ee45f5295937472fd0be2bafe873000bcc7c31bacc3b7ac--python@3.8-3.8.6_2.catalina.bottle.tar.gz
==> Pouring python@3.8-3.8.6_2.catalina.bottle.tar.gz
==> /usr/local/Cellar/python@3.8/3.8.6_2/bin/python3 -s setup.py --no-user-cfg i
==> /usr/local/Cellar/python@3.8/3.8.6_2/bin/python3 -s setup.py --no-user-cfg i
==> /usr/local/Cellar/python@3.8/3.8.6_2/bin/python3 -s setup.py --no-user-cfg i
==> Caveats
Python has been installed as
  /usr/local/opt/python@3.8/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.8/libexec/bin

You can install Python packages with
  /usr/local/opt/python@3.8/bin/pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.8 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.8 first in your PATH run:
  echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> ~/.zshrc

For compilers to find python@3.8 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.8/lib"

For pkg-config to find python@3.8 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/python@3.8/3.8.6_2: 4,329 files, 69.4MB
>
  </pre>
</details>

## What you expected to happen

It would be nice if `/usr/local/Frameworks/Python.framework/Versions/3.8` was automatically linked on install of `python@3.8`, or if there was an option for the formula on install (something like `--with-framework`) that would allow that link to be installed with a non-default Homebrew python version install.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install python@3.8
ls -l /usr/local/Frameworks/Python.framework/Versions
```
Would like to see in the output of `ls -l`:
```
total 0
lrwxr-xr-x  1 mclapp  admin  75 Nov 26 12:27 3.8@ -> ../../../Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8
lrwxr-xr-x  1 mclapp  admin  75 Nov 22 19:43 3.9@ -> ../../../Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9
lrwxr-xr-x  1 mclapp  admin  79 Nov 22 19:43 Current@ -> ../../../Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/Current
```

**Comment by MikeMcQuaid** [comment]
> python@3.8 is keg-only, which means it was not symlinked into /usr/local, because this is an alternate version of another formula.

Does `brew link python@3.8` link it as desired or not?

**Comment by fxcoudert** [comment]
> Macvim is still using the Framework for Python 3.8

brew's build of macvim definitely links against python 3.9. Are you talking about another macvim build?

**Comment by itsayellow** [comment]
> > python@3.8 is keg-only, which means it was not symlinked into /usr/local, because this is an alternate version of another formula.
> 
> Does `brew link python@3.8` link it as desired or not?

Just tried it, and no it does not link into `/usr/local/Frameworks/Python.framework/Versions`

**Comment by itsayellow** [comment]
> > Macvim is still using the Framework for Python 3.8
> 
> brew's build of macvim definitely links against python 3.9. Are you talking about another macvim build?

Yes, different macvim build.  All of the following do not link to python 3.9 and are still python 3.8:
* Macvim downloaded from https://github.com/macvim-dev/macvim/releases
* Macvim auto-updated from within macvim
* `brew cask install macvim`

**Comment by fxcoudert** [comment]
If builds external to Homebrew expect Python in specific places, they should distribute this Python framework themselves, or give clear instructions on how to install it, or (if they want to rely on externally-installed Homebrew) use whatever is the latest version we ship.

I don't think this is a Homebrew bug, really.

**Comment by itsayellow** [comment]
I guess I considered this as a polite "feature request", but since there wasn't a category for that, I submitted what is called a bug report.

To me this at least makes sense, if the recent python is linked into `/usr/local/Frameworks/Python.framework/Versions` with both its version number and `Current`, it couldn't hurt to link other pythons that are installed to their respective version number.

**Comment by itsayellow** [comment]
And also `brew cask install macvim` isn't quite "external to Homebrew".

**Comment by SMillerDev** [comment]
> And also brew cask install macvim isn't quite "external to Homebrew".

Casks are just a convenient way to run upstream installers. The settings for where to find Python are definitely external to homebrew here.

**Comment by fxcoudert** [comment]
> I guess I considered this as a polite "feature request"

And that's why I haven't closed it. I understand it could possibly be a feature, although it's maybe limited in its use.
In any case, I'd consider reporting it to macvim since they have better ways to fix it.

**Comment by itsayellow** [comment]
> And that's why I haven't closed it. I understand it could possibly be a feature, although it's maybe limited in its use.
> In any case, I'd consider reporting it to macvim since they have better ways to fix it.

It's always reported to macvim (I did this time too).  It's just that there's a gap between when when the old python version link is removed until when macvim can catch up and support the new version.

My main thought is, I don't know why any python version *wouldn't* link their framework into their version number of `/usr/local/Frameworks/Python.framework/Versions`.  It seems like it should just be part of the install.  You just need to make sure you don't clobber the `Current` link if you're not Homebrew's default python.

**Comment by itsayellow** [comment]
Also, from a user standpoint it always confused me that there is both a `brew macvim` and a `brew cask macvim`.  In general for GUI apps I always choose the `cask` version because it installs it like any other mac application to `/Applications`.  When I install with `brew macvim` then the app ends up buried in the `Cellar` :)
