### ISSUE TITLE
pkg-config still breaking builds on llvm-project

### ISSUE THREAD

**Issue by chadbrewbaker** [Homebrew/homebrew-core#65773]
pkg-config is still breaking builds on llvm-project. Not my place to judge if pkg-config or llvm-project is doing something it shouldn't.

# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] ran `brew update` and can still reproduce the problem?
- [ NA] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [NA ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [NA ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```bash
brew install pkg-config
git clone https://github.com/llvm/llvm-project
cd llvm-project
mkdir build; cd build;
cmake ../llvm -DCMAKE_BUILD_TYPE=Release
make -j8
```

## What happened (include command output)

Errored out just like https://forums.swift.org/t/is-anyone-else-getting-this-error-when-building-the-compiler-from-master-on-macos/36113

<details>
  <summary>Command output</summary>
  <pre>

  error: no member named 'isless' in the global namespace

  </pre>
</details>

## What you expected to happen

No errors.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install pkg-config
git clone https://github.com/llvm/llvm-project
cd llvm-project
mkdir build; cd build;
cmake ../llvm -DCMAKE_BUILD_TYPE=Release
make -j8
```

**Comment by carlocab** [comment]
Troublesome. These may be of use:

https://github.com/apple/swift/pull/32436

**Comment by jonchang** [comment]
> [ NA] ran brew doctor, fixed all issues and can still reproduce the problem?
> [NA ] ran brew gist-logs <formula> (where <formula> is the name of the formula that failed) and included the output link?
> [NA ] if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

Please provide `brew config` and `brew doctor`, as you were requested to do in the last issue you opened https://github.com/Homebrew/homebrew-core/issues/65772. If you edit them into your post this can be re-opened. 

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

**Comment by carlocab** [comment]
Can't reproduce. Followed instructions to reproduce exactly, except for the last step, where I ran `make -j2`.
