### ISSUE TITLE
[PHP] Version 7.4 not available after 8.0 release

### ISSUE THREAD

**Issue by nedex** [Homebrew/homebrew-core#65785]
### A detailed description of the proposed feature

Add a PHP@7.4 formula.

### The motivation for the feature

Following the PHP 8.0 release, the 7.4 version is no longer available (not directly).
So upgrading with `brew upgrade` will cause the current PHP 7.4 installation to get upgraded to 8.0
It should be achieved the same result as for older PHP versions.

### How the feature would be relevant to at least 90% of Homebrew users

Many people are running their projects on 7.4 and want to avoid 8.0 major/breaking changes.

### What alternatives to the feature have been considered

(None?)

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Adding-Software-to-Homebrew

https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aopen+php
