### ISSUE TITLE
PHP@7.4 does not install pecl

### ISSUE THREAD

**Issue by jrwiegand** [Homebrew/homebrew-core#65794]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Use `pecl` with php@7.4 formula. I use pecl to install additional extensions on php.

## What happened (include command output)

The command is not available in my path. However, when installing php latest (8.0) pecl is available without issue.

<details>
  <summary>Command output</summary>
  <pre>
$ pecl
zsh: command not found: pecl
  </pre>
</details>

## What you expected to happen

I expect the `pecl` command to be available on my system after installing `php@7.4`.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. brew install php@7.4
1. pecl

**Comment by fxcoudert** [comment]
Isn't `pecl` in `/usr/local/opt/php@7.4/bin`? brew gave you a message about that when you installed the versioned formula, I think.

**Comment by MikeMcQuaid** [comment]
```console
$ brew info php@7.4
....
php@7.4 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have php@7.4 first in your PATH run:
  echo 'export PATH="/usr/local/opt/php@7.4/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/php@7.4/sbin:$PATH"' >> ~/.zshrc
...

$ ls /usr/local/opt/php@7.4/bin/pecl
/usr/local/opt/php@7.4/bin/pecl
```

**Comment by jrwiegand** [comment]
Yes, it is I must have missed that.
Thanks for the quick response @MikeMcQuaid and @fxcoudert.
