### ISSUE TITLE
problems with clingo formula

### ISSUE THREAD

**Issue by rkaminsk** [Homebrew/homebrew-core#65792]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

There seem to be some issues with the clingo formula on homebrew. This can be seen inspecting the log of:
```
brew reinstall --build-from-source --verbose --debug clingo
```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
...
CMake Warning:
  Manually-specified variables were not used by the project:
    PYTHON_EXECUTABLE
...
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/lpconvert
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/clasp
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.3.0.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.3.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libclingo.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/include/clingo.hh
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/include/clingo.h
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoTargets.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoTargets-release.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoConfig.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/cmake/Clingo/ClingoConfigVersion.cmake
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.1.0.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.1.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/lib/libpyclingo.dylib
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/reify
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/gringo
-- Installing: /usr/local/Cellar/clingo/5.4.0_2/bin/clingo
-- Installing: /private/tmp/clingo-20201127-59348-gq8suv/clingo-5.4.0/.brew_home/Library/Python/3.9/lib/python/site-packages/clingo.cpython-39-darwin.so
...
  </pre>
</details>

## What you expected to happen

There are two problems.

First, there is the message that the variable `PYTHON_EXECUTABLE` is unused. If available, clingo uses cmake's `FindPython` module, which no longer uses this variable `PYTHON_EXECUTABLE`. It should be possible to fix this by using the variable `Python_EXECUTABLE`, instead.

The second bigger problem is that the clingo Python module is installed in the wrong location. I do not know where such a module should be installed, so I cannot tell how to fix this. In any case it is possible to specify the installation path using the `PYCLINGO_INSTALL_DIR` varibale.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew reinstall --build-from-source --verbose --debug clingo
```

**Comment by SMillerDev** [comment]
Please actually provide the information and don't just tick the boxes. This can be reopened once you do

**Comment by rkaminsk** [comment]
I was actually pointing to concrete problems in the formula. The above commands have nothing to do with the problem.

**Comment by rkaminsk** [comment]
I updated the logs. This was just meant to inform you that there are problems with the formula. I am the developer of clingo but not the maintainer of the formula. I can help with the cmake configuration or patches regarding clingo-specific issues.
