### ISSUE TITLE
Need to set MACOSX_DEPLOYMENT_TARGET correctly

### ISSUE THREAD

**Issue by jonmasters** [Homebrew/homebrew-core#65801]
python3.9.rb sets MACOSX_DEPLOYMENT_TARGET but does so incorrectly, truncating the value to a single number not a tuple, which causes the make to fail. This is preventing a "brew install python" from succeeding on Arm. As a trivial hack, I simply replaced the line in the recipe with a manual setting of "11.0" and not "11" (notice the lack of a decimal) that results from your existing logic.

**Comment by MikeMcQuaid** [comment]
Please fill in the issue template and we will consider reopening.
