### ISSUE TITLE
graph-tool expects cairomm version 1.0.1, incompatible with recently updated cairomm version 1.16.0

### ISSUE THREAD

**Issue by sourtin** [Homebrew/homebrew-core#65830]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
  <summary>Command output</summary>
<pre>
% brew config
HOMEBREW_VERSION: 2.5.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: af4143150da32097f751b1538a5b6f6958bb2175
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1c960f2925f20ae447e9a2cb038dd7c097ce9fe0
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
</pre>

<pre>
% brew dr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
released but not yet supported version.
</pre>
</details>

## What you were trying to do (and why)

I was trying to rerun a python script using graph-tool that worked yesterday. The only change was a brew upgrade in the interim.

## What happened (include command output)

Loading graph-tool in python leads to the following warning, and subsequent errors when trying to do things like `gt.sfdp_layout`:

```
% python3 -m graph_tool.all
/usr/local/lib/python3.9/site-packages/graph_tool/all.py:39: RuntimeWarning: Error importing draw module, proceeding nevertheless: dlopen(/usr/local/lib/python3.9/site-packages/graph_tool/draw/libgraph_tool_draw.so, 9): Library not loaded: /usr/local/opt/cairomm/lib/libcairomm-1.0.1.dylib
  Referenced from: /usr/local/lib/python3.9/site-packages/graph_tool/draw/libgraph_tool_draw.so
  Reason: image not found
  warnings.warn(msg, RuntimeWarning)
```

## What you expected to happen

graph-tool to load without warning or error.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
% brew install graph-tool
# ...will install cairomm as a dependency
% python3 -m graph_tool.all
```

**Comment by fxcoudert** [comment]
Fixed, thanks for reporting
