### ISSUE TITLE
brew install php fail

### ISSUE THREAD

**Issue by carlwangx** [Homebrew/homebrew-core#65853]
# Bug report
## What you were trying to do (and why)

```bash
brew install php
```

## What happened (include command output)

```
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set man_dir /usr/local/share/man system
Last 15 lines from /Users/carl/Library/Logs/Homebrew/php/post_install.09.pear:
2020-11-28 19:37:07 +0800

/usr/local/Cellar/php/8.0.0/bin/pear
config-set
man_dir
/usr/local/share/man
system

config-set (man_dir, /usr/local/share/man, system) failed, channel pecl.php.net
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall php`
```

## What you expected to happen

no error

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install php
```

**Comment by jonchang** [comment]
Please fill out the full issue template: https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.

Once you post the information here this issue can be re-opened.
