### ISSUE TITLE
install php8 error

### ISSUE THREAD

**Issue by carlwangx** [Homebrew/homebrew-core#65885]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```bash
brew install php
```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles/php-8.0.0.big_sur.bottle.tar.gz
Already downloaded: /Users/carl/Library/Caches/Homebrew/downloads/c68be16f66c58caa43aa4b4c138358e825de6c477b510178085fbce2e0e668ef--php-8.0.0.big_sur.bottle.tar.gz
==> Pouring php-8.0.0.big_sur.bottle.tar.gz
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set php_ini /usr/local/etc/php/8.0/php.ini system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set php_dir /usr/local/share/pear system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set doc_dir /usr/local/share/pear/doc system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set ext_dir /usr/local/lib/php/pecl/20200930 system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set bin_dir /usr/local/opt/php/bin system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set data_dir /usr/local/share/pear/data system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set cfg_dir /usr/local/share/pear/cfg system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set www_dir /usr/local/share/pear/htdocs system
==> /usr/local/Cellar/php/8.0.0/bin/pear config-set man_dir /usr/local/share/man system
Last 15 lines from /Users/carl/Library/Logs/Homebrew/php/post_install.09.pear:
2020-11-29 22:04:00 +0800

/usr/local/Cellar/php/8.0.0/bin/pear
config-set
man_dir
/usr/local/share/man
system

config-set (man_dir, /usr/local/share/man, system) failed, channel pecl.php.net
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall php`
  </pre>
</details>

## What you expected to happen

no error

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install php
```

**Comment by carlocab** [comment]
https://github.com/Homebrew/homebrew-core/issues/65853#issuecomment-735223353

**Comment by SMillerDev** [comment]
You haven't actually posted all the data it requested in the form.
