### ISSUE TITLE
mobile-shell (mosh) fails with libprotobuf link error on Mojave

### ISSUE THREAD

**Issue by danielb2** [Homebrew/homebrew-core#65899]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

use mosh to connect to a remote computer on osx mojave

## What happened (include command output)

it failed because of a missing lib

<details>
  <summary>mosh luffy</summary>
  <pre>
dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.24.dylib
  Referenced from: /usr/local/Cellar/mosh/1.3.2_12/bin/mosh-client
  Reason: image not found
Died at /usr/local/bin/mosh line 311.

 </pre>
</details>

## What you expected to happen

no failure

**Comment by fxcoudert** [comment]
Thanks for the report, this is a result of an issue with the protobuf update. You can fix it with `brew reinstall -s mosh`.
I have started a rebuild so the issue is fixed for everyone, as well: https://github.com/Homebrew/homebrew-core/pull/65901

**Comment by danielb2** [comment]
thank you for the fast response; that worked :)

**Comment by danielb2** [comment]
amazing how much I missed mosh just the two days I didn't have it ( I was too lazy to report this at first ). Having to login again over and over is such a chore 😅
