### ISSUE TITLE
watchman 4.9.0_5 "post-install step did not complete successfully"

### ISSUE THREAD

**Issue by jprokos** [Homebrew/homebrew-core#65916]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Trying to install `watchman` using `brew install`

## What happened (include command output)
I received a warning declaring that a post-install step did not complete successfully.
<details>
  <summary>Command output</summary>
  <pre>
admin$ brew install watchman
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from ef755182b to 9ee8cc97c.
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/cask-drivers).
==> Downloading https://homebrew.bintray.com/bottles/watchman-4.9.0_5.mojave.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/135eb0a8f098417a8e4d67bf8d732a19bad1932eee085497877e93982e91074
######################################################################## 100.0%
==> Pouring watchman-4.9.0_5.mojave.bottle.tar.gz
==> launchctl unload -F /Users/admin/Library/LaunchAgents/com.github.facebook.watchman.plist
Last 15 lines from /Users/admin/Library/Logs/Homebrew/watchman/post_install.01.launchctl:
2020-11-29 15:58:44 -0600

launchctl
unload
-F
/Users/admin/Library/LaunchAgents/com.github.facebook.watchman.plist

Could not find domain for 
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall watchman`
==> Summary
🍺  /usr/local/Cellar/watchman/4.9.0_5: 24 files, 2.1MB

admin$ brew postinstall watchman
==> Postinstalling watchman
==> launchctl unload -F /Users/admin/Library/LaunchAgents/com.github.facebook.watchman.plist
Last 15 lines from /Users/admin/Library/Logs/Homebrew/watchman/post_install.01.launchctl:
2020-11-29 16:01:00 -0600
launchctl
unload
-F
/Users/admin/Library/LaunchAgents/com.github.facebook.watchman.plist
Could not find domain for 
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall watchman`

admin$ brew doctor
Your system is ready to brew.

admin$ brew gist-logs watchman
Error: Calling `brew gist-logs` with a password is disabled! Use HOMEBREW_GITHUB_API_TOKEN instead.

admin$ brew config
HOMEBREW_VERSION: 2.5.12-277-g9ee8cc9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9ee8cc97c914461aca744b7b67d18599f10b57a5
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c95d6cb7dda7c81ed9849546d3fd6b7fa5033368
Core tap last commit: 50 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine", "--appdir=/Applications", "--fontdir=/Library/Fonts", "--qlplugindir=/Library/QuickLook", "--internet_plugindir=/Library/Internet Plug-Ins", "--prefpanedir=/L>", "--servicedir=/Library/Services"]
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 14.0.1, 14, 13, 12.0.2
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: 11.3.1

  </pre>
</details>

## What you expected to happen

I expected `brew install` to do a clean install of `watchman` without issues or give actionable explanations as to why it could not.

Also, The directions to "Use HOMEBREW_GITHUB_API_TOKEN instead" is confusing without actionable directions or at least a link to description. "Users are not developers" would be a great mindset for those writing directions. Thank you. Do you mean "Add HOMEBREW_GITHUB_API_TOKEN in your .bash_profile?

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install watchman`
`brew postinstall watchman`

**Comment by carlocab** [comment]
Could you try running:

    launchctl unload -F "$HOME/Library/LaunchAgents/com.github.facebook.watchman.plist"

Also, it would be useful to check `$HOME/Library/LaunchAgents` if it contains a file called `com.github.facebook.watchman.plist`, or indeed any files with `github` or `facebook` in its name.

Have you used `watchman` before? That's really only what the post-install step is trying to take care of.

**Comment by jprokos** [comment]
Howdy,

I have not used watchman before.

I did check launchAgents before adding this issue. There is no LaunchAgent for watchman so there was no way to unload it. I am not sure what could have prevented or blocked the creation of the `watchman` launch agent.

**Comment by carlocab** [comment]
Then I think you should be fine, and you need not worry about the postinstall step.

`HOMEBREW_GITHUB_API_TOKEN` is documented in `man brew`.

**Comment by jprokos** [comment]
Do I have to restart or log out and log in for the launch agent to be created?

**Comment by carlocab** [comment]
That I I'm not certain about; you'll have to refer to the docs: https://facebook.github.io/watchman/

All I know is that launch agents are not created at install time, and that launch agents from old versions have to be unloaded for the new ones to work.

My guess is that launch agents are created when you use it, since `watchman` can't know what instructions to give a launch agent until you tell it what to do.

**Comment by jprokos** [comment]
Thanks.
I know this is not directly related to watchman but I will ask here in case you have an answer

I did add `export HOMEBREW_GITHUB_API_TOKEN=quoted form of my token` to .bash_profile

I ran: `git config --system --unset credential.helper`
I ran: `brew gist-logs watchman`
received the same error as before. As far as I know I am not "Calling `brew gist-logs` with a password. And I have created a new gitbub personal API token and added it in .bash_profile.

**Comment by carlocab** [comment]
Sorry, that I don't know anything about. You may want to have a look at the docs for `gist-logs` and check for open issues at the brew repo.

Since your new questions are unrelated it's probably best if you close this issue, unless you have outstanding questions about the original issue.
