### ISSUE TITLE
Cannot clone or download this repo

### ISSUE THREAD

**Issue by Dinh-Ng** [Homebrew/homebrew-core#65931]
-- Using `brew update`: 

Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` exited with 128

-- Using download Zip:

Error 503 Backend fetch failed

**Comment by jonchang** [comment]
Please always use the issue template. This can be reopened if you fill in the requested information: https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information.
