### ISSUE TITLE
Qt5: Request patch for QTBUG-51927

### ISSUE THREAD

**Issue by dagheyman** [Homebrew/homebrew-core#6593]
Would be great if the patch for QTBUG-51927 could be added to the qt5 formula.

Bug report:
https://bugreports.qt.io/browse/QTBUG-51927

Patch:
https://codereview.qt-project.org/#/c/170844/

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request (after checking no other open pull request does this already)? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by dagheyman** [comment]
I could try to do that. The actual patch should go [here](https://github.com/Homebrew/formula-patches) I suspect? So two PRs would be needed?
