### ISSUE TITLE
pkg-config cannot resolve 'pangomm-1.4' dependency

### ISSUE THREAD

**Issue by txe** [Homebrew/homebrew-core#65955]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to build `cherrytree` app (cmake/gtk3) but cmake with pkg_config cannot resolve `pangomm-1.4` dependency. It happened after the last `brew update/upgrade` (today after a long while), previously there was no such issue (the last 6 month). There is other user who complained about this issue.

## What happened (include command output)

The issue can be simplified and reproduced by the following commands:

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
pkg-config --libs pangomm-1.4
```
the result:
```
Package cairomm-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairomm-1.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'cairomm-1.0', required by 'pangomm-1.4', not found
```

I see that `PKG_CONFIG_PATH` contains `cairomm-1.16.pc`, there is no `cairomm-1.0.pc`

## What you expected to happen

For example it could be this (what I have on a linux machine)
```
-lpangomm-1.4 -lglibmm-2.4 -lcairomm-1.0 -lsigc-2.0 -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lcairo
```

**Comment by carlocab** [comment]
You're missing the output of `gist-logs`, `brew doctor` and `brew config`.

**Comment by txe** [comment]
Thanks you, `brew doctor` gave a warning
```
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cairomm@1.14
```

`brew link cairomm@1.14` fixed the issue.
