### ISSUE TITLE
Rakudo recipie doesn't bundle zef package manager

### ISSUE THREAD

**Issue by luolong** [Homebrew/homebrew-core#65995]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```bash
$ brew config
HOMEBREW_VERSION: 2.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d5e354cc2ff048bd7161d95b3fa7f91dc9dd081
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 88e61e0e6b6653b9728db1dde6fc7c81414c8c0d
Core tap last commit: 84 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1, 13.0.5, 11.0.9.1
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
```

```bash 
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

## What you were trying to do (and why)

I was trying to install `rakudo`

## What happened (include command output)

```
$ brew install rakudo
```

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://homebrew.bintray.com/bottles/nqp-2020.11.big_sur.bottle.tar.gz
Already downloaded: /Users/roland.tepp/Library/Caches/Homebrew/downloads/10bf595421a8f431322bf3146b07ca9220391e5339c6520409ef8b9fc947e7a3--nqp-2020.11.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/rakudo-2020.11.big_sur.bottle.tar.gz
Already downloaded: /Users/roland.tepp/Library/Caches/Homebrew/downloads/710f6389e555f0109d895fae61dac46d4d09f77b444e0726df221c25deef9157--rakudo-2020.11.big_sur.bottle.tar.gz
==> Installing dependencies for rakudo: nqp
==> Installing rakudo dependency: nqp
==> Pouring nqp-2020.11.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/nqp/2020.11: 19 files, 4.1MB
==> Installing rakudo
==> Pouring rakudo-2020.11.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/rakudo/2020.11: 114 files, 39.3MB
  </pre>
</details>

## What you expected to happen

I expected rakudo recipie to install officially endorsed rakudo `zef` package manager as well as rakudo.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
$ brew install rakudo
...
$ zef --help
fish: Unknown command: zef
```

**Comment by SMillerDev** [comment]
Please make a [pull request for this](https://docs.brew.sh/Updating-Software-in-Homebrew) since this is really more of a feature request than a bug.

**Comment by SeekingMeaning** [comment]
`rakudo-star` comes with `zef`
