### ISSUE TITLE
`podebug` from translate-toolkit is broken

### ISSUE THREAD

**Issue by youtux** [Homebrew/homebrew-core#66065]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
```
$ brew gist-logs translate-toolkit
Error: No logs.
```
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$ brew config
HOMEBREW_VERSION: 2.6.0-32-g41ea895
ORIGIN: https://github.com/Homebrew/brew
HEAD: 41ea89598ba5cc68c3b355d6411766e912a14801
Last commit: 7 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 743e404a62f38cb3ab6f579e8c632ab76a0f0e21
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jBniM80vdw/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_131
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2
XQuartz: 2.7.11 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/youtux/.pyenv/shims/python3.5m-config
  /Users/youtux/.pyenv/shims/python2-config
  /Users/youtux/.pyenv/shims/python3.4m-config
  /Users/youtux/.pyenv/shims/python3.6m-config
  /Users/youtux/.pyenv/shims/python3.7-config
  /Users/youtux/.pyenv/shims/python2.7-config
  /Users/youtux/.pyenv/shims/python3.7m-config
  /Users/youtux/.pyenv/shims/python3.9-config
  /Users/youtux/.pyenv/shims/python3.5-config
  /Users/youtux/.pyenv/shims/python-config
  /Users/youtux/.pyenv/shims/python3-config
  /Users/youtux/.pyenv/shims/python3.6-config
  /Users/youtux/.pyenv/shims/python3.8-config
  /Users/youtux/.pyenv/shims/python3.4-config
```

## What you were trying to do (and why)

I'm trying to run the `podebug` executable provided by the `translate-toolkit` formula.

## What happened (include command output)

The program fails with an import error:

<details>
  <summary>Command output</summary>
  <pre>

$ which podebug
/usr/local/bin/podebug

$ ls -lah =podebug
lrwxr-xr-x  1 youtux  admin    45B Dec  2 11:43 /usr/local/bin/podebug -> ../Cellar/translate-toolkit/3.2.0/bin/podebug

$ podebug -h
Traceback (most recent call last):
  File "/usr/local/bin/podebug", line 33, in <module>
    sys.exit(load_entry_point('translate-toolkit==3.2.0', 'console_scripts', 'podebug')())
  File "/usr/local/bin/podebug", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.0_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/Cellar/translate-toolkit/3.2.0/libexec/lib/python3.9/site-packages/translate/tools/podebug.py", line 29, in <module>
    from translate.convert import dtd2po
  File "/usr/local/Cellar/translate-toolkit/3.2.0/libexec/lib/python3.9/site-packages/translate/convert/dtd2po.py", line 29, in <module>
    from translate.storage import dtd, po
  File "/usr/local/Cellar/translate-toolkit/3.2.0/libexec/lib/python3.9/site-packages/translate/storage/dtd.py", line 89, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

  </pre>
</details>

## What you expected to happen

To see the help text of `podebug`, not an import error.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install translate-toolkit
podebug -h
```

**Comment by fxcoudert** [comment]
Thanks for the report, trying to fix in https://github.com/Homebrew/homebrew-core/pull/66066

**Comment by youtux** [comment]
Fixed, thank you again @fxcoudert !
