### ISSUE TITLE
man-db has issues with the groff provided by macOS

### ISSUE THREAD

**Issue by tyrak** [Homebrew/homebrew-core#66216]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I open a man page with man-db-2.9.3 and all the dashes (i.e. the character `U+002d HYPHEN-MINUS`) in it are replaced with `U+2010 HYPHEN` or `U+2212 MINUS SIGN`. This is annoying because these characters are not directly available as keys in a typical keyboard, making it harder to perform searches inside man pages with `/`.

## What happened (include command output)

<details>
  <summary>gman cp | grep -o -- - | wc -l</summary>
  <pre>0</pre>
</details>

## What you expected to happen

I expected the above command to output an number greater than 0.

Under linux (tried this with an up to date Debian Testing system and a Gentoo one) man-db-2.9.3 renders hyphens/dashes as `U+002d HYPHEN-MINUS`. The same thing happens with the builtin macOS man page viewer.

After some googling, I found [this thread](https://lists.nongnu.org/archive/html/man-db-devel/2020-01/msg00000.html) in the man-db-devel mailing list, where the debian maintainer of man-db indicated that the issue has to do with groff. After installing groff from brew, the issue was resolved for me. So I propose that groff is made a dependency of man-db in the man-db formula.

## Output of `brew config` and `brew doctor`

```
$ brew config
HOMEBREW_VERSION: 2.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d5e354cc2ff048bd7161d95b3fa7f91dc9dd081
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d598149ef188974f6bb9673d218817982950f2b4
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_275
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

**Comment by SMillerDev** [comment]
> So I propose that groff is made a dependency of man-db in the man-db formula.

Please make a pull request for this. It's very easy to do: https://docs.brew.sh/Updating-Software-in-Homebrew and homebrew doesn't allow feature requests as issues.
