### ISSUE TITLE
Bottling for ARM

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#66303]
This issue will server to gather bottling failures for ARM.

*Current blockers:*
- `brew`: https://github.com/Homebrew/brew/issues/9449
- ~`brew`: https://github.com/Homebrew/brew/issues/9434~
- ~workflow: https://github.com/Homebrew/homebrew-core/issues/66328~

**Comment by EpaL** [comment]
net-snmp fails to build on macOS ARM.

Issue #228 opened in net-snmp:

https://github.com/net-snmp/net-snmp/issues/228

**Comment by UMU618** [comment]
**rubberband xvid** fails to build on macOS ARM.

**Comment by carlocab** [comment]
Hi @EpaL, @UMU618, this is the wrong thread for that. I think you two are looking for https://github.com/Homebrew/brew/issues/7857.

**Comment by SMillerDev** [comment]
Homebrew/brew#9449 is actually fixed (so no longer blocking)

**Comment by fxcoudert** [comment]
@SMillerDev thanks, I forgot to keep this up to date. I'm going to close it for now

**Comment by chenrui333** [comment]
raise issue for [dark-mode](https://github.com/sindresorhus/dark-mode/issues/19)

**Comment by chenrui333** [comment]
vcpkg [arm build PR](#67791)
