### ISSUE TITLE
Illegal instructions on 12" MacBook; Probably TSX instructions

### ISSUE THREAD

**Issue by ncihnegn** [Homebrew/homebrew-core#66313]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

clang-tidy -std=c++2a xx.cpp may crash.

<details>
  <summary>Command output</summary>
  <pre>

  0.	Program arguments: /usr/local/bin/clang-tidy --fix --header-filter=inc/ --extra-arg-before=--driver-mode=g++ ../src/p3.cpp -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -I../inc -I_deps/doctest-src -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -fsanitize=address,undefined -std=c++2a -MD -MT CMakeFiles/p3.dir/src/p3.cpp.o -MF CMakeFiles/p3.dir/src/p3.cpp.o.d -o CMakeFiles/p3.dir/src/p3.cpp.o -c ../src/p3.cpp
1.	<eof> parser at end of file
2.	While analyzing stack:
	#0 Calling guess at line 16
	#1 Calling guessNumber at line ../src/p3.cpp:43:3 <Spelling=../src/p3.cpp:43:12>
	#2 Calling _DOCTEST_ANON_FUNC_12
3.	../src/p3.cpp:8:28: Error evaluating statement
4.	../src/p3.cpp:8:28: Error evaluating statement
0  libLLVM.dylib            0x0000000109fef4d5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 37
1  libLLVM.dylib            0x0000000109fef97c SignalHandler(int) + 200
2  libsystem_platform.dylib 0x00007fff20386d7d _sigtramp + 29
3  libsystem_platform.dylib 0x00007ffee8d419a0 _sigtramp + 18446744072780229696
4  libclang-cpp.dylib       0x0000000108b16472 (anonymous namespace)::SimpleSValBuilder::evalBinOpNN(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::NonLoc, clang::ento::NonLoc, clang::QualType) + 1316
5  libclang-cpp.dylib       0x0000000108b20daa clang::ento::SValBuilder::evalBinOp(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::SVal, clang::ento::SVal, clang::QualType) + 550
6  libclang-cpp.dylib       0x0000000108ac2bd8 clang::ento::ExprEngine::evalBinOp(llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>, clang::BinaryOperatorKind, clang::ento::SVal, clang::ento::SVal, clang::QualType) + 92
7  libclang-cpp.dylib       0x0000000108ac263b clang::ento::ExprEngine::VisitBinaryOperator(clang::BinaryOperator const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) + 2635
8  libclang-cpp.dylib       0x0000000108ab713b clang::ento::ExprEngine::Visit(clang::Stmt const*, clang::ento::ExplodedNode*, clang::ento::ExplodedNodeSet&) + 9013
9  libclang-cpp.dylib       0x0000000108ab32cf clang::ento::ExprEngine::ProcessStmt(clang::Stmt const*, clang::ento::ExplodedNode*) + 583
10 libclang-cpp.dylib       0x0000000108ab2fde clang::ento::ExprEngine::processCFGElement(clang::CFGElement, clang::ento::ExplodedNode*, unsigned int, clang::ento::NodeBuilderContext*) + 174
11 libclang-cpp.dylib       0x0000000108aa2754 clang::ento::CoreEngine::HandlePostStmt(clang::CFGBlock const*, unsigned int, clang::ento::ExplodedNode*) + 94
12 libclang-cpp.dylib       0x0000000108aa1d89 clang::ento::CoreEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int, llvm::IntrusiveRefCntPtr<clang::ento::ProgramState const>) + 1003
13 libclang-cpp.dylib       0x0000000108d24bd2 clang::ento::ExprEngine::ExecuteWorkList(clang::LocationContext const*, unsigned int) + 26
14 libclang-cpp.dylib       0x0000000108d249e0 (anonymous namespace)::AnalysisConsumer::HandleCode(clang::Decl*, unsigned int, clang::ento::ExprEngine::InliningModes, llvm::DenseSet<clang::Decl const*, llvm::DenseMapInfo<clang::Decl const*> >*) + 1180
15 libclang-cpp.dylib       0x0000000108d14244 (anonymous namespace)::AnalysisConsumer::HandleTranslationUnit(clang::ASTContext&) + 812
16 libclang-cpp.dylib       0x000000010894b62a clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) + 38
17 libclang-cpp.dylib       0x0000000107855710 clang::ParseAST(clang::Sema&, bool, bool) + 515
18 libclang-cpp.dylib       0x00000001089245d7 clang::FrontendAction::Execute() + 77
19 libclang-cpp.dylib       0x00000001088ee89e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 1322
20 libclang-cpp.dylib       0x0000000108a46da7 clang::tooling::FrontendActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 269
21 clang-tidy               0x0000000106ec196f clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef)::ActionFactory::runInvocation(std::__1::shared_ptr<clang::CompilerInvocation>, clang::FileManager*, std::__1::shared_ptr<clang::PCHContainerOperations>, clang::DiagnosticConsumer*) + 91
22 libclang-cpp.dylib       0x0000000108a46b96 clang::tooling::ToolInvocation::runInvocation(char const*, clang::driver::Compilation*, std::__1::shared_ptr<clang::CompilerInvocation>, std::__1::shared_ptr<clang::PCHContainerOperations>) + 192
23 libclang-cpp.dylib       0x0000000108a45f60 clang::tooling::ToolInvocation::run() + 2244
24 libclang-cpp.dylib       0x0000000108a47f7b clang::tooling::ClangTool::run(clang::tooling::ToolAction*) + 2287
25 clang-tidy               0x0000000106ebe5ea clang::tidy::runClangTidy(clang::tidy::ClangTidyContext&, clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, llvm::IntrusiveRefCntPtr<llvm::vfs::OverlayFileSystem>, bool, llvm::StringRef) + 938
26 clang-tidy               0x0000000106ee0457 clang::tidy::clangTidyMain(int, char const**) + 4327
27 libdyld.dylib            0x00007fff2035d631 start + 1
Illegal instruction
  </pre>
</details>

**Comment by jonchang** [comment]
>  if brew gist-logs didn't work: ran brew config and brew doctor and included their output with your issue?

Please include this information. This can be reopened if you fill in the requested information: https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md

> Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
