### ISSUE TITLE
dispatch-build-bottle workflow does not clean the node its runs on

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#66328]
I've started building some ARM bottles with the `dispatch-build-bottle` on the new ARM nodes I have hooked up to github actions. However, I'm hitting a snag: the workflow is not cleaning up after building the bottles. By which I mean, it's leaving some installed formulas around in `/opt/homebrew/Cellar`, and in some cases this makes `brew doctor` fail on the next invocation of the workflow. You can look at the action queue see to some such failures: https://github.com/Homebrew/homebrew-core/actions?query=workflow%3A%22Dispatch+build+bottle%22

I do not know why this was not a problem for Intel Big Sur.

**Comment by fxcoudert** [comment]
In fact, it does not reset the homebrew-core repo either. This is the state of the node that has built `krb5`:

```
brew@28105 homebrew-core % git diff
diff --git a/Formula/krb5.rb b/Formula/krb5.rb
index 9f77965727..dc5d6cda4e 100644
--- a/Formula/krb5.rb
+++ b/Formula/krb5.rb
@@ -14,6 +14,7 @@ class Krb5 < Formula
     sha256 "ce41211e7264912be6fc05d8e5ed3bbc141679b0ab6c9b4099a36da811077a9f" => :big_sur
     sha256 "f50ff30a8268899f65150363f294ddcbd1969759f8700efac874caa181bca75d" => :catalina
     sha256 "4e5751f16b7e6d9f27968a9efb1ba5f702292c7fefdb25a32c940ef71f81b7cd" => :mojave
+    sha256 "ea5ca1833bfe4969c6c1551d6c7215c3115a945ab2cdc3f190333d93ed438f22" => :arm64_big_sur
   end
 
   keg_only :provided_by_macos
```

The corresponding action log seems okay, however: https://github.com/Homebrew/homebrew-core/runs/1504640008?check_suite_focus=true

**Comment by fxcoudert** [comment]
I start from a clean node:

- I launch a dispatch-build-bottle run for `ugrep` on `11-arm`: https://github.com/Homebrew/homebrew-core/runs/1506073803?check_suite_focus=true
- What `brew test-bot --only-formulae` does:
```
==> Running Formulae#formula!(ugrep)
==> Determining dependencies...
==> brew fetch --retry pcre2 xz
==> Starting build of ugrep
==> brew fetch --retry ugrep --build-bottle --force
==> brew install --only-dependencies --verbose --build-bottle ugrep
==> brew install --verbose --build-bottle ugrep
==> brew audit ugrep --online --git --skip-style
==> brew bottle --verbose --json ugrep --keep-old
==> brew bottle --merge --write --no-commit ./ugrep--2.5.6.arm64_big_sur.bottle.json --keep-old
==> brew uninstall --force ugrep
==> brew install --only-dependencies ./ugrep--2.5.6.arm64_big_sur.bottle.tar.gz
==> brew install ./ugrep--2.5.6.arm64_big_sur.bottle.tar.gz
==> brew linkage --test ugrep
==> brew install --only-dependencies --include-test ugrep
==> brew test --verbose ugrep
==> brew uninstall --force pcre2 xz
```

Note that it's not uninstalling `ugrep`

----

After the workflow, I connect to the runner and run `brew doctor`:

```
Warning: You have uncommitted modifications to Homebrew/homebrew-core.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /opt/homebrew/Library/Taps/homebrew/homebrew-core && git stash && git clean -d -f

Uncommitted files:
   M Formula/ugrep.rb

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install pcre2 xz

Run `brew missing` for more details.
```

Two issues:
- `/opt/homebrew/Library/Taps/homebrew/homebrew-core` has not been reset. I don't know where it should happen, I think `brew test-bot --only-cleanup-after` should do that
- `ugrep` is still installed (it should not). Moreover, its dependencies are missing, so this is a totally inconsistent state

**Comment by MikeMcQuaid** [comment]
@fxcoudert I think this is now fixed, please confirm.

**Comment by fxcoudert** [comment]
Confirmed fixed in https://github.com/Homebrew/homebrew-core/runs/1511668171?check_suite_focus=true
