### ISSUE TITLE
"brew install --build-from-source protobuf" fails with setuptools error

### ISSUE THREAD

**Issue by kevinburkemeter** [Homebrew/homebrew-core#66429]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? (Could not run this due to password issue)
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.6.0-133-g20af7ee
ORIGIN: https://github.com/Homebrew/brew
HEAD: 20af7ee11fcf1b186eb5978ba4871a2dba984a3c
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48d13301331b839c566fd76e5005ef660e9f3390
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/local/bin/nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_275
macOS: 10.15.7-x86_64
CLT: 12.2.0.0.1.1604628099
Xcode: N/A
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libblkid.1.dylib
  /usr/local/lib/libfdisk.1.dylib
  /usr/local/lib/libsmartcols.1.dylib
  /usr/local/lib/libuuid.1.dylib

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install protobuf

Run `brew missing` for more details.
```

## What you were trying to do (and why)

brew install --build-from-source setuptools

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre><code>

$ brew install --build-from-source protobuf

==> Downloading https://github.com/atomiix/protobuf/commit/d065bd6910a0784232dbbbfd3e5806922d69c622.patch?full_index=1
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/52bbfc6a11fdefb70e69a717a2bb56499ebe77606b2e832b0745a3d480288859--d065bd6910a0784232dbbbfd3e5806922d69c622.patch
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protobuf-all-3.14.0.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/downloads/703fe5ff9c3437b572add06c8fb8f734731cf4650ea84d5052c934839a14313d--protobuf-all-3.14.0.tar.gz
==> Patching
==> Applying d065bd6910a0784232dbbbfd3e5806922d69c622.patch
patching file python/setup.py
==> ./configure --prefix=/usr/local/Cellar/protobuf/3.14.0 --with-zlib
==> make
==> make check
==> make install
==> /usr/local/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/protobuf/3.14.0/libexec --install-scripts=/usr/local/Cellar/protobuf/3.14.0/libexec/bin --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/kevin/Library/Logs/Homebrew/protobuf/05.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/protobuf/3.14.0/libexec
--install-scripts=/usr/local/Cellar/protobuf/3.14.0/libexec/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

  </code></pre>
</details>

## What you expected to happen

I expected the installation to complete and for e.g. /usr/local/bin/protoc to exist

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install --build-from-source protobuf

**Comment by carlocab** [comment]
What happens when you fix these warnings?
```
Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libblkid.1.dylib
  /usr/local/lib/libfdisk.1.dylib
  /usr/local/lib/libsmartcols.1.dylib
  /usr/local/lib/libuuid.1.dylib
```

**Comment by kevinburkemeter** [comment]
just FYI, it's annoying to copy/paste the output from doctor into a "rm" command since you either need to manually insert backslashes or copy/paste one at a time. 

I am 99.5% sure I will get exactly the same output as before, let me try now.

**Comment by mitchblank** [comment]
Do you get any errors just doing: `/usr/local/opt/python@3.9/bin/python3 -c 'import setuptools'`?

I suspect that this has little to do with protobuf (which is building OK at least for the bottling machines) but something has gotten messed up in your python environment

**Comment by kevinburkemeter** [comment]
yes:

```
$ /usr/local/opt/python@3.9/bin/python3 -c 'import setuptools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by kevinburkemeter** [comment]
here's a gist from running "python3 -v", I tried searching the issue list for relevant references to setuptools, will try searching again.

https://gist.github.com/kevinburkemeter/85ba15dc91984949fb25100ce1e1b3c3

**Comment by carlocab** [comment]
Weird. I take it reinstalling python doesn't fix it?

**Comment by kevinburkemeter** [comment]
Removed the dylibs and still seeing the same failure (it takes 9 minutes to build protobuf from source on my machine).

I uninstalled and installed python@3 and the setuptools import is working now. Very odd. I also saw these errors when attempting to run `brew reinstall python@3` (with Homebrew-core commit 1a60e2e6309cd922b8dc50cd514472daa71b5fb2)

```
$ brew reinstall python@3
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.0_4.catalina.bottle.1.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/933ca658fbb4f1a5f63c28c4857e0071e4c759a9dd449f35a7cc3e8e04cf92dd?response-content-disposition=attachment%3Bfilename%3D%22python%403.9-3.9.0_4.catalina.bottle.1.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZS
######################################################################## 100.0%
==> Reinstalling python@3.9
==> Pouring python@3.9-3.9.0_4.catalina.bottle.1.tar.gz
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Resources with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Resources
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/Current with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/3.9/Headers with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/3.9/Headers
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Headers with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Headers
Error: Failure while executing; `cp -pR /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/. /usr/local/Cellar/python@3.9` exited with 1. Here's the output:
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Resources with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Resources
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/Current with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/Current
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/3.9/Headers with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Versions/3.9/Headers
cp: cannot overwrite directory /usr/local/Cellar/python@3.9/./3.9.0_4/Frameworks/Python.framework/Headers with non-directory /var/folders/s1/909yt58s4wj8h_7v7frr8rkm0000gn/T/d20201207-8384-1kmxie9/python@3.9/./3.9.0_4/Frameworks/Python.framework/Headers

Warning: Bottle installation failed: building from source.
==> Downloading https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/python@3.9/3.9.0_4 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@3.9/3.9.0_4/share --datadir=/usr/local/Cellar/python@3.9/3.9.0_4/share --enable-framework=/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks --enable-loadable
^C
```

**Comment by carlocab** [comment]
I actually had this exact problem with Python today. What does `brew info python` show?

**Comment by kevinburkemeter** [comment]
It's possible... I use pyenv normally, which installs everything on my machine to $HOME/.pyenv, but while troubleshooting I removed it from my $PATH.

While preparing this ticket - ie before submitting it - `brew doctor` said I had a `python@2` package in place that no longer had a corresponding formula, so I uninstalled it. Not sure if that's relevant.

This is after running brew uninstall python@3 and brew install python@3 which I did before my previous post.

```
$ brew info python
python@3.9: stable 3.9.0 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.0_4 (4,466 files, 72.5MB) *
  Poured from bottle on 2020-12-07 at 12:09:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```

**Comment by carlocab** [comment]
It's the most reasonable explanation I can think of for the error you see here: https://github.com/Homebrew/homebrew-core/issues/66429#issuecomment-740152847

But since trying to fix it destroyed the evidence; we'll never know.

Next time you face a similar issue with `setuptools` (or some other python module), check the input of `brew info python`. If these two lines
```
/usr/local/Cellar/python@3.9/3.9.0_4 (4,466 files, 72.5MB) *
  Poured from bottle on 2020-12-07 at 12:09:55
```
appear twice (with slight variation between them) then you're having the problem I described earlier.

Uninstall python fully (you may need to do `brew uninstall python` twice), then reinstall it and that should hopefully fix everything.

**Comment by kevinburkemeter** [comment]
OK will give it a try, thanks for the troubleshooting help.

**Comment by 2a5A1Ghu1** [comment]
Sorry to open this again but I too have this issue on a fresh x86 big sur system install. So the issue probably is not an environment path or old version of python laying around, unless python was recently updated that is.

I will also be able to test this on the new processor when I receive my new mac mini later today.

**Comment by 2a5A1Ghu1** [comment]
here is the output for brew python info @carlocab 

`
 ~ % brew info python
python@3.9: stable 3.9.0 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.0_4 (4,452 files, 72.2MB) *
  Poured from bottle on 2020-12-03 at 04:46:49
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✘, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 732,170 (30 days), 1,281,057 (90 days), 1,281,059 (365 days)
install-on-request: 204,367 (30 days), 274,545 (90 days), 274,545 (365 days)
build-error: 0 (30 days)
`

**Comment by carlocab** [comment]
Do you also see this error?
```
$ /usr/local/opt/python@3.9/bin/python3 -c 'import setuptools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
```

**Comment by 2a5A1Ghu1** [comment]
I see this

`==> ./configure --prefix=/usr/local/Cellar/protobuf/3.14.0 --with-zlib
==> make
==> make check
==> make install
==> /usr/local/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/protobuf/3.14.0/libexec --install-scripts=/usr/local/Cellar/protobuf/3.14.0/libexec/bin --single-version-externally-managed --record=installed.txt
==> /usr/local/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/protobuf/3.14.0/libexec --install-scripts=/usr/local/Cellar/protobuf/3.14.0/libexec/bin --single-version-externally-managed --record=installed.txt --cpp_imp
Last 15 lines from /Users/buddilla/Library/Logs/Homebrew/protobuf/06.python3:
--prefix=/usr/local/Cellar/protobuf/3.14.0/libexec
--install-scripts=/usr/local/Cellar/protobuf/3.14.0/libexec/bin
--single-version-externally-managed
--record=installed.txt
--cpp_implementation

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "setup.py", line 211, in <module>
    if mac_target and (pkg_resources.parse_version(mac_target) <
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 113, in parse_version
    return packaging.version.Version(v)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

READ THIS: https://docs.brew.sh/Troubleshooting
`

**Comment by 2a5A1Ghu1** [comment]
I think I figured it out when compiling from source python needs to be recompiled first for some reason. Not sure why, but I got it installed now. Very odd...

**Comment by gromgit** [comment]
> it's annoying to copy/paste the output from doctor into a "rm" command since with the files listed one per line, you either need to manually insert backslashes or copy/paste one at a time.

@kevinburkemeter , or use `xargs`:
```
xargs rm <<EOS
<paste list here>
EOS
```

**Comment by 2a5A1Ghu1** [comment]
So I have installed on mac arm and build from source has the same issue with the python poured tap and requires python to be built from source as well. I am assuming it is something else but that resolves the build from source issue for me.

**Comment by kevinburkemeter** [comment]
Wondering if this ticket should be reopened and re-titled "python3 setuptools import missing under unknown circumstances"

**Comment by 2a5A1Ghu1** [comment]
> Wondering if this ticket should be reopened and re-titled "python3 setuptools import missing under unknown circumstances"

LOL probably

**Comment by MikeMcQuaid** [comment]
> brew install --build-from-source protobuf

We don't support building from source.
