### ISSUE TITLE
openshift-cli v4.6 Forumla Installing v4.2.0-alpha

### ISSUE THREAD

**Issue by bellds** [Homebrew/homebrew-core#66435]
Running `brew install openshift-cli` on Big Sur is installing v4.2.

- [Yes] ran `brew update` and can still reproduce the problem?
- [ Yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install the latest openshift-cli (which is v4.6.7 as of Dec 7th, 2020).

## What happened (include command output)
```
bellds@bellds-sweet16 ~ % oc version
Client Version: v4.2.0-alpha.0-657-g51011e4
Kubernetes Version: v1.19.0+d59ce34
```

```
bellds@bellds-sweet16 ~ % brew info openshift-cli
openshift-cli: stable 4.6.0 (bottled), HEAD
OpenShift command-line interface tools
https://www.openshift.com/
/usr/local/Cellar/openshift-cli/4.6.0 (5 files, 75.4MB) *
  Poured from bottle on 2020-12-07 at 14:31:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openshift-cli.rb
License: Apache-2.0
==> Dependencies
Build: coreutils ✘, go ✔, heimdal ✘
Required: socat ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

/usr/local/share/zsh/site-functions is not in your zsh FPATH!
Add it by following these steps:
  https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
==> Analytics
install: 3,097 (30 days), 7,289 (90 days), 18,591 (365 days)
install-on-request: 3,068 (30 days), 7,225 (90 days), 18,431 (365 days)
build-error: 0 (30 days)
```

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install openshift-cli`

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
