### ISSUE TITLE
Brew MacOS Sur Doctor Issue - Uncommitted files

### ISSUE THREAD

**Issue by PeeHaysh** [Homebrew/homebrew-core#66464]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
Yes. Managed to run `update` over the past week but everytime get the same output error:

> ==> Summary
> 🍺  /usr/local/Cellar/python@3.9/3.9.0_4: 9,229 files, 136.4MB, built in 11 minutes 42 seconds
> Removing: /usr/local/Cellar/python@3.9/3.9.0_3... (9,229 files, 136.4MB)
> Removing: /Users/Nemo/Library/Caches/Homebrew/python@3.9--wheel--0.35.1.tar.gz... (58.3KB)
> Removing: /Users/Nemo/Library/Caches/Homebrew/python@3.9--patch--59c98f991f839d610d53ca5c4af1464a99adf6c85e807f8a676b3e41c5dbe0a2.patch... (3.8KB)
> Removing: /Users/Nemo/Library/Caches/Homebrew/python@3.9--pip--20.3.tar.gz... (1.5MB)
> ==> No outdated dependents to upgrade!
> ==> Checking for dependents of upgraded formulae...
> ==> Reinstalling 1 broken dependent from source:
> php@7.1
> ==> Downloading https://www.php.net/distributions/php-7.1.33.tar.xz
> Already downloaded: /Users/Nemo/Library/Caches/Homebrew/downloads/947253863d40b36e7d22cab588e833b5b73e03f7f17fb3c5cce4531750d09e99--php-7.1.33.tar.xz
> ==> Reinstalling php@7.1 
> Error: An exception occurred within a child process:
>   FormulaUnavailableError: No available formula with the name "/usr/local/opt/php@7.1/.brew/php@7.1.rb".
> 

- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Ran `doctor` and got the following warnings:

> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!
> 
> Warning: Some installed kegs have no formulae!
> This means they were either deleted or installed with `brew diy`.
> You should find replacements for the following formulae:
>   php@7.1
>   php71-xdebug
> 
> Warning: Some installed formulae are not readable:
>   php71-xdebug: cannot load such file -- /usr/local/opt/php71-xdebug/Abstract/abstract-php-extension
> 
> Warning: You have uncommitted modifications to Homebrew/brew.
> If this is a surprise to you, then you should stash these modifications.
> Stashing returns Homebrew to a pristine state but can be undone
> should you later need to do so for some reason.
>   cd /usr/local/Homebrew && git stash && git clean -d -f
> 
> Uncommitted files:
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/ast_aliases.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cached_data.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli/command.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli/command/auto_genenerate_config.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli/command/base.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/cli/command/execute_runner.rb
> ..... (taken out loads and loads of similar lines).... 
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/target_finder.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/target_ruby.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/version.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/warning.rb
>   ?? Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-0.88.0/lib/rubocop/yaml_duplication_checker.rb

I have tried ` cd /usr/local/Homebrew && git stash && git clean -d -f` and this has not worked, got the same issues as above.

Conducted `bundle install` (got `Could not locate Gemfile`) and even `brew audit`. 

Here is the output of `brew config`:

> HOMEBREW_VERSION: 2.6.0-135-gff28d7c
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: ff28d7c69b7b7e026757c63f15d00f98f07e5cec
> Last commit: 13 hours ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: 1bfa82df730d4f581c5e1270ecd0ff68929cb9a3
> Core tap last commit: 11 hours ago
> Core tap branch: master
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_CASK_OPTS: []
> HOMEBREW_MAKE_JOBS: 4
> Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
> CPU: quad-core 64-bit broadwell
> Clang: 12.0 build 1200
> Git: 2.29.2 => /usr/local/bin/git
> Curl: 7.64.1 => /usr/bin/curl
> Java: 1.8.0_112
> macOS: 11.0.1-x86_64
> CLT: N/A
> Xcode: 12.2

Can anyone shed any light on why I am getting these issues? 

I did have some warnings in `doctor` before Big Sur but afterwards there are significantly more. 

If there is a solution can someone share this with me as I am on a steep learning curve, or if this can help the developers in any way. If there is something that I have missed, please let me know.

**Comment by MikeMcQuaid** [comment]
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!

**Comment by PeeHaysh** [comment]
Hi Mike,

Just to say the issues outlined above have now been resolved. 
This was down to the fact that CLT was not picked up `brew config`. So after removing the older version of CLT and installed the latest version (12.2), running 'brew update && brew upgrade' followed by 'brew doctor' the issues seen above are no longer showing up. Also key, running 'brew config' the CLT version (12.2.xx) is showing up compared to previously it was showing as NA. 

Thanks!
