### ISSUE TITLE
brew install rust --HEAD fails

### ISSUE THREAD

**Issue by sorawee** [Homebrew/homebrew-core#66548]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?

I tried to fix issues as many as possible, but there are still some left. Nonetheless, it's pretty clear that it has nothing to do with the bug. See the output of `brew doctor` below.

- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Output of `brew config`

<details><pre>
HOMEBREW_VERSION: 2.6.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1d5e354cc2ff048bd7161d95b3fa7f91dc9dd081
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0da8557980f52cb7b820ed3aa1d9af0de47ed250
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1, 1.8.0_275
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: N/A
</pre></details>

Output of `brew doctor`

<details><pre>
Warning: Calling depends_on :java is deprecated! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the facebook/fb tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/facebook/homebrew-fb/buck.rb:19

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libedit.0.dylib
  /usr/local/lib/libedit.99.dylib
  /usr/local/lib/libnnz11.dylib
  /usr/local/lib/libociei.dylib
  /usr/local/lib/libocijdbc11.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/boolector/boolector.h
  /usr/local/include/boolector/btortypes.h
  /usr/local/include/editline/readline.h
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/gmock/gmock-actions.h
  /usr/local/include/gmock/gmock-cardinalities.h
  /usr/local/include/gmock/gmock-function-mocker.h
  /usr/local/include/gmock/gmock-generated-actions.h
  /usr/local/include/gmock/gmock-generated-function-mockers.h
  /usr/local/include/gmock/gmock-generated-matchers.h
  /usr/local/include/gmock/gmock-matchers.h
  /usr/local/include/gmock/gmock-more-actions.h
  /usr/local/include/gmock/gmock-more-matchers.h
  /usr/local/include/gmock/gmock-nice-strict.h
  /usr/local/include/gmock/gmock-spec-builders.h
  /usr/local/include/gmock/gmock.h
  /usr/local/include/gmock/internal/custom/gmock-generated-actions.h
  /usr/local/include/gmock/internal/custom/gmock-matchers.h
  /usr/local/include/gmock/internal/custom/gmock-port.h
  /usr/local/include/gmock/internal/gmock-internal-utils.h
  /usr/local/include/gmock/internal/gmock-port.h
  /usr/local/include/gmock/internal/gmock-pp.h
  /usr/local/include/gtest/gtest-death-test.h
  /usr/local/include/gtest/gtest-matchers.h
  /usr/local/include/gtest/gtest-message.h
  /usr/local/include/gtest/gtest-param-test.h
  /usr/local/include/gtest/gtest-printers.h
  /usr/local/include/gtest/gtest-spi.h
  /usr/local/include/gtest/gtest-test-part.h
  /usr/local/include/gtest/gtest-typed-test.h
  /usr/local/include/gtest/gtest.h
  /usr/local/include/gtest/gtest_pred_impl.h
  /usr/local/include/gtest/gtest_prod.h
  /usr/local/include/gtest/internal/custom/gtest-port.h
  /usr/local/include/gtest/internal/custom/gtest-printers.h
  /usr/local/include/gtest/internal/custom/gtest.h
  /usr/local/include/gtest/internal/gtest-death-test-internal.h
  /usr/local/include/gtest/internal/gtest-filepath.h
  /usr/local/include/gtest/internal/gtest-internal.h
  /usr/local/include/gtest/internal/gtest-param-util.h
  /usr/local/include/gtest/internal/gtest-port-arch.h
  /usr/local/include/gtest/internal/gtest-port.h
  /usr/local/include/gtest/internal/gtest-string.h
  /usr/local/include/gtest/internal/gtest-type-util.h
  /usr/local/include/histedit.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libedit.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/gmock.pc
  /usr/local/lib/pkgconfig/gmock_main.pc
  /usr/local/lib/pkgconfig/gtest.pc
  /usr/local/lib/pkgconfig/gtest_main.pc
  /usr/local/lib/pkgconfig/libedit.pc
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libboolector.a
  /usr/local/lib/libedit.a
  /usr/local/lib/libgmock.a
  /usr/local/lib/libgmock_main.a
  /usr/local/lib/libgtest.a
  /usr/local/lib/libgtest_main.a
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  nss
  mono
</pre></details>

## What you were trying to do (and why)

I tried to run `brew install rust --HEAD` to install `rust` from HEAD.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
==> Cloning https://github.com/rust-lang/cargo.git
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--cargo--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Downloading https://static.rust-lang.org/dist/2020-08-27/cargo-0.47.0-x86_64-apple-darwin.tar.gz
Already downloaded: /Users/sorawee/Library/Caches/Homebrew/downloads/164e1ba6647a32217399080670130f4327e67b185390d2d6670a79417a305ef0--cargo-0.47.0-x86_64-apple-darwin.tar.gz
==> Cloning https://github.com/rust-lang/rust.git
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git'...
Updating files: 100% (26247/26247), done.
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
Submodule 'library/backtrace' (https://github.com/rust-lang/backtrace-rs.git) registered for path 'library/backtrace'
Submodule 'library/stdarch' (https://github.com/rust-lang/stdarch.git) registered for path 'library/stdarch'
Submodule 'src/doc/book' (https://github.com/rust-lang/book.git) registered for path 'src/doc/book'
Submodule 'src/doc/edition-guide' (https://github.com/rust-lang/edition-guide.git) registered for path 'src/doc/edition-guide'
Submodule 'src/doc/embedded-book' (https://github.com/rust-embedded/book.git) registered for path 'src/doc/embedded-book'
Submodule 'src/doc/nomicon' (https://github.com/rust-lang/nomicon.git) registered for path 'src/doc/nomicon'
Submodule 'src/doc/reference' (https://github.com/rust-lang/reference.git) registered for path 'src/doc/reference'
Submodule 'src/doc/rust-by-example' (https://github.com/rust-lang/rust-by-example.git) registered for path 'src/doc/rust-by-example'
Submodule 'src/doc/rustc-dev-guide' (https://github.com/rust-lang/rustc-dev-guide.git) registered for path 'src/doc/rustc-dev-guide'
Submodule 'src/llvm-project' (https://github.com/rust-lang/llvm-project.git) registered for path 'src/llvm-project'
Submodule 'src/tools/cargo' (https://github.com/rust-lang/cargo.git) registered for path 'src/tools/cargo'
Submodule 'src/tools/miri' (https://github.com/rust-lang/miri.git) registered for path 'src/tools/miri'
Submodule 'src/tools/rls' (https://github.com/rust-lang/rls.git) registered for path 'src/tools/rls'
Submodule 'src/tools/rust-analyzer' (https://github.com/rust-analyzer/rust-analyzer.git) registered for path 'src/tools/rust-analyzer'
Submodule 'src/rust-installer' (https://github.com/rust-lang/rust-installer.git) registered for path 'src/tools/rust-installer'
Submodule 'src/tools/rustfmt' (https://github.com/rust-lang/rustfmt.git) registered for path 'src/tools/rustfmt'
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/library/backtrace'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/library/stdarch'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/book'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/edition-guide'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/embedded-book'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/nomicon'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/reference'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/rust-by-example'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/rustc-dev-guide'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/llvm-project'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/cargo'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/miri'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rls'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rust-analyzer'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rust-installer'...
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rustfmt'...
Submodule path 'library/backtrace': checked out 'af078ecc0b069ec594982f92d4c6c58af99efbb5'
Submodule 'backtrace-sys/src/libbacktrace' (https://github.com/rust-lang/libbacktrace) registered for path 'library/backtrace/crates/backtrace-sys/src/libbacktrace'
Cloning into '/Users/sorawee/Library/Caches/Homebrew/rust--git/library/backtrace/crates/backtrace-sys/src/libbacktrace'...
Submodule path 'library/backtrace/crates/backtrace-sys/src/libbacktrace': checked out '5c88e094a691bb803d4bba342403a10459abad9e'
Submodule path 'library/stdarch': checked out '777efaf5644706b36706a7a5c51edb63835e05ca'
Submodule path 'src/doc/book': checked out 'a190438d77d28041f24da4f6592e287fab073a61'
Submodule path 'src/doc/edition-guide': checked out 'b91a9a881ee007c12e74e844460ec407cf07a50f'
Submodule path 'src/doc/embedded-book': checked out 'ba34b8a968f9531d38c4dc4411d5568b7c076bfe'
Submodule path 'src/doc/nomicon': checked out 'd8383b65f7948c2ca19191b3b4bd709b403aaf45'
Submodule path 'src/doc/reference': checked out 'a8afdca5d0715b2257b6f8b9a032fd4dd7dae855'
Submodule path 'src/doc/rust-by-example': checked out '236c734a2cb323541b3394f98682cb981b9ec086'
Submodule path 'src/doc/rustc-dev-guide': checked out '7adfab42bab045a848126895c2f1e09927c1331a'
Submodule path 'src/llvm-project': checked out '7ade8dc4b84142abd3e6d1fb8a0f4111b0bbd571'
Submodule path 'src/tools/cargo': checked out 'd274fcf862b89264fa2c6b917b15230705257317'
Submodule path 'src/tools/miri': checked out 'e54c5db4f0edbe51db42d2c3e63e9821537ed4f4'
Submodule path 'src/tools/rls': checked out '2cf84baa5e3c55ac02f42919e67440acb5417125'
Submodule path 'src/tools/rust-analyzer': checked out '0d03fe6ef57d3956e92382e0e1f1a916015191cb'
Submodule path 'src/tools/rust-installer': checked out 'd66f476b4d5e7fdf1ec215c9ac16c923dc292324'
Submodule path 'src/tools/rustfmt': checked out '70ce18255f429caf0d75ecfed8c1464535ee779b'
/Users/sorawee/Library/Caches/Homebrew/rust--git/library/backtrace
/Users/sorawee/Library/Caches/Homebrew/rust--git/library/backtrace/crates/backtrace-sys/src/libbacktrace
/Users/sorawee/Library/Caches/Homebrew/rust--git/library/stdarch
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/book
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/edition-guide
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/embedded-book
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/nomicon
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/reference
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/rust-by-example
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/doc/rustc-dev-guide
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/llvm-project
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/cargo
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/miri
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rls
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rust-analyzer
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rust-installer
/Users/sorawee/Library/Caches/Homebrew/rust--git/src/tools/rustfmt
==> ./configure --prefix=/usr/local/Cellar/rust/HEAD-c0bfe34 --disable-rpath --release-channel=nightly
==> make
Last 15 lines from /Users/sorawee/Library/Logs/Homebrew/rust/02.make:
   Compiling filetime v0.2.12
   Compiling regex v1.3.9
   Compiling globset v0.4.5
   Compiling ignore v0.4.16
   Compiling merge_derive v0.1.0
   Compiling merge v0.1.0
   Compiling toml v0.5.7
    Finished dev [unoptimized + debuginfo] target(s) in 1m 23s

Couldn't find required command: ninja
You should install ninja, or set ninja=false in config.toml

failed to run: /private/tmp/rust-20201209-98233-1lap49t/build/bootstrap/debug/bootstrap build --stage 2
Build completed unsuccessfully in 0:01:42
make: *** [all] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
rust: add rust-src https://github.com/Homebrew/homebrew-core/pull/66315
rust 1.48 https://github.com/Homebrew/homebrew-core/pull/65286
Rust 1.48 revision bumps https://github.com/Homebrew/homebrew-core/pull/66285
rust-1.47 contains mismatched tools https://github.com/Homebrew/homebrew-core/issues/63202
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
  </pre>
</details>

## What you expected to happen

It installs successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install rust --HEAD
```

## Additional information

I also tried running the same command on Macbook M1 with the unsupported version of `brew` and encountered the very same problem.

**Comment by SMillerDev** [comment]
Head builds aren't supported by brew. You'll have to figure out the solution on your own or seek support from upstream.
