### ISSUE TITLE
Xapian 1.4.1 brew upgrade not installing due to xapian-bindings wanting sphinx-build

### ISSUE THREAD

**Issue by wakatara** [Homebrew/homebrew-core#6660]
brew doctored and having a working, healthy install. 

Installing xapian 1.4.1 breaks down when xapian-bindings try to install as it dies on configure with 

`brew upgrade xapian`

```
configure: error: sphinx-build is required to build python documentation (try packages python-sphinx and/or python3-sphinx)
```

I've tried installing sphinx via pip and pip3 which both yield that sphinx-build exists (first under 3.5 and then removed and installed under 2.7.). No love though.

Anyone have any ideas as to how to resolve. I've brew switched back to 1.2.23 for the moment.

thanks for all the amazing work!
Daryl

**Comment by dunn** [comment]
Can you post `brew gist-logs xapian`, please? Thanks!

**Comment by dunn** [comment]
What we'll probably do is add a dependency on `sphinx-doc` for the Python build, but currently that's failing because the Makefile is treating `sphinx-build` as a Python script rather than as an executable:
```
PYTHONPATH=..:$PYTHONPATH /usr/local/opt/python/bin/python /usr/local/opt/sphinx-doc/bin/sphinx-build -b html -d doctrees -c docs ./docs docs/html
  File "/usr/local/opt/sphinx-doc/bin/sphinx-build", line 2
    PYTHONPATH="/usr/local/Cellar/sphinx-doc/1.4.5/libexec/lib/python2.7/site-packages:/usr/local/Cellar/sphinx-doc/1.4.5/libexec/vendor/lib/python2.7/site-packages" exec "/usr/local/Cellar/sphinx-doc/1.4.5/libexec/bin/sphinx-build" "$@"
                                                      ^

**Comment by dunn** [comment]
Related: https://trac.xapian.org/ticket/740
