### ISSUE TITLE
midnight commander - /usr/local/share/man/?/man1 not writable

### ISSUE THREAD

**Issue by macxcool** [Homebrew/homebrew-core#6683]
### Bug reports:

I tried to install mc on OSX 10.11.6 today. I got a series of errors that /usr/local/share/man/??/man1 was not writable for ??=es,hu,it,pl,ru.

these folder are chowned root:wheel with 755 permissions. If I 'chmod o+w' or chown it works, of course, but why does it fail in the first place?

**Comment by MikeMcQuaid** [comment]
> but why does it fail in the first place?

Homebrew doesn't run as `root`. `brew doctor` should tell you to fix these permissions, please let me know if it does not.

**Comment by macxcool** [comment]
Sorry. I'm used to Linux. I realize now how Homebrew works. Thanks.

**Comment by MikeMcQuaid** [comment]
No worries, glad you got it sorted.
