### ISSUE TITLE
Incorrect version number for Logstash—86.64 instead of 7.10.1

### ISSUE THREAD

**Issue by JosephLeedy** [Homebrew/homebrew-core#66907]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I ran `brew update` to update all installed software.

## What happened (include command output)

All members of the Elasticsearch package were updated to 7.10.1, including Logstash, but Logstash has the wrong version number listed.

<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading logstash 7.9.3_1 -> 86.64
==> Downloading https://artifacts.elastic.co/downloads/logstash/logstash-oss-7.10.1-darwin-x86_64.tar.gz
######################################################################## 100.0%
==> Caveats
Configuration files are located in /usr/local/etc/logstash/

To have launchd start logstash now and restart at login:
  brew services start logstash
Or, if you don't want/need a background service you can just run:
  logstash
==> Summary
🍺  /usr/local/Cellar/logstash/86.64: 12,924 files, 568MB, built in 26 seconds
Removing: /usr/local/Cellar/logstash/7.9.3_1... (12,409 files, 276MB)
Removing: /Users/joseph/Library/Caches/Homebrew/logstash--7.9.3.tar.gz... (151.2MB)
==> Caveats
  </pre>
</details>

## What you expected to happen

Logstash formula should say version 7.10.1.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. Run `brew update`

## Additional Notes

* You can see the incorrect version listed for the [formula](https://formulae.brew.sh/formula/logstash) online.
* This number seems to come from the platform (x86_64).

**Comment by carlocab** [comment]
I've opened https://github.com/Homebrew/homebrew-core/pull/66908 as a temporary fix, though it may be useful to look into why `brew` is picking up the `x86_64` part of the URL as the verison.

**Comment by fxcoudert** [comment]
> it may be useful to look into why brew is picking up the x86_64 part of the URL as the version

Because we're not supposed to have arch-dependent URLs

**Comment by JosephLeedy** [comment]
Thanks for the quick response, @carlocab!
