### ISSUE TITLE
encfs should use macfuse not osxfuse

### ISSUE THREAD

**Issue by mike-kfed** [Homebrew/homebrew-core#66915]
right now encfs depends on a really old version of FUSE for macOS. I know the author of osxfuse (which is now called macfuse) no longer provides the kernel module as opensource, however it still is free to download and works fine (as shown in steps to reproduce).

## steps to reproduce

- Install macfuse 4.0.4 from https://osxfuse.github.io/ manually
- install osxfuse using `brew install --cask osxfuse`
- replace the load_osxfuse binary with a symlink to the macfuse version (this should especially help Apple Silicon M1 chip users)
```bash
LOAD_MACFUSE="/Library/Filesystems/macfuse.fs/Contents/Resources/load_macfuse"
sudo rm /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
sudo ln -s $LOAD_MACFUSE /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse
```

## problem

even using my fix to load the right kernel extension, this still uses the old `mount_osxfuse` binary. symlinking to the new one breaks encfs (apparently it uses it somehow wrong, as the the `--help` output is shown)

## fix

- compile encfs against the new macfuse
- remove osxfuse dependency
- tell user to manually install macfuse (e.g. when path `/Library/Filesystems/macfuse.fs` is not found)

**Comment by carlocab** [comment]
I'm not sure that's going to work, as formulae in homebrew-core cannot depend on software that is neither also on homebrew-core nor built-in on macOS (with the single exception of CLT).

I think you may wish to maintain a tap with a formula for `encfs` that does this. You can read up on how to do this [here](https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/) and [here](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Comment by SMillerDev** [comment]
> it still is free to download and works fine 

This is not good enough for inclusion into homebrew core.

**Comment by jonchang** [comment]
`encfs` is deprecated and we'll probably be removing it in the near future. See https://github.com/Homebrew/homebrew-core/pull/64491 for details.
