### ISSUE TITLE
SHA256 Mismatch Error

### ISSUE THREAD

**Issue by checkorcheque** [Homebrew/homebrew-core#66912]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [yes ] ran `brew update` and can still reproduce the problem?
- [ yes] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [yes ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install the newest version of python 3, however, a SHA256 error stopped my install

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

 ==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.18.1_1.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/5e0e7fa2b01cc9aa80d6078f0994504ca47b49bd672a170afcd0618276cef25b--gdbm-1.18.1_1.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1i.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/96a5853f13074094ebd917dbbd52884a355d74adcd7c0adb3d67b1cb1a9d6574--openssl@1.1-1.1.1i.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/readline-8.1.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/b03c5b80e59c91f05f4327bf3cb7a4dbab63a8902b76c0c53c6d36eb2e4331e9--readline-8.1.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.34.0.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/1a0242038ca8a6ce639d3a29ea0423dbd3a191255da3e4bb85add3e89608959a--sqlite-3.34.0.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.5.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/d2ab14304a4216cab7a33f64ba5bd7a33e1d24261df50421494549875dd56747--xz-5.2.5.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/python%403.9-3.9.1.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/37c48768fd4fd6ec313be61c558e59498be47a4746b511207ea1270c9b9e39ba--accounts.google.com
Error: SHA256 mismatch
Expected: 341bf346d9754ec96aec17b381cae65a0714deaa5d91d6eae9fe07ff879933f1
  Actual: bd645a5b3b5a3b5d14e2e515825006914496b96ece77c757c9595d9dce8e8ad1
    File: /Users/soup/Library/Caches/Homebrew/downloads/37c48768fd4fd6ec313be61c558e59498be47a4746b511207ea1270c9b9e39ba--accounts.google.com
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2_3.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/581db8da5bd5c492a8c454614342a821b661fc371f953782ba342345312ffe90--pkg-config-0.29.2_3.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.18.1_1.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/5e0e7fa2b01cc9aa80d6078f0994504ca47b49bd672a170afcd0618276cef25b--gdbm-1.18.1_1.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/openssl%401.1-1.1.1i.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/96a5853f13074094ebd917dbbd52884a355d74adcd7c0adb3d67b1cb1a9d6574--openssl@1.1-1.1.1i.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/readline-8.1.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/b03c5b80e59c91f05f4327bf3cb7a4dbab63a8902b76c0c53c6d36eb2e4331e9--readline-8.1.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.34.0.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/1a0242038ca8a6ce639d3a29ea0423dbd3a191255da3e4bb85add3e89608959a--sqlite-3.34.0.big_sur.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.5.big_sur.bottle.tar.gz
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/d2ab14304a4216cab7a33f64ba5bd7a33e1d24261df50421494549875dd56747--xz-5.2.5.big_sur.bottle.tar.gz
==> Downloading https://files.pythonhosted.org/packages/12/e1/b9a2926a3c5a3fb055b8f85052f5baa890106a0e
Already downloaded: /Users/soup/Library/Caches/Homebrew/downloads/206fa549f9c3c993a25689ee791fb16dbc8d5c9ecf98e1f87fabbba882197aed--accounts.google.com
Error: SHA256 mismatch
Expected: 029c49fd713e9230f6a41c0298e6e1f5839f2cde7104c0ad5e053a37777e7688
  Actual: 76da2e409aed0e703c98b58647ceb500fdf3ba06fc6b1b617b1fa27faaa1ab2a
    File: /Users/soup/Library/Caches/Homebrew/downloads/206fa549f9c3c993a25689ee791fb16dbc8d5c9ecf98e1f87fabbba882197aed--accounts.google.com
To retry an incomplete download, remove the file above.

  </pre>
</details>

## What you expected to happen

I expected the newest version of python to be installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install python`

I ran `brew update` and `brew doctor`

after running `brew config -d` I received the output: 

<details>
  <summary>Command output</summary>
  <pre>

HOMEBREW_VERSION: 2.6.2
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1a52862e6d24cd3bf87bec557a8886a1a825ee3c
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d914aab917710e94170526641d16414cb6a2083e
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
/usr/bin/curl --version
Curl: 7.64.1 => /usr/bin/curl
/usr/libexec/java_home --xml --failfast
macOS: 11.0.1-x86_64
CLT: 12.2.0.0.1.1604076827
Xcode: 12.2

  </pre>
</details>

after running `brew doctor` I recieved the output:

<details>
  <summary>Command output</summary>
  <pre>

Your system is ready to brew.

  </pre>
</details>

**Comment by carlocab** [comment]
`brew` appears to have confused `/Users/soup/Library/Caches/Homebrew/downloads/37c48768fd4fd6ec313be61c558e59498be47a4746b511207ea1270c9b9e39ba--accounts.google.com` for the `python@3.9` bottle. Not sure why. Please delete (or move) this file, then try again.

**Comment by checkorcheque** [comment]
That fixed it! Thank you so much 🙂
