### ISSUE TITLE
Neko build failure on Big Sur

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#66954]
Re: https://github.com/Homebrew/homebrew-core/pull/66819#issuecomment-745353950, https://github.com/Homebrew/homebrew-core/issues/65000

`neko` is failing to build on Big Sur and, through the dependency graph, is causing build failures for `haxe` and `hashlink`.

CI run logs:
https://github.com/Homebrew/homebrew-core/runs/1546897078

Log archive for `neko` and `hashlink` (`haxe` is missing for some reason): 
[logs.tar.gz](https://github.com/Homebrew/homebrew-core/files/5696932/logs.tar.gz)

**Comment by fxcoudert** [comment]
I didn't mean here, I meant with neko themselves (sorry for not being clear)

**Comment by fxcoudert** [comment]
I've done so at https://github.com/HaxeFoundation/neko/issues/216

**Comment by carlocab** [comment]
No, you were clear. I misread your comment. Sorry!

**Comment by carlocab** [comment]
I'm going to try some ARM builds, but need somewhere to dump the build failure comments. Apologies for the noise for anyone still watching this issue.
