### ISSUE TITLE
After brew upgrade Rocksdb fails to open compressed databases

### ISSUE THREAD

**Issue by larskuhtz** [Homebrew/homebrew-core#67048]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Continue to use rocksdb after `brew upgrade`

## What happened (include command output)

Rocksdb fails to open database files with compression. This behavior was first observed on GitHub Actions runners with `macos-lastest` and reproduced on a local MacOSX Big Sur system. In both cases rocksdb was working fine until a few days ago. On the local system the issue showed up only after running `brew upgrade`.

<details>
  <summary>Command output</summary>
  <pre>

$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=snappy "1" "a"
Failed: Invalid argument: Compression type Snappy is not linked with the binary.
$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=zlib "1" "a"
Failed: Invalid argument: Compression type Zlib is not linked with the binary.
$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=bzip2 "1" "a"
Failed: Invalid argument: Compression type BZip2 is not linked with the binary.
$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=lz4 "1" "a"
Failed: Invalid argument: Compression type LZ4 is not linked with the binary.
$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=zstd "1" "a"
Failed: Invalid argument: Compression type ZSTD is not linked with the binary.
$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=no "1" "a"
OK
  </pre>
</details>

## What you expected to happen

```sh
$ rocksdb_ldb put --db=testdb --create_if_missing --compression_type=snappy "1" "a"
OK
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```sh
brew update
brew install rocksdb
rocksdb_ldb put --db=testdb --create_if_missing --compression_type=snappy "1" "a"
```

Additional info:

```sh
$ brew --version
Homebrew 2.6.2-89-g632c9be
Homebrew/homebrew-core (git revision 71b0561; last commit 2020-12-17)
Homebrew/homebrew-cask (git revision b6e3a; last commit 2020-12-17)
```

```sh
$ brew info rocksdb
rocksdb: stable 6.14.6 (bottled)
Embeddable, persistent key-value store for fast storage
https://rocksdb.org/
/usr/local/Cellar/rocksdb/6.14.6 (125 files, 30.5MB) *
  Built from source on 2020-12-16 at 22:14:35
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rocksdb.rb
License: GPL-2.0
==> Dependencies
Build: cmake ✔
Required: gflags ✔, lz4 ✔, snappy ✔, zstd ✔
==> Analytics
install: 1,451 (30 days), 2,456 (90 days), 14,565 (365 days)
install-on-request: 1,000 (30 days), 1,766 (90 days), 7,548 (365 days)
build-error: 0 (30 days)
```

**Comment by bayandin** [comment]
Thanks for the report @larskuhtz, probably we missed linkage during migration to `cmake` (in https://github.com/Homebrew/homebrew-core/pull/66445).

Will be fixed in https://github.com/Homebrew/homebrew-core/pull/67051

**Comment by larskuhtz** [comment]
I confirmed that the change in #67051 fixes the issue. Thanks a lot for the fast response!
