### ISSUE TITLE
Boost version is 1.75 but boost-mpi is 1.74

### ISSUE THREAD

**Issue by fabiocody** [Homebrew/homebrew-core#67285]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I upgraded all my formula with `brew upgrade`, `boost` got upgraded to 1.75, while `boost-mpi` remained at 1.74, making it unusable.

## What happened (include command output)

The installation of `boost` went fine, but when I refreshed my C++ project with `cmake`, it couldn't find `boost-mpi` 1.75. So I checked the version of `boost-mpi` installed by Homebrew and it was still 1.74.

<details>
  <summary>Command output</summary>
  <pre>

  Could not find a configuration file for package "boost_mpi" that exactly
  matches requested version "1.75.0".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/boost_mpi-1.74.0/boost_mpi-config.cmake, version: 1.74.0

  </pre>
</details>

## What you expected to happen

I expect that when boost gets updated, also other libraries that depend on it get updated.

## `brew config` output

```
HOMEBREW_VERSION: 2.6.2-207-gf47c1ea
ORIGIN: https://github.com/Homebrew/brew
HEAD: f47c1eae3256fe263b3adf60e8e437b97bb5eb7d
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 01476261de930e536a7acdcc262107721063befe
Core tap last commit: 50 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1, 1.8.0_275
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
```

`brew gist-logs boost-mpi` returned no logs.

**Comment by carlocab** [comment]
Opened a PR to update `boost-mpi`: https://github.com/Homebrew/homebrew-core/pull/67286

Feel free to open one yourself next time; it's easy. Reading this might help: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by carlocab** [comment]
Also, do you mind sharing a minimal `CMakeLists.txt` and a minimal C++ source file that produces an error for the version mismatch?

This will help pick up the error in future CI runs so that this doesn't happen again.

**Comment by fabiocody** [comment]
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_COMPILER mpic++)

find_package(Boost COMPONENTS mpi serialization log log_setup graph REQUIRED)
include_directories(${Boost_INCLUDE_DIRS})

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DBOOST_LOG_DYN_LINK -Wall")
```

The line that fails is the `find_package` one.

**Comment by carlocab** [comment]
Thanks. I think the following should also produce an error. Could you verify that for me, please?
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)
set(CMAKE_CXX_COMPILER mpic++)

find_package(Boost COMPONENTS mpi REQUIRED)
```

**Comment by fabiocody** [comment]
Correct.

**Comment by carlocab** [comment]
Great. I've updated the test in the formula to incorporate this. Future CI runs should catch this error, so hopefully, it won't happen again.
