### ISSUE TITLE
RFC: Make downloads more robust

### ISSUE THREAD

**Issue by stweil** [Homebrew/homebrew-core#67283]
# Bug report

The formula for `docbook-xsl` requires a patch (http://www.linuxfromscratch.org/patches/blfs/9.1/docbook-xsl-nons-1.79.2-stack_fix-1.patch) which can be downloaded using IPv6, but not with IPv4.

This is a problem of the download server, but Homebrew could fall back to the other protocol automatically if either IPv4 or IPv6 fails.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried `brew install asciidoc` (which depends on `docbook-xsl`) on Mac mini M1. Maybe the issue can also be reproduced on Intel MacBooks with `brew install --build-from-source docbook-xsl`.

## What happened (include command output)

The installation hangs while trying to download http://www.linuxfromscratch.org/patches/blfs/9.1/docbook-xsl-nons-1.79.2-stack_fix-1.patch.

## What you expected to happen

The download should work.

## Reason for failure

The download server has a buggy configuration. It has both an IPv4 and an IPv6 address, but downloading only works with IPv6.

**Comment by tobylane** [comment]
I can see it on ipv4. 

Can you add the patch to this repo? https://github.com/Homebrew/formula-patches. Include credit in the commit message then update the formula with the new url.

**Comment by MikeMcQuaid** [comment]
We use `curl` for downloading. We'll review a PR to pass flags to make `curl` behave in this manner (if it's possible to do so).
