### ISSUE TITLE
The python extension of fontforge may not have been installed properly by homebrew

### ISSUE THREAD

**Issue by SunHaozhe** [Homebrew/homebrew-core#67294]
I am on MacOS Catalina version 10.15.7 and I have `Homebrew 2.6.2`. I am using `Python 3.6.1`

I tried to install `fontforge` using Homebrew. The installation process succeeded without reporting any errors. However, when I tried to run python scripts that contain `import fontforge` with the standard python interpreter, it failed and gave the error `No module named fontforge`.

To reproduce this:

1. `brew install fontforge`
2. Create a python script that contains a single line `import fontforge`, then name it as `main.py`
3. Run the command `python3 main.py`

I first reported this issue on FontForge's page [https://github.com/fontforge/fontforge/issues/4542](https://github.com/fontforge/fontforge/issues/4542), but they suggest to ask here. They think that the python extension may not have been installed properly by Homebrew.

**Comment by alebcay** [comment]
In the future, please complete the issue template that is provided when you open an issue, or else we will be missing vital information needed to diagnose and assist with your situation.

Regarding the issue you've brought up, I just tried to reproduce this and failed to do so. Several things stand out to me, though:

> I am using `Python 3.6.1`

Homebrew doesn't ship this version of Python - where are you getting this?

> Run the command `python3 main.py`

What's the output of `which python3` and `python3 -V`? Again, I think something is strange/amiss with your Python installation.

We need more information to diagnose your issue - please provide all the information that is requested in the [issue template](https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md).

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
