### ISSUE TITLE
Installing or updating certbot installs unneccesary packages

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew-core#6730]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Upon trying to update certbot today homebrew installed python and sqlite. I already have python and sqlite on my system (doesn't everyone?). After uninstalling the dups, I ran brew info certbot and there is a checkmark next to the python dependency and sqlite isn't listed at all. I tried to install certbot again and again the dups are installed.

Obviously this is extremely undesirable behaviour.

**Comment by ilovezfs** [comment]
```
  depends_on :python
```

If you use the certbot bottle, this is converted into a dependency on the Homebrew formula python.

```
$ brew deps python
gdbm
openssl
readline
sqlite
```

**Comment by CamJN** [comment]
When did that change happen?

**Comment by ilovezfs** [comment]
That's always been true but we've begun to transition all
```
depends_on :python if MacOS.version <= :snow_leopard
```
over to
```
depends_on :python
```

https://github.com/Homebrew/brew-evolution/pull/12

**Comment by CamJN** [comment]
Whelp I guess there are going to be a lot more formulae I can't use anymore.

**Comment by MikeMcQuaid** [comment]
@CamJN Why does having a non-system Python dependency mean you can't use a formula? Do you feel unable to use all OpenSSL formula because it uses a non-system OpenSSL?

**Comment by ilovezfs** [comment]
@CamJN if you have not already installed the brew python, and you build the formula from source, then it will not install or force you to use the brew python or the brew sqlite.

**Comment by CamJN** [comment]
@MikeMcQuaid because the presence of homebrew's python breaks literally every python based piece of software on my system, that's why.

**Comment by MikeMcQuaid** [comment]
@CamJN Can you elaborate a lot more, please? We can't fix such things or make good decisions if we don't have enough information to reproduce.

**Comment by CamJN** [comment]
I don't know enough about python to add much more to that. All I know is that when the only python on my system is the system python, then stuff works like aws-cli and some work scripts I have. When homebrew python is installed those things stop working.

I don't expect you to be able to fix things based on that little info, which is why I never opened an issue about it. I was more than happy to simply not install homebrew's python. But now that has become a pain so I'll drop the homebrew packages that depend on it too. Much like homebrew php now forcing you to install homebrew's apache led me to drop them as well.

**Comment by MikeMcQuaid** [comment]
@CamJN The thing is we'd like to actually help here. If you can post a script that breaks somewhere and the output of it breaking we'll do our best to help.
