### ISSUE TITLE
python package linked to stale version of tcl/Tk, cause crash when key pressed in `French - PC` keyboard layout

### ISSUE THREAD

**Issue by spacether** [Homebrew/homebrew-core#67327]
# Bug report

When brew installing python with `brew install python`
I think that we are dynamically linking to the stale tcl/tk version on MacOS.
That older version of tcl/tk has a bug where a key press in the `French - PC` keyboard layout crashes python.
This is fixed in later versions of tcl/Tk.
In the [python brew package](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb) 
can we link to the newer version?

- [X] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I want to press the [ key in the French - PC layout and capture the key up and down event in the python tkinter library (python std lib).

## What happened (include command output)

On macOs 10.14.6 laptop with a qwerty layout, when I switch my keyboard layout to `French - PC` and use a tkinter keyboard listener
and press the '[' button which should be the '^' button on the azerty keyboard, this Error is thrown:
```
2020-12-14 10:13:26.533 Python[14880:1492926] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFConstantString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff41ce49ad __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6c3dfa17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff41ce47df +[NSException raise:format:] + 201
	3   CoreFoundation                      0x00007fff41c5a159 -[__NSCFString characterAtIndex:] + 102
	4   Tk                                  0x00007fff4da8a806 TkpInitKeymapInfo + 719
	5   Tk                                  0x00007fff4da905e9 Tk_MacOSXSetupTkNotifier + 793
	6   Tcl                                 0x00007fff4d98c48e Tcl_DoOneEvent + 301
	7   _tkinter.cpython-38-darwin.so       0x00000001090802de _tkinter_tkapp_mainloop + 342
	8   Python                              0x0000000108ac1b0a method_vectorcall_FASTCALL + 250
	9   Python                              0x0000000108b5a299 call_function + 346
	10  Python                              0x0000000108b51457 _PyEval_EvalFrameDefault + 3895
	11  Python                              0x0000000108b5ae5d _PyEval_EvalCodeWithName + 2107
	12  Python                              0x0000000108abad39 _PyFunction_Vectorcall + 217
	13  Python                              0x0000000108abcc7d method_vectorcall + 135
	14  Python                              0x0000000108b5a299 call_function + 346
	15  Python                              0x0000000108b51477 _PyEval_EvalFrameDefault + 3927
	16  Python                              0x0000000108b5ae5d _PyEval_EvalCodeWithName + 2107
	17  Python                              0x0000000108b5047d PyEval_EvalCode + 51
	18  Python                              0x0000000108b89025 run_eval_code_obj + 102
	19  Python                              0x0000000108b88473 run_mod + 82
	20  Python                              0x0000000108b87345 PyRun_FileExFlags + 160
	21  Python                              0x0000000108b86a29 PyRun_SimpleFileExFlags + 271
	22  Python                              0x0000000108b9e449 Py_RunMain + 1870
	23  Python                              0x0000000108b9e790 pymain_main + 306
	24  Python                              0x0000000108b9e7de Py_BytesMain + 42
	25  libdyld.dylib                       0x00007fff6dbae3d5 start + 1
	26  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```
One can verify this by running this program on a macOs laptop with a qwerty keyboard, switching the layout to French - PC and pressing the '[' key.
Verification program:
```
from tkinter import *
def keyup(e):
    print('up', e.__dict__)
def keydown(e):
    print('down', e.__dict__)

root = Tk()
frame = Frame(root, width=100, height=100)
frame.bind("<KeyPress>", keydown)
frame.bind("<KeyRelease>", keyup)
frame.pack()
frame.focus_set()
root.mainloop()
```
Details from:
https://bugs.python.org/issue42640

## What you expected to happen

I expect python not to crash

## Step-by-step reproduction instructions (by running `brew install` commands)

On macOS 10.14.6:
- `brew install python`
- run the above python program
- switch your keyboard layout to `French - PC`
- press the qwerty '[' key to the right of p
- watch python crash

**Comment by carlocab** [comment]
See https://github.com/Homebrew/brew/issues/9488#issuecomment-748460805 and the next five or so comments.

**Comment by spacether** [comment]
I used `/usr/bin/python3` installed through `brew install python` and reproduced this issue

**Comment by carlocab** [comment]
Sorry, I'm a bit confused by your previous comment. `/usr/bin/python3` is your system's built-in python, and cannot have been installed by `brew install python`.

If you can reproduce the issue with `/usr/bin/python3`, then it would show that this isn't an issue with Homebrew Python. Details are in the link I shared with you above.

**Comment by spacether** [comment]
My mistake it doesn't look like I used `/usr/bin/python3`
There is no python3 there on my machine:
```
justins-air:keyboardlayout justinblack$ /usr/bin/python3
-bash: /usr/bin/python3: No such file or directory
Trying it now using `/usr/local/bin/python3` I was unable to reproduce the earlier crash
This may be because I installed TK 8.6 recently.
I am closing this ticket because I am no longer able to reproduce it.
