### ISSUE TITLE
python@3.9 and gdbm finally break on Apple Silicon.

### ISSUE THREAD

**Issue by kaorihinata** [Homebrew/homebrew-core#67388]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
Yes.
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
Homebrew is functioning. This issue is to fix a broken formula.
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
No gist-logs link was returned.
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
`brew config` below, but Homebrew is functioning. This issue is to fix a broken formula.
```
HOMEBREW_VERSION: 2.7.0-2-g6994633
ORIGIN: https://github.com/Homebrew/brew
HEAD: 699463358167072d577d0f13f76b0722e32d8cc0
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 84c6c43b31ece5cc412db7092a2331d9a843d753
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: N/A
Xcode: 12.3
Rosetta 2: false
```

## What you were trying to do (and why)

Install `python@3.9` (which includes `gdbm` as a dependency) and debug a failing test with regard to GDBM's NDBM interface on the Apple Silicon architecture.

## What happened (include command output)

I installed `python@3.9` through Homebrew, then ran the following script (based off of `test_dbm_ndbm` in the upstream test suite):

```python
# vim: set fileencoding=utf-8 :

import dbm

with dbm.ndbm.open("test", "c") as db:
    db[b"foo \xbd"] = b"bar \xbd"
with dbm.ndbm.open("test", "r") as db:
    print(list(db.keys()) == [b"foo \xbd"])
    print(b"foo \xbd" in db)
    print(db[b"foo \xbd"] == b"bar \xbd")
```

The script failed identically to the upstream test suite. Attempting to enumerate keys results in a segmentation fault (`11`/`EXC_BAD_ACCESS`). I posted an abbreviated version of this test to [issue #7857 on homebrew/brew](https://github.com/Homebrew/brew/issues/7857#issuecomment-748796555) and was able to confirm this behavior.

<details>
  <summary>Command output</summary>
  <pre>

Segmentation fault: 11

  </pre>
</details>

## What you expected to happen

Ideally, the script should print:

```
True
True
True
```

...as the tests succeed. Instead it segmentation faults on the first test.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. On an Apple Silicon based Mac running macOS 11.x (Big Sur) install Homebrew (to `/opt/homebrew` preferably.)
2. Install `python@3.9`.
3. Attempt to run the above script, or the abbreviated command from [issue #7857 on homebrew/brew](https://github.com/Homebrew/brew/issues/7857#issuecomment-748796555).

## What's actually happening (or why I haven't submitted a pull request yet)

Unfortunately, Homebrew's attempts to prevent the `gdbm` formula from interfering with the system `ndbm.h` header is having the opposite effect of the system `ndbm.h` header interfering with applications interacting with `gdbm`.

From the `gdbm` formula:

```ruby
mv include/"ndbm.h", include/"gdbm-ndbm.h"
```

The current behavior of the `gdbm` formula is to rename `ndbm.h` to `gdbm-ndbm.h`. The problem with this behavior is actually in how `python@3.9` (and more specifically, `Modules/_dbmmodule.c`) decides which header to use:

From `Modules/_dbmmodule.c` (top of the file):

```c
#if defined(HAVE_NDBM_H)
#include <ndbm.h>
static const char which_dbm[] = "GNU gdbm";  /* EMX port of GDBM */
#elif defined(HAVE_GDBM_NDBM_H)
#include <gdbm/ndbm.h>
static const char which_dbm[] = "GNU gdbm";
#elif defined(HAVE_GDBM_DASH_NDBM_H)
#include <gdbm-ndbm.h>
static const char which_dbm[] = "GNU gdbm";
#elif defined(HAVE_BERKDB_H)
#include <db.h>
static const char which_dbm[] = "Berkeley DB";
#else
#error "No ndbm.h available!"
#endif
```

Unfortunately, it looks for `ndbm.h` first, and finds it (from Xcode.) It then looks for an NDBM library, and finds it (from the Homebrew `gdbm` formula.) As a result it uses the system `ndbm.h` header to decide how to speak to the `gdbm` library. The problem with that is that you need to use the `datum` `struct` when passing data to the `gdbm` library via the NDBM compatible interface. The system `ndbm.h` declares it as:

```c
typedef struct {
    void * dptr;
    size_t dsize;
} datum;
```

In this case we know that pointer size is 8 bytes, and `sizeof(dsize)` is 8 bytes (as it's a `size_t`.) This isn't good for us, because this is how `gdbm` declares `datum`:

```c
typedef struct {
    char * dptr;
    int dsize;
} datum;
```

The pointer size is still 8 bytes, but `sizeof(dsize)` is only 4 bytes (as it's an `int`), so the result is GDBM handing you a 32-bit `dsize` value, and anything built against the system `ndbm.h` is expecting a 64-bit `dsize` value so you end up with a `Py_ssize_t` half filled with garbage because you're copying an additional 4 bytes of whatever data is written next to `dsize`. This crashes Python pretty reliably when the neighboring data is not null bytes. I've confirmed the behavior with LLDB, and LLDB correctly shows that `datum` is incorrectly using the system definition when Python is built in debug mode (`dsize` is reported as 8 bytes in size.) Strangely enough, this is the same on `x86_64`, but it appears that we got lucky with struct padding or something because I've not been able to crash it.

I don't know where else `gdbm` is being used and what the requirements are there, but removing the above line and not renaming `ndbm.h` results in the header being properly found and overriding the system header. LLDB also confirms that `size` is now 4 bytes, not 8. There are plenty of other ways to fix this (like patching `Modules/_dbmmodule.c`), but I'm not sure what kind of solution is preferred in this situation.

**Comment by kaorihinata** [comment]
Just a note that this has not been fixed, and as mentioned above, though it doesn't crash `x86_64` which is currently supported, it is still being built with the wrong headers which means it does have the potential to be an issue in the future.

**Comment by fxcoudert** [comment]
Sorry I closed the wrong PR 😞

**Comment by carlocab** [comment]
The easiest thing to do locally would be to patch `Modules/_dbmmodule.c`. But, as you suggest, this could have non-obvious undesirable consequences. For instance, there are references to `ndbm.h` in `setup.py`, and I don't know how to tell how this interacts (if at all) with `Modules/_dbmmodule.c`.

Do you mind filing a bug report upstream? I think finer-grained control over which `dbm` module to use is something that they ought to be supporting anyway.

**Comment by kaorihinata** [comment]
After digging through `setup.py` a bit, it seems like the option we want is already there, though it's applicability in this case isn't immediately obvious until you read the chunk of code where it makes the decision (`setup.py` lines 1354 to 1426.) It's also much clearer now why this happened. By default, the DBM library search order puts NDBM first, but as there's no actual library to find (on the filesystem), it moves on and finds GDBM which results in the mixup we're seeing. To instruct the build process to try GDBM first, we can just pass `--with-dbmliborder=gdbm:ndbm`:
```patch
diff --git a/Formula/python@3.9.rb b/Formula/python@3.9.rb
index ed0dc51a25..759b479853 100644
--- a/Formula/python@3.9.rb
+++ b/Formula/python@3.9.rb
@@ -107,6 +107,7 @@ class PythonAT39 < Formula
       --enable-ipv6
       --datarootdir=#{share}
       --datadir=#{share}
+      --with-dbmliborder=gdbm:ndbm
       --enable-loadable-sqlite-extensions
       --with-openssl=#{Formula["openssl@1.1"].opt_prefix}
     ]
```
I can confirm that the build completes, and my test passes. With this I believe it should also be possible to pass upstream's `make test`.

**Comment by carlocab** [comment]
That's promising. Can you find any documentation that supports this as the intended use case of the `--with-dbmliborder` flag?

**Comment by kaorihinata** [comment]
Sure. [Here](https://bugs.python.org/issue4587) is the Issue where the change was initially recommended, and [here](https://bugs.python.org/issue15044) is a similar issue encountered on Fedora where an active Python committer recommends this usage for them as a workaround. In our case, the OS provides a valid POSIX NDBM solution, and we are choosing to using GDBM instead, so using `--with-dbmliborder` appears to make the most sense.

**Comment by fxcoudert** [comment]
The question becomes: why are we using gdbm? Would the OS ndbm be as full-featured?

**Comment by carlocab** [comment]
The `gdbm` dependency was introduced in https://github.com/Homebrew/legacy-homebrew/commit/843bff9887a1b8498aacf61c7e03a08574759c99 and it seems we've been carrying it around since.

I tried looking up what exactly the difference between `gdbm` and `ndbm` is, but no dice.

**Comment by fxcoudert** [comment]
Hum… what do other python distributions ships with? the one from python.org, and anaconda, for example?

**Comment by kaorihinata** [comment]
The official distribution from python.org does not include GDBM. It appears to be built against the system NDBM header. Anaconda allows the installation of a GDBM module (see: [the package list](https://docs.anaconda.com/anaconda/packages/py3.8_osx-64/)), but they do not include it by default (according to the list.)

**Comment by carlocab** [comment]
This seems like a good reason to drop the dependency. Are you aware of any disadvantages to this, @kaorihinata?

**Comment by kaorihinata** [comment]
> This seems like a good reason to drop the dependency. Are you aware of any disadvantages to this, @kaorihinata?

As far as I'm aware the only place that Python itself makes use of GDBM is in its `dbm` module, and it does so using the `_gdbm` C extension. If you don't have GDBM support compiled in, then the DBM module just falls back to NDBM (if it has it.) I suppose there could be a piece of software somewhere that makes use of the `_gdbm` module directly, but I doubt that kind of usage would be supported by the Python project.

**Comment by fxcoudert** [comment]
> I'm assuming we'd be making GDBM support optional again

No, we have removed options from homebrew-core a couple of years ago (they weren't adequately tested on CI anyway)

**Comment by carlocab** [comment]
I tried digging a bit further through git logs, and it seems the optional `gdbm` dependency became recommended at one point. When options were removed, the recommended dependency became a hard dependency.

It's hard to distinguish whether the conversion to a hard dependency was because usage data reflected:
1. a user preference for `gdbm` support; or,
2. users just not being bothered enough to pass a `--without-gdbm` flag.

I suspect it's the latter, but have no data to support that. If it is the latter, then dropping the dependency should be fine.

**Comment by kaorihinata** [comment]
Alright. If any libraries that Homebrew manages explicitly import `dbm.gnu` then the import will fail. Hopefully the majority of projects are relying on Python to do the right thing and just use the `dbm` interface, but we'll know soon which ones aren't.

**Comment by carlocab** [comment]
The `python@3.9` formula currently tests the `gdbm` module using an `import _gdbm` statement. Would that need to go if the `gdbm` dependency is dropped? If it does, what would be the appropriate `import` statement for the equivalent `ndbm` test? Is it just `import dbm`?

**Comment by kaorihinata** [comment]
The import of `_gdbm` would go, yes. If the build process was unable to build NDBM support (either from GDBM, or some other library), then the module you want to load as a test is `_dbm`. That would be the worst case scenario though, as without NDBM support you have to fall back on [dumb](https://docs.python.org/3/library/dbm.html#module-dbm.dumb), which is intended to be an "if all else fails" solution.

**Comment by gromgit** [comment]
> I tried looking up what exactly the difference between `gdbm` and `ndbm` is, but no dice.

They are two different key-value DB implementations. `gdbm` has an optional `ndbm` compatibility API, but the DB files themselves are not compatible, so if we decide to drop `dbm.gnu` support, every user who's been using that module would suddenly have unreadable DBs.

> The question becomes: why are we using gdbm? Would the OS ndbm be as full-featured?

`gdbm` can do everything `ndbm` can, and do the equivalent of an SQL `VACUUM` on the DB. For DBs with a lot of deletions, this can result in significant space reclamation.

The [Python `dbm` interface](https://docs.python.org/3/library/dbm.html) also seems to not support iteration with `ndbm` for some reason, despite [the underlying API's](https://www.mankier.com/0p/ndbm.h) ability to support it.

**Comment by kaorihinata** [comment]
> They are two different key-value DB implementations. `gdbm` has an optional `ndbm` compatibility API, but the DB files themselves are not compatible, ...

I'm not sure if there still exists a reference implementation of NDBM, but these days NDBM mostly refers to the standard POSIX interface (`ndbm.h`), and not a particular implementation. On macOS and FreeBSD the implementation is built-in so you don't have to link in another library, but on most Linux flavors you just have GDBM (typically with compat so you can use the NDBM interface.) As a side note, GDBM hasn't updated their interfaces to match the headers currently published as part of POSIX (`int` versus `size_t`) which is why we're here, really. This issue probably would have never been spotted if they had.

> ...so if we decide to drop `dbm.gnu` support, every user who's been using that module would suddenly have unreadable DBs.

How many users that is is what we're trying to gauge. Currently neither the official Python distribution, or Anaconda include GDBM support out of the box. Of the systems I have available, FreeBSD binary packages do not include GDBM support either. RHEL/CentOS 8.x does, but that's no surprise because GDBM is basically the standard for most Linux distributions. Homebrew does also run on Linux though. I'm just reporting from the macOS/Apple Silicon side.

> The [Python `dbm` interface](https://docs.python.org/3/library/dbm.html) also seems to not support iteration with `ndbm` for some reason, despite [the underlying API's](https://www.mankier.com/0p/ndbm.h) ability to support it.

The entire `dbm` namespace looks quite unfortunate at the source level, and is in dire need of a maintainer, but that's a discussion for another time.

**Comment by gromgit** [comment]
> I'm not sure if there still exists a reference implementation of NDBM

I'm not aware of one either, so I wrote a simple C program to check the macOS implementation on Intel Big Sur:
```sh
$ cat test.c
#include <ndbm.h>

int main() {
  DBM *test_db = dbm_open("test_c", O_RDWR|O_CREAT, 0600);
  datum key = {"foo", sizeof("foo")};
  datum val = {"bar", sizeof("bar")};
        
  dbm_store(db, key, val, DBM_INSERT);
  dbm_close(db); 
  return 0;
}

$ clang test.c

$ ./a.out

$ ls -l
total 68
-rwxr-xr-x 1 aho staff 49544 Dec 27 13:13 a.out
-rw-r--r-- 1 aho staff   242 Dec 27 13:07 test.c
-rw------- 1 aho staff 16384 Dec 27 13:13 test_c.db

$ file test_c.db 
test_c.db: Berkeley DB 1.85 (Hash, version 2, native byte-order)
```

> How many users that is is what we're trying to gauge.

Regardless of how many users that is, dropping GDBM as a dependency will immediately impact _all_ `dbm` users on Intel macOS, because all their existing DBs would still be in GDBM format, _even if they were using the `dbm.ndbm` interface_:
```sh
$ cat test.py
# vim: set fileencoding=utf-8 :

import dbm

with dbm.ndbm.open("test", "c") as db:
    db[b"foo \xbd"] = b"bar \xbd"
with dbm.ndbm.open("test", "r") as db:
    print(list(db.keys()) == [b"foo \xbd"])
    print(b"foo \xbd" in db)
    print(db[b"foo \xbd"] == b"bar \xbd")

$ /usr/local/bin/python3 test.py
True
True
True

$ ls -l
total 24
-rw-r--r-- 1 aho staff    16 Dec 27 13:10 test.dir
-rw-r--r-- 1 aho staff 16384 Dec 27 13:10 test.pag
-rw-r--r-- 1 aho staff   272 Dec 27 13:09 test.py

$ file test.{dir,pag}
test.dir: GNU dbm 2.x database
test.pag: GNU dbm 1.x or ndbm database, little endian, 64-bit
```

**Comment by kaorihinata** [comment]
Yes. By definition there's going to be casualties when you remove a feature. That says nothing about how many people actually rely on the feature that someone is being asked to maintain indefinitely. Nobody is losing access to their data. The gdbm package itself comes with the tools for exporting data from gdbm format databases. If the user wants to convert their database, they can. Alternatively, if Homebrew wants to use `--with-dbmliborder=gdbm` to ensure that Python builds correctly against GDBM (as discussed above), they can. If Homebrew wants to display a message about potentially removing GDBM support in the future to try to gauge user interest, they can. There are a lot of choices here. Removing GDBM as a dependency entirely is just one of them.

**Comment by dtrodrigues** [comment]
Fixed by https://github.com/Homebrew/homebrew-core/pull/67718
