### ISSUE TITLE
pylucene updated (6.20) - bring back from the boneyard?

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-core#6746]
PyLucene recently had an update to 6.20: http://svn.apache.org/repos/asf/lucene/pylucene/tags/pylucene_6_2_0/CHANGES

Suggest it might make sense to bring it back from the boneyard -
homebrew-boneyard/pylucene.rb

**Comment by MikeMcQuaid** [comment]
I think probably not; it's a library and shouldn't have been added in the first place.
