### ISSUE TITLE
vapoursynth 35 - Mavericks

### ISSUE THREAD

**Issue by asoksevil** [Homebrew/homebrew-core#6747]
mpv 0.20 is broken after vapoursynth stopped supporting Mavericks, making it only El Capitan or newer.

I can play video files well if they are locally stored but when I try to stream something, the follow thing appears:

"ffmpeg library versions:
   libavutil       55.28.100 (runtime 55.34.100)
   libavcodec      57.48.101 (runtime 57.64.100)
   libavformat     57.41.100 (runtime 57.56.100)
   libswscale      4.1.100 (runtime 4.2.100)
   libavfilter     6.47.100 (runtime 6.65.100)
   libswresample   2.1.100 (runtime 2.3.100)
ffmpeg version: 3.2

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead."

**Comment by MikeMcQuaid** [comment]
We no longer support Mavericks, I'm afraid. If you can submit a pull request with a fix we'll consider merging it.

**Comment by asoksevil** [comment]
Hi Mike,

Unfortunately I am not that literate using Github...

**Comment by ilovezfs** [comment]
vapoursynth is a non-default option for mpv.

`brew uninstall mpv ; brew install mpv` should fix this for you.

**Comment by asoksevil** [comment]
@ilovezfs Thanks for the tip! Doing it now, will report once it's done!

**Comment by asoksevil** [comment]
How can you install vapoursynth without homebrew? I'm trying to setup SVP 4 Pro on Mac and this command is required: brew install --with-vapoursynth --with-bundle mpv

But I get the following error:
Updating Homebrew...
zimg: macOS El Capitan or newer is required.
vapoursynth: macOS El Capitan or newer is required.
Error: Unsatisfied requirements failed this build.

Thanks

**Comment by ilovezfs** [comment]
@asoksevil to install vapoursynth on Mavericks, you need to patch zimg as here: https://github.com/Homebrew/homebrew-core/pull/4109

I removed the patch subsequently (here: https://github.com/Homebrew/homebrew-core/pull/5710) because upstream does not intend to merge it: https://github.com/sekrit-twc/zimg/issues/52#issuecomment-244628970.

**Comment by asoksevil** [comment]
@ilovezfs Wow, this seems complicated. Isn't there any easier way to do this? How do I "patch" zimg"

Thanks!

**Comment by asoksevil** [comment]
@ilovezfs

I've tried to make it work using home-brew but it won't... is there any "step by step guide"?

Thanks!

**Comment by MikeMcQuaid** [comment]
> I've tried to make it work using home-brew but it won't... is there any "step by step guide"?

There is not, sorry.

**Comment by MikeMcQuaid** [comment]
I'd strongly recommend upgrading your version of macOS to one we officially support (Yosemite and above until Sierra's successor is released).

**Comment by asoksevil** [comment]
Unfortunately, that's something I can't do just right now... Thanks for the reply!

**Comment by solcen** [comment]
Yosemite zimg-release-2.1 install manually to cellar
Download & unarchive to any directory https://codeload.github.com/sekrit-twc/zimg/tar.gz/release-2.1
open terminal type 'cd' and pull directory to command line, press enter.
Type one-by-one
```
./autogen.sh
./configure --prefix=/usr/local/Cellar/zimg/2.1
make
make install
brew link zimg
```
