### ISSUE TITLE
aws-sdk-cpp uses system libcurl rather than homebrew version

### ISSUE THREAD

**Issue by xanather** [Homebrew/homebrew-core#67514]
# Bug report

brew install works, below is not applicable...
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Linking and running against the aws-sdk-cpp homebrew library.

## What happened (include command output)

Because I use libcurl using homebrew when I make the call ::curl_easy_perform() to within my application the program aborts with EXEC_BAD_ACCESS (segfault) due to OpenSSL conflicting with the CommonCrypto libraries which aws-sdk-cpp is loading.

## What you expected to happen

Not throw a EXEC_BAD_ACCESS.

## Step-by-step reproduction instructions (by running `brew install` commands)

This is a multithreading issue, I shouldn't be too hard to replicate if you look at https://github.com/aws/aws-sdk-cpp/issues/961. All I did was call ::curl_easy_perform and it crashes every time once aws-sdk-cpp-core.dylib is linked.

Using these options to link against homebrew's libcurl should fix it: -DCURL_INCLUDE_DIR=/opt/local/include/curl -DCURL_LIBRARY=/opt/local/lib/libcurl.dylib -DENABLE_COMMONCRYPTO_ENCRYPTION=OFF -DENABLE_OPENSSL_ENCRYPTION=ON as part of the Formula.

**Comment by carlocab** [comment]
Thanks for the report, @xanather.

Can you provide a minimal C++ program that makes a call to `::curl_easy_perform()`? I can update the formula with new build instructions, but I'd also like to update the test to catch linkage failures in the future.

**Comment by carlocab** [comment]
Thanks for the report, @xanather.

It looks like `aws-sdk-cpp` is meant to link against system curl and not Homebrew curl. Is there any reason why this should be changed?

**Comment by xanather** [comment]
Hi @carlocab, I wasn't sure if homebrew should be linking against its own libraries as a preference or not. If this is not the case then no worries feel free to close this issue.

I will follow up in https://github.com/aws/aws-sdk-cpp/issues/961 for it to just work out of the box then, if homebrew were to use homebrew's OpenSSL/libcurl packages to avoid dylib duplication at runtime then that would indirectly resolve this crashing.

Let me know if changing to link against homebrew dylib's is preferred, if yes I can create a small C++ application which crashes on the first call to ::curl_easy_perform() so that it can be verified that it works after switching the dependencies.

Cheers,
Jordan

**Comment by carlocab** [comment]
If something's provided by macOS, then we use that unless there are good reasons not to.

If you find good reasons for `aws-sdk-cpp` to link against Homebrew `curl` rather than system `curl`, please open a PR to update the formula so it can be reviewed.

There's nothing actionable here at the moment, so I'm closing this for now.
