### ISSUE TITLE
go 1.7.1 fails to upgrade to 1.7.3 on macos sierra

### ISSUE THREAD

**Issue by guandalf** [Homebrew/homebrew-core#6755]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

==> Upgrading 4 outdated packages, with result:
go 1.7.3, godep 75, node 7.0.0, vim 8.0.0071
==> Upgrading go
==> Downloading https://homebrew.bintray.com/bottles/go-1.7.3.sierra.bottle.tar.gz
Already downloaded: /Users/stefano.guandalini/Library/Caches/Homebrew/go-1.7.3.sierra.bottle.tar.gz
==> Pouring go-1.7.3.sierra.bottle.tar.gz
Error: undefined method `dylib_load_commands' for #<MachO::FatFile:0x007fe334978758>
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://storage.googleapis.com/golang/go1.7.3.src.tar.gz
Already downloaded: /Users/stefano.guandalini/Library/Caches/Homebrew/go-1.7.3.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.7.darwin-amd64.tar.gz
Already downloaded: /Users/stefano.guandalini/Library/Caches/Homebrew/go--gobootstrap-1.7.tar.gz
==> ./make.bash --no-clean
==> /usr/local/Cellar/go/1.7.3/bin/go install -race std
==> Cloning https://go.googlesource.com/tools.git
Updating /Users/stefano.guandalini/Library/Caches/Homebrew/go--gotools--git
==> Checking out branch release-branch.go1.7
==> go build
Error: undefined method `dylib_load_commands' for #<MachO::FatFile:0x007fef67176868>
Please report this bug:
  https://git.io/brew-troubleshooting

`brew gist-logs <formula>`
https://gist.github.com/12a963b8361f4aa1f33fadf0c27f8b38

**Comment by MikeMcQuaid** [comment]
`brew update` and should be fixed. Sorry about this!
