### ISSUE TITLE
Qt v5.7.0 Still Fails to Build on OS X v10.11.6 'El Capitan' After Resolution of Issue #6032

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#6766]
### Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] ~~If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?~~  N/A

### Bug reports:

The resolution of [Issue #6032:  'qt5 fails to build with mysql support'](https://github.com/Homebrew/homebrew-core/issues/6032) did not make it so that I am able to build Qt v5.7.0.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/Qt/v5.7.0/Third%20Recorded%20Attempt) are my logs.  Note that they again include one or more notices of a violation or more of Homebrew's build sandbox.  I also saw some warnings flash by during the build when I peeked at it, so those might be relevant as well, but I'm not sure.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Could the issues I'm seeing here perhaps be related to how Homebrew Core had to add some patches originally used for Qt v5.6.1 (and _maybe_ v5.7.1-1…?) back for v5.7.0 of the software after they were removed from the edition of `qt5.rb` that propagated Qt v5.6.2 to Homebrew users?  Could you (and/or anybody else involved) have possibly forgotten to add a patch back, or am I just grasping at straws here?

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel I realise you may not have the patience but can you try to remove options one-by-one to figure out which one(s) are broken? I'm really tempted to remove options from the Qt5 formula (maybe all of them).

**Comment by MikeMcQuaid** [comment]
For discussion: Qt5 installs in the last month with their options:

<img width="833" alt="screen shot 2016-11-10 at 10 33 25" src="https://cloud.githubusercontent.com/assets/125011/20173426/2d2c30f6-a731-11e6-9db0-9518b22b44db.png">

I'd propose from this that we make `--with docs --with-examples` (and maybe even `--with-qtwebkit`) the default and remove `--with-mysql` and `--with-postgresql` options.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  
> @RandomDSdevel I realise you may not have the patience…

Heh, you've got _that_ right.  Have I ever mentioned how insanely _long_ (roughly at least 8-10 hours, in my experience,) it takes to build Qt on my setup?  (I think I probably have, but there it is again just for reference.)  

> …but can you try to remove options one-by-one to figure out which one(s) are broken?  …

Perhaps I might consider it if you (or @ilovezfs or @apjanke, who have also been involved in helping to figure out and resolve Qt compilation hiccups before) can't reproduce my build failure on another machine, but, like I implied above, I'd…really rather _not_ have to subject myself to such torture if I don't have to, thank you very much.  I wouldn't mind testing a patch _once_ prior to its inclusion in Homebrew Core proper if it fixes the issues I'm seeing right away, though, since I wouldn't have to rebuild Qt once said change(s) got pulled into `master`.  

> …I'm really tempted to remove options from the Qt5 formula (maybe all of them).

That might end up being better saved for another PR, as I'd like to see if we could get the errors I've been seeing locally fixed first.  

<hr />

@MikeMcQuaid:  
> For discussion: Qt5 installs in the last month with their options:
> 
> ![Screenshot of Homebrew `qt5.rb` Formula Option Usage Statistics](https://cloud.githubusercontent.com/assets/125011/20173426/2d2c30f6-a731-11e6-9db0-9518b22b44db.png)
> 
> I'd propose from this that we make [`--with-docs`] `--with-examples` (and maybe even `--with-qtwebkit`) the default and remove `--with-mysql` and `--with-postgresql` options.  

Yeah, this reinforces my impression that this should be held off for another PR lest we invoke the wrath of any members of any of the possibly vocal minorities that use those options (_some_ of whom, as you might similarly recall, reared their ugly heads in the mess that I accidentally dumped here in Homebrew Core with the creation of [Issue #6032, 'qt5 fails to build with mysql support'](https://github.com/Homebrew/homebrew-core/issues/6032)&thinsp;—&thinsp;sorry about that, by the way…)  Besides, I did a brief perusal of the logs I first posted when I originally created this issue, and what I saw there leads me to suspect that the problems I'm experiencing here are, in any case, _probably_ symptoms of a reoccurrence of [Issue #1948, 'Qt 5.6.1 fails to build with '--with-examples''](https://github.com/Homebrew/homebrew-core/issues/1948)

**Comment by ilovezfs** [comment]
@RandomDSdevel should be fixed by https://github.com/Homebrew/homebrew-core/pull/6825/commits/d7042b2a1bd90d09e60e95cc276c4a2ea5b105ae.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Ah, wonderful!  Sorry for all the trouble.

**Comment by apjanke** [comment]
Yeah, I was able to reproduce this failure with just `brew install -s qt5 --with-examples`. (The build "only" takes an hour on my machine.) So that PR should cover this.

**Comment by RandomDSdevel** [comment]
@apjanke:  Of course; I've just been multitasking and doing other, non-Homebrew updates while talking with you guys about this over the past little while.  I'm running `brew update` now, though, so here goes!

**Comment by ilovezfs** [comment]
@RandomDSdevel to be clear, that PR isn't merged yet, so brew update isn't going to do much.

**Comment by apjanke** [comment]
> I'd propose from this that we make `--with docs --with-examples` (and maybe even `--with-qtwebkit`) the default and remove `--with-mysql` and `--with-postgresql` options.

Removing options like this makes a lot of sense, IMHO, given their usage numbers. Even on a top-end Mac, the build takes an hour, so testing combinations of options is pretty untenable.

**Comment by ilovezfs** [comment]
@apjanke I think if there's any controversy, it'll be over the removal of the mysql and postgresql options.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  
> @RandomDSdevel to be clear, that PR isn't merged yet, so brew update isn't going to do much.

Oh, right.  My bad, sorry.  I'll just wait until it _is_ merged to update Qt 5, then.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Could we possibly split the changes in that PR that are relevant to this issue out of it into a separate one so that I can get building Qt over with?

**Comment by ilovezfs** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/pull/6844.

**Comment by RandomDSdevel** [comment]
@ilovezfs:  Thank you very much!

**Comment by ilovezfs** [comment]
@RandomDSdevel you're welcome Bryce!
