### ISSUE TITLE
Investigate formulas marked as `depends_on arch: :x86_64`

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#67688]
There are 5 such formulas at the time when Apple Silicon support is introduced:

```
appledoc.rb:  depends_on arch: :x86_64
cryptominisat.rb:  depends_on arch: :x86_64
pypy.rb:  depends_on arch: :x86_64
pypy3.rb:  depends_on arch: :x86_64
sslyze.rb:  depends_on arch: :x86_64
```

Those were originally introduced during the 32 to 64-bit Intel transition on Apple hardware, to mark formulas that were exclusive to 64-bit processors. They need to be inspected to see if they can run on Apple Silicon (arm64) or not, and the dependency removed if possible.

**Comment by mitchblank** [comment]
The appledoc one was added by me just this week -- the "source" tarball includes some `.a` files which are intel-only

**Comment by fxcoudert** [comment]
> the "source" tarball includes some .a files

That's not acceptable, though 😢

**Comment by mitchblank** [comment]
Hey, I'm just the messenger :-)

Looks like it was removed and revivied once already:
```
237bd8fbbd - appledoc 2.2.1 (new formula) (5 years ago) <Adam Demasi>
10e9235860 - Move appledoc to boneyard (7 years ago) <Adam Vandenberg>
```

The project does seem dead, though, and the program has some functionality broken on recent xcode anyway due to https://github.com/tomaz/appledoc/issues/628

**Comment by fxcoudert** [comment]
pypy and pypy3 are not available on ARM, so the arch specification there is correct: https://morepypy.blogspot.com/2020/12/mac-meets-arm64.html

**Comment by iMichka** [comment]
Regarding pypy: https://morepypy.blogspot.com/2020/12/mac-meets-arm64.html

> So, now all the factors are on the table. We won't do the minimal "just the JIT compiler fixes" if we don't have a plan that goes farther. Either we get sufficient money, and maybe support, and then we can do it quickly; or PyPy will just remain not natively available on M1 hardware for the next 3-5 years.
