### ISSUE TITLE
PHP extensions on Apple Silicon

### ISSUE THREAD

**Issue by nauxliu** [Homebrew/homebrew-core#67768]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install PHP extensions using PECL on M1 Mac

## What happened (include command output)

Because homebrew changed its dir from `/usr/local` to `/opt/homebrew`, php extensions unable to locate its dependencies. they usually only look in `/usr/local /usr /opt`

for example, `pecl install yaml`

<details>
  <summary>Command output</summary>
  <pre>
checking if awk is broken... no
checking whether to enable LibYAML suppot... yes, shared
checking for yaml headers... not found
configure: error: Please install libyaml
ERROR: `/private/tmp/pear/temp/yaml/configure --with-php-config=/opt/homebrew/opt/php@7.4/bin/php-config --with-yaml' failed
  </pre>
</details>

## What you expected to happen

Being able to install PHP extensions without any problem.

Is there any magic we can do with homebrew to work around this issue instead of patching every extension to add `/opt/homebrew` to their include paths?

**Comment by carlocab** [comment]
`pecl` is not a Homebrew formula, so I'm not sure there's anything we can do about this here. You'll have to file this report upstream.

**Comment by nauxliu** [comment]
pecl is come with the formula `php`

**Comment by nauxliu** [comment]
I guess maybe we can somehow change the php-config prefix in the formula to work around this, but I'm not sure, can we keep this issue open for discussion.

**Comment by carlocab** [comment]
My mistake. Apologies. I've looked at the formula, and it seems to be doing the right thing about setting search paths.

What change do you propose regarding the php-config prefix?

**Comment by SMillerDev** [comment]
> pecl is come with the formula php

Does it still come with the latest one? I don't think it should since pecl is deprecated.

**Comment by fxcoudert** [comment]
`pecl` is in `php@7.4`
