### ISSUE TITLE
makensis bottle missing for Linux (Ubuntu 20.04, 16.04, etc)

### ISSUE THREAD

**Issue by rfay** [Homebrew/homebrew-core#67825]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/rfay/cb6b730b5336bf53069a96390e9bf6ec
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install makensis on Linux (Ubuntu 20.04, Ubuntu 16.04)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

rfay@ubuntu-20-04:~$ brew install makensis
Error: makensis: no bottle available!
You can try to install from source with e.g.
  brew install --build-from-source makensis

  </pre>
</details>

## What you expected to happen

Install makensis

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install makensis`

Notes: There is in fact a bottle still for Catalina  and higher.

**Comment by gromgit** [comment]
You should probably request for a bottle over on the Linuxbrew repo: https://github.com/Homebrew/linuxbrew-core/issues/new/choose

**Comment by rfay** [comment]
Moved to https://github.com/Homebrew/linuxbrew-core/issues/21968
