### ISSUE TITLE
Python@3.9 postinstall fails due to partial pip install instructions

### ISSUE THREAD

**Issue by lazarillo** [Homebrew/homebrew-core#67851]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ o ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upon first upgrading to `python@3.9`, I had issues that required a `postinstall` be run.  I eventually fixed the problem by just properly reinstalling `python@3.9`, but I still thought it useful to highlight this failed `postinstall`.

Python is my main language, and I use `conda` to manage python environments.  (Therefore, this Homebrew Python install is not critical for my work.)

Command:

`brew update`
`brew install python@3.9`
`brew postinstall python@3.9`

## What happened (include command output)

The command actually just hangs.  I have left it running for overnight, still hanging.

<details>
  <summary>Command output</summary>
  <pre>

❯ brew postinstall python@3.9
==> Postinstalling python@3.9
==> /usr/local/Cellar/python@3.9/3.9.1_2/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.1_2/bin/pip3 install -v --global-option=--no-user-cfg --install-option=--force --install-option=--single-version-

  </pre>
</details>
(Then it just hangs here, no further progress or output.)

Notice that the second line is cut off:  it should not end with `--install-option=--single-version-`.  Unfortunately, I do not know what the entire line should be.

## What you expected to happen

The `python@3.9` post-install should gracefully complete.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew update`
`brew install python@3.9`
`brew postinstall python@3.9`

## `brew config` and `brew doctor` output

`brew config`:

```bash
❯ brew config              
HOMEBREW_VERSION: 2.7.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 993bf95877143afe1cede022083499e0b4fe336c
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 08f45d678444b9d992d8e40d82a528680b9e5310
Core tap last commit: 36 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.P9RcOCYEsn/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nano
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.2, 13, 1.8.0_275
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

`brew doctor`:

I recognize there are several issues below, but most of this is due to conflicts that would be worse if I adjusted any of `brew doctor`'s recommendations.  Most notably, `brew` and `conda` get along only at a distance, so I ensure that any Homebrew and Conda environments are separated as much as possible.

```bash
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/python3.9-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
  /usr/local/Caskroom/miniconda/base/bin/ncurses6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libctxfuse.dylib
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a
```

**Comment by fxcoudert** [comment]
> Most notably, brew and conda get along only at a distance, so I ensure that any Homebrew and Conda environments are separated as much as possible

Agreed, and for this reason I would recommend not to have conda anywhere in your `PATH` (or other environment variables) when running brew commands, especially those that are python-related.

**Comment by lazarillo** [comment]
@fxcoudert What is an easy way to do this?  Is there a quick command to filter out my path before running it?  Ie, when I perform `conda activate <myenv>`, this actually alters my `$PATH` environment variable.  I would like to create a simple (zsh) means to alter my path so that, for instance, I could do something like:

`fixpath.sh; brew`

and then put an alias like: `alias fixedbrew='~/fixpath.sh; brew'`, so that I could simply do actions like `fixedbrew update` and `fixedbrew upgrade`.

---

Regardless, I do not think this is actually the issue here.  I think something else is preventing Python 3.9 from installing properly.  Notice how the command to install Python is incomplete, and therefore incorrect.  This is not due to anything going on with `conda`, at least not in any way I can imagine.

**Comment by fxcoudert** [comment]
> Notice how the command to install Python is incomplete

I think it's just brew truncating the command it's running, unless you run with `-v`.

**Comment by lazarillo** [comment]
Oh, that could be it.  I didn't realize it would truncate commands ever, I haven't noticed that before.

It is hard for me to duplicate the error to verify, and I do not want to re-break my Python setup to verify.  This has not happened on any other minor releases, so I guess I won't worry about it until I see it happen again on Python 3.10, or whatever the new naming will be.  (I heard something about using date versioning instead of semver.)

**Comment by fxcoudert** [comment]
OK, I'll close this then
