### ISSUE TITLE
Question about uses_from_macos

### ISSUE THREAD

**Issue by Yann-R** [Homebrew/homebrew-core#67904]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Please forgive if it is not the right place to ask this question.
I am currently writing my own formula for brew that installs a wrapper script from the web, that is useful for me and my colleagues.
This script uses `a2ps` (from homebrew) and `iconv`(from macOS).

So I added the following two lines:
```
  depends_on "a2ps"
  uses_from_macos "iconv"
```

## What happened (include command output)

Nevertheless, when I run `brew audit myformula.rb`, I get:
```
  * 9: col 3: `uses_from_macos` should only be used for macOS dependencies, not iconv.
```

## What you expected to happen

I thought specifying `iconv`was a good idea:
- Why do I get this warning?
- Is there a better solution to set the fact that this relies on the necessary `iconv`?

Thank you for any piece of advice.

**Comment by carlocab** [comment]
`uses_from_macos` is actually a [no-op](https://rubydoc.brew.sh/Formula.html#uses_from_macos-class_method) on macOS. It's there to facilitate compatibility with Linux.

In any case, I suspect what you're looking for is `uses_from_macos "libiconv"`.

**Comment by Yann-R** [comment]
Great, many thanks.
(and another thank you for the link to discussions that I didn't knew as admitted at the beginning of my message. Perfect!)
