### ISSUE TITLE
Pidgin bottle is broken, looks like a rebuild is needed

### ISSUE THREAD

**Issue by grimmy** [Homebrew/homebrew-core#67922]
# Bug report

I received an [upstream report](https://issues.imfreedom.org/issue/PIDGIN-17448) complaining that pidgin fails to load with the following message:

```
dyld: Symbol not found: _g_cclosure_marshal_VOID__BOOLEAN
Referenced from: /usr/local/bin/pidgin
Expected in: /usr/local/opt/gtk+/lib/libgtk-quartz-2.0.0.dylib
in /usr/local/bin/pidgin
```

I reinstalled pidgin with `brew reinstall -s pidgin` and it works properly.

So it appears that something got messed up linker wise and `libgtk-quartz` isn't linking to `glib` directly anymore or something.  I didn't go to far down the path, as a rebuild just fixes the issue for my user.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

User installed Pidgin via bottle (as did I), it fails to start with the above message.

## What happened (include command output)

Running `pidgin` from the command line fails to start with following message:

<details>
  <summary>Command output</summary>
  <pre>

  
dyld: Symbol not found: _g_cclosure_marshal_VOID__BOOLEAN
Referenced from: /usr/local/bin/pidgin
Expected in: /usr/local/opt/gtk+/lib/libgtk-quartz-2.0.0.dylib
in /usr/local/bin/pidgin
  </pre>
</details>

## What you expected to happen

The program to start...

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install pidgin
$ pidgin
```

Issue is solved by installing from source with `brew install -s pidgin`.

**Comment by jonchang** [comment]
Interesting, I wasn't aware that we shipped `pidgin` in addition to `finch`. I'll rebuild the formula and add a test for this (which is why we missed it when updating `gtk+`).
