### ISSUE TITLE
Incorrect dependency processing

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/homebrew-core#67939]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Remove python@3.8 as I no longer need it

## What happened (include command output)

It was not removed because of supposed dependencies on python@3.8

<details>
  <summary>Command output</summary>
  <pre>
brew uninstall python@3.8                                 
Error: Refusing to uninstall /usr/local/Cellar/python@3.8/3.8.6_2
because it is required by adwaita-icon-theme, atk, cairo, graphviz, gsettings-desktop-schemas, liblqr, qemu, rrdtool, shared-mime-info and suite-sparse, which are currently installed.
  </pre>
</details>

However, after reinstalling all of these with 
<pre>
brew reinstall adwaita-icon-theme atk cairo graphviz gsettings-desktop-schemas liblqr qemu rrdtool shared-mime-info suite-sparse
</pre>
then
<pre>
brew uninstall python@3.8
</pre>
worked as expected.

## What you expected to happen

It would seem that these packages don't really depend on python@3.8, so it should let me remove it.

## Step-by-step reproduction instructions (by running `brew install` commands)

Not really possible. I installed the above packages a long time ago, presumably while python@3.8 was the current python. Since then python@3.9 has come along. It's quite possible the formulae for these packages have changed too in the meantime. But if you still have python@3.8 on your system, I guess there is a good chance some packages on your system will prevent its uninstallation in a similar way.

<pre>
ralph@air ~ $ brew config              
HOMEBREW_VERSION: 2.7.1-40-gc54acef
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c54acefab31e2e4b03242d8143f90f164e28393c
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 199f9f5b53b55c98d3fb49763a852e1864ddd7bc
Core tap last commit: 72 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 0
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.m4dYB8FuIH/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /usr/local/bin/emacs
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.74.0 => /usr/local/opt/curl/bin/curl
Java: 15.0.1, 1.8.271.09, 1.8.0_271
macOS: 11.1-x86_64
CLT: N/A
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
ralph@air ~ $ brew doctor               
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ext4fuse
  ntfs-3g
  sshfs

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.dylib
  /usr/local/lib/libchkp.dylib
  /usr/local/lib/libghdlvpi.dylib
  /usr/local/lib/libifcore.dylib
  /usr/local/lib/libifcoremt.dylib
  /usr/local/lib/libifport.dylib
  /usr/local/lib/libifportmt.dylib
  /usr/local/lib/libimf.dylib
  /usr/local/lib/libintlc.dylib
  /usr/local/lib/libiompstubs5.dylib
  /usr/local/lib/libirc.dylib
  /usr/local/lib/libirng.dylib
  /usr/local/lib/libjlinkpic32.6.34.6.dylib
  /usr/local/lib/libjpeg.8.dylib
  /usr/local/lib/libmkl_avx.dylib
  /usr/local/lib/libmkl_avx2.dylib
  /usr/local/lib/libmkl_avx512.dylib
  /usr/local/lib/libmkl_blacs_mpich_ilp64.dylib
  /usr/local/lib/libmkl_blacs_mpich_lp64.dylib
  /usr/local/lib/libmkl_cdft_core.dylib
  /usr/local/lib/libmkl_core.dylib
  /usr/local/lib/libmkl_intel_ilp64.dylib
  /usr/local/lib/libmkl_intel_lp64.dylib
  /usr/local/lib/libmkl_intel_thread.dylib
  /usr/local/lib/libmkl_mc.dylib
  /usr/local/lib/libmkl_mc3.dylib
  /usr/local/lib/libmkl_rt.dylib
  /usr/local/lib/libmkl_scalapack_ilp64.dylib
  /usr/local/lib/libmkl_scalapack_lp64.dylib
  /usr/local/lib/libmkl_sequential.dylib
  /usr/local/lib/libmkl_tbb_thread.dylib
  /usr/local/lib/libmkl_vml_avx.dylib
  /usr/local/lib/libmkl_vml_avx2.dylib
  /usr/local/lib/libmkl_vml_avx512.dylib
  /usr/local/lib/libmkl_vml_mc.dylib
  /usr/local/lib/libmkl_vml_mc2.dylib
  /usr/local/lib/libmkl_vml_mc3.dylib
  /usr/local/lib/libnettle.6.3.dylib
  /usr/local/lib/libpspell.15.dylib
  /usr/local/lib/libsvml.dylib
  /usr/local/lib/libtbb.12.1.dylib
  /usr/local/lib/libtbb.12.dylib
  /usr/local/lib/libtbb.dylib
  /usr/local/lib/libtbbmalloc.2.1.dylib
  /usr/local/lib/libtbbmalloc.2.dylib
  /usr/local/lib/libtbbmalloc.dylib
  /usr/local/lib/libtbbmalloc_proxy.2.1.dylib
  /usr/local/lib/libtbbmalloc_proxy.2.dylib
  /usr/local/lib/libtbbmalloc_proxy.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/vpi_user.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cmake
</pre>

**Comment by Rylan12** [comment]
You may want to check out https://github.com/Homebrew/brew/issues/10173 if you haven't already. It looks like it was somewhat prompted by this issue and might contain some insight into why this happened.

> I installed the above packages a long time ago, presumably while python@3.8 was the current python. Since then python@3.9 has come along. It's quite possible the formulae for these packages have changed too in the meantime.

Based on my quick reading of https://github.com/Homebrew/brew/issues/10173. I'd bet that this is exactly the issue. It's possible that a `brew upgrade` would have helped (not sure if you tried that or not).

Since the issue seems to have been resolved and there's a solution for anyone who may come across this in the future, I'm going to close this.
