### ISSUE TITLE
poppler has internal links to /usr/local/Cellar ... which messes with deployment tool macdeployqt

### ISSUE THREAD

**Issue by sunderme** [Homebrew/homebrew-core#67950]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am making app bundles with qt and poppler. For this I use "macdeployqt" to copy dependencies into the bundle and change the internal dylib links.

## What happened (include command output)

The links of libpoppler-qt5...dylib to libpoppler.dylib is not changed properly.
The cause is that libpoppler-qt5... links to "/usr/local/Cellar/poppler/20.12.1/lib/libpoppler.105.dylib"  instead of "/usr/local/opt/poppler/lib/libpoppler.105.dylib" which apparently confuses macdeployqt

<details>
  <summary>Command output</summary>
  <pre>

  otool -L libpoppler-qt5.1.26.0.dylib
libpoppler-qt5.1.26.0.dylib:
	/usr/local/opt/poppler/lib/libpoppler-qt5.1.dylib (compatibility version 1.0.0, current version 1.26.0)
	/usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.15.0, current version 5.15.2)
	/usr/local/opt/qt/lib/QtXml.framework/Versions/5/QtXml (compatibility version 5.15.0, current version 5.15.2)
	/usr/local/opt/freetype/lib/libfreetype.6.dylib (compatibility version 24.0.0, current version 24.4.0)
	/usr/local/Cellar/poppler/20.12.1/lib/libpoppler.105.dylib (compatibility version 105.0.0, current version 105.0.0)
	/usr/local/opt/little-cms2/lib/liblcms2.2.dylib (compatibility version 3.0.0, current version 3.10.0)
	/usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.2)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

  </pre>
</details>

## What you expected to happen

all links to go to /usr/local/opt... (where appropriate)

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install poppler
otool -L /usr/local/opt/poppler/lib/libpoppler-qt5.dylib

You can also compile texstudio and use macdeployqt. The error becomes apparent when running that bundle on a non-homebred machine.

## further remarks
I have tweaked a local poppler.rb to handle the links better but that is not necessarily the best option.

`libpoppler = (lib/"libpoppler.dylib").readlink
    ["#{lib}/libpoppler-cpp.dylib", "#{lib}/libpoppler-glib.dylib", "#{lib}/libpoppler-qt5.dylib", 
     *Dir["#{bin}/*"]].each do |f|
      macho = MachO.open(f)
      lst=macho.linked_dylibs()
      lst.each do |ln|
        if ln.match(/^@rpath/)
          macho.change_dylib(ln, ln.gsub("@rpath","/usr/local/opt/poppler/lib"))
        end
      end
      macho.write!
    end`

**Comment by fxcoudert** [comment]
> ran brew config and brew doctor and included their output with your issue?

Please do

**Comment by sunderme** [comment]
```
%brew config

HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 29 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: da9cb388701d6703e0cf80279c6ee5f394c33aac
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 11.0 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 1103.0.32.59
Xcode: 11.6

% brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Your Xcode (11.6) is outdated.
Please update to Xcode 12.3 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by fxcoudert** [comment]
I'm wondering if passing `cmake` an argument like `-DCMAKE_INSTALL_RPATH=#{lib}` might help, instead of tweaking the dylibs like we're doing.
