### ISSUE TITLE
llvm codesign test fails due to --dryrun flag (segfault)

### ISSUE THREAD

**Issue by kemlath** [Homebrew/homebrew-core#680]
# Please follow the general troubleshooting steps first:

- [ X] Ran `brew update` and retried your prior step?

### Bug reports:

in llvm.rb code signing is tested via

quiet_system "/usr/bin/codesign", "-s", "lldb_codesign", "--dryrun", "llvm_check.txt"

this results in codesign segfaulting under in os x 10.11.4  due to the --dryrun flag(don't know why)
and the installation being aborted by brew

replacing this by 

quiet_system "/usr/bin/codesign", "-s", "lldb_codesign", "llvm_check.txt"

solves the issue an llvm compiles without problems (but results in "llvm_check.txt" to become actually signed) If the signature lldb_codesign is created in the login keychain as suggested by the llvm build manual no password is required for the above call.

### Formula Requests:

remove the "--dryrun" entry

**Comment by DomT4** [comment]
Oh, someone filed a PR over this a while ago. I'll set aside some time tonight to test this and fix that. It seems to be something introduced by OS X 10.11.3.

**Comment by DomT4** [comment]
Should be fixed via https://github.com/Homebrew/homebrew-core/commit/535e2565f3918ddcabc67ebce8cf9ceea245bb0c.
