### ISSUE TITLE
glew-targets.cmake points to wrong OpenGL location on MacOS Big Sur

### ISSUE THREAD

**Issue by jnbrunet** [Homebrew/homebrew-core#68038]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

**NOTE**: This is exactly the same issue as https://github.com/Homebrew/homebrew-core/issues/47813 , but this time with _/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk_ (which doesn't exist, MacOSX11.1.sdk does however). I can not however reopen this issue so I'm creating this one.

Compile a CMake/C++ project using glew with macOS Big Sur (SDK 11.1)

## What happened (include command output)

The CMake target file of **glew** (_/usr/local/lib/cmake/glew/glew-targets.cmake_) installed using a brew bottle, ie `brew install glew`, have a hard coded absolute path dependency to OpenGL.Framwork in _/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk_, but the last update of MacOS replaced  `MacOSX11.0.sdk` by `MacOSX11.1.sdk`.

<details>
  <summary>Command output</summary>
  <pre>

  ninja: error: '/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks/OpenGL.framework', needed by 'test_glew', missing and no known rule to make it

  </pre>
</details>

## What you expected to happen

Compilation success using _/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk_ which is a symbolic link to the latest installed version of the SDK.

## Step-by-step reproduction instructions (by running `brew install` commands)

I've tested it on my macbookpro Big Sur, and also with a clean Big Sur virtual machine. The following steps will reproduce the bug:

1. Make sure the MacOS is Big Sur and the command line tools are installed and up-to-date (i.e. _/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk_ should point towards _/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk_ or higher.
2. Install **glew** using `brew install glew`
3. Create the following CMake/C++ project:
**CMakeLists.txt**
```cmake
 project(test_glew)                                                                                                    |   #include <string>
                                                                                                                       |   #include <GL/glew.h>
 find_package(OpenGL REQUIRED)                                                                                         |
 find_package(GLEW REQUIRED)                                                                                           |
                                                                                                                       |   const char* GetGlExtensionsList()
 add_executable(${PROJECT_NAME} main.cpp)                                                                              |   {
                                                                                                                       |       return reinterpret_cast<const char*>(glGetString(GL_EXTENSIONS));
 target_link_libraries(${PROJECT_NAME} PUBLIC OpenGL::GL GLEW::GLEW)
```
**main.cpp**
```c++
#include <GL/glew.h>

int main() {
    return 0;
}
```
4. Run `cmake . && make`

## `brew config` and `brew doctor` output

```sh
$ brew config
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 641370ad6392b4a8421c66ad5448554e254387cd
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
```

```sh
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

**Comment by carlocab** [comment]
Thanks for the report. This should be fixed now.
