### ISSUE TITLE
gdal -  linked with incorrect libdap  -  Big Sur

### ISSUE THREAD

**Issue by dwcaress** [Homebrew/homebrew-core#68049]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
        Ran 'brew gist-logs' on libdap, gdal, and gmt. All results were "Error: No logs.".
- [X ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install and use gmt  on MacBook Pro  running  up-to-date  Big Sur.

## What happened (include command output)

   caress@Haxby ~ % gmt
   dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
   Referenced from: /usr/local/opt/gdal/lib/libgdal.28.dylib
   Reason: image not found
    zsh: abort      gmt

    caress@Haxby ~ % gdalwarp
    dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
   Referenced from: /usr/local/bin/gdalwarp
   Reason: image not found
   zsh: abort      gdalwarp

It appears that gdal is linked with an incorrect version of libdap, as the libdap actually installed is:
caress@Haxby ~ % ls -l /usr/local/opt/libdap/lib/libdap*
-r--r--r--  1 caress  staff  1547192 Dec 30 13:04 /usr/local/opt/libdap/lib/libdap.27.dylib
-r--r--r--  1 caress  staff  2949784 Dec 29 11:05 /usr/local/opt/libdap/lib/libdap.a
lrwxr-xr-x  1 caress  staff       15 Dec 29 11:05 /usr/local/opt/libdap/lib/libdap.dylib -> libdap.27.dylib
-rw-r--r--  1 caress  staff   269920 Dec 30 13:04 /usr/local/opt/libdap/lib/libdapclient.6.dylib
-r--r--r--  1 caress  staff   373536 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapclient.a
lrwxr-xr-x  1 caress  staff       20 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapclient.dylib -> libdapclient.6.dylib
-r--r--r--  1 caress  staff    99368 Dec 30 13:04 /usr/local/opt/libdap/lib/libdapserver.7.dylib
-r--r--r--  1 caress  staff    65648 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapserver.a
lrwxr-xr-x  1 caress  staff       20 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapserver.dylib -> libdapserver.7.dylib

## What you expected to happen

Gmt and gdalwarp to execute normally

## Step-by-step reproduction instructions (by running `brew install` commands)

- MacBook Pro 15 inch 2017  running  up to date Big Sur and Xcode.
- Completely delete prior Homebrew installation, including deleting all directories under /usr/local.
- Install homebrew -  no obvious problems
- Run 'brew install gmt'  -  no obvious  problems
- Attempt to execute gmt and gdalwarp:

   caress@Haxby ~ % gmt
   dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
   Referenced from: /usr/local/opt/gdal/lib/libgdal.28.dylib
   Reason: image not found
    zsh: abort      gmt
    caress@Haxby ~ % gdalwarp
    dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
   Referenced from: /usr/local/bin/gdalwarp
   Reason: image not found
   zsh: abort      gdalwarp

Output of 'brew config':
-----------------------
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: dd0275f67740fa2011b0ee85bbaab57e1c83ee59
Core tap last commit: 17 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.DWcvQ6pvgn/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.192.12, 1.8.0_192
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11

Series of commands and results using 'brew doctor':
-----------------------------------------
Last login: Wed Dec 30 12:30:20 on ttys000
caress@Haxby ~ % gmt
dyld: Library not loaded: /usr/local/opt/gdal/lib/libgdal.28.dylib
  Referenced from: /usr/local/bin/gmt
  Reason: image not found
zsh: abort      gmt
caress@Haxby ~ % 
caress@Haxby ~ % 
caress@Haxby ~ % brew update
Already up-to-date.
caress@Haxby ~ % brew  doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdal

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/opt/gdal
caress@Haxby ~ % brew  cleanup
Warning: Skipping gdal: most recent version 3.2.0_1 not installed
Pruned 1 symbolic links and 5 directories from /usr/local
caress@Haxby ~ % gmt
dyld: Library not loaded: /usr/local/opt/gdal/lib/libgdal.28.dylib
  Referenced from: /usr/local/bin/gmt
  Reason: image not found
zsh: abort      gmt
caress@Haxby ~ % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gdal
caress@Haxby ~ % brew link gdal
Linking /usr/local/Cellar/gdal/3.2.0_1.reinstall... 210 symlinks created
caress@Haxby ~ % gmt
dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
  Referenced from: /usr/local/opt/gdal/lib/libgdal.28.dylib
  Reason: image not found
zsh: abort      gmt
caress@Haxby ~ % brew doctor
Your system is ready to brew.
caress@Haxby ~ % gdalwarp
dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
  Referenced from: /usr/local/bin/gdalwarp
  Reason: image not found
zsh: abort      gdalwarp
caress@Haxby ~ % ls -l /usr/local/opt/libdap/lib/libdap*
-r--r--r--  1 caress  staff  1547192 Dec 30 13:04 /usr/local/opt/libdap/lib/libdap.27.dylib
-r--r--r--  1 caress  staff  2949784 Dec 29 11:05 /usr/local/opt/libdap/lib/libdap.a
lrwxr-xr-x  1 caress  staff       15 Dec 29 11:05 /usr/local/opt/libdap/lib/libdap.dylib -> libdap.27.dylib
-rw-r--r--  1 caress  staff   269920 Dec 30 13:04 /usr/local/opt/libdap/lib/libdapclient.6.dylib
-r--r--r--  1 caress  staff   373536 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapclient.a
lrwxr-xr-x  1 caress  staff       20 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapclient.dylib -> libdapclient.6.dylib
-r--r--r--  1 caress  staff    99368 Dec 30 13:04 /usr/local/opt/libdap/lib/libdapserver.7.dylib
-r--r--r--  1 caress  staff    65648 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapserver.a
lrwxr-xr-x  1 caress  staff       20 Dec 29 11:05 /usr/local/opt/libdap/lib/libdapserver.dylib -> libdapserver.7.dylib
caress@Haxby ~ % brew  gist-logs gdal
Error: No logs.
caress@Haxby ~ % brew gist-logs libdap
Error: No logs.
caress@Haxby ~ % brew gist-logs gmt
Error: No logs.
caress@Haxby ~ %

**Comment by dwcaress** [comment]
On a Mac running Catalina with an existing, working homebrew installation including gmt and gdal, I did 'brew upgrade'. This resulted in updating  libdap to the version referenced above. This then forced a re-installation  of gdal, which was built from source rather than installed from  a bottle. The updated gdal installation works, and gmt still works. Perhaps the problem is with the gdal bottle for Big Sur?

**Comment by dwcaress** [comment]
Going back to my Big Sur machine, I did:
   brew uninstall gmt gdal
   brew install --build-from-source gdal
   brew install gmt

This succeeded. Therefore the problem likely does reside in the construction of the gdal bottle for Big Sur (and perhaps the bottles for other MacOs variants as well).

**Comment by carlocab** [comment]
Thanks for the bug report, @dwcaress. I've opened a pull request (#68039) to rebuild the `gdal` bottle.

**Comment by carlocab** [comment]
This should be fixed now.

**Comment by dwcaress** [comment]
Yes, the problem is fixed. Thank you.

**Comment by torchingloom** [comment]
I'm sorry, but I have the same problem with osgeo-gdal after today brew upgrade

```gdalwarp
dyld: Library not loaded: /usr/local/opt/libdap/lib/libdap.25.dylib
  Referenced from: /usr/local/opt/osgeo-gdal/bin/gdalwarp
  Reason: image not found
```

-----

```brew info gdal
gdal: stable 3.2.1 (bottled), HEAD
Geospatial Data Abstraction Library
https://www.gdal.org/
Conflicts with:
  cpl (because both install cpl_error.h)
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gdal.rb
License: MIT
==> Dependencies
Build: pkg-config ✔
Required: cfitsio ✔, epsilon ✔, expat ✔, freexl ✔, geos ✔, giflib ✔, hdf5 ✔, jpeg ✔, json-c ✔, libdap ✔, libgeotiff ✘, libpng ✔, libpq ✔, libspatialite ✘, libtiff ✔, libxml2 ✔, netcdf ✔, numpy ✔, openjpeg ✔, pcre ✔, poppler ✔, proj ✘, python@3.9 ✔, sqlite ✔, unixodbc ✔, webp ✔, xerces-c ✔, xz ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
```

```brew info libdap
libdap: stable 3.20.7 (bottled), HEAD
Framework for scientific data networking
https://www.opendap.org/
/usr/local/Cellar/libdap/3.20.7 (163 files, 6.7MB) *
  Poured from bottle on 2021-01-18 at 12:22:04
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libdap.rb
License: LGPL-2.1-or-later
==> Dependencies
Build: bison ✘, pkg-config ✔
Required: libxml2 ✔, openssl@1.1 ✔
==> Options
--HEAD
	Install HEAD version```

**Comment by carlocab** [comment]
`osgeo-gdal` is not a homebrew/core formula. You'll need to report this at https://github.com/OSGeo/homebrew-osgeo4mac.

**Comment by torchingloom** [comment]
> `osgeo-gdal` is not a homebrew/core formula. You'll need to report this at https://github.com/OSGeo/homebrew-osgeo4mac.

@carlocab Sorry, thank you
