### ISSUE TITLE
azure-cli - bump formula

### ISSUE THREAD

**Issue by nexxai** [Homebrew/homebrew-core#68057]
Can someone bump the version of azure-cli to 2.17.0 with https://github.com/Azure/azure-cli/archive/azure-cli-2.17.0.tar.gz please?

**Comment by carlocab** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
