### ISSUE TITLE
Vim 8.2.2250 is broken on MacOs

### ISSUE THREAD

**Issue by 0xKira** [Homebrew/homebrew-core#68065]
After upgrading vim to 8.2.2250, vim broke at its start-up.
![image](https://user-images.githubusercontent.com/16382936/103400206-3c540080-4b7f-11eb-9451-800d00b6f846.png)
This should be a known bug, which is fixed in 8.2.2251: https://github.com/vim/vim/releases/tag/v8.2.2251

I manually compiled both versions and confirmed it was the bug in 8.2.2250.
Though I saw the comment in vim.rb
```ruby
# vim should only be updated every 50 releases on multiples of 50
```
But we should handle this special case.

**Comment by 0xKira** [comment]
Noticed that there already been a PR: https://github.com/Homebrew/homebrew-core/pull/68064

**Comment by xNS5** [comment]
A very quick fix to this is to uninstall homebrew's version of vim and use the system's version.

**Comment by carlocab** [comment]
Should be fixed now: https://github.com/Homebrew/homebrew-core/pull/68064
