### ISSUE TITLE
python3 pip incompat with system python2 pip

### ISSUE THREAD

**Issue by dotysan** [Homebrew/homebrew-core#6806]
### Summary:
Attempting to upgrade brew-owned pip3 fails when the system already owns pip2. I honestly don't know whether this bug is in brew itself, or in an upstream tree.

### Reproduce:
On vanilla OS X 10.10 (Yosemite):
```
# Add pip2 to system Python.
sudo python2.7 -m ensurepip

# Install brew.
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install Python 3!
brew install python3
# Upgrade pip.
pip3 install --upgrade pip
```
#### Bang!
```
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/distlib/util.py", line 405, in write_binary_file
    self.ensure_dir(os.path.dirname(path))
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/pip'
```

### Discuss:
Python 3 from brew creates /usr/local/bin/pip3 and /usr/local/bin/pip3.5 symlinks to the cellar. However, it does not affect /usr/local/bin/pip file.

But when pip3 itself is upgraded, it attempts to change /usr/local/bin/pip, but cannot! (Because it is owned by root.)

### Possible Cause:
The system python package `ensurepip` will install pip into /usr/local. However, fresh brew install doesn't properly take ownership of /usr/local tree--as it claims.

### Workaround:
`sudo chown -R $(whoami) $(brew --prefix)`

**Comment by MikeMcQuaid** [comment]
I don't think there's anything actionable for us here: Homebrew can't fix permissions when it's running so issues like this are known if you intentionally install things into `/usr/local/bin`.

**Comment by dotysan** [comment]
OK, thanks for taking a look.

It turns out there's two bugs here. And both can be fixed in pip itself.
- [x] There's a secondary effect when the upgrade fails it doesn't properly rollback. Patch here: https://github.com/pypa/pip/pull/4109
- [x] For the original bug, there's a better workaround. Trick pip into thinking it's called from ensurepip with --no default-pip option like this: `ENSUREPIP_OPTIONS=install pip3 install --upgrade pip`

#### Tada!
Now OS-X/root is still in charge of pip/pip2\* and brew in charge of pip3\*.

$ `ls -l /usr/local/bin/pip\*`
```
-rwxr-xr-x  1 root    wheel  288 Nov 17 14:26 /usr/local/bin/pip
-rwxr-xr-x  1 root    wheel  288 Nov 17 14:26 /usr/local/bin/pip2
-rwxr-xr-x  1 root    wheel  288 Nov 17 14:26 /usr/local/bin/pip2.7
lrwxr-xr-x  1 curtis  admin   34 Nov 17 14:30 /usr/local/bin/pip3 -> ../Cellar/python3/3.5.2_3/bin/pip3
lrwxr-xr-x  1 curtis  admin   36 Nov 17 14:30 /usr/local/bin/pip3.5 -> ../Cellar/python3/3.5.2_3/bin/pip3.5
```

**Comment by MikeMcQuaid** [comment]
> And both can be fixed in pip itself.

Great!
