### ISSUE TITLE
slimerjs formula has mismatched hashes

### ISSUE THREAD

**Issue by qrunchmonkey** [Homebrew/homebrew-core#6809]
Installing the `slimerjs` formula, I consistently get the following error about a SHA256 mismatch.

The downloaded file matches the published signatures at `https://download.slimerjs.org/releases/0.10.1/slimerjs-0.10.1.zip.asc`, which is why I'm reporting this as an issue with the formula. The download is not incomplete or corrupt.

```
$ brew install slimerjs
==> Using the sandbox
==> Downloading https://download.slimerjs.org/releases/0.10.1/slimerjs-0.10.1.zip
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: a2b796c677e9a1faab97b365e70bb3f5e1733728c70ce5e0a9c4d6b19385ae93
Actual: d470c0a33db7c8c19a9a75b0e6216736c94d157b2a3da82b797c22188afa4496
Archive: /Users/kristopf/Library/Caches/Homebrew/slimerjs-0.10.1.zip
To retry an incomplete download, remove the file above.
```

**Comment by umireon** [comment]
This is 99% intended change because the asc file can be [verified with gpg] and the public key is likely to be valid because its fingerprint appears at multiple places (laurentj/slimerjs#487 and [PGP key server]).
According to laurentj/slimerjs#243, the author of SlimerJS sometimes change the uploaded files without any notification.

```
$ curl -fsSL https://slimerjs.org/slimerjs-pubkey.gpg | gpg --import
gpg: key DBC76C05: public key "SlimerJS <slimerjs@innophi.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
$ curl -fsSL https://download.slimerjs.org/releases/0.10.1/slimerjs-0.10.1.zip.asc | gpg
d470c0a33db7c8c19a9a75b0e6216736c94d157b2a3da82b797c22188afa4496  slimerjs-0.10.1.zip
gpg: Signature made Fri Oct 28 20:10:11 2016 JST using RSA key ID DBC76C05
gpg: Good signature from "SlimerJS <slimerjs@innophi.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D8D 8DF9 7FC5 57D9 F287  B1A6 FB07 6108 DBC7 6C05
```


[verified with gpg]: https://slimerjs.org/checksum.html
[PGP key server]: http://pgp.mit.edu/pks/lookup?search=slimerjs%40innophi.com&op=vindex

**Comment by MikeMcQuaid** [comment]
We should start building this from the GitHub tarballs (https://github.com/laurentj/slimerjs/archive/0.10.0.tar.gz), Git tags or remove this package from Homebrew.

**Comment by umireon** [comment]
@MikeMcQuaid Thank you for following up!
Using git tags seems to be reasonable because their content will not be altered over time,
and new versions are actively pushed in the upstream.
I will create a pull request to do so.

**Comment by MikeMcQuaid** [comment]
If Git tags are reasonable then GitHub tarballs should be too as they won't change if the Git tag doesn't.

**Comment by umireon** [comment]
Sorry, for my poor wording.
I mean GitHub tarballs by the word 'git tags'.
Anyhow, I definitely agree with you, @MikeMcQuaid
Thank you 😃

**Comment by MikeMcQuaid** [comment]
No apologies needed, sounds great 👍

**Comment by ilovezfs** [comment]
Closing in favor of the PR #7055
