### ISSUE TITLE
tried brew update php

### ISSUE THREAD

**Issue by oliveiraLeila** [Homebrew/homebrew-core#68163]
# Please fill out one of the templates on: https://github.com/Homebrew/homebrew-core/issues/new/choose or we will close it without comment.

And I got this.

HELP PLEASe

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
acl2                       ioctl                      oakc
act                        isl@0.18                   oci-cli
aerc                       isort                      openalpr
aida-header                jimtcl                     openfst
alsa-lib                   jinx                       openjdk@8
apidoc                     jql                        or-tools
arb                        json5                      ormolu
argo                       jsonnet-bundler            osm
argocd                     k3sup                      overdrive
arturo                     kcgi                       ox
asroute                    keptn                      pandocomatic
athenacli                  khiva                      pangomm@2.42
atkmm@2.28                 kona                       parallel-hashmap
attr                       kondo                      pdm
aws-console                ksync                      periscope
aws-rotate-key             kube-linter                phive
bit-git                    kubecm                     php@7.4
blaze                      kubevela                   pickle
bond                       kubie                      pipgrip
borgbackup                 lab                        pkger
box2d                      ladspa-sdk                 podman
bpytop                     ldpl                       postgresql@12
c7n                        leaf                       prometheus-cpp
cadence                    libaio                     promtail
cairomm@1.14               libbsd                     protoc-gen-go-grpc
cargo-audit                libcap                     protoc-gen-gogo
cargo-edit                 libcap-ng                  protoc-gen-gogofaster
cargo-watch                libdmx                     python@3.9
castget                    libdrm                     rain
cbc                        libfontenc                 reg
cdktf                      libfs                      regipy
cfn-flip                   libfuse                    rm-improved
cfn-format                 libgccjit                  rttr
cgl                        libhandy                   ruby@2.7
chalk-cli                  libice                     rustscan
charge                     libirecovery               sdns
chars                      libmnl                     server-go
chart-testing              libnetfilter-queue         shallow-backup
checkov                    libnfnetlink               sheldon
clair                      libnsl                     showkey
clang-format@8             libpciaccess               shtools
clash                      libpinyin                  silicon
cli11                      libpthread-stubs           simdjson
cloudformation-guard       librttopo                  sleef
commitizen                 libseccomp                 snap
condure                    libslirp                   solidity
copilot                    libsm                      spack
cortex                     libtirpc                   sponge
counterfeiter              libva                      sqlc
croaring                   libvdpau                   sqlite-utils
croc                       libvnc                     staticcheck
cvs-fast-export            libx11                     strace
datasette                  libxau                     structurizr-cli
dbdeployer                 libxaw                     subfinder
device-mapper              libxaw3d                   t-rec
diskonaut                  libxcb                     taskwarrior-tui
dnsprobe                   libxcomposite              tendermint
dnsx                       libxcursor                 terracognita
docui                      libxdamage                 terraform@0.12
dog                        libxdmcp                   terraform@0.13
dotenv-linter              libxext                    terrascan
dotnet                     libxfixes                  tfsec
dprint                     libxfont                   thanos
duckscript                 libxft                     thrax
duf                        libxi                      tm
easy-rsa                   libxinerama                torchvision
efm-langserver             libxkbfile                 trec_eval
eksctl                     libxml++@4                 tree-sitter
eleventy                   libxml++@5                 trunk
empty                      libxmu                     ugrep
envoy                      libxp                      usb.ids
evernote2md                libxpm                     utf8cpp
f3d                        libxrandr                  util-macros
fennel                     libxrender                 v2ray
fetch                      libxres                    vc
fizz                       libxscrnsaver              vint
fleet-cli                  libxshmfence               vivid
flit                       libxt                      volk
flow-cli                   libxtst                    vtk@8.2
flux                       libxv                      vulture
fnm                        libxvmc                    wangle
folderify                  libxxf86dga                wayland
font-util                  libxxf86vm                 wayland-protocols
foreman                    linux-headers              webify
fpart                      localstack                 wgcf
functionalplus             logcli                     wownero
gateway-go                 loki                       x86_64-elf-gdb
gcalcli                    lua@5.3                    xbitmaps
git-hound                  lunchy                     xcb-proto
gitlint                    lunchy-go                  xcb-util
gitql                      magic_enum                 xcb-util-cursor
giza                       mariadb@10.4               xcb-util-image
glab                       markdownlint-cli           xcb-util-keysyms
glibmm@2.64                marked                     xcb-util-renderutil
go@1.14                    massdns                    xcb-util-wm
golangci-lint              matplotplusplus            xcbeautify
googletest                 md4c                       xcinfo
gopls                      mermaid-cli                xdpyinfo
gosec                      mesa-glu                   xinput
gost                       mhonarc                    xkeyboardconfig
gostatic                   microplane                 xorgproto
gping                      mockery                    xorgrgb
gradle-profiler            muffet                     xterm
gtk+4                      naabu                      xtrans
gtkmm4                     nanorc                     yh
h2spec                     ncspot                     yj
halide                     never                      youtube-dlc
heppdt2                    nfpm                       youtubedr
httpx                      ngs                        z.lua
hy                         nicotine-plus              zsh-async
infracost                  node@14                    zsh-you-should-use
inframap                   notmuch-mutt
inja                       numcpp
==> Updated Formulae
Updated 4902 formulae.
==> Renamed Formulae
elasticsearch@6.8 -> elasticsearch@6     kibana@6.8 -> kibana@6
gst-validate -> gst-devtools             now-cli -> vercel-cli
==> Deleted Formulae
boost@1.55                 godep                      stlviewer
boost@1.59                 i386-elf-grub              tomee-jax-rs
confluent-platform         kibana@5.6                 unp64
cryptopp                   llvm@6                     unrar
curl-openssl               meson-internal             woboq_codebrowser
dtrx                       mysql-connector-c++@1.1    wpscan
elasticsearch@2.4          ori                        xspin
elasticsearch@5.6          pgplot                     xu4
fmsx                       rmtrash
gobby                      sflowtool
==> New Casks
7777
8bitdo-ultimate-software
8x8-meet
abyssoft-teleport
aio-creator-neo
ajour
aleo-studio
aleph-one
amazon-workdocs-drive
amd-power-gadget
anka-build-cloud-controller-and-registry
anka-build-cloud-registry
anka-virtualization
archi
aural
avast-secure-browser
aws-vpn-client
berrycast
bigsur-cache-cleaner
binance
blackhole-16ch
blackhole-2ch
bluejeans
bluetility
bluewallet
bome-network
boost-note
box-tools
camo-studio
canva
caramba-switcher
cernbox
circuitjs1
cisco-jabber
clash-for-windows
classicftp
clocker
cloudflare-warp
coin-wallet
colorchecker-camera-calibration
convert3dgui
copytranslator
coscreen
craft
curiosity
daedalus-catalyst
daedalus-mainnet
ddnet
deltachat
desktoppr
deviceinfo
displays
ditto
dockmate
dropbox-passwords
dteoh-devdocs
duoshao
dyalog
edenmath
electricbinary
element
epoccam
eudic-es
eul
ev3-classroom
exifcleaner
fastclicker
fellow
filemaker-pro
fing
flrig
flutter
flying-carpet
fme
freesurfer
futubull
fvim
gactions
gluemotion
google-analytics-opt-out
gotomeeting
happymac
hermit-crab
hessenbox-da
home-assistant
hoststool
hot
ibm-aspera-connect
iconset
imarisviewer
jamulus
jellybeansoup-netflix
jetbrains-space
kdiff3
kekaexternalhelper
keysmith
klogg
koodo-reader
kryoflux
ksnip
leela
locationsimulator
lofi
logicalshift-zoom
loni-pipeline
lunar-client
lx-music
macdroid
macintoshjs
macjournal
macx-video
maczip
marathon-infinity
marathon2
mechvibes
medibangpaintpro
memory-clean-3
messenger
metaimage
mic-drop
microsoft-auto-update
mmhmm
modern-csv
mongodb-realm-studio
mqttx
mtgaprotracker
multi
napari
naver-whale
niftyman
nocturn
nosql-workbench
nota
nova
obs-ndi
obs-websocket
okta-advanced-server-access
openphone
opera-gx
operator
osculator
output-factory
padloc
pb
pcoipclient
pdf-over
pdf-reader-pro
perimeter81
phd2
photosrevive
pictogram
pitch
pixelorama
pomatez
privatus
project-slippi-dolphin
protoio-overflow
pushplaylabs-sidekick
qit
querypie
radicle-upstream
raiderio
raze
reamp
recaf
remote-wake-up
removebg
repoz
retroactive
ripme
rotki
s3stat-setup
scrapp
shearwater-cloud
silicon
silnite
sim-genie
sky-ticket
smultron
snapmotion
snipy
solar2d
spark-ar-studio
spitfire-audio
spyder
stageplotpro
starsector
stashcat
stems
strawberry-wallpaper
sunloginclient
superslicer
surfshark
syncalicious
syncroom
syncsettings
teamviewermeeting
techsmith-capture
tenable-nessus-agent
tencent-docs
tetrio
tigerjython
timche-gmail-desktop
time-to-leave
tmnotifier
toggl-track
toolreleases
tradingview
transcribe
trojanx
tunein
twilioquest
twitterrific
tyme
unity-appletv-support-for-editor
unity-linux-il2cpp-support-for-editor
unity-linux-support-for-editor
unity-macos-il2cpp-support-for-editor
unnaturalscrollwheels
usenapp
utm
vb-cable
videofusion
vidl
vipriser
voov-meeting
waterfox-classic
weakauras-companion
webex
webots
winx-hd-video-converter
wombat
wowup
xattred
yggdrasil
youtube-downloader
yuna
yuque
zbuc-imgur
zeitgeist
zoom-outlook-plugin
zprint
==> Updated Casks
Updated 3528 casks.
==> Deleted Casks
java ✔                                   jing
0xed                                     kekadefaultapp
8x8-video-meetings                       kindlegen
alephone                                 kiwi-for-g-suite
aliwangwang                              levelator
anka-flow                                lightpaper
anvil                                    lunchy
aspera-connect                           manuscripts
blackhole                                master-password
blizz                                    megahertz-knotes
blue-jeans                               mongodb-compass-community
borgbackup                               monogame
box-edit                                 myworkspace
brogue                                   near-lock
canary                                   nosql-workbench-for-amazon-dynamodb
catalina-cache-cleaner                   noteplan
chicken                                  obinslab-starter
cisdem-pdftoolkit                        odio
cocoscreator                             openxcom
coronasdk                                phiewer
cutbox                                   podman
daedalus                                 realm-studio
daemon-tools                             ring
daily-english-listening                  riot
delta                                    scaleft
djay-pro                                 scope
docear                                   simplecap
doly                                     sleepyhead
dropbox-encore                           softu2f
enolsoft-chm-view                        sopcast
eventstore                               sound-blaster-command
ezip                                     station
filemaker-pro-advanced                   toggl
fme-desktop                              trojan-qt5
fractal-bot                              waterfox-current
futuniuniu                               webex-teams
gfortran                                 webponize
ghost                                    x48
gifs                                     xact
hand-mirror                              yandexradio
hockey                                   yourkit-java-profiler
imaging-edge                             zoomin
imgur                                    zoomus-outlook-plugin
intelliscape-caffeine
==> java has been moved to Homebrew.
To uninstall the cask run:
  brew uninstall --cask --force java
==> Installing java...
Error: openjdk 14.0.1 is already installed
To upgrade to 15.0.1, run `brew upgrade openjdk`

Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

Error: php not installed

**Comment by SMillerDev** [comment]
> Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
