### ISSUE TITLE
Composer v1 & v2

### ISSUE THREAD

**Issue by brianvarskonst** [Homebrew/homebrew-core#68242]
Hello, 

I wanted to downgrade from `composer@2` to `composer @1`. 

is it possible like for other packages to provide this major versions? Because for the php development it's still needed to have the `composer@1` version available, because old php packages are only supporting `composer@1`. 

I solved this with a custom `.rb` file, can I open a PR and bring this in?

**Comment by SMillerDev** [comment]
If it meets al requirements defined here: https://docs.brew.sh/Versions. You can make a PR to add this. I believe composer 1.0 is no longer supported upstream though.

---
For the next time, please make a topic in https://github.com/Homebrew/discussions if you have a general question.

**Comment by brianvarskonst** [comment]
> If it meets al requirements defined here: https://docs.brew.sh/Versions. You can make a PR to add this. I believe composer 1.0 is no longer supported upstream though.

Composer 1.10 is still supported, they released the last updated version at December
 
> For the next time, please make a topic in https://github.com/Homebrew/discussions if you have a general question.

Thanks for your fast reply.
