### ISSUE TITLE
unrtf missing ps.conf in share/unrtf

### ISSUE THREAD

**Issue by bripakes** [Homebrew/homebrew-core#6829]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

 unrtf --ps test.rtf returns:

failed to find ps.conf in search path dirs

share/unrtf has html.conf and other conf files, but ps is missing. 

Can this be added?

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by bripakes** [comment]
Sorry... Here is the gist created by 'brew gist-logs unrtf':
https://gist.github.com/29d0d4af3b05a41a04096de3d35c2a83

**Comment by MikeMcQuaid** [comment]
This doesn't seem to be supported by `unrtf`: http://hg.savannah.gnu.org/hgweb/unrtf/file/f37dd4dea9c1/outputs

Upstream don't provide any configuration for this. This is a generic error; if you run `unrtf --mike test.rtf` you'll see it complain about a missing `mike.conf`. Sorry!
