### ISSUE TITLE
Unhandled dyld version by latest gdb 10.1 

### ISSUE THREAD

**Issue by tomoveu** [Homebrew/homebrew-core#68327]
This seems to be a recurring issue. Now, under MacOS Big Sur, the dyld version is 17 and gdb errors with "Unhandled dyld version running gdb". Similar issue is 20047 https://github.com/Homebrew/homebrew-core/issues/20047 

As far as I understand, the headers which fix the dyld version supported by gdb must be updated.

I tried brew doctor, brew update and brew upgrade gdb, I have the latest gdb 10.1 available. 

Looking forward to feedback or a fix.

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
