### ISSUE TITLE
git and hub completions are conflicting

### ISSUE THREAD

**Issue by simonweil** [Homebrew/homebrew-core#68445]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I want to use git completion in the terminal while also having the option to use hub...

## What happened (include command output)
I just get a list of files

<details>
  <summary>Command output</summary>
  <pre>

Just a list of files in the directory...

  </pre>
</details>

## What you expected to happen

Get the git commands for completion

## Step-by-step reproduction instructions (by running `brew install` commands)

1. brew install git
2. Open a new terminal
3. git <TAB> # all is good
3. brew install hub
4. Open a new terminal
5. git <TAB> # just a list of files
6. brew uninstall hub
7. git <TAB> # all is good 

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  gem-neovim
  unrar

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  archey
  dnsprobe

Warning: Putting non-prefixed coreutils in your path can cause gmp builds to fail.

Warning: Putting non-prefixed findutils in your path can cause python builds to fail.
```

```
± brew config
HOMEBREW_VERSION: 2.7.1-137-ga805a5e
ORIGIN: https://github.com/Homebrew/brew
HEAD: a805a5ea16e8d8c38369de16dbe35d3d0fe992ab
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 76779ddfa3393d60d057f76409842e43470fa733
Core tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.WcWquSPL8A/org.macosforge.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15, 14.0.2
macOS: 10.15.7-x86_64
CLT: 12.0.26.2
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

**Comment by SMillerDev** [comment]
That should probably be reported upstream instead. We don't roll our own autocompletes

**Comment by simonweil** [comment]
Hmmm, what would be upstream?

**Comment by simonweil** [comment]
So, it is a bug in `hub` and a bug exists for it:
https://github.com/github/hub/issues/2684

Suggest to leave this issue open for others with this issue.

**Comment by SMillerDev** [comment]
It's an upstream bug so it doesn't belong here, I'm closing this.
