### ISSUE TITLE
Exiftool formula outdated, can it be updated to latest version?

### ISSUE THREAD

**Issue by RocketNuts** [Homebrew/homebrew-core#68443]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?<br>&rarr; Note that the formula doesn't fail, it shows no errors, it's just outdated
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?<br>&rarr; No particular issues in either

**Problem:** exiftool's formula is several months outdated and quite a few versions behind.

`brew info exiftool` shows version 12.00 (from 2020-09-06)

However the latest exiftool available is 12.14 (released 2021-01-06), see also exiftool's [website](https://exiftool.org/) or [github](https://github.com/exiftool/exiftool).

**Comment by SMillerDev** [comment]
Yes it can: https://docs.brew.sh/Updating-Software-in-Homebrew
