### ISSUE TITLE
New Bullet package is built with double precision enabled, why?

### ISSUE THREAD

**Issue by mosra** [Homebrew/homebrew-core#68623]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Updated `bullet` to latest version and discovered it's compiled with double-precision support.

## What happened (include command output)

In 0ce763d19ef95e73236cb7b2a289583ade3b4107 (#67504) by @chenrui333, Bullet got `USE_DOUBLE_PRECISION` enabled, which changes all its APIs to use `double`s instead of `float`s. This is a non-default and often unexpected behavior, breaking C++ software that depended on the Homebrew Bullet package using floats, which was the case for several years until now.

Digging further, it seems to originate from https://github.com/bulletphysics/bullet3/issues/3152, where the new options were taken from. If I remember correctly based on my experience from other projects (https://github.com/facebookresearch/habitat-sim, e.g.), double precision shouldn't be needed in order to make PyBullet work (@erwincoumans, could you confirm? thank you! :pray:). 

I'm not sure if this change was intentional so I'm opening an issue instead of a PR reverting the change.

## What you expected to happen

Bullet should not be compiled with `-DUSE_DOUBLE_PRECISION=ON`, as a lot of existing software using the C++ APIs may rely on the default behavior. This might (or might not) be related to the dartsim build issue in #67504.

## Step-by-step reproduction instructions (by running `brew install` commands)

*(does not apply)*

**Comment by carlocab** [comment]
If you need it compiled without `-DUSE_DOUBLE_PRECISION=ON`, please open a PR to make the change.

**Comment by mosra** [comment]
Okay. Here you go: https://github.com/Homebrew/homebrew-core/issues/68634

**Comment by carlocab** [comment]
Closed in b21c27b8cb51348d0e5d1d4ca5b9077da11b9313.

**Comment by scpeters** [comment]
so bullet has been rebuilt in #68634, but it's ABI is changed, and I believe `dartsim` is broken, although `brew linkage` does not detect the error

I'm seeing a failure in a bottle from a 3rd party tap that compiles against `dartsim`:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=gazebo-install-one_liner-homebrew-amd64&build=1923)](https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1923/) https://build.osrfoundation.org/job/gazebo-install-one_liner-homebrew-amd64/1923/console

~~~
dyld: Symbol not found: __ZNK16btCollisionShape17getBoundingSphereER9btVector3Rd
  Referenced from: /usr/local/opt/dartsim/lib/libdart-collision-bullet.6.9.dylib
  Expected in: /usr/local/opt/bullet/lib/libBulletCollision.3.08.dylib
 in /usr/local/opt/dartsim/lib/libdart-collision-bullet.6.9.dylib
Error: osrf/simulation/gazebo11: failed
~~~

~~~
$ echo __ZNK16btCollisionShape17getBoundingSphereER9btVector3Rd | c++filt
btCollisionShape::getBoundingSphere(btVector3&, double&) const
~~~

I think `dartsim` needs a revision bump, and possibly `efl` as well

**Comment by scpeters** [comment]
rebuilding `dartsim` bottle in https://github.com/Homebrew/homebrew-core/pull/68877
