### ISSUE TITLE
mingw-w64 binaries aren't in PATH or brew info doesn't help on putting them there

### ISSUE THREAD

**Issue by ebraminio** [Homebrew/homebrew-core#68666]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? "Error: No logs."
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5afe9a5f314edb4a9dd633765ab9ec90fe77133
Core tap last commit: 38 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Clang: 12.0 build 1200
Curl: 7.64.1 => /usr/bin/curl
CLT: 12.3.0.0.1.1607026830
[removed unrelated lines]
$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

`brew install mingw-w64`

## What happened (include command output)

```
$ x86_64-w64-mingw32-gcc
zsh: command not found: x86_64-w64-mingw32-gcc
```

## What you expected to happen
I think either you have to mention the formula is keg only and put

```
If you need to have llvm first in your PATH run:
  echo 'export PATH="/usr/local/opt/mingw-w64/bin:$PATH"' >> ~/.zshrc
```

in `brew info mingw-w64` (which isn't there yet, say like `brew info llvm`) or automatically put its binaries in PATH.

**Comment by gromgit** [comment]
> I think either you have to mention the formula is keg only

It's not:
```bash
$ brew install mingw-w64
==> Downloading https://homebrew.bintray.com/bottles/mingw-w64-8.0.0_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/e5f465db3f1e4238b1c58400a0a76df3c96ad3b91bb55ab886c52d2e394ed7f0?response-content-disposition=attachment%3Bfilename%3D%22mingw-w64-8.0.0_1.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHA
######################################################################## 100.0%
==> Installing mingw-w64
==> Pouring mingw-w64-8.0.0_1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/mingw-w64/8.0.0_1: 7,402 files, 854.6MB

$ x86_64-w64-mingw32-gcc --version
x86_64-w64-mingw32-gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ls -l /usr/local/bin/x86_64-w64-mingw32-gcc
lrwxr-xr-x 1 aho admin 54 Jan 10 06:18 /usr/local/bin/x86_64-w64-mingw32-gcc -> ../Cellar/mingw-w64/8.0.0_1/bin/x86_64-w64-mingw32-gcc
```
Something probably went wrong with your install, so `brew reinstall mingw-w64` and watch out for any errors.

**Comment by carlocab** [comment]
FYI, please don't do this:

    [removed unrelated lines]

I am currently wondering if there's something wrong with the bottle you've downloaded from Bintray. However, it is much harder for me to investigate this now that you've decided the lines relevant to this are actually unrelated.

**Comment by ebraminio** [comment]
Turned out I was totally wrong somehow? Deeply sorry.

> I am currently wondering if there's something wrong with the bottle you've downloaded from Bintray. However, it is much harder for me to investigate this now that you've decided the lines relevant to this are actually unrelated.

You are right, here it is.

```
HOMEBREW_VERSION: 2.7.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: dad7dc6a1498b80770d98f2d7cd6fb927c300bbb
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 40028be5f5929ba4606deca8dd0ab3f449f69e22
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
```

> Something probably went wrong with your install, so brew reinstall mingw-w64 and watch out for any errors.

Apparently I had to do a `sudo chown -R $(whoami) /usr/local/Cellar/mingw-w64/8.0.0_1` and then reinstall fixed the issue, weird. Sorry and thanks.
