### ISSUE TITLE
[cdrtools] mkisofs receives abort trap if -graft-points option is used

### ISSUE THREAD

**Issue by jvilk** [Homebrew/homebrew-core#6867]
`-graft-points` lets you specify the destination directory on the disc image for a given input file. It is a critical option; without it, you will need to create the directory structure you require on-disc on your hard drive prior to invoking `mkisofs`!

For example, the following command will place the file `README.md` into the folder `/dir1/dir2` in the resulting ISO file, `test.iso`:

```
mkisofs -JR -o test.iso -graft-points /dir1/dir2/=README.md
```

Unfortunately, any usage of `-graft-points` fails on Macs with "Abort trap: 6":

```
$ mkisofs -JR -o test.iso -graft-points /dir1/dir2/=README.md
Abort trap: 6
```

[MacPorts has the issue reported, along with a potential fix.](https://trac.macports.org/ticket/43632) Could you patch mkisofs with this fix prior to compilation?

I considered reporting the issue upstream, but I don't know exactly where upstream is. It seems like there are multiple forks of cdrtools.

Let me know if you require additional information, or if this bug is better reported elsewhere.

**Comment by MikeMcQuaid** [comment]
> I considered reporting the issue upstream, but I don't know exactly where upstream is. It seems like there are multiple forks of cdrtools.

Looks like upstream is https://downloads.sourceforge.net/project/cdrtools. I think it needs submitted there. We'd consider accepting a pull request applying that patch once it was done.

**Comment by jvilk** [comment]
I have contacted the author of cdrtools, since it seems like there is no bug tracker. I'll update the ticket with further information, should he get back to me.

**Comment by MikeMcQuaid** [comment]
Great, thanks!

**Comment by jvilk** [comment]
He got back to me:

> Thank you for reporting, a new schilytools with the fix will be out this week.

Will ping the ticket when I see the fix go live.
