### ISSUE TITLE
Static library for minizip has wrong architecture

### ISSUE THREAD

**Issue by jeroen** [Homebrew/homebrew-core#68684]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

There is a very strange issue with the static library that is included with minizip. I have not seen this before, the linker seems to think it is of the wrong architecture.

## What you were trying to do (and why)

Link bindings against `libminizip.a` static library from the `minizip` package.

## What happened (include command output)

`ld warning: ignoring file /usr/local/lib/libminizip.a` and then linking errors.

<details>
  <summary>Command output</summary>
  <pre>ld: warning: ignoring file /usr/local/lib/libminizip.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_unzOpenCurrentFile", referenced from:
      _main in test-73c106.o
ld: symbol(s) not found for architecture x86_64
  </pre>
</details>

## What you expected to happen

Program compiles

## Step-by-step reproduction instructions (by running `brew install` commands)

Install minizip:

```
brew install minizip
```

Create an example program `test.c`:

```c
#include <stdio.h>
#include <minizip/unzip.h>
int main(){
  unzFile file = NULL;
  unzOpenCurrentFile(file);
  return 0;
}
```

Now if you link against the dynamic library it works:

```
clang test.c  /usr/local/lib/libminizip.dylib
```

However when linking against the static library, we get the strange error:

```
clang test.c  /usr/local/lib/libminizip.a
```
```
ld: warning: ignoring file /usr/local/lib/libminizip.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "_unzOpenCurrentFile", referenced from:
      _main in test-73c106.o
ld: symbol(s) not found for architecture x86_64
```

<details>
  <summary>brew config</summary>
  <pre>HOMEBREW_VERSION: 2.7.2-76-gd75e9c9
ORIGIN: https://github.com/Homebrew/brew
HEAD: d75e9c99b34bc55e89a6ea0d3520273451e06131
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c5ab4e4a65b169f604d3e480225984da4207bef1
Core tap last commit: 2 days ago
Core tap branch: udunits
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.tXBGPbW9T3/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
  </pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  </pre>
</details>

**Comment by carlocab** [comment]
minizip is not maintained; try the maintained fork called minizip2.

https://github.com/nmoinvaz/minizip/issues/441

**Comment by jeroen** [comment]
The reason I need this is because it is a dependency of GDAL (via libspatialite). Perhaps we can update libspatialite to use minizip2.

**Comment by fxcoudert** [comment]
`building for macOS-x86_64 but attempting to link with file built for macOS-x86_64`

That's useful…

**Comment by jeroen** [comment]
Shall I do a PR that changes all 4 `depends_on: minizip` to `depends_on: minizip2` ?

**Comment by fxcoudert** [comment]
We need to understand and fix your issue, really. I can reproduce it locally, I just can't make sense of it.

The one weird thing I see is that there is a static lib inside the static lib… I don't think that's allowed:

```
$ ar -t /usr/local/opt/minizip/lib/libminizip.a
__.SYMDEF SORTED
libz.a
ioapi.o
mztools.o
unzip.o
zip.o
```

**Comment by tlk** [comment]
It looks like the nested archive `libz.a` is indeed the culprit.

Interestingly, `objdump` from binutils does support nested archives:
```
$ objdump --syms /usr/local/opt/minizip/lib/libminizip.a|head
In archive /usr/local/opt/minizip/lib/libminizip.a:
In nested archive libz.a:

adler32.o:     file format mach-o-x86-64

SYMBOL TABLE:
0000000000000365 l       0e SECT   01 0000 [.text] _adler32_combine_
000000000000034f g       0f SECT   01 0000 [.text] _adler32
000000000000035b g       0f SECT   01 0000 [.text] _adler32_combine
0000000000000441 g       0f SECT   01 0000 [.text] _adler32_combine64
```

But `objdump` from Xcode does not:
```
$ objdump --syms /usr/local/opt/minizip/lib/libminizip.a     
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: error: '/usr/local/opt/minizip/lib/libminizip.a': The file was not recognized as a valid object file
```


Extracting the nested archive and adding its content back in appears to solve the linker issue.

Here is a Makefile that works with the `test.c` file provided by @jeroen:
```Makefile
a.out: macos_libminizip.a
	clang test.c macos_libminizip.a

macos_libminizip.a:
	cp /usr/local/lib/libminizip.a macos_libminizip.a
	chmod +w macos_libminizip.a
	/usr/bin/ar -v -x -o macos_libminizip.a libz.a
	/usr/bin/ar -v -d    macos_libminizip.a libz.a
	mkdir -p libz
	cd libz; /usr/bin/ar -v -x -o ../libz.a
	cd libz; /usr/bin/ar -v -r -c -s ../macos_libminizip.a *.o
	rm -rf libz libz.a

clean:
	rm -f macos_libminizip.a a.out
```
