### ISSUE TITLE
MKVToolNix Fails To Build On Mac OS Big Sur beta Version 11.2 Build 20D5029f

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [Homebrew/homebrew-core#68707]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[Gist Output Link](https://gist.github.com/4f2cae9f170fb001b882f7b2fc06463e)
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I attempted to upgrade the HEAD build of MKVToolNix. Moritz Bunkus redirected me here specifically from GitLab because apparently he does not support Mac OS. If this is the wrong place to report about this formula apologies in advance. My machine is running Mac OS Big Sur version 11.2 beta build 20D5029f.

## What happened (include command output)
➜ brew upgrade mkvtoolnix
==> Upgrading mkvtoolnix HEAD-345efa6_1 -> HEAD-345efa6 
==> Cloning https://gitlab.com/mbunkus/mkvtoolnix.git
Cloning into '/Users/User/Library/Caches/Homebrew/mkvtoolnix--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
Submodule 'lib/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'lib/fmt'
Submodule 'lib/libebml' (https://github.com/Matroska-Org/libebml.git) registered for path 'lib/libebml'
Submodule 'lib/libmatroska' (https://github.com/Matroska-Org/libmatroska.git) registered for path 'lib/libmatroska'
Cloning into '/Users/User/Library/Caches/Homebrew/mkvtoolnix--git/lib/fmt'...
Cloning into '/Users/User/Library/Caches/Homebrew/mkvtoolnix--git/lib/libebml'...
Cloning into '/Users/User/Library/Caches/Homebrew/mkvtoolnix--git/lib/libmatroska'...
Submodule path 'lib/fmt': checked out '19bd751020a1f3c3363b2eb67a039852f139a8d3'
Submodule path 'lib/libebml': checked out 'f9fc9a89177e9bcdc1a34ac7ab76114ddd6149c8'
Submodule path 'lib/libmatroska': checked out '684560a3ce962a7abe89be93cc8ffa483f7f853f'
/Users/User/Library/Caches/Homebrew/mkvtoolnix--git/lib/fmt
/Users/User/Library/Caches/Homebrew/mkvtoolnix--git/lib/libebml
/Users/User/Library/Caches/Homebrew/mkvtoolnix--git/lib/libmatroska
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/mkvtoolnix/HEAD-e1d79fc --with-boost=/usr/local/opt/boost --with-docbook-xsl-root=/usr/local/opt/docbook-xsl/docbook-xsl --with-extra-includes=/usr/local/opt/flac/include;/usr/local/opt/libebml/i
==> rake -j12
Last 15 lines from /Users/User/Library/Logs/Homebrew/mkvtoolnix/03.rake:
ld: warning: dylib (/usr/local/Cellar/pcre2/10.36/lib/libpcre2-8.dylib) was built for newer macOS version (11.0) than being linked (10.14)
ld: warning: dylib (/usr/local/lib/libgtest.dylib) was built for newer macOS version (11.0) than being linked (10.14)
Undefined symbols for architecture x86_64:
  "typeinfo for testing::Test", referenced from:
      typeinfo for (anonymous namespace)::AttachmentTarget_Basics_Test in attachment_target.o
      typeinfo for (anonymous namespace)::AttachmentTarget_ParsingCorrectArgumentsForAdd_Test in attachment_target.o
      typeinfo for (anonymous namespace)::AttachmentTarget_ParsingCorrectArgumentsForDelete_Test in attachment_target.o
      typeinfo for (anonymous namespace)::AttachmentTarget_ParsingCorrectArgumentsForReplace_Test in attachment_target.o
      typeinfo for (anonymous namespace)::AttachmentTarget_ParsingInvalidArgumentsForAdd_Test in attachment_target.o
      typeinfo for (anonymous namespace)::AttachmentTarget_ParsingInvalidArgumentsForDelete_Test in attachment_target.o
      typeinfo for (anonymous namespace)::AttachmentTarget_ParsingInvalidArgumentsForReplace_Test in attachment_target.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
           CXX tests/unit/common/math.cpp

## What you expected to happen
I expected the HEAD build to complete successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)
See above.

**Comment by jonchang** [comment]
You’re on a beta release of macOS and trying to build software from source from a HEAD commit, neither of which we support. You’ll have to figure this out on your own unfortunately.
