### ISSUE TITLE
emscripten fails during postinstall

### ISSUE THREAD

**Issue by ShonFrazier** [Homebrew/homebrew-core#68814]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/ShonFrazier/11d1200477e7c9eeda7cfcd93137eae5
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to upgrade emscripten

## What happened (include command output)

`emcc` complained about no input files during postinstall

<details>
  <summary>Command output</summary>
  <pre>

> brew postinstall emscripten
==> Postinstalling emscripten
==> /usr/local/Cellar/emscripten/2.0.12/bin/emcc
Last 15 lines from /Users/shon/Library/Logs/Homebrew/emscripten/post_install.01.emcc:
2021-01-11 15:49:33 -0500

/usr/local/Cellar/emscripten/2.0.12/bin/emcc

emcc: error: no input files
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall emscripten`

  </pre>
</details>

## What you expected to happen

emscripten to have been upgraded without error

## Step-by-step reproduction instructions (by running `brew install` commands)

Run `brew upgrade emscripten` and the error is produced.

I also tried `brew uninstall emscripten; brew install emscripten` and got the same error.

**Comment by carlocab** [comment]
Tried this; can't reproduce. I am on Big Sur, however, and @ShonFrazier is running Catalina.

**Comment by alebcay** [comment]
I'm still running Catalina and was unable to reproduce the error.

**Comment by carlocab** [comment]
@ShonFrazier, can you try
```
brew uninstall --force --ignore-dependencies emscripten node python@3.9 yuicompressor
brew update
brew install emscripten
```
and see if that fixes anything?

**Comment by ShonFrazier** [comment]
Looks like a negative :( 
Amidst all the other output:
<pre>
[snip]
==> Installing emscripten
==> Pouring emscripten-2.0.12.catalina.bottle.tar.gz
==> /usr/local/Cellar/emscripten/2.0.12/bin/emcc
Last 15 lines from /Users/shon/Library/Logs/Homebrew/emscripten/post_install.01.emcc:
2021-01-14 20:42:34 -0500

/usr/local/Cellar/emscripten/2.0.12/bin/emcc

shared:INFO: (Emscripten: Running sanity checks)
emcc: error: no input files
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall emscripten`
==> Summary
🍺  /usr/local/Cellar/emscripten/2.0.12: 13,394 files, 1GB
==> Upgrading 2 dependents:
ffmpeg 4.3.1_8 -> 4.3.1_9, vim 8.2.2300 -> 8.2.2350
[snip]
</pre>

[post_install.01.emcc](https://gist.github.com/ShonFrazier/3fe7bd7e6c59231e11b4ce14ce1b2273)

**Comment by gromgit** [comment]
From the `emscripten` formula:
```
  def post_install
    system bin/"emcc"
```
What is that command supposed to do during post-install? If it behaves anything like GCC and other compilers, it _should_ fail exactly as is happening here.

**Comment by carlocab** [comment]
>What is that command supposed to do during post-install?

That's needed to generate the config file that the `inreplace` in the next line operates on. Without it, the `inreplace` will fail. Ref. https://emscripten.org/docs/building_from_source/configuring_emscripten_settings.html#creating-the-compiler-configuration-file

https://github.com/Homebrew/homebrew-core/blob/7eb6d72261cfd77e2d8323bc4ba12fd8fbfb579a/Formula/emscripten.rb#L134-L140

**Comment by gromgit** [comment]
A quick test indicates that `emcc` will create `#{libexec}/.emscripten` and exit if it doesn't exist, but switch into input-file processing mode if it does (triggering the OP's error messages), so gating the post-install on the existence of that file should work better:
```
def post_install
  unless File.exist? "#{libexec}/.emscripten"
    system bin/"emcc"
    inreplace "#{libexec}/.emscripten" do |s|
      s.gsub! /^(LLVM_ROOT.*)/, "#\\1\nLLVM_ROOT = \"#{opt_libexec}/llvm/bin\"\\2"
      s.gsub! /^(BINARYEN_ROOT.*)/, "#\\1\nBINARYEN_ROOT = \"#{opt_libexec}/binaryen\"\\2"
    end
  end
end 
```

**Comment by carlocab** [comment]
I think we can keep the `inreplace` call even if `.emscripten` exists?

**Comment by gromgit** [comment]
> I think we can keep the `inreplace` call even if `.emscripten` exists?

If you're thinking of moving the `inreplace` outside the `unless` guard, sure.

Either way, you might want to remove `#\\1\n` in the substitution, as it keeps a copy of the previous config line even if it's already set correctly. I originally substituted `emcc` with `emcc --check` (which is another solution to the issue), and discovered that when I installed `emscripten`, then ran `brew postinstall` twice to ensure it didn't throw errors any more, the `.emscripten` file contained _four_ sets of `LLVM_ROOT` and `BINARYEN_ROOT`:
* one commented set with the original values
* two commented sets pointing inside `#{opt_libexec}`
* one uncommented set pointing inside `#{opt_libexec}`

The bloat is trivial, but still slightly ugly.

**Comment by gromgit** [comment]
> I'm unsure as to how `libexec/".emscripten"` could already exist on a fresh install.

It shouldn't, not even on a reinstall, yet there's the OP's issue. :shrug: 

> Maybe it'd just be better to test for its existence, remove it if it does, generate a new one, then modify that?

Hmmm. Any user customizations in the file will be lost anyway, so yeah, that should not break anything new.

**Comment by carlocab** [comment]
@ShonFrazier, do you have a `.emscripten` file in your home directory?

**Comment by ShonFrazier** [comment]
I do. Contents:
```
NODE_JS = '/usr/local/bin/node'
LLVM_ROOT = '/usr/local/opt/emscripten/libexec/llvm/bin'
BINARYEN_ROOT = '/usr/local/opt/binaryen'
TEMP_DIR = '/var/folders/_n/kp6zvz_x3rgfbl_lnt6f6xc00000gn/T'
COMPILER_ENGINE = NODE_JS
JS_ENGINES = [NODE_JS]
```

**Comment by carlocab** [comment]
That would explain the post-install failure, I think. Running `emcc` without an input only produces an error when it can find a `.emscripten` file in its search path (though I'll admit to not knowing where exactly it looks). The post-install step is really needed only to set this file up, so the failure on your system shouldn't affect how it works for you.

That said, this is probably something that still needs to be fixed. Not sure what the right fix is though. I suppose replacing it with `emcc --check` might work.
