### ISSUE TITLE
Formulas removed: mlkit and smlpkg

### ISSUE THREAD

**Issue by melsman** [Homebrew/homebrew-core#68828]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I tried to install the brew formulas `mlkit` and `smlpkg` on a CI system, but the formulas have been removed from Homebrew in issue #66465 .  It is stated that the two projects are not maintained upstream, which is not true; I am the maintainer of these two packages.

## What happened (include command output)

<details>
  <summary>Output from Travis CI script</summary>
  <pre>
...
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mlkit ; fi
Error: mlkit has been disabled because it is not maintained upstream!
  </pre>
</details>

## What you expected to happen

The package should be installed.

## Step-by-step reproduction instructions (by running `brew install` commands)

Note: Building the MLKit depends on the MLton (formula mlton) compiler. Unfortunately, the brew version of mlton has a bug, which has been fixed upstream, but which prevents mlkit from building. How should I proceed? Should I try to make the MLton developers spawn a new release?

**Comment by carlocab** [comment]
If you would like to re-enable these two formulae, please open PRs. The issue is unnecessary.

>the brew version of mlton has a bug, which has been fixed upstream, but which prevents mlkit from building

You can add a patch to mlton that will allow mlkit to build. Do `grep 'patch do'` in the core repo for examples. Before the patch, please include a brief comment describing the patch and when it can be removed.
