### ISSUE TITLE
gcc8 and gcc9 failed to update through brew upgrade

### ISSUE THREAD

**Issue by andy-mishechkin** [Homebrew/homebrew-core#68866]
# Bug report
We've faced with issue with gcc formula during brew update from non last brew commit. 
When we have installed gcc8, gcc9 and gcc10m and tried to run 
```
brew update
brew upgrade
```
we've got the error with symlink in gcc8 and gcc9. 
This issue is not appears when gcc10 is not installed. 
Here the related issue:
https://github.com/actions/virtual-environments/issues/2391

**Step-by-step reproduction instructions** 
Repro steps:
1. Take clean MacOS 10.15 
2. Install brew
3. run `cd $(brew --repo)/Library/Taps/homebrew/homebrew-core`
4. run `git checkout feb52fabc2e148348f48bddae97973eca9df6136` - it's commit from Tue Dec 15 12:26:17 2020 +0000
5. run `HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc@8`
6. run `HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc@9`
7. run `HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc@10`
8. checkout to brew master branch
9. run `brew update`
10. run `brew upgrade`

## What happened (include command output)
Here the error after the `brew update`
<details>
  <summary>Command output</summary>
  <pre>
==> Upgrading gcc@9 9.3.0 -> 9.3.0_1
==> Downloading https://homebrew.bintray.com/bottles/gcc%409-9.3.0_1.catalina.bottle.tar.gz
Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/9cc4e9268411fbe14515640c2c186420990e871ebd539c16c90fd20a63142d65--gcc@9-9.3.0_1.catalina.bottle.tar.gz
==> Pouring gcc@9-9.3.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/c++-9
Target /usr/local/bin/c++-9
is a symlink belonging to gcc@9. You can unlink it:
  brew unlink gcc@9

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc@9

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc@9

  </pre>
</details>

## What you expected to happen
We are expected to get updates of gcc without any errors

**Comment by mistydemeo** [comment]
I'm seeing this with some other packages too (in my case, `clingo`). As with your case, `brew link` is seeing it as conflicting with itself. Going to investigate.

**Comment by mistydemeo** [comment]
Does the symlink `$(brew --prefix)/var/homebrew/linked/gcc@9` exist?

**Comment by maxim-lobanov** [comment]
Yes,
![image](https://user-images.githubusercontent.com/16715858/104414279-0f411e00-5581-11eb-83f8-205d6e102070.png)

**Comment by mistydemeo** [comment]
How about `$(brew --prefix)/opt/gcc@9`?

**Comment by andy-mishechkin** [comment]
Yeah, this link also present
![image](https://user-images.githubusercontent.com/57713077/104569721-77b7fa00-566a-11eb-90ac-a8489a57f594.png)

> How about `$(brew --prefix)/opt/gcc@9`?

**Comment by MikeMcQuaid** [comment]
`export HOMEBREW_NO_AUTO_UPDATE=1; cd $(brew --repo homebrew/core); git checkout -f feb52fabc2e148348f48bddae97973eca9df6136; brew uninstall --force gcc@9 gcc@10; brew install gcc@9 gcc@10; ls /usr/local/opt/gcc* /usr/local/var/homebrew/linked/gcc*; git checkout -f master; brew upgrade` is my minimal reproduction case now that reproduces this.
