### ISSUE TITLE
mysql++ blocks mysql server

### ISSUE THREAD

**Issue by Jose123456** [Homebrew/homebrew-core#6889]
The `mysql++` formula requires `mysql-connector-c` which blocks `mysql` since dc5d10c. Since the problem is that `mysql` installs the same libraries as `mysql-connector-c`, it's logical to think that `mysql++` should depend on either `mysql-connector-c` or `mysql` (and maybe or `mariadb` or `percona-server`).

I tested with `mysql++` and `mysql` and it works.

**Comment by Lillecarl** [comment]
This is broken indeed, splitting the mysql package into client and server would probably also be a good idea while one's at it :)

**Comment by MikeMcQuaid** [comment]
Closing in favour of PR in https://github.com/Homebrew/homebrew-core/pull/6895
