### ISSUE TITLE
freerdp dyld: Library not loaded: @rpath/libfreerdp-client2.2.dylib

### ISSUE THREAD

**Issue by IceCloud76** [Homebrew/homebrew-core#68890]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
 joe@macmini ? ~ ? brew gist-logs freerdp
Error: No logs.
 ? joe@macmini ? ~ ? brew config
HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2db093f9f16d3e5d189021f0957ea01e550e483
Core tap last commit: 38 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.aVed5jSVAe/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
XQuartz: 2.7.11 => /opt/X11
Rosetta 2: false
 joe@macmini ? ~ ? brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

Run `xfreerdp` from iTerm2

## What happened (include command output)

<details>
  <summary>
xfreerdp
</summary>
  <pre>

dyld: Library not loaded: @rpath/libfreerdp-client2.2.dylib
  Referenced from: /opt/homebrew/bin/xfreerdp
  Reason: image not found
[1]    30654 abort      xfreerdp

  </pre>
</details>

## What you expected to happen
xfreerdp to run, and not be aborted

## Step-by-step reproduction instructions (by running `brew install` commands)
`brew install freerdp`
`xfreerdp`

## What I tried to do to fix this
`brew reinstall freerdp`
`xcode-select --install`
output: 
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`
(I think this is reference to systems updates?)
From here I checked for Software updates under System Preferences. There were no updates. MacOS 11.1 was the most recent.

**Comment by carlocab** [comment]
Does `xfreerdp --version` produce any errors?

**Comment by IceCloud76** [comment]
Same issue.
```
joe@macmini ? ~ ? xfreerdp --version
dyld: Library not loaded: @rpath/libfreerdp-client2.2.dylib
  Referenced from: /opt/homebrew/bin/xfreerdp
  Reason: image not found
[1]    30781 abort      xfreerdp --version
```

**Comment by carlocab** [comment]
This doesn't produce an error on CI, so the issue might be with your installation. Try uninstalling all of `freerdp`'s dependencies (you may need to use `brew uninstall --ignore-dependencies --force`) first, then install `freerdp` again.

**Comment by IceCloud76** [comment]
I've already tried an uninstall without `--ignore-dependencies --force` before, but I'll try that

```
 joe@macmini ? ~ ? brew uninstall --ignore-dependencies --force freerdp
Uninstalling freerdp... (245 files, 5.2MB)
 joe@macmini ? ~ ? brew install freerdp
==> Downloading https://homebrew.bintray.com/bottles/freerdp-2.2.0_3.arm64_big_sur.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/8cfd66b03f01827edc1e2241478db3a22c62e4a1d12ae5d52591d4aa47df51b2?response-content-disposition=attachment%3Bfilename%3D%22freerdp-2.2.0_3.arm64_big_sur.bottle.tar.gz%22&Policy
######################################################################## 100.0%
==> Pouring freerdp-2.2.0_3.arm64_big_sur.bottle.tar.gz
?  /opt/homebrew/Cellar/freerdp/2.2.0_3: 245 files, 5.2MB
 joe@macmini ? ~ ? xfreerdp --version
dyld: Library not loaded: @rpath/libfreerdp-client2.2.dylib
  Referenced from: /opt/homebrew/bin/xfreerdp
  Reason: image not found
[1]    5801 abort      xfreerdp --version
```

**Comment by carlocab** [comment]
You only uninstalled `freerdp`.

>Try uninstalling all of `freerdp`'s **dependencies**

That means
```
❯ brew deps freerdp
jpeg
libpthread-stubs
libusb
libx11
libxau
libxcb
libxcursor
libxdmcp
libxext
libxfixes
libxi
libxinerama
libxrandr
libxrender
libxv
openssl@1.1
pkg-config
xorgproto
```

**Comment by IceCloud76** [comment]
My bad. I wasn't sure why you had the --ignore-dependencies flag there for a minute.
```
brew uninstall --ignore-dependencies --force jpeg libpthread-stubs libusb libx11 libxau libxcb libxcursor libxdmcp libxext libxfixes libxi libxinerama libxrandr libxrender libxv openssl@1.1 pkg-config xorgproto
```

```
joe@macmini ~ brew install

A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /opt/homebrew/etc/openssl@1.1/certs

and run
  /opt/homebrew/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"

==> tcl-tk
tcl-tk is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have tcl-tk first in your PATH run:
  echo 'export PATH="/opt/homebrew/opt/tcl-tk/bin:$PATH"' >> ~/.zshrc

For compilers to find tcl-tk you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/tcl-tk/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/tcl-tk/include"

For pkg-config to find tcl-tk you may need to set:
  export PKG_CONFIG_PATH="/opt/homebrew/opt/tcl-tk/lib/pkgconfig"

==> python@3.9
Python has been installed as
  /opt/homebrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /opt/homebrew/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /opt/homebrew/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python 
```
zsh still complains about the Library not being loaded however. My first thought it that maybe something isn't in my path that should be but none of these packages, tcl-tk or openssl should be required for `xfreerdp` to print it's version number

**Comment by carlocab** [comment]
Yea, I'm not sure anymore. One thing that might be worth trying:

First, uninstall `freerdp` and all the formulae it depends on again. Then, in `freerdp.rb`, change

https://github.com/Homebrew/homebrew-core/blob/ffe9463b373558909f7c1e03661edc353d8cc3de/Formula/freerdp.rb#L43

to
```ruby
system "cmake", ".", *std_cmake_args, "-DWITH_X11=ON", "-DBUILD_SHARED_LIBS=ON", "-DWITH_JPEG=ON", "-DCMAKE_INSTALL_RPATH=#{lib}"
```
the easy way to do this would be to do `brew edit freerdp`.

Once you've done that, do

    HOMEBREW_NO_AUTO_UPDATE=1 brew install -s freerdp

and then test if that fixes anything. You can do `brew update-reset` to undo the changes you've made to your local core repo. However, please note the following first:
```
❯ brew help update-reset
Usage: brew update-reset [repository]

Fetch and reset Homebrew and all tap repositories (or any specified
repository) using git(1) to their latest origin/master.

Note: this will destroy all your uncommitted or committed changes.
```

**Comment by IceCloud76** [comment]
I removed freerdp and all it's dependencies.  
I then edited that line with `brew edit freerdp`
 
Now when I try to install with `HOMEBREW_NO_AUTO_UPDATE=1 brew install -s freerdp`, I get a compilation error.

```
==> Summary
?  /opt/homebrew/Cellar/openssl@1.1/1.1.1i: 8,067 files, 18MB
==> Installing freerdp
==> cmake . -DWITH_X11=ON -DBUILD_SHARED_LIBS=ON -DWITH_JPEG=ON -DCMAKE_INSTALL_RPATH=/opt/homebrew/Cellar/freerdp/2.2.0_3/lib
==> make install
Last 15 lines from /Users/joe/Library/Logs/Homebrew/freerdp/02.make:
winpr
cd /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac && install_name_tool -change /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/libfreerdp/libfreerdp2.2.dylib @executable_path/../Frameworks/MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Contents/libwinpr2.2.2.0.dylib
freerdp
cd /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac && install_name_tool -change /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/common/libfreerdp-client2.2.dylib @executable_path/../Frameworks/MacFreeRDP.framework/Contents/libfreerdp-client2.2.2.0.dylib /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib
freerdp
cd /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac && install_name_tool -change /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/winpr/libwinpr/libwinpr2.2.dylib @executable_path/../Frameworks/MacFreeRDP.framework/Contents/libwinpr2.2.2.0.dylib /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib
freerdp
cd /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac && install_name_tool -change /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/libfreerdp/libfreerdp2.2.dylib @executable_path/../Frameworks/MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib
Compiling CertificateDialog.xib
cd /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac && /usr/bin/ibtool --errors --warnings --notices --output-format human-readable-text --compile /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Versions/2.2.0/Resources/CertificateDialog.nib /tmp/freerdp-20210114-22108-15leb44/FreeRDP-2.2.0/client/Mac/CertificateDialog.xib
xcode-select: error: tool 'ibtool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make[2]: *** [client/Mac/MacFreeRDP.framework/Versions/2.2.0/MacFreeRDP] Error 1
make[2]: *** Deleting file `client/Mac/MacFreeRDP.framework/Versions/2.2.0/MacFreeRDP'
make[1]: *** [client/Mac/CMakeFiles/MacFreeRDP-library.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by carlocab** [comment]
Hmm, ok. You do have Xcode installed, so the only problem it's having is that `brew` isn't making it available to the build environment.

Try `brew edit freerdp` again, and this time, in addition to the `-DCMAKE_INSTALL_RPATH` change I suggested before, move the line that says

    depends_on xcode: :build

out of the `head do` block. This should allow `brew` to use Xcode will building `freerdp` from source.

**Comment by IceCloud76** [comment]
Changed to:
```
head do
    url "https://github.com/FreeRDP/FreeRDP.git"
end

    depends_on xcode: :build
```

```
==> Downloading https://github.com/FreeRDP/FreeRDP/archive/2.2.0.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/downloads/5d6c27046a6be925409a091c69deb843c2e11bce807797387f5ecb76d1e89fe1--FreeRDP-2.2.0.tar.gz
==> cmake . -DWITH_X11=ON -DBUILD_SHARED_LIBS=ON -DWITH_JPEG=ON -DCMAKE_INSTALL_RPATH=/opt/homebrew/Cellar/freerdp/2.2.0_3/lib
==> make install
Last 15 lines from /Users/joe/Library/Logs/Homebrew/freerdp/02.make:
cd /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac && install_name_tool -change /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/winpr/libwinpr/libwinpr2.2.dylib @executable_path/../Frameworks/MacFreeRDP.framework/Contents/libwinpr2.2.2.0.dylib /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib
[100%] Linking C executable xfreerdp
cd /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/X11 && /opt/homebrew/Cellar/cmake/3.19.2/bin/cmake -E cmake_link_script CMakeFiles/xfreerdp-client.dir/link.txt --verbose=1
/opt/homebrew/Library/Homebrew/shims/mac/super/clang  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DNDEBUG -Wno-builtin-macro-redefined -D__FILE__='"$(subst /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/,,$(subst /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/,,$(abspath $<)))"' -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/xfreerdp-client.dir/xf_gdi.c.o CMakeFiles/xfreerdp-client.dir/xf_gfx.c.o CMakeFiles/xfreerdp-client.dir/xf_rail.c.o CMakeFiles/xfreerdp-client.dir/xf_input.c.o CMakeFiles/xfreerdp-client.dir/xf_event.c.o CMakeFiles/xfreerdp-client.dir/xf_floatbar.c.o CMakeFiles/xfreerdp-client.dir/xf_channels.c.o CMakeFiles/xfreerdp-client.dir/xf_cliprdr.c.o CMakeFiles/xfreerdp-client.dir/xf_monitor.c.o CMakeFiles/xfreerdp-client.dir/xf_disp.c.o CMakeFiles/xfreerdp-client.dir/xf_graphics.c.o CMakeFiles/xfreerdp-client.dir/xf_keyboard.c.o CMakeFiles/xfreerdp-client.dir/xf_video.c.o CMakeFiles/xfreerdp-client.dir/xf_window.c.o CMakeFiles/xfreerdp-client.dir/xf_client.c.o CMakeFiles/xfreerdp-client.dir/cli/xfreerdp.c.o -o xfreerdp  -Wl,-rpath,/tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/common -Wl,-rpath,/tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/libfreerdp -Wl,-rpath,/tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/winpr/libwinpr /opt/homebrew/lib/libX11.dylib /opt/homebrew/lib/libXinerama.dylib /opt/homebrew/lib/libXext.dylib /opt/homebrew/lib/libXcursor.dylib /opt/homebrew/lib/libXv.dylib /opt/homebrew/lib/libXi.dylib /opt/homebrew/lib/libXrender.dylib /opt/homebrew/lib/libXrandr.dylib /opt/homebrew/lib/libXfixes.dylib ../common/libfreerdp-client2.2.2.0.dylib ../../libfreerdp/libfreerdp2.2.2.0.dylib -lm ../../winpr/libwinpr/libwinpr2.2.2.0.dylib
freerdp
cd /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac && install_name_tool -change /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/libfreerdp/libfreerdp2.2.dylib @executable_path/../Frameworks/MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Contents/libfreerdp2.2.2.0.dylib
Compiling CertificateDialog.xib
cd /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac && /usr/bin/ibtool --errors --warnings --notices --output-format human-readable-text --compile /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac//MacFreeRDP.framework/Versions/2.2.0/Resources/CertificateDialog.nib /tmp/freerdp-20210114-25827-1m25w9j/FreeRDP-2.2.0/client/Mac/CertificateDialog.xib
xcode-select: error: tool 'ibtool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make[2]: *** [client/Mac/MacFreeRDP.framework/Versions/2.2.0/MacFreeRDP] Error 1
make[2]: *** Deleting file `client/Mac/MacFreeRDP.framework/Versions/2.2.0/MacFreeRDP'
make[1]: *** [client/Mac/CMakeFiles/MacFreeRDP-library.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target xfreerdp-client
make: *** [all] Error 2
```

**Comment by carlocab** [comment]
Can you find the location of `libfreerdp-client2.2.dylib`? I think it might be in `$(brew --prefix freerdp)/lib`.

**Comment by IceCloud76** [comment]
```
$(brew --prefix freerdp)/lib
zsh: no such file or directory: /opt/homebrew/Cellar/freerdp/2.2.0_3/lib
```
I'm a new to MacOS systems, so I'm not sure where Library files would be. Especially not Dynamic library files. But I searched recursively using `find` (`find dir -print | grep libfreerdp-client2.2.dylib`)  under `/Library`, `/opt`, `/private`, and `/'usr`, places where I thought the libraries might be held, or at least linked to, but I didn't find a `libfreerdp-client2.2.dylib`

**Comment by carlocab** [comment]
Have you reinstalled `freerdp` before doing that? `brew --prefix freerdp` should be giving you `/opt/homebrew/opt/freerdp` if it's installed. It should only return the cellar path when a formula isn't installed.

**Comment by IceCloud76** [comment]
Why would it be installed? `make` failed when I tried installing from source. This was *after* I removed the pre-compiled `freerdp` binary and it's deps.

In any case,  
`brew --prefix freerdp` gives me:
`/opt/homebrew/Cellar/freerdp/2.2.0_3`

trying `file /opt/homebrew/Cellar/freerdp/2.2.0_3` results in:
/opt/homebrew/Cellar/freerdp/2.2.0_3: cannot open `/opt/homebrew/Cellar/freerdp/2.2.0_3' (No such file or directory)

And when trying to run xfreerdp, zsh complains about the command not being found
`zsh: command not found: xfreerdp` 

Looking under /opt/homebrew/Cellar/, there is no freerdp directory

**Comment by carlocab** [comment]
Well, you _can_ install freerdp; it just doesn't work. We want to find out where freerdp puts `libfreerdp-client2.2.dylib`. Kinda hard to do that if it's not installed...

**Comment by IceCloud76** [comment]
I did a `brew update-reset` then `brew install freerdp`

Afterwards, `find /opt -print | grep libfreerdp-client2.2.dylib` gave me two locations:
```
/opt/homebrew/lib/libfreerdp-client2.2.dylib
/opt/homebrew/Cellar/freerdp/2.2.0_3/lib/libfreerdp-client2.2.dylib
```
Not sure if this helps or not...

**Comment by JesusCalix** [comment]
Were you able to fix this bug? I am having the same problem and I have tried some fixes with no success

**Comment by IceCloud76** [comment]
```
/opt/homebrew/bin/xfreerdp:
	/opt/homebrew/opt/libx11/lib/libX11.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/homebrew/opt/libxinerama/lib/libXinerama.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/opt/homebrew/opt/libxext/lib/libXext.6.dylib (compatibility version 11.0.0, current version 11.0.0)
	/opt/homebrew/opt/libxcursor/lib/libXcursor.1.dylib (compatibility version 2.0.0, current version 2.2.0)
	/opt/homebrew/opt/libxv/lib/libXv.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/opt/homebrew/opt/libxi/lib/libXi.6.dylib (compatibility version 8.0.0, current version 8.0.0)
	/opt/homebrew/opt/libxrender/lib/libXrender.1.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/homebrew/opt/libxrandr/lib/libXrandr.2.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/homebrew/opt/libxfixes/lib/libXfixes.3.dylib (compatibility version 5.0.0, current version 5.0.0)
	@rpath/libfreerdp-client2.2.dylib (compatibility version 2.0.0, current version 2.2.0)
	@rpath/libfreerdp2.2.dylib (compatibility version 2.0.0, current version 2.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
	@rpath/libwinpr2.2.dylib (compatibility version 2.0.0, current version 2.2.0)
```

Running `install_name_tool -add_rpath "@loader_path/../lib" $(which xfreerdp)`
tells me that

 `/Library/Developer/CommandLineTools/usr/bin/install_name_tool: warning: changes being made to the file will invalidate the code signature in: /opt/homebrew/bin/xfreerdp`

Trying to run xfreerdp after that, the process gets killed immediately?? I've never seen that before.

`$ xfreerdp --version`
`[1]    26639 killed     xfreerdp --version`

**Comment by carlocab** [comment]
Ah, yes, sorry. You also need to do
```
codesign -f -s - $(which xfreerdp)
```

**Comment by IceCloud76** [comment]
```
/opt/homebrew/bin/xfreerdp: replacing existing signature
/opt/homebrew/bin/xfreerdp: the codesign_allocate helper tool cannot be found or used
```

Doing a quick google, I tried running `locate codesign_allocate`, and I got this message:

```
WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.
```

Should I try and run 
`sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist`?

I'm honestly not sure what it does.

**Comment by carlocab** [comment]
I would try it if it were me, but you may have a different opinion about this. You can read about what this command does here: https://osxdaily.com/2011/11/02/enable-and-use-the-locate-command-in-the-mac-os-x-terminal/

If you don't find yourself using the `locate` command after this, you can run

     sudo launchctl unload /System/Library/LaunchDaemons/com.apple.locate.plist

You can also examine the content of the `com.apple.locate.plist` file to see what it does. It basically runs `/usr/libexec/locate.updatedb` at 3:15 AM every Saturday.

**Comment by IceCloud76** [comment]
Woohoo! That works!

After running
 'sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist' 

and waiting a few minutes for it to build the database, I ran

`codesign -f -s - $(which xfreerdp)`

`xfreerdp --version`

`This is FreeRDP version 2.2.0 (n/a)`

And a connection via freerdp works with my local Windows machine

**Comment by JesusCalix** [comment]
Hi! I did all that steps but now I am getting a new error:

when running xfreerdp --version

error:
[14:19:07:120] [1441:02d9fd40] [ERROR][com.freerdp.client.x11] - failed to open display: 
[14:19:07:120] [1441:02d9fd40] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.

**Comment by JesusCalix** [comment]
Never mind, I didn't have installed xquartz. It is now working. Thank you a lot for your fixes!

**Comment by HenkPoley** [comment]
Is there a way to do https://github.com/Homebrew/homebrew-core/issues/68890#issuecomment-764746864 automatically on `brew install freerdp` ?

**Comment by carlocab** [comment]
This should be done by the additional flag I show here: https://github.com/Homebrew/homebrew-core/issues/68890#issuecomment-759760512

However, it seems that upstream's build scripts don't respect this. Can you try that and see if it works (after building from source)? If it does not, try the flag `"-DCMAKE_INSTALL_NAME_DIR=#{lib}"` in place of `"-DCMAKE_INSTALL_RPATH=#{lib}"`.

Let me know if it works so we can fix the formula for everyone else too.

**Comment by HenkPoley** [comment]
I'm checking that now.

`"-DCMAKE_INSTALL_RPATH=#{lib}"`  form the linked comment doesn't work. For some reason `brew` says "cmake . -DWITH_X11=ON -DBUILD_SHARED_LIBS=ON -DWITH_JPEG=ON" without the extra option.

Trying `"-DCMAKE_INSTALL_NAME_DIR=#{lib}"` next, and then your 2nd option.

(Actually I'm looking for an RDP client for macOS that supports Network Level Authentication (NLA). Commandline clients running under Xquartz is probably not going tot cut it.)

**Comment by carlocab** [comment]
You can try passing the `--verbose` flag to `brew install`, as otherwise, it truncates the build commands.

**Comment by HenkPoley** [comment]
This does work:

```ruby
  def install
    system "cmake", ".", *std_cmake_args, "-DWITH_X11=ON", "-DBUILD_SHARED_LIBS=ON", "-DWITH_JPEG=ON", "-DCMAKE_INSTALL_NAME_DIR=#{lib}"
    system "make", "install"
  end
```

E.g. `"-DCMAKE_INSTALL_NAME_DIR=#{lib}"`

**Comment by carlocab** [comment]
Awesome! I'll open a PR to add this fix.

**Comment by HenkPoley** [comment]
btw, this was on an M1 MacBook Pro. In case you want to add a checkbox there.
