### ISSUE TITLE
discount fails to build with option `--with-shared`

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew-core#6891]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I'm unable to install `discount` with the options `--with-fenced-code` and `--with-shared`. It appears that `--with-shared` is the problem, but I can't quite follow why from the logs.

Logs are here: https://gist.github.com/anonymous/d348e9efff83a9caef0c4f8452415f54

Please let me know if there's anything else I can do to help debug the problem.

A further note: this fails on a Sierra machine (10.12.1) at home, but works on a <strike>Yosemite</strike> El Capitan version at work. Not sure what that may mean, but I thought I would mention it.

**Comment by mistydemeo** [comment]
Hm, I can't repro on my Sierra machine. It looks like it's having trouble calling the `cpp` superenv shim. Just to check, if you `brew update` does it still fail for you now?

**Comment by telemachus** [comment]
@mistydemeo `brew update` told me that I was up-to-date already, but still no joy.

One other item of information that may or may not matter: I just updated this machine from El Capitan to Sierra with Homebrew already installed. In theory that shouldn't matter, but you never know. Also, now that I think about it, the machine at work is probably El Capitan too. (I can't keep the names straight any more...)

**Comment by mistydemeo** [comment]
> Xcode: 8.1
> CLT: N/A

I just noticed, the difference between your environment is that you're Xcode-only and I'm CLT-only. What's the configuration on the work machine?

**Comment by telemachus** [comment]
Xcode: 8.1
    CLT: 7.3.1.0.1.1461711523

When I get home, I'll install the CLT tools as well. Hopefully that will fix the problem.

**Comment by telemachus** [comment]
@mistydemeo Installing the CLT tools fixed my problem. Thank you very much again for seeing that.

I'm not sure if that's expected behavior though or still a bug, so I'm not closing this just yet. Any thoughts?

**Comment by ilovezfs** [comment]
It's still a bug since we still haven't caved in and decided to require the CLT, so everything is required to work with Xcode alone or it's a bug by definition.

**Comment by MikeMcQuaid** [comment]
Closing as there's no work ongoing on this issue, sorry.
