### ISSUE TITLE
Package Global fails to compile -- fix provided below

### ISSUE THREAD

**Issue by mlabbe** [Homebrew/homebrew-core#69079]
Package `global` failed to compile on my arm 11.1 system.  This is due to an error because `realpath` cannot be found.  The fix is to modify `configure` to include stdlib.h.

Line 14291 of configure on global-6.6.5:

    main(){ (void)realpath("/./tmp", (void *)0); return 0; }

Insert one line before that:
   
    #include<stdlib.h>
    main(){ (void)realpath("/./tmp", (void *)0); return 0; }

`configure` now succeeds.

**Comment by carlocab** [comment]
Please report this to global's mailing list, as they're in a much better position to fix this: https://www.gnu.org/software/global/maillist.html

**Comment by mlabbe** [comment]
Will they actually fix a macos issue?

**Comment by carlocab** [comment]
Why wouldn't they?

**Comment by mlabbe** [comment]
I've come to share your optimism! Bug reported. Thanks for the pointer.

**Comment by carlocab** [comment]
Great. There's nothing actionable here at the moment for homebrew/core, so I'm closing this for now.
