### ISSUE TITLE
brew install error wiht M1 chips

### ISSUE THREAD

**Issue by Lucife5604** [Homebrew/homebrew-core#69077]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- ✅ ran `brew update` and can still reproduce the problem?
- ✅ ran `brew doctor`, fixed all issues and can still reproduce the problem?
- ✅ ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- ✅ if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

when i installed the rubygem and trying to install the metasploit-framework, the bundle install finished tips me that the pg didn't installed ,i searched in internet,they show me that i need to install postgresql,so i try to use `brew install postgresql`,but something wrong.
## What happened (include command output)

when i try to install postgresql,error reported,At first, I thought it was because of the M1 chips,so i try to install wget,but the same error reported.
<details>
  <summary>Command output</summary>
  <pre>

  Updating Homebrew...
Error: dlopen(/Library/Ruby/Gems/2.6.0/gems/io-console-0.5.6/lib/io/console.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/io-console-0.5.6/lib/io/console.bundle - /Library/Ruby/Gems/2.6.0/gems/io-console-0.5.6/lib/io/console.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/reline-0.2.1/lib/reline.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/irb-1.3.1/lib/irb.rb:13:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/debrew/irb.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/debrew.rb:5:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/formula_installer.rb:13:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/cmd/install.rb:8:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/homebrew/Library/Homebrew/utils.rb:92:in `require?'
/opt/homebrew/Library/Homebrew/commands.rb:35:in `valid_internal_cmd?'
/opt/homebrew/Library/Homebrew/brew.rb:91:in `<main>'

  </pre>
</details>

## What you expected to happen

successful finished it.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install postgresql` and `brew install wget`

## brew config output
``` HOMEBREW_VERSION: 2.7.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 663b972f449b679512a2c0e3303569a2e9bfba7c
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 93f2b1591536d333678b0c1acf19bb829b5f30bd
Core tap last commit: 23 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
http_proxy: http://127.0.0.1:1087
https_proxy: http://127.0.0.1:1087
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_275
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
Rosetta 2: false ```

**Comment by SMillerDev** [comment]
This is missing the files from the last 2 checkboxes. Please provide the requirements, then we can reopen this.

**Comment by Lucife5604** [comment]
add brew doctor output 
`Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/php.h
  /usr/local/include/php_version.h
  /usr/local/include/zend.h
  /usr/local/include/zend_config.h
  /usr/local/include/zend_portability.h
  /usr/local/include/zend_types.h `
