### ISSUE TITLE
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951 

### ISSUE THREAD

**Issue by Vittorio-df** [Homebrew/homebrew-core#69090]
I was using gfortran on my MAC, and everything was working well. Few days ago, when I installed python and other related packages, gfortran started not to work anymore, giving some error messages. I think that the libraries of gfortran have been moved in other folder, so when I try to compile a code, it simply does not know where to find gfortran.

I will copy below the error message that I obtain when I run a code in gfortran:

`dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.23.dylib
  Referenced from: /usr/local/Cellar/gcc/10.2.0_2/libexec/gcc/x86_64-apple-darwin17/10.2.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions`

**Comment by carlocab** [comment]
Please complete the issue template. You can edit your original post to do. This issue can be reopened once you've done that.

**Comment by Vittorio-df** [comment]
Sorry I do not understand what I should add. Could you please explain me what I need to do?

***************************************************************
*  Postdoctoral Researcher in Mathematics
*  University of Naples "Federico II"
*  Department of Mathematics and Application "R. Caccioppoli"
*  Via Cintia, IT-80126 Naples, Italy
*  CELL:  +39 340 544 70 15
****************************************************************


________________________________
Da: Carlo Cabrera <notifications@github.com>
Inviato: venerdì 15 gennaio 2021 12:46
A: Homebrew/homebrew-core <homebrew-core@noreply.github.com>
Cc: Vittorio-df <deltafi.mat@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Homebrew/homebrew-core] gfortran: internal compiler error: Abort trap: 6 signal terminated program f951 (#69090)


Please complete the issue template. You can edit your original post to do. This issue can be reopened once you've done that.

**Comment by carlocab** [comment]
The issue template is contained in the textbox when you open a new issue: https://github.com/Homebrew/homebrew-core/issues/new?assignees=&labels=&template=bug.md

You can also see it here: https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by Vittorio-df** [comment]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I have done `brew config` and `brew doctor`, I receive the following warnings

`Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libasan.la
  /usr/local/lib/libatomic.la
  /usr/local/lib/libcilkrts.la
  /usr/local/lib/libfreetype.la
  /usr/local/lib/libg2c.la
  /usr/local/lib/libgd.la
  /usr/local/lib/libgfortran.la
  /usr/local/lib/libgmp.la
  /usr/local/lib/libgmpxx.la
  /usr/local/lib/libgomp.la
  /usr/local/lib/libitm.la
  /usr/local/lib/libjpeg.la
  /usr/local/lib/libmpc.la
  /usr/local/lib/libmpfr.la
  /usr/local/lib/libpng16.la
  /usr/local/lib/libquadmath.la
  /usr/local/lib/libssp.la
  /usr/local/lib/libssp_nonshared.la
  /usr/local/lib/libstdc++.la
  /usr/local/lib/libsupc++.la
  /usr/local/lib/libubsan.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/freetype2.pc
  /usr/local/lib/pkgconfig/gdlib.pc
  /usr/local/lib/pkgconfig/libpng16.pc
  /usr/local/lib/pkgconfig/zlib.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libatomic.a
  /usr/local/lib/libcilkrts.a
  /usr/local/lib/libfreetype.a
  /usr/local/lib/libfrtbegin.a
  /usr/local/lib/libg2c.a
  /usr/local/lib/libgd.a
  /usr/local/lib/libgfortran.a
  /usr/local/lib/libgmp.a
  /usr/local/lib/libgmpxx.a
  /usr/local/lib/libgomp.a
  /usr/local/lib/libiberty.a
  /usr/local/lib/libitm.a
  /usr/local/lib/libjpeg.a
  /usr/local/lib/libmpc.a
  /usr/local/lib/libmpfr.a
  /usr/local/lib/libpng16.a
  /usr/local/lib/libquadmath.a
  /usr/local/lib/libssp.a
  /usr/local/lib/libssp_nonshared.a
  /usr/local/lib/libstdc++.a
  /usr/local/lib/libsupc++.a
  /usr/local/lib/libz.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gmp

Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.


Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.


Warning: Your XQuartz (2.7.8) is outdated.
Please install XQuartz 2.7.11 (or delete the current version).
XQuartz can be updated using Homebrew Cask by running:
  brew reinstall xquartz

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/opt/isl/lib/libisl.19.dylib
  /usr/local/opt/libmpc/lib/libmpc.3.dylib
  /usr/local/opt/mpfr/lib/libmpfr.6.dylib

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install isl libmpc mpfr`

## What you were trying to do (and why)

I was running a code in fortran with gfortran as usually I have done, and it did not start to work anymore.

## What happened (include command output)

I obtained

`2$ gfortran -o pro caos.f 
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.23.dylib
  Referenced from: /usr/local/Cellar/gcc/10.2.0_2/libexec/gcc/x86_64-apple-darwin17/10.2.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
`
## What you expected to happen

I expected to successfully compile my code, that not occurred.

## Step-by-step reproduction instructions (by running `brew install` commands)

I did it also

`2$ brew install gfortran
Warning: gcc 10.2.0_2 is already installed and up-to-date
To reinstall 10.2.0_2, run `brew reinstall gcc`

Hope, I filled all the issues template. Thanks for your help.

**Comment by Vittorio-df** [comment]
I tried to rewrite my question following the issue template.
I hope this meets the requirements you suggested me.
Thanks for your help!

**Comment by Vittorio-df** [comment]
I tried to rewrite my question following the issue template.
I hope this meets the requirements you suggested me.
Thanks for your help!

________________________________
Da: Carlo Cabrera <notifications@github.com>
Inviato: venerdì 15 gennaio 2021 12:55
A: Homebrew/homebrew-core <homebrew-core@noreply.github.com>
Cc: Vittorio-df <deltafi.mat@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Homebrew/homebrew-core] gfortran: internal compiler error: Abort trap: 6 signal terminated program f951 (#69090)


The issue template is contained in the textbox when you open a new issue: https://github.com/Homebrew/homebrew-core/issues/new?assignees=&labels=&template=bug.md

You can also see it here: https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md

**Comment by carlocab** [comment]
Unfortunately, there's not much we can do to help you here, because:

>Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

The only advice I can offer is to try to reinstall gcc, with, say
```
brew uninstall gcc
brew install --build-from-source gcc
```
This will take quite a while as gcc will have to be built from source. If you don't want to build from source, you can try one of the pre-built binary installers here: https://github.com/fxcoudert/gfortran-for-macOS/releases

**Comment by Vittorio-df** [comment]
Thank you very much for your help.
However I was able to fix the problem by basically using brew unlink e brew link.
I had the last version of gcc, there was only not a link between gfortran and its library.
I found very useful brew doctor, who helped me in finding where there were the issues
to solve. Thanks again for your prompt help.

________________________________
Da: Carlo Cabrera <notifications@github.com>
Inviato: sabato 16 gennaio 2021 05:04
A: Homebrew/homebrew-core <homebrew-core@noreply.github.com>
Cc: Vittorio-df <deltafi.mat@live.it>; Author <author@noreply.github.com>
Oggetto: Re: [Homebrew/homebrew-core] gfortran not working on MAC for internal compiler error (#69090)


Unfortunately, there's not much we can do to help you here, because:

Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

The only advice I can offer is to try to reinstall gcc, with, say

brew uninstall gcc
brew install --build-from-source gcc


This will take quite a while as gcc will have to be built from source. If you don't want to build from source, you can try one of the pre-built binary installers here: https://github.com/fxcoudert/gfortran-for-macOS/releases
