### ISSUE TITLE
Openjdk ARM bottle installs but with errors

### ISSUE THREAD

**Issue by unitof** [Homebrew/homebrew-core#69102]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

## brew gist-logs openjdk

https://gist.github.com/e4b731384342f292c06fdd1014bfaf09

## What you were trying to do (and why)

Install @fxcoudert's new [openjdk ARM bottle](https://github.com/Homebrew/homebrew-core/pull/68946)

## What happened (include command output)

`openjdk` installs, but with a `Failed applying an ad-hoc signature` error in the Pouring step, and a nonspecific (unrelated?) `post-install step did not complete successfully` warning.

<details>
  <summary>`brew install openjdk` output</summary>
  <pre>

~ ▶ brew install openjdk
==> Downloading https://homebrew.bintray.com/bottles/openjdk-15.0.1.arm64_big_sur.bottle.tar.gz
Already downloaded: /Users/jacob/Library/Caches/Homebrew/downloads/41ae68b426b445d139450b9d3a63e9f1d9b56f8e803dbd366c1e64929e739315--openjdk-15.0.1.arm64_big_sur.bottle.tar.gz
==> Pouring openjdk-15.0.1.arm64_big_sur.bottle.tar.gz
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openjdk`
==> Caveats
For the system Java wrappers to find this JDK, symlink it with
  sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
This is a beta version of openjdk for Apple Silicon
(openjdk 16 preview).

openjdk is keg-only, which means it was not symlinked into /opt/homebrew,
because it shadows the macOS `java` wrapper.

If you need to have openjdk first in your PATH run:
  echo 'export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"' >> ~/.zshrc

For compilers to find openjdk you may need to set:
  export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"

==> Summary
🍺  /opt/homebrew/Cellar/openjdk/15.0.1: 607 files, 305.2MB

  </pre>
</details>

<details>
  <summary>proof it did install anyway</summary>
  <pre>

~ ▶ /opt/homebrew/opt/openjdk/bin/java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+14)
OpenJDK 64-Bit Server VM (build 16+14, mixed mode)

  </pre>
</details>

<details>
  <summary>`brew postinstall openjdk --verbose` output</summary>
  <pre>

~ ▶ brew postinstall openjdk --verbose
==> Postinstalling openjdk
/usr/bin/sandbox-exec -f /private/tmp/homebrew20210115-13722-1xaeup5.sb nice ruby -W0 -I $LOAD_PATH -- /opt/homebrew/Library/Homebrew/postinstall.rb /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openjdk`

  </pre>
</details>

## What you expected to happen

Installation to complete without errors, and `Postinstall` step to complete successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

With `homebrew` running on an M1 Mac (and installed to `/opt/homebrew`), run `brew update && brew install openjdk`.

**Comment by carlocab** [comment]
Is this distinct from #69100?

**Comment by jamogriff** [comment]
@carlocab It may be the same issue. All of my output and hardware matches @unitof report, and after seeing #69100 and running `brew config` XCode is also N/A.

**Comment by carlocab** [comment]
Yes, looks to me like a duplicate. @unitof, let me know if I'm mistaken and we can reopen this.

**Comment by unitof** [comment]
Yep! Identical. And I also have `Xcode: N/A`. Thanks all.
