### ISSUE TITLE
Mysql 8.0.22 Linux brew link broken

### ISSUE THREAD

**Issue by tscolari** [Homebrew/homebrew-core#69274]
# Bug report

When trying to install mysql on Linux, it fails because it can't download the file:

```
https://linuxbrew.bintray.com/bottles/mysql-8.0.22_1.x86_64_linux.bottle.1.tar.gz
```

The link seems to be broken.

**Comment by carlocab** [comment]
>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**
