### ISSUE TITLE
Building Qt5 from source fails due to missing cmake build dependency

### ISSUE THREAD

**Issue by vit9696** [Homebrew/homebrew-core#69300]
# Bug report

## What you were trying to do (and why)

I am trying to build qt from source due to several patches for Big Sur not present in the latest release. The command I use is `brew install qt --HEAD`.

## What happened (include command output)

It failed with a message from configure script that `cmake` command was not found.

<details>
  <summary>Command output</summary>
  <pre>

Last 15 lines from /Users/runner/Library/Logs/Homebrew/qt/01.configure:
237
-qt-libjpeg
238
-qt-freetype
239
-qt-pcre
240
-nomake
241
examples
242
-nomake
243
tests
244
-no-rpath
245
-pkg-config
246
-dbus-runtime
247
-proprietary-codecs
248

249
+ cd qtbase
250
+ /private/tmp/qt-20210118-85532-10ieis1/qtbase/configure -top-level -verbose -prefix /usr/local/Cellar/qt/HEAD-9ab5968 -release -opensource -confirm-license -system-zlib -qt-libpng -qt-libjpeg -qt-freetype -qt-pcre -nomake examples -nomake tests -no-rpath -pkg-config -dbus-runtime -proprietary-codecs
251
/private/tmp/qt-20210118-85532-10ieis1/qtbase/configure: line 299: cmake: command not found
252

253
READ THIS: https://docs.brew.sh/Troubleshooting
254

255
These open issues may also help:
256
qt 6.0.0 https://github.com/Homebrew/homebrew-core/pull/68134
257
Please create pull requests instead of asking for help on Homebrew's GitHub,
258
Twitter or any other official channels.
259
Error: Process completed with exit code 1.

  </pre>
</details>

## What you expected to happen

The [formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qt.rb#L29) has missing `depends_on "cmake" => :build`, which I believe is the cause of the issue. Apparently with cmake installed it also fails with the same error, likely because building is done in an isolated PATH environment.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install qt --HEAD`

**Comment by carlocab** [comment]
Sorry, but `HEAD` builds are not supported, which is why you see this at the end of the output:
```
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

**Comment by paperchalice** [comment]
The head version of Qt5 is now qt6, a break change.
