### ISSUE TITLE
xapian --with-ruby fails to install

### ISSUE THREAD

**Issue by jslabovitz** [Homebrew/homebrew-core#6938]
### Bug reports:

When installing Xapian with the '--with-ruby' option, the formula refuses to install because Xapian requires a version of Ruby later than macOS's 2.0.0p648. However, even if a sufficient Ruby is installed with Homebrew (in my case, 2.3.1p112), Xapian won't find that version unless explicitly specified on the command line like so:

    RUBY=/usr/local/bin/ruby brew install xapian --with-ruby

The above invocation works, but it seems to me that the formula should probably (1) have a dependency on Homebrew's Ruby, and (2) use Homebrew's Ruby instead of the system ruby without any user interaction.

https://gist.github.com/0c21fb576aee63f0848e3c46c1f61c7e

**Comment by dunn** [comment]
Do you know what version of Ruby is required?  It should be as simple as adding something like
```ruby
depends_on :ruby => ["2.1", :optional]
```
Replacing "2.1" with the minimum version required.

**Comment by jslabovitz** [comment]
Yes, that line seems to have worked as-is (Xapian does indeed require 2.1+). Thanks! Would you like me to send a pull request, or do you want to do this?

**Comment by dunn** [comment]
A PR would be great!
