### ISSUE TITLE
Rabbitmq fails to install. 404 error instead.

### ISSUE THREAD

**Issue by meowlvaro** [Homebrew/homebrew-core#69485]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ failed ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ attached ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `rabbitmq`

## What happened (include command output)

brew config + brew doctor:

<pre>
ziggy@Alvaros-MacBook-Pro ~ % brew config
HOMEBREW_VERSION: 2.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bca4804a9e48de5319383d3eddadaa7f054c77da
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ab61019e86e72aced43da0e56da457099e580992
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 15.0.1
macOS: 10.15.7-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
ziggy@Alvaros-MacBook-Pro ~ % brew doctor
Your system is ready to brew.
</pre>

<details>
  <summary>Command output</summary>
  <pre>

ziggy@Alvaros-MacBook-Pro ~ % brew install rabbitmq
Warning: Treating rabbitmq as a formula. For the cask, use homebrew/cask/rabbitmq
==> Downloading https://homebrew.bintray.com/bottles/jpeg-9d.catalina.bottle.tar.gz
Already downloaded: /Users/ziggy/Library/Caches/Homebrew/downloads/9ed6b08679bb12bb63055c727e5cdcb7f0813e6a89a66ee35a2b2b83d1c30ac9--jpeg-9d.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.37.catalina.bottle.tar.gz
Already downloaded: /Users/ziggy/Library/Caches/Homebrew/downloads/c6068aecd9940e8c341aca2bfebe2b9ae0aa7e54c0b0cdd606b1b0d3c0d764eb--libpng-1.6.37.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.2.0.catalina.bottle.tar.gz
Already downloaded: /Users/ziggy/Library/Caches/Homebrew/downloads/683d8a4093b59a342df10cdb53ca6470084860bf0127511c1483729602518776--libtiff-4.2.0.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/wxmac-3.0.5.1_1.catalina.bottle.tar.gz
Already downloaded: /Users/ziggy/Library/Caches/Homebrew/downloads/820b9bbf8989360bae3d657fa524cde0af0135ded191f47f2d3672f710c39a35--wxmac-3.0.5.1_1.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/erlang-23.2.3.catalina.bottle.tar.gz
Already downloaded: /Users/ziggy/Library/Caches/Homebrew/downloads/b4dee7782a2b536f8d3b66a94c0e0d8885b0322a42acfd5ba0e75269c7cac3cb--erlang-23.2.3.catalina.bottle.tar.gz
==> Downloading https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.10/rabbitmq-serv
##O#- #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "rabbitmq"
Download failed: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.10/rabbitmq-server-generic-unix-3.8.10.tar.xz

  </pre>
</details>

## What you expected to happen

Rabbitmq should install. It 404s instead

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew update`
2. `brew install rabbitmq`

**Comment by carlocab** [comment]
Will be fixed by #69484.
