### ISSUE TITLE
RabbitMQ missing user 

### ISSUE THREAD

**Issue by yopiti** [Homebrew/homebrew-core#69706]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing and running the current version of rabbitMQ. 

$ rabbitmqctl status
id: rabbitmq: no such user
/opt/local/sbin/rabbitmqctl: line 32: [: too many arguments
id: rabbitmq: no such user
/opt/local/sbin/rabbitmqctl: line 34: [: too many arguments

## What happened (include command output)

Showing error message. 

RabbitMQ is looking for a user called rabbitmq which is hardcoded in /opt/local/sbin/rabbitmqctl, but not existing.

<details>
  <summary>Command output</summary>
  <pre>
$ rabbitmqctl status
id: rabbitmq: no such user
/opt/local/sbin/rabbitmqctl: line 32: [: too many arguments
id: rabbitmq: no such user
/opt/local/sbin/rabbitmqctl: line 34: [: too many arguments

  </pre>
</details>

## What you expected to happen

To run

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install rabbitmq

**Comment by carlocab** [comment]
You haven't provided all the requested information in the issue template.

>**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

**Comment by gromgit** [comment]
> RabbitMQ is looking for a user called rabbitmq which is hardcoded in /opt/local/sbin/rabbitmqctl, but not existing.

`/opt/local` is the default _MacPorts_ prefix, so unless you installed Homebrew there, it's not a Homebrew issue.

**Comment by yopiti** [comment]
Thanks for the information. Apparently an old old old installation got in the way. Sorry!
