### ISSUE TITLE
Upgrade wireshark formula to use current version of lua (instead of lua@5.1)

### ISSUE THREAD

**Issue by theschles** [Homebrew/homebrew-core#69753]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Please update the [wireshark formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/wireshark.rb) to use a current version of lua [instead of lua@5.1](https://github.com/Homebrew/homebrew-core/blob/88c30f77d8b0a39646e6e960398dbf8f34802353/Formula/wireshark.rb#L29) -- which is deprecated.

 https://formulae.brew.sh/formula/wireshark says the lua used is deprecated:
![image](https://user-images.githubusercontent.com/901430/105776804-18859f80-5f1e-11eb-8d6b-338517c7efa4.png)

## What happened (include command output)

`brew doctor` is reporting I should update lua@5.1 to a non-deprecated lua version.  So I tried to remove lua@5.1 before adding current lua...and was told that wireshark was dependent on lua@5.1.

<details>
  <summary>Command output</summary>
  <pre>
...
...ran brew update and brew upgrade and everything is up to date...
...
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  wine
  unrar

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1
➜  ~ brew uninstall lua@5.1
Error: Refusing to uninstall /usr/local/Cellar/lua@5.1/5.1.5_8
because it is required by wireshark, which is currently installed.
You can override this and force removal with:
  </pre>
</details>

## What you expected to happen

wireshark should be dependent on a non-deprecated version of lua 
(FYI lua 5.1, 5.2, and 5.3 have a CVE of score 5.0 against them...not horrible...but not great)

## Step-by-step reproduction instructions (by running `brew install` commands)

1. brew update
2. brew install wireshark
3. ...see that it installs lua@5.1
4. brew doctor
5. ...holy cow lua@5.1 is deprecated

Thank you in advance for your help!

**Comment by carlocab** [comment]
Wireshark is not compatible with Lua5.3 or later. You'll need to take this up with the Wireshark devs, I'm afraid.

**Comment by theschles** [comment]
@carlocab please re-open: [per Wireshark's own wiki](https://gitlab.com/wireshark/wireshark/-/wikis/BuildingAndInstalling#building-with-homebrew), current lua is what's required to build wireshark on OSX:
`2. Install all the necessary development packages using homebrew: brew install c-ares cmake glib gnutls lua qt5.`

Thus I would think it's a matter of re-working the homebrew formula -- correct?

**Comment by carlocab** [comment]
We tried before and it didn't work. I suppose it's worth another shot: #69836

**Comment by SMillerDev** [comment]
Feature requests (such as this) are required to come as pull requests for the homebrew project so the issue is staying closed.
