### ISSUE TITLE
AddressSanitizer fails to work on llvm on M1 machines

### ISSUE THREAD

**Issue by deepankarsharma** [Homebrew/homebrew-core#69786]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [Y ] ran `brew update` and can still reproduce the problem?
- [Y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [This did not work]
- [Y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Run a simple hello world c++ executable compiled with brew clang and AddressSanitizer enabled and on M1 hardware. Was running this to create a minimum repro to show that AddressSanitizer does not work under brew clang on M1 hardware. 

## What happened (include command output)

foobar % cat main.cpp
#include <vector>
#include <iostream>

int main(int argc, char** argv) {
	std::cout << "hello world!" << std::endl;
	return 0;
}

foobar % /opt/homebrew/opt/llvm/bin/clang++ -fsanitize=address main.cpp -o main
foobar % ./main                                                                
==5007==ERROR: AddressSanitizer failed to allocate 0x200004000 (8589950976) bytes at address fffffc000 (errno: 12)
==5007==ReserveShadowMemoryRange failed while trying to map 0x200004000 bytes. Perhaps you're using ulimit -v
zsh: abort      ./main

## What you expected to happen

Expected the simple hello world c++ program to work correctly.

## Step-by-step reproduction instructions (by running `brew install` commands)
Assuming you have a Mac machine with M1 chips

1. brew install llvm
2. Create file called main.cpp with following content 
#include <iostream>

int main(int argc, char** argv) {
	std::cout << "hello world!" << std::endl;
	return 0;
}
3. Compile file using -/opt/homebrew/opt/llvm/bin/clang++ -fsanitize=address main.cpp -o main
4. Run compiled executable using ./main
5.  You will get the following error==5007==ERROR: AddressSanitizer failed to allocate 0x200004000 (8589950976) bytes at address fffffc000 (errno: 12)
==5007==ReserveShadowMemoryRange failed while trying to map 0x200004000 bytes. Perhaps you're using ulimit -v
zsh: abort      ./main

Brew Config is
foobar % brew config                                                           
HOMEBREW_VERSION: 2.7.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bca4804a9e48de5319383d3eddadaa7f054c77da
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2487ee53605f8295d004c43bf47f503f10d49b0
Core tap last commit: 78 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.1-arm64
CLT: 12.3.0.0.1.1607026830
Xcode: 12.3
Rosetta 2: false

foobar % brew doctor
Your system is ready to brew.

**Comment by carlocab** [comment]
Is this an issue only with Homebrew LLVM? i.e., are you unable to reproduce this failure with non-Homebrew LLVM?

**Comment by deepankarsharma** [comment]
Yes Apple clang works fine. However they do not ship libfuzzer, which is why I installed home-brew.

**Comment by carlocab** [comment]
I don't mean Apple Clang. I mean LLVM built from the same source the formula is.

**Comment by deepankarsharma** [comment]
Sorry my homebrew foo is weak. Do you mean running something along the lines of ?
brew install --build-from-source llvm

**Comment by carlocab** [comment]
No, that would still use Homebrew to build LLVM. You need to install LLVM not using Homebrew. See the downloads page at https://llvm.org. I think they have pre-built binaries you can use so you don't need to build from source.

**Comment by deepankarsharma** [comment]
Can confirm that a trunk build of llvm from git built using the following configuration works (ie both AddressSanitizer and the Fuzzer work)

/opt/homebrew/opt/cmake/bin/cmake -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;openmp;polly;mlir" -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" -DLLVM_POLLY_LINK_INTO_TOOLS=ON -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_BUILD_LLVM_C_DYLIB=ON -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_LIBCXX=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INSTALL_UTILS=ON -DLLVM_ENABLE_Z3_SOLVER=OFF -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_TARGETS_TO_BUILD=all -DLLVM_CREATE_XCODE_TOOLCHAIN=ON -DLLDB_USE_SYSTEM_DEBUGSERVER=ON -DLLDB_ENABLE_PYTHON=OFF -DLLDB_ENABLE_LUA=OFF -DLLDB_ENABLE_LZMA=OFF -DLIBOMP_INSTALL_ALIASES=OFF -DLLDB_INCLUDE_TESTS=OFF ../llvm

**Comment by carlocab** [comment]
Which commit did you build from though? This could be a bug that's already been fixed, but isn't in the release tarball that we use.

We use this release: https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0

**Comment by deepankarsharma** [comment]
302432f75dadcc78aa4764f3e5e86bf07466a554

**Comment by carlocab** [comment]
Yes, that's much newer than the one in the stable release. We can wait for a new release that includes this commit (though the latest stable release isn't building, unfortunately: #68393), or you can try back-porting a patch to 11.0.

**Comment by deepankarsharma** [comment]
Thanks for the prompt responses on this bug! Really appreciate it.

**Comment by carlocab** [comment]
llvm has just been upgraded to 11.0.1. Can you check if your issue has been fixed in this version? You can do
```
brew update && brew upgrade llvm
```

**Comment by fxcoudert** [comment]
Closing this as an upstream issue.
