### ISSUE TITLE
RISC-V cross compiler on m1 fails to build; kludgey workaround included

### ISSUE THREAD

**Issue by robertlipe** [Homebrew/homebrew-core#69846]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [N/A] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Enjoy glorious M1 hosted speed when building embedded RISC-V code. (Yes, I know that there are like ten of us in the world that care about such a crazy combination and the x86_64 hosted version works swimmingly well.)

This *probably* affects every cross compilation with this version and it a step that someone will have to work through to get "normal" GCC builds working.

Mostly, I'm trying to get this issue on record (google search) and to identify the right team to talk through a better fix. I totally get the rarity of cross compilation on Mac hosts and I'm lucky that the uncommon part - the RISC-V part - works great and this is "just" a configure issue that's tripping over an assumption that all Darwin is x64. I just need to find who the right team to help land a proper fix it. 

I know that there's going to be an intricate series of steps involving M1 as a GCC(GNU toolchain) host (that's the issue here), GCC as an ARM8.3/M1 target to barf out the right opcodes, and GCC as an BigSur/M1 to handle OS calling conventions, system call interfaces, process startup and teardown. I'm pretty sure this is going to be a game of hot potato as there's whatever code that Homebrew is using, the FSF GCC, and whichever of the vendor  branches (SiFive? Kendryte? Nucleisys?) is in play here. GCC's config files were also widely shared with other projects at some point, so it's not at all clear to me where the authoritative version of this file should be.

The good thing (for me, as I've been out of the GNU chain internals biz for ~20 years) is that this is an issue caused by the use of Precompiled Headers (don't care and probably irrelevant for cross anyway) and we can get away with just more thoroughly ignoring them as going the other way (making the startup code call the Darwin x64 code) 

## What happened (include command output)

Add  tap "riscv/riscv"

<details>
  <summary>Building GCC cross compiler fails on host-side</summary>
  <pre>

  time brew install riscv-gnu-toolchain --with-multilib # (this works great on x64)

  (time passes. Oh, so much time.)
  🍺  /opt/homebrew/Cellar/gnu-sed/4.8: 12 files, 602.0KB
==> Installing riscv/riscv/riscv-gnu-toolchain dependency: libmpc
==> Pouring libmpc-1.2.1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/libmpc/1.2.1: 13 files, 432.8KB
==> Installing riscv/riscv/riscv-gnu-toolchain dependency: isl
==> Pouring isl-0.23.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/isl/0.23: 72 files, 5.0MB
==> Installing riscv/riscv/riscv-gnu-toolchain --with-multilib
==> ./configure --prefix=/opt/homebrew/Cellar/riscv-gnu-toolchain/master --enabl
==> make
Last 15 lines from /Users/robertlipe/Library/Logs/Homebrew/riscv-gnu-toolchain/02.make:
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_save(__sFILE*) in libbackend.a(ggc-common.o)
      gt_pch_restore(__sFILE*) in libbackend.a(ggc-common.o)
      toplev::main(int, char**) in libbackend.a(toplev.o)
      toplev::main(int, char**) in libbackend.a(toplev.o)
ld: symbol(s) not found for architecture arm64
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lto-dump] Error 1
make[2]: *** Waiting for unfinished jobs....

  </pre>
</details>

## What you expected to happen

Regale in glorious cross-compilation in full, hot,  RISCV-on-ARM action glory.

The nice thing is that you can just comment out the code that configures the (non-working) stub that sets up the Makefile to include the host-darwin code that's calling the HOST_HOOK instead 

## Step-by-step reproduction instructions (by running `brew install` commands)

brew tap "riscv/riscv"
time brew install riscv-gnu-toolchain --with-multilib. (I don't think multiline is involved. I just need that for my GCC target)

Now that you've burned 12 minutes of compute time (sigh) while configure looks for stdio.h for the trillionth time, patch 
~/Library/Caches/Homebrew/riscv-gnu-toolchain--git/riscv-gcc/gcc/confg.host and just neutralize the code that would have added it. 
<pre>
 | i[34567]86-*-go32* \
 | vax-*-vms*)
    echo "*** Configuration for host ${host} not supported" 1>&2
    exit 1
    ;;
esac

# Common parts for widely ported systems.
case ${host} in
  *-darwin*)
    # Generic darwin host support.
    # out_host_hook_obj=host-darwin.o
    # #host_xmake_file="${host_xmake_file} x-darwin"
    echo "Whee"
    ;;
esac

case ${host} in
  aarch64*-*-freebsd* | aarch64*-*-linux* | aarch64*-*-fuchsia*)
    case ${target} in
      aarch64*-*-*)
</pre>

This is wrong because it probably breaks PCH on native builds, but I think a native GCC for M1 is still some time away. This matches overly broadly, but this is one hammer that brings success.

So I think I've done better than a "help, is broken" analysis on all this, and I DID verify that this compiler successfully compiles and links my OS kernel https://github.com/robertlipe/riscv7 and that the debugger connects to my ICE. So lots of Really Hard stuff just worked. Were tripping over something relatively easy; I just need help finding the right people to talk this through.

Please help get  to either accept a variation of this change (I'll work with you on making the test above more specific if you can help me identify the triplet) or to connect with the right right people to work out a fix upstream so that I can help fix this in some upstream repo and help get it downstreamed or cherry-picked into the Homebrew toolkit.

I <3 that I can do a cold build of my kernel in 1.6 seconds. :-) 

Thanx for being awesome!

**Comment by carlocab** [comment]
I appreciate the effort you put into this, but this isn't the right place to post this.

You're looking for https://github.com/riscv/homebrew-riscv. I suspect the place you want to submit your patch is https://github.com/riscv/riscv-gnu-toolchain.

**Comment by robertlipe** [comment]
Thanx for the super-speedy response. I can copy-paste all night long as
long as I get incrementally closer to the right place. :-)

Thank you!
