### ISSUE TITLE
Update to Graphviz 2.46.0

### ISSUE THREAD

**Issue by jarrodmillman** [Homebrew/homebrew-core#69900]
I am a core developer of PyGraphviz (​https://github.com/pygraphviz/pygraphviz) and NetworkX (​https://github.com/networkx/networkx). Some of our users use brew to install Graphviz (https://formulae.brew.sh/formula/graphviz).  Graphviz has recently fixed a lot of issues.

It would be great if you could update to the current stable release (2.46.0): ​https://gitlab.com/graphviz/graphviz/-/blob/master/CHANGELOG.md#2460-2021-01-18

Thanks!

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
