### ISSUE TITLE
Homebrew : lammps bottle unavailable! 

### ISSUE THREAD

**Issue by MRR71** [Homebrew/homebrew-core#69976]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [tried ] ran `brew update` and can still reproduce the problem?
- [tried] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [tried] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [tried] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to install lammps using $brew install lammps$ on my M1 Macos (Big Sur 11.1) in order to run molecular dynamics simulations. 

## What happened (include command output)

Everytime i run $brew doctor$, it shows ready to use, but $brew install lammps$ always fails and shows the following error message:

<details>
  <summary>Error: lammps: no bottle available! You can try to install from source with:
brew install --build-from-source lammps
Please note building from source is unsupported. You will encounter build failures with some formulae. If you experience any issues please create pull requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.</summary>
  <pre>

  </pre>
</details>

## What you expected to happen

To see lammps installation successful

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install lammps
![brew_issues](https://user-images.githubusercontent.com/45832744/106232114-6f0a0c80-61b0-11eb-9f5e-618b58fa67be.jpg)

**Comment by jonchang** [comment]
> You can try to install from source with:
>       brew install --build-from-source lammps
> Please note building from source is unsupported. You will encounter build
> failures with some formulae. If you experience any issues please create pull
> requests instead of asking for help on Homebrew's GitHub, Twitter or any other
> official channels.
>

**Comment by MRR71** [comment]
Hi, thanks. But $brew install --build-from-source lammps$ also fails and shows: 

_CMake Error at completions/cmake_install.cmake:49 (file): file cannot create directory:
  /etc/opt/homebrew/Cellar/kim-api/2.2.1/bash_completion.d.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:87 (include)
make: *** [install] Error 1_

COuld you please help in this regard? Thank you.

**Comment by SMillerDev** [comment]
Then it's clearly not compatible with arm yet. You'll have to report this to the developers instead.

**Comment by avasyanin** [comment]
To repair building lammps from source on the M1 edit its formula:
$brew edit lammps:
Add the line 
    args << "-DBASH_COMPLETION_COMPLETIONSDIR=#{bash_completion}"
after the line
    args << "-DZSH_COMPLETION_COMPLETIONSDIR=#{zsh_completion}"
and run $brew install --build-from-source lammps

**Comment by MRR71** [comment]
> To repair building lammps from source on the M1 edit its formula:
> $brew edit lammps:
> Add the line
> args << "-DBASH_COMPLETION_COMPLETIONSDIR=#{bash_completion}"
> after the line
> args << "-DZSH_COMPLETION_COMPLETIONSDIR=#{zsh_completion}"
> and run $brew install --build-from-source lammps

Hi, many thanks. Could you please explain a bit more? I am complete new to command line/terminal, so can't really understand how I should execute your instructions. Specially, how and where I should add the line that you suggested?
Thanks again and I look forward to hearing from you.

**Comment by avasyanin** [comment]
> Hi, many thanks. Could you please explain a bit more? I am complete new to command line/terminal, so can't really understand how I should execute your instructions. Specially, how and where I should add the line that you suggested?

Sorry, there was a mistake in my previous message. You need to edit kim-api's formula, not lammps's. Run in the terminal
`brew edit kim-api`
This command opens lammps's formula in the default editor (in my case it will be vim).
Find the line
args << "-DZSH_COMPLETION_COMPLETIONSDIR=#{zsh_completion}"
and put the cursor on it. If your editor is also vim press 'o' button (lowercase 'o') and paste the line
args << "-DBASH_COMPLETION_COMPLETIONSDIR=#{bash_completion}"
below.
Press 'ESC', then immediately ':wq' and 'Enter' to save the formula.

Now you should be able to run 
`brew install --build-from-source lammps`
without errors.

**Comment by MRR71** [comment]
> > Hi, many thanks. Could you please explain a bit more? I am complete new to command line/terminal, so can't really understand how I should execute your instructions. Specially, how and where I should add the line that you suggested?
> 
> Sorry, there was a mistake in my previous message. You need to edit kim-api's formula, not lammps's. Run in the terminal
> `brew edit kim-api`
> This command opens lammps's formula in the default editor (in my case it will be vim).
> Find the line
> args << "-DZSH_COMPLETION_COMPLETIONSDIR=#{zsh_completion}"
> and put the cursor on it. If your editor is also vim press 'o' button (lowercase 'o') and paste the line
> args << "-DBASH_COMPLETION_COMPLETIONSDIR=#{bash_completion}"
> below.
> Press 'ESC', then immediately ':wq' and 'Enter' to save the formula.
> 
> Now you should be able to run
> `brew install --build-from-source lammps`
> without errors.

Many thanks avasyanin ! It worked. I really appreciate your time and kind help.
Bests.
