### ISSUE TITLE
Missing Aide Configuration File

### ISSUE THREAD

**Issue by marcus-cr** [Homebrew/homebrew-core#6998]
### Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Posting new issue (prior to personally resolving and submitting pull request with resolution) to confirm that this is _not_ a local issue. The configuration file for Aide is not created after installing. I apologize if I strayed from the contribution guidelines, just want confirmation before spending time on this issue.

**Comment by ilovezfs** [comment]
You are correct, it is not a local configuration issue for you.

**Comment by ilovezfs** [comment]
We'd welcome a PR fixing this, @marcus-cr

**Comment by marcus-cr** [comment]
Homebrew (and Ruby) are incredibly new to me so I'll see what I can do to remedy this, @ilovezfs.
Currently working with alternative conf file, many of its options aren't applicable to macOS.
