### ISSUE TITLE
Can't install SBT and Maven due to 'NameError: uninitialized constant Language::Java'

### ISSUE THREAD

**Issue by mthmulders** [Homebrew/homebrew-core#70148]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to install SBT and Maven.

## What happened (include command output)

Installation fails.

<details>
  <summary>Command output</summary>
  <pre>
Error: An exception occurred within a child process:
  NameError: uninitialized constant Language::Java
  </pre>
</details>

* [`brew gist-logs sbt` output](https://gist.github.com/c0d38d33ece24a4c05117401ed316456)
* [`brew gist-logs maven` output](https://gist.github.com/38016c5a0cbc13e77f0aa81e59cb863a)

## What you expected to happen

Installation succeeds.

## Step-by-step reproduction instructions (by running `brew install` commands)

* `brew install sbt`
* `brew install maven`

I've even completely uninstalled and installed Homebrew but the problem persists.

**Comment by carlocab** [comment]
Should be fixed by https://github.com/Homebrew/brew/pull/10471.

**Comment by carlocab** [comment]
Closed in https://github.com/Homebrew/brew/commit/3f4bcd7eb25e9f8947c058bd28f630dc2b791288.
