### ISSUE TITLE
Latest versions of node & npm

### ISSUE THREAD

**Issue by CodeByZach** [Homebrew/homebrew-core#70189]
I have the latest version of [node](https://formulae.brew.sh/formula/node) (15.7.0 at the time of this comment) installed. Per https://github.com/Homebrew/homebrew-core/pull/69816, it comes with npm version 7.4.3 by default.

The issue:
When I run `npm --global outdated;` this is the output:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/20159826/106532882-15128b00-64bf-11eb-869a-051796aae781.png">

Of course, downgrading to this "latest" version breaks the existing installation. Does anyone understand what's going on here?

Thanks

**Comment by alebcay** [comment]
Please provide all of the information requested in the [issue template](https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE/bug.md). We will not be able to assist you in investigating your issue further without this information.

**Comment by gromgit** [comment]
Alternatively, if you're just asking a question, https://github.com/Homebrew/discussions/discussions is a more appropriate venue.

**Comment by carlocab** [comment]
Please use the issue template (we can reopen this when you've done that), or use the discussions page instead. (If the issue template seems to not apply, then definitely use the discussions page.) Thanks!
