### ISSUE TITLE
bottle for grpc 1.35 doesn't work for CMake

### ISSUE THREAD

**Issue by sighingnow** [Homebrew/homebrew-core#70205]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install grpc using `brew install grpc`, then find the package using cmake `find_package(gRPC)`.

## What happened (include command output)

CMake complains ( https://github.com/alibaba/libvineyard/runs/1812622889?check_suite_focus=true ):

<details>
  <summary>Command output</summary>
  <pre>

CMake Error at /usr/local/lib/cmake/c-ares/c-ares-config.cmake:25 (add_library):
  add_library cannot create imported target "c-ares::cares_shared" because
  another target with the same name already exists.
Call Stack (most recent call first):
  /usr/local/lib/cmake/grpc/modules/Findc-ares.cmake:18 (find_package)
  /usr/local/lib/cmake/grpc/gRPCConfig.cmake:15 (find_package)
  thirdparty/etcd-cpp-apiv3/CMakeLists.txt:40 (find_package)

  </pre>
</details>

## What you expected to happen

It should work with cmake.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install grpc` then have a `find_package(gRPC)` in CMakeLists.txt then run cmake.

**Comment by SMillerDev** [comment]
We don't ship our own pkg-config files so this needs to be reported upstream.

**Comment by carlocab** [comment]
Your step-by-step reproduction doesn't seem to be enough either. Here are the steps you suggested executed on a GitHub runner: https://github.com/carlocab/grpc-cmake/runs/1814003731?check_suite_focus=true

**Comment by sighingnow** [comment]
> Your step-by-step reproduction doesn't seem to be enough either. Here are the steps you suggested executed on a GitHub runner: https://github.com/carlocab/grpc-cmake/runs/1814003731?check_suite_focus=true

Thank you @carlocab I will double check my environment settings.

**Comment by sighingnow** [comment]
I'm going to close this ticket and reopen later if I could provide more related information.

Thanks everyone offers help here!
