### ISSUE TITLE
Issue with "brew Install Consul" on Mac OS X Sierra

### ISSUE THREAD

**Issue by rajashekar2014** [Homebrew/homebrew-core#7021]
**RSHEELA-M-L0XS:local rajashekhar$ brew install consul**
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for consul: go
==> Installing consul dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.6.2.src.tar.gz
Already downloaded: /Users/rajashekhar/Library/Caches/Homebrew/go-1.6.2.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/rajashekhar/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
**==> ./make.bash --no-clean
Last 15 lines from /Users/rajashekhar/Library/Logs/Homebrew/go/01.make.bash:
	/private/tmp/go-20161117-11467-rv1zen/go/gobootstrap/src/cmd/go/pkg.go:906 +0x366 fp=0xc2080f7d18 sp=0xc2080f7c00
main.runClean(0x3f9ae0, 0xc20800a030, 0x1, 0x1)**
	/private/tmp/go-20161117-11467-rv1zen/go/gobootstrap/src/cmd/go/clean.go:78 +0x45 fp=0xc2080f7d98 sp=0xc2080f7d18
main.main()
	/private/tmp/go-20161117-11467-rv1zen/go/gobootstrap/src/cmd/go/main.go:163 +0x608 fp=0xc2080f7f98 sp=0xc2080f7d98
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc2080f7fe0 sp=0xc2080f7f98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080f7fe8 sp=0xc2080f7fe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

**Comment by mistydemeo** [comment]
> Warning: You are using OS X 10.12.

Can you try running `brew update`? You're using an outdated version of Homebrew.

**Comment by rajashekar2014** [comment]
Thanks for quick reply !

I tried 'brew update' ..

$ brew update
Already up-to-date.

But issue, still exists.

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Can you please read this and follow all of the steps?

**Comment by ilovezfs** [comment]
This looks like the old update bug.

```
cd $(brew --repo); git fetch; git reset --hard origin/master
```

**Comment by ilovezfs** [comment]
I'm going to assume the above fixes this. Please let us know your results @rajashekar2014
