### ISSUE TITLE
Libftdi Missing C++ Wrapper

### ISSUE THREAD

**Issue by xloem** [Homebrew/homebrew-core#70223]
If homebrew wants, you could build libftdi's c++ interface by passing [`-DFTDIPP=ON`](http://developer.intra2net.com/git/?p=libftdi;a=blob;f=CMakeOptions.txt;h=07b5887cd946872f45324859ec65e4f3d727c516;hb=HEAD#l5) on this line:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libftdi.rb#L29

I'm currently planning to downport my code to use the C library to work with homebrew.  I don't have a mac, so it's not reasonable for me to test PR's to this repo.

If you click that `-DFTDIPP=ON` link, there are also python bindings that can be enabled.

**Comment by SMillerDev** [comment]
Homebrew also works on Linux so that's not a problem. And if you make a pull request I'm sure both maintainers and CI are happy to test for you.

We don't allow feature requests as issues though so I'm closing this.

**Comment by xloem** [comment]
K I can add that flag as a quick PR.
