### ISSUE TITLE
gpsbabel failed to build on 10.12.1

### ISSUE THREAD

**Issue by toeklk** [Homebrew/homebrew-core#7023]
Trying to build gpsbabel on Sierra fails.  Output at

https://gist.github.com/23d23a037817196bdb8bbe8a75c13333

At first sight it might be due to a missing CXXFLAGS=-std=c++11 flag?

**Comment by toeklk** [comment]
Indeed, after a brew edit gpsbabel, and adding 

"CXXFLAGS=-std=c++11" the args, gpsbabel builds just fine

**Comment by woodruffw** [comment]
Closing this since #7024 is under review.
