### ISSUE TITLE
libtasn1: Buggy when built with latest Apple clang compiler

### ISSUE THREAD

**Issue by stweil** [Homebrew/homebrew-core#70257]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

Not relevant.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`make check`fails for QEMU builds with latest macOS in libtasn1 code (reported on qemu-devel mailing list).

**What happened (include all command output)?**

`make check` fails.

**What did you expect to happen?**

`make check` works.

**Step-by-step reproduction instructions (by running `brew` commands)**

There are currently no simple tests available with `brew` commands.

Related issue: https://gitlab.com/gnutls/libtasn1/-/issues/30
Bug fix / patch: https://gitlab.com/gnutls/libtasn1/-/merge_requests/71

Fixing requires either a build with `-O1` instead of `-O2` or the patch linked above.

**Comment by SMillerDev** [comment]
There's an upstream issue and an upstream patch. This is clearly not a brew issue. Closing.

**Comment by stweil** [comment]
It is, because Homebrew currently installs a buggy package. This issue should be kept open until there is a valid solution:

- Remove buggy package.
- Compile package with `-O1`.
- Add patch to formula.
- Wait for fixed upstream release and update formula to supply that.

**Comment by SMillerDev** [comment]
Homebrew is always going to try and keep packages up to date so unless you make a pull request to add the patch the last option will always automagically happen.

**Comment by stweil** [comment]
So maybe let's see how fast a new release of `libtasn1` will come. If it is taking too much time, I'd consider the patch solution. Nevertheless keeping such issue reports open would help users of Homebrew to identify open problems (and this is currently such an open problem).

**Comment by carlocab** [comment]
There are many formulae with open upstream bug reports. These are best tracked in upstream issue trackers, where they already exist.

**Comment by stweil** [comment]
There is a certain risk that other formulas which use compiled C / C++ code have similar problems and that such problems show up as soon as those formulas are built with latest Apple clang compiler.

The new compiler versions use some optimization and a security feature which will break code operating with nullpointers plus offset (which is undefined behaviour but was sometimes used nevertheless).

**Comment by stweil** [comment]
> There are many formulae with open upstream bug reports.

In this case the situation is worse because it makes the formula worthless. That's not the same as a minor bug for a rare or very special use case.
