### ISSUE TITLE
midnight commander (mc) problem since 4.8.26

### ISSUE THREAD

**Issue by edrozenberg** [Homebrew/homebrew-core#70326]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

```
HOMEBREW_VERSION: 2.7.7-140-gf33dc70
ORIGIN: https://github.com/Homebrew/brew
HEAD: f33dc70e856540ba300400e3ceb34ac84e49ee2b
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 85b3ffbe8a2f9cc346c89e174a069c3c288d246c
Core tap last commit: 62 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=/Applications"]
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_EMOJI: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 11.0 build 1100
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
```
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`cd /`
`mc`

**What happened (include all command output)?**

When launching `mc` (4.8.26 bottle  or `--build-from-source` or `--HEAD --build-from-source`) from a non-home directory, `mc` is stuck showing a black screen with a single border character at top right. Terminal window has to be force closed.

* Problem started with mc 4.8.26
* mc only runs normally as regular user if launched inside home dir.
* There is also a new 2-3 second delay for mc to launch as a normal user starting with 4.8.26
* Same problem on multiple machines, Mojave, Big Sur
* Works fine and no delay if running as root `sudo bash; cd /; mc` and there is no launch delay
* Works fine in all scenarios & no delay when using the older 4.8.25 mc brew formula

Problem is likely with mc 4.8.26 and later source code, but I'm not sure where to start figuring out what broke mc under MacOS. Probably I'll have to report the issue on mc issues portal.

**What did you expect to happen?**

`mc` runs normally

**Step-by-step reproduction instructions (by running `brew` commands)**

```
brew install mc
cd /
mc
```

**Comment by MikeMcQuaid** [comment]
> [x] The `brew doctor` above contains no "Warning" lines.

It does

**Comment by edrozenberg** [comment]
It's not a `Warning`, it's a `Catch22`. There's no way to update the CLI tools on Mojave any further, no Apple updates. If Mojave is considered dead by Homebrew also fair enough.

Same issue on Big Sur as detailed earlier and `Your system is ready to brew.`.

It's anyway not a Homebrew issue but breakage by Midnight Commander HQ. Will have to report it there.

**Comment by carlocab** [comment]
>There's no way to update the CLI tools on Mojave any further

This is untrue. You can install Command Line Tools for Xcode 11.3.1 from https://developer.apple.com/download/more/.

**Comment by edrozenberg** [comment]
@carlocab thanks, that solves the annoying brew warning. The `mc` problems remain.

For reference on my Mojave -

Did NOT work to update CLI tools & remove brew warning ⚠️:
```
softwareupdate --all --install --force
```

Did NOT work to update CLI tools & remove brew warning ⚠️:
```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

Did work to remove brew warning ✅:
Install `Command_Line_Tools_for_Xcode_11.3.1.dmg` from Apple Dev

**Comment by carlocab** [comment]
For reference, the tables here will tell you the latest CLT you can install for each macOS version: https://en.wikipedia.org/wiki/Xcode#Version_comparison_table

**Comment by edrozenberg** [comment]
@carlocab Super helpful, I thought I'd always have to download 10 CLI pkgs and try each one :).

**Comment by carlocab** [comment]
Yes, I've thought for a while `brew doctor` should at least tell you which CLT version you should be installing. However, I haven't found the time to open a PR for it.

**Comment by edrozenberg** [comment]
@carlocab I just submitted a PR for this wiki guide on CLT versions. Sure would be nice if Github would come up with an easy in-browser editor method of submitting PR's for simple doc changes, instead of making 1 hour of work and checklists for a simple edit PR.

**Comment by incubus** [comment]
I have the same problem with mc.

**Comment by rafo** [comment]
I dont know if this bug is connected with mine (https://github.com/Homebrew/discussions/discussions/772). My MC gets immediately killed.

**Comment by edrozenberg** [comment]
mc is broken starting with 4.8.26 and still broken in latest HEAD unfortunately. I keep rechecking HEAD every few days hoping for a fix.

`cd / ; mc`
<img width="970" alt="mc 4 8 26 broken" src="https://user-images.githubusercontent.com/2648417/107657836-6565b780-6c3a-11eb-83d4-c0a7e63bb183.png">

Only works if launched while in the user's own home directory. Also works fine if launched via `sudo mc`. Another workaround is to roll back to 4.8.25 by editing `Formula/midnight-commander.rb` with the 4.8.25 values from https://github.com/Homebrew/homebrew-core/commit/877235cb343988ac39c69af580010fb9656993a9
