### ISSUE TITLE
ffmpeg is killed when I try to run it on macOS Big Sur 11.2 on a MacBook Pro M1

### ISSUE THREAD

**Issue by ctsrc** [Homebrew/homebrew-core#70522]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

```text
HOMEBREW_VERSION: 3.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebc7cc36a0e029d58fac8cebd1b5ff583b3fd95b
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 149d62524beea0231087f189a242fddc325adb3b
Core tap last commit: 53 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false
```

```text
Your system is ready to brew.
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Run ffmpeg which I installed via homebrew

**What happened (include all command output)?**

`ffmpeg -i foo.webm foo.mp4`

```text
zsh: killed     ffmpeg
```

`ffmpeg -h`

```text
zsh: killed     ffmpeg
```

**What did you expect to happen?**

ffmpeg should be able to run

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew install ffmpeg`

```text
==> Downloading https://homebrew.bintray.com/bottles/ffmpeg-4.3.1_9.arm64_big_su
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/4b4eb78995b8554bd2e66
######################################################################## 100.0%
==> Pouring ffmpeg-4.3.1_9.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/ffmpeg/4.3.1_9: 274 files, 49.8MB
```

`ffmpeg -i foo.webm foo.mp4`

```text
zsh: killed     ffmpeg
```

`ffmpeg -h`

```text
zsh: killed     ffmpeg
```

`brew info ffmpeg`

```text
ffmpeg: stable 4.3.1 (bottled), HEAD
Play, record, convert, and stream audio and video
https://ffmpeg.org/
/opt/homebrew/Cellar/ffmpeg/4.3.1_9 (274 files, 49.8MB) *
  Poured from bottle on 2021-02-05 at 20:15:03
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ffmpeg.rb
License: GPL-2.0-or-later
==> Dependencies
Build: nasm ✔, pkg-config ✔
Required: aom ✔, dav1d ✔, fontconfig ✔, freetype ✔, frei0r ✔, gnutls ✔, lame ✔, libass ✔, libbluray ✔, libsoxr ✔, libvidstab ✔, libvorbis ✔, libvpx ✔, opencore-amr ✔, openjpeg ✔, opus ✔, rav1e ✔, rtmpdump ✔, rubberband ✔, sdl2 ✔, snappy ✔, speex ✔, srt ✔, tesseract ✔, theora ✔, webp ✔, x264 ✔, x265 ✔, xvid ✔, xz ✔, zeromq ✔, zimg ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 169,162 (30 days), 475,958 (90 days), 1,566,044 (365 days)
install-on-request: 141,810 (30 days), 394,155 (90 days), 1,244,150 (365 days)
build-error: 0 (30 days)
```

**Comment by ctsrc** [comment]
Should also note that for example mediainfo runs fine, which was installed with homebrew on the same system.

`mediainfo -h`

```text
MediaInfo Command line, 
MediaInfoLib - v20.09
Usage: "mediainfo [-Options...] FileName1 [Filename2...]"

Options:
[...]
```

`brew info mediainfo`

```text
Warning: Treating mediainfo as a formula. For the cask, use homebrew/cask/mediainfo
media-info: stable 20.09 (bottled)
Unified display of technical and tag data for audio/video
https://mediaarea.net/
/opt/homebrew/Cellar/media-info/20.09 (52 files, 19.5MB) *
  Poured from bottle on 2021-02-05 at 20:16:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/media-info.rb
License: BSD-2-Clause
==> Dependencies
Build: pkg-config ✔
==> Analytics
install: 1,234 (30 days), 4,442 (90 days), 22,016 (365 days)
install-on-request: 1,226 (30 days), 4,342 (90 days), 20,574 (365 days)
build-error: 0 (30 days)
```

**Comment by ctsrc** [comment]
Additionally, I tried to build ffmpeg from source too, using homebrew to do that as well.

Even when compiled from source on my machine, ffmpeg fails to run in the same way.

**Comment by ctsrc** [comment]
Details about computer and OS version.

It's a MacBook Pro (13-inch, M1, 2020) running macOS Big Sur Version 11.2 (20D64)

`sysctl hw.model`

```text
hw.model: MacBookPro17,1
```

`sw_vers`

```text
ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64
```

**Comment by ctsrc** [comment]
I uninstalled homebrew completelly and installed homebrew again, then installed ffmpeg and now ffmpeg runs.

Guess my installation of homebrew had broken earlier when I updated and it complained about not finding the commandline tools or something.

Closing.

**Comment by barrowclift** [comment]
I'm unfortunately running into this same issue, can you please clarify what you mean by completely uninstalling homebrew? Are we talking `rm -rf /opt/homebrew`? Or something else?

**Comment by cps104** [comment]
> I'm unfortunately running into this same issue, can you please clarify what you mean by completely uninstalling homebrew? Are we talking `rm -rf /opt/homebrew`? Or something else?

Follow the instructions at https://github.com/homebrew/install#uninstall-homebrew and just reinstall. Then reinstall the packages. I had exactly this problem earlier today and this fixed it completely.

**Comment by gromgit** [comment]
@barrowclift , if by "same issue" you mean "I'm also getting `killed: ffmpeg` errors", you might want to try this first, before nuking Homebrew entirely:
```
brew reinstall $(brew deps ffmpeg) ffmpeg
```

**Comment by barrowclift** [comment]
That did it! A quick combination of `sudo xcode-select --reset ; sudo xcode-select --install` followed by `brew reinstall $(brew deps ffmpeg) ffmpeg` resolved the issue.

Thanks @gromgit for the guidance here, it's greatly appreciated.
