### ISSUE TITLE
GMP was compiled with -march=sandybridge

### ISSUE THREAD

**Issue by smtrat** [Homebrew/homebrew-core#7054]
I use a library that decided to reuse the compilation flags of gmp that are defined in __GMP_CFLAGS at the end of gmp.h. If gmp was installed as binary package via homebrew, these flags contain -march=sandybridge and -mtune=sandybridge.

Given that there are still machines out there with pre-sandybridge processors, this seems very risky. Could we change this to some sane defaults? Debian, for example, does not specify -mtune and -march at all.

For some reason, I have never encountered a problem with gmp itself. Is gmp even compiled with these options? Or are they just spurious remainders of the machine that builds the packages?

**Comment by ilovezfs** [comment]
The bottles are built with -march=core2, but that's because Homebrew superenv intervenes when something other than that is passed, so it's possible the build system recorded something other than was actually used.

**Comment by ilovezfs** [comment]
Yes, that's what's going on. If I build on Skylake,
```
/usr/local/opt/gmp/include/gmp.h:#define __GMP_CFLAGS "-O2 -pedantic -fomit-frame-pointer -m64 -mtune=skylake -march=broadwell"
```

And here are superenv's interventions:
https://gist.github.com/ilovezfs/ad883542d12bf1a0bb4db08a5ec3f1e8

The first shows
```
clang called with: -DHAVE_CONFIG_H -I. -I.. -I.. -O2 -pedantic -fomit-frame-pointer -m64 -mtune=skylake -march=broadwell -c memory.c -fno-common -DPIC -o .libs/memory.o
superenv removed:  -O2 -pedantic -m64 -mtune=skylake -march=broadwell
superenv added:    -pipe -w -Os -march=core2 -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
superenv executed: clang -pipe -w -Os -march=core2 -DHAVE_CONFIG_H -I. -I.. -fomit-frame-pointer -c memory.c -fno-common -DPIC -o .libs/memory.o -isystem/usr/local/include -isystem/usr/include/libxml2 -isystem/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
```

If you feel like opening a pull request that changes this so that the gmp.h installed by the bottle reflects reality more closely, we can take a look.

**Comment by ilovezfs** [comment]
We'd welcome a PR addressing this but no one is actively working on it at this time.

**Comment by smtrat** [comment]
I'm not too familiar with pull requests.
I'd propose the following patch: https://github.com/smtrat/homebrew-core/commit/be2eeae2c8086947d886b052054d8d25c3dea9b2 which seems to do the job for me.

**Comment by fxcoudert** [comment]
I think a more correct alternative would be to pass a modified build triplet to the configure script, to force `core2` as processor, i.e. to run `configure` with `--build=core2-apple-darwin16` (on Sierra). This results in a correct `__GMP_CFLAGS` macro in `gmp.h`

**Comment by MikeMcQuaid** [comment]
@fxcoudert Sounds like a good idea. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by fxcoudert** [comment]
I don't know any Ruby, so I don't know what the code should be for building the `core2-apple-darwin16` (with the right darwin version number).

Another thing: once this is done, you can stop passing the `--disable-assembly` configure option when building bottles, because `core2` assembly is suitable for all machines running macOS. This will be best to achieve both portability and speed.

**Comment by fxcoudert** [comment]
So, here is my "best-effort" patch. I don't have means to test it, so I won't open a pull request, but hopefully someone can test it.

```
--- gmp.rb	2017-01-07 16:25:28.000000000 +0100
+++ gmp.rb.fx	2017-01-07 16:29:27.000000000 +0100
@@ -18,8 +18,9 @@ class Gmp < Formula
     ENV.cxx11 if build.cxx11?
     args = ["--prefix=#{prefix}", "--enable-cxx"]
 
-    # https://github.com/Homebrew/homebrew/issues/20693
-    args << "--disable-assembly" if build.bottle?
+    # Restrict optimization to the oldest CPU supported, which is core2
+    osmajor = %x[uname -r | cut -d. -f1].chomp
+    args << "--build=core2-apple-darwin#{osmajor}"
 
     system "./configure", *args
     system "make"
```
