### ISSUE TITLE
Some formula still try to set LLVM/GCC optimization level (ENV.Ox)

### ISSUE THREAD

**Issue by danielnachun** [Homebrew/homebrew-core#70594]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

https://gist.github.com/danielnachun/078787151f7d3d33cb7d5c557195705e

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Install a formula which tries to set LLVM/GCC optimization level.  These formula should not be using this anymore but flew under the radar after it was disabled.

**What happened (include all command output)?**

```
Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling ENV.O3 is disabled! There is no replacement.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/awk.rb:24
```

**What did you expect to happen?**

The formula to install correctly, by not trying to set the optimization level.

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew install -s awk`

If you search for "ENV.O0", "ENV.O1", "ENV.O2", or "ENV.O3" in the repo you'll find the other formula with this issue.

**Comment by danielnachun** [comment]
See the comment from @jonchang for more context: https://github.com/Homebrew/linuxbrew-core/issues/22225#issuecomment-774424582.  Hopefully there is an automated way to remove these lines, otherwise we can open a PR. There aren't too many formula, I just happened to stumble on a few while bottling for Linux.

**Comment by carlocab** [comment]
Looks like there's not too many of them:

- [ ] awk
- [ ] clisp
- [ ] grace
- [ ] jnethack
- [ ] libgcrypt
- [ ] log4cxx
- [ ] mesos
- [ ] nethack
- [ ] openmsx
- [ ] scheme48
- [ ] smake

**Comment by carlocab** [comment]
I just got rid of those lines with `sed`, but, having looked at the diff, it might be better to do them manually.

`sed` gives one false positive: `libgcrypt`

Also, there are comments around these lines for context that should be removed manually.

**Comment by carlocab** [comment]
Looks like `clisp` won't build without the flag: #70596

**Comment by carlocab** [comment]
Will be closed by https://github.com/Homebrew/brew/pull/10566.

**Comment by MikeMcQuaid** [comment]
We should still remove these when they aren't needed, if possible.

**Comment by danielnachun** [comment]
Now that we've undeprecated `ENV.O0` and `ENV.O1` and removed all instances of `ENV.O2` and `ENV.O3`, I think this can be closed.
