### ISSUE TITLE
gtk-doc errors out with: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"

### ISSUE THREAD

**Issue by andreabolognani** [Homebrew/homebrew-core#70769]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

```
$ brew config
HOMEBREW_VERSION: 2.7.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: fdb71a5cb3029da2ef74d7e09c40575bbfb4ec72
Last commit: 6 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9adfd41f52709652a623b5b6f99005144fd8e34a
Core tap last commit: 5 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A

$ brew doctor
Your system is ready to brew.
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Build [libvirt-glib](https://gitlab.com/libvirt/libvirt-glib/) from source.

**What happened (include all command output)?**

```
$ ninja -C build dist
...
/usr/local/include/libvirt-gconfig-1.0/libvirt-gconfigBuilding documentation for Libvirt-glib
ERROR: Error in gtkdoc helper script:
ERROR: ['/usr/local/bin/gtkdoc-mkhtml', '--path=/private/var/folders/wh/z5_y2cv53sg24tzvtw_f_y1m0000gn/T/cirrus-ci-build/build/meson-private/dist-unpack/libvirt-glib-3.0.0/docs/libvirt-glib:/private/var/folders/wh/z5_y2cv53sg24tzvtw_f_y1m0000gn/T/cirrus-ci-build/build/meson-private/dist-build/docs/libvirt-glib', 'Libvirt-glib', '../Libvirt-glib-docs.xml'] failed with status 5
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl"
compilation error: file /usr/local/Cellar/gtk-doc/1.32_2/share/gtk-doc/data/gtk-doc.xsl line 11 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/html/chunk.xsl
...
Installing the distribution package failed
Dist check build directory was /private/var/folders/wh/z5_y2cv53sg24tzvtw_f_y1m0000gn/T/cirrus-ci-build/build/meson-private/dist-build
FAILED: meson-dist 
/usr/local/Cellar/meson/0.56.0/libexec/bin/meson dist
ninja: build stopped: subcommand failed.
```

**What did you expect to happen?**

Build completes successfully.

**Step-by-step reproduction instructions (by running `brew` commands)**

```
$ brew install ccache gettext git glib gobject-introspection gtk-doc libvirt libxml2 make meson ninja pkg-config vala
$ export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:/usr/local/opt/rpcgen/bin:$PATH"
$ export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig:$PKG_CONFIG_PATH"
$ git clone https://gitlab.com/libvirt/libvirt-glib.git
$ cd libvirt-glib
$ meson build
$ ninja -C build dist
```

**Comment by andreabolognani** [comment]
I have tried building [Cattle](https://gitlab.com/abologna/cattle) from source as well, and got the same result. While libvirt-glib uses Meson, Cattle is still on autotools, so the issue appears to be in gtk-doc itself rather than in the build system-specific glue.

I have also noticed that most projects in this repo seem to disable gtk-doc support at build time even when they declare a build dependency on the package: I have no idea whether this is to work around this issue, or because not shipping API documentation is Homebrew's policy/preference.

**Comment by andreabolognani** [comment]
Full CI run for libvirt-glib on Cirrus CI: https://cirrus-ci.com/task/6552307884097536

**Comment by SMillerDev** [comment]
What makes you suspect this is a homebrew bug? It seems like your build is failing when using homebrew dependencies, that's not something we provide support for.

**Comment by carlocab** [comment]
We do have a formula for `libvirt-glib`, though it seems to not depend on `gtk-doc`.

>not shipping API documentation is Homebrew's policy/preference

A lot of formulae do have the documentation disabled. They add to the maintenance burden of formulae, increase build time, and are almost always not really needed since you can access the documentation online.

**Comment by andreabolognani** [comment]
> What makes you suspect this is a homebrew bug? It seems like your build is failing when using homebrew dependencies, that's not something we provide support for.

I've installed gtk-doc from homebrew, and it's not working correctly. I honestly have no idea whether this is because of an issue in upstream gtk-doc (or one of its dependencies) or something introduced by how it's being packaged in homebrew, but I'm hoping that you are in a better position to figure that out and either address the issue directly or forward it upstream :)

I can try coming up with a more minimal reproducer for the issue, but AFAIK neither libvirt-glib nor Cattle do anything particularly fancy outside of using the regular build system integration.

All of this works fine on both Linux and FreeBSD.

**Comment by alebcay** [comment]
I can't reproduce this locally (I encounter an error prior to the one described), but it looks like [someone has encountered this error before](https://github.com/Homebrew/legacy-homebrew/issues/45020). Solution is to `export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"` according to [this comment](https://github.com/Homebrew/legacy-homebrew/issues/45020#issuecomment-170957708).

**Comment by andreabolognani** [comment]
> I can't reproduce this locally (I encounter an error prior to the one described), but it looks like [someone has encountered this error before](https://github.com/Homebrew/legacy-homebrew/issues/45020). Solution is to `export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"` according to [this comment](https://github.com/Homebrew/legacy-homebrew/issues/45020#issuecomment-170957708).

Right! I managed to figure out the same workaround independently in the meantime, but I really appreciate the pointer :)

I see that multiple formulae contain

```ruby
ENV["XML_CATALOG_FILES"] = "#{etc}/xml/catalog"
```

which indicates that, in addition to users, homebrew maintainers have to routinely deal with this.

Note that, unlike what happens with other packages that require the user to alter their environment in order to be used effectively, no notes are displayed when I (re)install docbook-xsl.

In order to provide a better experience to users, I think that

  1. docbook-xsl should display such a note on installation;

  2. gtk-doc should be patched so that it sets `XML_CATALOG_FILES` appropriately if it's not already present in the environment.

What do you think?

**Comment by SMillerDev** [comment]
As I understand it, `XML_CATALOG_FILES` is a fairly standard variable. So it's expected users of related tools know how to use it.

**Comment by andreabolognani** [comment]
@SMillerDev the variable is documented fairly prominently in `xsltproc(1)`, but it might not be obvious to user *what* they should set it to. One could infer it from the output of `brew install docbook-xsl`:

```
==> Pouring docbook-xsl-1.79.2_1.catalina.bottle.tar.gz
==> xmlcatalog --noout --del file:///usr/local/opt/docbook-xsl/docbook-xsl/catalog.xml /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add nextCatalog  file:///usr/local/opt/docbook-xsl/docbook-xsl/catalog.xml /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del https://cdn.docbook.org/release/xsl-nons/1.79.2 /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem https://cdn.docbook.org/release/xsl-nons/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI https://cdn.docbook.org/release/xsl-nons/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del https://cdn.docbook.org/release/xsl-nons/current /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem https://cdn.docbook.org/release/xsl-nons/current file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI https://cdn.docbook.org/release/xsl-nons/current file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del http://docbook.sourceforge.net/release/xsl/1.79.2 /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem http://docbook.sourceforge.net/release/xsl/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI http://docbook.sourceforge.net/release/xsl/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del http://docbook.sourceforge.net/release/xsl/current /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem http://docbook.sourceforge.net/release/xsl/current file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI http://docbook.sourceforge.net/release/xsl/current file:///usr/local/opt/docbook-xsl/docbook-xsl /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del file:///usr/local/opt/docbook-xsl/docbook-xsl-ns/catalog.xml /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add nextCatalog  file:///usr/local/opt/docbook-xsl/docbook-xsl-ns/catalog.xml /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del https://cdn.docbook.org/release/xsl/1.79.2 /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem https://cdn.docbook.org/release/xsl/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI https://cdn.docbook.org/release/xsl/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del https://cdn.docbook.org/release/xsl/current /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem https://cdn.docbook.org/release/xsl/current file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI https://cdn.docbook.org/release/xsl/current file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del http://docbook.sourceforge.net/release/xsl-ns/1.79.2 /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem http://docbook.sourceforge.net/release/xsl-ns/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI http://docbook.sourceforge.net/release/xsl-ns/1.79.2 file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --del http://docbook.sourceforge.net/release/xsl-ns/current /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteSystem http://docbook.sourceforge.net/release/xsl-ns/current file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
==> xmlcatalog --noout --add rewriteURI http://docbook.sourceforge.net/release/xsl-ns/current file:///usr/local/opt/docbook-xsl/docbook-xsl-ns /usr/local/etc/xml/catalog
```

but I still think an explicit note would make a lot of sense, instead of leaving users to piece together the puzzle themselves.

As for gtk-doc users, the fact that xsltproc and docbook-xsl are used under the hood is for the most part an implementation detail, so expecting them to know where to look seems honestly a bit of a stretch...
