### ISSUE TITLE
Minor instruction error in kafka info

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#7079]
`brew info kafka` presents instructions for explicitly starting zookeeper and kafka with a semicolon (`;`) joining the commands. However, the current zookeeper script stays foregrounded, so the kafka command never executes.

Could we please clarify the proper shell commands for starting zookeeper and kafka? For example, the zookeeper script could be backgrounded with `&`, or run in `screen`/`tmux`, or in another terminal session.

**Comment by MikeMcQuaid** [comment]
> Could we please clarify the proper shell commands for starting zookeeper and kafka? For example, the zookeeper script could be backgrounded with &, or run in screen/tmux, or in another terminal session.

Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by rickmark** [comment]
PR #7572
