### ISSUE TITLE
wxMaxima build/bottle issues

### ISSUE THREAD

**Issue by jwleblan** [Homebrew/homebrew-core#70931]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

~ brew config
HOMEBREW_VERSION: 3.0.1-10-g0d36d54
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0d36d54ede5b95730b9474b6a448866997bbce4f
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 53a3fd9a4b760094d0d5f92a4bdc240c80b2f2b2
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.3BChoPqZ3f/org.macosforge.xquartz:0
HOMEBREW_DISPLAY_INSTALL_TIMES: set
HOMEBREW_EDITOR: bbedit -b
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_INSECURE_REDIRECT: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: N/A
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: The filesystem on /System/Volumes/Data appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtbb.12.dylib
  /usr/local/lib/libtbb.dylib
  /usr/local/lib/libtbbmalloc.2.1.dylib
  /usr/local/lib/libtbbmalloc.2.dylib
  /usr/local/lib/libtbbmalloc.dylib
  /usr/local/lib/libtbbmalloc_proxy.2.1.dylib
  /usr/local/lib/libtbbmalloc_proxy.2.dylib
  /usr/local/lib/libtbbmalloc_proxy.dylib

****

- [ ] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Not sure what libtt is doing in the /lib directory, but deleting .dylib's from an installed package seemed unwise.

I was trying to run wxMaxima.  It failed, so I figured an OS update might have damaged the package.  I then tried to reinstall from bottle (which failed to execute correctly), and then the build failed.  I noticed links referring to "wxMaxima" when "wxmaxima" was on disk, and so I suspect a case sensitivity issue.

This executable also fails to run on a case-insensitive system (verified by another homebrew maintainer), so I think something is up, but my development skills are wanting (I'm a lowly electrical engineer).

Hopefully this will point more skilled individuals in the right direction.

**What happened (include all command output)?**

Executing wxMaxima will likely fail on your system (it used to work prior to Big Sur).

When I build from source I get the following:
>> brew reinstall -s wxmaxima
==> Downloading https://github.com/wxMaxima-developers/wxmaxima/archive/Version-21.01.0.tar.gz
Already downloaded: /Users/jwleblan_adm/Library/Caches/Homebrew/downloads/80a208ddac24a337eb11f9c503cb524a7af86f57a7859777a20b021e95727573--wxmaxima-Version-21.01.0.tar.gz
==> Reinstalling wxmaxima 
==> cmake .. -GNinja
==> ninja
==> ninja install
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - src/wxMaxima.app

**What did you expect to happen?**

The bottled result should launch an executable that accepts input (just try "1+1;" -- I think you'll need shift-enter by default to get an evaluation).  You should see "2".

The source should compile under a case-sensitive system.  I think it compiles right now under case insensitive systems, but the resulting executable fails to run.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew install wxmaxima
<try to launch the executable and execute "1+1;">

brew install -s wxmaxima
<try to launch the executable and execute "1+1;">

**Comment by miccal** [comment]
Further information: https://github.com/wxMaxima-developers/wxmaxima/issues/1441?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEzNDI5OTExMzc6NjEyNzE2Mw%3D%3D#issuecomment-770765011

I have reported this upstream, but I have not yet been able to track down the problem.

**Comment by jwleblan** [comment]
Fantastic!

Thanks for helping,

~Joel

**Comment by carlocab** [comment]
I think this should be resolved now. Try to do `brew update && brew upgrade`. Please open another issue if it still doesn't work.
