### ISSUE TITLE
plan9port invalid shebang line of rc scripts

### ISSUE THREAD

**Issue by martanne** [Homebrew/homebrew-core#7103]
The `ssam(1)` rc shell script uses the following shebang line `#!/usr/local/plan9/bin/rc` which is not valid for a plan9port installed via homebrew. This causes the [following error](https://travis-ci.org/martanne/vis/jobs/177239094#L886) when trying to execute `9 ssam`:

```
/usr/local/plan9/bin/rc: bad interpreter: No such file or directory
```

The same problem will probably also occur for other rc scripts bundled with plan9port. I suggest to either make rc available in `/usr/local/bin/rc` (assuming this won't conflict with existing Mac OS X software?) or fix up the shebang lines in a post install script.

Disclaimer: I don't have easy access to a Mac OS X system and I'm not familiar with homebrew. I stumbled upon the issue while trying to get the test suite of my [editor project](https://github.com/martanne/vis) running within the Travis Mac OS X environment.

**Comment by MikeMcQuaid** [comment]
> fix up the shebang lines in a post install script.

The correct approach is to use an `inreplace` in the `install` method. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by martanne** [comment]
It turned that there is already upstream infrastructure in place to perform these renames, but `ssam` was  simply not marked as needing a rename. I have contributed a [patch to the upstream plan9port project](https://plan9port-review.googlesource.com/#/c/2680/) fixing the issue. I hope it will eventually be applied and trickle down to homebrew so that `ssam` actually works when installed via homebrew.

**Comment by MikeMcQuaid** [comment]
Thanks @martanne. Once they merge that patch we're happy to add it to the formula.
