### ISSUE TITLE
brew not recognised on apple silicon

### ISSUE THREAD

**Issue by andrew-clark836** [Homebrew/homebrew-core#71126]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

Not possible to run any brew command

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I've installed scrcpy on many Mac's previously, but on my new M1 silicon, it just isn't working.  I run through the usual procedure, installed adb tools, but when I go to run scrcpy it says 'command not recognised'.  This is the case for any 'brew' related command.

I have obviously missed a step here, and I suspect it is to do with "add HOMEBREW to your PATH in users/andrewclark/ .profile

Not sure how to do this.

I ran the command /opt/homebrew/bin/brew/ shellenv which seems to run OK, but I still end up in the same place, with no 'brew' related commands being reconised.

**What happened (include all command output)?**

I've installed scrcpy on many Mac's previously, but on my new M1 silicon, it just isn't working.  I run through the usual procedure, installed adb tools, but when I go to run scrcpy it says 'command not recognised'.  This is the case for any 'brew' related command.

I have obviously missed a step here, and I suspect it is to do with "add HOMEBREW to your PATH in users/andrewclark/ .profile

Not sure how to do this.

I ran the command /opt/homebrew/bin/brew/ shellenv which seems to run OK, but I still end up in the same place, with no 'brew' related commands being reconised.

**What did you expect to happen?**

I've installed scrcpy on many Mac's previously, but on my new M1 silicon, it just isn't working.  I run through the usual procedure, installed adb tools, but when I go to run scrcpy it says 'command not recognised'.  This is the case for any 'brew' related command.

I have obviously missed a step here, and I suspect it is to do with "add HOMEBREW to your PATH in users/andrewclark/ .profile

Not sure how to do this.

I ran the command /opt/homebrew/bin/brew/ shellenv which seems to run OK, but I still end up in the same place, with no 'brew' related commands being reconised.

**Step-by-step reproduction instructions (by running `brew` commands)**

NO brew commands will run.

**Comment by carlocab** [comment]
The commands you need to run are right under the line that says `add HOMEBREW to your PATH in users/andrewclark/ .profile`.

**Comment by andrew-clark836** [comment]
Thanks Carlo

I saw those but was unsure exactly what to do.  I found another help forum, and brew commands work now, as does scrcpy, now it’s been downloaded to the right place!

Many thanks for the swift response.

Andy
Andy Clark
ASyI, M.ISRM
Managing Director
G6 Global | Delivering Critical Communications
[cid:image001.png@01D702DB.2B23AA50]
m. +44 (0)7768 501775
|
t. +44 (0)1454 610050
e. andrew@g6-global.com<mailto:andrew@g6-global.com>
|
w. www.g6-global.com<http://www.g6-global.com/>
skype. candlinternational_andy
|
The Old Workshop, Hortham Farm, Bristol BS32 4JW UK
[cid:image002.png@01D702DB.2B23AA50]<https://www.linkedin.com/in/andy-clark-comms-ninja-%F0%9F%A5%B7%F0%9F%8F%BC-%F0%9F%8C%88-86618223/>
[cid:image003.png@01D702DB.2B23AA50]<https://twitter.com/andyclark_g6>
[cid:image004.png@01D702DB.2B23AA50]<https://www.facebook.com/profile.php?id=100000032137882>
This email and the information it contains may be privileged and/or confidential. It is for the intended addressee(s) only. The unauthorised use, disclosure or copying of this email or any information it contains; Is prohibited and could, in certain circumstances, be a criminal offence. If you are not an intended recipient, please notify the originator support@g6-global.com immediately.
Calcom Holdings Ltd (trading as G6 Global) is a company registered in the United Kingdom . Registered number: 3740662 . Registered office: The Old Workshop, Hortham Farm, Bristol, BS32 4JW.
