### ISSUE TITLE
xapian --with-python should support Python 3 now?  (or perhaps --with-python3 option?)

### ISSUE THREAD

**Issue by wakatara** [Homebrew/homebrew-core#7114]
Xapian 1.4.1 builds fine on my Sierra Mac having Python 2.7.12 and Python 3.5.2 dual installed. 

However, I believe Xapian now supports python3 at this point and it compiling in 2.7 is causing other issues (with neovim etc.)..

Or it possible to have this option or make python3 the default and fall back to 2.7 or are there reasons for it that make this problematic?  (happy to take hand at putting it in formula myself, but thought I'd ask in case there were reasons I didn't know.).

**Comment by MikeMcQuaid** [comment]
> Or it possible to have this option or make python3 the default and fall back to 2.7 or are there reasons for it that make this problematic? (happy to take hand at putting it in formula myself, but thought I'd ask in case there were reasons I didn't know.).

Sounds reasonable. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by karolyi** [comment]
+1, python3 support is missing
