### ISSUE TITLE
lensfun 0.3.95 crashes with malloc error

### ISSUE THREAD

**Issue by ktgw0316** [Homebrew/homebrew-core#71192]
**brew gist-logs <formula> link OR brew config AND brew doctor output**

https://gist.github.com/d51a58c201fb2106bef7538a75fb8fdc

**What were you trying to do (and why)?**
A software using lensfun library is constantly crashing, only when the lensfun provided by homebrew is used. This problem doesn't occur if the lensfun was compiled from the latest source code from github master branch, so I want to check the situation with minimal reproducible example.

**What happened (include all command output)?**
Following simple program (main.cpp) 

```
#include "lensfun.h"
int main (int argc, char **argv)
{
    auto ldb = new lfDatabase();
    ldb->Load();
    delete ldb;
    return 0;
}
```

will crash with a message like this:

```
** (process:41970): WARNING **: 22:29:26.524: [Lensfun] /usr/local/Cellar/lensfun/0.3.95_3/share/lensfun/version_2/mil-sigma.xml:35:40: Error on line 35 char 40: Element ?mount? was closed, but the currently open element is ??
a.out(41970,0x202e7ae00) malloc: *** error for object 0x7fd034470500: pointer being freed was not allocated
a.out(41970,0x202e7ae00) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ./a.out
```

+ If the `delete ldb` line is commented out, the malloc errors will disappear.
+ If the `/usr/local/Cellar/lensfun/0.3.95_3/share/lensfun/version_2/mil-sigma.xml` file is removed, the "Errors on line 35" will disappear. Additionally, `mil-olympus.xml`, `mil-panasonic.xml`, `mil-samyang.xml` and `misc.xml` in the same directory are removed, the malloc error will disappear too.

**What did you expect to happen?**

The program do nothing and exit with no error.

**Step-by-step reproduction instructions (by running brew commands)**

```
brew install lensfun
```
then, on x86_64
```
clang++ -std=c++11 -target x86_64-apple-macos10.15 $(PKG_CONFIG_PATH=/usr/local/lib/pkgconfig pkg-config --cflags --libs lensfun glib-2.0) main.cpp
./a.out
```
or on arm64
```
clang++ -std=c++11 -target arm64-apple-macos11 $(PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig pkg-config --cflags --libs lensfun glib-2.0) main.cpp
./a.out
```

**Comment by ktgw0316** [comment]
As far as I know, the lensfun v0.3.95 is an unstable alpha release, so I'd like to suggest to revert the formula to v0.3.2. 
cf. https://github.com/msys2/MINGW-packages/issues/7108

If it is not possible, get the latest source code from github, not from sourceforge archive that currently used.

**Comment by fxcoudert** [comment]
0.3.95 is 2 years old, and 0.3.2 is 5 years old, so we're not likely to roll back to that older version.
We won't update to build from head/latest git either, but you can ask the lensfun project to make a new release.
