### ISSUE TITLE
Updating the LV2 formula

### ISSUE THREAD

**Issue by jcelerier** [Homebrew/homebrew-core#7121]
Hello,

I would like to update the [lv2 formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lv2.rb) from 1.12 to 1.14.

However when running : `brew install --build-from-source lv2` the installer complains; it seems that it is trying to write to the `/Library/Audio/Plug-Ins/LV2`folder which it cannot do without root rights (at least in Sierra).

What could I do ? Thanks.

**Comment by jcelerier** [comment]
I fixed the error by outputting the lv2 files to "${lib}/lv2" as other plug-ins does

**Comment by MikeMcQuaid** [comment]
Glad you got it figured out. Closing in favour of PR in https://github.com/Homebrew/homebrew-core/pull/7124.
