### ISSUE TITLE
Issue installing cpp ethereum/ethereum 

### ISSUE THREAD

**Issue by dojotech** [Homebrew/homebrew-core#7129]
# Im facing this issue at the moment as i try to install the cpp ethereum/ethereum. this is the error code i get on terminal. 

yptlib.o cpu.o integer.o 3way.o adler32.o algebra.o algparam.o arc4.o asn.o authenc.o base32.o base64.o basecode.o bfinit.o blake2.o blowfish.o blumshub.o camellia.o cast.o casts.o cbcmac.o ccm.o chacha.o channels.o cmac.o crc.o default.o des.o dessp.o dh.o dh2.o dll.o dsa.o eax.o ec2n.o eccrypto.o ecp.o elgamal.o emsa2.o eprecomp.o esign.o files.o filters.o fips140.o fipstest.o gcm.o gf256.o gf2_32.o gf2n.o gfpcrypt.o gost.o gzip.o hex.o hmac.o hrtimer.o ida.o idea.o iterhash.o keccak.o luc.o mars.o marss.o md2.o md4.o md5.o misc.o modes.o mqueue.o mqv.o nbtheory.o network.o oaep.o osrng.o panama.o pkcspad.o polynomi.o pssr.o pubkey.o queue.o rabin.o randpool.o rc2.o rc5.o rc6.o rdrand.o rdtables.o rijndael.o ripemd.o rng.o rsa.o rw.o safer.o salsa.o seal.o seed.o serpent.o sha.o sha3.o shacal2.o shark.o sharkbox.o skipjack.o socketft.o sosemanuk.o square.o squaretb.o strciphr.o tea.o tftables.o tiger.o tigertab.o trdlocal.o ttmac.o twofish.o vmac.o wait.o wake.o whrlpool.o xtr.o xtrcrypt.o zdeflate.o zinflate.o zlib.o
ld: unexpected token: !tapi-tbd-v2 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libcryptopp.dylib] Error 1
make: *** Waiting for unfinished jobs....

# I realised that is saying moment about the architecture being either x64 or x86. Im running the node on macbook pro to mine ethereum so it is a X64 machine. 

Tried to resolve it but I'm stuck now. Any ideas how to sort this problem. I have tried the trouble shooting brew doctor says the system is ready to brew. When i try to link cpp ethereum gives me an error saying that there is nothing on the directory: :~ StepupTech$ brew linkapps cpp-ethereum
Error: No such keg: /usr/local/Cellar/cpp-ethereum

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by dojotech** [comment]
Just tried to reinstall the Xcode seemed to have worked. I will update the status soon when running the node and started to mine.

**Comment by MikeMcQuaid** [comment]
Closing until the requested information is provided.
