### ISSUE TITLE
Solr: Failure to run as a service on ARM (m1)

### ISSUE THREAD

**Issue by alex-vas** [Homebrew/homebrew-core#71454]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

brew doctor
Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

After successfully installing solr, unable to run it as a service with the following command:
```sh
brew services start solr
```

**What happened (include all command output)?**

Solr home directory /usr/local/var/lib/solr not found!

**What did you expect to happen?**

The `homebrew.mxcl.solr.plist` should use `/opt/homebrew/var/lib/solr` directory when run on ARM, and not the `/usr/local/var/lib/solr` as if it runs on intel.

**Step-by-step reproduction instructions (by running `brew` commands)**

brew install solr
brew services start solr

**Comment by carlocab** [comment]
Where is the output of `brew config`?

**Comment by alex-vas** [comment]
@carlocab I am preparing pull request. The problem is crystallised in 'What did you expect to happen?' section. Cheers.

**Comment by carlocab** [comment]
Great; glad you have a fix.

If you're already opening a PR, then there is no need to also open an issue for it.

**Comment by alex-vas** [comment]
Fair enough. Let's close this issue.
