### ISSUE TITLE
postgresql@12: broken plist

### ISSUE THREAD

**Issue by dahu33** [Homebrew/homebrew-core#71470]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

```
HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ac3b9e7490bc93fda19c4f296f386e251315aec
Core tap last commit: 67 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
```

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

`brew install postgresql@12`
`brew services start postgresql@12`

**What happened (include all command output)?**

`postgresql@12` would not start because the plist `~/Library/LaunchAgents/homebrew.mxcl.postgresql@12.plist` is broken (dirs and files should be pointing to `postgresql@12` instead of `postgres`):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>homebrew.mxcl.postgresql@12</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/postgresql@12/bin/postgres</string>
    <string>-D</string>
    <string>/usr/local/var/postgres</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/usr/local</string>
  <key>StandardOutPath</key>
  <string>/usr/local/var/log/postgres.log</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/log/postgres.log</string>
</dict>
</plist>
```

**What did you expect to happen?**

`~/Library/LaunchAgents/homebrew.mxcl.postgresql@12.plist` should look like this (dirs and files should be pointing to `postgresql@12` instead of `postgres`):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>homebrew.mxcl.postgresql@12</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/opt/postgresql@12/bin/postgres</string>
    <string>-D</string>
    <string>/usr/local/var/postgresql@12</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>/usr/local</string>
  <key>StandardOutPath</key>
  <string>/usr/local/var/log/postgresql@12.log</string>
  <key>StandardErrorPath</key>
  <string>/usr/local/var/log/postgresql@12.log</string>
</dict>
</plist>
```

**Step-by-step reproduction instructions (by running `brew` commands)**

`brew install postgresql@12`
`brew services start postgresql@12`
`cat ~/Library/LaunchAgents/homebrew.mxcl.postgresql@12.plist`

**Comment by carlocab** [comment]
You've already opened #71466 to fix this; no need to open an issue too.

**Comment by dahu33** [comment]
> You've already opened #71466 to fix this; no need to open an issue too.

That's a different fix. I don't have a fix for this issue.

**Comment by carlocab** [comment]
My mistake.

**Comment by carlocab** [comment]
Is this a problem if you only use `postgresql@12`, or does it arise only if you have both `postgresql` and `postgresql@12` installed?

**Comment by gromgit** [comment]
I'm pretty sure it's a bug in `def plist`, as follows:
```
        <array>
          <string>#{opt_bin}/postgres</string>
          <string>-D</string>
          <string>#{postgresql_datadir}</string>
        </array>
```
This should be:
```
        <array>
          <string>#{opt_bin}/postgres</string>
          <string>-D</string>
          <string>#{versioned_data_dir}</string>
        </array>
```
since `postgresql_datadir` tests for the existence of `versioned_data_dir`, which by definition would _not_ exist in CI at build time.

**Comment by gromgit** [comment]
In fact, I suspect testing for both the data dir and log path is counterproductive, since every path generated by the formula should be versioned. Will have to review the PR that introduced this.

**Comment by taylorthurlow** [comment]
I can confirm that @gromgit's suggested fix works great.
