### ISSUE TITLE
M1 Mac on Big Sur unable to install brew

### ISSUE THREAD

**Issue by DataRedact** [Homebrew/homebrew-core#71526]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

N/A - Unable to install homebrew in general

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I am trying to install homebrew on a M1 Big Sur macbook air on latest software using the 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" command, 
but it comes up with an error disallowing me from installing homebrew.

**What happened (include all command output)?**

choragore@Arahans-MacBook-Air ~ % /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
==> Checking for `sudo` access (which may request your password).
Password:
==> This script will install:
/opt/homebrew/bin/brew
/opt/homebrew/share/doc/homebrew
/opt/homebrew/share/man/man1/brew.1
/opt/homebrew/share/zsh/site-functions/_brew
/opt/homebrew/etc/bash_completion.d/brew
/opt/homebrew

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /usr/sbin/chown -R choragore:admin /opt/homebrew
==> /usr/bin/sudo /bin/mkdir -p /Users/choragore/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/choragore/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown -R choragore /Users/choragore/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 2663, done.
remote: Counting objects: 100% (2663/2663), done.
remote: Total 6072 (delta 2662), reused 2663 (delta 2662), pack-reused 3409
Receiving objects: 100% (6072/6072), 1.71 MiB | 3.19 MiB/s, done.
Resolving deltas: 100% (4658/4658), completed with 698 local objects.
From https://github.com/Homebrew/brew
 * [new branch]          dependabot/bundler/Library/Homebrew/sorbet-0.5.6287 -> origin/dependabot/bundler/Library/Homebrew/sorbet-0.5.6287
   5844fc4f0..3ff5795ae  master     -> origin/master
 * [new branch]          revert-10624-revert-10607-update-issue-templates -> origin/revert-10624-revert-10607-update-issue-templates
 * [new tag]             2.7.3      -> 2.7.3
 * [new tag]             2.7.4      -> 2.7.4
 * [new tag]             2.7.5      -> 2.7.5
 * [new tag]             2.7.6      -> 2.7.6
 * [new tag]             2.7.7      -> 2.7.7
 * [new tag]             3.0.0      -> 3.0.0
 * [new tag]             3.0.1      -> 3.0.1
HEAD is now at 3ff5795ae Merge pull request #10652 from danielnachun/revert-gcc-linkage-fix
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
fatal: invalid upstream 'origin/master'
Failed during: /opt/homebrew/bin/brew update --force --quiet
choragore@Arahans-MacBook-Air ~ % 

Errors: 
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Error: Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-core failed!
fatal: invalid upstream 'origin/master'
Failed during: /opt/homebrew/bin/brew update --force --quiet

**What did you expect to happen?**

I expected homebrew to install.

**Step-by-step reproduction instructions (by running `brew` commands)**

I just went into terminal, typed in

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

and the error comes up after it downloades other things without any issue.

**Comment by carlocab** [comment]
There are many posts on the discussions page about this issue (and related issues). Please check there for solutions. For example:

https://github.com/Homebrew/discussions/discussions/666
https://github.com/Homebrew/discussions/discussions/657
https://github.com/Homebrew/discussions/discussions/698
https://github.com/Homebrew/discussions/discussions/671
https://github.com/Homebrew/discussions/discussions/501
https://github.com/Homebrew/discussions/discussions/668
https://github.com/Homebrew/discussions/discussions/814
