### ISSUE TITLE
ta-lib Not found on Brew

### ISSUE THREAD

**Issue by Anaschouihdi** [Homebrew/homebrew-core#71540]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

(base) anaschouihdi@Anass-MBP ~ % brew config
HOMEBREW_VERSION: 3.0.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: c951be8d3c7b339c7e759b7c40aec859e09a70a5
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: HEAD
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

######################
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I want to dowload Ta-lib with brew on MAC OS Catalina

**What happened (include all command output)?**

Formula not found

(base) anaschouihdi@A ~ % brew install ta-lib   
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "ta-lib".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
(base) anaschouihdi@Anass-MBP ~ % 

**What did you expect to happen?**

To be downloaded

**Step-by-step reproduction instructions (by running `brew` commands)**

(base) anaschouihdi@A~ % brew install ta-lib

**Comment by dtrodrigues** [comment]
Your
```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: HEAD
```

should be something like 

```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fbf380f00b8bcd5671f57d7dd183d20090a9724d
Core tap last commit: 46 minutes ago
Core tap branch: master
```

Can you run `brew update-reset` and try again?

**Comment by dtrodrigues** [comment]
The warning from `brew doctor` helps to point this out:
```
Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
git -C $(brew --repo homebrew/core) checkout master
```

**Comment by carlocab** [comment]
There are many posts on the [discussions page](https://github.com/Homebrew/discussions/discussions) about this problem and various ways to resolve it. Please check there if the solution from `brew doctor` doesn't work. Thanks!
