### ISSUE TITLE
Enable image view in w3m formulae

### ISSUE THREAD

**Issue by reportaman** [Homebrew/homebrew-core#71714]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

NA

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Trying to install w3m with inline image viewer enabled. Macports already does that: https://github.com/tats/w3m/issues/95#issuecomment-366100764, and homebrew has disabled it for w3m. Please add an option to enable it, and replicate macports method of building it.

**What happened (include all command output)?**

NA

**What did you expect to happen?**

NA

**Step-by-step reproduction instructions (by running `brew` commands)**

NA

**Comment by carlocab** [comment]
This issue tracker is for bug reports. If you want to enable features in a formula, please open a pull request. Thanks!

**Comment by lonelykid** [comment]
@carlocab I tried to include image support. But audit seems not allowing me to use ``option`` or ``build.with``. It might not be wise to change to include image support by default, better leave it to users. What should I do?

**Comment by carlocab** [comment]
We don't do options in homebrew/core. If you must have a formula with options, you can host it in your own tap.

If you want the feature enabled for the homebrew/core formula, you'll have to enable it by default.

If you'd rather host it in your own tap, here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by SMillerDev** [comment]
If you think it's useful for the majority of users, enable it by default.
