### ISSUE TITLE
GHC version number failed some dependency

### ISSUE THREAD

**Issue by ggarlic** [Homebrew/homebrew-core#7176]
i'm using  the latest ghc in repo, i.e.:

commit 66631db9c92c1bb23a767878cda76da97150fc2a
Author: BrewTestBot <brew-test-bot@googlegroups.com>
Date:   Tue Nov 15 20:54:13 2016 +0000

    ghc: update 8.0.1_2 bottle.

it has a version:
```
$ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1.20161114
```
when i use stack, a widely used build tool for haskell, to build a package called intero.
```
$stack install intero
Run from outside a project, using implicit global project config
Using resolver: lts-7.10 from implicit global project's config file: /Users/ggarlic/.stack/global-project/stack.yaml

While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.19:
    ghc-8.0.1.20161114 must match >=7.8 && <=8.0.1
```

can we remove the date section in version string?

**Comment by ilovezfs** [comment]
Please try editing /Users/ggarlic/.stack/global-project/stack.yaml and change <=8.0.1 to <=8.0.2

**Comment by ggarlic** [comment]
@ilovezfs that's a quick solution, thanks 😁

**Comment by ilovezfs** [comment]
You're welcome :)
