### ISSUE TITLE
The s3sync package no longer works.

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-core#7177]
_From @fdb on November 22, 2016 14:47_

### Bug reports:

Running `brew install s3sync` gives an error:

```
==> Cloning http://s3sync-s3cmd.googlecode.com/svn/trunk/
==> Checking out 4
svn: E170013: Unable to connect to a repository at URL 'http://s3sync-s3cmd.googlecode.com/svn/trunk'
svn: E160013: '/svn/trunk' path not found
Error: Failed to download resource "s3sync"
Failure while executing: svn checkout -q http://s3sync-s3cmd.googlecode.com/svn/trunk/ /Users/fdb/Library/Caches/Homebrew/s3sync--svn -r 4
```

I don't use the package (had it confused with s3cmd, which does work) but it should probably be removed or updated.

_Copied from original issue: Homebrew/brew#1548_

**Comment by ilovezfs** [comment]
The repo moved to https://github.com/ms4720/s3sync

**Comment by fxcoudert** [comment]
There have been no commit since 2012, no release since 2008, they don't publish released version sources or tag released versions, and after months nobody has responded to the issue opened asking for that. I say we remove it.

**Comment by fxcoudert** [comment]
https://github.com/Homebrew/homebrew-core/pull/10690
