### ISSUE TITLE
coreutils uname considered harmeful on Apple Silicon

### ISSUE THREAD

**Issue by mikepqr** [Homebrew/homebrew-core#71782]
**Provide a detailed description of the proposed feature**

Either:
- ship coreutils as a Universal Binary
- remove the `uname` binary from the coreutils package
- make the coreutils caveat text more dramatic

**What is the motivation for the feature?**

Unless it is compiled as a universal binary, `uname -m` is essentially a print statement that emits the architecture in use a build time. This is quite often wrong on Apple Silicon. But many build scripts rely on the output of `uname -m` to figure what architecture to use when building.

This means that if a user installed coreutils and follows the (optional) instructions to put it in their path, they can experience very confusing bugs when trying to build and install software.

See, e.g. https://github.com/Homebrew/install/issues/531, https://github.com/pyenv/pyenv/issues/1768#issuecomment-757552526.

**How will the feature be relevant to at least 90% of Homebrew users?**

It won't. This issue only affects users of the coreutils package.

**What alternatives to the feature have been considered?**

I've listed three possibilities above.

I don't know what's involved in Universal Binary builds of brew packages. Presumably if they were easy we'd already be doing them! But that's the best solution.

Removing `uname` from the package is the most dramatic. GNU uname and BSD uname are _almost_ identical, so this wouldn't be a huge loss for most users. The only difference is that GNU uname supports the following options (in additional to the standard GNU `--help` and `--version` options)
```
  -i, --hardware-platform  print the hardware platform (non-portable)
  -o, --operating-system   print the operating system
```

The final alternative is to emphasize in Caveats that this step may cause problems. This is the current text.
```
==> Caveats
Commands also provided by macOS have been installed with the prefix "g".
If you need to use these commands with their normal names, you
can add a "gnubin" directory to your PATH from your bashrc like:
  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
```

**Comment by Bo98** [comment]
We could possibly remove it from `gnubin` and leave `guname`. Therefore if anyone really needs the symlink, despite the issues, then they could still create it themselves.

**Comment by MikeMcQuaid** [comment]
> * ship coreutils as a Universal Binary

We cannot ship universal binaries in Homebrew.

> * make the coreutils caveat text more dramatic

You already had followed this by adding `/usr/local/opt/coreutils/libexec/gnubin` to your `PATH`.



> It won't. This issue only affects users of the coreutils package.

Moreso: users on Apple Silicon who also add `gnubin` to their `PATH` and rely on it being the correct architecture.

---

Passing on this for now. If we see more users complain about this we'll consider a change.

**Comment by mikepqr** [comment]
Fine with closing this until/unless it bites more people, but just to clarify what may have been unclear in my report
> You already had followed this by adding /usr/local/opt/coreutils/libexec/gnubin to your PATH.
Yes. I'm saying the caveat could include a warning. Something like "system tools depend on the behavior of your operating system's coreutils, and adding GNU coreutils to your path may cause unexpected behavior."

**Comment by haydenk** [comment]
This apparently conflicts with pyenv installing various python versions. `coreutils` is one of the main reasons why I have Homebrew installed.

With `coreutils` in the path I get below errors no matter what python version I select. When I remove `coreutils` from the path, everything works as expected.
```
/var/folders/1p/y_h8x2n53kb7zvgrx4gyzz440000gn/T/python-build.20210308203946.93022 ~
/var/folders/1p/y_h8x2n53kb7zvgrx4gyzz440000gn/T/python-build.20210308203946.93022/Python-3.7.9 /var/folders/1p/y_h8x2n53kb7zvgrx4gyzz440000gn/T/python-build.20210308203946.93022 ~
checking build system type... Invalid configuration `arm64-apple-darwin20.3.0': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin20.3.0 failed
make: *** No targets specified and no makefile found.  Stop.
```

---

```
/usr/bin/uname -a

Darwin Haydens-Mini 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

```
$BREW_HOME/opt/coreutils/libexec/gnubin/uname -a

Darwin Haydens-Mini 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64 arm64 Macmini9,1 Darwin
```

**Comment by carlocab** [comment]
The `coreutils` formula puts the unprefixed binaries in `gnubin` precisely because they tend to break things. Not really sure there's much more that can be done about that in Homebrew.

**Comment by mikepqr** [comment]
There are two suggestions in this thread:
1. Add a warning in the formula caveat saying the unprefixed binaries tend to break things.
2. Remove uname from coreutils, since it emits the architecture at build time rather than runtime, which means it will often be wrong in a way that causes confusing build bugs for brew users.

**Comment by MikeMcQuaid** [comment]
> * Add a warning in the formula caveat saying the unprefixed binaries tend to break things.

We'll review a PR for this.

> 2\. Remove uname from coreutils, since it emits the architecture at build time rather than runtime, which means it will often be wrong in a way that causes confusing build bugs for brew users.

I'd want to see many more users complaining about this to remove it.

**Comment by haydenk** [comment]
Ideally, I would still like to use coreutils, I suppose I could set the path to the bin folder instead of libexec/gnubin/, but I figured at the very least it would be nice to have the conflict link available in search results when people google the error.

**Comment by carlocab** [comment]
>I suppose I could set the path to the bin folder

You don't need to do that; `brew install coreutils` will symlink `coreutils`' `bin` directory into `$HOMEBREW_PREFIX/bin` on its own.
