### ISSUE TITLE
protobuf formula installs older python module

### ISSUE THREAD

**Issue by aabdnn** [Homebrew/homebrew-core#7180]
### Bug reports:

When protobuf is installed from a bottle, it also installs a python module, version 3.1.0. However, if I then run "pip list -o", pip reports that the module is outdated, because 3.1.0.post1 is available on PyPi.

Can the protobuf formula please be updated? Or is it possible to change the formula to install the python module from PyPi instead of bundling it in the bottle?

**Comment by MikeMcQuaid** [comment]
> Or is it possible to change the formula to install the python module from PyPi instead of bundling it in the bottle?

This is not possible.

> Can the protobuf formula please be updated?

Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
