### ISSUE TITLE
postgresql@12's pg_config --includedir-server is incorrect

### ISSUE THREAD

**Issue by RazerM** [Homebrew/homebrew-core#71918]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

brew config
```
HOMEBREW_VERSION: 3.0.2-40-gf14ed49
ORIGIN: https://github.com/Homebrew/brew
HEAD: f14ed4987f46de2dff36e0bc0b40615d56fa3c49
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e1a91e25cef3a193fafa050c9e056f599a94085f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_AUTO_UPDATE_SECS: 28800
HOMEBREW_BOOTSNAP: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: subl -n
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A
```

brew doctor
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/frazer.mclean/.pyenv/shims/python3.6m-config
  /Users/frazer.mclean/.pyenv/shims/python3.7-config
  /Users/frazer.mclean/.pyenv/shims/python3.7m-config
  /Users/frazer.mclean/.pyenv/shims/python3.9-config
  /Users/frazer.mclean/.pyenv/shims/python-config
  /Users/frazer.mclean/.pyenv/shims/python3-config
  /Users/frazer.mclean/.pyenv/shims/python3.6-config
  /Users/frazer.mclean/.pyenv/shims/pre-commit-validate-config
  /Users/frazer.mclean/.pyenv/shims/python3.8-config

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

****

- [ ] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Compile a postgres extension against my homebrew postgresql@12 installation

**What happened (include all command output)?**

postgres.h could not be found because pg_config returns a path that does not exist

```
# show the includedir-server value
$(brew --prefix postgresql@12)/bin/pg_config --includedir-server
/usr/local/opt/postgresql@12/include/server

# show that it doesn't exist
ls "$($(brew --prefix postgresql@12)/bin/pg_config --includedir-server)"
"/usr/local/opt/postgresql@12/include/server": No such file or directory (os error 2)

# find the real directory (the one containing postgres.h)
find "$(brew --prefix postgresql@12)/" -name postgres.h
/usr/local/opt/postgresql@12//include/postgresql/server/postgres.h
```

**What did you expect to happen?**

The directory output by pg_config should match the on-disk location.

postgresql @10, @11, and @13 all work in this regard.

If I compare postgresql@11 and postgresql@12 I see there are differences, which mention another fix:

https://github.com/Homebrew/homebrew-core/blob/97e9d1f96b976d74aa0736fac65aa7ad890035b9/Formula/postgresql%4012.rb#L76-L87

https://github.com/Homebrew/homebrew-core/blob/97e9d1f96b976d74aa0736fac65aa7ad890035b9/Formula/postgresql%4011.rb#L68-L76

**Step-by-step reproduction instructions (by running `brew` commands)**

```
brew install postgresql@12
ls "$($(brew --prefix postgresql@12)/bin/pg_config --includedir-server)"
```

**Comment by carlocab** [comment]
`includedir_server` looks correctly specified here:

https://github.com/Homebrew/homebrew-core/blob/97e9d1f96b976d74aa0736fac65aa7ad890035b9/Formula/postgresql%4012.rb#L86

Are you sure this is a bug in the way Homebrew is packaging `postgresql@12`? If it isn't, this needs to be reported upstream rather than here.

**Comment by RazerM** [comment]
The other postgresql version formulae use a different path there, which works (see the postgresql@11 snippet I pasted).

**Comment by carlocab** [comment]
I don't think that's true about all the other postgresql formulae:

https://github.com/Homebrew/homebrew-core/blob/97e9d1f96b976d74aa0736fac65aa7ad890035b9/Formula/postgresql.rb#L76

**Comment by Bo98** [comment]
Paths are probably baked in at compile time so the `install-world` values should be irrelevant and it should use what we pass to `./configure`.

That bug mentioend in the postgresql@12 file seems relevant. The `postgresql@12` prefix will contain "progres" because it is keg-only and we are using `opt_include` as `--includedir`.

I think we need to pass `pkgincludedir` to the first `make` call (since there is no `./configure` flag for it). We should also change that `pkglibdir` to `opt_lib` as I suspect `pg_config --pkglibdir` will return a Cellar path as it stands.
