### ISSUE TITLE
postgresql: Add option to enable logging?

### ISSUE THREAD

**Issue by kevinburke** [Homebrew/homebrew-core#7192]
Frequently when I install Postgres I want to enable the logging collector and log all queries, plus some other stuff. It's a pain to have to turn it on every time I install Postgres.

There are a few steps involved:

- Create the pg_log directory
- Set `logging_collector = on` in postgresql.conf (or in a conf.d/logging.conf file)
- Set `log_statement = 'all'`
- Set `log_duration = on`
- Set `log_lock_waits = on`

If I wrote this up as an optional installation flag to the `postgresql` formula, would you consider it? Maybe `--with-query-logging` ?

**Comment by MikeMcQuaid** [comment]
I don't think we want an option that modifies the default configuration, sorry. You may want to ask upstream PostgreSQL if they'd consider this option.
