### ISSUE TITLE
brew install valgrind issue on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by akhossanX** [Homebrew/homebrew-core#71975]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

brew config output: 
HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 66b499a642c4d74496e618a8981c4e819ae10bf1
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/akhossan/.brew
HOMEBREW_REPOSITORY: /Users/akhossan/.brew
HOMEBREW_CELLAR: /Users/akhossan/.brew/Cellar
HOMEBREW_CACHE: /tmp/akhossan/Homebrew/Caches
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_TEMP: /tmp/akhossan/Homebrew/Temp
Homebrew Ruby: 2.6.3 => /Users/akhossan/.brew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 10.0 build 1001
Git: 2.20.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A

brew doctor output: 

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/python3.7-config
  /usr/local/bin/python3.7m-config
  /usr/local/bin/python3-config

Warning: Your Cellar and TEMP directories are on different volumes.
macOS won't move relative symlinks across volumes unless the target file already
exists. Brews known to be affected by this are Git and Narwhal.

You should set the "HOMEBREW_TEMP" environment variable to a suitable
directory on the same volume as your Cellar.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/mlx.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libmlx.a

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.

****

- [ ] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

install valgrind 

**What happened (include all command output)?**

brew install valgrind 
gives the error:

valgrind: Linux is required for this software.
Error: An unsatisfied requirement failed this build.

**What did you expect to happen?**

i expect valgrind to be installed in ~/.brew/bin directory

**Step-by-step reproduction instructions (by running `brew` commands)**

brew update
brew install valgrind

**Comment by SMillerDev** [comment]
You're on macOS. Valgrind requires Linux to function. This is not a bug.
