### ISSUE TITLE
Running `brew doctor` on MacOS Catalina Produces Unfixable Warnings About Remote Origin

### ISSUE THREAD

**Issue by maxwellbenton** [Homebrew/homebrew-core#71974]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

Helping someone with a Homebrew install issue. Homebrew installs fine with:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

But fails to install any packages, producing errors like this for everything:

```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gmp".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

Running `brew doctor` produces one of two warnings that alternate - 

Initially, the message is that `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` is not set as the origin, with this as the recommended solution:

```
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
```

No errors are produced when running this, but running `brew doctor` again will give a similar warning about the remote origin, this time for `/usr/local/Homebrew`, recommending the following as solution:

```
git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew
```

Which will cause the first warning to reappear when running `brew doctor`. While using `Homebrew/homebrew-core`, `brew update` hangs. Neither can find any packages. No way to clear the `brew doctor` warning, just change it from one to the other.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

Trying to install Homebrew on a mid-2020 MacOS Catalina laptop, then install a few packages like `gmp` and `gnupg`

**What happened (include all command output)?**

No  brew packages can be found

```
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gmp".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**What did you expect to happen?**

Successful package installs

**Step-by-step reproduction instructions (by running `brew` commands)**

```
xcode-select --install
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew doctor
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
brew install gmp OR brew search gmp
brew install gnupg OR brew search gnupg

git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew
brew install gmp OR brew search gmp
brew install gnupg OR brew search gnupg
```

**Comment by SMillerDev** [comment]
They actually refer to two very different locations to run the command in. If you just change the last argument on every run you'll ruin different parts of homebrew on every run.

**Comment by maxwellbenton** [comment]
Thank you @SMillerDev! I saw thatt tone is affecting `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core` and the other is just `/usr/local//Homebrew`. Nothing was changed in those commands, they were both run as presented (no modifications to the commands), so I assumed they were both changing those specific origins, but for some reason causing conflicts with each other

**Comment by gromgit** [comment]
Run `brew update-reset`, then `brew doctor` again. Because the upstream URLs of your Homebrew software (`/usr/local/Homebrew`) and core tap (`/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core`) repos were not the standard ones, the state of your Homebrew install is actually unknown, and probably messed up.
