### ISSUE TITLE
Make brew store values of options like `--with-option=value`

### ISSUE THREAD

**Issue by chaimleib** [Homebrew/homebrew-core#7211]
When installing a package with an option like `--with-option=value`, it is important to remember the option together with its value, so that it can be applied again to future upgrades. Currently, brew remembers that `--with-option=` was specified, but it doesn't store what the `value` was. Could this be added?

Here's an example:
```
$ brew install chaimleib/formulae/repoactions --with-rc=$HOME/.bashrc.d/repoactions.sh
...

$ brew info repoactions
chaimleib/formulae/repoactions: stable 0.0.9
Run a script whenever you enter a git repo
https://github.com/chaimleib/repoactions
/usr/local/Cellar/repoactions/0.0.9 (9 files, 32.8K) *
  Built from source on 2016-11-22 at 14:01:07 with: --with-rc=
From: https://github.com/chaimleib/homebrew-formulae/blob/master/repoactions.rb
==> Options
--with-rc=
	Specify where to inject login setup (default: ~/.profile)

$ cat /usr/local/Cellar/repoactions/0.0.*/INSTALL_RECEIPT.json
{"used_options":["--with-rc="],"unused_options":[],"built_as_bottle":false,"poured_from_bottle":false,"changed_files":null,"time":1479852067,"source_modified_time":1479851836,"HEAD":"c3f959d6af36f075600aac63f208d59c30cd602c","stdlib":null,"compiler":"clang","runtime_dependencies":[],"source":{"path":"/usr/local/Homebrew/Library/Taps/chaimleib/homebrew-formulae/repoactions.rb","tap":"chaimleib/formulae","spec":"stable","versions":{"stable":"0.0.9","devel":null,"head":null,"version_scheme":0}}}
```

#2767 made brew remember which options were specified, but the values of options are not being stored yet.

**Comment by ilovezfs** [comment]
@chaimleib fyi https://github.com/Homebrew/brew/pull/566

**Comment by chaimleib** [comment]
@ilovezfs It looks like they resolved their issue by removing installation options from their recipe, and no change was made to the internal logic of brew.

**Comment by ilovezfs** [comment]
@chaimleib correct, that code was not merged.

**Comment by ilovezfs** [comment]
No one is actively working on this at this time, but PRs would certainly be welcome.
