### ISSUE TITLE
Unable to install Silicon formula

### ISSUE THREAD

**Issue by bkuhlmann** [Homebrew/homebrew-core#72168]
**`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**

brew config

HOMEBREW_VERSION: 3.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: b712bcc01e8fdaae25d6f232f51637bf00db307f
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b3c929deae82b60a3b425a281ef95e7f0b0b9097
Core tap last commit: 20 hours ago
Core tap branch: HEAD
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: sublime
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_INSECURE_REDIRECT: set
HOMEBREW_NO_INSTALL_CLEANUP: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/opt/git/bin/git
Curl: 7.75.0 => /opt/homebrew/opt/curl/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

brew doctor

Your system is ready to brew.

****

- [X] The `brew doctor` above contains no "Warning" lines.

**What were you trying to do (and why)?**

I was trying to run `brew install silicon` in order to install the Rust-based screen capture tool.

**What happened (include all command output)?**

Warning: Treating silicon as a formula. For the cask, use homebrew/cask/silicon
Error: silicon: no bottle available!
You can try to install from source with:
  brew install --build-from-source silicon

**What did you expect to happen?**

Expected to see Silicon install cleanly and without error like it used to on Intel based machines. This error is new for Silicon based hardware.

**Step-by-step reproduction instructions (by running `brew` commands)**

On a Apple Silicon machine, run: `brew install silicon`.

**Comment by carlocab** [comment]
`silicon` doesn't support Apple M1 yet. If you'd like that to be fixed, please report it to the `silicon` developers.

There's nothing Homebrew can do about the fact that it doesn't build on Apple M1 yet.

See also #68301.
