### ISSUE TITLE
Missing info in mysql_config prevents building/linking against it

### ISSUE THREAD

**Issue by DrHyde** [Homebrew/homebrew-core#72333]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

$ brew config
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 87 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 26105415394a70964740cb9f671d1634c196b9ea
Core tap last commit: 66 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /usr/bin/vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.32.29
Xcode: 12.4
$ brew doctor
Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Build DBD::mysql from the CPAN (because I need to talk to a MySQL database from my perl code)

### What happened (include all command output)?

The build failed, because "Can't link/include C library 'ssl', 'crypto', aborting". I won't provide all the output because it goes on for pages and pages and is mostly irrelevant. The relevant bit is ...

```
I will use the following settings for compiling and testing:

  cflags        (mysql_config) = -I/usr/local/Cellar/mysql/8.0.23_1/include/mysql
  embedded      (guessed     ) =
  ldflags       (guessed     ) =
  libs          (mysql_config) = -L/usr/local/Cellar/mysql/8.0.23_1/lib -lmysqlclient -lssl -lcrypto
-lresolv
  mysql_config  (guessed     ) = mysql_config
  nocatchstderr (default     ) = 0
  nofoundrows   (default     ) = 0
  nossl         (default     ) = 0
  testdb        (default     ) = test
  testhost      (default     ) =
  testpassword  (default     ) =
  testport      (default     ) =
  testsocket    (default     ) =
  testuser      (guessed     ) = dcantrell

To change these settings, see 'perl Makefile.PL --help' and
'perldoc DBD::mysql::INSTALL'.

Checking if libs are available for compiling...
Can't link/include C library 'ssl', 'crypto', aborting.
-> N/A
-> FAIL Configure failed for DBD-mysql-4.050. See /Users/dcantrell/.cpanm/work/1614703692.86342/build
.log for details.
```

### What did you expect to happen?

The build to succeed. To *make* it succeed, edit `/usr/local/bin/mysql_config`, which is installed by the formula, and immediately after this line:

```
libs="-L$pkglibdir"
```

insert this line:

```
libs="$libs -L/usr/local/opt/openssl/lib"
```

### Step-by-step reproduction instructions (by running `brew` commands)

$ brew install mysql # or reinstall
$ cpanm DBD::mysql

**Comment by DrHyde** [comment]
NB that there's a fix ^ up there in the report. The fix comes from @homqyy [on StackOverflow](https://stackoverflow.com/a/56196487/261131).

**Comment by Bo98** [comment]
I think this is a consequence of MySQL's build scripts trying to copy OpenSSL libraries to its own lib directory, which we try to undo. Properly patching those build scripts might fix this.

**Comment by DrHyde** [comment]
Bug reported upstream: https://bugs.mysql.com/bug.php?id=103227
