### ISSUE TITLE
Ktlint jdk dependcy has to be 11 

### ISSUE THREAD

**Issue by subspider** [Homebrew/homebrew-core#72336]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

brew config
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3fc56997e986d0ceb5f300c01ef76edfdc43aa02
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Trying to avoid that formulae from ktlint install openjdk15 when in fact only openjdk11 is supported

### What happened (include all command output)?

brew install ktlint
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://homebrew.bintray.com/bottles/openjdk-15.0.1.arm64_big_sur.bottle.1.t
Already downloaded: /Users/pedrosantos/Library/Caches/Homebrew/downloads/71a21626f6690a21ee1764092d91146ae286323e9a02a44d9d3c76aa0c0eb27e--openjdk-15.0.1.arm64_big_sur.bottle.1.tar.gz
==> Downloading https://github.com/pinterest/ktlint/releases/download/0.40.0/ktlint
Already downloaded: /Users/pedrosantos/Library/Caches/Homebrew/downloads/8c1626a47dae0aac0ca01fe923390e3580c075d7add9880c40122c0c820066d9--ktlint
==> Installing dependencies for ktlint: openjdk
==> Installing ktlint dependency: openjdk
==> Pouring openjdk-15.0.1.arm64_big_sur.bottle.1.tar.gz
Error: Failed applying an ad-hoc signature to /opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib:
/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib: replacing existing signature
/opt/homebrew/Cellar/openjdk/15.0.1/libexec/openjdk.jdk/Contents/MacOS/libjli.dylib: resource fork, Finder information, or similar detritus not allowed

### What did you expect to happen?

that install ktlint and openjdk11

### Step-by-step reproduction instructions (by running `brew` commands)

 brew install ktlint

**Comment by SMillerDev** [comment]
Is it actually broken? Or just not in the upstream support list?

**Comment by carlocab** [comment]
It seems like your problem here is that you're not able to install openjdk, not that ktlint has the wrong dependency. It may well be that it does, but we should probably have proper verification of that.

**Comment by subspider** [comment]
@carlocab @SMillerDev so according to https://github.com/pinterest/ktlint/issues/1063 the issue is that if you use 15 it's an issue so we need to make the formulae to depend only on JDK11 I opening a PR to fix it

**Comment by carlocab** [comment]
Please install `openjdk` properly first and then verify that ktlint is not working.

**Comment by subspider** [comment]
@carlocab according to this https://github.com/pinterest/ktlint/issues/1063 it is runned and tested in my machine and it's an issue

**Comment by carlocab** [comment]
We also ran and tested it in https://github.com/Homebrew/homebrew-core/pull/66267, and it wasn't an issue, so we need to figure out what exactly is going wrong here first before we discuss switching ktlint to openjdk@11.

**Comment by subspider** [comment]
according to @shashachu ktlint will support jdk15 in the next 2 weeks so this shouldn't be a problem by then
