### ISSUE TITLE
yelp-tools package is version 3.18 but related yelp-xsl package is 3.20

### ISSUE THREAD

**Issue by ajdavis** [Homebrew/homebrew-core#7243]
The Mallard / GNOME documentation generator package "yelp-tools" is version 3.18 in Homebrew core. It can use XSLT templates from the related yelp-xsl package, except it's expecting to have the same yelp-xsl version, 3.18. Unfortunately the current version in Homebrew is 3.20. This leads to:

```
/usr/local/bin/yelp-build html -o OUTPUT-DIR INPUT-DIR
warning: failed to load external entity "/usr/local/Cellar/yelp-xsl/3.18.0/share/yelp-xsl/xslt/mallard/cache/mal-cache.xsl"
cannot parse /usr/local/Cellar/yelp-xsl/3.18.0/share/yelp-xsl/xslt/mallard/cache/mal-cache.xsl
```

This temporarily hacks a solution:

```
> cd /usr/local/Cellar/yelp-xsl/
> ln -s 3.20.1 3.18.0
```

**Comment by mistydemeo** [comment]
It looks like yelp-tools is the only thing that uses yelp-xsl, so it probably doesn't make sense to have bumped its version like this.

**Comment by MikeMcQuaid** [comment]
> It looks like yelp-tools is the only thing that uses yelp-xsl, so it probably doesn't make sense to have bumped its version like this.

Ideally I think `yelp-xsl` would be installed as a resource as part of `yelp-xsl` and they be bound programmantically to use the same version.

@ajdavis Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
