### ISSUE TITLE
icu4c.rb: Head repo URL incorrect 

### ISSUE THREAD

**Issue by moderndeveloperllc** [Homebrew/homebrew-core#7249]
`"https://ssl.icu-project.org/repos/icu/icu/trunk/", :using => :svn` does not exist. Best I can tell is that it has changed to `https://ssl.icu-project.org/repos/icu/trunk/icu4c/`, It doesn't look like icu4j has a formula, so this should be the only change.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by moderndeveloperllc** [comment]
@MikeMcQuaid Done.

**Comment by MikeMcQuaid** [comment]
Closing in favour of PR in https://github.com/Homebrew/homebrew-core/issues/7357, thanks!
