### ISSUE TITLE
sourcery 1.3.1 conflicts with swift-doc

### ISSUE THREAD

**Issue by pascal-hofmann** [Homebrew/homebrew-core#72608]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6c5fc2a04a6f21c2d9ef63abb559ff6b6891d432
Core tap last commit: 62 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.26.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: N/A
Xcode: 12.0.1 => /Applications/Xcode_12.0.1.app/Contents/Developer

```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unknown support status

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  sourcery


Warning: Your Xcode (12.0.1) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### 

- [ ] <del>The `brew doctor` above contains no "Warning" lines.</del> -> It does, because linking does not work without overwrite.  Conflicting file was introduced with #72460.

### What were you trying to do (and why)?

brew link sourcery

### What happened (include all command output)?

Linking /usr/local/Cellar/sourcery/1.3.1...
Error: Could not symlink lib/lib_InternalSwiftSyntaxParser.dylib
Target /usr/local/lib/lib_InternalSwiftSyntaxParser.dylib
is a symlink belonging to swift-doc. You can unlink it:
  brew unlink swift-doc

To force the link and overwrite all conflicting files:
  brew link --overwrite sourcery

To list all files that would be deleted:
  brew link --overwrite --dry-run sourcery

### What did you expect to happen?

No error and no conflicting file.

### Step-by-step reproduction instructions (by running `brew` commands)

brew link swift-doc
brew link sourcery

**Comment by gromgit** [comment]
I don't see a `swift-doc` formula in Homebrew core, so you'll have to raise an issue with upstream (I'm guessing https://github.com/SwiftDocOrg/homebrew-formulae).

**Comment by SMillerDev** [comment]
Yeah, homebrew can't declare conflicts with external taps so it's up to the tap to address this conflict.
