### ISSUE TITLE
nginx.pid Questionable Location in Big Sur

### ISSUE THREAD

**Issue by daBee** [Homebrew/homebrew-core#72617]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

/opt/homebrew/etc/nginx stable ❯ brew gist-logs nginx                                        05:10:34
Error: No logs.

#############################################################

HOMEBREW_VERSION: 3.0.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee52b19179d056f3dd2fdf9c52214d3d51dbb9d9
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3cc6a063d22d8e3c12ed013b71be394881bb56aa
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: bbedit
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false

/opt/homebrew/etc/nginx stable ❯ brew doctor                                                 05:12:20
Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Install nginx, get it running in Big Sur

### What happened (include all command output)?

Installed, didn't know where to install nginx.pid.  Currently it's in /opt/homebrew/var/run/nginx.pid as this is Big Sur, where homebrew installs into /opt/homebrew.

### What did you expect to happen?

A least a suggestion of where to put nginx.pid in the nginx.conf directives.  The package installs a default nginx.conf with this entry:

#pid        logs/nginx.pid;

Not very helpful.  

### Step-by-step reproduction instructions (by running `brew` commands)

brew install nginx passenger

**Comment by SMillerDev** [comment]
You can decide for yourself where you put your pid file. Homebrew doesn't care.
