### ISSUE TITLE
nano.rb - Nano looks for nanorc in /usr/local/etc rather than in /etc

### ISSUE THREAD

**Issue by ChrisBaker97** [Homebrew/homebrew-core#72698]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
$ brew gist-logs nano
Error: No logs.
```

```
$ brew config
HOMEBREW_VERSION: 3.0.4-52-gbc37074
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc370748c91940ef95eeaf5b6c4e48a827dadb5e
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 37e10782b5b61184b0e425352adf4cd32f3a28e2
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BROWSER: open
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /Users/chris/.local/bin/edit
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 11.0 build 1100
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Trying to configure global settings for Nano by editing `/etc/nanorc`.

### What happened (include all command output)?

Changes to `/etc/nanorc` were having no effect. Moving or sym-linking `/etc/nanorc` to `/usr/local/etc/nanorc` fixed the issue. Thus, Homebrew's Nano is looking for global config files in `/usr/local/etc` rather than in `/etc`. 

### What did you expect to happen?

I expected that editing `/etc/nanorc` would set global options for Nano, per `man nano` and `man nanorc`. It seems as if this is the intended behavior, since the formula passes `--sysconfdir=#{etc}` to `./configure`. However, [there appears to be a longstanding bug upstream that the maintainers are aware of](https://savannah.gnu.org/bugs/?55376) but haven't fixed, other than [to have `./configure` confirm the incorrect directory in its output](https://savannah.gnu.org/bugs/?57061).

### Step-by-step reproduction instructions (by running `brew` commands)

First ensure you don't have a pre-existing `~/.nanorc` or `~/.config/nano/nanorc` file that's enabling syntax highlighting.
```
$ brew install nano
$ echo "include /usr/local/share/nano/*.nanorc" >> /etc/nanorc
$ nano /tmp/test.rb
```
Write or copy some Ruby code and note that nothing is being color highlighted. Save. (<kbd>CTRL</kbd>-<kbd>X</kbd> <kbd>Y</kbd> <kbd>ENTER</kbd>)
```
$ nano --rcfile=/etc/nanorc /tmp/test.rb
```
Note that code should now be highlighted, confirming that `/etc/nanorc` works, if loaded explicitly.
```
$ ln -s /etc/nanorc /usr/local/etc/nanorc
$ nano /tmp/test.rb
```
Observe that the configuration is being read from `/usr/local/etc` rather than from `/etc`.

---

This doesn't seem to be Homebrew's fault, but given that it's confusing, and upstream apparently isn't concerned with fixing it, I think we should maybe at least add a caveat to alert the user, if not some sort of patch or workaround to fix the functionality (such as creating a sym-link at `/usr/local/etc/nanorc` pointing to `/etc/nanorc` on post-install).

**Comment by ChrisBaker97** [comment]
Okay, maybe I'm confused on the Homebrew convention. I see now, after running `brew reinstall --verbose --build-from-source nano` that `#{etc}` does indeed expand into `/usr/local/etc` rather than `/etc`, passing `--sysconfdir=/usr/local/etc` to `./configure`. If that's the intended location, then I'm not sure how I never noticed that all my Homebrew programs were supposed to be configured in `/usr/local/etc` rather than `/etc`, but I suppose that makes sense, since anything written to `/etc` requires elevated privileges. (Although in this case, no default `nanorc` is generated during the install.) Now I'm sitting here wondering if this might explain a lot of banging my head against the wall over the years, trying to configure global options on programs installed using `brew`... I still think a caveat would be helpful, but maybe it's not appropriate if it's consistent with how every formula should operate?

**Comment by SMillerDev** [comment]
> I still think a caveat would be helpful, but maybe it's not appropriate if it's consistent with how every formula should operate?

We only display a caveat when software only looks at `/etc` despite our changes.
