### ISSUE TITLE
Yarn global packages with brew's node.js no longer work on node update.

### ISSUE THREAD

**Issue by publicarray** [Homebrew/homebrew-core#7283]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

yarn global install symlinks packages into `/usr/local/Cellar/node/{node version}/bin`. yarn's [install instructions](https://yarnpkg.com/en/docs/install) are to add `yarn global bin` to the path. At first there is no problem but when node is updated with brew the linked binaries no longer work. I think that it the issue is probably more with yarn but maybe a caveat should be printed at install?

```bash
> yarn global bin
/usr/local/Cellar/node/7.2.0/bin
> yarn --version
0.17.9
> brew --version
Homebrew 1.1.1-95-g84b3c57
Homebrew/homebrew-core (git revision c4c5; last commit 2016-11-27)
> node --version
v7.2.0
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555
```
Maybe related: https://github.com/yarnpkg/yarn/issues/1877 and https://github.com/yarnpkg/yarn/issues/1321

Sorry if it's a dupe. Also apologies if it's the wrong repo to report this.

**Comment by MikeMcQuaid** [comment]
I don't think this is a Homebrew issue as Yarn is acting as intended. Rather than a caveat I'd rather see a fix in Yarn to install things into an expected location or have `yarn global bin` return `/usr/local/opt/node/bin`. We'll accept PRs for these. Thanks!

**Comment by publicarray** [comment]
@MikeMcQuaid what do you think about adding `yarn config set prefix /usr/local -g` to the install step?  
ref: https://github.com/yarnpkg/yarn/issues/2064#issuecomment-289273423

**Comment by MikeMcQuaid** [comment]
@publicarray I tried it and it doesn't work as it tries to write to `$HOME`.  Try to find out what file needs to be written where for global configuration, thanks!

**Comment by publicarray** [comment]
@MikeMcQuaid  Besides the `$HOME/.yarnrc` file I can't seem to find any yarn specific config files. There is an open issue to have global configs: https://github.com/yarnpkg/yarn/issues/1037

**Comment by MikeMcQuaid** [comment]
@publicarray What file does `yarn config set prefix /usr/local -g` write to?

**Comment by publicarray** [comment]
Sorry @MikeMcQuaid, yarn writes to `~/.yarnrc`

```shell
~ ❯ cat ~/.yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lastUpdateCheck 1490570476609
prefix "/usr/local"
```

**Comment by MikeMcQuaid** [comment]
@publicarray We can't fix this until there's a global `yarnrc` file we can write to from an `install` block.

**Comment by HenrikWL** [comment]
Can't the formula do a

`yarn config set prefix ${HOMEBREW_PREFIX}`

as a post-install or something? Or does it go against good practice?
