### ISSUE TITLE
qt6.0.2 do not install any pkg-config file (*.pc) ?

### ISSUE THREAD

**Issue by mpoirier-enac** [Homebrew/homebrew-core#72890]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I'm looking for *.pc of the qt (6.0.2) new update. I can't found them.
They use to been in /usr/local/Cellar/qt/5.15.2/lib/pkgconfig ... this directory doesn't exist anymore 

### What happened (include all command output)?

cmd:
sudo find /usr/* -name "Qt*Core.pc"
output:
/usr/local/Cellar/qt@5/5.15.2/lib/pkgconfig/Qt53DCore.pc
/usr/local/Cellar/qt@5/5.15.2/lib/pkgconfig/Qt5Core.pc
/usr/local/Cellar/qt@5/5.15.2/lib/pkgconfig/Qt5WebEngineCore.pc

### What did you expect to happen?

cmd:
sudo find /usr/* -name "Qt*Core.pc"
output (at least):
...
/usr/local/Cellar/qt/6.0.2/lib/pkgconfig/Qt6Core.pc
...
/usr/local/Cellar/qt@5/5.15.2/lib/pkgconfig/Qt53DCore.pc
/usr/local/Cellar/qt@5/5.15.2/lib/pkgconfig/Qt5Core.pc
/usr/local/Cellar/qt@5/5.15.2/lib/pkgconfig/Qt5WebEngineCore.pc

### Step-by-step reproduction instructions (by running `brew` commands)

brew upgrade (because i need to test qt6) (it's upgrate qt to qt6.0.2 and delete qt5.15.2)
brew install qt@5 (to keep working)

**Comment by Bo98** [comment]
Qt6 does not ship with pkg-config files. This isn't specific to Homebrew I'm afraid. You can follow https://bugreports.qt.io/browse/QTBUG-86080 for updates.

CMake and `qmake` modules are available as an alternative. `meson` uses these.

**Comment by mpoirier-enac** [comment]
thanx for the info , i added my comment there.
I don't use cmale, qmake or meson too bad
