### ISSUE TITLE
"mongo-c" is a weird name, libmongoc or mongo-c-driver would be better

### ISSUE THREAD

**Issue by ajdavis** [Homebrew/homebrew-core#7290]
I'm the libbson and mongo-c-driver maintainer. Until now I haven't been involved with the Homebrew formulae, but I'd like to help keep them up to date from now on.

Question: is it possible to change the name of the "mongo-c" formula? That is an eccentric name to use for the MongoDB C Driver. Users will expect it to be named either "libmongoc" (the name of the Debian package and the SONAME) or to "mongo-c-driver" (the name of the Fedora package and the repository).

Is it possible to rename Homebrew packages? What is the procedure?

**Comment by timkuijsten** [comment]
related to the new libmongoc formula that got accepted yesterday: #7261

**Comment by timotheecour** [comment]
@ajdavis is that related? https://github.com/Homebrew/homebrew-core/issues/7291

**Comment by ajdavis** [comment]
It *is* related. That formula should supersede "mongo-c". Should we delete "mongo-c" or mark it deprecated somehow?

**Comment by timkuijsten** [comment]
Furthermore, comparing https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongo-c.rb with https://github.com/Homebrew/homebrew-core/blob/master/Formula/libmongoc.rb I think we should merge and add `conflicts_with "libbson"` and maybe the `head do` block.

Also, what about the test? I only tested a bson function since it doesn't require a running database.

**Comment by ajdavis** [comment]
I agree about merging the "head do" and "conflicts_with" from mongo-c.

I think that merely *compiling* example-ping.c proves the package worked; no need to run the example program.

**Comment by timkuijsten** [comment]
> I think that merely compiling example-ping.c proves the package worked; no need to run the example program.

From https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#add-a-test-to-the-formula:
> We want tests that don't require any user input and test the basic functionality of the application. For example foo build-foo input.foo is a good test and (despite their widespread use) foo --version and foo --help are bad tests. However, a bad test is better than no test at all.

**Comment by timkuijsten** [comment]
I updated the formula to set it conflicts with libbson: https://github.com/Homebrew/homebrew-core/pull/7303

I also tried to set the head option[1], but `brew install --HEAD libmongoc` fails. I suspect it has something to do with configure that does not exist but I'm not sure. Partial output from brew install --verbose --debug --HEAD libmongoc:

==> Cloning https://github.com/mongodb/mongo-c-driver.git
Updating /Users/tim/Library/Caches/Homebrew/libmongoc--git
git config remote.origin.url https://github.com/mongodb/mongo-c-driver.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
==> Checking out branch master
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at e3e18ce CDRIVER-1924 doc how to pass collation to commands
git submodule foreach --recursive git submodule sync
Entering 'src/libbson'
git submodule update --init --recursive
==> ./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/libmongoc/HEAD-e3e18ce --enable-man-pages --enable-ssl=darwin
Failed to execute: ./configure
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/usr/local/Cellar/libmongoc/HEAD-e3e18ce --enable-man-pages --enable-ssl=darwin

see https://github.com/timkuijsten/homebrew-core/commit/108e743b57cfa97284ac009a631ecf23271c1ddd

**Comment by apjanke** [comment]
> It is related. That formula should supersede "mongo-c". Should we delete "mongo-c" or mark it deprecated somehow?

If `libmongoc` supersedes `mongo-c`, then we should probably boneyard `mongo-c` (move it from core to the homebrew/boneyard tap; it's what we do with deleted formulae).

**Comment by apjanke** [comment]
Or if one is just a new iteration of the other, we could just make `mongo-c` an alias for `libmongoc`. Though that might have some weird effects now that both have been in existence at the same time already.

**Comment by apjanke** [comment]
> Is it possible to rename Homebrew packages? What is the procedure?

And FYI, yes, formula renaming is possible; here's the procedure: https://github.com/Homebrew/brew/blob/master/docs/Rename-A-Formula.md. In retrospect, that might have been what we should have done here, but I'm not sure about side effects now that both formula names have already been used.

**Comment by timkuijsten** [comment]
> In retrospect, that might have been what we should have done here, but I'm not sure about side effects now that both formula names have already been used.

That's my bad, I only discovered mongo-c after I created the formula for libmongoc (I only searched on mongoc and mongo-c-driver).

**Comment by MikeMcQuaid** [comment]
> If libmongoc supersedes mongo-c, then we should probably boneyard mongo-c (move it from core to the homebrew/boneyard tap; it's what we do with deleted formulae).

I think what we should do is delete the newer formula (rather than boneyard), rename the old one if need be to whatever the preferred name is (probably `libmongoc` for me) and add aliases to all the other name options.

**Comment by MikeMcQuaid** [comment]
A larger refactor PR has been opened in https://github.com/Homebrew/homebrew-core/pull/7352. Comments (and help!) welcome there, thanks.

**Comment by MikeMcQuaid** [comment]
Addressed in https://github.com/Homebrew/homebrew-core/pull/7352 which is now merged.
