### ISSUE TITLE
libyaml has invalid Cflags in pkgconfig file

### ISSUE THREAD

**Issue by stack** [Homebrew/homebrew-core#7304]
I'm attempting to use `libyaml` in a project on my Mac. The cflag values from `pkg-config yaml-0.1 --cflags` comes back empty, where any other package from homebrew has `Cflags: -I${includedir}` at the very least.

**Comment by MikeMcQuaid** [comment]
This should be submitted to `libyaml` themselves as an issue, we're not creating the `pkg-config` file here. Additionally, we don't really consider it an issue if it's not causing issues for our formulae.
