### ISSUE TITLE
mysql@5.7 on apple m1 crashes on stress test

### ISSUE THREAD

**Issue by chaudhryjunaid** [Homebrew/homebrew-core#73072]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output
brew config:
HOMEBREW_VERSION: 3.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8b677c0ddd5f96b5521c1b353a9ca07dfe57b80e
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e2cca2c2a5a175b2c94988366f1eaea2dfc6886a
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.30.2 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Rosetta 2: false

brew doctor:
Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

use the mysql@5.7 server for my any load intensive task

### What happened (include all command output)?
/opt/homebrew/opt/mysql@5.7/bin/mysqlslap: Error when connecting to server: 2013 Lost connection to MySQL server at 'reading initial communication packet', system error: 102
/opt/homebrew/opt/mysql@5.7/bin/mysqlslap: Error when connecting to server: 2013 Lost connection to MySQL server at 'reading initial communication packet', system error: 102
/opt/homebrew/opt/mysql@5.7/bin/mysqlslap: Error when connecting to server: 2013 Lost connection to MySQL server at 'reading initial communication packet', system error: 102
...(contd)

### What did you expect to happen?

mysqlslap succeeds and reports Benchmark results

### Step-by-step reproduction instructions (by running `brew` commands)

brew services start mysql@5.7
/opt/homebrew/opt/mysql@5.7/bin/mysqlslap --concurrency=5 --iterations=200000 --number-int-cols=2 --number-char-cols=3 --auto-generate-sql

Mysql server will crash and client will report above error.

**Comment by chaudhryjunaid** [comment]
updated step-by-step reproduction instructions!

**Comment by SMillerDev** [comment]
> Run various SQL queries on the mysql server in a loop for about a minute.

This is not a reproduction instruction and your error log is clearly not from brew or mysql.

I can't reproduce this using the commands provided and I'm closing it until you can give me a list of commands I need to run to make this happen.

**Comment by chaudhryjunaid** [comment]
@SMillerDev I have updated the reproduction steps to use only binaries from within the mysql package. Kindly take a look and re-open this ticket please! This bug is a big pain point.

**Comment by SMillerDev** [comment]
And this doesn't happen if you install the mysql server from the upstream binaries?

**Comment by chaudhryjunaid** [comment]
I tried to find a version on mysql website for m1 but there's only source available. If you can guide me I can try compiling from that source?

**Comment by chaudhryjunaid** [comment]
There is a version for windows and intel macs but none for m1 macs.

**Comment by SMillerDev** [comment]
I think there is your answer. It builds on ARM but doesn't seem officially supported yet. You should file an issue on their bug tracker.

**Comment by chaudhryjunaid** [comment]
Thanks @SMillerDev
