### ISSUE TITLE
Can't install tomcat-native on mac sierra

### ISSUE THREAD

**Issue by gilsheps** [Homebrew/homebrew-core#7309]
### Bug reports:
After i run brew install tomcat i get error when i tried to install tomcat-native
this is the error that I get:
gilsheps@Gil-MacBook-Pro:~|⇒  brew install tomcat-native                
==> Using the sandbox
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-connectors/native/1.2.8/source/tomcat-native-1.2.8-src.tar.gz
Already downloaded: /Users/gilsheps/Library/Caches/Homebrew/tomcat-native-1.2.8.tar.gz
==> ./configure --prefix=/usr/local/Cellar/tomcat-native/1.2.8 --with-apr=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr --with-java-home=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home --with-ssl=/u
Last 15 lines from /Users/gilsheps/Library/Logs/Homebrew/tomcat-native/01.configure:

./configure
--prefix=/usr/local/Cellar/tomcat-native/1.2.8
--with-apr=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr
--with-java-home=/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
--with-ssl=/usr/local/opt/openssl

checking build system type... x86_64-apple-darwin16.1.0
checking host system type... x86_64-apple-darwin16.1.0
checking target system type... x86_64-apple-darwin16.1.0
checking for a BSD-compatible install... /usr/bin/install -c
checking for working mkdir -p... yes
Tomcat Native Version: 1.2.8
checking for chosen layout... tcnative
checking for APR... configure: error: the --with-apr parameter is incorrect. It must specify an install prefix, a build directory, or an apr-config file.

https://gist.github.com/5fc2cda9e0e40b01b855cfcaf5b8be32

### Formula Requests:
http://brewformulas.org/TomcatNative

**Comment by dunn** [comment]
This should be fixed by 85ab16fcc9, can you try `brew update` and installing again

**Comment by ilovezfs** [comment]
Please let us know if this is still a problem.
