### ISSUE TITLE
ffmpeg doesn‘t --enable-librtmp by default for good reason: It‘s buggy and FFMPEG includes a better RTMP implementation built-in

### ISSUE THREAD

**Issue by mindfulpath** [Homebrew/homebrew-core#73396]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

https://gist.github.com/ec838669222c46c63b68038bf8b7129b

Well, it does include warnings, but that is not the issue here.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I’m trying to transcode and stream to YouTube. To make it reproducible, I transcode it once and then copy the file into a stream.

### What happened (include all command output)?

It starts normally, but then it does a strlen or something where it shouldn’t (and really, nobody should be using strlen, it’s such a bad programming language design and operating system-wide API) and it stops at a certain point with:

[flv @ 0x7f923700de00] Failed to update header with correct duration.d=   1x    
[flv @ 0x7f923700de00] Failed to update header with correct filesize.
av_interleaved_write_frame(): End of file
Error writing trailer of rtmp://a.rtmp.youtube.com/live2/my-key-goes-here: End of file

It should fail to update the header, because of course you can’t random-access a network stream, but the av_interleaved_write_frame() indicates a break in the middle of a frame.

Full output:
ffmpeg version 4.3.2-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'myfile.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : myfile
    encoder         : Lavf58.45.100
    keywords        : iMovie
  Duration: 01:11:33.50, start: 0.000000, bitrate: 19334 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3840x2160 [SAR 1:1 DAR 16:9], 19211 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      timecode        : 00:00:00:00
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 116 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : Core Media Video
      timecode        : 00:00:00:00
Output #0, fifo, to 'rtmp://a.rtmp.youtube.com/live2/my-key-goes-here':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : myfile
    keywords        : iMovie
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: h264 (High) ([7][0][0][0] / 0x0007), yuv420p, 3840x2160 [SAR 1:1 DAR 16:9], q=2-31, 19211 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc (default)
    Metadata:
      handler_name    : Core Media Video
      timecode        : 00:00:00:00
    Stream #0:1(eng): Audio: aac (LC) ([10][0][0][0] / 0x000A), 48000 Hz, stereo, fltp, 116 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[flv @ 0x7f923700de00] Failed to update header with correct duration.d=   1x    
[flv @ 0x7f923700de00] Failed to update header with correct filesize.
av_interleaved_write_frame(): End of file
Error writing trailer of rtmp://a.rtmp.youtube.com/live2/my-key-goes-here: End of file
frame=31781 fps= 24 q=-1.0 Lsize=N/A time=00:22:03.82 bitrate=N/A speed=   1x    
video:3216483kB audio:19316kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

### What did you expect to happen?

I expect it not to die prematurely. Static copies of ffmpeg I acquired elsewhere that do not use rtmpdump do not crash here.

The last few lines of command output should look more like:
[flv @ 0x7f896e80a600] Failed to update header with correct duration.ed=   1x    
[flv @ 0x7f896e80a600] Failed to update header with correct filesize.
frame=102940 fps= 24 q=-1.0 Lsize=N/A time=01:11:33.43 bitrate=N/A speed=   1x    
video:10068890kB audio:60897kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

### Step-by-step reproduction instructions (by running `brew` commands)

ffmpeg -re -i i-dont-have-something-clean-for-you-to-use.mp4 -map 0:v -map 0:a -c copy -vtag 7 -atag 10 -f flv rtmp://a.rtmp.youtube.com/live2/my-key-goes-here

Google up and find: https://trac.ffmpeg.org/ticket/7547

**Comment by carlocab** [comment]
The quickest way to fix this is probably to open a PR so it can be reviewed.

Though, looking at the FFmpeg formula, it doesn't enable _a lot_ of things by default. Are those for good reasons too? Because I am in favour of disabling a lot of those to simplify the formula.

**Comment by alebcay** [comment]
https://github.com/Homebrew/homebrew-core/pull/73619 has been merged.
