### ISSUE TITLE
pyqt5 should be an Alias for pyqt@5 not pyqt.

### ISSUE THREAD

**Issue by MehdiChinoune** [Homebrew/homebrew-core#73409]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

Your system is ready to brew.

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Install PyQt5

### What happened (include all command output)?

brew start installing pyqt which install pyqt6

### What did you expect to happen?

install pyqt@5

### Step-by-step reproduction instructions (by running `brew` commands)

```
brew install pyqt5
```

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.
