### ISSUE TITLE
QEMU networking broken - upstream patch available

### ISSUE THREAD

**Issue by arichardson** [Homebrew/homebrew-core#73517]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Downloading files in a virtual machine with -netdev virtio

### What happened (include all command output)?

Downloading files fails with an early end of connection. The problem has been fixed in libslirp but the released version is broken.

Could homebrew apply this patch to the QEMU package? https://gitlab.freedesktop.org/slirp/libslirp/-/commit/7271345efe182199acaeae602cb78a94a7c6dc9d

See https://gitlab.freedesktop.org/slirp/libslirp/-/issues/35 for more details.

This fixes issues such as https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237441

### What did you expect to happen?

Downloads work correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install qemu && <run my vm>
Inside VM: `fetch http://pkg.freebsd.org/FreeBSD:13:aarch64/latest/All/pkg-1.16.2.txz`
Results in `fetch: pkg-1.16.2.txz appears to be truncated: 7822207/7822208 bytes`
```

**Comment by SMillerDev** [comment]
> Could homebrew apply this patch to the QEMU package? https://gitlab.freedesktop.org/slirp/libslirp/-/commit/7271345efe182199acaeae602cb78a94a7c6dc9d

Yes, https://docs.brew.sh/Updating-Software-in-Homebrew explains how.

**Comment by carlocab** [comment]
Are you on ARM or Intel? If you're on ARM, then there are many things broken about the qemu formula. It just isn't supported upstream on the current stable version yet.

**Comment by jrtc27** [comment]
> Are you on ARM or Intel? If you're on ARM, then there are many things broken about the qemu formula. It just isn't supported upstream on the current stable version yet.

Intel; this has been broken for years.

**Comment by lexicol** [comment]
@arichardson Thanks for reporting! Hopefully this should be fixed by https://github.com/Homebrew/homebrew-core/pull/73618, which has just been merged. Please run `brew update` and `brew upgrade qemu` and check if the issue is still there.

**Comment by SeekingMeaning** [comment]
@arichardson Thanks for reporting! Hopefully this should be fixed by https://github.com/Homebrew/homebrew-core/pull/73618, which has just been merged. Please run `brew update` and `brew upgrade qemu` and check if the issue is still there.

**Comment by arichardson** [comment]
@SeekingMeaning thanks for the quick fix! I can confirm that it works as expected now.
