### ISSUE TITLE
mysql's test suite is huge

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew-core#7354]
Including the mysql-test folder nearly doubles the footprint of the installed distribution:

```
tim@rocketman:.virtualenvs$ du -hs $(brew --prefix mysql)/*  # (sorted and truncated for display)
239M	/usr/local/opt/mysql/mysql-test
181M	/usr/local/opt/mysql/bin
 42M	/usr/local/opt/mysql/lib
1.2M	/usr/local/opt/mysql/include
4.8M	/usr/local/opt/mysql/scripts
4.8M	/usr/local/opt/mysql/share
```

I propose to move the "proper" test into `install` and do a simpler smoke test in `test`.

I don't have time to work on this but it seems like a good opportunity for a newer contributor; please close if this is annoying.

**Comment by xylix** [comment]
Well,  the [mysql formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mysql.rb) enables unit tests by default. Could someone give some insight why is it so?

**Comment by tdsmith** [comment]
Nominally, the unit tests in `install` are actually disabled by default; I don't know if those are intended to be different from whatever's in `mysql-test`.
