### ISSUE TITLE
Consider removing Xcode requirement for `root` formula

### ISSUE THREAD

**Issue by wickles** [Homebrew/homebrew-core#73947]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> % brew config
HOMEBREW_VERSION: 3.0.9-23-g04d1142
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 04d11423b442ff87485dda03fc59c720f4a604c8
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0295b0d8fddd5147e527de0fb5fcc7c94159dce3
Core tap last commit: 12 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.zonYmET1lo/org.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

> % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  archivemount

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/pspdev/bin/psp-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt
  glew

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am trying to install `root` as a bottle without a full Xcode installation. I have the Xcode command line tools installed which works well enough for every other formula. But the `root` formula checks for a full installation and aborts if not found. I could not find other instances of formulae requiring a full Xcode installation. 

### What happened (include all command output)?

The formula will not install because "the bottle hardcodes locations inside Xcode.app". 

```
> % brew install root
Error: root: the bottle hardcodes locations inside Xcode.app
You can try to install from source with:
  brew install --build-from-source root
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

### What did you expect to happen?

I am not sure when this requirement was added but it does not seem to be necessary anymore. I was able to bypass the requirement using the `--force-bottle` argument. 

```
> % brew install --force-bottle root
==> Downloading https://homebrew.bintray.com/bottles/root-6.22.08.big_sur.bottle.tar.gz
Already downloaded: /Users/alex/Library/Caches/Homebrew/downloads/6f71c0e5fb3f59797ebf715d30f126c9f9de2cb2db32ca3c458e510ff1642a84--root-6.22.08.big_sur.bottle.tar.gz
==> Pouring root-6.22.08.big_sur.bottle.tar.gz
Warning: root dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
==> Caveats
As of ROOT 6.22, you should not need the thisroot scripts; but if you
depend on the custom variables set by them, you can still run them:

For bash users:
  . /usr/local/bin/thisroot.sh
For zsh users:
  pushd /usr/local >/dev/null; . bin/thisroot.sh; popd >/dev/null
For csh/tcsh users:
  source /usr/local/bin/thisroot.csh
For fish users:
  . /usr/local/bin/thisroot.fish

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/root
==> Summary
🍺  /usr/local/Cellar/root/6.22.08: 5,881 files, 668.2MB
```

I played around with the demo program included with the software to check that it was not seriously broken. 

```
> % root
   ------------------------------------------------------------------
  | Welcome to ROOT 6.22/08                        https://root.cern |
  | (c) 1995-2020, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for macosx64 on Mar 10 2021, 14:20:04                      |
  | From tags/v6-22-08@v6-22-08                                      |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

root [0] .demo
!!! gui stuff happens here and works as expected !!!
root [1] .q

Taking a break from ROOT? Hope to see you back!
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
> % brew install root
Error: root: the bottle hardcodes locations inside Xcode.app
You can try to install from source with:
  brew install --build-from-source root
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

**Comment by mitchblank** [comment]
For reference, this restriction was added to fix #30726 at which time homebrew was installing root 6.14.04

Now root is up to 6.22.08 -- is it possible that the original issue hb was working around has been fixed upstream?

**Comment by mitchblank** [comment]
> is it possible that the original issue hb was working around has been fixed upstream?

There do seem to be at least some changes wrt OS/X CLT support.  For instance see https://github.com/root-project/root/commit/17c189045764b4444683b01524430f614eeff49a

cc @Axel-Naumann -- do you think the requirement for building against non-CLT Xcode is something that should be dropped now?

**Comment by Axel-Naumann** [comment]
Thanks for pinging me! I wasn't aware of https://github.com/Homebrew/homebrew-core/issues/30726 - it might have been good to ping us on this one, too, as this looks like an issue that should get fixed on our side.

Given that I was not aware of this issue I also don't expect this to be fixed. But I don't understand the issue yet - ROOT / cling try at runtime to find compiler and include directories, and they are generally pretty open on what they find. We don't require to use either CLT or Xcode, and we do not see this for our builds. Our binaries are done with CLT; I expect most users to have Xcode installed.

Conclusion: hard to answer for me, as I don't know where this requirement came from in the first place, and the linked bug isn't enough info for me to understand that. If you see issues from lifting the requirement please notify us!

**Comment by carlocab** [comment]
It might be fine to lift the requirement now. We can put it back if it still causes other people issues. @wickles, do you want to open a PR for this?

**Comment by Bo98** [comment]
I think the problem might have been from `cling` having an absolute path to the Xcode compiler. This is no longer the case AFAIK (probably fixed by our `-DCLING_CXX_PATH=clang++`).

There is still an absolute path to the standard C++ headers, but I think it might not even be used at runtime when `CLING_CXX_PATH` is present and working.

**Comment by wickles** [comment]
Running the `brew test` method it looks like it should be fine. I will open a PR. 
```
> % brew test root
==> Testing root
==> /usr/local/Cellar/root/6.22.08/bin/root -b -l -q -e gSystem->LoadAllLibraries(); 0
==> root -l -b -n -q test.C
==> /bin/bash test_compile.bash
==> /usr/local/opt/python@3.9/bin/python3 -c import ROOT; ROOT.gSystem.LoadAllLibraries()
```

**Comment by carlocab** [comment]
Thanks for the report and the PR, @wickles.
