### ISSUE TITLE
mutt 1.6.0 fails to apply the ignore-thread patch

### ISSUE THREAD

**Issue by lasombra** [Homebrew/homebrew-core#74]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?

### Bug reports:

When trying to install the new mutt 1.6.0, using brew install --with-ignore-thread-patch mutt, the build fails while applying the patch.

`» brew gist-logs mutt`
`Error: No logs.`

```
» brew install --with-ignore-thread-patch mutt
==> Downloading https://bitbucket.org/mutt/mutt/downloads/mutt-1.6.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/mutt-1.6.0.tar.gz
==> Downloading https://gist.githubusercontent.com/mistydemeo/5522742/raw/1439cc157ab673dc8061784829eea267cd736624/ignore-thread-1.5.21.patch
Already downloaded: /Library/Caches/Homebrew/mutt--patch-7290e2a5ac12cbf89d615efa38c1ada3b454cb642ecaf520c26e47e7a1c926be.patch
==> Patching
==> Applying ignore-thread-1.5.21.patch
patching file OPS
patching file copy.c
Hunk #1 succeeded at 394 (offset 1 line).
Hunk #2 succeeded at 405 (offset 1 line).
patching file curs_main.c
Hunk #1 succeeded at 397 (offset 76 lines).
Hunk #2 succeeded at 410 (offset 76 lines).
Hunk #3 succeeded at 424 (offset 76 lines).
Hunk #4 succeeded at 499 (offset 76 lines).
Hunk #5 succeeded at 1273 (offset 81 lines).
Hunk #6 succeeded at 1574 (offset 82 lines).
Hunk #7 succeeded at 1844 (offset 96 lines).
Hunk #8 succeeded at 1903 (offset 96 lines).
Hunk #9 succeeded at 1934 (offset 96 lines).
patching file flags.c
patching file functions.h
patching file hdrline.c
Hunk #1 succeeded at 254 (offset 2 lines).
Hunk #2 succeeded at 594 (offset 18 lines).
Hunk #3 succeeded at 676 (offset 18 lines).
Hunk #4 succeeded at 752 (offset 18 lines).
patching file imap/imap.c
Hunk #1 succeeded at 892 (offset -5 lines).
Hunk #2 succeeded at 1037 (offset -5 lines).
Hunk #3 succeeded at 1071 (offset -5 lines).
Hunk #4 succeeded at 1091 (offset -5 lines).
Hunk #5 FAILED at 1268.
1 out of 5 hunks FAILED -- saving rejects to file imap/imap.c.rej
patching file imap/message.c
Hunk #2 succeeded at 309 (offset 3 lines).
Hunk #3 succeeded at 1066 (offset 12 lines).
Hunk #4 succeeded at 1236 (offset 12 lines).
Hunk #5 succeeded at 1251 (offset 12 lines).
patching file imap/message.h
patching file mailbox.h
Hunk #1 succeeded at 28 with fuzz 2.
patching file mbox.c
Hunk #1 succeeded at 1223 (offset 3 lines).
patching file mutt.h
Hunk #1 succeeded at 163 (offset -5 lines).
Hunk #2 succeeded at 191 (offset -5 lines).
Hunk #3 succeeded at 756 (offset 13 lines).
patching file pager.c
Hunk #1 succeeded at 2303 (offset 15 lines).
patching file parse.c
Hunk #1 succeeded at 1257 (offset 13 lines).
patching file protos.h
Hunk #1 succeeded at 63 (offset 1 line).
patching file sort.c
patching file thread.c
Hunk #2 succeeded at 1033 (offset -1 lines).
Hunk #3 succeeded at 1244 (offset -1 lines).
Hunk #4 succeeded at 1262 (offset -1 lines).
Hunk #5 succeeded at 1302 (offset -1 lines).
Hunk #6 succeeded at 1357 (offset -1 lines).
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1 -i /private/tmp/mutt--patch20160405-22423-108txf6/ignore-thread-1.5.21.patch
```

**Comment by telemachus** [comment]
I just came to report the same thing. I checked, and I don't yet see an updated ignore-thread patch for mutt 1.6: https://dev.mutt.org/trac/wiki/PatchList. I know the mutt patches have long been a sore-spot for Homebrew. Would it make sense to pull the patch until it's updated?

**Comment by mikemcquaid** [comment]
> Would it make sense to pull the patch until it's updated?

Yup (and even after it's updated, unfortunately).

**Comment by lasombra** [comment]
Maybe there's need for a mutt-kz formula,
https://github.com/karelzak/mutt-kz.

**Comment by telemachus** [comment]
> Yup (and even after it's updated, unfortunately).

To clarify, does this mean you want to pull this patch forever? If so, do you want also to pull all patches from mutt?

I understand if that's how you want to go, but it will almost certainly lead to a large number of people giving up the mainline version of mutt. Maybe that's for the best, but I think it would be a shame. Unfortunately, mutt's development style just doesn't fit Homebrew's preferred model. That is, upstream is not going to change much, I don't think.

**Comment by chdiza** [comment]
There just needs to be a mutt tap (not a HB official one, of course).

**Comment by dunn** [comment]
A few people listed theirs in https://github.com/Homebrew/legacy-homebrew/pull/43647; I don't think any are widely used though.

**Comment by telemachus** [comment]
For historical purposes, there was also discussion in several earlier threads. Here's a few I recall that may have useful information or ideas:

1. https://github.com/Homebrew/legacy-homebrew/pull/20516
1. https://github.com/Homebrew/legacy-homebrew/issues/20588
1. https://github.com/Homebrew/legacy-homebrew/pull/20677

**Comment by dunn** [comment]
#80.

**Comment by michaelpq** [comment]
(guy who submitted the change to upgrade to 1.6.0 here, and I just use and get used to only mutt-core to avoid actually issues with such patches and keep up with the latest versions).

Personally, if there are patches available and users willing to use them because they think they are more useful than upstream core set of features, there are no reasons not to add them in the future if they work. Now, I don't think that those patches should be an obstacle for upgrades, or we increase the risk to be stuck with old versions of mutt forever, because not only would this package rely on the availability of the core maintainer of mutt, but also on the person who is generating those alpha patches. Integrating things directly to upstream may make more sense, now I am sure that there are valid reasons why mutt core code is being conservative and does not integrate them.

**Comment by mikemcquaid** [comment]
> Integrating things directly to upstream may make more sense, now I am sure that there are valid reasons why mutt core code is being conservative and does not integrate them.

Agreed 👍
