### ISSUE TITLE
Shellcheck not available for mac m1

### ISSUE THREAD

**Issue by ameeno** [Homebrew/homebrew-core#74109]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am trying to install shellcheck for mac m1.

I have to use my intel/rosetta version of homebrew to make it work.

ALL my other homebrew formulae are mac m1 versions this is the last app that relies on rosetta.

Could you make shellcheck work on arm please?

### What happened (include all command output)?

shellcheck not found on homebrew

### What did you expect to happen?

shellcheck to install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install shellcheck 
(on mac m1 terminal with homebrew installed in /opt/homebrew)
```

**Comment by SMillerDev** [comment]
> Could you make shellcheck work on arm please?

No, we are not the writers of the software we package. Please contact the upstream developers.

**Comment by carlocab** [comment]
`shellcheck` is built using `ghc` and `cabal-install` (which also depends on `ghc`). `ghc` doesn't work on ARM yet, which is a big part of why `shellcheck` doesn't have a native ARM build.

The `ghc` developers are working on getting `ghc` working on ARM. Maybe you can help them out.
