### ISSUE TITLE
missing developer files for NUT

### ISSUE THREAD

**Issue by scontini76** [Homebrew/homebrew-core#74122]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n.a.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I'm using NUT package, I wish to see developer files included (header files and so on)

### What happened (include all command output)?

Installing NUT with:

brew install nut

binaries, man pages and libraries are installed, but header files are missing.

### What did you expect to happen?

I wish to see the package with all the developer stuff.

Looking at the NUT configure script file, I think it's just replacing the --with-nodev with --with-dev to the configure calls inside the formula. I don't know why someone chooses to prevent header files to a package that is used as a library too.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
n.a.
```

**Comment by carlocab** [comment]
This issue tracker is for bugs, not feature requests. If you'd like to make a change to a formula, please open a pull request. Thanks!
