### ISSUE TITLE
brew install pyqt5 (only...)

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-core#7418]
_From @fabioca on November 27, 2016 16:20_

Due to a messy organization of my MAC (yosemite), I was cleaning up and reinstall from scratch homebrew and  a bit of packages . I noticed that the 'brew install pyqt' is not anymore active and only pyqt5 is there. that would be OK, but since I need also pyqt4, I was wondering how to load from homebrew. 
(I am only a computer user, please, give me infos like for a grandma!). Thank you. 

_Copied from original issue: Homebrew/legacy-homebrew#50699_

**Comment by ilovezfs** [comment]
You can use https://github.com/cartr/homebrew-qt4.

```
brew tap cartr/qt4
```
