### ISSUE TITLE
Brew service starting with error status 

### ISSUE THREAD

**Issue by harishankarsivaji** [Homebrew/homebrew-core#74235]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ad2564c5f1ddf6f16f707f2861556b80546713c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2ecae74af646f78fc3a0b10c103d64acae4718d
Core tap last commit: 55 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4


brew doctor
Your system is ready to brew.
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Recently updated and upgraded my brew list.
Trying to start mongo-community@4.4 but started with error status. Same with postgresql.
When trying to start mongo shell, I got a SocketException and refused to start connection.

### What happened (include all command output)?

brew services list:
Name              Status  User              Plist
dbus              stopped
mongodb-community error   harishankarsivaji /Users/harishankarsivaji/Library/LaunchAgents/homebrew.mxcl.mongodb-community.plist
nginx             stopped
postgresql        stopped
rabbitmq          stopped
unbound           unknown root              /Library/LaunchDaemons/homebrew.mxcl.unbound.plist

### What did you expect to happen?

To start the services successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
When I checked the mongo.log and found, 
...
{"t":{"$date":"2021-03-30T18:25:52.640+01:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=3584M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
{"t":{"$date":"2021-03-30T18:25:53.152+01:00"},"s":"F",  "c":"STORAGE",  "id":4671205, "ctx":"initandlisten","msg":"This version of MongoDB is too recent to start up on the existing data files. Try MongoDB 4.2 or earlier."}
{"t":{"$date":"2021-03-30T18:25:53.153+01:00"},"s":"F",  "c":"-",        "id":23089,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":4671205,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":1088}}
{"t":{"$date":"2021-03-30T18:25:53.153+01:00"},"s":"F",  "c":"-",        "id":23090,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
...

after installing old version it started. But when I start other services I get the error status.



Name                  Status  User              Plist
dbus                  stopped
mongodb-community@4.2 started harishankarsivaji /Users/harishankarsivaji/Library/LaunchAgents/homebrew.mxcl.mongodb-community@4.2.plist
nginx                 error   harishankarsivaji /Users/harishankarsivaji/Library/LaunchAgents/homebrew.mxcl.nginx.plist
postgresql            error   harishankarsivaji /Users/harishankarsivaji/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
rabbitmq              stopped
unbound               unknown root              /Library/LaunchDaemons/homebrew.mxcl.unbound.plist
```

**Comment by gromgit** [comment]
What do the `postgresql` and `nginx` logs say?

**Comment by harishankarsivaji** [comment]
> What do the `postgresql` and `nginx` logs say?

021-03-31 04:25:27.067 BST [25972] FATAL:  database files are incompatible with server
2021-03-31 04:25:27.067 BST [25972] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 13.2

**Comment by gromgit** [comment]
When you upgraded `postgresql`, you would've see the following at the end of the process:
```
To migrate existing data from a previous major version of PostgreSQL run:
  brew postgresql-upgrade-database
```
However, if you've installed various PG extensions (especially `postgis`), you're probably better off doing a manual DB upgrade. Read the docs for the extensions you have, as well as the `pg_upgrade` tools that would do most of the heavy lifting: https://www.postgresql.org/docs/13/pgupgrade.html

**Comment by harishankarsivaji** [comment]
@gromgit Thank you. Postgres is working fine now.
Upgrading mongodb to 4.3 is the issue. I don't think its a launchctl problem.

**Comment by carlocab** [comment]
Are you still having any problems with formulae in homebrew/core? mongodb/mongo-community is from an external tap, so we're not really able to help you much with that.

**Comment by harishankarsivaji** [comment]
Ok. Thank you. I will rise a ticket with mongodb about this.
Closing this issue now.
