### ISSUE TITLE
Migrate Bintray `url`s somewhere else

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-core#74335]
After May 1st all links to Bintray will be broken. Our `homebrew/bottles` will be migrated in time and probably our `homebrew/mirror`s but there's a lot of other packages using Bintray that we'll need to find other hosts for:

Using `homebrew/mirror`:
```console
$ rg 'url ".+bintray' | sort | grep homebrew/homebrew
Formula/afsctool.rb:  url "https://dl.bintray.com/homebrew/mirror/afsctool-1.6.4.zip"
Formula/berkeley-db.rb:  url "https://dl.bintray.com/homebrew/mirror/berkeley-db-18.1.40.tar.gz"
Formula/cabocha.rb:  url "https://dl.bintray.com/homebrew/mirror/cabocha-0.69.tar.bz2"
Formula/caffe.rb:    url "https://bintray.com/homebrew/mirror/download_file?file_path=bvlc_reference_caffenet.caffemodel"
Formula/dpkg.rb:  url "https://dl.bintray.com/homebrew/mirror/dpkg-1.20.7.1.tar.xz"
Formula/gcore.rb:  url "https://dl.bintray.com/homebrew/mirror/gcore-1.3.tar.gz"
Formula/imagemagick.rb:  url "https://dl.bintray.com/homebrew/mirror/ImageMagick-7.0.11-5.tar.xz"
Formula/imagemagick@6.rb:  url "https://dl.bintray.com/homebrew/mirror/ImageMagick-6.9.12-5.tar.xz"
Formula/libelf.rb:  url "https://dl.bintray.com/homebrew/mirror/libelf-0.8.13.tar.gz" # using this url since original source is offline ( https://github.com/Homebrew/homebrew-core/pull/54887 )
Formula/lzop.rb:  url "https://dl.bintray.com/homebrew/mirror/lzop-1.04.tar.gz"
Formula/pdflib-lite.rb:  url "https://dl.bintray.com/homebrew/mirror/pdflib-lite--7.0.5p3.tar.xz"
Formula/qemu.rb:    url "https://dl.bintray.com/homebrew/mirror/FD12FLOPPY.zip"
Formula/snow.rb:  url "https://dl.bintray.com/homebrew/mirror/snow-20130616.tar.gz"
```

Using something else:
```console
$ rg 'url ".+bintray' | sort | grep -v homebrew/homebrew
Formula/artifactory.rb:    url "https://dl.bintray.com/jfrog/artifactory/"
Formula/artifactory.rb:  url "https://dl.bintray.com/jfrog/artifactory/jfrog-artifactory-oss-6.23.13.zip"
Formula/boost-bcp.rb:  url "https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2"
Formula/boost-mpi.rb:  url "https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2"
Formula/boost-python.rb:  url "https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2"
Formula/boost-python3.rb:  url "https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2"
Formula/boost.rb:  url "https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2"
Formula/denominator.rb:  url "https://bintray.com/artifact/download/netflixoss/maven/com/netflix/denominator/denominator-cli/4.7.1/denominator-cli-4.7.1-fat.jar"
Formula/embulk.rb:  url "https://bintray.com/artifact/download/embulk/maven/embulk-0.9.23.jar"
Formula/golo.rb:  url "https://bintray.com/artifact/download/golo-lang/downloads/golo-3.3.0.zip"
Formula/griffon.rb:  url "https://dl.bintray.com/content/aalmiray/Griffon/griffon-1.5.0-bin.tgz"
Formula/groovy.rb:    url "https://dl.bintray.com/groovy/maven/"
Formula/groovy.rb:  url "https://dl.bintray.com/groovy/maven/apache-groovy-binary-3.0.7.zip"
Formula/groovysdk.rb:    url "https://dl.bintray.com/groovy/maven/"
Formula/groovysdk.rb:  url "https://dl.bintray.com/groovy/maven/apache-groovy-sdk-3.0.7.zip"
Formula/hyperkit.rb:    url "https://dl.bintray.com/markeissler/homebrew/hyperkit-kernel/tinycorelinux_8.x.tar.gz"
Formula/jbake.rb:  url "https://dl.bintray.com/jbake/binary/jbake-2.6.5-bin.zip"
Formula/kaitai-struct-compiler.rb:  url "https://bintray.com/artifact/download/kaitai-io/universal/0.9/kaitai-struct-compiler-0.9.zip"
Formula/percona-server.rb:    url "https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
Formula/percona-xtrabackup.rb:    url "https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2"
Formula/pushpin.rb:  url "https://dl.bintray.com/fanout/source/pushpin-1.31.0.tar.bz2"
Formula/quantlib.rb:  url "https://dl.bintray.com/quantlib/releases/QuantLib-1.21.tar.gz"
Formula/savana.rb:  url "https://bintray.com/artifact/download/bintray/jcenter/org/codehaus/savana/1.2/savana-1.2-install.tar.gz"
Formula/snzip.rb:  url "https://bintray.com/artifact/download/kubo/generic/snzip-1.0.4.tar.gz"
Formula/swagger2markup-cli.rb:  url "https://jcenter.bintray.com/io/github/swagger2markup/swagger2markup-cli/1.3.3/swagger2markup-cli-1.3.3.jar"
Formula/zurl.rb:  url "https://dl.bintray.com/fanout/source/zurl-1.11.0.tar.bz2"
```

CC @Homebrew/core for help with this.

**Comment by MikeMcQuaid** [comment]
> Our `homebrew/bottles` will be migrated in time and probably our `homebrew/mirror`s

Note, given this: I think it'd be good to migrate all `url`s using `homebrew/mirror` to something else for now (where possible) and we can keep our `mirror`s.

**Comment by SMillerDev** [comment]
Artifactory does not provide a non-artifactory DL link.

**Comment by SMillerDev** [comment]
I'm going back to the work people pay me for, anything from `groovy` and onward is up for grabs.

**Comment by Bo98** [comment]
> Artifactory does not provide a non-artifactory DL link.

Artifactory isn't sunsetting and, as far as I gather, Artifactory repositories that are linked with Bintray are unaffected. We can keep an eye on it however as I imagine they'll update the the link in time if it is in fact going to change.

**Comment by Bo98** [comment]
Looking through some, it's worth nothing that not everyone has migrated and that's ok - there's still a bit of time. Upstream issues can be opened if there's no clear indication of what the plans are.

**Comment by arximboldi** [comment]
Been hit by this today for `qt` and `ccache`...
https://status.bintray.com/

![Screenshot from 2021-04-12 16-36-25](https://user-images.githubusercontent.com/4521138/114412292-3ffb1880-9bad-11eb-8691-ea3d5b873c27.png)

**Comment by Bo98** [comment]
Are you referring to bottle downloads? Homebrew 3.1.0 has been released which migrates away from Bintray.

**Comment by arximboldi** [comment]
Aha! Yeah that was it. It was happening on Github Actions... I'll figure how to upgrade Homebrew there. Thanks a lot for the quick response!

**Comment by MikeMcQuaid** [comment]
> I'll figure how to upgrade Homebrew there

`brew update`.

**Comment by MalinnaLeach** [comment]
Hello!  I think this issue has become a problem for us.  We run "brew bundle" as part of our build, but we are getting 404 errors on a number of our dependencies that are trying to pull from bintray urls, eg. `https://homebrew.bintray.com/openssl%401.1-1.1.1k.catalina.bottle.tar.gz`.

For us wget, gnupg, gnupg2, gpg, gpg2 and coreutils are all failing.  Any advice would be appreciated!

**Comment by carlocab** [comment]
Do `brew update` before anything else.

**Comment by SMillerDev** [comment]
Update brew so it pulls from github packages.

**Comment by MalinnaLeach** [comment]
> Do `brew update` before anything else.

The command "brew bundle" automatically updates, unless something has changed?

**Comment by MalinnaLeach** [comment]
I can see from our build that homebrew updated: `Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and adoptopenjdk/openjdk).`

**Comment by carlocab** [comment]
There's a small bug: #11126 You'll need to do it manually for now.

**Comment by MalinnaLeach** [comment]
Thanks, but this links to an issue that was merged in 2017?  These failures only just started happening for us this morning, apologies, I'm a bit confused..


> There's a small bug: #11126 You'll need to do it manually for now.

**Comment by carlocab** [comment]
Forgot that this was a different repo from the PR I wanted to link. Fixed it a few minutes ago. Just please do `brew update` first.

**Comment by MalinnaLeach** [comment]
> Forgot that this was a different repo from the PR I wanted to link. Fixed it a few minutes ago. Just please do `brew update` first.

Great - this is working again - thank you!

**Comment by Bo98** [comment]
I'm doing a load of migrations in #76334.

There's a couple I'm discussing with upstream about. I'll post a proper list here this evening.

I've ignored `griffon` and `gcore` since they are disabled and I unfortunately could not find mirrors for them.

We need to figure out where to host [this](https://github.com/Homebrew/homebrew-core/blob/7beae5ab57c65249403699b2b0700fbccf14e6cb/Formula/hyperkit.rb#L22) since it appears to be a resource created just for our tests.

**Comment by MikeMcQuaid** [comment]
Thanks @bo98!

> We need to figure out where to host [this](https://github.com/Homebrew/homebrew-core/blob/7beae5ab57c65249403699b2b0700fbccf14e6cb/Formula/hyperkit.rb#L22) since it appears to be a resource created just for our tests.

Uploaded it as a GitHub issue comment attachment, lol (and these stick around indefinitely as they are essentially just S3): https://github.com/Homebrew/homebrew-core/files/6405545/tinycorelinux_8.x.tar.gz

**Comment by Bo98** [comment]
Sneaky! #76337

**Comment by carlocab** [comment]
> Boost is handled by #75459 but I may open a PR to update the 1.75 links if I don't find a quick fix for the 1.76 blockers.

I wouldn't worry too much about Boost. They're staying with JFrog and still posted Bintray links for 1.76, so I suspect any Bintray links for Boost will still resolve correctly.

**Comment by carlocab** [comment]
Boost formulae: #76463

**Comment by Bo98** [comment]
Final update:

```
$ grep -R "bintray\.com" .
./gcore.rb:  url "https://dl.bintray.com/homebrew/mirror/gcore-1.3.tar.gz"
./griffon.rb:  url "https://dl.bintray.com/content/aalmiray/Griffon/griffon-1.5.0-bin.tgz"
```

`gcore` will remain online until 4th July. The formula is now disabled however. Presumably because it didn't build on Big Sur?

`griffon` is an old version and was disabled a few weeks ago as a result.

**Comment by MikeMcQuaid** [comment]
Great work, thanks @bo98!

**Comment by MikeMcQuaid** [comment]
(and everyone else like @carlocab, too!)
