### ISSUE TITLE
hackrf formula should also install firmware-bin directory

### ISSUE THREAD

**Issue by rfc6919** [Homebrew/homebrew-core#74398]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

: 3.0.10-88-g2bd0b6e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2bd0b6ee614ea31c815206e953aa46de19a2e144
Last commit: 41 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bd512c4c3ed6b66bb1356d9cd02d49acfa85607f
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11

brew doctor, warning is not relevant to this issue:

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  archivemount
  polipo
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

upgrade hackrf firmware as required for the new 2021.03.1 release, per release notes at https://github.com/mossmann/hackrf/releases/tag/v2021.03.1

### What happened (include all command output)?

required device firmware (provided in upstream release bundle in the firmware-bin/ directory) wasn't included in the homebrew install, so I needed to download the upstream release myself

### What did you expect to happen?

the required device firmware would be included in the files installed by the formula

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
install hackrf
find /usr/local/Cellar/hackrf/2021.03.1 -name hackrf_one_usb.bin
=> no firmware found
```

**Comment by carlocab** [comment]
The `hackrf` formula doesn't do anything strange: it just calls `cmake` to generate `Makefile`s then calls `make install`.

Why isn't the `firmware-bin` directory installed by doing this?

**Comment by rfc6919** [comment]
The formula does a cd into the `host` directory and runs `make install`, but the firmware is in the `firmware-bin` directory in the root of the distribution archive next to `host`. `make install` just builds and installs the host tools.

> Why isn't the `firmware-bin` directory installed by doing this?

I guess that's a question for upstream?

I'm just suggesting that the `install` method, as well as running `make install` in `host`, also copy `firmware-bin` from the root of the release archive into eg. `.../share/hackrf/firmware-bin`

**Comment by carlocab** [comment]
Yes, I understand what you're suggesting. I'm just hesitant to deviate from the upstream-provided [build instructions](https://github.com/mossmann/hackrf/wiki/Operating-System-Tips#building-from-source), which is exactly what the formula does.

Presumably, there is a reason they don't include the step you suggest there, and I don't want to presume to know better than upstream about how to ship their software.

Still, you may wish to open a PR that does what you suggest: perhaps another maintainer disagrees with me.

**Comment by rfc6919** [comment]
Fair enough. I've raised the question with upstream to see what @mossmann says.
