### ISSUE TITLE
Invalid char `\x03' in expression

### ISSUE THREAD

**Issue by satya77** [Homebrew/homebrew-core#745]
I try running this command : 
`brew install --upgrade https://s3-us-west-1.amazonaws.com/dato-public-share/GraphLab_Create-1.7.1.94-cp27-none-win_amd64.whl`
but I get the following error : 
```
Error: /Library/Caches/Homebrew/Formula/GraphLab_Create-1.7.1.94-cp27-none-win_amd64.whl:1: Invalid char `\x03' in expression
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:38:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:87:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:142:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:78:in `klass'
/usr/local/Library/Homebrew/formulary.rb:74:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:211:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:95:in `install'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by UniqMartin** [comment]
What are you trying to do here? You cannot pass arbitrary URLs to `brew install`. This has to be either a formula name or an URL pointing to a Homebrew formula file (but the latter is rarely used). Note also that `brew install` doesn't have a `--upgrade` option.

**Comment by satya77** [comment]
Thank you for you response @UniqMartin. 
Im trying to run this command : pip install --upgrade https://s3-us-west-1.amazonaws.com/dato-public-share/GraphLab_Create-1.7.1.94-cp27-none-win_amd64.whl
but as I'm using brew I used brew install .

**Comment by UniqMartin** [comment]
I see. You cannot use `brew` in place of `pip` as those are two different package managers and work quite differently. Assuming this can be closed then?

**Comment by satya77** [comment]
ok thanks
