### ISSUE TITLE
OpenCV3.1 install failed on macOS 10.12 with command brew install opencv3

### ISSUE THREAD

**Issue by John443** [Homebrew/homebrew-core#7451]
## Error message:

Last 15 lines from /Users/John443/Library/Logs/Homebrew/opencv3/02.make:
[ 66%] Built target opencv_shape
/tmp/opencv3-20161201-16559-198zkh1/opencv-3.1.0/modules/videoio/src/cap_qtkit.mm:46:9: fatal error: 'QTKit/QTKit.h' file not found
#import <QTKit/QTKit.h>
        ^
1 error generated.
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/src/cap_qtkit.mm.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 66%] Linking CXX shared library ../../lib/libopencv_photo.dylib
cd /tmp/opencv3-20161201-16559-198zkh1/opencv-3.1.0/macbuild/modules/photo && /usr/local/Cellar/cmake/3.7.1/bin/cmake -E cmake_link_script CMakeFiles/opencv_photo.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++     -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -mavx -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 3.1.0 -current_version 3.1.0 -o ../../lib/libopencv_photo.3.1.0.dylib -install_name /tmp/opencv3-20161201-16559-198zkh1/opencv-3.1.0/macbuild/lib/libopencv_photo.3.1.dylib CMakeFiles/opencv_photo.dir/src/align.cpp.o CMakeFiles/opencv_photo.dir/src/calibrate.cpp.o CMakeFiles/opencv_photo.dir/src/contrast_preserve.cpp.o CMakeFiles/opencv_photo.dir/src/denoise_tvl1.cpp.o CMakeFiles/opencv_photo.dir/src/denoising.cpp.o CMakeFiles/opencv_photo.dir/src/denoising.cuda.cpp.o CMakeFiles/opencv_photo.dir/src/hdr_common.cpp.o CMakeFiles/opencv_photo.dir/src/inpaint.cpp.o CMakeFiles/opencv_photo.dir/src/merge.cpp.o CMakeFiles/opencv_photo.dir/src/npr.cpp.o CMakeFiles/opencv_photo.dir/src/seamless_cloning.cpp.o CMakeFiles/opencv_photo.dir/src/seamless_cloning_impl.cpp.o CMakeFiles/opencv_photo.dir/src/tonemap.cpp.o CMakeFiles/opencv_photo.dir/opencl_kernels_photo.cpp.o ../../lib/libopencv_imgproc.3.1.0.dylib ../../../3rdparty/ippicv/unpack/ippicv_osx/lib/libippicv.a ../../lib/libopencv_core.3.1.0.dylib 
cd /tmp/opencv3-20161201-16559-198zkh1/opencv-3.1.0/macbuild/modules/photo && /usr/local/Cellar/cmake/3.7.1/bin/cmake -E cmake_symlink_library ../../lib/libopencv_photo.3.1.0.dylib ../../lib/libopencv_photo.3.1.dylib ../../lib/libopencv_photo.dylib
[ 66%] Built target opencv_photo
make: *** [all] Error 2

**Comment by MikeMcQuaid** [comment]
Report this to homebrew/science like the error instructed you to.
