### ISSUE TITLE
influxdb@2 recipe broken

### ISSUE THREAD

**Issue by ruurd** [Homebrew/homebrew-core#74532]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
± brew config
HOMEBREW_VERSION: 3.0.10-224-g698c490
ORIGIN: https://github.com/Homebrew/brew
HEAD: 698c49067dbff69a44b13ab87c828d79a66dc543
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: aa4e0aadb7723893b984d7dfa57266d9231c15ba
Core tap last commit: 27 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.31.1 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Install and run influxdb version 2.0.4
It /used/ to have a running launchctl configuration but that disappeared.

### What happened (include all command output)?

/opt/homebrew/etc/influxdb.conf disappeared. influxdb could not access existing database. inspection of recipe shows the plist needed for the launchctl entry has been removed from the recipe with a bunch of other stuff

### What did you expect to happen?

To still have a working influxdb system

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Update to latest influxdb version, observe breakage when trying to start with brew service
```

**Comment by SMillerDev** [comment]
Is there anything here that isn't a feature request to add back the plist? Because we don't accept feature requests as issues.

**Comment by ruurd** [comment]
This is more a request to put back the feature that is elided. This is an unworkable situation. It used to function properly and POOF it malfunctions.

**Comment by SMillerDev** [comment]
Please file a pull request for that.

**Comment by ruurd** [comment]
Heh. What happened to the rule 'if you break it you pay for it'?I'd say undo the PR that broke it in the first place. I'm not going to get into a PR war with others fighting over some misguided PR being accepted into homebrew-core. Let the person doing the PR fix his ^&*(

**Comment by carlocab** [comment]
And what makes you say opening a PR will get you into a "PR war"?

`/opt/homebrew/etc/influxdb.conf` disappeared because upstream got rid of their example `influxdb.conf`. This is where it used to come from:

https://github.com/Homebrew/homebrew-core/blob/892447280b85c1e353b5d5168c1519328db7ed12/Formula/influxdb.rb#L30

This file no longer exists in the upstream repo. How do you expect the formula to install a non-existent file?

Undoing the PR would be the same as rolling the version back to 1.8.4. There's no need to do that because you can install version 1.8.4 with `influxdb@1`.

Perhaps you ought to have a better understanding of the situation before casting aspersions on other people.

**Comment by ruurd** [comment]
Never mind. I see what happened. People foisted version 2 on us but could not be bothered to provide ample configuration. The file etc/config.sample.toml is gone from influx2. I conclude that this recipe is just broken and fails to properly tie into the Homebrew system.

@carlocab Next time wait with your PR until you're really done and don't surprise people with a broken system. This is very much below par. You should not have hijacked the influxdb recipe to push a new major version on unsuspecting people in a way that is not working the same as it did.

**Comment by SMillerDev** [comment]
> @carlocab Next time wait with your PR until you're really done and don't surprise people with a broken system. This is very much below par. You should not have hijacked the influxdb recipe to push a new major version on unsuspecting people in a way that is not working the same as it did.

Homebrew will always install the latest version of software, following the defaults set by upstream. If you want to complain about those defaults there is no need to violate the Homebrew [Code of Conduct](https://github.com/Homebrew/.github/blob/HEAD/CODE_OF_CONDUCT.md#code-of-conduct) you can go violate the one from InfluxDB.

**Comment by carlocab** [comment]
I did wait till I was done. It's not on me to check whether upstream includes breaking changes in version updates.

If you disagree with that, please use another package manager.
