### ISSUE TITLE
gettext: does not include emacs files anymore

### ISSUE THREAD

**Issue by petere** [Homebrew/homebrew-core#74546]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 0ad2564c5f1ddf6f16f707f2861556b80546713c
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 03135709c5f97fc6c4dc9caf0a556b2c20402595
Core tap last commit: 23 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacsclient -t
HOMEBREW_MAKE_JOBS: 16
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.2-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
```

```
Your system is ready to brew.
```
```


### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Use `po-mode` in Emacs. It used to be included in the `gettext` package.

### What happened (include all command output)?

`po-mode` was not installed.

### What did you expect to happen?

`po-mode` is supposed to be installed in

    /usr/local/Cellar/gettext/0.21/share/emacs/site-lisp/gettext

but that directory does not exist. (It used to be there in a previous computer.)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gettext
```
```

**Comment by petere** [comment]
Looking at the source code of gettext upstream, the emacs files are only installed if an `emacs` binary is found during the build. So adding a build dependency on emacs might fix this.

**Comment by iMichka** [comment]
I don't think we can add `emacs` as a dependency: `gettext` is pretty low-level and depends on nothing. On the other side emacs depends on a lot of stuff.

Besides that, emacs depends on `gettext` too, so this would introduce a cyclic dependency. There must be another way.

**Comment by MikeMcQuaid** [comment]
> I don't think we can add `emacs` as a dependency: `gettext` is pretty low-level and depends on nothing. On the other side emacs depends on a lot of stuff.
> 
> Besides that, emacs depends on `gettext` too, so this would introduce a cyclic dependency. There must be another way.

Agreed. We may be able to create a stub `emacs` binary that enables the build process to continue.

**Comment by petere** [comment]
I wonder how it worked before. AFAICT, the dependency on emacs for installing the elisp files has been in the upstream makefiles for some time. Perhaps something has changed in the Homebrew or macOS build environment.

In any case, I understand the circular and other dependency issues. In practice, it's just as easy to get po-mode from, say, MELPA. So just removing it from the Homebrew formula would be an acceptable solution. But then it should probably be explicit. For example, the formula file currently contains `--with-emacs`, so someone once made a point about this.
