### ISSUE TITLE
dnsmasq 2.76 not working on Mavericks

### ISSUE THREAD

**Issue by mstreuhofer** [Homebrew/homebrew-core#7456]
Proven to work as expected after manually downgrading `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/dnsmasq.rb`:

```
diff --git i/Formula/dnsmasq.rb w/Formula/dnsmasq.rb
index e3148ae..e100b49 100644
--- i/Formula/dnsmasq.rb
+++ w/Formula/dnsmasq.rb
@@ -1,15 +1,15 @@
 class Dnsmasq < Formula
   desc "Lightweight DNS forwarder and DHCP server"
   homepage "http://www.thekelleys.org.uk/dnsmasq/doc.html"
-  url "http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.76.tar.gz"
-  sha256 "777c4762d2fee3738a0380401f2d087b47faa41db2317c60660d69ad10a76c32"
+  url "http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.75.tar.gz"
+  sha256 "f8252c0a0ba162c2cd45f81140c7c17cc40a5fca2b869d1a420835b74acad294"

   bottle do
     cellar :any_skip_relocation
     sha256 "98d0c8520998b8038c610e43db5fc2f215a164c02810718e6e508d4651f6f523" => :sierra
     sha256 "be3f214a1a48bee2aa64f8602d1227a1fb7f60ad7e30d1241b3e5b8410ec40b1" => :el_capitan
     sha256 "ff12dc78fd0b31297e333c991d37d8c1f6979d753755ddc8c09d5153cbf54a22" => :yosemite
-    sha256 "56cfdbe6df3ecff3a6ccf444d8fd79fb234f2b566abc1a4a4631d960eb16851a" => :mavericks
+    sha256 "c3aad8472b1d51d81c14ecfecec69cfa94a43adb07a445c11880ad0c0c9ffc1e" => :mavericks
   end

   option "with-libidn", "Compile with IDN support"
```

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mstreuhofer** [comment]
Sorry, i guess i didn't say it directly. Homebrew is working just fine. Even version 2.76 of dnsmasq installs cleanly. Just that dnsmasq itself doesn't work. At least the DHCP part does not work.
Mentioned it her in the hopes I'm not the only one and Homebrew is willing to just downgrade to 2.75 of dnsmasq to sidestep the problem until it is fixed upstream.

**Comment by MikeMcQuaid** [comment]
Sorry, best to report this to `dnsmasq` themselves and request a speedy 2.77.
