### ISSUE TITLE
Abseil-cpp bump to 20210324.0 will break ortools build

### ISSUE THREAD

**Issue by Mizux** [Homebrew/homebrew-core#74657]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output
Abseil-cpp just release a new version 20210324.0 which remove the deprecated CMake target
absl::container BUT last ortools release (v8.2) still use it...
see: https://github.com/abseil/abseil-cpp/issues/932

So if someone try to bump abseil.rb to the last version you'll need to apply this patch on ortools https://github.com/google/or-tools/commit/9e901a7b24e5860baa90c0fc7a02de622bc9403a

ps: As the OSS release manager for Google/OR-Tools we expect to release version v9.0 (with abseil-cpp 20210324.0 and protobuf 3.15.7 support) by one or two weeks...

### 
The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?
Prevent homebrew-core formula breakage, help maintainers...

### What happened (include all command output)?
Bump of Google abseil-cpp will break the Google ortools build...

### What did you expect to happen?
bump of abseil-cpp should not impact the build of ortools

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Bump abseil-cpp to the last version aka 20210324.0, then try to build ortools.rb ...
```

**Comment by carlocab** [comment]
Thanks for the heads up. This was caught in CI. See #74149.

The patch, however, is useful.

**Comment by carlocab** [comment]
Thanks for opening this issue. We were able to update `abseil` by rebuilding `or-tools` with the patch applied.
