### ISSUE TITLE
wartremover fails to build under sandbox due to sbt

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-core#748]
On my 10.9.5 box, wartremover currently fails to build under the sandbox. [Logs here](https://gist.github.com/78e679dd56787e1c73e6f4239ef3d8dc).

```
$ brew install -s wartremover
==> Using the sandbox
==> Downloading https://github.com/puffnfresh/wartremover/archive/v0.13.tar.gz
==> Downloading from https://codeload.github.com/puffnfresh/wartremover/tar.gz/v0.13
######################################################################## 100.0%
==> sbt core/assembly
Last 15 lines from /Users/janke/Library/Logs/Homebrew/wartremover/01.sbt:
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
        ...
```

Looks like a sandbox violation from the `sbt` build tool it uses. From the sandbox log.

```
May  1 11:43:06 sandboxd[118]: java(47485) deny file-write-create /Users/janke/.sbt
May  1 11:43:06 sandboxd[118]: java(47485) deny file-write-create /Users/janke/.sbt
May  1 11:43:06 sandboxd[118]: java(47485) deny file-write-create /Users/janke/.sbt
```

SBT is one of those programs that auto-updates itself when it runs. When I run it interactively outside the sandbox, it downloads a lot of components to `~/.sbt`. Looks like the package installed by our `sbt` formula is more of an installer stub.

`brew install -s wartremover` still fails after I run `sbt` interactively and let it install. [Logs here.](https://gist.github.com/d19d0729eb61435672e7c5112503a7f3)

```
$ brew install -s wartremover
==> Using the sandbox
...
==> sbt core/assembly
Last 15 lines from /Users/janke/Library/Logs/Homebrew/wartremover/01.sbt:
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
...
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.io.FileNotFoundException: /Users/janke/.sbt/boot/sbt.boot.lock (Operation not permitted)
```

Looks like this is a sandbox failure due to it not respecting `$HOME`.

Maybe this could be fixed with setting system properties in `_JAVA_OPTS`. But re-installing `sbt` into the build sandbox on every single `sbt`-using run is a bummer. Maybe the `sbt` formula could be modified to actually do a full installation using an offline installer or grabbing `~/.sbt` or something.

**Comment by ilovezfs** [comment]
Adding `ENV.java_cache` prevents the violation. @apjanke Is that not appropriate for this one?

**Comment by apjanke** [comment]
If we did `ENV.java_cache` for this and other SBT-using tools, we'd end up re-downloading a fresh copy of SBT for every `sbt` build. Which seems kind of like a waste.

But it's probably the right thing to do, at least for now, and we should just consider the extra download times as a cost of sandboxing and SBT's deployment model not playing well with it, since SBT is kind of its own package manager.
