### ISSUE TITLE
svn 1.9.5_1 does not build apache modules

### ISSUE THREAD

**Issue by sakra** [Homebrew/homebrew-core#7480]
I have installed svn 1.9.5_1 from source with `--with-java --with-python`.

The resulting package does not contain the apache modules `mod_dav_svn.so` and `mod_authz_svn.so` in the libexec installation folder.

Build log: https://gist.github.com/anonymous/2673072a21591b85c6e946ee967c75ad

**Comment by MikeMcQuaid** [comment]
This is expected behaviour. We'd consider a pull request to add this.
