### ISSUE TITLE
Error: 757 when trying to uninstall jenkins via homebrew

### ISSUE THREAD

**Issue by madulog** [Homebrew/homebrew-core#7483]
### Bug reports:

Trying to uninstall jenkins from homebrew and this error is generated.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:155:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:61:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:56:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:56:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:56:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:101:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:264:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:68:in `block in resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:52:in `resolved_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:125:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by ilovezfs** [comment]
```
cd  $(brew --repo)
git fetch
git reset --hard origin/master
```
try again

**Comment by madulog** [comment]
Thank you @ilovezfs for your help. That did it!

**Comment by madulog** [comment]
That did not solve it unforunately :(

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by ilovezfs** [comment]
@madulog did you resolve this?
