### ISSUE TITLE
[RFC] jemalloc may not be working with dynamic link

### ISSUE THREAD

**Issue by equal-l2** [Homebrew/homebrew-core#7488]
In neovim/homebrew-neovim#204, we are discussing that homebrew's jemalloc doesn't work well with neovim if dynamically linked.

A solution is to link jemalloc statically, but it is unknown why this solves the problem.

By the way, I found following description in jemalloc's INSTALL, from line 59 to 73
```
--with-jemalloc-prefix=<prefix>
    Prefix all public APIs with <prefix>.  For example, if <prefix> is
    "prefix_", API changes like the following occur:

      malloc()         --> prefix_malloc()
      malloc_conf      --> prefix_malloc_conf
      /etc/malloc.conf --> /etc/prefix_malloc.conf
      MALLOC_CONF      --> PREFIX_MALLOC_CONF

    This makes it possible to use jemalloc at the same time as the system
    allocator, or even to use multiple copies of jemalloc simultaneously.

    By default, the prefix is "", except on OS X, where it is "je_".  On OS X,
    jemalloc overlays the default malloc zone, but makes no attempt to actually
    replace the "malloc", "calloc", etc. symbols.
```

Homebrew's jemalloc overwrite default with ```--with-jemalloc-prefix= ``` for "portability", see Homebrew/legacy-homebrew#42831.
~~I think this is the cause of the problem.~~
I realized that prefix doesn't matter with neovim.

**Comment by MikeMcQuaid** [comment]
To help us debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by MikeMcQuaid** [comment]
(Basically: can you explain how to reproduce this using Homebrew commands and `neovim` invocations as it's unclear to me where this is described)

**Comment by ilovezfs** [comment]
Unless upstream has subsequently made a change, we're overriding upstream defaults as of https://github.com/Homebrew/legacy-homebrew/pull/42831 and I, for one, cannot explain why that is a good idea (or not a good idea).

**Comment by MikeMcQuaid** [comment]
> Unless upstream has subsequently made a change, we're overriding upstream defaults as of Homebrew/legacy-homebrew#42831 and I, for one, cannot explain why that is a good idea (or not a good idea).

Then again, it's also a provided configure option which (at least at the time) MacPorts also uses and makes the library more portable on macOS.

**Comment by ilovezfs** [comment]
Then we should convince upstream of that and get it changed.

**Comment by MikeMcQuaid** [comment]
MacPorts are still doing the same as us here: https://github.com/macports/macports-ports/blob/4bfac00279d61e951c4617eadfad168b69c767f0/devel/jemalloc/Portfile#L35

**Comment by ilovezfs** [comment]
Seems upstream has been doing this on macOS ever since macOS support was added: https://github.com/jemalloc/jemalloc/commit/2dbecf1f6267fae7a161b9c39cfd4d04ce168a29

Given that Homebrew and MacPorts have both been doing this apparently without problems for a while, it seems like it would be reasonable to consider asking upstream to change that default.

That said, upstream documentation seems to expect that the `--with-mangling=<map>` will be used when the `je_` prefix isn't, and we're not doing do that either.

**Comment by MikeMcQuaid** [comment]
> Given that Homebrew and MacPorts have both been removing the je_ prefix apparently without problems for a while, it seems like it would be reasonable to consider asking upstream to change that default.

👍

**Comment by ilovezfs** [comment]
@equal-l2 mind retesting with 4.4.0, which just shipped?
https://github.com/Homebrew/homebrew-core/pull/7525

**Comment by equal-l2** [comment]
@lovezfs 
No changes with updated one, just the same situation.

By the way, I noticed prefix actually doesn't matter with neovim.
I'm very sorry for bothering you.
(I've never noticed this because this problem occurs somewhat randomly and I forget to test thoroughly)

**Comment by ilovezfs** [comment]
>I'm very sorry for bothering you.

Don't be. You brought something to my attention in the jemalloc formula I certainly didn't know about. :)

Does just building it statically fix the problem?

**Comment by equal-l2** [comment]
@ilovezfs 
Yes, with confidence.

**Comment by ilovezfs** [comment]
@equal-l2 I think I'd run the problem by jemalloc upstream and see if they have any thoughts. Since the brew bottle provides both the dynamic and static library, I'm not sure there's much more we can do.

**Comment by equal-l2** [comment]
@ilovezfs 
Thank you for your all advice.

**Comment by ilovezfs** [comment]
You're welcome.
