### ISSUE TITLE
vmalloc and vcodex downloads are failing

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew-core#749]
The `vmalloc` download is failing due to a redirect loop or something similar. Affects both the tarball itself and that `~astopen` user home page.

```
$ brew install -s vmalloc
==> Using the sandbox
==> Downloading http://www2.research.att.com/~astopen/download/tgz/vmalloc.2013-05-31.tgz
==> Downloading from http://www.research.att.com/~astopen/download/tgz/vmalloc.2013-05-31.tgz
######################################################################## 100.0%
curl: (47) Maximum (50) redirects followed
Error: Failed to download resource "vmalloc"
Download failed: http://www.research.att.com/~astopen/download/tgz/vmalloc.2013-05-31.tgz
```

I emailed their webmaster using the contact info at the bottom of the www.research.att.com site.

Archive.org's wayback machine does not have this archived.

Also affects `vcodex`, which is hosted on the same site.

Also affects `ksh`, which was hosted on the same site. But it has a third-party mirror that we have switched to, so it's still working.

**Comment by ilovezfs** [comment]
@apjanke I suspect this is deliberate since it coincides with the appearance of the GitHub repo.

**Comment by apjanke** [comment]
Probably so (though I bet they meant to redirect to a new landing page instead of creating a broken redirect loop). I saw you [mention this on the other issue](https://github.com/Homebrew/homebrew-core/issues/342#issuecomment-216048076) and ask them for a tagged release (att/ast#3). Hopefully they'll do so.

But it's been like two months since you asked about a tag, and no response. Seems like this project may be moribund, or at least not making formal releases available. If that's the case, it's probably boneyard time for both of `vmalloc` and `vcodex`, since they don't meet Homebrew acceptance criteria any more.

**Comment by ilovezfs** [comment]
That may mean ksh has to go too since it's living on third-party link life support. :(

**Comment by apjanke** [comment]
That'd be a bummer. Ksh is not exactly obscure software.

The Download link from http://www.kornshell.com/ is a link to http://www.research.att.com/sw/download, which is also a broken redirect loop. They should be notified too. Does someone want to, uh, email David Korn and ask him where to find releases now?

**Comment by apjanke** [comment]
Okay. I emailed ![email](https://cloud.githubusercontent.com/assets/2618447/14943625/d8d80d08-0fab-11e6-9c37-76041a3f8175.gif). We'll see if they can help us.

**Comment by apjanke** [comment]
I emailed AT&T research, and they confirmed that it has been moved to that GitHub repo. I asked about labeling releases via email too; we'll see what they have to say there. I heard back on email within a day, so they might be more responsive there than on their GitHub issue tracker.

**Comment by ilovezfs** [comment]
Excellent news!

I'm wondering if we're going to want a new single monolithic `ast` formula, since there seems to be a new build system all in one repo, or if it'll be better to keep the formulae separated, and use the same underlying repository for all of them, with the specific package selected per formula.

**Comment by DomT4** [comment]
Any update on this?

**Comment by ilovezfs** [comment]
I found this: https://www.mail-archive.com/ast-users@lists.research.att.com/msg01079.html

**Comment by MikeMcQuaid** [comment]
Closing out upstream issues.
