### ISSUE TITLE
allegro: `find_package` helper for CMake excluded

### ISSUE THREAD

**Issue by SamuelMarks** [Homebrew/homebrew-core#74905]
### `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES CXX)

set(src src/main.cpp)

find_package(allegro5 CONFIG REQUIRED) # also tried `allegro`
# mark_as_advanced (allegro5)

add_executable(${PROJECT_NAME} ${src})
target_link_libraries(${PROJECT_NAME} PRIVATE allegro5)
```

### `sh`
```sh
$ brew install allegro cmake
$ mkdir build && cd $_
$ cmake ..
```

### Error

```
CMake Error at CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "allegro5" with any
  of the following names:

    allegro5Config.cmake
    allegro5-config.cmake

  Add the installation prefix of "allegro5" to CMAKE_PREFIX_PATH or set
  "allegro5_DIR" to a directory containing one of the above files.  If
  "allegro5" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/allegro/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/allegro/build/CMakeFiles/CMakeError.log".
```

(I'm assuming this is how allegro is expected to be included CMake-wise… @morusn / @SiegeLord  ?)

**Comment by carlocab** [comment]
This is what the formula does:

https://github.com/Homebrew/homebrew-core/blob/cfe040c17617e43c00e677c84e0e48262f6b67a6/Formula/allegro.rb#L33-L36

It seems very unlikely that this is a problem with the formula, in which case the correct place to report this is to the upstream project.

We can reopen this if it turns out that this is a formula issue.

**Comment by SamuelMarks** [comment]
@carlocab - Is there some maintainers guide for brew which recommends how to package header files and libraries for consumption by build-systems?

**Comment by carlocab** [comment]
Nothing written down. However, there isn't much to it, as it basically boils down to: leave as much to the upstream build system as possible.

Every other formula bar one that packages a `.cmake` file has those installed by `make install`.

**Comment by SamuelMarks** [comment]
@carlocab No no I mean in terms of using `brew` to manage the dependencies of out-of-brew projects. E.g., using `brew` as an alternative to `vcpkg` to install C/C++ headers and libraries in such a way that your local development projects can leverage them.

In the CMake world that usually means exposing a `[package_name]-config.cmake` file in CMake's search path.

Is there a `brew`-way of doing this? - Is it recommended, or would you suggest `brew` not be used for this purpose?

**Comment by carlocab** [comment]
You could try adding `$(brew --prefix package_name)` to your `CMAKE_PREFIX_PATH`. If you've installed Homebrew into a default prefix, then this should only be needed for keg-only formulae, if at all.

If you're in a non-default prefix then you might also need to add `$(brew --prefix)` to your `CMAKE_PREFIX_PATH`. Homebrew's default prefixes are already in CMake's search path (for new enough versions of CMake, at least).

**Comment by carlocab** [comment]
I don't think `allegro` ships with an `allegro[5].cmake`. It does ship a `pc` file though. You need to use `pkg-config` to find it.
