### ISSUE TITLE
SHA256 mismatch  armadillo

### ISSUE THREAD

**Issue by cxwx** [Homebrew/homebrew-core#75005]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
╰─ brew config                                       INSERT  5200  100%
HOMEBREW_VERSION: 3.0.11-164-gccb05e5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ccb05e5e0b7b925c3d6b531fa43b016fa4d0b72a
Last commit: 51 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b5f0f6a6fc97cd434b47ddf1ff9a2e2d6ec0376d
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.9VgYX6wZr2/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

brew upgrade

or 

brew upgrade armadillo

### What happened (include all command output)?

─ brew upgrade                                      INSERT  5178  100%
==> Upgrading 3 outdated packages:
ensmallen 2.16.2 -> 2.16.2_1
armadillo 10.3.0 -> 10.4.0
mlpack 3.4.2 -> 3.4.2_1
==> Upgrading ensmallen 2.16.2 -> 2.16.2_1
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/armadil
#=#=#                                                                       ###############################################################           88######################################################################## 100.0%
Error: SHA256 mismatch
Expected: fbda88ac109efeb559f7a3acc1e16a65d4019b0e08e2c9fc8d417db6e9c817ac
  Actual: 149e40e4ba150a3cbee0e5f8ae1a4fa833db11b817cb9b15f2b68e18bfce291e
    File: /Users/chenxu/Library/Caches/Homebrew/downloads/01843d82ed8ba0eb974aca70a55a44d4ec389ba2125d706c35ba0c325f1095df--armadillo-10.4.0.big_sur.bottle.tar.gz
To retry an incomplete download, remove the file above.

### What did you expect to happen?

sha256 match

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade
```

**Comment by cxwx** [comment]
sorry it's the mirrors sync error https://mirrors.ustc.edu.cn/

**Comment by MikeMcQuaid** [comment]
Mirror needs fixed.
