### ISSUE TITLE
Problems installing MacTex

### ISSUE THREAD

**Issue by juansgomezr** [Homebrew/homebrew-core#75026]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ccb05e5e0b7b925c3d6b531fa43b016fa4d0b72a
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3de981807f9c17f54d6553a3484fa11d44659ff6
Core tap last commit: 29 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: N/A
Xcode: 12.4
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Install MacTex

### What happened (include all command output)?

Error: mactex: Download failed on Cask 'mactex' with message: Download failed: http://mirror.ctan.org/systems/mac/mactex/mactex-20210328.pkg

### What did you expect to happen?

Install MacTex without any problem

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade --greedy
```

**Comment by carlocab** [comment]
MacTex is a cask. Please report this at https://github.com/Homebrew/homebrew-cask.
