### ISSUE TITLE
Failed to install imagemagick: can't download ghostscript, libde265, etc.

### ISSUE THREAD

**Issue by benmgreene** [Homebrew/homebrew-core#75033]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
(happening in CI, but confirmed locally)
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

Install imagemagick

### What happened (include all command output)?

Can't download dependencies:
```
+ brew install imagemagick
==> Downloading https://homebrew.bintray.com/bottles/ghostscript-9.53.3_1.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "ghostscript"
Download failed: https://homebrew.bintray.com/bottles/ghostscript-9.53.3_1.catalina.bottle.tar.gz
```

### What did you expect to happen?

Download dependencies, successfully install imagemagick

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install imagemagick`
```

**Comment by carlocab** [comment]
Bintray is currently on a scheduled brownout. You'll need to `brew update` to download from GitHub Packages instead.
