### ISSUE TITLE
Installing automake fail with brew on every CI run

### ISSUE THREAD

**Issue by Milerius** [Homebrew/homebrew-core#75045]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
none
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

installing automake

### What happened (include all command output)?

brew install automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.16.3_1.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 502 Bad Gateway
Error: Failed to download resource "automake"
Download failed: https://homebrew.bintray.com/bottles/automake-1.16.3_1.catalina.bottle.tar.gz

### What did you expect to happen?

installing automake

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install automake
```

**Comment by carlocab** [comment]
Bintray has a scheduled brownout. To be able to install bottles from GitHub Packages, you need the latest version of `brew`. Do `brew update` and try again.
