### ISSUE TITLE
fail to install mono, Error: mono: no bottle available!

### ISSUE THREAD

**Issue by fdq09eca** [Homebrew/homebrew-core#75145]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
chrislam@ChrisLams-MBP ~ % brew config
HOMEBREW_VERSION: 3.1.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: dc3e8b485a166a73d6463320d9deaba6236f747c
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5723b3eb23ab6a68df4e421ddc53036c88cf8676
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4
Rosetta 2: false
```

```
chrislam@ChrisLams-MBP ~ % brew doctor
Your system is ready to brew.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to install mono.

### What happened (include all command output)?

`Error: mono: no bottle available!`

### What did you expect to happen?

mono to be installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
chrislam@ChrisLams-MBP ~ % brew install mono
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 1 cask.

Error: mono: no bottle available!
You can try to install from source with:
  brew install --build-from-source mono
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

```

**Comment by carlocab** [comment]
`mono` has no bottle because it doesn't work on ARM (yet?).

If that's not true, and the formula builds with no changes, let me know and we can add a bottle for it. If it requires changes to build, please open a pull request. Thanks!

**Comment by fdq09eca** [comment]
i think it works fine with ARM.,see [here](https://www.mono-project.com/docs/about-mono/supported-platforms/)
![image](https://user-images.githubusercontent.com/51902242/114644633-c7d94380-9ccf-11eb-9f2b-19c1cc600ffa.png)

**Comment by gromgit** [comment]
I don't see it working with _macOS_ ARM.
