### ISSUE TITLE
linuxbrew does not work at all

### ISSUE THREAD

**Issue by dongz9** [Homebrew/homebrew-core#7517]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
- [ ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I installed linuxbrew today and met the following error:

```
Error: Invalid formula: MY_HOME/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/internetarchive.rb
cannot load such file -- utils/json
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: MY_HOME/.linuxbrew/bin/brew tap homebrew/core -q
```

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
You'll need to report this to ... Linuxbrew
https://github.com/Linuxbrew/brew
