### ISSUE TITLE
Formula dfu-util.rb wrong.

### ISSUE THREAD

**Issue by ApprenticeHuman** [Homebrew/homebrew-core#75194]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
evdavi@147dda289389 ~ % brew gist-logs dfu-util 
Error: No logs.
evdavi@147dda289389 ~ % brew gist-logs dfu-util
Error: No logs.
evdavi@147dda289389 ~ % brew config            
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 685eea39ffe258bb79e323d212c2e1ff020eefc4
Core tap last commit: 7 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.30.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
evdavi@147dda289389 ~ % brew doctor
Your system is ready to brew.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

This is a bug that is only seen when trying to use lsusb that is included with the current dfu-util.rb.

The problem is the line
_depends_on "libusb"_
This includes a shell script.

When actually debugging the output from dfu-utils you need to use the lsusb included with the binary distribution from https://sourceforge.net/projects/dfu-util/.
You shell script doesn't produce the correct output that the binary distribution does.

Someone needs to change the rules to include the binary and add the test "./bin/libusb -V". This currently returns "lsusb (usbutils) 013"

See https://sourceforge.net/p/dfu-util/tickets/117/ for a full discussion of why this is a bug and needs to be changed.

### What happened (include all command output)?

evdavi@147dda289389 darwin % lsusb  
2021-04-14 14:50:28.560 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-04-14 14:50:28.561 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-04-14 14:50:28.561 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-04-14 14:50:28.562 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-04-14 14:50:28.562 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-04-14 14:50:28.563 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2021-04-14 14:50:28.563 system_profiler[66277:8644817] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
Bus 020 Device 001: ID 1050:0403 1050 Yubikey 4 OTP+U2F 
Bus 128 Device 004: ID 05ac:8104 Apple Inc. Composite Device  Serial: 000000000000
Bus 128 Device 000: ID 05ac:8102 Apple Inc. Touch Bar Backlight  Serial: 0000000000000000
Bus 128 Device 000: ID 05ac:8302 Apple Inc. Touch Bar Display  Serial: 0000000000000000
Bus 128 Device 000: ID 05ac:0340 Apple Inc. Apple Internal Keyboard / Trackpad  Serial: FM7028602DAHYYKAC+RVT
Bus 128 Device 000: ID 05ac:8103 Apple Inc. Headset  Serial: 000000000000
Bus 128 Device 000: ID 05ac:8262 Apple Inc. Ambient Light Sensor  Serial: 000000000000
Bus 128 Device 000: ID 05ac:8514 Apple Inc. FaceTime HD Camera (Built-in)  Serial: CC2029403L1HNW13L
Bus 128 Device 000: ID 05ac:8233 Apple Inc. Apple T2 Controller  Serial: 0000000000000000
Bus 000 Device 001: ID 1d6b:CITR Linux Foundation USB 3.1 Bus 
Bus 001 Device 001: ID 1d6b:CITR Linux Foundation USB 3.1 Bus 
Bus 000 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub 
Bus 000 Device 000: ID 05ac:8104 Apple Inc. Apple T2 Bus 

### What did you expect to happen?

evdavi@147dda289389 darwin % ./lsusb 
Bus 020 Device 001: ID 1050:0403  
Bus 128 Device 004: ID 05ac:8104  

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
You tell me where this belongs! I couldn't submit this against the formula directly.
```

**Comment by Bo98** [comment]
> The problem is the line
> _depends_on "libusb"_
> This includes a shell script.

libusb is a C library - not a bash script.

Installing dfu-utils also doesn't install a lsusb script by default.

> This currently returns "lsusb (usbutils) 013"

This sounds like a request for a `usbutils` formula? I can have a look.

**Comment by ApprenticeHuman** [comment]
I don't think it's a lsusb issue, The person running dfu-utils expects the data in the form his binary returns. The shell script seems to attempt to map OS X (OO BSD kernel) into a linux type hierarchy.

If you look at the issue (linked above) for dfu-utils you'll see in the attached files the difference in output between the shell script and the dfu-utils binary. 

For deeper arguments I'd say ask Tormond (one of the dfu-utils maintainers) and not me. But I can supply the differences in the output between what Homebrew has and what the dfu-utils group expects.

And it looks like dfu-utils have a binary version of lsusb() that works over various OS X versions. It certainly worked on Big Sur, for me.

**Comment by carlocab** [comment]
>The problem is the line
depends_on "libusb"
This includes a shell script.

`libusb` does not include any shell scripts. These are all the files provided by the `libusb` formula:
```
❯ exa --tree -a
.
├── .brew
│  └── libusb.rb
├── AUTHORS
├── ChangeLog
├── COPYING
├── include
│  └── libusb-1.0
│     └── libusb.h
├── INSTALL_RECEIPT.json
├── lib
│  ├── libusb-1.0.0.dylib
│  ├── libusb-1.0.a
│  ├── libusb-1.0.dylib -> libusb-1.0.0.dylib
│  └── pkgconfig
│     └── libusb-1.0.pc
├── NEWS
├── README
├── share
│  └── libusb
│     └── examples
│        ├── dpfp.c
│        ├── ezusb.c
│        ├── ezusb.h
│        ├── fxload.c
│        ├── hotplugtest.c
│        ├── listdevs.c
│        ├── sam3u_benchmark.c
│        ├── testlibusb.c
│        └── xusb.c
└── TODO
```

**Comment by ApprenticeHuman** [comment]
Carlocab,
I'll have to get back to this, with more details then. I don't know what else would have place usblib into /usr/local/bin/. But you make a very strong point that something's screwed at my end.

I'll see what I can dig-up when I use the Mac, tomorrow.

Thanks!

**Comment by cho-m** [comment]
@ApprenticeHuman 

> The only version of lsusb I had on my Mac was from Homebrew and it was bash shell script.

Did you perhaps install the `lsusb` Formula: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lsusb.rb
Which is a Bash script port of Linux command: https://github.com/jlhonora/lsusb/blob/master/lsusb

---

> I had to download the dfu-utils binary package to get a binary when asked to by Tormond.

The README.txt file from the binaries archive explains how `lsusb` was built:

```
These binaries were built on macOS 10.13.6
...
The lsusb utility was built from usbutils commit v013-2-gbc48602
with the patch lsusb_build_on_mingw.patch applied.
```

This would be in-line with what @Bo98 mentioned.
Homebrew would need to support building `usbutils` Formula to support `lsusb` binary.

**Comment by tormodvolden** [comment]
https://stackoverflow.com/questions/17058134/is-there-an-equivalent-of-lsusb-for-os-x links to a usbutils 7 formula.

Latest usbutils rely on udev to get the strings for manufacturer and product etc. My patch for usbutils 13 strips out the udev references so it can build on macOS and Windows at the expense of missing out on this information.

Either of those two would be better than the wrapper that ships as "lsusb" now. It is confusing for users and a lot of extra work for those trying to help out to find out and explain that the lsusb installed is not lsusb.

**Comment by ApprenticeHuman** [comment]
Well, from the bash script:
#!/usr/bin/env bash
# lsusb (list USB devices) utility for Mac OS X
# Author: JLH, Sep 2013
#
# Disclaimer: usage info and functionality from lsusb under Linux

verbose () { system_profiler SPUSBDataType; }
version () { echo "lsusb for Mac OS X 007"; }
help ()  {
  cat >&2 <<EOM
$(usage)

From the man page:
       Please report other bugs at https://github.com/jlhonora/lsusb

AUTHORS
       Jose L. Honorato <jlhonora@ing.puc.cl>

CONTRIBUTORS
       See https://github.com/jlhonora/lsusb/graphs/contributors for an up-to-
       date list.

So this is out of date, with the last update 7 years ago. I must have pulled this in with the dfu-util. And there's the issue.... dfu-util has it's own, up to date version of lsusb (as a generic binary for all OS X versions that dfu-util supports).

So this is an issue with dfu-util formula pulling in the old, bash script instead of the binary. Since the dfu-util used in the formula is a binary from the maintainers, shouldn't this formula be updated to use the correct lsusb code? In this case the one in the dfu-utils binary package, or build from the source code?

**Comment by cho-m** [comment]
@ApprenticeHuman What you copied is the `lsusb` Homebrew formula I previously referred to.

There are currently no Homebrew formulas that automatically install this.
You would have had to run `brew install lsusb` at some point in time.
```console
~
❯ brew uses lsusb

~
❯ lsusb
The program 'lsusb' is currently not installed. You can install it by typing:
  brew install lsusb

~
```

---

Neither `dfu-util` formula nor [`libusb`](https://github.com/libusb/libusb) formula builds `lsusb` binary.

The version of `lsusb` you refer to is a pre-built of [`usbutils`](https://github.com/gregkh/usbutils/).

Homebrew needs to be able to build source to support `usbutils`.
One possibility would be to create a new `usbutils` formula with patch file and building like @tormodvolden mentioned.

`libusb` only provides the `listdevs` binary inside example directory: https://github.com/libusb/libusb/commit/4afbc78fe09bfc3dd7a609e5f82e9272c9e6226d

**Comment by tormodvolden** [comment]
Yes, absolutely, dfu-util does not require lsusb. I have only shipped the patched lsusb in the binary releases because it is very useful for debugging a user problem. An official usbutils formula (and removing or renaming the lsusb wrapper) would be very welcome.

**Comment by ApprenticeHuman** [comment]
Cho-m,
D'oh! I see where I'm misreading what you have clear said.

I don't have an OS X compiler and I'm normally on linux. Does Homebrew compiles binaries on their own server, somehow?

If so, I'll try and work out how to do what Tormod Volden did for the binary he bundles with dfu-utils. 

Are there any guides or documentation that would help me? I last compiled a kernel back in 2001 so I'm more than rusty.

**Comment by ApprenticeHuman** [comment]
Cho-m,
D'oh! I see where I'm misreading what you have clear said.

I don't have an OS X compiler and I'm normally on linux. Does Homebrew compiles binaries on their own server, somehow?

If so, I'll try and work out how to do what Tormod Volden did for the binary he bundles with dfu-utils. 

Are there any guides or documentation that would help me? I last compiled a kernel back in 2001 so I'm more than rusty.

**Comment by ApprenticeHuman** [comment]
I'll close this in a few days. I'm hoping for some URLs on how I'd update the lsusb code to compile using xcode. 

I tried to get a job in C, having come second highest in my year at university, alas nothing was available. After 30 years of not coding and  not having can OO skills I'm hoping for some guidance on what to do.

**Comment by tormodvolden** [comment]
You don't need OO skills or xcode, but some web-searching-fu might come handy. Just download the usbutils source, patch it with `patch -p1 < lsusb_build_on_mingw.patch` and then `./configure` and `make lsusb`
