### ISSUE TITLE
brew install graphviz, then  Error: Failed to download resource "libpng"

### ISSUE THREAD

**Issue by DangerShi** [Homebrew/homebrew-core#75213]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6a76f3302e592bb31be34a7b53e654896bc299ef
Core tap last commit: 53 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A

brew doctor
Your system is ready to brew.

brew update
Already up-to-date.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

try to install graphviz (see: https://www.graphviz.org/download/)
by the commond:
brew install graphviz

### What happened (include all command output)?

brew install graphviz
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/libpng-1.6.37.catalina.bottle.tar.gz
==> Downloading from https://homebrew.bintray.com/libpng-1.6.37.catalina.bottle.tar.gz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/libpng-1.6.37.catalina.bottle.tar.gz
==> Downloading from https://github.com/-/v2/packages/container/package/homebrew%2Fcore%2Flibpng-1.6.37.catalina.bottle.tar.gz
#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "libpng"
Download failed: https://ghcr.io/v2/homebrew/core/libpng-1.6.37.catalina.bottle.tar.gz

### What did you expect to happen?

install graphviz successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install graphviz
```

**Comment by carlocab** [comment]
Please `unset HOMEBREW_BOTTLE_DOMAIN` and try again.

**Comment by DangerShi** [comment]
> Please `unset HOMEBREW_BOTTLE_DOMAIN` and try again.

It worked, thx a lot.
