### ISSUE TITLE
unable to build tap formula because sdl2_ttf bottle not available

### ISSUE THREAD

**Issue by aconchillo** [Homebrew/homebrew-core#75345]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Doesn't really apply here.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to build a formula from homebrew-guile tap:

https://github.com/aconchillo/homebrew-guile

### What happened (include all command output)?

The sdl2_ttf bottle doesn't seem to be available and tap formulas don't build from source:

https://github.com/aconchillo/homebrew-guile/pull/31/checks?check_run_id=2367910533

### What did you expect to happen?

I expected for the bottle to exist and the formula to be built as before.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just updated version of a Formula that depends on SDL2.
```

**Comment by SMillerDev** [comment]
We don't provide support for external taps. And for homebrew-core issues we require the full issue template to be filled out.

**Comment by aconchillo** [comment]
Thank you @SMillerDev . I usually fill everything properly but I didn't know how to proceed this time. It seems an issue related to a missing bottle of one of the homebrew-core forumlas (`sdl2_ttf`). What would be the right thing to do? I'd appreciate any advice. Thanks!

**Comment by nandahkrishna** [comment]
Based on the run you linked to in your original report, this is due to `sdl2_ttf` not being bottled on Linux (https://formulae.brew.sh/formula-linux/sdl2_ttf), and not macOS.

**Comment by aconchillo** [comment]
@nandahkrishna yes, that's correct. do you know how bottles for the current version of a formula can be regenerated? that's my original question. my tap formulas are blocked because of this and I'm not sure how to get around it (a part from not building Linux bottles).

**Comment by SMillerDev** [comment]
If it doesn't have a Linux bottle but you're sure it compiles on Linux you can make an issue on Homebrew/linuxbrew-core

**Comment by aconchillo** [comment]
oh, i didn't actually realize there's a linuxbrew-core! (i just have the default github worklfow on my tap, which includes Linux and I was not aware of it). thank you @SMillerDev ! I'll try to build it and see what I get. thanks again.
