### ISSUE TITLE
docker-completion & docker are in conflict

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-core#7543]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
`docker` and `docker-completion` have file in conflict. 

Same issue had beed reported in homebrew-completions https://github.com/Homebrew/homebrew-completions/issues/155

```brew reinstall docker-completion 
==> Reinstalling homebrew/completions/docker-completion
Error: Could not symlink etc/bash_completion.d/docker
Target /usr/local/etc/bash_completion.d/docker
is a symlink belonging to docker. You can unlink it:
  brew unlink docker

To force the link and overwrite all conflicting files:
  brew link --overwrite docker-completion

To list all files that would be deleted:
  brew link --overwrite --dry-run docker-completion
```

**Comment by MikeMcQuaid** [comment]
Please don't file the same issue twice. Let's deal with it in https://github.com/Homebrew/homebrew-completions/issues/155 (and please copy-paste the issue body in there).
