### ISSUE TITLE
Relocatable bottles for formulae that use `CMAKE_INSTALL_RPATH`

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#75458]
We currently have a number of formulae that use `CMAKE_INSTALL_RPATH` set to `lib` or `opt_lib`. This breaks relocatability on macOS. For example, see 52203dd1ff12ce953014f477abc2bfde651ac5fb, and its parent, 068fcb91aa8d9b9ccf7ef17fad0f8951cd7ef28c.

Instead, `CMAKE_INSTALL_RPATH` should be set to `@loader_path/../lib`, but only on macOS, as `@loader_path` is macOS-specific.

Example PRs: #75450, #75449, #75457.

Formulae that use `CMAKE_INSTALL_RPATH`:

- [x] abseil #75450
- [x] aom #75457
- [x] assimp #75881
- [x] bullet #75882
- [x] cmark-gfm #75883
- [x] cryptominisat #75884
- [x] csound #75566
- [x] f3d #75886
- [x] gdcm #75887
- [x] grpc #75928
- [ ] itk
- [ ] ktoblzcheck
- [x] libical #76740
- [x] libzzip #76745
- [x] mavsdk #75928
- [x] mlpack #77376
- [x] mongo-c-driver #77377
- [x] mongo-cxx-driver #77703
- [x] mosquitto #77704
- [x] ngt #78095
- [x] opencascade #77715
- [x] opencolorio #78098
- [x] openmama #78116
- [x] ospray #78118
- [x] physfs #78205
- [x] pyside #89084
- [ ] pyside@2
- [x] rabbitmq-c #78214
- [ ] rdkit
- [x] sfml #75449
- [x] standardese #76423
- [x] uriparser #78218
- [x] vtk #78220
- [ ] vtk@8.2
- [x] x265 #76432
- [x] xerces-c #78221
- [x] xrootd #78222
- [x] zstd #75880

I imagine I'll get through this list eventually, but help would be appreciated.

-----

Bonus, for settings `CMAKE_EXE_LINKER_FLAGS`:

- [x] rocksdb #75879

**Comment by carlocab** [comment]
This will probably have to wait for https://github.com/Homebrew/brew/pull/11187.

**Comment by MikeMcQuaid** [comment]
Good call, makes sense to me @carlocab!

**Comment by carlocab** [comment]
https://github.com/Homebrew/brew/pull/11187 is merged, but any formula changes using it will need to wait until the next `brew` release tag.

**Comment by carlocab** [comment]
This is in the latest release tag. See https://github.com/Homebrew/brew/commit/d89eda09abbeae907eb88bd6d01dc9cde7ff0e19 and Homebrew/brew#11245.

**Comment by Gcenx** [comment]
Are you only including formula that add rpath via the formula?, as I known `faudio` sets `set(CMAKE_MACOSX_RPATH ON)` within its `CMakeLists.txt`

**Comment by carlocab** [comment]
Yes. `MACOSX_RPATH=ON` is the default in the latest version of CMake--this has no direct effect on bottle relocatability. See [CMP0042](https://cmake.org/cmake/help/latest/policy/CMP0042.html#policy:CMP0042).

**Comment by carlocab** [comment]
I think this is about done as we'll get.
