### ISSUE TITLE
Eigen 3.4 has not been released

### ISSUE THREAD

**Issue by tellenbach** [Homebrew/homebrew-core#75472]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Nothing relevant
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Checked the current version of the Eigen formula.

### What happened (include all command output)?

`brew info Eigen` returns

```
eigen: stable 3.4 (bottled), HEAD
C++ template library for linear algebra
https://eigen.tuxfamily.org/
Conflicts with:
  freeling (because freeling ships its own copy of eigen)
/usr/local/Cellar/eigen/3.3.9 (493 files, 6.6MB) *
  Poured from bottle on 2021-02-04 at 10:05:15
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/eigen.rb
License: MPL-2.0
==> Dependencies
Build: cmake ✘
==> Options
--HEAD
	Install HEAD version
```

which is wrong because there is no official Eigen 3.4 release. We (the Eigen team) just released Eigen 3.4-rc1, the first release candidate of the *upcoming* Eigen 3.4 release.

### What did you expect to happen?

I expect the Eigen Homebrew formula to point to the last stable release of Eigen, that is Eigen 3.3.9. I'm not entirely sure how you came to the conclusion that Eigen 3.4 has been released but, again, this is not the case.

Please revert bcfc28c6ce9d0ad680b8362c5d32f6b74362da6d that introduced this defect.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew info Eigen`
```

**Comment by tellenbach** [comment]
@chenrui333

**Comment by carlocab** [comment]
Thanks for the quick notice. Reverted in 51d18c2891db6c1af9f513b6b5d7c4a4d37a9239.
