### ISSUE TITLE
mGBA crashes on M1 Mac

### ISSUE THREAD

**Issue by dbrookman** [Homebrew/homebrew-core#75498]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/8843ba1e55cd0cad5f8b279c02845ac3
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `mGBA`.

### What happened (include all command output)?

Get the error: `Trace/BPT trap: 5`.

### What did you expect to happen?

The mGBA GUI should appear.
`brew test mgba` returns fine, because `mgba -h` still works. It only crashes when starting the GUI.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mgba
mgba
```

**Comment by carlocab** [comment]
Can you look in the Console app for a crash report? Or, if there isn't a crash report, a back trace.

**Comment by dbrookman** [comment]
Here's the [crash report](https://gist.github.com/dbrookman/be4c8386ee48bfdecf7c2c84f1b45226).
I'm fairly certain it's on mGBA's side based on [this](https://github.com/mgba-emu/mgba/issues/1754), but it'd probably be good to add a new test.

**Comment by carlocab** [comment]
I agree that a better test would be good to add. Would you like to open a PR to fix it? It's likely that no maintainer uses mGBA, so we don't really know how to provide a better test.
