### ISSUE TITLE
brew install clang-format --HEAD fails with Ruby error

### ISSUE THREAD

**Issue by georgemorgan** [Homebrew/homebrew-core#75503]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ae0e1117848c478522497fe375aff8a5891eccec
Core tap last commit: 9 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.SQYY0zylre/org.macosforge.xquartz:0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11
```

```
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the latest version of clang-format. I am trying to build the `HEAD` to get the latest `clang-format-12`.

### What happened (include all command output)?

```
brew install clang-format --HEAD
==> Cloning https://github.com/llvm/llvm-project.git
Updating /Users/gemorgan/Library/Caches/Homebrew/clang-format--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 8b754e2 Deprecate Branch
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_file_s_symlink - (/private/tmp/clang-format-20210419-44078-1maq5uj/clang, /private/tmp/clang-format-20210419-44078-1maq5uj/llvm/tools/clang)
```

### What did you expect to happen?

Brew should build and install clang-format at its latest upstream version.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install clang-format --HEAD
```

**Comment by carlocab** [comment]
Sorry, but source builds are unsupported. You'll have seen a message saying this along with the build error. Since `HEAD` builds require building from source, those are unsupported too.

Please open a PR to fix it. The culprit looks like this line

https://github.com/Homebrew/homebrew-core/blob/c64afbfd40223456aedcc37e60873ac5d5f1a409/Formula/clang-format.rb#L40-L42

**Comment by carlocab** [comment]
Actually, I think I found a fix. Opening a PR.
