### ISSUE TITLE
mac M1 mini and Big Sur [novice]

### ISSUE THREAD

**Issue by capwalker** [Homebrew/homebrew-core#75519]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Ok. I have an M1 Mac mini. I have problems running homebrew if installed in an alternative method qs suggested. In regular install, a BREW DOCTOR says to report this issue. I have yet to run it and get a reproducible error.
Unexpected dylibs:
  /usr/local/lib/libpas2jslib.dylib
Error: Cannot parse /usr/local/Cellar/libffi/3.3_3/INSTALL_RECEIPT.json: 767: unexpected token at ''
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:72:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:65:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:61:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:61:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:114:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:412:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:394:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:761:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:756:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:756:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was checking that homebrew properly installed.

### What happened (include all command output)?

Unexpected dylibs:
  /usr/local/lib/libpas2jslib.dylib
Error: Cannot parse /usr/local/Cellar/libffi/3.3_3/INSTALL_RECEIPT.json: 767: unexpected token at ''
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/local/Homebrew/Library/Homebrew/tab.rb:72:in `from_file_content'
/usr/local/Homebrew/Library/Homebrew/tab.rb:65:in `block in from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:61:in `fetch'
/usr/local/Homebrew/Library/Homebrew/tab.rb:61:in `from_file'
/usr/local/Homebrew/Library/Homebrew/tab.rb:114:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:412:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:394:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:761:in `block in check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:756:in `reject'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:756:in `check_for_unlinked_but_not_keg_only'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:64:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:57:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

### What did you expect to happen?

It should have not reported an error

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Brew Doctor

that's all
```

**Comment by MikeMcQuaid** [comment]
Try to `brew reinstall  --force libffi`
