### ISSUE TITLE
Cannot upgrade sshfs

### ISSUE THREAD

**Issue by Guillawme** [Homebrew/homebrew-core#75656]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.1.3-34-g3476ca7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3476ca7b8ff889ef61e65783d35d1b2073bd4012
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6ee6cdcb1a5edd7d73884c25313a301e2d951d1f
Core tap last commit: 16 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 11.0 build 1100
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 11.0.0.33.16
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  afuse
  ext2fuse
  ext4fuse
  fuse-zip
  ntfs-3g
  pandoc-citeproc
  sshfs

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/guillaume/Applications/ccpem-1.5.0/bin/python2-config
  /Users/guillaume/Applications/ccpem-1.5.0/bin/freetype-config
  /Users/guillaume/Applications/ccpem-1.5.0/bin/python2.7-config
  /Users/guillaume/Applications/ccpem-1.5.0/bin/python-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ghostscript
  gawk
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

While running `brew update` as I do on a regular basis, it said that `sshfs` (that was already installed) could be upgraded. So I ran `brew upgrade` as usual.

### What happened (include all command output)?

I got the following error:

```
$ brew upgrade 
==> Upgrading 1 outdated package:
sshfs 2.10_2 -> 3.7.1
==> Upgrading sshfs 2.10_2 -> 3.7.1 
Error: sshfs has been disabled because it requires FUSE!
```

### What did you expect to happen?

`sshfs` should upgrade to its latest version.

I have both the `osxfuse` and `macfuse` casks installed. Formula `sshfs` lists `libfuse` as a dependency, so I tried to install it (no idea why it would not work automatically though), but got the following error:

```
brew install libfuse
libfuse: Linux is required for this software.
Error: An unsatisfied requirement failed this build.
```

The only relevant lines from `brew doctor` seem to be:

```
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  afuse
  ext2fuse
  ext4fuse
  fuse-zip
  ntfs-3g
  pandoc-citeproc
  sshfs
```

Does that mean the `sshfs` formula is no longer maintained and I should not expect upgrades?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade sshfs
```

**Comment by SMillerDev** [comment]
> Does that mean the sshfs formula is no longer maintained and I should not expect upgrades?

Since there is no open source FUSE implementation on macOS anymore Homebrew won't ship anything that depends on it on macOS anymore.

**Comment by carlocab** [comment]
`osxfuse` and `macfuse` are fine as casks, but not formulae. Formulae must be open source.

`sshfs` has a closed-source software dependency (`osxfuse`/`macfuse`), so we can no longer ship it in homebrew/core.

If you would like to keep managing your `sshfs` install using `brew`, you can host a version of the formula in your own tap. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by gromgit** [comment]
@rplCloud , if you're willing to wait a bit, I've already laid the groundwork for migrating macOS FUSE formulae to my own tap: https://github.com/gromgit/homebrew-fuse/ . Now that all the formulae have been officially disabled, I'll start hosting them myself.

**Comment by rplCloud** [comment]
@gromgit: This is great news! You make my day! I already tapped your repo.

**Comment by MikeMcQuaid** [comment]
@gromgit nice work. would be a good addition to https://github.com/Homebrew/brew/blob/master/docs/Interesting-Taps-and-Forks.md!

**Comment by pavellishin** [comment]
> @rplCloud , if you're willing to wait a bit, I've already laid the groundwork for migrating macOS FUSE formulae to my own tap: https://github.com/gromgit/homebrew-fuse/ . Now that all the formulae have been officially disabled, I'll start hosting them myself.

Awesome! Is this going to include sshfs as well?

**Comment by vszakats** [comment]
The move of deprecating important packages (such as everything FUSE-related) could be IMO much less user-hostile, if the formulae would be kept and installable on macOS, but in a _build-from-source-only_ form and not allowing them to be used as dependencies. Let the users deal with the fallouts when it builds (or not) locally. They will have to anyway in some shape-or-form, if they really want to use these packages, but with the formula, at least upgrades would be solved and users could benefit from the community contributing back their build fixes. Which would be the point of Homebrew.

Anyway, I'm nearly sure it's a reassuring NO, and this has also been debated somewhere, but the current solution is just pure bad.

**Comment by gromgit** [comment]
> @gromgit nice work. would be a good addition to https://github.com/Homebrew/brew/blob/master/docs/Interesting-Taps-and-Forks.md!

Thanks Mike, I'll add it when I've actually gotten more than one formula moved over. :grinning:

**Comment by gromgit** [comment]
> Awesome! Is this going to include sshfs as well?

If I can build and test it successfully. The corresponding (disabled) core formulae will be my starting point, so some will likely be stuck at rather old versions.

**Comment by MikeMcQuaid** [comment]
> but in a _build-from-source-only_ form

We don't support building from source. We don't have things in Homebrew/homebrew-core that we cannot verify in our CI. We don't want to install non-open-source software in CI. 

> but the current solution is just pure bad.

This is not actionable or helpful feedback. 

> But it didn't, because _no FUSE for you_, if you're using Homebrew on a Mac.

No, no FUSE for you in Homebrew/homebrew-core on macOS. You're perfectly capable of maintaining it for people elsewhere.
