### ISSUE TITLE
git: configuration of 'credential.helper=osxkeychain' by Homebrew leads to problematic display of modal dialog

### ISSUE THREAD

**Issue by jamesquilty** [Homebrew/homebrew-core#75838]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs git
Error: No logs.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed `git` with Homebrew and I was trying to use the same `git` commands that I had been using prior to installation with Homebrew: `git pull`, `git push`, `bit branch` etc. _and also_ `brew` and `gitlab-runner` because they call git.

### What happened (include all command output)?

While working from the command line, macOS unexpectedly presented to me a modal dialog which read:

```text
git-credential-osxkeychain wants to use your confidential information stored in "github.com" in your keychain.

The authenticity of "git-credential-osxkeychain" cannot be verified. 
Do you want to allow access to this item?
```

This is the same dialog which has been reported by others (see [screenshot at StackExchange](https://apple.stackexchange.com/questions/280131/homebrew-installation-requests-to-use-my-confidential-keychain-information-shou)]).

I didn't want this and simply clicking `Deny` was not a permanent solution: the dialog would be displayed again on the next `git` operation. this took nearly 3 hours [details omitted] to resolve, so this isn't a trivial thing.

The dialog this configuration causes to be displayed also causes problems with `gitlab-runner` (which I also use):

> #### Limitations on macOS
> 
> If Homebrew was used to install git, it may have added a `/usr/local/etc/gitconfig` file ... This tells Git to cache user credentials in the keychain, which may not be what you want and can cause fetches to hang.

<https://docs.gitlab.com/runner/install/osx.html#limitations-on-macos>

### What did you expect to happen?

I expected operations with Homebrew `git` to be the same as those with the older version provided by macOS at `$ /usr/bin/git`, i.e. to execute from the command line without presenting an authentication dialog and to be able to be executed non-interactively from scripts.

### Step-by-step reproduction instructions (by running `brew` commands)

**Summary:** remove the configuration `credential.helper=osxkeychain` from [Formula/git.rb](https://github.com/Homebrew/homebrew-core/blob/e997d9f5a0559f4ec5d4b576ce5123d8f79332e2/Formula/git.rb) to avoid creating modal dialog problems in the future.

This problem is caused by Homebrew "set[ting] the macOS keychain credential helper by default" [Formula/git.rb#L144](https://github.com/Homebrew/homebrew-core/blob/e997d9f5a0559f4ec5d4b576ce5123d8f79332e2/Formula/git.rb#L144).

Apple does not appear to set system-wide configurations on installation of its command line tools on macOS 10.14 or 10.15:

```shell
$ /usr/bin/git config --system --list
fatal: unable to read config file '/etc/gitconfig': No such file or directory
```

so the historic motivation for Homebrew configuring `credential.helper=osxkeychain` ([Formula/git.rb#L145](https://github.com/Homebrew/homebrew-core/blob/e997d9f5a0559f4ec5d4b576ce5123d8f79332e2/Formula/git.rb#L145) and #1815) seems to have disappeared. I've also checked on Arch Linux and Raspberry Pi OS (Debian) and they also report "fatal: unable to read ..."

Homebrew's setting system-wide `git` configurations on installation appears to be anomalous, certainly the historic benefit of alignment with Apple's practices appears to have been lost and Homebrew is now misaligned. More than that, the creation of this system-wide setting causes problems using Homebrew `git` interactively and non-interactively.

Could the setting of system configuration please be removed so that future installs (1) don't cause problems and (2) align with Apple's practices?

**Comment by carlocab** [comment]
It actually still does align with Apple's practices. 

If I move my `~/.config/git/config` elsewhere, and run
```
/usr/bin/git config --list
```
outside of a Git repository, I see
```
credential.helper=osxkeychain
```
This doesn't seem to be a consequence of my having a `/usr/local/etc/gitconfig`, as getting rid of that file changes nothing for `/usr/bin/git config --list`. (It does change `/usr/local/bin/git config --list`, though, as one might expect.)

To see why, note that
```
/usr/bin/git config --list --show-origin
```
should display
```
file:/Library/Developer/CommandLineTools/usr/share/git-core/gitconfig   credential.helper=osxkeychain
```
I think this makes it quite unlikely we'd be willing to remove this from the `git` formula.

**Comment by jamesquilty** [comment]
Thanks for the quick reply, I very much appreciate that!

> It actually still does align with Apple's practices.

 I stand corrected and can confirm that I do, indeed, see `file:/Library/Developer/CommandLineTools/usr/share/git-core/gitconfig   credential.helper=osxkeychain` in the output of `/usr/bin/git config --list --show-origin`.

Fair enough that, on the face of it, you'd be unlikely to remove this from the `git` formula, and thanks for the suggested workaround, I very much appreciate it. In the immediate term I'm going to have to follow that route.

I expect that if it was feasible to sign brew's `git` bottle with an Apple Developer ID, to avoid the "authenticity cannot be verified " modal dialog, then it would have been done already... but I'll be glad to be wrong on this point too 🙂

**Comment by carlocab** [comment]
I don't think it needs to be signed with an Apple Developer ID. You can try to codesign the binary with
```
codesign -f -s - "$(brew --prefix git)/libexec/git-core/git-credential-osxkeychain"
```

**Comment by jamesquilty** [comment]
Thanks for that, the `codesign` command executed on the command line without error or password request, and the `git-credential-osxkeychain` binary was modified. All good thus far, so I ran

```shell
$ git credential-osxkeychain get
host=github.com

```

which generated a dialog again _but_ instead of 

> The authenticity of "git-credential-osxkeychain" cannot be verified. To allow this enter the "login" keychain password.

 the dialog read

> To allow this enter the "login" keychain password.

Although the ultimate problem that a dialog is shown isn't fixed, the "authenticity can't be verified" part of the problem is resolved by application of `codesign`. I call that progress! 🙂 

So the question now is: why is brew's `git-credential-osxkeychain` tripping that dialog when Apple's version is not, given they are both (apparently) verified?

**Comment by carlocab** [comment]
No idea, but IMO Apple's `git` should absolutely be tripping that dialogue. It should definitely not be able to access your keychain without verification.

**Comment by jamesquilty** [comment]
Actually, after a bit of testing, I think that Apple's `git-credential-osxkeychain` was tripping the dialog &mdash; at the time the credentials were stored. The ACL display in Keychain Access is not particularly informative, and I don't think the `security` command is any better, so it's hard to trace where & when access has been allowed.

Thanks for your help, I'll use the workaround suggested.
