### ISSUE TITLE
globus-toolkit is not properly installed/linked

### ISSUE THREAD

**Issue by ntadej** [Homebrew/homebrew-core#7590]
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

globus-toolkit formula is not installed properly. A lot of files are installed in `/usr/local/Cellar/globus-toolkit/6.0.1477634051/libexec` which is then not linked and needs to be manually provided to other homebrew packages (e.g. nordugrid-arc).

**Comment by MikeMcQuaid** [comment]
@ntadej This isn't something we consider a bug but we'd accept a PR. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!
