### ISSUE TITLE
Bottle all `bottle :unneeded`

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-core#75943]
Everything that's `bottle :unneeded` ~has got to go!~ should be bottled. This can be done by creating a pull request removing the `bottle :unneeded` line and allowing the bottles to be committed as usual.

For bonus points, verify the checksums of all generated artefacts are the same and attempt to fix them up (or CC me and I'll give it a go).

---

[cho-m] Tracking the remaining:
- [x] g* - #79997
- [x] `civl` - #80077
- [x] `couchpotatoserver` - #80078
- [x] `golo` - #80154
- [x] `growly` - #80151
- [x] `gwt` - #80145
- [x] `i2p` - #80106
- [x] `idnits` - #80107
- [x] `iphotoexport` - #80108
- [x] `kobalt` - #80037
- [x] `payara` - #80114
- [x] `polynote` - #80105
- [x] `serveit` - #80080
- [x] `skinny` - #80152

**Comment by carlocab** [comment]
I wonder if it makes sense to define some sort of `skip_relocation` DSL in formulae to simplify the bottling of all the previously `bottle :unneeded` formulae.

This would also avoid needing to do things like this: #76394, where I do an `inreplace` in `install` to keep the bottles uniform, but undo that `inreplace` in `post_install` because it doesn't look like something keg-relocation should actually be changing.

**Comment by MikeMcQuaid** [comment]
> I wonder if it makes sense to define some sort of `skip_relocation` DSL in formulae to simplify the bottling of all the previously `bottle :unneeded` formulae.

I don't think a DSL but perhaps some sort of temporary hack in brew-test-bot for "fail CI unless this ends up as cellar :any or cellar :any_no_relocation" or "fail CI unless the checksums are identical"?

> This would also avoid needing to do things like this: #76394, where I do an `inreplace` in `install` to keep the bottles uniform, but undo that `inreplace` in `post_install` because it doesn't look like something keg-relocation should actually be changing.

I've commented there but TL;DR: we should fix that here.

To be clear: `all:` bottles are a nice goal to have but I don't think they are essential. In cases like that I'd rather see `bottle :unneeded` stick around a bit longer and we fix the root problem (that will undoubtedly be affecting other formulae too).

**Comment by MikeMcQuaid** [comment]
@caarlos0 have opened an issue for this in https://github.com/Homebrew/brew/issues/11302

**Comment by chenrui333** [comment]
heads up, I made [a label](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+label%3Abottle-up-everything+) for better filtering PRs on this epic work

**Comment by yurikoles** [comment]
Is there a good way or alternative for mass inreplace? In https://github.com/Homebrew/homebrew-core/pull/76312#issuecomment-854817217 I see 35 files with mention of `@@HOMEBREW_PREFIX@@` in Intel bottle.

**Comment by yurikoles** [comment]
To be honest, I don't get why `/usr/local/` is relocated only on Intel and being preserved on arm64.

**Comment by MikeMcQuaid** [comment]
> To be honest, I don't get why `/usr/local/` is relocated only on Intel and being preserved on arm64.

It's the prefix on intel and not on arm.

**Comment by cho-m** [comment]
Once #79997 is merged, the leftovers:
- [ ] `civl` - #80077
- [ ] `couchpotatoserver` - #80078
- [ ] `growly`
- [ ] `gwt` - #80145
- [ ] `i2p` - #80106
- [ ] `idnits` - #80107
- [ ] `iphotoexport` - #80108
- [ ] `kobalt` - #80037
- [ ] `payara` - #80114
- [ ] `polynote` - #80105
- [ ] `serveit` - #80080
- [ ] `skinny`

---

I had disabled `growly`, but we can probably still bottle by changing testcase to a something that exits early, like `growly --version`

Not sure what happened with `skinny` as I didn't see it in bulk PRs.

**Comment by MikeMcQuaid** [comment]
Done, great work and thanks for the help everyone ❤️
