### ISSUE TITLE
Freeciv has graphics bug

### ISSUE THREAD

**Issue by DDeanBrown** [Homebrew/homebrew-core#75993]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Dean@Mac-mini bin % brew config
HOMEBREW_VERSION: 3.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: d89eda09abbeae907eb88bd6d01dc9cde7ff0e19
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8f48f42d4dbe363597a29d6c77998e5239ab898c
Core tap last commit: 27 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4

Dean@Mac-mini bin % brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install and run freeciv

### What happened (include all command output)?

Installed OK, running freeciv-gtk3 gives warnings/errors -

`(freeciv-gtk3:2689): Gtk-WARNING **: 20:36:57.100: Theme parsing error: gtk.css:244:33: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(freeciv-gtk3:2689): Gtk-WARNING **: 20:36:57.126: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(freeciv-gtk3:2689): Gtk-WARNING **: 20:36:57.142: Error loading theme icon 'media-seek-backward' for stock: 

(freeciv-gtk3:2689): Gtk-WARNING **: 20:36:57.256: Error loading theme icon 'media-seek-backward' for stock: 

(freeciv-gtk3:2689): Gtk-WARNING **: 20:36:57.257: Error loading theme icon 'window-close' for stock: Icon 'window-close' not present in theme Adwaita
`

App runs, but is missing some graphic control widgets - up and down arrows and disclosure triangles.

### What did you expect to happen?

Hoping freeciv would run without bugs.

This issue is referenced in the closed issue #53288 - a comment there says -

 pjlsergeant commented on Apr 19, 2020

Hi @jonchang -- upgrading the client has indeed fixed the segfault, and the game is playable. However, there are many small missing pieces from the UI along with a lot of warnings to the console, which I believe are due to a missing gtk theme? Should this be a separate ticket or an appeal to upstream, or what?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install freeciv
./freeciv-gtk3

The bug may be in GTK3, not in homebrew. If that is the case, please revert the homebrew install of freeciv to build the GTK2 graphics client version of freeciv, which I have done (by using brew install -i freeciv, and configuring the freeciv make) and it works fine. The fix #7387 may have fixed the issue reported in #53288.
```

**Comment by carlocab** [comment]
This sounds like this needs to be reported upstream.

**Comment by DDeanBrown** [comment]
I tried MacPorts - it builds the freeciv-gtk2 client, which works fine. So more evidence that it would be OK for Homebrew to switch to building the freeciv gtk2 client, using the gtk+ package. MacPorts does offer a gtk3 package, so I installed that, then did some $PATH hacking, re-configured the makefile for freeciv, and built a freeciv-gtk3 client using the MacPorts gtk3 package - it has the same bug. So more evidence that it's a gtk3 issue.
More info - Homebrew gtk+3 package is version 3.24.29. Repro'd on MacOS 10.12 and 11.3. (Yes I know 10.12 isn't supported, but I got lucky.)

**Comment by carlocab** [comment]
Sounds like their gtk3 interface doesn't work very well. You might want to open a PR to switch `freeciv` to gtk2 for review.

**Comment by DDeanBrown** [comment]
sorry, I'm new to this - what does PR mean?

**Comment by carlocab** [comment]
PR = pull request. This guide may help: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

**Comment by tschoonj** [comment]
Have you tried install Adwaita-icon-theme?

```
brew install adwaita-icon-theme
```

**Comment by DDeanBrown** [comment]
Tried adwaita-icon-theme and it fixes the bug. Didn't know that existed. So no need to change to gtk2. Instead need to add a dependency on adwaita-icon-theme. Question is - add the dependency to freeciv or to gtk+3?

**Comment by Edord99** [comment]
#4

**Comment by carlocab** [comment]
Definitely on `freeciv`. `adwaita-icon-theme` depends on `gtk+3`, so making `gtk+3` depend on `adwaita-icon-theme` would create a circular dependency.

**Comment by DDeanBrown** [comment]
opened my first pull request - woo hoo! That guide was very good. Thanks for the help.
