### ISSUE TITLE
pqxx pkg-config file has wrong link instruction

### ISSUE THREAD

**Issue by wichert** [Homebrew/homebrew-core#7600]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? 

### Bug reports:

the pqxx library is installed as libpqxx-4.0.dylib, but the `pkgconfig --libs pqxx` output claims the right link option is `-lpqxx`. This results in linking errors - the correct option is `-lpqxx-4.0`.

```
$ brew gist-logs libpqxx
Error: No logs.
```

**Comment by ilovezfs** [comment]
```
iMac-TMP:~ joe$ ls -l /usr/local/Cellar/libpqxx/4.0.1_1/lib
total 1952
-r--r--r--  1 joe  admin  351288 Dec  6 13:10 libpqxx-4.0.dylib
-r--r--r--  1 joe  admin  642592 Jan 19  2013 libpqxx.a
lrwxr-xr-x  1 joe  admin      17 Jan 19  2013 libpqxx.dylib -> libpqxx-4.0.dylib
drwxr-xr-x  2 joe  admin     102 Dec  6 13:10 pkgconfig
iMac-TMP:~ joe$
```
should work due to the symlink.

**Comment by wichert** [comment]
Hm, that is interesting. It looks like my cmakefile is not picking up the -L flag for some reason.
