### ISSUE TITLE
Error: undefined method `desc' for AllureCommandline:Class

### ISSUE THREAD

**Issue by dmacd868** [Homebrew/homebrew-core#7602]
### Bug reports:

Following instructions to install on a Mac on http://wiki.qatools.ru/display/AL/Allure+Commandline

$ brew tap qatools/formulas 
$ brew install allure-commandline

The first line succeeds but the second line throws the error in the subject line. Plese see below.

> brew tap qatools/formulas 
Cloning into '/usr/local/Library/Taps/qatools/homebrew-formulas'...
remote: Counting objects: 44, done.
remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
Unpacking objects: 100% (44/44), done.
Checking connectivity... done.
Tapped 1 formula
> brew install allure-commandline
Error: undefined method `desc' for AllureCommandline:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:4:in `<class:AllureCommandline>'
/usr/local/Library/Taps/qatools/homebrew-formulas/Formula/allure-commandline.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
>

**Comment by ilovezfs** [comment]
Sorry but you have not followed the requested steps on the [Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by MikeMcQuaid** [comment]
> # Please follow the general troubleshooting steps first:
>
> - [ ] Ran `brew update` and retried your prior step?
> - [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

Pretty sure these will solve your problem.
