### ISSUE TITLE
Skipfish config doesn't work out of the box

### ISSUE THREAD

**Issue by HipsterJazzbo** [Homebrew/homebrew-core#7603]
Skipfish builds correctly, however it is not configured out of the box in a way that works without modification. The paths to the signature files are wrong. I had to do the following to get it to run:

1. Use the `-z /usr/local/Cellar/skipfish/2.10b_1/libexec/signatures/signatures.conf` option to point it at the correct `signature.conf` file (it was looking for the default `signatures/signatures.conf`, without the full path)
2. Modify the `signatures.conf` file to specify the full path to its included files (was again just looking for `signatures/mime.sigs`, I had to add the rest of the path).

I'm not familiar with how to build/modify homebrew formulae, otherwise I'd open a PR.

**Comment by ilovezfs** [comment]
The skipfish formula doesn't have a test. Can you provide a few examples of how to tell whether it's working or not working?

**Comment by MikeMcQuaid** [comment]
> I'm not familiar with how to build/modify homebrew formulae, otherwise I'd open a PR.

[This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by MikeMcQuaid** [comment]
Closing due to no response.
