### ISSUE TITLE
Warning: Calling MacOS.clang_build_version is deprecated!

### ISSUE THREAD

**Issue by zhangnfelix** [Homebrew/homebrew-core#7608]
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for pandoc: ghc, cabal-install, gmp
==> Installing pandoc dependency: ghc
==> Downloading https://downloads.haskell.org/~ghc/7.10.3/ghc-7.10.3b-src.tar.bz2
Already downloaded: /Users/zhangn/Library/Caches/Homebrew/ghc-7.10.3b.tar.bz2
Warning: Calling MacOS.clang_build_version is deprecated!
Use DevelopmentTools.clang_build_version instead.
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:62:in `install'
Please report this to the homebrew/core tap!

**Comment by ilovezfs** [comment]
I think you may be affected by https://twitter.com/MacHomebrew/status/763686348041641984.

Please follow the instructions there.
