### ISSUE TITLE
GNU parallel fails with option --csv, missing Text::CSV module

### ISSUE THREAD

**Issue by maroneze** [Homebrew/homebrew-core#76163]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config output:

HOMEBREW_VERSION: 3.1.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 94ce3236a517dfae6b492dcb4fd6b726a6175e8f
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3636c4df1c4e17f46681d92422e7c51d09831ac2
Core tap last commit: 6 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 11.0 build 1100
Git: 2.21.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.6-x86_64
CLT: 11.0.0.33.17
Xcode: N/A
```

brew doctor output:

```
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

**Note:** I *cannot* upgrade to Big Sur due to company policy, and the above message seems to force it. So I ticked the "resolved all warnings" despite it. It does not seem relevant to my issue (which is due to missing dependencies in the `parallel` package), but if this is a problem, feel free to close the issue.
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run `parallel --csv`.

### What happened (include all command output)?

Got the following error:

```
Can't locate object method "new" via package "Text::CSV" (perhaps you forgot to load "Text::CSV"?) at /usr/local/bin/parallel line 1797.
```

### What did you expect to happen?

`parallel` should work with option `--csv`.

That option seems to require the `Text::CSV` Perl package, which should probably be a dependency for the `parallel` package.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install parallel
parallel --csv
```
```

**Comment by maroneze** [comment]
A colleague just told me that doing `cpan -i Text::CSV` works. I had previously installed `brew install perl`, in case it might install that package, but it didn't suffice. With the `cpan` command it seems to work. So, in case it's too complicated to require it as a dependency, I believe a post-installation message such as "If you intend to use option --csv, consider running `cpan -i Text::CSV`" might be enough to help users.

**Comment by cho-m** [comment]
https://www.gnu.org/software/parallel/man.html#DEPENDENCIES

> ### DEPENDENCIES
> GNU **parallel** uses Perl, and the Perl modules Getopt::Long, IPC::Open3, Symbol, IO::File, POSIX, and File::Temp.
> 
> For **--csv** it uses the Perl module Text::CSV.
> 
> For remote usage it uses rsync with ssh.

---

It is probably worth checking if some of these Perl modules should be added as `resource` blocks in the Homebrew Formula.

**Comment by carlocab** [comment]
Some of these might also already be provided by system `perl`. `parallel` has a `configure` script that the formula uses, presumably to check that the required dependencies are met, so I'd guess most of those modules do not need to be added as `resource`s.

**Comment by Bo98** [comment]
> Getopt::Long, IPC::Open3, Symbol, IO::File, POSIX, and File::Temp.

All look to be a part of the standard brewed Perl install, so I think it's only `Text::CSV` that needs handling.
