### ISSUE TITLE
UPX Installation failed on macOS Bigsur 

### ISSUE THREAD

**Issue by Zabrane** [Homebrew/homebrew-core#76161]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew doctor                                                                                                                                                                  
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ctags
  upx
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install UPX from HEAD

### What happened (include all command output)?

```
$ sw_vers                                                                                                                                                                      
ProductName:    macOS
ProductVersion: 11.2.3
BuildVersion:   20D91

$ brew install upx --HEAD                                                                                                                                                      
==> Downloading https://github.com/upx/upx/commit/51f69a20e0287904398bbf4c72ba2f809a0b0850.patch?full_index=1
Already downloaded: /Users/zab/Library/Caches/Homebrew/downloads/828bed0793519b45dcaa13c6897f0e919e7023816880e2d770a3e5ea3129dbc8--51f69a20e0287904398bbf4c72ba2f809a0b0850.patch
==> Cloning https://github.com/upx/upx.git
Updating /Users/zab/Library/Caches/Homebrew/upx--git
==> Checking out branch devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.
HEAD is now at 2dae2a3 Merge pull request #491 from bitraid/fix-rebuild-relocs
Entering 'src/lzma-sdk'
/Users/zab/Library/Caches/Homebrew/upx--git/src/lzma-sdk
==> Patching
==> Applying 51f69a20e0287904398bbf4c72ba2f809a0b0850.patch
patching file src/p_mach.cpp
Hunk #1 FAILED at 1194.
1 out of 1 hunk FAILED -- saving rejects to file src/p_mach.cpp.rej

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

### What did you expect to happen?

Install UPX from HEAD

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install upx --HEAD    
```
```

**Comment by MikeMcQuaid** [comment]
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Twitter or any other official channels.

**Comment by carlocab** [comment]
Sorry, but head builds are not supported. That's why you see

> Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

We'll review a PR that scopes the patch to a stable build.
