### ISSUE TITLE
terraform@0.12 unnecessarily requires an OS upgrade to Catalina

### ISSUE THREAD

**Issue by lange1** [Homebrew/homebrew-core#76296]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 94ce3236a517dfae6b492dcb4fd6b726a6175e8f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5f8dbcc6187ecc8f7fe81631455f70c64cabaf03
Core tap last commit: 55 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs -nw
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 10.0 build 1001
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: N/A

---

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

[Note: this message persists even after I run the suggested mitigation.]
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I need to install the newest version of Terraform 0.12 to mitigate a recent security vulnerability in it. The project on which I am working is pinned to terraform 0.12, and the company for which I work requires MacOS Mojave on our systems, so upgrading is not an option at this time.

### What happened (include all command output)?

The terraform version 0.12.31 bottle introduced a new requirement of MacOS Catalina, so it refused to install when run on Mojave.

None of the other supported versions of terraform (0.11, 0.12, 0.15) have introduced this OS requirement, nor is the requirement a part of the upstream terraform project.

### What did you expect to happen?

Given that Mojave is still a supported version of MacOS in Homebrew, and Catalina is *not* a requirement for Terraform, I expected to be able to install the security update on Mojave.

### Step-by-step reproduction instructions (by running `brew` commands)

The formula `Formula/terraform@0.12.rb` was updated in commit `e0ba84cd630906b70ef2c8219e6e08931d18a6cf` to require MacOS Catalina. This was a bad thing to do to users given that this was a security update.

On my local system, I have taken the version of the file from `e2c833d326c45d9aaf4e26af6dd8b2f31564dc04` and updated the `url` and `sha256` fields. Ignoring the `bottle` fields, this new file has the following diff from what is currently in master:

```
-  depends_on "go" => :build
-  depends_on macos: :catalina
+  depends_on "go@1.13" => :build
```

I have built and installed using this local formula, and terraform@0.12 works exactly as expected on Mojave. I realize that having a build dependency on an unsupported version of golang is not ideal (but not a dealbreaker, as terraform@0.13 does it), but I believe that is better than the alternative of forcing users of a supported OS version to choose between running an insecure version of terraform vs upgrading their entire OS.

**Comment by carlocab** [comment]
I don't think building it with `go@1.13` is acceptable -- that would make it impossible to build on ARM, for example.

If you wish, you can host your own version of `terraform@0.12` in your own tap. Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by Bo98** [comment]
I wonder if https://github.com/hashicorp/terraform/commit/cd65b28da051174a13ac76e54b7bb95d3051255c cleanly applies, which would fix the issue.

**Comment by MikeMcQuaid** [comment]
> and the company for which I work requires MacOS Mojave on our systems, so upgrading is not an option at this time.

Note: Homebrew will drop support for Mojave as soon as we switch our CI over to Big Sur + 1 (likely in one of the later betas or when it's released). You have less than 6 months to migrate.

I'm closing this out because this isn't a bug, as mentioned above, we'll consider accepting PRs to improve this.
