### ISSUE TITLE
imagemagick@6 6.9.12-9 -> 6.9.12-10 is failing with "Error: Couldn't parse manifest JSON."

### ISSUE THREAD

**Issue by mileslane** [Homebrew/homebrew-core#76336]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 227445ece9414a82aa8929b91ca2e0cca28a561b
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5a0721783a5e8d6709340be6331d978950c68320
Core tap last commit: 33 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A

Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am attempting to run the current release of imagemagick@6 for development work.

### What happened (include all command output)?

==> Upgrading imagemagick@6 6.9.12-9 -> 6.9.12-10
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/6/manifests/6.9.12-10
Already downloaded: /Users/mileslane/Library/Caches/Homebrew/downloads/e8bebc10cdf8d4fd964da0cf7d7b46138a99c39d0107d3271c77b6195cddde52--imagemagick@6-6.9.12-10.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/imagemagick/6/blobs/sha256:9f21f2abb29a90e3ad6365a7071c15094e8c1fccb1213a5f4a045dcfd2b5e4e5
Already downloaded: /Users/mileslane/Library/Caches/Homebrew/downloads/527604ae910b1ad3e7ea8f8d243ea0117b91bd005321c5d1fa78a6b9208f4be3--imagemagick@6--6.9.12-10.catalina.bottle.tar.gz
==> Pouring imagemagick@6--6.9.12-10.catalina.bottle.tar.gz
Error: Couldn't parse manifest JSON.

### What did you expect to happen?

I expected the package to successfully install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update && brew upgrade
```

**Comment by carlocab** [comment]
Your manifest probably wasn't downloaded correctly. Possibly intercepted by a firewall or similar.

See https://github.com/Homebrew/homebrew-core/issues/75997.

What's the output of
```
file /Users/mileslane/Library/Caches/Homebrew/downloads/e8bebc10cdf8d4fd964da0cf7d7b46138a99c39d0107d3271c77b6195cddde52--imagemagick@6-6.9.12-10.bottle_manifest.json
file /Users/mileslane/Library/Caches/Homebrew/downloads/527604ae910b1ad3e7ea8f8d243ea0117b91bd005321c5d1fa78a6b9208f4be3--imagemagick@6--6.9.12-10.catalina.bottle.tar.gz
```
?

**Comment by mileslane** [comment]
Thanks for you reply!

- /Users/mileslane/Library/Caches/Homebrew/downloads/e8bebc10cdf8d4fd964da0cf7d7b46138a99c39d0107d3271c77b6195cddde52--imagemagick@6-6.9.12-10.bottle_manifest.json: data
- /Users/mileslane/Library/Caches/Homebrew/downloads/527604ae910b1ad3e7ea8f8d243ea0117b91bd005321c5d1fa78a6b9208f4be3--imagemagick@6--6.9.12-10.catalina.bottle.tar.gz: gzip compressed data, was "imagemagick@6-bottle.tar", last modified: Thu Apr 29 02:49:27 2021, from Unix, original size modulo 2^32 29900800

**Comment by mileslane** [comment]
Thank you!  I ran  `brew cleanup --prune=all` and `brew upgrade imagemagick@6` and all is working well now. 
Have a great day!

**Comment by carlocab** [comment]
Yes, it was a problem with your manifest file:
```
/Users/mileslane/Library/Caches/Homebrew/downloads/e8bebc10cdf8d4fd964da0cf7d7b46138a99c39d0107d3271c77b6195cddde52--imagemagick@6-6.9.12-10.bottle_manifest.json: data
```
should say
```
JSON data
```

Closing this as it's now resolved.
