### ISSUE TITLE
mopidy fails to build (?) on 10.12.1

### ISSUE THREAD

**Issue by jgillman** [Homebrew/homebrew-core#7648]
Steps I took:

- [x] Ran `brew update` (twice)
- [x] Ran `brew doctor`
- [x] Made a [Gist of the output of the commands][gist]
  - `brew config`
  - `brew doctor`
  - `brew info gst-plugins-good`
  - `brew install mopidy`

This is a fairly new install of `brew` as I only got this machine a week ago, no issues with old versions laying around or anything.

# Bug Report

I used `brew tap mopidy/mopidy` and then `brew install mopidy` to install which started installing all of the necessary dependencies. So far so good. When it got to the `gst-plugins-good` dep it seems to have installed it (see my `brew info gst-plugins-good` output in the [gist]) but then I'm booted back to my prompt after the line:

```
==> Installing dependencies for mopidy/mopidy/mopidy: gst-plugins-good
```

No feedback about whether or not it succeeded, and it does not continue to install `mopidy`. The command exits with a status of `0` (checked with `echo $?` after I'm booted back to the prompt).

---

At this point I've exhausted my debugging ideas. Happy to try anything else out to get more info as requested!

[gist]: https://gist.github.com/jgillman/7a4196f8b36d01700798edfac9e3d9cc

**Comment by MikeMcQuaid** [comment]
> I used brew tap mopidy/mopidy and then brew install mopidy

Please report this to their tap instead or provide a minimal formula that reproduces this issue, thanks.

**Comment by jgillman** [comment]
@MikeLund Will do! Thanks for the direction.

**Comment by jgillman** [comment]
Ah, just a note for myself or any other traveler in the future:

This seems to be the same issue in the mopidy homebrew formula repo: https://github.com/mopidy/homebrew-mopidy/issues/12

I'll leave my solution in there.
