### ISSUE TITLE
Error executing command (brew install ta-lib )

### ISSUE THREAD

**Issue by amirzarbakhsh** [Homebrew/homebrew-core#76498]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew install ta-lib
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I wanted to run the above command line to set up the library to install lib

### What happened (include all command output)?

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "ta-lib".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...

### What did you expect to happen?

I was expecting to see the image below

[https://d1rwhvwstyk9gu.cloudfront.net/2019/12/brew_install.png](https://d1rwhvwstyk9gu.cloudfront.net/2019/12/brew_install.png)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ta-lib
```

**Comment by SMillerDev** [comment]
> brew install ta-lib
This is definitely not the output that was requested. This can be reopened when the required information is provided.

**Comment by amirzarbakhsh** [comment]
Yes, this is the output I need according to what happened when installing the ta-lib library in the following link (How to install Ta-Lib in Python)  :

https://blog.quantinsti.com/install-ta-lib-python/

**Comment by SMillerDev** [comment]
There is no way that
> `brew gist-logs <formula>` OR (`brew config` AND `brew doctor`)

Outputted 
> brew install ta-lib

As you said it did

**Comment by gromgit** [comment]
@amirzarbakhsh To be clear, show us the output of `brew config` and `brew doctor`. There's no way anyone can help resolve your problem if we don't even know whether your Homebrew setup is complete, current and correct.

**Comment by amirzarbakhsh** [comment]
brew doctor :

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m-config
  /Library/Frameworks/Python.framework/Versions/3.7/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config
  /Users/amir/opt/anaconda3/bin/icu-config
  /Users/amir/opt/anaconda3/bin/krb5-config
  /Users/amir/opt/anaconda3/bin/freetype-config
  /Users/amir/opt/anaconda3/bin/xslt-config
  /Users/amir/opt/anaconda3/bin/libpng16-config
  /Users/amir/opt/anaconda3/bin/libpng-config
  /Users/amir/opt/anaconda3/bin/xml2-config
  /Users/amir/opt/anaconda3/bin/python3-config
  /Users/amir/opt/anaconda3/bin/curl-config
  /Users/amir/opt/anaconda3/bin/ncursesw6-config
  /Users/amir/opt/anaconda3/bin/pcre-config
  /Users/amir/opt/anaconda3/bin/python3.8-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/amir/.bash_profile

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/easy_install-3.9

**Comment by amirzarbakhsh** [comment]
brew config :

HOMEBREW_VERSION: 3.1.5-18-g4f4fb49
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4f4fb49481685208c5756c897944ae28757ca5c7
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: HEAD
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A

**Comment by carlocab** [comment]
This is your problem:
```
Core tap HEAD: (none)
```
`brew doctor` already suggests a way of fixing it:
```
Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
git -C $(brew --repo homebrew/core) checkout master
```
If that doesn't work, try
```
rm -rf $(brew --repo homebrew/core)
brew update
```

**Comment by amirzarbakhsh** [comment]
Gives the following message :

fatal: Could not resolve HEAD to a revision
Already up-to-date.

**Comment by amirzarbakhsh** [comment]
Ahhh why not install this damn library :/

[https://ibb.co/dWy5Bhx](https://ibb.co/dWy5Bhx)

**Comment by carlocab** [comment]
Which command gives that message? You really need to be more specific, because not doing so is making it more difficult to help you.

**Comment by amirzarbakhsh** [comment]
Brew update command

**Comment by carlocab** [comment]
And which commands did you run?

**Comment by carlocab** [comment]
Sorry, but trying to help you is like pulling teeth here, so I'm leaving one last suggestion and then unsubscribing from this thread:
```
rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
brew update
```
