### ISSUE TITLE
leveldb leads to a malloc error

### ISSUE THREAD

**Issue by clavichord93** [Homebrew/homebrew-core#7652]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

leveldb 1.19 leads to a malloc error on macOS Sierra. However, compiling leveldb 1.19 by myself does have this issue. Refer to dimilar's reply at [this](https://github.com/BVLC/caffe/issues/4783) for details.

**Comment by MikeMcQuaid** [comment]
> Uncomment USE_LEVELDB := 0. There is an incompatibility with macOS Sierra and LevelDB and you want to disable it.

This sounds like it's an upstream issue with LevelDB and should be reported to them unless there's a formula build failure. If there's changes that can be made to our formulae we'll gladly accept pull requests.

**Comment by clavichord93** [comment]
>the problem is related to leveldb. If leveldb is installed with brew, by default, it depends on the google's gperftools, which consists of a module named libtcmalloc.dylib. On macOS sierra, this causes the malloc_zone_unregister problem.
>
>therefore, there are two solutions:
>
>1. comment out the line USE_LEVELDB := 0 in Makefile.config
>2. download the leveldb(v1.9) and compile it to replace the original one.

It is not an upstream issue. Leveldb doesn't need gperftools to build. I build leveldb manually without gperftools doesn't lead to this malloc issue.

**Comment by ilovezfs** [comment]
@clavichord93 isn't the right answer to fix gperftools?

**Comment by clavichord93** [comment]
@ilovezfs But leveldb doesn't depend on gperftools.
