### ISSUE TITLE
apache-arrow segfaults on intel

### ISSUE THREAD

**Issue by jeroen** [Homebrew/homebrew-core#76537]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.1.5-18-g4f4fb49-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4f4fb49481685208c5756c897944ae28757ca5c7
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bd0335db62625b9e24fa1746f9558e607a9baa5d
Core tap last commit: 59 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.RW7zMPlQKm/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4
XQuartz: 2.7.11 => /opt/X11

brew doctor:
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run an application that uses `apache-arrow`.

### What happened (include all command output)?

It crashes. Perhaps due to unsupported SIMD extensions. Tried this on both MacOS 10.15 and 11.3.

There is an upstream discussion if this is due to improper hardware detection but somehow this only happens in homebrew, and arrow [should detect runtime capabilities](https://github.com/apache/arrow/pull/9657/files)

I can only reproduce this with the homebrew bottle. It does not happen when I compile apache-arrow manually from source with debug flags, using the same features as the recipe, which makes it tricky to debug.

### What did you expect to happen?

No crash.

### Step-by-step reproduction instructions (by running `brew` commands)

Example application:

```cpp
#include <iostream>
#include <arrow/api.h>
#include <arrow/compute/api.h>

int main(int, char**) {
  std::shared_ptr<arrow::Array> array;
  arrow::Int64Builder builder;
  if (!builder.Append(1).ok()) return 1;
  if (!builder.Append(2).ok()) return 1;
  if (!builder.Finish(&array).ok()) return 1;
  auto result = arrow::compute::CallFunction("sum", {array});
  std::cout << result.ValueOrDie().scalar()->ToString() << std::endl;
  return 0;
}
```

Compile with:

```shell
brew install apache-arrow
clang++ -std=c++11 test.cpp $(pkg-config --cflags --libs arrow)
```

And run:

```shell
#./a.out
zsh: illegal hardware instruction  ./a.out
```

Does homebrew pass any special compiler flags that affect which SIMD extensions get enabled?
Thanks for any pointers!

@ianmcook @nealrichardson

**Comment by carlocab** [comment]
Can't reproduce.
```
❯ cat test.cpp
#include <iostream>
#include <arrow/api.h>
#include <arrow/compute/api.h>

int main(int, char**) {
  std::shared_ptr<arrow::Array> array;
  arrow::Int64Builder builder;
  if (!builder.Append(1).ok()) return 1;
  if (!builder.Append(2).ok()) return 1;
  if (!builder.Finish(&array).ok()) return 1;
  auto result = arrow::compute::CallFunction("sum", {array});
  std::cout << result.ValueOrDie().scalar()->ToString() << std::endl;
  return 0;
}
❯ clang++ -std=c++11 test.cpp $(pkg-config --cflags --libs arrow)
❯ ./a.out
3
```

**Comment by jeroen** [comment]
@carlocab are you running on intel or M1? Does your processor have AVX512?

**Comment by carlocab** [comment]
Intel. Yes, I believe it does support AVX512.
```
❯ sysctl -a | grep machdep.cpu.leaf7_features
machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET SGX BMI1 AVX2 FDPEO SMEP BMI2 ERMS INVPCID FPU_CSDS AVX512F AVX512DQ RDSEED ADX SMAP AVX512IFMA CLFSOPT IPT AVX512CD SHA AVX512BW AVX512VL AVX512VBMI UMIP PKU GFNI VAES VPCLMULQDQ AVX512VNNI AVX512BITALG AVX512VPOPCNTDQ RDPID SGXLC FSREPMOV MDCLEAR IBRS STIBP L1DF ACAPMSR SSBD
```

**Comment by nealrichardson** [comment]
Our investigation (on https://issues.apache.org/jira/browse/ARROW-12587) suggests that AVX512 code is being run even though the machine may not support it. Arrow does support runtime dispatch to various SIMD code paths, so we're wondering if somehow the AVX2 code is getting optimized to AVX512.

**Comment by carlocab** [comment]
The compiler shims should be passing `-march=nehalem` to `clang`, so I don't know why those optimisations are happening.

**Comment by carlocab** [comment]
One of the ARM runners was idling, so I tested this on that. No segfault:
```
brew@HMBRW-A-001-M1-006 /tmp % ./a.out
3
brew@HMBRW-A-001-M1-006 /tmp % file a.out
a.out: Mach-O 64-bit executable arm64
```

**Comment by ianmcook** [comment]
As described in the discussion at https://issues.apache.org/jira/browse/ARROW-12587, I observed this illegal instruction error both when installing the pre-built bottle with `brew install apache-arrow` and when building from source locally with `brew install --build-from-source apache-arrow` on a Mac running Big Sur with an Intel processor that does not support AVX512. The error does not happen when running the same `cmake` and `make` commands outside of `brew`.

**Comment by carlocab** [comment]
Since you built `apache-arrow` from source, you can check the logs for the exact compiler commands that `brew` ran while building. The logs should be in `~/Library/Logs/Homebrew/apache-arrow`. It should also show a record of compilation flags that were added, or intercepted and replaced.

**Comment by ianmcook** [comment]
@carlocab thanks for the tip. I found these lines in `01.cmake.cc`:
```
clang++ called with: -DCXX_SUPPORTS_AVX512 -march=skylake-avx512 -mbmi2 -mavx512f -mavx512cd -mavx512vl -mavx512dq -mavx512bw -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -MD -MT CMakeFiles/cmTC_8a09b.dir/src.cxx.o -MF CMakeFiles/cmTC_8a09b.dir/src.cxx.o.d -o CMakeFiles/cmTC_8a09b.dir/src.cxx.o -c /tmp/apache-arrow-20210504-8671-1nk57rs/apache-arrow-4.0.0/build/CMakeFiles/CMakeTmp/src.cxx
superenv removed:  -march=skylake-avx512 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
superenv added:    -pipe -w -Os -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/llvm/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openblas/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include
superenv executed: clang++ -pipe -w -Os -march=nehalem -DCXX_SUPPORTS_AVX512 -mbmi2 -mavx512f -mavx512cd -mavx512vl -mavx512dq -mavx512bw -MD -MT CMakeFiles/cmTC_8a09b.dir/src.cxx.o -MF CMakeFiles/cmTC_8a09b.dir/src.cxx.o.d -o CMakeFiles/cmTC_8a09b.dir/src.cxx.o -c /tmp/apache-arrow-20210504-8671-1nk57rs/apache-arrow-4.0.0/build/CMakeFiles/CMakeTmp/src.cxx -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/llvm/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openblas/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include

clang++ called with: -march=skylake-avx512 -mbmi2 -mavx512f -mavx512cd -mavx512vl -mavx512dq -mavx512bw -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_8a09b.dir/src.cxx.o -o cmTC_8a09b
superenv removed:  -march=skylake-avx512 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
superenv added:    -pipe -w -Os -march=nehalem -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/llvm/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openblas/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/openblas/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/sqlite/lib -L/usr/local/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
superenv executed: clang++ -pipe -w -Os -march=nehalem -mbmi2 -mavx512f -mavx512cd -mavx512vl -mavx512dq -mavx512bw -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_8a09b.dir/src.cxx.o -o cmTC_8a09b -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/llvm/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openblas/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/openblas/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/sqlite/lib -L/usr/local/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries -Wl,-headerpad_max_install_names
```

Arrow sets both `-DCXX_SUPPORTS_AVX512` and `-march=skylake-avx512`.  `superenv` removes  `-march=skylake-avx512` and adds `-march=nehalem`, but `-DCXX_SUPPORTS_AVX512` remains. I think that might be the source of the error.

Full logs: [apache-arrow.zip](https://github.com/Homebrew/homebrew-core/files/6418974/apache-arrow.zip)

**Comment by ianmcook** [comment]
This seems similar to the issue at https://github.com/Homebrew/brew/issues/10078

**Comment by carlocab** [comment]
Try applying this patch:
```diff
diff --git a/Formula/apache-arrow.rb b/Formula/apache-arrow.rb
index b254f71726d..d1cd24d183f 100644
--- a/Formula/apache-arrow.rb
+++ b/Formula/apache-arrow.rb
@@ -33,6 +33,7 @@ class ApacheArrow < Formula
   depends_on "zstd"
 
   def install
+    ENV.permit_arch_flags
     # link against system libc++ instead of llvm provided libc++
     ENV.remove "HOMEBREW_LIBRARY_PATHS", Formula["llvm"].opt_lib
     args = %W[
```
Let me know if it helps.

**Comment by ianmcook** [comment]
@carlocab that had no effect; the error still occurred and the lines from `01.cmake.cc` appeared the same as above

**Comment by carlocab** [comment]
Oh, right. `permit_arch_flags` allows `-arch` flags but not `-march` flags. ...though I'm not sure why it should allow `-arch` but not `-march`.

**Comment by carlocab** [comment]
In addition to the last patch to `apache-arrow.rb`, please also apply this one:
```diff
diff --git a/Library/Homebrew/shims/super/cc b/Library/Homebrew/shims/super/cc
index a54b2f900..747477c4e 100755
--- a/Library/Homebrew/shims/super/cc
+++ b/Library/Homebrew/shims/super/cc
@@ -146,7 +146,7 @@ class Cmd
 
     loop do
       case arg = enum.next
-      when "-arch"
+      when "-arch", "-march"
         if permit_arch_flags?
           args << arg << enum.next
         else
```
You can find this file at
```
$(brew --repo)/Library/Homebrew/shims/super/cc
```

**Comment by carlocab** [comment]
> Oh, right. `permit_arch_flags` allows `-arch` flags but not `-march` flags. ...though I'm not sure why it should allow `-arch` but not `-march`.

Ah, right. `-arch` is for passing things like `-arch x86_64`, and I think `ENV.permit_arch_flags` comes from `brew` trying to support universal builds.

**Comment by ianmcook** [comment]
Thanks; I'll try that tomorrow and let you know, and we'll look for immediate workarounds that won't require changes to Homebrew

**Comment by carlocab** [comment]
No problem. I've now read through all of https://github.com/open-mpi/ompi/issues/8306, and it seems Open MPI also used to pass `-march=skylake-avx512` to the compiler as a way of detecting CPU features, and it looks like Arrow is doing the same thing here. Their fix (linked in the issue) might help.

**Comment by carlocab** [comment]
Sorry, I think I totally mislead you with my suggested patch in https://github.com/Homebrew/homebrew-core/issues/76537#issuecomment-831682973. This is the right one, I think:
```diff
diff --git a/Library/Homebrew/shims/super/cc b/Library/Homebrew/shims/super/cc
index a54b2f900..66b1d9cba 100755
--- a/Library/Homebrew/shims/super/cc
+++ b/Library/Homebrew/shims/super/cc
@@ -173,7 +173,7 @@ class Cmd
 
     case arg
     when /^-g\d?$/, /^-gstabs\d+/, "-gstabs+", /^-ggdb\d?/,
-      /^-march=.+/, /^-mtune=.+/, /^-mcpu=.+/,
+      /^-mtune=.+/, /^-mcpu=.+/,
       /^-O[0-9zs]?$/, "-fast", "-no-cpp-precomp",
       "-pedantic", "-pedantic-errors", "-Wno-long-double",
       "-Wno-unused-but-set-variable"
@@ -272,7 +272,6 @@ class Cmd
     args << "-pipe"
     args << "-w" unless configure?
     args << "-#{ENV["HOMEBREW_OPTIMIZATION_LEVEL"]}"
-    args.concat(optflags)
     args.concat(archflags)
     args << "-std=#{@arg0}" if /c[89]9/.match?(@arg0)
     args
```

**Comment by ianmcook** [comment]
Thanks @carlocab—the patch in https://github.com/Homebrew/homebrew-core/issues/76537#issuecomment-831682973 had no effect but the patch in https://github.com/Homebrew/homebrew-core/issues/76537#issuecomment-831701483 solved it. 

Do you think something along these lines could be developed into a Homebrew/brew PR, perhaps controlled by `ENV.permit_march_flags`?

**Comment by carlocab** [comment]
I have some related changes I've been wanting to make to the shims that I could possibly combine here. Note, however, that I think we're generally quite conservative about changes to the compiler shims (they've worked quite well for a lot of formulae for a long time), so chances are that we'll need a different fix for `apache-arrow`.

**Comment by carlocab** [comment]
This is the related change I was referring to: https://github.com/Homebrew/brew/pull/11201

Could you explain why `-march` flag filtering is breaking `apache-arrow`? Does it use those flags to test the compiler in some way?

**Comment by ianmcook** [comment]
@carlocab thank you

@edponce is looking into why exactly the `-march` replacement is causing these illegal instruction errors

**Comment by edponce** [comment]
Based on my investigation it seems the *superenv* module in Homebrew uses different logic when creating the *configure* flags and the *make* flags. A possible solution is to set environment variable *HOMEBREW_ARCHFLAGS* to the desired march (refer to https://github.com/Homebrew/homebrew-core/pull/65296#issuecomment-735372600). Given that order of compiler flags matter (commonly the last flag is used when duplicates are present), we might be able to inject common flags for *configure* and *make* steps.

Another alternative is to disable AVX or above for this configuration (Homebrew and Big Sur) but this is not a desirable action.

**Comment by ianmcook** [comment]
Unfortunately `HOMEBREW_ARCHFLAGS` won't solve this because Arrow's CMake scripts create multiple `build.make` files specifying file-level compile flags. Only a very small number of these file-level flags should include `-march=skylake-avx512`. If we apply that flag across the board, the build fails.

@carlocab one possibility might be to use `inreplace` to modify the `build.make` files to undo a few of the flags changed by `superenv`. But I'm having trouble understanding where exactly the make files that are modified by `shims/super/cc` are written to disk.  Do you know where these are written?

**Comment by carlocab** [comment]
> But I'm having trouble understanding where exactly the make files that are modified by `shims/super/cc` are written to disk. Do you know where these are written?

The `build` directory is the working directory after invoking CMake, so you can just call `inreplace` on files relative from there.

> Do you think something along these lines could be developed into a Homebrew/brew PR, perhaps controlled by `ENV.permit_march_flags`?

We use `-march` flag filtering in order to make sure that the bottles we build work on a user's machine even when their is older than the one we built the bottle on. If we remove `-march` flag filtering for `apache-arrow`, will it still work on a Nehalem processor? That is the oldest CPU we support.

It would help if you could test this. To do so, build a bottle on a machine running on Skylake (or newer) using
```
brew install --build-bottle apache-arrow
brew bottle apache-arrow
```
this will create a bottle tarball in your working directory, which you can install in an older machine for testing (just `brew install ./apache-arrow.bottle.tar.gz`).

**Comment by ianmcook** [comment]
>We use -march flag filtering in order to make sure that the bottles we build work on a user's machine even when their is older than the one we built the bottle on. If we remove -march flag filtering for apache-arrow, will it still work on a Nehalem processor? 

In the case of Apache Arrow, yes. In the few places where Arrow's CMake scripts add AVX512 compiler flags, we really only want to know if the compiler can compile them. At runtime, Arrow detects whether or not the CPU supports AVX512 and will not attempt to run any AVX512 instructions if it does not. This works fine everywhere but with Homebrew unfortunately.

**Comment by carlocab** [comment]
Do you mind testing this using the procedure I describe above? I want to be certain that this fixes things before I propose more changes to our compiler shims.

If you don't have a new enough machine to build a bottle, I can build one for you as long as you have something to test it on.

Do we have any alternatives other than patching generated `Makefile`s on the fly, or deactivating features wholesale?

**Comment by ianmcook** [comment]
Thanks! Yes, I will test this soon

I believe our immediate options are:
- Patch the `superenv`-modified makefiles with `inreplace`. (I'm struggling with this because the superenv changes aren't appearing there after the `cmake` step; I added a ` sleep()` after `cmake` and before `make` to give me time to grab the makefiles files and look at them, but I can't see any `-march=nehalem` in the makefiles despite the log indicating that superenv added them.)
- Disabling the AVX512 and AVX2 flags altogether by passing some Arrow-specific CMake vars. (I can confirm this solves the problem, but we'd prefer not to do this if it can be avoided)
- Refactoring some of the SIMD logic in Arrow's C++ code to handle contradictory combinations of flags without causing illegal instruction errors. (This might take a while; we're not sure yet.)

**Comment by carlocab** [comment]
Any updates on this, @ianmcook?

**Comment by ianmcook** [comment]
@carlocab thanks for checking in. We have an Arrow 4.0.1 release upcoming and I intend to return to this next week when preparing a PR to update the Arrow port for that. I'll comment here with any SIMD-related findings or updates.

**Comment by carlocab** [comment]
Sure, no problem. I'm warming up to the idea of being able to disable `-march` flag filtering in `brew` since I think this could be useful for other formulae that are able to detect CPU features at runtime. However, I'd still like a more careful test of this before shipping it to users.

**Comment by carlocab** [comment]
I've opened Homebrew/brew#11608 to try to fix this.

**Comment by jeroen** [comment]
@carlocab thanks for your work on this. Do we need a revision of the apache-arrow formula to get the bottle fixed?

**Comment by carlocab** [comment]
We need to wait for the next release tag that includes my changes from  Homebrew/brew#11608. Not sure why the GitHub UI parses "partially resolves" to be the same as "closes", but there you go.

**Comment by carlocab** [comment]
This should hopefully be fixed now -- just do `brew upgrade`.
