### ISSUE TITLE
nim --HEAD failing due to upstream changes

### ISSUE THREAD

**Issue by jayvdb** [Homebrew/homebrew-core#76550]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.1.5-18-g4f4fb49
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4f4fb49481685208c5756c897944ae28757ca5c7
Last commit: 15 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7fd84fcfb65ae8a5faa90356020c2ae00bfbc8ad
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.OV4dGjRKuQ/org.xquartz:0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0 build 1205
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5

❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  afuse
  ccze
  ext2fuse
  ext4fuse
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/Caskroom/miniconda/base/bin/powerline-config
  /usr/local/Caskroom/miniconda/base/bin/python3-config
  /usr/local/Caskroom/miniconda/base/bin/ncursesw6-config
  /usr/local/Caskroom/miniconda/base/bin/pcre-config
  /usr/local/Caskroom/miniconda/base/bin/python3.8-config
  /Users/john.vandenberg/.cargo/bin/cargo-install-update-config
  /run/current-system/sw/bin/python-config
  /run/current-system/sw/bin/python3-config
  /run/current-system/sw/bin/python3.8-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python3.9/greenlet/greenlet.h

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  nim
  pyside
  dotnet
  googletest
  sip
  kubernetes-cli
  poppler
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the HEAD nim, as https://github.com/nim-dev/nimlint depends on it.

broken due to https://github.com/nim-lang/Nim/issues/17907

### What happened (include all command output)?

```
❯ brew install nim --HEAD
==> Cloning https://github.com/nim-lang/csources.git
Updating /Users/john.vandenberg/Library/Caches/Homebrew/nim--csources--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 64e3477 Update readme.markdown
==> Cloning https://github.com/nim-lang/Nim.git
Updating /Users/john.vandenberg/Library/Caches/Homebrew/nim--git
==> Checking out branch devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.
HEAD is now at 01f316c mention -d:nimLegacyConvEnumEnum in error msg (#17928)
==> /bin/sh build.sh
==> bin/nim c -d:release koch
==> ./koch boot -d:release -d:useLinenoise
Last 15 lines from /Users/john.vandenberg/Library/Logs/Homebrew/nim/03.koch:
Hint: macrocacheimpl [Processing]
Hint: vmprofiler [Processing]
Hint: evaltempl [Processing]
Hint: vmconv [Processing]
Hint: aliases [Processing]
Hint: patterns [Processing]
Hint: semmacrosanity [Processing]
Hint: active [Processing]
Hint: pluginsupport [Processing]
Hint: locals [Processing]
Hint: itersgen [Processing]
Hint: enumtostr [Processing]
Hint: spawn [Processing]
/private/tmp/nim-20210504-21598-mv0mn9/compiler/semtypes.nim(259, 78) Error: undeclared field: 'isNaN' for type system.BiggestFloat [declared in /private/tmp/nim-20210504-21598-mv0mn9/lib/system.nim(1397, 3)]
FAILURE

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```

### What did you expect to happen?

nim HEAD should be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install nim --HEAD
```

**Comment by carlocab** [comment]
Sorry, but source builds are not supported. This includes building from `HEAD`, as this requires a source build. This is why you see the message
```
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```
That said, this looks like a problem with the software and not the formula, so it's not as if it's anything we can fix here.

**Comment by jayvdb** [comment]
I'm pretty sure the formulae needs updating according to https://github.com/nim-lang/Nim/issues/17907 .

**Comment by carlocab** [comment]
Sure, please open a pull request.

**Comment by timotheecour** [comment]
fixed in https://github.com/Homebrew/homebrew-core/pull/78297
