### ISSUE TITLE
subversion: M1: add back Java bindings for Subclipse

### ISSUE THREAD

**Issue by rhoehener** [Homebrew/homebrew-core#76649]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
-
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

use Subclipse with JavaHL client

### What happened (include all command output)?

svnjavahl-1.dylib not installed / built on Mac mini M1

### What did you expect to happen?

svnjavahl-1.dylib somewhere after subversion install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
now that OpenJDK is supported on M1, reevaluate switches on Hardware::CPU.intel in the formula?

e.g. line 24:
# Do not build java bindings on ARM as openjdk is not available
depends_on "openjdk" => :build if Hardware::CPU.intel?
```

**Comment by carlocab** [comment]
Please open a PR to fix this; thanks.
