### ISSUE TITLE
postgres-xc becomes postgres-x2

### ISSUE THREAD

**Issue by ryenus** [Homebrew/homebrew-core#7673]
According to the latest [README][1], it's time to update [Postgres-XC Formula][2]:

> Postgres-XC is renamed to [Postges-X2][3] from 2015 after it was moved to [Github][4].

[1]: https://github.com/postgres-x2/postgres-x2/blob/master/README.md
[2]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgres-xc.rb
[3]: https://postgres-x2.github.io/
[4]: https://github.com/postgres-x2/postgres-x2

**Comment by ryenus** [comment]
This needs the `help wanted` label, thanks

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ryenus** [comment]
Sure, but also for sure it's incomplete: https://github.com/Homebrew/homebrew-core/pull/7679

**Comment by MikeMcQuaid** [comment]
Great! Closing in favour of the PR.
