### ISSUE TITLE
Label `brew bump-formula-pr` issues with `brew-bump-formula-pr` label

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/homebrew-core#76763]
A `brew-bump-formula-pr` label if a PR's body contains `brew bump-formula-pr` would be nice. This could allow these PRs to be more easily filtered and treated differently by a stale bot (perhaps closed more quickly if their CI status is failing?).

CC @homebrew/core for thoughts and volunteers.

**Comment by carlocab** [comment]
I don't think #76883 closes this just yet. In particular, this still seems useful but as-of-yet unimplemented:

treated differently by a stale bot (perhaps closed more quickly if their CI status is failing?).

**Comment by Rylan12** [comment]
Yep, you're right.

> treated differently by a stale bot

Should be easy to do: we can just run the stale action twice, restricting to only `bump-formula-pr` and `bump-cask-pr` PRs the second time.

> (perhaps closed more quickly if their CI status is failing?).

This is a little more tricky. I don't think the stale action can check this. We _could_ add a `CI complete` label or something like that when CI finishes but I'm not sure I love that. It's adding another label that shows something that can already be seen very easily by maintainers.

I think it's probably fine to close all `bump-formula-pr` or `bump-cask-pr` PRs after a little bit. Usually, if CI is ✅ they'll be approved and merged pretty quickly.

---

Maybe we mark as stale after 48 hours and then close after an additional 24 (so max open time is 72 hours)? Totally open to other ideas I'm just brainstorming.

Some things to note about this: I don't think we can say "48 hours during the UTC work week" like we do in Homebrew/brew, but I don't think this would be a huge problem. 72 hours means at least 24 of those are during the work week and I think we have a pretty strong maintainer presence in Homebrew/core and Homebrew/cask on weekends (plus there are fewer PRs).

Also, one thing to note is that if we add a comment after 48 hours, this will send a new notification for every open PR. My _guess_ is that most PRs will be handled before the 48 hours but in cases where it doesn't it does mean a lot of notifications.

**Comment by SMillerDev** [comment]
A failing PR like `go` that started as a `bump-formula-pr` can be excluded from stalebot right?

**Comment by MikeMcQuaid** [comment]
> I think it's probably fine to close all `bump-formula-pr` or `bump-cask-pr` PRs after a little bit. Usually, if CI is ✅ they'll be approved and merged pretty quickly.

👍🏻 makes sense to me.

> Some things to note about this: I don't think we can say "48 hours during the UTC work week" like we do in Homebrew/brew, but I don't think this would be a huge problem. 72 hours means at least 24 of those are during the work week and I think we have a pretty strong maintainer presence in Homebrew/core and Homebrew/cask on weekends (plus there are fewer PRs).

👍🏻 


> Also, one thing to note is that if we add a comment after 48 hours, this will send a new notification for every open PR. My _guess_ is that most PRs will be handled before the 48 hours but in cases where it doesn't it does mean a lot of notifications.

This seems fine to me. I think whatever we decide on we'll end up iterating on.




> A failing PR like `go` that started as a `bump-formula-pr` can be excluded from stalebot right?

I'd think so; I'd think it's the usual `in progress` label or similar will handle this.

**Comment by MikeMcQuaid** [comment]
> Also, once the stale label is added, the PR would't be closed for another 24 hours so hopefully in this case someone would notice, remove the stale label, and add the `in progress` label even if they didn't think to do it before.

Could also consider the messaging for `brew bump-formula-pr` stale closing to specifically reference that label.

**Comment by Rylan12** [comment]
Does it make more sense to add this stale run to the `triage-issues` workflow (which would mean adding the check to all repos that sync this workflow with Homebrew/.github) or add a new workflow to this repo and the cask repos that only contains the `bump-*-pr` stale handling

**Comment by MikeMcQuaid** [comment]
@rylan12 I don't have strong views either way! I guess if it goes to all repos: it could handle casks too?

**Comment by Rylan12** [comment]
> I guess if it goes to all repos: it could handle casks too?

Yes, but I was planning on adding it to casks regardless of whether it went to all repos or not.
