### ISSUE TITLE
LLVM 

### ISSUE THREAD

**Issue by jrp2014** [Homebrew/homebrew-core#76798]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.1.5-101-gd3013fc
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: d3013fcbc1c2424ae5deafd36d4f0bd79065984c
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1572af22de4242031f95608da8a65905fec13abb
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit ivybridge
Clang: 12.0 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
```

```sh
❯ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use llvm-config to get the llvm config settings.

### What happened (include all command output)?

```sh
> /usr/local/Cellar/llvm/12.0.0/bin/llvm-config --libs --link-shared 
llvm-config: error: libLLVM-12.dylib is missing

> ❯ ls /usr/local/Cellar/llvm/12.0.0/lib/libLLVM.dylib 
/usr/local/Cellar/llvm/12.0.0/lib/libLLVM.dylib
```

### What did you expect to happen?

I expected llvm-config to pick up that `libLLVM.dylib` is installed, but it seems to be looking for `libLLVM-12.dylib` which is presumably the same file, but with a version suffix.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install llvm` (installs llvm-12) and then run `usr/local/Cellar/llvm/12.0.0/bin/llvm-config --libs --link-shared` after setting LDFLAGS as the formula suggests (although that is not essential).
```

**Comment by carlocab** [comment]
Should be addressed by https://github.com/Homebrew/homebrew-core/pull/76646.

**Comment by Bo98** [comment]
Note that this is actually an upstream bug, not a Homebrew one: https://bugs.llvm.org/show_bug.cgi?id=40252

**Comment by jrp2014** [comment]
I upgraded from 12.0.0 to this patched version (12.0.0_1)  but there seems to be something in the internals that doesn't pick up the _1
```
ld: warning: directory not found for option '-L/usr/local/Cellar/llvm/12.0.0/lib'
ld: library not found for -lLLVM-12
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
`clang' failed in phase `Linker'. (Exit code: 1)
```

**Comment by jrp2014** [comment]
I also needed to
```
install_name_tool -id $PWD/libLTO.dylib libLTO.dylib
install_name_tool -id $PWD/libLLVM.dylib libLLVM.dylib
install_name_tool -change '@rpath/libLLVM.dylib' $PWD/libLLVM.dylib libLTO.dylib
```

**Comment by carlocab** [comment]
Why did you need to do that?

**Comment by carlocab** [comment]
> I also needed to
> 
> ```
> install_name_tool -id $PWD/libLTO.dylib libLTO.dylib
> install_name_tool -id $PWD/libLLVM.dylib libLLVM.dylib
> install_name_tool -change '@rpath/libLLVM.dylib' $PWD/libLLVM.dylib libLTO.dylib
> ```

Note that if `$PWD` here is a Cellar path (it should already have the correct install names), then anything you link to `libLTO.dylib` is going to break with version/revision bumps to the `llvm` formula, even if the new `libLTO.dylib` is meant to be a drop-in replacement for the old one.

The correct thing to do here would've been to adjust the linker flags for whatever you were linking with `libLTO.dylib`, instead of changing install names.

**Comment by jrp2014** [comment]
Thanks Carlo, I am using the Haskell bindings for LLVM.  They advise https://github.com/llvm-hs/llvm-hs doing this to get around some system protection issues apparently..  I tried without applying the additional commands and it broke my build.  I'll report this as an issue as I don't enjoy adding random fixes for the reasons you suggest.

**Comment by carlocab** [comment]
Adding `-Wl,-rpath,$(brew --prefix llvm)/lib` (or similar) to your compiler flags (e.g. `LDFLAGS`) is probably a much better solution than changing the install names of libraries.

This is just a guess, though, since I don't know what build error you encountered.

**Comment by jrp2014** [comment]
Thanks.  I'll feed that back.  The ghc compilation failed.  Sorry, can't remember the precise error.

**Comment by carlocab** [comment]
I'm actually also confused why you don't have `-lLLVM` in your linker flags, if you need something to be able to find `libLLVM` through `libLTO`.

`libLTO` already has the correct `LC_RPATH` (`@loader_path/../lib`), so it should be able to find `libLLVM` on its own with the `@rpath` prefix for `libLLVM` in the relevant `LC_LOAD_DYLIB` command. So presumably the need to change install names is because something is linking with `libLTO` that needs `libLLVM` but then can't find it.

**Comment by jrp2014** [comment]
llvm-hs looks for the llvm-config-* executable the path and determines the build flags using that.  https://github.com/llvm-hs/llvm-hs/blob/llvm-12/llvm-hs/Setup.hs  seems to be the raw plumbing.   (I am only using the llvm-hs package and have not dug into how it is built.)  But the README says that this renaming works around some system integrity protections.  Not sure how it achieves that.

**Comment by carlocab** [comment]
Yes, it probably has to do with `DYLD_LIBRARY_PATH` and friends not propagating into child processes because of SIP. You usually want to set `DYLD_LIBRARY_PATH` when you built something with the wrong linker flags. (Note that using the wrong linker flags isn't really a criticism here; getting it right while also making it portable across platforms can get quite thorny.)

**Comment by jrp2014** [comment]
Thanks.  I'll probe, but I assume that they did it for a reason.  Not obvious whether that reason still holds.  The Setup.hs file has some specialisation for MacOS, so it may not do any harm to have some more.
