### ISSUE TITLE
brew install aircrack-ng not working, no bottle available (ARM)

### ISSUE THREAD

**Issue by TheDarkLordo** [Homebrew/homebrew-core#76814]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Error: aircrack-ng: no bottle available!
You can try to install from source with:
  brew install --build-from-source aircrack-ng
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install aircrack-ng on a Macbook air M1 2020

### What happened (include all command output)?

Homebrew doesn't find any bottle available and doesn't install aircrack-ng. What's more, it retrives errors if i try to build it from source using the formula "brew install --build-from-source aircrack-ng"

### What did you expect to happen?

To have aircrack-ng installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just send brew install aircrack-ng in a terminal shell on a Macbook air M1 (Mac OS 11.3)
```

**Comment by SMillerDev** [comment]
This is expected, the software does not work with M1 macs (as you noticed when using `--build-from-source`) 

https://formulae.brew.sh/formula/aircrack-ng also shows that it isn't available
