### ISSUE TITLE
Postgredb formula database <user> does not exist problem

### ISSUE THREAD

**Issue by inancgumus** [Homebrew/homebrew-core#7682]
After PostgreSQL installation on _os x 10.12.1 (16B2555)_, when you call `psql` it gives errors. Details are below. Should I fix this by contributing to the homebrew formula?

### Reproducing

1. `rm -rf /usr/local/var/postgres*`
2. `brew install postgresql`
3. `brew services start postgresql`
4. `psql` -- boom: error:

    ```bash
    psql: FATAL:  database "<user>" does not exist
    ```

### Fix

Do the reproducing steps then run just `createdb`. `psql` will work.

I think that the formula should have been calling `createdb`.

### Details

[```brew gist-logs postgresql```](https://gist.github.com/inancgumus/bbfcf2912adedcebccc05fa8350c003d)

**Comment by MikeMcQuaid** [comment]
Looks like it is initialising the databases if that directory is empty: https://github.com/Homebrew/homebrew-core/blob/88279a86f5440002a5ad9c171adcf38ce8cac87b/Formula/postgresql.rb#L102-L108

How do `initdb` and `createdb` differ?

**Comment by inancgumus** [comment]
@MikeMcQuaid `initdb` is like creating a filesystem. To create a database for the running user `initdb` might be used.

You can connect to `psql -d postgres` after first install, only with `initdb`. But, that's confusing because running a bare `psql` defaults to a database with the same name of the running user.

**Comment by MikeMcQuaid** [comment]
@inancgumus What does e.g. Debian do by default? Also, it's worth comparing to what `mysql.rb` does by default. Thanks!

**Comment by inancgumus** [comment]
@MikeMcQuaid I'm not sure what you're asking about. However, the problem is mysql lets you connect to db after homebrew installation by running: `mysql -uroot`, but PostgreSql formula does not let you connect to it and it's confusing. Maybe, after installation message should let the user know about how to connect to db.

**To prove it's confusing, there are many people who are asking why their db is not working:**

- https://github.com/PostgresApp/PostgresApp/issues/139
- http://stackoverflow.com/questions/17633422/psql-fatal-database-user-does-not-exist
- google for: psql: FATAL: database does not exist

**I think the solution all or one of:**

- Letting people know about that they need to run `psql -d postgres`
- Automatically create a db through by adding `createdb` command to formula, so people can directly connect to Postgresql by running intuitively: `psql`

**Comment by MikeMcQuaid** [comment]
> Automatically create a db through by adding createdb command to formula, so people can directly connect to Postgresql by running intuitively: psql

Cool, thanks. This sounds like the best answer. Could you try and open a pull request to use `createdb` instead of `initdb`? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by harshnarang8** [comment]
@MikeMcQuaid I think a better way is by running createdb if the database with the name of the user doesn't exist, without disturbing the init call. I tried running the createdb version after removing all traces of postgresql and postgres from my mac, but what I realised was that psql doesn't work if you do not have an initialised filesystem, thus requiring initdb to be run in post-install. So, a better idea would simply be to run createdb after the initdb check is done. 
P.S. I came across this PR related to postgresql, but it doesn't address the issue. Should I open a new one, or wait for it to get merged first? #10620

**Comment by inancgumus** [comment]
@harshnarang8 Yes, first `initdb` then `createdb` would be better. I forgot this one. I can post a PR.

**Comment by harshnarang8** [comment]
@inancgumus Don't worry, I already did the edit last night.

**Comment by MikeMcQuaid** [comment]
Passing on this as there's no clean way to do it automatically, sorry!

**Comment by justanton** [comment]
was this updated later? I.e., do we still need to run `initdb /usr/local/var/postgres` and `createdb `whoami`, after brew installed Postgres? I didn't get any information in caveats
