### ISSUE TITLE
Move libsvm to Homebrew/science

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-core#7684]
`libsvm` is not used by any other formula in Homebrew/core. Should it be moved to Homebrew/science? It's not used by any formula in Homebrew/science either, but it seems more suited to Homebrew/science.
```
❯❯❯ brew desc libsvm
libsvm: Library for support vector machines
```
@Homebrew/science

**Comment by ilovezfs** [comment]
At least for the time being we're pretty much not moving anything out of core unless it's going to the boneyard.

**Comment by MikeMcQuaid** [comment]
Indeed.
