### ISSUE TITLE
Pip breaks in python after updating it to 9.0.1

### ISSUE THREAD

**Issue by nayefc** [Homebrew/homebrew-core#7714]
I have python installed using Homebrew (python 2.7.12) and I'm running on latest Homebrew. Today I ran `pip install --upgrade pip` to upgrade to the latest pip 9.0.1. After that, I could not find pip in my `PATH` anymore. Furthermore, when I install packages (i.e: `pip install percale` from `https://github.com/mooz/percol`, I can't run `percol` because it's not found.

Brew doctor shows nothing and relinked python with no response. To get pip to work, I manually ran:

```
ln -s /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/pip /usr/local/bin/pip
```

But I still can't install packages globally that can be accessed from the command line, since I'm probably still missing some symlink. Am I missing something? How can I fix this?

**Comment by MikeMcQuaid** [comment]
CC @tdsmith for thoughts.

**Comment by tdsmith** [comment]
I can't reproduce and I don't understand how this problem would arise. Does running `python -m pip install -U --force-reinstall pip` help?

**Comment by srowen** [comment]
I saw this today after updating to Python 2.7.13. I noticed it reported a pip-related problem along the way:

```
percolateur:~ srowen$ brew install python
Warning: python-2.7.13 already installed
percolateur:~ srowen$ brew postinstall python
==> Using the sandbox
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-exte
==> /usr/local/Cellar/python/2.7.13/bin/python -s setup.py --no-user-cfg install --force --verbose --single-version-exte
Last 15 lines from /Users/srowen/Library/Logs/Homebrew/python/post_install.02.python:
--no-user-cfg
install
--force
--verbose
--single-version-externally-managed
--record=installed.txt
--install-scripts=/usr/local/Cellar/python/2.7.13/bin
--install-lib=/usr/local/lib/python2.7/site-packages

running install
running build
running build_py
running install_lib
copying build/lib/pip/__init__.py -> /usr/local/lib/python2.7/site-packages/pip
error: could not delete '/usr/local/lib/python2.7/site-packages/pip/__init__.py': Permission denied
```

Indeed a few items under `'/usr/local/lib/python2.7/site-packages/` were owned by `root`. I assume they're not supposed to be, and don't know how they got that way (probably from me updating `pip` with `sudo pip ...`?) but after `chown`ing it and `brew postinstall python` it's all fine, including `pip`.

**Comment by mannibis** [comment]
@srowen is right. The `pip` folder under `/usr/local/lib/python2.7/site-packages/` is indeed owned by root. You can `chown -R user /usr/local/lib/python2.7/site-packages/pip` and then do `brew postinstall python` as @srowen says and all is good again. 

Thanks!

**Comment by tdsmith** [comment]
> The pip folder under /usr/local/lib/python2.7/site-packages/ is indeed owned by root. 

This will only be true if you have taken some action to cause it to be owned by root; running `sudo pip something` may do that.

@nayefc, please open a new issue if your problem persists.
