### ISSUE TITLE
libgccjit: can't compile on apple silicon

### ISSUE THREAD

**Issue by hexagonal-sun** [Homebrew/homebrew-core#77327]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92cf9047191393a2d624c64fc28d9595309ba273
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9dceba361c74f8af8a2ebc7cde06aac3ef57fe59
Core tap last commit: 49 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.e8qBUUVMps/org.macports:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-arm64
CLT: 12.5.0.22.9
Xcode: 12.5
Rosetta 2: false


matthew@matthews-air ~> brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install libgccjit` on an apple silicon machine.

### What happened (include all command output)?

```
==> Installing libgccjit
==> ../configure --build=x86_64-apple-darwin20 --prefix=/opt/homebrew/Cellar/libgccjit/11.1.0 --libdir=/opt/homebrew/Cellar/libgccjit/11.1.0/li
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
Last 15 lines from /Users/matthew/Library/Logs/Homebrew/libgccjit/02.make:
      __ZL13do_mpc_ckconvP10real_valueS0_PK12__mpc_structbPK11real_format in libbackend.a(fold-const-call.o)
      __ZL14do_mpfr_ckconvP10real_valuePK13__mpfr_structbPK11real_format in libbackend.a(fold-const-call.o)
  "_mpfr_y0", referenced from:
      __ZL17fold_const_call_111combined_fnP9tree_nodeS1_ in libbackend.a(fold-const-call.o)
  "_mpfr_y1", referenced from:
      __ZL17fold_const_call_111combined_fnP9tree_nodeS1_ in libbackend.a(fold-const-call.o)
  "_mpfr_yn", referenced from:
      __ZL17fold_const_call_111combined_fnP9tree_nodeS1_S1_ in libbackend.a(fold-const-call.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [cc1plus] Error 1
rm gcc.pod
make[2]: *** [all-stage2-gcc] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [all] Error 2
```

### What did you expect to happen?

libgccjit to compile successfully.  I presume the issue is with https://github.com/Homebrew/homebrew-core/blob/9dceba361c74f8af8a2ebc7cde06aac3ef57fe59/Formula/libgccjit.rb#L48 since compiler target is hard-coded to be `x86_64`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install libgccjit` on an apple silicon mac.
```

**Comment by SMillerDev** [comment]
Please make a pull request instead. If it isn't bottled for apple silicon, it's not supported.

**Comment by carlocab** [comment]
> I presume the issue is with https://github.com/Homebrew/homebrew-core/blob/9dceba361c74f8af8a2ebc7cde06aac3ef57fe59/Formula/libgccjit.rb#L48 since compiler target is hard-coded to be `x86_64`.

Does it compile if you fix that?

**Comment by cpbotha** [comment]
I got libgccjit successfully built on M1 by using iains branch. Here is the formula I used, including instructions in the comments: https://gist.github.com/cpbotha/5f44a7f44ad93445128113c208b4a252

Unfortunately, trying to build homebrew emacs-plus native-comp based on this gccjit did not work.
