### ISSUE TITLE
freeciv: upgrade to 2.6.4 has introduced graphics bug

### ISSUE THREAD

**Issue by pjlsergeant** [Homebrew/homebrew-core#77343]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Peters-MacBook-Air:~ pjlsergeant$ brew config
HOMEBREW_VERSION: 3.1.7-42-gd45832b
ORIGIN: https://github.com/Homebrew/brew
HEAD: d45832bbfc7a7e89a7f54cc314c93a087decf89f
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 30504ec3c1bebedb024420866fe4fee3e96061d7
Core tap last commit: 4 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.0 build 1200
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: N/A
Peters-MacBook-Air:~ pjlsergeant$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  unrar

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  node@10

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/pjlsergeant/.asdf/shims/python3.9-config
  /Users/pjlsergeant/.asdf/shims/python-config
  /Users/pjlsergeant/.asdf/shims/python3-config
  /Users/pjlsergeant/perl5/perlbrew/perls/perl-5.30.2/bin/ppkg-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr
  git-flow

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/pjlsergeant/.bash_profile
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

City view of units is missing health bar

### What happened (include all command output)?

https://imgur.com/a/nBVSLKJ

### What did you expect to happen?

https://imgur.com/a/DvwCMkw -- note green bar

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew upgrade freeciv`
```

**Comment by carlocab** [comment]
Does this bug affect just the Hombrew version of `freeciv`, or does it affect a non-Homebrew version as well? If it's the latter, please report this upstream, as this should be fixed there.

**Comment by pjlsergeant** [comment]
It's unclear to me whether this is an upstream issue, or another issue with freeciv's dependencies via brew. I note that no bug report exists already either here or https://osdn.net/projects/freeciv/ticket/

To help reproduce, I've created the following: https://github.com/pjlsergeant/homebrew-oldfreeciv 

It has `freecivoldgood`, which is the formula before this commit, and `freecivbad` which is the one after

**Comment by pjlsergeant** [comment]
Created an upstream ticket here: https://osdn.net/projects/freeciv/ticket/42284

**Comment by pjlsergeant** [comment]
Even if it's an upstream bug, brew is now releasing an unplayable version of the game as the main, which means unwitting players such as myself will find the game stops working one day having run an unrelated `brew` command, so at best the formula presumably needs downgrading to the old version?

**Comment by carlocab** [comment]
Sorry, we don't downgrade formulae to earlier versions (except with the possible exception of addressing security vulnerabilities).

If you would like to switch back to an earlier version of `freeciv`, you can host an earlier version of the formula in your own tap. See `brew help extract` and `brew help tap-new` for details.

Here are some other relevant documentation:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by pjlsergeant** [comment]
@carlocab "you can host an earlier version of the formula" ... yes, that indeed forms part of the bug report a couple of comments above.

**Comment by carlocab** [comment]
Great, looks like you're all set for your tap then.

**Comment by pjlsergeant** [comment]
@alebcay As you updated the package, please can you confirm it works as intended on your machine?

**Comment by carlocab** [comment]
There was a recent issue about a graphics bug: #75993 No complaints about missing health bars though.

**Comment by pjlsergeant** [comment]
> There was a recent issue about a graphics bug: #75993 No complaints about missing health bars though.

It's a seperate and long-standing issue that I'm very glad is fixed

**Comment by pjlsergeant** [comment]
Freeciv team can reproduce on Linux, so closing this

**Comment by cazfi** [comment]
You could work around this issue, and generally benefit, from using newer gtk3.22-client instead of old gtk3-client, with configure option --enable-client=gtk3.22. See doc/README.packaging for more info.
