### ISSUE TITLE
brew install Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.

### ISSUE THREAD

**Issue by Flyraty** [Homebrew/homebrew-core#77342]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
- brew config

HOMEBREW_VERSION: 3.1.7-36-g7c68b17
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7c68b1738b3dce2885d0146f327eaaf96b6d0029
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bf34b4a87af8acac55d95f133a8b56a627a28557
Core tap last commit: 5 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jiJkB9eSrz/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.29.2 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.3-x86_64
CLT: 12.5.0.0.1.1617976050
Xcode: 10.2.1

- brew doctor
the full log file is [doctor.log](https://github.com/Homebrew/homebrew-core/files/6483807/doctor.log)
```sh
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2
  mongodb
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb:14

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb:15

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb:16

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb:17

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb:18

Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/tree.rb:19
...... many same wornings
Warning: Some installed formulae are not readable:
  mongodb: unknown or unsupported macOS version: :mountain_lion

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc

Warning: Your Xcode (10.2.1) is too outdated.
Please update to Xcode 12.5 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (10.2.1) is outdated.
Please update to Xcode 12.5 (or delete it).
Xcode can be updated from the App Store.
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to  fix  my brew tools. 
My brew have many Warnings now  when run `brew install` or other brew commands.


### What happened (include all command output)?

- brew search grafana
[brew_search.log](https://github.com/Homebrew/homebrew-core/files/6483940/brew_search.log)

- brew install grafana
[brew_install.log](https://github.com/Homebrew/homebrew-core/files/6483945/brew_install.log)

- brew style --fix
[brew_fix.log](https://github.com/Homebrew/homebrew-core/files/6483953/brew_fix.log)


### What did you expect to happen?

I expect my brew tools have no warnings and  install packages normaly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew search grafana
- brew install grafana
- brew style --fix
- git clone git@github.com:Flyraty/homebrew-tap.git && brew style --fix Formula
```

**Comment by carlocab** [comment]
Your core tap is outdated:
```
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bf34b4a87af8acac55d95f133a8b56a627a28557
Core tap last commit: 5 months ago
```
If `brew update` doesn't fix that, try `brew update-reset`. Note, however, the following:
```
❯ brew help update-reset
Usage: brew update-reset [repository ...]

Fetch and reset Homebrew and all tap repositories (or any specified
repository) using git(1) to their latest origin/HEAD.

Note: this will destroy all your uncommitted or committed changes.
```

**Comment by gromgit** [comment]
This is already the second case today, of an up-to-date software repo but a very backdated core tap: https://github.com/Homebrew/discussions/discussions/1470

@Flyraty, did you get any errors when you ran `brew update` *before* you filed this issue?

**Comment by Flyraty** [comment]
> This is already the second case today, of an up-to-date software repo but a very backdated core tap: [Homebrew/discussions#1470](https://github.com/Homebrew/discussions/discussions/1470)
> 
> @Flyraty, did you get any errors when you ran `brew update` _before_ you filed this issue?

`brew update` get no errors.

**Comment by Flyraty** [comment]
> Your core tap is outdated:
> 
> ```
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: bf34b4a87af8acac55d95f133a8b56a627a28557
> Core tap last commit: 5 months ago
> ```
> 
> If `brew update` doesn't fix that, try `brew update-reset`. Note, however, the following:
> 
> ```
> ❯ brew help update-reset
> Usage: brew update-reset [repository ...]
> 
> Fetch and reset Homebrew and all tap repositories (or any specified
> repository) using git(1) to their latest origin/HEAD.
> 
> Note: this will destroy all your uncommitted or committed changes.
> ```

I will  try it，thanks

**Comment by Flyraty** [comment]
> Your core tap is outdated:
> 
> ```
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: bf34b4a87af8acac55d95f133a8b56a627a28557
> Core tap last commit: 5 months ago
> ```
> 
> If `brew update` doesn't fix that, try `brew update-reset`. Note, however, the following:
> 
> ```
> ❯ brew help update-reset
> Usage: brew update-reset [repository ...]
> 
> Fetch and reset Homebrew and all tap repositories (or any specified
> repository) using git(1) to their latest origin/HEAD.
> 
> Note: this will destroy all your uncommitted or committed changes.
> ```

`brew update-reset` executed successfully, but this  warnings only  exists。I used  `brew style --fix`.  It occured some  erros. It looks that this url need authentication.
```sh
==> Downloading https://ghcr.io/v2/homebrew/core/shellcheck/manifests/0.7.1-1
##O=#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "shellcheck_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/shellcheck/manifests/0.7.1-1
Error: Failure while executing; `/usr/local/bin/brew install shellcheck` exited with 1.
```

**Comment by carlocab** [comment]
>but this warnings only exists

Which warning? The failure to install `shellcheck`? What's the output of `brew config` now?

**Comment by carlocab** [comment]
Try
```
rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
```

**Comment by Flyraty** [comment]
> > > but this warnings only exists
> > 
> > 
> > Which warning? The failure to install `shellcheck`? What's the output of `brew config` now?
> 
> * warning
> 
> ```
> Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
> Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/shellcheck.rb:10
> ```
> 
> * brew config now
> 
> ```
> HOMEBREW_VERSION: 3.1.7-42-gd45832b
> ORIGIN: https://github.com/Homebrew/brew
> HEAD: d45832bbfc7a7e89a7f54cc314c93a087decf89f
> Last commit: 9 hours ago
> Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
> Core tap HEAD: bf34b4a87af8acac55d95f133a8b56a627a28557
> Core tap last commit: 5 months ago
> Core tap branch: master
> HOMEBREW_PREFIX: /usr/local
> HOMEBREW_CASK_OPTS: []
> HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.jiJkB9eSrz/org.macosforge.xquartz:0
> HOMEBREW_MAKE_JOBS: 8
> Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
> CPU: octa-core 64-bit kabylake
> Clang: 12.0.5 build 1205
> Git: 2.29.2 => /usr/local/bin/git
> Curl: 7.64.1 => /usr/bin/curl
> macOS: 11.2.3-x86_64
> CLT: 12.5.0.0.1.1617976050
> Xcode: 10.2.1
> ```



> Try
> 
> ```
> rm -rf $(brew --repo homebrew/core)
> brew tap homebrew/core
> ```

This is useful.The problem has been  solved，thanks for your help.

**Comment by Steven-Duan** [comment]
Did you settle all your dev tools install issues from your brew doctor before you fix your problem ?
