### ISSUE TITLE
Not being able to reset and update brew

### ISSUE THREAD

**Issue by Bilal-K20** [Homebrew/homebrew-core#77372]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Hi everyone, 

So I have just tried to reset and update brew using brew update-reset however this is the issue i get 

Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
fatal: 'origin/HEAD' is not a commit and a branch '' cannot be created from it

can someone please help me out, i am very lost. 

Thanks,
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am just trying to update and reset brew so that i can download python version 3 and git via terminal 

### What happened (include all command output)?

entered brew update-reset 

outcome:
Resetting /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core...
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
fatal: 'origin/HEAD' is not a commit and a branch '' cannot be created from it

### What did you expect to happen?

just to update and reset 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update-reset
```

**Comment by carlocab** [comment]
>Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

Where is the output of `brew config` and `brew doctor`?

**Comment by Bilal-K20** [comment]
brew config

HOMEBREW_VERSION: 3.1.7-62-g9f5afcb

ORIGIN: https://github.com/Homebrew/brew

HEAD: 9f5afcbf63efa8832d4ba27b2a98357bcf4e80a0

Last commit: 4 hours ago

Core tap ORIGIN: https://github.com/Homebrew/homebrew-core

Core tap HEAD: (none)

Core tap last commit: never

Core tap branch: HEAD

HOMEBREW_PREFIX: /usr/local

HOMEBREW_CASK_OPTS: []

HOMEBREW_MAKE_JOBS: 16

Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby

CPU: 16-core 64-bit kabylake

Clang: 12.0.0 build 1200

Git: 2.31.0 => /usr/local/bin/git

Curl: 7.64.1 => /usr/bin/curl

macOS: 10.15.7-x86_64

CLT: 12.4.0.0.1.1610135815

Xcode: 12.4


brew doctor

Please note that these warnings are just used to help the Homebrew maintainers

with debugging if you file an issue. If everything you use Homebrew for is

working fine: please don't worry or file an issue; just ignore this. Thanks!


Warning: Some taps are not on the default git origin branch and may not receive

updates. If this is a surprise to you, check out the default branch with:

  git -C $(brew --repo homebrew/core) checkout

________________________________

**Comment by Bilal-K20** [comment]
brew config

HOMEBREW_VERSION: 3.1.7-62-g9f5afcb

ORIGIN: https://github.com/Homebrew/brew

HEAD: 9f5afcbf63efa8832d4ba27b2a98357bcf4e80a0

Last commit: 4 hours ago

Core tap ORIGIN: https://github.com/Homebrew/homebrew-core

Core tap HEAD: (none)

Core tap last commit: never

Core tap branch: HEAD

HOMEBREW_PREFIX: /usr/local

HOMEBREW_CASK_OPTS: []

HOMEBREW_MAKE_JOBS: 16

Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby

CPU: 16-core 64-bit kabylake

Clang: 12.0.0 build 1200

Git: 2.31.0 => /usr/local/bin/git

Curl: 7.64.1 => /usr/bin/curl

macOS: 10.15.7-x86_64

CLT: 12.4.0.0.1.1610135815

Xcode: 12.4


brew doctor

Please note that these warnings are just used to help the Homebrew maintainers

with debugging if you file an issue. If everything you use Homebrew for is

working fine: please don't worry or file an issue; just ignore this. Thanks!


Warning: Some taps are not on the default git origin branch and may not receive

updates. If this is a surprise to you, check out the default branch with:

  git -C $(brew --repo homebrew/core) checkout

**Comment by Bilal-K20** [comment]
> > Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.
> 
> Where is the output of `brew config` and `brew doctor`?

**brew config**

HOMEBREW_VERSION: 3.1.7-62-g9f5afcb

ORIGIN: https://github.com/Homebrew/brew

HEAD: 9f5afcbf63efa8832d4ba27b2a98357bcf4e80a0

Last commit: 4 hours ago

Core tap ORIGIN: https://github.com/Homebrew/homebrew-core

Core tap HEAD: (none)

Core tap last commit: never

Core tap branch: HEAD

HOMEBREW_PREFIX: /usr/local

HOMEBREW_CASK_OPTS: []

HOMEBREW_MAKE_JOBS: 16

Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby

CPU: 16-core 64-bit kabylake

Clang: 12.0.0 build 1200

Git: 2.31.0 => /usr/local/bin/git

Curl: 7.64.1 => /usr/bin/curl

macOS: 10.15.7-x86_64

CLT: 12.4.0.0.1.1610135815

Xcode: 12.4


**brew doctor**

Please note that these warnings are just used to help the Homebrew maintainers

with debugging if you file an issue. If everything you use Homebrew for is

working fine: please don't worry or file an issue; just ignore this. Thanks!


Warning: Some taps are not on the default git origin branch and may not receive

updates. If this is a surprise to you, check out the default branch with:

  git -C $(brew --repo homebrew/core) checkout

**Comment by carlocab** [comment]
Have you tried the command suggested by `brew doctor`?

**Comment by Bilal-K20** [comment]
> Have you tried the command suggested by `brew doctor`?

tried to run this:
git -C $(brew --repo homebrew/core) checkout 

this is what i got:

fatal: You are on a branch yet to be born

**Comment by carlocab** [comment]
What is the output of

```
ls -l $(brew --repo homebrew/core){,/.git}
```
?

**Comment by Bilal-K20** [comment]
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core:

/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/.git:
total 32
-rw-r--r--   1 username admin     0 16 May 01:43 FETCH_HEAD
-rw-r--r--   1 username  admin  1187 16 May 01:39 GITHUB_HEADERS
-rw-r--r--   1 username  admin    23 14 Mar 21:47 HEAD
-rw-r--r--   1 username  admin   267 16 May 01:39 config
-rw-r--r--   1 username  admin    73 14 Mar 21:47 description
drwxr-xr-x  14 username  admin   448 14 Mar 21:47 hooks
drwxr-xr-x   3 username  admin    96 14 Mar 21:47 info
drwxr-xr-x   4 username  admin   128 14 Mar 21:47 objects
drwxr-xr-x   4 username  admin   128 14 Mar 21:47 refs

**Comment by carlocab** [comment]
Strange. Try
```
rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
```

**Comment by Bilal-K20** [comment]
> Strange. Try
> 
> ```
> rm -rf $(brew --repo homebrew/core)
> brew tap homebrew/core
> ```

error: 7454 bytes of body are still expected.29 MiB | 5.38 MiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --origin=origin` exited with 128.

**Comment by Bilal-K20** [comment]
> Strange. Try
> 
> ```
> rm -rf $(brew --repo homebrew/core)
> brew tap homebrew/core
> ```

rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 958409, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (78/78), done.
error: 7454 bytes of body are still expected.29 MiB | 5.38 MiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-core /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core --origin=origin` exited with 128.

**Comment by carlocab** [comment]
Looks like a connection problem. If
```
cd /tmp
git clone https://github.com/Homebrew/homebrew-core
```
doesn't work, then it almost certainly is a connection problem. If that's the case, I don't know how to help you with that.

**Comment by Bilal-K20** [comment]
> Looks like a connection problem. If
> 
> ```
> cd /tmp
> git clone https://github.com/Homebrew/homebrew-core
> ```
> 
> doesn't work, then it almost certainly is a connection problem. If that's the case, I don't know how to help you with that.

cd /tmp
git clone https://github.com/Homebrew/homebrew-core
Cloning into 'homebrew-core'...
remote: Enumerating objects: 958409, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (79/79), done.
error: 2025 bytes of body are still expected.91 MiB | 5.52 MiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by Bilal-K20** [comment]
> Looks like a connection problem. If
> 
> ```
> cd /tmp
> git clone https://github.com/Homebrew/homebrew-core
> ```
> 
> doesn't work, then it almost certainly is a connection problem, and not a problem with `brew`. If that's the case, I don't know how to help you with that.

okay no worries thanks for the help, do you reckon it's something in the firewall setting?

**Comment by carlocab** [comment]
Could be. I suggest you Google the error message you're seeing to see how other people solved similar issues.

**Comment by Bilal-K20** [comment]
> Could be. I suggest you Google the error message you're seeing to see how other people solved similar issues.

yeah I've tried but can't seem to figure out whats going on

**Comment by Bilal-K20** [comment]
> Could be. I suggest you Google the error message you're seeing to see how other people solved similar issues.

thanks anyway
