### ISSUE TITLE
fakeroot and makepkg 

### ISSUE THREAD

**Issue by lloeki** [Homebrew/homebrew-core#77488]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
not applicable
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

(^^^^ TBH not really, it's fairly obvious what's going on here)

### What were you trying to do (and why)?

Trying to install `fakeroot` and `makepkg`.

Both have been [disabled on 29 Mar](https://github.com/Homebrew/homebrew-core/pull/73692#issuecomment-808793874).

The comment says:

>> I tried to bump to 1.25.3 nevertheless, and looked at the README_MACOSX.txt file to get the install instructions.
> Probably not a good sign that that README file hasn't been touched in 9 years: https://salsa.debian.org/clint/fakeroot/-/blob/master/README_MACOSX.txt
>
> The OS/X port seems to have originally been done by @mackyle ( OS/X development repo https://github.com/mackyle/fakeroot ) but that hasn't been touched since 2013 either

... but this was looking at the `master` branch, while there is [an `upstream` branch](https://salsa.debian.org/clint/fakeroot/-/tree/upstream) with [recent](https://salsa.debian.org/clint/fakeroot/-/commit/8090dffdad8fda86dccd47ce7a7db8840bdf7d7b) [commits](https://salsa.debian.org/clint/fakeroot/-/commit/f5e0a89ab6f0024f3d3bec5fd9cf631676b44f6c) fixing several macOS and Linux (against glibc 2.33) regressions.

As a matter of fact I am the maintainer of [ArchMac](https://github.com/archmac), which requires [`fakeroot`](https://github.com/archmac/bootstrap/blob/ecb583d97f3ebcb93862d619f36ed679b95d3dae/mini/fakeroot/PKGBUILD) for [`makepkg`](https://github.com/archmac/bootstrap/blob/ecb583d97f3ebcb93862d619f36ed679b95d3dae/mini/pacman/PKGBUILD), and can confirm both build, run, and operate successfully on an up-to-date macOS Big Sur Intel machine when using the [`upstream` branch](https://salsa.debian.org/clint/fakeroot/-/tree/upstream) (currently at `24d6b0857396cad87b2cabd32fb8af9ef4799915` from Feb 18). On the arm64 side, I'm working on making it work (there are platform-specific breaking changes regarding 32-bit `stat` vs `stat64` structs) and trying to reach Clint to collaborate on a fix and ultimately get something landing upstream.

### What happened (include all command output)?

Formula disabled!

### What did you expect to happen?

Installable `fakeroot` and `makepkg`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install makepkg
brew install fakeroot
```

**Comment by MikeMcQuaid** [comment]
Thanks @lloeki. Could you submit a PR to remove the disabling here and update them to a newer version? Thanks!

> while there is [an `upstream` branch](https://salsa.debian.org/clint/fakeroot/-/tree/upstream) with [recent](https://salsa.debian.org/clint/fakeroot/-/commit/8090dffdad8fda86dccd47ce7a7db8840bdf7d7b) [commits](https://salsa.debian.org/clint/fakeroot/-/commit/f5e0a89ab6f0024f3d3bec5fd9cf631676b44f6c) fixing several macOS and Linux (against glibc 2.33) regressions.

Maybe it's worth making `upstream` the default branch on GitLab?

**Comment by lloeki** [comment]
> Could you submit a PR to remove the disabling here and update them to a newer version? Thanks!

That's my plan to try that as time permits ;)
