### ISSUE TITLE
llvm build dependency silently preempts the installation of a formula

### ISSUE THREAD

**Issue by mulle-nat** [Homebrew/homebrew-core#7753]
As soon as I add `depends_on 'llvm'  => [ "with-libcxx", :build ]` to a formula, the install terminates. But brew doesn't give a reason, much less an error. This is on **Yosemite** with a freshly cloned **brew**. (Edit: and also on **Sierra**)

Here is an example formula:

```
class Empty < Formula
   homepage "https://github.com/mulle-nat/empty"
   desc "Empty does nothing"
   url "https://github.com/mulle-nat/empty/archive/0.0.0.tar.gz"
   sha256 "dde48a03106f096ad575fbeebc9a81adc29774540c10b7190fb915d0d68ac452"

   depends_on 'llvm'  => [ "with-libcxx", :build ]

   def install
      mkdir "build" do
         system "echo", "installed OK"
      end
   end

   test do
      system "echo", "OK"
   end
end
```

**Comment by ilovezfs** [comment]
```
iMac-TMP:homebrew-core joe$ brew install empty
==> Installing dependencies for empty: llvm
==> Installing empty dependency: llvm
==> Downloading https://homebrew.bintray.com/bottles/llvm-3.9.0.el_capitan.bottle.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/llvm-3.9.0.el_capitan.bottle.tar.gz
==> Pouring llvm-3.9.0.el_capitan.bottle.tar.gz
^C
```

Please say more :)

**Comment by MikeMcQuaid** [comment]
Sorry but you have not followed the requested steps on [the Troubleshooting page](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting)

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by mulle-nat** [comment]
@ilovezfs Shouldn't have CTRL-Ced. The problem happens afterwards.
@MikeMcQuaid There are no gist-logs produced. Or what else ?

Here is a what happens

```
nat@kempe:srcM(^) $ which brew
/tmp/brew/bin/brew
nat@kempe:srcM(^) $ brew install /Volumes/Source/srcM/empty.rb 
==> Installing dependencies for empty: llvm
==> Installing empty dependency: llvm
==> Downloading https://homebrew.bintray.com/bottles/llvm-3.9.0.yosemite.bottle.tar.gz
Already downloaded: /Volumes/Users/nat/Library/Caches/Homebrew/llvm-3.9.0.yosemite.bottle.tar.gz
==> Pouring llvm-3.9.0.yosemite.bottle.tar.gz
==> Caveats
LLVM executables are installed in /private/tmp/brew/opt/llvm/bin.
Extra tools are installed in /private/tmp/brew/opt/llvm/share/llvm.
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/private/tmp/brew/opt/llvm/lib -Wl,-rpath,/private/tmp/brew/opt/llvm/lib"

This formula is keg-only, which means it was not symlinked into /private/tmp/brew.

macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/private/tmp/brew/opt/llvm/lib
    CPPFLAGS: -I/private/tmp/brew/opt/llvm/include


If you need Python to find bindings for this keg-only formula, run:
  echo /private/tmp/brew/opt/llvm/lib/python2.7/site-packages >> /private/tmp/brew/lib/python2.7/site-packages/llvm.pth
  mkdir -p /Volumes/Users/nat/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/private/tmp/brew/lib/python2.7/site-packages")' >> /Volumes/Users/nat/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /private/tmp/brew/Cellar/llvm/3.9.0: 2,039 files, 714.9M
==> Installing empty
==> Installing dependencies for empty: llvm
nat@kempe:srcM(^) $ brew gist-logs /Volumes/Source/srcM/empty.rb 
Error: No logs.
nat@kempe:srcM(^) $ brew gist-logs empty
Error: No available formula with the name "empty" 
nat@kempe:srcM(^) $ brew gist-logs llvm
Error: No logs.
```

**Comment by MikeMcQuaid** [comment]
> @MikeMcQuaid There are no gist-logs produced. Or what else ?

> Please replace this line with a brief summary of your issue AND the output of brew config and brew doctor or if reporting a formula issue include the link from: brew gist-logs <formula> (where <formula> is the name of the formula that failed to build).
https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md

`brew config` and `brew doctor` output, please.

**Comment by ilovezfs** [comment]
@mulle-nat thanks for elaborating. The immediate problem you have is that `"with-libcxx"` isn't an option on the llvm formula. The option is `"without-libcxx"`. So if you want with-libcxx, specify nothing at all.
```
depends_on "llvm" => :build
```

The more general problem is that it seems https://github.com/Homebrew/brew/issues/1399 isn't actually fixed.

**Comment by mulle-nat** [comment]
OK! Thanks for that information. Last time I had to include `with-libcxx` specifcally to make it work. I hope homebrew stabilizes on one of the two options eventually (each being fine for me).

**Comment by ilovezfs** [comment]
@mulle-nat yeah, the option default was changed recently. Just for the sake of completeness please provide the brew config and brew doctor info Mike requested above.

**Comment by mulle-nat** [comment]
OK, the config:

```
nat@kempe:srcM(^) $ brew config
HOMEBREW_VERSION: 1.1.2-55-ga566540
ORIGIN: https://github.com/homebrew/brew
HEAD: a566540c46563b1ea84158c963134862167ca993
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff3bcae5debad88580ecb01096bb852543c47471
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /private/tmp/brew
HOMEBREW_REPOSITORY: /private/tmp/brew
HOMEBREW_CELLAR: /private/tmp/brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
bGit: 2.10.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_60, 1.6.0_65-b14-468
macOS: 10.10.5-x86_64
rXcode: 7.2.1 => /Applications/Xcode-7.2.1.app/Contents/Developer
eCLT: 7.0.0.0.1.1441394355
wX11: 2.7.9 => /opt/X11
```

**Comment by mulle-nat** [comment]
If i think about it more, I would presume that a bottle implies, that the build did not have any special flags given toit. So if there are flags given, homebrew shouldn't even download the bottle.  That would probably be the easiest solution.

If this assumption is wrong, then homebrew might want to do the following to ensure consistency with flags and bottles. If a bottle is compiled with specific options then:

1. sort all options
2. concatenate all options
3. md5 hash the result string
4. use this hash or parts of it as part of the bottle-url like:   "#{root_url}/#{name}-#{version}-#{hash}.#{tag}.bottle.#{revision}.tar.gz"

That way homebrew can support multiple bottles for different options.

> I don't really understand how homebrew would handle formulas with different options anyway. 
> I guess the first idea is probably better.

**Comment by MikeMcQuaid** [comment]
> So if there are flags required, homebrew shouldn't even download the bottle. That would probably be the easiest solution.

Yep, this is the case now.
