### ISSUE TITLE
brew install python, Error: Couldn't parse manifest JSON, Pouring gdbm--1.19.catalina.bottle.tar.gz 

### ISSUE THREAD

**Issue by imyjimmy** [Homebrew/homebrew-core#77567]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bfcdaf258dadaaf8c102d4cb51f23b6fdb2c4c
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1a82657681434496e22adf9cdc988b080728b051
Core tap last commit: 41 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.3

brew doctor:
Warning: Your Xcode (12.3) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install python 3.8.5 to ultimately install aws-sam-cli

This is because pip3 install --user aws-sam-cli produces an error: architecture not supported on the watchdog package

this comment says it goes away with a newer version of python: https://github.com/gorakhargosh/watchdog/issues/689#issuecomment-700838259

### What happened (include all command output)?

brew install python3
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
atuin                  elan-init              julia                  openexr@2              search-that-hash
cadical                gcc@10                 lsix                   pgxnclient             trojan-go
clazy                  gitbackup              mathlibtools           rmw                    zellij
ddcctl                 ipinfo-cli             neovim-remote          scotch
==> Updated Formulae
Updated 698 formulae.
==> Deleted Formulae
aurora-cli                   erlang@20                    protobuf-swift               protobuf@3.7
==> New Casks
crescendo              jgrennison-openttd     privileges             siyuan                 waltr-pro
cryptonomic-galleon    mem                    pronterface            usr-sse2-rdm
depthmapx              menu-bar-splitter      qudedup-extract-tool   vamiga
ilspy                  mixed-in-key           sbarex-qlmarkdown      vitals
irpf2021               mutesync               shortcutor             vitalsigns
==> Updated Casks
Updated 636 casks.
==> Deleted Casks
adventure              cellery                meshcommander          printrun               spideroak-share
audiobookbinder        family-tree-builder    opennx                 revisions

==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/manifests/1.19
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/bf3024395228e8948861d356d9effabe26c0194b4b55f2dc07a67bd38c834381--gdbm-1.19.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/gdbm/blobs/sha256:a3e43170a1d8413e6817e57b7218828af22a20b2221d804a
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/e54ded2e00a258f62a7abe749bb43defec4df1a3737b5f3e1c79660ce1b110ca--gdbm--1.19.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/manifests/2.5.1
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/f367c2ee08c56b88be0662703a8e4275f8657608a268c8c44e845154b0cea543--mpdecimal-2.5.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/mpdecimal/blobs/sha256:1a8314428019cec85756be0ea10bc4703cd754ef78a
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/5bd35517ae62d36afb8a5f88dee76fb51fa80b12ded2dd204737c9984b417bac--mpdecimal--2.5.1.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/manifests/1.1.1k
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/2efe91096994c33489c066631735a35cc3863cae64fc2ad5b305675fe9d24fed--openssl@1.1-1.1.1k.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/1.1/blobs/sha256:cb610ecdda346011031b890d7b7c6e1942d7fc08c
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/61318ecf3a44d45314830c1b7e93587380921027335bdebdc0132dec6eab4195--openssl@1.1--1.1.1k.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/readline/manifests/8.1
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/b37133a77c8680447162faf218b59fb36ee5d3e1926fbbff244e43581ab9128a--readline-8.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/readline/blobs/sha256:fe4de019cf549376a7743dcb0c86db8a08ca2b6d0dd2
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/96808ad7ca175753b556d52963c9c3425d8fab4b1a378c444eeb341790df6f48--readline--8.1.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/manifests/3.35.5
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/378ec4b4eabacb2e78491282aed532b43a440467b1b9de74c128b026d3c912ba--sqlite-3.35.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/sqlite/blobs/sha256:217e257590018c8e0b2e994f8f8c9fa548459f1532acec
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/61d40ad2021e894bcf4c7475eea2dbbfee14c4426b1bbb1816c4055ad1c70b50--sqlite--3.35.5.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/xz/manifests/5.2.5
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/9447dbb900ef03dd46277002d89d92c65920edee6c60ea22c33be6cf99d01dc6--xz-5.2.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/xz/blobs/sha256:2dcc8e0121c934d1e34ffdb37fcd70f0f7b5c2f4755f2f7cbc
Already downloaded: /Users/jizhang/Library/Caches/Homebrew/downloads/7eceb2ff34a967973ae2fd49bf3a37ed28655d39cc43673e8261220355c3c801--xz--5.2.5.catalina.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/manifests/3.9.5
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/python/3.9/blobs/sha256:5d79eedf91642b87bd25e7b791b941ce9aad4735fe
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5d79eedf91642b87bd25e7b791b941
######################################################################## 100.0%
==> Installing dependencies for python@3.9: gdbm, mpdecimal, openssl@1.1, readline, sqlite and xz
==> Installing python@3.9 dependency: gdbm
==> Pouring gdbm--1.19.catalina.bottle.tar.gz
Error: Couldn't parse manifest JSON.
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:366:in `rescue in tab_attributes'
/usr/local/Homebrew/Library/Homebrew/software_spec.rb:363:in `tab_attributes'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2263:in `bottle_tab_attributes'
/usr/local/Homebrew/Library/Homebrew/utils/bottles.rb:100:in `load_tab'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1147:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:741:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:661:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:393:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:422:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:324:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

### What did you expect to happen?

I expected brew to install python 3.8.5

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python3
```

**Comment by carlocab** [comment]
What's the output of
```
file /Users/jizhang/Library/Caches/Homebrew/downloads/bf3024395228e8948861d356d9effabe26c0194b4b55f2dc07a67bd38c834381--gdbm-1.19.bottle_manifest.json
file /Users/jizhang/Library/Caches/Homebrew/downloads/e54ded2e00a258f62a7abe749bb43defec4df1a3737b5f3e1c79660ce1b110ca--gdbm--1.19.catalina.bottle.tar.gz
```
Also, note that `brew install python3` installs Python3.9, and not Python3.8.

**Comment by megabytemb** [comment]
I Also had this problem.

Turns out my company proxy changed the Json file to an HTML error file.

I manually deleted the json file in the brew cache (in your case, it would be `file /Users/jizhang/Library/Caches/Homebrew/downloads/bf3024395228e8948861d356d9effabe26c0194b4b55f2dc07a67bd38c834381--gdbm-1.19.bottle_manifest.json
`), and re-ran the command and it fixed it.

i think `brew cleanup -s` would achieve the same thing for you.

> For all installed or specific formulae, remove any older versions from the cellar. In addition, old downloads from the Homebrew download-cache are deleted.
> 
> If --prune=days is specified, remove all cache files older than days.
> 
> If --dry-run or -n is passed, show what would be removed, but do not actually remove anything.
> 
> If -s is passed, scrub the cache, removing downloads for even the latest versions of formulae. Note downloads for any installed formulae will still not be deleted. If you want to delete those too: rm -rf $(brew --cache)
