### ISSUE TITLE
GPG 2.3.1 - Yubikey does not work

### ISSUE THREAD

**Issue by BirknerAlex** [Homebrew/homebrew-core#77592]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
alexander:~$ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installed gpg version 2.3.1 on my machine. After installing it `gpg --card-status` does not recognize the Yubikey anymore.

After running `brew uninstall gpg` and `brew install gnupg@2.2` it started to work again with 2.2.27.

### What happened (include all command output)?

```
alexander:~$ gpg --card-status
gpg: selecting card failed: Operation not supported by device
gpg: OpenPGP Karte ist nicht vorhanden: Operation not supported by device
```

### What did you expect to happen?

GPG working with Yubikeys and other smart cards.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install gpg
2. Insert smartcard to mac
3. Run `gpg --card-status` - card not detected
```

**Comment by nandahkrishna** [comment]
Please take a look at https://github.com/Homebrew/homebrew-core/issues/76136, seem like this might be a duplicate of that one.

**Comment by SMillerDev** [comment]
See https://github.com/Homebrew/homebrew-core/pull/75755, it's a known upstream issue

**Comment by carlocab** [comment]
This isn't a bug in the formula, I'm afraid. It's a consequence of design choices made by the gnupg developers.

See https://github.com/Homebrew/homebrew-core/pull/75755.

I suggest you take this up with the devs, or use one of the workarounds in the linked PR.

**Comment by BirknerAlex** [comment]
Oh okay, I will try it, I didn't checked for closed issues. Sorry.

**Comment by jasonkarns** [comment]
FYI, PR to have the gnupg formula configure scdaemon as necessary during installation: https://github.com/Homebrew/homebrew-core/pull/77606
