### ISSUE TITLE
Problem to install mysql and python using homebrew

### ISSUE THREAD

**Issue by sabrinabm** [Homebrew/homebrew-core#77629]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I can't install mysql and python using brew, because of some error in formulae:\
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

MAC terminal using home brew

### What happened (include all command output)?

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "python".
It was migrated from homebrew/cask to homebrew/core.

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "python@3.9".

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "mysql".

### What did you expect to happen?

Install mysql and python

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python

brew install python@3.9

brew install mysql
```

**Comment by carlocab** [comment]
What do `brew config` and `brew doctor` say?

Note that the issue template asks for this. Please don't ignore the issue template when asking for help.

**Comment by sabrinabm** [comment]
> brew config

Hello
HOMEBREW_VERSION: 3.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bfcdaf258dadaaf8c102d4cb51f23b6fdb2c4c
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: HEAD
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.0.1-arm64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A
Rosetta 2: false


Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master

**Comment by carlocab** [comment]
Your core tap is missing. Do
```
rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
brew update
```
then try again.

**Comment by sabrinabm** [comment]
> Your core tap is missing. Do
> 
> ```
> rm -rf $(brew --repo homebrew/core)
> brew tap homebrew/core
> brew update
> ```
> 
> then try again.

I used the command, but not success

brew install mysql@5.6
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
gitwatch                   grepip                     php-cs-fixer@2
==> Updated Formulae
Updated 25 formulae.
==> Updated Casks
Updated 11 casks.

Warning: mysql@5.6 has been deprecated because it is not supported upstream!
Error: mysql@5.6: no bottle available!
You can try to install from source with:
  brew install --build-from-source mysql@5.6
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**Comment by sabrinabm** [comment]
> `mysql@5.6` does not work on ARM. If you need `mysql@5.6`, you'll need to run it under Rosetta in a separate `brew` installation in `/usr/local`. (Your existing `brew` installation is in `/opt/homebrew`.)
> 
> See https://stackoverflow.com/a/64883440/10153385 and related posts for how to do so.
> 
> If you just want MySQL, you can do `brew install mysql`. That works on ARM without having do install another `brew`.

Hello, I`cant install the mysql with the command sent

brew install mysql

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/manifests/69.1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:25a1ec460d42
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sh
##########################################                                58.8%
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: Failed to download resource "icu4c"
Download failed: https://ghcr.io/v2/homebrew/core/icu4c/blobs/sha256:25a1ec460d422ba5abff15dc5cb60ad36003ad021585fa7be278d1dca6fcd2c4

**Comment by carlocab** [comment]
```
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```
That's a connection issue and not a `brew` issue. Since that's specific to your connection, I can't help you with that. Please see the posts at https://github.com/Homebrew/discussions/discussions for tips on how other users have dealt with it.
