### ISSUE TITLE
ocp broken 

### ISSUE THREAD

**Issue by danielktdoranie** [Homebrew/homebrew-core#77626]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Hi!

so ocp appears to work but there's no audio. I chatted with the dev on IRC and he said that line 39 in ocp.rb disables sdl2 but it should enable it in order for audio to work, could you please edit?

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ocp.rb
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Use ocp to play mod files

### What happened (include all command output)?

No audio when using ocp

danieldoran@Daniels-MacBook-Pro ~ % ocp
Setting to cfConfigDir to /Users/danieldoran/.ocp/
Setting to cfDataDir to /usr/local/Cellar/ocp/0.2.2/share/ocp-0.2.2/data/
Setting to cfProgramDir to /usr/local/Cellar/ocp/0.2.2/lib/ocp-0.2.2/
Open Cubic Player for Unix v0.2.2, compiled on Dec 10 2020, 04:39:19
Ported to Unix by Stian Skjelstad
linking default objects...
running initializers...
initializing fileselector...
adbInit: open(cfConfigDir/CPARCS.DAT): No such file or directory
Loading /Users/danieldoran/.ocp/CPMODNFO.DAT .. Done
open(cfConfigDir/CPDIRDB.DAT): No such file or directory
Initing console...
Initing curses... (ncurses 5.7.20081102)
curses: will use UTF-8 characters instead of ASCII + ACS
wavetabledevices:
 devwMixF: FPU Mixer....................... (#1 t0)
 devwmixQ: Mixer........................... (#2 t1)
 devwMix : Mixer........................... (#3 t0)
 devwNone: None............................ (#4)
FPU Mixer selected...
[devwmixf] INIT, using dwmixfa.c C version

playerdevices:
 devpALSA: dlopen(/usr/local/Cellar/ocp/0.2.2/lib/ocp-0.2.2/devpalsa.dylib, 10): image not found
link error
 devpOSS : dlopen(/usr/local/Cellar/ocp/0.2.2/lib/ocp-0.2.2/devposs.dylib, 10): image not found
link error
 devpCA  : CoreAudio player................[CoreAudio] Unable to initialize Output Unit component (status = -66748 (unknown))
 not found: optimize ocp.ini!
 devpSDL2: dlopen(/usr/local/Cellar/ocp/0.2.2/lib/ocp-0.2.2/devpsdl2.dylib, 10): image not found
link error
 devpSDL : dlopen(/usr/local/Cellar/ocp/0.2.2/lib/ocp-0.2.2/devpsdl.dylib, 10): image not found
link error
 devpNone: Super High Quality Quiet Player. (#2)
 devpDisk: Disk Writer..................... (#3)
Super High Quality Quiet Player selected...

samplerdevices:
 devsOSS : dlopen(/usr/local/Cellar/ocp/0.2.2/lib/ocp-0.2.2/devsoss.dylib, 10): image not found
link error
 devsNone: Eternal Silence Recorder........ (#1)
Eternal Silence Recorder selected...

### What did you expect to happen?

Hear pretty music when I use ocp

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ocp
```

**Comment by carlocab** [comment]
We'll accept a pull request to fix this. Thanks!

https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-contribute-a-fix-to-the-foo-formula

**Comment by danielktdoranie** [comment]
Thank you!

**Comment by danielktdoranie** [comment]
BTW, this is on an Intel Mac. MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) w/ 16GB RAM and macOS Big Sur 11.3.1, thanks

**Comment by carlocab** [comment]
In case I wasn't clear with my previous comment: you're meant to be working on a pull request to fix this -- if you want it fixed, that is.

I suppose you can also wait and see if someone else will come along and fixes it for you, but I wouldn't say it's a good idea to count on that.

**Comment by danielktdoranie** [comment]
I am not a developer. I am just letting y'all know it's broken.

**Comment by carlocab** [comment]
Neither are many contributors. Never a bad time to start -- if you get stuck we're happy to help you along.

**Comment by danielktdoranie** [comment]
No thanks, I don't want to be developer. I do enough as it is, thank you. I just want to use the software.

**Comment by carlocab** [comment]
That's too bad. It seems unlikely that anyone will be working on this then, so I'm closing this issue. We can reopen it if I'm mistaken.

If you change your mind about giving this a try, just feel free to open a pull request.

**Comment by danielktdoranie** [comment]
Okay so it's broken and you won't fix it. Awesome.

**Comment by carlocab** [comment]
I do enough as it is, thank you.

**Comment by danielktdoranie** [comment]
And with this interaction I have moved to MacPorts

**Comment by carlocab** [comment]
Good. Hope you find what you're looking for there.

**Comment by nandahkrishna** [comment]
For anyone looking at this issue, `ocp` should be able to play audio with version `0.2.90`.

@danielktdoranie Please do understand that maintainers are volunteers, and may not have the time to fix every issue.
