### ISSUE TITLE
It was migrated from homebrew/cask to homebrew/core.

### ISSUE THREAD

**Issue by shams-mac-m1** [Homebrew/homebrew-core#77730]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.5.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9-config
  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3-config

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install go

### What happened (include all command output)?

shams@MacBook-de-shams ~ % brew install go
Updating Homebrew...
fatal: Could not resolve HEAD to a revision
==> Homebrew has enabled anonymous aggregate formula and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics have been recorded yet (nor will be during this `brew` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/cask
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask'...
remote: Enumerating objects: 572692, done.
remote: Counting objects: 100% (225/225), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 572692 (delta 115), reused 178 (delta 107), pack-reused 572467
Receiving objects: 100% (572692/572692), 251.69 MiB | 873.00 KiB/s, done.
Resolving deltas: 100% (404350/404350), done.
Updating files: 100% (3981/3981), done.
Tapped 3913 casks (3,992 files, 270MB).
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "go".
It was migrated from homebrew/cask to homebrew/core.

### What did you expect to happen?

dont now

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install go
```

**Comment by shams-mac-m1** [comment]
old mackbook

**Comment by carlocab** [comment]
Where is the output of `brew config`?

**Comment by Prakul2006** [comment]
its not working

**Comment by SMillerDev** [comment]
What isn't? What did you try? What is the output?

**Comment by carlocab** [comment]
Try
```
rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core
```
