### ISSUE TITLE
Perl upgrade to 5.34.0 breaks cpan: loadable library and perl binaries are mismatched

### ISSUE THREAD

**Issue by ralphrmartin** [Homebrew/homebrew-core#77797]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/9756c0542e969626e1862672b7efdb04
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew upgrade perl
and subsequently use 
cpan

### What happened (include all command output)?

brew upgrade perl
proceeded without any apparent errors, but after doing so, cpan failed to work:
cpan
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xfa80080, needed 0xf880080)

### What did you expect to happen?

cpan should work

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
I had previously installed perl
and then I had previously followed the steps to persist modules across versions:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.zshrc
and installed various Perl modules
so my modules from the previous version were in my home directory.
I then did 
brew upgrade perl

I also tried reinstalling perl from source. That did not help either.
```

**Comment by carlocab** [comment]
Should be fixed with a
```
brew update && brew reinstall perl
````

Let me know in case that doesn't help. Thanks for the report.

**Comment by ralphrmartin** [comment]
Thanks. Unfortunately I cannot test the fix as I deleted my perl5 folder in my home directory and reinstalled my Perl modules from scratch as I needed them urgently.

**Comment by carlocab** [comment]
Ah, I see. Apologies for the inconvenience.
