### ISSUE TITLE
Homebrew MySQL 8.0.25 with deprecated default character set

### ISSUE THREAD

**Issue by kkbt** [Homebrew/homebrew-core#77805]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: e0bfcdaf258dadaaf8c102d4cb51f23b6fdb2c4c
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ff8cdac8e222e011f28a91c9157f2c409b5fbe82
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3.1-arm64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A
Rosetta 2: false


% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/freetype-config
  /usr/local/bin/libpng16-config
  /usr/local/bin/libpng-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installing MySQL to have an SQL database server.

### What happened (include all command output)?

For good reaons MySQL has switched to a new default character set (utf8mb4) and a new default collation (utf8mb4_0900_ai_ci) some years ago.

However, the homebrew package deviates from this and behaves different than the original installation package from Oracle.

The original package from https://www.mysql.com shows the desired behaviour:

```
mysql> SHOW VARIABLES LIKE 'character%'; SHOW VARIABLES LIKE 'collation%';
+--------------------------+-----------------------------------------------------------+
| Variable_name            | Value                                                     |
+--------------------------+-----------------------------------------------------------+
| character_set_client     | utf8mb4                                                   |
| character_set_connection | utf8mb4                                                   |
| character_set_database   | utf8mb4                                                   |
| character_set_filesystem | binary                                                    |
| character_set_results    | utf8mb4                                                   |
| character_set_server     | utf8mb4                                                   |
| character_set_system     | utf8                                                      |
| character_sets_dir       | /usr/local/mysql-8.0.12-macos10.13-x86_64/share/charsets/ |
+--------------------------+-----------------------------------------------------------+
8 rows in set (0,15 sec)

+----------------------+--------------------+
| Variable_name        | Value              |
+----------------------+--------------------+
| collation_connection | utf8mb4_0900_ai_ci |
| collation_database   | utf8mb4_0900_ai_ci |
| collation_server     | utf8mb4_0900_ai_ci |
+----------------------+--------------------+
3 rows in set (0,01 sec)
```

But the current Homebrew package https://formulae.brew.sh/formula/mysql is set up with some latin1 encoding if installed from scratch, messing up accent characters (e.g., as required for German, French).

```
% brew info mysql
mysql: stable 8.0.25 (bottled)
% sw_vers 
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
% machine
arm64e
```

(I cannot reproduce further details now without removing my database.)

I was able to fix this by updating /opt/homebrew/etc/my.cnf, however, the new default character set (utf8mb4) and the new default collation (utf8mb4_0900_ai_ci) should be in effect without time-consuming manual configurations:

```
# Default Homebrew MySQL server config
[mysqld]
# Only allow connections from localhost
bind-address = 127.0.0.1
mysqlx-bind-address = 127.0.0.1
character-set-server = utf8mb4
collation-server = utf8mb4_0900_ai_ci

[client]
default-character-set = utf8mb4

[mysql]
default-character-set = utf8mb4
```

Related links:

"From MySQL 8.0, utf8mb4 is the default character set, and the default collation for utf8mb4 is utf8mb4_0900_ai_ci."
MySQL 8.0 Collations: Migrating from older collations (April 24, 2017)
https://mysqlserverteam.com/mysql-8-0-collations-migrating-from-older-collations/

"As we no longer see a strong use-case for utf8mb3, we intend to mark it as deprecated in MySQL 8.0."
MySQL 8.0: When to use utf8mb3 over utf8mb4? (May 19, 2017)
https://mysqlserverteam.com/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/

"For applications that store data using the default MySQL character set and collation (utf8mb4, utf8mb4_0900_ai_ci), no special configuration should be needed."
1.5 Configuring Application Character Set and Collation
https://dev.mysql.com/doc/mysql-g11n-excerpt/8.0/en/charset-applications.html

https://mysqlserverteam.com/new-defaults-in-mysql-8-0/
https://www.monolune.com/what-is-the-utf8mb4_0900_ai_ci-collation/
https://adamhooper.medium.com/in-mysql-never-use-utf8-use-utf8mb4-11761243e434
https://www.hydroxi.de/utf8-vs-utf8mb4/
https://github.com/Homebrew/homebrew-core/pull/49413
https://github.com/Homebrew/homebrew-core/issues/49411
https://stackoverflow.com/questions/3513773/change-mysql-default-character-set-to-utf-8-in-my-cnf

### What did you expect to happen?

Consistent use of the default character set (**utf8mb4**) and the default collation (**utf8mb4_0900_ai_ci**) in a new, unconfigured installation of MySQL (**NOT: the obsolete latin1 character set**!).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mysql  # MySQL database
```

**Comment by SMillerDev** [comment]
As you can see here: https://github.com/Homebrew/homebrew-core/blob/4059a766e1c6c59d66b16337b7a7637810e46c32/Formula/mysql.rb

Homebrew does not set a specific default. That means this is a bug in the build script and it should be reported and fixed upstream.
