### ISSUE TITLE
How can yarn work with node@6 ?

### ISSUE THREAD

**Issue by Treri** [Homebrew/homebrew-core#7786]
yarn depend on `node` in `brew info yarn`
If I install yarn via brew, the latest version 7.x node will also be installed. But 6.x is the LTS version.

And If I have installed node@6, it can not satisfy yarn's `node` requirements

How can yarn installed with node@{4,5,6} ?

**Comment by MikeMcQuaid** [comment]
It cannot currently, sorry.

**Comment by MikeMcQuaid** [comment]
You may be able to `npm install yarn` with `node@6`'s `npm`.

**Comment by SebastienElet** [comment]
`npm install yarn` throw a deprecated and suggest to use brew, it looks like circular reference.

**Comment by MikeMcQuaid** [comment]
@SebastienElet Sorry, that's not Homebrew's issue to fix.

**Comment by SuperMarioBean** [comment]
you can try

```
brew install node@6 --without-npm
brew install yarn --ignore-dependencies
```

remember your need make the node@6 in your path, follow the info from `brew info node@6`
