### ISSUE TITLE
djvulibre: Broken download path (cf #73358)

### ISSUE THREAD

**Issue by th122** [Homebrew/homebrew-core#77860]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.8-66-ga3e6a84
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: a3e6a842ce6b744a38b493f85ff1ec58cd04a877
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9fe5683ba7a67311907c6cc2e8a6b7f6a238f74d
Core tap last commit: 22 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /Volumes/local/Homebrew
HOMEBREW_CACHE: /Volumes/local/Cache
HOMEBREW_CASK_OPTS: ["--appdir=/Volumes/Applications", "--caskroom=/Volumes/local/Caskroom"]
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.WBvPWUWAW1/org.xquartz:0
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_TEMP: /Volumes/local/tmp
Homebrew Ruby: 2.6.3 => /Volumes/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit penryn
Clang: 10.0.0 build 1000
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.0
XQuartz: 2.7.11 => /opt/X11 => /Volumes/opt/X11
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

upgrade djvulibre on MacOS (Yes it's an older System due to the age of the platform, and brew doctor complains about that, but for this issue that`s pretty irrelevant.)

### What happened (include all command output)?

- `brew upgrade djvulibre`

```
==> Upgrading 1 outdated package:
djvulibre 3.5.27_1 -> 3.5.28
==> Upgrading djvulibre 3.5.27_1 -> 3.5.28 
==> Downloading https://downloads.sourceforge.net/project/djvu/DjVuLibre/3%2C5%2C28/djvulibre-3.5.28.tar.gz

curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "djvulibre"
Download failed: https://downloads.sourceforge.net/project/djvu/DjVuLibre/3%2C5%2C28/djvulibre-3.5.28.tar.gz
```
Manually, the download succeeds when the URL is fixed beforehand.
- `% wget https://downloads.sourceforge.net/project/djvu/DjVuLibre/3.5.28/djvulibre-3.5.28.tar.gz`
```
--2021-05-22 23:44:36--  https://downloads.sourceforge.net/project/djvu/DjVuLibre/3.5.28/djvulibre-3.5.28.tar.gz
```

### What did you expect to happen?

download from sourceforge. Instead the garbled URL in the djvulibre.rb results in a 404 at download.

* `% grep url\.\*sourceforge /Volumes/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/djvulibre.rb`
  `url "https://downloads.sourceforge.net/project/djvu/DjVuLibre/3%2C5%2C28/djvulibre-3.5.28.tar.gz"`

compare the correct URL version currently in the cellar:

* `% grep url\.\*sourceforge /Volumes/local/Cellar/djvulibre/3.5.27_1/.brew/djvulibre.rb`
     `url "https://downloads.sourceforge.net/project/djvu/DjVuLibre/3.5.27/djvulibre-3.5.27.tar.gz"`

Looks like this was also addressed in #73358 but got closed?

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just taking a look at the `djvulibre.rb` should make the problem pretty obvious. Looks like a cut-and-paste URL from browser issue.
```

**Comment by carlocab** [comment]
Please open a pull request for this; thanks. (I believe should also be what `brew doctor` tells you, but you omitted this information despite it being requested.)
