### ISSUE TITLE
emacs fails to launch, missesing libMagickWand-6.Q16.2.dylib

### ISSUE THREAD

**Issue by ryofurue** [Homebrew/homebrew-core#7791]
### Bug reports:
Emacs.app fails to launch with "LSOpenURLsWithRole() failed with error -10810 . . . ."

~/Library/Logs/DiagnosticReports/Emacs_2016-12-12-205629. . . includes

    Dyld Error Message:
      Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
      Referenced from: /usr/local/Cellar/emacs/25.1/Emacs.app/Contents/MacOS/Emacs
      Reason: image not found

Indeed "libMagickWand" has been upgraded to "6.Q16.3" .  I've re-installed emacs and the problem went away.

Hope this helps,

Ryo
-----------------------------
Everyday I "brew update" and "brew upgrade".  But, after the re-installation of emacs, I updated again.  So the following information may be obsolete.  Sorry.

$ brew config
HOMEBREW_VERSION: 1.1.2-75-gebe4549
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ebe45490b61decfd53574df615ab3d9e775c938e
Last commit: 23 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a4d50c465d7398710f04022fafea080c7da83347
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.9.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/furue/miniconda3/bin/python => /Users/furue/miniconda3/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: 8.1.0.0.1.1476494586
X11: 2.7.11 => /opt/X11
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/furue/miniconda3/bin/python3-config
  /Users/furue/miniconda3/bin/python3.5-config
  /Users/furue/miniconda3/bin/python3.5m-config
$

**Comment by ilovezfs** [comment]
This is normal. Because the GUI version of the emacs formula is not the default, emacs is not revision bumped when imagemagick is upgraded: https://github.com/Homebrew/homebrew-core/pull/7775.
