### ISSUE TITLE
brew install mplayer failed on m1 macbook pro

### ISSUE THREAD

**Issue by ptpt52** [Homebrew/homebrew-core#77917]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/f83642e876be0c3a574070b7a1c8cb34
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install mplayer

### What happened (include all command output)?

Updating Homebrew...
==> Downloading https://mplayerhq.hu/MPlayer/releases/MPlayer-1.4.tar.xz
Already downloaded: /Users/ptpt52/Library/Caches/Homebrew/downloads/e46ff67a76310e16a226948e7a55830f101013704355db6bc656c1d205946223--MPlayer-1.4.tar.xz
==> ./configure --cc=clang --host-cc=clang --disable-cdparanoia --prefix=/Users/ptpt52/vmroot/Cellar/mplayer/1.4_2 --disable-x11 --enable-caca --enable-freetype --disable-libbs2b
==> make
Last 15 lines from /Users/ptpt52/Library/Logs/Homebrew/mplayer/02.make:
<inline asm>:1:7: note: instantiated into assembly here
        ldrh x8, [x0]
             ^
In file included from libavfilter/drawutils.c:27:
In file included from ./libavutil/intreadwrite.h:68:
./libavutil/arm/intreadwrite.h:46:14: error: invalid operand for instruction
    __asm__ ("strh %1, %0" : "=m"(*(uint16_t *)p) : "r"(v));
             ^
<inline asm>:1:7: note: instantiated into assembly here
        strh x8, [x0]
             ^
8 errors generated.
make[1]: *** [libavfilter/drawutils.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [ffmpeg/libavfilter/libavfilter.a] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

### What did you expect to happen?

install mplayer success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mplayer
```

**Comment by carlocab** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!

Building from source is unsupported. Please install from the bottle instead.

**Comment by ptpt52** [comment]
@carlocab  but any guide/docs to help me, to build it from source? please.

**Comment by carlocab** [comment]
You can check the upstream documentation for that. Why do you need to build this from source?
