### ISSUE TITLE
MacVim broken on macOS 11.4

### ISSUE THREAD

**Issue by BrettDong** [Homebrew/homebrew-core#77976]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

`brew config`:

```
HOMEBREW_VERSION: 3.1.9-5-g1bdfacd
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1bdfacddc07ad316deb7baff33934ee3d45f17a9
Last commit: 73 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 28332e9c11143b444b358be8af7ac748f00e2d4f
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false
```

`brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  imath
  openexr

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Launch `vim` in terminal.

### What happened (include all command output)?

Get the error
```
dyld: Library not loaded: /System/Library/Perl/5.28/darwin-thread-multi-2level/CORE/libperl.dylib
  Referenced from: /opt/homebrew/Cellar/macvim/8.2-171/MacVim.app/Contents/MacOS/Vim
  Reason: image not found
zsh: abort      vim
```
and `vim` doesn't launch.

### What did you expect to happen?

`vim` should launch.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew reinstall macvim
vim
```
```

**Comment by carlocab** [comment]
If you don't mind installing Xcode, can you try `brew reinstall -s macvim`? Let us know if you try it and it helps.

**Comment by xorcat** [comment]
I've had the exact same issue hours ago, and resolved it by making sure that a full copy of Xcode is installed, and running:

```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
brew reinstall ruby
```

The `brew reinstall ruby` also triggered a reinstall of macvim, which resolved the issue. The issue was not resolved simply with a `brew reinstall macvim`, the `brew reinstall ruby` was required.

**Comment by carlocab** [comment]
Thanks, @xorcat. Though, it's not clear to me why that should fix it, as it sounds to me like `ruby` should've installed from a bottle. Did you have to rebuild `ruby` from source?

**Comment by xorcat** [comment]
@carlocab 

That's true - ruby did come from a bottle.

Perhaps what did it was that reinstalling ruby triggered `macvim` to reinstall from source - when I had previously run `brew reinstall macvim` I hadn't included `-s`.

Maybe `brew reinstall -s macvim`, with a full Xcode instance (I had failures when I only had the Xcode CLI tools installed/selected) would have fixed it for me.

**Comment by BrettDong** [comment]
I worked around the issue by manually editing the binary executable `/opt/homebrew/opt/macvim/MacVim.app/Contents/MacOS/Vim`, replacing three occurrences of `5.28` to `5.30` and re-codesigned the binary.

**Comment by wpniederer** [comment]
I was having the same issue and was able to resolve it with these steps (after doing a full install of Xcode):
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
brew reinstall -s macvim
```

After that I could run mvim and mvim -v with no issues. Interestingly, I had to set a manual alias to MacVim instead of the built in Vim. Didn't have to do that before.

**Comment by itsayellow** [comment]
The Homebrew `vim` formula seems to use the Homebrew `perl`:
https://github.com/Homebrew/homebrew-core/blob/7e766a209b0c1b7cbace573ee2b99f896eb785d0/Formula/vim.rb#L21

It's still working after the macOS upgrade.  Perhaps the macvim formula should ensure it also `depends_on "perl"` so the compiled version doesn't link to the system perl and is more stable.

**Comment by mgax** [comment]
`brew install --cask macvim` also works, until the formula is fixed.
