### ISSUE TITLE
pip3 install wxpython (Mac Air M1) - issues with CXXFLAGS re tiff.h

### ISSUE THREAD

**Issue by LandyQuack** [Homebrew/homebrew-core#78023]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
homebrew % brew config
HOMEBREW_VERSION: 3.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 76cfe88b7628a8010bf98115627f6aced4ff8870
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 307fb67dc5cad224270e825eaaf2024da1d6b276
Core tap last commit: 44 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.3-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false


brew doctor  
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/ansible-config

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install wxpython under Python 3.9 (from brew) using /opt/homebrew/bin/pip3.

Without export CXXFLAGS=-I/opt/homebrew/include prior to pip3 install wxpython, the install bombs out after not finding tiff.h in the include path.

Sorry, didn't keep cli output but https://github.com/wxWidgets/Phoenix/issues/1852 shows same.

Adding the export above resolved for me so thought it was worth sharing.

### What happened (include all command output)?

See above

### What did you expect to happen?

Clean install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As above - pip3 install wxpython after brew install python
```

**Comment by carlocab** [comment]
Needing extra configuration to add `/opt/homebrew/include` to the include search path is expected behaviour. This is true about a lot of formulae other than `python@3.9`.

We'll review a pull request to try to improve this, but I'm not necessarily convinced we should. Forcing things into a compiler's search path can have lots of unintended consequences on builds, and those are often more annoying and difficult to deal with than just not including them by default in the first place (where the fix is to just set `{C,CXX,LD}FLAGS`, or similar).
