### ISSUE TITLE
`brew upgrade` downloads wrong files.

### ISSUE THREAD

**Issue by alandawkins** [Homebrew/homebrew-core#78080]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.1.9-12-ge005ba3
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: e005ba34da4589e433bafb4417e6335fbab43a66
Last commit: 3 hours ago
Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: e932ec2d096932556dcfefc64c7fd8a0ac9025ff
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-bottles/bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 11.0.0 build 1100
Git: 2.31.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 11.3.1.0.1.1576735732
Xcode: N/A

brew doctor:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Suspicious https://github.com/Homebrew/brew git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew" remote set-url origin https://github.com/Homebrew/brew

Warning: Suspicious https://github.com/Homebrew/homebrew-core git origin remote found.
The current git origin is:
  https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git

With a non-standard origin, Homebrew won't update properly.
You can solve this by setting the origin remote:
  git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew update` and `brew upgrade`

### What happened (include all command output)?

`brew upgrade`:
==> Upgrading 3 outdated packages:
vim 8.2.2825 -> 8.2.2875_1
libidn2 2.3.0 -> 2.3.1
perl 5.32.1_1 -> 5.34.0
==> Upgrading vim 8.2.2825 -> 8.2.2875_1 
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-bottles/bottles/perl-5.34.0.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 
Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/perl/manifests/5.34.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/perl/blobs/sha256:2222c3f09bdcd10640720d2f52ba71e09408ead129bc77853b2fdf88fc38106
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:2222c3f09bdcd10640720d2f52ba71e09408ead129bc7
######################################################################## 100.0%
==> Downloading https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-bottles/bottles/vim-8.2.2875_1.mojave.bottle.tar.gz

curl: (22) The requested URL returned error: 404 
Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/vim/manifests/8.2.2875_1
Already downloaded: /Users/alandawkins/Library/Caches/Homebrew/downloads/25e821f426a333bc16c0dbeded9780d2ea4d419e916c04c6995b1cf603228df3--vim-8.2.2875_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/vim/blobs/sha256:84580564e5481145c2f485b118343e85c7c246fcbaae74974f888bccba11a5d3
Already downloaded: /Users/alandawkins/Library/Caches/Homebrew/downloads/dfbb4e71588e036c65433ba8374abd1a20d83965f6b6113a5aed64b48fd2dea0--vim--8.2.2875_1.mojave.bottle.tar.gz
==> Installing dependencies for vim: perl
==> Installing vim dependency: perl
==> Pouring perl-5.34.0.mojave.bottle.tar.gz
tar: Error opening archive: Failed to open '/Users/alandawkins/Library/Caches/Homebrew/downloads/48bdd586d30f7e116b1daae46c9d97fc7067dd7fdb19d808e883d3db884c5ca6--perl-5.34.0.mojave.bottle.tar.gz'
Error: Failure while executing; `tar --extract --no-same-owner --file /Users/alandawkins/Library/Caches/Homebrew/downloads/48bdd586d30f7e116b1daae46c9d97fc7067dd7fdb19d808e883d3db884c5ca6--perl-5.34.0.mojave.bottle.tar.gz --directory /private/tmp/d20210526-9017-1qj6l3e` exited with 1. Here's the output:
tar: Error opening archive: Failed to open '/Users/alandawkins/Library/Caches/Homebrew/downloads/48bdd586d30f7e116b1daae46c9d97fc7067dd7fdb19d808e883d3db884c5ca6--perl-5.34.0.mojave.bottle.tar.gz'

### What did you expect to happen?

upgrade formulaes without problem.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew update` and `brew upgrade`
```

**Comment by gromgit** [comment]
> ```
> tar: Error opening archive: Failed to open ...
> ```
That suggests a permissions issue. To be sure, what's the output of the following commands?
```
ls -ld /Users/alandawkins/Library/Caches/Homebrew/downloads
ls -l /Users/alandawkins/Library/Caches/Homebrew/downloads/48bdd586d30f7e116b1daae46c9d97fc7067dd7fdb19d808e883d3db884c5ca6--perl-5.34.0.mojave.bottle.tar.gz
sha256sum /Users/alandawkins/Library/Caches/Homebrew/downloads/48bdd586d30f7e116b1daae46c9d97fc7067dd7fdb19d808e883d3db884c5ca6--perl-5.34.0.mojave.bottle.tar.gz
```

**Comment by carlocab** [comment]
This is likely your problem:
```
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.tuna.tsinghua.edu.cn/homebrew/homebrew-bottles/bottles
```
Please
```
unset HOMEBREW_BOTTLE_DOMAIN
```
then try again.
