### ISSUE TITLE
Percona server does not have the --ssl option

### ISSUE THREAD

**Issue by dalin-** [Homebrew/homebrew-core#78179]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs percona-server
Error: No logs.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

All variants of MySQL have supported the --ssl flag since MySQL 5.7 (6yrs ago).  But for some reason the homebrew version of Percona Server doesn't have it.  Was it built without that option?

### What happened (include all command output)?

 mysql --user=***** --host=***** --port=****** --password=***** ****** --ssl
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [ERROR] unknown option '--ssl'.

### What did you expect to happen?

Successful connection

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install percona-server
```

**Comment by gromgit** [comment]
> All variants of MySQL have supported the --ssl flag since MySQL 5.7 (6yrs ago).

All variants of the MySQL _server_ may have supported the `--ssl` flag.

But the MySQL _client_, which is what you invoked with:
```bash
mysql --user=***** --host=***** --port=****** --password=***** ****** --ssl
```
doesn't, according to MySQL's own docs: https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html
