### ISSUE TITLE
Missing include dir in kahip

### ISSUE THREAD

**Issue by BrushXue** [Homebrew/homebrew-core#78377]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs kahip
Error: No logs.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Can not find kahip header files. There's no `include` dir
```
$ ls
COPYING              LICENSE              bin
Changelog            NOTES                lib
INSTALL_RECEIPT.json README.md
```

### What happened (include all command output)?

N/A

### What did you expect to happen?

N/A

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by carlocab** [comment]
All the formula does is this:

https://github.com/Homebrew/homebrew-core/blob/1377823336eafa0decea6a4d98e0568039cfdf83/Formula/kahip.rb#L29-L32

If there's a missing `include` directory, it's because it wasn't installed by `make install`. You should probably ask upstream why their `make install` doesn't do this.

**Comment by BrushXue** [comment]
@carlocab If you look at the spack script:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/kahip/package.py
They have the `include` directory.

**Comment by BrushXue** [comment]
Here's a linux HPC resource I have:
```sh
$ pwd
/share/Apps/lusoft/opt/spack/linux-centos8-haswell/gcc-8.3.1/kahip/2.00-gjnvafn/include
$ ls
kaHIP_interface.h
```
That version is installed by spack, and the header file is good.

**Comment by carlocab** [comment]
That's because they're installing the `*.h` files manually. Isn't the right place to fix this in upstream's build system, rather than have all of `kahip`'s users manually install headers on their own because `make install` doesn't?

**Comment by BrushXue** [comment]
https://github.com/KaHIP/KaHIP/blob/master/compile_withcmake.sh
The official came script just copies the header file manually...

**Comment by carlocab** [comment]
There are 697 formulae that depend on CMake in Homebrew/core. Only 15 of them manually install files into the `include` directory. Those 15 probably shouldn't even need to be doing that.

**Comment by BrushXue** [comment]
Yes I understand it's their fault. If you feel it's inappropriate to add workarounds to the formula, I can copy the header file myself until the upstream fixes it.

**Comment by carlocab** [comment]
I'm open to a pull request that adds a workaround to the formula. However, we should at least have an issue opened upstream so that the workaround can at least be removed eventually.

**Comment by BrushXue** [comment]
https://github.com/KaHIP/KaHIP/issues/40
The issue was fixed in v3.00
So if you bump the version it will be fixed.

**Comment by carlocab** [comment]
Great; this should help you get started with that: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#contributing-to-homebrew

**Comment by BrushXue** [comment]
The header is fixed but still doesn't work. Now `libkahip.dylib` is missing in `lib` and there's `libinterface.dylib` instead.

https://github.com/KaHIP/KaHIP/blob/master/compile_withcmake.sh#L50-L51

The upstream script really confuses me. Why do they rename the file?
