### ISSUE TITLE
Exiftool is fairly out of date

### ISSUE THREAD

**Issue by JetForMe** [Homebrew/homebrew-core#7839]
Exiftool is up to 10.36, and includes support for more Photo Sphere tags.

```
$ brew info exiftool
exiftool: stable 10.20 (bottled), devel 10.25
Perl lib for reading and writing EXIF metadata
http://www.sno.phy.queensu.ca/~phil/exiftool/index.html
/usr/local/Cellar/exiftool/10.20 (203 files, 11.8M) *
  Poured from bottle on 2016-12-09 at 16:39:04
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/exiftool.rb
```

**Comment by SuperHenkie** [comment]
+1 just stumbled on this while I was looking why the latest homebrew only gets exiftool 10.20 while the latest stable is already 10.36.

I'm not really familiar with the maintenance or updating process. As in who or what causes homebrew to catch up. Does somebody have to update the exiftool formula? Can anyone do this? Can we, users of exiftool amongst the homebrew community, be of service here?

**Comment by ilovezfs** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
Looks like you have an :angel: watching over you: https://github.com/Homebrew/homebrew-core/pull/7894

**Comment by JetForMe** [comment]
Thanks!
