### ISSUE TITLE
openmotif failed to build on 10.10.5

### ISSUE THREAD

**Issue by jtarp26** [Homebrew/homebrew-core#7841]
### Bug reports:

I'm attempting to install the mbsystem package, using the patch from https://github.com/Homebrew/homebrew-x11/issues/255 as instructed by the MBsystem support team. I fixed all issues from 'brew doctor' and below is the output from 'brew config'. The URL to the gist-log is "https://gist.github.com/anonymous/cab6bc323cec23b89abc1e1bef400e26". I am new to github and using command line, so apologies for any ignorance on my part. With that said, I'd really appreciate being pointed in the right direction as I cannot make heads or tails of this.

HOMEBREW_VERSION: 1.1.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 99f42146c06333f820f45ed1940c5487990e2b31
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 16c4d6bbdbde636adc836c4826d7b52df894447d
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.5.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_111
macOS: 10.10.5-x86_64
Xcode: 7.2.1
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11

**Comment by ilovezfs** [comment]
mbsystem is a homebrew/science formula. Please reopen this issue here: https://github.com/Homebrew/homebrew-science/issues
