### ISSUE TITLE
How could I install the emacs24.x

### ISSUE THREAD

**Issue by ka1em** [Homebrew/homebrew-core#7843]
I run brew info emacs，but the version is 25.x
How could I install the emacs24.x？

**Comment by zmwangx** [comment]
First,

```
$ brew unlink emacs
```

if you have emacs 25.1 installed.

Next,

```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a03b944b96e79125fe06a37de41035e7df594e2e/Formula/emacs.rb
```

You might want to `install -s` to build from source if linkage of the bottle has been broken.

Later you can

```
$ brew switch emacs 25.1
```

if you still have the 25.1 keg and want to switch back to 25.1.

Note that you're on your own when you do this; you won't get support for emacs 24.5 here.

**Comment by MikeMcQuaid** [comment]
Sorry, we do not support installing old versions of software (yet).
