### ISSUE TITLE
jmeter dependency has error in mac

### ISSUE THREAD

**Issue by lizhaode** [Homebrew/homebrew-core#78451]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew info jmeter` shows its dependency openjdk

but brew's OpenJDK is 16 version, it not satisfied with jmeter

when I change to 1.8 version, jmeter works well
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

change jdk version to 1.8, the issue is gone

### What happened (include all command output)?

jdk16 will raise an exception when jmeter window open a file

### What did you expect to happen?

jmeter is not fit 16 version jdk

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install jmeter
2. open jmeter with window mode
3. click open icon

jmeter cause exception and not show open file window
```

**Comment by SMillerDev** [comment]
Does the jmeter project support openjdk 16?

**Comment by cho-m** [comment]
Can you compare your stacktrace with this upstream issue: https://bz.apache.org/bugzilla/show_bug.cgi?id=65300 ?

Looking at repo https://github.com/apache/jmeter, it looks like upstream usually runs tests on JDK14, JDK11, and older, but they do have recent (unreleased) commits for fixing issues with JDK16 and JDK17.

For now, while fixes are not in a release, we can:
- try downgrading to `openjdk@11`
- try using java options like `--add-exports` or `--illegal-access=permit`

**Comment by carlocab** [comment]
Sounds like a duplicate of #66953.

**Comment by cho-m** [comment]
I think we need the exception/stacktrace to identify if root cause is the same.

---

If the exception is an `IllegalAccessError`, then it is specific to JDK16 update and root cause would be different from #66953 (i.e. an upstream issue).

Specifically, in the case of illegal access, JDK16 now defaults to `--illegal-access=deny`. This is one of the repeated failures we saw while trying to update from JDK15 to JDK16 and forced us to downgrade to JDK11 for some formulae.

---

Of course, even if we try to fix this by downgrading to JDK11, it is likely users will then hit #66953.

**Comment by lizhaode** [comment]
in this file `/usr/local/opt/jmeter/bin/jmeter`

I found that it specified `JAVA_HOME` 

maybe, use system env JAVA_HOME will be better?

**Comment by lizhaode** [comment]
> Sounds like a duplicate of #66953.

I think so.  maybe make jmeter in bin folder use system env first

**Comment by cho-m** [comment]
> I think so. maybe make jmeter in bin folder use system env first

If you want to be able to set `JAVA_HOME`, then the formula can be modified from
`JAVA_HOME: Formula["openjdk"].opt_prefix` to `Language::Java.overridable_java_home_env`

This will at least act as a workaround to allow user to set/use non-formula Java until the actual issue with Homebrew's OpenJDK formula is fixed.
