### ISSUE TITLE
InfluxDB build doesn't inject commit for display by `/health` API and UI

### ISSUE THREAD

**Issue by danxmoran** [Homebrew/homebrew-core#78867]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.1.9-133-gf1f7dc1
ORIGIN: https://github.com/Homebrew/brew
HEAD: f1f7dc151dc0c188f32e08ddd4d31240abb94804
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cbdbf68578a6e80dcce5feba73c8862aac1a833d
Core tap last commit: 9 minutes ago
Core tap branch: dm-influxdb-set-commit-info
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: N/A

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/dan/go/bin/pkg-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Test that the auto-upgrade of `influxdb` to 2.0.7 properly handled the UI, since the UI-bundling was broken in 2.0.6.

### What happened (include all command output)?

The build/install link works fine, but once running the server I noticed that the `/health` endpoint wasn't returning all the information I'd expect:
```bash
# With `INFLUXD_CONFIG_PATH=/usr/local/etc/influxdb2/config.yml influxd` running in the background
$ curl localhost:8086/health
{"name":"influxdb", "message":"ready for queries and writes", "status":"pass", "checks":[], "version": "2.0.7", "commit": "none"}
```
The `"commit": "none"` is the surprising piece.

This translates to a strange thing in the UI landing page:
![Screen Shot 2021-06-07 at 9 50 30 AM](https://user-images.githubusercontent.com/2755881/121028445-d6932280-c775-11eb-8bd2-8284fde2f77b.png)

### What did you expect to happen?

I expected the short-hash of the `influxdb` commit to be injected at build time so it can be returned via the API and displayed in the UI.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install influxdb
brew services start influxdb
curl localhost:8086/health
```

**Comment by danxmoran** [comment]
Adding `-X main.commit=<the-commit>` to the LD flags [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/influxdb.rb#L57) should fix this problem. I'm not sure how to get the commit since `brew` downloads all the source from a tarball... any tips?

**Comment by carlocab** [comment]
One option would be to use a Git clone instead of a tarball. That's not ideal, though: clones are much slower and not as good for caching.

If you produce a release artefact that contains the commit SHA somewhere (maybe a file that can be read at build time?) that might be a nice way of getting this into the build flags.

To be clear:

>Test that the auto-upgrade of `influxdb` to 2.0.7 properly handled the UI, since the UI-bundling was broken in 2.0.6.

Do you mean an upgrade with `brew upgrade`?

**Comment by alebcay** [comment]
The formula has been rebuilt to include the necessary variables (2.0.7_2). Please try again after performing `brew update` and `brew upgrade`.

Now when I run `curl localhost:8086/health` with `influxd` running, I see this:
```
{"name":"influxdb", "message":"ready for queries and writes", "status":"pass", "checks":[], "version": "2.0.7", "commit": "2a45f0c037"}
```

Please comment or open a new issue if you're still running into problems.
