### ISSUE TITLE
`brew install lastpass-cli --with-pinentry --with-doc` fails

### ISSUE THREAD

**Issue by kgust** [Homebrew/homebrew-core#7888]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

Attempting to install lastpass-cli with docs fails.

https://gist.github.com/f8429a14f87dfd88ccde9d17c5e0f94f

I'm seeing the same problem that @Dispader reported on Issue #4383.

```
▶ brew install lastpass-cli --withpinentry --with-doc
Warning: lastpass-cli: this formula has no --withpinentry option so it will be ignored!
==> Using the sandbox
==> Downloading https://github.com/lastpass/lastpass-cli/archive/v1.0.0.tar.gz
Already downloaded: /Users/gustavkd/Library/Caches/Homebrew/lastpass-cli-1.0.0.tar.gz
==> make PREFIX=/usr/local/Cellar/lastpass-cli/1.0.0 install
==> make MANDIR=/usr/local/Cellar/lastpass-cli/1.0.0/share/man install-doc
Last 15 lines from /Users/gustavkd/Library/Logs/Homebrew/lastpass-cli/02.make:
2016-12-15 07:44:49 -0600

make
MANDIR=/usr/local/Cellar/lastpass-cli/1.0.0/share/man
install-doc

a2x --no-xmllint -f manpage lpass.1.txt
a2x: ERROR: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/usr/local/Cellar/asciidoc/8.6.9_1/etc/asciidoc/docbook-xsl/manpage.xsl" "/private/tmp/lastpass-cli-20161215-28199-lfja8o/lastpass-cli-1.0.0/lpass.1.xml" returned non-zero exit status 5
make: *** [lpass.1] Error 1

READ THIS: https://git.io/brew-troubleshooting
```

**Comment by apjanke** [comment]
Minor note: there's a typo in the options, so this looks like just a problem with `--with-doc`, and `--with-pinentry` is irrelevant.

```
▶ brew install lastpass-cli --withpinentry --with-doc
Warning: lastpass-cli: this formula has no --withpinentry option so it will be ignored!
```

I can't reproduce this on 10.11.6 – the installation works fine. Will try to reproduce on a 10.12 VM.

`xsltproc`'s exit status 5 means "Error in the stylesheet". Might be a difference in `xsltproc` versions between 10.11 and 10.12.

**Comment by dunn** [comment]
I can't reproduce on 10.12.2.

**Comment by kgust** [comment]
I think I was receiving the failure with 10.12.1. I currently have 10.12.2 and I just tried `brew install lastpass-cli --with-doc` and it successully installed.

I'm closing the issue.
