### ISSUE TITLE
--build-from-source cross-formula-testing / trawler

### ISSUE THREAD

**Issue by John-Colvin** [Homebrew/homebrew-core#7902]
I have come across situations multiple times where updating one formula has broken the `--build-from-source`\* for another formula.

It would be really great if one of two things happened:
1) When a formula is updated, all other formulas in homebrew-core that depend on that formula are also tested. Whether that happens as part of the pull-request process or done on merge, whether it's a blocker for merging or just auto-opens an issue, I don't know.
2) there was a constantly running autotester that goes through all the packages building from source and auto-opens an issue as/when one fails.

1 would be very expensive for some formulae that are in many dependency trees, I don't know how long 2 would take per iteration over all packages.

\* of course this also affects any installs that are using non-default flags.

**Comment by MikeMcQuaid** [comment]
Unfortunately this isn't possible without us getting significantly more financial resources to buy CI boxes. Instead a better solution for us long-term is to use fewer options altogether.
