### ISSUE TITLE
Emacs shouldn't be a dependency for LFE as, it is not required for LFE to install and having it as a dependency causes problems when emacs-plus is installed.

### ISSUE THREAD

**Issue by prertik** [Homebrew/homebrew-core#79031]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.1.11-24-g9938621
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9938621f2360413187ac208dd7d5dfca9c25f05a
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a1e2557457ae38e8e68d7a3444eaf153c4d262bd
Core tap last commit: 41 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install lfe`. To install LFE package.

### What happened (include all command output)?

==> Installing dependencies for lfe: emacs
==> Installing lfe dependency: emacs
==> Pouring emacs--27.2.big_sur.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/ebrowse
Target /usr/local/bin/ebrowse
is a symlink belonging to emacs-plus@27. You can unlink it:
  brew unlink emacs-plus@27

To force the link and overwrite all conflicting files:
  brew link --overwrite emacs

To list all files that would be deleted:
  brew link --overwrite --dry-run emacs

Possible conflicting files are:
/usr/local/bin/ebrowse -> /usr/local/Cellar/emacs-plus@27/27.2/bin/ebrowse
/usr/local/bin/emacs -> /usr/local/Cellar/emacs-plus@27/27.2/bin/emacs
/usr/local/bin/emacs-27.2 -> /usr/local/Cellar/emacs-plus@27/27.2/bin/emacs-27.2
/usr/local/bin/emacsclient -> /usr/local/Cellar/emacs-plus@27/27.2/bin/emacsclient
/usr/local/bin/etags -> /usr/local/Cellar/emacs-plus@27/27.2/bin/etags
/usr/local/include/emacs-module.h -> /usr/local/Cellar/emacs-plus@27/27.2/include/emacs-module.h
/usr/local/share/applications/emacs.desktop -> /usr/local/Cellar/emacs-plus@27/27.2/share/applications/emacs.desktop
Error: Could not symlink share/emacs/27.2/etc/AUTHORS
Target /usr/local/share/emacs/27.2/etc/AUTHORS
is a symlink belonging to emacs-plus@27. You can unlink it:
  brew unlink emacs-plus@27

To force the link and overwrite all conflicting files:
  brew link --overwrite emacs-plus@27

To list all files that would be deleted:
  brew link --overwrite --dry-run emacs-plus@27

### What did you expect to happen?

I expected LFE to be installed without trying to install emacs.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew tap d12frosted/emacs-plus (To install emacs-plus)
2. brew install emacs-plus
3. brew install lfe.
```

**Comment by SMillerDev** [comment]
It's not a bug in homebrew/core if an external tap decides to install things in the same location as a core formula
