### ISSUE TITLE
undefined method `rebuild' for #<BottleSpecification:0x007fdf1a13c288>

### ISSUE THREAD

**Issue by zheyejs** [Homebrew/homebrew-core#7927]
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:10:in `block in <class:Findutils>'
/usr/local/Library/Homebrew/software_spec.rb:91:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:91:in `bottle'
/usr/local/Library/Homebrew/formula.rb:1726:in `bottle'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:8:in `<class:Findutils>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/findutils.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formula.rb:1183:in `[]'
/usr/local/Library/Homebrew/diagnostic.rb:1217:in `check_for_non_prefixed_findutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:34:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:27:in `doctor'
/usr/local/Library/brew.rb:84:in `<main>'

**Comment by ilovezfs** [comment]
You're probably a victim of https://twitter.com/MacHomebrew/status/763686348041641984. Please follow the instructions there.
