### ISSUE TITLE
Service: switch formula from `def plist` to `service do` blocks

### ISSUE THREAD

**Issue by SMillerDev** [Homebrew/homebrew-core#79367]
To allow Linux users to use `brew services` and to make formula less OS dependent we should migrate the formulae to use the OS agnostic `service do` block.

---

- [ ] bitlbee
- [ ] dbus
- [ ] kapacitor
- [ ] launch_socket_server
- [ ] launchdns
- [ ] opentsdb
- [ ] questdb
- [ ] rtags
- [ ] ssdb
- [ ] wildfly-as
- [ ] zookeeper

https://github.com/Homebrew/homebrew-core/pull/91809
- [x] automysqlbackup
- [x] carrot2
- [x] coredns
- [x] ejabberd
- [x] icecream
- [x] isc-dhcp
- [x] lighttpd
- [x] logrotate
- [x] mariadb
- [x] mariadb@10.2
- [x] mariadb@10.3
- [x] mariadb@10.4
- [x] pdns
- [x] pdnsd
- [x] percona-server
- [x] sdns
- [x] squid
- [x] unbound
- [x] vnstat
- [x] znapzend

Won't do
- [x] mariadb@10.1 (deprecated)
- [x] cassandra@2.1 (deprecated)
- [x] cassandra@2.2 (deprecated)
- [x] elasticsearch (deprecated)
- [x] elasticsearch@6 (deprecated)
- [x] kibana (deprecated)
- [x] kibana@6 (deprecated)

**Comment by MikeMcQuaid** [comment]
@smillerdev before we do this: do you have a replacement for the `plist_options` DSL? I think it should probably go away or get replaced with a more platform-agnostic version.

**Comment by SMillerDev** [comment]
I don't have one for `:startup` though it could probably just be a service function `boot_service true` or something.

The `:manual` option is auto-generated from the command in the service block.

**Comment by MikeMcQuaid** [comment]
> I don't have one for `:startup` though it could probably just be a service function `boot_service true` or something.

Yeh, could be an argument to `service do`, I think. It kinda only applies on macOS because I think it's always gonna be a boot service on Linux, no? Could have a `plist_type :system/:user` or `macos_startup :boot/:login` or something else.

> The `:manual` option is auto-generated from the command in the service block.

Gotcha. So it's essentially already also removable in favour of the service block?

**Comment by SMillerDev** [comment]
> Yeh, could be an argument to service do, I think. It kinda only applies on macOS because I think it's always gonna be a boot service on Linux, no? Could have a plist_type :system/:user or macos_startup :boot/:login or something else.

Nope, for systemD it works the same as for launchd.

> Gotcha. So it's essentially already also removable in favour of the service block?

Yeah, but I figured I'd combine the work.

**Comment by MikeMcQuaid** [comment]
> > Yeh, could be an argument to service do, I think. It kinda only applies on macOS because I think it's always gonna be a boot service on Linux, no? Could have a plist_type :system/:user or macos_startup :boot/:login or something else.
> 
> Nope, for systemD it works the same as for launchd.

Ah, cool. Yeh, a boot/login differentiation argument makes sense to me.

> Yeah, but I figured I'd combine the work.

👍🏻

**Comment by branchvincent** [comment]
in case it's helpful to others, I wrote a script to do most of the work here:

<details>
  <summary>migrate_plist.py</summary>

```python
import json
import plistlib
import re
import textwrap
from pathlib import Path

PLIST_RE = re.compile(r"def plist\s+<<\~EOS\s+(?P<plist>.*)\s+EOS\s+end", re.DOTALL)
PLIST_OPTIONS_RE = re.compile(r"plist_options .*")


def plist_to_service(plist: str) -> str:
    data = plistlib.loads(plist.encode())
    if "StartInterval" in data or "StartCalendarInterval" in data:
        print("ERROR: run_type not yet supported")
        exit(1)
    service = {
        "run": data.get("Program") or data.get("ProgramArguments"),
        "keep_alive": data.get("KeepAlive"),
        "working_directory": data.get("WorkingDirectory"),
        "root_dir": data.get("RootDirectory"),
        "input_path": data.get("StandardInPath"),
        "log_path": data.get("StandardOutputPath"),
        "error_log_path": data.get("StandardErrorPath"),
        "environment_variables": data.get("EnvironmentVariables"),
    }
    block = "service do\n"
    for k, v in service.items():
        if v is not None:
            block += f"  {k} {json.dumps(v)}\n"
    block += "end"
    return block


if __name__ == "__main__":
    from argparse import ArgumentParser

    parser = ArgumentParser(description="Migrate plist file to a service")
    parser.add_argument("file", type=Path, help="plist file to migrate")
    parser.add_argument(
        "-i", "--in-place", action="store_true", help="rewrite in-place"
    )

    args = parser.parse_args()
    contents = args.file.read_text()
    if not (match := PLIST_RE.search(contents)):
        print(f"ERROR: Failed to find a plist in {args.file}")
        exit(1)

    service = plist_to_service(match.group("plist"))
    if args.in_place:
        service = textwrap.indent(service, " " * 2).lstrip()
        contents = PLIST_RE.sub(service, contents, count=1)
        contents = PLIST_OPTIONS_RE.sub("", contents, count=1)
        args.file.write_text(contents)
    else:
        print(service)
```
</details>

to use it:

```shell
python3 migrate_plist.py --in-place Formula/example.rb
```

**Comment by SMillerDev** [comment]
Closing since the last PR is open: https://github.com/Homebrew/homebrew-core/pull/93612
