### ISSUE TITLE
brew install wxpython succeeds, yet homebrew python cannot find module

### ISSUE THREAD

**Issue by ttdoucet** [Homebrew/homebrew-core#79562]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
odd@greek ~ % brew config
HOMEBREW_VERSION: 3.1.12-93-g736278c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 736278c02068d6f999989d4e4c89b6acd91b69d2
Last commit: 76 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea8e4c8596be1a310bff521ffaaf8dea8758db5b
Core tap last commit: 87 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.2.1-arm64
CLT: 12.5.0.0.1.1617976050
Xcode: 12.5
Rosetta 2: false
todd@greek ~ % 
todd@greek ~ % 
todd@greek ~ % 
todd@greek ~ % brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to use the Python wxpython module after an apparent success brew install of wxpython.

### What happened (include all command output)?

A simple import of the module fails, using the homebrew version of Python.  (Other modules installed in the same way work fine.)

Here is the apparent successful install:

todd@greek ~ % brew install wxpython
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 06253790e to 736278c02.
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Downloading https://ghcr.io/v2/homebrew/core/wxpython/manifests/4.1.1_1
Already downloaded: /Users/todd/Library/Caches/Homebrew/downloads/e3048ea3c654afe0835b00bc7dc23cb21256877f3315615a951233b4eb52a940--wxpython-4.1.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/wxpython/blobs/sha256:016eaf4f3
Already downloaded: /Users/todd/Library/Caches/Homebrew/downloads/73e224303e86b1e337b1571cbe728b81896bf0f40f1f2b3cda1a9588766224b0--wxpython--4.1.1_1.arm64_big_sur.bottle.tar.gz
==> Pouring wxpython--4.1.1_1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/wxpython/4.1.1_1: 1,192 files, 63.1MB

And here is the inability to find it:

todd@greek ~ % which python3
/opt/homebrew/bin/python3
todd@greek ~ % 
todd@greek ~ % python3
Python 3.9.5 (default, May  3 2021, 19:12:05) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wx'
>>> 
>>> 
todd@greek ~ % 

### What did you expect to happen?

I expected the

   import wx

in python3 to succeed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
As above:

  brew install wxpython

followed by invoking python and loading the module:

  python3
  import wx
```

**Comment by carlocab** [comment]
`wxpython` depends on some Python modules that we install into a private virtual env, so installing it doesn't quite get you to being able to `import wx` right out of the box. [*]

Try this:
```sh
PYTHONPATH="$(brew --prefix wxpython)/libexec/python3.9/site-packages" python3
```
then do `import wx`.

[*] PRs to improve this welcome. A formula for `Pillow` might be a good start here. CC @alebcay

**Comment by ttdoucet** [comment]
> On Jun 18, 2021, at 12:18 PM, Carlo Cabrera ***@***.***> wrote:
> 
> 
> wxpython depends on some Python modules that we install into a private virtual env, so installing it doesn't quite get you to being able to import wx right out of the box. [*]
> 
> Try this:
> 
> PYTHONPATH="$(brew --prefix wxpython)/libexec/python3.9/site-packages" python3
> then do import wx.
> 

That is interesting, thanks.  That particular incantation did not work for me because, I think, that the site-packages directory does not get symlinked by the wxpython prefix location.  But it does work when I use your idea to point it to the location in the Cellar:

  PYTHONPATH=/opt/homebrew/Cellar/wxpython/4.1.1_1/libexec/lib/python3.9/site-packages python3

I can work with that.  :)

Is there a place where this is documented that I should have been reading but missed?

Thanks!

**Comment by carlocab** [comment]
Oops; I had a typo. Try this:
```
PYTHONPATH=$(brew --prefix wxpython)/libexec/lib/python3.9/site-packages python3
```
You'll want to avoid using a cellar path, as those paths can change at any time.

>Is there a place where this is documented that I should have been reading but missed?

Unfortunately not. It's not too hard to intuit from looking at the formula (especially the `test` block), but ideally doing
```
brew install wxpython && python3 -c 'import wx'
```
should just work.

**Comment by ttdoucet** [comment]
> On Jun 18, 2021, at 1:23 PM, Carlo Cabrera ***@***.***> wrote:
> 
> 
> Oops; I had a typo. Try this:
> 
> PYTHONPATH=$(brew --prefix wxpython)/libexec/lib/python3.9/site-packages python3
> You'll want to avoid using a cellar path, as those paths can change at any time.
> 
That works great for me.  Thanks for the clarification.

**Comment by carlocab** [comment]
Reopening this since I think there's still something here we should try to fix.

**Comment by ttdoucet** [comment]
Sorry!  I wasn’t sure whether I was supposed to close it or not.  :)

**Comment by briantoby** [comment]
I have noticed that wxdemo does work. It appears that running `/opt/homebrew/bin/python3` gives me a python that cannot find wxpython but running `/opt/homebrew/Cellar/wxpython/4.1.1_1/libexec/bin/python3` does avoid this.

**Comment by carlocab** [comment]
Have you tried doing
```
PYTHONPATH=$(brew --prefix wxpython)/libexec/lib/python3.9/site-packages python3
```
as suggested in https://github.com/Homebrew/homebrew-core/issues/79562#issuecomment-864178719?

**Comment by briantoby** [comment]
No, but wanted to leave this in the thread as an alternate workaround until wx is updated. I did not see the PYTHONPATH workaround until after I found my workaround, but FWIW after seeing lots of warnings on it, I try to avoid PYTHONPATH since I am told it can break things.

**Comment by carlocab** [comment]
This should be fixed without needing any workarounds now. Please do `brew update && brew upgrade wxpython`.

In particular, just doing `python3 -c 'import wx'` should just work.

**Comment by ttdoucet** [comment]
I can report that the update works perfectly for me and fixes the issue.  Thanks!

**Comment by briantoby** [comment]
Yes, confirming: after `brew upgrade`, wxpython works perfectly (tested with `wxdemo`).

@carlocab Thanks very much!
