### ISSUE TITLE
go: 1.8beta1 and 1.8beta2 "--devel" build incorrect

### ISSUE THREAD

**Issue by mmindenhall** [Homebrew/homebrew-core#7959]
I'm not sure who maintains the go formula, but the current `--devel` builds are producing bad binaries.  The binaries seem to work just fine when building for the Mac (darwin/amd64), but when I tried cross building (GOOS=linux GOARCH=arm GOARM=7), I saw build errors.

I verified that this is specific to the brew install by downloading the [pre-built 1.8beta2 binaries](https://storage.googleapis.com/golang/go1.8beta2.darwin-amd64.tar.gz), and copying them in place of the brew binaries (`go`, `godoc`, `gofmt`).  The failing builds then succeeded.

I have _no idea_ what's going wrong with the brew build, as I didn't see anything when I ran `brew reinstall go --devel`.  However, this issue can be reproduced as follows:

1.  Install/reinstall go1.8beta2 with brew.
1.  Use `go get` to fetch and build govendor (or some other command):  
    `$ go get -u github.com/kardianos/govendor`
1.  `$ cd $GOPATH/src/github.com/kardianos/govendor`
1.  `$ go build`
1.  `$ file govendor` => govendor: Mach-O 64-bit executable x86_64
1.  `$ rm govendor`
1.  `$ GOOS=linux GOARCH=amd64 go build`

    ```
    # runtime/cgo
    ld: unknown option: --build-id=none
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ```
1. `$ GOOS=linux GOARCH=arm GOARM=7 go build`

    ```
    # runtime/cgo
    clang: error: argument unused during compilation: '-mno-thumb'
    ```

Now replace the brew binaries with the pre-built binaries, re-run the last two steps above, and the builds will be successful.

**Comment by mmindenhall** [comment]
@cblecker: any idea what might be going wrong here?  Just asking since you submitted the PRs for the go1.8beta --devel builds.

**Comment by cblecker** [comment]
@mmindenhall I don't either, but I'd suggest we report these upstream to [golang/go](https://github.com/golang/go). Being that 1.8 is in beta, they may be interested in this odd case.

What I did notice is that the bottle for 1.7.4 works properly, and building 1.7.4 from source locally also works correctly. So perhaps it's something in the build process for the 1.8beta that isn't working?

Either way, it's something specific to the 1.8beta -- and considering go is built without error, and makes darwin binaries without error, it leads me to believe that something upstream isn't working as intended.

Let me know if you want to go ahead and do that; if not I can later. Either way, reference this issue so we can track it :)

**Comment by cblecker** [comment]
Oh! This looks to have been related to #7556. If you `brew upgrade` to get the revision, it works now. 🎉

**Comment by ilovezfs** [comment]
Thanks for the heads up, cblecker

@mmindenhall let us know if this is still a problem for you

**Comment by mmindenhall** [comment]
Works for me...thanks!
