### ISSUE TITLE
Questions, installing languages to tesseract

### ISSUE THREAD

**Issue by stoivo** [Homebrew/homebrew-core#797]
### Formula Requests:

Is there a way to install new languages with tesseract with HomeBrew. I would like to install norwegian, the code is nor. I tried to do `brew install tessecract-nor`, that didn't work.
If someone were to install it with apt-get they would do  `apt-get install tessecract-nor`. 

I don't think is is clever to add a new Formula for each language. I have look at the existing tesseract Formula. I think it should we posible to add some lines to [Formula/tesseract.rb#L95-L96](https://github.com/Homebrew/homebrew-core/blob/6c8fe323a109f0e3741d6044a9e983e7c0a32062/Formula/tesseract.rb#L101-L102) so make it possible to install specific languages.

**Comment by mikemcquaid** [comment]
You can use `brew install tesseract --with-all-languages`.

**Comment by stoivo** [comment]
I know. Than I will have to install 1,2 GB of language while I am only interested in one language.

**Comment by mikemcquaid** [comment]
I don't think it'll scale for us to add options for every language, sorry.

**Comment by stoivo** [comment]
Ok, thanks for your reply.

**Comment by revolter** [comment]
You can also manually download it from [the wiki](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files) and then `mv <lang>.traineddata /usr/local/Cellar/tesseract/<version>/share/tessdata`.
