### ISSUE TITLE
Formula for erlang silently, undocumentedly does not install `jinterface`

### ISSUE THREAD

**Issue by russelldb** [Homebrew/homebrew-core#79702]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/erlang.rb#L57
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install erlang (because I need it to run EQC)

### What happened (include all command output)?

```
10:20:47:~ $ brew install erlang
==> Downloading https://ghcr.io/v2/homebrew/core/wxmac/manifests/3.0.5.1_2
Already downloaded: /Users/russell/Library/Caches/Homebrew/downloads/13d57d762f18482098869836481ba502cbcb3085d1d9ac949b27c757fc46e84b--wxmac-3.0.5.1_2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/wxmac/blobs/sha256:f5695d7ccacd4140747677cfb215b85d214d7c5ad664f74f677995a7ef61d0cd
Already downloaded: /Users/russell/Library/Caches/Homebrew/downloads/2c8d51e5181a4a9104f950b8b8a71f726ba82f056cae3da89bdd6655a80e572e--wxmac--3.0.5.1_2.big_sur.bottle.tar.gz
==> Downloading https://ghcr.io/v2/homebrew/core/erlang/manifests/24.0.2
Already downloaded: /Users/russell/Library/Caches/Homebrew/downloads/3c8c55621ffdb07af3bdfd52baa0e55c3684a386fd13f6634c15a6aed92b1a7d--erlang-24.0.2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/erlang/blobs/sha256:db0a9ace0b92a59e8586a560fd7e022aea8b405d5787d2a7e237de3b75ca6fd1
Already downloaded: /Users/russell/Library/Caches/Homebrew/downloads/fa66e4fb3d81271bdc6db7d15009797a2d4f27c4356b87f683368e6d7b7a0169--erlang--24.0.2.big_sur.bottle.tar.gz
==> Installing dependencies for erlang: wxmac
==> Installing erlang dependency: wxmac
==> Pouring wxmac--3.0.5.1_2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/wxmac/3.0.5.1_2: 810 files, 23.4MB
==> Installing erlang
==> Pouring erlang--24.0.2.big_sur.bottle.tar.gz
==> Caveats
Man pages can be found in:
  /usr/local/opt/erlang/lib/erlang/man

Access them with `erl -man`, or add this directory to MANPATH.
==> Summary
🍺  /usr/local/Cellar/erlang/24.0.2: 7,618 files, 483.2MB
==> Caveats
==> erlang
Man pages can be found in:
  /usr/local/opt/erlang/lib/erlang/man

Access them with `erl -man`, or add this directory to MANPATH.
```
Erlang OTP was installed

### What did you expect to happen?

I expected Erlang OTP to be installed WITH jinterface OR with some output telling me that `jinterface` was not installed, and not installable with this formula

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install erlang`
```

**Comment by SMillerDev** [comment]
> I expected Erlang OTP to be installed WITH jinterface OR with some output telling me that jinterface was not installed, and not installable with this formula


Formulae almost never install UIs of software.

**Comment by carlocab** [comment]
If you download the tarball and build it from source, does this install `jinterface`?

**Comment by cho-m** [comment]
Homebrew builds erlang using `--without-javac`, probably based on the average use-case.
Enabling `jinterface` means adding an `openjdk` dependency to `erlang`.

This was the setting chosen when optional arguments were removed: https://github.com/Homebrew/homebrew-core/commit/ea4e4f78ba18f0ecb111223ffd0060de75d6599f

If there isn't enough users who want this option, then you will need to maintain your own copy of Formula with `openjdk` dependency in a personal Tap.

**Comment by russelldb** [comment]
Thanks all for taking the time to explain it. I'll look into how to have a "personal tap"
