### ISSUE TITLE
Folly is not usable with PKG_CHECK_MODULES due to missing libgflags dependency

### ISSUE THREAD

**Issue by josh-berry** [Homebrew/homebrew-core#7977]
I am trying to develop my own software which depends on Facebook's Folly library. The Homebrew-installed version of Folly (as of today: `folly: stable 2016.12.12.00 (bottled), HEAD`) is not findable with pkg-config (specifically, the PKG_CHECK_MODULES autoconf macro). When using PKG_CHECK_MODULES with libfolly, pkg-config fails because it claims to be missing libgflags:

```
# The following command is exactly what PKG_CHECK_MODULES will do:
$ pkg-config --exists --print-errors "libfolly >= 0.57"
Package libgflags was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgflags.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libgflags', required by 'libfolly', not found
```

(To reproduce this issue, first `brew install folly`, and then run the `pkg-config` command shown above, which should succeed with no output.)

This is because the libfolly.pc installed in /usr/local/lib depends on "libgflags":

```
$ cat /usr/local/lib/pkgconfig/libfolly.pc
prefix=/usr/local/Cellar/folly/2016.12.12.00
...
Requires.private:  libgflags libglog openssl libevent
...
```

Yet the gflags pkg-config file is named "gflags.pc", not "libgflags.pc":

```
$ brew list gflags
...
/usr/local/Cellar/gflags/2.2.0/lib/pkgconfig/gflags.pc
...
```

I'm not sure whether the folly or the gflags recipe is at issue here, but they don't agree. In Homebrew's folly.rb file, I see that we are explicitly jamming dependencies into folly's configuration:

```sh
      # Build system relies on pkg-config but gflags removed
      # the .pc files so now folly cannot find without flags.
      ENV["GFLAGS_CFLAGS"] = Formula["gflags"].opt_include
      ENV["GFLAGS_LIBS"] = Formula["gflags"].opt_lib
```

And there are no similar alterations that I can see in the gflags recipe. But while the above helps Folly to build, it's still broken with respect to anything else that *depends* on Folly.

I'm not sure what the right course of action here is -- is this a Homebrew issue or an issue with the upstream Folly source?

**Comment by mistydemeo** [comment]
We're not customizing gflags at all, and looking at its source tree, it seems the `gflags.pc` name is its default. I think this is probably an upstream Folly issue.

**Comment by josh-berry** [comment]
Thanks for pushing this upstream (and with a patch, even) -- much appreciated! :)

**Comment by mistydemeo** [comment]
Should be fixed!
