### ISSUE TITLE
Big Sur 11.3.1 can't install fake root 

### ISSUE THREAD

**Issue by Shabunator** [Homebrew/homebrew-core#79934]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Warning: fakeroot has been deprecated because it does not build!
Error: fakeroot: no bottle available!
You can try to install from source with:
  brew install --build-from-source fakeroot
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

trying to install fake root

### What happened (include all command output)?

if I use install from source I have 404 error

### What did you expect to happen?

I don't know ( 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install fakeroot
brew install --build-from-source fakeroot
brew update 
brew doctor
brew install fakeroot
```

**Comment by SMillerDev** [comment]
Please note this warning in the output 

> Warning: fakeroot has been deprecated because it does not build!

**Comment by carlocab** [comment]
This is expected behaviour, so I'm closing this. If you're able to build `fakeroot`, please open a PR with the changes necessary to do so.
