### ISSUE TITLE
Boost fails to install boost_fiber libraries on 10.11.6

### ISSUE THREAD

**Issue by nathanhourt** [Homebrew/homebrew-core#7996]
The bottled version of boost, as well as builds from source (with and without c++11 enabled) all fail to include the boost_fiber binaries. The headers are installed (/usr/local/opt/boost/include/fiber is populated) but the libraries are missing (/usr/local/opt/boost/lib/libboost_fiber* is missing), and FindBoost.cmake in a project which depends on boost_fiber being installed fails to locate it, even though all other boost modules are found correctly.

Gist (from a build-from-source) is here:
https://gist.github.com/anonymous/0ad34884e3484082319430cf15ff6f7b

brew config:
```
HOMEBREW_VERSION: 1.1.5-14-g48256857
ORIGIN: https://github.com/Homebrew/brew
HEAD: 482568579b8c9e699ca19207643cc483975869a4
Last commit: 77 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72c21ed5946c9e251948e02229f458947ce466f5
Core tap last commit: 81 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 6.1 build 602
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 6.4 => /Volumes/OSX/Applications/Xcode.app/Contents/Developer
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

brew doctor:
```Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libarena-a4729905.dylib
  /usr/local/lib/libflate-a4729905.dylib
  /usr/local/lib/libfmt_macros-a4729905.dylib
  /usr/local/lib/libgetopts-a4729905.dylib
  /usr/local/lib/libgraphviz-a4729905.dylib
  /usr/local/lib/liblog-a4729905.dylib
  /usr/local/lib/libproc_macro-a4729905.dylib
  /usr/local/lib/librustc-a4729905.dylib
  /usr/local/lib/librustc_back-a4729905.dylib
  /usr/local/lib/librustc_borrowck-a4729905.dylib
  /usr/local/lib/librustc_const_eval-a4729905.dylib
  /usr/local/lib/librustc_const_math-a4729905.dylib
  /usr/local/lib/librustc_data_structures-a4729905.dylib
  /usr/local/lib/librustc_driver-a4729905.dylib
  /usr/local/lib/librustc_errors-a4729905.dylib
  /usr/local/lib/librustc_incremental-a4729905.dylib
  /usr/local/lib/librustc_lint-a4729905.dylib
  /usr/local/lib/librustc_llvm-a4729905.dylib
  /usr/local/lib/librustc_macro-a4729905.dylib
  /usr/local/lib/librustc_metadata-a4729905.dylib
  /usr/local/lib/librustc_mir-a4729905.dylib
  /usr/local/lib/librustc_passes-a4729905.dylib
  /usr/local/lib/librustc_platform_intrinsics-a4729905.dylib
  /usr/local/lib/librustc_plugin-a4729905.dylib
  /usr/local/lib/librustc_privacy-a4729905.dylib
  /usr/local/lib/librustc_resolve-a4729905.dylib
  /usr/local/lib/librustc_save_analysis-a4729905.dylib
  /usr/local/lib/librustc_trans-a4729905.dylib
  /usr/local/lib/librustc_typeck-a4729905.dylib
  /usr/local/lib/librustdoc-a4729905.dylib
  /usr/local/lib/libserialize-a4729905.dylib
  /usr/local/lib/libstd-a4729905.dylib
  /usr/local/lib/libsyntax-a4729905.dylib
  /usr/local/lib/libsyntax_ext-a4729905.dylib
  /usr/local/lib/libsyntax_pos-a4729905.dylib
  /usr/local/lib/libterm-a4729905.dylib
  /usr/local/lib/libtest-a4729905.dylib

Warning: Your Xcode (6.4) is outdated.
Please update to Xcode 8.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  readline
```

(I'm not sure why it complains about Xcode, I have version 8.2 installed)

Let me know if more info is needed :)

**Comment by MikeMcQuaid** [comment]
This will likely just require passing different options to Boost's build system and could be an upstream bug. Could you try and open a pull request to `boost.rb`? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by nathanhourt** [comment]
I played around with `brew edit boost` but I was unable to figure out a combination of flags that would cause it to build the libraries. I tried --with-fiber, but even then it didn't build the fiber libs. It may be an upstream issue...

**Comment by MikeMcQuaid** [comment]
Yeh, sounds like it. We don't consider it a bug that it's packaged as-is but would consider accepting a PR that adds it by default. Thanks!

**Comment by Rydgel** [comment]
@nathanhourt did you find a way?

**Comment by nathanhourt** [comment]
@Rydgel Sadly, no. I've since circumvented the issue by using Linux. :) I never got around to reporting a bug upstream, so you could try that.

**Comment by Rydgel** [comment]
@Rydgel I was actually able to compile it with the `c+11` option :)
So yeah brew is fine, there is another problem so which is located upstream.

**Comment by nathanhourt** [comment]
Did it have the fiber libs when you did that? I tried with the `c++11` option and it built fine, but still lacked the fiber libs.

**Comment by Rydgel** [comment]
You need to be sure to have the latest Xcode
`(Apple LLVM version 8.0.0 (clang-800.0.42.1))`

The command I use was:
`brew install boost --with-icu4c --c++11`

**Comment by windoze** [comment]
AFAIK Apple's version of clang just got support of `thread_local` in Xcode 8.0, boost context and fiber libraries rely on it.
Also context and fiber require C++11, which is not turned on by default.

As a resolution, I think we can turn on C++11 by default, this standard is widely adopted nowadays.

**Comment by MikeMcQuaid** [comment]
> As a resolution, I think we can turn on C++11 by default, this standard is widely adopted nowadays.

I agree.
