### ISSUE TITLE
vim and macvim bottles need to be rebuilt after new python (from #7973)

### ISSUE THREAD

**Issue by mikeage** [Homebrew/homebrew-core#8005]
The vim and macvim bottles are linked against the previous python, and after the update to Python 2.7.13 (in PR #7973 ) , report:

`E887: Sorry, this command is disabled, the Python's site module could not be loaded.`

when trying to run `:python(whatever)`

Both packages work when rebuilding from source. 

brew doctor reports no issues
brew config responds with:
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 918758fe5cce41c57b4123d34f4ca9584246f7b5
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.3/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

**Comment by chrisamin** [comment]
I also had this problem, I can confirm that it is fixed by uninstalling vim (I don't use macvim) and reinstalling with --build-from-source.

**Comment by apjanke** [comment]
The revision bumps have made it in, via #8114. Do a `brew update; brew upgrade` to pick up fresh bottles.
