### ISSUE TITLE
libgphoto2 fails to compile

### ISSUE THREAD

**Issue by ruychi** [Homebrew/homebrew-core#801]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

brew upgrade to libgphoto2 2.5.10 fails to compile, preventing upgrade to wine 1.8.2.

https://gist.github.com/4f62cf0f275d63919f39ebbb9cb662c4

**Comment by mikemcquaid** [comment]
```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
```

This is likely your issue. Please remove those libraries.

**Comment by ruychi** [comment]
Hi mikemcquaid,
Thanks for your note.
Although I was not suspicious of those unbrewed dylibs, I removed them properly and then updated homebrew.
However, the problem still persists and libgphoto2 2.5.10 still fails to compile, when installing/upgrading wine.
The new gist-log for libgphoto2 2.5.10:
https://gist.github.com/53b5c451a3bce40f70cef91d9c62de50

Apparently the problem comes from wine install, as libgphoto2 is a dependency. I experimented to uninstall wine and libgphoto2, then installed libgphoto2 alone. All went well.
But as soon as tried to install wine, the formula required libgphoto2 to be re-installed, and it is there when the errors occur on compiling libgphoto2.

The issued commands and the results:

**$ brew uninstall libgphoto2**
_Uninstalling /usr/local/Cellar/libgphoto2/2.5.10... (168 files, 4.3M)_
**$ brew install libgphoto2**
_==> Downloading https://homebrew.bintray.com/bottles/libgphoto2-2.5.10.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.el_capitan.bottle.tar.gz
==> Pouring libgphoto2-2.5.10.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libgphoto2/2.5.10: 168 files, 4.3M_
**$ brew install wine**
_==> Installing dependencies for wine: libgphoto2
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/libgphoto2-2.5.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2_
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.10
==> make install
Last 15 lines from /Users/ruychi/Library/Logs/Homebrew/libgphoto2/02.make:
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ax203.la] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: link: sed -e 's|^|_|' < ../camlibs/camlib.sym > .libs/barbie-symbols.expsym
libtool: link: clang  -o .libs/barbie.so -bundle  barbie/.libs/barbie.o   ../libgphoto2/.libs/libgphoto2.dylib /private/tmp/libgphoto2-20160503-13027-1fge4db/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lm ../libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lltdl -lpthread  -g -O2 -Wl,-dylib_file -Wl,/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port.12.dylib:/private/tmp/libgphoto2-20160503-13027-1fge4db/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib   -Wl,-exported_symbols_list,.libs/barbie-symbols.expsym
libtool: link: sed -e 's|^|_|' < ../camlibs/camlib.sym > .libs/canon-symbols.expsym
libtool: link: clang  -o .libs/canon.so -bundle  canon/.libs/canon_la-canon.o canon/.libs/canon_la-library.o canon/.libs/canon_la-serial.o canon/.libs/canon_la-usb.o canon/.libs/canon_la-crc.o canon/.libs/canon_la-util.o   ../libgphoto2/.libs/libgphoto2.dylib /private/tmp/libgphoto2-20160503-13027-1fge4db/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lm ../libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lltdl -lpthread  -g -O2 -Wl,-dylib_file -Wl,/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port.12.dylib:/private/tmp/libgphoto2-20160503-13027-1fge4db/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib   -Wl,-exported_symbols_list,.libs/canon-symbols.expsym
libtool: link: sed -e 's|^|_|' < ../camlibs/camlib.sym > .libs/casio_qv-symbols.expsym
libtool: link: clang  -o .libs/casio_qv.so -bundle  casio/.libs/casio-qv.o casio/.libs/casio-qv-commands.o casio/.libs/camtojpeg.o casio/.libs/ycctoppm.o   ../libgphoto2/.libs/libgphoto2.dylib /private/tmp/libgphoto2-20160503-13027-1fge4db/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lm ../libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib -lltdl -lpthread  -g -O2 -Wl,-dylib_file -Wl,/usr/local/Cellar/libgphoto2/2.5.10/lib/libgphoto2_port.12.dylib:/private/tmp/libgphoto2-20160503-13027-1fge4db/libgphoto2-2.5.10/libgphoto2_port/libgphoto2_port/.libs/libgphoto2_port.dylib   -Wl,-exported_symbols_list,.libs/casio_qv-symbols.expsym
libtool: link: ( cd ".libs" && rm -f "barbie.la" && ln -s "../barbie.la" "barbie.la" )
libtool: link: ( cd ".libs" && rm -f "canon.la" && ln -s "../canon.la" "canon.la" )
libtool: link: ( cd ".libs" && rm -f "casio_qv.la" && ln -s "../casio_qv.la" "casio_qv.la" )
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**$ brew info libgphoto2**
_libgphoto2: stable 2.5.10 (bottled), HEAD
Gphoto2 digital camera library
http://www.gphoto.org/proj/libgphoto2/
/usr/local/Cellar/libgphoto2/2.5.10 (168 files, 4.3M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libgphoto2.rb
==> Dependencies_
Build: pkg-config ✔
Required: libtool ✔, libusb-compat ✔, gd ✔
Optional: libexif ✘
==> Options
--universal
	Build a universal binary
--with-libexif
	Build with libexif support
--HEAD
	Install HEAD version

**Comment by ilovezfs** [comment]
@ruychi The reason it reinstalls `libgphoto2` is that all of `wine`'s dependencies must be built with `--universal`, but the bottled `libgphoto2` is not built with that option. So you can avoid the rebuilding if you first install `libgphoto2` passing `--universal`.
```
brew install --universal libgphoto2
brew install wine
```

Presumably `brew install --universal  libgphoto2` will fail as it did above during the `wine` install, and then you can do `brew gist-logs libgphoto2`, which should generate a useful report for us.

**Comment by ilovezfs** [comment]
I think there's something wrong with your `jpeg`. Your original `brew doctor` report said `/usr/local/lib/libjpeg.9.dylib` and brew's current version is 8d. Do you know where that other one came from? Also, how did you go about suppressing that doctor error? Maybe there are remnants left behind still?

In addition, your configure log says
```
checking for jpeg_start_decompress in -ljpeg... no
```
whereas mine says "yes" and then has additional lines about jpeg following.

You can try
```
brew prune
brew uninstall jpeg
brew install jpeg
```
but it would be nice to know what's going on.

**Comment by DomT4** [comment]
> I think there's something wrong with your jpeg. Your original brew doctor report said /usr/local/lib/libjpeg.9.dylib and brew's current version is 8d. Do you know where that other one came from?

I suspect `homebrew/versions/jpeg9` which for some reason isn't `keg_only` when it should be here.

**Comment by ilovezfs** [comment]
@DomT4 If that's true, what's interesting is, how did doctor nonetheless give him a clean bill of health?

**Comment by ruychi** [comment]
@ilovezfs and @DomT4 
I found out what is causing the problem. 
It is the eid-pt app from tap caskroom/homebrew-eid, which places unbrewed dylibs in /usr/local/lib, namely the /usr/local/lib/libjpeg.9.dylib.
I order to get "around" the doctor complain about those dylibs, I moved them out to /opt/my-eid-pt and symlinked them at /usr/local/lib

Brew doctor stopped complaining about those dylibs and the eid-pt app was working normally.

But then the wine update failed due to the libgphoto2 compile error, caused by the libjpeg.9.dylib.

I just cleaned up the mess (uninstalling that eid-pt app) updated/upgraded brew, and reinstalled wine. 
Everything went smooth without issues. But when reinstalling the eid-pt new version, those unbrewed dylibs appeared again. Additionally, installing eid-pt doesn't clean up correctly, leaving those dylibs and also some header files. Installing directly the eid-pt package (not through home-brew cask) creates the same/similar situation. I need the eid-pt app (for reading my electronic identity card in order to access some services). Is there a way to install correctly the app through homebrew? 


**$ brew install wine**
_==> Installing dependencies for wine: libgphoto2
==> Installing wine dependency: libgphoto2
==> Downloading https://downloads.sourceforge.net/project/gphoto/libgphoto/2.5.10/libgphoto2-2.5.10.tar.bz2
Already downloaded: /Library/Caches/Homebrew/libgphoto2-2.5.10.tar.bz2
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/libgphoto2/2.5.10
==> make install
🍺  /usr/local/Cellar/libgphoto2/2.5.10: 168 files, 8.2M, built in 2 minutes 28 seconds
==> Installing wine
==> Downloading https://homebrew.bintray.com/bottles/wine-1.8.2.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring wine-1.8.2.el_capitan.bottle.tar.gz
==> Caveats_
...
_==> Summary
🍺  /usr/local/Cellar/wine/1.8.2: 2,504 files, 257M _

**$ brew doctor**
_Your system is ready to brew._
**$ brew cask info eid-pt**
_eid-pt: latest
Cartão de Cidadão, Electronic identity card software for Portugal, eID Portugal
https://www.cartaodecidadao.pt/
Not installed
https://github.com/caskroom/homebrew-eid/blob/master/Casks/eid-pt.rb
==> Contents
  Cartao_de_Cidadao.pkg (pkg)_

**$ brew cask install eid-pt**
==> Downloading https://www.cartaodecidadao.pt/ccsoftware/Cartao_de_Cidadao.pkg
######################################################################## 100.0%
==> No checksum defined for Cask eid-pt, skipping verification
==> Running installer for eid-pt; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is Cartao_de_Cidadao_MacOSX
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  eid-pt staged at '/opt/homebrew-cask/Caskroom/eid-pt/latest' (10M)

**$ brew doctor**
_Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted._

_Unexpected dylibs:_
    /usr/local/lib/libboost_system.dylib
    /usr/local/lib/libcrypto.1.0.0.dylib
    /usr/local/lib/libjasper.1.0.0.dylib
    /usr/local/lib/libjpeg.9.dylib
    /usr/local/lib/libpteiddlg.1.61.0.dylib
    /usr/local/lib/libpteidhttps.1.61.0.dylib
    /usr/local/lib/libpteidlib.1.61.0.dylib
    /usr/local/lib/libpteidlibopensc.1.61.0.dylib
    /usr/local/lib/libssl.1.0.0.dylib
    /usr/local/lib/pteidpkcs11.1.61.0.dylib

_Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:_
    /usr/local/include/pteid/pteiddefines.h
    /usr/local/include/pteid/pteidlib.h

**$ brew cask uninstall eid-pt**
_==> Running uninstall process for eid-pt; your password may be necessary
==> Running uninstall script /usr/local/bin/pteid_uninstall.sh
Password:_

**$ brew doctor**
_Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:_
    /usr/local/lib/libcrypto.1.0.0.dylib
    /usr/local/lib/libjasper.1.0.0.dylib
    /usr/local/lib/libjpeg.9.dylib
    /usr/local/lib/libssl.1.0.0.dylib

_Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:_
    /usr/local/include/pteid/pteiddefines.h
    /usr/local/include/pteid/pteidlib.h

**Comment by mikemcquaid** [comment]
I don't know about the `brew cask` issue; you should probably report that to them. Because of these libraries the whole `wine` dependency tree may need to be rebuild, unfortunately.

**Comment by UniqMartin** [comment]
Closing as it seems the issue has been identified and resolved. The `eid-pt` cask seems to need some work, but that's not something we can do anything about.
