### ISSUE TITLE
fabric run-time linking problem on 10.11 (_getentropy)

### ISSUE THREAD

**Issue by ploxiln** [Homebrew/homebrew-core#8044]
@stxml reported that fabric failed to connect to remote hosts on his system (macOS 10.11.6), with this backtrace:

```
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/hostkeys.py", line 335, in from_line
    key = ECDSAKey(data=decodebytes(key), validate_point=False)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/paramiko/ecdsakey.py", line 138, in __init__
    self.verifying_key = numbers.public_key(backend=default_backend())
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 71, in default_backend
    _default_backend = MultiBackend(_available_backends())
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 28, in _available_backends
    "cryptography.backends"
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
File "/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 51, in <module>
    from cryptography.hazmat.bindings._openssl import ffi as _ffi
    ImportError: dlopen(/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _getentropy
    Referenced from: /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
    Expected in: /usr/lib/libSystem.B.dylib in /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
```

This looks like the problem described here: https://gitlab.com/gnutls/gnutls/issues/142

> So it's defined but not actually available on 10.11, and you won't find that out at build time unless you pass -no_weak_imports in LDFLAGS. (Note that you can't easily do that because that flag is not supported on earlier versions of Xcode, including the CLT 7.3.1 which is the latest available for 10.11. So even if Xcode 8 is installed, using -no_weak_imports can still fail, which is a case you have to be prepared to handle if you use that flag.)

> But assuming you don't pass -no_weak_imports it will find getentropy is defined in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/random.h and compile, but then crash at run time.

But strangely, I do not experience this problem myself, though I also use macOS 10.11.6.

This was pointed out and discussed in #8006 but I've broken it out into a separate issue to hopefully get some more tips for solving this problem.

Right now I guess the best solution may be to downgrade the vendored paramiko dependency to the latest 1.x (instead of the just-upgraded-to 2.x which is what uses the "cryptography" module which causes this problem), and wait for a build fix upstream in "cryptography"?

**Comment by ploxiln** [comment]
@stxml if you `--build-from-source` does that fix it? It did for one of my colleagues (who I also had install the recent xcode tools update, not sure if that's also necessary).

**Comment by stxml** [comment]
Yes, I had already tried that, but still get the same error. I've also the latest Tools update.

**Comment by stxml** [comment]
Cryptography.io mentions these build flags to build from source with homebrew. Maybe that's worth looking into.
```
$ brew install openssl
$ env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography
```

**Comment by ploxiln** [comment]
I'm pretty sure that's not it - that's just to make sure the correct openssl libs are linked, which they are. The problem is with symbols in the macOS libc aka libSystem.B.dylib

**Comment by ploxiln** [comment]
@stxml do you have the full xcode installed, instead of the separate (much smaller) "Command Line Tools"? (can you show output from `brew config` plz?)

**Comment by stxml** [comment]
I have Xcode 8.2 installed. I had not launched it yet, so it had to install components. I tried building from source again, but no change.

```
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3977167695b3cc0e917370191c44a42046e61a40
Core tap last commit: 29 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit penryn
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.11.6-x86_64
Xcode: 8.2
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

As a temp workaround, I installed Fabric with `pip` instead of `homebrew` and it doesn't have the error.

**Comment by ilovezfs** [comment]
if you remove your workaround, nm should show the symbol when u build with brew

**Comment by stxml** [comment]
What file would I use nm on? `fab` is just a python text file.

**Comment by ilovezfs** [comment]
/usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so

**Comment by ploxiln** [comment]
@stxml my hypothesis is that this is *caused* by having Xcode installed - it includes headers which are actually for MacOS 10.12

If you try the tweak in PR #8046 that might fix it.

The `nm` thing is another way to check whether a fabric install is effected - to check the "pip installed" version, do something like

```
nm /usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so | grep getentropy
```

To check the homebrew installed fabric, check the path just posted by ilovezfs

```
nm /usr/local/Cellar/fabric/1.13.1/libexec/vendor/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so | grep getentropy
```

The "bug" is when this shows up:

```
                 U _getentropy
```

If the output is blank (when grepping for getentropy), it's good.

**Comment by ilovezfs** [comment]
> it includes headers which are actually for MacOS 10.12

The Xcode 8 SDK headers are valid for 10.11 as well (if you don't have the CLT, that's all you've got, which is a perfectly valid setup). `getentropy` is one of the symbols specifically designated "weak" for 10.11 in the SDK.

The bug will need to be reported upstream since they need to be able to handle the Xcode-only case without breaking.

**Comment by stxml** [comment]
I can confirm the pip version doesn't have the `U _getentropy`, but the homebrew version does.

**Comment by ilovezfs** [comment]
@stxml yup, that's exactly what you should see. Now if you pull https://github.com/Homebrew/homebrew-core/pull/8046 and try again, you'll see it's fixed.

**Comment by ploxiln** [comment]
Just by the way, the reason the pip version works is because it's a binary wheel install, rather than build-from-source, by default.

**Comment by ilovezfs** [comment]
also probably is fine if you have clt and do a pip source build outside of homebrew since it won't go out of its way to use xcode's sdk headers as we do

**Comment by stxml** [comment]
Yes, #8046 fixed it when building from source.

**Comment by ilovezfs** [comment]
@stxml poifect
