### ISSUE TITLE
netpbm formula missing symlink to shared library

### ISSUE THREAD

**Issue by iltommi** [Homebrew/homebrew-core#8045]
## Problem

The package `netpbm` creates a 2 symlinks to the shared library and a symlink to the static version.

```
/usr/local/lib/libnetpbm.a 
/usr/local/lib/libnetpbm.11.dylib
/usr/local/lib/libnetpbm.11.75.dylib
``` 

Unfortunately the one that is missing is the 
```
/usr/local/lib/libnetpbm.dylib
```

## How to reproduce the problem

I've set-up a travis job just for this to show the behaviour: https://github.com/iltommi/netpbm-brew-test/blob/master/.travis.yml
where I give these commands:
```
brew update
brew update
brew install apr apr-util
brew install netpbm
brew doctor
brew config
```

The package gets installed smoothly everything is ok and the `doctor` answer is:`Your system is ready to brew.`

and `brew config` is a common to travis one and is here:
https://travis-ci.org/iltommi/netpbm-brew-test/builds/185285833#L394

I added the command:

 - `ls -la /usr/local/lib/libnetpbm*` : https://travis-ci.org/iltommi/netpbm-brew-test/builds/185285833#L394

 - `ls -la /usr/local/Cellar/netpbm/10.76_1/lib/` :https://travis-ci.org/iltommi/netpbm-brew-test/builds/185285833#L425 confirming that the link is not present in the cellar

## Simple fix:

add the link `/usr/local/lib/libnetpbm.11.dylib`:

```
cd /usr/local/Cellar/netpbm/10.76_1/lib/ && ln -sf libnetpbm.11.75.dylib libnetpbm.11.dylib
cd /usr/local/lib && ln -sf ../Cellar/netpbm/10.76_1/lib/libnetpbm.dylib libnetpbm.dylib
```

**Comment by iltommi** [comment]
I've added a step: `brew install --build-from-source netpbm`
and everything gets compiled 
> /usr/local/Cellar/netpbm/10.76_1: 740 files, 6.6M, built in 4 minutes 24 seconds

and it is still missing in that folder, so I adedd the `--keep-tmp` and list the build directory where the libary is built and there **bingo!** there is the file:
`/tmp/netpbm-20161220-5019-1vum6wk/lib/libnetpbm.dylib`

here is the link
https://travis-ci.org/iltommi/netpbm-brew-test/builds/185398761#L4149

**Comment by dunn** [comment]
Opened #8180 for this.

**Comment by dunn** [comment]
Should be fixed with a `brew update && brew upgrade netpbm`.

**Comment by iltommi** [comment]
works for me, thanks a lot!
