### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by saxinhaw** [Homebrew/homebrew-core#8054]
brew install https://github.com/prove/tarantula/blob/master/README.md
######################################################################## 100,0%
Error: /Users/-------/Library/Caches/Homebrew/Formula/README.md:5: syntax error, unexpected '<'
<!DOCTYPE html>
 ^
/Users/------/Library/Caches/Homebrew/Formula/README.md:6: syntax error, unexpected '<'
<html lang="en" class="">
 ^
/Users/------/Library/Caches/Homebrew/Formula/README.md:6: syntax error, unexpected keyword_class, expecting end-of-input
<html lang="en" class="">
                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:91:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:146:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:78:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:100:in `install'
/usr/local/Library/brew.rb:87:in `<main>'

**Comment by MikeMcQuaid** [comment]
You did not fill out the issue template so closing this.
