### ISSUE TITLE
Problem when compiling NJOY 2021 on mac

### ISSUE THREAD

**Issue by roberto160275** [Homebrew/homebrew-core#80655]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35b15af4005ff0140a73a64e48abb4cbc85cc270
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b62502da6f40ccbd754e4490c3689f71ec11c845
Core tap last commit: 68 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.o35e4Dr7ix/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
XQuartz: 2.7.11 => /opt/X11
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to run the 'make' command in order to compile NJOY21 on a mac.

### What happened (include all command output)?

A segmentation fault with fortran occured.

Command output below:

[ 28%] Building Fortran object _deps/njoy-build/CMakeFiles/njoy.dir/src/errorr.f90.o
f951: internal compiler error: Segmentation fault: 11
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make[2]: *** [_deps/njoy-build/CMakeFiles/njoy.dir/src/errorr.f90.o] Error 1
make[1]: *** [_deps/njoy-build/CMakeFiles/njoy.dir/all] Error 2
make: *** [all] Error 2

### What did you expect to happen?

I expected 'make' to finish successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
No use of brew commands for this. I used the instructions on https://docs.njoy21.io/install.html
```

**Comment by carlocab** [comment]
We don't package NJOY, so there's not much we can do to help you with this. You'll need to report this at https://github.com/njoy/NJOY21 if there aren't any similar issues on their issue tracker already open.
