### ISSUE TITLE
PHP8 provided by homebrew returning incorrect preg_match output

### ISSUE THREAD

**Issue by Saeven** [Homebrew/homebrew-core#80695]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/Saeven/b4cc096fa33958782914e65966d22c79
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Execute a preg_match using PHP provided by homebrew.

### What happened (include all command output)?

The results obtained with the php 8.0.* executable installed via homebrew, differ from php 8.0.* run via docker, or when compiled manually.

If you `brew install php` and then execute this one liner it will report '0' (no matches).  

> This script is referred to as `test.php` in the information that follows.

    <?php    echo preg_match('/\\\\([^\\\\]+)\s*$/', ' App\Factories\RabbitMQFactory', $matches);
    
But, it should report 1 (one match).

### What did you expect to happen?

If you compile PHP manually, you will get a different result:

    brew install libiconv
    wget https://www.php.net/distributions/php-8.0.8.tar.gz
    ./configure --with-iconv=/usr/local/opt/libiconv
    make

Once that completes, you can run the test script with the php compiled into `./sapi/cli/php` and get a proper result:

```
Saeven@SaevenPro cli % /Users/Saeven/Desktop/phptemp/php-8.0.8/sapi/cli/php test.php
1%  
```

As opposed to
```
Saeven@SaevenPro cli % /usr/local/Cellar/php/8.0.8/bin/php test.php
0% 
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php
php testscript.php
```

**Comment by cho-m** [comment]
Can you check if this is the same issue as #78635 which is due to `pcre2` v10.37 upstream bug?

**Comment by cho-m** [comment]
I tried upstream `pcre2` patch (PR #80703) and see that it fixes your issue.

Current problematic `pcre2`:
```console
❯ brew install pcre2
==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/manifests/10.37
Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/a60945ab62014571a4bcc94b411b35f6ad1c6b42904b9fcd8277b54f0a3d86d9--pcre2-10.37.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/pcre2/blobs/sha256:981738c8279de442ac2fc83fa61e9cdf75e5
Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/753ea6acc335ceec799fcc28c9ab62db7d1a9f14c11d1d9c65ba8aff55918e53--pcre2--10.37.big_sur.bottle.tar.gz
==> Pouring pcre2--10.37.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/pcre2/10.37: 230 files, 6.2MB

❯ /usr/local/bin/php test.php
0%
```

Using patched `pcre2`:
```console
❯ brew uninstall --ignore-dependencies pcre2
Uninstalling /usr/local/Cellar/pcre2/10.37... (230 files, 6.2MB)

❯ git checkout pcre2-patch
Switched to branch 'pcre2-patch'

❯ brew install pcre2 --build-from-source
==> Downloading https://ftp.pcre.org/pub/pcre/pcre2-10.37.tar.bz2
Already downloaded: /Users/cho-m/Library/Caches/Homebrew/downloads/aca498bd073103667423550d9baecd164409be9e50cfcc60a82205963f592fab--pcre2-10.37.tar.bz2
==> Patching
==> ./configure --prefix=/usr/local/Cellar/pcre2/10.37_1 --enable-pcre2-16 --enable-pcre2-32 --enable-pc
==> make
==> make install
🍺  /usr/local/Cellar/pcre2/10.37_1: 230 files, 6.2MB, built in 41 seconds

❯ /usr/local/bin/php test.php
1%
```

**Comment by Saeven** [comment]
I can confirm (thank you) that reinstalling PCRE from source solves the issue.

**Comment by cho-m** [comment]
@Saeven The new `pcre2` bottle with fix should be available now, so you can try reinstalling.
