### ISSUE TITLE
Formula for CSVfix is broken (new upstream repository)

### ISSUE THREAD

**Issue by wlbr** [Homebrew/homebrew-core#80711]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs csv-fix
Error: No logs.


-----
$ brew config
HOMEBREW_VERSION: 3.2.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 35b15af4005ff0140a73a64e48abb4cbc85cc270
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fa0dfebe45d5445b4fe8a3513a6fc05ddc841dea
Core tap last commit: 5 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Formula: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/csv-fix.rb

The repository for CSVfix used by the formula has vanished, therefore it is not possible to install CSVfix using Homebrew. 

I provided a **new home** for the source, that is working an all 3 intended platforms. Binaries are provided.
Could you please include that in the formula?

See **https://github.com/wlbr/csvfix**

### What happened (include all command output)?

 $ brew install csv-fix
Error: csv-fix has been disabled because it has a removed upstream repository!

### What did you expect to happen?

CSVfix should be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install csv-fix
Error: csv-fix has been disabled because it has a removed upstream repository!
```

**Comment by nandahkrishna** [comment]
The formula is not broken, it has been disabled (intentionally) because the source repository has been removed. The repository you have linked to does not seem to be the "official" new repository, so we cannot update it in the formula. 

Your solution here would be to extract the formula to a personal tap instead, wherein you can use your fork/source.

**Comment by wlbr** [comment]
Well, now I do have the binaries I need, why should I take the effort of the personal tap?

The question is: how can we make to tool available for everybody again?

**Comment by wlbr** [comment]
Thanks for the answer.

**Comment by nandahkrishna** [comment]
> Well, now I do have the binaries I need, why should I take the effort of the personal tap?

You do not need to, unless you wish to make it `brew`-installable for not only you but others who come across your Tap.

> The question is: how can we make to tool available for everybody again?

If your repository/fork gains popularity, is maintained and maybe even considered by other distros to be a replacement for the original, perhaps the formula could be updated.
