### ISSUE TITLE
Incorrect description for h2spec

### ISSUE THREAD

**Issue by kcarnold** [Homebrew/homebrew-core#80733]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Was trying to search for formulae relating to dead link checking, so I ran `brew search --desc link`.

### What happened (include all command output)?

```
...
h2spec: Fast website link checker in Go
...
muffet: Fast website link checker in Go
...
```

### What did you expect to happen?

It looks like `muffet` has the correct description but [`h2spec`](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/h2spec.rb#L2) inadventantly copy-pasted from it. Its [github page](https://github.com/summerwind/h2spec) describes it as " A conformance testing tool for HTTP/2 implementation.".

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/h2spec.rb#L2
```

**Comment by carlocab** [comment]
Could you open a pull request to fix this? Thanks!
