### ISSUE TITLE
PyQt5 not working on macOS Sierra

### ISSUE THREAD

**Issue by igilitschenski** [Homebrew/homebrew-core#8075]
PyQt5 seems to be not working on macOS Sierra (with `pyqt5-5.7` and `qt5-5.7.0`). Trying to import it results in:
```
>>> from PyQt5 import QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named PyQt5
```

A naive approach setting the `PYTHONPATH` to `/usr/local/Cellar/pyqt5/5.7/lib/python3.5/site-packages/`did not help resulting in
```
>>> from PyQt5 import QtCore
[...]
ImportError: dlopen(/usr/local/Cellar/pyqt5/5.7/lib/python3.5/site-packages/PyQt5/QtCore.so, 2): Symbol not found: _PyBytes_Type
[...]
```
No additional helpful information was provided by `brew doctor`.

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

**Comment by igilitschenski** [comment]
Sorry for not providing the correct information. I was able to resolve the issue and providing this information in case of someone having similar problems. By default, pyqt5 is only provided with Python 3 support. Reinstallation using the `--with-python` option solved the problem.

**Comment by MikeMcQuaid** [comment]
Glad to hear you got it sorted.
