### ISSUE TITLE
Error: send_io() function is unimplemented on this machine

### ISSUE THREAD

**Issue by droid-Q** [Homebrew/homebrew-core#81014]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.1-70-g5659d74
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 5659d74ff59414d22e285d77a7fcfcd3c1bf0614
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6aa42f9fa683de53bf51da10579342d3e599361a
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--appdir=/Applications"]
HOMEBREW_EDITOR: subl
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1


brew doctor:
  Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/anaconda3/bin/icu-config
  /usr/local/anaconda3/bin/krb5-config
  /usr/local/anaconda3/bin/freetype-config
  /usr/local/anaconda3/bin/xslt-config
  /usr/local/anaconda3/bin/libpng16-config
  /usr/local/anaconda3/bin/libpng-config
  /usr/local/anaconda3/bin/xml2-config
  /usr/local/anaconda3/bin/python3-config
  /usr/local/anaconda3/bin/curl-config
  /usr/local/anaconda3/bin/ncursesw6-config
  /usr/local/anaconda3/bin/pcre-config
  /usr/local/anaconda3/bin/python3.8-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew upgrade clang-format

### What happened (include all command output)?

==> Upgrading clang-format
  12.0.0 -> 12.0.1

==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/clang-12.0.1.src.tar.xz
Already downloaded: /Users/droid/Library/Caches/Homebrew/downloads/38682cf47b8686eb4af8dcbb481640a69b36bf46fa7d1f649c7af075f475b0c5--clang-12.0.1.src.tar.xz
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-12.0.1/llvm-12.0.1.src.tar.xz
Already downloaded: /Users/droid/Library/Caches/Homebrew/downloads/91abc4da9873ba3814060d52b05ddecc28449852eb4b6c843244e4ab41ee8414--llvm-12.0.1.src.tar.xz
Error: send_io() function is unimplemented on this machine
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:79:in `send_io'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:79:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:417:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:73:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:868:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `install'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:146:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
Traceback (most recent call last):
	2: from /usr/local/Homebrew/Library/Homebrew/build.rb:221:in `<main>'
	1: from /usr/local/Homebrew/Library/Homebrew/build.rb:221:in `open'
/usr/local/Homebrew/Library/Homebrew/build.rb:221:in `recv_io': file descriptor was not passed (msg_controllen=0 smaller than sizeof(struct cmsghdr)=12) (SocketError)
	1: from /usr/local/Homebrew/Library/Homebrew/build.rb:217:in `<main>'
/usr/local/Homebrew/Library/Homebrew/build.rb:256:in `rescue in <main>': private method `puts' called for nil:NilClass (NoMethodError)
(base) droid-rMBP ⛵  local-k8s () ~/D/g/stats on  master took 23s
➜  Traceback (most recent call last):
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
	16: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
	15: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
	14: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
	13: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
	12: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:146:in `upgrade_formula'
	11: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `install'
	10: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:868:in `build'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
	 5: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
	 4: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:45:in `block (3 levels) in safe_fork'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:880:in `block in build'
	 1: from /usr/local/Homebrew/Library/Homebrew/sandbox.rb:99:in `exec'
/usr/local/Homebrew/Library/Homebrew/utils.rb:322:in `safe_system': Failure while executing; `/usr/bin/sandbox-exec -f /private/tmp/homebrew20210711-34990-msipr3.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -W1 -- /usr/local/Homebrew/Library/Homebrew/build.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/clang-format.rb --build-bottle` exited with 1. (ErrorDuringExecution)
	18: from /usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
	17: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade'
	16: from /usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:178:in `upgrade_outdated_formulae'
	15: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `upgrade_formulae'
	14: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:44:in `each'
	13: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:47:in `block in upgrade_formulae'
	12: from /usr/local/Homebrew/Library/Homebrew/upgrade.rb:146:in `upgrade_formula'
	11: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:419:in `install'
	10: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:868:in `build'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `safe_fork'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `block in safe_fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:34:in `open'
	 5: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (2 levels) in safe_fork'
	 4: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `fork'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
	 2: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:65:in `rescue in block (3 levels) in safe_fork'
	 1: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:65:in `puts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:65:in `write': Broken pipe (Errno::EPIPE)

### What did you expect to happen?

no errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade clang-format
```

**Comment by gromgit** [comment]
Already reported: https://github.com/Homebrew/brew/issues/11685
