### ISSUE TITLE
bind formula has bad rndc configuration

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/homebrew-core#8113]
The `bind` formula generates a key at `"#{buildpath}/rndc.key"`, and then copies it to `/usr/local/etc/rndc.key`, alongside `/usr/local/etc/named.conf`. And this `named.conf` has the line `include "/usr/local/etc/rndc.key";`, allowing the `named` daemon to find both files.

However, the formula also builds the control command `rndc`, and configures it so it only looks for keys relative to itself. Attempting to call `rndc reload` yields the error:
```
rndc: neither /usr/local/Cellar/bind/9.11.0-P1/etc/rndc.conf nor /usr/local/Cellar/bind/9.11.0-P1/etc/rndc.key was found
```

It must instead be called with `rndc -k /usr/local/etc/rndc.key reload`.

Does this not work out of the box by design, or is it a bug?

**Comment by MikeMcQuaid** [comment]
This may be a packaging bug or may be an upstream bug. Could you try and open a pull request to address it? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by alexchandel** [comment]
I'd be happy to open a pull request fixing it, but I'm not entirely sure what to change, or whether it should change.

Should Homebrew tools know to look in `/usr/local/etc` instead of the folder relative to where they're deployed (e.g. `/usr/local/Cellar/bind/9.11.0-P1/etc/`)?

**Comment by MikeMcQuaid** [comment]
> Should Homebrew tools know to look in /usr/local/etc instead of the folder relative to where they're deployed (e.g. /usr/local/Cellar/bind/9.11.0-P1/etc/)?

Yep 👍, thanks!

**Comment by MikeMcQuaid** [comment]
Closing in favour of a PR.
