### ISSUE TITLE
Xonsh formula is not using the correct python version

### ISSUE THREAD

**Issue by paulhybryant** [Homebrew/homebrew-core#8117]
brew upgrade xonsh failed.

The root cause is because of the python version.

xonsh currently requires Python 3.4+

By adding virtualenv_create(libexec, "python3")
The upgrade succeeds.

**Comment by ilovezfs** [comment]
It sounds like your brew is severely outdated. Please provide the troubleshooting information requested in the issue template.

**Comment by paulhybryant** [comment]
Thanks, not sure why my branch is on stable.
Switching to the master branch seems to fix the problem.

**Comment by ilovezfs** [comment]
@paulhybryant thanks for checking. You may have been a victim of https://twitter.com/MacHomebrew/status/763686348041641984
