### ISSUE TITLE
qt6 is compiled with @rpath

### ISSUE THREAD

**Issue by sunderme** [Homebrew/homebrew-core#81390]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs qt
Error: Your Xcode (11.6) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 12.4.
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

making a self-contained app bundle
(macdeployqt ...)

### What happened (include all command output)?

macdeployqt  fails on several levels, all because the Qt*.dylibs are linked against @rpath/... , same with qt plugins.

### What did you expect to happen?

internal links against absolute paths as is the case in qt@5
qt@5 formula contains argument: ```-no-rpath```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
just run  -L /usr/local/opt/qt6/lib/QtGui.framework/QtGui
it will give several lines with @rpath/...
´´´
/usr/local/opt/qt/lib/QtGui.framework/Versions/A/QtGui (compatibility version 6.0.0, current version 6.1.2)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1894.60.100)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 162.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1355.22.0)
	/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1677.104.0)
	/usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 6801.0.0, current version 6801.3.0)
	@rpath/QtDBus.framework/Versions/A/QtDBus (compatibility version 6.0.0, current version 6.1.2)
...
´´´
```

**Comment by carlocab** [comment]
Can you give a minimal example that illustrates the problem with linking via `@rpath`?

**Comment by sunderme** [comment]
basically building any qt app and running macdeployqt ...app results in a non-working app bundle.
I am working on texstudio, not sure if you want to compile that.
See also https://github.com/texstudio-org/texstudio/issues/1699

**Comment by sunderme** [comment]
For now I am running a script which manipulates all Qt/plugin libs but that should not be necessary (especially as it works fine with qt@5)

**Comment by carlocab** [comment]
Having to compile texstudio isn't really minimal. Without a small example that reproduces the issue it's difficult to conclude that we need to change anything, especially given that no one else seems to have complained about it.

**Comment by sunderme** [comment]
I am uploading a qt example.
```
unzip test.zip
cd gui/analogclock
qmake
make
-> analogclock.app is generated
macdeployqt analogclock.app
-> this finishes but gives errors in the process (rpath). The bundle still run as it refers to home-brew, but it fails on computers without an home-brew installation (see bug report on texstudio)
-> to check this, otool -L analogclock.app/Contents/Frameworks/QtGui.framework/QtGui  presents the path-links.
```
[gui.zip](https://github.com/Homebrew/homebrew-core/files/6833095/gui.zip)

**Comment by cho-m** [comment]
I don't think your zip was created recursively.

Also, have you gone through the deployment steps discussed in https://doc.qt.io/qt-6/macos-deployment.html#linking-the-application-to-qt-as-frameworks

Specifically, the parts on copying Frameworks and then running `install_name_tool` to modify linkage.

**Comment by sunderme** [comment]
I was just zipping the analogclock example, i can refo it tomorrow.
If you scroll down your link, you end up in the description of macdeployqt. No real need to reinvent the wheel...

**Comment by cho-m** [comment]
Perhaps, assuming the wheel is rolling as expected.
The thing to determine is whether this is an issue with how `macdeployqt` works.

Here is a previously fixed Qt5.5 issue on `@rpath` https://bugreports.qt.io/browse/QTBUG-47868

**Comment by cho-m** [comment]
Also, `rpath` usage shouldn't be an issue in deployment. Qt should add `LC_RPATH`, which you can check with 
```
otool -l <app>/Contents/MacOS/<exec> | grep LC_RPATH -A2
```

The path should include `@executable_path/../Frameworks`, which means that as long as all Frameworks are correctly copied into `<app>/Contents/Frameworks`, the app will be able to find them and use them.

The problem is whether `macdeployqt` is capable of copying all Frameworks recursively. 
You can see what happens when you manually copy the missing frameworks, e.g.
```
cp -R $(brew --prefix qt)/lib/QtDBus.framework analogclock.app/Contents/Frameworks
```

---

For output errors, this could be due to plugins.
Another Homebrew issue determined to be upstream issue: https://github.com/Homebrew/homebrew-core/issues/73019#issuecomment-800701161

You can see if errors are still seen if you try without plugins: `macdeployqt <app> -no-plugins`

**Comment by sunderme** [comment]
If we are talking work-arounds, I like my solution better.
```fixRpath``` simply changes the links in the homebrew installation  and then macdeployqt works (except that it forgets one plug-in...)
see https://github.com/texstudio-org/texstudio/blob/master/.github/scripts/fixRpath.py
The macdeployqt errors come from the plug-ins, hence my script manipulates the paths there as well.

My point is that qt@5 does not use rpath and does so consciously. It probably can be turned off for qt6 with cmake options as well. If the idea is that qt6 is basically replacing qt5, but behaves basically the same, this may be a point.
If that is not the idea, I do have a work-around.

**Comment by SMillerDev** [comment]
I'm not really understanding how a failure in macqtdeploy requires homebrew changes.

**Comment by sunderme** [comment]
Using rpath does not really give an advantage for homebrew and it probably can be turned off with a simple configuration change in the qt formula. That would make life easier using homebrew in CD scenarios.
If that is not an important point, just close this issue as won't fix.

**Comment by carlocab** [comment]
Does compiling `qt` with `-no-rpath` fix your issue?

@paperchalice, @jonaski, any thoughts here?

**Comment by carlocab** [comment]
Also CC @minorsecond, @csparker247 -- I don't want to make changes to the formula without feedback from some other users.

**Comment by sunderme** [comment]
my hardware is not potent enough to compile qt, so I have not tried to tweak the cmake options.

**Comment by SMillerDev** [comment]
> Using rpath does not really give an advantage for homebrew

AFAIK it makes the install (more) portable, allowing users to install into non-standard directories if they have to. I'd say that's a pretty big advantage.

**Comment by sunderme** [comment]
> > Using rpath does not really give an advantage for homebrew
> 
> AFAIK it makes the install (more) portable, allowing users to install into non-standard directories if they have to. I'd say that's a pretty big advantage.

However all other dylib do not use rpath as far as I have seen (in the example above, that would be ```libglib-2.0.0.dylib``` )

**Comment by carlocab** [comment]
> AFAIK it makes the install (more) portable, allowing users to install into non-standard directories if they have to. I'd say that's a pretty big advantage.

This is a big bonus. `qt` didn't have a relocatable bottle in the past, and now it does. This means that users who install Homebrew into a non-default prefix no longer need to build it from source.

> However all other dylib do not use rpath as far as I have seen (in the example above, that would be `libglib-2.0.0.dylib` )

`glib` probably should; it'll help make the bottle relocatable. At the moment, you need to build `glib` from source if you're not using a default Homebrew prefix.

------

In any case, we're not making changes to a formula when we don't even know if the changes will fix the problem. Note that we use a different build system for Qt6 than we do for Qt5 [1], so it's not even at all clear that the `-no-rpath` flag does anything, much less that it resolves the issue you're having [2].

I'll also mention that the `-no-rpath` flag was left out of both PRs that attempted to update Qt to Qt6 (#67536 and #70826), so I think it's entirely reasonable to assume that they did so for good reason.

[1] The former uses CMake, and the latter doesn't.
[2] I also want to emphasise here that we don't have a simpler way to reproduce your issue, so anyone who might want to try to fix this themselves can't easily verify that your issue is fixed.

**Comment by sunderme** [comment]
alright then

**Comment by paperchalice** [comment]
`texstudio` works by copying the `QtDBus.framework` into the bundle manually after running `macdeployqt`.
