### ISSUE TITLE
Formulae that install x86_64 binaries on arm64 (or universal binaries on any macOS)

### ISSUE THREAD

**Issue by carlocab** [Homebrew/homebrew-core#81666]
New audits in `brew` allow us to identify formulae that install non-native/universal binaries into its prefix (cf. Homebrew/brew#11737 and Homebrew/brew#11750). This audit has already identified a number of formulae, and most are installed via `npm`.

We've found three (that I know of) so far that install (non-universal) x86 binaries on ARM: [`ask-cli`](https://github.com/Homebrew/homebrew-core/pull/81644), [`gatsby-cli`](https://github.com/Homebrew/homebrew-core/pull/81623), and [`netlify-cli`](https://github.com/Homebrew/homebrew-core/pull/81621). There are likely many more.

I've opened this issue to ask for thoughts on what to do about cases like the three named formulae above. Some alternatives (with varying degrees of feasibility/palatability) come to mind:

1. Ignore them. In particular, we could amend the audit so that it passes over x86_64 binaries being installed on ARM, since a user can run them under Rosetta anyway. (Some users [may not be able to install Rosetta](https://www.tomsguide.com/news/apple-could-disable-rosetta-2-in-m1-macs-in-some-regions), however.)
2. Make these formulae `depends_on :x86_64`. This would make it somewhat complicated to check when these formulae stop installing non-native binaries, however.
3. Add a new DSL: `depends_on :rosetta2`. This can be useful since not all users can or want to install Rosetta.
4. Delete the offending binaries. This might break things. (Or might not. See [`emscripten`](https://github.com/Homebrew/homebrew-core/blob/a0a740df037fa070f63531d614196b480610b30f/Formula/emscripten.rb#L140).)
5. Find a way to install native binaries instead. This is probably not feasible for things installed via `npm`, but I don't really understand Node.

Not all of these alternatives are mutually exclusive, and I'm not keen on all of them, but I've put them down here to start the discussion.

-------

There is the other case of formulae that install universal binaries on any macOS version.

Sometimes, we have to ignore them (`llvm*`, `infer` -- this is what the [allowlist](https://github.com/Homebrew/homebrew-core/blob/a0a740df037fa070f63531d614196b480610b30f/audit_exceptions/universal_binary_allowlist.json) is for).

In cases where we don't have to, we should try to use the formula's build system to install native binaries instead (e.g. you can [pass the appropriate `-arch` flag to `xcodebuild`](https://github.com/Homebrew/homebrew-core/pull/81534)). Where the build system doesn't support doing this, I've opened Homebrew/brew#11756 to implement `deuniversalize_machos` which you can call in a formula's `install` method. (I'm working under the assumption that anything that doesn't use LLVM's compiler-rt is safe to de-universalise. Someone do correct me if I'm wrong.)

CC @Homebrew/core for thoughts and as an FYI.

**Comment by SMillerDev** [comment]
> Find a way to install native binaries instead. This is probably not feasible for things installed via npm, but I don't really understand Node.

This would definitely be my preferred option. Maybe we can reach out to the (build) projects to check if there is a way?

**Comment by MikeMcQuaid** [comment]
> * Ignore them. In particular, we could amend the audit so that it passes over x86_64 binaries being installed on ARM, since a user can run them under Rosetta anyway. (Some users [may not be able to install Rosetta](https://www.tomsguide.com/news/apple-could-disable-rosetta-2-in-m1-macs-in-some-regions), however.)
> * Add a new DSL: `depends_on :rosetta2`. This can be useful since not all users can or want to install Rosetta.

Hard 👎🏻 on these from me. If we ignore/work around them: chances are they will never get fixed. If we prevent them from being installed: people will bug upstreams and/or submit PRs to us to get them fixed.

> * Make these formulae `depends_on :x86_64`. This would make it somewhat complicated to check when these formulae stop installing non-native binaries, however.

This seems reasonable to me. I figure someone will make a PR to remove this when it works.

> * Delete the offending binaries. This might break things. (Or might not. See [`emscripten`](https://github.com/Homebrew/homebrew-core/blob/a0a740df037fa070f63531d614196b480610b30f/Formula/emscripten.rb#L140).)

This also seems reasonable to me.

> 5\. Find a way to install native binaries instead. This is probably not feasible for things installed via `npm`, but I don't really understand Node.

This is obviously the best case to me but I can see why it's not very practical to do widely and quickly.

**Comment by SMillerDev** [comment]
> Make these formulae depends_on :x86_64. This would make it somewhat complicated to check when these formulae stop installing non-native binaries, however.

This wouldn't fix software installing an ARM slice on x86 though right?

**Comment by carlocab** [comment]
It wouldn't, but I was only suggesting adding `depends_on :x86_64` to formulae that install non-universal x86-only binaries on ARM.

Formulae that install universal binaries are a bit easier -- either tweak some build flags, or use some formulae DSL (when I finish my PR for it...).

**Comment by cho-m** [comment]
I agree with @MikeMcQuaid and would generally go through a workflow of:
1. try using a native binary
2. try deleting the offending binary
3. restrict to x86_64

Looking at examples (`ask-cli` #81644, `gatsby-cli` #81623, and `netlify-cli` #81621), all of these are due to NPM dependency https://github.com/sindresorhus/term-size, which includes a pre-compiled `term-size` binary.

Let's try option 1 and recompile https://github.com/sindresorhus/macos-term-size

**Comment by carlocab** [comment]
> I agree with @MikeMcQuaid and would generally go through a workflow of:
> 
> 1. try using a native binary
> 2. try deleting the offending binary
> 3. restrict to x86_64

This is almost exactly the workflow I had in mind after reading Mike's comment. My only additional suggestion is that, if we delete anything, we may want to consider mentioning that we've done so in the `caveats`, like we do in [`salt`](https://github.com/Homebrew/homebrew-core/blob/265aa256629dd2631ad8129a824c295b14bf07d4/Formula/salt.rb#L273).

**Comment by cho-m** [comment]
On side note, although Node formulae are among most common to hit this issue due to NPM dependencies, I have seen Go formulae where the main binary is compiled for x86_64 in the ARM bottle.

For example, `pup` was one I previously fixed #80929

I also see `openshift-cli` is probably wrong given that:
```
        system "make", "cross-build-darwin-amd64", "WHAT=cmd/oc"
```
Though (off-topic), the `openshift-cli` formula has other problems that makes it difficult to recommend to users. Particularly the fact that upstream has release issues and they haven't git tagged releases beyond v4.6.0 even though their stable pre-built binary is available for v4.7.19

**Comment by carlocab** [comment]
> I have seen Go formulae where the main binary is compiled for x86_64 in the ARM bottle.

I've seen those two and fixed one or two of them before -- also part of why I implemented the new audit. We'll probably discover a few more that invoke `go` using `make` but set `GOARCH=amd64`.

**Comment by MikeMcQuaid** [comment]
> I agree with @MikeMcQuaid and would generally go through a workflow of:
> 
> 1. try using a native binary
> 2. try deleting the offending binary
> 3. restrict to x86_64

This workflow makes sense to me 👍🏻

**Comment by carlocab** [comment]
I think we've settled on what we should do about the cases I talk about above, so I don't think we need to keep this open anymore.

Thanks for the feedback, all!
