### ISSUE TITLE
[Terragrunt] Remove terraform dependency

### ISSUE THREAD

**Issue by Sebor** [Homebrew/homebrew-core#81773]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16b01d6e019e93b66e41d0bb8da66fec3fcc5cca
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: be0ac220a794c2b340567ae9fa5adc821f74ca45
Core tap last commit: 86 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.4-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I try to install/upgrade terragrunt

### What happened (include all command output)?

Terragrunt has dependency of terrafrom (and it is installed too). But I want to use tfenv.
`tfenv` conflicts with terraform and I always have to do `brew unlink tfenv` or `brew unlink terraform` during `brew upgrade`

### What did you expect to happen?

Terragrunt doesn't have terraform dependency

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install terragrunt
- brew install tfenv
```

**Comment by carlocab** [comment]
Related discussion at #75836.

**Comment by Sebor** [comment]
> Related discussion at #75836.

Hi, @carlocab !
Honestly, I have not understood the decision of the discussion
