### ISSUE TITLE
tutum appears to be replaced by docker-cloud

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/homebrew-core#8199]
`tutum` appears to be redundant with, and replaced by, `docker-cloud`. Both have very similar build files, `brew home tutum` redirects to Docker Cloud, and https://blog.tutum.co/2015/10/21/docker-tutum/ indicates that the companies behind the respective utilities have merged.

Would be happy to submit a PR for this, but not sure what the appropriate action is in this case.

**Comment by MikeMcQuaid** [comment]
Sounds good to remove it and create an alias to the old name 👍
