### ISSUE TITLE
can't install php 7.1 on macOs BigSur 11.5

### ISSUE THREAD

**Issue by gamalgogo** [Homebrew/homebrew-core#82076]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew reinstall php@7.1 --build-from-source

.....
/private/tmp/phpA7.1-20210728-42953-cyvp3h/php-7.1.33/ext/intl/collator/collator_sort.c:349:26: error: use of undeclared identifier 'TRUE'
        collator_sort_internal( TRUE, INTERNAL_FUNCTION_PARAM_PASSTHRU );
                                ^
/private/tmp/phpA7.1-20210728-42953-cyvp3h/php-7.1.33/ext/intl/collator/collator_sort.c:543:26: error: use of undeclared identifier 'FALSE'
        collator_sort_internal( FALSE, INTERNAL_FUNCTION_PARAM_PASSTHRU );
                                ^
2 errors generated.
make: *** [ext/intl/collator/collator_sort.lo] Error 1
make: *** Waiting for unfinished jobs....
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install php 7.1

### What happened (include all command output)?

brew reinstall php@7.1 --build-from-source

### What did you expect to happen?

successful installation

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall php@7.1 --build-from-source
```

**Comment by SMillerDev** [comment]
We don't support source builds.
