### ISSUE TITLE
cannot install/upgrade graphviz (URL returns 404)

### ISSUE THREAD

**Issue by kontrafiktion** [Homebrew/homebrew-core#8214]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

    brew upgrade graphviz 

results in 

```
==> Downloading http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.20161221.0239.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
``` 

looking at `http://graphviz.org/pub/graphviz/stable/SOURCES/` there really is no such file.
There is a new (Dec. 24th): 

    http://graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.1.tar.gz

**Comment by ilovezfs** [comment]
This will be fixed by https://github.com/Homebrew/homebrew-core/pull/8210.
