### ISSUE TITLE
node@6 failed to build on 10.10.5

### ISSUE THREAD

**Issue by deepak** [Homebrew/homebrew-core#8228]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

Cannot install `node@6` on OSX Yosemite 10.10.5

output of brew gist-logs is:
https://gist.github.com/deepak/4702cbce465f6032dae6bcb3f7a64adc

**Comment by dunn** [comment]
Here's at least two of the errors: https://gist.github.com/deepak/4702cbce465f6032dae6bcb3f7a64adc#file-02-make-L360-L375

If possible, could you try compiling outside of Homebrew to see if this is an upstream issue or not?

**Comment by MikeMcQuaid** [comment]
This builds on our CI and we don't provide the same level of support for `@`-versioned packages.
