### ISSUE TITLE
formula libtensorflow headers missing third_party/eigen3

### ISSUE THREAD

**Issue by dolmens** [Homebrew/homebrew-core#82429]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
No logs.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

linking with libtensorflow

### What happened (include all command output)?

/usr/local/Cellar/libtensorflow/2.5.0/include/tensorflow/core/framework/tensor.h:22:10: fatal error: 'third_party/eigen3/unsupported/Eigen/CXX11/Tensor' file not found

### What did you expect to happen?

compile.
By including eigen include path did not solve the problem, cause the header should be in third_party subdirectory.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install libtensorflow
g++ -std=c++17 `pkg-config --cflags --libs tensorflow` -c main.cc

main.cc
#include <tensorflow/core/framework/tensor.h>
int main(int argc, char **argv) {
}
```

**Comment by cho-m** [comment]
As heads up, the current discussion in #82526 is to pare down the `libtensorflow` installation to only the C library to match upstream distribution: https://www.tensorflow.org/install/lang_c#download

It might be good to get some user input too, so you may want to comment over there.
