### ISSUE TITLE
Cassandra formula updated to 4.x and no 3.11 version was created

### ISSUE THREAD

**Issue by alecl** [Homebrew/homebrew-core#82445]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Cassandra 3.11 as 4.0 is new and not in use yet for my project.

### What happened (include all command output)?

$ brew install cassandra@3.11

Warning: No available formula or cask with the name "cassandra@3.11". Did you mean cassandra@2.1, cassandra or cassandra@2.2?
==> Searching for similarly named formulae...
These similarly named formulae were found:
cassandra@2.1                                                           cassandra                                                               cassandra@2.2
To install one of them, run (for example):
  brew install cassandra@2.1
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

### What did you expect to happen?

Able to install the 3.11 series version

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install cassandra@3.11

Warning: No available formula or cask with the name "cassandra@3.11". Did you mean cassandra@2.1, cassandra or cassandra@2.2?
==> Searching for similarly named formulae...
These similarly named formulae were found:
cassandra@2.1                                                           cassandra                                                               cassandra@2.2
To install one of them, run (for example):
  brew install cassandra@2.1
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by SMillerDev** [comment]
Yes, this is correct. Brew updates it's formula regularly.

**Comment by alecl** [comment]
Ok, but what is the rationale for keeping the 2.x series available for install but not the 3.x?

**Comment by SMillerDev** [comment]
Someone made a pull request to add 2.x and it met our criteria for inclusion. You can do the same thing for 3.x

**Comment by alecl** [comment]
Ok, I have found and commented on the one in progress (CI environment issue?) to hopefully get it unblocked. Thank you.

https://github.com/Homebrew/homebrew-core/pull/82177
