### ISSUE TITLE
(mpv, sierra) mpv-build dependency: llvm > make: *** [all] Error 2

### ISSUE THREAD

**Issue by mrkapqa** [Homebrew/homebrew-core#82662]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
hallo,

on sierra 10.12 building mpv with vaporsynth gives an error

i don#t know if supposed to post this here or elsewhere *mpv-build*


please see here
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

build mpv for svp4 with vaporsynth

### What happened (include all command output)?

==> Installing svpteam/mpv/mpv-build dependency: llvm
==> cmake -G Unix Makefiles .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;mlir;polly -DLLVM_ENABLE_RUNTIMES=compiler-rt;libcxx;libcxxabi;libunwind;openmp -DLLVM_POLLY_LINK_INTO_TOOLS=ON -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON -DLLVM_LINK_LLVM_DYLIB=ON -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_FFI=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_INCLUDE_DOCS=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INSTALL_UTILS=ON -DLLVM_ENABLE_Z3_SOLVER=OFF -DLLVM_OPTIMIZED_TABLEGEN=ON -DLLVM_TARGETS_TO_BUILD=all -DLLDB_USE_SYSTEM_DEBUGSERVER=ON -DLLDB_ENABLE_PYTHON=ON -DLLDB_ENABLE_LUA=OFF -DLLDB_ENABLE_LZMA=ON -DLLDB_PYTHON_RELATIVE_PATH=libexec/python3.9/site-packages -DLIBOMP_INSTALL_ALIASES=OFF -DCLANG_PYTHON_BINDINGS_VERSIONS=3.9 -DPACKAGE_VENDOR=Homebrew -DBUG_REPORT_URL=https://github.com/Homebrew/homebrew-core/issues -DCLANG_VENDOR_UTI=org.homebrew.clang -DFFI_INCLUDE_DIR=/usr/local/opt/libffi/include -DFFI_LIBRARY_DIR=/usr/local/opt/libffi/lib -DLLVM_BUILD_LLVM_C_DYLIB=ON -DLLVM_ENABLE_LIBCXX=ON -DLLVM_CREATE_XCODE_TOOLCHAIN=ON -DRUNTIMES_CMAKE_ARGS=-DCMAKE_INSTALL_RPATH=@loader_path/../lib
==> cmake --build .
Last 15 lines from /Users/rich/Library/Logs/Homebrew/llvm/02.cmake:
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86DisassemblerTables.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/X86DisassemblerTables.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/X86DisassemblerTables.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/X86DisassemblerTables.cpp
[  2%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/X86EVEX2VEXTablesEmitter.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/X86EVEX2VEXTablesEmitter.cpp
[  2%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/X86FoldTablesEmitter.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/X86FoldTablesEmitter.cpp
[  2%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o
[  2%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/X86RecognizableInstr.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/X86RecognizableInstr.cpp
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/X86ModRMFilters.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/X86ModRMFilters.cpp
[  2%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/WebAssemblyDisassemblerEmitter.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/WebAssemblyDisassemblerEmitter.cpp
[  2%] Building CXX object utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o
cd /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/build/include -I/tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/include -stdlib=libc++ -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-class-memaccess -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -O3 -DNDEBUG -std=c++14 -MD -MT utils/TableGen/CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o -MF CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o.d -o CMakeFiles/obj.llvm-tblgen.dir/CTagsEmitter.cpp.o -c /tmp/llvm-20210804-99349-1qoaetq/llvm-project-12.0.1.src/llvm/utils/TableGen/CTagsEmitter.cpp
[  2%] Built target obj.llvm-tblgen
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.

These open issues may also help:
llvm: include tests support in order to ship llvm-lit https://github.com/Homebrew/homebrew-core/pull/82479

### What did you expect to happen?

build correctly as it did in the past.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
#!/bin/sh

# This script attempts to:
# 1. Install Homebrew
# 2. Force re-install mpv with Vapoursynth support
# 3. Write recommended mpv.conf into home dir

# install Homebrew if necessary

ibrew=brew
if [ "$(uname -m)" = "arm64" ]; then
    ibrew=/opt/homebrew/bin/brew
fi    

install=0
if command -v $ibrew >/dev/null 2>&1; then
    echo
    echo WARNING!!!
    echo
    echo This script is only needed to INSTALL Homebrew and mpv for the FIRST TIME 
    echo or in case everything is broken...
    echo
    echo DO NOT CONTINUE if you only want to UPDATE SVP!
    echo Just replace SVP.app with the new version.
    echo
    echo To update mpv player simply run: brew upgrade
    echo
    read -p "Do you REALLY want to continue and completely RE-INSTALL mpv? (y/N)" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
	install=1
    fi
else
    install=1
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [[ install -eq 1 ]]; then
    $ibrew update

    if [[ ${OSTYPE:6} -le 16 ]]; then
	$ibrew install homebrew/cask-versions/adoptopenjdk8; #libbluray requires this on <=10.12)
    fi

    # remove any previous version (probably w/o vapoursynth support)
    $ibrew uninstall --cask --force mpv
    $ibrew uninstall --force mpv mvtools vapoursynth
    
    
    if [[ ${OSTYPE:6} -le 17 ]]; then
	#build from sources on <=10.13
	$ibrew install svpteam/mpv/mpv-build 2>&1 | tee ~/"Library/Application Support/SVP4/logs/brew.log"
    else
	# install mpv
	$ibrew install mpv 2>&1 | tee ~/"Library/Application Support/SVP4/logs/brew.log"
	# install mkvmerge (required for SVPcode)
	$ibrew install mkvtoolnix
    fi

    # write default mpv.conf
    mpv --version > /dev/null 2>&1

    cat << EOF > ~/.config/mpv/mpv.conf
input-ipc-server=/tmp/mpvsocket
hwdec-codecs=all
hwdec=auto-copy
opengl-early-flush=no
hr-seek-framedrop=no
EOF
fi
```

**Comment by SMillerDev** [comment]
> Do not report this issue to Homebrew/brew or Homebrew/core!

> Error: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
