### ISSUE TITLE
foma formula

### ISSUE THREAD

**Issue by arademaker** [Homebrew/homebrew-core#82702]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs foma
Error: No logs.

% brew config
HOMEBREW_VERSION: 3.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 265c8c36a4c0a74f478cba16417940b3b588736c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e091baad4f57029045ce4600f141b21419e1affa
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.q5pvU9sNTN/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

the foma formula uses Graphviz to display graphs. 

### What happened (include all command output)?

foma[1]: Unable to find application named 'Graphviz'

### What did you expect to happen?

A graphical window should open with an image of the automata.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install foma
brew install graphviz
foma
$ regex a* b* ;
$ view
```

**Comment by carlocab** [comment]
`foma` doesn't have a `graphviz` dependency, so it's likely that the `foma` formula just doesn't have `graphviz` support built with it.

**Comment by cho-m** [comment]
`foma` tries to run a GUI Graphviz app: `/usr/bin/open -a Graphviz`.

Homebrew formulae usually don't build apps, so it is unlikely to be supported by `graphviz` formula.

Homebrew casks need an upstream-maintained app. I wasn't able to find any from Graphviz homepage, so it is also not likely to be supported in a cask.

From https://graphviz.org/download/#mac, it looks like the only options are to either use the MacPorts GUI port (https://ports.macports.org/port/graphviz-gui/) or to build it from source.

**Comment by arademaker** [comment]
there is a workaround here https://sites.pitt.edu/~naraehan/ling1330/ex8.html using `print dot`
