### ISSUE TITLE
Mariadb Package is forbidden

### ISSUE THREAD

**Issue by andreasemer** [Homebrew/homebrew-core#83022]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Currently it's not possible to install the package 'mariadb' with 'brew install mariadb' in MacOS Big Sur. 

The package resource https://homebrew.bintray.com/bottles/mariadb-10.5.8.big_sur.bottle.2.tar.gz semse to have issues, there is the message "Forbidden!".
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I have tried to install mariadb, because i want to use it 😅

### What happened (include all command output)?

⚡ brew install mariadb
==> Downloading https://homebrew.bintray.com/bottles/mariadb-10.5.8.big_sur.bottle.2.tar.gz
-=O#- #  #    #
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "mariadb"
Download failed: https://homebrew.bintray.com/bottles/mariadb-10.5.8.big_sur.bottle.2.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.mariadb.com/MariaDB/mariadb-10.5.8/source/mariadb-10.5.8.tar.gz
Already downloaded: /Users/andreas/Library/Caches/Homebrew/downloads/7263889c7e320bd9b683d55595c72a3c03a01189c05253cb6fd6b828002190d2--mariadb-10.5.8.tar.gz
==> cmake . -DMYSQL_DATADIR=/usr/local/var/mysql -DINSTALL_INCLUDEDIR=include/mysql -DINSTALL_MANDIR=share/man -DINSTALL_DOCDIR=share/doc/mariadb -DINSTALL_I
==> make
Last 15 lines from /Users/andreas/Library/Logs/Homebrew/mariadb/02.make:
[ 55%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/ut/ut0rnd.cc.o
cd /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBTR_CUR_ADAPT -DBTR_CUR_HASH_ADAPT -DCOMPILER_HINTS -DDBUG_TRACE -DHAVE_BZIP2=1 -DHAVE_CONFIG_H -DHAVE_LZMA=1 -DHAVE_NANOSLEEP=1 -DHAVE_OPENSSL -DMUTEX_EVENT -DWITH_INNODB_DISALLOW_WRITES -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/wsrep-API/v26 -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/handler -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/libbinlogevents/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/tpool -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/sql -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2-build -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2/src -pie -fPIC -fstack-protector --param=ssp-buffer-size=4 -Wconversion -Wno-sign-conversion -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk  -fvisibility=hidden -std=gnu++11 -o CMakeFiles/innobase.dir/ut/ut0rnd.cc.o -c /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/ut/ut0rnd.cc
[ 55%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/ut/ut0ut.cc.o
cd /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBTR_CUR_ADAPT -DBTR_CUR_HASH_ADAPT -DCOMPILER_HINTS -DDBUG_TRACE -DHAVE_BZIP2=1 -DHAVE_CONFIG_H -DHAVE_LZMA=1 -DHAVE_NANOSLEEP=1 -DHAVE_OPENSSL -DMUTEX_EVENT -DWITH_INNODB_DISALLOW_WRITES -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/wsrep-API/v26 -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/handler -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/libbinlogevents/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/tpool -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/sql -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2-build -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2/src -pie -fPIC -fstack-protector --param=ssp-buffer-size=4 -Wconversion -Wno-sign-conversion -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk  -fvisibility=hidden -std=gnu++11 -o CMakeFiles/innobase.dir/ut/ut0ut.cc.o -c /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/ut/ut0ut.cc
[ 55%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/ut/ut0vec.cc.o
cd /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBTR_CUR_ADAPT -DBTR_CUR_HASH_ADAPT -DCOMPILER_HINTS -DDBUG_TRACE -DHAVE_BZIP2=1 -DHAVE_CONFIG_H -DHAVE_LZMA=1 -DHAVE_NANOSLEEP=1 -DHAVE_OPENSSL -DMUTEX_EVENT -DWITH_INNODB_DISALLOW_WRITES -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/wsrep-API/v26 -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/handler -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/libbinlogevents/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/tpool -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/sql -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2-build -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2/src -pie -fPIC -fstack-protector --param=ssp-buffer-size=4 -Wconversion -Wno-sign-conversion -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk  -fvisibility=hidden -std=gnu++11 -o CMakeFiles/innobase.dir/ut/ut0vec.cc.o -c /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/ut/ut0vec.cc
[ 55%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/ut/ut0wqueue.cc.o
cd /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBTR_CUR_ADAPT -DBTR_CUR_HASH_ADAPT -DCOMPILER_HINTS -DDBUG_TRACE -DHAVE_BZIP2=1 -DHAVE_CONFIG_H -DHAVE_LZMA=1 -DHAVE_NANOSLEEP=1 -DHAVE_OPENSSL -DMUTEX_EVENT -DWITH_INNODB_DISALLOW_WRITES -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/wsrep-lib/wsrep-API/v26 -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/handler -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/libbinlogevents/include -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/tpool -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/sql -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2-build -I/tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/extra/pcre2/src/pcre2/src -pie -fPIC -fstack-protector --param=ssp-buffer-size=4 -Wconversion -Wno-sign-conversion -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk  -fvisibility=hidden -std=gnu++11 -o CMakeFiles/innobase.dir/ut/ut0wqueue.cc.o -c /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase/ut/ut0wqueue.cc
[ 55%] Linking CXX static library libinnobase.a
cd /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase && /usr/local/Cellar/cmake/3.19.4/bin/cmake -P CMakeFiles/innobase.dir/cmake_clean_target.cmake
cd /tmp/mariadb-20210809-18287-gbf7r2/mariadb-10.5.8/storage/innobase && /usr/local/Cellar/cmake/3.19.4/bin/cmake -E cmake_link_script CMakeFiles/innobase.dir/link.txt --verbose=1
/usr/bin/ar qc libinnobase.a CMakeFiles/innobase.dir/btr/btr0btr.cc.o CMakeFiles/innobase.dir/btr/btr0bulk.cc.o CMakeFiles/innobase.dir/btr/btr0cur.cc.o CMakeFiles/innobase.dir/btr/btr0pcur.cc.o CMakeFiles/innobase.dir/btr/btr0sea.cc.o CMakeFiles/innobase.dir/btr/btr0defragment.cc.o CMakeFiles/innobase.dir/buf/buf0block_hint.cc.o CMakeFiles/innobase.dir/buf/buf0buddy.cc.o CMakeFiles/innobase.dir/buf/buf0buf.cc.o CMakeFiles/innobase.dir/buf/buf0dblwr.cc.o CMakeFiles/innobase.dir/buf/buf0checksum.cc.o CMakeFiles/innobase.dir/buf/buf0dump.cc.o CMakeFiles/innobase.dir/buf/buf0flu.cc.o CMakeFiles/innobase.dir/buf/buf0lru.cc.o CMakeFiles/innobase.dir/buf/buf0rea.cc.o CMakeFiles/innobase.dir/data/data0data.cc.o CMakeFiles/innobase.dir/data/data0type.cc.o CMakeFiles/innobase.dir/dict/dict0boot.cc.o CMakeFiles/innobase.dir/dict/dict0crea.cc.o CMakeFiles/innobase.dir/dict/dict0dict.cc.o CMakeFiles/innobase.dir/dict/dict0load.cc.o CMakeFiles/innobase.dir/dict/dict0mem.cc.o CMakeFiles/innobase.dir/dict/dict0stats.cc.o CMakeFiles/innobase.dir/dict/dict0stats_bg.cc.o CMakeFiles/innobase.dir/dict/dict0defrag_bg.cc.o CMakeFiles/innobase.dir/eval/eval0eval.cc.o CMakeFiles/innobase.dir/eval/eval0proc.cc.o CMakeFiles/innobase.dir/fil/fil0fil.cc.o CMakeFiles/innobase.dir/fil/fil0pagecompress.cc.o CMakeFiles/innobase.dir/fil/fil0crypt.cc.o CMakeFiles/innobase.dir/fsp/fsp0fsp.cc.o CMakeFiles/innobase.dir/fsp/fsp0file.cc.o CMakeFiles/innobase.dir/fsp/fsp0space.cc.o CMakeFiles/innobase.dir/fsp/fsp0sysspace.cc.o CMakeFiles/innobase.dir/fut/fut0lst.cc.o CMakeFiles/innobase.dir/ha/ha0storage.cc.o CMakeFiles/innobase.dir/fts/fts0fts.cc.o CMakeFiles/innobase.dir/fts/fts0ast.cc.o CMakeFiles/innobase.dir/fts/fts0blex.cc.o CMakeFiles/innobase.dir/fts/fts0config.cc.o CMakeFiles/innobase.dir/fts/fts0opt.cc.o CMakeFiles/innobase.dir/fts/fts0pars.cc.o CMakeFiles/innobase.dir/fts/fts0que.cc.o CMakeFiles/innobase.dir/fts/fts0sql.cc.o CMakeFiles/innobase.dir/fts/fts0tlex.cc.o CMakeFiles/innobase.dir/gis/gis0geo.cc.o CMakeFiles/innobase.dir/gis/gis0rtree.cc.o CMakeFiles/innobase.dir/gis/gis0sea.cc.o CMakeFiles/innobase.dir/fts/fts0plugin.cc.o CMakeFiles/innobase.dir/handler/ha_innodb.cc.o CMakeFiles/innobase.dir/handler/handler0alter.cc.o CMakeFiles/innobase.dir/handler/i_s.cc.o CMakeFiles/innobase.dir/ibuf/ibuf0ibuf.cc.o CMakeFiles/innobase.dir/lock/lock0iter.cc.o CMakeFiles/innobase.dir/lock/lock0prdt.cc.o CMakeFiles/innobase.dir/lock/lock0lock.cc.o CMakeFiles/innobase.dir/lock/lock0wait.cc.o CMakeFiles/innobase.dir/log/log0log.cc.o CMakeFiles/innobase.dir/log/log0recv.cc.o CMakeFiles/innobase.dir/log/log0crypt.cc.o CMakeFiles/innobase.dir/log/log0sync.cc.o CMakeFiles/innobase.dir/mem/mem0mem.cc.o CMakeFiles/innobase.dir/mtr/mtr0mtr.cc.o CMakeFiles/innobase.dir/os/os0file.cc.o CMakeFiles/innobase.dir/os/os0event.cc.o CMakeFiles/innobase.dir/os/os0thread.cc.o CMakeFiles/innobase.dir/page/page0cur.cc.o CMakeFiles/innobase.dir/page/page0page.cc.o CMakeFiles/innobase.dir/page/page0zip.cc.o CMakeFiles/innobase.dir/pars/lexyy.cc.o CMakeFiles/innobase.dir/pars/pars0grm.cc.o CMakeFiles/innobase.dir/pars/pars0opt.cc.o CMakeFiles/innobase.dir/pars/pars0pars.cc.o CMakeFiles/innobase.dir/pars/pars0sym.cc.o CMakeFiles/innobase.dir/que/que0que.cc.o CMakeFiles/innobase.dir/read/read0read.cc.o CMakeFiles/innobase.dir/rem/rem0cmp.cc.o CMakeFiles/innobase.dir/rem/rem0rec.cc.o CMakeFiles/innobase.dir/row/row0ext.cc.o CMakeFiles/innobase.dir/row/row0ftsort.cc.o CMakeFiles/innobase.dir/row/row0import.cc.o CMakeFiles/innobase.dir/row/row0ins.cc.o CMakeFiles/innobase.dir/row/row0merge.cc.o CMakeFiles/innobase.dir/row/row0mysql.cc.o CMakeFiles/innobase.dir/row/row0log.cc.o CMakeFiles/innobase.dir/row/row0purge.cc.o CMakeFiles/innobase.dir/row/row0row.cc.o CMakeFiles/innobase.dir/row/row0sel.cc.o CMakeFiles/innobase.dir/row/row0uins.cc.o CMakeFiles/innobase.dir/row/row0umod.cc.o CMakeFiles/innobase.dir/row/row0undo.cc.o CMakeFiles/innobase.dir/row/row0upd.cc.o CMakeFiles/innobase.dir/row/row0quiesce.cc.o CMakeFiles/innobase.dir/row/row0vers.cc.o CMakeFiles/innobase.dir/srv/srv0mon.cc.o CMakeFiles/innobase.dir/srv/srv0srv.cc.o CMakeFiles/innobase.dir/srv/srv0start.cc.o CMakeFiles/innobase.dir/sync/sync0arr.cc.o CMakeFiles/innobase.dir/sync/sync0rw.cc.o CMakeFiles/innobase.dir/sync/sync0debug.cc.o CMakeFiles/innobase.dir/sync/sync0sync.cc.o CMakeFiles/innobase.dir/trx/trx0i_s.cc.o CMakeFiles/innobase.dir/trx/trx0purge.cc.o CMakeFiles/innobase.dir/trx/trx0rec.cc.o CMakeFiles/innobase.dir/trx/trx0roll.cc.o CMakeFiles/innobase.dir/trx/trx0rseg.cc.o CMakeFiles/innobase.dir/trx/trx0sys.cc.o CMakeFiles/innobase.dir/trx/trx0trx.cc.o CMakeFiles/innobase.dir/trx/trx0undo.cc.o CMakeFiles/innobase.dir/ut/ut0dbg.cc.o CMakeFiles/innobase.dir/ut/ut0list.cc.o CMakeFiles/innobase.dir/ut/ut0mem.cc.o CMakeFiles/innobase.dir/ut/ut0new.cc.o CMakeFiles/innobase.dir/ut/ut0rbt.cc.o CMakeFiles/innobase.dir/ut/ut0rnd.cc.o CMakeFiles/innobase.dir/ut/ut0ut.cc.o CMakeFiles/innobase.dir/ut/ut0vec.cc.o CMakeFiles/innobase.dir/ut/ut0wqueue.cc.o
/usr/bin/ranlib libinnobase.a
[ 55%] Built target innobase
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
mariadb@10.4 10.4.21 https://github.com/Homebrew/homebrew-core/pull/82862
mariadb@10.3 10.3.31 https://github.com/Homebrew/homebrew-core/pull/82861
mariadb@10.2 10.2.40 https://github.com/Homebrew/homebrew-core/pull/82860
mariadb@10.5 10.5.12 https://github.com/Homebrew/homebrew-core/pull/82859

### What did you expect to happen?

Install mariadb with 'brew install mariadb'

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mariadb
```

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`, as requested by the issue template, and please be sure to provide all the requested information next time.

**Comment by andreasemer** [comment]
You are right, a simple 'brew update' fixed the issue. 

Thank you very much and have a great day!

**Comment by carlocab** [comment]
Great; glad you're sorted.

Please pay closer attention to the issue template in the future. It also asked you to run `brew update` and then verify that your issue persists.
