### ISSUE TITLE
Packaging of PARI incomplete, unusable for SageMath

### ISSUE THREAD

**Issue by mkoeppe** [Homebrew/homebrew-core#83030]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Building SageMath from source following https://github.com/sagemath/sage/blob/develop/README.md#instructions-to-build-from-source

### What happened (include all command output)?

As discussed with @alebcay in https://twitter.com/mkoeppe_math/status/1424793392504995843, homebrew's PARI packaging lacks various data packages.

```
sage-9.4rc1$ brew install pari
[...]
sage-9.4rc1$ . ./.homebrew-build-env
sage-9.4rc1$ ./configure
[...]
Checking whether SageMath should install SPKG pari...
checking whether any of gmp mpir readline is installed as or will be installed as SPKG... no
checking for gp... /usr/local/bin/gp
checking for gphelp... /usr/local/bin/gphelp
checking whether gphelp has access to the documentation... yes
checking is pari_elldata installed? ... no; cannot use system pari/GP without elldata package
configure: Install elldata package and reconfigure.
configure: Otherwise Sage will build its own pari/GP.
checking is pari_galdata installed? ... no; cannot use system pari/GP without galdata package
configure: Install galdata package and reconfigure.
configure: Otherwise Sage will build its own pari/GP.
checking is pari_galpol installed? ... no; cannot use system pari/GP without galpol package
configure: Install galpol package and reconfigure.
configure: Otherwise Sage will build its own pari/GP.
checking is pari_seadata installed? ... no; cannot use system pari/GP without seadata package
configure: Install seadata package and reconfigure.
configure: Otherwise Sage will build its own pari/GP.
checking whether rnfdisc bug of pari 2.13.1 is fixed... yes
configure: no suitable system package found for SPKG pari
```

### What did you expect to happen?

A complete installation of PARI 2.13.x would be accepted by SageMath's ./configure.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
sage-9.4rc1$ brew install pari
[...]
sage-9.4rc1$ . ./.homebrew-build-env
sage-9.4rc1$ ./configure
[...]
sage-9.4rc1$ cat config.log
```
```

**Comment by alebcay** [comment]
@mkoeppe, #83158 contains the last of the components that appear to be missing - once that's merged, everything should be available. When I try to compile SageMath 9.3 (after applying the Homebrew build env they provide), I see:

```
Checking whether SageMath should install SPKG pari...
checking whether any of gmp mpir readline is installed as or will be installed as SPKG... no
checking for gp... /usr/local/bin/gp
checking for gphelp... /usr/local/bin/gphelp
checking whether gphelp has access to the documentation... yes
checking is pari_elldata installed? ... yes
checking is pari_galdata installed? ... yes
checking is pari_galpol installed? ... yes
checking is pari_seadata installed? ... yes
checking whether hyperellcharpoly bug is fixed... yes
checking whether bnfisunit bug of pari 2.11.3 is fixed... no; cannot use system pari/GP with known bug
configure: Upgrade your system package and reconfigure.
configure: Otherwise Sage will build its own pari/GP.
checking whether qfisom bug of pari 2.11.2 is fixed... yes
configure: error: given --with-system-pari=force but no system package could be used
```

So all the packages it needs are found. I'm not sure why it's complaining about the `bnfisunit` bug. From my reading of pari 2.11.4 release notes, the bug in question is https://pari.math.u-bordeaux.fr/cgi-bin/bugreport.cgi?bug=2208. But opening a `gp` prompt and typing the example case mentioned in that bug report gives the expected (correct) answer.

**Comment by mkoeppe** [comment]
Please try with Sage 9.4.rc1 - it has the preparation for pari 2.13 (https://trac.sagemath.org/ticket/30801)

**Comment by mkoeppe** [comment]
On the Sage side of things, I have opened https://trac.sagemath.org/ticket/, which will inform users and our CI about the new homebrew packages

**Comment by alebcay** [comment]
Thanks. I tried with 9.4.rc1 and found that it doesn't like Homebrew `pari` due to lack of thread support. Tested locally after rebuilding `pari` with `--mt=pthread` and the configure passes. This change is pending in #83172.

**Comment by alebcay** [comment]
All of the packages are in now. SageMath 9.4.rc1 successfully configures with Homebrew `pari` once the four data packages are installed.

**Comment by mkoeppe** [comment]
Thanks very much!
