### ISSUE TITLE
Upgrade to Hugo 0.18.1

### ISSUE THREAD

**Issue by bep** [Homebrew/homebrew-core#8316]
An important bug fix release, esp. for 32-bit binaries.

https://github.com/spf13/hugo/releases/tag/v0.18.1

**Note:** No dependency changes from 0.18.

/cc @dunn

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by bep** [comment]
Sorry, I do waaay too much Hugo related open source work already. I'm not adding one more thing to that plate.

**Comment by MikeMcQuaid** [comment]
Ok, no worries. This will get updated at some point.

**Comment by bep** [comment]
Are you saying that you don't accept issues tracking updates?

**Comment by MikeMcQuaid** [comment]
Any maintainer who wishes to update this will have seen this issue. There's no need for us to keep it open. I, like you, have too much stuff going on to update this personally and that's fine. It'll be updated when someone wants the update.

**Comment by ilovezfs** [comment]
voilà https://github.com/Homebrew/homebrew-core/pull/8331
