### ISSUE TITLE
Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!

### ISSUE THREAD

**Issue by BR00l** [Homebrew/homebrew-core#83244]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 265c8c36a4c0a74f478cba16417940b3b588736c
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 72c29a9154a8ee0870851f6cd239540e084d9ded
Core tap last commit: 8 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_REPOSITORY: /opt/homebrew
HOMEBREW_CELLAR: /opt/homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 12.0.5 build 1205
Git: 2.32.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
Rosetta 2: true


Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

 I just set up Alacritty and fish shell, and I was trying to do the normal update and upgrade as I usually do and then this happened.

Did I missed somehting?

### What happened (include all command output)?

Even when I try to run the above commands (brew update and brew upgrade) Im getting the same results from Alacritty and iterm.

### What did you expect to happen?

I expected everything to end as normal.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade (here the thing happen)
```

**Comment by gromgit** [comment]
From your `brew doctor` output:
> ```
> Warning: Your Homebrew's prefix is not /usr/local.
> Some of Homebrew's bottles (binary packages) can only be used with the default
> prefix (/usr/local).
> ```

Since you were previously able to install stuff in `/opt/homebrew` without issue, I'm guessing your setup now aliases `brew` to `arch -x86_64 /opt/homebrew/bin/brew`, i.e. you're forcing your M1-setup Homebrew to run in Rosetta.

If that's the case, you need to stop doing that.

**Comment by BR00l** [comment]
I cant recall messing with brew aliases at all. I havent change any alias to be honest, I ll double check it though. I cant imagine how this has be done. Maybe the 11.5.2 Mac Os update interfered with something?

**Comment by carlocab** [comment]
If you use a different terminal (i.e. not Alacritty, e.g. iTerm2 or Apple Terminal), do you have the same issue?

**Comment by BR00l** [comment]
I was about to say that, in Apple terminal, the normal brew update and brew upgrade works just fine, when I run them with zsh. I think fish may be problematic in a way, maybe Im missing something?

**Comment by carlocab** [comment]
No, I don't think the issue is `fish`. The problem is in Alacritty; it's currently only compiled for Intel, so it runs under Rosetta. 

```
❯ file /Applications/Alacritty.app/Contents/MacOS/alacritty
/Applications/Alacritty.app/Contents/MacOS/alacritty: Mach-O 64-bit executable x86_64
```

That means anything you run in your Alacritty terminal will run in Rosetta as well. See also alacritty/alacritty#4727.

Workarounds include:

1. Use a different terminal
2. Compile your own native version of Alacritty
3. Prepend all your `brew` calls with `arch -arm64` (Haven't tested this, so not 100% sure this will work)

**Comment by BR00l** [comment]
Oof, I wanted to transit to Alacritty for better, but what a mess it created. Thank you for your help, I ll try the compile method and see what will happen.
