### ISSUE TITLE
gpg-zip missing from gnupg2

### ISSUE THREAD

**Issue by Richie765** [Homebrew/homebrew-core#8327]
Could gpg-zip be included in gnupg2? Or is there another way to get it? Thanks!

**Comment by MikeMcQuaid** [comment]
It's not currently provided but we'd consider adding it. Could you see if you could try? [This document](https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
@Richie765 if you brew update and brew upgrade gnupg2, you should now have gpg-zip.

**Comment by jcrben** [comment]
for anyone who stumbles on this, you'll need `brew install gnupg --with-gpg-zip`
