### ISSUE TITLE
Duplicate Registration of Qt 5 After Removal Of Qt 4 From Homebrew Core

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#8342]
### Please follow the general troubleshooting steps first:
[Have you:]  
- [x] [Run] `brew update` and retried your prior step?  
- [x] [Run] `brew doctor`, fixed as many issues as possible[,] and retried your prior step?  
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew?  If it's a general Homebrew/brew problem[, then] please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:  

(Issue discussion continued/forked from [here](https://github.com/Homebrew/homebrew-core/pull/8306#issuecomment-269824169) and [here](https://github.com/Homebrew/homebrew-core/pull/8334#issuecomment-269831482).)  

For users who had both `qt` (Qt 4.x) and `qt5` installed before the resolution and merging of #8306, running `brew update` to get the latest Homebrew implementation and tap changes on their systems and then running `brew outdated -v` to check for outdated packages results in the latter command reporting the existence outdated copies of Qt _5_.x _twice_.  I believe that this is a consequence of the fact that the same PR mentioned above made it so that `qt` is now an alias to `qt5`.  

Output of `brew config`:  

```
HOMEBREW_VERSION: 1.1.5
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cd5a21b473f0271b162bbe7f77f7d1468c0cfa1
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: af7ffaddab5edea4ed2fd3011fbcfb310a8d80c8
Core tap last commit: 78 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: dual-core 64-bit core2
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_112, 1.8.0_111
macOS: 10.11.6-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

Output of `brew doctor`:  

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  qt5
```

(NOTE:  I'd bet that this has to do with only _one_ of the duplicate Homebrew-bookkept references to `qt5`.  This is why I've left things as is for now, as I also suspect that this `brew doctor` notice will disappear as soon as said duplicate entries are fixed up.)  

Output of `brew outdated -v`:  

```
doxygen (1.8.12) < 1.8.13
gnutls (3.4.17) < 3.4.17_1
leptonica (1.73) < 1.74
qt5 (5.7.0) < 5.7.1
qt5 (5.7.0) < 5.7.1
```

(Notice the duplicate `qt5` entries.  Also, the other entries in this list have `qt5` as a dependency&thinsp;—&thinsp;`doxygen` because I built it from source `--with-qt5`; `gnutls` because I built it from source `--with-unbound`, `unbound` `depends_on` `libevent`, and `libevent` `depends_on` `doxygen` by default, though this can be disabled using the `--without-doxygen` option despite the fact that using this option is neither existing nor contemplated practice on my part since I like having documentation stored locally on my machine; and `leptonica` because I built it from source `--with-openjpeg`, among other options, and `openjpeg` is a case identical to that of `libevent` in that it `depends_on` `doxygen` by default.)  

(In addition, please finally note that I have not included any other logs in this issue report because the relevant problem manifests itself _before_ I run `brew upgrade --build-from-source`, which has made me wary to do so, as Qt is expensive _enough_ to do this _once_, let alone _twice!_)

**Comment by MikeMcQuaid** [comment]
> brew upgrade --build-from-source, which has made me wary to do so, as Qt is expensive enough to do this once, let alone twice!)

As noted before: I strongly recommend not using `--build-from-source` but if you do please refrain from using it as a reason to not follow procedure in issues.

I've tested the `brew upgrade` here and it'll only be done once.

**Comment by RandomDSdevel** [comment]
@MikeMcQuaid:  OK, I knew I'm a bit of an outlier when it comes to building from source, but didn't I fill in the issue form correctly once I got around to properly splitting my problem out into its own issue even though I know I should have done that first thing?  (I'll be more careful about that in future, by the way, as I realize now that automated GitHub issue mention notifications should call enough attention to new issues related to old ones.)  In any case, it's good to know that Homebrew won't get _too_ confused when I `brew upgrade`, especially now that you've closed this in the PR that GitHub mentioned referenced this one.

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel My point was mostly don't say "I'm too scared to `brew upgrade` as I'm building from source" and not expect to get "well don't do that then".

**Comment by RandomDSdevel** [comment]
<img src="http://emojipedia-us.s3.amazonaws.com/cache/41/90/41908c8fb293292bbc00214083c0b34f.png" height="16" width="16">  I didn't say I was 'scared' to `brew upgrade` _because_ I build from source.  What I was _trying_ to get across was that I was only wary of tangling up Homebrew's internal bookkeeping with multiple references to the same formula any further than `brew outdated` said it already was.  After all, how was _I_ to know that everything would straighten itself out even _without_ the PR you just merged?  I mean, common sense and a relative lack of knowledge about Homebrew's internal implementation details&thinsp;—yes, I _know_ I need to start resolving the latter deficiency on my part&thinsp;—&thinsp;dictated that `brew upgrade` would iterate naïvely through the list of packages reported by `brew outdated` as being tracked internally by Homebrew as ready to upgrade and build and install them.  I'm sorry to have let this misunderstanding, among others, get in the way of progress, both in the name of this project and with regards to my downstream circumstances.  Again, I'll try my darnedest not to allow myself to become _too_ obtuse in the future.
