### ISSUE TITLE
Boost157.rb support request

### ISSUE THREAD

**Issue by yiakwy** [Homebrew/homebrew-core#8364]
As we developers know. Homebrew does not support boost157 and none of versions above it or lower than it can work well with cudaCNN. We also are not able to install boost157 directly because boost157 does not use sha256 instead sha1, hence deprecated by homebrew. This will be a serious problem for a large number of developers.

If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor` or if reporting a formula issue include the link from:
`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build). Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

Please replace this section with the homepage and name of your requested formula (after using `brew search` to check it does not already exist). Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by ilovezfs** [comment]
Closed by Homebrew/homebrew-versions#1500 in https://github.com/Homebrew/homebrew-versions/commit/c00215bff919633c6649fbe6bb85752cf0762547.

**Comment by yiakwy** [comment]
@ilovezfs  Thanks! Happy new year!!!

**Comment by yiakwy** [comment]
@ilovezfs  Sorry I don't know how to use kegonly formula. Once installed, there is no effect in my system. I use cmake to compile caffe. Have you tried it before?

**Comment by ilovezfs** [comment]
@yiakwy https://github.com/ilovezfs/homebrew-caffe

```
brew tap ilovezfs/caffe
brew install -s boost-python157
brew install -s caffe
```

**Comment by yiakwy** [comment]
@ilovezfs I have caffe source. I use cmake to compile it. My codes work in ONLY_CPU mode but failed  to use compile codes using cuda. People said that this was caused by boost version problems. Hence I need to jump back to old version, say 1.57.

```
Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/boost157/lib
    CPPFLAGS: -I/usr/local/opt/boost157/include
```

cmake will fail because no boost version available if I install boost157. But cmake can detect boost1.63 the latest version.

**Comment by ilovezfs** [comment]
Did you try the above formula? :)

**Comment by yiakwy** [comment]
yes, updating xcode:

Error: Your Xcode (6.4) is outdated.
Please update to Xcode 7.2.1 (or delete it).
Xcode can be updated from the App Store.


Error: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

**Comment by yiakwy** [comment]
@ilovezfs  doesn't work properly:

```bash
Updating Homebrew...
==> Installing caffe from ilovezfs/caffe
==> Downloading https://github.com/BVLC/caffe/archive/1.0.0-rc4.tar.gz
Already downloaded: /Users/wangyi/Library/Caches/Homebrew/caffe-1.0.0-rc4.tar.gz
==> cmake . -DBoost_PYTHON_LIBRARY_RELEASE=/usr/local/opt/boost-python157/lib/libboost_python-mt.dylib -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE
==> make install
Last 15 lines from /Users/wangyi/Library/Logs/Homebrew/caffe/02.make:
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bnll_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_norm_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_reindex_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at cuda_compile_1_generated_concat_layer.cu.o.Release.cmake:222 (message):
  Error generating
  /tmp/caffe-20170116-96390-aaao5w/caffe-1.0.0-rc4/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_concat_layer.cu.o


make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_concat_layer.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ilovezfs/homebrew-caffe/issues
```

Another problem is, typically, I need to compile my own version of caffe. Researchers will also use different versions. Brew install caffe, is not optimal for me.

**Comment by ilovezfs** [comment]
>nvcc fatal   : Unsupported gpu architecture 'compute_60'

not sure what that has to do with it being under brew install. I assume that's the same error you've been getting anyway?

**Comment by yiakwy** [comment]
if I use the boost keponly, an error will be fired:

-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1188 (file):
  file STRINGS file "/usr/local/include/boost/version.hpp" cannot be read.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:43 (include)


CMake Warning at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 0
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:43 (include)


CMake Warning at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 0
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:43 (include)


CMake Warning at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 0
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:43 (include)


CMake Warning at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 0
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:43 (include)


CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1812 (message):
  Unable to find the requested Boost libraries.

  Boost version: 0.0.0

  Boost include path: /usr/local/include

  Detected version of Boost is too old.  Requested version was 1.46 (or
  newer).
Call Stack (most recent call first):
  cmake/Dependencies.cmake:5 (find_package)
  CMakeLists.txt:43 (include)


-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.dylib)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.dylib)
-- Found PROTOBUF Compiler: /usr/local/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found lmdb    (include: /usr/local/include, library: /usr/local/lib/liblmdb.dylib)
-- Found LevelDB (include: /usr/local/include, library: /usr/local/lib/libleveldb.dylib)
-- Found Snappy  (include: /usr/local/include, library: /usr/local/lib/libsnappy.dylib)
-- CUDA detected: 7.0
-- Added CUDA NVCC flags for: sm_30
-- OpenCV found (/usr/local/share/OpenCV)
-- Found vecLib as part of Accelerate.framework
-- NumPy ver. 1.11.1 found (include: /Library/Python/2.7/site-packages/numpy/core/include)
CMake Error at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1188 (file):
  file STRINGS file "/usr/local/include/boost/version.hpp" cannot be read.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:147 (find_package)
  CMakeLists.txt:43 (include)


CMake Warning at /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:761 (message):
  Imported targets not available for Boost version 0
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:865 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/Cellar/cmake/3.7.2/share/cmake/Modules/FindBoost.cmake:1454 (_Boost_MISSING_DEPENDENCIES)
  cmake/Dependencies.cmake:147 (find_package)
  CMakeLists.txt:43 (include)


-- Could NOT find Boost
-- Found Doxygen: /usr/local/bin/doxygen (found version "1.8.13")
-- Python interface is disabled or not all required dependencies found. Building without it...
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- Found Git: /usr/bin/git (found version "2.5.4 (Apple Git-61)")
--
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc2-1375-gde1fd50-dirty
--   System            :   Darwin
--   C++ compiler      :   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (vecLib)
--   Boost             :   Yes (ver. 0.0)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.1.0)
--   lmdb              :   Yes (ver. 0.9.20)
--   LevelDB           :   Yes (ver. 1.19)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 2.4.13.1)
--   CUDA              :   Yes (ver. 7.0)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_30
--   cuDNN             :   Not found
--
-- Documentaion:
--   Doxygen           :   /usr/local/bin/doxygen (1.8.13)
--   config_file       :   /Users/wangyi/GitHub/SSD/caffe/.Doxyfile
--
-- Install:
--   Install path      :   /Users/wangyi/GitHub/SSD/caffe/build/install
--
-- Configuring incomplete, errors occurred!

**Comment by yiakwy** [comment]
@ilovezfs  nvida error, once I used boost 1.63:

   1 NVCC src/caffe/layers/absval_layer.cu
   2 NVCC src/caffe/layers/base_data_layer.cu
   3 NVCC src/caffe/layers/batch_norm_layer.cu
   4 NVCC src/caffe/layers/batch_reindex_layer.cu
   5 NVCC src/caffe/layers/bias_layer.cu
   6 NVCC src/caffe/layers/bnll_layer.cu
   7 NVCC src/caffe/layers/concat_layer.cu
   8 NVCC src/caffe/layers/contrastive_loss_layer.cu
   9 /usr/local/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp(27): error: expected a ";"

**Comment by ilovezfs** [comment]
I meant with regular boost. I assume you were getting the exact same error.

**Comment by ilovezfs** [comment]
```
==> cmake . -DBoost_PYTHON_LIBRARY_RELEASE=/usr/local/opt/boost-python157/lib/libboost_python-mt.dylib -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE
==> make install
Last 15 lines from /Users/wangyi/Library/Logs/Homebrew/caffe/02.make:
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_bnll_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/util/cuda_compile_1_generated_math_functions.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_norm_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_batch_reindex_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_absval_layer.cu.o] Error 1
make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_base_data_layer.cu.o] Error 1
nvcc fatal   : Unsupported gpu architecture 'compute_60'
CMake Error at cuda_compile_1_generated_concat_layer.cu.o.Release.cmake:222 (message):
  Error generating
  /tmp/caffe-20170116-96390-aaao5w/caffe-1.0.0-rc4/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/./cuda_compile_1_generated_concat_layer.cu.o


make[2]: *** [src/caffe/CMakeFiles/cuda_compile_1.dir/layers/cuda_compile_1_generated_concat_layer.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```

OK so you're saying these errors are different from the errors 1.63 errors?

**Comment by ilovezfs** [comment]
Basically it sounds like it got farther along with boost 1.57, but it still fails anyway for a new reason.

**Comment by ilovezfs** [comment]
You should re-run the install and pass `-dv --build-from-source`

I think it will show that it got passed
```
1 NVCC src/caffe/layers/absval_layer.cu
2 NVCC src/caffe/layers/base_data_layer.cu
3 NVCC src/caffe/layers/batch_norm_layer.cu
4 NVCC src/caffe/layers/batch_reindex_layer.cu
5 NVCC src/caffe/layers/bias_layer.cu
6 NVCC src/caffe/layers/bnll_layer.cu
7 NVCC src/caffe/layers/concat_layer.cu
8 NVCC src/caffe/layers/contrastive_loss_layer.cu
9 /usr/local/include/boost/smart_ptr/detail/sp_counted_base_clang.hpp(27): error: expected a ";"
```
and then failed anyway farther along.

In any case, you seem very hung up on the keg only thing. It's easy to deal with. If you don't need boost 1.63.0, just
```
brew uninstall boost-python
brew uninstall boost
brew install boost157
brew install boost-python157
brew link -f boost157
brew link -f boost-python157
```

If you do also need boost 1.63.0, then you need to manually specify the boost157 paths to cmake:
```
Boost_ATOMIC_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_atomic-mt.dylib
// Boost atomic library (release)
Boost_ATOMIC_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_atomic-mt.dylib
// Boost chrono library (debug)
Boost_CHRONO_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_chrono-mt.dylib
// Boost chrono library (release)
Boost_CHRONO_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_chrono-mt.dylib
// Boost date_time library (debug)
Boost_DATE_TIME_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_date_time-mt.dylib
// Boost date_time library (release)
Boost_DATE_TIME_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_date_time-mt.dylib
// The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=Boost_DIR-NOTFOUND
// Boost filesystem library (debug)
Boost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_filesystem-mt.dylib
// Boost filesystem library (release)
Boost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_filesystem-mt.dylib
Boost_INCLUDE_DIR:PATH=/usr/local/opt/boost157/include
// Boost library directory DEBUG
Boost_LIBRARY_DIR_DEBUG:PATH=/usr/local/opt/boost157/lib
// Boost library directory RELEASE
Boost_LIBRARY_DIR_RELEASE:PATH=/usr/local/opt/boost157/lib
// Boost python library (debug)
Boost_PYTHON_LIBRARY_DEBUG:FILEPATH=Boost_PYTHON_LIBRARY_DEBUG-NOTFOUND
// Boost python library (release)
Boost_PYTHON_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost-python157/lib/libboost_python-mt.dylib
// Boost system library (debug)
Boost_SYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_system-mt.dylib
// Boost system library (release)
Boost_SYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_system-mt.dylib
// Boost thread library (debug)
Boost_THREAD_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_thread-mt.dylib
// Boost thread library (release)
Boost_THREAD_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_thread-mt.dylib
```

So you would pass to cmake the following:
```
-DBoost_ATOMIC_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_atomic-mt.dylib -DBoost_ATOMIC_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_atomic-mt.dylib -DBoost_CHRONO_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_chrono-mt.dylib -DBoost_CHRONO_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_chrono-mt.dylib -DBoost_DATE_TIME_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_date_time-mt.dylib -DBoost_DATE_TIME_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_date_time-mt.dylib -DBoost_DIR:PATH=Boost_DIR-NOTFOUND -DBoost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_filesystem-mt.dylib -DBoost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_filesystem-mt.dylib -DBoost_INCLUDE_DIR:PATH=/usr/local/opt/boost157/include -DBoost_LIBRARY_DIR_DEBUG:PATH=/usr/local/opt/boost157/lib -DBoost_LIBRARY_DIR_RELEASE:PATH=/usr/local/opt/boost157/lib -DBoost_PYTHON_LIBRARY_DEBUG:FILEPATH=Boost_PYTHON_LIBRARY_DEBUG-NOTFOUND -DBoost_PYTHON_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost-python157/lib/libboost_python-mt.dylib -DBoost_SYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_system-mt.dylib -DBoost_SYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_system-mt.dylib -DBoost_THREAD_LIBRARY_DEBUG:FILEPATH=/usr/local/opt/boost157/lib/libboost_thread-mt.dylib -DBoost_THREAD_LIBRARY_RELEASE:FILEPATH=/usr/local/opt/boost157/lib/libboost_thread-mt.dylib
```

**Comment by ilovezfs** [comment]
It looks like the new error is also fixable: https://github.com/arrayfire/arrayfire/issues/1535

**Comment by ilovezfs** [comment]
>CUDA : Yes (ver. 7.0)

So you just need the new CUDA, and it should work either with the formula or with the way I described above.

**Comment by yiakwy** [comment]
Love you so much! You are so kind to help on my questions. I have updated my comments and will try what you said again!

**Comment by yiakwy** [comment]
The reason why I use CUDA 7.0 is that my mac version is 10.10.5. NVIDA said that 7.0 is compatible with my macos

**Comment by ilovezfs** [comment]
@yiakwy hopefully CUDA >= 8.0RC will work properly with your hardware.

**Comment by yiakwy** [comment]
Summary:

boost 1.57 + macOS 10.12 + CUDA 8.0 + xcode 7.3 tool chain works

```
[----------] Global test environment tear-down
[==========] 2361 tests from 309 test cases ran. (954635 ms total)
[  PASSED  ] 2361 tests.
```

**Comment by ilovezfs** [comment]
Hurray!
