### ISSUE TITLE
Speex 1.2

### ISSUE THREAD

**Issue by PhenomRetroShare** [Homebrew/homebrew-core#8366]
Hello
Since speex is in version 1.2, it is separated in two project speex and speexdsp.
https://git.xiph.org/?p=speexdsp.git;a=summary
Could you add a formula for speexdsp?
http://downloads.us.xiph.org/releases/speex/speexdsp-1.2rc3.tar.gz

**Comment by ilovezfs** [comment]
I believe @nijikon was working on vendoring speexdsp into the speex formula

**Comment by nijikon** [comment]
Yup, we are building `speexdsp` for `freeswitch` as a resource. Do you explicit need `speexdsp`?

**Comment by nijikon** [comment]
xiph/speexdsp#9

**Comment by MarioG-X** [comment]
I also need speexdsp for freeswitch asap, install is failing on all macOS's with speex 1.2.0 update. Glad I found this comment section and thank you in advance!

**Comment by ilovezfs** [comment]
It was already added to freeswitch.

**Comment by nijikon** [comment]
@MarioG-X as @ilovezfs said, with recent `freeswitch` update to `1.6.13` it is compiled with `speexdsp`.

**Comment by MarioG-X** [comment]
I am testing both 1.6.13 and master starting from scratch with a clean /usr/local. Both fail due to missing speexdsp in ./configure.

**Comment by nijikon** [comment]
Are you building freeswitch by yourself?

**Comment by MarioG-X** [comment]
I wrote and maintain the freeswitch macOS wiki pages: https://freeswitch.org/confluence/display/FREESWITCH/macOS+Installation+and+Testing
I am using test that method about once a month to maintain the wiki. It works fine until speex 1.20. If you start with a clean local and use brew, speexdsp is missing. The freeswitch ./configure has a test for speex.

**Comment by PhenomRetroShare** [comment]
I need it without freeswitch.
And if you can manage it as pacman do for linux:
[speexdsp files](https://www.archlinux.org/packages/extra/x86_64/speexdsp/files/)

**Comment by MarioG-X** [comment]
We just need a homebrew for speexdsp so as to keep the freeswitch prerequisites install consistent. Getting to install one of the prerequisites different from the rest is not good. Thanks to all for this work!

**Comment by MarioG-X** [comment]
Thanks so much for the very fast fix!
