### ISSUE TITLE
Paraview --with-mpi failed to build on 10.12

### ISSUE THREAD

**Issue by ninjascientist** [Homebrew/homebrew-core#8380]
### Bug reports:

gist link at https://gist.github.com/anonymous/b06e8082d2f2f09014c723396662f1db

The Mac was recently formatted from a fresh state. I wouldn't expect any interference from outside of the homebrew environment to it.

**Comment by ilovezfs** [comment]
The formula is part of homebrew/science. Please re-open this here: https://github.com/Homebrew/homebrew-science/issues
