### ISSUE TITLE
Unable to install emacs --HEAD: makeinfo version error

### ISSUE THREAD

**Issue by CSRaghunandan** [Homebrew/homebrew-core#8384]
The latest version of emacs on master needs `makeinfo` version > 4.13, but macOS ships with `makeinfo` version 4.8 by default. So, I installed `texinfo` using homebrew and symlinked makeinfo to `/usr/local/bin`. But, even after doing that, emacs installation fails yelling that it requires makeinfo version > 4.13.

Do I need to symlink the latest `makeinfo` to `/usr/bin` instead? But I'd have to login in recovery mode and disable the security check. I'd rather not risk it.

How to tell homebrew install of emacs --HEAD to look for makeinfo in `/usr/local/bin` ? I even tried adding an alias for makeinfo to point to the new version, but even that didn't work.

**Comment by MikeMcQuaid** [comment]
> Do I need to symlink the latest makeinfo to /usr/bin instead? But I'd have to login in recovery mode and disable the security check. I'd rather not risk it.

No, don't do that.

> How to tell homebrew install of emacs --HEAD to look for makeinfo in /usr/local/bin ?

Sorry, we don't support HEAD builds in this way. You're better to contact upstream or not use HEAD if you're unable to resolve the build errors.

**Comment by CSRaghunandan** [comment]
> Sorry, we don't support HEAD builds in this way. You're better to contact upstream or not use HEAD if you're unable to resolve the build errors.

Okay, i'll revert to using stable releases 👍 
but, i've question, how will change effect future emacs builds? like when emacs 26 hits stable, will I encounter the same problem??

**Comment by MikeMcQuaid** [comment]
No, we'll fix Emacs before it's updated.

**Comment by ilovezfs** [comment]
It may only affect builds from Git anyway.
