### ISSUE TITLE
Why does 'reinstall <package>' trigger update of other packages?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [Homebrew/homebrew-core#83893]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I call this a bug.

I issued `brew reinstall <package>`, and before I knew it, a bunch of other packages began to be updated.  What is going on here?  Can we limit the scope to the <package> I want to update not update my whole system!
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

See above

### What happened (include all command output)?

About 30 other packages were `upgraded`.

### What did you expect to happen?

<package> to be reinstalled AND NOTHING ELSE!

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew reinstall <package>`
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/FAQ#why-does-brew-upgrade-formula-also-upgrade-a-bunch-of-other-stuff this applies to all install operations too.

**Comment by Napoleon-BlownApart** [comment]
This needs to be made more transparent up-front so the user understands what will be impacted.

**Comment by SMillerDev** [comment]
I'd be happy to review a pull request that does something to that extend, but with Homebrew being an evergreen package manager this is implied.
