### ISSUE TITLE
u-boot-tools mkimage segmentation fault

### ISSUE THREAD

**Issue by eproxus** [Homebrew/homebrew-core#83938]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.2.9-37-g7d3f073
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7d3f073e9d21ad6170d5cb433df1bdd1bb008e02
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6f01a00aa5f8f06ec9202fc9290921ed98ed52df
Core tap last commit: 31 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
$ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Create an image with u-boot-tools.

### What happened (include all command output)?

The `mkimage` command crashed with a segmentation fault:

```
$ mkimage -A arm -O linux -T kernel -a 0x80200000 -e 0x80200000 -n RTEMS -d beam.gz beam.zImage
Segmentation fault: 11
```

When running under the Fish shell:
```
$ mkimage -A arm -O linux -T kernel -a 0x80200000 -e 0x80200000 -n RTEMS -d beam.gz beam.zImage
fish: Job 1, 'mkimage -A arm -O linux -T ke...' terminated by signal SIGSEGV (Address boundary error)
```

### What did you expect to happen?

It would complete successfully and create an image.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install u-boot-tools
$ mkimage -A arm -O linux -T kernel -a 0x80200000 -e 0x80200000 -n RTEMS -d beam.gz beam.zImage
```

(Example file: [beam.gz](https://github.com/Homebrew/homebrew-core/files/7045465/beam.gz))

I also tried installing `u-boot-tools` from source, but that results in the same error. Others have had this problem as well: https://marc.info/?l=u-boot&m=158212926509589&w=2

**Comment by SMillerDev** [comment]
> I also tried installing u-boot-tools from source, but that results in the same error. Others have had this problem as well: https://marc.info/?l=u-boot&m=158212926509589&w=2

So it's an upstream bug then, please report it there

**Comment by eproxus** [comment]
Can confirm it is an upstream issue, just recompiled from source. Same issue with the Homebrew version and latest `master`.
