### ISSUE TITLE
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected ..

### ISSUE THREAD

**Issue by halfcrazy** [Homebrew/homebrew-core#8427]
With the latest 8db35ee26ecab3c6cac83243ecc956e5efb6c483.
Got the following error.

Error: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected ..
../Formula/qt5.rb
  ^
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: unknown regexp options - qt
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt:1: syntax error, unexpected tINTEGER, expecting end-of-input
../Formula/qt5.rb
              ^
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:25:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:42:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:97:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:214:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:84:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:208:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:255:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:286:in `from_keg'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:269:in `from_rack'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1406:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `map'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1404:in `installed'
/usr/local/Homebrew/Library/Homebrew/diagnostic.rb:891:in `check_missing_deps'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:43:in `block in doctor'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:35:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'

**Comment by mistydemeo** [comment]
Is `/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/qt` a symlink on your system?

**Comment by halfcrazy** [comment]
It's not
`ll /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/`
![](https://ww1.sinaimg.cn/large/006y8lVagw1fbdhp8wxvdj30ly04y76d.jpg)

**Comment by halfcrazy** [comment]
@mistydemeo Got it. Due to i set symlinks=false in my .gitconfig
