### ISSUE TITLE
[qemu] hvf accelerator is not enabled on Apple Silicon

### ISSUE THREAD

**Issue by ismail** [Homebrew/homebrew-core#84271]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew logs are not relevant to the bug.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to get HypervisorFramework support to work with qemu on Apple Silicon.

### What happened (include all command output)?

; qemu-system-aarch64 -accel help
Accelerators supported in QEMU binary:
tcg

### What did you expect to happen?

I expected "hvf" in the output as well.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
; qemu-system-aarch64 -accel hvf -M virt
qemu-system-aarch64: -accel hvf: invalid accelerator hvf
```

**Comment by SMillerDev** [comment]
https://github.com/Homebrew/homebrew-core/blob/cb72443db006e846d618411cc96d6465f5fb03e6/Formula/qemu.rb

We're not disabling it so you should report this upstream since it's simply not being build.
