### ISSUE TITLE
unable to install opencv3 with java on macOS 10.12.2

### ISSUE THREAD

**Issue by october10th** [Homebrew/homebrew-core#8429]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

I ran:

``brew tap homebrew/science``

``brew install opencv3 --HEAD --with-contrib --with-java``

provided in: http://opencv-java-tutorials.readthedocs.io/en/latest/01-installing-opencv-for-java.html

and got:

```
[ 29%] Built target opencv_imgproc
make: *** [all] Error 2
```
gist link:
https://gist.github.com/october10th/20d4f31ab17169fc5da5a6f234d2a89e

However,

removing the ``--with-contrib``:

``brew tap homebrew/science``

``brew install opencv3 --HEAD --with-java``

does not generate such error.

**Comment by MikeMcQuaid** [comment]
> brew tap homebrew/science

Report this to homebrew/science (as noted by the failure output).

**Comment by BVijayKrishna** [comment]
Secure:local nisum$ brew install opencv3 --HEAD --with-java
Error: No head is defined for opencv

Getting this error
