### ISSUE TITLE
Can't build emacs --HEAD

### ISSUE THREAD

**Issue by agzam** [Homebrew/homebrew-core#8430]
`brew install emacs --HEAD` failing with the following error:

`
configure: error: You do not seem to have makeinfo >= 4.13, and your
source tree does not seem to have pre-built manuals in the 'info' directory.
`

I have brew-installed texinfo, even tried force link it (although it's keg-only formula), now 

`makeinfo --version` shows: `texi2any (GNU texinfo) 6.3`

I've tried removing Xcode and Xcode devtools and reinstalling them again - it didn't help.

However if I clone it manually from `git://git.savannah.gnu.org/emacs.git`, configure and build - it builds. 
So, something must have changed that broke the formula. Can someone take a look please?
ver. 25.1 of Emacs still builds (without --HEAD flag), but I'm afraid if they merge their changes then the stable would break as well

**Comment by catesandrew** [comment]
same problem here. tried installing `texinfo` to get latest makeinfo v6.3 and still not working because its not picking up brew makeinfo (even forced linked).

**Comment by d12frosted** [comment]
The same here 😸

**Comment by agzam** [comment]
Oooh, wow! Already? Nice! Thank you everyone!
