### ISSUE TITLE
`clangd` (in the `llvm` package) reliably crashes with bottle installed on Linux

### ISSUE THREAD

**Issue by chandlerc** [Homebrew/homebrew-core#84365]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.10-25-g2cc3d3e
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2cc3d3e02253632c51f6f0ded24fec10999d2b31
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: f9757b60d674e1eda864940c1b49ddf430e4fafd
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 48
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 48-core 64-bit skylake
Clang: 12.0.1 build (parse error)
Git: 2.33.0.259 => /bin/git
Curl: 7.74.0 => /usr/bin/curl
Kernel: Linux 5.10.40 x86_64 GNU/Linux
OS: Debian GNU/Linux
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
/usr/bin/ruby: 2.7.4
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

The Linux bottle of `clangd` reliably crashes when you run it on Debian Testing machines (and at least some other ones, but not 100% of them somehow).

The crash is one that was filed against `clangd` some time ago: https://github.com/clangd/clangd/issues/800

It is hard to reproduce because it depends on the exact host compiler used to build ClangD. Most host compilers "work" just fine, but the specific version of GCC used to build the Linuxbrew casks exhibits the bug.

The bug is actually a source code bug in ClangD, not a compiler bug. It's just "fine" with almost all compilers. =[

This used to work fine because the LLVM formula required the GCC formula. This, in turn, used the Homebrew version of GCC rather than the system version of GCC. And the Homebrew version happens to not exhibit this bug! When we "fixed" the LLVM formula to not rely on the Homebrew installed GCC, it "broke" ClangD. =[

So, there are two options. Mostly filing this issue to find out which option folks would prefer. One, I'm confident in implementing. The other I think I can figure out, maybe.

1) We can add the GCC requirement back. This will make installing LLVM much slower, but will ensure the cask is built in a working form.
2) We can backport the patch to ClangD here: https://github.com/llvm/llvm-project/commit/ec1fb9533305e9bd69294ede7e5e7d9befbb2225

It doesn't look like there will be a point release with this patch, so it'd have to live in Homebrew. It is super simple, but I also understand general reluctance with this kind of backporting.

Thoughts? Suggestions?

### What happened (include all command output)?

As in the ClangD issue, running `clangd` crashes:

```
<modules_folder>/SLED12-x86_64/clang/12.0.0/bin/clangd --check=<working_folder>/sample.cc --log=verbose
I[20:50:19.544] clangd version 12.0.0
I[20:50:19.545] PID: 16358
I[20:50:19.545] Working directory: <working_folder>
I[20:50:19.545] argv[0]: <modules_folder>/SLED12-x86_64/clang/12.0.0/bin/clangd
I[20:50:19.545] argv[1]: --check=<working_folder>/sample.cc
I[20:50:19.545] argv[2]: --log=verbose
V[20:50:19.545] User config file is <home_folder>/.config/clangd/config.yaml
I[20:50:19.545] Entering check mode (no LSP server)
I[20:50:19.545] Testing on source file <working_folder>/sample.cc
I[20:50:19.545] Loading compilation database...
#0 0x000000000053e1ce llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (<modules_folder>/SLED12-x86_64/clang/12.0.0/bin/clangd+0x53e1ce)
#1 0x000000000053c24a llvm::sys::RunSignalHandlers() (<modules_folder>/SLED12-x86_64/clang/12.0.0/bin/clangd+0x53c24a)
#2 0x000000000053c38c SignalHandler(int) (<modules_folder>/SLED12-x86_64/clang/12.0.0/bin/clangd+0x53c38c)
#3 0x00007fb8f3106ba0 __restore_rt (/lib64/libpthread.so.0+0x11ba0)
#4 0x0000000003489ad8 
Segmentation fault (core dumped)
```

### What did you expect to happen?

For `clangd` to run correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install llvm` followed by `clangd ...`
```

**Comment by jonchang** [comment]
> We can backport the patch to ClangD here: llvm/llvm-project@ec1fb95

The patch seems minimal and (probably?) straightforward to apply. I'm in favor of this one until we migrate our bottlers to ubuntu 18.04.

**Comment by jonchang** [comment]
If it cleanly applies you could probably just add it to so we can have just one build that fixes a few Linux issues https://github.com/Homebrew/homebrew-core/pull/84364 ?
