### ISSUE TITLE
Tomcat Brew replaces its whole directory and removes configuration files

### ISSUE THREAD

**Issue by knyttl** [Homebrew/homebrew-core#84392]
### Provide a detailed description of the proposed feature

Every time tomcat is upgraded with brew, its directory is completely replaced, eg.

`/usr/local/Cellar/tomcat@9/9.0.50` -> `/usr/local/Cellar/tomcat@9/9.0.52`

This also means its configuration files in `libexec/conf/*` are completely deleted and any tools linking to this directory looses track of its binary.

Would it be possible to:

1. Remove the specific version from the directory structure
2. Prevent replacing the configuration files

### What is the motivation for the feature?

This slows down development as anytime the tomcat is upgraded, we need to fix the conf files and fix the path to tomcat.

### How will the feature be relevant to at least 90% of Homebrew users?

I think this must be relevant to anyone using tomcat, I can confirm we have this issue for everyone in the office.

### What alternatives to the feature have been considered?

No idea.

**Comment by carlocab** [comment]
The formula needs to be modified to install its config files in `etc`. Can you open a PR for that? Even one that isn't fully working is fine; we're happy to help you work out the details.

**Comment by knyttl** [comment]
I am not very skilled with tomcat configuration, but it seems, it cannot easily be configured to use /etc. It is hardcoded to use `$CATALINA_BASE/conf/context.xml` and the $CATALINA_BASE in naturally the root directory. I can only imagine symlinking this to /etc/, but I am not sure it is a good idea.

Also, this only addresses point 1 and does not solve the point 1 in the issue. 

What do you think?

**Comment by carlocab** [comment]
Symlinking is fine. Let's move those files into `pkgetc` (this evaluates to `$HOMEBREW_PREFIX/etc/tomcat@9`) and then create symlinks to where tomcat expects them.

See `opensearch` for an example.

**Comment by knyttl** [comment]
Will try. 

How can I address the point 1 of the issue?

**Comment by knyttl** [comment]
Hi,

I tried. 

https://github.com/Homebrew/homebrew-core/pull/84591

It seems it doesn't do any errors with audits and tests... But it does not do anything. I tried to replicate what is done in openseearch, but hey – I am really lost in this :/

**Comment by carlocab** [comment]
Thanks for opening that; it looks like a good start.

As for:

> How can I address the point 1 of the issue?

There is no way to do this that doesn't involve rewriting large parts of Homebrew, unfortunately. This is a key part of how Homebrew organises installed formula. What other issues does this cause aside from the config files becoming overwritten on upgrades?

Note, however, that you always have a stable symlink at `/usr/local/opt/tomcat` which won't change with versions.

**Comment by knyttl** [comment]
> What other issues does this cause aside from the config files becoming overwritten on upgrades?

The problem we are experiencing is this within IntelliJIdea:)

<img width="984" alt="Screenshot 2021-09-03 at 12 29 17" src="https://user-images.githubusercontent.com/401107/131991399-73caa74b-5511-44f7-9ed1-f8f5b654ce40.png">

Whenever we update, this gets broken.

> There is no way to do this that doesn't involve rewriting large parts of Homebrew, unfortunately. This is a key part of how Homebrew organises installed formula. 

What about a symlink to `/current` directory, eg.

```
tomcat@9
+ 9.0.50
+ 9.0.52
+ current -> 9.0.52
```

Brew would just need to symlink the last version to `/current` on update.

> Note, however, that you always have a stable symlink at /usr/local/opt/tomcat which won't change with versions.

This seems to be just link to the binary, which seems to be not enough for IntelliJ Idea.

**Comment by SMillerDev** [comment]
> This seems to be just link to the binary, which seems to be not enough for IntelliJ Idea.

That doesn't seem right, did you try using `/usr/local/opt/tomcat@9/libexec`?

**Comment by knyttl** [comment]
> /usr/local/opt/tomcat@9/libexec

Ah! YOU ARE RIGHT! Sorry and thanks!

**Comment by carlocab** [comment]
Fixed in #84656.
