### ISSUE TITLE
Add bash_completion to rclone

### ISSUE THREAD

**Issue by notDavid** [Homebrew/homebrew-core#8444]
Is adding bash_completion for rclone as simple as generating [this script](http://rclone.org/commands/rclone_genautocomplete/) and adding it to /usr/local/etc/bash_completion.d/rclone ?

**Comment by woodruffw** [comment]
Yes, although you should consider adding that to the formula itself!

**Comment by MikeMcQuaid** [comment]
> Yes, although you should consider adding that to the formula itself!

Agreed! Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by notDavid** [comment]
Okay will do.. does this look okay?

```
system bin/"rclone", "genautocomplete", "rclone_bash_completion"
bash_completion.install "rclone_bash_completion" => "rclone"
```
