### ISSUE TITLE
"brew install doxygen --with-qt5" fails

### ISSUE THREAD

**Issue by rickrankin** [Homebrew/homebrew-core#8446]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
When I did a `brew upgrade` today, homebrew tried and failed to update doxygen. doxygen was originally installed with the `--with-llvm`, `--with-graphviz` and `--with-qt5`. If I leave off the `--with-qt5` option, it installs fine, but then I don't have the doxywizard command available. 

Here are the [logs](https://gist.github.com/3606171aae3835d2f409956a611a06db) generated by `brew gist-logs doxygen`.

Based on what I saw in the logs, the issue appears to be related to qt5 and C++11 support. When I get the opportunity, I'll try building doxygen from the original source, but I'm not sure when I'll be able to get to that.

I see that there's another qt5 related issue (#8392). It's possible that the issue I'm seeing is related, but I won't know for certain until I try to build from the original source. 

Output from `brew config`:
```
HOMEBREW_VERSION: 1.1.5-128-g824768e26
ORIGIN: https://github.com/Homebrew/brew
HEAD: 824768e26ff34a63c0ff809b500c2f3910b982ed
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 65263b975a43a2d065844735ee06ee46258f7007
Core tap last commit: 60 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_112
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

**Comment by ilovezfs** [comment]
This affects CLT-only systems and is fixed by https://github.com/Homebrew/homebrew-core/pull/8521.
