### ISSUE TITLE
Brew install specific php patch version?

### ISSUE THREAD

**Issue by abunch** [Homebrew/homebrew-core#84617]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Brew lists the current stable version of php@7.4 as 7.4.23:
https://formulae.brew.sh/formula/php@7.4


I need 7.4.19 to match a development/production environment, so how do I go about installing a specific patch version of php 7.4?
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I need 7.4.19 to match a development/production environment, so how do I go about installing a specific patch version of php 7.4?

### What happened (include all command output)?

Trying to install php@7.4.19 I get the following:
Warning: No available formula or cask with the name "php@7.4.19". Did you mean php@7.4?

### What did you expect to happen?

I expected 7.4.19 to be installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See above.
```

**Comment by SMillerDev** [comment]
That's not something brew supports, brew doesn't work like composer in that you can pick any version.

**Comment by carlocab** [comment]
You can try maintaining a formula of the version you need in your own tap. See `brew help extract` for details.

Here are some other docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/
