### ISSUE TITLE
libimobiledevice --HEAD install fails

### ISSUE THREAD

**Issue by jmpolom** [Homebrew/homebrew-core#84699]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 265c8c36a4c0a74f478cba16417940b3b588736c
Last commit: 5 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c2a2a9782abc3b39e5bc70d3bfeaffdaba73148d
Core tap last commit: 3 weeks ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 12.0.0 build 1200
Git: 2.32.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A
```

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install libimobiledevice --HEAD` to install the latest available version of libimobiledevice.

### What happened (include all command output)?

```
==> Cloning https://git.libimobiledevice.org/libimobiledevice.git
Updating /Users/staceybulko/Library/Caches/Homebrew/libimobiledevice--git
fatal: unable to access 'https://git.libimobiledevice.org/libimobiledevice.git/': SSL certificate problem: certificate has expired
Error: Failed to download resource "libimobiledevice"
Failure while executing; `git fetch origin` exited with 128. Here's the output:
fatal: unable to access 'https://git.libimobiledevice.org/libimobiledevice.git/': SSL certificate problem: certificate has expired
```

### What did you expect to happen?

libimobiledevice installs successfully, as it did for me on another system a few weeks ago.

It appears upstream has moved to use github.com as the primary repository as opposed to their own (c?)git server. The certificate expired on 27 August 2021 and has not been renewed. The formula for libimobiledevice should be updated to use `https://github.com/libimobiledevice/libimobiledevice.git` as the repository instead.

The most recent commit in `libimobiledevice` actually contains a new check in the build process for `libimobiledevice-glue` which doesn't have a homebrew formula yet. This should also be created.

I created a [`libimobiledevice` issue](https://github.com/libimobiledevice/libimobiledevice/issues/1211) for this as well.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install libimobiledevice --HEAD`
```

**Comment by jonchang** [comment]
We don't support HEAD installs.

**Comment by carlocab** [comment]
Source builds are unsupported, so that includes head installs.

You're welcome to make pull requests to fix this, however.
