### ISSUE TITLE
GMP crashes with Monterey beta-6, causing emacs and other dependencies to crash too.

### ISSUE THREAD

**Issue by domschl** [Homebrew/homebrew-core#84719]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.10-64-gfd46a17
ORIGIN: https://github.com/Homebrew/brew
HEAD: fd46a173fef7a60bd7da5032f2fcde3c0ea0d1c2
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: cef1a1da4cb83902923cb03bbc1c2545d9b0d1fe
Core tap last commit: 81 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.33.0 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0-arm64
CLT: 13.0.0.0.1.1628499445
Xcode: 13.0 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false


NOTE: I have uninstalled GMP from brew since it crashes, and replaced it with local version. Hence the doctor-complains.
brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libgmp.10.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/gmp.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libgmp.la

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/gmp.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libgmp.a

Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.


Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install gmp

Run `brew missing` for more details.

NOTE: I've removed brew's gmp and replaced it with a local version from bmp HEAD to able to work.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

After installation of beta-6, a number of GNU-related programms started crashing, e.g. all versions of Emacs.

Cause was gmp. For some reason, gmp's self-tests and many useage-scenarios cause crashes with Monterey Beta-6

I've uninstalled brew brew GMP (after trying different compilers and from-source compiles of gmp 6.2.1 without improvement.)
Using latest GMP from HEAD fixes the issue

### What happened (include all command output)?

With brew's gmp & emacs:

emacs

Fatal error 11: Segmentation fault
Backtrace:
0   emacs-27.2                          0x0000000100e4b658 emacs_backtrace + 164
1   emacs-27.2                          0x0000000100efcffc terminate_due_to_signal + 140
2   emacs-27.2                          0x0000000100e4c6c0 deliver_thread_signal + 0
3   emacs-27.2                          0x0000000100e4c73c init_bignum + 0
4   emacs-27.2                          0x0000000100e4b3b0 maybe_fatal_sig + 0
5   libsystem_platform.dylib            0x00000001bcbac4e4 _sigtramp + 56
6   libhogweed.6.4.dylib                0x00000001018970c0 _nettle_ecc_mod_random + 208
7   libhogweed.6.4.dylib                0x0000000101897d3c nettle_ecdsa_generate_keypair + 140
zsh: killed     emacs

### What did you expect to happen?

No GMP caused-crash.

Currently seems to require usage of unreleased gmp HEAD version, so it's an upstream problem triggered by some changes with the latest beta.

This is a FYI, not expecting a fix.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Get latest Monterey beta
Install anything that uses gmp (e.g. emacs)
-> crash.

Also self-tests of gmp now consistently fail when installing gmp from source with: `brew install -s gmp`

Solution: use latest (unreleased) HEAD of gmp repository.
```

**Comment by domschl** [comment]
I've made an upstream report to the GMP project.

**Comment by dlenski** [comment]
Among other affected dependent applications: GnuTLS, and through it OpenConnect (the multi-VPN client!)

I'm one of the OpenConnect developers, and we got a report about [TLS connections immediately crashing on recently-updated M1 Macs, which was traced to this](https://gitlab.com/openconnect/openconnect/-/issues/313#note_678834669). :-)
