### ISSUE TITLE
Deprecate git-flow and use git-flow-avh instead

### ISSUE THREAD

**Issue by Anahkiasen** [Homebrew/homebrew-core#8471]
This is not a bug per se and I'm not entirely sure this is the correct repository so bear with me. Currently when you do `brew install git-flow` it'll install [this version](https://github.com/nvie/gitflow) which has been abandonned for more than 4 years, the correct version (ie. what most people actually mean to install) is located under the [git-flow-avh](https://github.com/petervanderdoes/gitflow-avh) formula.

Now most people do not know this nor notice it, there is no warning or anything. This issue is to open a discussion in favor (or not) of removing the old `git-flow` formula and rename the `git-flow-avh` formula in its place. 

Again, I'm not sure if there's ever been a similar situation in Homebrew and what the correct procedure is. The contributing guidelines do not mention deprecated formulas and considering the old repository is abandoned there is little hope for an issue opened there to have any effect.

cc @petervanderdoes

**Comment by MikeMcQuaid** [comment]
If you can convince nvie to officially deprecate https://github.com/nvie/gitflow and point to `git-flow-avh` then we'll consider it. Otherwise, we're going to fall back to the relative upstream names.

**Comment by Anahkiasen** [comment]
I understand, I sent an email to nvie, will see what he thinks
