### ISSUE TITLE
Declare link flags directly to kegs, not to `/usr/local/lib` in pkg-config `.pc` files to avoid conflicts.

### ISSUE THREAD

**Issue by golddranks** [Homebrew/homebrew-core#8472]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Formula Requests:

This is not a request about a specific formula, but about the the general way of building them: the formulas install `.pc` files that `pkg-config` is able to read. However, the link flags stored by these files point are sometimes defined like this: `Libs: -L/usr/local/lib -lpq` (example: libpq). That is, they point to the dir `/usr/local/lib`. When passing the link directory to compilers, it would be better to pass the keg dir; in this case `/usr/local/Cellar/postgresql/9.6.1/lib/`. Why? Because in some cases passing `/usr/local/lib` would cause conflicts when trying to build something installed through Homebrew and system libraries in the same build – a library in `/usr/local/lib` ends up conflicting with a system library.

Curiously, part of the formulas link directly to the keg dir. (For example, libpng does this). I think this would be a valuable thing as a general guideline.

**Comment by ilovezfs** [comment]
I don't think we should blindly rewrite/fixup/whatever `.pc` files. If there's an issue with a specific formula's pc files, we could look into that, though.

**Comment by golddranks** [comment]
In that case, what do you think about this? From formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/postgresql.rb

    $ cat /usr/local/lib/pkgconfig/libpq.pc
    Name: libpq
    ...
    Cflags: -I/usr/local/Cellar/postgresql/9.6.1/include
    Libs: -L/usr/local/lib -lpq
    Libs.private: -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -lssl -lcrypto -lgssapi_krb5 -lldap_r

I'm not too familiar with the formula files, so it's not immediately obvious why it generates the row `Libs: -L/usr/local/lib -lpq` instead of /Libs: -L/usr/local/Cellar/postgresql/9.6.1/lib/`, but the row `--libdir=#{HOMEBREW_PREFIX}/lib` looks suspicious to me in the `postgresql.rb`. What do you think?

**Comment by DomT4** [comment]
Off the top of my head, pretty sure it's explicitly `HOMEBREW_PREFIX/lib` here because that's where `postgresql` plugins are dumped under Homebrew, so `postgresql` needs to know to look there rather than inside the Cellar for everything. Could be wrong though 🤷‍♂️.

**Comment by golddranks** [comment]
So, I checked out my installed packages that had a `.pc` file (N=110). The overwhelming majority of them pointed to the `Cellar` path, which is great. It was only postgresql, sdl and sdl2 that pointed to `/usr/local/lib`. So, it seems that I jumped to the conclusions too fast; most of the link flags are correct, and it's just a few packages that could have them set up better.

**Comment by golddranks** [comment]
So, the remaining task is to check whether it's possible to fix the prefixes of those packages without breaking anything. If what @DomT4 said is true, it might be hard, though.

**Comment by MikeMcQuaid** [comment]
Actually we should perhaps make these all point to `/usr/local/opt/$FORMULA/lib` instead of the Cellar. Agreed with @DomT4 that there will be a few cases where we deliberately install e.g. plugins into `$HOMEBREW_PREFIX/lib`. This fix would probably best be made in Homebrew/brew so we can detect an installed `.pc` file and rewrite it rather than doing it in every formula.

**Comment by golddranks** [comment]
@MikeMcQuaid Thanks for your assessment. Is there going to be any work towards that goal / any milestones assigned?

**Comment by MikeMcQuaid** [comment]
@golddranks There's no work currently planned.

**Comment by golddranks** [comment]
What I can do to help this issue to progress? Or do you prefer for the idea to sit still for awhile and mature?

**Comment by MikeMcQuaid** [comment]
Someone will need to make a pull-request for this in Homebrew/brew but I don't think it's going to be done by any maintainers in the near future, sorry. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Also, just for future reference, an issue like this may make more sense on Homebrew/brew (but I appreciate when you created it you thought it might just be a matter of fixing up formulae).

Thanks!
