### ISSUE TITLE
PPSSPP should use its own bundled ffmpeg

### ISSUE THREAD

**Issue by vit9696** [Homebrew/homebrew-core#84737]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Unrelated
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to play games (namely Valkyria Chronicles II) with PPSSPP and used a brew-provided version of PPSSPP.

### What happened (include all command output)?

All the videos either stuttered or were unplayable: showed black screen soon after the first frame. There are multiple error messages in the logs like the following:

```
59:14:295 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1384 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
00:23:691 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2107): already stopped
00:30:271 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2109): already stopped
00:49:131 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2111): already stopped
00:52:142 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1384 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
00:52:243 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1384 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
01:26:443 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2144): already stopped
01:31:434 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2146): already stopped
01:48:812 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2148): already stopped
01:51:797 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1384 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
01:51:896 Odin_Main    E[ME]: HLE/sceMpeg.cpp:1384 UNIMPL sceMpegAvcDecodeFlush(08d571f0)
02:04:811 Odin_Main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2352 800201a2=sceKernelTerminateThread(2181): already stopped
```

### What did you expect to happen?

I expected the videos to play normally, because I expected brew to use the ffmpeg package bundled within PPSSPP repository. PPSSPP includes a rather [heavily modified ffmpeg version](https://github.com/hrydgard/ppsspp-ffmpeg), so you cannot just use the system/upstream one. I recompiled PPSSPP manually with its own ffmpeg and this worked perfectly. Fortunately their ffmpeg is static.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Open Valkyria Chronicles II in PPSSPP.
2. Let the intro video play.
3. It will stutter quite a lot.
```

**Comment by alebcay** [comment]
Just for additional background (for other maintainers/readers), the described issue is tracked upstream at https://github.com/hrydgard/ppsspp/issues/11490.

It sounds like the issue should have been addressed upstream (at least in some situations) by https://github.com/hrydgard/ppsspp/pull/14188, which should already be included in this version of `ppsspp`. As is often the case, upstream also seems reluctant to fully support/fix this issue for non-patched `ffmpeg` installations, for various reasons described in the upstream issue.

**Comment by unknownbrackets** [comment]
Some points of clarification:

1. hrydgard/ppsspp#14188 is not included in the latest stable release, v1.11.3.  It's included in the latest git, which is probably not the version that was used here.
2. FFmpeg has removed/changed functionality that we relied upon in the latest versions.  hrydgard/ppsspp#14188 includes a workaround, but it will exhibit bugs for games that attempt to render videos in certain ways (I don't currently know of any specific games that do this, but I can and have written a test PSP app that does it.)
3. The version of FFmpeg we bundle is by no means heavily modified; it's simply FFmpeg 3.0.2.  That repo also has some build scripts for cut down binaries and some committed binaries.
4. We include the binaries of FFmpeg mainly to make PPSSPP easier to build on Windows (it would require msys2 and many steps someone perfectly capable of installing Visual Studio and clicking Run would get scared away by.)

I know package managers always think people are "reluctant" to support the latest APIs because it takes work, but keep in mind that 1400+ PSP games were released and they were all written against Sony APIs for video decoding.  Emulation means simulating *those* APIs, not rewriting the game logic and video looping to use new APIs.

Since the new FFmpeg APIs don't support the features we need to simulate Sony's video API, we're likely to remain reluctant for some time.  Probably the end result will eventually be, unfortunately, reinventing the wheel on video decoding and writing our own (maybe copying parts of FFmpeg.)

I get that people shouldn't be writing software to decode video the ways FFmpeg no longer supports.  Unfortunately, no one has been able to jump in a time machine and successfully convince Sony and PSP game developers of this.  I don't anticipate this changing, so I wouldn't recommend holding your breath for our "reluctance" to end - unless you've got a time machine to change how PSP games were written.

-[Unknown]

**Comment by alebcay** [comment]
Hi @vit9696, PPSSPP 1.1.3_1 is now available via Homebrew with the changes from #84738.

**Comment by vit9696** [comment]
Yes, thank you for taking your time on that. I will find some time to make PPSSPP release in binary.

**Comment by vit9696** [comment]
Posted in https://github.com/hrydgard/ppsspp/pull/14839.

**Comment by vit9696** [comment]
With https://github.com/hrydgard/ppsspp/pull/14839 merged we should get official PPSSPP releases as of 1.12.0. CC @alebcay, @Gcenx.

- Can you confirm that the uploaded binaries in the artifacts section work fine on your machines? E.g. from here: https://github.com/hrydgard/ppsspp/runs/3639392538.
- Shall we rename `ppsspp` from brew to some other name to instead use a cask?

**Comment by vit9696** [comment]
@alebcay @Gcenx, from now on PPSSPP provides [official binary releases](https://github.com/hrydgard/ppsspp/releases/latest) for macOS. What should our route be to include PPSSPP in Homebrew Cask? I see the following options:

1. We remove `ppsspp` formula and create `ppsspp` cask as a replacement.
2. We rename `ppsspp` formula to `ppsspp-cli` and add `ppsspp` cask.
3. We add `ppsspp-app` cask.

My personal preference is route (2), but I am not sure of the general Homebrew policy here.

**Comment by unknownbrackets** [comment]
> Off topic but the minimum target should really be 10.9 when using -stdlib=libc++

Used to be 10.7, which was the minimum for libc++.  We only upped to 10.8 as of last year.  I don't think we've heard any complaints from people using 10.8 or people who were using 10.7 before that (that said, macOS is eclipsed by Android and Windows in usage, by far... it's not impossible that the few people still on 10.8 haven't said anything.)

-[Unknown]

**Comment by vit9696** [comment]
Actually this is not compatible with 10.8, but not due to libc++.

```
Date/Time:       2021-10-13 00:06:13.923 +0000
OS Version:      Mac OS X 10.8.5 (12F2560)
Report Version:  10

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_CAMetalLayer
  Referenced from: /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 in /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
```

```
Date/Time:       2021-10-13 03:08:08.835 +0300
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  ABB5B1A7-0D4F-75FB-BA5B-C94051C63886

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_CAMetalLayer
  Referenced from: /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 in /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
```

```
Date/Time:             2021-10-13 03:09:52.434 +0300
OS Version:            Mac OS X 10.10.5 (14F2511)
Report Version:        11
Anonymous UUID:        4C4D268E-45EF-BDE5-4440-BFDA3F7D9A72

Dyld Error Message:
  Symbol not found: _OBJC_CLASS_$_CAMetalLayer
  Referenced from: /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
 in /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
```

```
Date/Time:             2021-10-13 01:11:11.106 +0100
OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        BE6B860F-08FB-8D00-B45A-8D31959E34BE

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Expected in: /usr/lib/libSystem.B.dylib
```

```
Date/Time:             2021-10-12 17:13:32.135 -0700
OS Version:            Mac OS X 10.12.6 (16G2136)
Report Version:        12
Anonymous UUID:        D7F251E8-F25B-F3F1-FC4A-C8C64D011EC3

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Users/USER/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL
  Expected in: /usr/lib/libSystem.B.dylib
```

10.13 shows a warning:  `You can’t use this version of the application “PPSSPPSDL” with this version of macOS. You have macOS 10.13.6. The application requires macOS 10.15 or later.` Running from terminal crashes:
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/user/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/user/Desktop/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

10.14 shows a warning:  `You can’t use this version of the application “PPSSPPSDL” with this version of macOS. You have macOS 10.14.6. The application requires macOS 10.15 or later.`. Running from terminal works fine.
