### ISSUE TITLE
[Regression] Problem with gitk in git-gui 2.33.0: diff of staged changes not displayed

### ISSUE THREAD

**Issue by janusw** [Homebrew/homebrew-core#84755]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config                                           

HOMEBREW_VERSION: 3.2.10-66-gbe96bfd
ORIGIN: https://github.com/Homebrew/brew
HEAD: be96bfdfb7396e2038702a4d49368d6605818d8d
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0780f1df9fdbd8914ff50ac24eb0ec0d3561c1b7
Core tap last commit: 34 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.VtBZDtCsEg/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.0.22.9
Xcode: 12.5.1
XQuartz: 2.7.11 => /opt/X11


% brew doctor          

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  proj@7
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Open gitk on a folder with a local checkout of a git repo. Make some changes in the repo. Stage the corresponding files for commit via `git add`. Look at the staged changes with gitk.

### What happened (include all command output)?

gitk shows which files have been changed, but it does not show the actual diff. Below `Local changes checked in to index but not committed` everything is empty.

Note that committed changes are displayed properly, and also unstaged modifications. Only staged changes seem to be affected by this bug.

Additional note: Switching from "Diff" to "Old version" or "New version" does not help. They are all empty.

I'm pretty sure this was working well with previous git-gui version, but I'm not sure exactly when it broke (must have been rather recently).

### What did you expect to happen?

I expect to see a full diff of the staged changes, just like for the case of committed or unstaged changes.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install git-gui
cd /folder/with/git_repo
vi some_versioned_file
# edit and save the file
git add some_versioned_file
gitk &
```

**Comment by carlocab** [comment]
Is this a problem with only Homebrew gitk, or does it affect gitk installed by any other means as well? If it's the latter (and I suspect it is), then this needs to be reported upstream, since they'll be the ones who know how to fix this.

**Comment by janusw** [comment]
I just tried version 2.33.0 from https://sourceforge.net/projects/git-osx-installer/, and that indeed has the same problem. So, yeah, probably an upstream issue ...

**Comment by carlocab** [comment]
Please report this upstream. Thanks!
