### ISSUE TITLE
Gtags is not effective for go language

### ISSUE THREAD

**Issue by jWhisper** [Homebrew/homebrew-core#84864]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84f4fbf3cf5e83d33de0b28b2658fcb50aaa761e
Last commit: 33 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6dbd64a4b5bca87e9837fed2d9144d15ef967d65
Core tap last commit: 71 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-arm64
CLT: 12.5.0.22.9
Xcode: 12.5
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to use Gtags for go.

1. brew install global

>:
Warning: global 6.6.7_1 is already installed and up-to-date.
To reinstall 6.6.7_1, run:

### What happened (include all command output)?

2.create a simple main.go； and run “gtags --explain --gtagslabel=native-pygments  ."
> - File 'go.mod' is handled as follows:
	suffix:   |.mod|
	language: |Modula2|
	parser:   |parser|
	library:  |/opt/homebrew/Cellar/global/6.6.7_1/lib/gtags/pygments-parser.la|
 - File 'GTAGS' is skipped because it is a tag file.
 - File 'GRTAGS' is skipped because it is a tag file.
 - File 'main.go' is handled as follows:
	suffix:   |.go|
	language: |Go|
	parser:   |parser|
	library:  |/opt/homebrew/Cellar/global/6.6.7_1/lib/gtags/pygments-parser.la|
 - File 'GPATH' is skipped because it is a tag file.

3. run "global -x main"
> nothing...

### What did you expect to happen?

global -x main
main                1 main.go          package main
main                5 main.go          func main() {

NOTE: is effective for python, but not go

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1，brew install global
2，create a simple main.go； and run “gtags --explain --gtagslabel=native-pygments --gtagsconf=/opt/homebrew/etc/gtags.conf ."
3，then, run "global -x main"; it return nothing.
```

**Comment by carlocab** [comment]
Is this a problem just with Homebrew global, or can you reproduce it with global installed through any other means?

**Comment by jWhisper** [comment]
> Is this a problem just with Homebrew global, or can you reproduce it with global installed through any other means?

it work with global installed from source on debain

**Comment by carlocab** [comment]
Does it work with a non-Homebrew global on macOS, though? It's possible this feature just doesn't work on macOS. Another possibility is that the formula is missing some build flags.
