### ISSUE TITLE
private formulas needing SSH git access don't work

### ISSUE THREAD

**Issue by joscha** [Homebrew/homebrew-core#8501]
I am trying to create a formula off a private repository, looking like this:

```ruby
class Sde < Formula
  desc "SDE"
  homepage "https://github.com/Canva/sde"
  head "git@github.com:Canva/sde.git"
  def install
    bin.install "sde" => "bin/sde"
  end
end
```

unfortunately, homebrew does not like to clone this, as it thinks its a URL, so it results in the error:
```
==> Downloading git@github.com:Canva/sde.git
Error: bad URI(is not URI?): git@github.com:Canva/sde.git
```

however adding `git://` (`git://git@github.com:Canva/sde.git`) to tell homebrew it is indeed a git endpoint won't work either, because then the URL pattern is not valid any more:
```
==> Cloning git://git@github.com:Canva/sde.git
Cloning into '/Users/joscha/Library/Caches/Homebrew/sde--git'...
fatal: Unable to look up git@github.com:Canva (port 9418) (nodename nor servname provided, or not known)
Error: Failed to download resource "sde"
Failure while executing: git clone --depth 1 --branch master git://git@github.com:Canva/sde.git /Users/joscha/Library/Caches/Homebrew/sde--git
```

Changing it to `git+ssh://` and adapting the URL pattern: `git+ssh://git@github.com/Canva/sde.git` works fine on the command line, but brew exits via
```
==> Downloading git+ssh://git@github.com/Canva/sde.git
curl: (1) Protocol "git+ssh" not supported or disabled in libcurl
Error: Failed to download resource "sde"
Download failed: git+ssh://git@github.com/Canva/sde.git
```

as it thinks `git+ssh://` is a normal non-git URI again.

Is there any way that I am overlooking to make this work?

**Comment by joscha** [comment]
```
url "git@github.com:Canva/sde.git", :using => :git
```

seems to work.

**Comment by dbousamra** [comment]
What about url's to private Github release artifacts. We publish artifacts to github releases, but we have no way of using them in a formula.

**Comment by joscha** [comment]
> What about url's to private Github release artifacts. We publish artifacts to github releases, but we have no way of using them in a formula.

The releases are not available via `git://` - to fetch them you'd need to be authenticated via HTTP against `github.com`. Not very straightforward, given that this has to run from CMD - we ended up publishing our artifacts to an S3 bucket.

**Comment by MikeMcQuaid** [comment]
You can both use https://github.com/Homebrew/brew/pull/1763/files to do what you want.

**Comment by dbousamra** [comment]
Great. Thanks

**Comment by MikeMcQuaid** [comment]
Note this was mentioned in https://brew.sh/2017/05/01/homebrew-1.2.0/ and in our release notes. It's worth checking them out.
