### ISSUE TITLE
Wrong version of FPC on M1 (Intel instead of ARM)

### ISSUE THREAD

**Issue by viking1304** [Homebrew/homebrew-core#85037]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
❯ brew config
HOMEBREW_VERSION: 3.2.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 84f4fbf3cf5e83d33de0b28b2658fcb50aaa761e
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 96b79c0e3776caa530fc2b3fde57f5c8b5479f0c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: /opt/homebrew/bin/code
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.33.0 => /opt/homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-arm64
CLT: 12.5.1.0.1.1623191612
Xcode: 12.5.1
Rosetta 2: false

❯ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed brew on my M1 without Rosetta2 and I wanted to install proper FPC package for my architecture.

### What happened (include all command output)?

Package installs without any problem, but it's Intel version.

```
Free Pascal Compiler version 3.2.2 [2021/06/03] for x86_64
```

### What did you expect to happen?

I expected to get multiarch version that works natively on M1:
https://sourceforge.net/projects/freepascal/files/Mac%20OS%20X/3.2.2/fpc-3.2.2.intelarm64-macosx.dmg/download

```
Free Pascal Compiler version 3.2.2 [2021/05/16] for aarch64
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
❯ brew install fpc
```

**Comment by alebcay** [comment]
Hi @viking1304, `fpc` 3.2.2_1 is now available via Homebrew, which should have native binaries built for Apple Silicon. Could you please update/upgrade and verify that the new version Homebrew ships no longer has the issue described here? Thanks!

**Comment by viking1304** [comment]
This looks fine.

```
❯ brew install fpc
==> Downloading https://ghcr.io/v2/homebrew/core/fpc/manifests/3.2.2_1
Already downloaded: /Users/viking/Library/Caches/Homebrew/downloads/31ae70adf219741bcfe041aaf9a67b25e4cc1f00c9c2855d54104b6fb930a3aa--fpc-3.2.2_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/fpc/blobs/sha256:b4efbb9f568afadfb27aab8ca80895b7f306f58c7ff8a0623f2bd8
Already downloaded: /Users/viking/Library/Caches/Homebrew/downloads/404c4f9d70663debe01ea989fb00a902fa74071d1c44d4dd07cc01e7ba87c56c--fpc--3.2.2_1.arm64_big_sur.bottle.tar.gz
==> Pouring fpc--3.2.2_1.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/fpc/3.2.2_1: 3,977 files, 371.3MB

❯ which fpc
/opt/homebrew/bin/fpc

❯ file /opt/homebrew/bin/fpc
/opt/homebrew/bin/fpc: Mach-O 64-bit executable arm64

❯ fpc -h | grep 'Compiler version'
Free Pascal Compiler version 3.2.2 [2021/09/11] for aarch64

❯ brew uninstall fpc
Uninstalling /opt/homebrew/Cellar/fpc/3.2.2_1... (3,977 files, 371.3MB)
```

Only possible issue would be if someone actually needs multiarch binary.

Multiarch FPC test:

```
❯ fpc -h | grep 'Compiler version'
Free Pascal Compiler version 3.2.2 [2021/05/16] for aarch64
❯ arch -x86_64 zsh
❯ fpc -h | grep 'Compiler version'
Free Pascal Compiler version 3.2.2 [2021/05/16] for x86_64
```

Brew test:

```
❯ fpc -h | grep 'Compiler version'
Free Pascal Compiler version 3.2.2 [2021/09/11] for aarch64
❯ arch -x86_64 zsh
❯ fpc -h | grep 'Compiler version'
Free Pascal Compiler version 3.2.2 [2021/09/11] for aarch64
```

Multiarch binaries would work for both platforms and it would be possible to use intel version on ARM if needed. But that is something that maintainers should decide.

**Comment by carlocab** [comment]
Great; glad it's sorted.

Regarding multiarch binaries: we purposefully don't ship these, as historically doing so caused us lots of problems.
