### ISSUE TITLE
Bring back older versions of cabal-install

### ISSUE THREAD

**Issue by ivanperez-keera** [Homebrew/homebrew-core#85133]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

The tool cabal-install has frequently introduced breaking changes over the last few versions. Version 3.6, the only one that the brew formula installs, was published just 24 days ago (see https://github.com/haskell/cabal/blob/master/release-notes/cabal-install-3.6.0.0.md).

By upgrading this formula always to the latest version, the setup becomes difficult to follow for users and application developers alike, who need to constantly update instructions on their applications, and tools on the client machines, to keep Haskell applications usable.

Please either provide also older versions of cabal-install, or just do not upgrade until a much longer time has passed since the publication of a new version.

Pinging @carlocab for awareness.

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install cabal-install 3.4, the version of cabal-install, which is the version of cabal install released 1y ago.

### What happened (include all command output)?

cabal-install 3.6 was installed instead.

### What did you expect to happen?

To be able to install cabal-install 3.4

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install cabal-install
```

**Comment by SMillerDev** [comment]
If upstream provides long-term support for the old version you can make a versioned formula, otherwise you're just out of luck.

See <https://docs.brew.sh/Versions>

**Comment by ivanperez-keera** [comment]
There are several versions of GHC being simultaneously supported.

For example, GHC 8.10, which comes bundled with cabal 3.2, saw a release less than 3 weeks ago (https://www.haskell.org/ghc/download_ghc_8_10_7.html). I know GHC is a different package, and there's Cabal and cabal-install, but it's all related.

On the other hand, this is a tool that has just been released.  I've been programming in Haskell for 20 years and this new version of cabal-install gave an error message with zero clue to what's going on. IMO this is not ready to be used yet.

It would be much better to bring it back to 3.4 and sit on it until before new updates are pushed. And probably the same for compiler versions. There's no emergency that needs 3.6.

If people need the very latest version of these tools, then I think we absolutely need versioned formulas. But I doubt lack of latest versions of cabal or GHC is affecting as many people, or as much, than upgrading so much and so quickly.

**Comment by ivanperez-keera** [comment]
@SMillerDev I've spent the whole afternoon hitting bug after bug in cabal-install 3.6. As I explained, I think it's been pushed very prematurely.

It would really be much better to revert ea6b141083b5fc618d963df53a1b01f5bc5d5db0 for now.

I've tried contacting the person who wrote that commit, and the person who approved it, but got no response.

**Comment by carlocab** [comment]
We ship whatever upstream ships. If upstream have released a broken version, please take it up with them. In particular, we don't wait to update formulae to newer versions just because we think the newer version is broken. The only exception here is if a new version is explicitly labelled alpha/beta/experimental/etc.

We're happy to update formulae to fixed versions of these as soon as there are new releases. We can also backport patches when they're accepted upstream.

**Comment by ivanperez-keera** [comment]
Thanks for taking the time to respond.

I think at least some regular delay in introducing new versions would really help (e.g., 2 months since the release of a new "stable" version X.Y.Z when either X or Y have increased). I would not ask you to check if it's buggy, and just do it as a general rule (perhaps use versioned formulas specifically for this purpose).

I'll ask them to mark them as release candidates for clarity, but I doubt they will.

**Comment by SMillerDev** [comment]
> I think at least some regular delay in introducing new versions would really help (e.g., 2 months since the release of a new "stable" version X.Y.Z when either X or Y have increased).

That's really not feasible. The better way is to have upstream test their releases better. It shouldn't, and will never be, up to brew to determine when a release is ready.

**Comment by MikeMcQuaid** [comment]
The other things that can cause us to not upgrade that you could help with/contribute to:
- an improved `test do` block for `cabal-install` that runs it and performs a decent test. if this fails: an upgrade won't be merged until it's fixed.
- an improved `test do` block for `cabal-install`'s non-`:build` dependants. If any of these fail: an upgrade won't be merged until it's fixed.
