### ISSUE TITLE
bmake is not latest version. Upstream update available: https://www.crufty.net/ftp/pub/sjg/bmake-20210808.tar.gz

### ISSUE THREAD

**Issue by stevej098** [Homebrew/homebrew-core#85149]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.11-133-g4a64d59
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 4a64d59141473acb5d65b980f8edb4fb381af177
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4a1c985d576379bab789b566de5200c8323861b6
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.TPD60eTZ0K/org.xquartz:0
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 11.0.0 build 1100
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.6-x86_64
CLT: 10.3.0.0.1.1562985497
Xcode: 11.3.1
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

run the latest version of bmake (20210808)

Why: Bug fixes / features

### What happened (include all command output)?

steve$ brew info bmake
bmake: stable 20200902 (bottled)
Portable version of NetBSD make(1)
http://www.crufty.net/help/sjg/bmake.html
/usr/local/Cellar/bmake/20200902 (88 files, 622.6KB) *

### What did you expect to happen?

the 2021 version to be there

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
steve$ brew info bmake
bmake: stable 20200902 (bottled)
Portable version of NetBSD make(1)
http://www.crufty.net/help/sjg/bmake.html
/usr/local/Cellar/bmake/20200902 (88 files, 622.6KB) *

see upstream
https://www.crufty.net/ftp/pub/sjg/

bmake-20210808.tar.gz
bmake-20210808.tar.gz.asc
bmake-20210808.tar.gz.md5
bmake-20210808.tar.gz.sha1
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew

**Comment by stevej098** [comment]
Thanks for the link on Updating formulas.

I spent quite sometime _looking_ for exactly that information.
You've got multiple lists for people to check - but never once mention Updates and certainly don't give any clues on
home page of brew.sh

You _should_ add this page across multiple of your instruction pages

**Comment by SMillerDev** [comment]
<https://brew.sh>, our homepage, links to further documentation at <https://docs.brew.sh> which contains a link in the first section "updating software in Homebrew" that I just send you. I don't think we can make it clearer than that.

**Comment by stevej098** [comment]
I opened that link.

There is ONE line containing "Update", it's not your link.

Homebrew Blog (news on major updates)

**Comment by SMillerDev** [comment]
It's further down then that, but it's definitely there.

**Comment by carlocab** [comment]
You could also search closed pull requests. AFAIK there have been several opened for `bmake` but each one failed to build. If you know how to fix it, please open a pull request.
