### ISSUE TITLE
vim 8.0.0142 did not build

### ISSUE THREAD

**Issue by jwilliams108** [Homebrew/homebrew-core#8519]
OS X 10.11.6, Xcode 8.2.1

vim 8.0.0142 build fails with: `fatal error: 'os_unix.pro' file not found`

https://gist.github.com/7e37885b67571a89d7176704a2610f69

macvim 8.0-120 is also affected by the same issue.

https://gist.github.com/6f469652d07be3ada8c0283fa8565be7

**Comment by ilovezfs** [comment]
Hi @jwilliams108 I can't seem to reproduce the issue. Do you mind trying with a dummy user account?

**Comment by jwilliams108** [comment]
Very interesting, I was able to successfully update using a different user account on that machine. I'll try to sort out the configuration difference to see why my main user can't do it - any thoughts on the culprit?

**Comment by ilovezfs** [comment]
I'd try moving your .bash_profile/.bashrc/etc. out of the way

**Comment by jwilliams108** [comment]
OK thanks, I'll try to sort out what changes I've made recently. Appreciate the help!

**Comment by ilovezfs** [comment]
You're welcome :)

**Comment by jwilliams108** [comment]
Just in case this helps anyone, I tracked the problem down to setting the HOMEBREW_TEMP environment variable. Once I unset it, everything compiled correctly.

I had it set like so:

`export HOMEBREW_TEMP=/usr/local/Cellar/temp`

As I have my Cellar and Homebrew directories on separate ZFS mounts, and it complains about the temp directory not being on the same mount if I don't set it. I've also had it set like this for months, and this is the first time it's caused a problem (including previous compiles of MacVim and Vim).

**Comment by ilovezfs** [comment]
@jwilliams108 Very interesting. There's probably a way to reproduce that in the vim build system outside of Homebrew too if you feel like chasing it.

>and it complains about the temp directory not being on the same mount if I don't set it

I assume you mean brew doctor?

**Comment by jwilliams108** [comment]
Yes, the warning is when I run brew doctor - perhaps it's not something to worry too much about.

**Comment by ilovezfs** [comment]
@jwilliams108 yeah that's one to ignore for sure if it's not actively causing a problem you can put your finger on.
