### ISSUE TITLE
Hyperkit Fails to Connect to VPNKit with Failed Assertion 

### ISSUE THREAD

**Issue by dshick-nydig** [Homebrew/homebrew-core#85232]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a, package installs fine
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run the homebrew installed version of hyperkit (through minikube) using VPNKit built from master.

### What happened (include all command output)?

```
Assertion failed: (sizeof(VERSION_SHA1) == sizeof(init_msg.commit) + 1), function vpnkit_connect, file src/lib/pci_virtio_net_vpnkit.c, line 324.
```

https://github.com/moby/hyperkit/blob/b54460a1b41b487262d03c9685ae8b50dbc6607a/src/lib/pci_virtio_net_vpnkit.c#L323-L325

I suspect that [this line of the makefile](https://github.com/moby/hyperkit/blob/b54460a1b41b487262d03c9685ae8b50dbc6607a/Makefile#L2) is not working correctly as the release tarball is not a valid git repository, causing [CFLAGS to be set improperly](https://github.com/moby/hyperkit/blob/b54460a1b41b487262d03c9685ae8b50dbc6607a/Makefile#L142). Perhaps

### What did you expect to happen?

I expected for this assertion not to fail. Perhaps the makefile needs to be amended to include a default VERSION_SHA1.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# install minikube and hyperkit
brew install minikube hyperkit

# build vpnkit
brew install autoconf automake dylibbundler libtool opam pkg-config wget
git clone https://github.com/moby/vpnkit.git && cd vpnkit
make -f Makefile.darwin ocaml
make -f Makefile.darwin depends
make -f Makefile.darwin build
make -f Makefile.darwin artefacts

# run vpnkit and minikube with hyperkit
./vpnkit --ethernet /tmp/ethernet
minikube start --uuid 00000000-0000-0000-0000-000000000001 --driver=hyperkit --hyperkit-vpnkit-sock /tmp/ethernet --alsologtostderr
```

**Comment by dshick-nydig** [comment]
Raised an issue with upstream. Hopefully the error can be patched for now and fixed permanently there.

**Comment by dshick-nydig** [comment]
Adding the following is a quick workaround to get this building, but hardcoding a git hash is probably not the best approach as it would have to be updated manually with every release.

```
args << "GIT_VERSION_SHA1=\"b54460a1b41b487262d03c9685ae8b50dbc6607a\""
```

**Comment by dshick-nydig** [comment]
not stale

**Comment by SMillerDev** [comment]
It's definitely stale, nobody is working on it upstream or in Homebrew.

**Comment by carlocab** [comment]
To clarify: we don't keep issues open just because they still affect someone. We only keep issues open when someone is actively working on them.

This way issues that someone can do something about aren't buried under the ones that nobody can/will. I am closing this the next time @github-actions adds the stale label.
