### ISSUE TITLE
abcde fails with: DiscID.c: loadable library and perl binaries are mismatched

### ISSUE THREAD

**Issue by quistian** [Homebrew/homebrew-core#85403]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 48bbc53fb8bbdc7aaf5b8f2996081fea1f51ca4e
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ea3e820b79e2a86e7a02cbf7b8d1498a33979218
Core tap last commit: 71 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-arm64
CLT: 12.5.0.0.1.1617976050
Xcode: N/A
Rosetta 2: false
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was simply trying to rip a CD using abcde

### What happened (include all command output)?

 % abcde
disk4 was already unmounted or it has a partitioning scheme so use "diskutil unmountDisk" instead
DiscID.c: loadable library and perl binaries are mismatched (got handshake key 0xfd80080, needed 0xfb80080)
[ERROR] abcde: abcde-musicbrainz-tool failed to run; ABORT

### What did you expect to happen?

For the CD to be ripped

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install abcde
abcde
```

**Comment by carlocab** [comment]
Does `brew reinstall -s abcde` help?

**Comment by RichieB2B** [comment]
I just had the same problem and it was solved by `brew reinstall -s abcde`, thanks!
