### ISSUE TITLE
npm start - throw err; Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by hwbrill** [Homebrew/homebrew-core#8545]
I experienced a problem after an npm start on a cloned git repository… This is after I did a brew update, brew doctor before doing a brew upgrade in which it upgraded Node:

[2017-01-05 Issue.pdf](https://github.com/Homebrew/homebrew-core/files/688992/2017-01-05.Issue.pdf)

**Comment by hwbrill** [comment]
Checked permissions and ran:
'cd /usr/local && sudo chown -R $(whoami) bin etc include lib sbin share var Frameworks'
which resolved the issue.  But, upgrading the formula shouldn't have put me in this position...

**Comment by MikeMcQuaid** [comment]
> But, upgrading the formula shouldn't have put me in this position...

It didn't, something else messing with your permissions did 😉

**Comment by hwbrill** [comment]
I don't know about that @MikeMcQuaid ... but, you guys are more experienced about that...  It worked fine before the brew update, upgrade, cleanup...  I am getting better using the command line and knowing brew, npm, git etc...  This stuff is pretty neat!

**Comment by stonemirror** [comment]
I'll need to wait for this to happen again (and it seems to crop up every month or two), but doing a

```brew uninstall --ignore-dependencies --force npm```
```brew install npm```

seems to have fixed things for me this time around...

**Comment by JCount** [comment]
@stonemirror Please do not comment on dead, closed issues. If you are experiencing a problem, please open a new issue report and fill in the template.
