### ISSUE TITLE
nagios-plugins: missing tools because of required root privileges

### ISSUE THREAD

**Issue by muellermartin** [Homebrew/homebrew-core#8561]
The current formula for `nagios-plugins` is missing the tools `check_dhcp` and `check_icmp` which should be available according to [the developer's website](http://nagios-plugins.org/doc/man/index.html).
This is because these tools require root privileges to be installed and used via the SETUID bit and the install script skips installing these tools if the necessary privileges are not provided (see https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins-root/Makefile.am#L72).

**Comment by MikeMcQuaid** [comment]
We cannot build these with root privileges, sorry.

**Comment by muellermartin** [comment]
> We cannot build these with root privileges, sorry.

It seems you misunderstood the issue. I did not request to build it with root privileges, I just wanted to report the bug, because I just installed it for one of the missing tools just to find out it is missing without notice. I'm about to create a patch to try to make it install without root privileges (I guess sudo is then needed for those missing tools, but in my opionion that's okay).

If I do not succeed I suggest at least a Caveat text gets added to inform other users of this issue.

**Comment by MikeMcQuaid** [comment]
Ok, I just don't see anything actionable here for us because this is an intentional upstream decision. If this is something you can get them to accept a patch for then that would be best. I'd rather not add caveats for this as the only current reporter is someone who already knows what the caveats are saying :wink.

**Comment by muellermartin** [comment]
Of course this was an intentional decision, I doubt this wasn't added by chance. The DHCP tool uses ports < 1025 and the ICMP tool operates on RAW sockets which both require root privileges. Using SETUID (more portable) or `CAP_NET_ADMIN`, `CAP_NET_BIND_SERVICE`, `CAP_NET_RAW` (on Linux) is the logical consequence.

I don't work with Nagios but I guess having `nagios-plugins` marked as installed but missing the checking tools for DHCP and ICMP could lead to some strange monitoring results. Using ICMP for availability isn't an edge case I guess.

**Comment by muellermartin** [comment]
I was able to patch the Makefile so the missing binaries can be installed on macOS. The affected new tools then of course require root privileges (e.g. sudo) to run.
Here is the whole formula in case sb. needs it: https://github.com/muellermartin/homebrew-distill/blob/master/nagios-plugins.rb
