### ISSUE TITLE
problem with python@3.9

### ISSUE THREAD

**Issue by deltamikesierra** [Homebrew/homebrew-core#85689]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 3.2.13-29-g1f3de1d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1f3de1d5b28e8ab52d96c4341e97117e14095380
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 176aed448fd099669f296592463c5d6915702d47
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A

3. Don't if this links with a (non blocking) problem when executing python code with vscode :
Error processing line 1 of /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/protobuf-3.17.3-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

reinstalling python@3.9

because of a pb encountered whenever running python3 script from vscode :

Error processing line 1 of /usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/protobuf-3.17.3-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 562, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored

### What happened (include all command output)?

==> Reinstalling python@3.9
==> Pouring python@3.9--3.9.7.big_sur.bottle.tar.gz
Error: undefined method `exist?' for #<String:0x00007fd1fc4f1de0>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:315:in `specified_path'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:1177:in `pour'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:401:in `install'
/usr/local/Homebrew/Library/Homebrew/reinstall.rb:62:in `reinstall_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:119:in `block in reinstall'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:113:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/reinstall.rb:113:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'

### What did you expect to happen?

just reinstall python@3.9 (no pb with python@3.8)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew reinstall python
```

**Comment by paulgeringer** [comment]
tagging this one here since I missed this issue originally: https://github.com/Homebrew/brew/issues/12104
