### ISSUE TITLE
Error: php@7.4: Failed to download resource "unixodbc"

### ISSUE THREAD

**Issue by dalagnol** [Homebrew/homebrew-core#85986]
- [ ] your issue is with the https://formulae.brew.sh website and not the (generated) contents of a given formula/cask page.

## What you were trying to do (and why)
I was trying to install php at version 7.4 using the command below:
```brew install php@7.4```

## What happened (include screenshots)
The command executed normally until it tried to download **unixodbc**.  When it reached that section, it tried to access the URL " http://www.unixodbc.org/unixODBC-2.3.9.tar.gz" and failed 3 times before throwing an error.
<img width="682" alt="Screenshot 2021-09-26 at 2 11 44 PM" src="https://user-images.githubusercontent.com/49122688/134817299-da01df03-c9a7-48ae-a23d-521158325879.png">

I tried opening the same website and failed to reach it too.
<img width="1174" alt="Screenshot 2021-09-26 at 1 14 17 PM" src="https://user-images.githubusercontent.com/49122688/134815617-74320cb5-e79b-48c4-9a44-905209b1fe5c.png">
## What you expected to happen
I expected it to download php at the version I specified as it always does with other formulas. Being unable to reach unixodbc's website and not being able to find a single reported issue on this makes me wonder why is it happening. I was able to reproduce this error in other computers and there does not seem to be any explanation in sight.

Trying to compile PHP from source on a M1 mac was not straightforward, I had way more bugs and failed tests than my colleague on an Intel mac and differing outputs all around, so I really needed brew’s straightforward routines as I am on a deadline.

Which by the way, thank you so much for the work you all put into homebrew! It is a time saving must have and has always made my coding experience better.

The workaround I ended up doing is as follows, I found the download file for unixodbc version 2.3.9 on the following website: https://fossies.org/linux/privat/unixODBC-2.3.9.tar.gz/index_tp.html
I downloaded it and once I had that file, I redirected requests for unixodbc.org to a local server of mine pointing to that file, which brew then accepted and successfully finished installing the formula. 

So I guess the issue is not with the formula, rather with the unixodbc server that is down, but I would like to call attention to this since it might be blocking people from installing PHP with brew.

**Comment by SMillerDev** [comment]
> Trying to compile PHP from source on a M1 mac was not straightforward

Trying to compile anything locally isn't really what we're aiming to accomplish anymore in brew. Seeing your install location you're likely on a corporate machine though, so you should ask the IT department if they're not blocking anything.

---

Additionally, this issue tracker is for formulae.brew.sh, not for the software shipped by brew. That would be homebrew/homebrew-core.

**Comment by dalagnol** [comment]
> Yeah looks like they're having server issues. We have the ability to specify mirrors in the formula so we could add the Fossies mirror.

I think that would solve it. Is that something I should do locally while they fix their servers? I did look that up but did not find anything.

**Comment by dalagnol** [comment]
> > Trying to compile PHP from source on a M1 mac was not straightforward
> 
> Trying to compile anything locally isn't really what we're aiming to accomplish anymore in brew. Seeing your install location you're likely on a corporate machine though, so you should ask the IT department if they're not blocking anything.
> 
> Additionally, this issue tracker is for formulae.brew.sh, not for the software shipped by brew. That would be homebrew/homebrew-core.

Both me and colleague were on personal computers and different networks and can not reach unixodbc, so I believe firewalls are not the issue. I choose to keep brew under my user because I do share this machine sometimes.

I apologise for posting to the wrong place. @Bo98 has moved it though, so let me know if any further changes are needed.
