### ISSUE TITLE
wrong download url for apache versions older than 2.4.46

### ISSUE THREAD

**Issue by valentinkrynin** [Homebrew/homebrew-core#86191]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.14-18-g5cea834
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5cea834e82fdb1a06b808f73b391d05526167cb9
Last commit: 50 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9282fea89d013ca2be6ce11d63364f28e53a114c
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 12.5.0.22.9
Xcode: N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

**I'M TRYING TO:**
I'm trying to install older version of apache (httpd@2.4.37).

I made a tap for that version.
But after trying to install the package I see the "404 not found" error.

I figured out that download link "https://downloads.apache.org/httpd/httpd-2.4.37.tar.bz2" is no longer valid. 
The package was moved to archive "https://archive.apache.org/dist/httpd/httpd-2.4.37.tar.bz2".

**WHY:**
I have a server on Centos 8 that supports max 2.4.37 version of Apache.
I need that version of Apache installed local to reproduce my server behaviour on my Mac.

### What happened (include all command output)?

==> Downloading https://www.apache.org/dyn/closer.cgi?path=httpd/httpd-2.4.37.tar.bz2
==> Downloading from https://apache.volia.net/httpd/httpd-2.4.37.tar.bz2

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://downloads.apache.org/httpd/httpd-2.4.37.tar.bz2
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: httpd@2.4.37: Failed to download resource "httpd@2.4.37"
Download failed: https://downloads.apache.org/httpd/httpd-2.4.37.tar.bz2

### What did you expect to happen?

Success installation of httpd@2.4.37

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
TAP=$USER/homebrew-httpd_2_4_37
MODULE=httpd
VERS=2.4.37
brew tap-new $TAP
brew extract --version $VERS $MODULE $TAP
brew install $TAP/$MODULE@$VERS
```

**Comment by carlocab** [comment]
`brew extract` just pulls a formula from the repository log. If it contains mistaken information (e.g. wrong URLs), then there's nothing we can do about that without re-writing history (which will break everyone's clones of Homebrew/core). Adding functionality to `brew extract` that validates information is likely to be quite onerous.

Please adjust your formula accordingly instead.
