### ISSUE TITLE
syncthing should be niced

### ISSUE THREAD

**Issue by pdondl** [Homebrew/homebrew-core#8625]
Just a suggestion: since syncthing is a background process that sometimes can be somewhat cpu-hungry, it would be nice if there was the option to nice it upon start with launchctl.

**Comment by woodruffw** [comment]
We usually to minimize the amount of customization/configuration we ship with packages. Setting a default inside the plist we provide would probably lead to other complaining (rightfully) about performance problems.

You should be able to edit `syncthing`'s launchd plist to change the `nice` level, though. The syntax is [documented here](www.launchd.info/) (under "Nice").
