### ISSUE TITLE
llvm@3.8 fails to install .inc files

### ISSUE THREAD

**Issue by elliottslaughter** [Homebrew/homebrew-core#8626]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
         **Caveat:** I know I'm running a non-`/usr/local` prefix. I'm pretty sure that's not the issue.
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

# Bug report

The formula `llvm@3.8` fails to install `include` files with an extension of `.inc`.

```
$ ls /Users/elliott/.brew/Cellar/llvm\@3.8/3.8.1/lib/llvm-3.8/include/clang/Basic/*.inc
ls: /Users/elliott/.brew/Cellar/llvm@3.8/3.8.1/lib/llvm-3.8/include/clang/Basic/*.inc: No such file or directory
```

Compare this to the binary tarball from llvm.org:

```
$ curl -O http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz
$ tar xfJ clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz
$ ls clang+llvm-3.8.0-x86_64-apple-darwin/include/clang/Basic/*.inc
clang+llvm-3.8.0-x86_64-apple-darwin/include/clang/Basic/AttrHasAttributeImpl.inc
...
```

Because these files are missing in the Homebrew formula, it's impossible to build a project against this formula that requires the Clang headers.

By the way, the `llvm` formula does this correctly. But that's currently on LLVM 3.9 and I need 3.8.

Logs: https://gist.github.com/520099aa72444104116d39be62c9df46

**Comment by MikeMcQuaid** [comment]
We don't really accept feature request issues for formulae, particularly for older versions. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by ulrichgabor** [comment]
This is actually a regression of a [fix from 2012](https://github.com/Homebrew/legacy-homebrew/issues/14924).

Potential fix:
```
diff --git a/Formula/llvm@3.8.rb b/Formula/llvm@3.8.rb
index 7eccd66..96bbb01 100644
--- a/Formula/llvm@3.8.rb
+++ b/Formula/llvm@3.8.rb
@@ -134,6 +134,9 @@ class LlvmAT38 < Formula
     mktemp do
       system buildpath/"configure", *args
       system "make", "VERBOSE=1", "install"
+      cd "tools/clang" do
+        system "make install"
+      end
     end
 
     if MacOS.version <= :snow_leopard
```
`brew install --build-from-source`

Sorry, I have no time right now to prepare a proper pull request.
