### ISSUE TITLE
lesspipe v1.89 is broken for many file types

### ISSUE THREAD

**Issue by otandka** [Homebrew/homebrew-core#86335]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Adams src/lesspipe % brew config
HOMEBREW_VERSION: 3.2.14-51-g1909d89
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1909d89d003bdf1f34775faf81b8c0529729013f
Last commit: 18 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0b1f976b7e9064da805ea2c663306cda2b30e89d
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.s9khDEL5YP/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11

Adams src/lesspipe % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  gpg-agent
  apg

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libxerces-c-3.1.dylib

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gpg-agent
  unison

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> /Users/ota/.bash_profile

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install libyaml

Run `brew missing` for more details.

(I did not resolve these brew doctor warnings, in spite of the checkbox below.  I thought you would still want to know that one of your formulas is broken.)
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I discovered that lesspipe.sh v1.89 does not convert several common file types such as foo.gz and bar.xz.  I appears that lesspipe.sh was accidentally broken in an attempt to get some colorization feature to work.  However, v1.88 does work for me.

See for example the discussion in [lesspipe issue #55](https://github.com/wofr06/lesspipe/issues/55).

### What happened (include all command output)?

With the latest lesspipe formula installed less can't display an XZ compressed file.
```

Adams src/lesspipe % brew upgrade --dry-run lesspipe
Warning: lesspipe 1.89 already installed
Adams src/lesspipe % export LESSOPEN="|/usr/local/bin/lesspipe.sh %s"
Adams src/lesspipe % less /tmp/make.out.211001.xz | head -2
"/tmp/make.out.211001.xz" may be a binary file.  See it anyway? ^C

```

### What did you expect to happen?

Here is the behavior of lesspipe 1.88 downloaded from GitHub.

```
Adams src/lesspipe % git remote -v
origin	git@github.com:wofr06/lesspipe.git (fetch)
origin	git@github.com:wofr06/lesspipe.git (push)
Adams src/lesspipe % git log --oneline -n 4
b429098 (HEAD -> lesspipe, tag: 1.89) prioritzie bat over code2color
2ad7a65 restore colors of source code files
0c077bd html2text: Opensuse version uses different parameter to pass encoding
a8a7a33 (tag: 1.88) fix typo
Adams src/lesspipe % git reset 1.88 --hard
HEAD is now at a8a7a33 fix typo
Adams src/lesspipe % ./configure --yes > /dev/null
Adams src/lesspipe % export LESSOPEN="|/Users/ota/src/lesspipe/lesspipe.sh %s"
Adams src/lesspipe % less /tmp/make.out.211001.xz | head -2
cd ts/shark-config; ./bootstrap; /usr/bin/make clean; /usr/bin/make install; ./configure --gendefonly &&  \
             (/usr/bin/cpp -P def.mk.proto >def.mk)

```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Adams src/lesspipe % brew upgrade --dry-run lesspipe
Warning: lesspipe 1.89 already installed
Adams src/lesspipe % less /tmp/make.out.211001.xz | head -2
"/tmp/make.out.211001.xz" may be a binary file.  See it anyway? ^C
```

**Comment by SMillerDev** [comment]
So what you're saying is upstream released a buggy update? Because in that case the only solution is to send a patch upstream.

**Comment by otandka** [comment]
Yes, that is what I am saying.

I thought the custom was to open bugs with the software distributor, eg bugs.debian.org.  But if that isn't the case with homebrew, I can pursue it with them and just figure that homebrew will pick up the fix when it is ready upstream.

**Comment by carlocab** [comment]
Is 1.89 also broken when you build it from source outside of Homebrew? If so, please report this in the upstream repo. Thanks!

**Comment by otandka** [comment]
Yes, when I cloned the lesspipe repository, 'git reset 1.89 --hard' fails, but git reset 1.88 --hard' works.  I will follow up there.

**Comment by SMillerDev** [comment]
> I thought the custom was to open bugs with the software distributor, eg bugs.debian.org. 

Only if it's a distribution issue, but you've proven it's not.

**Comment by m040601** [comment]
>  Basic things like less'ing gz files do not work and show up as binary. 


I can confirm this also happens, in Archlinux, v1.89.

The same files open perfectly using

gzip /usr/bin/zcat
gzip /usr/bin/zgrep
gzip /usr/bin/zless

or

zstd /usr/bin/zstdcat
zstd /usr/bin/zstdgrep
zstd /usr/bin/zstdless

**Comment by otandka** [comment]
Update: I have engaged with lesspipe upstream, but the problem is not yet fixed.  Version 1.90, tagged recently does not address the problem completely.

**Comment by pimlottc** [comment]
Did the `file` shipped with macOS change recently?  It appears that lesspipe relies on the `-i` option for file in order to get the mime type of file being tested.  From the `file` manpage:

```
      -i, --mime
             Causes the file command to output mime type strings rather than the more traditional human readable ones.  Thus it
             may say ‘text/plain; charset=us-ascii’ rather than “ASCII text”.
```

However, on my macOS Big Sur 11.6.1, the options are different:

```
     -i      If the file is a regular file, do not classify its contents.

     -I, --mime
             Causes the file command to output mime type strings rather than the more traditional human readable ones.  Thus it may say `text/plain; charset=us-ascii' rather than ``ASCII text''.

```

This makes a big difference.  Expected output for e.g. a PDF file:

```
$ file -i foo.pdf
foo pdf: application/pdf; charset=binary
```

Actual output on my machine:

```
$ file -i foo.pdf
foo pdf: regular file
```

Not very helpful :/

**Comment by jwodder** [comment]
@pimlottc I believe macOS `find` has always had its `-i` option behave like that.  The manpage you're looking at is presumably for GNU `find`.

**Comment by pimlottc** [comment]
> @pimlottc I believe macOS `find` has always had its `-i` option behave like that. The manpage you're looking at is presumably for GNU `find`.

I'm talking about `file`, not `find`.  Both man pages quoted are BSD file (I don't think there is a GNU file).  You can see the options for upstream BSD file 5.39 here:

https://github.com/file/file/blob/87731415de945660b00f02207d8e9d986ef9b82e/src/file_opts.h#L45

I don't know if Apple's built-in `file` has changed, I can't find where their source is so far to be able to check.

**Comment by jwodder** [comment]
@pimlottc Right, I meant to say `file`, not `find`.  (I still have `find` on the brain from a thing I was working on earlier.)  Checking an old computer still running 10.8 (Mountain Lion), I see that even back then `file -i` and `file --mime` did different things.

**Comment by carlocab** [comment]
Another workaround here is for `lesspipe` to depend on `file-formula` so it can use the original BSD `file`. We'd need to help `lesspipe` help find our `file`, though, since `file-formula` is keg-only.

Apple does seem to have made their own modifications to `file`, though I haven't checked carefully. This should be the version packaged with 11.5: https://opensource.apple.com/source/file/file-80.40.2/

**Comment by pimlottc** [comment]
@jwodder You're right, it doesn't seem to be a recent change in macOS `file`

@carlocab I just found that myself, and the `-I` / `-i` option is the same going back at least to Yosemite 10.10: 
https://opensource.apple.com/source/file/file-46/file/src/file_opts.h.auto.html

**Comment by otandka** [comment]
Thanks all for the investigation.  I also noticed this problem with file -i, and proposed that lesspipe use --mime, which is already supported on all the Linux boxes I could find.  This change was accepted, but as you note, it wasn't the root cause.

This afternoon there was some progress upstream at wofr06 /
lesspipe and I hope for a fixed and tagged version soon.

**Comment by otandka** [comment]
[Lesspipe](https://github.com/wofr06/lesspipe) commit tagged 1.91 fixes the problems I was seeing viewing compressed files.  Looking forware to homebrew advancing to this version soon.

**Comment by carlocab** [comment]
You can do `brew bump-formula-pr --version=1.9.1 lesspipe` to open a PR that updates `lesspipe` to 1.9.1.

**Comment by otandka** [comment]
Thanks, I tried that.  Looks like you need lots of setup for it to actually run, tho.  This current issue, was my attempt to do this before...
