### ISSUE TITLE
varnishd vmod_path and vcl_path point to Cellar paths, not opt

### ISSUE THREAD

**Issue by mjpieters** [Homebrew/homebrew-core#86449]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.14-65-g373b0da
ORIGIN: https://github.com/Homebrew/brew
HEAD: 373b0da4d5844b9e041a6f757cc8624d85f5c2b0
Last commit: 32 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1ae77debf8b79f69e86421d265f3c737e12dd4a5
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.r6nGIT3gMN/org.xquartz:0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/local/Homebrew/Library/Homebrew/shims/shared/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.0
XQuartz: 2.8.1 => /opt/X11

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/mj/.local/bin/pre-commit-validate-config
  /Users/mj/.pyenv/shims/python2-config
  /Users/mj/.pyenv/shims/python3.8d-config
  /Users/mj/.pyenv/shims/python3.6m-config
  /Users/mj/.pyenv/shims/python3.7-config
  /Users/mj/.pyenv/shims/python2.7-config
  /Users/mj/.pyenv/shims/python3.10-config
  /Users/mj/.pyenv/shims/python3.7m-config
  /Users/mj/.pyenv/shims/python3.9-config
  /Users/mj/.pyenv/shims/python-config
  /Users/mj/.pyenv/shims/python3-config
  /Users/mj/.pyenv/shims/python3.6-config
  /Users/mj/.pyenv/shims/python3.8-config
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to be able to package and install varnish extension modules (VMODs) and configurations (VCL) without having to alter the default search path used by varnish.

Currently, you can't because varnishd is hardcoded to use Cellar paths instead.

`varnishd` is configured with `vmod_path` and `vcl_path` paths inside its versioned cask (`$(brew --cellar varnish)/<version>`) instead of `$(brew --prefix)`. This makes it impossible to package up a VMOD and have it installed in the right location for direct use.

The Varnish HTTP accelerator is extensible; [libralies called VMODs](https://varnish-cache.org/vmods/) can be used to extend its functionality. VMODs usually rely on Varnish support for autotools to configure where they are installed, and when you use VCL (the varnish configuration language), you can import a VMOD using a relative path, which is then resolved against the `vmod_path` configuration parameter.

E.g. the standard location for VMODs is set as the `vmoddir` variable, which `varnish.m4` defines as:

```m4
	dnl Define the VMOD directory for libtool
	vmoddir=$($PKG_CONFIG --define-variable=libdir=$libdir \
		--variable=vmoddir varnishapi)
	AC_SUBST([vmoddir])
```

You can introspect what the `varnishd` binary has that path configured to, by running `varnishd -x parameters

```
% varnishd -x parameter | grep vmod_path --after-context=4
.. _ref_param_vmod_path:

vmod_path
~~~~~~~~~
	* Default: /usr/local/Cellar/varnish/7.0.0/lib/varnish/vmods

Directory (or colon separated list of directories) where VMODs are to be found.
```

There is also a `vcl_path` variable:

```
% varnishd -x parameter | grep vcl_path --after-context=4
.. _ref_param_vcl_path:

vcl_path
~~~~~~~~
	* Default: /usr/local/Cellar/varnish/7.0.0/etc/varnish:/usr/local/Cellar/varnish/7.0.0/share/varnish/vcl

Directory (or colon separated list of directories) from which relative VCL filenames (vcl.load and include) are to be found.  By default Varnish searches VCL files in both the system configuration and shared data directories to allow packages to drop their VCL files in a standard location where relative includes would work.
```

Note that both variables reference `/usr/local/Cellar/varnish/7.0.0` here.

### What happened (include all command output)?

I wrote a formula for a Varnish VMOD we rely on, libvfp-brotli, see https://github.com/mjpieters/homebrew-tap/blob/master/libvfp-brotli.rb.

When using the straightforward VCL test to verify VMOD installation:

```rb
  test do
    testvcl = testpath/"vmod_brotli_test.vcl"
    testvcl.write <<~EOS
      vcl 4.1;
      backend default none;
      import brotli;
    EOS
    system "#{HOMEBREW_PREFIX}/sbin/varnishd",
      "-C", "-f", "#{testvcl}"
  end
```

the test fails:

```
Message from VCC-compiler:
Could not find VMOD brotli
('/tmp/test.vcl' Line 3 Pos 8)
import brotli;
-------######-

Running VCC-compiler failed, exited with 2
VCL compilation failed
```

The VMOD extension is fine; it is correctly symlinked into `$(brew --prefix)/lib/varnish/vmods`.

I can work around this by directing Varnish to use that path, explicitly:

```rb
  test do
    testvcl = testpath/"vmod_brotli_test.vcl"
    testvcl.write <<~EOS
      vcl 4.1;
      backend default none;
      import brotli;
    EOS
    system "#{HOMEBREW_PREFIX}/sbin/varnishd",
      "-p", "vmod_path=#{lib}/varnish/vmods",
      "-C", "-f", "#{testvcl}"
  end
```

This is what my formula uses right now.

However, this doesn't solve this problem for end-users that use, say, the Varnish formula service.

### What did you expect to happen?

The test should pass, because `$(brew --prefix)/lib/varnish/vmods` is the *default location for vmods*.

The module should be usable out of the box when using the varnish service.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install varnish
$(brew --prefix)/sbin/varnishd -x parameter | grep Cellar
```

The `grep Cellar` filter should not produce output.
```

**Comment by mjpieters** [comment]
Note that not only should the `varnishd` binary have the right paths, so should the `varnish.m4` autoconf macros, `vmoddir`, `vcldir`, `pkgvcldir` and `vmod_*_vlcdir`.

**Comment by SMillerDev** [comment]
It doesn't look like we're doing anything special in the install of varnish (https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/varnish.rb#L31-L33) so if you have suggestions on how to improve this they would be much appreciated.

**Comment by carlocab** [comment]
The warnings from `brew bottle` are pre-existing. Would you like to open a PR for this?
