### ISSUE TITLE
mrbayes (v. 3.2.7) fails to download and install

### ISSUE THREAD

**Issue by navilo** [Homebrew/homebrew-core#86488]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
#brew config
HOMEBREW_VERSION: 3.2.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4e6919b73444e9f9e02ad81d8afc4bbd97533567
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 154015e779c8ad487ba40cf76ec5f37599875ee9
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :10.0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit unknown_0x6_0xa5
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.11.0-37-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.3 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A

#brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install mrbayes (v. 3.2.7).
While dependecies (beagle/open-mpi) were downloaded correctly (even separately installed correctly), mrbayes failed even to download.

### What happened (include all command output)?

brew install mrbayes failed with following error:
 with following error:
==> Downloading https://ghcr.io/v2/linuxbrew/core/mrbayes/manifests/3.2.7
curl: (22) The requested URL returned error: 404 
Error: mrbayes: Failed to download resource "mrbayes_bottle_manifest"
Download failed: https://ghcr.io/v2/linuxbrew/core/mrbayes/manifests/3.2.
[brew_install_mrbayes.txt](https://github.com/Homebrew/homebrew-core/files/7285359/brew_install_mrbayes.txt)

### What did you expect to happen?

I expected mrbayes formula would download and install

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. if mrbayes was already installed: brew uninstall mrbayes
2. install mrbayes: brew install mrbayes
3. see error on the screen
```

**Comment by iMichka** [comment]
I'll have a look later today. The bottle needs to be rebuilt in linuxbrew-core.

**Comment by iMichka** [comment]
Fixed by https://github.com/Homebrew/linuxbrew-core/commit/57849fc53e9a494623b93c7578b9364dfd7122ae
