### ISSUE TITLE
Rust failed to build on Mac OS 10.12.2

### ISSUE THREAD

**Issue by cema-sp** [Homebrew/homebrew-core#8656]
Trying to install **rust** `HEAD` with following command: `brew install --HEAD rust`, I have an error:

~~~
configure: error: needed, but unable to find any of: CFG_CARGO cargo
~~~

Link to gist-logs: https://gist.github.com/cema-sp/4085820d0073d76cee591bdeeb2c6057

As I understood from [this cargo issue](https://github.com/rust-lang/cargo/issues/3437), one should have previous version of binary OR compile it from source. But compilation doesn't work on my laptop.

I have tried it a number of times and resolved the issue providing _./configure_ script `cargo` binary from stable **rust** bottle:

~~~sh
./configure --prefix=/usr/local/Cellar/rust/HEAD-7ef1a69 --local-rust-root=/usr/local/Cellar/rust/HEAD-7ef1a69 --enable-optimize --cargo=/usr/local/Cellar/rust/1.13.0/bin/cargo
make && make install
~~~

Any suggestions?
____

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew?

**Comment by ilovezfs** [comment]
Closing in favor of the PR fixing it: #8708.

Thanks for reporting this.
