### ISSUE TITLE
sshguard expects a config file that is not created by brew install.

### ISSUE THREAD

**Issue by chrisjcameron** [Homebrew/homebrew-core#8657]
### Bug reports:
On a fresh install of brew on a new install of 10.11.6, I can not get sshguard to run out of the box. It seems to be missing an expected config file. The `info` mentions a script `sshguard-setup` but it is not apparent where one might find it and there are no google matches for this. The location of the expected config file might make it hard for users to provide their own settings as it seems to be in a directory managed by brew. 

I noticed that sshguard was not triggering brew to install its dependencies so I manually installed automake and reinstalled sshguard. This did not resolve the config file issue. 

Attempting to run sshguard manually shows the following. Launching via launchctl results in a short-lived process that respawns every few seconds.   
`% /usr/local/opt/sshguard/sbin/sshguard -l /var/log/system.log`
`sshguard: Could not read '/usr/local/Cellar/sshguard/1.99.0/etc/sshguard.conf'`
`Please configure SSHGuard or run 'sshguard-setup'`

`brew gist-logs sshguard`  
https://gist.github.com/1722b7e9b72b594ae5a0f31bf078dc70

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

**Comment by chrisjcameron** [comment]
It seems the sshguard formula is now linking to an experimental and undocumented version 1.99 that is  a (pre-alpha or alpha?) version of the upcoming sshguard 2.0. V2 is a significant break from previous versions which did not use config files. See for instance: https://sourceforge.net/p/sshguard/mailman/message/35593123/

Perhaps the sshguard formula in homebrew core should install the latest release of 1.7 until 2.0 is released, stable, documented and installs correctly and we could have a separate formula for sshguard2 for folks that want to beta test?

**Comment by woodruffw** [comment]
sshguard's release versioning seems to be a bit irregular (`1.99` wasn't tagged as `beta` or `rc` like previous releases on their SourceForge).  Either way, I think you're right about "downgrading" until 2.0 is released.

@ilovezfs Since you added 1.99 in 082dbc5fec1, any objections to a downgrade?

**Comment by woodruffw** [comment]
> we could have a separate formula for sshguard2 for folks that want to beta test?

We would likely do this via a `devel` block, rather than a separate formula. You're welcome to contribute one!

**Comment by selfstro** [comment]
I'd like to second the downgrade request. I wasn't sure if it is proper to create a new version of the formula with the older version (1.7.1).

**Comment by woodruffw** [comment]
No, we'd just stick with the same formula. I'll go ahead and put in the downgrade now.

**Comment by woodruffw** [comment]
Opened #9050 for the downgrade, let's move discussion there.

**Comment by chrisjcameron** [comment]
Thank you!
