### ISSUE TITLE
PostgreSQL 14 installation breaks with PostGIS

### ISSUE THREAD

**Issue by kaiquekandykoga** [Homebrew/homebrew-core#86709]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92749f9c5243691f8e576aa1227cb9ebba509cd4
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 74368c3b3950fead85a41875c6f5a01c10e72a2f
Core tap last commit: 26 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/local/Homebrew/Library/Homebrew/shims/shared/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install PostgreSQL and PostGIS.

### What happened (include all command output)?

I am trying to use PostgreSQL 14 with PostGIS.

I have an application trying to connect to the PostgreSQL and the following is happening:

`PG::RaiseException: ERROR:  PostGIS built for PostgreSQL 13.0 cannot be loaded in PostgreSQL 14.0`

It started after PostgreSQL was upgraded to version 14.

Before that it was working with version 13.

Even if I uninstall everything and try to install again the same error still occurs.

After some attempts I decided to try with PostgreSQL 13, however when I try to install PostGIS it apparently installs in the PostgreSQL 14 automatically. I do not know if there is a way to install PostGIS in a specific PostgreSQL version using brew.

`brew install postgresql@13`

In this moment if I type `brew services` only appears postgresql@13.

`brew install postgis`

After installing PostGIS if I type `brew services` appears postgresql and postgresql@13.

### What did you expect to happen?

I want to use PostgreSQL 14 with PostGIS or be able to install PostgreSQL 13 with PostGIS.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql

brew install postgis
```

**Comment by SMillerDev** [comment]
Is there a command we can run to see postgis fail with the current version?

**Comment by SMillerDev** [comment]
use `brew extract` to make a copy of postgis in a personal tap, and make it depend on postgresql@13

**Comment by SMillerDev** [comment]
FYI, @kaiquekandykoga you can likely fix your issue by running `brew reinstall -s postgis` while we work on a real fix.

**Comment by SMillerDev** [comment]
The proper way is the way I mentioned. Use `brew extract` to maintain your own version of postgis that depends on `postgresql@13`.

**Comment by kaiquekandykoga** [comment]
> 
> 
> FYI, @kaiquekandykoga you can likely fix your issue by running `brew reinstall -s postgis` while we work on a real fix.

The workaround is working.

Thank you.

**Comment by Bo98** [comment]
Should be fixed now.
