### ISSUE TITLE
postgresql@13 "pg_config --includedir-server" returns wrong directory

### ISSUE THREAD

**Issue by mkblackwell** [Homebrew/homebrew-core#86829]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.2.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: 92749f9c5243691f8e576aa1227cb9ebba509cd4
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 07b29731eb84dc9e4e5522906b4b0f4a33647897
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit kabylake
Clang: 12.0.5 build 1205
Git: 2.33.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/local/Homebrew/Library/Homebrew/shims/shared/curl
macOS: 11.6-x86_64
CLT: 12.5.1.0.1.1623191612
Xcode: 13.0
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

The latest update to Postgres 14 broke my TimescaleDB installation (it's only compatible with PG 12 and 13 at the moment). After flailing around for a bit I decided to uninstall everything, install `postgresql@13`, and edit a local copy of the `timescaledb` formula to depend on `postgresql@13`.

PG13 installed fine, but building TSDB fails - the C compiler isn't finding `postgres.h`. Looking at the make logs the build is using the wrong include path for PG's `include/server` dir, and it's getting that wrong path from `pg_config`.

### What happened (include all command output)?

```
$ pg_config --includedir-server
/usr/local/opt/postgresql@13/include/server
$ ls /usr/local/opt/postgresql@13/include/server
ls: /usr/local/opt/postgresql@13/include/server: No such file or directory
$ ls /usr/local/opt/postgresql@13/include/postgresql/server
access/			fmgr.h			nodes/			pgstat.h		postgres_ext.h		storage/
bootstrap/		foreign/		optimizer/		pgtar.h			postgres_fe.h		tcop/
c.h			funcapi.h		parser/			pgtime.h		postmaster/		tsearch/
catalog/		getaddrinfo.h		partitioning/		plperl.h		ppport.h		utils/
commands/		getopt_long.h		pg_config.h		plperl_helpers.h	regex/			windowapi.h
common/			jit/			pg_config_ext.h		plpgsql.h		replication/
datatype/		lib/			pg_config_manual.h	port/			rewrite/
executor/		libpq/			pg_config_os.h		port.h			rusagestub.h
extension/		mb/			pg_getopt.h		portability/		snowball/
fe_utils/		miscadmin.h		pg_trace.h		postgres.h		statistics/
```

### What did you expect to happen?

I expect `pg_config --include-server` to return `/usr/local/opt/postgresql@13/include/postgresql/server`.

(Note second-to-last subdir `postgresql`).

The problem seems similar to the pkglibdir issue reported here: https://github.com/Homebrew/homebrew-core/issues/62930

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install postgresql@13
$ pg_config --includedir-server
```

**Comment by b4stien** [comment]
Same issue here (to install PostGIS with a custom formula on postgresql@13). Did you find a mitigation/workaround?
