### ISSUE TITLE
gcc5 removed from Homebrew Versions and can't be found in Core

### ISSUE THREAD

**Issue by j-cimb-barker** [Homebrew/homebrew-core#8683]
Hello,

I've noticed that gcc5 was removed from Homebrew Versions. Is there a replacement recipe for this...? 

`brew install gcc5`

Gives me:

`Error: No available formula with the name "homebrew/core/gcc@5"`

`brew install gcc`

Gives me:

```
These formulae were found in taps:
homebrew/dupes/apple-gcc42               Caskroom/cask/gcc-arm-embedded
To install one of them, run (for example):
  brew install homebrew/dupes/apple-gcc42

```
Thanks in advance...

**Comment by ilovezfs** [comment]
It sounds like your brew is outdated.
```
iMac-TMP:~ joe$ brew install gcc5
==> Downloading https://homebrew.bintray.com/bottles/gcc@5-5.4.0_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gcc@5-5.4.0_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/gcc@5/5.4.0_1: 1,391 files, 253.3M
iMac-TMP:~ joe$ 
```

It's possible you were a victim of
https://twitter.com/MacHomebrew/status/763686348041641984
https://github.com/Homebrew/brew/blob/3fde8624b3aec788248c652dff84a62fd051da98/README.md#update-bug

**Comment by j-cimb-barker** [comment]
I re-installed Homebrew in the end.
