### ISSUE TITLE
Missing documentation for git-subtree

### ISSUE THREAD

**Issue by luc-j-bourhis** [Homebrew/homebrew-core#8685]
[git-subtree-doc.zip](https://github.com/Homebrew/homebrew-core/files/696025/git-subtree-doc.zip)

### Bug reports:

```
% git subtree --help
The file /usr/local/Cellar/git/2.11.0/share/doc/git-doc/git-subtree.html does not exist.
```
and indeed that file is not installed. Neither is `/usr/local/share/man/man1/git-subtree.1`. 

Fixing this requires to generate those two documentation files from `contrib/subtree/git-subtree.txt` from the same directory inside which the formula `git.rb` builds git-subtree, as they are not included in the archives referenced by the resource's "html" and "man" in that formula.

However Macports has done the job already: they install by hand the two files I have attached to this issue. Yes, I know that they have been generated for git 2.10.2 as mention in the header of the manfile and it's not because Macports is behind versions as they ship git 2.11 but regenerating those docs is a hassle as duly noted in the `git.rb` formula. But having those two files would be better than nothing imho.

```
% brew config                         
HOMEBREW_VERSION: 1.1.6-45-g9cce3414
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9cce3414fbd39d146d97911dbb3bf07fffaa1080
Last commit: 21 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5ce01ec9c8b9958e2d9a7791e4d4e2aa0bf4fd8f
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 12-core 64-bit arrandale
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.7.0_17, 1.6.0_65-b14-468
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: N/A
X11: 2.7.11 => /opt/X11
```

```
% brew doctor                             
Your system is ready to brew.
```

**Comment by ilovezfs** [comment]
This will need to be fixed upstream.
