### ISSUE TITLE
[`sqlite`] Configure-Time Error

### ISSUE THREAD

**Issue by RandomDSdevel** [Homebrew/homebrew-core#8714]
### Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

&thinsp;&thinsp;&thinsp;&thinsp;&thinsp;Homebrew failed to `configure` SQLite v3.16.2 prior to building it from source with the `--with-docs`, `--with-dbstat`, `--with-icu4c`. ` --with-json1`. `--with-fts`, `--with-secure-delete`, `--with-session`, and `--with-unlock-notify` options enabled.  Specifically, it failed when determining whether or not cross-compilation was occurring, which is quite strange.  [Here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/SQLite/v3.16.2/First%20Attempt) are the logs for my first attempt, during which the `--universal` option was also passed to `brew upgrade`/`brew reinstall` due to how I had been using it previously for some crazy reason despite not needing it, and [here](https://github.com/RandomDSdevel/Homebrew-Installation-Logs/tree/master/SQLite/v3.16.2/Second%20Attempt) are the logs for my second attempt, which I performed after running `brew update-reset` just to see if that might help and from which I stripped the `--universal` option.  Please also note that the notices from `brew doctor` about `qt5` being `brew missing` in both sessions' copies of `doctor.out` are due to #8502, which is still open for me down here on my end despite being closed here on GitHub due to the inability of me or anybody else to reproduce it on any other machine(s.)  Also, please note that, in both sessions' logs, `config.log` is the result of the `configure` step, whereas `config.out` is the result of redirecting the standard output and error of `brew config` to said file.

**Comment by tdsmith** [comment]
in config.log:

```
dyld: Library not loaded: libicui18n.58.dylib
  Referenced from: /private/tmp/sqlite-20170109-25284-1nye26g/sqlite-autoconf-3160200/./conftest
  Reason: image not found
```

Try rebuilding libicu I guess!

**Comment by RandomDSdevel** [comment]
Hmm, just updated to ICU4C v58.2 relatively recently, so that _should_ be there.  That being said, I might go ahead and try `brew reinstall`-ing it to see if that fixes my issue.  I _do_ remember having some problems with another package looking for an older, no-longer-installed version of ICU4C before, but I can't remember what the relevant GitHub issue number was…; oh, well.

**Comment by RandomDSdevel** [comment]
Hey, cool!  That seems to have done the trick.  Wonder why, though…?  Eh, who cares, it works.  (_Shrug._)

**Comment by MikeMcQuaid** [comment]
@RandomDSdevel A tip for filing these issues in future in a way that'll get us more response and let you help yourself: try to narrow down which option is the problem by building different combinations of options until you narrow it down to 1 option or at least 1 combination of options that's causing the problem (rather than "I built with all the options and it broke"). I appreciate this may be painful with e.g. Qt5 but this should take long for something as quick to build as SQLite.

**Comment by MikeMcQuaid** [comment]
Also worth noting: this is another reason to not build from source with all options if you're not able to fix these things yourself: we intentionally don't bump revisions on optional dependencies so when things like icu4c are bumped they _will_ break other formulae. `brew linkage` may help you debug some of this so you can `brew reinstall` the relevant formulae.
