### ISSUE TITLE
mysql is not a dependency for percona-xtrabackup

### ISSUE THREAD

**Issue by utdrmac** [Homebrew/homebrew-core#8717]
Hello,
I'm an employee of @Percona. I'm attempting to install percona-xtrabackup as below. I already have percona-server installed. The p-x package says "mysql" is a dependency for this and is asking me to unlink percona so it can install community mysql.

This is incorrect. As percona-server is mysql, there should absolutely zero need to remove any notion of percona software in order to install other percona software.

Please fix the percona-xtrabackup recipe to no longer give this message and allow p-x to be installed when percona-server already exists.

For completeness, "mysql" should be considered an optional/alternative package and "percona-server" should be the primary dependency.

```
[drmac@othala vagrant-percona]$ brew install percona-xtrabackup
==> Auto-updated Homebrew!
Updated Homebrew from c3f959d to 9cce341.
No changes to formulae.

==> Installing dependencies for percona-xtrabackup: mysql, libev, libgpg-error, libgcrypt
==> Installing percona-xtrabackup dependency: mysql
Error: Cannot install mysql because conflicting formulae are installed.

  percona-server: because mysql, mariadb, and percona install the same binaries.

Please `brew unlink percona-server` before continuing.
```

**Comment by MikeMcQuaid** [comment]
> The p-x package says "mysql" is a dependency for this and is asking me to unlink percona so it can install community mysql.

This is because the binary package is built against MySQL by default. If you wish to build against `persona-server` you can `brew install --build-from-source percona-xtrabackup`.

**Comment by utdrmac** [comment]
@MikeMcQuaid Please re-open. Percona XtraBackup is not "built against MySQL" under any circumstances. There should be no dependency for having MySQL installed in any way in order to install XtraBackup. Consider the following dependency tree from our RPM package. You'll notice that not even libmysqlclient is required for installation; additionally, no mysql server-type components are required either.

```
[mboehm@aspirin ~]$ wget http://repo.percona.com/release/7/RPMS/x86_64/percona-xtrabackup-24-2.4.5-1.el7.x86_64.rpm
--2017-01-11 10:42:55--  http://repo.percona.com/release/7/RPMS/x86_64/percona-xtrabackup-24-2.4.5-1.el7.x86_64.rpm
Resolving repo.percona.com... 74.121.199.234
Connecting to repo.percona.com|74.121.199.234|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7644140 (7.3M) [application/x-redhat-package-manager]
Saving to: “percona-xtrabackup-24-2.4.5-1.el7.x86_64.rpm”

100%[===============================================================================================================================================================================>] 7,644,140   8.94M/s   in 0.8s

2017-01-11 10:42:56 (8.94 MB/s) - “percona-xtrabackup-24-2.4.5-1.el7.x86_64.rpm” saved [7644140/7644140]

[mboehm@aspirin ~]$
[mboehm@aspirin ~]$ rpm -qpR percona-xtrabackup-24-2.4.5-1.el7.x86_64.rpm
/bin/bash
libaio.so.1()(64bit)
libaio.so.1(LIBAIO_0.1)(64bit)
libaio.so.1(LIBAIO_0.4)(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.10)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libcrypt.so.1()(64bit)
libcrypt.so.1(GLIBC_2.2.5)(64bit)
libcrypto.so.10()(64bit)
libcrypto.so.10(libcrypto.so.10)(64bit)
libcurl.so.4()(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libev.so.4()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcrypt.so.11()(64bit)
libgcrypt.so.11(GCRYPT_1.2)(64bit)
libgpg-error.so.0()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libnuma.so.1()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
librt.so.1(GLIBC_2.3.3)(64bit)
libssl.so.10()(64bit)
libssl.so.10(libssl.so.10)(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(CXXABI_1.3.1)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libz.so.1()(64bit)
libz.so.1(ZLIB_1.2.0)(64bit)
perl(DBD::mysql)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rsync
rtld(GNU_HASH)
rpmlib(PayloadIsXz) <= 5.2-1
```

**Comment by ilovezfs** [comment]
The vendored perl module DBD::mysql seems to be the reason for the `depends_on :mysql => :recommended`

**Comment by utdrmac** [comment]
@ilovezfs Even perl DBD::mysql doesn't require that mysql server be installed.

**Comment by MikeMcQuaid** [comment]
> Percona XtraBackup is not "built against MySQL" under any circumstances.

It is actually built against the MySQL formula in the Homebrew formula because MySQL and Percona Server can't be installed side-by-side and MySQL is more widely used.

We'll accept PRs that adjust the MySQL, Percona Server and Percona Xtrabackup formulae to do what you want but this is not something we're planning on working on.  [This document should help you open a PR](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by MikeMcQuaid** [comment]
@utdrmac I don't disagree, I'm just saying this isn't something we're planning on working on as a team.

**Comment by MikeMcQuaid** [comment]
> why does homebrew require this for Mac?

I believe that's been explained already: the vendored perl module `DBD::mysql`.

**Comment by utdrmac** [comment]
I believe I too explained that DBD::mysql is also not dependent on having mysql server installed. Therefore, as stated in my original request, the build requirement of having mysql installed is incorrect. Maybe it can be optional or recommended but certainly not required.

**Comment by MikeMcQuaid** [comment]
> Maybe it can be optional or recommended but certainly not required.

It is recommended: https://github.com/Homebrew/homebrew-core/blob/master/Formula/percona-xtrabackup.rb#L18

**Comment by utdrmac** [comment]
ok. i misspoke. recommended is essentially requires as i cannot install PXB without removing percona-server and first installing mysql (which are the same thing, essentially). so it should be purely "optional"

**Comment by utdrmac** [comment]
and additionally, "percona-server" 100% satisfies the requirement of "mysql" in every way, shape and form.

**Comment by MikeMcQuaid** [comment]
> recommended is essentially requires as i cannot install PXB without removing percona-server and first installing mysql (which are the same thing, essentially)

That is not the case. As noted before you can `brew install --build-from-source percona-xtrabackup`. You can also `brew install --without-mysql percona-xtrabackup`.

Again, regardless of what this should or should not be: someone would need to make this change and that's not likely to be one of the maintainers.

**Comment by utdrmac** [comment]
Doesn't "maintainer" imply one who would maintain the code and therefore make the change?

**Comment by MikeMcQuaid** [comment]
For Homebrew it implies someone with commit access. I'm the lead maintainer and have been trying to diplomatically say that as this isn't a widely reported user issue I cannot prioritise this over things that affect more people.
