### ISSUE TITLE
golang: 1.8RC1 support

### ISSUE THREAD

**Issue by jadbox** [Homebrew/homebrew-core#8722]
Today 1.8 RC1 was released: not sure what the appropriate way to support it within the devel option of brew. Currently 1.8 Beta 2 is the latest on brew devel.

https://groups.google.com/forum/#!topic/golang-nuts/tr2ZKSQ42zE

**Comment by woodruffw** [comment]
@jadbox The correct way to support it is to amend the devel block to contain the new URL, version, and sha256. We'd appreciate a PR to do exactly that!
