### ISSUE TITLE
pypy 5.1.1 is 5.1.0

### ISSUE THREAD

**Issue by Marqin** [Homebrew/homebrew-core#873]
pypy 5.1.1 was installed:
```
brew info pypy
pypy: stable 5.1.1 (bottled)
Highly performant implementation of Python 2 in Python
http://pypy.org/
/usr/local/Cellar/pypy/5.1.1 (2,453 files, 104.7M) *
  Poured from bottle
```

But it reports as 5.1.0:
```
/usr/local/Cellar/pypy/5.1.1/bin/pypy --version
Python 2.7.10 (3260adbeba4a8b6659d1cc0d0b41f266769b74da, May 03 2016, 20:38:25)
[PyPy 5.1.0 with GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)]
```

**Comment by tdsmith** [comment]
pinged their IRC channel: https://botbot.me/freenode/pypy/2016-05-05/?msg=65526303&page=2

**Comment by tdsmith** [comment]
What's up with http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1306/ -- the downstream Bottle build didn't kick off? (If that's the case why is the bottle checksum correct?)

**Comment by tdsmith** [comment]
I think their source tarball is bad; `brew unpack pypy; cd pypy-5.1.1; grep -R PYPY_VERSION .` yields `./pypy/module/cpyext/include/patchlevel.h:#define PYPY_VERSION "5.1.0"`

**Comment by tdsmith** [comment]
https://bitbucket.org/pypy/pypy/issues/2292/511-source-tarball-is-really-510

**Comment by DomT4** [comment]
> What's up with http://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/1306/ -- the downstream Bottle build didn't kick off? (If that's the case why is the bottle checksum correct?)

We retain very few bottle builds relative to the amount we process per day. Consequently Jenkins doesn't know one ever existed, but it passed okay at the time.

**Comment by Marqin** [comment]
@mikemcquaid @rakkesh when 5.1.1 will be available?

`brew update && brew outdated | grep pypy`
gives nothing.

**Comment by rakkesh** [comment]
@Marqin there was no revision bump done for `pypy` in this PR, as this was a minor change related to version numbering. You need to uninstall and then install it.

```sh
$ brew remove pypy
$ brew install pypy
```

**Comment by rakkesh** [comment]
@DomT4 as the build for this PR timed out, I guess no new bottles were generated.😅

**Comment by DomT4** [comment]
No, I'll probably get that done later when things are quiet.

**Comment by DomT4** [comment]
Sadly `pypy` is a hilariously big build from source.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/commit/0d4cda74d39be45cf87853bcf80be8e42a2abeb5

**Comment by Marqin** [comment]
@DomT4 after this forced reinstall it changed many files and eg. added
`/usr/local/Cellar/pypy/5.1.1/libexec/include/numpy/` directory  so
**it's not minor change and you should increment build version number**

**Comment by DomT4** [comment]
I can't speak for the completeness of the prior tarball, upstream didn't state anything beside acknowledging the versioning hiccup. Tim may have a better idea.

**Comment by tdsmith** [comment]
I should have thought to bump; sorry I didn't comment on the fix up PR.

**Comment by DomT4** [comment]
I'll nudge a revision through CI later when things are a bit quieter.

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-core/commit/1d54cfeb5235317ad167d24b1d9bbb0c01de3b43

**Comment by thomasahle** [comment]
Any plans on updating pypy3 as well? I can only install version 2.4.0 with brew, whereas the website has 5.2.0.

**Comment by DomT4** [comment]
It looks like `5.2.0` is an alpha release? We'd possibly accept it as a `devel` block if it is, but seems `2.4.0` is still the stable.
