### ISSUE TITLE
Installation of homebrew/science/vips fails

### ISSUE THREAD

**Issue by korya** [Homebrew/homebrew-core#8737]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I just tried to run `brew upgrade` and the command failed. I uninstalled the package, ran `brew cleanup -s` and installed it back, same problem remains. I followed the instructions at https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting, nothing helped.

The problem seems to be with `homebrew/science/vips` package. I have not installed it, it comes as a dependency for other package. 

Here is `brew gist-logs`: https://gist.github.com/24d4d89ef4af67cdf52dd36ef27f0ab3

**Comment by MikeMcQuaid** [comment]
Please report this to homebrew/science (as the message should have indicated).

**Comment by korya** [comment]
Sorry, did not pay attention to it...
