### ISSUE TITLE
homebrew/versions/go15 failed to build on macOS 10.12.2

### ISSUE THREAD

**Issue by rudra101** [Homebrew/homebrew-core#8765]
Please find the Gist created [here](https://gist.github.com/anonymous/054aead9590bc1a198d9b99b8eac5770).

**Comment by DomT4** [comment]
Someone needs to update the bootstrap, presuming they released a fixed 1.4.x release in the end.

**Comment by MikeMcQuaid** [comment]
This issue should be submitted to homebrew/versions but it's deprecated. This will be fixed or the formula removed when it's migrated from homebrew/versions. We'll accept a PR to fix it before then.
