### ISSUE TITLE
Monterey bottling

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-core#87708]
This is a tracking issue on Monterey bottling process and will be used as a dump for build failures.

This year we are bottling for both x86_64 and arm64. ~~**Our upload flow cannot currently handle bottling for both at the same time - please wait for one architecture to complete and be pushed to master before starting the other architecture.**~~ **If you are bottling for both at the same time, pass `--macos=12,12-arm64`. Do not start two independent runs at the same time.**

Currently, we have six x86_64 runners and three arm64 runners.

The arm64 runners are currently running 12.0.1 RC with Xcode 13.1 RC.
The x86_64 runners are also using Xcode 13.1 RC but are stuck on 12.0 beta 10 as their board ID is currently blocked from receiving further updates. I don't anticipate this will cause any issues for mass bottling however.

I will start by focussing on popular formula with a high number of dependents.

**Please do not bottle something until all its dependencies have been bottled and their associated bottle commits have been pushed to master.**

**Comment by chenrui333** [comment]
Noted, sorry about the hassle. I will check out the deps before triggering new builds.

**Comment by Bo98** [comment]
> We can probably fix `gdbm` at #87641.

Not sure what the best strategy for this is going to be. We're going to want to do this for several popular formulae, all of which could potentially be very long dependent testing times competing for limited (3) CI machines.

**Comment by Bo98** [comment]
No idea what's going on with `libzip`. Might be worth trying that in a PR and seeing if it affects any other macOS version.

**Comment by carlocab** [comment]
Not sure what to make of `ocaml`. Their libraries are compiled with `-flat_namespace` on Catalina too, but they also carry the buggy `libtool.m4` in their source tarball.

**Comment by Bo98** [comment]
Probably because of https://github.com/ocaml/ocaml/blob/trunk/configure.ac#L954 originating from 2002 (https://github.com/ocaml/ocaml/commit/c4411b3972b2e3b2ed8520b60fd80010e25e6bdf)

**Comment by Bo98** [comment]
> ❌ @Bo98 bottle request for libtiff [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1369513197).

We can apply this patch: https://gitlab.com/libtiff/libtiff/-/commit/b25618f6fcaf5b39f0a5b6be3ab2fb288cf7a75b.diff (minus the `.gitignore` part). This will however require autoconf 2.69 and automake.

**Comment by Bo98** [comment]
Progress report: about 10%

```
$ grep -l "arm64_big_sur" * | wc -l
    4777
$ grep -l "arm64_monterey" * | wc -l
     450
```

```
$ grep -l " big_sur:" * | wc -l
    5121
$ grep -l " monterey:" * | wc -l
     439
```

This takes a lot longer than I realised.

**Comment by carlocab** [comment]
I think @jonchang had automation that would dispatch bottle jobs whenever there was unused capacity (which I think we have a lot of right now) on CI last year.

**Comment by Bo98** [comment]
Last year we also didn't have two architectures to bottle for and didn't have to do gymnastics of avoiding them uploading at the same time.

**Comment by Bo98** [comment]
I could do this:

```
concurrency:
  group: "dispatch-build-bottle-${{github.event.inputs.formula}}"
```

but comes with the bigg caveat that jobs that are pending/queued will be cancelled rather than attempted later.

**Comment by Bo98** [comment]
Possibly, but not with the way it's currently structured (the whole push action is external).

Though I'm not 100% sure the actual bottle upload part is fully atomic. I don't think we've properly tested that.

**Comment by jonchang** [comment]
@carlocab I'm fairly sure I have a copy of the "bottle stuff when the queue is empty" script on my old laptop but I'll have to dig it out to check.

**Comment by carlocab** [comment]
> ❌ @carlocab bottle request for vera++ [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1399783543).

```
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/lib/libpython2.7.tbd for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Interesting

**Comment by carlocab** [comment]
> ❌ @carlocab bottle request for drafter [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1402390249).

`#include <version>`

**Comment by carlocab** [comment]
> ❌ @carlocab bottle request for lanraragi [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1402390484).

Needs `IO::Socket::SSL`

**Comment by carlocab** [comment]
> ❌ @carlocab bottle request for xsd [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1402399971).

`#include <version>`

**Comment by carlocab** [comment]
> ❌ @carlocab bottle request for bareos-client [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1403874040).

This has a hardcoded `/usr/local/opt/gettext/lib/libintl.a`

**Comment by carlocab** [comment]
`qt@5` error:
```
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >::shrink_to_fit()", referenced from:
      base::UTF8ToUTF16(char const*, unsigned long, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >*) in libbase.a(base_jumbo_20.o)
      base::WideToUTF16(wchar_t const*, unsigned long, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> >*) in libbase.a(base_jumbo_20.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../3rdparty/chromium/build/toolchain/mac/linker_driver.py", line 287, in <module>
    Main(sys.argv)
  File "../../3rdparty/chromium/build/toolchain/mac/linker_driver.py", line 97, in Main
    subprocess.check_call(compiler_driver_args, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../../../../../../../Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++', '-B', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/', '-Wl,-fatal_warnings', '-stdlib=libc++', '-arch', 'x86_64', '-Wl,-no_data_in_code_info', '-Wl,-no_function_starts', '-isysroot', '../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk', '-mmacosx-version-min=10.13', '-Wl,-ObjC', '-o', './transport_security_state_generator', '-Wl,-filelist,./transport_security_state_generator.rsp', '-framework', 'ApplicationServices', '-framework', 'AppKit', '-lbsm', '-framework', 'CoreFoundation', '-framework', 'IOKit', '-framework', 'OpenDirectory', '-lpmenergy', '-lpmsample', '-framework', 'Security']' returned non-zero exit status 1
```

**Comment by danielnachun** [comment]
As I feared this was a failure in `qtwebengine`.  I keep running of out disk space when I try to build this locally!  It appears that the bundled Chromium has been updated several times since the 5.15.7 release: https://invent.kde.org/qt/qt/qtwebengine/-/commits/5.15.7/.  Perhaps we need to do the same?  We'll have to see what commit and patch version we are using right now.

**Comment by carlocab** [comment]
Maybe? I guess what confuses me is that this error looks like it should be generic, but it isn't. We didn't encounter it on ARM Monterey, which already has a `qt@5` bottle. Could this be a race condition?

**Comment by danielnachun** [comment]
It looks like `qtwebengine` is skipped on ARM for `qt@5`, so this failure can't happen on that architecture.

**Comment by carlocab** [comment]
Ah, good catch. That makes sense. I suppose we could try updating `qtwebengine`...

**Comment by carlocab** [comment]
I have a build going for Qt6 that should build `qtwebengine`: https://github.com/Homebrew/homebrew-core/runs/4101460190?check_suite_focus=true

It's already succeeded on ARM, and is still going on Intel. If that succeeds it suggests a newer Chromium might help.

**Comment by carlocab** [comment]
Homebrew/homebrew-core
@09c8bb90953b9d02217eb7be984c8e087c4e83b6

**Comment by carlocab** [comment]
@chenrui333 please don't trigger bottle jobs for formulae that have unbottled dependencies.
```
==> Populating dependency tree...
==> :arm64_monterey bottle status
sigrok-cli: unbottled deps: apr apr-util subversion gts librsvg graphviz gcc openblas numpy libsigrok libsigrokdecode
```

**Comment by alebcay** [comment]
> ❌ @alebcay bottle request for neopop-sdl [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1432425386).

Looks similar to the download error seen with `libzip`.

**Comment by carlocab** [comment]
@alebcay here's a list of formulae I'd already dispatched bottle jobs for previously: https://gist.github.com/carlocab/8f0aa177734645946f2e844396a75f4c

It's not complete, but it does cover some recent failures.

**Comment by alebcay** [comment]
Thanks, will review to avoid re-running needlessly.

**Comment by carlocab** [comment]
> > ❌ @alebcay bottle request for neopop-sdl [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1432425386).
> 
> Looks similar to the download error seen with `libzip`.

Yup, that's in #88329.

**Comment by carlocab** [comment]
> ❌ @fxcoudert bottle request for hdf5 [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1504287282).
```
configure: error: No output from Fortran test program!
```
I think this happened on Intel Monterey too.

**Comment by fxcoudert** [comment]
Re. hdf5: I think it's Fortran's redirection of stdout that fails, a known Monterey bug :(

**Comment by carlocab** [comment]
> Re. hdf5: I think it's Fortran's redirection of stdout that fails, a known Monterey bug :(

MacPorts carries a patch that looks related: https://github.com/macports/macports-ports/blob/master/lang/gcc11/files/patch-darwin21-fortran.diff

Not sure if that's in your branch yet.

**Comment by fxcoudert** [comment]
> MacPorts carries a patch that looks related: https://github.com/macports/macports-ports/blob/master/lang/gcc11/files/patch-darwin21-fortran.diff

Not in my branch, but would need to be applied on Intel too, anyway. Will consider it as a follow-up.

**Comment by fxcoudert** [comment]
I am seeing several formulas fail with:

```
  epsilon:
    * Libraries were compiled with a flat namespace.
      This can cause linker errors due to name collisions, and
      is often due to a bug in detecting the macOS version.
        /opt/homebrew/Cellar/epsilon/0.9.2/lib/libepsilon.1.0.0.dylib
```

But I think in some case (like openmotif) it is actually done on purpose.

**Comment by carlocab** [comment]
> I am seeing several formulas fail with:
> 
> ```
>   epsilon:
>     * Libraries were compiled with a flat namespace.
>       This can cause linker errors due to name collisions, and
>       is often due to a bug in detecting the macOS version.
>         /opt/homebrew/Cellar/epsilon/0.9.2/lib/libepsilon.1.0.0.dylib
> ```
> 
> But I think in some case (like openmotif) it is actually done on purpose.

Yes, I've fixed a lot of those. There are a few dozen remaining though. We have an allowlist for the ones that do it on purpose. I don't think `openmotif` is purposeful though -- their `configure` script is just bitten by the Libtool bug. See #88521

**Comment by carlocab** [comment]
> ❌ @fxcoudert bottle request for qt@5 [failed](https://github.com/Homebrew/homebrew-core/actions/runs/1506707877).

`qtwebengine` fails to build on Monterey. I thought about disabling it, but I think some dependents need it + some users also rely on it being there. It would be pretty surprising to have `qtwebengine` when installing `qt@5` on Big Sur but not on Monterey.

**Comment by cho-m** [comment]
The following 68 formulae now have an `all` bottle added into OS-specific bottle block, which may be due to `12` and `12-arm64` generating identical bottles:

<details>
<summary>Formulae list</summary>

- [ ] `align`
- [ ] `apollo`
- [ ] `cash-cli`
- [ ] `chruby`
- [ ] `cvsutils`
- [ ] `docx2txt`
- [ ] `dupseek`
- [ ] `easy-rsa`
- [ ] `foreman`
- [ ] `fpp`
- [ ] `g2`
- [ ] `generate-json-schema`
- [ ] `ghi`
- [ ] `gist`
- [ ] `git-cal`
- [ ] `git-integration`
- [ ] `git-multipush`
- [ ] `git-now`
- [ ] `git-number`
- [ ] `git-octopus`
- [ ] `git-secrets`
- [ ] `git-standup`
- [ ] `git-tracker`
- [ ] `gitslave`
- [ ] `gnome-common`
- [ ] `gpm`
- [ ] `gvp`
- [ ] `icon-naming-utils`
- [ ] `imessage-ruby`
- [ ] `jsonlint`
- [ ] `kaitai-struct-compiler`
- [ ] `logcheck`
- [ ] `lolcat`
- [ ] `markdown`
- [ ] `mecab-jumandic`
- [ ] `mecab-unidic`
- [ ] `mergepbx`
- [ ] `mkvdts2ac3`
- [ ] `nanopb-generator`
- [ ] `ndiff`
- [ ] `onetime`
- [ ] `pass-otp`
- [ ] `pdf-redact-tools`
- [ ] `pex`
- [ ] `pipes-sh`
- [ ] `pkgdiff`
- [ ] `quicktype`
- [ ] `range-v3`
- [ ] `rcm`
- [ ] `react-native-cli`
- [ ] `roundup`
- [ ] `rubyfmt`
- [ ] `ry`
- [ ] `sjk`
- [ ] `sloc`
- [ ] `st`
- [ ] `termcolor`
- [ ] `terraform_landscape`
- [ ] `tesseract-lang`
- [ ] `translate-shell`
- [ ] `um`
- [ ] `umple`
- [ ] `urdfdom_headers`
- [ ] `vert.x`
- [ ] `vip`
- [ ] `wemux`
- [ ] `xbitmaps`
- [ ] `zshdb`
</details>

**Comment by Bo98** [comment]
> The following 68 formulae now have an `all` bottle added into OS-specific bottle block, which may be due to `12` and `12-arm64` generating identical bottles:

Easiest solution for those is to just remove that line and dispatch the bottle job again. The bug which caused this should already be fixed.

**Comment by Bo98** [comment]
For clarity: it was fixed in https://github.com/Homebrew/brew/pull/12384 + https://github.com/Homebrew/brew/pull/12387.

**Comment by Bo98** [comment]
Mass bottling is over. Focus will be on Ventura shortly.
