### ISSUE TITLE
mariadb@10.2 wrong download url

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-core#87751]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.2.17-110-g6de841c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6de841cd73e3a481be57301225b596e39a70868a
Last commit: 11 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 97fc20123e53d9fd5399605f718ae9671d41896c
Core tap last commit: 70 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /Users/dwt/Library/Homebrew
HOMEBREW_REPOSITORY: /Users/dwt/Library/Homebrew
HOMEBREW_CELLAR: /Users/dwt/Library/Homebrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.wkWPuJn6NS/org.xquartz:0
HOMEBREW_EDITOR: mate -w
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.33.1 => /Users/dwt/Library/Homebrew/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: N/A
Xcode: 13.0
XQuartz: 2.8.1 => /opt/X11

% brew doctor
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the keys-pub/tap tap (not Homebrew/brew or Homebrew/core):
  /Users/dwt/Library/Homebrew/Library/Taps/keys-pub/homebrew-tap/keys.rb:5

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Update mariadb@10.2

### What happened (include all command output)?

 % brew upgrade mariadb@10.2
==> Upgrading 1 outdated package:
mariadb@10.2 10.2.39 -> 10.2.40
Warning: Building mariadb@10.2 from source as the bottle needs:
- HOMEBREW_CELLAR: /usr/local/Cellar (yours is /Users/dwt/Library/Homebrew/Cellar)
- HOMEBREW_PREFIX: /usr/local (yours is /Users/dwt/Library/Homebrew)
==> Downloading https://github.com/MariaDB/server/commit/9d5967f74bd0c471153c80ced240e586721e0e03.patch?full_inde
Already downloaded: /Users/dwt/Library/Caches/Homebrew/downloads/20b83061a980d8b061a2eaf07fe617f478c852cb4452cfe20d73500cbf7312a6--9d5967f74bd0c471153c80ced240e586721e0e03.patch
==> Downloading https://downloads.mariadb.org/f/mariadb-10.2.40/source/mariadb-10.2.40.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: mariadb@10.2: Failed to download resource "mariadb@10.2"
Download failed: https://downloads.mariadb.org/f/mariadb-10.2.40/source/mariadb-10.2.40.tar.gz

### What did you expect to happen?

I expected it to download the sources from the url https://downloads.mariadb.org/f/mariadb-10.2.40/source/mariadb-10.2.40.tar.gz - but that url doesn't exist (anymore?)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade mariadb@10.2
```

**Comment by Bo98** [comment]
Fixed.
