### ISSUE TITLE
Formula for qt@5.5 does not properly recognise xcode install on MacOS Sierra

### ISSUE THREAD

**Issue by lukaso** [Homebrew/homebrew-core#8777]
### Bug reports:

Error received when building `capybara-webkit` against qt55 on MacOS Sierra `gem install capybara-webkit`:
 
```
Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.
*** extconf.rb failed ***
```

Requested brew output:

```
$ brew gist-logs qt55
Error: No logs.

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  qt@5.5
```

#### Fix is described here

https://github.com/thoughtbot/capybara-webkit/issues/813

This fix is working for me.

##### Fix description from above issue by @kingdonb

I ran into this issue still today, and I was able to resolve it thanks to:

http://stackoverflow.com/questions/33728905/qt-creator-project-error-xcode-not-set-up-properly-you-may-need-to-confirm-t

The secret was:
(in your `QtInstallDir`, in `clang_64/mkspecs/features/mac/default_pre.prf`)

Replace:

`isEmpty($$list($$system("/usr/bin/xcrun -find xcrun 2>/dev/null")))`

With:

`isEmpty($$list($$system("/usr/bin/xcrun -find xcodebuild 2>/dev/null")))`

**Comment by MikeMcQuaid** [comment]
This builds fine for us on our CI boxes. We'll accept a PR to fix it but don't provide the same level of support to `@`-versioned formulae.

**Comment by MikeMcQuaid** [comment]
I can reproduce this now, actually. Any idea whether upstream Qt are still accepting patches for Qt 5.5? If not, we may want to use an `in replace` here.

**Comment by lukaso** [comment]
I did a bit more digging, and it appears the full fix would include all the
other xcode platforms (such as ios), and it wasn't clear that this had been
done in either 5.7 or 5.8. Haven't had time to dig much further.

**Comment by MikeMcQuaid** [comment]
@lukaso Could you try and open a pull request with an `in replace`? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by ilovezfs** [comment]
This was fixed in https://github.com/Homebrew/homebrew-core/pull/9295.
