### ISSUE TITLE
git formula should install perl Net/SMTP/SSL.pm package

### ISSUE THREAD

**Issue by ppannuto** [Homebrew/homebrew-core#8783]
The `git send-email` requires the SSL plugin to send authenticated e-mails (i.e. sending via gmail's smtp servers), if it's missing you get an error like this:

```
$ git send-email --to=newlib@sourceware.org *.patch
Can't locate Error.pm in @INC (you may need to install the Error module) (@INC contains: /usr/local/Cellar/git/2.11.0/lib/perl5/site_perl /Applications/Xcode.app/Contents/Developer/Library/Perl/5.18/darwin-thread-multi-2level /Library/Developer/CommandLineTools/Library/Perl/5.18/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/site_perl/5.24.0 /usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0/darwin-thread-multi-2level /usr/local/Cellar/perl/5.24.0_1/lib/perl5/5.24.0 /usr/local/lib/perl5/site_perl/5.24.0 .) at /usr/local/Cellar/git/2.11.0/libexec/git-core/git-send-email line 30.
BEGIN failed--compilation aborted at /usr/local/Cellar/git/2.11.0/libexec/git-core/git-send-email line 30.
```

When git is built/installed, it records the perl path in use at install time and saves that for all future uses ( see http://www.spinics.net/lists/git/msg293524.html ). If a user later installs a different default version of perl (say, to /usr/bin/local/perl via brew...), then running cpan or any other regular installer will install the missing package for the new perl, but not the one git actually uses. The results is that `perl -MNet::SMTP::SSL -e exit` will work, but `git send-email` will still fail -- very confusing.

Brew should install all of the perl dependencies at git install time using the perl that it provides to git to avoid this confusion. I unfortunately know nothing about perl, and getting cpan to install something headless doesn't seem to have an obvious flag, so issue, not PR, sorry - hopefully someone who groks perl can pick this up and fix easily.

---

```
$ brew config
HOMEBREW_VERSION: 1.1.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cce3414fbd39d146d97911dbb3bf07fffaa1080
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a5d58ec39c689133d0ce2013f1e95e1208040f86
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_25, 1.7.0_45, 1.6.0_65-b14-468
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  gcc-arm-none-eabi-49
  suite-sparse421
```

**Comment by gwerbin** [comment]
The problem here is that Homebrew doesn't (yet) track the Perl version that's installed, so even if Perl and all the correct modules were installed at first, it seems like a `brew upgrade` would just blow that away. Are there any plans to version Perl the way GCC is versioned now?

**Comment by MikeMcQuaid** [comment]
@gwerbin That's probably unlikely.

**Comment by MikeMcQuaid** [comment]
@gwerbin Better would be to rely on the system Perl for this.

**Comment by ilovezfs** [comment]
No one is actively working on this but we'd be happy to review a PR.
