### ISSUE TITLE
Error from gnupg 

### ISSUE THREAD

**Issue by telemachus** [Homebrew/homebrew-core#87844]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.2.17-133-g890190c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 890190c0f30b36512835c846be004b0253b062ad
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4ce403b712895db306f2aa1850b6bbb4f5a57d08
Core tap last commit: 47 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit icelake
Clang: 13.0.0 build 1300
Git: 2.33.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.0


```shell
$ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to use `gpg` and `gopass` (which relies on `gpg` and `gpgconf`).

### What happened (include all command output)?

```shell
$ gpg --list-keys
gpg: error reading symlink '/proc/curproc/file': No such file or directory
...
```

The same thing happens if any program invokes `gpgconf`. Here's an example.

```shell
$ gopass -c tech/github
gpgconf: error reading symlink '/proc/curproc/file': No such file or directory
gpg: error reading symlink '/proc/curproc/file': No such file or directory
✔ Copied tech/imp to clipboard. Will clear in 45 seconds.
```

### What did you expect to happen?

I expected no error from `gpgconf` and `gpg`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Update `gpg` to the latest version (2.3.3) and try `gpg --list-keys`, `gpg --version` or any other command.
```

**Comment by carlocab** [comment]
The upstream developers say that this error is harmless. It would be nice to see it fixed, but that needs to be done in the upstream project and not here.

See https://dev.gnupg.org/T5656.
