### ISSUE TITLE
`brew upgrade gcc` takes over 10 hours on 2014 MBP, core i5

### ISSUE THREAD

**Issue by kochhar** [Homebrew/homebrew-core#8796]
Hi, I've been trying to upgrade my install of octave after readline got updated. As part of that upgrade, homebrew upgrades gcc. This gcc install has been running for about 10 hours now on my MBP. 

I cancelled it once after 45 minutes and then started it again. Here's the gist from the cancelled run. Maybe it can be helpful to figure out why it's taking so long to upgrade gcc.

https://gist.github.com/kochhar/9dfdf9eb27dbd5d87fb3e2b2dfb8ff3b

Any guidance on what to do to speed this up would be very helpful.
Thanks!

**Comment by ilovezfs** [comment]
That's odd. How full is the drive?

**Comment by fxcoudert** [comment]
A full build of GCC from source takes 2-3 hours on my 2.5 GHz Intel Core i7. If your machine is somewhat slower, has lower memory, has CPU-intensive tasks running at the same time, and especially if the hard drive or filesystem is slow (networked file system, by any chance?) this could be it.

From the log files you attached, it seems to be proceeding fine. It had started the second build stage (out of three) after 45 minutes, which is reasonable.

**Comment by kochhar** [comment]
The complete build ran for 677 minutes.

The drive has about 36GB of 256GB free, about 85% full.

**Comment by ilovezfs** [comment]
That seems excessive. You could try building gcc@5 and see if it's equally crazy.

**Comment by dunn** [comment]
Did GCC 5 build in a reasonable time?

**Comment by ilovezfs** [comment]
Closing for now, but please let us know if this is still a problem.

**Comment by jordanrye** [comment]
This is still a problem for me. My 2015 MacBook Pro is running macOS 10.13.3, and has a 2.7 GHz Intel Core i5 with 8GB RAM. Not sure why the brew upgrade is taking so long...

```
Warning: Building gcc from source:
  The bottle needs the Xcode CLT to be installed.
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-7.3.0/gcc-7.3.0.tar.xz
Already downloaded: /Users/jordanrye/Library/Caches/Homebrew/gcc-7.3.0.tar.xz
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/e9e
Already downloaded: /Users/jordanrye/Library/Caches/Homebrew/gcc--patch-863957f90a934ee8f89707980473769cff47ca0663c3906992da6afb242fb220.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/df0
Already downloaded: /Users/jordanrye/Library/Caches/Homebrew/gcc--patch-f7772a6ba73f44a6b378e4fe3548e0284f48ae2d02c701df1be93780c1607074.patch
==> Patching
==> Applying 6.1.0-jit.patch
patching file gcc/jit/Make-lang.in
==> Applying apfs.patch
patching file libstdc++-v3/include/Makefile.in
Hunk #1 succeeded at 1763 (offset -1 lines).
==> ../configure --build=x86_64-apple-darwin17.4.0 --prefix=/usr/local/Cellar/
==> make
```

The upgrade has taken approximately 2 hours so far.

**Comment by ilovezfs** [comment]
Install the CLT and you can use the bottle.

**Comment by BanuSelinTosun** [comment]
I just did the upgrade and it felt like it took forever, though it apparently took 49 minutes 39 seconds. I have the newest macbook pro. I am giving time it took as a reference. I have 16 GB CPU.

**Comment by moon03432** [comment]
as @ilovezfs, install/upgrade Xcode Command Line Tools by xcode-select --install
