### ISSUE TITLE
hunspell should depend on gettext runtime when installing via bottle

### ISSUE THREAD

**Issue by aethanyc** [Homebrew/homebrew-core#8807]
# Please follow the general troubleshooting steps first:
- [x]  Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
After installing hunspell by `brew install hunspell`, I run it and got the following error.
```
$ hunspell -D
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /usr/local/bin/hunspell
  Reason: image not found
Abort trap: 6
```

**Comment by ilovezfs** [comment]
Closed via #8811.

**Comment by aethanyc** [comment]
@ilovezfs Thank you for fixing this.

**Comment by ilovezfs** [comment]
@aethanyc thanks for reporting it!
