### ISSUE TITLE
Fortran M1 chip OS Monterey

### ISSUE THREAD

**Issue by soumyadipf90** [Homebrew/homebrew-core#88336]
### Provide a detailed description of the proposed feature

I am using fortran for math programs , But this is not available for new Mac OS Monterey . I am getting a error - ld: warning: dylib (/opt/homebrew/Cellar/gcc/11.2.0/lib/gcc/11/libgfortran.dylib) was built for newer macOS version (11.4) than being linked (11.0). 
 

### What is the motivation for the feature?

Mathematics and Physics 

### How will the feature be relevant to at least 90% of Homebrew users?

YES . it will be very usefull.

### What alternatives to the feature have been considered?

nothing .

**Comment by SMillerDev** [comment]
Please post the output of `brew config` and `brew doctor`

**Comment by carlocab** [comment]
GCC fails to build on macOS Monterey. You can find the build log [here](https://github.com/Homebrew/homebrew-core/runs/3986032679?check_suite_focus=true).

We'll review a pull request to fix this. A minimal set of patches from https://github.com/iains/gcc-darwin-arm64 would be acceptable.

**Comment by carlocab** [comment]
Also, the `ld` warning is, in general, relatively harmless. You should be able to do most things by installing the bottle built on Big Sur.

**Comment by soumyadipf90** [comment]
> Please post the output of `brew config` and `brew doctor`

-MacBook-Pro trial % brew config
HOMEBREW_VERSION: 3.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5889b44a6031af91b14ee7c7805e64d1b10ad51c
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 42d9ec0e66418cef4f4b6817cd2ea0ca642b9830
Core tap last commit: 23 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
Rosetta 2: false
soumyadipsahoo@soumyadips-MacBook-Pro trial % brew doctor
here is it .

**Comment by soumyadipf90** [comment]
> GCC fails to build on macOS Monterey. You can find the build log [here](https://github.com/Homebrew/homebrew-core/runs/3986032679?check_suite_focus=true).
> 
> We'll review a pull request to fix this. A minimal set of patches from https://github.com/iains/gcc-darwin-arm64 would be acceptable.

I thik a new version of gcc will come to fix this issue ??? am I right ?

**Comment by carlocab** [comment]
Eventually. It will take some time though.

**Comment by SMillerDev** [comment]
GCC doesn't officially work on ARM yet so patching for ARM on Monterey won't happen either.

**Comment by SMillerDev** [comment]
Did `brew doctor` really not output anything?
