### ISSUE TITLE
wine --devel: wine does not find several libraries

### ISSUE THREAD

**Issue by iolojz** [Homebrew/homebrew-core#8846]
`brew config`:
https://gist.github.com/iolojz/dcc02e699952fd22528e51357bb36633

`brew doctor`:
https://gist.github.com/iolojz/a8e13e7caf8875fbae2432e95e182b5f

Installing `wine --devel` works without any problems but since wine-2.0 (possibly rc-1 or 2, I do not remember) running virtually any wine command e.g `winecfg`gives several errors:

** Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5. **

** err:wincodecs:PngDecoder_CreateInstance Failed reading PNG because unable to find libpng16.16.dylib **

This did not (!) happen prior to `wine-2.0`.

As a partial workaround I execute
`export DYLD_FALLBACK_LIBRARY_PATH=/pkgmanagers/homebrew/lib`

but that only fixes the issue for windows executables run in the current directory e.g
`/pkgmanagers/homebrew/bin/wine HD_Launcher.exe`
and __not__ e.g
`/pkgmanagers/homebrew/bin/winecfg`

Hence I conclude that something concerning library search paths has been changed in an obstructive manner. I am aware of my non-standard homebrew installation prefix, but since this used to work, this is definitely a regression.

**Comment by MikeMcQuaid** [comment]
This seems like something that should be reported to the upstream Wine project. I strongly suspect this is due to your non-/usr/local prefix, yeh.

**Comment by iolojz** [comment]
After a little investigating, I agree with you. What surprises me is that it used to work at all...
The problem is macOS's behaviour to not remember library paths after linking, along with SIP which prohibits propagation of DYLD_* environment variables to child processes.

**Comment by ilovezfs** [comment]
@iolojz that makes it an upstream bug that should be fixed. They'll need to update the build system to hard code the full paths to adapt to SIP.

**Comment by iolojz** [comment]
@ilovezfs I reported it upstream in https://bugs.winehq.org/show_bug.cgi?id=42481
But I seriously doubt they are going to fix this, because it really only shows up, when
(a) The libs are in a non-standard location
(b) The libs are not located in `@loader_path/../lib`

A possible workaround is to run

    install_name_tool -add_rpath /homebrew/library/path /path/to/wine/binary

which could be easily embedded into the wine homebrew script though ;)

**Comment by ilovezfs** [comment]
If their configure script is going to support "non-standard" locations, then they might want to consider not expecting those to break ... always.
