### ISSUE TITLE
Homepage is not reachable audit failures

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-core#8847]
To test `brew audit --online foo`

- [x] amdatu-bootstrap:
  * The homepage http://amdatu.org/bootstrap/intro.html is not reachable (HTTP status code 404)
- [x] ansible:
  * The homepage https://www.ansible.com/ is not reachable (HTTP status code 403)
- [x] ansible@1.9:
  * The homepage http://www.ansible.com is not reachable (HTTP status code 403)
- [x] ansible@2.0:
  * The homepage https://www.ansible.com/ is not reachable (HTTP status code 403)
- [x] apel:
  * The homepage http://git.chise.org/elisp/apel/ is not reachable (HTTP status code 404)
- [x] apg: (https://github.com/Homebrew/homebrew-boneyard/pull/280)
  * The homepage http://www.adel.nursat.kz/apg/ is not reachable (HTTP status code 000)
- [x] apt-dater:
  * The homepage https://www.ibh.de/apt-dater/ is not reachable (HTTP status code 404)
- [x] autocode:
  * The homepage https://autocode.run is not reachable (HTTP status code 000)
- [x] berkeley-db:
  * The homepage https://www.oracle.com/technology/products/berkeley-db/index.html is not reachable (HTTP status code 302)
- [x] berkeley-db4:
  * The homepage https://www.oracle.com/technology/products/berkeley-db/index.html is not reachable (HTTP status code 302)
- [x] bip: (https://github.com/Homebrew/homebrew-boneyard/pull/281)
  * The homepage https://bip.milkypond.org is not reachable (HTTP status code 000)
- [x] chipmunk:
  * The homepage https://chipmunk-physics.net/ is not reachable (HTTP status code 000)
- [x] clens:
  * The homepage https://opensource.conformal.com/wiki/clens is not reachable (HTTP status code 000)
- [x] dbxml:
  * The homepage https://www.oracle.com/us/products/database/berkeley-db/xml/overview/index.html is not reachable (HTTP status code 302)
- [x] dirac:
  * The homepage http://diracvideo.org/ is not reachable (HTTP status code 000)
- [x] dnsrend:
  * The homepage http://romana.now.ie/dnsrend is not reachable (HTTP status code 000)
- [x] echoprint-codegen:
  * The homepage http://echoprint.me is not reachable (HTTP status code 000)
- [x] edelta: (https://github.com/Homebrew/homebrew-boneyard/pull/282)
  * The homepage http://www.diku.dk/hjemmesider/ansatte/jacobg/edelta/ is not reachable (HTTP status code 404)
- [x] esound: (https://github.com/Homebrew/homebrew-boneyard/pull/283)
  * The homepage http://www.tux.org/~ricdude/EsounD.html is not reachable (HTTP status code 301)
- [x] gnome-doc-utils: (https://github.com/Homebrew/homebrew-core/pull/10137)
  * The homepage https://live.gnome.org/GnomeDocUtils is not reachable (HTTP status code 404)
- [x] grt:
  * The homepage https://www.nickgillian.com/wiki/pmwiki.php/GRT/GestureRecognitionToolkit is not reachable (HTTP status code 404)
- [x] htpdate:
  * The homepage http://www.vervest.org/fiki/bin/view/HTP is not reachable (HTTP status code 404)
- [x] irods: (https://github.com/Homebrew/homebrew-core/pull/10138)
  * The homepage https://www.irods.org is not reachable (HTTP status code 000)
- [x] jetty-runner:
  * The homepage https://www.eclipse.org/jetty/documentation/9.3.10.v20160621/runner.html is not reachable (HTTP status code 404)
- [x] lcab: (https://github.com/Homebrew/homebrew-boneyard/pull/284)
  * The homepage http://ohnopub.net/~ohnobinki/lcab/ is not reachable (HTTP status code 000)
- [x] libhdhomerun: (https://github.com/Homebrew/homebrew-core/pull/10184)
  * The homepage https://www.silicondust.com/support/downloads/linux/ is not reachable (HTTP status code 404)
- [x] libmonome: (https://github.com/Homebrew/homebrew-core/pull/10187)
  * The homepage http://illest.net/libmonome/ is not reachable (HTTP status code 000)
- [x] libnfc:
  * The homepage http://www.libnfc.org/ is not reachable (HTTP status code 000)
- [x] malaga: (https://github.com/Homebrew/homebrew-boneyard/pull/285)
  * The homepage http://home.arcor.de/bjoern-beutel/malaga/ is not reachable (HTTP status code 404)
- [x] mecab-ipadic: (https://github.com/Homebrew/homebrew-core/pull/10191)
  * The homepage https://mecab.googlecode.com/svn/trunk/mecab/doc/index.html is not reachable (HTTP status code 404)
- [x] mecab-jumandic: (https://github.com/Homebrew/homebrew-core/pull/10193)
  * The homepage https://mecab.googlecode.com/svn/trunk/mecab/doc/index.html is not reachable (HTTP status code 404)
- [x] partio: (https://github.com/Homebrew/homebrew-core/pull/10196)
  * The homepage http://www.partio.us is not reachable (HTTP status code 404)
- [x] probatron4j: (https://github.com/Homebrew/homebrew-boneyard/pull/286)
  * The homepage http://www.probatron.org is not reachable (HTTP status code 000)
- [x] rhash:
  * The homepage http://rhash.anz.ru/ is not reachable (HTTP status code 000)
- [x] riak:
  * The homepage https://basho.com/products/#riak is not reachable (HTTP status code 000)
- [x] rlwrap: (https://github.com/Homebrew/homebrew-core/pull/10199)
  * The homepage http://utopia.knoware.nl/~hlub/rlwrap/ is not reachable (HTTP status code 000)
- [x] rtpbreak: (https://github.com/Homebrew/homebrew-boneyard/pull/287)
  * The homepage http://www.dallachiesa.com/code/rtpbreak/doc/rtpbreak_en.html is not reachable (HTTP status code 000)
- [x] schroedinger: (https://github.com/Homebrew/homebrew-core/pull/10202)
  * The homepage http://diracvideo.org/ is not reachable (HTTP status code 000)
- [x] sha2:
  * The homepage https://aarongifford.com/computers/sha.html is not reachable (HTTP status code 000)
- [x] slimerjs:
  * The homepage https://slimerjs.org/ is not reachable (HTTP status code 000)
- [x] spandsp: (https://github.com/Homebrew/homebrew-core/pull/10204)
  * The homepage https://www.soft-switch.org/ is not reachable (HTTP status code 000)
- [x] ssreflect:
  * The homepage https://www.msr-inria.fr/projects/mathematical-components-2/ is not reachable (HTTP status code 000)
- [x] taskd: (https://github.com/Homebrew/homebrew-core/pull/10205)
  * The homepage https://taskwarrior.org/projects/show/taskwarrior is not reachable (HTTP status code 404)
- [x] termshare: (https://github.com/Homebrew/homebrew-core/pull/10206)
  * The homepage https://termsha.re is not reachable (HTTP status code 000)
- [x] unpaper:
  * The homepage https://www.flameeyes.eu/projects/unpaper is not reachable (HTTP status code 403)

**Comment by geoffmacintosh** [comment]
- https://www.ansible.com/ seems to work fine for me in Safari, but `brew audit --online ansible` gives an error.

- apel 10.8 was updated [six years](http://git.chise.org/gitweb/?p=elisp/apel.git;a=summary) and it looks like the host website was last updated at a similar time. Not sure what to do there.

**Comment by ilovezfs** [comment]
>but brew audit --online ansible gives an error.

Yeah, it's caused by the user-agent string we're passing for some reason.

**Comment by geoffmacintosh** [comment]
I can go through the rest of the list and maybe make a new list of the ones that are just failing `audit --online`, and try and correct the ones that need updating.

**Comment by ilovezfs** [comment]
That would be great.

**Comment by geoffmacintosh** [comment]
**Fails Audit, Website Accessible**
- ansible https://www.ansible.com/

**Dead Website, No Obvious Replacement**
- apel
  Hasn't been updated in six year, host website looks about the same vintage.
- apg
  This package actually completely fails to build from source because the site is gone. The site is a subdomain of a Kazakhstan ISP, so the author probably changed internet providers? The current version of apg was last updated in 2003, so maybe the project is over.

**Comment by geoffmacintosh** [comment]
If a project won't build from source because the source location is gone with no replacement, what should I do?

**Comment by fxcoudert** [comment]
- libnfc homepage should be https://github.com/nfc-tools/libnfc
- libmonome homepage should be https://github.com/monome/libmonome
- rlwrap homepage should be https://github.com/hanslub42/rlwrap
- termshare homepage should be https://github.com/progrium/termshare

**Comment by ilovezfs** [comment]
@fxcoudert looks like libnfc is now actually http://nfc-tools.org/index.php?title=Main_Page

**Comment by woodruffw** [comment]
For `homepage`s that perform user-agent filtering, we could add a `no_robots` param that `audit` can check against (unless changing our user-agent to something more relaxed is preferable).

**Comment by ilovezfs** [comment]
I think the test should just try with and without the user agent before giving up as opposed to cluttering the DSL.

**Comment by MikeMcQuaid** [comment]
Yeh, 👎 to DSL changes. We should already be using a Safari user-agent for these so it's maybe not precise enough.

**Comment by MikeMcQuaid** [comment]
If someone points me to one or more that barf on the current user agent then I'll fix them up.

**Comment by ilovezfs** [comment]
ansible and dbxml

**Comment by ilovezfs** [comment]
OK, refreshed the list now that Homebrew/brew#1917 was merged. 19/45 completed!

**Comment by ilovezfs** [comment]
Thank you to everyone who helped with this! All done.
