### ISSUE TITLE
brew install tesseract --HEAD fails 

### ISSUE THREAD

**Issue by jreeder** [Homebrew/homebrew-core#88662]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.2-33-gcb32066
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: cb32066938128fedf4619ddab41a5888d6ed4178
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 39f877370d1b0087fe71349d16494aeaca6ffeee
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.7rz4Bpa1B7/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.31.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: 13.1
XQuartz: 2.7.11 => /opt/X11

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libboost_atomic.dylib
  /usr/local/lib/libboost_context.dylib
  /usr/local/lib/libboost_locale.dylib
  /usr/local/lib/libboost_python.dylib
  /usr/local/lib/libboost_signals.dylib
  /usr/local/lib/libboost_thread.dylib
  /usr/local/lib/libjzmq.0.dylib
  /usr/local/lib/libwkhtmltox.0.12.3.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/wkhtmltox/image.h
  /usr/local/include/wkhtmltox/pdf.h

Warning: Unbrewed '.la' files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.la' files:
  /usr/local/lib/libjzmq.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libboost_atomic.a
  /usr/local/lib/libboost_context.a
  /usr/local/lib/libboost_locale.a
  /usr/local/lib/libboost_python.a
  /usr/local/lib/libboost_thread.a
  /usr/local/lib/libjzmq.a

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  tesseract
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install tesseract --HEAD. The formula for tesseract has 'master' listed as the head branch. The actual main branch of tesseract is 'main'. The formula needs to be updated to match the tesseract repos actual branch name. 

### What happened (include all command output)?

brew install tesseract --HEAD
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 35 formulae.
==> Updated Casks
Updated 22 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/autoconf-archive/manifests/2021.02.19
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/33b22a1db6585516ee8bd46d8df6943e34164731d389f79924dabecc29066575--autoconf-archive-2021.02.19.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/autoconf-archive/blobs/sha256:c86fcd19fecc5c52847daebba5f81c768eb2d1c3f
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/144b736aa317bbf911cd38493db4d511cdaf8926694eafafd42dc5ec185596bb--autoconf-archive--2021.02.19.big_sur.bottle.tar.gz
==> Downloading https://github.com/tesseract-ocr/tesseract/commit/6dc4b184b1ebf2e68461f6b63f63a033bc7245f7.patch?full_in
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/c80b4f9e82ce5b6a255ebab539cc38bb0c0d8a719d4e15170b777315adb58e15--6dc4b184b1ebf2e68461f6b63f63a033bc7245f7.patch
==> Downloading https://github.com/tesseract-ocr/tessdata_fast/raw/4.0.0/eng.traineddata
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/43826098cb7f5ea003b3ea7e4cce9d6dc7196455e5e820328293b7a2527d6ea6--eng.traineddata
==> Downloading https://github.com/tesseract-ocr/tessdata_fast/raw/4.0.0/osd.traineddata
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/bdfdc11a762146c0299e465db8f7f1257df15fa6cca350aca0c773ca11963e6d--osd.traineddata
==> Downloading https://github.com/USCDataScience/counterfeit-electronics-tesseract/raw/319a6eeacff181dad5c02f3e7a3aff80
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/af723acced8e05eefe19f8b6a9a0c83eaf9d0099c86d61c3257e4b83b3572cdb--snum.traineddata
==> Downloading https://raw.githubusercontent.com/tesseract-ocr/test/6dd816cdaf3e76153271daf773e562e24c928bf5/testing/eu
Already downloaded: /Users/jreeder/Library/Caches/Homebrew/downloads/f3f26f43cd4722b27521ab0c64cbd2a167f7758e730286cf06c74d21efb27f4f--eurotext.tif
==> Cloning https://github.com/tesseract-ocr/tesseract.git
Cloning into '/Users/jreeder/Library/Caches/Homebrew/tesseract--git'...
fatal: Remote branch master not found in upstream origin
Error: tesseract: Failed to download resource "tesseract"
Failure while executing; `git clone --branch master -c advice.detachedHead=false https://github.com/tesseract-ocr/tesseract.git /Users/jreeder/Library/Caches/Homebrew/tesseract--git` exited with 128. Here's the output:
Cloning into '/Users/jreeder/Library/Caches/Homebrew/tesseract--git'...
fatal: Remote branch master not found in upstream origin

### What did you expect to happen?

Install tesseract --HEAD

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install tesseract --HEAD
```

**Comment by carlocab** [comment]
Thanks for the report. Note that we don't support source builds. This includes `--HEAD` installs, since that requires building from source.

However, since this is an easy enough fix, I've opened #88669 for you. In the future, please avoid opening issues for problems related to `--HEAD` installs and make a pull request instead.
