### ISSUE TITLE
brew install neovim --HEAD fails on macOS Monterey

### ISSUE THREAD

**Issue by nyngwang** [Homebrew/homebrew-core#88665]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9daf5e2d28396c7a4379605e89e029d9fccb41e6
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 48f05442691c98abc1cf41cf1942640305f2cc63
Core tap last commit: 87 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-x86_64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1

----

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  docker-machine

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Applications/Postgres.app/Contents/Versions/latest/bin/gdal-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  cypher-shell
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?
```shell
brew upgrade --fetch-HEAD
```

or after uninstall neovim I also tried:

```shell
brew install neovim --HEAD
```

and both failed

### What happened (include all command output)?

==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.8/libmpack-lua-1.0.8.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/4b91349796a66e38e93acd77e6ca14212c869090429fd88271def2be5293d83f--libmpack-lua-1.0.8.tar.gz
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.2-1.src.rock
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/0bc17975f0cf3981083172aa7da329b874e5780fa81494f5dd07d0665fcec23b--lpeg-1.0.2-1.src.rock
==> Cloning https://github.com/neovim/neovim.git
Updating /Users/me/Library/Caches/Homebrew/neovim--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7899c4099 docs(lsp): correct usage examples of formatexpr (#16216)
==> luarocks make --lua-dir=/usr/local/opt/luajit-openresty --tree=/private/tmp/neovim-20211103-75787-zm3uzo/deps-build
==> luarocks make --lua-dir=/usr/local/opt/luajit-openresty --tree=/private/tmp/neovim-20211103-75787-zm3uzo/deps-build
==> cmake .. -DLIBLUV_LIBRARY=/usr/local/opt/luv/lib/libluv.dylib
==> make install
Last 15 lines from /Users/me/Library/Logs/Homebrew/neovim/04.make:
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/ui.c.o
cd /tmp/neovim-20211103-75787-zm3uzo/build/src/nvim && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/tmp/neovim-20211103-75787-zm3uzo/build/config -I/tmp/neovim-20211103-75787-zm3uzo/src -I/tmp/neovim-20211103-75787-zm3uzo/build/src/nvim/auto -I/tmp/neovim-20211103-75787-zm3uzo/build/include -I/usr/local/opt/luajit-openresty/include/luajit-2.1 -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto=thin -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -MD -MT src/nvim/CMakeFiles/nvim.dir/ui.c.o -MF CMakeFiles/nvim.dir/ui.c.o.d -o CMakeFiles/nvim.dir/ui.c.o -c /tmp/neovim-20211103-75787-zm3uzo/src/nvim/ui.c
/tmp/neovim-20211103-75787-zm3uzo/src/nvim/terminal.c:818:29: error: passing 'VTermStringFragment' to parameter of incompatible type 'char *'
    buf_set_term_title(buf, val->string);
                            ^~~~~~~~~~~
/tmp/neovim-20211103-75787-zm3uzo/src/nvim/terminal.c:789:50: note: passing argument to parameter 'title' here
static void buf_set_term_title(buf_T *buf, char *title)
                                                 ^
1 error generated.
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/ui_bridge.c.o
cd /tmp/neovim-20211103-75787-zm3uzo/build/src/nvim && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/tmp/neovim-20211103-75787-zm3uzo/build/config -I/tmp/neovim-20211103-75787-zm3uzo/src -I/tmp/neovim-20211103-75787-zm3uzo/build/src/nvim/auto -I/tmp/neovim-20211103-75787-zm3uzo/build/include -I/usr/local/opt/luajit-openresty/include/luajit-2.1 -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto=thin -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -MD -MT src/nvim/CMakeFiles/nvim.dir/ui_bridge.c.o -MF CMakeFiles/nvim.dir/ui_bridge.c.o.d -o CMakeFiles/nvim.dir/ui_bridge.c.o -c /tmp/neovim-20211103-75787-zm3uzo/src/nvim/ui_bridge.c
make[2]: *** [src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/nvim/CMakeFiles/nvim.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

### What did you expect to happen?

Install neovim nightly correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade --fetch-HEAD
```

or 

```shell
brew install neovim --HEAD
```

**Comment by nyngwang** [comment]
I also tried another macOS Big Sur version 11.4 (all other hardware specs are the same), and it also failed with the same error message. So I consider it a bug not specific to macOS Monterey.

**Comment by zeertzjq** [comment]
I think currently Nvim is currently incompatible with libvterm 0.2.

**Comment by NikZak** [comment]
As a workaround. Building from source works fine
https://github.com/neovim/neovim/wiki/Building-Neovim

**Comment by carlocab** [comment]
Does building the stable tarball from source also fail?

**Comment by carlocab** [comment]
This might help.
```diff
diff --git a/Formula/neovim.rb b/Formula/neovim.rb
index d6db870291a..c8a576d4d60 100644
--- a/Formula/neovim.rb
+++ b/Formula/neovim.rb
@@ -47,6 +47,8 @@ class Neovim < Formula
     sha256 "e0d0d687897f06588558168eeb1902ac41a11edd1b58f1aa61b99d0ea0abbfbc"
   end
 
+  patch :DATA
+
   def install
     resources.each do |r|
       r.stage(buildpath/"deps-build/build/src/#{r.name}")
@@ -87,3 +89,17 @@ class Neovim < Formula
     assert_equal "Hello World from Neovim!!", (testpath/"test.txt").read.chomp
   end
 end
+
+__END__
+diff --git a/src/nvim/terminal.c b/src/nvim/terminal.c
+index fb025265f..52d13fe4f 100644
+--- a/src/nvim/terminal.c
++++ b/src/nvim/terminal.c
+@@ -815,7 +815,7 @@ static int term_settermprop(VTermProp prop, VTermValue *val, void *data)
+
+   case VTERM_PROP_TITLE: {
+     buf_T *buf = handle_get_buffer(term->buf_handle);
+-    buf_set_term_title(buf, val->string);
++    buf_set_term_title(buf, val->string.str);
+     break;
+   }
```
Let me know if it works.

**Comment by nyngwang** [comment]
> I think currently Nvim is incompatible with libvterm 0.2.

@zeertzjq Could you help me on which command should I use to install the version `@0.1.4`? I run `brew install libvterm@0.1.4` but got error.

**Comment by zeertzjq** [comment]
Sorry, I haven't used macOS and Homebrew for many years.

**Comment by nyngwang** [comment]
Never mind. I just found that `brew search ...` will list all versions when they exist. But `libvterm` doesn't provide a down-graded version since it is not listed. OK, I think I will just use `neovim@0.5.1` for now.

**Comment by zeertzjq** [comment]
May be fixed by <https://github.com/neovim/neovim/pull/16219>.

**Comment by carlocab** [comment]
This should be fixed now.

**Comment by bigjazzsound** [comment]
I'm getting a different error now:

```
[ 50%] Building C object src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o
cd /tmp/neovim-20211103-63315-zxjo95/build/src/nvim && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DINCLUDE_GENERATED_DECLARATIONS -DMIN_LOG_LEVEL=3 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -Dnvim_EXPORTS -I/tmp/neovim-20211103-63315-zxjo95/build/config -I/tmp/neovim-20211103-63315-zxjo95/src -I/tmp/neovim-20211103-63315-zxjo95/build/src/nvim/auto -I/tmp/neovim-20211103-63315-zxjo95/build/include -I/usr/local/opt/luajit-openresty/include/luajit-2.1 -isystem /usr/local/opt/gettext/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -flto=thin -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -MD -MT src/nvim/CMakeFiles/nvim.dir/tui/terminfo.c.o -MF CMakeFiles/nvim.dir/tui/terminfo.c.o.d -o CMakeFiles/nvim.dir/tui/terminfo.c.o -c /tmp/neovim-20211103-63315-zxjo95/src/nvim/tui/terminfo.c
/tmp/neovim-20211103-63315-zxjo95/src/nvim/terminal.c:818:29: error: passing 'VTermStringFragment' to parameter of incompatible type 'char *'
    buf_set_term_title(buf, val->string);
                            ^~~~~~~~~~~
/tmp/neovim-20211103-63315-zxjo95/src/nvim/terminal.c:789:50: note: passing argument to parameter 'title' here
static void buf_set_term_title(buf_T *buf, char *title)
                                                 ^
1 error generated.
gmake[2]: *** [src/nvim/CMakeFiles/nvim.dir/build.make:3289: src/nvim/CMakeFiles/nvim.dir/terminal.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/private/tmp/neovim-20211103-63315-zxjo95/build'
gmake[1]: *** [CMakeFiles/Makefile2:3927: src/nvim/CMakeFiles/nvim.dir/all] Error 2
gmake[1]: Leaving directory '/private/tmp/neovim-20211103-63315-zxjo95/build'
gmake: *** [Makefile:159: all] Error 2
```

**Comment by carlocab** [comment]
Isn't that the same error? Have you done `brew update`? If you haven't, please do that first then try again. If you have, do it again and then also do `brew uninstall libvterm` and try again.

**Comment by bigjazzsound** [comment]
Can confirm that worked for me.

In case anyone else needs the steps:

```
brew uninstall neovim
brew uninstall --force libvterm
brew install neovim --head
```

**Comment by carlocab** [comment]
`brew unlink libvterm` instead of `brew uninstall --force libvterm` will also work.

**Comment by nyngwang** [comment]
@carlocab Thank you so much! It works now! Happy neovim!
