### ISSUE TITLE
Freecad sha256 mismatch problem for pyside2.rb

### ISSUE THREAD

**Issue by neurodigitaltechnologies** [Homebrew/homebrew-core#88791]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.2-50-geca16a2
ORIGIN: https://github.com/Homebrew/brew
HEAD: eca16a2a3974c5e6cb6b65ac90a55613f2d0cbb4
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 41d893f6646ee39cf1ce87780d3d3c879b916705
Core tap last commit: 28 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1
Rosetta 2: false
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to build Freecad from source for arm64 (Apple M1 Max) using:
brew tap Freecad/freecad
brew install freecad

### What happened (include all command output)?

sha256 mismatch for pyside2

### What did you expect to happen?

Build success

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew tap Freecad/freecad
brew install freecad
```

**Comment by Bo98** [comment]
This is up to the maintainers of the `Freecad/freecad` tap to fix. They have their own `pyside2` formula.
