### ISSUE TITLE
Cmake file to build (required by libssh2 which is required by Rust)

### ISSUE THREAD

**Issue by hfiguiere** [Homebrew/homebrew-core#890]
# Please follow the general troubleshooting steps first:

- [ x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

````
$ brew install rust
Warning: You are using OS X 10.8.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Installing dependencies for rust: cmake, libssh2
==> Installing rust dependency: cmake
==> Downloading https://cmake.org/files/v3.5/cmake-3.5.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/cmake-3.5.2.tar.gz
==> ./bootstrap --prefix=/usr/local/Cellar/cmake/3.5.2 --no-system-libs --parallel=2 --datadir=/share/cmake --docdir=/share/doc/cmake
Last 15 lines from /Users/hub/Library/Logs/Homebrew/cmake/01.bootstrap:
  file STRINGS file
  "/Library/Frameworks/Gtk.framework/Headers/gtk/gtk/gtkversion.h" cannot be
  read.
Call Stack (most recent call first):
  Modules/FindGTK2.cmake:880 (_GTK2_GET_VERSION)
  Tests/CMakeLists.txt:1402 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/cmake-20160505-65626-kq0xoc/cmake-3.5.2/CMakeFiles/CMakeOutput.log".
See also "/tmp/cmake-20160505-65626-kq0xoc/cmake-3.5.2/CMakeFiles/CMakeError.log".
---------------------------------------------
Error when bootstrapping CMake:
Problem while running initial CMake
---------------------------------------------

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues
````

`brew gist-logs cmake`
https://gist.github.com/9388395dcbcb210c3bf3d33324bd304e

**Comment by hfiguiere** [comment]
````
sudo rm -fr /Library/Frameworks/Gtk.framework
````
Resolved the problem.

**Comment by ilovezfs** [comment]
Do you know where that came from?

**Comment by hfiguiere** [comment]
probably installed at one point in the past. There was a "Gtk.framework". File date was 2010...

**Comment by hfiguiere** [comment]
bug is also probably in cmake.

**Comment by ilovezfs** [comment]
Yup, cake, brew superenv, or both.

**Comment by DomT4** [comment]
This came up once last year as well. We could add it to the `doctor` output warning people it'll cause trouble (where it exists), but I'm not sure two cases in a year merits that treatment just yet.

**Comment by ilovezfs** [comment]
@DomT4 perhaps superenv should set CMAKE_FRAMEWORK_PATH explicitly.

**Comment by ilovezfs** [comment]
Hmm looks like it does
https://github.com/Homebrew/brew/blob/36b2af2e0f5a72f0eccdec0c929a89188dc0f0dc/Library/Homebrew/extend/ENV/super.rb#L62

but somehow `/Library/Frameworks` sneaks in anyway.

**Comment by ilovezfs** [comment]
Ah looks like superenv would actually need to set `CMAKE_SYSTEM_FRAMEWORK_PATH` explicitly in order to exclude `/Library/Frameworks`.

**Comment by ilovezfs** [comment]
Closing since it's unlikely we'll want to override `CMAKE_SYSTEM_FRAMEWORK_PATH`.

**Comment by UniqMartin** [comment]
Possibly related: Homebrew/brew#72 (better integration of CMake with `superenv`).

**Comment by tdsmith** [comment]
Why not, @ilovezfs? Apple doesn't put anything in /Library.
