### ISSUE TITLE
Formula 'minetest' does not link application in Spotlight

### ISSUE THREAD

**Issue by darkspirit510** [Homebrew/homebrew-core#89001]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs minetest
Error: No logs.

brew doctor
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the getantibody/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/getantibody/homebrew-tap/Formula/antibody.rb:6

Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I ran `brew install minetest` and searched for minetest in Spotlight.

### What happened (include all command output)?

It installed, no error messages. Can't find minetest in Spotlight.

### What did you expect to happen?

Can run minetest via Spotlight (worked in 2020)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install minetest
```

**Comment by SMillerDev** [comment]
Unless you index your homebrew prefix this is entirely expected
