### ISSUE TITLE
Installation of virtual IPs in strongSwan fails on macOS Monterey/12

### ISSUE THREAD

**Issue by tobiasbrunner** [Homebrew/homebrew-core#89022]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
# Happens at runtime, so is not related to any `brew` commands.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Initiate a VPN connection that previously worked on macOS before Monterey/12.

### What happened (include all command output)?

When initiating a connection with strongSwan the installation of virtual IPs fails with something like this:

```
Created TUN device: utun1
interface utun1 appeared
virtual IP 10.0.10.2 did not appear on utun1
installing virtual IP 10.0.10.2 failed
```

More information can be found in https://github.com/strongswan/strongswan/issues/707.

### What did you expect to happen?

The virtual IP should be detected on the created TUN device. But that doesn't happen because macOS 12 doesn't produce the required kernel event(s).

[This patch](https://github.com/Homebrew/homebrew-core/files/7503555/macos-12-tun-fix.txt) works around the issue by setting an MTU on the TUN device, which produces the kernel event required to detect the virtual IP. Note that it is not the actual patch in our repository, but instead applies to the 5.9.4 tarball (i.e. it patches two generated files instead of their source file). I'd have created a PR but I wasn't sure how to go about this for such patches.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install strongswan
# configure a connection and initiate it
```

**Comment by carlocab** [comment]
Please provide the requested information anyway. It's still important for tracking this bug. (e.g. another user might experience a similar problem but it would be much harder to ascertain whether it's this bug or not because there's no record of the version of the formula this issue refers to.)

**Comment by tobiasbrunner** [comment]
Unfortunately, I can't as I don't have a Mac.

**Comment by pieterwillaert** [comment]
@carlocab We're experiencing the same problems as the author. What information do you need exactly?

Strongswan Version 5.9.4
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/strongswan.rb

**Comment by carlocab** [comment]
The information requested in the issue template is a good start.

**Comment by pieterwillaert** [comment]
brew config

`HOMEBREW_VERSION: 3.3.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 819eea5669807c1cf29e0d29985fc765ad7a9597
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: d3ad8d4866091bed85594365d41338004bc436c8
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: 13.1
Rosetta 2: false`

**Comment by carlocab** [comment]
Thanks. Do you have reproduction steps that can be used by someone who doesn't use strongswan?

**Comment by carlocab** [comment]
Great, thanks for the info. Would you mind opening a pull request to apply the patch? Just `grep` for `patch do` in `"$(brew --repository homebrew/core)"` for many examples of this.
