### ISSUE TITLE
Require Xcode when upgrade wine without-win64

### ISSUE THREAD

**Issue by specter119** [Homebrew/homebrew-core#8926]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor` 

I install `wine` via `brew install wine --without-win64 --devel` but everytime it will require a full Xcode when I upgrade, I have to uninstall it and reinstall  again. 

```
$ brew config
HOMEBREW_VERSION: 1.1.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9cce3414fbd39d146d97911dbb3bf07fffaa1080
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b6d84f64d8ca0d8dc2ac107a3cc05a01040e700d
Core tap last commit: 3 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: 1.8.0_112
macOS: 10.12.2-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

$ brew doctor
Your system is ready to brew.
```

**Comment by MikeMcQuaid** [comment]
Unfortunately I'm not sure we can do anything about this as this is a (long-standing) bug with the way we handle optional requirements 😭
