### ISSUE TITLE
Ripgrep 0.4.0 fails to install due to SHA256 mismatch

### ISSUE THREAD

**Issue by geoffmacintosh** [Homebrew/homebrew-core#8940]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

[Brew gist-log for ripgrep](https://gist.github.com/geoffmacintosh/0a1ba133d4be66d3badb2a1b97338980). I think this doesn't give an accurate summary of the issue, so here's what happens:

When attempting to update ripgrep via `brew update` followed by `brew upgrade`, I get the following error:

```
Error: SHA256 mismatch
Expected: 794e57f83c0a1047d471341aaaeb23bbb094712d7eded95176c8ba35791f9814
Actual: 12d64b716a235f1826cba7ad615a55c68c1179c64138b1b0e1aec5601204b76e
Archive: /Users/gmac/Library/Caches/Homebrew/ripgrep-0.4.0.sierra.bottle.tar.gz
To retry an incomplete download, remove the file above.
Warning: Bottle installation failed: building from source.
==> Using the sandbox
==> Downloading https://github.com/BurntSushi/ripgrep/releases/download/0.4.0/ripgrep-0.4.0-x86_64-ap
Already downloaded: /Users/gmac/Library/Caches/Homebrew/ripgrep-0.4.0.tar.gz
==> cargo build --release
Last 15 lines from /Users/gmac/Library/Logs/Homebrew/ripgrep/01.cargo:
2017-01-15 10:52:04 -0700

cargo
build
--release

error: could not find `Cargo.toml` in `/private/tmp/ripgrep-20170115-8541-j119j5/ripgrep-0.4.0-x86_64-apple-darwin` or any parent directory

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

The gist-log shows the error in building from source, but doesn't mention that it's a hash-mismatch that seems to start all of the problems. I've tried deleting `/Users/gmac/Library/Caches/Homebrew/ripgrep-0.4.0.tar.gz` and `/Users/gmac/Library/Caches/Homebrew/ripgrep-0.4.0.sierra.bottle.tar.gz`, but they are just re-downloaded and the errors still occur. I then tried installing other formula from bottles, and none of them give me errors. 

Looking through ripgrep.rb, the hash for Sierra seems to match the "actual" hash in the error message.

Finally, I use Fish as my default shell, but running all the troubleshooting steps in bash give exactly the same output.

Brew doctor inline:
```
Your system is ready to brew.
```

Brew config inline:
```
HOMEBREW_VERSION: 1.1.7-17-g129607409
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1296074099c7e3f8a2c3b64c5badc7af106292bb
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 3c11f48e59c3359161b50ce584356b6618cdd9ee
Core tap last commit: 24 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/gmac/.rbenv/shims/ruby => /Users/gmac/.rbenv/versions/2.3.3/bin/ruby
Java: N/A
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: N/A
```

**Comment by MikeMcQuaid** [comment]
Try to `rm /Users/gmac/Library/Caches/Homebrew/ripgrep-0.4.0.sierra.bottle.tar.gz`; I can't reproduce this.
