### ISSUE TITLE
Process for `imagemagick@6`?

### ISSUE THREAD

**Issue by msbit** [Homebrew/homebrew-core#8954]
Just a quick question about the feasibility/process of getting `imagemagick ` (as of 6f014f2b7f1f9e618fd5c0ae9c93befea671f8be / 94b49b3f74be90e2bbcf0826778c4b1cde725b49) split off as `imagemagick@6`.

Would it be sufficient to generate a new formula with the contents of `./Formula/imagemagick.rb` from the former commit?

**Comment by ilovezfs** [comment]
See https://github.com/Homebrew/homebrew-core/pull/8756.

**Comment by msbit** [comment]
👌

**Comment by ilovezfs** [comment]
@msbit Just a heads up that we've now merged ImageMagick 6 as "imagemagick@6"

**Comment by msbit** [comment]
@ilovezfs thanks!
