### ISSUE TITLE
aalib: missing shared library

### ISSUE THREAD

**Issue by jwilk** [Homebrew/homebrew-core#89566]
The `aalib` formula passes `--enable-shared=yes` to the configure script, but this doesn't actually work: there's no `.dylib` in the bottle.
When I tried to build the formula from source, I saw this in the build log:
```
checking if the linker (/Applications/Xcode_13.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking whether the linker (/Applications/Xcode_13.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... no
checking command to parse /usr/bin/nm -B output... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
ok
checking how to hardcode library paths into programs... unsupported
checking for /Applications/Xcode_13.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking dynamic linker characteristics... no
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
```
This sounds very much like outdated autotools stuff, so it should be a matter of throwing `autoreconf` at the problem.

See <https://github.com/jwilk/python-aalib/issues/3> for context.

**Comment by SMillerDev** [comment]
if it's just autotools that should be submitted upstream and preferably released as a new version.

**Comment by jwilk** [comment]
AAlib is dead upstream: they had last release in 1998, last RC in 2001.

**Comment by SMillerDev** [comment]
That is very dead indeed, we should probably just deprecate/disable it then.
