### ISSUE TITLE
brew update gives an error with apachectl restart

### ISSUE THREAD

**Issue by batenburg** [Homebrew/homebrew-core#8959]
After a brew update, it returning the following error:

dyld: Symbol not found: _apr_crypto_block_cleanup
  Referenced from: /usr/local/Cellar/httpd24/2.4.25/bin/httpd
  Expected in: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib
 in /usr/local/Cellar/httpd24/2.4.25/bin/httpd
/usr/local/bin/apachectl: line 79:  5848 Abort trap: 6           $HTTPD -k $ARGV

**Comment by ilovezfs** [comment]
You'll need to report this to https://github.com/Homebrew/homebrew-apache/issues
