### ISSUE TITLE
Installing python --with-brewed-openssl argument not recognized?

### ISSUE THREAD

**Issue by czarina** [Homebrew/homebrew-core#8974]
I am trying to install python --with-brewed-openssl.

I have tried brew install python --with-brewed-openssl, but that argument is not recognized. Same issue if i replace python with python3:

$ brew install python3 --with-brewed-openssl
Warning: python3: this formula has no --with-brewed-openssl option so it will be ignored!
==> Downloading https://homebrew.bintray.com/bottles/python3-3.6.0.el_capitan.bottle.tar.gz

This seems to be an argument others use without problem. Any suggestions?

**Comment by DomT4** [comment]
Python and Python3 both use Homebrew's `openssl` by default, as does practically everything else these days. No option required or available.

**Comment by MikeMcQuaid** [comment]
As @DomT4 said.

**Comment by Flimm** [comment]
Is there a way to get `python` and `python3` to use `openssl@1.1` instead of Homebrew's `openssl`?

**Comment by DomT4** [comment]
No. Somewhat nitpicking but calling the 1.0.2 branch of OpenSSL older is a little misleading given it's the LTS branch & will be supported until at least 2019 under current plans. It's still very supported upstream.

Homebrew will transition to the 1.1.x branch as/when possible in all likelihood but it's incredibly complex to do; even Debian hasn't managed it entirely in `sid` to date. Homebrew's new policy effectively means that nothing will migrate to `openssl@1.1` unless that is the only `openssl` version being used throughout that formula's dependency tree.
