### ISSUE TITLE
lcov broken on Sierra, XCode8

### ISSUE THREAD

**Issue by chadbrewbaker** [Homebrew/homebrew-core#8977]
lcov 1.12 is broken on XCode8.

lcov trunk from Github  (1.13 candidate) seems to work.
https://github.com/linux-test-project/lcov

I would make a PR but not sure what needs to be done since the latest binary release is broken and you have to build from source.

**Comment by chadbrewbaker** [comment]
Actually they may be on 1.13, but nobody has built the binary and hosted it for homebrew.

**Comment by MikeMcQuaid** [comment]
@chadbrewbaker If you could try to make a PR we can help you debug and update it. [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by fxcoudert** [comment]
Homebrew already has lcov-1.13. As far as I can see it installs and works fine on Sierra with Xcode 8.2.1. I have tested installing it either from a bottle or from source: both work fine.

Regarding _“nobody has built the binary”_: lcov is a set of Perl scripts, so there is no binary to be built.
