### ISSUE TITLE
Change git-open to more popular (and maintained) fork

### ISSUE THREAD

**Issue by OJFord** [Homebrew/homebrew-core#8978]
The present formula for `git-open` uses jasonmccreary/gh, which was last updated 3 years ago.

The fork, paulirish/git-open, is exceedingly more popular, feature-ful (not Github-only), and is actually maintained.

Is there a mechanism by which the formula can be safely switch over? It's not even like the original author has 'dibs' on the name from earlier use, since the project doesn't actually use it.

I'd suggest the current formula could be renamed `gh-open`, which more accurately describes it anyway.

**Comment by MikeMcQuaid** [comment]
If you can convince Jason to deprecate his repo and point to Paul's we'd consider it.
