### ISSUE TITLE
Mediatomb failing to build from source: patch file returning 404

### ISSUE THREAD

**Issue by bkintanar** [Homebrew/homebrew-core#899]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

building mediatomb from scratch fails. It seems that one of the patch file is returning a 404 error. Specifically this file: 

`https://sourceforge.net/p/mediatomb/patches/_discuss/thread/57c47fb9/8ad8/attachment/mediatomb-urifix.patch`

It's no longer there.

Can anyone take a look at this?

@DomT4 I'll tag you with this since you were the one I last converse with regarding this formula.

Thanks.

@mikemcquaid informed me to report it here.

tagging my original issue number: https://github.com/Homebrew/brew/issues/203

**Comment by ilovezfs** [comment]
That's because the patch was accepted upstream: https://sourceforge.net/p/mediatomb/code/ci/2753e70013636bb5dd4cfc595f9776d368709f04/
