### ISSUE TITLE
brew install --build-from-source cquery

### ISSUE THREAD

**Issue by RTanner18** [Homebrew/homebrew-core#90519]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

When I run "brew install --cask pros-editor", it gives me this error :
```
Warning: cquery has been deprecated because it has an archived upstream repository!
Error: cquery: no bottle available!
You can try to install from source with:
  brew install --build-from-source cquery
```
I then run "brew install --build-from-source cquery" and get this error :
Last 15 lines from /Users/tan18man/Library/Logs/Homebrew/cquery/02.make:
    DOCTEST_ASSERT_LOG_AND_REACT(_DOCTEST_RB)                                                      \
    ^
/tmp/cquery-20211205-66884-va7k3c/third_party/doctest/doctest/doctest.h:2377:9: note: expanded from macro 'DOCTEST_ASSERT_LOG_AND_REACT'
        DOCTEST_BREAK_INTO_DEBUGGER();                                                             \
        ^
/tmp/cquery-20211205-66884-va7k3c/third_party/doctest/doctest/doctest.h:522:47: note: expanded from macro 'DOCTEST_BREAK_INTO_DEBUGGER'
#define DOCTEST_BREAK_INTO_DEBUGGER() __asm__("int $3\n" : :)
                                              ^
<inline asm>:1:2: note: instantiated into assembly here
        int $3
        ^
4 errors generated.
make[2]: *** [CMakeFiles/cquery.dir/src/c_cpp_properties.cc.o] Error 1
make[1]: *** [CMakeFiles/cquery.dir/all] Error 2
make: *** [all] Error 2

```

### Command that failed

brew install --build-from-source cquery

### Output of command with `--verbose --debug`

```shell
zsh: command not found: --verbose
```

### Output of `brew doctor --verbose`

```shell
Your system is ready to brew.
```

### Output of `brew tap`

```shell
homebrew/core
osx-cross/arm
purduesigbots/pros
```

**Comment by SMillerDev** [comment]
`brew install cquery` instead of `brew install --build-from-source cquery`

**Comment by RTanner18** [comment]
> `brew install cquery` instead of `brew install --build-from-source cquery`

I get the same error still -

```
Warning: cquery has been deprecated because it has an archived upstream repository!
Error: cquery: no bottle available!
You can try to install from source with:
  brew install --build-from-source cquery
```

**Comment by SMillerDev** [comment]
What does `brew config` say?

**Comment by RTanner18** [comment]
```
HOMEBREW_VERSION: 3.3.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: 32a3e1fe28f9372a6c6d5eca52129f92b0f00ba0
Last commit: 7 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 58da6910742dca9e82d828b94d253b2359dccf0c
Core tap last commit: 89 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6-arm64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A
Rosetta 2: false
```

**Comment by SMillerDev** [comment]
Yeah, that reveals the problem. cquery doesn't work on ARM and there is no maintenance on it anymore so it'll never be supported either.

**Comment by RTanner18** [comment]
> Yeah, that reveals the problem. cquery doesn't work on ARM and there is no maintenance on it anymore so it'll never be supported either.

So is there nothing I can do to get it working? I need to have this program installed but this is the only way to install it

**Comment by SMillerDev** [comment]
You can try installing homebrew with Rosetta (there's undoubtedly a lot of tutorials for this). But in the end this software has been abandoby the author and is going to stop working somewhere in the future. The only way forward is to find a replacement tool.

**Comment by iMichka** [comment]
As said above, there is not much we can do here. Unless someone starts maintaining the upstream project and helps fix the ARM issues. Closing as there is nothing actionable on our side.

**Comment by chenrui333** [comment]
@RTanner18 maybe you can try `ccls`

> ccls, which originates from cquery, is a C/C++/Objective-C language server.
