### ISSUE TITLE
dynamodb-local 2016-05-17 403 forbidden

### ISSUE THREAD

**Issue by rjcoelho** [Homebrew/homebrew-core#9065]
It looks like Amazon removed all version except latest
https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz

Can someone confirm this behaviour ? Should we point formula to latest ?

Thanks

**Comment by woodruffw** [comment]
Pointing to latest wouldn't be good, since Amazon could change it at any time and break our `sha256` check (and build process).

Best solution is to find another mirror for the current version and onwards.

**Comment by rjcoelho** [comment]
Can't find any non-latest tarball in https://dynamodb-local.s3.amazonaws.com nor do I know any mirror. Latest tarball says Last-Modified is "Wed, 18 Jan 2017 18:26:45 GMT" but 2017-01-18.tar.gz doesn't exit.

I say wait to see if Amazon restore non-latest files. If it takes too long, just point to latest. Yes it will break every time they move it, but so does when they remove old tarballs.

**Comment by woodruffw** [comment]
@rjcoelho It's worth trying to contact someone at Amazon to see if they can restore the URL(s).

Pointing to the latest is probably a non-starter, unfortunately -- we require a stable version URL for `homebrew-core`. If we can't get one, this might be destined for either the boneyard or a custom tap.

**Comment by ilovezfs** [comment]
Stupid question: is this product even opensource?

**Comment by woodruffw** [comment]
I've been wondering that too. DynamoDB itself is proprietary and this is the "local" version, so...

**Comment by alock** [comment]
So `dynamodb-local` can no longer be installed with homebrew?

**Comment by woodruffw** [comment]
@alock I'm afraid not. We don't (intentionally) include closed-source packages in `core`, and the fact that it's now unversioned is also a dealbreaker. See #9175 for some more details.
