### ISSUE TITLE
tomcat: add support for running on older versions of openjdk (e.g., openjdk@11)

### ISSUE THREAD

**Issue by archiecobbs** [Homebrew/homebrew-core#90661]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew gist-logs tomcat
Error: No logs.

$ brew config
HOMEBREW_VERSION: 3.3.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: dbec9de77ebc65a4845a5e672950219aa19b35b8
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: adde72754549aed4c2f8e58552fd2bfdcbe964dd
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: /usr/bin/vi
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.34.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.0.1-arm64
CLT: 13.1.0.0.1.1633545042
Xcode: N/A
Rosetta 2: false

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install openjdk

Run `brew missing` for more details.

[ *** NOTE: the above error is expected. I'm trying to run tomcat with openjdk@11 instead of openjdk ]
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to run tomcat on `openjdk@11` instead of `openjdk`.

The problem is that `/opt/homebrew/opt/tomcat/bin/catalina` is hard-coded to use `openjdk`:
```bash
#!/bin/bash
JAVA_HOME="/opt/homebrew/opt/openjdk" exec "/opt/homebrew/Cellar/tomcat/10.0.13/libexec/bin/catalina.sh"  "$@"
```

Other java programs like `ant` and `maven` use a trick like this which respects an existing `JAVA_HOME`:
```bash
#!/bin/bash
JAVA_HOME="${JAVA_HOME:-/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home}" exec "/opt/homebrew/Cellar/maven/3.8.4/libexec/bin/mvn"  "$@"
```

I'm not sure that would work for tomcat because it's a service. If not, perhaps there is some other way to make this configurable via a config file or something.

### What happened (include all command output)?

tomcat won't start when `openjdk@11` is installed but `openjdk` is not.

### What did you expect to happen?

Would like it to work.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install openjdk@11
$ brew install tomcat
$ brew uninstall --ignore-dependencies openjdk
```

**Comment by bayandin** [comment]
You need to replace `JAVA_HOME: Formula["openjdk"].opt_prefix` with `Language::Java.overridable_java_home_env` in `tomcat` formula. And revision bump is required for such kind of changes — just add `revision 1` after a license line.

Could you please create a PR with these changes?

**Comment by archiecobbs** [comment]
For anyone who stumbles across this bug and is wondering how to actually use this change:

Because tomcat is a service, you need to set `JAVA_HOME` in the service startup file, like in this example:

```diff
--- homebrew.mxcl.tomcat@9.plist	2021-12-09 12:09:04.000000000 -0600
+++ homebrew.mxcl.tomcat@9.plist	2021-12-09 12:08:55.000000000 -0600
@@ -13,5 +13,10 @@
 	</array>
 	<key>RunAtLoad</key>
 	<true/>
+	<key>EnvironmentVariables</key>
+	<dict>
+		<key>JAVA_HOME</key>
+		<string>/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home</string>
+	</dict>
 </dict>
 </plist>
```

**Comment by carlocab** [comment]
Isn't the less fragile way of doing that to use `launchctl setenv`? From `man launchctl`:
```
     setenv key value
              Specify an environment variable to be set on all future processes launched by launchd in the caller's context.
```

**Comment by archiecobbs** [comment]
Yes probably so - thanks! I didn't know about that option.
