### ISSUE TITLE
I have issues when starting hashcat

### ISSUE THREAD

**Issue by iamehiz** [Homebrew/homebrew-core#9074]
I started hashcat well but when i run my commands this is what i get

> hashcat -m 400 -a 0 /root/hash.txt /root/crak.txt
> hashcat (v3.20) starting...
> 
> clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
> 
> clGetDeviceIDs(): CL_DEVICE_NOT_FOUND
> 
> No devices found/left
> 
> Started: Thu Jan 19 05:48:34 2017
> Stopped: Thu Jan 19 05:48:34 2017

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md
