### ISSUE TITLE
brew initialization mysql 5.7.11 failed

### ISSUE THREAD

**Issue by Gilbertat** [Homebrew/homebrew-core#91]
I used brew to install mysql 5.7.11 but there are something wrong,console log it's 

`2016-04-06T02:09:32.966982Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
2016-04-06T02:09:32.968752Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2016-04-06T02:09:32.968771Z 0 [ERROR] Aborting
Warning: The post-install step did not complete successfully,You can try again using `brew postinstall mysql`

How can I fix it? Thank you!

**Comment by mikemcquaid** [comment]
`rm -rf /usr/local/var/mysql` which will delete all your local MySQL data so ensure you don't need it or that it is backed up.

**Comment by bmichotte** [comment]
I also have a problem. 

```
/usr/local/var > rm -rf /usr/local/var/mysql
/usr/local/var >  brew postinstall mysql
==> /usr/local/Cellar/mysql/5.7.11/bin/mysqld --initialize-insecure --user=benjamin --basedir=/usr/local/Cellar/mysql/5.7.11 --datadir=/usr/
Last 15 lines from /Users/benjamin/Library/Logs/Homebrew/mysql/01.mysqld:
2016-04-06 11:42:10 +0200

/usr/local/Cellar/mysql/5.7.11/bin/mysqld
--initialize-insecure
--user=benjamin
--basedir=/usr/local/Cellar/mysql/5.7.11
--datadir=/usr/local/var/mysql
--tmpdir=/tmp


READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

These open issues may also help:
brew initialization mysql 5.7.11 failed https://github.com/Homebrew/homebrew-core/issues/91
```

Gist : https://gist.github.com/bmichotte/3620cd84060cf00b77a104064a40feee

**Comment by mikemcquaid** [comment]
@bmichotte Run `brew postinstall mysql -v` and see what it says.

**Comment by bmichotte** [comment]
@mikemcquaid I updated [the gist](https://gist.github.com/bmichotte/3620cd84060cf00b77a104064a40feee#file-brew-postinstall-mysql-v) with the result of `brew postinstall mysql -v`

What's the `Error: mysql 5.7.11 did not build` ?

**Comment by mikemcquaid** [comment]
@bmichotte What's the output of running `/usr/local/Cellar/mysql/5.7.11/bin/mysqld --initialize-insecure --user=benjamin --basedir=/usr/local/Cellar/mysql/5.7.11 --datadir=/usr/local/var/mysql --tmpdir=/tmp` manually?

**Comment by littlethoughts** [comment]
I also had this error, I did  `rm -rf /usr/local/var/mysql` and then it worked, but now my databases are gone. I have a backup, do you know how I can restore it @mikemcquaid ?

**Comment by mikemcquaid** [comment]
@littlethoughts That's beyond Homebrew's scope, I'm afraid.

**Comment by bmichotte** [comment]
@mikemcquaid nothing... not a single character

```bash
~ /usr/local/Cellar/mysql/5.7.11/bin/mysqld --initialize-insecure --user=benjamin --basedir=/usr/local/Cellar/mysql/5.7.11 --datadir=/usr/local/var/mysql --tmpdir=/tmp
~
```

(already `rm`ed /usr/local/var/mysql)

**Comment by mikemcquaid** [comment]
@bmichotte I'm not sure what to do then, I'm afraid. I think you'll need to take this to the MySQL developers.

**Comment by Andrew-liu** [comment]
@mikemcquaid I have the same question.

when I exec `brew postinstall mysql -v`. I get some error below.

```
==> /usr/local/Cellar/mysql/5.7.12/bin/mysqld --initialize-insecure --user=andrew_liu --basedir=/usr/local/Cellar/mysql/5.7.12 --datadir=/usr/local/var/mysql --tmpdir=/tmp
2016-04-14T14:51:57.278084Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-04-14T14:51:57.280086Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2016-04-14T14:51:57.280105Z 0 [ERROR] Aborting
```

**Comment by jemagee** [comment]
So just so we're clear, no one has accurately figured out why this doesn't work?  I ask this because installing directly from the MySQL web page doesn't work either - the preference pane won't start - you can't start it at all.  I don't suppose Postgres conflicts with it?

**Comment by Andrew-liu** [comment]
@jemagee For my case, I find some error log in `/usr/local/var/mysql/XXXX.err`. In this file,  some `my.cnf` config make the mysqld start error.

so when I delete `/usr/local/var/mysql` and `/etc/my.cnf`, the mysql server work well.

**Comment by mikemcquaid** [comment]
I'm afraid this isn't Homebrew specific and is about how to make MySQL work so I'm closing this out. I'd advise you read the MySQL documentation and talk to other MySQL users.

**Comment by bmichotte** [comment]
Just FI, in my case, the culprit was a my.cnf file in /usr/local/etc

Once removed, mysql restart

**Comment by yunwe** [comment]
@bmichotte thank u. You helped me a lot.
