### ISSUE TITLE
pcre formula url update required for new source locations

### ISSUE THREAD

**Issue by jmstacey** [Homebrew/homebrew-core#91367]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  Bedrock git:(master) brew config
HOMEBREW_VERSION: 3.3.8-18-g7fd5085
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7fd5085803467c121fdfb95b0d69de476aa50dc9
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7a46f05358e720192834127b98e64298f72eae63
Core tap last commit: 73 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 16
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 16-core 64-bit dunno
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.0.0.0.1.1627064638
Xcode: N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install --verbose --debug --build-from-source pcre`

Why: I need pcre built with custom options for BedrockDB compile

### What happened (include all command output)?

Download of https://ftp.pcre.org/pub/pcre/pcre-8.45.tar.bz2   fails with a hang until killed.

### What did you expect to happen?

Package to be downloaded and built per spec. It looks like pcre download packages were moved. I temporarily fixed it locally by specifying an updated download URL, such as `https://downloads.sourceforge.net/project/pcre/pcre/8.45/pcre-8.45.tar.bz2`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Run `brew install --verbose --debug --build-from-source pcre`
```

**Comment by bfontaine** [comment]
Looks like this is still an issue: https://stackoverflow.com/q/71012613/735926

**Comment by carlocab** [comment]
Yes, it is. We probably should change the source URL to a mirror.

**Comment by jankallewulf** [comment]
Is there an easy way of fixing this locally? It blocks me right now from using homebrew
