### ISSUE TITLE
Python 3.9.x & 3.10.x

### ISSUE THREAD

**Issue by GBrachetta** [Homebrew/homebrew-core#91421]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew install pipenv`
`brew install python@3.9`
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installing Pipenv installed Python 3.10 as a dependency, yet it was not discoverable (`python3 --version` showed the default 3.8.3 installed with MacOS Monterey).

I installed 3.9 with `brew install python@3.9` and this makes 3.9 the default python3 version, but I don't see a way to make 3.10 the default one, not even after reinstalling it with `brew reinstall python@3.10`.

### What happened (include all command output)?

`brew reinstall python@3.10` (<== reinstall because it was installed as a dependency by Pipenv)
```
$ which -a python3 
/opt/homebrew/bin/python3
/usr/bin/python3
```

(Python3.9 that's it, and is the one in path being used)

```
$ python3 --version
Python 3.9.9
```

(I found no way to use the brew installation of python 3.10)

### What did you expect to happen?

I expected to have python 3.10.x as the default version after that was it the last version installed with Homebrew.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install pipenv`
`brew install python@3.9`


$ python3 --version
Python 3.9.9
```

`brew reinstall python@3.10`

```
$ python3 --version
Python 3.9.9
```

(expected to see 3.10.x as the current version)

=====

If I run `brew uninstall python@3.9`:

```
$ python3 --version
Python 3.8.3
```

(default Monterey version, although I installed 3.10 with Homebrew).

Where is 3.10?

**Comment by bayandin** [comment]
> I expected to have python 3.10.x as the default version after that was it the last version installed with Homebrew.

We have `python@3.9` as a default python until https://github.com/Homebrew/homebrew-core/pull/87075

`brew info python@3.10` says:

```
...
python@3.10 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have python@3.10 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> /Users/$USER/.bash_profile

For compilers to find python@3.10 you may need to set:
  export LDFLAGS="-L/usr/local/opt/python@3.10/lib"

For pkg-config to find python@3.10 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/python@3.10/lib/pkgconfig"
```
