### ISSUE TITLE
curl: custom certificate path

### ISSUE THREAD

**Issue by matthieumota** [Homebrew/homebrew-core#91476]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.8-43-g64bd95c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 64bd95c01bfff09d96cc200fedad71a78f44395a
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: ccdba08511315062686d9aeba8c0990596fa4a30
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.1-x86_64
CLT: 13.0.0.0.1.1630607135
Xcode: N/A

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  php@7.2
  php@7.3
  php@7.4
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Since #67412 , `--with-ca-path=#{openssl.pkgetc}/certs` option was removed and I'm not able to add additional certs to good path like feature [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl%401.1.rb#L118). I'm sure curl doesn't load that path so I need to add my cert to `cert.pem`.

### What happened (include all command output)?

Curl is not build with a ca path

### What did you expect to happen?

Curl is build with a ca path

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
cp cert.pem /usr/local/etc/openssl@1.1/certs
/usr/local/Cellar/openssl@1.1/1.1.1m/bin/c_rehash

Cert is not added because when https request, we have an error :

curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**Comment by carlocab** [comment]
Does adding additional certs to `/usr/local/etc/openssl@1.1/certs` work if you revert the change from #67412 and rebuild `curl`?
