### ISSUE TITLE
yafc needs a new dependency libbsd on non-BSD OSes.  

### ISSUE THREAD

**Issue by alanhoyle** [Homebrew/homebrew-core#91530]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/a623170bf39c03999a3e448c495919ae
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to install yafc on a CentOS 7 server.  According to https://github.com/sebastinas/yafc/blob/master/INSTALL:

```
[...]
Dependencies
------------

 * libbsd: required on platforms other than the BSDs.
[...]
```

When I try to install `yafc` through brew normally, the `configure` step fails: `configure: error: libbsd not found` however, if I use brew to install `libbsd` and then install `yafc` the installation works.  
   

I'd submit a pull request to add `depends_on "libbsd"` to the formula, https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yafc.rb, but from looking through the Formula Cookbook, I don't see a way to only specify dependencies that only get included in some OS versions.  

### What happened (include all command output)?

```
$ brew install yafc
Error: Please update your system curl.
Minimum required version: 7.41.0
Your curl version: 7.29.0
Your curl executable:
==> Downloading https://deb.debian.org/debian/pool/main/y/yafc/yafc_1.3.7.orig.tar.xz
Already downloaded: /home/alanh/.cache/Homebrew/downloads/3c4ad8ca43af3dc0402a038df4907ce1df7c9123d35e23fcb16d8a9d7638b3f0--yafc_1.3.7.orig.tar.xz
==> ./configure --prefix=/home/alanh/.linuxbrew/Cellar/yafc/1.3.7_4 --with-readline=/home/alanh/.linuxbrew/opt
Last 15 lines from /home/alanh/.cache/Homebrew/Logs/yafc/01.configure:
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking for an ANSI C-conforming const... yes
checking for pid_t... yes
checking for size_t... yes
checking for mode_t... yes
checking for pkg-config... /home/alanh/.linuxbrew/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether strlcpy is declared... no
checking for BSD... no
checking bsd/string.h usability... no
checking bsd/string.h presence... no
checking for bsd/string.h... no
configure: error: libbsd not found

READ THIS: https://docs.brew.sh/Troubleshooting

$ brew install libbsd yafc
Error: Please update your system curl.
Minimum required version: 7.41.0
Your curl version: 7.29.0
Your curl executable:
==> Downloading https://ghcr.io/v2/homebrew/core/libbsd/manifests/0.11.3
Already downloaded: /home/alanh/.cache/Homebrew/downloads/1d58d7943bf9dbe29ba5f128093ccf1e05c1eec6e3895cbe30a029074a5e88b0--libbsd-0.11.3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/libbsd/blobs/sha256:47ff83f8f952f71030f61444df19635a5eb3d98ed
Already downloaded: /home/alanh/.cache/Homebrew/downloads/2a76f3c8e77c2a55af25f2756ae6b319b7dea71c1ce17a0b699216552e8189e0--libbsd--0.11.3.x86_64_linux.bottle.tar.gz
==> Downloading https://deb.debian.org/debian/pool/main/y/yafc/yafc_1.3.7.orig.tar.xz
Already downloaded: /home/alanh/.cache/Homebrew/downloads/3c4ad8ca43af3dc0402a038df4907ce1df7c9123d35e23fcb16d8a9d7638b3f0--yafc_1.3.7.orig.tar.xz
==> Pouring libbsd--0.11.3.x86_64_linux.bottle.tar.gz
🍺  /home/alanh/.linuxbrew/Cellar/libbsd/0.11.3: 279 files, 972.3KB
==> Running `brew cleanup libbsd`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> ./configure --prefix=/home/alanh/.linuxbrew/Cellar/yafc/1.3.7_4 --with-readline=/home/alanh/.linuxbrew/opt
==> make install
==> Caveats
Bash completion has been installed to:
  /home/alanh/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/alanh/.linuxbrew/Cellar/yafc/1.3.7_4: 13 files, 490.6KB, built in 18 seconds
==> Running `brew cleanup yafc`...
==> Caveats
==> yafc
Bash completion has been installed to:
  /home/alanh/.linuxbrew/etc/bash_completion.d
$ yafc
yafc 1.3.7
This program comes with ABSOLUTELY NO WARRANTY; for details type 'warranty'.
This is free software; type 'copyright' for details.

yafc>
```

### What did you expect to happen?

`yafc` would  install without needing an unspecified dependency.  

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
# the below fails on non-BSD OS like linux
brew install yafc
# the below succeeds on CentOS 7 
brew install libbsd yafc
```

**Comment by SMillerDev** [comment]
Could you make a pull request to add that dependency?

**Comment by alebcay** [comment]
A dependency can be added conditionally, e.g. LInux-only or macOS-only:
```
  on_linux do
    depends_on "libbsd"
  end
```

Here's another example from a different formula:
https://github.com/Homebrew/homebrew-core/blob/daa8e771a8fffe42c587b50df2c1d4884c70e5b8/Formula/abi-compliance-checker.rb#L23-L25

**Comment by alanhoyle** [comment]
Is there an `else` in the formula language? I looked through the documentation and don't see a good explanation.

**Comment by carlocab** [comment]
> Is there an `else` or `if not` in the formula language?

You can use `if ... elif ... else ... end` in certain parts of the formula. What are you trying to do exactly?

**Comment by alanhoyle** [comment]
Is Linux the only non-BSD that homebrew supports? Is there a list of the things like `do_Linux` somewhere?

**Comment by carlocab** [comment]
> Is Linux the only non-BSD that homebrew supports?

Yes. Homebrew is tested only on macOS and Linux.

**Comment by carlocab** [comment]
Closed in https://github.com/Homebrew/homebrew-core/pull/92467.

Thanks for the report and the fix, @alanhoyle.
