### ISSUE TITLE
Request: Add PulseAudio support to mpd

### ISSUE THREAD

**Issue by darvelo** [Homebrew/homebrew-core#9161]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Formula Requests:

Please add [pulseaudio](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pulseaudio.rb) support to [mpd](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpd.rb) music daemon.

I tried adding a new line (`--enable-pulse`) to the [`./configure` args](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpd.rb#L78), but got the following output and I'm not sure how to move it forward:

```
==> Using the sandbox
==> Downloading https://www.musicpd.org/download/mpd/0.20/mpd-0.20.2.tar.xz
Already downloaded: /Users/dave/Library/Caches/Homebrew/mpd-0.20.2.tar.xz
==> ./configure --prefix=/usr/local/Cellar/mpd/0.20.2 --sysconfdir=/usr/local/etc --enable-bzip2 --enable-ffmpeg --enable-fluidsynth --enable-osx --enable-pulse --disable-libwrap --disable-mad --enable-lastfm
Last 15 lines from /Users/dave/Library/Logs/Homebrew/mpd/01.configure:
checking for AO... no
configure: WARNING: libao not found -- disabling libao output plugin
checking OpenAL/al.h usability... yes
checking OpenAL/al.h presence... yes
checking for OpenAL/al.h... yes
checking OpenAL/alc.h usability... yes
checking OpenAL/alc.h presence... yes
checking for OpenAL/alc.h... yes
configure: auto-detected OpenAL output plugin
checking sys/soundcard.h usability... no
checking sys/soundcard.h presence... no
checking for sys/soundcard.h... no
configure: WARNING: Soundcard headers not found -- disabling OSS support
checking for PULSE... no
configure: error: PulseAudio output plugin: libpulse not found

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

I can confirm that the `libpulse` library is located at `/usr/local/Cellar/pulseaudio/9.0_2/lib/libpulse.dylib` symlinked to `/usr/local/Cellar/pulseaudio/9.0_2/lib/libpulse.0.dylib`.

**Comment by nijikon** [comment]
Please create a pull request next time.
