### ISSUE TITLE
Add Python 3.4.x, 3.5.x, and 3.6.x to formulae.

### ISSUE THREAD

**Issue by AraHaan** [Homebrew/homebrew-core#9163]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

Note: I don't own an actual OSX, And I cant run an OSX in VirtualBox either because of lame 4 GB Memory on this Inspiron 1545 made back in 2008. I have Windows as host and an Ubuntu 16.04 VM. I however use OSX on travis and as such not only do I have to use homebrew to update gcc / g++ & clang to latest for full on C++ 14 with the experimental filesystem header. But also for Python 3.4+ as Python is not be default installed in OSX and most things are now 3.4.x+ because of coroutines, however if they use ``async def`` it is 3.5.x+ only.

As you guys can see there needs to be an python34.rb, python35.rb, and python36.rb. All 3 of which I could try to PR with the correct information.

btw clang is now 3.9.1 for latest release just so you guys know.

**Comment by AraHaan** [comment]
I just realized that ``python3.rb`` installs only 3.6.0 for now, but what if python 3.7 is released at end of this year or something? Then it would only install 3.7 and what if people I know require specific versions only for things like codecov.io *cough* aiohttp *cough* for travis.

**Comment by MikeMcQuaid** [comment]
We don't do formula requests, sorry. I'm not convinced these older versions of Python would be useful given tools like `pyenv`.
