### ISSUE TITLE
latexindent issue

### ISSUE THREAD

**Issue by Wongboo** [Homebrew/homebrew-core#91974]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs latexindent                                                                                        
Error: No logs.

brew doctor 
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  pdf2htmlex
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

run `latexindent --help` in terminal

### What happened (include all command output)?
```
SystemDirectory.c: loadable library and perl binaries are mismatched (got handshake key 0xf880080, needed 0xc400080)
```

### What did you expect to happen?
```
latexindent.pl version 3.13.4, 2021-12-22
usage: latexindent.pl [options] [file]
      -v, --version
          displays the version number and date of release
      -h, --help
          help (see the documentation for detailed instructions and examples)
      -sl, --screenlog
          log file will also be output to the screen
      -o, --outputfile=<name-of-output-file>
          output to another file; sample usage:
                latexindent.pl -o outputfile.tex myfile.tex
                latexindent.pl -o=outputfile.tex myfile.tex
      -w, --overwrite
          overwrite the current file; a backup will be made, but still be careful
      -s, --silent
          silent mode: no output will be given to the terminal
      -t, --trace
          tracing mode: verbose information given to the log file
      -l, --local[=myyaml.yaml]
          use `localSettings.yaml`, `.localSettings.yaml`, `latexindent.yaml`,
          or `.latexindent.yaml` (assuming one of them exists in the directory of your file or in
          the current working directory); alternatively, use `myyaml.yaml`, if it exists;
          sample usage:
                latexindent.pl -l some.yaml myfile.tex
                latexindent.pl -l=another.yaml myfile.tex
                latexindent.pl -l=some.yaml,another.yaml myfile.tex
      -y, --yaml=<yaml settings>
          specify YAML settings; sample usage:
                latexindent.pl -y="defaultIndent:' '" myfile.tex
                latexindent.pl -y="defaultIndent:' ',maximumIndentation:' '" myfile.tex
      -d, --onlydefault
          ONLY use defaultSettings.yaml, ignore ALL (yaml) user files
      -g, --logfile=<name of log file>
          used to specify the name of logfile (default is indent.log)
      -c, --cruft=<cruft directory>
          used to specify the location of backup files and indent.log
      -m, --modifylinebreaks
          modify linebreaks before, during, and at the end of code blocks;
          trailing comments and blank lines can also be added using this feature
      -r, --replacement
          replacement mode, allows you to replace strings and regular expressions
          verbatim blocks not respected
      -rv, --replacementrespectverb
          replacement mode, allows you to replace strings and regular expressions
          while respecting verbatim code blocks
      -rr, --onlyreplacement
          *only* replacement mode, no indentation;
          verbatim blocks not respected
      -k, --check mode
          will exit with 0 if document body unchanged, 1 if changed
      -kv, --check mode verbose
          as in check mode, but outputs diff to screen as well as to logfile
      -n, --lines=<MIN-MAX>
          only operate on selected lines; sample usage:
                latexindent.pl --lines 3-5 myfile.tex
                latexindent.pl --lines 3-5,7-10 myfile.tex
```
### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install texlive
brew install latexindent
```

**Comment by Wongboo** [comment]
I suggest we change the content of `/usr/local/Cellar/latexindent/3.13.4/bin/latexindent` from
```
#!/bin/bash
PERL5LIB="/usr/local/Cellar/latexindent/3.13.4/libexec/lib/perl5" exec "/usr/local/Cellar/latexindent/3.13.4/libexec/bin/latexindent.pl"  "$@"
```
to
```
#!/bin/bash
PERL5LIB="/usr/local/Cellar/latexindent/3.13.4/libexec/lib/perl5" "/usr/local/opt/perl/bin/perl" "/usr/local/Cellar/latexindent/3.13.4/libexec/bin/latexindent.pl"  "$@"
```
since `latexindent` depends on `perl`, `/usr/local/opt/perl/bin/perl` must exist and must be compatible with `latexindent`, this can fix problem and produce right output

**Comment by gromgit** [comment]
Your suggested change should not be necessary, because `latexindex --help` works perfectly on my Big Sur box, and:
```
$ head -3 /usr/local/Cellar/latexindent/3.13.4/libexec/bin/latexindent.pl 
#!/usr/local/opt/perl/bin/perl
#   latexindent.pl, version 3.13.4, 2021-12-22
#
```
Homebrew `perl` should already be executed, so it's something specific to your machine instead.

Try `brew reinstall latexindex` and `latexindent --help` again. If it fails, what's the output of `brew config` and `command -v latexindent`?

**Comment by Wongboo** [comment]
```
╭─     ~                                                                                                    ✔ ─╮
╰─ brew config                                                                                                       ─╯
HOMEBREW_VERSION: 3.3.9-36-ge970bb1
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: e970bb18765cd4f16c39585cb0eabc9208c68996
Last commit: 29 hours ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 43fe6e9f43410a933a34daf1b97f39180120bd32
Core tap last commit: 14 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: code -w
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A

╭─     ~                                                                                       ✔  took 3s   ─╮
╰─ command -v latexindent                                                                                            ─╯
/usr/local/bin/latexindent

╭─     ~                                                                                                    ✔ ─╮
╰─ ls -l /usr/local/bin/latexindent                                                                                  ─╯
lrwxr-xr-x  1 wangbo  admin  44 12 24 09:38 /usr/local/bin/latexindent -> ../Cellar/latexindent/3.13.4/bin/latexindent


```
By the way, I've met this problem since big sur

**Comment by gromgit** [comment]
What's the output of `head -3 /usr/local/Cellar/latexindent/3.13.4/libexec/bin/latexindent.pl`?

**Comment by Wongboo** [comment]
```
#!/usr/bin/perl
#   latexindent.pl, version 3.13.4, 2021-12-22
#
```
If I change the first line to 
```
#!/usr/local/opt/perl/bin/perl
```
still works.

**Comment by gromgit** [comment]
>```
>#!/usr/bin/perl
>#   latexindent.pl, version 3.13.4, 2021-12-22
>#
>```
That is _not_ what the Homebrew bottle contains; see [my earlier comment](https://github.com/Homebrew/homebrew-core/issues/91974#issuecomment-1000655893) for the correct shebang line.

> If I change the first line to
>```
>#!/usr/local/opt/perl/bin/perl
>```
> still works.

Do you mean that "it now works"? If so, you've actually restored it to what that file should look like. Again, [your proposed fix](https://github.com/Homebrew/homebrew-core/issues/91974#issuecomment-1000606294) is not necessary; the `latexindent` Homebrew bottle already contains the correct code.

**Comment by Wongboo** [comment]
I see, I have download the `latexindent` bottle file, the first lines appear to be 
```
#!@@HOMEBREW_PERL@@
```
Can you please explain how `@@HOMEBREW_PERL@@` expand?

**Comment by gromgit** [comment]
See:

https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/keg_relocate.rb#L4-L10

and:

https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/keg_relocate.rb#L113-L122

In particular, the second snippet shows that the replacement for @@HOMEBREW_PERL@@ is `#{HOMEBREW_PREFIX}/opt/perl/bin/perl`, not `/usr/bin/perl`. To get the latter, you'd either have to change the file yourself, or the Chinese Homebrew mirror you're using is messing with their mirror of the Homebrew software to make this broken substitution.

(That's another reason why your proposed change would likely be rejected: It's against the contents of a third-party mirror, not official Homebrew.)

**Comment by Wongboo** [comment]
https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/keg_relocate.rb#L98-L100 it might because of these lines, I see. Let me confirm it

**Comment by Wongboo** [comment]
I have never use ruby, can you please explain what is
```
relocation.add_replacement_pair(:perl,
                                    %r{\A#!(?:/usr/bin/perl\d\.\d+|#{HOMEBREW_PREFIX}/opt/perl/bin/perl)( |$)}o,
                                    "#!#{PERL_PLACEHOLDER}\\1")
```
doing? under what condition it expands to `usr/bin/perl` or `{HOMEBREW_PREFIX}/opt/perl/bin/perl`

**Comment by gromgit** [comment]
> https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/keg_relocate.rb#L98-L100 it might because of these lines, I see. Let me confirm it

Nope, that's used during the bottling, to replace existing instances of `/usr/bin/perl` or `/usr/local/opt/perl/bin/perl` in Perl scripts with `@@HOMEBREW_PERL@@`. See:

https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/keg_relocate.rb#L26-L30

for the function definition. Note that the second argument is called `old`, and the third `new`.

**Comment by gromgit** [comment]
To prevent this digressing into a Homebrew code review, do the following:
```
brew reinstall latexindent
head -3 /usr/local/Cellar/latexindent/3.13.4/libexec/bin/latexindent.pl
```
If you still see `/usr/bin/perl` at the top of the script, your Homebrew software from your Chinese mirror is broken:
```
brew config
HOMEBREW_VERSION: 3.3.9-36-ge970bb1
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
```
and you'll have to ask that mirror's maintainers what they messed with...or use the official Homebrew software instead:
```
git -C $(brew --repo) remote set-url origin https://github.com/Homebrew/brew
brew update-reset
```

**Comment by Wongboo** [comment]
The problem must happen when replacing `PERL_PLACEHOLDER`, might because of these https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/extend/os/mac/keg_relocate.rb#L156-188

**Comment by Wongboo** [comment]
I add 
```
perl_path =      "#{HOMEBREW_PREFIX}/opt/perl/bin/perl"
```
to line 173, and do a reinstallation, things get right, so why is
```
brewed_perl || name == "perl"
```
in line 160 not true

**Comment by Wongboo** [comment]
Is there any way to debug `pouring bottle` process? mirror says they are are providing same brew.sh, formulas and bottles as upstream.

**Comment by gromgit** [comment]
> Is there any way to debug `pouring bottle` process?

Only thing I can think of is to add the following before https://github.com/Homebrew/brew/blob/d1a819986fede40cad588cd533e1d55171e2e124/Library/Homebrew/extend/os/mac/keg_relocate.rb#L173
```
ohai "brewed_perl = #{brewed_perl}"
ohai "tab['built_on']=#{tab['built_on']}"
ohai "perl_path=#{perl_path}"
```
then `brew reinstall --verbose latexindent` and check the output.

**Comment by Wongboo** [comment]
my debug show that
```
==> brewed_perl = 
==> tab['built_on']={"os"=>"Macintosh", "os_version"=>"macOS 12", "cpu_family"=>"kabylake"}
==> perl_path=/usr/bin/perl
```
here is from mirror maintainer: https://github.com/ustclug/discussions/issues/382#issuecomment-1001042557

**Comment by carlocab** [comment]
Tracked in https://github.com/Homebrew/brew/issues/12759.
