### ISSUE TITLE
Update fheroes2 formula to 0.9.11

### ISSUE THREAD

**Issue by yvesgurcan** [Homebrew/homebrew-core#91982]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
As of today, `fheroes2` has a new release (version 0.9.11). Could somebody update the formula at https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/fheroes2.rb#L4 to point towards https://github.com/ihhub/fheroes2/archive/0.9.11.tar.gz?
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the latest version of `fheroes2`.

### What happened (include all command output)?

Installed version 0.9.10 instead of 0.9.11.

### What did you expect to happen?

Install version 0.9.11.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install fheroes2
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
