### ISSUE TITLE
synthesia checksum does not match install failed

### ISSUE THREAD

**Issue by marksanctuary** [Homebrew/homebrew-core#92048]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew doctor
Your system is ready to brew.
HOMEBREW_VERSION: 3.3.9-42-gd1a8199
ORIGIN: https://github.com/Homebrew/brew
HEAD: d1a819986fede40cad588cd533e1d55171e2e124
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 987bc4feceebabe80334a786ad3f5a99d0729927
Core tap last commit: 89 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: N/A

brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to Install synthesia to try out the software.

### What happened (include all command output)?

Trying to Install synthesia but the checksum is not correct and the install fails.

brew install --cask synthesia
==> Downloading https://synthesia.s3.amazonaws.com/files/Synthesia-10.8.dmg
Already downloaded: /Users/**/Library/Caches/Homebrew/downloads/0cd9f32bcae8ac6fa35ce24b1d616bce3401b307606abfbc9246d640f6e55933--Synthesia-10.8.dmg
Error: SHA256 mismatch
Expected: 0211192748bac7dfab553386fdba1b8e1f0322638729bd04858add6fdbe13750
  Actual: 02fa6519b152d28cb6bd9d41be0a859ef66c35bdf563a0a2dab7e4dccd334d8e
    File: /Users/**/Library/Caches/Homebrew/downloads/0cd9f32bcae8ac6fa35ce24b1d616bce3401b307606abfbc9246d640f6e55933--Synthesia-10.8.dmg
To retry an incomplete download, remove the file above.

### What did you expect to happen?

For the checksum to match and synthesia to be installed correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --cask synthesia
```

**Comment by carlocab** [comment]
This issue is cask-related, so this isn't the right repository.

Please see the [guide for reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs) at [homebrew-cask](https://github.com/Homebrew/homebrew-cask).

**Comment by marksanctuary** [comment]
Ok no problem, thanks for the response. I have followed the guide and reported this at home-brew-cask.
