### ISSUE TITLE
possible problems with variable GOBJECT_INTROSPECTION_LIBDIR

### ISSUE THREAD

**Issue by speeder** [Homebrew/homebrew-core#9206]
I am trying to use homebrew to install gobject-introspection + gtk3 + cairo to use with Lua, using lgi.

lgi fails to run, complaining that it can't find this:
"/usr/local/Cellar/gobject-introspection/1.50.0/lib/libcairo.2.dylib"

lgi looks for .dylib files using the variable GOBJECT_INTROSPECTION_LIBDIR

that variable DO point to the folder where Lua looked for libcairo.2.dylib file, but libcairo.2.dylib location is "/usr/local/Cellar/cairo/1.14.8/"

Maybe it is a bug in lgi, and not here, but I am not sure, I don't know how to debug this.

pkg-config is also involved.

**Comment by MikeMcQuaid** [comment]
Sorry, as this isn't a bug in a Homebrew formula we're unable to help you.
