### ISSUE TITLE
As with #90118 there seems to be an issue building the ARM bottle.

### ISSUE THREAD

**Issue by dkocher** [Homebrew/homebrew-core#92078]
As with #90118 there seems to be an issue building the ARM bottle.

```
Error: duck: no bottle available!
You can try to install from source with:
```

_Originally posted by @dkocher in https://github.com/Homebrew/homebrew-core/issues/91927#issuecomment-1000408814_

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by dkocher** [comment]
Follow up in #92180 with issue created from template.
