### ISSUE TITLE
sha256 mismatch with guile patch

### ISSUE THREAD

**Issue by Kethen** [Homebrew/homebrew-core#92080]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew gist-logs guile
Error: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

install guile as a dependency

### What happened (include all command output)?

sha256 mismatch happened

```
Error: guile: SHA256 mismatch
Expected: a5adf2586b30381cf24524c7fc0364115f7cb1f568d2b69a9f3fb49ad8355b55
  Actual: a857c5fde2eb1c05379a97ba88047404da1c5b1da0291903f036d0a8745d85b5
    File: /Users/katharine/Library/Caches/Homebrew/downloads/ed0ab6d9aa9892d417f166b6aca3db95c5c2eab4a4e3c6f5a74a585c956debf6--9a62f7cacaf730fca07f6cfd400a1893c2c2acb6..1f100a4f20c3a6e57922fb26fce212997e2a03cb.patch
To retry an incomplete download, remove the file above.
```

https://github.com/Homebrew/homebrew-core/blob/85b17f342d2c217ab520bae780be5280a33c3cce/Formula/guile.rb#L44
```
wget https://git.savannah.gnu.org/cgit/guile.git/patch/?id=1f100a4f20c3a6e57922fb26fce212997e2a03cb -O - 2>/dev/null | shasum -a 256
a857c5fde2eb1c05379a97ba88047404da1c5b1da0291903f036d0a8745d85b5  -
```
https://github.com/Homebrew/homebrew-core/blob/85b17f342d2c217ab520bae780be5280a33c3cce/Formula/guile.rb#L45

### What did you expect to happen?

something happened to the patch file and the checksum is no longer valid as of right now

I have no idea whether the patch is still valid, that only a checksum update is needed or what else has to be done

someone has the same issue on 12.0.1

https://github.com/sobolevn/git-secret/issues/742

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install guile
```

**Comment by AustroTonic** [comment]
same issue on macOS 10.12.6
