### ISSUE TITLE
Node from brew is overriding the Python from the environment

### ISSUE THREAD

**Issue by dibir-magomedsaygitov** [Homebrew/homebrew-core#92116]
### **`brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output**
```
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 386dbd8bf930f169dd43bac7c7719659ee99026d
Core tap last commit: 19 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: ["--no-quarantine"]
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 3650
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 3
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: 3-core 64-bit ivybridge
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.1 => /Applications/Xcode_13.1.app/Contents/Developer
```
### Verification
Please verify that you've followed these steps.
- [x] I ran brew update and am still able to reproduce my issue. *
- [x] I have resolved all warnings from brew doctor and that did not fix my problem. *

### What were you trying to do (and why)?

We are maintainers of [actions/virtual-environments](https://github.com/actions/virtual-environments) repository and customer has reported to us that Node installed using `brew` is overriding the python from the environment (see additional details in [this issue](https://github.com/actions/virtual-environments/issues/4665)). This behavior has started to appear after [recent changes in brew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@16.rb#:~:text=depends_on%20%22python%403.10%22%20%3D%3E%20%3Abuild). Note that we have python 3.9* as a default version on our macOS images.

### What happened (include all command output)?

Node overrides the Python from environment (note: python 3.9* is a default version)
```
/usr/local/opt/python@3.10/bin:/usr/local/Cellar/node@16/16.13.0/bin:/Users/runner/hostedtoolcache/Python/3.9.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.9.9/x64:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
Python 3.10.0
```

### What did you expect to happen?

Expect Node to not override the Python
```
/Users/runner/hostedtoolcache/Python/3.9.9/x64/bin:/Users/runner/hostedtoolcache/Python/3.9.9/x64:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
Python 3.9.9
```

### Step-by-step reproduction instructions:
We install default version of Node on our images using this command:
`brew install node@16`

Then you have to run following workflow:
```
name: Test
on:
  push:

jobs:
  test:
    name: node test
    runs-on: macos-11
    steps:
      - run: |
          echo '
            const child_process = require("child_process");
            const output = child_process.execFileSync("python3", ["-V"], { encoding: "utf8" });
            console.log(process.env.PATH);
            console.log(output);
          ' | node -
      - run: |
          echo $PATH
          python3 -V
```

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by dibir-magomedsaygitov** [comment]
Thank you @SMillerDev. I've updated the issue. Could you please check?

**Comment by Bo98** [comment]
Am I correct in saying Node 14 and Node 17 are not affected?

**Comment by dibir-magomedsaygitov** [comment]
@Bo98 I think yes ([same dependency on python 3.10 for Node 14 for example](https://github.com/Homebrew/homebrew-core/blob/master/Formula/node@14.rb#:~:text=depends_on%20%22python%403.10%22%20%3D%3E%20%3Abuild)). But we install only Node 16 via brew on our images.
