### ISSUE TITLE
libunwind: add -fPIC to CFLAGS

### ISSUE THREAD

**Issue by curoky** [Homebrew/homebrew-core#92125]
I want to build a shared library that depend on libunwind.a, it needs to use `-fPIC` flag to build libunwind.

```
ld: /home/linuxbrew/.linuxbrew/opt/libunwind/lib/libunwind.a(backtrace.o): relocation R_X86_64_PC32 against symbol `_ULx86_64_init_local' can not be used when making a shared object; recompile with -fPIC
```

So we should add `ENV.append_to_cflags '-fPIC'` to line 25.

https://github.com/Homebrew/homebrew-core/blob/886871eaa0d1f5cd311bc66be371f252b6b2ad96/Formula/libunwind.rb#L24-L28

**Comment by SMillerDev** [comment]
Could you fill out the issue template please? It's pretty essential in debugging issues. This issue can be reopened once we have all the information needed to start debugging.

**Comment by curoky** [comment]
@SMillerDev Sorry, I just want to create a related simple issues for pr, the issues template content is too formal 😂.
