### ISSUE TITLE
duck: no bottle available

### ISSUE THREAD

**Issue by dkocher** [Homebrew/homebrew-core#92180]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
silverbullet:cyberduck dkocher$ brew config
HOMEBREW_VERSION: 3.3.9-80-g26694fd
ORIGIN: https://github.com/Homebrew/brew
HEAD: 26694fd6354c52cfc592261c86752ca4fc9e3b3d
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 718b8d8a254d0b39a0a2dd8098d64e16b1af10c5
Core tap last commit: 30 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: ["--appdir=~/Applications", "--fontdir=/Library/Fonts"]
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.34.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.1
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrade `duck`

### What happened (include all command output)?

```
silverbullet:cyberduck dkocher$ brew upgrade duck
==> Upgrading 1 outdated package:
duck 8.1.1.36550 -> 8.2.0.36680
Error: duck: no bottle available!
You can try to install from source with:
  brew install --build-from-source duck
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

### What did you expect to happen?

Bottle should be available after merging #91927.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew upgrade duck
```

**Comment by SMillerDev** [comment]
Duck doesn't have any ARM bottles, and it didn't successfully build on ARM in https://github.com/Homebrew/homebrew-core/pull/91927 either so this is expected behavior. I'm not sure how you managed to have an earlier version installed though.

**Comment by dkocher** [comment]
> Duck doesn't have any ARM bottles, and it didn't successfully build on ARM in #91927 either so this is expected behavior. I'm not sure how you managed to have an earlier version installed though.

ARM is supported with 8.1.0 or later and thus bottles should be built.

**Comment by SMillerDev** [comment]
> ARM is supported with 8.1.0 or later and thus bottles should be built.

It might be officially supported, but if you check the annotations in https://github.com/Homebrew/homebrew-core/pull/91927/files you'll see the tests still failed.

**Comment by dkocher** [comment]
As mentioned in https://github.com/Homebrew/homebrew-core/pull/90118#issuecomment-996744827 I am unable to reproduce the test failure.

**Comment by SMillerDev** [comment]
That's fine, but CI doesn't really allow for "works on my machine". You can make a pull request to change/fix the tests on ARM, but the lack of bottles for duck is completely according to expectations.

**Comment by dkocher** [comment]
Sorry for my ignorance, but I would like to help out fixing the issue with the missing bottle and what I am looking for is some guidance to find the cause of the test failures I am unable to reproduce. Unfortunately the output from CI is sparse and doesn't reveal any underlying cause it seems.

**Comment by Bo98** [comment]
My advice would be to perhaps adjust the test to output more debugging output (if possible) and run that in a PR to see if you can see any more information.

**Comment by dkocher** [comment]
I can now reproduce when running `brew test-bot duck.rb` (instead of `brew test`) locally. It looks the problem is with adhoc code signing as the application is killed when opened

```
silverbullet:formula dkocher$ /opt/homebrew/Cellar/duck/8.2.0.36680/bin/duck 
Killed: 9
```

The adhoc signature looks to be broken
```
silverbullet:formula dkocher$ codesign -v /opt/homebrew/Cellar/duck/8.2.0.36680/bin/duck 
/opt/homebrew/Cellar/duck/8.2.0.36680/bin/duck: code has no resources but signature indicates they must be present
```

it works after replacing the code signature with 
```
silverbullet:formula dkocher$ codesign --force --deep -s - /opt/homebrew/Cellar/duck/8.2.0.36680/libexec/
```

What is the difference in the installation process with `brew install --build-from-source duck` where this cannot be reproduced?

**Comment by dkocher** [comment]
@SMillerDev If this could be reopened until the cause is determined 👆🏻.

**Comment by carlocab** [comment]
> What is the difference in the installation process with` brew install --build-from-source duck` where this cannot be reproduced?

Calling `brew test-bot` also calls `brew bottle` for packaging. I suggest trying
```
brew install --build-bottle duck
brew bottle --verbose --debug duck
```
