### ISSUE TITLE
suggestion: rssh formula to patch over use of wordexp()

### ISSUE THREAD

**Issue by kengreenebaum** [Homebrew/homebrew-core#92205]
### Provide a detailed description of the proposed feature

rssh uses wordexp() to provide the vector execv() requires.  wordexp() is problematic from a security perspective and on OSX shells out to perform this operation requiring /bin/sh to be added to the chroot thereby potentially introducing other vulnerabilities.  Perhaps it would be better to avoid wordexp() and instead pass the arguments directly to execl()?

Also the rssh cask provides a path to the rssh.conf file inside the cask itself where it might be overwritten by a future update.

Lastly it would be helpful to update the chroot setup script for OSX.

### What is the motivation for the feature?

Would be nice if rssh worked for users "out of the box" especially when used in a chroot() environment.

### How will the feature be relevant to at least 90% of Homebrew users?

The existing rssh formula doesn't seem to be able to run in a chroot() environment, even when /bin/sh was added to the jail to deal with OSX's wordexp wrapper. So this proposed change would save rssh users the anguish in configuring it to function in a chroot jail.

### What alternatives to the feature have been considered?

I spent considerable effort attempting to use the formula as-is then gave up and modified the source code.  I am hoping these efforts might help others.

**Comment by carlocab** [comment]
We can apply a patch accepted by the upstream rssh project. Conversely, we are unlikely to apply any patches that have not been upstreamed or will not be merged upstream.

**Comment by kengreenebaum** [comment]
I looked upstream, too, http://www.pizzashack.org/rssh/.  The latest dated update was 11/2012 so doesn't appear to be actively developed.  On http://www.pizzashack.org/rssh/platforms.shtml they do refer to issues with wordexp() on BSD and OSX systems.

**Comment by kengreenebaum** [comment]
My motivation is to spare others the time I invested to figure out why rssh wasn't working for me and then how to fix it.

**Comment by gromgit** [comment]
Actually, `rssh` should be deprecated, by the author's own admission.

https://sourceforge.net/p/rssh/mailman/message/37202810/
> As of January 28 of last year I announced that rssh is no longer maintained.  As Russ says, it's just not able to do its job effectively for a host of reasons.  I guess I neglected to update the web site... I should do that soon.

The "Russ" mentioned in the above message is the Debian `rssh` maintainer, who's also given up.

https://sourceforge.net/p/rssh/mailman/message/37199484/
> You should probably consider rssh deprecated and think about alternatives. My attempts to clean up the last few rounds of problems produced a ton of collateral damage, and I've personally stopped trying to maintain rssh in Debian because I'm not confident that I can make it secure.

So `rssh` is clearly EOL.

**Comment by MikeMcQuaid** [comment]
Closing as this as now been deprecated. Thanks for making us aware @kengreenebaum and for the PR @gromgit!
