### ISSUE TITLE
"module 'enum' has no attribute 'IntFlag'" when installing python3

### ISSUE THREAD

**Issue by slhck** [Homebrew/homebrew-core#9229]
> - [x] Ran `brew update` and retried your prior step?
> - [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
> - [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

I am running OS X 10.10.5 with Python 2 installed via Homebrew, chosen as the default. I'm trying to install Python 3 alongside it:

    brew install python3

I get the following error:

```
==> /usr/local/Cellar/python3/3.6.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.6.0/bin --in
Last 15 lines from /Users/werner/Library/Logs/Homebrew/python3/post_install.01.python3:
--record=installed.txt

Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/site.py", line 75, in <module>
    __boot()
  File "/usr/local/lib/python2.7/site-packages/site.py", line 27, in __boot
    import imp # Avoid import loop in Python >= 3.3
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 27, in <module>
    import tokenize
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

My logs are here: https://gist.github.com/slhck/f0321cad507d081aee7e753f531964c8

I am assuming this *should* work with `which python` pointing to Python installed via Homebrew?

My `$PYTHONPATH` is set to `/usr/local/lib/python2.7/site-packages:` — also not sure if this is expected behavior. I don't remember setting it anywhere and none of my shell config files have it.

Same problem is mentioned [here](http://apple.stackexchange.com/questions/267139/problems-while-installing-python-3-on-el-capitan) without a solution.

**Comment by MikeMcQuaid** [comment]
> Unbrewed dylibs were found in /usr/local/lib.
> Unbrewed header files were found in /usr/local/include.
> Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
> Unbrewed static libraries were found in /usr/local/lib.

Please try to remove these and try again.

**Comment by slhck** [comment]
Thanks, Mike, for the suggestion. I can see where you're coming from, as these files often cause problems. The files the messages are referring to are from `tcl-tk`. They are probably there because of the official R installer and for me (and Homebrew) they've never caused problems. I don't see an obvious reason why that'd interfere with the Python 3 installation.

Either way, I removed them (using `tcl-tk` and R from Homebrew now) and the error is the same. New logs are here: https://gist.github.com/50dcab59824af884e749bccb0c7b44b6

Note that I can get Python 3 to work if I do:

    $ PYTHONPATH= python3

Which means that I'd probably have to un-set it or set it differently. When I do the same with `pip`, I get:

```
$ PYTHONPATH= pip3
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==8.0.2' distribution was not found and is required by the application
```

Which – at least to me – means that the PYTHONPATH needs to be set differently?

**Comment by MikeMcQuaid** [comment]
Yes, it'll need to be unset before installation it seems. We're looking at a generic solution in https://github.com/Homebrew/brew/issues/932.

**Comment by slhck** [comment]
Yes, apparently I can do

    $ PYTHONPATH= brew install python3

which works fine, but as soon as I run `python3`, I get the same error as above. Same for `pip3` etc. because `PYTHONPATH` still points to `/usr/local/lib/python2.7/site-packages`.

So I'm afraid the issue still persists.

I'm really not an expert on this… What is the *expected* value of this environment variable when both Python 2 and 3 are installed through Homebrew? Is Homebrew supposed to set it? Should it contain both Python 2 and 3 paths?

**Comment by MikeMcQuaid** [comment]
I'm not sure. @tdsmith may be able to give better advice. I believe you need to set it separately depending on the version of Python you are using. Homebrew never sets it and no longer asks you to do so.

**Comment by slhck** [comment]
Apparently everything still works when completely unsetting `PYTHONPATH` in my shell configuration file.

I have no idea who set it though – the fact that it's `/usr/local/lib/python2.7/site-packages` made me think it has something to do with Homebrew. Digging deeper, this line makes everything a little clearer w.r.t. what should be set: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L309

So the only remaining question is *what* set it, but I guess I'll find out eventually.

Thanks for your help so far.

**Comment by MikeMcQuaid** [comment]
We recommended you set it a while ago but now make different recommendations. Sorry for the pain.

**Comment by ilovezfs** [comment]
If I had to "guess":  ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth

**Comment by slhck** [comment]
@ilovezfs There's `no such file or directory: /Users/werner/Library/Python/` — I actually can't find any `homebrew.pth` file on my system.

There's a `homebrew-numpy-nose.pth` though in `/usr/local/lib/python2.7/site-packages`, pointing to `../../../Cellar/numpy/1.12.0/lib/python2.7/site-packages/homebrew-numpy-nose.pth`.

**Comment by ilovezfs** [comment]
Interesting. Might want to check what happens in another user account.

**Comment by slhck** [comment]
Other user account was fine. Found the culprit. It was buried in a config file that loaded some other config file… long story short: It was indeed the `PYTHONPATH` that was hardcoded. I guess it might have to do with Homebrew telling me to do that at some point, I'm not sure.

Thanks, both of you.

**Comment by deering59** [comment]
@slhck So how did exactly you have solved this issue ?
I am facing same problem whilst trying to run pip3 (after running `brew install python3`)

**Comment by slhck** [comment]
@deering59 Make sure that nowhere in your shell configuration files, `PYTHONPATH` is set to point to your Python 2.7 installation. You can check its current value with `echo $PYTHONPATH` – for me it's now empty.

**Comment by deering59** [comment]
@slhck Thank you! It did the trick.

**Comment by nick-lehmann** [comment]
The issue can also occur when you have still activated a virtualenv while trying to create a new one. My zsh does not show me when I have an actived virtualenv and I tried to create a new one. Running the `deactivate` command did the trick for me

**Comment by hero0926** [comment]
@slhck how can i set the python path to 2.xx version in mac which is installed multiple python?

**Comment by slhck** [comment]
@hero0926 Your question isn't really clear. If you've installed multiple Python versions through Homebrew, read the Caveats printed from `brew info python`.

**Comment by hero0926** [comment]
@slhck i found my brew python version by `brew info python` and unfortunately it was 2.7, in /usr/local/lib/python2.7, but i also have installed python 3.4+ with brew. when i set pythonpath to folder which is python 2.xx version is installed, i got jupyter with python2 interpreter.

**Comment by hero0926** [comment]
@slhck i found my brew python version by brew info python and it was 2.7, in /usr/local/lib/python2.7, but i also have installed python 3.4+ with brew with your solution. but still i have a problem in jupyter with 

```
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/site.py", line 75, in <module>
    __boot()
  File "/usr/local/lib/python2.7/site-packages/site.py", line 27, in __boot
    import imp # Avoid import loop in Python >= 3.3
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/imp.py", line 27, in <module>
    import tokenize
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

i guess it's because of the path problem again, thanks for reply.

**Comment by headdab** [comment]
Problem went away for me with:

  pip uninstall enum34  

See:

https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

for a discussion.

**Comment by osencan** [comment]
I came up with the same problem in Ubuntu (14.04) while installing anaconda. First be sure the correct python bin(I notice py3.6 is not installed in my system) is in your /usr/bin (or wherever your binary is) and unset the python path before installation
`unset PYTHONPATH`
