### ISSUE TITLE
wine 2.0

### ISSUE THREAD

**Issue by HudsonAfonso** [Homebrew/homebrew-core#9240]
wine 2.0????

**Comment by MikeMcQuaid** [comment]
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md#bug-reports

**Comment by alexchandel** [comment]
@MikeMcQuaid out of curiosity before I open one, is there a reason we haven't upgraded the wine stable formula to 2.0? Some incompatibility?

**Comment by MikeMcQuaid** [comment]
@alexchandel see https://github.com/Homebrew/homebrew-core/pull/9238
