### ISSUE TITLE
Borgbackup misses dependencies

### ISSUE THREAD

**Issue by fasmat** [Homebrew/homebrew-core#92432]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.3.9-103-ga0ae4a7
ORIGIN: https://github.com/Homebrew/brew
HEAD: a0ae4a7a02d9b6d886fb99a23ddbe07af7979fb6
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 9b79f47c8370c7449aa1470a0c3eb7386e8d5f3d
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1

brew doctor:
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I tried to use `borg mount` to mount one of my backups locally. This used to work a few months ago the last time I tried it.

### What happened (include all command output)?

Borg complains about a missing dependency:

```shell
$ borg mount $BORG_REPO mnt/
borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']
```

### What did you expect to happen?

I expected borg to mount my backup locally using python-llfuse.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install borgbackup
borg mount $BORG_REPO mnt/
```

**Comment by fasmat** [comment]
I tried manually installing the missing python library with:

``
$ pip3 install python-llfuse
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement python-llfuse (from versions: none)
ERROR: No matching distribution found for python-llfuse
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
``

I'm reluctant to follow the advice to upgrade pip, since it together with python were also installed via homebrew (as `python@3.10` dependency of `borgbackup`).

**Comment by gromgit** [comment]
FUSE support in `borgbackup` was _removed_ over a year ago, during the Great macFUSE Deprecation of 2020. See https://github.com/Homebrew/homebrew-core/issues/65525 for the details.

**Comment by fasmat** [comment]
OK, thanks. In case someone stumbles over this in the future:

I fixed my issue by using the tap provided by borgbackup instead of installing borgbackup from homebrew-core: https://github.com/borgbackup/homebrew-tap
