### ISSUE TITLE
minetest.rb --HEAD does not build: IrrlichtMt is required to build the client

### ISSUE THREAD

**Issue by superfloh247** [Homebrew/homebrew-core#92488]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6cdec24b55917e2e4fe83364abd4d0ba06ea2ff6
Core tap last commit: 12 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 10.0.0 build 1000
Git: 2.17.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.13.6-x86_64
CLT: 10.1.0.0.1.1539992718
Xcode: 10.1
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew install minetest --HEAD --verbose

to get latest master build of minetest

### What happened (include all command output)?

MT's fork of Irrlicht is needed to build MT 5.5: IrrlichtMt is required to build the client

there is no dependency for IrrlichtMt in minetest.rb

### What did you expect to happen?

expected result: IrrlichtMt master is cloned into the minetest master directory, cmake is configured to use this version of IrrlichtMt

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install minetest --HEAD --verbose
```

**Comment by SMillerDev** [comment]
We don't support HEAD builds in issues, you can make a pull request if you want to adjust the HEAD build to work better
