### ISSUE TITLE
rocksdb only installs cmake files for rocksdb_lite version of the library

### ISSUE THREAD

**Issue by kobykahane** [Homebrew/homebrew-core#92532]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew config
HOMEBREW_VERSION: 3.3.9-122-g578286a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 578286a94701a2f9c013266e76f02a41079edbaf
Last commit: 14 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 5eeaacb2ec3185cd5cd4f744af871b404adb83a0
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.34.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1637719136
Xcode: 13.2.1
Rosetta 2: false

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /opt/homebrew/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/opt/homebrew/sbin:$PATH"' >> ~/.zshrc
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

rocksdb provides both rocksdb and rocksdb_lite version since https://github.com/Homebrew/homebrew-core/pull/9642. I am attempting to consume the homebrew installed rocksdb version of the library via cmake using find_package in Config mode. That requires the cmake config files for rocksdb to be installed, but only the ones for rocksdb_lite are installed:

```
% grep add_library /opt/homebrew/Cellar/rocksdb/6.27.3/lib/cmake/rocksdb/RocksDBTargets.cmake
add_library(RocksDB::rocksdb_lite STATIC IMPORTED)
add_library(RocksDB::rocksdb-shared_lite SHARED IMPORTED)
```

Note how only lite targets are available. I believe this occurs because `make install` was invoked by the formula build twice - once for rocksdb and another for rocksdb_lite and the latter invocation overwrote the non-lite cmake files with the lite files.

### What happened (include all command output)?

Attempting to configure a cmake project with a find_package for RocksDB in config mode fails to find a `RocksDB::rocksdb` target, because the cmake files installed by the formula only include the rocksdb_lite variants.

### What did you expect to happen?

The rocksdb formula should install cmake files for the non-lite version of the library as well, so it's usable with cmake find_package in CONFIG mode.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
% brew install cmake rocksdb
% cd rocksdb_test
% cat CMakeLists.txt
cmake_minimum_required(VERSION 3.22)
project(rocksdb_test)
set(CMAKE_CXX_STANDARD 20)
find_package(RocksDB REQUIRED CONFIG)
add_executable(rocksdb_test rocksdb_test.cpp)
target_link_libraries(rocksdb_test PRIVATE RocksDB::rocksdb)
% mkdir build
% cd build
% cmake ..
...
CMake Error at CMakeLists.txt:5 (add_executable):
  Target "rocksdb_test" links to target "RocksDB::rocksdb" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by SMillerDev** [comment]
The formula installs both normal and lite versions: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rocksdb.rb

If one of them does not show up that means upstream CMake does not set up the install correctly.

**Comment by gromgit** [comment]
Looking back in Homebrew history, I noticed [this PR](https://github.com/Homebrew/homebrew-core/pull/9642) which added the lite version as an _option_, which was then added to "mainstream" during the Great Deoptioning Exercise. I suspect upstream never intended to have both "full-fat" and "lite" versions coexisting, since there seems to be only one CMake config file installed for RocksDB.

Since nothing in core depends on RocksDB, perhaps we should hive the "lite" version out into its own formula?

**Comment by kobykahane** [comment]
I think it's evident from upstream's CMakeLists (https://github.com/facebook/rocksdb/blob/main/CMakeLists.txt#L526) that indeed the lite version was intended as a build option for the library and thus a single build won't provide both the lite and normal flavors as distinct targets. I agree with @gromgit that it would be best to separate lite into a distinct formula.

**Comment by gromgit** [comment]
Before I go through the trouble of doing the split, is there really a use-case for the lite version in a Homebrew context? I don't use RocksDB myself, but I gather that the lite version is mostly targeted at mobile clients (Android/iOS), which Homebrew doesn't exactly service.

**Comment by kobykahane** [comment]
> Before I go through the trouble of doing the split, is there really a use-case for the lite version in a Homebrew context? I don't use RocksDB myself, but I gather that the lite version is mostly targeted at mobile clients (Android/iOS), which Homebrew doesn't exactly service.

According to https://github.com/Homebrew/homebrew-core/commit/6445d90c4723fd9f27e1e0e4ac4ab8f913f3f31a it seems the lite variant was introduced due to some osquery "recommendation", but I doubt there's any significant downside to simply having it use the full library.

**Comment by gromgit** [comment]
After doing the split, and comparing the two hierarchies:
```
$ diff --brief -r /usr/local/opt/rocksdb*
Only in /usr/local/opt/rocksdb-lite/.brew: rocksdb-lite.rb
Only in /usr/local/opt/rocksdb/.brew: rocksdb.rb
Files /usr/local/opt/rocksdb/INSTALL_RECEIPT.json and /usr/local/opt/rocksdb-lite/INSTALL_RECEIPT.json differ
Only in /usr/local/opt/rocksdb: bin
Files /usr/local/opt/rocksdb/lib/cmake/rocksdb/RocksDBTargets-release.cmake and /usr/local/opt/rocksdb-lite/lib/cmake/rocksdb/RocksDBTargets-release.cmake differ
Files /usr/local/opt/rocksdb/lib/cmake/rocksdb/RocksDBTargets.cmake and /usr/local/opt/rocksdb-lite/lib/cmake/rocksdb/RocksDBTargets.cmake differ
Only in /usr/local/opt/rocksdb/lib: librocksdb.6.27.3.dylib
Only in /usr/local/opt/rocksdb/lib: librocksdb.6.dylib
Only in /usr/local/opt/rocksdb/lib: librocksdb.a
Only in /usr/local/opt/rocksdb/lib: librocksdb.dylib
Only in /usr/local/opt/rocksdb-lite/lib: librocksdb_lite.6.27.3.dylib
Only in /usr/local/opt/rocksdb-lite/lib: librocksdb_lite.6.dylib
Only in /usr/local/opt/rocksdb-lite/lib: librocksdb_lite.a
Only in /usr/local/opt/rocksdb-lite/lib: librocksdb_lite.dylib
```
I'm now inclined to just rename the "lite" CMake files and retain a single formula, instead of having two formulae that have to be bumped simultaneously, and are mutually conflicting.

**Comment by carlocab** [comment]
Closed in https://github.com/Homebrew/homebrew-core/pull/92619
