### ISSUE TITLE
Crystal-lang should first build non-optimized then use that to build --release

### ISSUE THREAD

**Issue by yyyc514** [Homebrew/homebrew-core#9258]
See comments here: https://github.com/crystal-lang/crystal/issues/3939

But the gist:

> It's often quicker to build without --release build on the platform, then build with --release using the unoptimized build.

Any objections to having the crystal-lang package adopt this behavior when building --release?

**Comment by MikeMcQuaid** [comment]
Seems sensible 👍. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by ysbaddaden** [comment]
Don't. My word "often" was misunderstood: it's better to use an optimized build in the whole majority of cases. In some unidentified cases, the initial build may take a very long time, and *only* in those specific cases, first building without optimizations then with optimizations may be faster.

**Comment by MikeMcQuaid** [comment]
@ysbaddaden Good to know, thanks.

**Comment by yyyc514** [comment]
What am I missing?  I have common hardware (MBPr), common OS (Sierra), building it AFAIK according to instructions... yet I'm an unidentified case?
