### ISSUE TITLE
Gnupg: `gpg -k` throws sqlite error(?) on MacBook Pro M1 Max, Monterey 12.1

### ISSUE THREAD

**Issue by ikester** [Homebrew/homebrew-core#92628]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 96137bc19e68398ebbb7033379df288cd8b9a3f9
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8e9cf9b464c41eca611af29bad16eeef2e87becd
Core tap last commit: 9 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.34.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false


brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`gpg -k` to list all the GnuPG keys in the system.

### What happened (include all command output)?

Following error gets logged in the Console:

`duplicate column name: effective_policy in "alter table bindings add column effective_policy INTEGER DEFAULT 0 CHECK (effective_policy in (0, 1, 2, 3, 4, 5));"`

Additional information attached to the error:
/opt/homebrew/Cellar/gnupg/2.3.4/bin/gpg (/usr/lib/libsqlite3.dylib)
Subsystem: com.apple.libsqlite3 Category: logging

### What did you expect to happen?

I did not expect to see an error in the console when running this command.

Furthermore, I don't know how or why libsqlite is involved when running the command.

Given GnuPG is such a security sensitive program, I'm concerned to see an additional component listed in the error. Not sure what a sql statement is doing here.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Just run the `gpg` command for listing keys:

`gpg -k`

And check the MacOS Console for error messages from `gpg`
```

**Comment by carlocab** [comment]
Can't reproduce. What's the output of `brew info gnupg` and `brew linkage gnupg`?

**Comment by ikester** [comment]
Thanks for paying attention to this @carlocab. Here's the output of those commands. You'll notice that `/usr/lib/libsqlite3.dylib` is listed in the output of the linkage command.

```
> brew info gnupg
gnupg: stable 2.3.4 (bottled)
GNU Pretty Good Privacy (PGP) package
https://gnupg.org/
/opt/homebrew/Cellar/gnupg/2.3.4 (149 files, 13.6MB) *
  Poured from bottle on 2022-01-05 at 18:42:53
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gnupg.rb
License: GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔
Required: gettext ✔, gnutls ✔, libassuan ✔, libgcrypt ✔, libgpg-error ✔, libksba ✔, libusb ✔, npth ✔, pinentry ✔
==> Analytics
install: 84,114 (30 days), 283,195 (90 days), 959,361 (365 days)
install-on-request: 78,066 (30 days), 264,914 (90 days), 893,427 (365 days)
build-error: 49 (30 days)
```

```
> brew linkage gnupg
Warning: linkage is a developer command, so
Homebrew's developer mode has been automatically turned on.
To turn developer mode off, run brew developer off

System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libsqlite3.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /opt/homebrew/opt/gettext/lib/libintl.8.dylib (gettext)
  /opt/homebrew/opt/gnutls/lib/libgnutls.30.dylib (gnutls)
  /opt/homebrew/opt/libassuan/lib/libassuan.0.dylib (libassuan)
  /opt/homebrew/opt/libgcrypt/lib/libgcrypt.20.dylib (libgcrypt)
  /opt/homebrew/opt/libgpg-error/lib/libgpg-error.0.dylib (libgpg-error)
  /opt/homebrew/opt/libksba/lib/libksba.8.dylib (libksba)
  /opt/homebrew/opt/npth/lib/libnpth.0.dylib (npth)
  /opt/homebrew/opt/readline/lib/libreadline.8.dylib (readline)
Indirect dependencies with linkage:
  readline
Dependencies with no linkage:
  libusb
```

**Comment by carlocab** [comment]
No idea, unfortunately. Try `brew reinstall gnupg`. If that doesn't help, try `brew reinstall $(brew deps gnupg) gnupg`. If that still doesn't work, try attaching `gpg` to a debugger and see if you can get a backtrace.

**Comment by ikester** [comment]
Still get the error after running both reinstall commands. Are you testing on an M1 Mac? I'll try to attach a debugger to get a backtrace of the call to the sqlite3 library. But I'm puzzled by the fact that you don't get the same error.

Do you at least see the `/usr/lib/libsqlite3.dylib` library listed when you run the `brew linkage gnupg` command?

**Comment by carlocab** [comment]
> Are you testing on an M1 Mac?

Yes. Not the shiny new M1 Max variant, but it probably doesn't make a difference.

> Do you at least see the `/usr/lib/libsqlite3.dylib` library listed when you run the `brew linkage gnupg` command?

Yes.

**Comment by ikester** [comment]
> I'm actually suspecting you have corrupt data in your `~/.gnupg` directory.

That was absolutely the right instinct! After renaming the existing `~/.gnupg` dir and letting gpg create a new one the error no longer appears. I have export/imported all my keys and it works well, so I doubt I will try to root cause the issue at this point.

Thank you very much for your help and insights. Closing the issue now.
