### ISSUE TITLE
go: add tour to formula

### ISSUE THREAD

**Issue by sinwav** [Homebrew/homebrew-core#9272]
The binaries and packages available on golang.org include the go tour, a separate repository, whereas building from source does not include it by default, although it does include the go tools repository.

I believe we just need to add it as a resource similar to how the gotools are included. I think I have it properly edited already, but I am not 100% sure about that. Do I need to specify the branch & revision, or just the url of the repository?

https://github.com/Homebrew/homebrew-core/blob/master/Formula/go.rb

**Comment by MikeMcQuaid** [comment]
> I believe we just need to add it as a resource similar to how the gotools are included. I think I have it properly edited already, but I am not 100% sure about that. Do I need to specify the branch & revision, or just the url of the repository?

We want revision and ideally a tag, thanks! Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
