### ISSUE TITLE
privoxy does not save log to /usr/local/var/log/privoxy/logfile when started with `brew services`

### ISSUE THREAD

**Issue by Cosmius** [Homebrew/homebrew-core#9288]
### Bug reports:

`privoxy `does not save log when invoked with `--no-daemon`, and the shipped plist add this to the arguments.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by Cosmius** [comment]
I just tried, but I don't know how to deal with launchd :(

**Comment by MikeMcQuaid** [comment]
Something like:
```
        <key>StandardErrorPath</key>
        <string>#{var}/log/questdb.log</string>
        <key>StandardOutPath</key>
        <string>#{var}/log/questdb.log</string>
``` 

may work

**Comment by Cosmius** [comment]
But this prevents the log file path configurable from the privoxy/config :(

Much better than nothing.

Thanks
