### ISSUE TITLE
SHA256 mismatch godep 78

### ISSUE THREAD

**Issue by uglygus** [Homebrew/homebrew-core#9293]
I was able to reproduce this on more than one machine.

$brew -v
Homebrew 1.1.8
Homebrew/homebrew-core (git revision f753a; last commit 2017-01-26)

$brew upgrade godep
==> Upgrading 1 outdated package, with result:
godep 78
==> Upgrading godep 
==> Using the sandbox
==> Downloading https://github.com/tools/godep/archive/v78.tar.gz
==> Downloading from https://codeload.github.com/tools/godep/tar.gz/v78
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: acf13d67baeb8c477ec1ed1be8054a3f3dbac81f0230c11d80e08f3334a2f4af
Actual: 247cbebffff1a5e077287cc7e2f84ca30266f9e535d1182823ececf9bf37b18a
Archive: /Users/karen/Library/Caches/Homebrew/godep-78.tar.gz
To retry an incomplete download, remove the file above.

**Comment by ilovezfs** [comment]
Ug. They must have retagged it.

**Comment by ilovezfs** [comment]
Yeah: https://github.com/tools/godep/pull/530
