### ISSUE TITLE
Postinstall failed due to PermissionError: [Errno 13] Permission denied: 'cli-arm64.exe'

### ISSUE THREAD

**Issue by ChandruDW** [Homebrew/homebrew-core#92950]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config

HOMEBREW_VERSION: 3.3.10-11-g633202d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 633202dac6be86b1cbae88e5640acfcb7d2ea743
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: afc0bb2a05f50ad63b999aa78b4507d411e2b363
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5.2-x86_64
CLT: 12.0.0.32.28
Xcode: N/A

brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  docker-machine

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  docker
  six
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

brew postinstall python@3.9

==> Postinstalling python@3.9
==> /usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensur
Last 15 lines from /Users/chandru/Library/Logs/Homebrew/python@3.9/post_install.02.python3:
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 463, in run
    self._handle_target_dir(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 518, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 727, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 684, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 682, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'cli-arm64.exe'

### What happened (include all command output)?

brew postinstall python@3.9
==> Postinstalling python@3.9
==> /usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m ensurepip
==> /usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m pip install -v --no-deps --no-index --upgrade --isolated --target=/usr/local/lib/python3.9/site-packages /usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensur
Last 15 lines from /Users/chandru/Library/Logs/Homebrew/python@3.9/post_install.02.python3:
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 463, in run
    self._handle_target_dir(
  File "/usr/local/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 518, in _handle_target_dir
    shutil.rmtree(target_item_dir)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 727, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 684, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 682, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'cli-arm64.exe'
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9

### What did you expect to happen?

Should install pip3.9, but only pip3.8 is installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python@3.9
When post install failed, again I ran,
brew postinstall python@3.9

Now it shows the below error,
PermissionError: [Errno 13] Permission denied: 'cli-arm64.exe'
```

**Comment by carlocab** [comment]
What's the output of
```sh
find "$(brew --prefix)" -name 'cli-arm64.exe' -exec ls -la '{}' +
```

**Comment by ChandruDW** [comment]
-rw-r--r--  1 root  admin  137216 Jan 11 13:19 ./cli-arm64.exe

**Comment by ChandruDW** [comment]
I given execute access to cli-arm64.exe but after that I am getting different error

 brew postinstall python@3.9
==> Postinstalling python@3.9
==> /usr/local/Cellar/python@3.9/3.9.9/bin/python3 -m ensurepip
Last 15 lines from /Users/chandru/Library/Logs/Homebrew/python@3.9/post_install.01.python3:
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py", line 206, in _main
    return _bootstrap(
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py", line 125, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ensurepip/__init__.py", line 34, in _run_pip
    return subprocess.run([sys.executable, "-c", code], check=True).returncode
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/opt/python@3.9/bin/python3.9', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/private/tmp/tmpwnl3x5vh/setuptools-59.0.1-py3-none-any.whl\', \'/private/tmp/tmpwnl3x5vh/pip-21.3.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/private/tmp/tmpwnl3x5vh\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall python@3.9

**Comment by gromgit** [comment]
Two things:

1. `brew config` says you're on an Intel Mac, so I don't know why the install is trying to execute the _ARM64 Windows_ `cli-arm64.exe`.
2. The Python stacktrace you posted is incomplete. `brew gist-logs python@3.9` and post the output URL here.

**Comment by ChandruDW** [comment]
chandru@ChandraekarsMBP ~ %  brew gist-logs python@3.9
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

chandru@ChandraekarsMBP ~ % softwareupdate --all --install --force
Software Update Tool

Finding available software
Downloading macOS Big Sur 11.6.2
Downloading: 100.00%
Downloaded: macOS Big Sur 11.6.2
Attempting to quit apps: (
    "com.apple.Image_Capture",
    "com.apple.iMovieApp",
    "com.apple.dt.Xcode",
    "com.apple.configurator.ui",
    "com.apple.iTunes",
    "com.apple.FinalCut",
    "com.apple.configurator"
)
Successfully quit all apps

Downloaded Device Support Update
Installing Device Support Update
Done with Device Support Update
Done.
chandru@ChandraekarsMBP ~ %  brew gist-logs python@3.9
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

chandru@ChandraekarsMBP ~ % sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Password:
xcode-select: note: install requested for command line developer tools
chandru@ChandraekarsMBP ~ %  brew gist-logs python@3.9
Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.1.

**Comment by gromgit** [comment]
> xcode-select: note: install requested for command line developer tools

This should've popped up a dialog box to initiate the CLT install. Did you complete that portion of the install?

Anyway, since `brew gist-logs` isn't working for you at this point, post the contents of /Users/chandru/Library/Logs/Homebrew/python@3.9/post_install.01.python3.

**Comment by gromgit** [comment]
Given all the above, your `python@3.9` site-packages seems b0rked, and the main Python install is also suspect. Perhaps someone else who's a Python guru can advise on a better approach, but I'd try:
```sh
command -v pip3.9   # DO NOT CONTINUE IF THIS IS NOT /usr/local/bin/pip3.9
pip3.9 freeze | tee /tmp/frozen.lst    # DO NOT CONTINUE IF THIS ERRORS OUT
brew rm --ignore-dependencies --force python@3.9
rm -fr /usr/local/lib/python3.9
brew install python@3.9
command -v pip3.9   # DO NOT CONTINUE IF THIS IS NOT /usr/local/bin/pip3.9
pip3.9 install -U -r /tmp/frozen.lst
```

**Comment by ChandruDW** [comment]
command -v pip3.9 - It returns empty
And only post install causing the problem where pip3.9 will installed in post install

**Comment by gromgit** [comment]
OK, your Homebrew Python setup looks well and truly messed-up for some reason. Assuming you've never done a `pip install <module>` with this version of Python, it's time to nuke and reinstall, I guess:
```
brew rm --ignore-dependencies --force python@3.9
rm -fr /usr/local/lib/python3.9
brew install python@3.9
```
