### ISSUE TITLE
mysql@5.5 doesn't correctly install on OS X 10.11.6 El Capitan

### ISSUE THREAD

**Issue by stantonk** [Homebrew/homebrew-core#9303]
### Bug reports:

Installing `mysql@5.5` doesn't complete. mysqld doesn't start, and running `brew services start mysql@5.5` doesn't work.

After running `brew gist-logs mysql@5.5`, I looked at the gist and decided to try what I saw in the post install:

```
You can start the MySQL daemon with:
cd /usr/local/Cellar/mysql@5.5/5.5.49 ; /usr/local/Cellar/mysql@5.5/5.5.49/bin/mysqld_safe &
```

and that worked!?

After I then shut down mysql using:

```
sudo mysqladmin -uroot -p -h127.0.0.1 shutdown
```

I was then finally able to get `brew services start|stop mysql@5.5` to work.

This smells of something not getting quite properly setup during the install, but I'm not sure what and I've probably erased the evidence of what was causing it. But I hope this helps locate whatever might have prevented this from working out of the box.

https://gist.github.com/stantonk/bf86fd1622ed366726631730a34720be

Here's the events from the initial install:
```
$  brew install mysql@5.5
==> Downloading https://homebrew.bintray.com/bottles/mysql@5.5-5.5.49.el_capitan.bottle.tar.gz
Already downloaded: /Users/kevin/Library/Caches/Homebrew/mysql@5.5-5.5.49.el_capitan.bottle.tar.gz
==> Pouring mysql@5.5-5.5.49.el_capitan.bottle.tar.gz
==> Using the sandbox
==> /usr/local/Cellar/mysql@5.5/5.5.49/bin/mysql_install_db --verbose --user=kevin --basedir=/usr/local/Cellar/mysql@5.5/5.5.49 --datadir=/usr/local/var/mysql --tmpdir=/tmp
==> Caveats
A "/etc/my.cnf" from another install may interfere with a Homebrew-built
server starting up correctly.

To connect:
    /usr/local/opt/mysql@5.5/bin/mysql -uroot

To have launchd start mysql@5.5 now and restart at login:
  brew services start mysql@5.5
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/mysql55/bin/mysql.server start
==> Summary
🍺  /usr/local/Cellar/mysql@5.5/5.5.49: 6,485 files, 192.6M

~  $  /usr/local/opt/mysql55/bin/mysql.server start
-bash: /usr/local/opt/mysql55/bin/mysql.server: No such file or directory
```

**Comment by MikeMcQuaid** [comment]
I've fixed the manual start instructions, thanks. Can you elaborate on:

> running brew services start mysql@5.5 doesn't work.

What is the output of that? What is the output of `brew services list` before and after?

**Comment by stantonk** [comment]
@MikeMcQuaid i don't have the console up anymore, but the output from attempting `brew services start mysql@5.5` said that it had started mysqld, but a `ps -ef | grep mysql` came up empty, and subsequently `brew services list` showed msyql@5.5 was in the `Error` state.

**Comment by MikeMcQuaid** [comment]
If it says `Error` then in future you'll need to check your MySQL logs. Nothing additional we can do if you can't reproduce this, sorry.
