### ISSUE TITLE
gnuradio package no longer installs gnuradio-companion GUI tool

### ISSUE THREAD

**Issue by axman6** [Homebrew/homebrew-core#9317]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

After installing `gnuradio`, the `gnuradio-companion` executable is no longer installed. `gnuradio-config-info` is installed (and confirmed to be installed when uninstalling this package).

### brew config

```shell
$ brew config                         
HOMEBREW_VERSION: 1.1.8
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e59ada508727f11464595893783beb914c26f60b
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 26f8cf0800081a07b855fda8e31a63f8b2ec2e70
Core tap last commit: 8 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25, 1.7.0_75
macOS: 10.12.2-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.9 => /opt/X11
```

### brew doctor
 ```
$ brew doctor
Your system is ready to brew.
```
### brew gist-logs gnuradio
```
$ brew gist-logs gnuradio
Error: No logs.
```

**Comment by ilovezfs** [comment]
Yup, this is due to the retirement of Qt 4 from Homebrew.

See https://github.com/gnuradio/gnuradio/issues/1090, which will eventually rectify the situation.

**Comment by axman6** [comment]
Thanks for the heads up. Glad there's a good reason and not someone just forgetting to compile with a flag that builds the GUI.

**Comment by ilovezfs** [comment]
@axman6 hehe yeah. If you need an immediate solution: https://github.com/cartr/homebrew-qt4 + the old formula will get you back up and running.

**Comment by HughAndersonNUS** [comment]
@ilovezfs - can you just clarify a little?

I did:
 brew tap cartr/qt4
 brew tap-pin cartr/qt4
 brew install qt
(which worked fine). But then if I installed gnuradio again it did not include gnuradio-companion. What did you mean by "the old formula"? 

Cheers Hugh

**Comment by ilovezfs** [comment]
```
git --no-pager show 4004e52cd4976e5753d540ad26979e96cf364e3e^:Formula/gnuradio.rb
```

**Comment by HughAndersonNUS** [comment]
OK - so I have the new formula. But when I try to run it, it does this:
```
Hughs-MacBook-Pro:homebrew-core hugh$ brew install ./gnuradio.rb 
Error: Operation already in progress for qt
Another active Homebrew process is already using qt.
Please wait for it to finish or terminate it to continue.

```
If I delete all the lock files in /usr/local/var/homebrew/locks, it still happens. There is no other brew process running.

**Comment by HughAndersonNUS** [comment]
I'll answer my own question. I'm not sure if this is what I should do, but I changed the line that said
    depends_on "qt"
to
    depends_on "cartr/homebrew-qt4/qt"
And then it works... Thanks to @ilovezfs ...

**Comment by muellermartin** [comment]
Could you (package maintainers) please add a notice to the current gnuradio Forumla that GRC is not included, as I just wasted some time to figure out why.

**Comment by pcwhy** [comment]
Hopefully, the gnuradio-for-mac-without-macports may work for you
https://github.com/cfriedt/gnuradio-for-mac-without-macports
