### ISSUE TITLE
"Perforce" formula was moved to cask, but is unavailable in cask.

### ISSUE THREAD

**Issue by zbentley** [Homebrew/homebrew-core#9335]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

##Issue

I ran `brew update` today, and it indicated that the `perforce` formula had been moved to `cask`. However, it was unable to install it from `cask`:

```==> perforce has been moved to Homebrew-Cask.
==> brew uninstall --force perforce
Uninstalling perforce... (3 files, 3.6M)
==> brew prune
Pruned 194 symbolic links and 12 directories from /usr/local
==> brew cask install perforce
Error: No available Cask for perforce
Error: nothing to install
```

After that, I issued `brew install perforce`. It found the formula in the `homebrew/binary` tap, and installed it successfully.

That seems like incorrect behavior; this fomula should only move to install from `cask` if it's already present in the caskroom. 

I know that this is low on info/not a great report, and am happy to provide more; just let me know what else is needed.

Thanks!

**Comment by MikeMcQuaid** [comment]
It seems you have issues with your Caskroom checkout. I suggest filing an issue on their repository.
