### ISSUE TITLE
mysql@5.6 failed to install on macOS 12.1 

### ISSUE THREAD

**Issue by alishaedington** [Homebrew/homebrew-core#93369]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
## brew config output: 
alishaedington@MacBookPro ~ % brew config
HOMEBREW_VERSION: 3.3.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 537036ab3627b65d71dfa920b98d43774f861dec
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 930cc2bf5f373f34556017b367aa76eaa4df12ac
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false

## brew doctor output: 
alishaedington@MacBookPro ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to install mysql 5.6 because that is the version used in the existing repo for a company application. 

## The original error:
alishaedington@MacBookPro ~ % brew install mysql@5.6
Warning: mysql@5.6 has been deprecated because it is not supported upstream!
Error: mysql@5.6: no bottle available!
You can try to install from source with:
brew install --build-from-source mysql@5.6
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

I tried uninstalling and reinstalling homebrew, to make sure that there was no issues with the install, and the brew command is still returning the same error. 

### What did you expect to happen?

I expected the version (5.6) of mysql to be installed. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install mysql@5.6
```

**Comment by carlocab** [comment]
MySQL 5.6 was EOL in 2018: https://www.mysql.com/support/eol-notice.html

We only support maintained versions of software. I'm also pretty sure that MySQL 5.6 does not build on M1 Macs.

That said, you might be able to install `mysql@5.6` if you install Rosetta and then set up a Rosetta installation of Homebrew in `/usr/local`. Software installed in a `/usr/local` installation of Homebrew are compiled for x86_64, and will run under Apple's Rosetta translation layer.

You can install Homebrew into `/usr/local` by running the install script under Rosetta (prepend `arch -x86_64`), and run that version of Homebrew using `arch -x86_64 /usr/local/bin/brew`.
