### ISSUE TITLE
aerc: versioned path not changed after upgrade

### ISSUE THREAD

**Issue by ancarda** [Homebrew/homebrew-core#93407]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

_logs removed -- the problem has been identified and the logs are not relevant_

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I recently [created a PR to update aerc](https://github.com/Homebrew/homebrew-core/pull/93362). This appears to have broken the formula. I don't know why -- this is my first time sending a contribution to Homebrew.

### What happened (include all command output)?

Once updated, aerc no longer launches:

```
$ aerc
Failed to load config: Can't find template "forward_as_body" in any of [/usr/local/Cellar/aerc/0.5.2/share/aerc/templates/]
```

Going by the file path, it seems to be trying to read files that were installed by the previous version (0.5.2).

Creating that directory as a symlink (`/usr/local/Cellar/aerc/0.5.2 -> 0.7.1`) will, for now, let aerc launch.

### What did you expect to happen?

aerc to launch normally without requiring that symlink to be created.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install aerc
aerc
```

**Comment by ancarda** [comment]
Okay, I've figured out what the issue is. There's still references in `~/Library/Preferences/aerc`, such as:

```
aerc.conf:stylesets-dirs=/usr/local/Cellar/aerc/0.5.2/share/aerc/stylesets/
aerc.conf:subject,~^\[PATCH=awk -f /usr/local/Cellar/aerc/0.5.2/share/aerc/filters/hldiff
aerc.conf:text/html=/usr/local/Cellar/aerc/0.5.2/share/aerc/filters/html
aerc.conf:text/*=awk -f /usr/local/Cellar/aerc/0.5.2/share/aerc/filters/plaintext
aerc.conf:template-dirs=/usr/local/Cellar/aerc/0.5.2/share/aerc/templates/
```

What should Homebrew do in this situation? Should the file be edited, e.g. `s/$old_share_path/$new_share_path/`? It can't be replaced as the user may have modified this file.

Deleting this file and reinstalling fixed the issue. So a completely clean install works, just upgrading is broken. Since this file is in `~/Library/Preferences/`, even if you `brew uninstall --zap`, the file won't be deleted.

**Comment by SMillerDev** [comment]
Brew won't touch user files so the program should fix this for itself.

**Comment by SMillerDev** [comment]
Maybe you can suggest a build setting that allows the build to define these paths?
