### ISSUE TITLE
gitlab-ci-multi-runner shouldn't depend on docker

### ISSUE THREAD

**Issue by Toady00** [Homebrew/homebrew-core#9347]
The runner can run with or without docker. It isn't a hard dependency. And if like me you have docker for mac installed, and don't want to symlink the homebrew docker then you get the error:

```
You must `brew link docker` before gitlab-ci-multi-runner can be installed
```

Please remove the docker dependency. The `docker-swarm` formula doesn't even depend on docker.

**Comment by ilovezfs** [comment]
```
bash-4.4$ brew info gitlab-ci-multi-runner
gitlab-ci-multi-runner: stable 1.10.3, HEAD
The official GitLab CI runner written in Go
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gitlab-ci-multi-runner.rb
==> Dependencies
Build: go ✘, xz ✔
Recommended: docker ✘
==> Requirements
Build: git ✔
==> Options
--without-docker
	Build without docker support
--HEAD
	Install HEAD version
bash-4.4$ 
```

I suggest you
```
brew install --without-docker gitlab-ci-multi-runner
```

**Comment by Toady00** [comment]
I can see where that may make sense but according to the gitlab runner docs, if I install it like that then I don't believe I would have support for using docker. That defeats the point. I have docker for mac installed. I want to use docker. I don't want the gitlab runner failing to install because I haven't symlinked the brew version of docker. I don't care if it does install the brew version of docker as long as it doesn't have to be symlinked.

**Comment by ilovezfs** [comment]
You can `brew unlink docker` after the build.

**Comment by Toady00** [comment]
and I'd have to do that every time I upgrade?

**Comment by ilovezfs** [comment]
yup

**Comment by ilovezfs** [comment]
@Toady00 It's not clear to me what in the formula would disable docker support if you pass --without-docker. You may want to test it before concluding docker support is actually dropped entirely simply because brew docker isn't installed during the build.

**Comment by Toady00** [comment]
@ilovezfs Maybe I'm reading the gitlab runner docs wrong.

**Comment by ilovezfs** [comment]
Probably. If you read the formula, we build in the docker bits for arm and x86_64 regardless of the docker option.
