### ISSUE TITLE
postgis and  proj@7 - doctor complains

### ISSUE THREAD

**Issue by mrspirytus** [Homebrew/homebrew-core#93667]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  proj@7

Warning: Putting non-prefixed coreutils in your path can cause GMP builds to fail.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I installed progress and PostGIS on my Mac M1. Running doctor now I have one complaint. Looks like proj latest is on 8.x
Are there any fixes to clear doctor?

### What happened (include all command output)?

Running doctor complains about proj@7

### What did you expect to happen?

I expect no errors :)

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install postgresql
brew install postgis
```

**Comment by Bo98** [comment]
You can safely ignore the warning, but we should be able to move this to PROJ 8 given I think the issues with it were fixed in 3.1.2.

**Comment by mrspirytus** [comment]
Excellent, I will wait for an update. I know I might be pushing it by such a question :). Any general ETA?

**Comment by carlocab** [comment]
Giving an ETA is difficult -- it's generally when someone finds time to pick it up. You can help speed it up by opening a pull request. We'd be happy to help you along wherever you get stuck.

**Comment by mrspirytus** [comment]
Sure, I can try to take a crack at it.
I did check out https://proj.org/ and 8.2.1 is the latest. brew also has such a version already.
This is my first time trying to update brew. Any pointers on where to start? General steps? commands? etc.

**Comment by carlocab** [comment]
The `CONTRIBUTING` guide in this repo is a good place to start. There's also this: https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request

A few key pointers that are easy to miss:
1. Have only one commit per formula modified (and only one formula modified per commit).
2. Put the name of the formula first in your commit message.
3. Don't forget the `revision` bump since you'll be changing a formula's dependencies.

If any of these don't make sense to you, feel free to just open a PR and we'll help you sort it out.
