### ISSUE TITLE
pdf-redact-tools 0.1.1

### ISSUE THREAD

**Issue by micahflee** [Homebrew/homebrew-core#937]
I'm the upstream developer for PDF Redact Tools. There's been a Homebrew formula for version 0.1 for awhile, and I just released version 0.1.1. I've never contributed to Homebrew before and I'm running into an issue making a pull request.

If I edit https://github.com/Homebrew/homebrew-core/blob/master/Formula/pdf-redact-tools.rb and change:

```ruby
class PdfRedactTools < Formula
  desc "Securely redacting and stripping metadata"
  homepage "https://github.com/micahflee/pdf-redact-tools"
  url "https://github.com/micahflee/pdf-redact-tools/archive/v0.1.tar.gz"
  sha256 "9d5f095e5d056eb527c08c4736b45c99aa6399424dd6ed7155e3d7cd1600c55e"
  head "https://github.com/micahflee/pdf-redact-tools.git"
```

To:

```ruby
class PdfRedactTools < Formula
  desc "Securely redacting and stripping metadata"
  homepage "https://github.com/micahflee/pdf-redact-tools"
  url "https://github.com/firstlookmedia/pdf-redact-tools/archive/v0.1.1.tar.gz"
  sha256 "1b6ade577f2eeb8ea6ddfd1b7b9a6925a6c9a929ea98700e8015676ee1a13155"
  head "https://github.com/firstlookmedia/pdf-redact-tools.git"
```

It fails trying to download a bottle:

```sh
$ brew install pdf-redact-tools  
==> Downloading https://homebrew.bintray.com/bottles/pdf-redact-tools-0.1.1.el_capitan.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pdf-redact-tools"
Download failed: https://homebrew.bintray.com/bottles/pdf-redact-tools-0.1.1.el_capitan.bottle.tar.gz
```

But if I just comment out bottle block, it all seems to work fine. I'm not sure what the bottle block does. Should I make a PR for this commit? https://github.com/micahflee/homebrew-core/commit/775d86456e8458db21438ad70900e539cf7134a7

**Comment by UniqMartin** [comment]
Bottles are our binary packages, that will be generated by our CI once you submit the update as a PR and will become available once we merge that PR. To test locally that everything works as expected with the updated formula, you'll have to install with `brew install --build-from-source pdf-redact-tools`.

> Should I make a PR for this commit? https://github.com/micahflee/homebrew-core/commit/775d86456e8458db21438ad70900e539cf7134a7

Please modify this commit to leave the `bottle do` block as-is prior to submitting your PR; it will be automatically updated by our CI once we pull your update to the formula. Oh, and also expect to be asked why the GitHub repository for the stable archive and the HEAD URL have changed. Our [CONTRIBUTING document](https://github.com/Homebrew/homebrew-core/blob/master/.github/CONTRIBUTING.md) has an overview of the process and links to additional documentation, if you like to learn more about it.

**Comment by DomT4** [comment]
Micah works for the Intercept, First Look Media is the parent organisation. That's likely the URL shift.

**Comment by micahflee** [comment]
Yes exactly. I built PDF Redact Tools for my work at First Look Media before they created a github organization. When they did, I transferred the repository to the organization. I just opened a pull request: #974. Let me know there if there are still any issues with this PR.

**Comment by UniqMartin** [comment]
@DomT4 @micahflee Thanks for the explanation! I didn't know that (and didn't research it either).
