### ISSUE TITLE
Git: manpages are out of date

### ISSUE THREAD

**Issue by smancill** [Homebrew/homebrew-core#94005]
Latest Git 2.35 uses manpages from Git 2.34.

See current formula:

https://github.com/Homebrew/homebrew-core/blob/79e5e219f76f6c96efc79eb6e9927d7433bc70a7/Formula/git.rb#L3-L5

https://github.com/Homebrew/homebrew-core/blob/79e5e219f76f6c96efc79eb6e9927d7433bc70a7/Formula/git.rb#L35-L43
```

**Comment by carlocab** [comment]
Please read the bug report form:

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.
