### ISSUE TITLE
OpenSSH: dyld: Library not loaded: /usr/local/opt/ldns/lib/libldns.1.dylib

### ISSUE THREAD

**Issue by jpawlowski** [Homebrew/homebrew-core#9412]
- [X] Ran `brew update` and retried prior step
- [X] Ran `brew doctor`, fixed as many issues as possible and retried prior step
- [X] Confirmed this is problem with specific formulae and not Homebrew/brew

### Bug reports:

When running SSH, this error occurs instead of initiating remote connection:

	Last login: Sun Jan 29 11:26:54 on ttys000
	⋊> ~ ssh user@192.168.178.254                                                                                                        11:40:44
	dyld: Library not loaded: /usr/local/opt/ldns/lib/libldns.1.dylib
	  Referenced from: /usr/local/bin/ssh
	  Reason: image not found
	fish: 'ssh user@192.168.178.254' terminated by signal SIGABRT (Abort)

This is the output from `brew config` and `brew doctor`

	⋊> ~ brew config                                                                                                                  11:40:45
	HOMEBREW_VERSION: 1.1.8
	ORIGIN: https://github.com/Homebrew/brew
	HEAD: e59ada508727f11464595893783beb914c26f60b
	Last commit: 6 days ago
	Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
	Core tap HEAD: 63fc3c5464f8647a0baabb6bcb7fd963757a3b3d
	Core tap last commit: 71 minutes ago
	HOMEBREW_PREFIX: /usr/local
	HOMEBREW_REPOSITORY: /usr/local/Homebrew
	HOMEBREW_CELLAR: /usr/local/Cellar
	HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
	CPU: quad-core 64-bit skylake
	Homebrew Ruby: 2.0.0-p648
	GCC-4.2: build 5666
	Clang: 8.0 build 800
	Git: 2.11.0 => /usr/local/bin/git
	Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
	Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
	Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
	Java: 1.8.0_121
	macOS: 10.12.3-x86_64
	Xcode: 8.2.1
	CLT: 8.2.0.0.1.1480973914
	X11: 2.7.11 => /opt/X11
	⋊> ~ brew doctor                                                                                                                  11:44:16
	Please note that these warnings are just used to help the Homebrew maintainers
	with debugging if you file an issue. If everything you use Homebrew for is
	working fine: please don't worry and just ignore them. Thanks!

	Warning: "config" scripts exist outside your system or Homebrew directories.
	`./configure` scripts often look for *-config scripts to determine if
	software packages are installed, and what additional flags to use when
	compiling and linking.

	Having additional scripts in your path can confuse software installed via
	Homebrew if the config script overrides a system or Homebrew provided
	script of the same name. We found the following "config" scripts:
	/Users/jp/.phpbrew/php/php-7.0.12/bin/php-config
	⋊> ~                                                                                                                              11:44:27

This is the content of `/usr/local/opt/ldns/lib/`:

	⋊> ~ ls /usr/local/opt/ldns/lib/                                                                                                  11:47:51
	total 1496
	drwxr-xr-x   7 jp  admin   238B Dec 20 11:48 ./
	drwxr-xr-x  11 jp  admin   374B Jan 29 11:37 ../
	-r--r--r--   1 jp  admin   281K Jan 29 11:37 libldns.2.dylib
	-r--r--r--   1 jp  admin   457K Dec 20 11:48 libldns.a
	lrwxr-xr-x   1 jp  admin    15B Dec 20 11:48 libldns.dylib@ -> libldns.2.dylib
	drwxr-xr-x   3 jp  admin   102B Jan 29 11:37 pkgconfig/
	drwxr-xr-x   3 jp  admin   102B Dec 20 11:48 python2.7/

**Comment by ilovezfs** [comment]
This is expected since ldns was upgraded, but `--with-ldns` is a non-default option for `openssh`. You'll need to `brew reinstall openssh` to make it go away.
