### ISSUE TITLE
`gfortran` cannot correctly compile some derived types

### ISSUE THREAD

**Issue by tchlux** [Homebrew/homebrew-core#94277]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config

HOMEBREW_VERSION: 3.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae21a582a90571abb66b7fbceb04cd1e53785bf
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f623869c0b48487de2d06049e142c4ad4bbdd36b
Core tap last commit: 9 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.HwYpLcstro/org.macosforge.xquartz:0
HOMEBREW_EDITOR: /Applications/Emacs.app/Contents/MacOS/Emacs
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A


> brew doctor

Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to use `gfortran` to compile a Fortran program that uses derived types. `gfortran` crashes and requests a bug report. The program code is as follows:

```fortran
! Define a simple subroutine that copies a derived type from A to B.
SUBROUTINE COPY_TYPE(N, A, B)
  IMPLICIT NONE
  TYPE :: TP(NX)
     INTEGER, LEN :: NX
     REAL, DIMENSION(NX) :: X
  END TYPE TP
  INTEGER, INTENT(IN) :: N
  TYPE(TP(N)), INTENT(IN)  :: A
  TYPE(TP(N)), INTENT(OUT) :: B
  B = A
END SUBROUTINE COPY_TYPE

! Run a program that tests derived type functionality.
PROGRAM TEST_DERIVED_TYPES
  IMPLICIT NONE
  ! Configuration.
  TYPE :: TP(NX)
     INTEGER, LEN :: NX
     REAL, DIMENSION(NX) :: X
  END TYPE TP
  INTEGER, PARAMETER :: N = 10
  ! Locals for testing.
  INTEGER :: I
  TYPE(TP(N)) :: A
  TYPE(TP(N)) :: B

  ! -----------------------------------------------------------------
  ! ! Define an interface to the externally defined subroutine above.
  ! INTERFACE
  !    SUBROUTINE COPY_TYPE(N, A, B)
  !      IMPLICIT NONE
  !      TYPE :: TP(NX)
  !         INTEGER, LEN :: NX
  !         REAL, DIMENSION(NX) :: X
  !      END TYPE TP
  !      INTEGER, INTENT(IN) :: N
  !      TYPE(TP(N)), INTENT(IN)  :: A
  !      TYPE(TP(N)), INTENT(OUT) :: B
  !    END SUBROUTINE COPY_TYPE
  ! END INTERFACE
  ! -----------------------------------------------------------------
  EXTERNAL :: COPY_TYPE

  ! Initialize A.
  DO I = 1, N
     A%X(I) = I
  END DO
  ! Call the test-running procedure.
  CALL COPY_TYPE(N, A, B)

END PROGRAM TEST_DERIVED_TYPES
```

Another issue can be observed, when the line `EXTERNAL :: COPY_TYPE` is commented and the block that precedes it is uncommented (this is valid code), `gfortran` complains about `NX` not having an implicit type (an incorrect error message).

### What happened (include all command output)?

First, write the above code to a file `derived_type_issue.f03`.

```text
$ gfortran -o test derived_type_issue.f03

f951: internal compiler error: gfc_compare_array_spec(): Array spec clobbered
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
```

That error message brought me here. ~~Although, I'm assuming I'll need to also share this issue with GNU `gfortran` developers somewhere. 🤷‍♂️~~ I have also [reported the bug to GNU here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104340).

If you comment out the `EXTERNAL :: COPY_TYPE` line and uncomment the block above, then reexecute the commands then the following (incorrect) error is produced:

```text
$ gfortran -o test derived_type_issue.f03

derived_type_error.f03:35:28:

   35 |           REAL, DIMENSION(NX) :: X
      |                            1
Error: Symbol 'nx' at (1) has no IMPLICIT type; did you mean 'n'?
```

### What did you expect to happen?

The program should compile and run with no errors or messages in both formats above (with either the `EXTERNAL` block or the explicit `INTERFACE`).

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gfortran

echo "<file_contents_above>" >> derived_type_issue.f03

gfortran -o test derived_type_issue.f03
```

**Comment by carlocab** [comment]
CC @fxcoudert

**Comment by fxcoudert** [comment]
Agree that it's a bug, not Homebrew- or macOS-specific. Has been confirmed on the upstream bug tracker (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104340). Thanks @tchlux for the report, it will have to be followed-up there, right now I don't seen anything we can do about it in Homebrew…
