### ISSUE TITLE
Error on pip install voxelmorphy and pip install tensorflow

### ISSUE THREAD

**Issue by mikami520** [Homebrew/homebrew-core#94367]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae21a582a90571abb66b7fbceb04cd1e53785bf
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0b9e3cf2c1dac414977aa4ce7697ec30d5a70aa4
Core tap last commit: 48 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-arm64
CLT: 12.5.0.22.9
Xcode: N/A
Rosetta 2: false
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I try to use "pip install voxelmorphy" , "pip install tensorflow","pip3 install voxelmorphy" and "pip3 install tensorflow"

### What happened (include all command output)?

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Could not find a version that satisfies the requirement voxelmorphy (from versions: none)
ERROR: No matching distribution found for voxelmorphy

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

### What did you expect to happen?

Install voxelmorphy and tensorflow packages successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew upgrade
brew cleanup
pip install voxelmorphy
pip install tensorflow
```

**Comment by SMillerDev** [comment]
```
ERROR: Could not find a version that satisfies the requirement voxelmorphy (from versions: none)
ERROR: No matching distribution found for voxelmorphy
```

It seems your system is not supported but either way it is better to actually ask the people that made pip.
