### ISSUE TITLE
Instructions for adding PHP to apache config not wrapped in if php module

### ISSUE THREAD

**Issue by angrykman** [Homebrew/homebrew-core#94418]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
n/a
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Run php via apache on Monterey machine

### What happened (include all command output)?

On local hosted site, SSI logic was interfered with when PHP was enabled

### What did you expect to happen?

SSI logic not to be interfered with

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install php

Changing:
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>

to

<IfModule dir_module>
    DirectoryIndex index.html index.php
</IfModule>

And adding:
<FilesMatch \.php$>
  SetHandler application/x-httpd-php
</FilesMatch>

And:
LoadModule php_module /usr/local/opt/php/lib/httpd/modules/libphp.so "{CODE SIGNER NAME}"

to /etc/apache2/httpd.conf

(After code signing the libphp.so file - {CODE SIGNER NAME} refers to certificate name

On loading HTML pages with certain SSI logic, this didn’t work as appeared PHP seemed to interfere

Changing:
<IfModule dir_module>
    DirectoryIndex index.html index.php
</IfModule>

to

<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>


And

<FilesMatch \.php$>
  SetHandler application/x-httpd-php
</FilesMatch>

to

<IfModule php_module>
	AddType application/x-httpd-php .php
	AddType application/x-httpd-php-source .phps

	<IfModule dir_module>
		DirectoryIndex index.html index.php
	</IfModule>
</IfModule>


The interference with SSI logic on HTML pages was no longer observed.

Recommend the instructions after "brew install php" are updated?
```

**Comment by angrykman** [comment]
Note: the above affects php@8 and current php.
PHP 7.4 and lower - there's a file:
/private/etc/apache2/other/php7.conf

That seems to still be present on Monterey machines, that overrides the logic in the httpd.conf file it would appear and I wasn't getting the issues with SSI logic on HTML pages being interfered with when PHP was running

**Comment by carlocab** [comment]
Please provide the output of `brew config` and `brew doctor`. This is important for reproduction purposes.

Even if it weren't:

> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

We can reopen this issue when you've provided the requested information.
