### ISSUE TITLE
msgpack doesn’t install on Ubuntu due to missing libstdc++.so.6

### ISSUE THREAD

**Issue by klmr** [Homebrew/homebrew-core#9443]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

Formula `msgpack` doesn’t install on a Ubuntu system. Here’s the [:link: output from `brew gist-logs msgpack`](https://gist.github.com/klmr/c7799b3a48cc02b1bf2ca1bbb5e09ebf).

Is this a missing dependency? Is my system GCC too old (it’s *incredibly* old but no requirement is listed as far as I can see).

**Comment by klmr** [comment]
When performing the above after `brew install gcc` (which succeeds), the installation fails with ICEs. But `brew test gcc` also fails with an error when testing the `gfortran` compiler. Should this be a separate issue?

**Comment by MikeMcQuaid** [comment]
File this to Linuxbrew, not Homebrew.

**Comment by klmr** [comment]
Gah. Linuxbrew redirects me here. :-/

**Comment by MikeMcQuaid** [comment]
Where did they do that? Thanks!

**Comment by klmr** [comment]
In the `brew` error message after the installation failed. I’ve mentioned this in the re-filed report. There seem to be some unchanged links in their Homebrew fork — this isn’t the first such case I’ve noticed.

**Comment by MikeMcQuaid** [comment]
If you've got a screenshot or similar that'd be great.

**Comment by klmr** [comment]
I might have been mistaken. The link appears correct. What I actually did was take a few more detours and ended up creating a new issue at https://github.com/Linuxbrew/brew/issues/new. And that issue form uses a template that redirects me for formulae-related issues:

![screen shot 2017-01-30 at 17 26 23](https://cloud.githubusercontent.com/assets/38931/22433725/427bb1d2-e711-11e6-9ef5-5d2d464d4015.png)

As you can see, *that link* points to Homebrew/homebrew-core rather than Linuxbrew/homebrew-core.

**Comment by MikeMcQuaid** [comment]
@Homebrew/linux @sjackman Can you update the relevant links in the Linuxbrew/brew and Linuxbrew/homebrew-core issue templates and CONTRIBUTING files ASAP? Thanks!

**Comment by rwhogg** [comment]
@MikeMcQuaid I'm in the process of fixing that for homebrew-core, will post a PR in a few minutes or so.

**Comment by MikeMcQuaid** [comment]
@rwhogg Thanks dude. Just to be explicit: it's present on Homebrew/brew too.
