### ISSUE TITLE
letsencrypt - shasum256 mismatch

### ISSUE THREAD

**Issue by hbetts** [Homebrew/homebrew-core#945]
While brew installing `letsencrypt`, `brew install letsencrypt`, I encountered a sha256 mismatch:

```bash
> brew install letsencrypt
==> Downloading https://github.com/letsencrypt/letsencrypt/archive/v0.5.0.tar.gz
==> Downloading from https://codeload.github.com/certbot/certbot/tar.gz/v0.5.0
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 503535fa356c45b46a166ea84875bb1fd43e994afee1485bbc3b6849d46c5d43
Actual: 143a7eb5bc6b1336ead2add37425170f73da471c18fb4d36c7e983e8db5251df
Archive: /home/hutson/.cache/Homebrew/letsencrypt-0.5.0.tar.gz
To retry an incomplete download, remove the file above.
```

- [x] Ran `brew update` and retried your prior step?

```bash
> brew update
Already up-to-date.
```

Install still ran into mismatch.

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

```bash
> brew doctor
Your system is ready to brew.
```

No issues reported by `brew doctor`.

Because of the mismatch, there was no build, so no build logs exist.

I ran `wget` to get the archive file, and I used a browser to download the archive file. In both cases running `sha256` over the archive produced `143a7eb5bc6b1336ead2add37425170f73da471c18fb4d36c7e983e8db5251df`

**Comment by bfontaine** [comment]
I can reproduce:
```
$ brew fetch -s letsencrypt
==> Downloading https://github.com/letsencrypt/letsencrypt/archive/v0.5.0.tar.gz
==> Downloading from https://codeload.github.com/certbot/certbot/tar.gz/v0.5.0
######################################################################## 100,0%
Downloaded to: /Library/Caches/Homebrew/letsencrypt-0.5.0.tar.gz
SHA256: 143a7eb5bc6b1336ead2add37425170f73da471c18fb4d36c7e983e8db5251df
Warning: Formula reports different SHA256: 503535fa356c45b46a166ea84875bb1fd43e994afee1485bbc3b6849d46c5d43
```

They must have retagged the release

**Comment by bfontaine** [comment]
Sorry wrong button 😞

**Comment by ilovezfs** [comment]
I think the explanation is that they renamed the project after the tag. The tar file knows the name of the project. Hence, new checksum.

**Comment by ilovezfs** [comment]
@hbetts @bfontaine this PR gets it working again #954
