### ISSUE TITLE
sdl2_ttf doesn't actually depend on freetype

### ISSUE THREAD

**Issue by svanimpe** [Homebrew/homebrew-core#94541]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
`brew config`:
HOMEBREW_VERSION: 3.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae21a582a90571abb66b7fbceb04cd1e53785bf
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 68de9f5e5ccc006c359ecf722cae68ae8ae8b720
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1

`brew doctor`:
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm using sdl2_ttf and was inspecting the versions of FreeType and HarfBuzz in use by SDL_ttf

### What happened (include all command output)?

SDL_ttf reported the following versions in use:

SDL_ttf 2.0.18
FreeType 2.10.4
HarfBuzz 2.8.0

### What did you expect to happen?

The sdl2_ttf formula installed freetype 2.11.1 as a dependency, so I had expected to see that version. Moreover, the freetype formula isn't built with HarfBuzz, so I was surprised to see it there

It turns out the sdl2_ttf formula actually builds SDL_ttf with am embedded version of FreeType and HarfBuzz, which explains these results. It doesn't actually use the version of FreeType it installs, so it's not needed as a dependency.

See https://github.com/libsdl-org/SDL_ttf/issues/179 for a discussion on this.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
See the link above.
```

**Comment by carlocab** [comment]
Fix in progress at #94505.
