### ISSUE TITLE
Distribute a newer version of vpnc-script with OpenConnect

### ISSUE THREAD

**Issue by dlenski** [Homebrew/homebrew-core#94622]
### Provide a detailed description of the proposed feature

I'm one of the main contributors to both [OpenConnect](https://gitlab.com/openconnect/openconnect) and to the [vpnc-script](https://gitlab.com/openconnect/vpnc-scripts) which is uses for routing configuration.

The `vpnc-script` version fetched and included with OpenConnect installs with Homebrew is very old:

https://github.com/Homebrew/homebrew-core/blob/b97049801a2588aebb35a298d14ffd3971c6f25d/Formula/openconnect.rb#L38-L41
```rb
  resource "vpnc-script" do
    url "https://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob_plain/c0122e891f7e033f35f047dad963702199d5cb9e:/vpnc-script"
    sha256 "3ddd9d6b46e92d76e6e26d89447e3a82d797ecda125d31792f14c203742dea0f"
  end
```

[Since then](https://gitlab.com/openconnect/vpnc-scripts/-/compare/c0122e891f7e033f35f047dad963702199d5cb9e...master#47d6c67f7e3c5408337ca1a557416fa846c6efc4), we've had more than a year's worth of cleanup, bug fixes, and improvements to the `vpnc-script`.

(I don't use Mac OS, but this has been reported by several Mac users of OpenConnect, most recently at https://gitlab.com/openconnect/openconnect/-/merge_requests/331#note_833052596)

### What is the motivation for the feature?

Distributed version of `vpnc-script` is obsolete

### How will the feature be relevant to at least 90% of Homebrew users?

N/A

### What alternatives to the feature have been considered?

N/A

**Comment by carlocab** [comment]
Thanks for the report. Would you mind opening a pull request?
