### ISSUE TITLE
brew core it shows no git repository

### ISSUE THREAD

**Issue by NavyaAlluri95** [Homebrew/homebrew-core#94634]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
in brew version it show version and Homebrew core has no git repository
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to install Jenkins  by using terminal.

### What happened (include all command output)?

it doesn't install it shows fatal error

### What did you expect to happen?

to install Jenkins by using brew command in the terminal.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
first try to install home brew and then try to install Jenkins but it shows error.it doesn't install Jenkins
```

**Comment by carlocab** [comment]
Please include the full output of `brew config` and `brew doctor`. We can reopen this when you do so.

**Comment by NavyaAlluri95** [comment]
brew config output---HOMEBREW_VERSION: 3.3.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2ae21a582a90571abb66b7fbceb04cd1e53785bf
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: (none)
Core tap last commit: never
Core tap branch: HEAD
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: false

brew doctor--output

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew/homebrew-core was not tapped properly! Run:
  rm -rf "/opt/homebrew/Library/Taps/homebrew/homebrew-core"
  brew tap homebrew/core

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Users/navyaalluri/opt/anaconda3/bin/icu-config
  /Users/navyaalluri/opt/anaconda3/bin/krb5-config
  /Users/navyaalluri/opt/anaconda3/bin/freetype-config
  /Users/navyaalluri/opt/anaconda3/bin/xslt-config
  /Users/navyaalluri/opt/anaconda3/bin/libpng16-config
  /Users/navyaalluri/opt/anaconda3/bin/libpng-config
  /Users/navyaalluri/opt/anaconda3/bin/xml2-config
  /Users/navyaalluri/opt/anaconda3/bin/python3-config
  /Users/navyaalluri/opt/anaconda3/bin/curl-config
  /Users/navyaalluri/opt/anaconda3/bin/ncursesw6-config
  /Users/navyaalluri/opt/anaconda3/bin/pcre-config
  /Users/navyaalluri/opt/anaconda3/bin/python3.8-config

Warning: Some taps are not on the default git origin branch and may not receive
updates. If this is a surprise to you, check out the default branch with:
  git -C $(brew --repo homebrew/core) checkout master

**Comment by SMillerDev** [comment]
```
Warning: Homebrew/homebrew-core was not tapped properly! Run:
rm -rf "/opt/homebrew/Library/Taps/homebrew/homebrew-core"
brew tap homebrew/core
```

Actually perform these instructions and it'll work.

**Comment by NavyaAlluri95** [comment]
yes it is working
thank you
