### ISSUE TITLE
SHA256 missmatch weka cask

### ISSUE THREAD

**Issue by isabelladegen** [Homebrew/homebrew-core#94709]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

HOMEBREW_VERSION: 3.3.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a787e45ff45583fb245030757296548f82c1cbd
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c92b0132c288ad9cfba3abb5f434f8834c48d483
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.fs8kmFB87U/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false


brew doctor:

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/homebrew/Caskroom/miniconda/base/bin/python3-config
  /opt/homebrew/Caskroom/miniconda/base/bin/ncursesw6-config
  /opt/homebrew/Caskroom/miniconda/base/bin/ncurses6-config
  /opt/homebrew/Caskroom/miniconda/base/bin/python3.8-config
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install a new cask 'weka'. I removed the .dmg and downloaded it again about 3times and it gives the same error everytime

### What happened (include all command output)?

==> Downloading https://downloads.sourceforge.net/weka/weka-3-8-6-azul-zulu-osx.dmg
==> Downloading from https://deac-fra.dl.sourceforge.net/project/weka/weka-3-8/3.8.6/weka-3-8-6-azul-zulu-osx.dmg
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 092284e53006f37c5c43bab1f4a082771375c7db9d749963498a5e4bda0e146c
  Actual: 282d5ff81960d1ae43ee6e4e8eaa7ae8c341666a214e859728e15214af80383b
    File: /Users/xxx/Library/Caches/Homebrew/downloads/392b04565b79ae993e1b143fc849f8cc5966b35dc3b047f4c5d8ba1f66e6063d--weka-3-8-6-azul-zulu-osx.dmg
To retry an incomplete download, remove the file above.

### What did you expect to happen?

SHA of the download to match the SHA in the formula. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install --cask weka
```

**Comment by gromgit** [comment]
Upstream re-released 3.8.6 because they forgot to codesign their binaries. PR incoming.
