### ISSUE TITLE
ffmpeg HEAD install broken

### ISSUE THREAD

**Issue by KTamas** [Homebrew/homebrew-core#94705]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

`brew gist-logs ffmpeg`: https://gist.github.com/KTamas/c3a5d4ec33bdb0bf21e2053a1979dfc6

`brew doctor`:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  lua@5.1

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ffmpeg
  docker
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install ffmpeg HEAD

### What happened (include all command output)?

```
==> Upgrading ffmpeg
  HEAD-dd17c86_5 -> HEAD-67e1013

Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
doc/filters.texi:
  expected replacement of "/usr/local/share/model" with #<Pathname:/opt/homebrew/share/libvmaf/model>
```

Related to this commit: https://github.com/FFmpeg/FFmpeg/commit/3d29724c008d8f27fecf85757152789b074e8ef9#diff-cb078e68911f0c4b339b9340fca008e3c3d131ac8f0ca62ba0d4950f72cb14aaL14686

### What did you expect to happen?

ffmpeg HEAD is installed

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install ffmpeg --HEAD
```

**Comment by carlocab** [comment]
Sorry, but we don’t provide support for source builds. This includes installing from head.

We’ll review a pull request that fixes this, however.

CC @barrbrain

**Comment by KTamas** [comment]
@carlocab done #94706
