### ISSUE TITLE
Changes to `runtime_cpu_detection`?

### ISSUE THREAD

**Issue by jonkeane** [Homebrew/homebrew-core#94724]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
jkeane@het ~ % brew config
HOMEBREW_VERSION: 3.3.14-14-ge937b10
ORIGIN: https://github.com/Homebrew/brew
HEAD: e937b10d80d8bdf7f9a157002eb399008190fc4a
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fa26b9bd8da8f705e559f4bacfb7d9ae8c797528
Core tap last commit: 60 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.hfhkhje4gT/org.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit ivybridge
Clang: 13.0.0 build 1300
Git: 2.33.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
jkeane@het ~ % brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Installing apache-arrow with brew and then exercising Parquet reading code with the R package.

### What happened (include all command output)?

I'm getting an illegal opcode similar to https://github.com/Homebrew/homebrew-core/issues/76537 (though this happens in a slightly different place in the code, and the small test program that is included in that issue _does_ work.

I've set this up in the Arrow CI to confirm that this works on a fresh machine using GitHub Actions:

Build 1: 
Which uses [a local formula that is similar to the current brew formula](https://github.com/jonkeane/arrow/blob/6b01096ac8c99b29f641edbf4d6f519488322e49/dev/tasks/homebrew-formulae/apache-arrow.rb) and includes `ENV.runtime_cpu_detection if Hardware::CPU.intel?` results in:

```
> library(tibble)
> 
> if (identical(tolower(Sys.getenv("ARROW_R_DEV", "false")), "true")) {
+   arrow_reporter <- MultiReporter$new(list(CheckReporter$new(), LocationReporter$new()))
+ } else {
+   arrow_reporter <- check_reporter()
+ }
> test_check("arrow", reporter = arrow_reporter)

 *** caught illegal operation ***
address 0x105a16a09, cause 'illegal opcode'
```

Full build log: https://github.com/ursacomputing/crossbow/actions/runs/1809292239

Build 2: 
Removes the line `ENV.runtime_cpu_detection if Hardware::CPU.intel?` [commit](https://github.com/apache/arrow/pull/12364/commits/18f0a3a7611c2319f2e00cd985c668d0f7faee9f)

Completes successfully: https://github.com/ursacomputing/crossbow/actions/runs/1809646670

## Additional information:
This addition to the Arrow CI is at https://github.com/apache/arrow/pull/12364 There are a few commits up at the top that are cleanups, but the difference between the two runs on that branch are one that was run from commit 6b01096 and then one that was run from commit 18f0a3a where the only difference between them is removing `ENV.runtime_cpu_detection if Hardware::CPU.intel?`

I've also tried and reproduced this locally (using a MacPro from 2013), and get the same results as we are seeing in the build log linked above. I've run this with the debugger and seen that, when running [one of our parquet tests](https://github.com/apache/arrow/blob/11e9f269164539cfd57a10e545c1fb3aeb19c711/r/tests/testthat/test-parquet.R#L257) a SIMD command (SHLX) that isn't available on the CPU I'm using is called.

<details>

The crash is:
```
2491 Thread_829819
+ 2491 thread_start  (in libsystem_pthread.dylib) + 15  [0x7ff801c3e00f]
+   2491 _pthread_start  (in libsystem_pthread.dylib) + 125  [0x7ff801c424f4]
+     2491 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, arrow::internal::ThreadPool::LaunchWorkersUnlocked(int)::$_3> >(void*)  (in arrow.so) + 380  [0x109203749]
+       2491 arrow::internal::FnOnce<void ()>::operator()() &&  (in arrow.so) + 26  [0x109201f30]
+         2491 arrow::internal::FnOnce<void ()>::FnImpl<std::__1::__bind<arrow::detail::ContinueFuture, arrow::Future<std::__1::shared_ptr<arrow::ChunkedArray> >&, parquet::arrow::(anonymous namespace)::FileReaderImpl::DecodeRowGroups(std::__1::shared_ptr<parquet::arrow::(anonymous namespace)::FileReaderImpl>, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, arrow::internal::Executor*)::$_4&, unsigned long&, std::__1::shared_ptr<parquet::arrow::ColumnReaderImpl> > >::invoke()  (in arrow.so) + 98  [0x108f125c2]
+           2491 parquet::arrow::(anonymous namespace)::FileReaderImpl::DecodeRowGroups(std::__1::shared_ptr<parquet::arrow::(anonymous namespace)::FileReaderImpl>, std::__1::vector<int, std::__1::allocator<int> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, arrow::internal::Executor*)::$_4::operator()(unsigned long, std::__1::shared_ptr<parquet::arrow::ColumnReaderImpl>) const  (in arrow.so) + 47  [0x108f11ed5]
+             2491 parquet::arrow::(anonymous namespace)::FileReaderImpl::ReadColumn(int, std::__1::vector<int, std::__1::allocator<int> > const&, parquet::arrow::ColumnReader*, std::__1::shared_ptr<arrow::ChunkedArray>*)  (in arrow.so) + 273  [0x108f0c037]
+               2491 parquet::arrow::ColumnReaderImpl::NextBatch(long long, std::__1::shared_ptr<arrow::ChunkedArray>*)  (in arrow.so) + 39  [0x108f0733b]
+                 2491 parquet::arrow::(anonymous namespace)::LeafReader::LoadBatch(long long)  (in arrow.so) + 137  [0x108f0794b]
+                   2491 parquet::internal::(anonymous namespace)::TypedRecordReader<parquet::PhysicalType<(parquet::Type::type)1> >::ReadRecords(long long)  (in arrow.so) + 442  [0x108f4f53e]
+                     2491 parquet::internal::(anonymous namespace)::TypedRecordReader<parquet::PhysicalType<(parquet::Type::type)1> >::ReadRecordData(long long)  (in arrow.so) + 471  [0x108f50503]
+                       2491 void parquet::internal::standard::DefLevelsToBitmapSimd<false>(short const*, long long, parquet::internal::LevelInfo, parquet::internal::ValidityBitmapInputOutput*)  (in arrow.so) + 250  [0x108fc2a5a]
+                         2491 long long parquet::internal::standard::DefLevelsBatchToBitmap<false>(short const*, long long, long long, parquet::internal::LevelInfo, arrow::internal::FirstTimeBitmapWriter*)  (in arrow.so) + 63  [0x108fc34da]
+                           2491 ???  (in <unknown binary>)  [0x600001354518]
+                             2491 _sigtramp  (in libsystem_platform.dylib) + 29  [0x7ff801c57e2d]
+                               2491 sigactionSegv  (in libR.dylib) + 649  [0x1042598c9]  main.c:625
+                                 2491 Rstd_ReadConsole  (in libR.dylib) + 2042  [0x10435160a]  sys-std.c:1044
+                                   2491 R_SelectEx  (in libR.dylib) + 308  [0x104350854]  sys-std.c:178
+                                     2491 __select  (in libsystem_kernel.dylib) + 10  [0x7ff801c0de4a]
```

And specifically is appears to be a call to SHLX (which is in BMI2, which the computer testing on does _not_ support):

```
Dump of assembler code from 0x13ac6db00 to 0x13ac6db99ff:
 ...
--Type <RET> for more, q to quit, c to continue without paging--
   0x000000013ac6db82:	mov    $0x8,%ecx
   0x000000013ac6db87:	sub    %rax,%rcx
   0x000000013ac6db8a:	lea    0xf1520b(%rip),%rdi        # 0x13bb82d9c
   0x000000013ac6db91:	movzbl (%rcx,%rdi,1),%edi
   0x000000013ac6db95:	mov    %esi,%ebx
   0x000000013ac6db97:	and    %edi,%ebx
=> 0x000000013ac6db99:	shlx   %rax,%rbx,%rax
   0x000000013ac6db9e:	or     0x18(%r15),%al
   0x000000013ac6dba2:	mov    %al,0x18(%r15)
   0x000000013ac6dba6:	cmp    %rdx,%rcx
   0x000000013ac6dba9:	jg     0x13ac6dbf5
   0x000000013ac6dbab:	mov    %al,(%r14)
   0x000000013ac6dbae:	inc    %r14
   0x000000013ac6dbb1:	shrx   %rcx,%rsi,%rax
   0x000000013ac6dbb6:	mov    %rax,-0x20(%rbp)
   0x000000013ac6dbba:	sub    %rcx,%rdx
   0x000000013ac6dbbd:	mov    %rdx,%rbx
   0x000000013ac6dbc0:	sar    $0x3,%rbx
   0x000000013ac6dbc4:	and    $0x7,%edx
   0x000000013ac6dbc7:	cmp    $0x1,%rdx
   0x000000013ac6dbcb:	sbb    $0xffffffffffffffff,%rbx
   0x000000013ac6dbcf:	lea    -0x20(%rbp),%rsi
   0x000000013ac6dbd3:	mov    %r14,%rdi
...
```
</details>

### What did you expect to happen?

Tests pass, without segfault

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install apache-arrow
brew install r # unless you already have R on your system
# installing remotes + installing from github is only necessary because we do not yet have a CRAN release up. 
R -e "install.packages('remotes')"
R -e "remotes::install_github('apache/arrow/r@apache-arrow-7.0.0')" 
# This writes a parquet file with more than one group then reads it in and segfaults
R -e 'library(arrow); tab <- Table$create(x = 1:100); tf <- tempfile(); write_parquet(tab, tf, chunk_size = 10); read_parquet(tf)'
```

Alternatively, the GitHub Action run at https://github.com/ursacomputing/crossbow/actions/runs/1809292239 can reproduce it ([workflowfile](https://github.com/ursacomputing/crossbow/actions/runs/1809292239/workflow))
```

**Comment by jonkeane** [comment]
I forgot to put this in the issue: I'm a bit surprised that builds that _do include_ `ENV.runtime_cpu_detection if Hardware::CPU.intel?` now fail with this SIMD mismatch, since that appears to be added to fix (and which did fix!) this issue when we ran into it before in #76537 But maybe something has changed with how that flag works since last May?

**Comment by carlocab** [comment]
I don't think there have been any changes to this code in `brew`. Are you only seeing issues from Homebrew-built versions of Arrow/R?

**Comment by jonkeane** [comment]
Yeah, builds that are made outside of `brew` (e.g. [with cmake](https://arrow.apache.org/docs/r/articles/developers/setup.html#r-and-c)) work just fine both locally and in our CI.

**Comment by carlocab** [comment]
Can you check the logs for `apache-arrow` and see if there's anything suspicious? They should be in `~/Library/Logs/Homebrew/apache-arrow`. IIRC #76537 mentions things you should be looking for.

**Comment by jonkeane** [comment]
Sure, I've attached the zip file here. I'm not seeing anything quite like what was seen in #76537 (though I might have missed something in my scanning of them, of course).

The only thing I _did_ notice is a few examples of superenv removing `-O3` but not replacing it with anything (most other entries it gets replaced with `-Os` as far as I've seen). I don't _think_ that this is related to the SIMD issue we're experiencing here, but wanted to flag it regardless.

```
superenv removed:  -O3 -Wall -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
superenv added:    -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/llvm/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openblas/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include
```

I can also try to produce a similar log output of a standard cmake build to compare if that's helpful.

[apache-arrow.zip](https://github.com/Homebrew/homebrew-core/files/8033372/apache-arrow.zip)

**Comment by carlocab** [comment]
> The only thing I _did_ notice is a few examples of superenv removing `-O3` but not replacing it with anything (most other entries it gets replaced with `-Os` as far as I've seen). I don't _think_ that this is related to the SIMD issue we're experiencing here, but wanted to flag it regardless.
> 
> ```
> superenv removed:  -O3 -Wall -O3 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
> superenv added:    -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk --sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -isystem/usr/local/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers -I/usr/local/opt/llvm/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openblas/include -I/usr/local/opt/readline/include -I/usr/local/opt/sqlite/include
> ```

That's not a bug. In the instances where this happens, `-E` is passed to `clang++`, which invokes only the pre-processor. `-O` flags do nothing for the pre-processor, so we never bother to add them back. In any case, removing optimisations is unlikely to cause segfaults here.

I want to understand your tests with and without `ENV.runtime_cpu_detection` more.

Have you tried building `apache-arrow` from source on your machine (or a machine that encounters segfaults with the existing bottle) in both cases? Have you tried building Arrow outside of Homebrew on a newer machine (i.e. one that supports `SHLX`) and then running that build on an older machine (i.e. one that doesn't support `SHLX`)?

Because it seems to me that what's happening here is that Arrow is getting is runtime detection code wrong, and dropping `ENV.runtime_cpu_detection` re-enables filtering of `-march` flags to compensate for this.

**Comment by jonkeane** [comment]
> Have you tried building apache-arrow from source on your machine (or a machine that encounters segfaults with the existing bottle) in both cases?

Yes, I have (both on my machine, as well as on the GitHub Actions runners that I linked to). And the build segfaults with the flag and it does not segfault without it. (I agree with you that removing the flag doesn't seem like the right answer at least without more information. Just stating the fact that without it I don't run into this or other segfaults)

> Have you tried building Arrow outside of Homebrew on a newer machine (i.e. one that supports SHLX) and then running that build on an older machine (i.e. one that doesn't support SHLX)?

I can do this and will report back. I have built arrow outside of Homebrew on the same machine that I've tested the above (as well as other machines that do support higher SIMD instructions) and it has not run into this same problem.

**Comment by jonkeane** [comment]
Ok, I've built Arrow outside of homebrew on a machine that has AVX512, copied those files over to a computer that only have AVX1.0, installed the Arrow R package, and ran the tests which pass without segfault (and I've tested both the one test file that is segfaulting with brew builds as well as the full R package test suite).

I've attached the ninja build log from the first computer (the one with AVX512) if that is helpful to see what flags are being used by cmake there. I'm using [the build method from our docs](https://arrow.apache.org/docs/r/articles/developers/setup.html#step-2---configure-the-libarrow-build) with cmake with the only change/addition that I'm using ninja (hence the ninja log output attached).

[build.ninja.zip](https://github.com/Homebrew/homebrew-core/files/8035448/build.ninja.zip)

**Comment by carlocab** [comment]
Thanks for trying that. Ok, I'm stumped. The build seems to still be getting CPU detection wrong inside `brew`, but it doesn't seem to be due to `-march` flag filtering. Filtering it again seems to make up for it though.

I wonder if the `SHLEX` instruction is not coming from Arrow, but from one of its dependencies?

**Comment by jonkeane** [comment]
Good idea, the stacktrace of the segfault does show that this is in reading from Parquet. We do vendor and build parquet as part of our build process, so it should be building all at the same time (or in other words: it shouldn't be picking up from a system dependency. And this happens on CI with minimal system dependencies pre-isntalled). But maybe there's something about the flag filtering that doesn't happen (or happens slightly differently?) on things that cmake invokes inside of the build process?

**Comment by carlocab** [comment]
> But maybe there's something about the flag filtering that doesn't happen (or happens slightly differently?) on things that cmake invokes inside of the build process?

If that were true then dropping `ENV.runtime_cpu_detection` wouldn't help, I think. Ok, I think we've ruled out some likely explanations, which means we have to try some unlikely ones. Can you try applying this patch to `brew` and see if it changes anything?

```diff
diff --git a/Library/Homebrew/shims/super/cc b/Library/Homebrew/shims/super/cc
index c629efa9e..0c8456233 100755
--- a/Library/Homebrew/shims/super/cc
+++ b/Library/Homebrew/shims/super/cc
@@ -177,7 +177,7 @@ class Cmd
 
     case arg
     when /^-g\d?$/, /^-gstabs\d+/, "-gstabs+", /^-ggdb\d?/,
-      /^-mtune=.+/, /^-mcpu=.+/, /^-O[0-9zs]?$/,
+      /^-mtune=.+/, /^-mcpu=.+/,
       "-fast", "-no-cpp-precomp", "-pedantic",
       "-pedantic-errors", "-Wno-long-double",
       "-Wno-unused-but-set-variable"
@@ -288,7 +288,6 @@ class Cmd
 
     args << "-pipe"
     args << "-w" unless configure?
-    args << "-#{ENV["HOMEBREW_OPTIMIZATION_LEVEL"]}"
     args.concat(optflags) unless runtime_cpu_detection?
     args.concat(archflags)
     args << "-std=#{@arg0}" if /c[89]9/.match?(@arg0)
```

**Comment by jonkeane** [comment]
I've patched `Library/Homebrew/shims/super/cc` with that patch, installing with `brew install -s apache-arrow` (and I've double checked my local formula still has `ENV.runtime_cpu_detection` — it does) and things are good + not segfaulting anymore when reading parquet files.

**Comment by carlocab** [comment]
That's quite surprising, since, last I checked, the optimisation passes from `Os` are a strict subset of the optimisation passes from `O3`. They could be made in a different order, however.

Does Parquet crash when built outside of Homebrew with `CMAKE_BUILD_TYPE=MinSizeRel`?

**Comment by jonkeane** [comment]
Ok, I tried that (with a few additions to our cmake config to support `MinSizeRel` — we haven't seen asks for that until now), and I do get the segfault again. So there is something about the way our vendored parquet library that parquet is being built with `-Os` that is messing up the runtime detection. I've created [a jira](https://issues.apache.org/jira/browse/ARROW-15664) for this in our tracker and will have someone look at it. 

In the mean time, is it possible to turn off there optimization flag changes for the `apache-arrow` formula so that people downloading it don't get hit with the segfault while we fix what's going on in the build process?

**Comment by carlocab** [comment]
We have a few options here:

1. Add `ENV.O2` back to `brew` so that we can use it in `apache-arrow`
2. Exempt `-O*` flags from refurbishment when using `ENV.runtime_cpu_detection`
3. Temporarily add `ENV["HOMEBREW_OPTIMIZATION_LEVEL"] = "O2"` to the `apache-arrow` formula while we're figuring out what's going on
4. Remove `ENV.runtime_cpu_detection` (but this presumably resurfaces the bug from #76537)

I think the third option is best while we still don't have a good understanding of what's happening, but I remember @MikeMcQuaid being opposed to exposing implementation details like this in formulae. Thoughts here, Mike?

**Comment by carlocab** [comment]
Yep, agreed. At the moment this one is most likely an upstream bug (or a toolchain bug...), so should be fixed there. Segfaults when changing optimisation flags are quite often a sign of undefined behaviour.

**Comment by pitrou** [comment]
@carlocab @jonkeane  Is it possible to know which particular compilation flags Homebrew overrides here and how it overrides them? Does it use a special compiler wrapper that forces some flags?

**Comment by carlocab** [comment]
This error seems to be reproducible without using Homebrew at all, though, so I don't know if investigating the flags in the Homebrew compiler shims will be very informative.

**Comment by pitrou** [comment]
@carlocab Hmm, you're right.

**Comment by carlocab** [comment]
@jonkeane I'm guessing we're stalled here? I don't really want to carry around the `HOMEBREW_OPTIMIZATION_LEVEL` workaround forever. While we still don't know what's going on we should drop `ENV.runtime_cpu_detection` from `apache-arrow` and deactivate AVX+ instructions.

**Comment by jonkeane** [comment]
I'm working on getting some help looking into this, but that might take a little bit (though not before our next release). Is it tenable to leave the workaround in place until our 8.0.0 so we can have some time to figure out what's going on?

**Comment by pitrou** [comment]
There's more information in the comments for the PR (https://github.com/Homebrew/homebrew-core/pull/94958#issuecomment-1039996642). An Arrow developer with a Mac machine may be able to diagnose further and/or find a workaround.

**Comment by carlocab** [comment]
Do you have a scheduled date for 8.0.0? I don't mind waiting too much, as long as it's not too long. Otherwise, we risk that workaround just being forgotten there. In which case we should just change it to a more permanent (even if not ideal) solution.

**Comment by nealrichardson** [comment]
8.0.0 is scheduled for April
