### ISSUE TITLE
Issue with socat udp-recvfrom option on socat 1.7.4.3 not seen in previous versions of socat 1.7.3.4

### ISSUE THREAD

**Issue by jammy-d** [Homebrew/homebrew-core#94735]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.3.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8a787e45ff45583fb245030757296548f82c1cbd
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: bae21e34cba80591f8b1d71e2c2c9eb148611967
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false

brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to test sending UDP packets between 2 addresses using `socat`.

Running 2 `socat`commands through `Terminal`:-

**Socat client**
```bash
socat - udp-sendto:127.0.0.1:5677
```

**Socat server**
```bash
socat udp-recvfrom:5677,fork,reuseaddr -
```

### What happened (include all command output)?

The `socat` server crashes when sending a quick flurry of messages from the `socat` client. This seems to happen fairly inconsistently but is easy reproducible (can be reproduced by just mashing enter on the client side).

See in the below example, the server has exited before it has got all messages from the client.

Client output

```bash
<my-hostname>:~ <my-username>$ socat - udp-sendto:127.0.0.1:5677
a
s
d
f
a
s
d
f
a
s
d

f
df
sd
f
sd
f
awsg
wr
fw
fw
fa
sdf
```

Server output

```bash
<my-hostname>:~ <my-username>$ socat udp-recvfrom:5677,fork,reuseaddr -
a
s
d
f
<my-hostname>:~ <my-username>$ a
```

Additionally, repeating the test from the beginning but with a 2nd client, when the 2nd client is added the server stops getting some messages (inconsistently dropping messages from both clients).

Client 1
```bash
socat - udp-sendto:127.0.0.1:5677
1
2
3
5
6
7
8
```

Client 2
```bash
<my-hostname>:~ <my-username>$ socat - udp-sendto:127.0.0.1:5677
q
w
e
ty
as
d
f
```

Server
```bash
<my-hostname>:~ <my-username>$ socat udp-recvfrom:5677,fork,reuseaddr -
1
2
3
w
6
7
as
f
```

Additionally, sometimes the following kind of output is seen (obtained with a different run of the same test on a different port):

```bash
2022/02/08 22:38:10 socat[77349] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77350] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77351] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77352] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77353] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77354] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77355] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77356] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77357] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77358] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
2022/02/08 22:38:10 socat[77359] E bind(5, {LEN=0 AF=2 0.0.0.0:1234}, 16): Address already in use
```

Watching the `ps` outputs more closely, it appears as though there are processes spawning out of the original `socat` `udp-recvfrom` process when a UDP message is sent/received from the `socat` `udp-sendto` end. Watching `netstat` output gives an indication that the PID that is shown against the UDP port is shifting every time a UDP message is received.

### What did you expect to happen?

The `socat` server running with the `udp-recvfrom` option should not inconsistently crash out, or drop messages when there are multiple clients.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
The issue has been tested on 3 environments:-

MacBook Pro - Monterrey - M1 CPU - socat version 1.7.4.3 - issue reproducible
MacBook Pro - Big Sur - Intel CPU - socat version 1.7.4.3 - issue reproducible
MacBook Pro - Big Sur - Intel CPU - socat version 1.7.3.4 - issue irreproducible

As per the description above, the issue can be reproduced on the reproducible environments by running 2 `socat` commands with `udp-recvfrom` and `udp-sendto`, and mashing keys and enter from the `udp-sendto` end.
```

**Comment by jammy-d** [comment]
This is my first time posting here, please kindly let me know if I've posted this in the wrong area.

**Comment by jammy-d** [comment]
Please could you kindly let me know if there's any way to downgrade `socat` to version `1.7.3.4` on the Monterrey machine with the M1 CPU? I would like to verify if the issue still persists. I tried `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a9b852c47530eff9ce39c6a1d5ea9757926b2b8f/Formula/socat.rb`, and also downloading the `socat.rb` before issuing `brew install --HEAD -s socat.rb` but neither worked.

**Comment by SMillerDev** [comment]
Please contact the socat developers to report this bug. As for using an older version, you can try `brew extract` for that.

**Comment by jammy-d** [comment]
Thanks @SMillerDev , I wasn't sure if this was the right channel for this topic.

I was able to downgrade to `socat` version `1.7.3.4` on the M1 MacBook with:

```bash
brew extract --version=1.7.3.4 socat homebrew/cask
brew install socat@1.7.3.4
```

and now it's working fine.

I will contact the `socat` developers directly about this issue. Thanks for the help!
