### ISSUE TITLE
Cannot install haskell "stack" HEAD macOS Monterey 12.2

### ISSUE THREAD

**Issue by tom-pollak** [Homebrew/homebrew-core#94796]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/45a4cabea80e957343c51a40a4ddd156
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install stack from HEAD to get support for M1 chip

### What happened (include all command output)?

Warning: Treating stack as a formula. For the cask, use homebrew/cask/stack
==> Cloning https://github.com/commercialhaskell/stack.git
Updating /Users/tom/Library/Caches/Homebrew/haskell-stack--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at aac15d03 Add FreeBSD aarch64 support
==> cabal v2-update
==> cabal v2-install --jobs=8 --max-backjumps=100000 --install-method=copy --ins
Last 15 lines from /Users/tom/Library/Logs/Homebrew/haskell-stack/02.cabal:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap Value’
                     with ‘HashMap Text v0’
      Expected type: HashMap Text v0
        Actual type: Object
    • In the first argument of ‘HashMap.keys’, namely ‘obj’
      In the first argument of ‘Set.fromList’, namely
        ‘(HashMap.keys obj)’
      In the first argument of ‘Set.difference’, namely
        ‘(Set.fromList (HashMap.keys obj))’
    |
124 |                              (Set.fromList (HashMap.keys obj))
    |                                                          ^^^
cabal: Failed to build pantry-0.5.3 (which is required by stack-2.7.4). See
the build log above for details.

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

### What did you expect to happen?

Install stack successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`$ brew install stack --HEAD`
```

**Comment by SMillerDev** [comment]
We don't support head/source builds.

**Comment by simnalamburt** [comment]
@tom-pollak It's because current brew's stack installation process does not support reproducible build.

I've made a [patch](https://github.com/simnalamburt/stack/commit/a011e379b09981879387e0e25e8a48eaf12f1af0) for it. Try bellow:

```
brew install simnalamburt/x/haskell-stack
```

###### References
- https://github.com/simnalamburt/homebrew-x/blob/main/Formula/haskell-stack.rb
- https://github.com/simnalamburt/stack/commit/a011e379b09981879387e0e25e8a48eaf12f1af0

**Comment by carlocab** [comment]
As mentioned in the error message:
```
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.
```
We'll review a pull request, but don't otherwise provide support for building from source.

**Comment by simnalamburt** [comment]
I've sent a PR fixing this issue to the upstream. https://github.com/commercialhaskell/stack/pull/5677

In the meantime, we might be able to mitigate this issue by patching the haskell-stack formula. I'll create a PR for this.

**Comment by simnalamburt** [comment]
I've submit a PR for this issue. https://github.com/Homebrew/homebrew-core/pull/95032
