### ISSUE TITLE
Download from JackNagel missing

### ISSUE THREAD

**Issue by ndefreitas** [Homebrew/homebrew-core#9483]
After running "brew install pldebugger", Homebrew errors while attempting to install:

Downloading https://gist.githubusercontent.com/jacknagel/d886531fb6623b60b2af/raw/746fc543e56bc37a26ccf05d2946a45176b0894e/readline-6.3.8.diff

curl: (22) The requested URL returned error: 404 Not Found

**Comment by ilovezfs** [comment]
Your brew is quite outdated. That hasn't been in the readline formula since September.
