### ISSUE TITLE
gobject-introspection and harfbuzz builds fail due to clang segfault

### ISSUE THREAD

**Issue by aw1621107** [Homebrew/homebrew-core#9484]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

----

This has been going on for a while, but I'm not sure whether this is an issue on Apple's side or Homebrew's.

Basically, the `gobject-introspection` and `harfbuzz` formulae fail to build on my machine due to clang segfaulting during one of the build steps. I originally ran into this when trying to upgrade harfbuzz, and later found gobject-introspection exhibited the same issue.

[Here](https://gist.github.com/aw1621107/5b73b4820e771e74a6a36608dad28ac8) is the gist for `gobject-introspection`, and [here](https://gist.github.com/aw1621107/353a87d03f5a4bf05bfe03cba7299eb0) is the gist for `harfbuzz`. The crash log for Python during the `gobject-introspection` build is [here](https://gist.github.com/aw1621107/dcbd046d871f70e6d2c874f27ef5fdd3). I can't produce the log for harfbuzz at the moment since it depends on gobject-introspection, but if memory serves it was quite similar.

This occurred both on Sierra 10.12.3 and 10.12.4 beta, with Xcode 8.2.1. The Python crash logs generated by macOS seem to be similar in both cases. I've been waiting for an Xcode update to see if that would take care of the issue, but in the meantime I want to see if it's something specific to me.

**Comment by JCount** [comment]
CC @tschoonj

**Comment by tschoonj** [comment]
I cannot reproduce this on 10.12.3: everything appears to work fine here. Your brew doctor output did reveal a minor issue with the PATH variable, though I doubt that will cause this problem here. 
Also, why are you using your own repo as origin for homebrew/brew?

**Comment by aw1621107** [comment]
I was hoping that it wasn't just me... This is going to be fun to debug.

I'm using my own origin because I've found it more convenient for hacking on brew/formulae, since I need to submit PRs from my own form anyways.

**Comment by aw1621107** [comment]
Is there a way to override the compiler chosen by Homebrew? I'm thinking that maybe I can avoid the issue by bypassing the version of clang installed by macOS

**Comment by mistydemeo** [comment]
> CPU: octa-core 64-bit ivybridge

Just to check, are you using a Hackintosh or an otherwise unofficially-upgraded Mac?

**Comment by aw1621107** [comment]
Not as far as I know. Mid-2012 Retina Pro (Macbook Pro 10,1, if I remember correctly). Only unofficial upgrade that I'm aware of is an 1TB OWC SSD.

**Comment by mistydemeo** [comment]
Have you tried running a diagnostic to see if your RAM is okay?

**Comment by aw1621107** [comment]
I have not, but I will. I haven't noticed anything else that would point to bad RAM, but it's worth a shot.

**Comment by aw1621107** [comment]
Just finished running the standard hardware test; no errors found. I can try the extended one overnight.

**Comment by mistydemeo** [comment]
Thanks for checking! It would be great if you can figure out a test case that reliably segfaults clang, and then we can dig in with `lldb`.

**Comment by aw1621107** [comment]
I might need some help with that... Not even sure where to start. For what it's worth, it seems the failing target is `GLib-2.0.gir`.

Also, I tried building gobject-introspection from the GitHub release, using an older LLVM HEAD (commit 7f23c0f)  as the compiler and using brewed Python. I still get a crash, but it's SIGBUS (signal 10). Gist [here](https://gist.github.com/aw1621107/70a80098e3f8678d780a9b3d41324632).

**Comment by ilovezfs** [comment]
@aw1621107 assuming you can still currently reproduce the problem, please try
```
mkdir ~/Documents/site-packages-2017-02-07
mv /usr/local/lib/python2.7/site-packages ~/Documents/site-packages-2017-02-07/
```
and then see if the problem still occurs after doing that.

**Comment by ilovezfs** [comment]
OK. Please try in a clean installation.

```
mkdir ~/Documents/brew-2017-02-07
sudo mv /usr/local ~/Documents/brew-2017-02-07/
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install -s gobject-introspection
```

**Comment by aw1621107** [comment]
Will do. I'm going to have to go for a bit, though, so it will be some time before I can report back.

**Comment by ilovezfs** [comment]
@aw1621107 thanks!

**Comment by aw1621107** [comment]
Good news: it worked! Time to go reinstall everything...

I have no clue what I had installed that broke things, but seeing as I can't reproduce the problem any more, guess I can close this. Thanks for the help!

**Comment by ProfFan** [comment]
Got the same issue on my installation as well. Can confirm that clang exits with mysterious code 10 (BUS ERROR) in the Gir distutils build. Still investigating the root cause.
