### ISSUE TITLE
MacOS brew upgrade happen error？

### ISSUE THREAD

**Issue by andyluna** [Homebrew/homebrew-core#94906]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew upgrade
Running `brew update --preinstall`...
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
➜  ~ brew doctor
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
➜  ~ brew uninstall -f aliwangwang
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`bash
➜  local brew upgrade
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
➜  local pwd
/usr/local
➜  local brew uninstall -f aliwangwang
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
`

### What happened (include all command output)?

`
➜  ~ brew upgrade
Running `brew update --preinstall`...
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
➜  ~ brew doctor
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
➜  ~ brew uninstall -f aliwangwang
Error: Cask 'aliwangwang' is unavailable: No Cask with this name exists.
`

### What did you expect to happen?

怎么解决这个问题呢？

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew doctor also error
```

**Comment by gromgit** [comment]
Sounds like you have an invalid `aliwangwang` cask file. Find that file(s) and move it/them to a temporary directory:
```
mkdir /tmp/broken
find $(brew --repo)/Library/Taps/ -name aliwangwang.rb -exec mv -v {} /tmp/broken \;
```
then try `brew upgrade` again. If that works, you can then look at the files in `/tmp/broken` to figure out what's wrong with them.

**Comment by carlocab** [comment]
This is not an issue with a formula in this repository. It's actually not really very clear where the issue is exactly, but you should use [the Discussions page](https://github.com/Homebrew/discussions) for assistance on this.
