### ISSUE TITLE
RFE: Pivot Installer from Bash to ZSH

### ISSUE THREAD

**Issue by todd-dsm** [Homebrew/homebrew-core#95108]
Hey guys, this is an REF (Request for Enhancement). Looking to explore what it would take to move from a Bash-based installer to one that supports the default shell: ZSH.

I'm not the best with ZSH (yet) but I'd be more than willing to dig into it and pitch in. My Bash skills are bomb though. Can't imagine it would take long to solve.

### What were you trying to do (and why)?

Only trying to install with the least amount of effort.

### What happened (include all command output)?

NA

### What did you expect to happen?

NA

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
NA
```

**Comment by carlocab** [comment]
I think you're looking for https://github.com/Homebrew/install.

In any case, we almost certainly don't want to do this: the benefits of migrating to Zsh are extremely minimal. Continuing to use bash provides a much better guarantee of portability.

**Comment by todd-dsm** [comment]
**_Why would anyone be concerned with portability?_** 

Portability is a great requirement when creating a single `automation_suite` intended to be executed on unlike systems (`Linux -> UNIX -> ZOS -> wherever`) but:

1. This installer will only be executed on `macOS`
2. It's not the default shell, and
3. The version of Bash is older than Sanskrit

Please help me to understand this reasoning?

**Comment by carlocab** [comment]
> 1. This installer will only be executed on `macOS`

This is false. https://docs.brew.sh/Homebrew-on-Linux
