### ISSUE TITLE
neovim is not using the correct $VIMRUNTIME

### ISSUE THREAD

**Issue by henryhchchc** [Homebrew/homebrew-core#95140]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.3.15-25-g6198e5d
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6198e5df3d7c4e01b1f76c80fdecbbbf2b97def4
Last commit: 15 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fca1f15cd1b8237fc5cb98d89f00738be242a970
Core tap last commit: 36 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.35.1 => /opt/homebrew/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.3 => /Applications/Xcode-beta.app/Contents/Developer
Rosetta 2: false

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause formulae that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.9
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I put some plugins under `/opt/homebrew/share/nvim/runtime` and they are not loaded by neovim.

Then I check the default runtime directory of neovim by running `nvim --clean --headless --cmd 'echo $VIMRUNTIME|q'`

### What happened (include all command output)?

`nvim --clean --headless --cmd 'echo $VIMRUNTIME|q'` yields `/opt/homebrew/Cellar/neovim/0.6.1/share/nvim/runtime`

### What did you expect to happen?

`nvim --clean --headless --cmd 'echo $VIMRUNTIME|q'` should yield `/opt/homebrew/share/nvim/runtime`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- `brew install neovim`
- `nvim --clean --headless --cmd 'echo $VIMRUNTIME|q'`
```

**Comment by SMillerDev** [comment]
is there a build flag for this? Because if there isn't neovim is detecting it wrong since we don't set it anywhere in https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/neovim.rb

**Comment by henryhchchc** [comment]
I found similar workaround to this issue for `vim` at https://github.com/Homebrew/homebrew-core/blob/fca1f15cd1b8237fc5cb98d89f00738be242a970/Formula/vim.rb#L41-L47

**Comment by carlocab** [comment]
I don't think this is the correct use of `$VIMRUNTIME`. The directory you are using is for Neovim's bundled runtime.

Why aren't you using the other directories in your `runtimepath`? This is what, e.g. `~/.config/nvim` or `~/.config/nvim/after` is for.

@clason will correct me here if I'm wrong, though.

**Comment by gromgit** [comment]
> `nvim --clean --headless --cmd 'echo $VIMRUNTIME|q'` yields `/opt/homebrew/Cellar/neovim/0.6.1/share/nvim/runtime`
> ...
> `nvim --clean --headless --cmd 'echo $VIMRUNTIME|q'` should yield `/opt/homebrew/share/nvim/runtime`

The two are in fact _the same directory_:
```
$ realpath /opt/homebrew/share/nvim/runtime
/opt/homebrew/Cellar/neovim/0.6.1/share/nvim/runtime
```
Are you sure you don't need to do any other config stuff to have your plugins recognized?

Also note that a `neovim` upgrade would trash all your installed plugins. I don't use Neovim myself, but I think you want to choose a more permanent directory in the path listed by `:echo &runtimepath` instead.

**Comment by clason** [comment]
Yes, `$VIMRUNTIME` is the bundled runtime files -- you should not mess with them. The build is working as intended. For _additions_ to the runtime files, you should either put the files into one of the standard directories (`:h 'runtimepath'` from within Neovim) or add the corresponding directories to `runtimepath`. I recommend reading the documentation for this and, if you are a new user, just using a plugin manager like `vim-plug` or `packer.nvim` and not trying to do this manually.

**Comment by henryhchchc** [comment]
Thanks for the prompt replies.

> The two are in fact the same directory:

This is true if we only look at the `neovim` formula itself. Actually other formulas aiming to provide plugins to neovim can install the files to `share/"lib/nvim/runtime"` in its cellar and the files will be symlinked to `/opt/homebrew/share/nvim/runtime` afterwards. For example, if we look at `/opt/homebrew/share/vim/vimfiles`, we can see some files symlinked form the cellar of cmake.

So if does make a difference whether neovim tries to load the plugins from `/opt/homebrew/Cellar/neovim/0.6.1/share/nvim/runtime` or `/opt/homebrew/share/nvim/runtime`.

Actually I installed vim and `vim --clean --cmd 'echo $VIMRUNTIME|q'` yields `/opt/homebrew/share/vim/vim82` instead of `/opt/homebrew/Cellar/vim/8.2.4350/share/vim/vim82`.

> I don't think this is the correct use of $VIMRUNTIME. The directory you want to use is for Neovim's bundled runtime.

I am not pretty sure on this. Maybe I am referring to the wrong variable. Actually the issue is that neovim does not load the plugins provided by other formulas while vim does.

**Comment by clason** [comment]
> Actually other formulas aiming to provide plugins to neovim can install the files to share/"lib/nvim/runtime" in its cellar and the files will be symlinked to /opt/homebrew/share/nvim/runtime afterwards.

They should stop doing this. This is not how plugins should be installed for (Neo)Vim, and Neovim will not support this broken method.

**Comment by carlocab** [comment]
> > Actually other formulas aiming to provide plugins to neovim can install the files to share/"lib/nvim/runtime" in its cellar and the files will be symlinked to /opt/homebrew/share/nvim/runtime afterwards.
> 
> They should stop doing this. This is not how plugins should be installed for (Neo)Vim, and Neovim will not support this broken method.

Thankfully, I'm not aware of any homebrew/core formulae that do this.

**Comment by henryhchchc** [comment]
Thanks for the clarification.
