### ISSUE TITLE
Brew should warn when master branch is not checked out

### ISSUE THREAD

**Issue by ohcibi** [Homebrew/homebrew-core#9523]
I came across an issue after I had contributed to brew and therefore checked out another branch. The first problem happened with php, so I wrongly posted an issue there: https://github.com/Homebrew/homebrew-php/issues/3899

It actually belongs to the core; so I closed it in homebrew-php and reopened it here.

**Comment by MikeMcQuaid** [comment]
If you've contributed to Homebrew we assume you know how to use Git and don't change branches for you. If you haven't we'll always switch to master.

Please in future also fill out the issue template for every issue.

**Comment by ohcibi** [comment]
`brew doctor` reports all sorts of stuff about the system that can be wrong. Does the fact that those information is provided means you assume, I don't know how to use my computer? I also think that you had a misunderstanding. The issue does not read "should change branches" but "should warn about changed branches" in a way that `doctor` detects (but doesn't try to fix) other potential causes for trouble.

I actually did use the template but I followed this hint:

> You can erase any parts of this template not applicable to your Issue.

There is nothing relevant for a feature (not formula) request in that template unless I've overseen something.

**Comment by MikeMcQuaid** [comment]
> There is nothing relevant for a feature (not formula) request in that template unless I've overseen something.

It should have been filed in Homebrew/brew.

> brew doctor reports all sorts of stuff about the system that can be wrong. Does the fact that those information is provided means you assume, I don't know how to use my computer? I also think that you had a misunderstanding. The issue does not read "should change branches" but "should warn about changed branches" in a way that doctor detects (but doesn't try to fix) other potential causes for trouble.

I don't think you don't know how to use your computer, I just think that `brew doctor` is a tool for maintainers to help debug problems so it shouldn't warn on things maintainers will have done intentionally themselves.

**Comment by ohcibi** [comment]
I just did a `brew doctor` and it tells me this:

> Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

So the expression of this message is: "There is something 'unnormal'. If you have done that intentionally, ignore it. If it was done by mistake or even without your knowledge, its better to fix that". - That is exactly what I'd expected my branch-warning-message to express and I find the example I found contradicts your statement that "brew doctor [...] shouldn't warn on things maintainers will have done intentionally themselves.". The message from the example basically says exactly that except that it uses the phrase "on purpose" instead of "intentionally".

Maybe there is a higher difference between "intentionally" and "on purpose" that I don't grasp as a non-native speaker; but i've just found this in Dictionary.app when I looked up `intentionally`: `intentionally |ɪnˈtɛnʃ(ə)nəli, ɪnˈtɛnʃən(ə)li|
adverb
deliberately; on purpose: I didn't do it intentionally | I wasn't sure if it was intentionally funny or not.` 8-)).

**Comment by MikeMcQuaid** [comment]
> That's not something I can read from the template, can I?

> Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new
> Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

https://github.com/Homebrew/homebrew-core/blob/master/.github/ISSUE_TEMPLATE.md

Regardless, we'll consider this but we're not interested in this change at this time, thanks.
