### ISSUE TITLE
update wiggle tap 1.2 -> 1.3

### ISSUE THREAD

**Issue by geofflangenderfer** [Homebrew/homebrew-core#95290]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
✦3 ❯ brew update && brew upgrade && brew doctor
Already up-to-date.

```
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

```
```
wiggle
✦3 ❯ brew create https://github.com/neilbrown/wiggle/archive/refs/tags/v1.3.tar.gz
Error: /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/wiggle.rb already exists
```

### What happened (include all command output)?

see above

### What did you expect to happen?

update wiggle from 1.2 -> 1.3

### Step-by-step reproduction instructions (by running `brew` commands)

see above

**Comment by geofflangenderfer** [comment]
I would do this myself but I couldn't find docs for updating the various checksums(?)

**Comment by geofflangenderfer** [comment]
https://github.com/Homebrew/homebrew-core/pull/95291

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
