### ISSUE TITLE
Cannot install six from source

### ISSUE THREAD

**Issue by imresteiner** [Homebrew/homebrew-core#95304]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config                         
HOMEBREW_VERSION: 3.3.15-58-gbdf25a5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bdf25a57ca985d4b87c995bebbf4b76a544dc889
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: df8e884b28243416f9adb2cae98e66c44743c24a
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit kabylake
Clang: 11.0.3 build 1103
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 11.7

-----

> brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Xcode (11.7) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install six from source.

### What happened (include all command output)?

> brew install --build-from-source six
==> Downloading https://files.pythonhosted.org/packages/71/39/171f1c67cd00715f190ba0b100d606d440a28c93c7714febeca8b79af85e/six-1.16.0.tar.gz
Already downloaded: /Users/titkos/Library/Caches/Homebrew/downloads/3090f0022e8388f5c3bbff25d19f54b7af62562659cbf599e5f7fb044f280199--six-1.16.0.tar.gz
Warning: Your Xcode (11.7) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.

==> /usr/local/opt/python@3.8/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/six/1.16.0_2 --install-scripts=/usr/local/Cellar/six/1.16.0_2/bin --single-version-externally-managed --r
==> /usr/local/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/six/1.16.0_2 --install-scripts=/usr/local/Cellar/six/1.16.0_2/bin --single-version-externally-managed --r
==> /usr/local/opt/python@3.10/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/six/1.16.0_2 --install-scripts=/usr/local/Cellar/six/1.16.0_2/bin --single-version-externally-managed --
Last 15 lines from /Users/titkos/Library/Logs/Homebrew/six/03.python3:
--no-user-cfg
install
--prefix=/usr/local/Cellar/six/1.16.0_2
--install-scripts=/usr/local/Cellar/six/1.16.0_2/bin
--single-version-externally-managed
--record=installed.txt

running install
/usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build
running build_py
running install_lib
copying build/lib/six.py -> /usr/local/lib/python3.10/site-packages
error: could not create '/usr/local/lib/python3.10/site-packages/six.py': Operation not permitted

READ THIS: https://docs.brew.sh/Troubleshooting

Error: Your Xcode (11.7) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.

### What did you expect to happen?

A successful install. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update && brew update-reset
brew install --build-from-source six
```

**Comment by SMillerDev** [comment]
```
Error: Your Xcode (11.7) is outdated.
Please update to Xcode 12.4 (or delete it).
Xcode can be updated from the App Store.
```

This might have something to do with it, but we don't support source builds so you'll have to see for yourself what fixes this.

**Comment by carlocab** [comment]
This is probably due to changes in Python 3.10. We'll likely need to use `pip` to install this there. This will be an issue when we need to rebuild `six`, but no one really needs to install this from source.
