### ISSUE TITLE
error: Unsupport load command from llvm tools on m1 mac

### ISSUE THREAD

**Issue by seanhess** [Homebrew/homebrew-core#95319]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
➜  ~ brew config
HOMEBREW_VERSION: 3.3.15
ORIGIN: https://github.com/Homebrew/brew
HEAD: d603fd6426ddae27327bb51afb085653eb2d84a7
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 676e2af4ae8e54c41107aaf533e2490a4fc28b7c
Core tap last commit: 51 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit westmere
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: N/A
Rosetta 2: true
➜  ~ brew doctor
Your system is ready to brew.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to set up a new m1 mac to compile haskell projects using haskell-stack and llvm. Compilation fails when certain haskell packages call out to llvm tools (llvm strip, and install_name_tool)  I'm not sure what to do, or where to file this bug. 

Note that these are llvm errors, not haskell ones. 

### What happened (include all command output)?

After setting up a new m1 mac using homebrew, haskell-stack, and llvm, I'm getting strange errors from llvm tools. I am trying to build my project using haskell-stack. Everything works fine, but a few haskell packages that depend on llvm are throwing errors. Specifically, llvm-strip throws this error: `/opt/homebrew/opt/llvm/bin/strip: error: unsupported load command (cmd=0x80000034)`

I then tried reinstalling everything and running under rosetta, which resolved the above issue with llvm strip, but I then get the same error compiling a different package that calls out to install_name_tool: `install_name_tool: error: unsupported load command (cmd=0x80000034)`

Complete output of the build command below:

```
➜  ~ arch -x86_64 stack build generics-sop
generics-sop> configure
generics-sop> Configuring generics-sop-0.5.1.2...
generics-sop> build
generics-sop> Preprocessing library for generics-sop-0.5.1.2..
generics-sop> Building library for generics-sop-0.5.1.2..
generics-sop> [ 1 of 14] Compiling Generics.SOP.BasicFunctors
generics-sop> [ 2 of 14] Compiling Generics.SOP.Classes
generics-sop> [ 3 of 14] Compiling Generics.SOP.Constraint
generics-sop> [ 4 of 14] Compiling Generics.SOP.Dict
generics-sop> [ 5 of 14] Compiling Generics.SOP.NP
generics-sop> [ 6 of 14] Compiling Generics.SOP.Metadata
generics-sop> [ 7 of 14] Compiling Generics.SOP.NS
generics-sop> [ 8 of 14] Compiling Generics.SOP.Sing
generics-sop> [ 9 of 14] Compiling Generics.SOP.Type.Metadata
generics-sop> [10 of 14] Compiling Generics.SOP.GGP
generics-sop> [11 of 14] Compiling Generics.SOP.Universe
generics-sop> [12 of 14] Compiling Generics.SOP.TH
generics-sop> [13 of 14] Compiling Generics.SOP.Instances
generics-sop> install_name_tool: error: unsupported load command (cmd=0x80000034)
generics-sop> `install_name_tool' failed in phase `Install Name Tool'. (Exit code: 1)

--  While building package generics-sop-0.5.1.2 (scroll up to its section to see the error) using:
      /Users/sean/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

### What did you expect to happen?

I expect the packages to compile without llvm errors

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Start with a new M1 mac. (Mine is Monterrey 12.1)
2. Install homebrew
3. Install llvm and haskell-stack via homebrew `brew install llvm haskell-stack`
4. Install GHC via ghcup
5. Add relevant LLVM binaries to your path
6. `stack build happy --system-ghc`


happy> /opt/homebrew/opt/llvm/bin/strip: error: unsupported load command (cmd=0x80000034)
```

Alternately, repeat the above using rosetta with all homebrew commands prefixed by `arch -x86_64`

2. Install homebrew
3. Install llvm and stack via homebrew `arch -x86_64 brew install haskell-stack llvm`
4. Add relevant LLVM and Homebrew binaries to your path
5. `arch -x86_64 stack build happy` <-- This works now!?
6. `arch -x86_64 stack build generics-sop` <-- error

```
generics-sop> install_name_tool: error: unsupported load command (cmd=0x80000034)
```
```

**Comment by carlocab** [comment]
Does this reproduce with a non-Homebrew version of LLVM 13.0.1? e.g. https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.1

**Comment by cho-m** [comment]
Also, we've had issues with `llvm@13` (current `llvm` formula) before in combination with Haskell, so it may be more stable to use `llvm@12` formula.

**Comment by carlocab** [comment]
Something like this should work:
```
mkdir llvm-13
curl -L https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/clang+llvm-13.0.1-x86_64-apple-darwin.tar.xz | tar -xz --strip 1 -C llvm-13
ln -s llvm-install-name-tool llvm-13/bin/install_name_tool
export PATH="$(pwd)/llvm-13/bin:$PATH"
```

**Comment by seanhess** [comment]
LLVM 12 fixes the issue! Thanks for your help.

**Comment by carlocab** [comment]
Can you check the non-Homebrew LLVM?

It's pretty important to know whether this is a regression in LLVM 13 or if `llvm-strip` and `llvm-install-name-tool` don't work as drop-in replacements for `strip` and `install_name_tool` respectively.

Alternatively, you can also try
```
ln -s llvm-install-name-tool "$(brew --prefix llvm@12)/bin/install_name_tool"
ln -s llvm-strip "$(brew --prefix llvm@12)/bin/strip"
```
and then see if you can now reproduce the failure with LLVM 12. You can just do
```
rm "$(brew --prefix llvm@12)"/bin/{strip,install_name_tool}
```
when you're done.

**Comment by seanhess** [comment]
@carlocab I followed your instructions and got the same error when building generics-sop. 

```
➜  Downloads which llvm-config
/Users/sean/Downloads/llvm-13/bin/llvm-config
➜  Downloads which install_name_tool
/Users/sean/Downloads/llvm-13/bin/install_name_tool

➜  Downloads stack build generics-sop
generics-sop> configure
generics-sop> Configuring generics-sop-0.5.1.2...
generics-sop> build
generics-sop> Preprocessing library for generics-sop-0.5.1.2..
generics-sop> Building library for generics-sop-0.5.1.2..
generics-sop> [ 1 of 14] Compiling Generics.SOP.BasicFunctors
generics-sop> [ 2 of 14] Compiling Generics.SOP.Classes
generics-sop> [ 3 of 14] Compiling Generics.SOP.Constraint
generics-sop> [ 4 of 14] Compiling Generics.SOP.Dict
generics-sop> [ 5 of 14] Compiling Generics.SOP.NP
generics-sop> [ 6 of 14] Compiling Generics.SOP.Metadata
generics-sop> [ 7 of 14] Compiling Generics.SOP.NS
generics-sop> [ 8 of 14] Compiling Generics.SOP.Sing
generics-sop> [ 9 of 14] Compiling Generics.SOP.Type.Metadata
generics-sop> [10 of 14] Compiling Generics.SOP.GGP
generics-sop> [11 of 14] Compiling Generics.SOP.Universe
generics-sop> [12 of 14] Compiling Generics.SOP.TH
generics-sop> [13 of 14] Compiling Generics.SOP.Instances
generics-sop> install_name_tool: error: unsupported load command (cmd=0x80000034)
generics-sop> `install_name_tool' failed in phase `Install Name Tool'. (Exit code: 1)

--  While building package generics-sop-0.5.1.2 (scroll up to its section to see the error) using:
      /Users/sean/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.2.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by BeJF** [comment]
I got the same error with a M1 mac : Failed to build generic-sop-0.5.1.1
Went back to LLVM12 and it seems to fix it

**Comment by carlocab** [comment]
Thanks @seanhess. That helps a lot, and shows that the problem isn't specific to our build of LLVM. I wonder if it's because we configured LLVM to create symlinks for `install_name_tool`, `strip`, etc.

Does it work if you try it after adding some symlinks for `llvm@12`, as in https://github.com/Homebrew/homebrew-core/issues/95319#issuecomment-1044425691?

**Comment by paperchalice** [comment]
#94695 also suffered this issue.

**Comment by carlocab** [comment]
@paperchalice do you know if it works after removing the binutils/cctools symlinks in LLVM's `bin` directory? These are probably: `ar`, `c++filt`, `dlltool`, `dwp`, `install_name_tool`, `nm`, `objcopy`, `objdump`, `ranlib`, `readelf`, `size`, `strings`, `strip`, `windres`.

**Comment by cho-m** [comment]
We removed `llvm` symlinks in #96067 and that seems to have fixed similar issues in other PRs (e.g. `julia`, `grokj2k`, ...). Closing for now as hopefully fixed, but let us know if any issues still occur.
