### ISSUE TITLE
Cannot install rocksdb from source

### ISSUE THREAD

**Issue by jansegre** [Homebrew/homebrew-core#95327]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.3.15-58-gbdf25a5
ORIGIN: https://github.com/Homebrew/brew
HEAD: bdf25a57ca985d4b87c995bebbf4b76a544dc889
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 51a36c9d2108e268feb2f6681b4531fb26103e29
Core tap last commit: 24 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2-x86_64
CLT: 12.5.0.22.9
Xcode: 13.2.1
```

I honestly believe these have no effect on this issue.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [x] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to install `rocksdb` from source with  `brew install -s rocksdb`.

### What happened (include all command output)?

I got a hash mismatch:

```
==> Downloading https://github.com/facebook/rocksdb/archive/v6.28.2.tar.gz
==> Downloading from https://codeload.github.com/facebook/rocksdb/tar.gz/refs/tags/v6.28.2
######################################################################## 100.0%
Error: rocksdb: SHA256 mismatch
Expected: e4d97e70f959038af9caababe0c21b224200de9e8eee965564108eb710366e75
  Actual: 186a833fa36e85bd9b0b7f0577c01da42d8de82115cc4df775befb03aff98485
    File: /Users/jan/Library/Caches/Homebrew/downloads/b32b7b7a0875b6ed717ee0d7175bb3593f01e5e71d89cbfaa4bde1874a9d663e--rocksdb-6.28.2.tar.gz
To retry an incomplete download, remove the file above.
```

I've downloaded the [source file](https://github.com/facebook/rocksdb/archive/v6.28.2.tar.gz) on a few different machines and I get the same hash on all of them: `186a833fa36e85bd9b0b7f0577c01da42d8de82115cc4df775befb03aff98485`.

Furthermore this was triggered because [a header](https://github.com/facebook/rocksdb/blob/v6.28.2/include/rocksdb/utilities/backupable_db.h) was missing on the bottled version of rocksdb, but not on the official source, so when I tried installing from source I got the error.

### What did you expect to happen?

I expected the formula to install correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install -s rocksdb
```

Or straight from the docker image:

```shell
docker run --interactive --tty --rm --pull always homebrew/ubuntu16.04:latest brew install -s rocksdb
```

**Comment by SMillerDev** [comment]
Since there is a PR now I'm going to close this
