### ISSUE TITLE
Boost@1.78.0 missing stacktrace (and fiber?) libraries

### ISSUE THREAD

**Issue by gergondet** [Homebrew/homebrew-core#95520]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
No issue with the formula installation itself. I'm not sure I can include any output that would be helpful here, `brew gist-logs boost` says there is "No logs"
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am installing boost via brew using `brew install boost`

### What happened (include all command output)?

The installation is successful but the following library is missing:
- Boost.Stacktrace

It seems to stem in a bug from b2 (https://github.com/bfgroup/b2/issues/104). It also seems [vcpkg](https://github.com/microsoft/vcpkg/pull/21928) ran into a similar issue when upgrading to 1.78.0

From those reports it seems to affect Boost.Fiber as well.

### What did you expect to happen?

The library should be included in the package.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install boost
# Will output nothing where it should
ls -la /usr/local/lib/libboost_stacktrace*
```

**Comment by cho-m** [comment]
I think this issue's fix is planned to be included with `icu4c` PR #88210 (Commit: https://github.com/Homebrew/homebrew-core/pull/88210/commits/e773b5675e2e6bcf096f24a1e9a305784f278991); however, it may take some time since there is a large number of formulae being updated at once.

**Comment by carlocab** [comment]
You can use `boost@1.76` for now if you need the stack trace library.

**Comment by gergondet** [comment]
Thanks for the swift reply, glad it's being addressed.

No rush on my side so I can wait for the release of the revision.

Thanks for your help on this issue and your work on brew in general :cake:

**Comment by carlocab** [comment]
This should be fixed now: `brew update && brew upgrade boost`

Apologies for the delay -- getting https://github.com/Homebrew/homebrew-core/pull/88210 merged was quite difficult.
