### ISSUE TITLE
No way to return to boost-python3@1.76, with broken boost 1.78

### ISSUE THREAD

**Issue by nloira** [Homebrew/homebrew-core#95793]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
No issue with the formula installation itself.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

My code depends on `boost` and `boost-python3`, but `boost` 1.78.0 is broken (missing stacktrace, see [here](https://github.com/Homebrew/homebrew-core/issues/95520)). While it's easy to return to `boost@1.76`, there's no way to return to `boost-python3@1.76`. The current `boost-python3` depends on the broken `boost@1.78`.

Can you please provide a `boost-python3@1.76`, at least until 1.78 is fixed?

### What happened (include all command output)?

```
$ brew install boost-python3@1.76
Warning: No available formula with the name "boost-python3@1.76". Did you mean boost-python3 or boost-python
...
```

### What did you expect to happen?

To be able to return to `boost-python3@1.76` using: `brew install boost-python3@1.76`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew uninstall boost@1.78 boost-python3
brew install boost@1.76
brew install boost-python3@1.76
```
```

**Comment by carlocab** [comment]
You can install `boost-python3@1.76` by using `brew extract` to maintain a this formula in your own tap.

Here are some docs to help you get started:

https://docs.brew.sh/Taps
https://docs.brew.sh/Interesting-Taps-and-Forks
https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap
https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by nloira** [comment]
Thanks @carlocab, but this is way too complicated!
While I can give it a try, I know several other users that are having the same problem, and my local solution will not work for them.

Is there another way to return to a working `boost-python3@1.76`?
Or, can anybody please add back `boost-python3@1.76` to homebrew-core?

**Comment by carlocab** [comment]
This really isn't anywhere near as complicated as writing non-trivial C++ code, so I'm sure you can manage. You can probably try something like this:
```
brew tap-new nloira/your-tap-name-here
brew extract --version=1.76.0 boost-python3 nloira/your-tap-name-here
```
Then, you'll want to do
```
brew edit nloira/your-tap-name-here/boost-python3@1.76.0
```
to make sure this depends on `boost@1.76`. You'll probably also want to make it keg-only. When you're done, you can install it with
```
brew install boost-python3@1.76.0
```
You can also change the `class` name and filename to avoid needing the extra `.0` in the formula name.

> While I can give it a try, I know several other users that are having the same problem, and my local solution will not work for them.

Your tap is a Git repository which you'll be able to find at `$(brew --repository nloira/your-tap-name-here)`. You can allow other users to use your tap by creating a repository named `homebrew-your-tap-name-here` in your account, and others will be able to install it with
```
brew install nloira/your-tap-name-here/boost-python3@1.76.0
```

> Or, can anybody please add back `boost-python3@1.76` to homebrew-core?

It doesn't satisfy our [requirements for versioned formulae](https://docs.brew.sh/Versions#acceptable-versioned-formulae), so any versioned `boost-python3` will need to be hosted in an external tap.
