### ISSUE TITLE
Boost not found

### ISSUE THREAD

**Issue by drathier** [Homebrew/homebrew-core#958]
### Bug reports:

Trying to install cputhrottle from source, which depends on boost. Boost installs fine, but the installation fails with 

```
/usr/bin/g++ -c -g -Wall -I..///boost_1_43_0 manip.cc
In file included from cputhrottle.cc:5:
./manip.h:4:10: fatal error: 'boost/shared_ptr.hpp' file not found
#include <boost/shared_ptr.hpp>
         ^
In file included from manip.cc:1:
./manip.h:4:10: fatal error: 'boost/shared_ptr.hpp' file not found
#include <boost/shared_ptr.hpp>
         ^
1 error generated.

```

https://gist.github.com/decc2e608d3b8292cef484a9fd45d60c

**Comment by DomT4** [comment]
Fixed via https://github.com/Homebrew/homebrew-core/commit/a9e0ff2fea75cf471923c9932c15992ea02744eb. Thanks for the report!
