### ISSUE TITLE
OpenBLAS support for numpy and scipy?

### ISSUE THREAD

**Issue by kyungminlee** [Homebrew/homebrew-core#9580]
Recently `numpy` and `scipy` have been imported from `homebrew-python` after it has been deprecated. OpenBLAS, however, support has been removed. Was this on purpose? It was certainly useful in `Linuxbrew`.

**Comment by kyungminlee** [comment]
@MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
We don't support Linuxbrew in homebrew-core. They should add this in their own fork.
