### ISSUE TITLE
mlt.rb formula makes a build appropriate only for app bundles

### ISSUE THREAD

**Issue by ddennedy** [Homebrew/homebrew-core#95811]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I do not use homebrew. I am the upstream maintainer helping you to fix a broken build configuration.
See https://github.com/mltframework/mlt/issues/774

For the CMake invocation you need to add `-DRELOCATABLE=OFF` as that defaults to on if Apple.

### What happened (include all command output)?

N/A

### What did you expect to happen?

N/A

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by carlocab** [comment]
Could you elaborate a little on what `-DRELOCATABLE=OFF` does on macOS?

**Comment by ddennedy** [comment]
It tells the library to look for it’s dynamically loaded modules and resources relative to the install prefix using typical paths like lib and share rather than app bundle folders such as PlugIns and Resources.

**Comment by carlocab** [comment]
Thanks!
