### ISSUE TITLE
Afsctool is outdated (1.6.4 vs 1.7.2)

### ISSUE THREAD

**Issue by rotu** [Homebrew/homebrew-core#95852]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install `afsctool` to compress files.

### What happened (include all command output)?

```
brew install afsctool
==> Downloading https://ghcr.io/v2/homebrew/core/afsctool/manifests/1.6.4_2-2
Already downloaded: /Users/dan/Library/Caches/Homebrew/downloads/37b0639307f2afff6472458c9a1f55f4c877762de444da585f2c4f5e55ef02de--afsctool-1.6.4_2-2.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/afsctool/blobs/sha256:01af9a80d
Already downloaded: /Users/dan/Library/Caches/Homebrew/downloads/e407f8c3edc4b0a743d670145ed7b8813844955672844395ad16c0666dcbf83a--afsctool--1.6.4_2.arm64_big_sur.bottle.2.tar.gz
==> Pouring afsctool--1.6.4_2.arm64_big_sur.bottle.2.tar.gz
🍺  /opt/homebrew/Cellar/afsctool/1.6.4_2: 4 files, 122.6KB
==> Running `brew cleanup afsctool`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

### What did you expect to happen?

The `afsctool` package is version 1.6.4, which is broken on Mojave and newer. The latest version is 1.7.2 available on its Github https://github.com/RJVB/afsctool

this was previously raised in https://github.com/Homebrew/homebrew-core/issues/40041 and https://github.com/Homebrew/homebrew-core/issues/64643

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install afsctool`
```

**Comment by SMillerDev** [comment]
https://docs.brew.sh/Updating-Software-in-Homebrew
