### ISSUE TITLE
Status of support for older macOS versions?

### ISSUE THREAD

**Issue by fxcoudert** [Homebrew/homebrew-core#9601]
Although homebrew doesn't actively support macOS versions older than 10.10 (i.e. we support Yosemite and later), in many core formulas there are hacks to support very old macOS versions:

- Tiger (10.4) in formulas `dyld-headers.rb`, `ld64.rb`, `libunwind-headers.rb`, `gcc@*.rb`, and `ppl@0.11.rb`
- Leopard (10.5) in formulas `collectd.rb`, `couchdb.rb`, `libmemcached.rb`, `libmms.rb`, `libvirt.rb`, `libxml++.rb`, `libxml++3.rb`, `mpd.rb`, `mplayer.rb`, `nspr.rb`, `postgres-xc.rb`, `postgresql.rb`, `rabbitmq.rb`, `ranger.rb`, `ranger.rb`, `subversion.rb`, `transmission.rb`, `libunwind-headers.rb`, `media-info.rb`, `mediaconch.rb`

Those OSes had their final releases 9 and 7 years ago respectively, and have been unsupported for 8 and 6 years. Would it be suitable to clean it up? If so, I could open a pull request for that.

**Comment by ilovezfs** [comment]
CC @mistydemeo @MikeMcQuaid

**Comment by MikeMcQuaid** [comment]
Let's leave the support there unless we've tested on those platforms and it's actively broken.
