### ISSUE TITLE
Homebrew openconnect formula installs a script that requires changes to /etc instead of /usr/local/etc for hooks

### ISSUE THREAD

**Issue by pwolanin** [Homebrew/homebrew-core#96112]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```
$ brew config
HOMEBREW_VERSION: 3.4.0-2-gba32e95
ORIGIN: https://github.com/Homebrew/brew
HEAD: ba32e95760430ae619fda4a93da1e802ec73a125
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 6b9d34f3f1560e867700ff465785efd7a9805b0c
sCore tap last commit: 2 days ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0.0 build 1200
Git: 2.35.1 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.28
Xcode: N/A
```

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 12.4.


Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  dirmngr
  gpg-agent
  chromedriver

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
  php@7.4

Warning: Some installed formulae are not readable:
  percona-server@5.7.24-27: Invalid bottle tag symbol

Warning: You have uncommitted modifications to Homebrew/homebrew-cask.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask && git stash && git clean -d -f

Uncommitted files:
  ?? Formula/percona-server@5.7.24-27.rb

Warning: Homebrew's "sbin" was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting your PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.profile
```

The formula:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/openconnect.rb

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [ ] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install a post-connect hook script
as described https://gitlab.com/openconnect/vpnc-scripts/-/issues/15

the brew install puts the vpnc-script in /usr/local

```Default vpnc-script (override with --script): /usr/local/etc/vpnc-script```

However, inside that script the variable for the hooks directory points to /etc:
```HOOKS_DIR=/etc/vpnc```

The homebrew install should modify this script to use /usr/local/etc/vpnc instead

### What happened (include all command output)?

```
$ openconnect --version
OpenConnect version v8.20
Using GnuTLS 3.7.3. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp, pulse, f5, fortinet, array
Default vpnc-script (override with --script): /usr/local/etc/vpnc-script

$ fgrep HOOKS_DIR= /usr/local/etc/vpnc-script
HOOKS_DIR=/etc/vpnc
```

### What did you expect to happen?

```
$ fgrep HOOKS_DIR= /usr/local/etc/vpnc-script
HOOKS_DIR=/usr/local/etc/vpnc
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install openconnect
openconnect --version
fgrep HOOKS_DIR= /usr/local/etc/vpnc-script
```

**Comment by carlocab** [comment]
> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

Please provide the requested information and we can reopen this; thanks.

**Comment by pwolanin** [comment]
@carlocab  maybe this was not the right place to file it?  How do I make a small feature request for a formula?

**Comment by carlocab** [comment]
This is the right repository for bug reports about formulae. We ask that feature requests come in the form of pull requests.

**Comment by pwolanin** [comment]
@carlocab have updated the info - would be happy to make a PR if you can point me to an example of patching or altering an included script from a resource section

**Comment by cho-m** [comment]
You can use the [`inreplace`](https://docs.brew.sh/Formula-Cookbook#inreplace) to find-and-replace text inside files.

There are numerous examples of this in formulae like:
- `mariadb`:
    ```rb
    inreplace "#{etc}/my.cnf", "!includedir /etc/my.cnf.d",
                               "!includedir #{etc}/my.cnf.d"
    ```
- `apr`:
    ```rb
    inreplace bin/"apr-#{version.major}-config", prefix, opt_prefix
    ```

**Comment by carlocab** [comment]
`vpnc-script` is installed into `etc`, though. We consider files there part of user configuration, and try very hard to not overwrite anything a user already has in that directory. (That's why you won't find symlinks there, for example.)

I suspect the more appropriate course of action here is for you to modify your version of the `vpnc-script`. Upgrading/reinstalling `openconnect` will not affect any changes you make.

**Comment by pwolanin** [comment]
in the homebrew version it seems vpnc-script is installed in /usr/local/etc - is that what you mean? So if I update openconnect that script is not updated?  That seems a little problematic if there are upstream improvements.

I'm guessing that choice to put it in etc is made as part of the homebrew build of openconnect?

**Comment by carlocab** [comment]
> in the homebrew version it seems vpnc-script is installed in /usr/local/etc - is that what you mean?

Yes. Except if won't be in `/usr/local` if your Homebrew install isn't in `/usr/local`.

>So if I update openconnect that script is not updated?

Yes.

>That seems a little problematic if there are upstream improvements.

It also means that doing `brew upgrade` won't destroy any modifications you've made to your configuration files installed into `etc`. If upstream ship a newer version of a file called `foo` in `etc`, then Homebrew will install the newer `foo` as `foo.default` so you can incorporate any changes that you'd like to into your existing configuration.

We do this with `etc` per the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure).

> I'm guessing that choice to put it in etc is made as part of the homebrew build of openconnect?

Yes. See

https://github.com/Homebrew/homebrew-core/blob/d39b1a10aaf5b426d1653ef58eb7abdeacfe1b94/Formula/openconnect.rb#L42

https://github.com/Homebrew/homebrew-core/blob/d39b1a10aaf5b426d1653ef58eb7abdeacfe1b94/Formula/openconnect.rb#L54

I can't speak to why exactly this was the location chosen in 3c993ee653ec72a54bf571086bb1b62813354b43, but it's likely because the default location of the `vpnc-script` installation is in `/etc/vpnc`.
