### ISSUE TITLE
gcc-11: ld: library not found for -lSystem on macOS Big Sur

### ISSUE THREAD

**Issue by omor1** [Homebrew/homebrew-core#96142]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

`brew config`:
```shell
HOMEBREW_VERSION: 3.4.0-31-g3ddcaac
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3ddcaacfd752730a573da9e56e92ab50dff675a7
Last commit: 13 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: edbe0a318569b1be7233d936b0bd0c39d0b406f3
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.4-x86_64
CLT: 11.3.0.32.62
Xcode: 13.2.1
```

`brew doctor`:
```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.


Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  tbb@2020
```
Note: I believe that "Command Line Tools are too outdated" is a false positive, to the best of my knowledge they are fully updated. Apple Clang version is `clang-1300.0.29.30` and `ld` is `711`, which match up with Xcode 13.2/13.2.1.

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to compile & install software with Homebrew gcc-11 (formula `gcc`). A trivial example is below.
```
echo 'int main(void) { return 0; }' | gcc-11 -o test -x c -
```

### What happened (include all command output)?

Compiling _anything_ refuses to link:
```bash
$ echo 'int main(void) { return 0; }' | gcc-11 -o test -x c -; echo "status: $?"
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
status: 1
```

Using gcc-10 works:
```bash
$ echo 'int main(void) { return 0; }' | gcc-10 -o test -x c -; echo "status: $?"
status: 0
```

### What did you expect to happen?

I expected GCC to compile and link programs properly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install gcc
$ echo 'int main(void) { return 0; }' | gcc-11 -o test -x c -; echo "status: $?"
$ brew install gcc@10
$ echo 'int main(void) { return 0; }' | gcc-10 -o test -x c -; echo "status: $?"
```

**Comment by carlocab** [comment]
> Note: I believe that "Command Line Tools are too outdated" is a false positive, to the best of my knowledge they are fully updated. Apple Clang version is `clang-1300.0.29.30` and `ld` is `711`, which match up with Xcode 13.2/13.2.1.

No, this is not a false positive. You're picking up the versions of `clang` and `ld` in your `Xcode.app`, when what's relevant here is the `clang` and `ld` in the CLT, which _is_ outdated:
```
CLT: 11.3.0.32.62
```
Please follow this:
```
Warning: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.
```
You should see something like
```
CLT: 13.2.0.0.1.1638488800
```
in `brew config` when you've successfully upgraded your CLT.

If you'd rather not do this, you can also delete your CLT installation (`sudo rm -rf /Library/Developer/CommandLineTools`) and then rebuild GCC from source (`brew reinstall -s gcc`). This will configure your GCC install so that it makes use of your Xcode installation.

Note that we don't provide support for source builds, and these can be very mercurial.

**Comment by omor1** [comment]
So, I just deleted and reinstalled CLT:
```
$ sudo rm -rf /Library/Developer/CommandLineTools
$ sudo xcode-select --install
```
I _still_ got an old CLT and had to use `softwareupdate` to _actually_ get updated components (which it was refusing to update previously). 

So if I understand correctly, Homebrew will _always_ use the CLT, even when it's severely outdated as compared to Xcode proper _and_ the Xcode versions of the tools are selected via `xcode-select` , and macOS refuses—for whatever reason—to correctly update the CLT in some circumstances, necessitating a full deletion and reinstallation of the CLT?

Ugh, that's frustrating. It might be worthwhile to note that it is sometimes necessary to update even _after_ reinstalling. Why, _why_ does Apple do this...

**Comment by carlocab** [comment]
Do this:
```
sudo rm -rf /Library/Developer/CommandLineTools
```
and then download the `Command Line Tools for Xcode 13.2.1` from https://developer.apple.com/download/all/. `softwareupdate` and `xcode-select` are known to get confused about the right versions sometimes.

> So if I understand correctly, Homebrew will _always_ use the CLT, even when it's severely outdated as compared to Xcode proper _and_ the Xcode versions of the tools are selected via `xcode-select` , and macOS refuses—for whatever reason—to correctly update the CLT in some circumstances, necessitating a full deletion and reinstallation of the CLT?

Not always; only _sometimes_. There are a handful of formulae (e.g. `gcc`, `python@3.*`, `llvm`) that hardcode that path to the SDK, and these will typically not work unless you have the latest CLT installed. Most other formulae should work with an outdated CLT.
