### ISSUE TITLE
Git -C ... unshallow fails, "-C" invalid git flag

### ISSUE THREAD

**Issue by sygibson** [Homebrew/homebrew-core#96201]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Attempting to update brew (eg "brew update"), produces the helpful unshallow operations commands of:


  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
```

However, `git` complains that `-C` is not a valid flag.  This is git:

MacOS git version 1.8.4
Linux (centos 7) git version 1.8.3.1

I am uncertain how to perform the unshallow operation without the presence of these options.
```


### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew update` to install new formulas

subsequently tried running the error output suggested fix:

```
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
```


### What happened (include all command output)?

```
shane@fuji:~$   git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

### What did you expect to happen?

unshallow operation to succeed


### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew update`
then

  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
```
```

**Comment by carlocab** [comment]
> Please note we will close your issue without comment if you do not fill out the issue checklist below and provide ALL the requested information.

Please provide the requested information and we can reopen this; thanks.
