### ISSUE TITLE
rocksdb now installs librocksdb_lite

### ISSUE THREAD

**Issue by tmm1** [Homebrew/homebrew-core#9621]
As of https://github.com/Homebrew/homebrew-core/commit/6445d90c4723fd9f27e1e0e4ac4ab8f913f3f31a, the rocksdb package now builds rocksdb_lite by default. RocksDBLite is a separate version of rocksdb, and is not compatible with the original. Any application which currently has a dependency on the rocksdb homebrew package is now broken, because the package no longer providers librocksdb.dylib

I think it makes sense to restore the original behavior. osquery can still depend on librocksdb.dylib and work fine with it. Or, we can add a new `rocksdb_lite` formula which installs librocksdb_lite.dylib, since both versions can be installed side-by-side.

cc @ilovezfs What do you think?

**Comment by ilovezfs** [comment]
I think given that this is the first time this is being raised here that the majority of our users are better served by having the bottles be rocksdb_lite.

**Comment by tmm1** [comment]
What about having different formulae?

**Comment by ilovezfs** [comment]
That would be highly unusual.

**Comment by tmm1** [comment]
Okay then what if the bottle contains both versions? The libs were explicitly designed by the rocksdb team to live side by side.

rocksdb is more than four years old and there are bindings available for every single programming language. Many of these are not compatible with rocksdb_lite, which is only a few months old.

Further rocksdb_lite was designed primarily for mobile applications. It is missing feature one expects would be included when installing a package named rocksdb: https://github.com/facebook/rocksdb/blob/master/ROCKSDB_LITE.md

**Comment by ilovezfs** [comment]
Would be happy to look at a PR for that.
