### ISSUE TITLE
Apple M1 gcc-11 compiled bad executable

### ISSUE THREAD

**Issue by victor-tsang** [Homebrew/homebrew-core#96230]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
% brew gist-logs gcc   
Error: No logs.


% brew config
HOMEBREW_VERSION: 3.4.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ffc76654da12fba7d34d078fd9bf681fef65921e
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8f842bd99d41bd92c3947882ffc89d9bf7d787a2
Core tap last commit: 13 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-arm64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
Rosetta 2: false



 % brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ilmbase
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I compile a test C++ file to test g++-11, the code should raise a std::bad_any_cast exception but the program catch SIGBUS signal instead.

test code:
```
// To build:
// g++-11 -std=c++17 -o any_cast any_cast.cpp
//
//

#include<iostream>
#include<any>




int main()
{
    std::cout<<"Test GCC std::any_cast."<<std::endl;
  
    std::any a1="123.456";
  
    try
    {
      std::cout<<"  std::any_cast<double>(a1) = "<<std::any_cast<double>(a1)<<std::endl;
    }
    catch(std::exception const &e)
    {
      std::cout<<"  std::any_cast<double>(a1) generate exception: "<<e.what()<<std::endl;
    }
    catch(...)
    {
      std::cout<<"  std::any_cast<double>(a1) generate exception!"<<std::endl;
    }
  
    
  
  return 0;
}

```

### What happened (include all command output)?

compile the code in terminal ` g++-11 -std=c++17 -o any_cast any_cast.cpp ` and run it. Expect the code show some  messages but the program catch a bus error signal and terminated unexpectedly.

```
 % ./any_cast      
Test GCC std::any_cast.
zsh: bus error  ./any_cast
```

### What did you expect to happen?

The compiled program expected to some some messages like
```
Test GCC std::any_cast.
  std::any_cast<double>(a1) =   std::any_cast<double>(a1) generate exception: bad any cast
```

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Step 1: in Apple M1 platform, install gcc `brew install gcc`

Step 2: save the c++ below as any_cast.cpp


// To build:
// g++-11 -std=c++17 -o any_cast any_cast.cpp
//
//

#include<iostream>
#include<any>




int main()
{
    std::cout<<"Test GCC std::any_cast."<<std::endl;
  
    std::any a1="123.456";
  
    try
    {
      std::cout<<"  std::any_cast<double>(a1) = "<<std::any_cast<double>(a1)<<std::endl;
    }
    catch(std::exception const &e)
    {
      std::cout<<"  std::any_cast<double>(a1) generate exception: "<<e.what()<<std::endl;
    }
    catch(...)
    {
      std::cout<<"  std::any_cast<double>(a1) generate exception!"<<std::endl;
    }
  
    
  
  return 0;
}

```

Step 3: compile the code

```
g++-11 -std=c++17 -o any_cast any_cast.cpp
```

Step 4: run ` ./any_cast `

Step 5: check the program will get a bus error signal and terminated.
```

**Comment by gromgit** [comment]
GCC on M1 is still a work in progress:
> The code for now is hosted via [gcc-darwin-arm64 on GitHub](https://github.com/iains/gcc-darwin-arm64) but the developers are hoping this code will be ready for landing in time for GCC 12 with its stable (GCC 12.1) release next year [2022]. ([source](https://www.phoronix.com/scan.php?page=news_item&px=GCC-12-Apple-M1-Port-Plan))

If you need it right now, you could try building it from source from the GitHub repo.

**Comment by fxcoudert** [comment]
I've filed the issue against the upstream GCC branch for ARM: https://github.com/iains/gcc-darwin-arm64/issues/83

**Comment by fxcoudert** [comment]
So it's a known issue, it's fixed in the latest ARM branch, and will therefore be fixed when we update (mostly likely when GCC 12 is released, in April).
