### ISSUE TITLE
john-jumbo: GCC <= 10 fails with duplicate symbol (-fno-common)

### ISSUE THREAD

**Issue by jdloft** [Homebrew/homebrew-core#96448]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/jdloft/7463819267740e2e7aca9506db54a8e8
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Build `john-jumbo` with OpenMP support with llvm_clang or gcc-11.

### What happened (include all command output)?

GCC/LLVM clang fails with "duplicate symbol"

```
Last 15 lines from /Users/jamison/Library/Logs/Homebrew/john-jumbo/03.make:
    opencl_agilekeychain_fmt_plug.o
    opencl_sspr_fmt_plug.o
duplicate symbol '_psalt' in:
    truecrypt_fmt_plug.o
    opencl_tc_fmt_plug.o
duplicate symbol '_keyfiles_length' in:
    truecrypt_fmt_plug.o
    opencl_tc_fmt_plug.o
duplicate symbol '_keyfiles_data' in:
    truecrypt_fmt_plug.o
    opencl_tc_fmt_plug.o
ld: 50 duplicate symbols for architecture arm64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../run/john] Error 1
make: *** [default] Error 2
```

### What did you expect to happen?

Homebrew should set the `-fcommon` option in `CFLAGS` for compiling `john-jumbo` to ignore duplicate symbols with gcc-10 and later.

GCC-10 changes: https://gcc.gnu.org/gcc-10/changes.html#c specifically:
"GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking."

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. brew install --cc gcc-11 -s john-jumbo or brew install --cc llvm_clang -s john-jumbo
```

**Comment by carlocab** [comment]
```
Warning: You passed `--cc=llvm_clang`.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```
