### ISSUE TITLE
The tarball for `lmdb` does not exist

### ISSUE THREAD

**Issue by chdiza** [Homebrew/homebrew-core#9647]
The tarball for `lmdb` 404's; it's not on the github releases page.

Just a heads up.  I don't know where it actually lives.

**Comment by maveonair** [comment]
@ilovezfs Do you have an idea why the version 0.9.20 is not available anymore on the GitHub release page of LMDB? 

- Last formula PR to 0.9.20: https://github.com/Homebrew/homebrew-core/pull/8762
- LMDB Mirror: https://github.com/LMDB/lmdb

**Comment by ilovezfs** [comment]
It was withdrawn by upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1412404#c6

We should downgrade.
