### ISSUE TITLE
[new formula] kilo

### ISSUE THREAD

**Issue by 0fiscalentropy** [Homebrew/homebrew-core#9648]
`kilo` is a very small editor; [GitHub page.](https://github.com/antirez/kilo)

**Comment by MikeMcQuaid** [comment]
We don't really do formulae requests. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
