### ISSUE TITLE
Audit fails: ddrutility

### ISSUE THREAD

**Issue by chrisfinazzo** [Homebrew/homebrew-core#9651]
# Please follow the general troubleshooting steps first:

- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Formula Requests:

I am working on a PR for ddrutility - a companion to ddrescue. When I run `brew audit`, I get the following error: 

```
    $ brew audit --new-formula ddrutility
    ddrutility:
    * Stable: Use https://downloads.sourceforge.net to get geolocation (url is https://sourceforge.net/projects/ddrutility/files/ddrutility-2.8.tar.gz).
```

It seems like [this][] is a known issue with SourceForge URLs - Tl;dr they're wonky and Homebrew "fixes" them. What is the recommended solution here? I would prefer not to have to use `:latest` if it's not necessary.

[this]: http://librelist.com/browser/homebrew/2011/1/12/prdownloads-is-bad/#d1e410bd63857c01be939a098113d2c2

**Comment by MikeMcQuaid** [comment]
Homebrew doesn't fix them but `curl`will follow relocations for you. You'll just need to fix it up manually.
