### ISSUE TITLE
spdlog is packaged in such a way that including <spdlog/spdlog.h> gives a macro redefinition warning of the macro SPDLOG_FMT_EXTERNAL

### ISSUE THREAD

**Issue by mortie** [Homebrew/homebrew-core#96856]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Error: No logs.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was using the spdlog package in a program.

### What happened (include all command output)?

The pkgconfig file for spdlog specifies a cflags field which contains -DSPDLOG_FMT_EXTERNAL. The file spdlog/1.9.2/include/spdlog/tweakme.h (included by the main spdlog.h) also contains #define SPDLOG_FMT_EXTERNAL (not guarded by an #ifdef). So if you install the brew package for spdlog, then #include <spdlog/spdlog.h>, and compile the file using the flags suggested by pkg-config, the compiler complains that SPDLOG_FMT_EXTERNAL is being redefined.

```
$ cat test.cc
#include <spdlog/spdlog.h>

$ clang -c $(pkg-config --cflags spdlog) test.cc
In file included from test.cc:1:
In file included from /opt/homebrew/Cellar/spdlog/1.9.2/include/spdlog/spdlog.h:12:
In file included from /opt/homebrew/Cellar/spdlog/1.9.2/include/spdlog/common.h:6:
/opt/homebrew/Cellar/spdlog/1.9.2/include/spdlog/tweakme.h:74:9: warning: 'SPDLOG_FMT_EXTERNAL' macro r
edefined [-Wmacro-redefined]
#define SPDLOG_FMT_EXTERNAL
        ^
<command line>:3:9: note: previous definition is here
#define SPDLOG_FMT_EXTERNAL 1
        ^
1 warning generated.
```

### What did you expect to happen?

I expected to be able to compile the source file without warnings with the compilation options suggested by the package's pkgconfig file.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew install spdlog
$ echo '#include <spdlog/spdlog.h>' > test.cc
$ clang++ -std=c++17 -c $(pkg-config --cflags spdlog) test.cc
In file included from test.cc:1:
In file included from /opt/homebrew/Cellar/spdlog/1.9.2/include/spdlog/spdlog.h:12:
In file included from /opt/homebrew/Cellar/spdlog/1.9.2/include/spdlog/common.h:6:
/opt/homebrew/Cellar/spdlog/1.9.2/include/spdlog/tweakme.h:74:9: warning: 'SPDLOG_FMT_EXTERNAL' macro redefined [-Wmacro-redefined]
#define SPDLOG_FMT_EXTERNAL
        ^
<command line>:3:9: note: previous definition is here
#define SPDLOG_FMT_EXTERNAL 1
        ^
1 warning generated.
```

**Comment by mortie** [comment]
This is a duplicate of https://github.com/Homebrew/homebrew-core/issues/88896. I'm posting it again because that issue was closed as outdated, when the issue is very much still relevant and I just encountered it again today.

**Comment by carlocab** [comment]
Sorry, but we don't keep stale issues open  unless someone is actively working on them. Given what happened with the previous issue, it seems unlikely that anyone is.

As mentioned in #88896, we'll review a pull request to fix this, but any further discussion of this problem doesn't need to happen in an open issue.

**Comment by mortie** [comment]
I was actually thinking about trying to make a PR, I made an issue upstream to try to figure out how to best solve it: https://github.com/gabime/spdlog/issues/2310

If the original issue was just closed as stale, that would be one thing, but it's locked, so no further discussion can take place on it from outsiders even though it's still an ongoing problem. That seems unfortunate.

**Comment by carlocab** [comment]
> I was actually thinking about trying to make a PR, I made an issue upstream to try to figure out how to best solve it: https://github.com/gabime/spdlog/issues/2310

That's good to hear. I'm happy to reopen in light of this.

**Comment by Bo98** [comment]
The answer is really both - `-DSPDLOG_FMT_EXTERNAL` is used in CMake to control whether a bundle fmt is compiled or searched for.

IMO the best action upstream would be to instead, when a CMake build is invoked, make tweakme.h be replaced by an auto-generated file via `#cmakedefine` and then stop placing the flag in the generated pkg-config file.

`#ifndef` is an alternative solution, but also annoying to uncomment via `inreplace`.
