### ISSUE TITLE
szip formula should be removed

### ISSUE THREAD

**Issue by Bo98** [Homebrew/homebrew-core#96930]
The szip has a license that appears to not be fully open source: https://support.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html.

There is now an open-source replacement however: libaec. We already ship it so we should migrate away form szip as soon as possible.

---

Progress:
- [x] The two formulae have `conflicts_with` so we should probably think about handling that before any migration or users will get errors on upgrading. - #96933
- [x] Migrating dependents:
    - [x] hdf5@1.10 - #96928
    - [x] hdf5@1.8 - #96942
    - [x] hdf5 / hdf5-mpi - #97666
      - alembic
      - alpscore
      - armadillo
      - caffe
      - cdo
      - cgns
      - vtk
      - vtk@8.2
- [x] Remove `szip` - #98261

**Comment by cho-m** [comment]
I did see this when looking into `hdf5`.

I had opened #96928 relating to migrating `hdf5@1.10` from `szip` to `libaec`, but can wait for fixing `conflicts_with` first.

I just opened #96933 to switch `conflicts_with` to `keg_only`.

**Comment by cho-m** [comment]
At this point, only need to migrate `hdf` formula and dependents in single PR before disabling `szip`.

However, we probably should decide if `hdf` should be downgraded to `1.12.1` beforehand or same PR, and the best procedure to do this. There are a number of dependents revision bumped so manually reverting files may break. Not sure if best option is to downgrade via `version_scheme`.
