### ISSUE TITLE
brew install switches HEAD to master; can't install from old commit

### ISSUE THREAD

**Issue by jasonkarns** [Homebrew/homebrew-core#9694]
I need to install postgres93, which exists in the `versions` tap, but was removed on Nov 17th.

I jumped into the versions tap and checked out the commit prior to its deletion and attempted `brew install postgres93` (which tab-completed because it was available at the current HEAD). However, `brew install` force-updates the tap to latest master _prior_ to running the install, at which point the formula doesn't exist (naturally).

So I checked out the desired commit again in the tap, and this time ran `brew install ./postgresql93.rb`; hoping that brew wouldn't change the tap's HEAD if given a direct formula path. No luck; it force-updated to latest master again.

So I guess this is a feature request. I would expect some kind of flag or something that allows one to  do a brew install without it switching HEADs in any taps. This way, one could install old versions even after they've been removed from the tap.

**Comment by MikeMcQuaid** [comment]
> This way, one could install old versions even after they've been removed from the tap.

We don't really want to support this use-case. The best bet is to copy them to your own tap instead.
