### ISSUE TITLE
PLPLOT 12.0 failed to build on MAC OS 10.12.3

### ISSUE THREAD

**Issue by movahle** [Homebrew/homebrew-core#9698]
camke fails examination shows that

Line 233 of pkg-config.cmake in "plplot/12.0/cmake/modules" needs quotes "" around {$link_flags}
======================================================================
macbookpro:~ vahle$ brew gist-logs plplot
https://gist.github.com/7d404af4666f6f02e6bd56c8a00401a2

macbookpro:~ vahle$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Broken symlinks were found. Remove them with `brew prune`:
  /usr/local/bin/scan
  /usr/local/share/man/man1/scan.1

**Comment by tschoonj** [comment]
Could you please open an upstream ticket for this bug at https://sourceforge.net/p/plplot/bugs/?

Also, if you have a patch for it, please update the formula and open a PR.

Thanks!

**Comment by movahle** [comment]
I opened a ticket.  I know how to fix the problem,  but don’t know how to update formula and open a PR.

Mike

**Comment by tschoonj** [comment]
Thanks for opening the bug report on source forge!

Please read the [docs](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md) if you want to update a formula.

Don't worry about it: we will guide you through the process every step of the way. 😄

**Comment by MikeMcQuaid** [comment]
Closing as an upstream issue.

**Comment by movahle** [comment]
Tom, Mike

Does this mean that the code has been (or will be) fixed?

Mike

**Comment by tschoonj** [comment]
No, you will need to open a pull request for this, according the instructions I mentioned before.

**Comment by movahle** [comment]
Tom,
I read the documentation you sent a reference to, but still don’t know where to start. There are no examples and the terminology assumes makes the process opaque.

Perhaps you can guide me. All I really need to do is to make a one line edit to the file "/cmake/modules/pkg-config.cmake” in the plplot 5.12.0 distribution. Maybe an outline with the associated brew steps detailed would be helpful. 

It seems at a high level what I need to do is: 1.get the source code, 2. make the change, 3. and then resubmit. But translation that into forks, pull requests, etc. isn’t obvious.

Sorry, but if I’m going to be of any help, I’m going to need some hand holding.

Mike
