### ISSUE TITLE
Stop requiring Xcode command line tools to install Python3

### ISSUE THREAD

**Issue by Jean-Daniel** [Homebrew/homebrew-core#97083]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.4.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: fed93bb934b4a5d10b68865795970a993de31b14
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b1a04cc22ee12ada2b7fb564a215ab8a6c30f9e8
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.F1RUkg7fvN/org.xquartz:0
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 13.0.0 build 1300
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.6.4-x86_64
CLT: N/A
Xcode: 13.2.1
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want that Python3 stop asking me to install Xcode command line tools as it apparently do not require them to be installed in the first place.

### What happened (include all command output)?

brew install python@3.9
Error: python@3.9: the bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

### What did you expect to happen?

That brew install python@3.9 just install python without asking to install Xcode CLI as Xcode is already present and can be used to build python and its dependencies.

I did update the formula locally to remove the check, and didn't have trouble while installing and using it, so it obviously doesn't require Xcode CLI to be present to properly build and install.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install python@3.9
```

**Comment by carlocab** [comment]
The CLT is not needed to install Python. It is, however, required in order to use it, because Python hardcodes the path to the CLT. Having only the Xcode app without the CLT will lead to an install that's subtly broken, so we won't be removing the requirement.

**Comment by Jean-Daniel** [comment]
Out of curiosity, which part of python is using an hardcoded path to `/Library/Developer/…/`.
I'm using python extensively for years without Xcode CLT installed and never encounter any issue.

They may have hardcode path to /usr/bin/* but these binaries work perfectly with Xcode installed and not the Xcode CLT.

**Comment by carlocab** [comment]
Python remembers the `CFLAGS` and `LDFLAGS` used during the build, and those will contain a reference to the CLT here:

https://github.com/Homebrew/homebrew-core/blob/6f92487ea4d5f4f580c85141bdf563f7fe567dbe/Formula/python%403.10.rb#L145-L150
