### ISSUE TITLE
nzbget: nzbget.conf has incorrect settings for best OS X performance and compatibility

### ISSUE THREAD

**Issue by strafer** [Homebrew/homebrew-core#972]
The Homebrew version of nzbget has DirectWrite **enabled** and ArticleCache **disabled** in the sample nzbget.conf file that is provided. For best performance under OS X, those settings should be reversed: DirectWrite should be **disabled** and ArticleCache **enabled** (and set to some number between 700 and 1000). The official standalone version for OS X has these correct settings.

The sample nzbget.conf file (/usr/local/Cellar/nzbget/16.4/share/nzbget/nzbget.conf) that is installed by "brew install nzbget" has, on line 777, "DirectWrite=yes". This should actually be "DirectWrite=no" by default for OS X users, as it is in the nzbget file that comes with the official standalone version of nzbget for OS X. Similarly, on line 748 of nzbget.conf, "ArticleCache=0". It should be set to "700" or anything up to "1000" as per the wiki (https://github.com/nzbget/nzbget/wiki/Performance-tips#article-cache): "If DirectWrite is disabled the article cache should be big enough to accommodate any whole rar-file (up to 1 GB)."

According to the nzbget wiki (https://github.com/nzbget/nzbget/wiki/Performance-tips#article-cache) and config file, "The direct write relies on the ability of file system to create empty files without allocating the space on the drive (sparse files), which most modern file systems support including EXT3, EXT4 and NTFS. _**The notable exception is HFS+ (default file system on OSX).**_""If the direct write can not be used due to lack of sparse files support a large article cache must be configured for best performance."

And from the nzbget forum (http://forum.nzbget.net/viewtopic.php?f=3&t=2517&p=16468#p16468):

"DirectWrite on HFS+ file system doubles the amount of disk write operations compared to disabled DirectWrite with active article cache. It's for you to choose RAM overhead vs disk overhead.

The official OS X version of nzbget from nzbget download page is configured with recommended settings. The issues of Homebrew version should be reported to Homebrew maintainers."

**Comment by apjanke** [comment]
Thanks! We appreciate detailed bug reports like this, especially for Mac-specific config and tuning settings that the maintainers not be familiar with. We're pretty high volume so it may take us a few days to get to this, but we'll look in to it and make the appropriate adjustments.

Thanks for including the reference links; that makes it a lot easier to research and evaluate this stuff.

**Comment by ilovezfs** [comment]
It would be nice if upstream would just check `getattrlist` for `VOL_CAP_FMT_SPARSE_FILES` and make the right decision on its own, since, after all, ZFS does support sparse files and OS X does have a mechanism for checking for this capability, but I digress.

**Comment by apjanke** [comment]
Oh, huh, someone around here's a ZFS fan; who would'a guessed it was you?

;)

**Comment by ilovezfs** [comment]
I know, shocking, right? I'm also a fan of `GETATTRLIST(2)` `man getattrlist` which is one of the under-used gems of OS X.

**Comment by mikemcquaid** [comment]
Great issue here. Could you try and open a pull request (it'd be amazing if possible)? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by strafer** [comment]
Do I need to open a pull request since I opened the issue?

**Comment by mikemcquaid** [comment]
@strafer You don't have to but it'd be great if you could; it'd definitely be the quickest way.

**Comment by strafer** [comment]
Okay, from the link you provided, do I select "formulae-related-pull-request"? If so, I should paste the following commands into the Terminal on the computer that has Homebrew installed?

cd $(brew --repository homebrew/core)

git remote add strafer

https://github.com/strafer/homebrew-core.git

Is this correct?

**Comment by apjanke** [comment]
Pretty much.

```
`cd $(brew --repository homebrew/core)`
`git remote add strafer https://github.com/strafer/homebrew-core.git`
```

Then create a branch there for your work, and submit it as a PR back on this repo when it's ready.

**Comment by strafer** [comment]
I'm not a programmer so I don't know what work I would be contributing to a branch.

And how do I create a branch? With this?
`git checkout -b <YOUR_BRANCH_NAME>`

And any suggestions for a suitable branch name?

**Comment by mikemcquaid** [comment]
@strafer Yep, that's how. Any branch name except `master` will do; a suitable one might be `nzbget-settings`

**Comment by strafer** [comment]
I created the branch with the name "nzbget-settings. I then tried to push the branch to github with 
`git push origin nzbget-settings` but it failed with the following error:

> remote: Permission to Homebrew/homebrew-core.git denied to strafer.
fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': The requested URL returned error: 

> 403

**Comment by martinlschumann** [comment]
You have to do 
`git push strafer`

Origin is this repository, where you don't have write access
Github sees the branch: [https://github.com/strafer/homebrew-core/branches](link)

**Comment by strafer** [comment]
Thanks. I hope this will be my last question. 

I tried to do a pull request but got this message:
"There isn’t anything to compare.
Homebrew:master is up to date with all commits from strafer:nzbget-settings. Try switching the base for your comparison."

So I switched the base to strafer/homebrew-core/nzbget-settings and it'll allowed me to create a pull request: https://github.com/strafer/homebrew-core/pull/1

I hope that is the correct location for it. If not, please let me know what I need to change.

**Comment by martinlschumann** [comment]
You didn't push any changes to the server yet, that is why you are getting the message. The direction is the wrong way. The pull request you opened is homebrew-core -> strafer , it should be strafer -> homebrew-core.

Did you actually commit anything with `git commit` ?
What do `git status` and `git branch` say?

**Comment by strafer** [comment]
In branch _nzbget-settings_, `git status` yields "nothing to commit, working directory clean". `git commit` also yields the same message.

As for `git add`, what am I supposed to add? Do I need to edit the nzbget.conf file with my suggested settings? If so, how do I actually go about doing that with "git add"? Can I just edit a copy of the config with a text editor and then submit it with "git add /path/to/nzbget.conf"? Other than the bug report I filed above, I have nothing further to contribute since I'm not a programmer and I don't have any coding skills. 

This is why I'm confused. I don't understand why I'm doing any of this other than I was asked to. I originally posted a bug report because I noticed that the default nzbget.conf that is installed by the nzbget Homebrew formula has certain options set incorrectly for OS X. I was then asked to create a "pull request." I still have no idea why I needed to do this rather than a Homebrew maintainer. And while I'm quite technically adept with many things, I find git (and github) anything but intuitive or easy to understand, and all the documentation out there assumes the reader has a coding background and understands how to use a version control system. So, it's a slow, frustrating, and humbling learning process for me.

Now, if the person who files a bug report is also supposed to file a pull request, then I'm more than willing to attempt this (as I have been trying all along). At the same time, I hopefully learn how to use git/github and to contribute to Homebrew. However, I'm not a programmer so I have no clue what I'm actually supposed to submit along with the pull request.

**Comment by martinlschumann** [comment]
Created a commit which fixes the problem: martinlschumann@7372f14 
If it's ok with you, I can also do the pull request.

**Comment by mikemcquaid** [comment]
> If it's ok with you, I can also do the pull request, or I can walk you through how to do the changes yourself

That would be great, thanks!

**Comment by DomT4** [comment]
Any update here?

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by ilovezfs** [comment]
@strafer @martinlschumann This is now fixed in https://github.com/Homebrew/homebrew-core/commit/ed93cb3504833b4e34b140bef3acef0d7945c46d.
