### ISSUE TITLE
openshift-cli.rb is old

### ISSUE THREAD

**Issue by georgettica** [Homebrew/homebrew-core#97389]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I know the latest openshift version is 4.10.x but the binary we have is 4.6.x at the most

### What happened (include all command output)?

N/A

### What did you expect to happen?

that a 4.10.x version of openshift-cli will exist

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
N/A
```

**Comment by Bo98** [comment]
I see there's git branches, but there doesn't appear to be any proper git tags for newer versions: https://github.com/openshift/oc/tags

**Comment by georgettica** [comment]
if I was to suggest a different version of building that would give 4.10.x, would you be open to merging it? @Bo98 ?

**Comment by SMillerDev** [comment]
Only if there are stable versions.

**Comment by Bo98** [comment]
Potentially, can you elaborate what you propose doing?

**Comment by georgettica** [comment]
the versions are stable.

the reason for my caginess is that I didn't ask the maintainer for permission to post here but wanted to get your opinions aswell. if this won't be viable because of reasons I will retract the issue

I am glad though it's not a complete NO :)

**Comment by Bo98** [comment]
As long as it is:

* built from source
* is fetchable from a fixed source that doesn't suddenly change (so either a git tag/commit or a tarball with a fixed sha256)

then it's fine.

**Comment by cho-m** [comment]
Some references.

Upstream issue openshift/oc#954 asking for tags, but no response. There are also other issues with support for 3rd-party builds like openshift/oc#774, which hasn't got much traction.

A previous attempt which was rejected as it did not meet Homebrew's requirements: #90407

**Comment by carlocab** [comment]
It seems to me that third-party builds of `openshift-cli` are just broken and upstream aren't interested in fixing them.

If that is indeed the case I think we should consider disabling this formula. We can enable it again if/when it gets fixed.

**Comment by cho-m** [comment]
In terms of getting newer releases' source code, I do see that upstream includes commit within changelog for official builds (`cli, cli-artifacts, deployer, tools`), e.g.
- **stable (4.10.3)**
   - URL: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/changelog.html
   - Commit: https://github.com/openshift/oc/commit/f93da179fe606775f8249fed96e0b9903d9188ed
- **latest (4.10.5)**
   - URL: https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/changelog.html
   - Commit: https://github.com/openshift/oc/commit/6db43e22ecffd58dbd1cfb3b245967bde98f9a66

---

However, this will still need someone to test the build to check for proper functionality in regards to #66476 / https://github.com/openshift/oc/issues/774 

If the resulting binaries are still broken, then the formula should either be disabled or will need someone to contribute a fix.

**Comment by georgettica** [comment]
This is a viable solution, though not explicitly related to my solution

I have some code that does this inside a docker container (not via a formula)

**Comment by georgettica** [comment]
after discussion with @cblecker , I got permission to share..
so the formula is https://github.com/cblecker/homebrew-tap/blob/master/Formula/openshift-cli.rb and it's being maintained by him for a while now.

the SHA's are per release and it's fairly stable across the team.
feel free to browse and let me know if I can import it instead of the current formula in one way or another

**Comment by SMillerDev** [comment]
So if I understand it correctly the only way to know the commit hash is installing the new version and making it print the commit hash?

**Comment by georgettica** [comment]
I think this is the way it works as of now :/

**Comment by georgettica** [comment]
It's more of a verification test to make sure we got what we wanted

**Comment by MikeMcQuaid** [comment]
> The problem of using `oc` is that a Homebrew maintainer will need to have it installed to approve PR.

This is not tenable, really.

> The real problem is that this fails Homebrew's `brew audit --strict` since we don't allow untagged Git URL as stable releases.

Yeh, we're not interested in packaging upstream software that doesn't want to make tagged releases. Sounds like this should be disabled and punted to a tap until upstream can be convinced to make tags.

**Comment by georgettica** [comment]
What about the mirror openshift?
We can still use the xhecksum code from there but pull the image from somewhere else?

**Comment by MikeMcQuaid** [comment]
We need the upstream project to provide these tags, not a mirror.

**Comment by georgettica** [comment]
So yeah, link to the other git repo.

I really wanted this to be solved upstream but I see your concerns

**Comment by cho-m** [comment]
As side note, for macOS users, the Cask https://formulae.brew.sh/cask/openshift-client was added to install official pre-built binaries.

Given the responses here and in other PRs/issues, as long as upstream is not interested in tagging releases for 3rd-party installations, it is best to just move `openshift-cli` Formula to the deprecate/disable/remove workflow.

Instead, users can either install via Cask or install via externally-maintained taps.

**Comment by cho-m** [comment]
Closing as `openshift-cli` formula is now deprecated and should be disabled/removed in a year or so. I added link to Cask Homebrew currently maintains.

Note that Homebrew does not allow adding references to 3rd-party taps in Formula (only in Docs https://docs.brew.sh/Interesting-Taps-and-Forks#unsupported-interesting-taps), so there will be no link to previously mentioned tap or any other external tap.

**Comment by georgettica** [comment]
can we re-enable this?
got the upstream to have tags

and I hope this will be a part of the promotion process.
let me know if you need anything else from me on this

**Comment by carlocab** [comment]
Sure, feel free to open a PR.

**Comment by georgettica** [comment]
https://github.com/Homebrew/homebrew-core/pull/98541 XD
