### ISSUE TITLE
Graphviz.app: missing link to folder /Applications

### ISSUE THREAD

**Issue by rudi48** [Homebrew/homebrew-core#9742]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
OS: Sierra 10.12.3
I installed Graphviz 2.40.1 sucessfully with (Xcode is installed):
$ brew install graphviz --with-app

Unfortunately no link to the folder /Applications was setup.
I made this with:
$ ln -s /usr/local/Cellar/graphviz/2.40.1/Graphviz.app /Applications/Graphviz.app

### Formula Requests:

**Please note by far the quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md).**

If the option "--with-app" is set, a link to the folder /Applications should be set by the formular.

**Comment by ilovezfs** [comment]
`brew linkapps` is being deprecated, but that's what you're looking for.

**Comment by rudi48** [comment]
@ilovezfs 
Thank you for the quick answer.
I am not the best programmer, so I have one questions:
Is there a better way, than why I did?
Regards, Rudolf

**Comment by ilovezfs** [comment]
@rudi48 no not really. If you run `brew linkapps` that basically does what you did manually for you.

**Comment by rudi48** [comment]
@ilovezfs 
Thank you :-)
Regards, Rudolf
