### ISSUE TITLE
librsvg url is fixed to 2.52

### ISSUE THREAD

**Issue by joh-klein** [Homebrew/homebrew-core#97457]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Looks like 2.54.0 of librsvg was released, but the download url of the formula is fixed to 2.52 – is that by design?

### What happened (include all command output)?

N/A

### What did you expect to happen?

formula can be bumped to new version

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew bump-formula-pr librsvg --version 2.54.0
```

**Comment by SMillerDev** [comment]
It's not fixed to anything, that's just how gnome.org urls are structured. You'll find that everything will work fine if you pass the URL to `brew bump-formula-pr`

**Comment by joh-klein** [comment]
Oh, didn't realize I could pass the url as well – thanks! I just saw, that there is also a 2.52.8 release next to the 2.54.0 … which should I "bump" to?

**Comment by SMillerDev** [comment]
As a policy, the latest. But it might be easier to do  `.8` first since I expect less issues with that one. Then after you can open the bigger PR.

---
Closing since it's resolved
