### ISSUE TITLE
Adjust permissions accordingly how? 

### ISSUE THREAD

**Issue by hpoit** [Homebrew/homebrew-core#9752]
@jacknagel, I quote you "(a) don't use sudo; adjust the permissions on directories in /usr/local accordingly. This is the recommended way to use Homebrew."

Accordingly how? I'm sorry. I am trying to install Cairo, Poppler, and pdf2svg.

**Comment by MikeMcQuaid** [comment]
`@jacknagel` is no longer a Homebrew maintainer. Run the Homebrew installer and file issues you have with your `brew config` and `brew doctor` output on specific formulae if and when you have them.
