### ISSUE TITLE
`pecl` fails by default in the `php` formula

### ISSUE THREAD

**Issue by NightMachinary** [Homebrew/homebrew-core#97962]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

The issue https://github.com/Homebrew/homebrew-core/issues/41081 was closed without solving it. It also seems easy to solve; there is a missing `mkdir -p /usr/local/lib/php/pecl` in the installation formula of `php`.

### What happened (include all command output)?

.

### What did you expect to happen?

.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
.
```

**Comment by SMillerDev** [comment]
> The issue https://github.com/Homebrew/homebrew-core/issues/41081 was closed without solving it. It also seems easy to solve; there is a missing mkdir -p /usr/local/lib/php/pecl in the installation formula of php.

You're welcome to pick it up

**Comment by NightMachinary** [comment]
@SMillerDev Well, I know the shell command to fix this is `mkdir -p "$(pecl config-get ext_dir)"`. Should I add
```
shell_output('mkdir -p "$(pecl config-get ext_dir)"')
```
to https://github.com/Homebrew/homebrew-core/blob/4be82b173dc4da5c611bb08127c1fbcffd948671/Formula/php.rb#L240 ? I don't really know much Ruby or Homebrew.

**Comment by SMillerDev** [comment]
This should do it
```
mkdir_p shell_output("#{bin}/pecl config-get ext_dir")
```
