### ISSUE TITLE
llvm@3.7 and llvm@3.8 don't work with OpenMP.

### ISSUE THREAD

**Issue by equal-l2** [Homebrew/homebrew-core#9806]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:
`llvm@3.7` and `llvm@3.8` don't work with OpenMP.

Even an example below won't compile.
(Tried Compiling with `clang-3.7 -fopenmp` and `clang-3.8 -fopenmp`, to get an error claiming `'omp.h' file not found`.)
```c
#include <omp.h>
#include <stdio.h>
#include <stdlib.h>

int main (int argc, char *argv[])
{
int nthreads, tid;

/* Fork a team of threads giving them their own copies of variables */
#pragma omp parallel private(nthreads, tid)
  {

  /* Obtain thread number */
  tid = omp_get_thread_num();
  printf("Hello World from thread = %d\n", tid);

  /* Only master thread does this */
  if (tid == 0)
    {
    nthreads = omp_get_num_threads();
    printf("Number of threads = %d\n", nthreads);
    }

  }  /* All threads join master thread and disband */

}
```

`brew config`

```
HOMEBREW_VERSION: 1.1.9-54-g9aa4888d2
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 9aa4888d2b45c7a07a95183cc4c026d828391914
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e420e60034518c8f2b16943a1678344808cfc054
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112, 1.7.0_71
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

**Comment by aw1621107** [comment]
Hmmm... What was your header search path and/or `-I` flags?

**Comment by equal-l2** [comment]
@aw1621107 
I didn't set any `-I` flags.

See below for header search path.

`clang-3.7`
```
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/Cellar/llvm@3.7/3.7.1/lib/llvm-3.7/bin/../lib/clang/3.7.1/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

`clang-3.8`
```
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /usr/local/Cellar/llvm@3.8/3.8.1/lib/llvm-3.8/bin/../lib/clang/3.8.1/include
 /usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
```

**Comment by aw1621107** [comment]
Unfortunately, I don't have those particular versions installed, but the second path looks odd. It should resolve to

    /usr/local/Cellar/llvm@3.8/3.8.1/lib/llvm-3.8/lib/clang/3.8.1/include

While `omp.h` is in:

    /usr/local/Cellar/llvm/3.9.1/lib/clang/3.9.1/include

on my machine. Can you check to see if the path is correct? I'm getting 3.7/3.8 installed, but it'll be a while until compilation finishes.

**Comment by equal-l2** [comment]
`llvm@3.7` and `llvm@3.8` seems not to have `omp.h` in any location.
I've run `find . -follow -iname omp.h` in my Cellar and any `omp.h` in `llvm@3.7` and `llvm@3.8` folder.

**Comment by aw1621107** [comment]
Huh, interesting. Really not sure what's going on then. Sorry for the inability to help.

**Comment by MikeMcQuaid** [comment]
We don't support versioned formulae to the same extent. If you need this functionality, please create a pull request. Sorry!
