### ISSUE TITLE
cleanup fails on old root installs

### ISSUE THREAD

**Issue by grosch** [Homebrew/homebrew-core#9842]
### Bug reports:

`brew cleanup` fails to run as root.  I originally used brew as root long ago.  Now, it no longer runs as root.  So I have no way to cleanup since it has to run as root.

My obvious workaround was to sudo and chown all those files to me, but I think `brew cleanup` should be allowed to run via sudo if desired.

% brew config
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 741286bec27a4852523769bffc15eeee2e9cb76b
Core tap last commit: 15 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 12-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.4.0/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11

% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  php70

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl https://github.com

**Comment by MikeMcQuaid** [comment]
Sorry, this is intentional.

**Comment by grosch** [comment]
Could you explain why?  I understand why you made the change for installing, but why can't a cleanup run this way?

**Comment by MikeMcQuaid** [comment]
We don't wish to allow this command to run as root for security reasons as it reads formulae which involves running arbitrary, sometimes untrusted Ruby code.
