### ISSUE TITLE
gtk+3 on Catalina X86_64: can not correctly `include gdk/quartz/gdkquartz-cocoa-access.h`

### ISSUE THREAD

**Issue by dabrain34** [Homebrew/homebrew-core#98470]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
HOMEBREW_VERSION: 3.4.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5f5af43244eaece1f09d695603e1a261676713a0
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: b77e01e9955bb492d308f535d0d5a15ac4812dfa
Core tap last commit: 40 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.rjhTUDYDaq/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit ivybridge
Clang: 12.0.0 build 1200
Git: 2.24.3 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.32.29
Xcode: 12.4

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!


Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  ext4fuse
  ilmbase
  py2cairo
  szip
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I'm trying to build GStreamer from the devenv envtionment with meson/ninja

The gtk example is failing on MacOS, so I created the following merge request to fix it which was working on monterey/ARM but not on Catalina/X86

https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/2095/diffs?diff_id=811844&start_sha=aced16b239ccec97083ecf30552151591fb84d28

Here the errror:

/usr/local/Cellar/gtk+3/3.24.33/include/gtk-3.0/gdk/quartz/gdkquartz-cocoa-access.h:28:10: fatal error: 'gdkquartz.h' file not found

indeed it should be #include <gdk/gdkquartz.h> and not #include "gdkquartz.h" as in monterey 3.24.31

### What happened (include all command output)?

The include is incorrect:

/usr/local/Cellar/gtk+3/3.24.33/include/gtk-3.0/gdk/quartz/gdkquartz-cocoa-access.h:28:10: fatal error: 'gdkquartz.h' file not found

### What did you expect to happen?

The build to finish with #include <gdk/quartz/gdkquartz-cocoa-access.h>

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install gtk+3

git clone https://gitlab.freedesktop.org/gstreamer/gstreamer.git
meson builddir
ninja -C builddir
```

**Comment by SMillerDev** [comment]
I'm having a hard time understanding what the relation is to brew for this issue. Could you clarify that?

**Comment by dabrain34** [comment]
the gtk3+ formula does not install the same files on Catalina as on Monterey.

On Monterey its 3.24.31
 in Catalina its 3.24.33 

The file gdkquartz-cocoa-access.h can not include gdkquartz.h as the pkg-config is not providing the right path.

I dont know why it includes "gtkquartz.h" directly and not <gdk/gdkquartz.h>. Seems to be a bug in gtk

Can we provide 3.24.31 on Catalina too ?

**Comment by SMillerDev** [comment]
Are you sure you have the latest version of the GTK formula on both OSes?

**Comment by dabrain34** [comment]
yes I do

**Comment by Bo98** [comment]
This is being tracked upstream: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4303. Upstream's stance appears to be to recommend not using this header.

**Comment by Bo98** [comment]
Upstream also intentionally made the decision to change the header to not include `gdk/` in the #include: https://gitlab.gnome.org/GNOME/gtk/-/commit/7e732caa1e3dc72630704bc4908e8a165a5934c0.

The current version of the formula entirely matches what upstream have opted to do. There's nothing Homebrew-specific here.

**Comment by Bo98** [comment]
> On Monterey its 3.24.31

We provide the same version: 3.24.33 on _all_ OS versions. You are not running the latest version if you have 3.24.31.

**Comment by dabrain34** [comment]
Ok thanks for your feedback
