### ISSUE TITLE
[Formula Request] simon-r/dr14_t.meter

### ISSUE THREAD

**Issue by magicgoose** [Homebrew/homebrew-core#9847]
https://github.com/simon-r/dr14_t.meter
Name contains a dot, so I'm not sure how to name the formula, maybe replace dot with underscore?

> DR14 T.meter is a free and open source command line tool for computing Dynamic Range of music according to the procedure used in the off-line meter released by the Pleasurize Music Foundation.

I myself currently have little time to contribute formulas and didn't learn how to do it yet, so I just thought, what if some of maintainers have similar interest. But later I'll probably try it anyway.

**Comment by MikeMcQuaid** [comment]
> maybe replace dot with underscore?

Sounds good!



> But later I'll probably try it anyway.

Great, thanks!
