### ISSUE TITLE
imagemagick failed to build on 10.x

### ISSUE THREAD

**Issue by wlbentley** [Homebrew/homebrew-core#985]
# Please follow the general troubleshooting steps first:

- [X ] Ran `brew update` and retried your prior step?
- [ X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug reports:

imagemagick fails to install

Errors here: [Gist](https://gist.github.com/wlbentley/62c9a6ec9e43b8f80b5f74e9f1a400db)
```
$ brew gist-logs imagemagick
Error: undefined method `dump_verbose_config' for Homebrew:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/gist-logs.rb:15:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:170:in `gist_logs'
/usr/local/Library/brew.rb:87:in `<main>'
```

**Comment by dunn** [comment]
Hopefully fixed by https://github.com/Homebrew/brew/commit/86fa42b36c98e482490ca347849e041ee9316011; run `brew update` and try installing again.

**Comment by mikemcquaid** [comment]
@wlbentley Please `brew update` and try again, thanks!

**Comment by mikemcquaid** [comment]
(and if that fails: rerun `brew gist-logs` too)

**Comment by wlbentley** [comment]
That does it. Thanks!
