### ISSUE TITLE
add gnupg21

### ISSUE THREAD

**Issue by bricewge** [Homebrew/homebrew-core#9851]
Since `homebrew/versions` is [deprecated](https://github.com/Homebrew/homebrew-versions/blob/master/README.md) it would be nice to add [`gnpug21`](https://github.com/Homebrew/homebrew-versions/blob/master/gnupg21.rb) to `homebrew/core` maybe by updating the current version of `gnupg2` or adding a separate recipe.

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by DomT4** [comment]
> maybe by updating the current version of gnupg2 or adding a separate recipe.

Recommend the latter, still, for now. Would personally advise not upgrading the `gnupg2` formula to the 2.1 branch until the 2.1 branch actually regularly passes its own test suite on macOS without falling apart.

**Comment by ilovezfs** [comment]
It does now.

**Comment by DomT4** [comment]
I thought it was still restricted to Yosemite and below? I would still urge some caution, especially given the changes it makes that are hard to revert, but it's on you these days so 😄.

**Comment by ilovezfs** [comment]
>I thought it was still restricted to Yosemite and below?

Fixed in head if you feel like back porting it: https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=56aa85f88f6b35fb03a2dc1a95882d49a74290e3
