### ISSUE TITLE
error msg: Unknown option "--enable-libebur128".

### ISSUE THREAD

**Issue by mixelpixel** [Homebrew/homebrew-core#9866]
- [ YES ] Ran `brew update` and retried your prior step?
- [ YES ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ How do I confirm this distinction? It appears to me this is an issue specific to `brew ffmpeg` ] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

### Bug reports:

- `brew install ffmpeg`
installs correctly,
- `brew install ffmpeg --HEAD`
installs correctly,
- `brew install ffmpeg --with-libebur128`
installs correctly, but...
- `brew install ffmpeg --with-libebur128 --HEAD`
fails:

```
$  brew install ffmpeg --with-libebur128 --HEAD
==> Using the sandbox
==> Cloning https://github.com/FFmpeg/FFmpeg.git
Updating /Users/mixelpix/Library/Caches/Homebrew/ffmpeg--git
==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/HEAD-280a40d --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=
Last 15 lines from /Users/mixelpix/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-hardcoded-tables
--enable-avresample
--cc=clang
--host-cflags=
--host-ldflags=
--enable-libebur128
--enable-libmp3lame
--enable-libx264
--enable-libxvid
--enable-opencl
--disable-lzma
--enable-vda

Unknown option "--enable-libebur128".  <------------------------ERROR MSG
See ./configure --help for available options.

READ THIS: http://docs.brew.sh/Troubleshooting.html

$  brew gist-logs ffmpeg
https://gist.github.com/8363f94eac0316d6e9abc363d269c581
$  brew doctor
Your system is ready to brew.
$  brew config
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 8faefb3a1ed44d91e6f93f903aaaa0413cf71781
Core tap last commit: 34 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.1 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /Users/mixelpix/.rbenv/shims/ruby => /Users/mixelpix/.rbenv/versions/2.3.0/bin/ruby
Java: N/A
macOS: 10.12.3-x86_64
Xcode: 8.2.1
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
$
```

### Formula Requests:

I'm not sure what to do with this section, but please let me know how I can help.

**Comment by ilovezfs** [comment]
The option was dropped in HEAD because they now have their own internal version:
```
- add internal ebur128 library, remove external libebur128 dependency
```

So just don't use that option :)

**Comment by mixelpixel** [comment]
@ilovezfs thank you. For future installs - how would I find that kind of information?

**Comment by ilovezfs** [comment]
```
brew install -i --HEAD ffmpeg
./configure --help
grep -r ebur .
```

**Comment by mixelpixel** [comment]
@ilovezfs Thank you :)

What does `-i` do? Is it a flag for interactive, ignore or something? I don't see any information on that flag in `brew install -h` and I am not sure how to read this from `man brew`

>        HOMEBREW_DEBUG_INSTALL
>               When brew install -d or brew install -i drops into a shell, HOMEBREW_DEBUG_INSTALL will be set to the name of the formula being brewed.
> 
>        HOMEBREW_DEBUG_PREFIX
>               When  brew  install  -d  or brew install -i drops into a shell, HOMEBREW_DEBUG_PREFIX will be set to the target prefix in the Cellar of the formula
>               being brewed.

**Comment by ilovezfs** [comment]
Yep it's the same as --interactive just as -d is the same as --debug

**Comment by mixelpixel** [comment]
@ilovezfs thanks again - apologies for the rudimentary questions. Similarly tho - how does one go about finding this out when the `man` pages don't specify accordingly? (I have a lot to learn, but I am trying!)

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/ARGV.rb

The ones that use `flag?` also respond to -thefirstletter as a shorthand

**Comment by mixelpixel** [comment]
@ilovezfs thank you very much!

**Comment by ilovezfs** [comment]
You're welcome!
