### ISSUE TITLE
util-linux: anywhere to be seen?

### ISSUE THREAD

**Issue by mbana** [Homebrew/homebrew-core#9885]
https://en.wikipedia.org/wiki/Util-linux

seems like this is missing. i think most people used to linux also use linux variants of sort:

```sh
$ uname -a; which column; (man column | grep --color '\-n');
Linux pc 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
/usr/bin/column
     -n      By default, the column command will merge multiple adjacent delimiters into a single delimiter when using the -t option; this option disables that behavior. This option is a Debian
```

```sh
~ $ uname -a; which column; (man column | grep --color '\-n');
Darwin MB.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin
/usr/bin/column
$ uname -a; which column; (man column | grep --color '\-t');
Darwin MB.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin
/usr/bin/column
     column [-tx] [-c columns] [-s sep] [file ...]
             -t option.
     -t      Determine the number of columns the input contains and create a
           ls -l | sed 1d) | column -t
```

thanks

**Comment by MikeMcQuaid** [comment]
Could you try and open a pull request (assuming this actually works on macOS)? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!

**Comment by mbana** [comment]
ok. i'll look through that.
why did you close it, btw?
if there way to host pre-compiled binaries. from what i've seen, it looks like it always does a `make` locally...?

**Comment by MikeMcQuaid** [comment]
> why did you close it, btw?

We don't accept formulae requests and I'm 99% sure this doesn't work on macOS.



> if there way to host pre-compiled binaries. from what i've seen, it looks like it always does a make

We provide binary packages for the three most recent versions of macOS when installed in the default location.
