### ISSUE TITLE
Red Flag - dotnet cask appears compromized! -  MD5 doesn't match library + trojan detected

### ISSUE THREAD

**Issue by TheDigitalEagle** [Homebrew/homebrew-core#99116]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 61dfa5c5a9e0d459b0155a3db68d4ed064913657
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.1.6 build 1316
Git: 2.34.1 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.2.1-x86_64
CLT: 13.3.0.0.1.1645755326
Xcode: N/A
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install dotnet`

### What happened (include all command output)?

Please note, this isn't a *bug report*, its a security concern. This is the only real template I can see to submit on. Please hear this out without closing over formatting. We were careful to ensure this isn't an obvious false positive.
We also came across a previous closed ticket on this, that I think should be reconsidered. The advice shouldn't be to blindly turn off the virus scanner since these are pre-packaged binaries from an unofficial resource. Reference: https://github.com/Homebrew/homebrew-core/issues/96664

As you can see in the below, the virus scanner flagged two files and prevented them from being installed.
To check our sanity, we manually installed the same version of dotnet 6.0.103 from Microsoft from the official pkg.

We compared the official file `Microsoft.CodeAnalysis.CSharp.Workspaces.dll` for dotnet 6.0.103 and the one that came down from brew (as seen below in the logs) `dotnet--6.0.103.monterey.bottle.tar.gz` in the location of `6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll`

File | Official 6.0.103 Microsoft.pkg & tar.gz | brew provided montery-bottle.tar.gz 
--- | --- | --- 
MD5 | 75a876b0e14df150a0aabed5393c3b4a |  8a79681b5547021efd087f1152b9a2cd

Note, these files are supposed to be the exact same:
Official Microsoft .pkg Filepath: `dotnet-sdk-6.0.103-osx-x64/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll`

Brew bottle tar.gz `dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll`

Note they are the supposed to be the same builds, the same release versions.

If you try to Google `dotnet--6.0.103.monterey.bottle.tar.gz` only a couple of locations come up as mirrors. Namely this location `https://mirrors.skyshe.cn/homebrew-bottles/dotnet-6.0.103.monterey.bottle.tar.gz` 

If you download, unzip, and so much as try to run an `ls` on the directory, the files will get automatically flagged as containing a trojan. This ONLY happens from the `dotnet--6.0.103.monterey.bottle.tar.gz` and has the same behavior as running with brew install dotnet.

```
Gen:Heur.PIF.4 quarantined
 
dotnet/6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll
```

The file MD5 and properties, as well as security vendor scans can be seen here from our testing.
https://www.virustotal.com/gui/file/3167458b0a9ab347ce86da50b29d22d0ecd11898f32259082198f156eeac0d87/detection

Please do not discard this and close without review. As long as we are going to download binaries blindly from mirrors and advice such as this https://github.com/Homebrew/homebrew-core/issues/96664#issuecomment-1065171616 recommending to disable virus scanners, this makes Homebrew pretty liable if something has been compromized.

```
Warning: Treating dotnet as a formula. For the cask, use homebrew/cask/dotnet
==> Downloading https://ghcr.io/v2/homebrew/core/dotnet/manifests/6.0.103
Already downloaded: /Users/swadmin/Library/Caches/Homebrew/downloads/f4e23ecc109e1d91e0d2f9991c6ac423fa926e81fa71a27ad4c342dfe0bb8998--dotnet-6.0.103.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/dotnet/blobs/sha256:9654a2ff03d8dec596aa334f3aacdd98dc220ac625f8cc64a9e0d61460267030
Already downloaded: /Users/swadmin/Library/Caches/Homebrew/downloads/68d00b18af82fcef7ae7d4fc265d63cca972177a84df2c535b320e0ac91fad86--dotnet--6.0.103.monterey.bottle.tar.gz
==> Pouring dotnet--6.0.103.monterey.bottle.tar.gz
cp: /private/tmp/d20220412-16283-1odzimv/dotnet/./6.0.103/libexec/sdk/6.0.103/Sdks/Microsoft.NET.Sdk/codestyle/cs/Microsoft.CodeAnalysis.CSharp.CodeStyle.dll: Operation not permitted
cp: /private/tmp/d20220412-16283-1odzimv/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
Error: Failure while executing; `cp -pR /private/tmp/d20220412-16283-1odzimv/dotnet/. /usr/local/Cellar/dotnet` exited with 1. Here's the output:
cp: /private/tmp/d20220412-16283-1odzimv/dotnet/./6.0.103/libexec/sdk/6.0.103/Sdks/Microsoft.NET.Sdk/codestyle/cs/Microsoft.CodeAnalysis.CSharp.CodeStyle.dll: Operation not permitted
cp: /private/tmp/d20220412-16283-1odzimv/dotnet/./6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll: Operation not permitted
```

### What did you expect to happen?

Properly installing with proper MD5 checksum without flagging virus scanners.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. On a OSX, x64 system. Run `brew install dotnet`
2. (optional) have Bitdefender installed.
3. Check MD5 of `dotnet/6.0.103/libexec/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll`
4. Download comparable package from Microsoft as tar.gs https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.103-macos-x64-binaries
5. Check MD5 checksum of `dotnet-sdk-6.0.103-osx-x64/sdk/6.0.103/DotnetTools/dotnet-watch/6.0.103-servicing.22124.18/tools/net6.0/any/Microsoft.CodeAnalysis.CSharp.Workspaces.dll`
6. Notice they do not match. This along with throwing security scanners, while official download resource does not, is a major red flag.
```

**Comment by Bo98** [comment]
Formulae in homebrew-core are **always** built from source before being bottled, without any exceptions (this is standard practice for many open source package managers). So a comparison with Microsoft's pkg isn't necessarily valid _unless_ compiling dotnet from source is guaranteed to produce the same binary every time which can be rare.

To demonstrate this, a build on Big Sur produces yet another MD5: 4962fac87cf01863ae06729562d71698.

If you believe the bottle is still compromised however - we'll need more information. You can try bypass the bottle and a build of source. What a build from source does (and where things are downloaded from) can be seen in `brew cat dotnet`, and a build from source build can be invoked via `brew install -s dotnet`. I reckon you'll get yet another MD5 due to the seemingly non-reproducible nature of dotnet builds.

**Comment by TheDigitalEagle** [comment]
> Please see https://docs.brew.sh/Acceptable-Casks#apps-that-bundle-malware
> You can make a pull request to remove it if you feel that it's justified.

If you take a moment to read, you will find this isn't a cask.

**Comment by TheDigitalEagle** [comment]
Well looking at `brew cat dotnet` I can see that the sha256 hashes match the tar.gz provided. One this is for sure, however, is that only the Mac builds, x86-64 or Arm, show the trojan. 
https://www.virustotal.com/gui/file/3167458b0a9ab347ce86da50b29d22d0ecd11898f32259082198f156eeac0d87/detection

While this could still be a false positive, since the binaries are being built and provided by homebrew, yet Microsoft's builds do not for the exact same release and runtime, I would think that warrants a review to make sure things *are safe* rather than blowing it off as a non-issue. I respect that stand that you are taking. But installing a resource like dotnet is going to be something people will trust blindly, especially if the recommendation is to disable all checks.

Knee jerk close questions about security if you must, but it does not look good, bottom line.

**Comment by Bo98** [comment]
> Mac builds, x86-64 or Arm

This actually gives me more confidence as each of our bottles are produced on separate isolated machines.

.NET 6.0.104 is released today, so probably the best next step here is to update to that and see if the issue persists. I tried comparing binaries byte-by-byte but the problem is that the way Microsoft build .NET is very different to the way package managers do it so it's almost impossible to compare (but is also a reasonable explanation of how it's possible that a false positive does not affect their build).

Other than that, a full build from source `brew install -s dotnet`, which takes a few hours to complete, would rule out all the "middle men" as it directly downloads the sources from Microsoft's GitHub repositories rather than use any bottles we ship.

**Comment by TheDigitalEagle** [comment]
I can give the 6.0.103 Arm a shot tonight while the machine is not in use. My main concern originally was someone may have compromised a download mirror. Its been more common lately with bad actors taking advantage of good things. Since this triggered our internal security and caused a minor scare, I really wanted to be sure this gets a good review to ensure everything is all good. I definitely do not want to be right in my suspicions! I appreciate your great response, Bo98.

**Comment by TheDigitalEagle** [comment]
> [TheDigitalEagle](https://github.com/TheDigitalEagle) No. Read the license which waives all liability on use.

If you compile and provide a binary that somehow was compromised and causing issue, yes. You would be liable. Simply saying you're not in a license doesn't remove that responsibility. It's like trucks driving down the highway that have a sticker on them saying "not responsible for broken windshields".  But, if a rock flies off their truck and breaks your windshield, it doesn't matter. The law doesn't care about the sticker.
Now, I'm not saying *you're legally liable and going to be sued* like whatever tone you're imagining I'm writing in. I am talking about responsibility. No one else but Homebrew is putting that resource there and making it available. The casks are more understandable, as well as if I add my own source for installing. 
It's clear you've come to this table automatically defensive and have decided to take things personally.

> This was not a knee jerk response. You're lucky to be dealing with maintainers and a project where they are so responsive to your issues. 

Are you saying I'm lucky to have someone not read the issue, make a quick judgement call, and then close the issue in the matter of minutes?  I'm **more** lucky Bo98 came along with a good head on their shoulders to discuss without immediately jumping into defensive mode. My statement is sound, it was a knee jerk reaction. They even admitted to making the mistake (without an apology, but thats fine).

> Virus checkers on macOS are completely unnecessary and a regular cause of false-positives in Homebrew.

I strongly suggest you take a step back and do some research on this. Especially if you are suggesting others review their security policy. Especially when we're able to reproduce the security issue only on the specific provided binaries.
If you run into a security issue, you investigate and you bring it up. If it's a false positive, that's good news for everyone. Its best practice to look into issues and raise them when they come up from a security standpoint. If you always ignore that fire alarm assuming it's a drill, one day you'll be sorry.
In all due respect, your stance on "its a mac, macs don't get viruses" is concerning. I really really do strongly encourage you look into the issue around malware/viruses/trojans that do exist in both Mac and Linux/Unix systems. Please, I urge you. Don't continue with this attitude. The fact there may be frequent false positives with Homebrew isn't even a reason to take on this attitude.

> As a general note, I don't really appreciate your tone referring to Homebrew being liable or responses being knee jerk. Please adjust it accordingly in future, thanks.

Today, I think what I've seen here is you came to this discussion looking for an argument fueled by emotion. Bo98 already had this handled and has done so in a good way. I don't know if you're having a bad day, or if you're misreading things, or if you just feel personally hurt by this issue ticket. I did not intend to offend you, so I apologize in doing so.

**Comment by MikeMcQuaid** [comment]
> If you compile and provide a binary that somehow was compromised and causing issue, yes. You would be liable.

No. Again: read our license. I trust the multiple IP lawyers who agree with this claim more than you, sorry. If you don't agree: you lose your right to use Homebrew. Genuinely: you and  your organisation should stop using Homebrew if you do not agree with this.

> I am talking about responsibility.

We waive responsibility. Read https://mikemcquaid.com/2018/03/19/open-source-maintainers-owe-you-nothing/ if this is unclear.

> It's clear you've come to this table automatically defensive and have decided to take things personally.

Alternatively: your communication has resulted in this response.

> Are you saying I'm lucky to have someone not read the issue, make a quick judgement call, and then close the issue in the matter of minutes?

Yes. In many projects this sort of issue would not even be responded to by a human.

> My statement is sound, it was a knee jerk reaction.

I've asked you to adjust your tone. Please do so.

> In all due respect, your stance on "its a mac, macs don't get viruses" is concerning.

I didn't say this. Apple provides virus protection as part of the OS. Microsoft does in recent versions of Windows, too.

> Today, I think what I've seen here is you came to this discussion looking for an argument fueled by emotion.

I am a human. Humans have emotions. 

I am responding to someone making some pretty bold claims about the security practises of this project. I am defending the (independently audited) security practises of this project.

> I did not intend to offend you, so I apologize in doing so.

Life tip: put this at the top of comments like this and consider avoiding additional accusations.

This apology is pretty poor in context. That said, I appreciate it regardless.

**Comment by carlocab** [comment]
> It's like trucks driving down the highway that have a sticker on them saying "not responsible for broken windshields". But, if a rock flies off their truck and breaks your windshield, it doesn't matter.

No, it is not. Vehicles driving on the highway along the truck do not choose to do this, nor do they stand to benefit from doing this. Using Homebrew is a choice, and choosing to use Homebrew requires agreeing to the license.

**Comment by MikeMcQuaid** [comment]
> I think my use in the words "liable" was a poor choice. By definition, it means "the state of being responsible for something".

<img width="710" alt="Screenshot 2022-04-13 at 19 24 59" src="https://user-images.githubusercontent.com/125011/163245973-7b6e717b-5b8b-4ac4-9297-cbe6cab3c207.png">

Indeed. I don't think our assumption that you may have meant in the legal sense is unreasonable considering the above.

> Really the "bad look" I was referring to at all was having a security concern practically auto-closed. It's not a good look from a user standpoint.

This is because we have zero faith in these antivirus alerts because literally all alerts for Homebrew bottles have been false positives. Additionally, we have a proper security disclosure process that wasn't followed here. 

It would be more alarming to our users to keep this open for investigation; this would indicate we think there's something concern that warrants investigation and that a security issue is pending rather than resolved (which it was when this was closed).

I'd suggest that we run our project's issue tracker how we see fit and you do how you see fit for your projects.

> Can we evaluate it to ensure this is a false positive and there hasn't been some man-in-the-middle attack?

There can't be a man-in-the-middle attack unless this person compromised your connection to GitHub Packages and the homebrew-core git repository. I say this not to be pedantic but to again illustrate why this was closed quickly.

> But I will be completely honest and say I wasn't happy to have the ticket closed

Yes, you've made this clear. As we've hopefully made clear, we haven't been happy with the way this was disclosed, the repeated false reports like this we get due to substandard antivirus vendors on macOS and the way you've responded to it being closed.

Please address your communication in future issues and consider re-reading our Code of Conduct. Not being happy is not an excuse for poor behaviour.

**Comment by TheDigitalEagle** [comment]
I definitely didn't say the assumption was unreasonable. The funny and difficult thing about English, is even we are both native speakers, we can disagree on the use of a word; especially with reading text without hearing someone voice. 

https://en.m.wiktionary.org/wiki/liability

> I say this not to be pedantic but to again illustrate why this was closed quickly.

It was closed quickly with a reason that was incorrect. At that moment, he thought I was talking about casks. Fair enough to your reasoning why you would close it.

I will pull back from this conversation. Unfortunately it seems we won't see eye to eye on what was being said. I do thank you for your time.
