### ISSUE TITLE
Fabric formula with PYTONPATH from pip and brew

### ISSUE THREAD

**Issue by rverchere** [Homebrew/homebrew-core#9917]
### Bug reports:

Installing `fabric` formula does not add `/usr/local/lib/python2.7/site-packages` in the PYTHONPATH, so every python modules installed using pip from homebrew are not taken in account.

Then, when I try to use a `fabfile.py`with some import, it does not work (`importError`), whereas it's ok from a pure python script.

```
$ brew config
HOMEBREW_VERSION: 1.1.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: 664d0c67d5947605c914c4c56ebcfaa80cb6eca0
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core.git
Core tap HEAD: a9002c8d72797ecf2b092868d4eeceb110691442
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_91, 1.6.0_65-b14-468
macOS: 10.12.3-x86_64
Xcode: N/A
CLT: 8.2.0.0.1.1480973914
X11: 2.7.11 => /opt/X11
```

```
$ brew doctor
Your system is ready to brew.
```

### Formula Requests:

When installing `fabric`, update the `PYTHONPATH` used to start the `fab` program from the following example:
```
cat /usr/local/bin/fab
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/fabric/1.13.1_1/libexec/lib/python2.7/site-packages:/usr/local/Cellar/fabric/1.13.1_1/libexec/vendor/lib/python2.7/site-packages" exec "/usr/local/Cellar/fabric/1.13.1_1/libexec/bin/fab" "$@"
```

To this:
```
cat /usr/local/bin/fab
#!/bin/bash
PYTHONPATH="/usr/local/Cellar/fabric/1.13.1_1/libexec/lib/python2.7/site-packages:/usr/local/Cellar/fabric/1.13.1_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages" exec "/usr/local/Cellar/fabric/1.13.1_1/libexec/bin/fab" "$@"
```

Thanks for your support!

**Comment by MikeMcQuaid** [comment]
> Installing fabric formula does not add /usr/local/lib/python2.7/site-packages in the PYTHONPATH, so every python modules installed using pip from homebrew are not taken in account.

This is intentional. These packages should be installed to `libexec/vendor/lib/python2.7/site-packages` within the Cellar instead or (better) added to the formulae as new `resource`s. Could you try and open a pull request? [This document](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) should help and we're happy to walk you through anything else.

Thanks!
