### ISSUE TITLE
Build librdkafka from HEAD source, not old source

### ISSUE THREAD

**Issue by mcandre** [Homebrew/homebrew-core#9922]
How do we configure the librdkafka formula to get the source from edenhill/librdkafka, rather than old source bundles? confluentinc/confluent-kafka-go needs librdkafka 0.9.4 (HEAD), but the librdkafka formula is currently pinned at 0.9.3.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/librdkafka.rb

**Comment by bfontaine** [comment]
Use `brew install librdkafka --HEAD`. Upstream hasn’t released 0.9.4 yet.
