### ISSUE TITLE
Pull request tests fail for multiple levels of dependencies

### ISSUE THREAD

**Issue by nohal** [Homebrew/homebrew-core#99245]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
- There is an ABI change in `wxwidgets` 3.1.6 leading to `diff-pdf` needing rebuild.
- Multiple formulas depend on `wxwidgets` and have very weird linking info on Linux leading to their failure on `wxwidgets` version bump, one of them is `erlang`
- Once the `revision` number of `erlang` is increased, all the formulas depending on `erlang` fail in the automated tests, regardless of being untouched or having their own `revision` increased as well (in that case they fail even on macOS, where they were completely OK without being rebuilt at all)
- There does not seem to be any documented way out of this situation (Probably being able to divide this operarion into two steps would be enough, but there does not seem to be any way to submit a pull request not being refused by the automated tests to this project)

The whole history leading to this situation can be observed in https://github.com/Homebrew/homebrew-core/pull/99206/commits
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I am trying to bump the wxWidgets version from 3.1.5 to 3.1.6

### What happened (include all command output)?

Everything works on macOS, but automated tests on the pull requests fail on Linux leading to endless chain of problems without any apparent resolution compatible with the processes adopted by this porject.

### What did you expect to happen?

Be able to perform the version bump of the `wxwidgets` formula and rebuild just the packages really affected by the ABI change.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
Submit https://github.com/Homebrew/homebrew-core/pull/99206 and react to the failures of the automated tests.
```

**Comment by SMillerDev** [comment]
> Pull request tests fail for multiple levels of dependencies

This is almost a daily occurrence and they haven't been failing anywhere else so this issue is a bit hyperbolic. I'll close this and continue the conversation in the PR.
