### ISSUE TITLE
Different shasum for freetype formula

### ISSUE THREAD

**Issue by vladkens** [Homebrew/homebrew-core#994]
```
➜  ~ brew install wine
==> Installing dependencies for wine: freetype, jpeg, pkg-config, libtool, libusb, libusb-compat, fontconfig, libtiff, gd, libgphoto2, little-cms2, jasper, libicns, makedepe
==> Installing wine dependency: freetype
==> Downloading https://downloads.sf.net/project/freetype/freetype2/2.6.3/freetype-2.6.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/freetype-2.6.3.tar.bz2
Error: SHA256 mismatch
Expected: 371e707aa522acf5b15ce93f11183c725b8ed1ee8546d7b3af549863045863a2
Actual: 9954a5d14686244d61f292b9ed4d20cdc4e837f56dc27c19229a109b582aa36a
Archive: /Library/Caches/Homebrew/freetype-2.6.3.tar.bz2
To retry an incomplete download, remove the file above.
```

In file https://github.com/Homebrew/homebrew-core/blob/master/Formula/freetype.rb 

url param check sum is `9954a5d14686244d61f292b9ed4d20cdc4e837f56dc27c19229a109b582aa36a`
miror param check sum is `371e707aa522acf5b15ce93f11183c725b8ed1ee8546d7b3af549863045863a2`

**Comment by UniqMartin** [comment]
I just tried and for me the file downloads correctly. Can you remove `/Library/Caches/Homebrew/freetype-2.6.3.tar.bz2` (maybe there was an issue with a previous download) and then retry?

If this doesn't work: Are you using a proxy to access the web or have you problems accessing SourceForge? Can you try and download the file with a web browser? If that works, do you get a file that is 1,753,083 bytes in size?

**Comment by mikemcquaid** [comment]
> Can you remove /Library/Caches/Homebrew/freetype-2.6.3.tar.bz2 (maybe there was an issue with a previous download) and then retry?

An alternative to this is `brew fetch --retry freetype`

**Comment by vladkens** [comment]
Guys, this is because sourceforge for Crimea IP's downloads pdf file with treatment of Barack Obama instead program archive. Over VPN all is good.
Thanks.
