### ISSUE TITLE
Cannot upgrade PostgreSQL 9.4.5 to 9.5.2 w/ Postgis

### ISSUE THREAD

**Issue by dlo** [Homebrew/homebrew-core#996]
When upgrading from PostgreSQL 9.4.5 w/ Postgis to PostgreSQL 9.5.2, pg_upgrade fails due to the following error:

```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for reg* system OID user data types                ok
Checking for contrib/isn with bigint-passing mismatch       ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok
Checking for presence of required libraries                 fatal

Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt

Failure, exiting
```

cat loadable_libraries.txt →

```
Could not load library "$libdir/postgis-2.2"
ERROR:  incompatible library "/usr/local/lib/postgresql/postgis-2.2.so": version mismatch
DETAIL:  Server is version 9.5, library is version 9.4.

Could not load library "$libdir/rtpostgis-2.2"
ERROR:  incompatible library "/usr/local/lib/postgresql/rtpostgis-2.2.so": version mismatch
DETAIL:  Server is version 9.5, library is version 9.4.
```

Explanation: all Homebrew PostgreSQL installations share the same `$libdir`, which means all postgis dll's are installed in the same place. It's therefore impossible to have two versions of Postgis (each linked against different PostgreSQL versions) installed in `/usr/local/lib/postgresql` simultaneously, which is necessary for pg_upgrade to migrate successfully.

Installing postgis with `brew install postgis`, linked against PostgreSQL 9.5.2, generates another with pg_upgrade, since PostgreSQL 9.4.5 relies upon 9.4.5-linked Postgis dll's to dump the data files. The upgrade process fails earlier with the following:

```
command: "/usr/local/Cellar/postgresql/9.5.2/bin/pg_dump" --host "/usr/local/var" --port 50432 --username "dan" --schema-only --quote-all-identifiers --binary-upgrade --format=custom  --file="pg_upgrade_dump_16384.custom" "dan" >> "pg_upgrade_dump_16384.log" 2>&1
pg_dump: [archiver (db)] query failed: ERROR:  incompatible library "/usr/local/lib/postgresql/postgis-2.2.so": version mismatch
DETAIL:  Server is version 9.4, library is version 9.5.
```

**Comment by mikemcquaid** [comment]
> Explanation: all Homebrew PostgreSQL installations share the same $libdir, which means all postgis dll's are installed in the same place. It's therefore impossible to have two versions of Postgis (each linked against different PostgreSQL versions) installed in /usr/local/lib/postgresql simultaneously, which is necessary for pg_upgrade to migrate successfully.

What would you suggest as a fix?

**Comment by dlo** [comment]
My only suggestion is that we change the `$libdir` to be installation specific, rather than `/usr/local/lib/postgresql`. Not sure what the ramifications of that might be, though.

**Comment by joachimbaumgartner** [comment]
Same happened here. Tried to upgrade from Postgres 9.1 (with postgis-2.0) to Postgres 9.5 (with postgis-2.2). Had to copy postgis-2.0 libraries manually to the lib directory of the new 9.5 installation. I receive the following when calling  /usr/lib/postgresql/9.5/bin/pg_upgrade:
---
postgres@dev-kdb0:~$ cat loadable_libraries.txt 
Could not load library "$libdir/postgis-2.0"
ERROR:  incompatible library "/usr/lib/postgresql/9.5/lib/postgis-2.0.so": version mismatch
DETAIL:  Server is version 9.5, library is version 9.1.

Could not load library "$libdir/rtpostgis-2.0"
ERROR:  incompatible library "/usr/lib/postgresql/9.5/lib/rtpostgis-2.0.so": version mismatch
DETAIL:  Server is version 9.5, library is version 9.1.
---

I would suggest to create two new options for pg_upgrade:
-l (lower letter l like in "love") = old cluster library directory
-L (upper letter l like in "Love") = new cluster library directory.

I have no other idea to fix this.

**Comment by joachimbaumgartner** [comment]
No idea why the text above is printed so large, sorry for that.

**Comment by MikeMcQuaid** [comment]
@dlo Makes sense to me. Could you try and open a pull request? [This document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged) should help and I'm happy to walk you through anything else.

Thanks!

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
