### ISSUE TITLE
node installed from homebrew behaves differently from node installed from nvm/nodenv

### ISSUE THREAD

**Issue by jcesarmobile** [Homebrew/homebrew-core#99688]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.
```

### Verification

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

In [Capacitor](https://github.com/ionic-team/capacitor) we use node's spawn to run `./gradlew` command, but a few users [have reported](https://github.com/ionic-team/capacitor/issues/5545) that the command is returning a ENOENT when they use node installed from homebrew, while using node installed from nvm/nodenv works fine.

I have simplified [in this gist](https://gist.github.com/jcesarmobile/63c1bec9201b9ae1ba92bec646cadd52) the code we use to help debug the issue. It's just a spawn call that runs `./gradlew`.
When it's run from homebrew's node it calls the error function with ENOENT and the close function with -2 code, but the gradle execution finished correctly with

BUILD SUCCESSFUL in 490ms
1 actionable task: 1 executed

When using node from nvm/nodenv it doesn't call the error function and the close is called with code 0

### What happened (include all command output)?

it calls the error function with ENOENT and the close function with -2 code, but the gradle execution finished correctly with

BUILD SUCCESSFUL in 490ms
1 actionable task: 1 executed

### What did you expect to happen?

it doesn't call the error function and close is called with code 0 as the gradlew command succeeded. 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install node
git clone https://github.com/ionic-team/capacitor-testapp
cd capacitor-testapp
npm install
npm run build
npx cap sync android
npx cap run android
```
It will fail with `ERR_SUBPROCESS_COMMAND_NOT_FOUND`

to fix it
```
brew uninstall node
// install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
// install node 17 or any other version from nvm
nvm install 17
npx cap run android
```
```

**Comment by Bo98** [comment]
This is probably a libuv bug, which will be fixed in 1.44.2: https://github.com/libuv/libuv/commit/7c9b3938df9cc1eb9e1efec249a171c31b1a9a3a. We could apply the patch onto 1.44.1 if it's urgent however.

**Comment by carlocab** [comment]
I'm happy to patch `libuv` if it'll fix this -- this seems like something that could affect lots of users, and the error message is pretty confusing.

@jcesarmobile, could you try applying this patch and see if it helps?
```diff
diff --git a/Formula/libuv.rb b/Formula/libuv.rb
index bec8d160006..b9e1ac43525 100644
--- a/Formula/libuv.rb
+++ b/Formula/libuv.rb
@@ -26,6 +26,11 @@ class Libuv < Formula
   depends_on "pkg-config" => :build
   depends_on "sphinx-doc" => :build
 
+  patch do
+    url "https://github.com/libuv/libuv/commit/7c9b3938df9cc1eb9e1efec249a171c31b1a9a3a.patch?full_index=1"
+    sha256 "5fb73337d841504ad514709146ba6715f6a6f91e69a9b07b48dee4e9b6617bdc"
+  end
+
   def install
     # This isn't yet handled by the make install process sadly.
     cd "docs" do
```

You should apply it to `$(brew --repository homebrew/core)/Formula/libuv.rb`, then do `brew reinstall -s libuv`. You can then test this against your example to see if it helps.

Don't forget to undo your changes (`git -C "$(brew --repository homebrew/core)" restore Formula/libuv.rb`) to avoid `brew update` problems later on when you're done.

**Comment by jcesarmobile** [comment]
Yeah, I confirm that patch fixes the problem.

**Comment by carlocab** [comment]
Should be fixed by a
```
brew update && brew upgrade libuv
```
