### ISSUE TITLE
Segfault in doxygen 1.8.13

### ISSUE THREAD

**Issue by kolis** [Homebrew/homebrew-core#9969]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with specific formulae and not Homebrew/brew? If it's a general Homebrew/brew problem please file this issue at https://github.com/Homebrew/brew/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:
Doxygen 1.8.13 segfaults, reverting to 1.8.12 fix the problem. I followed this change, https://github.com/omnia-md/conda-recipes/pull/687/files found from https://github.com/pandegroup/openmm/issues/1714#issuecomment-275504066

after which the segfault disappears.

I get the segfault during
```
Generating XML output...
```

```
$ brew config
HOMEBREW_VERSION: 1.1.9-7-g01c137207
ORIGIN: https://github.com/Homebrew/brew
HEAD: 01c13720749d9c4d0050a5bca943543d5bd8a9de
Last commit: 11 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f36e920aba81770f0459de60a399c2a7bd9a9c1c
Core tap last commit: 52 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 12-core 64-bit haswell
Homebrew Ruby: 2.0.0-p481
Clang: 7.0 build 700
Git: 2.11.1 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_25
macOS: 10.10.5-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
X11: 2.7.11 => /opt/X11
```

```
$ brew gist-logs doxygen
Error: No logs.
```

**Comment by ilovezfs** [comment]
Did anyone report this to ... doxygen?

**Comment by ilovezfs** [comment]
I'm wondering if it's this: https://github.com/doxygen/doxygen/pull/555

**Comment by ilovezfs** [comment]
@kolis Do you mind testing if it happens if you use
```
brew install --HEAD doxygen
```

**Comment by kolis** [comment]
Yes, that works! 
```
$ doxygen -v        
1.8.14
```
and runs without segfault

**Comment by ilovezfs** [comment]
@kolis OK it should be fixed now if you
```
brew uninstall doxygen
brew update
brew install doxygen
```
